var searchData=
[
  ['raycrossingcounter',['RayCrossingCounter',['../classgeos_1_1algorithm_1_1RayCrossingCounter.html',1,'geos::algorithm']]],
  ['rectangle',['Rectangle',['../classgeos_1_1operation_1_1intersection_1_1Rectangle.html',1,'geos::operation::intersection']]],
  ['rectanglecontains',['RectangleContains',['../classgeos_1_1operation_1_1predicate_1_1RectangleContains.html',1,'geos::operation::predicate']]],
  ['rectangleintersection',['RectangleIntersection',['../classgeos_1_1operation_1_1intersection_1_1RectangleIntersection.html',1,'geos::operation::intersection']]],
  ['rectangleintersectionbuilder',['RectangleIntersectionBuilder',['../classgeos_1_1operation_1_1intersection_1_1RectangleIntersectionBuilder.html',1,'geos::operation::intersection']]],
  ['rectangleintersects',['RectangleIntersects',['../classgeos_1_1operation_1_1predicate_1_1RectangleIntersects.html',1,'geos::operation::predicate']]],
  ['relatecomputer',['RelateComputer',['../classgeos_1_1operation_1_1relate_1_1RelateComputer.html',1,'geos::operation::relate']]],
  ['relatenode',['RelateNode',['../classgeos_1_1operation_1_1relate_1_1RelateNode.html',1,'geos::operation::relate']]],
  ['relatenodefactory',['RelateNodeFactory',['../classgeos_1_1operation_1_1relate_1_1RelateNodeFactory.html',1,'geos::operation::relate']]],
  ['relatenodegraph',['RelateNodeGraph',['../classgeos_1_1operation_1_1relate_1_1RelateNodeGraph.html',1,'geos::operation::relate']]],
  ['relateop',['RelateOp',['../classgeos_1_1operation_1_1relate_1_1RelateOp.html',1,'geos::operation::relate']]],
  ['repeatedpointtester',['RepeatedPointTester',['../classgeos_1_1operation_1_1valid_1_1RepeatedPointTester.html',1,'geos::operation::valid']]],
  ['rescaler',['ReScaler',['../classgeos_1_1noding_1_1ScaledNoder_1_1ReScaler.html',1,'geos::noding::ScaledNoder']]],
  ['rightmostedgefinder',['RightmostEdgeFinder',['../classgeos_1_1operation_1_1buffer_1_1RightmostEdgeFinder.html',1,'geos::operation::buffer']]],
  ['robustdeterminant',['RobustDeterminant',['../classgeos_1_1algorithm_1_1RobustDeterminant.html',1,'geos::algorithm']]],
  ['root',['Root',['../classgeos_1_1index_1_1quadtree_1_1Root.html',1,'geos::index::quadtree']]],
  ['root',['Root',['../classgeos_1_1index_1_1bintree_1_1Root.html',1,'geos::index::bintree']]]
];
