PDAL: pdal/java/native/src/include/Accessors.hpp File Reference
Accessors.hpp File Reference
#include <jni.h>
#include <string>
Functions
jfieldID getHandleField (JNIEnv *, jobject)
template<typename T >
T * getHandle (JNIEnv *env, jobject obj)
template<typename T >
void setHandle (JNIEnv *env, jobject obj, T *t)
Function Documentation
template<typename T > T* getHandle (JNIEnv * env, jobject obj)
Definition at line 43 of file Accessors.hpp.
References getHandleField().
jfieldID getHandleField (JNIEnv * , jobject)
Definition at line 36 of file Accessors.cpp.
References c.
Referenced by getHandle(), and setHandle().
template<typename T > void setHandle (JNIEnv * env, jobject obj, T * t)
Definition at line 50 of file Accessors.hpp.
References getHandleField().
Referenced by Java_io_pdal_Pipeline_getPointViews(), Java_io_pdal_Pipeline_initialise(), Java_io_pdal_PointView_layout(), and Java_io_pdal_PointViewIterator_next().