PDAL: pdal/test/unit/filters/AdditionalMergeTest.cpp File Reference
AdditionalMergeTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include "Support.hpp"
#include <pdal/PipelineManager.hpp>
#include <pdal/util/FileUtils.hpp>
#include <io/LasReader.hpp>
#include <io/LasWriter.hpp>
#include <filters/DecimationFilter.hpp>
#include <filters/MergeFilter.hpp>
Functions
TEST (AdditionalMergeTest, merge_filter_and_reader_with_manager)
TEST (AdditionalMergeTest, merge_reader_and_filter_with_manager)
TEST (AdditionalMergeTest, merge_filter_and_reader_without_manager)
TEST (AdditionalMergeTest, merge_reader_and_filter_without_manager)
TEST (AdditionalMergeTest, filter_and_reader_writer_inputs_with_manager)
TEST (AdditionalMergeTest, reader_and_filter_writer_inputs_with_manager)
TEST (AdditionalMergeTest, filter_and_reader_writer_inputs_without_manager)
TEST (AdditionalMergeTest, reader_and_filter_writer_inputs_without_manager)
TEST (AdditionalMergeTest, merge_two_filters_with_manager)
TEST (AdditionalMergeTest, merge_two_filters_without_manager)
TEST (AdditionalMergeTest, two_filters_writer_inputs_with_manager)
TEST (AdditionalMergeTest, two_filters_writer_inputs_without_manager)
Function Documentation
TEST (AdditionalMergeTest , merge_filter_and_reader_with_manager)
Definition at line 48 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::PipelineManager::execute(), hag::filter(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (AdditionalMergeTest , merge_reader_and_filter_with_manager)
Definition at line 86 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::PipelineManager::execute(), hag::filter(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (AdditionalMergeTest , merge_filter_and_reader_without_manager)
Definition at line 124 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::size().
TEST (AdditionalMergeTest , merge_reader_and_filter_without_manager)
Definition at line 165 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::size().
TEST (AdditionalMergeTest , filter_and_reader_writer_inputs_with_manager)
Definition at line 206 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::PipelineManager::execute(), hag::filter(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (AdditionalMergeTest , reader_and_filter_writer_inputs_with_manager)
Definition at line 241 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::PipelineManager::execute(), hag::filter(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (AdditionalMergeTest , filter_and_reader_writer_inputs_without_manager)
Definition at line 276 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (AdditionalMergeTest , reader_and_filter_writer_inputs_without_manager)
Definition at line 318 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (AdditionalMergeTest , merge_two_filters_with_manager)
Definition at line 360 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::PipelineManager::execute(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (AdditionalMergeTest , merge_two_filters_without_manager)
Definition at line 405 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::size().
TEST (AdditionalMergeTest , two_filters_writer_inputs_with_manager)
Definition at line 453 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::PipelineManager::execute(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (AdditionalMergeTest , two_filters_writer_inputs_without_manager)
Definition at line 495 of file AdditionalMergeTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().