var annotated_dup =
[
    [ "anonymous_namespace{QuadIndex.cpp}", "namespaceanonymous__namespace_02QuadIndex_8cpp_03.html", "namespaceanonymous__namespace_02QuadIndex_8cpp_03" ],
    [ "anonymous_namespace{SpatialReference.cpp}", "namespaceanonymous__namespace_02SpatialReference_8cpp_03.html", "namespaceanonymous__namespace_02SpatialReference_8cpp_03" ],
    [ "embed", "namespaceembed.html", "namespaceembed" ],
    [ "libpdaljava", "namespacelibpdaljava.html", "namespacelibpdaljava" ],
    [ "libpdalpython", "namespacelibpdalpython.html", "namespacelibpdalpython" ],
    [ "nanoflann", "namespacenanoflann.html", "namespacenanoflann" ],
    [ "pcl", "namespacepcl.html", "namespacepcl" ],
    [ "pdal", "namespacepdal.html", "namespacepdal" ],
    [ "test", "namespacetest.html", "namespacetest" ],
    [ "App", "classApp.html", "classApp" ],
    [ "Arg", "namespace_3globalScope_4.html#classArg", null ],
    [ "CompressionStream", "classCompressionStream.html", "classCompressionStream" ],
    [ "GDALReaderTypeTest", "classGDALReaderTypeTest.html", "classGDALReaderTypeTest" ],
    [ "GreyhoundReaderTest", "classGreyhoundReaderTest.html", "classGreyhoundReaderTest" ],
    [ "jsonWithPredicate", "classjsonWithPredicate.html", null ],
    [ "jsonWithProgrammable", "classjsonWithProgrammable.html", null ],
    [ "NITFBandInfo", "nitflib_8h.html#structNITFBandInfo", "nitflib_8h_structNITFBandInfo" ],
    [ "NITFColormapRecord", "nitflib_8h.html#structNITFColormapRecord", "nitflib_8h_structNITFColormapRecord" ],
    [ "NITFDES", "nitflib_8h.html#structNITFDES", "nitflib_8h_structNITFDES" ],
    [ "NITFFile", "nitflib_8h.html#structNITFFile", "nitflib_8h_structNITFFile" ],
    [ "NITFICHIPBInfo", "nitflib_8h.html#structNITFICHIPBInfo", "nitflib_8h_structNITFICHIPBInfo" ],
    [ "NITFImage", "nitflib_8h.html#structNITFImage", "nitflib_8h_structNITFImage" ],
    [ "NITFLocation", "nitflib_8h.html#structNITFLocation", "nitflib_8h_structNITFLocation" ],
    [ "NITFRPC00BInfo", "nitflib_8h.html#structNITFRPC00BInfo", "nitflib_8h_structNITFRPC00BInfo" ],
    [ "NITFSegmentInfo", "nitflib_8h.html#structNITFSegmentInfo", "nitflib_8h_structNITFSegmentInfo" ],
    [ "NITFSeries", "nitflib_8h.html#structNITFSeries", "nitflib_8h_structNITFSeries" ],
    [ "OCITest", "classOCITest.html", "classOCITest" ],
    [ "PF_PluginAPI_Version", "plugin_8hpp.html#structPF__PluginAPI__Version", "plugin_8hpp_structPF__PluginAPI__Version" ],
    [ "PF_RegisterParams", "plugin_8hpp.html#structPF__RegisterParams", "plugin_8hpp_structPF__RegisterParams" ],
    [ "PgpointcloudWriterTest", "classPgpointcloudWriterTest.html", "classPgpointcloudWriterTest" ],
    [ "Point", "GDALReaderTest_8cpp.html#structPoint", "GDALReaderTest_8cpp_structPoint" ],
    [ "PredicateFilterTest", "classPredicateFilterTest.html", "classPredicateFilterTest" ],
    [ "ProgramArgs", "namespace_3globalScope_4.html#classProgramArgs", [
      [ "Stores", "namespace_3globalScope_4.html#classProgramArgs_1_1Stores", null ]
    ] ],
    [ "PythonFilterTest", "classPythonFilterTest.html", "classPythonFilterTest" ],
    [ "SplitFilter", "classSplitFilter.html", "classSplitFilter" ],
    [ "Support", "classSupport.html", "classSupport" ],
    [ "XYZIRGBA", "point__types_8hpp.html#structXYZIRGBA", "point__types_8hpp_structXYZIRGBA" ]
];