PDAL: pdal/test/unit/BoundsTest.cpp File Reference
BoundsTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/util/Bounds.hpp>
#include <pdal/PDALUtils.hpp>
Functions
TEST (BoundsTest, test_ctor)
TEST (BoundsTest, test_equals)
TEST (BoundsTest, test_copy)
TEST (BoundsTest, test_accessor)
TEST (BoundsTest, test_clip)
TEST (BoundsTest, test_intersect)
TEST (BoundsTest, test_grow)
TEST (BoundsTest, test_static)
TEST (BoundsTest, test_invalid)
TEST (BoundsTest, test_output)
TEST (BoundsTest, test_input)
TEST (BoundsTest, test_parse)
TEST (BoundsTest, test_wkt)
TEST (BoundsTest, test_json)
TEST (BoundsTest, test_2d_input)
TEST (BoundsTest, test_precisionloss)
TEST (BoundsTest, b1)
TEST (BoundsTest, b2)
TEST (BoundsTest, bounds_insertion)
Function Documentation
TEST (BoundsTest , test_ctor)
Definition at line 41 of file BoundsTest.cpp.
References pdal::BOX3D::clear(), and pdal::BOX3D::empty().
TEST (BoundsTest , test_equals)
Definition at line 51 of file BoundsTest.cpp.
TEST (BoundsTest , test_copy)
Definition at line 73 of file BoundsTest.cpp.
TEST (BoundsTest , test_accessor)
Definition at line 84 of file BoundsTest.cpp.
References pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
TEST (BoundsTest , test_clip)
Definition at line 101 of file BoundsTest.cpp.
References pdal::BOX2D::clip(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, and pdal::BOX2D::miny.
TEST (BoundsTest , test_intersect)
Definition at line 130 of file BoundsTest.cpp.
References pdal::BOX2D::contains(), and pdal::BOX2D::overlaps().
TEST (BoundsTest , test_grow)
Definition at line 152 of file BoundsTest.cpp.
References pdal::BOX2D::grow().
TEST (BoundsTest , test_static)
Definition at line 164 of file BoundsTest.cpp.
References pdal::BOX2D::getDefaultSpatialExtent(), pdal::BOX3D::getDefaultSpatialExtent(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
TEST (BoundsTest , test_invalid)
Definition at line 183 of file BoundsTest.cpp.
References pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
TEST (BoundsTest , test_output)
Definition at line 202 of file BoundsTest.cpp.
TEST (BoundsTest , test_input)
Definition at line 221 of file BoundsTest.cpp.
TEST (BoundsTest , test_parse)
Definition at line 232 of file BoundsTest.cpp.
TEST (BoundsTest , test_wkt)
Definition at line 246 of file BoundsTest.cpp.
References b, and pdal::BOX2D::toWKT().
TEST (BoundsTest , test_json)
Definition at line 256 of file BoundsTest.cpp.
References b, and pdal::BOX2D::toGeoJSON().
TEST (BoundsTest , test_2d_input)
Definition at line 263 of file BoundsTest.cpp.
TEST (BoundsTest , test_precisionloss)
Definition at line 272 of file BoundsTest.cpp.
References pdal::BOX2D::minx.
TEST (BoundsTest , b1)
Definition at line 291 of file BoundsTest.cpp.
References b.
TEST (BoundsTest , b2)
Definition at line 309 of file BoundsTest.cpp.
References b, pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
TEST (BoundsTest , bounds_insertion)
Definition at line 334 of file BoundsTest.cpp.
References b.