PDAL: pdal/test/unit/io/BPFTest.cpp File Reference
BPFTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <array>
#include <pdal/Filter.hpp>
#include <pdal/PointView.hpp>
#include <pdal/util/Utils.hpp>
#include <pdal/util/FileUtils.hpp>
#include <io/BpfReader.hpp>
#include <io/BpfWriter.hpp>
#include <io/BufferReader.hpp>
#include "Support.hpp"
Namespaces
anonymous_namespace{BPFTest.cpp}
Functions
template<typename LeftIter , typename RightIter >
::testing::AssertionResult anonymous_namespace{BPFTest.cpp}::CheckEqualCollections (LeftIter left_begin, LeftIter left_end, RightIter right_begin)
void anonymous_namespace{BPFTest.cpp}::test_file_type_view (const std::string &filename)
void anonymous_namespace{BPFTest.cpp}::test_file_type_stream (const std::string &filename)
void anonymous_namespace{BPFTest.cpp}::test_file_type (const std::string &filename)
void anonymous_namespace{BPFTest.cpp}::test_roundtrip (Options &writerOps)
TEST (BPFTest, test_point_major)
TEST (BPFTest, test_dim_major)
TEST (BPFTest, test_byte_major)
TEST (BPFTest, roundtrip_byte)
TEST (BPFTest, roundtrip_dimension)
TEST (BPFTest, roundtrip_point)
TEST (BPFTest, roundtrip_scaling)
TEST (BPFTest, extra_bytes)
TEST (BPFTest, bundled)
TEST (BPFTest, inspect)
TEST (BPFTest, mueller)
TEST (BPFTest, flex)
TEST (BPFTest, flex2)
TEST (BPFTest, outputdims)
TEST (BPFTest, autoutm)
Function Documentation
TEST (BPFTest , test_point_major)
Definition at line 245 of file BPFTest.cpp.
References Support::datapath(), and anonymous_namespace{BPFTest.cpp}::test_file_type().
TEST (BPFTest , test_dim_major)
Definition at line 251 of file BPFTest.cpp.
References Support::datapath(), and anonymous_namespace{BPFTest.cpp}::test_file_type().
TEST (BPFTest , test_byte_major)
Definition at line 257 of file BPFTest.cpp.
References Support::datapath(), pdal::TEST(), and anonymous_namespace{BPFTest.cpp}::test_file_type().
TEST (BPFTest , roundtrip_byte)
Definition at line 285 of file BPFTest.cpp.
References pdal::Options::add(), and anonymous_namespace{BPFTest.cpp}::test_roundtrip().
TEST (BPFTest , roundtrip_dimension)
Definition at line 293 of file BPFTest.cpp.
References pdal::Options::add(), and anonymous_namespace{BPFTest.cpp}::test_roundtrip().
TEST (BPFTest , roundtrip_point)
Definition at line 301 of file BPFTest.cpp.
References pdal::Options::add(), pdal::TEST(), and anonymous_namespace{BPFTest.cpp}::test_roundtrip().
TEST (BPFTest , roundtrip_scaling)
Definition at line 338 of file BPFTest.cpp.
References pdal::Options::add(), and anonymous_namespace{BPFTest.cpp}::test_roundtrip().
TEST (BPFTest , extra_bytes)
Definition at line 352 of file BPFTest.cpp.
References pdal::Options::add(), pdal::Utils::base64_decode(), pdal::Utils::base64_encode(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::MetadataNode::findChild(), pdal::Stage::getMetadata(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), anonymous_namespace{BPFTest.cpp}::test_file_type(), and pdal::MetadataNode::value().
TEST (BPFTest , bundled)
Definition at line 394 of file BPFTest.cpp.
References pdal::Options::add(), pdal::Utils::base64_decode(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::MetadataNode::find(), pdal::MetadataNode::findChildren(), pdal::Stage::getMetadata(), pdal::MetadataNode::name(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), anonymous_namespace{BPFTest.cpp}::test_file_type(), and pdal::MetadataNode::value().
TEST (BPFTest , inspect)
Definition at line 448 of file BPFTest.cpp.
References pdal::Options::add(), anonymous_namespace{BPFTest.cpp}::CheckEqualCollections(), Support::datapath(), pdal::SpatialReference::getWKT(), pdal::QuickInfo::m_bounds, pdal::QuickInfo::m_dimNames, pdal::QuickInfo::m_pointCount, pdal::QuickInfo::m_srs, pdal::Stage::preview(), and pdal::Stage::setOptions().
TEST (BPFTest , mueller)
Definition at line 489 of file BPFTest.cpp.
References pdal::BpfMuellerMatrix::apply(), pdal::BpfMuellerMatrix::m_vals, and z.
TEST (BPFTest , flex)
Definition at line 534 of file BPFTest.cpp.
References pdal::Options::add(), pdal::BufferReader::addView(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::FileUtils::fileExists(), pdal::QuickInfo::m_pointCount, pdal::Stage::prepare(), pdal::Stage::preview(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
TEST (BPFTest , flex2)
Definition at line 596 of file BPFTest.cpp.
References pdal::Options::add(), pdal::BufferReader::addView(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::FileUtils::fileExists(), pdal::QuickInfo::m_pointCount, pdal::Stage::prepare(), pdal::Stage::preview(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
TEST (BPFTest , outputdims)
Definition at line 651 of file BPFTest.cpp.
References pdal::Options::add(), anonymous_namespace{BPFTest.cpp}::CheckEqualCollections(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::PointLayout::dimName(), pdal::PointLayout::dims(), pdal::Stage::execute(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
TEST (BPFTest , autoutm)
Definition at line 715 of file BPFTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::getSpatialReference(), pdal::SpatialReference::getUTMZone(), pdal::Stage::prepare(), pdal::Options::replace(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().