PDAL: pdal/test/unit/filters/ChipperTest.cpp File Reference
ChipperTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/Options.hpp>
#include <pdal/StageWrapper.hpp>
#include <filters/ChipperFilter.hpp>
#include <io/LasWriter.hpp>
#include <io/LasReader.hpp>
#include "Support.hpp"
Functions
TEST (ChipperTest, test_construction)
TEST (ChipperTest, empty_buffer)
Function Documentation
TEST (ChipperTest , test_construction)
Definition at line 47 of file ChipperTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::size().
TEST (ChipperTest , empty_buffer)
Definition at line 107 of file ChipperTest.cpp.
References pdal::StageWrapper::done(), pdal::Stage::prepare(), pdal::StageWrapper::ready(), and pdal::StageWrapper::run().