PDAL: pdal::TriangularMesh Class Reference
pdal::TriangularMesh Class Reference
#include <Mesh.hpp>
Public Member Functions
TriangularMesh ()
size_t size () const
void add (PointId a, PointId b, PointId c)
const Triangle & operator[] (PointId id) const
Protected Attributes
std::deque< Triangle > m_index
Detailed Description
A mesh where the faces are triangles.
Definition at line 67 of file Mesh.hpp.
Constructor & Destructor Documentation
pdal::TriangularMesh::TriangularMesh ()
Definition at line 70 of file Mesh.hpp.
Member Function Documentation
void pdal::TriangularMesh::add (PointId a, PointId b, PointId c)
Definition at line 75 of file Mesh.hpp.
Referenced by pdal::GreedyProjection::addTriangle(), and pdal::TEST().
const Triangle& pdal::TriangularMesh::operator[] (PointId id) const
Definition at line 77 of file Mesh.hpp.
References pdal::Dimension::id().
size_t pdal::TriangularMesh::size () const
Definition at line 73 of file Mesh.hpp.
Referenced by pdal::PlyWriter::done(), and pdal::GreedyProjection::filter().
Member Data Documentation
std::deque<Triangle> pdal::TriangularMesh::m_index protected
Definition at line 83 of file Mesh.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/Mesh.hpp