PDAL: pdal::GreedyProjection Class Reference
pdal::GreedyProjection Class Reference
GreedyProjectionTriangulation is an implementation of a greedy triangulation algorithm for 3D points based on local 2D projections. It assumes locally smooth surfaces and relatively smooth transitions between areas with different point densities.
#include <GreedyProjection.hpp>
Classes
struct doubleEdge
Struct for storing the edges starting from a fringe point.
struct nnAngle
Struct for storing the angles to nearest neighbors.
Public Types
enum GP3Type {
GP3Type::NONE = -1, GP3Type::FREE = 0, GP3Type::FRINGE = 1, GP3Type::BOUNDARY = 2,
GP3Type::COMPLETED = 3
}
Public Member Functions
GreedyProjection ()
Empty constructor.
std::string getName () const
void setMaximumSurfaceAngle (double eps_angle)
Don't consider points for triangulation if their normal deviates more than this value from the query point's normal.
double getMaximumSurfaceAngle () const
Get the maximum surface angle.
void setNormalConsistency (bool consistent)
Set the flag if the input normals are oriented consistently.
bool getNormalConsistency () const
Get the flag for consistently oriented normals.
void setConsistentVertexOrdering (bool consistent_ordering)
Set the flag to order the resulting triangle vertices consistently (positive direction around normal).
bool getConsistentVertexOrdering () const
Get the flag signaling consistently ordered triangle vertices.
void setInput (Stage &input)
void setProgressFd (int fd)
QuickInfo preview ()
void prepare (PointTableRef table)
PointViewSet execute (PointTableRef table)
void execute (StreamPointTable &table)
void setSpatialReference (SpatialReference const &srs)
const SpatialReference & getSpatialReference () const
void setOptions (Options options)
void addConditionalOptions (const Options &opts)
void addAllArgs (ProgramArgs &args)
void addOptions (const Options &opts)
void removeOptions (const Options &opts)
void setLog (LogPtr &log)
virtual LogPtr log () const
void startLogging () const
void stopLogging () const
bool isDebug () const
void setTag (const std::string &tag)
virtual std::string tag () const
std::vector< Stage * > & getInputs ()
MetadataNode getMetadata () const
void serialize (MetadataNode root, PipelineWriter::TagMap &tags) const
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
static bool parseName (std::string o, std::string::size_type &pos)
static bool parseTagName (std::string o, std::string::size_type &pos)
Protected Member Functions
void setSpatialReference (MetadataNode &m, SpatialReference const &)
void addSpatialReferenceArg (ProgramArgs &args)
void throwError (const std::string &s) const
point_count_t pointCount () const
point_count_t faceCount () const
void throwStreamingError () const
Protected Attributes
double mu_
Get the state of each point after reconstruction.
double search_radius_
Nearest neighbors search radius for each point and the maximum edge length.
int nnn_
Maximum number of nearest neighbors accepted by searching.
double minimum_angle_
The preferred minimum angle for the triangles.
double maximum_angle_
The maximum angle for the triangles.
double eps_angle_
Maximum surface angle.
bool consistent_
Set this to true if the normals of the input are consistently oriented.
bool consistent_ordering_
Set this to true if the output triangle vertices should be consistently oriented.
Options m_options
Stage's options.
MetadataNode m_metadata
Stage's metadata.
int m_progressFd
Descriptor for progress info.
Private Member Functions
void connectPoint (PointId prev_index, PointId next_index, PointId next_next_index, const Eigen::Vector2d &uvn_current, const Eigen::Vector2d &uvn_prev, const Eigen::Vector2d &uvn_next)
Forms a new triangle by connecting the current neighbor to the query point and the previous neighbor.
void closeTriangle ()
Whenever a query point is part of a boundary loop containing 3 points, that triangle is created (called if angle constraints make it possible)
void addFringePoint (int v, int s)
Get the list of containing triangles for each vertex in a PolygonMesh.
bool stateSet (PointId idx)
void addArgs (ProgramArgs &args)
void addDimensions (PointLayoutPtr layout)
void initialize ()
void filter (PointView &view)
void addTriangle (PointId a, PointId b, PointId c)
Eigen::Vector3d getCoord (PointId id)
Eigen::Vector3d getNormalCoord (PointId id)
Private Attributes
std::vector< nnAngle > angles_
A list of angles to neighbors.
PointId R_
Index of the current query point.
std::vector< GP3Type > state_
List of point states.
std::vector< PointId > source_
List of sources.
std::vector< PointId > ffn_
List of fringe neighbors in one direction.
std::vector< PointId > sfn_
List of fringe neighbors in other direction.
std::vector< PointId > part_
Connected component labels for each point.
std::vector< PointId > fringe_queue_
Points on the outer edge from which the mesh is grown.
bool is_current_free_
Flag to set if the current point is free.
PointId current_index_
Current point's index.
bool prev_is_ffn_
Flag set if the previous point is the first fringe neighbor.
bool prev_is_sfn_
Flag to set if the next point is the second fringe neighbor.
bool next_is_ffn_
Flag to set if the next point is the first fringe neighbor.
bool next_is_sfn_
Flag to set if the next point is the second fringe neighbor.
bool changed_1st_fn_
Flag to set if the first fringe neighbor was changed.
bool changed_2nd_fn_
Flag to set if the second fringe neighbor was changed.
PointId new2boundary_
New boundary point.
bool already_connected_
Flag to set if the next neighbor was already connected in the previous step. To avoid inconsistency it should not be connected again.
Eigen::Vector3d proj_qp_
Point coordinates projected onto the plane defined by the point normal.
Eigen::Vector3d u_
First coordinate vector of the 2D coordinate frame.
Eigen::Vector3d v_
Second coordinate vector of the 2D coordinate frame.
Eigen::Vector2d uvn_ffn_
2D coordinates of the first fringe neighbor
Eigen::Vector2d uvn_sfn_
2D coordinates of the second fringe neighbor
Eigen::Vector2d uvn_next_ffn_
2D coordinates of the 1st fringe neighbor of the next point
Eigen::Vector2d uvn_next_sfn_
2D coordinates of the 2nd fringe neighbor of the next point
Eigen::Vector3d tmp_
Temporary variable to store 3 coordiantes.
PointView * view_
Pointer to current point view.
TriangularMesh * mesh_
Pointer to the mesh we're creating.
Detailed Description
GreedyProjectionTriangulation is an implementation of a greedy triangulation algorithm for 3D points based on local 2D projections. It assumes locally smooth surfaces and relatively smooth transitions between areas with different point densities.
Author
Zoltan Csaba Marton
Definition at line 134 of file GreedyProjection.hpp.
Class Documentation
struct pdal::GreedyProjection::nnAngle
Struct for storing the angles to nearest neighbors.
Definition at line 267 of file GreedyProjection.hpp.
Class Members
double angle
PointId index
int nnIndex
bool visible
Member Enumeration Documentation
enum pdal::GreedyProjection::GP3Type strong
Enumerator
NONE
FREE
FRINGE
BOUNDARY
COMPLETED
Definition at line 138 of file GreedyProjection.hpp.
Constructor & Destructor Documentation
pdal::GreedyProjection::GreedyProjection ()
Empty constructor.
Definition at line 148 of file GreedyProjection.hpp.
Member Function Documentation
void pdal::Stage::addAllArgs (ProgramArgs & args) inherited
Add a stage's options to a ProgramArgs set.
Parameters
args ProgramArgs to add to.
Definition at line 84 of file Stage.cpp.
References pdal::Stage::addArgs(), pdal::Stage::getName(), pdal::Stage::l_addArgs(), and pdal::arg_error::m_error.
Referenced by pdal::Stage::handleOptions(), and App::outputOptions().
void pdal::GreedyProjection::addArgs (ProgramArgs &) private virtual
Add arguments(options) handled by this stage. Implement in subclass.
Parameters
args ProgramArgs object to which arguments should be added.
Reimplemented from pdal::Stage.
Definition at line 61 of file GreedyProjection.cpp.
References pdal::ProgramArgs::add(), eps_angle_, maximum_angle_, minimum_angle_, mu_, nnn_, search_radius_, and pdal::Arg::setPositional().
void pdal::Stage::addConditionalOptions (const Options & opts) inherited
Add options if an option with the same name doesn't already exist on the stage.
Parameters
opts Options to add.
Definition at line 57 of file Stage.cpp.
References pdal::Options::addConditional(), pdal::Options::getOptions(), and pdal::Stage::m_options.
Referenced by pdal::TEST().
void pdal::GreedyProjection::addDimensions (PointLayoutPtr) private virtual
Add dimensions to a layout.
Parameters
layout Point layout.
Reimplemented from pdal::Stage.
Definition at line 78 of file GreedyProjection.cpp.
References pdal::Dimension::NormalX, pdal::Dimension::NormalY, pdal::Dimension::NormalZ, and pdal::PointLayout::registerDims().
void pdal::GreedyProjection::addFringePoint (int v, int s) private
Get the list of containing triangles for each vertex in a PolygonMesh.
Parameters
[in] polygonMesh the input polygon mesh std::vector<std::vector<size_t> > getTriangleList (const pcl::PolygonMesh &input);Add a new triangle to the current polygon mesh
[in] a index of the first vertex
[in] b index of the second vertex
[in] c index of the third vertex inline void addTriangle (PointId a, PointId b, PointId c) { triangle_.vertices.resize (3); if (consistent_ordering_) { const PointInT p = input_->at (indices_->at (a)); const Eigen::Vector3f pv = p.getVector3fMap (); if (p.getNormalVector3fMap ().dot ((pv - input_->at (indices_->at (b)).getVector3fMap ()).cross (pv - input_->at (indices_->at (c)).getVector3fMap ())) > 0) { triangle_.vertices[0] = a; triangle_.vertices[1] = b; triangle_.vertices[2] = c; } else { triangle_.vertices[0] = a; triangle_.vertices[1] = c; triangle_.vertices[2] = b; } } else { triangle_.vertices[0] = a; triangle_.vertices[1] = b; triangle_.vertices[2] = c; } polygons.push_back (triangle_); }Add a new vertex to the advancing edge front and set its source point
[in] v index of the vertex that was connected
[in] s index of the source point
Definition at line 423 of file GreedyProjection.hpp.
Referenced by filter().
void pdal::Stage::addOptions (const Options & opts) inherited
Add options to the existing option set.
Parameters
opts Options to add.
Definition at line 195 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions(), and TEST().
void pdal::Stage::addSpatialReferenceArg (ProgramArgs & args) protected inherited
Definition at line 468 of file Stage.cpp.
References pdal::ProgramArgs::add(), and pdal::Stage::m_spatialReference.
Referenced by pdal::OciReader::addArgs(), and pdal::PgReader::addArgs().
void pdal::GreedyProjection::addTriangle (PointId a, PointId b, PointId c) private
Definition at line 119 of file GreedyProjection.cpp.
References pdal::TriangularMesh::add(), and mesh_.
Referenced by closeTriangle(), connectPoint(), and filter().
void pdal::GreedyProjection::closeTriangle () private
Whenever a query point is part of a boundary loop containing 3 points, that triangle is created (called if angle constraints make it possible)
Parameters
[out] polygons the polygon mesh to be updated
Definition at line 1218 of file GreedyProjection.cpp.
References addTriangle(), angles_, COMPLETED, ffn_, R_, sfn_, and state_.
Referenced by filter().
void pdal::GreedyProjection::connectPoint (PointId prev_index, PointId next_index, PointId next_next_index, const Eigen::Vector2d & uvn_current, const Eigen::Vector2d & uvn_prev, const Eigen::Vector2d & uvn_next) private
Forms a new triangle by connecting the current neighbor to the query point and the previous neighbor.
Parameters
[in] prev_index index of the previous point
[in] next_index index of the next point
[in] next_next_index index of the point after the next one
[in] uvn_current 2D coordinate of the current point
[in] uvn_prev 2D coordinates of the previous point
[in] uvn_next 2D coordinates of the next point
Definition at line 1249 of file GreedyProjection.cpp.
References addTriangle(), already_connected_, changed_1st_fn_, changed_2nd_fn_, COMPLETED, current_index_, ffn_, FRINGE, getCoord(), is_current_free_, pdal::isVisible(), new2boundary_, next_is_ffn_, next_is_sfn_, prev_is_ffn_, prev_is_sfn_, proj_qp_, R_, sfn_, state_, stateSet(), tmp_, u_, uvn_ffn_, uvn_next_ffn_, uvn_next_sfn_, uvn_sfn_, and v_.
Referenced by filter().
static void* pdal::GreedyProjection::create () static
static int32_t pdal::GreedyProjection::destroy (void *) static
PointViewSet pdal::Stage::execute (PointTableRef table) inherited
Execute a prepared pipeline (linked set of stages).
This performs the action associated with the stage by executing the run function of each stage in depth first order. Each stage is run to completion (all points are processed) before the next stages is run.o
Parameters
table Point table being used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 156 of file Stage.cpp.
References pdal::BasePointTable::addSpatialReference(), pdal::BasePointTable::clearSpatialReferences(), pdal::SpatialReference::empty(), pdal::Stage::execute(), pdal::BasePointTable::finalize(), pdal::Stage::getSpatialReference(), pdal::Stage::l_done(), pdal::Stage::m_faceCount, pdal::Stage::m_inputs, pdal::Stage::m_pointCount, pdal::Stage::ready(), pdal::Stage::StageRunner, pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::execute(), pdal::Stage::execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
void pdal::Stage::execute (StreamPointTable & table) inherited
Execute a prepared pipeline (linked set of stages) in streaming mode.
This performs the action associated with the stage by executing the processOne function of each stage in depth first order. Points are processed up to the capacity of the provided StreamPointTable. Not all stages support streaming mode and an exception will be thrown when attempting to execute an unsupported stage.
Streaming points can reduce memory consumption, but may limit access to algorithms that need to operate on full point sets.
Parameters
table Streming point table used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 239 of file Stage.cpp.
References pdal::Stage::done(), pdal::SpatialReference::empty(), pdal::Stage::execute(), pdal::StreamPointTable::finalize(), pdal::Stage::m_inputs, pdal::entwine::operator-(), pdal::Stage::ready(), and pdal::BasePointTable::setSpatialReference().
point_count_t pdal::Stage::faceCount () const protected inherited
Return the count of faces in all primary meshes for all point views. Only valid during execute().
Returns
Total number of faces in all point views being executed.
Definition at line 336 of file Stage.hpp.
Referenced by pdal::PlyWriter::writeHeader().
void pdal::GreedyProjection::filter (PointView & view) private virtual
if (!input_->is_dense) { Skip invalid points from the indices list for (std::vector<int>::const_iterator it = indices_->begin ();o it != indices_->end (); ++it) if (!pcl_isfinite (input_->points[*it].x) || !pcl_isfinite (input_->points[*it].y) || !pcl_isfinite (input_->points[*it].z)) state_[*it] = GP3Type::NONE; }
coords_.clear (); coords_.reserve (indices_->size ()); std::vector<int> point2index (input_->points.size (), -1); for (int cp = 0; cp < static_cast<int> (indices_->size ()); ++cp) { coords_.push_back(input_->points[(*indices_)[cp]].getVector3fMap()); point2index[(*indices_)[cp]] = cp; }
Search tree returns indices into the original cloud, but we are working with indices. TODO: make that optional! for (int i = 1; i < nnn_; i++) { if (point2index[nnIdx[i]] == -1) std::cerr << R_ << " [" << indices_->at (R_) << "] " << i << ": " << nnIdx[i] << " / " << point2index[nnIdx[i]] << std::endl; nnIdx[i] = point2index[nnIdx[i]]; }
Search tree returns indices into the original cloud, but we are working with indices TODO: make that optional! for (int i = 1; i < nnn_; i++) { if (point2index[nnIdx[i]] == -1) std::cerr << R_ << " [" << indices_->at (R_) << "] " << i << ": " << nnIdx[i] << " / " << point2index[nnIdx[i]] << std::endl; nnIdx[i] = point2index[nnIdx[i]]; }
TODO: document!
Reimplemented from pdal::Filter.
Definition at line 125 of file GreedyProjection.cpp.
References addFringePoint(), addTriangle(), already_connected_, pdal::GreedyProjection::nnAngle::angle, angles_, BOUNDARY, pdal::PointView::build3dIndex(), c, changed_1st_fn_, changed_2nd_fn_, closeTriangle(), COMPLETED, connectPoint(), consistent_, pdal::PointView::createMesh(), current_index_, pdal::Debug, pdal::NormalFilter::doFilter(), pdal::Stage::done(), eps_angle_, pdal::georeference::anonymous_namespace{Georeference.cpp}::f, ffn_, pdal::GreedyProjection::doubleEdge::first, FREE, FRINGE, fringe_queue_, getCoord(), getName(), getNormalCoord(), pdal::GreedyProjection::doubleEdge::index, is_current_free_, pdal::isVisible(), pdal::KD3Index::knnSearch(), pdal::Stage::log(), maximum_angle_, mesh_, minimum_angle_, mu_, new2boundary_, next_is_ffn_, next_is_sfn_, nnn_, NONE, part_, prev_is_ffn_, prev_is_sfn_, proj_qp_, R_, search_radius_, pdal::GreedyProjection::doubleEdge::second, sfn_, pdal::TriangularMesh::size(), pdal::PointView::size(), source_, state_, stateSet(), pdal::swap(), tmp_, u_, v_, view_, pdal::GreedyProjection::nnAngle::visible, pdal::Warning, and X.
bool pdal::GreedyProjection::getConsistentVertexOrdering () const
Get the flag signaling consistently ordered triangle vertices.
Definition at line 226 of file GreedyProjection.hpp.
Eigen::Vector3d pdal::GreedyProjection::getCoord (PointId id) private
Definition at line 95 of file GreedyProjection.cpp.
References pdal::PointView::getFieldAs(), view_, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by connectPoint(), and filter().
std::vector<Stage*>& pdal::Stage::getInputs () inherited
Return a list of the stage's inputs.
Returns
A vector pointers to input stages.
Definition at line 272 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTags(), pdal::PipelineManager::leaves(), pdal::PipelineManager::replace(), and TEST().
double pdal::GreedyProjection::getMaximumSurfaceAngle () const
Get the maximum surface angle.
Definition at line 201 of file GreedyProjection.hpp.
MetadataNode pdal::Stage::getMetadata () const inherited
Get the stage's metadata node.
Returns
Stage's metadata.
Definition at line 280 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{CpdFilter.cpp}::addMetadata(), pdal::CpdFilter::change(), pdal::CpdFilter::cpd_affine(), pdal::CpdFilter::cpd_rigid(), pdal::SbetWriter::done(), pdal::MatlabWriter::done(), pdal::PcdWriter::done(), pdal::PlyWriter::done(), pdal::MbReader::done(), pdal::MrsidReader::done(), pdal::MatlabReader::done(), pdal::GDALWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::LasWriter::doneFile(), pdal::InfoKernel::dump(), pdal::IcpFilter::icp(), pdal::PythonFilter::run(), and TEST().
std::string pdal::GreedyProjection::getName () const virtual
Return the name of a stage.
Returns
The stage's name.
Implements pdal::Stage.
Definition at line 55 of file GreedyProjection.cpp.
References pdal::PluginInfo::name.
Referenced by filter().
bool pdal::GreedyProjection::getNormalConsistency () const
Get the flag for consistently oriented normals.
Definition at line 212 of file GreedyProjection.hpp.
Eigen::Vector3d pdal::GreedyProjection::getNormalCoord (PointId id) private
Definition at line 107 of file GreedyProjection.cpp.
References pdal::PointView::getFieldAs(), pdal::Dimension::NormalX, pdal::Dimension::NormalY, pdal::Dimension::NormalZ, and view_.
Referenced by filter().
const SpatialReference & pdal::Stage::getSpatialReference () const inherited
Get the spatial reference of the stage.
Get the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Returns
The stage's spatial reference.
Definition at line 474 of file Stage.cpp.
References pdal::Stage::m_spatialReference.
Referenced by pdal::Stage::execute(), pdal::PgReader::initialize(), pdal::BpfReader::inspect(), pdal::LasWriter::prepOutput(), pdal::MergeFilter::ready(), pdal::MergeFilter::run(), and TEST().
void pdal::GreedyProjection::initialize () private virtual
Initialize stage after options have been processed. Implement in subclass.
Reimplemented from pdal::Stage.
Definition at line 85 of file GreedyProjection.cpp.
References mu_, search_radius_, and pdal::Stage::throwError().
bool pdal::Stage::isDebug () const inherited
Determine whether the stage is in debug mode or not.
Returns
The stage's debug state.
Definition at line 243 of file Stage.hpp.
References pdal::Debug.
Referenced by pdal::Stage::setupLog(), pdal::Stage::startLogging(), and pdal::OciWriter::wipeBlockTable().
virtual LogPtr pdal::Stage::log () const virtual inherited
Return the stage's log pointer.
Returns
Log pointer.
Definition at line 225 of file Stage.hpp.
Referenced by pdal::OciReader::addDimensions(), pdal::GeoWaveReader::addDimensions(), pdal::SQLiteReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), pdal::LasWriter::addMetadataVlr(), pdal::LasWriter::addPipelineVlr(), pdal::OciWriter::blockTableExists(), pdal::CpdFilter::change(), pdal::PgWriter::CheckPointCloudExists(), pdal::PgWriter::CheckPostGISExists(), pdal::PgWriter::CheckTableExists(), pdal::SQLiteWriter::CreateBlockTable(), pdal::SQLiteWriter::CreateCloud(), pdal::SQLiteWriter::CreateCloudTable(), pdal::SQLiteWriter::CreateIndexes(), pdal::GeoWaveWriter::createJvm(), pdal::GeoWaveReader::createJvm(), pdal::PgReader::CursorSetup(), pdal::PgReader::CursorTeardown(), pdal::SQLiteWriter::DeleteBlockTable(), pdal::SQLiteWriter::DeleteCloudTable(), pdal::PgReader::fetchPcid(), pdal::SQLiteReader::fetchSpatialReference(), pdal::PgReader::fetchSpatialReference(), pdal::TextReader::fillFields(), pdal::ComputeRangeFilter::filter(), pdal::RadialDensityFilter::filter(), pdal::KDistanceFilter::filter(), pdal::LOFFilter::filter(), pdal::ELMFilter::filter(), pdal::ColorinterpFilter::filter(), filter(), pdal::LasWriter::finishOutput(), pdal::PgReader::getDataQuery(), pdal::GeoWaveWriter::initialize(), pdal::SQLiteWriter::initialize(), pdal::GeoWaveReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), pdal::BpfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::MbReader::loadData(), pdal::PgReader::NextBuffer(), pdal::GreyhoundReader::prepared(), pdal::PMFFilter::prepared(), pdal::NormalFilter::prepared(), pdal::LasWriter::prepared(), pdal::PMFFilter::processGround(), pdal::MongusFilter::processGround(), pdal::TextReader::processOne(), pdal::GreyhoundReader::read(), pdal::SQLiteReader::read(), pdal::PtsReader::read(), pdal::PgReader::read(), pdal::GDALReader::readBandData(), pdal::SQLiteReader::readPatch(), pdal::GeoWaveReader::ready(), pdal::PythonFilter::ready(), pdal::CropFilter::ready(), pdal::SQLiteReader::ready(), pdal::ColorinterpFilter::ready(), pdal::ColorizationFilter::ready(), pdal::BpfWriter::readyFile(), pdal::MovingLeastSquaresFilter::run(), pdal::GridProjectionFilter::run(), pdal::IcpFilter::run(), pdal::VoxelGridFilter::run(), pdal::CpdFilter::run(), pdal::MergeFilter::run(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::SampleFilter::run(), pdal::PythonFilter::run(), pdal::IQRFilter::run(), pdal::MADFilter::run(), pdal::OutlierFilter::run(), pdal::MongusFilter::run(), pdal::LasWriter::spatialReferenceChanged(), pdal::GeoWaveWriter::write(), pdal::MatlabWriter::write(), pdal::OciWriter::writeInit(), pdal::SQLiteWriter::writeInit(), pdal::OciWriter::writeTile(), and pdal::SQLiteWriter::writeTile().
bool pdal::Stage::parseName (std::string o, std::string::size_type & pos) static inherited
Parse a stage name from a string. Return the name and update the position in the input string to the end of the stage name.
Parameters
o Input string to parse.
pos Parsing start/end position.
Returns
Whether the parsed name is a valid stage name.
Definition at line 504 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::Kernel::parseStageOption().
bool pdal::Stage::parseTagName (std::string o, std::string::size_type & pos) static inherited
Parse a tag name from a string. Return the name and update the position in the input string to the end of the tag name.
Parameters
o Input string to parse.
pos Parsing start/end position.
tag Parsed tag name.
Returns
Whether the parsed name is a valid tag name.
Definition at line 518 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::PipelineReaderJSON::extractTag(), and pdal::Kernel::parseStageOption().
point_count_t pdal::Stage::pointCount () const protected inherited
Return the point count of all point views at the start of execution. Only valid during execute().
Returns
Total number of points in all point views being executed.
Definition at line 328 of file Stage.hpp.
Referenced by pdal::PlyWriter::ready(), and pdal::PlyWriter::writeHeader().
void pdal::Stage::prepare (PointTableRef table) inherited
Prepare a stage for execution. This function needs to be called on the terminal stage of a pipeline (linked set of stages) before execute can be called. Prepare recurses through all input stages.
Parameters
table PointTable being used for stage pipeline.
Definition at line 138 of file Stage.cpp.
References pdal::Stage::addDimensions(), pdal::Stage::handleOptions(), pdal::Stage::initialize(), pdal::Stage::l_initialize(), pdal::BasePointTable::layout(), pdal::Stage::m_args, pdal::Stage::m_inputs, pdal::Stage::prepare(), pdal::Stage::prepared(), pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), pdal::Stage::prepare(), pdal::PipelineManager::prepare(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
QuickInfo pdal::Stage::preview () inherited
Retrieve some basic point information without reading all data when possible. Usually implemented only by Readers.
Definition at line 127 of file Stage.cpp.
References pdal::Stage::handleOptions(), pdal::Stage::inspect(), pdal::Stage::m_args, pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by pdal::TIndexKernel::getFileInfo(), pdal::PipelineManager::preview(), pdal::InfoKernel::run(), and TEST().
void pdal::Stage::removeOptions (const Options & opts) inherited
Remove options from a stage's option set.
Parameters
opts Options to remove.
Definition at line 206 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions().
void pdal::Stage::serialize (MetadataNode root, PipelineWriter::TagMap & tags) const inherited
Serialize a stage by inserting apporpritate data into the provided MetadataNode. Used to dump a pipeline specification in a portable format.
Parameters
root Node to which a stages meatdata should be added.
tags Pipeline writer's current list of stage tags.
Definition at line 64 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), pdal::Stage::getName(), pdal::Stage::m_inputs, pdal::Stage::m_options, and pdal::Options::toMetadata().
Referenced by pdal::PipelineWriter::writePipeline().
void pdal::GreedyProjection::setConsistentVertexOrdering (bool consistent_ordering)
Set the flag to order the resulting triangle vertices consistently (positive direction around normal).
Note
Assumes consistently oriented normals (towards the viewpoint) – see setNormalConsistency ()
Parameters
[in] consistent_ordering set it to true if triangle vertices should be ordered consistently
Definition at line 222 of file GreedyProjection.hpp.
void pdal::Stage::setInput (Stage & input) inherited
Add a stage to the input list of this stage.
Parameters
input Stage to use as input.
Definition at line 85 of file Stage.hpp.
Referenced by compareTextLasStreaming(), pdal::MergeKernel::execute(), pdal::TIndexReader::initialize(), main(), pdal::PipelineManager::makeFilter(), pdal::TIndexKernel::mergeFile(), pdal::PipelineReaderJSON::parsePipeline(), pdal::PipelineManager::replace(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::TransformationFilterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), pdal::TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testOverlay(), and writeData().
void pdal::Stage::setLog (LogPtr & log) inherited
Set the stage's log.
Parameters
log Log pointer.
Definition at line 217 of file Stage.hpp.
References setup::log.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), and testOverlay().
void pdal::GreedyProjection::setMaximumSurfaceAngle (double eps_angle)
Don't consider points for triangulation if their normal deviates more than this value from the query point's normal.
Parameters
[in] eps_angle maximum surface angle
Note
As normal estimation methods usually give smooth transitions at sharp edges, this ensures correct triangulation by avoiding connecting points from one side to points from the other through forcing the use of the edge points.
Definition at line 197 of file GreedyProjection.hpp.
void pdal::GreedyProjection::setNormalConsistency (bool consistent)
Set the flag if the input normals are oriented consistently.
Parameters
[in] consistent set it to true if the normals are consistently oriented
Definition at line 208 of file GreedyProjection.hpp.
void pdal::Stage::setOptions (Options options) inherited
Set a stage's options.
Set the options on a stage, clearing all previously set options.
Parameters
options Options to set.
Definition at line 172 of file Stage.hpp.
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), getBytes(), pdal::TIndexReader::initialize(), main(), anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::PipelineManager::setOptions(), pdal::TransformationFilterTest::SetUp(), pdal::MatlabWriterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_file_type_stream(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), testReadWrite(), and writeData().
void pdal::Stage::setProgressFd (int fd) inherited
Set a file descriptor to which progress information should be written.
Parameters
fd Progress file descriptor.
Definition at line 93 of file Stage.hpp.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), and pdal::PipelineManager::addWriter().
void pdal::Stage::setSpatialReference (SpatialReference const & srs) inherited
Set the spatial reference of a stage.
Set the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Parameters
srs Spatial reference to set.
Definition at line 480 of file Stage.cpp.
References pdal::Stage::m_metadata.
Referenced by pdal::OciReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), pdal::BpfReader::initialize(), pdal::Ilvis2Reader::initialize(), pdal::PgReader::initialize(), pdal::LasWriter::initialize(), pdal::OptechReader::OptechReader(), pdal::MyReader::ready(), and TEST().
void pdal::Stage::setSpatialReference (MetadataNode & m, SpatialReference const & spatialRef) protected inherited
Definition at line 486 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::empty(), pdal::MetadataNode::findChild(), pdal::SpatialReference::getWKT(), pdal::Stage::m_spatialReference, pdal::MetadataNode::name(), and pdal::SpatialReference::toMetadata().
void pdal::Stage::setTag (const std::string & tag) inherited
Set a specific tag name.
Definition at line 256 of file Stage.hpp.
Referenced by pdal::PipelineManager::makeFilter(), and pdal::PipelineManager::makeReader().
void pdal::Stage::startLogging () const inherited
Push the stage's leader into the log.
Definition at line 538 of file Stage.cpp.
References pdal::gdal::ErrorHandler::getGlobalErrorHandler(), pdal::Stage::isDebug(), pdal::Stage::m_log, pdal::Stage::m_logLeader, and pdal::gdal::ErrorHandler::set().
Referenced by pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::preview().
bool pdal::GreedyProjection::stateSet (PointId idx) private
Definition at line 430 of file GreedyProjection.hpp.
References a, b, c, and hag::filter().
Referenced by connectPoint(), and filter().
void pdal::Stage::stopLogging () const inherited
Pop the stage's leader from the log.
Definition at line 545 of file Stage.cpp.
References pdal::Stage::m_log.
Referenced by pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::preview().
virtual std::string pdal::Stage::tag () const virtual inherited
Return the tag name of a stage.
Returns
The tag name.
Definition at line 264 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTag(), pdal::TranslateKernel::makeJSONPipeline(), and pdal::PipelineManager::stageOptions().
void pdal::Stage::throwError (const std::string & s) const protected inherited
Definition at line 532 of file Stage.cpp.
References pdal::Stage::getName().
Referenced by pdal::SQLiteReader::addDimensions(), pdal::MrsidReader::addDimensions(), pdal::TextReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), pdal::PlyReader::addDimensions(), pdal::LasWriter::addGeotiffVlrs(), pdal::LasWriter::addVlr(), pdal::PgWriter::CheckTableExists(), pdal::OciWriter::createPCEntry(), pdal::ReprojectionFilter::createTransform(), pdal::MatlabWriter::done(), pdal::NitfWriter::doneFile(), pdal::GDALWriter::doneFile(), pdal::OGRWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::GDALWriter::expandGrid(), pdal::PlyReader::extractElement(), pdal::PlyReader::extractEnd(), pdal::PlyReader::extractFormat(), pdal::PlyReader::extractHeader(), pdal::PlyReader::extractMagic(), pdal::PlyReader::extractProperty(), pdal::PgReader::fetchPcid(), pdal::PgReader::fetchSpatialReference(), pdal::LasWriter::fillForwardList(), pdal::LasWriter::fillHeader(), pdal::LasWriter::fillPointBuf(), pdal::HAGFilter::filter(), pdal::EigenvaluesFilter::filter(), pdal::ApproximateCoplanarFilter::filter(), pdal::NormalFilter::filter(), pdal::LasWriter::finishOutput(), pdal::TIndexReader::getFields(), pdal::PgReader::getNumPoints(), pdal::PlyWriter::getType(), pdal::LasWriter::handleLaszip(), pdal::OciWriter::initialize(), pdal::SQLiteWriter::initialize(), pdal::OciReader::initialize(), pdal::GDALWriter::initialize(), pdal::TextReader::initialize(), pdal::ReprojectionFilter::initialize(), pdal::PtsReader::initialize(), pdal::RangeFilter::initialize(), pdal::MatlabReader::initialize(), pdal::OGRWriter::initialize(), pdal::FerryFilter::initialize(), pdal::SQLiteReader::initialize(), pdal::OptechReader::initialize(), pdal::DividerFilter::initialize(), pdal::TIndexReader::initialize(), pdal::QfitReader::initialize(), pdal::BpfWriter::initialize(), pdal::ColorizationFilter::initialize(), pdal::BpfReader::initialize(), pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::LasWriter::initialize(), pdal::FauxReader::initialize(), initialize(), pdal::GDALReader::inspect(), pdal::OciWriter::isGeographic(), pdal::BpfWriter::loadBpfDimensions(), pdal::MbReader::loadData(), pdal::SQLiteWriter::loadGeometryWKT(), pdal::OciWriter::loadSQLData(), pdal::NitfWriter::NitfWriter(), pdal::MatlabWriter::prepared(), pdal::GDALWriter::prepared(), pdal::PlyWriter::prepared(), pdal::ComputeRangeFilter::prepared(), pdal::HAGFilter::prepared(), pdal::GroupByFilter::prepared(), pdal::IQRFilter::prepared(), pdal::LocateFilter::prepared(), pdal::RangeFilter::prepared(), pdal::MADFilter::prepared(), pdal::OGRWriter::prepared(), pdal::FerryFilter::prepared(), pdal::SortFilter::prepared(), pdal::ColorinterpFilter::prepared(), pdal::LasWriter::prepared(), pdal::OGRWriter::processOne(), pdal::Ilvis2Reader::processOne(), pdal::MatlabReader::processOne(), pdal::QfitReader::read(), pdal::OciReader::readBlob(), pdal::PlyReader::readElement(), pdal::SQLiteReader::readPatch(), pdal::OciReader::readPointMajor(), pdal::MatlabWriter::ready(), pdal::PlyWriter::ready(), pdal::SbetReader::ready(), pdal::GDALReader::ready(), pdal::OptechReader::ready(), pdal::PtsReader::ready(), pdal::ColorinterpFilter::ready(), pdal::QfitReader::ready(), pdal::TextReader::ready(), pdal::MbReader::ready(), pdal::ColorizationFilter::ready(), pdal::Ilvis2Reader::ready(), pdal::OGRWriter::readyFile(), pdal::BpfWriter::readyFile(), pdal::LasWriter::readyFile(), pdal::LasWriter::readyLazPerfCompression(), pdal::GDALWriter::readyTable(), pdal::NitfWriter::reprojectBoxToDD(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::PgWriter::SetupSchema(), pdal::CropFilter::transform(), pdal::OciWriter::updatePCExtent(), pdal::OciReader::validateQuery(), pdal::SQLiteReader::validateQuery(), pdal::MatlabWriter::write(), pdal::LasWriter::writeLasZipBuf(), pdal::OciWriter::writePointMajor(), pdal::OciWriter::writeTile(), pdal::SQLiteWriter::writeTile(), and pdal::BpfWriter::writeView().
void pdal::Stage::throwStreamingError () const protected inherited
Definition at line 339 of file Stage.hpp.
Referenced by pdal::ColorinterpFilter::processOne().
Member Data Documentation
bool pdal::GreedyProjection::already_connected_ private
Flag to set if the next neighbor was already connected in the previous step. To avoid inconsistency it should not be connected again.
Definition at line 324 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
std::vector<nnAngle> pdal::GreedyProjection::angles_ private
A list of angles to neighbors.
Definition at line 287 of file GreedyProjection.hpp.
Referenced by closeTriangle(), and filter().
bool pdal::GreedyProjection::changed_1st_fn_ private
Flag to set if the first fringe neighbor was changed.
Definition at line 316 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
bool pdal::GreedyProjection::changed_2nd_fn_ private
Flag to set if the second fringe neighbor was changed.
Definition at line 318 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
bool pdal::GreedyProjection::consistent_ protected
Set this to true if the normals of the input are consistently oriented.
Definition at line 258 of file GreedyProjection.hpp.
Referenced by filter().
bool pdal::GreedyProjection::consistent_ordering_ protected
Set this to true if the output triangle vertices should be consistently oriented.
Definition at line 263 of file GreedyProjection.hpp.
PointId pdal::GreedyProjection::current_index_ private
Current point's index.
Definition at line 306 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
double pdal::GreedyProjection::eps_angle_ protected
Maximum surface angle.
Definition at line 253 of file GreedyProjection.hpp.
Referenced by addArgs(), and filter().
std::vector<PointId> pdal::GreedyProjection::ffn_ private
List of fringe neighbors in one direction.
Definition at line 295 of file GreedyProjection.hpp.
Referenced by closeTriangle(), connectPoint(), and filter().
std::vector<PointId> pdal::GreedyProjection::fringe_queue_ private
Points on the outer edge from which the mesh is grown.
Definition at line 301 of file GreedyProjection.hpp.
Referenced by filter().
bool pdal::GreedyProjection::is_current_free_ private
Flag to set if the current point is free.
Definition at line 304 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
MetadataNode pdal::Stage::m_metadata protected inherited
Stage's metadata.
Definition at line 316 of file Stage.hpp.
Referenced by pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), pdal::Stage::l_initialize(), pdal::BpfReader::readHeaderExtraData(), pdal::BpfReader::readUlemFiles(), pdal::Ilvis2Reader::ready(), and pdal::Stage::setSpatialReference().
Options pdal::Stage::m_options protected inherited
Stage's options.
Definition at line 315 of file Stage.hpp.
Referenced by pdal::Stage::addConditionalOptions(), pdal::Stage::handleOptions(), and pdal::Stage::serialize().
int pdal::Stage::m_progressFd protected inherited
Descriptor for progress info.
Definition at line 317 of file Stage.hpp.
Referenced by pdal::LasWriter::doneFile(), pdal::NitfWriter::readyFile(), pdal::LasWriter::readyFile(), and pdal::LasWriter::writeView().
double pdal::GreedyProjection::maximum_angle_ protected
The maximum angle for the triangles.
Definition at line 250 of file GreedyProjection.hpp.
Referenced by addArgs(), and filter().
TriangularMesh* pdal::GreedyProjection::mesh_ private
Pointer to the mesh we're creating.
Definition at line 345 of file GreedyProjection.hpp.
Referenced by addTriangle(), and filter().
double pdal::GreedyProjection::minimum_angle_ protected
The preferred minimum angle for the triangles.
Definition at line 247 of file GreedyProjection.hpp.
Referenced by addArgs(), and filter().
double pdal::GreedyProjection::mu_ protected
Get the state of each point after reconstruction.
Note
Options are defined as constants: FREE, FRINGE, COMPLETED, BOUNDARY and NONEThe nearest neighbor distance multiplier to obtain the final search radius.
Definition at line 236 of file GreedyProjection.hpp.
Referenced by addArgs(), filter(), and initialize().
PointId pdal::GreedyProjection::new2boundary_ private
New boundary point.
Definition at line 320 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
bool pdal::GreedyProjection::next_is_ffn_ private
Flag to set if the next point is the first fringe neighbor.
Definition at line 312 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
bool pdal::GreedyProjection::next_is_sfn_ private
Flag to set if the next point is the second fringe neighbor.
Definition at line 314 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
int pdal::GreedyProjection::nnn_ protected
Maximum number of nearest neighbors accepted by searching.
Definition at line 244 of file GreedyProjection.hpp.
Referenced by addArgs(), and filter().
std::vector<PointId> pdal::GreedyProjection::part_ private
Connected component labels for each point.
Definition at line 299 of file GreedyProjection.hpp.
Referenced by filter().
bool pdal::GreedyProjection::prev_is_ffn_ private
Flag set if the previous point is the first fringe neighbor.
Definition at line 308 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
bool pdal::GreedyProjection::prev_is_sfn_ private
Flag to set if the next point is the second fringe neighbor.
Definition at line 310 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
Eigen::Vector3d pdal::GreedyProjection::proj_qp_ private
Point coordinates projected onto the plane defined by the point normal.
Definition at line 327 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
PointId pdal::GreedyProjection::R_ private
Index of the current query point.
Definition at line 289 of file GreedyProjection.hpp.
Referenced by closeTriangle(), connectPoint(), and filter().
double pdal::GreedyProjection::search_radius_ protected
Nearest neighbors search radius for each point and the maximum edge length.
Definition at line 241 of file GreedyProjection.hpp.
Referenced by addArgs(), filter(), and initialize().
std::vector<PointId> pdal::GreedyProjection::sfn_ private
List of fringe neighbors in other direction.
Definition at line 297 of file GreedyProjection.hpp.
Referenced by closeTriangle(), connectPoint(), and filter().
std::vector<PointId> pdal::GreedyProjection::source_ private
List of sources.
Definition at line 293 of file GreedyProjection.hpp.
Referenced by filter().
std::vector<GP3Type> pdal::GreedyProjection::state_ private
List of point states.
Definition at line 291 of file GreedyProjection.hpp.
Referenced by closeTriangle(), connectPoint(), and filter().
Eigen::Vector3d pdal::GreedyProjection::tmp_ private
Temporary variable to store 3 coordiantes.
Definition at line 341 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
Eigen::Vector3d pdal::GreedyProjection::u_ private
First coordinate vector of the 2D coordinate frame.
Definition at line 329 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
Eigen::Vector2d pdal::GreedyProjection::uvn_ffn_ private
2D coordinates of the first fringe neighbor
Definition at line 333 of file GreedyProjection.hpp.
Referenced by connectPoint().
Eigen::Vector2d pdal::GreedyProjection::uvn_next_ffn_ private
2D coordinates of the 1st fringe neighbor of the next point
Definition at line 337 of file GreedyProjection.hpp.
Referenced by connectPoint().
Eigen::Vector2d pdal::GreedyProjection::uvn_next_sfn_ private
2D coordinates of the 2nd fringe neighbor of the next point
Definition at line 339 of file GreedyProjection.hpp.
Referenced by connectPoint().
Eigen::Vector2d pdal::GreedyProjection::uvn_sfn_ private
2D coordinates of the second fringe neighbor
Definition at line 335 of file GreedyProjection.hpp.
Referenced by connectPoint().
Eigen::Vector3d pdal::GreedyProjection::v_ private
Second coordinate vector of the 2D coordinate frame.
Definition at line 331 of file GreedyProjection.hpp.
Referenced by connectPoint(), and filter().
PointView* pdal::GreedyProjection::view_ private
Pointer to current point view.
Definition at line 343 of file GreedyProjection.hpp.
Referenced by filter(), getCoord(), and getNormalCoord().
The documentation for this class was generated from the following files:
pdal/filters/GreedyProjection.hpp
pdal/filters/GreedyProjection.cpp