PDAL: pdal::PluginManager Class Reference
pdal::PluginManager Class Reference
#include <PluginManager.hpp>
Public Member Functions
PluginManager ()
~PluginManager ()
Static Public Member Functions
static std::string description (const std::string &name)
static std::string link (const std::string &name)
static bool registerObject (const std::string &name, const PF_RegisterParams *params)
static bool initializePlugin (PF_InitFunc initFunc)
static bool loadPlugin (const std::string &pluginFilename)
static void loadAll (int type)
static void * createObject (const std::string &objectType)
static StringList names (int typeMask)
static void setLog (LogPtr &log)
Private Types
typedef std::shared_ptr< DynamicLibrary > DynLibPtr
typedef std::map< std::string, DynLibPtr > DynamicLibraryMap
typedef std::vector< PF_ExitFunc > ExitFuncVec
typedef std::map< std::string, PF_RegisterParams > RegistrationInfoMap
Private Member Functions
FRIEND_TEST (PluginManagerTest, SearchPaths)
bool shutdown ()
bool guessLoadByPath (const std::string &driverName)
bool loadByPath (const std::string &path, PF_PluginType type)
bool libraryLoaded (const std::string &path)
void loadAll (const std::string &pluginDirectory, int type)
bool l_initializePlugin (PF_InitFunc initFunc)
void * l_createObject (const std::string &objectType)
bool l_registerObject (const std::string &name, const PF_RegisterParams *params)
bool l_loadPlugin (const std::string &pluginFilename)
void l_loadAll (int type)
StringList l_names (int typeMask)
std::string l_description (const std::string &name)
std::string l_link (const std::string &name)
DynamicLibrary * loadLibrary (const std::string &path, std::string &errorString)
PluginManager (const PluginManager &)
PluginManager & operator= (const PluginManager &)
Static Private Member Functions
static StringList test_pluginSearchPaths ()
Private Attributes
PF_PluginAPI_Version m_version
DynamicLibraryMap m_dynamicLibraryMap
ExitFuncVec m_exitFuncVec
RegistrationInfoMap m_plugins
std::mutex m_mutex
LogPtr m_log
Detailed Description
Definition at line 62 of file PluginManager.hpp.
Member Typedef Documentation
typedef std::map<std::string, DynLibPtr> pdal::PluginManager::DynamicLibraryMap private
Definition at line 67 of file PluginManager.hpp.
typedef std::shared_ptr<DynamicLibrary> pdal::PluginManager::DynLibPtr private
Definition at line 66 of file PluginManager.hpp.
typedef std::vector<PF_ExitFunc> pdal::PluginManager::ExitFuncVec private
Definition at line 68 of file PluginManager.hpp.
typedef std::map<std::string, PF_RegisterParams> pdal::PluginManager::RegistrationInfoMap private
Definition at line 69 of file PluginManager.hpp.
Constructor & Destructor Documentation
pdal::PluginManager::PluginManager ()
Definition at line 248 of file PluginManager.cpp.
References m_version, PF_PluginAPI_Version::major, and PF_PluginAPI_Version::minor.
pdal::PluginManager::~PluginManager ()
Definition at line 255 of file PluginManager.cpp.
References pdal::Error, m_log, and shutdown().
pdal::PluginManager::PluginManager (const PluginManager &) private
Member Function Documentation
void * pdal::PluginManager::createObject (const std::string & objectType) static
Definition at line 441 of file PluginManager.cpp.
References l_createObject(), and pdal::anonymous_namespace{PluginManager.cpp}::s_instance.
Referenced by pdal::StageFactory::createStage(), App::execute(), and pdal::TEST().
std::string pdal::PluginManager::description (const std::string & name) static
Definition at line 191 of file PluginManager.cpp.
References l_description(), and pdal::anonymous_namespace{PluginManager.cpp}::s_instance.
Referenced by App::outputDrivers().
pdal::PluginManager::FRIEND_TEST (PluginManagerTest , SearchPaths) private
bool pdal::PluginManager::guessLoadByPath (const std::string & driverName) private
Definition at line 342 of file PluginManager.cpp.
References pdal::Debug, pdal::FileUtils::directoryList(), pdal::FileUtils::extension(), pdal::FileUtils::fileExists(), pdal::FileUtils::isDirectory(), loadByPath(), m_log, PF_PluginType_Filter, PF_PluginType_Kernel, PF_PluginType_Reader, PF_PluginType_Writer, pdal::anonymous_namespace{PluginManager.cpp}::pluginSearchPaths(), pdal::Utils::split2(), pdal::FileUtils::stem(), and pdal::Dimension::type().
Referenced by l_createObject().
bool pdal::PluginManager::initializePlugin (PF_InitFunc initFunc) static
Definition at line 230 of file PluginManager.cpp.
References l_initializePlugin(), and pdal::anonymous_namespace{PluginManager.cpp}::s_instance.
Referenced by loadByPath(), pdal::StageFactory::StageFactory(), and pdal::TEST().
void * pdal::PluginManager::l_createObject (const std::string & objectType) private
Definition at line 447 of file PluginManager.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, guessLoadByPath(), m_mutex, and m_plugins.
Referenced by createObject().
std::string pdal::PluginManager::l_description (const std::string & name) private
Definition at line 197 of file PluginManager.cpp.
References m_mutex, and m_plugins.
Referenced by description().
bool pdal::PluginManager::l_initializePlugin (PF_InitFunc initFunc) private
Definition at line 236 of file PluginManager.cpp.
References m_exitFuncVec, and m_mutex.
Referenced by initializePlugin().
std::string pdal::PluginManager::l_link (const std::string & name) private
Definition at line 179 of file PluginManager.cpp.
References link(), m_mutex, and m_plugins.
Referenced by link().
void pdal::PluginManager::l_loadAll (int type) private
Definition at line 137 of file PluginManager.cpp.
References loadAll(), and pdal::anonymous_namespace{PluginManager.cpp}::pluginSearchPaths().
Referenced by loadAll().
bool pdal::PluginManager::l_loadPlugin (const std::string & pluginFilename) private
Definition at line 310 of file PluginManager.cpp.
References pdal::FileUtils::extension(), pdal::Utils::iequals(), pdal::FileUtils::isDirectory(), loadByPath(), PF_PluginType_Filter, PF_PluginType_Kernel, PF_PluginType_Reader, PF_PluginType_Writer, pdal::Utils::split2(), and pdal::Dimension::type().
Referenced by loadPlugin().
StringList pdal::PluginManager::l_names (int typeMask) private
Definition at line 162 of file PluginManager.cpp.
References m_mutex, and m_plugins.
Referenced by names().
bool pdal::PluginManager::l_registerObject (const std::string & name, const PF_RegisterParams * params) private
Definition at line 116 of file PluginManager.cpp.
References PF_RegisterParams::createFunc, PF_RegisterParams::destroyFunc, m_mutex, m_plugins, m_version, PF_PluginAPI_Version::major, and PF_RegisterParams::version.
Referenced by registerObject().
bool pdal::PluginManager::libraryLoaded (const std::string & path) private
Definition at line 490 of file PluginManager.cpp.
References pdal::Utils::contains(), m_dynamicLibraryMap, m_mutex, and pdal::FileUtils::toAbsolutePath().
Referenced by loadByPath().
std::string pdal::PluginManager::link (const std::string & name) static
Definition at line 173 of file PluginManager.cpp.
References l_link(), and pdal::anonymous_namespace{PluginManager.cpp}::s_instance.
Referenced by l_link(), App::outputDrivers(), and App::outputOptions().
void pdal::PluginManager::loadAll (int type) static
Definition at line 131 of file PluginManager.cpp.
References l_loadAll(), and pdal::anonymous_namespace{PluginManager.cpp}::s_instance.
Referenced by l_loadAll(), and pdal::StageFactory::StageFactory().
void pdal::PluginManager::loadAll (const std::string & pluginDirectory, int type) private
Definition at line 209 of file PluginManager.cpp.
References pdal::Debug, pdal::FileUtils::directoryList(), pdal::FileUtils::extension(), pdal::FileUtils::fileExists(), pdal::FileUtils::isDirectory(), loadByPath(), and m_log.
bool pdal::PluginManager::loadByPath (const std::string & path, PF_PluginType type) private
Definition at line 392 of file PluginManager.cpp.
References pdal::Debug, pdal::Error, pdal::FileUtils::getFilename(), initializePlugin(), libraryLoaded(), loadLibrary(), m_log, pdal::anonymous_namespace{PluginManager.cpp}::pluginTypeValid(), pdal::FileUtils::toAbsolutePath(), and pdal::Utils::tolower().
Referenced by guessLoadByPath(), l_loadPlugin(), and loadAll().
DynamicLibrary * pdal::PluginManager::loadLibrary (const std::string & path, std::string & errorString) private
Definition at line 471 of file PluginManager.cpp.
References pdal::Error, pdal::DynamicLibrary::load(), m_dynamicLibraryMap, m_log, m_mutex, and pdal::FileUtils::toAbsolutePath().
Referenced by loadByPath().
bool pdal::PluginManager::loadPlugin (const std::string & pluginFilename) static
Definition at line 304 of file PluginManager.cpp.
References l_loadPlugin(), and pdal::anonymous_namespace{PluginManager.cpp}::s_instance.
Referenced by pdal::PipelineReaderJSON::extractOptions().
StringList pdal::PluginManager::names (int typeMask) static
Definition at line 150 of file PluginManager.cpp.
References l_names(), and pdal::anonymous_namespace{PluginManager.cpp}::s_instance.
Referenced by App::findKernel(), App::outputCommands(), App::outputDrivers(), App::outputHelp(), App::outputOptions(), and pdal::TEST().
PluginManager& pdal::PluginManager::operator= (const PluginManager &) private
bool pdal::PluginManager::registerObject (const std::string & name, const PF_RegisterParams * params) static
Definition at line 109 of file PluginManager.cpp.
References l_registerObject(), and pdal::anonymous_namespace{PluginManager.cpp}::s_instance.
Referenced by pdal::DummyPlugin::initPlugin().
void pdal::PluginManager::setLog (LogPtr & log) static
Definition at line 156 of file PluginManager.cpp.
References setup::log, m_log, and pdal::anonymous_namespace{PluginManager.cpp}::s_instance.
Referenced by App::execute().
bool pdal::PluginManager::shutdown () private
Definition at line 263 of file PluginManager.cpp.
References m_dynamicLibraryMap, m_exitFuncVec, m_mutex, and m_plugins.
Referenced by ~PluginManager().
StringList pdal::PluginManager::test_pluginSearchPaths () static private
Definition at line 144 of file PluginManager.cpp.
References pdal::anonymous_namespace{PluginManager.cpp}::pluginSearchPaths().
Referenced by pdal::TEST().
Member Data Documentation
DynamicLibraryMap pdal::PluginManager::m_dynamicLibraryMap private
Definition at line 108 of file PluginManager.hpp.
Referenced by libraryLoaded(), loadLibrary(), and shutdown().
ExitFuncVec pdal::PluginManager::m_exitFuncVec private
Definition at line 109 of file PluginManager.hpp.
Referenced by l_initializePlugin(), and shutdown().
LogPtr pdal::PluginManager::m_log private
Definition at line 112 of file PluginManager.hpp.
Referenced by guessLoadByPath(), loadAll(), loadByPath(), loadLibrary(), setLog(), and ~PluginManager().
std::mutex pdal::PluginManager::m_mutex private
Definition at line 111 of file PluginManager.hpp.
Referenced by l_createObject(), l_description(), l_initializePlugin(), l_link(), l_names(), l_registerObject(), libraryLoaded(), loadLibrary(), and shutdown().
RegistrationInfoMap pdal::PluginManager::m_plugins private
Definition at line 110 of file PluginManager.hpp.
Referenced by l_createObject(), l_description(), l_link(), l_names(), l_registerObject(), and shutdown().
PF_PluginAPI_Version pdal::PluginManager::m_version private
Definition at line 107 of file PluginManager.hpp.
Referenced by l_registerObject(), and PluginManager().
The documentation for this class was generated from the following files:
pdal/pdal/PluginManager.hpp
pdal/pdal/PluginManager.cpp