PDAL: pdal::KDIndex< DIM > Class Template Reference
pdal::KDIndex< DIM > Class Template Reference
#include <KDIndex.hpp>
Public Member Functions
std::size_t kdtree_get_point_count () const
double kdtree_get_pt (const PointId idx, int dim) const
double kdtree_distance (const double *p1, const PointId p2_idx, size_t) const
template<class BBOX >
bool kdtree_get_bbox (BBOX &bb) const
void build ()
template<>
double kdtree_get_pt (const PointId idx, int dim) const
template<>
double kdtree_get_pt (const PointId idx, int dim) const
template<>
double kdtree_distance (const double *p1, const PointId idx, size_t) const
template<>
double kdtree_distance (const double *p1, const PointId idx, size_t) const
template<>
bool kdtree_get_bbox (BBOX &bb) const
template<>
bool kdtree_get_bbox (BBOX &bb) const
Protected Types
typedef nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, KDIndex, double >, KDIndex,-1, std::size_t > my_kd_tree_t
Protected Member Functions
KDIndex (const PointView &buf)
~KDIndex ()
Protected Attributes
const PointView & m_buf
std::unique_ptr< my_kd_tree_t > m_index
Private Member Functions
KDIndex (const KDIndex &)
KDIndex & operator= (KDIndex &)
Detailed Description
template<int DIM>
class pdal::KDIndex< DIM >
Definition at line 56 of file KDIndex.hpp.
Member Typedef Documentation
template<int DIM> typedef nanoflann::KDTreeSingleIndexAdaptor<nanoflann::L2_Simple_Adaptor< double, KDIndex, double>, KDIndex, -1, std::size_t> pdal::KDIndex< DIM >::my_kd_tree_t protected
Definition at line 83 of file KDIndex.hpp.
Constructor & Destructor Documentation
template<int DIM> pdal::KDIndex< DIM >::KDIndex (const PointView & buf) protected
Definition at line 59 of file KDIndex.hpp.
template<int DIM> pdal::KDIndex< DIM >::~KDIndex () protected
Definition at line 62 of file KDIndex.hpp.
template<int DIM> pdal::KDIndex< DIM >::KDIndex (const KDIndex< DIM > &) private
Member Function Documentation
template<int DIM> void pdal::KDIndex< DIM >::build ()
Definition at line 73 of file KDIndex.hpp.
Referenced by pdal::Utils::computeHausdorff(), pdal::eigen::createMaxMatrix2(), pdal::InfoKernel::dumpQuery(), pdal::DeltaKernel::execute(), pdal::Segmentation::extractClusters(), pdal::KDistanceFilter::filter(), pdal::RadialDensityFilter::filter(), pdal::HAGFilter::filter(), pdal::LOFFilter::filter(), pdal::EigenvaluesFilter::filter(), pdal::EstimateRankFilter::filter(), pdal::ApproximateCoplanarFilter::filter(), pdal::SMRFilter::knnfill(), pdal::PMFFilter::processGround(), pdal::OutlierFilter::processRadius(), pdal::OutlierFilter::processStatistical(), pdal::SampleFilter::run(), pdal::VoxelCentroidNearestNeighborFilter::run(), pdal::VoxelCenterNearestNeighborFilter::run(), and TEST().
template<int DIM> double pdal::KDIndex< DIM >::kdtree_distance (const double * p1, const PointId p2_idx, size_t) const
template<> double pdal::KDIndex< 2 >::kdtree_distance (const double * p1, const PointId idx, size_t) const
Definition at line 411 of file KDIndex.hpp.
References X, and Y.
template<> double pdal::KDIndex< 3 >::kdtree_distance (const double * p1, const PointId idx, size_t) const
Definition at line 421 of file KDIndex.hpp.
References X, Y, and Z.
template<int DIM> template<class BBOX > bool pdal::KDIndex< DIM >::kdtree_get_bbox (BBOX & bb) const
template<> bool pdal::KDIndex< 2 >::kdtree_get_bbox (BBOX & bb) const
Definition at line 434 of file KDIndex.hpp.
References pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, and pdal::BOX2D::miny.
template<> bool pdal::KDIndex< 3 >::kdtree_get_bbox (BBOX & bb) const
Definition at line 458 of file KDIndex.hpp.
References pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
template<int DIM> std::size_t pdal::KDIndex< DIM >::kdtree_get_point_count () const
Definition at line 66 of file KDIndex.hpp.
template<int DIM> double pdal::KDIndex< DIM >::kdtree_get_pt (const PointId idx, int dim) const
template<> double pdal::KDIndex< 2 >::kdtree_get_pt (const PointId idx, int dim) const
Definition at line 361 of file KDIndex.hpp.
References pdal::Dimension::id(), X, and Y.
template<> double pdal::KDIndex< 3 >::kdtree_get_pt (const PointId idx, int dim) const
Definition at line 384 of file KDIndex.hpp.
References pdal::Dimension::id(), X, Y, and Z.
template<int DIM> KDIndex& pdal::KDIndex< DIM >::operator= (KDIndex< DIM > &) private
Member Data Documentation
template<int DIM> const PointView& pdal::KDIndex< DIM >::m_buf protected
Definition at line 80 of file KDIndex.hpp.
template<int DIM> std::unique_ptr<my_kd_tree_t> pdal::KDIndex< DIM >::m_index protected
Definition at line 85 of file KDIndex.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/KDIndex.hpp