PDAL: pdal::XMLSchema Class Reference
pdal::XMLSchema Class Reference
#include <XMLSchema.hpp>
Public Member Functions
XMLSchema (std::string xml, std::string xsd="", Orientation orientation=Orientation::PointMajor)
XMLSchema (const XMLDimList &dims, MetadataNode m=MetadataNode(), Orientation orientation=Orientation::PointMajor)
XMLSchema (const PointLayoutPtr &pointTable, MetadataNode m=MetadataNode(), Orientation orientation=Orientation::PointMajor)
XMLSchema ()
~XMLSchema ()
std::string xml () const
DimTypeList dimTypes () const
XMLDimList xmlDims () const
MetadataNode getMetadata () const
void setId (const std::string &name, Dimension::Id id)
void setXForm (Dimension::Id id, XForm xform)
XForm xForm (Dimension::Id id) const
void setOrientation (Orientation orientation)
Orientation orientation () const
Private Member Functions
XMLDim & xmlDim (Dimension::Id id)
const XMLDim & xmlDim (Dimension::Id id) const
XMLDim & xmlDim (const std::string &name)
xmlDocPtr init (const std::string &xml, const std::string &xsd)
bool validate (xmlDocPtr doc, const std::string &xsd)
std::string remapOldNames (const std::string &input)
bool loadMetadata (xmlNode *startNode, MetadataNode &input)
bool load (xmlDocPtr doc)
void writeXml (xmlTextWriterPtr w) const
Private Attributes
Orientation m_orientation
XMLDimList m_dims
void * m_global_context
MetadataNode m_metadata
Detailed Description
Definition at line 93 of file XMLSchema.hpp.
Constructor & Destructor Documentation
pdal::XMLSchema::XMLSchema (std::string xml, std::string xsd = "", Orientation orientation = Orientation::PointMajor)
Definition at line 159 of file XMLSchema.cpp.
References init(), and load().
pdal::XMLSchema::XMLSchema (const XMLDimList & dims, MetadataNode m = MetadataNode(), Orientation orientation = Orientation::PointMajor)
Definition at line 171 of file XMLSchema.cpp.
pdal::XMLSchema::XMLSchema (const PointLayoutPtr & pointTable, MetadataNode m = MetadataNode(), Orientation orientation = Orientation::PointMajor)
Definition at line 177 of file XMLSchema.cpp.
References pdal::PointLayout::dimName(), dimTypes(), pdal::PointLayout::dimTypes(), and m_dims.
pdal::XMLSchema::XMLSchema ()
Definition at line 102 of file XMLSchema.hpp.
pdal::XMLSchema::~XMLSchema ()
Definition at line 105 of file XMLSchema.hpp.
References xml.
Member Function Documentation
DimTypeList pdal::XMLSchema::dimTypes () const
Definition at line 215 of file XMLSchema.cpp.
References m_dims.
Referenced by XMLSchema().
MetadataNode pdal::XMLSchema::getMetadata () const
Definition at line 113 of file XMLSchema.hpp.
Referenced by pdal::OciReader::addDimensions(), pdal::SQLiteReader::addDimensions(), pdal::OciReader::readOci(), and TEST().
xmlDocPtr pdal::XMLSchema::init (const std::string & xml, const std::string & xsd) private
Definition at line 225 of file XMLSchema.cpp.
References m_global_context, pdal::OCISchemaGenericErrorHandler(), pdal::OCISchemaStructuredErrorHandler(), and validate().
Referenced by XMLSchema().
bool pdal::XMLSchema::load (xmlDocPtr doc) private
Definition at line 332 of file XMLSchema.cpp.
References pdal::DimensionMajor, pdal::Utils::iequals(), loadMetadata(), pdal::XMLDim::m_description, m_dims, pdal::XMLDim::m_dimType, pdal::XMLDim::m_max, m_metadata, pdal::XMLDim::m_min, pdal::XMLDim::m_name, pdal::XForm::m_offset, m_orientation, pdal::XMLDim::m_position, pdal::XForm::m_scale, pdal::DimType::m_type, pdal::DimType::m_xform, pdal::MetadataNode, orientation(), pdal::PointMajor, remapOldNames(), pdal::XForm::XFormComponent::set(), pdal::Utils::tolower(), and pdal::Dimension::type().
Referenced by XMLSchema().
bool pdal::XMLSchema::loadMetadata (xmlNode * startNode, MetadataNode & input) private
Definition at line 287 of file XMLSchema.cpp.
References pdal::MetadataNode::add(), pdal::Dimension::description(), pdal::Utils::iequals(), and pdal::MbError::text().
Referenced by load().
Orientation pdal::XMLSchema::orientation () const
Definition at line 123 of file XMLSchema.hpp.
Referenced by load(), pdal::DbReader::loadSchema(), pdal::DbReader::updateSchema(), and writeXml().
std::string pdal::XMLSchema::remapOldNames (const std::string & input) private
Definition at line 273 of file XMLSchema.cpp.
References pdal::Utils::iequals().
Referenced by load().
void pdal::XMLSchema::setId (const std::string & name, Dimension::Id id)
Definition at line 115 of file XMLSchema.hpp.
References pdal::Dimension::id().
Referenced by TEST().
void pdal::XMLSchema::setOrientation (Orientation orientation)
Definition at line 121 of file XMLSchema.hpp.
void pdal::XMLSchema::setXForm (Dimension::Id id, XForm xform)
Definition at line 117 of file XMLSchema.hpp.
bool pdal::XMLSchema::validate (xmlDocPtr doc, const std::string & xsd) private
Definition at line 249 of file XMLSchema.cpp.
References m_global_context, pdal::OCISchemaParserStructuredErrorHandler(), pdal::OCISchemaValidityDebug(), and pdal::OCISchemaValidityError().
Referenced by init().
void pdal::XMLSchema::writeXml (xmlTextWriterPtr w) const private
Definition at line 564 of file XMLSchema.cpp.
References pdal::anonymous_namespace{XMLSchema.cpp}::addMetadataEntry(), pdal::Dimension::description(), pdal::DimensionMajor, pdal::MetadataNode::empty(), pdal::Dimension::interpretationName(), m_dims, m_metadata, pdal::XForm::m_offset, m_orientation, pdal::XForm::m_scale, pdal::XForm::XFormComponent::m_val, pdal::Dimension::name(), pdal::XForm::nonstandard(), orientation(), PDAL_XML_SCHEMA_VERSION, pdal::PointMajor, and pdal::Dimension::size().
Referenced by xml().
XForm pdal::XMLSchema::xForm (Dimension::Id id) const
Definition at line 119 of file XMLSchema.hpp.
std::string pdal::XMLSchema::xml () const
Definition at line 186 of file XMLSchema.cpp.
References b, and writeXml().
Referenced by pdal::OciReader::addDimensions(), pdal::SQLiteWriter::CreateCloud(), pdal::OciWriter::createPCEntry(), pdal::PgWriter::SetupSchema(), and TEST().
XMLDim & pdal::XMLSchema::xmlDim (Dimension::Id id) private
Definition at line 497 of file XMLSchema.cpp.
References m_dims.
const XMLDim & pdal::XMLSchema::xmlDim (Dimension::Id id) const private
Definition at line 508 of file XMLSchema.cpp.
References m_dims.
XMLDim & pdal::XMLSchema::xmlDim (const std::string & name) private
Definition at line 519 of file XMLSchema.cpp.
References m_dims.
XMLDimList pdal::XMLSchema::xmlDims () const
Definition at line 110 of file XMLSchema.hpp.
Referenced by pdal::DbReader::loadSchema(), TEST(), and pdal::DbReader::updateSchema().
Member Data Documentation
XMLDimList pdal::XMLSchema::m_dims private
Definition at line 128 of file XMLSchema.hpp.
Referenced by dimTypes(), load(), writeXml(), xmlDim(), and XMLSchema().
void* pdal::XMLSchema::m_global_context private
Definition at line 129 of file XMLSchema.hpp.
Referenced by init(), and validate().
MetadataNode pdal::XMLSchema::m_metadata private
Definition at line 130 of file XMLSchema.hpp.
Referenced by load(), and writeXml().
Orientation pdal::XMLSchema::m_orientation private
Definition at line 127 of file XMLSchema.hpp.
Referenced by load(), and writeXml().
The documentation for this class was generated from the following files:
pdal/pdal/XMLSchema.hpp
pdal/pdal/XMLSchema.cpp