PDAL: pdal::MetadataNodeImpl Class Reference
pdal::MetadataNodeImpl Class Reference
#include <Metadata.hpp>
Public Member Functions
template<>
void setValue (const Eigen::MatrixXd &matrix)
template<>
void setValue (const SpatialReference &ref)
template<>
void setValue (const bool &b)
template<>
void setValue (const std::string &s)
template<>
void setValue (const char *const &c)
template<>
void setValue (const float &f)
template<>
void PDAL_DLL setValue (const SpatialReference &ref)
template<>
void setValue (const BOX3D &b)
template<>
void setValue (const unsigned char &u)
template<>
void setValue (const unsigned short &u)
template<>
void setValue (const unsigned int &u)
template<>
void setValue (const unsigned long &u)
template<>
void setValue (const unsigned long long &u)
template<>
void setValue (const char &i)
template<>
void setValue (const signed char &i)
template<>
void setValue (const short &s)
template<>
void setValue (const int &i)
template<>
void setValue (const long &l)
template<>
void setValue (const long long &l)
template<>
void setValue (const Uuid &u)
Private Member Functions
MetadataNodeImpl (const std::string &name)
MetadataNodeImpl ()
void makeArray (MetadataImplList &l)
MetadataNodeImplPtr add (const std::string &name)
MetadataNodeImplPtr addList (const std::string &name)
MetadataNodeImplPtr add (MetadataNodeImplPtr node)
MetadataNodeImplPtr addList (MetadataNodeImplPtr node)
bool operator== (const MetadataNodeImpl &m) const
template<typename T >
void setValue (const T &t)
template<std::size_t N>
void setValue (const char(&c)[N])
MetadataImplList & subnodes (const std::string &name)
const MetadataImplList & subnodes (const std::string &name) const
MetadataType nodeType (const std::string &name) const
template<>
void setValue (const double &d)
Private Attributes
std::string m_name
std::string m_descrip
std::string m_type
std::string m_value
MetadataType m_kind
MetadataSubnodes m_subnodes
Friends
class MetadataNode
Detailed Description
Definition at line 67 of file Metadata.hpp.
Constructor & Destructor Documentation
pdal::MetadataNodeImpl::MetadataNodeImpl (const std::string & name) private
Definition at line 72 of file Metadata.hpp.
References pdal::Dimension::name().
pdal::MetadataNodeImpl::MetadataNodeImpl () private
Definition at line 75 of file Metadata.hpp.
Member Function Documentation
MetadataNodeImplPtr pdal::MetadataNodeImpl::add (const std::string & name) private
Definition at line 87 of file Metadata.hpp.
References pdal::Dimension::name().
MetadataNodeImplPtr pdal::MetadataNodeImpl::add (MetadataNodeImplPtr node) private
Definition at line 106 of file Metadata.hpp.
MetadataNodeImplPtr pdal::MetadataNodeImpl::addList (const std::string & name) private
Definition at line 97 of file Metadata.hpp.
References pdal::Dimension::name().
MetadataNodeImplPtr pdal::MetadataNodeImpl::addList (MetadataNodeImplPtr node) private
Definition at line 115 of file Metadata.hpp.
void pdal::MetadataNodeImpl::makeArray (MetadataImplList & l) private
Definition at line 78 of file Metadata.hpp.
References pdal::Array.
MetadataType pdal::MetadataNodeImpl::nodeType (const std::string & name) const private
Definition at line 178 of file Metadata.hpp.
References pdal::Instance.
bool pdal::MetadataNodeImpl::operator== (const MetadataNodeImpl & m) const private
Definition at line 123 of file Metadata.hpp.
References m_descrip, m_name, m_subnodes, m_type, and m_value.
template<> void pdal::MetadataNodeImpl::setValue (const SpatialReference & ref)
Definition at line 42 of file Metadata.cpp.
References m_type, m_value, and pdal::Utils::toString().
template<typename T > void pdal::MetadataNodeImpl::setValue (const T & t) private
Definition at line 153 of file Metadata.hpp.
References c, and pdal::Utils::toString().
Referenced by setValue().
template<std::size_t N> void pdal::MetadataNodeImpl::setValue (const char(&) c[N]) private
Definition at line 219 of file Metadata.hpp.
References c.
template<> void pdal::MetadataNodeImpl::setValue (const bool & b)
Definition at line 198 of file Metadata.hpp.
template<> void pdal::MetadataNodeImpl::setValue (const std::string & s)
Definition at line 205 of file Metadata.hpp.
template<> void pdal::MetadataNodeImpl::setValue (const char *const & c)
Definition at line 212 of file Metadata.hpp.
References c.
template<> void pdal::MetadataNodeImpl::setValue (const float & f)
Definition at line 226 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const double & d) private
Definition at line 233 of file Metadata.hpp.
References PDAL_DLL, setValue(), and pdal::Utils::toString().
template<> void PDAL_DLL pdal::MetadataNodeImpl::setValue (const SpatialReference & ref)
template<> void pdal::MetadataNodeImpl::setValue (const BOX3D & b)
Definition at line 248 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const unsigned char & u)
Definition at line 255 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const unsigned short & u)
Definition at line 262 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const unsigned int & u)
Definition at line 269 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const unsigned long & u)
Definition at line 276 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const unsigned long long & u)
Definition at line 283 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const char & i)
Definition at line 290 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const signed char & i)
Definition at line 297 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const short & s)
Definition at line 304 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const int & i)
Definition at line 311 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const long & l)
Definition at line 318 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const long long & l)
Definition at line 325 of file Metadata.hpp.
References pdal::Utils::toString().
template<> void pdal::MetadataNodeImpl::setValue (const Uuid & u)
Definition at line 332 of file Metadata.hpp.
References pdal::Uuid::toString().
template<> void pdal::MetadataNodeImpl::setValue (const Eigen::MatrixXd & matrix)
Definition at line 992 of file EigenUtils.hpp.
References pdal::Utils::toString().
MetadataImplList& pdal::MetadataNodeImpl::subnodes (const std::string & name) private
Definition at line 162 of file Metadata.hpp.
Referenced by subnodes().
const MetadataImplList& pdal::MetadataNodeImpl::subnodes (const std::string & name) const private
Definition at line 172 of file Metadata.hpp.
References subnodes().
Friends And Related Function Documentation
friend class MetadataNode friend
Definition at line 69 of file Metadata.hpp.
Member Data Documentation
std::string pdal::MetadataNodeImpl::m_descrip private
Definition at line 190 of file Metadata.hpp.
Referenced by operator==().
MetadataType pdal::MetadataNodeImpl::m_kind private
Definition at line 193 of file Metadata.hpp.
std::string pdal::MetadataNodeImpl::m_name private
Definition at line 189 of file Metadata.hpp.
Referenced by operator==().
MetadataSubnodes pdal::MetadataNodeImpl::m_subnodes private
Definition at line 194 of file Metadata.hpp.
Referenced by operator==().
std::string pdal::MetadataNodeImpl::m_type private
Definition at line 191 of file Metadata.hpp.
Referenced by operator==(), and setValue().
std::string pdal::MetadataNodeImpl::m_value private
Definition at line 192 of file Metadata.hpp.
Referenced by operator==(), and setValue().
The documentation for this class was generated from the following files:
pdal/pdal/Metadata.hpp
pdal/pdal/EigenUtils.hpp
pdal/pdal/Metadata.cpp