PDAL: pdal::entwine::Bounds Class Reference
pdal::entwine::Bounds Class Reference
#include <bounds.hpp>
Public Member Functions
Bounds ()=default
Bounds (const Point &min, const Point &max)
Bounds (const Point &center, double radius)
Bounds (const Json::Value &json)
Bounds (double xMin, double yMin, double xMax, double yMax)
Bounds (double xMin, double yMin, double zMin, double xMax, double yMax, double zMax)
void set (const Bounds &other)
void set (const Point &min, const Point &max)
const Point & min () const
const Point & max () const
const Point & mid () const
bool overlaps (const Bounds &other, bool force2d=false) const
bool contains (const Bounds &other, bool force2d=false) const
bool contains (const Point &p) const
double width () const
double depth () const
double height () const
double area () const
double volume () const
void goNwu ()
void goNwd (const bool force2d=false)
void goNeu ()
void goNed (const bool force2d=false)
void goSwu ()
void goSwd (const bool force2d=false)
void goSeu ()
void goSed (const bool force2d=false)
Bounds getNwd (bool force2d=false) const
Bounds getNed (bool force2d=false) const
Bounds getSwd (bool force2d=false) const
Bounds getSed (bool force2d=false) const
Bounds getNwu () const
Bounds getNeu () const
Bounds getSwu () const
Bounds getSeu () const
void go (Dir dir, bool force2d=false)
Bounds get (Dir dir, bool force2d=false) const
bool exists () const
bool is3d () const
Json::Value toJson () const
void grow (const Bounds &bounds)
void grow (const Point &p)
void shrink (const Bounds &bounds)
bool isCubic () const
Bounds growBy (double ratio) const
std::vector< Bounds > explode () const
Bounds transform (const Transformation &t) const
Bounds intersection (const Bounds &b) const
Bounds scale (const Point &scale, const Point &offset)
Bounds unscale (const Point &scale, const Point &offset)
Private Member Functions
void setMid ()
Private Attributes
Point m_min
Point m_max
Point m_mid
Detailed Description
Definition at line 26 of file bounds.hpp.
Constructor & Destructor Documentation
pdal::entwine::Bounds::Bounds () default
Referenced by growBy().
pdal::entwine::Bounds::Bounds (const Point & min, const Point & max)
Definition at line 22 of file bounds.cpp.
References setMid(), pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
pdal::entwine::Bounds::Bounds (const Point & center, double radius)
Definition at line 75 of file bounds.cpp.
pdal::entwine::Bounds::Bounds (const Json::Value & json)
Definition at line 40 of file bounds.cpp.
References is3d(), m_max, and m_min.
pdal::entwine::Bounds::Bounds (double xMin, double yMin, double xMax, double yMax)
Definition at line 89 of file bounds.cpp.
pdal::entwine::Bounds::Bounds (double xMin, double yMin, double zMin, double xMax, double yMax, double zMax)
Definition at line 79 of file bounds.cpp.
Member Function Documentation
double pdal::entwine::Bounds::area () const
Definition at line 98 of file bounds.hpp.
bool pdal::entwine::Bounds::contains (const Bounds & other, bool force2d = false) const
Definition at line 75 of file bounds.hpp.
References m_max, m_min, pdal::entwine::Point::x, and pdal::entwine::Point::y.
Referenced by TEST_F().
bool pdal::entwine::Bounds::contains (const Point & p) const
Definition at line 92 of file bounds.hpp.
double pdal::entwine::Bounds::depth () const
Definition at line 95 of file bounds.hpp.
Referenced by overlaps().
bool pdal::entwine::Bounds::exists () const
Definition at line 228 of file bounds.hpp.
References pdal::entwine::Point::exists().
std::vector<Bounds> pdal::entwine::Bounds::explode () const
Bounds pdal::entwine::Bounds::get (Dir dir, bool force2d = false) const
Definition at line 207 of file bounds.hpp.
References pdal::entwine::ned, pdal::entwine::neu, pdal::entwine::nwd, pdal::entwine::nwu, pdal::entwine::sed, pdal::entwine::seu, pdal::entwine::swd, pdal::entwine::swu, pdal::entwine::toDir(), and pdal::entwine::toIntegral().
Bounds pdal::entwine::Bounds::getNed (bool force2d = false) const
Definition at line 170 of file bounds.hpp.
References b, and goNed().
Bounds pdal::entwine::Bounds::getNeu () const
Definition at line 186 of file bounds.hpp.
References b, and goNeu().
Bounds pdal::entwine::Bounds::getNwd (bool force2d = false) const
Definition at line 165 of file bounds.hpp.
References b, and goNwd().
Bounds pdal::entwine::Bounds::getNwu () const
Definition at line 185 of file bounds.hpp.
References b, and goNwu().
Bounds pdal::entwine::Bounds::getSed (bool force2d = false) const
Definition at line 180 of file bounds.hpp.
References b, and goSed().
Bounds pdal::entwine::Bounds::getSeu () const
Definition at line 188 of file bounds.hpp.
References b, and goSeu().
Bounds pdal::entwine::Bounds::getSwd (bool force2d = false) const
Definition at line 175 of file bounds.hpp.
References b, and goSwd().
Bounds pdal::entwine::Bounds::getSwu () const
Definition at line 187 of file bounds.hpp.
References b, and goSwu().
void pdal::entwine::Bounds::go (Dir dir, bool force2d = false)
Definition at line 190 of file bounds.hpp.
References pdal::entwine::ned, pdal::entwine::neu, pdal::entwine::nwd, pdal::entwine::nwu, pdal::entwine::sed, pdal::entwine::seu, pdal::entwine::swd, pdal::entwine::swu, pdal::entwine::toDir(), and pdal::entwine::toIntegral().
void pdal::entwine::Bounds::goNed (const bool force2d = false)
Definition at line 125 of file bounds.hpp.
Referenced by getNed().
void pdal::entwine::Bounds::goNeu ()
Definition at line 117 of file bounds.hpp.
Referenced by getNeu().
void pdal::entwine::Bounds::goNwd (const bool force2d = false)
Definition at line 109 of file bounds.hpp.
Referenced by getNwd().
void pdal::entwine::Bounds::goNwu ()
Definition at line 101 of file bounds.hpp.
Referenced by getNwu().
void pdal::entwine::Bounds::goSed (const bool force2d = false)
Definition at line 157 of file bounds.hpp.
Referenced by getSed().
void pdal::entwine::Bounds::goSeu ()
Definition at line 149 of file bounds.hpp.
Referenced by getSeu().
void pdal::entwine::Bounds::goSwd (const bool force2d = false)
Definition at line 141 of file bounds.hpp.
Referenced by getSwd().
void pdal::entwine::Bounds::goSwu ()
Definition at line 133 of file bounds.hpp.
Referenced by getSwu().
void pdal::entwine::Bounds::grow (const Bounds & bounds)
Definition at line 112 of file bounds.cpp.
References max(), and min().
void pdal::entwine::Bounds::grow (const Point & p)
Definition at line 118 of file bounds.cpp.
References m_max, m_min, setMid(), pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Bounds pdal::entwine::Bounds::growBy (double ratio) const
Definition at line 136 of file bounds.cpp.
References Bounds(), m_max, m_mid, m_min, pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
double pdal::entwine::Bounds::height () const
Definition at line 96 of file bounds.hpp.
Referenced by overlaps().
Bounds pdal::entwine::Bounds::intersection (const Bounds & b) const
Definition at line 251 of file bounds.hpp.
References max(), pdal::entwine::Point::max(), min(), and pdal::entwine::Point::min().
bool pdal::entwine::Bounds::is3d () const
Definition at line 229 of file bounds.hpp.
Referenced by Bounds(), and toJson().
bool pdal::entwine::Bounds::isCubic () const
Definition at line 237 of file bounds.hpp.
const Point& pdal::entwine::Bounds::max () const
Definition at line 57 of file bounds.hpp.
Referenced by grow(), intersection(), pdal::entwine::operator<<(), pdal::entwine::operator==(), and shrink().
const Point& pdal::entwine::Bounds::mid () const
Definition at line 58 of file bounds.hpp.
Referenced by pdal::entwine::operator<(), and overlaps().
const Point& pdal::entwine::Bounds::min () const
Definition at line 56 of file bounds.hpp.
Referenced by grow(), intersection(), pdal::entwine::operator<<(), pdal::entwine::operator==(), and shrink().
bool pdal::entwine::Bounds::overlaps (const Bounds & other, bool force2d = false) const
Definition at line 61 of file bounds.hpp.
References depth(), height(), mid(), and width().
Bounds pdal::entwine::Bounds::scale (const Point & scale, const Point & offset)
Definition at line 256 of file bounds.hpp.
References pdal::entwine::Point::scale().
void pdal::entwine::Bounds::set (const Bounds & other)
Definition at line 42 of file bounds.hpp.
void pdal::entwine::Bounds::set (const Point & min, const Point & max)
Definition at line 49 of file bounds.hpp.
void pdal::entwine::Bounds::setMid () private
Definition at line 275 of file bounds.hpp.
References pdal::entwine::operator<<(), PDAL_DLL, pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Referenced by Bounds(), grow(), and shrink().
void pdal::entwine::Bounds::shrink (const Bounds & bounds)
Definition at line 129 of file bounds.cpp.
References m_max, m_min, max(), pdal::entwine::Point::max(), min(), pdal::entwine::Point::min(), and setMid().
Json::Value pdal::entwine::Bounds::toJson () const
Definition at line 97 of file bounds.cpp.
References is3d(), m_max, m_min, pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Referenced by pdal::GreyhoundReader::Args::query(), and TEST_F().
Bounds pdal::entwine::Bounds::transform (const Transformation & t) const
Definition at line 246 of file bounds.hpp.
References pdal::entwine::Point::transform().
Bounds pdal::entwine::Bounds::unscale (const Point & scale, const Point & offset)
Definition at line 263 of file bounds.hpp.
References pdal::entwine::Point::unscale().
double pdal::entwine::Bounds::volume () const
Definition at line 99 of file bounds.hpp.
double pdal::entwine::Bounds::width () const
Definition at line 94 of file bounds.hpp.
Referenced by overlaps().
Member Data Documentation
Point pdal::entwine::Bounds::m_max private
Definition at line 272 of file bounds.hpp.
Referenced by Bounds(), contains(), grow(), growBy(), shrink(), and toJson().
Point pdal::entwine::Bounds::m_mid private
Definition at line 273 of file bounds.hpp.
Referenced by growBy().
Point pdal::entwine::Bounds::m_min private
Definition at line 271 of file bounds.hpp.
Referenced by Bounds(), contains(), grow(), growBy(), shrink(), and toJson().
The documentation for this class was generated from the following files:
pdal/plugins/greyhound/io/bounds.hpp
pdal/plugins/greyhound/io/bounds.cpp