PDAL: pdal::TArg< bool > Class Template Reference
pdal::TArg< bool > Class Template Reference
#include <ProgramArgs.hpp>
Public Types
enum PosType { PosType::None, PosType::Required, PosType::Optional }
Public Member Functions
TArg (const std::string &longname, const std::string &shortname, const std::string &description, bool &variable, bool def)
TArg (const std::string &longname, const std::string &shortname, const std::string &description, bool &variable)
virtual bool needsValue () const
virtual void setValue (const std::string &s)
virtual void reset ()
virtual Arg & setPositional ()
virtual Arg & setOptionalPositional ()
virtual bool defaultProvided () const
virtual std::string defaultVal () const
Arg & setHidden (bool hidden=true)
virtual Arg & setErrorText (const std::string &error)
bool set () const
virtual void assignPositional (ArgValList &vals)
PosType positional () const
bool hidden () const
std::string description () const
std::string longname () const
std::string nameDescrip () const
std::string commandLine () const
Protected Attributes
std::string m_longname
std::string m_shortname
std::string m_description
std::string m_rawVal
bool m_set
bool m_hidden
PosType m_positional
std::string m_error
Private Attributes
bool & m_val
bool m_defaultVal
bool m_defaultProvided
Detailed Description
template<>
class pdal::TArg< bool >
Description of a boolean argument. Boolean arguments don't take values. Setting a boolean argument inverts its default value. Boolean arguments are normally 'false' by default.
Definition at line 488 of file ProgramArgs.hpp.
Member Enumeration Documentation
enum pdal::Arg::PosType strong inherited
Positional type. Either None, Optional or Required.
Enumerator
None
Not positional.
Required
Required positional.
Optional
Optional positional.
Definition at line 137 of file ProgramArgs.hpp.
Constructor & Destructor Documentation
pdal::TArg< bool >::TArg (const std::string & longname, const std::string & shortname, const std::string & description, bool & variable, bool def)
Constructor for boolean arguments with default value.
Parameters
longname Name of argument specified on command line with "--" prefix.
shortname Optional name of argument specified on command line with "-" prefix.
description Argument description.
variable bool variable to which the value of the argument should be bound.
def Default value to be assigned to the bound variable.
Definition at line 503 of file ProgramArgs.hpp.
pdal::TArg< bool >::TArg (const std::string & longname, const std::string & shortname, const std::string & description, bool & variable)
Constructor for boolean arguments without default value.
Parameters
longname Name of argument specified on command line with "--" prefix.
shortname Optional name of argument specified on command line with "-" prefix.
description Argument description.
variable bool variable to which the value of the argument should be bound.
Definition at line 520 of file ProgramArgs.hpp.
Member Function Documentation
virtual void pdal::Arg::assignPositional (ArgValList & vals) virtual inherited
Set the argument's value from the list of command-line args.
Note
Not intended to be called from user code.
Parameters
vals The list of command-line argument values.
Reimplemented in pdal::BaseVArg, and pdal::TArg< T >.
Definition at line 268 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::parse(), and pdal::ProgramArgs::parseSimple().
std::string pdal::Arg::commandLine () const inherited
Returns text indicating the name of the option suitable for displaying in "usage" text.
Note
Not intended to be called from user code.
Definition at line 319 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::commandLine().
virtual bool pdal::TArg< bool >::defaultProvided () const virtual
Return whether a default value was provided for the argument.
Returns
Whether a default was provided.
Reimplemented from pdal::Arg.
Definition at line 605 of file ProgramArgs.hpp.
virtual std::string pdal::TArg< bool >::defaultVal () const virtual
Return a string representation of an Arg's default value.
Returns
Default value as a string.
Reimplemented from pdal::Arg.
Definition at line 612 of file ProgramArgs.hpp.
References pdal::Utils::toString().
std::string pdal::Arg::description () const inherited
Returns the description of the argument.
Note
Not intended to be called from user code.
Returns
Argument description.
Definition at line 290 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::dump(), pdal::ProgramArgs::dump2(), and pdal::ProgramArgs::dump3().
bool pdal::Arg::hidden () const inherited
Returns whether the argument is hidden or not.
Note
Not intended to be called from user code.
Definition at line 282 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::commandLine(), and pdal::ProgramArgs::dump().
std::string pdal::Arg::longname () const inherited
Returns the longname of the argument.
Note
Not intended to be called from user code.
Returns
Argument long name.
Definition at line 298 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::dump2(), pdal::ProgramArgs::dump3(), and pdal::ProgramArgs::validate().
std::string pdal::Arg::nameDescrip () const inherited
Returns text indicating the longname and shortname of the option suitable for displaying in help information.
Note
Not intended to be called from user code.
Definition at line 306 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::dump().
virtual bool pdal::TArg< bool >::needsValue () const virtual
Return whether an option needs a value to be valid.
Returns
false Boolean values don't need a value.
Note
Not intended to be called from user code.
Reimplemented from pdal::Arg.
Definition at line 532 of file ProgramArgs.hpp.
PosType pdal::Arg::positional () const inherited
Returns the positional type of the argument.
Note
Not intended to be called from user code.
Definition at line 275 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::validate().
virtual void pdal::TArg< bool >::reset () virtual
Reset the argument's state.
Set the internal state of the argument and it's referenced variable as if no command-line parsing had occurred.
Note
For testing. Not intended to be called from user code.
Implements pdal::Arg.
Definition at line 568 of file ProgramArgs.hpp.
bool pdal::Arg::set () const inherited
Return whether the argument was set during command-line parsing.
Definition at line 215 of file ProgramArgs.hpp.
Referenced by pdal::NormalFilter::filter(), pdal::DividerFilter::initialize(), pdal::BpfWriter::initialize(), pdal::GDALWriter::prepared(), pdal::NormalFilter::prepared(), and pdal::ProgramArgs::set().
virtual Arg& pdal::Arg::setErrorText (const std::string & error) virtual inherited
Provide error text for the argument to override the default.
Parameters
error Error text.
Definition at line 207 of file ProgramArgs.hpp.
References pdal::arg_error::m_error.
Referenced by pdal::CropFilter::addArgs().
Arg& pdal::Arg::setHidden (bool hidden = true) inherited
Definition at line 169 of file ProgramArgs.hpp.
Referenced by App::addArgs(), pdal::PipelineKernel::addSwitches(), and pdal::InfoKernel::addSwitches().
virtual Arg& pdal::TArg< bool >::setOptionalPositional () virtual
Indicate that the argument is positional and optional.
Throws an exception to indicate that boolean arguments can't positional.
Reimplemented from pdal::Arg.
Definition at line 594 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error().
virtual Arg& pdal::TArg< bool >::setPositional () virtual
Indicate that the argument is positional.
Throws an exception to indicate that boolean arguments can't positional.
Reimplemented from pdal::Arg.
Definition at line 581 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error().
virtual void pdal::TArg< bool >::setValue (const std::string & s) virtual
Set a an argument's value from a string.
Note
The argumet is either 'true' or 'false'. True means that we're setting the option, which sets the negative of the default value. False sets the option to the default value (essentially a no-op).
Not intended to be called from user code.
Parameters
s Value to set [ignored].
Implements pdal::Arg.
Definition at line 545 of file ProgramArgs.hpp.
Member Data Documentation
bool pdal::TArg< bool >::m_defaultProvided private
Definition at line 618 of file ProgramArgs.hpp.
bool pdal::TArg< bool >::m_defaultVal private
Definition at line 617 of file ProgramArgs.hpp.
std::string pdal::Arg::m_description protected inherited
Definition at line 332 of file ProgramArgs.hpp.
std::string pdal::Arg::m_error protected inherited
Definition at line 337 of file ProgramArgs.hpp.
bool pdal::Arg::m_hidden protected inherited
Definition at line 335 of file ProgramArgs.hpp.
std::string pdal::Arg::m_longname protected inherited
Definition at line 330 of file ProgramArgs.hpp.
PosType pdal::Arg::m_positional protected inherited
Definition at line 336 of file ProgramArgs.hpp.
std::string pdal::Arg::m_rawVal protected inherited
Definition at line 333 of file ProgramArgs.hpp.
bool pdal::Arg::m_set protected inherited
Definition at line 334 of file ProgramArgs.hpp.
std::string pdal::Arg::m_shortname protected inherited
Definition at line 331 of file ProgramArgs.hpp.
bool& pdal::TArg< bool >::m_val private
Definition at line 616 of file ProgramArgs.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/util/ProgramArgs.hpp