PDAL: pdal::PipelineKernel Class Reference
pdal::PipelineKernel Class Reference
#include <PipelineKernel.hpp>
Public Member Functions
std::string getName () const
int execute ()
int run (const StringList &cmdArgs, LogPtr &log)
std::string getShortName () const
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
Protected Member Functions
Stage & makeReader (const std::string &inputFile, std::string driver)
Stage & makeReader (const std::string &inputFile, std::string driver, Options options)
Stage & makeFilter (const std::string &driver, Stage &parent)
Stage & makeFilter (const std::string &driver, Stage &parent, Options options)
Stage & makeFilter (const std::string &driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver, Options options)
Protected Attributes
LogPtr m_log
PipelineManager m_manager
std::string m_driverOverride
Private Member Functions
PipelineKernel ()
void addSwitches (ProgramArgs &args)
void validateSwitches (ProgramArgs &args)
virtual bool isStagePrefix (const std::string &stage)
Private Attributes
std::string m_inputFile
std::string m_pipelineFile
std::string m_metadataFile
bool m_validate
std::string m_PointCloudSchemaOutput
std::string m_progressFile
int m_progressFd
bool m_usestdin
bool m_stream
Detailed Description
Definition at line 49 of file PipelineKernel.hpp.
Constructor & Destructor Documentation
pdal::PipelineKernel::PipelineKernel () private
Definition at line 54 of file PipelineKernel.cpp.
Member Function Documentation
void pdal::PipelineKernel::addSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 74 of file PipelineKernel.cpp.
References pdal::ProgramArgs::add(), m_inputFile, m_metadataFile, m_pipelineFile, m_PointCloudSchemaOutput, m_progressFile, m_stream, m_usestdin, m_validate, pdal::Arg::setHidden(), and pdal::Arg::setOptionalPositional().
static void* pdal::PipelineKernel::create () static
static int32_t pdal::PipelineKernel::destroy (void *) static
int pdal::PipelineKernel::execute () virtual
Implements pdal::Kernel.
Definition at line 95 of file PipelineKernel.cpp.
References pdal::Utils::closeFile(), pdal::Utils::closeProgress(), pdal::Utils::createFile(), pdal::PipelineManager::execute(), pdal::PipelineManager::executeStream(), pdal::Utils::fileExists(), pdal::PipelineManager::getMetadata(), pdal::PipelineManager::getStage(), pdal::BasePointTable::layout(), m_inputFile, pdal::Kernel::m_manager, m_metadataFile, m_pipelineFile, m_PointCloudSchemaOutput, m_progressFd, m_progressFile, m_stream, m_validate, pdal::Utils::openProgress(), pdal::PipelineManager::pointTable(), pdal::PipelineManager::prepare(), pdal::PipelineManager::readPipeline(), pdal::PipelineManager::setProgressFd(), pdal::Utils::toJSON(), pdal::PipelineWriter::writePipeline(), and xml.
std::string pdal::PipelineKernel::getName () const virtual
Implements pdal::Kernel.
Definition at line 52 of file PipelineKernel.cpp.
References pdal::PluginInfo::name.
std::string pdal::Kernel::getShortName () const inherited
Definition at line 67 of file Kernel.hpp.
References pdal::Utils::split2().
Referenced by pdal::Kernel::outputHelp().
bool pdal::PipelineKernel::isStagePrefix (const std::string & stage) private virtual
Reimplemented from pdal::Kernel.
Definition at line 68 of file PipelineKernel.cpp.
References pdal::Kernel::isStagePrefix().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent) protected inherited
Definition at line 320 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent, Options options) protected inherited
Definition at line 326 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeFilter (const std::string & driver) protected inherited
Definition at line 314 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver) protected inherited
Definition at line 301 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver, Options options) protected inherited
Definition at line 307 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver) protected inherited
Definition at line 333 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver, Options options) protected inherited
Definition at line 340 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
int pdal::Kernel::run (const StringList & cmdArgs, LogPtr & log) inherited
Definition at line 229 of file Kernel.cpp.
References pdal::Kernel::doExecution(), pdal::Kernel::doStartup(), pdal::Kernel::doSwitches(), setup::log, pdal::Kernel::m_log, pdal::Kernel::m_manager, pdal::Kernel::m_showHelp, pdal::Kernel::outputHelp(), pdal::Utils::printError(), and pdal::PipelineManager::setLog().
Referenced by App::execute().
void pdal::PipelineKernel::validateSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 58 of file PipelineKernel.cpp.
References m_inputFile, and m_usestdin.
Member Data Documentation
std::string pdal::Kernel::m_driverOverride protected inherited
Definition at line 105 of file Kernel.hpp.
Referenced by pdal::Kernel::addBasicSwitches(), pdal::MergeKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::DiffKernel::execute(), pdal::DeltaKernel::loadSet(), pdal::InfoKernel::makePipeline(), and pdal::TIndexKernel::mergeFile().
std::string pdal::PipelineKernel::m_inputFile private
Definition at line 63 of file PipelineKernel.hpp.
Referenced by addSwitches(), execute(), and validateSwitches().
LogPtr pdal::Kernel::m_log protected inherited
Definition at line 103 of file Kernel.hpp.
Referenced by pdal::TIndexKernel::createFeature(), pdal::TIndexKernel::createFile(), pdal::TIndexKernel::createLayer(), pdal::InfoKernel::dumpPoints(), pdal::TranslateKernel::execute(), and pdal::Kernel::run().
PipelineManager pdal::Kernel::m_manager protected inherited
Definition at line 104 of file Kernel.hpp.
Referenced by pdal::Kernel::doSwitches(), pdal::InfoKernel::dump(), pdal::SmoothKernel::execute(), pdal::DensityKernel::execute(), execute(), pdal::TranslateKernel::execute(), pdal::TIndexKernel::getFileInfo(), pdal::TranslateKernel::makeArgPipeline(), pdal::Kernel::makeFilter(), pdal::TranslateKernel::makeJSONPipeline(), pdal::InfoKernel::makePipeline(), pdal::Kernel::makeReader(), pdal::Kernel::makeWriter(), pdal::InfoKernel::run(), pdal::Kernel::run(), and pdal::InfoKernel::setup().
std::string pdal::PipelineKernel::m_metadataFile private
Definition at line 65 of file PipelineKernel.hpp.
Referenced by addSwitches(), and execute().
std::string pdal::PipelineKernel::m_pipelineFile private
Definition at line 64 of file PipelineKernel.hpp.
Referenced by addSwitches(), and execute().
std::string pdal::PipelineKernel::m_PointCloudSchemaOutput private
Definition at line 67 of file PipelineKernel.hpp.
Referenced by addSwitches(), and execute().
int pdal::PipelineKernel::m_progressFd private
Definition at line 69 of file PipelineKernel.hpp.
Referenced by execute().
std::string pdal::PipelineKernel::m_progressFile private
Definition at line 68 of file PipelineKernel.hpp.
Referenced by addSwitches(), and execute().
bool pdal::PipelineKernel::m_stream private
Definition at line 71 of file PipelineKernel.hpp.
Referenced by addSwitches(), and execute().
bool pdal::PipelineKernel::m_usestdin private
Definition at line 70 of file PipelineKernel.hpp.
Referenced by addSwitches(), and validateSwitches().
bool pdal::PipelineKernel::m_validate private
Definition at line 66 of file PipelineKernel.hpp.
Referenced by addSwitches(), and execute().
The documentation for this class was generated from the following files:
pdal/kernels/PipelineKernel.hpp
pdal/kernels/PipelineKernel.cpp