PDAL: PgpointcloudWriterTest Class Reference
PgpointcloudWriterTest Class Reference
Public Member Functions
PgpointcloudWriterTest ()
Protected Member Functions
virtual void SetUp ()
void executeOnTestDb (const std::string &sql)
virtual void TearDown ()
bool shouldSkipTests () const
Private Member Functions
void executeOnMasterDb (const std::string &sql)
void execute (PGconn *connection, const std::string &sql)
void dropTestDb ()
Private Attributes
PGconn * m_masterConnection
PGconn * m_testConnection
bool m_bSkipTests
Detailed Description
Definition at line 91 of file PgpointcloudWriterTest.cpp.
Constructor & Destructor Documentation
PgpointcloudWriterTest::PgpointcloudWriterTest ()
Definition at line 94 of file PgpointcloudWriterTest.cpp.
Member Function Documentation
void PgpointcloudWriterTest::dropTestDb () private
Definition at line 167 of file PgpointcloudWriterTest.cpp.
void PgpointcloudWriterTest::execute (PGconn * connection, const std::string & sql) private
Definition at line 162 of file PgpointcloudWriterTest.cpp.
References pdal::pg_execute().
void PgpointcloudWriterTest::executeOnMasterDb (const std::string & sql) private
Definition at line 157 of file PgpointcloudWriterTest.cpp.
References pdal::pg_execute().
void PgpointcloudWriterTest::executeOnTestDb (const std::string & sql) protected
Definition at line 134 of file PgpointcloudWriterTest.cpp.
References pdal::pg_execute().
virtual void PgpointcloudWriterTest::SetUp () protected virtual
Definition at line 97 of file PgpointcloudWriterTest.cpp.
References anonymous_namespace{PgpointcloudWriterTest.cpp}::getMasterDBConn(), anonymous_namespace{PgpointcloudWriterTest.cpp}::getTestDBTempConn(), and pdal::pg_connect().
bool PgpointcloudWriterTest::shouldSkipTests () const protected
Definition at line 153 of file PgpointcloudWriterTest.cpp.
virtual void PgpointcloudWriterTest::TearDown () protected virtual
Definition at line 139 of file PgpointcloudWriterTest.cpp.
Member Data Documentation
bool PgpointcloudWriterTest::m_bSkipTests private
Definition at line 176 of file PgpointcloudWriterTest.cpp.
PGconn* PgpointcloudWriterTest::m_masterConnection private
Definition at line 174 of file PgpointcloudWriterTest.cpp.
PGconn* PgpointcloudWriterTest::m_testConnection private
Definition at line 175 of file PgpointcloudWriterTest.cpp.
The documentation for this class was generated from the following file:
pdal/plugins/pgpointcloud/test/PgpointcloudWriterTest.cpp