PDAL: pdal::Charbuf Class Reference
pdal::Charbuf Class Reference
#include <Charbuf.hpp>
Public Member Functions
PDAL_DLL Charbuf ()
PDAL_DLL Charbuf (std::vector< char > &v, pos_type bufOffset=0)
PDAL_DLL Charbuf (char *buf, size_t count, pos_type bufOffset=0)
PDAL_DLL void initialize (char *buf, size_t count, pos_type bufOffset=0)
Protected Member Functions
PDAL_DLL std::ios::pos_type seekpos (std::ios::pos_type pos, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
PDAL_DLL std::ios::pos_type seekoff (std::ios::off_type off, std::ios_base::seekdir dir, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
Private Attributes
std::ios::pos_type m_bufOffset
char * m_buf
Detailed Description
Allow a data buffer to be used at a std::streambuf.
Definition at line 49 of file Charbuf.hpp.
Constructor & Destructor Documentation
PDAL_DLL pdal::Charbuf::Charbuf ()
Construct an empty Charbuf.
Definition at line 55 of file Charbuf.hpp.
PDAL_DLL pdal::Charbuf::Charbuf (std::vector< char > & v, pos_type bufOffset = 0)
Construct a Charbuf that wraps a byte vector.
Parameters
v Byte vector to back streambuf.
bufOffset Offset in vector (ignore bytes before offset).
Definition at line 64 of file Charbuf.hpp.
References initialize().
PDAL_DLL pdal::Charbuf::Charbuf (char * buf, size_t count, pos_type bufOffset = 0)
Construct a Charbuf that wraps a byte buffer.
Parameters
buf Buffer to back streambuf.
count Size of buffer.
bufOffset Offset in vector (ignore bytes before offset).
Definition at line 74 of file Charbuf.hpp.
References initialize(), PDAL_DLL, seekoff(), and seekpos().
Member Function Documentation
void pdal::Charbuf::initialize (char * buf, size_t count, pos_type bufOffset = 0)
Set a buffer to back a Charbuf.
Parameters
buf Buffer to back streambuf.
count Size of buffer.
bufOffset Offset in vector (ignore bytes before offset).
Definition at line 41 of file Charbuf.cpp.
References m_buf, and m_bufOffset.
Referenced by Charbuf(), and pdal::BpfReader::ready().
std::ios::pos_type pdal::Charbuf::seekoff (std::ios::off_type off, std::ios_base::seekdir dir, std::ios_base::openmode which = std::ios_base::in | std::ios_base::out) protected
Seek to a position based on an offset from a position.
Parameters
off Offset from current position.
dir Offset basis (beg, cur or end)
which I/O mode [default: rw]
Returns
Current position adjusted for buffer offset.
Definition at line 72 of file Charbuf.cpp.
References m_buf, and m_bufOffset.
Referenced by Charbuf().
std::ios::pos_type pdal::Charbuf::seekpos (std::ios::pos_type pos, std::ios_base::openmode which = std::ios_base::in | std::ios_base::out) protected
Seek to a position in the buffer.
Parameters
pos Position to seek to.
which I/O mode [default: rw]
Returns
Current position adjusted for buffer offset.
Definition at line 50 of file Charbuf.cpp.
References m_buf, and m_bufOffset.
Referenced by Charbuf().
Member Data Documentation
char* pdal::Charbuf::m_buf private
For the put pointer, it seems we need the beginning of the buffer in order to deal with offsets.
Definition at line 120 of file Charbuf.hpp.
Referenced by initialize(), seekoff(), and seekpos().
std::ios::pos_type pdal::Charbuf::m_bufOffset private
Offset that allows one to seek to positions not based on the beginning of the backing vector, but to some other reference point.
Definition at line 114 of file Charbuf.hpp.
Referenced by initialize(), seekoff(), and seekpos().
The documentation for this class was generated from the following files:
pdal/pdal/util/Charbuf.hpp
pdal/pdal/util/Charbuf.cpp