PDAL: pdal::ISwitchableStream Class Reference
pdal::ISwitchableStream Class Reference
#include <IStream.hpp>
Public Member Functions
PDAL_DLL ISwitchableStream ()
PDAL_DLL ISwitchableStream (const std::string &filename)
PDAL_DLL ISwitchableStream (std::istream *stream)
PDAL_DLL bool isLittleEndian () const
PDAL_DLL void switchToLittleEndian ()
PDAL_DLL void switchToBigEndian ()
PDAL_DLL ISwitchableStream & operator>> (uint8_t &v)
PDAL_DLL ISwitchableStream & operator>> (int8_t &v)
PDAL_DLL ISwitchableStream & operator>> (uint16_t &v)
PDAL_DLL ISwitchableStream & operator>> (int16_t &v)
PDAL_DLL ISwitchableStream & operator>> (uint32_t &v)
PDAL_DLL ISwitchableStream & operator>> (int32_t &v)
PDAL_DLL ISwitchableStream & operator>> (uint64_t &v)
PDAL_DLL ISwitchableStream & operator>> (int64_t &v)
PDAL_DLL ISwitchableStream & operator>> (float &v)
PDAL_DLL ISwitchableStream & operator>> (double &v)
PDAL_DLL int open (const std::string &filename)
PDAL_DLL void close ()
PDAL_DLL operator bool ()
PDAL_DLL void seek (std::streampos pos)
PDAL_DLL void seek (std::streampos off, std::ios_base::seekdir way)
PDAL_DLL void skip (std::streamoff offset)
PDAL_DLL std::streampos position () const
PDAL_DLL bool good () const
PDAL_DLL std::istream * stream ()
PDAL_DLL void pushStream (std::istream *strm)
PDAL_DLL std::istream * popStream ()
PDAL_DLL void get (std::string &s, size_t size)
PDAL_DLL void get (std::vector< char > &buf)
PDAL_DLL void get (std::vector< unsigned char > &buf)
PDAL_DLL void get (char *buf, size_t size)
PDAL_DLL void get (unsigned char *buf, size_t size)
Static Public Attributes
static const bool DefaultIsLittleEndian = true
Protected Attributes
std::istream * m_stream
std::ifstream * m_fstream
Private Attributes
bool m_isLittleEndian
Detailed Description
Stream wrapper for input of binary data that converts from either little-endian or big-endian to host ordering, depending on object settings.
Definition at line 589 of file IStream.hpp.
Constructor & Destructor Documentation
PDAL_DLL pdal::ISwitchableStream::ISwitchableStream ()
Definition at line 594 of file IStream.hpp.
PDAL_DLL pdal::ISwitchableStream::ISwitchableStream (const std::string & filename)
Definition at line 597 of file IStream.hpp.
PDAL_DLL pdal::ISwitchableStream::ISwitchableStream (std::istream * stream)
Definition at line 602 of file IStream.hpp.
Member Function Documentation
PDAL_DLL void pdal::IStream::close () inherited
Close the underlying stream.
Definition at line 105 of file IStream.hpp.
References pdal::IStream::m_fstream, and pdal::IStream::m_stream.
Referenced by pdal::BpfReader::done(), and pdal::BpfReader::initialize().
PDAL_DLL void pdal::IStream::get (std::string & s, size_t size) inherited
Fetch data from the stream into a string.
Parameters
s String to fill.
size Number of bytes to extract.
Definition at line 204 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::Dimension::size().
Referenced by pdal::LasHeader::get(), pdal::OptechReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::lasdump::operator>>(), pdal::operator>>(), pdal::BpfDimension::read(), pdal::BpfUlemHeader::read(), pdal::BpfUlemFile::read(), pdal::BpfPolarHeader::read(), pdal::BpfReader::readHeaderExtraData(), pdal::lasdump::Dumper::readPoints(), pdal::BpfHeader::readV3(), and pdal::BpfReader::seekByteMajor().
PDAL_DLL void pdal::IStream::get (std::vector< char > & buf) inherited
Fetch data from the stream into a vector of char.
Parameters
buf Buffer to fill.
Definition at line 220 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL void pdal::IStream::get (std::vector< unsigned char > & buf) inherited
Fetch data from the stream into a vector of unsigned char.
Parameters
buf Buffer to fill.
Definition at line 230 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL void pdal::IStream::get (char * buf, size_t size) inherited
Fetch data from the stream into the specified buffer of char.
Parameters
buf Buffer to fill.
size Number of bytes to extract.
Definition at line 241 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::Dimension::size().
PDAL_DLL void pdal::IStream::get (unsigned char * buf, size_t size) inherited
Fetch data from the stream into the specified buffer of unsigned char.
Parameters
buf Buffer to fill.
size Number of bytes to extract.
Definition at line 250 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::Dimension::size().
PDAL_DLL bool pdal::IStream::good () const inherited
Determine if the underlying stream is good.
Returns
Whether the underlying stream is good.
Definition at line 159 of file IStream.hpp.
References pdal::IStream::m_stream.
Referenced by pdal::lasdump::Dumper::dump().
PDAL_DLL bool pdal::ISwitchableStream::isLittleEndian () const
Definition at line 607 of file IStream.hpp.
PDAL_DLL int pdal::IStream::open (const std::string & filename) inherited
Open a file to extract.
Parameters
filename Filename.
Returns
-1 if a stream is already assigned, 0 otherwise.
Definition at line 93 of file IStream.hpp.
References pdal::IStream::m_fstream, and pdal::IStream::m_stream.
Referenced by pdal::BpfReader::initialize(), pdal::IStream::IStream(), and pdal::BpfReader::ready().
PDAL_DLL pdal::IStream::operator bool () inherited
Return the state of the stream.
Returns
The state of the underlying stream.
Definition at line 117 of file IStream.hpp.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (uint8_t & v)
Definition at line 614 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (int8_t & v)
Definition at line 620 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (uint16_t & v)
Definition at line 626 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (int16_t & v)
Definition at line 633 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (uint32_t & v)
Definition at line 641 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (int32_t & v)
Definition at line 648 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (uint64_t & v)
Definition at line 656 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (int64_t & v)
Definition at line 663 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (float & v)
Definition at line 671 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL ISwitchableStream& pdal::ISwitchableStream::operator>> (double & v)
Definition at line 680 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL std::istream* pdal::IStream::popStream () inherited
Pop the current stream and return it. The last stream on the stack cannot be popped.
Returns
Pointer to the popped stream.
Definition at line 187 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::IStream::m_streams.
Referenced by pdal::BpfReader::done().
PDAL_DLL std::streampos pdal::IStream::position () const inherited
Determine the position of the get pointer.
Returns
Current get position.
Definition at line 151 of file IStream.hpp.
References pdal::IStream::m_stream.
Referenced by pdal::QfitReader::initialize(), pdal::BpfReader::initialize(), pdal::BpfReader::readHeaderExtraData(), and pdal::BpfReader::ready().
PDAL_DLL void pdal::IStream::pushStream (std::istream * strm) inherited
Temporarily push a stream to read from.
Parameters
strm New stream to read from.
Definition at line 175 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::IStream::m_streams.
Referenced by pdal::BpfReader::ready().
PDAL_DLL void pdal::IStream::seek (std::streampos pos) inherited
Seek to a position in the underlying stream.
Parameters
pos Position to seek to,
Definition at line 125 of file IStream.hpp.
References pdal::IStream::m_stream.
Referenced by pdal::lasdump::Dumper::dump(), pdal::QfitReader::initialize(), pdal::BpfReader::initialize(), pdal::operator>>(), pdal::PlyReader::ListProperty::read(), pdal::BpfReader::ready(), pdal::BpfReader::seekByteMajor(), pdal::BpfReader::seekDimMajor(), and pdal::BpfReader::seekPointMajor().
PDAL_DLL void pdal::IStream::seek (std::streampos off, std::ios_base::seekdir way) inherited
Seek to an offset from a specified position.
Parameters
off Offset.
way Absolute position for offset (beg, end or cur)
Definition at line 135 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL void pdal::IStream::skip (std::streamoff offset) inherited
Skip relative to the current position.
Parameters
offset Offset from the current position.
Definition at line 143 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL std::istream* pdal::IStream::stream () inherited
Fetch a pointer to the underlying stream.
Returns
Pointer to the underlying stream.
Definition at line 167 of file IStream.hpp.
References pdal::IStream::m_stream.
Referenced by pdal::lasdump::Dumper::readCompressedPoints().
PDAL_DLL void pdal::ISwitchableStream::switchToBigEndian ()
Definition at line 611 of file IStream.hpp.
Referenced by pdal::QfitReader::initialize().
PDAL_DLL void pdal::ISwitchableStream::switchToLittleEndian ()
Definition at line 609 of file IStream.hpp.
Member Data Documentation
const bool pdal::ISwitchableStream::DefaultIsLittleEndian = true static
Definition at line 592 of file IStream.hpp.
std::ifstream* pdal::IStream::m_fstream protected inherited
Definition at line 255 of file IStream.hpp.
Referenced by pdal::IStream::close(), pdal::IStream::open(), and pdal::IStream::~IStream().
bool pdal::ISwitchableStream::m_isLittleEndian private
Definition at line 690 of file IStream.hpp.
std::istream* pdal::IStream::m_stream protected inherited
Definition at line 254 of file IStream.hpp.
Referenced by pdal::IStream::close(), pdal::IStream::get(), pdal::IStream::good(), pdal::IStreamMarker::IStreamMarker(), pdal::IStream::open(), pdal::ILeStream::operator>>(), pdal::IBeStream::operator>>(), operator>>(), pdal::IStream::popStream(), pdal::IStream::position(), pdal::IStream::pushStream(), pdal::IStreamMarker::rewind(), pdal::IStream::seek(), pdal::IStream::skip(), and pdal::IStream::stream().
The documentation for this class was generated from the following file:
pdal/pdal/util/IStream.hpp