PDAL: pdal::TranslateKernel Class Reference
pdal::TranslateKernel Class Reference
#include <TranslateKernel.hpp>
Public Member Functions
std::string getName () const
int execute ()
int run (const StringList &cmdArgs, LogPtr &log)
std::string getShortName () const
virtual void validateSwitches (ProgramArgs &args)
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
Protected Member Functions
Stage & makeReader (const std::string &inputFile, std::string driver)
Stage & makeReader (const std::string &inputFile, std::string driver, Options options)
Stage & makeFilter (const std::string &driver, Stage &parent)
Stage & makeFilter (const std::string &driver, Stage &parent, Options options)
Stage & makeFilter (const std::string &driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver, Options options)
virtual bool isStagePrefix (const std::string &stageType)
Protected Attributes
LogPtr m_log
PipelineManager m_manager
std::string m_driverOverride
Private Member Functions
TranslateKernel ()
virtual void addSwitches (ProgramArgs &args)
void makeJSONPipeline ()
void makeArgPipeline ()
Private Attributes
std::string m_inputFile
std::string m_outputFile
std::string m_pipelineOutputFile
std::string m_readerType
StringList m_filterType
std::string m_writerType
std::string m_filterJSON
std::string m_metadataFile
Detailed Description
Definition at line 53 of file TranslateKernel.hpp.
Constructor & Destructor Documentation
pdal::TranslateKernel::TranslateKernel () private
Definition at line 72 of file TranslateKernel.cpp.
Member Function Documentation
void pdal::TranslateKernel::addSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 75 of file TranslateKernel.cpp.
References pdal::ProgramArgs::add(), m_filterJSON, m_filterType, m_inputFile, m_metadataFile, m_outputFile, m_pipelineOutputFile, m_readerType, and m_writerType.
static void* pdal::TranslateKernel::create () static
static int32_t pdal::TranslateKernel::destroy (void *) static
int pdal::TranslateKernel::execute () virtual
Implements pdal::Kernel.
Definition at line 176 of file TranslateKernel.cpp.
References pdal::FileUtils::closeFile(), pdal::FileUtils::createFile(), pdal::PipelineManager::execute(), pdal::PipelineManager::getMetadata(), pdal::PipelineManager::getStage(), pdal::Info, m_filterJSON, m_filterType, pdal::Kernel::m_log, pdal::Kernel::m_manager, m_metadataFile, m_pipelineOutputFile, makeArgPipeline(), makeJSONPipeline(), pdal::Utils::toJSON(), and pdal::PipelineWriter::writePipeline().
std::string pdal::TranslateKernel::getName () const virtual
Implements pdal::Kernel.
Definition at line 67 of file TranslateKernel.cpp.
References pdal::PluginInfo::name.
std::string pdal::Kernel::getShortName () const inherited
Definition at line 67 of file Kernel.hpp.
References pdal::Utils::split2().
Referenced by pdal::Kernel::outputHelp().
bool pdal::Kernel::isStagePrefix (const std::string & stageType) protected virtual inherited
Reimplemented in pdal::PipelineKernel.
Definition at line 58 of file Kernel.cpp.
Referenced by pdal::PipelineKernel::isStagePrefix(), and pdal::Kernel::parseStageOption().
void pdal::TranslateKernel::makeArgPipeline () private
Definition at line 149 of file TranslateKernel.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), m_filterType, m_inputFile, pdal::Kernel::m_manager, m_outputFile, m_readerType, m_writerType, pdal::PipelineManager::makeFilter(), pdal::PipelineManager::makeReader(), pdal::PipelineManager::makeWriter(), and pdal::Utils::startsWith().
Referenced by execute().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent) protected inherited
Definition at line 320 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent, Options options) protected inherited
Definition at line 326 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeFilter (const std::string & driver) protected inherited
Definition at line 314 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
void pdal::TranslateKernel::makeJSONPipeline () private
Definition at line 96 of file TranslateKernel.cpp.
References pdal::FileUtils::fileExists(), pdal::PipelineManager::leaves(), m_filterJSON, m_inputFile, pdal::Kernel::m_manager, m_outputFile, m_readerType, m_writerType, pdal::PipelineManager::makeReader(), pdal::PipelineManager::makeWriter(), pdal::FileUtils::readFileIntoString(), pdal::PipelineManager::readPipeline(), pdal::PipelineManager::replace(), pdal::PipelineManager::roots(), and pdal::Stage::tag().
Referenced by execute().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver) protected inherited
Definition at line 301 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver, Options options) protected inherited
Definition at line 307 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver) protected inherited
Definition at line 333 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver, Options options) protected inherited
Definition at line 340 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
int pdal::Kernel::run (const StringList & cmdArgs, LogPtr & log) inherited
Definition at line 229 of file Kernel.cpp.
References pdal::Kernel::doExecution(), pdal::Kernel::doStartup(), pdal::Kernel::doSwitches(), setup::log, pdal::Kernel::m_log, pdal::Kernel::m_manager, pdal::Kernel::m_showHelp, pdal::Kernel::outputHelp(), pdal::Utils::printError(), and pdal::PipelineManager::setLog().
Referenced by App::execute().
virtual void pdal::Kernel::validateSwitches (ProgramArgs & args) virtual inherited
Reimplemented in pdal::TIndexKernel, pdal::InfoKernel, pdal::PipelineKernel, pdal::MergeKernel, and pdal::SplitKernel.
Definition at line 95 of file Kernel.hpp.
Referenced by pdal::Kernel::innerRun().
Member Data Documentation
std::string pdal::Kernel::m_driverOverride protected inherited
Definition at line 105 of file Kernel.hpp.
Referenced by pdal::Kernel::addBasicSwitches(), pdal::MergeKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::DiffKernel::execute(), pdal::DeltaKernel::loadSet(), pdal::InfoKernel::makePipeline(), and pdal::TIndexKernel::mergeFile().
std::string pdal::TranslateKernel::m_filterJSON private
Definition at line 73 of file TranslateKernel.hpp.
Referenced by addSwitches(), execute(), and makeJSONPipeline().
StringList pdal::TranslateKernel::m_filterType private
Definition at line 71 of file TranslateKernel.hpp.
Referenced by addSwitches(), execute(), and makeArgPipeline().
std::string pdal::TranslateKernel::m_inputFile private
Definition at line 67 of file TranslateKernel.hpp.
Referenced by addSwitches(), makeArgPipeline(), and makeJSONPipeline().
LogPtr pdal::Kernel::m_log protected inherited
Definition at line 103 of file Kernel.hpp.
Referenced by pdal::TIndexKernel::createFeature(), pdal::TIndexKernel::createFile(), pdal::TIndexKernel::createLayer(), pdal::InfoKernel::dumpPoints(), execute(), and pdal::Kernel::run().
PipelineManager pdal::Kernel::m_manager protected inherited
Definition at line 104 of file Kernel.hpp.
Referenced by pdal::Kernel::doSwitches(), pdal::InfoKernel::dump(), pdal::SmoothKernel::execute(), pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), execute(), pdal::TIndexKernel::getFileInfo(), makeArgPipeline(), pdal::Kernel::makeFilter(), makeJSONPipeline(), pdal::InfoKernel::makePipeline(), pdal::Kernel::makeReader(), pdal::Kernel::makeWriter(), pdal::InfoKernel::run(), pdal::Kernel::run(), and pdal::InfoKernel::setup().
std::string pdal::TranslateKernel::m_metadataFile private
Definition at line 74 of file TranslateKernel.hpp.
Referenced by addSwitches(), and execute().
std::string pdal::TranslateKernel::m_outputFile private
Definition at line 68 of file TranslateKernel.hpp.
Referenced by addSwitches(), makeArgPipeline(), and makeJSONPipeline().
std::string pdal::TranslateKernel::m_pipelineOutputFile private
Definition at line 69 of file TranslateKernel.hpp.
Referenced by addSwitches(), and execute().
std::string pdal::TranslateKernel::m_readerType private
Definition at line 70 of file TranslateKernel.hpp.
Referenced by addSwitches(), makeArgPipeline(), and makeJSONPipeline().
std::string pdal::TranslateKernel::m_writerType private
Definition at line 72 of file TranslateKernel.hpp.
Referenced by addSwitches(), makeArgPipeline(), and makeJSONPipeline().
The documentation for this class was generated from the following files:
pdal/kernels/TranslateKernel.hpp
pdal/kernels/TranslateKernel.cpp