PDAL: pdal::OStream Class Reference
pdal::OStream Class Reference
#include <OStream.hpp>
Public Member Functions
PDAL_DLL OStream ()
PDAL_DLL OStream (const std::string &filename)
PDAL_DLL OStream (std::ostream *stream)
PDAL_DLL ~OStream ()
PDAL_DLL int open (const std::string &filename)
PDAL_DLL void close ()
PDAL_DLL bool isOpen () const
PDAL_DLL void flush ()
PDAL_DLL operator bool ()
PDAL_DLL void seek (std::streampos pos)
PDAL_DLL void put (const std::string &s)
PDAL_DLL void put (const std::string &s, size_t len)
PDAL_DLL void put (const char *c, size_t len)
PDAL_DLL void put (const unsigned char *c, size_t len)
PDAL_DLL std::streampos position () const
PDAL_DLL void pushStream (std::ostream *strm)
PDAL_DLL std::ostream * popStream ()
Protected Attributes
std::ostream * m_stream
std::ostream * m_fstream
Private Member Functions
OStream (const OStream &)
Private Attributes
std::stack< std::ostream * > m_streams
Detailed Description
Definition at line 49 of file OStream.hpp.
Constructor & Destructor Documentation
PDAL_DLL pdal::OStream::OStream ()
Definition at line 52 of file OStream.hpp.
PDAL_DLL pdal::OStream::OStream (const std::string & filename)
Definition at line 54 of file OStream.hpp.
References open().
PDAL_DLL pdal::OStream::OStream (std::ostream * stream)
Definition at line 57 of file OStream.hpp.
PDAL_DLL pdal::OStream::~OStream ()
Definition at line 59 of file OStream.hpp.
References m_fstream.
pdal::OStream::OStream (const OStream &) private
Member Function Documentation
PDAL_DLL void pdal::OStream::close ()
Definition at line 70 of file OStream.hpp.
References flush(), m_fstream, and m_stream.
Referenced by pdal::BpfWriter::doneFile().
PDAL_DLL void pdal::OStream::flush ()
Definition at line 79 of file OStream.hpp.
References m_stream.
Referenced by close().
PDAL_DLL bool pdal::OStream::isOpen () const
Definition at line 77 of file OStream.hpp.
References m_stream.
PDAL_DLL int pdal::OStream::open (const std::string & filename)
Definition at line 62 of file OStream.hpp.
References m_fstream, and m_stream.
Referenced by OStream(), and pdal::BpfWriter::readyFile().
PDAL_DLL pdal::OStream::operator bool ()
Definition at line 81 of file OStream.hpp.
PDAL_DLL std::ostream* pdal::OStream::popStream ()
Definition at line 104 of file OStream.hpp.
References m_stream, and m_streams.
PDAL_DLL std::streampos pdal::OStream::position () const
Definition at line 97 of file OStream.hpp.
References m_stream.
Referenced by pdal::BpfWriter::readyFile().
PDAL_DLL void pdal::OStream::pushStream (std::ostream * strm)
Definition at line 99 of file OStream.hpp.
References m_stream, and m_streams.
PDAL_DLL void pdal::OStream::put (const std::string & s)
Definition at line 85 of file OStream.hpp.
Referenced by pdal::operator<<(), pdal::LasHeader::put(), pdal::BpfWriter::readyFile(), pdal::BpfDimension::write(), pdal::BpfHeader::write(), and pdal::BpfUlemFile::write().
PDAL_DLL void pdal::OStream::put (const std::string & s, size_t len)
Definition at line 87 of file OStream.hpp.
References m_stream.
PDAL_DLL void pdal::OStream::put (const char * c, size_t len)
Definition at line 93 of file OStream.hpp.
References m_stream.
PDAL_DLL void pdal::OStream::put (const unsigned char * c, size_t len)
Definition at line 95 of file OStream.hpp.
References m_stream.
PDAL_DLL void pdal::OStream::seek (std::streampos pos)
Definition at line 83 of file OStream.hpp.
References m_stream.
Referenced by pdal::BpfWriter::doneFile(), and pdal::LasWriter::finishOutput().
Member Data Documentation
std::ostream* pdal::OStream::m_fstream protected
Definition at line 117 of file OStream.hpp.
Referenced by close(), open(), and ~OStream().
std::ostream* pdal::OStream::m_stream protected
Definition at line 116 of file OStream.hpp.
Referenced by close(), flush(), isOpen(), pdal::OStreamMarker::mark(), open(), pdal::OLeStream::operator<<(), pdal::OBeStream::operator<<(), pdal::OStreamMarker::OStreamMarker(), popStream(), position(), pushStream(), put(), pdal::OStreamMarker::rewind(), and seek().
std::stack<std::ostream *> pdal::OStream::m_streams private
Definition at line 120 of file OStream.hpp.
Referenced by popStream(), and pushStream().
The documentation for this class was generated from the following file:
pdal/pdal/util/OStream.hpp