PDAL: pdal::KD2Index Class Reference
pdal::KD2Index Class Reference
#include <KDIndex.hpp>
Public Member Functions
KD2Index (const PointView &buf)
PointId neighbor (double x, double y)
PointId neighbor (PointId idx)
PointId neighbor (PointRef &point)
std::vector< PointId > neighbors (double x, double y, point_count_t k)
std::vector< PointId > neighbors (PointId idx, point_count_t k)
std::vector< PointId > neighbors (PointRef &point, point_count_t k)
void knnSearch (double x, double y, point_count_t k, std::vector< PointId > *indices, std::vector< double > *sqr_dists)
void knnSearch (PointId idx, point_count_t k, std::vector< PointId > *indices, std::vector< double > *sqr_dists)
std::vector< PointId > radius (double const &x, double const &y, double const &r) const
std::vector< PointId > radius (PointId idx, double const &r) const
std::vector< PointId > radius (PointRef &point, double const &r) const
std::size_t kdtree_get_point_count () const
double kdtree_get_pt (const PointId idx, int dim) const
double kdtree_distance (const double *p1, const PointId p2_idx, size_t) const
bool kdtree_get_bbox (BBOX &bb) const
void build ()
Protected Types
typedef nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, KDIndex, double >, KDIndex,-1, std::size_t > my_kd_tree_t
Protected Attributes
const PointView & m_buf
std::unique_ptr< my_kd_tree_t > m_index
Detailed Description
Definition at line 92 of file KDIndex.hpp.
Member Typedef Documentation
typedef nanoflann::KDTreeSingleIndexAdaptor<nanoflann::L2_Simple_Adaptor< double, KDIndex, double>, KDIndex, -1, std::size_t> pdal::KDIndex< DIM >::my_kd_tree_t protected inherited
Definition at line 83 of file KDIndex.hpp.
Constructor & Destructor Documentation
pdal::KD2Index::KD2Index (const PointView & buf)
Definition at line 95 of file KDIndex.hpp.
References pdal::PointView::hasDim(), X, and Y.
Member Function Documentation
void pdal::KDIndex< DIM >::build () inherited
Definition at line 73 of file KDIndex.hpp.
double pdal::KDIndex< DIM >::kdtree_distance (const double * p1, const PointId p2_idx, size_t) const inherited
bool pdal::KDIndex< DIM >::kdtree_get_bbox (BBOX & bb) const inherited
std::size_t pdal::KDIndex< DIM >::kdtree_get_point_count () const inherited
Definition at line 66 of file KDIndex.hpp.
double pdal::KDIndex< DIM >::kdtree_get_pt (const PointId idx, int dim) const inherited
void pdal::KD2Index::knnSearch (double x, double y, point_count_t k, std::vector< PointId > * indices, std::vector< double > * sqr_dists)
Definition at line 153 of file KDIndex.hpp.
Referenced by pdal::SMRFilter::knnfill(), and pdal::PMFFilter::processGround().
void pdal::KD2Index::knnSearch (PointId idx, point_count_t k, std::vector< PointId > * indices, std::vector< double > * sqr_dists)
Definition at line 167 of file KDIndex.hpp.
References X, and Y.
PointId pdal::KD2Index::neighbor (double x, double y)
Definition at line 103 of file KDIndex.hpp.
Referenced by TEST().
PointId pdal::KD2Index::neighbor (PointId idx)
Definition at line 109 of file KDIndex.hpp.
PointId pdal::KD2Index::neighbor (PointRef & point)
Definition at line 115 of file KDIndex.hpp.
std::vector<PointId> pdal::KD2Index::neighbors (double x, double y, point_count_t k)
Definition at line 121 of file KDIndex.hpp.
Referenced by pdal::InfoKernel::dumpQuery(), pdal::HAGFilter::filter(), and TEST().
std::vector<PointId> pdal::KD2Index::neighbors (PointId idx, point_count_t k)
Definition at line 137 of file KDIndex.hpp.
References X, and Y.
std::vector<PointId> pdal::KD2Index::neighbors (PointRef & point, point_count_t k)
Definition at line 145 of file KDIndex.hpp.
References pdal::PointRef::getFieldAs(), X, and Y.
std::vector<PointId> pdal::KD2Index::radius (double const & x, double const & y, double const & r) const
Definition at line 176 of file KDIndex.hpp.
Referenced by pdal::eigen::createMaxMatrix2(), and TEST().
std::vector<PointId> pdal::KD2Index::radius (PointId idx, double const & r) const
Definition at line 198 of file KDIndex.hpp.
References anonymous_namespace{GreyhoundReaderTest.cpp}::radius, X, and Y.
std::vector<PointId> pdal::KD2Index::radius (PointRef & point, double const & r) const
Definition at line 206 of file KDIndex.hpp.
References pdal::PointRef::getFieldAs(), anonymous_namespace{GreyhoundReaderTest.cpp}::radius, X, and Y.
Member Data Documentation
const PointView& pdal::KDIndex< DIM >::m_buf protected inherited
Definition at line 80 of file KDIndex.hpp.
std::unique_ptr<my_kd_tree_t> pdal::KDIndex< DIM >::m_index protected inherited
Definition at line 85 of file KDIndex.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/KDIndex.hpp