PDAL: libpdalpython::Pipeline Class Reference
libpdalpython::Pipeline Class Reference
#include <PyPipeline.hpp>
Public Member Functions
Pipeline (std::string const &xml)
~Pipeline ()
int64_t execute ()
bool validate ()
std::string getPipeline () const
std::string getMetadata () const
std::string getSchema () const
std::string getLog () const
std::vector< PArray > getArrays () const
void setLogLevel (int level)
int getLogLevel () const
Private Attributes
pdal::PipelineExecutor m_executor
Detailed Description
Definition at line 68 of file PyPipeline.hpp.
Constructor & Destructor Documentation
libpdalpython::Pipeline::Pipeline (std::string const & xml)
Definition at line 44 of file PyPipeline.cpp.
libpdalpython::Pipeline::~Pipeline ()
Definition at line 57 of file PyPipeline.cpp.
Member Function Documentation
int64_t libpdalpython::Pipeline::execute ()
Definition at line 71 of file PyPipeline.cpp.
References pdal::PipelineExecutor::execute(), and m_executor.
std::vector< PArray > libpdalpython::Pipeline::getArrays () const
Definition at line 83 of file PyPipeline.cpp.
References pdal::PipelineExecutor::executed(), pdal::PipelineExecutor::getManagerConst(), m_executor, pdal::python::Array::update(), and pdal::PipelineManager::views().
std::string libpdalpython::Pipeline::getLog () const
Definition at line 87 of file PyPipeline.hpp.
References setup::level, and pdal::pclsupport::setLogLevel().
int libpdalpython::Pipeline::getLogLevel () const
Definition at line 66 of file PyPipeline.cpp.
References pdal::PipelineExecutor::getLogLevel(), and m_executor.
std::string libpdalpython::Pipeline::getMetadata () const
Definition at line 79 of file PyPipeline.hpp.
std::string libpdalpython::Pipeline::getPipeline () const
Definition at line 75 of file PyPipeline.hpp.
std::string libpdalpython::Pipeline::getSchema () const
Definition at line 83 of file PyPipeline.hpp.
void libpdalpython::Pipeline::setLogLevel (int level)
Definition at line 61 of file PyPipeline.cpp.
References m_executor, and pdal::PipelineExecutor::setLogLevel().
bool libpdalpython::Pipeline::validate ()
Definition at line 78 of file PyPipeline.cpp.
References m_executor, and pdal::PipelineExecutor::validate().
Member Data Documentation
pdal::PipelineExecutor libpdalpython::Pipeline::m_executor private
Definition at line 99 of file PyPipeline.hpp.
Referenced by execute(), getArrays(), getLogLevel(), setLogLevel(), and validate().
The documentation for this class was generated from the following files:
pdal/python/pdal/PyPipeline.hpp
pdal/python/pdal/PyPipeline.cpp