PDAL: pdal::geos::ErrorHandler Class Reference
pdal::geos::ErrorHandler Class Reference
#include <GEOSUtils.hpp>
Public Member Functions
~ErrorHandler ()
void set (LogPtr log, bool doDebug)
void setLog (LogPtr log)
void setDebug (bool debug)
GEOSContextHandle_t ctx () const
Static Public Member Functions
static ErrorHandler & get ()
Private Member Functions
ErrorHandler ()
void handle (const char *msg, bool notice)
Static Private Member Functions
static void vaErrorCb (const char *msg,...)
static void vaNoticeCb (const char *msg,...)
Private Attributes
GEOSContextHandle_t m_ctx
bool m_debug
LogPtr m_log
Static Private Attributes
static std::unique_ptr< ErrorHandler > m_instance
Detailed Description
Definition at line 49 of file GEOSUtils.hpp.
Constructor & Destructor Documentation
pdal::geos::ErrorHandler::~ErrorHandler ()
Definition at line 114 of file GEOSUtils.cpp.
References m_ctx.
pdal::geos::ErrorHandler::ErrorHandler () private
Definition at line 87 of file GEOSUtils.cpp.
References handle(), m_ctx, vaErrorCb(), and vaNoticeCb().
Member Function Documentation
GEOSContextHandle_t pdal::geos::ErrorHandler::ctx () const
Get the GEOS context handle.
Returns
The GEOS context handle.
Definition at line 159 of file GEOSUtils.cpp.
References m_ctx.
Referenced by pdal::Polygon::area(), pdal::Geometry::bounds(), pdal::Polygon::contains(), pdal::Polygon::covers(), pdal::Polygon::crosses(), pdal::Geometry::equals(), pdal::Geometry::Geometry(), pdal::Polygon::initializeFromBounds(), pdal::geos::GeometryDeleter::operator()(), pdal::Polygon::operator=(), pdal::Geometry::operator=(), pdal::Polygon::overlaps(), pdal::Polygon::Polygon(), pdal::Geometry::prepare(), pdal::Polygon::simplify(), pdal::Polygon::touches(), pdal::filter::Point::update(), pdal::Geometry::update(), pdal::Geometry::valid(), pdal::Geometry::validReason(), pdal::Polygon::within(), pdal::Geometry::wkt(), and pdal::Geometry::~Geometry().
ErrorHandler & pdal::geos::ErrorHandler::get () static
Get the singleton error handler.
Returns
Reference to the error handler.
Definition at line 57 of file GEOSUtils.cpp.
References m_instance.
Referenced by vaErrorCb(), and vaNoticeCb().
void pdal::geos::ErrorHandler::handle (const char * msg, bool notice) private
Definition at line 143 of file GEOSUtils.cpp.
References pdal::Debug, m_debug, and m_log.
Referenced by ErrorHandler(), vaErrorCb(), and vaNoticeCb().
void pdal::geos::ErrorHandler::set (LogPtr log, bool doDebug)
Set the log and debug state of the error handler. This is a convenience and is equivalent to calling setLog() and setDebug().
Parameters
log Log to write to.
doDebug Debug state of the error handler.
Definition at line 124 of file GEOSUtils.cpp.
References setDebug(), and setLog().
void pdal::geos::ErrorHandler::setDebug (bool debug)
Set the debug state of the error handler. If the error handler is set to debug, output is logged instead of causing an exception.
Parameters
debug The debug state of the error handler.
Definition at line 131 of file GEOSUtils.cpp.
References m_debug.
Referenced by set().
void pdal::geos::ErrorHandler::setLog (LogPtr log)
Set the log to which error/debug messages should be written.
Parameters
log Log to write to.
Definition at line 137 of file GEOSUtils.cpp.
References setup::log, and m_log.
Referenced by set().
void pdal::geos::ErrorHandler::vaErrorCb (const char * msg, ...) static private
Definition at line 65 of file GEOSUtils.cpp.
References get(), and handle().
Referenced by ErrorHandler().
void pdal::geos::ErrorHandler::vaNoticeCb (const char * msg, ...) static private
Definition at line 76 of file GEOSUtils.cpp.
References get(), and handle().
Referenced by ErrorHandler().
Member Data Documentation
GEOSContextHandle_t pdal::geos::ErrorHandler::m_ctx private
Definition at line 99 of file GEOSUtils.hpp.
Referenced by ctx(), ErrorHandler(), and ~ErrorHandler().
bool pdal::geos::ErrorHandler::m_debug private
Definition at line 100 of file GEOSUtils.hpp.
Referenced by handle(), and setDebug().
std::unique_ptr< ErrorHandler > pdal::geos::ErrorHandler::m_instance static private
Definition at line 102 of file GEOSUtils.hpp.
Referenced by get().
LogPtr pdal::geos::ErrorHandler::m_log private
Definition at line 101 of file GEOSUtils.hpp.
Referenced by handle(), and setLog().
The documentation for this class was generated from the following files:
pdal/pdal/GEOSUtils.hpp
pdal/pdal/GEOSUtils.cpp