PDAL: pdal::lasdump::Dumper Class Reference
pdal::lasdump::Dumper Class Reference
#include <Dumper.hpp>
Public Member Functions
Dumper (const std::deque< std::string > &args)
void dump ()
int error ()
Private Member Functions
int processArgs (std::deque< std::string > args)
void readPoints (ILeStream &in)
void readCompressedPoints (ILeStream &in)
void loadPoint (const laszip_point_struct *zipPoint, std::vector< char > &buf)
Private Attributes
std::string m_filename
Header m_header
Vlr m_zipVlr
int m_error
std::ofstream m_fout
std::ostream * m_out
Detailed Description
Definition at line 52 of file Dumper.hpp.
Constructor & Destructor Documentation
pdal::lasdump::Dumper::Dumper (const std::deque< std::string > & args)
Definition at line 56 of file Dumper.hpp.
References dump(), m_error, and processArgs().
Member Function Documentation
void pdal::lasdump::Dumper::dump ()
Definition at line 69 of file Dumper.cpp.
References pdal::IStream::good(), m_error, m_filename, m_header, m_out, m_zipVlr, readCompressedPoints(), readPoints(), and pdal::IStream::seek().
Referenced by Dumper(), and main().
int pdal::lasdump::Dumper::error ()
Definition at line 59 of file Dumper.hpp.
References m_error.
Referenced by main().
void pdal::lasdump::Dumper::loadPoint (const laszip_point_struct * zipPoint, std::vector< char > & buf) private
Definition at line 179 of file Dumper.cpp.
References m_header, and pdal::lasdump::Header::pointFormat().
Referenced by readCompressedPoints().
int pdal::lasdump::Dumper::processArgs (std::deque< std::string > args) private
Definition at line 243 of file Dumper.cpp.
References m_filename, m_fout, m_out, and anonymous_namespace{Dumper.cpp}::usage().
Referenced by Dumper().
void pdal::lasdump::Dumper::readCompressedPoints (ILeStream & in) private
Definition at line 159 of file Dumper.cpp.
References pdal::lasdump::cksum(), pdal::lasdump::anonymous_namespace{Dumper.cpp}::handleLaszip(), loadPoint(), m_header, m_out, pdal::lasdump::Header::pointCount(), pdal::lasdump::Header::pointLen(), and pdal::IStream::stream().
Referenced by dump().
void pdal::lasdump::Dumper::readPoints (ILeStream & in) private
Definition at line 131 of file Dumper.cpp.
References pdal::lasdump::cksum(), pdal::IStream::get(), m_header, m_out, pdal::lasdump::Header::pointCount(), and pdal::lasdump::Header::pointLen().
Referenced by dump().
Member Data Documentation
int pdal::lasdump::Dumper::m_error private
Definition at line 66 of file Dumper.hpp.
Referenced by dump(), Dumper(), and error().
std::string pdal::lasdump::Dumper::m_filename private
Definition at line 63 of file Dumper.hpp.
Referenced by dump(), and processArgs().
std::ofstream pdal::lasdump::Dumper::m_fout private
Definition at line 67 of file Dumper.hpp.
Referenced by processArgs().
Header pdal::lasdump::Dumper::m_header private
Definition at line 64 of file Dumper.hpp.
Referenced by dump(), loadPoint(), readCompressedPoints(), and readPoints().
std::ostream* pdal::lasdump::Dumper::m_out private
Definition at line 68 of file Dumper.hpp.
Referenced by dump(), processArgs(), readCompressedPoints(), and readPoints().
Vlr pdal::lasdump::Dumper::m_zipVlr private
Definition at line 65 of file Dumper.hpp.
Referenced by dump().
The documentation for this class was generated from the following files:
pdal/tools/lasdump/Dumper.hpp
pdal/tools/lasdump/Dumper.cpp