PDAL: pdal::Metadata Class Reference
pdal::Metadata Class Reference
#include <Metadata.hpp>
Public Member Functions
Metadata ()
Metadata (const std::string &name)
MetadataNode getNode () const
Static Public Member Functions
static std::string PDAL_DLL inferType (const std::string &val)
Private Attributes
MetadataNode m_root
MetadataNode m_private
std::string m_name
Friends
class BasePointTable
Detailed Description
Definition at line 667 of file Metadata.hpp.
Constructor & Destructor Documentation
pdal::Metadata::Metadata ()
Definition at line 672 of file Metadata.hpp.
pdal::Metadata::Metadata (const std::string & name)
Definition at line 675 of file Metadata.hpp.
Member Function Documentation
MetadataNode pdal::Metadata::getNode () const
Definition at line 678 of file Metadata.hpp.
References PDAL_DLL.
Referenced by pdal::SQLiteWriter::CreateCloud(), and pdal::PgWriter::SetupSchema().
std::string pdal::Metadata::inferType (const std::string & val) static
Definition at line 49 of file Metadata.cpp.
References pdal::Uuid::isNull().
Referenced by pdal::plang::addMetadata().
Friends And Related Function Documentation
friend class BasePointTable friend
Definition at line 669 of file Metadata.hpp.
Member Data Documentation
std::string pdal::Metadata::m_name private
Definition at line 685 of file Metadata.hpp.
MetadataNode pdal::Metadata::m_private private
Definition at line 684 of file Metadata.hpp.
MetadataNode pdal::Metadata::m_root private
Definition at line 683 of file Metadata.hpp.
The documentation for this class was generated from the following files:
pdal/pdal/Metadata.hpp
pdal/pdal/Metadata.cpp