PDAL: pdal::Kernel Class Reference
pdal::Kernel Class Reference abstract
#include <Kernel.hpp>
Public Member Functions
virtual ~Kernel ()
int run (const StringList &cmdArgs, LogPtr &log)
virtual std::string getName () const =0
std::string getShortName () const
virtual void addSwitches (ProgramArgs &args)
virtual void validateSwitches (ProgramArgs &args)
virtual int execute ()=0
Protected Member Functions
Kernel ()
Stage & makeReader (const std::string &inputFile, std::string driver)
Stage & makeReader (const std::string &inputFile, std::string driver, Options options)
Stage & makeFilter (const std::string &driver, Stage &parent)
Stage & makeFilter (const std::string &driver, Stage &parent, Options options)
Stage & makeFilter (const std::string &driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver, Options options)
virtual bool isStagePrefix (const std::string &stageType)
Protected Attributes
LogPtr m_log
PipelineManager m_manager
std::string m_driverOverride
Private Member Functions
FRIEND_TEST (KernelTest, parseOption)
int innerRun (ProgramArgs &args)
void outputHelp (ProgramArgs &args)
void outputVersion ()
void addBasicSwitches (ProgramArgs &args)
void doSwitches (const StringList &cmdArgs, ProgramArgs &args)
int doStartup ()
int doExecution (ProgramArgs &args)
bool parseStageOption (std::string o, std::string &stage, std::string &option, std::string &value)
Kernel & operator= (const Kernel &)
Kernel (const Kernel &)
Static Private Member Functions
static bool test_parseStageOption (std::string o, std::string &stage, std::string &option, std::string &value)
Private Attributes
bool m_showHelp
bool m_showOptions
bool m_showTime
bool m_hardCoreDebug
std::string m_label
Detailed Description
Definition at line 55 of file Kernel.hpp.
Constructor & Destructor Documentation
virtual pdal::Kernel::~Kernel () virtual
Definition at line 60 of file Kernel.hpp.
References setup::log.
pdal::Kernel::Kernel () protected
Definition at line 53 of file Kernel.cpp.
pdal::Kernel::Kernel (const Kernel &) private
Member Function Documentation
void pdal::Kernel::addBasicSwitches (ProgramArgs & args) private
Definition at line 293 of file Kernel.cpp.
References pdal::ProgramArgs::add(), m_driverOverride, m_hardCoreDebug, and m_label.
Referenced by doSwitches().
virtual void pdal::Kernel::addSwitches (ProgramArgs & args) virtual
Reimplemented in pdal::DeltaKernel, pdal::TIndexKernel, pdal::InfoKernel, pdal::DensityKernel, pdal::GroundKernel, pdal::TranslateKernel, pdal::DiffKernel, pdal::HausdorffKernel, pdal::PipelineKernel, pdal::RandomKernel, pdal::SortKernel, pdal::MergeKernel, pdal::SplitKernel, pdal::SmoothKernel, pdal::PCLKernel, and pdal::MyKernel.
Definition at line 90 of file Kernel.hpp.
Referenced by doSwitches().
int pdal::Kernel::doExecution (ProgramArgs & args) private
Definition at line 194 of file Kernel.cpp.
References innerRun(), m_hardCoreDebug, and pdal::Utils::printError().
Referenced by run().
int pdal::Kernel::doStartup () private
Definition at line 188 of file Kernel.cpp.
Referenced by run().
void pdal::Kernel::doSwitches (const StringList & cmdArgs, ProgramArgs & args) private
Definition at line 135 of file Kernel.cpp.
References pdal::ProgramArgs::add(), addBasicSwitches(), addSwitches(), getName(), pdal::arg_error::m_error, m_manager, m_showHelp, pdal::ProgramArgs::parse(), pdal::ProgramArgs::parseSimple(), parseStageOption(), and pdal::PipelineManager::stageOptions().
Referenced by run().
virtual int pdal::Kernel::execute () pure virtual
Implemented in pdal::DeltaKernel, pdal::TIndexKernel, pdal::GroundKernel, pdal::InfoKernel, pdal::TranslateKernel, pdal::DiffKernel, pdal::HausdorffKernel, pdal::PipelineKernel, pdal::RandomKernel, pdal::MergeKernel, pdal::SortKernel, pdal::SplitKernel, pdal::DensityKernel, pdal::SmoothKernel, pdal::PCLKernel, and pdal::MyKernel.
Referenced by innerRun(), and test_parseStageOption().
pdal::Kernel::FRIEND_TEST (KernelTest , parseOption) private
virtual std::string pdal::Kernel::getName () const pure virtual
Implemented in pdal::DeltaKernel, pdal::TIndexKernel, pdal::GroundKernel, pdal::InfoKernel, pdal::TranslateKernel, pdal::DiffKernel, pdal::HausdorffKernel, pdal::PipelineKernel, pdal::RandomKernel, pdal::MergeKernel, pdal::SortKernel, pdal::SplitKernel, pdal::DensityKernel, pdal::SmoothKernel, pdal::PCLKernel, and pdal::MyKernel.
Referenced by doSwitches(), pdal::operator<<(), and test_parseStageOption().
std::string pdal::Kernel::getShortName () const
Definition at line 67 of file Kernel.hpp.
References pdal::Utils::split2().
Referenced by outputHelp().
int pdal::Kernel::innerRun (ProgramArgs & args) private
Definition at line 260 of file Kernel.cpp.
References execute(), outputHelp(), pdal::Utils::printError(), and validateSwitches().
Referenced by doExecution().
bool pdal::Kernel::isStagePrefix (const std::string & stageType) protected virtual
Reimplemented in pdal::PipelineKernel.
Definition at line 58 of file Kernel.cpp.
Referenced by pdal::PipelineKernel::isStagePrefix(), and parseStageOption().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent) protected
Definition at line 320 of file Kernel.cpp.
References m_manager, and pdal::PipelineManager::makeFilter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent, Options options) protected
Definition at line 326 of file Kernel.cpp.
References m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeFilter (const std::string & driver) protected
Definition at line 314 of file Kernel.cpp.
References m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver) protected
Definition at line 301 of file Kernel.cpp.
References m_manager, and pdal::PipelineManager::makeReader().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver, Options options) protected
Definition at line 307 of file Kernel.cpp.
References m_manager, and pdal::PipelineManager::makeReader().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver) protected
Definition at line 333 of file Kernel.cpp.
References m_manager, and pdal::PipelineManager::makeWriter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver, Options options) protected
Definition at line 340 of file Kernel.cpp.
References m_manager, and pdal::PipelineManager::makeWriter().
Kernel& pdal::Kernel::operator= (const Kernel &) private
void pdal::Kernel::outputHelp (ProgramArgs & args) private
Definition at line 278 of file Kernel.cpp.
References pdal::ProgramArgs::commandLine(), pdal::ProgramArgs::dump(), getShortName(), and pdal::Utils::screenWidth().
Referenced by innerRun(), and run().
void pdal::Kernel::outputVersion () private
bool pdal::Kernel::parseStageOption (std::string o, std::string & stage, std::string & option, std::string & value) private
Definition at line 65 of file Kernel.cpp.
References c, pdal::Utils::extract(), isStagePrefix(), pdal::Option::parse(), pdal::Stage::parseName(), and pdal::Stage::parseTagName().
Referenced by doSwitches().
int pdal::Kernel::run (const StringList & cmdArgs, LogPtr & log)
Definition at line 229 of file Kernel.cpp.
References doExecution(), doStartup(), doSwitches(), setup::log, m_log, m_manager, m_showHelp, outputHelp(), pdal::Utils::printError(), and pdal::PipelineManager::setLog().
Referenced by App::execute().
bool pdal::Kernel::test_parseStageOption (std::string o, std::string & stage, std::string & option, std::string & value) static private
Definition at line 347 of file Kernel.cpp.
References execute(), and getName().
Referenced by pdal::TEST().
virtual void pdal::Kernel::validateSwitches (ProgramArgs & args) virtual
Reimplemented in pdal::TIndexKernel, pdal::InfoKernel, pdal::PipelineKernel, pdal::MergeKernel, and pdal::SplitKernel.
Definition at line 95 of file Kernel.hpp.
Referenced by innerRun().
Member Data Documentation
std::string pdal::Kernel::m_driverOverride protected
Definition at line 105 of file Kernel.hpp.
Referenced by addBasicSwitches(), pdal::MergeKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::DiffKernel::execute(), pdal::DeltaKernel::loadSet(), pdal::InfoKernel::makePipeline(), and pdal::TIndexKernel::mergeFile().
bool pdal::Kernel::m_hardCoreDebug private
Definition at line 125 of file Kernel.hpp.
Referenced by addBasicSwitches(), and doExecution().
std::string pdal::Kernel::m_label private
Definition at line 126 of file Kernel.hpp.
Referenced by addBasicSwitches().
LogPtr pdal::Kernel::m_log protected
Definition at line 103 of file Kernel.hpp.
Referenced by pdal::TIndexKernel::createFeature(), pdal::TIndexKernel::createFile(), pdal::TIndexKernel::createLayer(), pdal::InfoKernel::dumpPoints(), pdal::TranslateKernel::execute(), and run().
PipelineManager pdal::Kernel::m_manager protected
Definition at line 104 of file Kernel.hpp.
Referenced by doSwitches(), pdal::InfoKernel::dump(), pdal::SmoothKernel::execute(), pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), pdal::TranslateKernel::execute(), pdal::TIndexKernel::getFileInfo(), pdal::TranslateKernel::makeArgPipeline(), makeFilter(), pdal::TranslateKernel::makeJSONPipeline(), pdal::InfoKernel::makePipeline(), makeReader(), makeWriter(), pdal::InfoKernel::run(), run(), and pdal::InfoKernel::setup().
bool pdal::Kernel::m_showHelp private
Definition at line 122 of file Kernel.hpp.
Referenced by doSwitches(), and run().
bool pdal::Kernel::m_showOptions private
Definition at line 123 of file Kernel.hpp.
bool pdal::Kernel::m_showTime private
Definition at line 124 of file Kernel.hpp.
The documentation for this class was generated from the following files:
pdal/pdal/Kernel.hpp
pdal/pdal/Kernel.cpp