PDAL: pdal::MetadataReader Class Reference
pdal::MetadataReader Class Reference
#include <MetadataReader.hpp>
Classes
struct error
Public Member Functions
MetadataReader (::nitf::Record &, MetadataNode &, bool showEmptyFields=true)
void read ()
Private Member Functions
void writeField (const std::string &parentkey, const std::string &key,::nitf::Field field)
void writeInt (const std::string &parentkey, const std::string &key, int thevalue)
void writeString (const std::string &parentkey, const std::string &key, const std::string &thevalue)
void doFileHeader (const std::string &parentkey,::nitf::FileHeader &)
void doSecurity (const std::string &parentkey, const std::string &prefix,::nitf::FileSecurity &)
void doBands (const std::string &key,::nitf::ImageSubheader &)
void doBand (const std::string &key,::nitf::BandInfo &)
void doImageSubheader (const std::string &key,::nitf::ImageSubheader &)
void doDESubheader (const std::string &key,::nitf::DESubheader &)
void doExtensions (const std::string &key,::nitf::Extensions &)
void doComments (const std::string &key,::nitf::List &)
void doTRE (const std::string &key,::nitf::TRE &)
MetadataReader (const MetadataReader &)
MetadataReader & operator= (const MetadataReader &)
Private Attributes
::nitf::Record m_record
MetadataNode & m_node
const bool m_showEmptyFields
Detailed Description
Definition at line 76 of file MetadataReader.hpp.
Constructor & Destructor Documentation
pdal::MetadataReader::MetadataReader (::nitf::Record & record, MetadataNode & node, bool showEmptyFields = true)
Definition at line 49 of file MetadataReader.cpp.
pdal::MetadataReader::MetadataReader (const MetadataReader &) private
Member Function Documentation
void pdal::MetadataReader::doBand (const std::string & key, ::nitf::BandInfo & band) private
Definition at line 243 of file MetadataReader.cpp.
References writeField(), and writeInt().
Referenced by doBands().
void pdal::MetadataReader::doBands (const std::string & key, ::nitf::ImageSubheader & header) private
Definition at line 230 of file MetadataReader.cpp.
References doBand().
Referenced by doImageSubheader().
void pdal::MetadataReader::doComments (const std::string & key, ::nitf::List & list) private
Definition at line 382 of file MetadataReader.cpp.
References writeField().
Referenced by doImageSubheader().
void pdal::MetadataReader::doDESubheader (const std::string & key, ::nitf::DESubheader & subheader) private
Definition at line 308 of file MetadataReader.cpp.
References doSecurity(), and writeField().
Referenced by read().
void pdal::MetadataReader::doExtensions (const std::string & key, ::nitf::Extensions & ext) private
Definition at line 367 of file MetadataReader.cpp.
References doTRE().
Referenced by read().
void pdal::MetadataReader::doFileHeader (const std::string & parentkey, ::nitf::FileHeader & header) private
Definition at line 180 of file MetadataReader.cpp.
References writeField().
Referenced by read().
void pdal::MetadataReader::doImageSubheader (const std::string & key, ::nitf::ImageSubheader & subheader) private
Definition at line 259 of file MetadataReader.cpp.
References doBands(), doComments(), doSecurity(), and writeField().
Referenced by read().
void pdal::MetadataReader::doSecurity (const std::string & parentkey, const std::string & prefix, ::nitf::FileSecurity & security) private
Definition at line 208 of file MetadataReader.cpp.
References writeField().
Referenced by doDESubheader(), doImageSubheader(), and read().
void pdal::MetadataReader::doTRE (const std::string & key, ::nitf::TRE & tre) private
Definition at line 323 of file MetadataReader.cpp.
References writeField().
Referenced by doExtensions().
MetadataReader& pdal::MetadataReader::operator= (const MetadataReader &) private
void pdal::MetadataReader::read ()
Definition at line 59 of file MetadataReader.cpp.
References doDESubheader(), doExtensions(), doFileHeader(), doImageSubheader(), doSecurity(), setup::ext, and m_record.
Referenced by pdal::NitfFileReader::extractMetadata().
void pdal::MetadataReader::writeField (const std::string & parentkey, const std::string & key, ::nitf::Field field) private
Definition at line 119 of file MetadataReader.cpp.
References pdal::MetadataNode::add(), m_node, m_showEmptyFields, and pdal::Utils::trim().
Referenced by doBand(), doComments(), doDESubheader(), doFileHeader(), doImageSubheader(), doSecurity(), and doTRE().
void pdal::MetadataReader::writeInt (const std::string & parentkey, const std::string & key, int thevalue) private
Definition at line 164 of file MetadataReader.cpp.
References pdal::MetadataNode::add(), and m_node.
Referenced by doBand().
void pdal::MetadataReader::writeString (const std::string & parentkey, const std::string & key, const std::string & thevalue) private
Definition at line 172 of file MetadataReader.cpp.
References pdal::MetadataNode::add(), and m_node.
Member Data Documentation
MetadataNode& pdal::MetadataReader::m_node private
Definition at line 91 of file MetadataReader.hpp.
Referenced by writeField(), writeInt(), and writeString().
::nitf::Record pdal::MetadataReader::m_record private
Definition at line 90 of file MetadataReader.hpp.
Referenced by read().
const bool pdal::MetadataReader::m_showEmptyFields private
Definition at line 92 of file MetadataReader.hpp.
Referenced by writeField().
The documentation for this class was generated from the following files:
pdal/plugins/nitf/io/MetadataReader.hpp
pdal/plugins/nitf/io/MetadataReader.cpp