PDAL: pdal::NitfFileWriter Class Reference
pdal::NitfFileWriter Class Reference
#include <NitfFileWriter.hpp>
Classes
struct error
Public Member Functions
NitfFileWriter ()
NitfFileWriter (const NitfFileWriter &)=delete
NitfFileWriter & operator= (const NitfFileWriter &)=delete
void initialize ()
void setFilename (const std::string &filename)
void wrapData (const char *buf, size_t size)
void wrapData (const std::string &filename)
void addArgs (ProgramArgs &args)
void setBounds (const BOX3D &bounds)
void write ()
Public Attributes
std::unique_ptr< nitf::DataSource > m_source
std::unique_ptr< nitf::IOHandle > m_inputHandle
std::string m_cLevel
std::string m_sType
std::string m_oStationId
std::string m_fileTitle
std::string m_fileClass
std::string m_origName
std::string m_origPhone
std::string m_securityControlAndHandling
std::string m_securityClassificationSystem
std::string m_imgSecurityClass
std::string m_imgDate
StringList m_aimidb
StringList m_acftb
std::string m_imgIdentifier2
std::string m_sic
BOX3D m_bounds
std::string m_filename
Detailed Description
Definition at line 71 of file NitfFileWriter.hpp.
Constructor & Destructor Documentation
pdal::NitfFileWriter::NitfFileWriter ()
Definition at line 80 of file NitfFileWriter.hpp.
pdal::NitfFileWriter::NitfFileWriter (const NitfFileWriter &) delete
Member Function Documentation
void pdal::NitfFileWriter::addArgs (ProgramArgs & args)
Definition at line 57 of file NitfFileWriter.cpp.
References pdal::ProgramArgs::add(), m_acftb, m_aimidb, m_cLevel, m_fileClass, m_fileTitle, m_imgDate, m_imgIdentifier2, m_imgSecurityClass, m_origName, m_origPhone, m_oStationId, m_securityClassificationSystem, m_securityControlAndHandling, m_sic, and m_sType.
Referenced by pdal::NitfWriter::addArgs(), and pdal::nitfwrap::NitfWrap::parseArgs().
void pdal::NitfFileWriter::initialize ()
Definition at line 44 of file NitfFileWriter.cpp.
References pdal::register_tre_plugins().
Referenced by pdal::nitfwrap::NitfWrap::NitfWrap(), and pdal::NitfWriter::NitfWriter().
NitfFileWriter& pdal::NitfFileWriter::operator= (const NitfFileWriter &) delete
void pdal::NitfFileWriter::setBounds (const BOX3D & bounds)
Definition at line 277 of file NitfFileWriter.cpp.
References m_bounds, pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, and pdal::BOX2D::miny.
Referenced by pdal::NitfWriter::doneFile(), and pdal::nitfwrap::NitfWrap::NitfWrap().
void pdal::NitfFileWriter::setFilename (const std::string & filename)
Definition at line 86 of file NitfFileWriter.hpp.
References pdal::Dimension::size().
Referenced by pdal::nitfwrap::NitfWrap::NitfWrap(), and pdal::NitfWriter::readyFile().
void pdal::NitfFileWriter::wrapData (const char * buf, size_t size)
Definition at line 293 of file NitfFileWriter.cpp.
References m_source.
Referenced by pdal::NitfWriter::doneFile(), and pdal::nitfwrap::NitfWrap::NitfWrap().
void pdal::NitfFileWriter::wrapData (const std::string & filename)
Definition at line 299 of file NitfFileWriter.cpp.
References m_inputHandle, and m_source.
void pdal::NitfFileWriter::write ()
< The number of rows
< The number of columns
< The number of rows/block
< The number of columns/block
< Image mode
Definition at line 81 of file NitfFileWriter.cpp.
References pdal::FileUtils::getFilename(), m_acftb, m_aimidb, m_bounds, m_cLevel, m_fileClass, m_filename, m_fileTitle, m_imgDate, m_imgIdentifier2, m_imgSecurityClass, m_origName, m_origPhone, m_oStationId, m_securityClassificationSystem, m_securityControlAndHandling, m_sic, m_source, m_sType, pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::Utils::split2(), pdal::Utils::toString(), and pdal::Utils::trim().
Referenced by pdal::NitfWriter::doneFile(), and pdal::nitfwrap::NitfWrap::NitfWrap().
Member Data Documentation
StringList pdal::NitfFileWriter::m_acftb
Definition at line 109 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
StringList pdal::NitfFileWriter::m_aimidb
Definition at line 108 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
BOX3D pdal::NitfFileWriter::m_bounds
Definition at line 112 of file NitfFileWriter.hpp.
Referenced by setBounds(), and write().
std::string pdal::NitfFileWriter::m_cLevel
Definition at line 97 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_fileClass
Definition at line 101 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_filename
Definition at line 114 of file NitfFileWriter.hpp.
Referenced by write().
std::string pdal::NitfFileWriter::m_fileTitle
Definition at line 100 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_imgDate
Definition at line 107 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_imgIdentifier2
Definition at line 110 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_imgSecurityClass
Definition at line 106 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::unique_ptr<nitf::IOHandle> pdal::NitfFileWriter::m_inputHandle
Definition at line 95 of file NitfFileWriter.hpp.
Referenced by wrapData().
std::string pdal::NitfFileWriter::m_origName
Definition at line 102 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_origPhone
Definition at line 103 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_oStationId
Definition at line 99 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_securityClassificationSystem
Definition at line 105 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_securityControlAndHandling
Definition at line 104 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::string pdal::NitfFileWriter::m_sic
Definition at line 111 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
std::unique_ptr<nitf::DataSource> pdal::NitfFileWriter::m_source
Definition at line 94 of file NitfFileWriter.hpp.
Referenced by wrapData(), and write().
std::string pdal::NitfFileWriter::m_sType
Definition at line 98 of file NitfFileWriter.hpp.
Referenced by addArgs(), and write().
The documentation for this class was generated from the following files:
pdal/plugins/nitf/io/NitfFileWriter.hpp
pdal/plugins/nitf/io/NitfFileWriter.cpp