PDAL: pdal::SwitchableExtractor Class Reference
pdal::SwitchableExtractor Class Reference
#include <Extractor.hpp>
Public Member Functions
SwitchableExtractor (const char *buf, std::size_t size)
SwitchableExtractor (const char *buf, std::size_t size, bool isLittleEndian)
bool isLittleEndian () const
void switchToLittleEndian ()
void switchToBigEndian ()
SwitchableExtractor & operator>> (uint8_t &v)
SwitchableExtractor & operator>> (int8_t &v)
SwitchableExtractor & operator>> (uint16_t &v)
SwitchableExtractor & operator>> (int16_t &v)
SwitchableExtractor & operator>> (uint32_t &v)
SwitchableExtractor & operator>> (int32_t &v)
SwitchableExtractor & operator>> (uint64_t &v)
SwitchableExtractor & operator>> (int64_t &v)
SwitchableExtractor & operator>> (float &v)
SwitchableExtractor & operator>> (double &v)
operator bool ()
void seek (std::size_t pos)
void skip (std::size_t cnt)
size_t position () const
bool good () const
void get (std::string &s, size_t size)
void get (std::vector< char > &buf)
void get (std::vector< unsigned char > &buf)
void get (char *buf, size_t size)
void get (unsigned char *buf, size_t size)
Static Public Attributes
static const bool DefaultIsLittleEndian = true
Protected Attributes
const char * m_eback
Start of the buffer (name from std::streambuf)
const char * m_egptr
End of the buffer.
const char * m_gptr
Current get position.
Private Attributes
bool m_isLittleEndian
Detailed Description
Wrapper extraction of data from a buffer to host ordering. Endianness of buffered data can be specified at run-time.
Definition at line 504 of file Extractor.hpp.
Constructor & Destructor Documentation
pdal::SwitchableExtractor::SwitchableExtractor (const char * buf, std::size_t size)
Construct extractor for a buffer.
Parameters
buf Buffer to extract from.
size Buffer size.
Definition at line 515 of file Extractor.hpp.
pdal::SwitchableExtractor::SwitchableExtractor (const char * buf, std::size_t size, bool isLittleEndian)
Construct extractor for a buffer.
Parameters
buf Buffer to extract from.
size Buffer size.
isLittleEndian true if the extractor converts from little endian byte order
Definition at line 528 of file Extractor.hpp.
Member Function Documentation
void pdal::Extractor::get (std::string & s, size_t size) inherited
Extract a string of a particular size from the buffer. Trim trailing null bytes.
Parameters
s String to extract to.
size Number of bytes to extract from buffer into string.
Definition at line 108 of file Extractor.hpp.
References pdal::Dimension::size().
Referenced by pdal::ExtraBytesIf::readFrom().
void pdal::Extractor::get (std::vector< char > & buf) inherited
Extract data to char vector. Vector must be sized to indicate number of bytes to extract.
Parameters
buf Vector to which bytes should be extracted.
Definition at line 131 of file Extractor.hpp.
void pdal::Extractor::get (std::vector< unsigned char > & buf) inherited
Extract data to unsigned char vector. Vector must be sized to indicate number of bytes to extract.
Parameters
buf Vector to which bytes should be extracted.
Definition at line 143 of file Extractor.hpp.
void pdal::Extractor::get (char * buf, size_t size) inherited
Extract data into a provided buffer.
Parameters
buf Pointer to buffer to which bytes should be extracted.
size Number of bytes to extract.
Definition at line 155 of file Extractor.hpp.
References pdal::Dimension::size().
void pdal::Extractor::get (unsigned char * buf, size_t size) inherited
Extract data into a provided unsigned buffer.
Parameters
buf Pointer to buffer to which bytes should be extracted.
size Number of bytes to extract.
Definition at line 167 of file Extractor.hpp.
References pdal::operator>>(), and pdal::Dimension::size().
bool pdal::Extractor::good () const inherited
Determine whether the extractor is good (the get pointer is in the buffer).
Returns
Whether the get pointer is valid.
Definition at line 98 of file Extractor.hpp.
Referenced by pdal::OptechReader::read().
bool pdal::SwitchableExtractor::isLittleEndian () const
Returns whether the extractor converts from little endian.
Returns
true if the extractor converts from little endian.
Definition at line 538 of file Extractor.hpp.
pdal::Extractor::operator bool () inherited
Determine if the buffer is good.
Returns
Whether the buffer is good.
Definition at line 65 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (uint8_t & v) virtual
Extract an unsigned byte from a buffer.
Parameters
v unsigned byte to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 559 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (int8_t & v) virtual
Extract a byte from a buffer.
Parameters
v byte to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 571 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (uint16_t & v) virtual
Extract an unsigned short from a buffer.
Parameters
v unsigned short to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 583 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (int16_t & v) virtual
Extract a short from a buffer.
Parameters
v short to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 597 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (uint32_t & v) virtual
Extract an unsigned int from a buffer.
Parameters
v unsigned int to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 612 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (int32_t & v) virtual
Extract an int from a buffer.
Parameters
v int to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 626 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (uint64_t & v) virtual
Extract an unsigned long from a buffer.
Parameters
v unsigned long to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 641 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (int64_t & v) virtual
Extract a long from a buffer.
Parameters
v long to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 655 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (float & v) virtual
Extract a float from a buffer.
Parameters
v float to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 670 of file Extractor.hpp.
SwitchableExtractor& pdal::SwitchableExtractor::operator>> (double & v) virtual
Extract a double from a buffer.
Parameters
v double to extract to.
Returns
This extractor.
Implements pdal::Extractor.
Definition at line 686 of file Extractor.hpp.
size_t pdal::Extractor::position () const inherited
Return the get position of buffer.
Returns
Get position.
Definition at line 89 of file Extractor.hpp.
void pdal::Extractor::seek (std::size_t pos) inherited
Seek to a position in the buffer.
Parameters
pos Position to seek in buffer.
Definition at line 73 of file Extractor.hpp.
void pdal::Extractor::skip (std::size_t cnt) inherited
Advance buffer position.
Parameters
cnt Number of bytes to skip in buffer.
Definition at line 81 of file Extractor.hpp.
Referenced by pdal::LasReader::loadExtraDims().
void pdal::SwitchableExtractor::switchToBigEndian ()
Set to convert from big endian.
Definition at line 550 of file Extractor.hpp.
void pdal::SwitchableExtractor::switchToLittleEndian ()
Set to convert from little endian.
Definition at line 544 of file Extractor.hpp.
Member Data Documentation
const bool pdal::SwitchableExtractor::DefaultIsLittleEndian = true static
Definition at line 507 of file Extractor.hpp.
const char* pdal::Extractor::m_eback protected inherited
Start of the buffer (name from std::streambuf)
Definition at line 185 of file Extractor.hpp.
const char* pdal::Extractor::m_egptr protected inherited
End of the buffer.
Definition at line 186 of file Extractor.hpp.
const char* pdal::Extractor::m_gptr protected inherited
Current get position.
Definition at line 187 of file Extractor.hpp.
bool pdal::SwitchableExtractor::m_isLittleEndian private
Definition at line 697 of file Extractor.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/util/Extractor.hpp