PDAL: pdal::SQLiteWriter Class Reference
pdal::SQLiteWriter Class Reference
#include <SQLiteWriter.hpp>
Public Member Functions
SQLiteWriter ()
std::string getName () const
void setInput (Stage &input)
void setProgressFd (int fd)
QuickInfo preview ()
void prepare (PointTableRef table)
PointViewSet execute (PointTableRef table)
void execute (StreamPointTable &table)
void setSpatialReference (SpatialReference const &srs)
const SpatialReference & getSpatialReference () const
void setOptions (Options options)
void addConditionalOptions (const Options &opts)
void addAllArgs (ProgramArgs &args)
void addOptions (const Options &opts)
void removeOptions (const Options &opts)
void setLog (LogPtr &log)
virtual LogPtr log () const
void startLogging () const
void stopLogging () const
bool isDebug () const
void setTag (const std::string &tag)
virtual std::string tag () const
std::vector< Stage * > & getInputs ()
MetadataNode getMetadata () const
void serialize (MetadataNode root, PipelineWriter::TagMap &tags) const
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
static bool parseName (std::string o, std::string::size_type &pos)
static bool parseTagName (std::string o, std::string::size_type &pos)
Protected Member Functions
virtual void setAutoXForm (const PointViewPtr view)
Make sure that computed offsets are stored in the schema.
XMLDimList dbDimTypes () const
size_t readField (const PointView &view, char *pos, Dimension::Id id, PointId idx)
size_t readPoint (const PointView &view, PointId idx, char *outbuf)
size_t packedPointSize () const
void doReady (PointTableRef table)
void doAddArgs (ProgramArgs &args)
std::string::size_type handleFilenameTemplate (const std::string &filename)
void setSpatialReference (MetadataNode &m, SpatialReference const &)
void addSpatialReferenceArg (ProgramArgs &args)
void throwError (const std::string &s) const
point_count_t pointCount () const
point_count_t faceCount () const
void throwStreamingError () const
Protected Attributes
Options m_options
Stage's options.
MetadataNode m_metadata
Stage's metadata.
int m_progressFd
Descriptor for progress info.
Private Member Functions
SQLiteWriter & operator= (const SQLiteWriter &)
SQLiteWriter (const SQLiteWriter &)
virtual void addArgs (ProgramArgs &args)
virtual void initialize ()
virtual void write (const PointViewPtr view)
virtual void done (PointTableRef table)
void writeInit ()
void writeTile (const PointViewPtr view)
void CreateBlockTable ()
void CreateCloudTable ()
bool CheckTableExists (std::string const &name)
void DeleteBlockTable ()
void DeleteCloudTable ()
void CreateIndexes (std::string const &table_name, std::string const &spatial_column_name, bool is3d)
bool IsValidGeometryWKT (std::string const &wkt) const
std::string loadGeometryWKT (std::string const &filename_or_wkt) const
void CreateCloud ()
Private Attributes
std::unique_ptr< SQLite > m_session
bool m_doCreateIndex
BOX3D m_bounds
bool m_sdo_pc_is_initialized
std::ostringstream m_block_insert_query
int32_t m_obj_id
int32_t m_block_id
uint32_t m_srid
std::string m_preSql
std::string m_postSql
std::string m_block_table
std::string m_cloud_table
std::string m_cloud_column
std::string m_connection
std::string m_modulename
std::string m_cloudBoundary
long m_pcId
bool m_is3d
bool m_doCompression
bool m_overwrite
PatchPtr m_patch
Detailed Description
Definition at line 45 of file SQLiteWriter.hpp.
Constructor & Destructor Documentation
pdal::SQLiteWriter::SQLiteWriter ()
Definition at line 64 of file SQLiteWriter.cpp.
pdal::SQLiteWriter::SQLiteWriter (const SQLiteWriter &) private
Member Function Documentation
void pdal::Stage::addAllArgs (ProgramArgs & args) inherited
Add a stage's options to a ProgramArgs set.
Parameters
args ProgramArgs to add to.
Definition at line 84 of file Stage.cpp.
References pdal::Stage::addArgs(), pdal::Stage::getName(), pdal::Stage::l_addArgs(), and pdal::arg_error::m_error.
Referenced by pdal::Stage::handleOptions(), and App::outputOptions().
void pdal::SQLiteWriter::addArgs (ProgramArgs &) private virtual
Add arguments(options) handled by this stage. Implement in subclass.
Parameters
args ProgramArgs object to which arguments should be added.
Reimplemented from pdal::DbWriter.
Definition at line 72 of file SQLiteWriter.cpp.
References pdal::ProgramArgs::add(), pdal::ProgramArgs::addSynonym(), pdal::DbWriter::doAddArgs(), m_block_table, m_cloud_column, m_cloud_table, m_cloudBoundary, m_connection, m_doCompression, m_is3d, m_modulename, m_overwrite, m_pcId, m_postSql, m_preSql, m_srid, and pdal::Arg::setPositional().
void pdal::Stage::addConditionalOptions (const Options & opts) inherited
Add options if an option with the same name doesn't already exist on the stage.
Parameters
opts Options to add.
Definition at line 57 of file Stage.cpp.
References pdal::Options::addConditional(), pdal::Options::getOptions(), and pdal::Stage::m_options.
Referenced by pdal::TEST().
void pdal::Stage::addOptions (const Options & opts) inherited
Add options to the existing option set.
Parameters
opts Options to add.
Definition at line 195 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions(), and TEST().
void pdal::Stage::addSpatialReferenceArg (ProgramArgs & args) protected inherited
Definition at line 468 of file Stage.cpp.
References pdal::ProgramArgs::add(), and pdal::Stage::m_spatialReference.
Referenced by pdal::OciReader::addArgs(), and pdal::PgReader::addArgs().
bool pdal::SQLiteWriter::CheckTableExists (std::string const & name) private
static void* pdal::SQLiteWriter::create () static
void pdal::SQLiteWriter::CreateBlockTable () private
Definition at line 210 of file SQLiteWriter.cpp.
References pdal::Debug, pdal::Stage::log(), m_block_table, m_cloud_column, m_cloud_table, m_session, m_srid, and pdal::Utils::tolower().
Referenced by writeInit().
void pdal::SQLiteWriter::CreateCloud () private
Definition at line 398 of file SQLiteWriter.cpp.
References pdal::MetadataNode::add(), pdal::DbWriter::dbDimTypes(), pdal::Debug, pdal::Metadata::getNode(), pdal::Dimension::id(), loadGeometryWKT(), pdal::Stage::log(), m_block_table, m_cloud_column, m_cloud_table, m_cloudBoundary, m_doCompression, m_obj_id, m_pcId, m_session, m_srid, pdal::Utils::tolower(), xml, and pdal::XMLSchema::xml().
Referenced by writeInit().
void pdal::SQLiteWriter::CreateCloudTable () private
Definition at line 263 of file SQLiteWriter.cpp.
References pdal::Debug, pdal::Stage::log(), m_cloud_column, m_cloud_table, m_session, m_srid, and pdal::Utils::tolower().
Referenced by writeInit().
void pdal::SQLiteWriter::CreateIndexes (std::string const & table_name, std::string const & spatial_column_name, bool is3d) private
Definition at line 318 of file SQLiteWriter.cpp.
References pdal::Debug, pdal::Stage::log(), m_session, and pdal::Utils::tolower().
Referenced by done().
XMLDimList pdal::DbWriter::dbDimTypes () const protected inherited
Definition at line 57 of file DbWriter.hpp.
Referenced by CreateCloud(), pdal::OciWriter::createPCEntry(), pdal::PgWriter::SetupSchema(), pdal::OciWriter::writeDimMajor(), pdal::OciWriter::writePointMajor(), and writeTile().
void pdal::SQLiteWriter::DeleteBlockTable () private
Definition at line 236 of file SQLiteWriter.cpp.
References pdal::Debug, pdal::Stage::log(), m_block_table, m_session, and pdal::Utils::tolower().
Referenced by writeInit().
void pdal::SQLiteWriter::DeleteCloudTable () private
Definition at line 287 of file SQLiteWriter.cpp.
References pdal::Debug, pdal::Stage::log(), m_cloud_table, m_session, and pdal::Utils::tolower().
Referenced by writeInit().
static int32_t pdal::SQLiteWriter::destroy (void *) static
void pdal::DbWriter::doAddArgs (ProgramArgs & args) protected inherited
Definition at line 68 of file DbWriter.hpp.
References pdal::DbWriter::addArgs(), and ready.
Referenced by pdal::OciWriter::addArgs(), pdal::PgWriter::addArgs(), and addArgs().
void pdal::SQLiteWriter::done (PointTableRef) private virtual
Called after all point views have been processed. Implement in subclass.
Parameters
table PointTable associated with pipeline.
Reimplemented from pdal::Stage.
Definition at line 373 of file SQLiteWriter.cpp.
References CreateIndexes(), m_block_table, m_doCreateIndex, m_is3d, m_postSql, m_session, and pdal::FileUtils::readFileIntoString().
void pdal::DbWriter::doReady (PointTableRef table) protected inherited
Definition at line 66 of file DbWriter.hpp.
References pdal::DbWriter::ready().
Referenced by pdal::OciWriter::ready().
PointViewSet pdal::Stage::execute (PointTableRef table) inherited
Execute a prepared pipeline (linked set of stages).
This performs the action associated with the stage by executing the run function of each stage in depth first order. Each stage is run to completion (all points are processed) before the next stages is run.o
Parameters
table Point table being used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 156 of file Stage.cpp.
References pdal::BasePointTable::addSpatialReference(), pdal::BasePointTable::clearSpatialReferences(), pdal::SpatialReference::empty(), pdal::Stage::execute(), pdal::BasePointTable::finalize(), pdal::Stage::getSpatialReference(), pdal::Stage::l_done(), pdal::Stage::m_faceCount, pdal::Stage::m_inputs, pdal::Stage::m_pointCount, pdal::Stage::ready(), pdal::Stage::StageRunner, pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::execute(), pdal::Stage::execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
void pdal::Stage::execute (StreamPointTable & table) inherited
Execute a prepared pipeline (linked set of stages) in streaming mode.
This performs the action associated with the stage by executing the processOne function of each stage in depth first order. Points are processed up to the capacity of the provided StreamPointTable. Not all stages support streaming mode and an exception will be thrown when attempting to execute an unsupported stage.
Streaming points can reduce memory consumption, but may limit access to algorithms that need to operate on full point sets.
Parameters
table Streming point table used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 239 of file Stage.cpp.
References pdal::Stage::done(), pdal::SpatialReference::empty(), pdal::Stage::execute(), pdal::StreamPointTable::finalize(), pdal::Stage::m_inputs, pdal::entwine::operator-(), pdal::Stage::ready(), and pdal::BasePointTable::setSpatialReference().
point_count_t pdal::Stage::faceCount () const protected inherited
Return the count of faces in all primary meshes for all point views. Only valid during execute().
Returns
Total number of faces in all point views being executed.
Definition at line 336 of file Stage.hpp.
Referenced by pdal::PlyWriter::writeHeader().
std::vector<Stage*>& pdal::Stage::getInputs () inherited
Return a list of the stage's inputs.
Returns
A vector pointers to input stages.
Definition at line 272 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTags(), pdal::PipelineManager::leaves(), pdal::PipelineManager::replace(), and TEST().
MetadataNode pdal::Stage::getMetadata () const inherited
Get the stage's metadata node.
Returns
Stage's metadata.
Definition at line 280 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{CpdFilter.cpp}::addMetadata(), pdal::CpdFilter::change(), pdal::CpdFilter::cpd_affine(), pdal::CpdFilter::cpd_rigid(), pdal::SbetWriter::done(), pdal::MatlabWriter::done(), pdal::PcdWriter::done(), pdal::PlyWriter::done(), pdal::MbReader::done(), pdal::MrsidReader::done(), pdal::MatlabReader::done(), pdal::GDALWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::LasWriter::doneFile(), pdal::InfoKernel::dump(), pdal::IcpFilter::icp(), pdal::PythonFilter::run(), and TEST().
std::string pdal::SQLiteWriter::getName () const virtual
Return the name of a stage.
Returns
The stage's name.
Implements pdal::Stage.
Definition at line 62 of file SQLiteWriter.cpp.
References pdal::PluginInfo::name.
const SpatialReference & pdal::Stage::getSpatialReference () const inherited
Get the spatial reference of the stage.
Get the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Returns
The stage's spatial reference.
Definition at line 474 of file Stage.cpp.
References pdal::Stage::m_spatialReference.
Referenced by pdal::Stage::execute(), pdal::PgReader::initialize(), pdal::BpfReader::inspect(), pdal::LasWriter::prepOutput(), pdal::MergeFilter::ready(), pdal::MergeFilter::run(), and TEST().
std::string::size_type pdal::Writer::handleFilenameTemplate (const std::string & filename) protected inherited
Locate template placeholder ('#') and validate filename with respect to placeholder.
Definition at line 47 of file Writer.cpp.
References pdal::Stage::getName().
void pdal::SQLiteWriter::initialize () private virtual
Initialize stage after options have been processed. Implement in subclass.
Reimplemented from pdal::Stage.
Definition at line 100 of file SQLiteWriter.cpp.
References pdal::Debug, pdal::Stage::log(), m_connection, m_modulename, m_patch, m_session, and pdal::Stage::throwError().
bool pdal::Stage::isDebug () const inherited
Determine whether the stage is in debug mode or not.
Returns
The stage's debug state.
Definition at line 243 of file Stage.hpp.
References pdal::Debug.
Referenced by pdal::Stage::setupLog(), pdal::Stage::startLogging(), and pdal::OciWriter::wipeBlockTable().
bool pdal::SQLiteWriter::IsValidGeometryWKT (std::string const & wkt) const private
Definition at line 363 of file SQLiteWriter.cpp.
Referenced by loadGeometryWKT().
std::string pdal::SQLiteWriter::loadGeometryWKT (std::string const & filename_or_wkt) const private
Definition at line 337 of file SQLiteWriter.cpp.
References pdal::FileUtils::fileExists(), IsValidGeometryWKT(), pdal::FileUtils::readFileIntoString(), and pdal::Stage::throwError().
Referenced by CreateCloud().
virtual LogPtr pdal::Stage::log () const virtual inherited
Return the stage's log pointer.
Returns
Log pointer.
Definition at line 225 of file Stage.hpp.
Referenced by pdal::OciReader::addDimensions(), pdal::GeoWaveReader::addDimensions(), pdal::SQLiteReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), pdal::LasWriter::addMetadataVlr(), pdal::LasWriter::addPipelineVlr(), pdal::OciWriter::blockTableExists(), pdal::CpdFilter::change(), pdal::PgWriter::CheckPointCloudExists(), pdal::PgWriter::CheckPostGISExists(), pdal::PgWriter::CheckTableExists(), CreateBlockTable(), CreateCloud(), CreateCloudTable(), CreateIndexes(), pdal::GeoWaveWriter::createJvm(), pdal::GeoWaveReader::createJvm(), pdal::PgReader::CursorSetup(), pdal::PgReader::CursorTeardown(), DeleteBlockTable(), DeleteCloudTable(), pdal::PgReader::fetchPcid(), pdal::SQLiteReader::fetchSpatialReference(), pdal::PgReader::fetchSpatialReference(), pdal::TextReader::fillFields(), pdal::ComputeRangeFilter::filter(), pdal::RadialDensityFilter::filter(), pdal::KDistanceFilter::filter(), pdal::LOFFilter::filter(), pdal::ELMFilter::filter(), pdal::ColorinterpFilter::filter(), pdal::GreedyProjection::filter(), pdal::LasWriter::finishOutput(), pdal::PgReader::getDataQuery(), pdal::GeoWaveWriter::initialize(), initialize(), pdal::GeoWaveReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), pdal::BpfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::MbReader::loadData(), pdal::PgReader::NextBuffer(), pdal::GreyhoundReader::prepared(), pdal::PMFFilter::prepared(), pdal::NormalFilter::prepared(), pdal::LasWriter::prepared(), pdal::PMFFilter::processGround(), pdal::MongusFilter::processGround(), pdal::TextReader::processOne(), pdal::GreyhoundReader::read(), pdal::SQLiteReader::read(), pdal::PtsReader::read(), pdal::PgReader::read(), pdal::GDALReader::readBandData(), pdal::SQLiteReader::readPatch(), pdal::GeoWaveReader::ready(), pdal::PythonFilter::ready(), pdal::CropFilter::ready(), pdal::SQLiteReader::ready(), pdal::ColorinterpFilter::ready(), pdal::ColorizationFilter::ready(), pdal::BpfWriter::readyFile(), pdal::GridProjectionFilter::run(), pdal::MovingLeastSquaresFilter::run(), pdal::IcpFilter::run(), pdal::CpdFilter::run(), pdal::VoxelGridFilter::run(), pdal::MergeFilter::run(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::SampleFilter::run(), pdal::PythonFilter::run(), pdal::IQRFilter::run(), pdal::MADFilter::run(), pdal::OutlierFilter::run(), pdal::MongusFilter::run(), pdal::LasWriter::spatialReferenceChanged(), pdal::GeoWaveWriter::write(), pdal::MatlabWriter::write(), pdal::OciWriter::writeInit(), writeInit(), pdal::OciWriter::writeTile(), and writeTile().
SQLiteWriter& pdal::SQLiteWriter::operator= (const SQLiteWriter &) private
size_t pdal::DbWriter::packedPointSize () const protected inherited
Definition at line 62 of file DbWriter.hpp.
Referenced by pdal::OciWriter::writePointMajor(), pdal::OciWriter::writeTile(), pdal::PgWriter::writeTile(), and writeTile().
bool pdal::Stage::parseName (std::string o, std::string::size_type & pos) static inherited
Parse a stage name from a string. Return the name and update the position in the input string to the end of the stage name.
Parameters
o Input string to parse.
pos Parsing start/end position.
Returns
Whether the parsed name is a valid stage name.
Definition at line 504 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::Kernel::parseStageOption().
bool pdal::Stage::parseTagName (std::string o, std::string::size_type & pos) static inherited
Parse a tag name from a string. Return the name and update the position in the input string to the end of the tag name.
Parameters
o Input string to parse.
pos Parsing start/end position.
tag Parsed tag name.
Returns
Whether the parsed name is a valid tag name.
Definition at line 518 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::PipelineReaderJSON::extractTag(), and pdal::Kernel::parseStageOption().
point_count_t pdal::Stage::pointCount () const protected inherited
Return the point count of all point views at the start of execution. Only valid during execute().
Returns
Total number of points in all point views being executed.
Definition at line 328 of file Stage.hpp.
Referenced by pdal::PlyWriter::ready(), and pdal::PlyWriter::writeHeader().
void pdal::Stage::prepare (PointTableRef table) inherited
Prepare a stage for execution. This function needs to be called on the terminal stage of a pipeline (linked set of stages) before execute can be called. Prepare recurses through all input stages.
Parameters
table PointTable being used for stage pipeline.
Definition at line 138 of file Stage.cpp.
References pdal::Stage::addDimensions(), pdal::Stage::handleOptions(), pdal::Stage::initialize(), pdal::Stage::l_initialize(), pdal::BasePointTable::layout(), pdal::Stage::m_args, pdal::Stage::m_inputs, pdal::Stage::prepare(), pdal::Stage::prepared(), pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), pdal::Stage::prepare(), pdal::PipelineManager::prepare(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
QuickInfo pdal::Stage::preview () inherited
Retrieve some basic point information without reading all data when possible. Usually implemented only by Readers.
Definition at line 127 of file Stage.cpp.
References pdal::Stage::handleOptions(), pdal::Stage::inspect(), pdal::Stage::m_args, pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by pdal::TIndexKernel::getFileInfo(), pdal::PipelineManager::preview(), pdal::InfoKernel::run(), and TEST().
size_t pdal::DbWriter::readField (const PointView & view, char * pos, Dimension::Id id, PointId idx) protected inherited
Read a field from a PointView and write its value as formatted for output to the DB schema to the location as requested.
Parameters
[in] view PointView to read from.
[in] pos Location in which to store field value.
[in] id ID of the dimension to read.
[in] idx Index of point to read.
Returns
Size of field as read.
Definition at line 175 of file DbWriter.cpp.
References pdal::PointView::getField(), pdal::DbWriter::m_dimMap, pdal::DbWriter::m_locationScaling, pdal::DbWriter::m_scaling, pdal::DimType::m_type, pdal::Scaling::m_xXform, pdal::Scaling::m_yXform, pdal::Scaling::m_zXform, pdal::Dimension::name(), pdal::Utils::numericCast(), pdal::Dimension::size(), pdal::XForm::toScaled(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by pdal::OciWriter::writeDimMajor().
size_t pdal::DbWriter::readPoint (const PointView & view, PointId idx, char * outbuf) protected inherited
Read a point's data packed into a buffer.
Parameters
[in] view PointView to read from.
[in] idx Index of point to read.
[in] outbuf Buffer to write to.
Returns
Number of bytes written to buffer.
Definition at line 234 of file DbWriter.cpp.
References pdal::PointView::getPackedPoint(), pdal::DbWriter::m_dbPointSize, pdal::DbWriter::m_dimTypes, pdal::DbWriter::m_scaling, pdal::DbWriter::m_xOffsets, pdal::Scaling::m_xXform, pdal::DbWriter::m_yOffsets, pdal::Scaling::m_yXform, pdal::DbWriter::m_zOffsets, pdal::Scaling::m_zXform, pdal::Dimension::name(), pdal::Utils::numericCast(), pdal::XForm::toScaled(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by pdal::OciWriter::writePointMajor(), pdal::PgWriter::writeTile(), and writeTile().
void pdal::Stage::removeOptions (const Options & opts) inherited
Remove options from a stage's option set.
Parameters
opts Options to remove.
Definition at line 206 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions().
void pdal::Stage::serialize (MetadataNode root, PipelineWriter::TagMap & tags) const inherited
Serialize a stage by inserting apporpritate data into the provided MetadataNode. Used to dump a pipeline specification in a portable format.
Parameters
root Node to which a stages meatdata should be added.
tags Pipeline writer's current list of stage tags.
Definition at line 64 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), pdal::Stage::getName(), pdal::Stage::m_inputs, pdal::Stage::m_options, and pdal::Options::toMetadata().
Referenced by pdal::PipelineWriter::writePipeline().
void pdal::DbWriter::setAutoXForm (const PointViewPtr view) protected virtual inherited
Make sure that computed offsets are stored in the schema.
Definition at line 151 of file DbWriter.cpp.
References pdal::DbWriter::m_dbDims, pdal::DbWriter::m_scaling, pdal::Scaling::m_xXform, pdal::Scaling::m_yXform, pdal::Scaling::m_zXform, pdal::Scaling::setAutoXForm(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by pdal::OciWriter::write().
void pdal::Stage::setInput (Stage & input) inherited
Add a stage to the input list of this stage.
Parameters
input Stage to use as input.
Definition at line 85 of file Stage.hpp.
Referenced by compareTextLasStreaming(), pdal::MergeKernel::execute(), pdal::TIndexReader::initialize(), main(), pdal::PipelineManager::makeFilter(), pdal::TIndexKernel::mergeFile(), pdal::PipelineReaderJSON::parsePipeline(), pdal::PipelineManager::replace(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::TransformationFilterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), pdal::TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testOverlay(), and writeData().
void pdal::Stage::setLog (LogPtr & log) inherited
Set the stage's log.
Parameters
log Log pointer.
Definition at line 217 of file Stage.hpp.
References setup::log.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), and testOverlay().
void pdal::Stage::setOptions (Options options) inherited
Set a stage's options.
Set the options on a stage, clearing all previously set options.
Parameters
options Options to set.
Definition at line 172 of file Stage.hpp.
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), getBytes(), pdal::TIndexReader::initialize(), main(), anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::PipelineManager::setOptions(), pdal::TransformationFilterTest::SetUp(), pdal::MatlabWriterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_file_type_stream(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), testReadWrite(), and writeData().
void pdal::Stage::setProgressFd (int fd) inherited
Set a file descriptor to which progress information should be written.
Parameters
fd Progress file descriptor.
Definition at line 93 of file Stage.hpp.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), and pdal::PipelineManager::addWriter().
void pdal::Stage::setSpatialReference (SpatialReference const & srs) inherited
Set the spatial reference of a stage.
Set the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Parameters
srs Spatial reference to set.
Definition at line 480 of file Stage.cpp.
References pdal::Stage::m_metadata.
Referenced by pdal::OciReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), pdal::BpfReader::initialize(), pdal::Ilvis2Reader::initialize(), pdal::PgReader::initialize(), pdal::LasWriter::initialize(), pdal::OptechReader::OptechReader(), pdal::MyReader::ready(), and TEST().
void pdal::Stage::setSpatialReference (MetadataNode & m, SpatialReference const & spatialRef) protected inherited
Definition at line 486 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::empty(), pdal::MetadataNode::findChild(), pdal::SpatialReference::getWKT(), pdal::Stage::m_spatialReference, pdal::MetadataNode::name(), and pdal::SpatialReference::toMetadata().
void pdal::Stage::setTag (const std::string & tag) inherited
Set a specific tag name.
Definition at line 256 of file Stage.hpp.
Referenced by pdal::PipelineManager::makeFilter(), and pdal::PipelineManager::makeReader().
void pdal::Stage::startLogging () const inherited
Push the stage's leader into the log.
Definition at line 538 of file Stage.cpp.
References pdal::gdal::ErrorHandler::getGlobalErrorHandler(), pdal::Stage::isDebug(), pdal::Stage::m_log, pdal::Stage::m_logLeader, and pdal::gdal::ErrorHandler::set().
Referenced by pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::preview().
void pdal::Stage::stopLogging () const inherited
Pop the stage's leader from the log.
Definition at line 545 of file Stage.cpp.
References pdal::Stage::m_log.
Referenced by pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::preview().
virtual std::string pdal::Stage::tag () const virtual inherited
Return the tag name of a stage.
Returns
The tag name.
Definition at line 264 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTag(), pdal::TranslateKernel::makeJSONPipeline(), and pdal::PipelineManager::stageOptions().
void pdal::Stage::throwError (const std::string & s) const protected inherited
Definition at line 532 of file Stage.cpp.
References pdal::Stage::getName().
Referenced by pdal::SQLiteReader::addDimensions(), pdal::MrsidReader::addDimensions(), pdal::TextReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), pdal::PlyReader::addDimensions(), pdal::LasWriter::addGeotiffVlrs(), pdal::LasWriter::addVlr(), pdal::PgWriter::CheckTableExists(), pdal::OciWriter::createPCEntry(), pdal::ReprojectionFilter::createTransform(), pdal::MatlabWriter::done(), pdal::NitfWriter::doneFile(), pdal::GDALWriter::doneFile(), pdal::OGRWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::GDALWriter::expandGrid(), pdal::PlyReader::extractElement(), pdal::PlyReader::extractEnd(), pdal::PlyReader::extractFormat(), pdal::PlyReader::extractHeader(), pdal::PlyReader::extractMagic(), pdal::PlyReader::extractProperty(), pdal::PgReader::fetchPcid(), pdal::PgReader::fetchSpatialReference(), pdal::LasWriter::fillForwardList(), pdal::LasWriter::fillHeader(), pdal::LasWriter::fillPointBuf(), pdal::HAGFilter::filter(), pdal::EigenvaluesFilter::filter(), pdal::ApproximateCoplanarFilter::filter(), pdal::NormalFilter::filter(), pdal::LasWriter::finishOutput(), pdal::TIndexReader::getFields(), pdal::PgReader::getNumPoints(), pdal::PlyWriter::getType(), pdal::LasWriter::handleLaszip(), pdal::OciWriter::initialize(), initialize(), pdal::OciReader::initialize(), pdal::GDALWriter::initialize(), pdal::TextReader::initialize(), pdal::ReprojectionFilter::initialize(), pdal::PtsReader::initialize(), pdal::RangeFilter::initialize(), pdal::MatlabReader::initialize(), pdal::OGRWriter::initialize(), pdal::FerryFilter::initialize(), pdal::SQLiteReader::initialize(), pdal::OptechReader::initialize(), pdal::DividerFilter::initialize(), pdal::TIndexReader::initialize(), pdal::QfitReader::initialize(), pdal::BpfWriter::initialize(), pdal::ColorizationFilter::initialize(), pdal::BpfReader::initialize(), pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::LasWriter::initialize(), pdal::FauxReader::initialize(), pdal::GreedyProjection::initialize(), pdal::GDALReader::inspect(), pdal::OciWriter::isGeographic(), pdal::BpfWriter::loadBpfDimensions(), pdal::MbReader::loadData(), loadGeometryWKT(), pdal::OciWriter::loadSQLData(), pdal::NitfWriter::NitfWriter(), pdal::MatlabWriter::prepared(), pdal::GDALWriter::prepared(), pdal::PlyWriter::prepared(), pdal::ComputeRangeFilter::prepared(), pdal::HAGFilter::prepared(), pdal::GroupByFilter::prepared(), pdal::IQRFilter::prepared(), pdal::LocateFilter::prepared(), pdal::RangeFilter::prepared(), pdal::MADFilter::prepared(), pdal::OGRWriter::prepared(), pdal::FerryFilter::prepared(), pdal::SortFilter::prepared(), pdal::ColorinterpFilter::prepared(), pdal::LasWriter::prepared(), pdal::OGRWriter::processOne(), pdal::Ilvis2Reader::processOne(), pdal::MatlabReader::processOne(), pdal::QfitReader::read(), pdal::OciReader::readBlob(), pdal::PlyReader::readElement(), pdal::SQLiteReader::readPatch(), pdal::OciReader::readPointMajor(), pdal::MatlabWriter::ready(), pdal::PlyWriter::ready(), pdal::SbetReader::ready(), pdal::GDALReader::ready(), pdal::OptechReader::ready(), pdal::PtsReader::ready(), pdal::ColorinterpFilter::ready(), pdal::QfitReader::ready(), pdal::TextReader::ready(), pdal::MbReader::ready(), pdal::ColorizationFilter::ready(), pdal::Ilvis2Reader::ready(), pdal::OGRWriter::readyFile(), pdal::BpfWriter::readyFile(), pdal::LasWriter::readyFile(), pdal::LasWriter::readyLazPerfCompression(), pdal::GDALWriter::readyTable(), pdal::NitfWriter::reprojectBoxToDD(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::PgWriter::SetupSchema(), pdal::CropFilter::transform(), pdal::OciWriter::updatePCExtent(), pdal::OciReader::validateQuery(), pdal::SQLiteReader::validateQuery(), pdal::MatlabWriter::write(), pdal::LasWriter::writeLasZipBuf(), pdal::OciWriter::writePointMajor(), pdal::OciWriter::writeTile(), writeTile(), and pdal::BpfWriter::writeView().
void pdal::Stage::throwStreamingError () const protected inherited
Definition at line 339 of file Stage.hpp.
Referenced by pdal::ColorinterpFilter::processOne().
void pdal::SQLiteWriter::write (const PointViewPtr) private virtual
Write the point in a PointView. This is a simplification of the run() interface for convenience. Impelment in subclass if desired.
Reimplemented from pdal::Writer.
Definition at line 131 of file SQLiteWriter.cpp.
References writeInit(), and writeTile().
void pdal::SQLiteWriter::writeInit () private
Definition at line 137 of file SQLiteWriter.cpp.
References CreateBlockTable(), CreateCloud(), CreateCloudTable(), pdal::Debug, DeleteBlockTable(), DeleteCloudTable(), pdal::Stage::log(), m_block_insert_query, m_block_table, m_cloud_column, m_cloud_table, m_doCreateIndex, m_overwrite, m_preSql, m_sdo_pc_is_initialized, m_session, pdal::FileUtils::readFileIntoString(), and pdal::Utils::tolower().
Referenced by write().
void pdal::SQLiteWriter::writeTile (const PointViewPtr view) private
Definition at line 456 of file SQLiteWriter.cpp.
References b, pdal::DbWriter::dbDimTypes(), pdal::Debug3, pdal::Stage::log(), m_block_id, m_block_insert_query, m_doCompression, m_obj_id, m_patch, m_session, m_srid, pdal::DbWriter::packedPointSize(), pdal::DbWriter::readPoint(), pdal::Dimension::size(), pdal::Stage::throwError(), pdal::BOX3D::toBox(), and pdal::BOX3D::toWKT().
Referenced by write().
Member Data Documentation
int32_t pdal::SQLiteWriter::m_block_id private
Definition at line 86 of file SQLiteWriter.hpp.
Referenced by writeTile().
std::ostringstream pdal::SQLiteWriter::m_block_insert_query private
Definition at line 84 of file SQLiteWriter.hpp.
Referenced by writeInit(), and writeTile().
std::string pdal::SQLiteWriter::m_block_table private
Definition at line 90 of file SQLiteWriter.hpp.
Referenced by addArgs(), CreateBlockTable(), CreateCloud(), DeleteBlockTable(), done(), and writeInit().
BOX3D pdal::SQLiteWriter::m_bounds private
Definition at line 82 of file SQLiteWriter.hpp.
std::string pdal::SQLiteWriter::m_cloud_column private
Definition at line 92 of file SQLiteWriter.hpp.
Referenced by addArgs(), CreateBlockTable(), CreateCloud(), CreateCloudTable(), and writeInit().
std::string pdal::SQLiteWriter::m_cloud_table private
Definition at line 91 of file SQLiteWriter.hpp.
Referenced by addArgs(), CreateBlockTable(), CreateCloud(), CreateCloudTable(), DeleteCloudTable(), and writeInit().
std::string pdal::SQLiteWriter::m_cloudBoundary private
Definition at line 95 of file SQLiteWriter.hpp.
Referenced by addArgs(), and CreateCloud().
std::string pdal::SQLiteWriter::m_connection private
Definition at line 93 of file SQLiteWriter.hpp.
Referenced by addArgs(), and initialize().
bool pdal::SQLiteWriter::m_doCompression private
Definition at line 98 of file SQLiteWriter.hpp.
Referenced by addArgs(), CreateCloud(), and writeTile().
bool pdal::SQLiteWriter::m_doCreateIndex private
Definition at line 81 of file SQLiteWriter.hpp.
Referenced by done(), and writeInit().
bool pdal::SQLiteWriter::m_is3d private
Definition at line 97 of file SQLiteWriter.hpp.
Referenced by addArgs(), and done().
MetadataNode pdal::Stage::m_metadata protected inherited
Stage's metadata.
Definition at line 316 of file Stage.hpp.
Referenced by pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), pdal::Stage::l_initialize(), pdal::BpfReader::readHeaderExtraData(), pdal::BpfReader::readUlemFiles(), pdal::Ilvis2Reader::ready(), and pdal::Stage::setSpatialReference().
std::string pdal::SQLiteWriter::m_modulename private
Definition at line 94 of file SQLiteWriter.hpp.
Referenced by addArgs(), and initialize().
int32_t pdal::SQLiteWriter::m_obj_id private
Definition at line 85 of file SQLiteWriter.hpp.
Referenced by CreateCloud(), and writeTile().
Options pdal::Stage::m_options protected inherited
Stage's options.
Definition at line 315 of file Stage.hpp.
Referenced by pdal::Stage::addConditionalOptions(), pdal::Stage::handleOptions(), and pdal::Stage::serialize().
bool pdal::SQLiteWriter::m_overwrite private
Definition at line 98 of file SQLiteWriter.hpp.
Referenced by addArgs(), and writeInit().
PatchPtr pdal::SQLiteWriter::m_patch private
Definition at line 100 of file SQLiteWriter.hpp.
Referenced by initialize(), and writeTile().
long pdal::SQLiteWriter::m_pcId private
Definition at line 96 of file SQLiteWriter.hpp.
Referenced by addArgs(), and CreateCloud().
std::string pdal::SQLiteWriter::m_postSql private
Definition at line 89 of file SQLiteWriter.hpp.
Referenced by addArgs(), and done().
std::string pdal::SQLiteWriter::m_preSql private
Definition at line 88 of file SQLiteWriter.hpp.
Referenced by addArgs(), and writeInit().
int pdal::Stage::m_progressFd protected inherited
Descriptor for progress info.
Definition at line 317 of file Stage.hpp.
Referenced by pdal::LasWriter::doneFile(), pdal::NitfWriter::readyFile(), pdal::LasWriter::readyFile(), and pdal::LasWriter::writeView().
bool pdal::SQLiteWriter::m_sdo_pc_is_initialized private
Definition at line 83 of file SQLiteWriter.hpp.
Referenced by writeInit().
std::unique_ptr<SQLite> pdal::SQLiteWriter::m_session private
Definition at line 79 of file SQLiteWriter.hpp.
Referenced by CreateBlockTable(), CreateCloud(), CreateCloudTable(), CreateIndexes(), DeleteBlockTable(), DeleteCloudTable(), done(), initialize(), writeInit(), and writeTile().
uint32_t pdal::SQLiteWriter::m_srid private
Definition at line 87 of file SQLiteWriter.hpp.
Referenced by addArgs(), CreateBlockTable(), CreateCloud(), CreateCloudTable(), and writeTile().
The documentation for this class was generated from the following files:
pdal/plugins/sqlite/io/SQLiteWriter.hpp
pdal/plugins/sqlite/io/SQLiteWriter.cpp