PDAL: pdal::ProgramArgs Class Reference
pdal::ProgramArgs Class Reference
#include <ProgramArgs.hpp>
Public Member Functions
Arg & add (const std::string &name, const std::string description, std::string &var, std::string def)
Arg & add (const std::string &name, const std::string &description, std::vector< std::string > &var)
bool set (const std::string &name) const
template<typename T >
Arg & add (const std::string &name, const std::string &description, std::vector< T > &var)
template<typename T >
Arg & add (const std::string &name, const std::string &description, std::vector< T > &var, std::vector< T > def)
template<typename T >
Arg & add (const std::string &name, const std::string description, T &var, T def)
template<typename T >
Arg & add (const std::string &name, const std::string description, T &var)
void parseSimple (std::vector< std::string > &s)
void parse (const std::vector< std::string > &s)
void addSynonym (const std::string &name, const std::string &synonym)
void reset ()
std::string commandLine () const
void dump (std::ostream &out, size_t indent, size_t totalWidth) const
void dump2 (std::ostream &out, size_t nameIndent, size_t descripIndent, size_t totalWidth) const
void dump3 (std::ostream &out) const
Private Member Functions
void splitName (const std::string &name, std::string &longname, std::string &shortname)
void addLongArg (const std::string &name, Arg *arg)
void addShortArg (const std::string &name, Arg *arg)
Arg * findLongArg (const std::string &s) const
Arg * findShortArg (char c) const
int parseArg (const std::string &arg, const std::string &value)
int parseLongArg (const std::string &inName, const std::string &inValue)
int parseShortArg (const std::string &name, const std::string &value)
void validate ()
Private Attributes
std::vector< std::unique_ptr< Arg > > m_args
std::map< std::string, Arg * > m_shortargs
Storage for arguments.
std::map< std::string, Arg * > m_longargs
Map from shortname to args.
Detailed Description
Parses command lines, provides validation and stores found values in bound variables. Add arguments with add. When all arguments have been added, use parse to validate command line and assign values to variables bound with add.
Definition at line 926 of file ProgramArgs.hpp.
Member Function Documentation
Arg& pdal::ProgramArgs::add (const std::string & name, const std::string description, std::string & var, std::string def)
Add a string argument to the list of arguments.
Parameters
name Name of argument. Argument names are specified as "longname[,shortname]", where shortname is an optional one-character abbreviation.
description Description of the argument.
var Reference to variable to bind to argument.
def Default value of argument.
Returns
Reference to the new argument.
Definition at line 941 of file ProgramArgs.hpp.
References pdal::Dimension::description(), and pdal::Dimension::name().
Referenced by pdal::MyWriter::addArgs(), pdal::MyReader::addArgs(), pdal::MyFilter::addArgs(), pdal::GeoWaveWriter::addArgs(), pdal::OciWriter::addArgs(), pdal::VoxelGridFilter::addArgs(), pdal::AssignFilter::addArgs(), pdal::MatlabWriter::addArgs(), pdal::PgWriter::addArgs(), pdal::SQLiteWriter::addArgs(), pdal::TextWriter::addArgs(), pdal::OciReader::addArgs(), pdal::SbetWriter::addArgs(), pdal::TailFilter::addArgs(), pdal::HeadFilter::addArgs(), pdal::PCLBlock::addArgs(), pdal::GDALWriter::addArgs(), pdal::CpdFilter::addArgs(), pdal::GreyhoundReader::addArgs(), pdal::GeoWaveReader::addArgs(), pdal::MatlabFilter::addArgs(), pdal::DecimationFilter::addArgs(), pdal::ReprojectionFilter::addArgs(), pdal::PcdWriter::addArgs(), pdal::PlyWriter::addArgs(), pdal::PoissonFilter::addArgs(), pdal::RadialDensityFilter::addArgs(), pdal::RangeFilter::addArgs(), pdal::SampleFilter::addArgs(), pdal::ClusterFilter::addArgs(), pdal::GroupByFilter::addArgs(), pdal::VoxelCenterNearestNeighborFilter::addArgs(), pdal::VoxelCentroidNearestNeighborFilter::addArgs(), pdal::KDistanceFilter::addArgs(), pdal::PythonFilter::addArgs(), pdal::LOFFilter::addArgs(), pdal::IQRFilter::addArgs(), pdal::LocateFilter::addArgs(), pdal::ELMFilter::addArgs(), pdal::MADFilter::addArgs(), pdal::PMFFilter::addArgs(), pdal::OGRWriter::addArgs(), pdal::EigenvaluesFilter::addArgs(), pdal::TextReader::addArgs(), pdal::DbWriter::addArgs(), pdal::EstimateRankFilter::addArgs(), pdal::TransformationFilter::addArgs(), pdal::FerryFilter::addArgs(), pdal::CropFilter::addArgs(), pdal::ApproximateCoplanarFilter::addArgs(), pdal::SQLiteReader::addArgs(), App::addArgs(), pdal::SMRFilter::addArgs(), pdal::MatlabReader::addArgs(), pdal::SortFilter::addArgs(), pdal::SplitterFilter::addArgs(), pdal::IcebridgeReader::addArgs(), pdal::DividerFilter::addArgs(), pdal::TIndexReader::addArgs(), pdal::MongusFilter::addArgs(), pdal::NormalFilter::addArgs(), pdal::OutlierFilter::addArgs(), pdal::ColorinterpFilter::addArgs(), pdal::QfitReader::addArgs(), pdal::OverlayFilter::addArgs(), pdal::MbReader::addArgs(), pdal::Scaling::addArgs(), pdal::BpfWriter::addArgs(), pdal::RxpReader::addArgs(), pdal::ColorizationFilter::addArgs(), pdal::NitfFileWriter::addArgs(), pdal::Ilvis2Reader::addArgs(), pdal::PgReader::addArgs(), pdal::ChipperFilter::addArgs(), pdal::LasReader::addArgs(), pdal::LasWriter::addArgs(), pdal::FauxReader::addArgs(), pdal::StatsFilter::addArgs(), pdal::GreedyProjection::addArgs(), pdal::Kernel::addBasicSwitches(), pdal::Stage::addSpatialReferenceArg(), pdal::MyKernel::addSwitches(), pdal::PCLKernel::addSwitches(), pdal::MergeKernel::addSwitches(), pdal::SplitKernel::addSwitches(), pdal::SmoothKernel::addSwitches(), pdal::SortKernel::addSwitches(), pdal::RandomKernel::addSwitches(), pdal::PipelineKernel::addSwitches(), pdal::DiffKernel::addSwitches(), pdal::HausdorffKernel::addSwitches(), pdal::TranslateKernel::addSwitches(), pdal::GroundKernel::addSwitches(), pdal::DensityKernel::addSwitches(), pdal::InfoKernel::addSwitches(), pdal::DeltaKernel::addSwitches(), pdal::TIndexKernel::addSwitches(), pdal::Kernel::doSwitches(), pdal::Stage::l_addArgs(), pdal::nitfwrap::NitfWrap::parseArgs(), pdal::DimBuilder::parseArgs(), pdal::Reader::readerAddArgs(), TEST(), and pdal::TEST().
Arg& pdal::ProgramArgs::add (const std::string & name, const std::string & description, std::vector< std::string > & var)
Add a list-based (vector) string argument
Parameters
name Name of argument. Argument names are specified as "longname[,shortname]", where shortname is an optional one-character abbreviation.
description Description of the argument.
var Reference to variable to bind to argument.
Returns
Reference to the new argument.
Definition at line 957 of file ProgramArgs.hpp.
References pdal::Dimension::description(), and pdal::Dimension::name().
template<typename T > Arg& pdal::ProgramArgs::add (const std::string & name, const std::string & description, std::vector< T > & var)
Add a list-based (vector) argument.
Parameters
name Name of argument. Argument names are specified as "longname[,shortname]", where shortname is an optional one-character abbreviation.
description Description of the argument.
var Reference to variable to bind to argument.
Returns
Reference to the new argument.
Definition at line 986 of file ProgramArgs.hpp.
References pdal::Dimension::description().
template<typename T > Arg& pdal::ProgramArgs::add (const std::string & name, const std::string & description, std::vector< T > & var, std::vector< T > def)
Add a list-based (vector) argument with a default.
Parameters
name Name of argument. Argument names are specified as "longname[,shortname]", where shortname is an optional one-character abbreviation.
description Description of the argument.
var Reference to variable to bind to argument.
Returns
Reference to the new argument.
Definition at line 1010 of file ProgramArgs.hpp.
References pdal::Dimension::description().
template<typename T > Arg& pdal::ProgramArgs::add (const std::string & name, const std::string description, T & var, T def)
Add an argument to the list of arguments with a default.
Parameters
name Name of argument. Argument names are specified as "longname[,shortname]", where shortname is an optional one-character abbreviation.
description Description of the argument.
var Reference to variable to bind to argument.
def Default value of argument.
Returns
Reference to the new argument.
Definition at line 1035 of file ProgramArgs.hpp.
References pdal::Dimension::description().
template<typename T > Arg& pdal::ProgramArgs::add (const std::string & name, const std::string description, T & var)
Add an argument to the list of arguments.
Parameters
name Name of argument. Argument names are specified as "longname[,shortname]", where shortname is an optional one-character abbreviation.
description Description of the argument.
var Reference to variable to bind to argument.
Returns
Reference to the new argument.
Definition at line 1059 of file ProgramArgs.hpp.
References pdal::Dimension::description().
void pdal::ProgramArgs::addLongArg (const std::string & name, Arg * arg) private
Definition at line 1366 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error(), and pdal::Dimension::name().
void pdal::ProgramArgs::addShortArg (const std::string & name, Arg * arg) private
Definition at line 1381 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error(), and pdal::Dimension::name().
void pdal::ProgramArgs::addSynonym (const std::string & name, const std::string & synonym)
Add a synonym for an argument.
Parameters
name Longname of existing arugment.
synonym Synonym for argument.
Definition at line 1168 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error().
Referenced by pdal::SQLiteWriter::addArgs(), and TEST().
std::string pdal::ProgramArgs::commandLine () const
Return a string suitable for use in a "usage" line for display to users as help.
Definition at line 1194 of file ProgramArgs.hpp.
References a, pdal::Arg::commandLine(), and pdal::Arg::hidden().
Referenced by pdal::nitfwrap::anonymous_namespace{NitfWrap.cpp}::outputHelp(), and pdal::Kernel::outputHelp().
void pdal::ProgramArgs::dump (std::ostream & out, size_t indent, size_t totalWidth) const
Write a formatted description of arguments to an output stream.
Write a list of the names and descriptions of arguments suitable for display as help information.
Parameters
out Stream to which output should be written.
indent Number of characters to indent all text.
totalWidth Total width to assume for formatting output. Typically this is the width of a terminal window.
Definition at line 1224 of file ProgramArgs.hpp.
References a, pdal::Arg::description(), pdal::Arg::hidden(), pdal::Dimension::name(), pdal::Arg::nameDescrip(), and pdal::Utils::wordWrap().
Referenced by App::outputHelp(), pdal::nitfwrap::anonymous_namespace{NitfWrap.cpp}::outputHelp(), and pdal::Kernel::outputHelp().
void pdal::ProgramArgs::dump2 (std::ostream & out, size_t nameIndent, size_t descripIndent, size_t totalWidth) const
Write a verbose description of arguments to an output stream. Each argument is on its own line. The argument's description follows on subsequent lines.
Parameters
out Stream to which output should be written.
nameIndent Number of characters to indent argument lines.
descripIndent Number of characters to indent description lines.
totalWidth Total line width.
Definition at line 1282 of file ProgramArgs.hpp.
References a, pdal::Arg::defaultProvided(), pdal::Arg::defaultVal(), pdal::Arg::description(), pdal::Arg::longname(), and pdal::Utils::wordWrap().
Referenced by App::outputOptions().
void pdal::ProgramArgs::dump3 (std::ostream & out) const
Write a JSON array of arguments to an output stream.
Parameters
out Stream to which output should be written.
Definition at line 1309 of file ProgramArgs.hpp.
References a, pdal::Arg::defaultProvided(), pdal::Arg::defaultVal(), pdal::Arg::description(), and pdal::Arg::longname().
Referenced by App::outputOptions().
Arg* pdal::ProgramArgs::findLongArg (const std::string & s) const private
Definition at line 1396 of file ProgramArgs.hpp.
Arg* pdal::ProgramArgs::findShortArg (char c) const private
Definition at line 1410 of file ProgramArgs.hpp.
void pdal::ProgramArgs::parse (const std::vector< std::string > & s)
Parse a command line as specified by its argument list. Parsing validates the argument vector and assigns values to variables bound to added arguments.
Parameters
s List of strings that constitute the argument list.
Definition at line 1134 of file ProgramArgs.hpp.
References pdal::Arg::assignPositional().
Referenced by pdal::Kernel::doSwitches(), pdal::nitfwrap::NitfWrap::parseArgs(), pdal::DimBuilder::parseArgs(), TEST(), and pdal::TEST().
int pdal::ProgramArgs::parseArg (const std::string & arg, const std::string & value) private
Definition at line 1427 of file ProgramArgs.hpp.
int pdal::ProgramArgs::parseLongArg (const std::string & inName, const std::string & inValue) private
Definition at line 1446 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error(), pdal::Dimension::name(), pdal::Arg::needsValue(), and pdal::Arg::setValue().
int pdal::ProgramArgs::parseShortArg (const std::string & name, const std::string & value) private
Definition at line 1507 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error().
void pdal::ProgramArgs::parseSimple (std::vector< std::string > & s)
Parse a command line as specified by its argument vector. No validation occurs and only argument value exceptions are raised, but assignments are made to bound variables where possible.
Parameters
s List of strings that constitute the argument list.
Definition at line 1078 of file ProgramArgs.hpp.
References pdal::Arg::assignPositional().
Referenced by pdal::Kernel::doSwitches(), App::execute(), and TEST().
void pdal::ProgramArgs::reset ()
Reset the state of all arguments and bound variables as if no parsing had occurred.
Definition at line 1184 of file ProgramArgs.hpp.
Referenced by TEST(), and pdal::TEST().
bool pdal::ProgramArgs::set (const std::string & name) const
Return whether the argument (as specified by it's longname) had its value set during parsing.
Definition at line 967 of file ProgramArgs.hpp.
References pdal::Dimension::name(), and pdal::Arg::set().
Referenced by pdal::TIndexKernel::validateSwitches().
void pdal::ProgramArgs::splitName (const std::string & name, std::string & longname, std::string & shortname) private
Definition at line 1342 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error(), and pdal::Utils::split().
void pdal::ProgramArgs::validate () private
Definition at line 1546 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error(), pdal::Arg::longname(), pdal::Arg::Optional, pdal::Arg::positional(), and pdal::Arg::Required.
Member Data Documentation
std::vector<std::unique_ptr<Arg> > pdal::ProgramArgs::m_args private
Definition at line 1560 of file ProgramArgs.hpp.
std::map<std::string, Arg *> pdal::ProgramArgs::m_longargs private
Map from shortname to args.
Definition at line 1562 of file ProgramArgs.hpp.
std::map<std::string, Arg *> pdal::ProgramArgs::m_shortargs private
Storage for arguments.
Definition at line 1561 of file ProgramArgs.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/util/ProgramArgs.hpp