PDAL: pdal::gdal::SpatialRef Class Reference
pdal::gdal::SpatialRef Class Reference
#include <GDALUtils.hpp>
Public Member Functions
SpatialRef ()
SpatialRef (const std::string &srs)
void setFromLayer (OGRLayerH layer)
operator bool () const
OGRSpatialReferenceH get () const
std::string wkt () const
bool empty () const
Private Member Functions
void newRef (void *v)
Private Attributes
RefPtr m_ref
Detailed Description
Definition at line 78 of file GDALUtils.hpp.
Constructor & Destructor Documentation
pdal::gdal::SpatialRef::SpatialRef ()
Definition at line 81 of file GDALUtils.hpp.
References newRef().
pdal::gdal::SpatialRef::SpatialRef (const std::string & srs)
Definition at line 83 of file GDALUtils.hpp.
References newRef().
Member Function Documentation
bool pdal::gdal::SpatialRef::empty () const
Definition at line 115 of file GDALUtils.hpp.
References wkt().
Referenced by pdal::gdal::Geometry::Geometry().
OGRSpatialReferenceH pdal::gdal::SpatialRef::get () const
Definition at line 103 of file GDALUtils.hpp.
References m_ref.
Referenced by pdal::hexdensity::writer::OGR::createLayer(), pdal::gdal::Geometry::Geometry(), pdal::TIndexKernel::prepareGeometry(), and pdal::gdal::Geometry::transform().
void pdal::gdal::SpatialRef::newRef (void * v) private
Definition at line 121 of file GDALUtils.hpp.
References m_ref.
Referenced by pdal::gdal::Geometry::Geometry(), pdal::gdal::Geometry::setFromGeometry(), setFromLayer(), and SpatialRef().
pdal::gdal::SpatialRef::operator bool () const
Definition at line 101 of file GDALUtils.hpp.
References m_ref.
void pdal::gdal::SpatialRef::setFromLayer (OGRLayerH layer)
Definition at line 89 of file GDALUtils.hpp.
References newRef().
std::string pdal::gdal::SpatialRef::wkt () const
Definition at line 105 of file GDALUtils.hpp.
References m_ref.
Referenced by empty().
Member Data Documentation
RefPtr pdal::gdal::SpatialRef::m_ref private
Definition at line 126 of file GDALUtils.hpp.
Referenced by get(), pdal::gdal::Geometry::get(), newRef(), pdal::gdal::Geometry::newRef(), operator bool(), pdal::gdal::Geometry::transform(), wkt(), and pdal::gdal::Geometry::wkt().
The documentation for this class was generated from the following file:
pdal/pdal/GDALUtils.hpp