PDAL: pdal::NitfFileReader Class Reference
pdal::NitfFileReader Class Reference
#include <NitfFileReader.hpp>
Classes
struct error
Public Member Functions
NitfFileReader (const std::string &filename)
NitfFileReader (const NitfFileReader &)=delete
NitfFileReader & operator= (const NitfFileReader &)=delete
void open ()
void close ()
void getLasOffset (uint64_t &offset, uint64_t &length)
void extractMetadata (MetadataNode &metadata)
Private Member Functions
bool locateLidarImageSegment ()
bool locateLidarDataSegment ()
Private Attributes
std::unique_ptr< nitf::IOHandle > m_io
nitf::Record m_record
std::string m_filename
bool m_validLidarSegments
nitf::Uint32 m_lidarDataSegment
Detailed Description
Definition at line 76 of file NitfFileReader.hpp.
Constructor & Destructor Documentation
pdal::NitfFileReader::NitfFileReader (const std::string & filename)
Definition at line 58 of file NitfFileReader.cpp.
References pdal::register_tre_plugins().
pdal::NitfFileReader::NitfFileReader (const NitfFileReader &) delete
Member Function Documentation
void pdal::NitfFileReader::close ()
Definition at line 120 of file NitfFileReader.cpp.
References m_io.
Referenced by pdal::nitfwrap::NitfWrap::unwrap().
void pdal::NitfFileReader::extractMetadata (MetadataNode & metadata)
Definition at line 154 of file NitfFileReader.cpp.
References m_record, pdal::MetadataReader::read(), and SHOW_EMPTY_FIELDS.
Referenced by pdal::NitfReader::initialize().
void pdal::NitfFileReader::getLasOffset (uint64_t & offset, uint64_t & length)
Definition at line 126 of file NitfFileReader.cpp.
References m_lidarDataSegment, m_record, and m_validLidarSegments.
Referenced by pdal::NitfReader::initialize(), and pdal::nitfwrap::NitfWrap::unwrap().
bool pdal::NitfFileReader::locateLidarDataSegment () private
Definition at line 205 of file NitfFileReader.cpp.
References m_lidarDataSegment, and m_record.
Referenced by open().
bool pdal::NitfFileReader::locateLidarImageSegment () private
Definition at line 170 of file NitfFileReader.cpp.
References m_record.
Referenced by open().
void pdal::NitfFileReader::open ()
Definition at line 74 of file NitfFileReader.cpp.
References locateLidarDataSegment(), locateLidarImageSegment(), m_filename, m_io, m_record, m_validLidarSegments, and REQUIRE_LIDAR_SEGMENTS.
Referenced by pdal::NitfReader::initialize(), and pdal::nitfwrap::NitfWrap::unwrap().
NitfFileReader& pdal::NitfFileReader::operator= (const NitfFileReader &) delete
Member Data Documentation
std::string pdal::NitfFileReader::m_filename private
Definition at line 101 of file NitfFileReader.hpp.
Referenced by open().
std::unique_ptr<nitf::IOHandle> pdal::NitfFileReader::m_io private
Definition at line 98 of file NitfFileReader.hpp.
Referenced by close(), and open().
nitf::Uint32 pdal::NitfFileReader::m_lidarDataSegment private
Definition at line 103 of file NitfFileReader.hpp.
Referenced by getLasOffset(), and locateLidarDataSegment().
nitf::Record pdal::NitfFileReader::m_record private
Definition at line 99 of file NitfFileReader.hpp.
Referenced by extractMetadata(), getLasOffset(), locateLidarDataSegment(), locateLidarImageSegment(), and open().
bool pdal::NitfFileReader::m_validLidarSegments private
Definition at line 102 of file NitfFileReader.hpp.
Referenced by getLasOffset(), and open().
The documentation for this class was generated from the following files:
pdal/plugins/nitf/io/NitfFileReader.hpp
pdal/plugins/nitf/io/NitfFileReader.cpp