PDAL: pdal::SplitKernel Class Reference
pdal::SplitKernel Class Reference
#include <SplitKernel.hpp>
Public Member Functions
std::string getName () const
int execute ()
int run (const StringList &cmdArgs, LogPtr &log)
std::string getShortName () const
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
Protected Member Functions
Stage & makeReader (const std::string &inputFile, std::string driver)
Stage & makeReader (const std::string &inputFile, std::string driver, Options options)
Stage & makeFilter (const std::string &driver, Stage &parent)
Stage & makeFilter (const std::string &driver, Stage &parent, Options options)
Stage & makeFilter (const std::string &driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver, Options options)
virtual bool isStagePrefix (const std::string &stageType)
Protected Attributes
LogPtr m_log
PipelineManager m_manager
std::string m_driverOverride
Private Member Functions
void addSwitches (ProgramArgs &args)
void validateSwitches (ProgramArgs &args)
Private Attributes
std::string m_inputFile
std::string m_outputFile
uint32_t m_capacity
double m_length
double m_xOrigin
double m_yOrigin
Detailed Description
Definition at line 46 of file SplitKernel.hpp.
Member Function Documentation
void pdal::SplitKernel::addSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 55 of file SplitKernel.cpp.
References pdal::ProgramArgs::add(), m_capacity, m_inputFile, m_length, m_outputFile, m_xOrigin, m_yOrigin, and pdal::Arg::setPositional().
static void* pdal::SplitKernel::create () static
static int32_t pdal::SplitKernel::destroy (void *) static
int pdal::SplitKernel::execute () virtual
Implements pdal::Kernel.
Definition at line 99 of file SplitKernel.cpp.
References pdal::Options::add(), pdal::BufferReader::addView(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, m_capacity, pdal::Kernel::m_driverOverride, m_inputFile, m_length, m_outputFile, m_xOrigin, m_yOrigin, pdal::anonymous_namespace{SplitKernel.cpp}::makeFilename(), pdal::Kernel::makeFilter(), pdal::Kernel::makeReader(), pdal::Kernel::makeWriter(), and pdal::Stage::prepare().
std::string pdal::SplitKernel::getName () const virtual
Implements pdal::Kernel.
Definition at line 49 of file SplitKernel.cpp.
References pdal::PluginInfo::name.
std::string pdal::Kernel::getShortName () const inherited
Definition at line 67 of file Kernel.hpp.
References pdal::Utils::split2().
Referenced by pdal::Kernel::outputHelp().
bool pdal::Kernel::isStagePrefix (const std::string & stageType) protected virtual inherited
Reimplemented in pdal::PipelineKernel.
Definition at line 58 of file Kernel.cpp.
Referenced by pdal::PipelineKernel::isStagePrefix(), and pdal::Kernel::parseStageOption().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent) protected inherited
Definition at line 320 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), execute(), pdal::SortKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent, Options options) protected inherited
Definition at line 326 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeFilter (const std::string & driver) protected inherited
Definition at line 314 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver) protected inherited
Definition at line 301 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver, Options options) protected inherited
Definition at line 307 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver) protected inherited
Definition at line 333 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver, Options options) protected inherited
Definition at line 340 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
int pdal::Kernel::run (const StringList & cmdArgs, LogPtr & log) inherited
Definition at line 229 of file Kernel.cpp.
References pdal::Kernel::doExecution(), pdal::Kernel::doStartup(), pdal::Kernel::doSwitches(), setup::log, pdal::Kernel::m_log, pdal::Kernel::m_manager, pdal::Kernel::m_showHelp, pdal::Kernel::outputHelp(), pdal::Utils::printError(), and pdal::PipelineManager::setLog().
Referenced by App::execute().
void pdal::SplitKernel::validateSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 68 of file SplitKernel.cpp.
References m_capacity, m_inputFile, m_length, and m_outputFile.
Member Data Documentation
uint32_t pdal::SplitKernel::m_capacity private
Definition at line 60 of file SplitKernel.hpp.
Referenced by addSwitches(), execute(), and validateSwitches().
std::string pdal::Kernel::m_driverOverride protected inherited
Definition at line 105 of file Kernel.hpp.
Referenced by pdal::Kernel::addBasicSwitches(), pdal::MergeKernel::execute(), pdal::SortKernel::execute(), execute(), pdal::DiffKernel::execute(), pdal::DeltaKernel::loadSet(), pdal::InfoKernel::makePipeline(), and pdal::TIndexKernel::mergeFile().
std::string pdal::SplitKernel::m_inputFile private
Definition at line 58 of file SplitKernel.hpp.
Referenced by addSwitches(), execute(), and validateSwitches().
double pdal::SplitKernel::m_length private
Definition at line 61 of file SplitKernel.hpp.
Referenced by addSwitches(), execute(), and validateSwitches().
LogPtr pdal::Kernel::m_log protected inherited
Definition at line 103 of file Kernel.hpp.
Referenced by pdal::TIndexKernel::createFeature(), pdal::TIndexKernel::createFile(), pdal::TIndexKernel::createLayer(), pdal::InfoKernel::dumpPoints(), pdal::TranslateKernel::execute(), and pdal::Kernel::run().
PipelineManager pdal::Kernel::m_manager protected inherited
Definition at line 104 of file Kernel.hpp.
Referenced by pdal::Kernel::doSwitches(), pdal::InfoKernel::dump(), pdal::SmoothKernel::execute(), pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), pdal::TranslateKernel::execute(), pdal::TIndexKernel::getFileInfo(), pdal::TranslateKernel::makeArgPipeline(), pdal::Kernel::makeFilter(), pdal::TranslateKernel::makeJSONPipeline(), pdal::InfoKernel::makePipeline(), pdal::Kernel::makeReader(), pdal::Kernel::makeWriter(), pdal::InfoKernel::run(), pdal::Kernel::run(), and pdal::InfoKernel::setup().
std::string pdal::SplitKernel::m_outputFile private
Definition at line 59 of file SplitKernel.hpp.
Referenced by addSwitches(), execute(), and validateSwitches().
double pdal::SplitKernel::m_xOrigin private
Definition at line 62 of file SplitKernel.hpp.
Referenced by addSwitches(), and execute().
double pdal::SplitKernel::m_yOrigin private
Definition at line 63 of file SplitKernel.hpp.
Referenced by addSwitches(), and execute().
The documentation for this class was generated from the following files:
pdal/kernels/SplitKernel.hpp
pdal/kernels/SplitKernel.cpp