PDAL: App Class Reference
App Class Reference
Public Member Functions
App ()
int execute (StringList &cmdArgs, LogPtr &log)
Private Member Functions
void outputVersion ()
void outputHelp (const ProgramArgs &args)
void outputDrivers ()
void outputCommands ()
void outputOptions ()
void outputOptions (const std::string &stageName, std::ostream &strm)
void addArgs (ProgramArgs &args)
std::string findKernel ()
Private Attributes
std::ostream & m_out
std::string m_command
bool m_debug
LogLevel m_logLevel
bool m_showDrivers
bool m_help
bool m_showCommands
bool m_showVersion
std::string m_showOptions
bool m_showJSON
std::string m_log
Detailed Description
Definition at line 60 of file pdal.cpp.
Constructor & Destructor Documentation
App::App ()
Definition at line 63 of file pdal.cpp.
References setup::log, and pdal::nitfwrap::anonymous_namespace{NitfWrap.cpp}::outputHelp().
Member Function Documentation
void App::addArgs (ProgramArgs & args) private
Definition at line 271 of file pdal.cpp.
References pdal::ProgramArgs::add(), pdal::None, pdal::Arg::setHidden(), and pdal::Arg::setPositional().
int App::execute (StringList & cmdArgs, LogPtr & log)
Definition at line 336 of file pdal.cpp.
References pdal::Utils::backtrace(), pdal::PluginManager::createObject(), pdal::Debug, pdal::Error, anonymous_namespace{pdal.cpp}::logPtr(), pdal::Dimension::name(), pdal::None, pdal::nitfwrap::anonymous_namespace{NitfWrap.cpp}::outputHelp(), pdal::ProgramArgs::parseSimple(), pdal::Utils::printError(), pdal::Kernel::run(), pdal::PluginManager::setLog(), pdal::Utils::tolower(), pdal::gdal::unregisterDrivers(), and pdal::arg_error::what().
Referenced by main().
std::string App::findKernel () private
Definition at line 307 of file pdal.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Dimension::name(), pdal::PluginManager::names(), PF_PluginType_Kernel, and pdal::Utils::split2().
void App::outputCommands () private
Definition at line 182 of file pdal.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Dimension::name(), pdal::PluginManager::names(), and PF_PluginType_Kernel.
void App::outputDrivers () private
Definition at line 122 of file pdal.cpp.
References pdal::PluginManager::description(), pdal::Dimension::description(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::PluginManager::link(), pdal::Dimension::name(), pdal::PluginManager::names(), PF_PluginType_Filter, PF_PluginType_Reader, PF_PluginType_Writer, pdal::Utils::screenWidth(), and pdal::Utils::wordWrap().
void App::outputHelp (const ProgramArgs & args) private
Definition at line 102 of file pdal.cpp.
References pdal::ProgramArgs::dump(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Dimension::name(), pdal::PluginManager::names(), and PF_PluginType_Kernel.
void App::outputOptions () private
Definition at line 235 of file pdal.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::PluginManager::names(), PF_PluginType_Filter, PF_PluginType_Reader, and PF_PluginType_Writer.
void App::outputOptions (const std::string & stageName, std::ostream & strm) private
Definition at line 192 of file pdal.cpp.
References pdal::Stage::addAllArgs(), pdal::StageFactory::createStage(), pdal::ProgramArgs::dump2(), pdal::ProgramArgs::dump3(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, headline(), and pdal::PluginManager::link().
void App::outputVersion () private
Definition at line 93 of file pdal.cpp.
References pdal::GetFullVersionString(), and headline().
Member Data Documentation
std::string App::m_command private
Definition at line 80 of file pdal.cpp.
bool App::m_debug private
Definition at line 81 of file pdal.cpp.
bool App::m_help private
Definition at line 84 of file pdal.cpp.
std::string App::m_log private
Definition at line 89 of file pdal.cpp.
LogLevel App::m_logLevel private
Definition at line 82 of file pdal.cpp.
std::ostream& App::m_out private
Definition at line 78 of file pdal.cpp.
bool App::m_showCommands private
Definition at line 85 of file pdal.cpp.
bool App::m_showDrivers private
Definition at line 83 of file pdal.cpp.
bool App::m_showJSON private
Definition at line 88 of file pdal.cpp.
std::string App::m_showOptions private
Definition at line 87 of file pdal.cpp.
bool App::m_showVersion private
Definition at line 86 of file pdal.cpp.
The documentation for this class was generated from the following file:
pdal/apps/pdal.cpp