PDAL: pdal::VArg< T > Class Template Reference
pdal::VArg< T > Class Template Reference
#include <ProgramArgs.hpp>
Public Types
enum PosType { PosType::None, PosType::Required, PosType::Optional }
Public Member Functions
VArg (const std::string &longname, const std::string &shortname, const std::string &description, std::vector< T > &variable, std::vector< T > def)
VArg (const std::string &longname, const std::string &shortname, const std::string &description, std::vector< T > &variable)
virtual void setValue (const std::string &s)
virtual void reset ()
virtual std::string defaultVal () const
virtual void assignPositional (ArgValList &vals)
virtual bool defaultProvided () const
Arg & setHidden (bool hidden=true)
virtual Arg & setPositional ()
virtual Arg & setOptionalPositional ()
virtual Arg & setErrorText (const std::string &error)
bool set () const
virtual bool needsValue () const
PosType positional () const
bool hidden () const
std::string description () const
std::string longname () const
std::string nameDescrip () const
std::string commandLine () const
Protected Attributes
bool m_defaultProvided
std::string m_longname
std::string m_shortname
std::string m_description
std::string m_rawVal
bool m_set
bool m_hidden
PosType m_positional
std::string m_error
Private Attributes
std::vector< T > & m_var
std::vector< T > m_defaultVal
Detailed Description
template<typename T>
class pdal::VArg< T >
Description of a generic list-based (vector) argument.
Note
Doesn't properly support list-based boolean values.
Definition at line 699 of file ProgramArgs.hpp.
Member Enumeration Documentation
enum pdal::Arg::PosType strong inherited
Positional type. Either None, Optional or Required.
Enumerator
None
Not positional.
Required
Required positional.
Optional
Optional positional.
Definition at line 137 of file ProgramArgs.hpp.
Constructor & Destructor Documentation
template<typename T> pdal::VArg< T >::VArg (const std::string & longname, const std::string & shortname, const std::string & description, std::vector< T > & variable, std::vector< T > def)
Constructor for arguments with default value.
Parameters
longname Name of argument specified on command line with "--" prefix.
shortname Optional name of argument specified on command line with "-" prefix.
description Argument description.
variable Variable to which the argument value(s) should be bound.
def Default value.
Definition at line 713 of file ProgramArgs.hpp.
template<typename T> pdal::VArg< T >::VArg (const std::string & longname, const std::string & shortname, const std::string & description, std::vector< T > & variable)
Constructor for arguments without default value.
Parameters
longname Name of argument specified on command line with "--" prefix.
shortname Optional name of argument specified on command line with "-" prefix.
description Argument description.
variable Variable to which the argument value(s) should be bound.
Definition at line 733 of file ProgramArgs.hpp.
Member Function Documentation
virtual void pdal::BaseVArg::assignPositional (ArgValList & vals) virtual inherited
Set the argument's value from the command-line args.
List-based arguments consume ALL positional arguments until one is found that can't be converted to the type of the bound variable.
Note
Not intended to be called from user code.
Parameters
vals The list of command-line args.
Reimplemented from pdal::Arg.
Definition at line 653 of file ProgramArgs.hpp.
References pdal::arg_error::arg_error(), and pdal::None.
std::string pdal::Arg::commandLine () const inherited
Returns text indicating the name of the option suitable for displaying in "usage" text.
Note
Not intended to be called from user code.
Definition at line 319 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::commandLine().
virtual bool pdal::BaseVArg::defaultProvided () const virtual inherited
Return whether a default value was provided for the argument.
Returns
Whether a default was provided.
Reimplemented from pdal::Arg.
Definition at line 687 of file ProgramArgs.hpp.
template<typename T> virtual std::string pdal::VArg< T >::defaultVal () const virtual
Return a string representation of an Arg's default value, or an empty string if none exists.
Returns
Default value as a string.
Reimplemented from pdal::Arg.
Definition at line 793 of file ProgramArgs.hpp.
References pdal::Utils::toString().
std::string pdal::Arg::description () const inherited
Returns the description of the argument.
Note
Not intended to be called from user code.
Returns
Argument description.
Definition at line 290 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::dump(), pdal::ProgramArgs::dump2(), and pdal::ProgramArgs::dump3().
bool pdal::Arg::hidden () const inherited
Returns whether the argument is hidden or not.
Note
Not intended to be called from user code.
Definition at line 282 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::commandLine(), and pdal::ProgramArgs::dump().
std::string pdal::Arg::longname () const inherited
Returns the longname of the argument.
Note
Not intended to be called from user code.
Returns
Argument long name.
Definition at line 298 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::dump2(), pdal::ProgramArgs::dump3(), and pdal::ProgramArgs::validate().
std::string pdal::Arg::nameDescrip () const inherited
Returns text indicating the longname and shortname of the option suitable for displaying in help information.
Note
Not intended to be called from user code.
Definition at line 306 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::dump().
virtual bool pdal::Arg::needsValue () const virtual inherited
Return whether an option needs a value to be valid. Generally true for all options not bound to boolean values.
Note
Not intended to be called from user code.
Reimplemented in pdal::TArg< bool >.
Definition at line 239 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::parseLongArg().
PosType pdal::Arg::positional () const inherited
Returns the positional type of the argument.
Note
Not intended to be called from user code.
Definition at line 275 of file ProgramArgs.hpp.
Referenced by pdal::ProgramArgs::validate().
template<typename T> virtual void pdal::VArg< T >::reset () virtual
Reset the argument's state.
Set the internal state of the argument and it's referenced variable as if no command-line parsing had occurred.
Note
For testing. Not intended to be called from user code.
Implements pdal::Arg.
Definition at line 780 of file ProgramArgs.hpp.
bool pdal::Arg::set () const inherited
Return whether the argument was set during command-line parsing.
Definition at line 215 of file ProgramArgs.hpp.
Referenced by pdal::NormalFilter::filter(), pdal::DividerFilter::initialize(), pdal::BpfWriter::initialize(), pdal::GDALWriter::prepared(), pdal::NormalFilter::prepared(), and pdal::ProgramArgs::set().
virtual Arg& pdal::Arg::setErrorText (const std::string & error) virtual inherited
Provide error text for the argument to override the default.
Parameters
error Error text.
Definition at line 207 of file ProgramArgs.hpp.
References pdal::arg_error::m_error.
Referenced by pdal::CropFilter::addArgs().
Arg& pdal::Arg::setHidden (bool hidden = true) inherited
Definition at line 169 of file ProgramArgs.hpp.
Referenced by App::addArgs(), pdal::PipelineKernel::addSwitches(), and pdal::InfoKernel::addSwitches().
virtual Arg& pdal::Arg::setOptionalPositional () virtual inherited
Reimplemented in pdal::TArg< bool >.
Definition at line 197 of file ProgramArgs.hpp.
Referenced by pdal::PipelineKernel::addSwitches(), pdal::InfoKernel::addSwitches(), pdal::nitfwrap::NitfWrap::parseArgs(), and TEST().
virtual Arg& pdal::Arg::setPositional () virtual inherited
Indicate that the argument is positional.
Positional arguments may be specified on the command line without any argument name. Such arguments are required to be specified either with the argument name as a normal option or positionally. Missing positional arguments will raise an exception when the command line is parsed
Reimplemented in pdal::TArg< bool >.
Definition at line 183 of file ProgramArgs.hpp.
Referenced by pdal::MyWriter::addArgs(), pdal::OciWriter::addArgs(), pdal::GeoWaveWriter::addArgs(), pdal::PgWriter::addArgs(), pdal::SQLiteWriter::addArgs(), pdal::MatlabWriter::addArgs(), pdal::OciReader::addArgs(), pdal::SbetWriter::addArgs(), pdal::GDALWriter::addArgs(), pdal::GeoWaveReader::addArgs(), pdal::ReprojectionFilter::addArgs(), pdal::PcdWriter::addArgs(), pdal::PlyWriter::addArgs(), pdal::RangeFilter::addArgs(), pdal::OGRWriter::addArgs(), pdal::TransformationFilter::addArgs(), pdal::FerryFilter::addArgs(), App::addArgs(), pdal::OverlayFilter::addArgs(), pdal::BpfWriter::addArgs(), pdal::MbReader::addArgs(), pdal::PgReader::addArgs(), pdal::LasWriter::addArgs(), pdal::GreedyProjection::addArgs(), pdal::MyKernel::addSwitches(), pdal::PCLKernel::addSwitches(), pdal::SmoothKernel::addSwitches(), pdal::SplitKernel::addSwitches(), pdal::MergeKernel::addSwitches(), pdal::SortKernel::addSwitches(), pdal::RandomKernel::addSwitches(), pdal::HausdorffKernel::addSwitches(), pdal::DiffKernel::addSwitches(), pdal::GroundKernel::addSwitches(), pdal::DensityKernel::addSwitches(), pdal::DeltaKernel::addSwitches(), pdal::TIndexKernel::addSwitches(), pdal::nitfwrap::NitfWrap::parseArgs(), pdal::DimBuilder::parseArgs(), and TEST().
template<typename T> virtual void pdal::VArg< T >::setValue (const std::string & s) virtual
Set a an argument's value from a string.
Throws an arg_error exception if s can't be converted to the argument's type.
Note
Not intended to be called from user code.
Parameters
s Value to set.
Implements pdal::Arg.
Definition at line 750 of file ProgramArgs.hpp.
References pdal::Utils::fromString(), and pdal::arg_error::m_error.
Member Data Documentation
bool pdal::BaseVArg::m_defaultProvided protected inherited
Definition at line 691 of file ProgramArgs.hpp.
template<typename T> std::vector<T> pdal::VArg< T >::m_defaultVal private
Definition at line 808 of file ProgramArgs.hpp.
std::string pdal::Arg::m_description protected inherited
Definition at line 332 of file ProgramArgs.hpp.
std::string pdal::Arg::m_error protected inherited
Definition at line 337 of file ProgramArgs.hpp.
bool pdal::Arg::m_hidden protected inherited
Definition at line 335 of file ProgramArgs.hpp.
std::string pdal::Arg::m_longname protected inherited
Definition at line 330 of file ProgramArgs.hpp.
PosType pdal::Arg::m_positional protected inherited
Definition at line 336 of file ProgramArgs.hpp.
std::string pdal::Arg::m_rawVal protected inherited
Definition at line 333 of file ProgramArgs.hpp.
bool pdal::Arg::m_set protected inherited
Definition at line 334 of file ProgramArgs.hpp.
std::string pdal::Arg::m_shortname protected inherited
Definition at line 331 of file ProgramArgs.hpp.
template<typename T> std::vector<T>& pdal::VArg< T >::m_var private
Definition at line 807 of file ProgramArgs.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/util/ProgramArgs.hpp