PDAL: pdal::filter::Point Class Reference
pdal::filter::Point Class Reference
#include <Point.hpp>
Public Member Functions
Point ()
Point (const std::string &wkt_or_json, SpatialReference ref)
bool is3d () const
bool empty () const
void clear ()
virtual void update (const std::string &wkt_or_json)
OGRGeometryH getOGRHandle ()
void setSpatialReference (const SpatialReference &ref)
const SpatialReference & getSpatialReference () const
Geometry transform (const SpatialReference &ref) const
bool equals (const Geometry &other, double tolerance=0.0001) const
bool operator== (const Geometry &other) const
bool operator!= (const Geometry &other) const
bool operator< (const Geometry &other) const
virtual bool valid () const
virtual std::string validReason () const
std::string wkt (double precision=8, bool bOutputZ=false) const
std::string json (double precision=8) const
BOX3D bounds () const
operator bool () const
Public Attributes
double x
double y
double z
Protected Member Functions
void prepare ()
Protected Attributes
GEOSGeomPtr m_geom
const GEOSPreparedGeometry * m_prepGeom
SpatialReference m_srs
geos::ErrorHandler & m_geoserr
Detailed Description
Definition at line 45 of file Point.hpp.
Constructor & Destructor Documentation
Point::Point ()
Definition at line 51 of file Point.cpp.
Point::Point (const std::string & wkt_or_json, SpatialReference ref)
Definition at line 59 of file Point.cpp.
Member Function Documentation
BOX3D pdal::Geometry::bounds () const inherited
Definition at line 213 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::BOX3D::grow(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, and z.
Referenced by pdal::StatsFilter::extractMetadata(), pdal::TEST(), and TEST().
void Point::clear ()
Definition at line 100 of file Point.cpp.
References pdal::filter::anonymous_namespace{Point.cpp}::LOWEST, x, y, and z.
bool Point::empty () const
Definition at line 106 of file Point.cpp.
References pdal::filter::anonymous_namespace{Point.cpp}::LOWEST, x, y, and z.
bool pdal::Geometry::equals (const Geometry & other, double tolerance = 0.0001) const inherited
Definition at line 249 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
Referenced by pdal::Geometry::operator!=(), and pdal::Geometry::operator==().
OGRGeometryH pdal::Geometry::getOGRHandle () inherited
const SpatialReference& pdal::Geometry::getSpatialReference () const inherited
Definition at line 106 of file Geometry.hpp.
References pdal::operator!=(), and pdal::operator==().
bool Point::is3d () const
Definition at line 112 of file Point.cpp.
References z.
Referenced by pdal::CropFilter::crop().
std::string pdal::Geometry::json (double precision = 8) const inherited
Definition at line 306 of file Geometry.cpp.
References pdal::SpatialReference::getWKT(), pdal::Geometry::m_srs, and pdal::Geometry::wkt().
Referenced by pdal::StatsFilter::extractMetadata(), and pdal::TEST().
pdal::Geometry::operator bool () const inherited
Definition at line 126 of file Geometry.hpp.
bool pdal::Geometry::operator!= (const Geometry & other) const inherited
Definition at line 262 of file Geometry.cpp.
References pdal::Geometry::equals().
bool pdal::Geometry::operator< (const Geometry & other) const inherited
Definition at line 114 of file Geometry.hpp.
References pdal::Geometry::wkt().
bool pdal::Geometry::operator== (const Geometry & other) const inherited
Definition at line 256 of file Geometry.cpp.
References pdal::Geometry::equals().
void pdal::Geometry::prepare () protected inherited
Definition at line 112 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, and pdal::Geometry::m_prepGeom.
Referenced by pdal::Geometry::Geometry(), pdal::Polygon::initializeFromBounds(), pdal::Polygon::operator=(), pdal::Geometry::operator=(), pdal::Polygon::Polygon(), and pdal::Geometry::update().
void pdal::Geometry::setSpatialReference (const SpatialReference & ref) inherited
Definition at line 103 of file Geometry.hpp.
Referenced by TEST().
Geometry pdal::Geometry::transform (const SpatialReference & ref) const inherited
Definition at line 194 of file Geometry.cpp.
References pdal::SpatialReference::empty(), pdal::Geometry::Geometry(), pdal::SpatialReference::getWKT(), pdal::Geometry::m_srs, and pdal::Geometry::wkt().
void Point::update (const std::string & wkt_or_json) virtual
Reimplemented from pdal::Geometry.
Definition at line 64 of file Point.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, pdal::Geometry::update(), x, y, and z.
bool pdal::Geometry::valid () const virtual inherited
Definition at line 268 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
Referenced by pdal::TEST().
std::string pdal::Geometry::validReason () const virtual inherited
Definition at line 278 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
std::string pdal::Geometry::wkt (double precision = 8, bool bOutputZ = false) const inherited
Definition at line 289 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
Referenced by pdal::Geometry::json(), pdal::Geometry::operator<(), pdal::operator<<(), pdal::TEST(), pdal::Polygon::transform(), and pdal::Geometry::transform().
Member Data Documentation
GEOSGeomPtr pdal::Geometry::m_geom protected inherited
Definition at line 131 of file Geometry.hpp.
Referenced by pdal::Polygon::area(), pdal::Geometry::bounds(), pdal::Polygon::contains(), pdal::Polygon::covers(), pdal::Polygon::crosses(), pdal::Geometry::equals(), pdal::Geometry::Geometry(), pdal::Polygon::initializeFromBounds(), pdal::Polygon::operator=(), pdal::Geometry::operator=(), pdal::Polygon::overlaps(), pdal::Polygon::Polygon(), pdal::Geometry::prepare(), pdal::Polygon::simplify(), pdal::Polygon::touches(), update(), pdal::Geometry::update(), pdal::Geometry::valid(), pdal::Geometry::validReason(), pdal::Polygon::within(), pdal::Geometry::wkt(), and pdal::Geometry::~Geometry().
geos::ErrorHandler& pdal::Geometry::m_geoserr protected inherited
Definition at line 135 of file Geometry.hpp.
Referenced by pdal::Polygon::area(), pdal::Geometry::bounds(), pdal::Polygon::contains(), pdal::Polygon::covers(), pdal::Polygon::crosses(), pdal::Geometry::equals(), pdal::Geometry::Geometry(), pdal::Polygon::initializeFromBounds(), pdal::Polygon::operator=(), pdal::Geometry::operator=(), pdal::Polygon::overlaps(), pdal::Polygon::Polygon(), pdal::Geometry::prepare(), pdal::Polygon::simplify(), pdal::Polygon::touches(), update(), pdal::Geometry::update(), pdal::Geometry::valid(), pdal::Geometry::validReason(), pdal::Polygon::within(), pdal::Geometry::wkt(), and pdal::Geometry::~Geometry().
const GEOSPreparedGeometry* pdal::Geometry::m_prepGeom protected inherited
Definition at line 132 of file Geometry.hpp.
Referenced by pdal::Polygon::covers(), pdal::Geometry::Geometry(), pdal::Geometry::prepare(), and pdal::Geometry::~Geometry().
SpatialReference pdal::Geometry::m_srs protected inherited
Definition at line 134 of file Geometry.hpp.
Referenced by pdal::Geometry::json(), pdal::Polygon::operator=(), pdal::Geometry::operator=(), pdal::Polygon::simplify(), pdal::Polygon::transform(), and pdal::Geometry::transform().
double pdal::filter::Point::x
Definition at line 57 of file Point.hpp.
Referenced by clear(), pdal::CropFilter::crop(), empty(), pdal::NormalFilter::filter(), and update().
double pdal::filter::Point::y
Definition at line 58 of file Point.hpp.
Referenced by clear(), pdal::CropFilter::crop(), empty(), pdal::NormalFilter::filter(), and update().
double pdal::filter::Point::z
Definition at line 59 of file Point.hpp.
Referenced by clear(), pdal::CropFilter::crop(), empty(), pdal::NormalFilter::filter(), is3d(), and update().
The documentation for this class was generated from the following files:
pdal/filters/private/Point.hpp
pdal/filters/private/Point.cpp