PDAL: pdal::PointLayout Class Reference
pdal::PointLayout Class Reference
#include <PointLayout.hpp>
Public Member Functions
PDAL_DLL PointLayout ()
virtual PDAL_DLL ~PointLayout ()
PDAL_DLL void finalize ()
PDAL_DLL bool finalized () const
PDAL_DLL void registerDims (std::vector< Dimension::Id > ids)
PDAL_DLL void registerDims (Dimension::Id *id)
PDAL_DLL void registerDim (Dimension::Id id)
PDAL_DLL void registerDim (Dimension::Id id, Dimension::Type type)
PDAL_DLL Dimension::Id assignDim (const std::string &name, Dimension::Type type)
PDAL_DLL Dimension::Id registerOrAssignDim (const std::string name, Dimension::Type type)
PDAL_DLL DimTypeList dimTypes () const
PDAL_DLL DimType findDimType (const std::string &name) const
PDAL_DLL Dimension::Id findDim (const std::string &name) const
PDAL_DLL Dimension::Id findProprietaryDim (const std::string &name) const
PDAL_DLL std::string dimName (Dimension::Id id) const
PDAL_DLL bool hasDim (Dimension::Id id) const
PDAL_DLL const Dimension::IdList & dims () const
PDAL_DLL Dimension::Type dimType (Dimension::Id id) const
PDAL_DLL size_t dimSize (Dimension::Id id) const
PDAL_DLL size_t dimOffset (Dimension::Id id) const
PDAL_DLL size_t pointSize () const
PDAL_DLL const Dimension::Detail * dimDetail (Dimension::Id id) const
PDAL_DLL MetadataNode toMetadata () const
Protected Attributes
std::vector< Dimension::Detail > m_detail
Dimension::IdList m_used
std::map< std::string, Dimension::Id > m_propIds
int m_nextFree
std::size_t m_pointSize
bool m_finalized
Private Member Functions
virtual PDAL_DLL bool update (Dimension::Detail dd, const std::string &name)
Dimension::Type resolveType (Dimension::Type t1, Dimension::Type t2)
Detailed Description
Definition at line 49 of file PointLayout.hpp.
Constructor & Destructor Documentation
pdal::PointLayout::PointLayout ()
Default constructor.
Definition at line 41 of file PointLayout.cpp.
References m_detail.
virtual PDAL_DLL pdal::PointLayout::~PointLayout () virtual
Definition at line 56 of file PointLayout.hpp.
References finalize(), and PDAL_DLL.
Member Function Documentation
Dimension::Id pdal::PointLayout::assignDim (const std::string & name, Dimension::Type type)
Assign a non-existing (proprietary) dimension with the given name and type. No check is made to see if the dimension exists as a standard (non-propietary) dimension. If the dimension has already been assigned as a proprietary dimension, update the type but use the existing Id. If the dimension has already been assigned with a larger type, this does nothing.
Parameters
name Name of the proprietary dimension to add.
type Minimum type to assign to the dimension.
Returns
ID of the new or existing dimension, or Unknown on failure.
Definition at line 92 of file PointLayout.cpp.
References pdal::Dimension::COUNT, pdal::Dimension::id(), m_detail, m_nextFree, m_propIds, pdal::Dimension::name(), resolveType(), pdal::Utils::toNative(), pdal::Dimension::Unknown, and update().
Referenced by finalized(), registerOrAssignDim(), and TEST().
const Dimension::Detail * pdal::PointLayout::dimDetail (Dimension::Id id) const
Get a pointer to a dimension's detail information.
Parameters
id ID of the dimension.
Returns
A pointer a dimension's detail.
Definition at line 215 of file PointLayout.cpp.
References m_detail, and pdal::Utils::toNative().
Referenced by pdal::MatlabReader::addDimensions(), dimOffset(), dimSize(), dimType(), pdal::PointView::dump(), finalized(), pdal::SimplePointTable::getFieldInternal(), and pdal::SimplePointTable::setFieldInternal().
std::string pdal::PointLayout::dimName (Dimension::Id id) const
Get the name of a dimension give its ID. A dimension may have more than one name. The first one associated with the ID is returned.
Parameters
id ID of the dimension.
Returns
A name associated with the dimension, or a NULL string.
Definition at line 166 of file PointLayout.cpp.
References m_propIds, and pdal::Dimension::name().
Referenced by pdal::MatlabReader::addDimensions(), pdal::DeltaKernel::execute(), finalized(), pdal::MrsidReader::LayoutToPointInfo(), pdal::BpfWriter::loadBpfDimensions(), pdal::PlyWriter::prepared(), pdal::DbWriter::prepared(), pdal::LasWriter::prepared(), pdal::MrsidReader::read(), TEST(), toMetadata(), pdal::TextWriter::writeCSVHeader(), and pdal::XMLSchema::XMLSchema().
size_t pdal::PointLayout::dimOffset (Dimension::Id id) const
Get the offset of the dimension in the layout.
Parameters
id ID of the dimension.
Returns
Offset of the dimension in bytes.
Definition at line 203 of file PointLayout.cpp.
References dimDetail(), and pdal::Dimension::Detail::offset().
Referenced by finalized().
const Dimension::IdList & pdal::PointLayout::dims () const
Get a reference to vector of the IDs of currently used dimensions.
Returns
Vector of IDs of dimensions that are part of the layout.
Definition at line 185 of file PointLayout.cpp.
References m_used.
Referenced by pdal::MatlabReader::addDimensions(), pdal::plang::Invocation::begin(), dimTypes(), pdal::PointView::dump(), pdal::plang::Invocation::end(), pdal::DiffKernel::execute(), pdal::DeltaKernel::execute(), finalized(), pdal::MrsidReader::LayoutToPointInfo(), pdal::BpfWriter::loadBpfDimensions(), pdal::MatlabWriter::prepared(), pdal::PlyWriter::prepared(), pdal::GeoWaveWriter::ready(), pdal::TextWriter::ready(), TEST(), TEST_F(), toMetadata(), and pdal::PointView::toMetadata().
size_t pdal::PointLayout::dimSize (Dimension::Id id) const
Get the current size in bytes of the dimension.
Parameters
id ID of the dimension.
Returns
Size of the dimension in bytes.
Definition at line 197 of file PointLayout.cpp.
References dimDetail(), and pdal::Dimension::Detail::size().
Referenced by finalized(), Java_io_pdal_PointLayout_dimSize(), pdal::MrsidReader::LayoutToPointInfo(), and toMetadata().
Dimension::Type pdal::PointLayout::dimType (Dimension::Id id) const
Get the type of a dimension.
Parameters
id ID of the dimension.
Returns
Type of the dimension.
Definition at line 191 of file PointLayout.cpp.
References dimDetail(), and pdal::Dimension::Detail::type().
Referenced by dimTypes(), finalized(), findDim(), findDimType(), pdal::MrsidReader::LayoutToPointInfo(), pdal::MrsidReader::read(), toMetadata(), pdal::PlyWriter::writeHeader(), and pdal::PlyWriter::writePoint().
DimTypeList pdal::PointLayout::dimTypes () const
Get a list of DimType objects that define the layout.
Returns
A list of DimType objects.
Definition at line 130 of file PointLayout.cpp.
References dims(), and dimType().
Referenced by finalized(), Java_io_pdal_PointLayout_dimTypes(), pdal::DbWriter::prepared(), pdal::LasWriter::prepared(), and pdal::XMLSchema::XMLSchema().
void pdal::PointLayout::finalize ()
Mark a layout as finalized. Dimensions can't be added to a finalized PointLayout.
Definition at line 58 of file PointLayout.cpp.
References m_finalized.
Referenced by pdal::mlang::Script::getStructLayout(), and ~PointLayout().
PDAL_DLL bool pdal::PointLayout::finalized () const
Determine if the PointLayout is finalized.
Returns
Whether the PointLayout is finalized.
Definition at line 69 of file PointLayout.hpp.
References assignDim(), dimDetail(), dimName(), dimOffset(), dims(), dimSize(), dimType(), dimTypes(), findDim(), findDimType(), findProprietaryDim(), hasDim(), m_finalized, pdal::Dimension::name(), PDAL_DLL, pointSize(), registerDim(), registerDims(), registerOrAssignDim(), resolveType(), toMetadata(), pdal::Dimension::type(), and update().
Dimension::Id pdal::PointLayout::findDim (const std::string & name) const
Get the ID of a dimension (standard or proprietary) given its name.
Parameters
name Name of the dimension.
Returns
ID of the dimension or Unknown.
Definition at line 148 of file PointLayout.cpp.
References dimType(), findProprietaryDim(), pdal::Dimension::id(), and pdal::Dimension::None.
Referenced by GDALReaderTypeTest::compare(), finalized(), findDimType(), pdal::BpfWriter::loadBpfDimensions(), pdal::AssignFilter::prepared(), pdal::MatlabWriter::prepared(), pdal::GDALWriter::prepared(), pdal::PlyWriter::prepared(), pdal::RangeFilter::prepared(), pdal::FerryFilter::prepared(), pdal::SMRFilter::prepared(), pdal::SortFilter::prepared(), pdal::OverlayFilter::prepared(), pdal::LasWriter::prepared(), pdal::Ilvis2Reader::readPoint(), pdal::MyWriter::ready(), pdal::TextWriter::ready(), TEST(), TEST_F(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), and pdal::DbReader::updateSchema().
DimType pdal::PointLayout::findDimType (const std::string & name) const
Get a DimType structure for a named dimension.
Parameters
name Name of the dimension
Returns
A DimType associated with the named dimension. Returns a DimType with an Unknown ID if the dimension isn't part of the layout.
Definition at line 141 of file PointLayout.cpp.
References dimType(), and findDim().
Referenced by finalized(), and pdal::DbWriter::prepared().
Dimension::Id pdal::PointLayout::findProprietaryDim (const std::string & name) const
Get the ID of a proprietary dimension given its name.
Parameters
name Name of the dimension.
Returns
ID of the dimension or Unknown.
Definition at line 158 of file PointLayout.cpp.
References m_propIds, and pdal::Dimension::Unknown.
Referenced by finalized(), findDim(), and pdal::MyReader::read().
bool pdal::PointLayout::hasDim (Dimension::Id id) const
Determine if the PointLayout uses the dimension with the given ID.
Parameters
id ID of the dimension to check.
Returns
true if the layout uses the dimension, false otherwise.
Definition at line 179 of file PointLayout.cpp.
References m_detail, pdal::Dimension::None, and pdal::Utils::toNative().
Referenced by pdal::PoissonFilter::addDimensions(), and finalized().
size_t pdal::PointLayout::pointSize () const
Get number of bytes that make up a point. Returns the sum of the dimSize for all dimensions in the layout.
Returns
Size of a point in bytes.
Definition at line 209 of file PointLayout.cpp.
References m_pointSize.
Referenced by finalized(), and Java_io_pdal_PointLayout_pointSize().
void pdal::PointLayout::registerDim (Dimension::Id id)
Register use of a standard dimension (declare that a point will contain data for this dimension). Use the default type for the dimension.
Parameters
id ID of dimension to be registered.
Definition at line 78 of file PointLayout.cpp.
References pdal::Dimension::defaultType().
Referenced by pdal::MyReader::addDimensions(), pdal::MyFilter::addDimensions(), pdal::GeoWaveReader::addDimensions(), pdal::SampleFilter::addDimensions(), pdal::HAGFilter::addDimensions(), pdal::OSGReader::addDimensions(), pdal::ELMFilter::addDimensions(), pdal::PMFFilter::addDimensions(), pdal::GDALReader::addDimensions(), pdal::PtsReader::addDimensions(), pdal::OutlierFilter::addDimensions(), pdal::TIndexReader::addDimensions(), pdal::SMRFilter::addDimensions(), pdal::MongusFilter::addDimensions(), pdal::QfitReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::Ilvis2Reader::addDimensions(), pdal::TerrasolidReader::addDimensions(), pdal::PlyReader::addDimensions(), pdal::LasReader::addDimensions(), pdal::FauxReader::addDimensions(), anonymous_namespace{SortFilterTest.cpp}::doSort(), finalized(), pdal::DbReader::loadSchema(), main(), makeTestView(), registerDims(), registerOrAssignDim(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), and pdal::MongusFilter::writeControl().
void pdal::PointLayout::registerDim (Dimension::Id id, Dimension::Type type)
Register use of a standard dimension (declare that a point will contain data for this dimension) if it hasn't already been registered with a "larger" type. It the dimension already exists with a larger type, this does nothing.
Parameters
id ID of dimension to be registered.
type Minimum type to assign to the dimension.
Definition at line 84 of file PointLayout.cpp.
References m_detail, pdal::Dimension::name(), resolveType(), pdal::Dimension::Detail::setType(), pdal::Utils::toNative(), pdal::Dimension::Detail::type(), and update().
void pdal::PointLayout::registerDims (std::vector< Dimension::Id > ids)
Register a vector of dimensions.
Parameters
ids Vector of IDs to register.
Definition at line 64 of file PointLayout.cpp.
References registerDim().
Referenced by pdal::PcdReader::addDimensions(), pdal::GeoWaveReader::addDimensions(), pdal::PoissonFilter::addDimensions(), pdal::SbetReader::addDimensions(), pdal::IcebridgeReader::addDimensions(), pdal::OptechReader::addDimensions(), pdal::NormalFilter::addDimensions(), pdal::MbReader::addDimensions(), pdal::ColorinterpFilter::addDimensions(), pdal::RxpReader::addDimensions(), pdal::FauxReader::addDimensions(), pdal::GreedyProjection::addDimensions(), and finalized().
void pdal::PointLayout::registerDims (Dimension::Id * id)
Register a list of dimensions.
Parameters
id Pointer to list of IDs to register. The last ID in the list must have the value Unknown.
Definition at line 71 of file PointLayout.cpp.
References registerDim(), and pdal::Dimension::Unknown.
Dimension::Id pdal::PointLayout::registerOrAssignDim (const std::string name, Dimension::Type type)
Register a dimension if one already exists with the given name using the provided type. If the dimension doesn't already exist, create it.
Parameters
name Name of the dimension to register or assign.
type Requested type of the dimension. Dimension will at least accomodate values of this type.
Returns
ID of dimension registered or assigned.
Definition at line 117 of file PointLayout.cpp.
References assignDim(), pdal::Dimension::id(), registerDim(), and pdal::Dimension::Unknown.
Referenced by pdal::MyReader::addDimensions(), pdal::MyFilter::addDimensions(), pdal::GreyhoundReader::addDimensions(), pdal::MatlabFilter::addDimensions(), pdal::ComputeRangeFilter::addDimensions(), pdal::ClusterFilter::addDimensions(), pdal::KDistanceFilter::addDimensions(), pdal::LOFFilter::addDimensions(), pdal::RadialDensityFilter::addDimensions(), pdal::PythonFilter::addDimensions(), pdal::GDALReader::addDimensions(), pdal::EigenvaluesFilter::addDimensions(), pdal::EstimateRankFilter::addDimensions(), pdal::ApproximateCoplanarFilter::addDimensions(), pdal::FerryFilter::addDimensions(), pdal::MrsidReader::addDimensions(), pdal::TextReader::addDimensions(), pdal::ColorizationFilter::addDimensions(), pdal::BpfReader::addDimensions(), pdal::PlyReader::addDimensions(), pdal::LasReader::addDimensions(), finalized(), pdal::mlang::Script::getStructLayout(), pdal::DbReader::loadSchema(), and TEST().
Dimension::Type pdal::PointLayout::resolveType (Dimension::Type t1, Dimension::Type t2) private
Definition at line 286 of file PointLayout.cpp.
References pdal::Dimension::base(), pdal::Dimension::None, and pdal::Dimension::size().
Referenced by assignDim(), finalized(), and registerDim().
MetadataNode pdal::PointLayout::toMetadata () const
Definition at line 323 of file PointLayout.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), pdal::Dimension::base(), dimName(), dims(), dimSize(), dimType(), and pdal::Dimension::toName().
Referenced by pdal::plang::Invocation::begin(), pdal::InfoKernel::dump(), finalized(), pdal::PipelineExecutor::getSchema(), and pdal::BasePointTable::toMetadata().
bool pdal::PointLayout::update (Dimension::Detail dd, const std::string & name) private virtual
Definition at line 222 of file PointLayout.cpp.
References pdal::Utils::contains(), pdal::Dimension::Detail::id(), m_detail, m_finalized, m_pointSize, m_used, pdal::Dimension::Detail::size(), and pdal::Utils::toNative().
Referenced by assignDim(), finalized(), and registerDim().
Member Data Documentation
std::vector<Dimension::Detail> pdal::PointLayout::m_detail protected
Definition at line 239 of file PointLayout.hpp.
Referenced by assignDim(), dimDetail(), hasDim(), PointLayout(), registerDim(), and update().
bool pdal::PointLayout::m_finalized protected
Definition at line 244 of file PointLayout.hpp.
Referenced by finalize(), finalized(), and update().
int pdal::PointLayout::m_nextFree protected
Definition at line 242 of file PointLayout.hpp.
Referenced by assignDim().
std::size_t pdal::PointLayout::m_pointSize protected
Definition at line 243 of file PointLayout.hpp.
Referenced by pointSize(), and update().
std::map<std::string, Dimension::Id> pdal::PointLayout::m_propIds protected
Definition at line 241 of file PointLayout.hpp.
Referenced by assignDim(), dimName(), and findProprietaryDim().
Dimension::IdList pdal::PointLayout::m_used protected
Definition at line 240 of file PointLayout.hpp.
Referenced by dims(), and update().
The documentation for this class was generated from the following files:
pdal/pdal/PointLayout.hpp
pdal/pdal/PointLayout.cpp