PDAL: pdal::gdal::Raster Class Reference
pdal::gdal::Raster Class Reference
#include <GDALUtils.hpp>
Public Member Functions
Raster (const std::string &filename, const std::string &drivername="")
Raster (const std::string &filename, const std::string &drivername, const SpatialReference &srs, const std::array< double, 6 > pixelToPos)
~Raster ()
GDALError open ()
GDALError open (int width, int height, int numBands, Dimension::Type type, double noData, StringList options=StringList())
void close ()
template<typename T >
GDALError readBand (std::vector< T > &points, int nBand)
template<typename SOURCE_ITER >
GDALError writeBand (SOURCE_ITER si, ITER_VAL< SOURCE_ITER > srcNoData, int nBand, const std::string &name="")
GDALError read (double x, double y, std::vector< double > &data)
std::vector< pdal::Dimension::Type > getPDALDimensionTypes () const
void pixelToCoord (int column, int row, std::array< double, 2 > &output) const
SpatialReference getSpatialRef () const
std::string errorMsg () const
int bandCount () const
int width () const
int height () const
std::string const & filename ()
Private Member Functions
GDALError validateType (Dimension::Type &type, GDALDriver *driver)
bool getPixelAndLinePosition (double x, double y, int32_t &pixel, int32_t &line)
GDALError computePDALDimensionTypes ()
Private Attributes
std::string m_filename
int m_width
int m_height
int m_numBands
std::string m_drivername
std::array< double, 6 > m_forwardTransform
std::array< double, 6 > m_inverseTransform
SpatialReference m_srs
GDALDataset * m_ds
Dimension::Type m_bandType
double m_dstNoData
std::string m_errorMsg
std::vector< pdal::Dimension::Type > m_types
std::vector< std::array< double, 2 > > m_block_sizes
Detailed Description
Definition at line 516 of file GDALUtils.hpp.
Constructor & Destructor Documentation
pdal::gdal::Raster::Raster (const std::string & filename, const std::string & drivername = "")
Constructor.
Parameters
filename Filename of raster file.
drivername Optional name of driver to use to open raster file.
Definition at line 330 of file GDALUtils.cpp.
References m_forwardTransform, and m_inverseTransform.
pdal::gdal::Raster::Raster (const std::string & filename, const std::string & drivername, const SpatialReference & srs, const std::array< double, 6 > pixelToPos)
Constructor.
Parameters
filename Filename of raster file.
drivername Optional name of driver to use to open raster file.
srs SpatialReference of the raster.
pixelToPos Transformation matrix to convert raster positions to geolocations.
Definition at line 347 of file GDALUtils.cpp.
pdal::gdal::Raster::~Raster ()
Destructor. Closes an open raster.
Definition at line 677 of file GDALUtils.cpp.
References close().
Member Function Documentation
int pdal::gdal::Raster::bandCount () const
Get the number of bands in the raster.
Returns
The number of bands in the raster.
Definition at line 719 of file GDALUtils.hpp.
void pdal::gdal::Raster::close ()
Close the raster and deallocate the underlying dataset.
Definition at line 683 of file GDALUtils.cpp.
References m_ds, and m_types.
Referenced by ~Raster().
GDALError pdal::gdal::Raster::computePDALDimensionTypes () private
Definition at line 602 of file GDALUtils.cpp.
References pdal::gdal::InvalidBand, m_ds, m_errorMsg, m_filename, m_numBands, m_types, pdal::gdal::None, pdal::gdal::NotOpen, and pdal::gdal::anonymous_namespace{GDALUtils.cpp}::toPdalType().
Referenced by open().
std::string pdal::gdal::Raster::errorMsg () const
Get the most recent error message.
Definition at line 711 of file GDALUtils.hpp.
Referenced by pdal::GDALWriter::doneFile(), and pdal::eigen::writeMatrix().
std::string const& pdal::gdal::Raster::filename ()
Definition at line 734 of file GDALUtils.hpp.
std::vector<pdal::Dimension::Type> pdal::gdal::Raster::getPDALDimensionTypes () const
Get a vector of dimensions that map to the bands of a raster.
Definition at line 688 of file GDALUtils.hpp.
bool pdal::gdal::Raster::getPixelAndLinePosition (double x, double y, int32_t & pixel, int32_t & line) private
Definition at line 584 of file GDALUtils.cpp.
References m_height, m_inverseTransform, and m_width.
Referenced by read().
SpatialReference pdal::gdal::Raster::getSpatialRef () const
Get the spatial reference associated with the raster.
Returns
The associated spatial reference.
Definition at line 667 of file GDALUtils.cpp.
References m_ds.
int pdal::gdal::Raster::height () const
Get the height of the raster (Y direction)
Definition at line 731 of file GDALUtils.hpp.
Referenced by open().
GDALError pdal::gdal::Raster::open ()
Open raster file for reading.
Definition at line 459 of file GDALUtils.cpp.
References pdal::gdal::CantOpen, computePDALDimensionTypes(), pdal::gdal::InvalidBand, m_drivername, m_ds, m_errorMsg, m_filename, m_forwardTransform, m_height, m_inverseTransform, m_numBands, m_width, pdal::gdal::None, pdal::gdal::NotInvertible, and pdal::gdal::NoTransform.
Referenced by pdal::GDALWriter::doneFile(), and pdal::eigen::writeMatrix().
GDALError pdal::gdal::Raster::open (int width, int height, int numBands, Dimension::Type type, double noData, StringList options = StringList())
Open a raster for writing.
Parameters
width Width of the raster in cells (X direction)
height Height of the raster in cells (Y direction)
numBands Number of bands in the raster.
type Datatype (int, float, etc.) of the raster data.
noData Value that indiciates no data in the output raster cell.
options GDAL driver options.
Definition at line 360 of file GDALUtils.cpp.
References pdal::gdal::CantCreate, pdal::gdal::DriverNotFound, pdal::SpatialReference::getWKT(), height(), pdal::gdal::InvalidDriver, pdal::gdal::InvalidOption, m_bandType, m_drivername, m_ds, m_dstNoData, m_errorMsg, m_filename, m_forwardTransform, m_height, m_inverseTransform, m_numBands, m_srs, m_width, pdal::gdal::None, pdal::gdal::NotInvertible, pdal::Dimension::Signed8, pdal::gdal::anonymous_namespace{GDALUtils.cpp}::toGdalType(), pdal::Dimension::type(), pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned8, pdal::SpatialReference::valid(), validateType(), and width().
void pdal::gdal::Raster::pixelToCoord (int column, int row, std::array< double, 2 > & output) const
Convert an X/Y raster position into geo-located position using the raster's transformation matrix.
Parameters
column raster column whose position should be calculated
row raster row whose position should be calculated
[out] Array containing the geo-located position of the pixel.
double *xform = const_cast<double *>(m_forwardTransform.data()); GDALApplyGeoTransform(xform, col, row, &output[0], &output[1]);
Definition at line 553 of file GDALUtils.cpp.
References a, b, c, pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and m_forwardTransform.
GDALError pdal::gdal::Raster::read (double x, double y, std::vector< double > & data)
Read the data for each band at x/y into a vector of doubles. x and y are transformed to the basis of the raster before the data is fetched.
Parameters
x X position to read
y Y position to read
data Vector in which to store data.
Definition at line 630 of file GDALUtils.cpp.
References b, getPixelAndLinePosition(), m_ds, m_errorMsg, m_numBands, pdal::gdal::NoData, pdal::gdal::None, and pdal::gdal::NotOpen.
template<typename T > GDALError pdal::gdal::Raster::readBand (std::vector< T > & points, int nBand)
Read an entire raster band (layer) into a vector.
Parameters
band Vector into which data will be read. The vector will be resized appropriately to hold the data.
nBand Band number to read. Band numbers start at 1.
Returns
Error code or GDALError::None.
Definition at line 577 of file GDALUtils.hpp.
References pdal::gdal::CantReadBlock, pdal::gdal::InvalidBand, pdal::gdal::None, and hag::read().
GDALError pdal::gdal::Raster::validateType (Dimension::Type & type, GDALDriver * driver) private
Parameters
type Reqested type of the raster.
driver Pointer to the GDAL driver being used to write the raster.
Returns
Requested type, or if not supported, the preferred type to use for the raster.
Definition at line 517 of file GDALUtils.cpp.
References pdal::Utils::contains(), pdal::Dimension::interpretationName(), pdal::gdal::InvalidType, m_drivername, m_errorMsg, pdal::Dimension::None, pdal::gdal::None, pdal::Utils::split2(), and pdal::gdal::anonymous_namespace{GDALUtils.cpp}::toPdalType().
Referenced by open().
int pdal::gdal::Raster::width () const
Get the width of the raster (X direction)
Definition at line 725 of file GDALUtils.hpp.
Referenced by open().
template<typename SOURCE_ITER > GDALError pdal::gdal::Raster::writeBand (SOURCE_ITER si, ITER_VAL< SOURCE_ITER > srcNoData, int nBand, const std::string & name = "")
Write an entire raster band (layer) into raster to be written with GDAL.
Parameters
data Linearized raster data to be written.
noData No-data value in the source data.
nBand Band number to write.
name Name of the raster band.
Definition at line 611 of file GDALUtils.hpp.
References pdal::gdal::CantWriteBlock, pdal::Dimension::Double, pdal::Dimension::Float, pdal::Dimension::name(), pdal::Dimension::None, pdal::gdal::None, hag::read(), pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, pdal::Dimension::Unsigned8, and pdal::gdal::CantWriteBlock::what.
Referenced by pdal::GDALWriter::doneFile(), and pdal::eigen::writeMatrix().
Member Data Documentation
Dimension::Type pdal::gdal::Raster::m_bandType private
Definition at line 747 of file GDALUtils.hpp.
Referenced by open().
std::vector<std::array<double, 2> > pdal::gdal::Raster::m_block_sizes private
Definition at line 752 of file GDALUtils.hpp.
std::string pdal::gdal::Raster::m_drivername private
Definition at line 742 of file GDALUtils.hpp.
Referenced by open(), and validateType().
GDALDataset* pdal::gdal::Raster::m_ds private
Definition at line 746 of file GDALUtils.hpp.
Referenced by close(), computePDALDimensionTypes(), getSpatialRef(), open(), and read().
double pdal::gdal::Raster::m_dstNoData private
Definition at line 748 of file GDALUtils.hpp.
Referenced by open().
std::string pdal::gdal::Raster::m_errorMsg private
Definition at line 750 of file GDALUtils.hpp.
Referenced by computePDALDimensionTypes(), open(), read(), and validateType().
std::string pdal::gdal::Raster::m_filename private
Definition at line 737 of file GDALUtils.hpp.
Referenced by computePDALDimensionTypes(), and open().
std::array<double, 6> pdal::gdal::Raster::m_forwardTransform private
Definition at line 743 of file GDALUtils.hpp.
Referenced by open(), pixelToCoord(), and Raster().
int pdal::gdal::Raster::m_height private
Definition at line 740 of file GDALUtils.hpp.
Referenced by getPixelAndLinePosition(), and open().
std::array<double, 6> pdal::gdal::Raster::m_inverseTransform private
Definition at line 744 of file GDALUtils.hpp.
Referenced by getPixelAndLinePosition(), open(), and Raster().
int pdal::gdal::Raster::m_numBands private
Definition at line 741 of file GDALUtils.hpp.
Referenced by computePDALDimensionTypes(), open(), and read().
SpatialReference pdal::gdal::Raster::m_srs private
Definition at line 745 of file GDALUtils.hpp.
Referenced by open().
std::vector<pdal::Dimension::Type> pdal::gdal::Raster::m_types mutable private
Definition at line 751 of file GDALUtils.hpp.
Referenced by close(), and computePDALDimensionTypes().
int pdal::gdal::Raster::m_width private
Definition at line 739 of file GDALUtils.hpp.
Referenced by getPixelAndLinePosition(), and open().
The documentation for this class was generated from the following files:
pdal/pdal/GDALUtils.hpp
pdal/pdal/GDALUtils.cpp