PDAL: pdal::BpfCompressor Class Reference
pdal::BpfCompressor Class Reference
#include <BpfCompressor.hpp>
Classes
struct error
Public Member Functions
BpfCompressor (OLeStream &, size_t)
void startBlock ()
void finish ()
void compress ()
Static Private Attributes
static const int CHUNKSIZE = 1000000
Detailed Description
Definition at line 50 of file BpfCompressor.hpp.
Constructor & Destructor Documentation
pdal::BpfCompressor::BpfCompressor (OLeStream & , size_t)
Definition at line 65 of file BpfCompressor.hpp.
References compress(), finish(), and startBlock().
Referenced by pdal::BpfCompressor::error::error().
Member Function Documentation
void pdal::BpfCompressor::compress ()
Definition at line 138 of file BpfCompressor.cpp.
Referenced by BpfCompressor(), and pdal::BpfWriter::writeDimMajor().
void pdal::BpfCompressor::finish ()
Definition at line 140 of file BpfCompressor.cpp.
Referenced by BpfCompressor(), and pdal::BpfWriter::writeDimMajor().
void pdal::BpfCompressor::startBlock ()
Definition at line 136 of file BpfCompressor.cpp.
Referenced by BpfCompressor(), pdal::BpfWriter::writeByteMajor(), pdal::BpfWriter::writeDimMajor(), and pdal::BpfWriter::writePointMajor().
Member Data Documentation
const int pdal::BpfCompressor::CHUNKSIZE = 1000000 static private
Definition at line 74 of file BpfCompressor.hpp.
The documentation for this class was generated from the following files:
pdal/io/BpfCompressor.hpp
pdal/io/BpfCompressor.cpp