PDAL: pdal::MetadataNode Class Reference
pdal::MetadataNode Class Reference
#include <Metadata.hpp>
Public Member Functions
MetadataNode ()
MetadataNode (const std::string &name)
MetadataNode add (const std::string &name)
MetadataNode addList (const std::string &name)
MetadataNode clone (const std::string &name) const
MetadataNode add (MetadataNode node)
MetadataNode addList (MetadataNode node)
MetadataNode addEncoded (const std::string &name, const unsigned char *buf, size_t size, const std::string &descrip=std::string())
MetadataNode addListEncoded (const std::string &name, const unsigned char *buf, size_t size, const std::string &descrip=std::string())
MetadataNode addWithType (const std::string &name, const std::string &value, const std::string &type, const std::string &descrip)
template<typename T >
MetadataNode add (const std::string &name, const T &value, const std::string &descrip=std::string())
template<typename T >
MetadataNode addList (const std::string &name, const T &value, const std::string &descrip=std::string())
template<typename T >
MetadataNode addOrUpdate (const std::string &lname, const T &value)
template<typename T >
MetadataNode addOrUpdate (const std::string &lname, const T &value, const std::string &descrip)
std::string type () const
MetadataType kind () const
std::string name () const
template<typename T >
T value () const
std::string value () const
std::string jsonValue () const
std::string description () const
MetadataNodeList children () const
MetadataNodeList children (const std::string &name) const
bool hasChildren () const
std::vector< std::string > childNames () const
bool operator! ()
bool valid () const
bool empty () const
template<typename PREDICATE >
MetadataNode find (PREDICATE p) const
template<typename PREDICATE >
MetadataNodeList findChildren (PREDICATE p)
template<typename PREDICATE >
MetadataNode findChild (PREDICATE p) const
MetadataNode findChild (const char *s) const
MetadataNode findChild (std::string s) const
Private Member Functions
MetadataNode (MetadataNodeImplPtr node)
std::string escapeQuotes (const std::string &in) const
Private Attributes
MetadataNodeImplPtr m_impl
Friends
class Metadata
bool operator== (const MetadataNode &m1, const MetadataNode &m2)
bool operator!= (const MetadataNode &m1, const MetadataNode &m2)
Detailed Description
Definition at line 339 of file Metadata.hpp.
Constructor & Destructor Documentation
pdal::MetadataNode::MetadataNode ()
Definition at line 348 of file Metadata.hpp.
pdal::MetadataNode::MetadataNode (const std::string & name)
Definition at line 351 of file Metadata.hpp.
pdal::MetadataNode::MetadataNode (MetadataNodeImplPtr node) private
Definition at line 638 of file Metadata.hpp.
Member Function Documentation
MetadataNode pdal::MetadataNode::add (const std::string & name)
Definition at line 354 of file Metadata.hpp.
References pdal::MetadataNode.
Referenced by add(), addEncoded(), pdal::addForwardMetadata(), pdal::anonymous_namespace{CpdFilter.cpp}::addMetadata(), addWithType(), pdal::CpdFilter::change(), pdal::DiffKernel::checkPoints(), pdal::CpdFilter::cpd_affine(), pdal::CpdFilter::cpd_rigid(), pdal::SQLiteWriter::CreateCloud(), pdal::OciWriter::createPCEntry(), pdal::HexBin::done(), pdal::MatlabReader::done(), pdal::InfoKernel::dump(), pdal::DeltaKernel::dump(), pdal::DeltaKernel::dumpDetail(), pdal::InfoKernel::dumpPoints(), pdal::InfoKernel::dumpSummary(), pdal::DiffKernel::execute(), pdal::HausdorffKernel::execute(), pdal::LasReader::extractHeaderMetadata(), pdal::stats::Summary::extractMetadata(), pdal::StatsFilter::extractMetadata(), pdal::LasReader::extractVlrMetadata(), pdal::PipelineManager::getMetadata(), pdal::IcpFilter::icp(), pdal::NitfReader::initialize(), pdal::Stage::l_initialize(), pdal::XMLSchema::loadMetadata(), pdal::Ilvis2MetadataReader::parseCollectionMetaData(), pdal::Ilvis2MetadataReader::parseDataFileContainer(), pdal::Ilvis2MetadataReader::parseECSDataGranule(), pdal::Ilvis2MetadataReader::parseGPolygon(), pdal::Ilvis2MetadataReader::parseGranuleMetaDataFile(), pdal::Ilvis2MetadataReader::parseGranuleURMetaData(), pdal::Ilvis2MetadataReader::parseInstrument(), pdal::Ilvis2MetadataReader::parsePlatform(), pdal::Ilvis2MetadataReader::parsePSA(), pdal::Ilvis2MetadataReader::parseRangeDateTime(), pdal::Ilvis2MetadataReader::parseSensor(), pdal::Ilvis2MetadataReader::parseSensorCharacteristic(), pdal::BasePointTable::privateMetadata(), pdal::BpfReader::readUlemFiles(), pdal::InfoKernel::run(), pdal::Stage::serialize(), pdal::Stage::setSpatialReference(), pdal::PgWriter::SetupSchema(), TEST(), pdal::Option::toMetadata(), pdal::SpatialReference::toMetadata(), pdal::Options::toMetadata(), pdal::Utils::toMetadata(), pdal::PointLayout::toMetadata(), pdal::PointView::toMetadata(), pdal::MetadataReader::writeField(), pdal::MetadataReader::writeInt(), and pdal::MetadataReader::writeString().
MetadataNode pdal::MetadataNode::add (MetadataNode node)
Definition at line 368 of file Metadata.hpp.
References m_impl, and pdal::MetadataNode.
template<typename T > MetadataNode pdal::MetadataNode::add (const std::string & name, const T & value, const std::string & descrip = std::string())
Definition at line 407 of file Metadata.hpp.
References add(), and pdal::MetadataNode.
MetadataNode pdal::MetadataNode::addEncoded (const std::string & name, const unsigned char * buf, size_t size, const std::string & descrip = std::string())
Definition at line 374 of file Metadata.hpp.
References add(), pdal::Utils::base64_encode(), and pdal::MetadataNode.
Referenced by pdal::LasReader::extractHeaderMetadata(), pdal::LasReader::extractVlrMetadata(), pdal::BpfReader::readHeaderExtraData(), pdal::BpfReader::readUlemFiles(), and TEST().
MetadataNode pdal::MetadataNode::addList (const std::string & name)
Definition at line 357 of file Metadata.hpp.
References pdal::MetadataNode.
Referenced by addList(), addListEncoded(), pdal::SbetWriter::done(), pdal::MatlabWriter::done(), pdal::PcdWriter::done(), pdal::PlyWriter::done(), pdal::HexBin::done(), pdal::MbReader::done(), pdal::MrsidReader::done(), pdal::MatlabReader::done(), pdal::GDALWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::LasWriter::doneFile(), pdal::stats::Summary::extractMetadata(), pdal::StatsFilter::extractMetadata(), pdal::Ilvis2MetadataReader::parseCampaign(), pdal::Ilvis2MetadataReader::parseDataFiles(), pdal::Ilvis2MetadataReader::parseGranuleURMetaData(), pdal::Ilvis2MetadataReader::parseInstrument(), pdal::Ilvis2MetadataReader::parsePlatform(), pdal::Ilvis2MetadataReader::parsePSA(), pdal::Ilvis2MetadataReader::parsePSAs(), pdal::Ilvis2MetadataReader::parseSensor(), pdal::Ilvis2MetadataReader::parseXXProduct(), pdal::Stage::serialize(), and pdal::PointLayout::toMetadata().
MetadataNode pdal::MetadataNode::addList (MetadataNode node)
Definition at line 371 of file Metadata.hpp.
References m_impl, and pdal::MetadataNode.
template<typename T > MetadataNode pdal::MetadataNode::addList (const std::string & name, const T & value, const std::string & descrip = std::string())
Definition at line 417 of file Metadata.hpp.
References addList(), and pdal::MetadataNode.
MetadataNode pdal::MetadataNode::addListEncoded (const std::string & name, const unsigned char * buf, size_t size, const std::string & descrip = std::string())
Definition at line 385 of file Metadata.hpp.
References addList(), pdal::Utils::base64_encode(), and pdal::MetadataNode.
template<typename T > MetadataNode pdal::MetadataNode::addOrUpdate (const std::string & lname, const T & value)
Definition at line 427 of file Metadata.hpp.
References pdal::Array, and pdal::MetadataNode.
Referenced by pdal::addForwardMetadata().
template<typename T > MetadataNode pdal::MetadataNode::addOrUpdate (const std::string & lname, const T & value, const std::string & descrip)
Definition at line 441 of file Metadata.hpp.
MetadataNode pdal::MetadataNode::addWithType (const std::string & name, const std::string & value, const std::string & type, const std::string & descrip)
Definition at line 396 of file Metadata.hpp.
References add(), pdal::MetadataNode, and pdal::Dimension::type().
Referenced by pdal::plang::addMetadata(), pdal::LasReader::extractHeaderMetadata(), pdal::StatsFilter::extractMetadata(), pdal::Option::toMetadata(), and pdal::Options::toMetadata().
std::vector<std::string> pdal::MetadataNode::childNames () const
Definition at line 539 of file Metadata.hpp.
Referenced by pdal::anonymous_namespace{PDALUtils.cpp}::subnodesToJSON().
MetadataNodeList pdal::MetadataNode::children () const
Definition at line 508 of file Metadata.hpp.
Referenced by pdal::anonymous_namespace{XMLSchema.cpp}::addMetadataEntry(), pdal::plang::fromMetadata(), printChildren(), pdal::anonymous_namespace{PDALUtils.cpp}::subnodesToJSON(), TEST(), TEST_F(), and pdal::Utils::toJSON().
MetadataNodeList pdal::MetadataNode::children (const std::string & name) const
Definition at line 522 of file Metadata.hpp.
MetadataNode pdal::MetadataNode::clone (const std::string & name) const
Definition at line 360 of file Metadata.hpp.
References m_impl, and pdal::Dimension::name().
Referenced by pdal::InfoKernel::dump(), pdal::InfoKernel::dumpPoints(), pdal::PipelineExecutor::getMetadata(), pdal::PipelineExecutor::getSchema(), pdal::InfoKernel::run(), and pdal::mlang::Script::setMatlabStruct().
std::string pdal::MetadataNode::description () const
Definition at line 505 of file Metadata.hpp.
Referenced by pdal::plang::fromMetadata(), and TEST().
bool pdal::MetadataNode::empty () const
Definition at line 553 of file Metadata.hpp.
Referenced by find(), findChild(), pdal::Stage::setSpatialReference(), TEST(), and pdal::XMLSchema::writeXml().
std::string pdal::MetadataNode::escapeQuotes (const std::string & in) const private
Definition at line 641 of file Metadata.hpp.
template<typename PREDICATE > MetadataNode pdal::MetadataNode::find (PREDICATE p) const
Definition at line 557 of file Metadata.hpp.
References empty(), find(), and pdal::MetadataNode.
Referenced by find(), findChild(), pdal::LasWriter::findVlrMetadata(), and TEST().
template<typename PREDICATE > MetadataNode pdal::MetadataNode::findChild (PREDICATE p) const
Definition at line 587 of file Metadata.hpp.
References pdal::MetadataNode.
Referenced by pdal::OciReader::addDimensions(), pdal::addForwardMetadata(), pdal::LasWriter::addForwardVlrs(), anonymous_namespace{NitfWriterTest.cpp}::compare_contents(), pdal::InfoKernel::dumpPoints(), findChild(), pdal::TIndexKernel::getFileInfo(), pdal::LasWriter::handleHeaderForward(), pdal::BasePointTable::privateMetadata(), pdal::OciReader::readOci(), pdal::Stage::setSpatialReference(), TEST(), pdal::TEST(), and TEST_F().
MetadataNode pdal::MetadataNode::findChild (const char * s) const
Definition at line 599 of file Metadata.hpp.
MetadataNode pdal::MetadataNode::findChild (std::string s) const
Definition at line 602 of file Metadata.hpp.
References empty(), find(), findChild(), and pdal::MetadataNode.
template<typename PREDICATE > MetadataNodeList pdal::MetadataNode::findChildren (PREDICATE p)
Definition at line 572 of file Metadata.hpp.
Referenced by pdal::LasWriter::addForwardVlrs(), and TEST().
bool pdal::MetadataNode::hasChildren () const
Definition at line 536 of file Metadata.hpp.
Referenced by pdal::anonymous_namespace{PDALUtils.cpp}::arrayEltToJSON(), and pdal::anonymous_namespace{PDALUtils.cpp}::toJSON().
std::string pdal::MetadataNode::jsonValue () const
Definition at line 488 of file Metadata.hpp.
References pdal::Utils::escapeJSON().
Referenced by pdal::anonymous_namespace{PDALUtils.cpp}::arrayEltToJSON(), and pdal::anonymous_namespace{PDALUtils.cpp}::toJSON().
MetadataType pdal::MetadataNode::kind () const
Definition at line 452 of file Metadata.hpp.
Referenced by pdal::anonymous_namespace{PDALUtils.cpp}::subnodesToJSON(), and pdal::Utils::toJSON().
std::string pdal::MetadataNode::name () const
Definition at line 455 of file Metadata.hpp.
Referenced by anonymous_namespace{NitfWriterTest.cpp}::compare_contents(), pdal::plang::fromMetadata(), printChildren(), pdal::Stage::setSpatialReference(), pdal::anonymous_namespace{PDALUtils.cpp}::subnodesToJSON(), TEST(), pdal::anonymous_namespace{PDALUtils.cpp}::toJSON(), and pdal::Utils::toJSON().
bool pdal::MetadataNode::operator! ()
Definition at line 549 of file Metadata.hpp.
std::string pdal::MetadataNode::type () const
Definition at line 449 of file Metadata.hpp.
Referenced by pdal::plang::fromMetadata(), TEST(), and pdal::TEST().
bool pdal::MetadataNode::valid () const
Definition at line 551 of file Metadata.hpp.
Referenced by pdal::addForwardMetadata(), pdal::LasWriter::addForwardVlrs(), pdal::LasWriter::handleHeaderForward(), and pdal::BasePointTable::privateMetadata().
template<typename T > T pdal::MetadataNode::value () const
Definition at line 459 of file Metadata.hpp.
References pdal::Utils::base64_decode(), pdal::Utils::fromString(), and pdal::Dimension::name().
Referenced by pdal::OciReader::addDimensions(), pdal::addForwardMetadata(), pdal::LasWriter::addForwardVlrs(), anonymous_namespace{NitfWriterTest.cpp}::compare_contents(), pdal::plang::fromMetadata(), pdal::TIndexKernel::getFileInfo(), pdal::LasWriter::handleHeaderForward(), printChildren(), pdal::OciReader::readOci(), pdal::SQLiteReader::readPatch(), TEST(), and pdal::TEST().
std::string pdal::MetadataNode::value () const
Definition at line 485 of file Metadata.hpp.
Friends And Related Function Documentation
friend class Metadata friend
Definition at line 341 of file Metadata.hpp.
bool operator!= (const MetadataNode & m1, const MetadataNode & m2) friend
Definition at line 661 of file Metadata.hpp.
bool operator== (const MetadataNode & m1, const MetadataNode & m2) friend
Definition at line 656 of file Metadata.hpp.
Member Data Documentation
MetadataNodeImplPtr pdal::MetadataNode::m_impl private
Definition at line 636 of file Metadata.hpp.
Referenced by add(), addList(), clone(), pdal::operator!=(), and pdal::operator==().
The documentation for this class was generated from the following file:
pdal/pdal/Metadata.hpp