PDAL: GDALReaderTypeTest Class Reference
GDALReaderTypeTest Class Reference
Protected Member Functions
GDALReaderTypeTest ()
void compare (const std::string &path)
Private Attributes
std::vector< Point > m_xyzPoints
std::vector< Point > m_gdalPoints
Detailed Description
Definition at line 121 of file GDALReaderTest.cpp.
Constructor & Destructor Documentation
GDALReaderTypeTest::GDALReaderTypeTest () protected
Definition at line 124 of file GDALReaderTest.cpp.
References Support::datapath().
Member Function Documentation
void GDALReaderTypeTest::compare (const std::string & path) protected
Definition at line 140 of file GDALReaderTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::PointLayout::findDim(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::X, and pdal::Dimension::Y.
Member Data Documentation
std::vector<Point> GDALReaderTypeTest::m_gdalPoints private
Definition at line 175 of file GDALReaderTest.cpp.
std::vector<Point> GDALReaderTypeTest::m_xyzPoints private
Definition at line 174 of file GDALReaderTest.cpp.
The documentation for this class was generated from the following file:
pdal/test/unit/io/GDALReaderTest.cpp