PDAL: pdal::InfoKernel Class Reference
pdal::InfoKernel Class Reference
#include <InfoKernel.hpp>
Public Member Functions
std::string getName () const
int execute ()
void setup (const std::string &filename)
MetadataNode run (const std::string &filename)
bool showAll ()
void doShowAll (bool value)
void doComputeSummary (bool value)
void doComputeBoundary (bool value)
int run (const StringList &cmdArgs, LogPtr &log)
std::string getShortName () const
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
Protected Member Functions
Stage & makeReader (const std::string &inputFile, std::string driver)
Stage & makeReader (const std::string &inputFile, std::string driver, Options options)
Stage & makeFilter (const std::string &driver, Stage &parent)
Stage & makeFilter (const std::string &driver, Stage &parent, Options options)
Stage & makeFilter (const std::string &driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver, Options options)
virtual bool isStagePrefix (const std::string &stageType)
Protected Attributes
LogPtr m_log
PipelineManager m_manager
std::string m_driverOverride
Private Member Functions
InfoKernel ()
void addSwitches (ProgramArgs &args)
void validateSwitches (ProgramArgs &args)
void dump (MetadataNode &root)
MetadataNode dumpPoints (PointViewPtr inView) const
MetadataNode dumpStats () const
void dumpPipeline () const
MetadataNode dumpSummary (const QuickInfo &qi)
MetadataNode dumpQuery (PointViewPtr inView) const
void makePipeline (const std::string &filename, bool noPoints)
Private Attributes
std::string m_inputFile
bool m_showStats
bool m_showSchema
bool m_showAll
bool m_showMetadata
bool m_boundary
std::string m_pointIndexes
std::string m_dimensions
std::string m_queryPoint
std::string m_pipelineFile
bool m_showSummary
bool m_needPoints
std::string m_PointCloudSchemaOutput
bool m_usestdin
Stage * m_statsStage
Stage * m_hexbinStage
Stage * m_reader
MetadataNode m_tree
Detailed Description
Definition at line 54 of file InfoKernel.hpp.
Constructor & Destructor Documentation
pdal::InfoKernel::InfoKernel () private
Definition at line 59 of file InfoKernel.cpp.
Member Function Documentation
void pdal::InfoKernel::addSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 123 of file InfoKernel.cpp.
References pdal::ProgramArgs::add(), m_boundary, m_dimensions, m_inputFile, m_pipelineFile, m_PointCloudSchemaOutput, m_pointIndexes, m_queryPoint, m_showAll, m_showMetadata, m_showSchema, m_showStats, m_showSummary, m_usestdin, pdal::Arg::setHidden(), and pdal::Arg::setOptionalPositional().
static void* pdal::InfoKernel::create () static
static int32_t pdal::InfoKernel::destroy (void *) static
void pdal::InfoKernel::doComputeBoundary (bool value)
Definition at line 69 of file InfoKernel.hpp.
void pdal::InfoKernel::doComputeSummary (bool value)
Definition at line 68 of file InfoKernel.hpp.
void pdal::InfoKernel::doShowAll (bool value)
Definition at line 67 of file InfoKernel.hpp.
void pdal::InfoKernel::dump (MetadataNode & root) private
Definition at line 355 of file InfoKernel.cpp.
References pdal::MetadataNode::add(), b, pdal::MetadataNode::clone(), pdal::Utils::closeFile(), pdal::Utils::createFile(), dumpPoints(), dumpQuery(), pdal::PipelineManager::getMetadata(), pdal::Stage::getMetadata(), pdal::PipelineManager::getStage(), pdal::BOX2D::grow(), pdal::BasePointTable::layout(), m_boundary, m_hexbinStage, pdal::Kernel::m_manager, m_pipelineFile, m_PointCloudSchemaOutput, m_pointIndexes, m_queryPoint, m_reader, m_showMetadata, m_showSchema, m_showStats, m_statsStage, pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::PipelineManager::pointTable(), pdal::PointLayout::toMetadata(), pdal::PipelineManager::views(), pdal::PipelineWriter::writePipeline(), and xml.
Referenced by run().
void pdal::InfoKernel::dumpPipeline () const private
MetadataNode pdal::InfoKernel::dumpPoints (PointViewPtr inView) const private
Definition at line 200 of file InfoKernel.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::clone(), pdal::MetadataNode::findChild(), pdal::anonymous_namespace{InfoKernel.cpp}::getListOfPoints(), pdal::Dimension::id(), pdal::Kernel::m_log, m_pointIndexes, pdal::Dimension::size(), and pdal::Warning.
Referenced by dump().
MetadataNode pdal::InfoKernel::dumpQuery (PointViewPtr inView) const private
Definition at line 443 of file InfoKernel.cpp.
References pdal::KDIndex< DIM >::build(), c, pdal::Utils::fromString(), m_queryPoint, pdal::KD2Index::neighbors(), pdal::KD3Index::neighbors(), and pdal::Utils::split2().
Referenced by dump().
MetadataNode pdal::InfoKernel::dumpStats () const private
MetadataNode pdal::InfoKernel::dumpSummary (const QuickInfo & qi) private
Definition at line 233 of file InfoKernel.cpp.
References pdal::MetadataNode::add(), pdal::QuickInfo::m_bounds, pdal::QuickInfo::m_dimNames, pdal::QuickInfo::m_pointCount, pdal::QuickInfo::m_srs, pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::BOX3D::minz, pdal::SpatialReference::toMetadata(), pdal::SpatialReference::valid(), pdal::BOX3D::valid(), and z.
Referenced by run().
int pdal::InfoKernel::execute () virtual
Implements pdal::Kernel.
Definition at line 503 of file InfoKernel.cpp.
References m_inputFile, m_usestdin, run(), setup(), and pdal::Utils::toJSON().
std::string pdal::InfoKernel::getName () const virtual
Implements pdal::Kernel.
Definition at line 57 of file InfoKernel.cpp.
References pdal::PluginInfo::name.
std::string pdal::Kernel::getShortName () const inherited
Definition at line 67 of file Kernel.hpp.
References pdal::Utils::split2().
Referenced by pdal::Kernel::outputHelp().
bool pdal::Kernel::isStagePrefix (const std::string & stageType) protected virtual inherited
Reimplemented in pdal::PipelineKernel.
Definition at line 58 of file Kernel.cpp.
Referenced by pdal::PipelineKernel::isStagePrefix(), and pdal::Kernel::parseStageOption().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent) protected inherited
Definition at line 320 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent, Options options) protected inherited
Definition at line 326 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeFilter (const std::string & driver) protected inherited
Definition at line 314 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
void pdal::InfoKernel::makePipeline (const std::string & filename, bool noPoints) private
Definition at line 271 of file InfoKernel.cpp.
References pdal::Options::add(), pdal::FileUtils::extension(), pdal::Utils::fileExists(), pdal::PipelineManager::getStage(), pdal::Kernel::m_driverOverride, pdal::Kernel::m_manager, m_reader, pdal::PipelineManager::makeReader(), and pdal::PipelineManager::readPipeline().
Referenced by setup().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver) protected inherited
Definition at line 301 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver, Options options) protected inherited
Definition at line 307 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver) protected inherited
Definition at line 333 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver, Options options) protected inherited
Definition at line 340 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
int pdal::Kernel::run (const StringList & cmdArgs, LogPtr & log) inherited
Definition at line 229 of file Kernel.cpp.
References pdal::Kernel::doExecution(), pdal::Kernel::doStartup(), pdal::Kernel::doSwitches(), setup::log, pdal::Kernel::m_log, pdal::Kernel::m_manager, pdal::Kernel::m_showHelp, pdal::Kernel::outputHelp(), pdal::Utils::printError(), and pdal::PipelineManager::setLog().
Referenced by App::execute().
MetadataNode pdal::InfoKernel::run (const std::string & filename)
Definition at line 328 of file InfoKernel.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::clone(), dump(), dumpSummary(), pdal::PipelineManager::execute(), pdal::GetFullVersionString(), pdal::Kernel::m_manager, m_needPoints, m_reader, m_showMetadata, m_showSummary, pdal::PipelineManager::prepare(), pdal::Stage::preview(), and pdal::QuickInfo::valid().
Referenced by execute().
void pdal::InfoKernel::setup (const std::string & filename)
Definition at line 300 of file InfoKernel.cpp.
References pdal::Options::add(), m_boundary, m_dimensions, m_hexbinStage, pdal::Kernel::m_manager, m_needPoints, m_reader, m_showStats, m_statsStage, pdal::PipelineManager::makeFilter(), and makePipeline().
Referenced by execute().
bool pdal::InfoKernel::showAll ()
Definition at line 66 of file InfoKernel.hpp.
void pdal::InfoKernel::validateSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 71 of file InfoKernel.cpp.
References m_boundary, m_inputFile, m_needPoints, m_pointIndexes, m_queryPoint, m_showAll, m_showMetadata, m_showSchema, m_showStats, m_showSummary, and m_usestdin.
Member Data Documentation
bool pdal::InfoKernel::m_boundary private
Definition at line 89 of file InfoKernel.hpp.
Referenced by addSwitches(), dump(), setup(), and validateSwitches().
std::string pdal::InfoKernel::m_dimensions private
Definition at line 91 of file InfoKernel.hpp.
Referenced by addSwitches(), and setup().
std::string pdal::Kernel::m_driverOverride protected inherited
Definition at line 105 of file Kernel.hpp.
Referenced by pdal::Kernel::addBasicSwitches(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::DiffKernel::execute(), pdal::DeltaKernel::loadSet(), makePipeline(), and pdal::TIndexKernel::mergeFile().
Stage* pdal::InfoKernel::m_hexbinStage private
Definition at line 100 of file InfoKernel.hpp.
Referenced by dump(), and setup().
std::string pdal::InfoKernel::m_inputFile private
Definition at line 84 of file InfoKernel.hpp.
Referenced by addSwitches(), execute(), and validateSwitches().
LogPtr pdal::Kernel::m_log protected inherited
Definition at line 103 of file Kernel.hpp.
Referenced by pdal::TIndexKernel::createFeature(), pdal::TIndexKernel::createFile(), pdal::TIndexKernel::createLayer(), dumpPoints(), pdal::TranslateKernel::execute(), and pdal::Kernel::run().
PipelineManager pdal::Kernel::m_manager protected inherited
Definition at line 104 of file Kernel.hpp.
Referenced by pdal::Kernel::doSwitches(), dump(), pdal::SmoothKernel::execute(), pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), pdal::TranslateKernel::execute(), pdal::TIndexKernel::getFileInfo(), pdal::TranslateKernel::makeArgPipeline(), pdal::Kernel::makeFilter(), pdal::TranslateKernel::makeJSONPipeline(), makePipeline(), pdal::Kernel::makeReader(), pdal::Kernel::makeWriter(), run(), pdal::Kernel::run(), and setup().
bool pdal::InfoKernel::m_needPoints private
Definition at line 95 of file InfoKernel.hpp.
Referenced by run(), setup(), and validateSwitches().
std::string pdal::InfoKernel::m_pipelineFile private
Definition at line 93 of file InfoKernel.hpp.
Referenced by addSwitches(), and dump().
std::string pdal::InfoKernel::m_PointCloudSchemaOutput private
Definition at line 96 of file InfoKernel.hpp.
Referenced by addSwitches(), and dump().
std::string pdal::InfoKernel::m_pointIndexes private
Definition at line 90 of file InfoKernel.hpp.
Referenced by addSwitches(), dump(), dumpPoints(), and validateSwitches().
std::string pdal::InfoKernel::m_queryPoint private
Definition at line 92 of file InfoKernel.hpp.
Referenced by addSwitches(), dump(), dumpQuery(), and validateSwitches().
Stage* pdal::InfoKernel::m_reader private
Definition at line 101 of file InfoKernel.hpp.
Referenced by dump(), makePipeline(), run(), and setup().
bool pdal::InfoKernel::m_showAll private
Definition at line 87 of file InfoKernel.hpp.
Referenced by addSwitches(), and validateSwitches().
bool pdal::InfoKernel::m_showMetadata private
Definition at line 88 of file InfoKernel.hpp.
Referenced by addSwitches(), dump(), run(), and validateSwitches().
bool pdal::InfoKernel::m_showSchema private
Definition at line 86 of file InfoKernel.hpp.
Referenced by addSwitches(), dump(), and validateSwitches().
bool pdal::InfoKernel::m_showStats private
Definition at line 85 of file InfoKernel.hpp.
Referenced by addSwitches(), dump(), setup(), and validateSwitches().
bool pdal::InfoKernel::m_showSummary private
Definition at line 94 of file InfoKernel.hpp.
Referenced by addSwitches(), run(), and validateSwitches().
Stage* pdal::InfoKernel::m_statsStage private
Definition at line 99 of file InfoKernel.hpp.
Referenced by dump(), and setup().
MetadataNode pdal::InfoKernel::m_tree private
Definition at line 103 of file InfoKernel.hpp.
bool pdal::InfoKernel::m_usestdin private
Definition at line 97 of file InfoKernel.hpp.
Referenced by addSwitches(), execute(), and validateSwitches().
The documentation for this class was generated from the following files:
pdal/kernels/InfoKernel.hpp
pdal/kernels/InfoKernel.cpp