PDAL: pdal::GDALGrid Class Reference
pdal::GDALGrid Class Reference
#include <GDALGrid.hpp>
Classes
struct error
Public Member Functions
GDALGrid (size_t width, size_t height, double edgeLength, double radius, int outputTypes, size_t windowSize)
void expand (size_t width, size_t height, size_t xshift, size_t yshift)
int numBands () const
double * data (const std::string &name)
void addPoint (double x, double y, double z)
void finalize ()
size_t width () const
size_t height () const
Static Public Attributes
static const int statCount = 1
static const int statMin = 2
static const int statMax = 4
static const int statMean = 8
static const int statStdDev = 16
static const int statIdw = 32
Private Types
typedef std::vector< double > DataVec
typedef std::unique_ptr< DataVec > DataPtr
Private Member Functions
size_t index (size_t i, size_t j)
bool empty (size_t i, size_t j)
bool empty (size_t idx)
int horizontalIndex (double x)
int verticalIndex (double y)
double horizontalPos (size_t i)
double verticalPos (size_t j)
double distance (size_t i, size_t j, double x, double y)
void update (int i, int j, double val, double dist)
void fillNodata (size_t i)
void windowFill ()
void windowFill (size_t dstI, size_t dstJ)
void windowFillCell (size_t srcIdx, size_t dstIdx, double distance)
Private Attributes
size_t m_width
size_t m_height
size_t m_windowSize
double m_edgeLength
double m_radius
DataPtr m_count
DataPtr m_min
DataPtr m_max
DataPtr m_mean
DataPtr m_stdDev
DataPtr m_idw
DataPtr m_idwDist
int m_outputTypes
Detailed Description
Definition at line 44 of file GDALGrid.hpp.
Member Typedef Documentation
typedef std::unique_ptr<DataVec> pdal::GDALGrid::DataPtr private
Definition at line 91 of file GDALGrid.hpp.
typedef std::vector<double> pdal::GDALGrid::DataVec private
Definition at line 90 of file GDALGrid.hpp.
Constructor & Destructor Documentation
pdal::GDALGrid::GDALGrid (size_t width, size_t height, double edgeLength, double radius, int outputTypes, size_t windowSize)
Definition at line 46 of file GDALGrid.cpp.
References m_count, m_idw, m_idwDist, m_max, m_mean, m_min, m_outputTypes, m_stdDev, pdal::Dimension::size(), statIdw, statMax, statMean, statMin, and statStdDev.
Referenced by pdal::GDALGrid::error::error().
Member Function Documentation
void pdal::GDALGrid::addPoint (double x, double y, double z)
Definition at line 168 of file GDALGrid.cpp.
References distance(), horizontalIndex(), m_height, m_radius, m_width, update(), and verticalIndex().
Referenced by pdal::GDALGrid::error::error().
double * pdal::GDALGrid::data (const std::string & name)
Definition at line 150 of file GDALGrid.cpp.
References m_count, m_idw, m_max, m_mean, m_min, m_outputTypes, m_stdDev, statCount, statIdw, statMax, statMean, statMin, and statStdDev.
Referenced by pdal::GDALGrid::error::error().
double pdal::GDALGrid::distance (size_t i, size_t j, double x, double y) private
Definition at line 134 of file GDALGrid.hpp.
References fillNodata(), horizontalPos(), update(), and verticalPos().
Referenced by addPoint(), windowFill(), and windowFillCell().
bool pdal::GDALGrid::empty (size_t i, size_t j) private
Definition at line 107 of file GDALGrid.hpp.
References index().
Referenced by finalize(), and windowFill().
bool pdal::GDALGrid::empty (size_t idx) private
Definition at line 111 of file GDALGrid.hpp.
void pdal::GDALGrid::expand (size_t width, size_t height, size_t xshift, size_t yshift)
Expand the grid to a new size.
/param width
Definition at line 75 of file GDALGrid.cpp.
References height(), index(), m_count, m_height, m_idw, m_idwDist, m_max, m_mean, m_min, m_outputTypes, m_stdDev, m_width, pdal::Dimension::size(), statIdw, statMax, statMean, statMin, statStdDev, and width().
Referenced by pdal::GDALGrid::error::error().
void pdal::GDALGrid::fillNodata (size_t i) private
Definition at line 384 of file GDALGrid.cpp.
References m_idw, m_max, m_mean, m_min, and m_stdDev.
Referenced by distance(), finalize(), and windowFill().
void pdal::GDALGrid::finalize ()
Definition at line 355 of file GDALGrid.cpp.
References empty(), fillNodata(), m_count, m_idw, m_stdDev, m_windowSize, and windowFill().
Referenced by pdal::GDALGrid::error::error().
size_t pdal::GDALGrid::height () const
Definition at line 80 of file GDALGrid.hpp.
References m_height.
Referenced by pdal::GDALGrid::error::error(), expand(), and windowFill().
int pdal::GDALGrid::horizontalIndex (double x) private
Definition at line 115 of file GDALGrid.hpp.
References m_edgeLength.
Referenced by addPoint().
double pdal::GDALGrid::horizontalPos (size_t i) private
Definition at line 124 of file GDALGrid.hpp.
References m_edgeLength.
Referenced by distance().
size_t pdal::GDALGrid::index (size_t i, size_t j) private
Definition at line 103 of file GDALGrid.hpp.
Referenced by empty(), expand(), update(), and windowFill().
int pdal::GDALGrid::numBands () const
Definition at line 130 of file GDALGrid.cpp.
References m_outputTypes, statCount, statIdw, statMax, statMean, statMin, and statStdDev.
Referenced by pdal::GDALGrid::error::error().
void pdal::GDALGrid::update (int i, int j, double val, double dist) private
Definition at line 290 of file GDALGrid.cpp.
References index(), m_idw, m_max, m_mean, m_min, and m_stdDev.
Referenced by addPoint(), and distance().
int pdal::GDALGrid::verticalIndex (double y) private
Definition at line 119 of file GDALGrid.hpp.
References m_edgeLength.
Referenced by addPoint().
double pdal::GDALGrid::verticalPos (size_t j) private
Definition at line 129 of file GDALGrid.hpp.
References m_edgeLength.
Referenced by distance().
size_t pdal::GDALGrid::width () const
Definition at line 77 of file GDALGrid.hpp.
References m_width.
Referenced by pdal::GDALGrid::error::error(), expand(), and windowFill().
void pdal::GDALGrid::windowFill () private
Definition at line 149 of file GDALGrid.hpp.
References distance(), empty(), height(), width(), and windowFillCell().
Referenced by finalize().
void pdal::GDALGrid::windowFill (size_t dstI, size_t dstJ) private
Definition at line 399 of file GDALGrid.cpp.
References distance(), empty(), fillNodata(), height(), index(), m_idw, m_max, m_mean, m_min, m_stdDev, m_windowSize, width(), and windowFillCell().
void pdal::GDALGrid::windowFillCell (size_t srcIdx, size_t dstIdx, double distance) private
Definition at line 449 of file GDALGrid.cpp.
References distance(), m_idw, m_max, m_mean, m_min, and m_stdDev.
Referenced by windowFill().
Member Data Documentation
DataPtr pdal::GDALGrid::m_count private
Definition at line 92 of file GDALGrid.hpp.
Referenced by data(), expand(), finalize(), and GDALGrid().
double pdal::GDALGrid::m_edgeLength private
Definition at line 87 of file GDALGrid.hpp.
Referenced by horizontalIndex(), horizontalPos(), verticalIndex(), and verticalPos().
size_t pdal::GDALGrid::m_height private
Definition at line 85 of file GDALGrid.hpp.
Referenced by addPoint(), expand(), and height().
DataPtr pdal::GDALGrid::m_idw private
Definition at line 97 of file GDALGrid.hpp.
Referenced by data(), expand(), fillNodata(), finalize(), GDALGrid(), update(), windowFill(), and windowFillCell().
DataPtr pdal::GDALGrid::m_idwDist private
Definition at line 98 of file GDALGrid.hpp.
Referenced by expand(), and GDALGrid().
DataPtr pdal::GDALGrid::m_max private
Definition at line 94 of file GDALGrid.hpp.
Referenced by data(), expand(), fillNodata(), GDALGrid(), update(), windowFill(), and windowFillCell().
DataPtr pdal::GDALGrid::m_mean private
Definition at line 95 of file GDALGrid.hpp.
Referenced by data(), expand(), fillNodata(), GDALGrid(), update(), windowFill(), and windowFillCell().
DataPtr pdal::GDALGrid::m_min private
Definition at line 93 of file GDALGrid.hpp.
Referenced by data(), expand(), fillNodata(), GDALGrid(), update(), windowFill(), and windowFillCell().
int pdal::GDALGrid::m_outputTypes private
Definition at line 100 of file GDALGrid.hpp.
Referenced by data(), expand(), GDALGrid(), and numBands().
double pdal::GDALGrid::m_radius private
Definition at line 88 of file GDALGrid.hpp.
Referenced by addPoint().
DataPtr pdal::GDALGrid::m_stdDev private
Definition at line 96 of file GDALGrid.hpp.
Referenced by data(), expand(), fillNodata(), finalize(), GDALGrid(), update(), windowFill(), and windowFillCell().
size_t pdal::GDALGrid::m_width private
Definition at line 84 of file GDALGrid.hpp.
Referenced by addPoint(), expand(), and width().
size_t pdal::GDALGrid::m_windowSize private
Definition at line 86 of file GDALGrid.hpp.
Referenced by finalize(), and windowFill().
const int pdal::GDALGrid::statCount = 1 static
Definition at line 47 of file GDALGrid.hpp.
Referenced by data(), pdal::GDALWriter::initialize(), and numBands().
const int pdal::GDALGrid::statIdw = 32 static
Definition at line 52 of file GDALGrid.hpp.
Referenced by data(), expand(), GDALGrid(), pdal::GDALWriter::initialize(), and numBands().
const int pdal::GDALGrid::statMax = 4 static
Definition at line 49 of file GDALGrid.hpp.
Referenced by data(), expand(), GDALGrid(), pdal::GDALWriter::initialize(), and numBands().
const int pdal::GDALGrid::statMean = 8 static
Definition at line 50 of file GDALGrid.hpp.
Referenced by data(), expand(), GDALGrid(), pdal::GDALWriter::initialize(), and numBands().
const int pdal::GDALGrid::statMin = 2 static
Definition at line 48 of file GDALGrid.hpp.
Referenced by data(), expand(), GDALGrid(), pdal::GDALWriter::initialize(), and numBands().
const int pdal::GDALGrid::statStdDev = 16 static
Definition at line 51 of file GDALGrid.hpp.
Referenced by data(), expand(), GDALGrid(), pdal::GDALWriter::initialize(), and numBands().
The documentation for this class was generated from the following files:
pdal/io/GDALGrid.hpp
pdal/io/GDALGrid.cpp