PDAL: pdal::gdal::ErrorHandler Class Reference
pdal::gdal::ErrorHandler Class Reference
#include <GDALUtils.hpp>
Public Member Functions
void set (LogPtr log, bool doDebug)
void setLog (LogPtr log)
void setDebug (bool doDebug)
int errorNum ()
ErrorHandler ()
Static Public Member Functions
static ErrorHandler & getGlobalErrorHandler ()
static void CPL_STDCALL trampoline (::CPLErr code, int num, char const *msg)
Private Member Functions
void handle (::CPLErr level, int num, const char *msg)
Private Attributes
std::mutex m_mutex
bool m_debug
pdal::LogPtr m_log
int m_errorNum
bool m_cplSet
Detailed Description
Definition at line 212 of file GDALUtils.hpp.
Constructor & Destructor Documentation
pdal::gdal::ErrorHandler::ErrorHandler ()
Definition at line 264 of file GDALUtils.cpp.
References m_cplSet, m_debug, and trampoline().
Referenced by getGlobalErrorHandler().
Member Function Documentation
int pdal::gdal::ErrorHandler::errorNum ()
Get the last error and clear the error last error value.
Returns
The last error number.
Definition at line 303 of file GDALUtils.cpp.
References m_errorNum, and m_mutex.
ErrorHandler & pdal::gdal::ErrorHandler::getGlobalErrorHandler () static
Get the singleton error handler.
Returns
Reference to the error handler.
Definition at line 251 of file GDALUtils.cpp.
References ErrorHandler(), and pdal::gdal::s_gdalErrorHandler.
Referenced by pdal::Stage::setupLog(), pdal::Stage::startLogging(), and trampoline().
void pdal::gdal::ErrorHandler::handle (::CPLErr level, int num, const char * msg) private
Definition at line 309 of file GDALUtils.cpp.
References pdal::Debug, pdal::Error, m_debug, m_errorNum, m_log, and m_mutex.
Referenced by trampoline().
void pdal::gdal::ErrorHandler::set (LogPtr log, bool doDebug)
Set the log and debug state of the error handler. This is a convenience and is equivalent to calling setLog() and setDebug().
Parameters
log Log to write to.
doDebug Debug state of the error handler.
Definition at line 278 of file GDALUtils.cpp.
References setDebug(), and setLog().
Referenced by pdal::Stage::setupLog(), and pdal::Stage::startLogging().
void pdal::gdal::ErrorHandler::setDebug (bool doDebug)
Set the debug state of the error handler. Setting to true will also set the environment variable CPL_DEBUG to "ON". This will force GDAL to emit debug error messages which will be logged by this handler.
Parameters
doDebug Whether we're setting or clearing the debug state.
Definition at line 292 of file GDALUtils.cpp.
References m_debug, and m_mutex.
Referenced by set().
void pdal::gdal::ErrorHandler::setLog (LogPtr log)
Set the log to which error/debug messages should be written.
Parameters
log Log to write to.
Definition at line 285 of file GDALUtils.cpp.
References setup::log, m_log, and m_mutex.
Referenced by set().
static void CPL_STDCALL pdal::gdal::ErrorHandler::trampoline (::CPLErr code, int num, char const * msg) static
Definition at line 254 of file GDALUtils.hpp.
References getGlobalErrorHandler(), handle(), and setup::level.
Referenced by ErrorHandler().
Member Data Documentation
bool pdal::gdal::ErrorHandler::m_cplSet private
Definition at line 269 of file GDALUtils.hpp.
Referenced by ErrorHandler().
bool pdal::gdal::ErrorHandler::m_debug private
Definition at line 266 of file GDALUtils.hpp.
Referenced by ErrorHandler(), handle(), and setDebug().
int pdal::gdal::ErrorHandler::m_errorNum private
Definition at line 268 of file GDALUtils.hpp.
Referenced by errorNum(), and handle().
pdal::LogPtr pdal::gdal::ErrorHandler::m_log private
Definition at line 267 of file GDALUtils.hpp.
Referenced by handle(), and setLog().
std::mutex pdal::gdal::ErrorHandler::m_mutex private
Definition at line 265 of file GDALUtils.hpp.
Referenced by errorNum(), handle(), setDebug(), and setLog().
The documentation for this class was generated from the following files:
pdal/pdal/GDALUtils.hpp
pdal/pdal/GDALUtils.cpp