PDAL: pdal::KD3Index Class Reference
pdal::KD3Index Class Reference
#include <KDIndex.hpp>
Public Member Functions
KD3Index (const PointView &buf)
PointId neighbor (double x, double y, double z)
PointId neighbor (PointId idx)
PointId neighbor (PointRef &point)
std::vector< PointId > neighbors (double x, double y, double z, point_count_t k)
std::vector< PointId > neighbors (PointId idx, point_count_t k)
std::vector< PointId > neighbors (PointRef &point, point_count_t k)
void knnSearch (double x, double y, double z, point_count_t k, std::vector< PointId > *indices, std::vector< double > *sqr_dists)
void knnSearch (PointId idx, point_count_t k, std::vector< PointId > *indices, std::vector< double > *sqr_dists)
void knnSearch (PointRef &point, point_count_t k, std::vector< PointId > *indices, std::vector< double > *sqr_dists)
std::vector< PointId > radius (double x, double y, double z, double r) const
std::vector< PointId > radius (PointId idx, double r) const
std::vector< PointId > radius (PointRef &point, double r) const
std::size_t kdtree_get_point_count () const
double kdtree_get_pt (const PointId idx, int dim) const
double kdtree_distance (const double *p1, const PointId p2_idx, size_t) const
bool kdtree_get_bbox (BBOX &bb) const
void build ()
Protected Types
typedef nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< double, KDIndex, double >, KDIndex,-1, std::size_t > my_kd_tree_t
Protected Attributes
const PointView & m_buf
std::unique_ptr< my_kd_tree_t > m_index
Detailed Description
Definition at line 215 of file KDIndex.hpp.
Member Typedef Documentation
typedef nanoflann::KDTreeSingleIndexAdaptor<nanoflann::L2_Simple_Adaptor< double, KDIndex, double>, KDIndex, -1, std::size_t> pdal::KDIndex< DIM >::my_kd_tree_t protected inherited
Definition at line 83 of file KDIndex.hpp.
Constructor & Destructor Documentation
pdal::KD3Index::KD3Index (const PointView & buf)
Definition at line 218 of file KDIndex.hpp.
References pdal::PointView::hasDim(), X, Y, and Z.
Member Function Documentation
void pdal::KDIndex< DIM >::build () inherited
Definition at line 73 of file KDIndex.hpp.
double pdal::KDIndex< DIM >::kdtree_distance (const double * p1, const PointId p2_idx, size_t) const inherited
bool pdal::KDIndex< DIM >::kdtree_get_bbox (BBOX & bb) const inherited
std::size_t pdal::KDIndex< DIM >::kdtree_get_point_count () const inherited
Definition at line 66 of file KDIndex.hpp.
double pdal::KDIndex< DIM >::kdtree_get_pt (const PointId idx, int dim) const inherited
void pdal::KD3Index::knnSearch (double x, double y, double z, point_count_t k, std::vector< PointId > * indices, std::vector< double > * sqr_dists)
Definition at line 282 of file KDIndex.hpp.
Referenced by pdal::Utils::computeHausdorff(), pdal::KDistanceFilter::filter(), pdal::LOFFilter::filter(), pdal::GreedyProjection::filter(), and pdal::OutlierFilter::processStatistical().
void pdal::KD3Index::knnSearch (PointId idx, point_count_t k, std::vector< PointId > * indices, std::vector< double > * sqr_dists)
Definition at line 297 of file KDIndex.hpp.
References X, Y, Z, and z.
void pdal::KD3Index::knnSearch (PointRef & point, point_count_t k, std::vector< PointId > * indices, std::vector< double > * sqr_dists)
Definition at line 307 of file KDIndex.hpp.
References pdal::PointRef::getFieldAs(), X, Y, Z, and z.
PointId pdal::KD3Index::neighbor (double x, double y, double z)
Definition at line 228 of file KDIndex.hpp.
Referenced by pdal::DeltaKernel::dump(), pdal::DeltaKernel::dumpDetail(), and TEST().
PointId pdal::KD3Index::neighbor (PointId idx)
Definition at line 234 of file KDIndex.hpp.
PointId pdal::KD3Index::neighbor (PointRef & point)
Definition at line 240 of file KDIndex.hpp.
std::vector<PointId> pdal::KD3Index::neighbors (double x, double y, double z, point_count_t k)
Definition at line 246 of file KDIndex.hpp.
Referenced by pdal::InfoKernel::dumpQuery(), pdal::EigenvaluesFilter::filter(), pdal::EstimateRankFilter::filter(), pdal::ApproximateCoplanarFilter::filter(), pdal::NormalFilter::filter(), pdal::VoxelCenterNearestNeighborFilter::run(), pdal::VoxelCentroidNearestNeighborFilter::run(), and TEST().
std::vector<PointId> pdal::KD3Index::neighbors (PointId idx, point_count_t k)
Definition at line 264 of file KDIndex.hpp.
References X, Y, Z, and z.
std::vector<PointId> pdal::KD3Index::neighbors (PointRef & point, point_count_t k)
Definition at line 273 of file KDIndex.hpp.
References pdal::PointRef::getFieldAs(), X, Y, Z, and z.
std::vector<PointId> pdal::KD3Index::radius (double x, double y, double z, double r) const
Definition at line 317 of file KDIndex.hpp.
Referenced by pdal::Segmentation::extractClusters(), pdal::RadialDensityFilter::filter(), pdal::OutlierFilter::processRadius(), pdal::SampleFilter::run(), and TEST().
std::vector<PointId> pdal::KD3Index::radius (PointId idx, double r) const
Definition at line 339 of file KDIndex.hpp.
References anonymous_namespace{GreyhoundReaderTest.cpp}::radius, X, Y, Z, and z.
std::vector<PointId> pdal::KD3Index::radius (PointRef & point, double r) const
Definition at line 348 of file KDIndex.hpp.
References pdal::PointRef::getFieldAs(), anonymous_namespace{GreyhoundReaderTest.cpp}::radius, X, Y, Z, and z.
Member Data Documentation
const PointView& pdal::KDIndex< DIM >::m_buf protected inherited
Definition at line 80 of file KDIndex.hpp.
std::unique_ptr<my_kd_tree_t> pdal::KDIndex< DIM >::m_index protected inherited
Definition at line 85 of file KDIndex.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/KDIndex.hpp