PDAL: pdal::TIndexKernel Class Reference
pdal::TIndexKernel Class Reference
#include <TIndexKernel.hpp>
Classes
struct FieldIndexes
struct FileInfo
Public Member Functions
std::string getName () const
int execute ()
int run (const StringList &cmdArgs, LogPtr &log)
std::string getShortName () const
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
Protected Member Functions
Stage & makeReader (const std::string &inputFile, std::string driver)
Stage & makeReader (const std::string &inputFile, std::string driver, Options options)
Stage & makeFilter (const std::string &driver, Stage &parent)
Stage & makeFilter (const std::string &driver, Stage &parent, Options options)
Stage & makeFilter (const std::string &driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver, Options options)
virtual bool isStagePrefix (const std::string &stageType)
Protected Attributes
LogPtr m_log
PipelineManager m_manager
std::string m_driverOverride
Private Member Functions
TIndexKernel ()
virtual void addSwitches (ProgramArgs &args)
virtual void validateSwitches (ProgramArgs &args)
void createFile ()
void mergeFile ()
bool openDataset (const std::string &filename)
bool createDataset (const std::string &filename)
bool openLayer (const std::string &layerName)
bool createLayer (const std::string &layerName)
FieldIndexes getFields ()
FileInfo getFileInfo (StageFactory &factory, const std::string &filename)
bool createFeature (const FieldIndexes &indexes, FileInfo &info)
gdal::Geometry prepareGeometry (const FileInfo &fileInfo)
gdal::Geometry prepareGeometry (const std::string &wkt, const gdal::SpatialRef &inSrs, const gdal::SpatialRef &outSrs)
void createFields ()
bool isFileIndexed (const FieldIndexes &indexes, const FileInfo &fileInfo)
Private Attributes
std::string m_idxFilename
std::string m_filespec
StringList m_files
std::string m_layerName
std::string m_driverName
std::string m_tileIndexColumnName
std::string m_srsColumnName
std::string m_wkt
BOX2D m_bounds
bool m_merge
bool m_absPath
void * m_dataset
void * m_layer
std::string m_tgtSrsString
std::string m_assignSrsString
bool m_fastBoundary
bool m_usestdin
bool m_overrideASrs
Detailed Description
Definition at line 52 of file TIndexKernel.hpp.
Class Documentation
struct pdal::TIndexKernel::FieldIndexes
Definition at line 63 of file TIndexKernel.hpp.
Class Members
int m_ctime
int m_filename
int m_mtime
int m_srs
struct pdal::TIndexKernel::FileInfo
Definition at line 54 of file TIndexKernel.hpp.
Class Members
string m_boundary
struct tm m_ctime
string m_filename
struct tm m_mtime
string m_srs
Constructor & Destructor Documentation
pdal::TIndexKernel::TIndexKernel () private
Definition at line 71 of file TIndexKernel.cpp.
Member Function Documentation
void pdal::TIndexKernel::addSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 83 of file TIndexKernel.cpp.
References pdal::ProgramArgs::add(), m_absPath, m_assignSrsString, m_bounds, m_driverName, m_fastBoundary, m_filespec, m_idxFilename, m_layerName, m_merge, m_tgtSrsString, m_tileIndexColumnName, m_usestdin, m_wkt, and pdal::Arg::setPositional().
static void* pdal::TIndexKernel::create () static
bool pdal::TIndexKernel::createDataset (const std::string & filename) private
Definition at line 521 of file TIndexKernel.cpp.
References m_dataset, m_driverName, and pdal::FileUtils::toAbsolutePath().
Referenced by createFile().
bool pdal::TIndexKernel::createFeature (const FieldIndexes & indexes, FileInfo & info) private
Definition at line 380 of file TIndexKernel.cpp.
References m_assignSrsString, pdal::TIndexKernel::FileInfo::m_ctime, pdal::TIndexKernel::FieldIndexes::m_ctime, pdal::TIndexKernel::FileInfo::m_filename, pdal::TIndexKernel::FieldIndexes::m_filename, m_layer, pdal::Kernel::m_log, pdal::TIndexKernel::FileInfo::m_mtime, pdal::TIndexKernel::FieldIndexes::m_mtime, m_overrideASrs, pdal::TIndexKernel::FileInfo::m_srs, pdal::TIndexKernel::FieldIndexes::m_srs, prepareGeometry(), anonymous_namespace{TIndexKernel.cpp}::setDate(), and pdal::Warning.
Referenced by createFile().
void pdal::TIndexKernel::createFields () private
Definition at line 574 of file TIndexKernel.cpp.
References m_layer, m_srsColumnName, and m_tileIndexColumnName.
Referenced by createLayer().
void pdal::TIndexKernel::createFile () private
Definition at line 215 of file TIndexKernel.cpp.
References createDataset(), createFeature(), createLayer(), pdal::Error, pdal::georeference::anonymous_namespace{Georeference.cpp}::f, getFields(), getFileInfo(), pdal::FileUtils::glob(), pdal::Info, isFileIndexed(), m_absPath, m_dataset, m_files, m_filespec, m_idxFilename, m_layerName, pdal::Kernel::m_log, m_usestdin, openDataset(), openLayer(), pdal::readSTDIN(), and pdal::FileUtils::toAbsolutePath().
Referenced by execute().
bool pdal::TIndexKernel::createLayer (const std::string & layerName) private
Definition at line 550 of file TIndexKernel.cpp.
References createFields(), pdal::Error, m_dataset, m_layer, m_layerName, pdal::Kernel::m_log, and m_tgtSrsString.
Referenced by createFile().
static int32_t pdal::TIndexKernel::destroy (void *) static
int pdal::TIndexKernel::execute () virtual
Implements pdal::Kernel.
Definition at line 153 of file TIndexKernel.cpp.
References createFile(), m_dataset, m_merge, mergeFile(), and pdal::gdal::registerDrivers().
TIndexKernel::FieldIndexes pdal::TIndexKernel::getFields () private
Definition at line 597 of file TIndexKernel.cpp.
References pdal::TIndexKernel::FieldIndexes::m_ctime, pdal::TIndexKernel::FieldIndexes::m_filename, m_idxFilename, m_layer, pdal::TIndexKernel::FieldIndexes::m_mtime, pdal::TIndexKernel::FieldIndexes::m_srs, m_srsColumnName, and m_tileIndexColumnName.
Referenced by createFile(), and mergeFile().
TIndexKernel::FileInfo pdal::TIndexKernel::getFileInfo (StageFactory & factory, const std::string & filename) private
Definition at line 459 of file TIndexKernel.cpp.
References pdal::PipelineManager::commonOptions(), pdal::SpatialReference::empty(), pdal::Stage::execute(), pdal::FileUtils::fileTimes(), pdal::MetadataNode::findChild(), pdal::SpatialReference::getWKT(), pdal::TIndexKernel::FileInfo::m_boundary, pdal::QuickInfo::m_bounds, pdal::TIndexKernel::FileInfo::m_ctime, m_fastBoundary, pdal::TIndexKernel::FileInfo::m_filename, pdal::Kernel::m_manager, pdal::TIndexKernel::FileInfo::m_mtime, pdal::QuickInfo::m_srs, pdal::TIndexKernel::FileInfo::m_srs, pdal::PipelineManager::makeFilter(), pdal::PipelineManager::makeReader(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BasePointTable::metadata(), pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::Stage::prepare(), pdal::Stage::preview(), pdal::PipelineManager::stageOptions(), and pdal::MetadataNode::value().
Referenced by createFile().
std::string pdal::TIndexKernel::getName () const virtual
Implements pdal::Kernel.
Definition at line 69 of file TIndexKernel.cpp.
References pdal::PluginInfo::name.
std::string pdal::Kernel::getShortName () const inherited
Definition at line 67 of file Kernel.hpp.
References pdal::Utils::split2().
Referenced by pdal::Kernel::outputHelp().
bool pdal::TIndexKernel::isFileIndexed (const FieldIndexes & indexes, const FileInfo & fileInfo) private
Definition at line 188 of file TIndexKernel.cpp.
References pdal::TIndexKernel::FileInfo::m_filename, m_layer, m_tileIndexColumnName, and pdal::Utils::toupper().
Referenced by createFile().
bool pdal::Kernel::isStagePrefix (const std::string & stageType) protected virtual inherited
Reimplemented in pdal::PipelineKernel.
Definition at line 58 of file Kernel.cpp.
Referenced by pdal::PipelineKernel::isStagePrefix(), and pdal::Kernel::parseStageOption().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent) protected inherited
Definition at line 320 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::GroundKernel::execute(), and mergeFile().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent, Options options) protected inherited
Definition at line 326 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeFilter (const std::string & driver) protected inherited
Definition at line 314 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver) protected inherited
Definition at line 301 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), and mergeFile().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver, Options options) protected inherited
Definition at line 307 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver) protected inherited
Definition at line 333 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::GroundKernel::execute(), and mergeFile().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver, Options options) protected inherited
Definition at line 340 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
void pdal::TIndexKernel::mergeFile () private
Definition at line 280 of file TIndexKernel.cpp.
References pdal::Options::add(), pdal::BOX2D::empty(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, getFields(), m_bounds, pdal::Kernel::m_driverOverride, pdal::TIndexKernel::FileInfo::m_filename, m_filespec, m_idxFilename, m_layer, m_layerName, pdal::TIndexKernel::FileInfo::m_srs, m_tgtSrsString, m_wkt, pdal::Kernel::makeFilter(), pdal::Kernel::makeReader(), pdal::Kernel::makeWriter(), openDataset(), openLayer(), pdal::Stage::prepare(), pdal::Stage::setInput(), and writerOptions().
Referenced by execute().
bool pdal::TIndexKernel::openDataset (const std::string & filename) private
Definition at line 514 of file TIndexKernel.cpp.
References m_dataset.
Referenced by createFile(), and mergeFile().
bool pdal::TIndexKernel::openLayer (const std::string & layerName) private
Definition at line 539 of file TIndexKernel.cpp.
References m_dataset, m_layer, and m_layerName.
Referenced by createFile(), and mergeFile().
gdal::Geometry pdal::TIndexKernel::prepareGeometry (const FileInfo & fileInfo) private
Definition at line 638 of file TIndexKernel.cpp.
References pdal::TIndexKernel::FileInfo::m_boundary, pdal::TIndexKernel::FileInfo::m_filename, pdal::TIndexKernel::FileInfo::m_srs, and m_tgtSrsString.
Referenced by createFeature().
gdal::Geometry pdal::TIndexKernel::prepareGeometry (const std::string & wkt, const gdal::SpatialRef & inSrs, const gdal::SpatialRef & outSrs) private
Definition at line 671 of file TIndexKernel.cpp.
References pdal::gdal::SpatialRef::get(), and pdal::gdal::Geometry::get().
int pdal::Kernel::run (const StringList & cmdArgs, LogPtr & log) inherited
Definition at line 229 of file Kernel.cpp.
References pdal::Kernel::doExecution(), pdal::Kernel::doStartup(), pdal::Kernel::doSwitches(), setup::log, pdal::Kernel::m_log, pdal::Kernel::m_manager, pdal::Kernel::m_showHelp, pdal::Kernel::outputHelp(), pdal::Utils::printError(), and pdal::PipelineManager::setLog().
Referenced by App::execute().
void pdal::TIndexKernel::validateSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 112 of file TIndexKernel.cpp.
References pdal::BOX2D::empty(), m_bounds, m_filespec, m_merge, m_overrideASrs, m_usestdin, m_wkt, pdal::ProgramArgs::set(), and pdal::BOX2D::toWKT().
Member Data Documentation
bool pdal::TIndexKernel::m_absPath private
Definition at line 108 of file TIndexKernel.hpp.
Referenced by addSwitches(), and createFile().
std::string pdal::TIndexKernel::m_assignSrsString private
Definition at line 113 of file TIndexKernel.hpp.
Referenced by addSwitches(), and createFeature().
BOX2D pdal::TIndexKernel::m_bounds private
Definition at line 106 of file TIndexKernel.hpp.
Referenced by addSwitches(), mergeFile(), and validateSwitches().
void* pdal::TIndexKernel::m_dataset private
Definition at line 110 of file TIndexKernel.hpp.
Referenced by createDataset(), createFile(), createLayer(), execute(), openDataset(), and openLayer().
std::string pdal::TIndexKernel::m_driverName private
Definition at line 102 of file TIndexKernel.hpp.
Referenced by addSwitches(), and createDataset().
std::string pdal::Kernel::m_driverOverride protected inherited
Definition at line 105 of file Kernel.hpp.
Referenced by pdal::Kernel::addBasicSwitches(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::DiffKernel::execute(), pdal::DeltaKernel::loadSet(), pdal::InfoKernel::makePipeline(), and mergeFile().
bool pdal::TIndexKernel::m_fastBoundary private
Definition at line 114 of file TIndexKernel.hpp.
Referenced by addSwitches(), and getFileInfo().
StringList pdal::TIndexKernel::m_files private
Definition at line 100 of file TIndexKernel.hpp.
Referenced by createFile().
std::string pdal::TIndexKernel::m_filespec private
Definition at line 99 of file TIndexKernel.hpp.
Referenced by addSwitches(), createFile(), mergeFile(), and validateSwitches().
std::string pdal::TIndexKernel::m_idxFilename private
Definition at line 98 of file TIndexKernel.hpp.
Referenced by addSwitches(), createFile(), getFields(), and mergeFile().
void* pdal::TIndexKernel::m_layer private
Definition at line 111 of file TIndexKernel.hpp.
Referenced by createFeature(), createFields(), createLayer(), getFields(), isFileIndexed(), mergeFile(), and openLayer().
std::string pdal::TIndexKernel::m_layerName private
Definition at line 101 of file TIndexKernel.hpp.
Referenced by addSwitches(), createFile(), createLayer(), mergeFile(), and openLayer().
LogPtr pdal::Kernel::m_log protected inherited
Definition at line 103 of file Kernel.hpp.
Referenced by createFeature(), createFile(), createLayer(), pdal::InfoKernel::dumpPoints(), pdal::TranslateKernel::execute(), and pdal::Kernel::run().
PipelineManager pdal::Kernel::m_manager protected inherited
Definition at line 104 of file Kernel.hpp.
Referenced by pdal::Kernel::doSwitches(), pdal::InfoKernel::dump(), pdal::SmoothKernel::execute(), pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), pdal::TranslateKernel::execute(), getFileInfo(), pdal::TranslateKernel::makeArgPipeline(), pdal::Kernel::makeFilter(), pdal::TranslateKernel::makeJSONPipeline(), pdal::InfoKernel::makePipeline(), pdal::Kernel::makeReader(), pdal::Kernel::makeWriter(), pdal::InfoKernel::run(), pdal::Kernel::run(), and pdal::InfoKernel::setup().
bool pdal::TIndexKernel::m_merge private
Definition at line 107 of file TIndexKernel.hpp.
Referenced by addSwitches(), execute(), and validateSwitches().
bool pdal::TIndexKernel::m_overrideASrs private
Definition at line 116 of file TIndexKernel.hpp.
Referenced by createFeature(), and validateSwitches().
std::string pdal::TIndexKernel::m_srsColumnName private
Definition at line 104 of file TIndexKernel.hpp.
Referenced by createFields(), and getFields().
std::string pdal::TIndexKernel::m_tgtSrsString private
Definition at line 112 of file TIndexKernel.hpp.
Referenced by addSwitches(), createLayer(), mergeFile(), and prepareGeometry().
std::string pdal::TIndexKernel::m_tileIndexColumnName private
Definition at line 103 of file TIndexKernel.hpp.
Referenced by addSwitches(), createFields(), getFields(), and isFileIndexed().
bool pdal::TIndexKernel::m_usestdin private
Definition at line 115 of file TIndexKernel.hpp.
Referenced by addSwitches(), createFile(), and validateSwitches().
std::string pdal::TIndexKernel::m_wkt private
Definition at line 105 of file TIndexKernel.hpp.
Referenced by addSwitches(), mergeFile(), and validateSwitches().
The documentation for this class was generated from the following files:
pdal/kernels/TIndexKernel.hpp
pdal/kernels/TIndexKernel.cpp