PDAL: pdal::PointRef Class Reference
pdal::PointRef Class Reference
#include <PointRef.hpp>
Public Member Functions
PointRef (PointContainer &container, PointId idx)
bool hasDim (Dimension::Id dim) const
template<class T >
T getFieldAs (Dimension::Id dim) const
template<typename T >
void setField (Dimension::Id dim, T val)
void setPointId (PointId idx)
PointId pointId () const
void getField (char *val, Dimension::Id d, Dimension::Type type) const
void setField (Dimension::Id dim, Dimension::Type type, const void *val)
void getPackedData (const DimTypeList &dims, char *buf) const
void setPackedData (const DimTypeList &dims, const char *buf)
Private Attributes
PointContainer & m_container
PointLayout & m_layout
PointId m_idx
Detailed Description
Definition at line 45 of file PointRef.hpp.
Constructor & Destructor Documentation
pdal::PointRef::PointRef (PointContainer & container, PointId idx)
Definition at line 48 of file PointRef.hpp.
Member Function Documentation
void pdal::PointRef::getField (char * val, Dimension::Id d, Dimension::Type type) const
Definition at line 202 of file PointRef.hpp.
References pdal::Everything::d, pdal::Dimension::Double, pdal::Everything::f, pdal::Dimension::Float, pdal::Dimension::None, pdal::Everything::s16, pdal::Everything::s32, pdal::Everything::s64, pdal::Everything::s8, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::size(), pdal::Everything::u16, pdal::Everything::u32, pdal::Everything::u64, pdal::Everything::u8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
Referenced by pdal::LasWriter::fillPointBuf(), pdal::LasWriter::writeLasZipBuf(), and pdal::PlyWriter::writeValue().
template<class T > T pdal::PointRef::getFieldAs (Dimension::Id dim) const
Definition at line 56 of file PointRef.hpp.
References pdal::Everything::d, pdal::Dimension::Double, pdal::Everything::f, pdal::Dimension::Float, pdal::Dimension::interpretationName(), pdal::Dimension::name(), pdal::Dimension::None, pdal::Utils::numericCast(), pdal::Everything::s16, pdal::Everything::s32, pdal::Everything::s64, pdal::Everything::s8, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Utils::toDouble(), pdal::Dimension::type(), pdal::Everything::u16, pdal::Everything::u32, pdal::Everything::u64, pdal::Everything::u8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
Referenced by pdal::Polygon::covers(), pdal::CropFilter::crop(), pdal::LasWriter::fillPointBuf(), pdal::HAGFilter::filter(), pdal::NormalFilter::filter(), pdal::Segmentation::ignoreDimRange(), pdal::KD3Index::knnSearch(), pdal::KD2Index::neighbors(), pdal::KD3Index::neighbors(), pdal::AssignFilter::processOne(), pdal::ReprojectionFilter::processOne(), pdal::GDALWriter::processOne(), pdal::RangeFilter::processOne(), pdal::TransformationFilter::processOne(), pdal::OGRWriter::processOne(), pdal::FerryFilter::processOne(), pdal::ColorinterpFilter::processOne(), pdal::ColorizationFilter::processOne(), pdal::StatsFilter::processOne(), pdal::KD2Index::radius(), pdal::KD3Index::radius(), pdal::Ilvis2Reader::readPoint(), pdal::Segmentation::segmentLastReturns(), pdal::TEST(), anonymous_namespace{BPFTest.cpp}::test_file_type_stream(), pdal::LasWriter::writeLasZipBuf(), and pdal::PlyWriter::writeValue().
void pdal::PointRef::getPackedData (const DimTypeList & dims, char * buf) const
Fill a buffer with point data specified by the dimension list.
Parameters
[in] dims List of dimensions/types to retrieve.
[in] idx Index of point to get.
[in] buf Pointer to buffer to fill.
Definition at line 172 of file PointRef.hpp.
References pdal::Dimension::size().
Referenced by streamTest().
bool pdal::PointRef::hasDim (Dimension::Id dim) const
Definition at line 52 of file PointRef.hpp.
Referenced by pdal::LasWriter::fillPointBuf(), and pdal::LasWriter::writeLasZipBuf().
PointId pdal::PointRef::pointId () const
Definition at line 161 of file PointRef.hpp.
References pdal::Dimension::type().
Referenced by pdal::PlyReader::readElement().
template<typename T > void pdal::PointRef::setField (Dimension::Id dim, T val)
Definition at line 114 of file PointRef.hpp.
References pdal::Everything::d, pdal::Dimension::Double, pdal::Everything::f, pdal::Dimension::Float, pdal::Dimension::None, pdal::Utils::numericCast(), pdal::Everything::s16, pdal::Everything::s32, pdal::Everything::s64, pdal::Everything::s8, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::type(), pdal::Everything::u16, pdal::Everything::u32, pdal::Everything::u64, pdal::Everything::u8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
Referenced by pdal::OverlayFilter::filter(), pdal::LasReader::loadExtraDims(), pdal::LasReader::loadPoint(), pdal::LasReader::loadPointV10(), pdal::LasReader::loadPointV14(), pdal::AssignFilter::processOne(), pdal::SbetReader::processOne(), pdal::ReprojectionFilter::processOne(), pdal::TransformationFilter::processOne(), pdal::FerryFilter::processOne(), pdal::ColorinterpFilter::processOne(), pdal::OverlayFilter::processOne(), pdal::MbReader::processOne(), pdal::ColorizationFilter::processOne(), pdal::MatlabReader::processOne(), pdal::TextReader::processOne(), pdal::FauxReader::processOne(), pdal::PlyReader::SimpleProperty::read(), pdal::BpfReader::readByteMajor(), pdal::BpfReader::readDimMajor(), pdal::Ilvis2Reader::readPoint(), pdal::BpfReader::readPointMajor(), and TEST().
void pdal::PointRef::setField (Dimension::Id dim, Dimension::Type type, const void * val)
Definition at line 245 of file PointRef.hpp.
References pdal::Everything::d, pdal::Dimension::Double, pdal::Everything::f, pdal::Dimension::Float, pdal::Dimension::None, pdal::Everything::s16, pdal::Everything::s32, pdal::Everything::s64, pdal::Everything::s8, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::size(), pdal::Everything::u16, pdal::Everything::u32, pdal::Everything::u64, pdal::Everything::u8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
void pdal::PointRef::setPackedData (const DimTypeList & dims, const char * buf)
Load the point buffer from memory whose arrangement is specified by the dimension list.
Parameters
[in] dims Dimension/types of data in packed order
[in] idx Index of point to write.
[in] buf Packed data buffer.
Definition at line 186 of file PointRef.hpp.
References pdal::Dimension::size().
void pdal::PointRef::setPointId (PointId idx)
Definition at line 159 of file PointRef.hpp.
Referenced by pdal::CropFilter::crop(), pdal::PlyWriter::done(), pdal::Stage::execute(), pdal::LasWriter::fillWriteBuf(), pdal::AssignFilter::filter(), pdal::StreamCallbackFilter::filter(), pdal::TransformationFilter::filter(), pdal::FerryFilter::filter(), pdal::ColorinterpFilter::filter(), pdal::OverlayFilter::filter(), pdal::ColorizationFilter::filter(), pdal::StatsFilter::filter(), pdal::Segmentation::ignoreDimRange(), pdal::MbReader::read(), pdal::MatlabReader::read(), pdal::TextReader::read(), pdal::Ilvis2Reader::read(), pdal::PlyReader::read(), pdal::Segmentation::segmentLastReturns(), pdal::GDALWriter::writeView(), pdal::OGRWriter::writeView(), and pdal::LasWriter::writeView().
Member Data Documentation
PointContainer& pdal::PointRef::m_container private
Definition at line 197 of file PointRef.hpp.
PointId pdal::PointRef::m_idx private
Definition at line 199 of file PointRef.hpp.
PointLayout& pdal::PointRef::m_layout private
Definition at line 198 of file PointRef.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/PointRef.hpp