PDAL: pdal::SQLite Class Reference
pdal::SQLite Class Reference
#include <SQLiteCommon.hpp>
Public Member Functions
SQLite (std::string const &connection, LogPtr log)
~SQLite ()
void connect (bool bWrite=false)
void execute (std::string const &sql)
void begin ()
void commit ()
void query (std::string const &query)
bool next ()
const row * get () const
std::map< std::string, int32_t > const & columns () const
std::vector< std::string > const & types () const
int64_t last_row_id () const
void insert (std::string const &statement, records const &rs)
bool loadSpatialite (const std::string &module_name="")
bool haveSpatialite ()
void initSpatialiteMetadata ()
bool doesTableExist (std::string const &name)
std::string getSpatialiteVersion ()
std::string getSQLiteVersion ()
LogPtr log ()
Static Public Member Functions
static void log_callback (void *p, int num, char const *msg)
Private Member Functions
void error (std::string const &userMssg, std::string const &func)
void checkSession ()
Private Attributes
pdal::LogPtr m_log
std::string m_connection
sqlite3 * m_session
sqlite3_stmt * m_statement
records m_data
records::size_type m_position
std::map< std::string, int32_t > m_columns
std::vector< std::string > m_types
Detailed Description
Definition at line 123 of file SQLiteCommon.hpp.
Constructor & Destructor Documentation
pdal::SQLite::SQLite (std::string const & connection, LogPtr log)
Definition at line 126 of file SQLiteCommon.hpp.
References pdal::Debug3.
pdal::SQLite::~SQLite ()
Definition at line 141 of file SQLiteCommon.hpp.
Member Function Documentation
void pdal::SQLite::begin ()
Definition at line 211 of file SQLiteCommon.hpp.
void pdal::SQLite::checkSession () private
Definition at line 575 of file SQLiteCommon.hpp.
std::map<std::string, int32_t> const& pdal::SQLite::columns () const
Definition at line 355 of file SQLiteCommon.hpp.
void pdal::SQLite::commit ()
Definition at line 216 of file SQLiteCommon.hpp.
void pdal::SQLite::connect (bool bWrite = false)
Definition at line 165 of file SQLiteCommon.hpp.
References pdal::Debug3, and flags.
Referenced by TEST().
bool pdal::SQLite::doesTableExist (std::string const & name)
Definition at line 511 of file SQLiteCommon.hpp.
References c, pdal::column::data, and pdal::Utils::iequals().
Referenced by TEST().
void pdal::SQLite::error (std::string const & userMssg, std::string const & func) private
Definition at line 563 of file SQLiteCommon.hpp.
void pdal::SQLite::execute (std::string const & sql)
Definition at line 191 of file SQLiteCommon.hpp.
References pdal::Debug3, and pdal::Utils::trimTrailing().
Referenced by TEST().
const row* pdal::SQLite::get () const
Definition at line 347 of file SQLiteCommon.hpp.
Referenced by pdal::SQLiteReader::getSession(), and TEST().
std::string pdal::SQLite::getSpatialiteVersion ()
Definition at line 532 of file SQLiteCommon.hpp.
Referenced by TEST().
std::string pdal::SQLite::getSQLiteVersion ()
Definition at line 544 of file SQLiteCommon.hpp.
Referenced by TEST().
bool pdal::SQLite::haveSpatialite ()
Definition at line 501 of file SQLiteCommon.hpp.
Referenced by TEST().
void pdal::SQLite::initSpatialiteMetadata ()
Definition at line 506 of file SQLiteCommon.hpp.
Referenced by TEST().
void pdal::SQLite::insert (std::string const & statement, records const & rs)
Definition at line 371 of file SQLiteCommon.hpp.
References pdal::column::blobBuf, pdal::column::blobLen, c, pdal::column::data, pdal::Debug3, and pdal::column::null.
int64_t pdal::SQLite::last_row_id () const
Definition at line 366 of file SQLiteCommon.hpp.
bool pdal::SQLite::loadSpatialite (const std::string & module_name = "")
Definition at line 445 of file SQLiteCommon.hpp.
References pdal::Debug3.
Referenced by TEST().
LogPtr pdal::SQLite::log ()
Definition at line 551 of file SQLiteCommon.hpp.
Referenced by log_callback().
static void pdal::SQLite::log_callback (void * p, int num, char const * msg) static
Definition at line 156 of file SQLiteCommon.hpp.
References pdal::Debug, and log().
bool pdal::SQLite::next ()
Definition at line 338 of file SQLiteCommon.hpp.
Referenced by TEST().
void pdal::SQLite::query (std::string const & query)
Definition at line 234 of file SQLiteCommon.hpp.
References pdal::column::blobBuf, pdal::column::blobLen, c, pdal::column::data, pdal::Debug3, pdal::column::null, and pdal::Utils::toupper().
Referenced by TEST().
std::vector<std::string> const& pdal::SQLite::types () const
Definition at line 360 of file SQLiteCommon.hpp.
Member Data Documentation
std::map<std::string, int32_t> pdal::SQLite::m_columns private
Definition at line 560 of file SQLiteCommon.hpp.
std::string pdal::SQLite::m_connection private
Definition at line 555 of file SQLiteCommon.hpp.
records pdal::SQLite::m_data private
Definition at line 558 of file SQLiteCommon.hpp.
pdal::LogPtr pdal::SQLite::m_log private
Definition at line 551 of file SQLiteCommon.hpp.
records::size_type pdal::SQLite::m_position private
Definition at line 559 of file SQLiteCommon.hpp.
sqlite3* pdal::SQLite::m_session private
Definition at line 556 of file SQLiteCommon.hpp.
sqlite3_stmt* pdal::SQLite::m_statement private
Definition at line 557 of file SQLiteCommon.hpp.
std::vector<std::string> pdal::SQLite::m_types private
Definition at line 561 of file SQLiteCommon.hpp.
The documentation for this class was generated from the following file:
pdal/plugins/sqlite/io/SQLiteCommon.hpp