PDAL: pdal::PipelineManager Class Reference
pdal::PipelineManager Class Reference
#include <PipelineManager.hpp>
Public Member Functions
PipelineManager ()
~PipelineManager ()
void setProgressFd (int fd)
void readPipeline (std::istream &input)
void readPipeline (const std::string &filename)
Stage & addReader (const std::string &type)
Stage & addFilter (const std::string &type)
Stage & addWriter (const std::string &type)
Stage & makeReader (const std::string &inputFile, std::string driver)
Stage & makeReader (const std::string &inputFile, std::string driver, Options options)
Stage & makeReader (StageCreationOptions &opts)
Stage & makeFilter (const std::string &driver)
Stage & makeFilter (const std::string &driver, Options options)
Stage & makeFilter (const std::string &driver, Stage &parent)
Stage & makeFilter (const std::string &driver, Stage &parent, Options options)
Stage & makeFilter (StageCreationOptions &ops)
Stage & makeWriter (const std::string &outputFile, std::string driver)
Stage & makeWriter (const std::string &outputFile, std::string driver, Options options)
Stage & makeWriter (const std::string &outputFile, std::string driver, Stage &parent)
Stage & makeWriter (const std::string &outputFile, std::string driver, Stage &parent, Options options)
Stage & makeWriter (StageCreationOptions &ops)
bool isWriterPipeline () const
Stage * getStage () const
void setLog (LogPtr &log)
QuickInfo preview () const
void prepare () const
point_count_t execute ()
void executeStream (FixedPointTable &table)
void validateStageOptions () const
const PointViewSet & views () const
PointTableRef pointTable () const
MetadataNode getMetadata () const
Options & commonOptions ()
OptionsMap & stageOptions ()
std::vector< Stage * > roots () const
std::vector< Stage * > leaves () const
void replace (Stage *sOld, Stage *sNew)
const std::vector< Stage * > stages () const
Private Member Functions
FRIEND_TEST (json, tags)
void setOptions (Stage &stage, const Options &addOps)
Options stageOptions (Stage &stage)
PipelineManager & operator= (const PipelineManager &)
PipelineManager (const PipelineManager &)
Private Attributes
StageFactory m_factory
std::unique_ptr< PointTable > m_tablePtr
PointTableRef m_table
Options m_commonOptions
OptionsMap m_stageOptions
PointViewSet m_viewSet
std::vector< Stage * > m_stages
int m_progressFd
std::istream * m_input
LogPtr m_log
Detailed Description
Definition at line 57 of file PipelineManager.hpp.
Constructor & Destructor Documentation
pdal::PipelineManager::PipelineManager ()
Definition at line 61 of file PipelineManager.hpp.
pdal::PipelineManager::~PipelineManager ()
Definition at line 48 of file PipelineManager.cpp.
References pdal::Utils::closeFile(), and m_input.
pdal::PipelineManager::PipelineManager (const PipelineManager &) private
Member Function Documentation
Stage & pdal::PipelineManager::addFilter (const std::string & type)
Definition at line 108 of file PipelineManager.cpp.
References pdal::StageFactory::createStage(), hag::filter(), m_factory, m_log, m_progressFd, m_stages, pdal::Stage::setLog(), and pdal::Stage::setProgressFd().
Referenced by makeFilter(), and TEST().
Stage & pdal::PipelineManager::addReader (const std::string & type)
Definition at line 92 of file PipelineManager.cpp.
References pdal::StageFactory::createStage(), m_factory, m_log, m_progressFd, m_stages, pdal::Stage::setLog(), and pdal::Stage::setProgressFd().
Referenced by makeReader(), and TEST().
Stage & pdal::PipelineManager::addWriter (const std::string & type)
Definition at line 124 of file PipelineManager.cpp.
References pdal::StageFactory::createStage(), m_factory, m_log, m_progressFd, m_stages, pdal::Stage::setLog(), and pdal::Stage::setProgressFd().
Referenced by makeWriter(), and TEST().
Options& pdal::PipelineManager::commonOptions ()
Definition at line 128 of file PipelineManager.hpp.
Referenced by pdal::SmoothKernel::execute(), and pdal::TIndexKernel::getFileInfo().
point_count_t pdal::PipelineManager::execute ()
Definition at line 184 of file PipelineManager.cpp.
References pdal::Stage::execute(), getStage(), m_table, m_viewSet, and prepare().
Referenced by pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), pdal::TranslateKernel::execute(), pdal::PipelineExecutor::execute(), pdal::InfoKernel::run(), TEST(), and TEST_F().
void pdal::PipelineManager::executeStream (FixedPointTable & table)
Definition at line 202 of file PipelineManager.cpp.
References pdal::Stage::execute(), getStage(), pdal::Stage::prepare(), and validateStageOptions().
Referenced by pdal::PipelineKernel::execute().
pdal::PipelineManager::FRIEND_TEST (json , tags) private
MetadataNode pdal::PipelineManager::getMetadata () const
Definition at line 214 of file PipelineManager.cpp.
References pdal::MetadataNode::add(), and m_stages.
Referenced by pdal::InfoKernel::dump(), pdal::PipelineKernel::execute(), pdal::TranslateKernel::execute(), and pdal::PipelineExecutor::getMetadata().
Stage* pdal::PipelineManager::getStage () const
Definition at line 106 of file PipelineManager.hpp.
Referenced by pdal::InfoKernel::dump(), pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), pdal::TranslateKernel::execute(), execute(), executeStream(), pdal::PipelineExecutor::getPipeline(), pdal::InfoKernel::makePipeline(), prepare(), and preview().
bool pdal::PipelineManager::isWriterPipeline () const
Definition at line 101 of file PipelineManager.hpp.
std::vector< Stage * > pdal::PipelineManager::leaves () const
Definition at line 414 of file PipelineManager.cpp.
References pdal::Stage::getInputs(), m_stages, and pdal::Utils::remove().
Referenced by pdal::TranslateKernel::makeJSONPipeline().
Stage & pdal::PipelineManager::makeFilter (const std::string & driver)
Definition at line 263 of file PipelineManager.cpp.
Referenced by pdal::SmoothKernel::execute(), pdal::DensityKernel::execute(), pdal::TIndexKernel::getFileInfo(), pdal::TranslateKernel::makeArgPipeline(), pdal::Kernel::makeFilter(), makeFilter(), pdal::PipelineReaderJSON::parsePipeline(), pdal::InfoKernel::setup(), and TEST().
Stage & pdal::PipelineManager::makeFilter (const std::string & driver, Options options)
Definition at line 271 of file PipelineManager.cpp.
References makeFilter().
Stage & pdal::PipelineManager::makeFilter (const std::string & driver, Stage & parent)
Definition at line 279 of file PipelineManager.cpp.
References makeFilter().
Stage & pdal::PipelineManager::makeFilter (const std::string & driver, Stage & parent, Options options)
Definition at line 287 of file PipelineManager.cpp.
References makeFilter().
Stage & pdal::PipelineManager::makeFilter (StageCreationOptions & ops)
Definition at line 296 of file PipelineManager.cpp.
References addFilter(), hag::filter(), pdal::StageCreationOptions::m_driver, pdal::StageCreationOptions::m_options, pdal::StageCreationOptions::m_parent, pdal::StageCreationOptions::m_tag, pdal::Stage::setInput(), setOptions(), and pdal::Stage::setTag().
Stage & pdal::PipelineManager::makeReader (const std::string & inputFile, std::string driver)
Definition at line 226 of file PipelineManager.cpp.
Referenced by pdal::SmoothKernel::execute(), pdal::DensityKernel::execute(), pdal::TIndexKernel::getFileInfo(), pdal::TranslateKernel::makeArgPipeline(), pdal::TranslateKernel::makeJSONPipeline(), pdal::InfoKernel::makePipeline(), pdal::Kernel::makeReader(), makeReader(), pdal::PipelineReaderJSON::parsePipeline(), and TEST().
Stage & pdal::PipelineManager::makeReader (const std::string & inputFile, std::string driver, Options options)
Definition at line 235 of file PipelineManager.cpp.
References makeReader().
Stage & pdal::PipelineManager::makeReader (StageCreationOptions & opts)
Definition at line 244 of file PipelineManager.cpp.
References addReader(), pdal::StageFactory::inferReaderDriver(), pdal::StageCreationOptions::m_driver, pdal::StageCreationOptions::m_filename, pdal::StageCreationOptions::m_options, pdal::StageCreationOptions::m_tag, pdal::Options::replace(), setOptions(), and pdal::Stage::setTag().
Stage & pdal::PipelineManager::makeWriter (const std::string & outputFile, std::string driver)
Definition at line 307 of file PipelineManager.cpp.
Referenced by pdal::TranslateKernel::makeArgPipeline(), pdal::TranslateKernel::makeJSONPipeline(), pdal::Kernel::makeWriter(), makeWriter(), pdal::PipelineReaderJSON::parsePipeline(), TEST(), and pdal::MongusFilter::writeControl().
Stage & pdal::PipelineManager::makeWriter (const std::string & outputFile, std::string driver, Options options)
Definition at line 334 of file PipelineManager.cpp.
References makeWriter().
Stage & pdal::PipelineManager::makeWriter (const std::string & outputFile, std::string driver, Stage & parent)
Definition at line 316 of file PipelineManager.cpp.
References makeWriter().
Stage & pdal::PipelineManager::makeWriter (const std::string & outputFile, std::string driver, Stage & parent, Options options)
Definition at line 325 of file PipelineManager.cpp.
References makeWriter().
Stage & pdal::PipelineManager::makeWriter (StageCreationOptions & ops)
Definition at line 343 of file PipelineManager.cpp.
References addWriter(), pdal::StageFactory::inferWriterDriver(), pdal::StageCreationOptions::m_driver, pdal::StageCreationOptions::m_filename, pdal::StageCreationOptions::m_options, pdal::StageCreationOptions::m_parent, pdal::StageCreationOptions::m_tag, pdal::Options::replace(), and setOptions().
PipelineManager& pdal::PipelineManager::operator= (const PipelineManager &) private
PointTableRef pdal::PipelineManager::pointTable () const
Definition at line 124 of file PipelineManager.hpp.
Referenced by pdal::InfoKernel::dump(), pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), pdal::PipelineExecutor::getSchema(), and TEST().
void pdal::PipelineManager::prepare () const
Definition at line 175 of file PipelineManager.cpp.
References getStage(), m_table, pdal::Stage::prepare(), and validateStageOptions().
Referenced by pdal::PipelineKernel::execute(), execute(), pdal::InfoKernel::run(), and pdal::PipelineExecutor::validate().
QuickInfo pdal::PipelineManager::preview () const
Definition at line 163 of file PipelineManager.cpp.
References getStage(), pdal::Stage::preview(), and validateStageOptions().
void pdal::PipelineManager::readPipeline (std::istream & input)
Definition at line 54 of file PipelineManager.cpp.
References pdal::PipelineReaderJSON::readPipeline().
Referenced by pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), pdal::PipelineExecutor::execute(), pdal::TranslateKernel::makeJSONPipeline(), pdal::InfoKernel::makePipeline(), readPipeline(), TEST(), pdal::TEST(), TEST_F(), and pdal::PipelineExecutor::validate().
void pdal::PipelineManager::readPipeline (const std::string & filename)
Definition at line 66 of file PipelineManager.cpp.
References pdal::Utils::closeFile(), pdal::FileUtils::extension(), m_input, pdal::Utils::openFile(), pdal::PipelineReaderJSON::readPipeline(), and readPipeline().
void pdal::PipelineManager::replace (Stage * sOld, Stage * sNew)
Definition at line 424 of file PipelineManager.cpp.
References pdal::Stage::getInputs(), m_stages, pdal::Utils::remove(), and pdal::Stage::setInput().
Referenced by pdal::TranslateKernel::makeJSONPipeline(), and TEST().
std::vector< Stage * > pdal::PipelineManager::roots () const
Definition at line 403 of file PipelineManager.cpp.
References m_stages.
Referenced by pdal::TranslateKernel::makeJSONPipeline().
void pdal::PipelineManager::setLog (LogPtr & log)
Definition at line 110 of file PipelineManager.hpp.
References setup::log.
Referenced by pdal::Kernel::run(), pdal::PipelineExecutor::setLogStream(), and TEST().
void pdal::PipelineManager::setOptions (Stage & stage, const Options & addOps) private
Definition at line 365 of file PipelineManager.cpp.
References pdal::Stage::addOptions(), m_commonOptions, pdal::Stage::removeOptions(), pdal::Stage::setOptions(), and stageOptions().
Referenced by makeFilter(), makeReader(), and makeWriter().
void pdal::PipelineManager::setProgressFd (int fd)
Definition at line 66 of file PipelineManager.hpp.
References addFilter, and pdal::Dimension::type().
Referenced by pdal::PipelineKernel::execute().
OptionsMap& pdal::PipelineManager::stageOptions ()
Definition at line 130 of file PipelineManager.hpp.
Referenced by pdal::Kernel::doSwitches(), pdal::SmoothKernel::execute(), pdal::TIndexKernel::getFileInfo(), and setOptions().
Options pdal::PipelineManager::stageOptions (Stage & stage) private
Definition at line 382 of file PipelineManager.cpp.
References pdal::Options::add(), pdal::Options::addConditional(), pdal::Stage::getName(), m_stageOptions, and pdal::Stage::tag().
const std::vector<Stage *> pdal::PipelineManager::stages () const
Definition at line 136 of file PipelineManager.hpp.
void pdal::PipelineManager::validateStageOptions () const
Definition at line 140 of file PipelineManager.cpp.
References m_stageOptions, and m_stages.
Referenced by executeStream(), prepare(), and preview().
const PointViewSet& pdal::PipelineManager::views () const
Definition at line 120 of file PipelineManager.hpp.
Referenced by pdal::InfoKernel::dump(), libpdalpython::Pipeline::getArrays(), libpdaljava::Pipeline::getPointViews(), TEST(), and TEST_F().
Member Data Documentation
Options pdal::PipelineManager::m_commonOptions private
Definition at line 146 of file PipelineManager.hpp.
Referenced by setOptions().
StageFactory pdal::PipelineManager::m_factory private
Definition at line 143 of file PipelineManager.hpp.
Referenced by addFilter(), addReader(), and addWriter().
std::istream* pdal::PipelineManager::m_input private
Definition at line 151 of file PipelineManager.hpp.
Referenced by readPipeline(), and ~PipelineManager().
LogPtr pdal::PipelineManager::m_log private
Definition at line 152 of file PipelineManager.hpp.
Referenced by addFilter(), addReader(), and addWriter().
int pdal::PipelineManager::m_progressFd private
Definition at line 150 of file PipelineManager.hpp.
Referenced by addFilter(), addReader(), and addWriter().
OptionsMap pdal::PipelineManager::m_stageOptions private
Definition at line 147 of file PipelineManager.hpp.
Referenced by stageOptions(), and validateStageOptions().
std::vector<Stage*> pdal::PipelineManager::m_stages private
Definition at line 149 of file PipelineManager.hpp.
Referenced by addFilter(), addReader(), addWriter(), getMetadata(), leaves(), replace(), roots(), pdal::TEST(), and validateStageOptions().
PointTableRef pdal::PipelineManager::m_table private
Definition at line 145 of file PipelineManager.hpp.
Referenced by execute(), and prepare().
std::unique_ptr<PointTable> pdal::PipelineManager::m_tablePtr private
Definition at line 144 of file PipelineManager.hpp.
PointViewSet pdal::PipelineManager::m_viewSet private
Definition at line 148 of file PipelineManager.hpp.
Referenced by execute().
The documentation for this class was generated from the following files:
pdal/pdal/PipelineManager.hpp
pdal/pdal/PipelineManager.cpp