PDAL: pdal::plang::Invocation Class Reference
pdal::plang::Invocation Class Reference
#include <Invocation.hpp>
Public Member Functions
Invocation (const Script &)
~Invocation ()
void compile ()
void resetArguments ()
void insertArgument (std::string const &name, uint8_t *data, Dimension::Type t, point_count_t count)
void * extractResult (const std::string &name, Dimension::Type dataType)
bool hasOutputVariable (const std::string &name) const
bool execute ()
void getOutputNames (std::vector< std::string > &names)
void begin (PointView &view, MetadataNode m)
void end (PointView &view, MetadataNode m)
void setKWargs (std::string const &s)
Private Member Functions
void cleanup ()
Invocation & operator= (Invocation const &rhs)
Private Attributes
Script m_script
PyObject * m_bytecode
PyObject * m_module
PyObject * m_dictionary
PyObject * m_function
PyObject * m_varsIn
PyObject * m_varsOut
PyObject * m_scriptArgs
PyObject * m_scriptResult
std::vector< PyObject * > m_pyInputArrays
std::vector< void * > m_buffers
PyObject * m_metadata_PyObject
PyObject * m_schema_PyObject
PyObject * m_srs_PyObject
PyObject * m_pdalargs_PyObject
Detailed Description
Definition at line 51 of file Invocation.hpp.
Constructor & Destructor Documentation
pdal::plang::Invocation::Invocation (const Script & script)
Definition at line 78 of file Invocation.cpp.
References pdal::plang::Environment::get(), and resetArguments().
pdal::plang::Invocation::~Invocation ()
Definition at line 98 of file Invocation.cpp.
References cleanup().
Member Function Documentation
void pdal::plang::Invocation::begin (PointView & view, MetadataNode m)
Definition at line 365 of file Invocation.cpp.
References pdal::PointLayout::dims(), pdal::plang::fromMetadata(), pdal::PointView::getFieldInternal(), pdal::plang::getPyJSON(), insertArgument(), pdal::BasePointTable::layout(), pdal::PointView::layout(), m_buffers, m_metadata_PyObject, pdal::PointView::m_pointTable, m_schema_PyObject, m_srs_PyObject, pdal::Dimension::name(), pdal::Dimension::Detail::size(), pdal::PointView::size(), pdal::PointView::spatialReference(), pdal::Utils::toJSON(), pdal::SpatialReference::toMetadata(), pdal::PointLayout::toMetadata(), and pdal::Dimension::Detail::type().
Referenced by pdal::PythonFilter::run().
void pdal::plang::Invocation::cleanup () private
Definition at line 132 of file Invocation.cpp.
References m_bytecode, m_pyInputArrays, m_scriptArgs, m_scriptResult, m_varsIn, and m_varsOut.
Referenced by resetArguments(), and ~Invocation().
void pdal::plang::Invocation::compile ()
Definition at line 104 of file Invocation.cpp.
References pdal::plang::Script::function(), pdal::plang::getTraceback(), m_bytecode, m_dictionary, m_function, m_module, m_script, pdal::plang::Script::module(), and pdal::plang::Script::source().
Referenced by pdal::PythonFilter::ready(), and TEST().
void pdal::plang::Invocation::end (PointView & view, MetadataNode m)
Definition at line 406 of file Invocation.cpp.
References pdal::plang::addMetadata(), pdal::PointLayout::dims(), extractResult(), getOutputNames(), hasOutputVariable(), pdal::BasePointTable::layout(), m_buffers, m_metadata_PyObject, pdal::PointView::m_pointTable, pdal::Dimension::name(), pdal::PointView::setField(), pdal::Dimension::Detail::size(), pdal::PointView::size(), pdal::Dimension::size(), and pdal::Dimension::Detail::type().
Referenced by pdal::PythonFilter::run().
bool pdal::plang::Invocation::execute ()
Definition at line 260 of file Invocation.cpp.
References anonymous_namespace{Invocation.cpp}::argCount(), b, pdal::plang::getTraceback(), m_bytecode, m_dictionary, m_function, m_metadata_PyObject, m_module, m_pdalargs_PyObject, m_schema_PyObject, m_scriptArgs, m_scriptResult, m_srs_PyObject, m_varsIn, and m_varsOut.
Referenced by pdal::PythonFilter::run(), and TEST().
void * pdal::plang::Invocation::extractResult (const std::string & name, Dimension::Type dataType)
Definition at line 177 of file Invocation.cpp.
References b, pdal::Dimension::base(), pdal::plang::Environment::getPythonDataType(), m_varsOut, one, and pdal::Dimension::size().
Referenced by end(), pdal::PythonFilter::run(), and TEST().
void pdal::plang::Invocation::getOutputNames (std::vector< std::string > & names)
Definition at line 233 of file Invocation.cpp.
References m_varsOut.
Referenced by end(), and TEST().
bool pdal::plang::Invocation::hasOutputVariable (const std::string & name) const
Definition at line 254 of file Invocation.cpp.
References m_varsOut.
Referenced by end(), pdal::PythonFilter::run(), and TEST().
void pdal::plang::Invocation::insertArgument (std::string const & name, uint8_t * data, Dimension::Type t, point_count_t count)
Definition at line 153 of file Invocation.cpp.
References flags, pdal::plang::Environment::getPythonDataType(), m_pyInputArrays, m_varsIn, and pdal::Dimension::size().
Referenced by begin(), and TEST().
Invocation& pdal::plang::Invocation::operator= (Invocation const & rhs) private
void pdal::plang::Invocation::resetArguments ()
Definition at line 145 of file Invocation.cpp.
References cleanup(), m_varsIn, and m_varsOut.
Referenced by Invocation(), and pdal::PythonFilter::run().
void pdal::plang::Invocation::setKWargs (std::string const & s)
Definition at line 359 of file Invocation.cpp.
References pdal::plang::getPyJSON(), and m_pdalargs_PyObject.
Referenced by pdal::PythonFilter::run().
Member Data Documentation
std::vector<void *> pdal::plang::Invocation::m_buffers private
Definition at line 108 of file Invocation.hpp.
Referenced by begin(), and end().
PyObject* pdal::plang::Invocation::m_bytecode private
Definition at line 95 of file Invocation.hpp.
Referenced by cleanup(), compile(), and execute().
PyObject* pdal::plang::Invocation::m_dictionary private
Definition at line 97 of file Invocation.hpp.
Referenced by compile(), and execute().
PyObject* pdal::plang::Invocation::m_function private
Definition at line 98 of file Invocation.hpp.
Referenced by compile(), and execute().
PyObject* pdal::plang::Invocation::m_metadata_PyObject private
Definition at line 109 of file Invocation.hpp.
Referenced by begin(), end(), and execute().
PyObject* pdal::plang::Invocation::m_module private
Definition at line 96 of file Invocation.hpp.
Referenced by compile(), and execute().
PyObject* pdal::plang::Invocation::m_pdalargs_PyObject private
Definition at line 112 of file Invocation.hpp.
Referenced by execute(), and setKWargs().
std::vector<PyObject*> pdal::plang::Invocation::m_pyInputArrays private
Definition at line 104 of file Invocation.hpp.
Referenced by cleanup(), and insertArgument().
PyObject* pdal::plang::Invocation::m_schema_PyObject private
Definition at line 110 of file Invocation.hpp.
Referenced by begin(), and execute().
Script pdal::plang::Invocation::m_script private
Definition at line 93 of file Invocation.hpp.
Referenced by compile().
PyObject* pdal::plang::Invocation::m_scriptArgs private
Definition at line 102 of file Invocation.hpp.
Referenced by cleanup(), and execute().
PyObject* pdal::plang::Invocation::m_scriptResult private
Definition at line 103 of file Invocation.hpp.
Referenced by cleanup(), and execute().
PyObject* pdal::plang::Invocation::m_srs_PyObject private
Definition at line 111 of file Invocation.hpp.
Referenced by begin(), and execute().
PyObject* pdal::plang::Invocation::m_varsIn private
Definition at line 100 of file Invocation.hpp.
Referenced by cleanup(), execute(), insertArgument(), and resetArguments().
PyObject* pdal::plang::Invocation::m_varsOut private
Definition at line 101 of file Invocation.hpp.
Referenced by cleanup(), execute(), extractResult(), getOutputNames(), hasOutputVariable(), and resetArguments().
The documentation for this class was generated from the following files:
pdal/plugins/python/plang/Invocation.hpp
pdal/plugins/python/plang/Invocation.cpp