PDAL: pdal::SpatialReference Class Reference
pdal::SpatialReference Class Reference
#include <SpatialReference.hpp>
Public Member Functions
SpatialReference ()
SpatialReference (const std::string &wkt)
bool equals (const SpatialReference &other) const
bool operator== (const SpatialReference &other) const
bool operator!= (const SpatialReference &other) const
bool operator< (const SpatialReference &other) const
bool empty () const
bool valid () const
std::string getWKT () const
void set (std::string v)
std::string getProj4 () const
std::string getHorizontal () const
std::string getHorizontalUnits () const
std::string getVertical () const
std::string getVerticalUnits () const
int getUTMZone () const
void dump () const
MetadataNode toMetadata () const
bool isGeographic () const
bool isGeocentric () const
int computeUTMZone (const BOX3D &box) const
const std::string & getName () const
Static Public Member Functions
static int calculateZone (double lon, double lat)
static bool isWKT (const std::string &wkt)
static std::string prettyWkt (const std::string &wkt)
Private Attributes
std::string m_wkt
std::string m_horizontalWkt
Friends
PDAL_DLL std::ostream & operator<< (std::ostream &ostr, const SpatialReference &srs)
PDAL_DLL std::istream & operator>> (std::istream &istr, SpatialReference &srs)
Detailed Description
A SpatialReference defines a model of the earth that is used to describe the location of points. A SpatialReference is part of input data and is automatically loaded into PDAL by readers, or it's provided explicitly by a user through an option. All points in a point view share a common spatial reference. When a stage finishes processing point view, the point view takes on the spatial reference of that stage, if it had one. A point table tracks the spatial references of the views currently being processed by a stage. If a point table being processed by a stage has more than one spatial reference, PointTable::spatialReference() will return an empty spatial reference and PointTable::spatialReferenceUnique() will return false.
Definition at line 57 of file SpatialReference.hpp.
Constructor & Destructor Documentation
pdal::SpatialReference::SpatialReference ()
Constructor. Create an empty SRS.
Definition at line 63 of file SpatialReference.hpp.
References pdal::operator!=(), and pdal::operator==().
pdal::SpatialReference::SpatialReference (const std::string & wkt)
Construct a spatial reference from well-known text.
Parameters
wkt Well-known text from which to construct SRS.
Definition at line 88 of file SpatialReference.cpp.
Member Function Documentation
int pdal::SpatialReference::calculateZone (double lon, double lat) static
Definition at line 327 of file SpatialReference.cpp.
References pdal::Utils::normalizeLongitude().
Referenced by TEST().
int pdal::SpatialReference::computeUTMZone (const BOX3D & box) const
Definition at line 412 of file SpatialReference.cpp.
References pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::BOX3D::minz, and anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs().
Referenced by TEST().
void pdal::SpatialReference::dump () const
Definition at line 509 of file SpatialReference.cpp.
bool pdal::SpatialReference::empty () const
Returns true iff the object doesn't contain a valid srs.
Returns
Whether the SRS is empty.
Definition at line 94 of file SpatialReference.cpp.
Referenced by pdal::LasWriter::addGeotiffVlrs(), pdal::ReprojectionFilter::createTransform(), pdal::Stage::execute(), pdal::StatsFilter::extractMetadata(), pdal::GeotiffTags::GeotiffTags(), pdal::TIndexKernel::getFileInfo(), pdal::OciReader::initialize(), pdal::ReprojectionFilter::initialize(), pdal::SQLiteReader::initialize(), pdal::LasWriter::initialize(), pdal::LasWriter::prepOutput(), pdal::MergeFilter::ready(), pdal::CropFilter::ready(), pdal::NitfWriter::reprojectBoxToDD(), pdal::LasHeader::setSrsFromGeotiff(), TEST(), pdal::Polygon::transform(), pdal::CropFilter::transform(), pdal::Geometry::transform(), and pdal::transformWkt().
bool pdal::SpatialReference::equals (const SpatialReference & other) const
Determine if this spatial reference is the same as another.
Parameters
other SRS to compare with this one.
Returns
true if the SRSs match
Definition at line 270 of file SpatialReference.cpp.
References pdal::getWKT(), getWKT(), and anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs().
std::string pdal::SpatialReference::getHorizontal () const
Definition at line 230 of file SpatialReference.cpp.
References anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs().
Referenced by pdal::mlang::Script::setMatlabStruct(), and TEST().
std::string pdal::SpatialReference::getHorizontalUnits () const
Definition at line 249 of file SpatialReference.cpp.
References anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs(), and pdal::Utils::trim().
const std::string & pdal::SpatialReference::getName () const
Definition at line 299 of file SpatialReference.cpp.
References pdal::Dimension::name().
std::string pdal::SpatialReference::getProj4 () const
Returns the Proj.4 string describing the Spatial Reference System. If GDAL is linked, it uses GDAL's operations and methods to determine the Proj.4 string – otherwise, if libgeotiff is linked, it uses that. Note that GDAL's operations are much more mature and support more coordinate systems and descriptions.
Definition at line 159 of file SpatialReference.cpp.
References pdal::Utils::trim().
Referenced by TEST().
int pdal::SpatialReference::getUTMZone () const
Returns UTM zone if the coordinate system is actually UTM. The method simply forwards down to OSRGetUTMZone
Definition at line 400 of file SpatialReference.cpp.
References anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs().
Referenced by TEST(), and pdal::BpfHeader::trySetSpatialReference().
std::string pdal::SpatialReference::getVertical () const
Definition at line 179 of file SpatialReference.cpp.
References anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs().
Referenced by pdal::mlang::Script::setMatlabStruct(), and TEST().
std::string pdal::SpatialReference::getVerticalUnits () const
Definition at line 203 of file SpatialReference.cpp.
References anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs(), and pdal::Utils::trim().
std::string pdal::SpatialReference::getWKT () const
Definition at line 111 of file SpatialReference.cpp.
Referenced by pdal::LasWriter::addWktVlr(), pdal::ReprojectionFilter::createTransform(), equals(), pdal::GeotiffTags::GeotiffTags(), pdal::TIndexKernel::getFileInfo(), pdal::ReprojectionFilter::initialize(), pdal::Geometry::json(), pdal::gdal::Raster::open(), pdal::DensityKernel::outputDensity(), pdal::OGRWriter::readyFile(), pdal::NitfWriter::reprojectBoxToDD(), pdal::mlang::Script::setMatlabStruct(), pdal::Stage::setSpatialReference(), pdal::LasReader::setSrs(), TEST(), pdal::Polygon::transform(), pdal::CropFilter::transform(), pdal::Geometry::transform(), pdal::transformWkt(), and pdal::nitfwrap::NitfWrap::verifyLas().
bool pdal::SpatialReference::isGeocentric () const
Definition at line 317 of file SpatialReference.cpp.
References anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs().
bool pdal::SpatialReference::isGeographic () const
Definition at line 306 of file SpatialReference.cpp.
References anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs().
bool pdal::SpatialReference::isWKT (const std::string & wkt) static
Definition at line 359 of file SpatialReference.cpp.
bool pdal::SpatialReference::operator!= (const SpatialReference & other) const
Determine if this spatial reference is different from another.
Parameters
other SRS to compare with this one.
Returns
true if the SRSs don't match.
Definition at line 293 of file SpatialReference.cpp.
bool pdal::SpatialReference::operator< (const SpatialReference & other) const
Determine if the well-known text representation of this SRS is lexographically less than that of another.
Parameters
other SRS to compare with this one.
Returns
true if this SRS is lexographically less.
Definition at line 101 of file SpatialReference.hpp.
References pdal::getWKT(), m_wkt, and pdal::Utils::toMetadata().
bool pdal::SpatialReference::operator== (const SpatialReference & other) const
See equals.
Definition at line 287 of file SpatialReference.cpp.
std::string pdal::SpatialReference::prettyWkt (const std::string & wkt) static
Definition at line 383 of file SpatialReference.cpp.
References anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs().
void pdal::SpatialReference::set (std::string v)
Sets the SRS from a string representation. WKT is saved as provided.
Parameters
v - a string containing the definition (filename, proj4, wkt, etc).
Definition at line 117 of file SpatialReference.cpp.
References pdal::FileUtils::readFileIntoString().
Referenced by pdal::operator>>(), and pdal::LasHeader::setSrsFromWkt().
MetadataNode pdal::SpatialReference::toMetadata () const
Definition at line 488 of file SpatialReference.cpp.
References pdal::MetadataNode::add(), and pdal::getWKT().
Referenced by pdal::plang::Invocation::begin(), pdal::InfoKernel::dumpSummary(), and pdal::Stage::setSpatialReference().
bool pdal::SpatialReference::valid () const
Definition at line 100 of file SpatialReference.cpp.
References anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs().
Referenced by pdal::InfoKernel::dumpSummary(), and pdal::gdal::Raster::open().
Friends And Related Function Documentation
PDAL_DLL std::ostream& operator<< (std::ostream & ostr, const SpatialReference & srs) friend
Definition at line 515 of file SpatialReference.cpp.
PDAL_DLL std::istream& operator>> (std::istream & istr, SpatialReference & srs) friend
Definition at line 522 of file SpatialReference.cpp.
Member Data Documentation
std::string pdal::SpatialReference::m_horizontalWkt mutable private
Definition at line 153 of file SpatialReference.hpp.
std::string pdal::SpatialReference::m_wkt private
Definition at line 152 of file SpatialReference.hpp.
Referenced by operator<(), and pdal::operator<<().
The documentation for this class was generated from the following files:
pdal/pdal/SpatialReference.hpp
pdal/pdal/SpatialReference.cpp