PDAL: pdal::Ilvis2MetadataReader Class Reference
pdal::Ilvis2MetadataReader Class Reference
#include <Ilvis2MetadataReader.hpp>
Classes
struct error
Public Member Functions
void readMetadataFile (std::string filename, MetadataNode *m)
void readMetadataFile (std::string filename, pdal::MetadataNode *m)
void readMetadataFile (std::string filename, MetadataNode *m)
Protected Member Functions
void parseGranuleMetaDataFile (xmlNodePtr node, MetadataNode *m)
void parseGranuleURMetaData (xmlNodePtr node, MetadataNode *m)
void parseCollectionMetaData (xmlNodePtr node, MetadataNode *m)
void parseDataFiles (xmlNodePtr node, MetadataNode *m)
void parseDataFileContainer (xmlNodePtr node, MetadataNode *m)
void parseECSDataGranule (xmlNodePtr node, MetadataNode *m)
void parseRangeDateTime (xmlNodePtr node, MetadataNode *m)
void parsePlatform (xmlNodePtr node, MetadataNode *m)
void parseInstrument (xmlNodePtr node, MetadataNode *m)
void parseSensor (xmlNodePtr node, MetadataNode *m)
void parseSensorCharacteristic (xmlNodePtr node, MetadataNode *m)
void parseCampaign (xmlNodePtr node, MetadataNode *m)
void parsePSAs (xmlNodePtr node, MetadataNode *m)
void parsePSA (xmlNodePtr node, MetadataNode *m)
void parseXXProduct (std::string type, xmlNodePtr node, MetadataNode *m)
void parseSpatialDomainContainer (xmlNodePtr node, MetadataNode *m)
void parseGPolygon (xmlNodePtr node, MetadataNode *m)
void parseBoundary (xmlNodePtr node, MetadataNode *m)
void parsePoint (xmlNodePtr node, MetadataNode *m)
Private Member Functions
std::string extractString (xmlNodePtr node)
double extractDouble (xmlNodePtr node)
int extractInt (xmlNodePtr node)
long extractLong (xmlNodePtr node)
xmlNodePtr getNextElementNode (xmlNodePtr node)
xmlNodePtr getFirstChildElementNode (xmlNodePtr node)
bool nodeElementIs (xmlNodePtr node, std::string expected)
void assertElementIs (xmlNodePtr node, std::string expected)
void assertEndOfElements (xmlNodePtr node)
int countChildElements (xmlNodePtr node, std::string childName)
Detailed Description
Definition at line 49 of file Ilvis2MetadataReader.hpp.
Member Function Documentation
void pdal::Ilvis2MetadataReader::assertElementIs (xmlNodePtr node, std::string expected) private
Definition at line 646 of file Ilvis2MetadataReader.cpp.
References nodeElementIs().
Referenced by parseCampaign(), parseCollectionMetaData(), parseDataFileContainer(), parseDataFiles(), parseECSDataGranule(), parseGPolygon(), parseGranuleMetaDataFile(), parseGranuleURMetaData(), parseInstrument(), parsePlatform(), parsePSA(), parsePSAs(), parseRangeDateTime(), parseSensor(), parseSensorCharacteristic(), parseSpatialDomainContainer(), and parseXXProduct().
void pdal::Ilvis2MetadataReader::assertEndOfElements (xmlNodePtr node) private
Definition at line 655 of file Ilvis2MetadataReader.cpp.
Referenced by parseCampaign(), parseCollectionMetaData(), parseDataFileContainer(), parseDataFiles(), parseECSDataGranule(), parseGPolygon(), parseGranuleMetaDataFile(), parseGranuleURMetaData(), parseInstrument(), parsePlatform(), parsePSA(), parsePSAs(), parseRangeDateTime(), parseSensor(), parseSensorCharacteristic(), parseSpatialDomainContainer(), and parseXXProduct().
int pdal::Ilvis2MetadataReader::countChildElements (xmlNodePtr node, std::string childName) private
Definition at line 664 of file Ilvis2MetadataReader.cpp.
References getFirstChildElementNode(), getNextElementNode(), and nodeElementIs().
Referenced by parseGPolygon().
double pdal::Ilvis2MetadataReader::extractDouble (xmlNodePtr node) private
Definition at line 582 of file Ilvis2MetadataReader.cpp.
Referenced by parseECSDataGranule(), parseGPolygon(), and parseGranuleMetaDataFile().
int pdal::Ilvis2MetadataReader::extractInt (xmlNodePtr node) private
Definition at line 588 of file Ilvis2MetadataReader.cpp.
Referenced by parseCollectionMetaData(), and parseDataFileContainer().
long pdal::Ilvis2MetadataReader::extractLong (xmlNodePtr node) private
Definition at line 594 of file Ilvis2MetadataReader.cpp.
Referenced by parseGranuleURMetaData().
std::string pdal::Ilvis2MetadataReader::extractString (xmlNodePtr node) private
Definition at line 575 of file Ilvis2MetadataReader.cpp.
Referenced by parseCampaign(), parseCollectionMetaData(), parseDataFileContainer(), parseECSDataGranule(), parseGranuleMetaDataFile(), parseGranuleURMetaData(), parseInstrument(), parsePlatform(), parsePSA(), parseRangeDateTime(), parseSensor(), parseSensorCharacteristic(), and parseXXProduct().
xmlNodePtr pdal::Ilvis2MetadataReader::getFirstChildElementNode (xmlNodePtr node) private
Definition at line 615 of file Ilvis2MetadataReader.cpp.
References getNextElementNode().
Referenced by countChildElements(), parseCampaign(), parseCollectionMetaData(), parseDataFileContainer(), parseDataFiles(), parseECSDataGranule(), parseGPolygon(), parseGranuleMetaDataFile(), parseGranuleURMetaData(), parseInstrument(), parsePlatform(), parsePSA(), parsePSAs(), parseRangeDateTime(), parseSensor(), parseSensorCharacteristic(), parseSpatialDomainContainer(), and parseXXProduct().
xmlNodePtr pdal::Ilvis2MetadataReader::getNextElementNode (xmlNodePtr node) private
Definition at line 603 of file Ilvis2MetadataReader.cpp.
Referenced by countChildElements(), getFirstChildElementNode(), parseCampaign(), parseCollectionMetaData(), parseDataFileContainer(), parseDataFiles(), parseECSDataGranule(), parseGPolygon(), parseGranuleMetaDataFile(), parseGranuleURMetaData(), parseInstrument(), parsePlatform(), parsePSA(), parsePSAs(), parseRangeDateTime(), parseSensor(), parseSensorCharacteristic(), parseSpatialDomainContainer(), and parseXXProduct().
bool pdal::Ilvis2MetadataReader::nodeElementIs (xmlNodePtr node, std::string expected) private
Definition at line 633 of file Ilvis2MetadataReader.cpp.
Referenced by assertElementIs(), countChildElements(), parseDataFileContainer(), parseDataFiles(), parseECSDataGranule(), parseGPolygon(), parseGranuleURMetaData(), parseInstrument(), parsePlatform(), parsePSA(), parsePSAs(), parseSensor(), parseSpatialDomainContainer(), and parseXXProduct().
void pdal::Ilvis2MetadataReader::parseBoundary (xmlNodePtr node, MetadataNode * m) protected
void pdal::Ilvis2MetadataReader::parseCampaign (xmlNodePtr node, MetadataNode * m) protected
Definition at line 501 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::addList(), assertElementIs(), assertEndOfElements(), extractString(), getFirstChildElementNode(), and getNextElementNode().
Referenced by parseGranuleURMetaData().
void pdal::Ilvis2MetadataReader::parseCollectionMetaData (xmlNodePtr node, MetadataNode * m) protected
Definition at line 184 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), assertElementIs(), assertEndOfElements(), extractInt(), extractString(), getFirstChildElementNode(), and getNextElementNode().
Referenced by parseGranuleURMetaData().
void pdal::Ilvis2MetadataReader::parseDataFileContainer (xmlNodePtr node, MetadataNode * m) protected
Definition at line 220 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), assertElementIs(), assertEndOfElements(), extractInt(), extractString(), getFirstChildElementNode(), getNextElementNode(), and nodeElementIs().
Referenced by parseDataFiles().
void pdal::Ilvis2MetadataReader::parseDataFiles (xmlNodePtr node, MetadataNode * m) protected
Definition at line 202 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::addList(), assertElementIs(), assertEndOfElements(), getFirstChildElementNode(), getNextElementNode(), nodeElementIs(), and parseDataFileContainer().
Referenced by parseGranuleURMetaData().
void pdal::Ilvis2MetadataReader::parseECSDataGranule (xmlNodePtr node, MetadataNode * m) protected
Definition at line 256 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), assertElementIs(), assertEndOfElements(), extractDouble(), extractString(), getFirstChildElementNode(), getNextElementNode(), and nodeElementIs().
Referenced by parseGranuleURMetaData().
void pdal::Ilvis2MetadataReader::parseGPolygon (xmlNodePtr node, MetadataNode * m) protected
Definition at line 330 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), assertElementIs(), assertEndOfElements(), countChildElements(), extractDouble(), getFirstChildElementNode(), getNextElementNode(), and nodeElementIs().
Referenced by parseSpatialDomainContainer().
void pdal::Ilvis2MetadataReader::parseGranuleMetaDataFile (xmlNodePtr node, MetadataNode * m) protected
Definition at line 61 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), assertElementIs(), assertEndOfElements(), extractDouble(), extractString(), getFirstChildElementNode(), getNextElementNode(), and parseGranuleURMetaData().
Referenced by readMetadataFile().
void pdal::Ilvis2MetadataReader::parseGranuleURMetaData (xmlNodePtr node, MetadataNode * m) protected
Definition at line 83 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), assertElementIs(), assertEndOfElements(), extractLong(), extractString(), getFirstChildElementNode(), getNextElementNode(), nodeElementIs(), parseCampaign(), parseCollectionMetaData(), parseDataFiles(), parseECSDataGranule(), parsePlatform(), parsePSAs(), parseRangeDateTime(), parseSpatialDomainContainer(), and parseXXProduct().
Referenced by parseGranuleMetaDataFile().
void pdal::Ilvis2MetadataReader::parseInstrument (xmlNodePtr node, MetadataNode * m) protected
Definition at line 436 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), assertElementIs(), assertEndOfElements(), extractString(), getFirstChildElementNode(), getNextElementNode(), nodeElementIs(), and parseSensor().
Referenced by parsePlatform().
void pdal::Ilvis2MetadataReader::parsePlatform (xmlNodePtr node, MetadataNode * m) protected
Definition at line 415 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), assertElementIs(), assertEndOfElements(), extractString(), getFirstChildElementNode(), getNextElementNode(), nodeElementIs(), and parseInstrument().
Referenced by parseGranuleURMetaData().
void pdal::Ilvis2MetadataReader::parsePoint (xmlNodePtr node, MetadataNode * m) protected
void pdal::Ilvis2MetadataReader::parsePSA (xmlNodePtr node, MetadataNode * m) protected
Definition at line 531 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), assertElementIs(), assertEndOfElements(), extractString(), getFirstChildElementNode(), getNextElementNode(), and nodeElementIs().
Referenced by parsePSAs().
void pdal::Ilvis2MetadataReader::parsePSAs (xmlNodePtr node, MetadataNode * m) protected
Definition at line 515 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::addList(), assertElementIs(), assertEndOfElements(), getFirstChildElementNode(), getNextElementNode(), nodeElementIs(), and parsePSA().
Referenced by parseGranuleURMetaData().
void pdal::Ilvis2MetadataReader::parseRangeDateTime (xmlNodePtr node, MetadataNode * m) protected
Definition at line 286 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), assertElementIs(), assertEndOfElements(), extractString(), getFirstChildElementNode(), and getNextElementNode().
Referenced by parseGranuleURMetaData().
void pdal::Ilvis2MetadataReader::parseSensor (xmlNodePtr node, MetadataNode * m) protected
Definition at line 463 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), assertElementIs(), assertEndOfElements(), extractString(), getFirstChildElementNode(), getNextElementNode(), nodeElementIs(), and parseSensorCharacteristic().
Referenced by parseInstrument().
void pdal::Ilvis2MetadataReader::parseSensorCharacteristic (xmlNodePtr node, MetadataNode * m) protected
Definition at line 483 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::add(), assertElementIs(), assertEndOfElements(), extractString(), getFirstChildElementNode(), and getNextElementNode().
Referenced by parseSensor().
void pdal::Ilvis2MetadataReader::parseSpatialDomainContainer (xmlNodePtr node, MetadataNode * m) protected
Definition at line 311 of file Ilvis2MetadataReader.cpp.
References assertElementIs(), assertEndOfElements(), getFirstChildElementNode(), getNextElementNode(), nodeElementIs(), and parseGPolygon().
Referenced by parseGranuleURMetaData().
void pdal::Ilvis2MetadataReader::parseXXProduct (std::string type, xmlNodePtr node, MetadataNode * m) protected
Definition at line 552 of file Ilvis2MetadataReader.cpp.
References pdal::MetadataNode::addList(), assertElementIs(), assertEndOfElements(), extractString(), getFirstChildElementNode(), getNextElementNode(), and nodeElementIs().
Referenced by parseGranuleURMetaData().
void pdal::Ilvis2MetadataReader::readMetadataFile (std::string filename, pdal::MetadataNode * m)
Definition at line 47 of file Ilvis2Reader.hpp.
References Ilvis2Reader_ExitFunc(), and Ilvis2Reader_InitPlugin().
void pdal::Ilvis2MetadataReader::readMetadataFile (std::string filename, MetadataNode * m)
Definition at line 47 of file IcebridgeReader.hpp.
void pdal::Ilvis2MetadataReader::readMetadataFile (std::string filename, MetadataNode * m)
Definition at line 40 of file Ilvis2MetadataReader.cpp.
References parseGranuleMetaDataFile().
Referenced by pdal::Ilvis2Reader::ready(), and TEST().
The documentation for this class was generated from the following files:
pdal/io/Ilvis2MetadataReader.hpp
pdal/io/Ilvis2Reader.hpp
pdal/plugins/icebridge/io/IcebridgeReader.hpp
pdal/io/Ilvis2MetadataReader.cpp