PDAL: pdal::SimplePointTable Class Reference
pdal::SimplePointTable Class Reference abstract
#include <PointTable.hpp>
Public Member Functions
virtual PointLayoutPtr layout () const
MetadataNode metadata ()
virtual void finalize ()
void setSpatialReference (const SpatialReference &srs)
void clearSpatialReferences ()
void addSpatialReference (const SpatialReference &srs)
bool spatialReferenceUnique () const
SpatialReference spatialReference () const
SpatialReference anySpatialReference () const
virtual bool supportsView () const
MetadataNode privateMetadata (const std::string &name)
MetadataNode toMetadata () const
Protected Member Functions
SimplePointTable (PointLayout &layout)
std::size_t pointsToBytes (point_count_t numPts) const
virtual char * getPoint (PointId idx)=0
Protected Attributes
MetadataPtr m_metadata
std::list< SpatialReference > m_spatialRefs
PointLayout & m_layoutRef
Private Member Functions
virtual void setFieldInternal (Dimension::Id id, PointId idx, const void *value)
virtual void getFieldInternal (Dimension::Id id, PointId idx, void *value) const
char * getDimension (const Dimension::Detail *d, PointId idx)
const char * getDimension (const Dimension::Detail *d, PointId idx) const
Detailed Description
Definition at line 113 of file PointTable.hpp.
Constructor & Destructor Documentation
pdal::SimplePointTable::SimplePointTable (PointLayout & layout) protected
Definition at line 117 of file PointTable.hpp.
Member Function Documentation
void pdal::BasePointTable::addSpatialReference (const SpatialReference & srs) inherited
Definition at line 50 of file PointTable.cpp.
References pdal::BasePointTable::m_spatialRefs.
Referenced by pdal::Stage::execute(), and pdal::TEST().
SpatialReference pdal::BasePointTable::anySpatialReference () const inherited
Definition at line 88 of file PointTable.hpp.
Referenced by pdal::HexBin::done(), pdal::DensityKernel::execute(), pdal::StatsFilter::extractMetadata(), pdal::MergeFilter::ready(), pdal::ReprojectionFilter::ready(), pdal::CropFilter::ready(), pdal::OverlayFilter::ready(), and pdal::TEST().
void pdal::BasePointTable::clearSpatialReferences () inherited
Definition at line 78 of file PointTable.hpp.
Referenced by pdal::Stage::execute().
virtual void pdal::BasePointTable::finalize () virtual inherited
Reimplemented in pdal::FixedPointTable, and pdal::StreamPointTable.
Definition at line 71 of file PointTable.hpp.
Referenced by pdal::Stage::execute(), and pdal::FixedPointTable::finalize().
char* pdal::SimplePointTable::getDimension (const Dimension::Detail * d, PointId idx) private
Definition at line 131 of file PointTable.hpp.
References anonymous_namespace{ReprojectionFilterTest.cpp}::getPoint(), and pdal::Dimension::Detail::offset().
const char* pdal::SimplePointTable::getDimension (const Dimension::Detail * d, PointId idx) const private
Definition at line 134 of file PointTable.hpp.
References pdal::BasePointTable::getPoint(), and pdal::Dimension::Detail::offset().
void pdal::SimplePointTable::getFieldInternal (Dimension::Id id, PointId idx, void * value) const private virtual
Implements pdal::PointContainer.
Definition at line 73 of file PointTable.cpp.
References pdal::PointLayout::dimDetail(), pdal::BasePointTable::m_layoutRef, and pdal::Dimension::Detail::size().
virtual char* pdal::BasePointTable::getPoint (PointId idx) protected pure virtual inherited
Implemented in pdal::FixedPointTable, and pdal::PointTable.
Referenced by getDimension().
virtual PointLayoutPtr pdal::BasePointTable::layout () const virtual inherited
Implements pdal::PointContainer.
Definition at line 65 of file PointTable.hpp.
Referenced by pdal::plang::Invocation::begin(), GDALReaderTypeTest::compare(), pdal::PlyWriter::done(), anonymous_namespace{SortFilterTest.cpp}::doSort(), pdal::InfoKernel::dump(), pdal::PointView::dump(), pdal::plang::Invocation::end(), pdal::PipelineKernel::execute(), pdal::DiffKernel::execute(), pdal::DeltaKernel::execute(), getBytes(), pdal::PipelineExecutor::getSchema(), main(), makeTestView(), pdal::Stage::prepare(), pdal::MatlabWriter::prepared(), pdal::AssignFilter::prepared(), pdal::GDALWriter::prepared(), pdal::GreyhoundReader::prepared(), pdal::PlyWriter::prepared(), pdal::ComputeRangeFilter::prepared(), pdal::HAGFilter::prepared(), pdal::GroupByFilter::prepared(), pdal::IQRFilter::prepared(), pdal::LocateFilter::prepared(), pdal::RangeFilter::prepared(), pdal::MADFilter::prepared(), pdal::PMFFilter::prepared(), pdal::DbWriter::prepared(), pdal::FerryFilter::prepared(), pdal::SortFilter::prepared(), pdal::SMRFilter::prepared(), pdal::ColorinterpFilter::prepared(), pdal::BpfWriter::prepared(), pdal::OverlayFilter::prepared(), pdal::LasWriter::prepared(), pdal::StatsFilter::prepared(), pdal::MyWriter::ready(), pdal::GeoWaveWriter::ready(), pdal::TextWriter::ready(), pdal::PlyWriter::ready(), pdal::Ilvis2Reader::ready(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), TEST_F(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), pdal::BasePointTable::toMetadata(), pdal::MongusFilter::writeControl(), and pdal::TextWriter::writeCSVHeader().
MetadataNode pdal::BasePointTable::metadata () inherited
Definition at line 69 of file PointTable.hpp.
Referenced by pdal::DiffKernel::execute(), pdal::TIndexKernel::getFileInfo(), pdal::MatlabReader::initialize(), pdal::Stage::l_initialize(), pdal::MatlabWriter::ready(), pdal::MatlabFilter::ready(), pdal::PythonFilter::ready(), pdal::LasWriter::readyTable(), TEST(), and TEST_F().
std::size_t pdal::SimplePointTable::pointsToBytes (point_count_t numPts) const protected
Definition at line 121 of file PointTable.hpp.
MetadataNode pdal::BasePointTable::privateMetadata (const std::string & name) inherited
Definition at line 40 of file PointTable.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::findChild(), pdal::BasePointTable::m_metadata, and pdal::MetadataNode::valid().
Referenced by pdal::LasReader::initializeLocal(), pdal::LasWriter::readyTable(), and TEST().
void pdal::SimplePointTable::setFieldInternal (Dimension::Id id, PointId idx, const void * value) private virtual
Implements pdal::PointContainer.
Definition at line 63 of file PointTable.cpp.
References pdal::PointLayout::dimDetail(), pdal::BasePointTable::m_layoutRef, and pdal::Dimension::Detail::size().
void pdal::BasePointTable::setSpatialReference (const SpatialReference & srs) inherited
Definition at line 73 of file PointTable.hpp.
Referenced by pdal::Stage::execute().
SpatialReference pdal::BasePointTable::spatialReference () const inherited
Definition at line 83 of file PointTable.hpp.
Referenced by TEST().
bool pdal::BasePointTable::spatialReferenceUnique () const inherited
Definition at line 81 of file PointTable.hpp.
Referenced by pdal::CropFilter::ready(), and pdal::TEST().
virtual bool pdal::BasePointTable::supportsView () const virtual inherited
Reimplemented in pdal::PointTable.
Definition at line 93 of file PointTable.hpp.
References anonymous_namespace{ReprojectionFilterTest.cpp}::getPoint(), pdal::Dimension::name(), and pdal::Utils::toMetadata().
Referenced by pdal::ReprojectionFilter::ready(), pdal::GDALWriter::readyTable(), and pdal::FlexWriter::validateFilename().
MetadataNode pdal::BasePointTable::toMetadata () const inherited
Definition at line 109 of file PointTable.cpp.
References pdal::BasePointTable::layout(), and pdal::PointLayout::toMetadata().
Member Data Documentation
PointLayout& pdal::BasePointTable::m_layoutRef protected inherited
Definition at line 108 of file PointTable.hpp.
Referenced by getFieldInternal(), and setFieldInternal().
MetadataPtr pdal::BasePointTable::m_metadata protected inherited
Definition at line 106 of file PointTable.hpp.
Referenced by pdal::BasePointTable::privateMetadata().
std::list<SpatialReference> pdal::BasePointTable::m_spatialRefs protected inherited
Definition at line 107 of file PointTable.hpp.
Referenced by pdal::BasePointTable::addSpatialReference(), and pdal::TEST().
The documentation for this class was generated from the following files:
pdal/pdal/PointTable.hpp
pdal/pdal/PointTable.cpp