PDAL: pdal::plang::Redirector Class Reference
pdal::plang::Redirector Class Reference
#include <Redirector.hpp>
Public Types
typedef std::function< void(std::string)> stdout_write_type
typedef std::function< void()> stdout_flush_type
Public Member Functions
Redirector ()
~Redirector ()
void set_stdout (std::ostream *ostr)
void reset_stdout ()
Static Public Member Functions
static PyObject * init ()
Private Member Functions
void set_stdout (stdout_write_type write, stdout_flush_type flush)
Private Attributes
PyObject * m_stdout
PyObject * m_stdout_saved
Detailed Description
Definition at line 36 of file Redirector.hpp.
Member Typedef Documentation
typedef std::function<void()> pdal::plang::Redirector::stdout_flush_type
Definition at line 47 of file Redirector.hpp.
typedef std::function<void(std::string)> pdal::plang::Redirector::stdout_write_type
Definition at line 46 of file Redirector.hpp.
Constructor & Destructor Documentation
pdal::plang::Redirector::Redirector ()
Definition at line 124 of file Redirector.cpp.
pdal::plang::Redirector::~Redirector ()
Definition at line 132 of file Redirector.cpp.
Member Function Documentation
PyObject * pdal::plang::Redirector::init () static
Definition at line 161 of file Redirector.cpp.
Referenced by pdal::plang::Environment::Environment(), and pdal::plang::redirector_init().
void pdal::plang::Redirector::reset_stdout ()
Definition at line 210 of file Redirector.cpp.
References m_stdout, and m_stdout_saved.
Referenced by pdal::plang::Environment::reset_stdout().
void pdal::plang::Redirector::set_stdout (std::ostream * ostr)
Definition at line 185 of file Redirector.cpp.
Referenced by pdal::plang::Environment::set_stdout().
void pdal::plang::Redirector::set_stdout (stdout_write_type write, stdout_flush_type flush) private
Definition at line 194 of file Redirector.cpp.
References pdal::plang::Stdout::flush, m_stdout, m_stdout_saved, and pdal::plang::Stdout::write.
Member Data Documentation
PyObject* pdal::plang::Redirector::m_stdout private
Definition at line 53 of file Redirector.hpp.
Referenced by reset_stdout(), and set_stdout().
PyObject* pdal::plang::Redirector::m_stdout_saved private
Definition at line 54 of file Redirector.hpp.
Referenced by reset_stdout(), and set_stdout().
The documentation for this class was generated from the following files:
pdal/plugins/python/plang/Redirector.hpp
pdal/plugins/python/plang/Redirector.cpp