PDAL: pdal::FilterWrapper Class Reference
pdal::FilterWrapper Class Reference
#include <StageWrapper.hpp>
Static Public Member Functions
static void filter (Filter &f, PointView &view)
static void initialize (Stage &s, PointTableRef table)
static void addDimensions (Stage &s, PointLayoutPtr layout)
static void ready (Stage &s, PointTableRef table)
static void done (Stage &s, PointTableRef table)
static PointViewSet run (Stage &s, PointViewPtr view)
Detailed Description
Definition at line 30 of file StageWrapper.hpp.
Member Function Documentation
static void pdal::StageWrapper::addDimensions (Stage & s, PointLayoutPtr layout) static inherited
Definition at line 19 of file StageWrapper.hpp.
References pdal::Stage::addDimensions().
static void pdal::StageWrapper::done (Stage & s, PointTableRef table) static inherited
Definition at line 23 of file StageWrapper.hpp.
References pdal::Stage::done().
Referenced by anonymous_namespace{SortFilterTest.cpp}::doSort(), TEST(), and TEST_F().
static void pdal::FilterWrapper::filter (Filter & f, PointView & view) static
Definition at line 33 of file StageWrapper.hpp.
References pdal::Filter::filter().
Referenced by anonymous_namespace{SortFilterTest.cpp}::doSort().
static void pdal::StageWrapper::initialize (Stage & s, PointTableRef table) static inherited
Definition at line 14 of file StageWrapper.hpp.
References pdal::Stage::initialize(), and pdal::Stage::l_initialize().
static void pdal::StageWrapper::ready (Stage & s, PointTableRef table) static inherited
Definition at line 21 of file StageWrapper.hpp.
References pdal::Stage::ready().
Referenced by anonymous_namespace{SortFilterTest.cpp}::doSort(), TEST(), and TEST_F().
static PointViewSet pdal::StageWrapper::run (Stage & s, PointViewPtr view) static inherited
Definition at line 25 of file StageWrapper.hpp.
References pdal::Stage::run().
Referenced by TEST(), and TEST_F().
The documentation for this class was generated from the following file:
pdal/pdal/StageWrapper.hpp