PDAL: pdal::Dimension::Detail Class Reference
pdal::Dimension::Detail Class Reference
#include <DimDetail.hpp>
Public Member Functions
Detail ()
virtual ~Detail ()
void setOffset (int offset)
void setType (Type type)
void setId (Id id)
Id id () const
int offset () const
Type type () const
size_t size () const
BaseType base () const
Private Attributes
Id m_id
int m_offset
Type m_type
Detailed Description
Definition at line 44 of file DimDetail.hpp.
Constructor & Destructor Documentation
pdal::Dimension::Detail::Detail ()
Definition at line 47 of file DimDetail.hpp.
virtual pdal::Dimension::Detail::~Detail () virtual
Definition at line 54 of file DimDetail.hpp.
Member Function Documentation
BaseType pdal::Dimension::Detail::base () const
Definition at line 71 of file DimDetail.hpp.
References pdal::Dimension::base(), and m_type.
Id pdal::Dimension::Detail::id () const
Definition at line 63 of file DimDetail.hpp.
References m_id.
Referenced by pdal::MatlabReader::addDimensions(), pdal::GreyhoundReader::prepared(), setId(), TEST(), and pdal::PointLayout::update().
int pdal::Dimension::Detail::offset () const
Definition at line 65 of file DimDetail.hpp.
References m_offset.
Referenced by pdal::PointLayout::dimOffset(), pdal::SimplePointTable::getDimension(), and setOffset().
void pdal::Dimension::Detail::setId (Id id)
Definition at line 61 of file DimDetail.hpp.
References id(), and m_id.
void pdal::Dimension::Detail::setOffset (int offset)
Definition at line 57 of file DimDetail.hpp.
References m_offset, and offset().
void pdal::Dimension::Detail::setType (Type type)
Definition at line 59 of file DimDetail.hpp.
References m_type, and type().
Referenced by pdal::PointLayout::registerDim(), and TEST().
size_t pdal::Dimension::Detail::size () const
Definition at line 69 of file DimDetail.hpp.
References m_type, and pdal::Dimension::size().
Referenced by pdal::plang::Invocation::begin(), pdal::PointLayout::dimSize(), pdal::plang::Invocation::end(), pdal::SimplePointTable::getFieldInternal(), pdal::SimplePointTable::setFieldInternal(), and pdal::PointLayout::update().
Type pdal::Dimension::Detail::type () const
Definition at line 67 of file DimDetail.hpp.
References m_type.
Referenced by pdal::MatlabReader::addDimensions(), pdal::plang::Invocation::begin(), pdal::PointView::compare(), pdal::PointLayout::dimType(), pdal::PointView::dump(), pdal::plang::Invocation::end(), pdal::PointView::getFieldAs(), pdal::GreyhoundReader::prepared(), pdal::PointLayout::registerDim(), pdal::PointView::setField(), and setType().
Member Data Documentation
Id pdal::Dimension::Detail::m_id private
Definition at line 75 of file DimDetail.hpp.
Referenced by id(), and setId().
int pdal::Dimension::Detail::m_offset private
Definition at line 76 of file DimDetail.hpp.
Referenced by offset(), and setOffset().
Type pdal::Dimension::Detail::m_type private
Definition at line 77 of file DimDetail.hpp.
Referenced by base(), setType(), size(), and type().
The documentation for this class was generated from the following file:
pdal/pdal/DimDetail.hpp