PDAL: pdal::DimBuilder Class Reference
pdal::DimBuilder Class Reference
#include <DimBuilder.hpp>
Public Member Functions
DimBuilder ()
bool parseArgs (int argc, char *argv[])
bool execute ()
Private Member Functions
void extractDim (Json::Value &dim)
void writeOutput (std::ostream &out)
void writeHeader (std::ostream &out)
void writeFooter (std::ostream &out)
void writeIds (std::ostream &out)
void writeDescriptions (std::ostream &out)
void writeNameToId (std::ostream &out)
void writeIdToName (std::ostream &out)
void writeTypes (std::ostream &out)
void validateDimension (const std::string &dimName)
Private Attributes
std::string m_input
std::string m_output
std::vector< DimSpec > m_dims
Detailed Description
Definition at line 60 of file DimBuilder.hpp.
Constructor & Destructor Documentation
pdal::DimBuilder::DimBuilder ()
Definition at line 63 of file DimBuilder.hpp.
Member Function Documentation
bool pdal::DimBuilder::execute ()
Definition at line 124 of file DimBuilder.cpp.
References extractDim(), m_input, m_output, and writeOutput().
Referenced by main().
void pdal::DimBuilder::extractDim (Json::Value & dim) private
Definition at line 174 of file DimBuilder.cpp.
References pdal::Dimension::description(), pdal::DimSpec::m_altNames, pdal::DimSpec::m_description, m_dims, pdal::DimSpec::m_name, pdal::DimSpec::m_type, pdal::Dimension::name(), pdal::Dimension::None, pdal::Utils::split2(), pdal::Utils::trim(), pdal::Dimension::type(), and validateDimension().
Referenced by execute().
bool pdal::DimBuilder::parseArgs (int argc, char * argv[])
Definition at line 100 of file DimBuilder.cpp.
References pdal::ProgramArgs::add(), pdal::arg_error::m_error, m_input, m_output, pdal::ProgramArgs::parse(), and pdal::Arg::setPositional().
Referenced by main().
void pdal::DimBuilder::validateDimension (const std::string & dimName) private
Definition at line 254 of file DimBuilder.cpp.
References pdal::Dimension::extractName(), and m_dims.
Referenced by extractDim().
void pdal::DimBuilder::writeDescriptions (std::ostream & out) private
Definition at line 345 of file DimBuilder.cpp.
References m_dims, and pdal::Utils::wordWrap2().
Referenced by writeOutput().
void pdal::DimBuilder::writeFooter (std::ostream & out) private
Definition at line 318 of file DimBuilder.cpp.
Referenced by writeOutput().
void pdal::DimBuilder::writeHeader (std::ostream & out) private
Definition at line 296 of file DimBuilder.cpp.
References m_input.
Referenced by writeOutput().
void pdal::DimBuilder::writeIds (std::ostream & out) private
Definition at line 326 of file DimBuilder.cpp.
References m_dims, and pdal::DimSpec::m_name.
Referenced by writeOutput().
void pdal::DimBuilder::writeIdToName (std::ostream & out) private
Definition at line 412 of file DimBuilder.cpp.
References m_dims.
Referenced by writeOutput().
void pdal::DimBuilder::writeNameToId (std::ostream & out) private
Definition at line 382 of file DimBuilder.cpp.
References m_dims, and pdal::Utils::toupper().
Referenced by writeOutput().
void pdal::DimBuilder::writeOutput (std::ostream & out) private
Definition at line 278 of file DimBuilder.cpp.
References writeDescriptions(), writeFooter(), writeHeader(), writeIds(), writeIdToName(), writeNameToId(), and writeTypes().
Referenced by execute().
void pdal::DimBuilder::writeTypes (std::ostream & out) private
Definition at line 433 of file DimBuilder.cpp.
References pdal::anonymous_namespace{DimBuilder.cpp}::getTypename(), and m_dims.
Referenced by writeOutput().
Member Data Documentation
std::vector<DimSpec> pdal::DimBuilder::m_dims private
Definition at line 72 of file DimBuilder.hpp.
Referenced by extractDim(), validateDimension(), writeDescriptions(), writeIds(), writeIdToName(), writeNameToId(), and writeTypes().
std::string pdal::DimBuilder::m_input private
Definition at line 70 of file DimBuilder.hpp.
Referenced by execute(), parseArgs(), and writeHeader().
std::string pdal::DimBuilder::m_output private
Definition at line 71 of file DimBuilder.hpp.
Referenced by execute(), and parseArgs().
The documentation for this class was generated from the following files:
pdal/dimbuilder/DimBuilder.hpp
pdal/dimbuilder/DimBuilder.cpp