PDAL: pdal::IBeStream Class Reference
pdal::IBeStream Class Reference
#include <IStream.hpp>
Public Member Functions
PDAL_DLL IBeStream ()
PDAL_DLL IBeStream (const std::string &filename)
PDAL_DLL IBeStream (std::istream *stream)
PDAL_DLL IBeStream & operator>> (uint8_t &v)
PDAL_DLL IBeStream & operator>> (int8_t &v)
PDAL_DLL IBeStream & operator>> (uint16_t &v)
PDAL_DLL IBeStream & operator>> (int16_t &v)
PDAL_DLL IBeStream & operator>> (uint32_t &v)
PDAL_DLL IBeStream & operator>> (int32_t &v)
PDAL_DLL IBeStream & operator>> (uint64_t &v)
PDAL_DLL IBeStream & operator>> (int64_t &v)
PDAL_DLL IBeStream & operator>> (float &v)
PDAL_DLL IBeStream & operator>> (double &v)
PDAL_DLL int open (const std::string &filename)
PDAL_DLL void close ()
PDAL_DLL operator bool ()
PDAL_DLL void seek (std::streampos pos)
PDAL_DLL void seek (std::streampos off, std::ios_base::seekdir way)
PDAL_DLL void skip (std::streamoff offset)
PDAL_DLL std::streampos position () const
PDAL_DLL bool good () const
PDAL_DLL std::istream * stream ()
PDAL_DLL void pushStream (std::istream *strm)
PDAL_DLL std::istream * popStream ()
PDAL_DLL void get (std::string &s, size_t size)
PDAL_DLL void get (std::vector< char > &buf)
PDAL_DLL void get (std::vector< unsigned char > &buf)
PDAL_DLL void get (char *buf, size_t size)
PDAL_DLL void get (unsigned char *buf, size_t size)
Protected Attributes
std::istream * m_stream
std::ifstream * m_fstream
Detailed Description
Stream wrapper for input of binary data that converts from big-endian to host ordering.
Definition at line 427 of file IStream.hpp.
Constructor & Destructor Documentation
PDAL_DLL pdal::IBeStream::IBeStream ()
Default constructor.
Definition at line 433 of file IStream.hpp.
PDAL_DLL pdal::IBeStream::IBeStream (const std::string & filename)
Constructor that opens the file and maps it to a stream.
Parameters
filename Filename.
Definition at line 441 of file IStream.hpp.
PDAL_DLL pdal::IBeStream::IBeStream (std::istream * stream)
Constructor that maps to a provided stream.
Parameters
stream Stream to extract from.
Definition at line 449 of file IStream.hpp.
Member Function Documentation
PDAL_DLL void pdal::IStream::close () inherited
Close the underlying stream.
Definition at line 105 of file IStream.hpp.
References pdal::IStream::m_fstream, and pdal::IStream::m_stream.
Referenced by pdal::BpfReader::done(), and pdal::BpfReader::initialize().
PDAL_DLL void pdal::IStream::get (std::string & s, size_t size) inherited
Fetch data from the stream into a string.
Parameters
s String to fill.
size Number of bytes to extract.
Definition at line 204 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::Dimension::size().
Referenced by pdal::LasHeader::get(), pdal::OptechReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::lasdump::operator>>(), pdal::operator>>(), pdal::BpfDimension::read(), pdal::BpfUlemHeader::read(), pdal::BpfUlemFile::read(), pdal::BpfPolarHeader::read(), pdal::BpfReader::readHeaderExtraData(), pdal::lasdump::Dumper::readPoints(), pdal::BpfHeader::readV3(), and pdal::BpfReader::seekByteMajor().
PDAL_DLL void pdal::IStream::get (std::vector< char > & buf) inherited
Fetch data from the stream into a vector of char.
Parameters
buf Buffer to fill.
Definition at line 220 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL void pdal::IStream::get (std::vector< unsigned char > & buf) inherited
Fetch data from the stream into a vector of unsigned char.
Parameters
buf Buffer to fill.
Definition at line 230 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL void pdal::IStream::get (char * buf, size_t size) inherited
Fetch data from the stream into the specified buffer of char.
Parameters
buf Buffer to fill.
size Number of bytes to extract.
Definition at line 241 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::Dimension::size().
PDAL_DLL void pdal::IStream::get (unsigned char * buf, size_t size) inherited
Fetch data from the stream into the specified buffer of unsigned char.
Parameters
buf Buffer to fill.
size Number of bytes to extract.
Definition at line 250 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::Dimension::size().
PDAL_DLL bool pdal::IStream::good () const inherited
Determine if the underlying stream is good.
Returns
Whether the underlying stream is good.
Definition at line 159 of file IStream.hpp.
References pdal::IStream::m_stream.
Referenced by pdal::lasdump::Dumper::dump().
PDAL_DLL int pdal::IStream::open (const std::string & filename) inherited
Open a file to extract.
Parameters
filename Filename.
Returns
-1 if a stream is already assigned, 0 otherwise.
Definition at line 93 of file IStream.hpp.
References pdal::IStream::m_fstream, and pdal::IStream::m_stream.
Referenced by pdal::BpfReader::initialize(), pdal::IStream::IStream(), and pdal::BpfReader::ready().
PDAL_DLL pdal::IStream::operator bool () inherited
Return the state of the stream.
Returns
The state of the underlying stream.
Definition at line 117 of file IStream.hpp.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (uint8_t & v)
Extract an unsigned byte from the stream.
Parameters
v unsigned byte to populate
Returns
This stream.
Definition at line 458 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (int8_t & v)
Extract an unsigned byte from the stream.
Parameters
v unsigned byte to populate
Returns
This stream.
Definition at line 470 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (uint16_t & v)
Extract an unsigned short from the stream.
Parameters
v unsigned short to populate
Returns
This stream.
Definition at line 482 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (int16_t & v)
Extract an short from the stream.
Parameters
v short to populate
Returns
This stream.
Definition at line 495 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (uint32_t & v)
Extract an unsigned int from the stream.
Parameters
v unsigned int to populate
Returns
This stream.
Definition at line 508 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (int32_t & v)
Extract an int from the stream.
Parameters
v int to populate
Returns
This stream.
Definition at line 521 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (uint64_t & v)
Extract an unsigned long int from the stream.
Parameters
v unsigned long int to populate
Returns
This stream.
Definition at line 534 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (int64_t & v)
Extract a long int from the stream.
Parameters
v long int to populate
Returns
This stream.
Definition at line 547 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (float & v)
Extract a float from the stream.
Parameters
v float to populate
Returns
This stream.
Definition at line 560 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL IBeStream& pdal::IBeStream::operator>> (double & v)
Extract a double from the stream.
Parameters
v double to populate
Returns
This stream.
Definition at line 574 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL std::istream* pdal::IStream::popStream () inherited
Pop the current stream and return it. The last stream on the stack cannot be popped.
Returns
Pointer to the popped stream.
Definition at line 187 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::IStream::m_streams.
Referenced by pdal::BpfReader::done().
PDAL_DLL std::streampos pdal::IStream::position () const inherited
Determine the position of the get pointer.
Returns
Current get position.
Definition at line 151 of file IStream.hpp.
References pdal::IStream::m_stream.
Referenced by pdal::QfitReader::initialize(), pdal::BpfReader::initialize(), pdal::BpfReader::readHeaderExtraData(), and pdal::BpfReader::ready().
PDAL_DLL void pdal::IStream::pushStream (std::istream * strm) inherited
Temporarily push a stream to read from.
Parameters
strm New stream to read from.
Definition at line 175 of file IStream.hpp.
References pdal::IStream::m_stream, and pdal::IStream::m_streams.
Referenced by pdal::BpfReader::ready().
PDAL_DLL void pdal::IStream::seek (std::streampos pos) inherited
Seek to a position in the underlying stream.
Parameters
pos Position to seek to,
Definition at line 125 of file IStream.hpp.
References pdal::IStream::m_stream.
Referenced by pdal::lasdump::Dumper::dump(), pdal::QfitReader::initialize(), pdal::BpfReader::initialize(), pdal::operator>>(), pdal::PlyReader::ListProperty::read(), pdal::BpfReader::ready(), pdal::BpfReader::seekByteMajor(), pdal::BpfReader::seekDimMajor(), and pdal::BpfReader::seekPointMajor().
PDAL_DLL void pdal::IStream::seek (std::streampos off, std::ios_base::seekdir way) inherited
Seek to an offset from a specified position.
Parameters
off Offset.
way Absolute position for offset (beg, end or cur)
Definition at line 135 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL void pdal::IStream::skip (std::streamoff offset) inherited
Skip relative to the current position.
Parameters
offset Offset from the current position.
Definition at line 143 of file IStream.hpp.
References pdal::IStream::m_stream.
PDAL_DLL std::istream* pdal::IStream::stream () inherited
Fetch a pointer to the underlying stream.
Returns
Pointer to the underlying stream.
Definition at line 167 of file IStream.hpp.
References pdal::IStream::m_stream.
Referenced by pdal::lasdump::Dumper::readCompressedPoints().
Member Data Documentation
std::ifstream* pdal::IStream::m_fstream protected inherited
Definition at line 255 of file IStream.hpp.
Referenced by pdal::IStream::close(), pdal::IStream::open(), and pdal::IStream::~IStream().
std::istream* pdal::IStream::m_stream protected inherited
Definition at line 254 of file IStream.hpp.
Referenced by pdal::IStream::close(), pdal::IStream::get(), pdal::IStream::good(), pdal::IStreamMarker::IStreamMarker(), pdal::IStream::open(), pdal::ILeStream::operator>>(), operator>>(), pdal::ISwitchableStream::operator>>(), pdal::IStream::popStream(), pdal::IStream::position(), pdal::IStream::pushStream(), pdal::IStreamMarker::rewind(), pdal::IStream::seek(), pdal::IStream::skip(), and pdal::IStream::stream().
The documentation for this class was generated from the following file:
pdal/pdal/util/IStream.hpp