PDAL: Support Class Reference
Support Class Reference
#include <Support.hpp>
Static Public Member Functions
static std::string datapath ()
static std::string datapath (const std::string &file)
static std::string configuredpath ()
static std::string configuredpath (const std::string &file)
static std::string temppath ()
static std::string temppath (const std::string &file)
static std::string binpath ()
static std::string binpath (const std::string &file)
static std::string exename (const std::string &name)
static uint32_t diff_files (const std::string &file1, const std::string &file2)
static uint32_t diff_files (std::istream &str1, std::istream &str2)
static uint32_t diff_files (const std::string &file1, const std::string &file2, uint32_t ignorable_start, uint32_t ignorable_length)
static uint32_t diff_files (const std::string &file1, const std::string &file2, uint32_t *ignorable_start, uint32_t *ignorable_length, uint32_t num_ignorables)
static uint32_t diff_files (std::istream &str1, std::istream &str2, uint32_t *ignorable_start, uint32_t *ignorable_length, uint32_t num_ignorables)
static uint32_t diff_text_files (const std::string &file1, const std::string &file2, int32_t ignoreLine1=-1)
static uint32_t diff_text_files (std::istream &str1, std::istream &str2, int32_t ignoreLine1=-1)
static bool compare_files (const std::string &file1, const std::string &file2)
static bool compare_text_files (const std::string &file1, const std::string &file2)
static bool compare_text_files (std::istream &str1, std::istream &str2)
static void checkXYZ (const std::string &file1, const std::string &file2)
static void check_pN (const pdal::PointView &data, pdal::PointId index, double xref, double yref, double zref)
static void check_pN (const pdal::PointView &data, pdal::PointId index, double xref, double yref, double zref, double tref, uint16_t rref, uint16_t gref, uint16_t bref)
static void check_p0_p1_p2 (const pdal::PointView &data)
static void check_p100_p101_p102 (const pdal::PointView &data)
static void check_p355_p356_p357 (const pdal::PointView &data)
static void check_p710_p711_p712 (const pdal::PointView &data)
static void compareBounds (const pdal::BOX3D &p, const pdal::BOX3D &q)
Detailed Description
Definition at line 50 of file Support.hpp.
Member Function Documentation
std::string Support::binpath () static
Definition at line 83 of file Support.cpp.
References TestConfig::binaryPath().
Referenced by anonymous_namespace{AppTest.cpp}::appName(), anonymous_namespace{MergeTest.cpp}::appName(), appName(), anonymous_namespace{pcpipelineTestJSON.cpp}::appName(), run_pipeline(), runTranslate(), TEST(), and pdal::TEST().
std::string Support::binpath (const std::string & file) static
Definition at line 94 of file Support.cpp.
void Support::check_p0_p1_p2 (const pdal::PointView & data) static
Definition at line 374 of file Support.cpp.
References check_pN().
Referenced by TEST().
void Support::check_p100_p101_p102 (const pdal::PointView & data) static
Definition at line 382 of file Support.cpp.
References check_pN().
Referenced by TEST().
void Support::check_p355_p356_p357 (const pdal::PointView & data) static
Definition at line 390 of file Support.cpp.
References check_pN().
void Support::check_p710_p711_p712 (const pdal::PointView & data) static
Definition at line 398 of file Support.cpp.
References check_pN().
void Support::check_pN (const pdal::PointView & data, pdal::PointId index, double xref, double yref, double zref) static
Definition at line 337 of file Support.cpp.
References pdal::PointView::getFieldAs(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by check_p0_p1_p2(), check_p100_p101_p102(), check_p355_p356_p357(), check_p710_p711_p712(), and test_a_format().
void Support::check_pN (const pdal::PointView & data, pdal::PointId index, double xref, double yref, double zref, double tref, uint16_t rref, uint16_t gref, uint16_t bref) static
Definition at line 350 of file Support.cpp.
References pdal::Dimension::Blue, pdal::PointView::getFieldAs(), pdal::Dimension::GpsTime, pdal::Dimension::Green, pdal::PointView::hasDim(), and pdal::Dimension::Red.
void Support::checkXYZ (const std::string & file1, const std::string & file2) static
Definition at line 288 of file Support.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::StageFactory::inferReaderDriver(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by TEST().
bool Support::compare_files (const std::string & file1, const std::string & file2) static
Definition at line 271 of file Support.cpp.
Referenced by TEST().
bool Support::compare_text_files (const std::string & file1, const std::string & file2) static
Definition at line 276 of file Support.cpp.
Referenced by pdal::TEST(), and TEST().
bool Support::compare_text_files (std::istream & str1, std::istream & str2) static
Definition at line 282 of file Support.cpp.
void Support::compareBounds (const pdal::BOX3D & p, const pdal::BOX3D & q) static
Definition at line 406 of file Support.cpp.
References pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
string Support::configuredpath () static
Definition at line 63 of file Support.cpp.
References TestConfig::configuredPath().
Referenced by anonymous_namespace{pcpipelineTestJSON.cpp}::run_pipeline(), run_pipeline(), anonymous_namespace{pcpipelineTestJSON.cpp}::run_pipeline_stdin(), pdal::TEST(), TEST(), and TEST_F().
std::string Support::configuredpath (const std::string & file) static
Definition at line 68 of file Support.cpp.
string Support::datapath () static
Definition at line 53 of file Support.cpp.
References TestConfig::dataPath().
Referenced by GDALReaderTypeTest::GDALReaderTypeTest(), getBytes(), getFilePath(), pdal::getJSON(), pdal::anonymous_namespace{OptechReaderTest.cpp}::getTestfilePath(), pdal::anonymous_namespace{TerrasolidReaderTest.cpp}::getTestfilePath(), pdal::getWKT(), makeReaderOptions(), pdal::anonymous_namespace{IcpFilterTest.cpp}::newReader(), pdal::anonymous_namespace{CpdFilterTest.cpp}::newReader(), anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite(), readData(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), streamTest(), TEST(), pdal::TEST(), test_a_format(), TEST_F(), test_filter(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testOverlay(), testReadWrite(), and writeData().
std::string Support::datapath (const std::string & file) static
Definition at line 58 of file Support.cpp.
uint32_t Support::diff_files (const std::string & file1, const std::string & file2) static
Definition at line 260 of file Support.cpp.
Referenced by pdal::TEST(), and TEST().
uint32_t Support::diff_files (std::istream & str1, std::istream & str2) static
Definition at line 266 of file Support.cpp.
uint32_t Support::diff_files (const std::string & file1, const std::string & file2, uint32_t ignorable_start, uint32_t ignorable_length) static
Definition at line 184 of file Support.cpp.
uint32_t Support::diff_files (const std::string & file1, const std::string & file2, uint32_t * ignorable_start, uint32_t * ignorable_length, uint32_t num_ignorables) static
Definition at line 195 of file Support.cpp.
References pdal::Utils::closeFile(), pdal::Utils::fileExists(), and pdal::Utils::openFile().
uint32_t Support::diff_files (std::istream & str1, std::istream & str2, uint32_t * ignorable_start, uint32_t * ignorable_length, uint32_t num_ignorables) static
Definition at line 214 of file Support.cpp.
uint32_t Support::diff_text_files (const std::string & file1, const std::string & file2, int32_t ignoreLine1 = -1) static
Definition at line 110 of file Support.cpp.
References pdal::Utils::closeFile(), pdal::Utils::fileExists(), and pdal::Utils::openFile().
Referenced by TEST().
uint32_t Support::diff_text_files (std::istream & str1, std::istream & str2, int32_t ignoreLine1 = -1) static
Definition at line 126 of file Support.cpp.
std::string Support::exename (const std::string & name) static
Definition at line 99 of file Support.cpp.
References pdal::Dimension::name().
Referenced by appName(), anonymous_namespace{pcpipelineTestJSON.cpp}::appName(), run_pipeline(), runTranslate(), TEST(), and pdal::TEST().
std::string Support::temppath () static
Definition at line 73 of file Support.cpp.
References TestConfig::dataPath().
Referenced by compareTextLasStreaming(), makeWriterOptions(), TEST(), pdal::TEST(), pdal::TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), and testOverlay().
std::string Support::temppath (const std::string & file) static
Definition at line 78 of file Support.cpp.
The documentation for this class was generated from the following files:
pdal/test/unit/Support.hpp
pdal/test/unit/Support.cpp