PDAL: pdal::OLeStream Class Reference
pdal::OLeStream Class Reference
#include <OStream.hpp>
Public Member Functions
PDAL_DLL OLeStream ()
PDAL_DLL OLeStream (const std::string &filename)
PDAL_DLL OLeStream (std::ostream *stream)
PDAL_DLL OLeStream & operator<< (uint8_t v)
PDAL_DLL OLeStream & operator<< (int8_t v)
PDAL_DLL OLeStream & operator<< (uint16_t v)
PDAL_DLL OLeStream & operator<< (int16_t v)
PDAL_DLL OLeStream & operator<< (uint32_t v)
PDAL_DLL OLeStream & operator<< (int32_t v)
PDAL_DLL OLeStream & operator<< (uint64_t v)
PDAL_DLL OLeStream & operator<< (int64_t v)
PDAL_DLL OLeStream & operator<< (float v)
PDAL_DLL OLeStream & operator<< (double v)
PDAL_DLL int open (const std::string &filename)
PDAL_DLL void close ()
PDAL_DLL bool isOpen () const
PDAL_DLL void flush ()
PDAL_DLL operator bool ()
PDAL_DLL void seek (std::streampos pos)
PDAL_DLL void put (const std::string &s)
PDAL_DLL void put (const std::string &s, size_t len)
PDAL_DLL void put (const char *c, size_t len)
PDAL_DLL void put (const unsigned char *c, size_t len)
PDAL_DLL std::streampos position () const
PDAL_DLL void pushStream (std::ostream *strm)
PDAL_DLL std::ostream * popStream ()
Protected Attributes
std::ostream * m_stream
std::ostream * m_fstream
Detailed Description
Stream wrapper for output of binary data that converts from host ordering to little endian format
Definition at line 126 of file OStream.hpp.
Constructor & Destructor Documentation
PDAL_DLL pdal::OLeStream::OLeStream ()
Definition at line 129 of file OStream.hpp.
PDAL_DLL pdal::OLeStream::OLeStream (const std::string & filename)
Definition at line 131 of file OStream.hpp.
PDAL_DLL pdal::OLeStream::OLeStream (std::ostream * stream)
Definition at line 133 of file OStream.hpp.
Member Function Documentation
PDAL_DLL void pdal::OStream::close () inherited
Definition at line 70 of file OStream.hpp.
References pdal::OStream::flush(), pdal::OStream::m_fstream, and pdal::OStream::m_stream.
Referenced by pdal::BpfWriter::doneFile().
PDAL_DLL void pdal::OStream::flush () inherited
Definition at line 79 of file OStream.hpp.
References pdal::OStream::m_stream.
Referenced by pdal::OStream::close().
PDAL_DLL bool pdal::OStream::isOpen () const inherited
Definition at line 77 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL int pdal::OStream::open (const std::string & filename) inherited
Definition at line 62 of file OStream.hpp.
References pdal::OStream::m_fstream, and pdal::OStream::m_stream.
Referenced by pdal::OStream::OStream(), and pdal::BpfWriter::readyFile().
PDAL_DLL pdal::OStream::operator bool () inherited
Definition at line 81 of file OStream.hpp.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (uint8_t v)
Definition at line 136 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (int8_t v)
Definition at line 142 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (uint16_t v)
Definition at line 148 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (int16_t v)
Definition at line 155 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (uint32_t v)
Definition at line 162 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (int32_t v)
Definition at line 169 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (uint64_t v)
Definition at line 176 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (int64_t v)
Definition at line 183 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (float v)
Definition at line 190 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OLeStream& pdal::OLeStream::operator<< (double v)
Definition at line 199 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL std::ostream* pdal::OStream::popStream () inherited
Definition at line 104 of file OStream.hpp.
References pdal::OStream::m_stream, and pdal::OStream::m_streams.
PDAL_DLL std::streampos pdal::OStream::position () const inherited
Definition at line 97 of file OStream.hpp.
References pdal::OStream::m_stream.
Referenced by pdal::BpfWriter::readyFile().
PDAL_DLL void pdal::OStream::pushStream (std::ostream * strm) inherited
Definition at line 99 of file OStream.hpp.
References pdal::OStream::m_stream, and pdal::OStream::m_streams.
PDAL_DLL void pdal::OStream::put (const std::string & s) inherited
Definition at line 85 of file OStream.hpp.
Referenced by pdal::operator<<(), pdal::LasHeader::put(), pdal::BpfWriter::readyFile(), pdal::BpfDimension::write(), pdal::BpfHeader::write(), and pdal::BpfUlemFile::write().
PDAL_DLL void pdal::OStream::put (const std::string & s, size_t len) inherited
Definition at line 87 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL void pdal::OStream::put (const char * c, size_t len) inherited
Definition at line 93 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL void pdal::OStream::put (const unsigned char * c, size_t len) inherited
Definition at line 95 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL void pdal::OStream::seek (std::streampos pos) inherited
Definition at line 83 of file OStream.hpp.
References pdal::OStream::m_stream.
Referenced by pdal::BpfWriter::doneFile(), and pdal::LasWriter::finishOutput().
Member Data Documentation
std::ostream* pdal::OStream::m_fstream protected inherited
Definition at line 117 of file OStream.hpp.
Referenced by pdal::OStream::close(), pdal::OStream::open(), and pdal::OStream::~OStream().
std::ostream* pdal::OStream::m_stream protected inherited
Definition at line 116 of file OStream.hpp.
Referenced by pdal::OStream::close(), pdal::OStream::flush(), pdal::OStream::isOpen(), pdal::OStreamMarker::mark(), pdal::OStream::open(), operator<<(), pdal::OBeStream::operator<<(), pdal::OStreamMarker::OStreamMarker(), pdal::OStream::popStream(), pdal::OStream::position(), pdal::OStream::pushStream(), pdal::OStream::put(), pdal::OStreamMarker::rewind(), and pdal::OStream::seek().
The documentation for this class was generated from the following file:
pdal/pdal/util/OStream.hpp