PDAL: pdal::Geometry Class Reference
pdal::Geometry Class Reference
#include <Geometry.hpp>
Public Member Functions
Geometry ()
virtual ~Geometry ()
Geometry (const std::string &wkt_or_json, SpatialReference ref=SpatialReference())
Geometry (GEOSGeometry *g, const SpatialReference &srs)
Geometry (OGRGeometryH g, const SpatialReference &srs)
Geometry (const Geometry &)
Geometry & operator= (const Geometry &)
OGRGeometryH getOGRHandle ()
virtual void update (const std::string &wkt_or_json)
void setSpatialReference (const SpatialReference &ref)
const SpatialReference & getSpatialReference () const
Geometry transform (const SpatialReference &ref) const
bool equals (const Geometry &other, double tolerance=0.0001) const
bool operator== (const Geometry &other) const
bool operator!= (const Geometry &other) const
bool operator< (const Geometry &other) const
virtual bool valid () const
virtual std::string validReason () const
std::string wkt (double precision=8, bool bOutputZ=false) const
std::string json (double precision=8) const
BOX3D bounds () const
operator bool () const
Protected Member Functions
void prepare ()
Protected Attributes
GEOSGeomPtr m_geom
const GEOSPreparedGeometry * m_prepGeom
SpatialReference m_srs
geos::ErrorHandler & m_geoserr
Friends
PDAL_DLL std::ostream & operator<< (std::ostream &ostr, const Geometry &p)
PDAL_DLL std::istream & operator>> (std::istream &istr, Geometry &p)
Detailed Description
Definition at line 85 of file Geometry.hpp.
Constructor & Destructor Documentation
pdal::Geometry::Geometry ()
Definition at line 44 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, and m_geoserr.
Referenced by transform().
pdal::Geometry::~Geometry () virtual
Definition at line 63 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, m_geoserr, and m_prepGeom.
pdal::Geometry::Geometry (const std::string & wkt_or_json, SpatialReference ref = SpatialReference())
Definition at line 54 of file Geometry.cpp.
References update().
pdal::Geometry::Geometry (GEOSGeometry * g, const SpatialReference & srs)
Definition at line 155 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, m_geoserr, and prepare().
pdal::Geometry::Geometry (OGRGeometryH g, const SpatialReference & srs)
Definition at line 165 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, m_geoserr, and prepare().
pdal::Geometry::Geometry (const Geometry & input)
Definition at line 140 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, m_geoserr, m_prepGeom, and prepare().
Member Function Documentation
BOX3D pdal::Geometry::bounds () const
Definition at line 213 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::BOX3D::grow(), m_geom, m_geoserr, and z.
Referenced by pdal::StatsFilter::extractMetadata(), pdal::TEST(), and TEST().
bool pdal::Geometry::equals (const Geometry & other, double tolerance = 0.0001) const
Definition at line 249 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, and m_geoserr.
Referenced by operator!=(), and operator==().
OGRGeometryH pdal::Geometry::getOGRHandle ()
const SpatialReference& pdal::Geometry::getSpatialReference () const
Definition at line 106 of file Geometry.hpp.
References pdal::operator!=(), and pdal::operator==().
std::string pdal::Geometry::json (double precision = 8) const
Definition at line 306 of file Geometry.cpp.
References pdal::SpatialReference::getWKT(), m_srs, and wkt().
Referenced by pdal::StatsFilter::extractMetadata(), and pdal::TEST().
pdal::Geometry::operator bool () const
Definition at line 126 of file Geometry.hpp.
bool pdal::Geometry::operator!= (const Geometry & other) const
Definition at line 262 of file Geometry.cpp.
References equals().
bool pdal::Geometry::operator< (const Geometry & other) const
Definition at line 114 of file Geometry.hpp.
References wkt().
Geometry & pdal::Geometry::operator= (const Geometry & input)
Definition at line 124 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, m_geoserr, m_srs, and prepare().
bool pdal::Geometry::operator== (const Geometry & other) const
Definition at line 256 of file Geometry.cpp.
References equals().
void pdal::Geometry::prepare () protected
Definition at line 112 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, m_geoserr, and m_prepGeom.
Referenced by Geometry(), pdal::Polygon::initializeFromBounds(), pdal::Polygon::operator=(), operator=(), pdal::Polygon::Polygon(), and update().
void pdal::Geometry::setSpatialReference (const SpatialReference & ref)
Definition at line 103 of file Geometry.hpp.
Referenced by TEST().
Geometry pdal::Geometry::transform (const SpatialReference & ref) const
Definition at line 194 of file Geometry.cpp.
References pdal::SpatialReference::empty(), Geometry(), pdal::SpatialReference::getWKT(), m_srs, and wkt().
void pdal::Geometry::update (const std::string & wkt_or_json) virtual
Reimplemented in pdal::filter::Point.
Definition at line 72 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, m_geoserr, and prepare().
Referenced by Geometry(), pdal::operator>>(), and pdal::filter::Point::update().
bool pdal::Geometry::valid () const virtual
Definition at line 268 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, and m_geoserr.
Referenced by pdal::TEST().
std::string pdal::Geometry::validReason () const virtual
Definition at line 278 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, and m_geoserr.
std::string pdal::Geometry::wkt (double precision = 8, bool bOutputZ = false) const
Definition at line 289 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), m_geom, and m_geoserr.
Referenced by json(), operator<(), pdal::operator<<(), pdal::TEST(), pdal::Polygon::transform(), and transform().
Friends And Related Function Documentation
PDAL_DLL std::ostream& operator<< (std::ostream & ostr, const Geometry & p) friend
Definition at line 324 of file Geometry.cpp.
PDAL_DLL std::istream& operator>> (std::istream & istr, Geometry & p) friend
Definition at line 331 of file Geometry.cpp.
Member Data Documentation
GEOSGeomPtr pdal::Geometry::m_geom protected
Definition at line 131 of file Geometry.hpp.
Referenced by pdal::Polygon::area(), bounds(), pdal::Polygon::contains(), pdal::Polygon::covers(), pdal::Polygon::crosses(), equals(), Geometry(), pdal::Polygon::initializeFromBounds(), pdal::Polygon::operator=(), operator=(), pdal::Polygon::overlaps(), pdal::Polygon::Polygon(), prepare(), pdal::Polygon::simplify(), pdal::Polygon::touches(), pdal::filter::Point::update(), update(), valid(), validReason(), pdal::Polygon::within(), wkt(), and ~Geometry().
geos::ErrorHandler& pdal::Geometry::m_geoserr protected
Definition at line 135 of file Geometry.hpp.
Referenced by pdal::Polygon::area(), bounds(), pdal::Polygon::contains(), pdal::Polygon::covers(), pdal::Polygon::crosses(), equals(), Geometry(), pdal::Polygon::initializeFromBounds(), pdal::Polygon::operator=(), operator=(), pdal::Polygon::overlaps(), pdal::Polygon::Polygon(), prepare(), pdal::Polygon::simplify(), pdal::Polygon::touches(), pdal::filter::Point::update(), update(), valid(), validReason(), pdal::Polygon::within(), wkt(), and ~Geometry().
const GEOSPreparedGeometry* pdal::Geometry::m_prepGeom protected
Definition at line 132 of file Geometry.hpp.
Referenced by pdal::Polygon::covers(), Geometry(), prepare(), and ~Geometry().
SpatialReference pdal::Geometry::m_srs protected
Definition at line 134 of file Geometry.hpp.
Referenced by json(), pdal::Polygon::operator=(), operator=(), pdal::Polygon::simplify(), pdal::Polygon::transform(), and transform().
The documentation for this class was generated from the following files:
pdal/pdal/Geometry.hpp
pdal/pdal/Geometry.cpp