PDAL: pdal::LasVLR Class Reference
pdal::LasVLR Class Reference
#include <LasVLR.hpp>
Public Member Functions
LasVLR (const std::string &userId, uint16_t recordId, const std::string &description, std::vector< uint8_t > &data)
LasVLR ()
std::string userId () const
uint16_t recordId () const
std::string description () const
bool matches (const std::string &userId) const
bool matches (const std::string &userId, uint16_t recordId) const
const char * data () const
char * data ()
bool isEmpty () const
uint64_t dataLen () const
void setDataLen (uint64_t size)
void write (OLeStream &out, uint16_t recordSig)
Static Public Attributes
static const uint16_t MAX_DATA_SIZE = 65535
Protected Attributes
std::string m_userId
uint16_t m_recordId
std::string m_description
std::vector< uint8_t > m_data
uint16_t m_recordSig
Friends
ILeStream & operator>> (ILeStream &in, LasVLR &v)
OLeStream & operator<< (OLeStream &out, const LasVLR &v)
Detailed Description
Definition at line 66 of file LasVLR.hpp.
Constructor & Destructor Documentation
pdal::LasVLR::LasVLR (const std::string & userId, uint16_t recordId, const std::string & description, std::vector< uint8_t > & data)
Definition at line 71 of file LasVLR.hpp.
pdal::LasVLR::LasVLR ()
Definition at line 76 of file LasVLR.hpp.
Member Function Documentation
const char* pdal::LasVLR::data () const
Definition at line 91 of file LasVLR.hpp.
Referenced by pdal::LasReader::extractHeaderMetadata(), pdal::operator<<(), pdal::LasReader::readExtraBytesVlr(), pdal::LasReader::ready(), pdal::LasHeader::setSrsFromGeotiff(), and pdal::LasHeader::setSrsFromWkt().
char* pdal::LasVLR::data ()
Definition at line 93 of file LasVLR.hpp.
uint64_t pdal::LasVLR::dataLen () const
Definition at line 97 of file LasVLR.hpp.
Referenced by pdal::operator<<(), pdal::LasReader::readExtraBytesVlr(), pdal::LasHeader::setSrsFromGeotiff(), and pdal::LasHeader::setSrsFromWkt().
std::string pdal::LasVLR::description () const
Definition at line 83 of file LasVLR.hpp.
Referenced by pdal::operator<<().
bool pdal::LasVLR::isEmpty () const
Definition at line 95 of file LasVLR.hpp.
Referenced by pdal::LasHeader::setSrsFromGeotiff().
bool pdal::LasVLR::matches (const std::string & userId) const
Definition at line 86 of file LasVLR.hpp.
Referenced by pdal::LasHeader::findVlr().
bool pdal::LasVLR::matches (const std::string & userId, uint16_t recordId) const
Definition at line 88 of file LasVLR.hpp.
uint16_t pdal::LasVLR::recordId () const
Definition at line 81 of file LasVLR.hpp.
Referenced by pdal::operator<<().
void pdal::LasVLR::setDataLen (uint64_t size)
Definition at line 99 of file LasVLR.hpp.
References pdal::operator<<(), and pdal::operator>>().
std::string pdal::LasVLR::userId () const
Definition at line 79 of file LasVLR.hpp.
Referenced by pdal::operator<<().
void pdal::LasVLR::write (OLeStream & out, uint16_t recordSig)
Definition at line 100 of file LasVLR.cpp.
References m_recordSig.
Referenced by pdal::LasWriter::prepOutput().
Friends And Related Function Documentation
OLeStream& operator<< (OLeStream & out, const LasVLR & v) friend
Definition at line 60 of file LasVLR.cpp.
ILeStream& operator>> (ILeStream & in, LasVLR & v) friend
Definition at line 42 of file LasVLR.cpp.
Member Data Documentation
std::vector<uint8_t> pdal::LasVLR::m_data protected
Definition at line 110 of file LasVLR.hpp.
Referenced by pdal::operator>>().
std::string pdal::LasVLR::m_description protected
Definition at line 109 of file LasVLR.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
uint16_t pdal::LasVLR::m_recordId protected
Definition at line 108 of file LasVLR.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
uint16_t pdal::LasVLR::m_recordSig protected
Definition at line 111 of file LasVLR.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and write().
std::string pdal::LasVLR::m_userId protected
Definition at line 107 of file LasVLR.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
const uint16_t pdal::LasVLR::MAX_DATA_SIZE = 65535 static
Definition at line 69 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addMetadataVlr(), pdal::LasWriter::addPipelineVlr(), and pdal::LasWriter::addVlr().
The documentation for this class was generated from the following files:
pdal/io/LasVLR.hpp
pdal/io/LasVLR.cpp