PDAL: pdal::DynamicLibrary Class Reference
pdal::DynamicLibrary Class Reference
#include <DynamicLibrary.hpp>
Public Member Functions
~DynamicLibrary ()
void * getSymbol (const std::string &name)
void clear ()
Static Public Member Functions
static DynamicLibrary * load (const std::string &path, std::string &errorString)
Private Member Functions
DynamicLibrary (void *handle)
DynamicLibrary ()
DynamicLibrary (const DynamicLibrary &)
Private Attributes
void * m_handle
Detailed Description
Definition at line 47 of file DynamicLibrary.hpp.
Constructor & Destructor Documentation
pdal::DynamicLibrary::~DynamicLibrary ()
Definition at line 54 of file DynamicLibrary.cpp.
References m_handle.
pdal::DynamicLibrary::DynamicLibrary (void * handle) private
Definition at line 58 of file DynamicLibrary.hpp.
References DynamicLibrary().
pdal::DynamicLibrary::DynamicLibrary () private
Referenced by DynamicLibrary(), and load().
pdal::DynamicLibrary::DynamicLibrary (const DynamicLibrary &) private
Member Function Documentation
void pdal::DynamicLibrary::clear ()
Definition at line 67 of file DynamicLibrary.cpp.
References m_handle.
void * pdal::DynamicLibrary::getSymbol (const std::string & name)
Definition at line 113 of file DynamicLibrary.cpp.
References m_handle.
DynamicLibrary * pdal::DynamicLibrary::load (const std::string & path, std::string & errorString) static
Definition at line 73 of file DynamicLibrary.cpp.
References DynamicLibrary().
Referenced by pdal::PluginManager::loadLibrary().
Member Data Documentation
void* pdal::DynamicLibrary::m_handle private
Definition at line 65 of file DynamicLibrary.hpp.
Referenced by clear(), getSymbol(), and ~DynamicLibrary().
The documentation for this class was generated from the following files:
pdal/pdal/private/DynamicLibrary.hpp
pdal/pdal/DynamicLibrary.cpp