PDAL: pdal::Stage Class Reference
pdal::Stage Class Reference abstract
#include <Stage.hpp>
Public Member Functions
Stage ()
virtual ~Stage ()
void setInput (Stage &input)
void setProgressFd (int fd)
QuickInfo preview ()
void prepare (PointTableRef table)
PointViewSet execute (PointTableRef table)
void execute (StreamPointTable &table)
void setSpatialReference (SpatialReference const &srs)
const SpatialReference & getSpatialReference () const
void setOptions (Options options)
void addConditionalOptions (const Options &opts)
void addAllArgs (ProgramArgs &args)
void addOptions (const Options &opts)
void removeOptions (const Options &opts)
void setLog (LogPtr &log)
virtual LogPtr log () const
void startLogging () const
void stopLogging () const
bool isDebug () const
virtual std::string getName () const =0
void setTag (const std::string &tag)
virtual std::string tag () const
std::vector< Stage * > & getInputs ()
MetadataNode getMetadata () const
void serialize (MetadataNode root, PipelineWriter::TagMap &tags) const
Static Public Member Functions
static bool parseName (std::string o, std::string::size_type &pos)
static bool parseTagName (std::string o, std::string::size_type &pos)
Protected Member Functions
void setSpatialReference (MetadataNode &m, SpatialReference const &)
void addSpatialReferenceArg (ProgramArgs &args)
void throwError (const std::string &s) const
point_count_t pointCount () const
point_count_t faceCount () const
void throwStreamingError () const
Protected Attributes
Options m_options
Stage's options.
MetadataNode m_metadata
Stage's metadata.
int m_progressFd
Descriptor for progress info.
Private Member Functions
FRIEND_TEST (OptionsTest, conditional)
Stage & operator= (const Stage &)
Stage (const Stage &)
void setupLog ()
void handleOptions ()
virtual void readerAddArgs (ProgramArgs &)
void l_addArgs (ProgramArgs &args)
void l_done (PointTableRef table)
virtual void writerInitialize (PointTableRef)
void l_initialize (PointTableRef table)
virtual QuickInfo inspect ()
virtual void addArgs (ProgramArgs &)
virtual void processOptions (const Options &)
virtual void initialize (PointTableRef)
virtual void initialize ()
virtual void addDimensions (PointLayoutPtr)
virtual void prepared (PointTableRef)
virtual void ready (PointTableRef)
virtual bool processOne (PointRef &)
virtual void spatialReferenceChanged (const SpatialReference &srs)
virtual PointViewSet run (PointViewPtr)
virtual void done (PointTableRef)
void execute (StreamPointTable &table, std::list< Stage * > &stages)
const Options & getOptions () const
Private Attributes
uint32_t m_verbose
std::string m_logname
std::vector< Stage * > m_inputs
LogPtr m_log
std::string m_logLeader
SpatialReference m_spatialReference
std::unique_ptr< ProgramArgs > m_args
std::string m_tag
std::string m_userDataJSON
point_count_t m_pointCount
point_count_t m_faceCount
std::string m_optionFile
Friends
class StageWrapper
class StageRunner
Detailed Description
A stage performs the actual processing in PDAL. Stages may read data, modify or filter read data, create metadata or write processed data.
Stages are linked with setInput() into a pipeline. The pipeline is run with by calling in sequence prepare() and execute() on the stage at the end of the pipeline. PipelineManager can also be used to create and run a pipeline.
Definition at line 70 of file Stage.hpp.
Constructor & Destructor Documentation
pdal::Stage::Stage ()
Definition at line 52 of file Stage.cpp.
virtual pdal::Stage::~Stage () virtual
Definition at line 77 of file Stage.hpp.
pdal::Stage::Stage (const Stage &) private
Member Function Documentation
void pdal::Stage::addAllArgs (ProgramArgs & args)
Add a stage's options to a ProgramArgs set.
Parameters
args ProgramArgs to add to.
Definition at line 84 of file Stage.cpp.
References addArgs(), getName(), l_addArgs(), and pdal::arg_error::m_error.
Referenced by handleOptions(), and App::outputOptions().
virtual void pdal::Stage::addArgs (ProgramArgs &) private virtual
Add arguments(options) handled by this stage. Implement in subclass.
Parameters
args ProgramArgs object to which arguments should be added.
Reimplemented in pdal::GreedyProjection, pdal::StatsFilter, pdal::FauxReader, pdal::LasWriter, pdal::LasReader, pdal::ChipperFilter, pdal::PgReader, pdal::Ilvis2Reader, pdal::MrsidReader, pdal::ColorizationFilter, pdal::BpfWriter, pdal::MbReader, pdal::RxpReader, pdal::OverlayFilter, pdal::QfitReader, pdal::ColorinterpFilter, pdal::MongusFilter, pdal::NormalFilter, pdal::OutlierFilter, pdal::TIndexReader, pdal::DividerFilter, pdal::SortFilter, pdal::SplitterFilter, pdal::IcebridgeReader, pdal::SMRFilter, pdal::MatlabReader, pdal::SQLiteReader, pdal::ApproximateCoplanarFilter, pdal::CropFilter, pdal::FerryFilter, pdal::HexBin, pdal::EstimateRankFilter, pdal::TransformationFilter, pdal::DbWriter, pdal::EigenvaluesFilter, pdal::TextReader, pdal::PMFFilter, pdal::OGRWriter, pdal::ELMFilter, pdal::MADFilter, pdal::IQRFilter, pdal::LocateFilter, pdal::ClusterFilter, pdal::GroupByFilter, pdal::KDistanceFilter, pdal::LOFFilter, pdal::PoissonFilter, pdal::RadialDensityFilter, pdal::RangeFilter, pdal::SampleFilter, pdal::VoxelCenterNearestNeighborFilter, pdal::VoxelCentroidNearestNeighborFilter, pdal::PythonFilter, pdal::ReprojectionFilter, pdal::PlyWriter, pdal::PcdWriter, pdal::DecimationFilter, pdal::GeoWaveReader, pdal::MatlabFilter, pdal::CpdFilter, pdal::GreyhoundReader, pdal::HeadFilter, pdal::TailFilter, pdal::GDALWriter, pdal::PCLBlock, pdal::SbetWriter, pdal::NitfWriter, pdal::OciReader, pdal::AssignFilter, pdal::TextWriter, pdal::MatlabWriter, pdal::PgWriter, pdal::SQLiteWriter, pdal::VoxelGridFilter, pdal::GeoWaveWriter, pdal::OciWriter, pdal::MyFilter, pdal::MyReader, and pdal::MyWriter.
Definition at line 394 of file Stage.hpp.
Referenced by addAllArgs().
void pdal::Stage::addConditionalOptions (const Options & opts)
Add options if an option with the same name doesn't already exist on the stage.
Parameters
opts Options to add.
Definition at line 57 of file Stage.cpp.
References pdal::Options::addConditional(), pdal::Options::getOptions(), and m_options.
Referenced by pdal::TEST().
virtual void pdal::Stage::addDimensions (PointLayoutPtr) private virtual
Add dimensions to a layout.
Parameters
layout Point layout.
Reimplemented in pdal::GreedyProjection, pdal::FauxReader, pdal::LasReader, pdal::PlyReader, pdal::TerrasolidReader, pdal::PgReader, pdal::Ilvis2Reader, pdal::BpfReader, pdal::ColorizationFilter, pdal::RxpReader, pdal::ColorinterpFilter, pdal::QfitReader, pdal::MatlabReader, pdal::MbReader, pdal::NormalFilter, pdal::TextReader, pdal::MongusFilter, pdal::OutlierFilter, pdal::SMRFilter, pdal::TIndexReader, pdal::MrsidReader, pdal::OptechReader, pdal::IcebridgeReader, pdal::SQLiteReader, pdal::FerryFilter, pdal::PtsReader, pdal::ApproximateCoplanarFilter, pdal::EstimateRankFilter, pdal::EigenvaluesFilter, pdal::ELMFilter, pdal::PMFFilter, pdal::GDALReader, pdal::SbetReader, pdal::ClusterFilter, pdal::KDistanceFilter, pdal::LOFFilter, pdal::RadialDensityFilter, pdal::OSGReader, pdal::PythonFilter, pdal::HAGFilter, pdal::SampleFilter, pdal::ComputeRangeFilter, pdal::PoissonFilter, pdal::GeoWaveReader, pdal::GreyhoundReader, pdal::MatlabFilter, pdal::OciReader, pdal::PcdReader, pdal::MyFilter, and pdal::MyReader.
Definition at line 428 of file Stage.hpp.
Referenced by pdal::StageWrapper::addDimensions(), and prepare().
void pdal::Stage::addOptions (const Options & opts)
Add options to the existing option set.
Parameters
opts Options to add.
Definition at line 195 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions(), and TEST().
void pdal::Stage::addSpatialReferenceArg (ProgramArgs & args) protected
Definition at line 468 of file Stage.cpp.
References pdal::ProgramArgs::add(), and m_spatialReference.
Referenced by pdal::OciReader::addArgs(), and pdal::PgReader::addArgs().
virtual void pdal::Stage::done (PointTableRef) private virtual
Called after all point views have been processed. Implement in subclass.
Parameters
table PointTable associated with pipeline.
Reimplemented in pdal::StatsFilter, pdal::LasReader, pdal::PlyReader, pdal::TerrasolidReader, pdal::FlexWriter, pdal::PgReader, pdal::TextReader, pdal::MatlabReader, pdal::PtsReader, pdal::MrsidReader, pdal::BpfReader, pdal::RxpReader, pdal::MbReader, pdal::QfitReader, pdal::IcebridgeReader, pdal::OptechReader, pdal::HexBin, pdal::GDALReader, pdal::OSGReader, pdal::PythonFilter, pdal::PlyWriter, pdal::GeoWaveReader, pdal::MatlabFilter, pdal::PcdWriter, pdal::SbetWriter, pdal::TextWriter, pdal::CpdFilter, pdal::MatlabWriter, pdal::PgWriter, pdal::SQLiteWriter, pdal::OciWriter, pdal::IcpFilter, pdal::MyReader, and pdal::MyWriter.
Definition at line 489 of file Stage.hpp.
Referenced by pdal::StageWrapper::done(), execute(), pdal::GreedyProjection::filter(), and l_done().
PointViewSet pdal::Stage::execute (PointTableRef table)
Execute a prepared pipeline (linked set of stages).
This performs the action associated with the stage by executing the run function of each stage in depth first order. Each stage is run to completion (all points are processed) before the next stages is run.o
Parameters
table Point table being used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 156 of file Stage.cpp.
References pdal::BasePointTable::addSpatialReference(), pdal::BasePointTable::clearSpatialReferences(), pdal::SpatialReference::empty(), execute(), pdal::BasePointTable::finalize(), getSpatialReference(), l_done(), m_faceCount, m_inputs, m_pointCount, ready(), StageRunner, startLogging(), and stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::execute(), execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
void pdal::Stage::execute (StreamPointTable & table)
Execute a prepared pipeline (linked set of stages) in streaming mode.
This performs the action associated with the stage by executing the processOne function of each stage in depth first order. Points are processed up to the capacity of the provided StreamPointTable. Not all stages support streaming mode and an exception will be thrown when attempting to execute an unsupported stage.
Streaming points can reduce memory consumption, but may limit access to algorithms that need to operate on full point sets.
Parameters
table Streming point table used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 239 of file Stage.cpp.
References done(), pdal::SpatialReference::empty(), execute(), pdal::StreamPointTable::finalize(), m_inputs, pdal::entwine::operator-(), ready(), and pdal::BasePointTable::setSpatialReference().
void pdal::Stage::execute (StreamPointTable & table, std::list< Stage * > & stages) private
Definition at line 338 of file Stage.cpp.
References pdal::StreamPointTable::capacity(), pdal::BasePointTable::clearSpatialReferences(), pdal::SpatialReference::empty(), getSpatialReference(), processOne(), pdal::StreamPointTable::reset(), pdal::PointRef::setPointId(), pdal::BasePointTable::setSpatialReference(), startLogging(), and stopLogging().
point_count_t pdal::Stage::faceCount () const protected
Return the count of faces in all primary meshes for all point views. Only valid during execute().
Returns
Total number of faces in all point views being executed.
Definition at line 336 of file Stage.hpp.
Referenced by pdal::PlyWriter::writeHeader().
pdal::Stage::FRIEND_TEST (OptionsTest , conditional) private
std::vector<Stage*>& pdal::Stage::getInputs ()
Return a list of the stage's inputs.
Returns
A vector pointers to input stages.
Definition at line 272 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTags(), pdal::PipelineManager::leaves(), pdal::PipelineManager::replace(), and TEST().
MetadataNode pdal::Stage::getMetadata () const
Get the stage's metadata node.
Returns
Stage's metadata.
Definition at line 280 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{CpdFilter.cpp}::addMetadata(), pdal::CpdFilter::change(), pdal::CpdFilter::cpd_affine(), pdal::CpdFilter::cpd_rigid(), pdal::SbetWriter::done(), pdal::MatlabWriter::done(), pdal::PcdWriter::done(), pdal::PlyWriter::done(), pdal::MbReader::done(), pdal::MrsidReader::done(), pdal::MatlabReader::done(), pdal::GDALWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::LasWriter::doneFile(), pdal::InfoKernel::dump(), pdal::IcpFilter::icp(), pdal::PythonFilter::run(), and TEST().
virtual std::string pdal::Stage::getName () const pure virtual
Return the name of a stage.
Returns
The stage's name.
Implemented in pdal::GreedyProjection, pdal::StatsFilter, pdal::FauxReader, pdal::ChipperFilter, SplitFilter, pdal::TerrasolidReader, pdal::LasReader, pdal::PgReader, pdal::NitfReader, pdal::DummyPlugin, pdal::ColorizationFilter, pdal::LasWriter, pdal::Ilvis2Reader, pdal::RxpReader, pdal::OverlayFilter, pdal::MbReader, pdal::ColorinterpFilter, pdal::TIndexReader, pdal::FerryFilter, pdal::NormalFilter, pdal::IcebridgeReader, pdal::BpfWriter, pdal::SplitterFilter, pdal::OutlierFilter, pdal::QfitReader, pdal::MrsidReader, pdal::SortFilter, pdal::TransformationFilter, pdal::ApproximateCoplanarFilter, pdal::OGRWriter, pdal::EigenvaluesFilter, pdal::EstimateRankFilter, pdal::MongusFilter, pdal::BpfReader, pdal::GDALReader, pdal::HAGFilter, pdal::ELMFilter, pdal::ReprojectionFilter, pdal::VoxelCenterNearestNeighborFilter, pdal::VoxelCentroidNearestNeighborFilter, pdal::OptechReader, pdal::PcdWriter, pdal::CropFilter, pdal::IQRFilter, pdal::KDistanceFilter, pdal::LocateFilter, pdal::LOFFilter, pdal::MADFilter, pdal::RadialDensityFilter, pdal::RangeFilter, pdal::SampleFilter, pdal::OSGReader, pdal::ComputeRangeFilter, pdal::GroupByFilter, pdal::SMRFilter, pdal::PlyWriter, pdal::GeoWaveReader, pdal::GreyhoundReader, pdal::ClusterFilter, pdal::SbetReader, pdal::MatlabReader, pdal::PMFFilter, pdal::CpdFilter, pdal::OciReader, pdal::AssignFilter, pdal::DividerFilter, pdal::HeadFilter, pdal::MortonOrderFilter, pdal::PoissonFilter, pdal::TailFilter, pdal::PlyReader, pdal::TextWriter, pdal::MatlabWriter, pdal::SQLiteReader, pdal::DecimationFilter, pdal::RandomizeFilter, pdal::GDALWriter, pdal::HexBin, pdal::MatlabFilter, pdal::IcpFilter, pdal::PCLBlock, pdal::PythonFilter, pdal::MergeFilter, pdal::SbetWriter, pdal::GeoWaveWriter, pdal::OciWriter, pdal::StreamCallbackFilter, pdal::PtsReader, pdal::TextReader, pdal::NitfWriter, pdal::VoxelGridFilter, pdal::PcdReader, pdal::PgWriter, pdal::NullWriter, pdal::SQLiteWriter, pdal::BufferReader, pdal::GridProjectionFilter, pdal::MovingLeastSquaresFilter, pdal::MyFilter, pdal::MyWriter, and pdal::MyReader.
Referenced by addAllArgs(), pdal::anonymous_namespace{PipelineWriter.cpp}::generateTag(), pdal::Writer::handleFilenameTemplate(), handleOptions(), l_initialize(), serialize(), setupLog(), pdal::PipelineManager::stageOptions(), and throwError().
const Options& pdal::Stage::getOptions () const private
Definition at line 497 of file Stage.hpp.
const SpatialReference & pdal::Stage::getSpatialReference () const
Get the spatial reference of the stage.
Get the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Returns
The stage's spatial reference.
Definition at line 474 of file Stage.cpp.
References m_spatialReference.
Referenced by execute(), pdal::PgReader::initialize(), pdal::BpfReader::inspect(), pdal::LasWriter::prepOutput(), pdal::MergeFilter::ready(), pdal::MergeFilter::run(), and TEST().
void pdal::Stage::handleOptions () private
Definition at line 98 of file Stage.cpp.
References addAllArgs(), pdal::Options::addConditional(), pdal::Options::fromFile(), getName(), pdal::Options::getValues(), m_args, pdal::arg_error::m_error, m_options, pdal::Options::remove(), setupLog(), and pdal::Options::toCommandLine().
Referenced by prepare(), and preview().
virtual void pdal::Stage::initialize (PointTableRef) private virtual
Initialize stage after options have been processed. Implement in subclass. If you don't require the table argument, you can implement the version of this function that takes no arguments instead of this function.
Parameters
table PointTable associated with pipeline.
Reimplemented in pdal::LasReader, pdal::NitfReader, pdal::Ilvis2Reader, pdal::MatlabReader, pdal::PtsReader, pdal::TextReader, pdal::GreyhoundReader, and pdal::TextWriter.
Definition at line 413 of file Stage.hpp.
Referenced by pdal::StageWrapper::initialize().
virtual void pdal::Stage::initialize () private virtual
Initialize stage after options have been processed. Implement in subclass.
Reimplemented in pdal::GreedyProjection, pdal::FauxReader, pdal::LasWriter, pdal::PlyReader, pdal::TerrasolidReader, pdal::PgReader, pdal::BpfReader, pdal::MrsidReader, pdal::ColorizationFilter, pdal::OverlayFilter, pdal::BpfWriter, pdal::RxpReader, pdal::QfitReader, pdal::TIndexReader, pdal::DividerFilter, pdal::SplitterFilter, pdal::IcebridgeReader, pdal::OptechReader, pdal::CropFilter, pdal::FerryFilter, pdal::SQLiteReader, pdal::TransformationFilter, pdal::OGRWriter, pdal::GDALReader, pdal::RangeFilter, pdal::ReprojectionFilter, pdal::GDALWriter, pdal::GeoWaveReader, pdal::OciReader, pdal::PgWriter, pdal::SQLiteWriter, pdal::GeoWaveWriter, pdal::OciWriter, and pdal::MyWriter.
Definition at line 420 of file Stage.hpp.
Referenced by prepare().
virtual QuickInfo pdal::Stage::inspect () private virtual
Get basic metadata (avoids reading points). Implement in subclass.
Returns
QuickInfo data.
Reimplemented in pdal::LasReader, pdal::MrsidReader, pdal::BpfReader, pdal::MbReader, and pdal::GDALReader.
Definition at line 386 of file Stage.hpp.
Referenced by preview().
bool pdal::Stage::isDebug () const
Determine whether the stage is in debug mode or not.
Returns
The stage's debug state.
Definition at line 243 of file Stage.hpp.
References pdal::Debug.
Referenced by setupLog(), startLogging(), and pdal::OciWriter::wipeBlockTable().
void pdal::Stage::l_addArgs (ProgramArgs & args) private
Definition at line 422 of file Stage.cpp.
References pdal::ProgramArgs::add(), m_logname, m_optionFile, m_userDataJSON, and readerAddArgs().
Referenced by addAllArgs().
void pdal::Stage::l_done (PointTableRef table) private
Definition at line 417 of file Stage.cpp.
References done().
Referenced by execute().
void pdal::Stage::l_initialize (PointTableRef table) private
Definition at line 460 of file Stage.cpp.
References pdal::MetadataNode::add(), getName(), m_metadata, pdal::BasePointTable::metadata(), and writerInitialize().
Referenced by pdal::StageWrapper::initialize(), and prepare().
virtual LogPtr pdal::Stage::log () const virtual
Return the stage's log pointer.
Returns
Log pointer.
Definition at line 225 of file Stage.hpp.
Referenced by pdal::OciReader::addDimensions(), pdal::GeoWaveReader::addDimensions(), pdal::SQLiteReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), pdal::LasWriter::addMetadataVlr(), pdal::LasWriter::addPipelineVlr(), pdal::OciWriter::blockTableExists(), pdal::CpdFilter::change(), pdal::PgWriter::CheckPointCloudExists(), pdal::PgWriter::CheckPostGISExists(), pdal::PgWriter::CheckTableExists(), pdal::SQLiteWriter::CreateBlockTable(), pdal::SQLiteWriter::CreateCloud(), pdal::SQLiteWriter::CreateCloudTable(), pdal::SQLiteWriter::CreateIndexes(), pdal::GeoWaveWriter::createJvm(), pdal::GeoWaveReader::createJvm(), pdal::PgReader::CursorSetup(), pdal::PgReader::CursorTeardown(), pdal::SQLiteWriter::DeleteBlockTable(), pdal::SQLiteWriter::DeleteCloudTable(), pdal::PgReader::fetchPcid(), pdal::SQLiteReader::fetchSpatialReference(), pdal::PgReader::fetchSpatialReference(), pdal::TextReader::fillFields(), pdal::ComputeRangeFilter::filter(), pdal::RadialDensityFilter::filter(), pdal::KDistanceFilter::filter(), pdal::LOFFilter::filter(), pdal::ELMFilter::filter(), pdal::ColorinterpFilter::filter(), pdal::GreedyProjection::filter(), pdal::LasWriter::finishOutput(), pdal::PgReader::getDataQuery(), pdal::GeoWaveWriter::initialize(), pdal::SQLiteWriter::initialize(), pdal::GeoWaveReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), pdal::BpfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::MbReader::loadData(), pdal::PgReader::NextBuffer(), pdal::GreyhoundReader::prepared(), pdal::PMFFilter::prepared(), pdal::NormalFilter::prepared(), pdal::LasWriter::prepared(), pdal::PMFFilter::processGround(), pdal::MongusFilter::processGround(), pdal::TextReader::processOne(), pdal::GreyhoundReader::read(), pdal::SQLiteReader::read(), pdal::PtsReader::read(), pdal::PgReader::read(), pdal::GDALReader::readBandData(), pdal::SQLiteReader::readPatch(), pdal::GeoWaveReader::ready(), pdal::PythonFilter::ready(), pdal::CropFilter::ready(), pdal::SQLiteReader::ready(), pdal::ColorinterpFilter::ready(), pdal::ColorizationFilter::ready(), pdal::BpfWriter::readyFile(), pdal::MovingLeastSquaresFilter::run(), pdal::GridProjectionFilter::run(), pdal::IcpFilter::run(), pdal::VoxelGridFilter::run(), pdal::CpdFilter::run(), pdal::MergeFilter::run(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::SampleFilter::run(), pdal::PythonFilter::run(), pdal::IQRFilter::run(), pdal::MADFilter::run(), pdal::OutlierFilter::run(), pdal::MongusFilter::run(), pdal::LasWriter::spatialReferenceChanged(), pdal::GeoWaveWriter::write(), pdal::MatlabWriter::write(), pdal::OciWriter::writeInit(), pdal::SQLiteWriter::writeInit(), pdal::OciWriter::writeTile(), and pdal::SQLiteWriter::writeTile().
Stage& pdal::Stage::operator= (const Stage &) private
bool pdal::Stage::parseName (std::string o, std::string::size_type & pos) static
Parse a stage name from a string. Return the name and update the position in the input string to the end of the stage name.
Parameters
o Input string to parse.
pos Parsing start/end position.
Returns
Whether the parsed name is a valid stage name.
Definition at line 504 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::Kernel::parseStageOption().
bool pdal::Stage::parseTagName (std::string o, std::string::size_type & pos) static
Parse a tag name from a string. Return the name and update the position in the input string to the end of the tag name.
Parameters
o Input string to parse.
pos Parsing start/end position.
tag Parsed tag name.
Returns
Whether the parsed name is a valid tag name.
Definition at line 518 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::PipelineReaderJSON::extractTag(), and pdal::Kernel::parseStageOption().
point_count_t pdal::Stage::pointCount () const protected
Return the point count of all point views at the start of execution. Only valid during execute().
Returns
Total number of points in all point views being executed.
Definition at line 328 of file Stage.hpp.
Referenced by pdal::PlyWriter::ready(), and pdal::PlyWriter::writeHeader().
void pdal::Stage::prepare (PointTableRef table)
Prepare a stage for execution. This function needs to be called on the terminal stage of a pipeline (linked set of stages) before execute can be called. Prepare recurses through all input stages.
Parameters
table PointTable being used for stage pipeline.
Definition at line 138 of file Stage.cpp.
References addDimensions(), handleOptions(), initialize(), l_initialize(), pdal::BasePointTable::layout(), m_args, m_inputs, prepare(), prepared(), startLogging(), and stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), prepare(), pdal::PipelineManager::prepare(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
virtual void pdal::Stage::prepared (PointTableRef) private virtual
Functions called after dimensions have been added. Implement in subclass.
Parameters
table PointTable associated with pipeline.
Reimplemented in pdal::StatsFilter, pdal::LasWriter, pdal::OverlayFilter, pdal::BpfWriter, pdal::ColorinterpFilter, pdal::NormalFilter, pdal::SMRFilter, pdal::SortFilter, pdal::FerryFilter, pdal::DbWriter, pdal::OGRWriter, pdal::PMFFilter, pdal::MADFilter, pdal::IQRFilter, pdal::LocateFilter, pdal::RangeFilter, pdal::GroupByFilter, pdal::HAGFilter, pdal::ComputeRangeFilter, pdal::PlyWriter, pdal::GreyhoundReader, pdal::GDALWriter, pdal::AssignFilter, and pdal::MatlabWriter.
Definition at line 437 of file Stage.hpp.
Referenced by prepare().
QuickInfo pdal::Stage::preview ()
Retrieve some basic point information without reading all data when possible. Usually implemented only by Readers.
Definition at line 127 of file Stage.cpp.
References handleOptions(), inspect(), m_args, startLogging(), and stopLogging().
Referenced by pdal::TIndexKernel::getFileInfo(), pdal::PipelineManager::preview(), pdal::InfoKernel::run(), and TEST().
virtual bool pdal::Stage::processOne (PointRef &) private virtual
Process a single point (streaming mode). Implement in sublcass.
Parameters
point Point to process.
Returns
Readers return false when no more points are to be read. Filters return false if a point is to be filtered-out (not passed to subsequent stages).
Reimplemented in pdal::StatsFilter, pdal::FauxReader, pdal::LasWriter, pdal::LasReader, pdal::PlyReader, pdal::TextReader, pdal::MatlabReader, pdal::Ilvis2Reader, pdal::BpfReader, pdal::ColorizationFilter, pdal::ColorinterpFilter, pdal::OverlayFilter, pdal::MbReader, pdal::CropFilter, pdal::FerryFilter, pdal::OGRWriter, pdal::StreamCallbackFilter, pdal::TransformationFilter, pdal::RangeFilter, pdal::ReprojectionFilter, pdal::GDALWriter, pdal::SbetReader, pdal::DecimationFilter, pdal::AssignFilter, and pdal::MergeFilter.
Definition at line 457 of file Stage.hpp.
Referenced by execute().
virtual void pdal::Stage::processOptions (const Options &) private virtual
Process options. Implement in subclass.
Parameters
options Options to process.
Definition at line 402 of file Stage.hpp.
virtual void pdal::Stage::readerAddArgs (ProgramArgs &) private virtual
Reimplemented in pdal::Reader.
Definition at line 371 of file Stage.hpp.
Referenced by l_addArgs().
virtual void pdal::Stage::ready (PointTableRef) private virtual
First part of the execute step. Called after all stages have been prepared. Implement in subclass.
Parameters
table PointTable associated with the pipeline.
Reimplemented in pdal::FauxReader, pdal::LasReader, pdal::PlyReader, pdal::TerrasolidReader, pdal::PgReader, pdal::Ilvis2Reader, pdal::BpfReader, pdal::MrsidReader, pdal::ColorizationFilter, pdal::OverlayFilter, pdal::FlexWriter, pdal::RxpReader, pdal::MbReader, pdal::TextReader, pdal::QfitReader, pdal::ColorinterpFilter, pdal::PtsReader, pdal::TIndexReader, pdal::SMRFilter, pdal::IcebridgeReader, pdal::OptechReader, pdal::SQLiteReader, pdal::CropFilter, pdal::DbWriter, pdal::HexBin, pdal::GDALReader, pdal::SbetReader, pdal::OSGReader, pdal::PythonFilter, pdal::ReprojectionFilter, pdal::PlyWriter, pdal::GeoWaveReader, pdal::MatlabFilter, pdal::DecimationFilter, pdal::OciReader, pdal::SbetWriter, pdal::TextWriter, pdal::MatlabWriter, pdal::MergeFilter, pdal::GeoWaveWriter, pdal::OciWriter, pdal::PcdReader, pdal::MyReader, and pdal::MyWriter.
Definition at line 446 of file Stage.hpp.
Referenced by execute(), and pdal::StageWrapper::ready().
void pdal::Stage::removeOptions (const Options & opts)
Remove options from a stage's option set.
Parameters
opts Options to remove.
Definition at line 206 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions().
virtual PointViewSet pdal::Stage::run (PointViewPtr) private virtual
Process all points in a view. Implement in subclass.
Parameters
view PointView to process.
Reimplemented in pdal::ChipperFilter, SplitFilter, pdal::MongusFilter, pdal::OutlierFilter, pdal::TIndexReader, pdal::SMRFilter, pdal::DividerFilter, pdal::SplitterFilter, pdal::CropFilter, pdal::Writer, pdal::PMFFilter, pdal::MADFilter, pdal::RangeFilter, pdal::IQRFilter, pdal::LocateFilter, pdal::PythonFilter, pdal::GroupByFilter, pdal::DecimationFilter, pdal::HeadFilter, pdal::ReprojectionFilter, pdal::SampleFilter, pdal::TailFilter, pdal::VoxelCenterNearestNeighborFilter, pdal::VoxelCentroidNearestNeighborFilter, pdal::Reader, pdal::MatlabFilter, pdal::PoissonFilter, pdal::MergeFilter, pdal::PCLBlock, pdal::MortonOrderFilter, pdal::CpdFilter, pdal::VoxelGridFilter, pdal::BufferReader, pdal::IcpFilter, pdal::Filter, pdal::GridProjectionFilter, pdal::MovingLeastSquaresFilter, and pdal::MyFilter.
Definition at line 478 of file Stage.hpp.
Referenced by pdal::StageWrapper::run(), and pdal::StageRunner::run().
void pdal::Stage::serialize (MetadataNode root, PipelineWriter::TagMap & tags) const
Serialize a stage by inserting apporpritate data into the provided MetadataNode. Used to dump a pipeline specification in a portable format.
Parameters
root Node to which a stages meatdata should be added.
tags Pipeline writer's current list of stage tags.
Definition at line 64 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), getName(), m_inputs, m_options, and pdal::Options::toMetadata().
Referenced by pdal::PipelineWriter::writePipeline().
void pdal::Stage::setInput (Stage & input)
Add a stage to the input list of this stage.
Parameters
input Stage to use as input.
Definition at line 85 of file Stage.hpp.
Referenced by compareTextLasStreaming(), pdal::MergeKernel::execute(), pdal::TIndexReader::initialize(), main(), pdal::PipelineManager::makeFilter(), pdal::TIndexKernel::mergeFile(), pdal::PipelineReaderJSON::parsePipeline(), pdal::PipelineManager::replace(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::TransformationFilterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), pdal::TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testOverlay(), and writeData().
void pdal::Stage::setLog (LogPtr & log)
Set the stage's log.
Parameters
log Log pointer.
Definition at line 217 of file Stage.hpp.
References setup::log.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), and testOverlay().
void pdal::Stage::setOptions (Options options)
Set a stage's options.
Set the options on a stage, clearing all previously set options.
Parameters
options Options to set.
Definition at line 172 of file Stage.hpp.
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), getBytes(), pdal::TIndexReader::initialize(), main(), anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::PipelineManager::setOptions(), pdal::TransformationFilterTest::SetUp(), pdal::MatlabWriterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_file_type_stream(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), testReadWrite(), and writeData().
void pdal::Stage::setProgressFd (int fd)
Set a file descriptor to which progress information should be written.
Parameters
fd Progress file descriptor.
Definition at line 93 of file Stage.hpp.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), and pdal::PipelineManager::addWriter().
void pdal::Stage::setSpatialReference (SpatialReference const & srs)
Set the spatial reference of a stage.
Set the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Parameters
srs Spatial reference to set.
Definition at line 480 of file Stage.cpp.
References m_metadata.
Referenced by pdal::OciReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), pdal::BpfReader::initialize(), pdal::Ilvis2Reader::initialize(), pdal::PgReader::initialize(), pdal::LasWriter::initialize(), pdal::OptechReader::OptechReader(), pdal::MyReader::ready(), and TEST().
void pdal::Stage::setSpatialReference (MetadataNode & m, SpatialReference const & spatialRef) protected
Definition at line 486 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::empty(), pdal::MetadataNode::findChild(), pdal::SpatialReference::getWKT(), m_spatialReference, pdal::MetadataNode::name(), and pdal::SpatialReference::toMetadata().
void pdal::Stage::setTag (const std::string & tag)
Set a specific tag name.
Definition at line 256 of file Stage.hpp.
Referenced by pdal::PipelineManager::makeFilter(), and pdal::PipelineManager::makeReader().
void pdal::Stage::setupLog () private
Definition at line 435 of file Stage.cpp.
References pdal::Error, pdal::gdal::ErrorHandler::getGlobalErrorHandler(), getName(), isDebug(), m_log, m_logLeader, m_logname, and pdal::gdal::ErrorHandler::set().
Referenced by handleOptions().
virtual void pdal::Stage::spatialReferenceChanged (const SpatialReference & srs) private virtual
(Streaming mode) Notification that the points that will follow in processing are from a spatial reference different than the previous spatial reference.
Parameters
srs New spatial reference.
Reimplemented in pdal::LasWriter, pdal::OverlayFilter, and pdal::CropFilter.
Definition at line 470 of file Stage.hpp.
void pdal::Stage::startLogging () const
Push the stage's leader into the log.
Definition at line 538 of file Stage.cpp.
References pdal::gdal::ErrorHandler::getGlobalErrorHandler(), isDebug(), m_log, m_logLeader, and pdal::gdal::ErrorHandler::set().
Referenced by execute(), prepare(), and preview().
void pdal::Stage::stopLogging () const
Pop the stage's leader from the log.
Definition at line 545 of file Stage.cpp.
References m_log.
Referenced by execute(), prepare(), and preview().
virtual std::string pdal::Stage::tag () const virtual
Return the tag name of a stage.
Returns
The tag name.
Definition at line 264 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTag(), pdal::TranslateKernel::makeJSONPipeline(), and pdal::PipelineManager::stageOptions().
void pdal::Stage::throwError (const std::string & s) const protected
Definition at line 532 of file Stage.cpp.
References getName().
Referenced by pdal::SQLiteReader::addDimensions(), pdal::MrsidReader::addDimensions(), pdal::TextReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), pdal::PlyReader::addDimensions(), pdal::LasWriter::addGeotiffVlrs(), pdal::LasWriter::addVlr(), pdal::PgWriter::CheckTableExists(), pdal::OciWriter::createPCEntry(), pdal::ReprojectionFilter::createTransform(), pdal::MatlabWriter::done(), pdal::NitfWriter::doneFile(), pdal::GDALWriter::doneFile(), pdal::OGRWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::GDALWriter::expandGrid(), pdal::PlyReader::extractElement(), pdal::PlyReader::extractEnd(), pdal::PlyReader::extractFormat(), pdal::PlyReader::extractHeader(), pdal::PlyReader::extractMagic(), pdal::PlyReader::extractProperty(), pdal::PgReader::fetchPcid(), pdal::PgReader::fetchSpatialReference(), pdal::LasWriter::fillForwardList(), pdal::LasWriter::fillHeader(), pdal::LasWriter::fillPointBuf(), pdal::HAGFilter::filter(), pdal::EigenvaluesFilter::filter(), pdal::ApproximateCoplanarFilter::filter(), pdal::NormalFilter::filter(), pdal::LasWriter::finishOutput(), pdal::TIndexReader::getFields(), pdal::PgReader::getNumPoints(), pdal::PlyWriter::getType(), pdal::LasWriter::handleLaszip(), pdal::OciWriter::initialize(), pdal::SQLiteWriter::initialize(), pdal::OciReader::initialize(), pdal::GDALWriter::initialize(), pdal::TextReader::initialize(), pdal::ReprojectionFilter::initialize(), pdal::PtsReader::initialize(), pdal::RangeFilter::initialize(), pdal::MatlabReader::initialize(), pdal::OGRWriter::initialize(), pdal::FerryFilter::initialize(), pdal::SQLiteReader::initialize(), pdal::OptechReader::initialize(), pdal::DividerFilter::initialize(), pdal::TIndexReader::initialize(), pdal::QfitReader::initialize(), pdal::BpfWriter::initialize(), pdal::ColorizationFilter::initialize(), pdal::BpfReader::initialize(), pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::LasWriter::initialize(), pdal::FauxReader::initialize(), pdal::GreedyProjection::initialize(), pdal::GDALReader::inspect(), pdal::OciWriter::isGeographic(), pdal::BpfWriter::loadBpfDimensions(), pdal::MbReader::loadData(), pdal::SQLiteWriter::loadGeometryWKT(), pdal::OciWriter::loadSQLData(), pdal::NitfWriter::NitfWriter(), pdal::MatlabWriter::prepared(), pdal::GDALWriter::prepared(), pdal::PlyWriter::prepared(), pdal::ComputeRangeFilter::prepared(), pdal::HAGFilter::prepared(), pdal::GroupByFilter::prepared(), pdal::IQRFilter::prepared(), pdal::LocateFilter::prepared(), pdal::RangeFilter::prepared(), pdal::MADFilter::prepared(), pdal::OGRWriter::prepared(), pdal::FerryFilter::prepared(), pdal::SortFilter::prepared(), pdal::ColorinterpFilter::prepared(), pdal::LasWriter::prepared(), pdal::OGRWriter::processOne(), pdal::Ilvis2Reader::processOne(), pdal::MatlabReader::processOne(), pdal::QfitReader::read(), pdal::OciReader::readBlob(), pdal::PlyReader::readElement(), pdal::SQLiteReader::readPatch(), pdal::OciReader::readPointMajor(), pdal::MatlabWriter::ready(), pdal::PlyWriter::ready(), pdal::SbetReader::ready(), pdal::GDALReader::ready(), pdal::OptechReader::ready(), pdal::PtsReader::ready(), pdal::ColorinterpFilter::ready(), pdal::QfitReader::ready(), pdal::TextReader::ready(), pdal::MbReader::ready(), pdal::ColorizationFilter::ready(), pdal::Ilvis2Reader::ready(), pdal::OGRWriter::readyFile(), pdal::BpfWriter::readyFile(), pdal::LasWriter::readyFile(), pdal::LasWriter::readyLazPerfCompression(), pdal::GDALWriter::readyTable(), pdal::NitfWriter::reprojectBoxToDD(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::PgWriter::SetupSchema(), pdal::CropFilter::transform(), pdal::OciWriter::updatePCExtent(), pdal::OciReader::validateQuery(), pdal::SQLiteReader::validateQuery(), pdal::MatlabWriter::write(), pdal::LasWriter::writeLasZipBuf(), pdal::OciWriter::writePointMajor(), pdal::OciWriter::writeTile(), pdal::SQLiteWriter::writeTile(), and pdal::BpfWriter::writeView().
void pdal::Stage::throwStreamingError () const protected
Definition at line 339 of file Stage.hpp.
Referenced by pdal::ColorinterpFilter::processOne().
virtual void pdal::Stage::writerInitialize (PointTableRef) private virtual
Reimplemented in pdal::Writer, and pdal::FlexWriter.
Definition at line 376 of file Stage.hpp.
Referenced by l_initialize().
Friends And Related Function Documentation
friend class StageRunner friend
Definition at line 74 of file Stage.hpp.
Referenced by execute().
friend class StageWrapper friend
Definition at line 73 of file Stage.hpp.
Member Data Documentation
std::unique_ptr<ProgramArgs> pdal::Stage::m_args private
Definition at line 353 of file Stage.hpp.
Referenced by handleOptions(), prepare(), and preview().
point_count_t pdal::Stage::m_faceCount private
Definition at line 360 of file Stage.hpp.
Referenced by execute().
std::vector<Stage *> pdal::Stage::m_inputs private
Definition at line 349 of file Stage.hpp.
Referenced by execute(), prepare(), and serialize().
LogPtr pdal::Stage::m_log private
Definition at line 350 of file Stage.hpp.
Referenced by setupLog(), startLogging(), and stopLogging().
std::string pdal::Stage::m_logLeader private
Definition at line 351 of file Stage.hpp.
Referenced by setupLog(), and startLogging().
std::string pdal::Stage::m_logname private
Definition at line 348 of file Stage.hpp.
Referenced by l_addArgs(), and setupLog().
MetadataNode pdal::Stage::m_metadata protected
Stage's metadata.
Definition at line 316 of file Stage.hpp.
Referenced by pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), l_initialize(), pdal::BpfReader::readHeaderExtraData(), pdal::BpfReader::readUlemFiles(), pdal::Ilvis2Reader::ready(), and setSpatialReference().
std::string pdal::Stage::m_optionFile private
Definition at line 363 of file Stage.hpp.
Referenced by l_addArgs().
Options pdal::Stage::m_options protected
Stage's options.
Definition at line 315 of file Stage.hpp.
Referenced by addConditionalOptions(), handleOptions(), and serialize().
point_count_t pdal::Stage::m_pointCount private
Definition at line 359 of file Stage.hpp.
Referenced by execute().
int pdal::Stage::m_progressFd protected
Descriptor for progress info.
Definition at line 317 of file Stage.hpp.
Referenced by pdal::LasWriter::doneFile(), pdal::NitfWriter::readyFile(), pdal::LasWriter::readyFile(), and pdal::LasWriter::writeView().
SpatialReference pdal::Stage::m_spatialReference private
Definition at line 352 of file Stage.hpp.
Referenced by addSpatialReferenceArg(), getSpatialReference(), and setSpatialReference().
std::string pdal::Stage::m_tag private
Definition at line 354 of file Stage.hpp.
std::string pdal::Stage::m_userDataJSON private
Definition at line 358 of file Stage.hpp.
Referenced by l_addArgs().
uint32_t pdal::Stage::m_verbose private
Definition at line 347 of file Stage.hpp.
The documentation for this class was generated from the following files:
pdal/pdal/Stage.hpp
pdal/pdal/Stage.cpp