PDAL: pdal::gdal::Band< T > Class Template Reference
pdal::gdal::Band< T > Class Template Reference
#include <GDALUtils.hpp>
Private Member Functions
Band (GDALDataset *ds, int bandNum, double dstNoData=-9999.0, const std::string &name="")
Band name.
void read (std::vector< T > &data)
void readBlock (int x, int y, std::vector< T > &data)
template<typename SOURCE_ITER >
void write (SOURCE_ITER si, ITER_VAL< SOURCE_ITER > srcNoData)
T getNoData () const
template<typename SOURCE_ITER >
void writeBlock (int x, int y, SOURCE_ITER sourceBegin, ITER_VAL< SOURCE_ITER > srcNoData)
Private Attributes
GDALDataset * m_ds
int m_bandNum
Dataset handle.
double m_dstNoData
Band number. Band numbers start at 1.
GDALRasterBand * m_band
Output no data value.
int m_xTotalSize
Band handle.
int m_yTotalSize
int m_xBlockSize
Total size (x and y) of the raster.
int m_yBlockSize
int m_xBlockCnt
Size (x and y) of blocks.
int m_yBlockCnt
std::vector< T > m_buf
Number of blocks in each direction.
std::string m_name
Block read buffer.
Friends
class Raster
Detailed Description
template<typename T>
class pdal::gdal::Band< T >
Definition at line 318 of file GDALUtils.hpp.
Constructor & Destructor Documentation
template<typename T> pdal::gdal::Band< T >::Band (GDALDataset * ds, int bandNum, double dstNoData = -9999.0, const std::string & name = "") private
Band name.
Create an object for reading a band of a GDAL dataset.
Parameters
ds GDAL dataset handle.
dstNoData The no data value to be used when writing the band.
bandNum Band number (1-indexed).
name Name of the raster band.
Definition at line 341 of file GDALUtils.hpp.
References pdal::gdal::InvalidBand, and pdal::Dimension::name().
Member Function Documentation
template<typename T> T pdal::gdal::Band< T >::getNoData () const private
Definition at line 447 of file GDALUtils.hpp.
References pdal::gdal::CantWriteBlock, pdal::Utils::numericCast(), and pdal::Utils::toString().
template<typename T> void pdal::gdal::Band< T >::read (std::vector< T > & data) private
Definition at line 379 of file GDALUtils.hpp.
template<typename T> void pdal::gdal::Band< T >::readBlock (int x, int y, std::vector< T > & data) private
Definition at line 400 of file GDALUtils.hpp.
References pdal::gdal::CantReadBlock.
template<typename T> template<typename SOURCE_ITER > void pdal::gdal::Band< T >::write (SOURCE_ITER si, ITER_VAL< SOURCE_ITER > srcNoData) private
Definition at line 440 of file GDALUtils.hpp.
template<typename T> template<typename SOURCE_ITER > void pdal::gdal::Band< T >::writeBlock (int x, int y, SOURCE_ITER sourceBegin, ITER_VAL< SOURCE_ITER > srcNoData) private
Definition at line 462 of file GDALUtils.hpp.
References pdal::gdal::CantWriteBlock, pdal::Utils::numericCast(), and pdal::Utils::toString().
Friends And Related Function Documentation
template<typename T> friend class Raster friend
Definition at line 320 of file GDALUtils.hpp.
Member Data Documentation
template<typename T> GDALRasterBand* pdal::gdal::Band< T >::m_band private
Output no data value.
Definition at line 326 of file GDALUtils.hpp.
template<typename T> int pdal::gdal::Band< T >::m_bandNum private
Dataset handle.
Definition at line 324 of file GDALUtils.hpp.
template<typename T> std::vector<T> pdal::gdal::Band< T >::m_buf private
Number of blocks in each direction.
Definition at line 330 of file GDALUtils.hpp.
template<typename T> GDALDataset* pdal::gdal::Band< T >::m_ds private
Definition at line 323 of file GDALUtils.hpp.
template<typename T> double pdal::gdal::Band< T >::m_dstNoData private
Band number. Band numbers start at 1.
Definition at line 325 of file GDALUtils.hpp.
template<typename T> std::string pdal::gdal::Band< T >::m_name private
Block read buffer.
Definition at line 331 of file GDALUtils.hpp.
template<typename T> int pdal::gdal::Band< T >::m_xBlockCnt private
Size (x and y) of blocks.
Definition at line 329 of file GDALUtils.hpp.
template<typename T> int pdal::gdal::Band< T >::m_xBlockSize private
Total size (x and y) of the raster.
Definition at line 328 of file GDALUtils.hpp.
template<typename T> int pdal::gdal::Band< T >::m_xTotalSize private
Band handle.
Definition at line 327 of file GDALUtils.hpp.
template<typename T> int pdal::gdal::Band< T >::m_yBlockCnt private
Definition at line 329 of file GDALUtils.hpp.
template<typename T> int pdal::gdal::Band< T >::m_yBlockSize private
Definition at line 328 of file GDALUtils.hpp.
template<typename T> int pdal::gdal::Band< T >::m_yTotalSize private
Definition at line 327 of file GDALUtils.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/GDALUtils.hpp