PDAL: pdal::PointViewMesh Class Reference
pdal::PointViewMesh Class Reference
Public Member Functions
PointViewMesh (PointView &view, bool color)
virtual int pointCount () const
virtual int polygonCount () const
virtual int newPoint (const std::array< double, 3 > &position)
virtual int newPoint (const std::array< double, 3 > &position, double density)
virtual int newPoint (const std::array< double, 3 > &position, const std::array< uint8_t, 3 > &color, double density)
virtual void newPolygon (std::vector< int > &poly)
virtual bool hasDensity () const
virtual void resetIterator ()
virtual bool nextPolygon (Kazhdan::Polygon &poly)
virtual bool nextPoint (Kazhdan::Point &point)
Private Attributes
PointView & m_view
TriangularMesh & m_mesh
size_t m_polyIdx
size_t m_pointIdx
bool m_doColor
Detailed Description
Definition at line 107 of file PoissonFilter.cpp.
Constructor & Destructor Documentation
pdal::PointViewMesh::PointViewMesh (PointView & view, bool color)
Definition at line 110 of file PoissonFilter.cpp.
Member Function Documentation
virtual bool pdal::PointViewMesh::hasDensity () const virtual
Definition at line 157 of file PoissonFilter.cpp.
References pdal::Dimension::Density, pdal::PointView::hasDim(), and pdal::PointViewSource::m_view.
virtual int pdal::PointViewMesh::newPoint (const std::array< double, 3 > & position) virtual
Definition at line 118 of file PoissonFilter.cpp.
References pdal::PointViewSource::m_view, pdal::PointView::setField(), pdal::PointView::size(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
virtual int pdal::PointViewMesh::newPoint (const std::array< double, 3 > & position, double density) virtual
Definition at line 127 of file PoissonFilter.cpp.
References pdal::Dimension::Density, pdal::PointViewSource::m_view, pdal::PointView::setField(), pdal::PointView::size(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
virtual int pdal::PointViewMesh::newPoint (const std::array< double, 3 > & position, const std::array< uint8_t, 3 > & color, double density) virtual
Definition at line 137 of file PoissonFilter.cpp.
References pdal::Dimension::Blue, pdal::Dimension::Density, pdal::Dimension::Green, pdal::PointViewSource::m_view, pdal::Dimension::Red, pdal::PointView::setField(), pdal::PointView::size(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
virtual void pdal::PointViewMesh::newPolygon (std::vector< int > & poly) virtual
Definition at line 151 of file PoissonFilter.cpp.
virtual bool pdal::PointViewMesh::nextPoint (Kazhdan::Point & point) virtual
Definition at line 177 of file PoissonFilter.cpp.
References pdal::Dimension::Blue, pdal::Dimension::Density, pdal::PointView::getFieldAs(), pdal::Dimension::Green, pdal::PointViewSource::m_view, pdal::Dimension::Red, pdal::PointView::size(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
virtual bool pdal::PointViewMesh::nextPolygon (Kazhdan::Polygon & poly) virtual
Definition at line 166 of file PoissonFilter.cpp.
References pdal::Triangle::m_a, pdal::Triangle::m_b, and pdal::Triangle::m_c.
virtual int pdal::PointViewMesh::pointCount () const virtual
Definition at line 114 of file PoissonFilter.cpp.
References pdal::PointViewSource::m_view, and pdal::PointView::size().
virtual int pdal::PointViewMesh::polygonCount () const virtual
Definition at line 116 of file PoissonFilter.cpp.
virtual void pdal::PointViewMesh::resetIterator () virtual
Definition at line 160 of file PoissonFilter.cpp.
Member Data Documentation
bool pdal::PointViewMesh::m_doColor private
Definition at line 207 of file PoissonFilter.cpp.
TriangularMesh& pdal::PointViewMesh::m_mesh private
Definition at line 204 of file PoissonFilter.cpp.
size_t pdal::PointViewMesh::m_pointIdx private
Definition at line 206 of file PoissonFilter.cpp.
size_t pdal::PointViewMesh::m_polyIdx private
Definition at line 205 of file PoissonFilter.cpp.
PointView& pdal::PointViewMesh::m_view private
Definition at line 203 of file PoissonFilter.cpp.
The documentation for this class was generated from the following file:
pdal/filters/PoissonFilter.cpp