PDAL: pdal::gdal::Geometry Class Reference
pdal::gdal::Geometry Class Reference
#include <GDALUtils.hpp>
Public Member Functions
Geometry ()
Geometry (const std::string &wkt, const SpatialRef &srs)
operator bool () const
OGRGeometryH get () const
void transform (const SpatialRef &out_srs)
std::string wkt () const
void setFromGeometry (OGRGeometryH geom)
Private Member Functions
void newRef (void *v)
Private Attributes
RefPtr m_ref
Detailed Description
Definition at line 129 of file GDALUtils.hpp.
Constructor & Destructor Documentation
pdal::gdal::Geometry::Geometry ()
Definition at line 132 of file GDALUtils.hpp.
pdal::gdal::Geometry::Geometry (const std::string & wkt, const SpatialRef & srs)
Definition at line 134 of file GDALUtils.hpp.
References pdal::gdal::SpatialRef::empty(), pdal::gdal::SpatialRef::get(), and pdal::gdal::SpatialRef::newRef().
Member Function Documentation
OGRGeometryH pdal::gdal::Geometry::get () const
Definition at line 176 of file GDALUtils.hpp.
References pdal::gdal::SpatialRef::m_ref.
Referenced by pdal::TIndexKernel::prepareGeometry().
void pdal::gdal::Geometry::newRef (void * v) private
Definition at line 198 of file GDALUtils.hpp.
References pdal::gdal::SpatialRef::m_ref.
pdal::gdal::Geometry::operator bool () const
Definition at line 174 of file GDALUtils.hpp.
void pdal::gdal::Geometry::setFromGeometry (OGRGeometryH geom)
Definition at line 191 of file GDALUtils.hpp.
References pdal::gdal::SpatialRef::newRef().
void pdal::gdal::Geometry::transform (const SpatialRef & out_srs)
Definition at line 179 of file GDALUtils.hpp.
References pdal::gdal::SpatialRef::get(), and pdal::gdal::SpatialRef::m_ref.
Referenced by pdal::TIndexReader::initialize().
std::string pdal::gdal::Geometry::wkt () const
Definition at line 184 of file GDALUtils.hpp.
References pdal::gdal::SpatialRef::m_ref.
Referenced by pdal::TIndexReader::initialize().
Member Data Documentation
RefPtr pdal::gdal::Geometry::m_ref private
Definition at line 202 of file GDALUtils.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/GDALUtils.hpp