PDAL: pdal::BpfReader Class Reference
pdal::BpfReader Class Reference
#include <BpfReader.hpp>
Public Types
typedef std::function< void(PointView &, PointId)> PointReadFunc
Public Member Functions
std::string getName () const
virtual point_count_t numPoints () const
void setReadCb (PointReadFunc cb)
void setInput (Stage &input)
void setProgressFd (int fd)
QuickInfo preview ()
void prepare (PointTableRef table)
PointViewSet execute (PointTableRef table)
void execute (StreamPointTable &table)
void setSpatialReference (SpatialReference const &srs)
const SpatialReference & getSpatialReference () const
void setOptions (Options options)
void addConditionalOptions (const Options &opts)
void addAllArgs (ProgramArgs &args)
void addOptions (const Options &opts)
void removeOptions (const Options &opts)
void setLog (LogPtr &log)
virtual LogPtr log () const
void startLogging () const
void stopLogging () const
bool isDebug () const
void setTag (const std::string &tag)
virtual std::string tag () const
std::vector< Stage * > & getInputs ()
MetadataNode getMetadata () const
void serialize (MetadataNode root, PipelineWriter::TagMap &tags) const
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
static bool parseName (std::string o, std::string::size_type &pos)
static bool parseTagName (std::string o, std::string::size_type &pos)
Protected Member Functions
void setSpatialReference (MetadataNode &m, SpatialReference const &)
void addSpatialReferenceArg (ProgramArgs &args)
void throwError (const std::string &s) const
point_count_t pointCount () const
point_count_t faceCount () const
void throwStreamingError () const
Protected Attributes
std::string m_filename
point_count_t m_count
PointReadFunc m_cb
Arg * m_filenameArg
Arg * m_countArg
Options m_options
Stage's options.
MetadataNode m_metadata
Stage's metadata.
int m_progressFd
Descriptor for progress info.
Private Member Functions
virtual QuickInfo inspect ()
virtual void initialize ()
virtual void addDimensions (PointLayoutPtr Layout)
virtual void ready (PointTableRef table)
virtual bool processOne (PointRef &point)
virtual point_count_t read (PointViewPtr data, point_count_t num)
virtual void done (PointTableRef table)
bool readUlemData ()
bool readUlemFiles ()
bool readHeaderExtraData ()
bool readPolarData ()
void readPointMajor (PointRef &point)
point_count_t readPointMajor (PointViewPtr data, point_count_t count)
void readDimMajor (PointRef &point)
point_count_t readDimMajor (PointViewPtr data, point_count_t count)
void readByteMajor (PointRef &point)
point_count_t readByteMajor (PointViewPtr data, point_count_t count)
size_t readBlock (std::vector< char > &outBuf, size_t index)
bool eof ()
int inflate (char *inbuf, uint32_t insize, char *outbuf, uint32_t outsize)
void seekPointMajor (PointId ptIdx)
void seekDimMajor (size_t dimIdx, PointId ptIdx)
void seekByteMajor (size_t dimIdx, size_t byteIdx, PointId ptIdx)
Private Attributes
ILeStream m_stream
BpfHeader m_header
BpfDimensionList m_dims
Dimension::IdList m_schemaDims
BpfUlemHeader m_ulemHeader
std::vector< BpfUlemFrame > m_ulemFrames
BpfPolarHeader m_polarHeader
std::vector< BpfPolarFrame > m_polarFrames
std::streampos m_start
Stream position at the beginning of point records.
point_count_t m_index
Index of the next point to read.
std::vector< char > m_deflateBuf
Buffer for deflated data.
Charbuf m_charbuf
Streambuf for deflated data.
std::vector< std::unique_ptr< ILeStream > > m_streams
std::vector< std::unique_ptr< Charbuf > > m_charbufs
Detailed Description
Definition at line 58 of file BpfReader.hpp.
Member Typedef Documentation
typedef std::function<void(PointView&, PointId)> pdal::Reader::PointReadFunc inherited
Definition at line 50 of file Reader.hpp.
Member Function Documentation
void pdal::Stage::addAllArgs (ProgramArgs & args) inherited
Add a stage's options to a ProgramArgs set.
Parameters
args ProgramArgs to add to.
Definition at line 84 of file Stage.cpp.
References pdal::Stage::addArgs(), pdal::Stage::getName(), pdal::Stage::l_addArgs(), and pdal::arg_error::m_error.
Referenced by pdal::Stage::handleOptions(), and App::outputOptions().
void pdal::Stage::addConditionalOptions (const Options & opts) inherited
Add options if an option with the same name doesn't already exist on the stage.
Parameters
opts Options to add.
Definition at line 57 of file Stage.cpp.
References pdal::Options::addConditional(), pdal::Options::getOptions(), and pdal::Stage::m_options.
Referenced by pdal::TEST().
void pdal::BpfReader::addDimensions (PointLayoutPtr) private virtual
Add dimensions to a layout.
Parameters
layout Point layout.
Reimplemented from pdal::Stage.
Definition at line 183 of file BpfReader.cpp.
References pdal::Dimension::Double, pdal::Dimension::Float, m_dims, pdal::BpfDimension::m_id, pdal::BpfDimension::m_label, pdal::PointLayout::registerOrAssignDim(), and pdal::Dimension::type().
void pdal::Stage::addOptions (const Options & opts) inherited
Add options to the existing option set.
Parameters
opts Options to add.
Definition at line 195 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions(), and TEST().
void pdal::Stage::addSpatialReferenceArg (ProgramArgs & args) protected inherited
Definition at line 468 of file Stage.cpp.
References pdal::ProgramArgs::add(), and pdal::Stage::m_spatialReference.
Referenced by pdal::OciReader::addArgs(), and pdal::PgReader::addArgs().
static void* pdal::BpfReader::create () static
static int32_t pdal::BpfReader::destroy (void *) static
void pdal::BpfReader::done (PointTableRef) private virtual
Called after all point views have been processed. Implement in subclass.
Parameters
table PointTable associated with pipeline.
Reimplemented from pdal::Stage.
Definition at line 282 of file BpfReader.cpp.
References pdal::IStream::close(), m_stream, and pdal::IStream::popStream().
bool pdal::BpfReader::eof () private
Definition at line 323 of file BpfReader.cpp.
References m_index, and numPoints().
Referenced by processOne().
PointViewSet pdal::Stage::execute (PointTableRef table) inherited
Execute a prepared pipeline (linked set of stages).
This performs the action associated with the stage by executing the run function of each stage in depth first order. Each stage is run to completion (all points are processed) before the next stages is run.o
Parameters
table Point table being used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 156 of file Stage.cpp.
References pdal::BasePointTable::addSpatialReference(), pdal::BasePointTable::clearSpatialReferences(), pdal::SpatialReference::empty(), pdal::Stage::execute(), pdal::BasePointTable::finalize(), pdal::Stage::getSpatialReference(), pdal::Stage::l_done(), pdal::Stage::m_faceCount, pdal::Stage::m_inputs, pdal::Stage::m_pointCount, pdal::Stage::ready(), pdal::Stage::StageRunner, pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::execute(), pdal::Stage::execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
void pdal::Stage::execute (StreamPointTable & table) inherited
Execute a prepared pipeline (linked set of stages) in streaming mode.
This performs the action associated with the stage by executing the processOne function of each stage in depth first order. Points are processed up to the capacity of the provided StreamPointTable. Not all stages support streaming mode and an exception will be thrown when attempting to execute an unsupported stage.
Streaming points can reduce memory consumption, but may limit access to algorithms that need to operate on full point sets.
Parameters
table Streming point table used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 239 of file Stage.cpp.
References pdal::Stage::done(), pdal::SpatialReference::empty(), pdal::Stage::execute(), pdal::StreamPointTable::finalize(), pdal::Stage::m_inputs, pdal::entwine::operator-(), pdal::Stage::ready(), and pdal::BasePointTable::setSpatialReference().
point_count_t pdal::Stage::faceCount () const protected inherited
Return the count of faces in all primary meshes for all point views. Only valid during execute().
Returns
Total number of faces in all point views being executed.
Definition at line 336 of file Stage.hpp.
Referenced by pdal::PlyWriter::writeHeader().
std::vector<Stage*>& pdal::Stage::getInputs () inherited
Return a list of the stage's inputs.
Returns
A vector pointers to input stages.
Definition at line 272 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTags(), pdal::PipelineManager::leaves(), pdal::PipelineManager::replace(), and TEST().
MetadataNode pdal::Stage::getMetadata () const inherited
Get the stage's metadata node.
Returns
Stage's metadata.
Definition at line 280 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{CpdFilter.cpp}::addMetadata(), pdal::CpdFilter::change(), pdal::CpdFilter::cpd_affine(), pdal::CpdFilter::cpd_rigid(), pdal::SbetWriter::done(), pdal::MatlabWriter::done(), pdal::PcdWriter::done(), pdal::PlyWriter::done(), pdal::MbReader::done(), pdal::MrsidReader::done(), pdal::MatlabReader::done(), pdal::GDALWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::LasWriter::doneFile(), pdal::InfoKernel::dump(), pdal::IcpFilter::icp(), pdal::PythonFilter::run(), and TEST().
std::string pdal::BpfReader::getName () const virtual
Return the name of a stage.
Returns
The stage's name.
Implements pdal::Stage.
Definition at line 57 of file BpfReader.cpp.
References pdal::PluginInfo::name.
const SpatialReference & pdal::Stage::getSpatialReference () const inherited
Get the spatial reference of the stage.
Get the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Returns
The stage's spatial reference.
Definition at line 474 of file Stage.cpp.
References pdal::Stage::m_spatialReference.
Referenced by pdal::Stage::execute(), pdal::PgReader::initialize(), inspect(), pdal::LasWriter::prepOutput(), pdal::MergeFilter::ready(), pdal::MergeFilter::run(), and TEST().
int pdal::BpfReader::inflate (char * inbuf, uint32_t insize, char * outbuf, uint32_t outsize) private
Referenced by seekByteMajor().
void pdal::BpfReader::initialize () private virtual
Initialize stage after options have been processed. Implement in subclass.
Reimplemented from pdal::Stage.
Definition at line 94 of file BpfReader.cpp.
References pdal::Cartesian, pdal::IStream::close(), pdal::Error, pdal::Stage::log(), pdal::BpfHeader::m_compression, pdal::BpfHeader::m_coordId, pdal::BpfHeader::m_coordType, m_dims, pdal::Reader::m_filename, m_header, pdal::BpfHeader::m_len, m_stream, pdal::BpfHeader::m_version, pdal::IStream::open(), pdal::IStream::position(), pdal::BpfHeader::read(), pdal::BpfHeader::readDimensions(), readHeaderExtraData(), readPolarData(), readUlemData(), readUlemFiles(), pdal::IStream::seek(), pdal::BpfHeader::setLog(), pdal::Stage::setSpatialReference(), pdal::Stage::throwError(), pdal::Utils::toString(), and pdal::UTM.
Referenced by inspect().
QuickInfo pdal::BpfReader::inspect () private virtual
Get basic metadata (avoids reading points). Implement in subclass.
Returns
QuickInfo data.
Reimplemented from pdal::Stage.
Definition at line 59 of file BpfReader.cpp.
References pdal::Stage::getSpatialReference(), initialize(), pdal::QuickInfo::m_bounds, pdal::QuickInfo::m_dimNames, m_dims, m_header, pdal::BpfDimension::m_label, pdal::BpfDimension::m_max, pdal::BpfDimension::m_min, pdal::BpfHeader::m_numPts, pdal::QuickInfo::m_pointCount, pdal::QuickInfo::m_srs, pdal::QuickInfo::m_valid, pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
bool pdal::Stage::isDebug () const inherited
Determine whether the stage is in debug mode or not.
Returns
The stage's debug state.
Definition at line 243 of file Stage.hpp.
References pdal::Debug.
Referenced by pdal::Stage::setupLog(), pdal::Stage::startLogging(), and pdal::OciWriter::wipeBlockTable().
virtual LogPtr pdal::Stage::log () const virtual inherited
Return the stage's log pointer.
Returns
Log pointer.
Definition at line 225 of file Stage.hpp.
Referenced by pdal::OciReader::addDimensions(), pdal::GeoWaveReader::addDimensions(), pdal::SQLiteReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), pdal::LasWriter::addMetadataVlr(), pdal::LasWriter::addPipelineVlr(), pdal::OciWriter::blockTableExists(), pdal::CpdFilter::change(), pdal::PgWriter::CheckPointCloudExists(), pdal::PgWriter::CheckPostGISExists(), pdal::PgWriter::CheckTableExists(), pdal::SQLiteWriter::CreateBlockTable(), pdal::SQLiteWriter::CreateCloud(), pdal::SQLiteWriter::CreateCloudTable(), pdal::SQLiteWriter::CreateIndexes(), pdal::GeoWaveWriter::createJvm(), pdal::GeoWaveReader::createJvm(), pdal::PgReader::CursorSetup(), pdal::PgReader::CursorTeardown(), pdal::SQLiteWriter::DeleteBlockTable(), pdal::SQLiteWriter::DeleteCloudTable(), pdal::PgReader::fetchPcid(), pdal::SQLiteReader::fetchSpatialReference(), pdal::PgReader::fetchSpatialReference(), pdal::TextReader::fillFields(), pdal::ComputeRangeFilter::filter(), pdal::RadialDensityFilter::filter(), pdal::KDistanceFilter::filter(), pdal::LOFFilter::filter(), pdal::ELMFilter::filter(), pdal::ColorinterpFilter::filter(), pdal::GreedyProjection::filter(), pdal::LasWriter::finishOutput(), pdal::PgReader::getDataQuery(), pdal::GeoWaveWriter::initialize(), pdal::SQLiteWriter::initialize(), pdal::GeoWaveReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), initialize(), pdal::TerrasolidReader::initialize(), pdal::MbReader::loadData(), pdal::PgReader::NextBuffer(), pdal::GreyhoundReader::prepared(), pdal::PMFFilter::prepared(), pdal::NormalFilter::prepared(), pdal::LasWriter::prepared(), pdal::PMFFilter::processGround(), pdal::MongusFilter::processGround(), pdal::TextReader::processOne(), pdal::GreyhoundReader::read(), pdal::SQLiteReader::read(), pdal::PtsReader::read(), pdal::PgReader::read(), pdal::GDALReader::readBandData(), pdal::SQLiteReader::readPatch(), pdal::GeoWaveReader::ready(), pdal::PythonFilter::ready(), pdal::CropFilter::ready(), pdal::SQLiteReader::ready(), pdal::ColorinterpFilter::ready(), pdal::ColorizationFilter::ready(), pdal::BpfWriter::readyFile(), pdal::MovingLeastSquaresFilter::run(), pdal::GridProjectionFilter::run(), pdal::IcpFilter::run(), pdal::VoxelGridFilter::run(), pdal::CpdFilter::run(), pdal::MergeFilter::run(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::SampleFilter::run(), pdal::PythonFilter::run(), pdal::IQRFilter::run(), pdal::MADFilter::run(), pdal::OutlierFilter::run(), pdal::MongusFilter::run(), pdal::LasWriter::spatialReferenceChanged(), pdal::GeoWaveWriter::write(), pdal::MatlabWriter::write(), pdal::OciWriter::writeInit(), pdal::SQLiteWriter::writeInit(), pdal::OciWriter::writeTile(), and pdal::SQLiteWriter::writeTile().
virtual point_count_t pdal::BpfReader::numPoints () const virtual
Definition at line 65 of file BpfReader.hpp.
Referenced by eof(), readByteMajor(), readDimMajor(), readPointMajor(), ready(), seekByteMajor(), and seekDimMajor().
bool pdal::Stage::parseName (std::string o, std::string::size_type & pos) static inherited
Parse a stage name from a string. Return the name and update the position in the input string to the end of the stage name.
Parameters
o Input string to parse.
pos Parsing start/end position.
Returns
Whether the parsed name is a valid stage name.
Definition at line 504 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::Kernel::parseStageOption().
bool pdal::Stage::parseTagName (std::string o, std::string::size_type & pos) static inherited
Parse a tag name from a string. Return the name and update the position in the input string to the end of the tag name.
Parameters
o Input string to parse.
pos Parsing start/end position.
tag Parsed tag name.
Returns
Whether the parsed name is a valid tag name.
Definition at line 518 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::PipelineReaderJSON::extractTag(), and pdal::Kernel::parseStageOption().
point_count_t pdal::Stage::pointCount () const protected inherited
Return the point count of all point views at the start of execution. Only valid during execute().
Returns
Total number of points in all point views being executed.
Definition at line 328 of file Stage.hpp.
Referenced by pdal::PlyWriter::ready(), and pdal::PlyWriter::writeHeader().
void pdal::Stage::prepare (PointTableRef table) inherited
Prepare a stage for execution. This function needs to be called on the terminal stage of a pipeline (linked set of stages) before execute can be called. Prepare recurses through all input stages.
Parameters
table PointTable being used for stage pipeline.
Definition at line 138 of file Stage.cpp.
References pdal::Stage::addDimensions(), pdal::Stage::handleOptions(), pdal::Stage::initialize(), pdal::Stage::l_initialize(), pdal::BasePointTable::layout(), pdal::Stage::m_args, pdal::Stage::m_inputs, pdal::Stage::prepare(), pdal::Stage::prepared(), pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), pdal::Stage::prepare(), pdal::PipelineManager::prepare(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
QuickInfo pdal::Stage::preview () inherited
Retrieve some basic point information without reading all data when possible. Usually implemented only by Readers.
Definition at line 127 of file Stage.cpp.
References pdal::Stage::handleOptions(), pdal::Stage::inspect(), pdal::Stage::m_args, pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by pdal::TIndexKernel::getFileInfo(), pdal::PipelineManager::preview(), pdal::InfoKernel::run(), and TEST().
bool pdal::BpfReader::processOne (PointRef &) private virtual
Process a single point (streaming mode). Implement in sublcass.
Parameters
point Point to process.
Returns
Readers return false when no more points are to be read. Filters return false if a point is to be filtered-out (not passed to subsequent stages).
Reimplemented from pdal::Stage.
Definition at line 290 of file BpfReader.cpp.
References pdal::ByteMajor, pdal::DimMajor, eof(), pdal::Reader::m_count, m_header, m_index, pdal::BpfHeader::m_pointFormat, pdal::PointMajor, readByteMajor(), readDimMajor(), and readPointMajor().
point_count_t pdal::BpfReader::read (PointViewPtr data, point_count_t num) private virtual
Reimplemented from pdal::Reader.
Definition at line 308 of file BpfReader.cpp.
References pdal::ByteMajor, pdal::DimMajor, m_header, pdal::BpfHeader::m_pointFormat, pdal::PointMajor, readByteMajor(), readDimMajor(), and readPointMajor().
size_t pdal::BpfReader::readBlock (std::vector< char > & outBuf, size_t index) private
Referenced by ready(), and seekByteMajor().
void pdal::BpfReader::readByteMajor (PointRef & point) private
Definition at line 488 of file BpfReader.cpp.
References pdal::BpfMuellerMatrix::apply(), b, pdal::georeference::anonymous_namespace{Georeference.cpp}::f, m_dims, m_header, m_index, m_stream, pdal::BpfHeader::m_xform, seekByteMajor(), pdal::PointRef::setField(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by processOne(), and read().
point_count_t pdal::BpfReader::readByteMajor (PointViewPtr data, point_count_t count) private
Definition at line 528 of file BpfReader.cpp.
References pdal::BpfMuellerMatrix::apply(), b, pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Reader::m_cb, m_dims, m_header, m_index, m_stream, pdal::BpfHeader::m_xform, numPoints(), seekByteMajor(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
void pdal::BpfReader::readDimMajor (PointRef & point) private
Definition at line 394 of file BpfReader.cpp.
References pdal::BpfMuellerMatrix::apply(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, m_charbufs, pdal::BpfHeader::m_compression, m_deflateBuf, m_dims, pdal::Reader::m_filename, m_header, m_index, m_start, m_streams, pdal::BpfHeader::m_xform, numPoints(), pdal::PointRef::setField(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by processOne(), and read().
point_count_t pdal::BpfReader::readDimMajor (PointViewPtr data, point_count_t count) private
Definition at line 448 of file BpfReader.cpp.
References pdal::BpfMuellerMatrix::apply(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Reader::m_cb, m_dims, m_header, m_index, m_stream, pdal::BpfHeader::m_xform, numPoints(), seekDimMajor(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
bool pdal::BpfReader::readHeaderExtraData () private
Encode all data that follows the headers as metadata->
Returns
Whether the stream is still valid.
Definition at line 230 of file BpfReader.cpp.
References pdal::MetadataNode::addEncoded(), pdal::IStream::get(), m_header, pdal::BpfHeader::m_len, pdal::Stage::m_metadata, m_stream, pdal::IStream::position(), and pdal::Dimension::size().
Referenced by initialize().
void pdal::BpfReader::readPointMajor (PointRef & point) private
Definition at line 329 of file BpfReader.cpp.
References pdal::BpfMuellerMatrix::apply(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, m_dims, m_header, m_index, m_stream, pdal::BpfHeader::m_xform, seekPointMajor(), pdal::PointRef::setField(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by processOne(), and read().
point_count_t pdal::BpfReader::readPointMajor (PointViewPtr data, point_count_t count) private
Definition at line 358 of file BpfReader.cpp.
References pdal::BpfMuellerMatrix::apply(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Reader::m_cb, m_dims, m_header, m_index, m_stream, pdal::BpfHeader::m_xform, numPoints(), seekPointMajor(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
bool pdal::BpfReader::readPolarData () private
Definition at line 243 of file BpfReader.cpp.
References pdal::BpfPolarHeader::m_numFrames, m_polarFrames, m_polarHeader, m_stream, pdal::BpfPolarHeader::read(), and pdal::BpfPolarFrame::read().
Referenced by initialize().
bool pdal::BpfReader::readUlemData () private
Definition at line 199 of file BpfReader.cpp.
References pdal::BpfUlemHeader::m_numFrames, m_stream, m_ulemFrames, m_ulemHeader, pdal::BpfUlemHeader::read(), and pdal::BpfUlemFrame::read().
Referenced by initialize().
bool pdal::BpfReader::readUlemFiles () private
Definition at line 215 of file BpfReader.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addEncoded(), pdal::BpfUlemFile::m_buf, pdal::BpfUlemFile::m_filename, pdal::BpfUlemFile::m_len, pdal::Stage::m_metadata, m_stream, and pdal::BpfUlemFile::read().
Referenced by initialize().
void pdal::BpfReader::ready (PointTableRef) private virtual
First part of the execute step. Called after all stages have been prepared. Implement in subclass.
Parameters
table PointTable associated with the pipeline.
Reimplemented from pdal::Stage.
Definition at line 258 of file BpfReader.cpp.
References pdal::Charbuf::initialize(), m_charbuf, pdal::BpfHeader::m_compression, m_deflateBuf, m_dims, pdal::Reader::m_filename, m_header, m_index, pdal::BpfHeader::m_len, m_start, m_stream, numPoints(), pdal::IStream::open(), pdal::IStream::position(), pdal::IStream::pushStream(), readBlock(), and pdal::IStream::seek().
void pdal::Stage::removeOptions (const Options & opts) inherited
Remove options from a stage's option set.
Parameters
opts Options to remove.
Definition at line 206 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions().
void pdal::BpfReader::seekByteMajor (size_t dimIdx, size_t byteIdx, PointId ptIdx) private
Definition at line 606 of file BpfReader.cpp.
References pdal::IStream::get(), inflate(), m_start, m_stream, numPoints(), readBlock(), and pdal::IStream::seek().
Referenced by readByteMajor().
void pdal::BpfReader::seekDimMajor (size_t dimIdx, PointId ptIdx) private
Definition at line 598 of file BpfReader.cpp.
References m_start, m_stream, numPoints(), and pdal::IStream::seek().
Referenced by readDimMajor().
void pdal::BpfReader::seekPointMajor (PointId ptIdx) private
Definition at line 591 of file BpfReader.cpp.
References m_dims, m_start, m_stream, and pdal::IStream::seek().
Referenced by readPointMajor().
void pdal::Stage::serialize (MetadataNode root, PipelineWriter::TagMap & tags) const inherited
Serialize a stage by inserting apporpritate data into the provided MetadataNode. Used to dump a pipeline specification in a portable format.
Parameters
root Node to which a stages meatdata should be added.
tags Pipeline writer's current list of stage tags.
Definition at line 64 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), pdal::Stage::getName(), pdal::Stage::m_inputs, pdal::Stage::m_options, and pdal::Options::toMetadata().
Referenced by pdal::PipelineWriter::writePipeline().
void pdal::Stage::setInput (Stage & input) inherited
Add a stage to the input list of this stage.
Parameters
input Stage to use as input.
Definition at line 85 of file Stage.hpp.
Referenced by compareTextLasStreaming(), pdal::MergeKernel::execute(), pdal::TIndexReader::initialize(), main(), pdal::PipelineManager::makeFilter(), pdal::TIndexKernel::mergeFile(), pdal::PipelineReaderJSON::parsePipeline(), pdal::PipelineManager::replace(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::TransformationFilterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), pdal::TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testOverlay(), and writeData().
void pdal::Stage::setLog (LogPtr & log) inherited
Set the stage's log.
Parameters
log Log pointer.
Definition at line 217 of file Stage.hpp.
References setup::log.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), and testOverlay().
void pdal::Stage::setOptions (Options options) inherited
Set a stage's options.
Set the options on a stage, clearing all previously set options.
Parameters
options Options to set.
Definition at line 172 of file Stage.hpp.
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), getBytes(), pdal::TIndexReader::initialize(), main(), anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::PipelineManager::setOptions(), pdal::TransformationFilterTest::SetUp(), pdal::MatlabWriterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_file_type_stream(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), testReadWrite(), and writeData().
void pdal::Stage::setProgressFd (int fd) inherited
Set a file descriptor to which progress information should be written.
Parameters
fd Progress file descriptor.
Definition at line 93 of file Stage.hpp.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), and pdal::PipelineManager::addWriter().
void pdal::Reader::setReadCb (PointReadFunc cb) inherited
Definition at line 55 of file Reader.hpp.
Referenced by pdal::TEST(), and TEST().
void pdal::Stage::setSpatialReference (SpatialReference const & srs) inherited
Set the spatial reference of a stage.
Set the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Parameters
srs Spatial reference to set.
Definition at line 480 of file Stage.cpp.
References pdal::Stage::m_metadata.
Referenced by pdal::OciReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), initialize(), pdal::Ilvis2Reader::initialize(), pdal::PgReader::initialize(), pdal::LasWriter::initialize(), pdal::OptechReader::OptechReader(), pdal::MyReader::ready(), and TEST().
void pdal::Stage::setSpatialReference (MetadataNode & m, SpatialReference const & spatialRef) protected inherited
Definition at line 486 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::empty(), pdal::MetadataNode::findChild(), pdal::SpatialReference::getWKT(), pdal::Stage::m_spatialReference, pdal::MetadataNode::name(), and pdal::SpatialReference::toMetadata().
void pdal::Stage::setTag (const std::string & tag) inherited
Set a specific tag name.
Definition at line 256 of file Stage.hpp.
Referenced by pdal::PipelineManager::makeFilter(), and pdal::PipelineManager::makeReader().
void pdal::Stage::startLogging () const inherited
Push the stage's leader into the log.
Definition at line 538 of file Stage.cpp.
References pdal::gdal::ErrorHandler::getGlobalErrorHandler(), pdal::Stage::isDebug(), pdal::Stage::m_log, pdal::Stage::m_logLeader, and pdal::gdal::ErrorHandler::set().
Referenced by pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::preview().
void pdal::Stage::stopLogging () const inherited
Pop the stage's leader from the log.
Definition at line 545 of file Stage.cpp.
References pdal::Stage::m_log.
Referenced by pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::preview().
virtual std::string pdal::Stage::tag () const virtual inherited
Return the tag name of a stage.
Returns
The tag name.
Definition at line 264 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTag(), pdal::TranslateKernel::makeJSONPipeline(), and pdal::PipelineManager::stageOptions().
void pdal::Stage::throwError (const std::string & s) const protected inherited
Definition at line 532 of file Stage.cpp.
References pdal::Stage::getName().
Referenced by pdal::SQLiteReader::addDimensions(), pdal::MrsidReader::addDimensions(), pdal::TextReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), pdal::PlyReader::addDimensions(), pdal::LasWriter::addGeotiffVlrs(), pdal::LasWriter::addVlr(), pdal::PgWriter::CheckTableExists(), pdal::OciWriter::createPCEntry(), pdal::ReprojectionFilter::createTransform(), pdal::MatlabWriter::done(), pdal::NitfWriter::doneFile(), pdal::GDALWriter::doneFile(), pdal::OGRWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::GDALWriter::expandGrid(), pdal::PlyReader::extractElement(), pdal::PlyReader::extractEnd(), pdal::PlyReader::extractFormat(), pdal::PlyReader::extractHeader(), pdal::PlyReader::extractMagic(), pdal::PlyReader::extractProperty(), pdal::PgReader::fetchPcid(), pdal::PgReader::fetchSpatialReference(), pdal::LasWriter::fillForwardList(), pdal::LasWriter::fillHeader(), pdal::LasWriter::fillPointBuf(), pdal::HAGFilter::filter(), pdal::EigenvaluesFilter::filter(), pdal::ApproximateCoplanarFilter::filter(), pdal::NormalFilter::filter(), pdal::LasWriter::finishOutput(), pdal::TIndexReader::getFields(), pdal::PgReader::getNumPoints(), pdal::PlyWriter::getType(), pdal::LasWriter::handleLaszip(), pdal::OciWriter::initialize(), pdal::SQLiteWriter::initialize(), pdal::OciReader::initialize(), pdal::GDALWriter::initialize(), pdal::TextReader::initialize(), pdal::ReprojectionFilter::initialize(), pdal::PtsReader::initialize(), pdal::RangeFilter::initialize(), pdal::MatlabReader::initialize(), pdal::OGRWriter::initialize(), pdal::FerryFilter::initialize(), pdal::SQLiteReader::initialize(), pdal::OptechReader::initialize(), pdal::DividerFilter::initialize(), pdal::TIndexReader::initialize(), pdal::QfitReader::initialize(), pdal::BpfWriter::initialize(), pdal::ColorizationFilter::initialize(), initialize(), pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::LasWriter::initialize(), pdal::FauxReader::initialize(), pdal::GreedyProjection::initialize(), pdal::GDALReader::inspect(), pdal::OciWriter::isGeographic(), pdal::BpfWriter::loadBpfDimensions(), pdal::MbReader::loadData(), pdal::SQLiteWriter::loadGeometryWKT(), pdal::OciWriter::loadSQLData(), pdal::NitfWriter::NitfWriter(), pdal::MatlabWriter::prepared(), pdal::GDALWriter::prepared(), pdal::PlyWriter::prepared(), pdal::ComputeRangeFilter::prepared(), pdal::HAGFilter::prepared(), pdal::GroupByFilter::prepared(), pdal::IQRFilter::prepared(), pdal::LocateFilter::prepared(), pdal::RangeFilter::prepared(), pdal::MADFilter::prepared(), pdal::OGRWriter::prepared(), pdal::FerryFilter::prepared(), pdal::SortFilter::prepared(), pdal::ColorinterpFilter::prepared(), pdal::LasWriter::prepared(), pdal::OGRWriter::processOne(), pdal::Ilvis2Reader::processOne(), pdal::MatlabReader::processOne(), pdal::QfitReader::read(), pdal::OciReader::readBlob(), pdal::PlyReader::readElement(), pdal::SQLiteReader::readPatch(), pdal::OciReader::readPointMajor(), pdal::MatlabWriter::ready(), pdal::PlyWriter::ready(), pdal::SbetReader::ready(), pdal::GDALReader::ready(), pdal::OptechReader::ready(), pdal::PtsReader::ready(), pdal::ColorinterpFilter::ready(), pdal::QfitReader::ready(), pdal::TextReader::ready(), pdal::MbReader::ready(), pdal::ColorizationFilter::ready(), pdal::Ilvis2Reader::ready(), pdal::OGRWriter::readyFile(), pdal::BpfWriter::readyFile(), pdal::LasWriter::readyFile(), pdal::LasWriter::readyLazPerfCompression(), pdal::GDALWriter::readyTable(), pdal::NitfWriter::reprojectBoxToDD(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::PgWriter::SetupSchema(), pdal::CropFilter::transform(), pdal::OciWriter::updatePCExtent(), pdal::OciReader::validateQuery(), pdal::SQLiteReader::validateQuery(), pdal::MatlabWriter::write(), pdal::LasWriter::writeLasZipBuf(), pdal::OciWriter::writePointMajor(), pdal::OciWriter::writeTile(), pdal::SQLiteWriter::writeTile(), and pdal::BpfWriter::writeView().
void pdal::Stage::throwStreamingError () const protected inherited
Definition at line 339 of file Stage.hpp.
Referenced by pdal::ColorinterpFilter::processOne().
Member Data Documentation
PointReadFunc pdal::Reader::m_cb protected inherited
Definition at line 61 of file Reader.hpp.
Referenced by pdal::MyReader::read(), pdal::GeoWaveReader::read(), pdal::GreyhoundReader::read(), pdal::SbetReader::read(), pdal::OptechReader::read(), pdal::QfitReader::read(), pdal::Ilvis2Reader::read(), pdal::TerrasolidReader::read(), pdal::FauxReader::read(), readByteMajor(), pdal::OciReader::readDimMajor(), readDimMajor(), pdal::SQLiteReader::readPatch(), pdal::OciReader::readPointMajor(), and readPointMajor().
Charbuf pdal::BpfReader::m_charbuf private
Streambuf for deflated data.
Definition at line 83 of file BpfReader.hpp.
Referenced by ready().
std::vector<std::unique_ptr<Charbuf> > pdal::BpfReader::m_charbufs private
Definition at line 87 of file BpfReader.hpp.
Referenced by readDimMajor().
point_count_t pdal::Reader::m_count protected inherited
Definition at line 60 of file Reader.hpp.
Referenced by pdal::GDALReader::initialize(), pdal::FauxReader::initialize(), processOne(), pdal::PlyReader::processOne(), pdal::FauxReader::processOne(), pdal::GDALReader::read(), pdal::Reader::readerAddArgs(), and pdal::GeoWaveReader::ready().
Arg* pdal::Reader::m_countArg protected inherited
Definition at line 63 of file Reader.hpp.
Referenced by pdal::Reader::readerAddArgs().
std::vector<char> pdal::BpfReader::m_deflateBuf private
Buffer for deflated data.
Definition at line 81 of file BpfReader.hpp.
Referenced by readDimMajor(), and ready().
BpfDimensionList pdal::BpfReader::m_dims private
Definition at line 70 of file BpfReader.hpp.
Referenced by addDimensions(), initialize(), inspect(), readByteMajor(), readDimMajor(), readPointMajor(), ready(), and seekPointMajor().
std::string pdal::Reader::m_filename protected inherited
Definition at line 59 of file Reader.hpp.
Referenced by pdal::TextReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::MbReader::done(), pdal::MrsidReader::done(), pdal::MatlabReader::done(), pdal::TextReader::fillFields(), pdal::TIndexReader::getFields(), pdal::GreyhoundReader::initialize(), pdal::TextReader::initialize(), pdal::PtsReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::OptechReader::initialize(), pdal::TIndexReader::initialize(), pdal::QfitReader::initialize(), pdal::MrsidReader::initialize(), initialize(), pdal::NitfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::PlyReader::initialize(), pdal::GDALReader::inspect(), pdal::TextReader::processOne(), pdal::MyReader::read(), pdal::PcdReader::read(), pdal::PtsReader::read(), readDimMajor(), pdal::Reader::readerAddArgs(), pdal::PcdReader::ready(), pdal::SbetReader::ready(), pdal::GDALReader::ready(), pdal::OptechReader::ready(), pdal::PtsReader::ready(), pdal::QfitReader::ready(), pdal::TextReader::ready(), pdal::MbReader::ready(), ready(), pdal::Ilvis2Reader::ready(), pdal::TerrasolidReader::ready(), and pdal::PlyReader::ready().
Arg* pdal::Reader::m_filenameArg protected inherited
Definition at line 62 of file Reader.hpp.
Referenced by pdal::Reader::readerAddArgs().
BpfHeader pdal::BpfReader::m_header private
Definition at line 69 of file BpfReader.hpp.
Referenced by initialize(), inspect(), processOne(), read(), readByteMajor(), readDimMajor(), readHeaderExtraData(), readPointMajor(), and ready().
point_count_t pdal::BpfReader::m_index private
Index of the next point to read.
Definition at line 79 of file BpfReader.hpp.
Referenced by eof(), processOne(), readByteMajor(), readDimMajor(), readPointMajor(), and ready().
MetadataNode pdal::Stage::m_metadata protected inherited
Stage's metadata.
Definition at line 316 of file Stage.hpp.
Referenced by pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), pdal::Stage::l_initialize(), readHeaderExtraData(), readUlemFiles(), pdal::Ilvis2Reader::ready(), and pdal::Stage::setSpatialReference().
Options pdal::Stage::m_options protected inherited
Stage's options.
Definition at line 315 of file Stage.hpp.
Referenced by pdal::Stage::addConditionalOptions(), pdal::Stage::handleOptions(), and pdal::Stage::serialize().
std::vector<BpfPolarFrame> pdal::BpfReader::m_polarFrames private
Definition at line 75 of file BpfReader.hpp.
Referenced by readPolarData().
BpfPolarHeader pdal::BpfReader::m_polarHeader private
Definition at line 74 of file BpfReader.hpp.
Referenced by readPolarData().
int pdal::Stage::m_progressFd protected inherited
Descriptor for progress info.
Definition at line 317 of file Stage.hpp.
Referenced by pdal::LasWriter::doneFile(), pdal::NitfWriter::readyFile(), pdal::LasWriter::readyFile(), and pdal::LasWriter::writeView().
Dimension::IdList pdal::BpfReader::m_schemaDims private
Definition at line 71 of file BpfReader.hpp.
std::streampos pdal::BpfReader::m_start private
Stream position at the beginning of point records.
Definition at line 77 of file BpfReader.hpp.
Referenced by readDimMajor(), ready(), seekByteMajor(), seekDimMajor(), and seekPointMajor().
ILeStream pdal::BpfReader::m_stream private
Definition at line 68 of file BpfReader.hpp.
Referenced by done(), initialize(), readByteMajor(), readDimMajor(), readHeaderExtraData(), readPointMajor(), readPolarData(), readUlemData(), readUlemFiles(), ready(), seekByteMajor(), seekDimMajor(), and seekPointMajor().
std::vector<std::unique_ptr<ILeStream> > pdal::BpfReader::m_streams private
Definition at line 86 of file BpfReader.hpp.
Referenced by readDimMajor().
std::vector<BpfUlemFrame> pdal::BpfReader::m_ulemFrames private
Definition at line 73 of file BpfReader.hpp.
Referenced by readUlemData().
BpfUlemHeader pdal::BpfReader::m_ulemHeader private
Definition at line 72 of file BpfReader.hpp.
Referenced by readUlemData().
The documentation for this class was generated from the following files:
pdal/io/BpfReader.hpp
pdal/io/BpfReader.cpp