PDAL: pdal::plang::Script Class Reference
pdal::plang::Script Class Reference
#include <Script.hpp>
Public Member Functions
Script (const std::string &sourceCode, const std::string &moduleName, const std::string &functionName)
const char * source () const
const char * module () const
const char * function () const
Private Member Functions
Script & operator= (Script const &rhs)
Private Attributes
std::string m_source
std::string m_module
std::string m_function
Detailed Description
Definition at line 46 of file Script.hpp.
Constructor & Destructor Documentation
pdal::plang::Script::Script (const std::string & sourceCode, const std::string & moduleName, const std::string & functionName)
Definition at line 46 of file Script.cpp.
Member Function Documentation
const char* pdal::plang::Script::function () const
Definition at line 61 of file Script.hpp.
Referenced by pdal::plang::Invocation::compile(), and pdal::plang::operator<<().
const char* pdal::plang::Script::module () const
Definition at line 57 of file Script.hpp.
Referenced by pdal::plang::Invocation::compile(), and pdal::plang::operator<<().
Script& pdal::plang::Script::operator= (Script const & rhs) private
const char* pdal::plang::Script::source () const
Definition at line 53 of file Script.hpp.
Referenced by pdal::plang::Invocation::compile(), and pdal::plang::operator<<().
Member Data Documentation
std::string pdal::plang::Script::m_function private
Definition at line 69 of file Script.hpp.
std::string pdal::plang::Script::m_module private
Definition at line 68 of file Script.hpp.
std::string pdal::plang::Script::m_source private
Definition at line 67 of file Script.hpp.
The documentation for this class was generated from the following files:
pdal/plugins/python/plang/Script.hpp
pdal/plugins/python/plang/Script.cpp