PDAL: libpdaljava::Pipeline Class Reference
libpdaljava::Pipeline Class Reference
#include <JavaPipeline.hpp>
Public Member Functions
Pipeline (std::string const &xml)
~Pipeline ()
int64_t execute ()
bool validate ()
std::string getPipeline () const
std::string getMetadata () const
std::string getSchema () const
std::string getLog () const
pdal::PointViewSet getPointViews () const
void setLogLevel (int level)
int getLogLevel () const
Private Attributes
pdal::PipelineExecutor m_executor
Detailed Description
Definition at line 57 of file JavaPipeline.hpp.
Constructor & Destructor Documentation
libpdaljava::Pipeline::Pipeline (std::string const & xml)
Definition at line 44 of file JavaPipeline.cpp.
libpdaljava::Pipeline::~Pipeline ()
Definition at line 50 of file JavaPipeline.cpp.
Member Function Documentation
int64_t libpdaljava::Pipeline::execute ()
Definition at line 64 of file JavaPipeline.cpp.
References pdal::PipelineExecutor::execute(), and m_executor.
Referenced by Java_io_pdal_Pipeline_execute().
std::string libpdaljava::Pipeline::getLog () const
Definition at line 76 of file JavaPipeline.hpp.
References setup::level, and pdal::pclsupport::setLogLevel().
Referenced by Java_io_pdal_Pipeline_getLog().
int libpdaljava::Pipeline::getLogLevel () const
Definition at line 59 of file JavaPipeline.cpp.
References pdal::PipelineExecutor::getLogLevel(), and m_executor.
Referenced by Java_io_pdal_Pipeline_getLogLevel().
std::string libpdaljava::Pipeline::getMetadata () const
Definition at line 68 of file JavaPipeline.hpp.
Referenced by Java_io_pdal_Pipeline_getMetadata().
std::string libpdaljava::Pipeline::getPipeline () const
Definition at line 64 of file JavaPipeline.hpp.
PointViewSet libpdaljava::Pipeline::getPointViews () const
Definition at line 76 of file JavaPipeline.cpp.
References pdal::PipelineExecutor::executed(), pdal::PipelineExecutor::getManagerConst(), m_executor, and pdal::PipelineManager::views().
Referenced by Java_io_pdal_Pipeline_getPointViews().
std::string libpdaljava::Pipeline::getSchema () const
Definition at line 72 of file JavaPipeline.hpp.
Referenced by Java_io_pdal_Pipeline_getSchema().
void libpdaljava::Pipeline::setLogLevel (int level)
Definition at line 54 of file JavaPipeline.cpp.
References m_executor, and pdal::PipelineExecutor::setLogLevel().
Referenced by Java_io_pdal_Pipeline_setLogLevel().
bool libpdaljava::Pipeline::validate ()
Definition at line 71 of file JavaPipeline.cpp.
References m_executor, and pdal::PipelineExecutor::validate().
Referenced by Java_io_pdal_Pipeline_validate().
Member Data Documentation
pdal::PipelineExecutor libpdaljava::Pipeline::m_executor private
Definition at line 87 of file JavaPipeline.hpp.
Referenced by execute(), getLogLevel(), getPointViews(), setLogLevel(), and validate().
The documentation for this class was generated from the following files:
pdal/java/native/src/include/JavaPipeline.hpp
pdal/java/native/src/JavaPipeline.cpp