PDAL: pdal::Bounds Class Reference
pdal::Bounds Class Reference
#include <Bounds.hpp>
Public Member Functions
Bounds ()
Bounds (const BOX3D &box)
Bounds (const BOX2D &box)
BOX3D to3d () const
BOX2D to2d () const
bool is3d () const
Private Member Functions
void set (const BOX3D &box)
void set (const BOX2D &box)
Private Attributes
BOX3D m_box
Friends
PDAL_DLL std::istream & operator>> (std::istream &in, Bounds &bounds)
PDAL_DLL std::ostream & operator<< (std::ostream &out, const Bounds &bounds)
Detailed Description
Wrapper for BOX3D and BOX2D to allow extraction as either. Typically used to facilitate streaming either a BOX2D or BOX3D
Definition at line 563 of file Bounds.hpp.
Constructor & Destructor Documentation
pdal::Bounds::Bounds ()
Definition at line 566 of file Bounds.hpp.
References pdal::operator<<(), pdal::operator>>(), and PDAL_DLL.
pdal::Bounds::Bounds (const BOX3D & box) explicit
Definition at line 159 of file Bounds.cpp.
pdal::Bounds::Bounds (const BOX2D & box) explicit
Definition at line 163 of file Bounds.cpp.
References pdal::anonymous_namespace{Bounds.cpp}::HIGHEST, pdal::anonymous_namespace{Bounds.cpp}::LOWEST, m_box, pdal::BOX3D::maxz, and pdal::BOX3D::minz.
Member Function Documentation
bool pdal::Bounds::is3d () const
Definition at line 181 of file Bounds.cpp.
References m_box, pdal::BOX3D::maxz, and pdal::BOX3D::minz.
Referenced by pdal::operator<<(), and to3d().
void pdal::Bounds::set (const BOX3D & box) private
Definition at line 187 of file Bounds.cpp.
References m_box.
Referenced by pdal::operator>>().
void pdal::Bounds::set (const BOX2D & box) private
Definition at line 193 of file Bounds.cpp.
References pdal::BOX3D, pdal::anonymous_namespace{Bounds.cpp}::HIGHEST, pdal::anonymous_namespace{Bounds.cpp}::LOWEST, m_box, pdal::BOX3D::maxz, and pdal::BOX3D::minz.
BOX2D pdal::Bounds::to2d () const
Definition at line 176 of file Bounds.cpp.
References m_box, and pdal::BOX3D::to2d().
Referenced by pdal::operator<<(), pdal::GDALWriter::readyFile(), pdal::GDALWriter::readyTable(), and pdal::GDALWriter::writeView().
BOX3D pdal::Bounds::to3d () const
Definition at line 169 of file Bounds.cpp.
References pdal::BOX3D, is3d(), and m_box.
Referenced by pdal::operator<<().
Friends And Related Function Documentation
PDAL_DLL std::ostream& operator<< (std::ostream & out, const Bounds & bounds) friend
Definition at line 326 of file Bounds.cpp.
PDAL_DLL std::istream& operator>> (std::istream & in, Bounds & bounds) friend
Definition at line 307 of file Bounds.cpp.
Member Data Documentation
BOX3D pdal::Bounds::m_box private
Definition at line 582 of file Bounds.hpp.
Referenced by Bounds(), is3d(), set(), to2d(), and to3d().
The documentation for this class was generated from the following files:
pdal/pdal/util/Bounds.hpp
pdal/pdal/util/Bounds.cpp