PDAL: pdal::mlang::Environment Class Reference
pdal::mlang::Environment Class Reference
#include <Environment.hpp>
Public Member Functions
Environment ()
~Environment ()
void execute (Script &script)
Static Public Member Functions
static EnvironmentPtr get ()
Public Attributes
Engine * m_engine
Detailed Description
Definition at line 58 of file Environment.hpp.
Constructor & Destructor Documentation
pdal::mlang::Environment::Environment ()
Definition at line 63 of file Environment.cpp.
References m_engine.
Referenced by get().
pdal::mlang::Environment::~Environment ()
Definition at line 72 of file Environment.cpp.
References m_engine.
Member Function Documentation
void pdal::mlang::Environment::execute (Script & script)
Definition at line 64 of file Environment.hpp.
EnvironmentPtr pdal::mlang::Environment::get () static
Definition at line 51 of file Environment.cpp.
References Environment(), and pdal::mlang::g_environment.
Referenced by pdal::MatlabFilter::run().
Member Data Documentation
Engine* pdal::mlang::Environment::m_engine
Definition at line 68 of file Environment.hpp.
Referenced by Environment(), pdal::MatlabFilter::run(), and ~Environment().
The documentation for this class was generated from the following files:
pdal/plugins/matlab/filters/Environment.hpp
pdal/plugins/matlab/filters/Environment.cpp