PDAL: pdal::OBeStream Class Reference
pdal::OBeStream Class Reference
#include <OStream.hpp>
Public Member Functions
PDAL_DLL OBeStream ()
PDAL_DLL OBeStream (const std::string &filename)
PDAL_DLL OBeStream (std::ostream *stream)
PDAL_DLL OBeStream & operator<< (uint8_t v)
PDAL_DLL OBeStream & operator<< (int8_t v)
PDAL_DLL OBeStream & operator<< (uint16_t v)
PDAL_DLL OBeStream & operator<< (int16_t v)
PDAL_DLL OBeStream & operator<< (uint32_t v)
PDAL_DLL OBeStream & operator<< (int32_t v)
PDAL_DLL OBeStream & operator<< (uint64_t v)
PDAL_DLL OBeStream & operator<< (int64_t v)
PDAL_DLL OBeStream & operator<< (float v)
PDAL_DLL OBeStream & operator<< (double v)
PDAL_DLL int open (const std::string &filename)
PDAL_DLL void close ()
PDAL_DLL bool isOpen () const
PDAL_DLL void flush ()
PDAL_DLL operator bool ()
PDAL_DLL void seek (std::streampos pos)
PDAL_DLL void put (const std::string &s)
PDAL_DLL void put (const std::string &s, size_t len)
PDAL_DLL void put (const char *c, size_t len)
PDAL_DLL void put (const unsigned char *c, size_t len)
PDAL_DLL std::streampos position () const
PDAL_DLL void pushStream (std::ostream *strm)
PDAL_DLL std::ostream * popStream ()
Protected Attributes
std::ostream * m_stream
std::ostream * m_fstream
Detailed Description
Stream wrapper for output of binary data that converts from host ordering to big endian format
Definition at line 212 of file OStream.hpp.
Constructor & Destructor Documentation
PDAL_DLL pdal::OBeStream::OBeStream ()
Definition at line 215 of file OStream.hpp.
PDAL_DLL pdal::OBeStream::OBeStream (const std::string & filename)
Definition at line 217 of file OStream.hpp.
PDAL_DLL pdal::OBeStream::OBeStream (std::ostream * stream)
Definition at line 219 of file OStream.hpp.
Member Function Documentation
PDAL_DLL void pdal::OStream::close () inherited
Definition at line 70 of file OStream.hpp.
References pdal::OStream::flush(), pdal::OStream::m_fstream, and pdal::OStream::m_stream.
Referenced by pdal::BpfWriter::doneFile().
PDAL_DLL void pdal::OStream::flush () inherited
Definition at line 79 of file OStream.hpp.
References pdal::OStream::m_stream.
Referenced by pdal::OStream::close().
PDAL_DLL bool pdal::OStream::isOpen () const inherited
Definition at line 77 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL int pdal::OStream::open (const std::string & filename) inherited
Definition at line 62 of file OStream.hpp.
References pdal::OStream::m_fstream, and pdal::OStream::m_stream.
Referenced by pdal::OStream::OStream(), and pdal::BpfWriter::readyFile().
PDAL_DLL pdal::OStream::operator bool () inherited
Definition at line 81 of file OStream.hpp.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (uint8_t v)
Definition at line 222 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (int8_t v)
Definition at line 228 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (uint16_t v)
Definition at line 234 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (int16_t v)
Definition at line 241 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (uint32_t v)
Definition at line 248 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (int32_t v)
Definition at line 255 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (uint64_t v)
Definition at line 262 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (int64_t v)
Definition at line 269 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (float v)
Definition at line 276 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL OBeStream& pdal::OBeStream::operator<< (double v)
Definition at line 285 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL std::ostream* pdal::OStream::popStream () inherited
Definition at line 104 of file OStream.hpp.
References pdal::OStream::m_stream, and pdal::OStream::m_streams.
PDAL_DLL std::streampos pdal::OStream::position () const inherited
Definition at line 97 of file OStream.hpp.
References pdal::OStream::m_stream.
Referenced by pdal::BpfWriter::readyFile().
PDAL_DLL void pdal::OStream::pushStream (std::ostream * strm) inherited
Definition at line 99 of file OStream.hpp.
References pdal::OStream::m_stream, and pdal::OStream::m_streams.
PDAL_DLL void pdal::OStream::put (const std::string & s) inherited
Definition at line 85 of file OStream.hpp.
Referenced by pdal::operator<<(), pdal::LasHeader::put(), pdal::BpfWriter::readyFile(), pdal::BpfDimension::write(), pdal::BpfHeader::write(), and pdal::BpfUlemFile::write().
PDAL_DLL void pdal::OStream::put (const std::string & s, size_t len) inherited
Definition at line 87 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL void pdal::OStream::put (const char * c, size_t len) inherited
Definition at line 93 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL void pdal::OStream::put (const unsigned char * c, size_t len) inherited
Definition at line 95 of file OStream.hpp.
References pdal::OStream::m_stream.
PDAL_DLL void pdal::OStream::seek (std::streampos pos) inherited
Definition at line 83 of file OStream.hpp.
References pdal::OStream::m_stream.
Referenced by pdal::BpfWriter::doneFile(), and pdal::LasWriter::finishOutput().
Member Data Documentation
std::ostream* pdal::OStream::m_fstream protected inherited
Definition at line 117 of file OStream.hpp.
Referenced by pdal::OStream::close(), pdal::OStream::open(), and pdal::OStream::~OStream().
std::ostream* pdal::OStream::m_stream protected inherited
Definition at line 116 of file OStream.hpp.
Referenced by pdal::OStream::close(), pdal::OStream::flush(), pdal::OStream::isOpen(), pdal::OStreamMarker::mark(), pdal::OStream::open(), pdal::OLeStream::operator<<(), operator<<(), pdal::OStreamMarker::OStreamMarker(), pdal::OStream::popStream(), pdal::OStream::position(), pdal::OStream::pushStream(), pdal::OStream::put(), pdal::OStreamMarker::rewind(), and pdal::OStream::seek().
The documentation for this class was generated from the following file:
pdal/pdal/util/OStream.hpp