PDAL: pdal::hexdensity::writer::OGR Class Reference
pdal::hexdensity::writer::OGR Class Reference
#include <OGR.hpp>
Public Member Functions
OGR (std::string const &filename, std::string srs, std::string driver="ESRI Shapefile", std::string layerName="")
~OGR ()
void writeBoundary (hexer::HexGrid *grid)
void writeDensity (hexer::HexGrid *grid)
Private Member Functions
void createLayer ()
void collectPath (hexer::Path *path, OGRGeometryH polygon)
OGRGeometryH collectHexagon (hexer::HexInfo const &info, hexer::HexGrid const *grid)
Private Attributes
std::string m_filename
std::string m_driver
std::string m_srs
OGRDataSourceH m_ds
OGRLayerH m_layer
std::string m_layerName
Detailed Description
Definition at line 61 of file OGR.hpp.
Constructor & Destructor Documentation
pdal::hexdensity::writer::OGR::OGR (std::string const & filename, std::string srs, std::string driver = "ESRI Shapefile", std::string layerName = "")
Definition at line 58 of file OGR.cpp.
References createLayer().
pdal::hexdensity::writer::OGR::~OGR ()
Definition at line 255 of file OGR.cpp.
References m_ds.
Member Function Documentation
OGRGeometryH pdal::hexdensity::writer::OGR::collectHexagon (hexer::HexInfo const & info, hexer::HexGrid const * grid) private
Definition at line 193 of file OGR.cpp.
Referenced by writeDensity().
void pdal::hexdensity::writer::OGR::collectPath (hexer::Path * path, OGRGeometryH polygon) private
Definition at line 165 of file OGR.cpp.
Referenced by writeBoundary().
void pdal::hexdensity::writer::OGR::createLayer () private
Definition at line 69 of file OGR.cpp.
References pdal::FileUtils::fileExists(), pdal::gdal::SpatialRef::get(), m_driver, m_ds, m_filename, m_layer, m_layerName, and m_srs.
Referenced by OGR().
void pdal::hexdensity::writer::OGR::writeBoundary (hexer::HexGrid * grid)
Definition at line 129 of file OGR.cpp.
References collectPath(), and m_layer.
void pdal::hexdensity::writer::OGR::writeDensity (hexer::HexGrid * grid)
Definition at line 223 of file OGR.cpp.
References collectHexagon(), and m_layer.
Referenced by pdal::DensityKernel::outputDensity().
Member Data Documentation
std::string pdal::hexdensity::writer::OGR::m_driver private
Definition at line 74 of file OGR.hpp.
Referenced by createLayer().
OGRDataSourceH pdal::hexdensity::writer::OGR::m_ds private
Definition at line 77 of file OGR.hpp.
Referenced by createLayer(), and ~OGR().
std::string pdal::hexdensity::writer::OGR::m_filename private
Definition at line 73 of file OGR.hpp.
Referenced by createLayer().
OGRLayerH pdal::hexdensity::writer::OGR::m_layer private
Definition at line 78 of file OGR.hpp.
Referenced by createLayer(), writeBoundary(), and writeDensity().
std::string pdal::hexdensity::writer::OGR::m_layerName private
Definition at line 79 of file OGR.hpp.
Referenced by createLayer().
std::string pdal::hexdensity::writer::OGR::m_srs private
Definition at line 75 of file OGR.hpp.
Referenced by createLayer().
The documentation for this class was generated from the following files:
pdal/plugins/hexbin/kernel/OGR.hpp
pdal/plugins/hexbin/kernel/OGR.cpp