PDAL: pdal::PipelineExecutor Class Reference
pdal::PipelineExecutor Class Reference
#include <PipelineExecutor.hpp>
Public Member Functions
PipelineExecutor (std::string const &json)
~PipelineExecutor ()
int64_t execute ()
bool validate ()
std::string getPipeline () const
std::string getMetadata () const
std::string getSchema () const
std::string getLog () const
void setLogLevel (int level)
int getLogLevel () const
bool executed () const
PipelineManager const & getManagerConst () const
PipelineManager & getManager ()
Private Member Functions
void setLogStream (std::ostream &strm)
Private Attributes
std::string m_json
pdal::PipelineManager m_manager
bool m_executed
std::stringstream m_logStream
pdal::LogLevel m_logLevel
Detailed Description
An executor hides the management of constructing, executing, and fetching data from a PipelineManager.
It is constructed with JSON defining a pipeline.
Definition at line 54 of file PipelineExecutor.hpp.
Constructor & Destructor Documentation
pdal::PipelineExecutor::PipelineExecutor (std::string const & json)
Construct a PipelineExecutor
Parameters
json Pipeline JSON defining the PDAL operations
Definition at line 42 of file PipelineExecutor.cpp.
References pdal::Error.
pdal::PipelineExecutor::~PipelineExecutor ()
dtor
Definition at line 67 of file PipelineExecutor.hpp.
References setup::level, and pdal::pclsupport::setLogLevel().
Member Function Documentation
int64_t pdal::PipelineExecutor::execute ()
Execute the pipeline
Returns
total number of points produced by the pipeline.
Definition at line 95 of file PipelineExecutor.cpp.
References pdal::PipelineManager::execute(), m_executed, m_json, m_manager, and pdal::PipelineManager::readPipeline().
Referenced by libpdaljava::Pipeline::execute(), and libpdalpython::Pipeline::execute().
bool pdal::PipelineExecutor::executed () const
Returns
has the pipeline been executed
Definition at line 117 of file PipelineExecutor.hpp.
Referenced by libpdalpython::Pipeline::getArrays(), and libpdaljava::Pipeline::getPointViews().
std::string pdal::PipelineExecutor::getLog () const
Returns
log output for the executed pipeline. use setLogLevel to adjust verbosity.
Definition at line 134 of file PipelineExecutor.cpp.
References m_logStream.
int pdal::PipelineExecutor::getLogLevel () const
Returns
log verbosity
Definition at line 128 of file PipelineExecutor.cpp.
References m_logLevel.
Referenced by libpdaljava::Pipeline::getLogLevel(), and libpdalpython::Pipeline::getLogLevel().
PipelineManager& pdal::PipelineExecutor::getManager ()
Returns
a reference to the pipeline manager
Definition at line 131 of file PipelineExecutor.hpp.
PipelineManager const& pdal::PipelineExecutor::getManagerConst () const
Returns
a const reference to the pipeline manager
Definition at line 126 of file PipelineExecutor.hpp.
Referenced by libpdalpython::Pipeline::getArrays(), and libpdaljava::Pipeline::getPointViews().
std::string pdal::PipelineExecutor::getMetadata () const
Returns
computed metadata for the pipeline and all stages
Definition at line 61 of file PipelineExecutor.cpp.
References pdal::MetadataNode::clone(), pdal::PipelineManager::getMetadata(), m_executed, m_manager, and pdal::Utils::toJSON().
std::string pdal::PipelineExecutor::getPipeline () const
Returns
the transliterated pipeline
Definition at line 50 of file PipelineExecutor.cpp.
References pdal::PipelineManager::getStage(), m_executed, m_manager, and pdal::PipelineWriter::writePipeline().
std::string pdal::PipelineExecutor::getSchema () const
Returns
computed schema for the pipeline
Definition at line 73 of file PipelineExecutor.cpp.
References pdal::MetadataNode::clone(), pdal::BasePointTable::layout(), m_executed, m_manager, pdal::PipelineManager::pointTable(), pdal::Utils::toJSON(), and pdal::PointLayout::toMetadata().
void pdal::PipelineExecutor::setLogLevel (int level)
set the log verbosity. Use values 0-8.
Definition at line 118 of file PipelineExecutor.cpp.
References setup::level, m_logLevel, m_logStream, and setLogStream().
Referenced by libpdaljava::Pipeline::setLogLevel(), and libpdalpython::Pipeline::setLogLevel().
void pdal::PipelineExecutor::setLogStream (std::ostream & strm) private
Definition at line 108 of file PipelineExecutor.cpp.
References setup::log, m_logLevel, m_manager, and pdal::PipelineManager::setLog().
Referenced by setLogLevel().
bool pdal::PipelineExecutor::validate ()
Validate the pipeline
Returns
does PDAL think the pipeline is valid?
Definition at line 85 of file PipelineExecutor.cpp.
References m_json, m_manager, pdal::PipelineManager::prepare(), and pdal::PipelineManager::readPipeline().
Referenced by libpdaljava::Pipeline::validate(), and libpdalpython::Pipeline::validate().
Member Data Documentation
bool pdal::PipelineExecutor::m_executed private
Definition at line 138 of file PipelineExecutor.hpp.
Referenced by execute(), getMetadata(), getPipeline(), and getSchema().
std::string pdal::PipelineExecutor::m_json private
Definition at line 136 of file PipelineExecutor.hpp.
Referenced by execute(), and validate().
pdal::LogLevel pdal::PipelineExecutor::m_logLevel private
Definition at line 140 of file PipelineExecutor.hpp.
Referenced by getLogLevel(), setLogLevel(), and setLogStream().
std::stringstream pdal::PipelineExecutor::m_logStream private
Definition at line 139 of file PipelineExecutor.hpp.
Referenced by getLog(), and setLogLevel().
pdal::PipelineManager pdal::PipelineExecutor::m_manager private
Definition at line 137 of file PipelineExecutor.hpp.
Referenced by execute(), getMetadata(), getPipeline(), getSchema(), setLogStream(), and validate().
The documentation for this class was generated from the following files:
pdal/pdal/PipelineExecutor.hpp
pdal/pdal/PipelineExecutor.cpp