PDAL: pdal::Extractor Class Reference
pdal::Extractor Class Reference abstract
#include <Extractor.hpp>
Public Member Functions
Extractor (const char *buf, std::size_t size)
operator bool ()
void seek (std::size_t pos)
void skip (std::size_t cnt)
size_t position () const
bool good () const
void get (std::string &s, size_t size)
void get (std::vector< char > &buf)
void get (std::vector< unsigned char > &buf)
void get (char *buf, size_t size)
void get (unsigned char *buf, size_t size)
virtual Extractor & operator>> (uint8_t &v)=0
virtual Extractor & operator>> (int8_t &v)=0
virtual Extractor & operator>> (uint16_t &v)=0
virtual Extractor & operator>> (int16_t &v)=0
virtual Extractor & operator>> (uint32_t &v)=0
virtual Extractor & operator>> (int32_t &v)=0
virtual Extractor & operator>> (uint64_t &v)=0
virtual Extractor & operator>> (int64_t &v)=0
virtual Extractor & operator>> (float &v)=0
virtual Extractor & operator>> (double &v)=0
Protected Attributes
const char * m_eback
Start of the buffer (name from std::streambuf)
const char * m_egptr
End of the buffer.
const char * m_gptr
Current get position.
Detailed Description
Buffer wrapper for input of binary data from a buffer.
Definition at line 46 of file Extractor.hpp.
Constructor & Destructor Documentation
pdal::Extractor::Extractor (const char * buf, std::size_t size)
Construct an extractor to operate on a buffer.
Parameters
buf Buffer to extract from.
size Buffer size.
Definition at line 55 of file Extractor.hpp.
Member Function Documentation
void pdal::Extractor::get (std::string & s, size_t size)
Extract a string of a particular size from the buffer. Trim trailing null bytes.
Parameters
s String to extract to.
size Number of bytes to extract from buffer into string.
Definition at line 108 of file Extractor.hpp.
References pdal::Dimension::size().
Referenced by pdal::ExtraBytesIf::readFrom().
void pdal::Extractor::get (std::vector< char > & buf)
Extract data to char vector. Vector must be sized to indicate number of bytes to extract.
Parameters
buf Vector to which bytes should be extracted.
Definition at line 131 of file Extractor.hpp.
void pdal::Extractor::get (std::vector< unsigned char > & buf)
Extract data to unsigned char vector. Vector must be sized to indicate number of bytes to extract.
Parameters
buf Vector to which bytes should be extracted.
Definition at line 143 of file Extractor.hpp.
void pdal::Extractor::get (char * buf, size_t size)
Extract data into a provided buffer.
Parameters
buf Pointer to buffer to which bytes should be extracted.
size Number of bytes to extract.
Definition at line 155 of file Extractor.hpp.
References pdal::Dimension::size().
void pdal::Extractor::get (unsigned char * buf, size_t size)
Extract data into a provided unsigned buffer.
Parameters
buf Pointer to buffer to which bytes should be extracted.
size Number of bytes to extract.
Definition at line 167 of file Extractor.hpp.
References pdal::operator>>(), and pdal::Dimension::size().
bool pdal::Extractor::good () const
Determine whether the extractor is good (the get pointer is in the buffer).
Returns
Whether the get pointer is valid.
Definition at line 98 of file Extractor.hpp.
Referenced by pdal::OptechReader::read().
pdal::Extractor::operator bool ()
Determine if the buffer is good.
Returns
Whether the buffer is good.
Definition at line 65 of file Extractor.hpp.
virtual Extractor& pdal::Extractor::operator>> (uint8_t & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
virtual Extractor& pdal::Extractor::operator>> (int8_t & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
virtual Extractor& pdal::Extractor::operator>> (uint16_t & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
virtual Extractor& pdal::Extractor::operator>> (int16_t & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
virtual Extractor& pdal::Extractor::operator>> (uint32_t & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
virtual Extractor& pdal::Extractor::operator>> (int32_t & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
virtual Extractor& pdal::Extractor::operator>> (uint64_t & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
virtual Extractor& pdal::Extractor::operator>> (int64_t & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
virtual Extractor& pdal::Extractor::operator>> (float & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
virtual Extractor& pdal::Extractor::operator>> (double & v) pure virtual
Implemented in pdal::SwitchableExtractor, pdal::BeExtractor, and pdal::LeExtractor.
size_t pdal::Extractor::position () const
Return the get position of buffer.
Returns
Get position.
Definition at line 89 of file Extractor.hpp.
void pdal::Extractor::seek (std::size_t pos)
Seek to a position in the buffer.
Parameters
pos Position to seek in buffer.
Definition at line 73 of file Extractor.hpp.
void pdal::Extractor::skip (std::size_t cnt)
Advance buffer position.
Parameters
cnt Number of bytes to skip in buffer.
Definition at line 81 of file Extractor.hpp.
Referenced by pdal::LasReader::loadExtraDims().
Member Data Documentation
const char* pdal::Extractor::m_eback protected
Start of the buffer (name from std::streambuf)
Definition at line 185 of file Extractor.hpp.
const char* pdal::Extractor::m_egptr protected
End of the buffer.
Definition at line 186 of file Extractor.hpp.
const char* pdal::Extractor::m_gptr protected
Current get position.
Definition at line 187 of file Extractor.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/util/Extractor.hpp