PDAL: pcl::Pipeline< PointT > Class Template Reference
pcl::Pipeline< PointT > Class Template Reference
Pipeline composes a linear series of PCL operations to be applied to the source point cloud.
#include <PCLPipeline.h>
Public Types
typedef std::shared_ptr< Pipeline< PointT > > Ptr
typedef std::shared_ptr< const Pipeline< PointT > > ConstPtr
Public Member Functions
Pipeline ()
Constructor.
void setFilename (const std::string &filename)
Provide the name of the JSON file describing the PCL pipeline.
void setMethods (const std::string &methods)
Provide the PCL pipeline as a JSON string.
void setOffsets (const double x, const double y, const double z)
Set the offsets to the data in the x, y, and z dimension.
Protected Types
typedef Filter< PointT >::PointCloud PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef pcl::traits::fieldList< PointT >::type FieldList
Protected Member Functions
void applyFilter (PointCloud &output)
Filtered results are stored in a separate point cloud.
void applyPassThrough (PointCloudConstPtr cloud, PointCloud &output, Json::Value const &vt)
Apply passthrough filter to input cloud, using parameters specified in property tree.
void applyStatisticalOutlierRemoval (PointCloudConstPtr cloud, PointCloud &output, Json::Value const &vt)
Apply statistical outlier removal filter to input cloud, using parameters specified in property tree.
void applyRadiusOutlierRemoval (PointCloudConstPtr cloud, PointCloud &output, Json::Value const &vt)
Apply radius outlier removal filter to input cloud, using parameters specified in property tree.
void applyVoxelGrid (PointCloudConstPtr cloud, PointCloud &output, Json::Value const &vt)
Apply voxel grid filter to input cloud, using parameters specified in property tree.
void applyGridMinimum (PointCloudConstPtr cloud, PointCloud &output, Json::Value const &vt)
Apply grid minimum filter to input cloud, using parameters specified in property tree.
void applyApproximateProgressiveMorphologicalFilter (PointCloudConstPtr cloud, PointCloud &output, Json::Value const &vt)
Apply approximate progressive morphological filter to input cloud, using parameters specified in property tree.
void applyProgressiveMorphologicalFilter (PointCloudConstPtr cloud, PointCloud &output, Json::Value const &vt)
Apply progressive morphological filter to input cloud, using parameters specified in property tree.
Private Attributes
bool filename_set_
bool json_set_
Json::Value pt_
double x_offset_
The offsets to the data in the x, y, and z dimension.
double y_offset_
double z_offset_
Detailed Description
template<typename PointT>
class pcl::Pipeline< PointT >
Pipeline composes a linear series of PCL operations to be applied to the source point cloud.
TBD
Usage example:
pcl::Pipeline<PointType> pipeline (true); // Initializing with true will allow us to extract the removed indices
pipeline.setInputCloud (cloud_in);
pipeline.setFilename (filename);
pipeline.filter (*cloud_out);
Author
Bradley J Chambers
Definition at line 73 of file PCLPipeline.h.
Member Typedef Documentation
template<typename PointT> typedef std::shared_ptr< const Pipeline<PointT> > pcl::Pipeline< PointT >::ConstPtr
Definition at line 84 of file PCLPipeline.h.
template<typename PointT> typedef pcl::traits::fieldList<PointT>::type pcl::Pipeline< PointT >::FieldList protected
Definition at line 79 of file PCLPipeline.h.
template<typename PointT> typedef Filter<PointT>::PointCloud pcl::Pipeline< PointT >::PointCloud protected
Definition at line 76 of file PCLPipeline.h.
template<typename PointT> typedef PointCloud::ConstPtr pcl::Pipeline< PointT >::PointCloudConstPtr protected
Definition at line 78 of file PCLPipeline.h.
template<typename PointT> typedef PointCloud::Ptr pcl::Pipeline< PointT >::PointCloudPtr protected
Definition at line 77 of file PCLPipeline.h.
template<typename PointT> typedef std::shared_ptr< Pipeline<PointT> > pcl::Pipeline< PointT >::Ptr
Definition at line 83 of file PCLPipeline.h.
Constructor & Destructor Documentation
template<typename PointT> pcl::Pipeline< PointT >::Pipeline ()
Constructor.
Parameters
[in] extract_removed_indices Set to true if you want to be able to extract the indices of points being removed (default = false).
Definition at line 90 of file PCLPipeline.h.
References pcl::Pipeline< PointT >::filename_set_, and pcl::Pipeline< PointT >::json_set_.
Member Function Documentation
template<typename PointT > void pcl::Pipeline< PointT >::applyApproximateProgressiveMorphologicalFilter (PointCloudConstPtr cloud, PointCloud & output, Json::Value const & vt) protected
Apply approximate progressive morphological filter to input cloud, using parameters specified in property tree.
Parameters
[in] cloud The input point cloud.
[out] output The resultant point cloud.
[in] value_type The parameters.
Definition at line 223 of file PCLPipeline.hpp.
References b, c, and pdal::Utils::extract().
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT > void pcl::Pipeline< PointT >::applyFilter (PointCloud & output) protected
Filtered results are stored in a separate point cloud.
Parameters
[out] output The resultant point cloud.
Definition at line 323 of file PCLPipeline.hpp.
References pdal::Utils::iequals(), and pdal::Dimension::name().
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT > void pcl::Pipeline< PointT >::applyGridMinimum (PointCloudConstPtr cloud, PointCloud & output, Json::Value const & vt) protected
Apply grid minimum filter to input cloud, using parameters specified in property tree.
Parameters
[in] cloud The input point cloud.
[out] output The resultant point cloud.
[in] value_type The parameters.
Definition at line 203 of file PCLPipeline.hpp.
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT > void pcl::Pipeline< PointT >::applyPassThrough (PointCloudConstPtr cloud, PointCloud & output, Json::Value const & vt) protected
Apply passthrough filter to input cloud, using parameters specified in property tree.
Parameters
[in] cloud The input point cloud.
[out] output The resultant point cloud.
[in] value_type The parameters.
Definition at line 72 of file PCLPipeline.hpp.
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT > void pcl::Pipeline< PointT >::applyProgressiveMorphologicalFilter (PointCloudConstPtr cloud, PointCloud & output, Json::Value const & vt) protected
Apply progressive morphological filter to input cloud, using parameters specified in property tree.
Parameters
[in] cloud The input point cloud.
[out] output The resultant point cloud.
[in] value_type The parameters.
Definition at line 273 of file PCLPipeline.hpp.
References b, c, and pdal::Utils::extract().
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT > void pcl::Pipeline< PointT >::applyRadiusOutlierRemoval (PointCloudConstPtr cloud, PointCloud & output, Json::Value const & vt) protected
Apply radius outlier removal filter to input cloud, using parameters specified in property tree.
Parameters
[in] cloud The input point cloud.
[out] output The resultant point cloud.
[in] value_type The parameters.
Definition at line 154 of file PCLPipeline.hpp.
References anonymous_namespace{GreyhoundReaderTest.cpp}::radius.
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT > void pcl::Pipeline< PointT >::applyStatisticalOutlierRemoval (PointCloudConstPtr cloud, PointCloud & output, Json::Value const & vt) protected
Apply statistical outlier removal filter to input cloud, using parameters specified in property tree.
Parameters
[in] cloud The input point cloud.
[out] output The resultant point cloud.
[in] value_type The parameters.
Definition at line 128 of file PCLPipeline.hpp.
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT > void pcl::Pipeline< PointT >::applyVoxelGrid (PointCloudConstPtr cloud, PointCloud & output, Json::Value const & vt) protected
Apply voxel grid filter to input cloud, using parameters specified in property tree.
Parameters
[in] cloud The input point cloud.
[out] output The resultant point cloud.
[in] value_type The parameters.
Definition at line 180 of file PCLPipeline.hpp.
References z.
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT> void pcl::Pipeline< PointT >::setFilename (const std::string & filename)
Provide the name of the JSON file describing the PCL pipeline.
Parameters
[in] filename the name of the JSON file describing the PCL pipeline
Definition at line 101 of file PCLPipeline.h.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pcl::Pipeline< PointT >::filename_set_, pcl::Pipeline< PointT >::json_set_, and pcl::Pipeline< PointT >::pt_.
Referenced by pdal::PCLBlock::run().
template<typename PointT> void pcl::Pipeline< PointT >::setMethods (const std::string & methods)
Provide the PCL pipeline as a JSON string.
Parameters
[in] methods the PCL JSON pipeline as a string.
Definition at line 120 of file PCLPipeline.h.
References pcl::Pipeline< PointT >::filename_set_, pcl::Pipeline< PointT >::json_set_, and pcl::Pipeline< PointT >::pt_.
Referenced by pdal::PCLBlock::run().
template<typename PointT> void pcl::Pipeline< PointT >::setOffsets (const double x, const double y, const double z)
Set the offsets to the data in the x, y, and z dimension.
Parameters
[in] x the x offset
[in] y the y offset
[in] z the z offset
Definition at line 141 of file PCLPipeline.h.
References pcl::Pipeline< PointT >::applyApproximateProgressiveMorphologicalFilter(), pcl::Pipeline< PointT >::applyFilter(), pcl::Pipeline< PointT >::applyGridMinimum(), pcl::Pipeline< PointT >::applyPassThrough(), pcl::Pipeline< PointT >::applyProgressiveMorphologicalFilter(), pcl::Pipeline< PointT >::applyRadiusOutlierRemoval(), pcl::Pipeline< PointT >::applyStatisticalOutlierRemoval(), pcl::Pipeline< PointT >::applyVoxelGrid(), pcl::Pipeline< PointT >::x_offset_, pcl::Pipeline< PointT >::y_offset_, z, and pcl::Pipeline< PointT >::z_offset_.
Referenced by pdal::PCLBlock::run().
Member Data Documentation
template<typename PointT> bool pcl::Pipeline< PointT >::filename_set_ private
Definition at line 217 of file PCLPipeline.h.
Referenced by pcl::Pipeline< PointT >::Pipeline(), pcl::Pipeline< PointT >::setFilename(), and pcl::Pipeline< PointT >::setMethods().
template<typename PointT> bool pcl::Pipeline< PointT >::json_set_ private
Definition at line 217 of file PCLPipeline.h.
Referenced by pcl::Pipeline< PointT >::Pipeline(), pcl::Pipeline< PointT >::setFilename(), and pcl::Pipeline< PointT >::setMethods().
template<typename PointT> Json::Value pcl::Pipeline< PointT >::pt_ private
Definition at line 219 of file PCLPipeline.h.
Referenced by pcl::Pipeline< PointT >::setFilename(), and pcl::Pipeline< PointT >::setMethods().
template<typename PointT> double pcl::Pipeline< PointT >::x_offset_ private
The offsets to the data in the x, y, and z dimension.
Definition at line 222 of file PCLPipeline.h.
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT> double pcl::Pipeline< PointT >::y_offset_ private
Definition at line 222 of file PCLPipeline.h.
Referenced by pcl::Pipeline< PointT >::setOffsets().
template<typename PointT> double pcl::Pipeline< PointT >::z_offset_ private
Definition at line 222 of file PCLPipeline.h.
Referenced by pcl::Pipeline< PointT >::setOffsets().
The documentation for this class was generated from the following files:
pdal/plugins/pcl/pipeline/PCLPipeline.h
pdal/plugins/pcl/pipeline/PCLPipeline.hpp