PDAL: pdal::Option Class Reference
pdal::Option Class Reference
#include <Options.hpp>
Private Attributes
Private attributes
std::string m_name
std::string m_value
Constructors
Option ()
template<typename T >
Option (std::string const &name, const T &value)
Primary constructor.
Option (std::string const &name, const std::string &value)
Option (std::string const &name, const bool &value)
std::string const & getName () const
std::string toArg () const
std::string getValue () const
bool empty () const
void toMetadata (MetadataNode &parent) const
static std::string::size_type parse (const std::string &name, std::string::size_type p)
static bool nameValid (const std::string &name, bool reportError)
Detailed Description
Definition at line 51 of file Options.hpp.
Constructor & Destructor Documentation
pdal::Option::Option ()
Definition at line 57 of file Options.hpp.
template<typename T > pdal::Option::Option (std::string const & name, const T & value)
Primary constructor.
Definition at line 62 of file Options.hpp.
pdal::Option::Option (std::string const & name, const std::string & value)
Definition at line 69 of file Options.hpp.
pdal::Option::Option (std::string const & name, const bool & value)
Definition at line 73 of file Options.hpp.
Member Function Documentation
bool pdal::Option::empty () const
std::string const& pdal::Option::getName () const
Returns
the name for the Option instance
Definition at line 80 of file Options.hpp.
Referenced by pdal::Options::add(), pdal::Options::addConditional(), pdal::Options::remove(), pdal::TEST(), toArg(), and toMetadata().
std::string pdal::Option::getValue () const
Returns
the value of the Option.
Definition at line 108 of file Options.hpp.
References pdal::Utils::toMetadata().
Referenced by pdal::TEST(), toArg(), and toMetadata().
bool pdal::Option::nameValid (const std::string & name, bool reportError) static
Definition at line 64 of file Options.cpp.
References parse(), and pdal::Utils::printError().
Referenced by pdal::Options::add(), pdal::Options::addConditional(), and pdal::TEST().
static std::string::size_type pdal::Option::parse (const std::string & name, std::string::size_type p) static
Definition at line 86 of file Options.hpp.
References c, pdal::Utils::extract(), and pdal::Dimension::name().
Referenced by pdal::Options::fromCmdlineFile(), nameValid(), and pdal::Kernel::parseStageOption().
std::string pdal::Option::toArg () const
Definition at line 47 of file Options.cpp.
References getName(), and getValue().
Referenced by pdal::Options::toCommandLine().
void pdal::Option::toMetadata (MetadataNode & parent) const
Definition at line 53 of file Options.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addWithType(), getName(), getValue(), and pdal::Utils::iequals().
Member Data Documentation
std::string pdal::Option::m_name private
Definition at line 117 of file Options.hpp.
std::string pdal::Option::m_value private
Definition at line 118 of file Options.hpp.
The documentation for this class was generated from the following files:
pdal/pdal/Options.hpp
pdal/pdal/Options.cpp