PDAL: pdal::LasWriter Class Reference
pdal::LasWriter Class Reference
#include <LasWriter.hpp>
Public Member Functions
std::string getName () const
LasWriter ()
void setInput (Stage &input)
void setProgressFd (int fd)
QuickInfo preview ()
void prepare (PointTableRef table)
PointViewSet execute (PointTableRef table)
void execute (StreamPointTable &table)
void setSpatialReference (SpatialReference const &srs)
const SpatialReference & getSpatialReference () const
void setOptions (Options options)
void addConditionalOptions (const Options &opts)
void addAllArgs (ProgramArgs &args)
void addOptions (const Options &opts)
void removeOptions (const Options &opts)
void setLog (LogPtr &log)
virtual LogPtr log () const
void startLogging () const
void stopLogging () const
bool isDebug () const
void setTag (const std::string &tag)
virtual std::string tag () const
std::vector< Stage * > & getInputs ()
MetadataNode getMetadata () const
void serialize (MetadataNode root, PipelineWriter::TagMap &tags) const
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
static bool parseName (std::string o, std::string::size_type &pos)
static bool parseTagName (std::string o, std::string::size_type &pos)
Protected Member Functions
void prepOutput (std::ostream *out, const SpatialReference &srs)
void finishOutput ()
void validateFilename (PointTableRef table)
std::string::size_type handleFilenameTemplate (const std::string &filename)
void setSpatialReference (MetadataNode &m, SpatialReference const &)
void addSpatialReferenceArg (ProgramArgs &args)
void throwError (const std::string &s) const
point_count_t pointCount () const
point_count_t faceCount () const
void throwStreamingError () const
Protected Attributes
std::string m_filename
Scaling m_scaling
Options m_options
Stage's options.
MetadataNode m_metadata
Stage's metadata.
int m_progressFd
Descriptor for progress info.
Private Member Functions
virtual void addArgs (ProgramArgs &args)
virtual void initialize ()
virtual void prepared (PointTableRef table)
virtual void readyTable (PointTableRef table)
virtual void readyFile (const std::string &filename, const SpatialReference &srs)
virtual void writeView (const PointViewPtr view)
virtual bool processOne (PointRef &point)
void spatialReferenceChanged (const SpatialReference &srs)
virtual void doneFile ()
void handleLaszip (int result)
void fillForwardList ()
void addUserVlrs ()
template<typename T >
void handleHeaderForward (const std::string &s, T &headerVal, const MetadataNode &base)
void handleHeaderForwards (MetadataNode &forward)
void fillHeader ()
bool fillPointBuf (PointRef &point, LeInserter &ostream)
point_count_t fillWriteBuf (const PointView &view, PointId startId, std::vector< char > &buf)
bool writeLasZipBuf (PointRef &point)
void writeLazPerfBuf (char *data, size_t pointLen, point_count_t numPts)
void addForwardVlrs ()
Add VLRs forwarded from the input.
void addMetadataVlr (MetadataNode &forward)
void addPipelineVlr ()
void addExtraBytesVlr ()
void addSpatialRefVlrs ()
MetadataNode findVlrMetadata (MetadataNode node, uint16_t recordId, const std::string &userId)
void readyCompression ()
void readyLasZipCompression ()
void readyLazPerfCompression ()
void openCompression ()
void addVlr (const std::string &userId, uint16_t recordId, const std::string &description, std::vector< uint8_t > &data)
void deleteVlr (const std::string &userId, uint16_t recordId)
void addGeotiffVlrs ()
bool addWktVlr ()
void finishLasZipOutput ()
void finishLazPerfOutput ()
LasWriter & operator= (const LasWriter &)
LasWriter (const LasWriter &)
Private Attributes
LasHeader m_lasHeader
std::unique_ptr< LasSummaryData > m_summaryData
laszip_POINTER m_laszip
std::unique_ptr< LazPerfVlrCompressor > m_compressor
bool m_discardHighReturnNumbers
std::map< std::string, std::string > m_headerVals
std::vector< VlrOptionInfo > m_optionInfos
std::ostream * m_ostream
std::vector< LasVLR > m_vlrs
std::vector< ExtLasVLR > m_eVlrs
StringList m_extraDimSpec
std::vector< ExtraDim > m_extraDims
uint16_t m_extraByteLen
SpatialReference m_srs
std::string m_curFilename
StringList m_forwardSpec
std::set< std::string > m_forwards
bool m_forwardVlrs
LasCompression m_compression
std::vector< char > m_pointBuf
SpatialReference m_aSrs
int m_srsCnt
NumHeaderVal< uint8_t, 1, 1 > m_majorVersion
NumHeaderVal< uint8_t, 1, 4 > m_minorVersion
NumHeaderVal< uint8_t, 0, 10 > m_dataformatId
NumHeaderVal< uint16_t, 0, 65535 > m_filesourceId
NumHeaderVal< uint16_t, 0, 31 > m_globalEncoding
UuidHeaderVal m_projectId
StringHeaderVal< 32 > m_systemId
StringHeaderVal< 32 > m_softwareId
NumHeaderVal< uint16_t, 0, 366 > m_creationDoy
NumHeaderVal< uint16_t, 0, 65535 > m_creationYear
StringHeaderVal< 20 > m_scaleX
StringHeaderVal< 20 > m_scaleY
StringHeaderVal< 20 > m_scaleZ
StringHeaderVal< 20 > m_offsetX
StringHeaderVal< 20 > m_offsetY
StringHeaderVal< 20 > m_offsetZ
MetadataNode m_forwardMetadata
bool m_writePDALMetadata
Json::Value m_userVLRs
Friends
class LasTester
class NitfWriter
Detailed Description
Definition at line 75 of file LasWriter.hpp.
Constructor & Destructor Documentation
pdal::LasWriter::LasWriter ()
Definition at line 68 of file LasWriter.cpp.
References pdal::None.
pdal::LasWriter::LasWriter (const LasWriter &) private
Member Function Documentation
void pdal::Stage::addAllArgs (ProgramArgs & args) inherited
Add a stage's options to a ProgramArgs set.
Parameters
args ProgramArgs to add to.
Definition at line 84 of file Stage.cpp.
References pdal::Stage::addArgs(), pdal::Stage::getName(), pdal::Stage::l_addArgs(), and pdal::arg_error::m_error.
Referenced by pdal::Stage::handleOptions(), and App::outputOptions().
void pdal::LasWriter::addArgs (ProgramArgs &) private virtual
Add arguments(options) handled by this stage. Implement in subclass.
Parameters
args ProgramArgs object to which arguments should be added.
Reimplemented from pdal::Stage.
Reimplemented in pdal::NitfWriter.
Definition at line 73 of file LasWriter.cpp.
References pdal::ProgramArgs::add(), pdal::GetDefaultSoftwareId(), pdal::LasHeader::getSystemIdentifier(), m_aSrs, m_compression, m_creationDoy, m_creationYear, m_dataformatId, m_discardHighReturnNumbers, m_extraDimSpec, pdal::FlexWriter::m_filename, m_forwardSpec, m_globalEncoding, m_lasHeader, m_majorVersion, m_minorVersion, m_offsetX, m_offsetY, m_offsetZ, m_projectId, m_scaleX, m_scaleY, m_scaleZ, m_softwareId, m_systemId, m_userVLRs, m_writePDALMetadata, pdal::None, pdal::Arg::setPositional(), and conf::year.
Referenced by pdal::NitfWriter::addArgs().
void pdal::Stage::addConditionalOptions (const Options & opts) inherited
Add options if an option with the same name doesn't already exist on the stage.
Parameters
opts Options to add.
Definition at line 57 of file Stage.cpp.
References pdal::Options::addConditional(), pdal::Options::getOptions(), and pdal::Stage::m_options.
Referenced by pdal::TEST().
void pdal::LasWriter::addExtraBytesVlr () private
Definition at line 509 of file LasWriter.cpp.
References addVlr(), pdal::ExtraBytesIf::appendTo(), pdal::Dimension::description(), pdal::EXTRA_BYTES_RECORD_ID, m_extraDims, and pdal::SPEC_USER_ID.
Referenced by readyTable().
void pdal::LasWriter::addForwardVlrs () private
Add VLRs forwarded from the input.
Definition at line 418 of file LasWriter.cpp.
References addVlr(), pdal::Utils::base64_decode(), pdal::MetadataNode::findChild(), pdal::MetadataNode::findChildren(), m_forwardMetadata, m_forwardVlrs, pdal::Utils::startsWith(), pdal::MetadataNode::valid(), and pdal::MetadataNode::value().
Referenced by readyTable().
void pdal::LasWriter::addGeotiffVlrs () private
Definition at line 460 of file LasWriter.cpp.
References addVlr(), pdal::GeotiffTags::asciiData(), pdal::GeotiffTags::directoryData(), pdal::GeotiffTags::doublesData(), pdal::SpatialReference::empty(), pdal::GEOTIFF_ASCII_RECORD_ID, pdal::GEOTIFF_DIRECTORY_RECORD_ID, pdal::GEOTIFF_DOUBLES_RECORD_ID, m_srs, pdal::Stage::throwError(), and pdal::TRANSFORM_USER_ID.
Referenced by addSpatialRefVlrs().
void pdal::LasWriter::addMetadataVlr (MetadataNode & forward) private
Definition at line 383 of file LasWriter.cpp.
References addVlr(), pdal::Debug, pdal::Stage::log(), m_lasHeader, pdal::LasVLR::MAX_DATA_SIZE, pdal::PDAL_METADATA_RECORD_ID, pdal::PDAL_USER_ID, pdal::Utils::toJSON(), and pdal::LasHeader::versionAtLeast().
Referenced by readyTable().
void pdal::Stage::addOptions (const Options & opts) inherited
Add options to the existing option set.
Parameters
opts Options to add.
Definition at line 195 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions(), and TEST().
void pdal::LasWriter::addPipelineVlr () private
Definition at line 398 of file LasWriter.cpp.
References addVlr(), pdal::Debug, pdal::Stage::log(), m_lasHeader, pdal::LasVLR::MAX_DATA_SIZE, pdal::PDAL_PIPELINE_RECORD_ID, pdal::PDAL_USER_ID, pdal::LasHeader::versionAtLeast(), and pdal::PipelineWriter::writePipeline().
Referenced by readyTable().
void pdal::Stage::addSpatialReferenceArg (ProgramArgs & args) protected inherited
Definition at line 468 of file Stage.cpp.
References pdal::ProgramArgs::add(), and pdal::Stage::m_spatialReference.
Referenced by pdal::OciReader::addArgs(), and pdal::PgReader::addArgs().
void pdal::LasWriter::addSpatialRefVlrs () private
Set VLRs from the active spatial reference.
Parameters
srs - Active spatial reference.
Definition at line 444 of file LasWriter.cpp.
References addGeotiffVlrs(), addWktVlr(), deleteVlr(), pdal::GEOTIFF_ASCII_RECORD_ID, pdal::GEOTIFF_DIRECTORY_RECORD_ID, pdal::GEOTIFF_DOUBLES_RECORD_ID, pdal::LIBLAS_USER_ID, m_lasHeader, pdal::TRANSFORM_USER_ID, pdal::LasHeader::versionAtLeast(), and pdal::WKT_RECORD_ID.
Referenced by prepOutput().
void pdal::LasWriter::addUserVlrs () private
Definition at line 200 of file LasWriter.cpp.
References addVlr(), pdal::Utils::base64_decode(), pdal::Dimension::description(), m_userVLRs, and user.
Referenced by readyTable().
void pdal::LasWriter::addVlr (const std::string & userId, uint16_t recordId, const std::string & description, std::vector< uint8_t > & data) private
Add a standard or variable-length VLR depending on the data size.
Parameters
userId - VLR user ID
recordId - VLR record ID
description - VLR description
data - Raw VLR data
Definition at line 531 of file LasWriter.cpp.
References m_eVlrs, m_lasHeader, m_vlrs, pdal::LasVLR::MAX_DATA_SIZE, pdal::Stage::throwError(), and pdal::LasHeader::versionAtLeast().
Referenced by addExtraBytesVlr(), addForwardVlrs(), addGeotiffVlrs(), addMetadataVlr(), addPipelineVlr(), addUserVlrs(), pdal::LasTester::addVlr(), addWktVlr(), readyLasZipCompression(), and readyLazPerfCompression().
bool pdal::LasWriter::addWktVlr () private
Add a Well-known Text VLR associated with the spatial reference.
Returns
Whether the VLR was added.
Definition at line 488 of file LasWriter.cpp.
References addVlr(), pdal::SpatialReference::getWKT(), pdal::LIBLAS_USER_ID, m_srs, pdal::TRANSFORM_USER_ID, and pdal::WKT_RECORD_ID.
Referenced by addSpatialRefVlrs().
static void* pdal::LasWriter::create () static
void pdal::LasWriter::deleteVlr (const std::string & userId, uint16_t recordId) private
Delete a VLR from the vlr list.
Definition at line 555 of file LasWriter.cpp.
References m_eVlrs, m_vlrs, and pdal::Utils::remove_if().
Referenced by addSpatialRefVlrs(), and readyCompression().
static int32_t pdal::LasWriter::destroy (void *) static
void pdal::LasWriter::doneFile () private virtual
Reimplemented from pdal::FlexWriter.
Reimplemented in pdal::NitfWriter.
Definition at line 1075 of file LasWriter.cpp.
References pdal::MetadataNode::addList(), finishOutput(), pdal::Stage::getMetadata(), m_curFilename, m_ostream, pdal::Stage::m_progressFd, and pdal::Utils::writeProgress().
PointViewSet pdal::Stage::execute (PointTableRef table) inherited
Execute a prepared pipeline (linked set of stages).
This performs the action associated with the stage by executing the run function of each stage in depth first order. Each stage is run to completion (all points are processed) before the next stages is run.o
Parameters
table Point table being used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 156 of file Stage.cpp.
References pdal::BasePointTable::addSpatialReference(), pdal::BasePointTable::clearSpatialReferences(), pdal::SpatialReference::empty(), pdal::Stage::execute(), pdal::BasePointTable::finalize(), pdal::Stage::getSpatialReference(), pdal::Stage::l_done(), pdal::Stage::m_faceCount, pdal::Stage::m_inputs, pdal::Stage::m_pointCount, pdal::Stage::ready(), pdal::Stage::StageRunner, pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::execute(), pdal::Stage::execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
void pdal::Stage::execute (StreamPointTable & table) inherited
Execute a prepared pipeline (linked set of stages) in streaming mode.
This performs the action associated with the stage by executing the processOne function of each stage in depth first order. Points are processed up to the capacity of the provided StreamPointTable. Not all stages support streaming mode and an exception will be thrown when attempting to execute an unsupported stage.
Streaming points can reduce memory consumption, but may limit access to algorithms that need to operate on full point sets.
Parameters
table Streming point table used for stage pipeline. This must be the same table used in the prepare function.
Definition at line 239 of file Stage.cpp.
References pdal::Stage::done(), pdal::SpatialReference::empty(), pdal::Stage::execute(), pdal::StreamPointTable::finalize(), pdal::Stage::m_inputs, pdal::entwine::operator-(), pdal::Stage::ready(), and pdal::BasePointTable::setSpatialReference().
point_count_t pdal::Stage::faceCount () const protected inherited
Return the count of faces in all primary meshes for all point views. Only valid during execute().
Returns
Total number of faces in all point views being executed.
Definition at line 336 of file Stage.hpp.
Referenced by pdal::PlyWriter::writeHeader().
void pdal::LasWriter::fillForwardList () private
Definition at line 232 of file LasWriter.cpp.
References pdal::Utils::contains(), m_forwards, m_forwardSpec, m_forwardVlrs, pdal::Dimension::name(), and pdal::Stage::throwError().
Referenced by initialize().
void pdal::LasWriter::fillHeader () private
Fill the LAS header with values as provided in options or forwarded metadata.
Definition at line 611 of file LasWriter.cpp.
References pdal::LasHeader::basePointLen(), m_creationDoy, m_creationYear, m_dataformatId, m_eVlrs, m_extraByteLen, m_filesourceId, m_globalEncoding, m_lasHeader, m_minorVersion, m_projectId, pdal::FlexWriter::m_scaling, m_softwareId, m_systemId, m_vlrs, pdal::LasHeader::pointFormat(), pdal::LasHeader::pointFormatSupported(), pdal::LasHeader::setCreationDOY(), pdal::LasHeader::setCreationYear(), pdal::LasHeader::setEVlrCount(), pdal::LasHeader::setFileSourceId(), pdal::LasHeader::setGlobalEncoding(), pdal::LasHeader::setPointFormat(), pdal::LasHeader::setPointLen(), pdal::LasHeader::setProjectId(), pdal::LasHeader::setScaling(), pdal::LasHeader::setSoftwareId(), pdal::LasHeader::setSystemId(), pdal::LasHeader::setVersionMinor(), pdal::LasHeader::setVlrCount(), pdal::Stage::throwError(), pdal::Utils::toString(), pdal::NumHeaderVal< T, MIN, MAX >::val(), pdal::StringHeaderVal< LEN >::val(), pdal::UuidHeaderVal::val(), and pdal::LasHeader::versionAtLeast().
Referenced by prepared(), and prepOutput().
bool pdal::LasWriter::fillPointBuf (PointRef & point, LeInserter & ostream) private
Definition at line 940 of file LasWriter.cpp.
References Blue, pdal::PointRef::getField(), pdal::PointRef::getFieldAs(), GpsTime, Green, pdal::LasHeader::has14Format(), pdal::LasHeader::hasColor(), pdal::PointRef::hasDim(), pdal::LasHeader::hasInfrared(), pdal::LasHeader::hasTime(), pdal::Utils::insertDim(), Intensity, m_curFilename, m_discardHighReturnNumbers, m_extraDims, m_lasHeader, pdal::FlexWriter::m_scaling, m_summaryData, pdal::Scaling::m_xXform, pdal::Scaling::m_yXform, pdal::Scaling::m_zXform, pdal::LasHeader::maxReturnCount(), pdal::Dimension::name(), pdal::Utils::numericCast(), Red, pdal::Stage::throwError(), pdal::XForm::toScaled(), pdal::Utils::toString(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by fillWriteBuf(), and processOne().
point_count_t pdal::LasWriter::fillWriteBuf (const PointView & view, PointId startId, std::vector< char > & buf) private
Definition at line 1057 of file LasWriter.cpp.
References fillPointBuf(), m_lasHeader, pdal::LasHeader::pointLen(), pdal::PointRef::setPointId(), and pdal::PointView::size().
Referenced by writeView().
MetadataNode pdal::LasWriter::findVlrMetadata (MetadataNode node, uint16_t recordId, const std::string & userId) private
Search for metadata associated with the provided recordId and userId.
Parameters
node - Top-level node to use for metadata search.
recordId - Record ID to match.
userId - User ID to match.
Definition at line 356 of file LasWriter.cpp.
References pdal::MetadataNode::find(), and pdal::Utils::startsWith().
void pdal::LasWriter::finishLasZipOutput () private
Definition at line 1133 of file LasWriter.cpp.
References handleLaszip(), and m_laszip.
Referenced by finishOutput().
void pdal::LasWriter::finishLazPerfOutput () private
Definition at line 1142 of file LasWriter.cpp.
References m_compressor.
Referenced by finishOutput().
void pdal::LasWriter::finishOutput () protected
Definition at line 1085 of file LasWriter.cpp.
References pdal::Debug, finishLasZipOutput(), finishLazPerfOutput(), pdal::LasZip, pdal::LazPerf, pdal::Stage::log(), m_compression, m_eVlrs, m_lasHeader, m_ostream, pdal::FlexWriter::m_scaling, m_summaryData, pdal::OStream::seek(), pdal::LasHeader::setScaling(), pdal::LasHeader::setSummary(), and pdal::Stage::throwError().
Referenced by pdal::NitfWriter::doneFile(), and doneFile().
std::vector<Stage*>& pdal::Stage::getInputs () inherited
Return a list of the stage's inputs.
Returns
A vector pointers to input stages.
Definition at line 272 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTags(), pdal::PipelineManager::leaves(), pdal::PipelineManager::replace(), and TEST().
MetadataNode pdal::Stage::getMetadata () const inherited
Get the stage's metadata node.
Returns
Stage's metadata.
Definition at line 280 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{CpdFilter.cpp}::addMetadata(), pdal::CpdFilter::change(), pdal::CpdFilter::cpd_affine(), pdal::CpdFilter::cpd_rigid(), pdal::SbetWriter::done(), pdal::MatlabWriter::done(), pdal::PcdWriter::done(), pdal::PlyWriter::done(), pdal::MbReader::done(), pdal::MrsidReader::done(), pdal::MatlabReader::done(), pdal::GDALWriter::doneFile(), pdal::BpfWriter::doneFile(), doneFile(), pdal::InfoKernel::dump(), pdal::IcpFilter::icp(), pdal::PythonFilter::run(), and TEST().
std::string pdal::LasWriter::getName () const virtual
Return the name of a stage.
Returns
The stage's name.
Implements pdal::Stage.
Reimplemented in pdal::NitfWriter.
Definition at line 66 of file LasWriter.cpp.
References pdal::PluginInfo::name.
Referenced by prepared(), and spatialReferenceChanged().
const SpatialReference & pdal::Stage::getSpatialReference () const inherited
Get the spatial reference of the stage.
Get the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Returns
The stage's spatial reference.
Definition at line 474 of file Stage.cpp.
References pdal::Stage::m_spatialReference.
Referenced by pdal::Stage::execute(), pdal::PgReader::initialize(), pdal::BpfReader::inspect(), prepOutput(), pdal::MergeFilter::ready(), pdal::MergeFilter::run(), and TEST().
std::string::size_type pdal::Writer::handleFilenameTemplate (const std::string & filename) protected inherited
Locate template placeholder ('#') and validate filename with respect to placeholder.
Definition at line 47 of file Writer.cpp.
References pdal::Stage::getName().
template<typename T > void pdal::LasWriter::handleHeaderForward (const std::string & s, T & headerVal, const MetadataNode & base) private
Definition at line 568 of file LasWriter.cpp.
References pdal::Utils::contains(), pdal::MetadataNode::findChild(), m_forwards, pdal::Dimension::type(), pdal::MetadataNode::valid(), and pdal::MetadataNode::value().
Referenced by handleHeaderForwards().
void pdal::LasWriter::handleHeaderForwards (MetadataNode & forward) private
Definition at line 581 of file LasWriter.cpp.
References handleHeaderForward(), m_creationDoy, m_creationYear, m_dataformatId, m_filesourceId, m_globalEncoding, m_majorVersion, m_minorVersion, pdal::XForm::m_offset, m_offsetX, m_offsetY, m_offsetZ, m_projectId, pdal::XForm::m_scale, m_scaleX, m_scaleY, m_scaleZ, pdal::FlexWriter::m_scaling, m_softwareId, m_systemId, pdal::Scaling::m_xXform, pdal::Scaling::m_yXform, pdal::Scaling::m_zXform, pdal::XForm::XFormComponent::set(), and pdal::StringHeaderVal< LEN >::val().
Referenced by prepOutput().
void pdal::LasWriter::handleLaszip (int result) private
Definition at line 658 of file LasWriter.cpp.
References m_laszip, and pdal::Stage::throwError().
Referenced by finishLasZipOutput(), openCompression(), readyLasZipCompression(), and writeLasZipBuf().
void pdal::LasWriter::initialize () private virtual
Initialize stage after options have been processed. Implement in subclass.
Reimplemented from pdal::Stage.
Definition at line 121 of file LasWriter.cpp.
References pdal::SpatialReference::empty(), setup::ext, pdal::FileUtils::extension(), fillForwardList(), pdal::LasZip, m_aSrs, m_compression, m_extraDims, m_extraDimSpec, pdal::FlexWriter::m_filename, m_lasHeader, pdal::None, pdal::LasUtils::parse(), pdal::LasHeader::setCompressed(), pdal::Stage::setSpatialReference(), pdal::Stage::throwError(), and pdal::Utils::tolower().
bool pdal::Stage::isDebug () const inherited
Determine whether the stage is in debug mode or not.
Returns
The stage's debug state.
Definition at line 243 of file Stage.hpp.
References pdal::Debug.
Referenced by pdal::Stage::setupLog(), pdal::Stage::startLogging(), and pdal::OciWriter::wipeBlockTable().
virtual LogPtr pdal::Stage::log () const virtual inherited
Return the stage's log pointer.
Returns
Log pointer.
Definition at line 225 of file Stage.hpp.
Referenced by pdal::OciReader::addDimensions(), pdal::GeoWaveReader::addDimensions(), pdal::SQLiteReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), addMetadataVlr(), addPipelineVlr(), pdal::OciWriter::blockTableExists(), pdal::CpdFilter::change(), pdal::PgWriter::CheckPointCloudExists(), pdal::PgWriter::CheckPostGISExists(), pdal::PgWriter::CheckTableExists(), pdal::SQLiteWriter::CreateBlockTable(), pdal::SQLiteWriter::CreateCloud(), pdal::SQLiteWriter::CreateCloudTable(), pdal::SQLiteWriter::CreateIndexes(), pdal::GeoWaveWriter::createJvm(), pdal::GeoWaveReader::createJvm(), pdal::PgReader::CursorSetup(), pdal::PgReader::CursorTeardown(), pdal::SQLiteWriter::DeleteBlockTable(), pdal::SQLiteWriter::DeleteCloudTable(), pdal::PgReader::fetchPcid(), pdal::SQLiteReader::fetchSpatialReference(), pdal::PgReader::fetchSpatialReference(), pdal::TextReader::fillFields(), pdal::ComputeRangeFilter::filter(), pdal::RadialDensityFilter::filter(), pdal::KDistanceFilter::filter(), pdal::LOFFilter::filter(), pdal::ELMFilter::filter(), pdal::ColorinterpFilter::filter(), pdal::GreedyProjection::filter(), finishOutput(), pdal::PgReader::getDataQuery(), pdal::GeoWaveWriter::initialize(), pdal::SQLiteWriter::initialize(), pdal::GeoWaveReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), pdal::BpfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::MbReader::loadData(), pdal::PgReader::NextBuffer(), pdal::GreyhoundReader::prepared(), pdal::PMFFilter::prepared(), pdal::NormalFilter::prepared(), prepared(), pdal::PMFFilter::processGround(), pdal::MongusFilter::processGround(), pdal::TextReader::processOne(), pdal::GreyhoundReader::read(), pdal::SQLiteReader::read(), pdal::PtsReader::read(), pdal::PgReader::read(), pdal::GDALReader::readBandData(), pdal::SQLiteReader::readPatch(), pdal::GeoWaveReader::ready(), pdal::PythonFilter::ready(), pdal::CropFilter::ready(), pdal::SQLiteReader::ready(), pdal::ColorinterpFilter::ready(), pdal::ColorizationFilter::ready(), pdal::BpfWriter::readyFile(), pdal::GridProjectionFilter::run(), pdal::MovingLeastSquaresFilter::run(), pdal::IcpFilter::run(), pdal::CpdFilter::run(), pdal::VoxelGridFilter::run(), pdal::MergeFilter::run(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::SampleFilter::run(), pdal::PythonFilter::run(), pdal::IQRFilter::run(), pdal::MADFilter::run(), pdal::OutlierFilter::run(), pdal::MongusFilter::run(), spatialReferenceChanged(), pdal::GeoWaveWriter::write(), pdal::MatlabWriter::write(), pdal::OciWriter::writeInit(), pdal::SQLiteWriter::writeInit(), pdal::OciWriter::writeTile(), and pdal::SQLiteWriter::writeTile().
void pdal::LasWriter::openCompression () private
Prepare the compressor to write points.
Parameters
pointFormat - Formt of points we're writing.
Definition at line 715 of file LasWriter.cpp.
References handleLaszip(), m_laszip, and m_ostream.
Referenced by prepOutput().
LasWriter& pdal::LasWriter::operator= (const LasWriter &) private
bool pdal::Stage::parseName (std::string o, std::string::size_type & pos) static inherited
Parse a stage name from a string. Return the name and update the position in the input string to the end of the stage name.
Parameters
o Input string to parse.
pos Parsing start/end position.
Returns
Whether the parsed name is a valid stage name.
Definition at line 504 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::Kernel::parseStageOption().
bool pdal::Stage::parseTagName (std::string o, std::string::size_type & pos) static inherited
Parse a tag name from a string. Return the name and update the position in the input string to the end of the tag name.
Parameters
o Input string to parse.
pos Parsing start/end position.
tag Parsed tag name.
Returns
Whether the parsed name is a valid tag name.
Definition at line 518 of file Stage.cpp.
References c, and pdal::Utils::extract().
Referenced by pdal::PipelineReaderJSON::extractTag(), and pdal::Kernel::parseStageOption().
point_count_t pdal::Stage::pointCount () const protected inherited
Return the point count of all point views at the start of execution. Only valid during execute().
Returns
Total number of points in all point views being executed.
Definition at line 328 of file Stage.hpp.
Referenced by pdal::PlyWriter::ready(), and pdal::PlyWriter::writeHeader().
void pdal::Stage::prepare (PointTableRef table) inherited
Prepare a stage for execution. This function needs to be called on the terminal stage of a pipeline (linked set of stages) before execute can be called. Prepare recurses through all input stages.
Parameters
table PointTable being used for stage pipeline.
Definition at line 138 of file Stage.cpp.
References pdal::Stage::addDimensions(), pdal::Stage::handleOptions(), pdal::Stage::initialize(), pdal::Stage::l_initialize(), pdal::BasePointTable::layout(), pdal::Stage::m_args, pdal::Stage::m_inputs, pdal::Stage::prepare(), pdal::Stage::prepared(), pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineManager::executeStream(), getBytes(), pdal::TIndexKernel::getFileInfo(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), main(), pdal::TIndexKernel::mergeFile(), pdal::Stage::prepare(), pdal::PipelineManager::prepare(), pdal::TIndexReader::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), TEST(), anonymous_namespace{BufferTest.cpp}::TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), and pdal::MongusFilter::writeControl().
void pdal::LasWriter::prepared (PointTableRef) private virtual
Functions called after dimensions have been added. Implement in subclass.
Parameters
table PointTable associated with pipeline.
Reimplemented from pdal::Stage.
Definition at line 158 of file LasWriter.cpp.
References pdal::Utils::contains(), pdal::PointLayout::dimName(), pdal::PointLayout::dimTypes(), fillHeader(), pdal::PointLayout::findDim(), getName(), pdal::Info, pdal::Dimension::interpretationName(), pdal::BasePointTable::layout(), pdal::Stage::log(), m_extraByteLen, m_extraDims, m_lasHeader, pdal::Dimension::size(), pdal::Stage::throwError(), pdal::Dimension::Unknown, pdal::LasHeader::usedDims(), and pdal::FlexWriter::validateFilename().
void pdal::LasWriter::prepOutput (std::ostream * out, const SpatialReference & srs) protected
Definition at line 304 of file LasWriter.cpp.
References addSpatialRefVlrs(), pdal::LasHeader::compressed(), pdal::SpatialReference::empty(), fillHeader(), pdal::Stage::getSpatialReference(), handleHeaderForwards(), pdal::LasZip, m_compression, m_forwardMetadata, m_lasHeader, m_ostream, m_pointBuf, m_srs, m_summaryData, m_vlrs, openCompression(), readyCompression(), pdal::LasHeader::setVlrOffset(), and pdal::LasVLR::write().
Referenced by pdal::NitfWriter::readyFile(), and readyFile().
QuickInfo pdal::Stage::preview () inherited
Retrieve some basic point information without reading all data when possible. Usually implemented only by Readers.
Definition at line 127 of file Stage.cpp.
References pdal::Stage::handleOptions(), pdal::Stage::inspect(), pdal::Stage::m_args, pdal::Stage::startLogging(), and pdal::Stage::stopLogging().
Referenced by pdal::TIndexKernel::getFileInfo(), pdal::PipelineManager::preview(), pdal::InfoKernel::run(), and TEST().
bool pdal::LasWriter::processOne (PointRef &) private virtual
Process a single point (streaming mode). Implement in sublcass.
Parameters
point Point to process.
Returns
Readers return false when no more points are to be read. Filters return false if a point is to be filtered-out (not passed to subsequent stages).
Reimplemented from pdal::Stage.
Definition at line 723 of file LasWriter.cpp.
References fillPointBuf(), pdal::LasZip, pdal::LazPerf, m_compression, m_lasHeader, m_ostream, m_pointBuf, pdal::LasHeader::pointLen(), writeLasZipBuf(), and writeLazPerfBuf().
Referenced by writeView().
void pdal::LasWriter::readyCompression () private
Definition at line 648 of file LasWriter.cpp.
References deleteVlr(), pdal::LasZip, pdal::LASZIP_RECORD_ID, pdal::LASZIP_USER_ID, pdal::LazPerf, m_compression, readyLasZipCompression(), and readyLazPerfCompression().
Referenced by prepOutput().
void pdal::LasWriter::readyFile (const std::string & filename, const SpatialReference & srs) private virtual
Implements pdal::FlexWriter.
Reimplemented in pdal::NitfWriter.
Definition at line 292 of file LasWriter.cpp.
References pdal::Utils::createFile(), m_curFilename, pdal::Stage::m_progressFd, prepOutput(), pdal::Stage::throwError(), and pdal::Utils::writeProgress().
void pdal::LasWriter::readyLasZipCompression () private
Definition at line 671 of file LasWriter.cpp.
References addVlr(), handleLaszip(), pdal::LASZIP_RECORD_ID, pdal::LASZIP_USER_ID, m_lasHeader, m_laszip, pdal::LasHeader::pointFormat(), pdal::LasHeader::pointLen(), and pdal::Dimension::size().
Referenced by readyCompression().
void pdal::LasWriter::readyLazPerfCompression () private
Definition at line 690 of file LasWriter.cpp.
References addVlr(), pdal::LasHeader::hasColor(), pdal::LasHeader::hasTime(), pdal::LASZIP_RECORD_ID, pdal::LASZIP_USER_ID, m_compressor, m_lasHeader, m_ostream, pdal::Stage::throwError(), and pdal::LasHeader::versionAtLeast().
Referenced by readyCompression().
void pdal::LasWriter::readyTable (PointTableRef table) private virtual
Reimplemented from pdal::FlexWriter.
Definition at line 277 of file LasWriter.cpp.
References addExtraBytesVlr(), addForwardVlrs(), addMetadataVlr(), addPipelineVlr(), addUserVlrs(), m_forwardMetadata, m_writePDALMetadata, pdal::BasePointTable::metadata(), and pdal::BasePointTable::privateMetadata().
void pdal::Stage::removeOptions (const Options & opts) inherited
Remove options from a stage's option set.
Parameters
opts Options to remove.
Definition at line 206 of file Stage.hpp.
References pdal::Options::getOptions().
Referenced by pdal::PipelineManager::setOptions().
void pdal::Stage::serialize (MetadataNode root, PipelineWriter::TagMap & tags) const inherited
Serialize a stage by inserting apporpritate data into the provided MetadataNode. Used to dump a pipeline specification in a portable format.
Parameters
root Node to which a stages meatdata should be added.
tags Pipeline writer's current list of stage tags.
Definition at line 64 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), pdal::Stage::getName(), pdal::Stage::m_inputs, pdal::Stage::m_options, and pdal::Options::toMetadata().
Referenced by pdal::PipelineWriter::writePipeline().
void pdal::Stage::setInput (Stage & input) inherited
Add a stage to the input list of this stage.
Parameters
input Stage to use as input.
Definition at line 85 of file Stage.hpp.
Referenced by compareTextLasStreaming(), pdal::MergeKernel::execute(), pdal::TIndexReader::initialize(), main(), pdal::PipelineManager::makeFilter(), pdal::TIndexKernel::mergeFile(), pdal::PipelineReaderJSON::parsePipeline(), pdal::PipelineManager::replace(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::TransformationFilterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), pdal::TEST_F(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testOverlay(), and writeData().
void pdal::Stage::setLog (LogPtr & log) inherited
Set the stage's log.
Parameters
log Log pointer.
Definition at line 217 of file Stage.hpp.
References setup::log.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), and testOverlay().
void pdal::Stage::setOptions (Options options) inherited
Set a stage's options.
Set the options on a stage, clearing all previously set options.
Parameters
options Options to set.
Definition at line 172 of file Stage.hpp.
Referenced by Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), compareFiles(), compareTextLas(), compareTextLasStreaming(), anonymous_namespace{SortFilterTest.cpp}::doSort(), getBytes(), pdal::TIndexReader::initialize(), main(), anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::PipelineManager::setOptions(), pdal::TransformationFilterTest::SetUp(), pdal::MatlabWriterTest::SetUp(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_file_type_stream(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), testReadWrite(), and writeData().
void pdal::Stage::setProgressFd (int fd) inherited
Set a file descriptor to which progress information should be written.
Parameters
fd Progress file descriptor.
Definition at line 93 of file Stage.hpp.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), and pdal::PipelineManager::addWriter().
void pdal::Stage::setSpatialReference (SpatialReference const & srs) inherited
Set the spatial reference of a stage.
Set the spatial reference that will override that being carried by the PointView being processed. This is usually used when reprojecting data to a new spatial reference. The stage spatial reference will be carried by PointViews processes by this stage to subsequent stages.
Parameters
srs Spatial reference to set.
Definition at line 480 of file Stage.cpp.
References pdal::Stage::m_metadata.
Referenced by pdal::OciReader::initialize(), pdal::GreyhoundReader::initialize(), pdal::GDALReader::initialize(), pdal::MatlabReader::initialize(), pdal::SQLiteReader::initialize(), pdal::TIndexReader::initialize(), pdal::BpfReader::initialize(), pdal::Ilvis2Reader::initialize(), pdal::PgReader::initialize(), initialize(), pdal::OptechReader::OptechReader(), pdal::MyReader::ready(), and TEST().
void pdal::Stage::setSpatialReference (MetadataNode & m, SpatialReference const & spatialRef) protected inherited
Definition at line 486 of file Stage.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::empty(), pdal::MetadataNode::findChild(), pdal::SpatialReference::getWKT(), pdal::Stage::m_spatialReference, pdal::MetadataNode::name(), and pdal::SpatialReference::toMetadata().
void pdal::Stage::setTag (const std::string & tag) inherited
Set a specific tag name.
Definition at line 256 of file Stage.hpp.
Referenced by pdal::PipelineManager::makeFilter(), and pdal::PipelineManager::makeReader().
void pdal::LasWriter::spatialReferenceChanged (const SpatialReference & srs) private virtual
(Streaming mode) Notification that the points that will follow in processing are from a spatial reference different than the previous spatial reference.
Parameters
srs New spatial reference.
Reimplemented from pdal::Stage.
Definition at line 149 of file LasWriter.cpp.
References pdal::Error, getName(), pdal::Stage::log(), pdal::FlexWriter::m_filename, and m_srsCnt.
void pdal::Stage::startLogging () const inherited
Push the stage's leader into the log.
Definition at line 538 of file Stage.cpp.
References pdal::gdal::ErrorHandler::getGlobalErrorHandler(), pdal::Stage::isDebug(), pdal::Stage::m_log, pdal::Stage::m_logLeader, and pdal::gdal::ErrorHandler::set().
Referenced by pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::preview().
void pdal::Stage::stopLogging () const inherited
Pop the stage's leader from the log.
Definition at line 545 of file Stage.cpp.
References pdal::Stage::m_log.
Referenced by pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::preview().
virtual std::string pdal::Stage::tag () const virtual inherited
Return the tag name of a stage.
Returns
The tag name.
Definition at line 264 of file Stage.hpp.
Referenced by pdal::anonymous_namespace{PipelineWriter.cpp}::generateTag(), pdal::TranslateKernel::makeJSONPipeline(), and pdal::PipelineManager::stageOptions().
void pdal::Stage::throwError (const std::string & s) const protected inherited
Definition at line 532 of file Stage.cpp.
References pdal::Stage::getName().
Referenced by pdal::SQLiteReader::addDimensions(), pdal::MrsidReader::addDimensions(), pdal::TextReader::addDimensions(), pdal::MatlabReader::addDimensions(), pdal::PgReader::addDimensions(), pdal::PlyReader::addDimensions(), addGeotiffVlrs(), addVlr(), pdal::PgWriter::CheckTableExists(), pdal::OciWriter::createPCEntry(), pdal::ReprojectionFilter::createTransform(), pdal::MatlabWriter::done(), pdal::NitfWriter::doneFile(), pdal::GDALWriter::doneFile(), pdal::OGRWriter::doneFile(), pdal::BpfWriter::doneFile(), pdal::GDALWriter::expandGrid(), pdal::PlyReader::extractElement(), pdal::PlyReader::extractEnd(), pdal::PlyReader::extractFormat(), pdal::PlyReader::extractHeader(), pdal::PlyReader::extractMagic(), pdal::PlyReader::extractProperty(), pdal::PgReader::fetchPcid(), pdal::PgReader::fetchSpatialReference(), fillForwardList(), fillHeader(), fillPointBuf(), pdal::HAGFilter::filter(), pdal::EigenvaluesFilter::filter(), pdal::ApproximateCoplanarFilter::filter(), pdal::NormalFilter::filter(), finishOutput(), pdal::TIndexReader::getFields(), pdal::PgReader::getNumPoints(), pdal::PlyWriter::getType(), handleLaszip(), pdal::OciWriter::initialize(), pdal::SQLiteWriter::initialize(), pdal::OciReader::initialize(), pdal::GDALWriter::initialize(), pdal::TextReader::initialize(), pdal::ReprojectionFilter::initialize(), pdal::PtsReader::initialize(), pdal::RangeFilter::initialize(), pdal::MatlabReader::initialize(), pdal::OGRWriter::initialize(), pdal::FerryFilter::initialize(), pdal::SQLiteReader::initialize(), pdal::OptechReader::initialize(), pdal::DividerFilter::initialize(), pdal::TIndexReader::initialize(), pdal::QfitReader::initialize(), pdal::BpfWriter::initialize(), pdal::ColorizationFilter::initialize(), pdal::BpfReader::initialize(), pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), pdal::TerrasolidReader::initialize(), initialize(), pdal::FauxReader::initialize(), pdal::GreedyProjection::initialize(), pdal::GDALReader::inspect(), pdal::OciWriter::isGeographic(), pdal::BpfWriter::loadBpfDimensions(), pdal::MbReader::loadData(), pdal::SQLiteWriter::loadGeometryWKT(), pdal::OciWriter::loadSQLData(), pdal::NitfWriter::NitfWriter(), pdal::MatlabWriter::prepared(), pdal::GDALWriter::prepared(), pdal::PlyWriter::prepared(), pdal::ComputeRangeFilter::prepared(), pdal::HAGFilter::prepared(), pdal::GroupByFilter::prepared(), pdal::IQRFilter::prepared(), pdal::LocateFilter::prepared(), pdal::RangeFilter::prepared(), pdal::MADFilter::prepared(), pdal::OGRWriter::prepared(), pdal::FerryFilter::prepared(), pdal::SortFilter::prepared(), pdal::ColorinterpFilter::prepared(), prepared(), pdal::OGRWriter::processOne(), pdal::Ilvis2Reader::processOne(), pdal::MatlabReader::processOne(), pdal::QfitReader::read(), pdal::OciReader::readBlob(), pdal::PlyReader::readElement(), pdal::SQLiteReader::readPatch(), pdal::OciReader::readPointMajor(), pdal::MatlabWriter::ready(), pdal::PlyWriter::ready(), pdal::SbetReader::ready(), pdal::GDALReader::ready(), pdal::OptechReader::ready(), pdal::PtsReader::ready(), pdal::ColorinterpFilter::ready(), pdal::QfitReader::ready(), pdal::TextReader::ready(), pdal::MbReader::ready(), pdal::ColorizationFilter::ready(), pdal::Ilvis2Reader::ready(), pdal::OGRWriter::readyFile(), pdal::BpfWriter::readyFile(), readyFile(), readyLazPerfCompression(), pdal::GDALWriter::readyTable(), pdal::NitfWriter::reprojectBoxToDD(), pdal::PCLBlock::run(), pdal::MatlabFilter::run(), pdal::PgWriter::SetupSchema(), pdal::CropFilter::transform(), pdal::OciWriter::updatePCExtent(), pdal::OciReader::validateQuery(), pdal::SQLiteReader::validateQuery(), pdal::MatlabWriter::write(), writeLasZipBuf(), pdal::OciWriter::writePointMajor(), pdal::OciWriter::writeTile(), pdal::SQLiteWriter::writeTile(), and pdal::BpfWriter::writeView().
void pdal::Stage::throwStreamingError () const protected inherited
Definition at line 339 of file Stage.hpp.
Referenced by pdal::ColorinterpFilter::processOne().
void pdal::FlexWriter::validateFilename (PointTableRef table) protected inherited
Definition at line 52 of file FlexWriter.hpp.
References pdal::BasePointTable::supportsView().
Referenced by prepared().
bool pdal::LasWriter::writeLasZipBuf (PointRef & point) private
Definition at line 796 of file LasWriter.cpp.
References Blue, pdal::PointRef::getField(), pdal::PointRef::getFieldAs(), GpsTime, Green, handleLaszip(), pdal::LasHeader::has14Format(), pdal::LasHeader::hasColor(), pdal::PointRef::hasDim(), pdal::LasHeader::hasInfrared(), pdal::LasHeader::hasTime(), pdal::Utils::insertDim(), Intensity, m_curFilename, m_discardHighReturnNumbers, m_extraByteLen, m_extraDims, m_lasHeader, m_laszip, m_pointBuf, pdal::FlexWriter::m_scaling, m_summaryData, pdal::Scaling::m_xXform, pdal::Scaling::m_yXform, pdal::Scaling::m_zXform, pdal::LasHeader::maxReturnCount(), pdal::Dimension::name(), pdal::Utils::numericCast(), Red, pdal::Stage::throwError(), pdal::XForm::toScaled(), pdal::Utils::toString(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by processOne().
void pdal::LasWriter::writeLazPerfBuf (char * data, size_t pointLen, point_count_t numPts) private
Definition at line 927 of file LasWriter.cpp.
References m_compressor.
Referenced by processOne(), and writeView().
void pdal::LasWriter::writeView (const PointViewPtr view) private virtual
Implements pdal::FlexWriter.
Reimplemented in pdal::NitfWriter.
Definition at line 750 of file LasWriter.cpp.
References fillWriteBuf(), pdal::LasZip, pdal::LazPerf, m_compression, m_lasHeader, m_ostream, m_pointBuf, pdal::Stage::m_progressFd, pdal::FlexWriter::m_scaling, pdal::LasHeader::pointLen(), processOne(), pdal::Scaling::setAutoXForm(), pdal::PointRef::setPointId(), pdal::PointView::size(), writeLazPerfBuf(), and pdal::Utils::writeProgress().
Referenced by pdal::NitfWriter::writeView().
Friends And Related Function Documentation
friend class LasTester friend
Definition at line 77 of file LasWriter.hpp.
friend class NitfWriter friend
Definition at line 78 of file LasWriter.hpp.
Member Data Documentation
SpatialReference pdal::LasWriter::m_aSrs private
Definition at line 111 of file LasWriter.hpp.
Referenced by addArgs(), and initialize().
LasCompression pdal::LasWriter::m_compression private
Definition at line 109 of file LasWriter.hpp.
Referenced by addArgs(), finishOutput(), initialize(), prepOutput(), processOne(), readyCompression(), and writeView().
std::unique_ptr<LazPerfVlrCompressor> pdal::LasWriter::m_compressor private
Definition at line 94 of file LasWriter.hpp.
Referenced by finishLazPerfOutput(), readyLazPerfCompression(), and writeLazPerfBuf().
NumHeaderVal<uint16_t, 0, 366> pdal::LasWriter::m_creationDoy private
Definition at line 124 of file LasWriter.hpp.
Referenced by addArgs(), fillHeader(), and handleHeaderForwards().
NumHeaderVal<uint16_t, 0, 65535> pdal::LasWriter::m_creationYear private
Definition at line 127 of file LasWriter.hpp.
Referenced by addArgs(), fillHeader(), and handleHeaderForwards().
std::string pdal::LasWriter::m_curFilename private
Definition at line 105 of file LasWriter.hpp.
Referenced by doneFile(), fillPointBuf(), readyFile(), and writeLasZipBuf().
NumHeaderVal<uint8_t, 0, 10> pdal::LasWriter::m_dataformatId private
Definition at line 116 of file LasWriter.hpp.
Referenced by addArgs(), fillHeader(), and handleHeaderForwards().
bool pdal::LasWriter::m_discardHighReturnNumbers private
Definition at line 95 of file LasWriter.hpp.
Referenced by addArgs(), fillPointBuf(), and writeLasZipBuf().
std::vector<ExtLasVLR> pdal::LasWriter::m_eVlrs private
Definition at line 100 of file LasWriter.hpp.
Referenced by addVlr(), deleteVlr(), fillHeader(), and finishOutput().
uint16_t pdal::LasWriter::m_extraByteLen private
Definition at line 103 of file LasWriter.hpp.
Referenced by fillHeader(), prepared(), and writeLasZipBuf().
std::vector<ExtraDim> pdal::LasWriter::m_extraDims private
Definition at line 102 of file LasWriter.hpp.
Referenced by addExtraBytesVlr(), fillPointBuf(), initialize(), prepared(), and writeLasZipBuf().
StringList pdal::LasWriter::m_extraDimSpec private
Definition at line 101 of file LasWriter.hpp.
Referenced by addArgs(), and initialize().
std::string pdal::FlexWriter::m_filename protected inherited
Definition at line 49 of file FlexWriter.hpp.
Referenced by pdal::GDALWriter::addArgs(), pdal::OGRWriter::addArgs(), pdal::BpfWriter::addArgs(), addArgs(), pdal::GDALWriter::doneFile(), initialize(), pdal::OGRWriter::prepared(), and spatialReferenceChanged().
NumHeaderVal<uint16_t, 0, 65535> pdal::LasWriter::m_filesourceId private
Definition at line 119 of file LasWriter.hpp.
Referenced by fillHeader(), and handleHeaderForwards().
MetadataNode pdal::LasWriter::m_forwardMetadata private
Definition at line 134 of file LasWriter.hpp.
Referenced by addForwardVlrs(), prepOutput(), and readyTable().
std::set<std::string> pdal::LasWriter::m_forwards private
Definition at line 107 of file LasWriter.hpp.
Referenced by fillForwardList(), and handleHeaderForward().
StringList pdal::LasWriter::m_forwardSpec private
Definition at line 106 of file LasWriter.hpp.
Referenced by addArgs(), and fillForwardList().
bool pdal::LasWriter::m_forwardVlrs private
Definition at line 108 of file LasWriter.hpp.
Referenced by addForwardVlrs(), and fillForwardList().
NumHeaderVal<uint16_t, 0, 31> pdal::LasWriter::m_globalEncoding private
Definition at line 120 of file LasWriter.hpp.
Referenced by addArgs(), fillHeader(), and handleHeaderForwards().
std::map<std::string, std::string> pdal::LasWriter::m_headerVals private
Definition at line 96 of file LasWriter.hpp.
LasHeader pdal::LasWriter::m_lasHeader private
Definition at line 91 of file LasWriter.hpp.
Referenced by addArgs(), addMetadataVlr(), addPipelineVlr(), addSpatialRefVlrs(), addVlr(), fillHeader(), fillPointBuf(), fillWriteBuf(), finishOutput(), pdal::LasTester::header(), initialize(), prepared(), prepOutput(), processOne(), readyLasZipCompression(), readyLazPerfCompression(), writeLasZipBuf(), and writeView().
laszip_POINTER pdal::LasWriter::m_laszip private
Definition at line 93 of file LasWriter.hpp.
Referenced by finishLasZipOutput(), handleLaszip(), openCompression(), readyLasZipCompression(), and writeLasZipBuf().
NumHeaderVal<uint8_t, 1, 1> pdal::LasWriter::m_majorVersion private
Definition at line 114 of file LasWriter.hpp.
Referenced by addArgs(), and handleHeaderForwards().
MetadataNode pdal::Stage::m_metadata protected inherited
Stage's metadata.
Definition at line 316 of file Stage.hpp.
Referenced by pdal::Ilvis2Reader::initialize(), pdal::NitfReader::initialize(), pdal::Stage::l_initialize(), pdal::BpfReader::readHeaderExtraData(), pdal::BpfReader::readUlemFiles(), pdal::Ilvis2Reader::ready(), and pdal::Stage::setSpatialReference().
NumHeaderVal<uint8_t, 1, 4> pdal::LasWriter::m_minorVersion private
Definition at line 115 of file LasWriter.hpp.
Referenced by addArgs(), fillHeader(), and handleHeaderForwards().
StringHeaderVal<20> pdal::LasWriter::m_offsetX private
Definition at line 131 of file LasWriter.hpp.
Referenced by addArgs(), and handleHeaderForwards().
StringHeaderVal<20> pdal::LasWriter::m_offsetY private
Definition at line 132 of file LasWriter.hpp.
Referenced by addArgs(), and handleHeaderForwards().
StringHeaderVal<20> pdal::LasWriter::m_offsetZ private
Definition at line 133 of file LasWriter.hpp.
Referenced by addArgs(), and handleHeaderForwards().
std::vector<VlrOptionInfo> pdal::LasWriter::m_optionInfos private
Definition at line 97 of file LasWriter.hpp.
Options pdal::Stage::m_options protected inherited
Stage's options.
Definition at line 315 of file Stage.hpp.
Referenced by pdal::Stage::addConditionalOptions(), pdal::Stage::handleOptions(), and pdal::Stage::serialize().
std::ostream* pdal::LasWriter::m_ostream private
Definition at line 98 of file LasWriter.hpp.
Referenced by doneFile(), finishOutput(), openCompression(), prepOutput(), processOne(), readyLazPerfCompression(), and writeView().
std::vector<char> pdal::LasWriter::m_pointBuf private
Definition at line 110 of file LasWriter.hpp.
Referenced by prepOutput(), processOne(), writeLasZipBuf(), and writeView().
int pdal::Stage::m_progressFd protected inherited
Descriptor for progress info.
Definition at line 317 of file Stage.hpp.
Referenced by doneFile(), pdal::NitfWriter::readyFile(), readyFile(), and writeView().
UuidHeaderVal pdal::LasWriter::m_projectId private
Definition at line 121 of file LasWriter.hpp.
Referenced by addArgs(), fillHeader(), and handleHeaderForwards().
StringHeaderVal<20> pdal::LasWriter::m_scaleX private
Definition at line 128 of file LasWriter.hpp.
Referenced by addArgs(), and handleHeaderForwards().
StringHeaderVal<20> pdal::LasWriter::m_scaleY private
Definition at line 129 of file LasWriter.hpp.
Referenced by addArgs(), and handleHeaderForwards().
StringHeaderVal<20> pdal::LasWriter::m_scaleZ private
Definition at line 130 of file LasWriter.hpp.
Referenced by addArgs(), and handleHeaderForwards().
Scaling pdal::FlexWriter::m_scaling protected inherited
Definition at line 50 of file FlexWriter.hpp.
Referenced by pdal::BpfWriter::addArgs(), fillHeader(), fillPointBuf(), finishOutput(), pdal::BpfWriter::getAdjustedValue(), handleHeaderForwards(), pdal::BpfWriter::initialize(), pdal::BpfWriter::readyFile(), writeLasZipBuf(), pdal::BpfWriter::writeView(), and writeView().
StringHeaderVal<32> pdal::LasWriter::m_softwareId private
Definition at line 123 of file LasWriter.hpp.
Referenced by addArgs(), fillHeader(), and handleHeaderForwards().
SpatialReference pdal::LasWriter::m_srs private
Definition at line 104 of file LasWriter.hpp.
Referenced by addGeotiffVlrs(), addWktVlr(), pdal::NitfWriter::doneFile(), prepOutput(), and pdal::LasTester::srs().
int pdal::LasWriter::m_srsCnt private
Definition at line 112 of file LasWriter.hpp.
Referenced by spatialReferenceChanged().
std::unique_ptr<LasSummaryData> pdal::LasWriter::m_summaryData private
Definition at line 92 of file LasWriter.hpp.
Referenced by fillPointBuf(), finishOutput(), prepOutput(), and writeLasZipBuf().
StringHeaderVal<32> pdal::LasWriter::m_systemId private
Definition at line 122 of file LasWriter.hpp.
Referenced by addArgs(), fillHeader(), and handleHeaderForwards().
Json::Value pdal::LasWriter::m_userVLRs private
Definition at line 136 of file LasWriter.hpp.
Referenced by addArgs(), and addUserVlrs().
std::vector<LasVLR> pdal::LasWriter::m_vlrs private
Definition at line 99 of file LasWriter.hpp.
Referenced by addVlr(), deleteVlr(), fillHeader(), and prepOutput().
bool pdal::LasWriter::m_writePDALMetadata private
Definition at line 135 of file LasWriter.hpp.
Referenced by addArgs(), and readyTable().
The documentation for this class was generated from the following files:
pdal/io/LasWriter.hpp
pdal/io/LasWriter.cpp