PDAL: test.test_pipeline.TestPipeline Class Reference
test.test_pipeline.TestPipeline Class Reference
Public Member Functions
def fetch_json (self, filename)
def test_construction (self)
def test_execution (self)
def test_validate (self)
def test_array (self)
def test_metadata (self)
def test_no_execute (self)
def test_logging (self)
def test_schema (self)
def test_merged_arrays (self)
Static Public Attributes
DATADIRECTORY = os.environ.get('PDAL_TEST_DIR')
string DATADIRECTORY = "../test"
Detailed Description
Definition at line 21 of file test_pipeline.py.
Member Function Documentation
def test.test_pipeline.TestPipeline.fetch_json (self, filename)
Definition at line 26 of file test_pipeline.py.
Referenced by test.test_pipeline.TestPipeline.test_array(), test.test_pipeline.TestPipeline.test_construction(), test.test_pipeline.TestPipeline.test_execution(), test.test_pipeline.TestPipeline.test_logging(), test.test_pipeline.TestPipeline.test_merged_arrays(), test.test_pipeline.TestPipeline.test_metadata(), test.test_pipeline.TestPipeline.test_no_execute(), and test.test_pipeline.TestPipeline.test_schema().
def test.test_pipeline.TestPipeline.test_array (self)
Can we fetch PDAL data as a numpy array
Definition at line 58 of file test_pipeline.py.
References test.test_pipeline.TestPipeline.fetch_json().
def test.test_pipeline.TestPipeline.test_construction (self)
Can we construct a PDAL pipeline
Definition at line 36 of file test_pipeline.py.
References test.test_pipeline.TestPipeline.fetch_json().
def test.test_pipeline.TestPipeline.test_execution (self)
Can we execute a PDAL pipeline
Definition at line 43 of file test_pipeline.py.
References test.test_pipeline.TestPipeline.fetch_json().
def test.test_pipeline.TestPipeline.test_logging (self)
Can we fetch log output
Definition at line 94 of file test_pipeline.py.
References test.test_pipeline.TestPipeline.fetch_json().
def test.test_pipeline.TestPipeline.test_merged_arrays (self)
Can we fetch multiple point views from merged PDAL data
Definition at line 114 of file test_pipeline.py.
References test.test_pipeline.TestPipeline.fetch_json().
def test.test_pipeline.TestPipeline.test_metadata (self)
Can we fetch PDAL metadata
Definition at line 72 of file test_pipeline.py.
References test.test_pipeline.TestPipeline.fetch_json().
def test.test_pipeline.TestPipeline.test_no_execute (self)
Does fetching arrays without executing throw an exception
Definition at line 85 of file test_pipeline.py.
References test.test_pipeline.TestPipeline.fetch_json().
def test.test_pipeline.TestPipeline.test_schema (self)
Fetching a schema works
Definition at line 105 of file test_pipeline.py.
References test.test_pipeline.TestPipeline.fetch_json().
def test.test_pipeline.TestPipeline.test_validate (self)
Do we complain with bad pipelines
Definition at line 50 of file test_pipeline.py.
Member Data Documentation
test.test_pipeline.TestPipeline.DATADIRECTORY = os.environ.get('PDAL_TEST_DIR') static
Definition at line 23 of file test_pipeline.py.
string test.test_pipeline.TestPipeline.DATADIRECTORY = "../test" static
Definition at line 25 of file test_pipeline.py.
The documentation for this class was generated from the following file:
pdal/python/test/test_pipeline.py