PDAL: pdal::Hdf5Handler Class Reference
pdal::Hdf5Handler Class Reference
#include <Hdf5Handler.hpp>
Classes
struct ColumnData
struct error
Public Member Functions
Hdf5Handler ()
void initialize (const std::string &filename, const std::vector< hdf5::Hdf5ColumnData > &columns)
void close ()
uint64_t getNumPoints () const
void getColumnEntries (void *data, const std::string &dataSetName, const hsize_t numEntries, const hsize_t offset) const
Private Member Functions
hsize_t getColumnNumEntries (const std::string &dataSetName) const
const ColumnData & getColumnData (const std::string &dataSetName) const
Private Attributes
std::unique_ptr< H5::H5File > m_h5File
uint64_t m_numPoints
std::map< std::string, ColumnData > m_columnDataMap
Detailed Description
Definition at line 61 of file Hdf5Handler.hpp.
Constructor & Destructor Documentation
pdal::Hdf5Handler::Hdf5Handler ()
Definition at line 44 of file Hdf5Handler.cpp.
Member Function Documentation
void pdal::Hdf5Handler::close ()
Definition at line 87 of file Hdf5Handler.cpp.
References m_h5File.
const Hdf5Handler::ColumnData & pdal::Hdf5Handler::getColumnData (const std::string & dataSetName) const private
Definition at line 139 of file Hdf5Handler.cpp.
References m_columnDataMap.
Referenced by getColumnEntries(), and getColumnNumEntries().
void pdal::Hdf5Handler::getColumnEntries (void * data, const std::string & dataSetName, const hsize_t numEntries, const hsize_t offset) const
Definition at line 97 of file Hdf5Handler.cpp.
References pdal::Hdf5Handler::ColumnData::dataSet, pdal::Hdf5Handler::ColumnData::dataSpace, getColumnData(), and pdal::Hdf5Handler::ColumnData::predType.
hsize_t pdal::Hdf5Handler::getColumnNumEntries (const std::string & dataSetName) const private
Definition at line 129 of file Hdf5Handler.cpp.
References pdal::Hdf5Handler::ColumnData::dataSpace, and getColumnData().
Referenced by initialize().
uint64_t pdal::Hdf5Handler::getNumPoints () const
Definition at line 92 of file Hdf5Handler.cpp.
References m_numPoints.
void pdal::Hdf5Handler::initialize (const std::string & filename, const std::vector< hdf5::Hdf5ColumnData > & columns)
Definition at line 49 of file Hdf5Handler.cpp.
References getColumnNumEntries(), m_columnDataMap, m_h5File, and m_numPoints.
Member Data Documentation
std::map<std::string, ColumnData> pdal::Hdf5Handler::m_columnDataMap private
Definition at line 114 of file Hdf5Handler.hpp.
Referenced by getColumnData(), and initialize().
std::unique_ptr<H5::H5File> pdal::Hdf5Handler::m_h5File private
Definition at line 111 of file Hdf5Handler.hpp.
Referenced by close(), and initialize().
uint64_t pdal::Hdf5Handler::m_numPoints private
Definition at line 112 of file Hdf5Handler.hpp.
Referenced by getNumPoints(), and initialize().
The documentation for this class was generated from the following files:
pdal/plugins/icebridge/io/Hdf5Handler.hpp
pdal/plugins/icebridge/io/Hdf5Handler.cpp