PDAL: pdal::Uuid Class Reference
pdal::Uuid Class Reference
#include <Uuid.hpp>
Public Member Functions
Uuid ()
Uuid (const char *c)
Uuid (const std::string &s)
void clear ()
void unpack (const char *c)
void pack (char *c) const
bool parse (const std::string &s)
std::string unparse () const
std::string toString () const
bool empty () const
bool isNull () const
Static Public Attributes
static const int size = sizeof(uuid)
Private Attributes
uuid m_data
Friends
bool operator< (const Uuid &u1, const Uuid &u2)
Detailed Description
Definition at line 100 of file Uuid.hpp.
Constructor & Destructor Documentation
pdal::Uuid::Uuid ()
Definition at line 104 of file Uuid.hpp.
pdal::Uuid::Uuid (const char * c)
Definition at line 106 of file Uuid.hpp.
pdal::Uuid::Uuid (const std::string & s)
Definition at line 108 of file Uuid.hpp.
References pdal::LasUtils::parse().
Member Function Documentation
void pdal::Uuid::clear ()
Definition at line 111 of file Uuid.hpp.
bool pdal::Uuid::empty () const
Definition at line 187 of file Uuid.hpp.
bool pdal::Uuid::isNull () const
Definition at line 190 of file Uuid.hpp.
References c.
Referenced by pdal::Metadata::inferType(), and TEST().
void pdal::Uuid::pack (char * c) const
Definition at line 124 of file Uuid.hpp.
Referenced by pdal::LasHeader::put().
bool pdal::Uuid::parse (const std::string & s)
Definition at line 134 of file Uuid.hpp.
Referenced by pdal::operator>>().
std::string pdal::Uuid::toString () const
Definition at line 184 of file Uuid.hpp.
Referenced by pdal::operator<<(), pdal::MetadataNodeImpl::setValue(), and TEST().
void pdal::Uuid::unpack (const char * c)
Definition at line 114 of file Uuid.hpp.
Referenced by pdal::LasHeader::get().
std::string pdal::Uuid::unparse () const
Definition at line 170 of file Uuid.hpp.
Friends And Related Function Documentation
bool operator< (const Uuid & u1, const Uuid & u2) friend
Definition at line 215 of file Uuid.hpp.
Member Data Documentation
uuid pdal::Uuid::m_data private
Definition at line 207 of file Uuid.hpp.
Referenced by pdal::operator<().
const int pdal::Uuid::size = sizeof(uuid) static
Sadly, MS doesn't do constexpr. static constexpr size_t size() { return sizeof(m_data); }
Definition at line 204 of file Uuid.hpp.
Referenced by pdal::LasHeader::get(), and pdal::LasHeader::put().
The documentation for this class was generated from the following file:
pdal/pdal/util/Uuid.hpp