PDAL: pdal::Polygon Class Reference
pdal::Polygon Class Reference
#include <Polygon.hpp>
Public Member Functions
Polygon ()
Polygon (const std::string &wkt_or_json, SpatialReference ref=SpatialReference())
Polygon (const Polygon &)
Polygon (const BOX2D &)
Polygon (const BOX3D &)
Polygon (GEOSGeometry *g, const SpatialReference &srs)
Polygon (OGRGeometryH g, const SpatialReference &srs)
Polygon & operator= (const Polygon &)
OGRGeometryH getOGRHandle ()
~Polygon ()
Polygon simplify (double distance_tolerance, double area_tolerance) const
Polygon transform (const SpatialReference &ref) const
double area () const
bool covers (const PointRef &ref) const
bool equal (const Polygon &p) const
bool covers (const Polygon &p) const
bool overlaps (const Polygon &p) const
bool contains (const Polygon &p) const
bool touches (const Polygon &p) const
bool within (const Polygon &p) const
bool crosses (const Polygon &p) const
virtual void update (const std::string &wkt_or_json)
void setSpatialReference (const SpatialReference &ref)
const SpatialReference & getSpatialReference () const
bool equals (const Geometry &other, double tolerance=0.0001) const
bool operator== (const Geometry &other) const
bool operator!= (const Geometry &other) const
bool operator< (const Geometry &other) const
virtual bool valid () const
virtual std::string validReason () const
std::string wkt (double precision=8, bool bOutputZ=false) const
std::string json (double precision=8) const
BOX3D bounds () const
operator bool () const
Protected Member Functions
void prepare ()
Protected Attributes
GEOSGeomPtr m_geom
const GEOSPreparedGeometry * m_prepGeom
SpatialReference m_srs
geos::ErrorHandler & m_geoserr
Private Member Functions
void initializeFromBounds (const BOX3D &b)
Detailed Description
Definition at line 49 of file Polygon.hpp.
Constructor & Destructor Documentation
pdal::Polygon::Polygon ()
Definition at line 43 of file Polygon.cpp.
Referenced by transform().
pdal::Polygon::Polygon (const std::string & wkt_or_json, SpatialReference ref = SpatialReference())
Definition at line 49 of file Polygon.cpp.
pdal::Polygon::Polygon (const Polygon & input)
Definition at line 60 of file Polygon.cpp.
pdal::Polygon::Polygon (const BOX2D & box)
Definition at line 121 of file Polygon.cpp.
References initializeFromBounds(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, and pdal::BOX2D::miny.
pdal::Polygon::Polygon (const BOX3D & box)
Definition at line 129 of file Polygon.cpp.
References initializeFromBounds().
pdal::Polygon::Polygon (GEOSGeometry * g, const SpatialReference & srs)
Definition at line 83 of file Polygon.cpp.
pdal::Polygon::Polygon (OGRGeometryH g, const SpatialReference & srs)
Definition at line 89 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, and pdal::Geometry::prepare().
pdal::Polygon::~Polygon ()
Definition at line 55 of file Polygon.cpp.
Member Function Documentation
double pdal::Polygon::area () const
Definition at line 258 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
Referenced by simplify(), and pdal::TEST().
BOX3D pdal::Geometry::bounds () const inherited
Definition at line 213 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::BOX3D::grow(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, and z.
Referenced by pdal::StatsFilter::extractMetadata(), pdal::TEST(), and TEST().
bool pdal::Polygon::contains (const Polygon & p) const
Definition at line 304 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
bool pdal::Polygon::covers (const PointRef & ref) const
Definition at line 268 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::PointRef::getFieldAs(), pdal::Geometry::m_geoserr, pdal::Geometry::m_prepGeom, pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by pdal::CropFilter::crop(), and pdal::TEST().
bool pdal::Polygon::covers (const Polygon & p) const
Definition at line 294 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
bool pdal::Polygon::crosses (const Polygon & p) const
Definition at line 319 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
bool pdal::Polygon::equal (const Polygon & p) const
bool pdal::Geometry::equals (const Geometry & other, double tolerance = 0.0001) const inherited
Definition at line 249 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
Referenced by pdal::Geometry::operator!=(), and pdal::Geometry::operator==().
OGRGeometryH pdal::Polygon::getOGRHandle ()
const SpatialReference& pdal::Geometry::getSpatialReference () const inherited
Definition at line 106 of file Geometry.hpp.
References pdal::operator!=(), and pdal::operator==().
void pdal::Polygon::initializeFromBounds (const BOX3D & b) private
Definition at line 136 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::BOX3D::minz, pdal::Geometry::prepare(), and z.
Referenced by Polygon().
std::string pdal::Geometry::json (double precision = 8) const inherited
Definition at line 306 of file Geometry.cpp.
References pdal::SpatialReference::getWKT(), pdal::Geometry::m_srs, and pdal::Geometry::wkt().
Referenced by pdal::StatsFilter::extractMetadata(), and pdal::TEST().
pdal::Geometry::operator bool () const inherited
Definition at line 126 of file Geometry.hpp.
bool pdal::Geometry::operator!= (const Geometry & other) const inherited
Definition at line 262 of file Geometry.cpp.
References pdal::Geometry::equals().
bool pdal::Geometry::operator< (const Geometry & other) const inherited
Definition at line 114 of file Geometry.hpp.
References pdal::Geometry::wkt().
Polygon & pdal::Polygon::operator= (const Polygon & input)
Definition at line 66 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, pdal::Geometry::m_srs, and pdal::Geometry::prepare().
bool pdal::Geometry::operator== (const Geometry & other) const inherited
Definition at line 256 of file Geometry.cpp.
References pdal::Geometry::equals().
bool pdal::Polygon::overlaps (const Polygon & p) const
Definition at line 299 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
void pdal::Geometry::prepare () protected inherited
Definition at line 112 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, and pdal::Geometry::m_prepGeom.
Referenced by pdal::Geometry::Geometry(), initializeFromBounds(), operator=(), pdal::Geometry::operator=(), Polygon(), and pdal::Geometry::update().
void pdal::Geometry::setSpatialReference (const SpatialReference & ref) inherited
Definition at line 103 of file Geometry.hpp.
Referenced by TEST().
Polygon pdal::Polygon::simplify (double distance_tolerance, double area_tolerance) const
Definition at line 190 of file Polygon.cpp.
References area(), pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, and pdal::Geometry::m_srs.
Referenced by pdal::TEST().
bool pdal::Polygon::touches (const Polygon & p) const
Definition at line 309 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
Polygon pdal::Polygon::transform (const SpatialReference & ref) const
Definition at line 172 of file Polygon.cpp.
References pdal::SpatialReference::empty(), pdal::SpatialReference::getWKT(), pdal::Geometry::m_srs, Polygon(), and pdal::Geometry::wkt().
Referenced by pdal::StatsFilter::extractMetadata(), and TEST().
void pdal::Geometry::update (const std::string & wkt_or_json) virtual inherited
Reimplemented in pdal::filter::Point.
Definition at line 72 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, pdal::Geometry::m_geoserr, and pdal::Geometry::prepare().
Referenced by pdal::Geometry::Geometry(), pdal::operator>>(), and pdal::filter::Point::update().
bool pdal::Geometry::valid () const virtual inherited
Definition at line 268 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
Referenced by pdal::TEST().
std::string pdal::Geometry::validReason () const virtual inherited
Definition at line 278 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
bool pdal::Polygon::within (const Polygon & p) const
Definition at line 314 of file Polygon.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
std::string pdal::Geometry::wkt (double precision = 8, bool bOutputZ = false) const inherited
Definition at line 289 of file Geometry.cpp.
References pdal::geos::ErrorHandler::ctx(), pdal::Geometry::m_geom, and pdal::Geometry::m_geoserr.
Referenced by pdal::Geometry::json(), pdal::Geometry::operator<(), pdal::operator<<(), pdal::TEST(), transform(), and pdal::Geometry::transform().
Member Data Documentation
GEOSGeomPtr pdal::Geometry::m_geom protected inherited
Definition at line 131 of file Geometry.hpp.
Referenced by area(), pdal::Geometry::bounds(), contains(), covers(), crosses(), pdal::Geometry::equals(), pdal::Geometry::Geometry(), initializeFromBounds(), operator=(), pdal::Geometry::operator=(), overlaps(), Polygon(), pdal::Geometry::prepare(), simplify(), touches(), pdal::filter::Point::update(), pdal::Geometry::update(), pdal::Geometry::valid(), pdal::Geometry::validReason(), within(), pdal::Geometry::wkt(), and pdal::Geometry::~Geometry().
geos::ErrorHandler& pdal::Geometry::m_geoserr protected inherited
Definition at line 135 of file Geometry.hpp.
Referenced by area(), pdal::Geometry::bounds(), contains(), covers(), crosses(), pdal::Geometry::equals(), pdal::Geometry::Geometry(), initializeFromBounds(), operator=(), pdal::Geometry::operator=(), overlaps(), Polygon(), pdal::Geometry::prepare(), simplify(), touches(), pdal::filter::Point::update(), pdal::Geometry::update(), pdal::Geometry::valid(), pdal::Geometry::validReason(), within(), pdal::Geometry::wkt(), and pdal::Geometry::~Geometry().
const GEOSPreparedGeometry* pdal::Geometry::m_prepGeom protected inherited
Definition at line 132 of file Geometry.hpp.
Referenced by covers(), pdal::Geometry::Geometry(), pdal::Geometry::prepare(), and pdal::Geometry::~Geometry().
SpatialReference pdal::Geometry::m_srs protected inherited
Definition at line 134 of file Geometry.hpp.
Referenced by pdal::Geometry::json(), operator=(), pdal::Geometry::operator=(), simplify(), transform(), and pdal::Geometry::transform().
The documentation for this class was generated from the following files:
pdal/pdal/Polygon.hpp
pdal/pdal/Polygon.cpp