PDAL: pdal::PointIdxRef Class Reference
pdal::PointIdxRef Class Reference
#include <PointViewIter.hpp>
Public Member Functions
PointIdxRef ()
PointIdxRef (const PointIdxRef &r)
PointIdxRef (PointView *buf, PointId id)
~PointIdxRef ()
PointIdxRef & operator= (const PointIdxRef &r)
bool compare (Dimension::Id dim, const PointIdxRef &p) const
void swap (PointIdxRef &p)
Private Attributes
PointView * m_buf
PointId m_id
bool m_tmp
Detailed Description
Definition at line 44 of file PointViewIter.hpp.
Constructor & Destructor Documentation
pdal::PointIdxRef::PointIdxRef ()
Definition at line 52 of file PointViewIter.hpp.
Referenced by pdal::PointViewIter::operator*(), and pdal::PointViewIter::operator[]().
pdal::PointIdxRef::PointIdxRef (const PointIdxRef & r)
Definition at line 54 of file PointViewIter.hpp.
References pdal::PointView::getTemp(), and m_id.
pdal::PointIdxRef::PointIdxRef (PointView * buf, PointId id)
Definition at line 60 of file PointViewIter.hpp.
pdal::PointIdxRef::~PointIdxRef ()
Definition at line 63 of file PointViewIter.hpp.
References pdal::PointView::freeTemp().
Member Function Documentation
bool pdal::PointIdxRef::compare (Dimension::Id dim, const PointIdxRef & p) const
Definition at line 83 of file PointViewIter.hpp.
References pdal::PointView::compare(), and m_id.
Referenced by pdal::SortFilter::filter().
PointIdxRef& pdal::PointIdxRef::operator= (const PointIdxRef & r)
Definition at line 69 of file PointViewIter.hpp.
References pdal::PointView::getTemp(), m_buf, m_id, and pdal::PointView::m_index.
void pdal::PointIdxRef::swap (PointIdxRef & p)
Definition at line 86 of file PointViewIter.hpp.
References pdal::Dimension::id(), m_buf, m_id, and pdal::PointView::m_index.
Member Data Documentation
PointView* pdal::PointIdxRef::m_buf private
Definition at line 47 of file PointViewIter.hpp.
Referenced by operator=(), and swap().
PointId pdal::PointIdxRef::m_id private
Definition at line 48 of file PointViewIter.hpp.
Referenced by compare(), pdal::PointViewIter::operator++(), pdal::PointViewIter::operator--(), operator=(), PointIdxRef(), and swap().
bool pdal::PointIdxRef::m_tmp private
Definition at line 49 of file PointViewIter.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/PointViewIter.hpp