PDAL: pdal::OWStatement Class Reference
pdal::OWStatement Class Reference
#include <OciWrapper.h>
Public Member Functions
OWStatement (OWConnection *poConnect, const char *pszStatement)
virtual ~OWStatement ()
bool Execute (int nRows=1)
bool Fetch (int nRows=1)
bool GetNextField (int nIndex, char *pszName, int *pnType, int *pnSize, int *pnPrecision, signed short *pnScale, char *pszTypeName)
int GetInteger (OCINumber *ppoData)
double GetDouble (OCINumber *ppoData)
char * GetString (OCIString *ppoData)
void Bind (int *pnData)
void Bind (long *pnData)
void Bind (double *pnData)
void Bind (char *pData, long nData)
void BindClob (char *pData, long nData)
void Bind (sdo_geometry **pphData)
void Bind (sdo_pc_blk **pphData)
void BindBlob (OCILobLocator **pphLocator)
bool AllocBlob (OCILobLocator **phLocator)
void BindClob (OCILobLocator **pphLocator)
void Bind (OCIArray **pphData, OCIType *type)
void Bind (char *pszData, int nSize=OWNAME)
void Define (int *pnData)
void Define (long *pnData)
void Define (long long *pnData)
void Define (double *pnData)
void Define (char *pszData, int nSize=OWNAME)
void Define (OCILobLocator **pphLocator)
void Define (OCIArray **pphData)
void Define (sdo_georaster **pphData)
void Define (sdo_geometry **pphData)
void Define (sdo_pc **pphData)
void Define (sdo_pc_blk **pphData)
void Define (sdo_orgscl_type **pphData)
void Define (OCILobLocator **pphLocator, long nIterations)
void DefineClob (OCILobLocator **pphLocator, long nIterations)
void BindName (const char *pszName, int *pnData)
void BindName (const char *pszName, double *pnData)
void BindName (const char *pszName, char *pszData, int nSize=OWNAME)
void BindName (const char *pszName, OCILobLocator **pphLocator)
void BindArray (void *pData, long nSize=1)
bool OpenBlob (OCILobLocator *phLocator, bool bReadOnly=true)
bool CloseBlob (OCILobLocator *phLocator)
bool EnableBuffering (OCILobLocator *phLocator)
bool DisableBuffering (OCILobLocator *phLocator)
bool ReadBlob (OCILobLocator *phLocator, void *pBuffer, int nSize, unsigned int *nAmountRead)
char * ReadCLob (OCILobLocator *phLocator)
unsigned long GetBlobLength (OCILobLocator *phLocator)
signed long GetArrayLength (OCIArray **ppoData)
void WriteCLob (OCILobLocator **pphLocator, char *pszData)
bool WriteBlob (OCILobLocator **phLocator, void *pBuffer, int nSize, int numChunks=8)
int GetElement (OCIArray **ppoData, int nIndex, int *pnResult)
double GetElement (OCIArray **ppoData, int nIndex, double *pdfResult)
void AddElement (OCIArray *ppoData, int nValue)
void AddElement (OCIArray *ppoData, double dfValue)
Static Public Member Functions
static void Free (OCILobLocator **ppphLocator, int nCount)
Public Attributes
unsigned int nFetchCount
Private Attributes
OWConnection * poConnection
OCIStmt * hStmt
OCIError * hError
int nNextCol
int nNextBnd
ub4 nStmtMode
Detailed Description
Definition at line 384 of file OciWrapper.h.
Constructor & Destructor Documentation
pdal::OWStatement::OWStatement (OWConnection * poConnect, const char * pszStatement)
Definition at line 593 of file OciWrapper.cpp.
References pdal::CheckError(), pdal::OWConnection::hError, and pdal::MbError::text().
pdal::OWStatement::~OWStatement () virtual
Definition at line 649 of file OciWrapper.cpp.
Member Function Documentation
void pdal::OWStatement::AddElement (OCIArray * ppoData, int nValue)
Definition at line 1670 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::AddElement (OCIArray * ppoData, double dfValue)
Definition at line 1688 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
bool pdal::OWStatement::AllocBlob (OCILobLocator ** phLocator)
Definition at line 1832 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Bind (int * pnData)
Definition at line 862 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Bind (long * pnData)
Definition at line 885 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Bind (double * pnData)
Definition at line 908 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Bind (char * pData, long nData)
Definition at line 931 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Bind (sdo_geometry ** pphData)
Definition at line 977 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Bind (sdo_pc_blk ** pphData)
Definition at line 1011 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Bind (OCIArray ** pphData, OCIType * type)
Definition at line 1092 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Bind (char * pszData, int nSize = OWNAME)
Definition at line 1126 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::BindArray (void * pData, long nSize = 1)
Definition at line 2139 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::BindBlob (OCILobLocator ** pphLocator)
Definition at line 1045 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::BindClob (char * pData, long nData)
Definition at line 954 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::BindClob (OCILobLocator ** pphLocator)
Definition at line 1069 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::BindName (const char * pszName, int * pnData)
Definition at line 2043 of file OciWrapper.cpp.
References pdal::CheckError(), pdal::OWConnection::hError, and pdal::MbError::text().
void pdal::OWStatement::BindName (const char * pszName, double * pnData)
Definition at line 2065 of file OciWrapper.cpp.
References pdal::CheckError(), pdal::OWConnection::hError, and pdal::MbError::text().
void pdal::OWStatement::BindName (const char * pszName, char * pszData, int nSize = OWNAME)
Definition at line 2087 of file OciWrapper.cpp.
References pdal::CheckError(), pdal::OWConnection::hError, and pdal::MbError::text().
void pdal::OWStatement::BindName (const char * pszName, OCILobLocator ** pphLocator)
Definition at line 2109 of file OciWrapper.cpp.
References pdal::CheckError(), pdal::OWConnection::hError, and pdal::MbError::text().
bool pdal::OWStatement::CloseBlob (OCILobLocator * phLocator)
Definition at line 1790 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (int * pnData)
Definition at line 1149 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (long * pnData)
Definition at line 1168 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (long long * pnData)
Definition at line 1187 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (double * pnData)
Definition at line 1206 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (char * pszData, int nSize = OWNAME)
Definition at line 1225 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (OCILobLocator ** pphLocator)
Definition at line 1246 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (OCIArray ** pphData)
Definition at line 1345 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (sdo_georaster ** pphData)
Definition at line 1372 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (sdo_geometry ** pphData)
Definition at line 1399 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (sdo_pc ** pphData)
Definition at line 1454 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (sdo_pc_blk ** pphData)
Definition at line 1426 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (sdo_orgscl_type ** pphData)
Definition at line 1481 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::Define (OCILobLocator ** pphLocator, long nIterations)
Definition at line 1507 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
void pdal::OWStatement::DefineClob (OCILobLocator ** pphLocator, long nIterations)
Definition at line 1274 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
bool pdal::OWStatement::DisableBuffering (OCILobLocator * phLocator)
Definition at line 1817 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
bool pdal::OWStatement::EnableBuffering (OCILobLocator * phLocator)
Definition at line 1802 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
bool pdal::OWStatement::Execute (int nRows = 1)
Definition at line 654 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
bool pdal::OWStatement::Fetch (int nRows = 1)
Definition at line 679 of file OciWrapper.cpp.
References pdal::CheckError().
void pdal::OWStatement::Free (OCILobLocator ** ppphLocator, int nCount) static
Definition at line 1572 of file OciWrapper.cpp.
Referenced by pdal::OciWriter::writeTile().
signed long int pdal::OWStatement::GetArrayLength (OCIArray ** ppoData)
Definition at line 1587 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
unsigned long pdal::OWStatement::GetBlobLength (OCILobLocator * phLocator)
Definition at line 1754 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
double pdal::OWStatement::GetDouble (OCINumber * ppoData)
Definition at line 1551 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
int pdal::OWStatement::GetElement (OCIArray ** ppoData, int nIndex, int * pnResult)
Definition at line 1601 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
double pdal::OWStatement::GetElement (OCIArray ** ppoData, int nIndex, double * pdfResult)
Definition at line 1636 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
int pdal::OWStatement::GetInteger (OCINumber * ppoData)
Definition at line 1536 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
bool pdal::OWStatement::GetNextField (int nIndex, char * pszName, int * pnType, int * pnSize, int * pnPrecision, signed short * pnScale, char * pszTypeName)
Definition at line 705 of file OciWrapper.cpp.
References pdal::CheckError(), pdal::OWConnection::hError, OWNAME, and pdal::MbError::text().
char * pdal::OWStatement::GetString (OCIString * ppoData)
Definition at line 1565 of file OciWrapper.cpp.
bool pdal::OWStatement::OpenBlob (OCILobLocator * phLocator, bool bReadOnly = true)
Definition at line 1770 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
bool pdal::OWStatement::ReadBlob (OCILobLocator * phLocator, void * pBuffer, int nSize, unsigned int * nAmountRead)
Definition at line 1705 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
char * pdal::OWStatement::ReadCLob (OCILobLocator * phLocator)
Definition at line 1994 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
bool pdal::OWStatement::WriteBlob (OCILobLocator ** phLocator, void * pBuffer, int nSize, int numChunks = 8)
Definition at line 1881 of file OciWrapper.cpp.
References pdal::cbctx::buffer, pdal::cbctx::buffer_len, pdal::callback(), pdal::CheckError(), pdal::OWConnection::hError, pdal::cbctx::length, and pdal::cbctx::position.
void pdal::OWStatement::WriteCLob (OCILobLocator ** pphLocator, char * pszData)
Definition at line 1304 of file OciWrapper.cpp.
References pdal::CheckError(), and pdal::OWConnection::hError.
Member Data Documentation
OCIError* pdal::OWStatement::hError private
Definition at line 397 of file OciWrapper.h.
OCIStmt* pdal::OWStatement::hStmt private
Definition at line 396 of file OciWrapper.h.
unsigned int pdal::OWStatement::nFetchCount
Definition at line 408 of file OciWrapper.h.
int pdal::OWStatement::nNextBnd private
Definition at line 400 of file OciWrapper.h.
int pdal::OWStatement::nNextCol private
Definition at line 399 of file OciWrapper.h.
ub4 pdal::OWStatement::nStmtMode private
Definition at line 402 of file OciWrapper.h.
OWConnection* pdal::OWStatement::poConnection private
Definition at line 395 of file OciWrapper.h.
The documentation for this class was generated from the following files:
pdal/plugins/oci/io/OciWrapper.h
pdal/plugins/oci/io/OciWrapper.cpp