PDAL: pdal::StreamPointTable Class Reference
pdal::StreamPointTable Class Reference abstract
#include <PointTable.hpp>
Public Member Functions
virtual PointId addPoint ()
virtual void finalize ()
virtual void reset ()
virtual point_count_t capacity () const =0
virtual PointLayoutPtr layout () const
MetadataNode metadata ()
void setSpatialReference (const SpatialReference &srs)
void clearSpatialReferences ()
void addSpatialReference (const SpatialReference &srs)
bool spatialReferenceUnique () const
SpatialReference spatialReference () const
SpatialReference anySpatialReference () const
virtual bool supportsView () const
MetadataNode privateMetadata (const std::string &name)
MetadataNode toMetadata () const
Protected Member Functions
StreamPointTable (PointLayout &layout)
std::size_t pointsToBytes (point_count_t numPts) const
virtual char * getPoint (PointId idx)=0
Protected Attributes
MetadataPtr m_metadata
std::list< SpatialReference > m_spatialRefs
PointLayout & m_layoutRef
Detailed Description
A StreamPointTable must provide storage for point data up to its capacity. It must implement getPoint() which returns a pointer to a buffer of sufficient size to contain a point's data. The minimum size required is constant and can be determined by calling pointsToBytes(1) in the finalize() method.
Definition at line 173 of file PointTable.hpp.
Constructor & Destructor Documentation
pdal::StreamPointTable::StreamPointTable (PointLayout & layout) protected
Definition at line 176 of file PointTable.hpp.
Member Function Documentation
virtual PointId pdal::StreamPointTable::addPoint () virtual
Called when a new point should be added. Probably a no-op for streaming.
Implements pdal::BasePointTable.
Definition at line 182 of file PointTable.hpp.
void pdal::BasePointTable::addSpatialReference (const SpatialReference & srs) inherited
Definition at line 50 of file PointTable.cpp.
References pdal::BasePointTable::m_spatialRefs.
Referenced by pdal::Stage::execute(), and pdal::TEST().
SpatialReference pdal::BasePointTable::anySpatialReference () const inherited
Definition at line 88 of file PointTable.hpp.
Referenced by pdal::HexBin::done(), pdal::DensityKernel::execute(), pdal::StatsFilter::extractMetadata(), pdal::MergeFilter::ready(), pdal::ReprojectionFilter::ready(), pdal::CropFilter::ready(), pdal::OverlayFilter::ready(), and pdal::TEST().
virtual point_count_t pdal::StreamPointTable::capacity () const pure virtual
Implemented in pdal::FixedPointTable.
Referenced by pdal::Stage::execute().
void pdal::BasePointTable::clearSpatialReferences () inherited
Definition at line 78 of file PointTable.hpp.
Referenced by pdal::Stage::execute().
virtual void pdal::StreamPointTable::finalize () virtual
Called when execute() is started. Typically used to set buffer size when all dimensions are known.
Reimplemented from pdal::BasePointTable.
Reimplemented in pdal::FixedPointTable.
Definition at line 186 of file PointTable.hpp.
Referenced by pdal::Stage::execute().
virtual char* pdal::BasePointTable::getPoint (PointId idx) protected pure virtual inherited
Implemented in pdal::FixedPointTable, and pdal::PointTable.
Referenced by pdal::SimplePointTable::getDimension().
virtual PointLayoutPtr pdal::BasePointTable::layout () const virtual inherited
Implements pdal::PointContainer.
Definition at line 65 of file PointTable.hpp.
Referenced by pdal::plang::Invocation::begin(), GDALReaderTypeTest::compare(), pdal::PlyWriter::done(), anonymous_namespace{SortFilterTest.cpp}::doSort(), pdal::InfoKernel::dump(), pdal::PointView::dump(), pdal::plang::Invocation::end(), pdal::PipelineKernel::execute(), pdal::DiffKernel::execute(), pdal::DeltaKernel::execute(), getBytes(), pdal::PipelineExecutor::getSchema(), main(), makeTestView(), pdal::Stage::prepare(), pdal::MatlabWriter::prepared(), pdal::AssignFilter::prepared(), pdal::GDALWriter::prepared(), pdal::GreyhoundReader::prepared(), pdal::PlyWriter::prepared(), pdal::ComputeRangeFilter::prepared(), pdal::HAGFilter::prepared(), pdal::GroupByFilter::prepared(), pdal::IQRFilter::prepared(), pdal::LocateFilter::prepared(), pdal::RangeFilter::prepared(), pdal::MADFilter::prepared(), pdal::PMFFilter::prepared(), pdal::DbWriter::prepared(), pdal::FerryFilter::prepared(), pdal::SMRFilter::prepared(), pdal::SortFilter::prepared(), pdal::ColorinterpFilter::prepared(), pdal::BpfWriter::prepared(), pdal::OverlayFilter::prepared(), pdal::LasWriter::prepared(), pdal::StatsFilter::prepared(), pdal::MyWriter::ready(), pdal::GeoWaveWriter::ready(), pdal::TextWriter::ready(), pdal::PlyWriter::ready(), pdal::Ilvis2Reader::ready(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), pdal::TEST(), TEST_F(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), pdal::BasePointTable::toMetadata(), pdal::MongusFilter::writeControl(), and pdal::TextWriter::writeCSVHeader().
MetadataNode pdal::BasePointTable::metadata () inherited
Definition at line 69 of file PointTable.hpp.
Referenced by pdal::DiffKernel::execute(), pdal::TIndexKernel::getFileInfo(), pdal::MatlabReader::initialize(), pdal::Stage::l_initialize(), pdal::MatlabWriter::ready(), pdal::MatlabFilter::ready(), pdal::PythonFilter::ready(), pdal::LasWriter::readyTable(), TEST(), and TEST_F().
std::size_t pdal::SimplePointTable::pointsToBytes (point_count_t numPts) const protected inherited
Definition at line 121 of file PointTable.hpp.
MetadataNode pdal::BasePointTable::privateMetadata (const std::string & name) inherited
Definition at line 40 of file PointTable.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::findChild(), pdal::BasePointTable::m_metadata, and pdal::MetadataNode::valid().
Referenced by pdal::LasReader::initializeLocal(), pdal::LasWriter::readyTable(), and TEST().
virtual void pdal::StreamPointTable::reset () virtual
Called when the contents of StreamPointTable have been consumed and the point data will be potentially overwritten.
Reimplemented in pdal::FixedPointTable.
Definition at line 190 of file PointTable.hpp.
Referenced by pdal::Stage::execute().
void pdal::BasePointTable::setSpatialReference (const SpatialReference & srs) inherited
Definition at line 73 of file PointTable.hpp.
Referenced by pdal::Stage::execute().
SpatialReference pdal::BasePointTable::spatialReference () const inherited
Definition at line 83 of file PointTable.hpp.
Referenced by TEST().
bool pdal::BasePointTable::spatialReferenceUnique () const inherited
Definition at line 81 of file PointTable.hpp.
Referenced by pdal::CropFilter::ready(), and pdal::TEST().
virtual bool pdal::BasePointTable::supportsView () const virtual inherited
Reimplemented in pdal::PointTable.
Definition at line 93 of file PointTable.hpp.
References anonymous_namespace{ReprojectionFilterTest.cpp}::getPoint(), pdal::Dimension::name(), and pdal::Utils::toMetadata().
Referenced by pdal::ReprojectionFilter::ready(), pdal::GDALWriter::readyTable(), and pdal::FlexWriter::validateFilename().
MetadataNode pdal::BasePointTable::toMetadata () const inherited
Definition at line 109 of file PointTable.cpp.
References pdal::BasePointTable::layout(), and pdal::PointLayout::toMetadata().
Member Data Documentation
PointLayout& pdal::BasePointTable::m_layoutRef protected inherited
Definition at line 108 of file PointTable.hpp.
Referenced by pdal::SimplePointTable::getFieldInternal(), and pdal::SimplePointTable::setFieldInternal().
MetadataPtr pdal::BasePointTable::m_metadata protected inherited
Definition at line 106 of file PointTable.hpp.
Referenced by pdal::BasePointTable::privateMetadata().
std::list<SpatialReference> pdal::BasePointTable::m_spatialRefs protected inherited
Definition at line 107 of file PointTable.hpp.
Referenced by pdal::BasePointTable::addSpatialReference(), and pdal::TEST().
The documentation for this class was generated from the following file:
pdal/pdal/PointTable.hpp