PDAL: pdal::LasHeader Class Reference
pdal::LasHeader Class Reference
#include <LasHeader.hpp>
Classes
struct error
Public Member Functions
std::string getSystemIdentifier () const
LasHeader ()
std::string fileSignature () const
void SetFileSignature (std::string const &v)
uint16_t fileSourceId () const
void setFileSourceId (uint16_t v)
uint16_t globalEncoding () const
void setGlobalEncoding (uint16_t globalEncoding)
Uuid projectId () const
void setProjectId (const Uuid &v)
Set project identifier.
uint8_t versionMajor () const
uint8_t versionMinor () const
void setVersionMinor (uint8_t v)
bool versionAtLeast (uint8_t major, uint8_t minor) const
bool versionEquals (uint8_t major, uint8_t minor) const
std::string systemId () const
void setSystemId (std::string const &v)
std::string softwareId () const
void setSoftwareId (std::string const &v)
uint16_t creationDOY () const
Get day of year of file creation date.
void setCreationDOY (uint16_t v)
uint16_t creationYear () const
Set year of file creation date.
void setCreationYear (uint16_t v)
uint16_t vlrOffset () const
void setVlrOffset (uint16_t offset)
uint32_t pointOffset () const
Get number of bytes from the beginning to the first point record.
void setPointOffset (uint32_t offset)
void setPointFormat (uint8_t format)
uint8_t pointFormat () const
Get identifier of point data (record) format.
bool pointFormatSupported () const
uint16_t pointLen () const
void setPointLen (uint16_t v)
uint16_t basePointLen ()
uint16_t basePointLen (uint8_t format)
void setPointCount (uint64_t pointCount)
uint64_t pointCount () const
Get total number of point records stored in the LAS file.
void setPointCountByReturn (std::size_t index, uint64_t v)
uint64_t pointCountByReturn (std::size_t index)
size_t maxReturnCount () const
double scaleX () const
Get scale factor for X coordinate.
double scaleY () const
Get scale factor for Y coordinate.
double scaleZ () const
Get scale factor for Z coordinate.
void setScaling (const Scaling &scaling)
Set values of scale/offset factor for X, Y and Z coordinates.
double offsetX () const
Get X coordinate offset.
double offsetY () const
Get Y coordinate offset.
double offsetZ () const
Get Z coordinate offset.
void setOffset (double x, double y, double z)
Set values of X, Y and Z coordinates offset.
double maxX () const
Get minimum value of extent of X coordinate.
double minX () const
Get maximum value of extent of X coordinate.
double maxY () const
Get minimum value of extent of Y coordinate.
double minY () const
Get maximum value of extent of Y coordinate.
double maxZ () const
Get minimum value of extent of Z coordinate.
double minZ () const
Get maximum value of extent of Z coordinate.
const BOX3D & getBounds () const
void setBounds (const BOX3D &bounds)
bool hasTime () const
bool hasColor () const
bool hasWave () const
bool hasInfrared () const
bool has14Format () const
bool useWkt () const
bool incompatibleSrs () const
bool compressed () const
void setCompressed (bool b)
Sets whether or not the points are compressed.
void setVlrCount (uint32_t vlrCount)
uint32_t vlrCount () const
void setEVlrOffset (uint64_t offset)
uint64_t eVlrOffset () const
void setEVlrCount (uint32_t count)
uint32_t eVlrCount () const
std::string const & compressionInfo () const
void setCompressionInfo (std::string const &info)
SpatialReference srs () const
void setSummary (const LasSummaryData &summary)
bool valid () const
Dimension::IdList usedDims () const
const LasVLR * findVlr (const std::string &userId, uint16_t recordId) const
void removeVLR (const std::string &userId, uint16_t recordId)
void removeVLR (const std::string &userId)
void setLog (LogPtr log)
const VlrList & vlrs () const
Static Public Attributes
static const size_t LEGACY_RETURN_COUNT = 5
static const size_t RETURN_COUNT = 15
static const std::string FILE_SIGNATURE
Private Member Functions
void setSrs ()
void setSrsFromWkt ()
void setSrsFromGeotiff ()
Static Private Member Functions
static void get (ILeStream &in, Uuid &uuid)
static void put (OLeStream &in, Uuid uuid)
Private Attributes
std::string m_fileSig
uint16_t m_sourceId
uint16_t m_globalEncoding
Uuid m_projectUuid
uint8_t m_versionMinor
std::string m_systemId
std::string m_softwareId
uint16_t m_createDOY
uint16_t m_createYear
uint16_t m_vlrOffset
uint32_t m_pointOffset
uint32_t m_vlrCount
uint8_t m_pointFormat
uint16_t m_pointLen
uint64_t m_pointCount
std::array< uint64_t, RETURN_COUNT > m_pointCountByReturn
std::array< double, 3 > m_scales
std::array< double, 3 > m_offsets
bool m_isCompressed
uint64_t m_eVlrOffset
uint32_t m_eVlrCount
BOX3D m_bounds
std::string m_compressionInfo
LogPtr m_log
SpatialReference m_srs
VlrList m_vlrs
VlrList m_eVlrs
Friends
PDAL_DLL friend ILeStream & operator>> (ILeStream &, LasHeader &h)
OLeStream & operator<< (OLeStream &, const LasHeader &h)
std::ostream & operator<< (std::ostream &ostr, const LasHeader &h)
Detailed Description
Definition at line 60 of file LasHeader.hpp.
Constructor & Destructor Documentation
pdal::LasHeader::LasHeader ()
Definition at line 68 of file LasHeader.cpp.
References basePointLen(), m_createDOY, m_createYear, m_offsets, m_pointCountByReturn, m_pointFormat, m_pointLen, and m_scales.
Member Function Documentation
uint16_t pdal::LasHeader::basePointLen ()
Definition at line 231 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader(), LasHeader(), and TEST().
uint16_t pdal::LasHeader::basePointLen (uint8_t format)
Definition at line 130 of file LasHeader.cpp.
References pdal::Dimension::type().
bool pdal::LasHeader::compressed () const
Returns true iff the file is compressed (laszip), as determined by the high bit in the point type
Definition at line 355 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::LasWriter::prepOutput(), TEST(), and pdal::nitfwrap::NitfWrap::verifyLas().
std::string const& pdal::LasHeader::compressionInfo () const
Definition at line 374 of file LasHeader.hpp.
Referenced by TEST().
uint16_t pdal::LasHeader::creationDOY () const
Get day of year of file creation date.
Definition at line 174 of file LasHeader.hpp.
Referenced by TEST().
uint16_t pdal::LasHeader::creationYear () const
Set year of file creation date.
Definition at line 183 of file LasHeader.hpp.
Referenced by TEST().
uint32_t pdal::LasHeader::eVlrCount () const
Definition at line 372 of file LasHeader.hpp.
uint64_t pdal::LasHeader::eVlrOffset () const
Definition at line 368 of file LasHeader.hpp.
std::string pdal::LasHeader::fileSignature () const
Get ASPRS LAS file signature.
Returns
4-characters long string - "LASF".
Definition at line 78 of file LasHeader.hpp.
Referenced by TEST().
uint16_t pdal::LasHeader::fileSourceId () const
Get file source identifier.
Exceptions
No throw
Definition at line 91 of file LasHeader.hpp.
Referenced by TEST().
const LasVLR * pdal::LasHeader::findVlr (const std::string & userId, uint16_t recordId) const
Definition at line 255 of file LasHeader.cpp.
References m_vlrs, and pdal::LasVLR::matches().
Referenced by setSrs(), setSrsFromGeotiff(), setSrsFromWkt(), and TEST().
void pdal::LasHeader::get (ILeStream & in, Uuid & uuid) static private
Definition at line 155 of file LasHeader.cpp.
References pdal::IStream::get(), pdal::Uuid::size, and pdal::Uuid::unpack().
Referenced by pdal::operator>>().
const BOX3D& pdal::LasHeader::getBounds () const
Definition at line 312 of file LasHeader.hpp.
Referenced by pdal::nitfwrap::NitfWrap::verifyLas().
std::string pdal::LasHeader::getSystemIdentifier () const
Definition at line 72 of file LasHeader.hpp.
Referenced by pdal::LasWriter::addArgs().
uint16_t pdal::LasHeader::globalEncoding () const
Definition at line 100 of file LasHeader.hpp.
bool pdal::LasHeader::has14Format () const
Definition at line 341 of file LasHeader.hpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
Referenced by pdal::LasWriter::fillPointBuf(), and pdal::LasWriter::writeLasZipBuf().
bool pdal::LasHeader::hasColor () const
Definition at line 323 of file LasHeader.hpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
Referenced by pdal::LasWriter::fillPointBuf(), pdal::LasReader::loadPoint(), pdal::LasReader::loadPointV10(), pdal::LasReader::loadPointV14(), pdal::LasWriter::readyLazPerfCompression(), usedDims(), and pdal::LasWriter::writeLasZipBuf().
bool pdal::LasHeader::hasInfrared () const
Definition at line 335 of file LasHeader.hpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
Referenced by pdal::LasWriter::fillPointBuf(), pdal::LasReader::loadPointV10(), pdal::LasReader::loadPointV14(), usedDims(), and pdal::LasWriter::writeLasZipBuf().
bool pdal::LasHeader::hasTime () const
Definition at line 317 of file LasHeader.hpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
Referenced by pdal::LasWriter::fillPointBuf(), pdal::LasReader::loadPoint(), pdal::LasReader::loadPointV10(), pdal::LasWriter::readyLazPerfCompression(), usedDims(), and pdal::LasWriter::writeLasZipBuf().
bool pdal::LasHeader::hasWave () const
Definition at line 329 of file LasHeader.hpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
bool pdal::LasHeader::incompatibleSrs () const
Definition at line 350 of file LasHeader.hpp.
Referenced by setSrs().
size_t pdal::LasHeader::maxReturnCount () const
Definition at line 255 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillPointBuf(), and pdal::LasWriter::writeLasZipBuf().
double pdal::LasHeader::maxX () const
Get minimum value of extent of X coordinate.
Definition at line 289 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and TEST().
double pdal::LasHeader::maxY () const
Get minimum value of extent of Y coordinate.
Definition at line 297 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and TEST().
double pdal::LasHeader::maxZ () const
Get minimum value of extent of Z coordinate.
Definition at line 305 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and TEST().
double pdal::LasHeader::minX () const
Get maximum value of extent of X coordinate.
Definition at line 293 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and TEST().
double pdal::LasHeader::minY () const
Get maximum value of extent of Y coordinate.
Definition at line 301 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and TEST().
double pdal::LasHeader::minZ () const
Get maximum value of extent of Z coordinate.
Definition at line 309 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and TEST().
double pdal::LasHeader::offsetX () const
Get X coordinate offset.
Definition at line 274 of file LasHeader.hpp.
Referenced by pdal::LasReader::loadPoint(), pdal::LasReader::loadPointV10(), pdal::LasReader::loadPointV14(), and TEST().
double pdal::LasHeader::offsetY () const
Get Y coordinate offset.
Definition at line 278 of file LasHeader.hpp.
Referenced by pdal::LasReader::loadPoint(), pdal::LasReader::loadPointV10(), pdal::LasReader::loadPointV14(), and TEST().
double pdal::LasHeader::offsetZ () const
Get Z coordinate offset.
Definition at line 282 of file LasHeader.hpp.
References z.
Referenced by pdal::LasReader::loadPoint(), pdal::LasReader::loadPointV10(), pdal::LasReader::loadPointV14(), and TEST().
uint64_t pdal::LasHeader::pointCount () const
Get total number of point records stored in the LAS file.
Definition at line 240 of file LasHeader.hpp.
Referenced by TEST().
uint64_t pdal::LasHeader::pointCountByReturn (std::size_t index)
Get the point count by return number.
Parameters
index - Return number.
Returns
- Point count.
Definition at line 252 of file LasHeader.hpp.
Referenced by TEST().
uint8_t pdal::LasHeader::pointFormat () const
Get identifier of point data (record) format.
Definition at line 214 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader(), pdal::operator<<(), pdal::LasWriter::readyLasZipCompression(), TEST(), and test_a_format().
bool pdal::LasHeader::pointFormatSupported () const
Definition at line 216 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
uint16_t pdal::LasHeader::pointLen () const
The length in bytes of each point. All points in the file are considered to be fixed in size, and the PointFormatName is used to determine the fixed portion of the dimensions in the point.
Definition at line 227 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillWriteBuf(), pdal::LasWriter::processOne(), pdal::LasWriter::readyLasZipCompression(), TEST(), and pdal::LasWriter::writeView().
uint32_t pdal::LasHeader::pointOffset () const
Get number of bytes from the beginning to the first point record.
Definition at line 200 of file LasHeader.hpp.
Uuid pdal::LasHeader::projectId () const
Get project identifier.
Returns
UUID
Definition at line 107 of file LasHeader.hpp.
Referenced by TEST().
void pdal::LasHeader::put (OLeStream & in, Uuid uuid) static private
Definition at line 164 of file LasHeader.cpp.
References pdal::Uuid::pack(), pdal::OStream::put(), and pdal::Uuid::size.
Referenced by pdal::operator<<().
void pdal::LasHeader::removeVLR (const std::string & userId, uint16_t recordId)
Definition at line 230 of file LasHeader.cpp.
References m_eVlrs, m_vlrs, and pdal::Utils::remove_if().
void pdal::LasHeader::removeVLR (const std::string & userId)
Definition at line 242 of file LasHeader.cpp.
References m_eVlrs, m_vlrs, and pdal::Utils::remove_if().
double pdal::LasHeader::scaleX () const
Get scale factor for X coordinate.
Definition at line 259 of file LasHeader.hpp.
Referenced by pdal::LasReader::loadPoint(), pdal::LasReader::loadPointV10(), pdal::LasReader::loadPointV14(), and TEST().
double pdal::LasHeader::scaleY () const
Get scale factor for Y coordinate.
Definition at line 263 of file LasHeader.hpp.
Referenced by pdal::LasReader::loadPoint(), pdal::LasReader::loadPointV10(), pdal::LasReader::loadPointV14(), and TEST().
double pdal::LasHeader::scaleZ () const
Get scale factor for Z coordinate.
Definition at line 267 of file LasHeader.hpp.
Referenced by pdal::LasReader::loadPoint(), pdal::LasReader::loadPointV10(), pdal::LasReader::loadPointV14(), and TEST().
void pdal::LasHeader::setBounds (const BOX3D & bounds)
Definition at line 314 of file LasHeader.hpp.
void pdal::LasHeader::setCompressed (bool b)
Sets whether or not the points are compressed.
Definition at line 359 of file LasHeader.hpp.
References b.
Referenced by pdal::LasWriter::initialize(), and pdal::operator>>().
void pdal::LasHeader::setCompressionInfo (std::string const & info)
Definition at line 376 of file LasHeader.hpp.
void pdal::LasHeader::setCreationDOY (uint16_t v)
Set day of year of file creation date.
Exceptions
std::out_of_range - given value is higher than number 366.
Definition at line 179 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setCreationYear (uint16_t v)
Get year of file creation date.
Exceptions
std::out_of_range - given value is higher than number 9999.
Definition at line 188 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setEVlrCount (uint32_t count)
Definition at line 370 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setEVlrOffset (uint64_t offset)
Definition at line 366 of file LasHeader.hpp.
void pdal::LasHeader::SetFileSignature (std::string const & v)
Set ASPRS LAS file signature. The only value allowed as file signature is "LASF", defined as FileSignature constant.
Exceptions
std::invalid_argument - if invalid signature given.
Parameters
v - string contains file signature, at least 4-bytes long with "LASF" as first four bytes.
void pdal::LasHeader::setFileSourceId (uint16_t v)
Set file source identifier.
Parameters
v - should be set to a value between 1 and 65535.
Exceptions
No throw
Definition at line 97 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setGlobalEncoding (uint16_t globalEncoding)
Definition at line 102 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setLog (LogPtr log)
Definition at line 387 of file LasHeader.hpp.
References setup::log.
void pdal::LasHeader::setOffset (double x, double y, double z)
Set values of X, Y and Z coordinates offset.
void pdal::LasHeader::setPointCount (uint64_t pointCount)
Set the number of points.
Parameters
pointCount Number of points in the file.
Definition at line 237 of file LasHeader.hpp.
void pdal::LasHeader::setPointCountByReturn (std::size_t index, uint64_t v)
Set values point count by return number.
Parameters
index - Return number.
v - Point count for return number.
Definition at line 246 of file LasHeader.hpp.
void pdal::LasHeader::setPointFormat (uint8_t format)
Set the point format.
Parameters
format Point format
Definition at line 210 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setPointLen (uint16_t v)
Definition at line 229 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setPointOffset (uint32_t offset)
Set number of bytes from the beginning to the first point record.
Parameters
offset - Offset to start of point data.
Definition at line 205 of file LasHeader.hpp.
void pdal::LasHeader::setProjectId (const Uuid & v)
Set project identifier.
Definition at line 111 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setScaling (const Scaling & scaling)
Set values of scale/offset factor for X, Y and Z coordinates.
Definition at line 106 of file LasHeader.cpp.
References pdal::XForm::m_offset, m_offsets, pdal::XForm::m_scale, m_scales, pdal::XForm::XFormComponent::m_val, pdal::Scaling::m_xXform, pdal::Scaling::m_yXform, and pdal::Scaling::m_zXform.
Referenced by pdal::LasWriter::fillHeader(), and pdal::LasWriter::finishOutput().
void pdal::LasHeader::setSoftwareId (std::string const & v)
Set software identifier.
Parameters
v - software identifiers string.
Definition at line 170 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setSrs () private
Definition at line 198 of file LasHeader.cpp.
References pdal::Debug, pdal::Error, findVlr(), pdal::GEOTIFF_DIRECTORY_RECORD_ID, incompatibleSrs(), m_log, m_versionMinor, setSrsFromGeotiff(), setSrsFromWkt(), pdal::TRANSFORM_USER_ID, useWkt(), and pdal::WKT_RECORD_ID.
Referenced by pdal::operator>>().
void pdal::LasHeader::setSrsFromGeotiff () private
Definition at line 288 of file LasHeader.cpp.
References pdal::LasVLR::data(), pdal::LasVLR::dataLen(), pdal::SpatialReference::empty(), findVlr(), pdal::GEOTIFF_ASCII_RECORD_ID, pdal::GEOTIFF_DIRECTORY_RECORD_ID, pdal::GEOTIFF_DOUBLES_RECORD_ID, pdal::LasVLR::isEmpty(), m_srs, pdal::GeotiffSrs::srs(), and pdal::TRANSFORM_USER_ID.
Referenced by setSrs().
void pdal::LasHeader::setSrsFromWkt () private
Definition at line 268 of file LasHeader.cpp.
References c, pdal::LasVLR::data(), pdal::LasVLR::dataLen(), findVlr(), pdal::LIBLAS_USER_ID, m_srs, pdal::SpatialReference::set(), pdal::TRANSFORM_USER_ID, and pdal::WKT_RECORD_ID.
Referenced by setSrs().
void pdal::LasHeader::setSummary (const LasSummaryData & summary)
Definition at line 90 of file LasHeader.cpp.
References pdal::LasSummaryData::getBounds(), pdal::LasSummaryData::getReturnCount(), pdal::LasSummaryData::getTotalNumPoints(), m_bounds, m_pointCount, m_pointCountByReturn, and RETURN_COUNT.
Referenced by pdal::LasWriter::finishOutput().
void pdal::LasHeader::setSystemId (std::string const & v)
Set system identifier.
Parameters
v - system identifiers string.
Definition at line 159 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setVersionMinor (uint8_t v)
Set minor component of version of LAS format.
Exceptions
std::out_of_range - invalid value given.
Parameters
v - value between eVersionMinorMin and eVersionMinorMax.
Definition at line 127 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setVlrCount (uint32_t vlrCount)
Definition at line 362 of file LasHeader.hpp.
Referenced by pdal::LasWriter::fillHeader().
void pdal::LasHeader::setVlrOffset (uint16_t offset)
Definition at line 196 of file LasHeader.hpp.
Referenced by pdal::LasWriter::prepOutput().
std::string pdal::LasHeader::softwareId () const
Get software identifier. Default value is "libLAS 1.0", specified as the SoftwareIdentifier constant.
Definition at line 165 of file LasHeader.hpp.
SpatialReference pdal::LasHeader::srs () const
Definition at line 378 of file LasHeader.hpp.
Referenced by pdal::nitfwrap::NitfWrap::verifyLas().
std::string pdal::LasHeader::systemId () const
Get system identifier. Default value is "libLAS" specified as the SystemIdentifier constant.
Parameters
pad - if true the returned string is padded right with spaces and its length is 32 bytes, if false (default) no padding occurs and length of the returned string is <= 32 bytes.
Returns
value of system identifier field.
Definition at line 154 of file LasHeader.hpp.
Dimension::IdList pdal::LasHeader::usedDims () const
Definition at line 173 of file LasHeader.cpp.
References Blue, GpsTime, Green, hasColor(), hasInfrared(), hasTime(), Intensity, Red, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by pdal::LasWriter::prepared().
bool pdal::LasHeader::useWkt () const
Definition at line 347 of file LasHeader.hpp.
Referenced by setSrs().
bool pdal::LasHeader::valid () const
Definition at line 141 of file LasHeader.cpp.
References FILE_SIGNATURE, m_createDOY, m_fileSig, and m_versionMinor.
Referenced by TEST().
bool pdal::LasHeader::versionAtLeast (uint8_t major, uint8_t minor) const
Determine if the header is for a LAS file version of at least a certain level.
Parameters
major - Major version.
minor - Minor version.
Returns
Whether the version meets the criteria.
Definition at line 138 of file LasHeader.hpp.
Referenced by pdal::LasWriter::addMetadataVlr(), pdal::LasWriter::addPipelineVlr(), pdal::LasWriter::addSpatialRefVlrs(), pdal::LasWriter::addVlr(), pdal::LasWriter::fillHeader(), pdal::operator<<(), pdal::operator>>(), and pdal::LasWriter::readyLazPerfCompression().
bool pdal::LasHeader::versionEquals (uint8_t major, uint8_t minor) const
Determine if the header is for a particular LAS file version.
Parameters
major - Major version.
minor - Minor version.
Returns
Whether the version meets the criteria.
Definition at line 145 of file LasHeader.hpp.
Referenced by pdal::operator<<().
uint8_t pdal::LasHeader::versionMajor () const
Get the LAS major version.
Returns
LAS major version
Definition at line 116 of file LasHeader.hpp.
Referenced by pdal::operator>>(), TEST(), and test_a_format().
uint8_t pdal::LasHeader::versionMinor () const
Get minor component of version of LAS format.
Returns
Valid values are 0, 1, 2, 3.
Definition at line 121 of file LasHeader.hpp.
Referenced by TEST(), and test_a_format().
uint32_t pdal::LasHeader::vlrCount () const
Definition at line 364 of file LasHeader.hpp.
Referenced by TEST().
uint16_t pdal::LasHeader::vlrOffset () const
Get number of bytes of generic verion of public header block storage. Standard version of the public header block is 227 bytes long.
Definition at line 193 of file LasHeader.hpp.
Referenced by TEST().
const VlrList& pdal::LasHeader::vlrs () const
Definition at line 389 of file LasHeader.hpp.
References pdal::operator<<(), pdal::operator>>(), and PDAL_DLL.
Referenced by TEST().
Friends And Related Function Documentation
OLeStream& operator<< (OLeStream & out, const LasHeader & h) friend
Definition at line 407 of file LasHeader.cpp.
std::ostream& operator<< (std::ostream & ostr, const LasHeader & h) friend
Definition at line 458 of file LasHeader.cpp.
PDAL_DLL friend ILeStream& operator>> (ILeStream & in, LasHeader & h) friend
Definition at line 326 of file LasHeader.cpp.
Member Data Documentation
const std::string pdal::LasHeader::FILE_SIGNATURE static
Definition at line 71 of file LasHeader.hpp.
Referenced by pdal::operator>>(), and valid().
const size_t pdal::LasHeader::LEGACY_RETURN_COUNT = 5 static
Definition at line 69 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
BOX3D pdal::LasHeader::m_bounds private
Definition at line 418 of file LasHeader.hpp.
Referenced by pdal::operator>>(), and setSummary().
std::string pdal::LasHeader::m_compressionInfo private
Definition at line 419 of file LasHeader.hpp.
uint16_t pdal::LasHeader::m_createDOY private
Definition at line 404 of file LasHeader.hpp.
Referenced by LasHeader(), pdal::operator<<(), pdal::operator>>(), and valid().
uint16_t pdal::LasHeader::m_createYear private
Definition at line 405 of file LasHeader.hpp.
Referenced by LasHeader(), pdal::operator<<(), and pdal::operator>>().
uint32_t pdal::LasHeader::m_eVlrCount private
Definition at line 417 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
uint64_t pdal::LasHeader::m_eVlrOffset private
Definition at line 416 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
VlrList pdal::LasHeader::m_eVlrs private
Definition at line 423 of file LasHeader.hpp.
Referenced by removeVLR().
std::string pdal::LasHeader::m_fileSig private
Definition at line 397 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and valid().
uint16_t pdal::LasHeader::m_globalEncoding private
Definition at line 399 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
bool pdal::LasHeader::m_isCompressed private
Definition at line 415 of file LasHeader.hpp.
Referenced by pdal::operator<<().
LogPtr pdal::LasHeader::m_log private
Definition at line 420 of file LasHeader.hpp.
Referenced by setSrs().
std::array<double, 3> pdal::LasHeader::m_offsets private
Definition at line 414 of file LasHeader.hpp.
Referenced by LasHeader(), pdal::operator<<(), pdal::operator>>(), and setScaling().
uint64_t pdal::LasHeader::m_pointCount private
Definition at line 411 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and setSummary().
std::array<uint64_t, RETURN_COUNT> pdal::LasHeader::m_pointCountByReturn private
Definition at line 412 of file LasHeader.hpp.
Referenced by LasHeader(), pdal::operator<<(), pdal::operator>>(), and setSummary().
uint8_t pdal::LasHeader::m_pointFormat private
Definition at line 409 of file LasHeader.hpp.
Referenced by LasHeader(), pdal::operator<<(), and pdal::operator>>().
uint16_t pdal::LasHeader::m_pointLen private
Definition at line 410 of file LasHeader.hpp.
Referenced by LasHeader(), pdal::operator<<(), and pdal::operator>>().
uint32_t pdal::LasHeader::m_pointOffset private
Definition at line 407 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
Uuid pdal::LasHeader::m_projectUuid private
Definition at line 400 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
std::array<double, 3> pdal::LasHeader::m_scales private
Definition at line 413 of file LasHeader.hpp.
Referenced by LasHeader(), pdal::operator<<(), pdal::operator>>(), and setScaling().
std::string pdal::LasHeader::m_softwareId private
Definition at line 403 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
uint16_t pdal::LasHeader::m_sourceId private
Definition at line 398 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
SpatialReference pdal::LasHeader::m_srs private
Definition at line 421 of file LasHeader.hpp.
Referenced by setSrsFromGeotiff(), and setSrsFromWkt().
std::string pdal::LasHeader::m_systemId private
Definition at line 402 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
uint8_t pdal::LasHeader::m_versionMinor private
Definition at line 401 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), setSrs(), and valid().
uint32_t pdal::LasHeader::m_vlrCount private
Definition at line 408 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
uint16_t pdal::LasHeader::m_vlrOffset private
Definition at line 406 of file LasHeader.hpp.
Referenced by pdal::operator<<(), and pdal::operator>>().
VlrList pdal::LasHeader::m_vlrs private
Definition at line 422 of file LasHeader.hpp.
Referenced by findVlr(), pdal::operator>>(), and removeVLR().
const size_t pdal::LasHeader::RETURN_COUNT = 15 static
Definition at line 70 of file LasHeader.hpp.
Referenced by pdal::operator<<(), pdal::operator>>(), and setSummary().
The documentation for this class was generated from the following files:
pdal/io/LasHeader.hpp
pdal/io/LasHeader.cpp