PDAL: OCITest Class Reference
OCITest Class Reference
Protected Member Functions
virtual void SetUp ()
void connect ()
void run (std::string sql)
virtual void TearDown ()
void cleanup ()
Protected Attributes
Connection m_connection
Detailed Description
Definition at line 134 of file OCITest.cpp.
Member Function Documentation
void OCITest::cleanup () protected
Definition at line 178 of file OCITest.cpp.
References anonymous_namespace{OCITest.cpp}::baseTableName(), and anonymous_namespace{OCITest.cpp}::blockTableName().
void OCITest::connect () protected
Definition at line 152 of file OCITest.cpp.
References pdal::connect(), and anonymous_namespace{OCITest.cpp}::connectString().
void OCITest::run (std::string sql) protected
Definition at line 166 of file OCITest.cpp.
virtual void OCITest::SetUp () protected virtual
Definition at line 137 of file OCITest.cpp.
References anonymous_namespace{OCITest.cpp}::baseTableName(), anonymous_namespace{OCITest.cpp}::blockTableName(), and pdal::connect().
virtual void OCITest::TearDown () protected virtual
Definition at line 174 of file OCITest.cpp.
Member Data Documentation
Connection OCITest::m_connection protected
Definition at line 172 of file OCITest.cpp.
The documentation for this class was generated from the following file:
pdal/plugins/oci/test/OCITest.cpp