PDAL: pdal::GeotiffSrs Class Reference
pdal::GeotiffSrs Class Reference
#include <GeotiffSupport.hpp>
Public Member Functions
GeotiffSrs (const std::vector< uint8_t > &directoryRec, const std::vector< uint8_t > &doublesRec, const std::vector< uint8_t > &asciiRec)
SpatialReference srs () const
Private Attributes
SpatialReference m_srs
Detailed Description
Definition at line 42 of file GeotiffSupport.hpp.
Constructor & Destructor Documentation
pdal::GeotiffSrs::GeotiffSrs (const std::vector< uint8_t > & directoryRec, const std::vector< uint8_t > & doublesRec, const std::vector< uint8_t > & asciiRec)
Definition at line 81 of file GeotiffSupport.cpp.
References pdal::GEOTIFF_ASCII_RECORD_ID, pdal::GEOTIFF_DIRECTORY_RECORD_ID, pdal::GEOTIFF_DOUBLES_RECORD_ID, and GTIFGetOGISDefn().
Member Function Documentation
SpatialReference pdal::GeotiffSrs::srs () const
Definition at line 48 of file GeotiffSupport.hpp.
References m_srs.
Referenced by pdal::GeotiffTags::error::error(), and pdal::LasHeader::setSrsFromGeotiff().
Member Data Documentation
SpatialReference pdal::GeotiffSrs::m_srs private
Definition at line 51 of file GeotiffSupport.hpp.
Referenced by srs().
The documentation for this class was generated from the following files:
pdal/io/GeotiffSupport.hpp
pdal/io/GeotiffSupport.cpp