PDAL: pdal::nitfwrap::NitfWrap Class Reference
pdal::nitfwrap::NitfWrap Class Reference
#include <NitfWrap.hpp>
Public Member Functions
NitfWrap (std::vector< std::string > &args)
Private Member Functions
bool parseArgs (std::vector< std::string > &args)
void unwrap ()
void verify (BOX3D &bounds)
bool verifyLas (ILeStream &in, BOX3D &bounds, bool &compressed)
bool verifyBpf (ILeStream &in, BOX3D &bounds)
Private Attributes
std::string m_inputFile
std::string m_outputFile
NitfFileWriter m_nitfWriter
bool m_unwrap
Detailed Description
Definition at line 17 of file NitfWrap.hpp.
Constructor & Destructor Documentation
pdal::nitfwrap::NitfWrap::NitfWrap (std::vector< std::string > & args)
Definition at line 84 of file NitfWrap.cpp.
References pdal::NitfFileWriter::initialize(), m_inputFile, m_nitfWriter, m_outputFile, m_unwrap, parseArgs(), pdal::NitfFileWriter::setBounds(), pdal::NitfFileWriter::setFilename(), unwrap(), verify(), pdal::NitfFileWriter::wrapData(), and pdal::NitfFileWriter::write().
Member Function Documentation
bool pdal::nitfwrap::NitfWrap::parseArgs (std::vector< std::string > & args) private
Definition at line 168 of file NitfWrap.cpp.
References pdal::ProgramArgs::add(), pdal::NitfFileWriter::addArgs(), pdal::FileUtils::fileExists(), pdal::arg_error::m_error, m_inputFile, m_nitfWriter, m_outputFile, m_unwrap, pdal::nitfwrap::anonymous_namespace{NitfWrap.cpp}::outputHelp(), pdal::ProgramArgs::parse(), pdal::Arg::setOptionalPositional(), pdal::Arg::setPositional(), and pdal::FileUtils::stem().
Referenced by NitfWrap().
void pdal::nitfwrap::NitfWrap::unwrap () private
Definition at line 105 of file NitfWrap.cpp.
References pdal::NitfFileReader::close(), pdal::FileUtils::closeFile(), pdal::FileUtils::createFile(), pdal::NitfFileReader::getLasOffset(), m_inputFile, m_outputFile, pdal::NitfFileReader::open(), pdal::FileUtils::openFile(), pdal::IStreamMarker::rewind(), pdal::Dimension::size(), pdal::FileUtils::stem(), verifyBpf(), and verifyLas().
Referenced by NitfWrap().
void pdal::nitfwrap::NitfWrap::verify (BOX3D & bounds) private
Definition at line 210 of file NitfWrap.cpp.
References m_inputFile, pdal::FileUtils::openFile(), pdal::IStreamMarker::rewind(), verifyBpf(), and verifyLas().
Referenced by NitfWrap().
bool pdal::nitfwrap::NitfWrap::verifyBpf (ILeStream & in, BOX3D & bounds) private
Definition at line 253 of file NitfWrap.cpp.
References pdal::BpfHeader::m_coordId, pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::BOX3D::minz, pdal::BpfHeader::read(), pdal::BpfHeader::readDimensions(), pdal::gdal::reprojectBounds(), pdal::BpfHeader::setLog(), pdal::Utils::toString(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by unwrap(), and verify().
bool pdal::nitfwrap::NitfWrap::verifyLas (ILeStream & in, BOX3D & bounds, bool & compressed) private
Definition at line 234 of file NitfWrap.cpp.
References pdal::LasHeader::compressed(), pdal::LasHeader::getBounds(), pdal::SpatialReference::getWKT(), pdal::gdal::reprojectBounds(), and pdal::LasHeader::srs().
Referenced by unwrap(), and verify().
Member Data Documentation
std::string pdal::nitfwrap::NitfWrap::m_inputFile private
Definition at line 23 of file NitfWrap.hpp.
Referenced by NitfWrap(), parseArgs(), unwrap(), and verify().
NitfFileWriter pdal::nitfwrap::NitfWrap::m_nitfWriter private
Definition at line 25 of file NitfWrap.hpp.
Referenced by NitfWrap(), and parseArgs().
std::string pdal::nitfwrap::NitfWrap::m_outputFile private
Definition at line 24 of file NitfWrap.hpp.
Referenced by NitfWrap(), parseArgs(), and unwrap().
bool pdal::nitfwrap::NitfWrap::m_unwrap private
Definition at line 26 of file NitfWrap.hpp.
Referenced by NitfWrap(), and parseArgs().
The documentation for this class was generated from the following files:
pdal/tools/nitfwrap/NitfWrap.hpp
pdal/tools/nitfwrap/NitfWrap.cpp