PDAL: pdal::PipelineReaderJSON Class Reference
pdal::PipelineReaderJSON Class Reference
#include <PipelineReaderJSON.hpp>
Public Member Functions
PipelineReaderJSON (PipelineManager &)
void parsePipeline (Json::Value &)
Private Types
typedef std::map< std::string, Stage * > TagMap
Private Member Functions
void readPipeline (const std::string &filename)
void readPipeline (std::istream &input)
std::string extractType (Json::Value &node)
std::string extractFilename (Json::Value &node)
std::string extractTag (Json::Value &node, TagMap &tags)
std::vector< Stage * > extractInputs (Json::Value &node, TagMap &tags)
Options extractOptions (Json::Value &node)
void handleInputTag (const std::string &tag, const TagMap &tags, std::vector< Stage * > &inputs)
PipelineReaderJSON & operator= (const PipelineReaderJSON &)
PipelineReaderJSON (const PipelineReaderJSON &)
Private Attributes
PipelineManager & m_manager
std::string m_inputJSONFile
Friends
class PipelineManager
Detailed Description
Definition at line 54 of file PipelineReaderJSON.hpp.
Member Typedef Documentation
typedef std::map<std::string, Stage *> pdal::PipelineReaderJSON::TagMap private
Definition at line 63 of file PipelineReaderJSON.hpp.
Constructor & Destructor Documentation
pdal::PipelineReaderJSON::PipelineReaderJSON (PipelineManager & manager)
Definition at line 53 of file PipelineReaderJSON.cpp.
pdal::PipelineReaderJSON::PipelineReaderJSON (const PipelineReaderJSON &) private
Member Function Documentation
std::string pdal::PipelineReaderJSON::extractFilename (Json::Value & node) private
Definition at line 207 of file PipelineReaderJSON.cpp.
Referenced by parsePipeline().
std::vector< Stage * > pdal::PipelineReaderJSON::extractInputs (Json::Value & node, TagMap & tags) private
Definition at line 277 of file PipelineReaderJSON.cpp.
References handleInputTag().
Referenced by parsePipeline().
Options pdal::PipelineReaderJSON::extractOptions (Json::Value & node) private
Definition at line 310 of file PipelineReaderJSON.cpp.
References pdal::Options::add(), pdal::PluginManager::loadPlugin(), and pdal::Dimension::name().
Referenced by parsePipeline().
std::string pdal::PipelineReaderJSON::extractTag (Json::Value & node, TagMap & tags) private
Definition at line 231 of file PipelineReaderJSON.cpp.
References pdal::Stage::parseTagName().
Referenced by parsePipeline().
std::string pdal::PipelineReaderJSON::extractType (Json::Value & node) private
Definition at line 183 of file PipelineReaderJSON.cpp.
References pdal::Dimension::type().
Referenced by parsePipeline().
void pdal::PipelineReaderJSON::handleInputTag (const std::string & tag, const TagMap & tags, std::vector< Stage * > & inputs) private
Definition at line 265 of file PipelineReaderJSON.cpp.
Referenced by extractInputs().
PipelineReaderJSON& pdal::PipelineReaderJSON::operator= (const PipelineReaderJSON &) private
void pdal::PipelineReaderJSON::parsePipeline (Json::Value & tree)
Definition at line 58 of file PipelineReaderJSON.cpp.
References pdal::Options::add(), extractFilename(), extractInputs(), extractOptions(), extractTag(), extractType(), pdal::FileUtils::glob(), m_manager, pdal::PipelineManager::makeFilter(), pdal::PipelineManager::makeReader(), pdal::PipelineManager::makeWriter(), pdal::Stage::setInput(), pdal::Utils::startsWith(), and pdal::Dimension::type().
Referenced by readPipeline().
void pdal::PipelineReaderJSON::readPipeline (const std::string & filename) private
Definition at line 157 of file PipelineReaderJSON.cpp.
References pdal::Utils::closeFile(), m_inputJSONFile, and pdal::Utils::openFile().
Referenced by pdal::PipelineManager::readPipeline().
void pdal::PipelineReaderJSON::readPipeline (std::istream & input) private
Definition at line 139 of file PipelineReaderJSON.cpp.
References parsePipeline().
Friends And Related Function Documentation
friend class PipelineManager friend
Definition at line 56 of file PipelineReaderJSON.hpp.
Member Data Documentation
std::string pdal::PipelineReaderJSON::m_inputJSONFile private
Definition at line 76 of file PipelineReaderJSON.hpp.
Referenced by readPipeline().
PipelineManager& pdal::PipelineReaderJSON::m_manager private
Definition at line 75 of file PipelineReaderJSON.hpp.
Referenced by parsePipeline().
The documentation for this class was generated from the following files:
pdal/pdal/PipelineReaderJSON.hpp
pdal/pdal/PipelineReaderJSON.cpp