PDAL: pdal::Options Class Reference
pdal::Options Class Reference
#include <Options.hpp>
Public Member Functions
Options ()
Options (const Option &opt)
void add (const Option &option)
void add (const Options &options)
void addConditional (const Option &option)
void addConditional (const Options &option)
void remove (const Option &option)
void replace (const Option &option)
void toMetadata (MetadataNode &parent) const
template<typename T >
void add (const std::string &name, T value)
void add (const std::string &name, const std::string &value)
void add (const std::string &name, const bool &value)
template<typename T >
void replace (const std::string &name, T value)
void replace (const std::string &name, const std::string &value)
void replace (const std::string &name, const bool &value)
StringList getValues (const std::string &name) const
StringList getKeys () const
std::vector< Option > getOptions (std::string const &name="") const
StringList toCommandLine () const
Static Public Member Functions
static Options fromFile (const std::string &filename, bool throwOnOpenError=true)
Static Private Member Functions
static Options fromJsonFile (const std::string &filename, const std::string &s)
static Options fromCmdlineFile (const std::string &filename, const std::string &s)
Private Attributes
std::multimap< std::string, Option > m_options
Detailed Description
Definition at line 122 of file Options.hpp.
Constructor & Destructor Documentation
pdal::Options::Options ()
Definition at line 125 of file Options.hpp.
pdal::Options::Options (const Option & opt)
Definition at line 128 of file Options.hpp.
References option().
Member Function Documentation
void pdal::Options::add (const Option & option)
Definition at line 81 of file Options.cpp.
References pdal::Option::getName(), and pdal::Option::nameValid().
Referenced by pdal::anonymous_namespace{CpdFilterTest.cpp}::checkNoThrow(), Support::checkXYZ(), GDALReaderTypeTest::compare(), compare(), anonymous_namespace{NitfWriterTest.cpp}::compare_contents(), compareFiles(), compareTextLas(), compareTextLasStreaming(), defaultRxpReaderOptions(), anonymous_namespace{SortFilterTest.cpp}::doSort(), pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::DensityKernel::execute(), pdal::RandomKernel::execute(), pdal::GroundKernel::execute(), pdal::PipelineReaderJSON::extractOptions(), fileHasSrs(), fileIsCompressed(), fromCmdlineFile(), fromJsonFile(), getBytes(), getDbOptions(), getReaderOptions(), getWriterOptions(), pdal::TIndexReader::initialize(), main(), pdal::InfoKernel::makePipeline(), makeReaderOptions(), makeWriterOptions(), pdal::TIndexKernel::mergeFile(), pdal::anonymous_namespace{IcpFilterTest.cpp}::newReader(), pdal::anonymous_namespace{CpdFilterTest.cpp}::newReader(), pdal::anonymous_namespace{OptechReaderTest.cpp}::OptechReaderTest::OptechReaderTest(), anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite(), pdal::PipelineReaderJSON::parsePipeline(), readData(), readerOptions(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), pdal::TransformationFilterTest::SetUp(), pdal::MatlabWriterTest::SetUp(), pdal::InfoKernel::setup(), pdal::PipelineManager::stageOptions(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), streamTest(), pdal::anonymous_namespace{TerrasolidReaderTest.cpp}::TerrasolidReaderTest::TerrasolidReaderTest(), TEST(), pdal::TEST(), test_a_format(), pdal::TEST_F(), TEST_F(), anonymous_namespace{BPFTest.cpp}::test_file_type_stream(), anonymous_namespace{BPFTest.cpp}::test_file_type_view(), test_filter(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed(), testGrid(), testOverlay(), testReadWrite(), anonymous_namespace{GreyhoundReaderTest.cpp}::toOptions(), writeData(), and writerOptions().
void pdal::Options::add (const Options & options)
Definition at line 88 of file Options.cpp.
References m_options.
template<typename T > void pdal::Options::add (const std::string & name, T value)
Definition at line 167 of file Options.hpp.
void pdal::Options::add (const std::string & name, const std::string & value)
Definition at line 173 of file Options.hpp.
void pdal::Options::add (const std::string & name, const bool & value)
Definition at line 179 of file Options.hpp.
void pdal::Options::addConditional (const Option & option)
Definition at line 94 of file Options.cpp.
References pdal::Option::getName(), and pdal::Option::nameValid().
Referenced by pdal::Stage::addConditionalOptions(), pdal::Stage::handleOptions(), and pdal::PipelineManager::stageOptions().
void pdal::Options::addConditional (const Options & option)
Definition at line 102 of file Options.cpp.
References m_options.
Options pdal::Options::fromCmdlineFile (const std::string & filename, const std::string & s) static private
Definition at line 218 of file Options.cpp.
References add(), option(), pdal::Option::parse(), and pdal::Utils::simpleWordexp().
Options pdal::Options::fromFile (const std::string & filename, bool throwOnOpenError = true) static
Definition at line 156 of file Options.cpp.
References pdal::Utils::extractSpaces(), pdal::FileUtils::fileExists(), and pdal::FileUtils::readFileIntoString().
Referenced by pdal::Stage::handleOptions().
Options pdal::Options::fromJsonFile (const std::string & filename, const std::string & s) static private
Definition at line 179 of file Options.cpp.
References add(), and pdal::Dimension::name().
StringList pdal::Options::getKeys () const
Definition at line 213 of file Options.hpp.
References pdal::Dimension::name().
std::vector< Option > pdal::Options::getOptions (std::string const & name = "") const
Definition at line 115 of file Options.cpp.
Referenced by pdal::Stage::addConditionalOptions(), pdal::Stage::addOptions(), and pdal::Stage::removeOptions().
StringList pdal::Options::getValues (const std::string & name) const
Definition at line 203 of file Options.hpp.
Referenced by pdal::Stage::handleOptions().
void pdal::Options::remove (const Option & option)
Definition at line 109 of file Options.cpp.
References pdal::Option::getName().
Referenced by pdal::Stage::handleOptions().
void pdal::Options::replace (const Option & option)
Definition at line 139 of file Options.hpp.
References option().
Referenced by pdal::PipelineManager::makeReader(), pdal::PipelineManager::makeWriter(), and TEST().
template<typename T > void pdal::Options::replace (const std::string & name, T value)
Definition at line 185 of file Options.hpp.
void pdal::Options::replace (const std::string & name, const std::string & value)
Definition at line 191 of file Options.hpp.
void pdal::Options::replace (const std::string & name, const bool & value)
Definition at line 197 of file Options.hpp.
StringList pdal::Options::toCommandLine () const
Convert options to a string list appropriate for parsing with ProgramArgs.
Returns
List of options as argument strings.
Definition at line 144 of file Options.cpp.
References pdal::Option::toArg().
Referenced by pdal::Stage::handleOptions(), and pdal::TEST().
void pdal::Options::toMetadata (MetadataNode & parent) const
Definition at line 145 of file Options.hpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addWithType(), and pdal::Utils::iequals().
Referenced by pdal::Stage::serialize().
Member Data Documentation
std::multimap<std::string, Option> pdal::Options::m_options private
Definition at line 231 of file Options.hpp.
Referenced by add(), and addConditional().
The documentation for this class was generated from the following files:
pdal/pdal/Options.hpp
pdal/pdal/Options.cpp