PDAL: pdal::plang::Environment Class Reference
pdal::plang::Environment Class Reference
#include <Environment.hpp>
Public Member Functions
Environment ()
~Environment ()
void set_stdout (std::ostream *ostr)
void reset_stdout ()
void execute (Script &script)
Static Public Member Functions
static EnvironmentPtr get ()
static int getPythonDataType (Dimension::Type t)
Private Attributes
Redirector m_redirector
Detailed Description
Definition at line 67 of file Environment.hpp.
Constructor & Destructor Documentation
pdal::plang::Environment::Environment ()
Definition at line 96 of file Environment.cpp.
References pdal::plang::Redirector::init(), m_redirector, and pdal::plang::redirector_init().
Referenced by get().
pdal::plang::Environment::~Environment ()
Definition at line 127 of file Environment.cpp.
Member Function Documentation
void pdal::plang::Environment::execute (Script & script)
Definition at line 77 of file Environment.hpp.
EnvironmentPtr pdal::plang::Environment::get () static
Definition at line 83 of file Environment.cpp.
References Environment(), and pdal::plang::g_environment.
Referenced by pdal::PythonFilter::done(), pdal::plang::Invocation::Invocation(), pdal::PythonFilter::ready(), PythonFilterTest::SetUp(), PredicateFilterTest::SetUp(), and TEST_P().
int pdal::plang::Environment::getPythonDataType (Dimension::Type t) static
Definition at line 315 of file Environment.cpp.
Referenced by pdal::plang::Invocation::extractResult(), and pdal::plang::Invocation::insertArgument().
void pdal::plang::Environment::reset_stdout ()
Definition at line 139 of file Environment.cpp.
References m_redirector, and pdal::plang::Redirector::reset_stdout().
void pdal::plang::Environment::set_stdout (std::ostream * ostr)
Definition at line 133 of file Environment.cpp.
References m_redirector, and pdal::plang::Redirector::set_stdout().
Member Data Documentation
Redirector pdal::plang::Environment::m_redirector private
Definition at line 84 of file Environment.hpp.
Referenced by Environment(), reset_stdout(), and set_stdout().
The documentation for this class was generated from the following files:
pdal/plugins/python/plang/Environment.hpp
pdal/plugins/python/plang/Environment.cpp