PDAL: pdal::DeltaKernel Class Reference
pdal::DeltaKernel Class Reference
#include <DeltaKernel.hpp>
Public Member Functions
std::string getName () const
int execute ()
int run (const StringList &cmdArgs, LogPtr &log)
std::string getShortName () const
virtual void validateSwitches (ProgramArgs &args)
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
Protected Member Functions
Stage & makeReader (const std::string &inputFile, std::string driver)
Stage & makeReader (const std::string &inputFile, std::string driver, Options options)
Stage & makeFilter (const std::string &driver, Stage &parent)
Stage & makeFilter (const std::string &driver, Stage &parent, Options options)
Stage & makeFilter (const std::string &driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver, Options options)
virtual bool isStagePrefix (const std::string &stageType)
Protected Attributes
LogPtr m_log
PipelineManager m_manager
std::string m_driverOverride
Private Member Functions
DeltaKernel ()
void addSwitches (ProgramArgs &args)
PointViewPtr loadSet (const std::string &filename, PointTable &table)
MetadataNode dump (PointViewPtr &srcView, PointViewPtr &candView, KD3Index &index, DimIndexMap &dims)
MetadataNode dumpDetail (PointViewPtr &srcView, PointViewPtr &candView, KD3Index &index, DimIndexMap &dims)
void accumulate (DimIndex &d, double v)
Private Attributes
std::string m_sourceFile
std::string m_candidateFile
bool m_detail
bool m_allDims
Detailed Description
Definition at line 69 of file DeltaKernel.hpp.
Constructor & Destructor Documentation
pdal::DeltaKernel::DeltaKernel () private
Definition at line 50 of file DeltaKernel.cpp.
Member Function Documentation
void pdal::DeltaKernel::accumulate (DimIndex & d, double v) private
Definition at line 176 of file DeltaKernel.cpp.
References pdal::DimIndex::m_avg, pdal::DimIndex::m_cnt, pdal::DimIndex::m_max, and pdal::DimIndex::m_min.
Referenced by dump().
void pdal::DeltaKernel::addSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 54 of file DeltaKernel.cpp.
References pdal::ProgramArgs::add(), m_allDims, m_candidateFile, m_detail, m_sourceFile, and pdal::Arg::setPositional().
static void* pdal::DeltaKernel::create () static
static int32_t pdal::DeltaKernel::destroy (void *) static
MetadataNode pdal::DeltaKernel::dump (PointViewPtr & srcView, PointViewPtr & candView, KD3Index & index, DimIndexMap & dims) private
Definition at line 139 of file DeltaKernel.cpp.
References accumulate(), pdal::MetadataNode::add(), pdal::Dimension::id(), pdal::DimIndex::m_avg, pdal::DimIndex::m_candId, m_candidateFile, pdal::DimIndex::m_max, pdal::DimIndex::m_min, pdal::DimIndex::m_name, m_sourceFile, pdal::DimIndex::m_srcId, and pdal::KD3Index::neighbor().
Referenced by execute().
MetadataNode pdal::DeltaKernel::dumpDetail (PointViewPtr & srcView, PointViewPtr & candView, KD3Index & index, DimIndexMap & dims) private
Definition at line 185 of file DeltaKernel.cpp.
References pdal::MetadataNode::add(), pdal::Dimension::id(), pdal::DimIndex::m_candId, pdal::DimIndex::m_name, pdal::DimIndex::m_srcId, and pdal::KD3Index::neighbor().
Referenced by execute().
int pdal::DeltaKernel::execute () virtual
Implements pdal::Kernel.
Definition at line 78 of file DeltaKernel.cpp.
References pdal::KDIndex< DIM >::build(), pdal::PointLayout::dimName(), pdal::PointLayout::dims(), dump(), dumpDetail(), pdal::BasePointTable::layout(), loadSet(), m_allDims, pdal::DimIndex::m_candId, m_candidateFile, m_detail, pdal::DimIndex::m_name, m_sourceFile, pdal::DimIndex::m_srcId, pdal::Dimension::name(), pdal::Utils::toJSON(), and pdal::Dimension::Unknown.
std::string pdal::DeltaKernel::getName () const virtual
Implements pdal::Kernel.
Definition at line 48 of file DeltaKernel.cpp.
References pdal::PluginInfo::name.
std::string pdal::Kernel::getShortName () const inherited
Definition at line 67 of file Kernel.hpp.
References pdal::Utils::split2().
Referenced by pdal::Kernel::outputHelp().
bool pdal::Kernel::isStagePrefix (const std::string & stageType) protected virtual inherited
Reimplemented in pdal::PipelineKernel.
Definition at line 58 of file Kernel.cpp.
Referenced by pdal::PipelineKernel::isStagePrefix(), and pdal::Kernel::parseStageOption().
PointViewPtr pdal::DeltaKernel::loadSet (const std::string & filename, PointTable & table) private
Definition at line 67 of file DeltaKernel.cpp.
References pdal::Stage::execute(), pdal::Kernel::m_driverOverride, pdal::Kernel::makeReader(), and pdal::Stage::prepare().
Referenced by execute().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent) protected inherited
Definition at line 320 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent, Options options) protected inherited
Definition at line 326 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeFilter (const std::string & driver) protected inherited
Definition at line 314 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver) protected inherited
Definition at line 301 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::HausdorffKernel::loadSet(), loadSet(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver, Options options) protected inherited
Definition at line 307 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver) protected inherited
Definition at line 333 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
Referenced by pdal::MyKernel::execute(), pdal::PCLKernel::execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver, Options options) protected inherited
Definition at line 340 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
int pdal::Kernel::run (const StringList & cmdArgs, LogPtr & log) inherited
Definition at line 229 of file Kernel.cpp.
References pdal::Kernel::doExecution(), pdal::Kernel::doStartup(), pdal::Kernel::doSwitches(), setup::log, pdal::Kernel::m_log, pdal::Kernel::m_manager, pdal::Kernel::m_showHelp, pdal::Kernel::outputHelp(), pdal::Utils::printError(), and pdal::PipelineManager::setLog().
Referenced by App::execute().
virtual void pdal::Kernel::validateSwitches (ProgramArgs & args) virtual inherited
Reimplemented in pdal::TIndexKernel, pdal::InfoKernel, pdal::PipelineKernel, pdal::MergeKernel, and pdal::SplitKernel.
Definition at line 95 of file Kernel.hpp.
Referenced by pdal::Kernel::innerRun().
Member Data Documentation
bool pdal::DeltaKernel::m_allDims private
Definition at line 95 of file DeltaKernel.hpp.
Referenced by addSwitches(), and execute().
std::string pdal::DeltaKernel::m_candidateFile private
Definition at line 88 of file DeltaKernel.hpp.
Referenced by addSwitches(), dump(), and execute().
bool pdal::DeltaKernel::m_detail private
std::ostream* m_outputStream;
Definition at line 94 of file DeltaKernel.hpp.
Referenced by addSwitches(), and execute().
std::string pdal::Kernel::m_driverOverride protected inherited
Definition at line 105 of file Kernel.hpp.
Referenced by pdal::Kernel::addBasicSwitches(), pdal::MergeKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::DiffKernel::execute(), loadSet(), pdal::InfoKernel::makePipeline(), and pdal::TIndexKernel::mergeFile().
LogPtr pdal::Kernel::m_log protected inherited
Definition at line 103 of file Kernel.hpp.
Referenced by pdal::TIndexKernel::createFeature(), pdal::TIndexKernel::createFile(), pdal::TIndexKernel::createLayer(), pdal::InfoKernel::dumpPoints(), pdal::TranslateKernel::execute(), and pdal::Kernel::run().
PipelineManager pdal::Kernel::m_manager protected inherited
Definition at line 104 of file Kernel.hpp.
Referenced by pdal::Kernel::doSwitches(), pdal::InfoKernel::dump(), pdal::SmoothKernel::execute(), pdal::DensityKernel::execute(), pdal::PipelineKernel::execute(), pdal::TranslateKernel::execute(), pdal::TIndexKernel::getFileInfo(), pdal::TranslateKernel::makeArgPipeline(), pdal::Kernel::makeFilter(), pdal::TranslateKernel::makeJSONPipeline(), pdal::InfoKernel::makePipeline(), pdal::Kernel::makeReader(), pdal::Kernel::makeWriter(), pdal::InfoKernel::run(), pdal::Kernel::run(), and pdal::InfoKernel::setup().
std::string pdal::DeltaKernel::m_sourceFile private
Definition at line 87 of file DeltaKernel.hpp.
Referenced by addSwitches(), dump(), and execute().
The documentation for this class was generated from the following files:
pdal/kernels/DeltaKernel.hpp
pdal/kernels/DeltaKernel.cpp