PDAL: pdal::PointView Class Reference
pdal::PointView Class Reference
#include <PointView.hpp>
Public Member Functions
PointView (const PointView &)=delete
PointView & operator= (const PointView &)=delete
PointView (PointTableRef pointTable)
PointView (PointTableRef pointTable, const SpatialReference &srs)
virtual ~PointView ()
PointViewIter begin ()
PointViewIter end ()
int id () const
point_count_t size () const
bool empty () const
void appendPoint (const PointView &buffer, PointId id)
void append (const PointView &buf)
PointViewPtr makeNew () const
PointRef point (PointId id)
template<class T >
T getFieldAs (Dimension::Id dim, PointId pointIndex) const
void getField (char *pos, Dimension::Id d, Dimension::Type type, PointId id) const
template<typename T >
void setField (Dimension::Id dim, PointId idx, T val)
void setField (Dimension::Id dim, Dimension::Type type, PointId idx, const void *val)
template<typename T >
bool compare (Dimension::Id dim, PointId id1, PointId id2)
bool compare (Dimension::Id dim, PointId id1, PointId id2)
void getRawField (Dimension::Id dim, PointId idx, void *buf) const
void calculateBounds (BOX2D &box) const
void calculateBounds (BOX3D &box) const
void dump (std::ostream &ostr) const
bool hasDim (Dimension::Id id) const
std::string dimName (Dimension::Id id) const
Dimension::IdList dims () const
std::size_t pointSize () const
std::size_t dimSize (Dimension::Id id) const
Dimension::Type dimType (Dimension::Id id) const
DimTypeList dimTypes () const
PointLayoutPtr layout () const
void setSpatialReference (const SpatialReference &spatialRef)
SpatialReference spatialReference () const
void getPackedPoint (const DimTypeList &dims, PointId idx, char *buf) const
void setPackedPoint (const DimTypeList &dims, PointId idx, const char *buf)
char * getPoint (PointId id)
char * getOrAddPoint (PointId id)
void clearTemps ()
MetadataNode toMetadata () const
TriangularMesh * createMesh (const std::string &name)
TriangularMesh * mesh (const std::string &name="")
KD3Index & build3dIndex ()
KD2Index & build2dIndex ()
Static Public Member Functions
static void calculateBounds (const PointViewSet &, BOX2D &box)
static void calculateBounds (const PointViewSet &, BOX3D &box)
Protected Attributes
PointTableRef m_pointTable
std::deque< PointId > m_index
point_count_t m_size
int m_id
std::queue< PointId > m_temps
SpatialReference m_spatialReference
std::map< std::string, std::unique_ptr< TriangularMesh > > m_meshes
std::unique_ptr< KD3Index > m_index3
std::unique_ptr< KD2Index > m_index2
Private Member Functions
template<typename T_IN , typename T_OUT >
bool convertAndSet (Dimension::Id dim, PointId idx, T_IN in)
virtual void setFieldInternal (Dimension::Id dim, PointId idx, const void *buf)
virtual void getFieldInternal (Dimension::Id dim, PointId idx, void *buf) const
template<class T >
T getFieldInternal (Dimension::Id dim, PointId pointIndex) const
PointId getTemp (PointId id)
void freeTemp (PointId id)
Static Private Attributes
static int m_lastId = 0
Friends
class plang::Invocation
class PointIdxRef
struct PointViewLess
Detailed Description
Definition at line 72 of file PointView.hpp.
Constructor & Destructor Documentation
pdal::PointView::PointView (const PointView &) delete
pdal::PointView::PointView (PointTableRef pointTable)
Definition at line 47 of file PointView.cpp.
References m_id, and m_lastId.
pdal::PointView::PointView (PointTableRef pointTable, const SpatialReference & srs)
Definition at line 53 of file PointView.cpp.
References m_id, and m_lastId.
pdal::PointView::~PointView () virtual
Definition at line 60 of file PointView.cpp.
Member Function Documentation
void pdal::PointView::append (const PointView & buf)
Definition at line 97 of file PointView.hpp.
References m_index, size(), and pdal::Dimension::size().
void pdal::PointView::appendPoint (const PointView & buffer, PointId id)
Definition at line 557 of file PointView.hpp.
References pdal::Dimension::id(), and m_index.
Referenced by pdal::CropFilter::crop(), and pdal::DecimationFilter::decimate().
PointViewIter pdal::PointView::begin ()
Definition at line 64 of file PointView.cpp.
Referenced by calculateBounds(), pdal::RandomizeFilter::filter(), and pdal::SortFilter::filter().
KD2Index & pdal::PointView::build2dIndex ()
Definition at line 203 of file PointView.cpp.
References m_index2.
KD3Index & pdal::PointView::build3dIndex ()
Definition at line 188 of file PointView.cpp.
References m_index3.
Referenced by pdal::NormalFilter::filter(), and pdal::GreedyProjection::filter().
void pdal::PointView::calculateBounds (BOX2D & box) const
Returns
a cumulated bounds of all points in the PointView.
embed:rst
.. note::
    This method requires that an `X`, `Y`, and `Z` dimension be
    available, and that it can be casted into a *double* data
    type using the :cpp:func:`pdal::Dimension::applyScaling`
    method. Otherwise, an exception will be thrown.
Definition at line 101 of file PointView.cpp.
References pdal::BOX2D::grow(), size(), pdal::Dimension::X, and pdal::Dimension::Y.
Referenced by pdal::ELMFilter::filter(), and TEST().
void pdal::PointView::calculateBounds (const PointViewSet & set, BOX2D & box) static
Definition at line 113 of file PointView.cpp.
References begin().
void pdal::PointView::calculateBounds (BOX3D & box) const
Definition at line 123 of file PointView.cpp.
References pdal::BOX3D::grow(), size(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
void pdal::PointView::calculateBounds (const PointViewSet & set, BOX3D & box) static
Definition at line 136 of file PointView.cpp.
References begin().
void pdal::PointView::clearTemps ()
Definition at line 271 of file PointView.hpp.
References pdal::Dimension::name(), and pdal::Utils::toMetadata().
template<typename T > bool pdal::PointView::compare (Dimension::Id dim, PointId id1, PointId id2)
Definition at line 132 of file PointView.hpp.
Referenced by pdal::PointIdxRef::compare().
bool pdal::PointView::compare (Dimension::Id dim, PointId id1, PointId id2)
Definition at line 137 of file PointView.hpp.
References pdal::Dimension::Double, pdal::Dimension::Float, pdal::Dimension::None, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::Detail::type(), pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
template<typename T_IN , typename T_OUT > bool pdal::PointView::convertAndSet (Dimension::Id dim, PointId idx, T_IN in) private
Definition at line 493 of file PointView.hpp.
References pdal::Utils::numericCast().
TriangularMesh * pdal::PointView::createMesh (const std::string & name)
Creates a mesh with the specified name.
Parameters
name Name of the mesh.
Returns
Pointer to the new mesh. Null is returned if the mesh already exists.
Definition at line 165 of file PointView.cpp.
References pdal::Utils::contains(), and m_meshes.
Referenced by pdal::GreedyProjection::filter().
std::string pdal::PointView::dimName (Dimension::Id id) const
Definition at line 203 of file PointView.hpp.
Referenced by toMetadata().
Dimension::IdList pdal::PointView::dims () const
Definition at line 205 of file PointView.hpp.
Referenced by pdal::DiffKernel::checkPoints(), dump(), and toMetadata().
std::size_t pdal::PointView::dimSize (Dimension::Id id) const
Definition at line 209 of file PointView.hpp.
Dimension::Type pdal::PointView::dimType (Dimension::Id id) const
Definition at line 211 of file PointView.hpp.
DimTypeList pdal::PointView::dimTypes () const
Definition at line 213 of file PointView.hpp.
void pdal::PointView::dump (std::ostream & ostr) const
Definition at line 217 of file PointView.cpp.
References pdal::PointLayout::dimDetail(), pdal::PointLayout::dims(), dims(), pdal::Dimension::Double, pdal::Dimension::Float, pdal::Dimension::interpretationName(), pdal::BasePointTable::layout(), layout(), m_pointTable, pdal::Dimension::name(), pdal::Dimension::None, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, size(), pdal::Dimension::Detail::type(), pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
Referenced by pdal::operator<<().
bool pdal::PointView::empty () const
Definition at line 93 of file PointView.hpp.
PointViewIter pdal::PointView::end ()
Definition at line 70 of file PointView.cpp.
References size().
Referenced by pdal::RandomizeFilter::filter(), and pdal::SortFilter::filter().
void pdal::PointView::freeTemp (PointId id) private
Definition at line 326 of file PointView.hpp.
Referenced by pdal::PointIdxRef::~PointIdxRef().
void pdal::PointView::getField (char * pos, Dimension::Id d, Dimension::Type type, PointId id) const
Definition at line 345 of file PointView.hpp.
References pdal::Everything::d, pdal::Dimension::Double, pdal::Everything::f, pdal::Dimension::Float, pdal::Dimension::id(), pdal::Dimension::None, pdal::Everything::s16, pdal::Everything::s32, pdal::Everything::s64, pdal::Everything::s8, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::size(), pdal::Everything::u16, pdal::Everything::u32, pdal::Everything::u64, pdal::Everything::u8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
Referenced by pdal::DbWriter::readField().
template<class T > T pdal::PointView::getFieldAs (Dimension::Id dim, PointId pointIndex) const
Definition at line 432 of file PointView.hpp.
References pdal::Dimension::Double, pdal::Dimension::Float, pdal::Dimension::interpretationName(), pdal::Dimension::name(), pdal::Dimension::None, pdal::Utils::numericCast(), pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::Detail::type(), pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
Referenced by Support::check_pN(), Check_Point(), checkDimension(), checkPoint(), pdal::eigen::computeCentroid(), pdal::eigen::computeCovariance(), pdal::eigen::createMaxMatrix(), pdal::eigen::createMaxMatrix2(), pdal::eigen::createMinMatrix(), pdal::eigen::extendedLocalMinimum(), pdal::ComputeRangeFilter::filter(), pdal::LOFFilter::filter(), pdal::HAGFilter::filter(), pdal::ELMFilter::filter(), pdal::HexBin::filter(), pdal::ColorinterpFilter::filter(), pdal::BpfWriter::getAdjustedValue(), pdal::GreedyProjection::getCoord(), pdal::GreedyProjection::getNormalCoord(), anonymous_namespace{ReprojectionFilterTest.cpp}::getPoint(), pdal::ChipperFilter::load(), pdal::PointViewSource::nextPoint(), pdal::ColorPointViewSource::nextPoint(), pdal::PointViewMesh::nextPoint(), pdal::eigen::pointViewToEigen(), pdal::QuadIndex::QImpl::QImpl(), TEST(), and verifyTestView().
virtual void pdal::PointView::getFieldInternal (Dimension::Id dim, PointId idx, void * buf) const private virtual
Implements pdal::PointContainer.
Definition at line 319 of file PointView.hpp.
Referenced by pdal::plang::Invocation::begin().
template<class T > T pdal::PointView::getFieldInternal (Dimension::Id dim, PointId pointIndex) const private
Definition at line 337 of file PointView.hpp.
char* pdal::PointView::getOrAddPoint (PointId id)
Provides access to the memory storing the point data. Though this function is public, other access methods are safer and preferred.
Definition at line 256 of file PointView.hpp.
References pdal::Dimension::size().
void pdal::PointView::getPackedPoint (const DimTypeList & dims, PointId idx, char * buf) const
Fill a buffer with point data specified by the dimension list.
Parameters
[in] dims List of dimensions/types to retrieve.
[in] idx Index of point to get.
[in] buf Pointer to buffer to fill.
Definition at line 226 of file PointView.hpp.
References pdal::Dimension::size().
Referenced by pdal::DbWriter::readPoint().
char* pdal::PointView::getPoint (PointId id)
Provides access to the memory storing the point data. Though this function is public, other access methods are safer and preferred.
Definition at line 251 of file PointView.hpp.
void pdal::PointView::getRawField (Dimension::Id dim, PointId idx, void * buf) const
Definition at line 180 of file PointView.hpp.
Referenced by pdal::DiffKernel::checkPoints().
PointId pdal::PointView::getTemp (PointId id) private
Definition at line 568 of file PointView.hpp.
References pdal::Dimension::id(), pdal::plang::operator<<(), and PDAL_DLL.
Referenced by pdal::PointIdxRef::operator=(), and pdal::PointIdxRef::PointIdxRef().
bool pdal::PointView::hasDim (Dimension::Id id) const
Definition at line 201 of file PointView.hpp.
Referenced by Support::check_pN(), pdal::PointViewMesh::hasDensity(), pdal::KD2Index::KD2Index(), and pdal::KD3Index::KD3Index().
int pdal::PointView::id () const
Definition at line 87 of file PointView.hpp.
PointLayoutPtr pdal::PointView::layout () const virtual
Implements pdal::PointContainer.
Definition at line 215 of file PointView.hpp.
Referenced by pdal::plang::Invocation::begin(), dump(), and toMetadata().
PointViewPtr pdal::PointView::makeNew () const
Return a new point view with the same point table as this point buffer.
Definition at line 111 of file PointView.hpp.
Referenced by pdal::HAGFilter::filter().
TriangularMesh * pdal::PointView::mesh (const std::string & name = "")
Get a pointer to a mesh.
Parameters
name Name of the mesh.
Returns
New mesh. Null is returned if the mesh already exists.
Definition at line 177 of file PointView.cpp.
References m_meshes.
PointView& pdal::PointView::operator= (const PointView &) delete
PointRef pdal::PointView::point (PointId id)
Definition at line 116 of file PointView.hpp.
References pdal::Dimension::type().
Referenced by pdal::CropFilter::crop(), pdal::NormalFilter::filter(), pdal::ColorizationFilter::filter(), and TEST().
std::size_t pdal::PointView::pointSize () const
Definition at line 207 of file PointView.hpp.
template<typename T > void pdal::PointView::setField (Dimension::Id dim, PointId idx, T val)
Definition at line 505 of file PointView.hpp.
References pdal::Dimension::Double, pdal::Dimension::Float, pdal::Dimension::interpretationName(), pdal::Dimension::name(), pdal::Dimension::None, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::Detail::type(), pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
Referenced by pdal::plang::Invocation::end(), pdal::ComputeRangeFilter::filter(), pdal::HAGFilter::filter(), pdal::KDistanceFilter::filter(), pdal::LOFFilter::filter(), pdal::RadialDensityFilter::filter(), pdal::ClusterFilter::filter(), pdal::ELMFilter::filter(), pdal::EigenvaluesFilter::filter(), pdal::EstimateRankFilter::filter(), pdal::ApproximateCoplanarFilter::filter(), pdal::NormalFilter::filter(), pdal::PointViewMesh::newPoint(), pdal::OciReader::readDimMajor(), TEST(), and pdal::DbReader::writeField().
void pdal::PointView::setField (Dimension::Id dim, Dimension::Type type, PointId idx, const void * val)
Definition at line 388 of file PointView.hpp.
References pdal::Everything::d, pdal::Dimension::Double, pdal::Everything::f, pdal::Dimension::Float, pdal::Dimension::None, pdal::Everything::s16, pdal::Everything::s32, pdal::Everything::s64, pdal::Everything::s8, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::size(), pdal::Everything::u16, pdal::Everything::u32, pdal::Everything::u64, pdal::Everything::u8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
void pdal::PointView::setFieldInternal (Dimension::Id dim, PointId idx, const void * buf) private virtual
Implements pdal::PointContainer.
Definition at line 76 of file PointView.cpp.
References pdal::BasePointTable::addPoint(), m_index, m_pointTable, m_size, m_temps, and size().
void pdal::PointView::setPackedPoint (const DimTypeList & dims, PointId idx, const char * buf)
Load the point buffer from memory whose arrangement is specified by the dimension list.
Parameters
[in] dims Dimension/types of data in packed order
[in] idx Index of point to write.
[in] buf Packed data buffer.
Definition at line 240 of file PointView.hpp.
References pdal::Dimension::size().
void pdal::PointView::setSpatialReference (const SpatialReference & spatialRef)
Definition at line 217 of file PointView.hpp.
point_count_t pdal::PointView::size () const
Definition at line 90 of file PointView.hpp.
Referenced by append(), pdal::plang::Invocation::begin(), calculateBounds(), pdal::DiffKernel::checkPoints(), pdal::eigen::createMaxMatrix(), pdal::eigen::createMinMatrix(), pdal::CropFilter::crop(), pdal::DecimationFilter::decimate(), dump(), end(), pdal::plang::Invocation::end(), pdal::eigen::extendedLocalMinimum(), pdal::Segmentation::extractClusters(), pdal::LasWriter::fillWriteBuf(), pdal::AssignFilter::filter(), pdal::StreamCallbackFilter::filter(), pdal::ComputeRangeFilter::filter(), pdal::LOFFilter::filter(), pdal::RadialDensityFilter::filter(), pdal::HAGFilter::filter(), pdal::KDistanceFilter::filter(), pdal::ELMFilter::filter(), pdal::EigenvaluesFilter::filter(), pdal::EstimateRankFilter::filter(), pdal::HexBin::filter(), pdal::ApproximateCoplanarFilter::filter(), pdal::TransformationFilter::filter(), pdal::FerryFilter::filter(), pdal::ColorinterpFilter::filter(), pdal::NormalFilter::filter(), pdal::ColorizationFilter::filter(), pdal::StatsFilter::filter(), pdal::GreedyProjection::filter(), pdal::ChipperFilter::load(), pdal::PointViewMesh::newPoint(), pdal::PointViewSource::nextPoint(), pdal::ColorPointViewSource::nextPoint(), pdal::PointViewMesh::nextPoint(), pdal::PointViewMesh::pointCount(), pdal::eigen::pointViewToEigen(), pdal::QuadIndex::QImpl::QImpl(), pdal::OciReader::readDimMajor(), pdal::OciReader::readPointMajor(), setFieldInternal(), toMetadata(), pdal::BpfWriter::writeByteMajor(), pdal::BpfWriter::writeDimMajor(), pdal::BpfWriter::writePointMajor(), and pdal::LasWriter::writeView().
SpatialReference pdal::PointView::spatialReference () const
Definition at line 219 of file PointView.hpp.
Referenced by pdal::plang::Invocation::begin().
MetadataNode pdal::PointView::toMetadata () const
Definition at line 146 of file PointView.cpp.
References pdal::MetadataNode::add(), dimName(), pdal::PointLayout::dims(), dims(), layout(), and size().
Friends And Related Function Documentation
friend class plang::Invocation friend
Definition at line 74 of file PointView.hpp.
friend class PointIdxRef friend
Definition at line 75 of file PointView.hpp.
friend struct PointViewLess friend
Definition at line 76 of file PointView.hpp.
Member Data Documentation
int pdal::PointView::m_id protected
Definition at line 304 of file PointView.hpp.
Referenced by PointView().
std::deque<PointId> pdal::PointView::m_index protected
Definition at line 300 of file PointView.hpp.
Referenced by append(), appendPoint(), pdal::PointIdxRef::operator=(), setFieldInternal(), and pdal::PointIdxRef::swap().
std::unique_ptr<KD2Index> pdal::PointView::m_index2 protected
Definition at line 309 of file PointView.hpp.
Referenced by build2dIndex().
std::unique_ptr<KD3Index> pdal::PointView::m_index3 protected
Definition at line 308 of file PointView.hpp.
Referenced by build3dIndex().
int pdal::PointView::m_lastId = 0 static private
Definition at line 312 of file PointView.hpp.
Referenced by PointView().
std::map<std::string, std::unique_ptr<TriangularMesh> > pdal::PointView::m_meshes protected
Definition at line 307 of file PointView.hpp.
Referenced by createMesh(), and mesh().
PointTableRef pdal::PointView::m_pointTable protected
Definition at line 299 of file PointView.hpp.
Referenced by pdal::plang::Invocation::begin(), dump(), pdal::plang::Invocation::end(), and setFieldInternal().
point_count_t pdal::PointView::m_size protected
Definition at line 303 of file PointView.hpp.
Referenced by setFieldInternal().
SpatialReference pdal::PointView::m_spatialReference protected
Definition at line 306 of file PointView.hpp.
std::queue<PointId> pdal::PointView::m_temps protected
Definition at line 305 of file PointView.hpp.
Referenced by setFieldInternal().
The documentation for this class was generated from the following files:
pdal/pdal/PointView.hpp
pdal/pdal/PointView.cpp