PDAL: pdal::stats::Summary Class Reference
pdal::stats::Summary Class Reference
#include <StatsFilter.hpp>
Public Types
enum EnumType { NoEnum, Enumerate, Count, Global }
typedef std::map< double, point_count_t > EnumMap
typedef std::vector< double > DataVector
Public Member Functions
Summary (std::string name, EnumType enumerate)
double minimum () const
double maximum () const
double average () const
double variance () const
double stddev () const
double skewness () const
double kurtosis () const
double median () const
double mad () const
point_count_t count () const
std::string name () const
const EnumMap & values () const
void extractMetadata (MetadataNode &m)
void computeGlobalStats ()
void reset ()
void insert (double value)
Private Attributes
std::string m_name
EnumType m_enumerate
double m_max
double m_min
double m_avg
double m_mad
double m_median
EnumMap m_values
DataVector m_data
point_count_t m_cnt
double M1
double M2
double M3
double M4
Detailed Description
Definition at line 48 of file StatsFilter.hpp.
Member Typedef Documentation
typedef std::vector<double> pdal::stats::Summary::DataVector
Definition at line 60 of file StatsFilter.hpp.
typedef std::map<double, point_count_t> pdal::stats::Summary::EnumMap
Definition at line 59 of file StatsFilter.hpp.
Member Enumeration Documentation
enum pdal::stats::Summary::EnumType
Enumerator
NoEnum
Enumerate
Count
Global
Definition at line 51 of file StatsFilter.hpp.
Constructor & Destructor Documentation
pdal::stats::Summary::Summary (std::string name, EnumType enumerate)
Definition at line 63 of file StatsFilter.hpp.
Referenced by pdal::StatsFilter::prepared().
Member Function Documentation
double pdal::stats::Summary::average () const
Definition at line 71 of file StatsFilter.hpp.
Referenced by extractMetadata(), anonymous_namespace{BufferTest.cpp}::TEST(), and TEST().
void pdal::stats::Summary::computeGlobalStats ()
Definition at line 111 of file StatsFilter.cpp.
References m_data, m_mad, and m_median.
Referenced by extractMetadata().
point_count_t pdal::stats::Summary::count () const
Definition at line 85 of file StatsFilter.hpp.
Referenced by extractMetadata(), pdal::StatsFilter::extractMetadata(), TEST(), and anonymous_namespace{BufferTest.cpp}::TEST().
void pdal::stats::Summary::extractMetadata (MetadataNode & m)
Definition at line 65 of file StatsFilter.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addList(), average(), computeGlobalStats(), Count, count(), Enumerate, Global, kurtosis(), m_enumerate, m_mad, m_median, m_name, m_values, maximum(), minimum(), skewness(), stddev(), and variance().
Referenced by pdal::StatsFilter::done(), and pdal::StatsFilter::extractMetadata().
void pdal::stats::Summary::insert (double value)
Definition at line 106 of file StatsFilter.hpp.
Referenced by pdal::ColorinterpFilter::filter(), and pdal::StatsFilter::processOne().
double pdal::stats::Summary::kurtosis () const
Definition at line 79 of file StatsFilter.hpp.
Referenced by extractMetadata().
double pdal::stats::Summary::mad () const
Definition at line 83 of file StatsFilter.hpp.
Referenced by TEST().
double pdal::stats::Summary::maximum () const
Definition at line 69 of file StatsFilter.hpp.
Referenced by extractMetadata(), pdal::ColorinterpFilter::filter(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), and TEST_F().
double pdal::stats::Summary::median () const
Definition at line 81 of file StatsFilter.hpp.
Referenced by TEST().
double pdal::stats::Summary::minimum () const
Definition at line 67 of file StatsFilter.hpp.
Referenced by extractMetadata(), pdal::ColorinterpFilter::filter(), anonymous_namespace{BufferTest.cpp}::TEST(), TEST(), and TEST_F().
std::string pdal::stats::Summary::name () const
Definition at line 87 of file StatsFilter.hpp.
void pdal::stats::Summary::reset ()
Definition at line 95 of file StatsFilter.hpp.
double pdal::stats::Summary::skewness () const
Definition at line 77 of file StatsFilter.hpp.
Referenced by extractMetadata().
double pdal::stats::Summary::stddev () const
Definition at line 75 of file StatsFilter.hpp.
Referenced by extractMetadata().
const EnumMap& pdal::stats::Summary::values () const
Definition at line 89 of file StatsFilter.hpp.
Referenced by TEST().
double pdal::stats::Summary::variance () const
Definition at line 73 of file StatsFilter.hpp.
Referenced by extractMetadata().
Member Data Documentation
double pdal::stats::Summary::M1 private
Definition at line 151 of file StatsFilter.hpp.
double pdal::stats::Summary::M2 private
Definition at line 151 of file StatsFilter.hpp.
double pdal::stats::Summary::M3 private
Definition at line 151 of file StatsFilter.hpp.
double pdal::stats::Summary::M4 private
Definition at line 151 of file StatsFilter.hpp.
double pdal::stats::Summary::m_avg private
Definition at line 145 of file StatsFilter.hpp.
point_count_t pdal::stats::Summary::m_cnt private
Definition at line 150 of file StatsFilter.hpp.
DataVector pdal::stats::Summary::m_data private
Definition at line 149 of file StatsFilter.hpp.
Referenced by computeGlobalStats().
EnumType pdal::stats::Summary::m_enumerate private
Definition at line 142 of file StatsFilter.hpp.
Referenced by extractMetadata().
double pdal::stats::Summary::m_mad private
Definition at line 146 of file StatsFilter.hpp.
Referenced by computeGlobalStats(), and extractMetadata().
double pdal::stats::Summary::m_max private
Definition at line 143 of file StatsFilter.hpp.
double pdal::stats::Summary::m_median private
Definition at line 147 of file StatsFilter.hpp.
Referenced by computeGlobalStats(), and extractMetadata().
double pdal::stats::Summary::m_min private
Definition at line 144 of file StatsFilter.hpp.
std::string pdal::stats::Summary::m_name private
Definition at line 141 of file StatsFilter.hpp.
Referenced by extractMetadata().
EnumMap pdal::stats::Summary::m_values private
Definition at line 148 of file StatsFilter.hpp.
Referenced by extractMetadata().
The documentation for this class was generated from the following files:
pdal/filters/StatsFilter.hpp
pdal/filters/StatsFilter.cpp