PDAL: pdal::ChipRefList Class Reference
pdal::ChipRefList Class Reference
#include <ChipperFilter.hpp>
Private Member Functions
std::vector< ChipPtRef >::size_type size () const
void reserve (std::vector< ChipPtRef >::size_type n)
void resize (std::vector< ChipPtRef >::size_type n)
void push_back (const ChipPtRef &ref)
std::vector< ChipPtRef >::iterator begin ()
std::vector< ChipPtRef >::iterator end ()
ChipPtRef & operator[] (uint32_t pos)
Private Attributes
std::vector< ChipPtRef > m_vec
Friends
class ChipperFilter
Detailed Description
Definition at line 78 of file ChipperFilter.hpp.
Member Function Documentation
std::vector<ChipPtRef>::iterator pdal::ChipRefList::begin () private
Definition at line 101 of file ChipperFilter.hpp.
Referenced by pdal::ChipperFilter::load().
std::vector<ChipPtRef>::iterator pdal::ChipRefList::end () private
Definition at line 105 of file ChipperFilter.hpp.
Referenced by pdal::ChipperFilter::load().
ChipPtRef& pdal::ChipRefList::operator[] (uint32_t pos) private
Definition at line 109 of file ChipperFilter.hpp.
void pdal::ChipRefList::push_back (const ChipPtRef & ref) private
Definition at line 97 of file ChipperFilter.hpp.
Referenced by pdal::ChipperFilter::load().
void pdal::ChipRefList::reserve (std::vector< ChipPtRef >::size_type n) private
Definition at line 89 of file ChipperFilter.hpp.
Referenced by pdal::ChipperFilter::load().
void pdal::ChipRefList::resize (std::vector< ChipPtRef >::size_type n) private
Definition at line 93 of file ChipperFilter.hpp.
Referenced by pdal::ChipperFilter::load().
std::vector<ChipPtRef>::size_type pdal::ChipRefList::size () const private
Definition at line 85 of file ChipperFilter.hpp.
Referenced by pdal::ChipperFilter::load(), and pdal::ChipperFilter::run().
Friends And Related Function Documentation
friend class ChipperFilter friend
Definition at line 80 of file ChipperFilter.hpp.
Member Data Documentation
std::vector<ChipPtRef> pdal::ChipRefList::m_vec private
Definition at line 83 of file ChipperFilter.hpp.
The documentation for this class was generated from the following file:
pdal/filters/ChipperFilter.hpp