PDAL: pdal::Log Class Reference
pdal::Log Class Reference
#include <Log.hpp>
Public Member Functions
Log (std::string const &leaderString, std::string const &outputName)
Log (std::string const &leaderString, std::ostream *v)
Destructor
~Log ()
Logging level
LogLevel getLevel ()
void setLevel (LogLevel v)
void setLeader (const std::string &leader)
void pushLeader (const std::string &leader)
std::string leader () const
void popLeader ()
Pop the current leader string.
std::string getLevelString (LogLevel v) const
Log stream operations
std::ostream * m_log
LogLevel m_level
bool m_deleteStreamOnCleanup
std::stack< std::string > m_leaders
NullOStream m_nullStream
std::ostream * getLogStream ()
std::ostream & get (LogLevel level=LogLevel::Info)
void floatPrecision (int level)
Sets the floating point precision.
void clearFloat ()
Clears the floating point precision settings of the streams.
Log (const Log &)
Log & operator= (const Log &)
Detailed Description
pdal::Log is a logging object that is provided by pdal::Stage to facilitate logging operations.
Definition at line 51 of file Log.hpp.
Constructor & Destructor Documentation
pdal::Log::Log (std::string const & leaderString, std::string const & outputName)
Constructs a pdal::Log instance.
Parameters
leaderString A string to presage all log entries with
outputName A filename or one of 'stdout', 'stdlog', or 'stderr' to use for outputting log information.
Definition at line 44 of file Log.cpp.
References pdal::Utils::createFile(), pdal::Utils::iequals(), m_deleteStreamOnCleanup, m_leaders, m_log, m_nullStream, and pdal::Warning.
pdal::Log::Log (std::string const & leaderString, std::ostream * v)
Constructs a pdal::Log instance.
Parameters
leaderString A string to presage all log entries with
v An existing std::ostream to use for logging (instead of the the instance creating its own)
Definition at line 67 of file Log.cpp.
References m_leaders, and m_log.
pdal::Log::~Log ()
The destructor will clean up its own internal log stream, but it will not touch one that is given via the constructor
Definition at line 77 of file Log.cpp.
References m_deleteStreamOnCleanup, and m_log.
pdal::Log::Log (const Log &) private
Member Function Documentation
void pdal::Log::clearFloat ()
Clears the floating point precision settings of the streams.
Definition at line 95 of file Log.cpp.
References m_log.
void pdal::Log::floatPrecision (int level)
Sets the floating point precision.
Definition at line 88 of file Log.cpp.
References m_log.
std::ostream & pdal::Log::get (LogLevel level = LogLevel::Info)
Returns the log stream given the logging level.
Parameters
level logging level to request If the logging level asked for with pdal::Log::get is less than the logging level of the pdal::Log instance
Definition at line 102 of file Log.cpp.
References pdal::Debug, getLevelString(), leader(), m_level, m_log, m_nullStream, and pdal::Utils::toNative().
Referenced by pdal::TEST().
LogLevel pdal::Log::getLevel ()
Returns
the logging level of the pdal::Log instance
Definition at line 76 of file Log.hpp.
std::string pdal::Log::getLevelString (LogLevel v) const
Returns
A string representing the LogLevel
Definition at line 123 of file Log.cpp.
References pdal::Error, pdal::Info, and pdal::Warning.
Referenced by get().
std::ostream* pdal::Log::getLogStream ()
Returns
the stream object that is currently being used to for log operations regardless of logging level of the instance.
Definition at line 118 of file Log.hpp.
References pdal::Info, and setup::level.
std::string pdal::Log::leader () const
Get the leader string.
Returns
The current leader string.
Definition at line 101 of file Log.hpp.
Referenced by get().
Log& pdal::Log::operator= (const Log &) private
void pdal::Log::popLeader ()
Pop the current leader string.
Definition at line 105 of file Log.hpp.
void pdal::Log::pushLeader (const std::string & leader)
Push the leader string onto the stack.
Parameters
leader Leader string
Definition at line 96 of file Log.hpp.
void pdal::Log::setLeader (const std::string & leader)
Set the leader string (deprecated).
Parameters
[in] leader Leader string.
Definition at line 91 of file Log.hpp.
void pdal::Log::setLevel (LogLevel v)
Sets the logging level of the pdal::Log instance
Parameters
v logging level to use for get() comparison operations
Definition at line 83 of file Log.hpp.
References pdal::None.
Referenced by pdal::TEST().
Member Data Documentation
bool pdal::Log::m_deleteStreamOnCleanup private
Definition at line 143 of file Log.hpp.
Referenced by Log(), and ~Log().
std::stack<std::string> pdal::Log::m_leaders private
Definition at line 144 of file Log.hpp.
Referenced by Log().
LogLevel pdal::Log::m_level private
Definition at line 142 of file Log.hpp.
Referenced by get().
std::ostream* pdal::Log::m_log protected
Definition at line 136 of file Log.hpp.
Referenced by clearFloat(), floatPrecision(), get(), Log(), and ~Log().
NullOStream pdal::Log::m_nullStream private
Definition at line 145 of file Log.hpp.
Referenced by get(), and Log().
The documentation for this class was generated from the following files:
pdal/pdal/Log.hpp
pdal/pdal/Log.cpp