PDAL: pdal::StageFactory Class Reference
pdal::StageFactory Class Reference
#include <StageFactory.hpp>
Public Member Functions
StageFactory (bool no_plugins=true)
Stage * createStage (const std::string &type)
void destroyStage (Stage *stage)
Static Public Member Functions
static StringList extensions (const std::string &driver)
static std::string inferReaderDriver (const std::string &filename)
static std::string inferWriterDriver (const std::string &filename)
Private Member Functions
StageFactory & operator= (const StageFactory &)
StageFactory (const StageFactory &)
Private Attributes
std::vector< std::unique_ptr< Stage > > m_ownedStages
std::mutex m_mutex
Detailed Description
This class provides a mechanism for creating Stage objects given a driver name. Creates stages are owned by the factory and destroyed when the factory is destroyed. Stages can be explicitly destroyed with destroyStage() if desired.
Note
Stage creation is thread-safe.
Definition at line 58 of file StageFactory.hpp.
Constructor & Destructor Documentation
pdal::StageFactory::StageFactory (bool no_plugins = true)
Create a stage factory.
Parameters
no_plugins Don't load plugins or allowed them to be created with this factory.
Definition at line 259 of file StageFactory.cpp.
References ApproximateCoplanarFilter_InitPlugin(), AssignFilter_InitPlugin(), BpfReader_InitPlugin(), BpfWriter_InitPlugin(), ChipperFilter_InitPlugin(), ClusterFilter_InitPlugin(), ColorinterpFilter_InitPlugin(), ColorizationFilter_InitPlugin(), ComputeRangeFilter_InitPlugin(), CropFilter_InitPlugin(), DecimationFilter_InitPlugin(), DeltaKernel_InitPlugin(), DiffKernel_InitPlugin(), DividerFilter_InitPlugin(), EigenvaluesFilter_InitPlugin(), ELMFilter_InitPlugin(), EstimateRankFilter_InitPlugin(), FauxReader_InitPlugin(), FerryFilter_InitPlugin(), GDALReader_InitPlugin(), GDALWriter_InitPlugin(), GreedyProjection_InitPlugin(), GroundKernel_InitPlugin(), GroupByFilter_InitPlugin(), HAGFilter_InitPlugin(), HausdorffKernel_InitPlugin(), HeadFilter_InitPlugin(), Ilvis2Reader_InitPlugin(), InfoKernel_InitPlugin(), pdal::PluginManager::initializePlugin(), IQRFilter_InitPlugin(), KDistanceFilter_InitPlugin(), LasReader_InitPlugin(), LasWriter_InitPlugin(), pdal::PluginManager::loadAll(), LocateFilter_InitPlugin(), LOFFilter_InitPlugin(), MADFilter_InitPlugin(), MergeFilter_InitPlugin(), MergeKernel_InitPlugin(), MongusFilter_InitPlugin(), MortonOrderFilter_InitPlugin(), NormalFilter_InitPlugin(), NullWriter_InitPlugin(), OGRWriter_InitPlugin(), OptechReader_InitPlugin(), OutlierFilter_InitPlugin(), OverlayFilter_InitPlugin(), PF_PluginType_Filter, PF_PluginType_Kernel, PF_PluginType_Reader, PF_PluginType_Writer, PipelineKernel_InitPlugin(), PlyReader_InitPlugin(), PlyWriter_InitPlugin(), PMFFilter_InitPlugin(), PoissonFilter_InitPlugin(), PtsReader_InitPlugin(), QfitReader_InitPlugin(), RadialDensityFilter_InitPlugin(), RandomizeFilter_InitPlugin(), RandomKernel_InitPlugin(), RangeFilter_InitPlugin(), ReprojectionFilter_InitPlugin(), SampleFilter_InitPlugin(), SbetReader_InitPlugin(), SbetWriter_InitPlugin(), SMRFilter_InitPlugin(), SortFilter_InitPlugin(), SortKernel_InitPlugin(), SplitKernel_InitPlugin(), SplitterFilter_InitPlugin(), StatsFilter_InitPlugin(), TailFilter_InitPlugin(), TerrasolidReader_InitPlugin(), TextReader_InitPlugin(), TextWriter_InitPlugin(), TIndexKernel_InitPlugin(), TIndexReader_InitPlugin(), TransformationFilter_InitPlugin(), TranslateKernel_InitPlugin(), VoxelCenterNearestNeighborFilter_InitPlugin(), and VoxelCentroidNearestNeighborFilter_InitPlugin().
pdal::StageFactory::StageFactory (const StageFactory &) private
Member Function Documentation
Stage * pdal::StageFactory::createStage (const std::string & type)
Create a stage and return a pointer to the created stage. The factory takes ownership of any successfully created stage.
Parameters
stage_name Type of stage to by created.
Returns
Pointer to created stage.
Definition at line 354 of file StageFactory.cpp.
References pdal::PluginManager::createObject(), m_mutex, and m_ownedStages.
Referenced by pdal::PipelineManager::addFilter(), pdal::PipelineManager::addReader(), pdal::PipelineManager::addWriter(), Support::checkXYZ(), anonymous_namespace{NitfWriterTest.cpp}::compare_contents(), pdal::TIndexReader::initialize(), main(), anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite(), App::outputOptions(), readData(), TEST(), pdal::TEST(), pdal::TEST_F(), TEST_F(), test_filter(), pdal::TEST_P(), TEST_P(), testOverlay(), testReadWrite(), and writeData().
void pdal::StageFactory::destroyStage (Stage * stage)
Destroy a stage created by this factory. This doesn't need to be called unless you specifically want to destroy a stage as all stages are destroyed when the factory is destroyed.
Parameters
stage Pointer to stage to destroy.
Definition at line 367 of file StageFactory.cpp.
References m_mutex, and m_ownedStages.
StringList pdal::StageFactory::extensions (const std::string & driver) static
Return the file extensions associated with a driver.
Parameters
driver Name of the driver whose extensions should be returned.
Definition at line 129 of file StageFactory.cpp.
Referenced by pdal::TEST().
std::string pdal::StageFactory::inferReaderDriver (const std::string & filename) static
Infer the reader to use based on a filename.
Parameters
filename Filename that should be analyzed to determine a driver.
Returns
Driver name or empty string if no reader can be inferred from the filename.
Definition at line 170 of file StageFactory.cpp.
References setup::ext, pdal::FileUtils::extension(), pdal::Utils::iequals(), and pdal::Utils::tolower().
Referenced by Support::checkXYZ(), pdal::TIndexReader::initialize(), pdal::PipelineManager::makeReader(), and pdal::TEST().
std::string pdal::StageFactory::inferWriterDriver (const std::string & filename) static
Infer the writer to use based on filename extension.
Returns
Driver name or empty string if no writer can be inferred from the filename.
Definition at line 217 of file StageFactory.cpp.
References setup::ext, pdal::FileUtils::extension(), and pdal::Utils::tolower().
Referenced by pdal::PipelineManager::makeWriter(), and pdal::TEST().
StageFactory& pdal::StageFactory::operator= (const StageFactory &) private
Member Data Documentation
std::mutex pdal::StageFactory::m_mutex private
Definition at line 116 of file StageFactory.hpp.
Referenced by createStage(), and destroyStage().
std::vector<std::unique_ptr<Stage> > pdal::StageFactory::m_ownedStages private
Definition at line 115 of file StageFactory.hpp.
Referenced by createStage(), and destroyStage().
The documentation for this class was generated from the following files:
pdal/pdal/StageFactory.hpp
pdal/pdal/StageFactory.cpp