PDAL: pdal::IStreamMarker Class Reference
pdal::IStreamMarker Class Reference
Stream position marker with rewinding support.
#include <IStream.hpp>
Public Member Functions
PDAL_DLL IStreamMarker (IStream &stream)
PDAL_DLL void rewind ()
Private Member Functions
IStreamMarker (const IStreamMarker &)
IStreamMarker & operator= (const IStreamMarker &)
Private Attributes
std::streampos m_pos
IStream & m_stream
Detailed Description
Stream position marker with rewinding support.
Definition at line 695 of file IStream.hpp.
Constructor & Destructor Documentation
PDAL_DLL pdal::IStreamMarker::IStreamMarker (IStream & stream)
Definition at line 698 of file IStream.hpp.
References pdal::IStream::m_stream.
pdal::IStreamMarker::IStreamMarker (const IStreamMarker &) private
Member Function Documentation
IStreamMarker& pdal::IStreamMarker::operator= (const IStreamMarker &) private
PDAL_DLL void pdal::IStreamMarker::rewind ()
Definition at line 701 of file IStream.hpp.
References pdal::IStream::m_stream.
Referenced by pdal::BpfHeader::read(), pdal::BpfUlemHeader::read(), pdal::BpfUlemFile::read(), pdal::BpfPolarHeader::read(), pdal::nitfwrap::NitfWrap::unwrap(), and pdal::nitfwrap::NitfWrap::verify().
Member Data Documentation
std::streampos pdal::IStreamMarker::m_pos private
Definition at line 705 of file IStream.hpp.
IStream& pdal::IStreamMarker::m_stream private
Definition at line 706 of file IStream.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/util/IStream.hpp