PDAL: pdal::mlang::Script Class Reference
pdal::mlang::Script Class Reference
#include <Script.hpp>
Public Member Functions
Script ()
Static Public Member Functions
static int getMatlabDataType (Dimension::Type t)
static Dimension::Type getPDALDataType (mxClassID t)
static mxArray * setMatlabStruct (PointViewPtr view, const Dimension::IdList &dims, const std::string &pdalargs, MetadataNode node, LogPtr log)
static void getMatlabStruct (mxArray *array, PointViewPtr view, const Dimension::IdList &dims, std::string &pdalargs, MetadataNode node, LogPtr log)
static PointLayoutPtr getStructLayout (mxArray *array, LogPtr log)
static std::string getLogicalMask (mxArray *array, LogPtr log)
static std::string getSRSWKT (mxArray *array, LogPtr log)
Public Attributes
std::string m_source
std::string m_scriptFilename
Private Member Functions
Script & operator= (Script const &rhs)
Detailed Description
Definition at line 50 of file Script.hpp.
Constructor & Destructor Documentation
pdal::mlang::Script::Script ()
Definition at line 53 of file Script.hpp.
References setup::log.
Member Function Documentation
std::string pdal::mlang::Script::getLogicalMask (mxArray * array, LogPtr log) static
Definition at line 52 of file Script.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and pdal::Dimension::name().
Referenced by pdal::MatlabFilter::run().
int pdal::mlang::Script::getMatlabDataType (Dimension::Type t) static
Definition at line 366 of file Script.cpp.
Referenced by setMatlabStruct().
void pdal::mlang::Script::getMatlabStruct (mxArray * array, PointViewPtr view, const Dimension::IdList & dims, std::string & pdalargs, MetadataNode node, LogPtr log) static
Definition at line 143 of file Script.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and getPDALDataType().
Referenced by pdal::MatlabFilter::run().
Dimension::Type pdal::mlang::Script::getPDALDataType (mxClassID t) static
Definition at line 332 of file Script.cpp.
References pdal::Dimension::None.
Referenced by getMatlabStruct(), and getStructLayout().
std::string pdal::mlang::Script::getSRSWKT (mxArray * array, LogPtr log) static
Definition at line 74 of file Script.cpp.
Referenced by pdal::MatlabReader::initialize().
PointLayoutPtr pdal::mlang::Script::getStructLayout (mxArray * array, LogPtr log) static
Definition at line 97 of file Script.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::PointLayout::finalize(), getPDALDataType(), and pdal::PointLayout::registerOrAssignDim().
Referenced by pdal::MatlabReader::addDimensions().
Script& pdal::mlang::Script::operator= (Script const & rhs) private
mxArray * pdal::mlang::Script::setMatlabStruct (PointViewPtr view, const Dimension::IdList & dims, const std::string & pdalargs, MetadataNode node, LogPtr log) static
Definition at line 219 of file Script.cpp.
References pdal::MetadataNode::clone(), pdal::convert(), pdal::SpatialReference::getHorizontal(), getMatlabDataType(), pdal::SpatialReference::getVertical(), pdal::SpatialReference::getWKT(), pdal::Dimension::name(), and pdal::Utils::toJSON().
Referenced by pdal::MatlabFilter::run(), and pdal::MatlabWriter::write().
Member Data Documentation
std::string pdal::mlang::Script::m_scriptFilename
Definition at line 66 of file Script.hpp.
Referenced by pdal::MatlabFilter::ready().
std::string pdal::mlang::Script::m_source
Definition at line 65 of file Script.hpp.
Referenced by pdal::MatlabFilter::addArgs(), pdal::mlang::operator<<(), pdal::MatlabFilter::ready(), and pdal::MatlabFilter::run().
The documentation for this class was generated from the following files:
pdal/plugins/matlab/filters/Script.hpp
pdal/plugins/matlab/filters/Script.cpp