PDAL: pdal::python::Array Class Reference
pdal::python::Array Class Reference
#include <PyArray.hpp>
Public Member Functions
Array ()
~Array ()
void update (PointViewPtr view)
PyObject * getPythonArray () const
Private Member Functions
void cleanup ()
PyObject * buildNumpyDescription (PointViewPtr view) const
Array & operator= (Array const &rhs)
Private Attributes
PyObject * m_py_array
std::unique_ptr< std::vector< uint8_t > > m_data_array
Detailed Description
Definition at line 74 of file PyArray.hpp.
Constructor & Destructor Documentation
pdal::python::Array::Array ()
Definition at line 78 of file PyArray.hpp.
pdal::python::Array::~Array ()
Definition at line 92 of file PyArray.hpp.
Member Function Documentation
PyObject* pdal::python::Array::buildNumpyDescription (PointViewPtr view) const private
Definition at line 165 of file PyArray.hpp.
References b, pdal::Dimension::base(), pdal::Dimension::Floating, pdal::anonymous_namespace{MbFormat.cpp}::formats, pdal::Dimension::name(), and pdal::Dimension::Unsigned.
void pdal::python::Array::cleanup () private
Definition at line 156 of file PyArray.hpp.
PyObject* pdal::python::Array::getPythonArray () const
Definition at line 151 of file PyArray.hpp.
Array& pdal::python::Array::operator= (Array const & rhs) private
void pdal::python::Array::update (PointViewPtr view)
Definition at line 98 of file PyArray.hpp.
References flags.
Referenced by libpdalpython::Pipeline::getArrays(), and TEST().
Member Data Documentation
std::unique_ptr<std::vector<uint8_t> > pdal::python::Array::m_data_array private
Definition at line 231 of file PyArray.hpp.
PyObject* pdal::python::Array::m_py_array private
Definition at line 230 of file PyArray.hpp.
The documentation for this class was generated from the following file:
pdal/pdal/PyArray.hpp