PDAL: pdal::PCLKernel Class Reference
pdal::PCLKernel Class Reference
#include <PCLKernel.hpp>
Public Member Functions
std::string getName () const
int execute ()
int run (const StringList &cmdArgs, LogPtr &log)
std::string getShortName () const
virtual void validateSwitches (ProgramArgs &args)
Static Public Member Functions
static void * create ()
static int32_t destroy (void *)
Protected Member Functions
Stage & makeReader (const std::string &inputFile, std::string driver)
Stage & makeReader (const std::string &inputFile, std::string driver, Options options)
Stage & makeFilter (const std::string &driver, Stage &parent)
Stage & makeFilter (const std::string &driver, Stage &parent, Options options)
Stage & makeFilter (const std::string &driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver)
Stage & makeWriter (const std::string &outputFile, Stage &parent, std::string driver, Options options)
virtual bool isStagePrefix (const std::string &stageType)
Protected Attributes
LogPtr m_log
std::string m_driverOverride
Private Member Functions
PCLKernel ()
virtual void addSwitches (ProgramArgs &args)
Private Attributes
std::unique_ptr< PipelineManager > m_manager
std::string m_inputFile
std::string m_outputFile
std::string m_pclFile
bool m_bCompress
bool m_bForwardMetadata
Detailed Description
Definition at line 43 of file PCLKernel.hpp.
Constructor & Destructor Documentation
pdal::PCLKernel::PCLKernel () private
Definition at line 51 of file PCLKernel.cpp.
Member Function Documentation
void pdal::PCLKernel::addSwitches (ProgramArgs & args) private virtual
Reimplemented from pdal::Kernel.
Definition at line 58 of file PCLKernel.cpp.
References pdal::ProgramArgs::add(), m_bCompress, m_bForwardMetadata, m_inputFile, m_outputFile, m_pclFile, and pdal::Arg::setPositional().
static void* pdal::PCLKernel::create () static
static int32_t pdal::PCLKernel::destroy (void *) static
int pdal::PCLKernel::execute () virtual
Implements pdal::Kernel.
Definition at line 72 of file PCLKernel.cpp.
References pdal::Options::add(), pdal::Stage::execute(), m_bCompress, m_bForwardMetadata, m_inputFile, m_outputFile, m_pclFile, pdal::Kernel::makeFilter(), pdal::Kernel::makeReader(), pdal::Kernel::makeWriter(), pdal::Stage::prepare(), and writerOptions().
std::string pdal::PCLKernel::getName () const virtual
Implements pdal::Kernel.
Definition at line 49 of file PCLKernel.cpp.
References pdal::PluginInfo::name.
std::string pdal::Kernel::getShortName () const inherited
Definition at line 67 of file Kernel.hpp.
References pdal::Utils::split2().
Referenced by pdal::Kernel::outputHelp().
bool pdal::Kernel::isStagePrefix (const std::string & stageType) protected virtual inherited
Reimplemented in pdal::PipelineKernel.
Definition at line 58 of file Kernel.cpp.
Referenced by pdal::PipelineKernel::isStagePrefix(), and pdal::Kernel::parseStageOption().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent) protected inherited
Definition at line 320 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Referenced by pdal::MyKernel::execute(), execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeFilter (const std::string & driver, Stage & parent, Options options) protected inherited
Definition at line 326 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeFilter (const std::string & driver) protected inherited
Definition at line 314 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeFilter().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver) protected inherited
Definition at line 301 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Referenced by pdal::MyKernel::execute(), execute(), pdal::SmoothKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::DiffKernel::execute(), pdal::GroundKernel::execute(), pdal::HausdorffKernel::loadSet(), pdal::DeltaKernel::loadSet(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeReader (const std::string & inputFile, std::string driver, Options options) protected inherited
Definition at line 307 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeReader().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver) protected inherited
Definition at line 333 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
Referenced by pdal::MyKernel::execute(), execute(), pdal::SmoothKernel::execute(), pdal::SortKernel::execute(), pdal::SplitKernel::execute(), pdal::MergeKernel::execute(), pdal::RandomKernel::execute(), pdal::GroundKernel::execute(), and pdal::TIndexKernel::mergeFile().
Stage & pdal::Kernel::makeWriter (const std::string & outputFile, Stage & parent, std::string driver, Options options) protected inherited
Definition at line 340 of file Kernel.cpp.
References pdal::Kernel::m_manager, and pdal::PipelineManager::makeWriter().
int pdal::Kernel::run (const StringList & cmdArgs, LogPtr & log) inherited
Definition at line 229 of file Kernel.cpp.
References pdal::Kernel::doExecution(), pdal::Kernel::doStartup(), pdal::Kernel::doSwitches(), setup::log, pdal::Kernel::m_log, pdal::Kernel::m_manager, pdal::Kernel::m_showHelp, pdal::Kernel::outputHelp(), pdal::Utils::printError(), and pdal::PipelineManager::setLog().
Referenced by App::execute().
virtual void pdal::Kernel::validateSwitches (ProgramArgs & args) virtual inherited
Reimplemented in pdal::TIndexKernel, pdal::InfoKernel, pdal::PipelineKernel, pdal::MergeKernel, and pdal::SplitKernel.
Definition at line 95 of file Kernel.hpp.
Referenced by pdal::Kernel::innerRun().
Member Data Documentation
bool pdal::PCLKernel::m_bCompress private
Definition at line 60 of file PCLKernel.hpp.
Referenced by addSwitches(), and execute().
bool pdal::PCLKernel::m_bForwardMetadata private
Definition at line 61 of file PCLKernel.hpp.
Referenced by addSwitches(), and execute().
std::string pdal::Kernel::m_driverOverride protected inherited
Definition at line 105 of file Kernel.hpp.
Referenced by pdal::Kernel::addBasicSwitches(), pdal::MergeKernel::execute(), pdal::SplitKernel::execute(), pdal::SortKernel::execute(), pdal::DiffKernel::execute(), pdal::DeltaKernel::loadSet(), pdal::InfoKernel::makePipeline(), and pdal::TIndexKernel::mergeFile().
std::string pdal::PCLKernel::m_inputFile private
Definition at line 57 of file PCLKernel.hpp.
Referenced by addSwitches(), and execute().
LogPtr pdal::Kernel::m_log protected inherited
Definition at line 103 of file Kernel.hpp.
Referenced by pdal::TIndexKernel::createFeature(), pdal::TIndexKernel::createFile(), pdal::TIndexKernel::createLayer(), pdal::InfoKernel::dumpPoints(), pdal::TranslateKernel::execute(), and pdal::Kernel::run().
std::unique_ptr<PipelineManager> pdal::PCLKernel::m_manager private
Definition at line 55 of file PCLKernel.hpp.
std::string pdal::PCLKernel::m_outputFile private
Definition at line 58 of file PCLKernel.hpp.
Referenced by addSwitches(), and execute().
std::string pdal::PCLKernel::m_pclFile private
Definition at line 59 of file PCLKernel.hpp.
Referenced by addSwitches(), and execute().
The documentation for this class was generated from the following files:
pdal/plugins/pcl/kernel/PCLKernel.hpp
pdal/plugins/pcl/kernel/PCLKernel.cpp