PDAL: pdal/test/unit/filters/ColorizationFilterTest.cpp File Reference
ColorizationFilterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/PointView.hpp>
#include <io/LasReader.hpp>
#include <filters/ColorizationFilter.hpp>
#include <filters/StreamCallbackFilter.hpp>
#include "Support.hpp"
Namespaces
anonymous_namespace{ColorizationFilterTest.cpp}
Functions
void anonymous_namespace{ColorizationFilterTest.cpp}::testFile (const Options &filterOps, StringList dimNames, uint16_t expectedRed, uint16_t expectedGreen, uint16_t expectedBlue)
void anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed (const Options &filterOps, StringList dimNames, uint16_t expectedRed, uint16_t expectedGreen, uint16_t expectedBlue)
TEST (ColorizationFilterTest, test1)
TEST (ColorizationFilterTest, test2)
TEST (ColorizationFilterTest, test3)
TEST (ColorizationFilterTest, test4)
Function Documentation
TEST (ColorizationFilterTest , test1)
Definition at line 130 of file ColorizationFilterTest.cpp.
References pdal::Options::add(), Support::datapath(), anonymous_namespace{ColorizationFilterTest.cpp}::testFile(), and anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed().
TEST (ColorizationFilterTest , test2)
Definition at line 146 of file ColorizationFilterTest.cpp.
References pdal::Options::add(), Support::datapath(), and anonymous_namespace{ColorizationFilterTest.cpp}::testFile().
TEST (ColorizationFilterTest , test3)
Definition at line 161 of file ColorizationFilterTest.cpp.
References pdal::Options::add(), Support::datapath(), and anonymous_namespace{ColorizationFilterTest.cpp}::testFile().
TEST (ColorizationFilterTest , test4)
Definition at line 176 of file ColorizationFilterTest.cpp.
References pdal::Options::add(), Support::datapath(), and anonymous_namespace{ColorizationFilterTest.cpp}::testFile().