PDAL: pdal/test/unit/filters/ColorinterpFilterTest.cpp File Reference
ColorinterpFilterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <io/FauxReader.hpp>
#include <filters/ColorinterpFilter.hpp>
#include <filters/StreamCallbackFilter.hpp>
#include "Support.hpp"
Namespaces
anonymous_namespace{ColorinterpFilterTest.cpp}
Functions
std::string anonymous_namespace{ColorinterpFilterTest.cpp}::makeColor ()
TEST (ColorinterpFilterTest, minmax)
TEST (ColorinterpFilterTest, missingz)
TEST (ColorinterpFilterTest, badramp)
TEST (ColorinterpFilterTest, cantstream)
void anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest (Options &coptions, std::function< bool(int, int)> test)
TEST (ColorinterpFilterTest, autorange)
TEST (ColorinterpFilterTest, k)
TEST (ColorinterpFilterTest, mad)
Function Documentation
TEST (ColorinterpFilterTest , minmax)
Definition at line 64 of file ColorinterpFilterTest.cpp.
References pdal::Options::add(), b, pdal::Dimension::Blue, c, pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Dimension::Green, anonymous_namespace{ColorinterpFilterTest.cpp}::makeColor(), pdal::Stage::prepare(), pdal::Dimension::Red, pdal::StreamCallbackFilter::setCallback(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Dimension::Z, and z.
TEST (ColorinterpFilterTest , missingz)
Definition at line 118 of file ColorinterpFilterTest.cpp.
References pdal::Options::add(), c, anonymous_namespace{ColorinterpFilterTest.cpp}::makeColor(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (ColorinterpFilterTest , badramp)
Definition at line 132 of file ColorinterpFilterTest.cpp.
References pdal::Options::add(), c, pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (ColorinterpFilterTest , cantstream)
Definition at line 157 of file ColorinterpFilterTest.cpp.
References pdal::Options::add(), c, pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, anonymous_namespace{ColorinterpFilterTest.cpp}::makeColor(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (ColorinterpFilterTest , autorange)
Definition at line 227 of file ColorinterpFilterTest.cpp.
References pdal::Options::add(), anonymous_namespace{ColorinterpFilterTest.cpp}::makeColor(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), and z.
TEST (ColorinterpFilterTest , k)
Definition at line 245 of file ColorinterpFilterTest.cpp.
References pdal::Options::add(), anonymous_namespace{ColorinterpFilterTest.cpp}::makeColor(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), and z.
TEST (ColorinterpFilterTest , mad)
Definition at line 272 of file ColorinterpFilterTest.cpp.
References pdal::Options::add(), anonymous_namespace{ColorinterpFilterTest.cpp}::makeColor(), anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest(), and z.