PDAL: pdal/test/unit/CompressionTest.cpp File Reference
CompressionTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <iterator>
#include <sstream>
#include <iostream>
#include <string>
#include <random>
#include "Support.hpp"
#include <pdal/Options.hpp>
#include <pdal/PointView.hpp>
#include <pdal/compression/DeflateCompression.hpp>
#include <pdal/compression/LazPerfCompression.hpp>
#include <pdal/compression/LzmaCompression.hpp>
#include <pdal/compression/ZstdCompression.hpp>
#include <io/LasReader.hpp>
Functions
std::vector< char > getBytes (PointViewPtr view)
Function Documentation
std::vector<char> getBytes (PointViewPtr view)
Definition at line 54 of file CompressionTest.cpp.
References pdal::Options::add(), bytes, c, Support::datapath(), pdal::Dimension::Double, pdal::Stage::execute(), pdal::Dimension::Float, pdal::BasePointTable::layout(), lzma, pdal::Stage::prepare(), pdal::Dimension::Red, pdal::Stage::setOptions(), pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::size(), pdal::TEST(), pdal::Dimension::Unknown, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, pdal::Dimension::Unsigned8, pdal::Dimension::X, and pdal::Dimension::Y.