PDAL: pdal/test/unit/ConfigTest.cpp File Reference
ConfigTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/pdal_config.hpp>
Functions
TEST (ConfigTest, test_3rdparty_libs)
TEST (ConfigTest, test_version)
Function Documentation
TEST (ConfigTest , test_3rdparty_libs)
Definition at line 41 of file ConfigTest.cpp.
References pdal::IsLasZipEnabled(), and pdal::IsLibGeoTIFFEnabled().
TEST (ConfigTest , test_version)
Definition at line 55 of file ConfigTest.cpp.
References pdal::GetFullVersionString(), pdal::GetVersionInteger(), pdal::GetVersionMajor(), pdal::GetVersionMinor(), pdal::GetVersionPatch(), pdal::GetVersionString(), and conf::version.