PDAL: pdal/test/unit/filters/CropFilterTest.cpp File Reference
CropFilterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/util/FileUtils.hpp>
#include <pdal/PointView.hpp>
#include <pdal/StageFactory.hpp>
#include <io/BufferReader.hpp>
#include <io/FauxReader.hpp>
#include <io/LasReader.hpp>
#include <filters/ReprojectionFilter.hpp>
#include <filters/CropFilter.hpp>
#include <filters/StatsFilter.hpp>
#include <filters/StreamCallbackFilter.hpp>
#include "Support.hpp"
Functions
TEST (CropFilterTest, create)
TEST (CropFilterTest, test_crop)
TEST (CropFilterTest, test_crop_polygon)
TEST (CropFilterTest, test_crop_polygon_reprojection)
TEST (CropFilterTest, multibounds)
TEST (CropFilterTest, stream)
TEST (CropFilterTest, circle)
TEST (CropFilterTest, sphere)
Function Documentation
TEST (CropFilterTest , create)
Definition at line 51 of file CropFilterTest.cpp.
References pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and hag::filter().
TEST (CropFilterTest , test_crop)
Definition at line 58 of file CropFilterTest.cpp.
References pdal::Options::add(), pdal::stats::Summary::average(), pdal::Stage::execute(), hag::filter(), pdal::StatsFilter::getStats(), pdal::stats::Summary::maximum(), pdal::stats::Summary::minimum(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (CropFilterTest , test_crop_polygon)
Definition at line 120 of file CropFilterTest.cpp.
References pdal::Options::add(), pdal::FileUtils::closeFile(), Support::datapath(), pdal::Stage::execute(), pdal::FileUtils::openFile(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (CropFilterTest , test_crop_polygon_reprojection)
Definition at line 157 of file CropFilterTest.cpp.
References pdal::Options::add(), pdal::FileUtils::closeFile(), Support::datapath(), pdal::Stage::execute(), pdal::FileUtils::openFile(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (CropFilterTest , multibounds)
Definition at line 198 of file CropFilterTest.cpp.
References pdal::Options::add(), pdal::BufferReader::addView(), pdal::Stage::execute(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::PointLayout::registerDim(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (CropFilterTest , stream)
Definition at line 261 of file CropFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::PointLayout::registerDim(), pdal::StreamCallbackFilter::setCallback(), pdal::PointRef::setField(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (CropFilterTest , circle)
Definition at line 354 of file CropFilterTest.cpp.
References pdal::Options::add(), pdal::BOX3D, pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Dimension::X, and pdal::Dimension::Y.
TEST (CropFilterTest , sphere)
Definition at line 399 of file CropFilterTest.cpp.
References pdal::Options::add(), pdal::BOX3D, pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and z.