var dir_1d5bbadd870fe047ff237b24e55617ae =
[
    [ "BpfCompressor.cpp", "BpfCompressor_8cpp.html", null ],
    [ "BpfCompressor.hpp", "BpfCompressor_8hpp.html", [
      [ "BpfCompressor", "classpdal_1_1BpfCompressor.html", "classpdal_1_1BpfCompressor" ],
      [ "error", "structpdal_1_1BpfCompressor_1_1error.html", "structpdal_1_1BpfCompressor_1_1error" ]
    ] ],
    [ "BpfHeader.cpp", "BpfHeader_8cpp.html", "BpfHeader_8cpp" ],
    [ "BpfHeader.hpp", "BpfHeader_8hpp.html", "BpfHeader_8hpp" ],
    [ "BpfReader.cpp", "BpfReader_8cpp.html", "BpfReader_8cpp" ],
    [ "BpfReader.hpp", "BpfReader_8hpp.html", "BpfReader_8hpp" ],
    [ "BpfWriter.cpp", "BpfWriter_8cpp.html", "BpfWriter_8cpp" ],
    [ "BpfWriter.hpp", "BpfWriter_8hpp.html", "BpfWriter_8hpp" ],
    [ "BufferReader.hpp", "BufferReader_8hpp.html", [
      [ "BufferReader", "classpdal_1_1BufferReader.html", "classpdal_1_1BufferReader" ]
    ] ],
    [ "FauxReader.cpp", "FauxReader_8cpp.html", "FauxReader_8cpp" ],
    [ "FauxReader.hpp", "FauxReader_8hpp.html", "FauxReader_8hpp" ],
    [ "GDALGrid.cpp", "GDALGrid_8cpp.html", null ],
    [ "GDALGrid.hpp", "GDALGrid_8hpp.html", "GDALGrid_8hpp" ],
    [ "GDALReader.cpp", "GDALReader_8cpp.html", "GDALReader_8cpp" ],
    [ "GDALReader.hpp", "GDALReader_8hpp.html", "GDALReader_8hpp" ],
    [ "GDALWriter.cpp", "GDALWriter_8cpp.html", "GDALWriter_8cpp" ],
    [ "GDALWriter.hpp", "GDALWriter_8hpp.html", "GDALWriter_8hpp" ],
    [ "GeotiffSupport.cpp", "GeotiffSupport_8cpp.html", "GeotiffSupport_8cpp" ],
    [ "GeotiffSupport.hpp", "GeotiffSupport_8hpp.html", [
      [ "GeotiffSrs", "classpdal_1_1GeotiffSrs.html", "classpdal_1_1GeotiffSrs" ],
      [ "GeotiffTags", "classpdal_1_1GeotiffTags.html", "classpdal_1_1GeotiffTags" ],
      [ "error", "structpdal_1_1GeotiffTags_1_1error.html", "structpdal_1_1GeotiffTags_1_1error" ]
    ] ],
    [ "HeaderVal.hpp", "HeaderVal_8hpp.html", "HeaderVal_8hpp" ],
    [ "Ilvis2MetadataReader.cpp", "Ilvis2MetadataReader_8cpp.html", null ],
    [ "Ilvis2MetadataReader.hpp", "Ilvis2MetadataReader_8hpp.html", [
      [ "Ilvis2MetadataReader", "classpdal_1_1Ilvis2MetadataReader.html", "classpdal_1_1Ilvis2MetadataReader" ],
      [ "error", "structpdal_1_1Ilvis2MetadataReader_1_1error.html", "structpdal_1_1Ilvis2MetadataReader_1_1error" ]
    ] ],
    [ "Ilvis2Reader.cpp", "Ilvis2Reader_8cpp.html", "Ilvis2Reader_8cpp" ],
    [ "Ilvis2Reader.hpp", "Ilvis2Reader_8hpp.html", "Ilvis2Reader_8hpp" ],
    [ "LasError.hpp", "LasError_8hpp.html", [
      [ "LasError", "classpdal_1_1LasError.html", "classpdal_1_1LasError" ]
    ] ],
    [ "LasHeader.cpp", "LasHeader_8cpp.html", "LasHeader_8cpp" ],
    [ "LasHeader.hpp", "LasHeader_8hpp.html", "LasHeader_8hpp" ],
    [ "LasReader.cpp", "LasReader_8cpp.html", "LasReader_8cpp" ],
    [ "LasReader.hpp", "LasReader_8hpp.html", "LasReader_8hpp" ],
    [ "LasSummaryData.cpp", "LasSummaryData_8cpp.html", "LasSummaryData_8cpp" ],
    [ "LasSummaryData.hpp", "LasSummaryData_8hpp.html", "LasSummaryData_8hpp" ],
    [ "LasUtils.cpp", "LasUtils_8cpp.html", "LasUtils_8cpp" ],
    [ "LasUtils.hpp", "LasUtils_8hpp.html", "LasUtils_8hpp" ],
    [ "LasVLR.cpp", "LasVLR_8cpp.html", "LasVLR_8cpp" ],
    [ "LasVLR.hpp", "LasVLR_8hpp.html", "LasVLR_8hpp" ],
    [ "LasWriter.cpp", "LasWriter_8cpp.html", "LasWriter_8cpp" ],
    [ "LasWriter.hpp", "LasWriter_8hpp.html", "LasWriter_8hpp" ],
    [ "NullWriter.cpp", "NullWriter_8cpp.html", "NullWriter_8cpp" ],
    [ "NullWriter.hpp", "NullWriter_8hpp.html", "NullWriter_8hpp" ],
    [ "OGRWriter.cpp", "OGRWriter_8cpp.html", null ],
    [ "OGRWriter.hpp", "OGRWriter_8hpp.html", "OGRWriter_8hpp" ],
    [ "OGRWriterV1.cpp", "OGRWriterV1_8cpp.html", "OGRWriterV1_8cpp" ],
    [ "OptechCommon.hpp", "OptechCommon_8hpp.html", "OptechCommon_8hpp" ],
    [ "OptechReader.cpp", "OptechReader_8cpp.html", "OptechReader_8cpp" ],
    [ "OptechReader.hpp", "OptechReader_8hpp.html", "OptechReader_8hpp" ],
    [ "OptechRotationMatrix.hpp", "OptechRotationMatrix_8hpp.html", null ],
    [ "PlyReader.cpp", "PlyReader_8cpp.html", "PlyReader_8cpp" ],
    [ "PlyReader.hpp", "PlyReader_8hpp.html", "PlyReader_8hpp" ],
    [ "PlyWriter.cpp", "PlyWriter_8cpp.html", "PlyWriter_8cpp" ],
    [ "PlyWriter.hpp", "PlyWriter_8hpp.html", "PlyWriter_8hpp" ],
    [ "PtsReader.cpp", "PtsReader_8cpp.html", "PtsReader_8cpp" ],
    [ "PtsReader.hpp", "PtsReader_8hpp.html", "PtsReader_8hpp" ],
    [ "QfitReader.cpp", "QfitReader_8cpp.html", "QfitReader_8cpp" ],
    [ "QfitReader.hpp", "QfitReader_8hpp.html", "QfitReader_8hpp" ],
    [ "SbetCommon.cpp", "SbetCommon_8cpp.html", "SbetCommon_8cpp" ],
    [ "SbetCommon.hpp", "SbetCommon_8hpp.html", "SbetCommon_8hpp" ],
    [ "SbetReader.cpp", "SbetReader_8cpp.html", "SbetReader_8cpp" ],
    [ "SbetReader.hpp", "SbetReader_8hpp.html", "SbetReader_8hpp" ],
    [ "SbetWriter.cpp", "SbetWriter_8cpp.html", "SbetWriter_8cpp" ],
    [ "SbetWriter.hpp", "SbetWriter_8hpp.html", "SbetWriter_8hpp" ],
    [ "TerrasolidReader.cpp", "TerrasolidReader_8cpp.html", "TerrasolidReader_8cpp" ],
    [ "TerrasolidReader.hpp", "TerrasolidReader_8hpp.html", "TerrasolidReader_8hpp" ],
    [ "TextReader.cpp", "TextReader_8cpp.html", "TextReader_8cpp" ],
    [ "TextReader.hpp", "TextReader_8hpp.html", "TextReader_8hpp" ],
    [ "TextWriter.cpp", "TextWriter_8cpp.html", "TextWriter_8cpp" ],
    [ "TextWriter.hpp", "TextWriter_8hpp.html", "TextWriter_8hpp" ],
    [ "TIndexReader.cpp", "TIndexReader_8cpp.html", "TIndexReader_8cpp" ],
    [ "TIndexReader.hpp", "TIndexReader_8hpp.html", "TIndexReader_8hpp" ]
];