PDAL: pdal/test/unit/EigenTest.cpp File Reference
EigenTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/EigenUtils.hpp>
#include <pdal/PointView.hpp>
#include <Eigen/Dense>
#include <limits>
Functions
TEST (EigenTest, PointViewToEigen)
TEST (EigenTest, ComputeValues)
TEST (EigenTest, CheckThrow)
TEST (EigenTest, Padding)
TEST (EigenTest, Morphological)
TEST (EigenTest, RoundtripString)
Function Documentation
TEST (EigenTest , PointViewToEigen)
Definition at line 46 of file EigenTest.cpp.
References pdal::BasePointTable::layout(), pdal::eigen::pointViewToEigen(), pdal::PointLayout::registerDim(), pdal::PointView::setField(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (EigenTest , ComputeValues)
Definition at line 64 of file EigenTest.cpp.
References B, pdal::eigen::centralDiffX(), pdal::eigen::centralDiffX2(), pdal::eigen::centralDiffXY(), pdal::eigen::centralDiffY(), pdal::eigen::centralDiffY2(), pdal::eigen::computeAspectD8(), pdal::eigen::computeAspectFD(), pdal::eigen::computeContour(), pdal::eigen::computeDZDX(), pdal::eigen::computeDZDY(), pdal::eigen::computeHillshade(), pdal::eigen::computeProfile(), pdal::eigen::computeSlopeD8(), pdal::eigen::computeSlopeFD(), pdal::eigen::computeSlopeRad(), pdal::eigen::computeTangential(), pdal::eigen::computeTotal(), pdal::eigen::gradX(), pdal::eigen::gradY(), and pdal::eigen::replaceNaNs().
TEST (EigenTest , CheckThrow)
Definition at line 153 of file EigenTest.cpp.
References B, pdal::eigen::centralDiffX(), pdal::eigen::centralDiffX2(), pdal::eigen::centralDiffXY(), pdal::eigen::centralDiffY(), pdal::eigen::centralDiffY2(), pdal::eigen::computeAspectD8(), pdal::eigen::computeAspectFD(), pdal::eigen::computeContour(), pdal::eigen::computeDZDX(), pdal::eigen::computeDZDY(), pdal::eigen::computeHillshade(), pdal::eigen::computeProfile(), pdal::eigen::computeSlopeD8(), pdal::eigen::computeSlopeFD(), pdal::eigen::computeTangential(), and pdal::eigen::computeTotal().
TEST (EigenTest , Padding)
Definition at line 196 of file EigenTest.cpp.
References B, and pdal::eigen::padMatrix().
TEST (EigenTest , Morphological)
Definition at line 215 of file EigenTest.cpp.
References pdal::eigen::dilate(), pdal::eigen::dilateDiamond(), pdal::eigen::erode(), and pdal::eigen::erodeDiamond().
TEST (EigenTest , RoundtripString)
Definition at line 254 of file EigenTest.cpp.
References pdal::Utils::fromString(), and pdal::Utils::toString().