PDAL: pdal/test/unit/io/FauxReaderTest.cpp File Reference
FauxReaderTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <io/FauxReader.hpp>
Functions
TEST (FauxReaderTest, test_constant_mode_sequential_iter)
TEST (FauxReaderTest, test_random_mode)
TEST (FauxReaderTest, test_ramp_mode_1)
TEST (FauxReaderTest, test_ramp_mode_2)
TEST (FauxReaderTest, test_return_number)
TEST (FauxReaderTest, one_point)
void testGrid (point_count_t xlimit, point_count_t ylimit, point_count_t zlimit)
TEST (FauxReaderTest, grid)
Function Documentation
TEST (FauxReaderTest , test_constant_mode_sequential_iter)
Definition at line 41 of file FauxReaderTest.cpp.
References pdal::Options::add(), pdal::Dimension::OffsetTime, pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
TEST (FauxReaderTest , test_random_mode)
Definition at line 73 of file FauxReaderTest.cpp.
References pdal::Options::add(), pdal::Dimension::OffsetTime, pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
TEST (FauxReaderTest , test_ramp_mode_1)
Definition at line 111 of file FauxReaderTest.cpp.
References pdal::Options::add(), pdal::Dimension::OffsetTime, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (FauxReaderTest , test_ramp_mode_2)
Definition at line 151 of file FauxReaderTest.cpp.
References pdal::Options::add(), pdal::Dimension::OffsetTime, pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
TEST (FauxReaderTest , test_return_number)
Definition at line 187 of file FauxReaderTest.cpp.
References pdal::Options::add(), pdal::Dimension::NumberOfReturns, and pdal::Dimension::ReturnNumber.
TEST (FauxReaderTest , one_point)
Definition at line 219 of file FauxReaderTest.cpp.
References pdal::Options::add(), pdal::BOX3D, pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (FauxReaderTest , grid)
Definition at line 300 of file FauxReaderTest.cpp.
References testGrid().
void testGrid (point_count_t xlimit, point_count_t ylimit, point_count_t zlimit)
Definition at line 241 of file FauxReaderTest.cpp.
References pdal::Options::add(), pdal::BOX3D, pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::size(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by TEST().