PDAL: pdal/test/unit/FileUtilsTest.cpp File Reference
FileUtilsTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/util/FileUtils.hpp>
#include <pdal/util/Utils.hpp>
#include "Support.hpp"
Functions
TEST (FileUtilsTest, test_file_ops)
TEST (FileUtilsTest, test_readFileIntoString)
static std::string normalize (const std::string p)
static void compare_paths (const std::string a, const std::string b)
TEST (FileUtilsTest, test_toAbsolutePath)
TEST (FileUtilsTest, test_getDirectory)
TEST (FileUtilsTest, test_isAbsolute)
TEST (FileUtilsTest, filename)
TEST (FileUtilsTest, extension)
TEST (FileUtilsTest, stem)
TEST (FileUtilsTest, glob)
Variables
static const std::string drive = ""
Function Documentation
static void compare_paths (const std::string a, const std::string b) static
Definition at line 104 of file FileUtilsTest.cpp.
References normalize().
Referenced by TEST().
static std::string normalize (const std::string p) static
Definition at line 99 of file FileUtilsTest.cpp.
References pdal::Utils::replaceAll().
Referenced by compare_paths().
TEST (FileUtilsTest , test_file_ops)
Definition at line 44 of file FileUtilsTest.cpp.
References pdal::FileUtils::closeFile(), pdal::FileUtils::createFile(), pdal::FileUtils::deleteFile(), pdal::FileUtils::fileExists(), pdal::FileUtils::fileSize(), pdal::FileUtils::openFile(), pdal::FileUtils::renameFile(), and Support::temppath().
TEST (FileUtilsTest , test_readFileIntoString)
Definition at line 80 of file FileUtilsTest.cpp.
References Support::datapath(), drive, pdal::FileUtils::fileExists(), and pdal::FileUtils::readFileIntoString().
TEST (FileUtilsTest , test_toAbsolutePath)
Definition at line 109 of file FileUtilsTest.cpp.
References a, b, c, compare_paths(), drive, pdal::FileUtils::getcwd(), and pdal::FileUtils::toAbsolutePath().
TEST (FileUtilsTest , test_getDirectory)
Definition at line 137 of file FileUtilsTest.cpp.
References a, b, compare_paths(), drive, and pdal::FileUtils::getDirectory().
TEST (FileUtilsTest , test_isAbsolute)
Definition at line 148 of file FileUtilsTest.cpp.
References a, b, drive, and pdal::FileUtils::isAbsolutePath().
TEST (FileUtilsTest , filename)
Definition at line 159 of file FileUtilsTest.cpp.
References pdal::FileUtils::getFilename().
TEST (FileUtilsTest , extension)
Definition at line 188 of file FileUtilsTest.cpp.
References pdal::FileUtils::extension().
TEST (FileUtilsTest , stem)
Definition at line 196 of file FileUtilsTest.cpp.
References pdal::FileUtils::stem().
TEST (FileUtilsTest , glob)
Definition at line 206 of file FileUtilsTest.cpp.
References pdal::FileUtils::closeFile(), pdal::FileUtils::createFile(), pdal::FileUtils::deleteFile(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::FileUtils::glob(), pdal::Dimension::name(), pdal::Dimension::size(), and Support::temppath().
Variable Documentation
const std::string drive = "" static
Definition at line 96 of file FileUtilsTest.cpp.
Referenced by TEST().