PDAL: pdal/test/unit/io/GDALReaderTest.cpp File Reference
GDALReaderTest.cpp File Reference
#include <fstream>
#include <iostream>
#include <pdal/pdal_test_main.hpp>
#include <io/GDALReader.hpp>
#include "Support.hpp"
Classes
struct Point
class GDALReaderTypeTest
Functions
TEST (GDALReaderTest, badfile)
TEST (GDALReaderTest, simple)
std::ostream & operator<< (std::ostream &o, const Point &p)
bool operator< (const Point &p1, const Point &p2)
TEST_F (GDALReaderTypeTest, byte)
TEST_F (GDALReaderTypeTest, int16)
TEST_F (GDALReaderTypeTest, int32)
TEST_F (GDALReaderTypeTest, float32)
TEST_F (GDALReaderTypeTest, float64)
Class Documentation
struct Point
Definition at line 99 of file GDALReaderTest.cpp.
Class Members
double m_x
double m_y
double m_z
Function Documentation
bool operator< (const Point & p1, const Point & p2)
Definition at line 112 of file GDALReaderTest.cpp.
std::ostream& operator<< (std::ostream & o, const Point & p)
Definition at line 106 of file GDALReaderTest.cpp.
TEST (GDALReaderTest , badfile)
Definition at line 45 of file GDALReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (GDALReaderTest , simple)
Definition at line 59 of file GDALReaderTest.cpp.
References pdal::Options::add(), b, Support::datapath(), pdal::Stage::execute(), pdal::PointLayout::findDim(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::X, and pdal::Dimension::Y.
TEST_F (GDALReaderTypeTest , byte)
Definition at line 178 of file GDALReaderTest.cpp.
References compare(), and Support::datapath().
TEST_F (GDALReaderTypeTest , int16)
Definition at line 183 of file GDALReaderTest.cpp.
References compare(), and Support::datapath().
TEST_F (GDALReaderTypeTest , int32)
Definition at line 188 of file GDALReaderTest.cpp.
References compare(), and Support::datapath().
TEST_F (GDALReaderTypeTest , float32)
Definition at line 193 of file GDALReaderTest.cpp.
References compare(), and Support::datapath().
TEST_F (GDALReaderTypeTest , float64)
Definition at line 198 of file GDALReaderTest.cpp.
References compare(), and Support::datapath().