PDAL: pdal/test/unit/io/GDALWriterTest.cpp File Reference
GDALWriterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/GDALUtils.hpp>
#include <pdal/util/FileUtils.hpp>
#include <io/GDALWriter.hpp>
#include <io/LasReader.hpp>
#include <io/TextReader.hpp>
#include "Support.hpp"
#include <iostream>
#include <sstream>
Namespaces
anonymous_namespace{GDALWriterTest.cpp}
Functions
void anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter (const Options &wo, const std::string &outfile, const std::string &values)
void anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2 (const Options &wo, const std::string &outfile, const std::string &values, bool stream)
TEST (GDALWriterTest, min)
TEST (GDALWriterTest, min2)
TEST (GDALWriterTest, minWindow)
TEST (GDALWriterTest, max)
TEST (GDALWriterTest, maxWindow)
TEST (GDALWriterTest, mean)
TEST (GDALWriterTest, meanWindow)
TEST (GDALWriterTest, idw)
TEST (GDALWriterTest, idwWindow)
TEST (GDALWriterTest, count)
TEST (GDALWriterTest, stdev)
TEST (GDALWriterTest, stdevWindow)
TEST (GDALWriterTest, additionalDim)
TEST (GDALWriterTest, btbad)
TEST (GDALWriterTest, btint)
Function Documentation
TEST (GDALWriterTest , min)
Definition at line 162 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , min2)
Definition at line 183 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), and Support::temppath().
TEST (GDALWriterTest , minWindow)
Definition at line 213 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , max)
Definition at line 235 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , maxWindow)
Definition at line 256 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , mean)
Definition at line 278 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , meanWindow)
Definition at line 299 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , idw)
Definition at line 321 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , idwWindow)
Definition at line 342 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , count)
Definition at line 364 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , stdev)
Definition at line 385 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , stdevWindow)
Definition at line 406 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , additionalDim)
Definition at line 428 of file GDALWriterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
TEST (GDALWriterTest , btbad)
Definition at line 468 of file GDALWriterTest.cpp.
References pdal::Options::add(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), and Support::temppath().
TEST (GDALWriterTest , btint)
Definition at line 490 of file GDALWriterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::gdal::None, pdal::Stage::prepare(), pdal::gdal::registerDrivers(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().