PDAL: pdal/plugins/greyhound/test/GreyhoundReaderTest.cpp File Reference
GreyhoundReaderTest.cpp File Reference
#include <sstream>
#include <pdal/pdal_test_main.hpp>
#include <pdal/Writer.hpp>
#include <pdal/StageFactory.hpp>
#include <pdal/util/Algorithm.hpp>
#include <arbiter/arbiter.hpp>
#include "Support.hpp"
#include "../io/GreyhoundReader.hpp"
#include "../io/bounds.hpp"
Classes
class GreyhoundReaderTest
Namespaces
anonymous_namespace{GreyhoundReaderTest.cpp}
Functions
const std::string anonymous_namespace{GreyhoundReaderTest.cpp}::server ("http://data.greyhound.io")
const std::string anonymous_namespace{GreyhoundReaderTest.cpp}::resource ("dev/ellipsoid-multi-nyc")
const greyhound::Bounds anonymous_namespace{GreyhoundReaderTest.cpp}::full (center-radius, center+radius)
Options anonymous_namespace{GreyhoundReaderTest.cpp}::toOptions (const Json::Value &json)
std::string anonymous_namespace{GreyhoundReaderTest.cpp}::dense (const Json::Value &json)
TEST_F (GreyhoundReaderTest, tileQuery)
TEST_F (GreyhoundReaderTest, boundsQuery)
TEST_F (GreyhoundReaderTest, boundsAndDepthQuery)
TEST_F (GreyhoundReaderTest, filter)
TEST_F (GreyhoundReaderTest, singleOption)
Variables
const greyhound::Point anonymous_namespace{GreyhoundReaderTest.cpp}::center (-8242596.04, 4966606.26)
const greyhound::Point anonymous_namespace{GreyhoundReaderTest.cpp}::radius (151, 101, 51)
Function Documentation
TEST_F (GreyhoundReaderTest , tileQuery)
Definition at line 105 of file GreyhoundReaderTest.cpp.
References anonymous_namespace{GreyhoundReaderTest.cpp}::center, pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setOptions(), anonymous_namespace{GreyhoundReaderTest.cpp}::toOptions(), pdal::Dimension::X, pdal::entwine::Point::x, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST_F (GreyhoundReaderTest , boundsQuery)
Definition at line 131 of file GreyhoundReaderTest.cpp.
References anonymous_namespace{GreyhoundReaderTest.cpp}::center, pdal::entwine::Bounds::contains(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::entwine::Bounds::toJson(), anonymous_namespace{GreyhoundReaderTest.cpp}::toOptions(), pdal::Dimension::X, pdal::entwine::Point::x, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST_F (GreyhoundReaderTest , boundsAndDepthQuery)
Definition at line 159 of file GreyhoundReaderTest.cpp.
References anonymous_namespace{GreyhoundReaderTest.cpp}::center, pdal::entwine::Bounds::contains(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::entwine::Bounds::toJson(), anonymous_namespace{GreyhoundReaderTest.cpp}::toOptions(), pdal::Dimension::X, pdal::entwine::Point::x, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST_F (GreyhoundReaderTest , filter)
Definition at line 189 of file GreyhoundReaderTest.cpp.
References anonymous_namespace{GreyhoundReaderTest.cpp}::center, pdal::entwine::Bounds::contains(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::entwine::Bounds::toJson(), anonymous_namespace{GreyhoundReaderTest.cpp}::toOptions(), pdal::Dimension::X, pdal::entwine::Point::x, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST_F (GreyhoundReaderTest , singleOption)
Definition at line 228 of file GreyhoundReaderTest.cpp.
References pdal::Options::add(), anonymous_namespace{GreyhoundReaderTest.cpp}::center, pdal::entwine::Bounds::contains(), anonymous_namespace{GreyhoundReaderTest.cpp}::dense(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), anonymous_namespace{GreyhoundReaderTest.cpp}::resource(), anonymous_namespace{GreyhoundReaderTest.cpp}::server(), pdal::Stage::setOptions(), pdal::entwine::Bounds::toJson(), pdal::Dimension::X, pdal::entwine::Point::x, pdal::Dimension::Y, and pdal::Dimension::Z.