PDAL: pdal/plugins/hexbin/test/HexbinFilterTest.cpp File Reference
HexbinFilterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/SpatialReference.hpp>
#include <pdal/StageFactory.hpp>
#include <pdal/PointView.hpp>
#include <pdal/util/FileUtils.hpp>
#include "Support.hpp"
Functions
void printChildren (std::ostream &out, MetadataNode m, int depth=0)
TEST (HexbinFilterTest, HexbinFilterTest_test_1)
Function Documentation
void printChildren (std::ostream & out, MetadataNode m, int depth = 0)
Definition at line 46 of file HexbinFilterTest.cpp.
References c, pdal::MetadataNode::children(), pdal::MetadataNode::name(), and pdal::MetadataNode::value().
Referenced by TEST().
TEST (HexbinFilterTest , HexbinFilterTest_test_1)
Definition at line 59 of file HexbinFilterTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::MetadataNode::findChild(), pdal::BasePointTable::metadata(), printChildren(), and Support::temppath().