PDAL: pdal/plugins/icebridge/test/IcebridgeReaderTest.cpp File Reference
IcebridgeReaderTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/Options.hpp>
#include <pdal/PointView.hpp>
#include <pdal/PipelineManager.hpp>
#include <pdal/StageFactory.hpp>
#include <pdal/util/FileUtils.hpp>
#include "Support.hpp"
Functions
template<typename T >
void checkDimension (const PointView &data, std::size_t index, Dimension::Id dim, T expected)
void checkPoint (const PointView &data, std::size_t index, float time, float latitude, float longitude, float elevation, int xmtSig, int rcvSig, float azimuth, float pitch, float roll, float gpsPdop, float pulseWidth, float relTime)
std::string getFilePath ()
TEST (IcebridgeReaderTest, testRead)
TEST (IcebridgeReaderTest, testPipeline)
Function Documentation
template<typename T > void checkDimension (const PointView & data, std::size_t index, Dimension::Id dim, T expected)
Definition at line 48 of file IcebridgeReaderTest.cpp.
References pdal::PointView::getFieldAs().
Referenced by checkPoint().
void checkPoint (const PointView & data, std::size_t index, float time, float latitude, float longitude, float elevation, int xmtSig, int rcvSig, float azimuth, float pitch, float roll, float gpsPdop, float pulseWidth, float relTime)
Definition at line 55 of file IcebridgeReaderTest.cpp.
References pdal::Dimension::Azimuth, checkDimension(), pdal::Dimension::GpsTime, pdal::Dimension::OffsetTime, pdal::Dimension::Pdop, pdal::Dimension::Pitch, pdal::Dimension::PulseWidth, pdal::Dimension::ReflectedPulse, pdal::Dimension::Roll, pdal::Dimension::StartPulse, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
std::string getFilePath ()
Definition at line 86 of file IcebridgeReaderTest.cpp.
References Support::datapath().
Referenced by TEST().
TEST (IcebridgeReaderTest , testRead)
Definition at line 91 of file IcebridgeReaderTest.cpp.
References pdal::checkPoint(), pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and getFilePath().
TEST (IcebridgeReaderTest , testPipeline)
Definition at line 141 of file IcebridgeReaderTest.cpp.
References Support::configuredpath(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::PipelineManager::execute(), and pdal::PipelineManager::readPipeline().