PDAL: pdal/test/unit/io/Ilvis2ReaderWithMDReaderTest.cpp File Reference
Ilvis2ReaderWithMDReaderTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/Options.hpp>
#include <pdal/PointView.hpp>
#include <io/Ilvis2Reader.hpp>
#include "Support.hpp"
Functions
TEST (Ilvis2ReaderWithMDReaderTest, testInvalidMetadataFile)
TEST (Ilvis2ReaderWithMDReaderTest, testValidMetadataFile)
TEST (Ilvis2ReaderWithMDReaderTest, testNoMetadataFile)
Function Documentation
TEST (Ilvis2ReaderWithMDReaderTest , testInvalidMetadataFile)
Definition at line 45 of file Ilvis2ReaderWithMDReaderTest.cpp.
References pdal::Options::add(), and Support::datapath().
TEST (Ilvis2ReaderWithMDReaderTest , testValidMetadataFile)
Definition at line 69 of file Ilvis2ReaderWithMDReaderTest.cpp.
References pdal::Options::add(), pdal::MetadataNode::children(), Support::datapath(), and pdal::MetadataNode::value().
TEST (Ilvis2ReaderWithMDReaderTest , testNoMetadataFile)
Definition at line 100 of file Ilvis2ReaderWithMDReaderTest.cpp.
References pdal::MetadataNode::children(), and Support::datapath().