PDAL: pdal/test/unit/io/Ilvis2ReaderTest.cpp File Reference
Ilvis2ReaderTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/Options.hpp>
#include <pdal/PointView.hpp>
#include <io/Ilvis2Reader.hpp>
#include "Support.hpp"
Functions
void checkPoint (const PointView &data, PointId index, double time, double latitude, double longitude, double altitude)
TEST (Ilvis2ReaderTest, testReadDefault)
TEST (Ilvis2ReaderTest, testReadHigh)
Function Documentation
void checkPoint (const PointView & data, PointId index, double time, double latitude, double longitude, double altitude)
Definition at line 46 of file Ilvis2ReaderTest.cpp.
References checkDimension(), pdal::PointView::getFieldAs(), pdal::Dimension::GpsTime, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (Ilvis2ReaderTest , testReadDefault)
Definition at line 62 of file Ilvis2ReaderTest.cpp.
References pdal::checkPoint(), and Support::datapath().
TEST (Ilvis2ReaderTest , testReadHigh)
Definition at line 97 of file Ilvis2ReaderTest.cpp.
References pdal::Options::add(), pdal::checkPoint(), and Support::datapath().