PDAL: pdal/java/native/src/include/io_pdal_PointView.h File Reference
io_pdal_PointView.h File Reference
#include <jni.h>
Functions
JNIEXPORT jobject JNICALL Java_io_pdal_PointView_layout (JNIEnv *, jobject)
JNIEXPORT jint JNICALL Java_io_pdal_PointView_size (JNIEnv *, jobject)
JNIEXPORT jboolean JNICALL Java_io_pdal_PointView_empty (JNIEnv *, jobject)
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsProj4 (JNIEnv *, jobject)
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsWKT (JNIEnv *, jobject, jboolean)
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoint (JNIEnv *, jobject, jlong, jobjectArray)
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoints (JNIEnv *, jobject, jobjectArray)
JNIEXPORT void JNICALL Java_io_pdal_PointView_dispose (JNIEnv *, jobject)
Function Documentation
JNIEXPORT void JNICALL Java_io_pdal_PointView_dispose (JNIEnv * , jobject)
Definition at line 208 of file io_pdal_PointView.cpp.
Referenced by Java_io_pdal_PointView_getPackedPoints().
JNIEXPORT jboolean JNICALL Java_io_pdal_PointView_empty (JNIEnv * , jobject)
Definition at line 121 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_getCrsProj4(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_size().
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsProj4 (JNIEnv * , jobject)
Definition at line 129 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_getCrsWKT(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_empty().
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsWKT (JNIEnv * , jobject , jboolean)
Definition at line 137 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_getPackedPoint(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_getCrsProj4().
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoint (JNIEnv * , jobject , jlong , jobjectArray)
Definition at line 150 of file io_pdal_PointView.cpp.
References convertDimTypeJavaArrayToVector(), Java_io_pdal_PointView_getPackedPoints(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_getCrsWKT().
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoints (JNIEnv * , jobject , jobjectArray)
Definition at line 177 of file io_pdal_PointView.cpp.
References appendPackedPoint(), convertDimTypeJavaArrayToVector(), Java_io_pdal_PointView_dispose(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_getPackedPoint().
JNIEXPORT jobject JNICALL Java_io_pdal_PointView_layout (JNIEnv * , jobject)
Definition at line 97 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_size(), setHandle(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by appendPackedPoint().
JNIEXPORT jint JNICALL Java_io_pdal_PointView_size (JNIEnv * , jobject)
Definition at line 113 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_empty(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_layout().