PDAL: pdal/java/native/src/io_pdal_PointView.cpp File Reference
io_pdal_PointView.cpp File Reference
#include <stdio.h>
#include <vector>
#include "io_pdal_PointView.h"
#include "JavaPipeline.hpp"
#include "PointViewRawPtr.hpp"
#include "Accessors.hpp"
Functions
void convertDimTypeJavaArrayToVector (JNIEnv *env, jobjectArray dims, std::size_t *pointSize, DimTypeList *dimTypes)
void appendPackedPoint (PointViewPtr pv, const DimTypeList &dims, PointId idx, std::size_t pointSize, char *buf)
JNIEXPORT jobject JNICALL Java_io_pdal_PointView_layout (JNIEnv *env, jobject obj)
JNIEXPORT jint JNICALL Java_io_pdal_PointView_size (JNIEnv *env, jobject obj)
JNIEXPORT jboolean JNICALL Java_io_pdal_PointView_empty (JNIEnv *env, jobject obj)
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsProj4 (JNIEnv *env, jobject obj)
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsWKT (JNIEnv *env, jobject obj, jboolean pretty)
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoint (JNIEnv *env, jobject obj, jlong idx, jobjectArray dims)
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoints (JNIEnv *env, jobject obj, jobjectArray dims)
JNIEXPORT void JNICALL Java_io_pdal_PointView_dispose (JNIEnv *env, jobject obj)
Function Documentation
void appendPackedPoint (PointViewPtr pv, const DimTypeList & dims, PointId idx, std::size_t pointSize, char * buf)
Fill a buffer with point data specified by the dimension list, accounts index Using this functions it is possible to pack all points into one buffer
Parameters
[in] pv PointView pointer.
[in] dims List of dimensions/types to retrieve.
[in] idx Index of point to get.
[in] buf Pointer to buffer to fill.
Definition at line 88 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_layout().
Referenced by Java_io_pdal_PointView_getPackedPoints().
void convertDimTypeJavaArrayToVector (JNIEnv * env, jobjectArray dims, std::size_t * pointSize, DimTypeList * dimTypes)
Converts JavaArray of DimTypes (In Java interpretation DimType is a pair of strings) into DimTypeList (vector of DimTypes), puts dim size into bufSize
Parameters
[in] env JNI environment
[in] dims JavaArray of DimTypes
[in] bufSize Dims sum size
[in] dimTypes Vector of DimTypes
Definition at line 60 of file io_pdal_PointView.cpp.
References pdal::Dimension::id(), pdal::Dimension::size(), and pdal::Dimension::type().
Referenced by Java_io_pdal_PointView_getPackedPoint(), and Java_io_pdal_PointView_getPackedPoints().
JNIEXPORT void JNICALL Java_io_pdal_PointView_dispose (JNIEnv * env, jobject obj)
Definition at line 208 of file io_pdal_PointView.cpp.
Referenced by Java_io_pdal_PointView_getPackedPoints().
JNIEXPORT jboolean JNICALL Java_io_pdal_PointView_empty (JNIEnv * env, jobject obj)
Definition at line 121 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_getCrsProj4(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_size().
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsProj4 (JNIEnv * env, jobject obj)
Definition at line 129 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_getCrsWKT(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_empty().
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsWKT (JNIEnv * env, jobject obj, jboolean pretty)
Definition at line 137 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_getPackedPoint(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_getCrsProj4().
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoint (JNIEnv * env, jobject obj, jlong idx, jobjectArray dims)
Definition at line 150 of file io_pdal_PointView.cpp.
References convertDimTypeJavaArrayToVector(), Java_io_pdal_PointView_getPackedPoints(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_getCrsWKT().
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoints (JNIEnv * env, jobject obj, jobjectArray dims)
Definition at line 177 of file io_pdal_PointView.cpp.
References appendPackedPoint(), convertDimTypeJavaArrayToVector(), Java_io_pdal_PointView_dispose(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_getPackedPoint().
JNIEXPORT jobject JNICALL Java_io_pdal_PointView_layout (JNIEnv * env, jobject obj)
Definition at line 97 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_size(), setHandle(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by appendPackedPoint().
JNIEXPORT jint JNICALL Java_io_pdal_PointView_size (JNIEnv * env, jobject obj)
Definition at line 113 of file io_pdal_PointView.cpp.
References Java_io_pdal_PointView_empty(), and libpdaljava::PointViewRawPtr::shared_pointer.
Referenced by Java_io_pdal_PointView_layout().