PDAL: pdal/java/native/src/io_pdal_PointLayout.cpp File Reference
io_pdal_PointLayout.cpp File Reference
#include <stdio.h>
#include <vector>
#include "io_pdal_PointLayout.h"
#include "JavaPipeline.hpp"
#include "Accessors.hpp"
Functions
JNIEXPORT jobjectArray JNICALL Java_io_pdal_PointLayout_dimTypes (JNIEnv *env, jobject obj)
JNIEXPORT jobject JNICALL Java_io_pdal_PointLayout_findDimType (JNIEnv *env, jobject obj, jstring jstr)
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimSize (JNIEnv *env, jobject obj, jstring jstr)
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimPackedOffset (JNIEnv *env, jobject obj, jstring jstr)
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_pointSize (JNIEnv *env, jobject obj)
JNIEXPORT void JNICALL Java_io_pdal_PointLayout_dispose (JNIEnv *env, jobject obj)
Function Documentation
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimPackedOffset (JNIEnv * env, jobject obj, jstring jstr)
Definition at line 98 of file io_pdal_PointLayout.cpp.
References Java_io_pdal_PointLayout_pointSize(), and pdal::Dimension::name().
Referenced by Java_io_pdal_PointLayout_dimSize().
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimSize (JNIEnv * env, jobject obj, jstring jstr)
Definition at line 89 of file io_pdal_PointLayout.cpp.
References pdal::PointLayout::dimSize(), and Java_io_pdal_PointLayout_dimPackedOffset().
Referenced by Java_io_pdal_PointLayout_findDimType().
JNIEXPORT jobjectArray JNICALL Java_io_pdal_PointLayout_dimTypes (JNIEnv * env, jobject obj)
Definition at line 45 of file io_pdal_PointLayout.cpp.
References pdal::PointLayout::dimTypes(), pdal::Dimension::interpretationName(), Java_io_pdal_PointLayout_findDimType(), pdal::Dimension::name(), and pdal::Dimension::type().
JNIEXPORT void JNICALL Java_io_pdal_PointLayout_dispose (JNIEnv * env, jobject obj)
Definition at line 127 of file io_pdal_PointLayout.cpp.
Referenced by Java_io_pdal_PointLayout_pointSize().
JNIEXPORT jobject JNICALL Java_io_pdal_PointLayout_findDimType (JNIEnv * env, jobject obj, jstring jstr)
Definition at line 73 of file io_pdal_PointLayout.cpp.
References pdal::Dimension::interpretationName(), Java_io_pdal_PointLayout_dimSize(), pdal::Dimension::name(), and pdal::Dimension::type().
Referenced by Java_io_pdal_PointLayout_dimTypes().
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_pointSize (JNIEnv * env, jobject obj)
Definition at line 120 of file io_pdal_PointLayout.cpp.
References Java_io_pdal_PointLayout_dispose(), and pdal::PointLayout::pointSize().
Referenced by Java_io_pdal_PointLayout_dimPackedOffset().