PDAL: pdal/java/native/src/io_pdal_Pipeline.cpp File Reference
io_pdal_Pipeline.cpp File Reference
#include <stdio.h>
#include <iostream>
#include <string>
#include "io_pdal_Pipeline.h"
#include "JavaPipeline.hpp"
#include "JavaIterator.hpp"
#include "Accessors.hpp"
Functions
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_initialise (JNIEnv *env, jobject obj)
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_dispose (JNIEnv *env, jobject obj)
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_execute (JNIEnv *env, jobject obj)
JNIEXPORT jstring JNICALL Java_io_pdal_Pipeline_getMetadata (JNIEnv *env, jobject obj)
JNIEXPORT jstring JNICALL Java_io_pdal_Pipeline_getSchema (JNIEnv *env, jobject obj)
JNIEXPORT jboolean JNICALL Java_io_pdal_Pipeline_validate (JNIEnv *env, jobject obj)
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_setLogLevel (JNIEnv *env, jobject obj, jint i)
JNIEXPORT jint JNICALL Java_io_pdal_Pipeline_getLogLevel (JNIEnv *env, jobject obj)
JNIEXPORT jstring JNICALL Java_io_pdal_Pipeline_getLog (JNIEnv *env, jobject obj)
JNIEXPORT jobject JNICALL Java_io_pdal_Pipeline_getPointViews (JNIEnv *env, jobject obj)
Function Documentation
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_dispose (JNIEnv * env, jobject obj)
Definition at line 62 of file io_pdal_Pipeline.cpp.
References Java_io_pdal_Pipeline_execute().
Referenced by Java_io_pdal_Pipeline_initialise().
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_execute (JNIEnv * env, jobject obj)
Definition at line 70 of file io_pdal_Pipeline.cpp.
References libpdaljava::Pipeline::execute(), and Java_io_pdal_Pipeline_getMetadata().
Referenced by Java_io_pdal_Pipeline_dispose().
JNIEXPORT jstring JNICALL Java_io_pdal_Pipeline_getLog (JNIEnv * env, jobject obj)
Definition at line 123 of file io_pdal_Pipeline.cpp.
References libpdaljava::Pipeline::getLog(), and Java_io_pdal_Pipeline_getPointViews().
Referenced by Java_io_pdal_Pipeline_getLogLevel().
JNIEXPORT jint JNICALL Java_io_pdal_Pipeline_getLogLevel (JNIEnv * env, jobject obj)
Definition at line 116 of file io_pdal_Pipeline.cpp.
References libpdaljava::Pipeline::getLogLevel(), and Java_io_pdal_Pipeline_getLog().
Referenced by Java_io_pdal_Pipeline_setLogLevel().
JNIEXPORT jstring JNICALL Java_io_pdal_Pipeline_getMetadata (JNIEnv * env, jobject obj)
Definition at line 77 of file io_pdal_Pipeline.cpp.
References libpdaljava::Pipeline::getMetadata(), and Java_io_pdal_Pipeline_getSchema().
Referenced by Java_io_pdal_Pipeline_execute().
JNIEXPORT jobject JNICALL Java_io_pdal_Pipeline_getPointViews (JNIEnv * env, jobject obj)
Definition at line 130 of file io_pdal_Pipeline.cpp.
References libpdaljava::Pipeline::getPointViews(), and setHandle().
Referenced by Java_io_pdal_Pipeline_getLog().
JNIEXPORT jstring JNICALL Java_io_pdal_Pipeline_getSchema (JNIEnv * env, jobject obj)
Definition at line 84 of file io_pdal_Pipeline.cpp.
References libpdaljava::Pipeline::getSchema(), and Java_io_pdal_Pipeline_validate().
Referenced by Java_io_pdal_Pipeline_getMetadata().
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_initialise (JNIEnv * env, jobject obj)
Definition at line 53 of file io_pdal_Pipeline.cpp.
References c, Java_io_pdal_Pipeline_dispose(), and setHandle().
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_setLogLevel (JNIEnv * env, jobject obj, jint i)
Definition at line 109 of file io_pdal_Pipeline.cpp.
References Java_io_pdal_Pipeline_getLogLevel(), and libpdaljava::Pipeline::setLogLevel().
Referenced by Java_io_pdal_Pipeline_validate().
JNIEXPORT jboolean JNICALL Java_io_pdal_Pipeline_validate (JNIEnv * env, jobject obj)
Definition at line 91 of file io_pdal_Pipeline.cpp.
References Java_io_pdal_Pipeline_setLogLevel(), and libpdaljava::Pipeline::validate().
Referenced by Java_io_pdal_Pipeline_getSchema().