PDAL: pdal/java/native/src/include/io_pdal_PointLayout.h File Reference
io_pdal_PointLayout.h File Reference
#include <jni.h>
Functions
JNIEXPORT jobjectArray JNICALL Java_io_pdal_PointLayout_dimTypes (JNIEnv *, jobject)
JNIEXPORT jobject JNICALL Java_io_pdal_PointLayout_findDimType (JNIEnv *, jobject, jstring)
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimSize (JNIEnv *, jobject, jstring)
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimPackedOffset (JNIEnv *, jobject, jstring)
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_pointSize (JNIEnv *, jobject)
JNIEXPORT void JNICALL Java_io_pdal_PointLayout_dispose (JNIEnv *, jobject)
Function Documentation
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimPackedOffset (JNIEnv * , jobject , jstring)
Definition at line 98 of file io_pdal_PointLayout.cpp.
References Java_io_pdal_PointLayout_pointSize(), and pdal::Dimension::name().
Referenced by Java_io_pdal_PointLayout_dimSize().
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimSize (JNIEnv * , jobject , jstring)
Definition at line 89 of file io_pdal_PointLayout.cpp.
References pdal::PointLayout::dimSize(), and Java_io_pdal_PointLayout_dimPackedOffset().
Referenced by Java_io_pdal_PointLayout_findDimType().
JNIEXPORT jobjectArray JNICALL Java_io_pdal_PointLayout_dimTypes (JNIEnv * , jobject)
Definition at line 45 of file io_pdal_PointLayout.cpp.
References pdal::PointLayout::dimTypes(), pdal::Dimension::interpretationName(), Java_io_pdal_PointLayout_findDimType(), pdal::Dimension::name(), and pdal::Dimension::type().
JNIEXPORT void JNICALL Java_io_pdal_PointLayout_dispose (JNIEnv * , jobject)
Definition at line 127 of file io_pdal_PointLayout.cpp.
Referenced by Java_io_pdal_PointLayout_pointSize().
JNIEXPORT jobject JNICALL Java_io_pdal_PointLayout_findDimType (JNIEnv * , jobject , jstring)
Definition at line 73 of file io_pdal_PointLayout.cpp.
References pdal::Dimension::interpretationName(), Java_io_pdal_PointLayout_dimSize(), pdal::Dimension::name(), and pdal::Dimension::type().
Referenced by Java_io_pdal_PointLayout_dimTypes().
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_pointSize (JNIEnv * , jobject)
Definition at line 120 of file io_pdal_PointLayout.cpp.
References Java_io_pdal_PointLayout_dispose(), and pdal::PointLayout::pointSize().
Referenced by Java_io_pdal_PointLayout_dimPackedOffset().