PDAL: pdal/test/unit/KDIndexTest.cpp File Reference
KDIndexTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/KDIndex.hpp>
Functions
TEST (KDIndex, neighbors2D)
TEST (KDIndex, neighbors3D)
TEST (KDIndex, neighbordims)
TEST (KDIndex, radius2D)
TEST (KDIndex, radius3D)
Function Documentation
TEST (KDIndex , neighbors2D)
Definition at line 40 of file KDIndexTest.cpp.
References pdal::KDIndex< DIM >::build(), pdal::BasePointTable::layout(), pdal::KD2Index::neighbor(), pdal::KD2Index::neighbors(), pdal::PointView::point(), pdal::PointLayout::registerDim(), pdal::PointView::setField(), pdal::Dimension::X, and pdal::Dimension::Y.
TEST (KDIndex , neighbors3D)
Definition at line 118 of file KDIndexTest.cpp.
References pdal::KDIndex< DIM >::build(), pdal::BasePointTable::layout(), pdal::KD3Index::neighbor(), pdal::KD3Index::neighbors(), pdal::PointView::point(), pdal::PointLayout::registerDim(), pdal::PointView::setField(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (KDIndex , neighbordims)
Definition at line 202 of file KDIndexTest.cpp.
References pdal::BasePointTable::layout(), pdal::PointLayout::registerDim(), pdal::PointView::setField(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (KDIndex , radius2D)
Definition at line 235 of file KDIndexTest.cpp.
References pdal::KDIndex< DIM >::build(), pdal::BasePointTable::layout(), pdal::PointView::point(), pdal::KD2Index::radius(), pdal::PointLayout::registerDim(), pdal::PointView::setField(), pdal::Dimension::X, and pdal::Dimension::Y.
TEST (KDIndex , radius3D)
Definition at line 294 of file KDIndexTest.cpp.
References pdal::KDIndex< DIM >::build(), pdal::BasePointTable::layout(), pdal::PointView::point(), pdal::KD3Index::radius(), pdal::PointLayout::registerDim(), pdal::PointView::setField(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.