PDAL: pdal/test/unit/io/LasReaderTest.cpp File Reference
LasReaderTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/Filter.hpp>
#include <pdal/PointView.hpp>
#include <pdal/StageFactory.hpp>
#include <io/LasReader.hpp>
#include "Support.hpp"
Namespaces
anonymous_namespace{LasReaderTest.cpp}
Functions
template<typename LeftIter , typename RightIter >
::testing::AssertionResult anonymous_namespace{LasReaderTest.cpp}::CheckEqualCollections (LeftIter left_begin, LeftIter left_end, RightIter right_begin)
TEST (LasReaderTest, create)
TEST (LasReaderTest, header)
TEST (LasReaderTest, test_sequential)
static void test_a_format (const std::string &file, uint8_t majorVersion, uint8_t minorVersion, int pointFormat, double xref, double yref, double zref, double tref, uint16_t rref, uint16_t gref, uint16_t bref)
TEST (LasReaderTest, test_different_formats)
TEST (LasReaderTest, inspect)
TEST (LasReaderTest, test_vlr)
TEST (LasReaderTest, testInvalidFileSignature)
TEST (LasReaderTest, extraBytes)
TEST (LasReaderTest, callback)
void streamTest (const std::string src, const std::string compression)
TEST (LasReaderTest, stream)
TEST (LasReaderTest, LasHeaderIncorrentPointcount)
TEST (LasReaderTest, EmptyGeotiffVlr)
TEST (LasReaderTest, IgnoreVLRs)
Function Documentation
void streamTest (const std::string src, const std::string compression)
Definition at line 397 of file LasReaderTest.cpp.
References pdal::Options::add(), c, Support::datapath(), pdal::Stage::execute(), pdal::PointRef::getPackedData(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
Referenced by TEST().
TEST (LasReaderTest , create)
Definition at line 71 of file LasReaderTest.cpp.
References pdal::StageFactory::createStage(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
TEST (LasReaderTest , header)
Definition at line 80 of file LasReaderTest.cpp.
References pdal::Options::add(), pdal::LasHeader::compressed(), pdal::LasHeader::compressionInfo(), pdal::LasHeader::creationDOY(), pdal::LasHeader::creationYear(), Support::datapath(), pdal::LasHeader::fileSignature(), pdal::LasHeader::fileSourceId(), pdal::LasReader::header(), pdal::Uuid::isNull(), pdal::LasHeader::maxX(), pdal::LasHeader::maxY(), pdal::LasHeader::maxZ(), pdal::LasHeader::minX(), pdal::LasHeader::minY(), pdal::LasHeader::minZ(), pdal::LasHeader::offsetX(), pdal::LasHeader::offsetY(), pdal::LasHeader::offsetZ(), pdal::LasHeader::pointCount(), pdal::LasHeader::pointCountByReturn(), pdal::LasHeader::pointFormat(), pdal::Stage::prepare(), pdal::LasHeader::projectId(), pdal::LasHeader::scaleX(), pdal::LasHeader::scaleY(), pdal::LasHeader::scaleZ(), pdal::Stage::setOptions(), pdal::LasHeader::versionMajor(), pdal::LasHeader::versionMinor(), and pdal::LasHeader::vlrOffset().
TEST (LasReaderTest , test_sequential)
Definition at line 125 of file LasReaderTest.cpp.
References pdal::Options::add(), Support::check_p0_p1_p2(), Support::check_p100_p101_p102(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (LasReaderTest , test_different_formats)
Definition at line 174 of file LasReaderTest.cpp.
References test_a_format().
TEST (LasReaderTest , inspect)
Definition at line 189 of file LasReaderTest.cpp.
References pdal::Options::add(), anonymous_namespace{LasReaderTest.cpp}::CheckEqualCollections(), Support::datapath(), pdal::SpatialReference::getWKT(), pdal::QuickInfo::m_bounds, pdal::QuickInfo::m_dimNames, pdal::QuickInfo::m_pointCount, pdal::QuickInfo::m_srs, pdal::Stage::preview(), and pdal::Stage::setOptions().
TEST (LasReaderTest , test_vlr)
Definition at line 229 of file LasReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::MetadataNode::empty(), pdal::Stage::execute(), pdal::MetadataNode::findChild(), pdal::Stage::getMetadata(), pdal::Dimension::name(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (LasReaderTest , testInvalidFileSignature)
Definition at line 253 of file LasReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::LasReader::header(), pdal::Stage::setOptions(), and pdal::LasHeader::valid().
TEST (LasReaderTest , extraBytes)
Definition at line 265 of file LasReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::Signed8, pdal::Dimension::Unsigned16, and pdal::Dimension::Unsigned64.
TEST (LasReaderTest , callback)
Definition at line 329 of file LasReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::Dimension::id(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Reader::setReadCb(), and pdal::TEST().
TEST (LasReaderTest , stream)
Definition at line 459 of file LasReaderTest.cpp.
References Support::datapath(), and streamTest().
TEST (LasReaderTest , LasHeaderIncorrentPointcount)
Definition at line 474 of file LasReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (LasReaderTest , EmptyGeotiffVlr)
Definition at line 490 of file LasReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (LasReaderTest , IgnoreVLRs)
Definition at line 507 of file LasReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::MetadataNode::empty(), pdal::Stage::execute(), pdal::MetadataNode::findChild(), pdal::Stage::getMetadata(), pdal::Dimension::name(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
static void test_a_format (const std::string & file, uint8_t majorVersion, uint8_t minorVersion, int pointFormat, double xref, double yref, double zref, double tref, uint16_t rref, uint16_t gref, uint16_t bref) static
Definition at line 148 of file LasReaderTest.cpp.
References pdal::Options::add(), Support::check_pN(), Support::datapath(), pdal::Stage::execute(), pdal::LasReader::header(), pdal::LasHeader::pointFormat(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::LasHeader::versionMajor(), and pdal::LasHeader::versionMinor().
Referenced by TEST().