PDAL: pdal/test/unit/io/LasWriterTest.cpp File Reference
LasWriterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <stdlib.h>
#include <pdal/PointView.hpp>
#include <pdal/StageFactory.hpp>
#include <pdal/StageWrapper.hpp>
#include <pdal/util/FileUtils.hpp>
#include <io/BufferReader.hpp>
#include <io/LasHeader.hpp>
#include <io/LasReader.hpp>
#include <io/LasWriter.hpp>
#include <io/BpfReader.hpp>
#include "Support.hpp"
Classes
class pdal::LasTester
Namespaces
pdal
Functions
TEST (LasWriterTest, srs)
TEST (LasWriterTest, srs2)
TEST (LasWriterTest, auto_offset)
TEST (LasWriterTest, extra_dims)
TEST (LasWriterTest, all_extra_dims)
TEST (LasWriterTest, forward)
TEST (LasWriterTest, forwardvlr)
TEST (LasWriterTest, flex)
TEST (LasWriterTest, flex2)
void compareFiles (const std::string &name1, const std::string &name2, size_t increment=100)
TEST (LasWriterTest, stream)
TEST (LasWriterTest, streamhashwrite)
TEST (LasWriterTest, fix1063_1064_1065)
TEST (LasWriterTest, pdal_metadata)
TEST (LasWriterTest, pdal_add_vlr)
TEST (LasWriterTest, forward_spec_3)
TEST (LasWriterTest, oversize_vlr)
Function Documentation
void compareFiles (const std::string & name1, const std::string & name2, size_t increment = 100)
Definition at line 818 of file LasWriterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
Referenced by TEST().
TEST (LasWriterTest , srs)
Definition at line 71 of file LasWriterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::LasTester::srs(), and Support::temppath().
TEST (LasWriterTest , srs2)
Definition at line 95 of file LasWriterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::LasTester::srs(), and Support::temppath().
TEST (LasWriterTest , auto_offset)
Definition at line 120 of file LasWriterTest.cpp.
References pdal::Options::add(), pdal::BufferReader::addView(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::LasReader::header(), pdal::BasePointTable::layout(), pdal::LasHeader::offsetX(), pdal::Stage::prepare(), pdal::PointLayout::registerDim(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), and pdal::Dimension::X.
TEST (LasWriterTest , extra_dims)
Definition at line 169 of file LasWriterTest.cpp.
References pdal::Options::add(), pdal::LasHeader::basePointLen(), Support::datapath(), pdal::Stage::execute(), pdal::PointLayout::findDim(), pdal::LasTester::header(), pdal::BasePointTable::layout(), pdal::LasHeader::pointLen(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), and pdal::Dimension::Unknown.
TEST (LasWriterTest , all_extra_dims)
Definition at line 235 of file LasWriterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::PointLayout::findDim(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (LasWriterTest , forward)
Definition at line 292 of file LasWriterTest.cpp.
References pdal::Options::add(), pdal::Stage::addOptions(), pdal::StageFactory::createStage(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::MetadataNode::findChild(), pdal::Stage::getMetadata(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), and pdal::MetadataNode::value().
TEST (LasWriterTest , forwardvlr)
Definition at line 357 of file LasWriterTest.cpp.
References pdal::Options::add(), pdal::Stage::addOptions(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::MetadataNode::findChildren(), pdal::Stage::prepare(), pdal::BasePointTable::privateMetadata(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Utils::startsWith(), and Support::temppath().
TEST (LasWriterTest , flex)
Definition at line 402 of file LasWriterTest.cpp.
References pdal::Options::add(), pdal::BufferReader::addView(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::FileUtils::fileExists(), pdal::QuickInfo::m_pointCount, pdal::Stage::prepare(), pdal::Stage::preview(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
TEST (LasWriterTest , flex2)
Definition at line 464 of file LasWriterTest.cpp.
References pdal::Options::add(), pdal::BufferReader::addView(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::FileUtils::fileExists(), pdal::LasHeader::findVlr(), pdal::LasReader::header(), pdal::QuickInfo::m_pointCount, pdal::Stage::prepare(), pdal::Stage::preview(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), pdal::TEST(), and pdal::LasHeader::vlrs().
TEST (LasWriterTest , stream)
Definition at line 863 of file LasWriterTest.cpp.
References pdal::Options::add(), compareFiles(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
TEST (LasWriterTest , streamhashwrite)
Definition at line 890 of file LasWriterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
TEST (LasWriterTest , fix1063_1064_1065)
Definition at line 913 of file LasWriterTest.cpp.
References pdal::Options::add(), Support::binpath(), pdal::Dimension::ClassFlags, Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::MetadataNode::findChild(), pdal::Stage::getMetadata(), pdal::SpatialReference::getWKT(), pdal::Stage::prepare(), pdal::Utils::run_shell_command(), pdal::Stage::setOptions(), Support::temppath(), and pdal::MetadataNode::value().
TEST (LasWriterTest , pdal_metadata)
Definition at line 953 of file LasWriterTest.cpp.
References pdal::Options::add(), pdal::MetadataNode::children(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::getMetadata(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
TEST (LasWriterTest , pdal_add_vlr)
Definition at line 994 of file LasWriterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::MetadataNode::findChildren(), pdal::Stage::getMetadata(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Utils::startsWith(), and Support::temppath().
TEST (LasWriterTest , forward_spec_3)
Definition at line 1041 of file LasWriterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::MetadataNode::findChildren(), pdal::Stage::getMetadata(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Utils::startsWith(), and Support::temppath().
TEST (LasWriterTest , oversize_vlr)
Definition at line 1100 of file LasWriterTest.cpp.
References pdal::Options::add(), pdal::Stage::addOptions(), pdal::LasTester::addVlr(), and pdal::Stage::prepare().