PDAL: pdal/test/unit/MetadataTest.cpp File Reference
MetadataTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/Metadata.hpp>
#include <pdal/SpatialReference.hpp>
Functions
TEST (MetadataTest, assign)
TEST (MetadataTest, test_construction)
TEST (MetadataTest, typed_value)
TEST (MetadataTest, test_construction_with_srs)
TEST (MetadataTest, test_metadata_copy)
TEST (MetadataTest, test_metadata_set)
TEST (MetadataTest, test_vlr_metadata)
TEST (MetadataTest, find_child_string)
TEST (MetadataTest, test_float)
TEST (MetadataTest, pointer)
Function Documentation
TEST (MetadataTest , assign)
Definition at line 42 of file MetadataTest.cpp.
References pdal::MetadataNode::name().
TEST (MetadataTest , test_construction)
Definition at line 50 of file MetadataTest.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addEncoded(), pdal::MetadataNode::type(), and pdal::MetadataNode::value().
TEST (MetadataTest , typed_value)
Definition at line 139 of file MetadataTest.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addEncoded(), pdal::Utils::redirect(), pdal::Utils::restore(), and pdal::MetadataNode::value().
TEST (MetadataTest , test_construction_with_srs)
Definition at line 160 of file MetadataTest.cpp.
References pdal::MetadataNode::add(), and pdal::MetadataNode::type().
TEST (MetadataTest , test_metadata_copy)
Definition at line 183 of file MetadataTest.cpp.
References pdal::MetadataNode::add(), pdal::Utils::fromString(), and pdal::MetadataNode::value().
TEST (MetadataTest , test_metadata_set)
Definition at line 192 of file MetadataTest.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::children(), pdal::MetadataNode::find(), pdal::MetadataNode::findChild(), pdal::MetadataNode::name(), pdal::Dimension::name(), and pdal::MetadataNode::value().
TEST (MetadataTest , test_vlr_metadata)
Definition at line 227 of file MetadataTest.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::description(), pdal::MetadataNode::find(), pdal::MetadataNode::name(), pdal::Utils::startsWith(), and pdal::MetadataNode::value().
TEST (MetadataTest , find_child_string)
Definition at line 262 of file MetadataTest.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::findChild(), and pdal::MetadataNode::value().
TEST (MetadataTest , test_float)
TEST(MetadataTest, sanitize) { MetadataNode top(" Test;semicolon:colon space'apostrophe\"quote:"); EXPECT_EQ(top.name(), "_Test_semicolon_colon_space_apostrophe_quote_"); }
Definition at line 287 of file MetadataTest.cpp.
References pdal::MetadataNode::add(), and pdal::MetadataNode::value().
TEST (MetadataTest , pointer)
Definition at line 298 of file MetadataTest.cpp.
References pdal::MetadataNode::add(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and pdal::MetadataNode::value().