PDAL: pdal::gdal::anonymous_namespace{GDALUtils.cpp} Namespace Reference
pdal::gdal::anonymous_namespace{GDALUtils.cpp} Namespace Reference
Functions
Dimension::Type toPdalType (const std::string &gdalType)
Dimension::Type toPdalType (GDALDataType t)
GDALDataType toGdalType (Dimension::Type t)
Function Documentation
GDALDataType pdal::gdal::anonymous_namespace{GDALUtils.cpp}::toGdalType (Dimension::Type t)
Definition at line 114 of file GDALUtils.cpp.
References pdal::Dimension::Double, pdal::Dimension::Float, pdal::Dimension::None, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed64, pdal::Dimension::Signed8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, pdal::Dimension::Unsigned64, and pdal::Dimension::Unsigned8.
Referenced by pdal::gdal::Raster::open().
Dimension::Type pdal::gdal::anonymous_namespace{GDALUtils.cpp}::toPdalType (const std::string & gdalType)
Convert a GDAL type string to a PDAL dimension type.
Parameters
gdalType String representing the GDAL type.
Returns
PDAL type associated with .
Definition at line 63 of file GDALUtils.cpp.
References pdal::Dimension::Double, pdal::Dimension::Float, pdal::Dimension::None, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, and pdal::Dimension::Unsigned8.
Dimension::Type pdal::gdal::anonymous_namespace{GDALUtils.cpp}::toPdalType (GDALDataType t)
Definition at line 83 of file GDALUtils.cpp.
References pdal::Dimension::Double, pdal::Dimension::Float, pdal::Dimension::None, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned32, and pdal::Dimension::Unsigned8.
Referenced by pdal::gdal::Raster::computePDALDimensionTypes(), and pdal::gdal::Raster::validateType().