PDAL: anonymous_namespace{SpatialReference.cpp} Namespace Reference
anonymous_namespace{SpatialReference.cpp} Namespace Reference
Classes
struct OGRDeleter
Typedefs
using OGRScopedSpatialReference = std::unique_ptr< OGRSpatialReference, OGRDeleter >
Functions
OGRScopedSpatialReference ogrCreateSrs (std::string s="")
Typedef Documentation
using anonymous_namespace{SpatialReference.cpp}::OGRScopedSpatialReference = typedef std::unique_ptr<OGRSpatialReference, OGRDeleter>
Definition at line 74 of file SpatialReference.cpp.
Function Documentation
OGRScopedSpatialReference anonymous_namespace{SpatialReference.cpp}::ogrCreateSrs (std::string s = "")
Definition at line 76 of file SpatialReference.cpp.
Referenced by pdal::SpatialReference::computeUTMZone(), pdal::SpatialReference::equals(), pdal::SpatialReference::getHorizontal(), pdal::SpatialReference::getHorizontalUnits(), pdal::SpatialReference::getUTMZone(), pdal::SpatialReference::getVertical(), pdal::SpatialReference::getVerticalUnits(), pdal::SpatialReference::isGeocentric(), pdal::SpatialReference::isGeographic(), pdal::SpatialReference::prettyWkt(), and pdal::SpatialReference::valid().