PDAL: pdal::lasdump Namespace Reference
pdal::lasdump Namespace Reference
Namespaces
anonymous_namespace{Dumper.cpp}
anonymous_namespace{Header.cpp}
Classes
class Dumper
class EVlr
struct Exception
class Header
class Vlr
Typedefs
typedef uint8_t PointFormat
Functions
ILeStream & operator>> (ILeStream &in, Header &h)
std::ostream & operator<< (std::ostream &out, const Header &h)
std::ostream & operator<< (std::ostream &out, const Exception &ex)
int32_t cksum (const void *c, size_t size)
int32_t cksum (const std::vector< char > &v)
int32_t cksum (const std::vector< unsigned char > &v)
std::ostream & operator<< (std::ostream &out, Vlr &v)
ILeStream & operator>> (ILeStream &in, Vlr &v)
ILeStream & operator>> (ILeStream &in, EVlr &v)
Typedef Documentation
typedef uint8_t pdal::lasdump::PointFormat
Definition at line 49 of file Header.hpp.
Function Documentation
int32_t pdal::lasdump::cksum (const void * c, size_t size)
Definition at line 62 of file Lasdump.hpp.
References c.
Referenced by cksum(), operator<<(), pdal::lasdump::Dumper::readCompressedPoints(), and pdal::lasdump::Dumper::readPoints().
int32_t pdal::lasdump::cksum (const std::vector< char > & v)
Definition at line 80 of file Lasdump.hpp.
References cksum().
int32_t pdal::lasdump::cksum (const std::vector< unsigned char > & v)
Definition at line 85 of file Lasdump.hpp.
References cksum().
std::ostream& pdal::lasdump::operator<< (std::ostream & out, const Exception & ex)
Definition at line 55 of file Lasdump.hpp.
References pdal::lasdump::Exception::m_text.
std::ostream& pdal::lasdump::operator<< (std::ostream & out, Vlr & v)
Definition at line 72 of file Vlr.hpp.
References cksum(), pdal::lasdump::Vlr::m_data, pdal::lasdump::Vlr::m_description, pdal::lasdump::Vlr::m_recordId, pdal::lasdump::Vlr::m_recordSig, and pdal::lasdump::Vlr::m_userId.
std::ostream& pdal::lasdump::operator<< (std::ostream & out, const Header & h)
Definition at line 173 of file Header.cpp.
References pdal::lasdump::Header::m_createDOY, pdal::lasdump::Header::m_createYear, pdal::lasdump::Header::m_eVlrCount, pdal::lasdump::Header::m_eVlrOffset, pdal::lasdump::Header::m_fileSig, pdal::lasdump::Header::m_globalEncoding, pdal::lasdump::Header::m_isCompressed, pdal::lasdump::Header::m_offsets, pdal::lasdump::Header::m_pointCount, pdal::lasdump::Header::m_pointCountByReturn, pdal::lasdump::Header::m_pointFormat, pdal::lasdump::Header::m_pointOffset, pdal::lasdump::Header::m_projectGuid, pdal::lasdump::Header::m_scales, pdal::lasdump::Header::m_softwareId, pdal::lasdump::Header::m_sourceId, pdal::lasdump::Header::m_systemId, pdal::lasdump::Header::m_versionMinor, pdal::lasdump::Header::m_vlrCount, pdal::lasdump::Header::m_vlrOffset, pdal::lasdump::Header::maxX(), pdal::lasdump::Header::maxY(), pdal::lasdump::Header::maxZ(), pdal::lasdump::Header::minX(), pdal::lasdump::Header::minY(), pdal::lasdump::Header::minZ(), pdal::lasdump::Header::RETURN_COUNT, and pdal::lasdump::Header::versionAtLeast().
ILeStream& pdal::lasdump::operator>> (ILeStream & in, Vlr & v)
Definition at line 83 of file Vlr.hpp.
References pdal::lasdump::Vlr::dataLen(), pdal::IStream::get(), pdal::lasdump::Vlr::m_data, pdal::lasdump::Vlr::m_description, pdal::lasdump::Vlr::m_recordId, pdal::lasdump::Vlr::m_recordSig, and pdal::lasdump::Vlr::m_userId.
ILeStream& pdal::lasdump::operator>> (ILeStream & in, EVlr & v)
Definition at line 97 of file Vlr.hpp.
References pdal::lasdump::Vlr::dataLen(), pdal::IStream::get(), pdal::lasdump::Vlr::m_data, pdal::lasdump::Vlr::m_description, pdal::lasdump::Vlr::m_recordId, pdal::lasdump::Vlr::m_recordSig, and pdal::lasdump::Vlr::m_userId.
ILeStream& pdal::lasdump::operator>> (ILeStream & in, Header & h)
Definition at line 108 of file Header.cpp.
References pdal::BOX3D, for(), pdal::IStream::get(), if(), pdal::lasdump::Header::LEGACY_RETURN_COUNT, pdal::lasdump::Header::m_bounds, pdal::lasdump::Header::m_createDOY, pdal::lasdump::Header::m_createYear, pdal::lasdump::Header::m_eVlrCount, pdal::lasdump::Header::m_eVlrOffset, pdal::lasdump::Header::m_fileSig, pdal::lasdump::Header::m_globalEncoding, pdal::lasdump::Header::m_offsets, pdal::lasdump::Header::m_pointCount, pdal::lasdump::Header::m_pointCountByReturn, pdal::lasdump::Header::m_pointFormat, pdal::lasdump::Header::m_pointLen, pdal::lasdump::Header::m_pointOffset, pdal::lasdump::Header::m_projectGuid, pdal::lasdump::Header::m_scales, pdal::lasdump::Header::m_softwareId, pdal::lasdump::Header::m_sourceId, pdal::lasdump::Header::m_systemId, pdal::lasdump::Header::m_versionMinor, pdal::lasdump::Header::m_vlrCount, pdal::lasdump::Header::m_vlrOffset, pdal::lasdump::Header::maxX(), pdal::lasdump::Header::maxY(), pdal::lasdump::Header::maxZ(), pdal::lasdump::Header::minX(), pdal::lasdump::Header::minY(), pdal::lasdump::Header::minZ(), pdal::lasdump::Header::RETURN_COUNT, pdal::lasdump::Header::setCompressed(), pdal::lasdump::Header::signatureValid(), pdal::lasdump::Header::versionAtLeast(), and pdal::lasdump::Header::versionMajor().