PDAL: pdal::plang Namespace Reference
pdal::plang Namespace Reference
Classes
class Environment
class Invocation
class Redirector
class Script
struct Stdout
Typedefs
typedef Environment * EnvironmentPtr
Functions
std::string getTraceback ()
PyObject * fromMetadata (MetadataNode m)
std::string readPythonString (PyObject *dict, const std::string &key)
void addMetadata (PyObject *dict, MetadataNode m)
PyObject * getPyJSON (std::string const &str)
static PyObject * Stdout_write (PyObject *self, PyObject *args)
static PyObject * Stdout_flush (PyObject *self, PyObject *)
PyMODINIT_FUNC redirector_init (void)
std::ostream & operator<< (std::ostream &os, Script const &script)
Variables
static Environment * g_environment =0
static PyMethodDef Stdout_methods []
static PyTypeObject StdoutType
Class Documentation
struct pdal::plang::Stdout
Definition at line 24 of file Redirector.cpp.
Class Members
stdout_flush_type flush
PyObject_HEAD stdout_write_type write
Typedef Documentation
typedef Environment* pdal::plang::EnvironmentPtr
Definition at line 64 of file Environment.hpp.
Function Documentation
void pdal::plang::addMetadata (PyObject * dict, MetadataNode m)
Definition at line 280 of file Environment.cpp.
References pdal::MetadataNode::addWithType(), pdal::Dimension::description(), pdal::Metadata::inferType(), pdal::Dimension::name(), readPythonString(), and pdal::Dimension::type().
Referenced by pdal::plang::Invocation::end().
PyObject * pdal::plang::fromMetadata (MetadataNode m)
Definition at line 231 of file Environment.cpp.
References pdal::MetadataNode::children(), pdal::Dimension::description(), pdal::MetadataNode::description(), pdal::MetadataNode::name(), pdal::Dimension::name(), pdal::Dimension::type(), pdal::MetadataNode::type(), and pdal::MetadataNode::value().
Referenced by pdal::plang::Invocation::begin().
PyObject* pdal::plang::getPyJSON (std::string const & str)
Definition at line 328 of file Invocation.cpp.
References getTraceback().
Referenced by pdal::plang::Invocation::begin(), and pdal::plang::Invocation::setKWargs().
std::string pdal::plang::getTraceback ()
Definition at line 145 of file Environment.cpp.
References pdal::Dimension::size(), and pdal::Dimension::type().
Referenced by pdal::plang::Invocation::compile(), pdal::plang::Invocation::execute(), and getPyJSON().
PDAL_DLL std::ostream & pdal::plang::operator<< (std::ostream & os, Script const & script)
Definition at line 56 of file Script.cpp.
References pdal::plang::Script::function(), pdal::plang::Script::module(), and pdal::plang::Script::source().
Referenced by pdal::PointView::getTemp().
std::string pdal::plang::readPythonString (PyObject * dict, const std::string & key)
Definition at line 255 of file Environment.cpp.
References pdal::Dimension::size().
Referenced by addMetadata().
PyMODINIT_FUNC pdal::plang::redirector_init (void)
Definition at line 138 of file Redirector.cpp.
References pdal::plang::Redirector::init(), and Stdout_methods.
Referenced by pdal::plang::Environment::Environment().
static PyObject* pdal::plang::Stdout_flush (PyObject * self, PyObject *) static
Definition at line 50 of file Redirector.cpp.
References pdal::plang::Stdout::flush.
static PyObject* pdal::plang::Stdout_write (PyObject * self, PyObject * args) static
Definition at line 32 of file Redirector.cpp.
References pdal::plang::Stdout::write.
Variable Documentation
Environment* pdal::plang::g_environment =0 static
Definition at line 81 of file Environment.cpp.
Referenced by pdal::plang::Environment::get().
PyMethodDef pdal::plang::Stdout_methods[] static
Initial value:
=
{
    {"write", Stdout_write, METH_VARARGS, "sys.stdout.write"},
    {"flush", Stdout_flush, METH_VARARGS, "sys.stdout.flush"},
    {0, 0, 0, 0}
}
Definition at line 61 of file Redirector.cpp.
Referenced by redirector_init().
PyTypeObject pdal::plang::StdoutType static
Definition at line 69 of file Redirector.cpp.