PDAL: pdal::PipelineWriter Namespace Reference
pdal::PipelineWriter Namespace Reference
Typedefs
typedef std::map< const Stage *, std::string > TagMap
Functions
PDAL_DLL void writePipeline (Stage *stage, const std::string &filename)
PDAL_DLL void writePipeline (Stage *stage, std::ostream &strm)
Typedef Documentation
typedef std::map<const Stage *, std::string> pdal::PipelineWriter::TagMap
Definition at line 49 of file PipelineWriter.hpp.
Function Documentation
PDAL_DLL void pdal::PipelineWriter::writePipeline (Stage * stage, const std::string & filename)
Definition at line 85 of file PipelineWriter.cpp.
References pdal::Utils::closeFile(), and pdal::Utils::createFile().
Referenced by pdal::LasWriter::addPipelineVlr(), pdal::InfoKernel::dump(), pdal::PipelineKernel::execute(), pdal::TranslateKernel::execute(), and pdal::PipelineExecutor::getPipeline().
PDAL_DLL void pdal::PipelineWriter::writePipeline (Stage * stage, std::ostream & strm)
Definition at line 92 of file PipelineWriter.cpp.
References pdal::anonymous_namespace{PipelineWriter.cpp}::generateTags(), pdal::Stage::serialize(), and pdal::Utils::toJSON().