PDAL: pdal::gdal Namespace Reference
pdal::gdal Namespace Reference
Namespaces
anonymous_namespace{GDALUtils.cpp}
Classes
class Band
struct CantReadBlock
struct CantWriteBlock
class ErrorHandler
class ErrorHandlerSuspender
class Geometry
struct InvalidBand
class Raster
class SpatialRef
Typedefs
template<typename ITER >
using ITER_VAL = typename std::iterator_traits< ITER >::value_type
typedef std::shared_ptr< void > RefPtr
Enumerations
enum GDALError {
GDALError::None, GDALError::NotOpen, GDALError::CantOpen, GDALError::NoData,
GDALError::InvalidBand, GDALError::NoTransform, GDALError::NotInvertible, GDALError::CantReadBlock,
GDALError::InvalidDriver, GDALError::DriverNotFound, GDALError::CantCreate, GDALError::InvalidOption,
GDALError::CantWriteBlock, GDALError::InvalidType
}
Functions
bool reprojectBounds (BOX3D &box, const std::string &srcSrs, const std::string &dstSrs)
bool reprojectBounds (BOX2D &box, const std::string &srcSrs, const std::string &dstSrs)
bool reprojectPoint (double &x, double &y, double &z, const std::string &srcSrs, const std::string &dstSrs)
std::string lastError ()
void registerDrivers ()
void unregisterDrivers ()
Variables
static ErrorHandler * s_gdalErrorHandler = 0
Class Documentation
struct pdal::gdal::CantReadBlock
Definition at line 300 of file GDALUtils.hpp.
struct pdal::gdal::InvalidBand
Definition at line 299 of file GDALUtils.hpp.
Typedef Documentation
template<typename ITER > using pdal::gdal::ITER_VAL = typedef typename std::iterator_traits<ITER>::value_type
Definition at line 64 of file GDALUtils.hpp.
typedef std::shared_ptr<void> pdal::gdal::RefPtr
Definition at line 76 of file GDALUtils.hpp.
Enumeration Type Documentation
enum pdal::gdal::GDALError strong
Enumerator
None
NotOpen
CantOpen
NoData
InvalidBand
NoTransform
NotInvertible
CantReadBlock
InvalidDriver
DriverNotFound
CantCreate
InvalidOption
CantWriteBlock
InvalidType
Definition at line 281 of file GDALUtils.hpp.
Function Documentation
PDAL_DLL std::string pdal::gdal::lastError ()
Definition at line 223 of file GDALUtils.cpp.
Referenced by pdal::NitfWriter::reprojectBoxToDD().
PDAL_DLL void pdal::gdal::registerDrivers ()
Definition at line 231 of file GDALUtils.cpp.
Referenced by pdal::DensityKernel::execute(), pdal::TIndexKernel::execute(), pdal::OciWriter::initialize(), pdal::OciReader::initialize(), pdal::GDALWriter::initialize(), pdal::GDALReader::initialize(), pdal::OGRWriter::initialize(), pdal::TIndexReader::initialize(), pdal::ColorizationFilter::initialize(), pdal::OverlayFilter::initialize(), pdal::ColorinterpFilter::ready(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), TEST(), and pdal::eigen::writeMatrix().
PDAL_DLL bool pdal::gdal::reprojectBounds (BOX3D & box, const std::string & srcSrs, const std::string & dstSrs)
Reproject a bounds box from a source projection to a destination.
Parameters
box Bounds box to be reprojected in-place.
srcSrs String in WKT or other suitable format of box coordinates.
dstSrs String in WKT or other suitable format to which coordinates should be projected.
Returns
Whether the reprojection was successful or not.
Definition at line 154 of file GDALUtils.cpp.
References pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
Referenced by reprojectBounds(), pdal::NitfWriter::reprojectBoxToDD(), pdal::CropFilter::transform(), pdal::nitfwrap::NitfWrap::verifyBpf(), and pdal::nitfwrap::NitfWrap::verifyLas().
PDAL_DLL bool pdal::gdal::reprojectBounds (BOX2D & box, const std::string & srcSrs, const std::string & dstSrs)
Reproject a bounds box from a source projection to a destination.
Parameters
box 2D Bounds box to be reprojected in-place.
srcSrs String in WKT or other suitable format of box coordinates.
dstSrs String in WKT or other suitable format to which coordinates should be projected.
Returns
Whether the reprojection was successful or not.
Definition at line 183 of file GDALUtils.cpp.
References b, reprojectBounds(), and pdal::BOX3D::to2d().
PDAL_DLL bool pdal::gdal::reprojectPoint (double & x, double & y, double & z, const std::string & srcSrs, const std::string & dstSrs)
Reproject a point from a source projection to a destination.
Parameters
x X coordinate of point to be reprojected.
y Y coordinate of point to be reprojected.
z Z coordinate of point to be reprojected.
srcSrs String in WKT or other suitable format of box coordinates.
dstSrs String in WKT or other suitable format to which coordinates should be projected.
Returns
Whether the reprojection was successful or not.
Definition at line 203 of file GDALUtils.cpp.
Referenced by pdal::CropFilter::transform().
PDAL_DLL void pdal::gdal::unregisterDrivers ()
Definition at line 245 of file GDALUtils.cpp.
Referenced by App::execute().
Variable Documentation
ErrorHandler* pdal::gdal::s_gdalErrorHandler = 0 static
Definition at line 229 of file GDALUtils.cpp.
Referenced by pdal::gdal::ErrorHandler::getGlobalErrorHandler().