PDAL: anonymous_namespace{OCITest.cpp} Namespace Reference
anonymous_namespace{OCITest.cpp} Namespace Reference
Functions
static std::string connectString (TestConfig::oracleConnection())
static const std::string baseTableName ("PDAL_TEST_BASE")
static const std::string blockTableName ("PDAL_TEST_BLOCKS")
Function Documentation
static const std::string anonymous_namespace{OCITest.cpp}::baseTableName ("PDAL_TEST_BASE") static
Referenced by OCITest::cleanup(), OCITest::SetUp(), writeData(), and writerOptions().
static const std::string anonymous_namespace{OCITest.cpp}::blockTableName ("PDAL_TEST_BLOCKS") static
Referenced by OCITest::cleanup(), OCITest::SetUp(), writeData(), and writerOptions().
static std::string anonymous_namespace{OCITest.cpp}::connectString (TestConfig::oracleConnection()) static
Referenced by OCITest::connect(), main(), readerOptions(), ShouldRunTest(), writeData(), and writerOptions().