PDAL: anonymous_namespace{ReprojectionFilterTest.cpp} Namespace Reference
anonymous_namespace{ReprojectionFilterTest.cpp} Namespace Reference
Functions
void getPoint (const PointView &data, double &x, double &y, double &z)
Function Documentation
void anonymous_namespace{ReprojectionFilterTest.cpp}::getPoint (const PointView & data, double & x, double & y, double & z)
Definition at line 50 of file ReprojectionFilterTest.cpp.
References pdal::PointView::getFieldAs(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by pdal::SimplePointTable::getDimension(), pdal::BasePointTable::supportsView(), pdal::PointTable::supportsView(), TEST(), and pdal::TEST().