PDAL: anonymous_namespace{BPFTest.cpp} Namespace Reference
anonymous_namespace{BPFTest.cpp} Namespace Reference
Functions
template<typename LeftIter , typename RightIter >
::testing::AssertionResult CheckEqualCollections (LeftIter left_begin, LeftIter left_end, RightIter right_begin)
void test_file_type_view (const std::string &filename)
void test_file_type_stream (const std::string &filename)
void test_file_type (const std::string &filename)
void test_roundtrip (Options &writerOps)
Function Documentation
template<typename LeftIter , typename RightIter > ::testing::AssertionResult anonymous_namespace{BPFTest.cpp}::CheckEqualCollections (LeftIter left_begin, LeftIter left_end, RightIter right_begin)
Definition at line 55 of file BPFTest.cpp.
References setup::message.
Referenced by TEST().
void anonymous_namespace{BPFTest.cpp}::test_file_type (const std::string & filename)
Definition at line 209 of file BPFTest.cpp.
References test_file_type_stream(), and test_file_type_view().
Referenced by TEST(), and test_roundtrip().
void anonymous_namespace{BPFTest.cpp}::test_file_type_stream (const std::string & filename)
Definition at line 134 of file BPFTest.cpp.
References pdal::Options::add(), c, pdal::PointRef::getFieldAs(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by test_file_type().
void anonymous_namespace{BPFTest.cpp}::test_file_type_view (const std::string & filename)
Definition at line 78 of file BPFTest.cpp.
References pdal::Options::add(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by test_file_type().
void anonymous_namespace{BPFTest.cpp}::test_roundtrip (Options & writerOps)
Definition at line 216 of file BPFTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), and test_file_type().
Referenced by TEST().