PDAL: pdal Namespace Reference
pdal Namespace Reference
Namespaces
anonymous_namespace{Bounds.cpp}
anonymous_namespace{ColorizationFilter.cpp}
anonymous_namespace{CpdFilter.cpp}
anonymous_namespace{CpdFilterTest.cpp}
anonymous_namespace{DimBuilder.cpp}
anonymous_namespace{FileUtils.cpp}
anonymous_namespace{GeotiffSupport.cpp}
anonymous_namespace{GreyhoundReader.cpp}
anonymous_namespace{IcebridgeReader.cpp}
anonymous_namespace{IcpFilterTest.cpp}
anonymous_namespace{InfoKernel.cpp}
anonymous_namespace{LasReader.cpp}
anonymous_namespace{LasUtils.cpp}
anonymous_namespace{MbFormat.cpp}
anonymous_namespace{MortonOrderFilter.cpp}
anonymous_namespace{OptechReaderTest.cpp}
anonymous_namespace{pdal_types.hpp}
anonymous_namespace{PDALUtils.cpp}
anonymous_namespace{PipelineWriter.cpp}
anonymous_namespace{PluginManager.cpp}
anonymous_namespace{ProgramArgs.hpp}
anonymous_namespace{SplitKernel.cpp}
anonymous_namespace{TerrasolidReaderTest.cpp}
anonymous_namespace{XMLSchema.cpp}
Dimension
eigen
entwine
FileUtils
filter
gdal
georeference
geos
hdf5
hexdensity
lasdump
LasUtils
MbError
mlang
nitfwrap
pclsupport
pipeline
PipelineWriter
plang
python
Segmentation
stats
Utils
Classes
class ApproximateCoplanarFilter
class Arg
class arg_error
class arg_val_error
class AssignFilter
struct AssignRange
class BaseHeaderVal
class BasePointTable
class BaseVArg
class BeExtractor
class BeInserter
class blob
class Block
class Bounds
class BOX2D
class BOX3D
class BpfCompressor
struct BpfDimension
struct BpfHeader
struct BpfMuellerMatrix
struct BpfPolarFrame
struct BpfPolarHeader
struct BpfPolarStokesParam
class BpfReader
struct BpfUlemFile
struct BpfUlemFrame
struct BpfUlemHeader
class BpfWriter
class BufferReader
struct cbctx
class Charbuf
class ChipperFilter
class ChipPtRef
class ChipRefList
class ClusterFilter
struct CollectTriangles
struct CollectTrianglesVisitor
class ColorinterpFilter
class ColorizationFilter
class ColorPointViewSource
class column
class compression_error
class ComputeRangeFilter
class connection_failed
class CpdFilter
class CropFilter
struct CsdHeader
struct CsdPulse
class DbReader
class DbWriter
class DecimationFilter
class DeltaKernel
class DensityKernel
class DiffKernel
class DimBuilder
struct dimbuilder_error
struct DimIndex
struct DimRange
struct DimSpec
struct DimType
class DividerFilter
class DoubleHeaderVal
struct DummyPlugin
class DynamicLibrary
class EigenvaluesFilter
class ELMFilter
class EstimateRankFilter
union Everything
class ExtLasVLR
class ExtraBytesIf
struct ExtraBytesSpec
class Extractor
struct ExtraDim
class FauxReader
class FerryFilter
struct FileStreamDeleter
class Filter
class FilterWrapper
class FixedPointTable
class FlexWriter
class GDALGrid
class GDALReader
class GDALWriter
class Geometry
class GeotiffSrs
class GeotiffTags
class GeoWaveReader
class GeoWaveWriter
class GreedyProjection
GreedyProjectionTriangulation is an implementation of a greedy triangulation algorithm for 3D points based on local 2D projections. It assumes locally smooth surfaces and relatively smooth transitions between areas with different point densities.
class GreyhoundReader
class GridProjectionFilter
class GroundKernel
class GroupByFilter
class HAGFilter
class HausdorffKernel
class Hdf5Handler
class HeadFilter
class HexBin
class IBeStream
class IcebridgeReader
class IcpFilter
class ILeStream
class Ilvis2MetadataReader
class Ilvis2Reader
struct Indices
class InfoKernel
class Inserter
class IQRFilter
class IStream
class IStreamMarker
Stream position marker with rewinding support.
class ISwitchableStream
class json
class jsonWithHexer
class jsonWithLAZ
class jsonWithNITF
class jsonWithP2G
class KD2Index
class KD3Index
class KDIndex
class KDistanceFilter
class Kernel
class LasError
class LasHeader
class LasReader
class LasSummaryData
class LasTester
class LasVLR
class LasWriter
class LeExtractor
class LeInserter
class LocateFilter
class LOFFilter
class Log
class MADFilter
class MatlabFilter
class MatlabReader
class MatlabWriter
class MatlabWriterTest
class MbFormat
class MbReader
class MergeFilter
class MergeKernel
class Mesh
class Metadata
class MetadataNode
class MetadataNodeImpl
class MetadataReader
class MongusFilter
class MortonOrderFilter
class MovingLeastSquaresFilter
class MrsidReader
class MyFilter
class MyKernel
class MyReader
class MyWriter
class NitfFileReader
class NitfFileWriter
class NitfReader
class NitfWriter
class NormalFilter
class NullOStream
class NullStreambuf
class NullWriter
class NumHeaderVal
class OBeStream
class OciReader
class OciWriter
struct OGRDataSourceDeleter
struct OGRFeatureDeleter
class OGRWriter
class OLeStream
class OptechReader
class Option
class Options
class OSGReader
class OStream
class OStreamMarker
Stream position marker with rewinding/reset support.
class OutlierFilter
class OverlayFilter
struct OW_CellDepth
class OWConnection
class OWStatement
class Patch
class PcdReader
class PcdWriter
class PCLBlock
class PCLKernel
class pdal_error
class PgReader
class PgWriter
class PipelineExecutor
class PipelineKernel
class PipelineManager
class PipelineReaderJSON
struct PluginInfo
class PluginManager
class PlyReader
class PlyWriter
class PMFFilter
struct Point
class PointContainer
class PointIdxRef
class PointLayout
class PointRef
class PointTable
class PointView
class PointViewIter
struct PointViewLess
class PointViewMesh
class PointViewSource
class PoissonFilter
class Polygon
class ProgramArgs
class PtsReader
class PythonFilter
class QfitReader
class QuadIndex
struct QuadPointRef
struct QuickInfo
class RadialDensityFilter
class RandomizeFilter
class RandomKernel
class RangeFilter
class Reader
class ReprojectionFilter
class RxpPointcloud
class RxpReader
class SampleFilter
class SbetReader
class SbetWriter
class Scaling
struct sdo_geometry
struct sdo_geometry_ind
struct sdo_georaster
struct sdo_georaster_ind
struct sdo_mbr
struct sdo_mbr_ind
struct sdo_orgscl_type
struct sdo_orgscl_type_ind
struct sdo_pc
struct sdo_pc_blk
struct sdo_pc_blk_type_ind
struct sdo_pc_ind
struct sdo_point_type
struct sdo_point_type_ind
class SimplePointTable
class SmoothKernel
class SMRFilter
class SortFilter
class SortKernel
class SpatialReference
class SplitKernel
class SplitterFilter
class SQLite
class SQLiteReader
class SQLiteWriter
class Stage
struct StageCreationOptions
class StageFactory
class StageRunner
class StageWrapper
class StatsFilter
class StreamCallbackFilter
class StreamPointTable
class StringHeaderVal
class SwitchableExtractor
class TailFilter
class TArg
class TArg< bool >
struct TerraSolidHeader
class TerrasolidReader
class TextReader
class TextWriter
class TIndexKernel
class TIndexReader
class TransformationFilter
class TransformationFilterTest
class TranslateKernel
struct Tree
class Triangle
class TriangularMesh
struct uuid
class Uuid
class UuidHeaderVal
class VArg
class VArg< std::string >
struct VlrOptionInfo
class VoxelCenterNearestNeighborFilter
class VoxelCentroidNearestNeighborFilter
class VoxelGridFilter
class Writer
class WriterWrapper
struct XForm
struct XMLDim
class XMLSchema
Typedefs
typedef std::shared_ptr< std::ostream > FileStreamPtr
typedef std::unordered_map< int, std::vector< PointId > > PointIdHash
typedef std::pair< double, double > Coord
typedef std::shared_ptr< void > OGRDSPtr
typedef std::shared_ptr< void > OGRFeaturePtr
typedef std::shared_ptr< void > OGRGeometryPtr
typedef std::array< double, 16 > TransformationMatrix
typedef std::vector< BpfDimension > BpfDimensionList
typedef std::unique_ptr< GDALGrid > GDALGridPtr
typedef std::map< std::string, Dimension::Id > DimensionMap
typedef uint8_t PointFormat
typedef std::vector< LasVLR > VlrList
typedef std::unique_ptr< TerraSolidHeader > TerraSolidHeaderPtr
typedef std::map< std::string, DimIndex > DimIndexMap
using BlockCb = std::function< void(char *buf, size_t bufsize)>
typedef char LazPerfVlrCompressor
typedef char LazPerfVlrDecompressor
typedef std::vector< DimType > DimTypeList
typedef std::shared_ptr< PointView > PointViewPtr
typedef std::unique_ptr< GEOSGeometry, geos::GeometryDeleter > GEOSGeomPtr
typedef std::shared_ptr< Log > LogPtr
typedef std::shared_ptr< MetadataNodeImpl > MetadataNodeImplPtr
typedef std::vector< MetadataNodeImplPtr > MetadataImplList
typedef std::map< std::string, MetadataImplList > MetadataSubnodes
typedef std::vector< MetadataNode > MetadataNodeList
typedef std::shared_ptr< Metadata > MetadataPtr
typedef std::map< std::string, Options > OptionsMap
typedef uint64_t PointId
typedef uint64_t point_count_t
typedef std::vector< std::string > StringList
typedef std::unique_ptr< PipelineManager > PipelineManagerPtr
typedef PointLayout * PointLayoutPtr
typedef BasePointTable & PointTableRef
typedef BasePointTable const & ConstPointTableRef
typedef std::set< PointViewPtr, PointViewLess > PointViewSet
typedef std::shared_ptr< StageRunner > StageRunnerPtr
typedef std::vector< XMLDim > XMLDimList
typedef std::shared_ptr< OWConnection > Connection
typedef std::shared_ptr< OWStatement > Statement
typedef std::shared_ptr< Block > BlockPtr
typedef struct pdal::cbctx cbctx
typedef OCIRef SDO_GEORASTER_ref
typedef OCIRef SDO_GEOMETRY_ref
typedef OCIRef SDO_POINT_TYPE_ref
typedef OCIArray sdo_elem_info_array
typedef OCIArray sdo_ordinate_array
typedef OCIArray SDO_NUMBER_ARRAY_TYPE
typedef struct sdo_point_type sdo_point_type
typedef struct sdo_point_type_ind sdo_point_type_ind
typedef struct sdo_geometry SDO_GEOMETRY_TYPE
typedef struct SDO_GEOMETRY_ind SDO_GEOMETRY_ind
typedef struct sdo_georaster SDO_GEORASTER_TYPE
typedef struct sdo_georaster_ind SDO_GEORASTER_ind
typedef struct sdo_mbr SDO_MBR_TYPE
typedef struct sdo_mbr_ind SDO_MBR_ind
typedef struct sdo_orgscl_type SDO_ORGSCL_TYPE
typedef struct sdo_orgscl_type_ind SDO_ORGSCL_TYPE_ind
typedef struct sdo_pc SDO_PC_TYPE
typedef struct sdo_pc_ind SDO_PC_ind
typedef struct sdo_pc_blk SDO_PC_BLK_TYPE
typedef struct sdo_pc_blk_type_ind SDO_PC_BLK_TYPE_ind
typedef std::vector< column > row
typedef std::vector< row > records
typedef std::shared_ptr< Patch > PatchPtr
Enumerations
enum SortOrder { SortOrder::ASC, SortOrder::DESC }
enum BpfFormat { BpfFormat::DimMajor, BpfFormat::PointMajor, BpfFormat::ByteMajor }
enum BpfCoordType { BpfCoordType::Cartesian, BpfCoordType::UTM, BpfCoordType::TCR, BpfCoordType::ENU }
enum BpfCompression { BpfCompression::None, BpfCompression::QuickLZ, BpfCompression::FastLZ, BpfCompression::Zlib }
enum Mode {
Mode::Constant, Mode::Random, Mode::Ramp, Mode::Uniform,
Mode::Normal, Mode::Grid
}
enum LasCompression { LasCompression::LasZip, LasCompression::LazPerf, LasCompression::None }
enum QFIT_Format_Type { QFIT_Format_10 = 10, QFIT_Format_12 = 12, QFIT_Format_14 = 14, QFIT_Format_Unknown = 128 }
enum TERRASOLID_Format_Type { TERRASOLID_Format_1 = 20010712, TERRASOLID_Format_2 = 20020715, TERRASOLID_Format_Unknown = 999999999 }
enum CompressionType {
CompressionType::None = 0, CompressionType::Ght = 1, CompressionType::Dimensional = 2, CompressionType::Lazperf = 3,
CompressionType::Unknown = 256
}
enum MetadataType { MetadataType::Instance, MetadataType::Array }
enum LogLevel {
LogLevel::Error = 0, LogLevel::Warning, LogLevel::Info, LogLevel::Debug,
LogLevel::Debug1, LogLevel::Debug2, LogLevel::Debug3, LogLevel::Debug4,
LogLevel::Debug5, LogLevel::None
}
enum Orientation { Orientation::PointMajor, Orientation::DimensionMajor }
Functions
CREATE_SHARED_PLUGIN (1, 0, MyKernel, Kernel, s_info)
template<typename T >
T convert (const StringList &s, const std::string &name, size_t fieldno)
CREATE_SHARED_PLUGIN (1, 0, MyWriter, Writer, s_info)
std::istream & operator>> (std::istream &in, AssignRange &r)
std::ostream & operator<< (std::ostream &out, const AssignRange &r)
std::shared_ptr< gdal::Raster > openRamp (std::string &rampFilename)
std::istream & operator>> (std::istream &in, DividerFilter::Mode &mode)
std::ostream & operator<< (std::ostream &out, const DividerFilter::Mode &mode)
bool isVisible (const Eigen::Vector2d &X, const Eigen::Vector2d &S1, const Eigen::Vector2d &S2, const Eigen::Vector2d &R=Eigen::Vector2d::Zero())
Returns if a point X is visible from point R (or the origin) when taking into account the segment between the points S1 and S2.
bool operator< (const DimRange &r1, const DimRange &r2)
std::istream & operator>> (std::istream &in, DimRange &r)
std::ostream & operator<< (std::ostream &out, const DimRange &r)
std::istream & operator>> (std::istream &in, SortOrder &order)
std::ostream & operator<< (std::ostream &out, const SortOrder &order)
TransformationMatrix transformationMatrixFromString (const std::string &s)
std::istream & operator>> (std::istream &in, BpfFormat &format)
std::ostream & operator<< (std::ostream &out, const BpfFormat &format)
ILeStream & operator>> (ILeStream &stream, BpfMuellerMatrix &m)
OLeStream & operator<< (OLeStream &stream, BpfMuellerMatrix &m)
std::istream & operator>> (std::istream &in, BpfWriter::CoordId &id)
std::ostream & operator<< (std::ostream &out, const BpfWriter::CoordId &id)
std::istream & operator>> (std::istream &in, Mode &m)
std::ostream & operator<< (std::ostream &out, const Mode &m)
CREATE_STATIC_PLUGIN (1, 0, GDALReader, Reader, s_info)
CREATE_STATIC_PLUGIN (1, 0, GDALWriter, Writer, s_info)
template<typename T , T MIN, T MAX>
std::istream & operator>> (std::istream &in, NumHeaderVal< T, MIN, MAX > &h)
template<typename T , T MIN, T MAX>
std::ostream & operator<< (std::ostream &out, const NumHeaderVal< T, MIN, MAX > &h)
std::istream & operator>> (std::istream &in, DoubleHeaderVal &h)
template<size_t LEN>
std::istream & operator>> (std::istream &in, StringHeaderVal< LEN > &h)
template<size_t LEN>
std::ostream & operator<< (std::ostream &out, const StringHeaderVal< LEN > &h)
std::istream & operator>> (std::istream &in, UuidHeaderVal &h)
std::ostream & operator<< (std::ostream &out, const UuidHeaderVal &h)
std::istream & operator>> (std::istream &in, Ilvis2Reader::IlvisMapping &mval)
std::ostream & operator<< (std::ostream &out, const Ilvis2Reader::IlvisMapping &mval)
std::string GetDefaultSoftwareId ()
ILeStream & operator>> (ILeStream &in, LasHeader &h)
OLeStream & operator<< (OLeStream &out, const LasHeader &h)
std::ostream & operator<< (std::ostream &out, const LasHeader &h)
template<typename T >
void addForwardMetadata (MetadataNode &forward, MetadataNode &m, const std::string &name, T val, const std::string description="")
std::ostream & operator<< (std::ostream &ostr, const LasSummaryData &data)
std::istream & operator>> (std::istream &in, LasCompression &c)
std::ostream & operator<< (std::ostream &out, const LasCompression &c)
bool operator== (const ExtraDim &ed1, const ExtraDim &ed2)
ILeStream & operator>> (ILeStream &in, LasVLR &v)
OLeStream & operator<< (OLeStream &out, const LasVLR &v)
ILeStream & operator>> (ILeStream &in, ExtLasVLR &v)
OLeStream & operator<< (OLeStream &out, const ExtLasVLR &v)
CREATE_STATIC_PLUGIN (1, 0, OGRWriter, Writer, s_info)
pdal::georeference::RotationMatrix createOptechRotationMatrix (double roll, double pitch, double heading)
CREATE_STATIC_PLUGIN (1, 0, OptechReader, Reader, s_info)
CREATE_STATIC_PLUGIN (1, 0, PlyReader, Reader, s_info)
std::istream & operator>> (std::istream &in, PlyWriter::Format &f)
std::ostream & operator<< (std::ostream &out, const PlyWriter::Format &f)
Dimension::IdList fileDimensions ()
StringList readSTDIN ()
const size_t CHUNKSIZE (1000000)
std::string transformWkt (std::string wkt, const SpatialReference &from, const SpatialReference &to)
std::ostream & operator<< (std::ostream &ostr, const Geometry &p)
std::istream & operator>> (std::istream &istr, Geometry &p)
std::ostream & operator<< (std::ostream &ostr, const Kernel &kernel)
bool operator== (const MetadataNode &m1, const MetadataNode &m2)
bool operator!= (const MetadataNode &m1, const MetadataNode &m2)
PDAL_DLL std::ostream & operator<< (std::ostream &ostr, const Options &)
bool IsLibGeoTIFFEnabled ()
Check if GeoTIFF support has been built in to PDAL.
bool IsLasZipEnabled ()
Check if LasZip compression support has been built in to PDAL.
int GetVersionMajor ()
int GetVersionMinor ()
int GetVersionPatch ()
std::string GetVersionString ()
int GetVersionInteger ()
std::string GetSHA1 ()
std::string GetFullVersionString ()
Tell the user a bit about PDAL's compilation.
std::string getPDALDebugInformation ()
PDAL_DLL bool IsLibLASEnabled ()
PDAL_DLL bool IsGDALEnabled ()
std::istream & operator>> (std::istream &in, XForm::XFormComponent &xfc)
std::ostream & operator<< (std::ostream &out, const XForm::XFormComponent &xfc)
std::istream & operator>> (std::istream &in, LogLevel &level)
std::ostream & operator<< (std::ostream &out, const LogLevel &level)
std::ostream & operator<< (std::ostream &ostr, const PointView &buf)
void swap (PointIdxRef &&p1, PointIdxRef &&p2)
std::ostream & operator<< (std::ostream &ostr, const SpatialReference &srs)
std::istream & operator>> (std::istream &istr, SpatialReference &srs)
std::istream & operator>> (std::istream &istr, BOX2D &bounds)
std::istream & operator>> (std::istream &istr, BOX3D &bounds)
std::istream & operator>> (std::istream &in, Bounds &bounds)
std::ostream & operator<< (std::ostream &out, const Bounds &bounds)
std::ostream & operator<< (std::ostream &ostr, const BOX2D &bounds)
std::ostream & operator<< (std::ostream &ostr, const BOX3D &bounds)
static bool is_base64 (unsigned char c)
bool operator< (const uuid &u1, const uuid &u2)
bool operator== (const Uuid &u1, const Uuid &u2)
bool operator< (const Uuid &u1, const Uuid &u2)
std::ostream & operator<< (std::ostream &out, const Uuid &u)
std::istream & operator>> (std::istream &in, Uuid &u)
void OCISchemaStructuredErrorHandler (void *, xmlErrorPtr error)
void OCISchemaParserStructuredErrorHandler (void *, xmlErrorPtr error)
void OCISchemaValidationStructuredErrorHandler (void *, xmlErrorPtr error)
void OCISchemaValidityError (void *, const char *message,...)
void OCISchemaValidityDebug (void *, const char *message,...)
void OCISchemaGenericErrorHandler (void *, const char *message,...)
bool operator< (const XMLDim &d1, const XMLDim &d2)
CREATE_SHARED_PLUGIN (1, 0, CpdFilter, Filter, s_info)
TEST (CpdFilterTest, DefaultMethod)
TEST (CpdFilterTest, DefaultIdentity)
TEST (CpdFilterTest, RecoverTranslation)
TEST (CpdFilterTest, TooFewInputs)
TEST (CpdFilterTest, TooManyInputs)
TEST (CpdFilterTest, RigidNoThrow)
TEST (CpdFilterTest, AffineNoThrow)
TEST (CpdFilterTest, NonrigidNoThrow)
TEST_F (MatlabWriterTest, constructor)
TEST_F (MatlabWriterTest, findStage)
TEST_F (MatlabWriterTest, write)
TEST_F (MatlabWriterTest, outputDims)
std::istream & operator>> (std::istream &in, MbFormat &f)
std::ostream & operator<< (std::ostream &out, const MbFormat &f)
pdal::Dimension::Type getPDALType (LizardTech::DataType t)
template<typename T >
T getData (LizardTech::PointData &points, const char *channelId, point_count_t pointIndex)
NITF_TRE_STATIC_HANDLER_REF (ACCHZB)
NITF_TRE_STATIC_HANDLER_REF (ACCPOB)
NITF_TRE_STATIC_HANDLER_REF (ACCVTB)
NITF_TRE_STATIC_HANDLER_REF (ACFTA)
NITF_TRE_STATIC_HANDLER_REF (ACFTB)
NITF_TRE_STATIC_HANDLER_REF (AIMIDA)
NITF_TRE_STATIC_HANDLER_REF (AIMIDB)
NITF_TRE_STATIC_HANDLER_REF (AIPBCA)
NITF_TRE_STATIC_HANDLER_REF (ASTORA)
NITF_TRE_STATIC_HANDLER_REF (BANDSA)
NITF_TRE_STATIC_HANDLER_REF (BANDSB)
NITF_TRE_STATIC_HANDLER_REF (BCKGDA)
NITF_TRE_STATIC_HANDLER_REF (BLOCKA)
NITF_TRE_STATIC_HANDLER_REF (BNDPLB)
NITF_TRE_STATIC_HANDLER_REF (CLCTNA)
NITF_TRE_STATIC_HANDLER_REF (CLCTNB)
NITF_TRE_STATIC_HANDLER_REF (CMETAA)
NITF_TRE_STATIC_HANDLER_REF (CSCCGA)
NITF_TRE_STATIC_HANDLER_REF (CSCRNA)
NITF_TRE_STATIC_HANDLER_REF (CSDIDA)
NITF_TRE_STATIC_HANDLER_REF (CSEPHA)
NITF_TRE_STATIC_HANDLER_REF (CSEXRA)
NITF_TRE_STATIC_HANDLER_REF (CSPROA)
NITF_TRE_STATIC_HANDLER_REF (CSSFAA)
NITF_TRE_STATIC_HANDLER_REF (CSSHPA)
NITF_TRE_STATIC_HANDLER_REF (ENGRDA)
NITF_TRE_STATIC_HANDLER_REF (EXOPTA)
NITF_TRE_STATIC_HANDLER_REF (EXPLTA)
NITF_TRE_STATIC_HANDLER_REF (EXPLTB)
NITF_TRE_STATIC_HANDLER_REF (GEOLOB)
NITF_TRE_STATIC_HANDLER_REF (GEOPSB)
NITF_TRE_STATIC_HANDLER_REF (GRDPSB)
NITF_TRE_STATIC_HANDLER_REF (HISTOA)
NITF_TRE_STATIC_HANDLER_REF (ICHIPB)
NITF_TRE_STATIC_HANDLER_REF (IMGDTA)
NITF_TRE_STATIC_HANDLER_REF (IOMAPA)
NITF_TRE_STATIC_HANDLER_REF (J2KLRA)
NITF_TRE_STATIC_HANDLER_REF (JITCID)
NITF_TRE_STATIC_HANDLER_REF (MAPLOB)
NITF_TRE_STATIC_HANDLER_REF (MENSRA)
NITF_TRE_STATIC_HANDLER_REF (MENSRB)
NITF_TRE_STATIC_HANDLER_REF (MPDSRA)
NITF_TRE_STATIC_HANDLER_REF (MSTGTA)
NITF_TRE_STATIC_HANDLER_REF (MTIRPA)
NITF_TRE_STATIC_HANDLER_REF (MTIRPB)
NITF_TRE_STATIC_HANDLER_REF (NBLOCA)
NITF_TRE_STATIC_HANDLER_REF (OBJCTA)
NITF_TRE_STATIC_HANDLER_REF (OFFSET)
NITF_TRE_STATIC_HANDLER_REF (PATCHA)
NITF_TRE_STATIC_HANDLER_REF (PATCHB)
NITF_TRE_STATIC_HANDLER_REF (PIAEQA)
NITF_TRE_STATIC_HANDLER_REF (PIAEVA)
NITF_TRE_STATIC_HANDLER_REF (PIAIMB)
NITF_TRE_STATIC_HANDLER_REF (PIAIMC)
NITF_TRE_STATIC_HANDLER_REF (PIAPEA)
NITF_TRE_STATIC_HANDLER_REF (PIAPEB)
NITF_TRE_STATIC_HANDLER_REF (PIAPRC)
NITF_TRE_STATIC_HANDLER_REF (PIAPRD)
NITF_TRE_STATIC_HANDLER_REF (PIATGA)
NITF_TRE_STATIC_HANDLER_REF (PIATGB)
NITF_TRE_STATIC_HANDLER_REF (PIXQLA)
NITF_TRE_STATIC_HANDLER_REF (PLTFMA)
NITF_TRE_STATIC_HANDLER_REF (PRJPSB)
NITF_TRE_STATIC_HANDLER_REF (REGPTB)
NITF_TRE_STATIC_HANDLER_REF (RPC00B)
NITF_TRE_STATIC_HANDLER_REF (RPFDES)
NITF_TRE_STATIC_HANDLER_REF (RPFHDR)
NITF_TRE_STATIC_HANDLER_REF (RPFIMG)
NITF_TRE_STATIC_HANDLER_REF (RSMAPA)
NITF_TRE_STATIC_HANDLER_REF (RSMDCA)
NITF_TRE_STATIC_HANDLER_REF (RSMECA)
NITF_TRE_STATIC_HANDLER_REF (RSMGGA)
NITF_TRE_STATIC_HANDLER_REF (RSMGIA)
NITF_TRE_STATIC_HANDLER_REF (RSMIDA)
NITF_TRE_STATIC_HANDLER_REF (RSMPCA)
NITF_TRE_STATIC_HANDLER_REF (RSMPIA)
NITF_TRE_STATIC_HANDLER_REF (SECTGA)
NITF_TRE_STATIC_HANDLER_REF (SENSRA)
NITF_TRE_STATIC_HANDLER_REF (SENSRB)
NITF_TRE_STATIC_HANDLER_REF (SNSPSB)
NITF_TRE_STATIC_HANDLER_REF (SNSRA)
NITF_TRE_STATIC_HANDLER_REF (SOURCB)
NITF_TRE_STATIC_HANDLER_REF (STDIDC)
NITF_TRE_STATIC_HANDLER_REF (STEROB)
NITF_TRE_STATIC_HANDLER_REF (STREOB)
NITF_TRE_STATIC_HANDLER_REF (TRGTA)
NITF_TRE_STATIC_HANDLER_REF (USE00A)
void register_tre_handler (NITF_PLUGIN_INIT_FUNCTION init, NITF_PLUGIN_TRE_HANDLER_FUNCTION handler)
void register_tre_plugins ()
Connection connect (std::string connSpec)
XMLSchema fetchSchema (Statement stmt, BlockPtr block)
sb4 callback (void *ctxp, void *bufp, oraub8 *lenp, ub1 *piece, void **changed_bufpp, oraub8 *changed_lenp)
bool OWIsNumeric (const char *pszText)
const char * OWReplaceString (const char *pszBaseString, const char *pszToken, const char *pszStopToken, const char *pszOWReplaceToken)
const char * OWParseValue (const char *pszText, const char *pszSeparators, const char *pszHint, int nOffset)
const char * OWParseSDO_GEOR_INIT (const char *pszInsert, int nField)
int OWParseServerVersion (const char *pszText)
int OWParseEPSG (const char *pszText)
GDALDataType OWGetDataType (const char *pszCellDepth)
const char * OWSetDataType (const GDALDataType eType)
bool CheckError (sword nStatus, OCIError *hError)
CREATE_SHARED_PLUGIN (1, 0, IcpFilter, Filter, s_info)
TEST (IcpFilterTest, DefaultIdentity)
TEST (IcpFilterTest, RecoverTranslation)
TEST (IcpFilterTest, TooFewInputs)
TEST (IcpFilterTest, ThreeInputs)
pdal::CompressionType getCompressionType (std::string compression_type)
PGconn * pg_connect (std::string const &connection)
void pg_execute (PGconn *session, std::string const &sql)
void pg_begin (PGconn *session)
void pg_commit (PGconn *session)
std::string pg_query_once (PGconn *session, std::string const &sql)
PGresult * pg_query_result (PGconn *session, std::string const &sql)
std::string pg_quote_identifier (std::string const &name)
std::string pg_quote_literal (std::string const &lit)
Dimension::Id getTimeDimensionId (bool syncToPps)
Dimension::IdList getRxpDimensions (bool syncToPps, bool minimal, bool reflectanceAsIntensity)
std::string extractRivlibURI (const Options &options)
Dimension::IdList getRxpDimensions (bool syncToPps, bool minimal)
TEST (PdalApp, log)
TEST (PdalApp, option_file)
TEST (pipelineBaseTest, no_input)
TEST (pipelineBaseTest, common_opts)
TEST (pipelineBaseTest, progress)
TEST_P (json, pipeline)
TEST (json, pipeline_stdin)
INSTANTIATE_TEST_CASE_P (base, json, testing::Values("pipeline/assign.json","pipeline/bpf2las.json","pipeline/chipper.json","pipeline/colorize-multi.json","pipeline/colorize.json","pipeline/crop-hole.json","pipeline/crop_wkt.json","pipeline/crop_wkt_2d.json","pipeline/decimate.json","pipeline/ferry-reproject.json","pipeline/las2csv.json","pipeline/las2geojson.json","pipeline/las2space-delimited.json","pipeline/merge.json","pipeline/metadata_reader.json","pipeline/metadata_writer.json","pipeline/mississippi.json","pipeline/mississippi_reverse.json","pipeline/overlay.json","pipeline/range_z.json","pipeline/range_z_classification.json","pipeline/range_classification.json","pipeline/sbet2txt.json","pipeline/sort.json","pipeline/splitter.json","pipeline/stats.json","pipeline/transformation.json"))
TEST_P (jsonWithNITF, pipeline)
INSTANTIATE_TEST_CASE_P (plugins, jsonWithNITF, testing::Values("pipeline/bpf2nitf.json","pipeline/las2nitf.json","pipeline/las2nitf-crop-with-options.json","pipeline/nitf2las.json"))
TEST_P (jsonWithP2G, pipeline)
INSTANTIATE_TEST_CASE_P (plugins, jsonWithP2G, testing::Values("pipeline/p2g-writer.json"))
TEST_P (jsonWithHexer, pipeline)
INSTANTIATE_TEST_CASE_P (plugins, jsonWithHexer, testing::Values("pipeline/hexbin-info.json","pipeline/hexbin.json"))
TEST_P (jsonWithLAZ, pipeline)
INSTANTIATE_TEST_CASE_P (plugins, jsonWithLAZ, testing::Values("pipeline/crop.json","pipeline/crop-stats.json"))
TEST (json, tags)
TEST (json, issue1417)
TEST (json, stagetags)
TEST (TransformationMatrix, create)
TEST (TransformationMatrix, FromString)
TEST (TransformationMatrix, TooShort)
TEST (TransformationMatrix, TooLong)
TEST_F (TransformationFilterTest, NoChange)
TEST_F (TransformationFilterTest, Translation)
TEST_F (TransformationFilterTest, Rotation)
TEST (OptechReader, Constructor)
TEST_F (OptechReaderTest, Header)
TEST_F (OptechReaderTest, ReadingPoints)
TEST_F (OptechReaderTest, Spatialreference)
void checkPoint (const PointViewPtr &view, point_count_t idx, double x, double y, double z)
TEST (PlyReader, Constructor)
TEST (PlyReader, ReadText)
TEST (PlyReader, ReadTextExtraDims)
TEST (PlyReader, ReadBinary)
TEST (PlyReader, ReadBinaryStream)
TEST (PlyReader, NoVertex)
TEST (PlyWriter, Constructor)
TEST (PlyWriter, Write)
TEST (PlyWriter, mesh)
TEST (PtsReader, Constructor)
TEST (PtsReader, ReadPtsExtraDims)
TEST (TerrasolidReader, Constructor)
TEST_F (TerrasolidReaderTest, Header)
TEST_F (TerrasolidReaderTest, ReadingPoints)
TEST (KernelTest, parseOption)
TEST (Log, t1)
TEST (Log, t2)
TEST (OptionsTest, test_option_writing)
TEST (OptionsTest, json)
TEST (OptionsTest, conditional)
TEST (OptionsTest, valid)
TEST (OptionsTest, programargs)
TEST (OptionsTest, nan)
TEST (PluginManagerTest, NoPluginsNoNames)
TEST (PluginManagerTest, InitPlugin)
TEST (PluginManagerTest, MissingPlugin)
TEST (PluginManagerTest, CreateObject)
TEST (PluginManagerTest, SearchPaths)
TEST (PointTable, resolveType)
TEST (PointTable, userView)
TEST (PointTable, srs)
std::string getWKT ()
std::string getJSON ()
TEST (PolygonTest, test_wkt_in)
TEST (PolygonTest, test_json_in)
TEST (PolygonTest, test_wkt_out)
TEST (PolygonTest, test_json_out)
TEST (PolygonTest, smooth)
TEST (PolygonTest, covers)
TEST (PolygonTest, valid)
TEST (PolygonTest, bounds)
TEST (PolygonTest, bounds2d)
TEST (PolygonTest, bounds3d)
TEST (PolygonTest, streams)
TEST (StageFactoryTest, Load)
TEST (StageFactoryTest, Load2)
TEST (StageFactoryTest, Load3)
TEST (StageFactoryTest, Load4)
TEST (StageFactoryTest, extensionTest)
TEST (NitfWrap, las)
TEST (NitfWrap, altPath)
TEST (NitfWrap, bpf)
Variables
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
class PDAL_DLL ChipperFilter
static PluginInfo const s_info
static std::vector< std::string > ramps
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static const int WKT_RECORD_ID = 2112
static const uint16_t GEOTIFF_DIRECTORY_RECORD_ID = 34735
static const uint16_t GEOTIFF_DOUBLES_RECORD_ID = 34736
static const uint16_t GEOTIFF_ASCII_RECORD_ID = 34737
static const uint16_t LASZIP_RECORD_ID = 22204
static const uint16_t EXTRA_BYTES_RECORD_ID = 4
static const uint16_t PDAL_METADATA_RECORD_ID = 12
static const uint16_t PDAL_PIPELINE_RECORD_ID = 13
static const char TRANSFORM_USER_ID [] = "LASF_Projection"
static const char SPEC_USER_ID [] = "LASF_Spec"
static const char LIBLAS_USER_ID [] = "liblas"
static const char LASZIP_USER_ID [] = "laszip encoded"
static const char PDAL_USER_ID [] = "PDAL"
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
class PDAL_DLL BOX3D
class PDAL_DLL MetadataNode
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static const OW_CellDepth ahOW_CellDepth []
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
static PluginInfo const s_info
const bool DEFAULT_SYNC_TO_PPS = true
const bool DEFAULT_IS_RDTP = false
const bool DEFAULT_MINIMAL = false
const bool DEFAULT_REFLECTANCE_AS_INTENSITY = true
const float DEFAULT_MIN_REFLECTANCE = -25.0
const float DEFAULT_MAX_REFLECTANCE = 5.0
static PluginInfo const s_info
static PluginInfo const s_info
string __version__ = '1.6.0'
Detailed Description
The objective is to split the region into non-overlapping blocks, each containing approximately the same number of points, as specified by the user. We'd also like the blocks closer to square than not.
First, the points are read into arrays - one for the x direction, and one for the y direction. The arrays are sorted and are initialized with indices into the other array of the location of the other coordinate of the same point.
Partitions are created that place the maximum number of points in a block, subject to the user-defined threshold, using a cumulate and round procedure.
The distance of the point-space is checked in each direction and the wider dimension is chosen for splitting at an appropriate partition point. The points in the narrower direction are copied to locations in the spare array at one side or the other of the chosen partition, and that portion of the spare array then becomes the active array for the narrow direction. This avoids resorting of the arrays, which are already sorted.
This procedure is then recursively applied to the created blocks until they contains only one or two partitions. In the case of one or two partitions we are done, and we simply store away the contents of the blocks.
Class Documentation
struct pdal::cbctx
Definition at line 1844 of file OciWrapper.cpp.
Class Members
ub1 * buffer
ub4 buffer_len
oraub8 length
oraub8 position
struct pdal::CsdHeader
Definition at line 42 of file OptechCommon.hpp.
Class Members
float formatVersion
char freeSpace[830]
uint16_t gpsWeek
uint16_t headerSize
double imuOffsets[3]
double maxTime
double minTime
double misalignmentAngles[3]
uint32_t numRecords
uint16_t numStrips
double pressure
char signature[4]
char softwareVersion[32]
uint32_t stripPointers[256]
double temperature
char vendorId[64]
struct pdal::CsdPulse
Definition at line 63 of file OptechCommon.hpp.
Class Members
float elevation
double gpsTime
float heading
uint16_t intensity[4]
double latitude
double longitude
float pitch
float range[4]
uint8_t returnCount
float roll
float scanAngle
struct pdal::DimSpec
Definition at line 52 of file DimBuilder.hpp.
Class Members
vector< string > m_altNames
string m_description
string m_name
Type m_type
union pdal::Everything
Definition at line 55 of file pdal_types.hpp.
Class Members
double d
float f
int16_t s16
int32_t s32
int64_t s64
int8_t s8
uint16_t u16
uint32_t u32
uint64_t u64
uint8_t u8
struct pdal::ExtraBytesSpec
Definition at line 107 of file LasUtils.hpp.
Class Members
uint8_t m_dataType
char m_description[32]
double m_max[3]
double m_min[3]
char m_name[32]
uint64_t m_noData[3]
double m_offset[3]
uint8_t m_options
char m_reserved[2]
char m_reserved2[4]
double m_scale[3]
struct pdal::Indices
Definition at line 52 of file OutlierFilter.hpp.
Class Members
vector< PointId > inliers
vector< PointId > outliers
struct pdal::OW_CellDepth
Definition at line 52 of file OciWrapper.h.
Class Members
GDALDataType eDataType
const char * pszValue
struct pdal::sdo_geometry
Definition at line 140 of file OciWrapper.h.
Class Members
OCIArray * sdo_elem_info
OCINumber sdo_gtype
OCIArray * sdo_ordinates
sdo_point_type sdo_point
OCINumber sdo_srid
struct pdal::sdo_geometry_ind
Definition at line 151 of file OciWrapper.h.
Class Members
OCIInd _atomic
OCIInd sdo_elem_info
OCIInd sdo_gtype
OCIInd sdo_ordinates
struct sdo_point_type_ind sdo_point
OCIInd sdo_srid
struct pdal::sdo_georaster
Definition at line 167 of file OciWrapper.h.
Class Members
void * metadata
OCIString * rasterdatatable
OCINumber rasterid
OCINumber rastertype
SDO_GEOMETRY_TYPE spatialextent
struct pdal::sdo_georaster_ind
Definition at line 178 of file OciWrapper.h.
Class Members
OCIInd _atomic
OCIInd metadata
OCIInd rasterdatatable
OCIInd rasterid
OCIInd rastertype
sdo_geometry_ind spatialextent
struct pdal::sdo_mbr
Definition at line 194 of file OciWrapper.h.
Class Members
OCIArray * lower_left
OCIArray * upper_right
struct pdal::sdo_mbr_ind
Definition at line 201 of file OciWrapper.h.
Class Members
OCIInd _atomic
OCIInd lower_left
OCIInd upper_right
struct pdal::sdo_orgscl_type
Definition at line 209 of file OciWrapper.h.
Class Members
SDO_MBR_TYPE extent
OCIArray * ord_cmp_type
OCIArray * scale
struct pdal::sdo_orgscl_type_ind
Definition at line 217 of file OciWrapper.h.
Class Members
OCIInd _atomic
SDO_MBR_ind extent
OCIInd ord_cmp_type
OCIInd scale
struct pdal::sdo_pc
Definition at line 226 of file OciWrapper.h.
Class Members
OCIString * base_column
OCIString * base_table
OCIString * blk_table
SDO_ORGSCL_TYPE pc_domain
SDO_GEOMETRY_TYPE pc_geometry
OCINumber pc_id
void * pc_other_attrs
OCINumber pc_tol
OCINumber pc_tot_dimensions
OCIString * pc_val_attr_tables
OCIString * ptn_params
struct pdal::sdo_pc_blk
Definition at line 259 of file OciWrapper.h.
Class Members
OCINumber blkno
SDO_GEOMETRY_TYPE ind_dimqry
SDO_PC_TYPE inp
SDO_MBR_TYPE other_dimqry
OCINumber qry_max_res
OCINumber qry_min_res
struct pdal::sdo_pc_blk_type_ind
Definition at line 271 of file OciWrapper.h.
Class Members
OCIInd _atomic
sdo_orgscl_type_ind blk_domain
sdo_geometry_ind blk_extent
OCIInd blk_id
OCIInd num_points
OCIInd num_unsorted_points
OCIInd obj_id
OCIInd pcblk_max_res
OCIInd pcblk_min_res
OCIInd pt_sort_dim
struct pdal::sdo_pc_ind
Definition at line 242 of file OciWrapper.h.
Class Members
OCIInd _atomic
OCIInd base_column
OCIInd base_table
OCIInd blk_table
OCIInd pc_domain
sdo_geometry_ind pc_geometry
OCIInd pc_id
OCIInd pc_other_attrs
OCIInd pc_tol
OCIInd pc_tot_dimensions
OCIInd pc_val_attr_tables
OCIInd ptn_params
struct pdal::sdo_point_type
Definition at line 117 of file OciWrapper.h.
Class Members
OCINumber x
OCINumber y
OCINumber z
struct pdal::sdo_point_type_ind
Definition at line 126 of file OciWrapper.h.
Class Members
OCIInd _atomic
OCIInd x
OCIInd y
OCIInd z
struct pdal::StageCreationOptions
Definition at line 48 of file PipelineManager.hpp.
Class Members
string m_driver
string m_filename
Options m_options
Stage * m_parent
string m_tag
struct pdal::uuid
Definition at line 76 of file Uuid.hpp.
Class Members
uint16_t clock_seq
uint8_t node[6]
uint16_t time_hi_and_version
uint32_t time_low
uint16_t time_mid
struct pdal::VlrOptionInfo
Definition at line 66 of file LasWriter.hpp.
Class Members
string m_description
string m_name
uint16_t m_recordId
string m_userId
string m_value
Typedef Documentation
using pdal::BlockCb = typedef std::function<void(char *buf, size_t bufsize)>
Definition at line 50 of file Compression.hpp.
typedef std::shared_ptr<Block> pdal::BlockPtr
Definition at line 101 of file OciCommon.hpp.
typedef std::vector<BpfDimension> pdal::BpfDimensionList
Definition at line 138 of file BpfHeader.hpp.
typedef struct pdal::cbctx pdal::cbctx
typedef std::shared_ptr<OWConnection> pdal::Connection
Definition at line 49 of file OciCommon.hpp.
typedef BasePointTable const& pdal::ConstPointTableRef
Definition at line 111 of file PointTable.hpp.
typedef std::pair<double, double> pdal::Coord
Definition at line 57 of file MortonOrderFilter.cpp.
typedef std::map<std::string, Dimension::Id> pdal::DimensionMap
Definition at line 54 of file GDALReader.hpp.
typedef std::map<std::string, DimIndex> pdal::DimIndexMap
Definition at line 67 of file DeltaKernel.hpp.
typedef std::vector<DimType> pdal::DimTypeList
Definition at line 59 of file DimType.hpp.
typedef std::shared_ptr< std::ostream > pdal::FileStreamPtr
Definition at line 11 of file MyWriter.hpp.
typedef std::unique_ptr<GDALGrid> pdal::GDALGridPtr
Definition at line 165 of file GDALGrid.hpp.
typedef std::unique_ptr<GEOSGeometry, geos::GeometryDeleter> pdal::GEOSGeomPtr
Definition at line 83 of file Geometry.hpp.
typedef char pdal::LazPerfVlrCompressor
Definition at line 419 of file LazPerfCompression.hpp.
typedef char pdal::LazPerfVlrDecompressor
Definition at line 420 of file LazPerfCompression.hpp.
typedef std::shared_ptr<Log> pdal::LogPtr
Definition at line 148 of file Log.hpp.
typedef std::vector<MetadataNodeImplPtr> pdal::MetadataImplList
Definition at line 63 of file Metadata.hpp.
typedef std::shared_ptr<MetadataNodeImpl> pdal::MetadataNodeImplPtr
Definition at line 61 of file Metadata.hpp.
typedef std::vector<MetadataNode> pdal::MetadataNodeList
Definition at line 65 of file Metadata.hpp.
typedef std::shared_ptr<Metadata> pdal::MetadataPtr
Definition at line 687 of file Metadata.hpp.
typedef std::map<std::string, MetadataImplList> pdal::MetadataSubnodes
Definition at line 64 of file Metadata.hpp.
typedef std::shared_ptr<void> pdal::OGRDSPtr
Definition at line 60 of file OverlayFilter.hpp.
typedef std::shared_ptr<void> pdal::OGRFeaturePtr
Definition at line 61 of file OverlayFilter.hpp.
typedef std::shared_ptr<void> pdal::OGRGeometryPtr
Definition at line 62 of file OverlayFilter.hpp.
typedef std::map<std::string, Options> pdal::OptionsMap
Definition at line 238 of file Options.hpp.
typedef std::shared_ptr<Patch> pdal::PatchPtr
Definition at line 120 of file SQLiteCommon.hpp.
typedef std::unique_ptr<PipelineManager> pdal::PipelineManagerPtr
Definition at line 157 of file PipelineManager.hpp.
typedef uint64_t pdal::point_count_t
Definition at line 52 of file pdal_types.hpp.
typedef uint8_t pdal::PointFormat
Definition at line 53 of file LasHeader.hpp.
typedef uint64_t pdal::PointId
Definition at line 51 of file pdal_types.hpp.
typedef std::unordered_map<int, std::vector<PointId> > pdal::PointIdHash
Definition at line 52 of file MongusFilter.hpp.
typedef PointLayout* pdal::PointLayoutPtr
Definition at line 247 of file PointLayout.hpp.
typedef BasePointTable& pdal::PointTableRef
Definition at line 110 of file PointTable.hpp.
typedef std::shared_ptr< PointView > pdal::PointViewPtr
Definition at line 49 of file EigenUtils.hpp.
typedef std::set<PointViewPtr, PointViewLess> pdal::PointViewSet
Definition at line 70 of file PointView.hpp.
typedef std::vector<row> pdal::records
Definition at line 83 of file SQLiteCommon.hpp.
typedef std::vector<column> pdal::row
Definition at line 82 of file SQLiteCommon.hpp.
typedef OCIArray pdal::sdo_elem_info_array
Definition at line 109 of file OciWrapper.h.
typedef struct SDO_GEOMETRY_ind pdal::SDO_GEOMETRY_ind
Definition at line 161 of file OciWrapper.h.
typedef OCIRef pdal::SDO_GEOMETRY_ref
Definition at line 106 of file OciWrapper.h.
typedef struct sdo_geometry pdal::SDO_GEOMETRY_TYPE
Definition at line 149 of file OciWrapper.h.
typedef struct sdo_georaster_ind pdal::SDO_GEORASTER_ind
Definition at line 188 of file OciWrapper.h.
typedef OCIRef pdal::SDO_GEORASTER_ref
Definition at line 105 of file OciWrapper.h.
typedef struct sdo_georaster pdal::SDO_GEORASTER_TYPE
Definition at line 176 of file OciWrapper.h.
typedef struct sdo_mbr_ind pdal::SDO_MBR_ind
Definition at line 207 of file OciWrapper.h.
typedef struct sdo_mbr pdal::SDO_MBR_TYPE
Definition at line 199 of file OciWrapper.h.
typedef OCIArray pdal::SDO_NUMBER_ARRAY_TYPE
Definition at line 111 of file OciWrapper.h.
typedef OCIArray pdal::sdo_ordinate_array
Definition at line 110 of file OciWrapper.h.
typedef struct sdo_orgscl_type pdal::SDO_ORGSCL_TYPE
Definition at line 215 of file OciWrapper.h.
typedef struct sdo_orgscl_type_ind pdal::SDO_ORGSCL_TYPE_ind
Definition at line 224 of file OciWrapper.h.
typedef struct sdo_pc_blk pdal::SDO_PC_BLK_TYPE
Definition at line 269 of file OciWrapper.h.
typedef struct sdo_pc_blk_type_ind pdal::SDO_PC_BLK_TYPE_ind
Definition at line 284 of file OciWrapper.h.
typedef struct sdo_pc_ind pdal::SDO_PC_ind
Definition at line 257 of file OciWrapper.h.
typedef struct sdo_pc pdal::SDO_PC_TYPE
Definition at line 240 of file OciWrapper.h.
typedef struct sdo_point_type pdal::sdo_point_type
Definition at line 124 of file OciWrapper.h.
typedef struct sdo_point_type_ind pdal::sdo_point_type_ind
Definition at line 134 of file OciWrapper.h.
typedef OCIRef pdal::SDO_POINT_TYPE_ref
Definition at line 107 of file OciWrapper.h.
typedef std::shared_ptr<StageRunner> pdal::StageRunnerPtr
Definition at line 63 of file StageRunner.hpp.
typedef std::shared_ptr<OWStatement> pdal::Statement
Definition at line 50 of file OciCommon.hpp.
typedef std::vector<std::string> pdal::StringList
Definition at line 53 of file pdal_types.hpp.
typedef std::unique_ptr<TerraSolidHeader> pdal::TerraSolidHeaderPtr
Definition at line 86 of file TerrasolidReader.hpp.
typedef std::array<double, 16> pdal::TransformationMatrix
Definition at line 52 of file TransformationFilter.hpp.
typedef std::vector<LasVLR> pdal::VlrList
Definition at line 63 of file LasVLR.hpp.
typedef std::vector<XMLDim> pdal::XMLDimList
Definition at line 89 of file XMLSchema.hpp.
Enumeration Type Documentation
enum pdal::BpfCompression strong
Enumerator
None
QuickLZ
FastLZ
Zlib
Definition at line 112 of file BpfHeader.hpp.
enum pdal::BpfCoordType strong
Enumerator
Cartesian
UTM
TCR
ENU
Definition at line 104 of file BpfHeader.hpp.
enum pdal::BpfFormat strong
Enumerator
DimMajor
PointMajor
ByteMajor
Definition at line 94 of file BpfHeader.hpp.
enum pdal::CompressionType strong
Enumerator
None
Ght
Dimensional
Lazperf
Unknown
Definition at line 41 of file Compression.hpp.
enum pdal::LasCompression strong
Enumerator
LasZip
LazPerf
None
Definition at line 44 of file LasUtils.hpp.
enum pdal::LogLevel strong
Enumerator
Error
Warning
Info
Debug
Debug1
Debug2
Debug3
Debug4
Debug5
None
Definition at line 153 of file pdal_types.hpp.
enum pdal::MetadataType strong
Enumerator
Instance
Array
Definition at line 53 of file Metadata.hpp.
enum pdal::Mode strong
Enumerator
Constant
Random
Ramp
Uniform
Normal
Grid
Definition at line 46 of file FauxReader.hpp.
enum pdal::Orientation strong
Enumerator
PointMajor
DimensionMajor
Definition at line 214 of file pdal_types.hpp.
enum pdal::QFIT_Format_Type
Enumerator
QFIT_Format_10
QFIT_Format_12
QFIT_Format_14
QFIT_Format_Unknown
Definition at line 52 of file QfitReader.hpp.
enum pdal::SortOrder strong
Enumerator
ASC
DESC
Definition at line 48 of file SortFilter.hpp.
enum pdal::TERRASOLID_Format_Type
Enumerator
TERRASOLID_Format_1
TERRASOLID_Format_2
TERRASOLID_Format_Unknown
Definition at line 51 of file TerrasolidReader.hpp.
Function Documentation
template<typename T > void pdal::addForwardMetadata (MetadataNode & forward, MetadataNode & m, const std::string & name, T val, const std::string description = "")
Definition at line 266 of file LasReader.cpp.
References pdal::MetadataNode::add(), pdal::MetadataNode::addOrUpdate(), pdal::Dimension::description(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::MetadataNode::findChild(), pdal::MetadataNode::valid(), and pdal::MetadataNode::value().
Referenced by pdal::LasReader::extractHeaderMetadata().
sb4 pdal::callback (void * ctxp, void * bufp, oraub8 * lenp, ub1 * piece, void ** changed_bufpp, oraub8 * changed_lenp)
Definition at line 1852 of file OciWrapper.cpp.
References pdal::cbctx::buffer, pdal::cbctx::buffer_len, pdal::cbctx::length, and pdal::cbctx::position.
Referenced by pdal::OWStatement::WriteBlob().
bool pdal::CheckError (sword nStatus, OCIError * hError)
Definition at line 2429 of file OciWrapper.cpp.
References OWTEXT, and pdal::MbError::text().
Referenced by pdal::OWStatement::AddElement(), pdal::OWStatement::AllocBlob(), pdal::OWStatement::Bind(), pdal::OWStatement::BindArray(), pdal::OWStatement::BindBlob(), pdal::OWStatement::BindClob(), pdal::OWStatement::BindName(), pdal::OWStatement::CloseBlob(), pdal::OWConnection::Commit(), pdal::OWConnection::CreateType(), pdal::OWStatement::Define(), pdal::OWStatement::DefineClob(), pdal::OWConnection::DescribeType(), pdal::OWConnection::DestroyType(), pdal::OWStatement::DisableBuffering(), pdal::OWStatement::EnableBuffering(), pdal::OWStatement::Execute(), pdal::OWStatement::Fetch(), pdal::OWStatement::GetArrayLength(), pdal::OWStatement::GetBlobLength(), pdal::OWConnection::GetDescription(), pdal::OWStatement::GetDouble(), pdal::OWStatement::GetElement(), pdal::OWStatement::GetInteger(), pdal::OWConnection::GetNextField(), pdal::OWStatement::GetNextField(), pdal::OWStatement::OpenBlob(), pdal::OWConnection::OWConnection(), pdal::OWStatement::OWStatement(), pdal::OWStatement::ReadBlob(), pdal::OWStatement::ReadCLob(), pdal::OWConnection::StartTransaction(), pdal::OWStatement::WriteBlob(), and pdal::OWStatement::WriteCLob().
void pdal::checkPoint (const PointViewPtr & view, point_count_t idx, double x, double y, double z)
Definition at line 45 of file PlyReaderTest.cpp.
References pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by TEST(), and TEST().
const size_t pdal::CHUNKSIZE (1000000)
PDAL_DLL Connection pdal::connect (std::string connSpec)
Definition at line 45 of file OciCommon.cpp.
References pdal::Utils::closeFile(), pdal::Utils::fileExists(), pdal::Utils::openFile(), and pdal::Dimension::size().
Referenced by OCITest::connect(), pdal::OciWriter::initialize(), pdal::OciReader::initialize(), and OCITest::SetUp().
template<typename T > T pdal::convert (const StringList & s, const std::string & name, size_t fieldno)
Definition at line 38 of file MyReader.cpp.
References pdal::Utils::fromString().
Referenced by pdal::Ilvis2Reader::initialize(), and pdal::mlang::Script::setMatlabStruct().
pdal::CREATE_SHARED_PLUGIN (1 , 0 , MyWriter , Writer , s_info)
pdal::CREATE_SHARED_PLUGIN (1 , 0 , MyKernel , Kernel , s_info)
pdal::CREATE_SHARED_PLUGIN (1 , 0 , IcpFilter , Filter , s_info)
pdal::CREATE_SHARED_PLUGIN (1 , 0 , CpdFilter , Filter , s_info)
pdal::CREATE_STATIC_PLUGIN (1 , 0 , GDALWriter , Writer , s_info)
pdal::CREATE_STATIC_PLUGIN (1 , 0 , GDALReader , Reader , s_info)
pdal::CREATE_STATIC_PLUGIN (1 , 0 , PlyReader , Reader , s_info)
pdal::CREATE_STATIC_PLUGIN (1 , 0 , OptechReader , Reader , s_info)
pdal::CREATE_STATIC_PLUGIN (1 , 0 , OGRWriter , Writer , s_info)
pdal::georeference::RotationMatrix pdal::createOptechRotationMatrix (double roll, double pitch, double heading)
Definition at line 81 of file OptechCommon.hpp.
Referenced by pdal::OptechReader::initialize(), and pdal::OptechReader::read().
std::string pdal::extractRivlibURI (const Options & options)
PDAL_DLL XMLSchema pdal::fetchSchema (Statement stmt, BlockPtr block)
Definition at line 97 of file OciCommon.cpp.
Referenced by pdal::OciReader::addDimensions(), and pdal::OciReader::findSchema().
PDAL_DLL Dimension::IdList pdal::fileDimensions ()
Definition at line 40 of file SbetCommon.cpp.
References pdal::Dimension::Azimuth, pdal::Dimension::GpsTime, pdal::Dimension::Pitch, pdal::Dimension::Roll, pdal::Dimension::WanderAngle, pdal::Dimension::X, pdal::Dimension::XBodyAccel, pdal::Dimension::XBodyAngRate, pdal::Dimension::XVelocity, pdal::Dimension::Y, pdal::Dimension::YBodyAccel, pdal::Dimension::YBodyAngRate, pdal::Dimension::YVelocity, pdal::Dimension::Z, pdal::Dimension::ZBodyAccel, pdal::Dimension::ZBodyAngRate, and pdal::Dimension::ZVelocity.
Referenced by pdal::PcdReader::addDimensions(), pdal::SbetReader::addDimensions(), pdal::SbetReader::ready(), pdal::SbetReader::seek(), and pdal::SbetWriter::write().
pdal::CompressionType pdal::getCompressionType (std::string compression_type)
Definition at line 47 of file PgCommon.hpp.
References Dimensional, Ght, Lazperf, None, and pdal::Utils::tolower().
Referenced by pdal::PgWriter::initialize().
template<typename T > T pdal::getData (LizardTech::PointData & points, const char * channelId, point_count_t pointIndex)
Definition at line 241 of file MrsidReader.cpp.
std::string pdal::GetDefaultSoftwareId ()
Definition at line 56 of file LasHeader.cpp.
References GetSHA1(), and PDAL_VERSION_STRING.
Referenced by pdal::LasWriter::addArgs().
PDAL_DLL std::string pdal::GetFullVersionString ()
Tell the user a bit about PDAL's compilation.
Definition at line 122 of file pdal_config.cpp.
References GetSHA1(), pdal::Utils::iequals(), and PDAL_VERSION_STRING.
Referenced by pdal::HausdorffKernel::execute(), getPDALDebugInformation(), App::outputVersion(), pdal::InfoKernel::run(), and TEST().
std::string pdal::getJSON ()
Definition at line 66 of file PolygonTest.cpp.
References pdal::FileUtils::closeFile(), Support::datapath(), and pdal::FileUtils::openFile().
Referenced by TEST().
PDAL_DLL std::string pdal::getPDALDebugInformation ()
Definition at line 136 of file pdal_config.cpp.
References GetFullVersionString(), headline(), PDAL_BUILD_TYPE, and pdal::Utils::screenWidth().
pdal::Dimension::Type pdal::getPDALType (LizardTech::DataType t)
Definition at line 77 of file MrsidReader.cpp.
Referenced by pdal::MrsidReader::addDimensions().
Dimension::IdList pdal::getRxpDimensions (bool syncToPps, bool minimal, bool reflectanceAsIntensity)
Definition at line 59 of file RxpReader.cpp.
References pdal::Dimension::Amplitude, pdal::Dimension::BackgroundRadiation, pdal::Dimension::Deviation, pdal::Dimension::EchoRange, getTimeDimensionId(), pdal::Dimension::Intensity, pdal::Dimension::IsPpsLocked, pdal::Dimension::NumberOfReturns, pdal::Dimension::Reflectance, pdal::Dimension::ReturnNumber, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by pdal::RxpReader::addDimensions().
Dimension::IdList pdal::getRxpDimensions (bool syncToPps, bool minimal)
PDAL_DLL std::string pdal::GetSHA1 ()
Definition at line 115 of file pdal_config.cpp.
References g_GIT_SHA1.
Referenced by GetDefaultSoftwareId(), and GetFullVersionString().
Dimension::Id pdal::getTimeDimensionId (bool syncToPps)
Definition at line 49 of file RxpPointcloud.cpp.
References pdal::Dimension::GpsTime, and pdal::Dimension::InternalTime.
Referenced by checkPoint(), getRxpDimensions(), and pdal::RxpPointcloud::on_echo_transformed().
PDAL_DLL int pdal::GetVersionInteger ()
Definition at line 110 of file pdal_config.cpp.
References PDAL_VERSION_INTEGER.
Referenced by TEST().
PDAL_DLL int pdal::GetVersionMajor ()
Definition at line 90 of file pdal_config.cpp.
References PDAL_VERSION_MAJOR.
Referenced by TEST().
PDAL_DLL int pdal::GetVersionMinor ()
Definition at line 95 of file pdal_config.cpp.
References PDAL_VERSION_MINOR.
Referenced by TEST().
PDAL_DLL int pdal::GetVersionPatch ()
Definition at line 100 of file pdal_config.cpp.
References PDAL_VERSION_PATCH.
Referenced by TEST().
PDAL_DLL std::string pdal::GetVersionString ()
Definition at line 105 of file pdal_config.cpp.
References PDAL_VERSION_STRING.
Referenced by TEST().
std::string pdal::getWKT ()
Definition at line 51 of file PolygonTest.cpp.
References pdal::FileUtils::closeFile(), Support::datapath(), and pdal::FileUtils::openFile().
Referenced by pdal::SpatialReference::equals(), pdal::SpatialReference::operator<(), TEST(), and pdal::SpatialReference::toMetadata().
pdal::INSTANTIATE_TEST_CASE_P (base , json , testing::Values("pipeline/assign.json","pipeline/bpf2las.json","pipeline/chipper.json","pipeline/colorize-multi.json","pipeline/colorize.json","pipeline/crop-hole.json","pipeline/crop_wkt.json","pipeline/crop_wkt_2d.json","pipeline/decimate.json","pipeline/ferry-reproject.json","pipeline/las2csv.json","pipeline/las2geojson.json","pipeline/las2space-delimited.json","pipeline/merge.json","pipeline/metadata_reader.json","pipeline/metadata_writer.json","pipeline/mississippi.json","pipeline/mississippi_reverse.json","pipeline/overlay.json","pipeline/range_z.json","pipeline/range_z_classification.json","pipeline/range_classification.json","pipeline/sbet2txt.json","pipeline/sort.json","pipeline/splitter.json","pipeline/stats.json","pipeline/transformation.json"))
Referenced by TEST(), TEST_P(), and TEST_P().
pdal::INSTANTIATE_TEST_CASE_P (plugins , jsonWithNITF , testing::Values("pipeline/bpf2nitf.json","pipeline/las2nitf.json","pipeline/las2nitf-crop-with-options.json","pipeline/nitf2las.json"))
pdal::INSTANTIATE_TEST_CASE_P (plugins , jsonWithP2G , testing::Values("pipeline/p2g-writer.json"))
pdal::INSTANTIATE_TEST_CASE_P (plugins , jsonWithHexer , testing::Values("pipeline/hexbin-info.json","pipeline/hexbin.json"))
pdal::INSTANTIATE_TEST_CASE_P (plugins , jsonWithLAZ , testing::Values("pipeline/crop.json","pipeline/crop-stats.json"))
static bool pdal::is_base64 (unsigned char c) static
Definition at line 276 of file Utils.cpp.
Referenced by pdal::Utils::base64_decode().
PDAL_DLL bool pdal::IsGDALEnabled ()
PDAL_DLL bool pdal::IsLasZipEnabled ()
Check if LasZip compression support has been built in to PDAL.
Definition at line 81 of file pdal_config.cpp.
Referenced by TEST().
PDAL_DLL bool pdal::IsLibGeoTIFFEnabled ()
Check if GeoTIFF support has been built in to PDAL.
Definition at line 75 of file pdal_config.cpp.
Referenced by TEST().
PDAL_DLL bool pdal::IsLibLASEnabled ()
bool pdal::isVisible (const Eigen::Vector2d & X, const Eigen::Vector2d & S1, const Eigen::Vector2d & S2, const Eigen::Vector2d & R = Eigen::Vector2d::Zero ())
Returns if a point X is visible from point R (or the origin) when taking into account the segment between the points S1 and S2.
Parameters
X 2D coordinate of the point
S1 2D coordinate of the segment's first point
S2 2D coordinate of the segment's secont point
R 2D coorddinate of the reference point (defaults to 0,0)
Definition at line 64 of file GreedyProjection.hpp.
Referenced by pdal::GreedyProjection::connectPoint(), and pdal::GreedyProjection::filter().
pdal::NITF_TRE_STATIC_HANDLER_REF (ACCHZB)
pdal::NITF_TRE_STATIC_HANDLER_REF (ACCPOB)
pdal::NITF_TRE_STATIC_HANDLER_REF (ACCVTB)
pdal::NITF_TRE_STATIC_HANDLER_REF (ACFTA)
pdal::NITF_TRE_STATIC_HANDLER_REF (ACFTB)
pdal::NITF_TRE_STATIC_HANDLER_REF (AIMIDA)
pdal::NITF_TRE_STATIC_HANDLER_REF (AIMIDB)
pdal::NITF_TRE_STATIC_HANDLER_REF (AIPBCA)
pdal::NITF_TRE_STATIC_HANDLER_REF (ASTORA)
pdal::NITF_TRE_STATIC_HANDLER_REF (BANDSA)
pdal::NITF_TRE_STATIC_HANDLER_REF (BANDSB)
pdal::NITF_TRE_STATIC_HANDLER_REF (BCKGDA)
pdal::NITF_TRE_STATIC_HANDLER_REF (BLOCKA)
pdal::NITF_TRE_STATIC_HANDLER_REF (BNDPLB)
pdal::NITF_TRE_STATIC_HANDLER_REF (CLCTNA)
pdal::NITF_TRE_STATIC_HANDLER_REF (CLCTNB)
pdal::NITF_TRE_STATIC_HANDLER_REF (CMETAA)
pdal::NITF_TRE_STATIC_HANDLER_REF (CSCCGA)
pdal::NITF_TRE_STATIC_HANDLER_REF (CSCRNA)
pdal::NITF_TRE_STATIC_HANDLER_REF (CSDIDA)
pdal::NITF_TRE_STATIC_HANDLER_REF (CSEPHA)
pdal::NITF_TRE_STATIC_HANDLER_REF (CSEXRA)
pdal::NITF_TRE_STATIC_HANDLER_REF (CSPROA)
pdal::NITF_TRE_STATIC_HANDLER_REF (CSSFAA)
pdal::NITF_TRE_STATIC_HANDLER_REF (CSSHPA)
pdal::NITF_TRE_STATIC_HANDLER_REF (ENGRDA)
pdal::NITF_TRE_STATIC_HANDLER_REF (EXOPTA)
pdal::NITF_TRE_STATIC_HANDLER_REF (EXPLTA)
pdal::NITF_TRE_STATIC_HANDLER_REF (EXPLTB)
pdal::NITF_TRE_STATIC_HANDLER_REF (GEOLOB)
pdal::NITF_TRE_STATIC_HANDLER_REF (GEOPSB)
pdal::NITF_TRE_STATIC_HANDLER_REF (GRDPSB)
pdal::NITF_TRE_STATIC_HANDLER_REF (HISTOA)
pdal::NITF_TRE_STATIC_HANDLER_REF (ICHIPB)
pdal::NITF_TRE_STATIC_HANDLER_REF (IMGDTA)
pdal::NITF_TRE_STATIC_HANDLER_REF (IOMAPA)
pdal::NITF_TRE_STATIC_HANDLER_REF (J2KLRA)
pdal::NITF_TRE_STATIC_HANDLER_REF (JITCID)
pdal::NITF_TRE_STATIC_HANDLER_REF (MAPLOB)
pdal::NITF_TRE_STATIC_HANDLER_REF (MENSRA)
pdal::NITF_TRE_STATIC_HANDLER_REF (MENSRB)
pdal::NITF_TRE_STATIC_HANDLER_REF (MPDSRA)
pdal::NITF_TRE_STATIC_HANDLER_REF (MSTGTA)
pdal::NITF_TRE_STATIC_HANDLER_REF (MTIRPA)
pdal::NITF_TRE_STATIC_HANDLER_REF (MTIRPB)
pdal::NITF_TRE_STATIC_HANDLER_REF (NBLOCA)
pdal::NITF_TRE_STATIC_HANDLER_REF (OBJCTA)
pdal::NITF_TRE_STATIC_HANDLER_REF (OFFSET)
pdal::NITF_TRE_STATIC_HANDLER_REF (PATCHA)
pdal::NITF_TRE_STATIC_HANDLER_REF (PATCHB)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIAEQA)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIAEVA)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIAIMB)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIAIMC)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIAPEA)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIAPEB)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIAPRC)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIAPRD)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIATGA)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIATGB)
pdal::NITF_TRE_STATIC_HANDLER_REF (PIXQLA)
pdal::NITF_TRE_STATIC_HANDLER_REF (PLTFMA)
pdal::NITF_TRE_STATIC_HANDLER_REF (PRJPSB)
pdal::NITF_TRE_STATIC_HANDLER_REF (REGPTB)
pdal::NITF_TRE_STATIC_HANDLER_REF (RPC00B)
pdal::NITF_TRE_STATIC_HANDLER_REF (RPFDES)
pdal::NITF_TRE_STATIC_HANDLER_REF (RPFHDR)
pdal::NITF_TRE_STATIC_HANDLER_REF (RPFIMG)
pdal::NITF_TRE_STATIC_HANDLER_REF (RSMAPA)
pdal::NITF_TRE_STATIC_HANDLER_REF (RSMDCA)
pdal::NITF_TRE_STATIC_HANDLER_REF (RSMECA)
pdal::NITF_TRE_STATIC_HANDLER_REF (RSMGGA)
pdal::NITF_TRE_STATIC_HANDLER_REF (RSMGIA)
pdal::NITF_TRE_STATIC_HANDLER_REF (RSMIDA)
pdal::NITF_TRE_STATIC_HANDLER_REF (RSMPCA)
pdal::NITF_TRE_STATIC_HANDLER_REF (RSMPIA)
pdal::NITF_TRE_STATIC_HANDLER_REF (SECTGA)
pdal::NITF_TRE_STATIC_HANDLER_REF (SENSRA)
pdal::NITF_TRE_STATIC_HANDLER_REF (SENSRB)
pdal::NITF_TRE_STATIC_HANDLER_REF (SNSPSB)
pdal::NITF_TRE_STATIC_HANDLER_REF (SNSRA)
pdal::NITF_TRE_STATIC_HANDLER_REF (SOURCB)
pdal::NITF_TRE_STATIC_HANDLER_REF (STDIDC)
pdal::NITF_TRE_STATIC_HANDLER_REF (STEROB)
pdal::NITF_TRE_STATIC_HANDLER_REF (STREOB)
pdal::NITF_TRE_STATIC_HANDLER_REF (TRGTA)
pdal::NITF_TRE_STATIC_HANDLER_REF (USE00A)
void pdal::OCISchemaGenericErrorHandler (void * , const char * message, ...)
Definition at line 144 of file XMLSchema.cpp.
Referenced by pdal::XMLSchema::init(), and OCISchemaValidityDebug().
void pdal::OCISchemaParserStructuredErrorHandler (void * , xmlErrorPtr error)
Definition at line 101 of file XMLSchema.cpp.
References OCISchemaValidationStructuredErrorHandler().
Referenced by OCISchemaStructuredErrorHandler(), and pdal::XMLSchema::validate().
void pdal::OCISchemaStructuredErrorHandler (void * , xmlErrorPtr error)
Definition at line 76 of file XMLSchema.cpp.
References OCISchemaParserStructuredErrorHandler().
Referenced by pdal::XMLSchema::init().
void pdal::OCISchemaValidationStructuredErrorHandler (void * , xmlErrorPtr error)
Definition at line 108 of file XMLSchema.cpp.
References OCISchemaValidityError().
Referenced by OCISchemaParserStructuredErrorHandler().
void pdal::OCISchemaValidityDebug (void * , const char * message, ...)
Definition at line 129 of file XMLSchema.cpp.
References OCISchemaGenericErrorHandler().
Referenced by OCISchemaValidityError(), and pdal::XMLSchema::validate().
void pdal::OCISchemaValidityError (void * , const char * message, ...)
Definition at line 115 of file XMLSchema.cpp.
References OCISchemaValidityDebug().
Referenced by OCISchemaValidationStructuredErrorHandler(), and pdal::XMLSchema::validate().
std::shared_ptr<gdal::Raster> pdal::openRamp (std::string & rampFilename)
Definition at line 87 of file ColorinterpFilter.cpp.
References awesome_green, black_orange, blue_hue, blue_orange, blue_red, GETRAMP, heat_map, and pestel_shades.
Referenced by pdal::ColorinterpFilter::ready().
bool pdal::operator!= (const MetadataNode & m1, const MetadataNode & m2)
Definition at line 661 of file Metadata.hpp.
References pdal::MetadataNode::m_impl.
Referenced by pdal::Geometry::getSpatialReference(), and pdal::SpatialReference::SpatialReference().
bool pdal::operator< (const uuid & u1, const uuid & u2)
Definition at line 86 of file Uuid.hpp.
References pdal::uuid::node, pdal::uuid::time_hi_and_version, pdal::uuid::time_low, and pdal::uuid::time_mid.
bool pdal::operator< (const XMLDim & d1, const XMLDim & d2)
Definition at line 90 of file XMLSchema.hpp.
References pdal::XMLDim::m_position.
bool pdal::operator< (const DimRange & r1, const DimRange & r2)
Definition at line 138 of file DimRange.cpp.
References pdal::DimRange::m_name.
bool pdal::operator< (const Uuid & u1, const Uuid & u2)
Definition at line 215 of file Uuid.hpp.
References pdal::Uuid::m_data.
OLeStream& pdal::operator<< (OLeStream & out, const LasVLR & v)
Definition at line 60 of file LasVLR.cpp.
References pdal::LasVLR::data(), pdal::LasVLR::dataLen(), pdal::LasVLR::m_description, pdal::LasVLR::m_recordId, pdal::LasVLR::m_recordSig, pdal::LasVLR::m_userId, and pdal::OStream::put().
std::ostream & pdal::operator<< (std::ostream & out, const BpfFormat & format)
Definition at line 62 of file BpfHeader.cpp.
References ByteMajor, DimMajor, and PointMajor.
std::ostream& pdal::operator<< (std::ostream & out, const LasCompression & c)
Definition at line 66 of file LasUtils.hpp.
References LasZip, LazPerf, and None.
std::ostream& pdal::operator<< (std::ostream & out, const DividerFilter::Mode & mode)
Definition at line 67 of file DividerFilter.cpp.
References pdal::DividerFilter::Partition, and pdal::DividerFilter::RoundRobin.
std::ostream & pdal::operator<< (std::ostream & out, const Ilvis2Reader::IlvisMapping & mval)
Definition at line 73 of file Ilvis2Reader.cpp.
References pdal::Ilvis2Reader::ALL, pdal::Ilvis2Reader::HIGH, pdal::Ilvis2Reader::INVALID, and pdal::Ilvis2Reader::LOW.
std::ostream& pdal::operator<< (std::ostream & out, const BpfWriter::CoordId & id)
Definition at line 74 of file BpfWriter.cpp.
std::ostream& pdal::operator<< (std::ostream & out, const Mode & m)
Definition at line 79 of file FauxReader.hpp.
References Constant, Grid, Normal, Ramp, Random, and Uniform.
OLeStream & pdal::operator<< (OLeStream & stream, BpfMuellerMatrix & m)
Definition at line 84 of file BpfHeader.cpp.
References pdal::BpfMuellerMatrix::m_vals.
OLeStream& pdal::operator<< (OLeStream & out, const ExtLasVLR & v)
Definition at line 89 of file LasVLR.cpp.
References pdal::LasVLR::data(), pdal::LasVLR::dataLen(), pdal::LasVLR::description(), pdal::OStream::put(), pdal::LasVLR::recordId(), and pdal::LasVLR::userId().
std::ostream & pdal::operator<< (std::ostream & out, const SortOrder & order)
Definition at line 90 of file SortFilter.cpp.
References ASC, and DESC.
PDAL_DLL std::ostream & pdal::operator<< (std::ostream & ostr, const LasSummaryData & data)
Definition at line 103 of file LasSummaryData.cpp.
References pdal::LasSummaryData::dump().
std::ostream& pdal::operator<< (std::ostream & out, const PlyWriter::Format & f)
Definition at line 103 of file PlyWriter.hpp.
References pdal::PlyWriter::Ascii, pdal::PlyWriter::BinaryBe, and pdal::PlyWriter::BinaryLe.
std::ostream& pdal::operator<< (std::ostream & out, const AssignRange & r)
Definition at line 105 of file AssignFilter.cpp.
References pdal::DimRange::m_name.
Referenced by pdal::BpfMuellerMatrix::apply(), pdal::Bounds::Bounds(), pdal::ExtLasVLR::ExtLasVLR(), operator<<(), pdal::Inserter::position(), pdal::LasVLR::setDataLen(), and pdal::LasHeader::vlrs().
template<typename T , T MIN, T MAX> std::ostream& pdal::operator<< (std::ostream & out, const NumHeaderVal< T, MIN, MAX > & h)
Definition at line 108 of file HeaderVal.hpp.
References pdal::NumHeaderVal< T, MIN, MAX >::val().
PDAL_DLL std::ostream & pdal::operator<< (std::ostream & ostr, const Kernel & kernel)
Definition at line 128 of file Kernel.cpp.
References pdal::Kernel::getName().
std::ostream& pdal::operator<< (std::ostream & out, const XForm::XFormComponent & xfc)
Definition at line 143 of file pdal_types.hpp.
References pdal::XForm::XFormComponent::m_auto, and pdal::XForm::XFormComponent::m_val.
std::ostream & pdal::operator<< (std::ostream & out, const DimRange & r)
Definition at line 156 of file DimRange.cpp.
References if(), pdal::DimRange::m_inclusive_lower_bound, pdal::DimRange::m_inclusive_upper_bound, pdal::DimRange::m_lower_bound, and pdal::DimRange::m_upper_bound.
std::ostream& pdal::operator<< (std::ostream & out, const MbFormat & f)
Definition at line 178 of file MbFormat.cpp.
References pdal::anonymous_namespace{MbFormat.cpp}::formats, and pdal::MbFormat::m_value.
template<size_t LEN> std::ostream& pdal::operator<< (std::ostream & out, const StringHeaderVal< LEN > & h)
Definition at line 181 of file HeaderVal.hpp.
References pdal::StringHeaderVal< LEN >::val().
std::ostream& pdal::operator<< (std::ostream & out, const LogLevel & level)
Definition at line 200 of file pdal_types.hpp.
References pdal::anonymous_namespace{pdal_types.hpp}::logNames, and pdal::Utils::toupper().
std::ostream& pdal::operator<< (std::ostream & out, const UuidHeaderVal & h)
Definition at line 219 of file HeaderVal.hpp.
References pdal::UuidHeaderVal::val().
std::ostream& pdal::operator<< (std::ostream & out, const Uuid & u)
Definition at line 220 of file Uuid.hpp.
References pdal::Uuid::toString().
PDAL_DLL std::ostream& pdal::operator<< (std::ostream & ostr, const Options &)
PDAL_DLL std::ostream & pdal::operator<< (std::ostream & ostr, const PointView & buf)
Definition at line 298 of file PointView.cpp.
References pdal::PointView::dump().
std::ostream& pdal::operator<< (std::ostream & ostr, const Geometry & p)
Definition at line 324 of file Geometry.cpp.
References pdal::Geometry::wkt().
PDAL_DLL std::ostream & pdal::operator<< (std::ostream & out, const Bounds & bounds)
Definition at line 326 of file Bounds.cpp.
References pdal::Bounds::is3d(), pdal::Bounds::to2d(), and pdal::Bounds::to3d().
OLeStream& pdal::operator<< (OLeStream & out, const LasHeader & h)
Definition at line 407 of file LasHeader.cpp.
References pdal::LasHeader::compressed(), pdal::LasHeader::LEGACY_RETURN_COUNT, pdal::LasHeader::m_createDOY, pdal::LasHeader::m_createYear, pdal::LasHeader::m_eVlrCount, pdal::LasHeader::m_eVlrOffset, pdal::LasHeader::m_fileSig, pdal::LasHeader::m_globalEncoding, pdal::LasHeader::m_offsets, pdal::LasHeader::m_pointCount, pdal::LasHeader::m_pointCountByReturn, pdal::LasHeader::m_pointFormat, pdal::LasHeader::m_pointLen, pdal::LasHeader::m_pointOffset, pdal::LasHeader::m_projectUuid, pdal::LasHeader::m_scales, pdal::LasHeader::m_softwareId, pdal::LasHeader::m_sourceId, pdal::LasHeader::m_systemId, pdal::LasHeader::m_versionMinor, pdal::LasHeader::m_vlrCount, pdal::LasHeader::m_vlrOffset, pdal::LasHeader::maxX(), pdal::LasHeader::maxY(), pdal::LasHeader::maxZ(), pdal::LasHeader::minX(), pdal::LasHeader::minY(), pdal::LasHeader::minZ(), pdal::LasHeader::pointFormat(), pdal::OStream::put(), pdal::LasHeader::put(), pdal::LasHeader::RETURN_COUNT, pdal::LasHeader::versionAtLeast(), and pdal::LasHeader::versionEquals().
std::ostream& pdal::operator<< (std::ostream & out, const LasHeader & h)
Definition at line 458 of file LasHeader.cpp.
References pdal::LasHeader::m_createDOY, pdal::LasHeader::m_createYear, pdal::LasHeader::m_eVlrCount, pdal::LasHeader::m_eVlrOffset, pdal::LasHeader::m_fileSig, pdal::LasHeader::m_globalEncoding, pdal::LasHeader::m_isCompressed, pdal::LasHeader::m_offsets, pdal::LasHeader::m_pointCount, pdal::LasHeader::m_pointCountByReturn, pdal::LasHeader::m_pointFormat, pdal::LasHeader::m_pointOffset, pdal::LasHeader::m_projectUuid, pdal::LasHeader::m_scales, pdal::LasHeader::m_softwareId, pdal::LasHeader::m_sourceId, pdal::LasHeader::m_systemId, pdal::LasHeader::m_versionMinor, pdal::LasHeader::m_vlrCount, pdal::LasHeader::m_vlrOffset, pdal::LasHeader::maxX(), pdal::LasHeader::maxY(), pdal::LasHeader::maxZ(), pdal::LasHeader::minX(), pdal::LasHeader::minY(), pdal::LasHeader::minZ(), pdal::LasHeader::RETURN_COUNT, and pdal::LasHeader::versionAtLeast().
PDAL_DLL std::ostream & pdal::operator<< (std::ostream & ostr, const SpatialReference & srs)
Definition at line 515 of file SpatialReference.cpp.
References pdal::SpatialReference::m_wkt.
std::ostream& pdal::operator<< (std::ostream & ostr, const BOX2D & bounds)
Write a 2D bounds box to a stream in a format used by PDAL options.
Parameters
ostr Stream to write to.
bounds Box to write.
Definition at line 594 of file Bounds.hpp.
References pdal::BOX2D::empty(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, and pdal::BOX2D::miny.
std::ostream& pdal::operator<< (std::ostream & ostr, const BOX3D & bounds)
Write a 3D bounds box to a stream in a format used by PDAL options.
Parameters
ostr Stream to write to.
bounds Box to write.
Definition at line 618 of file Bounds.hpp.
References pdal::BOX3D::empty(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::BOX3D::minz, operator<<(), operator>>(), and PDAL_DLL.
bool pdal::operator== (const ExtraDim & ed1, const ExtraDim & ed2)
Definition at line 95 of file LasUtils.hpp.
References pdal::ExtraDim::m_dimType, pdal::ExtraDim::m_name, pdal::ExtraDim::m_size, and pdal::DimType::m_type.
Referenced by pdal::ExtraDim::ExtraDim(), pdal::Geometry::getSpatialReference(), and pdal::SpatialReference::SpatialReference().
bool pdal::operator== (const Uuid & u1, const Uuid & u2)
Definition at line 210 of file Uuid.hpp.
bool pdal::operator== (const MetadataNode & m1, const MetadataNode & m2)
Definition at line 656 of file Metadata.hpp.
References pdal::MetadataNode::m_impl.
ILeStream& pdal::operator>> (ILeStream & in, LasVLR & v)
Definition at line 42 of file LasVLR.cpp.
References pdal::IStream::get(), pdal::LasVLR::m_data, pdal::LasVLR::m_description, pdal::LasVLR::m_recordId, and pdal::LasVLR::m_userId.
std::istream & pdal::operator>> (std::istream & in, BpfFormat & format)
Definition at line 45 of file BpfHeader.cpp.
References ByteMajor, DimMajor, PointMajor, and pdal::Utils::toupper().
std::istream& pdal::operator>> (std::istream & in, DividerFilter::Mode & mode)
Definition at line 50 of file DividerFilter.cpp.
References pdal::DividerFilter::Partition, pdal::DividerFilter::RoundRobin, and pdal::Utils::tolower().
std::istream& pdal::operator>> (std::istream & in, LasCompression & c)
Definition at line 51 of file LasUtils.hpp.
References LasZip, LazPerf, None, and pdal::Utils::toupper().
std::istream& pdal::operator>> (std::istream & in, Ilvis2Reader::IlvisMapping & mval)
Definition at line 55 of file Ilvis2Reader.cpp.
References pdal::Ilvis2Reader::ALL, pdal::Ilvis2Reader::HIGH, pdal::Ilvis2Reader::INVALID, pdal::Ilvis2Reader::LOW, and pdal::Utils::toupper().
std::istream& pdal::operator>> (std::istream & in, Mode & m)
Definition at line 56 of file FauxReader.hpp.
References Constant, Grid, Normal, Ramp, Random, pdal::Utils::tolower(), and Uniform.
std::istream& pdal::operator>> (std::istream & in, BpfWriter::CoordId & id)
Definition at line 63 of file BpfWriter.cpp.
References pdal::Utils::fromString().
ILeStream& pdal::operator>> (ILeStream & in, ExtLasVLR & v)
Definition at line 72 of file LasVLR.cpp.
References pdal::IStream::get(), pdal::LasVLR::m_data, pdal::LasVLR::m_description, pdal::LasVLR::m_recordId, pdal::LasVLR::m_recordSig, and pdal::LasVLR::m_userId.
std::istream & pdal::operator>> (std::istream & in, SortOrder & order)
Definition at line 75 of file SortFilter.cpp.
References ASC, DESC, and pdal::Utils::toupper().
ILeStream & pdal::operator>> (ILeStream & stream, BpfMuellerMatrix & m)
Definition at line 76 of file BpfHeader.cpp.
References pdal::BpfMuellerMatrix::m_vals.
std::istream& pdal::operator>> (std::istream & in, PlyWriter::Format & f)
Definition at line 85 of file PlyWriter.hpp.
References pdal::PlyWriter::Ascii, pdal::PlyWriter::BinaryBe, pdal::PlyWriter::BinaryLe, pdal::Utils::tolower(), and pdal::Utils::trim().
std::istream& pdal::operator>> (std::istream & in, AssignRange & r)
Definition at line 88 of file AssignFilter.cpp.
References pdal::AssignRange::parse().
Referenced by pdal::BpfMuellerMatrix::apply(), pdal::Bounds::Bounds(), pdal::ExtLasVLR::ExtLasVLR(), pdal::Extractor::get(), operator<<(), pdal::LasVLR::setDataLen(), and pdal::LasHeader::vlrs().
template<typename T , T MIN, T MAX> std::istream& pdal::operator>> (std::istream & in, NumHeaderVal< T, MIN, MAX > & h)
Definition at line 96 of file HeaderVal.hpp.
References pdal::Utils::fromString(), and pdal::NumHeaderVal< T, MIN, MAX >::setVal().
std::istream& pdal::operator>> (std::istream & in, XForm::XFormComponent & xfc)
Definition at line 133 of file pdal_types.hpp.
References pdal::XForm::XFormComponent::set().
std::istream& pdal::operator>> (std::istream & in, DoubleHeaderVal & h)
Definition at line 137 of file HeaderVal.hpp.
References pdal::DoubleHeaderVal::setVal().
std::istream & pdal::operator>> (std::istream & in, DimRange & r)
Definition at line 146 of file DimRange.cpp.
References pdal::DimRange::parse().
std::istream& pdal::operator>> (std::istream & in, MbFormat & f)
Definition at line 146 of file MbFormat.cpp.
References pdal::anonymous_namespace{MbFormat.cpp}::formats, pdal::MbFormat::m_value, and pdal::Utils::toupper().
template<size_t LEN> std::istream& pdal::operator>> (std::istream & in, StringHeaderVal< LEN > & h)
Definition at line 171 of file HeaderVal.hpp.
References pdal::StringHeaderVal< LEN >::setVal().
std::istream& pdal::operator>> (std::istream & in, LogLevel & level)
Definition at line 173 of file pdal_types.hpp.
References pdal::anonymous_namespace{pdal_types.hpp}::logNames, None, and pdal::Utils::tolower().
PDAL_DLL std::istream & pdal::operator>> (std::istream & istr, BOX2D & bounds)
Read a 2D bounds box from a stream in a format provided by PDAL options.
Parameters
istr Stream to read from.
bounds Bounds box to populate.
Definition at line 200 of file Bounds.cpp.
References anonymous_namespace{Bounds.cpp}::eat(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, pdal::BOX2D::miny, and anonymous_namespace{Bounds.cpp}::readpair().
std::istream& pdal::operator>> (std::istream & in, UuidHeaderVal & h)
Definition at line 210 of file HeaderVal.hpp.
References pdal::UuidHeaderVal::setVal().
std::istream& pdal::operator>> (std::istream & in, Uuid & u)
Definition at line 226 of file Uuid.hpp.
References pdal::Uuid::parse().
PDAL_DLL std::istream & pdal::operator>> (std::istream & istr, BOX3D & bounds)
Read a 3D bounds box from a stream in a format provided by PDAL options.
Parameters
istr Stream to read from.
bounds Bounds box to populate.
Definition at line 252 of file Bounds.cpp.
References anonymous_namespace{Bounds.cpp}::eat(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::BOX3D::minz, and anonymous_namespace{Bounds.cpp}::readpair().
PDAL_DLL std::istream & pdal::operator>> (std::istream & in, Bounds & bounds)
Definition at line 307 of file Bounds.cpp.
References pdal::BOX3D::clear(), and pdal::Bounds::set().
ILeStream& pdal::operator>> (ILeStream & in, LasHeader & h)
Definition at line 326 of file LasHeader.cpp.
References BOX3D, pdal::LasHeader::FILE_SIGNATURE, pdal::IStream::get(), pdal::LasHeader::get(), pdal::Utils::iequals(), pdal::LasHeader::LEGACY_RETURN_COUNT, pdal::LasHeader::m_bounds, pdal::LasHeader::m_createDOY, pdal::LasHeader::m_createYear, pdal::LasHeader::m_eVlrCount, pdal::LasHeader::m_eVlrOffset, pdal::LasHeader::m_fileSig, pdal::LasHeader::m_globalEncoding, pdal::LasHeader::m_offsets, pdal::LasHeader::m_pointCount, pdal::LasHeader::m_pointCountByReturn, pdal::LasHeader::m_pointFormat, pdal::LasHeader::m_pointLen, pdal::LasHeader::m_pointOffset, pdal::LasHeader::m_projectUuid, pdal::LasHeader::m_scales, pdal::LasHeader::m_softwareId, pdal::LasHeader::m_sourceId, pdal::LasHeader::m_systemId, pdal::LasHeader::m_versionMinor, pdal::LasHeader::m_vlrCount, pdal::LasHeader::m_vlrOffset, pdal::LasHeader::m_vlrs, pdal::LasHeader::maxX(), pdal::LasHeader::maxY(), pdal::LasHeader::maxZ(), pdal::LasHeader::minX(), pdal::LasHeader::minY(), pdal::LasHeader::minZ(), pdal::LasHeader::RETURN_COUNT, pdal::IStream::seek(), pdal::LasHeader::setCompressed(), pdal::LasHeader::setSrs(), pdal::LasHeader::versionAtLeast(), and pdal::LasHeader::versionMajor().
std::istream& pdal::operator>> (std::istream & istr, Geometry & p)
Definition at line 331 of file Geometry.cpp.
References pdal::Geometry::update().
PDAL_DLL std::istream & pdal::operator>> (std::istream & istr, SpatialReference & srs)
Definition at line 522 of file SpatialReference.cpp.
References pdal::SpatialReference::set().
GDALDataType pdal::OWGetDataType (const char * pszCellDepth)
Definition at line 2386 of file OciWrapper.cpp.
References ahOW_CellDepth, and pdal::OW_CellDepth::eDataType.
bool pdal::OWIsNumeric (const char * pszText)
Definition at line 2173 of file OciWrapper.cpp.
int pdal::OWParseEPSG (const char * pszText)
Definition at line 2375 of file OciWrapper.cpp.
References OWParseValue().
const char * pdal::OWParseSDO_GEOR_INIT (const char * pszInsert, int nField)
Definition at line 2306 of file OciWrapper.cpp.
References OWParseValue(), OWTEXT, and pdal::Utils::toupper().
int pdal::OWParseServerVersion (const char * pszText)
Definition at line 2357 of file OciWrapper.cpp.
References OWParseValue().
Referenced by pdal::OWConnection::OWConnection().
const char* pdal::OWParseValue (const char * pszText, const char * pszSeparators, const char * pszHint, int nOffset)
Definition at line 2266 of file OciWrapper.cpp.
Referenced by OWParseEPSG(), OWParseSDO_GEOR_INIT(), and OWParseServerVersion().
const char * pdal::OWReplaceString (const char * pszBaseString, const char * pszToken, const char * pszStopToken, const char * pszOWReplaceToken)
Definition at line 2203 of file OciWrapper.cpp.
References OWTEXT, and pdal::Utils::toupper().
const char * pdal::OWSetDataType (const GDALDataType eType)
Definition at line 2407 of file OciWrapper.cpp.
References ahOW_CellDepth, and pdal::OW_CellDepth::pszValue.
void pdal::pg_begin (PGconn * session)
Definition at line 99 of file PgCommon.hpp.
References pg_execute().
Referenced by pdal::PgReader::CursorSetup(), and pdal::PgWriter::writeInit().
void pdal::pg_commit (PGconn * session)
Definition at line 105 of file PgCommon.hpp.
References pg_execute().
Referenced by pdal::PgReader::CursorTeardown(), and pdal::PgWriter::done().
PGconn* pdal::pg_connect (std::string const & connection)
Definition at line 60 of file PgCommon.hpp.
Referenced by pdal::PgWriter::initialize(), pdal::PgReader::initialize(), and PgpointcloudWriterTest::SetUp().
void pdal::pg_execute (PGconn * session, std::string const & sql)
Definition at line 88 of file PgCommon.hpp.
Referenced by pdal::PgWriter::CheckPointCloudExists(), pdal::PgWriter::CheckPostGISExists(), pdal::PgWriter::CreateIndex(), pdal::PgWriter::CreateTable(), pdal::PgReader::CursorSetup(), pdal::PgReader::CursorTeardown(), pdal::PgWriter::DeleteTable(), pdal::PgWriter::done(), PgpointcloudWriterTest::execute(), PgpointcloudWriterTest::executeOnMasterDb(), PgpointcloudWriterTest::executeOnTestDb(), pg_begin(), pg_commit(), pdal::PgWriter::writeInit(), and pdal::PgWriter::writeTile().
std::string pdal::pg_query_once (PGconn * session, std::string const & sql)
Definition at line 111 of file PgCommon.hpp.
Referenced by pdal::PgReader::addDimensions(), pdal::PgWriter::CheckTableExists(), pdal::PgReader::fetchPcid(), pdal::PgReader::fetchSpatialReference(), and pdal::PgWriter::SetupSchema().
PGresult* pdal::pg_query_result (PGconn * session, std::string const & sql)
Definition at line 131 of file PgCommon.hpp.
Referenced by pdal::PgReader::getNumPoints(), pdal::PgReader::NextBuffer(), and pdal::PgWriter::SetupSchema().
std::string pdal::pg_quote_identifier (std::string const & name)
Definition at line 151 of file PgCommon.hpp.
References pdal::Utils::replaceAll().
Referenced by pdal::PgWriter::CreateTable(), pdal::PgWriter::DeleteTable(), pdal::PgReader::getDataQuery(), pdal::PgReader::getNumPoints(), and pdal::PgWriter::writeTile().
std::string pdal::pg_quote_literal (std::string const & lit)
Definition at line 156 of file PgCommon.hpp.
References pdal::Utils::replaceAll().
Referenced by pdal::PgReader::fetchPcid().
StringList pdal::readSTDIN ()
Definition at line 176 of file TIndexKernel.cpp.
Referenced by pdal::TIndexKernel::createFile().
void pdal::register_tre_handler (NITF_PLUGIN_INIT_FUNCTION init, NITF_PLUGIN_TRE_HANDLER_FUNCTION handler)
Definition at line 156 of file tre_plugins.cpp.
Referenced by register_tre_plugins().
void pdal::register_tre_plugins ()
Definition at line 166 of file tre_plugins.cpp.
References register_tre_handler().
Referenced by pdal::NitfFileWriter::initialize(), and pdal::NitfFileReader::NitfFileReader().
void pdal::swap (PointIdxRef && p1, PointIdxRef && p2)
Definition at line 94 of file PointViewIter.hpp.
Referenced by pdal::Tree::addPoint(), and pdal::GreedyProjection::filter().
pdal::TEST (PtsReader , Constructor)
Definition at line 43 of file PtsReaderTest.cpp.
References pdal::StageFactory::createStage(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
pdal::TEST (NitfWrap , las)
Definition at line 43 of file NitfWrapTest.cpp.
References Support::binpath(), Support::datapath(), pdal::FileUtils::deleteFile(), Support::diff_files(), Support::exename(), and pdal::Utils::run_shell_command().
pdal::TEST (PointTable , resolveType)
Build as we go.
Definition at line 44 of file PointTableTest.cpp.
References pdal::Dimension::Double, pdal::Dimension::Float, pdal::BasePointTable::layout(), pdal::PointLayout::registerDim(), pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned8, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST (Log , t1)
Definition at line 45 of file LogTest.cpp.
References Support::compare_text_files(), Support::datapath(), Debug, Debug5, pdal::FileUtils::deleteFile(), pdal::Log::get(), Info, pdal::Log::setLevel(), and Support::temppath().
pdal::TEST (StageFactoryTest , Load)
Definition at line 46 of file StageFactoryTest.cpp.
References pdal::Utils::contains(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::PluginManager::names(), PF_PluginType_Filter, PF_PluginType_Reader, and PF_PluginType_Writer.
pdal::TEST (PlyWriter , Constructor)
Definition at line 49 of file PlyWriterTest.cpp.
References pdal::StageFactory::createStage(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
pdal::TEST (PdalApp , log)
Definition at line 51 of file AppTest.cpp.
References appName(), and pdal::Utils::run_shell_command().
pdal::TEST (PtsReader , ReadPtsExtraDims)
Definition at line 54 of file PtsReaderTest.cpp.
References pdal::Options::add(), pdal::Dimension::Blue, Support::datapath(), pdal::Stage::execute(), pdal::Dimension::Green, pdal::Stage::prepare(), pdal::Dimension::Red, pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST (PlyReader , Constructor)
Definition at line 54 of file PlyReaderTest.cpp.
References pdal::StageFactory::createStage(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
pdal::TEST (OptionsTest , test_option_writing)
Definition at line 56 of file OptionsTest.cpp.
References pdal::Option::getName(), and pdal::Option::getValue().
pdal::TEST (StageFactoryTest , Load2)
Definition at line 57 of file StageFactoryTest.cpp.
References pdal::Utils::contains(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::PluginManager::names(), and PF_PluginType_Filter.
pdal::TEST (KernelTest , parseOption)
class TestKernel : public Kernel { public: virtual std::string getName() { return "TestKernel"; } int execute() { return 0; } bool test_parseStageOption(std::string o, std::string& stage, std::string& option, std::string& value) { return Kernel::parseStageOption(o, stage, option, value); } }
Definition at line 58 of file KernelTest.cpp.
References option(), and pdal::Kernel::test_parseStageOption().
pdal::TEST (PlyWriter , Write)
Definition at line 59 of file PlyWriterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::Stage::prepare(), readerOptions(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), and writerOptions().
pdal::TEST (PlyReader , ReadText)
Definition at line 64 of file PlyReaderTest.cpp.
References pdal::Options::add(), checkPoint(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
pdal::TEST (NitfWrap , altPath)
Definition at line 65 of file NitfWrapTest.cpp.
References Support::binpath(), Support::datapath(), pdal::FileUtils::deleteFile(), Support::diff_files(), Support::exename(), and pdal::Utils::run_shell_command().
pdal::TEST (TransformationMatrix , create)
Definition at line 66 of file TransformationFilterTest.cpp.
References pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and hag::filter().
pdal::TEST (Log , t2)
Definition at line 66 of file LogTest.cpp.
References Support::binpath(), Support::datapath(), pdal::FileUtils::deleteFile(), Support::exename(), pdal::Utils::run_shell_command(), and Support::temppath().
pdal::TEST (StageFactoryTest , Load3)
Definition at line 67 of file StageFactoryTest.cpp.
References pdal::Utils::contains(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::PluginManager::names(), and PF_PluginType_Reader.
pdal::TEST (PdalApp , option_file)
Definition at line 67 of file AppTest.cpp.
References appName(), Support::datapath(), pdal::Utils::run_shell_command(), and Support::temppath().
pdal::TEST (OptionsTest , json)
Definition at line 69 of file OptionsTest.cpp.
References pdal::Option::getName(), and pdal::Option::getValue().
pdal::TEST (OptechReader , Constructor)
Definition at line 71 of file OptechReaderTest.cpp.
References pdal::StageFactory::createStage(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
pdal::TEST (TerrasolidReader , Constructor)
Definition at line 72 of file TerrasolidReaderTest.cpp.
References pdal::StageFactory::createStage(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
pdal::TEST (TransformationMatrix , FromString)
Definition at line 74 of file TransformationFilterTest.cpp.
References transformationMatrixFromString().
pdal::TEST (StageFactoryTest , Load4)
Definition at line 77 of file StageFactoryTest.cpp.
References pdal::Utils::contains(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::PluginManager::names(), and PF_PluginType_Writer.
pdal::TEST (PlyWriter , mesh)
Definition at line 78 of file PlyWriterTest.cpp.
References pdal::TriangularMesh::add(), pdal::Options::add(), pdal::BufferReader::addView(), Support::compare_text_files(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::PointLayout::registerDim(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST (PolygonTest , test_wkt_in)
Definition at line 79 of file PolygonTest.cpp.
References getWKT().
pdal::TEST (PlyReader , ReadTextExtraDims)
Definition at line 84 of file PlyReaderTest.cpp.
References pdal::Options::add(), pdal::Dimension::Alpha, pdal::Dimension::Blue, Support::datapath(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Dimension::Green, pdal::Stage::prepare(), pdal::Dimension::Red, pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST (NitfWrap , bpf)
Definition at line 85 of file NitfWrapTest.cpp.
References Support::binpath(), Support::datapath(), pdal::FileUtils::deleteFile(), Support::diff_files(), Support::exename(), and pdal::Utils::run_shell_command().
pdal::TEST (PolygonTest , test_json_in)
Definition at line 86 of file PolygonTest.cpp.
References getJSON().
pdal::TEST (OptionsTest , conditional)
Definition at line 87 of file OptionsTest.cpp.
References pdal::Options::add(), pdal::Stage::addConditionalOptions(), and pdal::Stage::setOptions().
pdal::TEST (StageFactoryTest , extensionTest)
Definition at line 87 of file StageFactoryTest.cpp.
References setup::ext, pdal::StageFactory::extensions(), pdal::StageFactory::inferReaderDriver(), and pdal::StageFactory::inferWriterDriver().
pdal::TEST (IcpFilterTest , DefaultIdentity)
Definition at line 88 of file IcpFilterTest.cpp.
References hag::filter(), pdal::MetadataNode::findChild(), pdal::anonymous_namespace{IcpFilterTest.cpp}::newFilter(), pdal::anonymous_namespace{IcpFilterTest.cpp}::newReader(), pdal::Dimension::size(), pdal::MetadataNode::type(), and pdal::MetadataNode::value().
pdal::TEST (pipelineBaseTest , no_input)
Definition at line 92 of file pcpipelineTestJSON.cpp.
References appName(), and pdal::Utils::run_shell_command().
pdal::TEST (PluginManagerTest , NoPluginsNoNames)
Definition at line 92 of file PluginManagerTest.cpp.
References pdal::PluginManager::names(), PF_PluginType_Filter, PF_PluginType_Reader, and PF_PluginType_Writer.
pdal::TEST (PolygonTest , test_wkt_out)
Definition at line 93 of file PolygonTest.cpp.
References getWKT(), and pdal::Geometry::wkt().
pdal::TEST (TransformationMatrix , TooShort)
Definition at line 97 of file TransformationFilterTest.cpp.
References transformationMatrixFromString().
pdal::TEST (PluginManagerTest , InitPlugin)
Definition at line 99 of file PluginManagerTest.cpp.
References pdal::PluginManager::initializePlugin(), pdal::DummyPlugin::initPlugin(), pdal::PluginManager::names(), and PF_PluginType_Filter.
pdal::TEST (TransformationMatrix , TooLong)
Definition at line 104 of file TransformationFilterTest.cpp.
References transformationMatrixFromString().
pdal::TEST (PolygonTest , test_json_out)
Definition at line 105 of file PolygonTest.cpp.
References getJSON(), and pdal::Geometry::json().
pdal::TEST (pipelineBaseTest , common_opts)
Definition at line 105 of file pcpipelineTestJSON.cpp.
References appName(), and pdal::Utils::run_shell_command().
pdal::TEST (CpdFilterTest , DefaultMethod)
Definition at line 106 of file CpdFilterTest.cpp.
References pdal::CpdFilter::defaultMethod().
Referenced by appName(), getBytes(), and TEST().
pdal::TEST (PointTable , userView)
Definition at line 108 of file PointTableTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), anonymous_namespace{ReprojectionFilterTest.cpp}::getPoint(), pdal::Dimension::id(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Reader::setReadCb(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
pdal::TEST (PluginManagerTest , MissingPlugin)
Definition at line 108 of file PluginManagerTest.cpp.
References pdal::PluginManager::createObject().
pdal::TEST (IcpFilterTest , RecoverTranslation)
Definition at line 109 of file IcpFilterTest.cpp.
References pdal::Options::add(), pdal::anonymous_namespace{IcpFilterTest.cpp}::checkPointsEqualReader(), hag::filter(), pdal::MetadataNode::findChild(), pdal::anonymous_namespace{IcpFilterTest.cpp}::newFilter(), pdal::anonymous_namespace{IcpFilterTest.cpp}::newReader(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::MetadataNode::value().
pdal::TEST (OptionsTest , valid)
Definition at line 110 of file OptionsTest.cpp.
References pdal::Option::nameValid().
pdal::TEST (CpdFilterTest , DefaultIdentity)
Definition at line 111 of file CpdFilterTest.cpp.
References pdal::CpdFilter::defaultMethod(), hag::filter(), pdal::MetadataNode::findChild(), pdal::anonymous_namespace{CpdFilterTest.cpp}::newFilter(), pdal::anonymous_namespace{CpdFilterTest.cpp}::newReader(), pdal::Dimension::size(), and pdal::MetadataNode::value().
pdal::TEST (PlyReader , ReadBinary)
Definition at line 113 of file PlyReaderTest.cpp.
References pdal::Options::add(), checkPoint(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
pdal::TEST (PolygonTest , smooth)
Definition at line 113 of file PolygonTest.cpp.
References pdal::Polygon::area(), getJSON(), and pdal::Polygon::simplify().
pdal::TEST (PluginManagerTest , CreateObject)
Definition at line 114 of file PluginManagerTest.cpp.
References pdal::PluginManager::createObject().
pdal::TEST (pipelineBaseTest , progress)
Definition at line 115 of file pcpipelineTestJSON.cpp.
References appName(), pdal::FileUtils::closeFile(), Support::configuredpath(), pdal::FileUtils::createFile(), pdal::FileUtils::deleteFile(), pdal::FileUtils::readFileIntoString(), pdal::Utils::run_shell_command(), and Support::temppath().
pdal::TEST (OptionsTest , programargs)
Definition at line 119 of file OptionsTest.cpp.
References pdal::Options::add(), pdal::ProgramArgs::add(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::reset(), and pdal::Options::toCommandLine().
pdal::TEST (PluginManagerTest , SearchPaths)
Definition at line 120 of file PluginManagerTest.cpp.
References pdal::Utils::contains(), pdal::Utils::getenv(), PDAL_PLUGIN_INSTALL_PATH, pdal::Utils::setenv(), pdal::PluginManager::test_pluginSearchPaths(), and pdal::Utils::unsetenv().
pdal::TEST (PolygonTest , covers)
Definition at line 121 of file PolygonTest.cpp.
References pdal::Polygon::covers(), getWKT(), pdal::BasePointTable::layout(), pdal::PointLayout::registerDim(), pdal::Dimension::X, and pdal::Dimension::Y.
pdal::TEST (PlyReader , ReadBinaryStream)
Definition at line 133 of file PlyReaderTest.cpp.
References pdal::Options::add(), c, Support::datapath(), pdal::PointRef::getFieldAs(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST (CpdFilterTest , RecoverTranslation)
Definition at line 134 of file CpdFilterTest.cpp.
References pdal::Options::add(), pdal::anonymous_namespace{CpdFilterTest.cpp}::checkPointsEqualReader(), hag::filter(), pdal::MetadataNode::findChild(), pdal::anonymous_namespace{CpdFilterTest.cpp}::newFilter(), pdal::anonymous_namespace{CpdFilterTest.cpp}::newReader(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::MetadataNode::value().
pdal::TEST (IcpFilterTest , TooFewInputs)
Definition at line 137 of file IcpFilterTest.cpp.
References hag::filter(), pdal::anonymous_namespace{IcpFilterTest.cpp}::newFilter(), and pdal::anonymous_namespace{IcpFilterTest.cpp}::newReader().
pdal::TEST (json , pipeline_stdin)
Definition at line 141 of file pcpipelineTestJSON.cpp.
References pdal::Dimension::base(), INSTANTIATE_TEST_CASE_P(), and anonymous_namespace{pcpipelineTestJSON.cpp}::run_pipeline_stdin().
pdal::TEST (PolygonTest , valid)
Definition at line 145 of file PolygonTest.cpp.
References getWKT(), and pdal::Geometry::valid().
pdal::TEST (IcpFilterTest , ThreeInputs)
Definition at line 148 of file IcpFilterTest.cpp.
References hag::filter(), pdal::anonymous_namespace{IcpFilterTest.cpp}::newFilter(), and pdal::anonymous_namespace{IcpFilterTest.cpp}::newReader().
pdal::TEST (PolygonTest , bounds)
Definition at line 151 of file PolygonTest.cpp.
References b, pdal::Geometry::bounds(), getWKT(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
pdal::TEST (OptionsTest , nan)
Definition at line 157 of file OptionsTest.cpp.
References pdal::Options::add(), pdal::ProgramArgs::add(), pdal::ProgramArgs::parse(), and pdal::Options::toCommandLine().
pdal::TEST (CpdFilterTest , TooFewInputs)
Definition at line 162 of file CpdFilterTest.cpp.
References hag::filter(), pdal::anonymous_namespace{CpdFilterTest.cpp}::newFilter(), and pdal::anonymous_namespace{CpdFilterTest.cpp}::newReader().
pdal::TEST (PolygonTest , bounds2d)
Definition at line 163 of file PolygonTest.cpp.
References b, pdal::Geometry::bounds(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
pdal::TEST (CpdFilterTest , TooManyInputs)
Definition at line 173 of file CpdFilterTest.cpp.
References hag::filter(), pdal::anonymous_namespace{CpdFilterTest.cpp}::newFilter(), and pdal::anonymous_namespace{CpdFilterTest.cpp}::newReader().
pdal::TEST (PolygonTest , bounds3d)
Definition at line 177 of file PolygonTest.cpp.
References b, pdal::Geometry::bounds(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
pdal::TEST (PointTable , srs)
Definition at line 182 of file PointTableTest.cpp.
References pdal::BasePointTable::addSpatialReference(), pdal::BasePointTable::anySpatialReference(), pdal::BasePointTable::m_spatialRefs, and pdal::BasePointTable::spatialReferenceUnique().
pdal::TEST (CpdFilterTest , RigidNoThrow)
Definition at line 188 of file CpdFilterTest.cpp.
References pdal::anonymous_namespace{CpdFilterTest.cpp}::checkNoThrow().
pdal::TEST (PlyReader , NoVertex)
Definition at line 191 of file PlyReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
pdal::TEST (PolygonTest , streams)
Definition at line 192 of file PolygonTest.cpp.
References getWKT().
pdal::TEST (CpdFilterTest , AffineNoThrow)
Definition at line 193 of file CpdFilterTest.cpp.
References pdal::anonymous_namespace{CpdFilterTest.cpp}::checkNoThrow().
pdal::TEST (CpdFilterTest , NonrigidNoThrow)
Definition at line 198 of file CpdFilterTest.cpp.
References pdal::anonymous_namespace{CpdFilterTest.cpp}::checkNoThrow().
pdal::TEST (json , tags)
Definition at line 257 of file pcpipelineTestJSON.cpp.
References Support::configuredpath(), pdal::PipelineManager::m_stages, and pdal::PipelineManager::readPipeline().
pdal::TEST (json , issue1417)
Definition at line 278 of file pcpipelineTestJSON.cpp.
References Support::datapath(), and run_pipeline().
pdal::TEST (json , stagetags)
Definition at line 286 of file pcpipelineTestJSON.cpp.
References pdal::Options::add(), appName(), pdal::Dimension::base(), Support::configuredpath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Utils::run_shell_command(), pdal::Stage::setOptions(), Support::temppath(), and pdal::Dimension::Z.
pdal::TEST_F (MatlabWriterTest , constructor)
Definition at line 64 of file MatlabWriterTest.cpp.
pdal::TEST_F (MatlabWriterTest , findStage)
Definition at line 70 of file MatlabWriterTest.cpp.
References pdal::StageFactory::createStage().
pdal::TEST_F (MatlabWriterTest , write)
Definition at line 78 of file MatlabWriterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::MatlabWriterTest::m_reader, pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
pdal::TEST_F (TerrasolidReaderTest , Header)
Definition at line 81 of file TerrasolidReaderTest.cpp.
References pdal::TerraSolidHeader::Color, pdal::TerraSolidHeader::HdrSize, pdal::TerraSolidHeader::HdrVersion, pdal::TerraSolidHeader::OrgX, pdal::TerraSolidHeader::OrgY, pdal::TerraSolidHeader::OrgZ, pdal::TerraSolidHeader::PntCnt, pdal::TerraSolidHeader::RecogStr, pdal::TerraSolidHeader::RecogVal, pdal::TerraSolidHeader::Time, and pdal::TerraSolidHeader::Units.
pdal::TEST_F (OptechReaderTest , Header)
Definition at line 81 of file OptechReaderTest.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::CsdHeader::formatVersion, pdal::CsdHeader::gpsWeek, pdal::CsdHeader::headerSize, pdal::CsdHeader::imuOffsets, pdal::CsdHeader::maxTime, pdal::CsdHeader::minTime, pdal::CsdHeader::misalignmentAngles, pdal::CsdHeader::numRecords, pdal::CsdHeader::numStrips, pdal::CsdHeader::pressure, pdal::CsdHeader::signature, pdal::CsdHeader::softwareVersion, pdal::CsdHeader::stripPointers, pdal::CsdHeader::temperature, and pdal::CsdHeader::vendorId.
pdal::TEST_F (MatlabWriterTest , outputDims)
Definition at line 92 of file MatlabWriterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::MatlabWriterTest::m_reader, pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
pdal::TEST_F (TerrasolidReaderTest , ReadingPoints)
Definition at line 101 of file TerrasolidReaderTest.cpp.
References pdal::Dimension::Alpha, pdal::Dimension::Blue, pdal::Dimension::Classification, pdal::Dimension::Flag, pdal::Dimension::Green, pdal::Dimension::Intensity, pdal::Dimension::Mark, pdal::Dimension::NumberOfReturns, pdal::Dimension::OffsetTime, pdal::Dimension::PointSourceId, pdal::Dimension::Red, pdal::Dimension::ReturnNumber, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST_F (OptechReaderTest , ReadingPoints)
Definition at line 109 of file OptechReaderTest.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::e2, pdal::Dimension::EchoRange, pdal::Dimension::GpsTime, pdal::Dimension::Intensity, pdal::Dimension::NumberOfReturns, pdal::Dimension::ReturnNumber, pdal::Dimension::ScanAngleRank, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST_F (TransformationFilterTest , NoChange)
Definition at line 111 of file TransformationFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::TransformationFilterTest::m_filter, pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST_F (TransformationFilterTest , Translation)
Definition at line 133 of file TransformationFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::TransformationFilterTest::m_filter, pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST_F (OptechReaderTest , Spatialreference)
Definition at line 136 of file OptechReaderTest.cpp.
pdal::TEST_F (TransformationFilterTest , Rotation)
Definition at line 153 of file TransformationFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::TransformationFilterTest::m_filter, pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
pdal::TEST_P (json , pipeline)
Definition at line 136 of file pcpipelineTestJSON.cpp.
References run_pipeline().
pdal::TEST_P (jsonWithNITF , pipeline)
Definition at line 182 of file pcpipelineTestJSON.cpp.
References pdal::StageFactory::createStage(), endif(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, INSTANTIATE_TEST_CASE_P(), and run_pipeline().
pdal::TEST_P (jsonWithP2G , pipeline)
Definition at line 207 of file pcpipelineTestJSON.cpp.
References pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, INSTANTIATE_TEST_CASE_P(), and run_pipeline().
pdal::TEST_P (jsonWithHexer , pipeline)
Definition at line 224 of file pcpipelineTestJSON.cpp.
References pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, INSTANTIATE_TEST_CASE_P(), and run_pipeline().
pdal::TEST_P (jsonWithLAZ , pipeline)
Definition at line 242 of file pcpipelineTestJSON.cpp.
References INSTANTIATE_TEST_CASE_P(), and run_pipeline().
TransformationMatrix PDAL_DLL pdal::transformationMatrixFromString (const std::string & s)
Definition at line 54 of file TransformationFilter.cpp.
Referenced by pdal::TransformationFilter::initialize(), and TEST().
PDAL_DLL std::string pdal::transformWkt (std::string wkt, const SpatialReference & from, const SpatialReference & to)
Definition at line 692 of file GDALUtils.cpp.
References pdal::SpatialReference::empty(), and pdal::SpatialReference::getWKT().
Variable Documentation
string pdal.__version__ = '1.6.0' private
Definition at line 1 of file __init__.py.
const OW_CellDepth pdal::ahOW_CellDepth[] static
Initial value:
=
{
    {"8BIT_U",          GDT_Byte},
    {"16BIT_U",         GDT_UInt16},
    {"16BIT_S",         GDT_Int16},
    {"32BIT_U",         GDT_UInt32},
    {"32BIT_S",         GDT_Int32},
    {"32BIT_REAL",      GDT_Float32},
    {"64BIT_REAL",      GDT_Float64},
    {"32BIT_COMPLEX",   GDT_CFloat32},
    {"64BIT_COMPLEX",   GDT_CFloat64},
    {"1BIT",            GDT_Byte},
    {"2BIT",            GDT_Byte},
    {"4BIT",            GDT_Byte}
}
Definition at line 39 of file OciWrapper.cpp.
Referenced by OWGetDataType(), and OWSetDataType().
class PDAL_DLL pdal::BOX3D
Definition at line 42 of file SpatialReference.hpp.
Referenced by pdal::FauxReader::addArgs(), pdal::lasdump::operator>>(), operator>>(), pdal::NitfWriter::reprojectBoxToDD(), pdal::Bounds::set(), TEST(), testGrid(), and pdal::Bounds::to3d().
class PDAL_DLL pdal::ChipperFilter
Definition at line 58 of file ChipperFilter.hpp.
const bool pdal::DEFAULT_IS_RDTP = false
Definition at line 56 of file RxpReader.hpp.
Referenced by pdal::RxpReader::addArgs().
const float pdal::DEFAULT_MAX_REFLECTANCE = 5.0
Definition at line 60 of file RxpReader.hpp.
Referenced by pdal::RxpReader::addArgs().
const float pdal::DEFAULT_MIN_REFLECTANCE = -25.0
Definition at line 59 of file RxpReader.hpp.
Referenced by pdal::RxpReader::addArgs().
const bool pdal::DEFAULT_MINIMAL = false
Definition at line 57 of file RxpReader.hpp.
const bool pdal::DEFAULT_REFLECTANCE_AS_INTENSITY = true
Definition at line 58 of file RxpReader.hpp.
Referenced by pdal::RxpReader::addArgs().
const bool pdal::DEFAULT_SYNC_TO_PPS = true
Definition at line 55 of file RxpReader.hpp.
Referenced by pdal::RxpReader::addArgs().
const uint16_t pdal::EXTRA_BYTES_RECORD_ID = 4 static
Definition at line 53 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addExtraBytesVlr(), and pdal::LasReader::readExtraBytesVlr().
const uint16_t pdal::GEOTIFF_ASCII_RECORD_ID = 34737 static
Definition at line 51 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addGeotiffVlrs(), pdal::LasWriter::addSpatialRefVlrs(), pdal::GeotiffSrs::GeotiffSrs(), pdal::GeotiffTags::GeotiffTags(), and pdal::LasHeader::setSrsFromGeotiff().
const uint16_t pdal::GEOTIFF_DIRECTORY_RECORD_ID = 34735 static
Definition at line 49 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addGeotiffVlrs(), pdal::LasWriter::addSpatialRefVlrs(), pdal::GeotiffSrs::GeotiffSrs(), pdal::GeotiffTags::GeotiffTags(), pdal::LasHeader::setSrs(), and pdal::LasHeader::setSrsFromGeotiff().
const uint16_t pdal::GEOTIFF_DOUBLES_RECORD_ID = 34736 static
Definition at line 50 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addGeotiffVlrs(), pdal::LasWriter::addSpatialRefVlrs(), pdal::GeotiffSrs::GeotiffSrs(), pdal::GeotiffTags::GeotiffTags(), and pdal::LasHeader::setSrsFromGeotiff().
const uint16_t pdal::LASZIP_RECORD_ID = 22204 static
Definition at line 52 of file LasVLR.hpp.
Referenced by pdal::LasReader::ready(), pdal::LasWriter::readyCompression(), pdal::LasWriter::readyLasZipCompression(), and pdal::LasWriter::readyLazPerfCompression().
const char pdal::LASZIP_USER_ID[] = "laszip encoded" static
Definition at line 60 of file LasVLR.hpp.
Referenced by pdal::LasReader::extractVlrMetadata(), pdal::LasReader::ready(), pdal::LasWriter::readyCompression(), pdal::LasWriter::readyLasZipCompression(), and pdal::LasWriter::readyLazPerfCompression().
const char pdal::LIBLAS_USER_ID[] = "liblas" static
Definition at line 59 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addSpatialRefVlrs(), pdal::LasWriter::addWktVlr(), pdal::LasReader::extractVlrMetadata(), and pdal::LasHeader::setSrsFromWkt().
class PDAL_DLL pdal::MetadataNode
Definition at line 43 of file SpatialReference.hpp.
Referenced by pdal::MetadataNode::add(), pdal::MetadataNode::addEncoded(), pdal::MetadataNode::addList(), pdal::MetadataNode::addListEncoded(), pdal::MetadataNode::addOrUpdate(), pdal::MetadataNode::addWithType(), pdal::MetadataNode::find(), pdal::MetadataNode::findChild(), pdal::XMLSchema::load(), and TEST().
const uint16_t pdal::PDAL_METADATA_RECORD_ID = 12 static
Definition at line 54 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addMetadataVlr().
const uint16_t pdal::PDAL_PIPELINE_RECORD_ID = 13 static
Definition at line 55 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addPipelineVlr().
const char pdal::PDAL_USER_ID[] = "PDAL" static
Definition at line 61 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addMetadataVlr(), and pdal::LasWriter::addPipelineVlr().
std::vector<std::string> pdal::ramps static
Initial value:
= {"awesome_green", "black_orange",
    "blue_hue", "blue_red", "heat_map", "pestel_shades", "blue_orange"}
Definition at line 55 of file ColorinterpFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.null",
    "Null writer.  Provides a sink for points in a pipeline.  "
        "It's the same as sending pipeline output to /dev/null.",
    "http://pdal.io/stages/writers.null.html" )
Definition at line 7 of file NullWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.myreader",
    "My Awesome Reader",
    "http://link/to/documentation" )
Definition at line 9 of file MyReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.mywriter",
    "My Awesome Writer",
    "http://path/to/documentation" )
Definition at line 10 of file MyWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.name", "My awesome filter",
               "http://link/to/documentation")
Definition at line 15 of file MyFilter.cpp.
Referenced by pdal::MyKernel::getName().
PluginInfo const pdal::s_info static
Initial value:
{
    "kernels.mykernel",
    "MyKernel",
    "http://link/to/documentation"
  }
Definition at line 18 of file MyKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.divider",
    "Divide points into approximately equal sized groups based on a simple "
      "scheme",
    "http://pdal.io/stages/filters.divider.html" )
Definition at line 40 of file DividerFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.randomize",
    "Randomize points in a view.",
    "http://pdal.io/stages/filters.randomize.html" )
Definition at line 40 of file RandomizeFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.head", "Return N points from beginning of the point cloud.",
    "http://pdal.io/stages/filters.head.html")
Definition at line 40 of file HeadFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.tail", "Return N points from end of the point cloud.",
    "http://pdal.io/stages/filters.tail.html")
Definition at line 40 of file TailFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.sort",
    "Sort data based on a given dimension.",
    "http://pdal.io/stages/filters.sort.html" )
Definition at line 41 of file SortFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.streamcallback",
    "Provide a hook for a simple point-by-point callback.",
    "" )
Definition at line 41 of file StreamCallbackFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.merge",
    "Merge data from two different readers into a single stream.",
    "http://pdal.io/stages/filters.merge.html" )
Definition at line 41 of file MergeFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.nitf",
    "NITF Reader",
    "http://pdal.io/stages/readers.nitf.html" )
Definition at line 42 of file NitfReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.tindex",
    "TileIndex Reader",
    "http://pdal.io/stages/readers.tindex.html" )
Definition at line 43 of file TIndexReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.delta", "Delta Kernel",
    "http://www.pdal.io/apps/delta.html")
Definition at line 43 of file DeltaKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.groupby", "Split data categorically by dimension.",
               "http://pdal.io/stages/filters.groupby.html")
Definition at line 43 of file GroupByFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.random", "Random Kernel",
    "http://pdal.io/apps/random.html" )
Definition at line 43 of file RandomKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.sort", "Sort Kernel",
    "http://pdal.io/apps/sort.html" )
Definition at line 43 of file SortKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.sbet",
    "SBET Writer",
    "http://pdal.io/stages/writers.sbet.html" )
Definition at line 44 of file SbetWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.merge", "Merge Kernel",
    "http://pdal.io/apps/merge.html" )
Definition at line 44 of file MergeKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.split", "Split Kernel",
    "http://pdal.io/apps/split.html" )
Definition at line 44 of file SplitKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.computerange", "Compute Range Filter",
               "http://pdal.io/stages/filters.computerange.html")
Definition at line 44 of file ComputeRangeFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.locate",
               "Return a single point with min/max value in the named dimension.",
               "http://pdal.io/stages/filters.locate.html")
Definition at line 44 of file LocateFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.decimation",
    "Rank decimation filter. Keep every Nth point",
    "http://pdal.io/stages/filters.decimation.html" )
Definition at line 44 of file DecimationFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.pcl", "PCL Kernel",
    "http://pdal.io/apps/pcl.html" )
Definition at line 44 of file PCLKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.cluster", "Label clusters",
               "http://pdal.io/stages/filters.cluster.html")
Definition at line 45 of file ClusterFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.pts",
    "Pts Reader",
    "http://pdal.io/stages/readers.pts.html" )
Definition at line 45 of file PtsReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.ferry",
    "Copy data from one dimension to another.",
    "http://pdal.io/stages/filters.ferry.html" )
Definition at line 45 of file FerryFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.sbet",
    "SBET Reader",
    "http://pdal.io/stages/readers.sbet.html" )
Definition at line 45 of file SbetReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.transformation",
    "Transform each point using a 4x4 transformation matrix",
    "http://pdal.io/stages/filters.transformation.html" )
Definition at line 45 of file TransformationFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.iqr", "Interquartile Range Filter",
               "http://pdal.io/stages/filters.iqr.html")
Definition at line 45 of file IQRFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.matlab",
    "Matlab .mat file writer.",
    "http://pdal.io/stages/writers.matlab.html")
Definition at line 45 of file MatlabWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
        "writers.gdal",
        "Write a point cloud as a GDAL raster.",
        "http://pdal.io/stages/writers.gdal.html")
Definition at line 45 of file GDALWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.mad", "Median Absolute Deviation Filter",
               "http://pdal.io/stages/filters.mad.html")
Definition at line 45 of file MADFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.icp", "Iterative Closest Point (ICP) filter",
               "http://pdal.io/stages/filters.icp.html")
Definition at line 45 of file IcpFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.mortonorder",
    "Morton or z-order sorting of points. See "
        "http://en.wikipedia.org/wiki/Z-order_curve for more detail.",
    "http://pdal.io/stages/filters.mortonorder.html" )
Definition at line 46 of file MortonOrderFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.sqlite",
    "Read data from SQLite3 database files.",
    "" )
Definition at line 46 of file SQLiteReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.radialdensity", "RadialDensity Filter",
               "http://pdal.io/stages/filters.radialdensity.html")
Definition at line 46 of file RadialDensityFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.terrasolid",
    "TerraSolid Reader",
    "http://pdal.io/stages/readers.terrasolid.html" )
Definition at line 46 of file TerrasolidReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.text",
    "Text Reader",
    "http://pdal.io/stages/readers.text.html" )
Definition at line 46 of file TextReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.matlab",
    "Matlab Reader",
    "http://pdal.io/stages/readers.matlab.html" )
Definition at line 46 of file MatlabReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.hag", "HAG Filter",
               "http://pdal.io/stages/filters.hag.html")
Definition at line 46 of file HAGFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.mrsid",
    "MrSID Reader",
    "http://www.pdal.io/stages/readers.mrsid.html" )
Definition at line 46 of file MrsidReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.ilvis2",
    "ILVIS2 Reader",
    "http://pdal.io/stages/readers.ilvis2.html" )
Definition at line 46 of file Ilvis2Reader.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.kdistance", "K-Distance Filter",
               "http://pdal.io/stages/filters.kdistance.html")
Definition at line 46 of file KDistanceFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.assign",
    "Assign values for a dimension using a specified value.",
    "http://pdal.io/stages/filters.assign.html" )
Definition at line 46 of file AssignFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
        "readers.gdal",
        "Read GDAL rasters as point clouds.",
        "http://pdal.io/stages/reader.gdal.html")
Definition at line 46 of file GDALReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.lof", "LOF Filter",
               "http://pdal.io/stages/filters.lof.html")
Definition at line 46 of file LOFFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "kernels.smooth",
    "Smooth Kernel",
    "http://pdal.io/kernels/kernels.smooth.html" )
Definition at line 46 of file SmoothKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.python",
    "Manipulate data using inline Python",
    "http://pdal.io/stages/filters.python.html" )
Definition at line 47 of file PythonFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
        "readers.ply",
        "Read ply files.",
        "http://pdal.io/stages/reader.ply.html")
Definition at line 47 of file PlyReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
        "writers.ply",
        "ply writer",
        "http://pdal.io/stages/writers.ply.html"
        )
Definition at line 47 of file PlyWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.overlay",
    "Assign values to a dimension based on the extent of an OGR-readable data "
    " source or an OGR SQL query.",
    "http://pdal.io/stages/filters.overlay.html" )
Definition at line 47 of file OverlayFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.faux",
    "Faux Reader",
    "http://pdal.io/stages/readers.faux.html" )
Definition at line 47 of file FauxReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.splitter",
    "Split data based on a X/Y box length.",
    "http://pdal.io/stages/filters.splitter.html" )
Definition at line 47 of file SplitterFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.pipeline",
    "Pipeline Kernel", "http://pdal.io/apps/pipeline.html" )
Definition at line 47 of file PipelineKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.density", "Density Kernel",
    "http://www.pdal.io/apps/density.html" )
Definition at line 47 of file DensityKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.greyhound",
    "Greyhound Reader",
    "http://pdal.io/stages/readers.greyhound.html")
Definition at line 47 of file GreyhoundReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.hexbin",
    "Tessellate the point's X/Y domain and determine point density and/or point boundary.",
    "http://pdal.io/stages/filters.hexbin.html" )
Definition at line 47 of file HexBin.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.mbio",
    "MBSystem Reader",
    "http://www.pdal.io/stages/readers.mbio.html" )
Definition at line 47 of file MbReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.diff", "Diff Kernel",
    "http://www.pdal.io/apps/diff.html" )
Definition at line 47 of file DiffKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.pgpointcloud",
    "Read data from pgpointcloud format. \"query\" option needs to be a \n"
        "SQL statement selecting the data.",
    "http://pdal.io/stages/readers.pgpointcloud.html" )
Definition at line 47 of file PgReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.outlier", "Outlier removal",
               "http://pdal.io/stages/filters.outlier.html")
Definition at line 48 of file OutlierFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.estimaterank", "EstimateRank Filter",
               "http://pdal.io/stages/filters.estimaterank.html")
Definition at line 48 of file EstimateRankFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.oci",
    "Read point cloud data from Oracle SDO_POINTCLOUD.",
    "http://pdal.io/stages/readers.oci.html" )
Definition at line 48 of file OciReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.sample", "Subsampling filter",
               "http://pdal.io/stages/filters.sample.html")
Definition at line 48 of file SampleFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.hausdorff",
    "Hausdorff Kernel", "http://pdal.io/apps/hausdorff.html")
Definition at line 48 of file HausdorffKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.bpf",
    "\"Binary Point Format\" (BPF) reader support. BPF is a simple \n"
        "DoD and research format that is used by some sensor and \n"
        "processing chains.",
    "http://pdal.io/stages/readers.bpf.html" )
Definition at line 48 of file BpfReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.voxelcenternearestneighbor",
               "Voxel Center Nearest Neighbor Filter",
               "http://pdal.io/stages/filters.voxelcenternearestneighbor.html")
Definition at line 48 of file VoxelCenterNearestNeighborFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.colorization",
    "Fetch and assign RGB color information from a GDAL-readable datasource.",
    "http://pdal.io/stages/filters.colorization.html" )
Definition at line 49 of file ColorizationFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.text",
    "Text Writer",
    "http://pdal.io/stages/writers.text.html" )
Definition at line 49 of file TextWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.greedyprojection", "Greedy Triangulation filter",
                   "http://pdal.io/stages/filters.greedyprojection.html")
Definition at line 49 of file GreedyProjection.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.movingleastsquares", "Moving Least Squares filter",
               "http://pdal.io/stages/filters.movingleastsquares.html")
Definition at line 49 of file MovingLeastSquaresFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.pgpointcloud",
    "Write points to PostgreSQL pgpointcloud output",
    "http://pdal.io/stages/writers.pgpointcloud.html" )
Definition at line 49 of file PgWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.gridprojection", "Grid Projection filter",
               "http://pdal.io/stages/filters.gridprojection.html")
Definition at line 50 of file GridProjectionFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.pclblock", "PCL Block implementation",
               "http://pdal.io/stages/filters.pclblock.html")
Definition at line 50 of file PCLBlock.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.normal", "Normal Filter",
               "http://pdal.io/stages/filters.normal.html")
Definition at line 50 of file NormalFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.eigenvalues", "Eigenvalues Filter",
               "http://pdal.io/stages/filters.eigenvalues.html")
Definition at line 50 of file EigenvaluesFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.mongus", "Mongus and Zalik (2012)",
               "http://pdal.io/stages/filters.mongus.html")
Definition at line 50 of file MongusFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.elm", "Extended Local Minimum Filter",
               "http://pdal.io/stages/filters.elm.html")
Definition at line 50 of file ELMFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.optech",
    "Optech reader support.",
    "http://pdal.io/stages/readers.optech.html" )
Definition at line 50 of file OptechReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.approximatecoplanar", "ApproximateCoplanar Filter",
               "http://pdal.io/stages/filters.approximatecoplanar.html")
Definition at line 50 of file ApproximateCoplanarFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.reprojection",
    "Reproject data using GDAL from one coordinate system to another.",
    "http://pdal.io/stages/filters.reprojection.html" )
Definition at line 50 of file ReprojectionFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.voxelgrid", "Voxel grid filter",
               "http://pdal.io/stages/filters.voxelgrid.html")
Definition at line 50 of file VoxelGridFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.matlab",
    "Manipulate data using inline Matlab",
    "http://pdal.io/stages/filters.matlab.html" )
Definition at line 50 of file MatlabFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.rxp",
    "RXP Reader",
    "http://pdal.io/stages/readers.rxp.html" )
Definition at line 50 of file RxpReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.voxelcentroidnearestneighbor",
    "Voxel Centroid Nearest Neighbor Filter",
    "http://pdal.io/stages/filters.voxelcentroidnearestneighbor.html")
Definition at line 51 of file VoxelCentroidNearestNeighborFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.pcd",
    "Read data in the Point Cloud Library (PCL) format.",
    "http://pdal.io/stages/readers.pcd.html" )
Definition at line 51 of file PcdReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.info", "Info Kernel",
    "http://pdal.io/apps/info.html" )
Definition at line 52 of file InfoKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.bpf",
    "\"Binary Point Format\" (BPF) writer support. BPF is a simple \n"
        "DoD and research format that is used by some sensor and \n"
        "processing chains.",
    "http://pdal.io/stages/writers.bpf.html" )
Definition at line 52 of file BpfWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.crop",
    "Filter points inside or outside a bounding box or a polygon",
    "http://pdal.io/stages/filters.crop.html" )
Definition at line 52 of file CropFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.range", "Pass only points given a dimension/range.",
               "http://pdal.io/stages/filters.range.html")
Definition at line 52 of file RangeFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.ground", "Ground Kernel",
                                            "http://pdal.io/apps/ground.html")
Definition at line 52 of file GroundKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
        "writers.ogr",
        "Write a point cloud as a set of OGR points/multipoints",
        "http://pdal.io/stages/writers.ogr.html")
Definition at line 52 of file OGRWriterV1.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.stats",
    "Compute statistics about each dimension (mean, min, max, etc.)",
    "http://pdal.io/stages/filters.stats.html" )
Definition at line 52 of file StatsFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.oci",
    "Write data using SDO_PC objects to Oracle.",
    "http://pdal.io/stages/writers.oci.html" )
Definition at line 52 of file OciWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.pmf", "Progressive morphological filter",
               "http://pdal.io/stages/filters.pmf.html")
Definition at line 53 of file PMFFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.pcd",
    "Write data in the Point Cloud Library (PCL) format.",
    "http://pdal.io/stages/writers.pcd.html" )
Definition at line 55 of file PcdWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.sqlite",
    "Write data to SQLite3 database files.",
    "" )
Definition at line 55 of file SQLiteWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("kernels.translate",
               "The Translate kernel allows users to construct a pipeline "
               "consisting of a reader, a writer, and N filter stages. "
               "Any supported stage type can be specified from the command "
               "line, reducing the need to create custom kernels for every "
               "combination.",
               "http://pdal.io/apps/translate.html")
Definition at line 56 of file TranslateKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.las",
    "ASPRS LAS 1.0 - 1.4 writer. LASzip support is also \n"
        "available if enabled at compile-time. Note that LAZ \n"
        "does not provide LAS 1.4 support at this time.",
    "http://pdal.io/stages/writers.las.html" )
Definition at line 57 of file LasWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.colorinterp",
    "Assigns RGB colors based on a dimension and a ramp",
    "http://pdal.io/stages/filters.colorinterp.html" )
Definition at line 58 of file ColorinterpFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo("kernels.tindex", "TIndex Kernel",
    "http://pdal.io/apps/tindex.html" )
Definition at line 64 of file TIndexKernel.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.icebridge",
    "NASA HDF5-based IceBridge ATM reader. \n"
        "See http://nsidc.org/data/docs/daac/icebridge/ilatm1b/index.html \n"
        "for more information.",
    "http://pdal.io/stages/readers.icebridge.html" )
Definition at line 65 of file IcebridgeReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.cpd", "CPD filter", "http://pdal.io/stages/filters.cpd.html")
Definition at line 66 of file CpdFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.smrf", "Simple Morphological Filter (Pingel et al., 2013)",
    "http://pdal.io/stages/filters.smrf.html")
Definition at line 68 of file SMRFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "filters.chipper",
    "Organize points into spatially contiguous, squarish, and non-overlapping chips.",
    "http://pdal.io/stages/filters.chipper.html" )
Definition at line 71 of file ChipperFilter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.nitf",
    "NITF Writer",
    "http://pdal.io/stages/writers.nitf.html" )
Definition at line 71 of file NitfWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.las",
    "ASPRS LAS 1.0 - 1.4 read support. LASzip support is also \n"
        "enabled through this driver if LASzip was found during \n"
        "compilation.",
    "http://pdal.io/stages/readers.las.html" )
Definition at line 76 of file LasReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
"readers.osg",
"osg reader.",
"")
Definition at line 121 of file OSGReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.geowave",
    "\"GeoWave\"  reader support. ",
    "http://pdal.io/stages/drivers.geowave.reader.html" )
Definition at line 135 of file GeoWaveReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "writers.geowave",
    "Write data using GeoWave.",
    "http://pdal.io/stages/drivers.geowave.writer.html" )
Definition at line 142 of file GeoWaveWriter.cpp.
PluginInfo const pdal::s_info static
Initial value:
= PluginInfo(
    "readers.qfit",
    "QFIT Reader",
    "http://pdal.io/stages/readers.qfit.html" )
Definition at line 186 of file QfitReader.cpp.
PluginInfo const pdal::s_info static
Initial value:
=
    PluginInfo("filters.poisson", "Poisson Surface Reconstruction Filter",
               "http://pdal.io/stages/filters.poisson.html")
Definition at line 210 of file PoissonFilter.cpp.
const char pdal::SPEC_USER_ID[] = "LASF_Spec" static
Definition at line 58 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addExtraBytesVlr(), pdal::LasReader::extractVlrMetadata(), and pdal::LasReader::readExtraBytesVlr().
const char pdal::TRANSFORM_USER_ID[] = "LASF_Projection" static
Definition at line 57 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addGeotiffVlrs(), pdal::LasWriter::addSpatialRefVlrs(), pdal::LasWriter::addWktVlr(), pdal::LasReader::extractVlrMetadata(), pdal::LasHeader::setSrs(), pdal::LasHeader::setSrsFromGeotiff(), and pdal::LasHeader::setSrsFromWkt().
const int pdal::WKT_RECORD_ID = 2112 static
Definition at line 48 of file LasVLR.hpp.
Referenced by pdal::LasWriter::addSpatialRefVlrs(), pdal::LasWriter::addWktVlr(), pdal::LasHeader::setSrs(), and pdal::LasHeader::setSrsFromWkt().