PDAL: pdal::Dimension Namespace Reference
pdal::Dimension Namespace Reference
Classes
class Detail
Typedefs
typedef std::vector< Id > IdList
typedef std::vector< Detail > DetailList
Enumerations
enum Id {
Id::Unknown, Id::X, Id::Y, Id::Z,
Id::Intensity, Id::Amplitude, Id::Reflectance, Id::ReturnNumber,
Id::NumberOfReturns, Id::ScanDirectionFlag, Id::EdgeOfFlightLine, Id::Classification,
Id::ScanAngleRank, Id::UserData, Id::PointSourceId, Id::Red,
Id::Green, Id::Blue, Id::GpsTime, Id::InternalTime,
Id::OffsetTime, Id::IsPpsLocked, Id::StartPulse, Id::ReflectedPulse,
Id::Pdop, Id::Pitch, Id::Roll, Id::PulseWidth,
Id::Deviation, Id::PassiveSignal, Id::BackgroundRadiation, Id::PassiveX,
Id::PassiveY, Id::PassiveZ, Id::XVelocity, Id::YVelocity,
Id::ZVelocity, Id::Azimuth, Id::WanderAngle, Id::XBodyAccel,
Id::YBodyAccel, Id::ZBodyAccel, Id::XBodyAngRate, Id::YBodyAngRate,
Id::ZBodyAngRate, Id::Flag, Id::Mark, Id::Alpha,
Id::EchoRange, Id::ScanChannel, Id::Infrared, Id::HeightAboveGround,
Id::ClassFlags, Id::LvisLfid, Id::ShotNumber, Id::LongitudeCentroid,
Id::LatitudeCentroid, Id::ElevationCentroid, Id::LongitudeLow, Id::LatitudeLow,
Id::ElevationLow, Id::LongitudeHigh, Id::LatitudeHigh, Id::ElevationHigh,
Id::PointId, Id::OriginId, Id::NormalX, Id::NormalY,
Id::NormalZ, Id::Curvature, Id::Density
}
enum BaseType { BaseType::None = 0x000, BaseType::Signed = 0x100, BaseType::Unsigned = 0x200, BaseType::Floating = 0x400 }
enum Type {
Type::None = 0, Type::Unsigned8 = unsigned(BaseType::Unsigned) | 1, Type::Signed8 = unsigned(BaseType::Signed) | 1, Type::Unsigned16 = unsigned(BaseType::Unsigned) | 2,
Type::Signed16 = unsigned(BaseType::Signed) | 2, Type::Unsigned32 = unsigned(BaseType::Unsigned) | 4, Type::Signed32 = unsigned(BaseType::Signed) | 4, Type::Unsigned64 = unsigned(BaseType::Unsigned) | 8,
Type::Signed64 = unsigned(BaseType::Signed) | 8, Type::Float = unsigned(BaseType::Floating) | 4, Type::Double = unsigned(BaseType::Floating) | 8
}
Functions
std::string description (Id id)
Id id (std::string s)
std::string name (Id id)
Type defaultType (Id id)
BaseType fromName (std::string name)
std::string toName (BaseType b)
std::size_t size (Type t)
BaseType base (Type t)
std::string interpretationName (Type dimtype)
Type type (std::string s)
std::size_t extractName (const std::string &s, std::string::size_type p)
std::istream & operator>> (std::istream &in, Dimension::Type &type)
std::ostream & operator<< (std::ostream &out, const Dimension::Type &type)
Variables
static const int COUNT = std::numeric_limits<uint16_t>::max()
static const int PROPRIETARY = 0xF000
Typedef Documentation
typedef std::vector<Detail> pdal::Dimension::DetailList
Definition at line 79 of file DimDetail.hpp.
typedef std::vector<Id> pdal::Dimension::IdList
Definition at line 92 of file Dimension.hpp.
Enumeration Type Documentation
enum pdal::Dimension::BaseType strong
Enumerator
None
Signed
Unsigned
Floating
Definition at line 47 of file DimUtil.hpp.
enum pdal::Dimension::Id strong
Enumerator
Unknown
X
Y
Z
Intensity
Amplitude
Reflectance
ReturnNumber
NumberOfReturns
ScanDirectionFlag
EdgeOfFlightLine
Classification
ScanAngleRank
UserData
PointSourceId
Red
Green
Blue
GpsTime
InternalTime
OffsetTime
IsPpsLocked
StartPulse
ReflectedPulse
Pdop
Pitch
Roll
PulseWidth
Deviation
PassiveSignal
BackgroundRadiation
PassiveX
PassiveY
PassiveZ
XVelocity
YVelocity
ZVelocity
Azimuth
WanderAngle
XBodyAccel
YBodyAccel
ZBodyAccel
XBodyAngRate
YBodyAngRate
ZBodyAngRate
Flag
Mark
Alpha
EchoRange
ScanChannel
Infrared
HeightAboveGround
ClassFlags
LvisLfid
ShotNumber
LongitudeCentroid
LatitudeCentroid
ElevationCentroid
LongitudeLow
LatitudeLow
ElevationLow
LongitudeHigh
LatitudeHigh
ElevationHigh
PointId
OriginId
NormalX
NormalY
NormalZ
Curvature
Density
Definition at line 18 of file Dimension.hpp.
enum pdal::Dimension::Type strong
Enumerator
None
Unsigned8
Signed8
Unsigned16
Signed16
Unsigned32
Signed32
Unsigned64
Signed64
Float
Double
Definition at line 81 of file DimUtil.hpp.
Function Documentation
BaseType pdal::Dimension::base (Type t)
Definition at line 101 of file DimUtil.hpp.
References pdal::Utils::toNative().
Referenced by pdal::Dimension::Detail::base(), pdal::python::Array::buildNumpyDescription(), pdal::plang::Invocation::extractResult(), pdal::GreyhoundReader::prepared(), pdal::PointLayout::resolveType(), TEST(), pdal::TEST(), and pdal::PointLayout::toMetadata().
Type pdal::Dimension::defaultType (Id id)
Get the default storage type of a predefined dimension.
Parameters
id ID of the predefined dimension.
Returns
The dimension's default storage type. An exception is thrown if the id doesn't represent a predefined dimension.
Definition at line 616 of file Dimension.hpp.
References Alpha, Amplitude, Azimuth, BackgroundRadiation, Blue, ClassFlags, Classification, Curvature, Density, Deviation, Double, EchoRange, EdgeOfFlightLine, ElevationCentroid, ElevationHigh, ElevationLow, Flag, Float, GpsTime, Green, HeightAboveGround, Infrared, Intensity, InternalTime, IsPpsLocked, LatitudeCentroid, LatitudeHigh, LatitudeLow, LongitudeCentroid, LongitudeHigh, LongitudeLow, LvisLfid, Mark, NormalX, NormalY, NormalZ, NumberOfReturns, OffsetTime, OriginId, PassiveSignal, PassiveX, PassiveY, PassiveZ, Pdop, Pitch, PointId, PointSourceId, PulseWidth, Red, Reflectance, ReflectedPulse, ReturnNumber, Roll, ScanAngleRank, ScanChannel, ScanDirectionFlag, ShotNumber, Signed32, StartPulse, Unknown, Unsigned16, Unsigned32, Unsigned64, Unsigned8, UserData, WanderAngle, X, XBodyAccel, XBodyAngRate, XVelocity, Y, YBodyAccel, YBodyAngRate, YVelocity, Z, ZBodyAccel, ZBodyAngRate, and ZVelocity.
Referenced by pdal::ColorizationFilter::addDimensions(), pdal::DiffKernel::checkPoints(), and pdal::PointLayout::registerDim().
std::string pdal::Dimension::description (Id id)
Get a description of a predefined dimension.
Parameters
[in] id Dimension ID.
Returns
Dimension description.
Definition at line 98 of file Dimension.hpp.
References Alpha, Amplitude, Azimuth, BackgroundRadiation, Blue, ClassFlags, Classification, Curvature, Density, Deviation, EchoRange, EdgeOfFlightLine, ElevationCentroid, ElevationHigh, ElevationLow, Flag, GpsTime, Green, HeightAboveGround, Infrared, Intensity, InternalTime, IsPpsLocked, LatitudeCentroid, LatitudeHigh, LatitudeLow, LongitudeCentroid, LongitudeHigh, LongitudeLow, LvisLfid, Mark, NormalX, NormalY, NormalZ, NumberOfReturns, OffsetTime, OriginId, PassiveSignal, PassiveX, PassiveY, PassiveZ, Pdop, Pitch, PointId, PointSourceId, PulseWidth, Red, Reflectance, ReflectedPulse, ReturnNumber, Roll, ScanAngleRank, ScanChannel, ScanDirectionFlag, ShotNumber, StartPulse, Unknown, UserData, WanderAngle, X, XBodyAccel, XBodyAngRate, XVelocity, Y, YBodyAccel, YBodyAngRate, YVelocity, Z, ZBodyAccel, ZBodyAngRate, and ZVelocity.
Referenced by pdal::ProgramArgs::add(), pdal::LasWriter::addExtraBytesVlr(), pdal::addForwardMetadata(), pdal::plang::addMetadata(), pdal::LasWriter::addUserVlrs(), pdal::DimBuilder::extractDim(), pdal::plang::fromMetadata(), pdal::XMLSchema::loadMetadata(), App::outputDrivers(), TEST(), TEST_F(), and pdal::XMLSchema::writeXml().
std::size_t pdal::Dimension::extractName (const std::string & s, std::string::size_type p)
Extract a dimension name of a string. Dimension names start with an alpha and continue with numbers or underscores.
Parameters
s String from which to extract dimension name.
p Position at which to start extracting.
Returns
Number of characters in the extracted name.
Definition at line 178 of file DimUtil.hpp.
References c, and pdal::Utils::extract().
Referenced by pdal::anonymous_namespace{ColorizationFilter.cpp}::parseDim(), pdal::DimRange::subParse(), and pdal::DimBuilder::validateDimension().
BaseType pdal::Dimension::fromName (std::string name)
Definition at line 55 of file DimUtil.hpp.
References Floating, None, Signed, and Unsigned.
Referenced by pdal::GreyhoundReader::addDimensions().
Id pdal::Dimension::id (std::string s)
Get a predefined dimension ID given a dimension name. Multiple names may map to the same dimension for convenience. Names are case-insensitive.
Parameters
[in] s Name of dimension.
Returns
Dimension ID associated with the name. Id::Unknown is returned if the name doesn't map to a predefined dimension.
Definition at line 278 of file Dimension.hpp.
References Alpha, Amplitude, Azimuth, BackgroundRadiation, Blue, ClassFlags, Classification, Curvature, Density, Deviation, EchoRange, EdgeOfFlightLine, ElevationCentroid, ElevationHigh, ElevationLow, Flag, GpsTime, Green, HeightAboveGround, Infrared, Intensity, InternalTime, IsPpsLocked, LatitudeCentroid, LatitudeHigh, LatitudeLow, LongitudeCentroid, LongitudeHigh, LongitudeLow, LvisLfid, Mark, NormalX, NormalY, NormalZ, NumberOfReturns, OffsetTime, OriginId, PassiveSignal, PassiveX, PassiveY, PassiveZ, Pdop, Pitch, PointId, PointSourceId, PulseWidth, Red, Reflectance, ReflectedPulse, ReturnNumber, Roll, ScanAngleRank, ScanChannel, ScanDirectionFlag, ShotNumber, StartPulse, pdal::Utils::toupper(), Unknown, UserData, WanderAngle, X, XBodyAccel, XBodyAngRate, XVelocity, Y, YBodyAccel, YBodyAngRate, YVelocity, Z, ZBodyAccel, ZBodyAngRate, and ZVelocity.
Referenced by pdal::GeoWaveReader::addDimensions(), pdal::PointView::appendPoint(), pdal::PointLayout::assignDim(), pdal::eigen::computeSpline(), convertDimTypeJavaArrayToVector(), pdal::SQLiteWriter::CreateCloud(), pdal::PlyWriter::done(), pdal::DeltaKernel::dump(), pdal::DeltaKernel::dumpDetail(), pdal::InfoKernel::dumpPoints(), pdal::AssignFilter::filter(), pdal::ELMFilter::filter(), pdal::FerryFilter::filter(), pdal::PointLayout::findDim(), pdal::PointView::getField(), pdal::PointView::getTemp(), pdal::KDIndex< DIM >::kdtree_get_pt(), pdal::BpfWriter::loadBpfDimensions(), pdal::TriangularMesh::operator[](), pdal::LasUtils::parseIgnoreVLRs(), pdal::GreyhoundReader::read(), pdal::MbReader::read(), pdal::PointLayout::registerOrAssignDim(), pdal::ReprojectionFilter::run(), pdal::SampleFilter::run(), pdal::VoxelCentroidNearestNeighborFilter::run(), pdal::VoxelCenterNearestNeighborFilter::run(), pdal::PlyReader::SimpleProperty::setDim(), pdal::XMLSchema::setId(), pdal::PointIdxRef::swap(), pdal::TEST(), and TEST().
std::string pdal::Dimension::interpretationName (Type dimtype)
Get a string reresentation of a datatype.
Parameters
[in] dimtype Dimension type.
Returns
String representation of dimension type.
Definition at line 112 of file DimUtil.hpp.
References Double, Float, None, Signed16, Signed32, Signed64, Signed8, Unsigned16, Unsigned32, Unsigned64, and Unsigned8.
Referenced by pdal::PointView::dump(), pdal::PointRef::getFieldAs(), pdal::PointView::getFieldAs(), pdal::PlyWriter::getType(), Java_io_pdal_PointLayout_dimTypes(), Java_io_pdal_PointLayout_findDimType(), operator<<(), pdal::LasWriter::prepared(), pdal::PointView::setField(), pdal::gdal::Raster::validateType(), and pdal::XMLSchema::writeXml().
std::string pdal::Dimension::name (Id id)
Get the name of a predefined dimension.
Parameters
[in] id Dimension ID
Returns
Dimension name.
Definition at line 462 of file Dimension.hpp.
References Alpha, Amplitude, Azimuth, BackgroundRadiation, Blue, ClassFlags, Classification, Curvature, Density, Deviation, EchoRange, EdgeOfFlightLine, ElevationCentroid, ElevationHigh, ElevationLow, Flag, GpsTime, Green, HeightAboveGround, Infrared, Intensity, InternalTime, IsPpsLocked, LatitudeCentroid, LatitudeHigh, LatitudeLow, LongitudeCentroid, LongitudeHigh, LongitudeLow, LvisLfid, Mark, NormalX, NormalY, NormalZ, NumberOfReturns, OffsetTime, OriginId, PassiveSignal, PassiveX, PassiveY, PassiveZ, Pdop, Pitch, PointId, PointSourceId, PulseWidth, Red, Reflectance, ReflectedPulse, ReturnNumber, Roll, ScanAngleRank, ScanChannel, ScanDirectionFlag, ShotNumber, StartPulse, Unknown, UserData, WanderAngle, X, XBodyAccel, XBodyAngRate, XVelocity, Y, YBodyAccel, YBodyAngRate, YVelocity, Z, ZBodyAccel, ZBodyAngRate, and ZVelocity.
Referenced by pdal::MetadataNodeImpl::add(), pdal::ProgramArgs::add(), pdal::GeoWaveReader::addDimensions(), pdal::GreyhoundReader::addDimensions(), pdal::MrsidReader::addDimensions(), pdal::TextReader::addDimensions(), pdal::MetadataNodeImpl::addList(), pdal::ProgramArgs::addLongArg(), pdal::plang::addMetadata(), pdal::ProgramArgs::addShortArg(), pcl::Pipeline< PointT >::applyFilter(), pdal::PointLayout::assignDim(), pdal::gdal::Band< T >::Band(), pdal::plang::Invocation::begin(), pdal::python::Array::buildNumpyDescription(), pdal::DiffKernel::checkPoints(), pdal::Utils::cksum(), pdal::PointView::clearTemps(), pdal::MetadataNode::clone(), pdal::OciWriter::createBlockIndex(), pdal::PgWriter::DeleteTable(), pdal::PointLayout::dimName(), pdal::PointView::dump(), pdal::ProgramArgs::dump(), pdal::plang::Invocation::end(), pdal::GDALGrid::error::error(), App::execute(), pdal::DeltaKernel::execute(), Support::exename(), pdal::DimBuilder::extractDim(), pdal::PlyReader::extractElement(), pdal::PipelineReaderJSON::extractOptions(), pdal::PlyReader::extractProperty(), pdal::LasReader::extractVlrMetadata(), pdal::LasWriter::fillForwardList(), pdal::LasWriter::fillPointBuf(), pdal::ColorinterpFilter::filter(), pdal::PointLayout::finalized(), App::findKernel(), pdal::Options::fromJsonFile(), pdal::plang::fromMetadata(), pdal::PointRef::getFieldAs(), pdal::PointView::getFieldAs(), pdal::Options::getKeys(), pdal::mlang::Script::getLogicalMask(), pdal::SpatialReference::getName(), if(), pdal::Ilvis2Reader::initialize(), Java_io_pdal_PointLayout_dimPackedOffset(), Java_io_pdal_PointLayout_dimTypes(), Java_io_pdal_PointLayout_findDimType(), pdal::MrsidReader::LayoutToPointInfo(), pdal::MetadataNodeImpl::MetadataNodeImpl(), pdal::FileUtils::openFile(), App::outputCommands(), App::outputDrivers(), App::outputHelp(), pdal::Option::parse(), pdal::anonymous_namespace{ColorizationFilter.cpp}::parseDim(), pdal::ProgramArgs::parseLongArg(), pdal::GreyhoundReader::prepared(), pdal::PlyWriter::prepared(), pdal::MongusFilter::processGround(), pdal::MyReader::read(), pdal::GeoWaveReader::read(), pdal::MrsidReader::read(), pdal::DbWriter::readField(), pdal::DbWriter::readPoint(), pdal::PointLayout::registerDim(), pdal::ProgramArgs::set(), pdal::PointView::setField(), pdal::mlang::Script::setMatlabStruct(), pdal::DimRange::subParse(), pdal::BasePointTable::supportsView(), TEST(), TEST_F(), pdal::anonymous_namespace{PDALUtils.cpp}::toJSON(), pdal::Utils::typeidName(), pdal::MetadataNode::value(), pdal::gdal::Raster::writeBand(), pdal::PlyWriter::writeHeader(), pdal::LasWriter::writeLasZipBuf(), and pdal::XMLSchema::writeXml().
std::ostream& pdal::Dimension::operator<< (std::ostream & out, const Dimension::Type & type)
Definition at line 200 of file DimUtil.hpp.
References interpretationName().
std::istream& pdal::Dimension::operator>> (std::istream & in, Dimension::Type & type)
Definition at line 189 of file DimUtil.hpp.
References None, and type().
std::size_t pdal::Dimension::size (Type t)
Definition at line 96 of file DimUtil.hpp.
References pdal::Utils::toNative().
Referenced by pdal::GreyhoundReader::addDimensions(), pdal::PointTable::addPoint(), pdal::PointView::append(), pdal::Utils::backtrace(), pdal::blob::blob(), pdal::DiffKernel::checkPoints(), pdal::ChipperFilter::ChipperFilter(), pdal::connect(), convertDimTypeJavaArrayToVector(), pdal::DbReader::dimOffset(), pdal::NitfWriter::doneFile(), pdal::InfoKernel::dumpPoints(), pdal::plang::Invocation::end(), pdal::GDALGrid::expand(), pdal::LasReader::extractHeaderMetadata(), pdal::plang::Invocation::extractResult(), pdal::GDALGrid::GDALGrid(), pdal::GeotiffTags::GeotiffTags(), pdal::Extractor::get(), pdal::IStream::get(), getBytes(), pdal::PointView::getField(), pdal::PointRef::getField(), pdal::PointView::getOrAddPoint(), pdal::PointRef::getPackedData(), pdal::PointView::getPackedPoint(), pdal::plang::getTraceback(), pdal::BpfWriter::initialize(), pdal::plang::Invocation::insertArgument(), pdal::MrsidReader::LayoutToPointInfo(), pdal::DbReader::loadSchema(), pdal::OciWriter::loadSQLData(), pdal::ChipperFilter::partition(), pdal::GreyhoundReader::prepared(), pdal::LasWriter::prepared(), pdal::MatlabReader::processOne(), pdal::RxpPointcloud::read(), pdal::PlyReader::ListProperty::read(), pdal::BpfPolarHeader::read(), pdal::OciReader::readDimMajor(), pdal::LasReader::readExtraBytesVlr(), pdal::DbWriter::readField(), pdal::BpfReader::readHeaderExtraData(), pdal::plang::readPythonString(), ReadXML(), pdal::DbWriter::ready(), pdal::LasWriter::readyLasZipCompression(), pdal::PointLayout::resolveType(), pdal::SbetReader::seek(), pdal::OciReader::seekDimMajor(), pdal::PointView::setField(), pdal::PointRef::setField(), pdal::NitfFileWriter::setFilename(), pdal::PointRef::setPackedData(), pdal::PointView::setPackedPoint(), pdal::Dimension::Detail::size(), pdal::TEST(), TEST(), testGrid(), pdal::Utils::trim(), pdal::anonymous_namespace{ProgramArgs.hpp}::ArgValList::unconsumedArgs(), pdal::nitfwrap::NitfWrap::unwrap(), pdal::DbReader::updateSchema(), pdal::OciReader::validateQuery(), pdal::OciWriter::writeDimMajor(), pdal::DbReader::writeField(), pdal::DbReader::writePoint(), pdal::OciWriter::writePointMajor(), pdal::BpfWriter::writePointMajor(), pdal::RxpPointcloud::writeSavedPoints(), pdal::SQLiteWriter::writeTile(), pdal::PgWriter::writeTile(), and pdal::XMLSchema::writeXml().
std::string pdal::Dimension::toName (BaseType b)
Definition at line 66 of file DimUtil.hpp.
References Floating, Signed, and Unsigned.
Referenced by pdal::GreyhoundReader::prepared(), and pdal::PointLayout::toMetadata().
Type pdal::Dimension::type (std::string s)
Get the type corresponding to a type name.
Parameters
s Name of type.
Returns
Corresponding type enumeration value.
Definition at line 146 of file DimUtil.hpp.
References Double, Float, None, Signed16, Signed32, Signed64, Signed8, pdal::Utils::tolower(), Unsigned16, Unsigned32, Unsigned64, and Unsigned8.
Referenced by pdal::GreyhoundReader::addDimensions(), pdal::BpfReader::addDimensions(), pdal::LasReader::addDimensions(), pdal::plang::addMetadata(), pdal::MetadataNode::addWithType(), pdal::LasHeader::basePointLen(), convertDimTypeJavaArrayToVector(), pdal::Ilvis2MetadataReader::error::error(), pdal::DimBuilder::extractDim(), pdal::PlyReader::extractProperty(), pdal::PipelineReaderJSON::extractType(), pdal::PointLayout::finalized(), pdal::plang::fromMetadata(), pdal::GeotiffTags::GeotiffTags(), pdal::PointRef::getFieldAs(), pdal::plang::getTraceback(), pdal::PluginManager::guessLoadByPath(), pdal::LasWriter::handleHeaderForward(), Java_io_pdal_PointLayout_dimTypes(), Java_io_pdal_PointLayout_findDimType(), pdal::PluginManager::l_loadPlugin(), pdal::XMLSchema::load(), pdal::gdal::Raster::open(), operator>>(), pdal::LasUtils::parse(), pdal::PipelineReaderJSON::parsePipeline(), pdal::pclsupport::PCDtoPDAL(), pdal::pclsupport::PDALtoPCD(), pdal::PointView::point(), pdal::PointRef::pointId(), pdal::ExtraBytesIf::readFrom(), pdal::PointRef::setField(), pdal::PipelineManager::setProgressFd(), and pdal::Utils::toNative().
Variable Documentation
const int pdal::Dimension::COUNT = std::numeric_limits<uint16_t>::max() static
Definition at line 106 of file DimUtil.hpp.
Referenced by pdal::PointLayout::assignDim(), and TEST().
const int pdal::Dimension::PROPRIETARY = 0xF000 static
Definition at line 107 of file DimUtil.hpp.