PDAL: anonymous_namespace{ColorizationFilterTest.cpp} Namespace Reference
anonymous_namespace{ColorizationFilterTest.cpp} Namespace Reference
Functions
void testFile (const Options &filterOps, StringList dimNames, uint16_t expectedRed, uint16_t expectedGreen, uint16_t expectedBlue)
void testFileStreamed (const Options &filterOps, StringList dimNames, uint16_t expectedRed, uint16_t expectedGreen, uint16_t expectedBlue)
Function Documentation
void anonymous_namespace{ColorizationFilterTest.cpp}::testFile (const Options & filterOps, StringList dimNames, uint16_t expectedRed, uint16_t expectedGreen, uint16_t expectedBlue)
Definition at line 49 of file ColorizationFilterTest.cpp.
References pdal::Options::add(), b, Support::datapath(), pdal::Stage::execute(), hag::filter(), pdal::PointLayout::findDim(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
Referenced by TEST().
void anonymous_namespace{ColorizationFilterTest.cpp}::testFileStreamed (const Options & filterOps, StringList dimNames, uint16_t expectedRed, uint16_t expectedGreen, uint16_t expectedBlue)
Definition at line 81 of file ColorizationFilterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), hag::filter(), pdal::PointLayout::findDim(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::StreamCallbackFilter::setCallback(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
Referenced by TEST().