PDAL: pdal::entwine Namespace Reference
pdal::entwine Namespace Reference
Classes
class Bounds
class Color
class Point
Typedefs
using Transformation = std::vector< double >
Enumerations
enum Dir {
Dir::swd = 0, Dir::sed = 1, Dir::nwd = 2, Dir::ned = 3,
Dir::swu = 4, Dir::seu = 5, Dir::nwu = 6, Dir::neu = 7
}
Functions
std::ostream & operator<< (std::ostream &os, const Bounds &bounds)
PDAL_DLL bool operator< (const Bounds &lhs, const Bounds &rhs)
PDAL_DLL bool operator== (const Bounds &lhs, const Bounds &rhs)
PDAL_DLL bool operator!= (const Bounds &lhs, const Bounds &rhs)
constexpr std::size_t dirHalfEnd ()
constexpr std::size_t dirEnd ()
Dir getDirection (const Point &o, const Point &p)
Dir getDirection (const Point &o, const Point &p, bool force2d)
std::string dirToString (Dir dir)
Dir stringToDir (const std::string &s)
std::size_t toIntegral (Dir dir, bool force2d=false)
Dir toDir (std::size_t val)
bool isSouth (Dir dir)
bool isNorth (Dir dir)
bool isWest (Dir dir)
bool isEast (Dir dir)
bool isDown (Dir dir)
bool isUp (Dir dir)
std::ostream & operator<< (std::ostream &os, Dir dir)
bool ltChained (const Point &lhs, const Point &rhs)
bool operator< (const Point &lhs, const Point &rhs)
bool operator<= (const Point &lhs, const Point &rhs)
bool operator> (const Point &lhs, const Point &rhs)
bool operator>= (const Point &lhs, const Point &rhs)
bool operator== (const Point &lhs, const Point &rhs)
bool operator!= (const Point &lhs, const Point &rhs)
Point operator+ (const Point &in, double offset)
Point operator- (const Point &p)
Point operator- (const Point &in, double offset)
Point operator+ (const Point &lhs, const Point &rhs)
Point operator- (const Point &lhs, const Point &rhs)
Point & operator+= (Point &lhs, const Point &rhs)
Point & operator-= (Point &lhs, const Point &rhs)
Point operator* (const Point &p, double s)
Point operator* (const Point &a, const Point &b)
Point operator/ (const Point &a, const Point &b)
std::ostream & operator<< (std::ostream &os, const Point &point)
std::ostream & operator<< (std::ostream &os, const Color &c)
Typedef Documentation
using pdal::entwine::Transformation = typedef std::vector<double>
Definition at line 27 of file point.hpp.
Enumeration Type Documentation
enum pdal::entwine::Dir strong
Enumerator
swd
sed
nwd
ned
swu
seu
nwu
neu
Definition at line 19 of file dir.hpp.
Function Documentation
constexpr std::size_t pdal::entwine::dirEnd ()
Definition at line 32 of file dir.hpp.
constexpr std::size_t pdal::entwine::dirHalfEnd ()
Definition at line 31 of file dir.hpp.
std::string pdal::entwine::dirToString (Dir dir)
Definition at line 57 of file dir.hpp.
References ned, neu, nwd, nwu, sed, seu, swd, and swu.
Referenced by operator<<().
Dir pdal::entwine::getDirection (const Point & o, const Point & p)
Definition at line 35 of file dir.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Referenced by getDirection().
Dir pdal::entwine::getDirection (const Point & o, const Point & p, bool force2d)
Definition at line 43 of file dir.hpp.
References getDirection(), pdal::entwine::Point::x, and pdal::entwine::Point::y.
bool pdal::entwine::isDown (Dir dir)
Definition at line 100 of file dir.hpp.
References toIntegral().
Referenced by isUp().
bool pdal::entwine::isEast (Dir dir)
Definition at line 98 of file dir.hpp.
References isWest().
bool pdal::entwine::isNorth (Dir dir)
Definition at line 95 of file dir.hpp.
References isSouth().
bool pdal::entwine::isSouth (Dir dir)
Definition at line 94 of file dir.hpp.
References toIntegral().
Referenced by isNorth().
bool pdal::entwine::isUp (Dir dir)
Definition at line 101 of file dir.hpp.
References isDown().
bool pdal::entwine::isWest (Dir dir)
Definition at line 97 of file dir.hpp.
References toIntegral().
Referenced by isEast().
bool pdal::entwine::ltChained (const Point & lhs, const Point & rhs)
Definition at line 262 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
bool pdal::entwine::operator!= (const Point & lhs, const Point & rhs)
Definition at line 297 of file point.hpp.
PDAL_DLL bool pdal::entwine::operator!= (const Bounds & lhs, const Bounds & rhs)
Definition at line 303 of file bounds.hpp.
Point pdal::entwine::operator* (const Point & p, double s)
Definition at line 343 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Point pdal::entwine::operator* (const Point & a, const Point & b)
Definition at line 348 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Point pdal::entwine::operator+ (const Point & in, double offset)
Definition at line 302 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Point pdal::entwine::operator+ (const Point & lhs, const Point & rhs)
Definition at line 317 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Point& pdal::entwine::operator+= (Point & lhs, const Point & rhs)
Definition at line 327 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Point pdal::entwine::operator- (const Point & p)
Definition at line 307 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Referenced by pdal::Stage::execute().
Point pdal::entwine::operator- (const Point & in, double offset)
Definition at line 312 of file point.hpp.
Point pdal::entwine::operator- (const Point & lhs, const Point & rhs)
Definition at line 322 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Point& pdal::entwine::operator-= (Point & lhs, const Point & rhs)
Definition at line 335 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Point pdal::entwine::operator/ (const Point & a, const Point & b)
Definition at line 353 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
bool pdal::entwine::operator< (const Point & lhs, const Point & rhs)
Definition at line 272 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
PDAL_DLL bool pdal::entwine::operator< (const Bounds & lhs, const Bounds & rhs)
Definition at line 287 of file bounds.hpp.
References pdal::entwine::Bounds::mid().
std::ostream& pdal::entwine::operator<< (std::ostream & os, Dir dir)
Definition at line 103 of file dir.hpp.
References dirToString().
PDAL_DLL std::ostream & pdal::entwine::operator<< (std::ostream & os, const Bounds & bounds)
Definition at line 146 of file bounds.cpp.
References flags, pdal::entwine::Bounds::max(), and pdal::entwine::Bounds::min().
Referenced by pdal::entwine::Bounds::setMid().
std::ostream& pdal::entwine::operator<< (std::ostream & os, const Point & point)
Definition at line 358 of file point.hpp.
References flags, pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
std::ostream& pdal::entwine::operator<< (std::ostream & os, const Color & c)
Definition at line 416 of file point.hpp.
References pdal::entwine::Color::b, pdal::entwine::Color::g, and pdal::entwine::Color::r.
bool pdal::entwine::operator<= (const Point & lhs, const Point & rhs)
Definition at line 277 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
bool pdal::entwine::operator== (const Point & lhs, const Point & rhs)
Definition at line 292 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
PDAL_DLL bool pdal::entwine::operator== (const Bounds & lhs, const Bounds & rhs)
Definition at line 298 of file bounds.hpp.
References pdal::entwine::Bounds::max(), and pdal::entwine::Bounds::min().
bool pdal::entwine::operator> (const Point & lhs, const Point & rhs)
Definition at line 282 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
bool pdal::entwine::operator>= (const Point & lhs, const Point & rhs)
Definition at line 287 of file point.hpp.
References pdal::entwine::Point::x, pdal::entwine::Point::y, and pdal::entwine::Point::z.
Dir pdal::entwine::stringToDir (const std::string & s)
Definition at line 74 of file dir.hpp.
Dir pdal::entwine::toDir (std::size_t val)
Definition at line 89 of file dir.hpp.
Referenced by pdal::entwine::Bounds::get(), and pdal::entwine::Bounds::go().
std::size_t pdal::entwine::toIntegral (Dir dir, bool force2d = false)
Definition at line 82 of file dir.hpp.
Referenced by pdal::entwine::Bounds::get(), pdal::entwine::Bounds::go(), isDown(), isSouth(), and isWest().