PDAL: anonymous_namespace{ColorinterpFilterTest.cpp} Namespace Reference
anonymous_namespace{ColorinterpFilterTest.cpp} Namespace Reference
Functions
std::string makeColor ()
void standardTest (Options &coptions, std::function< bool(int, int)> test)
Function Documentation
std::string anonymous_namespace{ColorinterpFilterTest.cpp}::makeColor ()
Definition at line 48 of file ColorinterpFilterTest.cpp.
References pdal::Utils::toString().
Referenced by TEST().
void anonymous_namespace{ColorinterpFilterTest.cpp}::standardTest (Options & coptions, std::function< bool(int, int)> test)
Definition at line 183 of file ColorinterpFilterTest.cpp.
References pdal::Options::add(), b, pdal::Dimension::Blue, c, pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Dimension::Green, pdal::Stage::prepare(), pdal::Dimension::Red, pdal::StreamCallbackFilter::setCallback(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Dimension::Z, and z.
Referenced by TEST().