PDAL: setup Namespace Reference
setup Namespace Reference
Functions
def get_pdal_config (option)
Variables
bool USE_CYTHON = True
string ext = '.pyx'
log = logging.getLogger(__file__)
level
pdal_config = os.environ['PDAL_CONFIG']
module_version = None
dictionary open_kwds = {}
readme = fp.read()
changes = fp.read()
string long_description = readme+'\n\n'
list include_dirs = []
list library_dirs = []
list libraries = []
list extra_link_args = []
built_version = item.split('.')
built_major = int(built_version[0])
running_major = int(sys.version_info[0])
string message = "Version mismatch. PDAL Python support was compiled against version %d.x but setup is running version is %d.x. "
string separator = ':'
list extra_compile_args = ['-std=c++11',]
bool DEBUG = False
list sources = ['pdal/libpdalpython'+ext, "pdal/PyPipeline.cpp" ]
list extensions
setup_args
ext_modules
Function Documentation
def setup.get_pdal_config (option)
Get configuration option from the `pdal-config` development utility
This code was adapted from Shapely's geos-config stuff
Definition at line 51 of file setup.py.
References pdal::lasdump::anonymous_namespace{Header.cpp}.get().
Variable Documentation
setup.built_major = int(built_version[0])
Definition at line 121 of file setup.py.
setup.built_version = item.split('.')
Definition at line 120 of file setup.py.
setup.changes = fp.read()
Definition at line 100 of file setup.py.
bool setup.DEBUG = False
Definition at line 148 of file setup.py.
string setup.ext = '.pyx'
Definition at line 26 of file setup.py.
Referenced by pdal::StageFactory.inferReaderDriver(), pdal::StageFactory.inferWriterDriver(), pdal::LasWriter.initialize(), pdal::MetadataReader.read(), and pdal.TEST().
setup.ext_modules
Definition at line 194 of file setup.py.
setup.extensions
Initial value:
 = [DistutilsExtension("*",
                                    sources,
                                    include_dirs=include_dirs,
                                    library_dirs=library_dirs,
                                    extra_compile_args=extra_compile_args,
                                    libraries=libraries,
                                    extra_link_args=extra_link_args,)]
Definition at line 153 of file setup.py.
list setup.extra_compile_args = ['-std=c++11',]
Definition at line 146 of file setup.py.
list setup.extra_link_args = []
Definition at line 107 of file setup.py.
list setup.include_dirs = []
Definition at line 104 of file setup.py.
Referenced by option().
setup.level
Definition at line 37 of file setup.py.
Referenced by pdal::Tree.getFills(), libpdaljava::Pipeline.getLog(), libpdalpython::Pipeline.getLog(), pdal::Log.getLogStream(), pdal::MongusFilter.processGround(), pdal::PipelineExecutor.setLogLevel(), pdal::gdal::ErrorHandler.trampoline(), pdal::Tree.Tree(), and pdal::PipelineExecutor.~PipelineExecutor().
list setup.libraries = []
Definition at line 106 of file setup.py.
list setup.library_dirs = []
Definition at line 105 of file setup.py.
setup.log = logging.getLogger(__file__)
Definition at line 33 of file setup.py.
Referenced by App.App(), pdal::LasReader.initializeLocal(), pdal::SMRFilter.prepared(), pdal::StatsFilter.prepared(), pdal::SMRFilter.progressiveFilter(), pdal::LasReader.readExtraBytesVlr(), pdal::TextWriter.ready(), pdal::FlexWriter.ready(), pdal::Kernel.run(), pdal::HeadFilter.run(), pdal::TailFilter.run(), pdal::mlang::Script.Script(), pdal::LasError.setLog(), pdal::geos::ErrorHandler.setLog(), pdal::PluginManager.setLog(), pdal::PipelineManager.setLog(), pdal::BpfHeader.setLog(), pdal::Stage.setLog(), pdal::gdal::ErrorHandler.setLog(), pdal::LasHeader.setLog(), pdal::PipelineExecutor.setLogStream(), TEST(), pdal::TextWriter.writeHeader(), and pdal::Kernel.~Kernel().
string setup.long_description = readme+'\n\n'
Definition at line 102 of file setup.py.
string setup.message = "Version mismatch. PDAL Python support was compiled against version %d.x but setup is running version is %d.x. "
Definition at line 124 of file setup.py.
Referenced by anonymous_namespace{LasReaderTest.cpp}.CheckEqualCollections(), anonymous_namespace{BPFTest.cpp}.CheckEqualCollections(), if(), include(), and target_include_directories().
setup.module_version = None
Definition at line 78 of file setup.py.
dictionary setup.open_kwds = {}
Definition at line 89 of file setup.py.
string setup.pdal_config = os.environ['PDAL_CONFIG']
Definition at line 42 of file setup.py.
setup.readme = fp.read()
Definition at line 97 of file setup.py.
setup.running_major = int(sys.version_info[0])
Definition at line 122 of file setup.py.
string setup.separator = ':'
Definition at line 131 of file setup.py.
setup.setup_args
Initial value:
 = dict(
     name                = 'PDAL',
     version             = str(module_version),
     requires            = ['Python (>=2.7)', ],
     description         = 'Point cloud data processing',
     license             = 'BSD',
     keywords            = 'point cloud spatial',
     author              = 'Howard Butler',
     author_email        = 'howard@hobu.co',
     maintainer          = 'Howard Butler',
     maintainer_email    = 'howard@hobu.co',
     url                 = 'http://pdal.io',
     long_description    = long_description,
     test_suite          = 'test',
     packages            = [
         'pdal',
     ],
     classifiers         = [
         'Development Status :: 5 - Production/Stable',
         'Intended Audience :: Developers',
         'Intended Audience :: Science/Research',
         'License :: OSI Approved :: BSD License',
         'Operating System :: OS Independent',
         'Programming Language :: Python :: 2.7',
         'Programming Language :: Python :: 3',
         'Topic :: Scientific/Engineering :: GIS',
     ],
     cmdclass           = {},
     install_requires   = ['numpy', 'packaging'],
 )
Definition at line 164 of file setup.py.
list setup.sources = ['pdal/libpdalpython'+ext, "pdal/PyPipeline.cpp" ]
Definition at line 152 of file setup.py.
bool setup.USE_CYTHON = True
Definition at line 20 of file setup.py.