PDAL: anonymous_namespace{pcpipelineTestJSON.cpp} Namespace Reference
anonymous_namespace{pcpipelineTestJSON.cpp} Namespace Reference
Functions
std::string appName ()
void run_pipeline (std::string const &pipelineFile, const std::string options=std::string())
void run_pipeline_stdin (std::string const &pipelineFile)
Function Documentation
std::string anonymous_namespace{pcpipelineTestJSON.cpp}::appName ()
Definition at line 51 of file pcpipelineTestJSON.cpp.
References Support::binpath(), and Support::exename().
void anonymous_namespace{pcpipelineTestJSON.cpp}::run_pipeline (std::string const & pipelineFile, const std::string options = std::string())
Definition at line 59 of file pcpipelineTestJSON.cpp.
References appName(), Support::configuredpath(), and pdal::Utils::run_shell_command().
void anonymous_namespace{pcpipelineTestJSON.cpp}::run_pipeline_stdin (std::string const & pipelineFile)
Definition at line 74 of file pcpipelineTestJSON.cpp.
References appName(), Support::configuredpath(), and pdal::Utils::run_shell_command().
Referenced by pdal::TEST().