PDAL: pdal::georeference Namespace Reference
pdal::georeference Namespace Reference
Namespaces
anonymous_namespace{Georeference.cpp}
Classes
struct RotationMatrix
struct Xyz
Functions
Xyz georeferenceWgs84 (double range, double scanAngle, const RotationMatrix &boresightMatrix, const RotationMatrix &imuMatrix, const Xyz &gpsPoint)
RotationMatrix createIdentityMatrix ()
TEST (RotationMatrix, Constructor)
TEST (RotationMatrix, IdentityMatrix)
TEST (Georeference, Zeros)
TEST (Georeference, LatLonElev)
TEST (Georeference, Range)
TEST (Georeference, RangeAndAngle)
TEST (Georeference, WithImu)
Function Documentation
RotationMatrix pdal::georeference::createIdentityMatrix ()
Definition at line 80 of file Georeference.hpp.
References georeferenceWgs84(), and PDAL_DLL.
Referenced by TEST().
PDAL_DLL Xyz pdal::georeference::georeferenceWgs84 (double range, double scanAngle, const RotationMatrix & boresightMatrix, const RotationMatrix & imuMatrix, const Xyz & gpsPoint)
Definition at line 76 of file Georeference.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::cartesianToCurvilinear(), pdal::georeference::anonymous_namespace{Georeference.cpp}::rotate(), pdal::georeference::Xyz::X, pdal::georeference::Xyz::Y, and pdal::georeference::Xyz::Z.
Referenced by createIdentityMatrix(), pdal::OptechReader::read(), and TEST().
pdal::georeference::TEST (RotationMatrix , Constructor)
Definition at line 48 of file GeoreferenceTest.cpp.
References pdal::georeference::RotationMatrix::m00, pdal::georeference::RotationMatrix::m01, pdal::georeference::RotationMatrix::m10, pdal::georeference::RotationMatrix::m11, pdal::georeference::RotationMatrix::m12, pdal::georeference::RotationMatrix::m20, pdal::georeference::RotationMatrix::m21, and pdal::georeference::RotationMatrix::m22.
pdal::georeference::TEST (RotationMatrix , IdentityMatrix)
Definition at line 63 of file GeoreferenceTest.cpp.
References createIdentityMatrix(), pdal::georeference::RotationMatrix::m00, pdal::georeference::RotationMatrix::m01, pdal::georeference::RotationMatrix::m10, pdal::georeference::RotationMatrix::m11, pdal::georeference::RotationMatrix::m12, pdal::georeference::RotationMatrix::m20, pdal::georeference::RotationMatrix::m21, and pdal::georeference::RotationMatrix::m22.
pdal::georeference::TEST (Georeference , Zeros)
Definition at line 78 of file GeoreferenceTest.cpp.
References createIdentityMatrix(), georeferenceWgs84(), pdal::georeference::Xyz::X, pdal::georeference::Xyz::Y, and pdal::georeference::Xyz::Z.
pdal::georeference::TEST (Georeference , LatLonElev)
Definition at line 88 of file GeoreferenceTest.cpp.
References createIdentityMatrix(), georeferenceWgs84(), pdal::georeference::Xyz::X, pdal::georeference::Xyz::Y, and pdal::georeference::Xyz::Z.
pdal::georeference::TEST (Georeference , Range)
Definition at line 98 of file GeoreferenceTest.cpp.
References createIdentityMatrix(), georeferenceWgs84(), pdal::georeference::Xyz::X, pdal::georeference::Xyz::Y, and pdal::georeference::Xyz::Z.
pdal::georeference::TEST (Georeference , RangeAndAngle)
Definition at line 108 of file GeoreferenceTest.cpp.
References createIdentityMatrix(), georeferenceWgs84(), pdal::georeference::Xyz::X, pdal::georeference::Xyz::Y, and pdal::georeference::Xyz::Z.
pdal::georeference::TEST (Georeference , WithImu)
Definition at line 118 of file GeoreferenceTest.cpp.
References createIdentityMatrix(), georeferenceWgs84(), pdal::georeference::Xyz::X, pdal::georeference::Xyz::Y, and pdal::georeference::Xyz::Z.