PDAL: pdal::FileUtils Namespace Reference
pdal::FileUtils Namespace Reference
Functions
std::istream * openFile (std::string const &filename, bool asBinary)
std::ostream * createFile (std::string const &name, bool asBinary)
bool directoryExists (const std::string &dirname)
bool createDirectory (const std::string &dirname)
void deleteDirectory (const std::string &dirname)
std::vector< std::string > directoryList (const std::string &dir)
void closeFile (std::ostream *out)
void closeFile (std::istream *in)
bool deleteFile (const std::string &file)
void renameFile (const std::string &dest, const std::string &src)
bool fileExists (const std::string &name)
uintmax_t fileSize (const std::string &file)
std::string readFileIntoString (const std::string &filename)
std::string getcwd ()
std::string toAbsolutePath (const std::string &filename)
std::string toAbsolutePath (const std::string &filename, const std::string base)
std::string getFilename (const std::string &path)
std::string getDirectory (const std::string &path)
std::string stem (const std::string &path)
bool isDirectory (const std::string &path)
bool isAbsolutePath (const std::string &path)
void fileTimes (const std::string &filename, struct tm *createTime, struct tm *modTime)
std::string extension (const std::string &filename)
std::vector< std::string > glob (std::string path)
Function Documentation
PDAL_DLL void pdal::FileUtils::closeFile (std::ostream * ofs)
Close a file created with createFile.
Parameters
ofs Pointer to stream to close.
Definition at line 158 of file FileUtils.cpp.
Referenced by pdal::OciReader::addDimensions(), pdal::TranslateKernel::execute(), pdal::getJSON(), pdal::getWKT(), pdal::FileStreamDeleter::operator()(), readFileIntoString(), TEST(), pdal::TEST(), pdal::nitfwrap::NitfWrap::unwrap(), and pdal::NitfReader::NitfStreamIf::~NitfStreamIf().
PDAL_DLL void pdal::FileUtils::closeFile (std::istream * ifs)
Close a file created with openFile.
Parameters
ifs Pointer to stream to close.
Definition at line 173 of file FileUtils.cpp.
PDAL_DLL bool pdal::FileUtils::createDirectory (const std::string & dirname)
Create a directory.
Parameters
dirname Directory name.
Returns
Whether the directory was created.
Definition at line 131 of file FileUtils.cpp.
PDAL_DLL std::ostream * pdal::FileUtils::createFile (std::string const & filename, bool asBinary = true)
Create a file and open for writing.
Parameters
filename Filename.
asBinary Write as binary file (don't convert /n to /r/n)
Returns
Point to opened stream.
Definition at line 105 of file FileUtils.cpp.
References pdal::anonymous_namespace{FileUtils.cpp}::isStdout().
Referenced by pdal::TranslateKernel::execute(), pdal::MyWriter::initialize(), TEST(), pdal::TEST(), and pdal::nitfwrap::NitfWrap::unwrap().
PDAL_DLL void pdal::FileUtils::deleteDirectory (const std::string & dirname)
Delete a directory and its contents.
Parameters
dirname Directory name.
Definition at line 137 of file FileUtils.cpp.
PDAL_DLL bool pdal::FileUtils::deleteFile (const std::string & filename)
Delete a file.
Parameters
filename Name of file to delete.
Returns
true if successful, false otherwise
Definition at line 188 of file FileUtils.cpp.
References pdal::Utils::remove().
Referenced by compareTextLasStreaming(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter(), anonymous_namespace{GDALWriterTest.cpp}::runGdalWriter2(), TEST(), pdal::TEST(), anonymous_namespace{BPFTest.cpp}::test_roundtrip(), testOverlay(), testReadWrite(), and pdal::Utils::anonymous_namespace{PDALUtils.cpp}::TempFile::~TempFile().
PDAL_DLL bool pdal::FileUtils::directoryExists (const std::string & dirname)
Determine if a directory exists.
Parameters
dirname Name of directory.
Returns
Whether a directory exists.
Definition at line 124 of file FileUtils.cpp.
Referenced by pdal::SMRFilter::ready().
PDAL_DLL std::vector< std::string > pdal::FileUtils::directoryList (const std::string & dirname)
List the contents of a directory.
Parameters
dirname Name of directory to list.
Returns
List of entries in the directory.
Definition at line 143 of file FileUtils.cpp.
Referenced by pdal::PluginManager::guessLoadByPath(), and pdal::PluginManager::loadAll().
PDAL_DLL std::string pdal::FileUtils::extension (const std::string & path)
Return the extension of the filename, including the separator (.).
Parameters
path File path from which to extract extension.
Returns
Extension of filename.
Definition at line 355 of file FileUtils.cpp.
Referenced by pdal::DensityKernel::execute(), pdal::PluginManager::guessLoadByPath(), pdal::StageFactory::inferReaderDriver(), pdal::StageFactory::inferWriterDriver(), pdal::LasWriter::initialize(), pdal::PluginManager::l_loadPlugin(), pdal::PluginManager::loadAll(), pdal::InfoKernel::makePipeline(), pdal::OGRWriter::prepared(), pdal::PipelineManager::readPipeline(), and TEST().
PDAL_DLL bool pdal::FileUtils::fileExists (const std::string & filename)
Determine if a file exists.
Parameters
Filename.
Returns
Whether the file exists.
Definition at line 200 of file FileUtils.cpp.
References pdal::anonymous_namespace{FileUtils.cpp}::isStdin().
Referenced by pdal::hexdensity::writer::OGR::createLayer(), fileIsOkay(), pdal::Options::fromFile(), pdal::PluginManager::guessLoadByPath(), pdal::IcebridgeReader::initialize(), pdal::BpfWriter::initialize(), pdal::Ilvis2Reader::initialize(), pdal::PluginManager::loadAll(), pdal::SQLiteWriter::loadGeometryWKT(), pdal::TranslateKernel::makeJSONPipeline(), openFile(), pdal::nitfwrap::NitfWrap::parseArgs(), and TEST().
PDAL_DLL uintmax_t pdal::FileUtils::fileSize (const std::string & filename)
Get the size of a file.
Parameters
filename Filename.
Returns
Size of file.
Definition at line 216 of file FileUtils.cpp.
Referenced by fileIsOkay(), pdal::BpfWriter::initialize(), pdal::SbetReader::ready(), and TEST().
PDAL_DLL void pdal::FileUtils::fileTimes (const std::string & filename, struct tm * createTime, struct tm * modTime)
Get the file creation and modification times.
Parameters
filename Filename.
createTime Pointer to creation time structure.
modTime Pointer to modification time structure.
Definition at line 332 of file FileUtils.cpp.
Referenced by pdal::TIndexKernel::getFileInfo().
PDAL_DLL std::string pdal::FileUtils::getcwd ()
Get the current working directory with trailing separator.
Returns
The current working directory.
Definition at line 237 of file FileUtils.cpp.
References pdal::anonymous_namespace{FileUtils.cpp}::addTrailingSlash().
Referenced by TEST().
PDAL_DLL std::string pdal::FileUtils::getDirectory (const std::string & path)
Return the directory component of the given path, e.g. "d:/foo/bar/a.c" -> "d:/foo/bar/"
Parameters
path Path from which to extract directory component.
Returns
Directory part of path.
Definition at line 298 of file FileUtils.cpp.
References pdal::anonymous_namespace{FileUtils.cpp}::addTrailingSlash().
Referenced by TEST().
PDAL_DLL std::string pdal::FileUtils::getFilename (const std::string & path)
Return the file component of the given path, e.g. "d:/foo/bar/a.c" -> "a.c"
Parameters
path Path from which to extract file component.
Returns
File part of path.
Definition at line 282 of file FileUtils.cpp.
Referenced by pdal::BpfWriter::initialize(), pdal::PluginManager::loadByPath(), stem(), TEST(), and pdal::NitfFileWriter::write().
PDAL_DLL std::vector< std::string > pdal::FileUtils::glob (std::string filespec)
Expand a filespec to a list of files.
Parameters
filespec File specification to expand.
Returns
List of files that correspond to provided file specification.
Definition at line 364 of file FileUtils.cpp.
Referenced by pdal::TIndexKernel::createFile(), pdal::PipelineReaderJSON::parsePipeline(), and TEST().
PDAL_DLL bool pdal::FileUtils::isAbsolutePath (const std::string & path)
Determine if the path is an absolute path.
Parameters
path Path to test.
Returns
Whether the path is absolute.
Definition at line 326 of file FileUtils.cpp.
Referenced by TEST().
PDAL_DLL bool pdal::FileUtils::isDirectory (const std::string & path)
Determine if path is a directory.
Parameters
path Directory to check.
Returns
Whether the path represents a directory.
Definition at line 320 of file FileUtils.cpp.
Referenced by pdal::PluginManager::guessLoadByPath(), pdal::PluginManager::l_loadPlugin(), and pdal::PluginManager::loadAll().
PDAL_DLL std::istream * pdal::FileUtils::openFile (std::string const & filename, bool asBinary = true)
Open an existing file for reading.
Parameters
filename Filename.
asBinary Read as binary file (don't convert /r/n to /n)
Returns
Pointer to opened stream.
Definition at line 80 of file FileUtils.cpp.
References fileExists(), pdal::anonymous_namespace{FileUtils.cpp}::isStdin(), and pdal::Dimension::name().
Referenced by pdal::getJSON(), pdal::getWKT(), pdal::NitfReader::NitfStreamIf::NitfStreamIf(), readFileIntoString(), ReadXML(), TEST(), pdal::nitfwrap::NitfWrap::unwrap(), and pdal::nitfwrap::NitfWrap::verify().
PDAL_DLL std::string pdal::FileUtils::readFileIntoString (const std::string & filename)
Read a file into a string.
Parameters
filename Filename.
Returns
File contents as a string
Definition at line 222 of file FileUtils.cpp.
References closeFile(), and openFile().
Referenced by pdal::PgWriter::done(), pdal::SQLiteWriter::done(), pdal::Options::fromFile(), pdal::SQLiteWriter::loadGeometryWKT(), pdal::TranslateKernel::makeJSONPipeline(), pdal::MatlabFilter::ready(), pdal::PythonFilter::ready(), pdal::SpatialReference::set(), TEST(), pdal::TEST(), pdal::PgWriter::writeInit(), and pdal::SQLiteWriter::writeInit().
PDAL_DLL void pdal::FileUtils::renameFile (const std::string & dest, const std::string & src)
Rename a file.
Parameters
dest Desired filename.
src Source filename.
Definition at line 194 of file FileUtils.cpp.
Referenced by TEST().
PDAL_DLL std::string pdal::FileUtils::stem (const std::string & path)
Return the filename stripped of the extension. . and .. are returned unchanged.
Parameters
path File path from which to extract file stem.
Returns
Stem of filename.
Definition at line 306 of file FileUtils.cpp.
References pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and getFilename().
Referenced by pdal::PluginManager::guessLoadByPath(), pdal::nitfwrap::NitfWrap::parseArgs(), TEST(), and pdal::nitfwrap::NitfWrap::unwrap().
PDAL_DLL std::string pdal::FileUtils::toAbsolutePath (const std::string & filename)
If the filename is an absolute path, just return it otherwise, make it absolute (relative to current working dir) and return it.
Parameters
filename Name of file to convert to absolute path.
Returns
Absolute version of provided filename.
Definition at line 265 of file FileUtils.cpp.
Referenced by pdal::SMRFilter::classifyGround(), pdal::TIndexKernel::createDataset(), pdal::TIndexKernel::createFile(), pdal::SMRFilter::createLowMask(), pdal::SMRFilter::createObjMask(), pdal::SMRFilter::createZImin(), pdal::SMRFilter::createZInet(), pdal::SMRFilter::createZIpro(), pdal::PluginManager::libraryLoaded(), pdal::PluginManager::loadByPath(), pdal::PluginManager::loadLibrary(), pdal::anonymous_namespace{PluginManager.cpp}::pluginSearchPaths(), TEST(), and toAbsolutePath().
PDAL_DLL std::string pdal::FileUtils::toAbsolutePath (const std::string & filename, const std::string base)
If the filename is an absolute path, just return it otherwise, make it absolute (relative to base dir) and return that.
Parameters
filename Name of file to convert to absolute path.
base Base name to use.
Returns
Absolute version of provided filename relative to base.
Definition at line 276 of file FileUtils.cpp.
References toAbsolutePath().