PDAL: pdal::pclsupport Namespace Reference
pdal::pclsupport Namespace Reference
Functions
template<typename CLOUDFETCH >
void setValues (PointViewPtr view, Dimension::Id dim, size_t numPts, CLOUDFETCH fetcher)
template<typename CloudT >
void PCDtoPDAL (CloudT &cloud, PointViewPtr view, BOX3D const &bounds)
Convert PCD point cloud to PDAL.
template<typename CloudT >
void PCDtoPDAL (CloudT &cloud, PointViewPtr view)
template<typename CloudT >
void PDALtoPCD (PointViewPtr view, CloudT &cloud, BOX3D const &bounds, double const &scale_x, double const &scale_y, double const &scale_z)
Convert PDAL point cloud to PCD.
template<typename CloudT >
void PDALtoPCD (PointViewPtr view, CloudT &cloud, BOX3D const &bounds)
Convert PDAL point cloud to PCD.
template<typename CloudT >
void PDALtoPCD (PointViewPtr view, CloudT &cloud)
void setLogLevel (LogLevel level)
Function Documentation
template<typename CloudT > void pdal::pclsupport::PCDtoPDAL (CloudT & cloud, PointViewPtr view, BOX3D const & bounds)
Convert PCD point cloud to PDAL.
Converts PCD data to PDAL format.
Definition at line 68 of file PCLConversions.hpp.
References pdal::Dimension::Blue, pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Dimension::Green, pdal::Dimension::Intensity, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::BOX3D::minz, pdal::Dimension::Red, setValues(), pdal::Dimension::type(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by PCDtoPDAL(), pdal::PcdReader::read(), pdal::MovingLeastSquaresFilter::run(), pdal::GridProjectionFilter::run(), pdal::VoxelGridFilter::run(), and pdal::PCLBlock::run().
template<typename CloudT > void pdal::pclsupport::PCDtoPDAL (CloudT & cloud, PointViewPtr view)
Definition at line 120 of file PCLConversions.hpp.
References PCDtoPDAL().
template<typename CloudT > void pdal::pclsupport::PDALtoPCD (PointViewPtr view, CloudT & cloud, BOX3D const & bounds, double const & scale_x, double const & scale_y, double const & scale_z)
Convert PDAL point cloud to PCD.
Converts PDAL data to PCD format.
Definition at line 133 of file PCLConversions.hpp.
References b, pdal::Dimension::Blue, pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Dimension::Green, pdal::Dimension::Intensity, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::BOX3D::minz, pdal::Dimension::Red, pdal::Dimension::type(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by pdal::IcpFilter::icp(), PDALtoPCD(), pdal::GridProjectionFilter::run(), pdal::MovingLeastSquaresFilter::run(), pdal::VoxelGridFilter::run(), pdal::PCLBlock::run(), and pdal::PcdWriter::writeView().
template<typename CloudT > void pdal::pclsupport::PDALtoPCD (PointViewPtr view, CloudT & cloud, BOX3D const & bounds)
Convert PDAL point cloud to PCD.
Converts PDAL data to PCD format.
Definition at line 199 of file PCLConversions.hpp.
References PDALtoPCD().
template<typename CloudT > void pdal::pclsupport::PDALtoPCD (PointViewPtr view, CloudT & cloud)
Definition at line 207 of file PCLConversions.hpp.
References PDALtoPCD().
void pdal::pclsupport::setLogLevel (LogLevel level)
Definition at line 214 of file PCLConversions.hpp.
References pdal::Debug, pdal::Debug1, pdal::Error, pdal::Info, and pdal::Warning.
Referenced by libpdaljava::Pipeline::getLog(), libpdalpython::Pipeline::getLog(), pdal::MovingLeastSquaresFilter::run(), pdal::GridProjectionFilter::run(), pdal::VoxelGridFilter::run(), pdal::PCLBlock::run(), and pdal::PipelineExecutor::~PipelineExecutor().
template<typename CLOUDFETCH > void pdal::pclsupport::setValues (PointViewPtr view, Dimension::Id dim, size_t numPts, CLOUDFETCH fetcher)
Definition at line 55 of file PCLConversions.hpp.
Referenced by PCDtoPDAL().