PDAL: anonymous_namespace{GreyhoundReaderTest.cpp} Namespace Reference
anonymous_namespace{GreyhoundReaderTest.cpp} Namespace Reference
Functions
const std::string server ("http://data.greyhound.io")
const std::string resource ("dev/ellipsoid-multi-nyc")
const greyhound::Bounds full (center-radius, center+radius)
Options toOptions (const Json::Value &json)
std::string dense (const Json::Value &json)
Variables
const greyhound::Point center (-8242596.04, 4966606.26)
const greyhound::Point radius (151, 101, 51)
Function Documentation
std::string anonymous_namespace{GreyhoundReaderTest.cpp}::dense (const Json::Value & json)
Definition at line 79 of file GreyhoundReaderTest.cpp.
Referenced by TEST_F().
const greyhound::Bounds anonymous_namespace{GreyhoundReaderTest.cpp}::full (center- radius, center+ radius)
const std::string anonymous_namespace{GreyhoundReaderTest.cpp}::resource ("dev/ellipsoid-multi-nyc")
Referenced by pdal::GreyhoundReader::Args::base(), GreyhoundReaderTest::GreyhoundReaderTest(), and TEST_F().
const std::string anonymous_namespace{GreyhoundReaderTest.cpp}::server ("http://data.greyhound.io")
Referenced by GreyhoundReaderTest::GreyhoundReaderTest(), and TEST_F().
Options anonymous_namespace{GreyhoundReaderTest.cpp}::toOptions (const Json::Value & json)
Definition at line 60 of file GreyhoundReaderTest.cpp.
References pdal::Options::add().
Referenced by TEST_F().
Variable Documentation
const greyhound::Point anonymous_namespace{GreyhoundReaderTest.cpp}::center(-8242596.04, 4966606.26)
Referenced by pdal::Tree::addPoint(), anonymous_namespace{QuadIndex.cpp}::BBox::overlaps(), pdal::CropFilter::processOne(), pdal::ChipperFilter::split(), and TEST_F().
const greyhound::Point anonymous_namespace{GreyhoundReaderTest.cpp}::radius(151, 101, 51)
Referenced by pcl::Pipeline< PointT >::applyRadiusOutlierRemoval(), pdal::eigen::centralDiffY(), pdal::eigen::computeSpline(), pdal::eigen::dilate(), pdal::eigen::erode(), pdal::GDALGrid::error::error(), pdal::SMRFilter::progressiveFilter(), pdal::KD2Index::radius(), and pdal::KD3Index::radius().