PDAL: pdal::LasUtils Namespace Reference
pdal::LasUtils Namespace Reference
Classes
struct error
struct IgnoreVLR
Functions
std::vector< IgnoreVLR > parseIgnoreVLRs (const StringList &ignored)
std::vector< ExtraDim > parse (const StringList &dimString)
Class Documentation
struct pdal::LasUtils::IgnoreVLR
Definition at line 177 of file LasUtils.hpp.
Class Members
uint16_t m_recordId
string m_userId
Function Documentation
std::vector< ExtraDim > pdal::LasUtils::parse (const StringList & dimString)
Definition at line 215 of file LasUtils.cpp.
References pdal::Dimension::None, pdal::Utils::split2(), pdal::Utils::trim(), and pdal::Dimension::type().
Referenced by pdal::LasUtils::error::error(), pdal::LasWriter::initialize(), pdal::LasReader::initializeLocal(), TEST(), and pdal::Uuid::Uuid().
std::vector< IgnoreVLR > pdal::LasUtils::parseIgnoreVLRs (const StringList & ignored)
Definition at line 183 of file LasUtils.cpp.
References pdal::Dimension::id(), pdal::LasUtils::IgnoreVLR::m_recordId, pdal::LasUtils::IgnoreVLR::m_userId, pdal::Utils::split2(), and pdal::Utils::trim().
Referenced by pdal::LasReader::initializeLocal().