PDAL: pdal::Utils Namespace Reference
pdal::Utils Namespace Reference
Namespaces
anonymous_namespace{PDALUtils.cpp}
Classes
struct RedirectStream
Functions
template<>
bool fromString< Eigen::MatrixXd > (const std::string &s, Eigen::MatrixXd &matrix)
std::string toJSON (const MetadataNode &m)
void toJSON (const MetadataNode &m, std::ostream &o)
std::ostream * createFile (const std::string &path, bool asBinary)
std::istream * openFile (const std::string &path, bool asBinary)
void closeFile (std::ostream *out)
void closeFile (std::istream *in)
bool fileExists (const std::string &path)
double computeHausdorff (PointViewPtr srcView, PointViewPtr candView)
void printError (const std::string &s)
double toDouble (const Everything &e, Dimension::Type type)
template<typename INPUT >
Everything extractDim (INPUT &ext, Dimension::Type type)
template<typename OUTPUT >
void insertDim (OUTPUT &ins, Dimension::Type type, const Everything &e)
MetadataNode toMetadata (const BOX2D &bounds)
MetadataNode toMetadata (const BOX3D &bounds)
int openProgress (const std::string &filename)
void closeProgress (int fd)
void writeProgress (int fd, const std::string &type, const std::string &text)
std::vector< std::string > PDAL_DLL maybeGlob (const std::string &path)
template<typename CONTAINER , typename VALUE >
bool contains (const CONTAINER &cont, const VALUE &val)
template<typename KEY , typename VALUE >
bool contains (const std::map< KEY, VALUE > &c, const KEY &v)
template<typename CONTAINER , typename VALUE >
void remove (CONTAINER &cont, const VALUE &val)
template<typename CONTAINER , typename PREDICATE >
void remove_if (CONTAINER &cont, PREDICATE p)
template<class T >
PDAL_DLL const T & clamp (const T &t, const T &min, const T &max)
Clamp value to given bounds.
PDAL_DLL void random_seed (unsigned int seed)
PDAL_DLL double random (double minimum, double maximum)
PDAL_DLL double uniform (const double &minimum, const double &maximum, uint32_t seed)
PDAL_DLL double normal (const double &mean, const double &sigma, uint32_t seed)
PDAL_DLL bool compare_approx (double v1, double v2, double tolerance)
double sround (double r)
std::string tolower (const std::string &s)
std::string toupper (const std::string &s)
bool iequals (const std::string &s, const std::string &s2)
bool startsWith (const std::string &s, const std::string &prefix)
int cksum (char *buf, size_t size)
PDAL_DLL int getenv (std::string const &name, std::string &val)
PDAL_DLL int setenv (const std::string &env, const std::string &val)
PDAL_DLL int unsetenv (const std::string &env)
PDAL_DLL void eatwhitespace (std::istream &s)
PDAL_DLL void trimLeading (std::string &s)
PDAL_DLL void trimTrailing (std::string &s)
void trim (std::string &s)
PDAL_DLL bool eatcharacter (std::istream &s, char x)
PDAL_DLL std::string base64_encode (const unsigned char *buf, size_t size)
std::string base64_encode (std::vector< uint8_t > const &bytes)
PDAL_DLL std::vector< uint8_t > base64_decode (std::string const &input)
PDAL_DLL FILE * portable_popen (const std::string &command, const std::string &mode)
PDAL_DLL int portable_pclose (FILE *fp)
PDAL_DLL int run_shell_command (const std::string &cmd, std::string &output)
PDAL_DLL std::string replaceAll (std::string input, const std::string &replaceWhat, const std::string &replaceWithWhat)
PDAL_DLL std::vector< std::string > wordWrap (std::string const &inputString, size_t lineLength, size_t firstLength=0)
PDAL_DLL std::vector< std::string > wordWrap2 (std::string const &inputString, size_t lineLength, size_t firstLength=0)
PDAL_DLL std::string escapeJSON (const std::string &s)
PDAL_DLL std::string demangle (const std::string &s)
PDAL_DLL int screenWidth ()
PDAL_DLL std::string escapeNonprinting (const std::string &s)
PDAL_DLL double normalizeLongitude (double longitude)
PDAL_DLL std::string hexDump (const char *buf, size_t count)
PDAL_DLL std::vector< std::string > backtrace ()
template<typename PREDICATE >
PDAL_DLL std::string::size_type extract (const std::string &s, std::string::size_type p, PREDICATE pred)
PDAL_DLL std::string::size_type extractSpaces (const std::string &s, std::string::size_type p)
template<typename PREDICATE >
PDAL_DLL std::vector< std::string > split (const std::string &s, PREDICATE p)
template<typename PREDICATE >
PDAL_DLL std::vector< std::string > split2 (const std::string &s, PREDICATE p)
PDAL_DLL std::vector< std::string > split (const std::string &s, char tChar)
PDAL_DLL std::vector< std::string > split2 (const std::string &s, char tChar)
PDAL_DLL std::vector< std::string > simpleWordexp (const std::string &s)
template<typename T >
std::string typeidName ()
RedirectStream redirect (std::ostream &out, std::ostream &dst)
RedirectStream redirect (std::ostream &out)
RedirectStream redirect (std::ostream &out, const std::string &file)
void restore (std::ostream &out, RedirectStream &redir)
template<typename T_OUT >
bool inRange (double in)
template<typename T_IN , typename T_OUT >
bool inRange (T_IN in)
template<typename T_IN , typename T_OUT >
bool numericCast (T_IN in, T_OUT &out)
template<typename T >
std::string toString (const T &from)
std::string toString (bool from)
std::string toString (double from)
std::string toString (float from)
std::string toString (long long from)
std::string toString (unsigned long from)
std::string toString (long from)
std::string toString (unsigned int from)
std::string toString (int from)
std::string toString (unsigned short from)
std::string toString (short from)
std::string toString (char from)
std::string toString (unsigned char from)
std::string toString (signed char from)
template<typename T >
bool fromString (const std::string &from, T *&to)
template<typename T >
bool fromString (const std::string &from, T &to)
template<>
bool fromString (const std::string &from, std::string &to)
template<>
bool fromString< char > (const std::string &s, char &to)
template<>
bool fromString< unsigned char > (const std::string &s, unsigned char &to)
template<>
bool fromString< signed char > (const std::string &s, signed char &to)
template<>
bool fromString< double > (const std::string &s, double &d)
template<typename E >
std::underlying_type< E >::type toNative (E e)
Function Documentation
std::vector< std::string > pdal::Utils::backtrace ()
Generate a backtrace as a list of strings.
Returns
List of functions at the point of the call.
Definition at line 606 of file Utils.cpp.
References demangle(), pdal::Dimension::size(), trimLeading(), and trimTrailing().
Referenced by base64_encode(), and App::execute().
std::vector< uint8_t > pdal::Utils::base64_decode (std::string const & input)
Decode a base64-encoded string into a buffer.
Parameters
input String to decode.
Returns
Buffer containing decoded string.
Definition at line 282 of file Utils.cpp.
References pdal::is_base64().
Referenced by pdal::LasWriter::addForwardVlrs(), pdal::LasWriter::addUserVlrs(), base64_encode(), pdal::BpfWriter::initialize(), TEST(), and pdal::MetadataNode::value().
std::string pdal::Utils::base64_encode (const unsigned char * buf, size_t size)
Convert a buffer to a string using base64 encoding.
Parameters
buf Pointer to buffer to encode.
size Size of buffer.
Returns
Encoded buffer.
Definition at line 193 of file Utils.cpp.
Referenced by pdal::MetadataNode::addEncoded(), pdal::MetadataNode::addListEncoded(), base64_encode(), TEST(), and trim().
std::string pdal::Utils::base64_encode (std::vector< uint8_t > const & bytes)
Convert a buffer to a string using base64 encoding.
Parameters
bytes Pointer to buffer to encode.
Returns
Encoded buffer.
Definition at line 299 of file Utils.hpp.
References backtrace(), base64_decode(), base64_encode(), demangle(), escapeJSON(), escapeNonprinting(), hexDump(), normalizeLongitude(), PDAL_DLL, portable_pclose(), portable_popen(), replaceAll(), run_shell_command(), screenWidth(), wordWrap(), and wordWrap2().
int pdal::Utils::cksum (char * buf, size_t size)
Generate a checksum that is the integer sum of the values of the bytes in a buffer.
Parameters
buf Pointer to buffer.
size Size of buffer.
Returns
Generated checksum.
Definition at line 206 of file Utils.hpp.
References eatwhitespace(), getenv(), pdal::Dimension::name(), PDAL_DLL, setenv(), trimLeading(), trimTrailing(), and unsetenv().
template<class T > PDAL_DLL const T& pdal::Utils::clamp (const T & t, const T & min, const T & max)
Clamp value to given bounds.
Clamps the input value t to bounds specified by min and max. Used to ensure that row and column indices remain within valid bounds.
Parameters
t the input value.
min the lower bound.
max the upper bound.
Returns
the value to clamped to the given bounds.
Definition at line 78 of file Utils.hpp.
References normal(), PDAL_DLL, random(), random_seed(), and uniform().
Referenced by pdal::eigen::computeSpline(), pdal::eigen::createMaxMatrix(), pdal::eigen::createMinMatrix(), pdal::eigen::extendedLocalMinimum(), pdal::eigen::matrixClose(), pdal::eigen::matrixOpen(), and pdal::MongusFilter::processGround().
void PDAL_DLL pdal::Utils::closeFile (std::ostream * out)
Close an output stream.
Parameters
out Stream to close.
Definition at line 323 of file PDALUtils.cpp.
References closeFile().
Referenced by pdal::SQLiteReader::addDimensions(), pdal::connect(), Support::diff_files(), Support::diff_text_files(), pdal::PlyWriter::done(), pdal::PtsReader::done(), pdal::TextReader::done(), pdal::PlyReader::done(), pdal::InfoKernel::dump(), pdal::PipelineKernel::execute(), pdal::TextReader::initialize(), pdal::PtsReader::initialize(), pdal::PlyReader::initialize(), pdal::OciWriter::loadSQLData(), pdal::FileStreamDeleter::operator()(), pdal::PipelineReaderJSON::readPipeline(), pdal::PipelineManager::readPipeline(), pdal::PipelineWriter::writePipeline(), writeProgress(), pdal::LasReader::LasStreamIf::~LasStreamIf(), and pdal::PipelineManager::~PipelineManager().
void PDAL_DLL pdal::Utils::closeFile (std::istream * in)
Close an input stream.
Parameters
out Stream to close.
Definition at line 334 of file PDALUtils.cpp.
Referenced by closeFile().
void pdal::Utils::closeProgress (int fd)
Definition at line 240 of file PDALUtils.hpp.
Referenced by pdal::PipelineKernel::execute().
PDAL_DLL bool pdal::Utils::compare_approx (double v1, double v2, double tolerance)
Determine if two values are within a particular range of each other.
Parameters
v1 First value to compare.
v2 Second value to compare.
tolerance Maximum difference between v1 and v2
Definition at line 126 of file Utils.hpp.
Referenced by TEST(), TEST_F(), and verifyTestView().
double PDAL_DLL pdal::Utils::computeHausdorff (PointViewPtr srcView, PointViewPtr candView)
Definition at line 360 of file PDALUtils.cpp.
References pdal::KDIndex< DIM >::build(), and pdal::KD3Index::knnSearch().
Referenced by pdal::HausdorffKernel::execute(), TEST(), and writeProgress().
template<typename CONTAINER , typename VALUE > bool pdal::Utils::contains (const CONTAINER & cont, const VALUE & val)
Determine if a container contains a value.
Parameters
cont Container.
val Value.
Returns
true if the value is in the container, false otherwise.
Definition at line 55 of file Algorithm.hpp.
Referenced by pdal::TextReader::addDimensions(), pdal::PointView::createMesh(), pdal::LasWriter::fillForwardList(), pdal::LasWriter::handleHeaderForward(), pdal::FerryFilter::initialize(), pdal::PluginManager::libraryLoaded(), pdal::LasError::numReturnsWarning(), pdal::LasWriter::prepared(), pdal::GeoWaveWriter::ready(), pdal::TextWriter::ready(), pdal::LasError::returnNumWarning(), TEST(), pdal::TEST(), TEST_F(), pdal::PointLayout::update(), and pdal::gdal::Raster::validateType().
template<typename KEY , typename VALUE > bool pdal::Utils::contains (const std::map< KEY, VALUE > & c, const KEY & v)
Determine if a map contains a key.
Parameters
c Map.
v Key value.
Returns
true if the value is in the container, false otherwise.
Definition at line 68 of file Algorithm.hpp.
std::ostream PDAL_DLL * pdal::Utils::createFile (const std::string & path, bool asBinary)
Create a file (may be on a supported remote filesystem).
Parameters
path Path to file to create.
asBinary Whether the file should be written in binary mode.
Returns
Pointer to the created stream, or NULL.
Definition at line 261 of file PDALUtils.cpp.
References a, and tempFilename().
Referenced by pdal::OciReader::addDimensions(), pdal::SQLiteReader::addDimensions(), pdal::InfoKernel::dump(), pdal::PipelineKernel::execute(), pdal::TextWriter::initialize(), pdal::Log::Log(), pdal::PlyWriter::ready(), pdal::LasWriter::readyFile(), pdal::PipelineWriter::writePipeline(), and writeProgress().
std::string pdal::Utils::demangle (const std::string & s)
Demangle a C++ symbol into readable form.
Parameters
s String to demangle.
Returns
Demangled symbol.
Demangle strings using the compiler-provided demangle function.
Parameters
[in] s String to be demangled.
Returns
Demangled string
Definition at line 538 of file Utils.cpp.
Referenced by backtrace(), base64_encode(), and typeidName().
bool pdal::Utils::eatcharacter (std::istream & s, char x)
If specified character is at the current stream position, advance the stream position by 1.
Parameters
s Stream to insect.
x Character to check for.
Returns
true if the character is at the current stream position, false otherwise.
Definition at line 180 of file Utils.cpp.
References c.
Referenced by trim().
void pdal::Utils::eatwhitespace (std::istream & s)
Skip stream input until a non-space character is found.
Parameters
s Stream to process.
Definition at line 136 of file Utils.cpp.
References c.
Referenced by cksum().
std::string pdal::Utils::escapeJSON (const std::string & s)
Add escape characters or otherwise transform an input string so as to be a valid JSON string.
Parameters
s Input string.
Returns
Valid JSON version of input string.
Definition at line 423 of file Utils.cpp.
References c, and remove_if().
Referenced by base64_encode(), and pdal::MetadataNode::jsonValue().
std::string pdal::Utils::escapeNonprinting (const std::string & s)
Escape non-printing characters by using standard notation (i.e.
) or hex notation () as as necessary.
Parameters
s String to modify.
Returns
Copy of input string with non-printing characters converted to printable notation.
Definition at line 566 of file Utils.cpp.
Referenced by base64_encode(), and TEST().
template<typename PREDICATE > PDAL_DLL std::string::size_type pdal::Utils::extract (const std::string & s, std::string::size_type p, PREDICATE pred)
Count the number of characters in a string that meet a predicate.
Parameters
s String in which to start counting characters.
p Position in input string at which to start counting.
pred Unary predicate that tests a character.
Returns
Then number of characters matching the predicate.
Definition at line 453 of file Utils.hpp.
References PDAL_DLL.
Referenced by pcl::Pipeline< PointT >::applyApproximateProgressiveMorphologicalFilter(), pcl::Pipeline< PointT >::applyProgressiveMorphologicalFilter(), pdal::Dimension::extractName(), extractSpaces(), pdal::PlyReader::nextWord(), pdal::Option::parse(), pdal::Stage::parseName(), pdal::Kernel::parseStageOption(), pdal::Stage::parseTagName(), and pdal::PlyReader::readLine().
template<typename INPUT > Everything pdal::Utils::extractDim (INPUT & ext, Dimension::Type type)
Definition at line 114 of file PDALUtils.hpp.
References pdal::Everything::d, pdal::Everything::f, pdal::Dimension::None, pdal::Everything::s16, pdal::Everything::s32, pdal::Everything::s64, pdal::Everything::s8, pdal::Everything::u16, pdal::Everything::u32, pdal::Everything::u64, and pdal::Everything::u8.
Referenced by pdal::LasReader::loadExtraDims(), pdal::PlyReader::SimpleProperty::read(), and pdal::PlyReader::ListProperty::read().
PDAL_DLL std::string::size_type pdal::Utils::extractSpaces (const std::string & s, std::string::size_type p)
Count the number of characters spaces in a string at a position.
Parameters
s String in which to start counting characters.
p Position in input string at which to start counting.
Returns
Then number of space-y characters matching the predicate.
Definition at line 469 of file Utils.hpp.
References extract().
Referenced by pdal::Options::fromFile(), pdal::PlyReader::nextWord(), pdal::AssignRange::parse(), pdal::anonymous_namespace{ColorizationFilter.cpp}::parseDim(), and pdal::DimRange::subParse().
bool PDAL_DLL pdal::Utils::fileExists (const std::string & path)
Check to see if a file exists.
Parameters
path Path to file.
Returns
Whether the file exists or not.
Definition at line 346 of file PDALUtils.cpp.
References a.
Referenced by pdal::connect(), pdal::OciWriter::createPCEntry(), Support::diff_files(), Support::diff_text_files(), pdal::PipelineKernel::execute(), pdal::OciWriter::loadSQLData(), pdal::InfoKernel::makePipeline(), pdal::OciWriter::runFileSQL(), and writeProgress().
template<typename T > bool pdal::Utils::fromString (const std::string & from, T *& to)
Definition at line 879 of file Utils.hpp.
Referenced by pdal::convert(), pdal::InfoKernel::dumpQuery(), pdal::PtsReader::initialize(), pdal::Ilvis2Reader::initialize(), pdal::operator>>(), pdal::anonymous_namespace{InfoKernel.cpp}::parseInt(), pdal::TextReader::processOne(), pdal::PtsReader::read(), pdal::SQLiteReader::readPatch(), pdal::BpfHeader::readV3(), pdal::TArg< T >::setValue(), pdal::VArg< T >::setValue(), TEST(), and pdal::MetadataNode::value().
template<typename T > bool pdal::Utils::fromString (const std::string & from, T & to)
Convert a string to a value by reading from a string stream.
Parameters
from String to convert.
to Converted value.
Returns
true if the conversion was successful, false otherwise.
Definition at line 902 of file Utils.hpp.
template<> bool pdal::Utils::fromString (const std::string & from, std::string & to)
Definition at line 912 of file Utils.hpp.
template<> bool pdal::Utils::fromString< char > (const std::string & s, char & to)
Convert a numeric string to a char numeric value.
s String to convert.
Parameters
to Converted numeric value.
Returns
true if the conversion was successful, false otherwise.
Definition at line 926 of file Utils.hpp.
template<> bool pdal::Utils::fromString< double > (const std::string & s, double & d)
Specialization conversion from string to double to handle Nan.
Parameters
s String to be converted.
d Converted value.
Returns
true if the conversion was successful, false otherwise.
Definition at line 1021 of file Utils.hpp.
template<> bool pdal::Utils::fromString< Eigen::MatrixXd > (const std::string & s, Eigen::MatrixXd & matrix)
Definition at line 957 of file EigenUtils.hpp.
template<> bool pdal::Utils::fromString< signed char > (const std::string & s, signed char & to)
Convert a numeric string to a signed char numeric value.
s String to convert.
Parameters
to Converted numeric value.
Returns
true if the conversion was successful, false otherwise.
Definition at line 990 of file Utils.hpp.
template<> bool pdal::Utils::fromString< unsigned char > (const std::string & s, unsigned char & to)
Convert a numeric string to an unsigned char numeric value.
s String to convert.
Parameters
to Converted numeric value.
Returns
true if the conversion was successful, false otherwise.
Definition at line 957 of file Utils.hpp.
int pdal::Utils::getenv (std::string const & name, std::string & val)
Fetch the value of an environment variable.
Parameters
name Name of environment varaible.
name Value of the environemnt variable if it exists, empty otherwise.
Returns
0 on success, -1 on failure
Definition at line 105 of file Utils.cpp.
Referenced by cksum(), pdal::anonymous_namespace{PluginManager.cpp}::pluginSearchPaths(), TEST(), and pdal::TEST().
std::string pdal::Utils::hexDump (const char * buf, size_t count)
Convert an input buffer to a hexadecimal string representation similar to the output of the UNIX command 'od'. This is mostly used as an occasional debugging aid.
Parameters
buf Point to buffer to dump.
count Size of buffer.
Returns
Buffer converted to hex string.
Definition at line 667 of file Utils.cpp.
References bytes.
Referenced by base64_encode().
bool pdal::Utils::iequals (const std::string & s, const std::string & s2)
Compare strings in a case-insensitive manner.
Parameters
s First string to compare.
s2 Second string to compare.
Returns
Whether the strings are equal.
Definition at line 174 of file Utils.hpp.
References toupper().
Referenced by pcl::Pipeline< PointT >::applyFilter(), pdal::OciWriter::blockTableExists(), pdal::SQLite::doesTableExist(), pdal::GetFullVersionString(), pdal::StageFactory::inferReaderDriver(), pdal::PluginManager::l_loadPlugin(), pdal::MrsidReader::LayoutToPointInfo(), pdal::XMLSchema::load(), pdal::XMLSchema::loadMetadata(), pdal::Log::Log(), pdal::operator>>(), pdal::MrsidReader::read(), pdal::SQLiteReader::readPatch(), pdal::XMLSchema::remapOldNames(), pdal::LocateFilter::run(), pdal::OutlierFilter::run(), pdal::OciWriter::shutOff_SDO_PC_Trigger(), TEST(), pdal::Option::toMetadata(), and pdal::Options::toMetadata().
template<typename T_OUT > bool pdal::Utils::inRange (double in)
Determine whether a double value may be safely converted to the given output type without over/underflow. If the output type is integral the input will be rounded before being tested.
Parameters
in Value to range test.
Returns
Whether value can be safely converted to template type.
Definition at line 681 of file Utils.hpp.
References sround().
template<typename T_IN , typename T_OUT > bool pdal::Utils::inRange (T_IN in)
Determine whether a value may be safely converted to the given output type without over/underflow. If the output type is integral and different from the input time, the value will be rounded before being tested.
Parameters
in Value to range test.
Returns
Whether value can be safely converted to template type.
Definition at line 703 of file Utils.hpp.
template<typename OUTPUT > void pdal::Utils::insertDim (OUTPUT & ins, Dimension::Type type, const Everything & e)
Definition at line 159 of file PDALUtils.hpp.
References pdal::Everything::d, pdal::Everything::f, pdal::Dimension::None, pdal::Everything::s16, pdal::Everything::s32, pdal::Everything::s64, pdal::Everything::s8, pdal::Everything::u16, pdal::Everything::u32, pdal::Everything::u64, and pdal::Everything::u8.
Referenced by pdal::LasWriter::fillPointBuf(), pdal::LasWriter::writeLasZipBuf(), and pdal::PlyWriter::writeValue().
std::vector<std::string> PDAL_DLL pdal::Utils::maybeGlob (const std::string & path)
Referenced by writeProgress().
double pdal::Utils::normal (const double & mean, const double & sigma, uint32_t seed)
Generate values in a normal distribution in the range [minimum, maximum] using the provided seed value.
Parameters
double Lower value of range for random number generation.
double Upper value of range for random number generation.
seed Seed value for random number generation.
Definition at line 96 of file Utils.cpp.
Referenced by clamp(), pdal::NormalFilter::filter(), and pdal::FauxReader::processOne().
double pdal::Utils::normalizeLongitude (double longitude)
Normalize longitude so that it's between (-180, 180].
Parameters
longitude Longitude to normalize.
Returns
Normalized longitude.
Definition at line 595 of file Utils.cpp.
Referenced by base64_encode(), pdal::SpatialReference::calculateZone(), pdal::IcebridgeReader::read(), and pdal::Ilvis2Reader::readPoint().
template<typename T_IN , typename T_OUT > bool pdal::Utils::numericCast (T_IN in, T_OUT & out)
Convert a numeric value from one type to another. Floating point values are rounded to the nearest integer before a conversion is attempted.
Parameters
in Value to convert.
out Converted value.
Returns
true if the conversion was successful, false if the datatypes/input value don't allow conversion.
Definition at line 720 of file Utils.hpp.
References sround().
Referenced by pdal::PointView::convertAndSet(), pdal::LasWriter::fillPointBuf(), pdal::PointRef::getFieldAs(), pdal::PointView::getFieldAs(), pdal::gdal::Band< T >::getNoData(), pdal::MrsidReader::inspect(), pdal::LasReader::inspect(), pdal::DbWriter::readField(), pdal::DbWriter::readPoint(), pdal::PointRef::setField(), pdal::BpfHeader::write(), pdal::gdal::Band< T >::writeBlock(), and pdal::LasWriter::writeLasZipBuf().
std::istream PDAL_DLL * pdal::Utils::openFile (const std::string & path, bool asBinary)
Open a file (potentially on a remote filesystem).
Parameters
path Path (potentially remote) of file to open.
asBinary Whether the file should be opened binary.
Returns
Pointer to stream opened for input.
Definition at line 298 of file PDALUtils.cpp.
References a, and tempFilename().
Referenced by pdal::connect(), Support::diff_files(), Support::diff_text_files(), pdal::TextReader::initialize(), pdal::PtsReader::initialize(), pdal::OptechReader::initialize(), pdal::PlyReader::initialize(), pdal::LasReader::LasStreamIf::LasStreamIf(), pdal::OciWriter::loadSQLData(), pdal::PipelineReaderJSON::readPipeline(), pdal::PipelineManager::readPipeline(), pdal::PtsReader::ready(), pdal::TextReader::ready(), pdal::PlyReader::ready(), and writeProgress().
int pdal::Utils::openProgress (const std::string & filename)
Definition at line 223 of file PDALUtils.hpp.
References printError().
Referenced by pdal::PipelineKernel::execute().
int pdal::Utils::portable_pclose (FILE * fp)
Close file opened with portable_popen.
Parameters
fp Pointer to file to close.
Returns
0 on success, -1 on failure.
Definition at line 353 of file Utils.cpp.
Referenced by base64_encode(), and run_shell_command().
FILE * pdal::Utils::portable_popen (const std::string & command, const std::string & mode)
Start a process to run a command and open a pipe to which input can be written and from which output can be read.
Parameters
command Command to run in subprocess. Either 'r', 'w' or 'r+' to specify if the pipe should be opened as read-only, write-only or read-write.
Returns
Pointer to FILE for input/output from the subprocess.
Definition at line 342 of file Utils.cpp.
References replaceAll().
Referenced by base64_encode(), and run_shell_command().
void pdal::Utils::printError (const std::string & s)
Definition at line 64 of file PDALUtils.hpp.
Referenced by pdal::Kernel::doExecution(), App::execute(), pdal::Kernel::innerRun(), pdal::Option::nameValid(), openProgress(), and pdal::Kernel::run().
double pdal::Utils::random (double minimum, double maximum)
Generate a random value in the range [minimum, maximum].
Parameters
minimum Lower value of range for random number generation.
maximum Upper value of range for random number generation.
Definition at line 72 of file Utils.cpp.
Referenced by clamp(), pdal::FauxReader::processOne(), and TEST().
void pdal::Utils::random_seed (unsigned int seed)
Set a seed for random number generation.
Parameters
seed Seed value.
Definition at line 66 of file Utils.cpp.
Referenced by clamp(), and TEST().
RedirectStream pdal::Utils::redirect (std::ostream & out, std::ostream & dst)
Redirect a stream to some other stream, by default a null stream.
Parameters
out Stream to redirect.
dst Destination stream.
Returns
Context for stream restoration (see restore()).
Definition at line 611 of file Utils.hpp.
References pdal::Utils::RedirectStream::m_buf.
Referenced by TEST().
RedirectStream pdal::Utils::redirect (std::ostream & out)
Redirect a stream to a null stream.
Parameters
out Stream to redirect.
Returns
Context for stream restoration (see restore()).
Definition at line 626 of file Utils.hpp.
References pdal::Utils::RedirectStream::m_buf, and pdal::Utils::RedirectStream::m_null.
RedirectStream pdal::Utils::redirect (std::ostream & out, const std::string & file)
Redirect a stream to some file.
Parameters
out Stream to redirect.
file Name of file where stream should be redirected.
Returns
Context for stream restoration (see restore()).
Definition at line 642 of file Utils.hpp.
References pdal::Utils::RedirectStream::m_buf, and pdal::Utils::RedirectStream::m_out.
template<typename CONTAINER , typename VALUE > void pdal::Utils::remove (CONTAINER & cont, const VALUE & val)
Remove all instances of a value from a container.
Parameters
cont Container.
v Value to remove.
Definition at line 80 of file Algorithm.hpp.
Referenced by pdal::FileUtils::deleteFile(), pdal::TextReader::fillFields(), pdal::PipelineManager::leaves(), and pdal::PipelineManager::replace().
template<typename CONTAINER , typename PREDICATE > void pdal::Utils::remove_if (CONTAINER & cont, PREDICATE p)
Remove all instances matching a unary predicate from a container.
Parameters
cont Container.
p Predicate indicating whether a value should be removed.
Definition at line 93 of file Algorithm.hpp.
Referenced by pdal::LasWriter::deleteVlr(), escapeJSON(), pdal::anonymous_namespace{InfoKernel.cpp}::getListOfPoints(), and pdal::LasHeader::removeVLR().
std::string pdal::Utils::replaceAll (std::string input, const std::string & replaceWhat, const std::string & replaceWithWhat)
Replace all instances of one string found in the input with another value.
Parameters
input Input string to modify.
replaceWhat Token to locate in input string.
replaceWithWhat Replacement for found tokens.
Returns
Modified version of input string.
Definition at line 404 of file Utils.cpp.
Referenced by base64_encode(), pdal::anonymous_namespace{PipelineWriter.cpp}::generateTag(), normalize(), pdal::pg_quote_identifier(), pdal::pg_quote_literal(), portable_popen(), and TEST().
void pdal::Utils::restore (std::ostream & out, RedirectStream & redir)
Restore a stream redirected with redirect().
Parameters
out Stream to be restored.
redir RedirectStream returned from corresponding redirect() call.
Definition at line 659 of file Utils.hpp.
References pdal::Utils::RedirectStream::m_buf, and pdal::Utils::RedirectStream::m_out.
Referenced by TEST().
int pdal::Utils::run_shell_command (const std::string & cmd, std::string & output)
Create a subprocess and set the standard output of the command into the provided output string.
Parameters
cmd Command to run.
output String to which output from the command should be written,
Definition at line 379 of file Utils.cpp.
References portable_pclose(), and portable_popen().
Referenced by appName(), base64_encode(), anonymous_namespace{pcpipelineTestJSON.cpp}::run_pipeline(), run_pipeline(), anonymous_namespace{pcpipelineTestJSON.cpp}::run_pipeline_stdin(), runTranslate(), TEST(), and pdal::TEST().
int pdal::Utils::screenWidth ()
Return the screen width of an associated tty.
Returns
The tty screen width or 80 if on Windows or it can't be determined.
Definition at line 552 of file Utils.cpp.
Referenced by base64_encode(), pdal::getPDALDebugInformation(), App::outputDrivers(), pdal::nitfwrap::anonymous_namespace{NitfWrap.cpp}::outputHelp(), and pdal::Kernel::outputHelp().
int pdal::Utils::setenv (const std::string & env, const std::string & val)
Set the value of an environment variable.
Parameters
env Name of environment variable.
val Value of environment variable.
Returns
0 on success, -1 on failure
Definition at line 116 of file Utils.cpp.
Referenced by cksum(), and pdal::TEST().
std::vector< std::string > pdal::Utils::simpleWordexp (const std::string & s)
Perform shell-style word expansion (break a string into arguments). This only does simple handling of quoted values and backslashes and doesn't support fancier shell behavior. Use the real wordexp() if you need all that. The behavior of escaped values in a string was surprising to me, so try the shell first if you think you've found a problem.
Parameters
s Input string to parse.
Returns
List of arguments.
Definition at line 701 of file Utils.cpp.
Referenced by pdal::Options::fromCmdlineFile(), split2(), and TEST().
template<typename PREDICATE > PDAL_DLL std::vector<std::string> pdal::Utils::split (const std::string & s, PREDICATE p)
Split a string into substrings based on a predicate. Characters matching the predicate are discarded.
Parameters
s String to split.
p Unary predicate that returns true to indicate that a character is a split location.
Returns
Substrings.
Definition at line 482 of file Utils.hpp.
Referenced by pdal::ChipperFilter::ChipperFilter(), pdal::TextReader::fillFields(), pdal::anonymous_namespace{InfoKernel.cpp}::getListOfPoints(), pdal::TextReader::initialize(), pdal::FerryFilter::initialize(), split(), pdal::ProgramArgs::splitName(), TEST(), and writeData().
PDAL_DLL std::vector<std::string> pdal::Utils::split (const std::string & s, char tChar)
Split a string into substrings based a splitting character. The splitting characters are discarded.
Parameters
s String to split.
p Character indicating split positions.
Returns
Substrings.
Definition at line 548 of file Utils.hpp.
References c, PDAL_DLL, and split().
template<typename PREDICATE > PDAL_DLL std::vector<std::string> pdal::Utils::split2 (const std::string & s, PREDICATE p)
Split a string into substrings. Characters matching the predicate are discarded, as are empty strings otherwise produced by split().
Parameters
s String to split.
p Predicate returns true if a char in a string is a split location.
Returns
Vector of substrings.
Definition at line 515 of file Utils.hpp.
References PDAL_DLL.
Referenced by pdal::InfoKernel::dumpQuery(), pdal::DimBuilder::extractDim(), pdal::TextReader::fillFields(), App::findKernel(), pdal::anonymous_namespace{InfoKernel.cpp}::getListOfPoints(), pdal::Kernel::getShortName(), pdal::PluginManager::guessLoadByPath(), pdal::TextReader::initialize(), pdal::PluginManager::l_loadPlugin(), pdal::LasUtils::parse(), pdal::LasUtils::parseIgnoreVLRs(), pdal::anonymous_namespace{PluginManager.cpp}::pluginSearchPaths(), pdal::Ilvis2Reader::processOne(), pdal::MyReader::read(), pdal::PtsReader::read(), pdal::TextWriter::ready(), pdal::VArg< std::string >::setValue(), split2(), TEST(), pdal::gdal::Raster::validateType(), and pdal::NitfFileWriter::write().
PDAL_DLL std::vector<std::string> pdal::Utils::split2 (const std::string & s, char tChar)
Split a string into substrings based a splitting character. The splitting characters are discarded as are empty strings otherwise produced by split().
Parameters
s String to split.
p Character indicating split positions.
Returns
Substrings.
Definition at line 564 of file Utils.hpp.
References c, PDAL_DLL, simpleWordexp(), and split2().
double pdal::Utils::sround (double r)
Round double value to nearest integral value.
Parameters
r Value to round
Returns
Rounded value
Definition at line 138 of file Utils.hpp.
Referenced by pdal::Tree::getPoints(), pdal::QuadIndex::QImpl::getPoints(), inRange(), and numericCast().
bool pdal::Utils::startsWith (const std::string & s, const std::string & prefix)
Determine if a string starts with a particular prefix.
Parameters
s String to check for prefix.
prefix Prefix to search for.
Returns
Whether the string begins with the prefix.
Definition at line 191 of file Utils.hpp.
Referenced by pdal::LasWriter::addForwardVlrs(), pdal::LasWriter::findVlrMetadata(), main(), pdal::TranslateKernel::makeArgPipeline(), pdal::PipelineReaderJSON::parsePipeline(), pdal::anonymous_namespace{PluginManager.cpp}::pluginTypeValid(), and TEST().
double pdal::Utils::toDouble (const Everything & e, Dimension::Type type)
Definition at line 70 of file PDALUtils.hpp.
References pdal::Everything::d, pdal::Everything::f, pdal::Everything::s16, pdal::Everything::s32, pdal::Everything::s64, pdal::Everything::s8, pdal::Everything::u16, pdal::Everything::u32, pdal::Everything::u64, and pdal::Everything::u8.
Referenced by pdal::PointRef::getFieldAs(), pdal::LasReader::loadExtraDims(), pdal::PlyReader::ListProperty::read(), and pdal::DbReader::writeField().
std::string PDAL_DLL pdal::Utils::toJSON (const MetadataNode & m)
Definition at line 153 of file PDALUtils.cpp.
References toJSON().
Referenced by pdal::LasWriter::addMetadataVlr(), pdal::plang::Invocation::begin(), pdal::PipelineKernel::execute(), pdal::HausdorffKernel::execute(), pdal::TranslateKernel::execute(), pdal::InfoKernel::execute(), pdal::DeltaKernel::execute(), pdal::PipelineExecutor::getMetadata(), pdal::PipelineExecutor::getSchema(), pdal::mlang::Script::setMatlabStruct(), pdal::PipelineWriter::writePipeline(), and writeProgress().
void PDAL_DLL pdal::Utils::toJSON (const MetadataNode & m, std::ostream & o)
Definition at line 161 of file PDALUtils.cpp.
References pdal::anonymous_namespace{PDALUtils.cpp}::arrayToJSON(), pdal::MetadataNode::children(), pdal::MetadataNode::kind(), pdal::MetadataNode::name(), and pdal::anonymous_namespace{PDALUtils.cpp}::subnodesToJSON().
Referenced by pdal::anonymous_namespace{PDALUtils.cpp}::subnodesToJSON(), and toJSON().
std::string pdal::Utils::tolower (const std::string & s)
Convert a string to lowercase.
Returns
Converted string.
Definition at line 146 of file Utils.hpp.
Referenced by pdal::SQLiteWriter::CreateBlockTable(), pdal::SQLiteWriter::CreateCloud(), pdal::SQLiteWriter::CreateCloudTable(), pdal::SQLiteWriter::CreateIndexes(), pdal::SQLiteWriter::DeleteBlockTable(), pdal::SQLiteWriter::DeleteCloudTable(), pdal::RandomKernel::execute(), App::execute(), pdal::getCompressionType(), pdal::StageFactory::inferReaderDriver(), pdal::StageFactory::inferWriterDriver(), pdal::LasWriter::initialize(), pdal::XMLSchema::load(), pdal::PluginManager::loadByPath(), pdal::operator>>(), pdal::PlyWriter::prepared(), TEST(), pdal::Dimension::type(), and pdal::SQLiteWriter::writeInit().
MetadataNode pdal::Utils::toMetadata (const BOX2D & bounds)
Definition at line 201 of file PDALUtils.hpp.
References pdal::MetadataNode::add(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, and pdal::BOX2D::miny.
Referenced by pdal::PointView::clearTemps(), pdal::StatsFilter::extractMetadata(), pdal::Option::getValue(), pdal::SpatialReference::operator<(), and pdal::BasePointTable::supportsView().
MetadataNode pdal::Utils::toMetadata (const BOX3D & bounds)
Definition at line 211 of file PDALUtils.hpp.
References pdal::MetadataNode::add(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
template<typename E > std::underlying_type<E>::type pdal::Utils::toNative (E e)
Return the argument cast to its underlying type. Typically used on an enum.
Parameters
e Variable for which to find the underlying type.
Returns
Converted variable.
Definition at line 1043 of file Utils.hpp.
References pdal::Dimension::type().
Referenced by pdal::GreyhoundReader::addDimensions(), pdal::PointLayout::assignDim(), pdal::Dimension::base(), pdal::PointLayout::dimDetail(), pdal::Log::get(), pdal::PointLayout::hasDim(), pdal::BpfWriter::initialize(), pdal::DbWriter::ready(), pdal::BpfWriter::readyFile(), pdal::PointLayout::registerDim(), pdal::Dimension::size(), and pdal::PointLayout::update().
template<typename T > std::string pdal::Utils::toString (const T & from)
Convert a value to its string representation by writing to a stringstream.
Parameters
from Value to convert.
Returns
String representation.
Definition at line 746 of file Utils.hpp.
Referenced by pdal::column::column(), pdal::TArg< T >::defaultVal(), pdal::TArg< bool >::defaultVal(), pdal::VArg< T >::defaultVal(), pdal::HexBin::done(), pdal::LasWriter::fillHeader(), pdal::LasWriter::fillPointBuf(), pdal::gdal::Band< T >::getNoData(), if(), pdal::BpfReader::initialize(), pdal::TerrasolidReader::initialize(), pdal::LasReader::initializeLocal(), pdal::OciWriter::isGeographic(), anonymous_namespace{ColorinterpFilterTest.cpp}::makeColor(), pdal::Ilvis2Reader::processOne(), pdal::PgWriter::SetupSchema(), pdal::MetadataNodeImpl::setValue(), TEST(), pdal::OciWriter::updatePCExtent(), pdal::nitfwrap::NitfWrap::verifyBpf(), pdal::GeoWaveWriter::write(), pdal::NitfFileWriter::write(), pdal::gdal::Band< T >::writeBlock(), and pdal::LasWriter::writeLasZipBuf().
std::string pdal::Utils::toString (bool from)
Convert a bool to a string.
Definition at line 756 of file Utils.hpp.
std::string pdal::Utils::toString (double from)
Convert a double to string with a precision of 10 decimal places.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 767 of file Utils.hpp.
std::string pdal::Utils::toString (float from)
Convert a float to string with a precision of 10 decimal places.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 780 of file Utils.hpp.
std::string pdal::Utils::toString (long long from)
Convert a long long int to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 793 of file Utils.hpp.
std::string pdal::Utils::toString (unsigned long from)
Convert an unsigned long long int to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 802 of file Utils.hpp.
std::string pdal::Utils::toString (long from)
Convert a long int to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 811 of file Utils.hpp.
std::string pdal::Utils::toString (unsigned int from)
Convert an unsigned int to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 820 of file Utils.hpp.
std::string pdal::Utils::toString (int from)
Convert an int to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 829 of file Utils.hpp.
std::string pdal::Utils::toString (unsigned short from)
Convert an unsigned short to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 838 of file Utils.hpp.
std::string pdal::Utils::toString (short from)
Convert a short int to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 847 of file Utils.hpp.
std::string pdal::Utils::toString (char from)
Convert a char (treated as numeric) to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 856 of file Utils.hpp.
std::string pdal::Utils::toString (unsigned char from)
Convert an unsigned char (treated as numeric) to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 865 of file Utils.hpp.
std::string pdal::Utils::toString (signed char from)
Convert a signed char (treated as numeric) to string.
Parameters
from Value to convert.
Returns
String representation of numeric value.
Definition at line 874 of file Utils.hpp.
std::string pdal::Utils::toupper (const std::string & s)
Convert a string to uppercase.
Returns
Converted string.
Definition at line 159 of file Utils.hpp.
Referenced by pdal::OciReader::defineBlock(), pdal::LasReader::handleCompressionOption(), pdal::Dimension::id(), iequals(), pdal::OciWriter::initialize(), pdal::TextWriter::initialize(), pdal::TIndexKernel::isFileIndexed(), pdal::OciWriter::isGeographic(), pdal::anonymous_namespace{FileUtils.cpp}::isStdin(), pdal::anonymous_namespace{FileUtils.cpp}::isStdout(), pdal::operator<<(), pdal::operator>>(), pdal::OWParseSDO_GEOR_INIT(), pdal::OWReplaceString(), pdal::SQLite::query(), TEST(), and pdal::DimBuilder::writeNameToId().
void pdal::Utils::trim (std::string & s)
Remove whitespace from the beginning and end of a string.
Parameters
s String to be trimmed.
Definition at line 267 of file Utils.hpp.
References base64_encode(), eatcharacter(), PDAL_DLL, pdal::Dimension::size(), trimLeading(), and trimTrailing().
Referenced by pdal::TextReader::addDimensions(), pdal::DimBuilder::extractDim(), pdal::SpatialReference::getHorizontalUnits(), pdal::SpatialReference::getProj4(), pdal::SpatialReference::getVerticalUnits(), if(), pdal::GDALWriter::initialize(), pdal::FerryFilter::initialize(), pdal::operator>>(), pdal::LasUtils::parse(), pdal::LasUtils::parseIgnoreVLRs(), pdal::TextWriter::ready(), pdal::VArg< std::string >::setValue(), pdal::PgReader::Patch::update_binary(), pdal::NitfFileWriter::write(), and pdal::MetadataReader::writeField().
void pdal::Utils::trimLeading (std::string & s)
Remove whitspace from the beginning of a string.
Parameters
s String to be trimmed.
Definition at line 150 of file Utils.cpp.
Referenced by backtrace(), cksum(), TEST(), and trim().
void pdal::Utils::trimTrailing (std::string & s)
Remove whitspace from the end of a string.
Parameters
s String to be trimmed.
Definition at line 160 of file Utils.cpp.
Referenced by backtrace(), cksum(), pdal::SQLite::execute(), pdal::BpfUlemFile::read(), pdal::PlyReader::readLine(), TEST(), trim(), and wordWrap().
template<typename T > std::string pdal::Utils::typeidName ()
Return a string representation of a type specified by the template argument.
Returns
String representation of the type.
Definition at line 591 of file Utils.hpp.
References demangle(), and pdal::Dimension::name().
double pdal::Utils::uniform (const double & minimum, const double & maximum, uint32_t seed)
Generate values in a uniform distribution in the range [minimum, maximum] using the provided seed value.
Parameters
double Lower value of range for random number generation.
double Upper value of range for random number generation.
seed Seed value for random number generation.
Definition at line 86 of file Utils.cpp.
Referenced by clamp(), and pdal::FauxReader::processOne().
int pdal::Utils::unsetenv (const std::string & env)
Clear the value of an environment variable.
Parameters
env Name of the environment variable to clear.
Returns
0 on success, -1 on failure
Definition at line 126 of file Utils.cpp.
Referenced by cksum(), and pdal::TEST().
StringList pdal::Utils::wordWrap (std::string const & inputString, size_t lineLength, size_t firstLength = 0)
Break a string into a list of strings to not exceed a specified length. Whitespace is condensed to a single space and each string is free of whitespace at the beginning and end when possible. Optionally, a line length for the first line can be different from subsequent lines.
Parameters
inputString String to split into substrings.
lineLength Maximum length of substrings.
firstLength When non-zero, the maximum length of the first substring. When zero, the first firstLength is assigned the value provided in lineLength.
Returns
List of substrings generated from the input string.
Definition at line 450 of file Utils.cpp.
References trimTrailing().
Referenced by base64_encode(), pdal::ProgramArgs::dump(), pdal::ProgramArgs::dump2(), App::outputDrivers(), and TEST().
StringList pdal::Utils::wordWrap2 (std::string const & inputString, size_t lineLength, size_t firstLength = 0)
Break a string into a list of strings to not exceed a specified length. The concatanation of the returned substrings will yield the original string. The algorithm attempts to break the original string such that each substring begins with a word.
Parameters
inputString String to split into substrings.
lineLength Maximum length of substrings.
firstLength When non-zero, the maximum length of the first substring. When zero, the first firstLength is assigned the value provided in lineLength.
Returns
List of substrings generated from the input string.
Definition at line 491 of file Utils.cpp.
Referenced by base64_encode(), TEST(), and pdal::DimBuilder::writeDescriptions().
void pdal::Utils::writeProgress (int fd, const std::string & type, const std::string & text)
Definition at line 250 of file PDALUtils.hpp.
References closeFile(), computeHausdorff(), createFile(), fileExists(), maybeGlob(), openFile(), PDAL_DLL, and toJSON().
Referenced by pdal::LasWriter::doneFile(), pdal::NitfWriter::readyFile(), pdal::LasWriter::readyFile(), and pdal::LasWriter::writeView().