PDAL: pdal::anonymous_namespace{IcpFilterTest.cpp} Namespace Reference
pdal::anonymous_namespace{IcpFilterTest.cpp} Namespace Reference
Functions
std::unique_ptr< LasReader > newReader ()
std::unique_ptr< IcpFilter > newFilter ()
void checkPointsEqualReader (const PointViewSet &pointViewSet, double tolerance)
Function Documentation
void pdal::anonymous_namespace{IcpFilterTest.cpp}::checkPointsEqualReader (const PointViewSet & pointViewSet, double tolerance)
Definition at line 63 of file IcpFilterTest.cpp.
References newReader(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by pdal::TEST().
std::unique_ptr<IcpFilter> pdal::anonymous_namespace{IcpFilterTest.cpp}::newFilter ()
Definition at line 58 of file IcpFilterTest.cpp.
Referenced by pdal::TEST().
std::unique_ptr<LasReader> pdal::anonymous_namespace{IcpFilterTest.cpp}::newReader ()
Definition at line 49 of file IcpFilterTest.cpp.
References pdal::Options::add(), and Support::datapath().
Referenced by checkPointsEqualReader(), and pdal::TEST().