PDAL: pdal::Segmentation Namespace Reference
pdal::Segmentation Namespace Reference
Functions
std::vector< std::vector< PointId > > extractClusters (PointView &view, uint64_t min_points, uint64_t max_points, double tolerance)
void ignoreDimRange (DimRange dr, PointViewPtr input, PointViewPtr keep, PointViewPtr ignore)
void segmentLastReturns (PointViewPtr input, PointViewPtr last, PointViewPtr other)
Function Documentation
PDAL_DLL std::vector< std::vector< PointId > > pdal::Segmentation::extractClusters (PointView & view, uint64_t min_points, uint64_t max_points, double tolerance)
Extract clusters of points from input PointView.
For each point, find neighbors within a given tolerance (Euclidean distance). If a neighbor already belongs to another cluster, skip it. Otherwise, add it to the current cluster. Recursively visit newly added cluster points, looking for neighbors to add to the cluster.
Parameters
[in] view the input PointView.
[in] min_points the minimum number of points in a cluster.
[in] max_points the maximum number of points in a cluster.
[in] tolerance the tolerance for adding points to a cluster.
Returns
a vector of clusters (themselves vectors of PointIds).
Definition at line 52 of file Segmentation.cpp.
References pdal::KDIndex< DIM >::build(), pdal::KD3Index::radius(), and pdal::PointView::size().
Referenced by pdal::ClusterFilter::filter(), and TEST().
PDAL_DLL void pdal::Segmentation::ignoreDimRange (DimRange dr, PointViewPtr input, PointViewPtr keep, PointViewPtr ignore)
Definition at line 116 of file Segmentation.cpp.
References pdal::PointRef::getFieldAs(), pdal::DimRange::m_id, pdal::PointRef::setPointId(), and pdal::DimRange::valuePasses().
Referenced by pdal::PMFFilter::run(), and pdal::SMRFilter::run().
PDAL_DLL void pdal::Segmentation::segmentLastReturns (PointViewPtr input, PointViewPtr last, PointViewPtr other)
Definition at line 130 of file Segmentation.cpp.
References pdal::PointRef::getFieldAs(), pdal::Dimension::NumberOfReturns, pdal::Dimension::ReturnNumber, and pdal::PointRef::setPointId().
Referenced by pdal::PMFFilter::run(), and pdal::SMRFilter::run().