PDAL: pdal::eigen Namespace Reference
pdal::eigen Namespace Reference
Functions
Eigen::Vector3f computeCentroid (PointView &view, std::vector< PointId > ids)
Eigen::Matrix3f computeCovariance (PointView &view, std::vector< PointId > ids)
uint8_t computeRank (PointView &view, std::vector< PointId > ids, double threshold)
Eigen::MatrixXd computeSpline (Eigen::MatrixXd x, Eigen::MatrixXd y, Eigen::MatrixXd z, Eigen::MatrixXd xx, Eigen::MatrixXd yy)
Eigen::MatrixXd createMinMatrix (PointView &view, int rows, int cols, double cell_size, BOX2D bounds)
Eigen::MatrixXd createMaxMatrix (PointView &view, int rows, int cols, double cell_size, BOX2D bounds)
Eigen::MatrixXd createMaxMatrix2 (PointView &view, int rows, int cols, double cell_size, BOX2D bounds)
Eigen::MatrixXd extendedLocalMinimum (PointView &view, int rows, int cols, double cell_size, BOX2D bounds)
Eigen::MatrixXd matrixClose (Eigen::MatrixXd data, int radius)
Eigen::MatrixXd matrixOpen (Eigen::MatrixXd data, int radius)
std::vector< double > dilateDiamond (std::vector< double > data, size_t rows, size_t cols, int iterations)
std::vector< double > erodeDiamond (std::vector< double > data, size_t rows, size_t cols, int iterations)
Eigen::MatrixXd pointViewToEigen (const PointView &view)
void writeMatrix (Eigen::MatrixXd data, const std::string &filename, const std::string &driver, double cell_size, BOX2D bounds, SpatialReference srs)
Eigen::MatrixXd cleanDSM (Eigen::MatrixXd data)
template<typename Derived >
PDAL_DLL double centralDiffX2 (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double centralDiffY2 (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double centralDiffXY (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double centralDiffX (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double centralDiffY (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL Derived padMatrix (const Eigen::MatrixBase< Derived > &d, int r)
template<typename Derived >
PDAL_DLL Eigen::MatrixXd replaceNaNs (const Eigen::MatrixBase< Derived > &data)
template<typename Derived >
PDAL_DLL Derived gradX (const Eigen::MatrixBase< Derived > &A)
template<typename Derived >
PDAL_DLL Derived gradY (const Eigen::MatrixBase< Derived > &A)
template<typename Derived >
PDAL_DLL double computeContour (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double computeTotal (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double computeProfile (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double computeTangential (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double computeDZDX (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double computeDZDY (const Eigen::MatrixBase< Derived > &data, double spacing)
PDAL_DLL double computeSlopeRad (double dZdX, double dZdY)
template<typename Derived >
PDAL_DLL double computeHillshade (const Eigen::MatrixBase< Derived > &data, double spacing, double illumAltitudeDegree, double illumAzimuthDegree)
template<typename Derived >
PDAL_DLL double computeAspectFD (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double computeAspectD8 (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double computeSlopeD8 (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL double computeSlopeFD (const Eigen::MatrixBase< Derived > &data, double spacing)
template<typename Derived >
PDAL_DLL Derived dilate (const Eigen::MatrixBase< Derived > &A, int radius)
template<typename Derived >
PDAL_DLL Derived erode (const Eigen::MatrixBase< Derived > &A, int radius)
Function Documentation
template<typename Derived > PDAL_DLL double pdal::eigen::centralDiffX (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute first derivative in X direction using central difference method.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing of the matrix.
Returns
the first derivative in X.
Definition at line 170 of file EigenUtils.hpp.
Referenced by computeAspectFD(), computeContour(), computeProfile(), computeSlopeFD(), computeTangential(), and TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::centralDiffX2 (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute second derivative in X direction using central difference method.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing of the matrix.
Returns
the second derivative in X.
Definition at line 114 of file EigenUtils.hpp.
Referenced by computeContour(), computeProfile(), computeTangential(), computeTotal(), and TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::centralDiffXY (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute mixed second derivative of X in the Y direction using central difference method.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing of the matrix.
Returns
the second derivative of X in the Y direction.
Definition at line 151 of file EigenUtils.hpp.
Referenced by computeContour(), computeProfile(), computeTangential(), computeTotal(), and TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::centralDiffY (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute first derivative in Y direction using central difference method.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing of the matrix.
Returns
the first derivative in Y.
Definition at line 188 of file EigenUtils.hpp.
References cleanDSM(), computeRank(), createMaxMatrix(), createMaxMatrix2(), createMinMatrix(), dilateDiamond(), erodeDiamond(), extendedLocalMinimum(), matrixClose(), matrixOpen(), PDAL_DLL, and anonymous_namespace{GreyhoundReaderTest.cpp}::radius.
Referenced by computeAspectFD(), computeContour(), computeProfile(), computeSlopeFD(), computeTangential(), and TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::centralDiffY2 (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute second derivative in Y direction using central difference method.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing of the matrix.
Returns
the second derivative in Y.
Definition at line 132 of file EigenUtils.hpp.
Referenced by computeContour(), computeProfile(), computeTangential(), computeTotal(), and TEST().
PDAL_DLL Eigen::MatrixXd pdal::eigen::cleanDSM (Eigen::MatrixXd data)
Clean a raster.
Parameters
data the Eigen matrix to clean.
Returns
the cleaned raster.
Definition at line 584 of file EigenUtils.cpp.
Referenced by centralDiffY().
template<typename Derived > PDAL_DLL double pdal::eigen::computeAspectD8 (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute aspect using D8 method.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing.
Returns
the local aspect.
Definition at line 721 of file EigenUtils.hpp.
Referenced by TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::computeAspectFD (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute aspect using finite difference method.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing.
Returns
the local aspect.
Definition at line 699 of file EigenUtils.hpp.
References centralDiffX(), centralDiffY(), and replaceNaNs().
Referenced by TEST().
PDAL_DLL Eigen::Vector3f pdal::eigen::computeCentroid (PointView & view, std::vector< PointId > ids)
Compute the centroid of a collection of points.
Computes the 3D centroid of a collection of points (specified by PointId) sampled from the input PointView.
// build 3D kd-tree
KD3Index kdi(view);
kdi.build();
// find the k-nearest neighbors of the first point (k=8)
auto ids = kdi.neighbors(0, 8);
// compute the centroid
auto centroid = computeCentroid(view, ids);
Parameters
view the source PointView.
ids a vector of PointIds specifying a subset of points.
Returns
the 3D centroid of the XYZ dimensions.
Definition at line 55 of file EigenUtils.cpp.
References pdal::PointView::getFieldAs(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by computeCovariance(), and pdal::VoxelCentroidNearestNeighborFilter::run().
template<typename Derived > PDAL_DLL double pdal::eigen::computeContour (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute contour curvature for a single 3x3 matrix.
Parameters
data the incoming Eigen matrix.
spacing the spacing between cells (or edge length of a cell).
Returns
the contour curvature.
Definition at line 497 of file EigenUtils.hpp.
References centralDiffX(), centralDiffX2(), centralDiffXY(), centralDiffY(), centralDiffY2(), and replaceNaNs().
Referenced by TEST().
PDAL_DLL Eigen::Matrix3f pdal::eigen::computeCovariance (PointView & view, std::vector< PointId > ids)
Compute the covariance matrix of a collection of points.
Computes the covariance matrix of a collection of points (specified by PointId) sampled from the input PointView.
// build 3D kd-tree
KD3Index kdi(view);
kdi.build();
// find the k-nearest neighbors of the first point (k=8)
auto ids = kdi.neighbors(0, 8);
// compute the covariance
auto cov = computeCovariance(view, ids);
Parameters
view the source PointView.
ids a vector of PointIds specifying a subset of points.
Returns
the covariance matrix of the XYZ dimensions.
Definition at line 76 of file EigenUtils.cpp.
References computeCentroid(), pdal::PointView::getFieldAs(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by computeRank(), pdal::EigenvaluesFilter::filter(), pdal::ApproximateCoplanarFilter::filter(), and pdal::NormalFilter::filter().
template<typename Derived > PDAL_DLL double pdal::eigen::computeDZDX (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute first derivative in X using 3x3 window.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing.
Returns
the first derivative in X.
Definition at line 597 of file EigenUtils.hpp.
Referenced by computeHillshade(), and TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::computeDZDY (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute first derivative in Y using 3x3 window.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing.
Returns
the first derivative in Y.
Definition at line 616 of file EigenUtils.hpp.
Referenced by computeHillshade(), and TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::computeHillshade (const Eigen::MatrixBase< Derived > & data, double spacing, double illumAltitudeDegree, double illumAzimuthDegree)
Compute hillshade.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing.
illumAltitudeDegree the illumination altitude in degrees.
illumAzimuthDegree the illumination azimuth in degrees.
Returns
the local slope.
Definition at line 643 of file EigenUtils.hpp.
References computeDZDX(), computeDZDY(), and computeSlopeRad().
Referenced by TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::computeProfile (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute profile curvature for a single 3x3 matrix.
Parameters
data the incoming Eigen matrix.
spacing the spacing between cells (or edge length of a cell).
Returns
the profile curvature.
Definition at line 545 of file EigenUtils.hpp.
References centralDiffX(), centralDiffX2(), centralDiffXY(), centralDiffY(), centralDiffY2(), and replaceNaNs().
Referenced by TEST().
PDAL_DLL uint8_t pdal::eigen::computeRank (PointView & view, std::vector< PointId > ids, double threshold)
Compute the rank of a collection of points.
Computes the rank of a collection of points (specified by PointId) sampled from the input PointView. This method uses Eigen's JacobiSVD class to solve the singular value decomposition and to estimate the rank using the given threshold. A singular value will be considered nonzero if its absolute value is greater than the product of the user-supplied threshold and the absolute value of the maximum singular value.
More on JacobiSVD can be found at https://eigen.tuxfamily.org/dox/classEigen_1_1JacobiSVD.html.
// build 3D kd-tree
KD3Index kdi(view);
kdi.build();
// find the k-nearest neighbors of the first point (k=8)
auto ids = kdi.neighbors(0, 8);
// compute the rank using threshold of 0.01
auto rank = computeRank(view, ids, 0.01);
Parameters
view the source PointView.
ids a vector of PointIds specifying a subset of points.
Returns
the estimated rank.
Definition at line 98 of file EigenUtils.cpp.
References B, and computeCovariance().
Referenced by centralDiffY(), and pdal::EstimateRankFilter::filter().
template<typename Derived > PDAL_DLL double pdal::eigen::computeSlopeD8 (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute slope using D8 method.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing.
Returns
the local slope.
Definition at line 772 of file EigenUtils.hpp.
Referenced by TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::computeSlopeFD (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute slope using finite difference method.
Parameters
data the incoming Eigen matrix.
spacing the grid spacing.
Returns
the local slope.
Definition at line 810 of file EigenUtils.hpp.
References centralDiffX(), centralDiffY(), and replaceNaNs().
Referenced by TEST().
PDAL_DLL double pdal::eigen::computeSlopeRad (double dZdX, double dZdY)
Definition at line 628 of file EigenUtils.hpp.
Referenced by computeHillshade(), and TEST().
PDAL_DLL Eigen::MatrixXd pdal::eigen::computeSpline (Eigen::MatrixXd x, Eigen::MatrixXd y, Eigen::MatrixXd z, Eigen::MatrixXd xx, Eigen::MatrixXd yy)
Thin Plate Spline interpolation.
Parameters
x the x coordinate of the input data.
y the y coordinate of the input data.
z the z coordinate of the input data.
xx the x coordinate of the points to be interpolated.
yy the y coordinate of the points to be interpolated.
Returns
the values of the interpolated data at xx and yy.
Definition at line 110 of file EigenUtils.cpp.
References a, b, c, pdal::Utils::clamp(), cs, pdal::Dimension::id(), and anonymous_namespace{GreyhoundReaderTest.cpp}::radius.
Referenced by erode(), and pdal::MongusFilter::processGround().
template<typename Derived > PDAL_DLL double pdal::eigen::computeTangential (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute tangential curvature for a single 3x3 matrix.
Parameters
data the incoming Eigen matrix.
spacing the spacing between cells (or edge length of a cell).
Returns
the tangential curvature.
Definition at line 571 of file EigenUtils.hpp.
References centralDiffX(), centralDiffX2(), centralDiffXY(), centralDiffY(), centralDiffY2(), and replaceNaNs().
Referenced by TEST().
template<typename Derived > PDAL_DLL double pdal::eigen::computeTotal (const Eigen::MatrixBase< Derived > & data, double spacing)
Compute total curvature for a single 3x3 matrix.
Parameters
data the incoming Eigen matrix.
spacing the spacing between cells (or edge length of a cell).
Returns
the total curvature.
Definition at line 523 of file EigenUtils.hpp.
References centralDiffX2(), centralDiffXY(), centralDiffY2(), and replaceNaNs().
Referenced by TEST().
PDAL_DLL Eigen::MatrixXd pdal::eigen::createMaxMatrix (PointView & view, int rows, int cols, double cell_size, BOX2D bounds)
Create matrix of maximum Z values.
Create a DSM from the provided PointVieew, where each cell contains the maximum Z value of all contributing elevations.
Parameters
view the input PointView.
rows the number of rows.
cols the number of columns.
cell_size the edge length of raster cell.
bounds the 2D bounds of the PointView.
Returns
the matrix of maximum Z values.
Definition at line 235 of file EigenUtils.cpp.
References c, pdal::Utils::clamp(), pdal::PointView::getFieldAs(), pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::PointView::size(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by centralDiffY().
PDAL_DLL Eigen::MatrixXd pdal::eigen::createMaxMatrix2 (PointView & view, int rows, int cols, double cell_size, BOX2D bounds)
Definition at line 260 of file EigenUtils.cpp.
References pdal::KDIndex< DIM >::build(), c, pdal::PointView::getFieldAs(), pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::KD2Index::radius(), pdal::Dimension::Z, and z.
Referenced by centralDiffY().
PDAL_DLL Eigen::MatrixXd pdal::eigen::createMinMatrix (PointView & view, int rows, int cols, double cell_size, BOX2D bounds)
Create matrix of minimum Z values.
Create a DTM from the provided PointVieew, where each cell contains the minimum Z value of all contributing elevations.
Parameters
view the input PointView.
rows the number of rows.
cols the number of columns.
cell_size the edge length of raster cell.
bounds the 2D bounds of the PointView.
Returns
the matrix of minimum Z values.
Definition at line 210 of file EigenUtils.cpp.
References c, pdal::Utils::clamp(), pdal::PointView::getFieldAs(), pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::PointView::size(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by centralDiffY().
template<typename Derived > PDAL_DLL Derived pdal::eigen::dilate (const Eigen::MatrixBase< Derived > & A, int radius)
Perform a morphological dilation of the input matrix.
Performs a morphological dilation of the input matrix using a circular structuring element of given radius.
Parameters
data the input matrix.
radius the radius of the circular structuring element.
Returns
the morphological dilation of the input matrix.
Definition at line 835 of file EigenUtils.hpp.
References B, c, pdal::Constant, and anonymous_namespace{GreyhoundReaderTest.cpp}::radius.
Referenced by TEST().
PDAL_DLL std::vector< double > pdal::eigen::dilateDiamond (std::vector< double > data, size_t rows, size_t cols, int iterations)
Perform a morphological dilation of the input raster.
Performs a morphological dilation of the input raster using a diamond structuring element. Larger structuring elements are approximated by applying multiple iterations of the opening operation. The input and output rasters are stored in column major order.
Parameters
data the input raster.
rows the number of rows.
cols the number of cols.
iterations the number of iterations used to approximate a larger structuring element.
Returns
the morphological dilation of the input raster.
Definition at line 471 of file EigenUtils.cpp.
Referenced by centralDiffY(), pdal::SMRFilter::createZInet(), pdal::PMFFilter::processGround(), pdal::SMRFilter::progressiveFilter(), and TEST().
template<typename Derived > PDAL_DLL Derived pdal::eigen::erode (const Eigen::MatrixBase< Derived > & A, int radius)
Perform a morphological erosion of the input matrix.
Performs a morphological erosion of the input matrix using a circular structuring element of given radius.
Parameters
data the input matrix.
radius the radius of the circular structuring element.
Returns
the morphological erosion of the input matrix.
Definition at line 888 of file EigenUtils.hpp.
References B, c, computeSpline(), pdal::Constant, PDAL_DLL, anonymous_namespace{GreyhoundReaderTest.cpp}::radius, and z.
Referenced by TEST().
PDAL_DLL std::vector< double > pdal::eigen::erodeDiamond (std::vector< double > data, size_t rows, size_t cols, int iterations)
Perform a morphological erosion of the input raster.
Performs a morphological erosion of the input raster using a diamond structuring element. Larger structuring elements are approximated by applying multiple iterations of the opening operation. The input and output rasters are stored in column major order.
Parameters
data the input raster.
rows the number of rows.
cols the number of cols.
iterations the number of iterations used to approximate a larger structuring element.
Returns
the morphological erosion of the input raster.
Definition at line 505 of file EigenUtils.cpp.
Referenced by centralDiffY(), pdal::SMRFilter::createZInet(), pdal::PMFFilter::processGround(), pdal::SMRFilter::progressiveFilter(), and TEST().
PDAL_DLL Eigen::MatrixXd pdal::eigen::extendedLocalMinimum (PointView & view, int rows, int cols, double cell_size, BOX2D bounds)
Find local minimum elevations by extended local minimum.
Extended local minimum can be used to select seed points for ground return segmentation. Several low-lying points are considered for each grid cell. The difference between the lowest and second lowest points is evaluated and, if the difference exceeds 1.0, the lowest points is considered an outlier. The process continues with the next pair of lowest points (second and third lowest). When the points under consideration are within the given tolerance, the lowest is retained as a seed point.
Parameters
view the input PointView.
rows the number of rows.
cols the cnumber of columns.
cell_size the edge length of raster cell.
bounds the 2D bounds of the PointView.
Returns
the matrix of minimum Z values (ignoring low outliers).
Definition at line 298 of file EigenUtils.cpp.
References c, pdal::Utils::clamp(), pdal::PointView::getFieldAs(), pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::PointView::size(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by centralDiffY().
template<typename Derived > PDAL_DLL Derived pdal::eigen::gradX (const Eigen::MatrixBase< Derived > & A)
Compute the numerical gradient in the X direction.
This is meant to mimic MATLAB's gradient function. The spacing between points in each direction is assumed to be one.
Parameters
data the input matrix.
Returns
the X component of the two-dimensional gradient.
Definition at line 449 of file EigenUtils.hpp.
Referenced by pdal::SMRFilter::classifyGround(), and TEST().
template<typename Derived > PDAL_DLL Derived pdal::eigen::gradY (const Eigen::MatrixBase< Derived > & A)
Compute the numerical gradient in the Y direction.
This is meant to mimic MATLAB's gradient function. The spacing between points in each direction is assumed to be one.
Parameters
data the input matrix.
Returns
the Y component of the two-dimensional gradient.
Definition at line 474 of file EigenUtils.hpp.
Referenced by pdal::SMRFilter::classifyGround(), and TEST().
PDAL_DLL Eigen::MatrixXd pdal::eigen::matrixClose (Eigen::MatrixXd data, int radius)
Perform a morphological closing of the input matrix.
Performs a morphological closing of the input matrix using a circular structuring element of given radius. Data will be symmetrically padded at its edges.
Parameters
data the input matrix.
radius the radius of the circular structuring element.
Returns
the morphological closing of the input radius.
Definition at line 349 of file EigenUtils.cpp.
References c, pdal::Utils::clamp(), cs, and padMatrix().
Referenced by centralDiffY(), and pdal::MongusFilter::processGround().
PDAL_DLL Eigen::MatrixXd pdal::eigen::matrixOpen (Eigen::MatrixXd data, int radius)
Perform a morphological opening of the input matrix.
Performs a morphological opening of the input matrix using a circular structuring element of given radius. Data will be symmetrically padded at its edges.
Parameters
data the input matrix.
radius the radius of the circular structuring element.
Returns
the morphological opening of the input radius.
Definition at line 410 of file EigenUtils.cpp.
References c, pdal::Utils::clamp(), cs, and padMatrix().
Referenced by centralDiffY(), and pdal::MongusFilter::processGround().
template<typename Derived > PDAL_DLL Derived pdal::eigen::padMatrix (const Eigen::MatrixBase< Derived > & d, int r)
Pad input matrix symmetrically.
Symmetrically pads the input matrix with given radius.
Parameters
d the input matrix.
r the radius of the padding.
Returns
the padded matrix.
Definition at line 368 of file EigenUtils.hpp.
References PDAL_DLL, and pointViewToEigen().
Referenced by matrixClose(), matrixOpen(), and TEST().
PDAL_DLL Eigen::MatrixXd pdal::eigen::pointViewToEigen (const PointView & view)
Converts a PointView into an Eigen::MatrixXd.
This method exists (as of this writing) purely as a convenience method in the API. It is not currently used in the PDAL codebase itself.
Definition at line 539 of file EigenUtils.cpp.
References pdal::PointView::getFieldAs(), pdal::PointView::size(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by pdal::CpdFilter::cpd_affine(), pdal::CpdFilter::cpd_nonrigid(), pdal::CpdFilter::cpd_rigid(), padMatrix(), and TEST().
template<typename Derived > PDAL_DLL Eigen::MatrixXd pdal::eigen::replaceNaNs (const Eigen::MatrixBase< Derived > & data)
Replace NaNs with mean.
Parameters
data the incoming Eigen matrix.
Returns
the updated Eigen matrix.
Definition at line 401 of file EigenUtils.hpp.
References PDAL_DLL, and writeMatrix().
Referenced by computeAspectFD(), computeContour(), computeProfile(), computeSlopeFD(), computeTangential(), computeTotal(), and TEST().
PDAL_DLL void pdal::eigen::writeMatrix (Eigen::MatrixXd data, const std::string & filename, const std::string & driver, double cell_size, BOX2D bounds, SpatialReference srs)
Write Eigen Matrix as a GDAL raster.
Parameters
data the Eigen matrix to write.
filename the filename of the output raster.
cell_size the edge length of raster cell.
bounds the 2D bounds of the data.
srs the spatial reference system of the data.
Definition at line 551 of file EigenUtils.cpp.
References pdal::gdal::Raster::errorMsg(), pdal::Dimension::Float, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::gdal::None, pdal::gdal::Raster::open(), pdal::gdal::registerDrivers(), and pdal::gdal::Raster::writeBand().
Referenced by pdal::SMRFilter::classifyGround(), pdal::SMRFilter::createLowMask(), pdal::SMRFilter::createObjMask(), pdal::SMRFilter::createZImin(), pdal::SMRFilter::createZInet(), pdal::SMRFilter::createZIpro(), pdal::MongusFilter::processGround(), and replaceNaNs().