PDAL: pdal::anonymous_namespace{PDALUtils.cpp} Namespace Reference
pdal::anonymous_namespace{PDALUtils.cpp} Namespace Reference
Functions
void toJSON (const MetadataNode &m, std::ostream &o, int level)
void arrayToJSON (const MetadataNodeList &children, std::ostream &o, int level)
void arrayEltToJSON (const MetadataNode &m, std::ostream &o, int level)
void subnodesToJSON (const MetadataNode &parent, std::ostream &o, int level)
Function Documentation
void pdal::anonymous_namespace{PDALUtils.cpp}::arrayEltToJSON (const MetadataNode & m, std::ostream & o, int level)
Definition at line 100 of file PDALUtils.cpp.
References pdal::MetadataNode::hasChildren(), pdal::MetadataNode::jsonValue(), and subnodesToJSON().
Referenced by arrayToJSON().
void pdal::anonymous_namespace{PDALUtils.cpp}::arrayToJSON (const MetadataNodeList & children, std::ostream & o, int level)
Definition at line 83 of file PDALUtils.cpp.
References arrayEltToJSON().
Referenced by subnodesToJSON(), and pdal::Utils::toJSON().
void pdal::anonymous_namespace{PDALUtils.cpp}::subnodesToJSON (const MetadataNode & parent, std::ostream & o, int level)
Definition at line 57 of file PDALUtils.cpp.
References arrayToJSON(), pdal::MetadataNode::childNames(), pdal::MetadataNode::children(), pdal::MetadataNode::kind(), pdal::MetadataNode::name(), and pdal::Utils::toJSON().
Referenced by arrayEltToJSON(), toJSON(), and pdal::Utils::toJSON().
void pdal::anonymous_namespace{PDALUtils.cpp}::toJSON (const MetadataNode & m, std::ostream & o, int level)
Definition at line 120 of file PDALUtils.cpp.
References pdal::MetadataNode::hasChildren(), pdal::MetadataNode::jsonValue(), pdal::MetadataNode::name(), pdal::Dimension::name(), and subnodesToJSON().