PDAL: pdal/plugins/nitf/test/NitfReaderTest.cpp File Reference
NitfReaderTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/PointView.hpp>
#include <pdal/PipelineManager.hpp>
#include <pdal/StageFactory.hpp>
#include <io/LasWriter.hpp>
#include "Support.hpp"
#include <iostream>
Functions
TEST (NitfReaderTest, test_one)
TEST (NitfReaderTest, optionSrs)
Function Documentation
TEST (NitfReaderTest , test_one)
Definition at line 53 of file NitfReaderTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::MetadataNode::findChild(), pdal::MetadataNode::name(), pdal::MetadataNode::value(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (NitfReaderTest , optionSrs)
Definition at line 119 of file NitfReaderTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Stage::getSpatialReference(), pdal::SpatialReference::getWKT(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::BasePointTable::spatialReference(), and Support::temppath().