PDAL: pdal/plugins/oci/test/OCITest.cpp File Reference
OCITest.cpp File Reference
#include "gtest/gtest.h"
#include <pdal/Filter.hpp>
#include <pdal/StageFactory.hpp>
#include <io/LasReader.hpp>
#include "../io/OciCommon.hpp"
#include "Support.hpp"
#include "TestConfig.hpp"
Classes
class SplitFilter
class OCITest
Namespaces
anonymous_namespace{OCITest.cpp}
Functions
static std::string anonymous_namespace{OCITest.cpp}::connectString (TestConfig::oracleConnection())
static const std::string anonymous_namespace{OCITest.cpp}::baseTableName ("PDAL_TEST_BASE")
static const std::string anonymous_namespace{OCITest.cpp}::blockTableName ("PDAL_TEST_BLOCKS")
GTEST_API_ int main (int argc, char **argv)
bool ShouldRunTest ()
Options readerOptions ()
Options writerOptions ()
void writeData (Orientation orient, bool scaling, bool compression=false)
void compare (const PointViewPtr candidate, std::string filename)
void readData ()
TEST_F (OCITest, dim_major_unscaled)
TEST_F (OCITest, dim_major_scaled)
TEST_F (OCITest, point_major_unscaled)
TEST_F (OCITest, point_major_unscaled_compressed)
TEST_F (OCITest, point_major_scaled)
Function Documentation
void compare (const PointViewPtr candidate, std::string filename)
Definition at line 242 of file OCITest.cpp.
References pdal::Options::add(), Blue, pdal::Stage::execute(), Green, Intensity, pdal::Stage::prepare(), Red, pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by readData(), pdal::MortonOrderFilter::run(), and TEST_F().
GTEST_API_ int main (int argc, char ** argv)
Definition at line 56 of file OCITest.cpp.
References anonymous_namespace{OCITest.cpp}::connectString(), and pdal::Utils::startsWith().
void readData ()
Definition at line 293 of file OCITest.cpp.
References pdal::Options::add(), compare(), pdal::StageFactory::createStage(), Support::datapath(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and readerOptions().
Referenced by TEST_F().
Options readerOptions ()
Definition at line 81 of file OCITest.cpp.
References pdal::Options::add(), and anonymous_namespace{OCITest.cpp}::connectString().
Referenced by pdal::RandomKernel::execute(), pdal::TIndexReader::initialize(), readData(), pdal::TEST(), and TEST().
bool ShouldRunTest ()
Definition at line 75 of file OCITest.cpp.
References anonymous_namespace{OCITest.cpp}::connectString().
TEST_F (OCITest , dim_major_unscaled)
Definition at line 325 of file OCITest.cpp.
References pdal::DimensionMajor, readData(), and writeData().
TEST_F (OCITest , dim_major_scaled)
Definition at line 332 of file OCITest.cpp.
References pdal::DimensionMajor, readData(), and writeData().
TEST_F (OCITest , point_major_unscaled)
Definition at line 339 of file OCITest.cpp.
References pdal::PointMajor, readData(), and writeData().
TEST_F (OCITest , point_major_unscaled_compressed)
Definition at line 346 of file OCITest.cpp.
References pdal::PointMajor, readData(), and writeData().
TEST_F (OCITest , point_major_scaled)
Definition at line 353 of file OCITest.cpp.
References pdal::PointMajor, readData(), and writeData().
void writeData (Orientation orient, bool scaling, bool compression = false)
Definition at line 193 of file OCITest.cpp.
References pdal::Options::add(), anonymous_namespace{OCITest.cpp}::baseTableName(), anonymous_namespace{OCITest.cpp}::blockTableName(), anonymous_namespace{OCITest.cpp}::connectString(), pdal::StageFactory::createStage(), Support::datapath(), pdal::DimensionMajor, pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Utils::split().
Referenced by TEST_F().
Options writerOptions ()
Definition at line 90 of file OCITest.cpp.
References pdal::Options::add(), anonymous_namespace{OCITest.cpp}::baseTableName(), anonymous_namespace{OCITest.cpp}::blockTableName(), and anonymous_namespace{OCITest.cpp}::connectString().
Referenced by pdal::PCLKernel::execute(), pdal::SortKernel::execute(), pdal::RandomKernel::execute(), pdal::TIndexKernel::mergeFile(), pdal::TEST(), and testReadWrite().