PDAL: pdal/test/unit/OldPCLBlockTest.cpp File Reference
OldPCLBlockTest.cpp File Reference
#include <string>
#include <pdal/StageFactory.hpp>
#include <pdal/pdal_test_main.hpp>
#include "Support.hpp"
Functions
TEST (OldPCLBlockTests, StatisticalOutliers1)
TEST (OldPCLBlockTests, StatisticalOutliers2)
TEST (OldPCLBlockTests, RadiusOutliers1)
TEST (OldPCLBlockTests, RadiusOutliers2)
TEST (OldPCLBlockTests, PMF)
Function Documentation
TEST (OldPCLBlockTests , StatisticalOutliers1)
Definition at line 44 of file OldPCLBlockTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
TEST (OldPCLBlockTests , StatisticalOutliers2)
Definition at line 82 of file OldPCLBlockTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
TEST (OldPCLBlockTests , RadiusOutliers1)
Definition at line 120 of file OldPCLBlockTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
TEST (OldPCLBlockTests , RadiusOutliers2)
Definition at line 158 of file OldPCLBlockTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
TEST (OldPCLBlockTests , PMF)
Definition at line 196 of file OldPCLBlockTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.