PDAL: pdal/test/unit/apps/pc2pcTest.cpp File Reference
pc2pcTest.cpp File Reference
#include <iostream>
#include <sstream>
#include <string>
#include <pdal/pdal_test_main.hpp>
#include <pdal/util/FileUtils.hpp>
#include <io/LasReader.hpp>
#include "Support.hpp"
Functions
static std::string appName ()
TEST (pc2pcTest, pc2pcTest_test_common_opts)
static bool fileIsOkay (const std::string &name)
static bool fileIsCompressed (const std::string &name)
static bool fileHasSrs (const std::string &name)
TEST (pc2pcTest, pc2pc_test_switches)
Function Documentation
static std::string appName () static
Definition at line 47 of file pc2pcTest.cpp.
References Support::binpath(), Support::exename(), pdal::Utils::run_shell_command(), and pdal::TEST().
Referenced by anonymous_namespace{pcpipelineTestJSON.cpp}::run_pipeline(), anonymous_namespace{pcpipelineTestJSON.cpp}::run_pipeline_stdin(), pdal::TEST(), and TEST().
static bool fileHasSrs (const std::string & name) static
Definition at line 108 of file pc2pcTest.cpp.
References pdal::Options::add().
Referenced by TEST().
static bool fileIsCompressed (const std::string & name) static
Definition at line 95 of file pc2pcTest.cpp.
References pdal::Options::add().
Referenced by TEST().
static bool fileIsOkay (const std::string & name) static
Definition at line 84 of file pc2pcTest.cpp.
References pdal::FileUtils::fileExists(), and pdal::FileUtils::fileSize().
Referenced by TEST().
TEST (pc2pcTest , pc2pcTest_test_common_opts)
Definition at line 69 of file pc2pcTest.cpp.
References appName(), Support::binpath(), Support::exename(), and pdal::Utils::run_shell_command().
TEST (pc2pcTest , pc2pc_test_switches)
Definition at line 122 of file pc2pcTest.cpp.
References appName(), Support::datapath(), pdal::FileUtils::deleteFile(), fileHasSrs(), fileIsCompressed(), fileIsOkay(), pdal::Utils::run_shell_command(), and Support::temppath().