PDAL: pdal/plugins/pcl/test/PCLBlockFilterTest.cpp File Reference
PCLBlockFilterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/PipelineManager.hpp>
#include <pdal/StageFactory.hpp>
#include "Support.hpp"
Functions
TEST (PCLBlockFilterTest, PCLBlockFilterTest_example_passthrough_json)
static void test_filter (const std::string &jsonFile, size_t expectedPointCount)
TEST (PCLBlockFilterTest, PCLBlockFilterTest_example_PassThrough_1)
TEST (PCLBlockFilterTest, PCLBlockFilterTest_example_PassThrough_2)
TEST (PCLBlockFilterTest, PCLBlockFilterTest_filter_GridMinimum)
TEST (PCLBlockFilterTest, PCLBlockFilterTest_filter_PassThrough)
TEST (PCLBlockFilterTest, PCLBlockFilterTest_filter_VoxelGrid)
Function Documentation
TEST (PCLBlockFilterTest , PCLBlockFilterTest_example_passthrough_json)
Definition at line 44 of file PCLBlockFilterTest.cpp.
References Support::configuredpath(), pdal::StageFactory::createStage(), pdal::PipelineManager::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::PipelineManager::readPipeline(), and pdal::PipelineManager::views().
TEST (PCLBlockFilterTest , PCLBlockFilterTest_example_PassThrough_1)
Definition at line 93 of file PCLBlockFilterTest.cpp.
References test_filter().
TEST (PCLBlockFilterTest , PCLBlockFilterTest_example_PassThrough_2)
Definition at line 99 of file PCLBlockFilterTest.cpp.
References test_filter().
TEST (PCLBlockFilterTest , PCLBlockFilterTest_filter_GridMinimum)
Definition at line 110 of file PCLBlockFilterTest.cpp.
References test_filter().
TEST (PCLBlockFilterTest , PCLBlockFilterTest_filter_PassThrough)
Definition at line 115 of file PCLBlockFilterTest.cpp.
References test_filter().
TEST (PCLBlockFilterTest , PCLBlockFilterTest_filter_VoxelGrid)
Definition at line 124 of file PCLBlockFilterTest.cpp.
References test_filter().
static void test_filter (const std::string & jsonFile, size_t expectedPointCount) static
Definition at line 62 of file PCLBlockFilterTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
Referenced by TEST().