PDAL: pdal/apps/pdal.cpp File Reference
pdal.cpp File Reference
#include <pdal/GDALUtils.hpp>
#include <pdal/Kernel.hpp>
#include <pdal/PluginManager.hpp>
#include <pdal/StageFactory.hpp>
#include <pdal/pdal_config.hpp>
#include <iomanip>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>
#include <json/json.h>
#include <csignal>
#include <unistd.h>
Classes
class App
Namespaces
anonymous_namespace{pdal.cpp}
Functions
std::string headline (Utils::screenWidth(), '-')
LogPtr anonymous_namespace{pdal.cpp}::logPtr (new Log("PDAL","stderr"))
int main (int argc, char *argv[])
Function Documentation
std::string headline (Utils::screenWidth() , '-')
Referenced by pdal::getPDALDebugInformation(), App::outputOptions(), and App::outputVersion().
int main (int argc, char * argv[])
Definition at line 296 of file pdal.cpp.
References App::execute(), and anonymous_namespace{pdal.cpp}::logPtr().