PDAL: pdal/plugins/pgpointcloud/test/PgpointcloudWriterTest.cpp File Reference
PgpointcloudWriterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/Writer.hpp>
#include <pdal/StageFactory.hpp>
#include <pdal/util/Algorithm.hpp>
#include "Support.hpp"
#include "Pgtest-Support.hpp"
#include "../io/PgCommon.hpp"
Classes
class PgpointcloudWriterTest
Namespaces
anonymous_namespace{PgpointcloudWriterTest.cpp}
Functions
std::string anonymous_namespace{PgpointcloudWriterTest.cpp}::getTestConnBase ()
std::string anonymous_namespace{PgpointcloudWriterTest.cpp}::getConnectionString (const std::string &dbname)
std::string anonymous_namespace{PgpointcloudWriterTest.cpp}::getTestDBTempConn ()
std::string anonymous_namespace{PgpointcloudWriterTest.cpp}::getMasterDBConn ()
Options getDbOptions ()
void anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite (const Options &writerOps)
TEST_F (PgpointcloudWriterTest, write)
TEST_F (PgpointcloudWriterTest, writeScaled)
TEST_F (PgpointcloudWriterTest, writeXYZ)
TEST_F (PgpointcloudWriterTest, writetNoPointcloudExtension)
TEST_F (PgpointcloudWriterTest, writeDeleteTable)
Function Documentation
Options getDbOptions ()
Definition at line 80 of file PgpointcloudWriterTest.cpp.
References pdal::Options::add(), and anonymous_namespace{PgpointcloudWriterTest.cpp}::getTestDBTempConn().
Referenced by TEST_F().
TEST_F (PgpointcloudWriterTest , write)
Definition at line 210 of file PgpointcloudWriterTest.cpp.
References getDbOptions(), and anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite().
TEST_F (PgpointcloudWriterTest , writeScaled)
Definition at line 220 of file PgpointcloudWriterTest.cpp.
References pdal::Options::add(), getDbOptions(), and anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite().
TEST_F (PgpointcloudWriterTest , writeXYZ)
Definition at line 235 of file PgpointcloudWriterTest.cpp.
References pdal::Options::add(), pdal::Utils::contains(), pdal::StageFactory::createStage(), pdal::PointLayout::dims(), getDbOptions(), pdal::BasePointTable::layout(), anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST_F (PgpointcloudWriterTest , writetNoPointcloudExtension)
Definition at line 260 of file PgpointcloudWriterTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and getDbOptions().
TEST_F (PgpointcloudWriterTest , writeDeleteTable)
Definition at line 291 of file PgpointcloudWriterTest.cpp.
References pdal::Options::add(), getDbOptions(), and anonymous_namespace{PgpointcloudWriterTest.cpp}::optionsWrite().