PDAL: pdal/plugins/python/plang/CMakeLists.txt File Reference
pdal/plugins/python/plang/CMakeLists.txt File Reference
Functions
set (plang_srcs Invocation.cpp Environment.cpp Redirector.cpp Script.cpp) include($
python cmake set_target_properties (${PDAL_PLANG_LIB_NAME}PROPERTIES VERSION"${PDAL_BUILD_VERSION}"SOVERSION"${PDAL_API_VERSION}"CLEAN_DIRECT_OUTPUT 1) target_link_libraries($
Function Documentation
set (plang_srcs Invocation.cpp Environment.cpp Redirector.cpp Script. cpp)
Definition at line 2 of file CMakeLists.txt.
References python.
python cmake set_target_properties (${PDAL_PLANG_LIB_NAME}PROPERTIES VERSION"${PDAL_BUILD_VERSION}"SOVERSION"${PDAL_API_VERSION}"CLEAN_DIRECT_OUTPUT)
Definition at line 12 of file CMakeLists.txt.
References include(), target_include_directories(), and rtd_theme::VERSION.
Referenced by include().