PDAL: pdal/plugins/greyhound/CMakeLists.txt File Reference
pdal/plugins/greyhound/CMakeLists.txt File Reference
Functions
add_definitions (-DHAVE_JSONCPP=1) if(WIN32) add_definitions("-DARBITER_DLL_IMPORT") endif() PDAL_ADD_PLUGIN(libname reader greyhound FILES io/CompressionStream.cpp io/GreyhoundReader.cpp io/bounds.cpp LINK_WITH $
target_include_directories (${libname}PRIVATE ${PDAL_JSONCPP_INCLUDE_DIR}${PDAL_VENDOR_DIR}) if(WITH_TESTS) PDAL_ADD_TEST(pdal_io_greyhound_reader_test FILES test/GreyhoundReaderTest.cpp LINK_WITH $
Function Documentation
add_definitions (- DHAVE_JSONCPP = 1)
Definition at line 5 of file CMakeLists.txt.
Referenced by find_package().
target_include_directories (${libname}PRIVATE ${PDAL_JSONCPP_INCLUDE_DIR}${PDAL_VENDOR_DIR})
Definition at line 16 of file CMakeLists.txt.
References endif(), and PDAL_ADD_TEST().
Referenced by cmake_minimum_required(), endif(), find_package(), include(), option(), PDAL_ADD_PLUGIN(), PDAL_ADD_TEST(), set(), set_target_properties(), and target_include_directories().