PDAL: pdal/plugins/cpd/CMakeLists.txt File Reference
pdal/plugins/cpd/CMakeLists.txt File Reference
Functions
set (Cpd_VERSION 0.5) find_package(Cpd $
REQUIRED option (BUILD_PLUGIN_CPD"Build Coherent Point Drift support"${Cpd_FOUND}) set(files filters/CpdFilter.cpp) set(include_dirs"$
Function Documentation
REQUIRED option (BUILD_PLUGIN_CPD"Build Coherent Point Drift support"${Cpd_FOUND})
Definition at line 4 of file CMakeLists.txt.
References endif(), hag::filter(), setup::include_dirs, PDAL_ADD_PLUGIN(), PDAL_ADD_TEST(), and target_include_directories().
Referenced by pdal::Options::fromCmdlineFile(), pdal::Options::Options(), pdal::Options::replace(), target_include_directories(), and pdal::TEST().
set (Cpd_VERSION 0. 5)
Definition at line 1 of file CMakeLists.txt.