PDAL: pdal/plugins/pgpointcloud/CMakeLists.txt File Reference
pdal/plugins/pgpointcloud/CMakeLists.txt File Reference
Functions
include (${PDAL_CMAKE_DIR}/postgres.cmake) PDAL_ADD_PLUGIN(reader_libname reader pgpointcloud FILES io/PgReader.cpp LINK_WITH $
target_include_directories (${reader_libname}PRIVATE ${PDAL_VENDOR_DIR}/pdalboost ${LIBXML2_INCLUDE_DIR}) PDAL_ADD_PLUGIN(writer_libname writer pgpointcloud FILES io/PgWriter.cpp LINK_WITH $
CACHE STRING Postgres test database must be able to create databases set (PGPOINTCLOUD_TEST_DB_HOST $ENV{PGHOST}CACHE STRING"Postgres test database host") set(PGPOINTCLOUD_TEST_DB_PORT $ENV
CACHE STRING Postgres test database port set (PGPOINTCLOUD_TEST_DB_NAME template1 CACHE STRING"Postgres master database name, must exist") set(PGPOINTCLOUD_TEST_DB_TEMPNAME pdal_test_tmp CACHE STRING"Postgres test database temp database name") configure_file(test/Pgtest-Support.hpp.in $
include Pgtest Support hpp PDAL_ADD_TEST (pgpointcloudtest FILES test/PgpointcloudWriterTest.cpp LINK_WITH ${reader_libname}${writer_libname}) target_include_directories(pgpointcloudtest PRIVATE $
Variables
CACHE STRING Postgres test database user
Function Documentation
include (${PDAL_CMAKE_DIR}/postgres.)
Definition at line 4 of file CMakeLists.txt.
References PDAL_ADD_PLUGIN().
include Pgtest Support hpp PDAL_ADD_TEST (pgpointcloudtest FILES test/PgpointcloudWriterTest.cpp LINK_WITH ${reader_libname}${writer_libname})
Definition at line 49 of file CMakeLists.txt.
Referenced by find_package(), include(), option(), PDAL_ADD_PLUGIN(), set(), and target_include_directories().
CACHE STRING Postgres test database must be able to create databases set (PGPOINTCLOUD_TEST_DB_HOST $ENV{PGHOST}CACHE STRING"Postgres test database host")
Definition at line 35 of file CMakeLists.txt.
CACHE STRING Postgres test database port set (PGPOINTCLOUD_TEST_DB_NAME template1 CACHE STRING"Postgres master database name, must exist")
Definition at line 39 of file CMakeLists.txt.
target_include_directories (${reader_libname}PRIVATE ${PDAL_VENDOR_DIR}/pdalboost ${LIBXML2_INCLUDE_DIR})
Definition at line 14 of file CMakeLists.txt.
References PDAL_ADD_PLUGIN(), and target_include_directories().
Variable Documentation
CACHE STRING Postgres test database user
Definition at line 34 of file CMakeLists.txt.
Referenced by pdal::LasWriter::addUserVlrs(), pdal::LasReader::loadPointV10(), and pdal::LasReader::loadPointV14().