PDAL: pdal/test/unit/PointViewTest.cpp File Reference
PointViewTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <array>
#include <random>
#include <pdal/PointView.hpp>
#include <pdal/PointViewIter.hpp>
#include <pdal/PDALUtils.hpp>
#include "Support.hpp"
Functions
PointViewPtr makeTestView (PointTableRef table, point_count_t cnt=17)
void verifyTestView (const PointView &view, point_count_t cnt=17)
TEST (PointViewTest, getSet)
TEST (PointViewTest, getAsUint8)
TEST (PointViewTest, getAsInt32)
TEST (PointViewTest, getFloat)
TEST (PointViewTest, bigfile)
static void check_bounds (const BOX3D &box, double minx, double maxx, double miny, double maxy, double minz, double maxz)
TEST (PointViewTest, calcBounds)
TEST (PointViewTest, order)
TEST (PointViewTest, issue1264)
TEST (PointViewDeathTest, out_of_bounds)
Function Documentation
static void check_bounds (const BOX3D & box, double minx, double maxx, double miny, double maxy, double minz, double maxz) static
Definition at line 231 of file PointViewTest.cpp.
References pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX3D::maxz, pdal::BOX2D::minx, pdal::BOX2D::miny, and pdal::BOX3D::minz.
Referenced by TEST().
PointViewPtr makeTestView (PointTableRef table, point_count_t cnt = 17)
Definition at line 47 of file PointViewTest.cpp.
References pdal::Dimension::Classification, pdal::BasePointTable::layout(), pdal::PointLayout::registerDim(), pdal::Dimension::X, pdal::Dimension::Y, and z.
Referenced by TEST().
TEST (PointViewTest , getSet)
Definition at line 90 of file PointViewTest.cpp.
References makeTestView(), and verifyTestView().
TEST (PointViewTest , getAsUint8)
Definition at line 97 of file PointViewTest.cpp.
References pdal::Dimension::Classification, makeTestView(), pdal::Dimension::X, pdal::Dimension::Y, and z.
TEST (PointViewTest , getAsInt32)
Definition at line 126 of file PointViewTest.cpp.
References pdal::Dimension::Classification, makeTestView(), pdal::Dimension::X, pdal::Dimension::Y, and z.
TEST (PointViewTest , getFloat)
Definition at line 145 of file PointViewTest.cpp.
References pdal::Dimension::Classification, pdal::georeference::anonymous_namespace{Georeference.cpp}::f, makeTestView(), pdal::Dimension::X, pdal::Dimension::Y, and z.
TEST (PointViewTest , bigfile)
Definition at line 164 of file PointViewTest.cpp.
References pdal::PointView::getFieldAs(), pdal::Dimension::id(), pdal::BasePointTable::layout(), pdal::PointLayout::registerDim(), pdal::PointView::setField(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (PointViewTest , calcBounds)
Definition at line 245 of file PointViewTest.cpp.
References pdal::PointView::calculateBounds(), check_bounds(), pdal::BasePointTable::layout(), pdal::PointLayout::registerDim(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
TEST (PointViewTest , order)
Definition at line 294 of file PointViewTest.cpp.
References pdal::Dimension::COUNT.
TEST (PointViewTest , issue1264)
Definition at line 321 of file PointViewTest.cpp.
References pdal::PointLayout::assignDim(), pdal::PointView::getFieldAs(), pdal::BasePointTable::layout(), pdal::PointView::setField(), pdal::Dimension::Signed8, and pdal::Dimension::Unsigned8.
TEST (PointViewDeathTest , out_of_bounds)
Definition at line 349 of file PointViewTest.cpp.
References makeTestView(), and pdal::Dimension::X.
void verifyTestView (const PointView & view, point_count_t cnt = 17)
Definition at line 73 of file PointViewTest.cpp.
References pdal::Dimension::Classification, pdal::Utils::compare_approx(), pdal::PointView::getFieldAs(), pdal::Dimension::X, pdal::Dimension::Y, and z.
Referenced by TEST().