PDAL: pdal/test/unit/PointContextTest.cpp File Reference
PointContextTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/PointContext.hpp>
#include <las/LasReader.hpp>
#include "Support.hpp"
Functions
TEST (PointContext, resolveType)
TEST (PointContext, userBuffer)
Function Documentation
TEST (PointContext , resolveType)
Build as we go.
Definition at line 43 of file PointContextTest.cpp.
References pdal::Dimension::Double, pdal::Dimension::Float, pdal::Dimension::Signed16, pdal::Dimension::Signed32, pdal::Dimension::Signed8, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned8, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (PointContext , userBuffer)
Definition at line 106 of file PointContextTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Dimension::Double, pdal::Stage::execute(), anonymous_namespace{ReprojectionFilterTest.cpp}::getPoint(), pdal::Dimension::Detail::id(), pdal::Dimension::id(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Reader::setReadCb(), pdal::Dimension::Detail::setType(), pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.