PDAL: pdal/test/unit/ProgramArgsTest.cpp File Reference
ProgramArgsTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <json/json.h>
#include <wordexp.h>
#include <pdal/pdal_internal.hpp>
#include <pdal/util/ProgramArgs.hpp>
Namespaces
anonymous_namespace{ProgramArgsTest.cpp}
Macros
#define HANDLE_EXCEPTION(a) EXPECT_THROW(a, arg_error)
Functions
StringList anonymous_namespace{ProgramArgsTest.cpp}::toStringList (const std::string &s)
TEST (ProgramArgsTest, t1)
TEST (ProgramArgsTest, t2)
TEST (ProgramArgsTest, t3)
TEST (ProgramArgsTest, t4)
TEST (ProgramArgsTest, synonym)
TEST (ProgramArgsTest, positional)
TEST (ProgramArgsTest, vector)
TEST (ProgramArgsTest, stringvector)
TEST (ProgramArgsTest, vectorfail)
TEST (ProgramArgsTest, parseSimple)
TEST (ProgramArgsTest, json)
TEST (ProgramArgsTest, invalidJson)
Macro Definition Documentation
#define HANDLE_EXCEPTION (a) EXPECT_THROW(a, arg_error)
Definition at line 48 of file ProgramArgsTest.cpp.
Referenced by TEST().
Function Documentation
TEST (ProgramArgsTest , t1)
Definition at line 78 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::reset(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().
TEST (ProgramArgsTest , t2)
Definition at line 117 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::reset(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().
TEST (ProgramArgsTest , t3)
Definition at line 160 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), HANDLE_EXCEPTION, pdal::ProgramArgs::parse(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().
TEST (ProgramArgsTest , t4)
Definition at line 211 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), and HANDLE_EXCEPTION.
TEST (ProgramArgsTest , synonym)
Definition at line 231 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::ProgramArgs::addSynonym(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::reset(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().
TEST (ProgramArgsTest , positional)
Definition at line 248 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::reset(), pdal::Arg::setPositional(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().
TEST (ProgramArgsTest , vector)
Definition at line 284 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::reset(), pdal::Arg::setOptionalPositional(), pdal::Arg::setPositional(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().
TEST (ProgramArgsTest , stringvector)
Definition at line 341 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::reset(), pdal::Arg::setOptionalPositional(), pdal::Arg::setPositional(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().
TEST (ProgramArgsTest , vectorfail)
Definition at line 383 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::ProgramArgs::parse(), pdal::Arg::setOptionalPositional(), and pdal::Arg::setPositional().
TEST (ProgramArgsTest , parseSimple)
Definition at line 400 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::parseSimple(), pdal::ProgramArgs::reset(), pdal::Arg::setPositional(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().
TEST (ProgramArgsTest , json)
Definition at line 449 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::Utils::fromString(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::reset(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().
TEST (ProgramArgsTest , invalidJson)
Definition at line 515 of file ProgramArgsTest.cpp.
References pdal::ProgramArgs::add(), pdal::LasUtils::parse(), pdal::ProgramArgs::parse(), pdal::ProgramArgs::reset(), and anonymous_namespace{ProgramArgsTest.cpp}::toStringList().