PDAL: pdal/plugins/python/test/PythonFilterTest.cpp File Reference
PythonFilterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/PipelineManager.hpp>
#include <pdal/StageFactory.hpp>
#include <io/FauxReader.hpp>
#include <filters/StatsFilter.hpp>
#include "../plang/Invocation.hpp"
#include <pdal/PyArray.hpp>
#include "../plang/Environment.hpp"
#include <pdal/StageWrapper.hpp>
#include "Support.hpp"
Classes
class PythonFilterTest
class PredicateFilterTest
class jsonWithProgrammable
class jsonWithPredicate
Functions
TEST_F (PythonFilterTest, PythonFilterTest_test1)
TEST_F (PythonFilterTest, pipelineJSON)
TEST_F (PythonFilterTest, add_dimension)
TEST_F (PythonFilterTest, metadata)
TEST_F (PythonFilterTest, pdalargs)
TEST_F (PredicateFilterTest, PredicateFilterTest_test_programmable)
TEST_F (PredicateFilterTest, PredicateFilterTest_test_programmable_2)
TEST_F (PredicateFilterTest, PredicateFilterTest_test_programmable_3)
TEST_F (PredicateFilterTest, PredicateFilterTest_test_programmable_4)
TEST_F (PredicateFilterTest, PredicateFilterTest_PipelineJSON)
TEST_F (PredicateFilterTest, PredicateFilterTest_EmbedJSON)
TEST (PLangTest, PLangTest_basic)
TEST (PLangTest, PLangTest_compile_error)
TEST (PLangTest, PLangTest_runtime_error)
TEST (PLangTest, PLangTest_returnvoid)
TEST (PLangTest, PLangTest_returnint)
TEST (PLangTest, PLangTest_ins)
TEST (PLangTest, PLangTest_outs)
TEST (PLangTest, PLangTest_aliases)
TEST (PLangTest, PLangTest_returntrue)
TEST (PLangTest, PLangTest_returnfalse)
TEST (PLangTest, PLangTest_reentry)
TEST (PLangTest, log)
PointViewPtr makeTestView (PointTableRef table, point_count_t cnt=17)
void verifyTestView (const PointView &view, point_count_t cnt=17)
TEST (PLangTest, PLangTest_array)
static void run_pipeline (std::string const &pipeline)
TEST_P (jsonWithProgrammable, pipeline)
INSTANTIATE_TEST_CASE_P (plugins, jsonWithProgrammable, testing::Values("pipeline/programmable-update-y-dims.json"))
TEST_P (jsonWithPredicate, pipeline)
INSTANTIATE_TEST_CASE_P (plugins, jsonWithPredicate, testing::Values("pipeline/crop_wkt_2d_classification.json","pipeline/from-module.json","pipeline/predicate-embed.json","pipeline/predicate-keep-ground-and-unclass.json","pipeline/predicate-keep-last-return.json","pipeline/predicate-keep-specified-returns.json","pipeline/reproject.json"))
Function Documentation
INSTANTIATE_TEST_CASE_P (plugins , jsonWithProgrammable , testing::Values("pipeline/programmable-update-y-dims.json"))
INSTANTIATE_TEST_CASE_P (plugins , jsonWithPredicate , testing::Values("pipeline/crop_wkt_2d_classification.json","pipeline/from-module.json","pipeline/predicate-embed.json","pipeline/predicate-keep-ground-and-unclass.json","pipeline/predicate-keep-last-return.json","pipeline/predicate-keep-specified-returns.json","pipeline/reproject.json"))
PointViewPtr makeTestView (PointTableRef table, point_count_t cnt = 17)
Definition at line 949 of file PythonFilterTest.cpp.
References pdal::Dimension::Classification, pdal::BasePointTable::layout(), pdal::PointLayout::registerDim(), pdal::Dimension::X, pdal::Dimension::Y, and z.
Referenced by TEST().
static void run_pipeline (std::string const & pipeline) static
Definition at line 1004 of file PythonFilterTest.cpp.
References Support::binpath(), Support::configuredpath(), Support::exename(), and pdal::Utils::run_shell_command().
Referenced by pdal::TEST(), pdal::TEST_P(), and TEST_P().
TEST (PLangTest , PLangTest_basic)
Definition at line 580 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), and pdal::plang::Invocation::execute().
TEST (PLangTest , PLangTest_compile_error)
Definition at line 601 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile().
TEST (PLangTest , PLangTest_runtime_error)
Definition at line 615 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), and pdal::plang::Invocation::execute().
TEST (PLangTest , PLangTest_returnvoid)
Definition at line 631 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), and pdal::plang::Invocation::execute().
TEST (PLangTest , PLangTest_returnint)
Definition at line 647 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), and pdal::plang::Invocation::execute().
TEST (PLangTest , PLangTest_ins)
Definition at line 670 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), pdal::Dimension::Double, pdal::plang::Invocation::execute(), and pdal::plang::Invocation::insertArgument().
TEST (PLangTest , PLangTest_outs)
Definition at line 690 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), pdal::Dimension::Double, pdal::plang::Invocation::execute(), pdal::plang::Invocation::extractResult(), and pdal::plang::Invocation::hasOutputVariable().
TEST (PLangTest , PLangTest_aliases)
Definition at line 718 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), pdal::Dimension::Double, pdal::plang::Invocation::execute(), pdal::plang::Invocation::extractResult(), pdal::plang::Invocation::getOutputNames(), pdal::plang::Invocation::hasOutputVariable(), and pdal::plang::Invocation::insertArgument().
TEST (PLangTest , PLangTest_returntrue)
Definition at line 793 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), and pdal::plang::Invocation::execute().
TEST (PLangTest , PLangTest_returnfalse)
Definition at line 809 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), and pdal::plang::Invocation::execute().
TEST (PLangTest , PLangTest_reentry)
Definition at line 831 of file PythonFilterTest.cpp.
References pdal::plang::Invocation::compile(), pdal::Dimension::Double, pdal::plang::Invocation::execute(), pdal::plang::Invocation::extractResult(), and pdal::plang::Invocation::insertArgument().
TEST (PLangTest , log)
Definition at line 875 of file PythonFilterTest.cpp.
References pdal::Options::add(), Support::compare_text_files(), pdal::StageFactory::createStage(), Support::datapath(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Stage::setOptions(), and Support::temppath().
TEST (PLangTest , PLangTest_array)
Definition at line 991 of file PythonFilterTest.cpp.
References makeTestView(), pdal::python::Array::update(), and verifyTestView().
TEST_F (PythonFilterTest , PythonFilterTest_test1)
Definition at line 64 of file PythonFilterTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::stats::Summary::maximum(), pdal::stats::Summary::minimum(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST_F (PythonFilterTest , pipelineJSON)
Definition at line 128 of file PythonFilterTest.cpp.
References Support::configuredpath(), pdal::PipelineManager::execute(), pdal::PipelineManager::readPipeline(), pdal::PipelineManager::views(), and pdal::Dimension::Y.
TEST_F (PythonFilterTest , add_dimension)
Definition at line 146 of file PythonFilterTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::PointLayout::findDim(), pdal::BasePointTable::layout(), and pdal::Stage::setOptions().
TEST_F (PythonFilterTest , metadata)
Definition at line 200 of file PythonFilterTest.cpp.
References pdal::Options::add(), pdal::MetadataNode::children(), pdal::StageFactory::createStage(), pdal::Dimension::description(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::MetadataNode::findChild(), pdal::BasePointTable::layout(), pdal::BasePointTable::metadata(), pdal::Dimension::name(), and pdal::Stage::setOptions().
TEST_F (PythonFilterTest , pdalargs)
Definition at line 251 of file PythonFilterTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), and pdal::Stage::setOptions().
TEST_F (PredicateFilterTest , PredicateFilterTest_test_programmable)
Definition at line 307 of file PythonFilterTest.cpp.
References pdal::Options::add(), pdal::Utils::compare_approx(), pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::stats::Summary::maximum(), pdal::stats::Summary::minimum(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST_F (PredicateFilterTest , PredicateFilterTest_test_programmable_2)
Definition at line 366 of file PythonFilterTest.cpp.
References pdal::Options::add(), pdal::Utils::compare_approx(), pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::stats::Summary::maximum(), pdal::stats::Summary::minimum(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST_F (PredicateFilterTest , PredicateFilterTest_test_programmable_3)
Definition at line 424 of file PythonFilterTest.cpp.
References pdal::Options::add(), pdal::Utils::compare_approx(), pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::stats::Summary::maximum(), pdal::stats::Summary::minimum(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST_F (PredicateFilterTest , PredicateFilterTest_test_programmable_4)
Definition at line 505 of file PythonFilterTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), pdal::StageWrapper::done(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::StageWrapper::ready(), pdal::StageWrapper::run(), and pdal::Stage::setOptions().
TEST_F (PredicateFilterTest , PredicateFilterTest_PipelineJSON)
Definition at line 561 of file PythonFilterTest.cpp.
References Support::configuredpath(), pdal::PipelineManager::execute(), and pdal::PipelineManager::readPipeline().
TEST_F (PredicateFilterTest , PredicateFilterTest_EmbedJSON)
Definition at line 570 of file PythonFilterTest.cpp.
References Support::configuredpath(), pdal::PipelineManager::execute(), and pdal::PipelineManager::readPipeline().
TEST_P (jsonWithProgrammable , pipeline)
Definition at line 1019 of file PythonFilterTest.cpp.
References pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::plang::Environment::get(), pdal::INSTANTIATE_TEST_CASE_P(), and run_pipeline().
TEST_P (jsonWithPredicate , pipeline)
Definition at line 1038 of file PythonFilterTest.cpp.
References pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::plang::Environment::get(), pdal::INSTANTIATE_TEST_CASE_P(), and run_pipeline().
void verifyTestView (const PointView & view, point_count_t cnt = 17)
Definition at line 974 of file PythonFilterTest.cpp.
References pdal::Dimension::Classification, pdal::Utils::compare_approx(), pdal::PointView::getFieldAs(), pdal::Dimension::X, pdal::Dimension::Y, and z.
Referenced by TEST().