PDAL: pdal/test/unit/io/QFITReaderTest.cpp File Reference
QFITReaderTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/Options.hpp>
#include <pdal/PointView.hpp>
#include <io/QfitReader.hpp>
#include "Support.hpp"
#include <iostream>
Functions
void Check_Point (const PointView &data, PointId index, double xref, double yref, double zref, int32_t tref)
TEST (QFITReaderTest, test_10_word)
TEST (QFITReaderTest, test_14_word)
Function Documentation
void Check_Point (const PointView & data, PointId index, double xref, double yref, double zref, int32_t tref)
Definition at line 47 of file QFITReaderTest.cpp.
References pdal::PointView::getFieldAs(), pdal::Dimension::OffsetTime, pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by TEST().
TEST (QFITReaderTest , test_10_word)
Definition at line 63 of file QFITReaderTest.cpp.
References pdal::Options::add(), Check_Point(), Support::datapath(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
TEST (QFITReaderTest , test_14_word)
Definition at line 88 of file QFITReaderTest.cpp.
References pdal::Options::add(), Check_Point(), Support::datapath(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.