PDAL: pdal/test/unit/filters/RangeFilterTest.cpp File Reference
RangeFilterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/PointView.hpp>
#include <pdal/StageFactory.hpp>
#include <io/FauxReader.hpp>
#include <io/LasReader.hpp>
#include <io/TextReader.hpp>
#include <filters/RangeFilter.hpp>
#include <filters/StreamCallbackFilter.hpp>
#include "Support.hpp"
Functions
TEST (RangeFilterTest, createStage)
TEST (RangeFilterTest, noLimits)
TEST (RangeFilterTest, singleDimension)
TEST (RangeFilterTest, multipleDimensions)
TEST (RangeFilterTest, multipleDimsBusted)
TEST (RangeFilterTest, onlyMin)
TEST (RangeFilterTest, onlyMax)
TEST (RangeFilterTest, negation)
TEST (RangeFilterTest, equals)
TEST (RangeFilterTest, negativeValues)
TEST (RangeFilterTest, simple_logic)
TEST (RangeFilterTest, case_1659)
TEST (RangeFilterTest, stream_logic)
TEST (RangeFilterTest, nan)
Function Documentation
TEST (RangeFilterTest , createStage)
Definition at line 49 of file RangeFilterTest.cpp.
References pdal::StageFactory::createStage(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, and hag::filter().
TEST (RangeFilterTest , noLimits)
Definition at line 56 of file RangeFilterTest.cpp.
References hag::filter(), and pdal::Stage::prepare().
TEST (RangeFilterTest , singleDimension)
Definition at line 64 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::Z.
TEST (RangeFilterTest , multipleDimensions)
Definition at line 95 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (RangeFilterTest , multipleDimsBusted)
Definition at line 130 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (RangeFilterTest , onlyMin)
Definition at line 169 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::Z.
TEST (RangeFilterTest , onlyMax)
Definition at line 202 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::Z.
TEST (RangeFilterTest , negation)
Definition at line 236 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::Z.
TEST (RangeFilterTest , equals)
Definition at line 271 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::Z.
TEST (RangeFilterTest , negativeValues)
Definition at line 300 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::Z.
TEST (RangeFilterTest , simple_logic)
Definition at line 330 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::BOX3D, pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::X.
TEST (RangeFilterTest , case_1659)
Definition at line 363 of file RangeFilterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (RangeFilterTest , stream_logic)
Definition at line 387 of file RangeFilterTest.cpp.
References pdal::Options::add(), pdal::BOX3D, pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Stage::prepare(), pdal::StreamCallbackFilter::setCallback(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::X.
TEST (RangeFilterTest , nan)
Definition at line 433 of file RangeFilterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), hag::filter(), pdal::Stage::prepare(), pdal::Stage::setInput(), and pdal::Stage::setOptions().