PDAL: pdal/plugins/rxp/test/RxpReaderTest.cpp File Reference
RxpReaderTest.cpp File Reference
#include <limits>
#include <pdal/pdal_test_main.hpp>
#include <pdal/Options.hpp>
#include <pdal/PipelineManager.hpp>
#include <pdal/PointView.hpp>
#include "RxpReader.hpp"
#include "Config.hpp"
Functions
Options defaultRxpReaderOptions ()
template<typename T >
void checkDimensionClose (const PointViewPtr view, std::size_t index, Dimension::Id dim, T expected)
template<typename T >
void checkDimensionEqual (const PointViewPtr view, std::size_t index, Dimension::Id dim, T expected)
void checkPoint (const PointViewPtr view, std::size_t index, float x, float y, float z, double time, double echoRange, float amplitude, float reflectance, float deviation, bool isPpsLocked, uint8_t returnNumber, uint8_t numberOfReturns)
TEST (RxpReaderTest, testConstructor)
TEST (RxpReaderTest, testRead)
TEST (RxpReaderTest, testNoPpsSync)
TEST (RxpReaderTest, testReflectanceAsIntensity)
Function Documentation
template<typename T > void checkDimensionClose (const PointViewPtr view, std::size_t index, Dimension::Id dim, T expected)
Definition at line 57 of file RxpReaderTest.cpp.
Referenced by checkPoint().
template<typename T > void checkDimensionEqual (const PointViewPtr view, std::size_t index, Dimension::Id dim, T expected)
Definition at line 67 of file RxpReaderTest.cpp.
Referenced by checkPoint().
void checkPoint (const PointViewPtr view, std::size_t index, float x, float y, float z, double time, double echoRange, float amplitude, float reflectance, float deviation, bool isPpsLocked, uint8_t returnNumber, uint8_t numberOfReturns)
Definition at line 76 of file RxpReaderTest.cpp.
References pdal::Dimension::Amplitude, checkDimensionClose(), checkDimensionEqual(), pdal::Dimension::Deviation, pdal::Dimension::EchoRange, pdal::getTimeDimensionId(), pdal::Dimension::IsPpsLocked, pdal::Dimension::NumberOfReturns, pdal::Dimension::Reflectance, pdal::Dimension::ReturnNumber, pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Options defaultRxpReaderOptions ()
Definition at line 48 of file RxpReaderTest.cpp.
References pdal::Options::add().
Referenced by TEST().
TEST (RxpReaderTest , testConstructor)
Definition at line 101 of file RxpReaderTest.cpp.
References defaultRxpReaderOptions(), pdal::RxpReader::getName(), and pdal::Stage::setOptions().
TEST (RxpReaderTest , testRead)
Definition at line 109 of file RxpReaderTest.cpp.
References pdal::checkPoint(), defaultRxpReaderOptions(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (RxpReaderTest , testNoPpsSync)
Definition at line 131 of file RxpReaderTest.cpp.
References pdal::Options::add(), pdal::checkPoint(), defaultRxpReaderOptions(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (RxpReaderTest , testReflectanceAsIntensity)
Definition at line 149 of file RxpReaderTest.cpp.
References pdal::Options::add(), defaultRxpReaderOptions(), pdal::Stage::execute(), pdal::Dimension::Intensity, pdal::Stage::prepare(), and pdal::Stage::setOptions().