PDAL: pdal/test/unit/io/SbetWriterTest.cpp File Reference
SbetWriterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/util/FileUtils.hpp>
#include <io/SbetReader.hpp>
#include <io/SbetWriter.hpp>
#include "Support.hpp"
Functions
Options makeReaderOptions ()
Options makeWriterOptions ()
TEST (SbetWriterTest, testConstructor)
TEST (SbetWriterTest, testWrite)
Function Documentation
Options makeReaderOptions ()
Definition at line 45 of file SbetWriterTest.cpp.
References pdal::Options::add(), and Support::datapath().
Referenced by TEST().
Options makeWriterOptions ()
Definition at line 54 of file SbetWriterTest.cpp.
References pdal::Options::add(), and Support::temppath().
Referenced by TEST().
TEST (SbetWriterTest , testConstructor)
Definition at line 61 of file SbetWriterTest.cpp.
References pdal::SbetWriter::getName(), makeReaderOptions(), makeWriterOptions(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (SbetWriterTest , testWrite)
EXPECT_TRUE(Support::compare_files(Support::temppath("SbetWriterTest.sbet"), Support::datapath("sbet/2-points.sbet")));
Definition at line 72 of file SbetWriterTest.cpp.
References pdal::FileUtils::deleteFile(), pdal::Stage::execute(), makeReaderOptions(), makeWriterOptions(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().