PDAL: pdal/test/unit/io/SbetReaderTest.cpp File Reference
SbetReaderTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/Options.hpp>
#include <pdal/PipelineManager.hpp>
#include <pdal/PointView.hpp>
#include <pdal/util/FileUtils.hpp>
#include <io/SbetReader.hpp>
#include "Support.hpp"
Functions
void checkPoint (const PointView &data, PointId index, double time, double latitude, double longitude, double altitude, double xvelocity, double yvelocity, double zvelocity, double roll, double pitch, double heading, double wander, double xaccel, double yaccel, double zaccel, double xangrate, double yangrate, double zangrate)
TEST (SbetReaderTest, testRead)
TEST (SbetReaderTest, testBadFile)
TEST (SbetReaderTest, testPipelineJSON)
Function Documentation
void checkPoint (const PointView & data, PointId index, double time, double latitude, double longitude, double altitude, double xvelocity, double yvelocity, double zvelocity, double roll, double pitch, double heading, double wander, double xaccel, double yaccel, double zaccel, double xangrate, double yangrate, double zangrate)
Definition at line 47 of file SbetReaderTest.cpp.
References pdal::Dimension::Azimuth, checkDimension(), pdal::PointView::getFieldAs(), pdal::Dimension::GpsTime, pdal::Dimension::Pitch, pdal::Dimension::Roll, pdal::Dimension::WanderAngle, pdal::Dimension::X, pdal::Dimension::XBodyAccel, pdal::Dimension::XBodyAngRate, pdal::Dimension::XVelocity, pdal::Dimension::Y, pdal::Dimension::YBodyAccel, pdal::Dimension::YBodyAngRate, pdal::Dimension::YVelocity, pdal::Dimension::Z, pdal::Dimension::ZBodyAccel, pdal::Dimension::ZBodyAngRate, and pdal::Dimension::ZVelocity.
TEST (SbetReaderTest , testRead)
Definition at line 79 of file SbetReaderTest.cpp.
References pdal::Options::add(), pdal::checkPoint(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (SbetReaderTest , testBadFile)
Definition at line 118 of file SbetReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (SbetReaderTest , testPipelineJSON)
Definition at line 131 of file SbetReaderTest.cpp.
References Support::configuredpath(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::PipelineManager::execute(), and pdal::PipelineManager::readPipeline().