PDAL: pdal/test/unit/filters/SortFilterTest.cpp File Reference
SortFilterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <random>
#include <pdal/PipelineManager.hpp>
#include <pdal/StageWrapper.hpp>
#include <io/LasReader.hpp>
#include <io/LasWriter.hpp>
#include <filters/SortFilter.hpp>
#include "Support.hpp"
Namespaces
anonymous_namespace{SortFilterTest.cpp}
Functions
void anonymous_namespace{SortFilterTest.cpp}::doSort (point_count_t count, const std::string &dim="X", const std::string &order="")
TEST (SortFilterTest, simple)
TEST (SortFilterTest, testUnknownOptions)
TEST (SortFilterTest, pipelineJSON)
TEST (SortFilterTest, issue1382)
TEST (SortFilterTest, issue1121_simpleSortOrderDesc)
Function Documentation
TEST (SortFilterTest , simple)
Definition at line 92 of file SortFilterTest.cpp.
References anonymous_namespace{SortFilterTest.cpp}::doSort().
TEST (SortFilterTest , testUnknownOptions)
Definition at line 100 of file SortFilterTest.cpp.
References anonymous_namespace{SortFilterTest.cpp}::doSort().
TEST (SortFilterTest , pipelineJSON)
Definition at line 106 of file SortFilterTest.cpp.
References Support::configuredpath(), pdal::PipelineManager::execute(), pdal::PipelineManager::readPipeline(), pdal::PipelineManager::views(), and pdal::Dimension::X.
TEST (SortFilterTest , issue1382)
Definition at line 126 of file SortFilterTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), and pdal::Dimension::Z.
TEST (SortFilterTest , issue1121_simpleSortOrderDesc)
Definition at line 162 of file SortFilterTest.cpp.
References anonymous_namespace{SortFilterTest.cpp}::doSort().