PDAL: pdal/test/unit/SpatialReferenceTest.cpp File Reference
SpatialReferenceTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/SpatialReference.hpp>
#include <pdal/Polygon.hpp>
#include <pdal/util/FileUtils.hpp>
#include <filters/ReprojectionFilter.hpp>
#include <filters/MergeFilter.hpp>
#include <io/LasWriter.hpp>
#include <io/LasReader.hpp>
#include <gdal_version.h>
#include "Support.hpp"
Functions
TEST (SpatialReferenceTest, test_env_vars)
TEST (SpatialReferenceTest, test_ctor)
TEST (SpatialReferenceTest, test_proj4_roundtrip)
TEST (SpatialReferenceTest, test_userstring_roundtrip)
TEST (SpatialReferenceTest, test_get_utmzone)
TEST (SpatialReferenceTest, calcZone)
TEST (SpatialReferenceTest, test_read_srs)
TEST (SpatialReferenceTest, test_writing_vlr)
TEST (SpatialReferenceTest, test_io)
TEST (SpatialReferenceTest, test_vertical_and_horizontal)
TEST (SpatialReferenceTest, merge)
TEST (SpatialReferenceTest, test_bounds)
Function Documentation
TEST (SpatialReferenceTest , test_env_vars)
Definition at line 51 of file SpatialReferenceTest.cpp.
References pdal::FileUtils::fileExists(), and pdal::Utils::getenv().
TEST (SpatialReferenceTest , test_ctor)
Definition at line 63 of file SpatialReferenceTest.cpp.
References pdal::SpatialReference::empty(), pdal::SpatialReference::getProj4(), and pdal::SpatialReference::getWKT().
TEST (SpatialReferenceTest , test_proj4_roundtrip)
Definition at line 73 of file SpatialReferenceTest.cpp.
References pdal::Utils::contains(), pdal::SpatialReference::empty(), and pdal::SpatialReference::getProj4().
TEST (SpatialReferenceTest , test_userstring_roundtrip)
Definition at line 106 of file SpatialReferenceTest.cpp.
References pdal::SpatialReference::getProj4(), and pdal::SpatialReference::getWKT().
TEST (SpatialReferenceTest , test_get_utmzone)
Definition at line 124 of file SpatialReferenceTest.cpp.
References pdal::SpatialReference::computeUTMZone().
TEST (SpatialReferenceTest , calcZone)
Definition at line 138 of file SpatialReferenceTest.cpp.
References pdal::SpatialReference::calculateZone().
TEST (SpatialReferenceTest , test_read_srs)
Definition at line 158 of file SpatialReferenceTest.cpp.
References pdal::Options::add(), pdal::Utils::contains(), Support::datapath(), pdal::Stage::execute(), pdal::SpatialReference::getProj4(), pdal::Stage::getSpatialReference(), pdal::SpatialReference::getWKT(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (SpatialReferenceTest , test_writing_vlr)
TEST(SpatialReferenceTest, test_vertical_datums) { std::string tmpfile(Support::temppath("tmp_srs.las")); FileUtils::deleteFile(tmpfile);
const std::string wkt = "COMPD_CS[\"unknown",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4326"]],VERT_CS["NAVD88 height",VERT_DATUM["North American Vertical Datum 1988",2005,AUTHORITY["EPSG","5103"],EXTENSION["PROJ4_GRIDS","g2012a_conus.gtx,g2012a_alaska.gtx,g2012a_guam.gtx,g2012a_hawaii.gtx,g2012a_puertorico.gtx,g2012a_samoa.gtx"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Up",UP],AUTHORITY["EPSG","5703"]]]";
SpatialReference ref(wkt); const std::string wktCheck = ref.getWKT(); EXPECT_EQ(wkt, wktCheck); // just to make sure
PointTable table; Write a very simple file with our SRS and one point. Options ops1; ops1.add("filename", Support::datapath("las/1.2-with-color.las")); LasReader reader; reader.setOptions(ops1);
Options opts; opts.add("filename", tmpfile);
LasWriter writer; writer.setOptions(opts); writer.setInput(reader); writer.setSpatialReference(ref); writer.prepare(table); writer.execute(table); SpatialReference sr = writer.getSpatialReference();
Reopen and check contents. PointTable table2; LasReader reader2; reader2.setOptions(opts); reader2.prepare(table2); reader2.execute(table2);
const SpatialReference ref2 = reader2.getSpatialReference(); const std::string wkt2 = ref2.getWKT();
EXPECT_EQ(wkt, wkt2);
Cleanup FileUtils::deleteFile(tmpfile); }
Definition at line 243 of file SpatialReferenceTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::getSpatialReference(), pdal::SpatialReference::getWKT(), pdal::LasReader::header(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Stage::setSpatialReference(), Support::temppath(), and pdal::LasHeader::vlrCount().
TEST (SpatialReferenceTest , test_io)
Definition at line 299 of file SpatialReferenceTest.cpp.
TEST (SpatialReferenceTest , test_vertical_and_horizontal)
Definition at line 315 of file SpatialReferenceTest.cpp.
References pdal::SpatialReference::getHorizontal(), and pdal::SpatialReference::getVertical().
TEST (SpatialReferenceTest , merge)
Definition at line 331 of file SpatialReferenceTest.cpp.
References pdal::Options::add(), Support::checkXYZ(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and Support::temppath().
TEST (SpatialReferenceTest , test_bounds)
Definition at line 379 of file SpatialReferenceTest.cpp.
References pdal::Geometry::bounds(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::Geometry::setSpatialReference(), and pdal::Polygon::transform().