PDAL: pdal/test/unit/filters/SplitterTest.cpp File Reference
SplitterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/StageFactory.hpp>
#include <pdal/StageWrapper.hpp>
#include <io/LasReader.hpp>
#include <filters/SplitterFilter.hpp>
#include "Support.hpp"
Functions
TEST (SplitterTest, test_tile_filter)
TEST (SplitterTest, test_buffer)
Function Documentation
TEST (SplitterTest , test_tile_filter)
Definition at line 45 of file SplitterTest.cpp.
References pdal::Options::add(), b, Support::datapath(), pdal::StageWrapper::done(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::Stage::prepare(), pdal::StageWrapper::ready(), pdal::StageWrapper::run(), pdal::Stage::setInput(), and pdal::Stage::setOptions().
TEST (SplitterTest , test_buffer)
Definition at line 117 of file SplitterTest.cpp.
References pdal::Options::add(), b, Support::datapath(), pdal::StageWrapper::done(), pdal::BOX2D::maxx, pdal::BOX2D::maxy, pdal::BOX2D::minx, pdal::BOX2D::miny, pdal::Stage::prepare(), readerOptions(), pdal::StageWrapper::ready(), pdal::StageWrapper::run(), pdal::Stage::setInput(), and pdal::Stage::setOptions().