PDAL: pdal/plugins/sqlite/test/SQLiteTest.cpp File Reference
SQLiteTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/util/FileUtils.hpp>
#include <pdal/StageFactory.hpp>
#include <pdal/PointView.hpp>
#include <pdal/pdal_defines.h>
#include <io/LasReader.hpp>
#include "../io/SQLiteCommon.hpp"
#include "Support.hpp"
Functions
std::string tempFilename (Support::temppath("temp-SqliteWriterTest_test_simple_las.sqlite"))
Options getWriterOptions ()
Options getReaderOptions ()
void testReadWrite (bool compression, bool scaling)
TEST (SQLiteTest, readWrite)
TEST (SQLiteTest, readWriteScale)
TEST (SQLiteTest, Issue895)
TEST (SQLiteTest, testSpatialite)
TEST (SQLiteTest, testVersionInfo)
Function Documentation
Options getReaderOptions ()
Definition at line 68 of file SQLiteTest.cpp.
References pdal::Options::add(), and tempFilename().
Referenced by testReadWrite().
Options getWriterOptions ()
Definition at line 53 of file SQLiteTest.cpp.
References pdal::Options::add(), and tempFilename().
Referenced by testReadWrite().
std::string tempFilename (Support::temppath("temp-SqliteWriterTest_test_simple_las.sqlite"))
Referenced by pdal::Utils::createFile(), getReaderOptions(), getWriterOptions(), pdal::Utils::openFile(), and testReadWrite().
TEST (SQLiteTest , readWrite)
Definition at line 141 of file SQLiteTest.cpp.
References pdal::TEST(), and testReadWrite().
TEST (SQLiteTest , readWriteScale)
Definition at line 153 of file SQLiteTest.cpp.
References pdal::TEST(), and testReadWrite().
TEST (SQLiteTest , Issue895)
Definition at line 165 of file SQLiteTest.cpp.
References c, pdal::SQLite::connect(), pdal::column::data, pdal::Debug, pdal::FileUtils::deleteFile(), pdal::SQLite::doesTableExist(), pdal::SQLite::execute(), pdal::SQLite::get(), setup::log, pdal::SQLite::next(), pdal::SQLite::query(), and Support::temppath().
TEST (SQLiteTest , testSpatialite)
Definition at line 232 of file SQLiteTest.cpp.
References pdal::SQLite::connect(), pdal::Debug, pdal::FileUtils::deleteFile(), pdal::SQLite::haveSpatialite(), pdal::SQLite::initSpatialiteMetadata(), pdal::SQLite::loadSpatialite(), setup::log, and Support::temppath().
TEST (SQLiteTest , testVersionInfo)
Definition at line 255 of file SQLiteTest.cpp.
References pdal::SQLite::connect(), pdal::Debug, pdal::FileUtils::deleteFile(), pdal::SQLite::getSpatialiteVersion(), pdal::SQLite::getSQLiteVersion(), pdal::SQLite::loadSpatialite(), setup::log, and Support::temppath().
void testReadWrite (bool compression, bool scaling)
Definition at line 83 of file SQLiteTest.cpp.
References pdal::Options::add(), pdal::StageFactory::createStage(), Support::datapath(), pdal::FileUtils::deleteFile(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, getReaderOptions(), getWriterOptions(), pdal::Dimension::Red, pdal::Stage::setOptions(), tempFilename(), writerOptions(), and pdal::Dimension::X.
Referenced by TEST().