PDAL: pdal/test/unit/filters/StatsFilterTest.cpp File Reference
StatsFilterTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/PDALUtils.hpp>
#include <pdal/StageFactory.hpp>
#include <filters/StatsFilter.hpp>
#include <io/FauxReader.hpp>
#include "Support.hpp"
Functions
TEST (Stats, simple)
TEST (Stats, stream)
TEST (Stats, dimset)
TEST (Stats, metadata)
TEST (Stats, enum)
TEST (Stats, global)
Function Documentation
TEST (Stats , simple)
Definition at line 46 of file StatsFilterTest.cpp.
References pdal::Options::add(), pdal::stats::Summary::average(), pdal::stats::Summary::count(), pdal::StageFactory::createStage(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::StatsFilter::getName(), pdal::StatsFilter::getStats(), pdal::stats::Summary::maximum(), pdal::stats::Summary::minimum(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (Stats , stream)
Definition at line 90 of file StatsFilterTest.cpp.
References pdal::Options::add(), pdal::stats::Summary::average(), pdal::stats::Summary::count(), pdal::StageFactory::createStage(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::StatsFilter::getName(), pdal::StatsFilter::getStats(), pdal::stats::Summary::maximum(), pdal::stats::Summary::minimum(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (Stats , dimset)
Definition at line 134 of file StatsFilterTest.cpp.
References pdal::Options::add(), pdal::stats::Summary::average(), pdal::stats::Summary::count(), pdal::StageFactory::createStage(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::StatsFilter::getName(), pdal::StatsFilter::getStats(), pdal::stats::Summary::maximum(), pdal::stats::Summary::minimum(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
TEST (Stats , metadata)
Definition at line 176 of file StatsFilterTest.cpp.
References pdal::Options::add(), pdal::MetadataNode::children(), pdal::StageFactory::createStage(), pdal::Stage::execute(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::MetadataNode::find(), pdal::Stage::getMetadata(), pdal::MetadataNode::name(), pdal::Dimension::name(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::MetadataNode::value().
TEST (Stats , enum)
Definition at line 230 of file StatsFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), hag::filter(), pdal::StatsFilter::getStats(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), pdal::stats::Summary::values(), pdal::Dimension::X, and pdal::Dimension::Y.
TEST (Stats , global)
Definition at line 275 of file StatsFilterTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), hag::filter(), pdal::StatsFilter::getStats(), pdal::stats::Summary::mad(), pdal::stats::Summary::maximum(), pdal::stats::Summary::median(), pdal::stats::Summary::minimum(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), and pdal::Dimension::Z.