PDAL: pdal::BpfPolarHeader Struct Reference
pdal::BpfPolarHeader Struct Reference
#include <BpfHeader.hpp>
Public Member Functions
bool read (ILeStream &stream)
Public Attributes
uint32_t m_numFrames
uint16_t m_fpaId
uint32_t m_numXmit
uint32_t m_numRcv
std::vector< BpfPolarStokesParam > m_xmitStates
std::vector< BpfMuellerMatrix > m_psaSettings
Detailed Description
Definition at line 243 of file BpfHeader.hpp.
Member Function Documentation
bool pdal::BpfPolarHeader::read (ILeStream & stream)
Definition at line 390 of file BpfHeader.cpp.
References pdal::IStream::get(), pdal::BpfPolarStokesParam::read(), pdal::IStreamMarker::rewind(), and pdal::Dimension::size().
Referenced by pdal::BpfReader::readPolarData().
Member Data Documentation
uint16_t pdal::BpfPolarHeader::m_fpaId
Definition at line 246 of file BpfHeader.hpp.
uint32_t pdal::BpfPolarHeader::m_numFrames
Definition at line 245 of file BpfHeader.hpp.
Referenced by pdal::BpfReader::readPolarData().
uint32_t pdal::BpfPolarHeader::m_numRcv
Definition at line 248 of file BpfHeader.hpp.
uint32_t pdal::BpfPolarHeader::m_numXmit
Definition at line 247 of file BpfHeader.hpp.
std::vector<BpfMuellerMatrix> pdal::BpfPolarHeader::m_psaSettings
Definition at line 250 of file BpfHeader.hpp.
std::vector<BpfPolarStokesParam> pdal::BpfPolarHeader::m_xmitStates
Definition at line 249 of file BpfHeader.hpp.
The documentation for this struct was generated from the following files:
pdal/io/BpfHeader.hpp
pdal/io/BpfHeader.cpp