PDAL: pdal::Tree Struct Reference
pdal::Tree Struct Reference
Public Member Functions
Tree (BBox bbox, const QuadPointRef *data=0)
void getFills (std::vector< std::size_t > &fills, std::size_t level=0) const
std::size_t addPoint (const QuadPointRef *toAdd, std::size_t curDepth=0)
void getPoints (std::vector< PointId > &results, std::size_t depthBegin, std::size_t depthEnd, std::size_t curDepth) const
void getPoints (std::vector< PointId > &results, std::size_t rasterize, double xBegin, double xEnd, double xStep, double yBegin, double yEnd, double yStep, std::size_t curDepth) const
void getPoints (std::vector< PointId > &results, double xBegin, double xEnd, double xStep, double yBegin, double yEnd, double yStep) const
void getPoints (std::vector< PointId > &results, const BBox &query, std::size_t depthBegin, std::size_t depthEnd, std::size_t curDepth) const
Public Attributes
const BBox bbox
const QuadPointRef * data
std::unique_ptr< Tree > nw
std::unique_ptr< Tree > ne
std::unique_ptr< Tree > se
std::unique_ptr< Tree > sw
Detailed Description
Definition at line 113 of file QuadIndex.cpp.
Constructor & Destructor Documentation
pdal::Tree::Tree (BBox bbox, const QuadPointRef * data = 0)
Definition at line 115 of file QuadIndex.cpp.
References setup::level.
Member Function Documentation
std::size_t pdal::Tree::addPoint (const QuadPointRef * toAdd, std::size_t curDepth = 0)
Definition at line 171 of file QuadIndex.cpp.
References anonymous_namespace{GreyhoundReaderTest.cpp}::center, pdal::QuadPointRef::point, pdal::Point::sqDist(), pdal::swap(), pdal::Point::x, and pdal::Point::y.
void pdal::Tree::getFills (std::vector< std::size_t > & fills, std::size_t level = 0) const
Definition at line 267 of file QuadIndex.cpp.
References setup::level.
void pdal::Tree::getPoints (std::vector< PointId > & results, std::size_t depthBegin, std::size_t depthEnd, std::size_t curDepth) const
Definition at line 284 of file QuadIndex.cpp.
void pdal::Tree::getPoints (std::vector< PointId > & results, std::size_t rasterize, double xBegin, double xEnd, double xStep, double yBegin, double yEnd, double yStep, std::size_t curDepth) const
Definition at line 304 of file QuadIndex.cpp.
References pdal::Utils::sround().
void pdal::Tree::getPoints (std::vector< PointId > & results, double xBegin, double xEnd, double xStep, double yBegin, double yEnd, double yStep) const
Definition at line 378 of file QuadIndex.cpp.
References pdal::Utils::sround().
void pdal::Tree::getPoints (std::vector< PointId > & results, const BBox & query, std::size_t depthBegin, std::size_t depthEnd, std::size_t curDepth) const
Definition at line 451 of file QuadIndex.cpp.
Member Data Documentation
const BBox pdal::Tree::bbox
Definition at line 162 of file QuadIndex.cpp.
const QuadPointRef* pdal::Tree::data
Definition at line 163 of file QuadIndex.cpp.
std::unique_ptr<Tree> pdal::Tree::ne
Definition at line 166 of file QuadIndex.cpp.
std::unique_ptr<Tree> pdal::Tree::nw
Definition at line 165 of file QuadIndex.cpp.
std::unique_ptr<Tree> pdal::Tree::se
Definition at line 167 of file QuadIndex.cpp.
std::unique_ptr<Tree> pdal::Tree::sw
Definition at line 168 of file QuadIndex.cpp.
The documentation for this struct was generated from the following file:
pdal/pdal/QuadIndex.cpp