PDAL: pdal::PlyReader::ListProperty Struct Reference
pdal::PlyReader::ListProperty Struct Reference
Public Member Functions
ListProperty (const std::string &name, Dimension::Type countType, Dimension::Type listType)
virtual void read (std::istream *stream, PlyReader::Format format, PointRef &point) override
virtual void setDim (Dimension::Id id)
Public Attributes
Dimension::Type m_countType
Dimension::Type m_listType
std::string m_name
Detailed Description
Definition at line 98 of file PlyReader.hpp.
Constructor & Destructor Documentation
pdal::PlyReader::ListProperty::ListProperty (const std::string & name, Dimension::Type countType, Dimension::Type listType)
Definition at line 100 of file PlyReader.hpp.
Member Function Documentation
void pdal::PlyReader::ListProperty::read (std::istream * stream, PlyReader::Format format, PointRef & point) override virtual
Implements pdal::PlyReader::Property.
Definition at line 362 of file PlyReader.cpp.
References pdal::PlyReader::Ascii, pdal::PlyReader::BinaryBe, pdal::PlyReader::BinaryLe, pdal::Utils::extractDim(), pdal::IStream::seek(), pdal::Dimension::size(), and pdal::Utils::toDouble().
virtual void pdal::PlyReader::Property::setDim (Dimension::Id id) virtual inherited
Reimplemented in pdal::PlyReader::SimpleProperty.
Definition at line 77 of file PlyReader.hpp.
References hag::read().
Member Data Documentation
Dimension::Type pdal::PlyReader::ListProperty::m_countType
Definition at line 105 of file PlyReader.hpp.
Dimension::Type pdal::PlyReader::ListProperty::m_listType
Definition at line 106 of file PlyReader.hpp.
std::string pdal::PlyReader::Property::m_name inherited
Definition at line 75 of file PlyReader.hpp.
The documentation for this struct was generated from the following files:
pdal/io/PlyReader.hpp
pdal/io/PlyReader.cpp