PDAL: pdal::BpfUlemHeader Struct Reference
pdal::BpfUlemHeader Struct Reference
#include <BpfHeader.hpp>
Public Member Functions
bool read (ILeStream &stream)
Public Attributes
uint32_t m_numFrames
uint16_t m_year
uint8_t m_month
uint8_t m_day
uint16_t m_lidarMode
uint16_t m_wavelen
uint16_t m_pulseFreq
uint16_t m_focalWidth
uint16_t m_focalHeight
float m_pixelPitchWidth
float m_pixelPitchHeight
std::string m_classCode
Detailed Description
Definition at line 183 of file BpfHeader.hpp.
Member Function Documentation
bool pdal::BpfUlemHeader::read (ILeStream & stream)
Definition at line 318 of file BpfHeader.cpp.
References pdal::IStream::get(), and pdal::IStreamMarker::rewind().
Referenced by pdal::BpfReader::readUlemData().
Member Data Documentation
std::string pdal::BpfUlemHeader::m_classCode
Definition at line 196 of file BpfHeader.hpp.
uint8_t pdal::BpfUlemHeader::m_day
Definition at line 188 of file BpfHeader.hpp.
uint16_t pdal::BpfUlemHeader::m_focalHeight
Definition at line 193 of file BpfHeader.hpp.
uint16_t pdal::BpfUlemHeader::m_focalWidth
Definition at line 192 of file BpfHeader.hpp.
uint16_t pdal::BpfUlemHeader::m_lidarMode
Definition at line 189 of file BpfHeader.hpp.
uint8_t pdal::BpfUlemHeader::m_month
Definition at line 187 of file BpfHeader.hpp.
uint32_t pdal::BpfUlemHeader::m_numFrames
Definition at line 185 of file BpfHeader.hpp.
Referenced by pdal::BpfReader::readUlemData().
float pdal::BpfUlemHeader::m_pixelPitchHeight
Definition at line 195 of file BpfHeader.hpp.
float pdal::BpfUlemHeader::m_pixelPitchWidth
Definition at line 194 of file BpfHeader.hpp.
uint16_t pdal::BpfUlemHeader::m_pulseFreq
Definition at line 191 of file BpfHeader.hpp.
uint16_t pdal::BpfUlemHeader::m_wavelen
Definition at line 190 of file BpfHeader.hpp.
uint16_t pdal::BpfUlemHeader::m_year
Definition at line 186 of file BpfHeader.hpp.
The documentation for this struct was generated from the following files:
pdal/io/BpfHeader.hpp
pdal/io/BpfHeader.cpp