PDAL: pdal::DimRange Struct Reference
pdal::DimRange Struct Reference
#include <DimRange.hpp>
Classes
struct error
Public Member Functions
DimRange (const std::string name, double lower_bound, double upper_bound, bool inclusive_lower_bound, bool inclusive_upper_bound, bool negate)
DimRange ()
void parse (const std::string &s)
bool valuePasses (double d) const
Public Attributes
std::string m_name
Dimension::Id m_id
double m_lower_bound
double m_upper_bound
bool m_inclusive_lower_bound
bool m_inclusive_upper_bound
bool m_negate
Protected Member Functions
std::string::size_type subParse (const std::string &r)
Detailed Description
Definition at line 44 of file DimRange.hpp.
Constructor & Destructor Documentation
pdal::DimRange::DimRange (const std::string name, double lower_bound, double upper_bound, bool inclusive_lower_bound, bool inclusive_upper_bound, bool negate)
Definition at line 52 of file DimRange.hpp.
pdal::DimRange::DimRange ()
Definition at line 65 of file DimRange.hpp.
References parse(), and valuePasses().
Member Function Documentation
void pdal::DimRange::parse (const std::string & s)
Definition at line 130 of file DimRange.cpp.
References subParse().
Referenced by DimRange(), pdal::RangeFilter::initialize(), and pdal::operator>>().
std::string::size_type pdal::DimRange::subParse (const std::string & r) protected
Definition at line 42 of file DimRange.cpp.
References pdal::Dimension::extractName(), pdal::Utils::extractSpaces(), m_inclusive_lower_bound, m_inclusive_upper_bound, m_lower_bound, m_name, m_negate, m_upper_bound, and pdal::Dimension::name().
Referenced by pdal::AssignRange::parse(), and parse().
bool pdal::DimRange::valuePasses (double d) const
Definition at line 116 of file DimRange.cpp.
References m_inclusive_lower_bound, m_inclusive_upper_bound, m_lower_bound, m_negate, and m_upper_bound.
Referenced by DimRange(), and pdal::Segmentation::ignoreDimRange().
Member Data Documentation
Dimension::Id pdal::DimRange::m_id
Definition at line 74 of file DimRange.hpp.
Referenced by pdal::Segmentation::ignoreDimRange(), pdal::PMFFilter::prepared(), and pdal::PMFFilter::run().
bool pdal::DimRange::m_inclusive_lower_bound
Definition at line 77 of file DimRange.hpp.
Referenced by pdal::operator<<(), subParse(), and valuePasses().
bool pdal::DimRange::m_inclusive_upper_bound
Definition at line 78 of file DimRange.hpp.
Referenced by pdal::operator<<(), subParse(), and valuePasses().
double pdal::DimRange::m_lower_bound
Definition at line 75 of file DimRange.hpp.
Referenced by pdal::operator<<(), subParse(), and valuePasses().
std::string pdal::DimRange::m_name
Definition at line 73 of file DimRange.hpp.
Referenced by pdal::operator<(), pdal::operator<<(), pdal::PMFFilter::prepared(), and subParse().
bool pdal::DimRange::m_negate
Definition at line 79 of file DimRange.hpp.
Referenced by subParse(), and valuePasses().
double pdal::DimRange::m_upper_bound
Definition at line 76 of file DimRange.hpp.
Referenced by pdal::operator<<(), subParse(), and valuePasses().
The documentation for this struct was generated from the following files:
pdal/filters/private/DimRange.hpp
pdal/filters/private/DimRange.cpp