PDAL: pdal::QuadIndex::QImpl Struct Reference
pdal::QuadIndex::QImpl Struct Reference
Public Member Functions
QImpl (const PointView &view, std::size_t topLevel)
QImpl (const PointView &view, double xMin, double yMin, double xMax, double yMax, std::size_t topLevel)
QImpl (const std::vector< std::shared_ptr< QuadPointRef > > &points, double xMin, double yMin, double xMax, double yMax, std::size_t topLevel)
void getBounds (double &xMin, double &yMin, double &xMax, double &yMax) const
std::size_t getDepth () const
std::vector< std::size_t > getFills ()
std::vector< PointId > getPoints (std::size_t depthBegin, std::size_t depthEnd) const
std::vector< PointId > getPoints (std::size_t rasterize, double &xBegin, double &xEnd, double &xStep, double &yBegin, double &yEnd, double &yStep) const
std::vector< PointId > getPoints (double xBegin, double xEnd, double xStep, double yBegin, double yEnd, double yStep) const
std::vector< PointId > getPoints (double xMin, double yMin, double xMax, double yMax, std::size_t depthBegin, std::size_t depthEnd) const
Public Attributes
std::size_t m_topLevel
std::vector< std::shared_ptr< QuadPointRef > > m_pointRefVec
std::unique_ptr< Tree > m_tree
std::size_t m_depth
std::vector< std::size_t > m_fills
Detailed Description
Definition at line 480 of file QuadIndex.cpp.
Constructor & Destructor Documentation
pdal::QuadIndex::QImpl::QImpl (const PointView & view, std::size_t topLevel)
Definition at line 544 of file QuadIndex.cpp.
References pdal::PointView::getFieldAs(), m_depth, m_pointRefVec, m_tree, pdal::QuadPointRef::point, pdal::PointView::size(), pdal::Dimension::X, pdal::Point::x, pdal::Dimension::Y, and pdal::Point::y.
pdal::QuadIndex::QImpl::QImpl (const PointView & view, double xMin, double yMin, double xMax, double yMax, std::size_t topLevel)
Definition at line 582 of file QuadIndex.cpp.
References pdal::PointView::getFieldAs(), m_depth, m_pointRefVec, m_tree, pdal::PointView::size(), pdal::Dimension::X, and pdal::Dimension::Y.
pdal::QuadIndex::QImpl::QImpl (const std::vector< std::shared_ptr< QuadPointRef > > & points, double xMin, double yMin, double xMax, double yMax, std::size_t topLevel)
Definition at line 615 of file QuadIndex.cpp.
References m_depth, m_pointRefVec, and m_tree.
Member Function Documentation
void pdal::QuadIndex::QImpl::getBounds (double & xMin, double & yMin, double & xMax, double & yMax) const
Definition at line 637 of file QuadIndex.cpp.
References m_tree.
std::size_t pdal::QuadIndex::QImpl::getDepth () const
Definition at line 652 of file QuadIndex.cpp.
References m_depth.
std::vector< std::size_t > pdal::QuadIndex::QImpl::getFills ()
Definition at line 657 of file QuadIndex.cpp.
References m_fills, and m_tree.
std::vector< PointId > pdal::QuadIndex::QImpl::getPoints (std::size_t depthBegin, std::size_t depthEnd) const
Definition at line 667 of file QuadIndex.cpp.
References m_topLevel, and m_tree.
std::vector< PointId > pdal::QuadIndex::QImpl::getPoints (std::size_t rasterize, double & xBegin, double & xEnd, double & xStep, double & yBegin, double & yEnd, double & yStep) const
Definition at line 681 of file QuadIndex.cpp.
References m_topLevel, and m_tree.
std::vector< PointId > pdal::QuadIndex::QImpl::getPoints (double xBegin, double xEnd, double xStep, double yBegin, double yEnd, double yStep) const
Definition at line 722 of file QuadIndex.cpp.
References m_tree, and pdal::Utils::sround().
std::vector< PointId > pdal::QuadIndex::QImpl::getPoints (double xMin, double yMin, double xMax, double yMax, std::size_t depthBegin, std::size_t depthEnd) const
Definition at line 751 of file QuadIndex.cpp.
References m_topLevel, and m_tree.
Member Data Documentation
std::size_t pdal::QuadIndex::QImpl::m_depth
Definition at line 540 of file QuadIndex.cpp.
Referenced by getDepth(), and QImpl().
std::vector<std::size_t> pdal::QuadIndex::QImpl::m_fills
Definition at line 541 of file QuadIndex.cpp.
Referenced by getFills().
std::vector<std::shared_ptr<QuadPointRef> > pdal::QuadIndex::QImpl::m_pointRefVec
Definition at line 538 of file QuadIndex.cpp.
Referenced by QImpl().
std::size_t pdal::QuadIndex::QImpl::m_topLevel
Definition at line 537 of file QuadIndex.cpp.
Referenced by getPoints().
std::unique_ptr<Tree> pdal::QuadIndex::QImpl::m_tree
Definition at line 539 of file QuadIndex.cpp.
Referenced by getBounds(), getFills(), getPoints(), and QImpl().
The documentation for this struct was generated from the following file:
pdal/pdal/QuadIndex.cpp