PDAL: pdal::BpfMuellerMatrix Struct Reference
pdal::BpfMuellerMatrix Struct Reference
#include <BpfHeader.hpp>
Public Member Functions
BpfMuellerMatrix ()
void dump ()
void apply (double &x, double &y, double &z)
Public Attributes
double m_vals [16]
Detailed Description
Definition at line 51 of file BpfHeader.hpp.
Constructor & Destructor Documentation
pdal::BpfMuellerMatrix::BpfMuellerMatrix ()
Definition at line 53 of file BpfHeader.hpp.
References m_vals.
Member Function Documentation
void pdal::BpfMuellerMatrix::apply (double & x, double & y, double & z)
Definition at line 81 of file BpfHeader.hpp.
References pdal::operator<<(), and pdal::operator>>().
Referenced by pdal::BpfReader::readByteMajor(), pdal::BpfReader::readDimMajor(), pdal::BpfReader::readPointMajor(), and TEST().
void pdal::BpfMuellerMatrix::dump ()
Definition at line 64 of file BpfHeader.hpp.
Referenced by pdal::BpfHeader::setLog().
Member Data Documentation
double pdal::BpfMuellerMatrix::m_vals[16]
Definition at line 62 of file BpfHeader.hpp.
Referenced by BpfMuellerMatrix(), pdal::operator<<(), pdal::operator>>(), pdal::BpfWriter::readyFile(), and TEST().
The documentation for this struct was generated from the following file:
pdal/io/BpfHeader.hpp