PDAL: pdal::BpfUlemFile Struct Reference
pdal::BpfUlemFile Struct Reference
#include <BpfHeader.hpp>
Public Member Functions
BpfUlemFile ()
BpfUlemFile (uint32_t len, const std::string &filename, const std::string &filespec)
bool read (ILeStream &stream)
bool write (OLeStream &stream)
Public Attributes
uint32_t m_len
std::string m_filename
std::vector< char > m_buf
std::string m_filespec
Detailed Description
Definition at line 214 of file BpfHeader.hpp.
Constructor & Destructor Documentation
pdal::BpfUlemFile::BpfUlemFile ()
Definition at line 221 of file BpfHeader.hpp.
pdal::BpfUlemFile::BpfUlemFile (uint32_t len, const std::string & filename, const std::string & filespec)
Definition at line 224 of file BpfHeader.hpp.
References hag::read().
Member Function Documentation
bool pdal::BpfUlemFile::read (ILeStream & stream)
Definition at line 343 of file BpfHeader.cpp.
References pdal::IStream::get(), pdal::BpfHeader::m_len, pdal::IStreamMarker::rewind(), and pdal::Utils::trimTrailing().
Referenced by pdal::BpfReader::readUlemFiles().
bool pdal::BpfUlemFile::write (OLeStream & stream)
Definition at line 363 of file BpfHeader.cpp.
References pdal::BpfHeader::m_len, and pdal::OStream::put().
Member Data Documentation
std::vector<char> pdal::BpfUlemFile::m_buf
Definition at line 218 of file BpfHeader.hpp.
Referenced by pdal::BpfReader::readUlemFiles().
std::string pdal::BpfUlemFile::m_filename
Definition at line 217 of file BpfHeader.hpp.
Referenced by pdal::BpfWriter::initialize(), and pdal::BpfReader::readUlemFiles().
std::string pdal::BpfUlemFile::m_filespec
Definition at line 219 of file BpfHeader.hpp.
uint32_t pdal::BpfUlemFile::m_len
Definition at line 216 of file BpfHeader.hpp.
Referenced by pdal::BpfReader::readUlemFiles().
The documentation for this struct was generated from the following files:
pdal/io/BpfHeader.hpp
pdal/io/BpfHeader.cpp