PDAL: pdal::GreyhoundReader::Args Struct Reference
pdal::GreyhoundReader::Args Struct Reference
Public Member Functions
std::string base () const
std::string query () const
Public Attributes
std::string url
std::string resource
std::string sbounds
std::size_t depthBegin = 0
std::size_t depthEnd = 0
std::string tilePath
Json::Value filter
Json::Value schema
Detailed Description
Definition at line 68 of file GreyhoundReader.hpp.
Member Function Documentation
std::string pdal::GreyhoundReader::Args::base () const
Definition at line 100 of file GreyhoundReader.cpp.
References anonymous_namespace{GreyhoundReaderTest.cpp}::resource().
Referenced by pdal::GreyhoundReader::initialize(), and pdal::GreyhoundReader::read().
std::string pdal::GreyhoundReader::Args::query () const
Definition at line 141 of file GreyhoundReader.cpp.
References pdal::anonymous_namespace{GreyhoundReader.cpp}::dense(), pdal::georeference::anonymous_namespace{Georeference.cpp}::f, hag::filter(), pdal::anonymous_namespace{GreyhoundReader.cpp}::parse(), and pdal::entwine::Bounds::toJson().
Referenced by pdal::GreyhoundReader::read().
Member Data Documentation
std::size_t pdal::GreyhoundReader::Args::depthBegin = 0
Definition at line 73 of file GreyhoundReader.hpp.
Referenced by pdal::GreyhoundReader::addArgs().
std::size_t pdal::GreyhoundReader::Args::depthEnd = 0
Definition at line 74 of file GreyhoundReader.hpp.
Referenced by pdal::GreyhoundReader::addArgs().
Json::Value pdal::GreyhoundReader::Args::filter
Definition at line 76 of file GreyhoundReader.hpp.
Referenced by pdal::GreyhoundReader::addArgs().
std::string pdal::GreyhoundReader::Args::resource
Definition at line 71 of file GreyhoundReader.hpp.
Referenced by pdal::GreyhoundReader::addArgs().
std::string pdal::GreyhoundReader::Args::sbounds
Definition at line 72 of file GreyhoundReader.hpp.
Referenced by pdal::GreyhoundReader::addArgs().
Json::Value pdal::GreyhoundReader::Args::schema
Definition at line 77 of file GreyhoundReader.hpp.
Referenced by pdal::GreyhoundReader::addArgs(), and pdal::GreyhoundReader::prepared().
std::string pdal::GreyhoundReader::Args::tilePath
Definition at line 75 of file GreyhoundReader.hpp.
Referenced by pdal::GreyhoundReader::addArgs().
std::string pdal::GreyhoundReader::Args::url
Definition at line 70 of file GreyhoundReader.hpp.
Referenced by pdal::GreyhoundReader::addArgs(), and pdal::GreyhoundReader::initialize().
The documentation for this struct was generated from the following files:
pdal/plugins/greyhound/io/GreyhoundReader.hpp
pdal/plugins/greyhound/io/GreyhoundReader.cpp