PDAL: pdal/test/unit/io/TextReaderTest.cpp File Reference
TextReaderTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include "Support.hpp"
#include <io/LasReader.hpp>
#include <io/LasWriter.hpp>
#include <io/TextReader.hpp>
#include <pdal/util/FileUtils.hpp>
Functions
void compareTextLas (const std::string &textFilename, Options &textOptions, const std::string &lasFilename)
void compareTextLas (const std::string &textFilename, const std::string &lasFilename)
void compareTextLasStreaming (const std::string &textFilename, const std::string &lasFilename)
TEST (TextReaderTest, t1)
TEST (TextReaderTest, t1a)
TEST (TextReaderTest, t2)
TEST (TextReaderTest, t3)
TEST (TextReaderTest, badheader)
TEST (TextReaderTest, s1)
TEST (TextReaderTest, strip_whitespace_from_dimension_names)
Function Documentation
void compareTextLas (const std::string & textFilename, Options & textOptions, const std::string & lasFilename)
Definition at line 46 of file TextReaderTest.cpp.
References pdal::Options::add(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setOptions(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by compareTextLas(), and TEST().
void compareTextLas (const std::string & textFilename, const std::string & lasFilename)
Definition at line 85 of file TextReaderTest.cpp.
References compareTextLas().
void compareTextLasStreaming (const std::string & textFilename, const std::string & lasFilename)
Definition at line 94 of file TextReaderTest.cpp.
References pdal::Options::add(), pdal::FileUtils::deleteFile(), pdal::Stage::execute(), pdal::Stage::prepare(), pdal::Stage::setInput(), pdal::Stage::setOptions(), Support::temppath(), pdal::Dimension::X, pdal::Dimension::Y, and pdal::Dimension::Z.
Referenced by TEST().
TEST (TextReaderTest , t1)
Definition at line 152 of file TextReaderTest.cpp.
References compareTextLas(), and Support::datapath().
TEST (TextReaderTest , t1a)
Definition at line 158 of file TextReaderTest.cpp.
References pdal::Options::add(), compareTextLas(), and Support::datapath().
TEST (TextReaderTest , t2)
Definition at line 168 of file TextReaderTest.cpp.
References compareTextLas(), and Support::datapath().
TEST (TextReaderTest , t3)
Definition at line 174 of file TextReaderTest.cpp.
References compareTextLas(), and Support::datapath().
TEST (TextReaderTest , badheader)
Definition at line 180 of file TextReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::prepare(), and pdal::Stage::setOptions().
TEST (TextReaderTest , s1)
Definition at line 191 of file TextReaderTest.cpp.
References compareTextLasStreaming(), and Support::datapath().
TEST (TextReaderTest , strip_whitespace_from_dimension_names)
Definition at line 197 of file TextReaderTest.cpp.
References pdal::Options::add(), Support::datapath(), pdal::Stage::execute(), pdal::Dimension::Intensity, pdal::Stage::prepare(), and pdal::Stage::setOptions().