PDAL: pdal/test/unit/apps/TranslateTest.cpp File Reference
TranslateTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/StageFactory.hpp>
#include <pdal/util/FileUtils.hpp>
#include <pdal/util/Utils.hpp>
#include "Support.hpp"
#include <iostream>
#include <sstream>
#include <string>
Functions
static int runTranslate (std::string const &cmdline, std::string &output)
TEST (translateTest, t1)
TEST (translateTest, t2)
TEST (translateTest, t3)
Function Documentation
static int runTranslate (std::string const & cmdline, std::string & output) static
Definition at line 48 of file TranslateTest.cpp.
References Support::binpath(), Support::exename(), and pdal::Utils::run_shell_command().
Referenced by TEST().
TEST (translateTest , t1)
Definition at line 56 of file TranslateTest.cpp.
References Support::datapath(), runTranslate(), and Support::temppath().
TEST (translateTest , t2)
Definition at line 75 of file TranslateTest.cpp.
References Support::datapath(), pdal::FileUtils::deleteFile(), runTranslate(), and Support::temppath().
TEST (translateTest , t3)
Definition at line 193 of file TranslateTest.cpp.
References Support::datapath(), pdal::Utils::run_shell_command(), runTranslate(), and Support::temppath().