PDAL: pdal/examples/writing/tutorial.cpp File Reference
tutorial.cpp File Reference
#include <pdal/PointView.hpp>
#include <pdal/PointTable.hpp>
#include <pdal/Dimension.hpp>
#include <pdal/Options.hpp>
#include <pdal/StageFactory.hpp>
#include <io/BufferReader.hpp>
#include <vector>
Functions
void fillView (pdal::PointViewPtr view)
int main (int argc, char *argv[])
Function Documentation
void fillView (pdal::PointViewPtr view)
Definition at line 11 of file tutorial.cpp.
References pdal::Dimension::X, pdal::Dimension::Y, pdal::Dimension::Z, and z.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 35 of file tutorial.cpp.
References pdal::Options::add(), pdal::BufferReader::addView(), pdal::StageFactory::createStage(), pdal::Stage::execute(), fillView(), pdal::BasePointTable::layout(), pdal::Stage::prepare(), pdal::PointLayout::registerDim(), pdal::Stage::setInput(), pdal::Stage::setOptions(), X, Y, and Z.