PDAL: pdal/test/unit/UtilsTest.cpp File Reference
UtilsTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/pdal_defines.h>
#include <sstream>
#include <pdal/util/Utils.hpp>
#include <vector>
Functions
TEST (UtilsTest, test_random)
TEST (UtilsTest, test_comparators)
TEST (UtilsTest, test_base64)
TEST (UtilsTest, blanks)
TEST (UtilsTest, split)
TEST (UtilsTest, splitChar)
TEST (UtilsTest, split2)
TEST (UtilsTest, split2Char)
TEST (UtilsTest, case)
TEST (UtilsTest, starts)
TEST (UtilsTest, iequals)
TEST (UtilsTest, replaceAll)
TEST (UtilsTest, escapeNonprinting)
TEST (UtilsTest, wordWrap)
TEST (UtilsTest, wordWrap2)
TEST (UtilsTest, simpleWordexpTest)
Function Documentation
TEST (UtilsTest , test_random)
Definition at line 46 of file UtilsTest.cpp.
References pdal::Utils::random(), and pdal::Utils::random_seed().
TEST (UtilsTest , test_comparators)
Definition at line 73 of file UtilsTest.cpp.
References pdal::Utils::compare_approx(), and pdal::georeference::anonymous_namespace{Georeference.cpp}::f.
TEST (UtilsTest , test_base64)
Definition at line 104 of file UtilsTest.cpp.
References pdal::Utils::base64_decode(), pdal::Utils::base64_encode(), and pdal::Dimension::size().
TEST (UtilsTest , blanks)
Definition at line 128 of file UtilsTest.cpp.
References pdal::Dimension::base(), pdal::Utils::trimLeading(), and pdal::Utils::trimTrailing().
TEST (UtilsTest , split)
Definition at line 162 of file UtilsTest.cpp.
References c, and pdal::Utils::split().
TEST (UtilsTest , splitChar)
Definition at line 192 of file UtilsTest.cpp.
References pdal::Utils::split().
TEST (UtilsTest , split2)
Definition at line 220 of file UtilsTest.cpp.
References c, and pdal::Utils::split2().
TEST (UtilsTest , split2Char)
Definition at line 257 of file UtilsTest.cpp.
References pdal::Utils::split2().
TEST (UtilsTest , case)
Definition at line 271 of file UtilsTest.cpp.
References pdal::Utils::tolower(), and pdal::Utils::toupper().
TEST (UtilsTest , starts)
Definition at line 288 of file UtilsTest.cpp.
References pdal::Utils::startsWith().
TEST (UtilsTest , iequals)
Definition at line 299 of file UtilsTest.cpp.
References pdal::Utils::iequals().
TEST (UtilsTest , replaceAll)
Definition at line 308 of file UtilsTest.cpp.
References pdal::Utils::replaceAll().
TEST (UtilsTest , escapeNonprinting)
Definition at line 316 of file UtilsTest.cpp.
References pdal::Utils::escapeNonprinting().
TEST (UtilsTest , wordWrap)
Definition at line 323 of file UtilsTest.cpp.
References pdal::Utils::wordWrap().
TEST (UtilsTest , wordWrap2)
Definition at line 349 of file UtilsTest.cpp.
References pdal::Utils::wordWrap2().
TEST (UtilsTest , simpleWordexpTest)
Definition at line 383 of file UtilsTest.cpp.
References pdal::Utils::simpleWordexp().