PDAL: pdal/test/unit/XMLSchemaTest.cpp File Reference
XMLSchemaTest.cpp File Reference
#include <pdal/pdal_test_main.hpp>
#include <pdal/util/FileUtils.hpp>
#include <pdal/util/Uuid.hpp>
#include <pdal/Metadata.hpp>
#include <pdal/PointTable.hpp>
#include <pdal/XMLSchema.hpp>
#include "Support.hpp"
#include "TestConfig.hpp"
#include <fstream>
Functions
std::string ReadXML (std::string filename)
TEST (XMLSchemaTest, read)
TEST (XMLSchemaTest, copy)
TEST (XMLSchemaTest, utf8)
TEST (XMLSchemaTest, precision)
TEST (XMLSchemaTest, nonstandard)
Function Documentation
std::string ReadXML (std::string filename)
Definition at line 50 of file XMLSchemaTest.cpp.
References pdal::FileUtils::openFile(), and pdal::Dimension::size().
Referenced by TEST().
TEST (XMLSchemaTest , read)
Definition at line 70 of file XMLSchemaTest.cpp.
References TestConfig::dataPath(), pdal::XForm::m_offset, pdal::XForm::m_scale, pdal::DimType::m_type, pdal::XForm::XFormComponent::m_val, pdal::DimType::m_xform, pdal::Dimension::name(), ReadXML(), pdal::Dimension::Signed32, pdal::Dimension::Unsigned16, pdal::Dimension::Unsigned8, xml, and pdal::XMLSchema::xmlDims().
TEST (XMLSchemaTest , copy)
Definition at line 135 of file XMLSchemaTest.cpp.
References pdal::MetadataNode::add(), TestConfig::dataPath(), pdal::BasePointTable::layout(), pdal::XMLDim::m_dimType, pdal::XMLDim::m_name, pdal::DimType::m_type, ReadXML(), pdal::PointLayout::registerOrAssignDim(), pdal::XMLSchema::setId(), xml, pdal::XMLSchema::xml(), and pdal::XMLSchema::xmlDims().
TEST (XMLSchemaTest , utf8)
Definition at line 185 of file XMLSchemaTest.cpp.
References pdal::MetadataNode::children(), TestConfig::dataPath(), pdal::XMLSchema::getMetadata(), pdal::XMLDim::m_description, ReadXML(), xml, and pdal::XMLSchema::xmlDims().
TEST (XMLSchemaTest , precision)
Definition at line 216 of file XMLSchemaTest.cpp.
References pdal::XMLDim::m_dimType, pdal::XForm::m_offset, pdal::XForm::m_scale, pdal::DimType::m_type, pdal::XForm::XFormComponent::m_val, pdal::DimType::m_xform, pdal::MetadataNode, pdal::Dimension::Signed32, pdal::Dimension::Unsigned32, pdal::Dimension::X, pdal::XMLSchema::xml(), pdal::XMLSchema::xmlDims(), and pdal::Dimension::Y.
TEST (XMLSchemaTest , nonstandard)
Definition at line 253 of file XMLSchemaTest.cpp.
References pdal::MetadataNode, pdal::Dimension::Signed32, xml, pdal::XMLSchema::xml(), and pdal::XMLSchema::xmlDims().