GEOS: geos::triangulate::quadedge::LastFoundQuadEdgeLocator Class Reference
geos::triangulate::quadedge::LastFoundQuadEdgeLocator Class Reference
#include <LastFoundQuadEdgeLocator.h>
Public Member Functions
LastFoundQuadEdgeLocator (QuadEdgeSubdivision *subdiv)
QuadEdge * locate (const Vertex &v) override
Private Member Functions
virtual void init ()
virtual QuadEdge * findEdge ()
Private Attributes
QuadEdgeSubdivision * subdiv
QuadEdge * lastEdge
Detailed Description
Locates QuadEdges in a QuadEdgeSubdivision, optimizing the search by starting in the locality of the last edge found.
Author
JTS: Martin Davis
Benjamin Campbell
Definition at line 41 of file LastFoundQuadEdgeLocator.h.
Constructor & Destructor Documentation
geos::triangulate::quadedge::LastFoundQuadEdgeLocator::LastFoundQuadEdgeLocator (QuadEdgeSubdivision * subdiv)
Definition at line 26 of file LastFoundQuadEdgeLocator.cpp.
                                                                               :
   subdiv(subdiv), lastEdge(nullptr)
 {
 }
Member Function Documentation
QuadEdge * geos::triangulate::quadedge::LastFoundQuadEdgeLocator::findEdge () private virtual
Definition at line 38 of file LastFoundQuadEdgeLocator.cpp.
References geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), and subdiv.
Referenced by init().
 {
   // assume there is an edge
   return *(subdiv->getEdges().begin());
 }
void geos::triangulate::quadedge::LastFoundQuadEdgeLocator::init (void) private virtual
Definition at line 32 of file LastFoundQuadEdgeLocator.cpp.
References findEdge(), and lastEdge.
Referenced by locate().
 {
   lastEdge = findEdge();
 }
QuadEdge * geos::triangulate::quadedge::LastFoundQuadEdgeLocator::locate (const Vertex & v) override virtual
Locates an edge e, such that either v is on e, or e is an edge of a triangle containing v. The search starts from the last located edge amd proceeds on the general direction of v.
Returns
The caller does not take ownership of the returned object.
Implements geos::triangulate::quadedge::QuadEdgeLocator.
Definition at line 45 of file LastFoundQuadEdgeLocator.cpp.
References init(), geos::triangulate::quadedge::QuadEdge::isLive(), lastEdge, geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge(), and subdiv.
 {
   if (!lastEdge || !lastEdge->isLive()) {
     init();
   }
   QuadEdge *e = subdiv->locateFromEdge(v, *lastEdge);
   lastEdge = e;
   return e;
 }
Member Data Documentation
QuadEdge* geos::triangulate::quadedge::LastFoundQuadEdgeLocator::lastEdge private
Definition at line 44 of file LastFoundQuadEdgeLocator.h.
Referenced by init(), and locate().
QuadEdgeSubdivision* geos::triangulate::quadedge::LastFoundQuadEdgeLocator::subdiv private
Definition at line 43 of file LastFoundQuadEdgeLocator.h.
Referenced by findEdge(), and locate().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/triangulate/quadedge/LastFoundQuadEdgeLocator.h
/home/vicky/potree/geos/vicky/src/triangulate/quadedge/LastFoundQuadEdgeLocator.cpp