GEOS: geos::util::GeometricShapeFactory::Dimensions Class Reference
geos::util::GeometricShapeFactory::Dimensions Class Reference
#include <GeometricShapeFactory.h>
Public Member Functions
Dimensions ()
void setBase (const geom::Coordinate &newBase)
void setCentre (const geom::Coordinate &newCentre)
void setSize (double size)
void setWidth (double nWidth)
void setHeight (double nHeight)
geom::Envelope * getEnvelope () const
Public Attributes
geom::Coordinate base
geom::Coordinate centre
double width
double height
Detailed Description
Definition at line 68 of file GeometricShapeFactory.h.
Constructor & Destructor Documentation
geos::util::GeometricShapeFactory::Dimensions::Dimensions ()
Definition at line 214 of file GeometricShapeFactory.cpp.
   :
   base(Coordinate::getNull()),
   centre(Coordinate::getNull())
 {
 }
Member Function Documentation
Envelope * geos::util::GeometricShapeFactory::Dimensions::getEnvelope () const
Definition at line 252 of file GeometricShapeFactory.cpp.
References base, centre, height, geos::geom::Coordinate::isNull(), width, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::util::GeometricShapeFactory::createArc(), geos::util::GeometricShapeFactory::createArcPolygon(), geos::util::GeometricShapeFactory::createCircle(), and geos::util::GeometricShapeFactory::createRectangle().
 {
   if (!base.isNull()) {
     return new Envelope(base.x, base.x + width, base.y, base.y + height);
   }
   if (!centre.isNull()) {
     return new Envelope(centre.x - width/2, centre.x + width/2,centre.y - height/2, centre.y + height/2);
   }
   return new Envelope(0, width, 0, height);
 }
void geos::util::GeometricShapeFactory::Dimensions::setBase (const geom::Coordinate & newBase)
Definition at line 222 of file GeometricShapeFactory.cpp.
References base.
Referenced by geos::util::GeometricShapeFactory::setBase().
 {
   base=newBase;
 }
void geos::util::GeometricShapeFactory::Dimensions::setCentre (const geom::Coordinate & newCentre)
Definition at line 228 of file GeometricShapeFactory.cpp.
References centre.
Referenced by geos::util::GeometricShapeFactory::setCentre().
 {
   centre=newCentre;
 }
void geos::util::GeometricShapeFactory::Dimensions::setHeight (double nHeight)
Definition at line 246 of file GeometricShapeFactory.cpp.
References height.
Referenced by geos::util::GeometricShapeFactory::setHeight().
 {
   height=nHeight;
 }
void geos::util::GeometricShapeFactory::Dimensions::setSize (double size)
Definition at line 234 of file GeometricShapeFactory.cpp.
References height, and width.
Referenced by geos::util::GeometricShapeFactory::setSize().
 {
   height = size;
   width = size;
 }
void geos::util::GeometricShapeFactory::Dimensions::setWidth (double nWidth)
Definition at line 241 of file GeometricShapeFactory.cpp.
References width.
Referenced by geos::util::GeometricShapeFactory::setWidth().
 {
   width=nWidth;
 }
Member Data Documentation
geom::Coordinate geos::util::GeometricShapeFactory::Dimensions::base
Definition at line 71 of file GeometricShapeFactory.h.
Referenced by getEnvelope(), and setBase().
geom::Coordinate geos::util::GeometricShapeFactory::Dimensions::centre
Definition at line 72 of file GeometricShapeFactory.h.
Referenced by getEnvelope(), and setCentre().
double geos::util::GeometricShapeFactory::Dimensions::height
Definition at line 74 of file GeometricShapeFactory.h.
Referenced by getEnvelope(), setHeight(), and setSize().
double geos::util::GeometricShapeFactory::Dimensions::width
Definition at line 73 of file GeometricShapeFactory.h.
Referenced by getEnvelope(), setSize(), and setWidth().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/util/GeometricShapeFactory.h
/home/vicky/potree/geos/vicky/src/util/GeometricShapeFactory.cpp