GEOS: geos::operation::predicate::RectangleIntersects Class Reference
geos::operation::predicate::RectangleIntersects Class Reference
Optimized implementation of the "intersects" spatial predicate for cases where one Geometry is a rectangle.
#include <RectangleIntersects.h>
Public Member Functions
RectangleIntersects (const geom::Polygon &newRect)
Create a new intersects computer for a rectangle.
bool intersects (const geom::Geometry &geom)
Static Public Member Functions
static bool intersects (const geom::Polygon &rectangle, const geom::Geometry &b)
Tests whether a rectangle intersects a given geometry.
Private Member Functions
RectangleIntersects (const RectangleIntersects &other)=delete
RectangleIntersects & operator= (const RectangleIntersects &rhs)=delete
Private Attributes
const geom::Polygon & rectangle
const geom::Envelope & rectEnv
Detailed Description
Optimized implementation of the "intersects" spatial predicate for cases where one Geometry is a rectangle.
This class works for all input geometries, including GeometryCollections.
As a further optimization, this class can be used to test many geometries against a single rectangle in a slightly more efficient way.
Definition at line 52 of file RectangleIntersects.h.
Constructor & Destructor Documentation
geos::operation::predicate::RectangleIntersects::RectangleIntersects (const RectangleIntersects & other) private delete
geos::operation::predicate::RectangleIntersects::RectangleIntersects (const geom::Polygon & newRect) inline
Create a new intersects computer for a rectangle.
Parameters
newRect a rectangular geometry
Definition at line 71 of file RectangleIntersects.h.
     :
     rectangle(newRect),
     rectEnv(*(newRect.getEnvelopeInternal()))
   {}
Member Function Documentation
bool geos::operation::predicate::RectangleIntersects::intersects (const geom::Geometry & geom)
Definition at line 266 of file RectangleIntersects.cpp.
References geos::geom::util::ShortCircuitedGeometryVisitor::applyTo(), geos::operation::predicate::ContainsPointVisitor::containsPoint(), geos::geom::Geometry::getEnvelopeInternal(), geos::operation::predicate::EnvelopeIntersectsVisitor::intersects(), geos::geom::Envelope::intersects(), geos::operation::predicate::LineIntersectsVisitor::intersects(), and geos::operation::predicate::EnvelopeIntersectsVisitor::rectEnv.
Referenced by geos::geom::prep::PreparedPolygon::intersects(), and intersects().
 {
   if (!rectEnv.intersects(geom.getEnvelopeInternal()))
     return false;
   // test envelope relationships
   EnvelopeIntersectsVisitor visitor(rectEnv);
   visitor.applyTo(geom);
   if (visitor.intersects()) return true;
   // test if any rectangle corner is contained in the target
   ContainsPointVisitor ecpVisitor(rectangle);
   ecpVisitor.applyTo(geom);
   if (ecpVisitor.containsPoint())
     return true;
   // test if any lines intersect
   LineIntersectsVisitor liVisitor(rectangle);
   liVisitor.applyTo(geom);
   if (liVisitor.intersects())
     return true;
   return false;
 }
static bool geos::operation::predicate::RectangleIntersects::intersects (const geom::Polygon & rectangle, const geom::Geometry & b) inline static
Tests whether a rectangle intersects a given geometry.
Parameters
rectangle a rectangular Polygon
b a Geometry of any type
Returns
true if the geometries intersect
Definition at line 86 of file RectangleIntersects.h.
References intersects().
   {
     RectangleIntersects rp(rectangle);
     return rp.intersects(b);
   }
RectangleIntersects& geos::operation::predicate::RectangleIntersects::operator= (const RectangleIntersects & rhs) private delete
Member Data Documentation
const geom::Polygon& geos::operation::predicate::RectangleIntersects::rectangle private
Definition at line 56 of file RectangleIntersects.h.
const geom::Envelope& geos::operation::predicate::RectangleIntersects::rectEnv private
Definition at line 58 of file RectangleIntersects.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/predicate/RectangleIntersects.h
/home/vicky/potree/geos/vicky/src/operation/predicate/RectangleIntersects.cpp