GEOS: geos::algorithm::SIRtreePointInRing Class Reference
geos::algorithm::SIRtreePointInRing Class Reference
#include <SIRtreePointInRing.h>
Public Member Functions
SIRtreePointInRing (geom::LinearRing *newRing)
~SIRtreePointInRing () override
bool isInside (const geom::Coordinate &pt) override
Private Member Functions
void buildIndex ()
void testLineSegment (const geom::Coordinate &p, geom::LineSegment *seg)
Private Attributes
geom::LinearRing * ring
index::strtree::SIRtree * sirTree
int crossings
Detailed Description
Definition at line 42 of file SIRtreePointInRing.h.
Constructor & Destructor Documentation
geos::algorithm::SIRtreePointInRing::SIRtreePointInRing (geom::LinearRing * newRing)
Definition at line 35 of file SIRtreePointInRing.cpp.
References buildIndex().
                                                          :
   PointInRing(),
   ring(newRing),
   sirTree(nullptr),
   crossings(0)
 {
   buildIndex();
 }
geos::algorithm::SIRtreePointInRing::~SIRtreePointInRing () override
Definition at line 44 of file SIRtreePointInRing.cpp.
References sirTree.
 {
   delete sirTree;
 }
Member Function Documentation
void geos::algorithm::SIRtreePointInRing::buildIndex () private
Definition at line 50 of file SIRtreePointInRing.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::CoordinateSequence::getSize(), geos::index::strtree::SIRtree::insert(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, ring, sirTree, and geos::geom::Coordinate::y.
Referenced by SIRtreePointInRing().
 {
   //Envelope *env=ring->getEnvelopeInternal();
   sirTree=new SIRtree();
   const CoordinateSequence *pts=ring->getCoordinatesRO();
   const std::size_t npts=pts->getSize();
   for(std::size_t i=1; i<npts; ++i)
   {
     if(pts->getAt(i-1)==pts->getAt(i)) continue; // Optimization suggested by MD. [Jon Aquino]
     LineSegment *seg=new LineSegment(pts->getAt(i-1), pts->getAt(i));
     sirTree->insert(seg->p0.y, seg->p1.y, seg);
   }
 }
bool geos::algorithm::SIRtreePointInRing::isInside (const geom::Coordinate & pt) override virtual
Implements geos::algorithm::PointInRing.
Definition at line 66 of file SIRtreePointInRing.cpp.
References crossings, geos::index::strtree::SIRtree::query(), sirTree, testLineSegment(), and geos::geom::Coordinate::y.
 {
   crossings=0;
   // test all segments intersected by vertical ray at pt
   vector<void*> *segs=sirTree->query(pt.y);
   //System.out.println("query size=" + segs.size());
   for(int i=0;i<(int)segs->size();i++) {
     LineSegment *seg=(LineSegment*) (*segs)[i];
     testLineSegment(pt,seg);
   }
   /*
   *  p is inside if number of crossings is odd.
   */
   if ((crossings%2)==1) {
     return true;
   }
   return false;
 }
void geos::algorithm::SIRtreePointInRing::testLineSegment (const geom::Coordinate & p, geom::LineSegment * seg) private
Definition at line 87 of file SIRtreePointInRing.cpp.
References crossings, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, geos::algorithm::RobustDeterminant::signOfDet2x2(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by isInside().
 {
   double xInt;  // x intersection of segment with ray
   double x1;    // translated coordinates
   double y1;
   double x2;
   double y2;
   /*
   *  Test if segment crosses ray from test point in positive x direction.
   */
   Coordinate& p1=seg->p0;
   Coordinate& p2=seg->p1;
   x1=p1.x-p.x;
   y1=p1.y-p.y;
   x2=p2.x-p.x;
   y2=p2.y-p.y;
   if (((y1>0) && (y2<=0)) ||
     ((y2>0) && (y1<=0))) {
     /*
     *  segment straddles x axis,so compute intersection.
     */
     xInt=RobustDeterminant::signOfDet2x2(x1,y1,x2,y2)/(y2-y1);
     //xsave=xInt;
     /*
     *  crosses ray if strictly positive intersection.
     */
     if (0.0<xInt) {
       crossings++;
     }
   }
 }
Member Data Documentation
int geos::algorithm::SIRtreePointInRing::crossings private
Definition at line 46 of file SIRtreePointInRing.h.
Referenced by isInside(), and testLineSegment().
geom::LinearRing* geos::algorithm::SIRtreePointInRing::ring private
Definition at line 44 of file SIRtreePointInRing.h.
Referenced by buildIndex().
index::strtree::SIRtree* geos::algorithm::SIRtreePointInRing::sirTree private
Definition at line 45 of file SIRtreePointInRing.h.
Referenced by buildIndex(), isInside(), and ~SIRtreePointInRing().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/SIRtreePointInRing.h
/home/vicky/potree/geos/vicky/src/algorithm/SIRtreePointInRing.cpp