GEOS: geos::simplify::DPTransformer Class Reference
geos::simplify::DPTransformer Class Reference
Public Member Functions
DPTransformer (double tolerance)
std::unique_ptr< Geometry > transform (const Geometry *nInputGeom)
void setSkipTransformedInvalidInteriorRings (bool b)
Protected Member Functions
CoordinateSequence::Ptr transformCoordinates (const CoordinateSequence *coords, const Geometry *parent) override
Geometry::Ptr transformPolygon (const Polygon *geom, const Geometry *parent) override
Geometry::Ptr transformMultiPolygon (const MultiPolygon *geom, const Geometry *parent) override
CoordinateSequence::Ptr createCoordinateSequence (std::unique_ptr< std::vector< Coordinate > > coords)
virtual Geometry::Ptr transformPoint (const Point *geom, const Geometry *parent)
virtual Geometry::Ptr transformMultiPoint (const MultiPoint *geom, const Geometry *parent)
virtual Geometry::Ptr transformLinearRing (const LinearRing *geom, const Geometry *parent)
virtual Geometry::Ptr transformLineString (const LineString *geom, const Geometry *parent)
virtual Geometry::Ptr transformMultiLineString (const MultiLineString *geom, const Geometry *parent)
virtual Geometry::Ptr transformGeometryCollection (const GeometryCollection *geom, const Geometry *parent)
Protected Attributes
const GeometryFactory * factory
Private Member Functions
Geometry::Ptr createValidArea (const Geometry *roughAreaGeom)
Private Attributes
double distanceTolerance
Detailed Description
Definition at line 46 of file DouglasPeuckerSimplifier.cpp.
Constructor & Destructor Documentation
geos::simplify::DPTransformer::DPTransformer (double tolerance)
Definition at line 88 of file DouglasPeuckerSimplifier.cpp.
References geos::geom::util::GeometryTransformer::setSkipTransformedInvalidInteriorRings().
   :
   distanceTolerance(t)
 {
   setSkipTransformedInvalidInteriorRings(true);
 }
Member Function Documentation
std::unique_ptr< CoordinateSequence > geos::geom::util::GeometryTransformer::createCoordinateSequence (std::unique_ptr< std::vector< Coordinate > > coords) protected inherited
Convenience method which provides standard way of creating a CoordinateSequence
Parameters
coords the coordinate array to copy
Returns
a coordinate sequence for the array
[final]
Definition at line 109 of file GeometryTransformer.cpp.
References geos::geom::CoordinateSequenceFactory::create(), geos::geom::util::GeometryTransformer::factory, and geos::geom::GeometryFactory::getCoordinateSequenceFactory().
 {
   return std::unique_ptr<CoordinateSequence>(
     factory->getCoordinateSequenceFactory()->create(
         coords.release())
   );
 }
Geometry::Ptr geos::simplify::DPTransformer::createValidArea (const Geometry * roughAreaGeom) private
Definition at line 96 of file DouglasPeuckerSimplifier.cpp.
References geos::geom::Geometry::buffer().
Referenced by transformMultiPolygon(), and transformPolygon().
 {
   return Geometry::Ptr(roughAreaGeom->buffer(0.0));
 }
void geos::geom::util::GeometryTransformer::setSkipTransformedInvalidInteriorRings (bool b) inherited
Definition at line 70 of file GeometryTransformer.cpp.
References geos::geom::util::GeometryTransformer::skipTransformedInvalidInteriorRings.
Referenced by DPTransformer().
 {
   skipTransformedInvalidInteriorRings = b;
 }
unique_ptr< Geometry > geos::geom::util::GeometryTransformer::transform (const Geometry * nInputGeom) inherited
Definition at line 77 of file GeometryTransformer.cpp.
References geos::geom::util::GeometryTransformer::factory, geos::geom::Geometry::getFactory(), geos::geom::util::GeometryTransformer::inputGeom, geos::geom::util::GeometryTransformer::transformGeometryCollection(), geos::geom::util::GeometryTransformer::transformLinearRing(), geos::geom::util::GeometryTransformer::transformLineString(), geos::geom::util::GeometryTransformer::transformMultiLineString(), geos::geom::util::GeometryTransformer::transformMultiPoint(), geos::geom::util::GeometryTransformer::transformMultiPolygon(), geos::geom::util::GeometryTransformer::transformPoint(), and geos::geom::util::GeometryTransformer::transformPolygon().
Referenced by geos::simplify::DouglasPeuckerSimplifier::getResultGeometry(), and geos::geom::util::GeometryTransformer::transformGeometryCollection().
 {
   using geos::util::IllegalArgumentException;
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transform(Geometry " << nInputGeom << ");" << std::endl;
 #endif
   inputGeom = nInputGeom;
   factory = inputGeom->getFactory();
   if ( const Point* p=dynamic_cast<const Point*>(inputGeom) )
     return transformPoint(p, nullptr);
   if ( const MultiPoint* mp=dynamic_cast<const MultiPoint*>(inputGeom) )
     return transformMultiPoint(mp, nullptr);
   if ( const LinearRing* lr=dynamic_cast<const LinearRing*>(inputGeom) )
     return transformLinearRing(lr, nullptr);
   if ( const LineString* ls=dynamic_cast<const LineString*>(inputGeom) )
     return transformLineString(ls, nullptr);
   if ( const MultiLineString* mls=dynamic_cast<const MultiLineString*>(inputGeom) )
     return transformMultiLineString(mls, nullptr);
   if ( const Polygon* p=dynamic_cast<const Polygon*>(inputGeom) )
     return transformPolygon(p, nullptr);
   if ( const MultiPolygon* mp=dynamic_cast<const MultiPolygon*>(inputGeom) )
     return transformMultiPolygon(mp, nullptr);
   if ( const GeometryCollection* gc=dynamic_cast<const GeometryCollection*>(inputGeom) )
     return transformGeometryCollection(gc, nullptr);
   throw IllegalArgumentException("Unknown Geometry subtype.");
 }
CoordinateSequence::Ptr geos::simplify::DPTransformer::transformCoordinates (const CoordinateSequence * coords, const Geometry * parent) override protected virtual
Reimplemented from geos::geom::util::GeometryTransformer.
Definition at line 102 of file DouglasPeuckerSimplifier.cpp.
References geos::geom::CoordinateSequenceFactory::create(), distanceTolerance, geos::geom::util::GeometryTransformer::factory, geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::ignore_unused_variable_warning(), geos::simplify::DouglasPeuckerLineSimplifier::simplify(), and geos::geom::CoordinateSequence::toVector().
 {
     ::geos::ignore_unused_variable_warning(parent);
   const Coordinate::Vect* inputPts = coords->toVector();
   assert(inputPts);
   std::unique_ptr<Coordinate::Vect> newPts =
       DouglasPeuckerLineSimplifier::simplify(*inputPts,
         distanceTolerance);
   return CoordinateSequence::Ptr(
     factory->getCoordinateSequenceFactory()->create(
       newPts.release()
     ));
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformGeometryCollection (const GeometryCollection * geom, const Geometry * parent) protected virtual inherited
Definition at line 358 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::buildGeometry(), geos::geom::GeometryFactory::createGeometryCollection(), geos::geom::util::GeometryTransformer::factory, geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::ignore_unused_variable_warning(), geos::geom::util::GeometryTransformer::preserveGeometryCollectionType, geos::geom::util::GeometryTransformer::pruneEmptyGeometry, and geos::geom::util::GeometryTransformer::transform().
Referenced by geos::geom::util::GeometryTransformer::transform().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformGeometryCollection(GeometryCollection " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   vector<Geometry*>* transGeomList = new vector<Geometry*>();
   for (std::size_t i=0, n=geom->getNumGeometries(); i<n; i++)
   {
     Geometry::Ptr transformGeom = transform(
       geom->getGeometryN(i)); // no parent ?
     if ( transformGeom.get() == nullptr ) continue;
     if ( pruneEmptyGeometry && transformGeom->isEmpty() ) continue;
     // If an exception is thrown we'll leak
     transGeomList->push_back(transformGeom.release());
   }
   if ( preserveGeometryCollectionType )
   {
     return Geometry::Ptr(factory->createGeometryCollection(
       transGeomList));
   }
   else
   {
     return Geometry::Ptr(factory->buildGeometry(transGeomList));
   }
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformLinearRing (const LinearRing * geom, const Geometry * parent) protected virtual inherited
Definition at line 180 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createLineString(), geos::geom::util::GeometryTransformer::factory, geos::geom::LineString::getCoordinatesRO(), geos::ignore_unused_variable_warning(), geos::geom::util::GeometryTransformer::preserveType, and geos::geom::util::GeometryTransformer::transformCoordinates().
Referenced by geos::geom::util::GeometryTransformer::transform(), and geos::geom::util::GeometryTransformer::transformPolygon().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformLinearRing(LinearRing " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   CoordinateSequence::Ptr seq(transformCoordinates(
     geom->getCoordinatesRO(), geom));
   auto seqSize = seq->size();
   // ensure a valid LinearRing
   if ( seqSize > 0 && seqSize < 4 && ! preserveType )
   {
     return factory->createLineString(std::move(seq));
   }
   else
   {
     return factory->createLinearRing(std::move(seq));
   }
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformLineString (const LineString * geom, const Geometry * parent) protected virtual inherited
Definition at line 207 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::createLineString(), geos::geom::util::GeometryTransformer::factory, geos::geom::LineString::getCoordinatesRO(), geos::ignore_unused_variable_warning(), and geos::geom::util::GeometryTransformer::transformCoordinates().
Referenced by geos::geom::util::GeometryTransformer::transform(), and geos::geom::util::GeometryTransformer::transformMultiLineString().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformLineString(LineString " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   // should check for 1-point sequences and downgrade them to points
   return factory->createLineString(
     transformCoordinates(geom->getCoordinatesRO(), geom));
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformMultiLineString (const MultiLineString * geom, const Geometry * parent) protected virtual inherited
Definition at line 223 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::buildGeometry(), geos::geom::util::GeometryTransformer::factory, geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::ignore_unused_variable_warning(), and geos::geom::util::GeometryTransformer::transformLineString().
Referenced by geos::geom::util::GeometryTransformer::transform().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformMultiLineString(MultiLineString " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   vector<Geometry*>* transGeomList = new vector<Geometry*>();
   for (unsigned int i=0, n=static_cast<unsigned int>(geom->getNumGeometries()); i<n; i++)
   {
     const LineString* l = dynamic_cast<const LineString*>(
         geom->getGeometryN(i));
     assert(l);
     Geometry::Ptr transformGeom = transformLineString(l, geom);
     if ( transformGeom.get() == nullptr ) continue;
     if ( transformGeom->isEmpty() ) continue;
     // If an exception is thrown we'll leak
     transGeomList->push_back(transformGeom.release());
   }
   return Geometry::Ptr(factory->buildGeometry(transGeomList));
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformMultiPoint (const MultiPoint * geom, const Geometry * parent) protected virtual inherited
Definition at line 150 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::buildGeometry(), geos::geom::util::GeometryTransformer::factory, geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::ignore_unused_variable_warning(), and geos::geom::util::GeometryTransformer::transformPoint().
Referenced by geos::geom::util::GeometryTransformer::transform().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformMultiPoint(MultiPoint " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   vector<Geometry*>* transGeomList = new vector<Geometry*>();
   for (unsigned int i=0, n=static_cast<unsigned int>(geom->getNumGeometries()); i<n; i++)
   {
     const Point* p = dynamic_cast<const Point*>(geom->getGeometryN(i));
     assert(p);
     Geometry::Ptr transformGeom = transformPoint(p, geom);
     if ( transformGeom.get() == nullptr ) continue;
     if ( transformGeom->isEmpty() ) continue;
     // If an exception is thrown we'll leak
     transGeomList->push_back(transformGeom.release());
   }
   return Geometry::Ptr(factory->buildGeometry(transGeomList));
 }
Geometry::Ptr geos::simplify::DPTransformer::transformMultiPolygon (const MultiPolygon * geom, const Geometry * parent) override protected virtual
Reimplemented from geos::geom::util::GeometryTransformer.
Definition at line 143 of file DouglasPeuckerSimplifier.cpp.
References createValidArea().
 {
 #if GEOS_DEBUG
   std::cerr << "DPTransformer::transformMultiPolygon(MultiPolygon " << geom << ", Geometry " << parent << ");" << std::endl;
 #endif
   Geometry::Ptr roughGeom(GeometryTransformer::transformMultiPolygon(geom, parent));
         return createValidArea(roughGeom.get());
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformPoint (const Point * geom, const Geometry * parent) protected virtual inherited
Definition at line 133 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::createPoint(), geos::geom::util::GeometryTransformer::factory, geos::geom::Point::getCoordinatesRO(), geos::ignore_unused_variable_warning(), and geos::geom::util::GeometryTransformer::transformCoordinates().
Referenced by geos::geom::util::GeometryTransformer::transform(), and geos::geom::util::GeometryTransformer::transformMultiPoint().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformPoint(Point " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   CoordinateSequence::Ptr cs(transformCoordinates(
     geom->getCoordinatesRO(), geom));
   return Geometry::Ptr(factory->createPoint(cs.release()));
 }
Geometry::Ptr geos::simplify::DPTransformer::transformPolygon (const Polygon * geom, const Geometry * parent) override protected virtual
Reimplemented from geos::geom::util::GeometryTransformer.
Definition at line 122 of file DouglasPeuckerSimplifier.cpp.
References createValidArea().
 {
 #if GEOS_DEBUG
   std::cerr << "DPTransformer::transformPolygon(Polygon " << geom << ", Geometry " << parent << ");" << std::endl;
 #endif
   Geometry::Ptr roughGeom(GeometryTransformer::transformPolygon(geom, parent));
         // don't try and correct if the parent is going to do this
   if ( dynamic_cast<const MultiPolygon*>(parent) )
   {
     return roughGeom;
   }
   return createValidArea(roughGeom.get());
 }
Member Data Documentation
double geos::simplify::DPTransformer::distanceTolerance private
Definition at line 84 of file DouglasPeuckerSimplifier.cpp.
Referenced by transformCoordinates().
const GeometryFactory* geos::geom::util::GeometryTransformer::factory protected inherited
Definition at line 106 of file GeometryTransformer.h.
Referenced by geos::geom::util::GeometryTransformer::createCoordinateSequence(), geos::geom::util::GeometryTransformer::transform(), transformCoordinates(), geos::geom::util::GeometryTransformer::transformGeometryCollection(), geos::geom::util::GeometryTransformer::transformLinearRing(), geos::geom::util::GeometryTransformer::transformLineString(), geos::geom::util::GeometryTransformer::transformMultiLineString(), geos::geom::util::GeometryTransformer::transformMultiPoint(), geos::geom::util::GeometryTransformer::transformMultiPolygon(), geos::geom::util::GeometryTransformer::transformPoint(), and geos::geom::util::GeometryTransformer::transformPolygon().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/simplify/DouglasPeuckerSimplifier.cpp