GEOS: geos::planargraph::DirectedEdgeStar Class Reference
geos::planargraph::DirectedEdgeStar Class Reference
A sorted collection of DirectedEdge which leave a Node in a PlanarGraph.
#include <DirectedEdgeStar.h>
Public Member Functions
DirectedEdgeStar ()
Constructs a DirectedEdgeStar with no edges.
virtual ~DirectedEdgeStar ()
void add (DirectedEdge *de)
Adds a new member to this DirectedEdgeStar.
void remove (DirectedEdge *de)
Drops a member of this DirectedEdgeStar.
std::vector< DirectedEdge * >::iterator iterator ()
Returns an Iterator over the DirectedEdges, in ascending order by angle with the positive x-axis.
std::vector< DirectedEdge * >::iterator begin ()
Returns an iterator to first DirectedEdge.
std::vector< DirectedEdge * >::iterator end ()
Returns an iterator to one-past last DirectedEdge.
std::vector< DirectedEdge * >::const_iterator begin () const
Returns an const_iterator to first DirectedEdge.
std::vector< DirectedEdge * >::const_iterator end () const
Returns an const_iterator to one-past last DirectedEdge.
std::size_t getDegree () const
Returns the number of edges around the Node associated with this DirectedEdgeStar.
geom::Coordinate & getCoordinate () const
Returns the coordinate for the node at wich this star is based.
std::vector< DirectedEdge * > & getEdges ()
Returns the DirectedEdges, in ascending order by angle with the positive x-axis.
int getIndex (const Edge *edge)
Returns the zero-based index of the given Edge, after sorting in ascending order by angle with the positive x-axis.
int getIndex (const DirectedEdge *dirEdge)
Returns the zero-based index of the given DirectedEdge, after sorting in ascending order by angle with the positive x-axis.
int getIndex (int i) const
Returns the remainder when i is divided by the number of edges in this DirectedEdgeStar.
DirectedEdge * getNextEdge (DirectedEdge *dirEdge)
Returns the DirectedEdge on the left-hand side of the given DirectedEdge (which must be a member of this DirectedEdgeStar).
Private Member Functions
void sortEdges () const
Private Attributes
std::vector< DirectedEdge * > outEdges
The underlying list of outgoing DirectedEdges.
bool sorted
Detailed Description
A sorted collection of DirectedEdge which leave a Node in a PlanarGraph.
Definition at line 43 of file DirectedEdgeStar.h.
Constructor & Destructor Documentation
geos::planargraph::DirectedEdgeStar::DirectedEdgeStar () inline
Constructs a DirectedEdgeStar with no edges.
Definition at line 58 of file DirectedEdgeStar.h.
 : sorted(false) {}
virtual geos::planargraph::DirectedEdgeStar::~DirectedEdgeStar () inline virtual
Definition at line 60 of file DirectedEdgeStar.h.
 {}
Member Function Documentation
void geos::planargraph::DirectedEdgeStar::add (DirectedEdge * de)
Adds a new member to this DirectedEdgeStar.
Definition at line 33 of file DirectedEdgeStar.cpp.
Referenced by geos::planargraph::Node::addOutEdge().
 {
   outEdges.push_back(de);
   sorted=false;
 }
vector< DirectedEdge * >::iterator geos::planargraph::DirectedEdgeStar::begin ()
Returns an iterator to first DirectedEdge.
Definition at line 56 of file DirectedEdgeStar.cpp.
{
   sortEdges();
   return outEdges.begin();
 }
vector< DirectedEdge * >::const_iterator geos::planargraph::DirectedEdgeStar::begin () const
Returns an const_iterator to first DirectedEdge.
Definition at line 68 of file DirectedEdgeStar.cpp.
{
   sortEdges();
   return outEdges.begin();
 }
vector< DirectedEdge * >::iterator geos::planargraph::DirectedEdgeStar::end ()
Returns an iterator to one-past last DirectedEdge.
Definition at line 62 of file DirectedEdgeStar.cpp.
                       {
   sortEdges();
   return outEdges.end();
 }
vector< DirectedEdge * >::const_iterator geos::planargraph::DirectedEdgeStar::end () const
Returns an const_iterator to one-past last DirectedEdge.
Definition at line 74 of file DirectedEdgeStar.cpp.
{
   sortEdges();
   return outEdges.end();
 }
Coordinate & geos::planargraph::DirectedEdgeStar::getCoordinate () const
Returns the coordinate for the node at wich this star is based.
Definition at line 83 of file DirectedEdgeStar.cpp.
References geos::planargraph::DirectedEdge::getCoordinate().
 {
   if (outEdges.empty())
     return Coordinate::getNull();
   DirectedEdge *e=outEdges[0];
   return e->getCoordinate();
 }
std::size_t geos::planargraph::DirectedEdgeStar::getDegree () const inline
Returns the number of edges around the Node associated with this DirectedEdgeStar.
Definition at line 93 of file DirectedEdgeStar.h.
Referenced by geos::planargraph::Node::getDegree().
 { return outEdges.size(); }
vector< DirectedEdge * > & geos::planargraph::DirectedEdgeStar::getEdges ()
Returns the DirectedEdges, in ascending order by angle with the positive x-axis.
Definition at line 96 of file DirectedEdgeStar.cpp.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsStartingAt(), geos::operation::polygonize::PolygonizeGraph::deleteAllEdges(), geos::operation::polygonize::PolygonizeGraph::getDegree(), geos::operation::polygonize::PolygonizeGraph::getDegreeNonDeleted(), geos::planargraph::Node::getEdgesBetween(), geos::operation::linemerge::LineMergeDirectedEdge::getNext(), and geos::planargraph::PlanarGraph::remove().
 {
   sortEdges();
   return outEdges;
 }
int geos::planargraph::DirectedEdgeStar::getIndex (const Edge * edge)
Returns the zero-based index of the given Edge, after sorting in ascending order by angle with the positive x-axis.
Definition at line 126 of file DirectedEdgeStar.cpp.
References geos::planargraph::DirectedEdge::getEdge().
Referenced by geos::planargraph::Node::getIndex().
 {
   sortEdges();
   for (unsigned int i = 0; i<outEdges.size(); ++i)
   {
     DirectedEdge *de =outEdges[i];
     if (de->getEdge() == edge)
     return i;
   }
   return -1;
 }
int geos::planargraph::DirectedEdgeStar::getIndex (const DirectedEdge * dirEdge)
Returns the zero-based index of the given DirectedEdge, after sorting in ascending order by angle with the positive x-axis.
Definition at line 143 of file DirectedEdgeStar.cpp.
 {
   sortEdges();
   for (unsigned int i = 0; i <outEdges.size(); ++i)
   {
     DirectedEdge *de =outEdges[i];
     if (de == dirEdge)
     return i;
   }
   return -1;
 }
int geos::planargraph::DirectedEdgeStar::getIndex (int i) const
Returns the remainder when i is divided by the number of edges in this DirectedEdgeStar.
Definition at line 160 of file DirectedEdgeStar.cpp.
 {
   int modi = i % (int)outEdges.size();
   //I don't think modi can be 0 (assuming i is positive) [Jon Aquino 10/28/2003]
   if (modi < 0) modi += (int)outEdges.size();
   return modi;
 }
DirectedEdge * geos::planargraph::DirectedEdgeStar::getNextEdge (DirectedEdge * dirEdge)
Returns the DirectedEdge on the left-hand side of the given DirectedEdge (which must be a member of this DirectedEdgeStar).
Definition at line 173 of file DirectedEdgeStar.cpp.
 {
   int i = getIndex(dirEdge);
   return outEdges[getIndex(i + 1)];
 }
std::vector<DirectedEdge*>::iterator geos::planargraph::DirectedEdgeStar::iterator () inline
Returns an Iterator over the DirectedEdges, in ascending order by angle with the positive x-axis.
Definition at line 76 of file DirectedEdgeStar.h.
 { return begin(); }
void geos::planargraph::DirectedEdgeStar::remove (DirectedEdge * de)
Drops a member of this DirectedEdgeStar.
Definition at line 43 of file DirectedEdgeStar.cpp.
Referenced by geos::planargraph::PlanarGraph::remove().
 {
   for(unsigned int i=0; i<outEdges.size(); ++i)
   {
     if(outEdges[i]==de)
     {
       outEdges.erase(outEdges.begin()+i);
       --i;
     }
   }
 }
void geos::planargraph::DirectedEdgeStar::sortEdges () const private
Definition at line 113 of file DirectedEdgeStar.cpp.
References geos::planargraph::pdeLessThan().
 {
   if (!sorted) {
     sort(outEdges.begin(), outEdges.end(), pdeLessThan);
     sorted=true;
   }
 }
Member Data Documentation
std::vector<DirectedEdge*> geos::planargraph::DirectedEdgeStar::outEdges mutable private
The underlying list of outgoing DirectedEdges.
Definition at line 50 of file DirectedEdgeStar.h.
bool geos::planargraph::DirectedEdgeStar::sorted mutable private
Definition at line 51 of file DirectedEdgeStar.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/planargraph/DirectedEdgeStar.h
/home/vicky/potree/geos/vicky/src/planargraph/DirectedEdgeStar.cpp