GEOS: geos::operation::polygonize::Polygonizer::LineStringAdder Class Reference
geos::operation::polygonize::Polygonizer::LineStringAdder Class Reference
Public Member Functions
LineStringAdder (Polygonizer *p)
void filter_ro (const geom::Geometry *g) override
virtual void filter_rw (Geometry *geom)
Public Attributes
Polygonizer * pol
Detailed Description
Add every linear element in a geometry into the polygonizer graph.
Definition at line 190 of file Polygonizer.h.
Constructor & Destructor Documentation
geos::operation::polygonize::Polygonizer::LineStringAdder::LineStringAdder (Polygonizer * p)
Definition at line 47 of file Polygonizer.cpp.
                                                          :
   pol(p)
 {
 }
Member Function Documentation
void geos::operation::polygonize::Polygonizer::LineStringAdder::filter_ro (const geom::Geometry * g) override virtual
Reimplemented from geos::geom::GeometryComponentFilter.
Definition at line 54 of file Polygonizer.cpp.
References geos::operation::polygonize::Polygonizer::add(), and pol.
 {
   const LineString *ls = dynamic_cast<const LineString *>(g);
   if ( ls ) pol->add(ls);
 }
void geos::geom::GeometryComponentFilter::filter_rw (Geometry * geom) virtual inherited
Performs an operation with or on geom.
Parameters
geom a Geometry to which the filter is applied.
Reimplemented in geos::geom::Geometry::GeometryChangedFilter, geos::geom::util::LinearComponentExtracter, and geos::geom::util::ComponentCoordinateExtracter.
Definition at line 25 of file GeometryComponentFilter.cpp.
References geos::ignore_unused_variable_warning().
Referenced by geos::geom::Point::apply_rw(), geos::geom::GeometryCollection::apply_rw(), geos::geom::Polygon::apply_rw(), geos::geom::LineString::apply_rw(), and geos::geom::Geometry::apply_rw().
 {
   ::geos::ignore_unused_variable_warning(geom);
   assert(0);
 }
Member Data Documentation
Polygonizer* geos::operation::polygonize::Polygonizer::LineStringAdder::pol
Definition at line 192 of file Polygonizer.h.
Referenced by filter_ro().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/polygonize/Polygonizer.h
/home/vicky/potree/geos/vicky/src/operation/polygonize/Polygonizer.cpp