GEOS: geos::operation::intersection::RectangleIntersectionBuilder Class Reference
geos::operation::intersection::RectangleIntersectionBuilder Class Reference
Rebuild geometries from subpaths left by clipping with a rectangle.
#include <RectangleIntersectionBuilder.h>
Public Member Functions
~RectangleIntersectionBuilder ()
Private Member Functions
std::unique_ptr< geom::Geometry > build ()
Build the result geometry from partial results and clean up.
void reconnectPolygons (const Rectangle &rect)
Build polygons from parts left by clipping one.
void reconnect ()
void reverseLines ()
void release (RectangleIntersectionBuilder &parts)
void add (geom::Polygon *g)
Add intermediate Polygon.
void add (geom::LineString *g)
Add intermediate LineString.
void add (geom::Point *g)
Add intermediate Point.
bool empty () const
Test if there are no parts at all.
void clear ()
Clear the parts having transferred ownership elsewhere.
void close_boundary (const Rectangle &rect, std::vector< geom::Coordinate > *ring, double x1, double y1, double x2, double y2)
Close a ring clockwise along rectangle edges.
void close_ring (const Rectangle &rect, std::vector< geom::Coordinate > *ring)
RectangleIntersectionBuilder (const geom::GeometryFactory &f)
Private Attributes
std::list< geom::Polygon * > polygons
std::list< geom::LineString * > lines
std::list< geom::Point * > points
const geom::GeometryFactory & _gf
Friends
class RectangleIntersection
Detailed Description
Rebuild geometries from subpaths left by clipping with a rectangle.
The RectangleIntersectionBuilder is used to maintain lists of polygons, linestrings and points left from clipping a Geometry with a Rectangle. Once all clipping has been done, the class builds a valid Geometry from the components.
This is a utility class needed by RectangleIntersection, and is not intended for public use.
Definition at line 63 of file RectangleIntersectionBuilder.h.
Constructor & Destructor Documentation
geos::operation::intersection::RectangleIntersectionBuilder::~RectangleIntersectionBuilder ()
Definition at line 34 of file RectangleIntersectionBuilder.cpp.
 {
   for (std::list<geom::Polygon *>::iterator i=polygons.begin(), e=polygons.end(); i!=e; ++i)
     delete *i;
   for (std::list<geom::LineString *>::iterator i=lines.begin(), e=lines.end(); i!=e; ++i)
     delete *i;
   for (std::list<geom::Point *>::iterator i=points.begin(), e=points.end(); i!=e; ++i)
     delete *i;
 }
geos::operation::intersection::RectangleIntersectionBuilder::RectangleIntersectionBuilder (const geom::GeometryFactory & f) inline private
Definition at line 150 of file RectangleIntersectionBuilder.h.
     : _gf(f) {}
Member Function Documentation
void geos::operation::intersection::RectangleIntersectionBuilder::add (geom::Polygon * g) private
Add intermediate Polygon.
Definition at line 120 of file RectangleIntersectionBuilder.cpp.
Referenced by geos::operation::intersection::RectangleIntersection::clip_linestring(), geos::operation::intersection::RectangleIntersection::clip_linestring_parts(), geos::operation::intersection::RectangleIntersection::clip_point(), geos::operation::intersection::RectangleIntersection::clip_polygon_to_linestrings(), geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons(), and release().
 {
   polygons.push_back(thePolygon);
 }
void geos::operation::intersection::RectangleIntersectionBuilder::add (geom::LineString * g) private
Add intermediate LineString.
Definition at line 129 of file RectangleIntersectionBuilder.cpp.
 {
   lines.push_back(theLine);
 }
void geos::operation::intersection::RectangleIntersectionBuilder::add (geom::Point * g) private
Add intermediate Point.
Definition at line 138 of file RectangleIntersectionBuilder.cpp.
 {
   points.push_back(thePoint);
 }
std::unique_ptr< geom::Geometry > geos::operation::intersection::RectangleIntersectionBuilder::build () private
Build the result geometry from partial results and clean up.
Definition at line 144 of file RectangleIntersectionBuilder.cpp.
Referenced by geos::operation::intersection::RectangleIntersection::clip(), and geos::operation::intersection::RectangleIntersection::clipBoundary().
 {
   // Total number of objects
   std::size_t n = polygons.size() + lines.size() + points.size();
   if(n == 0)
   return std::unique_ptr<Geometry>(_gf.createGeometryCollection());
   std::vector<Geometry *> *geoms = new std::vector<Geometry *>;
   geoms->reserve(n);
   for (std::list<geom::Polygon *>::iterator i=polygons.begin(), e=polygons.end(); i!=e; ++i)
       geoms->push_back(*i);
   polygons.clear();
   for (std::list<geom::LineString *>::iterator i=lines.begin(), e=lines.end(); i!=e; ++i)
       geoms->push_back(*i);
   lines.clear();
   for (std::list<geom::Point *>::iterator i=points.begin(), e=points.end(); i!=e; ++i)
       geoms->push_back(*i);
   points.clear();
   return std::unique_ptr<Geometry>(
     (*geoms)[0]->getFactory()->buildGeometry(geoms)
   );
 }
void geos::operation::intersection::RectangleIntersectionBuilder::clear () private
Clear the parts having transferred ownership elsewhere.
Definition at line 100 of file RectangleIntersectionBuilder.cpp.
 {
   polygons.clear();
   lines.clear();
   points.clear();
 }
void geos::operation::intersection::RectangleIntersectionBuilder::close_boundary (const Rectangle & rect, std::vector< geom::Coordinate > * ring, double x1, double y1, double x2, double y2) private
Close a ring clockwise along rectangle edges.
Only the 4 corners and x1,y1 need to be considered. The possible cases are:
x1,y1 corner1 x1,y1 corner1 corner2 x1,y1 corner1 corner2 corner3 x1,y1 corner1 corner2 corner3 corner4 x1,y1
Definition at line 311 of file RectangleIntersectionBuilder.cpp.
References geos::operation::intersection::Rectangle::Left, geos::operation::intersection::Rectangle::nextEdge(), geos::operation::intersection::Rectangle::position(), geos::operation::intersection::Rectangle::Right, geos::operation::intersection::Rectangle::Top, geos::operation::intersection::Rectangle::xmax(), geos::operation::intersection::Rectangle::xmin(), geos::operation::intersection::Rectangle::ymax(), and geos::operation::intersection::Rectangle::ymin().
 {
   Rectangle::Position endpos = rect.position(x2,y2);
   Rectangle::Position pos = rect.position(x1,y1);
   while(true)
   {
     // Close up when we have the same edge and the
     // points are in the correct clockwise order
     if((pos & endpos) != 0 &&
      (
       (x1==rect.xmin() && y2>=y1) ||
       (y1==rect.ymax() && x2>=x1) ||
       (x1==rect.xmax() && y2<=y1) ||
       (y1==rect.ymin() && x2<=x1))
       )
     {
       if(x1!=x2 || y1!=y2)    // the polygon may have started at a corner
       ring->push_back(Coordinate(x2,y2));
       break;
     }
     pos = Rectangle::nextEdge(pos);
     if(pos & Rectangle::Left)
     x1 = rect.xmin();
     else if(pos & Rectangle::Top)
     y1 = rect.ymax();
     else if(pos & Rectangle::Right)
     x1 = rect.xmax();
     else
     y1 = rect.ymin();
     ring->push_back(Coordinate(x1,y1));
   }
 }
void geos::operation::intersection::RectangleIntersectionBuilder::close_ring (const Rectangle & rect, std::vector< geom::Coordinate > * ring) private
Definition at line 353 of file RectangleIntersectionBuilder.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   auto nr = ring->size();
   Coordinate &c2 = (*ring)[0];
   Coordinate &c1 = (*ring)[nr-1];
   double x2 = c2.x;
   double y2 = c2.y;
   double x1 = c1.x;
   double y1 = c1.y;
   close_boundary(rect, ring, x1, y1, x2, y2);
 }
bool geos::operation::intersection::RectangleIntersectionBuilder::empty () const private
Test if there are no parts at all.
Definition at line 111 of file RectangleIntersectionBuilder.cpp.
Referenced by geos::operation::intersection::RectangleIntersection::clip_polygon_to_linestrings(), and geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons().
 {
   return polygons.empty() && lines.empty() && points.empty();
 }
void geos::operation::intersection::RectangleIntersectionBuilder::reconnect () private
Reconnect disjointed parts
When we clip a LinearRing we may get multiple linestrings. Often the first and last ones can be reconnected to simplify output.
Sample clip with a rectangle 0,0 –> 10,10 without reconnecting:
Input: POLYGON ((5 10,0 0,10 0,5 10)) Output: MULTILINESTRING ((5 10,0 0),(10 0,5 10)) Desired: LINESTRING (10 0,5 10,0 0)
TODO: If there is a very sharp spike from inside the rectangle outside, and then back in, it is possible that the intersection points at the edge are equal. In this case we could reconnect the linestrings. The task is the same we're already doing for the 1st/last linestrings, we'd just do it for any adjacent pair as well.
Definition at line 45 of file RectangleIntersectionBuilder.cpp.
References geos::geom::CoordinateSequence::add(), geos::geom::LineString::getCoordinatesRO(), geos::geom::CoordinateSequence::removeRepeatedPoints(), and geos::geom::CoordinateSequence::size().
Referenced by geos::operation::intersection::RectangleIntersection::clip_polygon_to_linestrings(), and geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons().
 {
   // Nothing to reconnect if there aren't at least two lines
   if(lines.size() < 2)
        return;
   geom::LineString * line1 = lines.front();
   const geom::CoordinateSequence &cs1 = *line1->getCoordinatesRO();
   geom::LineString * line2 = lines.back();
   const geom::CoordinateSequence &cs2 = *line2->getCoordinatesRO();
   const auto n1 = cs1.size();
   const auto n2 = cs2.size();
   // Safety check against bad input to prevent segfaults
   if(n1==0 || n2==0)
        return;
   if (cs1[0] != cs2[n2-1]) return;
   // Merge the two linestrings
   CoordinateSequence *ncs = CoordinateSequence::removeRepeatedPoints(&cs2);
   ncs->add(&cs1, false, true);
   delete line1;
   delete line2;
   LineString * nline = _gf.createLineString(ncs);
   lines.pop_front();
   lines.pop_back();
   lines.push_front(nline);
 }
void geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons (const Rectangle & rect) private
Build polygons from parts left by clipping one.
Build exterior ring(s) from lines
Attach polygons as holes to the exterior ring(s)
Definition at line 370 of file RectangleIntersectionBuilder.cpp.
References geos::geom::LineString::clone(), geos::geom::CoordinateSequenceFactory::create(), geos::operation::intersection::distance(), geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::operation::intersection::normalize_ring(), poly, geos::geom::CoordinateSequence::size(), geos::operation::intersection::Rectangle::toLinearRing(), and geos::geom::CoordinateSequence::toVector().
Referenced by geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons().
 {
   // Build the exterior rings first
   typedef std::vector< geom::Geometry *> LinearRingVect;
   typedef std::pair< geom::LinearRing *, LinearRingVect * > ShellAndHoles;
   typedef std::list< ShellAndHoles > ShellAndHolesList;
   ShellAndHolesList exterior;
   const CoordinateSequenceFactory &_csf = *_gf.getCoordinateSequenceFactory();
   // If there are no lines, the rectangle must have been
   // inside the exterior ring.
   if(lines.empty())
   {
     geom::LinearRing * ring = rect.toLinearRing(_gf);
     exterior.push_back(make_pair(ring, new LinearRingVect()));
   }
   else
   {
     // Reconnect all lines into one or more linearrings
     // using box boundaries if necessary
     std::vector<Coordinate> *ring = nullptr;
     while(!lines.empty() || ring != nullptr)
     {
       if(ring == nullptr)
       {
         ring = new std::vector<Coordinate>();
         LineString *line = lines.front();
         lines.pop_front();
         line->getCoordinatesRO()->toVector(*ring);
         delete line;
       }
       // Distance to own endpoint
       double own_distance = distance(rect, *ring);
       // Find line to connect to
       // TODO: should we use LineMerge op ?
       double best_distance = -1;
       std::list<LineString*>::iterator best_pos = lines.begin();
       for(std::list<LineString*>::iterator iter=lines.begin(); iter!=lines.end(); ++iter)
       {
         double d = distance(rect, *ring, *iter);
         if(best_distance < 0 || d<best_distance)
         {
           best_distance = d;
           best_pos = iter;
         }
       }
       // If own end point is closest, close the ring and continue
       if(best_distance < 0 || own_distance < best_distance)
       {
         close_ring(rect,ring);
         normalize_ring(*ring);
         geom::CoordinateSequence *shell_cs = _csf.create(ring);
         geom::LinearRing *shell = _gf.createLinearRing(shell_cs);
         exterior.push_back(make_pair(shell, new LinearRingVect()));
         ring = nullptr;
       }
       else
       {
         LineString * line = *best_pos;
         auto nr = ring->size();
         const CoordinateSequence& cs = *line->getCoordinatesRO();
         close_boundary(rect, ring,
                (*ring)[nr-1].x,
                (*ring)[nr-1].y,
                cs[0].x,
                cs[0].y);
         // above function adds the 1st point
         for (size_t i=1; i<cs.size(); ++i)
           ring->push_back(cs[i]);
         //ring->addSubLineString(line,1);
         delete line;
         lines.erase(best_pos);
       }
     }
   }
   // Attach holes to polygons
   for (std::list<geom::Polygon *>::iterator i=polygons.begin(), e=polygons.end(); i!=e; ++i)
   {
     geom::Polygon *poly = *i;
     const geom::LineString *hole = poly->getExteriorRing();
     if(exterior.size() == 1)
     {
       exterior.front().second->push_back( hole->clone() );
     }
     else
     {
       using geos::algorithm::CGAlgorithms;
       geom::Coordinate c;
       hole->getCoordinatesRO()->getAt(0, c);
       for (ShellAndHolesList::iterator i=exterior.begin(), e=exterior.end(); i!=e; ++i)
       {
         ShellAndHoles &p = *i;
         const CoordinateSequence *shell_cs = p.first->getCoordinatesRO();
         if( CGAlgorithms::isPointInRing(c, shell_cs) )
         {
           // add hole to shell
           p.second->push_back(hole->clone());
           break;
         }
       }
     }
     delete poly;
   }
   // Build the result polygons
   std::list<geom::Polygon *> new_polygons;
   for (ShellAndHolesList::iterator i=exterior.begin(), e=exterior.end(); i!=e; ++i)
   {
     ShellAndHoles &p = *i;
     geom::Polygon * poly = _gf.createPolygon(p.first, p.second);
     new_polygons.push_back(poly);
   }
   clear();
   polygons = new_polygons;
 }
void geos::operation::intersection::RectangleIntersectionBuilder::release (RectangleIntersectionBuilder & parts) private
Export parts to another container
Definition at line 82 of file RectangleIntersectionBuilder.cpp.
References add().
Referenced by geos::operation::intersection::RectangleIntersection::clip_polygon_to_linestrings(), and geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons().
 {
   for (std::list<geom::Polygon *>::iterator i=polygons.begin(), e=polygons.end(); i!=e; ++i)
     theParts.add(*i);
   for (std::list<geom::LineString *>::iterator i=lines.begin(), e=lines.end(); i!=e; ++i)
     theParts.add(*i);
   for (std::list<geom::Point *>::iterator i=points.begin(), e=points.end(); i!=e; ++i)
     theParts.add(*i);
   clear();
 }
void geos::operation::intersection::RectangleIntersectionBuilder::reverseLines () private
Definition at line 502 of file RectangleIntersectionBuilder.cpp.
References geos::geom::LineString::reverse().
Referenced by geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons().
 {
   std::list<geom::LineString *> new_lines;
   for (std::list<geom::LineString *>::reverse_iterator i=lines.rbegin(), e=lines.rend(); i!=e; ++i)
   {
     LineString *ol = *i;
     new_lines.push_back(dynamic_cast<LineString*>(ol->reverse()));
     delete ol;
   }
   lines = new_lines;
 }
Friends And Related Function Documentation
friend class RectangleIntersection friend
Definition at line 66 of file RectangleIntersectionBuilder.h.
Member Data Documentation
const geom::GeometryFactory& geos::operation::intersection::RectangleIntersectionBuilder::_gf private
Definition at line 153 of file RectangleIntersectionBuilder.h.
std::list<geom::LineString *> geos::operation::intersection::RectangleIntersectionBuilder::lines private
Definition at line 127 of file RectangleIntersectionBuilder.h.
std::list<geom::Point *> geos::operation::intersection::RectangleIntersectionBuilder::points private
Definition at line 128 of file RectangleIntersectionBuilder.h.
std::list<geom::Polygon *> geos::operation::intersection::RectangleIntersectionBuilder::polygons private
Definition at line 126 of file RectangleIntersectionBuilder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/intersection/RectangleIntersectionBuilder.h
/home/vicky/potree/geos/vicky/src/operation/intersection/RectangleIntersectionBuilder.cpp