GEOS: geos::operation::overlay::validate::FuzzyPointLocator Class Reference
geos::operation::overlay::validate::FuzzyPointLocator Class Reference
Finds the most likely Location of a point relative to the polygonal components of a geometry, using a tolerance value.
#include <FuzzyPointLocator.h>
Public Member Functions
FuzzyPointLocator (const geom::Geometry &geom, double nTolerance)
geom::Location::Value getLocation (const geom::Coordinate &pt)
Private Member Functions
std::unique_ptr< geom::Geometry > getLineWork (const geom::Geometry &geom)
std::unique_ptr< geom::Geometry > extractLineWork (const geom::Geometry &geom)
Extracts linework for polygonal components.
FuzzyPointLocator (const FuzzyPointLocator &other)=delete
FuzzyPointLocator & operator= (const FuzzyPointLocator &rhs)=delete
Private Attributes
const geom::Geometry & g
double tolerance
algorithm::PointLocator ptLocator
std::unique_ptr< geom::Geometry > linework
Detailed Description
Finds the most likely Location of a point relative to the polygonal components of a geometry, using a tolerance value.
If a point is not clearly in the Interior or Exterior, it is considered to be on the Boundary. In other words, if the point is within the tolerance of the Boundary, it is considered to be on the Boundary; otherwise, whether it is Interior or Exterior is determined directly.
Definition at line 58 of file FuzzyPointLocator.h.
Constructor & Destructor Documentation
geos::operation::overlay::validate::FuzzyPointLocator::FuzzyPointLocator (const geom::Geometry & geom, double nTolerance)
Definition at line 49 of file FuzzyPointLocator.cpp.
   :
   g(geom),
   tolerance(nTolerance),
   ptLocator(),
   linework(extractLineWork(g))
 {
 }
geos::operation::overlay::validate::FuzzyPointLocator::FuzzyPointLocator (const FuzzyPointLocator & other) private delete
Member Function Documentation
std::unique_ptr< Geometry > geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork (const geom::Geometry & geom) private
Extracts linework for polygonal components.
Parameters
g the geometry from which to extract
Returns
a lineal geometry containing the extracted linework
Definition at line 61 of file FuzzyPointLocator.cpp.
References geos::geom::GeometryFactory::buildGeometry(), g, geos::geom::Geometry::getBoundary(), geos::geom::Geometry::getDimension(), geos::geom::Geometry::getFactory(), geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getNumGeometries(), and geos::ignore_unused_variable_warning().
 {
     ::geos::ignore_unused_variable_warning(geom);
   vector<Geometry*>* lineGeoms = new vector<Geometry*>();
   try { // geoms array will leak if an exception is thrown
   for (size_t i=0, n=g.getNumGeometries(); i<n; ++i)
   {
     const Geometry* gComp = g.getGeometryN(i);
     Geometry* lineGeom = nullptr;
     // only get linework for polygonal components
     if (gComp->getDimension() == 2) {
       lineGeom = gComp->getBoundary();
       lineGeoms->push_back(lineGeom);
     }
   }
   return std::unique_ptr<Geometry>(g.getFactory()->buildGeometry(lineGeoms));
   } catch (...) { // avoid leaks
     for (size_t i=0, n=lineGeoms->size(); i<n; ++i)
     {
       delete (*lineGeoms)[i];
     }
     delete lineGeoms;
     throw;
   }
 }
std::unique_ptr< Geometry > geos::operation::overlay::validate::FuzzyPointLocator::getLineWork (const geom::Geometry & geom) private
Definition at line 94 of file FuzzyPointLocator.cpp.
References geos::geom::GeometryFactory::buildGeometry(), geos::geom::Geometry::clone(), g, geos::geom::Geometry::getBoundary(), geos::geom::Geometry::getDimension(), geos::geom::Geometry::getFactory(), geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getNumGeometries(), and geos::ignore_unused_variable_warning().
 {
     ::geos::ignore_unused_variable_warning(geom);
   vector<Geometry*>* lineGeoms = new vector<Geometry*>();
   try { // geoms array will leak if an exception is thrown
   for (size_t i=0, n=g.getNumGeometries(); i<n; ++i)
   {
     const Geometry* gComp = g.getGeometryN(i);
     Geometry* lineGeom;
     if (gComp->getDimension() == 2) {
       lineGeom = gComp->getBoundary();
     }
     else {
       lineGeom = gComp->clone();
     }
     lineGeoms->push_back(lineGeom);
   }
   return std::unique_ptr<Geometry>(g.getFactory()->buildGeometry(lineGeoms));
   } catch (...) { // avoid leaks
     for (size_t i=0, n=lineGeoms->size(); i<n; ++i)
     {
       delete (*lineGeoms)[i];
     }
     delete lineGeoms;
     throw;
   }
 }
Location::Value geos::operation::overlay::validate::FuzzyPointLocator::getLocation (const geom::Coordinate & pt)
Definition at line 129 of file FuzzyPointLocator.cpp.
References geos::geom::GeometryFactory::createPoint(), g, geos::geom::Geometry::getFactory(), linework, geos::algorithm::PointLocator::locate(), ptLocator, and tolerance.
Referenced by geos::operation::overlay::validate::OverlayResultValidator::testValid().
 {
   unique_ptr<Geometry> point(g.getFactory()->createPoint(pt));
   double dist = linework->distance(point.get());
   // if point is close to boundary, it is considered
   // to be on the boundary
   if (dist < tolerance)
     return Location::BOUNDARY;
   // now we know point must be clearly inside or outside geometry,
   // so return actual location value
   // (the static_cast is needed because PointLocator doesn't cleanly
   // return a Location::Value - it should !!)
   return static_cast<Location::Value>(ptLocator.locate(pt, &g));
 }
FuzzyPointLocator& geos::operation::overlay::validate::FuzzyPointLocator::operator= (const FuzzyPointLocator & rhs) private delete
Member Data Documentation
const geom::Geometry& geos::operation::overlay::validate::FuzzyPointLocator::g private
Definition at line 68 of file FuzzyPointLocator.h.
Referenced by extractLineWork(), getLineWork(), and getLocation().
std::unique_ptr<geom::Geometry> geos::operation::overlay::validate::FuzzyPointLocator::linework private
Definition at line 74 of file FuzzyPointLocator.h.
Referenced by getLocation().
algorithm::PointLocator geos::operation::overlay::validate::FuzzyPointLocator::ptLocator private
Definition at line 72 of file FuzzyPointLocator.h.
Referenced by getLocation().
double geos::operation::overlay::validate::FuzzyPointLocator::tolerance private
Definition at line 70 of file FuzzyPointLocator.h.
Referenced by getLocation().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/validate/FuzzyPointLocator.h
/home/vicky/potree/geos/vicky/src/operation/overlay/validate/FuzzyPointLocator.cpp