GEOS: geos::geom::prep::PreparedPolygonIntersects Class Reference
geos::geom::prep::PreparedPolygonIntersects Class Reference
Computes the intersects spatial relationship predicate for PreparedPolygons relative to all other Geometry classes.
#include <PreparedPolygonIntersects.h>
Public Member Functions
PreparedPolygonIntersects (const PreparedPolygon *const prep)
bool intersects (const geom::Geometry *geom)
Static Public Member Functions
static bool intersects (const PreparedPolygon *const prep, const geom::Geometry *geom)
Protected Member Functions
bool isAllTestComponentsInTarget (const geom::Geometry *testGeom) const
Tests whether all components of the test Geometry are contained in the target geometry.
bool isAllTestComponentsInTargetInterior (const geom::Geometry *testGeom) const
Tests whether all components of the test Geometry are contained in the interior of the target geometry.
bool isAnyTestComponentInTarget (const geom::Geometry *testGeom) const
Tests whether any component of the test Geometry intersects the area of the target geometry.
bool isAnyTestComponentInTargetInterior (const geom::Geometry *testGeom) const
Tests whether any component of the test Geometry intersects the interior of the target geometry.
bool isAnyTargetComponentInAreaTest (const geom::Geometry *testGeom, const geom::Coordinate::ConstVect *targetRepPts) const
Protected Attributes
const PreparedPolygon *const prepPoly
Detailed Description
Computes the intersects spatial relationship predicate for PreparedPolygons relative to all other Geometry classes.
Uses short-circuit tests and indexing to improve performance.
Author
Martin Davis
Definition at line 50 of file PreparedPolygonIntersects.h.
Constructor & Destructor Documentation
geos::geom::prep::PreparedPolygonIntersects::PreparedPolygonIntersects (const PreparedPolygon *const prep) inline
Creates an instance of this operation.
Parameters
prepPoly the PreparedPolygon to evaluate
Definition at line 74 of file PreparedPolygonIntersects.h.
   : PreparedPolygonPredicate( prep)
   { }
Member Function Documentation
static bool geos::geom::prep::PreparedPolygonIntersects::intersects (const PreparedPolygon *const prep, const geom::Geometry * geom) inline static
Computes the intersects predicate between a PreparedPolygon and a Geometry.
Parameters
prep the prepared polygon
geom a test geometry
Returns
true if the polygon intersects the geometry
Definition at line 63 of file PreparedPolygonIntersects.h.
References intersects().
Referenced by intersects(), and geos::geom::prep::PreparedPolygon::intersects().
   {
     PreparedPolygonIntersects polyInt(prep);
     return polyInt.intersects( geom);
   }
bool geos::geom::prep::PreparedPolygonIntersects::intersects (const geom::Geometry * geom)
Tests whether this PreparedPolygon intersects a given geometry.
Parameters
geom the test geometry
Returns
true if the test geometry intersects
Definition at line 47 of file PreparedPolygonIntersects.cpp.
References geos::noding::SegmentStringUtil::extractSegmentStrings(), geos::geom::Geometry::getDimension(), geos::geom::prep::PreparedPolygon::getIntersectionFinder(), geos::geom::prep::BasicPreparedGeometry::getRepresentativePoints(), geos::noding::FastSegmentSetIntersectionFinder::intersects(), geos::geom::prep::PreparedPolygonPredicate::isAnyTargetComponentInAreaTest(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTarget(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
 {
   // Do point-in-poly tests first, since they are cheaper and may result
   // in a quick positive result.
   // If a point of any test components lie in target, result is true
   bool isInPrepGeomArea = isAnyTestComponentInTarget( geom);
   if ( isInPrepGeomArea )
     return true;
   if ( dynamic_cast<const geom::Puntal *>(geom) ) {
     // point-in-poly failed, no way there can be an intersection
     // (NOTE: isAnyTestComponentInTarget also checks for boundary)
     return false;
   }
   // If any segments intersect, result is true
   noding::SegmentString::ConstVect lineSegStr;
   noding::SegmentStringUtil::extractSegmentStrings( geom, lineSegStr );
   bool segsIntersect = prepPoly->getIntersectionFinder()->intersects( &lineSegStr);
   for ( size_t i = 0, ni = lineSegStr.size(); i < ni; i++ )
   {
     delete lineSegStr[ i ];
   }
   if (segsIntersect)
     return true;
   // If the test has dimension = 2 as well, it is necessary to
   // test for proper inclusion of the target.
   // Since no segments intersect, it is sufficient to test representative points.
   if ( geom->getDimension() == 2)
   {
     // TODO: generalize this to handle GeometryCollections
     bool isPrepGeomInArea = isAnyTargetComponentInAreaTest( geom, prepPoly->getRepresentativePoints());
     if ( isPrepGeomInArea )
       return true;
   }
   return false;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTarget (const geom::Geometry * testGeom) const protected inherited
Tests whether all components of the test Geometry are contained in the target geometry.
Handles both linear and point components.
Parameters
geom a geometry to test
Returns
true if all components of the argument are contained in the target geometry
Definition at line 41 of file PreparedPolygonPredicate.cpp.
References geos::geom::Location::EXTERIOR, geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::algorithm::locate::PointOnGeometryLocator::locate(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::eval().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const geom::Coordinate* pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::EXTERIOR == loc)
         {
             return false;
         }
     }
     return true;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTargetInterior (const geom::Geometry * testGeom) const protected inherited
Tests whether all components of the test Geometry are contained in the interior of the target geometry.
Handles both linear and point components.
Parameters
geom a geometry to test
Returns
true if all componenta of the argument are contained in the target geometry interior
Definition at line 59 of file PreparedPolygonPredicate.cpp.
References geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::geom::Location::INTERIOR, geos::algorithm::locate::PointOnGeometryLocator::locate(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const geom::Coordinate * pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::INTERIOR != loc)
         {
             return false;
         }
     }
     return true;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAnyTargetComponentInAreaTest (const geom::Geometry * testGeom, const geom::Coordinate::ConstVect * targetRepPts) const protected inherited
Tests whether any component of the target geometry intersects the test geometry (which must be an areal geometry)
Parameters
geom the test geometry
repPts the representative points of the target geometry
Returns
true if any component intersects the areal test geometry
Definition at line 116 of file PreparedPolygonPredicate.cpp.
References geos::geom::Location::EXTERIOR, and geos::algorithm::locate::SimplePointInAreaLocator::locate().
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), and intersects().
 {
     algorithm::locate::SimplePointInAreaLocator piaLoc(testGeom);
     for (std::size_t i = 0, ni = targetRepPts->size(); i < ni; i++)
     {
         const geom::Coordinate * pt = (*targetRepPts)[i];
         const int loc = piaLoc.locate(pt);
         if (geom::Location::EXTERIOR != loc)
         {
             return true;
         }
     }
     return false;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTarget (const geom::Geometry * testGeom) const protected inherited
Tests whether any component of the test Geometry intersects the area of the target geometry.
Handles test geometries with both linear and point components.
Parameters
geom a geometry to test
Returns
true if any component of the argument intersects the prepared geometry
Definition at line 78 of file PreparedPolygonPredicate.cpp.
References geos::geom::Location::EXTERIOR, geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::algorithm::locate::PointOnGeometryLocator::locate(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
Referenced by intersects().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const Coordinate* pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::EXTERIOR != loc)
         {
             return true;
         }
     }
     return false;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTargetInterior (const geom::Geometry * testGeom) const protected inherited
Tests whether any component of the test Geometry intersects the interior of the target geometry.
Handles test geometries with both linear and point components.
Parameters
geom a geometry to test
Returns
true if any component of the argument intersects the prepared area geometry interior
Definition at line 97 of file PreparedPolygonPredicate.cpp.
References geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::geom::Location::INTERIOR, geos::algorithm::locate::PointOnGeometryLocator::locate(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::eval().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const Coordinate * pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::INTERIOR == loc)
         {
             return true;
         }
     }
     return false;
 }
Member Data Documentation
const PreparedPolygon* const geos::geom::prep::PreparedPolygonPredicate::prepPoly protected inherited
Definition at line 65 of file PreparedPolygonPredicate.h.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections(), geos::geom::prep::PreparedPolygonCovers::fullTopologicalPredicate(), geos::geom::prep::PreparedPolygonContains::fullTopologicalPredicate(), intersects(), geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTarget(), geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTargetInterior(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTarget(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTargetInterior(), and geos::geom::prep::AbstractPreparedPolygonContains::isProperIntersectionImpliesNotContainedSituation().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/prep/PreparedPolygonIntersects.h
/home/vicky/potree/geos/vicky/src/geom/prep/PreparedPolygonIntersects.cpp