GEOS: geos::operation::predicate::RectangleContains Class Reference
geos::operation::predicate::RectangleContains Class Reference
Optimized implementation of spatial predicate "contains" for cases where the first Geometry is a rectangle.
#include <RectangleContains.h>
Public Member Functions
RectangleContains (const geom::Polygon &rect)
bool contains (const geom::Geometry &geom)
RectangleContains (const RectangleContains &other)=delete
RectangleContains & operator= (const RectangleContains &rhs)=delete
Static Public Member Functions
static bool contains (const geom::Polygon &rect, const geom::Geometry &b)
Private Member Functions
bool isContainedInBoundary (const geom::Geometry &geom)
bool isPointContainedInBoundary (const geom::Point &geom)
bool isPointContainedInBoundary (const geom::Coordinate &pt)
Tests if a point is contained in the boundary of the target rectangle.
bool isLineStringContainedInBoundary (const geom::LineString &line)
Tests if a linestring is completely contained in the boundary of the target rectangle.
bool isLineSegmentContainedInBoundary (const geom::Coordinate &p0, const geom::Coordinate &p1)
Tests if a line segment is contained in the boundary of the target rectangle.
Private Attributes
const geom::Polygon & rectangle
const geom::Envelope & rectEnv
Detailed Description
Optimized implementation of spatial predicate "contains" for cases where the first Geometry is a rectangle.
As a further optimization, this class can be used directly to test many geometries against a single rectangle.
Definition at line 51 of file RectangleContains.h.
Constructor & Destructor Documentation
geos::operation::predicate::RectangleContains::RectangleContains (const geom::Polygon & rect) inline
Create a new contains computer for two geometries.
Parameters
rect a rectangular geometry
Definition at line 104 of file RectangleContains.h.
     :
     rectangle(rect),
     rectEnv(*(rect.getEnvelopeInternal()))
     {}
geos::operation::predicate::RectangleContains::RectangleContains (const RectangleContains & other) delete
Member Function Documentation
static bool geos::operation::predicate::RectangleContains::contains (const geom::Polygon & rect, const geom::Geometry & b) inline static
Definition at line 93 of file RectangleContains.h.
References contains().
Referenced by geos::geom::prep::PreparedPolygon::contains(), and contains().
   {
     RectangleContains rc(rect);
     return rc.contains(b);
   }
bool geos::operation::predicate::RectangleContains::contains (const geom::Geometry & geom)
Definition at line 35 of file RectangleContains.cpp.
References geos::geom::Geometry::getEnvelopeInternal().
 {
   if ( ! rectEnv.contains(geom.getEnvelopeInternal()) )
     return false;
   // check that geom is not contained entirely in the rectangle boundary
   if (isContainedInBoundary(geom))
     return false;
   return true;
 }
bool geos::operation::predicate::RectangleContains::isContainedInBoundary (const geom::Geometry & geom) private
Definition at line 49 of file RectangleContains.cpp.
References geos::geom::Geometry::getGeometryN(), and geos::geom::Geometry::getNumGeometries().
 {
   // polygons can never be wholely contained in the boundary
   if (dynamic_cast<const geom::Polygon *>(&geom)) return false;
   if (const Point *p=dynamic_cast<const Point *>(&geom))
     return isPointContainedInBoundary(*p);
   if (const LineString *l=dynamic_cast<const LineString *>(&geom))
     return isLineStringContainedInBoundary(*l);
   for (unsigned i=0, n=static_cast<unsigned>(geom.getNumGeometries()); i<n; ++i)
   {
     const Geometry &comp = *(geom.getGeometryN(i));
     if ( !isContainedInBoundary(comp) )
       return false;
   }
   return true;
 }
bool geos::operation::predicate::RectangleContains::isLineSegmentContainedInBoundary (const geom::Coordinate & p0, const geom::Coordinate & p1) private
Tests if a line segment is contained in the boundary of the target rectangle.
Parameters
p0 an endpoint of the segment
p1 an endpoint of the segment
Returns
true if the line segment is contained in the boundary
Either both x and y values are different or one of x and y are the same, but the other ordinate is not the same as a boundary ordinate
In either case, the segment is not wholely in the boundary
Definition at line 107 of file RectangleContains.cpp.
References geos::geom::Coordinate::equals2D(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   if (p0.equals2D(p1))
     return isPointContainedInBoundary(p0);
   // we already know that the segment is contained in
   // the rectangle envelope
   if (p0.x == p1.x) {
     if (p0.x == rectEnv.getMinX() ||
       p0.x == rectEnv.getMaxX() )
     {
       return true;
     }
   }
   else if (p0.y == p1.y) {
     if (p0.y == rectEnv.getMinY() ||
       p0.y == rectEnv.getMaxY() )
     {
       return true;
     }
   }
   return false;
 }
bool geos::operation::predicate::RectangleContains::isLineStringContainedInBoundary (const geom::LineString & line) private
Tests if a linestring is completely contained in the boundary of the target rectangle.
Parameters
line the linestring to test
Returns
true if the linestring is contained in the boundary
Definition at line 93 of file RectangleContains.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), and geos::geom::CoordinateSequence::getSize().
 {
   const CoordinateSequence &seq = *(line.getCoordinatesRO());
   for (unsigned int i=0, n=static_cast<unsigned int>(seq.getSize()-1); i<n; ++i) {
     const Coordinate& p0=seq.getAt(i);
     const Coordinate& p1=seq.getAt(i+1);
     if (! isLineSegmentContainedInBoundary(p0, p1))
       return false;
   }
   return true;
 }
bool geos::operation::predicate::RectangleContains::isPointContainedInBoundary (const geom::Point & geom) private
Definition at line 70 of file RectangleContains.cpp.
References geos::geom::Point::getCoordinate().
 {
   return isPointContainedInBoundary(*(point.getCoordinate()));
 }
bool geos::operation::predicate::RectangleContains::isPointContainedInBoundary (const geom::Coordinate & pt) private
Tests if a point is contained in the boundary of the target rectangle.
Parameters
pt the point to test
Returns
true if the point is contained in the boundary
contains = false iff the point is properly contained in the rectangle.
This code assumes that the point lies in the rectangle envelope
Definition at line 77 of file RectangleContains.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   return pt.x == rectEnv.getMinX()
     || pt.x == rectEnv.getMaxX()
     || pt.y == rectEnv.getMinY()
     || pt.y == rectEnv.getMaxY();
 }
RectangleContains& geos::operation::predicate::RectangleContains::operator= (const RectangleContains & rhs) delete
Member Data Documentation
const geom::Polygon& geos::operation::predicate::RectangleContains::rectangle private
Definition at line 55 of file RectangleContains.h.
const geom::Envelope& geos::operation::predicate::RectangleContains::rectEnv private
Definition at line 56 of file RectangleContains.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/predicate/RectangleContains.h
/home/vicky/potree/geos/vicky/src/operation/predicate/RectangleContains.cpp