GEOS: geos::index::strtree::STRtree Class Reference
geos::index::strtree::STRtree Class Reference
A query-only R-tree created using the Sort-Tile-Recursive (STR) algorithm. For two-dimensional spatial data.
#include <STRtree.h>
Classes
class STRIntersectsOp
Public Member Functions
~STRtree () override
STRtree (std::size_t nodeCapacity=10)
void insert (const geom::Envelope *itemEnv, void *item) override
Adds a spatial item with an extent specified by the given Envelope to the index.
void query (const geom::Envelope *searchEnv, std::vector< void * > &matches) override
Queries the index for all items whose extents intersect the given search Envelope.
void query (const geom::Envelope *searchEnv, ItemVisitor &visitor) override
Queries the index for all items whose extents intersect the given search Envelope and applies an ItemVisitor to them.
const void * nearestNeighbour (const geom::Envelope *env, const void *item, ItemDistance *itemDist)
std::pair< const void *, const void * > nearestNeighbour (BoundablePair *initBndPair)
std::pair< const void *, const void * > nearestNeighbour (ItemDistance *itemDist)
std::pair< const void *, const void * > nearestNeighbour (BoundablePair *initBndPair, double maxDistance)
std::pair< const void *, const void * > nearestNeighbour (STRtree *tree, ItemDistance *itemDist)
bool remove (const geom::Envelope *itemEnv, void *item) override
Removes a single item from the tree.
ItemsList * itemsTree ()
virtual void query (const void *searchBounds, const AbstractNode *node, std::vector< void * > *matches)
virtual void boundablesAtLevel (int level, AbstractNode *top, BoundableList *boundables)
virtual void build ()
virtual std::size_t getNodeCapacity ()
void iterate (ItemVisitor &visitor)
Static Public Member Functions
static double avg (double a, double b)
static double centreY (const geom::Envelope *e)
static bool compareDoubles (double a, double b)
Protected Member Functions
AbstractNode * createNode (int level) override
IntersectsOp * getIntersectsOp () override
bool remove (const void *itemEnv, void *item)
Also builds the tree, if necessary.
virtual AbstractNode * lastNode (BoundableList *nodeList)
virtual AbstractNode * getRoot ()
virtual void insert (const void *bounds, void *item)
Also builds the tree, if necessary.
void query (const void *searchBounds, std::vector< void * > &foundItems)
Also builds the tree, if necessary.
void query (const void *searchBounds, ItemVisitor &visitor)
Also builds the tree, if necessary.
void query (const void *searchBounds, const AbstractNode &node, ItemVisitor &visitor)
std::unique_ptr< BoundableList > boundablesAtLevel (int level)
Protected Attributes
AbstractNode * root
std::vector< AbstractNode * > * nodes
std::size_t nodeCapacity
Private Member Functions
std::unique_ptr< BoundableList > createParentBoundables (BoundableList *childBoundables, int newLevel) override
std::unique_ptr< BoundableList > createParentBoundablesFromVerticalSlices (std::vector< BoundableList * > *verticalSlices, int newLevel)
std::unique_ptr< BoundableList > sortBoundables (const BoundableList *input) override
std::unique_ptr< BoundableList > createParentBoundablesFromVerticalSlice (BoundableList *childBoundables, int newLevel)
std::vector< BoundableList * > * verticalSlices (BoundableList *childBoundables, size_t sliceCount)
Private Attributes
STRIntersectsOp intersectsOp
Detailed Description
A query-only R-tree created using the Sort-Tile-Recursive (STR) algorithm. For two-dimensional spatial data.
The STR packed R-tree is simple to implement and maximizes space utilization; that is, as many leaves as possible are filled to capacity. Overlap between nodes is far less than in a basic R-tree. However, once the tree has been built (explicitly or on the first call to query), items may not be added or removed.
Described in: P. Rigaux, Michel Scholl and Agnes Voisard. Spatial Databases With Application To GIS. Morgan Kaufmann, San Francisco, 2002.
Definition at line 64 of file STRtree.h.
Constructor & Destructor Documentation
geos::index::strtree::STRtree::~STRtree () override
Definition at line 98 of file STRtree.cpp.
 {
 }
geos::index::strtree::STRtree::STRtree (std::size_t nodeCapacity = 10)
Constructs an STRtree with the given maximum number of child nodes that a node may have
Definition at line 93 of file STRtree.cpp.
                                    : AbstractSTRtree(nodeCapacity)
 {
 }
Member Function Documentation
static double geos::index::strtree::STRtree::avg (double a, double b) inline static
Definition at line 126 of file STRtree.h.
Referenced by centreY().
{
     return (a + b) / 2.0;
   }
std::unique_ptr< BoundableList > geos::index::strtree::AbstractSTRtree::boundablesAtLevel (int level) protected inherited
Definition at line 308 of file AbstractSTRtree.cpp.
 {
   std::unique_ptr<BoundableList> boundables ( new BoundableList() );
   boundablesAtLevel(level, root, boundables.get());
   return boundables;
 }
void geos::index::strtree::AbstractSTRtree::boundablesAtLevel (int level, AbstractNode * top, BoundableList * boundables) virtual inherited
Parameters
level -1 to get items
Definition at line 317 of file AbstractSTRtree.cpp.
References geos::index::strtree::AbstractNode::getChildBoundables(), and geos::index::strtree::AbstractNode::getLevel().
 {
   assert(level>-2);
   if (top->getLevel()==level)
   {
     boundables->push_back(top);
     return;
   }
   assert(top);
   const BoundableList& vb = *(top->getChildBoundables());
   for(BoundableList::const_iterator i=vb.begin(), e=vb.end();
       i!=e; ++i)
   {
     Boundable* boundable=*i;
     if (typeid(*boundable)==typeid(AbstractNode))
     {
       boundablesAtLevel(level, (AbstractNode*)boundable,
         boundables);
     }
     else
     {
       assert(typeid(*boundable)==typeid(ItemBoundable));
       if (level==-1)
       {
         boundables->push_back(boundable);
       }
     }
   }
   return;
 }
void geos::index::strtree::AbstractSTRtree::build () virtual inherited
Creates parent nodes, grandparent nodes, and so forth up to the root node, for the data that has been inserted into the tree. Can only be called once, and thus can be called only after all of the data has been inserted into the tree.
Definition at line 56 of file AbstractSTRtree.cpp.
Referenced by nearestNeighbour().
 {
   if(built)
     return;
   root=(itemBoundables->empty()?createNode(0):createHigherLevels(itemBoundables,-1));
   built=true;
 }
static double geos::index::strtree::STRtree::centreY (const geom::Envelope * e) inline static
Definition at line 130 of file STRtree.h.
References avg(), geos::geom::Envelope::getMaxY(), and geos::geom::Envelope::getMinY().
{
     return STRtree::avg(e->getMinY(), e->getMaxY());
   }
static bool geos::index::strtree::AbstractSTRtree::compareDoubles (double a, double b) inline static inherited
Definition at line 260 of file AbstractSTRtree.h.
{
     // NOTE - strk:
     // Ternary operation is a workaround for
     // a probable MingW bug, see
     // http://trac.osgeo.org/geos/ticket/293
     return ( a < b ) ? true : false;
   }
AbstractNode * geos::index::strtree::STRtree::createNode (int level) override protected virtual
Implements geos::index::strtree::AbstractSTRtree.
Definition at line 315 of file STRtree.cpp.
References geos::index::strtree::AbstractSTRtree::nodeCapacity, and geos::index::strtree::AbstractSTRtree::nodes.
 {
   AbstractNode *an = new STRAbstractNode(level, static_cast<int>(nodeCapacity));
   nodes->push_back(an);
   return an;
 }
std::unique_ptr< BoundableList > geos::index::strtree::STRtree::createParentBoundables (BoundableList * childBoundables, int newLevel) override private virtual
Creates the parent level for the given child level. First, orders the items by the x-values of the midpoints, and groups them into vertical slices. For each slice, orders the items by the y-values of the midpoints, and group them into runs of size M (the node capacity). For each run, creates a new (parent) node.
Reimplemented from geos::index::strtree::AbstractSTRtree.
Definition at line 110 of file STRtree.cpp.
References createParentBoundablesFromVerticalSlices(), geos::index::strtree::AbstractSTRtree::getNodeCapacity(), sortBoundables(), and verticalSlices().
 {
   assert(!childBoundables->empty());
   int minLeafCount=(int) ceil((double)childBoundables->size()/(double)getNodeCapacity());
   std::unique_ptr<BoundableList> sortedChildBoundables ( sortBoundables(childBoundables) );
   std::unique_ptr< vector<BoundableList*> > verticalSlicesV (
       verticalSlices(sortedChildBoundables.get(), (int)ceil(sqrt((double)minLeafCount)))
       );
   std::unique_ptr<BoundableList> ret (
     createParentBoundablesFromVerticalSlices(verticalSlicesV.get(), newLevel)
   );
   for (size_t i=0, vssize=verticalSlicesV->size(); i<vssize; ++i)
   {
     BoundableList* inner = (*verticalSlicesV)[i];
     delete inner;
   }
   return ret;
 }
std::unique_ptr< BoundableList > geos::index::strtree::STRtree::createParentBoundablesFromVerticalSlice (BoundableList * childBoundables, int newLevel) private
Definition at line 158 of file STRtree.cpp.
References geos::index::strtree::AbstractSTRtree::createParentBoundables().
Referenced by createParentBoundablesFromVerticalSlices().
 {
   return AbstractSTRtree::createParentBoundables(childBoundables, newLevel);
 }
std::unique_ptr< BoundableList > geos::index::strtree::STRtree::createParentBoundablesFromVerticalSlices (std::vector< BoundableList * > * verticalSlices, int newLevel) private
Definition at line 135 of file STRtree.cpp.
References createParentBoundablesFromVerticalSlice().
Referenced by createParentBoundables().
 {
   assert(!verticalSlices->empty());
   std::unique_ptr<BoundableList> parentBoundables( new BoundableList() );
   for (size_t i=0, vssize=verticalSlices->size(); i<vssize; ++i)
   {
     std::unique_ptr<BoundableList> toAdd (
       createParentBoundablesFromVerticalSlice(
         (*verticalSlices)[i], newLevel)
       );
     assert(!toAdd->empty());
     parentBoundables->insert(
         parentBoundables->end(),
         toAdd->begin(),
         toAdd->end());
   }
   return parentBoundables;
 }
IntersectsOp* geos::index::strtree::STRtree::getIntersectsOp () inline override protected virtual
Returns
a test for intersection between two bounds, necessary because subclasses of AbstractSTRtree have different implementations of bounds.
See also
IntersectsOp
Implements geos::index::strtree::AbstractSTRtree.
Definition at line 108 of file STRtree.h.
{
     return &intersectsOp;
   }
virtual std::size_t geos::index::strtree::AbstractSTRtree::getNodeCapacity () inline virtual inherited
Returns the maximum number of child nodes that a node may have
Definition at line 281 of file AbstractSTRtree.h.
Referenced by createParentBoundables().
 { return nodeCapacity; }
virtual AbstractNode* geos::index::strtree::AbstractSTRtree::getRoot () inline protected virtual inherited
Definition at line 203 of file AbstractSTRtree.h.
Referenced by nearestNeighbour().
{
                 assert(built);
     return root;
   }
void geos::index::strtree::STRtree::insert (const geom::Envelope * itemEnv, void * item) override virtual
Adds a spatial item with an extent specified by the given Envelope to the index.
Parameters
itemEnv Envelope of the item, ownership left to caller. TODO: Reference hold by this class ?
item Opaque item, ownership left to caller. Reference hold by this class.
Implements geos::index::SpatialIndex.
Definition at line 324 of file STRtree.cpp.
References geos::index::strtree::AbstractSTRtree::insert(), and geos::geom::Envelope::isNull().
Referenced by GEOSSTRtree_insert_r(), geos::operation::geounion::CascadedUnion::Union(), and geos::operation::geounion::CascadedPolygonUnion::Union().
 {
   if (itemEnv->isNull()) { return; }
   AbstractSTRtree::insert(itemEnv, item);
 }
void geos::index::strtree::AbstractSTRtree::insert (const void * bounds, void * item) protected virtual inherited
Also builds the tree, if necessary.
Definition at line 115 of file AbstractSTRtree.cpp.
Referenced by geos::index::strtree::SIRtree::insert(), and insert().
 {
   // Cannot insert items into an STR packed R-tree after it has been built
   assert(!built);
   itemBoundables->push_back(new ItemBoundable(bounds,item));
 }
ItemsList * geos::index::strtree::AbstractSTRtree::itemsTree () inherited
Gets a tree structure (as a nested list) corresponding to the structure of the items and nodes in this tree.
The returned Lists contain either Object items, or Lists which correspond to subtrees of the tree Subtrees which do not contain any items are not included.
Builds the tree if necessary.
Note
The caller is responsible for releasing the list
Returns
a List of items and/or Lists
Definition at line 382 of file AbstractSTRtree.cpp.
Referenced by geos::operation::geounion::CascadedUnion::Union(), and geos::operation::geounion::CascadedPolygonUnion::Union().
 {
     if (!built) {
         build();
     }
     ItemsList* valuesTree (itemsTree(root));
     if (valuesTree == nullptr)
         return new ItemsList();
     return valuesTree;
 }
void geos::index::strtree::AbstractSTRtree::iterate (ItemVisitor & visitor) inherited
Iterate over all items added thus far. Explicitly does not build the tree.
Definition at line 293 of file AbstractSTRtree.cpp.
References geos::index::ItemVisitor::visitItem().
Referenced by geos::precision::MinimumClearance::compute(), and GEOSSTRtree_iterate_r().
 {
     for (BoundableList::const_iterator i=itemBoundables->begin(), e=itemBoundables->end();
       i!=e; i++)
   {
     const Boundable* boundable = *i;
     if (const ItemBoundable *ib=dynamic_cast<const ItemBoundable *>(boundable))
     {
       visitor.visitItem(ib->getItem());
     }
         }
 }
virtual AbstractNode* geos::index::strtree::AbstractSTRtree::lastNode (BoundableList * nodeList) inline protected virtual inherited
Definition at line 196 of file AbstractSTRtree.h.
   {
     assert(!nodeList->empty());
     // Cast from Boundable to AbstractNode
     return static_cast<AbstractNode*>(nodeList->back() );
   }
const void * geos::index::strtree::STRtree::nearestNeighbour (const geom::Envelope * env, const void * item, ItemDistance * itemDist)
Definition at line 189 of file STRtree.cpp.
References geos::index::strtree::AbstractSTRtree::build(), and geos::index::strtree::AbstractSTRtree::getRoot().
Referenced by GEOSSTRtree_nearest_generic_r(), and nearestNeighbour().
{
   build();
   ItemBoundable bnd = ItemBoundable(env, (void*) item);
   BoundablePair bp(getRoot(), &bnd, itemDist);
   return nearestNeighbour(&bp).first;
 }
std::pair< const void *, const void * > geos::index::strtree::STRtree::nearestNeighbour (BoundablePair * initBndPair)
Definition at line 198 of file STRtree.cpp.
References nearestNeighbour().
{
   return nearestNeighbour(initBndPair, std::numeric_limits<double>::infinity());
 }
std::pair< const void *, const void * > geos::index::strtree::STRtree::nearestNeighbour (ItemDistance * itemDist)
Definition at line 202 of file STRtree.cpp.
References geos::index::strtree::AbstractSTRtree::getRoot(), and nearestNeighbour().
{
   BoundablePair bp(this->getRoot(), this->getRoot(), itemDist);
   return nearestNeighbour(&bp);
 }
std::pair< const void *, const void * > geos::index::strtree::STRtree::nearestNeighbour (BoundablePair * initBndPair, double maxDistance)
If the distance for the first node in the queue is >= the current minimum distance, all other nodes in the queue must also have a greater distance. So the current minDistance must be the true minimum, and we are done.
If the pair members are leaves then their distance is the exact lower bound. Update the distanceLowerBound to reflect this (which must be smaller, due to the test immediately prior to this).
Otherwise, expand one side of the pair, (the choice of which side to expand is heuristically determined) and insert the new expanded pairs into the queue
Definition at line 212 of file STRtree.cpp.
References geos::index::strtree::BoundablePair::expandToQueue(), geos::index::strtree::BoundablePair::getBoundable(), geos::index::strtree::BoundablePair::getDistance(), and geos::index::strtree::BoundablePair::isLeaves().
{
   double distanceLowerBound = maxDistance;
   BoundablePair* minPair = nullptr;
   BoundablePair::BoundablePairQueue priQ;
   priQ.push(initBndPair);
   while(!priQ.empty() && distanceLowerBound > 0.0) {
     BoundablePair* bndPair = priQ.top();
     double currentDistance = bndPair->getDistance();
     if (minPair && currentDistance >= distanceLowerBound)
       break;
     priQ.pop();
     if (bndPair->isLeaves()) {
       distanceLowerBound = currentDistance;
       minPair = bndPair;
     } else {
       bndPair->expandToQueue(priQ, distanceLowerBound);
     }
     if (bndPair != initBndPair && bndPair != minPair)
             delete bndPair;
   }
   /* Free any remaining BoundablePairs in the queue */
   while(!priQ.empty()) {
     BoundablePair* bndPair = priQ.top();
     priQ.pop();
     if (bndPair != initBndPair)
             delete bndPair;
   }
   if (!minPair)
     throw util::GEOSException("Error computing nearest neighbor");
   const void* item0 = dynamic_cast<const ItemBoundable*>(minPair->getBoundable(0))->getItem();
   const void* item1 = dynamic_cast<const ItemBoundable*>(minPair->getBoundable(1))->getItem();
   if (minPair != initBndPair)
         delete minPair;
   return std::pair<const void*, const void*>(item0, item1);
 }
std::pair< const void *, const void * > geos::index::strtree::STRtree::nearestNeighbour (STRtree * tree, ItemDistance * itemDist)
Definition at line 207 of file STRtree.cpp.
References geos::index::strtree::AbstractSTRtree::getRoot(), and nearestNeighbour().
{
   BoundablePair bp(getRoot(), tree->getRoot(), itemDist);
   return nearestNeighbour(&bp);
 }
void geos::index::strtree::STRtree::query (const geom::Envelope * searchEnv, std::vector< void * > &) inline override virtual
Queries the index for all items whose extents intersect the given search Envelope.
Note that some kinds of indexes may also return objects which do not in fact intersect the query envelope.
Parameters
searchEnv the envelope to query for
Returns
a list of the items found by the query in a newly allocated vector
Implements geos::index::SpatialIndex.
Definition at line 134 of file STRtree.h.
References geos::index::strtree::AbstractSTRtree::query().
Referenced by GEOSSTRtree_query_r().
{
     AbstractSTRtree::query(searchEnv, matches);
   }
void geos::index::strtree::STRtree::query (const geom::Envelope * searchEnv, ItemVisitor & visitor) inline override virtual
Queries the index for all items whose extents intersect the given search Envelope and applies an ItemVisitor to them.
Note that some kinds of indexes may also return objects which do not in fact intersect the query envelope.
Parameters
searchEnv the envelope to query for
visitor a visitor object to apply to the items found
Implements geos::index::SpatialIndex.
Definition at line 138 of file STRtree.h.
References geos::index::strtree::AbstractSTRtree::query().
{
     return AbstractSTRtree::query(searchEnv, visitor);
   }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, std::vector< void * > & foundItems) protected inherited
Also builds the tree, if necessary.
Definition at line 124 of file AbstractSTRtree.cpp.
Referenced by geos::index::strtree::SIRtree::query(), and query().
 {
   if (!built) build();
   if (itemBoundables->empty()) assert(root->getBounds()==nullptr);
   if (getIntersectsOp()->intersects(root->getBounds(), searchBounds))
   {
     query(searchBounds,root, &matches);
   }
 }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, ItemVisitor & visitor) protected inherited
Also builds the tree, if necessary.
Definition at line 138 of file AbstractSTRtree.cpp.
 {
   if (!built) build();
   if (itemBoundables->empty()) assert(root->getBounds()==nullptr);
   if (getIntersectsOp()->intersects(root->getBounds(),searchBounds))
   {
     query(searchBounds, *root, visitor);
   }
 }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, const AbstractNode & node, ItemVisitor & visitor) protected inherited
Definition at line 152 of file AbstractSTRtree.cpp.
References geos::index::strtree::Boundable::getBounds(), geos::index::strtree::AbstractNode::getChildBoundables(), and geos::index::ItemVisitor::visitItem().
 {
   const BoundableList& boundables = *(node.getChildBoundables());
   for (BoundableList::const_iterator i=boundables.begin(), e=boundables.end();
       i!=e; i++)
   {
     const Boundable* childBoundable = *i;
     if (!getIntersectsOp()->intersects(childBoundable->getBounds(), searchBounds)) {
       continue;
     }
     if(const AbstractNode *an=dynamic_cast<const AbstractNode*>(childBoundable))
     {
       query(searchBounds, *an, visitor);
     }
     else if (const ItemBoundable *ib=dynamic_cast<const ItemBoundable *>(childBoundable))
     {
       visitor.visitItem(ib->getItem());
     }
     else
     {
       assert(0); // unsupported childBoundable type
     }
   }
 }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, const AbstractNode * node, std::vector< void * > * matches) virtual inherited
Definition at line 257 of file AbstractSTRtree.cpp.
References geos::index::strtree::Boundable::getBounds(), geos::index::strtree::AbstractNode::getChildBoundables(), and geos::index::strtree::AbstractSTRtree::IntersectsOp::intersects().
 {
   assert(node);
   const BoundableList& vb = *(node->getChildBoundables());
   IntersectsOp *io=getIntersectsOp();
   //std::size_t vbsize=vb.size();
   //cerr<<"AbstractSTRtree::query: childBoundables: "<<vbsize<<endl;
   for(BoundableList::const_iterator i=vb.begin(), e=vb.end();
       i!=e; ++i)
   {
     const Boundable* childBoundable=*i;
     if (!io->intersects(childBoundable->getBounds(), searchBounds))
     {
       continue;
     }
     if(const AbstractNode *an=dynamic_cast<const AbstractNode*>(childBoundable))
     {
       query(searchBounds, an, matches);
     }
     else if (const ItemBoundable *ib=dynamic_cast<const ItemBoundable *>(childBoundable))
     {
       matches->push_back(ib->getItem());
     }
     else
     {
       assert(0); // unsupported childBoundable type
     }
   }
 }
bool geos::index::strtree::STRtree::remove (const geom::Envelope * itemEnv, void * item) inline override virtual
Removes a single item from the tree.
Parameters
itemEnv the Envelope of the item to remove
item the item to remove
Returns
true if the item was found
Implements geos::index::SpatialIndex.
Definition at line 148 of file STRtree.h.
References geos::index::strtree::AbstractSTRtree::remove().
Referenced by GEOSSTRtree_remove_r().
{
     return AbstractSTRtree::remove(itemEnv, item);
   }
bool geos::index::strtree::AbstractSTRtree::remove (const void * itemEnv, void * item) protected inherited
Also builds the tree, if necessary.
Definition at line 183 of file AbstractSTRtree.cpp.
 {
   if (!built) build();
   if (itemBoundables->empty()) {
     assert(root->getBounds() == nullptr);
   }
   if (getIntersectsOp()->intersects(root->getBounds(), searchBounds)) {
     return remove(searchBounds, *root, item);
   }
   return false;
 }
std::unique_ptr< BoundableList > geos::index::strtree::STRtree::sortBoundables (const BoundableList * input) override private virtual
Implements geos::index::strtree::AbstractSTRtree.
Definition at line 332 of file STRtree.cpp.
References geos::index::strtree::yComparator().
Referenced by createParentBoundables().
 {
   assert(input);
   std::unique_ptr<BoundableList> output ( new BoundableList(*input) );
   assert(output->size() == input->size());
   sort(output->begin(), output->end(), yComparator);
   return output;
 }
std::vector< BoundableList * > * geos::index::strtree::STRtree::verticalSlices (BoundableList * childBoundables, size_t sliceCount) private
Parameters
childBoundables Must be sorted by the x-value of the envelope midpoints
Returns
Definition at line 165 of file STRtree.cpp.
Referenced by createParentBoundables().
 {
   size_t sliceCapacity = (size_t) ceil((double)childBoundables->size() / (double) sliceCount);
   vector<BoundableList*>* slices = new vector<BoundableList*>(sliceCount);
   size_t i=0, nchilds=childBoundables->size();
   for (size_t j=0; j<sliceCount; j++)
   {
     (*slices)[j]=new BoundableList();
     (*slices)[j]->reserve(sliceCapacity);
     size_t boundablesAddedToSlice = 0;
     while (i<nchilds && boundablesAddedToSlice<sliceCapacity)
     {
       Boundable *childBoundable=(*childBoundables)[i];
       ++i;
       (*slices)[j]->push_back(childBoundable);
       ++boundablesAddedToSlice;
     }
   }
   return slices;
 }
Member Data Documentation
STRIntersectsOp geos::index::strtree::STRtree::intersectsOp private
Definition at line 86 of file STRtree.h.
std::size_t geos::index::strtree::AbstractSTRtree::nodeCapacity protected inherited
Definition at line 233 of file AbstractSTRtree.h.
Referenced by createNode(), and geos::index::strtree::SIRtree::SIRtree().
std::vector<AbstractNode *>* geos::index::strtree::AbstractSTRtree::nodes protected inherited
Definition at line 184 of file AbstractSTRtree.h.
Referenced by geos::index::strtree::SIRtree::createNode(), and createNode().
AbstractNode* geos::index::strtree::AbstractSTRtree::root protected inherited
Definition at line 182 of file AbstractSTRtree.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/strtree/STRtree.h
/home/vicky/potree/geos/vicky/src/index/strtree/STRtree.cpp