GEOS: geos::index::quadtree::Key Class Reference
geos::index::quadtree::Key Class Reference
A Key is a unique identifier for a node in a quadtree.
#include <Key.h>
Public Member Functions
Key (const geom::Envelope &itemEnv)
~Key ()
const geom::Coordinate & getPoint () const
Returned object ownership retained by this class.
int getLevel () const
const geom::Envelope & getEnvelope () const
Returned object ownership retained by this class.
geom::Coordinate * getCentre () const
Returns newly allocated object (ownership transferred)
void computeKey (const geom::Envelope &itemEnv)
Static Public Member Functions
static int computeQuadLevel (const geom::Envelope &env)
Private Member Functions
void computeKey (int level, const geom::Envelope &itemEnv)
Private Attributes
geom::Coordinate pt
int level
geom::Envelope env
Detailed Description
A Key is a unique identifier for a node in a quadtree.
It contains a lower-left point and a level number. The level number is the power of two for the size of the node envelope
Definition at line 42 of file Key.h.
Constructor & Destructor Documentation
geos::index::quadtree::Key::Key (const geom::Envelope & itemEnv)
Definition at line 56 of file Key.cpp.
References computeKey().
   :
   pt(),
   level(0),
   env()
 {
   computeKey(itemEnv);
 }
geos::index::quadtree::Key::~Key ()
Definition at line 65 of file Key.cpp.
 {
 }
Member Function Documentation
void geos::index::quadtree::Key::computeKey (const geom::Envelope & itemEnv)
return a square envelope containing the argument envelope, whose extent is a power of two and which is based at a power of 2
Definition at line 98 of file Key.cpp.
References computeQuadLevel(), geos::geom::Envelope::contains(), env, geos::geom::Envelope::init(), level, and geos::geom::Envelope::toString().
Referenced by Key().
 {
   level=computeQuadLevel(itemEnv);
   env.init(); // reset to null
   computeKey(level, itemEnv);
   // MD - would be nice to have a non-iterative form of this algorithm
   while (!env.contains(itemEnv)) {
     level+=1;
     computeKey(level, itemEnv);
   }
 #if GEOS_DEBUG
   std::cerr<<"Key::computeKey:"<<std::endl;
   std::cerr<<" itemEnv: "<<itemEnv.toString()<<std::endl;
   std::cerr<<"  keyEnv: "<<env.toString()<<std::endl;
   std::cerr<<"  keyLvl: "<<level<<std::endl;
 #endif
 }
void geos::index::quadtree::Key::computeKey (int level, const geom::Envelope & itemEnv) private
Definition at line 118 of file Key.cpp.
References env, geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), geos::geom::Envelope::init(), geos::index::quadtree::DoubleBits::powerOf2(), pt, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   double quadSize=DoubleBits::powerOf2(level);
   //double quadSize=pow2.power(level);
   pt.x = std::floor(itemEnv.getMinX()/quadSize)*quadSize;
   pt.y = std::floor(itemEnv.getMinY()/quadSize)*quadSize;
   env.init(pt.x, pt.x + quadSize, pt.y, pt.y + quadSize);
 }
int geos::index::quadtree::Key::computeQuadLevel (const geom::Envelope & env) static
Definition at line 44 of file Key.cpp.
References geos::geom::Envelope::getHeight(), and geos::geom::Envelope::getWidth().
Referenced by computeKey().
 {
   double dx = env.getWidth();
   double dy = env.getHeight();
   double dMax = dx > dy ? dx : dy;
   int level=DoubleBits::exponent(dMax)+1;
 #if GEOS_DEBUG
   std::cerr<<"Maxdelta:"<<dMax<<" exponent:"<<(level-1)<<std::endl;
 #endif
   return level;
 }
Coordinate * geos::index::quadtree::Key::getCentre () const
Returns newly allocated object (ownership transferred)
Definition at line 88 of file Key.cpp.
References env, geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), and geos::geom::Envelope::getMinY().
 {
   return new Coordinate(
       ( env.getMinX() + env.getMaxX() ) / 2,
       ( env.getMinY() + env.getMaxY() ) / 2
     );
 }
const Envelope & geos::index::quadtree::Key::getEnvelope () const
Returned object ownership retained by this class.
Definition at line 82 of file Key.cpp.
References env.
Referenced by geos::index::quadtree::Node::createNode().
 {
   return env;
 }
int geos::index::quadtree::Key::getLevel () const
Definition at line 76 of file Key.cpp.
References level.
Referenced by geos::index::quadtree::Node::createNode().
 {
   return level;
 }
const Coordinate & geos::index::quadtree::Key::getPoint () const
Returned object ownership retained by this class.
Definition at line 70 of file Key.cpp.
References pt.
 {
   return pt;
 }
Member Data Documentation
geom::Envelope geos::index::quadtree::Key::env private
Definition at line 80 of file Key.h.
Referenced by computeKey(), getCentre(), and getEnvelope().
int geos::index::quadtree::Key::level private
Definition at line 77 of file Key.h.
Referenced by computeKey(), and getLevel().
geom::Coordinate geos::index::quadtree::Key::pt private
Definition at line 75 of file Key.h.
Referenced by computeKey(), and getPoint().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/quadtree/Key.h
/home/vicky/potree/geos/vicky/src/index/quadtree/Key.cpp