GEOS: geos::algorithm::distance::DiscreteFrechetDistance Class Reference
geos::algorithm::distance::DiscreteFrechetDistance Class Reference
An algorithm for computing a distance metric which is an approximation to the Frechet Distance based on a discretization of the input Geometry.
#include <DiscreteFrechetDistance.h>
Public Member Functions
DiscreteFrechetDistance (const geom::Geometry &g0, const geom::Geometry &g1)
void setDensifyFraction (double dFrac)
double distance ()
const std::vector< geom::Coordinate > getCoordinates () const
Static Public Member Functions
static double distance (const geom::Geometry &g0, const geom::Geometry &g1)
static double distance (const geom::Geometry &g0, const geom::Geometry &g1, double densifyFrac)
Private Member Functions
geom::Coordinate getSegementAt (const geom::CoordinateSequence &seq, size_t index)
PointPairDistance & getFrecheDistance (std::vector< std::vector< PointPairDistance > > &ca, size_t i, size_t j, const geom::CoordinateSequence &p, const geom::CoordinateSequence &q)
void compute (const geom::Geometry &discreteGeom, const geom::Geometry &geom)
DiscreteFrechetDistance (const DiscreteFrechetDistance &other)=delete
DiscreteFrechetDistance & operator= (const DiscreteFrechetDistance &rhs)=delete
Private Attributes
const geom::Geometry & g0
const geom::Geometry & g1
PointPairDistance ptDist
double densifyFrac
Value of 0.0 indicates that no densification should take place.
Detailed Description
An algorithm for computing a distance metric which is an approximation to the Frechet Distance based on a discretization of the input Geometry.
The algorithm computes the Frechet distance restricted to discrete points for one of the geometries. The points can be either the vertices of the geometries (the default), or the geometries with line segments densified by a given fraction. Also determines two points of the Geometries which are separated by the computed distance.
This algorithm is an approximation to the standard Frechet distance. Specifically,
   for all geometries a, b:    DFD(a, b) >= FD(a, b)
The approximation can be made as close as needed by densifying the input geometries. In the limit, this value will approach the true Frechet distance:
   DFD(A, B, densifyFactor) -> FD(A, B) as densifyFactor -> 0.0
The default approximation is exact or close enough for a large subset of useful cases.
The difference between DFD and FD is bounded by the length of the longest edge of the polygonal curves.
Fréchet distance sweep continuously along their respective curves and the direction of curves is significant. This makes a better measure of similarity than Hausdorff distance.
An example showing how different DHD and DFD are:
  A  = LINESTRING (0 0, 50 200, 100 0, 150 200, 200 0)
  B  = LINESTRING (0 200, 200 150, 0 100, 200 50, 0 0)
  B' = LINESTRING (0 0, 200 50, 0 100, 200 150, 0 200)
  DHD(A, B)  = DHD(A, B') = 48.5071250072666
  DFD(A, B)  = 200
  DFD(A, B') = 282.842712474619
Definition at line 106 of file DiscreteFrechetDistance.h.
Constructor & Destructor Documentation
geos::algorithm::distance::DiscreteFrechetDistance::DiscreteFrechetDistance (const geom::Geometry & g0, const geom::Geometry & g1) inline
Definition at line 116 of file DiscreteFrechetDistance.h.
     :
     g0(g0),
     g1(g1),
     ptDist(),
     densifyFrac(0.0)
   {}
geos::algorithm::distance::DiscreteFrechetDistance::DiscreteFrechetDistance (const DiscreteFrechetDistance & other) private delete
Member Function Documentation
void geos::algorithm::distance::DiscreteFrechetDistance::compute (const geom::Geometry & discreteGeom, const geom::Geometry & geom) private
Definition at line 123 of file DiscreteFrechetDistance.cpp.
References geos::geom::Geometry::getCoordinates(), geos::util::round(), and geos::geom::CoordinateSequence::size().
 {
   const CoordinateSequence* lp = discreteGeom.getCoordinates();
   const CoordinateSequence* lq = geom.getCoordinates();
   size_t pSize, qSize;
   if (densifyFrac > 0)
   {
     size_t numSubSegs =  std::size_t(util::round(1.0/densifyFrac));
     pSize = numSubSegs * (lp->size() - 1) + 1;
     qSize = numSubSegs * (lq->size() - 1) + 1;
   }
   else
   {
     pSize = lp->size();
     qSize = lq->size();
   }
   std::vector< std::vector<PointPairDistance> > ca(pSize, std::vector<PointPairDistance>(qSize));
   for (size_t i = 0; i < pSize; i++)
   {
     for (size_t j = 0; j < qSize; j++)
     {
       ca[i][j].initialize();
     }
   }
   ptDist = getFrecheDistance(ca, pSize-1, qSize-1, *lp, *lq);
   delete lp;
   delete lq;
 }
double geos::algorithm::distance::DiscreteFrechetDistance::distance (const geom::Geometry & g0, const geom::Geometry & g1) static
Definition at line 38 of file DiscreteFrechetDistance.cpp.
References distance().
Referenced by distance().
 {
   DiscreteFrechetDistance dist(g0, g1);
   return dist.distance();
 }
double geos::algorithm::distance::DiscreteFrechetDistance::distance (const geom::Geometry & g0, const geom::Geometry & g1, double densifyFrac) static
Definition at line 47 of file DiscreteFrechetDistance.cpp.
References distance(), and setDensifyFraction().
 {
   DiscreteFrechetDistance dist(g0, g1);
   dist.setDensifyFraction(densifyFrac);
   return dist.distance();
 }
double geos::algorithm::distance::DiscreteFrechetDistance::distance () inline
Definition at line 144 of file DiscreteFrechetDistance.h.
   {
     compute(g0, g1);
     return ptDist.getDistance();
   }
const std::vector<geom::Coordinate> geos::algorithm::distance::DiscreteFrechetDistance::getCoordinates () const inline
Definition at line 150 of file DiscreteFrechetDistance.h.
   {
     return ptDist.getCoordinates();
   }
PointPairDistance & geos::algorithm::distance::DiscreteFrechetDistance::getFrecheDistance (std::vector< std::vector< PointPairDistance > > & ca, size_t i, size_t j, const geom::CoordinateSequence & p, const geom::CoordinateSequence & q) private
Definition at line 87 of file DiscreteFrechetDistance.cpp.
References geos::algorithm::distance::PointPairDistance::getDistance(), and geos::algorithm::distance::PointPairDistance::initialize().
 {
   PointPairDistance ptDist;
   if (! ca[i][j].getIsNull())
   {
     return ca[i][j];
   }
   ptDist.initialize(getSegementAt(p, i), getSegementAt(q, j));
   if (i == 0 && j == 0)
   {
     ca[i][j] = ptDist;
   }
   else if (i > 0 && j == 0)
   {
     PointPairDistance nextDist = getFrecheDistance(ca,i-1,0,p,q);
     ca[i][j] =  (nextDist.getDistance() > ptDist.getDistance()) ? nextDist : ptDist;
   }
   else if (i == 0 && j > 0)
   {
     PointPairDistance nextDist = getFrecheDistance(ca,0,j-1,p,q);
     ca[i][j] =  (nextDist.getDistance() > ptDist.getDistance()) ? nextDist : ptDist;
   }
   else
   {
     PointPairDistance d1 = getFrecheDistance(ca,i-1,j,p,q),
           d2 = getFrecheDistance(ca,i-1,j-1,p,q),
           d3 = getFrecheDistance(ca,i,j-1,p,q);
     PointPairDistance& minDist = (d1.getDistance() < d2.getDistance()) ? d1 : d2;
     if (d3.getDistance() < minDist.getDistance()) minDist = d3;
     ca[i][j] =  (minDist.getDistance() > ptDist.getDistance()) ? minDist : ptDist;
   }
   return ca[i][j];
 }
geom::Coordinate geos::algorithm::distance::DiscreteFrechetDistance::getSegementAt (const geom::CoordinateSequence & seq, size_t index) private
Definition at line 59 of file DiscreteFrechetDistance.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::util::round(), geos::geom::CoordinateSequence::size(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   if (densifyFrac > 0.0)
   {
     size_t numSubSegs =  std::size_t(util::round(1.0/densifyFrac));
     size_t i = index / numSubSegs;
     size_t j = index % numSubSegs;
     if (i >= seq.size()-1) {
       return seq.getAt(seq.size()-1);
     }
     const geom::Coordinate& p0 = seq.getAt(i);
     const geom::Coordinate& p1 = seq.getAt(i+1);
     double delx = (p1.x - p0.x)/static_cast<double>(numSubSegs);
     double dely = (p1.y - p0.y)/static_cast<double>(numSubSegs);
     double x = p0.x + static_cast<double>(j)*delx;
     double y = p0.y + static_cast<double>(j)*dely;
     Coordinate pt(x, y);
     return pt;
   }
   else
   {
     return seq.getAt(index);
   }
 }
DiscreteFrechetDistance& geos::algorithm::distance::DiscreteFrechetDistance::operator= (const DiscreteFrechetDistance & rhs) private delete
void geos::algorithm::distance::DiscreteFrechetDistance::setDensifyFraction (double dFrac) inline
Sets the fraction by which to densify each segment. Each segment will be (virtually) split into a number of equal-length subsegments, whose fraction of the total length is closest to the given fraction.
Parameters
dFrac
Definition at line 133 of file DiscreteFrechetDistance.h.
Referenced by distance().
   {
     if ( dFrac > 1.0 || dFrac <= 0.0 )
     {
       throw util::IllegalArgumentException(
         "Fraction is not in range (0.0 - 1.0]");
     }
     densifyFrac = dFrac;
   }
Member Data Documentation
double geos::algorithm::distance::DiscreteFrechetDistance::densifyFrac private
Value of 0.0 indicates that no densification should take place.
Definition at line 169 of file DiscreteFrechetDistance.h.
const geom::Geometry& geos::algorithm::distance::DiscreteFrechetDistance::g0 private
Definition at line 162 of file DiscreteFrechetDistance.h.
const geom::Geometry& geos::algorithm::distance::DiscreteFrechetDistance::g1 private
Definition at line 164 of file DiscreteFrechetDistance.h.
PointPairDistance geos::algorithm::distance::DiscreteFrechetDistance::ptDist private
Definition at line 166 of file DiscreteFrechetDistance.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/distance/DiscreteFrechetDistance.h
/home/vicky/potree/geos/vicky/src/algorithm/distance/DiscreteFrechetDistance.cpp