GEOS: geos::operation::distance::FacetSequenceTreeBuilder Class Reference
geos::operation::distance::FacetSequenceTreeBuilder Class Reference
#include <FacetSequenceTreeBuilder.h>
Static Public Member Functions
static geos::index::strtree::STRtree * build (const geom::Geometry *g)
Static Private Member Functions
static void addFacetSequences (const geom::CoordinateSequence *pts, std::vector< FacetSequence * > &sections)
static std::vector< FacetSequence * > * computeFacetSequences (const geom::Geometry *g)
Static Private Attributes
static const int FACET_SEQUENCE_SIZE = 6
static const int STR_TREE_NODE_CAPACITY = 4
Detailed Description
Definition at line 30 of file FacetSequenceTreeBuilder.h.
Member Function Documentation
void geos::operation::distance::FacetSequenceTreeBuilder::addFacetSequences (const geom::CoordinateSequence * pts, std::vector< FacetSequence * > & sections) static private
Definition at line 69 of file FacetSequenceTreeBuilder.cpp.
References geos::geom::CoordinateSequence::size().
{
     size_t i = 0;
     size_t size = pts->size();
     while (i <= size - 1) {
         size_t end = i + FACET_SEQUENCE_SIZE + 1;
         // if only one point remains after this section, include it in this
         // section
         if (end >= size - 1)
             end = size;
         FacetSequence* sect = new FacetSequence(pts, i, end);
         sections.push_back(sect);
         i += FACET_SEQUENCE_SIZE;
     }
 }
STRtree * geos::operation::distance::FacetSequenceTreeBuilder::build (const geom::Geometry * g) static
Definition at line 30 of file FacetSequenceTreeBuilder.cpp.
References geos::operation::distance::FacetSequence::getEnvelope().
{
     std::unique_ptr<STRtree> tree(new STRtree(STR_TREE_NODE_CAPACITY));
     std::unique_ptr<std::vector<FacetSequence*> > sections(computeFacetSequences(g));
     for (std::vector<FacetSequence*>::iterator it = sections->begin(); it != sections->end(); ++it) {
         FacetSequence* section = *it;
         tree->insert(section->getEnvelope(), section);
     }
     tree->build();
     return tree.release();
 }
std::vector< FacetSequence * > * geos::operation::distance::FacetSequenceTreeBuilder::computeFacetSequences (const geom::Geometry * g) static private
Definition at line 42 of file FacetSequenceTreeBuilder.cpp.
References geos::geom::Geometry::apply_ro().
{
     std::unique_ptr<std::vector<FacetSequence*> > sections(new std::vector<FacetSequence*>());
     class FacetSequenceAdder;
     class FacetSequenceAdder : public geom::GeometryComponentFilter {
         std::vector<FacetSequence*>*  m_sections;
     public :
         FacetSequenceAdder(std::vector<FacetSequence*> * p_sections) :
             m_sections(p_sections) {}
         void filter_ro(const Geometry* geom) override {
             if (const LineString* ls = dynamic_cast<const LineString*>(geom)) {
                 const CoordinateSequence* seq = ls->getCoordinatesRO();
                 addFacetSequences(seq, *m_sections);
             } else if (const Point* pt = dynamic_cast<const Point*>(geom)) {
                 const CoordinateSequence* seq = pt->getCoordinatesRO();
                 addFacetSequences(seq, *m_sections);
             }
         }
     };
     FacetSequenceAdder facetSequenceAdder(sections.get());
     g->apply_ro(&facetSequenceAdder);
     return sections.release();
 }
Member Data Documentation
const int geos::operation::distance::FacetSequenceTreeBuilder::FACET_SEQUENCE_SIZE = 6 static private
Definition at line 33 of file FacetSequenceTreeBuilder.h.
const int geos::operation::distance::FacetSequenceTreeBuilder::STR_TREE_NODE_CAPACITY = 4 static private
Definition at line 36 of file FacetSequenceTreeBuilder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/distance/FacetSequenceTreeBuilder.h
/home/vicky/potree/geos/vicky/src/operation/distance/FacetSequenceTreeBuilder.cpp