GEOS: geos::algorithm::distance::DistanceToPoint Class Reference
geos::algorithm::distance::DistanceToPoint Class Reference
#include <DistanceToPoint.h>
Public Member Functions
DistanceToPoint ()
Static Public Member Functions
static void computeDistance (const geom::Geometry &geom, const geom::Coordinate &pt, PointPairDistance &ptDist)
static void computeDistance (const geom::LineString &geom, const geom::Coordinate &pt, PointPairDistance &ptDist)
static void computeDistance (const geom::LineSegment &geom, const geom::Coordinate &pt, PointPairDistance &ptDist)
static void computeDistance (const geom::Polygon &geom, const geom::Coordinate &pt, PointPairDistance &ptDist)
Detailed Description
Computes the Euclidean distance (L2 metric) from a Point to a Geometry.
Also computes two points which are separated by the distance.
Definition at line 47 of file DistanceToPoint.h.
Constructor & Destructor Documentation
geos::algorithm::distance::DistanceToPoint::DistanceToPoint () inline
Definition at line 51 of file DistanceToPoint.h.
 {}
Member Function Documentation
void geos::algorithm::distance::DistanceToPoint::computeDistance (const geom::Geometry & geom, const geom::Coordinate & pt, PointPairDistance & ptDist) static
Definition at line 39 of file DistanceToPoint.cpp.
References geos::geom::Geometry::getCoordinate(), geos::geom::Geometry::getGeometryN(), and geos::algorithm::distance::PointPairDistance::setMinimum().
 {
   if ( const LineString* ls = dynamic_cast<const LineString*>(&geom) )
   {
     computeDistance(*ls, pt, ptDist);
   }
   else if ( const Polygon* pl = dynamic_cast<const Polygon*>(&geom) )
   {
     computeDistance(*pl, pt, ptDist);
   }
   else if ( const GeometryCollection* gc = dynamic_cast<const GeometryCollection*>(&geom) )
   {
     for (size_t i = 0; i < gc->getNumGeometries(); i++)
     {
       const Geometry* g = gc->getGeometryN(i);
       computeDistance(*g, pt, ptDist);
     }
   }
   else
   {
     // assume geom is Point
     ptDist.setMinimum(*(geom.getCoordinate()), pt);
   }
 }
void geos::algorithm::distance::DistanceToPoint::computeDistance (const geom::LineString & geom, const geom::Coordinate & pt, PointPairDistance & ptDist) static
Definition at line 68 of file DistanceToPoint.cpp.
References geos::geom::LineSegment::closestPoint(), geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, geos::algorithm::distance::PointPairDistance::setMinimum(), and geos::geom::CoordinateSequence::size().
 {
   const CoordinateSequence* coordsRO = line.getCoordinatesRO();
   const CoordinateSequence& coords = *coordsRO;
   size_t npts = coords.size();
   if ( ! npts ) return; // can this ever be ?
   LineSegment tempSegment;
   Coordinate closestPt;
   Coordinate* segPts[2] = { &(tempSegment.p0), &(tempSegment.p1) };
   tempSegment.p0 = coords.getAt(0);
   for (size_t i=1; i<npts; ++i)
   {
     *(segPts[i%2]) = coords.getAt(i);
     // this is somewhat inefficient - could do better
     tempSegment.closestPoint(pt, closestPt);
     ptDist.setMinimum(closestPt, pt);
   }
 }
void geos::algorithm::distance::DistanceToPoint::computeDistance (const geom::LineSegment & geom, const geom::Coordinate & pt, PointPairDistance & ptDist) static
Definition at line 95 of file DistanceToPoint.cpp.
References geos::geom::LineSegment::closestPoint(), and geos::algorithm::distance::PointPairDistance::setMinimum().
 {
   Coordinate closestPt;
   segment.closestPoint(pt, closestPt);
   ptDist.setMinimum(closestPt, pt);
 }
void geos::algorithm::distance::DistanceToPoint::computeDistance (const geom::Polygon & geom, const geom::Coordinate & pt, PointPairDistance & ptDist) static
Definition at line 106 of file DistanceToPoint.cpp.
References geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), and geos::geom::Polygon::getNumInteriorRing().
 {
   computeDistance(*(poly.getExteriorRing()), pt, ptDist);
   for (size_t i=0, n=poly.getNumInteriorRing(); i<n; ++i)
   {
     computeDistance(*(poly.getInteriorRingN(i)), pt, ptDist);
   }
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/distance/DistanceToPoint.h
/home/vicky/potree/geos/vicky/src/algorithm/distance/DistanceToPoint.cpp