GEOS: geos::noding::Noder Class Reference
geos::noding::Noder Class Reference abstract
Computes all intersections between segments in a set of SegmentString.
#include <Noder.h>
Public Member Functions
virtual void computeNodes (std::vector< SegmentString * > *segStrings)=0
Computes the noding for a collection of SegmentStrings.
virtual std::vector< SegmentString * > * getNodedSubstrings () const =0
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
virtual ~Noder ()
Protected Member Functions
Noder ()
Detailed Description
Computes all intersections between segments in a set of SegmentString.
Intersections found are represented as SegmentNodes and added to the SegmentStrings in which they occur. As a final step in the noding a new set of segment strings split at the nodes may be returned.
Last port: noding/Noder.java rev. 1.8 (JTS-1.7)
TODO: this was really an interface, we should avoid making it a Base class
Definition at line 49 of file Noder.h.
Constructor & Destructor Documentation
virtual geos::noding::Noder::~Noder () inline virtual
Definition at line 70 of file Noder.h.
 {}
geos::noding::Noder::Noder () inline protected
Definition at line 73 of file Noder.h.
 {}
Member Function Documentation
virtual void geos::noding::Noder::computeNodes (std::vector< SegmentString * > * segStrings) pure virtual
Computes the noding for a collection of SegmentStrings.
Some Noders may add all these nodes to the input SegmentStrings; others may only add some or none at all.
Parameters
segStrings a collection of SegmentStrings to node
Implemented in geos::noding::IteratedNoder, geos::noding::MCIndexNoder, geos::noding::snapround::MCIndexSnapRounder, geos::noding::ScaledNoder, geos::noding::SinglePassNoder, geos::noding::snapround::SimpleSnapRounder, and geos::noding::SimpleNoder.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::operation::buffer::BufferBuilder::computeNodedEdges(), and geos::noding::GeometryNoder::getNoded().
virtual std::vector<SegmentString*>* geos::noding::Noder::getNodedSubstrings () const pure virtual
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
Returns
a newly allocated std::vector of const SegmentStrings. Caller is responsible to delete container and elements.
Implemented in geos::noding::IteratedNoder, geos::noding::MCIndexNoder, geos::noding::SinglePassNoder, geos::noding::snapround::MCIndexSnapRounder, geos::noding::ScaledNoder, geos::noding::snapround::SimpleSnapRounder, and geos::noding::SimpleNoder.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), and geos::noding::GeometryNoder::getNoded().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/noding/Noder.h