GEOS: geos::operation::linemerge::EdgeString Class Reference
geos::operation::linemerge::EdgeString Class Reference
A sequence of LineMergeDirectedEdge forming one of the lines that will be output by the line-merging process.
#include <EdgeString.h>
Public Member Functions
EdgeString (const geom::GeometryFactory *newFactory)
~EdgeString ()
void add (LineMergeDirectedEdge *directedEdge)
geom::LineString * toLineString ()
Private Member Functions
geom::CoordinateSequence * getCoordinates ()
Private Attributes
const geom::GeometryFactory * factory
std::vector< LineMergeDirectedEdge * > directedEdges
geom::CoordinateSequence * coordinates
Detailed Description
A sequence of LineMergeDirectedEdge forming one of the lines that will be output by the line-merging process.
Definition at line 55 of file EdgeString.h.
Constructor & Destructor Documentation
geos::operation::linemerge::EdgeString::EdgeString (const geom::GeometryFactory * newFactory)
Constructs an EdgeString with the given factory used to convert this EdgeString to a LineString
Definition at line 43 of file EdgeString.cpp.
                                                        :
   factory(newFactory),
   directedEdges(),
   coordinates(nullptr)
 {
 }
geos::operation::linemerge::EdgeString::~EdgeString ()
Definition at line 50 of file EdgeString.cpp.
{
 }
Member Function Documentation
void geos::operation::linemerge::EdgeString::add (LineMergeDirectedEdge * directedEdge)
Adds a directed edge which is known to form part of this line.
Definition at line 57 of file EdgeString.cpp.
References directedEdges.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringStartingWith().
 {
   directedEdges.push_back(directedEdge);
 }
CoordinateSequence * geos::operation::linemerge::EdgeString::getCoordinates (void) private
Definition at line 63 of file EdgeString.cpp.
References geos::geom::CoordinateSequence::add(), coordinates, geos::geom::CoordinateSequenceFactory::create(), directedEdges, factory, geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::geom::LineString::getCoordinatesRO(), geos::planargraph::DirectedEdge::getEdge(), geos::planargraph::DirectedEdge::getEdgeDirection(), and geos::operation::linemerge::LineMergeEdge::getLine().
Referenced by toLineString().
 {
   if (coordinates==nullptr) {
     int forwardDirectedEdges = 0;
     int reverseDirectedEdges = 0;
     coordinates=factory->getCoordinateSequenceFactory()->create();
     for (std::size_t i=0, e=directedEdges.size(); i<e; ++i) {
       LineMergeDirectedEdge* directedEdge = directedEdges[i];
       if (directedEdge->getEdgeDirection()) {
         forwardDirectedEdges++;
       } else {
         reverseDirectedEdges++;
       }
       assert(dynamic_cast<LineMergeEdge*>(directedEdge->getEdge()));
       LineMergeEdge* lme=static_cast<LineMergeEdge*>( directedEdge->getEdge());
       coordinates->add(lme->getLine()->getCoordinatesRO(),
           false,
           directedEdge->getEdgeDirection());
     }
     if (reverseDirectedEdges > forwardDirectedEdges) {
       CoordinateSequence::reverse(coordinates);
     }
   }
   return coordinates;
 }
LineString * geos::operation::linemerge::EdgeString::toLineString ()
Definition at line 95 of file EdgeString.cpp.
References geos::geom::GeometryFactory::createLineString(), factory, and getCoordinates().
Referenced by geos::operation::linemerge::LineMerger::merge().
 {
   return factory->createLineString(getCoordinates());
 }
Member Data Documentation
geom::CoordinateSequence* geos::operation::linemerge::EdgeString::coordinates private
Definition at line 59 of file EdgeString.h.
Referenced by getCoordinates().
std::vector<LineMergeDirectedEdge*> geos::operation::linemerge::EdgeString::directedEdges private
Definition at line 58 of file EdgeString.h.
Referenced by add(), and getCoordinates().
const geom::GeometryFactory* geos::operation::linemerge::EdgeString::factory private
Definition at line 57 of file EdgeString.h.
Referenced by getCoordinates(), and toLineString().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/linemerge/EdgeString.h
/home/vicky/potree/geos/vicky/src/operation/linemerge/EdgeString.cpp