GEOS: geos::linearref::LengthIndexOfPoint Class Reference
geos::linearref::LengthIndexOfPoint Class Reference
Computes the length index of the point on a linear Geometry nearest a given Coordinate.
#include <LengthIndexOfPoint.h>
Public Member Functions
LengthIndexOfPoint (const geom::Geometry *linearGeom)
double indexOf (const geom::Coordinate &inputPt) const
double indexOfAfter (const geom::Coordinate &inputPt, double minIndex) const
Finds the nearest index along the linear Geometry to a given Coordinate after the specified minimum index.
Static Public Member Functions
static double indexOf (const geom::Geometry *linearGeom, const geom::Coordinate &inputPt)
static double indexOfAfter (const geom::Geometry *linearGeom, const geom::Coordinate &inputPt, double minIndex)
Private Member Functions
double indexOfFromStart (const geom::Coordinate &inputPt, const double minIndex) const
double segmentNearestMeasure (const geom::LineSegment *seg, const geom::Coordinate &inputPt, double segmentStartMeasure) const
Private Attributes
const geom::Geometry * linearGeom
Detailed Description
Computes the length index of the point on a linear Geometry nearest a given Coordinate.
The nearest point is not necessarily unique; this class always computes the nearest point closest to the start of the geometry.
Definition at line 45 of file LengthIndexOfPoint.h.
Constructor & Destructor Documentation
geos::linearref::LengthIndexOfPoint::LengthIndexOfPoint (const geom::Geometry * linearGeom)
Definition at line 50 of file LengthIndexOfPoint.cpp.
                                                                 :
     linearGeom(linearGeom) {}
Member Function Documentation
double geos::linearref::LengthIndexOfPoint::indexOf (const geom::Geometry * linearGeom, const geom::Coordinate & inputPt) static
Definition at line 38 of file LengthIndexOfPoint.cpp.
References indexOf().
Referenced by indexOf(), geos::linearref::LengthIndexedLine::indexOf(), indexOfAfter(), and geos::linearref::LengthIndexedLine::project().
 {
   LengthIndexOfPoint locater(linearGeom);
   return locater.indexOf(inputPt);
 }
double geos::linearref::LengthIndexOfPoint::indexOf (const geom::Coordinate & inputPt) const
Find the nearest location along a linear Geometry to a given point.
Parameters
inputPt the coordinate to locate
Returns
the location of the nearest point
Definition at line 53 of file LengthIndexOfPoint.cpp.
References indexOfFromStart().
 {
   return indexOfFromStart(inputPt, -1.0);
 }
double geos::linearref::LengthIndexOfPoint::indexOfAfter (const geom::Geometry * linearGeom, const geom::Coordinate & inputPt, double minIndex) static
Definition at line 44 of file LengthIndexOfPoint.cpp.
References indexOfAfter().
Referenced by indexOfAfter(), and geos::linearref::LengthIndexedLine::indexOfAfter().
 {
   LengthIndexOfPoint locater(linearGeom);
   return locater.indexOfAfter(inputPt, minIndex);
 }
double geos::linearref::LengthIndexOfPoint::indexOfAfter (const geom::Coordinate & inputPt, double minIndex) const
Finds the nearest index along the linear Geometry to a given Coordinate after the specified minimum index.
If possible the location returned will be strictly greater than the minLocation. If this is not possible, the value returned will equal minLocation. (An example where this is not possible is when minLocation = [end of line]).
Parameters
inputPt the coordinate to locate
minLocation the minimum location for the point location
Returns
the location of the nearest point
Return the minDistanceLocation found. This will not be null, since it was initialized to minLocation
Definition at line 59 of file LengthIndexOfPoint.cpp.
References geos::geom::Geometry::getLength(), indexOf(), indexOfFromStart(), and linearGeom.
 {
   if (minIndex < 0.0) return indexOf(inputPt);
   // sanity check for minIndex at or past end of line
   double endIndex = linearGeom->getLength();
   if (endIndex < minIndex)
     return endIndex;
   double closestAfter = indexOfFromStart(inputPt, minIndex);
   if (closestAfter <= minIndex)
   {
     throw util::IllegalArgumentException("computed index is before specified minimum index");
   }
   return closestAfter;
 }
double geos::linearref::LengthIndexOfPoint::indexOfFromStart (const geom::Coordinate & inputPt, const double minIndex) const private
Definition at line 80 of file LengthIndexOfPoint.cpp.
References geos::geom::LineSegment::distance(), geos::geom::LineSegment::getLength(), geos::linearref::LinearIterator::getSegmentEnd(), geos::linearref::LinearIterator::getSegmentStart(), geos::linearref::LinearIterator::hasNext(), geos::linearref::LinearIterator::isEndOfLine(), linearGeom, geos::linearref::LinearIterator::next(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and segmentNearestMeasure().
Referenced by indexOf(), and indexOfAfter().
 {
   double minDistance = numeric_limits<double>::max();
   double ptMeasure = minIndex;
   double segmentStartMeasure = 0.0;
   LineSegment seg;
   LinearIterator it(linearGeom);
   while (it.hasNext())
   {
     if (! it.isEndOfLine())
     {
       seg.p0 = it.getSegmentStart();
       seg.p1 = it.getSegmentEnd();
       double segDistance = seg.distance(inputPt);
       double segMeasureToPt = segmentNearestMeasure(&seg, inputPt, segmentStartMeasure);
       if (segDistance < minDistance
           && segMeasureToPt > minIndex)
       {
         ptMeasure = segMeasureToPt;
         minDistance = segDistance;
       }
       segmentStartMeasure += seg.getLength();
     }
     it.next();
   }
   return ptMeasure;
 }
double geos::linearref::LengthIndexOfPoint::segmentNearestMeasure (const geom::LineSegment * seg, const geom::Coordinate & inputPt, double segmentStartMeasure) const private
Definition at line 109 of file LengthIndexOfPoint.cpp.
References geos::geom::LineSegment::getLength(), and geos::geom::LineSegment::projectionFactor().
Referenced by indexOfFromStart().
 {
   // found new minimum, so compute location distance of point
   double projFactor = seg->projectionFactor(inputPt);
   if (projFactor <= 0.0)
     return segmentStartMeasure;
   if (projFactor <= 1.0)
     return segmentStartMeasure + projFactor * seg->getLength();
   // projFactor > 1.0
   return segmentStartMeasure + seg->getLength();
 }
Member Data Documentation
const geom::Geometry* geos::linearref::LengthIndexOfPoint::linearGeom private
Definition at line 49 of file LengthIndexOfPoint.h.
Referenced by indexOfAfter(), and indexOfFromStart().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/linearref/LengthIndexOfPoint.h
/home/vicky/potree/geos/vicky/src/linearref/LengthIndexOfPoint.cpp