GEOS: geos::index::quadtree::NodeBase Class Reference
geos::index::quadtree::NodeBase Class Reference abstract
The base class for nodes in a Quadtree.
#include <NodeBase.h>
Public Member Functions
NodeBase ()
virtual ~NodeBase ()
std::vector< void * > & getItems ()
void add (void *item)
std::vector< void * > & addAllItems (std::vector< void * > &resultItems) const
Push all node items to the given vector, return the argument.
virtual void addAllItemsFromOverlapping (const geom::Envelope &searchEnv, std::vector< void * > &resultItems) const
unsigned int depth () const
unsigned int size () const
unsigned int getNodeCount () const
virtual std::string toString () const
virtual void visit (const geom::Envelope *searchEnv, ItemVisitor &visitor)
bool remove (const geom::Envelope *itemEnv, void *item)
bool hasItems () const
bool hasChildren () const
bool isPrunable () const
Static Public Member Functions
static int getSubnodeIndex (const geom::Envelope *env, const geom::Coordinate &centre)
Protected Member Functions
virtual bool isSearchMatch (const geom::Envelope &searchEnv) const =0
Protected Attributes
std::vector< void * > items
Actual items are NOT owned by this class.
Node * subnode [4]
Private Member Functions
void visitItems (const geom::Envelope *searchEnv, ItemVisitor &visitor)
Detailed Description
The base class for nodes in a Quadtree.
Definition at line 54 of file NodeBase.h.
Constructor & Destructor Documentation
geos::index::quadtree::NodeBase::NodeBase ()
Definition at line 64 of file NodeBase.cpp.
 {
   subnode[0]=nullptr;
   subnode[1]=nullptr;
   subnode[2]=nullptr;
   subnode[3]=nullptr;
 }
geos::index::quadtree::NodeBase::~NodeBase () virtual
Definition at line 72 of file NodeBase.cpp.
 {
   delete subnode[0];
   delete subnode[1];
   delete subnode[2];
   delete subnode[3];
   subnode[0]=nullptr;
   subnode[1]=nullptr;
   subnode[2]=nullptr;
   subnode[3]=nullptr;
 }
Member Function Documentation
void geos::index::quadtree::NodeBase::add (void * item)
Add an item to this node. Ownership of the item is left to caller.
Definition at line 91 of file NodeBase.cpp.
Referenced by geos::index::quadtree::Root::insertContained().
 {
   items.push_back(item);
   //GEOS_DEBUG itemCount++;
   //GEOS_DEBUG System.out.print(itemCount);
 }
vector< void * > & geos::index::quadtree::NodeBase::addAllItems (std::vector< void * > & resultItems) const
Push all node items to the given vector, return the argument.
Definition at line 99 of file NodeBase.cpp.
 {
   // this node may have items as well as subnodes (since items may not
   // be wholely contained in any single subnode
   resultItems.insert(resultItems.end(), items.begin(), items.end());
   for(int i=0; i<4; ++i)
   {
     if ( subnode[i] )
     {
       subnode[i]->addAllItems(resultItems);
     }
   }
   return resultItems;
 }
void geos::index::quadtree::NodeBase::addAllItemsFromOverlapping (const geom::Envelope & searchEnv, std::vector< void * > & resultItems) const virtual
Definition at line 116 of file NodeBase.cpp.
 {
   if (!isSearchMatch(searchEnv))
     return;
   // this node may have items as well as subnodes (since items may not
   // be wholely contained in any single subnode
   resultItems.insert(resultItems.end(), items.begin(), items.end());
   for(int i=0; i<4; ++i)
   {
     if ( subnode[i] )
     {
       subnode[i]->addAllItemsFromOverlapping(searchEnv,
                                              resultItems);
     }
   }
 }
unsigned int geos::index::quadtree::NodeBase::depth () const
Definition at line 139 of file NodeBase.cpp.
 {
   unsigned int maxSubDepth=0;
   for (int i=0; i<4; ++i)
   {
     if (subnode[i] != nullptr)
     {
       unsigned int sqd=subnode[i]->depth();
       if ( sqd > maxSubDepth )
         maxSubDepth=sqd;
     }
   }
   return maxSubDepth + 1;
 }
vector< void * > & geos::index::quadtree::NodeBase::getItems ()
Definition at line 85 of file NodeBase.cpp.
 {
   return items;
 }
unsigned int geos::index::quadtree::NodeBase::getNodeCount () const
Definition at line 169 of file NodeBase.cpp.
 {
   unsigned int subSize=0;
   for(int i=0; i<4; ++i)
   {
     if (subnode[i] != nullptr)
     {
       subSize += subnode[i]->size();
     }
   }
   return subSize + 1;
 }
int geos::index::quadtree::NodeBase::getSubnodeIndex (const geom::Envelope * env, const geom::Coordinate & centre) static
Definition at line 47 of file NodeBase.cpp.
References geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), geos::geom::Coordinate::toString(), geos::geom::Envelope::toString(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   int subnodeIndex=-1;
   if (env->getMinX()>=centre.x) {
     if (env->getMinY()>=centre.y) subnodeIndex=3;
     if (env->getMaxY()<=centre.y) subnodeIndex=1;
   }
   if (env->getMaxX()<=centre.x) {
     if (env->getMinY()>=centre.y) subnodeIndex=2;
     if (env->getMaxY()<=centre.y) subnodeIndex=0;
   }
 #if GEOS_DEBUG
   cerr<<"getSubNodeIndex("<<env->toString()<<", "<<centre.toString()<<") returning "<<subnodeIndex<<endl;
 #endif
   return subnodeIndex;
 }
bool geos::index::quadtree::NodeBase::hasChildren () const inline
Definition at line 131 of file NodeBase.h.
 {
   for (int i = 0; i < 4; i++)
     if (subnode[i]) return true;
   return false;
 }
bool geos::index::quadtree::NodeBase::hasItems () const inline
Definition at line 145 of file NodeBase.h.
 {
   return ! items.empty();
 }
bool geos::index::quadtree::NodeBase::isPrunable () const inline
Definition at line 139 of file NodeBase.h.
 {
   return ! (hasChildren() || hasItems());
 }
virtual bool geos::index::quadtree::NodeBase::isSearchMatch (const geom::Envelope & searchEnv) const protected pure virtual
Implemented in geos::index::quadtree::Node, and geos::index::quadtree::Root.
bool geos::index::quadtree::NodeBase::remove (const geom::Envelope * itemEnv, void * item)
Removes a single item from this subtree.
Parameters
searchEnv the envelope containing the item
item the item to remove
Returns
true if the item was found and removed
Definition at line 232 of file NodeBase.cpp.
 {
   // use envelope to restrict nodes scanned
   if (! isSearchMatch(*itemEnv)) return false;
   bool found = false;
   for (int i = 0; i < 4; ++i)
   {
     if ( subnode[i] )
     {
       found = subnode[i]->remove(itemEnv, item);
       if (found)
       {
         // trim subtree if empty
         if (subnode[i]->isPrunable())
         {
           delete subnode[i];
           subnode[i] = nullptr;
         }
         break;
       }
     }
   }
   // if item was found lower down, don't need to search for it here
   if (found) return found;
   // otherwise, try and remove the item from the list of items
   // in this node
   vector<void*>::iterator foundIter =
     find(items.begin(), items.end(), item);
   if ( foundIter != items.end() ) {
     items.erase(foundIter);
     return true;
   } else {
     return false;
   }
 }
unsigned int geos::index::quadtree::NodeBase::size () const
Definition at line 155 of file NodeBase.cpp.
 {
   unsigned int subSize=0;
   for(int i=0; i<4; i++)
   {
     if (subnode[i] != nullptr)
     {
       subSize += subnode[i]->size();
     }
   }
   return subSize + static_cast<unsigned int>(items.size());
 }
string geos::index::quadtree::NodeBase::toString (void) const virtual
Reimplemented in geos::index::quadtree::Node.
Definition at line 184 of file NodeBase.cpp.
 {
   ostringstream s;
   s<<"ITEMS:"<<items.size()<<endl;
   for (int i=0; i<4; i++)
   {
     s<<"subnode["<<i<<"] ";
     if ( subnode[i] == nullptr ) s<<"NULL";
     else s<<subnode[i]->toString();
     s<<endl;
   }
   return s.str();
 }
void geos::index::quadtree::NodeBase::visit (const geom::Envelope * searchEnv, ItemVisitor & visitor) virtual
Definition at line 200 of file NodeBase.cpp.
Referenced by geos::index::quadtree::Quadtree::query().
 {
   if (! isSearchMatch(*searchEnv)) return;
   // this node may have items as well as subnodes (since items may not
   // be wholely contained in any single subnode
   visitItems(searchEnv, visitor);
   for (int i = 0; i < 4; i++) {
     if (subnode[i] != nullptr) {
       subnode[i]->visit(searchEnv, visitor);
     }
   }
 }
void geos::index::quadtree::NodeBase::visitItems (const geom::Envelope * searchEnv, ItemVisitor & visitor) private
Definition at line 217 of file NodeBase.cpp.
References geos::ignore_unused_variable_warning(), and geos::index::ItemVisitor::visitItem().
 {
     ::geos::ignore_unused_variable_warning(searchEnv);
   // would be nice to filter items based on search envelope, but can't
   // until they contain an envelope
   for (vector<void*>::iterator i=items.begin(), e=items.end();
       i!=e; i++)
   {
     visitor.visitItem(*i);
   }
 }
Member Data Documentation
std::vector<void*> geos::index::quadtree::NodeBase::items protected
Actual items are NOT owned by this class.
Definition at line 110 of file NodeBase.h.
Node* geos::index::quadtree::NodeBase::subnode[4] protected
subquads are numbered as follows:
 2 | 3
 --+--
 0 | 1
Nodes are owned by this class
Definition at line 122 of file NodeBase.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/quadtree/NodeBase.h
/home/vicky/potree/geos/vicky/src/index/quadtree/NodeBase.cpp