GEOS: geos::noding::OrientedCoordinateArray Class Reference
geos::noding::OrientedCoordinateArray Class Reference
Allows comparing geom::CoordinateSequences in an orientation-independent way.
#include <OrientedCoordinateArray.h>
Public Member Functions
OrientedCoordinateArray (const geom::CoordinateSequence &pts)
int compareTo (const OrientedCoordinateArray &o1) const
Compares two OrientedCoordinateArrays for their relative order.
Static Private Member Functions
static int compareOriented (const geom::CoordinateSequence &pts1, bool orientation1, const geom::CoordinateSequence &pts2, bool orientation2)
static bool orientation (const geom::CoordinateSequence &pts)
Private Attributes
const geom::CoordinateSequence * pts
Externally owned.
bool orientationVar
Detailed Description
Allows comparing geom::CoordinateSequences in an orientation-independent way.
Definition at line 46 of file OrientedCoordinateArray.h.
Constructor & Destructor Documentation
geos::noding::OrientedCoordinateArray::OrientedCoordinateArray (const geom::CoordinateSequence & pts) inline
Creates a new OrientedCoordinateArray for the given geom::CoordinateSequence.
Parameters
pts the coordinates to orient
Definition at line 56 of file OrientedCoordinateArray.h.
     :
     pts(&pts),
     orientationVar(orientation(pts))
   {
   }
Member Function Documentation
int geos::noding::OrientedCoordinateArray::compareOriented (const geom::CoordinateSequence & pts1, bool orientation1, const geom::CoordinateSequence & pts2, bool orientation2) static private
Definition at line 70 of file OrientedCoordinateArray.cpp.
References geos::geom::CoordinateSequence::size().
 {
     int dir1 = orientation1 ? 1 : -1;
     int dir2 = orientation2 ? 1 : -1;
     auto limit1 = orientation1 ? pts1.size() : -1;
     auto limit2 = orientation2 ? pts2.size() : -1;
     auto i1 = orientation1 ? 0 : pts1.size() - 1;
     auto i2 = orientation2 ? 0 : pts2.size() - 1;
     //int comp = 0; // unused, but is in JTS ...
     while (true) {
       int compPt = pts1[i1].compareTo(pts2[i2]);
       if (compPt != 0)
         return compPt;
       i1 += dir1;
       i2 += dir2;
       bool done1 = i1 == limit1;
       bool done2 = i2 == limit2;
       if (done1 && ! done2) return -1;
       if (! done1 && done2) return 1;
       if (done1 && done2) return 0;
     }
 }
int geos::noding::OrientedCoordinateArray::compareTo (const OrientedCoordinateArray & o1) const
Compares two OrientedCoordinateArrays for their relative order.
Returns
-1 this one is smaller
0 the two objects are equal
1 this one is greater
In JTS, this is used automatically by ordered lists. In C++, operator< would be used instead....
Definition at line 47 of file OrientedCoordinateArray.cpp.
References orientation(), orientationVar, and pts.
Referenced by geos::noding::operator<().
 {
   int comp = compareOriented(*pts, orientationVar,
                                *oca.pts, oca.orientationVar);
 #if 0 // MD - testing only
     int oldComp = SegmentStringDissolver.ptsComp.compare(pts, oca.pts);
     if ((oldComp == 0 || comp == 0) && oldComp != comp) {
       System.out.println("bidir mismatch");
       boolean orient1 = orientation(pts);
       boolean orient2 = orientation(oca.pts);
       int comp2 = compareOriented(pts, orientation,
                                oca.pts, oca.orientation);
       int oldComp2 = SegmentStringDissolver.ptsComp.compare(pts, oca.pts);
     }
 #endif
   return comp;
 }
bool geos::noding::OrientedCoordinateArray::orientation (const geom::CoordinateSequence & pts) static private
Computes the canonical orientation for a coordinate array.
Parameters
pts the array to test
Returns
true if the points are oriented forwards
false</code if the points are oriented in reverse
Definition at line 41 of file OrientedCoordinateArray.cpp.
References geos::geom::CoordinateSequence::increasingDirection().
Referenced by compareTo().
 {
   return CoordinateSequence::increasingDirection(pts) == 1;
 }
Member Data Documentation
bool geos::noding::OrientedCoordinateArray::orientationVar private
Definition at line 97 of file OrientedCoordinateArray.h.
Referenced by compareTo().
const geom::CoordinateSequence* geos::noding::OrientedCoordinateArray::pts private
Externally owned.
Definition at line 95 of file OrientedCoordinateArray.h.
Referenced by compareTo().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/OrientedCoordinateArray.h
/home/vicky/potree/geos/vicky/src/noding/OrientedCoordinateArray.cpp