GEOS: geos::noding::NodingValidator Class Reference
geos::noding::NodingValidator Class Reference
#include <NodingValidator.h>
Public Member Functions
NodingValidator (const std::vector< SegmentString * > &newSegStrings)
~NodingValidator ()
void checkValid ()
Private Member Functions
void checkCollapses () const
void checkCollapses (const SegmentString &ss) const
void checkCollapse (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &p2) const
void checkInteriorIntersections ()
void checkInteriorIntersections (const SegmentString &ss0, const SegmentString &ss1)
void checkInteriorIntersections (const SegmentString &e0, unsigned int segIndex0, const SegmentString &e1, unsigned int segIndex1)
void checkEndPtVertexIntersections () const
void checkEndPtVertexIntersections (const geom::Coordinate &testPt, const std::vector< SegmentString * > &segStrings) const
bool hasInteriorIntersection (const algorithm::LineIntersector &aLi, const geom::Coordinate &p0, const geom::Coordinate &p1) const
NodingValidator (const NodingValidator &other)=delete
NodingValidator & operator= (const NodingValidator &rhs)=delete
Private Attributes
algorithm::LineIntersector li
const std::vector< SegmentString * > & segStrings
Detailed Description
Validates that a collection of SegmentStrings is correctly noded. Throws a TopologyException if a noding error is found.
Last port: noding/NodingValidator.java rev. 1.6 (JTS-1.7)
Definition at line 48 of file NodingValidator.h.
Constructor & Destructor Documentation
geos::noding::NodingValidator::NodingValidator (const NodingValidator & other) private delete
geos::noding::NodingValidator::NodingValidator (const std::vector< SegmentString * > & newSegStrings) inline
Definition at line 99 of file NodingValidator.h.
                                                                  :
     segStrings(newSegStrings)
   {}
geos::noding::NodingValidator::~NodingValidator () inline
Definition at line 103 of file NodingValidator.h.
 {}
Member Function Documentation
void geos::noding::NodingValidator::checkCollapse (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & p2) const private
Definition at line 73 of file NodingValidator.cpp.
References geos::geom::Coordinate::equals2D(), and geos::geom::Coordinate::toString().
 {
   if (p0.equals2D(p2))
     throw util::TopologyException("found non-noded collapse at " +
       p0.toString() + ", " +
       p1.toString() + ", " +
       p2.toString());
 }
void geos::noding::NodingValidator::checkCollapses () const private
Checks if a segment string contains a segment pattern a-b-a (which implies a self-intersection)
Definition at line 48 of file NodingValidator.cpp.
 {
   for (SegmentString::NonConstVect::const_iterator
     it = segStrings.begin(), itEnd = segStrings.end();
     it != itEnd;
     ++it)
   {
     const SegmentString* ss = *it;
     checkCollapses(*ss);
   }
 }
void geos::noding::NodingValidator::checkCollapses (const SegmentString & ss) const private
Definition at line 62 of file NodingValidator.cpp.
References geos::noding::SegmentString::getCoordinates(), and geos::geom::CoordinateSequence::getSize().
 {
   const CoordinateSequence& pts = *(ss.getCoordinates());
   for (unsigned int i=0, n = static_cast<unsigned int>(pts.getSize() - 2); i < n; ++i)
   {
     checkCollapse(pts[i], pts[i + 1], pts[i + 2]);
   }
 }
void geos::noding::NodingValidator::checkEndPtVertexIntersections () const private
Checks for intersections between an endpoint of a segment string and an interior vertex of another segment string
Definition at line 148 of file NodingValidator.cpp.
References geos::noding::SegmentString::getCoordinates(), and geos::geom::CoordinateSequence::size().
 {
   for (SegmentString::NonConstVect::const_iterator
     it = segStrings.begin(), itEnd = segStrings.end();
     it != itEnd;
     ++it)
   {
     const SegmentString* ss = *it;
     const CoordinateSequence& pts = *(ss->getCoordinates());
     checkEndPtVertexIntersections(pts[0], segStrings);
     checkEndPtVertexIntersections(pts[pts.size() - 1], segStrings);
   }
 }
void geos::noding::NodingValidator::checkEndPtVertexIntersections (const geom::Coordinate & testPt, const std::vector< SegmentString * > & segStrings) const private
void geos::noding::NodingValidator::checkInteriorIntersections () private
Checks all pairs of segments for intersections at an interior point of a segment
Definition at line 85 of file NodingValidator.cpp.
 {
   for (SegmentString::NonConstVect::const_iterator
     it = segStrings.begin(), itEnd = segStrings.end();
     it != itEnd;
     ++it)
   {
     SegmentString* ss0 = *it;
     for (SegmentString::NonConstVect::const_iterator
       j = segStrings.begin(), jEnd = segStrings.end();
       j != jEnd; ++j)
     {
             const SegmentString* ss1 = *j;
       checkInteriorIntersections(*ss0, *ss1);
     }
   }
 }
void geos::noding::NodingValidator::checkInteriorIntersections (const SegmentString & ss0, const SegmentString & ss1) private
Definition at line 106 of file NodingValidator.cpp.
References geos::noding::SegmentString::getCoordinates(), and geos::geom::CoordinateSequence::size().
 {
   const CoordinateSequence& pts0 = *(ss0.getCoordinates());
   const CoordinateSequence& pts1 = *(ss1.getCoordinates());
   for (unsigned int i0=0, n0 = static_cast<unsigned int>(pts0.size()); i0 < n0 - 1; i0++) {
     for (unsigned int i1=0, n1 = static_cast<unsigned int>(pts1.size()); i1 < n1 - 1; i1++) {
       checkInteriorIntersections(ss0, i0, ss1, i1);
     }
   }
 }
void geos::noding::NodingValidator::checkInteriorIntersections (const SegmentString & e0, unsigned int segIndex0, const SegmentString & e1, unsigned int segIndex1) private
Definition at line 121 of file NodingValidator.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::noding::SegmentString::getCoordinates(), and geos::geom::Coordinate::toString().
 {
   if (&e0 == &e1 && segIndex0 == segIndex1) return;
   const Coordinate& p00 = e0.getCoordinates()->getAt(segIndex0);
   const Coordinate& p01 = e0.getCoordinates()->getAt(segIndex0 + 1);
   const Coordinate& p10 = e1.getCoordinates()->getAt(segIndex1);
   const Coordinate& p11 = e1.getCoordinates()->getAt(segIndex1 + 1);
   li.computeIntersection(p00, p01, p10, p11);
   if (li.hasIntersection()) {
     if (li.isProper()
       || hasInteriorIntersection(li, p00, p01)
       || hasInteriorIntersection(li, p10, p11))
     {
       throw util::TopologyException(
         "found non-noded intersection at "
         + p00.toString() + "-" + p01.toString()
         + " and "
         + p10.toString() + "-" + p11.toString());
     }
   }
 }
void geos::noding::NodingValidator::checkValid ()
Definition at line 39 of file NodingValidator.cpp.
Referenced by geos::noding::snapround::MCIndexSnapRounder::checkCorrectness().
 {
   checkEndPtVertexIntersections();
   checkInteriorIntersections();
   checkCollapses();
 }
bool geos::noding::NodingValidator::hasInteriorIntersection (const algorithm::LineIntersector & aLi, const geom::Coordinate & p0, const geom::Coordinate & p1) const private
Returns
true if there is an intersection point which is not an endpoint of the segment p0-p1
Definition at line 193 of file NodingValidator.cpp.
References geos::algorithm::LineIntersector::getIntersection(), and geos::algorithm::LineIntersector::getIntersectionNum().
 {
   for (int i=0, n=aLi.getIntersectionNum(); i<n; i++)
   {
     const Coordinate &intPt=aLi.getIntersection(i);
     if (!(intPt==p0 || intPt==p1))
       return true;
   }
   return false;
 }
NodingValidator& geos::noding::NodingValidator::operator= (const NodingValidator & rhs) private delete
Member Data Documentation
algorithm::LineIntersector geos::noding::NodingValidator::li private
Definition at line 50 of file NodingValidator.h.
const std::vector<SegmentString*>& geos::noding::NodingValidator::segStrings private
Definition at line 51 of file NodingValidator.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/NodingValidator.h
/home/vicky/potree/geos/vicky/src/noding/NodingValidator.cpp