GEOS: geos::geom::CoordinateArraySequence Class Reference
geos::geom::CoordinateArraySequence Class Reference abstract
The default implementation of CoordinateSequence.
#include <CoordinateArraySequence.h>
Public Types
enum { X, Y, Z, M }
Standard ordinate index values.
typedef std::unique_ptr< CoordinateSequence > Ptr
Public Member Functions
CoordinateArraySequence (const CoordinateArraySequence &cl)
CoordinateArraySequence (const CoordinateSequence &cl)
CoordinateSequence * clone () const override
Returns a deep copy of this collection.
const Coordinate & getAt (std::size_t pos) const override
Returns a read-only reference to Coordinate at position i.
void getAt (std::size_t i, Coordinate &c) const override
Copy Coordinate at position i to Coordinate c.
size_t getSize () const override
Returns the number of Coordinates (actual or otherwise, as this implementation may not store its data in Coordinate objects).
const std::vector< Coordinate > * toVector () const override
Returns a read-only vector with the Coordinates in this collection.
void toVector (std::vector< Coordinate > &) const override
Pushes all Coordinates of this sequence onto the provided vector.
CoordinateArraySequence ()
Construct an empty sequence.
CoordinateArraySequence (std::vector< Coordinate > *coords, std::size_t dimension=0)
Construct sequence taking ownership of given Coordinate vector.
CoordinateArraySequence (std::size_t n, std::size_t dimension=0)
Construct sequence allocating space for n coordinates.
~CoordinateArraySequence () override
bool isEmpty () const override
Returns true it list contains no coordinates.
bool empty () const
void clear ()
Reset this CoordinateArraySequence to the empty state.
void add (const Coordinate &c) override
Add a Coordinate to the list.
void add (const Coordinate &c, bool allowRepeated) override
Add a coordinate.
void add (std::size_t i, const Coordinate &coord, bool allowRepeated) override
Inserts the specified coordinate at the specified position in this list.
void setAt (const Coordinate &c, std::size_t pos) override
Get a reference to Coordinate at position pos.
void deleteAt (std::size_t pos) override
Delete Coordinate at position pos (list will shrink).
std::string toString () const override
Get a string rapresentation of CoordinateSequence.
void setPoints (const std::vector< Coordinate > &v) override
Substitute Coordinate list with a copy of the given vector.
double getOrdinate (std::size_t index, size_t ordinateIndex) const override
void setOrdinate (std::size_t index, std::size_t ordinateIndex, double value) override
void expandEnvelope (Envelope &env) const override
std::size_t getDimension () const override
void apply_rw (const CoordinateFilter *filter) override
void apply_ro (CoordinateFilter *filter) const override
CoordinateSequence & removeRepeatedPoints () override
Remove consecutive equal Coordinates from the sequence.
const Coordinate & back () const
Return last Coordinate in the sequence.
const Coordinate & front () const
Return first Coordinate in the sequence.
const Coordinate & operator[] (std::size_t i) const
size_t size () const
void add (const std::vector< Coordinate > *vc, bool allowRepeated)
Add an array of coordinates.
void add (const CoordinateSequence *cl, bool allowRepeated, bool direction)
Add an array of coordinates.
bool hasRepeatedPoints () const
Returns true if contains any two consecutive points.
const Coordinate * minCoordinate () const
Returns lower-left Coordinate in list.
virtual double getOrdinate (std::size_t index, std::size_t ordinateIndex) const =0
virtual double getX (std::size_t index) const
virtual double getY (std::size_t index) const
template<class T >
void applyCoordinateFilter (T &f)
Apply a fiter to each Coordinate of this sequence. The filter is expected to provide a .filter(Coordinate&) method.
Static Public Member Functions
static bool hasRepeatedPoints (const CoordinateSequence *cl)
Returns true if given CoordinateSequence contains any two consecutive Coordinate.
static const Coordinate * minCoordinate (CoordinateSequence *cl)
Returns lower-left Coordinate in given CoordinateSequence. This is actually the Coordinate with lower X (and Y if needed) ordinate.
static CoordinateSequence * removeRepeatedPoints (const CoordinateSequence *cl)
Returns a new CoordinateSequence being a copy of the input with any consecutive equal Coordinate removed.
static CoordinateSequence * atLeastNCoordinatesOrNothing (std::size_t n, CoordinateSequence *c)
Returns either the given CoordinateSequence if its length is greater than the given amount, or an empty CoordinateSequence.
static int indexOf (const Coordinate *coordinate, const CoordinateSequence *cl)
Return position of a Coordinate, or -1 if not found.
static bool equals (const CoordinateSequence *cl1, const CoordinateSequence *cl2)
Returns true if the two arrays are identical, both null, or pointwise equal.
static void scroll (CoordinateSequence *cl, const Coordinate *firstCoordinate)
Scroll given CoordinateSequence so to start with given Coordinate.
static int increasingDirection (const CoordinateSequence &pts)
Determines which orientation of the Coordinate array is (overall) increasing.
static void reverse (CoordinateSequence *cl)
Reverse Coordinate order in given CoordinateSequence.
Private Attributes
std::vector< Coordinate > * vect
std::size_t dimension
Detailed Description
The default implementation of CoordinateSequence.
Definition at line 37 of file CoordinateArraySequence.h.
Member Typedef Documentation
typedef std::unique_ptr<CoordinateSequence> geos::geom::CoordinateSequence::Ptr inherited
Definition at line 69 of file CoordinateSequence.h.
Member Enumeration Documentation
anonymous enum inherited
Standard ordinate index values.
Enumerator
X
Y
Z
M
Definition at line 302 of file CoordinateSequence.h.
 { X,Y,Z,M };
Constructor & Destructor Documentation
geos::geom::CoordinateArraySequence::CoordinateArraySequence (const CoordinateArraySequence & cl)
Definition at line 53 of file CoordinateArraySequence.cpp.
   :
   CoordinateSequence(c),
   vect(new vector<Coordinate>(*(c.vect))),
         dimension(c.getDimension())
 {
 }
geos::geom::CoordinateArraySequence::CoordinateArraySequence (const CoordinateSequence & cl)
Definition at line 62 of file CoordinateArraySequence.cpp.
References geos::geom::CoordinateSequence::getAt(), and vect.
   :
   CoordinateSequence(c),
   vect(new vector<Coordinate>(c.size())),
   dimension(c.getDimension())
 {
   for (size_t i = 0, n = vect->size(); i < n; ++i) {
       (*vect)[i] = c.getAt(i);
   }
 }
geos::geom::CoordinateArraySequence::CoordinateArraySequence ()
Construct an empty sequence.
Definition at line 33 of file CoordinateArraySequence.cpp.
References dimension, and vect.
Referenced by clone().
                                                 :
   vect(new vector<Coordinate>()),
         dimension(3)
 {
 }
geos::geom::CoordinateArraySequence::CoordinateArraySequence (std::vector< Coordinate > * coords, std::size_t dimension = 0)
Construct sequence taking ownership of given Coordinate vector.
geos::geom::CoordinateArraySequence::CoordinateArraySequence (std::size_t n, std::size_t dimension = 0)
Construct sequence allocating space for n coordinates.
geos::geom::CoordinateArraySequence::~CoordinateArraySequence () override
Definition at line 204 of file CoordinateArraySequence.cpp.
References vect.
 {
   delete vect;
 }
Member Function Documentation
void geos::geom::CoordinateArraySequence::add (const Coordinate & c) override virtual
Add a Coordinate to the list.
Implements geos::geom::CoordinateSequence.
Definition at line 117 of file CoordinateArraySequence.cpp.
References vect.
Referenced by add(), geos::operation::buffer::OffsetSegmentString::addPt(), geos::operation::buffer::OffsetSegmentString::closeRing(), and geos::linearref::ExtractLineByLocation::computeLine().
 {
   vect->push_back(c);
 }
void geos::geom::CoordinateArraySequence::add (const Coordinate & c, bool allowRepeated) override virtual
Add a coordinate.
Parameters
c The coordinate to add
allowRepeated if set to false, repeated coordinates are collapsed
Returns
true (as by general collection contract)
Reimplemented from geos::geom::CoordinateSequence.
Definition at line 123 of file CoordinateArraySequence.cpp.
References add(), geos::geom::Coordinate::equals2D(), getAt(), geos::geom::CoordinateSequence::size(), and vect.
 {
   if (!allowRepeated && ! vect->empty() )
   {
     const Coordinate& last=vect->back();
     if (last.equals2D(c)) return;
   }
   vect->push_back(c);
 }
void geos::geom::CoordinateArraySequence::add (std::size_t i, const Coordinate & coord, bool allowRepeated) override virtual
Inserts the specified coordinate at the specified position in this list.
Parameters
i the position at which to insert
coord the coordinate to insert
allowRepeated if set to false, repeated coordinates are collapsed
NOTE: this is a CoordinateList interface in JTS
Implements geos::geom::CoordinateSequence.
void geos::geom::CoordinateSequence::add (const std::vector< Coordinate > * vc, bool allowRepeated) inherited
Add an array of coordinates.
Parameters
vc The coordinates
allowRepeated if set to false, repeated coordinates are collapsed
Returns
true (as by general collection contract)
Definition at line 191 of file CoordinateSequence.cpp.
Referenced by geos::linearref::LinearGeometryBuilder::add(), geos::operation::polygonize::EdgeRing::addEdge(), geos::geomgraph::EdgeRing::addPoints(), geos::operation::linemerge::EdgeString::getCoordinates(), geos::io::WKTReader::getCoordinates(), geos::algorithm::MinimumDiameter::getDiameter(), geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), geos::algorithm::MinimumDiameter::getSupportingSegment(), geos::operation::distance::DistanceOp::nearestPoints(), geos::geom::Polygon::normalize(), geos::noding::SegmentIntersectionDetector::processIntersections(), geos::io::WKTReader::readMultiPointText(), geos::operation::intersection::RectangleIntersectionBuilder::reconnect(), geos::geom::GeometryFactory::toGeometry(), and geos::geom::LineSegment::toGeometry().
 {
   assert(vc);
   for(size_t i=0; i<vc->size(); ++i)
   {
     add((*vc)[i], allowRepeated);
   }
 }
void geos::geom::CoordinateSequence::add (const CoordinateSequence * cl, bool allowRepeated, bool direction) inherited
Add an array of coordinates.
Parameters
cl The coordinates
allowRepeated if set to false, repeated coordinates are collapsed
direction if false, the array is added in reverse order
Returns
true (as by general collection contract)
Definition at line 225 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   // FIXME:  don't rely on negative values for 'j' (the reverse case)
   const int npts = static_cast<int>(cl->getSize());
   if (direction) {
     for (int i=0; i<npts; i++) {
       add(cl->getAt(i), allowRepeated);
     }
   } else {
     for (int j=npts-1; j>=0; j--) {
       add(cl->getAt(j), allowRepeated);
     }
   }
 }
void geos::geom::CoordinateArraySequence::apply_ro (CoordinateFilter * filter) const override virtual
Implements geos::geom::CoordinateSequence.
Definition at line 268 of file CoordinateArraySequence.cpp.
References geos::geom::CoordinateFilter::filter_ro(), and vect.
 {
   for (vector<Coordinate>::const_iterator i=vect->begin(), e=vect->end(); i!=e; ++i)
   {
     filter->filter_ro(&(*i));
   }
 }
void geos::geom::CoordinateArraySequence::apply_rw (const CoordinateFilter * filter) override virtual
Implements geos::geom::CoordinateSequence.
Definition at line 258 of file CoordinateArraySequence.cpp.
References dimension, geos::geom::CoordinateFilter::filter_rw(), and vect.
 {
   for (vector<Coordinate>::iterator i=vect->begin(), e=vect->end(); i!=e; ++i)
   {
     filter->filter_rw(&(*i));
   }
   dimension = 0; // re-check (see http://trac.osgeo.org/geos/ticket/435)
 }
template<class T > void geos::geom::CoordinateSequence::applyCoordinateFilter (T & f) inline inherited
Apply a fiter to each Coordinate of this sequence. The filter is expected to provide a .filter(Coordinate&) method.
TODO: accept a Functor instead, will be more flexible. actually, define iterators on Geometry
Definition at line 372 of file CoordinateSequence.h.
References GEOS_DLL, geos::geom::operator!=(), geos::geom::operator<<(), and geos::geom::operator==().
   {
     Coordinate c;
     for(std::size_t i=0, n=size(); i<n; ++i)
     {
       getAt(i, c);
       f.filter(c);
       setAt(c, i);
     }
   }
CoordinateSequence * geos::geom::CoordinateSequence::atLeastNCoordinatesOrNothing (std::size_t n, CoordinateSequence * c) static inherited
Returns either the given CoordinateSequence if its length is greater than the given amount, or an empty CoordinateSequence.
Definition at line 55 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::getSize().
 {
   if ( c->getSize() >= n )
   {
     return c;
   }
   else
   {
     // FIXME: return NULL rather then empty coordinate array
     return CoordinateArraySequenceFactory::instance()->create();
   }
 }
const Coordinate& geos::geom::CoordinateSequence::back () const inline inherited
Return last Coordinate in the sequence.
Definition at line 88 of file CoordinateSequence.h.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::operation::buffer::OffsetSegmentString::closeRing(), and geos::operation::buffer::OffsetSegmentString::isRedundant().
{
     return getAt(size()-1);
   }
void geos::geom::CoordinateArraySequence::clear () inline
Reset this CoordinateArraySequence to the empty state.
Definition at line 78 of file CoordinateArraySequence.h.
Referenced by geos::operation::buffer::OffsetSegmentString::reset().
 { vect->clear(); }
CoordinateSequence * geos::geom::CoordinateArraySequence::clone () const override virtual
Returns a deep copy of this collection.
Implements geos::geom::CoordinateSequence.
Definition at line 75 of file CoordinateArraySequence.cpp.
References CoordinateArraySequence().
 {
   return new CoordinateArraySequence(*this);
 }
void geos::geom::CoordinateArraySequence::deleteAt (std::size_t pos) override virtual
Delete Coordinate at position pos (list will shrink).
Implements geos::geom::CoordinateSequence.
Definition at line 181 of file CoordinateArraySequence.cpp.
References vect.
 {
   vect->erase(vect->begin()+pos);
 }
bool geos::geom::CoordinateArraySequence::empty () const inline
Definition at line 75 of file CoordinateArraySequence.h.
 { return vect->empty(); }
bool geos::geom::CoordinateSequence::equals (const CoordinateSequence * cl1, const CoordinateSequence * cl2) static inherited
Returns true if the two arrays are identical, both null, or pointwise equal.
Definition at line 174 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   // FIXME: use std::equals()
   if (cl1==cl2) return true;
   if (cl1==nullptr||cl2==nullptr) return false;
   size_t npts1=cl1->getSize();
   if (npts1!=cl2->getSize()) return false;
   for (size_t i=0; i<npts1; i++) {
     if (!(cl1->getAt(i)==cl2->getAt(i))) return false;
   }
   return true;
 }
void geos::geom::CoordinateArraySequence::expandEnvelope (Envelope & env) const override virtual
Expands the given Envelope to include the coordinates in the sequence. Allows implementing classes to optimize access to coordinate values.
Parameters
env the envelope to expand
Reimplemented from geos::geom::CoordinateSequence.
Definition at line 210 of file CoordinateArraySequence.cpp.
References geos::geom::Envelope::expandToInclude(), and vect.
 {
   for (size_t i=0, n=vect->size(); i<n; ++i)
     env.expandToInclude((*vect)[i]);
 }
const Coordinate& geos::geom::CoordinateSequence::front () const inline inherited
Return first Coordinate in the sequence.
Definition at line 93 of file CoordinateSequence.h.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), and geos::operation::buffer::OffsetSegmentString::closeRing().
{
     return getAt(0);
   }
const Coordinate& geos::geom::CoordinateArraySequence::getAt (std::size_t i) const override virtual
Returns a read-only reference to Coordinate at position i.
Whether or not the Coordinate returned is the actual underlying Coordinate or merely a copy depends on the implementation.
Implements geos::geom::CoordinateSequence.
Referenced by add(), and getSize().
void geos::geom::CoordinateArraySequence::getAt (std::size_t i, Coordinate & c) const override virtual
Copy Coordinate at position i to Coordinate c.
Implements geos::geom::CoordinateSequence.
std::size_t geos::geom::CoordinateArraySequence::getDimension () const override virtual
Returns the dimension (number of ordinates in each coordinate) for this sequence.
Returns
the dimension of the sequence.
Implements geos::geom::CoordinateSequence.
Definition at line 93 of file CoordinateArraySequence.cpp.
References dimension, and vect.
 {
     if( dimension != 0 )
         return dimension;
     if( vect->size() == 0 )
         return 3;
     if( ISNAN((*vect)[0].z) )
         dimension = 2;
     else
         dimension = 3;
     return dimension;
 }
double geos::geom::CoordinateArraySequence::getOrdinate (std::size_t index, size_t ordinateIndex) const override
Definition at line 217 of file CoordinateArraySequence.cpp.
References vect, geos::geom::CoordinateSequence::X, geos::geom::CoordinateSequence::Y, and geos::geom::CoordinateSequence::Z.
 {
   switch (ordinateIndex)
   {
     case CoordinateSequence::X:
       return (*vect)[index].x;
     case CoordinateSequence::Y:
       return (*vect)[index].y;
     case CoordinateSequence::Z:
       return (*vect)[index].z;
     default:
       return DoubleNotANumber;
   }
 }
virtual double geos::geom::CoordinateSequence::getOrdinate (std::size_t index, std::size_t ordinateIndex) const pure virtual inherited
Returns the ordinate of a coordinate in this sequence. Ordinate indices 0 and 1 are assumed to be X and Y. Ordinates indices greater than 1 have user-defined semantics (for instance, they may contain other dimensions or measure values).
Parameters
index the coordinate index in the sequence
ordinateIndex the ordinate index in the coordinate (in range [0, dimension-1])
Referenced by GEOSCoordSeq_getOrdinate_r(), and geos::io::WKBWriter::writeCoordinate().
size_t geos::geom::CoordinateArraySequence::getSize () const override virtual
Returns the number of Coordinates (actual or otherwise, as this implementation may not store its data in Coordinate objects).
Implements geos::geom::CoordinateSequence.
Definition at line 157 of file CoordinateArraySequence.cpp.
References getAt(), and vect.
Referenced by toString().
 {
   return vect->size();
 }
virtual double geos::geom::CoordinateSequence::getX (std::size_t index) const inline virtual inherited
Returns ordinate X (0) of the specified coordinate.
Parameters
index
Returns
the value of the X ordinate in the index'th coordinate
Definition at line 330 of file CoordinateSequence.h.
Referenced by geos::operation::distance::FacetSequence::computeEnvelope(), geos::geom::Polygon::isRectangle(), geos::io::WKTWriter::toLineString(), and geos::io::WKBWriter::writeCoordinate().
 { return getOrdinate(index, X); }
virtual double geos::geom::CoordinateSequence::getY (std::size_t index) const inline virtual inherited
Returns ordinate Y (1) of the specified coordinate.
Parameters
index
Returns
the value of the Y ordinate in the index'th coordinate
Definition at line 338 of file CoordinateSequence.h.
Referenced by geos::operation::distance::FacetSequence::computeEnvelope(), geos::geom::Polygon::isRectangle(), geos::io::WKTWriter::toLineString(), and geos::io::WKBWriter::writeCoordinate().
 { return getOrdinate(index, Y); }
bool geos::geom::CoordinateSequence::hasRepeatedPoints () const inherited
Returns true if contains any two consecutive points.
Definition at line 39 of file CoordinateSequence.cpp.
 {
     const std::size_t size=getSize();
   for(std::size_t i=1; i<size; i++) {
     if (getAt(i-1)==getAt(i)) {
       return true;
     }
   }
   return false;
 }
bool geos::geom::CoordinateSequence::hasRepeatedPoints (const CoordinateSequence * cl) static inherited
Returns true if given CoordinateSequence contains any two consecutive Coordinate.
Definition at line 71 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   const std::size_t size=cl->getSize();
   for(std::size_t i=1;i<size; i++) {
     if (cl->getAt(i-1)==cl->getAt(i)) {
       return true;
     }
   }
   return false;
 }
int geos::geom::CoordinateSequence::increasingDirection (const CoordinateSequence & pts) static inherited
Determines which orientation of the Coordinate array is (overall) increasing.
In other words, determines which end of the array is "smaller" (using the standard ordering on Coordinate). Returns an integer indicating the increasing direction. If the sequence is a palindrome, it is defined to be oriented in a positive direction.
Parameters
pts the array of Coordinates to test
Returns
1 if the array is smaller at the start or is a palindrome, -1 if smaller at the end
NOTE: this method is found in CoordinateArrays class for JTS
Definition at line 145 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::size().
Referenced by geos::noding::OrientedCoordinateArray::orientation().
 {
   size_t ptsize = pts.size();
   for (size_t i=0, n=ptsize/2; i<n; ++i)
   {
     size_t j = ptsize - 1 - i;
     // skip equal points on both ends
     int comp = pts[i].compareTo(pts[j]);
     if (comp != 0) return comp;
   }
   // array must be a palindrome - defined to be in positive direction
   return 1;
 }
int geos::geom::CoordinateSequence::indexOf (const Coordinate * coordinate, const CoordinateSequence * cl) static inherited
Return position of a Coordinate, or -1 if not found.
FIXME: return std::size_t, using numeric_limits<std::size_t>::max as 'not found' value.
Definition at line 109 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   size_t size=cl->getSize();
   for (size_t i=0; i<size; ++i)
   {
     if ((*coordinate)==cl->getAt(i))
     {
       return static_cast<int>(i); // FIXME: what if we overflow the int ?
     }
   }
   return -1;
 }
bool geos::geom::CoordinateArraySequence::isEmpty () const inline override virtual
Returns true it list contains no coordinates.
Implements geos::geom::CoordinateSequence.
Definition at line 73 of file CoordinateArraySequence.h.
 { return empty(); }
const Coordinate * geos::geom::CoordinateSequence::minCoordinate () const inherited
Returns lower-left Coordinate in list.
Definition at line 83 of file CoordinateSequence.cpp.
References geos::geom::Coordinate::compareTo().
Referenced by geos::geom::Polygon::normalize().
 {
   const Coordinate* minCoord=nullptr;
   const std::size_t size=getSize();
   for(std::size_t i=0; i<size; i++) {
     if(minCoord==nullptr || minCoord->compareTo(getAt(i))>0) {
       minCoord=&getAt(i);
     }
   }
   return minCoord;
 }
const Coordinate * geos::geom::CoordinateSequence::minCoordinate (CoordinateSequence * cl) static inherited
Returns lower-left Coordinate in given CoordinateSequence. This is actually the Coordinate with lower X (and Y if needed) ordinate.
Definition at line 96 of file CoordinateSequence.cpp.
References geos::geom::Coordinate::compareTo(), geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   const Coordinate* minCoord=nullptr;
   const std::size_t size=cl->getSize();
   for(std::size_t i=0;i<size; i++) {
     if(minCoord==nullptr || minCoord->compareTo(cl->getAt(i))>0) {
       minCoord=&(cl->getAt(i));
     }
   }
   return minCoord;
 }
const Coordinate& geos::geom::CoordinateSequence::operator[] (std::size_t i) const inline inherited
Definition at line 97 of file CoordinateSequence.h.
{
     return getAt(i);
   }
CoordinateSequence & geos::geom::CoordinateArraySequence::removeRepeatedPoints () override virtual
Remove consecutive equal Coordinates from the sequence.
Equality test is 2D based. Returns a reference to self.
Implements geos::geom::CoordinateSequence.
Definition at line 277 of file CoordinateArraySequence.cpp.
References vect.
 {
   // We use == operator, which is 2D only
   vector<Coordinate>::iterator new_end = \
     std::unique(vect->begin(), vect->end());
   vect->erase(new_end, vect->end());
   return *this;
 }
CoordinateSequence * geos::geom::CoordinateSequence::removeRepeatedPoints (const CoordinateSequence * cl) static inherited
Returns a new CoordinateSequence being a copy of the input with any consecutive equal Coordinate removed.
Equality test is 2D based
Ownership of returned object goes to the caller.
Definition at line 245 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::toVector().
Referenced by geos::noding::ScaledNoder::scale(), and geos::triangulate::DelaunayTriangulationBuilder::unique().
 {
 #if PROFILE
   static Profile *prof= profiler->get("CoordinateSequence::removeRepeatedPoints()");
   prof->start();
 #endif
   const vector<Coordinate> *v=cl->toVector();
   vector<Coordinate> *nv=new vector<Coordinate>;
   nv->reserve(v->size());
   unique_copy(v->begin(), v->end(), back_inserter(*nv));
   CoordinateSequence* ret=CoordinateArraySequenceFactory::instance()->create(nv);
 #if PROFILE
   prof->stop();
 #endif
   return ret;
 }
void geos::geom::CoordinateSequence::reverse (CoordinateSequence * cl) static inherited
Reverse Coordinate order in given CoordinateSequence.
Definition at line 160 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), and geos::geom::CoordinateSequence::setAt().
Referenced by geos::geom::LineString::normalize(), geos::geom::Polygon::normalize(), geos::geom::LinearRing::reverse(), and geos::geom::LineString::reverse().
 {
   // FIXME: use a standard algorithm
   int last = static_cast<int>(cl->getSize()) - 1;
   int mid=last/2;
   for(int i=0;i<=mid;i++) {
     const Coordinate tmp=cl->getAt(i);
     cl->setAt(cl->getAt(last-i),i);
     cl->setAt(tmp,last-i);
   }
 }
void geos::geom::CoordinateSequence::scroll (CoordinateSequence * cl, const Coordinate * firstCoordinate) static inherited
Scroll given CoordinateSequence so to start with given Coordinate.
Definition at line 124 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), and geos::geom::CoordinateSequence::setPoints().
Referenced by geos::geom::Polygon::normalize().
 {
   // FIXME: use a standard algorithm instead
   std::size_t i, j=0;
   std::size_t ind=indexOf(firstCoordinate,cl);
   if (ind<1)
         return; // not found or already first
   const std::size_t length=cl->getSize();
   vector<Coordinate> v(length);
   for (i=ind; i<length; i++) {
     v[j++]=cl->getAt(i);
   }
   for (i=0; i<ind; i++) {
     v[j++]=cl->getAt(i);
   }
   cl->setPoints(v);
 }
void geos::geom::CoordinateArraySequence::setAt (const Coordinate & c, std::size_t pos) override virtual
Get a reference to Coordinate at position pos.
Copy Coordinate c to position pos
Implements geos::geom::CoordinateSequence.
Definition at line 175 of file CoordinateArraySequence.cpp.
 {
   (*vect)[pos]=c;
 }
void geos::geom::CoordinateArraySequence::setOrdinate (std::size_t index, std::size_t ordinateIndex, double value) override virtual
Sets the value for a given ordinate of a coordinate in this sequence.
Parameters
index the coordinate index in the sequence
ordinateIndex the ordinate index in the coordinate (in range [0, dimension-1])
value the new ordinate value
Implements geos::geom::CoordinateSequence.
Definition at line 233 of file CoordinateArraySequence.cpp.
References geos::geom::CoordinateSequence::X, geos::geom::CoordinateSequence::Y, and geos::geom::CoordinateSequence::Z.
 {
   switch (ordinateIndex)
   {
     case CoordinateSequence::X:
       (*vect)[index].x = value;
       break;
     case CoordinateSequence::Y:
       (*vect)[index].y = value;
       break;
     case CoordinateSequence::Z:
       (*vect)[index].z = value;
       break;
     default:
     {
       std::stringstream ss;
       ss << "Unknown ordinate index " << index;
       throw util::IllegalArgumentException(ss.str());
       break;
     }
   }
 }
void geos::geom::CoordinateArraySequence::setPoints (const std::vector< Coordinate > & v) override virtual
Substitute Coordinate list with a copy of the given vector.
Implements geos::geom::CoordinateSequence.
Definition at line 81 of file CoordinateArraySequence.cpp.
References vect.
 {
   vect->assign(v.begin(), v.end());
 }
size_t geos::geom::CoordinateSequence::size () const inline inherited
Definition at line 113 of file CoordinateSequence.h.
Referenced by add(), geos::algorithm::InteriorPointLine::addEndpoints(), geos::operation::distance::FacetSequenceTreeBuilder::addFacetSequences(), geos::algorithm::Centroid::addHole(), geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::addLine(), geos::algorithm::CentroidArea::addLinearSegments(), geos::algorithm::Centroid::addLineSegments(), geos::geomgraph::GeometryGraph::addLineString(), geos::operation::buffer::OffsetCurveSetBuilder::addPolygonRing(), geos::operation::buffer::OffsetSegmentString::addPts(), geos::algorithm::Centroid::addShell(), geos::noding::NodingValidator::checkEndPtVertexIntersections(), geos::noding::NodingValidator::checkInteriorIntersections(), geos::operation::buffer::OffsetSegmentString::closeRing(), geos::operation::buffer::BufferInputLineSimplifier::collapseLine(), geos::noding::OrientedCoordinateArray::compareOriented(), geos::algorithm::distance::DiscreteFrechetDistance::compute(), geos::algorithm::distance::DistanceToPoint::computeDistance(), geos::linearref::ExtractLineByLocation::computeLine(), geos::operation::buffer::OffsetCurveBuilder::computeLineBufferCurve(), geos::operation::buffer::BufferBuilder::computeNodedEdges(), geos::operation::buffer::OffsetCurveBuilder::computeRingBufferCurve(), geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve(), geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps(), geos::operation::buffer::BufferInputLineSimplifier::deleteShallowConcavities(), geos::linearref::LinearGeometryBuilder::endLine(), geos::operation::overlay::validate::OffsetPointGenerator::extractPoints(), geos::geomgraph::PlanarGraph::findEdgeInSameDirection(), geos::operation::buffer::BufferInputLineSimplifier::findNextNonDeletedIndex(), geos::algorithm::distance::DiscreteFrechetDistance::getSegementAt(), geos::operation::buffer::OffsetCurveBuilder::getSingleSidedLineCurve(), geos::geom::CoordinateSequence::increasingDirection(), geos::simplify::TaggedLineString::init(), geos::operation::buffer::OffsetSegmentString::isRedundant(), geos::algorithm::RayCrossingCounter::locatePointInRing(), geos::operation::overlay::OverlayOp::mergeZ(), geos::geom::operator<<(), geos::operation::intersection::RectangleIntersectionBuilder::reconnect(), geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), geos::noding::ScaledNoder::scale(), geos::simplify::TaggedLineStringSimplifier::simplify(), geos::operation::buffer::BufferInputLineSimplifier::simplify(), geos::operation::buffer::OffsetSegmentString::size(), and geos::triangulate::DelaunayTriangulationBuilder::toVertices().
 { return getSize(); }
string geos::geom::CoordinateArraySequence::toString () const override virtual
Get a string rapresentation of CoordinateSequence.
Implements geos::geom::CoordinateSequence.
Definition at line 187 of file CoordinateArraySequence.cpp.
References getSize(), geos::geom::Coordinate::toString(), and vect.
 {
   string result("(");
   if (getSize()>0) {
     //char buffer[100];
     for (size_t i=0, n=vect->size(); i<n; i++)
     {
       Coordinate& c=(*vect)[i];
       if ( i ) result.append(", ");
       result.append(c.toString());
     }
   }
   result.append(")");
   return result;
 }
const vector< Coordinate > * geos::geom::CoordinateArraySequence::toVector () const override virtual
Returns a read-only vector with the Coordinates in this collection.
Whether or not the Coordinates returned are the actual underlying Coordinates or merely copies depends on the implementation. Note that if this implementation does not store its data as an array of Coordinates, this method will incur a performance penalty because the array needs to be built from scratch.
This method is a port of the toCoordinateArray() method of JTS. It is not much used as memory management requires us to know wheter we should or not delete the returned object in a consistent way. Our options are: use shared_ptr<Coordinate> or always keep ownerhips of an eventual newly created vector. We opted for the second, so the returned object is a const, to also ensure that returning an internal pointer doesn't make the object mutable.
Deprecated:
use toVector(std::vector<Coordinate>&) instead
Implements geos::geom::CoordinateSequence.
Definition at line 87 of file CoordinateArraySequence.cpp.
References vect.
 {
   return vect; //new vector<Coordinate>(vect->begin(),vect->end());
 }
void geos::geom::CoordinateArraySequence::toVector (std::vector< Coordinate > & coords) const override virtual
Pushes all Coordinates of this sequence onto the provided vector.
This method is a port of the toCoordinateArray() method of JTS.
Implements geos::geom::CoordinateSequence.
Definition at line 110 of file CoordinateArraySequence.cpp.
References vect.
 {
   // TODO: can this be optimized ?
   out.insert(out.end(), vect->begin(), vect->end());
 }
Member Data Documentation
std::size_t geos::geom::CoordinateArraySequence::dimension mutable private
Definition at line 123 of file CoordinateArraySequence.h.
Referenced by apply_rw(), CoordinateArraySequence(), and getDimension().
std::vector<Coordinate>* geos::geom::CoordinateArraySequence::vect private
Definition at line 122 of file CoordinateArraySequence.h.
Referenced by add(), apply_ro(), apply_rw(), CoordinateArraySequence(), deleteAt(), expandEnvelope(), getDimension(), getOrdinate(), getSize(), removeRepeatedPoints(), setPoints(), toString(), toVector(), and ~CoordinateArraySequence().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/CoordinateArraySequence.h
/home/vicky/potree/geos/vicky/src/geom/CoordinateArraySequence.cpp