GEOS: geos::index::quadtree::DoubleBits Class Reference
geos::index::quadtree::DoubleBits Class Reference
DoubleBits manipulates Double numbers by using bit manipulation and bit-field extraction.
#include <DoubleBits.h>
Public Member Functions
DoubleBits (double nx)
double getDouble () const
int64 biasedExponent () const
Determines the exponent for the number.
int getExponent () const
Determines the exponent for the number.
void zeroLowerBits (int nBits)
int getBit (int i) const
int numCommonMantissaBits (const DoubleBits &db) const
This computes the number of common most-significant bits in the mantissa.
std::string toString () const
A representation of the Double bits formatted for easy readability.
Static Public Member Functions
static double powerOf2 (int exp)
static int exponent (double d)
static double truncateToPowerOfTwo (double d)
static std::string toBinaryString (double d)
static double maximumCommonMantissa (double d1, double d2)
Static Public Attributes
static const int EXPONENT_BIAS =1023
Private Attributes
double x
int64 xBits
Detailed Description
DoubleBits manipulates Double numbers by using bit manipulation and bit-field extraction.
For some operations (such as determining the exponent) this is more accurate than using mathematical operations (which suffer from round-off error).
The algorithms and constants in this class apply only to IEEE-754 double-precision floating point format.
Definition at line 44 of file DoubleBits.h.
Constructor & Destructor Documentation
geos::index::quadtree::DoubleBits::DoubleBits (double nx)
Definition at line 91 of file DoubleBits.cpp.
 {
 #if ASSUME_IEEE_DOUBLE
   memcpy(&xBits,&nx,sizeof(double));
 #endif
   x = nx;
 }
Member Function Documentation
int64 geos::index::quadtree::DoubleBits::biasedExponent () const
Determines the exponent for the number.
Definition at line 108 of file DoubleBits.cpp.
 {
   int64 signExp=xBits>>52;
   int64 exp=signExp&0x07ff;
   //cerr<<"xBits:"<<xBits<<" signExp:"<<signExp<<" exp:"<<exp<<endl;
   return exp;
 }
int geos::index::quadtree::DoubleBits::exponent (double d) static
Definition at line 59 of file DoubleBits.cpp.
References getExponent().
 {
   DoubleBits db(d);
   return db.getExponent();
 }
int geos::index::quadtree::DoubleBits::getBit (int i) const
Definition at line 139 of file DoubleBits.cpp.
Referenced by numCommonMantissaBits().
 {
   long mask=(1L<<i);
   return (xBits&mask)!=0?1:0;
 }
double geos::index::quadtree::DoubleBits::getDouble () const
Definition at line 101 of file DoubleBits.cpp.
Referenced by maximumCommonMantissa(), and truncateToPowerOfTwo().
 {
   return x;
 }
int geos::index::quadtree::DoubleBits::getExponent () const
Determines the exponent for the number.
Definition at line 118 of file DoubleBits.cpp.
Referenced by exponent(), and maximumCommonMantissa().
 {
 #if ASSUME_IEEE_DOUBLE
   return static_cast<int>(biasedExponent() - EXPONENT_BIAS);
 #else
   if ( x <= 0 ) return 0; // EDOM || ERANGE
   return (int)((log(x)/log(2.0))+(x<1?-0.9:0.00000000001));
 #endif
 }
double geos::index::quadtree::DoubleBits::maximumCommonMantissa (double d1, double d2) static
Definition at line 79 of file DoubleBits.cpp.
References getDouble(), getExponent(), numCommonMantissaBits(), and zeroLowerBits().
 {
   if (d1==0.0 || d2==0.0) return 0.0;
   DoubleBits db1(d1);
   DoubleBits db2(d2);
   if (db1.getExponent() != db2.getExponent()) return 0.0;
   int maxCommon=db1.numCommonMantissaBits(db2);
   db1.zeroLowerBits(64-(12+maxCommon));
   return db1.getDouble();
 }
int geos::index::quadtree::DoubleBits::numCommonMantissaBits (const DoubleBits & db) const
This computes the number of common most-significant bits in the mantissa.
It does not count the hidden bit, which is always 1. It does not determine whether the numbers have the same exponent; if they do not, the value computed by this function is meaningless.
Parameters
db
Returns
the number of common most-significant mantissa bits
Definition at line 147 of file DoubleBits.cpp.
References getBit().
Referenced by maximumCommonMantissa().
 {
   for (int i=0;i<52;i++) {
     //int bitIndex=i+12;
     if (getBit(i)!=db.getBit(i))
       return i;
   }
   return 52;
 }
double geos::index::quadtree::DoubleBits::powerOf2 (int exp) static
Definition at line 43 of file DoubleBits.cpp.
Referenced by geos::index::quadtree::Key::computeKey().
 {
   if (exp>1023 || exp<-1022)
     throw util::IllegalArgumentException("Exponent out of bounds");
 #if ASSUME_IEEE_DOUBLE
   int64 expBias=exp+EXPONENT_BIAS;
   int64 bits=expBias << 52;
   double ret;
   memcpy(&ret, &bits, sizeof(int64));
   return ret;
 #else
   return pow(2.0, exp);
 #endif
 }
string geos::index::quadtree::DoubleBits::toBinaryString (double d) static
Definition at line 73 of file DoubleBits.cpp.
References toString().
{
   DoubleBits db(d);
   return db.toString();
 }
string geos::index::quadtree::DoubleBits::toString (void) const
A representation of the Double bits formatted for easy readability.
Definition at line 159 of file DoubleBits.cpp.
Referenced by toBinaryString().
 {
     // TODO: Fix it!
     return "FIXME: unimplemented DoubleBits::toString()";
     //String numStr = Long.toBinaryString(xBits);
     //String zero64 = "0000000000000000000000000000000000000000000000000000000000000000";
     //String padStr =  zero64 + numStr;
     //String bitStr = padStr.substring(padStr.length() - 64);
     //String str = bitStr.substring(0, 1) + "  "
     //+ bitStr.substring(1, 12) + "(" + getExponent() + ") "
     //+ bitStr.substring(12)
     //+ " [ " + x + " ]";
     //return str;
 }
double geos::index::quadtree::DoubleBits::truncateToPowerOfTwo (double d) static
Definition at line 66 of file DoubleBits.cpp.
References getDouble(), and zeroLowerBits().
 {
   DoubleBits db(d);
   db.zeroLowerBits(52);
   return db.getDouble();
 }
void geos::index::quadtree::DoubleBits::zeroLowerBits (int nBits)
Definition at line 130 of file DoubleBits.cpp.
Referenced by maximumCommonMantissa(), and truncateToPowerOfTwo().
 {
   long invMask=(1L<<nBits)-1L;
   long mask=~invMask;
   xBits&=mask;
 }
Member Data Documentation
const int geos::index::quadtree::DoubleBits::EXPONENT_BIAS =1023 static
Definition at line 48 of file DoubleBits.h.
double geos::index::quadtree::DoubleBits::x private
Definition at line 93 of file DoubleBits.h.
int64 geos::index::quadtree::DoubleBits::xBits private
Definition at line 95 of file DoubleBits.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/quadtree/DoubleBits.h
/home/vicky/potree/geos/vicky/src/index/quadtree/DoubleBits.cpp