GEOS: geos::operation::overlay::ElevationMatrix Class Reference
geos::operation::overlay::ElevationMatrix Class Reference
#include <ElevationMatrix.h>
Public Member Functions
ElevationMatrix (const geom::Envelope &extent, unsigned int rows, unsigned int cols)
~ElevationMatrix ()
void add (const geom::Geometry *geom)
void elevate (geom::Geometry *geom) const
double getAvgElevation () const
ElevationMatrixCell & getCell (const geom::Coordinate &c)
const ElevationMatrixCell & getCell (const geom::Coordinate &c) const
std::string print () const
Private Member Functions
void add (const geom::Coordinate &c)
Private Attributes
ElevationMatrixFilter filter
geom::Envelope env
unsigned int cols
unsigned int rows
double cellwidth
double cellheight
bool avgElevationComputed
double avgElevation
std::vector< ElevationMatrixCell > cells
Friends
class ElevationMatrixFilter
Detailed Description
Definition at line 80 of file ElevationMatrix.h.
Constructor & Destructor Documentation
geos::operation::overlay::ElevationMatrix::ElevationMatrix (const geom::Envelope & extent, unsigned int rows, unsigned int cols)
Definition at line 91 of file ElevationMatrix.cpp.
References cellheight, cellwidth, cols, env, geos::geom::Envelope::getHeight(), geos::geom::Envelope::getWidth(), and rows.
                                                :
   filter(*this),
   env(newEnv), cols(newCols), rows(newRows),
   avgElevationComputed(false),
   avgElevation(DoubleNotANumber),
   cells(newRows*newCols)
 {
   cellwidth=env.getWidth()/cols;
   cellheight=env.getHeight()/rows;
   if ( ! cellwidth ) cols=1;
   if ( ! cellheight ) rows=1;
 }
geos::operation::overlay::ElevationMatrix::~ElevationMatrix ()
Definition at line 105 of file ElevationMatrix.cpp.
 {
 }
Member Function Documentation
void geos::operation::overlay::ElevationMatrix::add (const geom::Geometry * geom)
Definition at line 110 of file ElevationMatrix.cpp.
References geos::geom::Geometry::apply_ro(), avgElevationComputed, filter, geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
Referenced by geos::operation::overlay::ElevationMatrixFilter::filter_ro(), and geos::operation::overlay::OverlayOp::OverlayOp().
 {
 #if GEOS_DEBUG
   cerr<<"ElevationMatrix::add(Geometry *) called"<<endl;
 #endif // GEOS_DEBUG
   // Cannot add Geometries to an ElevationMatrix after it's average
   // elevation has been computed
   assert(!avgElevationComputed);
   //ElevationMatrixFilter filter(this);
   geom->apply_ro(&filter);
 }
void geos::operation::overlay::ElevationMatrix::add (const geom::Coordinate & c) private
Definition at line 138 of file ElevationMatrix.cpp.
References geos::operation::overlay::ElevationMatrixCell::add(), getCell(), geos::geom::Coordinate::toString(), geos::util::GEOSException::what(), and geos::geom::Coordinate::z.
 {
   if ( ISNAN(c.z) ) return;
   try {
     ElevationMatrixCell &emc = getCell(c);
     emc.add(c);
   } catch (const util::IllegalArgumentException& exp) {
     // coordinate do not overlap matrix
     cerr << "ElevationMatrix::add(" << c.toString()
          << "): Coordinate does not overlap grid extent: "
          << exp.what() << endl;
     return;
   }
 }
void geos::operation::overlay::ElevationMatrix::elevate (geom::Geometry * geom) const
Definition at line 235 of file ElevationMatrix.cpp.
References geos::geom::Geometry::apply_rw(), filter, and getAvgElevation().
Referenced by geos::operation::overlay::OverlayOp::computeOverlay().
 {
   // Nothing to do if no elevation info in matrix
   if ( ISNAN(getAvgElevation()) ) return;
   g->apply_rw(&filter);
 }
double geos::operation::overlay::ElevationMatrix::getAvgElevation () const
Definition at line 192 of file ElevationMatrix.cpp.
References avgElevation, avgElevationComputed, cells, cols, geos::operation::overlay::ElevationMatrixCell::getAvg(), and rows.
Referenced by elevate(), geos::operation::overlay::ElevationMatrixFilter::filter_rw(), and print().
 {
   if ( avgElevationComputed ) return avgElevation;
   double ztot=0;
   int zvals=0;
   for (unsigned int r=0; r<rows; r++)
   {
     for(unsigned int c=0; c<cols; c++)
     {
       const ElevationMatrixCell &cell = cells[(r*cols)+c];
       double e = cell.getAvg();
       if ( !ISNAN(e) )
       {
         zvals++;
         ztot+=e;
       }
     }
   }
   if ( zvals ) avgElevation = ztot/zvals;
   else avgElevation = DoubleNotANumber;
   avgElevationComputed = true;
   return avgElevation;
 }
ElevationMatrixCell & geos::operation::overlay::ElevationMatrix::getCell (const geom::Coordinate & c)
Definition at line 154 of file ElevationMatrix.cpp.
References cellheight, cells, cellwidth, cols, env, geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), rows, geos::geom::Envelope::toString(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by add(), and geos::operation::overlay::ElevationMatrixFilter::filter_rw().
 {
   int col, row;
   if ( ! cellwidth ) col=0;
   else
   {
     double xoffset = c.x - env.getMinX();
     col = (int)(xoffset/cellwidth);
     if ( col == (int)cols ) col = cols-1;
   }
   if ( ! cellheight ) row=0;
   else
   {
     double yoffset = c.y - env.getMinY();
     row = (int)(yoffset/cellheight);
     if ( row == (int)rows ) row = rows-1;
   }
   int celloffset = (cols*row)+col;
   if  (celloffset<0 || celloffset >= (int)(cols*rows))
   {
     ostringstream s;
     s<<"ElevationMatrix::getCell got a Coordinate out of grid extent ("<<env.toString()<<") - cols:"<<cols<<" rows:"<<rows;
     throw util::IllegalArgumentException(s.str());
   }
   return cells[celloffset];
 }
const ElevationMatrixCell & geos::operation::overlay::ElevationMatrix::getCell (const geom::Coordinate & c) const
Definition at line 185 of file ElevationMatrix.cpp.
 {
   return (const ElevationMatrixCell &)
     ((ElevationMatrix *)this)->getCell(c);
 }
string geos::operation::overlay::ElevationMatrix::print () const
Definition at line 219 of file ElevationMatrix.cpp.
References cells, cols, getAvgElevation(), and rows.
Referenced by geos::operation::overlay::OverlayOp::OverlayOp().
 {
   ostringstream ret;
   ret << "Cols:"<<cols<<" Rows:"<<rows<<" AvgElevation:"<<getAvgElevation()<<endl;
   for (unsigned int r=0; r<rows; r++)
   {
     for (unsigned int c=0; c<cols; c++)
     {
       ret << cells[(r*cols)+c].print() << '\t';
     }
     ret << endl;
   }
   return ret.str();
 }
Friends And Related Function Documentation
friend class ElevationMatrixFilter friend
Definition at line 81 of file ElevationMatrix.h.
Member Data Documentation
double geos::operation::overlay::ElevationMatrix::avgElevation mutable private
Definition at line 102 of file ElevationMatrix.h.
Referenced by getAvgElevation().
bool geos::operation::overlay::ElevationMatrix::avgElevationComputed mutable private
Definition at line 101 of file ElevationMatrix.h.
Referenced by add(), and getAvgElevation().
double geos::operation::overlay::ElevationMatrix::cellheight private
Definition at line 100 of file ElevationMatrix.h.
Referenced by ElevationMatrix(), and getCell().
std::vector<ElevationMatrixCell> geos::operation::overlay::ElevationMatrix::cells private
Definition at line 103 of file ElevationMatrix.h.
Referenced by getAvgElevation(), getCell(), and print().
double geos::operation::overlay::ElevationMatrix::cellwidth private
Definition at line 99 of file ElevationMatrix.h.
Referenced by ElevationMatrix(), and getCell().
unsigned int geos::operation::overlay::ElevationMatrix::cols private
Definition at line 97 of file ElevationMatrix.h.
Referenced by ElevationMatrix(), getAvgElevation(), getCell(), and print().
geom::Envelope geos::operation::overlay::ElevationMatrix::env private
Definition at line 96 of file ElevationMatrix.h.
Referenced by ElevationMatrix(), and getCell().
ElevationMatrixFilter geos::operation::overlay::ElevationMatrix::filter private
Definition at line 94 of file ElevationMatrix.h.
Referenced by add(), and elevate().
unsigned int geos::operation::overlay::ElevationMatrix::rows private
Definition at line 98 of file ElevationMatrix.h.
Referenced by ElevationMatrix(), getAvgElevation(), getCell(), and print().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/ElevationMatrix.h
/home/vicky/potree/geos/vicky/src/operation/overlay/ElevationMatrix.cpp