GEOS: geos::geomgraph::Label Class Reference
geos::geomgraph::Label Class Reference
A Label indicates the topological relationship of a component of a topology graph to a given Geometry. This class supports labels for relationships to two Geometrys, which is sufficient for algorithms for binary operations.
#include <Label.h>
Public Member Functions
Label (int onLoc)
Construct a Label with a single location for both Geometries.
Label (int geomIndex, int onLoc)
Construct a Label with the location specified for the given Geometry.
Label (int onLoc, int leftLoc, int rightLoc)
Construct a Label with On, Left and Right locations for both Geometries.
Label (const Label &l)
Copy ctor.
Label & operator= (const Label &l)
Label ()
Initialize both locations to Location::UNDEF.
Label (int geomIndex, int onLoc, int leftLoc, int rightLoc)
Construct a Label with On, Left and Right locations for the given Geometries. Initialize the locations for the other Geometry to Location::UNDEF.
void flip ()
int getLocation (int geomIndex, int posIndex) const
int getLocation (int geomIndex) const
void setLocation (int geomIndex, int posIndex, int location)
void setLocation (int geomIndex, int location)
void setAllLocations (int geomIndex, int location)
void setAllLocationsIfNull (int geomIndex, int location)
void setAllLocationsIfNull (int location)
void merge (const Label &lbl)
Merge this label with another one.
int getGeometryCount () const
bool isNull () const
bool isNull (int geomIndex) const
bool isAnyNull (int geomIndex) const
bool isArea () const
bool isArea (int geomIndex) const
bool isLine (int geomIndex) const
bool isEqualOnSide (const Label &lbl, int side) const
bool allPositionsEqual (int geomIndex, int loc) const
void toLine (int geomIndex)
Converts one GeometryLocation to a Line location.
std::string toString () const
Static Public Member Functions
static Label toLineLabel (const Label &label)
Converts a Label to a Line label (that is, one with no side Locations)
Private Attributes
TopologyLocation elt [2]
Friends
std::ostream & operator<< (std::ostream &, const Label &)
Detailed Description
A Label indicates the topological relationship of a component of a topology graph to a given Geometry. This class supports labels for relationships to two Geometrys, which is sufficient for algorithms for binary operations.
Topology graphs support the concept of labeling nodes and edges in the graph. The label of a node or edge specifies its topological relationship to one or more geometries. (In fact, since JTS operations have only two arguments labels are required for only two geometries). A label for a node or edge has one or two elements, depending on whether the node or edge occurs in one or both of the input Geometrys. Elements contain attributes which categorize the topological location of the node or edge relative to the parent Geometry; that is, whether the node or edge is in the interior, boundary or exterior of the Geometry. Attributes have a value from the set {Interior, Boundary, Exterior}. In a node each element has a single attribute <On>. For an edge each element has a triplet of attributes <Left, On, Right>.
It is up to the client code to associate the 0 and 1 TopologyLocations with specific geometries.
Definition at line 57 of file Label.h.
Constructor & Destructor Documentation
geos::geomgraph::Label::Label (int onLoc)
Construct a Label with a single location for both Geometries.
Definition at line 49 of file Label.cpp.
 {
   elt[0]=TopologyLocation(onLoc);
   elt[1]=TopologyLocation(onLoc);
 }
geos::geomgraph::Label::Label (int geomIndex, int onLoc)
Construct a Label with the location specified for the given Geometry.
Other geometry location will be set to Location::UNDEF.
Definition at line 56 of file Label.cpp.
 {
   assert(geomIndex>=0 && geomIndex<2);
   elt[0]=TopologyLocation(Location::UNDEF);
   elt[1]=TopologyLocation(Location::UNDEF);
   elt[geomIndex].setLocation(onLoc);
 }
geos::geomgraph::Label::Label (int onLoc, int leftLoc, int rightLoc)
Construct a Label with On, Left and Right locations for both Geometries.
Initialize the locations for both Geometries to the given values.
Definition at line 65 of file Label.cpp.
 {
   elt[0]=TopologyLocation(onLoc,leftLoc,rightLoc);
   elt[1]=TopologyLocation(onLoc,leftLoc,rightLoc);
 }
geos::geomgraph::Label::Label (const Label & l)
Copy ctor.
Definition at line 79 of file Label.cpp.
References elt.
 {
   elt[0]=TopologyLocation(l.elt[0]);
   elt[1]=TopologyLocation(l.elt[1]);
 }
geos::geomgraph::Label::Label ()
Initialize both locations to Location::UNDEF.
isNull() should return true after this kind of construction
Definition at line 72 of file Label.cpp.
 {
   elt[0]=TopologyLocation(Location::UNDEF);
   elt[1]=TopologyLocation(Location::UNDEF);
 }
geos::geomgraph::Label::Label (int geomIndex, int onLoc, int leftLoc, int rightLoc)
Construct a Label with On, Left and Right locations for the given Geometries. Initialize the locations for the other Geometry to Location::UNDEF.
Definition at line 95 of file Label.cpp.
 {
   elt[0]=TopologyLocation(Location::UNDEF,Location::UNDEF,Location::UNDEF);
   elt[1]=TopologyLocation(Location::UNDEF,Location::UNDEF,Location::UNDEF);
   elt[geomIndex].setLocations(onLoc,leftLoc,rightLoc);
 }
Member Function Documentation
bool geos::geomgraph::Label::allPositionsEqual (int geomIndex, int loc) const
Definition at line 242 of file Label.cpp.
Referenced by geos::geomgraph::DirectedEdge::isLineEdge().
 {
   assert(geomIndex>=0 && geomIndex<2);
   return elt[geomIndex].allPositionsEqual(loc);
 }
void geos::geomgraph::Label::flip ()
Definition at line 104 of file Label.cpp.
Referenced by geos::geomgraph::DirectedEdge::computeDirectedLabel(), geos::operation::relate::EdgeEndBuilder::createEdgeEndForPrev(), geos::operation::overlay::OverlayOp::insertUniqueEdge(), and geos::operation::buffer::BufferBuilder::insertUniqueEdge().
 {
   elt[0].flip();
   elt[1].flip();
 }
int geos::geomgraph::Label::getGeometryCount () const
Definition at line 177 of file Label.cpp.
Referenced by geos::geomgraph::EdgeRing::isIsolated(), geos::geomgraph::Node::isIsolated(), geos::operation::relate::RelateComputer::labelIsolatedNodes(), and geos::geomgraph::GraphComponent::updateIM().
 {
   int count = 0;
   if (!elt[0].isNull()) count++;
   if (!elt[1].isNull()) count++;
   return count;
 }
int geos::geomgraph::Label::getLocation (int geomIndex, int posIndex) const
Definition at line 112 of file Label.cpp.
Referenced by geos::geomgraph::Depth::add(), geos::geomgraph::GeometryGraph::addSelfIntersectionNodes(), geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent(), geos::operation::relate::RelateNode::computeIM(), geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), geos::geomgraph::DirectedEdgeStar::computeLabelling(), geos::geomgraph::EdgeEndStar::computeLabelling(), geos::operation::relate::EdgeEndBundle::computeLabelOn(), geos::operation::relate::EdgeEndBundle::computeLabelSide(), geos::geomgraph::Node::computeMergedLocation(), geos::operation::relate::RelateNodeGraph::copyNodesAndLabels(), geos::operation::relate::RelateComputer::copyNodesAndLabels(), geos::operation::overlay::OverlayOp::copyPoints(), geos::operation::buffer::BufferBuilder::depthDelta(), geos::operation::overlay::OverlayOp::findResultAreaEdges(), geos::geomgraph::NodeMap::getBoundaryNodes(), geos::operation::valid::ConnectedInteriorTester::hasUnvisitedShellEdge(), geos::geomgraph::GeometryGraph::insertBoundaryPoint(), geos::geomgraph::PlanarGraph::isBoundaryNode(), geos::geomgraph::DirectedEdge::isInteriorAreaEdge(), geos::operation::overlay::OverlayOp::isResultOfOp(), geos::operation::relate::RelateComputer::labelIntersectionNodes(), geos::geomgraph::Node::mergeLabel(), geos::geomgraph::EdgeRing::mergeLabel(), geos::geomgraph::EdgeEndStar::propagateSideLabels(), geos::operation::valid::ConnectedInteriorTester::setInteriorEdgesInResult(), geos::geomgraph::Node::setLabelBoundary(), toLineLabel(), geos::geomgraph::Edge::updateIM(), geos::geomgraph::DirectedEdgeStar::updateLabelling(), and geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
 {
   assert(geomIndex>=0 && geomIndex<2);
   return elt[geomIndex].get(posIndex);
 }
int geos::geomgraph::Label::getLocation (int geomIndex) const
Definition at line 120 of file Label.cpp.
 {
   assert(geomIndex>=0 && geomIndex<2);
   return elt[geomIndex].get(Position::ON);
 }
bool geos::geomgraph::Label::isAnyNull (int geomIndex) const
Definition at line 202 of file Label.cpp.
Referenced by geos::geomgraph::EdgeEndStar::computeLabelling().
 {
   assert(geomIndex>=0 && geomIndex<2);
   return elt[geomIndex].isAnyNull();
 }
bool geos::geomgraph::Label::isArea () const
Definition at line 210 of file Label.cpp.
Referenced by geos::operation::overlay::PolygonBuilder::buildMaximalEdgeRings(), geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent(), geos::operation::relate::EdgeEndBundle::computeLabel(), geos::operation::overlay::OverlayOp::computeLabelsFromDepths(), geos::operation::relate::EdgeEndBundle::computeLabelSide(), geos::geomgraph::EdgeRing::computePoints(), geos::operation::overlay::OverlayOp::findResultAreaEdges(), geos::geomgraph::Edge::isCollapsed(), geos::geomgraph::DirectedEdge::isInteriorAreaEdge(), geos::geomgraph::DirectedEdge::isLineEdge(), geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges(), geos::geomgraph::EdgeEndStar::propagateSideLabels(), and geos::geomgraph::Edge::updateIM().
 {
   return elt[0].isArea() || elt[1].isArea();
 }
bool geos::geomgraph::Label::isArea (int geomIndex) const
Definition at line 217 of file Label.cpp.
 {
   assert(geomIndex>=0 && geomIndex<2);
   return elt[geomIndex].isArea();
 }
bool geos::geomgraph::Label::isEqualOnSide (const Label & lbl, int side) const
Definition at line 233 of file Label.cpp.
References elt.
 {
   return
     elt[0].isEqualOnSide(lbl.elt[0], side)
     && elt[1].isEqualOnSide(lbl.elt[1], side);
 }
bool geos::geomgraph::Label::isLine (int geomIndex) const
Definition at line 225 of file Label.cpp.
Referenced by geos::geomgraph::EdgeEndStar::computeLabelling(), and geos::geomgraph::DirectedEdge::isLineEdge().
 {
   assert(geomIndex>=0 && geomIndex<2);
   return elt[geomIndex].isLine();
 }
bool geos::geomgraph::Label::isNull (void) const
Definition at line 195 of file Label.cpp.
Referenced by geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), geos::operation::overlay::OverlayOp::computeLabelsFromDepths(), geos::geomgraph::Node::computeMergedLocation(), geos::geomgraph::GeometryGraph::insertPoint(), geos::geomgraph::PlanarGraph::isBoundaryNode(), geos::operation::overlay::OverlayOp::labelIncompleteNodes(), geos::operation::relate::RelateComputer::labelIntersectionNodes(), geos::operation::overlay::LineBuilder::labelIsolatedLines(), geos::operation::relate::RelateComputer::labelIsolatedNodes(), geos::geomgraph::Node::mergeLabel(), and geos::geomgraph::Node::setLabel().
 {
   return elt[0].isNull() && elt[1].isNull();
 }
bool geos::geomgraph::Label::isNull (int geomIndex) const
Definition at line 187 of file Label.cpp.
 {
   assert(geomIndex>=0 && geomIndex<2);
   return elt[geomIndex].isNull();
 }
void geos::geomgraph::Label::merge (const Label & lbl)
Merge this label with another one.
Merging updates any null attributes of this label with the attributes from lbl
Definition at line 168 of file Label.cpp.
References elt.
Referenced by geos::operation::overlay::OverlayOp::insertUniqueEdge(), geos::operation::buffer::BufferBuilder::insertUniqueEdge(), geos::geomgraph::DirectedEdgeStar::mergeSymLabels(), and geos::operation::overlay::OverlayOp::updateNodeLabelling().
 {
   for (int i=0; i<2; i++) {
     elt[i].merge(lbl.elt[i]);
   }
 }
Label & geos::geomgraph::Label::operator= (const Label & l)
Definition at line 87 of file Label.cpp.
References elt.
 {
   elt[0] = TopologyLocation(l.elt[0]);
   elt[1] = TopologyLocation(l.elt[1]);
   return *this;
 }
void geos::geomgraph::Label::setAllLocations (int geomIndex, int location)
Definition at line 144 of file Label.cpp.
Referenced by geos::operation::relate::RelateComputer::labelIsolatedEdge(), and geos::operation::relate::RelateComputer::labelIsolatedNode().
 {
   assert(geomIndex>=0 && geomIndex<2);
   elt[geomIndex].setAllLocations(location);
 }
void geos::geomgraph::Label::setAllLocationsIfNull (int geomIndex, int location)
Definition at line 152 of file Label.cpp.
Referenced by geos::geomgraph::EdgeEndStar::computeLabelling(), and geos::geomgraph::DirectedEdgeStar::updateLabelling().
 {
   assert(geomIndex>=0 && geomIndex<2);
   elt[geomIndex].setAllLocationsIfNull(location);
 }
void geos::geomgraph::Label::setAllLocationsIfNull (int location)
Definition at line 160 of file Label.cpp.
 {
   setAllLocationsIfNull(0,location);
   setAllLocationsIfNull(1,location);
 }
void geos::geomgraph::Label::setLocation (int geomIndex, int posIndex, int location)
Definition at line 128 of file Label.cpp.
Referenced by geos::operation::relate::EdgeEndBundle::computeLabelOn(), geos::operation::overlay::OverlayOp::computeLabelsFromDepths(), geos::operation::relate::EdgeEndBundle::computeLabelSide(), geos::geomgraph::GeometryGraph::insertBoundaryPoint(), geos::geomgraph::GeometryGraph::insertPoint(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), geos::operation::overlay::LineBuilder::labelIsolatedLine(), geos::geomgraph::Node::mergeLabel(), geos::geomgraph::EdgeRing::mergeLabel(), geos::geomgraph::EdgeEndStar::propagateSideLabels(), geos::geomgraph::Node::setLabel(), geos::geomgraph::Node::setLabelBoundary(), and toLineLabel().
 {
   assert(geomIndex>=0 && geomIndex<2);
   elt[geomIndex].setLocation(posIndex,location);
 }
void geos::geomgraph::Label::setLocation (int geomIndex, int location)
Definition at line 136 of file Label.cpp.
 {
   assert(geomIndex>=0 && geomIndex<2);
   elt[geomIndex].setLocation(Position::ON,location);
 }
void geos::geomgraph::Label::toLine (int geomIndex)
Converts one GeometryLocation to a Line location.
Definition at line 250 of file Label.cpp.
Referenced by geos::operation::overlay::OverlayOp::computeLabelsFromDepths().
 {
   assert(geomIndex>=0 && geomIndex<2);
   if (elt[geomIndex].isArea()) {
     elt[geomIndex]=TopologyLocation(elt[geomIndex].getLocations()[0]);
   }
 }
Label geos::geomgraph::Label::toLineLabel (const Label & label) static
Converts a Label to a Line label (that is, one with no side Locations)
Definition at line 39 of file Label.cpp.
References getLocation(), and setLocation().
Referenced by geos::geomgraph::Edge::getCollapsedEdge().
 {
   Label lineLabel(Location::UNDEF);
   for (int i=0; i<2; i++) {
     lineLabel.setLocation(i, label.getLocation(i));
   }
   return lineLabel;
 }
string geos::geomgraph::Label::toString (void) const
Definition at line 259 of file Label.cpp.
Referenced by geos::operation::relate::EdgeEndBundle::print().
 {
   stringstream ss;
   ss << *this;
   return ss.str();
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & , const Label &) friend
Definition at line 267 of file Label.cpp.
 {
   os << "A:"
      << l.elt[0]
      << " B:"
      << l.elt[1];
   return os;
 }
Member Data Documentation
TopologyLocation geos::geomgraph::Label::elt[2] private
Definition at line 162 of file Label.h.
Referenced by isEqualOnSide(), Label(), merge(), geos::geomgraph::operator<<(), and operator=().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/Label.h
/home/vicky/potree/geos/vicky/src/geomgraph/Label.cpp