GEOS: geos::util::Profile Class Reference
geos::util::Profile Class Reference
#include <profiler.h>
Public Member Functions
Profile (std::string name)
Create a named profile.
~Profile ()
Destructor.
void start ()
start a new timer
void stop ()
stop current timer
double getMax () const
Return Max stored timing.
double getMin () const
Return Min stored timing.
double getTot () const
Return total timing.
double getAvg () const
Return average timing.
size_t getNumTimings () const
Return number of timings.
Public Attributes
std::string name
Profile name.
Private Attributes
struct timeval starttime stoptime
std::vector< double > timings
double totaltime
double max
double min
double avg
Detailed Description
Definition at line 66 of file profiler.h.
Constructor & Destructor Documentation
geos::util::Profile::Profile (std::string name)
Create a named profile.
Definition at line 26 of file Profiler.cpp.
 {
   name = newname;
   totaltime = 0;
   min = max = avg = 0;
 }
geos::util::Profile::~Profile ()
Destructor.
Definition at line 33 of file Profiler.cpp.
 {
 }
Member Function Documentation
double geos::util::Profile::getAvg (void) const
Return average timing.
Definition at line 50 of file Profiler.cpp.
Referenced by geos::util::operator<<().
 {
   return avg;
 }
double geos::util::Profile::getMax () const
Return Max stored timing.
Definition at line 38 of file Profiler.cpp.
Referenced by geos::util::operator<<().
 {
   return max;
 }
double geos::util::Profile::getMin () const
Return Min stored timing.
Definition at line 44 of file Profiler.cpp.
Referenced by geos::util::operator<<().
 {
   return min;
 }
size_t geos::util::Profile::getNumTimings () const
Return number of timings.
Definition at line 62 of file Profiler.cpp.
Referenced by geos::util::operator<<().
 {
   return timings.size();
 }
double geos::util::Profile::getTot () const
Return total timing.
Definition at line 56 of file Profiler.cpp.
Referenced by geos::util::operator<<().
 {
   return totaltime;
 }
void geos::util::Profile::start () inline
start a new timer
Definition at line 75 of file profiler.h.
References gettimeofday().
Referenced by geos::util::Profiler::start().
                {
     gettimeofday(&starttime, nullptr);
   }
void geos::util::Profile::stop () inline
stop current timer
Definition at line 80 of file profiler.h.
References gettimeofday().
   {
     gettimeofday(&stoptime, nullptr);
     double elapsed = static_cast<double>(
         1000000 * (stoptime.tv_sec - starttime.tv_sec)
         + (stoptime.tv_usec - starttime.tv_usec));
     timings.push_back(elapsed);
     totaltime += elapsed;
     if ( timings.size() == 1 ) max = min = elapsed;
     else
     {
       if ( elapsed > max ) max = elapsed;
       if ( elapsed < min ) min = elapsed;
     }
     avg = totaltime / static_cast<double>(timings.size());
   }
Member Data Documentation
double geos::util::Profile::avg private
Definition at line 135 of file profiler.h.
double geos::util::Profile::max private
Definition at line 129 of file profiler.h.
double geos::util::Profile::min private
Definition at line 132 of file profiler.h.
std::string geos::util::Profile::name
Profile name.
Definition at line 114 of file profiler.h.
Referenced by geos::util::operator<<().
struct timeval starttime geos::util::Profile::stoptime private
Definition at line 120 of file profiler.h.
std::vector<double> geos::util::Profile::timings private
Definition at line 123 of file profiler.h.
double geos::util::Profile::totaltime private
Definition at line 126 of file profiler.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/profiler.h
/home/vicky/potree/geos/vicky/src/util/Profiler.cpp