GEOS: geos::geom::Geometry::GeometryChangedFilter Class Reference
geos::geom::Geometry::GeometryChangedFilter Class Reference
Public Member Functions
void filter_rw (Geometry *geom) override
virtual void filter_ro (const Geometry *geom)
Detailed Description
Definition at line 853 of file Geometry.h.
Member Function Documentation
void geos::geom::GeometryComponentFilter::filter_ro (const Geometry * geom) virtual inherited
Reimplemented in geos::operation::polygonize::Polygonizer::LineStringAdder, geos::geom::util::LinearComponentExtracter, and geos::geom::util::ComponentCoordinateExtracter.
Definition at line 31 of file GeometryComponentFilter.cpp.
References geos::ignore_unused_variable_warning().
Referenced by geos::geom::Point::apply_ro(), geos::geom::GeometryCollection::apply_ro(), geos::geom::Polygon::apply_ro(), geos::geom::LineString::apply_ro(), and geos::geom::Geometry::apply_ro().
 {
   ::geos::ignore_unused_variable_warning(geom);
   assert(0);
 }
void geos::geom::Geometry::GeometryChangedFilter::filter_rw (Geometry * geom) override virtual
Performs an operation with or on geom.
Parameters
geom a Geometry to which the filter is applied.
Reimplemented from geos::geom::GeometryComponentFilter.
Definition at line 717 of file Geometry.cpp.
References geos::geom::Geometry::geometryChangedAction().
 {
    geom->geometryChangedAction();
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/Geometry.h
/home/vicky/potree/geos/vicky/src/geom/Geometry.cpp