GEOS: geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter Class Reference
geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter Class Reference
#include <DiscreteHausdorffDistance.h>
Public Member Functions
MaxDensifiedByFractionDistanceFilter (const geom::Geometry &geom, double fraction)
void filter_ro (const geom::CoordinateSequence &seq, std::size_t index) override
bool isGeometryChanged () const override
bool isDone () const override
const PointPairDistance & getMaxPointDistance () const
virtual void filter_rw (CoordinateSequence &, std::size_t)
Private Member Functions
MaxDensifiedByFractionDistanceFilter (const MaxDensifiedByFractionDistanceFilter &other)
MaxDensifiedByFractionDistanceFilter & operator= (const MaxDensifiedByFractionDistanceFilter &rhs)
Private Attributes
PointPairDistance maxPtDist
PointPairDistance minPtDist
const geom::Geometry & geom
std::size_t numSubSegs
Detailed Description
Definition at line 187 of file DiscreteHausdorffDistance.h.
Constructor & Destructor Documentation
geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::MaxDensifiedByFractionDistanceFilter (const geom::Geometry & geom, double fraction) inline
Definition at line 192 of file DiscreteHausdorffDistance.h.
       :
       geom(geom),
                 numSubSegs( std::size_t(util::round(1.0/fraction)) )
     {
     }
geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::MaxDensifiedByFractionDistanceFilter (const MaxDensifiedByFractionDistanceFilter & other) private
Member Function Documentation
void geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::filter_ro (const geom::CoordinateSequence & , std::size_t) override virtual
Performs an operation on a coordinate in a CoordinateSequence.
Parameters
seq the CoordinateSequence to which the filter is applied
i the index of the coordinate to apply the filter to
This logic also handles skipping Point geometries
Reimplemented from geos::geom::CoordinateSequenceFilter.
Definition at line 39 of file DiscreteHausdorffDistance.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
     if (index == 0)
       return;
     const geom::Coordinate& p0 = seq.getAt(index - 1);
     const geom::Coordinate& p1 = seq.getAt(index);
     double delx = (p1.x - p0.x) / static_cast<double>(numSubSegs);
     double dely = (p1.y - p0.y) / static_cast<double>(numSubSegs);
     for (size_t i = 0; i < numSubSegs; ++i) {
       double x = p0.x + static_cast<double>(i) * delx;
       double y = p0.y + static_cast<double>(i) * dely;
       Coordinate pt(x, y);
       minPtDist.initialize();
       DistanceToPoint::computeDistance(geom, pt, minPtDist);
       maxPtDist.setMaximum(minPtDist);
     }
 }
virtual void geos::geom::CoordinateSequenceFilter::filter_rw (CoordinateSequence & , std::size_t) inline virtual inherited
Performs an operation on a coordinate in a CoordinateSequence.
Parameters
seq the CoordinateSequence to which the filter is applied
i the index of the coordinate to apply the filter to
Definition at line 71 of file CoordinateSequenceFilter.h.
Referenced by geos::geom::Point::apply_rw(), and geos::geom::LineString::apply_rw().
   { assert(0); }
const PointPairDistance& geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::getMaxPointDistance () const inline
Definition at line 207 of file DiscreteHausdorffDistance.h.
Referenced by geos::algorithm::distance::DiscreteHausdorffDistance::computeOrientedDistance().
{
       return maxPtDist;
     }
bool geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::isDone () const inline override virtual
Reports whether the application of this filter can be terminated. Once this method returns false, it should continue to return false on every subsequent call.
Returns
true if the application of this filter can be terminated.
Implements geos::geom::CoordinateSequenceFilter.
Definition at line 205 of file DiscreteHausdorffDistance.h.
 { return false; }
bool geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::isGeometryChanged () const inline override virtual
Reports whether the execution of this filter has modified the coordinates of the geometry. If so, Geometry#geometryChanged will be executed after this filter has finished being executed.
Most filters can simply return a constant value reflecting whether they are able to change the coordinates.
Returns
true if this filter has changed the coordinates of the geometry
Implements geos::geom::CoordinateSequenceFilter.
Definition at line 203 of file DiscreteHausdorffDistance.h.
 { return false; }
MaxDensifiedByFractionDistanceFilter& geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::operator= (const MaxDensifiedByFractionDistanceFilter & rhs) private
Member Data Documentation
const geom::Geometry& geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::geom private
Definition at line 214 of file DiscreteHausdorffDistance.h.
PointPairDistance geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::maxPtDist private
Definition at line 212 of file DiscreteHausdorffDistance.h.
PointPairDistance geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::minPtDist private
Definition at line 213 of file DiscreteHausdorffDistance.h.
std::size_t geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::numSubSegs private
Definition at line 215 of file DiscreteHausdorffDistance.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/distance/DiscreteHausdorffDistance.h
/home/vicky/potree/geos/vicky/src/algorithm/distance/DiscreteHausdorffDistance.cpp