GEOS: geos::algorithm::locate::SimplePointInAreaLocator Class Reference
geos::algorithm::locate::SimplePointInAreaLocator Class Reference
Computes the location of points relative to an areal Geometry, using a simple O(n) algorithm.
#include <SimplePointInAreaLocator.h>
Public Member Functions
SimplePointInAreaLocator (const geom::Geometry *g)
int locate (const geom::Coordinate *p) override
Static Public Member Functions
static int locate (const geom::Coordinate &p, const geom::Geometry *geom)
static bool containsPointInPolygon (const geom::Coordinate &p, const geom::Polygon *poly)
Static Private Member Functions
static bool containsPoint (const geom::Coordinate &p, const geom::Geometry *geom)
Private Attributes
const geom::Geometry * g
Detailed Description
Computes the location of points relative to an areal Geometry, using a simple O(n) algorithm.
This algorithm is suitable for use in cases where only one or a few points will be tested against a given area.
The algorithm used is only guaranteed to return correct results for points which are not on the boundary of the Geometry.
Version
1.7
Definition at line 47 of file SimplePointInAreaLocator.h.
Constructor & Destructor Documentation
geos::algorithm::locate::SimplePointInAreaLocator::SimplePointInAreaLocator (const geom::Geometry * g) inline
Definition at line 58 of file SimplePointInAreaLocator.h.
   : g( g)
   { }
Member Function Documentation
bool geos::algorithm::locate::SimplePointInAreaLocator::containsPoint (const geom::Coordinate & p, const geom::Geometry * geom) static private
Definition at line 49 of file SimplePointInAreaLocator.cpp.
References poly.
 {
   if (const Polygon *poly = dynamic_cast<const Polygon*>(geom))
   {
     return containsPointInPolygon(p, poly);
   }
   if (const GeometryCollection *col = dynamic_cast<const GeometryCollection*>(geom))
   {
     for (GeometryCollection::const_iterator
         it=col->begin(), endIt=col->end();
         it != endIt;
         ++it)
     {
       const Geometry *g2=*it;
       assert (g2!=geom);
       if (containsPoint(p,g2)) return true;
     }
   }
   return false;
 }
bool geos::algorithm::locate::SimplePointInAreaLocator::containsPointInPolygon (const geom::Coordinate & p, const geom::Polygon * poly) static
Definition at line 72 of file SimplePointInAreaLocator.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), and geos::geom::Polygon::isEmpty().
 {
   if (poly->isEmpty()) return false;
   const LineString *shell=poly->getExteriorRing();
   const CoordinateSequence *cl;
   cl = shell->getCoordinatesRO();
   if (!CGAlgorithms::isPointInRing(p,cl)) {
     return false;
   }
   // now test if the point lies in or on the holes
   for(size_t i=0, n=poly->getNumInteriorRing(); i<n; i++)
   {
     const LineString *hole = poly->getInteriorRingN(i);
     cl = hole->getCoordinatesRO();
     if (CGAlgorithms::isPointInRing(p,cl)) {
       return false;
     }
   }
   return true;
 }
int geos::algorithm::locate::SimplePointInAreaLocator::locate (const geom::Coordinate & p, const geom::Geometry * geom) static
locate is the main location function. It handles both single-element and multi-element Geometries. The algorithm for multi-element Geometries is more complex, since it has to take into account the boundaryDetermination rule
Definition at line 40 of file SimplePointInAreaLocator.cpp.
References geos::geom::Location::EXTERIOR, geos::geom::Location::INTERIOR, and geos::geom::Geometry::isEmpty().
Referenced by geos::geomgraph::EdgeEndStar::getLocation(), and geos::geom::prep::PreparedPolygonPredicate::isAnyTargetComponentInAreaTest().
 {
   if (geom->isEmpty()) return Location::EXTERIOR;
   if (containsPoint(p,geom))
     return Location::INTERIOR;
   return Location::EXTERIOR;
 }
int geos::algorithm::locate::SimplePointInAreaLocator::locate (const geom::Coordinate * p) inline override virtual
Determines the Location of a point in an areal Geometry.
Parameters
p the point to test
Returns
the location of the point in the geometry
Implements geos::algorithm::locate::PointOnGeometryLocator.
Definition at line 62 of file SimplePointInAreaLocator.h.
   {
     return locate( *p, g);
   }
Member Data Documentation
const geom::Geometry* geos::algorithm::locate::SimplePointInAreaLocator::g private
Definition at line 72 of file SimplePointInAreaLocator.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/locate/SimplePointInAreaLocator.h
/home/vicky/potree/geos/vicky/src/algorithm/locate/SimplePointInAreaLocator.cpp