GEOS: geos::simplify::TopologyPreservingSimplifier Class Reference
geos::simplify::TopologyPreservingSimplifier Class Reference
Simplifies a geometry, ensuring that the result is a valid geometry having the same dimension and number of components as the input.
#include <TopologyPreservingSimplifier.h>
Public Member Functions
TopologyPreservingSimplifier (const geom::Geometry *geom)
void setDistanceTolerance (double tolerance)
Sets the distance tolerance for the simplification.
std::unique_ptr< geom::Geometry > getResultGeometry ()
Static Public Member Functions
static std::unique_ptr< geom::Geometry > simplify (const geom::Geometry *geom, double tolerance)
Private Attributes
const geom::Geometry * inputGeom
std::unique_ptr< TaggedLinesSimplifier > lineSimplifier
Detailed Description
Simplifies a geometry, ensuring that the result is a valid geometry having the same dimension and number of components as the input.
The simplification uses a maximum distance difference algorithm similar to the one used in the Douglas-Peucker algorithm.
In particular, if the input is an areal geometry (Polygon or MultiPolygon)
The result has the same number of shells and holes (rings) as the input, in the same order
The result rings touch at no more than the number of touching point in the input (although they may touch at fewer points)
Definition at line 58 of file TopologyPreservingSimplifier.h.
Constructor & Destructor Documentation
geos::simplify::TopologyPreservingSimplifier::TopologyPreservingSimplifier (const geom::Geometry * geom)
Definition at line 274 of file TopologyPreservingSimplifier.cpp.
   :
   inputGeom(geom),
   lineSimplifier(new TaggedLinesSimplifier())
 {
 }
Member Function Documentation
std::unique_ptr< geom::Geometry > geos::simplify::TopologyPreservingSimplifier::getResultGeometry ()
Definition at line 296 of file TopologyPreservingSimplifier.cpp.
References geos::geom::Geometry::apply_ro(), geos::geom::Geometry::clone(), inputGeom, geos::geom::Geometry::isEmpty(), lineSimplifier, and linestringMap.
Referenced by simplify().
 {
   // empty input produces an empty result
   if (inputGeom->isEmpty()) return std::unique_ptr<Geometry>(inputGeom->clone());
   LinesMap linestringMap;
   std::unique_ptr<geom::Geometry> result;
   try {
     LineStringMapBuilderFilter lsmbf(linestringMap);
     inputGeom->apply_ro(&lsmbf);
 #if GEOS_DEBUG
   std::cerr << "LineStringMapBuilderFilter applied, "
             << " lineStringMap contains "
             << linestringMap.size() << " elements\n";
 #endif
     LinesMapValueIterator begin(linestringMap.begin());
     LinesMapValueIterator end(linestringMap.end());
     lineSimplifier->simplify(begin, end);
 #if GEOS_DEBUG
   std::cerr << "all TaggedLineString simplified\n";
 #endif
     LineStringTransformer trans(linestringMap);
     result = trans.transform(inputGeom);
 #if GEOS_DEBUG
   std::cerr << "inputGeom transformed\n";
 #endif
   } catch (...) {
     for (LinesMap::iterator
         it = linestringMap.begin(),
         itEnd = linestringMap.end();
         it != itEnd;
         ++it)
     {
       delete it->second;
     }
     throw;
   }
   for (LinesMap::iterator
       it = linestringMap.begin(),
       itEnd = linestringMap.end();
       it != itEnd;
       ++it)
   {
     delete it->second;
   }
 #if GEOS_DEBUG
   std::cerr << "returning result\n";
 #endif
   return result;
 }
void geos::simplify::TopologyPreservingSimplifier::setDistanceTolerance (double tolerance)
Sets the distance tolerance for the simplification.
All vertices in the simplified geometry will be within this distance of the original geometry. The tolerance value must be non-negative. A tolerance value of zero is effectively a no-op.
Parameters
distanceTolerance the approximation tolerance to use
Definition at line 283 of file TopologyPreservingSimplifier.cpp.
References lineSimplifier.
Referenced by simplify().
 {
   using geos::util::IllegalArgumentException;
   if ( d < 0.0 )
     throw IllegalArgumentException("Tolerance must be non-negative");
   lineSimplifier->setDistanceTolerance(d);
 }
std::unique_ptr< geom::Geometry > geos::simplify::TopologyPreservingSimplifier::simplify (const geom::Geometry * geom, double tolerance) static
Definition at line 264 of file TopologyPreservingSimplifier.cpp.
References getResultGeometry(), and setDistanceTolerance().
Referenced by geos::geom::BinaryOp().
 {
   TopologyPreservingSimplifier tss(geom);
         tss.setDistanceTolerance(tolerance);
   return tss.getResultGeometry();
 }
Member Data Documentation
const geom::Geometry* geos::simplify::TopologyPreservingSimplifier::inputGeom private
Definition at line 85 of file TopologyPreservingSimplifier.h.
Referenced by getResultGeometry().
std::unique_ptr<TaggedLinesSimplifier> geos::simplify::TopologyPreservingSimplifier::lineSimplifier private
Definition at line 87 of file TopologyPreservingSimplifier.h.
Referenced by getResultGeometry(), and setDistanceTolerance().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/simplify/TopologyPreservingSimplifier.h
/home/vicky/potree/geos/vicky/src/simplify/TopologyPreservingSimplifier.cpp