GEOS: geos::linearref::ExtractLineByLocation Class Reference
geos::linearref::ExtractLineByLocation Class Reference
#include <ExtractLineByLocation.h>
Public Member Functions
ExtractLineByLocation (const geom::Geometry *line)
geom::Geometry * extract (const LinearLocation &start, const LinearLocation &end)
Static Public Member Functions
static geom::Geometry * extract (const geom::Geometry *line, const LinearLocation &start, const LinearLocation &end)
Private Member Functions
geom::Geometry * reverse (const geom::Geometry *linear)
geom::LineString * computeLine (const LinearLocation &start, const LinearLocation &end)
geom::Geometry * computeLinear (const LinearLocation &start, const LinearLocation &end)
Private Attributes
const geom::Geometry * line
Detailed Description
Extracts the subline of a linear Geometry between two LinearLocations on the line.
Definition at line 36 of file ExtractLineByLocation.h.
Constructor & Destructor Documentation
geos::linearref::ExtractLineByLocation::ExtractLineByLocation (const geom::Geometry * line)
Definition at line 50 of file ExtractLineByLocation.cpp.
                                                                  :
     line(line) {}
Member Function Documentation
LineString * geos::linearref::ExtractLineByLocation::computeLine (const LinearLocation & start, const LinearLocation & end) private
Assumes input is valid (e.g. start <= end)
Parameters
start
end
Returns
a linear geometry
Ensure there is enough coordinates to build a valid line. Make a 2-point line with duplicate coordinates, if necessary. There will always be at least one coordinate in the coordList.
Definition at line 88 of file ExtractLineByLocation.cpp.
References geos::geom::CoordinateArraySequence::add(), geos::geom::GeometryFactory::createLineString(), geos::linearref::LinearLocation::getCoordinate(), geos::geom::Geometry::getCoordinates(), geos::geom::Geometry::getFactory(), geos::linearref::LinearLocation::getSegmentFraction(), geos::linearref::LinearLocation::getSegmentIndex(), geos::linearref::LinearLocation::isVertex(), line, and geos::geom::CoordinateSequence::size().
 {
   CoordinateSequence* coordinates = line->getCoordinates();
   CoordinateArraySequence newCoordinateArray;
     const unsigned int indexStep = 1;
   unsigned int startSegmentIndex = start.getSegmentIndex();
   if (start.getSegmentFraction() > 0.0)
     {
     startSegmentIndex += indexStep;
     }
     unsigned int lastSegmentIndex = end.getSegmentIndex();
   if (end.getSegmentFraction() == 1.0)
     {
     lastSegmentIndex += indexStep;
     }
   if (lastSegmentIndex >= coordinates->size())
     {
         assert(coordinates->size() > 0);
         lastSegmentIndex = static_cast<unsigned int>(coordinates->size() - indexStep);
     }
   if (! start.isVertex())
     {
     newCoordinateArray.add(start.getCoordinate(line));
     }
   for (unsigned int i = startSegmentIndex; i <= lastSegmentIndex; i++)
   {
     newCoordinateArray.add((*coordinates)[i]);
   }
   if (! end.isVertex())
     {
     newCoordinateArray.add(end.getCoordinate(line));
     }
   // ensure there is at least one coordinate in the result
   if (newCoordinateArray.size() == 0)
     {
     newCoordinateArray.add(start.getCoordinate(line));
     }
   if (newCoordinateArray.size() <= 1)
   {
     newCoordinateArray.add(newCoordinateArray[0]);
   }
   return line->getFactory()->createLineString(newCoordinateArray);
 }
Geometry * geos::linearref::ExtractLineByLocation::computeLinear (const LinearLocation & start, const LinearLocation & end) private
Assumes input is valid (e.g. start <= end)
Parameters
start
end
Returns
a linear geometry
Definition at line 147 of file ExtractLineByLocation.cpp.
References geos::linearref::LinearLocation::compareLocationValues(), geos::linearref::LinearLocation::getCoordinate(), geos::geom::Geometry::getFactory(), geos::linearref::LinearIterator::hasNext(), geos::linearref::LinearLocation::isVertex(), line, and geos::linearref::LinearGeometryBuilder::setFixInvalidLines().
Referenced by extract().
 {
   LinearGeometryBuilder builder(line->getFactory());
   builder.setFixInvalidLines(true);
   if (! start.isVertex())
   {
     builder.add(start.getCoordinate(line));
   }
   for (LinearIterator it(line, start); it.hasNext(); it.next())
   {
     if (end.compareLocationValues(it.getComponentIndex(), it.getVertexIndex(), 0.0) < 0)
     {
       break;
     }
     Coordinate pt = it.getSegmentStart();
     builder.add(pt);
     if (it.isEndOfLine())
     {
       builder.endLine();
     }
   }
   if (! end.isVertex())
   {
     builder.add(end.getCoordinate(line));
   }
   return builder.getGeometry();
 }
Geometry * geos::linearref::ExtractLineByLocation::extract (const geom::Geometry * line, const LinearLocation & start, const LinearLocation & end) static
Computes the subline of a LineString between two LineStringLocations on the line. If the start location is after the end location, the computed geometry is reversed.
Parameters
line the line to use as the baseline
start the start location
end the end location
Returns
the extracted subline
Definition at line 44 of file ExtractLineByLocation.cpp.
References extract().
Referenced by extract(), geos::linearref::LengthIndexedLine::extractLine(), and geos::linearref::LocationIndexedLine::extractLine().
 {
   ExtractLineByLocation ls(line);
   return ls.extract(start, end);
 }
Geometry * geos::linearref::ExtractLineByLocation::extract (const LinearLocation & start, const LinearLocation & end)
Extracts a subline of the input. If end < start the linear geometry computed will be reversed.
Parameters
start the start location
end the end location
Returns
a linear geometry
Definition at line 54 of file ExtractLineByLocation.cpp.
References geos::linearref::LinearLocation::compareTo(), computeLinear(), and reverse().
 {
   if (end.compareTo(start) < 0)
   {
     Geometry* backwards = computeLinear(end, start);
     Geometry* forwards = reverse(backwards);
     delete backwards;
     return forwards;
   }
   return computeLinear(start, end);
 }
Geometry * geos::linearref::ExtractLineByLocation::reverse (const geom::Geometry * linear) private
Definition at line 66 of file ExtractLineByLocation.cpp.
References geos::geom::MultiLineString::reverse(), and geos::geom::LineString::reverse().
Referenced by extract().
 {
   const LineString* ls = dynamic_cast<const LineString *>(linear);
   if (ls)
   {
     return ls->reverse();
   }
   else
   {
     const MultiLineString* mls = dynamic_cast<const MultiLineString *>(linear);
     if (mls)
     {
       return mls->reverse();
     }
     else
     {
       assert(!static_cast<bool>("non-linear geometry encountered"));
             return nullptr;
     }
   }
 }
Member Data Documentation
const geom::Geometry* geos::linearref::ExtractLineByLocation::line private
Definition at line 40 of file ExtractLineByLocation.h.
Referenced by computeLine(), and computeLinear().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/linearref/ExtractLineByLocation.h
/home/vicky/potree/geos/vicky/src/linearref/ExtractLineByLocation.cpp