GEOS: geos::geom::GeometryComponentFilter Class Reference
geos::geom::GeometryComponentFilter Class Reference
#include <GeometryComponentFilter.h>
Public Member Functions
virtual void filter_rw (Geometry *geom)
virtual void filter_ro (const Geometry *geom)
virtual ~GeometryComponentFilter ()
Detailed Description
Geometry classes support the concept of applying a GeometryComponentFilter filter to the Geometry. The filter is applied to every component of the Geometry which is itself a Geometry. A GeometryComponentFilter filter can either record information about the Geometry or change the Geometry in some way. GeometryComponentFilter is an example of the Gang-of-Four Visitor pattern.
Definition at line 43 of file GeometryComponentFilter.h.
Constructor & Destructor Documentation
virtual geos::geom::GeometryComponentFilter::~GeometryComponentFilter () inline virtual
Definition at line 55 of file GeometryComponentFilter.h.
 {}
Member Function Documentation
void geos::geom::GeometryComponentFilter::filter_ro (const Geometry * geom) virtual
Reimplemented in geos::operation::polygonize::Polygonizer::LineStringAdder, geos::geom::util::LinearComponentExtracter, and geos::geom::util::ComponentCoordinateExtracter.
Definition at line 31 of file GeometryComponentFilter.cpp.
References geos::ignore_unused_variable_warning().
Referenced by geos::geom::Point::apply_ro(), geos::geom::GeometryCollection::apply_ro(), geos::geom::Polygon::apply_ro(), geos::geom::LineString::apply_ro(), and geos::geom::Geometry::apply_ro().
 {
   ::geos::ignore_unused_variable_warning(geom);
   assert(0);
 }
void geos::geom::GeometryComponentFilter::filter_rw (Geometry * geom) virtual
Performs an operation with or on geom.
Parameters
geom a Geometry to which the filter is applied.
Reimplemented in geos::geom::Geometry::GeometryChangedFilter, geos::geom::util::LinearComponentExtracter, and geos::geom::util::ComponentCoordinateExtracter.
Definition at line 25 of file GeometryComponentFilter.cpp.
References geos::ignore_unused_variable_warning().
Referenced by geos::geom::Point::apply_rw(), geos::geom::GeometryCollection::apply_rw(), geos::geom::Polygon::apply_rw(), geos::geom::LineString::apply_rw(), and geos::geom::Geometry::apply_rw().
 {
   ::geos::ignore_unused_variable_warning(geom);
   assert(0);
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/GeometryComponentFilter.h
/home/vicky/potree/geos/vicky/src/geom/GeometryComponentFilter.cpp