GEOS: geos::noding::snapround::MCIndexSnapRounder Class Reference
geos::noding::snapround::MCIndexSnapRounder Class Reference
Uses Snap Rounding to compute a rounded, fully noded arrangement from a set of SegmentString.
#include <MCIndexSnapRounder.h>
Public Member Functions
MCIndexSnapRounder (const geom::PrecisionModel &nPm)
std::vector< SegmentString * > * getNodedSubstrings () const override
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
void computeNodes (std::vector< SegmentString * > *segStrings) override
Computes the noding for a collection of SegmentStrings.
void computeVertexSnaps (std::vector< SegmentString * > &edges)
Private Member Functions
void snapRound (MCIndexNoder &noder, std::vector< SegmentString * > *segStrings)
void findInteriorIntersections (MCIndexNoder &noder, std::vector< SegmentString * > *segStrings, std::vector< geom::Coordinate > &intersections)
void computeIntersectionSnaps (std::vector< geom::Coordinate > &snapPts)
void computeVertexSnaps (NodedSegmentString *e)
void checkCorrectness (std::vector< SegmentString * > &inputSegmentStrings)
MCIndexSnapRounder (const MCIndexSnapRounder &other)=delete
MCIndexSnapRounder & operator= (const MCIndexSnapRounder &rhs)=delete
Private Attributes
const geom::PrecisionModel & pm
externally owned
algorithm::LineIntersector li
double scaleFactor
std::vector< SegmentString * > * nodedSegStrings
std::unique_ptr< MCIndexPointSnapper > pointSnapper
Detailed Description
Uses Snap Rounding to compute a rounded, fully noded arrangement from a set of SegmentString.
Implements the Snap Rounding technique described in Hobby, Guibas & Marimont, and Goodrich et al.
Snap Rounding assumes that all vertices lie on a uniform grid (hence the precision model of the input must be fixed precision, and all the input vertices must be rounded to that precision).
This implementation uses a monotone chains and a spatial index to speed up the intersection tests.
This implementation appears to be fully robust using an integer precision model.
It will function with non-integer precision models, but the results are not 100% guaranteed to be correctly noded.
Definition at line 74 of file MCIndexSnapRounder.h.
Constructor & Destructor Documentation
geos::noding::snapround::MCIndexSnapRounder::MCIndexSnapRounder (const geom::PrecisionModel & nPm) inline
Definition at line 78 of file MCIndexSnapRounder.h.
     :
     pm(nPm),
     scaleFactor(nPm.getScale()),
     pointSnapper(nullptr)
   {
     li.setPrecisionModel(&pm);
   }
geos::noding::snapround::MCIndexSnapRounder::MCIndexSnapRounder (const MCIndexSnapRounder & other) private delete
Member Function Documentation
void geos::noding::snapround::MCIndexSnapRounder::checkCorrectness (std::vector< SegmentString * > & inputSegmentStrings) private
Definition at line 126 of file MCIndexSnapRounder.cpp.
References geos::noding::NodingValidator::checkValid().
 {
   unique_ptr<SegmentString::NonConstVect> resultSegStrings(
     NodedSegmentString::getNodedSubstrings(inputSegmentStrings)
   );
   NodingValidator nv(*(resultSegStrings.get()));
   try {
     nv.checkValid();
   } catch (const std::exception &ex) {
     std::cerr << ex.what() << std::endl;
     throw;
   }
 }
void geos::noding::snapround::MCIndexSnapRounder::computeIntersectionSnaps (std::vector< geom::Coordinate > & snapPts) private
Computes nodes introduced as a result of snapping segments to snap points (hot pixels)
Definition at line 54 of file MCIndexSnapRounder.cpp.
 {
   for (vector<Coordinate>::iterator
       it=snapPts.begin(), itEnd=snapPts.end();
       it!=itEnd;
       ++it)
   {
     Coordinate& snapPt = *it;
     HotPixel hotPixel(snapPt, scaleFactor, li);
     pointSnapper->snap(hotPixel);
   }
 }
void geos::noding::snapround::MCIndexSnapRounder::computeNodes (std::vector< SegmentString * > * segStrings) override virtual
Computes the noding for a collection of SegmentStrings.
Some Noders may add all these nodes to the input SegmentStrings; others may only add some or none at all.
Parameters
segStrings a collection of SegmentStrings to node
Implements geos::noding::Noder.
Definition at line 111 of file MCIndexSnapRounder.cpp.
References geos::noding::MCIndexNoder::getIndex().
 {
   nodedSegStrings = inputSegmentStrings;
   MCIndexNoder noder;
   pointSnapper.release(); // let it leak ?!
   pointSnapper.reset(new MCIndexPointSnapper(noder.getIndex()));
   snapRound(noder, inputSegmentStrings);
   // testing purposes only - remove in final version
   assert(nodedSegStrings == inputSegmentStrings);
   //checkCorrectness(*inputSegmentStrings);
 }
void geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps (std::vector< SegmentString * > & edges)
Computes nodes introduced as a result of snapping segments to vertices of other segments
Parameters
edges the list of segment strings to snap together NOTE: they must be instances of NodedSegmentString, or an assertion will fail.
Definition at line 85 of file MCIndexSnapRounder.cpp.
 {
   SegmentString::NonConstVect::iterator i=edges.begin(), e=edges.end();
   for (; i!=e; ++i)
   {
     NodedSegmentString* edge0 =
       dynamic_cast<NodedSegmentString*>(*i);
     assert(edge0);
     computeVertexSnaps(edge0);
   }
 }
void geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps (NodedSegmentString * e) private
Performs a brute-force comparison of every segment in each SegmentString. This has n^2 performance.
Definition at line 69 of file MCIndexSnapRounder.cpp.
References geos::noding::NodedSegmentString::addIntersection(), geos::noding::NodedSegmentString::getCoordinates(), and geos::geom::CoordinateSequence::size().
 {
   CoordinateSequence& pts0 = *(e->getCoordinates());
   for (unsigned int i=0, n=static_cast<unsigned int>(pts0.size()-1); i<n; ++i)
   {
     HotPixel hotPixel(pts0[i], scaleFactor, li);
     bool isNodeAdded = pointSnapper->snap(hotPixel, e, i);
     // if a node is created for a vertex, that vertex must be noded too
     if (isNodeAdded) {
       e->addIntersection(pts0[i], i);
     }
   }
 }
void geos::noding::snapround::MCIndexSnapRounder::findInteriorIntersections (MCIndexNoder & noder, std::vector< SegmentString * > * segStrings, std::vector< geom::Coordinate > & intersections) private
Computes all interior intersections in the collection of SegmentStrings, and push their Coordinate to the provided vector.
Does NOT node the segStrings.
Definition at line 43 of file MCIndexSnapRounder.cpp.
References geos::noding::MCIndexNoder::computeNodes(), and geos::noding::SinglePassNoder::setSegmentIntersector().
 {
   IntersectionFinderAdder intFinderAdder(li, intersections);
   noder.setSegmentIntersector(&intFinderAdder);
   noder.computeNodes(segStrings);
 }
std::vector<SegmentString*>* geos::noding::snapround::MCIndexSnapRounder::getNodedSubstrings () const inline override virtual
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
Returns
a newly allocated std::vector of const SegmentStrings. Caller is responsible to delete container and elements.
Implements geos::noding::Noder.
Definition at line 87 of file MCIndexSnapRounder.h.
{
     return NodedSegmentString::getNodedSubstrings(*nodedSegStrings);
   }
MCIndexSnapRounder& geos::noding::snapround::MCIndexSnapRounder::operator= (const MCIndexSnapRounder & rhs) private delete
void geos::noding::snapround::MCIndexSnapRounder::snapRound (MCIndexNoder & noder, std::vector< SegmentString * > * segStrings) private
Definition at line 99 of file MCIndexSnapRounder.cpp.
 {
   vector<Coordinate> intersections;
   findInteriorIntersections(noder, segStrings, intersections);
   computeIntersectionSnaps(intersections);
   computeVertexSnaps(*segStrings);
 }
Member Data Documentation
algorithm::LineIntersector geos::noding::snapround::MCIndexSnapRounder::li private
Definition at line 108 of file MCIndexSnapRounder.h.
std::vector<SegmentString*>* geos::noding::snapround::MCIndexSnapRounder::nodedSegStrings private
Definition at line 112 of file MCIndexSnapRounder.h.
const geom::PrecisionModel& geos::noding::snapround::MCIndexSnapRounder::pm private
externally owned
Definition at line 106 of file MCIndexSnapRounder.h.
std::unique_ptr<MCIndexPointSnapper> geos::noding::snapround::MCIndexSnapRounder::pointSnapper private
Definition at line 114 of file MCIndexSnapRounder.h.
double geos::noding::snapround::MCIndexSnapRounder::scaleFactor private
Definition at line 110 of file MCIndexSnapRounder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/snapround/MCIndexSnapRounder.h
/home/vicky/potree/geos/vicky/src/noding/snapround/MCIndexSnapRounder.cpp