GEOS: geos::operation::overlay::ElevationMatrixFilter Class Reference
geos::operation::overlay::ElevationMatrixFilter Class Reference
#include <ElevationMatrix.h>
Public Member Functions
ElevationMatrixFilter (ElevationMatrix &em)
~ElevationMatrixFilter () override
void filter_rw (geom::Coordinate *c) const override
void filter_ro (const geom::Coordinate *c) override
Private Member Functions
ElevationMatrixFilter (const ElevationMatrixFilter &other)=delete
ElevationMatrixFilter & operator= (const ElevationMatrixFilter &rhs)=delete
Private Attributes
ElevationMatrix & em
double avgElevation
Detailed Description
Definition at line 61 of file ElevationMatrix.h.
Constructor & Destructor Documentation
geos::operation::overlay::ElevationMatrixFilter::ElevationMatrixFilter (ElevationMatrix & em)
Definition at line 48 of file ElevationMatrix.cpp.
                                                                   :
   em(newEm)
 { }
geos::operation::overlay::ElevationMatrixFilter::~ElevationMatrixFilter () override
Definition at line 52 of file ElevationMatrix.cpp.
 { }
geos::operation::overlay::ElevationMatrixFilter::ElevationMatrixFilter (const ElevationMatrixFilter & other) private delete
Member Function Documentation
void geos::operation::overlay::ElevationMatrixFilter::filter_ro (const geom::Coordinate *) override virtual
Performs an operation with coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented from geos::geom::CoordinateFilter.
Definition at line 81 of file ElevationMatrix.cpp.
References geos::operation::overlay::ElevationMatrix::add(), em, and geos::geom::Coordinate::toString().
 {
 #if GEOS_DEBUG
   cerr<<"ElevationMatrixFilter::filter_ro("<<c->toString()<<") called"
     <<endl;
 #endif
   em.add(*c);
 }
void geos::operation::overlay::ElevationMatrixFilter::filter_rw (geom::Coordinate *) const override virtual
Performs an operation on coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented from geos::geom::CoordinateFilter.
Definition at line 56 of file ElevationMatrix.cpp.
References avgElevation, em, geos::operation::overlay::ElevationMatrixCell::getAvg(), geos::operation::overlay::ElevationMatrix::getAvgElevation(), geos::operation::overlay::ElevationMatrix::getCell(), geos::geom::Coordinate::toString(), and geos::geom::Coordinate::z.
 {
 #if GEOS_DEBUG
   cerr<<"ElevationMatrixFilter::filter_rw("<<c->toString()<<") called"
     <<endl;
 #endif
   // already has a Z value, nothing to do
   if ( ! ISNAN(c->z) ) return;
   double avgElevation = em.getAvgElevation();
   try {
     const ElevationMatrixCell &emc = em.getCell(*c);
     c->z = emc.getAvg();
     if ( ISNAN(c->z) ) c->z = avgElevation;
 #if GEOS_DEBUG
     cerr<<"  z set to "<<c->z<<endl;
 #endif
   } catch (const util::IllegalArgumentException& /* ex */) {
     c->z = avgElevation;
   }
 }
ElevationMatrixFilter& geos::operation::overlay::ElevationMatrixFilter::operator= (const ElevationMatrixFilter & rhs) private delete
Member Data Documentation
double geos::operation::overlay::ElevationMatrixFilter::avgElevation private
Definition at line 70 of file ElevationMatrix.h.
Referenced by filter_rw().
ElevationMatrix& geos::operation::overlay::ElevationMatrixFilter::em private
Definition at line 69 of file ElevationMatrix.h.
Referenced by filter_ro(), and filter_rw().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/ElevationMatrix.h
/home/vicky/potree/geos/vicky/src/operation/overlay/ElevationMatrix.cpp