GEOS: geos::operation::predicate::SegmentIntersectionTester Class Reference
geos::operation::predicate::SegmentIntersectionTester Class Reference
Tests if any line segments in two sets of CoordinateSequences intersect.
#include <SegmentIntersectionTester.h>
Public Member Functions
SegmentIntersectionTester ()
bool hasIntersectionWithLineStrings (const geom::LineString &line, const std::vector< const geom::LineString * > &lines)
bool hasIntersection (const geom::LineString &line, const geom::LineString &testLine)
bool hasIntersectionWithEnvelopeFilter (const geom::LineString &line, const geom::LineString &testLine)
Private Attributes
algorithm::LineIntersector li
For purposes of intersection testing, don't need to set precision model.
bool hasIntersectionVar
geom::Coordinate pt10
geom::Coordinate pt11
geom::Coordinate pt00
geom::Coordinate pt01
Detailed Description
Tests if any line segments in two sets of CoordinateSequences intersect.
The algorithm is optimized for use when the first input has smaller extent than the set of test lines. The code is short-circuited to return as soon an intersection is found.
Definition at line 48 of file SegmentIntersectionTester.h.
Constructor & Destructor Documentation
geos::operation::predicate::SegmentIntersectionTester::SegmentIntersectionTester () inline
Definition at line 68 of file SegmentIntersectionTester.h.
 : hasIntersectionVar(false) {}
Member Function Documentation
bool geos::operation::predicate::SegmentIntersectionTester::hasIntersection (const geom::LineString & line, const geom::LineString & testLine)
Definition at line 47 of file SegmentIntersectionTester.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), and geos::geom::CoordinateSequence::getSize().
 {
   typedef std::size_t size_type;
   const CoordinateSequence &seq0 = *(line.getCoordinatesRO());
   size_type seq0size = seq0.getSize();
   const CoordinateSequence &seq1 = *(testLine.getCoordinatesRO());
   size_type seq1size = seq1.getSize();
   for (size_type i = 1; i<seq0size && !hasIntersectionVar; ++i)
   {
     seq0.getAt(i - 1, pt00);
     seq0.getAt(i, pt01);
     for (size_type j = 1; j < seq1size && !hasIntersectionVar; ++j)
     {
       seq1.getAt(j-1, pt10);
       seq1.getAt(j, pt11);
       li.computeIntersection(pt00, pt01, pt10, pt11);
       if (li.hasIntersection()) hasIntersectionVar = true;
     }
   }
   return hasIntersectionVar;
 }
bool geos::operation::predicate::SegmentIntersectionTester::hasIntersectionWithEnvelopeFilter (const geom::LineString & line, const geom::LineString & testLine)
Tests the segments of a LineString against the segs in another LineString for intersection. Uses the envelope of the query LineString to filter before testing segments directly. This is optimized for the case when the query LineString is a rectangle.
Testing shows this is somewhat faster than not checking the envelope.
Parameters
line
testLine
Returns
Definition at line 77 of file SegmentIntersectionTester.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::CoordinateSequence::getSize(), and geos::geom::Envelope::intersects().
 {
   typedef std::size_t size_type;
   const CoordinateSequence &seq0 = *(line.getCoordinatesRO());
   size_type seq0size = seq0.getSize();
   const CoordinateSequence &seq1 = *(testLine.getCoordinatesRO());
   size_type seq1size = seq1.getSize();
   const Envelope* lineEnv = line.getEnvelopeInternal();
   typedef std::size_t size_type;
   for (size_type i = 1; i<seq1size && !hasIntersectionVar; ++i)
   {
     seq1.getAt(i-1, pt10);
     seq1.getAt(i, pt11);
     // skip test if segment does not intersect query envelope
     if (! lineEnv->intersects(Envelope(pt10, pt11))) continue;
     for (size_type j = 1; j < seq0size && !hasIntersectionVar; ++j)
     {
       seq0.getAt(j - 1, pt00);
       seq0.getAt(j, pt01);
       li.computeIntersection(pt00, pt01, pt10, pt11);
       if (li.hasIntersection()) hasIntersectionVar = true;
     }
   }
   return hasIntersectionVar;
 }
bool geos::operation::predicate::SegmentIntersectionTester::hasIntersectionWithLineStrings (const geom::LineString & line, const std::vector< const geom::LineString * > & lines)
Definition at line 32 of file SegmentIntersectionTester.cpp.
Referenced by geos::operation::predicate::LineIntersectsVisitor::computeSegmentIntersection().
 {
   hasIntersectionVar = false;
   for (size_t i=0, n=lines.size(); i<n; ++i )
   {
     const LineString *testLine = lines[i];
     hasIntersection(line, *testLine);
     if (hasIntersectionVar) break;
   }
   return hasIntersectionVar;
 }
Member Data Documentation
bool geos::operation::predicate::SegmentIntersectionTester::hasIntersectionVar private
Definition at line 58 of file SegmentIntersectionTester.h.
algorithm::LineIntersector geos::operation::predicate::SegmentIntersectionTester::li private
For purposes of intersection testing, don't need to set precision model.
Definition at line 56 of file SegmentIntersectionTester.h.
geom::Coordinate geos::operation::predicate::SegmentIntersectionTester::pt00 private
Definition at line 62 of file SegmentIntersectionTester.h.
geom::Coordinate geos::operation::predicate::SegmentIntersectionTester::pt01 private
Definition at line 63 of file SegmentIntersectionTester.h.
geom::Coordinate geos::operation::predicate::SegmentIntersectionTester::pt10 private
Definition at line 60 of file SegmentIntersectionTester.h.
geom::Coordinate geos::operation::predicate::SegmentIntersectionTester::pt11 private
Definition at line 61 of file SegmentIntersectionTester.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/predicate/SegmentIntersectionTester.h
/home/vicky/potree/geos/vicky/src/operation/predicate/SegmentIntersectionTester.cpp