GEOS: geos::triangulate::quadedge::QuadEdge Class Reference
geos::triangulate::quadedge::QuadEdge Class Reference
#include <QuadEdge.h>
Public Member Functions
virtual ~QuadEdge ()
virtual void free ()
const QuadEdge & getPrimary () const
virtual void setData (void *data)
virtual void * getData ()
void remove ()
bool isLive ()
void setNext (QuadEdge *next)
QuadEdge & rot () const
QuadEdge & invRot () const
QuadEdge & sym () const
QuadEdge & oNext () const
QuadEdge & oPrev () const
QuadEdge & dNext () const
QuadEdge & dPrev () const
QuadEdge & lNext () const
QuadEdge & lPrev () const
QuadEdge & rNext ()
QuadEdge & rPrev ()
void setOrig (const Vertex &o)
void setDest (const Vertex &d)
const Vertex & orig () const
const Vertex & dest () const
double getLength () const
bool equalsNonOriented (const QuadEdge &qe) const
bool equalsOriented (const QuadEdge &qe) const
std::unique_ptr< geom::LineSegment > toLineSegment () const
Static Public Member Functions
static std::unique_ptr< QuadEdge > makeEdge (const Vertex &o, const Vertex &d)
static std::unique_ptr< QuadEdge > connect (QuadEdge &a, QuadEdge &b)
static void splice (QuadEdge &a, QuadEdge &b)
static void swap (QuadEdge &e)
Private Member Functions
QuadEdge ()
Private Attributes
QuadEdge * _rot
Vertex vertex
QuadEdge * next
void * data
bool isAlive
Detailed Description
A class that represents the edge data structure which implements the quadedge algebra. The quadedge algebra was described in a well-known paper by Guibas and Stolfi, "Primitives for the manipulation of general subdivisions and the computation of Voronoi diagrams", ACM Transactions on Graphics, 4(2), 1985, 75-123.
Each edge object is part of a quartet of 4 edges, linked via their _rot references. Any edge in the group may be accessed using a series of rot() operations. Quadedges in a subdivision are linked together via their next references. The linkage between the quadedge quartets determines the topology of the subdivision.
The edge class does not contain separate information for vertice or faces; a vertex is implicitly defined as a ring of edges (created using the next field).
Author
JTS: David Skea
JTS: Martin Davis
Benjamin Campbell
Definition at line 51 of file QuadEdge.h.
Constructor & Destructor Documentation
geos::triangulate::quadedge::QuadEdge::QuadEdge () private
Quadedges must be made using makeEdge, to ensure proper construction.
Definition at line 92 of file QuadEdge.cpp.
                    : _rot(nullptr), vertex(), next(nullptr), data(nullptr), isAlive(true)
 { }
geos::triangulate::quadedge::QuadEdge::~QuadEdge () virtual
Definition at line 95 of file QuadEdge.cpp.
 {
 }
Member Function Documentation
std::unique_ptr< QuadEdge > geos::triangulate::quadedge::QuadEdge::connect (QuadEdge & a, QuadEdge & b) static
Creates a new QuadEdge connecting the destination of a to the origin of b, in such a way that all three have the same left face after the connection is complete. Additionally, the data pointers of the new edge are set.
Returns
the new QuadEdge* The caller is reponsible for freeing the returned pointer
Definition at line 54 of file QuadEdge.cpp.
References dest(), lNext(), and orig().
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::connect().
 {
   std::unique_ptr<QuadEdge> q0 = makeEdge(a.dest(), b.orig());
   splice(*q0, a.lNext());
   splice(q0->sym(), b);
   return q0;
 }
const Vertex& geos::triangulate::quadedge::QuadEdge::dest () const inline
Gets the vertex for the edge's destination
Returns
the destination vertex
Definition at line 317 of file QuadEdge.h.
Referenced by connect(), equalsOriented(), geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), getPrimary(), geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::isFrameBorderEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::isFrameEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::isOnEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::isVertexOfEdge(), geos::triangulate::quadedge::Vertex::leftOf(), geos::triangulate::quadedge::QuadEdgeSubdivision::locate(), geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge(), geos::triangulate::quadedge::Vertex::rightOf(), swap(), and toLineSegment().
{
     return sym().orig();
   }
QuadEdge& geos::triangulate::quadedge::QuadEdge::dNext () const inline
Gets the next CCW edge around (into) the destination of this edge.
Returns
the next destination edge.
Definition at line 233 of file QuadEdge.h.
References oNext(), and sym().
{
     return sym().oNext().sym();
   }
QuadEdge& geos::triangulate::quadedge::QuadEdge::dPrev () const inline
Gets the next CW edge around (into) the destination of this edge.
Returns
the previous destination edge.
Definition at line 242 of file QuadEdge.h.
References invRot(), and oNext().
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge().
{
     return invRot().oNext().invRot();
   }
bool geos::triangulate::quadedge::QuadEdge::equalsNonOriented (const QuadEdge & qe) const
Tests if this quadedge and another have the same line segment geometry, regardless of orientation.
Parameters
qe a quadege
Returns
true if the quadedges are based on the same line segment regardless of orientation
Definition at line 150 of file QuadEdge.cpp.
References equalsOriented(), and sym().
 {
   if (equalsOriented(qe))
     return true;
   if (equalsOriented(qe.sym()))
     return true;
   return false;
 }
bool geos::triangulate::quadedge::QuadEdge::equalsOriented (const QuadEdge & qe) const
Tests if this quadedge and another have the same line segment geometry with the same orientation.
Parameters
qe a quadege
Returns
true if the quadedges are based on the same line segment
Definition at line 160 of file QuadEdge.cpp.
References dest(), geos::geom::Coordinate::equals2D(), geos::triangulate::quadedge::Vertex::getCoordinate(), and orig().
Referenced by equalsNonOriented().
 {
   if (orig().getCoordinate().equals2D(qe.orig().getCoordinate())
       && dest().getCoordinate().equals2D(qe.dest().getCoordinate()))
     return true;
   return false;
 }
void geos::triangulate::quadedge::QuadEdge::free () virtual
Free the QuadEdge quartet associated with this QuadEdge by a connect() or makeEdge() call. DO NOT call this function on a QuadEdge that was not returned by connect() or makeEdge().
Definition at line 100 of file QuadEdge.cpp.
References _rot.
 {
   if(_rot)
   {
     if(_rot->_rot)
     {
       if(_rot->_rot->_rot)
       {
         delete _rot->_rot->_rot;
         _rot->_rot->_rot = nullptr;
       }
       delete _rot->_rot;
       _rot->_rot = nullptr;
     }
     delete _rot;
     _rot = nullptr;
   }
 }
void * geos::triangulate::quadedge::QuadEdge::getData () virtual
Gets the external data value for this edge.
Returns
the data object
Definition at line 135 of file QuadEdge.cpp.
References data.
 {
   return data;
 }
double geos::triangulate::quadedge::QuadEdge::getLength () const inline
Gets the length of the geometry of this quadedge.
Returns
the length of the quadedge
Definition at line 326 of file QuadEdge.h.
{
     return orig().getCoordinate().distance(dest().getCoordinate());
   }
const QuadEdge & geos::triangulate::quadedge::QuadEdge::getPrimary () const
Gets the primary edge of this quadedge and its sym. The primary edge is the one for which the origin and destination coordinates are ordered according to the standard Coordinate ordering
Returns
the primary quadedge
Definition at line 120 of file QuadEdge.cpp.
References dest(), orig(), and sym().
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::getPrimaryEdges().
 {
   if (orig().getCoordinate().compareTo(dest().getCoordinate()) <= 0)
     return *this;
   else
     return sym();
 }
QuadEdge& geos::triangulate::quadedge::QuadEdge::invRot () const inline
Gets the dual of this edge, directed from its left to its right.
Returns
the inverse rotated edge.
Definition at line 197 of file QuadEdge.h.
References sym().
Referenced by dPrev(), and rNext().
{
     return rot().sym();
   }
bool geos::triangulate::quadedge::QuadEdge::isLive () inline
Tests whether this edge has been deleted.
Returns
true if this edge has not been deleted.
Definition at line 164 of file QuadEdge.h.
Referenced by geos::triangulate::quadedge::LastFoundQuadEdgeLocator::locate().
{
     return isAlive;
   }
QuadEdge& geos::triangulate::quadedge::QuadEdge::lNext () const inline
Gets the CCW edge around the left face following this edge.
Returns
the next left face edge.
Definition at line 251 of file QuadEdge.h.
References oNext(), and rot().
Referenced by connect(), geos::triangulate::quadedge::QuadEdgeSubdivision::fetchTriangleToVisit(), geos::triangulate::quadedge::QuadEdgeSubdivision::getTriangleEdges(), geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::isFrameBorderEdge(), and swap().
{
     return invRot().oNext().rot();
   }
QuadEdge& geos::triangulate::quadedge::QuadEdge::lPrev () const inline
Gets the CCW edge around the left face before this edge.
Returns
the previous left face edge.
Definition at line 260 of file QuadEdge.h.
References sym().
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite().
{
     return oNext().sym();
   }
std::unique_ptr< QuadEdge > geos::triangulate::quadedge::QuadEdge::makeEdge (const Vertex & o, const Vertex & d) static
Creates a new QuadEdge quartet from Vertex o to Vertex d.
Parameters
o the origin Vertex
d the destination Vertex
Returns
the new QuadEdge* The caller is reponsible for freeing the returned pointer
Definition at line 28 of file QuadEdge.cpp.
References _rot, setDest(), setNext(), and setOrig().
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::initSubdiv(), and geos::triangulate::quadedge::QuadEdgeSubdivision::makeEdge().
 {
   QuadEdge *q0 = new QuadEdge();
   //q1-q3 are free()'d by q0
   QuadEdge *q1 = new QuadEdge();
   QuadEdge *q2 = new QuadEdge();
   QuadEdge *q3 = new QuadEdge();
   q0->_rot = q1;
   q1->_rot = q2;
   q2->_rot = q3;
   q3->_rot = q0;
   q0->setNext(q0);
   q1->setNext(q3);
   q2->setNext(q2);
   q3->setNext(q1);
   QuadEdge *base = q0;
   base->setOrig(o);
   base->setDest(d);
   return std::unique_ptr<QuadEdge>(base);
 }
QuadEdge& geos::triangulate::quadedge::QuadEdge::oNext () const inline
Gets the next CCW edge around the origin of this edge.
Returns
the next linked edge.
Definition at line 215 of file QuadEdge.h.
Referenced by dNext(), dPrev(), geos::triangulate::quadedge::QuadEdgeSubdivision::getPrimaryEdges(), geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), lNext(), geos::triangulate::quadedge::QuadEdgeSubdivision::locate(), geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge(), oPrev(), rNext(), rPrev(), and splice().
{
     return *next;
   }
QuadEdge& geos::triangulate::quadedge::QuadEdge::oPrev () const inline
Gets the next CW edge around (from) the origin of this edge.
Returns
the previous edge.
Definition at line 224 of file QuadEdge.h.
References oNext(), and rot().
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon(), geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::remove(), and swap().
{
     return rot().oNext().rot();
   }
const Vertex& geos::triangulate::quadedge::QuadEdge::orig () const inline
Gets the vertex for the edge's origin
Returns
the origin vertex
Definition at line 308 of file QuadEdge.h.
Referenced by connect(), equalsOriented(), geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), getPrimary(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVertexUniqueEdges(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon(), geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::isFrameEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::isOnEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::isVertexOfEdge(), geos::triangulate::quadedge::Vertex::leftOf(), geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge(), geos::triangulate::quadedge::Vertex::rightOf(), and geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor::visit().
{
     return vertex;
   }
void geos::triangulate::quadedge::QuadEdge::remove ()
Marks this quadedge as being deleted. This does not free the memory used by this quadedge quartet, but indicates that this quadedge quartet no longer participates in a subdivision.
NOTE: called "delete" in JTS
Definition at line 141 of file QuadEdge.cpp.
References isAlive, and rot().
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::remove().
 {
   rot().rot().rot().isAlive = false;
   rot().rot().isAlive = false;
   rot().isAlive = false;
   isAlive = false;
 }
QuadEdge& geos::triangulate::quadedge::QuadEdge::rNext () inline
Gets the edge around the right face ccw following this edge.
Returns
the next right face edge.
Definition at line 269 of file QuadEdge.h.
References invRot(), and oNext().
{
     return rot().oNext().invRot();
   }
QuadEdge& geos::triangulate::quadedge::QuadEdge::rot () const inline
Gets the dual of this edge, directed from its right to its left.
Returns
the rotated edge
Definition at line 188 of file QuadEdge.h.
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon(), lNext(), oPrev(), remove(), splice(), sym(), and geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCircumcentreVisitor::visit().
{
     return *_rot;
   }
QuadEdge& geos::triangulate::quadedge::QuadEdge::rPrev () inline
Gets the edge around the right face ccw before this edge.
Returns
the previous right face edge.
Definition at line 278 of file QuadEdge.h.
References oNext().
{
     return sym().oNext();
   }
void geos::triangulate::quadedge::QuadEdge::setData (void * data) virtual
Sets the external data value for this edge.
Parameters
data an object containing external data
Definition at line 129 of file QuadEdge.cpp.
References data.
 {
   this->data = data;
 }
void geos::triangulate::quadedge::QuadEdge::setDest (const Vertex & d) inline
Sets the vertex for this edge's destination
Parameters
d the destination vertex
Definition at line 299 of file QuadEdge.h.
Referenced by makeEdge(), and swap().
{
     sym().setOrig(d);
   }
void geos::triangulate::quadedge::QuadEdge::setNext (QuadEdge * next) inline
Sets the connected edge
Parameters
nextEdge edge
Definition at line 174 of file QuadEdge.h.
Referenced by makeEdge(), and splice().
{
     this->next = next;
   }
void geos::triangulate::quadedge::QuadEdge::setOrig (const Vertex & o) inline
Sets the vertex for this edge's origin
Parameters
o the origin vertex
Definition at line 290 of file QuadEdge.h.
Referenced by makeEdge(), swap(), and geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCircumcentreVisitor::visit().
{
     vertex = o;
   }
void geos::triangulate::quadedge::QuadEdge::splice (QuadEdge & a, QuadEdge & b) static
Splices two edges together or apart. Splice affects the two edge rings around the origins of a and b, and, independently, the two edge rings around the left faces of a and b. In each case, (i) if the two rings are distinct, Splice will combine them into one, or (ii) if the two are the same ring, Splice will break it into two separate pieces. Thus, Splice can be used both to attach the two edges together, and to break them apart.
Parameters
a an edge to splice
b an edge to splice
Definition at line 63 of file QuadEdge.cpp.
References oNext(), rot(), and setNext().
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::initSubdiv(), geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::insertSite(), and geos::triangulate::quadedge::QuadEdgeSubdivision::remove().
 {
   QuadEdge &alpha = a.oNext().rot();
   QuadEdge &beta = b.oNext().rot();
   QuadEdge &t1 = b.oNext();
   QuadEdge &t2 = a.oNext();
   QuadEdge &t3 = beta.oNext();
   QuadEdge &t4 = alpha.oNext();
   a.setNext(&t1);
   b.setNext(&t2);
   alpha.setNext(&t3);
   beta.setNext(&t4);
 }
void geos::triangulate::quadedge::QuadEdge::swap (QuadEdge & e) static
Turns an edge counterclockwise inside its enclosing quadrilateral.
Parameters
e the quadedge to turn
Definition at line 80 of file QuadEdge.cpp.
References dest(), lNext(), oPrev(), setDest(), setOrig(), and sym().
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite().
 {
   QuadEdge &a = e.oPrev();
   QuadEdge &b = e.sym().oPrev();
   splice(e, a);
   splice(e.sym(), b);
   splice(e, a.lNext());
   splice(e.sym(), b.lNext());
   e.setOrig(a.dest());
   e.setDest(b.dest());
 }
QuadEdge& geos::triangulate::quadedge::QuadEdge::sym () const inline
Gets the edge from the destination to the origin of this edge.
Returns
the sym of the edge
Definition at line 206 of file QuadEdge.h.
References rot().
Referenced by dNext(), equalsNonOriented(), geos::triangulate::quadedge::QuadEdgeSubdivision::fetchTriangleToVisit(), getPrimary(), geos::triangulate::quadedge::QuadEdgeSubdivision::getPrimaryEdges(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVertexUniqueEdges(), geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::insertSite(), invRot(), geos::triangulate::quadedge::QuadEdgeSubdivision::isFrameBorderEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::locate(), geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge(), lPrev(), geos::triangulate::quadedge::QuadEdgeSubdivision::remove(), and swap().
{
     return rot().rot();
   }
std::unique_ptr< LineSegment > geos::triangulate::quadedge::QuadEdge::toLineSegment () const
Creates a LineSegment representing the geometry of this edge.
Returns
a LineSegment
Definition at line 169 of file QuadEdge.cpp.
References dest(), geos::triangulate::quadedge::Vertex::getCoordinate(), and vertex.
 {
   return std::unique_ptr<geom::LineSegment>(
       new geom::LineSegment(vertex.getCoordinate(), dest().getCoordinate()));
 }
Member Data Documentation
QuadEdge* geos::triangulate::quadedge::QuadEdge::_rot private
Definition at line 100 of file QuadEdge.h.
Referenced by free(), and makeEdge().
void* geos::triangulate::quadedge::QuadEdge::data private
Definition at line 103 of file QuadEdge.h.
Referenced by getData(), and setData().
bool geos::triangulate::quadedge::QuadEdge::isAlive private
Definition at line 104 of file QuadEdge.h.
Referenced by remove().
QuadEdge* geos::triangulate::quadedge::QuadEdge::next private
Definition at line 102 of file QuadEdge.h.
Vertex geos::triangulate::quadedge::QuadEdge::vertex private
Definition at line 101 of file QuadEdge.h.
Referenced by toLineSegment().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/triangulate/quadedge/QuadEdge.h
/home/vicky/potree/geos/vicky/src/triangulate/quadedge/QuadEdge.cpp