GEOS: geos::operation::relate::RelateComputer Class Reference
geos::operation::relate::RelateComputer Class Reference
Computes the topological relationship between two Geometries.
#include <RelateComputer.h>
Public Member Functions
RelateComputer (std::vector< geomgraph::GeometryGraph * > *newArg)
~RelateComputer ()
geom::IntersectionMatrix * computeIM ()
Private Member Functions
void insertEdgeEnds (std::vector< geomgraph::EdgeEnd * > *ee)
void computeProperIntersectionIM (geomgraph::index::SegmentIntersector *intersector, geom::IntersectionMatrix *imX)
void copyNodesAndLabels (int argIndex)
void computeIntersectionNodes (int argIndex)
void labelIntersectionNodes (int argIndex)
void computeDisjointIM (geom::IntersectionMatrix *imX)
void labelNodeEdges ()
void updateIM (geom::IntersectionMatrix &imX)
void labelIsolatedEdges (int thisIndex, int targetIndex)
void labelIsolatedEdge (geomgraph::Edge *e, int targetIndex, const geom::Geometry *target)
void labelIsolatedNodes ()
void labelIsolatedNode (geomgraph::Node *n, int targetIndex)
Private Attributes
algorithm::LineIntersector li
algorithm::PointLocator ptLocator
std::vector< geomgraph::GeometryGraph * > * arg
the arg(s) of the operation
geomgraph::NodeMap nodes
std::unique_ptr< geom::IntersectionMatrix > im
this intersection matrix will hold the results compute for the relate
std::vector< geomgraph::Edge * > isolatedEdges
geom::Coordinate invalidPoint
the intersection point found (if any)
Detailed Description
Computes the topological relationship between two Geometries.
RelateComputer does not need to build a complete graph structure to compute the IntersectionMatrix. The relationship between the geometries can be computed by simply examining the labelling of edges incident on each node.
RelateComputer does not currently support arbitrary GeometryCollections. This is because GeometryCollections can contain overlapping Polygons. In order to correct compute relate on overlapping Polygons, they would first need to be noded and merged (if not explicitly, at least implicitly).
Definition at line 75 of file RelateComputer.h.
Constructor & Destructor Documentation
geos::operation::relate::RelateComputer::RelateComputer (std::vector< geomgraph::GeometryGraph * > * newArg)
Definition at line 61 of file RelateComputer.cpp.
                                                                :
   arg(newArg),
   nodes(RelateNodeFactory::instance()),
   im(new IntersectionMatrix())
 {
 }
geos::operation::relate::RelateComputer::~RelateComputer ()
Definition at line 68 of file RelateComputer.cpp.
 {
 }
Member Function Documentation
void geos::operation::relate::RelateComputer::computeDisjointIM (geom::IntersectionMatrix * imX) private
If the Geometries are disjoint, we need to enter their dimension and boundary dimension in the Ext rows in the IM
Definition at line 394 of file RelateComputer.cpp.
References geos::geom::Geometry::getBoundaryDimension(), geos::geom::Geometry::getDimension(), geos::geom::Geometry::isEmpty(), and geos::geom::IntersectionMatrix::set().
Referenced by computeIM().
 {
   const Geometry *ga=(*arg)[0]->getGeometry();
   if (!ga->isEmpty()) {
     imX->set(Location::INTERIOR,Location::EXTERIOR,ga->getDimension());
     imX->set(Location::BOUNDARY,Location::EXTERIOR,ga->getBoundaryDimension());
   }
   const Geometry *gb=(*arg)[1]->getGeometry();
   if (!gb->isEmpty()) {
     imX->set(Location::EXTERIOR,Location::INTERIOR,gb->getDimension());
     imX->set(Location::EXTERIOR,Location::BOUNDARY,gb->getBoundaryDimension());
   }
 }
IntersectionMatrix * geos::operation::relate::RelateComputer::computeIM ()
Compute the labeling for isolated components. Isolated components are components that do not touch any other components in the graph. They can be identified by the fact that they will contain labels containing ONLY a single element, the one for their parent geometry. We only need to check components contained in the input graphs, since isolated components will not have been replaced by new components formed by intersections.
Definition at line 73 of file RelateComputer.cpp.
References arg, computeDisjointIM(), geos::operation::relate::EdgeEndBuilder::computeEdgeEnds(), computeIntersectionNodes(), computeProperIntersectionIM(), copyNodesAndLabels(), GEOS_CHECK_FOR_INTERRUPTS, im, insertEdgeEnds(), geos::geom::Envelope::intersects(), labelIsolatedEdges(), labelIsolatedNodes(), labelNodeEdges(), li, and updateIM().
Referenced by geos::operation::relate::RelateOp::getIntersectionMatrix().
 {
   // since Geometries are finite and embedded in a 2-D space, the EE element must always be 2
   im->set(Location::EXTERIOR,Location::EXTERIOR,2);
   // if the Geometries don't overlap there is nothing to do
   const Envelope *e1=(*arg)[0]->getGeometry()->getEnvelopeInternal();
   const Envelope *e2=(*arg)[1]->getGeometry()->getEnvelopeInternal();
   if (!e1->intersects(e2)) {
     computeDisjointIM(im.get());
     return im.release();
   }
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "computing self nodes 1"
             << std::endl;
 #endif
   std::unique_ptr<SegmentIntersector> si1 (
     (*arg)[0]->computeSelfNodes(&li,false)
   );
   GEOS_CHECK_FOR_INTERRUPTS();
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "computing self nodes 2"
             << std::endl;
 #endif
   std::unique_ptr<SegmentIntersector> si2 (
     (*arg)[1]->computeSelfNodes(&li,false)
   );
   GEOS_CHECK_FOR_INTERRUPTS();
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "computing edge intersections"
             << std::endl;
 #endif
   // compute intersections between edges of the two input geometries
   std::unique_ptr< SegmentIntersector> intersector (
     (*arg)[0]->computeEdgeIntersections((*arg)[1], &li,false)
   );
   GEOS_CHECK_FOR_INTERRUPTS();
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "copying intersection nodes"
             << std::endl;
 #endif
   computeIntersectionNodes(0);
   computeIntersectionNodes(1);
   GEOS_CHECK_FOR_INTERRUPTS();
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "copying nodes and labels"
             << std::endl;
 #endif
   GEOS_CHECK_FOR_INTERRUPTS();
   /*
    * Copy the labelling for the nodes in the parent Geometries.
    * These override any labels determined by intersections
    * between the geometries.
    */
   copyNodesAndLabels(0);
   copyNodesAndLabels(1);
   GEOS_CHECK_FOR_INTERRUPTS();
   /*
    * complete the labelling for any nodes which only have a
    * label for a single geometry
    */
   //Debug.addWatch(nodes.find(new Coordinate(110, 200)));
   //Debug.printWatch();
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "labeling isolated nodes"
             << std::endl;
 #endif
   labelIsolatedNodes();
   //Debug.printWatch();
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "computing proper intersection matrix"
             << std::endl;
 #endif
   /*
    * If a proper intersection was found, we can set a lower bound
    * on the IM.
    */
   computeProperIntersectionIM(intersector.get(), im.get());
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "computing improper intersections"
             << std::endl;
 #endif
   /*
    * Now process improper intersections
    * (eg where one or other of the geometrys has a vertex at the
    * intersection point)
    * We need to compute the edge graph at all nodes to determine
    * the IM.
    */
   // build EdgeEnds for all intersections
   EdgeEndBuilder eeBuilder;
   std::unique_ptr< std::vector<EdgeEnd*> > ee0 (
     eeBuilder.computeEdgeEnds((*arg)[0]->getEdges())
   );
   insertEdgeEnds(ee0.get());
   std::unique_ptr< std::vector<EdgeEnd*> > ee1 (
     eeBuilder.computeEdgeEnds((*arg)[1]->getEdges())
   );
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "inserting edge ends"
             << std::endl;
 #endif
   insertEdgeEnds(ee1.get());
   //Debug.println("==== NodeList ===");
   //Debug.print(nodes);
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "labeling node edges"
             << std::endl;
 #endif
   labelNodeEdges();
 #if GEOS_DEBUG
   std::cerr << "RelateComputer::computeIM: "
             << "computing labeling for isolated components"
             << std::endl;
 #endif
   //debugPrintln("Graph A isolated edges - ");
   labelIsolatedEdges(0,1);
   //debugPrintln("Graph B isolated edges - ");
   labelIsolatedEdges(1,0);
   // update the IM from all components
   updateIM( *im );
   return im.release();
 }
void geos::operation::relate::RelateComputer::computeIntersectionNodes (int argIndex) private
Insert nodes for all intersections on the edges of a Geometry. Label the created nodes the same as the edge label if they do not already have a label. This allows nodes created by either self-intersections or mutual intersections to be labelled. Endpoint nodes will already be labelled from when they were inserted.
Definition at line 332 of file RelateComputer.cpp.
References geos::geomgraph::NodeMap::addNode(), geos::geomgraph::EdgeIntersectionList::begin(), geos::geomgraph::EdgeIntersection::coord, geos::geomgraph::EdgeIntersectionList::end(), geos::geomgraph::Edge::getEdgeIntersectionList(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isNull(), nodes, geos::geomgraph::Node::setLabel(), and geos::geomgraph::Node::setLabelBoundary().
Referenced by computeIM().
 {
   std::vector<Edge*> *edges=(*arg)[argIndex]->getEdges();
   for(std::vector<Edge*>::iterator i=edges->begin();i<edges->end();i++)
   {
     Edge *e=*i;
     int eLoc=e->getLabel().getLocation(argIndex);
     EdgeIntersectionList &eiL=e->getEdgeIntersectionList();
     EdgeIntersectionList::iterator it=eiL.begin();
     EdgeIntersectionList::iterator end=eiL.end();
     for( ; it!=end; ++it)
     {
       EdgeIntersection *ei=*it;
       assert(dynamic_cast<RelateNode*>(nodes.addNode(ei->coord)));
       RelateNode *n=static_cast<RelateNode*>(nodes.addNode(ei->coord));
       if (eLoc==Location::BOUNDARY)
       {
         n->setLabelBoundary(argIndex);
       }
       else
       {
         if (n->getLabel().isNull(argIndex))
           n->setLabel(argIndex,Location::INTERIOR);
       }
     }
   }
 }
void geos::operation::relate::RelateComputer::computeProperIntersectionIM (geomgraph::index::SegmentIntersector * intersector, geom::IntersectionMatrix * imX) private
If edge segments of Areas properly intersect, the areas must properly overlap.
If an Line segment properly intersects an edge segment of an Area, it follows that the Interior of the Line intersects the Boundary of the Area. If the intersection is a proper interior intersection, then there is an Interior-Interior intersection too. Note that it does not follow that the Interior of the Line intersects the Exterior of the Area, since there may be another Area component which contains the rest of the Line.
Definition at line 254 of file RelateComputer.cpp.
References geos::geomgraph::index::SegmentIntersector::hasProperInteriorIntersection(), geos::geomgraph::index::SegmentIntersector::hasProperIntersection(), and geos::geom::IntersectionMatrix::setAtLeast().
Referenced by computeIM().
 {
   // If a proper intersection is found, we can set a lower bound on the IM.
   int dimA=(*arg)[0]->getGeometry()->getDimension();
   int dimB=(*arg)[1]->getGeometry()->getDimension();
   bool hasProper=intersector->hasProperIntersection();
   bool hasProperInterior=intersector->hasProperInteriorIntersection();
   // For Geometry's of dim 0 there can never be proper intersections.
   if (dimA==2 && dimB==2) {
     if (hasProper) imX->setAtLeast("212101212");
   }
    else if (dimA==2 && dimB==1) {
     if (hasProper) imX->setAtLeast("FFF0FFFF2");
     if (hasProperInterior) imX->setAtLeast("1FFFFF1FF");
   } else if (dimA==1 && dimB==2) {
     if (hasProper) imX->setAtLeast("F0FFFFFF2");
     if (hasProperInterior) imX->setAtLeast("1F1FFFFFF");
   }
   /* If edges of LineStrings properly intersect *in an interior point*, all
   we can deduce is that
   the interiors intersect.  (We can NOT deduce that the exteriors intersect,
   since some other segments in the geometries might cover the points in the
   neighbourhood of the intersection.)
   It is important that the point be known to be an interior point of
   both Geometries, since it is possible in a self-intersecting geometry to
   have a proper intersection on one segment that is also a boundary point of another segment.
   */
   else if (dimA==1 && dimB==1) {
     if (hasProperInterior) imX->setAtLeast("0FFFFFFFF");
   }
 }
void geos::operation::relate::RelateComputer::copyNodesAndLabels (int argIndex) private
Copy all nodes from an arg geometry into this graph. The node label in the arg geometry overrides any previously computed label for that argIndex. (E.g. a node may be an intersection node with a computed label of BOUNDARY, but in the original arg Geometry it is actually in the interior due to the Boundary Determination Rule)
Definition at line 307 of file RelateComputer.cpp.
References geos::geomgraph::NodeMap::addNode(), geos::geomgraph::NodeMap::begin(), geos::geomgraph::NodeMap::end(), geos::geomgraph::Node::getCoordinate(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), nodes, and geos::geomgraph::Node::setLabel().
Referenced by computeIM().
 {
   const NodeMap* nm = (*arg)[argIndex]->getNodeMap();
   NodeMap::const_iterator nodeIt=nm->begin(), nodeEnd=nm->end();
   for( ; nodeIt!=nodeEnd; nodeIt++)
   {
     Node *graphNode=nodeIt->second;
     Node *newNode=nodes.addNode(graphNode->getCoordinate());
     newNode->setLabel(argIndex,
         graphNode->getLabel().getLocation(argIndex));
     //node.print(System.out);
   }
 }
void geos::operation::relate::RelateComputer::insertEdgeEnds (std::vector< geomgraph::EdgeEnd * > * ee) private
Definition at line 244 of file RelateComputer.cpp.
References geos::geomgraph::NodeMap::add(), and nodes.
Referenced by computeIM().
 {
   for(std::vector<EdgeEnd*>::iterator i=ee->begin();i<ee->end();i++) {
     EdgeEnd *e=*i;
     nodes.add(e);
   }
 }
void geos::operation::relate::RelateComputer::labelIntersectionNodes (int argIndex) private
Definition at line 368 of file RelateComputer.cpp.
References geos::geomgraph::EdgeIntersectionList::begin(), geos::geomgraph::EdgeIntersection::coord, geos::geomgraph::EdgeIntersectionList::end(), geos::geomgraph::NodeMap::find(), geos::geomgraph::Edge::getEdgeIntersectionList(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isNull(), nodes, geos::geomgraph::Node::setLabel(), and geos::geomgraph::Node::setLabelBoundary().
 {
   std::vector<Edge*> *edges=(*arg)[argIndex]->getEdges();
   for(std::vector<Edge*>::iterator i=edges->begin();i<edges->end();i++) {
     Edge *e=*i;
     int eLoc=e->getLabel().getLocation(argIndex);
     EdgeIntersectionList &eiL=e->getEdgeIntersectionList();
     EdgeIntersectionList::iterator eiIt=eiL.begin();
     EdgeIntersectionList::iterator eiEnd=eiL.end();
     for( ; eiIt!=eiEnd; ++eiIt)
     {
       EdgeIntersection *ei=*eiIt;
       RelateNode *n=(RelateNode*) nodes.find(ei->coord);
       if (n->getLabel().isNull(argIndex)) {
         if (eLoc==Location::BOUNDARY)
           n->setLabelBoundary(argIndex);
         else
           n->setLabel(argIndex,Location::INTERIOR);
       }
     }
   }
 }
void geos::operation::relate::RelateComputer::labelIsolatedEdge (geomgraph::Edge * e, int targetIndex, const geom::Geometry * target) private
Label an isolated edge of a graph with its relationship to the target geometry. If the target has dim 2 or 1, the edge can either be in the interior or the exterior. If the target has dim 0, the edge must be in the exterior
Definition at line 469 of file RelateComputer.cpp.
References geos::geomgraph::Edge::getCoordinate(), geos::geom::Geometry::getDimension(), geos::geomgraph::GraphComponent::getLabel(), geos::algorithm::PointLocator::locate(), ptLocator, and geos::geomgraph::Label::setAllLocations().
Referenced by labelIsolatedEdges().
 {
   // this won't work for GeometryCollections with both dim 2 and 1 geoms
   if (target->getDimension()>0) {
     // since edge is not in boundary, may not need the full generality of PointLocator?
     // Possibly should use ptInArea locator instead?  We probably know here
     // that the edge does not touch the bdy of the target Geometry
     int loc=ptLocator.locate(e->getCoordinate(), target);
     e->getLabel().setAllLocations(targetIndex,loc);
   } else {
     e->getLabel().setAllLocations(targetIndex,Location::EXTERIOR);
   }
   //System.out.println(e.getLabel());
 }
void geos::operation::relate::RelateComputer::labelIsolatedEdges (int thisIndex, int targetIndex) private
Processes isolated edges by computing their labelling and adding them to the isolated edges list. Isolated edges are guaranteed not to touch the boundary of the target (since if they did, they would have caused an intersection to be computed and hence would not be isolated)
Definition at line 455 of file RelateComputer.cpp.
References arg, geos::geomgraph::Edge::isIsolated(), isolatedEdges, and labelIsolatedEdge().
Referenced by computeIM().
 {
   std::vector<Edge*> *edges=(*arg)[thisIndex]->getEdges();
   for(std::vector<Edge*>::iterator i=edges->begin();i<edges->end();i++) {
     Edge *e=*i;
     if (e->isIsolated()) {
       labelIsolatedEdge(e,targetIndex,(*arg)[targetIndex]->getGeometry());
       isolatedEdges.push_back(e);
     }
   }
 }
void geos::operation::relate::RelateComputer::labelIsolatedNode (geomgraph::Node * n, int targetIndex) private
Label an isolated node with its relationship to the target geometry.
Definition at line 506 of file RelateComputer.cpp.
References geos::geomgraph::Node::getCoordinate(), geos::geomgraph::GraphComponent::getLabel(), geos::algorithm::PointLocator::locate(), ptLocator, and geos::geomgraph::Label::setAllLocations().
Referenced by labelIsolatedNodes().
 {
   int loc=ptLocator.locate(n->getCoordinate(),
       (*arg)[targetIndex]->getGeometry());
   n->getLabel().setAllLocations(targetIndex,loc);
   //debugPrintln(n.getLabel());
 }
void geos::operation::relate::RelateComputer::labelIsolatedNodes () private
Isolated nodes are nodes whose labels are incomplete (e.g. the location for one Geometry is null). This is the case because nodes in one graph which don't intersect nodes in the other are not completely labelled by the initial process of adding nodes to the nodeList. To complete the labelling we need to check for nodes that lie in the interior of edges, and in the interior of areas.
Definition at line 486 of file RelateComputer.cpp.
References geos::geomgraph::NodeMap::begin(), geos::geomgraph::NodeMap::end(), geos::geomgraph::Label::getGeometryCount(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Node::isIsolated(), geos::geomgraph::Label::isNull(), labelIsolatedNode(), and nodes.
Referenced by computeIM().
 {
   NodeMap::iterator nodeIt=nodes.begin(), nodeEnd=nodes.end();
   for( ; nodeIt!=nodeEnd; nodeIt++)
   {
     Node *n=nodeIt->second;
     const Label& label = n->getLabel();
     // isolated nodes should always have at least one geometry in their label
     assert(label.getGeometryCount()>0); // node with empty label found
     if (n->isIsolated()) {
       if (label.isNull(0))
         labelIsolatedNode(n,0);
       else
         labelIsolatedNode(n,1);
     }
   }
 }
void geos::operation::relate::RelateComputer::labelNodeEdges () private
Definition at line 410 of file RelateComputer.cpp.
References arg, geos::geomgraph::EdgeEndStar::computeLabelling(), geos::geomgraph::Node::getEdges(), geos::geomgraph::NodeMap::nodeMap, and nodes.
Referenced by computeIM().
 {
   std::map<Coordinate*,Node*,CoordinateLessThen> &nMap=nodes.nodeMap;
   std::map<Coordinate*,Node*,CoordinateLessThen>::iterator nodeIt;
   for(nodeIt=nMap.begin();nodeIt!=nMap.end();nodeIt++)
   {
     assert(dynamic_cast<RelateNode*>(nodeIt->second));
     RelateNode *node=static_cast<RelateNode*>(nodeIt->second);
 #if GEOS_DEBUG
     std::cerr << "RelateComputer::labelNodeEdges: "
               << "node edges: " << *(node->getEdges())
               << std::endl;
 #endif
     node->getEdges()->computeLabelling(arg);
     //Debug.print(node.getEdges());
     //node.print(System.out);
   }
 }
void geos::operation::relate::RelateComputer::updateIM (geom::IntersectionMatrix & imX) private
update the IM with the sum of the IMs for each component
Definition at line 431 of file RelateComputer.cpp.
References isolatedEdges, geos::geomgraph::NodeMap::nodeMap, nodes, geos::geomgraph::GraphComponent::updateIM(), and geos::operation::relate::RelateNode::updateIMFromEdges().
Referenced by computeIM().
 {
   //Debug.println(im);
   std::vector<Edge *>::iterator ei=isolatedEdges.begin();
   for ( ; ei<isolatedEdges.end(); ++ei)
   {
     Edge *e=*ei;
     e->GraphComponent::updateIM(imX);
     //Debug.println(im);
   }
   std::map<Coordinate*,Node*,CoordinateLessThen> &nMap=nodes.nodeMap;
   std::map<Coordinate*,Node*,CoordinateLessThen>::iterator nodeIt;
   for(nodeIt=nMap.begin();nodeIt!=nMap.end();nodeIt++) {
     RelateNode *node=(RelateNode*) nodeIt->second;
     node->updateIM(imX);
     //Debug.println(im);
     node->updateIMFromEdges(imX);
     //Debug.println(im);
     //node.print(System.out);
   }
 }
Member Data Documentation
std::vector<geomgraph::GeometryGraph*>* geos::operation::relate::RelateComputer::arg private
the arg(s) of the operation
Definition at line 88 of file RelateComputer.h.
Referenced by computeIM(), labelIsolatedEdges(), and labelNodeEdges().
std::unique_ptr<geom::IntersectionMatrix> geos::operation::relate::RelateComputer::im private
this intersection matrix will hold the results compute for the relate
Definition at line 93 of file RelateComputer.h.
Referenced by computeIM().
geom::Coordinate geos::operation::relate::RelateComputer::invalidPoint private
the intersection point found (if any)
Definition at line 98 of file RelateComputer.h.
std::vector<geomgraph::Edge*> geos::operation::relate::RelateComputer::isolatedEdges private
Definition at line 95 of file RelateComputer.h.
Referenced by labelIsolatedEdges(), and updateIM().
algorithm::LineIntersector geos::operation::relate::RelateComputer::li private
Definition at line 83 of file RelateComputer.h.
Referenced by computeIM().
geomgraph::NodeMap geos::operation::relate::RelateComputer::nodes private
Definition at line 90 of file RelateComputer.h.
Referenced by computeIntersectionNodes(), copyNodesAndLabels(), insertEdgeEnds(), labelIntersectionNodes(), labelIsolatedNodes(), labelNodeEdges(), and updateIM().
algorithm::PointLocator geos::operation::relate::RelateComputer::ptLocator private
Definition at line 85 of file RelateComputer.h.
Referenced by labelIsolatedEdge(), and labelIsolatedNode().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/relate/RelateComputer.h
/home/vicky/potree/geos/vicky/src/operation/relate/RelateComputer.cpp