GEOS: geos::noding::snapround::HotPixelSnapAction Class Reference
geos::noding::snapround::HotPixelSnapAction Class Reference
Public Member Functions
HotPixelSnapAction (HotPixel &nHotPixel, SegmentString *nParentEdge, unsigned int nVertexIndex)
bool isNodeAdded () const
void select (chain::MonotoneChain &mc, unsigned int startIndex) override
This function can be overridden if the original chain is needed.
void select (const LineSegment &ls) override
Public Attributes
geom::Envelope tempEnv1
Protected Attributes
geom::LineSegment selectedSegment
Private Member Functions
HotPixelSnapAction (const HotPixelSnapAction &other)=delete
HotPixelSnapAction & operator= (const HotPixelSnapAction &rhs)=delete
Private Attributes
HotPixel & hotPixel
SegmentString * parentEdge
unsigned int vertexIndex
bool isNodeAddedVar
Detailed Description
Definition at line 39 of file MCIndexPointSnapper.cpp.
Constructor & Destructor Documentation
geos::noding::snapround::HotPixelSnapAction::HotPixelSnapAction (HotPixel & nHotPixel, SegmentString * nParentEdge, unsigned int nVertexIndex) inline
Definition at line 43 of file MCIndexPointSnapper.cpp.
     :
     MonotoneChainSelectAction(),
     hotPixel(nHotPixel),
     parentEdge(nParentEdge),
     vertexIndex(nVertexIndex),
     isNodeAddedVar(false)
   {}
geos::noding::snapround::HotPixelSnapAction::HotPixelSnapAction (const HotPixelSnapAction & other) private delete
Member Function Documentation
bool geos::noding::snapround::HotPixelSnapAction::isNodeAdded () const inline
Definition at line 54 of file MCIndexPointSnapper.cpp.
Referenced by geos::noding::snapround::MCIndexPointSnapper::snap().
 { return isNodeAddedVar; }
HotPixelSnapAction& geos::noding::snapround::HotPixelSnapAction::operator= (const HotPixelSnapAction & rhs) private delete
void geos::noding::snapround::HotPixelSnapAction::select (chain::MonotoneChain & mc, unsigned int start) inline override virtual
This function can be overridden if the original chain is needed.
Reimplemented from geos::index::chain::MonotoneChainSelectAction.
Definition at line 56 of file MCIndexPointSnapper.cpp.
References geos::index::chain::MonotoneChain::getContext().
   {
     // This is casting away 'constness'!
     NodedSegmentString& ss = *(static_cast<NodedSegmentString*>(mc.getContext()));
     // don't snap a vertex to itself
     if ( parentEdge ) {
       if (&ss == parentEdge && startIndex == vertexIndex) return;
     }
     //isNodeAddedVar = SimpleSnapRounder::addSnappedNode(hotPixel, ss, startIndex);
     isNodeAddedVar = hotPixel.addSnappedNode(ss, startIndex);
   }
void geos::noding::snapround::HotPixelSnapAction::select (const LineSegment & seg) inline override virtual
This is a convenience function which can be overridden to obtain the actual line segment which is selected
Parameters
seg
Implements geos::index::chain::MonotoneChainSelectAction.
Definition at line 71 of file MCIndexPointSnapper.cpp.
References geos::ignore_unused_variable_warning().
   {
     ::geos::ignore_unused_variable_warning(ls);
   }
Member Data Documentation
HotPixel& geos::noding::snapround::HotPixelSnapAction::hotPixel private
Definition at line 77 of file MCIndexPointSnapper.cpp.
bool geos::noding::snapround::HotPixelSnapAction::isNodeAddedVar private
Definition at line 80 of file MCIndexPointSnapper.cpp.
SegmentString* geos::noding::snapround::HotPixelSnapAction::parentEdge private
Definition at line 78 of file MCIndexPointSnapper.cpp.
geom::LineSegment geos::index::chain::MonotoneChainSelectAction::selectedSegment protected inherited
Definition at line 49 of file MonotoneChainSelectAction.h.
Referenced by geos::index::chain::MonotoneChainSelectAction::select().
geom::Envelope geos::index::chain::MonotoneChainSelectAction::tempEnv1 inherited
Definition at line 70 of file MonotoneChainSelectAction.h.
Referenced by geos::index::chain::MonotoneChain::computeSelect().
unsigned int geos::noding::snapround::HotPixelSnapAction::vertexIndex private
Definition at line 79 of file MCIndexPointSnapper.cpp.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/noding/snapround/MCIndexPointSnapper.cpp