GEOS: geos::operation::relate::EdgeEndBundle Class Reference
geos::operation::relate::EdgeEndBundle Class Reference
A collection of geomgraph::EdgeEnd objects which originate at the same point and have the same direction.
#include <EdgeEndBundle.h>
Public Member Functions
EdgeEndBundle (geomgraph::EdgeEnd *e)
~EdgeEndBundle () override
std::vector< geomgraph::EdgeEnd * > * getEdgeEnds ()
void insert (geomgraph::EdgeEnd *e)
void computeLabel (const algorithm::BoundaryNodeRule &bnr) override
void updateIM (geom::IntersectionMatrix &im)
Update the IM with the contribution for the computed label for the EdgeStubs.
std::string print () const override
Edge * getEdge ()
Label & getLabel ()
const Label & getLabel () const
virtual geom::Coordinate & getCoordinate ()
const geom::Coordinate & getCoordinate () const
virtual geom::Coordinate & getDirectedCoordinate ()
virtual int getQuadrant ()
virtual double getDx ()
virtual double getDy ()
virtual void setNode (Node *newNode)
virtual Node * getNode ()
virtual int compareTo (const EdgeEnd *e) const
virtual int compareDirection (const EdgeEnd *e) const
Protected Member Functions
void computeLabelOn (int geomIndex, const algorithm::BoundaryNodeRule &boundaryNodeRule)
void computeLabelSides (int geomIndex)
void computeLabelSide (int geomIndex, int side)
virtual void init (const geom::Coordinate &newP0, const geom::Coordinate &newP1)
Protected Attributes
std::vector< geomgraph::EdgeEnd * > * edgeEnds
Edge * edge
Label label
Detailed Description
A collection of geomgraph::EdgeEnd objects which originate at the same point and have the same direction.
Definition at line 47 of file EdgeEndBundle.h.
Constructor & Destructor Documentation
geos::operation::relate::EdgeEndBundle::EdgeEndBundle (geomgraph::EdgeEnd * e)
Definition at line 38 of file EdgeEndBundle.cpp.
References edgeEnds, and insert().
                                       :
   EdgeEnd(e->getEdge(),e->getCoordinate(),
     e->getDirectedCoordinate(),
     e->getLabel())
 {
   edgeEnds=new vector<EdgeEnd*>();
   insert(e);
 }
geos::operation::relate::EdgeEndBundle::~EdgeEndBundle () override
Definition at line 47 of file EdgeEndBundle.cpp.
References edgeEnds.
{
   for(size_t i=0, n=edgeEnds->size(); i<n; i++) {
     delete (*edgeEnds)[i];
   }
   delete edgeEnds;
 }
Member Function Documentation
int geos::geomgraph::EdgeEnd::compareDirection (const EdgeEnd * e) const virtual inherited
Implements the total order relation:
a has a greater angle with the positive x-axis than b
Using the obvious algorithm of simply computing the angle is not robust, since the angle calculation is obviously susceptible to roundoff. A robust algorithm is:
first compare the quadrant. If the quadrants are different, it it trivial to determine which vector is "greater".
if the vectors lie in the same quadrant, the computeOrientation function can be used to decide the relative orientation of the vectors.
Definition at line 167 of file EdgeEnd.cpp.
References geos::algorithm::CGAlgorithms::computeOrientation(), geos::geomgraph::EdgeEnd::dx, geos::geomgraph::EdgeEnd::dy, geos::geomgraph::EdgeEnd::p0, geos::geomgraph::EdgeEnd::p1, and geos::geomgraph::EdgeEnd::quadrant.
Referenced by geos::geomgraph::EdgeEnd::compareTo().
 {
   assert(e);
   if (dx == e->dx && dy == e->dy)
     return 0;
   // if the rays are in different quadrants,
   // determining the ordering is trivial
   if (quadrant>e->quadrant) return 1;
   if (quadrant<e->quadrant) return -1;
   // vectors are in the same quadrant - check relative
   // orientation of direction vectors
   // this is > e if it is CCW of e
   return CGAlgorithms::computeOrientation(e->p0, e->p1, p1);
 }
int geos::geomgraph::EdgeEnd::compareTo (const EdgeEnd * e) const virtual inherited
Definition at line 160 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::compareDirection().
Referenced by geos::geomgraph::EdgeEndLT::operator()().
 {
   return compareDirection(e);
 }
void geos::operation::relate::EdgeEndBundle::computeLabel (const algorithm::BoundaryNodeRule & boundaryNodeRule) override virtual
This computes the overall edge label for the set of edges in this EdgeStubBundle. It essentially merges the ON and side labels for each edge. These labels must be compatible
Reimplemented from geos::geomgraph::EdgeEnd.
Definition at line 73 of file EdgeEndBundle.cpp.
References computeLabelOn(), computeLabelSides(), edgeEnds, geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::isArea(), and geos::geomgraph::EdgeEnd::label.
 {
   // create the label.  If any of the edges belong to areas,
   // the label must be an area label
   bool isArea=false;
   for(vector<EdgeEnd*>::iterator it=edgeEnds->begin(), itEnd=edgeEnds->end();
       it != itEnd; it++)
   {
     EdgeEnd *e=*it;
     if (e->getLabel().isArea()) isArea=true;
   }
   if (isArea) {
     label = Label(Location::UNDEF,Location::UNDEF,Location::UNDEF);
   } else {
     label = Label(Location::UNDEF);
   }
   // compute the On label, and the side labels if present
   for(int i=0;i<2;i++) {
     computeLabelOn(i, boundaryNodeRule);
     if (isArea)
       computeLabelSides(i);
   }
 }
void geos::operation::relate::EdgeEndBundle::computeLabelOn (int geomIndex, const algorithm::BoundaryNodeRule & boundaryNodeRule) protected
Compute the overall ON location for the list of EdgeStubs.
(This is essentially equivalent to computing the self-overlay of a single Geometry)
edgeStubs can be either on the boundary (eg Polygon edge) OR in the interior (e.g. segment of a LineString) of their parent Geometry.
In addition, GeometryCollections use a algorithm::BoundaryNodeRule to determine whether a segment is on the boundary or not.
Finally, in GeometryCollections it can occur that an edge is both on the boundary and in the interior (e.g. a LineString segment lying on top of a Polygon edge.) In this case the Boundary is given precendence.
These observations result in the following rules for computing the ON location:
if there are an odd number of Bdy edges, the attribute is Bdy
if there are an even number >= 2 of Bdy edges, the attribute is Int
if there are any Int edges, the attribute is Int
otherwise, the attribute is NULL.
Definition at line 101 of file EdgeEndBundle.cpp.
References edgeEnds, geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::EdgeEnd::label, and geos::geomgraph::Label::setLocation().
Referenced by computeLabel().
 {
   // compute the ON location value
   int boundaryCount=0;
   bool foundInterior=false;
   for(vector<EdgeEnd*>::iterator it=edgeEnds->begin();it<edgeEnds->end();it++) {
     EdgeEnd *e=*it;
     int loc=e->getLabel().getLocation(geomIndex);
     if (loc==Location::BOUNDARY) boundaryCount++;
     if (loc==Location::INTERIOR) foundInterior=true;
   }
   int loc=Location::UNDEF;
   if (foundInterior) loc=Location::INTERIOR;
   if (boundaryCount>0) {
     loc = GeometryGraph::determineBoundary(boundaryNodeRule,
                                            boundaryCount);
   }
   label.setLocation(geomIndex,loc);
 }
void geos::operation::relate::EdgeEndBundle::computeLabelSide (int geomIndex, int side) protected
To compute the summary label for a side, the algorithm is: FOR all edges IF any edge's location is INTERIOR for the side, side location = INTERIOR ELSE IF there is at least one EXTERIOR attribute, side location = EXTERIOR ELSE side location = NULL
Note that it is possible for two sides to have apparently contradictory information i.e. one edge side may indicate that it is in the interior of a geometry, while another edge side may indicate the exterior of the same geometry. This is not an incompatibility - GeometryCollections may contain two Polygons that touch along an edge. This is the reason for Interior-primacy rule above - it results in the summary label having the Geometry interior on both sides.
Definition at line 145 of file EdgeEndBundle.cpp.
References edgeEnds, geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isArea(), geos::geomgraph::EdgeEnd::label, and geos::geomgraph::Label::setLocation().
Referenced by computeLabelSides().
{
   for(vector<EdgeEnd*>::iterator it=edgeEnds->begin();it<edgeEnds->end();it++) {
     EdgeEnd *e=*it;
     if (e->getLabel().isArea()) {
       int loc=e->getLabel().getLocation(geomIndex,side);
       if (loc==Location::INTERIOR) {
         label.setLocation(geomIndex,side,Location::INTERIOR);
         return;
       } else if (loc==Location::EXTERIOR) {
         label.setLocation(geomIndex,side,Location::EXTERIOR);
       }
     }
   }
 }
void geos::operation::relate::EdgeEndBundle::computeLabelSides (int geomIndex) protected
Compute the labelling for each side
Definition at line 126 of file EdgeEndBundle.cpp.
References computeLabelSide().
Referenced by computeLabel().
{
   computeLabelSide(geomIndex,Position::LEFT);
   computeLabelSide(geomIndex,Position::RIGHT);
 }
Coordinate & geos::geomgraph::EdgeEnd::getCoordinate () virtual inherited
Definition at line 110 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::p0.
Referenced by geos::geomgraph::NodeMap::add(), geos::geomgraph::Node::add(), geos::geomgraph::DirectedEdgeStar::computeDepths(), geos::geomgraph::EdgeEndStar::computeLabelling(), geos::geomgraph::EdgeRing::computePoints(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), geos::operation::buffer::RightmostEdgeFinder::findEdge(), geos::geomgraph::EdgeEndStar::getCoordinate(), geos::operation::valid::ConnectedInteriorTester::hasUnvisitedShellEdge(), geos::geomgraph::Node::Node(), geos::geomgraph::EdgeEndStar::propagateSideLabels(), geos::geomgraph::DirectedEdge::setDepth(), and geos::geomgraph::Node::testInvariant().
 {
   return p0;
 }
const geom::Coordinate& geos::geomgraph::EdgeEnd::getCoordinate () const inline inherited
Definition at line 95 of file EdgeEnd.h.
 { return p0; }
Coordinate & geos::geomgraph::EdgeEnd::getDirectedCoordinate () virtual inherited
Definition at line 117 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::p1.
 {
   return p1;
 }
double geos::geomgraph::EdgeEnd::getDx () virtual inherited
Definition at line 131 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::dx.
 {
   return dx;
 }
double geos::geomgraph::EdgeEnd::getDy () virtual inherited
Definition at line 138 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::dy.
Referenced by geos::geomgraph::DirectedEdgeStar::getRightmostEdge().
 {
   return dy;
 }
Edge* geos::geomgraph::EdgeEnd::getEdge () inline inherited
Definition at line 86 of file EdgeEnd.h.
Referenced by geos::operation::buffer::RightmostEdgeFinder::checkForRightmostCoordinate(), geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::LineBuilder::collectLineEdge(), geos::geomgraph::DirectedEdgeStar::computeLabelling(), geos::geomgraph::EdgeRing::computePoints(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges(), geos::geomgraph::PlanarGraph::findEdgeEnd(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtVertex(), geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments(), geos::operation::buffer::BufferSubgraph::getEnvelope(), geos::operation::buffer::RightmostEdgeFinder::getRightmostSideOfSegment(), geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), geos::geomgraph::Node::isIncidentEdgeInResult(), geos::geomgraph::DirectedEdge::setEdgeDepths(), and geos::geomgraph::EdgeRing::setInResult().
 { return edge; }
vector< EdgeEnd * > * geos::operation::relate::EdgeEndBundle::getEdgeEnds ()
Definition at line 57 of file EdgeEndBundle.cpp.
References edgeEnds.
Referenced by geos::operation::valid::ConsistentAreaTester::hasDuplicateRings().
{
   return edgeEnds;
 }
Label& geos::geomgraph::EdgeEnd::getLabel () inline inherited
Definition at line 89 of file EdgeEnd.h.
Referenced by geos::operation::overlay::PolygonBuilder::buildMaximalEdgeRings(), geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent(), geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::LineBuilder::collectLineEdge(), computeLabel(), geos::geomgraph::EdgeEndStar::computeLabelling(), computeLabelOn(), computeLabelSide(), geos::geomgraph::EdgeRing::computePoints(), geos::operation::overlay::OverlayOp::findResultAreaEdges(), geos::operation::valid::ConnectedInteriorTester::hasUnvisitedShellEdge(), geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges(), geos::geomgraph::DirectedEdgeStar::mergeSymLabels(), geos::geomgraph::EdgeEndStar::propagateSideLabels(), geos::operation::valid::ConnectedInteriorTester::setInteriorEdgesInResult(), geos::geomgraph::DirectedEdgeStar::updateLabelling(), and geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
 { return label; }
const Label& geos::geomgraph::EdgeEnd::getLabel () const inline inherited
Definition at line 91 of file EdgeEnd.h.
 { return label; }
Node * geos::geomgraph::EdgeEnd::getNode () virtual inherited
Definition at line 153 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::node.
Referenced by geos::operation::buffer::BufferSubgraph::add(), geos::operation::buffer::BufferSubgraph::computeDepths(), geos::geomgraph::EdgeRing::computeMaxNodeDegree(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode(), and geos::operation::overlay::MaximalEdgeRing::linkDirectedEdgesForMinimalEdgeRings().
 {
   return node;
 }
int geos::geomgraph::EdgeEnd::getQuadrant () virtual inherited
Definition at line 124 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::quadrant.
Referenced by geos::geomgraph::DirectedEdgeStar::getRightmostEdge().
 {
   return quadrant;
 }
void geos::geomgraph::EdgeEnd::init (const geom::Coordinate & newP0, const geom::Coordinate & newP1) protected virtual inherited
Definition at line 96 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::dx, geos::geomgraph::EdgeEnd::dy, geos::geomgraph::EdgeEnd::p0, geos::geomgraph::EdgeEnd::p1, geos::geomgraph::EdgeEnd::quadrant, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::geomgraph::DirectedEdge::DirectedEdge(), and geos::geomgraph::EdgeEnd::EdgeEnd().
 {
   p0=newP0;
   p1=newP1;
   dx=p1.x-p0.x;
   dy=p1.y-p0.y;
   quadrant=Quadrant::quadrant(dx,dy);
   // "EdgeEnd with identical endpoints found");
   assert(!(dx == 0 && dy == 0));
 }
void geos::operation::relate::EdgeEndBundle::insert (geomgraph::EdgeEnd * e)
Definition at line 61 of file EdgeEndBundle.cpp.
References edgeEnds.
Referenced by EdgeEndBundle(), and geos::operation::relate::EdgeEndBundleStar::insert().
{
   // Assert: start point is the same
   // Assert: direction is the same
   edgeEnds->push_back(e);
 }
string geos::operation::relate::EdgeEndBundle::print () const override virtual
Reimplemented from geos::geomgraph::EdgeEnd.
Definition at line 164 of file EdgeEndBundle.cpp.
References edgeEnds, geos::geomgraph::EdgeEnd::label, geos::geomgraph::EdgeEnd::print(), and geos::geomgraph::Label::toString().
{
   string out="EdgeEndBundle--> Label: "+label.toString()+"\n";
   for(vector<EdgeEnd*>::iterator it=edgeEnds->begin();it<edgeEnds->end();it++) {
     EdgeEnd *e=*it;
     out+=e->print();
     out+="\n";
   }
   return out;
 }
void geos::geomgraph::EdgeEnd::setNode (Node * newNode) virtual inherited
Definition at line 145 of file EdgeEnd.cpp.
References geos::geom::Coordinate::equals2D(), geos::geomgraph::Node::getCoordinate(), geos::geomgraph::EdgeEnd::node, and geos::geomgraph::EdgeEnd::p0.
Referenced by geos::geomgraph::Node::add().
 {
   node=newNode;
   assert(node->getCoordinate().equals2D(p0));
 }
void geos::operation::relate::EdgeEndBundle::updateIM (geom::IntersectionMatrix & im)
Update the IM with the contribution for the computed label for the EdgeStubs.
Definition at line 160 of file EdgeEndBundle.cpp.
References geos::geomgraph::EdgeEnd::label.
Referenced by geos::operation::relate::EdgeEndBundleStar::updateIM().
{
   Edge::updateIM(label, im);
 }
Member Data Documentation
Edge* geos::geomgraph::EdgeEnd::edge protected inherited
Definition at line 135 of file EdgeEnd.h.
Referenced by geos::geomgraph::DirectedEdge::computeDirectedLabel(), geos::geomgraph::DirectedEdge::DirectedEdge(), geos::geomgraph::DirectedEdge::getDepthDelta(), and geos::geomgraph::DirectedEdge::printEdge().
std::vector<geomgraph::EdgeEnd*>* geos::operation::relate::EdgeEndBundle::edgeEnds protected
Definition at line 66 of file EdgeEndBundle.h.
Referenced by computeLabel(), computeLabelOn(), computeLabelSide(), EdgeEndBundle(), getEdgeEnds(), insert(), print(), and ~EdgeEndBundle().
Label geos::geomgraph::EdgeEnd::label protected inherited
Definition at line 137 of file EdgeEnd.h.
Referenced by geos::geomgraph::DirectedEdge::computeDirectedLabel(), computeLabel(), computeLabelOn(), computeLabelSide(), geos::geomgraph::DirectedEdge::isInteriorAreaEdge(), geos::geomgraph::DirectedEdge::isLineEdge(), geos::geomgraph::operator<<(), print(), and updateIM().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/relate/EdgeEndBundle.h
/home/vicky/potree/geos/vicky/src/operation/relate/EdgeEndBundle.cpp