GEOS: geos::index::bintree::Root Class Reference
geos::index::bintree::Root Class Reference
The root node of a single Bintree.
#include <Root.h>
Public Member Functions
Root ()
~Root () override
void insert (Interval *itemInterval, void *item)
virtual std::vector< void * > * getItems ()
virtual void add (void *item)
virtual std::vector< void * > * addAllItems (std::vector< void * > *newItems)
virtual std::vector< void * > * addAllItemsFromOverlapping (Interval *interval, std::vector< void * > *resultItems)
virtual int depth ()
virtual int size ()
virtual int nodeSize ()
Static Public Member Functions
static int getSubnodeIndex (Interval *interval, double centre)
Protected Member Functions
bool isSearchMatch (Interval *) override
Protected Attributes
std::vector< void * > * items
Node * subnode [2]
Private Member Functions
void insertContained (Node *tree, Interval *itemInterval, void *item)
Static Private Attributes
static double origin =0.0
Detailed Description
The root node of a single Bintree.
It is centred at the origin, and does not have a defined extent.
Definition at line 41 of file Root.h.
Constructor & Destructor Documentation
geos::index::bintree::Root::Root () inline
Definition at line 54 of file Root.h.
 {}
geos::index::bintree::Root::~Root () inline override
Definition at line 56 of file Root.h.
 {}
Member Function Documentation
void geos::index::bintree::NodeBase::add (void * item) virtual inherited
Definition at line 68 of file NodeBase.cpp.
Referenced by insert(), and insertContained().
{
   items->push_back(item);
 }
vector< void * > * geos::index::bintree::NodeBase::addAllItems (std::vector< void * > * newItems) virtual inherited
Definition at line 72 of file NodeBase.cpp.
{
   items->insert(items->end(),newItems->begin(),newItems->end());
   for(int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subnode[i]->addAllItems(newItems);
     }
   }
   return items;
 }
vector< void * > * geos::index::bintree::NodeBase::addAllItemsFromOverlapping (Interval * interval, std::vector< void * > * resultItems) virtual inherited
Definition at line 83 of file NodeBase.cpp.
 {
   if (!isSearchMatch(interval))
     return items;
   resultItems->insert(resultItems->end(),items->begin(),items->end());
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subnode[i]->addAllItemsFromOverlapping(interval,resultItems);
     }
   }
   return items;
 }
int geos::index::bintree::NodeBase::depth () virtual inherited
Definition at line 97 of file NodeBase.cpp.
 {
   int maxSubDepth=0;
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       int sqd=subnode[i]->depth();
       if (sqd>maxSubDepth)
         maxSubDepth=sqd;
     }
   }
   return maxSubDepth+1;
 }
vector< void * > * geos::index::bintree::NodeBase::getItems () virtual inherited
Definition at line 63 of file NodeBase.cpp.
 {
   return items;
 }
int geos::index::bintree::NodeBase::getSubnodeIndex (Interval * interval, double centre) static inherited
Returns the index of the subnode that wholely contains the given interval. If none does, returns -1.
Definition at line 36 of file NodeBase.cpp.
References geos::index::bintree::Interval::max, and geos::index::bintree::Interval::min.
Referenced by geos::index::bintree::Node::find(), geos::index::bintree::Node::getNode(), geos::index::bintree::Node::insert(), and insert().
 {
   int subnodeIndex=-1;
   if (interval->min>=centre) subnodeIndex=1;
   if (interval->max<=centre) subnodeIndex=0;
   return subnodeIndex;
 }
void geos::index::bintree::Root::insert (Interval * itemInterval, void * item)
Parameters
itemInterval Ownership left to caller, references kept in this class.
item Ownership left to caller, references kept in this class.
the item must be contained in one interval, so insert it into the tree for that interval (which may not yet exist)
If the subnode doesn't exist or this item is not contained in it, have to expand the tree upward to contain the item.
At this point we have a subnode which exists and must contain contains the env for the item. Insert the item into the tree.
Definition at line 31 of file Root.cpp.
References geos::index::bintree::NodeBase::add(), geos::index::bintree::Interval::contains(), geos::index::bintree::Node::createExpanded(), geos::index::bintree::Node::getInterval(), geos::index::bintree::NodeBase::getSubnodeIndex(), insertContained(), origin, and geos::index::bintree::NodeBase::subnode.
 {
   int index=getSubnodeIndex(itemInterval,origin);
   // if index is -1, itemEnv must contain the origin.
   if (index==-1) {
     add(item);
     return;
   }
   Node *node=subnode[index];
   if (node==nullptr || !node->getInterval()->contains(itemInterval))
   {
     Node* largerNode=Node::createExpanded(node,itemInterval);
 //    delete subnode[index];
     subnode[index]=largerNode;
   }
   insertContained(subnode[index],itemInterval,item);
   //System.out.println("depth = " + root.depth() + " size = " + root.size());
 }
void geos::index::bintree::Root::insertContained (Node * tree, Interval * itemInterval, void * item) private
Do NOT create a new node for zero-area intervals - this would lead to infinite recursion. Instead, use a heuristic of simply returning the smallest existing node containing the query
Definition at line 65 of file Root.cpp.
References geos::index::bintree::NodeBase::add(), geos::index::bintree::Interval::contains(), geos::index::bintree::Node::find(), geos::index::bintree::Node::getInterval(), geos::index::bintree::Interval::getMax(), geos::index::bintree::Interval::getMin(), and geos::index::bintree::Node::getNode().
Referenced by insert().
 {
   using geos::index::quadtree::IntervalSize;
   assert(tree->getInterval()->contains(itemInterval));
   bool isZeroArea=IntervalSize::isZeroWidth(itemInterval->getMin(),
       itemInterval->getMax());
   NodeBase *node;
   if (isZeroArea)
     node=tree->find(itemInterval);
   else
     node=tree->getNode(itemInterval);
   node->add(item);
 }
bool geos::index::bintree::Root::isSearchMatch (Interval *) inline override protected virtual
Implements geos::index::bintree::NodeBase.
Definition at line 68 of file Root.h.
 { return true; }
int geos::index::bintree::NodeBase::nodeSize () virtual inherited
Definition at line 123 of file NodeBase.cpp.
 {
   int subSize=0;
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subSize+=subnode[i]->nodeSize();
     }
   }
   return subSize+1;
 }
int geos::index::bintree::NodeBase::size () virtual inherited
Definition at line 111 of file NodeBase.cpp.
 {
   int subSize=0;
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subSize+=subnode[i]->size();
     }
   }
   return subSize+(int)items->size();
 }
Member Data Documentation
std::vector<void*>* geos::index::bintree::NodeBase::items protected inherited
Definition at line 63 of file NodeBase.h.
double geos::index::bintree::Root::origin =0.0 static private
Definition at line 46 of file Root.h.
Referenced by insert().
Node* geos::index::bintree::NodeBase::subnode[2] protected inherited
subnodes are numbered as follows:
0 | 1
Definition at line 70 of file NodeBase.h.
Referenced by geos::index::bintree::Node::find(), geos::index::bintree::Node::getSubnode(), geos::index::bintree::Node::insert(), and insert().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/bintree/Root.h
/home/vicky/potree/geos/vicky/src/index/bintree/Root.cpp