GEOS: geos::operation::linemerge::LineMerger Class Reference
geos::operation::linemerge::LineMerger Class Reference
Sews together a set of fully noded LineStrings.
#include <LineMerger.h>
Public Member Functions
LineMerger ()
~LineMerger ()
void add (std::vector< geom::Geometry * > *geometries)
Adds a collection of Geometries to be processed. May be called multiple times.
void add (const geom::Geometry *geometry)
Adds a Geometry to be processed. May be called multiple times.
std::vector< geom::LineString * > * getMergedLineStrings ()
Returns the LineStrings built by the merging process.
void add (const geom::LineString *lineString)
Private Member Functions
void merge ()
void buildEdgeStringsForObviousStartNodes ()
void buildEdgeStringsForIsolatedLoops ()
void buildEdgeStringsForUnprocessedNodes ()
void buildEdgeStringsForNonDegree2Nodes ()
void buildEdgeStringsStartingAt (planargraph::Node *node)
EdgeString * buildEdgeStringStartingWith (LineMergeDirectedEdge *start)
Private Attributes
LineMergeGraph graph
std::vector< geom::LineString * > * mergedLineStrings
std::vector< EdgeString * > edgeStrings
const geom::GeometryFactory * factory
Detailed Description
Sews together a set of fully noded LineStrings.
Sewing stops at nodes of degree 1 or 3 or more. The exception is an isolated loop, which only has degree-2 nodes, in which case a node is simply chosen as a starting point. The direction of each merged LineString will be that of the majority of the LineStrings from which it was derived.
Any dimension of Geometry is handled. The constituent linework is extracted to form the edges. The edges must be correctly noded; that is, they must only meet at their endpoints.
The LineMerger will still run on incorrectly noded input but will not form polygons from incorrected noded edges.
Definition at line 75 of file LineMerger.h.
Constructor & Destructor Documentation
geos::operation::linemerge::LineMerger::LineMerger ()
Definition at line 55 of file LineMerger.cpp.
                       :
   mergedLineStrings(nullptr),
   factory(nullptr)
 {
 }
geos::operation::linemerge::LineMerger::~LineMerger ()
Definition at line 61 of file LineMerger.cpp.
References edgeStrings.
 {
   for (size_t i=0, n=edgeStrings.size(); i<n; ++i) {
     delete edgeStrings[i];
   }
 }
Member Function Documentation
void geos::operation::linemerge::LineMerger::add (std::vector< geom::Geometry * > * geometries)
Adds a collection of Geometries to be processed. May be called multiple times.
Any dimension of Geometry may be added; the constituent linework will be extracted.
Definition at line 47 of file LineMerger.cpp.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::operation::linemerge::LMGeometryComponentFilter::filter(), and GEOSLineMerge_r().
 {
   for(size_t i=0, n=geometries->size(); i<n; i++) {
     Geometry *geometry=(*geometries)[i];
     add(geometry);
   }
 }
void geos::operation::linemerge::LineMerger::add (const geom::Geometry * geometry)
Adds a Geometry to be processed. May be called multiple times.
Any dimension of Geometry may be added; the constituent linework will be extracted.
Adds a Geometry to be processed. May be called multiple times. Any dimension of Geometry may be added; the constituent linework will be extracted.
Definition at line 87 of file LineMerger.cpp.
References geos::geom::Geometry::applyComponentFilter().
 {
   LMGeometryComponentFilter lmgcf(this);
   geometry->applyComponentFilter(lmgcf);
 }
void geos::operation::linemerge::LineMerger::add (const geom::LineString * lineString)
Definition at line 94 of file LineMerger.cpp.
References geos::operation::linemerge::LineMergeGraph::addEdge(), factory, geos::geom::Geometry::getFactory(), and graph.
 {
   if (factory==nullptr) factory=lineString->getFactory();
   graph.addEdge(lineString);
 }
void geos::operation::linemerge::LineMerger::buildEdgeStringsForIsolatedLoops () private
Definition at line 134 of file LineMerger.cpp.
References buildEdgeStringsForUnprocessedNodes().
Referenced by merge().
 {
   buildEdgeStringsForUnprocessedNodes();
 }
void geos::operation::linemerge::LineMerger::buildEdgeStringsForNonDegree2Nodes () private
Definition at line 166 of file LineMerger.cpp.
References buildEdgeStringsStartingAt(), geos::planargraph::Node::getDegree(), geos::planargraph::PlanarGraph::getNodes(), graph, and geos::planargraph::GraphComponent::setMarked().
Referenced by buildEdgeStringsForObviousStartNodes().
 {
 #if GEOS_DEBUG
   cerr<<__FUNCTION__<<endl;
 #endif
   typedef std::vector<Node*> Nodes;
   Nodes nodes;
   graph.getNodes(nodes);
   for (Nodes::size_type i=0, in=nodes.size(); i<in; ++i) {
     Node *node=nodes[i];
 #if GEOS_DEBUG
     cerr<<"Node "<<i<<": "<<*node<<endl;
 #endif
     if (node->getDegree()!=2) {
       buildEdgeStringsStartingAt(node);
       node->setMarked(true);
 #if GEOS_DEBUG
       cerr<<" setMarked(true) : "<<*node<<endl;
 #endif
     }
   }
 }
void geos::operation::linemerge::LineMerger::buildEdgeStringsForObviousStartNodes () private
Definition at line 128 of file LineMerger.cpp.
References buildEdgeStringsForNonDegree2Nodes().
Referenced by merge().
 {
   buildEdgeStringsForNonDegree2Nodes();
 }
void geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes () private
Definition at line 140 of file LineMerger.cpp.
References buildEdgeStringsStartingAt(), geos::planargraph::Node::getDegree(), geos::planargraph::PlanarGraph::getNodes(), graph, geos::planargraph::GraphComponent::isMarked(), and geos::planargraph::GraphComponent::setMarked().
Referenced by buildEdgeStringsForIsolatedLoops().
 {
 #if GEOS_DEBUG
   cerr<<__FUNCTION__<<endl;
 #endif
   typedef std::vector<Node*> Nodes;
   Nodes nodes;
   graph.getNodes(nodes);
   for (Nodes::size_type i=0, in=nodes.size(); i<in; ++i) {
     Node *node=nodes[i];
 #if GEOS_DEBUG
     cerr<<"Node "<<i<<": "<<*node<<endl;
 #endif
     if (!node->isMarked()) {
       assert(node->getDegree()==2);
       buildEdgeStringsStartingAt(node);
       node->setMarked(true);
 #if GEOS_DEBUG
       cerr<<" setMarked(true) : "<<*node<<endl;
 #endif
     }
   }
 }
void geos::operation::linemerge::LineMerger::buildEdgeStringsStartingAt (planargraph::Node * node) private
Definition at line 191 of file LineMerger.cpp.
References buildEdgeStringStartingWith(), edgeStrings, geos::planargraph::DirectedEdge::getEdge(), geos::planargraph::DirectedEdgeStar::getEdges(), geos::planargraph::Node::getOutEdges(), and geos::planargraph::GraphComponent::isMarked().
Referenced by buildEdgeStringsForNonDegree2Nodes(), and buildEdgeStringsForUnprocessedNodes().
 {
   auto edges = node->getOutEdges().getEdges();
   size_t size = edges.size();
   for (size_t i=0; i<size; i++)
   {
     assert(dynamic_cast<LineMergeDirectedEdge*>(edges[i]));
     LineMergeDirectedEdge *directedEdge=\
       static_cast<LineMergeDirectedEdge*> (edges[i]);
     if (directedEdge->getEdge()->isMarked()) {
       continue;
     }
     edgeStrings.push_back(buildEdgeStringStartingWith(directedEdge));
   }
 }
EdgeString * geos::operation::linemerge::LineMerger::buildEdgeStringStartingWith (LineMergeDirectedEdge * start) private
Definition at line 208 of file LineMerger.cpp.
References geos::operation::linemerge::EdgeString::add(), factory, geos::planargraph::DirectedEdge::getEdge(), geos::operation::linemerge::LineMergeDirectedEdge::getNext(), and geos::planargraph::GraphComponent::setMarked().
Referenced by buildEdgeStringsStartingAt().
 {
   EdgeString *edgeString = new EdgeString(factory);
   LineMergeDirectedEdge *current=start;
   do {
     edgeString->add(current);
     current->getEdge()->setMarked(true);
     current=current->getNext();
   } while (current!=nullptr && current!=start);
   return edgeString;
 }
vector< LineString * > * geos::operation::linemerge::LineMerger::getMergedLineStrings ()
Returns the LineStrings built by the merging process.
Ownership of vector and its elements to caller.
Returns the LineStrings built by the merging process.
Definition at line 224 of file LineMerger.cpp.
References merge(), and mergedLineStrings.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided().
 {
   merge();
   // Explicitly give ownership to the caller.
   vector<LineString*>* ret = mergedLineStrings;
   mergedLineStrings = nullptr;
   return ret;
 }
void geos::operation::linemerge::LineMerger::merge () private
Definition at line 101 of file LineMerger.cpp.
References buildEdgeStringsForIsolatedLoops(), buildEdgeStringsForObviousStartNodes(), geos::planargraph::PlanarGraph::edgeEnd(), geos::planargraph::PlanarGraph::edgeIterator(), edgeStrings, graph, mergedLineStrings, geos::planargraph::PlanarGraph::nodeEnd(), geos::planargraph::PlanarGraph::nodeIterator(), and geos::operation::linemerge::EdgeString::toLineString().
Referenced by getMergedLineStrings().
 {
   if (mergedLineStrings!=nullptr) return;
   // reset marks (this allows incremental processing)
   GraphComponent::setMarkedMap(graph.nodeIterator(), graph.nodeEnd(),
                                                                 false);
   GraphComponent::setMarked(graph.edgeIterator(), graph.edgeEnd(),
                                                                 false);
   for (size_t i=0, n=edgeStrings.size(); i<n; ++i)
     delete edgeStrings[i];
   edgeStrings.clear();
   buildEdgeStringsForObviousStartNodes();
   buildEdgeStringsForIsolatedLoops();
   auto numEdgeStrings = edgeStrings.size();
   mergedLineStrings=new vector<LineString*>(numEdgeStrings);
   for (size_t i=0; i<numEdgeStrings; ++i)
   {
     EdgeString *edgeString=edgeStrings[i];
     (*mergedLineStrings)[i]=edgeString->toLineString();
   }
 }
Member Data Documentation
std::vector<EdgeString*> geos::operation::linemerge::LineMerger::edgeStrings private
Definition at line 83 of file LineMerger.h.
Referenced by buildEdgeStringsStartingAt(), merge(), and ~LineMerger().
const geom::GeometryFactory* geos::operation::linemerge::LineMerger::factory private
Definition at line 85 of file LineMerger.h.
Referenced by add(), and buildEdgeStringStartingWith().
LineMergeGraph geos::operation::linemerge::LineMerger::graph private
Definition at line 79 of file LineMerger.h.
Referenced by add(), buildEdgeStringsForNonDegree2Nodes(), buildEdgeStringsForUnprocessedNodes(), and merge().
std::vector<geom::LineString*>* geos::operation::linemerge::LineMerger::mergedLineStrings private
Definition at line 81 of file LineMerger.h.
Referenced by getMergedLineStrings(), and merge().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/linemerge/LineMerger.h
/home/vicky/potree/geos/vicky/src/operation/linemerge/LineMerger.cpp