GEOS: geos::operation::buffer::BufferBuilder Class Reference
geos::operation::buffer::BufferBuilder Class Reference
Builds the buffer geometry for a given input geometry and precision model.
#include <BufferBuilder.h>
Public Member Functions
BufferBuilder (const BufferParameters &nBufParams)
~BufferBuilder ()
void setWorkingPrecisionModel (const geom::PrecisionModel *pm)
void setNoder (noding::Noder *newNoder)
geom::Geometry * buffer (const geom::Geometry *g, double distance)
geom::Geometry * bufferLineSingleSided (const geom::Geometry *g, double distance, bool leftSide)
Private Member Functions
void computeNodedEdges (std::vector< noding::SegmentString * > &bufSegStr, const geom::PrecisionModel *precisionModel)
void insertUniqueEdge (geomgraph::Edge *e)
void createSubgraphs (geomgraph::PlanarGraph *graph, std::vector< BufferSubgraph * > &list)
void buildSubgraphs (const std::vector< BufferSubgraph * > &subgraphList, overlay::PolygonBuilder &polyBuilder)
noding::Noder * getNoder (const geom::PrecisionModel *precisionModel)
Return the externally-set noding::Noder OR a newly created one using the given precisionModel.
geom::Geometry * createEmptyResultGeometry () const
BufferBuilder (const BufferBuilder &other)=delete
BufferBuilder & operator= (const BufferBuilder &rhs)=delete
Static Private Member Functions
static int depthDelta (const geomgraph::Label &label)
Private Attributes
const BufferParameters & bufParams
const geom::PrecisionModel * workingPrecisionModel
algorithm::LineIntersector * li
noding::IntersectionAdder * intersectionAdder
noding::Noder * workingNoder
const geom::GeometryFactory * geomFact
geomgraph::EdgeList edgeList
std::vector< geomgraph::Label * > newLabels
Detailed Description
Builds the buffer geometry for a given input geometry and precision model.
Allows setting the level of approximation for circular arcs, and the precision model in which to carry out the computation.
When computing buffers in floating point double-precision it can happen that the process of iterated noding can fail to converge (terminate).
In this case a TopologyException will be thrown. Retrying the computation in a fixed precision can produce more robust results.
Definition at line 89 of file BufferBuilder.h.
Constructor & Destructor Documentation
geos::operation::buffer::BufferBuilder::BufferBuilder (const BufferParameters & nBufParams) inline
Creates a new BufferBuilder
Parameters
nBufParams buffer parameters, this object will keep a reference to the passed parameters so caller must make sure the object is kept alive for the whole lifetime of the buffer builder.
Definition at line 101 of file BufferBuilder.h.
     :
     bufParams(nBufParams),
     workingPrecisionModel(nullptr),
     li(nullptr),
     intersectionAdder(nullptr),
     workingNoder(nullptr),
     geomFact(nullptr),
     edgeList()
   {}
geos::operation::buffer::BufferBuilder::~BufferBuilder ()
Definition at line 122 of file BufferBuilder.cpp.
 {
   delete li; // could be NULL
   delete intersectionAdder;
 }
geos::operation::buffer::BufferBuilder::BufferBuilder (const BufferBuilder & other) private delete
Member Function Documentation
Geometry * geos::operation::buffer::BufferBuilder::buffer (const geom::Geometry * g, double distance)
Definition at line 367 of file BufferBuilder.cpp.
References geos::geomgraph::PlanarGraph::addEdges(), GEOS_CHECK_FOR_INTERRUPTS, geos::operation::buffer::OffsetCurveSetBuilder::getCurves(), geos::geom::Geometry::getFactory(), geos::operation::overlay::PolygonBuilder::getPolygons(), and geos::geom::Geometry::getPrecisionModel().
Referenced by bufferLineSingleSided(), and geos::operation::buffer::BufferOp::bufferOriginalPrecision().
 {
   const PrecisionModel *precisionModel=workingPrecisionModel;
   if (precisionModel==nullptr)
     precisionModel=g->getPrecisionModel();
   assert(precisionModel);
   assert(g);
   // factory must be the same as the one used by the input
   geomFact=g->getFactory();
   { // This scope is here to force release of resources owned by
     // OffsetCurveSetBuilder when we're doing with it
   OffsetCurveBuilder curveBuilder(precisionModel, bufParams);
   OffsetCurveSetBuilder curveSetBuilder(*g, distance, curveBuilder);
   GEOS_CHECK_FOR_INTERRUPTS();
   std::vector<SegmentString*>& bufferSegStrList=curveSetBuilder.getCurves();
 #if GEOS_DEBUG
   std::cerr << "OffsetCurveSetBuilder got " << bufferSegStrList.size()
             << " curves" << std::endl;
 #endif
   // short-circuit test
   if (bufferSegStrList.size()<=0) {
     return createEmptyResultGeometry();
   }
 #if GEOS_DEBUG
   std::cerr<<"BufferBuilder::buffer computing NodedEdges"<<std::endl;
 #endif
   computeNodedEdges(bufferSegStrList, precisionModel);
   GEOS_CHECK_FOR_INTERRUPTS();
   } // bufferSegStrList and contents are released here
 #if GEOS_DEBUG > 1
   std::cerr << std::endl << edgeList << std::endl;
 #endif
   Geometry* resultGeom=nullptr;
   std::unique_ptr< std::vector<Geometry*> > resultPolyList;
   std::vector<BufferSubgraph*> subgraphList;
   try {
     PlanarGraph graph(OverlayNodeFactory::instance());
     graph.addEdges(edgeList.getEdges());
     GEOS_CHECK_FOR_INTERRUPTS();
     createSubgraphs(&graph, subgraphList);
 #if GEOS_DEBUG
   std::cerr<<"Created "<<subgraphList.size()<<" subgraphs"<<std::endl;
 #if GEOS_DEBUG > 1
   for (size_t i=0, n=subgraphList.size(); i<n; i++)
     std::cerr << std::setprecision(10) << *(subgraphList[i]) << std::endl;
 #endif
 #endif
     GEOS_CHECK_FOR_INTERRUPTS();
     { // scope for earlier PolygonBuilder cleanupt
       PolygonBuilder polyBuilder(geomFact);
       buildSubgraphs(subgraphList, polyBuilder);
       resultPolyList.reset( polyBuilder.getPolygons() );
     }
     // Get rid of the subgraphs, shouldn't be needed anymore
     for (size_t i=0, n=subgraphList.size(); i<n; i++) delete subgraphList[i];
     subgraphList.clear();
 #if GEOS_DEBUG
   std::cerr << "PolygonBuilder got " << resultPolyList->size()
             << " polygons" << std::endl;
 #if GEOS_DEBUG > 1
   for (size_t i=0, n=resultPolyList->size(); i<n; i++)
     std::cerr << (*resultPolyList)[i]->toString() << std::endl;
 #endif
 #endif
     // just in case ...
     if ( resultPolyList->empty() ) return createEmptyResultGeometry();
     // resultPolyList ownership transferred here
     resultGeom=geomFact->buildGeometry(resultPolyList.release());
   } catch (const util::GEOSException& /* exc */) {
     // In case they're still around
     for (size_t i=0, n=subgraphList.size(); i<n; i++)
       delete subgraphList[i];
     subgraphList.clear();
     throw;
   }
   return resultGeom;
 }
Geometry * geos::operation::buffer::BufferBuilder::bufferLineSingleSided (const geom::Geometry * g, double distance, bool leftSide)
Generates offset curve for linear geometry.
Parameters
g non-areal geometry object
distance width of offset
leftSide controls on which side of the input geometry offset curve is generated.
Note
For left-side offset curve, the offset will be at the left side of the input line and retain the same direction. For right-side offset curve, it'll be at the right side and in the opposite direction.
BufferParameters::setSingleSided parameter, which is specific to areal geometries only, is ignored by this routine.
Not in JTS: this is a GEOS extension
Definition at line 130 of file BufferBuilder.cpp.
References geos::operation::linemerge::LineMerger::add(), geos::geom::CoordinateSequence::back(), buffer(), geos::geom::CoordinateSequence::clone(), geos::geom::Geometry::clone(), geos::noding::Noder::computeNodes(), geos::operation::intersection::distance(), geos::geom::CoordinateSequence::front(), geos::noding::SegmentString::getCoordinates(), geos::geom::Geometry::getCoordinates(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getFactory(), geos::geom::LineString::getLength(), geos::operation::linemerge::LineMerger::getMergedLineStrings(), geos::noding::Noder::getNodedSubstrings(), geos::geom::Geometry::getPrecisionModel(), geos::operation::buffer::OffsetCurveBuilder::getSingleSidedLineCurve(), geos::operation::buffer::BufferParameters::setEndCapStyle(), and geos::operation::buffer::BufferParameters::setSingleSided().
Referenced by GEOSOffsetCurve_r(), and GEOSSingleSidedBuffer_r().
 {
    // Returns the line used to create a single-sided buffer.
    // Input requirement: Must be a LineString.
    const LineString* l = dynamic_cast< const LineString* >( g );
    if ( !l ) throw util::IllegalArgumentException("BufferBuilder::bufferLineSingleSided only accept linestrings");
    // Nothing to do for a distance of zero
    if ( distance == 0 ) return g->clone();
    // Get geometry factory and precision model.
    const PrecisionModel* precisionModel = workingPrecisionModel;
    if ( !precisionModel ) precisionModel = l->getPrecisionModel();
    assert( precisionModel );
    assert( l );
    geomFact = l->getFactory();
    // First, generate the two-sided buffer using a butt-cap.
    BufferParameters modParams = bufParams;
    modParams.setEndCapStyle(BufferParameters::CAP_FLAT);
    modParams.setSingleSided(false); // ignore parameter for areal-only geometries
    std::unique_ptr<Geometry> buf;
    // This is a (temp?) hack to workaround the fact that
    // BufferBuilder BufferParamaters are immutable after
    // construction, while we want to force the end cap
    // style to FLAT for single-sided buffering
    {
       BufferBuilder tmp(modParams);
       buf.reset( tmp.buffer( l, distance ) );
    }
    // Create MultiLineStrings from this polygon.
    std::unique_ptr<Geometry> bufLineString ( buf->getBoundary() );
 #ifdef GEOS_DEBUG_SSB
    std::cerr << "input|" << *l << std::endl;
    std::cerr << "buffer|" << *bufLineString << std::endl;
 #endif
    // Then, get the raw (i.e. unnoded) single sided offset curve.
    OffsetCurveBuilder curveBuilder( precisionModel, modParams );
    std::vector< CoordinateSequence* > lineList;
    {
        std::unique_ptr< CoordinateSequence > coords(g->getCoordinates());
        curveBuilder.getSingleSidedLineCurve(coords.get(), distance,
            lineList, leftSide, !leftSide);
        coords.reset();
    }
    // Create a SegmentString from these coordinates.
    SegmentString::NonConstVect curveList;
    for ( unsigned int i = 0; i < lineList.size(); ++i )
    {
       CoordinateSequence* seq = lineList[i];
       // SegmentString takes ownership of CoordinateSequence
       SegmentString* ss = new NodedSegmentString(seq, nullptr);
       curveList.push_back( ss );
    }
    lineList.clear();
    // Node these SegmentStrings.
    Noder* noder = getNoder( precisionModel );
    noder->computeNodes( &curveList );
    SegmentString::NonConstVect* nodedEdges = noder->getNodedSubstrings();
    // Create a geometry out of the noded substrings.
    std::vector< Geometry* >* singleSidedNodedEdges =
       new std::vector< Geometry * >();
    singleSidedNodedEdges->reserve(nodedEdges->size());
    for ( std::size_t i = 0, n = nodedEdges->size(); i < n; ++i )
    {
       SegmentString* ss = ( *nodedEdges )[i];
       Geometry* tmp = geomFact->createLineString(
                         ss->getCoordinates()->clone()
                       );
       delete ss;
       singleSidedNodedEdges->push_back( tmp );
    }
    delete nodedEdges;
    for (size_t i=0, n=curveList.size(); i<n; ++i) delete curveList[i];
    curveList.clear();
    std::unique_ptr<Geometry> singleSided ( geomFact->createMultiLineString(
       singleSidedNodedEdges ) );
 #ifdef GEOS_DEBUG_SSB
      std::cerr << "edges|" << *singleSided << std::endl;
 #endif
    // Use the boolean operation intersect to obtain the line segments lying
    // on both the butt-cap buffer and this multi-line.
    //Geometry* intersectedLines = singleSided->intersection( bufLineString );
    // NOTE: we use Snapped overlay because the actual buffer boundary might
    //       diverge from original offset curves due to the addition of
    //       intersections with caps and joins curves
    using geos::operation::overlay::snap::SnapOverlayOp;
    std::unique_ptr<Geometry> intersectedLines = SnapOverlayOp::overlayOp(*singleSided, *bufLineString, OverlayOp::opINTERSECTION);
 #ifdef GEOS_DEBUG_SSB
      std::cerr << "intersection" << "|" << *intersectedLines << std::endl;
 #endif
    // Merge result lines together.
    LineMerger lineMerge;
    lineMerge.add( intersectedLines.get() );
    std::unique_ptr< std::vector< LineString* > > mergedLines (
   lineMerge.getMergedLineStrings() );
    // Convert the result into a std::vector< Geometry* >.
    std::vector< Geometry* >* mergedLinesGeom = new std::vector< Geometry* >();
    const Coordinate& startPoint = l->getCoordinatesRO()->front();
    const Coordinate& endPoint = l->getCoordinatesRO()->back();
    while( !mergedLines->empty() )
    {
       // Remove end points if they are a part of the original line to be
       // buffered.
       CoordinateSequence::Ptr coords(mergedLines->back()->getCoordinates());
       if ( nullptr != coords.get() )
       {
          // Use 98% of the buffer width as the point-distance requirement - this
          // is to ensure that the point that is "distance" +/- epsilon is not
          // included.
          //
          // Let's try and estimate a more accurate bound instead of just assuming
          // 98%. With 98%, the episilon grows as the buffer distance grows,
          // so that at large distance, artifacts may skip through this filter
          // Let the length of the line play a factor in the distance, which is still
          // going to be bounded by 98%. Take 10% of the length of the line  from the buffer distance
          // to try and minimize any artifacts.
          const double ptDistAllowance = std::max(distance - l->getLength()*0.1, distance * 0.98);
          // Use 102% of the buffer width as the line-length requirement - this
          // is to ensure that line segments that is length "distance" +/-
          // epsilon is removed.
          const double segLengthAllowance = 1.02 * distance;
          // Clean up the front of the list.
          // Loop until the line's end is not inside the buffer width from
          // the startPoint.
          while ( coords->size() > 1 &&
                  coords->front().distance( startPoint ) < ptDistAllowance )
          {
             // Record the end segment length.
             double segLength = coords->front().distance( ( *coords )[1] );
             // Stop looping if there are no more points, or if the segment
             // length is larger than the buffer width.
             if ( coords->size() <= 1 || segLength > segLengthAllowance )
             {
                break;
             }
             // If the first point is less than buffer width away from the
             // reference point, then delete the point.
             coords->deleteAt( 0 );
          }
          while ( coords->size() > 1 &&
                  coords->front().distance( endPoint ) < ptDistAllowance )
          {
             double segLength = coords->front().distance( ( *coords )[1] );
             if ( coords->size() <= 1 || segLength > segLengthAllowance )
             {
                break;
             }
             coords->deleteAt( 0 );
          }
          // Clean up the back of the list.
          while ( coords->size() > 1 &&
                  coords->back().distance( startPoint ) < ptDistAllowance )
          {
             double segLength = coords->back().distance(
                ( *coords )[coords->size()-2] );
             if ( coords->size() <= 1 || segLength > segLengthAllowance )
             {
                break;
             }
             coords->deleteAt( coords->size()-1 );
          }
          while ( coords->size() > 1 &&
                  coords->back().distance( endPoint ) < ptDistAllowance )
          {
             double segLength = coords->back().distance(
                ( *coords )[coords->size()-2] );
             if ( coords->size() <= 1 || segLength > segLengthAllowance )
             {
                break;
             }
             coords->deleteAt( coords->size()-1 );
          }
          // Add the coordinates to the resultant line string.
          if ( coords->size() > 1 )
          {
             mergedLinesGeom->push_back( geomFact->createLineString( coords.release() ) );
          }
       }
       geomFact->destroyGeometry( mergedLines->back() );
       mergedLines->pop_back();
    }
    // Clean up.
    if ( noder != workingNoder ) delete noder;
    buf.reset();
    singleSided.reset();
    intersectedLines.reset();
    if ( mergedLinesGeom->size() > 1 )
    {
       return geomFact->createMultiLineString( mergedLinesGeom );
    }
    else if ( mergedLinesGeom->size() == 1 )
    {
       Geometry* single = (*mergedLinesGeom)[0];
       delete mergedLinesGeom;
       return single;
    }
    else
    {
       delete mergedLinesGeom;
       return geomFact->createLineString();
    }
 }
void geos::operation::buffer::BufferBuilder::buildSubgraphs (const std::vector< BufferSubgraph * > & subgraphList, overlay::PolygonBuilder & polyBuilder) private
Completes the building of the input subgraphs by depth-labelling them, and adds them to the PolygonBuilder. The subgraph list must be sorted in rightmost-coordinate order.
Parameters
subgraphList the subgraphs to build
polyBuilder the PolygonBuilder which will build the final polygons
Definition at line 649 of file BufferBuilder.cpp.
References geos::operation::overlay::PolygonBuilder::add(), geos::operation::buffer::BufferSubgraph::computeDepth(), geos::operation::buffer::BufferSubgraph::findResultEdges(), geos::operation::buffer::SubgraphDepthLocater::getDepth(), geos::operation::buffer::BufferSubgraph::getDirectedEdges(), geos::operation::buffer::BufferSubgraph::getNodes(), and geos::operation::buffer::BufferSubgraph::getRightmostCoordinate().
 {
 #if GEOS_DEBUG
   std::cerr << __FUNCTION__ << " got " << subgraphList.size() << " subgraphs" << std::endl;
 #endif
   std::vector<BufferSubgraph*> processedGraphs;
   for (size_t i=0, n=subgraphList.size(); i<n; i++)
   {
     BufferSubgraph *subgraph=subgraphList[i];
     Coordinate *p=subgraph->getRightmostCoordinate();
     assert(p);
 #if GEOS_DEBUG
     std::cerr << " " << i << ") Subgraph[" << subgraph << "]" << std::endl;
     std::cerr << "  rightmost Coordinate " << *p;
 #endif
     SubgraphDepthLocater locater(&processedGraphs);
 #if GEOS_DEBUG
     std::cerr << " after SubgraphDepthLocater processedGraphs contain "
               << processedGraphs.size()
               << " elements" << std::endl;
 #endif
     int outsideDepth=locater.getDepth(*p);
 #if GEOS_DEBUG
     std::cerr << " Depth of rightmost coordinate: " << outsideDepth << std::endl;
 #endif
     subgraph->computeDepth(outsideDepth);
     subgraph->findResultEdges();
 #if GEOS_DEBUG
     std::cerr << " after computeDepth and findResultEdges subgraph contain:" << std::endl
               << "   " << subgraph->getDirectedEdges()->size() << " DirecteEdges " << std::endl
               << "   " << subgraph->getNodes()->size() << " Nodes " << std::endl;
 #endif
     processedGraphs.push_back(subgraph);
 #if GEOS_DEBUG
     std::cerr << " added " << subgraph << " to processedGraphs, new size is "
               << processedGraphs.size() << std::endl;
 #endif
     polyBuilder.add(subgraph->getDirectedEdges(), subgraph->getNodes());
   }
 }
void geos::operation::buffer::BufferBuilder::computeNodedEdges (std::vector< noding::SegmentString * > & bufSegStr, const geom::PrecisionModel * precisionModel) private
Definition at line 518 of file BufferBuilder.cpp.
References geos::noding::Noder::computeNodes(), geos::noding::SegmentString::getCoordinates(), geos::noding::SegmentString::getData(), geos::geom::CoordinateSequence::removeRepeatedPoints(), geos::io::WKTWriter::setTrim(), geos::geom::CoordinateSequence::size(), and geos::io::WKTWriter::write().
 {
   Noder* noder = getNoder( precisionModel );
 #if JTS_DEBUG
 geos::io::WKTWriter wktWriter; wktWriter.setTrim(true);
 std::cerr << "before noding: "
   << wktWriter.write(
         convertSegStrings(geomFact, bufferSegStrList.begin(),
                                     bufferSegStrList.end()).get()
      ) << std::endl;
 #endif
   noder->computeNodes(&bufferSegStrList);
   SegmentString::NonConstVect* nodedSegStrings = \
       noder->getNodedSubstrings();
 #if JTS_DEBUG
 std::cerr << "after noding: "
   << wktWriter.write(
         convertSegStrings(geomFact, bufferSegStrList.begin(),
                                     bufferSegStrList.end()).get()
      ) << std::endl;
 #endif
   for (SegmentString::NonConstVect::iterator
     i=nodedSegStrings->begin(), e=nodedSegStrings->end();
     i!=e;
     ++i)
   {
     SegmentString* segStr = *i;
     const Label* oldLabel = static_cast<const Label*>(segStr->getData());
     CoordinateSequence* cs = CoordinateSequence::removeRepeatedPoints(segStr->getCoordinates());
     delete segStr;
     if ( cs->size() < 2 )
     {
       // don't insert collapsed edges
       // we need to take care of the memory here as cs is a new sequence
       delete cs;
       continue;
     }
     // Edge takes ownership of the CoordinateSequence
     Edge* edge = new Edge(cs, *oldLabel);
     // will take care of the Edge ownership
     insertUniqueEdge(edge);
   }
   delete nodedSegStrings;
   if ( noder != workingNoder ) delete noder;
 }
geom::Geometry * geos::operation::buffer::BufferBuilder::createEmptyResultGeometry () const private
Gets the standard result for an empty buffer. Since buffer always returns a polygonal result, this is chosen to be an empty polygon.
Returns
the empty result geometry, transferring ownership to caller.
Definition at line 695 of file BufferBuilder.cpp.
 {
   geom::Geometry* emptyGeom = geomFact->createPolygon(nullptr, nullptr);
   return emptyGeom;
 }
void geos::operation::buffer::BufferBuilder::createSubgraphs (geomgraph::PlanarGraph * graph, std::vector< BufferSubgraph * > & list) private
Definition at line 625 of file BufferBuilder.cpp.
References geos::operation::buffer::BufferSubgraphGT(), geos::operation::buffer::BufferSubgraph::create(), geos::geomgraph::PlanarGraph::getNodes(), and geos::geomgraph::GraphComponent::isVisited().
 {
   std::vector<Node*> nodes;
   graph->getNodes(nodes);
   for (size_t i=0, n=nodes.size(); i<n; i++) {
     Node *node=nodes[i];
     if (!node->isVisited()) {
       BufferSubgraph *subgraph=new BufferSubgraph();
       subgraph->create(node);
       subgraphList.push_back(subgraph);
     }
   }
   /*
    * Sort the subgraphs in descending order of their rightmost coordinate
    * This ensures that when the Polygons for the subgraphs are built,
    * subgraphs for shells will have been built before the subgraphs for
    * any holes they contain
    */
     std::sort(subgraphList.begin(), subgraphList.end(), BufferSubgraphGT);
 }
int geos::operation::buffer::BufferBuilder::depthDelta (const geomgraph::Label & label) static private
Compute the change in depth as an edge is crossed from R to L
Definition at line 108 of file BufferBuilder.cpp.
References geos::geom::Location::EXTERIOR, geos::geomgraph::Label::getLocation(), and geos::geom::Location::INTERIOR.
 {
   int lLoc=label.getLocation(0, Position::LEFT);
   int rLoc=label.getLocation(0, Position::RIGHT);
   if (lLoc== Location::INTERIOR && rLoc== Location::EXTERIOR)
     return 1;
   else if (lLoc== Location::EXTERIOR && rLoc== Location::INTERIOR)
     return -1;
   return 0;
 }
Noder * geos::operation::buffer::BufferBuilder::getNoder (const geom::PrecisionModel * precisionModel) private
Return the externally-set noding::Noder OR a newly created one using the given precisionModel.
NOTE: if an externally-set noding::Noder is available no check is performed to ensure it will use the given PrecisionModel
Definition at line 476 of file BufferBuilder.cpp.
References geos::geom::PrecisionModel::getScale().
 {
   // this doesn't change workingNoder precisionModel!
   if (workingNoder != nullptr) return workingNoder;
   // otherwise use a fast (but non-robust) noder
   if ( li ) // reuse existing IntersectionAdder and LineIntersector
   {
     li->setPrecisionModel(pm);
     assert(intersectionAdder!=nullptr);
   }
   else
   {
     li = new LineIntersector(pm);
     intersectionAdder = new IntersectionAdder(*li);
   }
   MCIndexNoder* noder = new MCIndexNoder(intersectionAdder);
 #if 0
   /* CoordinateArraySequence.cpp:84:
    * virtual const geos::Coordinate& geos::CoordinateArraySequence::getAt(size_t) const:
    * Assertion `pos<vect->size()' failed.
    */
   //Noder* noder = new snapround::SimpleSnapRounder(*pm);
   Noder* noder = new IteratedNoder(pm);
   Noder noder = new SimpleSnapRounder(pm);
   Noder noder = new MCIndexSnapRounder(pm);
   Noder noder = new ScaledNoder(
     new MCIndexSnapRounder(new PrecisionModel(1.0)),
       pm.getScale());
 #endif
   return noder;
 }
void geos::operation::buffer::BufferBuilder::insertUniqueEdge (geomgraph::Edge * e) private
Inserted edges are checked to see if an identical edge already exists. If so, the edge is not inserted, but its label is merged with the existing edge.
The function takes responsability of releasing the Edge parameter memory when appropriate.
Definition at line 578 of file BufferBuilder.cpp.
References geos::geomgraph::Label::flip(), geos::geomgraph::Edge::getDepthDelta(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Edge::isPointwiseEqual(), geos::geomgraph::Label::merge(), and geos::geomgraph::Edge::setDepthDelta().
 {
   //<FIX> MD 8 Oct 03  speed up identical edge lookup
   // fast lookup
   Edge *existingEdge = edgeList.findEqualEdge(e);
   // If an identical edge already exists, simply update its label
   if (existingEdge != nullptr) {
     Label& existingLabel = existingEdge->getLabel();
     Label labelToMerge = e->getLabel();
     // check if new edge is in reverse direction to existing edge
     // if so, must flip the label before merging it
     if (! existingEdge->isPointwiseEqual(e))
     {
       labelToMerge = e->getLabel();
       labelToMerge.flip();
     }
     existingLabel.merge(labelToMerge);
     // compute new depth delta of sum of edges
     int mergeDelta = depthDelta(labelToMerge);
     int existingDelta = existingEdge->getDepthDelta();
     int newDelta = existingDelta + mergeDelta;
     existingEdge->setDepthDelta(newDelta);
     // we have memory release responsibility
     delete e;
   } else {   // no matching existing edge was found
     // add this new edge to the list of edges in this graph
     edgeList.add(e);
     e->setDepthDelta(depthDelta(e->getLabel()));
   }
 }
BufferBuilder& geos::operation::buffer::BufferBuilder::operator= (const BufferBuilder & rhs) private delete
void geos::operation::buffer::BufferBuilder::setNoder (noding::Noder * newNoder) inline
Sets the noding::Noder to use during noding. This allows choosing fast but non-robust noding, or slower but robust noding.
Parameters
noder the noder to use
Definition at line 136 of file BufferBuilder.h.
References geos::operation::intersection::distance().
 { workingNoder = newNoder; }
void geos::operation::buffer::BufferBuilder::setWorkingPrecisionModel (const geom::PrecisionModel * pm) inline
Sets the precision model to use during the curve computation and noding, if it is different to the precision model of the Geometry. If the precision model is less than the precision of the Geometry precision model, the Geometry must have previously been rounded to that precision.
Parameters
pm the precision model to use
Definition at line 125 of file BufferBuilder.h.
{
     workingPrecisionModel=pm;
   }
Member Data Documentation
const BufferParameters& geos::operation::buffer::BufferBuilder::bufParams private
Definition at line 170 of file BufferBuilder.h.
geomgraph::EdgeList geos::operation::buffer::BufferBuilder::edgeList private
Definition at line 182 of file BufferBuilder.h.
const geom::GeometryFactory* geos::operation::buffer::BufferBuilder::geomFact private
Definition at line 180 of file BufferBuilder.h.
noding::IntersectionAdder* geos::operation::buffer::BufferBuilder::intersectionAdder private
Definition at line 176 of file BufferBuilder.h.
algorithm::LineIntersector* geos::operation::buffer::BufferBuilder::li private
Definition at line 174 of file BufferBuilder.h.
std::vector<geomgraph::Label *> geos::operation::buffer::BufferBuilder::newLabels private
Definition at line 184 of file BufferBuilder.h.
noding::Noder* geos::operation::buffer::BufferBuilder::workingNoder private
Definition at line 178 of file BufferBuilder.h.
const geom::PrecisionModel* geos::operation::buffer::BufferBuilder::workingPrecisionModel private
Definition at line 172 of file BufferBuilder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/BufferBuilder.h
/home/vicky/potree/geos/vicky/src/operation/buffer/BufferBuilder.cpp