GEOS: geos::linearref::LinearGeometryBuilder Class Reference
geos::linearref::LinearGeometryBuilder Class Reference
#include <LinearGeometryBuilder.h>
Public Member Functions
LinearGeometryBuilder (const geom::GeometryFactory *geomFact)
~LinearGeometryBuilder ()
void setIgnoreInvalidLines (bool ignoreInvalidLines)
void setFixInvalidLines (bool fixInvalidLines)
void add (const geom::Coordinate &pt)
void add (const geom::Coordinate &pt, bool allowRepeatedPoints)
geom::Coordinate getLastCoordinate () const
NOTE strk: why return by value ?
void endLine ()
Terminate the current LineString.
geom::Geometry * getGeometry ()
Private Types
typedef std::vector< geom::Geometry * > GeomPtrVect
Private Attributes
const geom::GeometryFactory * geomFact
GeomPtrVect lines
bool ignoreInvalidLines
bool fixInvalidLines
geom::CoordinateSequence * coordList
geom::Coordinate lastPt
Detailed Description
Builds a linear geometry (LineString or MultiLineString) incrementally (point-by-point).
Version
1.7
Definition at line 42 of file LinearGeometryBuilder.h.
Member Typedef Documentation
typedef std::vector<geom::Geometry *> geos::linearref::LinearGeometryBuilder::GeomPtrVect private
Definition at line 47 of file LinearGeometryBuilder.h.
Constructor & Destructor Documentation
geos::linearref::LinearGeometryBuilder::LinearGeometryBuilder (const geom::GeometryFactory * geomFact)
Definition at line 44 of file LinearGeometryBuilder.cpp.
                                                                             :
     geomFact(geomFact),
     ignoreInvalidLines(false),
     fixInvalidLines(false),
     coordList(nullptr) {}
geos::linearref::LinearGeometryBuilder::~LinearGeometryBuilder ()
Definition at line 152 of file LinearGeometryBuilder.cpp.
References lines.
 {
   for (GeomPtrVect::const_iterator i=lines.begin(), e=lines.end();
     i != e; ++i)
   {
     delete *i;
   }
 }
Member Function Documentation
void geos::linearref::LinearGeometryBuilder::add (const geom::Coordinate & pt)
Adds a point to the current line.
Parameters
pt the Coordinate to add
Definition at line 66 of file LinearGeometryBuilder.cpp.
Referenced by endLine().
 {
   add(pt, true);
 }
void geos::linearref::LinearGeometryBuilder::add (const geom::Coordinate & pt, bool allowRepeatedPoints)
Adds a point to the current line.
Parameters
pt the Coordinate to add
Definition at line 73 of file LinearGeometryBuilder.cpp.
References geos::geom::CoordinateSequence::add(), coordList, and lastPt.
 {
   if (!coordList)
     coordList = new CoordinateArraySequence();
   coordList->add(pt, allowRepeatedPoints);
   lastPt = pt;
 }
void geos::linearref::LinearGeometryBuilder::endLine ()
Terminate the current LineString.
Definition at line 90 of file LinearGeometryBuilder.cpp.
References add(), coordList, geos::geom::GeometryFactory::createLineString(), fixInvalidLines, geomFact, ignoreInvalidLines, geos::geom::CoordinateSequence::isEmpty(), lines, and geos::geom::CoordinateSequence::size().
Referenced by getGeometry().
 {
   if (!coordList)
   {
     return;
   }
   if (coordList->size() < 2)
   {
     if (ignoreInvalidLines)
     {
       if (coordList)
       {
         delete coordList;
         coordList = nullptr;
       }
       return;
     }
     else if (fixInvalidLines)
     {
       assert(!coordList->isEmpty()); // just to be sure
       // NOTE: we copy the point cause reallocation of
       //       vector memory will invalidate the reference
       //       to one of its elements.
       //
       //       We wouldn't have such problems with a vector
       //       of pointers (as used in JTS)...
       //
       Coordinate firstPoint = (*coordList)[0];
       add(firstPoint);
     }
   }
   LineString* line = nullptr;
   try
   {
     line = geomFact->createLineString(coordList);
   }
   catch (util::IllegalArgumentException ex)
   {
     // exception is due to too few points in line.
     // only propagate if not ignoring short lines
     if (! ignoreInvalidLines)
       throw ex;
   }
   if (line) lines.push_back(line);
   coordList = nullptr;
 }
Geometry * geos::linearref::LinearGeometryBuilder::getGeometry ()
Definition at line 142 of file LinearGeometryBuilder.cpp.
References geos::geom::GeometryFactory::buildGeometry(), endLine(), geomFact, and lines.
 {
   // end last line in case it was not done by user
   endLine();
   // NOTE: lines elements are cloned
   return geomFact->buildGeometry(lines);
 }
Coordinate geos::linearref::LinearGeometryBuilder::getLastCoordinate () const
NOTE strk: why return by value ?
Definition at line 83 of file LinearGeometryBuilder.cpp.
References lastPt.
 {
   return lastPt;
 }
void geos::linearref::LinearGeometryBuilder::setFixInvalidLines (bool fixInvalidLines)
Allows invalid lines to be ignored rather than causing Exceptions. An invalid line is one which has only one unique point.
Parameters
ignoreShortLines true if short lines are to be ignored
Definition at line 59 of file LinearGeometryBuilder.cpp.
References fixInvalidLines.
Referenced by geos::linearref::ExtractLineByLocation::computeLinear().
 {
   this->fixInvalidLines = fixInvalidLines;
 }
void geos::linearref::LinearGeometryBuilder::setIgnoreInvalidLines (bool ignoreInvalidLines)
Allows invalid lines to be ignored rather than causing Exceptions. An invalid line is one which has only one unique point.
Parameters
ignoreShortLines true if short lines are to be ignored
Definition at line 52 of file LinearGeometryBuilder.cpp.
References ignoreInvalidLines.
 {
   this->ignoreInvalidLines = ignoreInvalidLines;
 }
Member Data Documentation
geom::CoordinateSequence* geos::linearref::LinearGeometryBuilder::coordList private
Definition at line 54 of file LinearGeometryBuilder.h.
Referenced by add(), and endLine().
bool geos::linearref::LinearGeometryBuilder::fixInvalidLines private
Definition at line 53 of file LinearGeometryBuilder.h.
Referenced by endLine(), and setFixInvalidLines().
const geom::GeometryFactory* geos::linearref::LinearGeometryBuilder::geomFact private
Definition at line 45 of file LinearGeometryBuilder.h.
Referenced by endLine(), and getGeometry().
bool geos::linearref::LinearGeometryBuilder::ignoreInvalidLines private
Definition at line 52 of file LinearGeometryBuilder.h.
Referenced by endLine(), and setIgnoreInvalidLines().
geom::Coordinate geos::linearref::LinearGeometryBuilder::lastPt private
Definition at line 56 of file LinearGeometryBuilder.h.
Referenced by add(), and getLastCoordinate().
GeomPtrVect geos::linearref::LinearGeometryBuilder::lines private
Definition at line 50 of file LinearGeometryBuilder.h.
Referenced by endLine(), getGeometry(), and ~LinearGeometryBuilder().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/linearref/LinearGeometryBuilder.h
/home/vicky/potree/geos/vicky/src/linearref/LinearGeometryBuilder.cpp