GEOS: geos::util::TopologyException Class Reference
geos::util::TopologyException Class Reference
Indicates an invalid or inconsistent topological situation encountered during processing.
#include <geos.h>
Public Member Functions
TopologyException ()
TopologyException (const std::string &msg)
TopologyException (const std::string &msg, const geom::Coordinate &newPt)
~TopologyException () override throw ()
geom::Coordinate & getCoordinate ()
const char * what () const override throw ()
Private Attributes
geom::Coordinate pt
Detailed Description
Indicates an invalid or inconsistent topological situation encountered during processing.
Definition at line 35 of file TopologyException.h.
Constructor & Destructor Documentation
geos::util::TopologyException::TopologyException () inline
Definition at line 37 of file TopologyException.h.
     :
     GEOSException("TopologyException", "")
   {}
geos::util::TopologyException::TopologyException (const std::string & msg) inline
Definition at line 42 of file TopologyException.h.
     :
     GEOSException("TopologyException", msg)
   {}
geos::util::TopologyException::TopologyException (const std::string & msg, const geom::Coordinate & newPt) inline
Definition at line 47 of file TopologyException.h.
     :
     GEOSException("TopologyException", msg + " at " + newPt.toString()),
     pt(newPt)
   {}
geos::util::TopologyException::~TopologyException () throw () inline override
Definition at line 53 of file TopologyException.h.
 {}
Member Function Documentation
geom::Coordinate& geos::util::TopologyException::getCoordinate () inline
Definition at line 54 of file TopologyException.h.
 { return pt; }
const char* geos::util::GEOSException::what () const throw () inline override inherited
Definition at line 63 of file GEOSException.h.
Referenced by geos::operation::overlay::ElevationMatrix::add(), geos::geom::BinaryOp(), geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::snap::SnapIfNeededOverlayOp::getResultGeometry(), geos::operation::polygonize::EdgeRing::getRingInternal(), and geos::precision::EnhancedPrecisionOp::intersection().
   {
     return _msg.c_str();
   }
Member Data Documentation
geom::Coordinate geos::util::TopologyException::pt private
Definition at line 56 of file TopologyException.h.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/util/TopologyException.h