GEOS: geos::simplify::DouglasPeuckerLineSimplifier Class Reference
geos::simplify::DouglasPeuckerLineSimplifier Class Reference
Simplifies a linestring (sequence of points) using the standard Douglas-Peucker algorithm.
#include <DouglasPeuckerLineSimplifier.h>
Public Types
typedef std::vector< short int > BoolVect
typedef std::unique_ptr< BoolVect > BoolVectAutoPtr
typedef std::vector< geom::Coordinate > CoordsVect
typedef std::unique_ptr< CoordsVect > CoordsVectAutoPtr
Public Member Functions
DouglasPeuckerLineSimplifier (const CoordsVect &nPts)
void setDistanceTolerance (double nDistanceTolerance)
Sets the distance tolerance for the simplification.
CoordsVectAutoPtr simplify ()
Returns a newly allocated Coordinate vector, wrapped into an unique_ptr.
Static Public Member Functions
static CoordsVectAutoPtr simplify (const CoordsVect &nPts, double distanceTolerance)
Returns a newly allocated Coordinate vector, wrapped into an unique_ptr.
Private Member Functions
void simplifySection (std::size_t i, std::size_t j)
DouglasPeuckerLineSimplifier (const DouglasPeuckerLineSimplifier &other)=delete
DouglasPeuckerLineSimplifier & operator= (const DouglasPeuckerLineSimplifier &rhs)=delete
Private Attributes
const CoordsVect & pts
BoolVectAutoPtr usePt
double distanceTolerance
Detailed Description
Simplifies a linestring (sequence of points) using the standard Douglas-Peucker algorithm.
Definition at line 45 of file DouglasPeuckerLineSimplifier.h.
Member Typedef Documentation
typedef std::vector<short int> geos::simplify::DouglasPeuckerLineSimplifier::BoolVect
Definition at line 49 of file DouglasPeuckerLineSimplifier.h.
typedef std::unique_ptr<BoolVect> geos::simplify::DouglasPeuckerLineSimplifier::BoolVectAutoPtr
Definition at line 50 of file DouglasPeuckerLineSimplifier.h.
typedef std::vector<geom::Coordinate> geos::simplify::DouglasPeuckerLineSimplifier::CoordsVect
Definition at line 52 of file DouglasPeuckerLineSimplifier.h.
typedef std::unique_ptr<CoordsVect> geos::simplify::DouglasPeuckerLineSimplifier::CoordsVectAutoPtr
Definition at line 53 of file DouglasPeuckerLineSimplifier.h.
Constructor & Destructor Documentation
geos::simplify::DouglasPeuckerLineSimplifier::DouglasPeuckerLineSimplifier (const CoordsVect & nPts)
Definition at line 43 of file DouglasPeuckerLineSimplifier.cpp.
   :
   pts(nPts)
 {
 }
geos::simplify::DouglasPeuckerLineSimplifier::DouglasPeuckerLineSimplifier (const DouglasPeuckerLineSimplifier & other) private delete
Member Function Documentation
DouglasPeuckerLineSimplifier& geos::simplify::DouglasPeuckerLineSimplifier::operator= (const DouglasPeuckerLineSimplifier & rhs) private delete
void geos::simplify::DouglasPeuckerLineSimplifier::setDistanceTolerance (double nDistanceTolerance)
Sets the distance tolerance for the simplification.
All vertices in the simplified linestring will be within this distance of the original linestring.
Parameters
nDistanceTolerance the approximation tolerance to use
Definition at line 52 of file DouglasPeuckerLineSimplifier.cpp.
References distanceTolerance.
Referenced by simplify().
 {
   distanceTolerance=nDistanceTolerance;
 }
DouglasPeuckerLineSimplifier::CoordsVectAutoPtr geos::simplify::DouglasPeuckerLineSimplifier::simplify (const CoordsVect & nPts, double distanceTolerance) static
Returns a newly allocated Coordinate vector, wrapped into an unique_ptr.
Definition at line 33 of file DouglasPeuckerLineSimplifier.cpp.
References setDistanceTolerance(), and simplify().
Referenced by simplify().
 {
   DouglasPeuckerLineSimplifier simp(nPts);
   simp.setDistanceTolerance(distanceTolerance);
   return simp.simplify();
 }
DouglasPeuckerLineSimplifier::CoordsVectAutoPtr geos::simplify::DouglasPeuckerLineSimplifier::simplify ()
Returns a newly allocated Coordinate vector, wrapped into an unique_ptr.
Definition at line 60 of file DouglasPeuckerLineSimplifier.cpp.
References pts, simplifySection(), and usePt.
Referenced by geos::simplify::DPTransformer::transformCoordinates().
 {
   CoordsVectAutoPtr coordList(new CoordsVect());
   // empty coordlist is the simplest, won't simplify further
   if ( ! pts.size() ) return coordList;
   usePt = BoolVectAutoPtr(new BoolVect(pts.size(), true));
   simplifySection(0, pts.size() - 1);
   for (std::size_t i=0, n=pts.size(); i<n; ++i)
   {
     if ( usePt->operator[](i) )
     {
       coordList->push_back(pts[i]);
     }
   }
   // unique_ptr transfer ownership to its
   // returned copy
   return coordList;
 }
void geos::simplify::DouglasPeuckerLineSimplifier::simplifySection (std::size_t i, std::size_t j) private
Definition at line 85 of file DouglasPeuckerLineSimplifier.cpp.
References geos::geom::LineSegment::distance(), geos::operation::intersection::distance(), distanceTolerance, pts, and usePt.
Referenced by simplify().
 {
   if ( (i+1) == j ) return;
   geos::geom::LineSegment seg(pts[i], pts[j]);
   double maxDistance = -1.0;
   std::size_t maxIndex = i;
   for (std::size_t k=i+1; k<j; k++)
   {
     double distance = seg.distance(pts[k]);
     if (distance > maxDistance) {
       maxDistance = distance;
       maxIndex = k;
     }
   }
   if (maxDistance <= distanceTolerance) {
     for(std::size_t k =i+1; k<j; k++)
     {
       usePt->operator[](k) = false;
     }
   }
   else {
     simplifySection(i, maxIndex);
     simplifySection(maxIndex, j);
   }
 }
Member Data Documentation
double geos::simplify::DouglasPeuckerLineSimplifier::distanceTolerance private
Definition at line 86 of file DouglasPeuckerLineSimplifier.h.
Referenced by setDistanceTolerance(), and simplifySection().
const CoordsVect& geos::simplify::DouglasPeuckerLineSimplifier::pts private
Definition at line 84 of file DouglasPeuckerLineSimplifier.h.
Referenced by simplify(), and simplifySection().
BoolVectAutoPtr geos::simplify::DouglasPeuckerLineSimplifier::usePt private
Definition at line 85 of file DouglasPeuckerLineSimplifier.h.
Referenced by simplify(), and simplifySection().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/simplify/DouglasPeuckerLineSimplifier.h
/home/vicky/potree/geos/vicky/src/simplify/DouglasPeuckerLineSimplifier.cpp