GEOS: geos::operation::overlay::EdgeSetNoder Class Reference
geos::operation::overlay::EdgeSetNoder Class Reference
Nodes a set of edges.
#include <EdgeSetNoder.h>
Public Member Functions
EdgeSetNoder (algorithm::LineIntersector *newLi)
~EdgeSetNoder ()
void addEdges (std::vector< geomgraph::Edge * > *edges)
std::vector< geomgraph::Edge * > * getNodedEdges ()
Private Attributes
algorithm::LineIntersector * li
std::vector< geomgraph::Edge * > * inputEdges
Detailed Description
Nodes a set of edges.
Takes one or more sets of edges and constructs a new set of edges consisting of all the split edges created by noding the input edges together
Definition at line 47 of file EdgeSetNoder.h.
Constructor & Destructor Documentation
geos::operation::overlay::EdgeSetNoder::EdgeSetNoder (algorithm::LineIntersector * newLi) inline
Definition at line 52 of file EdgeSetNoder.h.
     :
     li(newLi),
     inputEdges(new std::vector<geomgraph::Edge*>())
   {}
geos::operation::overlay::EdgeSetNoder::~EdgeSetNoder () inline
Definition at line 58 of file EdgeSetNoder.h.
                   {
     delete inputEdges; // TODO: avoid heap allocation
   }
Member Function Documentation
void geos::operation::overlay::EdgeSetNoder::addEdges (std::vector< geomgraph::Edge * > * edges)
Definition at line 39 of file EdgeSetNoder.cpp.
 {
   inputEdges->insert(inputEdges->end(),edges->begin(),edges->end());
 }
vector< Edge * > * geos::operation::overlay::EdgeSetNoder::getNodedEdges ()
Definition at line 45 of file EdgeSetNoder.cpp.
References geos::geomgraph::EdgeIntersectionList::addSplitEdges(), geos::geomgraph::index::EdgeSetIntersector::computeIntersections(), and geos::geomgraph::Edge::getEdgeIntersectionList().
 {
   EdgeSetIntersector *esi=new SimpleMCSweepLineIntersector();
   SegmentIntersector *si=new SegmentIntersector(li,true,false);
   esi->computeIntersections(inputEdges,si,true);
   //Debug.println("has proper int = " + si.hasProperIntersection());
   vector<Edge*> *splitEdges=new vector<Edge*>();
   for(int i=0;i<(int)inputEdges->size();i++) {
     Edge* e=(*inputEdges)[i];
     e->getEdgeIntersectionList().addSplitEdges(splitEdges);
   }
   return splitEdges;
 }
Member Data Documentation
std::vector<geomgraph::Edge*>* geos::operation::overlay::EdgeSetNoder::inputEdges private
Definition at line 50 of file EdgeSetNoder.h.
algorithm::LineIntersector* geos::operation::overlay::EdgeSetNoder::li private
Definition at line 49 of file EdgeSetNoder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/EdgeSetNoder.h
/home/vicky/potree/geos/vicky/src/operation/overlay/EdgeSetNoder.cpp