GEOS: geos::geom::LineString Class Reference
geos::geom::LineString Class Reference
#include <LineString.h>
Public Types
typedef std::vector< const LineString * > ConstVect
A vector of const LineString pointers.
using NonConstVect = std::vector< Geometry * >
A vector of non-const Geometry pointers.
using Ptr = std::unique_ptr< Geometry >
An unique_ptr of Geometry.
Public Member Functions
~LineString () override
Geometry * clone () const override
Creates and returns a full copy of this LineString object (including all coordinates contained by it)
CoordinateSequence * getCoordinates () const override
Returns this Geometry vertices. Caller takes ownership of the returned object.
const CoordinateSequence * getCoordinatesRO () const
Returns a read-only pointer to internal CoordinateSequence.
virtual const Coordinate & getCoordinateN (int n) const
Dimension::DimensionType getDimension () const override
Returns line dimension (1)
int getBoundaryDimension () const override
Returns Dimension::False for a closed LineString, 0 otherwise (LineString boundary is a MultiPoint)
int getCoordinateDimension () const override
Returns coordinate dimension.
Geometry * getBoundary () const override
Returns a MultiPoint. Empty for closed LineString, a Point for each vertex otherwise.
bool isEmpty () const override
Returns whether or not the set of points in this Geometry is empty.
std::size_t getNumPoints () const override
Returns the count of this Geometrys vertices.
virtual Point * getPointN (std::size_t n) const
virtual Point * getStartPoint () const
Return the start point of the LineString or NULL if this is an EMPTY LineString.
virtual Point * getEndPoint () const
Return the end point of the LineString or NULL if this is an EMPTY LineString.
virtual bool isClosed () const
virtual bool isRing () const
std::string getGeometryType () const override
Return a string representation of this Geometry type.
GeometryTypeId getGeometryTypeId () const override
Return an integer representation of this Geometry type.
virtual bool isCoordinate (Coordinate &pt) const
bool equalsExact (const Geometry *other, double tolerance=0) const override
Returns true iff the two Geometrys are of the same type and their vertices corresponding by index are equal up to a specified tolerance.
void apply_rw (const CoordinateFilter *filter) override
void apply_ro (CoordinateFilter *filter) const override
void apply_rw (GeometryFilter *filter) override
void apply_ro (GeometryFilter *filter) const override
void apply_rw (GeometryComponentFilter *filter) override
void apply_ro (GeometryComponentFilter *filter) const override
void apply_rw (CoordinateSequenceFilter &filter) override
void apply_ro (CoordinateSequenceFilter &filter) const override
void normalize () override
Normalizes a LineString.
int compareToSameClass (const Geometry *ls) const override
const Coordinate * getCoordinate () const override
Returns a vertex of this Geometry, or NULL if this is the empty geometry.
double getLength () const override
Returns the length of this Geometry.
Geometry * reverse () const override
const GeometryFactory * getFactory () const
Gets the factory which contains the context in which this geometry was created.
void setUserData (void *newUserData)
A simple scheme for applications to add their own custom data to a Geometry. An example use might be to add an object representing a Coordinate Reference System.
void * getUserData () const
Gets the user data object for this geometry, if any.
virtual int getSRID () const
virtual void setSRID (int newSRID)
const PrecisionModel * getPrecisionModel () const
Get the PrecisionModel used to create this Geometry.
virtual bool isSimple () const
Returns false if the Geometry not simple.
virtual std::size_t getNumGeometries () const
virtual const Geometry * getGeometryN (std::size_t) const
virtual bool isValid () const
Tests the validity of this Geometry.
virtual bool isRectangle () const
Polygon overrides to check for actual rectangle.
virtual Geometry * getEnvelope () const
Returns this Geometrys bounding box.
virtual const Envelope * getEnvelopeInternal () const
Returns the minimum and maximum x and y values in this Geometry, or a null Envelope if this Geometry is empty.
virtual bool disjoint (const Geometry *other) const
virtual bool touches (const Geometry *other) const
Returns true if the DE-9IM intersection matrix for the two Geometrys is FT*******, F**T***** or F***T****.
virtual bool intersects (const Geometry *g) const
Returns true if disjoint returns false.
virtual bool crosses (const Geometry *g) const
virtual bool within (const Geometry *g) const
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*F**F***.
virtual bool contains (const Geometry *g) const
Returns true if other.within(this) returns true.
virtual bool overlaps (const Geometry *g) const
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*T***T** (for two points or two surfaces) 1*T***T** (for two curves).
virtual bool relate (const Geometry *g, const std::string &intersectionPattern) const
Returns true if the elements in the DE-9IM intersection matrix for the two Geometrys match the elements in intersectionPattern.
bool relate (const Geometry &g, const std::string &intersectionPattern) const
virtual IntersectionMatrix * relate (const Geometry *g) const
Returns the DE-9IM intersection matrix for the two Geometrys.
IntersectionMatrix * relate (const Geometry &g) const
virtual bool equals (const Geometry *g) const
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*F**FFF*.
bool covers (const Geometry *g) const
Returns true if this geometry covers the specified geometry.
bool coveredBy (const Geometry *g) const
Tests whether this geometry is covered by the specified geometry.
virtual std::string toString () const
Returns the Well-known Text representation of this Geometry.
virtual std::string toText () const
virtual Geometry * buffer (double distance) const
Returns a buffer region around this Geometry having the given width.
virtual Geometry * buffer (double distance, int quadrantSegments) const
Returns a buffer region around this Geometry having the given width and with a specified number of segments used to approximate curves.
virtual Geometry * buffer (double distance, int quadrantSegments, int endCapStyle) const
Computes a buffer area around this geometry having the given width and with a specified accuracy of approximation for circular arcs, and using a specified end cap style.
virtual Geometry * convexHull () const
Returns the smallest convex Polygon that contains all the points in the Geometry.
virtual Geometry * intersection (const Geometry *other) const
Returns a Geometry representing the points shared by this Geometry and other.
Geometry * Union (const Geometry *other) const
Returns a Geometry representing all the points in this Geometry and other.
Ptr Union () const
virtual Geometry * difference (const Geometry *other) const
Returns a Geometry representing the points making up this Geometry that do not make up other.
virtual Geometry * symDifference (const Geometry *other) const
Returns a set combining the points in this Geometry not in other, and the points in other not in this Geometry.
template<class T >
void applyComponentFilter (T &f) const
Apply a fiter to each component of this geometry. The filter is expected to provide a .filter(const Geometry*) method.
virtual int compareTo (const Geometry *geom) const
virtual double distance (const Geometry *g) const
Returns the minimum distance between this Geometry and the Geometry g.
virtual double getArea () const
Returns the area of this Geometry.
virtual bool isWithinDistance (const Geometry *geom, double cDistance) const
Tests whether the distance from this Geometry to another is less than or equal to a specified value.
virtual Point * getCentroid () const
Computes the centroid of this Geometry.
virtual bool getCentroid (Coordinate &ret) const
Computes the centroid of this Geometry as a Coordinate.
virtual Point * getInteriorPoint () const
Computes an interior point of this Geometry.
virtual void geometryChanged ()
void geometryChangedAction ()
Notifies this Geometry that its Coordinates have been changed by an external party.
Protected Member Functions
LineString (const LineString &ls)
LineString (CoordinateSequence *pts, const GeometryFactory *newFactory)
Constructs a LineString taking ownership the given CoordinateSequence.
LineString (CoordinateSequence::Ptr pts, const GeometryFactory *newFactory)
Hopefully cleaner version of the above.
Envelope::Ptr computeEnvelopeInternal () const override
virtual bool isEquivalentClass (const Geometry *other) const
Returns whether the two Geometrys are equal, from the point of view of the equalsExact method.
int compare (std::vector< Coordinate > a, std::vector< Coordinate > b) const
int compare (std::vector< Geometry * > a, std::vector< Geometry * > b) const
bool equal (const Coordinate &a, const Coordinate &b, double tolerance) const
Static Protected Member Functions
static bool hasNonEmptyElements (const std::vector< Geometry * > *geometries)
Returns true if the array contains any non-empty Geometrys.
static bool hasNullElements (const CoordinateSequence *list)
Returns true if the CoordinateSequence contains any null elements.
static bool hasNullElements (const std::vector< Geometry * > *lrs)
Returns true if the vector contains any null elements.
static void checkNotGeometryCollection (const Geometry *g)
Protected Attributes
CoordinateSequence::Ptr points
std::unique_ptr< Envelope > envelope
The bounding box of this Geometry.
int SRID
Private Member Functions
void validateConstruction ()
Friends
class GeometryFactory
Detailed Description
Models an OGC-style LineString.
A LineString consists of a sequence of two or more vertices, along with all points along the linearly-interpolated curves (line segments) between each pair of consecutive vertices. Consecutive vertices may be equal. The line segments in the line may intersect each other (in other words, the linestring may "curl back" in itself and self-intersect). Linestrings with exactly two identical points are invalid.
A linestring must have either 0 or 2 or more points. If these conditions are not met, the constructors throw an IllegalArgumentException.
Definition at line 70 of file LineString.h.
Member Typedef Documentation
typedef std::vector<const LineString *> geos::geom::LineString::ConstVect
A vector of const LineString pointers.
Definition at line 77 of file LineString.h.
using geos::geom::Geometry::NonConstVect = std::vector<Geometry *> inherited
A vector of non-const Geometry pointers.
Definition at line 187 of file Geometry.h.
using geos::geom::Geometry::Ptr = std::unique_ptr<Geometry> inherited
An unique_ptr of Geometry.
Definition at line 190 of file Geometry.h.
Constructor & Destructor Documentation
geos::geom::LineString::~LineString () override
Definition at line 109 of file LineString.cpp.
 {
   //delete points;
 }
geos::geom::LineString::LineString (const LineString & ls) protected
Definition at line 49 of file LineString.cpp.
   :
   Geometry(ls),
   points(ls.points->clone())
 {
   //points=ls.points->clone();
 }
geos::geom::LineString::LineString (CoordinateSequence * pts, const GeometryFactory * newFactory) protected
Constructs a LineString taking ownership the given CoordinateSequence.
Definition at line 89 of file LineString.cpp.
References validateConstruction().
   :
   Geometry(factory),
   points(newCoords)
 {
   validateConstruction();
 }
geos::geom::LineString::LineString (CoordinateSequence::Ptr pts, const GeometryFactory * newFactory) protected
Hopefully cleaner version of the above.
Definition at line 99 of file LineString.cpp.
References validateConstruction().
   :
   Geometry(factory),
   points(std::move(newCoords))
 {
   validateConstruction();
 }
Member Function Documentation
void geos::geom::LineString::apply_ro (CoordinateFilter * filter) const override virtual
Implements geos::geom::Geometry.
Definition at line 314 of file LineString.cpp.
References points.
Referenced by geos::geom::Polygon::apply_ro().
 {
   assert(points.get());
   points->apply_ro(filter);
 }
void geos::geom::LineString::apply_ro (GeometryFilter * filter) const override virtual
Reimplemented from geos::geom::Geometry.
Definition at line 326 of file LineString.cpp.
References geos::geom::GeometryFilter::filter_ro().
 {
   assert(filter);
   filter->filter_ro(this);
 }
void geos::geom::LineString::apply_ro (GeometryComponentFilter * filter) const override virtual
Reimplemented from geos::geom::Geometry.
Definition at line 389 of file LineString.cpp.
References geos::geom::GeometryComponentFilter::filter_ro().
 {
   assert(filter);
   filter->filter_ro(this);
 }
void geos::geom::LineString::apply_ro (CoordinateSequenceFilter & filter) const override virtual
Performs a read-only operation on the coordinates in this Geometry's CoordinateSequences.
Parameters
filter the filter to apply
Implements geos::geom::Geometry.
Definition at line 409 of file LineString.cpp.
References geos::geom::CoordinateSequenceFilter::filter_ro(), geos::geom::CoordinateSequenceFilter::isDone(), and points.
 {
   size_t npts=points->size();
   if (!npts) return;
   for (size_t i = 0; i<npts; ++i)
   {
     filter.filter_ro(*points, i);
     if (filter.isDone()) break;
   }
   //if (filter.isGeometryChanged()) geometryChanged();
 }
void geos::geom::LineString::apply_rw (const CoordinateFilter * filter) override virtual
Implements geos::geom::Geometry.
Definition at line 307 of file LineString.cpp.
References points.
Referenced by geos::geom::Polygon::apply_rw().
 {
   assert(points.get());
   points->apply_rw(filter);
 }
void geos::geom::LineString::apply_rw (GeometryFilter * filter) override virtual
Reimplemented from geos::geom::Geometry.
Definition at line 320 of file LineString.cpp.
References geos::geom::GeometryFilter::filter_rw().
 {
   assert(filter);
   filter->filter_rw(this);
 }
void geos::geom::LineString::apply_rw (GeometryComponentFilter * filter) override virtual
Reimplemented from geos::geom::Geometry.
Definition at line 382 of file LineString.cpp.
References geos::geom::GeometryComponentFilter::filter_rw().
 {
   assert(filter);
   filter->filter_rw(this);
 }
void geos::geom::LineString::apply_rw (CoordinateSequenceFilter & filter) override virtual
Performs an operation on the coordinates in this Geometry's CoordinateSequences. If the filter reports that a coordinate value has been changed, geometryChanged will be called automatically.
Parameters
filter the filter to apply
Implements geos::geom::Geometry.
Definition at line 396 of file LineString.cpp.
References geos::geom::CoordinateSequenceFilter::filter_rw(), geos::geom::Geometry::geometryChanged(), geos::geom::CoordinateSequenceFilter::isDone(), geos::geom::CoordinateSequenceFilter::isGeometryChanged(), and points.
 {
   size_t npts=points->size();
   if (!npts) return;
   for (size_t i = 0; i<npts; ++i)
   {
     filter.filter_rw(*points, i);
     if (filter.isDone()) break;
   }
   if (filter.isGeometryChanged()) geometryChanged();
 }
template<class T > void geos::geom::Geometry::applyComponentFilter (T & f) const inline inherited
Apply a fiter to each component of this geometry. The filter is expected to provide a .filter(const Geometry*) method.
I intend similar templated methods to replace all the virtual apply_rw and apply_ro functions... –strk(2005-02-06);
Definition at line 703 of file Geometry.h.
References geos::operation::intersection::distance().
Referenced by geos::operation::linemerge::LineMerger::add(), and geos::operation::linemerge::LineSequencer::add().
   {
     for(std::size_t i=0, n=getNumGeometries(); i<n; ++i)
       f.filter(getGeometryN(i));
   }
Geometry * geos::geom::Geometry::buffer (double distance) const virtual inherited
Returns a buffer region around this Geometry having the given width.
Exceptions
util::TopologyException if a robustness error occurs
Definition at line 481 of file Geometry.cpp.
Referenced by geos::precision::EnhancedPrecisionOp::buffer(), geos::operation::buffer::BufferOp::bufferFixedPrecision(), geos::simplify::DPTransformer::createValidArea(), geos::precision::GeometryPrecisionReducer::fixPolygonalTopology(), and GEOSBuffer_r().
 {
   return BufferOp::bufferOp(this, distance);
 }
Geometry * geos::geom::Geometry::buffer (double distance, int quadrantSegments) const virtual inherited
Returns a buffer region around this Geometry having the given width and with a specified number of segments used to approximate curves.
Exceptions
util::TopologyException if a robustness error occurs
Definition at line 487 of file Geometry.cpp.
 {
   return BufferOp::bufferOp(this, distance, quadrantSegments);
 }
Geometry * geos::geom::Geometry::buffer (double distance, int quadrantSegments, int endCapStyle) const virtual inherited
Computes a buffer area around this geometry having the given width and with a specified accuracy of approximation for circular arcs, and using a specified end cap style.
Buffer area boundaries can contain circular arcs. To represent these arcs using linear geometry they must be approximated with line segments.
The quadrantSegments argument allows controlling the accuracy of the approximation by specifying the number of line segments used to represent a quadrant of a circle
The end cap style specifies the buffer geometry that will be created at the ends of linestrings. The styles provided are:
BufferOp::CAP_ROUND - (default) a semi-circle
BufferOp::CAP_BUTT - a straight line perpendicular to the end segment
BufferOp::CAP_SQUARE - a half-square
Parameters
distance the width of the buffer (may be positive, negative or 0)
quadrantSegments the number of line segments used to represent a quadrant of a circle
endCapStyle the end cap style to use
Returns
an area geometry representing the buffer region
Exceptions
util::TopologyException if a robustness error occurs
See also
BufferOp
Definition at line 493 of file Geometry.cpp.
 {
   return BufferOp::bufferOp(this, distance, quadrantSegments, endCapStyle);
 }
void geos::geom::Geometry::checkNotGeometryCollection (const Geometry * g) static protected inherited
Definition at line 682 of file Geometry.cpp.
Referenced by geos::geom::Geometry::isSimple().
 {
   if ((typeid(*g)==typeid(GeometryCollection))) {
     throw  geos::util::IllegalArgumentException("This method does not support GeometryCollection arguments\n");
   }
 }
Geometry * geos::geom::LineString::clone () const inline override virtual
Creates and returns a full copy of this LineString object (including all coordinates contained by it)
Returns
A clone of this instance
Implements geos::geom::Geometry.
Definition at line 219 of file LineString.h.
Referenced by geos::operation::linemerge::LineSequencer::buildSequencedGeometry(), geos::operation::intersection::RectangleIntersection::clip_linestring(), geos::operation::intersection::RectangleIntersection::clip_polygon_to_linestrings(), geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons(), geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), and reverse().
{
   return new LineString(*this);
 }
int geos::geom::Geometry::compare (std::vector< Coordinate > a, std::vector< Coordinate > b) const protected inherited
Definition at line 723 of file Geometry.cpp.
References geos::geom::Coordinate::compareTo().
Referenced by geos::geom::GeometryCollection::compareToSameClass().
 {
   size_t i=0;
   size_t j=0;
   while (i<a.size() && j<b.size()) {
     Coordinate& aCoord=a[i];
     Coordinate& bCoord=b[j];
     int comparison=aCoord.compareTo(bCoord);
     if (comparison!=0) {
       return comparison;
     }
     i++;
     j++;
   }
   if (i<a.size()) {
     return 1;
   }
   if (j<b.size()) {
     return -1;
   }
   return 0;
 }
int geos::geom::Geometry::compare (std::vector< Geometry * > a, std::vector< Geometry * > b) const protected inherited
Definition at line 747 of file Geometry.cpp.
References geos::geom::Geometry::compareTo().
 {
   size_t i=0;
   size_t j=0;
   while (i<a.size() && j<b.size()) {
     Geometry *aGeom=a[i];
     Geometry *bGeom=b[j];
     int comparison=aGeom->compareTo(bGeom);
     if (comparison!=0) {
       return comparison;
     }
     i++;
     j++;
   }
   if (i<a.size()) {
     return 1;
   }
   if (j<b.size()) {
     return -1;
   }
   return 0;
 }
int geos::geom::Geometry::compareTo (const Geometry * geom) const virtual inherited
Definition at line 652 of file Geometry.cpp.
References geos::geom::Geometry::compareToSameClass(), geos::geom::Geometry::getClassSortIndex(), and geos::geom::Geometry::isEmpty().
Referenced by geos::geom::Geometry::compare(), geos::geom::LineStringLT::operator()(), and geos::geom::GeometryGreaterThen::operator()().
 {
   // compare to self
   if ( this == geom ) return 0;
   if (getClassSortIndex()!=geom->getClassSortIndex()) {
     return getClassSortIndex()-geom->getClassSortIndex();
   }
   if (isEmpty() && geom->isEmpty()) {
     return 0;
   }
   if (isEmpty()) {
     return -1;
   }
   if (geom->isEmpty()) {
     return 1;
   }
   return compareToSameClass(geom);
 }
int geos::geom::LineString::compareToSameClass (const Geometry * ls) const override virtual
Implements geos::geom::Geometry.
Definition at line 351 of file LineString.cpp.
References points.
Referenced by geos::geom::Polygon::compareToSameClass().
 {
   const LineString *line=dynamic_cast<const LineString*>(ls);
   assert(line);
   // MD - optimized implementation
   std::size_t mynpts=points->getSize();
   std::size_t othnpts=line->points->getSize();
   if ( mynpts > othnpts ) return 1;
   if ( mynpts < othnpts ) return -1;
   for (std::size_t i=0; i<mynpts; i++)
   {
     int cmp=points->getAt(i).compareTo(line->points->getAt(i));
     if (cmp) return cmp;
   }
   return 0;
 }
Envelope::Ptr geos::geom::LineString::computeEnvelopeInternal () const override protected virtual
Implements geos::geom::Geometry.
Definition at line 254 of file LineString.cpp.
References isEmpty(), points, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   if (isEmpty()) {
     // We don't return NULL here
     // as it would indicate "unknown"
     // envelope. In this case we
     // *know* the envelope is EMPTY.
     return Envelope::Ptr(new Envelope());
   }
   assert(points.get());
   const Coordinate& c=points->getAt(0);
   double minx = c.x;
   double miny = c.y;
   double maxx = c.x;
   double maxy = c.y;
   std::size_t npts=points->getSize();
   for (std::size_t i=1; i<npts; i++) {
     const Coordinate &c=points->getAt(i);
     minx = minx < c.x ? minx : c.x;
     maxx = maxx > c.x ? maxx : c.x;
     miny = miny < c.y ? miny : c.y;
     maxy = maxy > c.y ? maxy : c.y;
   }
   // caller expects a newly allocated Envelope.
   // this function won't be called twice, unless
   // cached Envelope is invalidated (set to NULL)
   return Envelope::Ptr(new Envelope(minx, maxx, miny, maxy));
 }
bool geos::geom::Geometry::contains (const Geometry * g) const virtual inherited
Returns true if other.within(this) returns true.
Definition at line 391 of file Geometry.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::isRectangle(), and geos::geom::Geometry::relate().
Referenced by geos::geom::prep::BasicPreparedGeometry::contains(), geos::geom::prep::PreparedPolygonContains::fullTopologicalPredicate(), GEOSContains_r(), and geos::geom::Geometry::within().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->contains(g->getEnvelopeInternal()))
     return false;
 #endif
   // optimization for rectangle arguments
   if (isRectangle()) {
     const Polygon* p = dynamic_cast<const Polygon*>(this);
     return predicate::RectangleContains::contains(*p, *g);
   }
   // Incorrect: contains is not commutative
   //if (g->isRectangle()) {
   //  return predicate::RectangleContains::contains((const Polygon&)*g, *this);
   //}
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isContains();
   return res;
 }
Geometry * geos::geom::Geometry::convexHull () const virtual inherited
Returns the smallest convex Polygon that contains all the points in the Geometry.
Reimplemented in geos::geom::Polygon.
Definition at line 499 of file Geometry.cpp.
References geos::algorithm::ConvexHull::getConvexHull().
Referenced by geos::geom::Polygon::convexHull(), and GEOSConvexHull_r().
 {
   return ConvexHull(this).getConvexHull();
 }
bool geos::geom::Geometry::coveredBy (const Geometry * g) const inline inherited
Tests whether this geometry is covered by the specified geometry.
The coveredBy predicate has the following equivalent definitions:
Every point of this geometry is a point of the other geometry.
The DE-9IM Intersection Matrix for the two geometries matches [T*F**F***] or [*TF**F***] or [**FT*F***] or [**F*TF***]
g.covers(this) (coveredBy is the converse of covers)
If either geometry is empty, the value of this predicate is false.
This predicate is similar to within, but is more inclusive (i.e. returns true for more cases).
Parameters
g the Geometry with which to compare this Geometry
Returns
true if this Geometry is covered by g
See also
Geometry::within
Geometry::covers
Definition at line 518 of file Geometry.h.
References geos::geom::Geometry::covers(), and geos::operation::intersection::distance().
Referenced by geos::geom::prep::BasicPreparedGeometry::coveredBy(), and GEOSCoveredBy_r().
{
     return g->covers(this);
   }
bool geos::geom::Geometry::covers (const Geometry * g) const inherited
Returns true if this geometry covers the specified geometry.
The covers predicate has the following equivalent definitions:
Every point of the other geometry is a point of this geometry.
The DE-9IM Intersection Matrix for the two geometries is T*****FF* or *T****FF* or ***T**FF* or ****T*FF*
g.coveredBy(this) (covers is the inverse of coveredBy)
If either geometry is empty, the value of this predicate is false.
This predicate is similar to contains, but is more inclusive (i.e. returns true for more cases). In particular, unlike contains it does not distinguish between points in the boundary and in the interior of geometries. For most situations, covers should be used in preference to contains. As an added benefit, covers is more amenable to optimization, and hence should be more performant.
Parameters
g the Geometry with which to compare this Geometry
Returns
true if this Geometry covers g
See also
Geometry::contains
Geometry::coveredBy
Definition at line 351 of file Geometry.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::isRectangle(), and geos::geom::Geometry::relate().
Referenced by geos::geom::Geometry::coveredBy(), geos::geom::prep::BasicPreparedGeometry::covers(), geos::geom::prep::PreparedPolygonCovers::fullTopologicalPredicate(), and GEOSCovers_r().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->covers(g->getEnvelopeInternal()))
     return false;
 #endif
   // optimization for rectangle arguments
   if (isRectangle()) {
     // since we have already tested that the test envelope
     // is covered
     return true;
   }
   unique_ptr<IntersectionMatrix> im(relate(g));
   return im->isCovers();
 }
bool geos::geom::Geometry::crosses (const Geometry * g) const virtual inherited
Tests whether this geometry crosses the specified geometry.
The crosses predicate has the following equivalent definitions:
The geometries have some but not all interior points in common.
The DE-9IM Intersection Matrix for the two geometries matches
[T*T******] (for P/L, P/A, and L/A situations)
[T*****T**] (for L/P, A/P, and A/L situations)
[0********] (for L/L situations) For any other combination of dimensions this predicate returns false.
The SFS defined this predicate only for P/L, P/A, L/L, and L/A situations. JTS extends the definition to apply to L/P, A/P and A/L situations as well, in order to make the relation symmetric.
Parameters
g the Geometry with which to compare this Geometry
Returns
true if the two Geometrys cross.
Definition at line 372 of file Geometry.cpp.
References geos::geom::Geometry::getDimension(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::intersects(), and geos::geom::Geometry::relate().
Referenced by geos::geom::prep::BasicPreparedGeometry::crosses(), and GEOSCrosses_r().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return false;
 #endif
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isCrosses(getDimension(), g->getDimension());
   return res;
 }
Geometry * geos::geom::Geometry::difference (const Geometry * other) const virtual inherited
Returns a Geometry representing the points making up this Geometry that do not make up other.
Exceptions
util::TopologyException if a robustness error occurs
util::IllegalArgumentException if either input is a non-empty GeometryCollection
Definition at line 598 of file Geometry.cpp.
References geos::geom::BinaryOp(), geos::geom::Geometry::clone(), geos::geom::GeometryFactory::createGeometryCollection(), geos::geom::Geometry::getFactory(), and geos::geom::Geometry::isEmpty().
Referenced by geos::precision::EnhancedPrecisionOp::difference(), and GEOSDifference_r().
 {
   // special case: if A.isEmpty ==> empty; if B.isEmpty ==> A
   if (isEmpty()) return getFactory()->createGeometryCollection();
   if (other->isEmpty()) return clone();
   return BinaryOp(this, other, overlayOp(OverlayOp::opDIFFERENCE)).release();
 }
bool geos::geom::Geometry::disjoint (const Geometry * other) const virtual inherited
Tests whether this geometry is disjoint from the specified geometry.
The disjoint predicate has the following equivalent definitions:
The two geometries have no point in common
The DE-9IM Intersection Matrix for the two geometries matches [FF*FF****]
! g.intersects(this) (disjoint is the inverse of intersects)
Parameters
g the Geometry with which to compare this Geometry
Returns
true if the two Geometrys are disjoint
See also
Geometry::intersects
Definition at line 284 of file Geometry.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::intersects(), and geos::geom::Geometry::relate().
Referenced by GEOSDisjoint_r().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return true;
 #endif
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isDisjoint();
   return res;
 }
double geos::geom::Geometry::distance (const Geometry * other) const virtual inherited
Returns the minimum distance between this Geometry and the Geometry g.
Returns the minimum distance between this Geometry and the other Geometry
Parameters
other the Geometry from which to compute the distance
Definition at line 777 of file Geometry.cpp.
References geos::operation::intersection::distance().
Referenced by geos::index::strtree::GeometryItemDistance::distance(), GEOSDistance_r(), and geos::geom::Geometry::isWithinDistance().
 {
   return DistanceOp::distance(this, other);
 }
bool geos::geom::Geometry::equal (const Coordinate & a, const Coordinate & b, double tolerance) const protected inherited
Definition at line 826 of file Geometry.cpp.
References geos::geom::Coordinate::distance().
Referenced by geos::geom::Point::equalsExact(), and equalsExact().
 {
   if (tolerance==0)
   {
     return a == b; // 2D only !!!
   }
   //double dist=a.distance(b);
   return a.distance(b)<=tolerance;
 }
bool geos::geom::Geometry::equals (const Geometry * g) const virtual inherited
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*F**FFF*.
Definition at line 436 of file Geometry.cpp.
References geos::geom::Geometry::getDimension(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::isEmpty(), and geos::geom::Geometry::relate().
Referenced by GEOSEquals_r().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->equals(g->getEnvelopeInternal()))
     return false;
 #endif
   if (isEmpty()) return g->isEmpty();
   else if (g->isEmpty()) return isEmpty();
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isEquals(getDimension(), g->getDimension());
   return res;
 }
bool geos::geom::LineString::equalsExact (const Geometry * other, double tolerance = 0) const override virtual
Returns true iff the two Geometrys are of the same type and their vertices corresponding by index are equal up to a specified tolerance.
Implements geos::geom::Geometry.
Definition at line 286 of file LineString.cpp.
References geos::geom::Geometry::equal(), geos::geom::Geometry::isEquivalentClass(), and points.
Referenced by geos::geom::Polygon::equalsExact().
 {
   if (!isEquivalentClass(other)) {
     return false;
   }
   const LineString *otherLineString=dynamic_cast<const LineString*>(other);
   assert(otherLineString);
   size_t npts=points->getSize();
   if (npts!=otherLineString->points->getSize()) {
     return false;
   }
   for (size_t i=0; i<npts; ++i) {
     if (!equal(points->getAt(i),otherLineString->points->getAt(i),tolerance)) {
       return false;
     }
   }
   return true;
 }
void geos::geom::Geometry::geometryChanged () virtual inherited
Notifies this Geometry that its Coordinates have been changed by an external party (using a CoordinateFilter, for example). The Geometry will flush and/or update any information it has cached (such as its Envelope).
Definition at line 244 of file Geometry.cpp.
References geos::geom::Geometry::apply_rw(), and geos::geom::Geometry::geometryChangedFilter.
Referenced by geos::precision::CommonBitsRemover::addCommonBits(), geos::geom::Point::apply_rw(), geos::geom::Polygon::apply_rw(), geos::geom::GeometryCollection::apply_rw(), apply_rw(), and geos::precision::CommonBitsRemover::removeCommonBits().
 {
   apply_rw(&geometryChangedFilter);
 }
void geos::geom::Geometry::geometryChangedAction () inherited
Notifies this Geometry that its Coordinates have been changed by an external party.
Notifies this Geometry that its Coordinates have been changed by an external party. When geometryChanged is called, this method will be called for this Geometry and its component Geometries.
See also
apply(GeometryComponentFilter *)
Definition at line 256 of file Geometry.cpp.
References geos::geom::Geometry::envelope.
Referenced by geos::geom::Geometry::GeometryChangedFilter::filter_rw().
 {
   //delete envelope;
   envelope.reset(nullptr);
 }
double geos::geom::Geometry::getArea () const virtual inherited
Returns the area of this Geometry.
Returns the area of this Geometry. Areal Geometries have a non-zero area. They override this function to compute the area. Others return 0.0
Returns
the area of the Geometry
Reimplemented in geos::geom::GeometryCollection, and geos::geom::Polygon.
Definition at line 791 of file Geometry.cpp.
Referenced by geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), and GEOSArea_r().
 {
   return 0.0;
 }
Geometry * geos::geom::LineString::getBoundary () const override virtual
Returns a MultiPoint. Empty for closed LineString, a Point for each vertex otherwise.
Implements geos::geom::Geometry.
Definition at line 221 of file LineString.cpp.
References geos::geom::GeometryFactory::createMultiPoint(), getEndPoint(), geos::geom::Geometry::getFactory(), getStartPoint(), isClosed(), and isEmpty().
 {
   if (isEmpty()) {
     return getFactory()->createMultiPoint();
   }
   // using the default OGC_SFS MOD2 rule, the boundary of a
   // closed LineString is empty
   if (isClosed()) {
     return getFactory()->createMultiPoint();
   }
   vector<Geometry*> *pts=new vector<Geometry*>();
   pts->push_back(getStartPoint());
   pts->push_back(getEndPoint());
   MultiPoint *mp = getFactory()->createMultiPoint(pts);
   return mp;
 }
int geos::geom::LineString::getBoundaryDimension () const override virtual
Returns Dimension::False for a closed LineString, 0 otherwise (LineString boundary is a MultiPoint)
Implements geos::geom::Geometry.
Definition at line 149 of file LineString.cpp.
References geos::geom::Dimension::False, and isClosed().
 {
   if (isClosed()) {
     return Dimension::False;
   }
   return 0;
 }
Point * geos::geom::Geometry::getCentroid () const virtual inherited
Computes the centroid of this Geometry.
The centroid is equal to the centroid of the set of component Geometries of highest dimension (since the lower-dimension geometries contribute zero "weight" to the centroid)
Returns
a Point which is the centroid of this Geometry
Definition at line 198 of file Geometry.cpp.
References geos::geom::GeometryFactory::createPoint(), and geos::geom::Geometry::getFactory().
Referenced by GEOSGetCentroid_r(), geos::algorithm::InteriorPointLine::InteriorPointLine(), and geos::algorithm::InteriorPointPoint::InteriorPointPoint().
 {
   Coordinate centPt;
   if ( ! getCentroid(centPt) ) return nullptr;
   // We don't use createPointFromInternalCoord here
   // because ::getCentroid() takes care about rounding
   Point *pt=getFactory()->createPoint(centPt);
   return pt;
 }
bool geos::geom::Geometry::getCentroid (Coordinate & ret) const virtual inherited
Computes the centroid of this Geometry as a Coordinate.
Returns false if centroid cannot be computed (EMPTY geometry)
Definition at line 211 of file Geometry.cpp.
References geos::geom::Geometry::getPrecisionModel(), geos::geom::Geometry::isEmpty(), and geos::geom::PrecisionModel::makePrecise().
 {
   if ( isEmpty() ) { return false; }
   if ( ! Centroid::getCentroid(*this, ret) ) return false;
   getPrecisionModel()->makePrecise(ret); // not in JTS
   return true;
 }
const Coordinate * geos::geom::LineString::getCoordinate () const override virtual
Returns a vertex of this Geometry, or NULL if this is the empty geometry.
Implements geos::geom::Geometry.
Definition at line 369 of file LineString.cpp.
References isEmpty(), and points.
Referenced by geos::geom::Polygon::getCoordinate().
 {
   if (isEmpty()) return nullptr;
   return &(points->getAt(0));
 }
int geos::geom::LineString::getCoordinateDimension () const override virtual
Returns coordinate dimension.
Implements geos::geom::Geometry.
Definition at line 143 of file LineString.cpp.
References points.
Referenced by geos::geom::Polygon::getCoordinateDimension().
 {
     return (int) points->getDimension();
 }
const Coordinate & geos::geom::LineString::getCoordinateN (int n) const virtual
Definition at line 130 of file LineString.cpp.
References points.
Referenced by geos::algorithm::CentroidArea::add(), geos::io::WKTWriter::appendLineStringText(), geos::operation::valid::IsValidOp::checkClosedRing(), geos::operation::polygonize::EdgeRing::findEdgeRingContaining(), geos::operation::overlay::PolygonBuilder::findEdgeRingContaining(), geos::linearref::LinearLocation::getCoordinate(), geos::linearref::LinearLocation::getSegment(), geos::linearref::LinearIterator::getSegmentEnd(), geos::linearref::LinearLocation::getSegmentLength(), geos::linearref::LinearIterator::getSegmentStart(), geos::linearref::LocationIndexOfLine::indicesOf(), isClosed(), geos::operation::sharedpaths::SharedPathsOp::isForward(), and geos::operation::linemerge::LineSequencer::isSequenced().
 {
   assert(points.get());
   return points->getAt(n);
 }
CoordinateSequence * geos::geom::LineString::getCoordinates () const override virtual
Returns this Geometry vertices. Caller takes ownership of the returned object.
Implements geos::geom::Geometry.
Definition at line 115 of file LineString.cpp.
References points.
Referenced by geos::algorithm::MinimumDiameter::computeWidthConvex(), geos::noding::SegmentStringUtil::extractSegmentStrings(), geos::operation::valid::RepeatedPointTester::hasRepeatedPoint(), geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::init(), geos::operation::valid::SweeplineNestedRingTester::isInside(), geos::operation::valid::SimpleNestedRingTester::isNonNested(), geos::geom::Polygon::normalize(), and geos::operation::linemerge::LineSequencer::reverse().
 {
   assert(points.get());
   return points->clone();
   //return points;
 }
const CoordinateSequence * geos::geom::LineString::getCoordinatesRO () const
Returns a read-only pointer to internal CoordinateSequence.
Definition at line 123 of file LineString.cpp.
References points.
Referenced by geos::algorithm::CentroidLine::add(), geos::algorithm::CentroidArea::add(), geos::algorithm::Centroid::add(), geos::operation::linemerge::LineMergeGraph::addEdge(), geos::operation::polygonize::PolygonizeGraph::addEdge(), geos::algorithm::InteriorPointLine::addEndpoints(), geos::algorithm::InteriorPointLine::addInterior(), geos::operation::buffer::OffsetCurveSetBuilder::addLineString(), geos::geomgraph::GeometryGraph::addLineString(), geos::operation::buffer::OffsetCurveSetBuilder::addPolygon(), geos::geomgraph::GeometryGraph::addPolygonRing(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::algorithm::SIRtreePointInRing::buildIndex(), geos::algorithm::MCPointInRing::buildIndex(), geos::operation::valid::IsValidOp::checkHolesInShell(), geos::operation::valid::IsValidOp::checkInvalidCoordinates(), geos::operation::valid::IsValidOp::checkShellInsideHole(), geos::operation::valid::IsValidOp::checkShellNotNested(), geos::operation::valid::IsValidOp::checkValid(), geos::operation::intersection::RectangleIntersection::clip_linestring_parts(), geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons(), geos::algorithm::distance::DistanceToPoint::computeDistance(), geos::operation::distance::DistanceOp::computeMinDistance(), geos::geomgraph::EdgeRing::containsPoint(), geos::algorithm::locate::SimplePointInAreaLocator::containsPointInPolygon(), geos::operation::intersection::distance(), geos::geom::util::CoordinateOperation::edit(), geos::operation::overlay::validate::OffsetPointGenerator::extractPoints(), geos::operation::polygonize::EdgeRing::findEdgeRingContaining(), geos::operation::overlay::PolygonBuilder::findEdgeRingContaining(), GEOSGeom_getCoordSeq_r(), geos::geom::Polygon::getArea(), geos::operation::overlay::OverlayOp::getAverageZ(), geos::operation::linemerge::EdgeString::getCoordinates(), geos::operation::polygonize::EdgeRing::getCoordinates(), geos::geom::Polygon::getCoordinates(), geos::simplify::TaggedLineString::getParentCoordinates(), geos::operation::predicate::SegmentIntersectionTester::hasIntersection(), geos::operation::predicate::SegmentIntersectionTester::hasIntersectionWithEnvelopeFilter(), geos::simplify::TaggedLineString::init(), geos::operation::buffer::OffsetCurveSetBuilder::isErodedCompletely(), geos::operation::polygonize::EdgeRing::isHole(), geos::operation::predicate::RectangleContains::isLineStringContainedInBoundary(), geos::operation::valid::QuadtreeNestedRingTester::isNonNested(), geos::operation::valid::IndexedNestedRingTester::isNonNested(), geos::geom::Polygon::isRectangle(), geos::algorithm::PointLocator::locate(), geos::algorithm::PointLocator::locateInPolygonRing(), geos::operation::overlay::OverlayOp::mergeZ(), geos::operation::intersection::RectangleIntersectionBuilder::reconnect(), geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), geos::algorithm::SimplePointInRing::SimplePointInRing(), geos::geom::util::GeometryTransformer::transformLinearRing(), geos::geom::util::GeometryTransformer::transformLineString(), geos::operation::valid::ConnectedInteriorTester::visitInteriorRing(), geos::io::WKBWriter::writeLineString(), and geos::io::WKBWriter::writePolygon().
 {
   assert(nullptr != points.get());
   return points.get();
 }
Dimension::DimensionType geos::geom::LineString::getDimension () const override virtual
Returns line dimension (1)
Implements geos::geom::Geometry.
Definition at line 137 of file LineString.cpp.
References geos::geom::Dimension::L.
 {
   return Dimension::L; // line
 }
Point * geos::geom::LineString::getEndPoint () const virtual
Return the end point of the LineString or NULL if this is an EMPTY LineString.
Definition at line 190 of file LineString.cpp.
References getNumPoints(), getPointN(), and isEmpty().
Referenced by GEOSGeomGetEndPoint_r(), and getBoundary().
 {
   if (isEmpty()) {
     return nullptr;
     //return new Point(NULL,NULL);
   }
   return getPointN(getNumPoints() - 1);
 }
Geometry * geos::geom::Geometry::getEnvelope () const virtual inherited
Returns this Geometrys bounding box.
Definition at line 269 of file Geometry.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::getFactory(), and geos::geom::GeometryFactory::toGeometry().
Referenced by GEOSEnvelope_r().
 {
   return getFactory()->toGeometry(getEnvelopeInternal());
 }
const Envelope * geos::geom::Geometry::getEnvelopeInternal () const virtual inherited
Returns the minimum and maximum x and y values in this Geometry, or a null Envelope if this Geometry is empty.
Definition at line 275 of file Geometry.cpp.
References geos::geom::Geometry::computeEnvelopeInternal(), and geos::geom::Geometry::envelope.
Referenced by geos::operation::valid::QuadtreeNestedRingTester::add(), geos::operation::valid::SweeplineNestedRingTester::buildIndex(), geos::operation::valid::IndexedNestedRingTester::buildIndex(), geos::operation::valid::QuadtreeNestedRingTester::buildQuadtree(), geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), geos::geomgraph::GeometryGraph::computeEdgeIntersections(), geos::geom::Polygon::computeEnvelopeInternal(), geos::operation::distance::DistanceOp::computeMinDistance(), geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::snap::GeometrySnapper::computeSizeBasedSnapTolerance(), geos::operation::predicate::RectangleContains::contains(), geos::geom::Geometry::contains(), geos::geomgraph::EdgeRing::containsPoint(), geos::geom::prep::BasicPreparedGeometry::containsProperly(), geos::geom::Geometry::covers(), geos::geom::Geometry::crosses(), geos::geom::Geometry::disjoint(), geos::geom::prep::BasicPreparedGeometry::envelopeCovers(), geos::geom::prep::BasicPreparedGeometry::envelopesIntersect(), geos::geom::Geometry::equals(), geos::operation::geounion::CascadedUnion::extractByEnvelope(), geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope(), geos::operation::polygonize::EdgeRing::findEdgeRingContaining(), geos::operation::overlay::PolygonBuilder::findEdgeRingContaining(), GEOSGeom_getXMax_r(), GEOSGeom_getXMin_r(), GEOSGeom_getYMax_r(), GEOSGeom_getYMin_r(), GEOSSTRtree_insert_r(), GEOSSTRtree_nearest_generic_r(), GEOSSTRtree_query_r(), GEOSSTRtree_remove_r(), GEOSVoronoiDiagram_r(), geos::geom::Geometry::getEnvelope(), geos::operation::predicate::SegmentIntersectionTester::hasIntersectionWithEnvelopeFilter(), geos::algorithm::InteriorPointArea::horizontalBisector(), geos::geom::Geometry::intersection(), geos::operation::predicate::RectangleIntersects::intersects(), geos::geom::Geometry::intersects(), geos::operation::buffer::OffsetCurveSetBuilder::isErodedCompletely(), geos::operation::valid::SweeplineNestedRingTester::isInside(), geos::operation::valid::QuadtreeNestedRingTester::isNonNested(), geos::operation::valid::IndexedNestedRingTester::isNonNested(), geos::operation::valid::SimpleNestedRingTester::isNonNested(), geos::geom::Polygon::isRectangle(), geos::geom::Geometry::isWithinDistance(), geos::geom::Geometry::overlaps(), geos::operation::overlay::OverlayOp::OverlayOp(), geos::operation::buffer::BufferOp::precisionScaleFactor(), geos::geom::Geometry::symDifference(), geos::geom::Geometry::touches(), geos::operation::geounion::CascadedUnion::Union(), geos::operation::geounion::CascadedPolygonUnion::Union(), geos::geom::Geometry::Union(), geos::operation::geounion::CascadedUnion::unionOptimized(), geos::operation::geounion::CascadedPolygonUnion::unionOptimized(), geos::operation::predicate::EnvelopeIntersectsVisitor::visit(), geos::operation::predicate::ContainsPointVisitor::visit(), geos::operation::predicate::LineIntersectsVisitor::visit(), and geos::algorithm::InteriorPointArea::widestGeometry().
 {
   if (!envelope.get()) {
     envelope = computeEnvelopeInternal();
   }
   return envelope.get();
 }
const GeometryFactory* geos::geom::Geometry::getFactory () const inline inherited
Gets the factory which contains the context in which this geometry was created.
Returns
the factory for this geometry
Definition at line 206 of file Geometry.h.
Referenced by geos::operation::linemerge::LineMerger::add(), geos::operation::polygonize::Polygonizer::add(), geos::operation::linemerge::LineSequencer::addLine(), geos::simplify::TaggedLineString::asLinearRing(), geos::simplify::TaggedLineString::asLineString(), geos::geom::BinaryOp(), geos::operation::buffer::BufferBuilder::buffer(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), geos::precision::MinimumClearance::compute(), geos::linearref::ExtractLineByLocation::computeLine(), geos::linearref::ExtractLineByLocation::computeLinear(), geos::geom::GeometryFactory::createPointFromInternalCoord(), geos::geom::Geometry::difference(), geos::precision::PrecisionReducerCoordinateOperation::edit(), geos::geom::util::GeometryEditor::edit(), geos::geom::util::GeometryEditor::editPolygon(), geos::operation::geounion::UnaryUnionOp::extract(), geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), geos::precision::GeometryPrecisionReducer::fixPolygonalTopology(), GEOSDelaunayTriangulation_r(), GEOSVoronoiDiagram_r(), geos::geom::MultiLineString::getBoundary(), geos::geom::MultiPoint::getBoundary(), geos::geom::MultiPolygon::getBoundary(), geos::geom::Polygon::getBoundary(), geos::geom::Point::getBoundary(), getBoundary(), geos::geom::Geometry::getCentroid(), geos::geom::Polygon::getCoordinates(), geos::geom::Geometry::getEnvelope(), geos::geom::Geometry::getInteriorPoint(), geos::precision::MinimumClearance::getLine(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::operation::overlay::validate::FuzzyPointLocator::getLocation(), geos::algorithm::MinimumDiameter::getMinimumRectangle(), geos::noding::GeometryNoder::getNoder(), getPointN(), geos::simplify::TaggedLineString::getResultCoordinates(), geos::algorithm::InteriorPointArea::InteriorPointArea(), geos::geom::Geometry::intersection(), geos::operation::geounion::PointGeometryUnion::PointGeometryUnion(), geos::geom::Polygon::Polygon(), geos::geom::MultiLineString::reverse(), geos::geom::MultiPolygon::reverse(), geos::geom::LinearRing::reverse(), geos::operation::linemerge::LineSequencer::reverse(), geos::geom::Polygon::reverse(), geos::geom::GeometryCollection::reverse(), reverse(), geos::noding::GeometryNoder::toGeometry(), geos::geom::util::GeometryTransformer::transform(), geos::operation::geounion::CascadedPolygonUnion::Union(), and validateConstruction().
 { return _factory; }
virtual const Geometry* geos::geom::Geometry::getGeometryN (std::size_t) const inline virtual inherited
Returns a pointer to the nth Geometry int this collection (or self if this is not a collection)
Reimplemented in geos::geom::GeometryCollection.
Definition at line 291 of file Geometry.h.
Referenced by geos::geom::util::ShortCircuitedGeometryVisitor::applyTo(), geos::linearref::LinearLocation::clamp(), geos::algorithm::distance::DistanceToPoint::computeDistance(), geos::operation::geounion::CascadedUnion::extractByEnvelope(), geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope(), geos::geom::util::GeometryCombiner::extractElements(), geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), geos::operation::sharedpaths::SharedPathsOp::findLinearIntersections(), GEOSGetGeometryN_r(), GEOSPolygonize_full_r(), geos::linearref::LinearLocation::getCoordinate(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::linearref::LinearLocation::getSegment(), geos::linearref::LinearLocation::getSegmentLength(), geos::linearref::LocationIndexOfLine::indicesOf(), geos::operation::predicate::RectangleContains::isContainedInBoundary(), geos::linearref::LinearLocation::isEndpoint(), geos::geom::prep::AbstractPreparedPolygonContains::isSingleShell(), geos::linearref::LinearLocation::isValid(), geos::linearref::LinearIterator::loadCurrentLine(), geos::linearref::LengthLocationMap::resolveHigher(), geos::linearref::LinearLocation::setToEnd(), and geos::operation::geounion::PointGeometryUnion::Union().
 { return this; }
string geos::geom::LineString::getGeometryType () const override virtual
Return a string representation of this Geometry type.
Implements geos::geom::Geometry.
Definition at line 215 of file LineString.cpp.
 {
   return "LineString";
 }
GeometryTypeId geos::geom::LineString::getGeometryTypeId () const override virtual
Return an integer representation of this Geometry type.
Implements geos::geom::Geometry.
Definition at line 422 of file LineString.cpp.
References geos::geom::GEOS_LINESTRING.
 {
   return GEOS_LINESTRING;
 }
Point * geos::geom::Geometry::getInteriorPoint () const virtual inherited
Computes an interior point of this Geometry.
An interior point is guaranteed to lie in the interior of the Geometry, if it possible to calculate such a point exactly. Otherwise, the point may lie on the boundary of the geometry.
Returns
a Point which is in the interior of this Geometry, or null if the geometry doesn't have an interior (empty)
Definition at line 220 of file Geometry.cpp.
References geos::geom::GeometryFactory::createPointFromInternalCoord(), geos::geom::Geometry::getDimension(), geos::geom::Geometry::getFactory(), geos::algorithm::InteriorPointLine::getInteriorPoint(), geos::algorithm::InteriorPointPoint::getInteriorPoint(), and geos::algorithm::InteriorPointArea::getInteriorPoint().
Referenced by GEOSPointOnSurface_r().
 {
   Coordinate interiorPt;
   int dim=getDimension();
   if (dim==0) {
     InteriorPointPoint intPt(this);
     if ( ! intPt.getInteriorPoint(interiorPt) ) return nullptr;
   } else if (dim==1) {
     InteriorPointLine intPt(this);
     if ( ! intPt.getInteriorPoint(interiorPt) ) return nullptr;
   } else {
     InteriorPointArea intPt(this);
     if ( ! intPt.getInteriorPoint(interiorPt) ) return nullptr;
   }
   Point *p=getFactory()->createPointFromInternalCoord(&interiorPt, this);
   return p;
 }
double geos::geom::LineString::getLength () const override virtual
Returns the length of this Geometry.
Returns the length of this Geometry. Linear geometries return their length. Areal geometries return their perimeter. They override this function to compute the area. Others return 0.0
Returns
the length of the Geometry
Reimplemented from geos::geom::Geometry.
Definition at line 376 of file LineString.cpp.
References points.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), GEOSGeomGetLength_r(), and geos::geom::Polygon::getLength().
 {
   return CGAlgorithms::length(points.get());
 }
virtual std::size_t geos::geom::Geometry::getNumGeometries () const inline virtual inherited
Returns the number of geometries in this collection (or 1 if this is not a collection)
Reimplemented in geos::geom::GeometryCollection.
Definition at line 287 of file Geometry.h.
Referenced by geos::geom::util::ShortCircuitedGeometryVisitor::applyTo(), geos::linearref::LinearLocation::clamp(), geos::operation::geounion::CascadedUnion::extractByEnvelope(), geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope(), geos::geom::util::GeometryCombiner::extractElements(), geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), GEOSGetNumGeometries_r(), GEOSPolygonize_full_r(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::linearref::LocationIndexOfLine::indicesOf(), geos::operation::predicate::RectangleContains::isContainedInBoundary(), geos::geom::prep::AbstractPreparedPolygonContains::isSingleShell(), geos::linearref::LinearLocation::isValid(), geos::linearref::LengthLocationMap::resolveHigher(), geos::linearref::LinearLocation::setToEnd(), geos::geom::Geometry::symDifference(), geos::operation::geounion::PointGeometryUnion::Union(), geos::geom::Geometry::Union(), geos::operation::geounion::CascadedUnion::unionOptimized(), and geos::operation::geounion::CascadedPolygonUnion::unionOptimized().
 { return 1; }
size_t geos::geom::LineString::getNumPoints () const override virtual
Returns the count of this Geometrys vertices.
Implements geos::geom::Geometry.
Definition at line 165 of file LineString.cpp.
References points.
Referenced by geos::io::WKTWriter::appendLineStringText(), geos::linearref::LinearLocation::clamp(), geos::operation::intersection::RectangleIntersection::clip_linestring_parts(), GEOSGeomGetNumPoints_r(), geos::linearref::LinearLocation::getCoordinate(), getEndPoint(), geos::geom::Polygon::getNumPoints(), geos::linearref::LinearLocation::getSegment(), geos::linearref::LinearLocation::getSegmentLength(), geos::linearref::LinearIterator::hasNext(), geos::linearref::LocationIndexOfLine::indicesOf(), isClosed(), geos::linearref::LinearLocation::isEndpoint(), geos::geom::Polygon::isRectangle(), geos::operation::linemerge::LineSequencer::isSequenced(), geos::linearref::LinearLocation::isValid(), geos::linearref::LinearIterator::next(), and geos::linearref::LinearLocation::setToEnd().
 {
   assert(points.get());
   return points->getSize();
 }
Point * geos::geom::LineString::getPointN (std::size_t n) const virtual
Definition at line 172 of file LineString.cpp.
References geos::geom::GeometryFactory::createPoint(), geos::geom::Geometry::getFactory(), and points.
Referenced by GEOSGeomGetPointN_r(), getEndPoint(), and getStartPoint().
 {
   assert(getFactory());
   assert(points.get());
   return getFactory()->createPoint(points->getAt(n));
 }
const PrecisionModel * geos::geom::Geometry::getPrecisionModel () const inherited
Get the PrecisionModel used to create this Geometry.
Definition at line 871 of file Geometry.cpp.
References geos::geom::Geometry::_factory, and geos::geom::GeometryFactory::getPrecisionModel().
Referenced by geos::operation::buffer::BufferBuilder::buffer(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::operation::overlay::snap::GeometrySnapper::computeOverlaySnapTolerance(), geos::geom::GeometryFactory::createPointFromInternalCoord(), geos::operation::GeometryGraphOperation::GeometryGraphOperation(), geos::geom::Geometry::getCentroid(), and geos::io::WKTWriter::writeFormatted().
 {
   return _factory->getPrecisionModel();
 }
virtual int geos::geom::Geometry::getSRID () const inline virtual inherited
Definition at line 246 of file Geometry.h.
Referenced by GEOSGetSRID_r(), geos::io::WKBWriter::writeGeometryCollection(), geos::io::WKBWriter::writeLineString(), geos::io::WKBWriter::writePoint(), and geos::io::WKBWriter::writePolygon().
 { return SRID; }
Point * geos::geom::LineString::getStartPoint () const virtual
Return the start point of the LineString or NULL if this is an EMPTY LineString.
Definition at line 180 of file LineString.cpp.
References getPointN(), and isEmpty().
Referenced by GEOSGeomGetStartPoint_r(), and getBoundary().
 {
   if (isEmpty()) {
     return nullptr;
     //return new Point(NULL,NULL);
   }
   return getPointN(0);
 }
void* geos::geom::Geometry::getUserData () const inline inherited
Gets the user data object for this geometry, if any.
Returns
the user data object, or null if none set
Definition at line 229 of file Geometry.h.
Referenced by GEOSGeom_getUserData_r().
 { return _userData; }
bool geos::geom::Geometry::hasNonEmptyElements (const std::vector< Geometry * > * geometries) static protected inherited
Returns true if the array contains any non-empty Geometrys.
Definition at line 140 of file Geometry.cpp.
Referenced by geos::geom::Polygon::Polygon().
 {
   for (size_t i=0; i<geometries->size(); i++) {
     if (!(*geometries)[i]->isEmpty()) {
       return true;
     }
   }
   return false;
 }
bool geos::geom::Geometry::hasNullElements (const CoordinateSequence * list) static protected inherited
Returns true if the CoordinateSequence contains any null elements.
Definition at line 151 of file Geometry.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), and geos::geom::Coordinate::isNull().
Referenced by geos::geom::GeometryCollection::GeometryCollection(), and geos::geom::Polygon::Polygon().
 {
   size_t npts=list->getSize();
   for (size_t i=0; i<npts; ++i) {
     if (list->getAt(i).isNull()) {
       return true;
     }
   }
   return false;
 }
bool geos::geom::Geometry::hasNullElements (const std::vector< Geometry * > * lrs) static protected inherited
Returns true if the vector contains any null elements.
Definition at line 163 of file Geometry.cpp.
 {
   size_t n=lrs->size();
   for (size_t i=0; i<n; ++i) {
     if ((*lrs)[i]==nullptr) {
       return true;
     }
   }
   return false;
 }
Geometry * geos::geom::Geometry::intersection (const Geometry * other) const virtual inherited
Returns a Geometry representing the points shared by this Geometry and other.
Exceptions
util::TopologyException if a robustness error occurs
util::IllegalArgumentException if either input is a non-empty GeometryCollection
TODO: MD - add optimization for P-A case using Point-In-Polygon
Definition at line 505 of file Geometry.cpp.
References geos::geom::BinaryOp(), geos::geom::GeometryFactory::createGeometryCollection(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::getFactory(), geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), geos::geom::Geometry::isEmpty(), and geos::geom::Geometry::isRectangle().
Referenced by GEOSIntersection_r(), and geos::precision::EnhancedPrecisionOp::intersection().
 {
   // special case: if one input is empty ==> empty
   if (isEmpty() || other->isEmpty() )
   {
     return getFactory()->createGeometryCollection();
   }
 #ifdef USE_RECTANGLE_INTERSECTION
   // optimization for rectangle arguments
   using operation::intersection::Rectangle;
   using operation::intersection::RectangleIntersection;
   if ( isRectangle() ) {
     const Envelope* env = getEnvelopeInternal();
     Rectangle rect(env->getMinX(), env->getMinY(),
                    env->getMaxX(), env->getMaxY());
     return RectangleIntersection::clip(*other, rect).release();
   }
   if (other->isRectangle()) {
     const Envelope* env = other->getEnvelopeInternal();
     Rectangle rect(env->getMinX(), env->getMinY(),
                    env->getMaxX(), env->getMaxY());
     return RectangleIntersection::clip(*this, rect).release();
   }
 #endif
   return BinaryOp(this, other, overlayOp(OverlayOp::opINTERSECTION)).release();
 }
bool geos::geom::Geometry::intersects (const Geometry * g) const virtual inherited
Returns true if disjoint returns false.
TODO: (MD) Add optimizations:
for P-A case: If P is in env(A), test for point-in-poly
for A-A case: If env(A1).overlaps(env(A2)) test for overlaps via point-in-poly first (both ways) Possibly optimize selection of point to test by finding point of A1 closest to centre of env(A2). (Is there a test where we shouldn't bother - e.g. if env A is much smaller than env B, maybe there's no point in testing pt(B) in env(A)?
Definition at line 310 of file Geometry.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::isRectangle(), and geos::geom::Geometry::relate().
Referenced by geos::geom::Geometry::crosses(), geos::geom::Geometry::disjoint(), GEOSIntersects_r(), geos::geom::prep::BasicPreparedGeometry::intersects(), geos::geom::Geometry::overlaps(), and geos::geom::Geometry::touches().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return false;
 #endif
   // optimization for rectangle arguments
   if (isRectangle()) {
     const Polygon* p = dynamic_cast<const Polygon*>(this);
     return predicate::RectangleIntersects::intersects(*p, *g);
   }
   if (g->isRectangle()) {
     const Polygon* p = dynamic_cast<const Polygon*>(g);
     return predicate::RectangleIntersects::intersects(*p, *this);
   }
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isIntersects();
   return res;
 }
bool geos::geom::LineString::isClosed () const virtual
Reimplemented in geos::geom::LinearRing.
Definition at line 200 of file LineString.cpp.
References geos::geom::Coordinate::equals2D(), getCoordinateN(), getNumPoints(), and isEmpty().
Referenced by geos::operation::linemerge::LineSequencer::buildSequencedGeometry(), GEOSisClosed_r(), getBoundary(), getBoundaryDimension(), geos::geom::MultiLineString::isClosed(), geos::geom::LinearRing::isClosed(), isRing(), geos::algorithm::PointLocator::locate(), and geos::geom::LinearRing::validateConstruction().
 {
   if (isEmpty()) {
     return false;
   }
   return getCoordinateN(0).equals2D(getCoordinateN(static_cast<int>(getNumPoints()-1)));
 }
bool geos::geom::LineString::isCoordinate (Coordinate & pt) const virtual
Definition at line 240 of file LineString.cpp.
References points.
 {
   assert(points.get());
   std::size_t npts=points->getSize();
   for (std::size_t i = 0; i<npts; i++) {
     if (points->getAt(i)==pt) {
       return true;
     }
   }
   return false;
 }
bool geos::geom::LineString::isEmpty () const override virtual
Returns whether or not the set of points in this Geometry is empty.
Implements geos::geom::Geometry.
Definition at line 158 of file LineString.cpp.
References points.
Referenced by geos::operation::linemerge::LineMergeGraph::addEdge(), geos::operation::polygonize::PolygonizeGraph::addEdge(), geos::geomgraph::GeometryGraph::addPolygonRing(), geos::io::WKTWriter::appendLinearRingTaggedText(), geos::io::WKTWriter::appendLineStringTaggedText(), geos::io::WKTWriter::appendLineStringText(), geos::operation::valid::IsValidOp::checkClosedRing(), geos::operation::valid::IsValidOp::checkHolesInShell(), geos::operation::valid::IsValidOp::checkHolesNotNested(), geos::operation::valid::IsValidOp::checkShellsNotNested(), geos::operation::intersection::RectangleIntersection::clip_linestring(), computeEnvelopeInternal(), getBoundary(), getCoordinate(), getEndPoint(), getStartPoint(), isClosed(), geos::geom::Polygon::isEmpty(), geos::geom::Polygon::normalize(), geos::geom::Polygon::Polygon(), geos::geom::LinearRing::reverse(), reverse(), geos::geom::util::GeometryTransformer::transformPolygon(), and geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
 {
   assert(points.get());
   return points->isEmpty();
 }
bool geos::geom::Geometry::isEquivalentClass (const Geometry * other) const protected virtual inherited
Returns whether the two Geometrys are equal, from the point of view of the equalsExact method.
Definition at line 673 of file Geometry.cpp.
Referenced by geos::geom::MultiLineString::equalsExact(), geos::geom::MultiPoint::equalsExact(), geos::geom::MultiPolygon::equalsExact(), geos::geom::GeometryCollection::equalsExact(), geos::geom::Point::equalsExact(), and equalsExact().
 {
   if (typeid(*this)==typeid(*other))
     return true;
   else
     return false;
 }
virtual bool geos::geom::Geometry::isRectangle () const inline virtual inherited
Polygon overrides to check for actual rectangle.
Reimplemented in geos::geom::Polygon.
Definition at line 308 of file Geometry.h.
Referenced by geos::geom::Geometry::contains(), geos::geom::Geometry::covers(), geos::geom::Geometry::intersection(), geos::geom::Geometry::intersects(), and geos::geom::prep::PreparedPolygon::PreparedPolygon().
 { return false; }
bool geos::geom::LineString::isRing () const virtual
Definition at line 209 of file LineString.cpp.
References isClosed(), and geos::geom::Geometry::isSimple().
Referenced by GEOSisRing_r().
 {
   return isClosed() && isSimple();
 }
bool geos::geom::Geometry::isSimple () const virtual inherited
Returns false if the Geometry not simple.
Reimplemented in geos::geom::Polygon, geos::geom::LinearRing, geos::geom::Point, and geos::geom::MultiPolygon.
Definition at line 862 of file Geometry.cpp.
References geos::geom::Geometry::checkNotGeometryCollection(), and geos::operation::IsSimpleOp::isSimple().
Referenced by GEOSisSimple_r(), and isRing().
 {
   checkNotGeometryCollection(this);
   operation::IsSimpleOp op(*this);
   return op.isSimple();
 }
bool geos::geom::Geometry::isValid () const virtual inherited
Tests the validity of this Geometry.
Subclasses provide their own definition of "valid".
Returns
true if this Geometry is valid
See also
IsValidOp
Definition at line 263 of file Geometry.cpp.
References geos::operation::valid::IsValidOp::isValid().
Referenced by geos::precision::EnhancedPrecisionOp::buffer(), geos::precision::EnhancedPrecisionOp::difference(), geos::precision::EnhancedPrecisionOp::intersection(), geos::operation::polygonize::EdgeRing::isValid(), geos::precision::EnhancedPrecisionOp::symDifference(), and geos::precision::EnhancedPrecisionOp::Union().
 {
   return IsValidOp(this).isValid();
 }
bool geos::geom::Geometry::isWithinDistance (const Geometry * geom, double cDistance) const virtual inherited
Tests whether the distance from this Geometry to another is less than or equal to a specified value.
Parameters
geom the Geometry to check the distance to
cDistance the distance value to compare
Returns
true if the geometries are less than distance apart.
Todo:
doesn't seem to need being virtual, make it concrete
Definition at line 176 of file Geometry.cpp.
References geos::geom::Envelope::distance(), geos::geom::Geometry::distance(), and geos::geom::Geometry::getEnvelopeInternal().
 {
   const Envelope *env0=getEnvelopeInternal();
   const Envelope *env1=geom->getEnvelopeInternal();
   double envDist=env0->distance(env1);
   //delete env0;
   //delete env1;
   if (envDist>cDistance)
   {
     return false;
   }
   // NOTE: this could be implemented more efficiently
   double geomDist=distance(geom);
   if (geomDist>cDistance)
   {
     return false;
   }
   return true;
 }
void geos::geom::LineString::normalize (void) override virtual
Normalizes a LineString.
A normalized linestring has the first point which is not equal to its reflected point less than the reflected point.
Implements geos::geom::Geometry.
Definition at line 334 of file LineString.cpp.
References points, and geos::geom::CoordinateSequence::reverse().
 {
   assert(points.get());
   std::size_t npts=points->getSize();
   std::size_t n=npts/2;
   for (std::size_t i=0; i<n; i++) {
     std::size_t j = npts - 1 - i;
     if (!(points->getAt(i)==points->getAt(j))) {
       if (points->getAt(i).compareTo(points->getAt(j)) > 0) {
         CoordinateSequence::reverse(points.get());
       }
       return;
     }
   }
 }
bool geos::geom::Geometry::overlaps (const Geometry * g) const virtual inherited
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*T***T** (for two points or two surfaces) 1*T***T** (for two curves).
Definition at line 415 of file Geometry.cpp.
References geos::geom::Geometry::getDimension(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::intersects(), and geos::geom::Geometry::relate().
Referenced by GEOSOverlaps_r(), and geos::geom::prep::BasicPreparedGeometry::overlaps().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return false;
 #endif
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isOverlaps(getDimension(), g->getDimension());
   return res;
 }
virtual bool geos::geom::Geometry::relate (const Geometry * g, const std::string & intersectionPattern) const virtual inherited
Returns true if the elements in the DE-9IM intersection matrix for the two Geometrys match the elements in intersectionPattern.
IntersectionPattern elements may be: 0 1 2 T (= 0, 1 or 2) F (= -1) * (= -1, 0, 1 or 2).
For more information on the DE-9IM, see the OpenGIS Simple Features Specification.
Exceptions
util::IllegalArgumentException if either arg is a collection
Referenced by geos::geom::Geometry::contains(), geos::geom::prep::BasicPreparedGeometry::containsProperly(), geos::geom::Geometry::covers(), geos::geom::Geometry::crosses(), geos::geom::Geometry::disjoint(), geos::geom::Geometry::equals(), GEOSRelate_r(), GEOSRelatePattern_r(), geos::geom::Geometry::intersects(), geos::geom::Geometry::overlaps(), and geos::geom::Geometry::touches().
bool geos::geom::Geometry::relate (const Geometry & g, const std::string & intersectionPattern) const inline inherited
Definition at line 430 of file Geometry.h.
   {
     return relate(&g, intersectionPattern);
   }
IntersectionMatrix * geos::geom::Geometry::relate (const Geometry * g) const virtual inherited
Returns the DE-9IM intersection matrix for the two Geometrys.
Definition at line 453 of file Geometry.cpp.
 {
   return RelateOp::relate(this, other);
 }
IntersectionMatrix* geos::geom::Geometry::relate (const Geometry & g) const inline inherited
Definition at line 437 of file Geometry.h.
{
     return relate(&g);
   }
Geometry * geos::geom::LineString::reverse () const override virtual
Creates a LineString whose coordinates are in the reverse order of this object's
Returns
a LineString with coordinates in the reverse order
Implements geos::geom::Geometry.
Definition at line 58 of file LineString.cpp.
References clone(), geos::geom::GeometryFactory::createLineString(), geos::geom::Geometry::getFactory(), isEmpty(), points, and geos::geom::CoordinateSequence::reverse().
Referenced by geos::linearref::ExtractLineByLocation::reverse(), geos::geom::MultiLineString::reverse(), and geos::operation::intersection::RectangleIntersectionBuilder::reverseLines().
 {
   if (isEmpty()) {
     return clone();
   }
   assert(points.get());
   CoordinateSequence* seq = points->clone();
   CoordinateSequence::reverse(seq);
   assert(getFactory());
   return getFactory()->createLineString(seq);
 }
virtual void geos::geom::Geometry::setSRID (int newSRID) inline virtual inherited
Definition at line 252 of file Geometry.h.
Referenced by geos::geom::GeometryCollection::GeometryCollection(), GEOSSetSRID_r(), and geos::io::WKBReader::readGeometry().
 { SRID=newSRID; }
void geos::geom::Geometry::setUserData (void * newUserData) inline inherited
A simple scheme for applications to add their own custom data to a Geometry. An example use might be to add an object representing a Coordinate Reference System.
Note that user data objects are not present in geometries created by construction methods.
Parameters
newUserData an object, the semantics for which are defined by the application using this Geometry
Definition at line 221 of file Geometry.h.
Referenced by geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), and GEOSGeom_setUserData_r().
 { _userData=newUserData; }
Geometry * geos::geom::Geometry::symDifference (const Geometry * other) const virtual inherited
Returns a set combining the points in this Geometry not in other, and the points in other not in this Geometry.
Exceptions
util::TopologyException if a robustness error occurs
util::IllegalArgumentException if either input is a non-empty GeometryCollection
Definition at line 609 of file Geometry.cpp.
References geos::geom::Geometry::_factory, geos::geom::BinaryOp(), geos::geom::GeometryFactory::buildGeometry(), geos::geom::Geometry::clone(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::Geometry::getNumGeometries(), geos::geom::Envelope::intersects(), and geos::geom::Geometry::isEmpty().
Referenced by GEOSSymDifference_r(), and geos::precision::EnhancedPrecisionOp::symDifference().
 {
   // special case: if either input is empty ==> other input
   if ( isEmpty() ) return other->clone();
   if ( other->isEmpty() ) return clone();
   // if envelopes are disjoint return a MULTI geom or
   // a geometrycollection
   if ( ! getEnvelopeInternal()->intersects(other->getEnvelopeInternal()) )
   {
     const GeometryCollection *coll;
     size_t ngeomsThis = getNumGeometries();
     size_t ngeomsOther = other->getNumGeometries();
     // Allocated for ownership transfer
     vector<Geometry *> *v = new vector<Geometry *>();
     v->reserve(ngeomsThis+ngeomsOther);
     if ( nullptr != (coll = dynamic_cast<const GeometryCollection *>(this)) )
     {
       for (size_t i=0; i<ngeomsThis; ++i)
         v->push_back(coll->getGeometryN(i)->clone());
     } else {
       v->push_back(this->clone());
     }
     if ( nullptr != (coll = dynamic_cast<const GeometryCollection *>(other)) )
     {
       for (size_t i=0; i<ngeomsOther; ++i)
         v->push_back(coll->getGeometryN(i)->clone());
     } else {
       v->push_back(other->clone());
     }
     return _factory->buildGeometry(v);
   }
   return BinaryOp(this, other, overlayOp(OverlayOp::opSYMDIFFERENCE)).release();
 }
string geos::geom::Geometry::toString (void) const virtual inherited
Returns the Well-known Text representation of this Geometry.
Definition at line 460 of file Geometry.cpp.
References geos::geom::Geometry::toText().
Referenced by geos::operation::linemerge::LineMergeGraph::addEdge(), geos::operation::buffer::OffsetCurveSetBuilder::addLineString(), geos::geom::BinaryOp(), geos::geom::check_valid(), geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), geos::operation::distance::DistanceOp::computeMinDistancePoints(), GEOSClipByRect_r(), GEOSGeomToWKT_r(), GEOSNode_r(), GEOSUnaryUnion_r(), GEOSUnion_r(), and geos::geom::prep::BasicPreparedGeometry::toString().
 {
   return toText();
 }
string geos::geom::Geometry::toText () const virtual inherited
Definition at line 474 of file Geometry.cpp.
References geos::io::WKTWriter::write().
Referenced by geos::geom::Geometry::toString().
 {
   io::WKTWriter writer;
   return writer.write(this);
 }
bool geos::geom::Geometry::touches (const Geometry * other) const virtual inherited
Returns true if the DE-9IM intersection matrix for the two Geometrys is FT*******, F**T***** or F***T****.
Definition at line 297 of file Geometry.cpp.
References geos::geom::Geometry::getDimension(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::intersects(), and geos::geom::Geometry::relate().
Referenced by GEOSTouches_r(), and geos::geom::prep::BasicPreparedGeometry::touches().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return false;
 #endif
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isTouches(getDimension(), g->getDimension());
   return res;
 }
Geometry * geos::geom::Geometry::Union (const Geometry * other) const inherited
Returns a Geometry representing all the points in this Geometry and other.
Exceptions
util::TopologyException if a robustness error occurs
util::IllegalArgumentException if either input is a non-empty GeometryCollection
Definition at line 539 of file Geometry.cpp.
References geos::geom::Geometry::_factory, geos::geom::BinaryOp(), geos::geom::GeometryFactory::buildGeometry(), geos::geom::Geometry::clone(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::Geometry::getNumGeometries(), geos::geom::Envelope::intersects(), and geos::geom::Geometry::isEmpty().
Referenced by GEOSUnaryUnion_r(), GEOSUnion_r(), geos::precision::EnhancedPrecisionOp::Union(), geos::operation::geounion::CascadedUnion::unionActual(), and geos::operation::geounion::CascadedPolygonUnion::unionActual().
 {
   // special case: if one input is empty ==> other input
   if ( isEmpty() ) return other->clone();
   if ( other->isEmpty() ) return clone();
   Geometry *out = nullptr;
 #ifdef SHORTCIRCUIT_PREDICATES
   // if envelopes are disjoint return a MULTI geom or
   // a geometrycollection
   if ( ! getEnvelopeInternal()->intersects(other->getEnvelopeInternal()) )
   {
 //cerr<<"SHORTCIRCUITED-UNION engaged"<<endl;
     const GeometryCollection *coll;
     size_t ngeomsThis = getNumGeometries();
     size_t ngeomsOther = other->getNumGeometries();
     // Allocated for ownership transfer
     vector<Geometry *> *v = new vector<Geometry *>();
     v->reserve(ngeomsThis+ngeomsOther);
     if ( nullptr != (coll = dynamic_cast<const GeometryCollection *>(this)) )
     {
       for (size_t i=0; i<ngeomsThis; ++i)
         v->push_back(coll->getGeometryN(i)->clone());
     } else {
       v->push_back(this->clone());
     }
     if ( nullptr != (coll = dynamic_cast<const GeometryCollection *>(other)) )
     {
       for (size_t i=0; i<ngeomsOther; ++i)
         v->push_back(coll->getGeometryN(i)->clone());
     } else {
       v->push_back(other->clone());
     }
     out = _factory->buildGeometry(v);
     return out;
   }
 #endif
   return BinaryOp(this, other, overlayOp(OverlayOp::opUNION)).release();
 }
Geometry::Ptr geos::geom::Geometry::Union () const inherited
Computes the union of all the elements of this geometry. Heterogeneous GeometryCollections are fully supported.
The result obeys the following contract:
Unioning a set of LineStrings has the effect of fully noding and dissolving the linework.
Unioning a set of Polygons will always return a Polygonal geometry (unlike {link #union(Geometry)}, which may return geometrys of lower dimension if a topology collapse occurred.
Returns
the union geometry
See also
UnaryUnionOp
Definition at line 591 of file Geometry.cpp.
 {
   using geos::operation::geounion::UnaryUnionOp;
   return UnaryUnionOp::Union(*this);
 }
void geos::geom::LineString::validateConstruction () private
Definition at line 74 of file LineString.cpp.
References geos::geom::Geometry::getFactory(), and points.
Referenced by LineString().
 {
   if (points.get()==nullptr)
   {
     points.reset(getFactory()->getCoordinateSequenceFactory()->create());
     return;
   }
   if (points->size()==1)
   {
     throw util::IllegalArgumentException("point array must contain 0 or >1 elements\n");
   }
 }
bool geos::geom::Geometry::within (const Geometry * g) const virtual inherited
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*F**F***.
Definition at line 385 of file Geometry.cpp.
References geos::geom::Geometry::contains().
Referenced by GEOSWithin_r(), and geos::geom::prep::BasicPreparedGeometry::within().
 {
   return g->contains(this);
 }
Friends And Related Function Documentation
friend class GeometryFactory friend
Definition at line 74 of file LineString.h.
Member Data Documentation
std::unique_ptr<Envelope> geos::geom::Geometry::envelope mutable protected inherited
The bounding box of this Geometry.
Definition at line 786 of file Geometry.h.
Referenced by geos::geom::GeometryCollection::computeEnvelopeInternal(), geos::geom::Geometry::Geometry(), geos::geom::Geometry::geometryChangedAction(), and geos::geom::Geometry::getEnvelopeInternal().
CoordinateSequence::Ptr geos::geom::LineString::points protected
Definition at line 203 of file LineString.h.
Referenced by apply_ro(), apply_rw(), compareToSameClass(), computeEnvelopeInternal(), equalsExact(), getCoordinate(), getCoordinateDimension(), getCoordinateN(), getCoordinates(), getCoordinatesRO(), getLength(), getNumPoints(), getPointN(), geos::geom::LinearRing::isClosed(), isCoordinate(), isEmpty(), normalize(), geos::geom::LinearRing::reverse(), reverse(), geos::geom::LinearRing::setPoints(), geos::geom::LinearRing::validateConstruction(), and validateConstruction().
int geos::geom::Geometry::SRID protected inherited
Definition at line 825 of file Geometry.h.
Referenced by geos::geom::Geometry::Geometry().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/LineString.h
/home/vicky/potree/geos/vicky/src/geom/LineString.cpp