GEOS: geos::operation::relate::RelateNodeGraph Class Reference
geos::operation::relate::RelateNodeGraph Class Reference
Implements the simple graph of Nodes and geomgraph::EdgeEnd which is all that is required to determine topological relationships between Geometries.
#include <RelateNodeGraph.h>
Public Member Functions
RelateNodeGraph ()
virtual ~RelateNodeGraph ()
std::map< geom::Coordinate *, geomgraph::Node *, geom::CoordinateLessThen > & getNodeMap ()
void build (geomgraph::GeometryGraph *geomGraph)
void computeIntersectionNodes (geomgraph::GeometryGraph *geomGraph, int argIndex)
void copyNodesAndLabels (geomgraph::GeometryGraph *geomGraph, int argIndex)
void insertEdgeEnds (std::vector< geomgraph::EdgeEnd * > *ee)
Private Attributes
geomgraph::NodeMap * nodes
Detailed Description
Implements the simple graph of Nodes and geomgraph::EdgeEnd which is all that is required to determine topological relationships between Geometries.
Also supports building a topological graph of a single Geometry, to allow verification of valid topology.
It is not necessary to create a fully linked PlanarGraph to determine relationships, since it is sufficient to know how the Geometries interact locally around the nodes. In fact, this is not even feasible, since it is not possible to compute exact intersection points, and hence the topology around those nodes cannot be computed robustly. The only Nodes that are created are for improper intersections; that is, nodes which occur at existing vertices of the Geometries. Proper intersections (e.g. ones which occur between the interior of line segments) have their topology determined implicitly, without creating a geomgraph::Node object to represent them.
Definition at line 68 of file RelateNodeGraph.h.
Constructor & Destructor Documentation
geos::operation::relate::RelateNodeGraph::RelateNodeGraph ()
Definition at line 42 of file RelateNodeGraph.cpp.
 {
   nodes=new NodeMap(RelateNodeFactory::instance());
 }
geos::operation::relate::RelateNodeGraph::~RelateNodeGraph () virtual
Definition at line 47 of file RelateNodeGraph.cpp.
{
   delete nodes;
 }
Member Function Documentation
void geos::operation::relate::RelateNodeGraph::build (geomgraph::GeometryGraph * geomGraph)
Copy the labelling for the nodes in the parent Geometry. These override any labels determined by intersections.
Build EdgeEnds for all intersections.
Definition at line 58 of file RelateNodeGraph.cpp.
References geos::operation::relate::EdgeEndBuilder::computeEdgeEnds(), and geos::geomgraph::GeometryGraph::getEdges().
Referenced by geos::operation::valid::ConsistentAreaTester::isNodeConsistentArea().
 {
   // compute nodes for intersections between previously noded edges
   computeIntersectionNodes(geomGraph,0);
   copyNodesAndLabels(geomGraph,0);
   EdgeEndBuilder *eeBuilder=new EdgeEndBuilder();
   vector<EdgeEnd*> *eeList=eeBuilder->computeEdgeEnds(geomGraph->getEdges());
   insertEdgeEnds(eeList);
   delete eeBuilder;
   delete eeList;
   //Debug.println("==== NodeList ===");
   //Debug.print(nodes);
 }
void geos::operation::relate::RelateNodeGraph::computeIntersectionNodes (geomgraph::GeometryGraph * geomGraph, int argIndex)
Insert nodes for all intersections on the edges of a Geometry. Label the created nodes the same as the edge label if they do not already have a label. This allows nodes created by either self-intersections or mutual intersections to be labelled. Endpoint nodes will already be labelled from when they were inserted.
Precondition: edge intersections have been computed.
Definition at line 92 of file RelateNodeGraph.cpp.
References geos::geomgraph::EdgeIntersectionList::begin(), geos::geomgraph::EdgeIntersection::coord, geos::geomgraph::EdgeIntersectionList::end(), geos::geomgraph::Edge::getEdgeIntersectionList(), geos::geomgraph::GeometryGraph::getEdges(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isNull(), geos::geomgraph::Node::setLabel(), and geos::geomgraph::Node::setLabelBoundary().
 {
   vector<Edge*> *edges=geomGraph->getEdges();
   vector<Edge*>::iterator edgeIt=edges->begin();
   for( ; edgeIt<edges->end(); ++edgeIt)
   {
     Edge *e=*edgeIt;
     int eLoc=e->getLabel().getLocation(argIndex);
     EdgeIntersectionList &eiL=e->getEdgeIntersectionList();
     EdgeIntersectionList::iterator eiIt=eiL.begin();
     EdgeIntersectionList::iterator eiEnd=eiL.end();
     for( ; eiIt!=eiEnd; ++eiIt) {
       EdgeIntersection *ei=*eiIt;
       RelateNode *n=(RelateNode*) nodes->addNode(ei->coord);
       if (eLoc==Location::BOUNDARY)
         n->setLabelBoundary(argIndex);
       else {
         if (n->getLabel().isNull(argIndex))
           n->setLabel(argIndex,Location::INTERIOR);
       }
     }
   }
 }
void geos::operation::relate::RelateNodeGraph::copyNodesAndLabels (geomgraph::GeometryGraph * geomGraph, int argIndex)
Copy all nodes from an arg geometry into this graph. The node label in the arg geometry overrides any previously computed label for that argIndex. (E.g. a node may be an intersection node with a computed label of BOUNDARY, but in the original arg Geometry it is actually in the interior due to the Boundary Determination Rule)
Definition at line 127 of file RelateNodeGraph.cpp.
References geos::geomgraph::Node::getCoordinate(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::PlanarGraph::getNodeMap(), geos::geomgraph::NodeMap::nodeMap, and geos::geomgraph::Node::setLabel().
 {
   map<Coordinate*,Node*,CoordinateLessThen> &nMap=geomGraph->getNodeMap()->nodeMap;
   map<Coordinate*,Node*,CoordinateLessThen>::iterator nodeIt;
   for(nodeIt=nMap.begin();nodeIt!=nMap.end();nodeIt++) {
     Node *graphNode=nodeIt->second;
     Node *newNode=nodes->addNode(graphNode->getCoordinate());
     newNode->setLabel(argIndex,graphNode->getLabel().getLocation(argIndex));
     //node.print(System.out);
   }
 }
map< Coordinate *, Node *, CoordinateLessThen > & geos::operation::relate::RelateNodeGraph::getNodeMap ()
Definition at line 52 of file RelateNodeGraph.cpp.
Referenced by geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), and geos::operation::valid::ConsistentAreaTester::isNodeEdgeAreaLabelsConsistent().
 {
   return nodes->nodeMap;
 }
void geos::operation::relate::RelateNodeGraph::insertEdgeEnds (std::vector< geomgraph::EdgeEnd * > * ee)
Definition at line 140 of file RelateNodeGraph.cpp.
 {
   for(vector<EdgeEnd*>::iterator i=ee->begin();i<ee->end();i++) {
     EdgeEnd *e=*i;
     nodes->add(e);
   }
 }
Member Data Documentation
geomgraph::NodeMap* geos::operation::relate::RelateNodeGraph::nodes private
Definition at line 90 of file RelateNodeGraph.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/relate/RelateNodeGraph.h
/home/vicky/potree/geos/vicky/src/operation/relate/RelateNodeGraph.cpp