GEOS: geos::operation::buffer::BufferInputLineSimplifier Class Reference
geos::operation::buffer::BufferInputLineSimplifier Class Reference
Simplifies a buffer input line to remove concavities with shallow depth.
#include <BufferInputLineSimplifier.h>
Public Member Functions
BufferInputLineSimplifier (const geom::CoordinateSequence &input)
std::unique_ptr< geom::CoordinateSequence > simplify (double distanceTol)
Static Public Member Functions
static std::unique_ptr< geom::CoordinateSequence > simplify (const geom::CoordinateSequence &inputLine, double distanceTol)
Private Member Functions
bool deleteShallowConcavities ()
unsigned int findNextNonDeletedIndex (unsigned int index) const
std::unique_ptr< geom::CoordinateSequence > collapseLine () const
bool isDeletable (int i0, int i1, int i2, double distanceTol) const
bool isShallowConcavity (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &p2, double distanceTol) const
bool isShallowSampled (const geom::Coordinate &p0, const geom::Coordinate &p2, int i0, int i2, double distanceTol) const
bool isShallow (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &p2, double distanceTol) const
bool isConcave (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &p2) const
BufferInputLineSimplifier (const BufferInputLineSimplifier &other)=delete
BufferInputLineSimplifier & operator= (const BufferInputLineSimplifier &rhs)=delete
Private Attributes
const geom::CoordinateSequence & inputLine
double distanceTol
std::vector< int > isDeleted
int angleOrientation
Static Private Attributes
static const int NUM_PTS_TO_CHECK = 10
static const int INIT = 0
static const int DELETE = 1
static const int KEEP = 1
Detailed Description
Simplifies a buffer input line to remove concavities with shallow depth.
The most important benefit of doing this is to reduce the number of points and the complexity of shape which will be buffered. It also reduces the risk of gores created by the quantized fillet arcs (although this issue should be eliminated in any case by the offset curve generation logic).
A key aspect of the simplification is that it affects inside (concave or inward) corners only. Convex (outward) corners are preserved, since they are required to ensure that the generated buffer curve lies at the correct distance from the input geometry.
Another important heuristic used is that the end segments of the input are never simplified. This ensures that the client buffer code is able to generate end caps faithfully.
No attempt is made to avoid self-intersections in the output. This is acceptable for use for generating a buffer offset curve, since the buffer algorithm is insensitive to invalid polygonal geometry. However, this means that this algorithm cannot be used as a general-purpose polygon simplification technique.
Author
Martin Davis
Definition at line 73 of file BufferInputLineSimplifier.h.
Constructor & Destructor Documentation
geos::operation::buffer::BufferInputLineSimplifier::BufferInputLineSimplifier (const geom::CoordinateSequence & input)
Definition at line 38 of file BufferInputLineSimplifier.cpp.
   :
   inputLine(input),
   angleOrientation(CGAlgorithms::COUNTERCLOCKWISE)
 {}
geos::operation::buffer::BufferInputLineSimplifier::BufferInputLineSimplifier (const BufferInputLineSimplifier & other) private delete
Member Function Documentation
std::unique_ptr< geom::CoordinateSequence > geos::operation::buffer::BufferInputLineSimplifier::collapseLine () const private
Definition at line 124 of file BufferInputLineSimplifier.cpp.
References DELETE, inputLine, isDeleted, and geos::geom::CoordinateSequence::size().
Referenced by simplify().
 {
   std::unique_ptr<geom::CoordinateSequence> coordList(
     new CoordinateArraySequence());
   for (size_t i=0, n=inputLine.size(); i<n; ++i)
   {
     if (isDeleted[i] != DELETE)
       coordList->add(inputLine[i], false);
   }
   return coordList;
 }
bool geos::operation::buffer::BufferInputLineSimplifier::deleteShallowConcavities () private
Uses a sliding window containing 3 vertices to detect shallow angles in which the middle vertex can be deleted, since it does not affect the shape of the resulting buffer in a significant way.
Returns
Do not simplify end line segments of the line string. This ensures that end caps are generated consistently.
Definition at line 76 of file BufferInputLineSimplifier.cpp.
References DELETE, distanceTol, findNextNonDeletedIndex(), inputLine, isDeletable(), isDeleted, and geos::geom::CoordinateSequence::size().
Referenced by simplify().
 {
   unsigned int index = 1;
   unsigned int midIndex = findNextNonDeletedIndex(index);
   unsigned int lastIndex = findNextNonDeletedIndex(midIndex);
   bool isChanged = false;
   while (lastIndex < inputLine.size())
   {
     // test triple for shallow concavity
     bool isMiddleVertexDeleted = false;
     if (isDeletable(index, midIndex, lastIndex,
                     distanceTol))
     {
       isDeleted[midIndex] = DELETE;
       isMiddleVertexDeleted = true;
       isChanged = true;
     }
     // move simplification window forward
     if (isMiddleVertexDeleted)
       index = lastIndex;
     else
       index = midIndex;
     midIndex = findNextNonDeletedIndex(index);
     lastIndex = findNextNonDeletedIndex(midIndex);
   }
   return isChanged;
 }
unsigned int geos::operation::buffer::BufferInputLineSimplifier::findNextNonDeletedIndex (unsigned int index) const private
Finds the next non-deleted index, or the end of the point array if none
Parameters
index
Returns
the next non-deleted index, if any
inputLine.size() if there are no more non-deleted indices
Definition at line 113 of file BufferInputLineSimplifier.cpp.
References DELETE, inputLine, isDeleted, and geos::geom::CoordinateSequence::size().
Referenced by deleteShallowConcavities().
 {
   std::size_t next = index + 1;
   const std::size_t len = inputLine.size();
   while (next < len && isDeleted[next] == DELETE)
     next++;
   return static_cast<unsigned int>(next);
 }
bool geos::operation::buffer::BufferInputLineSimplifier::isConcave (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & p2) const private
Definition at line 203 of file BufferInputLineSimplifier.cpp.
References angleOrientation.
Referenced by isDeletable().
 {
   int orientation = CGAlgorithms::computeOrientation(p0, p1, p2);
   bool isConcave = (orientation == angleOrientation);
   return isConcave;
 }
bool geos::operation::buffer::BufferInputLineSimplifier::isDeletable (int i0, int i1, int i2, double distanceTol) const private
Definition at line 140 of file BufferInputLineSimplifier.cpp.
References inputLine, isConcave(), isShallow(), and isShallowSampled().
Referenced by deleteShallowConcavities().
 {
   const Coordinate& p0 = inputLine[i0];
   const Coordinate& p1 = inputLine[i1];
   const Coordinate& p2 = inputLine[i2];
   if (! isConcave(p0, p1, p2)) return false;
   if (! isShallow(p0, p1, p2, distanceTol)) return false;
   // MD - don't use this heuristic - it's too restricting
   // if (p0.distance(p2) > distanceTol) return false;
   return isShallowSampled(p0, p1, i0, i2, distanceTol);
 }
bool geos::operation::buffer::BufferInputLineSimplifier::isShallow (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & p2, double distanceTol) const private
Definition at line 192 of file BufferInputLineSimplifier.cpp.
References distanceTol.
Referenced by isDeletable(), and isShallowSampled().
 {
   double dist = CGAlgorithms::distancePointLine(p1, p0, p2);
   return dist < distanceTol;
 }
bool geos::operation::buffer::BufferInputLineSimplifier::isShallowConcavity (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & p2, double distanceTol) const private
Definition at line 158 of file BufferInputLineSimplifier.cpp.
References angleOrientation, and distanceTol.
 {
   int orientation = CGAlgorithms::computeOrientation(p0, p1, p2);
   bool isAngleToSimplify = (orientation == angleOrientation);
   if (! isAngleToSimplify)
     return false;
   double dist = CGAlgorithms::distancePointLine(p1, p0, p2);
   return dist < distanceTol;
 }
bool geos::operation::buffer::BufferInputLineSimplifier::isShallowSampled (const geom::Coordinate & p0, const geom::Coordinate & p2, int i0, int i2, double distanceTol) const private
Checks for shallowness over a sample of points in the given section.
This helps prevents the siplification from incrementally "skipping" over points which are in fact non-shallow.
Parameters
p0 start coordinate of section
p2 end coordinate of section
i0 start index of section
i2 end index of section
distanceTol distance tolerance
Returns
Definition at line 174 of file BufferInputLineSimplifier.cpp.
References inputLine, isShallow(), and NUM_PTS_TO_CHECK.
Referenced by isDeletable().
 {
   // check every n'th point to see if it is within tolerance
   int inc = (i2 - i0) / NUM_PTS_TO_CHECK;
   if (inc <= 0) inc = 1;
   for (int i = i0; i < i2; i += inc) {
     if (! isShallow(p0, p2, inputLine[i], distanceTol))
       return false;
   }
   return true;
 }
BufferInputLineSimplifier& geos::operation::buffer::BufferInputLineSimplifier::operator= (const BufferInputLineSimplifier & rhs) private delete
std::unique_ptr< geom::CoordinateSequence > geos::operation::buffer::BufferInputLineSimplifier::simplify (const geom::CoordinateSequence & inputLine, double distanceTol) static
Simplify the input coordinate list.
If the distance tolerance is positive, concavities on the LEFT side of the line are simplified. If the supplied distance tolerance is negative, concavities on the RIGHT side of the line are simplified.
Parameters
inputLine the coordinate sequence to simplify
distanceTol simplification distance tolerance to use
Returns
a simplified version of the coordinate sequence
Definition at line 47 of file BufferInputLineSimplifier.cpp.
References simplify().
Referenced by simplify().
 {
   BufferInputLineSimplifier simp(inputLine);
   return simp.simplify(distanceTol);
 }
std::unique_ptr< geom::CoordinateSequence > geos::operation::buffer::BufferInputLineSimplifier::simplify (double distanceTol)
Simplify the input coordinate list. If the distance tolerance is positive, concavities on the LEFT side of the line are simplified. If the supplied distance tolerance is negative, concavities on the RIGHT side of the line are simplified.
Parameters
distanceTol simplification distance tolerance to use
Returns
the simplified coordinate list
Definition at line 56 of file BufferInputLineSimplifier.cpp.
References angleOrientation, collapseLine(), deleteShallowConcavities(), distanceTol, INIT, inputLine, isDeleted, and geos::geom::CoordinateSequence::size().
 {
   distanceTol = fabs(nDistanceTol);
   if (nDistanceTol < 0)
     angleOrientation = CGAlgorithms::CLOCKWISE;
   // rely on fact that boolean array is filled with false value
   static const int startValue = INIT;
   isDeleted.assign(inputLine.size(), startValue);
   bool isChanged = false;
   do {
     isChanged = deleteShallowConcavities();
   } while (isChanged);
   return collapseLine();
 }
Member Data Documentation
int geos::operation::buffer::BufferInputLineSimplifier::angleOrientation private
Definition at line 172 of file BufferInputLineSimplifier.h.
Referenced by isConcave(), isShallowConcavity(), and simplify().
const int geos::operation::buffer::BufferInputLineSimplifier::DELETE = 1 static private
Definition at line 165 of file BufferInputLineSimplifier.h.
Referenced by collapseLine(), deleteShallowConcavities(), and findNextNonDeletedIndex().
double geos::operation::buffer::BufferInputLineSimplifier::distanceTol private
Definition at line 169 of file BufferInputLineSimplifier.h.
Referenced by deleteShallowConcavities(), isShallow(), isShallowConcavity(), and simplify().
const int geos::operation::buffer::BufferInputLineSimplifier::INIT = 0 static private
Definition at line 164 of file BufferInputLineSimplifier.h.
Referenced by simplify().
const geom::CoordinateSequence& geos::operation::buffer::BufferInputLineSimplifier::inputLine private
Definition at line 168 of file BufferInputLineSimplifier.h.
Referenced by collapseLine(), deleteShallowConcavities(), findNextNonDeletedIndex(), isDeletable(), isShallowSampled(), and simplify().
std::vector<int> geos::operation::buffer::BufferInputLineSimplifier::isDeleted private
Definition at line 170 of file BufferInputLineSimplifier.h.
Referenced by collapseLine(), deleteShallowConcavities(), findNextNonDeletedIndex(), and simplify().
const int geos::operation::buffer::BufferInputLineSimplifier::KEEP = 1 static private
Definition at line 166 of file BufferInputLineSimplifier.h.
const int geos::operation::buffer::BufferInputLineSimplifier::NUM_PTS_TO_CHECK = 10 static private
Definition at line 162 of file BufferInputLineSimplifier.h.
Referenced by isShallowSampled().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/BufferInputLineSimplifier.h
/home/vicky/potree/geos/vicky/src/operation/buffer/BufferInputLineSimplifier.cpp