GEOS: geos::operation::valid::RepeatedPointTester Class Reference
geos::operation::valid::RepeatedPointTester Class Reference
Implements the appropriate checks for repeated points (consecutive identical coordinates) as defined in the JTS spec.
#include <RepeatedPointTester.h>
Public Member Functions
RepeatedPointTester ()
geom::Coordinate & getCoordinate ()
bool hasRepeatedPoint (const geom::Geometry *g)
bool hasRepeatedPoint (const geom::CoordinateSequence *coord)
Private Member Functions
bool hasRepeatedPoint (const geom::Polygon *p)
bool hasRepeatedPoint (const geom::GeometryCollection *gc)
bool hasRepeatedPoint (const geom::MultiPolygon *gc)
bool hasRepeatedPoint (const geom::MultiLineString *gc)
Private Attributes
geom::Coordinate repeatedCoord
Detailed Description
Implements the appropriate checks for repeated points (consecutive identical coordinates) as defined in the JTS spec.
Definition at line 49 of file RepeatedPointTester.h.
Constructor & Destructor Documentation
geos::operation::valid::RepeatedPointTester::RepeatedPointTester () inline
Definition at line 51 of file RepeatedPointTester.h.
 {}
Member Function Documentation
Coordinate & geos::operation::valid::RepeatedPointTester::getCoordinate ()
Definition at line 41 of file RepeatedPointTester.cpp.
 {
   return repeatedCoord;
 }
bool geos::operation::valid::RepeatedPointTester::hasRepeatedPoint (const geom::Geometry * g)
Definition at line 47 of file RepeatedPointTester.cpp.
References geos::geom::Geometry::isEmpty().
 {
   if (g->isEmpty()) return false;
   if ( dynamic_cast<const Point*>(g) ) return false;
   if ( dynamic_cast<const MultiPoint*>(g) ) return false;
   // LineString also handles LinearRings
   if ( const LineString* x = dynamic_cast<const LineString*>(g) )
   {
     return hasRepeatedPoint(x->getCoordinatesRO());
   }
   if ( const Polygon* x = dynamic_cast<const Polygon*>(g) )
   {
     return hasRepeatedPoint(x);
   }
   if ( const MultiPolygon* x = dynamic_cast<const MultiPolygon*>(g) )
   {
     return hasRepeatedPoint(x);
   }
   if ( const MultiLineString* x = dynamic_cast<const MultiLineString*>(g) )
   {
     return hasRepeatedPoint(x);
   }
   if ( const GeometryCollection* x = dynamic_cast<const GeometryCollection*>(g) )
   {
     return hasRepeatedPoint(x);
   }
   throw util::UnsupportedOperationException(typeid(*g).name());
 }
bool geos::operation::valid::RepeatedPointTester::hasRepeatedPoint (const geom::CoordinateSequence * coord)
Definition at line 84 of file RepeatedPointTester.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   auto npts=coord->getSize();
   for(size_t i=1; i<npts; ++i)
   {
     if (coord->getAt(i - 1)==coord->getAt(i)) {
       repeatedCoord=coord->getAt(i);
       return true;
     }
   }
   return false;
 }
bool geos::operation::valid::RepeatedPointTester::hasRepeatedPoint (const geom::Polygon * p) private
Definition at line 98 of file RepeatedPointTester.cpp.
References geos::geom::LineString::getCoordinates(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), and geos::geom::Polygon::getNumInteriorRing().
 {
   if (hasRepeatedPoint(p->getExteriorRing()->getCoordinates()))
   {
     return true;
   }
   for(size_t i=0, n=p->getNumInteriorRing(); i<n; ++i)
   {
     if (hasRepeatedPoint(p->getInteriorRingN(i)->getCoordinates()))
     {
       return true;
     }
   }
   return false;
 }
bool geos::operation::valid::RepeatedPointTester::hasRepeatedPoint (const geom::GeometryCollection * gc) private
Definition at line 116 of file RepeatedPointTester.cpp.
References geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   for(size_t i=0, n=gc->getNumGeometries(); i<n; ++i)
   {
     const Geometry *g=gc->getGeometryN(i);
     if (hasRepeatedPoint(g)) return true;
   }
   return false;
 }
bool geos::operation::valid::RepeatedPointTester::hasRepeatedPoint (const geom::MultiPolygon * gc) private
Definition at line 127 of file RepeatedPointTester.cpp.
References geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   for(size_t i=0, n=gc->getNumGeometries(); i<n; ++i)
   {
     const Geometry *g=gc->getGeometryN(i);
     if (hasRepeatedPoint(g)) return true;
   }
   return false;
 }
bool geos::operation::valid::RepeatedPointTester::hasRepeatedPoint (const geom::MultiLineString * gc) private
Definition at line 138 of file RepeatedPointTester.cpp.
References geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   for(size_t i=0, n=gc->getNumGeometries(); i<n; ++i)
   {
     const Geometry *g=gc->getGeometryN(i);
     if (hasRepeatedPoint(g)) return true;
   }
   return false;
 }
Member Data Documentation
geom::Coordinate geos::operation::valid::RepeatedPointTester::repeatedCoord private
Definition at line 56 of file RepeatedPointTester.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/valid/RepeatedPointTester.h
/home/vicky/potree/geos/vicky/src/operation/valid/RepeatedPointTester.cpp