GEOS: geos::operation::polygonize::PolygonizeGraph Class Reference
geos::operation::polygonize::PolygonizeGraph Class Reference
Represents a planar graph of edges that can be used to compute a polygonization, and implements the algorithms to compute the EdgeRings formed by the graph.
#include <PolygonizeGraph.h>
Public Types
typedef std::vector< Edge * > EdgeContainer
typedef EdgeContainer::iterator EdgeIterator
Public Member Functions
bool empty () const
void deleteAllEdges (planargraph::Node *node)
Deletes all edges at a node.
PolygonizeGraph ()
Create a new polygonization graph.
PolygonizeGraph (const geom::GeometryFactory *newFactory)
~PolygonizeGraph () override
Destroy a polygonization graph.
void addEdge (const geom::LineString *line)
Add a LineString forming an edge of the polygon graph.
void getEdgeRings (std::vector< EdgeRing * > &edgeRingList)
Computes the EdgeRings formed by the edges in this graph.
std::vector< EdgeRing * > getEdgeRings () const
Computes the EdgeRings formed by the edges in this graph.
std::vector< const geom::LineString * > deleteCutEdges ()
Finds and removes all cut edges from the graph.
void deleteCutEdges (std::vector< const geom::LineString * > &cutLines)
std::vector< const geom::LineString * > deleteDangles ()
Marks all edges from the graph which are "dangles".
void deleteDangles (std::vector< const geom::LineString * > &dangleLines)
Node * findNode (const geom::Coordinate &pt)
Returns the Node at the given location, or null if no Node was there.
NodeMap::container::iterator nodeIterator ()
Returns an Iterator over the Nodes in this PlanarGraph.
NodeMap::container::iterator nodeBegin ()
NodeMap::container::const_iterator nodeBegin () const
NodeMap::container::iterator nodeEnd ()
NodeMap::container::const_iterator nodeEnd () const
void getNodes (std::vector< Node * > &nodes) const
Returns the Nodes in this PlanarGraph.
std::vector< DirectedEdge * >::iterator dirEdgeIterator ()
Returns an Iterator over the DirectedEdges in this PlanarGraph, in the order in which they were added.
std::vector< Edge * >::iterator edgeIterator ()
Alias for edgeBegin()
std::vector< Edge * >::iterator edgeBegin ()
Returns an iterator to first Edge in this graph.
std::vector< Edge * >::iterator edgeEnd ()
Returns an iterator to one-past last Edge in this graph.
std::vector< Edge * > * getEdges ()
Returns the Edges that have been added to this PlanarGraph.
void remove (Edge *edge)
Removes an Edge and its associated DirectedEdges from their from-Nodes and from this PlanarGraph.
void remove (DirectedEdge *de)
Removes DirectedEdge from its from-Node and from this PlanarGraph.
void remove (Node *node)
Removes a node from the graph, along with any associated DirectedEdges and Edges.
std::vector< Node * > findNodesOfDegree (std::size_t degree) const
Returns all Nodes with the given number of Edges around it. The return value is a newly allocated vector of existing nodes.
void findNodesOfDegree (std::size_t degree, std::vector< Node * > &to) const
Get all Nodes with the given number of Edges around it.
Protected Member Functions
void add (Node *node)
Adds a node to the std::map, replacing any that is already at that location.
void add (Edge *edge)
Adds the Edge and its DirectedEdges with this PlanarGraph.
void add (DirectedEdge *dirEdge)
Adds the Edge to this PlanarGraph.
Protected Attributes
std::vector< Edge * > edges
std::vector< DirectedEdge * > dirEdges
NodeMap nodeMap
Private Member Functions
int getDegreeNonDeleted (planargraph::Node *node) const
int getDegree (planargraph::Node *node, long label) const
planargraph::Node * getNode (const geom::Coordinate &pt)
void computeNextCWEdges () const
void convertMaximalToMinimalEdgeRings (const std::vector< PolygonizeDirectedEdge * > ringEdges) const
Convert the maximal edge rings found by the initial graph traversal into the minimal edge rings required by JTS polygon topology rules.
std::vector< planargraph::Node * > findIntersectionNodes (PolygonizeDirectedEdge *startDE, long label) const
Finds all nodes in a maximal edgering which are self-intersection nodes.
std::vector< PolygonizeDirectedEdge * > findLabeledEdgeRings (const std::vector< planargraph::DirectedEdge * > dirEdgesIn) const
void label (const std::vector< planargraph::DirectedEdge * > &dirEdges, long label) const
void computeNextCWEdges (planargraph::Node *node) const
void computeNextCCWEdges (planargraph::Node *node, long label) const
Computes the next edge pointers going CCW around the given node, for the given edgering label. This algorithm has the effect of converting maximal edgerings into minimal edgerings.
std::vector< planargraph::DirectedEdge * > findDirEdgesInRing (PolygonizeDirectedEdge *startDE) const
Traverse a ring of DirectedEdges, accumulating them into a list. This assumes that all dangling directed edges have been removed from the graph, so that there is always a next dirEdge.
EdgeRing * findEdgeRing (PolygonizeDirectedEdge *startDE) const
Private Attributes
const geom::GeometryFactory * factory
std::vector< planargraph::Edge * > newEdges
std::vector< planargraph::DirectedEdge * > newDirEdges
std::vector< planargraph::Node * > newNodes
std::vector< EdgeRing * > newEdgeRings
std::vector< geom::CoordinateSequence * > newCoords
Detailed Description
Represents a planar graph of edges that can be used to compute a polygonization, and implements the algorithms to compute the EdgeRings formed by the graph.
The marked flag on DirectedEdge is used to indicate that a directed edge has be logically deleted from the graph.
Definition at line 72 of file PolygonizeGraph.h.
Member Typedef Documentation
typedef std::vector<Edge *> geos::planargraph::PlanarGraph::EdgeContainer inherited
Definition at line 105 of file PlanarGraph.h.
typedef EdgeContainer::iterator geos::planargraph::PlanarGraph::EdgeIterator inherited
Definition at line 106 of file PlanarGraph.h.
Constructor & Destructor Documentation
geos::operation::polygonize::PolygonizeGraph::PolygonizeGraph () inline
Create a new polygonization graph.
Definition at line 85 of file PolygonizeGraph.h.
 {factory = new geom::GeometryFactory();};
geos::operation::polygonize::PolygonizeGraph::PolygonizeGraph (const geom::GeometryFactory * newFactory) explicit
Definition at line 85 of file PolygonizeGraph.cpp.
   : factory(newFactory) {
 }
geos::operation::polygonize::PolygonizeGraph::~PolygonizeGraph () override
Destroy a polygonization graph.
Definition at line 92 of file PolygonizeGraph.cpp.
References newCoords, newDirEdges, newEdgeRings, newEdges, and newNodes.
{
   for (auto e : newEdges) delete e;
   for (auto e : newDirEdges) delete e;
   for (auto n : newNodes) delete n;
   for (auto e : newEdgeRings) delete e;
   for (auto c : newCoords) delete c;
 }
Member Function Documentation
void geos::planargraph::PlanarGraph::add (Node * node) inline protected inherited
Adds a node to the std::map, replacing any that is already at that location.
Only subclasses can add Nodes, to ensure Nodes are of the right type.
Returns
the added node
Definition at line 77 of file PlanarGraph.h.
References geos::planargraph::NodeMap::add().
Referenced by addEdge(), and getNode().
{
     nodeMap.add(node);
   }
void geos::planargraph::PlanarGraph::add (Edge * edge) protected inherited
Adds the Edge and its DirectedEdges with this PlanarGraph.
Assumes that the Edge has already been created with its associated DirectEdges. Only subclasses can add Edges, to ensure the edges added are of the right class.
Definition at line 51 of file PlanarGraph.cpp.
References geos::planargraph::Edge::getDirEdge().
 {
   edges.push_back(edge);
   add(edge->getDirEdge(0));
   add(edge->getDirEdge(1));
 }
void geos::planargraph::PlanarGraph::add (DirectedEdge * dirEdge) inline protected inherited
Adds the Edge to this PlanarGraph.
Only subclasses can add DirectedEdges, to ensure the edges added are of the right class.
Definition at line 99 of file PlanarGraph.h.
{
     dirEdges.push_back(dirEdge);
   }
void geos::operation::polygonize::PolygonizeGraph::addEdge (const geom::LineString * line)
Add a LineString forming an edge of the polygon graph.
Parameters
line the line to add
Definition at line 105 of file PolygonizeGraph.cpp.
References geos::planargraph::PlanarGraph::add(), geos::geom::LineString::getCoordinatesRO(), getNode(), geos::geom::LineString::isEmpty(), newCoords, newDirEdges, newEdges, and geos::planargraph::Edge::setDirectedEdges().
Referenced by geos::operation::polygonize::Polygonizer::add().
{
   if (line->isEmpty()) return;
   // TODO(vicky) fix CoordinateSequence::removeRepeatedPoints function
   auto linePts = CoordinateSequence::removeRepeatedPoints(line->getCoordinatesRO());
   /*
    * This would catch invalid linestrings
    * (containing duplicated points only)
    */
   if ( linePts->getSize() < 2 ) {
     delete linePts;
     return;
   }
   const Coordinate& startPt = linePts->getAt(0);
   const Coordinate& endPt = linePts->getAt(linePts->getSize() - 1);
   auto nStart = getNode(startPt);
   auto nEnd = getNode(endPt);
   DirectedEdge *de0 = new PolygonizeDirectedEdge(
       nStart, nEnd, linePts->getAt(1), true);
   newDirEdges.push_back(de0);
   DirectedEdge *de1 = new PolygonizeDirectedEdge(
       nEnd, nStart, linePts->getAt(linePts->getSize() - 2), false);
   newDirEdges.push_back(de1);
   Edge *edge = new PolygonizeEdge(line);
   newEdges.push_back(edge);
   edge->setDirectedEdges(de0, de1);
   add(edge);
   newCoords.push_back(linePts);
 }
void geos::operation::polygonize::PolygonizeGraph::computeNextCCWEdges (planargraph::Node * node, long label) const private
Computes the next edge pointers going CCW around the given node, for the given edgering label. This algorithm has the effect of converting maximal edgerings into minimal edgerings.
Computes the next edge pointers going CCW around the given node, for the given edgering label. This algorithm has the effect of converting maximal edgerings into minimal edgerings
Definition at line 333 of file PolygonizeGraph.cpp.
References geos::planargraph::PlanarGraph::edges, geos::planargraph::Node::getOutEdges(), label(), and geos::operation::polygonize::PolygonizeDirectedEdge::setNext().
Referenced by convertMaximalToMinimalEdgeRings().
{
   auto deStar = node->getOutEdges();
   PolygonizeDirectedEdge *firstOutDE = nullptr;
   PolygonizeDirectedEdge *prevInDE = nullptr;
   // the edges are stored in CCW order around the star
   auto edges = deStar.getEdges();
   /*
    * Cycling in reverse order.
    */
   for(auto i = edges.size(); i > 0; --i) {
     auto de = dynamic_cast<PolygonizeDirectedEdge*>(edges[i - 1]);
     auto sym = dynamic_cast<PolygonizeDirectedEdge*>(de->getSym());
     auto outDE = (de->getLabel() == label)? de : nullptr;
     auto inDE = (sym->getLabel() == label)? sym : nullptr;
     if (!outDE && !inDE) continue;  // this edge is not in edgering
     if (inDE) prevInDE = inDE;
     if (outDE) {
       if (prevInDE) {
         prevInDE->setNext(outDE);
         prevInDE = nullptr;
       }
       if (!firstOutDE) firstOutDE = outDE;
     }
   }
   if (prevInDE) {
     assert(firstOutDE);
     prevInDE->setNext(firstOutDE);
   }
 }
void geos::operation::polygonize::PolygonizeGraph::computeNextCWEdges () const private
Definition at line 151 of file PolygonizeGraph.cpp.
References geos::planargraph::PlanarGraph::getNodes().
Referenced by deleteCutEdges(), and getEdgeRings().
{
   typedef std::vector<Node*> Nodes;
   Nodes pns;
   getNodes(pns);
   // set the next pointers for the edges around each node
   for(auto n : pns) {
     computeNextCWEdges(n);
   }
 }
void geos::operation::polygonize::PolygonizeGraph::computeNextCWEdges (planargraph::Node * node) const private
Definition at line 305 of file PolygonizeGraph.cpp.
References geos::planargraph::Node::getOutEdges(), and geos::planargraph::DirectedEdge::getSym().
{
   auto deStar = node->getOutEdges();
   PolygonizeDirectedEdge *startDE = nullptr;
   PolygonizeDirectedEdge *prevDE = nullptr;
   // the edges are stored in CCW order around the star
   auto pde = deStar.getEdges();
   for (auto e : pde) {
     auto outDE = dynamic_cast<PolygonizeDirectedEdge*>(e);
     if (outDE->isMarked()) continue;
     if (!startDE) startDE = outDE;
     if (prevDE) {
       dynamic_cast<PolygonizeDirectedEdge*>(prevDE->getSym())->setNext(outDE);
     }
     prevDE = outDE;
   }
   if (prevDE) {
     dynamic_cast<PolygonizeDirectedEdge*>(prevDE->getSym())->setNext(startDE);
   }
 }
void geos::operation::polygonize::PolygonizeGraph::convertMaximalToMinimalEdgeRings (const std::vector< PolygonizeDirectedEdge * > ringEdges) const private
Convert the maximal edge rings found by the initial graph traversal into the minimal edge rings required by JTS polygon topology rules.
Parameters
ringEdges the list of start edges for the edgeRings to convert.
Definition at line 163 of file PolygonizeGraph.cpp.
References computeNextCCWEdges(), findIntersectionNodes(), and label().
Referenced by getEdgeRings().
{
   for (const auto de : ringEdges) {
     auto label = de->getLabel();
     auto intNodes = findIntersectionNodes(de, label);
     for (auto n : intNodes) {
       computeNextCCWEdges(n, label);
     }
   }
 }
void geos::operation::polygonize::PolygonizeGraph::deleteAllEdges (planargraph::Node * node)
Deletes all edges at a node.
marks them as Deleted
Definition at line 73 of file PolygonizeGraph.cpp.
References geos::planargraph::PlanarGraph::edges, geos::planargraph::DirectedEdgeStar::getEdges(), geos::planargraph::Node::getOutEdges(), and geos::planargraph::GraphComponent::setMarked().
Referenced by deleteDangles().
{
   auto edges(node->getOutEdges().getEdges());
   for (auto e : edges) {
     auto de = dynamic_cast<PolygonizeDirectedEdge*>(e);
     de->setMarked(true);
     if (de->getSym()) de->getSym()->setMarked(true);
   }
 }
std::vector< const LineString * > geos::operation::polygonize::PolygonizeGraph::deleteCutEdges ()
Finds and removes all cut edges from the graph.
Returns
vector with the list of the LineString forming the removed cut edges will be pushed here.
Definition at line 256 of file PolygonizeGraph.cpp.
References computeNextCWEdges(), geos::planargraph::PlanarGraph::dirEdges, findLabeledEdgeRings(), and geos::planargraph::GraphComponent::setMarked().
Referenced by deleteCutEdges(), and geos::operation::polygonize::Polygonizer::polygonize().
{
   std::vector<const LineString*> cutLines;
   computeNextCWEdges();
   // label the current set of edgerings
   /* even that is a find it has side efects on the labels */
   findLabeledEdgeRings(dirEdges);  // ignoring the result
   /*
    * Cut Edges are edges where both dirEdges have the same label.
    * Delete them, and record them
    */
   for (auto e : dirEdges) {
     auto de = dynamic_cast<PolygonizeDirectedEdge*>(e);
     if (de->isMarked()) continue;
     auto sym = dynamic_cast<PolygonizeDirectedEdge*>(de->getSym());
     if (de->getLabel() == sym->getLabel()) {
       de->setMarked(true);
       sym->setMarked(true);
       // save the line as a cut edge
       auto ce = dynamic_cast<PolygonizeEdge*>(de->getEdge());
       cutLines.push_back(ce->getLine());
     }
   }
   return cutLines;
 }
void geos::operation::polygonize::PolygonizeGraph::deleteCutEdges (std::vector< const geom::LineString * > & cutLines)
Definition at line 291 of file PolygonizeGraph.cpp.
References deleteCutEdges().
{
   cutLines = deleteCutEdges();
 }
std::vector< const LineString * > geos::operation::polygonize::PolygonizeGraph::deleteDangles ()
Marks all edges from the graph which are "dangles".
Dangles are which are incident on a node with degree 1. This process is recursive, since removing a dangling edge may result in another edge becoming a dangle. In order to handle large recursion depths efficiently, an explicit recursion stack is used
Parameters
dangleLines : the LineStrings that formed dangles will be push_back'ed here
Definition at line 401 of file PolygonizeGraph.cpp.
References deleteAllEdges(), geos::planargraph::PlanarGraph::findNodesOfDegree(), and getDegreeNonDeleted().
Referenced by deleteDangles(), and geos::operation::polygonize::Polygonizer::polygonize().
{
   std::vector<const LineString*> dangleLines;
   auto nodeStack = findNodesOfDegree(1);
   std::set<const LineString*> uniqueDangles;
   while (!nodeStack.empty()) {
     auto node = nodeStack.back();
     nodeStack.pop_back();
     deleteAllEdges(node);
     /* get sorted edges in ascending order by angle with the positive x-axis */
     auto nodeOutEdges(node->getOutEdges().getEdges());
     for(auto oe : nodeOutEdges) {
       auto de(dynamic_cast<PolygonizeDirectedEdge*>(oe));
       // delete this edge and its sym
       de->setMarked(true);
       auto sym(dynamic_cast<PolygonizeDirectedEdge*>(de->getSym()));
       if (sym) sym->setMarked(true);
       // save the line as a dangle
       auto e(dynamic_cast<PolygonizeEdge*>(de->getEdge()));
       auto ls(e->getLine());
       if (uniqueDangles.insert(ls).second) {
         dangleLines.push_back(ls);
       }
       auto toNode = de->getToNode();
       // add the toNode to the list to be processed,
       // if it is now a dangle
       if (getDegreeNonDeleted(toNode) == 1) {
         nodeStack.push_back(toNode);
       }
     }
   }
   return dangleLines;
 }
void geos::operation::polygonize::PolygonizeGraph::deleteDangles (std::vector< const geom::LineString * > & dangleLines)
Definition at line 442 of file PolygonizeGraph.cpp.
References deleteDangles().
{
   dangleLines = deleteDangles();
 }
std::vector<DirectedEdge*>::iterator geos::planargraph::PlanarGraph::dirEdgeIterator () inline inherited
Returns an Iterator over the DirectedEdges in this PlanarGraph, in the order in which they were added.
See also
add(Edge)
add(DirectedEdge)
Definition at line 166 of file PlanarGraph.h.
{
     return dirEdges.begin();
   }
std::vector<Edge*>::iterator geos::planargraph::PlanarGraph::edgeBegin () inline inherited
Returns an iterator to first Edge in this graph.
Edges are stored in the order they were added.
See also
add(Edge)
Definition at line 180 of file PlanarGraph.h.
{
     return edges.begin();
   }
std::vector<Edge*>::iterator geos::planargraph::PlanarGraph::edgeEnd () inline inherited
Returns an iterator to one-past last Edge in this graph.
Edges are stored in the order they were added.
See also
add(Edge)
Definition at line 189 of file PlanarGraph.h.
Referenced by geos::operation::linemerge::LineMerger::merge().
{
     return edges.end();
   }
std::vector<Edge*>::iterator geos::planargraph::PlanarGraph::edgeIterator () inline inherited
Alias for edgeBegin()
Definition at line 171 of file PlanarGraph.h.
Referenced by geos::operation::linemerge::LineMerger::merge().
{
     return edges.begin();
   }
bool geos::operation::polygonize::PolygonizeGraph::empty () const inline
Definition at line 74 of file PolygonizeGraph.h.
Referenced by geos::operation::polygonize::Polygonizer::add(), and geos::operation::polygonize::Polygonizer::polygonize().
 {return newNodes.empty();}
std::vector< DirectedEdge * > geos::operation::polygonize::PolygonizeGraph::findDirEdgesInRing (PolygonizeDirectedEdge * startDE) const private
Traverse a ring of DirectedEdges, accumulating them into a list. This assumes that all dangling directed edges have been removed from the graph, so that there is always a next dirEdge.
Parameters
startDE the DirectedEdge to start traversing at
Returns
a vector of the DirectedEdge that form a ring
Definition at line 370 of file PolygonizeGraph.cpp.
References geos::planargraph::PlanarGraph::edges, and geos::operation::polygonize::PolygonizeDirectedEdge::isInRing().
Referenced by findLabeledEdgeRings().
{
   auto de = startDE;
   std::vector<DirectedEdge*> edges;
   do {
     edges.push_back(de);
     de = de->getNext();
     assert(de);  // found NULL DE in ring
     assert(de == startDE || !de->isInRing());  // found DE already in ring
   } while (de != startDE);
   return edges;
 }
EdgeRing * geos::operation::polygonize::PolygonizeGraph::findEdgeRing (PolygonizeDirectedEdge * startDE) const private
Definition at line 384 of file PolygonizeGraph.cpp.
References geos::operation::polygonize::EdgeRing::add(), factory, geos::operation::polygonize::PolygonizeDirectedEdge::isInRing(), and newEdgeRings.
Referenced by getEdgeRings().
{
   auto de = startDE;
   EdgeRing *er = new EdgeRing(factory);
   // Now, when will we delete those EdgeRings ?
   newEdgeRings.push_back(er);
   do {
     er->add(de);
     de->setRing(er);
     de = de->getNext();
     assert(de);  // found NULL DE in ring
     assert(de == startDE || !de->isInRing());  // found DE already in ring
   } while (de != startDE);
   return er;
 }
std::vector< Node * > geos::operation::polygonize::PolygonizeGraph::findIntersectionNodes (PolygonizeDirectedEdge * startDE, long label) const private
Finds all nodes in a maximal edgering which are self-intersection nodes.
Parameters
startDE
label
intNodes : intersection nodes found will be pushed here the vector won't be cleared before pushing.
Definition at line 175 of file PolygonizeGraph.cpp.
References getDegree(), geos::planargraph::DirectedEdge::getFromNode(), and geos::operation::polygonize::PolygonizeDirectedEdge::isInRing().
Referenced by convertMaximalToMinimalEdgeRings().
                       {
   std::vector<Node*> intNodes;
   auto de = startDE;
   do {
     auto node = de->getFromNode();
     if (getDegree(node, label) > 1) {
       intNodes.push_back(node);
     }
     de = de->getNext();
     assert(de);  // found NULL DE in ring
     assert(de == startDE || !de->isInRing());  // found DE already in ring
   } while (de != startDE);
   return intNodes;
 }
std::vector< PolygonizeDirectedEdge * > geos::operation::polygonize::PolygonizeGraph::findLabeledEdgeRings (const std::vector< planargraph::DirectedEdge * > dirEdgesIn) const private
Finds and labels all edgerings in the graph.
The edge rings are labelling with unique integers. The labelling allows detecting cut edges.
Parameters
dirEdgesIn a list of the DirectedEdges in the graph
Returns
vector that contains each ring found
Definition at line 231 of file PolygonizeGraph.cpp.
References geos::planargraph::PlanarGraph::edges, findDirEdgesInRing(), and label().
Referenced by deleteCutEdges(), and getEdgeRings().
{
   std::vector<PolygonizeDirectedEdge*> edgeRingStarts;
   // label the edge rings formed
   long currLabel(1);
   for (const auto e : dirEdges) {
     auto de = dynamic_cast<PolygonizeDirectedEdge*>(e);
     if (de->isMarked()) continue;
     if (de->getLabel() >= 0) continue;
     edgeRingStarts.push_back(de);
     auto edges = findDirEdgesInRing(de);
     label(edges, currLabel);
     ++currLabel;
   }
   return edgeRingStarts;
 }
Node* geos::planargraph::PlanarGraph::findNode (const geom::Coordinate & pt) inline inherited
Returns the Node at the given location, or null if no Node was there.
Definition at line 122 of file PlanarGraph.h.
References geos::planargraph::NodeMap::find().
Referenced by getNode().
{
     return nodeMap.find(pt);
   }
std::vector<Node*> geos::planargraph::PlanarGraph::findNodesOfDegree (std::size_t degree) const inherited
Returns all Nodes with the given number of Edges around it. The return value is a newly allocated vector of existing nodes.
Referenced by deleteDangles().
void geos::planargraph::PlanarGraph::findNodesOfDegree (std::size_t degree, std::vector< Node * > & to) const inherited
Get all Nodes with the given number of Edges around it.
Found nodes are pushed to the given vector
int geos::operation::polygonize::PolygonizeGraph::getDegree (planargraph::Node * node, long label) const private
Definition at line 60 of file PolygonizeGraph.cpp.
References geos::planargraph::PlanarGraph::edges, geos::planargraph::DirectedEdgeStar::getEdges(), geos::planargraph::Node::getOutEdges(), and label().
Referenced by findIntersectionNodes().
{
   auto edges(node->getOutEdges().getEdges());
   int degree = 0;
   for (auto e : edges) {
     if (dynamic_cast<PolygonizeDirectedEdge*>(e)->getLabel() == label) ++degree;
   }
   return degree;
 }
int geos::operation::polygonize::PolygonizeGraph::getDegreeNonDeleted (planargraph::Node * node) const private
Definition at line 50 of file PolygonizeGraph.cpp.
References geos::planargraph::PlanarGraph::edges, geos::planargraph::DirectedEdgeStar::getEdges(), and geos::planargraph::Node::getOutEdges().
Referenced by deleteDangles().
{
   auto edges(node->getOutEdges().getEdges());
   int degree = 0;
   for (auto e : edges) {
     if (!dynamic_cast<PolygonizeDirectedEdge*>(e)->isMarked()) ++degree;
   }
   return degree;
 }
void geos::operation::polygonize::PolygonizeGraph::getEdgeRings (std::vector< EdgeRing * > & edgeRingList)
Computes the EdgeRings formed by the edges in this graph.
Any old values on edgeRingList will be deleted (not destroyed)
Note
Marked as deprecated, because its public
[in/out] edgeRingList : the EdgeRings found by the polygonization process will be pushed here.
Definition at line 225 of file PolygonizeGraph.cpp.
References getEdgeRings().
Referenced by geos::operation::polygonize::Polygonizer::polygonize().
{
   edgeRingList = getEdgeRings();
 }
std::vector< EdgeRing * > geos::operation::polygonize::PolygonizeGraph::getEdgeRings () const
Computes the EdgeRings formed by the edges in this graph.
Returns
edgeRingList: the EdgeRings found by the polygonization process.
Definition at line 196 of file PolygonizeGraph.cpp.
References computeNextCWEdges(), convertMaximalToMinimalEdgeRings(), geos::planargraph::PlanarGraph::dirEdges, findEdgeRing(), findLabeledEdgeRings(), and label().
Referenced by getEdgeRings().
{
   std::vector<EdgeRing*> edgeRingList;
   // maybe could optimize this, since most of these pointers should
   // be set correctly already
   // by deleteCutEdges()
   // CVVC: the function is public,
   //  Q: is there a guaranty that deleteCutEdges has being called?
   computeNextCWEdges();
   // clear labels of all edges in graph
   label(dirEdges, -1);
   convertMaximalToMinimalEdgeRings(findLabeledEdgeRings(dirEdges));
   // find all edgerings
   for (auto e : dirEdges) {
     auto de = dynamic_cast<PolygonizeDirectedEdge*>(e);
     if (de->isMarked()) continue;
     if (de->isInRing()) continue;
     auto er = findEdgeRing(de);
     edgeRingList.push_back(er);
   }
   return edgeRingList;
 }
std::vector<Edge*>* geos::planargraph::PlanarGraph::getEdges () inline inherited
Returns the Edges that have been added to this PlanarGraph.
See also
#add(Edge)
Definition at line 198 of file PlanarGraph.h.
{
     return &edges;
   }
Node * geos::operation::polygonize::PolygonizeGraph::getNode (const geom::Coordinate & pt) private
Definition at line 139 of file PolygonizeGraph.cpp.
References geos::planargraph::PlanarGraph::add(), geos::planargraph::PlanarGraph::findNode(), and newNodes.
Referenced by addEdge().
{
   auto node = findNode(pt);
   if (!node) {
     node = new Node(pt);
     newNodes.push_back(node);
     // ensure node is only added once to graph
     add(node);
   }
   return node;
 }
void geos::planargraph::PlanarGraph::getNodes (std::vector< Node * > & nodes) const inline inherited
Returns the Nodes in this PlanarGraph.
Parameters
nodes : the nodes are push_back'ed here
Definition at line 156 of file PlanarGraph.h.
References geos::planargraph::NodeMap::getNodes().
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForNonDegree2Nodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), and computeNextCWEdges().
 { nodes = nodeMap.getNodes(); }
void geos::operation::polygonize::PolygonizeGraph::label (const std::vector< planargraph::DirectedEdge * > & dirEdges, long label) const private
Definition at line 296 of file PolygonizeGraph.cpp.
Referenced by computeNextCCWEdges(), convertMaximalToMinimalEdgeRings(), findLabeledEdgeRings(), getDegree(), and getEdgeRings().
                       {
   for(auto e : dirEdges) {
     dynamic_cast<PolygonizeDirectedEdge*>(e)->setLabel(label);
   }
 }
NodeMap::container::iterator geos::planargraph::PlanarGraph::nodeBegin () inline inherited
Definition at line 134 of file PlanarGraph.h.
References geos::planargraph::NodeMap::begin().
{
     return nodeMap.begin();
   }
NodeMap::container::const_iterator geos::planargraph::PlanarGraph::nodeBegin () const inline inherited
Definition at line 138 of file PlanarGraph.h.
References geos::planargraph::NodeMap::begin().
{
     return nodeMap.begin();
   }
NodeMap::container::iterator geos::planargraph::PlanarGraph::nodeEnd () inline inherited
Definition at line 142 of file PlanarGraph.h.
References geos::planargraph::NodeMap::end().
Referenced by geos::operation::linemerge::LineMerger::merge().
{
     return nodeMap.end();
   }
NodeMap::container::const_iterator geos::planargraph::PlanarGraph::nodeEnd () const inline inherited
Definition at line 146 of file PlanarGraph.h.
References geos::planargraph::NodeMap::end().
{
     return nodeMap.end();
   }
NodeMap::container::iterator geos::planargraph::PlanarGraph::nodeIterator () inline inherited
Returns an Iterator over the Nodes in this PlanarGraph.
Definition at line 130 of file PlanarGraph.h.
References geos::planargraph::NodeMap::begin().
Referenced by geos::operation::linemerge::LineMerger::merge().
{
     return nodeMap.begin();
   }
void geos::planargraph::PlanarGraph::remove (Edge * edge) inherited
Removes an Edge and its associated DirectedEdges from their from-Nodes and from this PlanarGraph.
Note: This method does not remove the Nodes associated with the Edge, even if the removal of the Edge reduces the degree of a Node to zero.
Definition at line 66 of file PlanarGraph.cpp.
References geos::planargraph::find_and_erase(), and geos::planargraph::Edge::getDirEdge().
 {
   remove(edge->getDirEdge(0));
   remove(edge->getDirEdge(1));
   find_and_erase(edge, edges);
 }
void geos::planargraph::PlanarGraph::remove (DirectedEdge * de) inherited
Removes DirectedEdge from its from-Node and from this PlanarGraph.
Note: This method does not remove the Nodes associated with the DirectedEdge, even if the removal of the DirectedEdge reduces the degree of a Node to zero.
Definition at line 80 of file PlanarGraph.cpp.
References geos::planargraph::find_and_erase(), geos::planargraph::DirectedEdge::getFromNode(), geos::planargraph::Node::getOutEdges(), geos::planargraph::DirectedEdge::getSym(), geos::planargraph::DirectedEdgeStar::remove(), and geos::planargraph::DirectedEdge::setSym().
 {
   DirectedEdge *sym = de->getSym();
   if (sym!=nullptr) sym->setSym(nullptr);
   de->getFromNode()->getOutEdges().remove(de);
   find_and_erase(de, dirEdges);
 }
void geos::planargraph::PlanarGraph::remove (Node * node) inherited
Removes a node from the graph, along with any associated DirectedEdges and Edges.
Definition at line 93 of file PlanarGraph.cpp.
References geos::planargraph::find_and_erase(), geos::planargraph::Node::getCoordinate(), geos::planargraph::DirectedEdgeStar::getEdges(), geos::planargraph::Node::getOutEdges(), and geos::planargraph::DirectedEdge::getSym().
 {
   // unhook all directed edges
   auto & outEdges=node->getOutEdges().getEdges();
   for(auto de : outEdges) {
     DirectedEdge *sym = de->getSym();
     // remove the diredge that points to this node
     if (sym) remove(sym);
     find_and_erase(de, dirEdges);
     find_and_erase(de->getEdge(), edges);
   }
   // remove the node from the graph
   nodeMap.remove(node->getCoordinate());
   //nodes.remove(node);
 }
Member Data Documentation
std::vector<DirectedEdge*> geos::planargraph::PlanarGraph::dirEdges protected inherited
Definition at line 65 of file PlanarGraph.h.
Referenced by deleteCutEdges(), and getEdgeRings().
std::vector<Edge*> geos::planargraph::PlanarGraph::edges protected inherited
Definition at line 64 of file PlanarGraph.h.
Referenced by computeNextCCWEdges(), deleteAllEdges(), findDirEdgesInRing(), findLabeledEdgeRings(), getDegree(), and getDegreeNonDeleted().
const geom::GeometryFactory* geos::operation::polygonize::PolygonizeGraph::factory private
Definition at line 232 of file PolygonizeGraph.h.
Referenced by findEdgeRing().
std::vector<geom::CoordinateSequence *> geos::operation::polygonize::PolygonizeGraph::newCoords private
Definition at line 243 of file PolygonizeGraph.h.
Referenced by addEdge(), and ~PolygonizeGraph().
std::vector<planargraph::DirectedEdge *> geos::operation::polygonize::PolygonizeGraph::newDirEdges private
Definition at line 240 of file PolygonizeGraph.h.
Referenced by addEdge(), and ~PolygonizeGraph().
std::vector<EdgeRing *> geos::operation::polygonize::PolygonizeGraph::newEdgeRings mutable private
Definition at line 242 of file PolygonizeGraph.h.
Referenced by findEdgeRing(), and ~PolygonizeGraph().
std::vector<planargraph::Edge *> geos::operation::polygonize::PolygonizeGraph::newEdges private
Definition at line 238 of file PolygonizeGraph.h.
Referenced by addEdge(), and ~PolygonizeGraph().
std::vector<planargraph::Node *> geos::operation::polygonize::PolygonizeGraph::newNodes private
Definition at line 241 of file PolygonizeGraph.h.
Referenced by getNode(), and ~PolygonizeGraph().
NodeMap geos::planargraph::PlanarGraph::nodeMap protected inherited
Definition at line 66 of file PlanarGraph.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/polygonize/PolygonizeGraph.h
/home/vicky/potree/geos/vicky/src/operation/polygonize/PolygonizeGraph.cpp