GEOS: geos::geom::prep::PreparedPolygonContains Class Reference
geos::geom::prep::PreparedPolygonContains Class Reference
Computes the contains spatial relationship predicate for a PreparedPolygon relative to all other Geometry classes.
#include <PreparedPolygonContains.h>
Public Member Functions
PreparedPolygonContains (const PreparedPolygon *const prepPoly)
bool contains (const geom::Geometry *geom)
Static Public Member Functions
static bool contains (const PreparedPolygon *const prep, const geom::Geometry *geom)
Protected Member Functions
bool fullTopologicalPredicate (const geom::Geometry *geom) override
bool eval (const geom::Geometry *geom)
bool isAllTestComponentsInTarget (const geom::Geometry *testGeom) const
Tests whether all components of the test Geometry are contained in the target geometry.
bool isAllTestComponentsInTargetInterior (const geom::Geometry *testGeom) const
Tests whether all components of the test Geometry are contained in the interior of the target geometry.
bool isAnyTestComponentInTarget (const geom::Geometry *testGeom) const
Tests whether any component of the test Geometry intersects the area of the target geometry.
bool isAnyTestComponentInTargetInterior (const geom::Geometry *testGeom) const
Tests whether any component of the test Geometry intersects the interior of the target geometry.
bool isAnyTargetComponentInAreaTest (const geom::Geometry *testGeom, const geom::Coordinate::ConstVect *targetRepPts) const
Protected Attributes
bool requireSomePointInInterior
const PreparedPolygon *const prepPoly
Detailed Description
Computes the contains spatial relationship predicate for a PreparedPolygon relative to all other Geometry classes.
Uses short-circuit tests and indexing to improve performance.
It is not possible to short-circuit in all cases, in particular in the case where the test geometry touches the polygon linework. In this case full topology must be computed.
Author
Martin Davis
Definition at line 54 of file PreparedPolygonContains.h.
Constructor & Destructor Documentation
geos::geom::prep::PreparedPolygonContains::PreparedPolygonContains (const PreparedPolygon *const prepPoly)
Creates an instance of this operation.
Parameters
prepPoly the PreparedPolygon to evaluate
Definition at line 31 of file PreparedPolygonContains.cpp.
     : AbstractPreparedPolygonContains( prepPoly)
 {
 }
Member Function Documentation
bool geos::geom::prep::PreparedPolygonContains::contains (const geom::Geometry * geom) inline
Tests whether this PreparedPolygon contains a given geometry.
Parameters
geom the test geometry
Returns
true if the test geometry is contained
Definition at line 71 of file PreparedPolygonContains.h.
Referenced by geos::geom::prep::PreparedPolygon::contains(), and contains().
   {
     return eval(geom);
   }
static bool geos::geom::prep::PreparedPolygonContains::contains (const PreparedPolygon *const prep, const geom::Geometry * geom) inline static
Computes the contains predicate between a PreparedPolygon and a Geometry.
Parameters
prep the prepared polygon
geom a test geometry
Returns
true if the polygon contains the geometry
Definition at line 84 of file PreparedPolygonContains.h.
References contains().
   {
     PreparedPolygonContains polyInt(prep);
     return polyInt.contains(geom);
   }
bool geos::geom::prep::AbstractPreparedPolygonContains::eval (const geom::Geometry * geom) protected inherited
Evaluate the contains or covers relationship for the given geometry.
Parameters
geom the test geometry
Returns
true if the test geometry is contained
Definition at line 108 of file AbstractPreparedPolygonContains.cpp.
References geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections(), geos::geom::prep::AbstractPreparedPolygonContains::fullTopologicalPredicate(), geos::geom::GEOS_MULTIPOLYGON, geos::geom::GEOS_POLYGON, geos::geom::Geometry::getDimension(), geos::geom::Geometry::getGeometryTypeId(), geos::geom::prep::BasicPreparedGeometry::getRepresentativePoints(), geos::geom::prep::AbstractPreparedPolygonContains::hasNonProperIntersection, geos::geom::prep::AbstractPreparedPolygonContains::hasProperIntersection, geos::geom::prep::AbstractPreparedPolygonContains::hasSegmentIntersection, geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTarget(), geos::geom::prep::PreparedPolygonPredicate::isAnyTargetComponentInAreaTest(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTargetInterior(), geos::geom::prep::AbstractPreparedPolygonContains::isProperIntersectionImpliesNotContainedSituation(), geos::geom::prep::PreparedPolygonPredicate::prepPoly, and geos::geom::prep::AbstractPreparedPolygonContains::requireSomePointInInterior.
 {
   // Do point-in-poly tests first, since they are cheaper and may result
   // in a quick negative result.
   //
   // If a point of any test components does not lie in target,
   // result is false
   bool isAllInTargetArea = isAllTestComponentsInTarget( geom);
   if ( !isAllInTargetArea )
     return false;
   // If the test geometry consists of only Points,
   // then it is now sufficient to test if any of those
   // points lie in the interior of the target geometry.
   // If so, the test is contained.
   // If not, all points are on the boundary of the area,
   // which implies not contained.
   if ( requireSomePointInInterior && geom->getDimension() == 0 )
   {
     bool isAnyInTargetInterior = isAnyTestComponentInTargetInterior( geom);
     return isAnyInTargetInterior;
   }
   // Check if there is any intersection between the line segments
   // in target and test.
   // In some important cases, finding a proper interesection implies that the
   // test geometry is NOT contained.
   // These cases are:
   // - If the test geometry is polygonal
   // - If the target geometry is a single polygon with no holes
   // In both of these cases, a proper intersection implies that there
   // is some portion of the interior of the test geometry lying outside
   // the target, which means that the test is not contained.
   bool properIntersectionImpliesNotContained = isProperIntersectionImpliesNotContainedSituation( geom);
     // find all intersection types which exist
     findAndClassifyIntersections( geom);
   if ( properIntersectionImpliesNotContained && hasProperIntersection )
     return false;
   // If all intersections are proper
   // (i.e. no non-proper intersections occur)
   // we can conclude that the test geometry is not contained in the target area,
   // by the Epsilon-Neighbourhood Exterior Intersection condition.
   // In real-world data this is likely to be by far the most common situation,
   // since natural data is unlikely to have many exact vertex segment intersections.
   // Thus this check is very worthwhile, since it avoid having to perform
   // a full topological check.
   //
   // (If non-proper (vertex) intersections ARE found, this may indicate
   // a situation where two shells touch at a single vertex, which admits
   // the case where a line could cross between the shells and still be wholely contained in them.
   if ( hasSegmentIntersection && !hasNonProperIntersection )
     return false;
   // If there is a segment intersection and the situation is not one
   // of the ones above, the only choice is to compute the full topological
   // relationship.  This is because contains/covers is very sensitive
   // to the situation along the boundary of the target.
   if ( hasSegmentIntersection )
     return fullTopologicalPredicate( geom);
   // This tests for the case where a ring of the target lies inside
   // a test polygon - which implies the exterior of the Target
   // intersects the interior of the Test, and hence the result is false
   if (  geom->getGeometryTypeId() == geos::geom::GEOS_MULTIPOLYGON
     ||  geom->getGeometryTypeId() == geos::geom::GEOS_POLYGON )
   {
     // TODO: generalize this to handle GeometryCollections
     bool isTargetInTestArea = isAnyTargetComponentInAreaTest( geom, prepPoly->getRepresentativePoints());
     if ( isTargetInTestArea )
       return false;
   }
   return true;
 }
bool geos::geom::prep::PreparedPolygonContains::fullTopologicalPredicate (const geom::Geometry * geom) override protected virtual
Computes the full topological contains predicate. Used when short-circuit tests are not conclusive.
Parameters
geom the test geometry
Returns
true if this prepared polygon contains the test geometry
Implements geos::geom::prep::AbstractPreparedPolygonContains.
Definition at line 40 of file PreparedPolygonContains.cpp.
References geos::geom::Geometry::contains(), geos::geom::prep::BasicPreparedGeometry::getGeometry(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
 {
   bool isContained = prepPoly->getGeometry().contains( geom);
   return isContained;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTarget (const geom::Geometry * testGeom) const protected inherited
Tests whether all components of the test Geometry are contained in the target geometry.
Handles both linear and point components.
Parameters
geom a geometry to test
Returns
true if all components of the argument are contained in the target geometry
Definition at line 41 of file PreparedPolygonPredicate.cpp.
References geos::geom::Location::EXTERIOR, geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::algorithm::locate::PointOnGeometryLocator::locate(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::eval().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const geom::Coordinate* pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::EXTERIOR == loc)
         {
             return false;
         }
     }
     return true;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTargetInterior (const geom::Geometry * testGeom) const protected inherited
Tests whether all components of the test Geometry are contained in the interior of the target geometry.
Handles both linear and point components.
Parameters
geom a geometry to test
Returns
true if all componenta of the argument are contained in the target geometry interior
Definition at line 59 of file PreparedPolygonPredicate.cpp.
References geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::geom::Location::INTERIOR, geos::algorithm::locate::PointOnGeometryLocator::locate(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const geom::Coordinate * pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::INTERIOR != loc)
         {
             return false;
         }
     }
     return true;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAnyTargetComponentInAreaTest (const geom::Geometry * testGeom, const geom::Coordinate::ConstVect * targetRepPts) const protected inherited
Tests whether any component of the target geometry intersects the test geometry (which must be an areal geometry)
Parameters
geom the test geometry
repPts the representative points of the target geometry
Returns
true if any component intersects the areal test geometry
Definition at line 116 of file PreparedPolygonPredicate.cpp.
References geos::geom::Location::EXTERIOR, and geos::algorithm::locate::SimplePointInAreaLocator::locate().
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), and geos::geom::prep::PreparedPolygonIntersects::intersects().
 {
     algorithm::locate::SimplePointInAreaLocator piaLoc(testGeom);
     for (std::size_t i = 0, ni = targetRepPts->size(); i < ni; i++)
     {
         const geom::Coordinate * pt = (*targetRepPts)[i];
         const int loc = piaLoc.locate(pt);
         if (geom::Location::EXTERIOR != loc)
         {
             return true;
         }
     }
     return false;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTarget (const geom::Geometry * testGeom) const protected inherited
Tests whether any component of the test Geometry intersects the area of the target geometry.
Handles test geometries with both linear and point components.
Parameters
geom a geometry to test
Returns
true if any component of the argument intersects the prepared geometry
Definition at line 78 of file PreparedPolygonPredicate.cpp.
References geos::geom::Location::EXTERIOR, geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::algorithm::locate::PointOnGeometryLocator::locate(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
Referenced by geos::geom::prep::PreparedPolygonIntersects::intersects().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const Coordinate* pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::EXTERIOR != loc)
         {
             return true;
         }
     }
     return false;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTargetInterior (const geom::Geometry * testGeom) const protected inherited
Tests whether any component of the test Geometry intersects the interior of the target geometry.
Handles test geometries with both linear and point components.
Parameters
geom a geometry to test
Returns
true if any component of the argument intersects the prepared area geometry interior
Definition at line 97 of file PreparedPolygonPredicate.cpp.
References geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::geom::Location::INTERIOR, geos::algorithm::locate::PointOnGeometryLocator::locate(), and geos::geom::prep::PreparedPolygonPredicate::prepPoly.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::eval().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const Coordinate * pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::INTERIOR == loc)
         {
             return true;
         }
     }
     return false;
 }
Member Data Documentation
const PreparedPolygon* const geos::geom::prep::PreparedPolygonPredicate::prepPoly protected inherited
Definition at line 65 of file PreparedPolygonPredicate.h.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections(), geos::geom::prep::PreparedPolygonCovers::fullTopologicalPredicate(), fullTopologicalPredicate(), geos::geom::prep::PreparedPolygonIntersects::intersects(), geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTarget(), geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTargetInterior(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTarget(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTargetInterior(), and geos::geom::prep::AbstractPreparedPolygonContains::isProperIntersectionImpliesNotContainedSituation().
bool geos::geom::prep::AbstractPreparedPolygonContains::requireSomePointInInterior protected inherited
This flag controls a difference between contains and covers.
For contains the value is true. For covers the value is false.
Definition at line 91 of file AbstractPreparedPolygonContains.h.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::eval().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/prep/PreparedPolygonContains.h
/home/vicky/potree/geos/vicky/src/geom/prep/PreparedPolygonContains.cpp