GEOS: geos::geomgraph::GraphComponent Class Reference
geos::geomgraph::GraphComponent Class Reference abstract
A GraphComponent is the parent class for the objects' that form a graph.
#include <GraphComponent.h>
Public Member Functions
GraphComponent ()
GraphComponent (const Label &newLabel)
virtual ~GraphComponent ()
Label & getLabel ()
const Label & getLabel () const
void setLabel (const Label &newLabel)
virtual void setInResult (bool isInResult)
virtual bool isInResult () const
virtual void setCovered (bool isCovered)
virtual bool isCovered () const
virtual bool isCoveredSet () const
virtual bool isVisited () const
virtual void setVisited (bool isVisited)
virtual bool isIsolated () const =0
virtual void updateIM (geom::IntersectionMatrix &im)
Protected Member Functions
virtual void computeIM (geom::IntersectionMatrix &im)=0
Protected Attributes
Label label
Private Attributes
bool isInResultVar
bool isCoveredVar
bool isCoveredSetVar
bool isVisitedVar
Detailed Description
A GraphComponent is the parent class for the objects' that form a graph.
Each GraphComponent can carry a Label.
Definition at line 47 of file GraphComponent.h.
Constructor & Destructor Documentation
geos::geomgraph::GraphComponent::GraphComponent ()
Definition at line 31 of file GraphComponent.cpp.
   :
   label(),
   isInResultVar(false),
   isCoveredVar(false),
   isCoveredSetVar(false),
   isVisitedVar(false)
 {
 }
geos::geomgraph::GraphComponent::GraphComponent (const Label & newLabel)
Definition at line 41 of file GraphComponent.cpp.
                                                    :
   label(newLabel),
   isInResultVar(false),
   isCoveredVar(false),
   isCoveredSetVar(false),
   isVisitedVar(false)
 {
 }
geos::geomgraph::GraphComponent::~GraphComponent () virtual
Definition at line 50 of file GraphComponent.cpp.
 {
 }
Member Function Documentation
virtual void geos::geomgraph::GraphComponent::computeIM (geom::IntersectionMatrix & im) protected pure virtual
Implemented in geos::geomgraph::Edge, geos::geomgraph::Node, and geos::operation::relate::RelateNode.
Referenced by updateIM().
Label& geos::geomgraph::GraphComponent::getLabel () inline
Definition at line 57 of file GraphComponent.h.
Referenced by geos::geomgraph::GeometryGraph::addSelfIntersectionNodes(), geos::geomgraph::DirectedEdge::computeDirectedLabel(), geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), geos::geomgraph::DirectedEdgeStar::computeLabelling(), geos::operation::relate::RelateNodeGraph::copyNodesAndLabels(), geos::operation::relate::RelateComputer::copyNodesAndLabels(), geos::operation::overlay::OverlayOp::copyPoints(), geos::operation::relate::EdgeEndBuilder::createEdgeEndForNext(), geos::operation::relate::EdgeEndBuilder::createEdgeEndForPrev(), geos::geomgraph::EdgeIntersectionList::createSplitEdge(), geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes(), geos::geomgraph::NodeMap::getBoundaryNodes(), geos::geomgraph::GeometryGraph::insertBoundaryPoint(), geos::geomgraph::GeometryGraph::insertPoint(), geos::operation::overlay::OverlayOp::insertUniqueEdge(), geos::operation::buffer::BufferBuilder::insertUniqueEdge(), geos::geomgraph::PlanarGraph::isBoundaryNode(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), geos::operation::overlay::OverlayOp::labelIncompleteNodes(), geos::operation::relate::RelateComputer::labelIntersectionNodes(), geos::operation::relate::RelateComputer::labelIsolatedEdge(), geos::operation::overlay::LineBuilder::labelIsolatedLine(), geos::operation::overlay::LineBuilder::labelIsolatedLines(), geos::operation::relate::RelateComputer::labelIsolatedNode(), geos::operation::relate::RelateComputer::labelIsolatedNodes(), and geos::operation::overlay::OverlayOp::updateNodeLabelling().
 { return label; }
const Label& geos::geomgraph::GraphComponent::getLabel () const inline
Definition at line 58 of file GraphComponent.h.
 { return label; }
virtual bool geos::geomgraph::GraphComponent::isCovered () const inline virtual
Definition at line 64 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::collectLineEdge(), and setCovered().
 { return isCoveredVar; }
virtual bool geos::geomgraph::GraphComponent::isCoveredSet () const inline virtual
Definition at line 65 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::findCoveredLineEdges().
 { return isCoveredSetVar; }
virtual bool geos::geomgraph::GraphComponent::isInResult () const inline virtual
Definition at line 62 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes(), and geos::geomgraph::Node::isIncidentEdgeInResult().
 { return isInResultVar; }
virtual bool geos::geomgraph::GraphComponent::isIsolated () const pure virtual
Implemented in geos::geomgraph::Edge, and geos::geomgraph::Node.
virtual bool geos::geomgraph::GraphComponent::isVisited () const inline virtual
Definition at line 66 of file GraphComponent.h.
Referenced by geos::operation::buffer::BufferSubgraph::add(), and geos::operation::buffer::BufferBuilder::createSubgraphs().
 { return isVisitedVar; }
void geos::geomgraph::GraphComponent::setCovered (bool isCovered) virtual
Definition at line 55 of file GraphComponent.cpp.
References isCovered(), isCoveredSetVar, and isCoveredVar.
Referenced by geos::operation::overlay::LineBuilder::findCoveredLineEdges(), and geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges().
 {
   isCoveredVar = isCovered;
   isCoveredSetVar = true;
 }
virtual void geos::geomgraph::GraphComponent::setInResult (bool isInResult) inline virtual
Definition at line 61 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::buildLines(), and geos::geomgraph::EdgeRing::setInResult().
 { isInResultVar=isInResult; }
void geos::geomgraph::GraphComponent::setLabel (const Label & newLabel) inline
Definition at line 59 of file GraphComponent.h.
 { label = newLabel; }
virtual void geos::geomgraph::GraphComponent::setVisited (bool isVisited) inline virtual
Definition at line 67 of file GraphComponent.h.
Referenced by geos::operation::buffer::BufferSubgraph::add().
 { isVisitedVar = isVisited; }
void geos::geomgraph::GraphComponent::updateIM (geom::IntersectionMatrix & im) virtual
Definition at line 62 of file GraphComponent.cpp.
References computeIM(), geos::geomgraph::Label::getGeometryCount(), and label.
Referenced by geos::operation::relate::RelateComputer::updateIM().
 {
   assert(label.getGeometryCount() >= 2); // found partial label
   computeIM(im);
 }
Member Data Documentation
bool geos::geomgraph::GraphComponent::isCoveredSetVar private
Definition at line 76 of file GraphComponent.h.
Referenced by setCovered().
bool geos::geomgraph::GraphComponent::isCoveredVar private
Definition at line 75 of file GraphComponent.h.
Referenced by setCovered().
bool geos::geomgraph::GraphComponent::isInResultVar private
Definition at line 74 of file GraphComponent.h.
bool geos::geomgraph::GraphComponent::isVisitedVar private
Definition at line 77 of file GraphComponent.h.
Label geos::geomgraph::GraphComponent::label protected
Definition at line 71 of file GraphComponent.h.
Referenced by geos::operation::relate::RelateNode::computeIM(), geos::geomgraph::Node::computeMergedLocation(), geos::geomgraph::Edge::getCollapsedEdge(), geos::geomgraph::Edge::isCollapsed(), geos::geomgraph::Node::isIsolated(), geos::geomgraph::Node::mergeLabel(), geos::geomgraph::operator<<(), geos::geomgraph::Edge::printReverse(), geos::geomgraph::Node::setLabel(), geos::geomgraph::Node::setLabelBoundary(), and updateIM().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/GraphComponent.h
/home/vicky/potree/geos/vicky/src/geomgraph/GraphComponent.cpp