GEOS: geos::geom::Envelope Class Reference
geos::geom::Envelope Class Reference
An Envelope defines a rectangulare region of the 2D coordinate plane.
#include <geos.h>
Public Types
typedef std::unique_ptr< Envelope > Ptr
Public Member Functions
Envelope (void)
Creates a null Envelope.
Envelope (double x1, double x2, double y1, double y2)
Creates an Envelope for a region defined by maximum and minimum values.
Envelope (const Coordinate &p1, const Coordinate &p2)
Creates an Envelope for a region defined by two Coordinates.
Envelope (const Coordinate &p)
Creates an Envelope for a region defined by a single Coordinate.
Envelope (const Envelope &env)
Copy constructor.
Envelope & operator= (const Envelope &e)
Assignment operator.
Envelope (const std::string &str)
Create an Envelope from an Envelope string representation produced by Envelope.toString()
~Envelope (void)
void init (void)
Initialize to a null Envelope.
void init (double x1, double x2, double y1, double y2)
Initialize an Envelope for a region defined by maximum and minimum values.
void init (const Coordinate &p1, const Coordinate &p2)
Initialize an Envelope to a region defined by two Coordinates.
void init (const Coordinate &p)
Initialize an Envelope to a region defined by a single Coordinate.
void setToNull (void)
Makes this Envelope a "null" envelope, that is, the envelope of the empty geometry.
bool isNull (void) const
Returns true if this Envelope is a "null" envelope.
double getWidth (void) const
Returns the difference between the maximum and minimum x values.
double getHeight (void) const
Returns the difference between the maximum and minimum y values.
double getArea () const
double getMaxY () const
double getMaxX () const
double getMinY () const
double getMinX () const
bool centre (Coordinate &centre) const
bool intersection (const Envelope &env, Envelope &result) const
void translate (double transX, double transY)
Translates this envelope by given amounts in the X and Y direction.
void expandBy (double deltaX, double deltaY)
Expands this envelope by a given distance in all directions. Both positive and negative distances are supported.
void expandBy (double distance)
Expands this envelope by a given distance in all directions. Both positive and negative distances are supported.
void expandToInclude (const Coordinate &p)
Enlarges the boundary of the Envelope so that it contains p. Does nothing if p is already on or within the boundaries.
void expandToInclude (double x, double y)
Enlarges the boundary of the Envelope so that it contains (x,y). Does nothing if (x,y) is already on or within the boundaries.
void expandToInclude (const Envelope *other)
Enlarges the boundary of the Envelope so that it contains other. Does nothing if other is wholly on or within the boundaries.
bool contains (const Envelope &other) const
Tests if the Envelope other lies wholely inside this Envelope (inclusive of the boundary).
bool contains (const Envelope *other) const
bool contains (const Coordinate &p) const
Returns true if the given point lies in or on the envelope.
bool contains (double x, double y) const
Returns true if the given point lies in or on the envelope.
bool intersects (const Coordinate &p) const
bool intersects (double x, double y) const
bool intersects (const Envelope *other) const
bool intersects (const Envelope &other) const
bool covers (double x, double y) const
bool covers (const Coordinate *p) const
bool covers (const Envelope &other) const
bool covers (const Envelope *other) const
bool equals (const Envelope *other) const
Returns true if the Envelope other spatially equals this Envelope.
std::string toString (void) const
Returns a string of the form Env[minx:maxx,miny:maxy] .
double distance (const Envelope *env) const
Computes the distance between this and another Envelope.
int hashCode () const
Static Public Member Functions
static bool intersects (const Coordinate &p1, const Coordinate &p2, const Coordinate &q)
Test the point q to see whether it intersects the Envelope defined by p1-p2.
static bool intersects (const Coordinate &p1, const Coordinate &p2, const Coordinate &q1, const Coordinate &q2)
Test the envelope defined by p1-p2 for intersection with the envelope defined by q1-q2.
Private Member Functions
std::vector< std::string > split (const std::string &str, const std::string &delimiters=" ")
Splits a string into parts based on the supplied delimiters.
Static Private Member Functions
static double distance (double x0, double y0, double x1, double y1)
Private Attributes
double minx
the minimum x-coordinate
double maxx
the maximum x-coordinate
double miny
the minimum y-coordinate
double maxy
the maximum y-coordinate
Friends
std::ostream & operator<< (std::ostream &os, const Envelope &o)
Output operator.
Detailed Description
An Envelope defines a rectangulare region of the 2D coordinate plane.
It is often used to represent the bounding box of a Geometry, e.g. the minimum and maximum x and y values of the Coordinates.
Note that Envelopes support infinite or half-infinite regions, by using the values of Double_POSITIVE_INFINITY and Double_NEGATIVE_INFINITY.
When Envelope objects are created or initialized, the supplies extent values are automatically sorted into the correct order.
Definition at line 59 of file Envelope.h.
Member Typedef Documentation
typedef std::unique_ptr<Envelope> geos::geom::Envelope::Ptr
Definition at line 65 of file Envelope.h.
Constructor & Destructor Documentation
geos::geom::Envelope::Envelope (void)
Creates a null Envelope.
Definition at line 92 of file Envelope.cpp.
Referenced by Envelope().
 {
   init();
 }
geos::geom::Envelope::Envelope (double x1, double x2, double y1, double y2)
Creates an Envelope for a region defined by maximum and minimum values.
Parameters
x1 the first x-value
x2 the second x-value
y1 the first y-value
y2 the second y-value
Definition at line 98 of file Envelope.cpp.
 {
   init(x1, x2, y1, y2);
 }
geos::geom::Envelope::Envelope (const Coordinate & p1, const Coordinate & p2)
Creates an Envelope for a region defined by two Coordinates.
Parameters
p1 the first Coordinate
p2 the second Coordinate
Definition at line 104 of file Envelope.cpp.
 {
   init(p1, p2);
 }
geos::geom::Envelope::Envelope (const Coordinate & p)
Creates an Envelope for a region defined by a single Coordinate.
Parameters
p the Coordinate
Definition at line 110 of file Envelope.cpp.
 {
   init(p);
 }
geos::geom::Envelope::Envelope (const Envelope & env)
Copy constructor.
Definition at line 116 of file Envelope.cpp.
References Envelope(), init(), and split().
   :
   minx(env.minx),
   maxx(env.maxx),
   miny(env.miny),
   maxy(env.maxy)
 {
 #if GEOS_DEBUG
   std::cerr<<"Envelope copy"<<std::endl;
 #endif
   //init(env.minx, env.maxx, env.miny, env.maxy);
 }
geos::geom::Envelope::Envelope (const std::string & str)
Create an Envelope from an Envelope string representation produced by Envelope.toString()
geos::geom::Envelope::~Envelope (void)
Definition at line 150 of file Envelope.cpp.
 {}
Member Function Documentation
bool geos::geom::Envelope::centre (Coordinate & centre) const
Computes the coordinate of the centre of this envelope (as long as it is non-null)
Parameters
centre The coordinate to write results into
Returns
NULL is the center could not be found (null envelope).
Definition at line 426 of file Envelope.cpp.
References getMaxX(), getMaxY(), getMinX(), getMinY(), isNull(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   if (isNull()) return false;
   centre.x=(getMinX() + getMaxX()) / 2.0;
   centre.y=(getMinY() + getMaxY()) / 2.0;
   return true;
 }
bool geos::geom::Envelope::contains (const Envelope & other) const inline
Tests if the Envelope other lies wholely inside this Envelope (inclusive of the boundary).
Note that this is not the same definition as the SFS contains, which would exclude the envelope boundary.
Parameters
other the Envelope to check
Returns
true if other is contained in this Envelope
See also
covers(Envelope)
Definition at line 331 of file Envelope.h.
Referenced by geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), geos::index::quadtree::Key::computeKey(), geos::geomgraph::EdgeRing::containsPoint(), geos::geom::prep::BasicPreparedGeometry::containsProperly(), geos::operation::polygonize::EdgeRing::findEdgeRingContaining(), geos::operation::overlay::PolygonBuilder::findEdgeRingContaining(), geos::index::quadtree::Root::insert(), geos::index::quadtree::Root::insertContained(), geos::algorithm::LineIntersector::isInSegmentEnvelopes(), geos::operation::predicate::EnvelopeIntersectsVisitor::visit(), and geos::operation::predicate::ContainsPointVisitor::visit().
{
     return covers(other);
   }
bool geos::geom::Envelope::contains (const Envelope * other) const inline
Definition at line 335 of file Envelope.h.
{
     return contains(*other);
   }
bool geos::geom::Envelope::contains (const Coordinate & p) const inline
Returns true if the given point lies in or on the envelope.
Parameters
p the point which this Envelope is being checked for containing
Returns
true if the point lies in the interior or on the boundary of this Envelope.
Definition at line 348 of file Envelope.h.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
{
     return covers(p.x, p.y);
   }
bool geos::geom::Envelope::contains (double x, double y) const inline
Returns true if the given point lies in or on the envelope.
Parameters
x the x-coordinate of the point which this Envelope is being checked for containing
y the y-coordinate of the point which this Envelope is being checked for containing
Returns
true if (x, y) lies in the interior or on the boundary of this Envelope.
Definition at line 367 of file Envelope.h.
{
     return covers(x, y);
   }
bool geos::geom::Envelope::covers (double x, double y) const
Tests if the given point lies in or on the envelope.
Parameters
x the x-coordinate of the point which this Envelope is being checked for containing
y the y-coordinate of the point which this Envelope is being checked for containing
Returns
true if (x, y) lies in the interior or on the boundary of this Envelope.
Definition at line 298 of file Envelope.cpp.
References isNull(), maxx, maxy, minx, and miny.
Referenced by geos::geomgraph::GeometryGraph::computeEdgeIntersections(), geos::geomgraph::GeometryGraph::computeSelfNodes(), geos::operation::overlay::OverlayOp::copyPoints(), covers(), and geos::geom::prep::BasicPreparedGeometry::envelopeCovers().
 {
   if (isNull()) return false;
   return x >= minx &&
     x <= maxx &&
     y >= miny &&
     y <= maxy;
 }
INLINE bool geos::geom::Envelope::covers (const Coordinate * p) const
Tests if the given point lies in or on the envelope.
Parameters
p the point which this Envelope is being checked for containing
Returns
true if the point lies in the interior or on the boundary of this Envelope.
Definition at line 89 of file Envelope.inl.
References covers(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   return covers(p->x, p->y);
 }
bool geos::geom::Envelope::covers (const Envelope & other) const
Tests if the Envelope other lies wholely inside this Envelope (inclusive of the boundary).
Parameters
other the Envelope to check
Returns
true if this Envelope covers the other
Definition at line 310 of file Envelope.cpp.
References getMaxX(), getMaxY(), getMinX(), getMinY(), isNull(), maxx, maxy, minx, and miny.
 {
   if (isNull() || other.isNull()) return false;
   return
     other.getMinX() >= minx &&
     other.getMaxX() <= maxx &&
     other.getMinY() >= miny &&
     other.getMaxY() <= maxy;
 }
bool geos::geom::Envelope::covers (const Envelope * other) const inline
Definition at line 435 of file Envelope.h.
References geos::operation::intersection::distance().
{
     return covers(*other);
   }
double geos::geom::Envelope::distance (const Envelope * env) const
Computes the distance between this and another Envelope.
The distance between overlapping Envelopes is 0. Otherwise, the distance is the Euclidean distance between the closest points.
Definition at line 355 of file Envelope.cpp.
References intersects(), maxx, maxy, minx, and miny.
Referenced by geos::operation::distance::DistanceOp::computeMinDistance(), geos::index::strtree::BoundablePair::distance(), and geos::geom::Geometry::isWithinDistance().
 {
   if (intersects(env)) return 0;
   double dx=0.0;
   if(maxx<env->minx) dx=env->minx-maxx;
   if(minx>env->maxx) dx=minx-env->maxx;
   double dy=0.0;
   if(maxy<env->miny) dy=env->miny-maxy;
   if(miny>env->maxy) dy=miny-env->maxy;
   // if either is zero, the envelopes overlap either vertically or horizontally
   if (dx==0.0) return dy;
   if (dy==0.0) return dx;
   return sqrt(dx*dx+dy*dy);
 }
double geos::geom::Envelope::distance (double x0, double y0, double x1, double y1) static private
Definition at line 84 of file Envelope.cpp.
 {
   double dx=x1-x0;
   double dy=y1-y0;
   return sqrt(dx*dx+dy*dy);
 }
bool geos::geom::Envelope::equals (const Envelope * other) const
Returns true if the Envelope other spatially equals this Envelope.
Parameters
other the Envelope which this Envelope is being checked for equality
Returns
true if this and other Envelope objs are spatially equal
Definition at line 326 of file Envelope.cpp.
References getMaxX(), getMaxY(), getMinX(), getMinY(), isNull(), maxx, maxy, minx, and miny.
Referenced by geos::operation::polygonize::EdgeRing::findEdgeRingContaining().
 {
   if (isNull()) return other->isNull();
   return  other->getMinX() == minx &&
       other->getMaxX() == maxx &&
       other->getMinY() == miny &&
       other->getMaxY() == maxy;
 }
void geos::geom::Envelope::expandBy (double deltaX, double deltaY)
Expands this envelope by a given distance in all directions. Both positive and negative distances are supported.
Parameters
deltaX the distance to expand the envelope along the X axis
deltaY the distance to expand the envelope along the Y axis
Definition at line 460 of file Envelope.cpp.
References isNull(), maxx, maxy, minx, miny, and setToNull().
Referenced by geos::triangulate::VoronoiDiagramBuilder::create().
 {
   if (isNull()) return;
   minx -= deltaX;
   maxx += deltaX;
   miny -= deltaY;
   maxy += deltaY;
   // check for envelope disappearing
   if (minx > maxx || miny > maxy)
     setToNull();
 }
void geos::geom::Envelope::expandBy (double distance) inline
Expands this envelope by a given distance in all directions. Both positive and negative distances are supported.
Parameters
distance the distance to expand the envelope
Returns
this envelope
Definition at line 287 of file Envelope.h.
References expandBy().
Referenced by expandBy().
 { expandBy(distance, distance); }
void geos::geom::Envelope::expandToInclude (const Coordinate & p)
Enlarges the boundary of the Envelope so that it contains p. Does nothing if p is already on or within the boundaries.
Parameters
p the Coordinate to include
Definition at line 238 of file Envelope.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::operation::valid::QuadtreeNestedRingTester::add(), geos::index::strtree::STRAbstractNode::computeBounds(), geos::operation::distance::FacetSequence::computeEnvelope(), geos::geom::GeometryCollection::computeEnvelopeInternal(), geos::triangulate::VoronoiDiagramBuilder::create(), geos::index::quadtree::Node::createExpanded(), geos::triangulate::DelaunayTriangulationBuilder::envelope(), geos::geom::CoordinateArraySequence::expandEnvelope(), geos::geom::CoordinateSequence::expandEnvelope(), geos::operation::buffer::BufferSubgraph::getEnvelope(), geos::geomgraph::Edge::getEnvelope(), and geos::operation::overlay::OverlayOp::OverlayOp().
 {
   expandToInclude(p.x, p.y);
 }
void geos::geom::Envelope::expandToInclude (double x, double y)
Enlarges the boundary of the Envelope so that it contains (x,y). Does nothing if (x,y) is already on or within the boundaries.
Parameters
x the value to lower the minimum x to or to raise the maximum x to
y the value to lower the minimum y to or to raise the maximum y to
Definition at line 245 of file Envelope.cpp.
References isNull(), maxx, maxy, minx, and miny.
 {
   if (isNull()) {
     minx = x;
     maxx = x;
     miny = y;
     maxy = y;
   } else {
     if (x < minx) {
       minx = x;
     }
     if (x > maxx) {
       maxx = x;
     }
     if (y < miny) {
       miny = y;
     }
     if (y > maxy) {
       maxy = y;
     }
   }
 }
void geos::geom::Envelope::expandToInclude (const Envelope * other)
Enlarges the boundary of the Envelope so that it contains other. Does nothing if other is wholly on or within the boundaries.
Parameters
other the Envelope to merge with
Definition at line 270 of file Envelope.cpp.
References getMaxX(), getMaxY(), getMinX(), getMinY(), isNull(), maxx, maxy, minx, and miny.
 {
   if (other->isNull()) {
     return;
   }
   if (isNull()) {
     minx = other->getMinX();
     maxx = other->getMaxX();
     miny = other->getMinY();
     maxy = other->getMaxY();
   } else {
     if (other->minx < minx) {
       minx = other->minx;
     }
     if (other->maxx > maxx) {
       maxx = other->maxx;
     }
     if (other->miny < miny) {
       miny = other->miny;
     }
     if (other->maxy > maxy) {
       maxy = other->maxy;
     }
   }
 }
double geos::geom::Envelope::getArea () const inline
Gets the area of this envelope.
Returns
the area of the envelope
0.0 if the envelope is null
Definition at line 211 of file Envelope.h.
   {
     return getWidth() * getHeight();
   }
double geos::geom::Envelope::getHeight (void) const
Returns the difference between the maximum and minimum y values.
Returns
max y - min y, or 0 if this is a null Envelope
Definition at line 228 of file Envelope.cpp.
References isNull(), maxy, and miny.
Referenced by geos::index::quadtree::Quadtree::collectStats(), geos::index::quadtree::Key::computeQuadLevel(), geos::operation::overlay::snap::GeometrySnapper::computeSizeBasedSnapTolerance(), geos::triangulate::VoronoiDiagramBuilder::create(), geos::triangulate::quadedge::QuadEdgeSubdivision::createFrame(), geos::operation::overlay::ElevationMatrix::ElevationMatrix(), and geos::operation::buffer::OffsetCurveSetBuilder::isErodedCompletely().
 {
   if (isNull()) {
     return 0;
   }
   return maxy - miny;
 }
INLINE double geos::geom::Envelope::getMaxX () const
Returns the Envelope maximum x-value. min x > max x indicates that this is a null Envelope.
Definition at line 35 of file Envelope.inl.
References INLINE, and maxx.
Referenced by geos::operation::valid::SweeplineNestedRingTester::buildIndex(), centre(), covers(), geos::triangulate::quadedge::QuadEdgeSubdivision::createFrame(), geos::index::quadtree::Quadtree::ensureExtent(), equals(), expandToInclude(), geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments(), GEOSGeom_getXMax_r(), geos::index::quadtree::Key::getCentre(), geos::index::quadtree::NodeBase::getSubnodeIndex(), geos::algorithm::InteriorPointArea::horizontalBisector(), geos::index::quadtree::Root::insertContained(), geos::geom::Geometry::intersection(), geos::geom::Polygon::isRectangle(), geos::geom::operator==(), geos::operation::buffer::BufferOp::precisionScaleFactor(), geos::geom::GeometryFactory::toGeometry(), translate(), and geos::operation::predicate::EnvelopeIntersectsVisitor::visit().
 { return maxx; }
INLINE double geos::geom::Envelope::getMaxY () const
Returns the Envelope maximum y-value. min y > max y indicates that this is a null Envelope.
Definition at line 31 of file Envelope.inl.
References INLINE, and maxy.
Referenced by geos::algorithm::MCPointInRing::buildIndex(), centre(), geos::index::strtree::STRtree::centreY(), covers(), geos::index::quadtree::Quadtree::ensureExtent(), equals(), expandToInclude(), geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments(), GEOSGeom_getYMax_r(), geos::index::quadtree::Key::getCentre(), geos::index::quadtree::NodeBase::getSubnodeIndex(), geos::index::quadtree::Root::insertContained(), geos::geom::Geometry::intersection(), geos::geom::Polygon::isRectangle(), geos::geom::operator==(), geos::operation::buffer::BufferOp::precisionScaleFactor(), geos::geom::GeometryFactory::toGeometry(), translate(), and geos::operation::predicate::EnvelopeIntersectsVisitor::visit().
 { return maxy; }
INLINE double geos::geom::Envelope::getMinX () const
Returns the Envelope minimum x-value. min x > max x indicates that this is a null Envelope.
Definition at line 43 of file Envelope.inl.
References INLINE, and minx.
Referenced by geos::operation::valid::SweeplineNestedRingTester::buildIndex(), centre(), geos::index::quadtree::Key::computeKey(), covers(), geos::triangulate::quadedge::QuadEdgeSubdivision::createFrame(), geos::index::quadtree::Quadtree::ensureExtent(), equals(), expandToInclude(), geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments(), GEOSGeom_getXMin_r(), geos::operation::overlay::ElevationMatrix::getCell(), geos::index::quadtree::Key::getCentre(), geos::index::quadtree::NodeBase::getSubnodeIndex(), geos::algorithm::InteriorPointArea::horizontalBisector(), geos::index::quadtree::Root::insertContained(), geos::geom::Geometry::intersection(), geos::geom::Polygon::isRectangle(), geos::geom::operator==(), geos::operation::buffer::BufferOp::precisionScaleFactor(), geos::geom::GeometryFactory::toGeometry(), translate(), and geos::operation::predicate::EnvelopeIntersectsVisitor::visit().
 { return minx; }
INLINE double geos::geom::Envelope::getMinY () const
Returns the Envelope minimum y-value. min y > max y indicates that this is a null Envelope.
Definition at line 39 of file Envelope.inl.
References INLINE, and miny.
Referenced by geos::algorithm::MCPointInRing::buildIndex(), centre(), geos::index::strtree::STRtree::centreY(), geos::index::quadtree::Key::computeKey(), covers(), geos::triangulate::quadedge::QuadEdgeSubdivision::createFrame(), geos::index::quadtree::Quadtree::ensureExtent(), equals(), expandToInclude(), geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments(), GEOSGeom_getYMin_r(), geos::operation::overlay::ElevationMatrix::getCell(), geos::index::quadtree::Key::getCentre(), geos::index::quadtree::NodeBase::getSubnodeIndex(), geos::index::quadtree::Root::insertContained(), geos::geom::Geometry::intersection(), geos::geom::Polygon::isRectangle(), geos::geom::operator==(), geos::operation::buffer::BufferOp::precisionScaleFactor(), geos::geom::GeometryFactory::toGeometry(), translate(), and geos::operation::predicate::EnvelopeIntersectsVisitor::visit().
 { return miny; }
double geos::geom::Envelope::getWidth (void) const
Returns the difference between the maximum and minimum x values.
Returns
max x - min x, or 0 if this is a null Envelope
Definition at line 218 of file Envelope.cpp.
References isNull(), maxx, and minx.
Referenced by geos::algorithm::InteriorPointArea::addPolygon(), geos::index::quadtree::Quadtree::collectStats(), geos::index::quadtree::Key::computeQuadLevel(), geos::operation::overlay::snap::GeometrySnapper::computeSizeBasedSnapTolerance(), geos::triangulate::VoronoiDiagramBuilder::create(), geos::triangulate::quadedge::QuadEdgeSubdivision::createFrame(), geos::operation::overlay::ElevationMatrix::ElevationMatrix(), and geos::operation::buffer::OffsetCurveSetBuilder::isErodedCompletely().
 {
   if (isNull()) {
     return 0;
   }
   return maxx - minx;
 }
int geos::geom::Envelope::hashCode () const
Definition at line 388 of file Envelope.cpp.
References geos::geom::Coordinate::hashCode(), maxx, maxy, minx, and miny.
 {
   //Algorithm from Effective Java by Joshua Bloch [Jon Aquino]
   int result = 17;
   result = 37 * result + Coordinate::hashCode(minx);
   result = 37 * result + Coordinate::hashCode(maxx);
   result = 37 * result + Coordinate::hashCode(miny);
   result = 37 * result + Coordinate::hashCode(maxy);
   return result;
 }
void geos::geom::Envelope::init (void)
Initialize to a null Envelope.
Definition at line 154 of file Envelope.cpp.
References setToNull().
Referenced by geos::geomgraph::index::MonotoneChainEdge::computeIntersectsForChain(), geos::index::quadtree::Key::computeKey(), geos::index::chain::MonotoneChain::computeOverlaps(), geos::index::chain::MonotoneChain::computeSelect(), Envelope(), init(), intersection(), and translate().
 {
   setToNull();
 }
void geos::geom::Envelope::init (double x1, double x2, double y1, double y2)
Initialize an Envelope for a region defined by maximum and minimum values.
Parameters
x1 the first x-value
x2 the second x-value
y1 the first y-value
y2 the second y-value
Definition at line 161 of file Envelope.cpp.
References maxx, maxy, minx, and miny.
 {
   if (x1 < x2) {
     minx = x1;
     maxx = x2;
   } else {
     minx = x2;
     maxx = x1;
   }
   if (y1 < y2) {
     miny = y1;
     maxy = y2;
   } else {
     miny = y2;
     maxy = y1;
   }
 }
void geos::geom::Envelope::init (const Coordinate & p1, const Coordinate & p2)
Initialize an Envelope to a region defined by two Coordinates.
Parameters
p1 the first Coordinate
p2 the second Coordinate
Definition at line 181 of file Envelope.cpp.
References init(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   init(p1.x, p2.x, p1.y, p2.y);
 }
void geos::geom::Envelope::init (const Coordinate & p)
Initialize an Envelope to a region defined by a single Coordinate.
Parameters
p the Coordinate
Definition at line 188 of file Envelope.cpp.
References init(), maxx, maxy, minx, miny, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   init(p.x, p.x, p.y, p.y);
 }
bool geos::geom::Envelope::intersection (const Envelope & env, Envelope & result) const
Computes the intersection of two Envelopes
Parameters
env the envelope to intersect with
result the envelope representing the intersection of the envelopes (this will be the null envelope if either argument is null, or they do not intersect)
Returns
false if not intersection is found
Definition at line 436 of file Envelope.cpp.
References init(), intersects(), isNull(), maxx, maxy, minx, and miny.
Referenced by geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::geounion::CascadedUnion::unionOptimized(), and geos::operation::geounion::CascadedPolygonUnion::unionOptimized().
 {
   if (isNull() || env.isNull() || ! intersects(env)) return false;
   double intMinX = minx > env.minx ? minx : env.minx;
   double intMinY = miny > env.miny ? miny : env.miny;
   double intMaxX = maxx < env.maxx ? maxx : env.maxx;
   double intMaxY = maxy < env.maxy ? maxy : env.maxy;
   result.init(intMinX, intMaxX, intMinY, intMaxY);
   return true;
 }
bool geos::geom::Envelope::intersects (const Coordinate & p1, const Coordinate & p2, const Coordinate & q) static
Test the point q to see whether it intersects the Envelope defined by p1-p2.
Parameters
p1 one extremal point of the envelope
p2 another extremal point of the envelope
q the point to test for intersection
Returns
true if q intersects the envelope p1-p2
Definition at line 46 of file Envelope.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), geos::geomgraph::collect_intersecting_edges(), geos::operation::relate::RelateComputer::computeIM(), geos::geomgraph::index::MonotoneChainEdge::computeIntersectsForChain(), geos::index::chain::MonotoneChain::computeOverlaps(), geos::index::chain::MonotoneChain::computeSelect(), distance(), geos::geom::prep::BasicPreparedGeometry::envelopesIntersect(), geos::operation::geounion::CascadedUnion::extractByEnvelope(), geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope(), geos::operation::predicate::SegmentIntersectionTester::hasIntersectionWithEnvelopeFilter(), geos::operation::overlay::OverlayOp::insertUniqueEdges(), intersection(), geos::operation::predicate::RectangleIntersects::intersects(), intersects(), geos::operation::valid::SweeplineNestedRingTester::isInside(), geos::operation::valid::QuadtreeNestedRingTester::isNonNested(), geos::operation::valid::IndexedNestedRingTester::isNonNested(), geos::operation::valid::SimpleNestedRingTester::isNonNested(), geos::geom::Geometry::symDifference(), geos::geom::Geometry::Union(), geos::operation::geounion::CascadedUnion::unionOptimized(), geos::operation::geounion::CascadedPolygonUnion::unionOptimized(), geos::operation::predicate::EnvelopeIntersectsVisitor::visit(), geos::operation::predicate::ContainsPointVisitor::visit(), and geos::operation::predicate::LineIntersectsVisitor::visit().
 {
   //OptimizeIt shows that Math#min and Math#max here are a bottleneck.
     //Replace with direct comparisons. [Jon Aquino]
     if (((q.x >= (p1.x < p2.x ? p1.x : p2.x)) && (q.x <= (p1.x > p2.x ? p1.x : p2.x))) &&
         ((q.y >= (p1.y < p2.y ? p1.y : p2.y)) && (q.y <= (p1.y > p2.y ? p1.y : p2.y)))) {
       return true;
   }
   return false;
 }
bool geos::geom::Envelope::intersects (const Coordinate & p1, const Coordinate & p2, const Coordinate & q1, const Coordinate & q2) static
Test the envelope defined by p1-p2 for intersection with the envelope defined by q1-q2.
Parameters
p1 one extremal point of the envelope P
p2 another extremal point of the envelope P
q1 one extremal point of the envelope Q
q2 another extremal point of the envelope Q
Returns
true if Q intersects P
Definition at line 60 of file Envelope.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   double minq=min(q1.x,q2.x);
   double maxq=max(q1.x,q2.x);
   double minp=min(p1.x,p2.x);
   double maxp=max(p1.x,p2.x);
   if(minp>maxq)
     return false;
   if(maxp<minq)
     return false;
   minq=min(q1.y,q2.y);
   maxq=max(q1.y,q2.y);
   minp=min(p1.y,p2.y);
   maxp=max(p1.y,p2.y);
   if(minp>maxq)
     return false;
   if(maxp<minq)
     return false;
   return true;
 }
INLINE bool geos::geom::Envelope::intersects (const Coordinate & p) const
Check if the point p intersects (lies inside) the region of this Envelope.
Parameters
p the Coordinate to be tested
Returns
true if the point intersects this Envelope
Definition at line 47 of file Envelope.inl.
References INLINE, maxx, maxy, minx, miny, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   return (other.x <= maxx && other.x >= minx &&
     other.y <= maxy && other.y >= miny);
 }
INLINE bool geos::geom::Envelope::intersects (double x, double y) const
Check if the point (x, y) intersects (lies inside) the region of this Envelope.
Parameters
x the x-ordinate of the point
y the y-ordinate of the point
Returns
true if the point intersects this Envelope
Definition at line 81 of file Envelope.inl.
References INLINE, minx, and miny.
 {
   return (x <= maxx && x >= minx && y <= maxy && y >= miny);
 }
INLINE bool geos::geom::Envelope::intersects (const Envelope * other) const
Check if the region defined by other Envelope intersects (intersects) the region of this Envelope.
Parameters
other the Envelope which this Envelope is being checked for intersection
Returns
true if the Envelopes intersects
Definition at line 69 of file Envelope.inl.
References INLINE, isNull(), maxx, maxy, minx, and miny.
 {
   // Optimized to reduce function calls
   if ( isNull() || other->isNull() ) return false;
   return !(other->minx > maxx ||
        other->maxx < minx ||
        other->miny > maxy ||
        other->maxy < miny);
 }
INLINE bool geos::geom::Envelope::intersects (const Envelope & other) const
Definition at line 55 of file Envelope.inl.
References INLINE, and intersects().
 {
   return intersects(&other);
 }
INLINE bool geos::geom::Envelope::isNull (void) const
Returns true if this Envelope is a "null" envelope.
Returns
true if this Envelope is uninitialized or is the envelope of the empty geometry.
Definition at line 62 of file Envelope.inl.
References INLINE, maxx, and minx.
Referenced by centre(), covers(), equals(), expandBy(), expandToInclude(), getHeight(), getWidth(), geos::index::strtree::STRtree::insert(), intersection(), intersects(), geos::geom::operator==(), geos::geom::GeometryFactory::toGeometry(), and translate().
 {
   return maxx < minx;
 }
Envelope & geos::geom::Envelope::operator= (const Envelope & e)
Assignment operator.
Definition at line 476 of file Envelope.cpp.
References maxx, maxy, minx, and miny.
 {
 #if GEOS_DEBUG
   std::cerr<<"Envelope assignment"<<std::endl;
 #endif
   if ( &e != this ) // is this check useful ?
   {
     minx=e.minx;
     maxx=e.maxx;
     miny=e.miny;
     maxy=e.maxy;
   }
   return *this;
 }
void geos::geom::Envelope::setToNull (void)
Makes this Envelope a "null" envelope, that is, the envelope of the empty geometry.
Definition at line 208 of file Envelope.cpp.
References maxx, maxy, minx, and miny.
Referenced by expandBy(), and init().
 {
   minx=0;
   maxx=-1;
   miny=0;
   maxy=-1;
 }
vector< string > geos::geom::Envelope::split (const std::string & str, const std::string & delimiters = " ") private
Splits a string into parts based on the supplied delimiters.
This is a generic function that really belongs in a utility file somewhere
Definition at line 401 of file Envelope.cpp.
Referenced by Envelope().
 {
   vector<string> tokens;
   // Find first "non-delimiter".
   string::size_type lastPos = 0;
   string::size_type pos = str.find_first_of(delimiters, lastPos);
   while (string::npos != pos || string::npos != lastPos)
   {
     // Found a token, add it to the vector.
     tokens.push_back(str.substr(lastPos, pos - lastPos));
     // Skip delimiters.  Note the "not_of"
     lastPos = str.find_first_not_of(delimiters, pos);
     // Find next "non-delimiter"
     pos = str.find_first_of(delimiters, lastPos);
   }
   return tokens;
 }
string geos::geom::Envelope::toString (void) const
Returns a string of the form Env[minx:maxx,miny:maxy] .
Returns
a string of the form Env[minx:maxx,miny:maxy]
Definition at line 346 of file Envelope.cpp.
Referenced by geos::index::quadtree::Key::computeKey(), geos::index::quadtree::Node::createExpanded(), geos::operation::overlay::ElevationMatrix::getCell(), geos::index::quadtree::NodeBase::getSubnodeIndex(), geos::index::quadtree::Root::insert(), and geos::index::quadtree::Quadtree::insert().
 {
   ostringstream s;
   s<<*this;
   return s.str();
 }
void geos::geom::Envelope::translate (double transX, double transY)
Translates this envelope by given amounts in the X and Y direction.
Parameters
transX the amount to translate along the X axis
transY the amount to translate along the Y axis
Definition at line 450 of file Envelope.cpp.
References getMaxX(), getMaxY(), getMinX(), getMinY(), init(), and isNull().
 {
   if (isNull()) return;
   init(getMinX() + transX, getMaxX() + transX,
     getMinY() + transY, getMaxY() + transY);
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Envelope & o) friend
Output operator.
Definition at line 336 of file Envelope.cpp.
 {
   os << "Env[" << o.minx << ":" << o.maxx << ","
      << o.miny << ":" << o.maxy << "]";
   return os;
 }
Member Data Documentation
double geos::geom::Envelope::maxx private
the maximum x-coordinate
Definition at line 489 of file Envelope.h.
Referenced by covers(), distance(), equals(), expandBy(), expandToInclude(), getMaxX(), getWidth(), hashCode(), init(), intersection(), intersects(), isNull(), geos::geom::operator<<(), operator=(), and setToNull().
double geos::geom::Envelope::maxy private
the maximum y-coordinate
Definition at line 495 of file Envelope.h.
Referenced by covers(), distance(), equals(), expandBy(), expandToInclude(), getHeight(), getMaxY(), hashCode(), init(), intersection(), intersects(), geos::geom::operator<<(), operator=(), and setToNull().
double geos::geom::Envelope::minx private
the minimum x-coordinate
Definition at line 486 of file Envelope.h.
Referenced by covers(), distance(), equals(), expandBy(), expandToInclude(), getMinX(), getWidth(), hashCode(), init(), intersection(), intersects(), isNull(), geos::geom::operator<<(), operator=(), and setToNull().
double geos::geom::Envelope::miny private
the minimum y-coordinate
Definition at line 492 of file Envelope.h.
Referenced by covers(), distance(), equals(), expandBy(), expandToInclude(), getHeight(), getMinY(), hashCode(), init(), intersection(), intersects(), geos::geom::operator<<(), operator=(), and setToNull().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/Envelope.h
/home/vicky/potree/geos/vicky/src/geom/Envelope.cpp
/home/vicky/potree/geos/vicky/include/geos/geom/Envelope.inl