GEOS: geos::operation::buffer::BufferSubgraph Class Reference
geos::operation::buffer::BufferSubgraph Class Reference
A connected subset of the graph of DirectedEdge and geomgraph::Node.
#include <BufferSubgraph.h>
Public Member Functions
BufferSubgraph ()
~BufferSubgraph ()
std::vector< geomgraph::DirectedEdge * > * getDirectedEdges ()
std::vector< geomgraph::Node * > * getNodes ()
geom::Coordinate * getRightmostCoordinate ()
Gets the rightmost coordinate in the edges of the subgraph.
void create (geomgraph::Node *node)
Creates the subgraph consisting of all edges reachable from this node.
void computeDepth (int outsideDepth)
void findResultEdges ()
Find all edges whose depths indicates that they are in the result area(s).
int compareTo (BufferSubgraph *)
BufferSubgraphs are compared on the x-value of their rightmost Coordinate.
geom::Envelope * getEnvelope ()
Computes the envelope of the edges in the subgraph. The envelope is cached after being computed.
Private Member Functions
void addReachable (geomgraph::Node *startNode)
Adds all nodes and edges reachable from this node to the subgraph.
void add (geomgraph::Node *node, std::vector< geomgraph::Node * > *nodeStack)
Adds the argument node and all its out edges to the subgraph.
void clearVisitedEdges ()
void computeDepths (geomgraph::DirectedEdge *startEdge)
Compute depths for all dirEdges via breadth-first traversal of nodes in graph.
void computeNodeDepth (geomgraph::Node *n)
void copySymDepths (geomgraph::DirectedEdge *de)
bool contains (std::set< geomgraph::Node * > &nodes, geomgraph::Node *node)
Private Attributes
RightmostEdgeFinder finder
std::vector< geomgraph::DirectedEdge * > dirEdgeList
std::vector< geomgraph::Node * > nodes
geom::Coordinate * rightMostCoord
geom::Envelope * env
Friends
std::ostream & operator<< (std::ostream &os, const BufferSubgraph &bs)
Detailed Description
A connected subset of the graph of DirectedEdge and geomgraph::Node.
Its edges will generate either
a single polygon in the complete buffer, with zero or more holes, or
ne or more connected holes
Definition at line 61 of file BufferSubgraph.h.
Constructor & Destructor Documentation
geos::operation::buffer::BufferSubgraph::BufferSubgraph ()
Definition at line 51 of file BufferSubgraph.cpp.
   :
   finder(),
   dirEdgeList(),
   nodes(),
   rightMostCoord(nullptr),
   env(nullptr)
 {
 }
geos::operation::buffer::BufferSubgraph::~BufferSubgraph ()
Definition at line 61 of file BufferSubgraph.cpp.
References env.
 {
   delete env;
 }
Member Function Documentation
void geos::operation::buffer::BufferSubgraph::add (geomgraph::Node * node, std::vector< geomgraph::Node * > * nodeStack) private
Adds the argument node and all its out edges to the subgraph.
Parameters
node the node to add
nodeStack the current set of nodes being traversed
NOTE: this is a depth-first traversal of the graph. This will cause a large depth of recursion. It might be better to do a breadth-first traversal.
Definition at line 98 of file BufferSubgraph.cpp.
References geos::geomgraph::EdgeEndStar::begin(), dirEdgeList, geos::geomgraph::EdgeEndStar::end(), geos::geomgraph::Node::getEdges(), geos::geomgraph::EdgeEnd::getNode(), geos::geomgraph::DirectedEdge::getSym(), geos::geomgraph::GraphComponent::isVisited(), nodes, and geos::geomgraph::GraphComponent::setVisited().
Referenced by addReachable().
 {
   node->setVisited(true);
   nodes.push_back(node);
   EdgeEndStar *ees=node->getEdges();
   EdgeEndStar::iterator it=ees->begin();
   EdgeEndStar::iterator endIt=ees->end();
   for( ; it!=endIt; ++it)
   {
     assert(dynamic_cast<DirectedEdge*>(*it));
     DirectedEdge *de=static_cast<DirectedEdge*>(*it);
     dirEdgeList.push_back(de);
     DirectedEdge *sym=de->getSym();
     Node *symNode=sym->getNode();
     if (! symNode->isVisited()) nodeStack->push_back(symNode);
   }
 }
void geos::operation::buffer::BufferSubgraph::addReachable (geomgraph::Node * startNode) private
Adds all nodes and edges reachable from this node to the subgraph.
Uses an explicit stack to avoid a large depth of recursion.
Parameters
node a node known to be in the subgraph
Definition at line 85 of file BufferSubgraph.cpp.
References add().
Referenced by create().
 {
   vector<Node*> nodeStack;
   nodeStack.push_back(startNode);
   while (!nodeStack.empty()) {
     Node *node=nodeStack.back();
     nodeStack.pop_back();
     add(node, &nodeStack);
   }
 }
void geos::operation::buffer::BufferSubgraph::clearVisitedEdges () private
Definition at line 123 of file BufferSubgraph.cpp.
References dirEdgeList, and geos::geomgraph::DirectedEdge::setVisited().
Referenced by computeDepth().
 {
   for(size_t i=0, n=dirEdgeList.size(); i<n; ++i)
   {
     DirectedEdge *de=dirEdgeList[i];
     de->setVisited(false);
   }
 }
int geos::operation::buffer::BufferSubgraph::compareTo (BufferSubgraph * graph)
BufferSubgraphs are compared on the x-value of their rightmost Coordinate.
This defines a partial ordering on the graphs such that:
g1 >= g2 <==> Ring(g2) does not contain Ring(g1)
where Polygon(g) is the buffer polygon that is built from g.
This relationship is used to sort the BufferSubgraphs so that shells are guaranteed to be built before holes.
Definition at line 250 of file BufferSubgraph.cpp.
References rightMostCoord, and geos::geom::Coordinate::x.
Referenced by geos::operation::buffer::BufferSubgraphGT().
 {
   assert(rightMostCoord);
   if (rightMostCoord->x<graph->rightMostCoord->x) {
     return -1;
   }
   if (rightMostCoord->x>graph->rightMostCoord->x) {
     return 1;
   }
   return 0;
 }
void geos::operation::buffer::BufferSubgraph::computeDepth (int outsideDepth)
Definition at line 134 of file BufferSubgraph.cpp.
References clearVisitedEdges(), computeDepths(), copySymDepths(), finder, geos::operation::buffer::RightmostEdgeFinder::getEdge(), and geos::geomgraph::DirectedEdge::setEdgeDepths().
Referenced by geos::operation::buffer::BufferBuilder::buildSubgraphs().
 {
   clearVisitedEdges();
   // find an outside edge to assign depth to
   DirectedEdge *de=finder.getEdge();
 #if GEOS_DEBUG
 cerr<<"outside depth: "<<outsideDepth<<endl;
 #endif
   //Node *n=de->getNode();
   //Label *label=de->getLabel();
   // right side of line returned by finder is on the outside
   de->setEdgeDepths(Position::RIGHT, outsideDepth);
   copySymDepths(de);
   //computeNodeDepth(n, de);
   computeDepths(de);
 }
void geos::operation::buffer::BufferSubgraph::computeDepths (geomgraph::DirectedEdge * startEdge) private
Compute depths for all dirEdges via breadth-first traversal of nodes in graph.
Parameters
startEdge edge to start processing with
Definition at line 264 of file BufferSubgraph.cpp.
References geos::geomgraph::EdgeEndStar::begin(), computeNodeDepth(), geos::geomgraph::EdgeEndStar::end(), geos::geomgraph::Node::getEdges(), geos::geomgraph::EdgeEnd::getNode(), geos::geomgraph::DirectedEdge::getSym(), geos::geomgraph::DirectedEdge::isVisited(), and geos::geomgraph::DirectedEdge::setVisited().
Referenced by computeDepth().
 {
   set<Node *> nodesVisited;
   list<Node*> nodeQueue; // Used to be a vector
   Node *startNode=startEdge->getNode();
   nodeQueue.push_back(startNode);
   //nodesVisited.push_back(startNode);
   nodesVisited.insert(startNode);
   startEdge->setVisited(true);
   while (! nodeQueue.empty())
   {
     //System.out.println(nodes.size() + " queue: " + nodeQueue.size());
     Node *n=nodeQueue.front(); // [0];
     //nodeQueue.erase(nodeQueue.begin());
     nodeQueue.pop_front();
     nodesVisited.insert(n);
     // compute depths around node, starting at this edge since it has depths assigned
     computeNodeDepth(n);
     // add all adjacent nodes to process queue,
     // unless the node has been visited already
     EdgeEndStar *ees=n->getEdges();
     EdgeEndStar::iterator endIt=ees->end();
     EdgeEndStar::iterator it=ees->begin();
     for(; it!=endIt; ++it)
     {
       assert(dynamic_cast<DirectedEdge*>(*it));
       DirectedEdge *de=static_cast<DirectedEdge*>(*it);
       DirectedEdge *sym=de->getSym();
       if (sym->isVisited()) continue;
       Node *adjNode=sym->getNode();
       //if (! contains(nodesVisited,adjNode))
       if(nodesVisited.insert(adjNode).second)
       {
         nodeQueue.push_back(adjNode);
         //nodesVisited.insert(adjNode);
       }
     }
   }
 }
void geos::operation::buffer::BufferSubgraph::computeNodeDepth (geomgraph::Node * n) private
Definition at line 154 of file BufferSubgraph.cpp.
References geos::geomgraph::EdgeEndStar::begin(), geos::geomgraph::DirectedEdgeStar::computeDepths(), copySymDepths(), geos::geomgraph::EdgeEndStar::end(), geos::geomgraph::Node::getCoordinate(), geos::geomgraph::Node::getEdges(), geos::geomgraph::DirectedEdge::getSym(), geos::geomgraph::DirectedEdge::isVisited(), and geos::geomgraph::DirectedEdge::setVisited().
Referenced by computeDepths().
 {
   // find a visited dirEdge to start at
   DirectedEdge *startEdge=nullptr;
   assert(dynamic_cast<DirectedEdgeStar *>(n->getEdges()));
   DirectedEdgeStar *ees=static_cast<DirectedEdgeStar *>(n->getEdges());
   EdgeEndStar::iterator endIt=ees->end();
   EdgeEndStar::iterator it=ees->begin();
   for(; it!=endIt; ++it)
   {
     assert(dynamic_cast<DirectedEdge*>(*it));
     DirectedEdge *de=static_cast<DirectedEdge*>(*it);
     if (de->isVisited() || de->getSym()->isVisited()) {
       startEdge=de;
       break;
     }
   }
   // MD - testing  Result: breaks algorithm
   //if (startEdge==null) return;
   // only compute string append if assertion would fail
   if (startEdge == nullptr)
   {
     throw util::TopologyException(
       "unable to find edge to compute depths at",
       n->getCoordinate());
   }
   ees->computeDepths(startEdge);
   // copy depths to sym edges
   for(it=ees->begin(); it!=endIt; ++it)
   {
     assert(dynamic_cast<DirectedEdge*>(*it));
     DirectedEdge *de=static_cast<DirectedEdge*>(*it);
     de->setVisited(true);
     copySymDepths(de);
   }
 }
bool geos::operation::buffer::BufferSubgraph::contains (std::set< geomgraph::Node * > & nodes, geomgraph::Node * node) private
Definition at line 311 of file BufferSubgraph.cpp.
 {
   //bool result=false;
   if ( nodeSet.find(node) != nodeSet.end() ) return true;
   return false;
 }
void geos::operation::buffer::BufferSubgraph::copySymDepths (geomgraph::DirectedEdge * de) private
Definition at line 200 of file BufferSubgraph.cpp.
References geos::geomgraph::DirectedEdge::getDepth(), geos::geomgraph::DirectedEdge::getSym(), and geos::geomgraph::DirectedEdge::setDepth().
Referenced by computeDepth(), and computeNodeDepth().
 {
 #if GEOS_DEBUG
   cerr << "copySymDepths: " << de->getDepth(Position::LEFT)
        << ", " << de->getDepth(Position::RIGHT)
        << endl;
 #endif
   DirectedEdge *sym=de->getSym();
   sym->setDepth(Position::LEFT, de->getDepth(Position::RIGHT));
   sym->setDepth(Position::RIGHT, de->getDepth(Position::LEFT));
 }
void geos::operation::buffer::BufferSubgraph::create (geomgraph::Node * node)
Creates the subgraph consisting of all edges reachable from this node.
Finds the edges in the graph and the rightmost coordinate.
Parameters
node a node to start the graph traversal from
Definition at line 68 of file BufferSubgraph.cpp.
References addReachable(), dirEdgeList, geos::operation::buffer::RightmostEdgeFinder::findEdge(), finder, geos::operation::buffer::RightmostEdgeFinder::getCoordinate(), and rightMostCoord.
Referenced by geos::operation::buffer::BufferBuilder::createSubgraphs().
 {
   addReachable(node);
   // We are assuming that dirEdgeList
   // contains *at leas* ONE forward DirectedEdge
   finder.findEdge(&dirEdgeList);
   rightMostCoord=&(finder.getCoordinate());
   // this is what happen if no forward DirectedEdge
   // is passed to the RightmostEdgeFinder
   assert(rightMostCoord);
 }
void geos::operation::buffer::BufferSubgraph::findResultEdges ()
Find all edges whose depths indicates that they are in the result area(s).
Since we want polygon shells to be oriented CW, choose dirEdges with the interior of the result on the RHS. Mark them as being in the result. Interior Area edges are the result of dimensional collapses. They do not form part of the result area boundary.
Select edges which have an interior depth on the RHS and an exterior depth on the LHS. Note that because of weird rounding effects there may be edges which have negative depths! Negative depths count as "outside".
Definition at line 214 of file BufferSubgraph.cpp.
References dirEdgeList, geos::geomgraph::DirectedEdge::getDepth(), geos::geomgraph::DirectedEdge::isInteriorAreaEdge(), geos::geomgraph::DirectedEdge::printEdge(), and geos::geomgraph::DirectedEdge::setInResult().
Referenced by geos::operation::buffer::BufferBuilder::buildSubgraphs().
 {
 #if GEOS_DEBUG
   cerr<<"BufferSubgraph::findResultEdges got "<<dirEdgeList.size()<<" edges"<<endl;
 #endif
   for(size_t i=0, n=dirEdgeList.size(); i<n; ++i)
   {
     DirectedEdge *de=dirEdgeList[i];
     // <FIX> - handle negative depths
 #if GEOS_DEBUG
     cerr << " dirEdge "<<i<<": " << de->printEdge() << endl
          << "         depth right: " << de->getDepth(Position::RIGHT) << endl
          << "          depth left: " << de->getDepth(Position::LEFT) << endl
          << "    interiorAreaEdge: " << de->isInteriorAreaEdge()<<endl;
 #endif
     if ( de->getDepth(Position::RIGHT)>=1
       &&  de->getDepth(Position::LEFT)<=0
       && !de->isInteriorAreaEdge()) {
           de->setInResult(true);
 #if GEOS_DEBUG
           cerr<<"   IN RESULT"<<endl;
 #endif
     }
   }
 }
std::vector< geomgraph::DirectedEdge * > * geos::operation::buffer::BufferSubgraph::getDirectedEdges () inline
Definition at line 183 of file BufferSubgraph.h.
References geos::operation::buffer::BufferSubgraphGT().
Referenced by geos::operation::buffer::BufferBuilder::buildSubgraphs(), and geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments().
{
   return &dirEdgeList;
 }
Envelope * geos::operation::buffer::BufferSubgraph::getEnvelope ()
Computes the envelope of the edges in the subgraph. The envelope is cached after being computed.
Returns
the envelope of the graph.
Definition at line 320 of file BufferSubgraph.cpp.
References dirEdgeList, env, geos::geom::Envelope::expandToInclude(), geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), geos::geomgraph::EdgeEnd::getEdge(), and geos::geom::CoordinateSequence::getSize().
Referenced by geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments().
 {
   if (env == nullptr) {
     env = new Envelope();
     std::size_t const size = dirEdgeList.size();
     for(std::size_t i=0; i<size; ++i)
     {
       DirectedEdge *dirEdge=dirEdgeList[i];
       const CoordinateSequence *pts = dirEdge->getEdge()->getCoordinates();
       std::size_t const n = pts->getSize()-1;
       for (std::size_t j=0; j<n; ++j) {
         env->expandToInclude(pts->getAt(j));
       }
     }
   }
   return env;
 }
std::vector< geomgraph::Node * > * geos::operation::buffer::BufferSubgraph::getNodes () inline
Definition at line 180 of file BufferSubgraph.h.
Referenced by geos::operation::buffer::BufferBuilder::buildSubgraphs().
 { return &nodes; }
geom::Coordinate * geos::operation::buffer::BufferSubgraph::getRightmostCoordinate () inline
Gets the rightmost coordinate in the edges of the subgraph.
Definition at line 177 of file BufferSubgraph.h.
Referenced by geos::operation::buffer::BufferBuilder::buildSubgraphs().
 {return rightMostCoord;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const BufferSubgraph & bs) friend
Definition at line 338 of file BufferSubgraph.cpp.
 {
   os << "BufferSubgraph[" << &bs << "] "
      << bs.nodes.size() << " nodes, "
      << bs.dirEdgeList.size() << " directed edges" << std::endl;
   for (size_t i=0, n=bs.nodes.size(); i<n; i++)
     os << "  Node " << i << ": " << *(bs.nodes[i]) << std::endl;
   for (size_t i=0, n=bs.dirEdgeList.size(); i<n; i++)
   {
     os << "  DirEdge " << i << ": " << std::endl
        << bs.dirEdgeList[i]->printEdge() << std::endl;
   }
   return os;
 }
Member Data Documentation
std::vector<geomgraph::DirectedEdge*> geos::operation::buffer::BufferSubgraph::dirEdgeList private
Definition at line 65 of file BufferSubgraph.h.
Referenced by add(), clearVisitedEdges(), create(), findResultEdges(), getEnvelope(), and geos::operation::buffer::operator<<().
geom::Envelope* geos::operation::buffer::BufferSubgraph::env private
Definition at line 71 of file BufferSubgraph.h.
Referenced by getEnvelope(), and ~BufferSubgraph().
RightmostEdgeFinder geos::operation::buffer::BufferSubgraph::finder private
Definition at line 63 of file BufferSubgraph.h.
Referenced by computeDepth(), and create().
std::vector<geomgraph::Node*> geos::operation::buffer::BufferSubgraph::nodes private
Definition at line 67 of file BufferSubgraph.h.
Referenced by add(), and geos::operation::buffer::operator<<().
geom::Coordinate* geos::operation::buffer::BufferSubgraph::rightMostCoord private
Definition at line 69 of file BufferSubgraph.h.
Referenced by compareTo(), and create().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/BufferSubgraph.h
/home/vicky/potree/geos/vicky/src/operation/buffer/BufferSubgraph.cpp