GEOS: geos::noding::snapround::SimpleSnapRounder Class Reference
geos::noding::snapround::SimpleSnapRounder Class Reference
Uses Snap Rounding to compute a rounded, fully noded arrangement from a set of SegmentStrings.
#include <SimpleSnapRounder.h>
Public Member Functions
SimpleSnapRounder (const geom::PrecisionModel &newPm)
std::vector< SegmentString * > * getNodedSubstrings () const override
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
void computeNodes (std::vector< SegmentString * > *inputSegmentStrings) override
Computes the noding for a collection of SegmentStrings.
void add (const SegmentString *segStr)
void computeVertexSnaps (const std::vector< SegmentString * > &edges)
Private Member Functions
void checkCorrectness (std::vector< SegmentString * > &inputSegmentStrings)
void snapRound (std::vector< SegmentString * > *segStrings, algorithm::LineIntersector &li)
void findInteriorIntersections (std::vector< SegmentString * > &segStrings, algorithm::LineIntersector &li, std::vector< geom::Coordinate > &ret)
void computeSnaps (const std::vector< SegmentString * > &segStrings, std::vector< geom::Coordinate > &snapPts)
Computes nodes introduced as a result of snapping segments to snap points (hot pixels)
void computeSnaps (NodedSegmentString *ss, std::vector< geom::Coordinate > &snapPts)
void computeVertexSnaps (NodedSegmentString *e0, NodedSegmentString *e1)
Performs a brute-force comparison of every segment in each SegmentString. This has n^2 performance.
SimpleSnapRounder (const SimpleSnapRounder &other)=delete
SimpleSnapRounder & operator= (const SimpleSnapRounder &rhs)=delete
Private Attributes
const geom::PrecisionModel & pm
algorithm::LineIntersector li
double scaleFactor
std::vector< SegmentString * > * nodedSegStrings
Detailed Description
Uses Snap Rounding to compute a rounded, fully noded arrangement from a set of SegmentStrings.
Implements the Snap Rounding technique described in Hobby, Guibas & Marimont, and Goodrich et al. Snap Rounding assumes that all vertices lie on a uniform grid (hence the precision model of the input must be fixed precision, and all the input vertices must be rounded to that precision).
This implementation uses simple iteration over the line segments.
This is not the most efficient approach for large sets of segments.
This implementation appears to be fully robust using an integer precision model. It will function with non-integer precision models, but the results are not 100% guaranteed to be correctly noded.
Definition at line 73 of file SimpleSnapRounder.h.
Constructor & Destructor Documentation
geos::noding::snapround::SimpleSnapRounder::SimpleSnapRounder (const geom::PrecisionModel & newPm)
Definition at line 45 of file SimpleSnapRounder.cpp.
   :
   pm(newPm),
   li(&newPm),
   scaleFactor(newPm.getScale())
 {
 }
geos::noding::snapround::SimpleSnapRounder::SimpleSnapRounder (const SimpleSnapRounder & other) private delete
Member Function Documentation
void geos::noding::snapround::SimpleSnapRounder::add (const SegmentString * segStr)
void geos::noding::snapround::SimpleSnapRounder::checkCorrectness (std::vector< SegmentString * > & inputSegmentStrings) private
Definition at line 78 of file SimpleSnapRounder.cpp.
References computeSnaps(), and geos::noding::NodedSegmentString::getNodedSubstrings().
Referenced by computeNodes().
 {
   SegmentString::NonConstVect resultSegStrings;
   NodedSegmentString::getNodedSubstrings(
     inputSegmentStrings.begin(), inputSegmentStrings.end(), &resultSegStrings
   );
   NodingValidator nv(resultSegStrings);
   try {
     nv.checkValid();
   }
   catch (const std::exception &ex) {
     for ( SegmentString::NonConstVect::iterator i=resultSegStrings.begin(),
                                                 e=resultSegStrings.end();
           i!=e; ++i )
     {
       delete *i;
     }
     std::cerr << ex.what() << std::endl;
     throw;
   }
   for ( SegmentString::NonConstVect::iterator i=resultSegStrings.begin(),
                                               e=resultSegStrings.end();
         i!=e; ++i )
   {
     delete *i;
   }
 }
void geos::noding::snapround::SimpleSnapRounder::computeNodes (std::vector< SegmentString * > * segStrings) override virtual
Computes the noding for a collection of SegmentStrings.
Some Noders may add all these nodes to the input SegmentStrings; others may only add some or none at all.
Parameters
segStrings a collection of SegmentStrings to node
Implements geos::noding::Noder.
Definition at line 64 of file SimpleSnapRounder.cpp.
References checkCorrectness(), li, nodedSegStrings, and snapRound().
 {
   nodedSegStrings = inputSegmentStrings;
   snapRound(inputSegmentStrings, li);
   // testing purposes only - remove in final version
   assert(nodedSegStrings == inputSegmentStrings);
   checkCorrectness(*inputSegmentStrings);
 }
void geos::noding::snapround::SimpleSnapRounder::computeSnaps (const std::vector< SegmentString * > & segStrings, std::vector< geom::Coordinate > & snapPts) private
Computes nodes introduced as a result of snapping segments to snap points (hot pixels)
Parameters
li
Referenced by checkCorrectness(), and snapRound().
void geos::noding::snapround::SimpleSnapRounder::computeSnaps (NodedSegmentString * ss, std::vector< geom::Coordinate > & snapPts) private
Definition at line 131 of file SimpleSnapRounder.cpp.
References geos::noding::snapround::HotPixel::addSnappedNode(), li, scaleFactor, and geos::noding::NodedSegmentString::size().
 {
   for (vector<Coordinate>::iterator
     it=snapPts.begin(), itEnd=snapPts.end();
     it!=itEnd; ++it)
   {
     const Coordinate& snapPt = *it;
     HotPixel hotPixel(snapPt, scaleFactor, li);
     for (int i=0, n=ss->size()-1; i<n; ++i) {
       hotPixel.addSnappedNode(*ss, i);
     }
   }
 }
void geos::noding::snapround::SimpleSnapRounder::computeVertexSnaps (const std::vector< SegmentString * > & edges)
Computes nodes introduced as a result of snapping segments to vertices of other segments
Parameters
edges the list of segment strings to snap together. Must be NodedSegmentString or an assertion will fail.
Definition at line 176 of file SimpleSnapRounder.cpp.
Referenced by snapRound().
 {
   for (SegmentString::NonConstVect::const_iterator
       i0=edges.begin(), i0End=edges.end();
       i0!=i0End; ++i0)
   {
     NodedSegmentString* edge0 = dynamic_cast<NodedSegmentString*>(*i0);
     assert(edge0);
     for (SegmentString::NonConstVect::const_iterator
         i1=edges.begin(), i1End=edges.end();
         i1!=i1End; ++i1)
     {
       NodedSegmentString* edge1 = dynamic_cast<NodedSegmentString*>(*i1);
       assert(edge1);
       computeVertexSnaps(edge0, edge1);
     }
   }
 }
void geos::noding::snapround::SimpleSnapRounder::computeVertexSnaps (NodedSegmentString * e0, NodedSegmentString * e1) private
Performs a brute-force comparison of every segment in each SegmentString. This has n^2 performance.
Definition at line 147 of file SimpleSnapRounder.cpp.
References geos::noding::NodedSegmentString::addIntersection(), geos::noding::snapround::HotPixel::addSnappedNode(), geos::geom::CoordinateSequence::getAt(), geos::noding::NodedSegmentString::getCoordinates(), geos::geom::CoordinateSequence::getSize(), li, and scaleFactor.
 {
   const CoordinateSequence* pts0 = e0->getCoordinates();
   const CoordinateSequence* pts1 = e1->getCoordinates();
   for (unsigned int i0=0, n0=static_cast<unsigned int>(pts0->getSize()-1); i0<n0; i0++)
   {
     const Coordinate& p0 = pts0->getAt(i0);
     HotPixel hotPixel(p0, scaleFactor, li);
     for (unsigned int i1=1, n1=static_cast<unsigned int>(pts1->getSize()-1); i1<n1; i1++)
     {
             // don't snap a vertex to itself
       if (i0 == i1 && e0 == e1) {
         continue;
       }
 //cerr<<"trying "<<p0<<" against "<<pts1->getAt(i1)<<" "<<pts1->getAt(i1 + 1)<<endl;
       bool isNodeAdded = hotPixel.addSnappedNode(*e1, i1);
       // if a node is created for a vertex, that vertex must be noded too
       if (isNodeAdded) {
         e0->addIntersection(p0, i0);
       }
     }
   }
 }
void geos::noding::snapround::SimpleSnapRounder::findInteriorIntersections (std::vector< SegmentString * > & segStrings, algorithm::LineIntersector & li, std::vector< geom::Coordinate > & ret) private
Computes all interior intersections in the vector of SegmentString, and fill the given vector with their Coordinates.
Does NOT node the segStrings.
Parameters
segStrings a vector of const Coordinates for the intersections
li the algorithm::LineIntersector to use
ret the vector to push intersection Coordinates to
Definition at line 211 of file SimpleSnapRounder.cpp.
References geos::noding::MCIndexNoder::computeNodes(), and geos::noding::SinglePassNoder::setSegmentIntersector().
Referenced by snapRound().
 {
   IntersectionFinderAdder intFinderAdder(li, ret);
   MCIndexNoder noder;
   noder.setSegmentIntersector(&intFinderAdder);
   noder.computeNodes(&segStrings);
   //intFinderAdder.getInteriorIntersections();
 }
std::vector< SegmentString * > * geos::noding::snapround::SimpleSnapRounder::getNodedSubstrings () const override virtual
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
Returns
a newly allocated std::vector of const SegmentStrings. Caller is responsible to delete container and elements.
Implements geos::noding::Noder.
Definition at line 55 of file SimpleSnapRounder.cpp.
References geos::noding::NodedSegmentString::getNodedSubstrings(), and nodedSegStrings.
 {
   std::vector<SegmentString*> *ret = new std::vector<SegmentString*>();
   NodedSegmentString::getNodedSubstrings(nodedSegStrings->begin(), nodedSegStrings->end(), ret);
   return ret;
 }
SimpleSnapRounder& geos::noding::snapround::SimpleSnapRounder::operator= (const SimpleSnapRounder & rhs) private delete
void geos::noding::snapround::SimpleSnapRounder::snapRound (std::vector< SegmentString * > * segStrings, algorithm::LineIntersector & li) private
Definition at line 198 of file SimpleSnapRounder.cpp.
References computeSnaps(), computeVertexSnaps(), and findInteriorIntersections().
Referenced by computeNodes().
 {
   assert(segStrings);
   vector<Coordinate> intersections;
   findInteriorIntersections(*segStrings, li, intersections);
   computeSnaps(*segStrings, intersections);
   computeVertexSnaps(*segStrings);
 }
Member Data Documentation
algorithm::LineIntersector geos::noding::snapround::SimpleSnapRounder::li private
Definition at line 97 of file SimpleSnapRounder.h.
Referenced by computeNodes(), computeSnaps(), and computeVertexSnaps().
std::vector<SegmentString*>* geos::noding::snapround::SimpleSnapRounder::nodedSegStrings private
Definition at line 99 of file SimpleSnapRounder.h.
Referenced by computeNodes(), and getNodedSubstrings().
const geom::PrecisionModel& geos::noding::snapround::SimpleSnapRounder::pm private
Definition at line 96 of file SimpleSnapRounder.h.
double geos::noding::snapround::SimpleSnapRounder::scaleFactor private
Definition at line 98 of file SimpleSnapRounder.h.
Referenced by computeSnaps(), and computeVertexSnaps().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/snapround/SimpleSnapRounder.h
/home/vicky/potree/geos/vicky/src/noding/snapround/SimpleSnapRounder.cpp