GEOS: geos::index::sweepline::SweepLineIndex Class Reference
geos::index::sweepline::SweepLineIndex Class Reference
A sweepline implements a sorted index on a set of intervals.
#include <SweepLineIndex.h>
Public Member Functions
SweepLineIndex ()
~SweepLineIndex ()
void add (SweepLineInterval *sweepInt)
void computeOverlaps (SweepLineOverlapAction *action)
Private Member Functions
void buildIndex ()
void processOverlaps (int start, int end, SweepLineInterval *s0, SweepLineOverlapAction *action)
Private Attributes
std::vector< SweepLineEvent * > events
bool indexBuilt
int nOverlaps
Detailed Description
A sweepline implements a sorted index on a set of intervals.
It is used to compute all overlaps between the interval in the index.
Definition at line 47 of file SweepLineIndex.h.
Constructor & Destructor Documentation
geos::index::sweepline::SweepLineIndex::SweepLineIndex ()
Definition at line 29 of file SweepLineIndex.cpp.
   :
   indexBuilt(false),
   nOverlaps(0)
 {
   //events=new vector<SweepLineEvent*>();
   //nOverlaps=0;
 }
geos::index::sweepline::SweepLineIndex::~SweepLineIndex ()
Definition at line 38 of file SweepLineIndex.cpp.
 {
   //delete events;
 }
Member Function Documentation
void geos::index::sweepline::SweepLineIndex::add (SweepLineInterval * sweepInt)
Definition at line 44 of file SweepLineIndex.cpp.
References events, geos::index::sweepline::SweepLineInterval::getMax(), and geos::index::sweepline::SweepLineInterval::getMin().
 {
   // FIXME: who's going to delete the newly-created events ?
   SweepLineEvent *insertEvent=new SweepLineEvent(sweepInt->getMin(),nullptr,sweepInt);
   events.push_back(insertEvent);
   events.push_back(new SweepLineEvent(sweepInt->getMax(), insertEvent, sweepInt));
 }
void geos::index::sweepline::SweepLineIndex::buildIndex () private
Because Delete Events have a link to their corresponding Insert event, it is possible to compute exactly the range of events which must be compared to a given Insert event object.
Definition at line 54 of file SweepLineIndex.cpp.
References events, geos::index::sweepline::SweepLineEvent::getInsertEvent(), indexBuilt, geos::index::sweepline::SweepLineEvent::isDelete(), and geos::index::sweepline::SweepLineEvent::setDeleteEventIndex().
Referenced by computeOverlaps().
 {
     if (!indexBuilt)
     {
         sort(events.begin(), events.end(), SweepLineEventLessThen());
         const std::vector<SweepLineEvent*>::size_type n = events.size();
         for(std::vector<SweepLineEvent*>::size_type i = 0; i < n; i++)
         {
             SweepLineEvent *ev=events[i];
             if (ev->isDelete())
             {
                 ev->getInsertEvent()->setDeleteEventIndex(static_cast<int>(i));
             }
         }
         indexBuilt = true;
     }
 }
void geos::index::sweepline::SweepLineIndex::computeOverlaps (SweepLineOverlapAction * action)
Definition at line 73 of file SweepLineIndex.cpp.
References buildIndex(), events, geos::index::sweepline::SweepLineEvent::getDeleteEventIndex(), geos::index::sweepline::SweepLineEvent::getInterval(), geos::index::sweepline::SweepLineEvent::isInsert(), nOverlaps, and processOverlaps().
 {
     nOverlaps = 0;
     buildIndex();
     const std::vector<SweepLineEvent*>::size_type n=events.size();
     for(std::vector<SweepLineEvent*>::size_type i=0; i<n; i++)
     {
         SweepLineEvent *ev=events[i];
         if (ev->isInsert())
         {
             processOverlaps(static_cast<int>(i),
                 ev->getDeleteEventIndex(),
                 ev->getInterval(), action);
         }
     }
 }
void geos::index::sweepline::SweepLineIndex::processOverlaps (int start, int end, SweepLineInterval * s0, SweepLineOverlapAction * action) private
Since we might need to test for self-intersections, include current insert event object in list of event objects to test. Last index can be skipped, because it must be a Delete event.
Definition at line 93 of file SweepLineIndex.cpp.
References events, geos::index::sweepline::SweepLineEvent::getInterval(), geos::index::sweepline::SweepLineEvent::isInsert(), nOverlaps, and geos::index::sweepline::SweepLineOverlapAction::overlap().
Referenced by computeOverlaps().
 {
   for(int i=start; i<end; i++)
   {
     SweepLineEvent *ev=events[i];
     if (ev->isInsert()) {
       SweepLineInterval *s1=ev->getInterval();
       action->overlap(s0,s1);
       nOverlaps++;
     }
   }
 }
Member Data Documentation
std::vector<SweepLineEvent*> geos::index::sweepline::SweepLineIndex::events private
Definition at line 62 of file SweepLineIndex.h.
Referenced by add(), buildIndex(), computeOverlaps(), and processOverlaps().
bool geos::index::sweepline::SweepLineIndex::indexBuilt private
Definition at line 64 of file SweepLineIndex.h.
Referenced by buildIndex().
int geos::index::sweepline::SweepLineIndex::nOverlaps private
Definition at line 67 of file SweepLineIndex.h.
Referenced by computeOverlaps(), and processOverlaps().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/sweepline/SweepLineIndex.h
/home/vicky/potree/geos/vicky/src/index/sweepline/SweepLineIndex.cpp