GEOS: geos::io::StringTokenizer Class Reference
geos::io::StringTokenizer Class Reference
#include <StringTokenizer.h>
Public Types
enum { TT_EOF, TT_EOL, TT_NUMBER, TT_WORD }
Public Member Functions
StringTokenizer (const std::string &txt)
~StringTokenizer ()
int nextToken ()
int peekNextToken ()
double getNVal ()
std::string getSVal ()
Private Member Functions
StringTokenizer (const StringTokenizer &other)=delete
StringTokenizer & operator= (const StringTokenizer &rhs)=delete
Private Attributes
const std::string & str
std::string stok
double ntok
std::string::const_iterator iter
Detailed Description
Definition at line 35 of file StringTokenizer.h.
Member Enumeration Documentation
anonymous enum
Enumerator
TT_EOF
TT_EOL
TT_NUMBER
TT_WORD
Definition at line 37 of file StringTokenizer.h.
        {
     TT_EOF,
     TT_EOL,
     TT_NUMBER,
     TT_WORD
   };
Constructor & Destructor Documentation
geos::io::StringTokenizer::StringTokenizer (const std::string & txt) explicit
geos::io::StringTokenizer::~StringTokenizer () inline
Definition at line 45 of file StringTokenizer.h.
 {}
geos::io::StringTokenizer::StringTokenizer (const StringTokenizer & other) private delete
Member Function Documentation
double geos::io::StringTokenizer::getNVal ()
Definition at line 177 of file StringTokenizer.cpp.
Referenced by geos::io::WKTReader::getNextNumber(), geos::io::WKTReader::getNextWord(), and geos::io::WKTReader::readMultiPointText().
 {
   return ntok;
 }
string geos::io::StringTokenizer::getSVal ()
Definition at line 184 of file StringTokenizer.cpp.
Referenced by geos::io::WKTReader::getNextNumber(), geos::io::WKTReader::getNextWord(), and geos::io::WKTReader::readMultiPointText().
 {
   return stok;
 }
int geos::io::StringTokenizer::nextToken ()
Definition at line 78 of file StringTokenizer.cpp.
References geos::io::strtod_with_vc_fix(), TT_EOF, TT_NUMBER, and TT_WORD.
Referenced by geos::io::WKTReader::getNextNumber(), and geos::io::WKTReader::getNextWord().
 {
   string tok="";
   if (iter==str.end())
     return StringTokenizer::TT_EOF;
   switch(*iter) {
     case '(':
     case ')':
     case ',':
       return *iter++;
     case '\n':
     case '\r':
     case '\t':
     case ' ':
       string::size_type pos=str.find_first_not_of(" \n\r\t",
         iter-str.begin());
       if (pos==string::npos) {
         return StringTokenizer::TT_EOF;
       } else {
         iter=str.begin()+pos;
         return nextToken();
       }
   }
   string::size_type pos=str.find_first_of("\n\r\t() ,",
     iter-str.begin());
   if (pos==string::npos) {
     if (iter!=str.end()) {
       tok.assign(iter,str.end());
       iter=str.end();
     } else {
       return StringTokenizer::TT_EOF;
     }
   } else {
     tok.assign(iter, str.begin()+pos);
     iter=str.begin()+pos;
   }
   char *stopstring;
   double dbl=strtod_with_vc_fix(tok.c_str(),&stopstring);
   if (*stopstring=='\0') {
     ntok=dbl;
     stok="";
     return StringTokenizer::TT_NUMBER;
   } else {
     ntok=0.0;
     stok=tok;
     return StringTokenizer::TT_WORD;
   }
 }
StringTokenizer& geos::io::StringTokenizer::operator= (const StringTokenizer & rhs) private delete
int geos::io::StringTokenizer::peekNextToken ()
Definition at line 129 of file StringTokenizer.cpp.
References geos::io::strtod_with_vc_fix(), TT_EOF, TT_NUMBER, and TT_WORD.
Referenced by geos::io::WKTReader::isNumberNext(), and geos::io::WKTReader::readMultiPointText().
 {
   string::size_type pos;
   string tok="";
   if (iter==str.end())
     return StringTokenizer::TT_EOF;
   pos=str.find_first_not_of(" \r\n\t", iter-str.begin());
   if (pos==string::npos) return StringTokenizer::TT_EOF;
   switch(str[pos]) {
     case '(':
     case ')':
     case ',':
       return str[pos];
   }
   // It's either a Number or a Word, let's
   // see when it ends
   pos=str.find_first_of("\n\r\t() ,", iter-str.begin());
   if (pos==string::npos) {
     if (iter!=str.end()) {
       tok.assign(iter,str.end());
     } else {
       return StringTokenizer::TT_EOF;
     }
   } else {
     tok.assign(iter, str.begin()+pos); //str.end());
   }
   char *stopstring;
   double dbl = strtod_with_vc_fix(tok.c_str(), &stopstring);
   if (*stopstring=='\0') {
     ntok=dbl;
     stok="";
     return StringTokenizer::TT_NUMBER;
   } else {
     ntok=0.0;
     stok=tok;
     return StringTokenizer::TT_WORD;
   }
 }
Member Data Documentation
std::string::const_iterator geos::io::StringTokenizer::iter private
Definition at line 54 of file StringTokenizer.h.
double geos::io::StringTokenizer::ntok private
Definition at line 53 of file StringTokenizer.h.
std::string geos::io::StringTokenizer::stok private
Definition at line 52 of file StringTokenizer.h.
const std::string& geos::io::StringTokenizer::str private
Definition at line 51 of file StringTokenizer.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/io/StringTokenizer.h
/home/vicky/potree/geos/vicky/src/io/StringTokenizer.cpp