GEOS: geos::noding::FastNodingValidator Class Reference
geos::noding::FastNodingValidator Class Reference
Validates that a collection of SegmentStrings is correctly noded.
#include <FastNodingValidator.h>
Public Member Functions
FastNodingValidator (std::vector< noding::SegmentString * > &newSegStrings)
bool isValid ()
std::string getErrorMessage () const
void checkValid ()
Private Member Functions
void execute ()
void checkInteriorIntersections ()
FastNodingValidator (const FastNodingValidator &other)=delete
FastNodingValidator & operator= (const FastNodingValidator &rhs)=delete
Private Attributes
geos::algorithm::LineIntersector li
std::vector< noding::SegmentString * > & segStrings
std::unique_ptr< SingleInteriorIntersectionFinder > segInt
bool isValidVar
Detailed Description
Validates that a collection of SegmentStrings is correctly noded.
Uses indexes to improve performance. Does NOT check a-b-a collapse situations. Also does not check for endpt-interior vertex intersections. This should not be a problem, since the noders should be able to compute intersections between vertices correctly. User may either test the valid condition, or request that a TopologyException be thrown.
Version
1.7
Definition at line 53 of file FastNodingValidator.h.
Constructor & Destructor Documentation
geos::noding::FastNodingValidator::FastNodingValidator (std::vector< noding::SegmentString * > & newSegStrings) inline
Definition at line 58 of file FastNodingValidator.h.
     :
     li(), // robust...
     segStrings(newSegStrings),
     segInt(),
     isValidVar(true)
   {
   }
geos::noding::FastNodingValidator::FastNodingValidator (const FastNodingValidator & other) private delete
Member Function Documentation
void geos::noding::FastNodingValidator::checkInteriorIntersections () private
Definition at line 34 of file FastNodingValidator.cpp.
References geos::noding::MCIndexNoder::computeNodes(), isValidVar, li, segInt, segStrings, and geos::noding::SinglePassNoder::setSegmentIntersector().
 {
   isValidVar = true;
   segInt.reset(new SingleInteriorIntersectionFinder(li));
   MCIndexNoder noder;
   noder.setSegmentIntersector(segInt.get());
   noder.computeNodes(&segStrings);
   if (segInt->hasIntersection()) {
     isValidVar = false;
     return;
   }
 }
void geos::noding::FastNodingValidator::checkValid ()
Checks for an intersection and throws a TopologyException if one is found.
Exceptions
TopologyException if an intersection is found
Definition at line 67 of file FastNodingValidator.cpp.
References execute(), getErrorMessage(), isValidVar, and segInt.
Referenced by geos::geomgraph::EdgeNodingValidator::checkValid().
 {
   execute();
   if (! isValidVar)
   {
     //std::cerr << "Not valid: " << getErrorMessage() << " interior intersection: " << segInt->getInteriorIntersection() << std::endl;
     throw util::TopologyException(getErrorMessage(), segInt->getInteriorIntersection());
   }
 }
void geos::noding::FastNodingValidator::execute () inline private
Definition at line 105 of file FastNodingValidator.h.
Referenced by checkValid().
   {
     if (segInt.get() != nullptr) return;
     checkInteriorIntersections();
   }
std::string geos::noding::FastNodingValidator::getErrorMessage () const
Returns an error message indicating the segments containing the intersection.
Returns
an error message documenting the intersection location
Definition at line 49 of file FastNodingValidator.cpp.
References isValidVar, and segInt.
Referenced by checkValid().
 {
   using geos::io::WKTWriter;
   using geos::geom::Coordinate;
   if (isValidVar) return std::string("no intersections found");
   //return std::string("found non-noded intersection etc etc");
   const std::vector<Coordinate>& intSegs = segInt->getIntersectionSegments();
   assert(intSegs.size() == 4);
   return "found non-noded intersection between "
     + WKTWriter::toLineString(intSegs[0], intSegs[1])
     + " and "
     + WKTWriter::toLineString(intSegs[2], intSegs[3]);
 }
bool geos::noding::FastNodingValidator::isValid () inline
Checks for an intersection and reports if one is found.
Returns
true if the arrangement contains an interior intersection
Definition at line 73 of file FastNodingValidator.h.
   {
     execute();
     return isValidVar;
   }
FastNodingValidator& geos::noding::FastNodingValidator::operator= (const FastNodingValidator & rhs) private delete
Member Data Documentation
bool geos::noding::FastNodingValidator::isValidVar private
Definition at line 103 of file FastNodingValidator.h.
Referenced by checkInteriorIntersections(), checkValid(), and getErrorMessage().
geos::algorithm::LineIntersector geos::noding::FastNodingValidator::li private
Definition at line 97 of file FastNodingValidator.h.
Referenced by checkInteriorIntersections().
std::unique_ptr<SingleInteriorIntersectionFinder> geos::noding::FastNodingValidator::segInt private
Definition at line 101 of file FastNodingValidator.h.
Referenced by checkInteriorIntersections(), checkValid(), and getErrorMessage().
std::vector<noding::SegmentString*>& geos::noding::FastNodingValidator::segStrings private
Definition at line 99 of file FastNodingValidator.h.
Referenced by checkInteriorIntersections().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/FastNodingValidator.h
/home/vicky/potree/geos/vicky/src/noding/FastNodingValidator.cpp