GEOS: geos::io::WKTReader Class Reference
geos::io::WKTReader Class Reference
WKT parser class; see also WKTWriter.
#include <geos.h>
Public Member Functions
WKTReader (const geom::GeometryFactory &gf)
Inizialize parser with given GeometryFactory.
WKTReader (const geom::GeometryFactory *gf)
WKTReader ()
Inizialize parser with default GeometryFactory.
~WKTReader ()
geom::Geometry * read (const std::string &wellKnownText)
Parse a WKT string returning a Geometry.
Protected Member Functions
geom::CoordinateSequence * getCoordinates (io::StringTokenizer *tokenizer)
double getNextNumber (io::StringTokenizer *tokenizer)
std::string getNextEmptyOrOpener (io::StringTokenizer *tokenizer)
std::string getNextCloserOrComma (io::StringTokenizer *tokenizer)
std::string getNextCloser (io::StringTokenizer *tokenizer)
std::string getNextWord (io::StringTokenizer *tokenizer)
geom::Geometry * readGeometryTaggedText (io::StringTokenizer *tokenizer)
geom::Point * readPointText (io::StringTokenizer *tokenizer)
geom::LineString * readLineStringText (io::StringTokenizer *tokenizer)
geom::LinearRing * readLinearRingText (io::StringTokenizer *tokenizer)
geom::MultiPoint * readMultiPointText (io::StringTokenizer *tokenizer)
geom::Polygon * readPolygonText (io::StringTokenizer *tokenizer)
geom::MultiLineString * readMultiLineStringText (io::StringTokenizer *tokenizer)
geom::MultiPolygon * readMultiPolygonText (io::StringTokenizer *tokenizer)
geom::GeometryCollection * readGeometryCollectionText (io::StringTokenizer *tokenizer)
Private Member Functions
void getPreciseCoordinate (io::StringTokenizer *tokenizer, geom::Coordinate &, std::size_t &dim)
bool isNumberNext (io::StringTokenizer *tokenizer)
Private Attributes
const geom::GeometryFactory * geometryFactory
const geom::PrecisionModel * precisionModel
Detailed Description
WKT parser class; see also WKTWriter.
Definition at line 58 of file WKTReader.h.
Constructor & Destructor Documentation
INLINE geos::io::WKTReader::WKTReader (const geom::GeometryFactory & gf)
Inizialize parser with given GeometryFactory.
Note that all Geometry objects created by the parser will contain a pointer to the given factory so be sure you'll keep the factory alive for the whole WKTReader and created Geometry life.
Definition at line 44 of file WKTReader.inl.
References INLINE.
   :
   geometryFactory(&gf),
   precisionModel(gf.getPrecisionModel())
 {
 #if GEOS_DEBUG
     std::cerr << "\nGEOS_DEBUG: WKTReader::WKTReader(const GeometryFactory &gf)\n";
 #endif
 }
INLINE geos::io::WKTReader::WKTReader (const geom::GeometryFactory * gf)
Deprecated:
in 3.4.0
Definition at line 33 of file WKTReader.inl.
References INLINE.
   :
   geometryFactory(gf),
   precisionModel(gf->getPrecisionModel())
 {
 #if GEOS_DEBUG
     std::cerr << "\nGEOS_DEBUG: WKTReader::WKTReader(const GeometryFactory *gf)\n";
 #endif
 }
INLINE geos::io::WKTReader::WKTReader ()
Inizialize parser with default GeometryFactory.
Definition at line 55 of file WKTReader.inl.
References INLINE.
   :
   geometryFactory(geom::GeometryFactory::getDefaultInstance()),
   precisionModel(geometryFactory->getPrecisionModel())
 {
 #if GEOS_DEBUG
     std::cerr << "\nGEOS_DEBUG: WKTReader::WKTReader()\n";
 #endif
 }
INLINE geos::io::WKTReader::~WKTReader ()
Definition at line 66 of file WKTReader.inl.
 {
 #if GEOS_DEBUG
     std::cerr << "\nGEOS_DEBUG: WKTReader::~WKTReader()\n";
 #endif
 }
Member Function Documentation
CoordinateSequence * geos::io::WKTReader::getCoordinates (io::StringTokenizer * tokenizer) protected
Definition at line 72 of file WKTReader.cpp.
References geos::geom::CoordinateSequence::add().
 {
   size_t dim;
   string nextToken=getNextEmptyOrOpener(tokenizer);
   if (nextToken=="EMPTY") {
     return geometryFactory->getCoordinateSequenceFactory()->create();
     //new CoordinateArraySequence();
   }
   Coordinate coord;
   getPreciseCoordinate(tokenizer, coord, dim);
   CoordinateSequence *coordinates = \
             geometryFactory->getCoordinateSequenceFactory()->create((size_t)0,dim);
   coordinates->add(coord);
   try {
     nextToken=getNextCloserOrComma(tokenizer);
     while (nextToken==",") {
       getPreciseCoordinate(tokenizer, coord, dim );
       coordinates->add(coord);
       nextToken=getNextCloserOrComma(tokenizer);
     }
   } catch (...) {
     delete coordinates;
     throw;
   }
   return coordinates;
 }
string geos::io::WKTReader::getNextCloser (io::StringTokenizer * tokenizer) protected
Definition at line 181 of file WKTReader.cpp.
 {
   string nextWord=getNextWord(tokenizer);
   if (nextWord==")") {
     return nextWord;
   }
   throw  ParseException("Expected ')' but encountered",nextWord);
 }
string geos::io::WKTReader::getNextCloserOrComma (io::StringTokenizer * tokenizer) protected
Definition at line 171 of file WKTReader.cpp.
 {
   string nextWord=getNextWord(tokenizer);
   if (nextWord=="," || nextWord==")") {
     return nextWord;
   }
   throw  ParseException("Expected ')' or ',' but encountered",nextWord);
 }
string geos::io::WKTReader::getNextEmptyOrOpener (io::StringTokenizer * tokenizer) protected
Definition at line 156 of file WKTReader.cpp.
 {
   string nextWord=getNextWord(tokenizer);
   // Skip the Z, M or ZM of an SF1.2 3/4 dim coordinate.
   if (nextWord == "Z" || nextWord == "M" || nextWord == "ZM" )
     nextWord = getNextWord(tokenizer);
   if (nextWord=="EMPTY" || nextWord=="(") {
     return nextWord;
   }
   throw  ParseException("Expected 'Z', 'M', 'ZM', 'EMPTY' or '(' but encountered ",nextWord);
 }
double geos::io::WKTReader::getNextNumber (io::StringTokenizer * tokenizer) protected
Definition at line 132 of file WKTReader.cpp.
References geos::io::StringTokenizer::getNVal(), geos::io::StringTokenizer::getSVal(), and geos::io::StringTokenizer::nextToken().
 {
   int type=tokenizer->nextToken();
   switch(type){
     case StringTokenizer::TT_EOF:
       throw  ParseException("Expected number but encountered end of stream");
     case StringTokenizer::TT_EOL:
       throw  ParseException("Expected number but encountered end of line");
     case StringTokenizer::TT_NUMBER:
       return tokenizer->getNVal();
     case StringTokenizer::TT_WORD:
       throw  ParseException("Expected number but encountered word",tokenizer->getSVal());
     case '(':
       throw  ParseException("Expected number but encountered '('");
     case ')':
       throw  ParseException("Expected number but encountered ')'");
     case ',':
       throw  ParseException("Expected number but encountered ','");
   }
   assert(0); // Encountered unexpected StreamTokenizer type
   return 0;
 }
string geos::io::WKTReader::getNextWord (io::StringTokenizer * tokenizer) protected
Definition at line 191 of file WKTReader.cpp.
References geos::io::StringTokenizer::getNVal(), geos::io::StringTokenizer::getSVal(), and geos::io::StringTokenizer::nextToken().
 {
   int type=tokenizer->nextToken();
   switch(type){
     case StringTokenizer::TT_EOF:
       throw  ParseException("Expected word but encountered end of stream");
     case StringTokenizer::TT_EOL:
       throw  ParseException("Expected word but encountered end of line");
     case StringTokenizer::TT_NUMBER:
       throw  ParseException("Expected word but encountered number", tokenizer->getNVal());
     case StringTokenizer::TT_WORD:
         {
             string word = tokenizer->getSVal();
             int i = static_cast<int>(word.size());
             while( --i >= 0 )
             {
                 word[i] = static_cast<char>(toupper(word[i]));
             }
       return word;
         }
     case '(':
       return "(";
     case ')':
       return ")";
     case ',':
       return ",";
   }
   assert(0);
   //throw  ParseException("Encountered unexpected StreamTokenizer type");
   return "";
 }
void geos::io::WKTReader::getPreciseCoordinate (io::StringTokenizer * tokenizer, geom::Coordinate & , std::size_t & dim) private
Definition at line 104 of file WKTReader.cpp.
References geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
 {
   coord.x=getNextNumber(tokenizer);
   coord.y=getNextNumber(tokenizer);
   if (isNumberNext(tokenizer)) {
     coord.z=getNextNumber(tokenizer);
     dim = 3;
         // If there is a fourth value (M) read and discard it.
         if (isNumberNext(tokenizer))
             getNextNumber(tokenizer);
   } else {
     coord.z=DoubleNotANumber;
     dim = 2;
   }
   precisionModel->makePrecise(coord);
 }
bool geos::io::WKTReader::isNumberNext (io::StringTokenizer * tokenizer) private
Definition at line 126 of file WKTReader.cpp.
References geos::io::StringTokenizer::peekNextToken().
 {
   return tokenizer->peekNextToken()==StringTokenizer::TT_NUMBER;
 }
Geometry * geos::io::WKTReader::read (const std::string & wellKnownText)
Parse a WKT string returning a Geometry.
Definition at line 61 of file WKTReader.cpp.
Referenced by GEOSGeomFromWKT_r(), and GEOSWKTReader_read_r().
 {
   //unique_ptr<StringTokenizer> tokenizer(new StringTokenizer(wellKnownText));
         CLocalizer clocale;
   StringTokenizer tokenizer(wellKnownText);
   Geometry *g=nullptr;
   g=readGeometryTaggedText(&tokenizer);
   return g;
 }
GeometryCollection * geos::io::WKTReader::readGeometryCollectionText (io::StringTokenizer * tokenizer) protected
Definition at line 458 of file WKTReader.cpp.
{
   string nextToken=getNextEmptyOrOpener(tokenizer);
   if (nextToken=="EMPTY") {
     return geometryFactory->createGeometryCollection(nullptr);
   }
   vector<Geometry *> *geoms=new vector<Geometry *>();
   Geometry *geom=nullptr;
   try {
     geom=readGeometryTaggedText(tokenizer);
     geoms->push_back(geom);
     geom=nullptr;
     nextToken=getNextCloserOrComma(tokenizer);
     while(nextToken==",") {
       geom=readGeometryTaggedText(tokenizer);
       geoms->push_back(geom);
       geom=nullptr;
       nextToken=getNextCloserOrComma(tokenizer);
     }
   } catch (...) {
     for (size_t i=0; i < geoms->size(); i++)
       delete (*geoms)[i];
     delete geoms;
     throw;
   }
   GeometryCollection *ret = geometryFactory->createGeometryCollection(geoms);
   //for (int i=0; i<geoms->size(); i++) delete (*geoms)[i];
   //delete geoms;
   return ret;
 }
Geometry * geos::io::WKTReader::readGeometryTaggedText (io::StringTokenizer * tokenizer) protected
Definition at line 225 of file WKTReader.cpp.
 {
   string type = getNextWord(tokenizer);
   if (type=="POINT") {
     return readPointText(tokenizer);
   } else if (type=="LINESTRING") {
     return readLineStringText(tokenizer);
   } else if (type=="LINEARRING") {
     return readLinearRingText(tokenizer);
   } else if (type=="POLYGON") {
     return readPolygonText(tokenizer);
   } else if (type=="MULTIPOINT") {
     return readMultiPointText(tokenizer);
   } else if (type=="MULTILINESTRING") {
     return readMultiLineStringText(tokenizer);
   } else if (type=="MULTIPOLYGON") {
     return readMultiPolygonText(tokenizer);
   } else if (type=="GEOMETRYCOLLECTION") {
     return readGeometryCollectionText(tokenizer);
   }
   throw  ParseException("Unknown type",type);
 }
LinearRing * geos::io::WKTReader::readLinearRingText (io::StringTokenizer * tokenizer) protected
Definition at line 270 of file WKTReader.cpp.
{
   CoordinateSequence *coords = getCoordinates(tokenizer);
   LinearRing *ret;
   ret = geometryFactory->createLinearRing(coords);
   return ret;
 }
LineString * geos::io::WKTReader::readLineStringText (io::StringTokenizer * tokenizer) protected
Definition at line 264 of file WKTReader.cpp.
{
   CoordinateSequence *coords = getCoordinates(tokenizer);
   LineString *ret = geometryFactory->createLineString(coords);
   return ret;
 }
MultiLineString * geos::io::WKTReader::readMultiLineStringText (io::StringTokenizer * tokenizer) protected
Definition at line 398 of file WKTReader.cpp.
{
   string nextToken=getNextEmptyOrOpener(tokenizer);
   if (nextToken=="EMPTY") {
     return geometryFactory->createMultiLineString(nullptr);
   }
   vector<Geometry *> *lineStrings=new vector<Geometry *>();
   LineString *lineString = nullptr;
   try {
     lineString=readLineStringText(tokenizer);
     lineStrings->push_back(lineString);
     lineString=nullptr;
     nextToken=getNextCloserOrComma(tokenizer);
     while(nextToken==",") {
       lineString=readLineStringText(tokenizer);
       lineStrings->push_back(lineString);
       lineString=nullptr;
       nextToken=getNextCloserOrComma(tokenizer);
     }
   } catch (...) {
     for (size_t i=0; i < lineStrings->size(); i++)
       delete (*lineStrings)[i];
     delete lineStrings;
     throw;
   }
   MultiLineString *ret = geometryFactory->createMultiLineString(lineStrings);
   //for (int i=0; i<lineStrings->size(); i++) delete (*lineStrings)[i];
   //delete lineStrings;
   return ret;
 }
MultiPoint * geos::io::WKTReader::readMultiPointText (io::StringTokenizer * tokenizer) protected
Definition at line 278 of file WKTReader.cpp.
References geos::geom::CoordinateSequence::add(), geos::geom::CoordinateSequenceFactory::create(), geos::io::StringTokenizer::getNVal(), geos::io::StringTokenizer::getSVal(), and geos::io::StringTokenizer::peekNextToken().
 {
   string nextToken=getNextEmptyOrOpener(tokenizer);
   if (nextToken=="EMPTY") {
     return geometryFactory->createMultiPoint();
   }
   int tok = tokenizer->peekNextToken();
   if ( tok == StringTokenizer::TT_NUMBER )
   {
     size_t dim;
     // Try to parse deprecated form "MULTIPOINT(0 0, 1 1)"
     const CoordinateSequenceFactory* csf = \
             geometryFactory->getCoordinateSequenceFactory();
     CoordinateSequence *coords = csf->create();
     try {
       do {
         Coordinate coord;
         getPreciseCoordinate(tokenizer, coord, dim);
         coords->add(coord);
         nextToken=getNextCloserOrComma(tokenizer);
       } while(nextToken == ",");
       MultiPoint *ret = geometryFactory->createMultiPoint(*coords);
       delete coords;
       return ret;
     } catch (...) {
       delete coords;
       throw;
     }
   }
   else if ( tok == '(' )
   {
     // Try to parse correct form "MULTIPOINT((0 0), (1 1))"
     vector<Geometry *> *points=new vector<Geometry *>();
     try {
       do {
         Point *point=readPointText(tokenizer);
         points->push_back(point);
         nextToken=getNextCloserOrComma(tokenizer);
       } while(nextToken == ",");
       return geometryFactory->createMultiPoint(points);
     } catch (...) {
       // clean up
       for (size_t i=0; i<points->size(); i++)
       {
         delete (*points)[i];
       }
       delete points;
       throw;
     }
   }
   else
   {
     stringstream err;
     err << "Unexpected token: ";
     switch (tok)
     {
       case StringTokenizer::TT_WORD:
         err << "WORD " << tokenizer->getSVal();
         break;
       case StringTokenizer::TT_NUMBER:
         err << "NUMBER " << tokenizer->getNVal();
         break;
       case StringTokenizer::TT_EOF:
       case StringTokenizer::TT_EOL:
         err << "EOF or EOL";
         break;
       case '(':
         err << "(";
         break;
       case ')':
         err << ")";
         break;
       case ',':
         err << ",";
         break;
       default:
         err << "??";
         break;
     }
     err << endl;
     throw ParseException(err.str());
   }
 }
MultiPolygon * geos::io::WKTReader::readMultiPolygonText (io::StringTokenizer * tokenizer) protected
Definition at line 428 of file WKTReader.cpp.
{
   string nextToken=getNextEmptyOrOpener(tokenizer);
   if (nextToken=="EMPTY") {
     return geometryFactory->createMultiPolygon(nullptr);
   }
   vector<Geometry *> *polygons=new vector<Geometry *>();
   Polygon *polygon = nullptr;
   try {
     polygon=readPolygonText(tokenizer);
     polygons->push_back(polygon);
     polygon=nullptr;
     nextToken=getNextCloserOrComma(tokenizer);
     while(nextToken==",") {
       polygon=readPolygonText(tokenizer);
       polygons->push_back(polygon);
       polygon=nullptr;
       nextToken=getNextCloserOrComma(tokenizer);
     }
   } catch (...) {
     for (size_t i=0; i < polygons->size(); i++)
       delete (*polygons)[i];
     delete polygons;
     throw;
   }
   MultiPolygon *ret = geometryFactory->createMultiPolygon(polygons);
   //for (int i=0; i<polygons->size(); i++) delete (*polygons)[i];
   //delete polygons;
   return ret;
 }
Point * geos::io::WKTReader::readPointText (io::StringTokenizer * tokenizer) protected
Definition at line 249 of file WKTReader.cpp.
 {
   size_t dim;
   string nextToken=getNextEmptyOrOpener(tokenizer);
   if (nextToken=="EMPTY") {
     return geometryFactory->createPoint(Coordinate::getNull());
   }
   Coordinate coord;
   getPreciseCoordinate(tokenizer, coord, dim);
   getNextCloser(tokenizer);
   return geometryFactory->createPoint(coord);
 }
Polygon * geos::io::WKTReader::readPolygonText (io::StringTokenizer * tokenizer) protected
Definition at line 369 of file WKTReader.cpp.
References poly.
 {
   Polygon *poly=nullptr;
   LinearRing *shell=nullptr;
   string nextToken=getNextEmptyOrOpener(tokenizer);
   if (nextToken=="EMPTY") {
     return geometryFactory->createPolygon(nullptr,nullptr);
   }
   vector<Geometry *> *holes=new vector<Geometry *>();
   try {
     shell=readLinearRingText(tokenizer);
     nextToken=getNextCloserOrComma(tokenizer);
     while(nextToken==",") {
       LinearRing *hole=readLinearRingText(tokenizer);
       holes->push_back(hole);
       nextToken=getNextCloserOrComma(tokenizer);
     }
     poly = geometryFactory->createPolygon(shell,holes);
   } catch (...) {
     for (unsigned int i=0; i<holes->size(); i++)
       delete (*holes)[i];
     delete holes;
     delete shell;
     throw;
   }
   return poly;
 }
Member Data Documentation
const geom::GeometryFactory* geos::io::WKTReader::geometryFactory private
Definition at line 105 of file WKTReader.h.
const geom::PrecisionModel* geos::io::WKTReader::precisionModel private
Definition at line 106 of file WKTReader.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/io/WKTReader.h
/home/vicky/potree/geos/vicky/src/io/WKTReader.cpp
/home/vicky/potree/geos/vicky/include/geos/io/WKTReader.inl