GEOS: geos::index::intervalrtree::SortedPackedIntervalRTree Class Reference
geos::index::intervalrtree::SortedPackedIntervalRTree Class Reference
A static index on a set of 1-dimensional intervals, using an R-Tree packed based on the order of the interval midpoints.
#include <SortedPackedIntervalRTree.h>
Public Member Functions
SortedPackedIntervalRTree ()
~SortedPackedIntervalRTree ()
void insert (double min, double max, void *item)
void query (double min, double max, index::ItemVisitor *visitor)
Private Member Functions
void init ()
void buildLevel (IntervalRTreeNode::ConstVect *src, IntervalRTreeNode::ConstVect *dest)
const IntervalRTreeNode * buildTree ()
Private Attributes
IntervalRTreeNode::ConstVect * leaves
const IntervalRTreeNode * root
int level
Detailed Description
A static index on a set of 1-dimensional intervals, using an R-Tree packed based on the order of the interval midpoints.
It supports range searching, where the range is an interval of the real line (which may be a single point). A common use is to index 1-dimensional intervals which are the projection of 2-D objects onto an axis of the coordinate system.
This index structure is static
items cannot be added or removed once the first query has been made. The advantage of this characteristic is that the index performance can be optimized based on a fixed set of items.
Author
Martin Davis
Definition at line 49 of file SortedPackedIntervalRTree.h.
Constructor & Destructor Documentation
geos::index::intervalrtree::SortedPackedIntervalRTree::SortedPackedIntervalRTree ()
Definition at line 104 of file SortedPackedIntervalRTree.cpp.
   :
   leaves( new IntervalRTreeNode::ConstVect()),
   root( nullptr),
   level( 0)
 { }
geos::index::intervalrtree::SortedPackedIntervalRTree::~SortedPackedIntervalRTree ()
Definition at line 111 of file SortedPackedIntervalRTree.cpp.
References leaves, and root.
 {
   if ( root != nullptr )
   {
     // deleting root cascades to all IntervalRTreeNode's
     delete root;
   }
   else // possibly IntervalRTreeNode's in leaves to delete
   {
     for ( size_t i = 0, ni = leaves->size(); i < ni; i++ )
       delete (*leaves)[i];
     delete leaves;
   }
 }
Member Function Documentation
void geos::index::intervalrtree::SortedPackedIntervalRTree::buildLevel (IntervalRTreeNode::ConstVect * src, IntervalRTreeNode::ConstVect * dest) private
Definition at line 72 of file SortedPackedIntervalRTree.cpp.
References level.
Referenced by buildTree().
 {
   level++;
   dest->clear();
   for (size_t i = 0, ni = src->size(); i < ni; i += 2)
   {
     const IntervalRTreeNode * n1 = (*src)[ i ];
     if ( i + 1 < ni )
     {
       const IntervalRTreeNode * n2 = (*src)[ i + 1 ];
       const IntervalRTreeNode * node = new IntervalRTreeBranchNode( n1, n2 );
       dest->push_back( node);
     }
     else
     {
       dest->push_back( n1);
     }
   }
 }
const IntervalRTreeNode * geos::index::intervalrtree::SortedPackedIntervalRTree::buildTree () private
Definition at line 43 of file SortedPackedIntervalRTree.cpp.
References buildLevel(), geos::index::intervalrtree::IntervalRTreeNode::compare(), and leaves.
Referenced by init().
 {
   // sort the leaf nodes
   std::sort( leaves->begin(), leaves->end(), IntervalRTreeNode::compare );
   // now group nodes into blocks of two and build tree up recursively
   IntervalRTreeNode::ConstVect * src = leaves;
   IntervalRTreeNode::ConstVect * dest = new IntervalRTreeNode::ConstVect();
   while (true)
   {
     buildLevel( src, dest);
     if (dest->size() == 1)
     {
       const IntervalRTreeNode * r = (*dest)[ 0 ];
       delete src;
       delete dest;
       //delete leaves; // don't need anymore
       return r;
     }
     IntervalRTreeNode::ConstVect * temp = src;
     src = dest;
     dest = temp;
   }
 }
void geos::index::intervalrtree::SortedPackedIntervalRTree::init (void) private
Definition at line 35 of file SortedPackedIntervalRTree.cpp.
References buildTree(), and root.
Referenced by query().
 {
   if (root != nullptr) return;
   root = buildTree();
 }
void geos::index::intervalrtree::SortedPackedIntervalRTree::insert (double min, double max, void * item)
Adds an item to the index which is associated with the given interval
Parameters
min the lower bound of the item interval
max the upper bound of the item interval
item the item to insert, ownership left to caller
Exceptions
IllegalStateException if the index has already been queried
Definition at line 129 of file SortedPackedIntervalRTree.cpp.
References leaves, and root.
Referenced by geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::addLine().
 {
   if (root != nullptr)
     throw new util::UnsupportedOperationException( "Index cannot be added to once it has been queried");
   leaves->push_back( new IntervalRTreeLeafNode( min, max, item));
 }
void geos::index::intervalrtree::SortedPackedIntervalRTree::query (double min, double max, index::ItemVisitor * visitor)
Search for intervals in the index which intersect the given closed interval and apply the visitor to them.
Parameters
min the lower bound of the query interval
max the upper bound of the query interval
visitor the visitor to pass any matched items to
Definition at line 138 of file SortedPackedIntervalRTree.cpp.
References init(), geos::index::intervalrtree::IntervalRTreeNode::query(), and root.
 {
   init();
   root->query( min, max, visitor);
 }
Member Data Documentation
IntervalRTreeNode::ConstVect* geos::index::intervalrtree::SortedPackedIntervalRTree::leaves private
Definition at line 52 of file SortedPackedIntervalRTree.h.
Referenced by buildTree(), insert(), and ~SortedPackedIntervalRTree().
int geos::index::intervalrtree::SortedPackedIntervalRTree::level private
Definition at line 54 of file SortedPackedIntervalRTree.h.
Referenced by buildLevel().
const IntervalRTreeNode* geos::index::intervalrtree::SortedPackedIntervalRTree::root private
Definition at line 53 of file SortedPackedIntervalRTree.h.
Referenced by init(), insert(), query(), and ~SortedPackedIntervalRTree().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/intervalrtree/SortedPackedIntervalRTree.h
/home/vicky/potree/geos/vicky/src/index/intervalrtree/SortedPackedIntervalRTree.cpp