GEOS: geos::algorithm::locate::IndexedPointInAreaLocator Class Reference
geos::algorithm::locate::IndexedPointInAreaLocator Class Reference
Determines the location of Coordinates relative to a Polygon or MultiPolygon geometry, using indexing for efficiency.
#include <IndexedPointInAreaLocator.h>
Classes
class IntervalIndexedGeometry
class SegmentVisitor
Public Member Functions
IndexedPointInAreaLocator (const geom::Geometry &g)
~IndexedPointInAreaLocator () override
int locate (const geom::Coordinate *p) override
Private Member Functions
void buildIndex (const geom::Geometry &g)
IndexedPointInAreaLocator (const IndexedPointInAreaLocator &other)=delete
IndexedPointInAreaLocator & operator= (const IndexedPointInAreaLocator &rhs)=delete
Private Attributes
const geom::Geometry & areaGeom
IntervalIndexedGeometry * index
Detailed Description
Determines the location of Coordinates relative to a Polygon or MultiPolygon geometry, using indexing for efficiency.
This algorithm is suitable for use in cases where many points will be tested against a given area.
Author
Martin Davis
Definition at line 55 of file IndexedPointInAreaLocator.h.
Constructor & Destructor Documentation
geos::algorithm::locate::IndexedPointInAreaLocator::IndexedPointInAreaLocator (const IndexedPointInAreaLocator & other) private delete
geos::algorithm::locate::IndexedPointInAreaLocator::IndexedPointInAreaLocator (const geom::Geometry & g)
Creates a new locator for a given Geometry
Parameters
g the Geometry to locate in
Definition at line 101 of file IndexedPointInAreaLocator.cpp.
References areaGeom, and buildIndex().
 : areaGeom( g)
 {
   if (  typeid( areaGeom) != typeid( geom::Polygon)
     &&  typeid( areaGeom) != typeid( geom::MultiPolygon) )
     throw new util::IllegalArgumentException("Argument must be Polygonal");
   //areaGeom = g;
   buildIndex( areaGeom);
 }
geos::algorithm::locate::IndexedPointInAreaLocator::~IndexedPointInAreaLocator () override
Definition at line 113 of file IndexedPointInAreaLocator.cpp.
References index.
 {
   delete index;
 }
Member Function Documentation
void geos::algorithm::locate::IndexedPointInAreaLocator::buildIndex (const geom::Geometry & g) private
Definition at line 88 of file IndexedPointInAreaLocator.cpp.
References geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::index.
Referenced by IndexedPointInAreaLocator().
 {
   index = new IndexedPointInAreaLocator::IntervalIndexedGeometry( g);
 }
int geos::algorithm::locate::IndexedPointInAreaLocator::locate (const geom::Coordinate * p) override virtual
Determines the Location of a point in an areal Geometry.
Parameters
p the point to test
Returns
the location of the point in the geometry
Implements geos::algorithm::locate::PointOnGeometryLocator.
Definition at line 119 of file IndexedPointInAreaLocator.cpp.
References geos::algorithm::RayCrossingCounter::getLocation(), index, geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::query(), and geos::geom::Coordinate::y.
 {
   algorithm::RayCrossingCounter rcc(*p);
   IndexedPointInAreaLocator::SegmentVisitor visitor( &rcc);
   index->query( p->y, p->y, &visitor);
   return rcc.getLocation();
 }
IndexedPointInAreaLocator& geos::algorithm::locate::IndexedPointInAreaLocator::operator= (const IndexedPointInAreaLocator & rhs) private delete
Member Data Documentation
const geom::Geometry& geos::algorithm::locate::IndexedPointInAreaLocator::areaGeom private
Definition at line 94 of file IndexedPointInAreaLocator.h.
Referenced by IndexedPointInAreaLocator().
IntervalIndexedGeometry* geos::algorithm::locate::IndexedPointInAreaLocator::index private
Definition at line 95 of file IndexedPointInAreaLocator.h.
Referenced by locate(), geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::query(), and ~IndexedPointInAreaLocator().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/locate/IndexedPointInAreaLocator.h
/home/vicky/potree/geos/vicky/src/algorithm/locate/IndexedPointInAreaLocator.cpp