GEOS: geos::triangulate::DelaunayTriangulationBuilder Class Reference
geos::triangulate::DelaunayTriangulationBuilder Class Reference
#include <DelaunayTriangulationBuilder.h>
Public Member Functions
DelaunayTriangulationBuilder ()
~DelaunayTriangulationBuilder ()
void setSites (const geom::Geometry &geom)
void setSites (const geom::CoordinateSequence &coords)
void setTolerance (double tolerance)
quadedge::QuadEdgeSubdivision & getSubdivision ()
std::unique_ptr< geom::MultiLineString > getEdges (const geom::GeometryFactory &geomFact)
std::unique_ptr< geom::GeometryCollection > getTriangles (const geom::GeometryFactory &geomFact)
Static Public Member Functions
static geom::CoordinateSequence * extractUniqueCoordinates (const geom::Geometry &geom)
static void unique (geom::CoordinateSequence &coords)
static IncrementalDelaunayTriangulator::VertexList * toVertices (const geom::CoordinateSequence &coords)
static geom::Envelope envelope (const geom::CoordinateSequence &coords)
Private Member Functions
void create ()
Private Attributes
geom::CoordinateSequence * siteCoords
double tolerance
quadedge::QuadEdgeSubdivision * subdiv
Detailed Description
A utility class which creates Delaunay Triangulations from collections of points and extract the resulting triangulation edges or triangles as geometries.
Author
JTS: Martin Davis
Benjamin Campbell
Definition at line 54 of file DelaunayTriangulationBuilder.h.
Constructor & Destructor Documentation
geos::triangulate::DelaunayTriangulationBuilder::DelaunayTriangulationBuilder ()
Creates a new triangulation builder.
Definition at line 67 of file DelaunayTriangulationBuilder.cpp.
                                                            :
   siteCoords(nullptr), tolerance(0.0), subdiv(nullptr)
 {
 }
geos::triangulate::DelaunayTriangulationBuilder::~DelaunayTriangulationBuilder ()
Definition at line 72 of file DelaunayTriangulationBuilder.cpp.
References siteCoords, and subdiv.
 {
   if(siteCoords)
     delete siteCoords;
   if(subdiv)
     delete subdiv;
 }
Member Function Documentation
void geos::triangulate::DelaunayTriangulationBuilder::create () private
Definition at line 100 of file DelaunayTriangulationBuilder.cpp.
References geos::geom::CoordinateSequence::expandEnvelope(), geos::triangulate::IncrementalDelaunayTriangulator::insertSites(), siteCoords, subdiv, tolerance, and toVertices().
Referenced by getEdges(), getSubdivision(), and getTriangles().
 {
   if(subdiv != nullptr || siteCoords == nullptr)
     return;
   Envelope siteEnv;
   siteCoords ->expandEnvelope(siteEnv);
   IncrementalDelaunayTriangulator::VertexList* vertices = toVertices(*siteCoords);
   subdiv = new quadedge::QuadEdgeSubdivision(siteEnv, tolerance);
   IncrementalDelaunayTriangulator triangulator = IncrementalDelaunayTriangulator(subdiv);
   triangulator.insertSites(*vertices);
   delete vertices;
 }
geom::Envelope geos::triangulate::DelaunayTriangulationBuilder::envelope (const geom::CoordinateSequence & coords) static
Computes the Envelope of a collection of Coordinates.
Parameters
coords a List of Coordinates
Returns
the envelope of the set of coordinates
Definition at line 138 of file DelaunayTriangulationBuilder.cpp.
References geos::geom::Envelope::expandToInclude(), and geos::geom::CoordinateSequence::toVector().
Referenced by geos::triangulate::VoronoiDiagramBuilder::create().
 {
   Envelope env;
   std::vector<Coordinate> coord_vector;
   coords.toVector(coord_vector);
   for(std::vector<Coordinate>::iterator it= coord_vector.begin() ; it!=coord_vector.end() ; ++it)
   {
     const Coordinate& coord = *it;
     env.expandToInclude(coord);
   }
   return env;
 }
CoordinateSequence * geos::triangulate::DelaunayTriangulationBuilder::extractUniqueCoordinates (const geom::Geometry & geom) static
Extracts the unique Coordinates from the given Geometry.
Parameters
geom the geometry to extract from
Returns
a List of the unique Coordinates. Caller takes ownership of the returned object.
Definition at line 35 of file DelaunayTriangulationBuilder.cpp.
References geos::geom::Geometry::getCoordinates().
Referenced by geos::triangulate::VoronoiDiagramBuilder::setSites(), and setSites().
 {
   geom::CoordinateSequence *coords = geom.getCoordinates();
   unique(*coords);
   return coords;
 }
std::unique_ptr< MultiLineString > geos::triangulate::DelaunayTriangulationBuilder::getEdges (const geom::GeometryFactory & geomFact)
Gets the edges of the computed triangulation as a MultiLineString.
Parameters
geomFact the geometry factory to use to create the output
Returns
the edges of the triangulation. The caller takes ownership of the returned object.
Definition at line 122 of file DelaunayTriangulationBuilder.cpp.
References create(), geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), and subdiv.
 {
   create();
   return subdiv->getEdges(geomFact);
 }
quadedge::QuadEdgeSubdivision & geos::triangulate::DelaunayTriangulationBuilder::getSubdivision ()
Gets the quadedge::QuadEdgeSubdivision which models the computed triangulation.
Returns
the subdivision containing the triangulation
Definition at line 115 of file DelaunayTriangulationBuilder.cpp.
References create(), and subdiv.
 {
   create();
   return *subdiv;
 }
std::unique_ptr< geom::GeometryCollection > geos::triangulate::DelaunayTriangulationBuilder::getTriangles (const geom::GeometryFactory & geomFact)
Gets the faces of the computed triangulation as a GeometryCollection of Polygon.
Parameters
geomFact the geometry factory to use to create the output
Returns
the faces of the triangulation. The caller takes ownership of the returned object.
Definition at line 130 of file DelaunayTriangulationBuilder.cpp.
References create(), geos::triangulate::quadedge::QuadEdgeSubdivision::getTriangles(), and subdiv.
 {
   create();
   return subdiv->getTriangles(geomFact);
 }
void geos::triangulate::DelaunayTriangulationBuilder::setSites (const geom::Geometry & geom)
Sets the sites (vertices) which will be triangulated. All vertices of the given geometry will be used as sites.
Parameters
geom the geometry from which the sites will be extracted.
Definition at line 81 of file DelaunayTriangulationBuilder.cpp.
References extractUniqueCoordinates(), and siteCoords.
 {
   if(siteCoords)
     delete siteCoords;
   // remove any duplicate points (they will cause the triangulation to fail)
   siteCoords = extractUniqueCoordinates(geom);
 }
void geos::triangulate::DelaunayTriangulationBuilder::setSites (const geom::CoordinateSequence & coords)
Sets the sites (vertices) which will be triangulated from a collection of Coordinates.
Parameters
geom a CoordinateSequence.
Definition at line 90 of file DelaunayTriangulationBuilder.cpp.
References geos::geom::CoordinateSequence::clone(), siteCoords, and unique().
 {
   if(siteCoords)
     delete siteCoords;
   siteCoords = coords.clone();
   // remove any duplicate points (they will cause the triangulation to fail)
   unique(*siteCoords);
 }
void geos::triangulate::DelaunayTriangulationBuilder::setTolerance (double tolerance) inline
Sets the snapping tolerance which will be used to improved the robustness of the triangulation computation. A tolerance of 0.0 specifies that no snapping will take place.
Parameters
tolerance the tolerance distance to use
Definition at line 110 of file DelaunayTriangulationBuilder.h.
Referenced by GEOSDelaunayTriangulation_r().
   {
     this->tolerance = tolerance;
   }
IncrementalDelaunayTriangulator::VertexList * geos::triangulate::DelaunayTriangulationBuilder::toVertices (const geom::CoordinateSequence & coords) static
Converts all Coordinates in a collection to Vertexes.
Parameters
coords the coordinates to convert
Returns
a List of Vertex objects. Call takes ownership of returned object.
Definition at line 54 of file DelaunayTriangulationBuilder.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::size().
Referenced by create(), and geos::triangulate::VoronoiDiagramBuilder::create().
 {
   IncrementalDelaunayTriangulator::VertexList* vertexList =
     new IncrementalDelaunayTriangulator::VertexList();
   for(size_t iter=0; iter < coords.size(); ++iter)
   {
     vertexList->push_back(quadedge::Vertex(coords.getAt(iter)));
   }
   return vertexList;
 }
void geos::triangulate::DelaunayTriangulationBuilder::unique (geom::CoordinateSequence & coords) static
Definition at line 44 of file DelaunayTriangulationBuilder.cpp.
References geos::geom::CoordinateSequence::removeRepeatedPoints(), geos::geom::CoordinateSequence::setPoints(), and geos::geom::CoordinateSequence::toVector().
Referenced by geos::triangulate::VoronoiDiagramBuilder::setSites(), and setSites().
 {
   std::vector<Coordinate> coordVector;
   coords.toVector(coordVector);
   std::sort(coordVector.begin(), coordVector.end(), geos::geom::CoordinateLessThen());
   coords.setPoints(coordVector);
   coords.removeRepeatedPoints();
 }
Member Data Documentation
geom::CoordinateSequence* geos::triangulate::DelaunayTriangulationBuilder::siteCoords private
Definition at line 74 of file DelaunayTriangulationBuilder.h.
Referenced by create(), setSites(), and ~DelaunayTriangulationBuilder().
quadedge::QuadEdgeSubdivision* geos::triangulate::DelaunayTriangulationBuilder::subdiv private
Definition at line 76 of file DelaunayTriangulationBuilder.h.
Referenced by create(), getEdges(), getSubdivision(), getTriangles(), and ~DelaunayTriangulationBuilder().
double geos::triangulate::DelaunayTriangulationBuilder::tolerance private
Definition at line 75 of file DelaunayTriangulationBuilder.h.
Referenced by create().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/triangulate/DelaunayTriangulationBuilder.h
/home/vicky/potree/geos/vicky/src/triangulate/DelaunayTriangulationBuilder.cpp