GEOS: geos::noding::SimpleNoder Class Reference
geos::noding::SimpleNoder Class Reference
Nodes a set of SegmentStrings by performing a brute-force comparison of every segment to every other one.
#include <SimpleNoder.h>
Public Member Functions
SimpleNoder (SegmentIntersector *nSegInt=nullptr)
void computeNodes (std::vector< SegmentString * > *inputSegmentStrings) override
std::vector< SegmentString * > * getNodedSubstrings () const override
virtual void setSegmentIntersector (SegmentIntersector *newSegInt)
Protected Attributes
SegmentIntersector * segInt
Externally owned.
Private Member Functions
virtual void computeIntersects (SegmentString *e0, SegmentString *e1)
Private Attributes
std::vector< SegmentString * > * nodedSegStrings
Detailed Description
Nodes a set of SegmentStrings by performing a brute-force comparison of every segment to every other one.
This has n^2 performance, so is too slow for use on large numbers of segments.
Version
1.7
Definition at line 51 of file SimpleNoder.h.
Constructor & Destructor Documentation
geos::noding::SimpleNoder::SimpleNoder (SegmentIntersector * nSegInt = nullptr) inline
Definition at line 57 of file SimpleNoder.h.
     :
     SinglePassNoder(nSegInt)
   {}
Member Function Documentation
void geos::noding::SimpleNoder::computeIntersects (SegmentString * e0, SegmentString * e1) private virtual
Definition at line 32 of file SimpleNoder.cpp.
References geos::noding::SegmentString::getCoordinates(), and geos::geom::CoordinateSequence::getSize().
 {
   assert(segInt); // must provide a segment intersector!
   const CoordinateSequence* pts0 = e0->getCoordinates();
   const CoordinateSequence* pts1 = e1->getCoordinates();
   for (unsigned int i0=0, n0=static_cast<unsigned int>(pts0->getSize()-1); i0<n0; i0++) {
     for (unsigned int i1=0, n1=static_cast<unsigned int>(pts1->getSize()-1); i1<n1; i1++) {
       segInt->processIntersections(e0, i0, e1, i1);
     }
   }
 }
void geos::noding::SimpleNoder::computeNodes (std::vector< SegmentString * > * segStrings) override virtual
Computes the noding for a collection of SegmentStrings.
Parameters
segStrings a collection of SegmentStrings to node
Implements geos::noding::SinglePassNoder.
Definition at line 48 of file SimpleNoder.cpp.
 {
   nodedSegStrings=inputSegmentStrings;
   for (SegmentString::NonConstVect::const_iterator
       i0=inputSegmentStrings->begin(), i0End=inputSegmentStrings->end();
       i0!=i0End; ++i0)
   {
     SegmentString* edge0 = *i0;
     for (SegmentString::NonConstVect::iterator
       i1=inputSegmentStrings->begin(), i1End=inputSegmentStrings->end();
       i1!=i1End; ++i1)
     {
             SegmentString* edge1 = *i1;
       computeIntersects(edge0, edge1);
     }
   }
 }
std::vector<SegmentString*>* geos::noding::SimpleNoder::getNodedSubstrings () const inline override virtual
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
Returns
a Collection of SegmentStrings
Implements geos::noding::SinglePassNoder.
Definition at line 64 of file SimpleNoder.h.
References geos::noding::NodedSegmentString::getNodedSubstrings().
{
     return NodedSegmentString::getNodedSubstrings(*nodedSegStrings);
   }
virtual void geos::noding::SinglePassNoder::setSegmentIntersector (SegmentIntersector * newSegInt) inline virtual inherited
Sets the SegmentIntersector to use with this noder. A SegmentIntersector will normally add intersection nodes to the input segment strings, but it may not - it may simply record the presence of intersections. However, some Noders may require that intersections be added.
Parameters
newSegInt
Definition at line 72 of file SinglePassNoder.h.
Referenced by geos::noding::FastNodingValidator::checkInteriorIntersections(), geos::noding::snapround::SimpleSnapRounder::findInteriorIntersections(), geos::noding::snapround::MCIndexSnapRounder::findInteriorIntersections(), and geos::noding::IteratedNoder::node().
{
     segInt = newSegInt;
   }
Member Data Documentation
std::vector<SegmentString*>* geos::noding::SimpleNoder::nodedSegStrings private
Definition at line 53 of file SimpleNoder.h.
SegmentIntersector* geos::noding::SinglePassNoder::segInt protected inherited
Externally owned.
Definition at line 55 of file SinglePassNoder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/SimpleNoder.h
/home/vicky/potree/geos/vicky/src/noding/SimpleNoder.cpp