GEOS: geos::noding::SegmentNode Class Reference
geos::noding::SegmentNode Class Reference
Represents an intersection point between two NodedSegmentString.
#include <SegmentNode.h>
Public Member Functions
SegmentNode (const NodedSegmentString &ss, const geom::Coordinate &nCoord, unsigned int nSegmentIndex, int nSegmentOctant)
Construct a node on the given NodedSegmentString.
~SegmentNode ()
bool isInterior () const
Return true if this Node is internal (not on the boundary) of the corresponding segment. Currently only the first segment endpoint is checked, actually.
bool isEndPoint (unsigned int maxSegmentIndex) const
int compareTo (const SegmentNode &other)
Public Attributes
geom::Coordinate coord
the point of intersection (own copy)
unsigned int segmentIndex
the index of the containing line segment in the parent edge
Private Member Functions
SegmentNode (const SegmentNode &other)=delete
SegmentNode & operator= (const SegmentNode &rhs)=delete
Private Attributes
const NodedSegmentString & segString
int segmentOctant
bool isInteriorVar
Friends
std::ostream & operator<< (std::ostream &os, const SegmentNode &n)
Detailed Description
Represents an intersection point between two NodedSegmentString.
Final class.
Definition at line 45 of file SegmentNode.h.
Constructor & Destructor Documentation
geos::noding::SegmentNode::SegmentNode (const SegmentNode & other) private delete
geos::noding::SegmentNode::SegmentNode (const NodedSegmentString & ss, const geom::Coordinate & nCoord, unsigned int nSegmentIndex, int nSegmentOctant)
Construct a node on the given NodedSegmentString.
Parameters
ss the parent NodedSegmentString
coord the coordinate of the intersection, will be copied
nSegmentIndex the index of the segment on parent NodedSegmentString where the Node is located.
nSegmentOctant
Definition at line 41 of file SegmentNode.cpp.
References coord, geos::geom::Coordinate::equals2D(), geos::noding::NodedSegmentString::getCoordinate(), isInteriorVar, segmentIndex, segString, and geos::noding::NodedSegmentString::size().
   :
   segString(ss),
   segmentOctant(nSegmentOctant),
   coord(nCoord),
   segmentIndex(nSegmentIndex)
 {
   // Number of points in NodedSegmentString is one-more number of segments
   assert(segmentIndex < segString.size() );
   isInteriorVar = \
     !coord.equals2D(segString.getCoordinate(segmentIndex));
 }
geos::noding::SegmentNode::~SegmentNode () inline
Definition at line 82 of file SegmentNode.h.
 {}
Member Function Documentation
int geos::noding::SegmentNode::compareTo (const SegmentNode & other)
Returns
-1 this EdgeIntersection is located before the argument location
0 this EdgeIntersection is at the argument location
1 this EdgeIntersection is located after the argument location
Definition at line 72 of file SegmentNode.cpp.
References geos::noding::SegmentPointComparator::compare(), coord, geos::geom::Coordinate::equals2D(), segmentIndex, and segmentOctant.
Referenced by geos::noding::SegmentNodeList::addSplitEdges(), and geos::noding::SegmentNodeLT::operator()().
 {
   if (segmentIndex < other.segmentIndex) return -1;
   if (segmentIndex > other.segmentIndex) return 1;
 #if GEOS_DEBUG
   cerr << setprecision(17) << "compareTo: " << *this << ", " << other <<endl;
 #endif
   if (coord.equals2D(other.coord)) {
 #if GEOS_DEBUG
     cerr << " Coordinates equal!"<<endl;
 #endif
     return 0;
   }
 #if GEOS_DEBUG
   cerr << " Coordinates do not equal!"<<endl;
 #endif
   return SegmentPointComparator::compare(segmentOctant, coord,
       other.coord);
 }
bool geos::noding::SegmentNode::isEndPoint (unsigned int maxSegmentIndex) const
Definition at line 59 of file SegmentNode.cpp.
References isInteriorVar, and segmentIndex.
 {
   if (segmentIndex == 0 && ! isInteriorVar) return true;
   if (segmentIndex == maxSegmentIndex) return true;
   return false;
 }
bool geos::noding::SegmentNode::isInterior () const inline
Return true if this Node is internal (not on the boundary) of the corresponding segment. Currently only the first segment endpoint is checked, actually.
Definition at line 89 of file SegmentNode.h.
References geos::noding::operator<<().
Referenced by geos::noding::SegmentNodeList::createSplitEdge(), and geos::noding::SegmentNodeList::findCollapseIndex().
 { return isInteriorVar; }
SegmentNode& geos::noding::SegmentNode::operator= (const SegmentNode & rhs) private delete
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const SegmentNode & n) friend
Member Data Documentation
geom::Coordinate geos::noding::SegmentNode::coord
the point of intersection (own copy)
Definition at line 61 of file SegmentNode.h.
Referenced by compareTo(), geos::noding::SegmentNodeList::createSplitEdge(), geos::noding::SegmentNodeList::findCollapseIndex(), geos::noding::operator<<(), SegmentNode(), and geos::noding::SegmentNodeList::~SegmentNodeList().
bool geos::noding::SegmentNode::isInteriorVar private
Definition at line 51 of file SegmentNode.h.
Referenced by isEndPoint(), and SegmentNode().
unsigned int geos::noding::SegmentNode::segmentIndex
the index of the containing line segment in the parent edge
Definition at line 64 of file SegmentNode.h.
Referenced by compareTo(), geos::noding::SegmentNodeList::createSplitEdge(), geos::noding::SegmentNodeList::findCollapseIndex(), isEndPoint(), geos::noding::operator<<(), and SegmentNode().
int geos::noding::SegmentNode::segmentOctant private
Definition at line 49 of file SegmentNode.h.
Referenced by compareTo(), and geos::noding::operator<<().
const NodedSegmentString& geos::noding::SegmentNode::segString private
Definition at line 47 of file SegmentNode.h.
Referenced by SegmentNode().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/SegmentNode.h
/home/vicky/potree/geos/vicky/src/noding/SegmentNode.cpp