GEOS: geos::geomgraph::EdgeEndStar Class Reference
geos::geomgraph::EdgeEndStar Class Reference abstract
A EdgeEndStar is an ordered list of EdgeEnds around a node.
#include <EdgeEndStar.h>
Public Types
typedef std::set< EdgeEnd *, EdgeEndLT > container
typedef container::iterator iterator
typedef container::const_iterator const_iterator
typedef container::reverse_iterator reverse_iterator
Public Member Functions
EdgeEndStar ()
virtual ~EdgeEndStar ()
virtual void insert (EdgeEnd *e)=0
Insert a EdgeEnd into this EdgeEndStar.
virtual geom::Coordinate & getCoordinate ()
const geom::Coordinate & getCoordinate () const
virtual std::size_t getDegree ()
virtual iterator begin ()
virtual iterator end ()
virtual reverse_iterator rbegin ()
virtual reverse_iterator rend ()
virtual const_iterator begin () const
virtual const_iterator end () const
virtual container & getEdges ()
virtual EdgeEnd * getNextCW (EdgeEnd *ee)
virtual void computeLabelling (std::vector< GeometryGraph * > *geomGraph)
virtual bool isAreaLabelsConsistent (const GeometryGraph &geomGraph)
virtual void propagateSideLabels (int geomIndex)
virtual iterator find (EdgeEnd *eSearch)
virtual std::string print () const
Protected Member Functions
virtual void insertEdgeEnd (EdgeEnd *e)
Insert an EdgeEnd into the map.
Protected Attributes
EdgeEndStar::container edgeMap
A map which maintains the edges in sorted order around the node.
Private Member Functions
virtual int getLocation (int geomIndex, const geom::Coordinate &p, std::vector< GeometryGraph * > *geom)
virtual void computeEdgeEndLabels (const algorithm::BoundaryNodeRule &)
virtual bool checkAreaLabelsConsistent (int geomIndex)
Private Attributes
int ptInAreaLocation [2]
The location of the point for this star in Geometry i Areas.
Detailed Description
A EdgeEndStar is an ordered list of EdgeEnds around a node.
They are maintained in CCW order (starting with the positive x-axis) around the node for efficient lookup and topology building.
Version
1.4
Definition at line 63 of file EdgeEndStar.h.
Member Typedef Documentation
typedef container::const_iterator geos::geomgraph::EdgeEndStar::const_iterator
Definition at line 69 of file EdgeEndStar.h.
typedef std::set<EdgeEnd *, EdgeEndLT> geos::geomgraph::EdgeEndStar::container
Definition at line 66 of file EdgeEndStar.h.
typedef container::iterator geos::geomgraph::EdgeEndStar::iterator
Definition at line 68 of file EdgeEndStar.h.
typedef container::reverse_iterator geos::geomgraph::EdgeEndStar::reverse_iterator
Definition at line 70 of file EdgeEndStar.h.
Constructor & Destructor Documentation
geos::geomgraph::EdgeEndStar::EdgeEndStar ()
Definition at line 46 of file EdgeEndStar.cpp.
References ptInAreaLocation.
   :
   edgeMap()
 {
   ptInAreaLocation[0]=Location::UNDEF;
   ptInAreaLocation[1]=Location::UNDEF;
 }
virtual geos::geomgraph::EdgeEndStar::~EdgeEndStar () inline virtual
Definition at line 74 of file EdgeEndStar.h.
 {}
Member Function Documentation
EdgeEndStar::iterator geos::geomgraph::EdgeEndStar::begin () inline virtual
Definition at line 161 of file EdgeEndStar.h.
Referenced by geos::operation::buffer::BufferSubgraph::add(), checkAreaLabelsConsistent(), geos::operation::buffer::BufferSubgraph::computeDepths(), computeEdgeEndLabels(), computeLabelling(), geos::operation::buffer::BufferSubgraph::computeNodeDepth(), getCoordinate(), getNextCW(), geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), geos::geomgraph::Node::isIncidentEdgeInResult(), geos::geomgraph::Node::Node(), geos::geomgraph::operator<<(), and propagateSideLabels().
 {
   return edgeMap.begin();
 }
virtual const_iterator geos::geomgraph::EdgeEndStar::begin () const inline virtual
Definition at line 102 of file EdgeEndStar.h.
 { return edgeMap.begin(); }
bool geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent (int geomIndex) private virtual
Definition at line 211 of file EdgeEndStar.cpp.
References begin(), edgeMap, end(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isArea(), geos::geomgraph::Position::LEFT, rbegin(), and geos::geomgraph::Position::RIGHT.
Referenced by isAreaLabelsConsistent().
 {
   // Since edges are stored in CCW order around the node,
   // As we move around the ring we move from the right to
   // the left side of the edge
   // if no edges, trivially consistent
   if (edgeMap.size()==0) return true;
   // initialize startLoc to location of last L side (if any)
   assert(*rbegin());
   const Label& startLabel = (*rbegin())->getLabel();
   int startLoc = startLabel.getLocation(geomIndex, Position::LEFT);
   // Found unlabelled area edge
   assert(startLoc!=Location::UNDEF);
   int currLoc=startLoc;
   for (EdgeEndStar::iterator it=begin(), itEnd=end(); it!=itEnd; ++it)
   {
     EdgeEnd *e=*it;
     assert(e);
     const Label& eLabel = e->getLabel();
     // we assume that we are only checking a area
     // Found non-area edge
     assert(eLabel.isArea(geomIndex));
     int leftLoc=eLabel.getLocation(geomIndex, Position::LEFT);
     int rightLoc=eLabel.getLocation(geomIndex, Position::RIGHT);
     // check that edge is really a boundary between inside and outside!
     if (leftLoc==rightLoc) {
       return false;
     }
     // check side location conflict
     //assert(rightLoc == currLoc); // "side location conflict " + locStr);
     if (rightLoc!=currLoc) {
       return false;
     }
     currLoc=leftLoc;
   }
   return true;
 }
void geos::geomgraph::EdgeEndStar::computeEdgeEndLabels (const algorithm::BoundaryNodeRule & boundaryNodeRule) private virtual
Definition at line 175 of file EdgeEndStar.cpp.
References begin(), geos::geomgraph::EdgeEnd::computeLabel(), and end().
Referenced by computeLabelling(), and isAreaLabelsConsistent().
 {
   // Compute edge label for each EdgeEnd
   for (EdgeEndStar::iterator it=begin(); it!=end(); ++it)
   {
     EdgeEnd *ee=*it;
     assert(ee);
     ee->computeLabel(boundaryNodeRule);
   }
 }
void geos::geomgraph::EdgeEndStar::computeLabelling (std::vector< GeometryGraph * > * geomGraph) virtual
If there are edges that still have null labels for a geometry this must be because there are no area edges for that geometry incident on this node. In this case, to label the edge for that geometry we must test whether the edge is in the interior of the geometry. To do this it suffices to determine whether the node for the edge is in the interior of an area. If so, the edge has location INTERIOR for the geometry. In all other cases (e.g. the node is on a line, on a point, or not on the geometry at all) the edge has the location EXTERIOR for the geometry.
Note that the edge cannot be on the BOUNDARY of the geometry, since then there would have been a parallel edge from the Geometry at this node also labelled BOUNDARY and this edge would have been labelled in the previous step.
This code causes a problem when dimensional collapses are present, since it may try and determine the location of a node where a dimensional collapse has occurred. The point should be considered to be on the EXTERIOR of the polygon, but locate() will return INTERIOR, since it is passed the original Geometry, not the collapsed version.
If there are incident edges which are Line edges labelled BOUNDARY, then they must be edges resulting from dimensional collapses. In this case the other edges can be labelled EXTERIOR for this Geometry.
MD 8/11/01 - NOT TRUE! The collapsed edges may in fact be in the interior of the Geometry, which means the other edges should be labelled INTERIOR for this Geometry. Not sure how solve this... Possibly labelling needs to be split into several phases: area label propagation, symLabel merging, then finally null label resolution.
Reimplemented in geos::geomgraph::DirectedEdgeStar.
Definition at line 87 of file EdgeEndStar.cpp.
References begin(), computeEdgeEndLabels(), end(), geos::geomgraph::EdgeEnd::getCoordinate(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), getLocation(), geos::geomgraph::Label::isAnyNull(), geos::geomgraph::Label::isLine(), propagateSideLabels(), and geos::geomgraph::Label::setAllLocationsIfNull().
Referenced by geos::operation::overlay::OverlayOp::computeLabelling(), and geos::operation::relate::RelateComputer::labelNodeEdges().
 {
   computeEdgeEndLabels((*geomGraph)[0]->getBoundaryNodeRule());
   // Propagate side labels  around the edges in the star
   // for each parent Geometry
   //
   // these calls can throw a TopologyException
   propagateSideLabels(0);
   propagateSideLabels(1);
   bool hasDimensionalCollapseEdge[2]={false,false};
   EdgeEndStar::iterator endIt=end();
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     EdgeEnd *e=*it;
     assert(e);
     const Label& label = e->getLabel();
     for(int geomi=0; geomi<2; geomi++)
     {
       if (label.isLine(geomi) && label.getLocation(geomi) == Location::BOUNDARY)
         hasDimensionalCollapseEdge[geomi]=true;
     }
   }
   for (EdgeEndStar::iterator it=begin(); it!=end(); ++it)
   {
     EdgeEnd *e=*it;
     assert(e);
     Label& label = e->getLabel();
     for(int geomi=0; geomi<2; ++geomi)
     {
       if (label.isAnyNull(geomi)) {
         int loc=Location::UNDEF;
         if (hasDimensionalCollapseEdge[geomi]){
           loc=Location::EXTERIOR;
         }else {
           Coordinate& p=e->getCoordinate();
           loc = getLocation(geomi, p, geomGraph);
         }
         label.setAllLocationsIfNull(geomi, loc);
       }
     }
   }
 }
EdgeEndStar::iterator geos::geomgraph::EdgeEndStar::end () inline virtual
Definition at line 179 of file EdgeEndStar.h.
Referenced by geos::operation::buffer::BufferSubgraph::add(), checkAreaLabelsConsistent(), geos::operation::buffer::BufferSubgraph::computeDepths(), computeEdgeEndLabels(), computeLabelling(), geos::operation::buffer::BufferSubgraph::computeNodeDepth(), getNextCW(), geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), geos::geomgraph::Node::isIncidentEdgeInResult(), geos::geomgraph::Node::Node(), geos::geomgraph::operator<<(), and propagateSideLabels().
 {
   return edgeMap.end();
 }
virtual const_iterator geos::geomgraph::EdgeEndStar::end () const inline virtual
Definition at line 104 of file EdgeEndStar.h.
 { return edgeMap.end(); }
EdgeEndStar::iterator geos::geomgraph::EdgeEndStar::find (EdgeEnd * eSearch) inline virtual
Definition at line 191 of file EdgeEndStar.h.
References geos::algorithm::operator<<().
Referenced by getNextCW().
 {
   return edgeMap.find(eSearch);
 }
Coordinate & geos::geomgraph::EdgeEndStar::getCoordinate () virtual
Returns
the coordinate for the node this star is based at or NULL if this is still an unbound star. Be aware that the returned pointer will point to a Coordinate owned by the specific EdgeEnd happening to be the first in the star (ordered CCW)
Definition at line 56 of file EdgeEndStar.cpp.
References begin(), edgeMap, and geos::geomgraph::EdgeEnd::getCoordinate().
Referenced by getCoordinate(), and geos::geomgraph::operator<<().
 {
   static Coordinate nullCoord(DoubleNotANumber, DoubleNotANumber, DoubleNotANumber);
   if (edgeMap.size()==0) return nullCoord;
   EdgeEndStar::iterator it=begin();
   EdgeEnd *e=*it;
   assert(e);
   return e->getCoordinate();
 }
const Coordinate & geos::geomgraph::EdgeEndStar::getCoordinate () const
Definition at line 69 of file EdgeEndStar.cpp.
References getCoordinate().
 {
   return const_cast<EdgeEndStar*>(this)->getCoordinate();
 }
std::size_t geos::geomgraph::EdgeEndStar::getDegree () inline virtual
Definition at line 155 of file EdgeEndStar.h.
Referenced by geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes().
 {
   return edgeMap.size();
 }
EdgeEndStar::container & geos::geomgraph::EdgeEndStar::getEdges () inline virtual
Definition at line 167 of file EdgeEndStar.h.
Referenced by geos::operation::overlay::OverlayOp::computeLabelling().
 {
   return edgeMap;
 }
int geos::geomgraph::EdgeEndStar::getLocation (int geomIndex, const geom::Coordinate & p, std::vector< GeometryGraph * > * geom) private virtual
Definition at line 189 of file EdgeEndStar.cpp.
References geos::algorithm::locate::SimplePointInAreaLocator::locate(), and ptInAreaLocation.
Referenced by computeLabelling().
 {
   // compute location only on demand
   if (ptInAreaLocation[geomIndex]==Location::UNDEF)
   {
     ptInAreaLocation[geomIndex]=algorithm::locate::SimplePointInAreaLocator::locate(p,
         (*geom)[geomIndex]->getGeometry());
   }
   return ptInAreaLocation[geomIndex];
 }
EdgeEnd * geos::geomgraph::EdgeEndStar::getNextCW (EdgeEnd * ee) virtual
Definition at line 76 of file EdgeEndStar.cpp.
References begin(), end(), and find().
 {
   EdgeEndStar::iterator it=find(ee);
   if ( it==end() ) return nullptr;
   if ( it==begin() ) { it=end(); --it; }
   else --it;
   return *it;
 }
virtual void geos::geomgraph::EdgeEndStar::insert (EdgeEnd * e) pure virtual
Insert a EdgeEnd into this EdgeEndStar.
Implemented in geos::geomgraph::DirectedEdgeStar, and geos::operation::relate::EdgeEndBundleStar.
Referenced by geos::geomgraph::Node::add().
virtual void geos::geomgraph::EdgeEndStar::insertEdgeEnd (EdgeEnd * e) inline protected virtual
Insert an EdgeEnd into the map.
Definition at line 134 of file EdgeEndStar.h.
 { edgeMap.insert(e); }
bool geos::geomgraph::EdgeEndStar::isAreaLabelsConsistent (const GeometryGraph & geomGraph) virtual
Definition at line 203 of file EdgeEndStar.cpp.
References checkAreaLabelsConsistent(), computeEdgeEndLabels(), and geos::geomgraph::GeometryGraph::getBoundaryNodeRule().
Referenced by geos::operation::valid::ConsistentAreaTester::isNodeEdgeAreaLabelsConsistent().
 {
   computeEdgeEndLabels(geomGraph.getBoundaryNodeRule());
   return checkAreaLabelsConsistent(0);
 }
std::string geos::geomgraph::EdgeEndStar::print () const virtual
Reimplemented in geos::geomgraph::DirectedEdgeStar.
Definition at line 347 of file EdgeEndStar.cpp.
 {
   std::ostringstream s;
   s << *this;
   return s.str();
 }
void geos::geomgraph::EdgeEndStar::propagateSideLabels (int geomIndex) virtual
RHS is null - LHS must be null too. This must be an edge from the other geometry, which has no location labelling for this geometry. This edge must lie wholly inside or outside the other geometry (which is determined by the current location). Assign both sides to be the current location.
Definition at line 259 of file EdgeEndStar.cpp.
References begin(), end(), geos::geomgraph::EdgeEnd::getCoordinate(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isArea(), geos::geomgraph::Position::LEFT, geos::geomgraph::Position::ON, geos::geomgraph::Position::RIGHT, and geos::geomgraph::Label::setLocation().
Referenced by computeLabelling().
 {
   // Since edges are stored in CCW order around the node,
   // As we move around the ring we move from the right to the
   // left side of the edge
   int startLoc=Location::UNDEF;
   EdgeEndStar::iterator beginIt=begin();
   EdgeEndStar::iterator endIt=end();
   EdgeEndStar::iterator it;
   // initialize loc to location of last L side (if any)
   for (EdgeEndStar::iterator it=beginIt; it!=endIt; ++it)
   {
     EdgeEnd *e=*it;
     assert(e);
     const Label& label = e->getLabel();
     if (label.isArea(geomIndex) &&
         label.getLocation(geomIndex,Position::LEFT) != Location::UNDEF)
     {
       startLoc = label.getLocation(geomIndex, Position::LEFT);
     }
   }
   // no labelled sides found, so no labels to propagate
   if (startLoc==Location::UNDEF) return;
   int currLoc=startLoc;
   for (it=beginIt; it!=endIt; ++it)
   {
     EdgeEnd *e=*it;
     assert(e);
     Label& label = e->getLabel();
     // set null ON values to be in current location
     if (label.getLocation(geomIndex,Position::ON) == Location::UNDEF)
     {
       label.setLocation(geomIndex,Position::ON,currLoc);
     }
     // set side labels (if any)
     // if (label.isArea())  //ORIGINAL
     if (label.isArea(geomIndex))
     {
       int leftLoc=label.getLocation(geomIndex,
         Position::LEFT);
       int rightLoc=label.getLocation(geomIndex,
         Position::RIGHT);
       // if there is a right location, that is the next
       // location to propagate
       if (rightLoc!=Location::UNDEF) {
         if (rightLoc!=currLoc)
           throw util::TopologyException("side location conflict",
             e->getCoordinate());
         if (leftLoc==Location::UNDEF) {
           // found single null side at e->getCoordinate()
           assert(0);
         }
         currLoc=leftLoc;
       } else {
         // found single null side
         assert(label.getLocation(geomIndex,
           Position::LEFT)==Location::UNDEF);
         label.setLocation(geomIndex,Position::RIGHT,
           currLoc);
         label.setLocation(geomIndex,Position::LEFT,
           currLoc);
       }
     }
   }
 }
EdgeEndStar::reverse_iterator geos::geomgraph::EdgeEndStar::rbegin () inline virtual
Definition at line 185 of file EdgeEndStar.h.
Referenced by checkAreaLabelsConsistent().
 {
   return edgeMap.rbegin();
 }
EdgeEndStar::reverse_iterator geos::geomgraph::EdgeEndStar::rend () inline virtual
Definition at line 173 of file EdgeEndStar.h.
 {
   return edgeMap.rend();
 }
Member Data Documentation
EdgeEndStar::container geos::geomgraph::EdgeEndStar::edgeMap protected
A map which maintains the edges in sorted order around the node.
Definition at line 129 of file EdgeEndStar.h.
Referenced by checkAreaLabelsConsistent(), and getCoordinate().
int geos::geomgraph::EdgeEndStar::ptInAreaLocation[2] private
The location of the point for this star in Geometry i Areas.
Definition at line 146 of file EdgeEndStar.h.
Referenced by EdgeEndStar(), and getLocation().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/EdgeEndStar.h
/home/vicky/potree/geos/vicky/src/geomgraph/EdgeEndStar.cpp