GEOS: geos::operation::overlay::validate::OverlayResultValidator Class Reference
geos::operation::overlay::validate::OverlayResultValidator Class Reference
Validates that the result of an overlay operation is geometrically correct within a determined tolerance.
#include <OverlayResultValidator.h>
Public Member Functions
OverlayResultValidator (const geom::Geometry &geom0, const geom::Geometry &geom1, const geom::Geometry &result)
bool isValid (OverlayOp::OpCode opCode)
geom::Coordinate & getInvalidLocation ()
Static Public Member Functions
static bool isValid (const geom::Geometry &geom0, const geom::Geometry &geom1, OverlayOp::OpCode opCode, const geom::Geometry &result)
Private Member Functions
void addTestPts (const geom::Geometry &g)
void addVertices (const geom::Geometry &g)
bool testValid (OverlayOp::OpCode overlayOp)
bool testValid (OverlayOp::OpCode overlayOp, const geom::Coordinate &pt)
bool isValidResult (OverlayOp::OpCode overlayOp, std::vector< geom::Location::Value > &location)
OverlayResultValidator (const OverlayResultValidator &other)=delete
OverlayResultValidator & operator= (const OverlayResultValidator &rhs)=delete
Static Private Member Functions
static double computeBoundaryDistanceTolerance (const geom::Geometry &g0, const geom::Geometry &g1)
Private Attributes
double boundaryDistanceTolerance
const geom::Geometry & g0
const geom::Geometry & g1
const geom::Geometry & gres
FuzzyPointLocator fpl0
FuzzyPointLocator fpl1
FuzzyPointLocator fplres
geom::Coordinate invalidLocation
std::vector< geom::Coordinate > testCoords
Detailed Description
Validates that the result of an overlay operation is geometrically correct within a determined tolerance.
Uses fuzzy point location to find points which are definitely in either the interior or exterior of the result geometry, and compares these results with the expected ones.
This algorithm is only useful where the inputs are polygonal.
This is a heuristic test, and may return false positive results (I.e. it may fail to detect an invalid result.) It should never return a false negative result, however (I.e. it should never report a valid result as invalid.)
See also
OverlayOp
Definition at line 64 of file OverlayResultValidator.h.
Constructor & Destructor Documentation
geos::operation::overlay::validate::OverlayResultValidator::OverlayResultValidator (const geom::Geometry & geom0, const geom::Geometry & geom1, const geom::Geometry & result)
Definition at line 89 of file OverlayResultValidator.cpp.
   :
   boundaryDistanceTolerance(
     computeBoundaryDistanceTolerance(geom0, geom1)
   ),
   g0(geom0),
   g1(geom1),
   gres(result),
   fpl0(g0, boundaryDistanceTolerance),
   fpl1(g1, boundaryDistanceTolerance),
   fplres(gres, boundaryDistanceTolerance),
   invalidLocation()
 {
 }
geos::operation::overlay::validate::OverlayResultValidator::OverlayResultValidator (const OverlayResultValidator & other) private delete
Member Function Documentation
void geos::operation::overlay::validate::OverlayResultValidator::addTestPts (const geom::Geometry & g) private
Definition at line 136 of file OverlayResultValidator.cpp.
References boundaryDistanceTolerance, geos::operation::overlay::validate::OffsetPointGenerator::getPoints(), and testCoords.
Referenced by isValid().
 {
   OffsetPointGenerator ptGen(g, 5 * boundaryDistanceTolerance);
   unique_ptr< vector<geom::Coordinate> > pts = ptGen.getPoints();
   testCoords.insert(testCoords.end(), pts->begin(), pts->end());
 }
void geos::operation::overlay::validate::OverlayResultValidator::addVertices (const geom::Geometry & g) private
Definition at line 145 of file OverlayResultValidator.cpp.
References geos::geom::Geometry::getCoordinates(), and testCoords.
 {
   // TODO: optimize this by not copying coordinates
   //       and pre-allocating memory
   unique_ptr<CoordinateSequence> cs ( g.getCoordinates() );
   const vector<Coordinate>* coords = cs->toVector();
   testCoords.insert(testCoords.end(), coords->begin(), coords->end());
 }
double geos::operation::overlay::validate::OverlayResultValidator::computeBoundaryDistanceTolerance (const geom::Geometry & g0, const geom::Geometry & g1) static private
Definition at line 219 of file OverlayResultValidator.cpp.
 {
     using geos::operation::overlay::snap::GeometrySnapper;
     return std::min(GeometrySnapper::computeSizeBasedSnapTolerance(g0),
                       GeometrySnapper::computeSizeBasedSnapTolerance(g1));
 }
geom::Coordinate& geos::operation::overlay::validate::OverlayResultValidator::getInvalidLocation () inline
Definition at line 81 of file OverlayResultValidator.h.
Referenced by geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), and isValid().
{
     return invalidLocation;
   }
bool geos::operation::overlay::validate::OverlayResultValidator::isValid (const geom::Geometry & geom0, const geom::Geometry & geom1, OverlayOp::OpCode opCode, const geom::Geometry & result) static
Definition at line 80 of file OverlayResultValidator.cpp.
References isValid().
Referenced by geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), isValid(), and isValidResult().
 {
   OverlayResultValidator validator(geom0, geom1, result);
   return validator.isValid(opCode);
 }
bool geos::operation::overlay::validate::OverlayResultValidator::isValid (OverlayOp::OpCode opCode)
Definition at line 109 of file OverlayResultValidator.cpp.
References addTestPts(), g0, g1, getInvalidLocation(), gres, testCoords, and testValid().
 {
   addTestPts(g0);
   addTestPts(g1);
   addTestPts(gres);
   if (! testValid(overlayOp) )
   {
 #if GEOS_DEBUG
   cerr << "OverlayResultValidator:" << endl
     << "Points:" << *toMultiPoint(testCoords) << endl
     << "Geom0: " << g0 << endl
     << "Geom1: " << g1 << endl
     << "Reslt: " << gres << endl
     << "Locat: " << getInvalidLocation()
     << endl;
 #endif
     return false;
   }
   return true;
 }
bool geos::operation::overlay::validate::OverlayResultValidator::isValidResult (OverlayOp::OpCode overlayOp, std::vector< geom::Location::Value > & location) private
Definition at line 204 of file OverlayResultValidator.cpp.
References geos::operation::overlay::OverlayOp::isResultOfOp(), and isValid().
Referenced by testValid().
 {
   bool expectedInterior = OverlayOp::isResultOfOp(location[0],
       location[1], overlayOp);
   bool resultInInterior = (location[2] == Location::INTERIOR);
   bool isValid = ! (expectedInterior ^ resultInInterior);
   return isValid;
 }
OverlayResultValidator& geos::operation::overlay::validate::OverlayResultValidator::operator= (const OverlayResultValidator & rhs) private delete
bool geos::operation::overlay::validate::OverlayResultValidator::testValid (OverlayOp::OpCode overlayOp) private
Definition at line 156 of file OverlayResultValidator.cpp.
References invalidLocation, and testCoords.
Referenced by isValid().
 {
   for (size_t i=0, n=testCoords.size(); i<n; ++i)
   {
     Coordinate& pt = testCoords[i];
     if (! testValid(overlayOp, pt)) {
       invalidLocation = pt;
       return false;
     }
   }
   return true;
 }
bool geos::operation::overlay::validate::OverlayResultValidator::testValid (OverlayOp::OpCode overlayOp, const geom::Coordinate & pt) private
Definition at line 171 of file OverlayResultValidator.cpp.
References fpl0, fpl1, fplres, geos::operation::overlay::validate::FuzzyPointLocator::getLocation(), and isValidResult().
 {
   std::vector<geom::Location::Value> location(3);
   location[0] = fpl0.getLocation(pt);
   location[1] = fpl1.getLocation(pt);
   location[2] = fplres.getLocation(pt);
 #if GEOS_DEBUG
   cerr << setprecision(10) << "Point " << pt << endl
     << "Loc0: " << location[0] << endl
     << "Loc1: " << location[1] << endl
     << "Locr: " << location[2] << endl;
 #endif
   /*
    * If any location is on the Boundary, can't deduce anything,
    * so just return true
    */
   if ( find(location.begin(), location.end(), Location::BOUNDARY) != location.end() )
   {
 #if GEOS_DEBUG
     cerr << "OverlayResultValidator: testpoint " << pt << " is on the boundary, blindly returning a positive answer (is valid)" << endl;
 #endif
     return true;
   }
   return isValidResult(overlayOp, location);
 }
Member Data Documentation
double geos::operation::overlay::validate::OverlayResultValidator::boundaryDistanceTolerance private
Definition at line 87 of file OverlayResultValidator.h.
Referenced by addTestPts().
FuzzyPointLocator geos::operation::overlay::validate::OverlayResultValidator::fpl0 private
Definition at line 95 of file OverlayResultValidator.h.
Referenced by testValid().
FuzzyPointLocator geos::operation::overlay::validate::OverlayResultValidator::fpl1 private
Definition at line 97 of file OverlayResultValidator.h.
Referenced by testValid().
FuzzyPointLocator geos::operation::overlay::validate::OverlayResultValidator::fplres private
Definition at line 99 of file OverlayResultValidator.h.
Referenced by testValid().
const geom::Geometry& geos::operation::overlay::validate::OverlayResultValidator::g0 private
Definition at line 89 of file OverlayResultValidator.h.
Referenced by isValid().
const geom::Geometry& geos::operation::overlay::validate::OverlayResultValidator::g1 private
Definition at line 91 of file OverlayResultValidator.h.
Referenced by isValid().
const geom::Geometry& geos::operation::overlay::validate::OverlayResultValidator::gres private
Definition at line 93 of file OverlayResultValidator.h.
Referenced by isValid().
geom::Coordinate geos::operation::overlay::validate::OverlayResultValidator::invalidLocation private
Definition at line 101 of file OverlayResultValidator.h.
Referenced by testValid().
std::vector<geom::Coordinate> geos::operation::overlay::validate::OverlayResultValidator::testCoords private
Definition at line 103 of file OverlayResultValidator.h.
Referenced by addTestPts(), addVertices(), isValid(), and testValid().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/validate/OverlayResultValidator.h
/home/vicky/potree/geos/vicky/src/operation/overlay/validate/OverlayResultValidator.cpp