GEOS: geos::operation::overlay::PolygonBuilder Class Reference
geos::operation::overlay::PolygonBuilder Class Reference
Forms Polygon out of a graph of geomgraph::DirectedEdge.
#include <PolygonBuilder.h>
Public Member Functions
PolygonBuilder (const geom::GeometryFactory *newGeometryFactory)
~PolygonBuilder ()
void add (geomgraph::PlanarGraph *graph)
void add (const std::vector< geomgraph::DirectedEdge * > *dirEdges, const std::vector< geomgraph::Node * > *nodes)
std::vector< geom::Geometry * > * getPolygons ()
bool containsPoint (const geom::Coordinate &p)
Checks the current set of shells (with their associated holes) to see if any of them contain the point.
Private Member Functions
void buildMaximalEdgeRings (const std::vector< geomgraph::DirectedEdge * > *dirEdges, std::vector< MaximalEdgeRing * > &maxEdgeRings)
void buildMinimalEdgeRings (std::vector< MaximalEdgeRing * > &maxEdgeRings, std::vector< geomgraph::EdgeRing * > &newShellList, std::vector< geomgraph::EdgeRing * > &freeHoleList, std::vector< MaximalEdgeRing * > &edgeRings)
geomgraph::EdgeRing * findShell (std::vector< MinimalEdgeRing * > *minEdgeRings)
void placePolygonHoles (geomgraph::EdgeRing *shell, std::vector< MinimalEdgeRing * > *minEdgeRings)
void sortShellsAndHoles (std::vector< MaximalEdgeRing * > &edgeRings, std::vector< geomgraph::EdgeRing * > &newShellList, std::vector< geomgraph::EdgeRing * > &freeHoleList)
void placeFreeHoles (std::vector< geomgraph::EdgeRing * > &newShellList, std::vector< geomgraph::EdgeRing * > &freeHoleList)
This method determines finds a containing shell for all holes which have not yet been assigned to a shell.
geomgraph::EdgeRing * findEdgeRingContaining (geomgraph::EdgeRing *testEr, std::vector< geomgraph::EdgeRing * > &newShellList)
Find the innermost enclosing shell geomgraph::EdgeRing containing the argument geomgraph::EdgeRing, if any.
std::vector< geom::Geometry * > * computePolygons (std::vector< geomgraph::EdgeRing * > &newShellList)
Private Attributes
const geom::GeometryFactory * geometryFactory
std::vector< geomgraph::EdgeRing * > shellList
Detailed Description
Forms Polygon out of a graph of geomgraph::DirectedEdge.
The edges to use are marked as being in the result Area.
Definition at line 61 of file PolygonBuilder.h.
Constructor & Destructor Documentation
geos::operation::overlay::PolygonBuilder::PolygonBuilder (const geom::GeometryFactory * newGeometryFactory)
Definition at line 52 of file PolygonBuilder.cpp.
   :
   geometryFactory(newGeometryFactory)
 {
 }
geos::operation::overlay::PolygonBuilder::~PolygonBuilder ()
Definition at line 58 of file PolygonBuilder.cpp.
References shellList.
 {
   for(size_t i=0, n=shellList.size(); i<n; ++i)
   {
     delete shellList[i];
   }
 }
Member Function Documentation
void geos::operation::overlay::PolygonBuilder::add (geomgraph::PlanarGraph * graph)
Add a complete graph. The graph is assumed to contain one or more polygons, possibly with holes.
Definition at line 68 of file PolygonBuilder.cpp.
References geos::geomgraph::PlanarGraph::getEdgeEnds(), geos::geomgraph::PlanarGraph::getNodeMap(), and geos::geomgraph::NodeMap::nodeMap.
Referenced by geos::operation::buffer::BufferBuilder::buildSubgraphs(), and geos::operation::overlay::OverlayOp::computeOverlay().
 {
   const vector<EdgeEnd*>* eeptr=graph->getEdgeEnds();
   assert(eeptr);
   const vector<EdgeEnd*>& ee = *eeptr;
   size_t eeSize=ee.size();
 #if GEOS_DEBUG
   cerr << __FUNCTION__ << ": PlanarGraph has " << eeSize << " EdgeEnds" << endl;
 #endif
   vector<DirectedEdge*> dirEdges(eeSize);
   for(size_t i=0; i<eeSize; ++i)
   {
     assert(dynamic_cast<DirectedEdge*>(ee[i]));
     DirectedEdge* de = static_cast<DirectedEdge*>(ee[i]);
     dirEdges[i]=de;
   }
   NodeMap::container &nodeMap=graph->getNodeMap()->nodeMap;
   vector<Node*> nodes;
   nodes.reserve(nodeMap.size());
   for ( NodeMap::iterator it=nodeMap.begin(), itEnd=nodeMap.end();
     it != itEnd; ++it )
   {
     Node *node=it->second;
     nodes.push_back(node);
   }
   add(&dirEdges, &nodes); // might throw a TopologyException *
 }
void geos::operation::overlay::PolygonBuilder::add (const std::vector< geomgraph::DirectedEdge * > * dirEdges, const std::vector< geomgraph::Node * > * nodes)
Add a set of edges and nodes, which form a graph. The graph is assumed to contain one or more polygons, possibly with holes.
Definition at line 104 of file PolygonBuilder.cpp.
References buildMaximalEdgeRings(), buildMinimalEdgeRings(), placeFreeHoles(), shellList, and sortShellsAndHoles().
 {
   PlanarGraph::linkResultDirectedEdges(nodes->begin(), nodes->end());
   vector<MaximalEdgeRing*> maxEdgeRings;
   buildMaximalEdgeRings(dirEdges, maxEdgeRings);
   vector<EdgeRing*> freeHoleList;
   vector<MaximalEdgeRing*> edgeRings;
   buildMinimalEdgeRings(maxEdgeRings, shellList, freeHoleList, edgeRings);
   sortShellsAndHoles(edgeRings, shellList, freeHoleList);
   placeFreeHoles(shellList, freeHoleList);
   //Assert: every hole on freeHoleList has a shell assigned to it
 }
void geos::operation::overlay::PolygonBuilder::buildMaximalEdgeRings (const std::vector< geomgraph::DirectedEdge * > * dirEdges, std::vector< MaximalEdgeRing * > & maxEdgeRings) private
For all DirectedEdges in result, form them into MaximalEdgeRings
Parameters
maxEdgeRings Formed MaximalEdgeRings will be pushed to this vector. Ownership of the elements is transferred to caller.
Definition at line 134 of file PolygonBuilder.cpp.
References geometryFactory, geos::geomgraph::DirectedEdge::getEdgeRing(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::isArea(), geos::geomgraph::DirectedEdge::isInResult(), geos::geomgraph::DirectedEdge::printEdge(), and geos::geomgraph::EdgeRing::setInResult().
Referenced by add().
 {
 #if GEOS_DEBUG
   cerr<<"PolygonBuilder::buildMaximalEdgeRings got "<<dirEdges->size()<<" dirEdges"<<endl;
 #endif
   vector<MaximalEdgeRing*>::size_type oldSize = maxEdgeRings.size();
   for(size_t i=0, n=dirEdges->size(); i<n; i++)
   {
     DirectedEdge *de=(*dirEdges)[i];
 #if GEOS_DEBUG
   cerr << "  dirEdge " << i << endl
        << de->printEdge() << endl
        << " inResult:" << de->isInResult() << endl
        << " isArea:" << de->getLabel().isArea() << endl;
 #endif
     if (de->isInResult() && de->getLabel().isArea())
     {
       // if this edge has not yet been processed
       if (de->getEdgeRing() == nullptr)
       {
         MaximalEdgeRing *er;
   try
   { // MaximalEdgeRing constructor may throw
         er=new MaximalEdgeRing(de,geometryFactory);
   }
   catch (util::GEOSException&)
   { // cleanup if that happens (see stmlf-cases-20061020.xml)
     for(size_t i=oldSize, n=maxEdgeRings.size(); i<n; i++)
       delete maxEdgeRings[i];
     //cerr << "Exception! " << e.what() << endl;
     throw;
   }
         maxEdgeRings.push_back(er);
         er->setInResult();
         //System.out.println("max node degree=" + er.getMaxDegree());
       }
     }
   }
 #if GEOS_DEBUG
   cerr<<"  pushed "<<maxEdgeRings.size()-oldSize<<" maxEdgeRings"<<endl;
 #endif
 }
void geos::operation::overlay::PolygonBuilder::buildMinimalEdgeRings (std::vector< MaximalEdgeRing * > & maxEdgeRings, std::vector< geomgraph::EdgeRing * > & newShellList, std::vector< geomgraph::EdgeRing * > & freeHoleList, std::vector< MaximalEdgeRing * > & edgeRings) private
Definition at line 183 of file PolygonBuilder.cpp.
References geos::operation::overlay::MaximalEdgeRing::buildMinimalRings(), findShell(), geos::geomgraph::EdgeRing::getMaxNodeDegree(), geos::operation::overlay::MaximalEdgeRing::linkDirectedEdgesForMinimalEdgeRings(), and placePolygonHoles().
Referenced by add().
 {
   for(size_t i=0, n=maxEdgeRings.size(); i<n; ++i)
   {
     MaximalEdgeRing *er = maxEdgeRings[i];
 #if GEOS_DEBUG
   cerr<<"buildMinimalEdgeRings: maxEdgeRing "<<i<<" has "<<er->getMaxNodeDegree()<<" maxNodeDegree"<<endl;
 #endif
     if (er->getMaxNodeDegree()>2)
     {
       er->linkDirectedEdgesForMinimalEdgeRings();
       vector<MinimalEdgeRing*> minEdgeRings;
       er->buildMinimalRings(minEdgeRings);
       // at this point we can go ahead and attempt to place
       // holes, if this EdgeRing is a polygon
       EdgeRing *shell=findShell(&minEdgeRings);
       if(shell != nullptr)
       {
         placePolygonHoles(shell, &minEdgeRings);
         newShellList.push_back(shell);
       }
       else
       {
         freeHoleList.insert(freeHoleList.end(),
             minEdgeRings.begin(),
             minEdgeRings.end() );
       }
       delete er;
     }
     else
     {
       edgeRings.push_back(er);
     }
   }
 }
vector< Geometry * > * geos::operation::overlay::PolygonBuilder::computePolygons (std::vector< geomgraph::EdgeRing * > & newShellList) private
Definition at line 366 of file PolygonBuilder.cpp.
References geometryFactory, poly, and geos::geomgraph::EdgeRing::toPolygon().
Referenced by getPolygons().
 {
 #if GEOS_DEBUG
   cerr<<"PolygonBuilder::computePolygons: got "<<newShellList.size()<<" shells"<<endl;
 #endif
   vector<Geometry*> *resultPolyList=new vector<Geometry*>();
   // add Polygons for all shells
   for(size_t i=0, n=newShellList.size(); i<n; i++)
   {
     EdgeRing *er=newShellList[i];
     Polygon *poly=er->toPolygon(geometryFactory);
     resultPolyList->push_back(poly);
   }
   return resultPolyList;
 }
bool geos::operation::overlay::PolygonBuilder::containsPoint (const geom::Coordinate & p)
Checks the current set of shells (with their associated holes) to see if any of them contain the point.
Definition at line 385 of file PolygonBuilder.cpp.
References geos::geomgraph::EdgeRing::containsPoint(), and shellList.
 {
   for(size_t i=0, size=shellList.size(); i<size; ++i)
   {
     EdgeRing *er=shellList[i];
     if ( er->containsPoint(p) )
     {
       return true;
     }
   }
   return false;
 }
EdgeRing * geos::operation::overlay::PolygonBuilder::findEdgeRingContaining (geomgraph::EdgeRing * testEr, std::vector< geomgraph::EdgeRing * > & newShellList) private
Find the innermost enclosing shell geomgraph::EdgeRing containing the argument geomgraph::EdgeRing, if any.
The innermost enclosing ring is the smallest enclosing ring. The algorithm used depends on the fact that:
ring A contains ring B iff envelope(ring A) contains envelope(ring B)
This routine is only safe to use if the chosen point of the hole is known to be properly contained in a shell (which is guaranteed to be the case if the hole does not touch its shell)
Returns
containing geomgraph::EdgeRing, if there is one
NULL if no containing geomgraph::EdgeRing is found
Definition at line 329 of file PolygonBuilder.cpp.
References geos::geom::Envelope::contains(), geos::geom::LineString::getCoordinateN(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getEnvelopeInternal(), and geos::geomgraph::EdgeRing::getLinearRing().
Referenced by placeFreeHoles().
 {
   LinearRing *testRing=testEr->getLinearRing();
   const Envelope *testEnv=testRing->getEnvelopeInternal();
   const Coordinate& testPt=testRing->getCoordinateN(0);
   EdgeRing *minShell=nullptr;
   const Envelope *minEnv=nullptr;
   for(size_t i=0, n=newShellList.size(); i<n; i++)
   {
     LinearRing *lr=nullptr;
     EdgeRing *tryShell=newShellList[i];
     LinearRing *tryRing=tryShell->getLinearRing();
     const Envelope *tryEnv=tryRing->getEnvelopeInternal();
     if (minShell!=nullptr) {
       lr=minShell->getLinearRing();
       minEnv=lr->getEnvelopeInternal();
     }
     bool isContained=false;
     const CoordinateSequence *rcl = tryRing->getCoordinatesRO();
     if (tryEnv->contains(testEnv)
       && CGAlgorithms::isPointInRing(testPt,rcl))
         isContained=true;
     // check if this new containing ring is smaller than
     // the current minimum ring
     if (isContained) {
       if (minShell==nullptr
         || minEnv->contains(tryEnv)) {
           minShell=tryShell;
       }
     }
   }
   return minShell;
 }
EdgeRing * geos::operation::overlay::PolygonBuilder::findShell (std::vector< MinimalEdgeRing * > * minEdgeRings) private
This method takes a list of MinimalEdgeRings derived from a MaximalEdgeRing, and tests whether they form a Polygon. This is the case if there is a single shell in the list. In this case the shell is returned. The other possibility is that they are a series of connected holes, in which case no shell is returned.
Returns
the shell geomgraph::EdgeRing, if there is one
NULL, if all the rings are holes
Definition at line 224 of file PolygonBuilder.cpp.
References geos::geomgraph::EdgeRing::isHole().
Referenced by buildMinimalEdgeRings().
 {
   int shellCount=0;
   EdgeRing *shell=nullptr;
 #if GEOS_DEBUG
   cerr<<"PolygonBuilder::findShell got "<<minEdgeRings->size()<<" minEdgeRings"<<endl;
 #endif
   for (size_t i=0, n=minEdgeRings->size(); i<n; ++i)
   {
     EdgeRing *er=(*minEdgeRings)[i];
     if ( ! er->isHole() )
     {
       shell=er;
       ++shellCount;
     }
   }
   if ( shellCount > 1 ) {
     throw util::TopologyException("found two shells in MinimalEdgeRing list");
   }
   return shell;
 }
vector< Geometry * > * geos::operation::overlay::PolygonBuilder::getPolygons ()
Definition at line 125 of file PolygonBuilder.cpp.
References computePolygons(), and shellList.
Referenced by geos::operation::buffer::BufferBuilder::buffer(), and geos::operation::overlay::OverlayOp::computeOverlay().
 {
   vector<Geometry*> *resultPolyList=computePolygons(shellList);
   return resultPolyList;
 }
void geos::operation::overlay::PolygonBuilder::placeFreeHoles (std::vector< geomgraph::EdgeRing * > & newShellList, std::vector< geomgraph::EdgeRing * > & freeHoleList) private
This method determines finds a containing shell for all holes which have not yet been assigned to a shell.
These "free" holes should all be properly contained in their parent shells, so it is safe to use the findEdgeRingContaining method. This is the case because any holes which are NOT properly contained (i.e. are connected to their parent shell) would have formed part of a MaximalEdgeRing and been handled in a previous step.
Exceptions
TopologyException if a hole cannot be assigned to a shell
Definition at line 285 of file PolygonBuilder.cpp.
References findEdgeRingContaining(), geometryFactory, geos::geomgraph::EdgeRing::getShell(), geos::geomgraph::EdgeRing::setShell(), and geos::geomgraph::EdgeRing::toPolygon().
Referenced by add().
 {
   for(std::vector<EdgeRing*>::iterator
       it=freeHoleList.begin(), itEnd=freeHoleList.end();
       it != itEnd;
       ++it)
   {
     EdgeRing *hole=*it;
     // only place this hole if it doesn't yet have a shell
     if (hole->getShell()==nullptr) {
       EdgeRing *shell=findEdgeRingContaining(hole, newShellList);
       if ( shell == nullptr )
       {
 #if GEOS_DEBUG
         Geometry* geom;
         std::cerr << "CREATE TABLE shells (g geometry);" << std::endl;
         std::cerr << "CREATE TABLE hole (g geometry);" << std::endl;
         for (std::vector<EdgeRing*>::iterator rIt=newShellList.begin(),
           rEnd=newShellList.end(); rIt!=rEnd; rIt++)
         {
           geom = (*rIt)->toPolygon(geometryFactory);
           std::cerr << "INSERT INTO shells VALUES ('"
                     << *geom
                     << "');" << std::endl;
           delete geom;
         }
         geom = hole->toPolygon(geometryFactory);
         std::cerr << "INSERT INTO hole VALUES ('"
                   << *geom
                   << "');" << std::endl;
         delete geom;
 #endif
         //assert(shell!=NULL); // unable to assign hole to a shell
         throw util::TopologyException("unable to assign hole to a shell");
       }
       hole->setShell(shell);
     }
   }
 }
void geos::operation::overlay::PolygonBuilder::placePolygonHoles (geomgraph::EdgeRing * shell, std::vector< MinimalEdgeRing * > * minEdgeRings) private
This method assigns the holes for a Polygon (formed from a list of MinimalEdgeRings) to its shell. Determining the holes for a MinimalEdgeRing polygon serves two purposes:
it is faster than using a point-in-polygon check later on.
it ensures correctness, since if the PIP test was used the point chosen might lie on the shell, which might return an incorrect result from the PIP test
Definition at line 252 of file PolygonBuilder.cpp.
References geos::geomgraph::EdgeRing::isHole(), and geos::geomgraph::EdgeRing::setShell().
Referenced by buildMinimalEdgeRings().
 {
   for (size_t i=0, n=minEdgeRings->size(); i<n; ++i)
   {
     MinimalEdgeRing *er=(*minEdgeRings)[i];
     if ( er->isHole() )
     {
       er->setShell(shell);
     }
   }
 }
void geos::operation::overlay::PolygonBuilder::sortShellsAndHoles (std::vector< MaximalEdgeRing * > & edgeRings, std::vector< geomgraph::EdgeRing * > & newShellList, std::vector< geomgraph::EdgeRing * > & freeHoleList) private
For all rings in the input list, determine whether the ring is a shell or a hole and add it to the appropriate list. Due to the way the DirectedEdges were linked, a ring is a shell if it is oriented CW, a hole otherwise.
Definition at line 267 of file PolygonBuilder.cpp.
References geos::geomgraph::EdgeRing::isHole().
Referenced by add().
 {
   for(size_t i=0, n=edgeRings.size(); i<n; i++)
   {
     EdgeRing *er = edgeRings[i];
     //er->setInResult();
     if (er->isHole() ) {
       freeHoleList.push_back(er);
     }
     else {
       newShellList.push_back(er);
     }
   }
 }
Member Data Documentation
const geom::GeometryFactory* geos::operation::overlay::PolygonBuilder::geometryFactory private
Definition at line 95 of file PolygonBuilder.h.
Referenced by buildMaximalEdgeRings(), computePolygons(), and placeFreeHoles().
std::vector<geomgraph::EdgeRing*> geos::operation::overlay::PolygonBuilder::shellList private
Definition at line 97 of file PolygonBuilder.h.
Referenced by add(), containsPoint(), getPolygons(), and ~PolygonBuilder().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/PolygonBuilder.h
/home/vicky/potree/geos/vicky/src/operation/overlay/PolygonBuilder.cpp