GEOS: geos::operation::predicate::EnvelopeIntersectsVisitor Class Reference
geos::operation::predicate::EnvelopeIntersectsVisitor Class Reference
Public Member Functions
EnvelopeIntersectsVisitor (const geom::Envelope &env)
bool intersects ()
void applyTo (const Geometry &geom)
Protected Member Functions
void visit (const geom::Geometry &element) override
bool isDone () override
Private Member Functions
EnvelopeIntersectsVisitor (const EnvelopeIntersectsVisitor &other)=delete
EnvelopeIntersectsVisitor & operator= (const EnvelopeIntersectsVisitor &rhs)=delete
Private Attributes
const geom::Envelope & rectEnv
bool intersectsVar
Detailed Description
Definition at line 46 of file RectangleIntersects.cpp.
Constructor & Destructor Documentation
geos::operation::predicate::EnvelopeIntersectsVisitor::EnvelopeIntersectsVisitor (const EnvelopeIntersectsVisitor & other) private delete
geos::operation::predicate::EnvelopeIntersectsVisitor::EnvelopeIntersectsVisitor (const geom::Envelope & env) inline
Definition at line 108 of file RectangleIntersects.cpp.
     :
     rectEnv(env),
     intersectsVar(false)
     {}
Member Function Documentation
void geos::geom::util::ShortCircuitedGeometryVisitor::applyTo (const Geometry & geom) inherited
Definition at line 31 of file ShortCircuitedGeometryVisitor.cpp.
References geos::geom::Geometry::getGeometryN(), and geos::geom::Geometry::getNumGeometries().
Referenced by geos::operation::predicate::RectangleIntersects::intersects().
 {
   for (std::size_t i=0, n=geom.getNumGeometries(); i<n; ++i)
   {
     const Geometry *element = geom.getGeometryN(i);
     if (dynamic_cast<const GeometryCollection*>(element))
     {
       applyTo(*element);
     }
     else
     {
       // calls the abstract virtual
       visit(*element);
       if (isDone()) done = true;
     }
     if ( done ) return;
   }
 }
bool geos::operation::predicate::EnvelopeIntersectsVisitor::intersects () inline
Definition at line 114 of file RectangleIntersects.cpp.
References intersectsVar.
Referenced by geos::operation::predicate::RectangleIntersects::intersects().
 { return intersectsVar; }
bool geos::operation::predicate::EnvelopeIntersectsVisitor::isDone () inline override protected virtual
Implements geos::geom::util::ShortCircuitedGeometryVisitor.
Definition at line 104 of file RectangleIntersects.cpp.
 { return intersectsVar==true; }
EnvelopeIntersectsVisitor& geos::operation::predicate::EnvelopeIntersectsVisitor::operator= (const EnvelopeIntersectsVisitor & rhs) private delete
Referenced by geos::operation::predicate::LineIntersectsVisitor::computeSegmentIntersection().
void geos::operation::predicate::EnvelopeIntersectsVisitor::visit (const geom::Geometry & element) inline override protected virtual
Reports whether it can be concluded that an intersection occurs, or whether further testing is required.
Returns
true if an intersection must occur false if no conclusion can be made
Implements geos::geom::util::ShortCircuitedGeometryVisitor.
Definition at line 66 of file RectangleIntersects.cpp.
References geos::geom::Envelope::contains(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), and geos::geom::Envelope::intersects().
   {
     const geom::Envelope &elementEnv = *(element.getEnvelopeInternal());
     // skip if envelopes do not intersect
     if ( ! rectEnv.intersects(elementEnv) ) return;
     // fully contained - must intersect
     if ( rectEnv.contains(elementEnv) ) {
       intersectsVar = true;
       return;
     }
     /*
      * Since the envelopes intersect and the test element is
      * connected, if the test envelope is completely bisected by
      * an edge of the rectangle the element and the rectangle
      * must touch (This is basically an application of the
      * Jordan Curve Theorem).  The alternative situation
      * is that the test envelope is "on a corner" of the
      * rectangle envelope, i.e. is not completely bisected.
      * In this case it is not possible to make a conclusion
      * about the presence of an intersection.
      */
     if (elementEnv.getMinX() >= rectEnv.getMinX()
       && elementEnv.getMaxX() <= rectEnv.getMaxX())
     {
       intersectsVar=true;
       return;
     }
     if (elementEnv.getMinY() >= rectEnv.getMinY()
       && elementEnv.getMaxY() <= rectEnv.getMaxY())
     {
       intersectsVar = true;
       return;
     }
   }
Member Data Documentation
bool geos::operation::predicate::EnvelopeIntersectsVisitor::intersectsVar private
Definition at line 51 of file RectangleIntersects.cpp.
Referenced by intersects(), geos::operation::predicate::LineIntersectsVisitor::intersects(), and geos::operation::predicate::LineIntersectsVisitor::isDone().
const geom::Envelope& geos::operation::predicate::EnvelopeIntersectsVisitor::rectEnv private
Definition at line 50 of file RectangleIntersects.cpp.
Referenced by geos::operation::predicate::RectangleIntersects::intersects().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/operation/predicate/RectangleIntersects.cpp