GEOS: geos::noding::FastSegmentSetIntersectionFinder Class Reference
geos::noding::FastSegmentSetIntersectionFinder Class Reference
Finds if two sets of SegmentStringss intersect.
#include <FastSegmentSetIntersectionFinder.h>
Public Member Functions
FastSegmentSetIntersectionFinder (SegmentString::ConstVect *baseSegStrings)
~FastSegmentSetIntersectionFinder ()
SegmentSetMutualIntersector * getSegmentSetIntersector ()
bool intersects (SegmentString::ConstVect *segStrings)
bool intersects (SegmentString::ConstVect *segStrings, SegmentIntersectionDetector *intDetector)
Private Attributes
MCIndexSegmentSetMutualIntersector * segSetMutInt
geos::algorithm::LineIntersector * lineIntersector
Detailed Description
Finds if two sets of SegmentStringss intersect.
Uses indexing for fast performance and to optimize repeated tests against a target set of lines. Short-circuited to return as soon an intersection is found.
Version
1.7
Definition at line 49 of file FastSegmentSetIntersectionFinder.h.
Constructor & Destructor Documentation
geos::noding::FastSegmentSetIntersectionFinder::FastSegmentSetIntersectionFinder (SegmentString::ConstVect * baseSegStrings)
Definition at line 41 of file FastSegmentSetIntersectionFinder.cpp.
References segSetMutInt, geos::noding::MCIndexSegmentSetMutualIntersector::setBaseSegments(), and ~FastSegmentSetIntersectionFinder().
 : segSetMutInt( new MCIndexSegmentSetMutualIntersector()),
   lineIntersector( new LineIntersector())
 {
   segSetMutInt->setBaseSegments( baseSegStrings);
 }
geos::noding::FastSegmentSetIntersectionFinder::~FastSegmentSetIntersectionFinder ()
Definition at line 49 of file FastSegmentSetIntersectionFinder.cpp.
References intersects(), lineIntersector, and segSetMutInt.
Referenced by FastSegmentSetIntersectionFinder().
 {
   delete lineIntersector;
   delete segSetMutInt;
 }
Member Function Documentation
SegmentSetMutualIntersector* geos::noding::FastSegmentSetIntersectionFinder::getSegmentSetIntersector () inline
Gets the segment set intersector used by this class. This allows other uses of the same underlying indexed structure.
Returns
the segment set intersector used
Definition at line 67 of file FastSegmentSetIntersectionFinder.h.
   {
     return segSetMutInt;
   }
bool geos::noding::FastSegmentSetIntersectionFinder::intersects (SegmentString::ConstVect * segStrings)
Definition at line 58 of file FastSegmentSetIntersectionFinder.cpp.
References lineIntersector.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections(), geos::geom::prep::PreparedLineStringIntersects::intersects(), geos::geom::prep::PreparedPolygonIntersects::intersects(), and ~FastSegmentSetIntersectionFinder().
 {
   SegmentIntersectionDetector intFinder( lineIntersector);
   return this->intersects( segStrings, &intFinder);
 }
bool geos::noding::FastSegmentSetIntersectionFinder::intersects (SegmentString::ConstVect * segStrings, SegmentIntersectionDetector * intDetector)
Definition at line 67 of file FastSegmentSetIntersectionFinder.cpp.
References geos::noding::SegmentIntersectionDetector::hasIntersection(), geos::noding::MCIndexSegmentSetMutualIntersector::process(), segSetMutInt, and geos::noding::SegmentSetMutualIntersector::setSegmentIntersector().
 {
   segSetMutInt->setSegmentIntersector( intDetector);
   segSetMutInt->process( segStrings);
   return intDetector->hasIntersection();
 }
Member Data Documentation
geos::algorithm::LineIntersector* geos::noding::FastSegmentSetIntersectionFinder::lineIntersector private
Definition at line 53 of file FastSegmentSetIntersectionFinder.h.
Referenced by intersects(), and ~FastSegmentSetIntersectionFinder().
MCIndexSegmentSetMutualIntersector* geos::noding::FastSegmentSetIntersectionFinder::segSetMutInt private
Definition at line 52 of file FastSegmentSetIntersectionFinder.h.
Referenced by FastSegmentSetIntersectionFinder(), intersects(), and ~FastSegmentSetIntersectionFinder().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/FastSegmentSetIntersectionFinder.h
/home/vicky/potree/geos/vicky/src/noding/FastSegmentSetIntersectionFinder.cpp