GEOS: geos::geomgraph::index::SimpleEdgeSetIntersector Class Reference
geos::geomgraph::index::SimpleEdgeSetIntersector Class Reference
#include <SimpleEdgeSetIntersector.h>
Public Member Functions
SimpleEdgeSetIntersector ()
void computeIntersections (std::vector< Edge * > *edges, SegmentIntersector *si, bool testAllSegments) override
void computeIntersections (std::vector< Edge * > *edges0, std::vector< Edge * > *edges1, SegmentIntersector *si) override
Private Member Functions
void computeIntersects (Edge *e0, Edge *e1, SegmentIntersector *si)
Private Attributes
int nOverlaps
Detailed Description
Definition at line 38 of file SimpleEdgeSetIntersector.h.
Constructor & Destructor Documentation
geos::geomgraph::index::SimpleEdgeSetIntersector::SimpleEdgeSetIntersector ()
Definition at line 30 of file SimpleEdgeSetIntersector.cpp.
                                                   :
   nOverlaps(0)
 {
 }
Member Function Documentation
void geos::geomgraph::index::SimpleEdgeSetIntersector::computeIntersections (std::vector< Edge * > * edges, SegmentIntersector * si, bool testAllSegments) override virtual
Computes all self-intersections between edges in a set of edges, allowing client to choose whether self-intersections are computed.
Parameters
edges a list of edges to test for intersections
si the SegmentIntersector to use
testAllSegments true if self-intersections are to be tested as well
Implements geos::geomgraph::index::EdgeSetIntersector.
Definition at line 36 of file SimpleEdgeSetIntersector.cpp.
References computeIntersects(), and nOverlaps.
 {
   nOverlaps = 0;
   size_t nedges=edges->size();
   for(size_t i0=0; i0<nedges; ++i0)
   {
     Edge *edge0=(*edges)[i0];
     for(size_t i1=0; i1<nedges; ++i1)
     {
       Edge *edge1=(*edges)[i1];
       if (testAllSegments || edge0!=edge1)
         computeIntersects(edge0,edge1,si);
     }
   }
 }
void geos::geomgraph::index::SimpleEdgeSetIntersector::computeIntersections (std::vector< Edge * > * edges0, std::vector< Edge * > * edges1, SegmentIntersector * si) override virtual
Computes all mutual intersections between two sets of edges
Implements geos::geomgraph::index::EdgeSetIntersector.
Definition at line 55 of file SimpleEdgeSetIntersector.cpp.
References computeIntersects(), and nOverlaps.
 {
   nOverlaps = 0;
   size_t nedges0=edges0->size();
   size_t nedges1=edges1->size();
   for(size_t i0=0;i0<nedges0; ++i0)
   {
     Edge *edge0=(*edges0)[i0];
     for(size_t i1=0; i1<nedges1; ++i1)
     {
       Edge *edge1=(*edges1)[i1];
       computeIntersects(edge0,edge1,si);
     }
   }
 }
void geos::geomgraph::index::SimpleEdgeSetIntersector::computeIntersects (Edge * e0, Edge * e1, SegmentIntersector * si) private
Performs a brute-force comparison of every segment in each Edge. This has n^2 performance, and is about 100 times slower than using monotone chains.
Definition at line 80 of file SimpleEdgeSetIntersector.cpp.
References geos::geomgraph::index::SegmentIntersector::addIntersections(), geos::geomgraph::Edge::getCoordinates(), and geos::geom::CoordinateSequence::getSize().
Referenced by computeIntersections().
 {
   const CoordinateSequence *pts0=e0->getCoordinates();
   const CoordinateSequence *pts1=e1->getCoordinates();
   auto npts0 = static_cast<int>(pts0->getSize());
   auto npts1 = static_cast<int>(pts1->getSize());
   for(int i0=0; i0<npts0-1; ++i0)
   {
     for(int i1=0; i1<npts1-1; ++i1)
     {
       si->addIntersections(e0, i0, e1, i1);
     }
   }
 }
Member Data Documentation
int geos::geomgraph::index::SimpleEdgeSetIntersector::nOverlaps private
Definition at line 52 of file SimpleEdgeSetIntersector.h.
Referenced by computeIntersections().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/index/SimpleEdgeSetIntersector.h
/home/vicky/potree/geos/vicky/src/geomgraph/index/SimpleEdgeSetIntersector.cpp