GEOS: geos::noding::MCIndexNoder Class Reference
geos::noding::MCIndexNoder Class Reference
Nodes a set of SegmentString using a index based on index::chain::MonotoneChain and a index::SpatialIndex.
#include <MCIndexNoder.h>
Classes
class SegmentOverlapAction
Public Member Functions
MCIndexNoder (SegmentIntersector *nSegInt=nullptr)
~MCIndexNoder () override
std::vector< index::chain::MonotoneChain * > & getMonotoneChains ()
Return a reference to this instance's std::vector of MonotoneChains.
index::SpatialIndex & getIndex ()
std::vector< SegmentString * > * getNodedSubstrings () const override
void computeNodes (std::vector< SegmentString * > *inputSegmentStrings) override
virtual void setSegmentIntersector (SegmentIntersector *newSegInt)
Protected Attributes
SegmentIntersector * segInt
Externally owned.
Private Member Functions
void intersectChains ()
void add (SegmentString *segStr)
Private Attributes
std::vector< index::chain::MonotoneChain * > monoChains
index::strtree::STRtree index
int idCounter
std::vector< SegmentString * > * nodedSegStrings
int nOverlaps
Detailed Description
Nodes a set of SegmentString using a index based on index::chain::MonotoneChain and a index::SpatialIndex.
The SpatialIndex used should be something that supports envelope (range) queries efficiently (such as a index::quadtree::Quadtree or index::strtree::STRtree.
Last port: noding/MCIndexNoder.java rev. 1.4 (JTS-1.7)
Definition at line 63 of file MCIndexNoder.h.
Constructor & Destructor Documentation
geos::noding::MCIndexNoder::MCIndexNoder (SegmentIntersector * nSegInt = nullptr) inline
Definition at line 79 of file MCIndexNoder.h.
     :
     SinglePassNoder(nSegInt),
     idCounter(0),
     nodedSegStrings(nullptr),
     nOverlaps(0)
   {}
geos::noding::MCIndexNoder::~MCIndexNoder () override
Definition at line 129 of file MCIndexNoder.cpp.
 {
   for(vector<MonotoneChain*>::iterator
       i=monoChains.begin(), iEnd=monoChains.end();
       i!=iEnd; ++i)
   {
     assert(*i);
     delete *i;
   }
 }
Member Function Documentation
void geos::noding::MCIndexNoder::add (SegmentString * segStr) private
Definition at line 106 of file MCIndexNoder.cpp.
References geos::noding::SegmentString::getCoordinates(), geos::index::chain::MonotoneChain::getEnvelope(), and geos::index::chain::MonotoneChain::setId().
 {
   vector<MonotoneChain*> segChains;
   // segChains will contain nelwy allocated MonotoneChain objects
   MonotoneChainBuilder::getChains(segStr->getCoordinates(),
       segStr, segChains);
   for(vector<MonotoneChain*>::iterator
       it=segChains.begin(), iEnd=segChains.end();
       it!=iEnd; ++it)
   {
     MonotoneChain* mc = *it;
     assert(mc);
     mc->setId(idCounter++);
     index.insert(&(mc->getEnvelope()), mc);
     // MonotoneChain objects deletion delegated to destructor
     monoChains.push_back(mc);
   }
 }
void geos::noding::MCIndexNoder::computeNodes (std::vector< SegmentString * > * segStrings) override virtual
Computes the noding for a collection of SegmentStrings.
Parameters
segStrings a collection of SegmentStrings to node
Implements geos::noding::SinglePassNoder.
Definition at line 46 of file MCIndexNoder.cpp.
Referenced by geos::noding::FastNodingValidator::checkInteriorIntersections(), geos::noding::snapround::SimpleSnapRounder::findInteriorIntersections(), geos::noding::snapround::MCIndexSnapRounder::findInteriorIntersections(), and geos::noding::IteratedNoder::node().
 {
   nodedSegStrings = inputSegStrings;
   assert(nodedSegStrings);
   for_each(nodedSegStrings->begin(), nodedSegStrings->end(),
       bind1st(mem_fun(&MCIndexNoder::add), this));
   intersectChains();
 //cerr<<"MCIndexNoder: # chain overlaps = "<<nOverlaps<<endl;
 }
INLINE index::SpatialIndex & geos::noding::MCIndexNoder::getIndex ()
Definition at line 32 of file MCIndexNoder.inl.
References index, and INLINE.
Referenced by geos::noding::snapround::MCIndexSnapRounder::computeNodes().
 {
   return index;
 }
std::vector<index::chain::MonotoneChain*>& geos::noding::MCIndexNoder::getMonotoneChains () inline
Return a reference to this instance's std::vector of MonotoneChains.
Definition at line 90 of file MCIndexNoder.h.
 { return monoChains; }
INLINE std::vector< SegmentString * > * geos::noding::MCIndexNoder::getNodedSubstrings () const override virtual
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
Returns
a Collection of SegmentStrings
Implements geos::noding::SinglePassNoder.
Definition at line 38 of file MCIndexNoder.inl.
References geos::noding::NodedSegmentString::getNodedSubstrings(), and nodedSegStrings.
Referenced by geos::noding::IteratedNoder::node().
 {
   assert(nodedSegStrings); // must have colled computeNodes before!
   return NodedSegmentString::getNodedSubstrings(*nodedSegStrings);
 }
void geos::noding::MCIndexNoder::intersectChains () private
following test makes sure we only compare each pair of chains once and that we don't compare a chain to itself
Definition at line 60 of file MCIndexNoder.cpp.
References geos::index::chain::MonotoneChain::computeOverlaps(), GEOS_CHECK_FOR_INTERRUPTS, geos::index::chain::MonotoneChain::getEnvelope(), and geos::index::chain::MonotoneChain::getId().
 {
   assert(segInt);
   SegmentOverlapAction overlapAction(*segInt);
   for (vector<MonotoneChain*>::iterator
       i=monoChains.begin(), iEnd=monoChains.end();
       i != iEnd;
       ++i)
   {
     GEOS_CHECK_FOR_INTERRUPTS();
     MonotoneChain* queryChain = *i;
     assert(queryChain);
     vector<void*> overlapChains;
     index.query(&(queryChain->getEnvelope()), overlapChains);
     for (vector<void*>::iterator
       j=overlapChains.begin(), jEnd=overlapChains.end();
       j != jEnd;
       ++j)
     {
       MonotoneChain* testChain = static_cast<MonotoneChain*>(*j);
       assert(testChain);
       if (testChain->getId() > queryChain->getId()) {
         queryChain->computeOverlaps(testChain,
             &overlapAction);
         nOverlaps++;
       }
       // short-circuit if possible
       if (segInt->isDone()) return;
     }
   }
 }
virtual void geos::noding::SinglePassNoder::setSegmentIntersector (SegmentIntersector * newSegInt) inline virtual inherited
Sets the SegmentIntersector to use with this noder. A SegmentIntersector will normally add intersection nodes to the input segment strings, but it may not - it may simply record the presence of intersections. However, some Noders may require that intersections be added.
Parameters
newSegInt
Definition at line 72 of file SinglePassNoder.h.
Referenced by geos::noding::FastNodingValidator::checkInteriorIntersections(), geos::noding::snapround::SimpleSnapRounder::findInteriorIntersections(), geos::noding::snapround::MCIndexSnapRounder::findInteriorIntersections(), and geos::noding::IteratedNoder::node().
{
     segInt = newSegInt;
   }
Member Data Documentation
int geos::noding::MCIndexNoder::idCounter private
Definition at line 68 of file MCIndexNoder.h.
index::strtree::STRtree geos::noding::MCIndexNoder::index private
Definition at line 67 of file MCIndexNoder.h.
Referenced by getIndex().
std::vector<index::chain::MonotoneChain*> geos::noding::MCIndexNoder::monoChains private
Definition at line 66 of file MCIndexNoder.h.
std::vector<SegmentString*>* geos::noding::MCIndexNoder::nodedSegStrings private
Definition at line 69 of file MCIndexNoder.h.
Referenced by getNodedSubstrings().
int geos::noding::MCIndexNoder::nOverlaps private
Definition at line 71 of file MCIndexNoder.h.
SegmentIntersector* geos::noding::SinglePassNoder::segInt protected inherited
Externally owned.
Definition at line 55 of file SinglePassNoder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/MCIndexNoder.h
/home/vicky/potree/geos/vicky/src/noding/MCIndexNoder.cpp
/home/vicky/potree/geos/vicky/include/geos/noding/MCIndexNoder.inl