GEOS: geos::simplify::TaggedLineSegment Class Reference
geos::simplify::TaggedLineSegment Class Reference
A geom::LineSegment which is tagged with its location in a geom::Geometry.
#include <TaggedLineSegment.h>
Public Member Functions
TaggedLineSegment (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Geometry *parent, unsigned int index)
TaggedLineSegment (const geom::Coordinate &p0, const geom::Coordinate &p1)
TaggedLineSegment (const TaggedLineSegment &ls)
const geom::Geometry * getParent () const
unsigned int getIndex () const
void setCoordinates (const Coordinate &c0, const Coordinate &c1)
void setCoordinates (const LineSegment &ls)
const Coordinate & operator[] (std::size_t i) const
Coordinate & operator[] (std::size_t i)
double getLength () const
Computes the length of the line segment.
bool isHorizontal () const
Tests whether the segment is horizontal.
bool isVertical () const
Tests whether the segment is vertical.
int orientationIndex (const LineSegment &seg) const
int orientationIndex (const LineSegment *seg) const
int orientationIndex (const Coordinate &p) const
Determines the orientation index of a Coordinate relative to this segment.
void reverse ()
Reverses the direction of the line segment.
void normalize ()
Puts the line segment into a normalized form.
double angle () const
void midPoint (Coordinate &ret) const
Computes the midpoint of the segment.
double distance (const LineSegment &ls) const
Computes the distance between this line segment and another one.
double distance (const Coordinate &p) const
Computes the distance between this line segment and a point.
double distancePerpendicular (const Coordinate &p) const
Computes the perpendicular distance between the (infinite) line defined by this line segment and a point.
void pointAlong (double segmentLengthFraction, Coordinate &ret) const
Computes the Coordinate that lies a given fraction along the line defined by this segment.
void pointAlongOffset (double segmentLengthFraction, double offsetDistance, Coordinate &ret) const
Computes the Coordinate that lies a given fraction along the line defined by this segment and offset from the segment by a given distance.
double projectionFactor (const Coordinate &p) const
Compute the projection factor for the projection of the point p onto this LineSegment.
double segmentFraction (const Coordinate &inputPt) const
Computes the fraction of distance (in [0.0, 1.0]) that the projection of a point occurs along this line segment.
void project (const Coordinate &p, Coordinate &ret) const
Compute the projection of a point onto the line determined by this line segment.
bool project (const LineSegment &seg, LineSegment &ret) const
Project a line segment onto this line segment and return the resulting line segment.
void closestPoint (const Coordinate &p, Coordinate &ret) const
Computes the closest point on this line segment to another point.
int compareTo (const LineSegment &other) const
Compares this object with the specified object for order.
bool equalsTopo (const LineSegment &other) const
Returns true if other is topologically equal to this LineSegment (e.g. irrespective of orientation).
CoordinateSequence * closestPoints (const LineSegment &line)
CoordinateSequence * closestPoints (const LineSegment *line)
bool intersection (const LineSegment &line, Coordinate &coord) const
bool lineIntersection (const LineSegment &line, Coordinate &ret) const
Computes the intersection point of the lines defined by two segments, if there is one.
std::unique_ptr< LineString > toGeometry (const GeometryFactory &gf) const
Public Attributes
Coordinate p0
Coordinate p1
Segment start.
Private Attributes
const geom::Geometry * parent
unsigned int index
Detailed Description
A geom::LineSegment which is tagged with its location in a geom::Geometry.
Used to index the segments in a geometry and recover the segment locations from the index.
Definition at line 54 of file TaggedLineSegment.h.
Constructor & Destructor Documentation
geos::simplify::TaggedLineSegment::TaggedLineSegment (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Geometry * parent, unsigned int index)
Definition at line 34 of file TaggedLineSegment.cpp.
   :
   LineSegment(p0, p1),
   parent(nParent),
   index(nIndex)
 {
 }
geos::simplify::TaggedLineSegment::TaggedLineSegment (const geom::Coordinate & p0, const geom::Coordinate & p1)
Definition at line 45 of file TaggedLineSegment.cpp.
   :
   LineSegment(p0, p1),
   parent(nullptr),
   index(0)
 {
 }
geos::simplify::TaggedLineSegment::TaggedLineSegment (const TaggedLineSegment & ls)
Definition at line 54 of file TaggedLineSegment.cpp.
   :
   LineSegment(ls),
   parent(ls.parent),
   index(ls.index)
 {
 }
Member Function Documentation
INLINE double geos::geom::LineSegment::angle () const inherited
Returns
the angle this segment makes with the x-axis (in radians)
Definition at line 168 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   return std::atan2(p1.y-p0.y,p1.x-p0.x);
 }
void geos::geom::LineSegment::closestPoint (const Coordinate & p, Coordinate & ret) const inherited
Computes the closest point on this line segment to another point.
Parameters
p the point to find the closest point to
ret the Coordinate to which the closest point on the line segment to the point p will be written
Definition at line 131 of file LineSegment.cpp.
Referenced by geos::geom::LineSegment::closestPoints(), geos::precision::MinimumClearance::compute(), and geos::algorithm::distance::DistanceToPoint::computeDistance().
 {
   double factor=projectionFactor(p);
   if (factor>0 && factor<1) {
     project(p, ret);
     return;
   }
   double dist0=p0.distance(p);
   double dist1=p1.distance(p);
   if (dist0<dist1)
   {
     ret=p0;
     return;
   }
   ret=p1;
 }
CoordinateSequence * geos::geom::LineSegment::closestPoints (const LineSegment & line) inherited
Computes the closest points on two line segments.
Parameters
p the point to find the closest point to
Returns
a pair of Coordinates which are the closest points on the line segments. The returned CoordinateSequence must be deleted by caller
Definition at line 181 of file LineSegment.cpp.
References geos::geom::LineSegment::closestPoint(), geos::geom::Coordinate::distance(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and geos::geom::CoordinateSequence::setAt().
Referenced by geos::geom::LineSegment::closestPoints().
 {
   // test for intersection
   Coordinate intPt;
   if ( intersection(line, intPt) )
   {
     CoordinateSequence *cl=new CoordinateArraySequence(new vector<Coordinate>(2, intPt));
     return cl;
   }
   /*
    * if no intersection closest pair contains at least one endpoint.
    * Test each endpoint in turn.
    */
   CoordinateSequence *closestPt=new CoordinateArraySequence(2);
   //vector<Coordinate> *cv = new vector<Coordinate>(2);
   double minDistance=DoubleMax;
   double dist;
   Coordinate close00;
   closestPoint(line.p0, close00);
   minDistance = close00.distance(line.p0);
   closestPt->setAt(close00, 0);
   closestPt->setAt(line.p0, 1);
   Coordinate close01;
   closestPoint(line.p1, close01);
   dist = close01.distance(line.p1);
   if (dist < minDistance) {
     minDistance = dist;
     closestPt->setAt(close01,0);
     closestPt->setAt(line.p1,1);
     //(*cv)[0] = close01;
     //(*cv)[1] = line.p1;
   }
   Coordinate close10;
   line.closestPoint(p0, close10);
   dist = close10.distance(p0);
     if (dist < minDistance) {
     minDistance = dist;
     closestPt->setAt(p0,0);
     closestPt->setAt(close10,1);
     //(*cv)[0] = p0;
     //(*cv)[1] = close10;
   }
   Coordinate close11;
   line.closestPoint(p1, close11);
   dist = close11.distance(p1);
   if (dist < minDistance) {
     minDistance = dist;
     closestPt->setAt(p1,0);
     closestPt->setAt(close11,1);
     //(*cv)[0] = p1;
     //(*cv)[1] = *close11;
   }
   return closestPt;
 }
INLINE CoordinateSequence * geos::geom::LineSegment::closestPoints (const LineSegment * line) inherited
Definition at line 161 of file LineSegment.inl.
References geos::geom::LineSegment::closestPoints(), and INLINE.
 {
   assert(line);
   return closestPoints(*line);
 }
int geos::geom::LineSegment::compareTo (const LineSegment & other) const inherited
Compares this object with the specified object for order.
Uses the standard lexicographic ordering for the points in the LineSegment.
Parameters
o the LineSegment with which this LineSegment is being compared
Returns
a negative integer, zero, or a positive integer as this LineSegment is less than, equal to, or greater than the specified LineSegment
Definition at line 150 of file LineSegment.cpp.
References geos::geom::Coordinate::compareTo(), geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   int comp0=p0.compareTo(other.p0);
   if (comp0!=0) return comp0;
   return p1.compareTo(other.p1);
 }
INLINE double geos::geom::LineSegment::distance (const LineSegment & ls) const inherited
Computes the distance between this line segment and another one.
Definition at line 82 of file LineSegment.inl.
References geos::algorithm::CGAlgorithms::distanceLineLine(), INLINE, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by geos::operation::overlay::snap::LineStringSnapper::findSegmentToSnap(), geos::linearref::LocationIndexOfPoint::indexOfFromStart(), geos::linearref::LengthIndexOfPoint::indexOfFromStart(), geos::triangulate::quadedge::QuadEdgeSubdivision::isOnEdge(), geos::simplify::DouglasPeuckerLineSimplifier::simplifySection(), and geos::operation::overlay::snap::LineStringSnapper::snapSegments().
 {
   return algorithm::CGAlgorithms::distanceLineLine(p0, p1, ls.p0, ls.p1);
 }
INLINE double geos::geom::LineSegment::distance (const Coordinate & p) const inherited
Computes the distance between this line segment and a point.
Definition at line 89 of file LineSegment.inl.
References geos::algorithm::CGAlgorithms::distancePointLine(), INLINE, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   return algorithm::CGAlgorithms::distancePointLine(p, p0, p1);
 }
INLINE double geos::geom::LineSegment::distancePerpendicular (const Coordinate & p) const inherited
Computes the perpendicular distance between the (infinite) line defined by this line segment and a point.
Definition at line 68 of file LineSegment.inl.
References geos::algorithm::CGAlgorithms::distancePointLinePerpendicular(), INLINE, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by geos::algorithm::MinimumDiameter::findMaxPerpDistance().
 {
   return algorithm::CGAlgorithms::distancePointLinePerpendicular(p, p0, p1);
 }
bool geos::geom::LineSegment::equalsTopo (const LineSegment & other) const inherited
Returns true if other is topologically equal to this LineSegment (e.g. irrespective of orientation).
Parameters
other a LineSegment with which to do the comparison.
Returns
true if other is a LineSegment with the same values for the x and y ordinates.
Definition at line 159 of file LineSegment.cpp.
References geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   return (p0==other.p0 && p1==other.p1) || (p0==other.p1 && p1==other.p0);
 }
unsigned int geos::simplify::TaggedLineSegment::getIndex () const
Definition at line 69 of file TaggedLineSegment.cpp.
References index.
Referenced by geos::simplify::TaggedLineStringSimplifier::isInLineSection().
 {
   return index;
 }
INLINE double geos::geom::LineSegment::getLength () const inherited
Computes the length of the line segment.
Definition at line 130 of file LineSegment.inl.
References geos::geom::Coordinate::distance(), INLINE, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by geos::linearref::LengthIndexOfPoint::indexOfFromStart(), and geos::linearref::LengthIndexOfPoint::segmentNearestMeasure().
 {
   return p0.distance(p1);
 }
const geom::Geometry * geos::simplify::TaggedLineSegment::getParent () const
Definition at line 63 of file TaggedLineSegment.cpp.
References parent.
Referenced by geos::simplify::TaggedLineStringSimplifier::isInLineSection().
 {
   return parent;
 }
bool geos::geom::LineSegment::intersection (const LineSegment & line, Coordinate & coord) const inherited
Computes an intersection point between two segments, if there is one. There may be 0, 1 or many intersection points between two segments. If there are 0, null is returned. If there is 1 or more, a single one is returned (chosen at the discretion of the algorithm). If more information is required about the details of the intersection, the LineIntersector class should be used.
Parameters
line
coord the Coordinate to write the result into
Returns
true if an intersection was found, false otherwise
Definition at line 245 of file LineSegment.cpp.
References geos::algorithm::LineIntersector::computeIntersection(), geos::algorithm::LineIntersector::getIntersection(), geos::algorithm::LineIntersector::hasIntersection(), geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by GEOSSegmentIntersection_r().
 {
   algorithm::LineIntersector li;
   li.computeIntersection(p0, p1, line.p0, line.p1);
   if (li.hasIntersection()) {
     ret=li.getIntersection(0);
     return true;
   }
   return false;
 }
INLINE bool geos::geom::LineSegment::isHorizontal () const inherited
Tests whether the segment is horizontal.
Returns
true if the segment is horizontal
Definition at line 136 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and geos::geom::Coordinate::y.
 {
   return p0.y == p1.y;
 }
INLINE bool geos::geom::LineSegment::isVertical () const inherited
Tests whether the segment is vertical.
Returns
true if the segment is vertical
Definition at line 142 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and geos::geom::Coordinate::x.
 {
   return p0.x == p1.x;
 }
bool geos::geom::LineSegment::lineIntersection (const LineSegment & line, Coordinate & ret) const inherited
Computes the intersection point of the lines defined by two segments, if there is one.
There may be 0, 1 or an infinite number of intersection points between two lines. If there is a unique intersection point, it is returned. Otherwise, null is returned. If more information is required about the details of the intersection, the algorithms::LineIntersector class should be used.
Parameters
line a line segment defining a straight line
ret will be set to the intersection point (if any)
Returns
true if an intersection was found, false otherwise
Definition at line 257 of file LineSegment.cpp.
References geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by geos::algorithm::MinimumDiameter::getMinimumRectangle().
 {
   try {
     HCoordinate::intersection(p0, p1, line.p0, line.p1, ret);
     return true;
   }
   catch (const NotRepresentableException& /*ex*/) {
     // eat this exception, and return null;
   }
   return false;
 }
INLINE void geos::geom::LineSegment::midPoint (Coordinate & ret) const inherited
Computes the midpoint of the segment.
Parameters
ret will be set to the midpoint of the segment
Definition at line 174 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   ret = Coordinate( (p0.x + p1.x) / 2,
                     (p0.y + p1.y) / 2 );
 }
INLINE void geos::geom::LineSegment::normalize (void) inherited
Puts the line segment into a normalized form.
This is useful for using line segments in maps and indexes when topological equality rather than exact equality is desired.
Definition at line 95 of file LineSegment.inl.
References geos::geom::Coordinate::compareTo(), INLINE, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and geos::geom::LineSegment::reverse().
 {
   if (p1.compareTo(p0)<0) reverse();
 }
INLINE const Coordinate & geos::geom::LineSegment::operator[] (std::size_t i) const inherited
Definition at line 108 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   if (i==0) return p0;
   assert(i==1);
   return p1;
 }
INLINE Coordinate & geos::geom::LineSegment::operator[] (std::size_t i) inherited
Definition at line 116 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   if (i==0) return p0;
   assert(i==1);
   return p1;
 }
int geos::geom::LineSegment::orientationIndex (const LineSegment & seg) const inherited
Determines the orientation of a LineSegment relative to this segment. The concept of orientation is specified as follows: Given two line segments A and L, <ul A is to the left of a segment L if A lies wholly in the closed half-plane lying to the left of L A is to the right of a segment L if A lies wholly in the closed half-plane lying to the right of L otherwise, A has indeterminate orientation relative to L. This happens if A is collinear with L or if A crosses the line determined by L.
Parameters
seg the LineSegment to compare
Returns
1 if seg is to the left of this segment
-1 if seg is to the right of this segment
0 if seg has indeterminate orientation relative to this segment
Definition at line 166 of file LineSegment.cpp.
References geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by geos::operation::buffer::DepthSegment::compareTo(), and geos::geom::LineSegment::orientationIndex().
 {
   int orient0 = algorithm::CGAlgorithms::orientationIndex(p0, p1, seg.p0);
   int orient1 = algorithm::CGAlgorithms::orientationIndex(p0, p1, seg.p1);
   // this handles the case where the points are L or collinear
   if (orient0 >= 0 && orient1 >= 0)
     return std::max(orient0, orient1);
   // this handles the case where the points are R or collinear
   if (orient0 <= 0 && orient1 <= 0)
         return std::max(orient0, orient1);
   // points lie on opposite sides ==> indeterminate orientation
   return 0;
 }
INLINE int geos::geom::LineSegment::orientationIndex (const LineSegment * seg) const inherited
Definition at line 148 of file LineSegment.inl.
References INLINE, and geos::geom::LineSegment::orientationIndex().
 {
   assert(seg);
   return orientationIndex(*seg);
 }
INLINE int geos::geom::LineSegment::orientationIndex (const Coordinate & p) const inherited
Determines the orientation index of a Coordinate relative to this segment.
The orientation index is as defined in CGAlgorithms::computeOrientation.
Parameters
seg the LineSegment to compare
Returns
1 if p is to the left of this segment
-1 if p is to the right of this segment
0 if p is collinear with this segment
See also
CGAlgorithms::computeOrientation(Coordinate, Coordinate, Coordinate)
Definition at line 155 of file LineSegment.inl.
References INLINE, geos::algorithm::CGAlgorithms::orientationIndex(), geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   return algorithm::CGAlgorithms::orientationIndex(p0, p1, p);
 }
INLINE void geos::geom::LineSegment::pointAlong (double segmentLengthFraction, Coordinate & ret) const inherited
Computes the Coordinate that lies a given fraction along the line defined by this segment.
A fraction of 0.0 returns the start point of the segment; a fraction of 1.0 returns the end point of the segment. If the fraction is < 0.0 or > 1.0 the point returned will lie before the start or beyond the end of the segment.
Parameters
segmentLengthFraction the fraction of the segment length along the line
ret will be set to the point at that distance
Definition at line 74 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
     ret = Coordinate(
   p0.x + segmentLengthFraction * (p1.x - p0.x),
   p0.y + segmentLengthFraction * (p1.y - p0.y));
 }
void geos::geom::LineSegment::pointAlongOffset (double segmentLengthFraction, double offsetDistance, Coordinate & ret) const inherited
Computes the Coordinate that lies a given fraction along the line defined by this segment and offset from the segment by a given distance.
A fraction of 0.0 offsets from the start point of the segment; a fraction of 1.0 offsets from the end point of the segment.
The computed point is offset to the left of the line if the offset distance is positive, to the right if negative.
Parameters
segmentLengthFraction the fraction of the segment length along the line
offsetDistance the distance the point is offset from the segment (positive is to the left, negative is to the right)
ret will be set to the point at that distance and offset
Exceptions
IllegalStateException if the segment has zero length
Definition at line 272 of file LineSegment.cpp.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addLimitedMitreJoin().
 {
   // the point on the segment line
   double segx = p0.x + segmentLengthFraction * (p1.x - p0.x);
   double segy = p0.y + segmentLengthFraction * (p1.y - p0.y);
   double dx = p1.x - p0.x;
   double dy = p1.y - p0.y;
   double len = sqrt(dx * dx + dy * dy);
   double ux = 0.0;
   double uy = 0.0;
   if (offsetDistance != 0.0) {
     if (len <= 0.0) {
       throw util::IllegalStateException("Cannot compute offset from zero-length line segment");
     }
     // u is the vector that is the length of the offset,
     // in the direction of the segment
     ux = offsetDistance * dx / len;
     uy = offsetDistance * dy / len;
   }
   // the offset point is the seg point plus the offset
   // vector rotated 90 degrees CCW
   double offsetx = segx - uy;
   double offsety = segy + ux;
   ret = Coordinate(offsetx, offsety);
 }
void geos::geom::LineSegment::project (const Coordinate & p, Coordinate & ret) const inherited
Compute the projection of a point onto the line determined by this line segment.
Note that the projected point may lie outside the line segment. If this is the case, the projection factor will lie outside the range [0.0, 1.0].
Definition at line 101 of file LineSegment.cpp.
 {
   if (p==p0 || p==p1) ret=p;
   double r=projectionFactor(p);
   ret=Coordinate(p0.x+r*(p1.x-p0.x),p0.y+r*(p1.y-p0.y));
 }
bool geos::geom::LineSegment::project (const LineSegment & seg, LineSegment & ret) const inherited
Project a line segment onto this line segment and return the resulting line segment.
The returned line segment will be a subset of the target line line segment. This subset may be null, if the segments are oriented in such a way that there is no projection.
Note that the returned line may have zero length (i.e. the same endpoints). This can happen for instance if the lines are perpendicular to one another.
Parameters
seg the line segment to project
ret the projected line segment
Returns
true if there is an overlap, false otherwise
Definition at line 109 of file LineSegment.cpp.
References geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and geos::geom::LineSegment::setCoordinates().
 {
   double pf0=projectionFactor(seg.p0);
   double pf1=projectionFactor(seg.p1);
   // check if segment projects at all
   if (pf0>=1.0 && pf1>=1.0) return false;
   if (pf0<=0.0 && pf1<=0.0) return false;
   Coordinate newp0;
   project(seg.p0, newp0);
   Coordinate newp1;
   project(seg.p1, newp1);
   ret.setCoordinates(newp0, newp1);
   return true;
 }
double geos::geom::LineSegment::projectionFactor (const Coordinate & p) const inherited
Compute the projection factor for the projection of the point p onto this LineSegment.
The projection factor is the constant r by which the vector for this segment must be multiplied to equal the vector for the projection of p on the line defined by this segment.
The projection factor returned will be in the range (-inf, +inf)
Parameters
p the point to compute the factor for
Returns
the projection factor for the point
Definition at line 65 of file LineSegment.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::linearref::LengthIndexOfPoint::segmentNearestMeasure(), and geos::operation::overlay::snap::LineStringSnapper::snapSegments().
 {
   if (p==p0) return 0.0;
   if (p==p1) return 1.0;
     // Otherwise, use comp.graphics.algorithms Frequently Asked Questions method
     /*(1)             AC dot AB
                    r = ---------
                          ||AB||^2
                 r has the following meaning:
                 r=0 P = A
                 r=1 P = B
                 r<0 P is on the backward extension of AB
                 r>1 P is on the forward extension of AB
                 0<r<1 P is interior to AB
         */
   double dx=p1.x-p0.x;
   double dy=p1.y-p0.y;
   double len2=dx*dx+dy*dy;
   double r=((p.x-p0.x)*dx+(p.y-p0.y)*dy)/len2;
   return r;
 }
void geos::geom::LineSegment::reverse () inherited
Reverses the direction of the line segment.
Definition at line 55 of file LineSegment.cpp.
Referenced by geos::geom::LineSegment::normalize().
 {
   // TODO: use std::swap<>
   Coordinate temp=p0;
   p0=p1;
   p1=temp;
 }
double geos::geom::LineSegment::segmentFraction (const Coordinate & inputPt) const inherited
Computes the fraction of distance (in [0.0, 1.0]) that the projection of a point occurs along this line segment.
If the point is beyond either ends of the line segment, the closest fractional value (0.0 or 1.0) is returned.
Essentially, this is the projectionFactor clamped to the range [0.0, 1.0].
Parameters
inputPt the point
Returns
the fraction along the line segment the projection of the point occurs
Definition at line 89 of file LineSegment.cpp.
Referenced by geos::linearref::LocationIndexOfPoint::indexOfFromStart().
 {
   double segFrac = projectionFactor(inputPt);
   if (segFrac < 0.0)
     segFrac = 0.0;
   else if (segFrac > 1.0)
     segFrac = 1.0;
   return segFrac;
 }
INLINE void geos::geom::LineSegment::setCoordinates (const Coordinate & c0, const Coordinate & c1) inherited
Definition at line 102 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addNextSegment(), geos::operation::buffer::OffsetSegmentGenerator::initSideSegments(), geos::triangulate::quadedge::QuadEdgeSubdivision::isOnEdge(), geos::geom::LineSegment::project(), and geos::geom::LineSegment::setCoordinates().
 {
   p0=c0; p1=c1;
 }
INLINE void geos::geom::LineSegment::setCoordinates (const LineSegment & ls) inherited
Definition at line 124 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and geos::geom::LineSegment::setCoordinates().
 {
   setCoordinates(ls.p0,ls.p1);
 }
std::unique_ptr< LineString > geos::geom::LineSegment::toGeometry (const GeometryFactory & gf) const inherited
Creates a LineString with the same coordinates as this segment
Parameters
gf the geometery factory to use
Returns
a LineString with the same geometry as this segment
Definition at line 307 of file LineSegment.cpp.
References geos::geom::CoordinateSequence::add(), and geos::geom::GeometryFactory::createLineString().
 {
   CoordinateSequence *cl=new CoordinateArraySequence();
   cl->add(p0);
   cl->add(p1);
   return std::unique_ptr<LineString>(
     gf.createLineString(cl) // ownership transferred
   );
 }
Member Data Documentation
unsigned int geos::simplify::TaggedLineSegment::index private
Definition at line 77 of file TaggedLineSegment.h.
Referenced by getIndex().
Coordinate geos::geom::LineSegment::p0 inherited
Definition at line 62 of file LineSegment.h.
Referenced by geos::simplify::LineSegmentIndex::add(), geos::operation::buffer::OffsetSegmentGenerator::addBevelJoin(), geos::operation::buffer::OffsetSegmentGenerator::addCollinear(), geos::operation::buffer::OffsetSegmentGenerator::addInsideTurn(), geos::operation::buffer::OffsetSegmentGenerator::addLimitedMitreJoin(), geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::addLine(), geos::operation::buffer::OffsetSegmentGenerator::addMitreJoin(), geos::operation::buffer::OffsetSegmentGenerator::addOutsideTurn(), geos::geom::LineSegment::angle(), geos::algorithm::SIRtreePointInRing::buildIndex(), geos::geom::LineSegment::closestPoints(), geos::geom::LineSegment::compareTo(), geos::operation::buffer::DepthSegment::compareX(), geos::algorithm::MinimumDiameter::computeConvexRingMinDiameter(), geos::algorithm::distance::DistanceToPoint::computeDistance(), geos::operation::buffer::OffsetSegmentGenerator::computeOffsetSegment(), geos::geom::LineSegment::distance(), geos::geom::LineSegment::distancePerpendicular(), geos::geom::LineSegment::equalsTopo(), geos::simplify::TaggedLineString::extractCoordinates(), geos::operation::overlay::snap::LineStringSnapper::findSegmentToSnap(), geos::geom::LineSegment::getLength(), geos::index::chain::MonotoneChain::getLineSegment(), geos::simplify::TaggedLineStringSimplifier::hasInteriorIntersection(), geos::linearref::LocationIndexOfPoint::indexOfFromStart(), geos::linearref::LengthIndexOfPoint::indexOfFromStart(), geos::geom::LineSegment::intersection(), geos::geom::LineSegment::isHorizontal(), geos::geom::LineSegment::isVertical(), geos::geom::LineSegment::lineIntersection(), geos::geom::LineSegment::midPoint(), geos::geom::LineSegment::normalize(), geos::geom::operator<<(), geos::geom::operator==(), geos::geom::LineSegment::operator[](), geos::geom::LineSegment::orientationIndex(), geos::geom::LineSegment::pointAlong(), geos::geom::LineSegment::project(), geos::simplify::LineSegmentIndex::query(), geos::simplify::LineSegmentIndex::remove(), geos::geom::LineSegment::setCoordinates(), geos::operation::overlay::snap::LineStringSnapper::snapSegments(), geos::algorithm::SIRtreePointInRing::testLineSegment(), geos::algorithm::MCPointInRing::testLineSegment(), and geos::simplify::LineSegmentVisitor::visitItem().
Coordinate geos::geom::LineSegment::p1 inherited
Segment start.
Definition at line 64 of file LineSegment.h.
Referenced by geos::simplify::LineSegmentIndex::add(), geos::operation::buffer::OffsetSegmentGenerator::addBevelJoin(), geos::operation::buffer::OffsetSegmentGenerator::addCollinear(), geos::operation::buffer::OffsetSegmentGenerator::addInsideTurn(), geos::operation::buffer::OffsetSegmentGenerator::addLimitedMitreJoin(), geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::addLine(), geos::operation::buffer::OffsetSegmentGenerator::addLineEndCap(), geos::operation::buffer::OffsetSegmentGenerator::addMitreJoin(), geos::operation::buffer::OffsetSegmentGenerator::addOutsideTurn(), geos::geom::LineSegment::angle(), geos::algorithm::SIRtreePointInRing::buildIndex(), geos::geom::LineSegment::closestPoints(), geos::geom::LineSegment::compareTo(), geos::operation::buffer::DepthSegment::compareX(), geos::algorithm::MinimumDiameter::computeConvexRingMinDiameter(), geos::algorithm::distance::DistanceToPoint::computeDistance(), geos::operation::buffer::OffsetSegmentGenerator::computeOffsetSegment(), geos::geom::LineSegment::distance(), geos::geom::LineSegment::distancePerpendicular(), geos::geom::LineSegment::equalsTopo(), geos::operation::overlay::snap::LineStringSnapper::findSegmentToSnap(), geos::geom::LineSegment::getLength(), geos::index::chain::MonotoneChain::getLineSegment(), geos::simplify::TaggedLineStringSimplifier::hasInteriorIntersection(), geos::linearref::LocationIndexOfPoint::indexOfFromStart(), geos::linearref::LengthIndexOfPoint::indexOfFromStart(), geos::geom::LineSegment::intersection(), geos::geom::LineSegment::isHorizontal(), geos::geom::LineSegment::isVertical(), geos::geom::LineSegment::lineIntersection(), geos::geom::LineSegment::midPoint(), geos::geom::LineSegment::normalize(), geos::geom::operator<<(), geos::geom::operator==(), geos::geom::LineSegment::operator[](), geos::geom::LineSegment::orientationIndex(), geos::geom::LineSegment::pointAlong(), geos::geom::LineSegment::project(), geos::simplify::LineSegmentIndex::query(), geos::simplify::LineSegmentIndex::remove(), geos::geom::LineSegment::setCoordinates(), geos::operation::overlay::snap::LineStringSnapper::snapSegments(), geos::algorithm::SIRtreePointInRing::testLineSegment(), geos::algorithm::MCPointInRing::testLineSegment(), and geos::simplify::LineSegmentVisitor::visitItem().
const geom::Geometry* geos::simplify::TaggedLineSegment::parent private
Definition at line 75 of file TaggedLineSegment.h.
Referenced by getParent().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/simplify/TaggedLineSegment.h
/home/vicky/potree/geos/vicky/src/simplify/TaggedLineSegment.cpp