GEOS: geos::noding::ScaledNoder Class Reference
geos::noding::ScaledNoder Class Reference
Wraps a Noder and transforms its input into the integer domain.
#include <ScaledNoder.h>
Classes
class ReScaler
class Scaler
Public Member Functions
bool isIntegerPrecision ()
ScaledNoder (Noder &n, double nScaleFactor, double nOffsetX=0.0, double nOffsetY=0.0)
~ScaledNoder () override
std::vector< SegmentString * > * getNodedSubstrings () const override
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
void computeNodes (std::vector< SegmentString * > *inputSegStr) override
Computes the noding for a collection of SegmentStrings.
void filter_ro (const geom::Coordinate *c)
void filter_rw (geom::Coordinate *c) const
Private Member Functions
void rescale (std::vector< SegmentString * > &segStrings) const
void scale (std::vector< SegmentString * > &segStrings) const
ScaledNoder (const ScaledNoder &other)=delete
ScaledNoder & operator= (const ScaledNoder &rhs)=delete
Private Attributes
Noder & noder
double scaleFactor
double offsetX
double offsetY
bool isScaled
std::vector< geom::CoordinateSequence * > newCoordSeq
Friends
class ScaledNoder::Scaler
class ScaledNoder::ReScaler
Detailed Description
Wraps a Noder and transforms its input into the integer domain.
This is intended for use with Snap-Rounding noders, which typically are only intended to work in the integer domain. Offsets can be provided to increase the number of digits of available precision.
Definition at line 61 of file ScaledNoder.h.
Constructor & Destructor Documentation
geos::noding::ScaledNoder::ScaledNoder (Noder & n, double nScaleFactor, double nOffsetX = 0.0, double nOffsetY = 0.0) inline
Definition at line 67 of file ScaledNoder.h.
     :
     noder(n),
     scaleFactor(nScaleFactor),
     offsetX(nOffsetX),
     offsetY(nOffsetY),
     isScaled(nScaleFactor!=1.0)
   {}
geos::noding::ScaledNoder::~ScaledNoder () override
Definition at line 175 of file ScaledNoder.cpp.
 {
   for (std::vector<geom::CoordinateSequence*>::const_iterator
     it=newCoordSeq.begin(), end=newCoordSeq.end();
     it != end;
     ++it)
   {
     delete *it;
   }
 }
geos::noding::ScaledNoder::ScaledNoder (const ScaledNoder & other) private delete
Member Function Documentation
void geos::noding::ScaledNoder::computeNodes (std::vector< SegmentString * > * segStrings) override virtual
Computes the noding for a collection of SegmentStrings.
Some Noders may add all these nodes to the input SegmentStrings; others may only add some or none at all.
Parameters
segStrings a collection of SegmentStrings to node
Implements geos::noding::Noder.
Definition at line 209 of file ScaledNoder.cpp.
 {
 #if GEOS_DEBUG > 1
   sqlPrint("inputSegStr", *inputSegStr);
 #endif
   if (isScaled) scale(*inputSegStr);
 #if GEOS_DEBUG > 1
   sqlPrint("scaledInputSegStr", *inputSegStr);
 #endif
   noder.computeNodes(inputSegStr);
 }
void geos::noding::ScaledNoder::filter_ro (const geom::Coordinate * c) inline
Definition at line 85 of file ScaledNoder.h.
References geos::ignore_unused_variable_warning().
     {
         ::geos::ignore_unused_variable_warning(c);
         assert(0);
     }
void geos::noding::ScaledNoder::filter_rw (geom::Coordinate * c) const
SegmentString::NonConstVect * geos::noding::ScaledNoder::getNodedSubstrings () const override virtual
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
Returns
a newly allocated std::vector of const SegmentStrings. Caller is responsible to delete container and elements.
Implements geos::noding::Noder.
Definition at line 189 of file ScaledNoder.cpp.
 {
   SegmentString::NonConstVect* splitSS = noder.getNodedSubstrings();
 #if GEOS_DEBUG > 1
   sqlPrint("nodedSegStr", *splitSS);
 #endif
   if ( isScaled ) rescale(*splitSS);
 #if GEOS_DEBUG > 1
   sqlPrint("scaledNodedSegStr", *splitSS);
 #endif
   return splitSS;
 }
bool geos::noding::ScaledNoder::isIntegerPrecision () inline
Definition at line 65 of file ScaledNoder.h.
 { return (scaleFactor == 1.0); }
ScaledNoder& geos::noding::ScaledNoder::operator= (const ScaledNoder & rhs) private delete
void geos::noding::ScaledNoder::rescale (std::vector< SegmentString * > & segStrings) const private
Definition at line 131 of file ScaledNoder.cpp.
References geos::geom::CoordinateSequence::apply_rw(), and geos::noding::SegmentString::getCoordinates().
 {
   ReScaler rescaler(*this);
   for (SegmentString::NonConstVect::const_iterator
     i0=segStrings.begin(), i0End=segStrings.end();
       i0!=i0End; ++i0)
   {
     SegmentString* ss=*i0;
     ss->getCoordinates()->apply_rw(&rescaler);
   }
 }
void geos::noding::ScaledNoder::scale (std::vector< SegmentString * > & segStrings) const private
Definition at line 149 of file ScaledNoder.cpp.
References geos::geom::CoordinateSequence::apply_rw(), geos::noding::SegmentString::getCoordinates(), geos::geom::CoordinateSequence::removeRepeatedPoints(), and geos::geom::CoordinateSequence::size().
 {
   Scaler scaler(*this);
   for (SegmentString::NonConstVect::const_iterator
     i0=segStrings.begin(), i0End=segStrings.end();
       i0!=i0End; ++i0)
   {
     SegmentString* ss=*i0;
     CoordinateSequence* cs=ss->getCoordinates();
 #ifndef NDEBUG
     size_t npts = cs->size();
 #endif
     cs->apply_rw(&scaler);
     assert(cs->size() == npts);
     // Actually, we should be creating *new*
     // SegmentStrings here, but who's going
     // to delete them then ? And is it worth
     // the memory cost ?
     cs->removeRepeatedPoints();
   }
 }
Friends And Related Function Documentation
friend class ScaledNoder::ReScaler friend
Definition at line 115 of file ScaledNoder.h.
friend class ScaledNoder::Scaler friend
Definition at line 111 of file ScaledNoder.h.
Member Data Documentation
bool geos::noding::ScaledNoder::isScaled private
Definition at line 103 of file ScaledNoder.h.
std::vector<geom::CoordinateSequence*> geos::noding::ScaledNoder::newCoordSeq mutable private
Definition at line 117 of file ScaledNoder.h.
Noder& geos::noding::ScaledNoder::noder private
Definition at line 95 of file ScaledNoder.h.
double geos::noding::ScaledNoder::offsetX private
Definition at line 99 of file ScaledNoder.h.
Referenced by geos::noding::ScaledNoder::Scaler::filter_rw(), geos::noding::ScaledNoder::ReScaler::filter_rw(), geos::noding::ScaledNoder::ReScaler::ReScaler(), and geos::noding::ScaledNoder::Scaler::Scaler().
double geos::noding::ScaledNoder::offsetY private
Definition at line 101 of file ScaledNoder.h.
Referenced by geos::noding::ScaledNoder::Scaler::filter_rw(), geos::noding::ScaledNoder::ReScaler::filter_rw(), geos::noding::ScaledNoder::ReScaler::ReScaler(), and geos::noding::ScaledNoder::Scaler::Scaler().
double geos::noding::ScaledNoder::scaleFactor private
Definition at line 97 of file ScaledNoder.h.
Referenced by geos::noding::ScaledNoder::Scaler::filter_rw(), geos::noding::ScaledNoder::ReScaler::filter_rw(), geos::noding::ScaledNoder::ReScaler::ReScaler(), and geos::noding::ScaledNoder::Scaler::Scaler().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/ScaledNoder.h
/home/vicky/potree/geos/vicky/src/noding/ScaledNoder.cpp