GEOS: geos::geomgraph::DirectedEdgeStar Class Reference
geos::geomgraph::DirectedEdgeStar Class Reference
A DirectedEdgeStar is an ordered list of outgoing DirectedEdges around a node.
#include <DirectedEdgeStar.h>
Public Types
typedef std::set< EdgeEnd *, EdgeEndLT > container
typedef container::iterator iterator
typedef container::const_iterator const_iterator
typedef container::reverse_iterator reverse_iterator
Public Member Functions
DirectedEdgeStar ()
~DirectedEdgeStar () override
void insert (EdgeEnd *ee) override
Insert a directed edge in the list.
Label & getLabel ()
int getOutgoingDegree ()
int getOutgoingDegree (EdgeRing *er)
DirectedEdge * getRightmostEdge ()
void computeLabelling (std::vector< GeometryGraph * > *geom) override
Compute the labelling for all dirEdges in this star, as well as the overall labelling.
void mergeSymLabels ()
For each dirEdge in the star, merge the label from the sym dirEdge into the label.
void updateLabelling (const Label &nodeLabel)
Update incomplete dirEdge labels from the labelling for the node.
void linkResultDirectedEdges ()
void linkMinimalDirectedEdges (EdgeRing *er)
void linkAllDirectedEdges ()
void findCoveredLineEdges ()
Traverse the star of edges, maintaing the current location in the result area at this node (if any).
void computeDepths (DirectedEdge *de)
Compute the DirectedEdge depths for a subsequence of the edge array.
std::string print () const override
virtual geom::Coordinate & getCoordinate ()
const geom::Coordinate & getCoordinate () const
virtual std::size_t getDegree ()
virtual iterator begin ()
virtual const_iterator begin () const
virtual iterator end ()
virtual const_iterator end () const
virtual reverse_iterator rbegin ()
virtual reverse_iterator rend ()
virtual container & getEdges ()
virtual EdgeEnd * getNextCW (EdgeEnd *ee)
virtual bool isAreaLabelsConsistent (const GeometryGraph &geomGraph)
virtual void propagateSideLabels (int geomIndex)
virtual iterator find (EdgeEnd *eSearch)
Protected Member Functions
virtual void insertEdgeEnd (EdgeEnd *e)
Insert an EdgeEnd into the map.
Protected Attributes
EdgeEndStar::container edgeMap
A map which maintains the edges in sorted order around the node.
Private Types
enum { SCANNING_FOR_INCOMING =1, LINKING_TO_OUTGOING }
States for linResultDirectedEdges.
Private Member Functions
std::vector< DirectedEdge * > * getResultAreaEdges ()
Returned vector is onwed by DirectedEdgeStar object, but lazily created.
int computeDepths (EdgeEndStar::iterator startIt, EdgeEndStar::iterator endIt, int startDepth)
Private Attributes
std::vector< DirectedEdge * > * resultAreaEdgeList
Label label
Detailed Description
A DirectedEdgeStar is an ordered list of outgoing DirectedEdges around a node.
It supports labelling the edges as well as linking the edges to form both MaximalEdgeRings and MinimalEdgeRings.
Definition at line 55 of file DirectedEdgeStar.h.
Member Typedef Documentation
typedef container::const_iterator geos::geomgraph::EdgeEndStar::const_iterator inherited
Definition at line 69 of file EdgeEndStar.h.
typedef std::set<EdgeEnd *, EdgeEndLT> geos::geomgraph::EdgeEndStar::container inherited
Definition at line 66 of file EdgeEndStar.h.
typedef container::iterator geos::geomgraph::EdgeEndStar::iterator inherited
Definition at line 68 of file EdgeEndStar.h.
typedef container::reverse_iterator geos::geomgraph::EdgeEndStar::reverse_iterator inherited
Definition at line 70 of file EdgeEndStar.h.
Member Enumeration Documentation
anonymous enum private
States for linResultDirectedEdges.
Enumerator
SCANNING_FOR_INCOMING
LINKING_TO_OUTGOING
Definition at line 152 of file DirectedEdgeStar.h.
        {
     SCANNING_FOR_INCOMING=1,
     LINKING_TO_OUTGOING
   };
Constructor & Destructor Documentation
geos::geomgraph::DirectedEdgeStar::DirectedEdgeStar () inline
Definition at line 59 of file DirectedEdgeStar.h.
     :
     EdgeEndStar(),
     resultAreaEdgeList(nullptr),
     label()
   {}
geos::geomgraph::DirectedEdgeStar::~DirectedEdgeStar () inline override
Definition at line 66 of file DirectedEdgeStar.h.
{
     delete resultAreaEdgeList;
   }
Member Function Documentation
EdgeEndStar::iterator geos::geomgraph::EdgeEndStar::begin () inline virtual inherited
Definition at line 161 of file EdgeEndStar.h.
Referenced by geos::operation::buffer::BufferSubgraph::add(), geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent(), geos::operation::buffer::BufferSubgraph::computeDepths(), geos::geomgraph::EdgeEndStar::computeEdgeEndLabels(), geos::geomgraph::EdgeEndStar::computeLabelling(), geos::operation::buffer::BufferSubgraph::computeNodeDepth(), geos::geomgraph::EdgeEndStar::getCoordinate(), geos::geomgraph::EdgeEndStar::getNextCW(), geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), geos::geomgraph::Node::isIncidentEdgeInResult(), geos::geomgraph::Node::Node(), geos::geomgraph::operator<<(), and geos::geomgraph::EdgeEndStar::propagateSideLabels().
 {
   return edgeMap.begin();
 }
virtual const_iterator geos::geomgraph::EdgeEndStar::begin () const inline virtual inherited
Definition at line 102 of file EdgeEndStar.h.
 { return edgeMap.begin(); }
void geos::geomgraph::DirectedEdgeStar::computeDepths (DirectedEdge * de)
Compute the DirectedEdge depths for a subsequence of the edge array.
Returns
the last depth assigned (from the R side of the last edge visited)
Definition at line 411 of file DirectedEdgeStar.cpp.
References geos::geomgraph::EdgeEnd::getCoordinate(), and geos::geomgraph::DirectedEdge::getDepth().
Referenced by geos::operation::buffer::BufferSubgraph::computeNodeDepth().
 {
   assert(de);
   EdgeEndStar::iterator edgeIterator=find(de);
   int startDepth=de->getDepth(Position::LEFT);
   int targetLastDepth=de->getDepth(Position::RIGHT);
   // compute the depths from this edge up to the end of the edge array
   EdgeEndStar::iterator nextEdgeIterator=edgeIterator;
   ++nextEdgeIterator;
   int nextDepth=computeDepths(nextEdgeIterator, end(), startDepth);
   // compute the depths for the initial part of the array
   int lastDepth=computeDepths(begin(), edgeIterator, nextDepth);
   if (lastDepth!=targetLastDepth)
     throw util::TopologyException("depth mismatch at ", de->getCoordinate());
 }
int geos::geomgraph::DirectedEdgeStar::computeDepths (EdgeEndStar::iterator startIt, EdgeEndStar::iterator endIt, int startDepth) private
Definition at line 434 of file DirectedEdgeStar.cpp.
References geos::geomgraph::DirectedEdge::getDepth(), and geos::geomgraph::DirectedEdge::setEdgeDepths().
 {
   int currDepth=startDepth;
   for (EdgeEndStar::iterator it=startIt; it!=endIt; ++it)
   {
     assert(*it);
           assert(dynamic_cast<DirectedEdge*>(*it));
           DirectedEdge *nextDe=static_cast<DirectedEdge*>(*it);
     nextDe->setEdgeDepths(Position::RIGHT, currDepth);
     currDepth=nextDe->getDepth(Position::LEFT);
   }
   return currDepth;
 }
void geos::geomgraph::DirectedEdgeStar::computeLabelling (std::vector< GeometryGraph * > * geom) override virtual
Compute the labelling for all dirEdges in this star, as well as the overall labelling.
Reimplemented from geos::geomgraph::EdgeEndStar.
Definition at line 129 of file DirectedEdgeStar.cpp.
References geos::geom::Location::BOUNDARY, geos::geomgraph::EdgeEnd::getEdge(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), geos::geom::Location::INTERIOR, and geos::geom::Location::UNDEF.
 {
   // this call can throw a TopologyException
   // we don't have any cleanup to do...
   EdgeEndStar::computeLabelling(geom);
   // determine the overall labelling for this DirectedEdgeStar
   // (i.e. for the node it is based at)
   label=Label(Location::UNDEF);
   EdgeEndStar::iterator endIt=end();
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     EdgeEnd *ee=*it;
     assert(ee);
     Edge *e=ee->getEdge();
     assert(e);
     const Label& eLabel=e->getLabel();
     for (int i=0; i<2; ++i) {
       int eLoc=eLabel.getLocation(i);
       if (eLoc==Location::INTERIOR || eLoc==Location::BOUNDARY)
         label.setLocation(i, Location::INTERIOR);
     }
   }
 }
EdgeEndStar::iterator geos::geomgraph::EdgeEndStar::end () inline virtual inherited
Definition at line 179 of file EdgeEndStar.h.
Referenced by geos::operation::buffer::BufferSubgraph::add(), geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent(), geos::operation::buffer::BufferSubgraph::computeDepths(), geos::geomgraph::EdgeEndStar::computeEdgeEndLabels(), geos::geomgraph::EdgeEndStar::computeLabelling(), geos::operation::buffer::BufferSubgraph::computeNodeDepth(), geos::geomgraph::EdgeEndStar::getNextCW(), geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), geos::geomgraph::Node::isIncidentEdgeInResult(), geos::geomgraph::Node::Node(), geos::geomgraph::operator<<(), and geos::geomgraph::EdgeEndStar::propagateSideLabels().
 {
   return edgeMap.end();
 }
virtual const_iterator geos::geomgraph::EdgeEndStar::end () const inline virtual inherited
Definition at line 104 of file EdgeEndStar.h.
 { return edgeMap.end(); }
EdgeEndStar::iterator geos::geomgraph::EdgeEndStar::find (EdgeEnd * eSearch) inline virtual inherited
Definition at line 191 of file EdgeEndStar.h.
References geos::algorithm::operator<<().
Referenced by geos::geomgraph::EdgeEndStar::getNextCW().
 {
   return edgeMap.find(eSearch);
 }
void geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges ()
Traverse the star of edges, maintaing the current location in the result area at this node (if any).
If any L edges are found in the interior of the result, mark them as covered.
Find first DirectedEdge of result area (if any). The interior of the result is on the RHS of the edge, so the start location will be:
INTERIOR if the edge is outgoing
EXTERIOR if the edge is incoming
move around ring, keeping track of the current location (Interior or Exterior) for the result area. If L edges are found, mark them as covered if they are in the interior
Definition at line 344 of file DirectedEdgeStar.cpp.
References geos::geom::Location::EXTERIOR, geos::geomgraph::EdgeEnd::getEdge(), geos::geomgraph::DirectedEdge::getSym(), geos::geom::Location::INTERIOR, geos::geomgraph::DirectedEdge::isInResult(), geos::geomgraph::DirectedEdge::isLineEdge(), geos::geomgraph::GraphComponent::setCovered(), and geos::geom::Location::UNDEF.
Referenced by geos::operation::overlay::LineBuilder::findCoveredLineEdges().
 {
   // Since edges are stored in CCW order around the node,
   // as we move around the ring we move from the right to the left side of the edge
   int startLoc=Location::UNDEF;
   EdgeEndStar::iterator endIt=end();
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     assert(*it);
           assert(dynamic_cast<DirectedEdge*>(*it));
           DirectedEdge *nextOut=static_cast<DirectedEdge*>(*it);
     DirectedEdge *nextIn=nextOut->getSym();
     assert(nextIn);
     if (!nextOut->isLineEdge()) {
       if (nextOut->isInResult()) {
         startLoc=Location::INTERIOR;
         break;
       }
       if (nextIn->isInResult()) {
         startLoc=Location::EXTERIOR;
         break;
       }
     }
   }
   // no A edges found, so can't determine if L edges are covered or not
   if (startLoc==Location::UNDEF) return;
   int currLoc=startLoc;
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     assert(*it);
           assert(dynamic_cast<DirectedEdge*>(*it));
           DirectedEdge *nextOut=static_cast<DirectedEdge*>(*it);
     DirectedEdge *nextIn=nextOut->getSym();
     assert(nextIn);
     if (nextOut->isLineEdge()) {
       nextOut->getEdge()->setCovered(currLoc==Location::INTERIOR);
     } else {  // edge is an Area edge
       if (nextOut->isInResult())
         currLoc=Location::EXTERIOR;
       if (nextIn->isInResult())
         currLoc=Location::INTERIOR;
     }
   }
 }
Coordinate & geos::geomgraph::EdgeEndStar::getCoordinate () virtual inherited
Returns
the coordinate for the node this star is based at or NULL if this is still an unbound star. Be aware that the returned pointer will point to a Coordinate owned by the specific EdgeEnd happening to be the first in the star (ordered CCW)
Definition at line 56 of file EdgeEndStar.cpp.
References geos::geomgraph::EdgeEndStar::begin(), geos::geomgraph::EdgeEndStar::edgeMap, and geos::geomgraph::EdgeEnd::getCoordinate().
Referenced by geos::geomgraph::EdgeEndStar::getCoordinate(), and geos::geomgraph::operator<<().
 {
   static Coordinate nullCoord(DoubleNotANumber, DoubleNotANumber, DoubleNotANumber);
   if (edgeMap.size()==0) return nullCoord;
   EdgeEndStar::iterator it=begin();
   EdgeEnd *e=*it;
   assert(e);
   return e->getCoordinate();
 }
const Coordinate & geos::geomgraph::EdgeEndStar::getCoordinate () const inherited
Definition at line 69 of file EdgeEndStar.cpp.
References geos::geomgraph::EdgeEndStar::getCoordinate().
 {
   return const_cast<EdgeEndStar*>(this)->getCoordinate();
 }
std::size_t geos::geomgraph::EdgeEndStar::getDegree () inline virtual inherited
Definition at line 155 of file EdgeEndStar.h.
Referenced by geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes().
 {
   return edgeMap.size();
 }
EdgeEndStar::container & geos::geomgraph::EdgeEndStar::getEdges () inline virtual inherited
Definition at line 167 of file EdgeEndStar.h.
Referenced by geos::operation::overlay::OverlayOp::computeLabelling().
 {
   return edgeMap;
 }
Label& geos::geomgraph::DirectedEdgeStar::getLabel () inline
Definition at line 73 of file DirectedEdgeStar.h.
Referenced by geos::operation::overlay::OverlayOp::updateNodeLabelling().
 { return label; }
EdgeEnd * geos::geomgraph::EdgeEndStar::getNextCW (EdgeEnd * ee) virtual inherited
Definition at line 76 of file EdgeEndStar.cpp.
References geos::geomgraph::EdgeEndStar::begin(), geos::geomgraph::EdgeEndStar::end(), and geos::geomgraph::EdgeEndStar::find().
 {
   EdgeEndStar::iterator it=find(ee);
   if ( it==end() ) return nullptr;
   if ( it==begin() ) { it=end(); --it; }
   else --it;
   return *it;
 }
int geos::geomgraph::DirectedEdgeStar::getOutgoingDegree ()
Definition at line 58 of file DirectedEdgeStar.cpp.
References geos::geomgraph::DirectedEdge::isInResult().
Referenced by geos::geomgraph::EdgeRing::computeMaxNodeDegree().
 {
   int degree = 0;
   EdgeEndStar::iterator endIt=end();
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     assert(*it);
     assert(dynamic_cast<DirectedEdge*>(*it));
     DirectedEdge *de=static_cast<DirectedEdge*>(*it);
     if (de->isInResult()) ++degree;
   }
   return degree;
 }
int geos::geomgraph::DirectedEdgeStar::getOutgoingDegree (EdgeRing * er)
Definition at line 74 of file DirectedEdgeStar.cpp.
References geos::geomgraph::DirectedEdge::getEdgeRing().
 {
   int degree = 0;
   EdgeEndStar::iterator endIt=end();
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     assert(*it);
     assert(dynamic_cast<DirectedEdge*>(*it));
     DirectedEdge *de=static_cast<DirectedEdge*>(*it);
     if (de->getEdgeRing()==er) ++degree;
   }
   return degree;
 }
std::vector< DirectedEdge * > * geos::geomgraph::DirectedEdgeStar::getResultAreaEdges () private
Returned vector is onwed by DirectedEdgeStar object, but lazily created.
Definition at line 193 of file DirectedEdgeStar.cpp.
References geos::geomgraph::DirectedEdge::getSym(), and geos::geomgraph::DirectedEdge::isInResult().
 {
   if (resultAreaEdgeList!=nullptr) return resultAreaEdgeList;
   resultAreaEdgeList=new std::vector<DirectedEdge*>();
   EdgeEndStar::iterator endIt=end();
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     assert(*it);
     assert(dynamic_cast<DirectedEdge*>(*it));
     DirectedEdge *de=static_cast<DirectedEdge*>(*it);
     if (de->isInResult() || de->getSym()->isInResult())
       resultAreaEdgeList->push_back(de);
   }
   return resultAreaEdgeList;
 }
DirectedEdge * geos::geomgraph::DirectedEdgeStar::getRightmostEdge ()
Definition at line 90 of file DirectedEdgeStar.cpp.
References geos::geomgraph::EdgeEnd::getDy(), and geos::geomgraph::EdgeEnd::getQuadrant().
Referenced by geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode().
 {
   EdgeEndStar::iterator it=begin();
   if ( it==end() ) return nullptr;
   assert(*it);
   assert(dynamic_cast<DirectedEdge*>(*it));
   DirectedEdge *de0=static_cast<DirectedEdge*>(*it);
   ++it;
   if ( it==end() ) return de0;
   it=end(); --it;
   assert(*it);
   assert(dynamic_cast<DirectedEdge*>(*it));
   DirectedEdge *deLast=static_cast<DirectedEdge*>(*it);
   assert(de0);
   int quad0=de0->getQuadrant();
   assert(deLast);
   int quad1=deLast->getQuadrant();
   if (Quadrant::isNorthern(quad0) && Quadrant::isNorthern(quad1))
     return de0;
   else if (!Quadrant::isNorthern(quad0) && !Quadrant::isNorthern(quad1))
     return deLast;
   else {
     // edges are in different hemispheres - make sure we return one that is non-horizontal
     //DirectedEdge *nonHorizontalEdge=NULL;
     if (de0->getDy()!=0)
       return de0;
     else if (deLast->getDy()!=0)
       return deLast;
   }
   assert(0); // found two horizontal edges incident on node
   return nullptr;
 }
void geos::geomgraph::DirectedEdgeStar::insert (EdgeEnd * ee) override virtual
Insert a directed edge in the list.
Implements geos::geomgraph::EdgeEndStar.
Definition at line 48 of file DirectedEdgeStar.cpp.
 {
   assert(ee);
   assert(dynamic_cast<DirectedEdge*>(ee));
   DirectedEdge *de=static_cast<DirectedEdge*>(ee);
   insertEdgeEnd(de);
 }
virtual void geos::geomgraph::EdgeEndStar::insertEdgeEnd (EdgeEnd * e) inline protected virtual inherited
Insert an EdgeEnd into the map.
Definition at line 134 of file EdgeEndStar.h.
 { edgeMap.insert(e); }
bool geos::geomgraph::EdgeEndStar::isAreaLabelsConsistent (const GeometryGraph & geomGraph) virtual inherited
Definition at line 203 of file EdgeEndStar.cpp.
References geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent(), geos::geomgraph::EdgeEndStar::computeEdgeEndLabels(), and geos::geomgraph::GeometryGraph::getBoundaryNodeRule().
Referenced by geos::operation::valid::ConsistentAreaTester::isNodeEdgeAreaLabelsConsistent().
 {
   computeEdgeEndLabels(geomGraph.getBoundaryNodeRule());
   return checkAreaLabelsConsistent(0);
 }
void geos::geomgraph::DirectedEdgeStar::linkAllDirectedEdges ()
Definition at line 313 of file DirectedEdgeStar.cpp.
References geos::geomgraph::DirectedEdge::getSym(), and geos::geomgraph::DirectedEdge::setNext().
Referenced by geos::geomgraph::PlanarGraph::linkAllDirectedEdges().
 {
   //getEdges();
   // find first area edge (if any) to start linking at
   DirectedEdge *prevOut=nullptr;
   DirectedEdge *firstIn=nullptr;
   // link edges in CW order
   EdgeEndStar::reverse_iterator rbeginIt=rbegin();
   EdgeEndStar::reverse_iterator rendIt=rend();
   for(EdgeEndStar::reverse_iterator it=rbeginIt; it!=rendIt; ++it)
   {
     assert(*it);
           assert(dynamic_cast<DirectedEdge*>(*it));
           DirectedEdge *nextOut=static_cast<DirectedEdge*>(*it);
     DirectedEdge *nextIn=nextOut->getSym();
     assert(nextIn);
     if (firstIn==nullptr) firstIn=nextIn;
     if (prevOut!=nullptr) nextIn->setNext(prevOut);
     // record outgoing edge, in order to link the last incoming edge
     prevOut=nextOut;
   }
   assert(firstIn);
   firstIn->setNext(prevOut);
 }
void geos::geomgraph::DirectedEdgeStar::linkMinimalDirectedEdges (EdgeRing * er)
Definition at line 267 of file DirectedEdgeStar.cpp.
References geos::geomgraph::DirectedEdge::getEdgeRing(), geos::geomgraph::DirectedEdge::getSym(), and geos::geomgraph::DirectedEdge::setNextMin().
Referenced by geos::operation::overlay::MaximalEdgeRing::linkDirectedEdgesForMinimalEdgeRings().
 {
   // find first area edge (if any) to start linking at
   DirectedEdge *firstOut=nullptr;
   DirectedEdge *incoming=nullptr;
   int state=SCANNING_FOR_INCOMING;
   // link edges in CW order
   for (std::vector<DirectedEdge*>::reverse_iterator
     i=resultAreaEdgeList->rbegin(), iEnd=resultAreaEdgeList->rend();
     i != iEnd;
     ++i)
   {
     //DirectedEdge *nextOut=(*resultAreaEdgeList)[i];
     DirectedEdge *nextOut=*i;
     assert(nextOut);
     DirectedEdge *nextIn=nextOut->getSym();
     assert(nextIn);
     // record first outgoing edge, in order to link the last incoming edge
     if (firstOut==nullptr && nextOut->getEdgeRing()==er) firstOut=nextOut;
     switch (state) {
       case SCANNING_FOR_INCOMING:
         if (nextIn->getEdgeRing()!=er) continue;
         incoming=nextIn;
         state = LINKING_TO_OUTGOING;
         break;
       case LINKING_TO_OUTGOING:
         if (nextOut->getEdgeRing()!=er) continue;
         assert(incoming);
         incoming->setNextMin(nextOut);
         state = SCANNING_FOR_INCOMING;
         break;
     }
   }
   if (state==LINKING_TO_OUTGOING) {
     assert(firstOut!=nullptr); // found null for first outgoing dirEdge
     assert(firstOut->getEdgeRing()==er); // unable to link last incoming dirEdge
     assert(incoming);
     incoming->setNextMin(firstOut);
   }
 }
void geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges ()
Traverse the star of DirectedEdges, linking the included edges together. To link two dirEdges, the <next> pointer for an incoming dirEdge is set to the next outgoing edge.
DirEdges are only linked if:
they belong to an area (i.e. they have sides)
they are marked as being in the result
Edges are linked in CCW order (the order they are stored). This means that rings have their face on the Right (in other words, the topological location of the face is given by the RHS label of the DirectedEdge)
PRECONDITION: No pair of dirEdges are both marked as being in the result
Definition at line 213 of file DirectedEdgeStar.cpp.
References geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::DirectedEdge::getSym(), geos::geomgraph::Label::isArea(), geos::geomgraph::DirectedEdge::isInResult(), and geos::geomgraph::DirectedEdge::setNext().
Referenced by geos::geomgraph::PlanarGraph::linkResultDirectedEdges().
 {
   // make sure edges are copied to resultAreaEdges list
   getResultAreaEdges();
   // find first area edge (if any) to start linking at
   DirectedEdge *firstOut=nullptr;
   DirectedEdge *incoming=nullptr;
   int state=SCANNING_FOR_INCOMING;
   // link edges in CCW order
   for (std::vector<DirectedEdge*>::iterator
     i=resultAreaEdgeList->begin(), iEnd=resultAreaEdgeList->end();
     i != iEnd;
     ++i)
   {
           DirectedEdge *nextOut=*i;
     assert(nextOut);
     // skip de's that we're not interested in
     if (!nextOut->getLabel().isArea()) continue;
     DirectedEdge *nextIn=nextOut->getSym();
     assert(nextIn);
     // record first outgoing edge, in order to link the last incoming edge
     if (firstOut==nullptr && nextOut->isInResult()) firstOut=nextOut;
     switch (state) {
       case SCANNING_FOR_INCOMING:
         if (!nextIn->isInResult()) continue;
         incoming=nextIn;
         state=LINKING_TO_OUTGOING;
         break;
       case LINKING_TO_OUTGOING:
         if (!nextOut->isInResult()) continue;
         incoming->setNext(nextOut);
         state=SCANNING_FOR_INCOMING;
         break;
     }
   }
   if (state==LINKING_TO_OUTGOING) {
     if (firstOut==nullptr)
     {
       throw util::TopologyException("no outgoing dirEdge found",
           getCoordinate());
     }
     assert(firstOut->isInResult()); // unable to link last incoming dirEdge
     assert(incoming);
     incoming->setNext(firstOut);
   }
 }
void geos::geomgraph::DirectedEdgeStar::mergeSymLabels ()
For each dirEdge in the star, merge the label from the sym dirEdge into the label.
Definition at line 157 of file DirectedEdgeStar.cpp.
References geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::DirectedEdge::getSym(), and geos::geomgraph::Label::merge().
 {
   EdgeEndStar::iterator endIt=end();
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     assert(*it);
     assert(dynamic_cast<DirectedEdge*>(*it));
     DirectedEdge *de=static_cast<DirectedEdge*>(*it);
     Label& deLabel = de->getLabel();
     DirectedEdge* deSym=de->getSym();
     assert(deSym);
     const Label& labelToMerge = deSym->getLabel();
     deLabel.merge(labelToMerge);
   }
 }
std::string geos::geomgraph::DirectedEdgeStar::print () const override virtual
Reimplemented from geos::geomgraph::EdgeEndStar.
Definition at line 452 of file DirectedEdgeStar.cpp.
References geos::geomgraph::DirectedEdge::getSym(), and geos::geomgraph::DirectedEdge::print().
 {
   std::string out="DirectedEdgeStar: " + getCoordinate().toString();
   EdgeEndStar::iterator endIt=end();
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     assert(*it);
           assert(dynamic_cast<DirectedEdge*>(*it));
           DirectedEdge *de=static_cast<DirectedEdge*>(*it);
     assert(de);
     out+="out ";
     out+=de->print();
     out+="\n";
     out+="in ";
     assert(de->getSym());
     out+=de->getSym()->print();
     out+="\n";
   }
   return out;
 }
void geos::geomgraph::EdgeEndStar::propagateSideLabels (int geomIndex) virtual inherited
RHS is null - LHS must be null too. This must be an edge from the other geometry, which has no location labelling for this geometry. This edge must lie wholly inside or outside the other geometry (which is determined by the current location). Assign both sides to be the current location.
Definition at line 259 of file EdgeEndStar.cpp.
References geos::geomgraph::EdgeEndStar::begin(), geos::geomgraph::EdgeEndStar::end(), geos::geomgraph::EdgeEnd::getCoordinate(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isArea(), geos::geomgraph::Position::LEFT, geos::geomgraph::Position::ON, geos::geomgraph::Position::RIGHT, and geos::geomgraph::Label::setLocation().
Referenced by geos::geomgraph::EdgeEndStar::computeLabelling().
 {
   // Since edges are stored in CCW order around the node,
   // As we move around the ring we move from the right to the
   // left side of the edge
   int startLoc=Location::UNDEF;
   EdgeEndStar::iterator beginIt=begin();
   EdgeEndStar::iterator endIt=end();
   EdgeEndStar::iterator it;
   // initialize loc to location of last L side (if any)
   for (EdgeEndStar::iterator it=beginIt; it!=endIt; ++it)
   {
     EdgeEnd *e=*it;
     assert(e);
     const Label& label = e->getLabel();
     if (label.isArea(geomIndex) &&
         label.getLocation(geomIndex,Position::LEFT) != Location::UNDEF)
     {
       startLoc = label.getLocation(geomIndex, Position::LEFT);
     }
   }
   // no labelled sides found, so no labels to propagate
   if (startLoc==Location::UNDEF) return;
   int currLoc=startLoc;
   for (it=beginIt; it!=endIt; ++it)
   {
     EdgeEnd *e=*it;
     assert(e);
     Label& label = e->getLabel();
     // set null ON values to be in current location
     if (label.getLocation(geomIndex,Position::ON) == Location::UNDEF)
     {
       label.setLocation(geomIndex,Position::ON,currLoc);
     }
     // set side labels (if any)
     // if (label.isArea())  //ORIGINAL
     if (label.isArea(geomIndex))
     {
       int leftLoc=label.getLocation(geomIndex,
         Position::LEFT);
       int rightLoc=label.getLocation(geomIndex,
         Position::RIGHT);
       // if there is a right location, that is the next
       // location to propagate
       if (rightLoc!=Location::UNDEF) {
         if (rightLoc!=currLoc)
           throw util::TopologyException("side location conflict",
             e->getCoordinate());
         if (leftLoc==Location::UNDEF) {
           // found single null side at e->getCoordinate()
           assert(0);
         }
         currLoc=leftLoc;
       } else {
         // found single null side
         assert(label.getLocation(geomIndex,
           Position::LEFT)==Location::UNDEF);
         label.setLocation(geomIndex,Position::RIGHT,
           currLoc);
         label.setLocation(geomIndex,Position::LEFT,
           currLoc);
       }
     }
   }
 }
EdgeEndStar::reverse_iterator geos::geomgraph::EdgeEndStar::rbegin () inline virtual inherited
Definition at line 185 of file EdgeEndStar.h.
Referenced by geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent().
 {
   return edgeMap.rbegin();
 }
EdgeEndStar::reverse_iterator geos::geomgraph::EdgeEndStar::rend () inline virtual inherited
Definition at line 173 of file EdgeEndStar.h.
 {
   return edgeMap.rend();
 }
void geos::geomgraph::DirectedEdgeStar::updateLabelling (const Label & nodeLabel)
Update incomplete dirEdge labels from the labelling for the node.
Definition at line 178 of file DirectedEdgeStar.cpp.
References geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), and geos::geomgraph::Label::setAllLocationsIfNull().
Referenced by geos::operation::overlay::OverlayOp::labelIncompleteNodes().
 {
   EdgeEndStar::iterator endIt=end();
   for (EdgeEndStar::iterator it=begin(); it!=endIt; ++it)
   {
     DirectedEdge *de=dynamic_cast<DirectedEdge*>(*it);
     assert(de);
     Label& deLabel = de->getLabel();
     deLabel.setAllLocationsIfNull(0, nodeLabel.getLocation(0));
     deLabel.setAllLocationsIfNull(1, nodeLabel.getLocation(1));
   }
 }
Member Data Documentation
EdgeEndStar::container geos::geomgraph::EdgeEndStar::edgeMap protected inherited
A map which maintains the edges in sorted order around the node.
Definition at line 129 of file EdgeEndStar.h.
Referenced by geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent(), and geos::geomgraph::EdgeEndStar::getCoordinate().
Label geos::geomgraph::DirectedEdgeStar::label private
Definition at line 144 of file DirectedEdgeStar.h.
std::vector<DirectedEdge*>* geos::geomgraph::DirectedEdgeStar::resultAreaEdgeList private
A list of all outgoing edges in the result, in CCW order
Definition at line 142 of file DirectedEdgeStar.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/DirectedEdgeStar.h
/home/vicky/potree/geos/vicky/src/geomgraph/DirectedEdgeStar.cpp