GEOS: geos::operation::overlay::MinimalEdgeRing Class Reference
geos::operation::overlay::MinimalEdgeRing Class Reference
A ring of Edges with the property that no node has degree greater than 2.
#include <MinimalEdgeRing.h>
Public Member Functions
MinimalEdgeRing (geomgraph::DirectedEdge *start, const geom::GeometryFactory *geometryFactory)
~MinimalEdgeRing () override
geomgraph::DirectedEdge * getNext (geomgraph::DirectedEdge *de) override
void setEdgeRing (geomgraph::DirectedEdge *de, geomgraph::EdgeRing *er) override
bool isIsolated ()
bool isHole ()
geom::LinearRing * getLinearRing ()
Label & getLabel ()
bool isShell ()
EdgeRing * getShell ()
void setShell (EdgeRing *newShell)
void addHole (EdgeRing *edgeRing)
geom::Polygon * toPolygon (const geom::GeometryFactory *geometryFactory)
void computeRing ()
std::vector< DirectedEdge * > & getEdges ()
int getMaxNodeDegree ()
void setInResult ()
bool containsPoint (const geom::Coordinate &p)
void testInvariant ()
Protected Member Functions
void computePoints (DirectedEdge *newStart)
throw(const TopologyException &)
void mergeLabel (const Label &deLabel)
void mergeLabel (const Label &deLabel, int geomIndex)
Merge the RHS label from a DirectedEdge into the label for this EdgeRing.
void addPoints (Edge *edge, bool isForward, bool isFirstEdge)
Protected Attributes
DirectedEdge * startDe
const geom::GeometryFactory * geometryFactory
std::vector< EdgeRing * > holes
a list of EdgeRings which are holes in this EdgeRing
Detailed Description
A ring of Edges with the property that no node has degree greater than 2.
These are the form of rings required to represent polygons under the OGC SFS spatial data model.
See also
operation::overlay::MaximalEdgeRing
Definition at line 56 of file MinimalEdgeRing.h.
Constructor & Destructor Documentation
geos::operation::overlay::MinimalEdgeRing::MinimalEdgeRing (geomgraph::DirectedEdge * start, const geom::GeometryFactory * geometryFactory)
Definition at line 39 of file MinimalEdgeRing.cpp.
References geos::geomgraph::EdgeRing::computePoints(), and geos::geomgraph::EdgeRing::computeRing().
   :
   geomgraph::EdgeRing(start, geometryFactory)
 {
   computePoints(start);
   computeRing();
 #if GEOS_DEBUG
   std::cerr << "MinimalEdgeRing[" << this << "] ctor" << std::endl;
 #endif
 }
INLINE geos::operation::overlay::MinimalEdgeRing::~MinimalEdgeRing () override
Definition at line 45 of file MinimalEdgeRing.inl.
 {
 #if GEOS_DEBUG
   std::cerr << "MinimalEdgeRing[" << this << "] dtor" << std::endl;
 #endif
 }
Member Function Documentation
void geos::geomgraph::EdgeRing::addHole (EdgeRing * edgeRing) inherited
Definition at line 171 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::holes, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::geomgraph::EdgeRing::setShell().
 {
   holes.push_back(edgeRing);
   testInvariant();
 }
void geos::geomgraph::EdgeRing::addPoints (Edge * edge, bool isForward, bool isFirstEdge) protected inherited
Definition at line 333 of file EdgeRing.cpp.
References geos::geom::CoordinateSequence::add(), geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), geos::geom::CoordinateSequence::getSize(), geos::geomgraph::EdgeRing::pts, geos::geomgraph::EdgeRing::ring, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::geomgraph::EdgeRing::computePoints().
 {
   // EdgeRing::addPoints: can't add points after LinearRing construction
   assert(ring==nullptr);
   assert(edge);
   const CoordinateSequence* edgePts=edge->getCoordinates();
   assert(edgePts);
   size_t numEdgePts=edgePts->getSize();
   assert(pts);
   if (isForward) {
     size_t startIndex=1;
     if (isFirstEdge) startIndex=0;
     for (size_t i=startIndex; i<numEdgePts; ++i)
     {
       pts->add(edgePts->getAt(i));
     }
   }
   else { // is backward
     size_t startIndex=numEdgePts-1;
     if (isFirstEdge) startIndex=numEdgePts;
     //for (int i=startIndex;i>=0;i--)
     for (size_t i=startIndex; i>0; --i)
     {
       pts->add(edgePts->getAt(i-1));
     }
   }
   testInvariant();
 }
void geos::geomgraph::EdgeRing::computePoints (DirectedEdge * newStart) protected inherited
throw(const TopologyException &)
Definition at line 224 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::addPoints(), geos::geomgraph::EdgeRing::edges, geos::geomgraph::EdgeEnd::getCoordinate(), geos::geomgraph::EdgeEnd::getEdge(), geos::geomgraph::DirectedEdge::getEdgeRing(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::EdgeRing::getNext(), geos::geomgraph::Label::isArea(), geos::geomgraph::DirectedEdge::isForward(), geos::geomgraph::EdgeRing::mergeLabel(), geos::geomgraph::EdgeRing::setEdgeRing(), geos::geomgraph::EdgeRing::startDe, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::MaximalEdgeRing::MaximalEdgeRing(), and MinimalEdgeRing().
 {
   startDe=newStart;
   DirectedEdge *de=newStart;
   bool isFirstEdge=true;
   do {
     //util::Assert::isTrue(de!=NULL,"EdgeRing::computePoints: found null Directed Edge");
     //assert(de!=NULL); // EdgeRing::computePoints: found null Directed Edge
     if(de==nullptr)
       throw util::TopologyException(
         "EdgeRing::computePoints: found null Directed Edge");
     if (de->getEdgeRing()==this)
       throw util::TopologyException(
         "Directed Edge visited twice during ring-building",
         de->getCoordinate());
     edges.push_back(de);
     const Label& deLabel = de->getLabel();
     assert(deLabel.isArea());
     mergeLabel(deLabel);
     addPoints(de->getEdge(),de->isForward(),isFirstEdge);
     isFirstEdge=false;
     setEdgeRing(de,this);
     de=getNext(de);
   } while (de!=startDe);
   testInvariant();
 }
void geos::geomgraph::EdgeRing::computeRing () inherited
Compute a LinearRing from the point list previously collected. Test if the ring is a hole (i.e. if it is CCW) and set the hole flag accordingly.
Definition at line 201 of file EdgeRing.cpp.
References geos::geom::GeometryFactory::createLinearRing(), geos::geomgraph::EdgeRing::geometryFactory, geos::algorithm::CGAlgorithms::isCCW(), geos::geomgraph::EdgeRing::isHoleVar, geos::geomgraph::EdgeRing::pts, geos::geomgraph::EdgeRing::ring, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::MaximalEdgeRing::MaximalEdgeRing(), and MinimalEdgeRing().
 {
   testInvariant();
   if (ring!=nullptr) return;   // don't compute more than once
   ring=geometryFactory->createLinearRing(pts);
   isHoleVar=CGAlgorithms::isCCW(pts);
   testInvariant();
 }
bool geos::geomgraph::EdgeRing::containsPoint (const geom::Coordinate & p) inherited
This method will use the computed ring. It will also check any holes, if they have been assigned.
Definition at line 371 of file EdgeRing.cpp.
References geos::geom::Envelope::contains(), geos::geomgraph::EdgeRing::containsPoint(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getEnvelopeInternal(), geos::geomgraph::EdgeRing::holes, geos::algorithm::CGAlgorithms::isPointInRing(), geos::geomgraph::EdgeRing::ring, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::PolygonBuilder::containsPoint(), and geos::geomgraph::EdgeRing::containsPoint().
 {
   testInvariant();
   assert(ring);
   const Envelope* env=ring->getEnvelopeInternal();
   assert(env);
   if ( ! env->contains(p) ) return false;
   if ( ! CGAlgorithms::isPointInRing(p, ring->getCoordinatesRO()) )
     return false;
   for (vector<EdgeRing*>::iterator i=holes.begin(); i<holes.end(); ++i)
   {
     EdgeRing *hole=*i;
     assert(hole);
     if (hole->containsPoint(p))
     {
       return false;
     }
   }
   return true;
 }
vector< DirectedEdge * > & geos::geomgraph::EdgeRing::getEdges () inherited
Returns the list of DirectedEdges that make up this EdgeRing
Definition at line 215 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::edges, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::valid::ConnectedInteriorTester::hasUnvisitedShellEdge().
 {
   testInvariant();
   return edges;
 }
Label & geos::geomgraph::EdgeRing::getLabel () inherited
Definition at line 142 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::label, and geos::geomgraph::EdgeRing::testInvariant().
 {
   testInvariant();
   return label;
 }
LinearRing * geos::geomgraph::EdgeRing::getLinearRing () inherited
Definition at line 134 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::ring, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::PolygonBuilder::findEdgeRingContaining(), and geos::geomgraph::EdgeRing::toPolygon().
 {
   testInvariant();
 //  return new LinearRing(*ring);
   return ring;
 }
int geos::geomgraph::EdgeRing::getMaxNodeDegree () inherited
Definition at line 258 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::computeMaxNodeDegree(), geos::geomgraph::EdgeRing::maxNodeDegree, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::PolygonBuilder::buildMinimalEdgeRings().
 {
   testInvariant();
   if (maxNodeDegree<0) computeMaxNodeDegree();
   return maxNodeDegree;
 }
INLINE geomgraph::DirectedEdge * geos::operation::overlay::MinimalEdgeRing::getNext (geomgraph::DirectedEdge * de) override virtual
Implements geos::geomgraph::EdgeRing.
Definition at line 39 of file MinimalEdgeRing.inl.
References geos::geomgraph::DirectedEdge::getNextMin(), and INLINE.
 {
   return de->getNextMin();
 }
EdgeRing * geos::geomgraph::EdgeRing::getShell () inherited
Definition at line 156 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::shell, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::PolygonBuilder::placeFreeHoles(), and geos::geomgraph::EdgeRing::testInvariant().
 {
   testInvariant();
   return shell;
 }
bool geos::geomgraph::EdgeRing::isHole () inherited
Definition at line 120 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::isHoleVar, geos::geomgraph::EdgeRing::ring, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::PolygonBuilder::findShell(), geos::operation::valid::ConnectedInteriorTester::hasUnvisitedShellEdge(), geos::operation::overlay::PolygonBuilder::placePolygonHoles(), and geos::operation::overlay::PolygonBuilder::sortShellsAndHoles().
 {
   testInvariant();
   // We can't tell if this is an hole
   // unless we computed the ring
   // see computeRing()
   assert(ring);
   return isHoleVar;
 }
bool geos::geomgraph::EdgeRing::isIsolated () inherited
Definition at line 113 of file EdgeRing.cpp.
References geos::geomgraph::Label::getGeometryCount(), geos::geomgraph::EdgeRing::label, and geos::geomgraph::EdgeRing::testInvariant().
 {
   testInvariant();
   return (label.getGeometryCount()==1);
 }
bool geos::geomgraph::EdgeRing::isShell () inherited
Definition at line 149 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::shell, and geos::geomgraph::EdgeRing::testInvariant().
 {
   testInvariant();
   return (shell==nullptr);
 }
void geos::geomgraph::EdgeRing::mergeLabel (const Label & deLabel) protected inherited
Definition at line 304 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::geomgraph::EdgeRing::computePoints().
 {
   mergeLabel(deLabel, 0);
   mergeLabel(deLabel, 1);
   testInvariant();
 }
void geos::geomgraph::EdgeRing::mergeLabel (const Label & deLabel, int geomIndex) protected inherited
Merge the RHS label from a DirectedEdge into the label for this EdgeRing.
The DirectedEdge label may be null. This is acceptable - it results from a node which is NOT an intersection node between the Geometries (e.g. the end node of a LinearRing). In this case the DirectedEdge label does not contribute any information to the overall labelling, and is simply skipped.
Definition at line 315 of file EdgeRing.cpp.
References geos::geomgraph::Label::getLocation(), geos::geomgraph::EdgeRing::label, geos::geomgraph::Position::RIGHT, geos::geomgraph::Label::setLocation(), and geos::geomgraph::EdgeRing::testInvariant().
 {
   testInvariant();
   int loc=deLabel.getLocation(geomIndex, Position::RIGHT);
   // no information to be had from this label
   if (loc==Location::UNDEF) return;
   // if there is no current RHS value, set it
   if (label.getLocation(geomIndex)==Location::UNDEF) {
     label.setLocation(geomIndex,loc);
     return;
   }
 }
INLINE void geos::operation::overlay::MinimalEdgeRing::setEdgeRing (geomgraph::DirectedEdge * de, geomgraph::EdgeRing * er) override virtual
Implements geos::geomgraph::EdgeRing.
Definition at line 33 of file MinimalEdgeRing.inl.
References INLINE, and geos::geomgraph::DirectedEdge::setMinEdgeRing().
 {
   de->setMinEdgeRing(er);
 }
void geos::geomgraph::EdgeRing::setInResult () inherited
Definition at line 290 of file EdgeRing.cpp.
References geos::geomgraph::EdgeEnd::getEdge(), geos::geomgraph::DirectedEdge::getNext(), geos::geomgraph::GraphComponent::setInResult(), geos::geomgraph::EdgeRing::startDe, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::PolygonBuilder::buildMaximalEdgeRings().
 {
   DirectedEdge *de=startDe;
   do {
     de->getEdge()->setInResult(true);
     de=de->getNext();
   } while (de!=startDe);
   testInvariant();
 }
void geos::geomgraph::EdgeRing::setShell (EdgeRing * newShell) inherited
Definition at line 163 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::addHole(), geos::geomgraph::EdgeRing::shell, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::PolygonBuilder::placeFreeHoles(), and geos::operation::overlay::PolygonBuilder::placePolygonHoles().
 {
   shell=newShell;
   if (shell!=nullptr) shell->addHole(this);
   testInvariant();
 }
void geos::geomgraph::EdgeRing::testInvariant () inline inherited
Definition at line 123 of file EdgeRing.h.
References geos::geomgraph::EdgeRing::getShell().
Referenced by geos::geomgraph::EdgeRing::addHole(), geos::geomgraph::EdgeRing::addPoints(), geos::geomgraph::EdgeRing::computeMaxNodeDegree(), geos::geomgraph::EdgeRing::computePoints(), geos::geomgraph::EdgeRing::computeRing(), geos::geomgraph::EdgeRing::containsPoint(), geos::geomgraph::EdgeRing::EdgeRing(), geos::geomgraph::EdgeRing::getEdges(), geos::geomgraph::EdgeRing::getLabel(), geos::geomgraph::EdgeRing::getLinearRing(), geos::geomgraph::EdgeRing::getMaxNodeDegree(), geos::geomgraph::EdgeRing::getShell(), geos::geomgraph::EdgeRing::isHole(), geos::geomgraph::EdgeRing::isIsolated(), geos::geomgraph::EdgeRing::isShell(), geos::geomgraph::EdgeRing::mergeLabel(), geos::geomgraph::EdgeRing::setInResult(), geos::geomgraph::EdgeRing::setShell(), geos::geomgraph::EdgeRing::toPolygon(), and geos::geomgraph::EdgeRing::~EdgeRing().
   {
     // pts are never NULL
     assert(pts);
 #ifndef NDEBUG
     // If this is not an hole, check that
     // each hole is not null and
     // has 'this' as it's shell
     if ( ! shell )
     {
       for (std::vector<EdgeRing*>::const_iterator
         it=holes.begin(), itEnd=holes.end();
         it != itEnd;
         ++it)
       {
         EdgeRing* hole=*it;
         assert(hole);
         assert(hole->getShell()==this);
       }
     }
 #endif // ndef NDEBUG
   }
Polygon * geos::geomgraph::EdgeRing::toPolygon (const geom::GeometryFactory * geometryFactory) inherited
Return a Polygon copying coordinates from this EdgeRing and its holes. Caller must remember to delete the result
Definition at line 179 of file EdgeRing.cpp.
References geos::geom::GeometryFactory::createPolygon(), geos::geomgraph::EdgeRing::getLinearRing(), geos::geomgraph::EdgeRing::holes, and geos::geomgraph::EdgeRing::testInvariant().
Referenced by geos::operation::overlay::PolygonBuilder::computePolygons(), and geos::operation::overlay::PolygonBuilder::placeFreeHoles().
 {
   testInvariant();
   size_t nholes=holes.size();
   vector<Geometry *> *holeLR=new vector<Geometry *>(nholes);
   for (size_t i=0; i<nholes; ++i)
   {
     Geometry *hole=holes[i]->getLinearRing()->clone();
           (*holeLR)[i]=hole;
   }
   // We don't use "clone" here because
   // GeometryFactory::createPolygon really
   // wants a LinearRing
   //
   LinearRing *shellLR=new LinearRing(*(getLinearRing()));
   return geometryFactory->createPolygon(shellLR, holeLR);
 }
Member Data Documentation
const geom::GeometryFactory* geos::geomgraph::EdgeRing::geometryFactory protected inherited
Definition at line 151 of file EdgeRing.h.
Referenced by geos::operation::overlay::MaximalEdgeRing::buildMinimalRings(), and geos::geomgraph::EdgeRing::computeRing().
std::vector<EdgeRing*> geos::geomgraph::EdgeRing::holes protected inherited
a list of EdgeRings which are holes in this EdgeRing
Definition at line 175 of file EdgeRing.h.
Referenced by geos::geomgraph::EdgeRing::addHole(), geos::geomgraph::EdgeRing::containsPoint(), geos::geomgraph::EdgeRing::toPolygon(), and geos::geomgraph::EdgeRing::~EdgeRing().
DirectedEdge* geos::geomgraph::EdgeRing::startDe protected inherited
Definition at line 149 of file EdgeRing.h.
Referenced by geos::operation::overlay::MaximalEdgeRing::buildMinimalRings(), geos::geomgraph::EdgeRing::computeMaxNodeDegree(), geos::geomgraph::EdgeRing::computePoints(), geos::operation::overlay::MaximalEdgeRing::linkDirectedEdgesForMinimalEdgeRings(), and geos::geomgraph::EdgeRing::setInResult().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/MinimalEdgeRing.h
/home/vicky/potree/geos/vicky/src/operation/overlay/MinimalEdgeRing.cpp
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/MinimalEdgeRing.inl