GEOS: geos::index::intervalrtree::IntervalRTreeNode Class Reference
geos::index::intervalrtree::IntervalRTreeNode Class Reference abstract
#include <IntervalRTreeNode.h>
Public Types
typedef std::vector< const IntervalRTreeNode * > ConstVect
Public Member Functions
IntervalRTreeNode ()
IntervalRTreeNode (double min, double max)
virtual ~IntervalRTreeNode ()
double getMin () const
double getMax () const
virtual void query (double queryMin, double queryMax, ItemVisitor *visitor) const =0
Static Public Member Functions
static bool compare (const IntervalRTreeNode *n1, const IntervalRTreeNode *n2)
Protected Member Functions
bool intersects (double queryMin, double queryMax) const
Protected Attributes
double min
double max
Detailed Description
Definition at line 35 of file IntervalRTreeNode.h.
Member Typedef Documentation
typedef std::vector<const IntervalRTreeNode *> geos::index::intervalrtree::IntervalRTreeNode::ConstVect
Definition at line 51 of file IntervalRTreeNode.h.
Constructor & Destructor Documentation
geos::index::intervalrtree::IntervalRTreeNode::IntervalRTreeNode () inline
Definition at line 53 of file IntervalRTreeNode.h.
   : min( DoubleInfinity ),
     max( DoubleNegInfinity )
   { }
geos::index::intervalrtree::IntervalRTreeNode::IntervalRTreeNode (double min, double max) inline
Definition at line 58 of file IntervalRTreeNode.h.
   : min( min ),
     max( max )
   { }
virtual geos::index::intervalrtree::IntervalRTreeNode::~IntervalRTreeNode () inline virtual
Definition at line 63 of file IntervalRTreeNode.h.
   { }
Member Function Documentation
static bool geos::index::intervalrtree::IntervalRTreeNode::compare (const IntervalRTreeNode * n1, const IntervalRTreeNode * n2) inline static
Definition at line 87 of file IntervalRTreeNode.h.
References getMax(), and getMin().
Referenced by geos::index::intervalrtree::SortedPackedIntervalRTree::buildTree().
     {
       //IntervalRTreeNode * n1 = dynamic_cast<IntervalRTreeNode *>( o1);
       //IntervalRTreeNode * n2 = dynamic_cast<IntervalRTreeNode *>( o2);
       double mid1 = (n1->getMin() + n1->getMax()) / 2;
       double mid2 = (n2->getMin() + n2->getMax()) / 2;
       //if (mid1 < mid2) return -1;
       //if (mid1 > mid2) return 1;
       //return 0;
       return mid1 > mid2;
     }
double geos::index::intervalrtree::IntervalRTreeNode::getMax () const inline
Definition at line 71 of file IntervalRTreeNode.h.
Referenced by compare().
   {
     return max;
   }
double geos::index::intervalrtree::IntervalRTreeNode::getMin () const inline
Definition at line 66 of file IntervalRTreeNode.h.
Referenced by compare().
   {
     return min;
   }
bool geos::index::intervalrtree::IntervalRTreeNode::intersects (double queryMin, double queryMax) const inline protected
Definition at line 42 of file IntervalRTreeNode.h.
Referenced by geos::index::intervalrtree::IntervalRTreeLeafNode::query(), and geos::index::intervalrtree::IntervalRTreeBranchNode::query().
   {
     if (min > queryMax || max < queryMin)
       return false;
     return true;
   }
virtual void geos::index::intervalrtree::IntervalRTreeNode::query (double queryMin, double queryMax, ItemVisitor * visitor) const pure virtual
Implemented in geos::index::intervalrtree::IntervalRTreeBranchNode, and geos::index::intervalrtree::IntervalRTreeLeafNode.
Referenced by geos::index::intervalrtree::IntervalRTreeBranchNode::query(), and geos::index::intervalrtree::SortedPackedIntervalRTree::query().
Member Data Documentation
double geos::index::intervalrtree::IntervalRTreeNode::max protected
Definition at line 40 of file IntervalRTreeNode.h.
double geos::index::intervalrtree::IntervalRTreeNode::min protected
Definition at line 39 of file IntervalRTreeNode.h.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/index/intervalrtree/IntervalRTreeNode.h