GEOS: geos::noding::ScaledNoder::Scaler Class Reference
geos::noding::ScaledNoder::Scaler Class Reference
Public Member Functions
Scaler (const ScaledNoder &n)
void filter_rw (geom::Coordinate *c) const override
virtual void filter_ro (const Coordinate *)
Public Attributes
const ScaledNoder & sn
Private Member Functions
Scaler (const Scaler &other)=delete
Scaler & operator= (const Scaler &rhs)=delete
Detailed Description
Definition at line 75 of file ScaledNoder.cpp.
Constructor & Destructor Documentation
geos::noding::ScaledNoder::Scaler::Scaler (const ScaledNoder & n) inline
Definition at line 78 of file ScaledNoder.cpp.
References geos::noding::ScaledNoder::offsetX, geos::noding::ScaledNoder::offsetY, and geos::noding::ScaledNoder::scaleFactor.
                              : sn(n)
   {
 #if GEOS_DEBUG
     std::cerr << "Scaler: offsetX,Y: " << sn.offsetX << ","
       << sn.offsetY << " scaleFactor: " << sn.scaleFactor
       << std::endl;
 #endif
   }
geos::noding::ScaledNoder::Scaler::Scaler (const Scaler & other) private delete
Member Function Documentation
virtual void geos::geom::CoordinateFilter::filter_ro (const Coordinate *) inline virtual inherited
Performs an operation with coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented in geos::operation::overlay::PointCoveredByAny, geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter, geos::noding::ScaledNoder::ReScaler, geos::precision::CommonCoordinateFilter, geos::operation::overlay::ElevationMatrixFilter, geos::util::UniqueCoordinateArrayFilter, geos::precision::Translater, and geos::util::CoordinateArrayFilter.
Definition at line 59 of file CoordinateFilter.h.
Referenced by geos::geom::CoordinateArraySequence::apply_ro(), and geos::geom::Point::apply_ro().
 { assert(0); }
void geos::noding::ScaledNoder::Scaler::filter_rw (geom::Coordinate *) const inline override virtual
Performs an operation on coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented from geos::geom::CoordinateFilter.
Definition at line 89 of file ScaledNoder.cpp.
References geos::noding::ScaledNoder::offsetX, geos::noding::ScaledNoder::offsetY, geos::util::round(), geos::noding::ScaledNoder::scaleFactor, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
{
     c->x = util::round( ( c->x - sn.offsetX ) * sn.scaleFactor );
     c->y = util::round( ( c->y - sn.offsetY ) * sn.scaleFactor );
   }
Scaler& geos::noding::ScaledNoder::Scaler::operator= (const Scaler & rhs) private delete
Member Data Documentation
const ScaledNoder& geos::noding::ScaledNoder::Scaler::sn
Definition at line 77 of file ScaledNoder.cpp.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/noding/ScaledNoder.cpp