GEOS: geos::linearref::LengthLocationMap Class Reference
geos::linearref::LengthLocationMap Class Reference
#include <LengthLocationMap.h>
Public Member Functions
LengthLocationMap (const geom::Geometry *linearGeom)
LinearLocation getLocation (double length, bool resolveLower) const
Compute the LinearLocation corresponding to a length.
LinearLocation getLocation (double length) const
Compute the LinearLocation corresponding to a length.
double getLength (const LinearLocation &loc) const
Static Public Member Functions
static LinearLocation getLocation (const geom::Geometry *linearGeom, double length)
Computes the LinearLocation for a given length along a linear Geometry.
static LinearLocation getLocation (const geom::Geometry *linearGeom, double length, bool resolveLower)
Computes the LinearLocation for a given length along a linear Geometry.
static double getLength (const geom::Geometry *linearGeom, const LinearLocation &loc)
Private Member Functions
LinearLocation getLocationForward (double length) const
LinearLocation resolveHigher (const LinearLocation &loc) const
Private Attributes
const geom::Geometry * linearGeom
Detailed Description
Computes the LinearLocation for a given length along a linear Geometry. Negative lengths are measured in reverse from end of the linear geometry. Out-of-range values are clamped.
Definition at line 37 of file LengthLocationMap.h.
Constructor & Destructor Documentation
geos::linearref::LengthLocationMap::LengthLocationMap (const geom::Geometry * linearGeom)
Definition at line 44 of file LengthLocationMap.cpp.
Referenced by getLocation().
                                                                :
     linearGeom(linearGeom) {}
Member Function Documentation
double geos::linearref::LengthLocationMap::getLength (const geom::Geometry * linearGeom, const LinearLocation & loc) static
Computes the length for a given LinearLocation on a linear Geometry.
Parameters
line the linear geometry to use
loc the LinearLocation index of the location
Returns
the length for the LinearLocation
Definition at line 37 of file LengthLocationMap.cpp.
References getLength().
Referenced by getLength(), getLocation(), and geos::linearref::LengthIndexedLine::indicesOf().
 {
   LengthLocationMap locater(linearGeom);
   return locater.getLength(loc);
 }
double geos::linearref::LengthLocationMap::getLength (const LinearLocation & loc) const
Definition at line 146 of file LengthLocationMap.cpp.
References geos::geom::Coordinate::distance(), geos::linearref::LinearIterator::getComponentIndex(), geos::linearref::LinearLocation::getComponentIndex(), geos::linearref::LinearIterator::getSegmentEnd(), geos::linearref::LinearLocation::getSegmentFraction(), geos::linearref::LinearLocation::getSegmentIndex(), geos::linearref::LinearIterator::getSegmentStart(), geos::linearref::LinearIterator::getVertexIndex(), geos::linearref::LinearIterator::hasNext(), geos::linearref::LinearIterator::isEndOfLine(), linearGeom, and geos::linearref::LinearIterator::next().
 {
   double totalLength = 0.0;
   LinearIterator it(linearGeom);
   while (it.hasNext())
   {
     if (! it.isEndOfLine())
     {
       Coordinate p0 = it.getSegmentStart();
       Coordinate p1 = it.getSegmentEnd();
       double segLen = p1.distance(p0);
       // length falls in this segment
       if (loc.getComponentIndex() == it.getComponentIndex()
           && loc.getSegmentIndex() == it.getVertexIndex())
       {
         return totalLength + segLen * loc.getSegmentFraction();
       }
       totalLength += segLen;
     }
     it.next();
   }
   return totalLength;
 }
static LinearLocation geos::linearref::LengthLocationMap::getLocation (const geom::Geometry * linearGeom, double length) inline static
Computes the LinearLocation for a given length along a linear Geometry.
Parameters
line the linear geometry to use
length the length index of the location
Returns
the LinearLocation for the length
Definition at line 63 of file LengthLocationMap.h.
References getLocation().
Referenced by geos::linearref::LengthIndexedLine::extractPoint(), getLocation(), and geos::linearref::LengthIndexedLine::locationOf().
   {
     LengthLocationMap locater(linearGeom);
     return locater.getLocation(length);
   }
static LinearLocation geos::linearref::LengthLocationMap::getLocation (const geom::Geometry * linearGeom, double length, bool resolveLower) inline static
Computes the LinearLocation for a given length along a linear Geometry.
Parameters
line the linear geometry to use
length the length index of the location
resolveLower if true lengths are resolved to the lowest possible index
Returns
the LinearLocation for the length
Definition at line 80 of file LengthLocationMap.h.
References getLength(), getLocation(), and LengthLocationMap().
   {
     LengthLocationMap locater(linearGeom);
     return locater.getLocation(length, resolveLower);
   }
LinearLocation geos::linearref::LengthLocationMap::getLocation (double length, bool resolveLower) const
Compute the LinearLocation corresponding to a length.
Negative lengths are measured in reverse from end of the linear geometry. Out-of-range values are clamped. Ambiguous indexes are resolved to the lowest possible location value, depending on the value of resolveLower.
Parameters
length the length index
Returns
the corresponding LinearLocation
Definition at line 60 of file LengthLocationMap.cpp.
References geos::geom::Geometry::getLength(), getLocationForward(), linearGeom, and resolveHigher().
 {
   double forwardLength = length;
   // negative values are measured from end of geometry
   if (length < 0.0)
   {
     double lineLen = linearGeom->getLength();
     forwardLength = lineLen + length;
   }
   LinearLocation loc = getLocationForward(forwardLength);
   if (resolveLower) {
     return loc;
   }
   return resolveHigher(loc);
 }
LinearLocation geos::linearref::LengthLocationMap::getLocation (double length) const
Compute the LinearLocation corresponding to a length.
Negative lengths are measured in reverse from end of the linear geometry. Out-of-range values are clamped. Ambiguous indexes are resolved to the lowest possible location value.
Parameters
length the length index
Returns
the corresponding LinearLocation
Definition at line 48 of file LengthLocationMap.cpp.
References geos::geom::Geometry::getLength(), getLocationForward(), and linearGeom.
 {
   double forwardLength = length;
   if (length < 0.0)
   {
     double lineLen = linearGeom->getLength();
     forwardLength = lineLen + length;
   }
   return getLocationForward(forwardLength);
 }
LinearLocation geos::linearref::LengthLocationMap::getLocationForward (double length) const private
Special handling is required for the situation when the length references exactly to a component endpoint. In this case, the endpoint location of the current component is returned, rather than the startpoint location of the next component. This produces consistent behaviour with the project method.
Definition at line 80 of file LengthLocationMap.cpp.
References geos::geom::Coordinate::distance(), geos::linearref::LinearIterator::getComponentIndex(), geos::linearref::LinearLocation::getEndLocation(), geos::linearref::LinearIterator::getSegmentEnd(), geos::linearref::LinearIterator::getSegmentStart(), geos::linearref::LinearIterator::getVertexIndex(), geos::linearref::LinearIterator::hasNext(), geos::linearref::LinearIterator::isEndOfLine(), linearGeom, and geos::linearref::LinearIterator::next().
Referenced by getLocation().
 {
   if (length <= 0.0)
     return LinearLocation();
   double totalLength = 0.0;
   LinearIterator it (linearGeom);
   while (it.hasNext())
   {
     if (it.isEndOfLine()) {
       if (totalLength == length) {
         unsigned int compIndex = it.getComponentIndex();
         unsigned int segIndex = it.getVertexIndex();
         return LinearLocation(compIndex, segIndex, 0.0);
       }
     }
     else {
       Coordinate p0 = it.getSegmentStart();
       Coordinate p1 = it.getSegmentEnd();
       double segLen = p1.distance(p0);
       // length falls in this segment
       if (totalLength + segLen > length)
       {
         double frac = (length - totalLength) / segLen;
         unsigned int compIndex = it.getComponentIndex();
         unsigned int segIndex = it.getVertexIndex();
         return LinearLocation(compIndex, segIndex, frac);
       }
       totalLength += segLen;
     }
     it.next();
   }
   // length is longer than line - return end location
   return LinearLocation::getEndLocation(linearGeom);
 }
LinearLocation geos::linearref::LengthLocationMap::resolveHigher (const LinearLocation & loc) const private
Definition at line 128 of file LengthLocationMap.cpp.
References geos::linearref::LinearLocation::getComponentIndex(), geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getLength(), geos::geom::Geometry::getNumGeometries(), geos::linearref::LinearLocation::isEndpoint(), and linearGeom.
Referenced by getLocation().
 {
   if (! loc.isEndpoint(*linearGeom)) return loc;
   unsigned int compIndex = loc.getComponentIndex();
   // if last component can't resolve any higher
   if (compIndex >= linearGeom->getNumGeometries() - 1) return loc;
   do {
     compIndex++;
   } while (compIndex < linearGeom->getNumGeometries() - 1
            && linearGeom->getGeometryN(compIndex)->getLength() == 0);
   // resolve to next higher location
   return LinearLocation(compIndex, 0, 0.0);
 }
Member Data Documentation
const geom::Geometry* geos::linearref::LengthLocationMap::linearGeom private
Definition at line 42 of file LengthLocationMap.h.
Referenced by getLength(), getLocation(), getLocationForward(), and resolveHigher().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/linearref/LengthLocationMap.h
/home/vicky/potree/geos/vicky/src/linearref/LengthLocationMap.cpp