GEOS: geos::operation::geounion::CascadedPolygonUnion Class Reference
geos::operation::geounion::CascadedPolygonUnion Class Reference
Provides an efficient method of unioning a collection of Polygonal geometries. This algorithm is faster and likely more robust than the simple iterated approach of repeatedly unioning each polygon to a result geometry.
#include <CascadedPolygonUnion.h>
Public Member Functions
CascadedPolygonUnion ()
CascadedPolygonUnion (std::vector< geom::Polygon * > *polys)
geom::Geometry * Union ()
Static Public Member Functions
static geom::Geometry * Union (std::vector< geom::Polygon * > *polys)
template<class T >
static geom::Geometry * Union (T start, T end)
static geom::Geometry * Union (const geom::MultiPolygon *polys)
Private Member Functions
geom::Geometry * unionTree (index::strtree::ItemsList *geomTree)
geom::Geometry * binaryUnion (GeometryListHolder *geoms)
geom::Geometry * binaryUnion (GeometryListHolder *geoms, std::size_t start, std::size_t end)
GeometryListHolder * reduceToGeometries (index::strtree::ItemsList *geomTree)
geom::Geometry * unionSafe (geom::Geometry *g0, geom::Geometry *g1)
geom::Geometry * unionOptimized (geom::Geometry *g0, geom::Geometry *g1)
geom::Geometry * unionUsingEnvelopeIntersection (geom::Geometry *g0, geom::Geometry *g1, geom::Envelope const &common)
Unions two polygonal geometries, restricting computation to the envelope intersection where possible.
geom::Geometry * extractByEnvelope (geom::Envelope const &env, geom::Geometry *geom, std::vector< geom::Geometry * > &disjointGeoms)
void extractByEnvelope (geom::Envelope const &env, geom::Geometry *geom, std::vector< geom::Geometry * > &intersectingGeoms, std::vector< geom::Geometry * > &disjointGeoms)
void extractByEnvelope (geom::Envelope const &env, std::vector< geom::Geometry * > &sourceGeoms, std::vector< geom::Geometry * > &intersectingGeoms, std::vector< geom::Geometry * > &disjointGeoms)
Static Private Member Functions
static std::unique_ptr< geom::Geometry > restrictToPolygons (std::unique_ptr< geom::Geometry > g)
static geom::Geometry * unionActual (geom::Geometry *g0, geom::Geometry *g1)
Private Attributes
std::vector< geom::Polygon * > * inputPolys
geom::GeometryFactory const * geomFactory
Static Private Attributes
static int const STRTREE_NODE_CAPACITY = 4
Detailed Description
Provides an efficient method of unioning a collection of Polygonal geometries. This algorithm is faster and likely more robust than the simple iterated approach of repeatedly unioning each polygon to a result geometry.
The buffer(0) trick is sometimes faster, but can be less robust and can sometimes take an exceptionally long time to complete. This is particularly the case where there is a high degree of overlap between the polygons. In this case, buffer(0) is forced to compute with all line segments from the outset, whereas cascading can eliminate many segments at each stage of processing. The best case for buffer(0) is the trivial case where there is no overlap between the input geometries. However, this case is likely rare in practice.
Definition at line 71 of file CascadedPolygonUnion.h.
Constructor & Destructor Documentation
geos::operation::geounion::CascadedPolygonUnion::CascadedPolygonUnion ()
geos::operation::geounion::CascadedPolygonUnion::CascadedPolygonUnion (std::vector< geom::Polygon * > * polys) inline
Creates a new instance to union the given collection of Geometrys.
Parameters
geoms a collection of Polygonal Geometrys ownership of elements and vector are left to caller.
Definition at line 148 of file CascadedPolygonUnion.h.
       : inputPolys(polys),
         geomFactory(nullptr)
     {}
Member Function Documentation
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::binaryUnion (GeometryListHolder * geoms) private
Unions a list of geometries by treating the list as a flattened binary tree, and performing a cascaded union on the tree.
Definition at line 165 of file CascadedPolygonUnion.cpp.
 {
     return binaryUnion(geoms, 0, geoms->size());
 }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::binaryUnion (GeometryListHolder * geoms, std::size_t start, std::size_t end) private
Unions a section of a list using a recursive binary union on each half of the section.
Parameters
geoms the list of geometries containing the section to union
start the start index of the section
end the index after the end of the section
Returns
the union of the list section
Definition at line 170 of file CascadedPolygonUnion.cpp.
References geos::operation::geounion::GeometryListHolder::getGeometry().
 {
     if (end - start <= 1) {
         return unionSafe(geoms->getGeometry(start), nullptr);
     }
     else if (end - start == 2) {
         return unionSafe(geoms->getGeometry(start), geoms->getGeometry(start + 1));
     }
     else {
         // recurse on both halves of the list
         std::size_t mid = (end + start) / 2;
         std::unique_ptr<geom::Geometry> g0 (binaryUnion(geoms, start, mid));
         std::unique_ptr<geom::Geometry> g1 (binaryUnion(geoms, mid, end));
         return unionSafe(g0.get(), g1.get());
     }
 }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope (geom::Envelope const & env, geom::Geometry * geom, std::vector< geom::Geometry * > & disjointGeoms) private
Definition at line 358 of file CascadedPolygonUnion.cpp.
 {
     std::vector<geom::Geometry*> intersectingGeoms;
     extractByEnvelope(env, geom, intersectingGeoms, disjointGeoms);
     return geomFactory->buildGeometry(intersectingGeoms);
 }
void geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope (geom::Envelope const & env, geom::Geometry * geom, std::vector< geom::Geometry * > & intersectingGeoms, std::vector< geom::Geometry * > & disjointGeoms) private
Definition at line 342 of file CascadedPolygonUnion.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getNumGeometries(), and geos::geom::Envelope::intersects().
 {
     for (std::size_t i = 0; i < geom->getNumGeometries(); i++) {
         geom::Geometry* elem = const_cast<geom::Geometry*>(geom->getGeometryN(i));
         if (elem->getEnvelopeInternal()->intersects(env))
             intersectingGeoms.push_back(elem);
         else
             disjointGeoms.push_back(elem);
     }
 }
void geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope (geom::Envelope const & env, std::vector< geom::Geometry * > & sourceGeoms, std::vector< geom::Geometry * > & intersectingGeoms, std::vector< geom::Geometry * > & disjointGeoms) private
Definition at line 324 of file CascadedPolygonUnion.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), and geos::geom::Envelope::intersects().
 {
     for (std::vector<geom::Geometry*>::iterator i=sourceGeoms.begin(),
          e=sourceGeoms.end(); i!=e; ++i)
     {
         geom::Geometry* elem = *i;
         if (elem->getEnvelopeInternal()->intersects(env))
             intersectingGeoms.push_back(elem);
         else
             disjointGeoms.push_back(elem);
     }
 }
GeometryListHolder * geos::operation::geounion::CascadedPolygonUnion::reduceToGeometries (index::strtree::ItemsList * geomTree) private
Reduces a tree of geometries to a list of geometries by recursively unioning the subtrees in the list.
Parameters
geomTree a tree-structured list of geometries
Returns
a list of Geometrys
Definition at line 189 of file CascadedPolygonUnion.cpp.
References geos::operation::geounion::GeometryListHolder::GeometryListHolder(), geos::index::strtree::ItemsListItem::item_is_geometry, and geos::index::strtree::ItemsListItem::item_is_list.
 {
     std::unique_ptr<GeometryListHolder> geoms (new GeometryListHolder());
     typedef index::strtree::ItemsList::iterator iterator_type;
     iterator_type end = geomTree->end();
     for (iterator_type i = geomTree->begin(); i != end; ++i) {
         if ((*i).get_type() == index::strtree::ItemsListItem::item_is_list) {
             std::unique_ptr<geom::Geometry> geom (unionTree((*i).get_itemslist()));
             geoms->push_back_owned(geom.get());
             geom.release();
         }
         else if ((*i).get_type() == index::strtree::ItemsListItem::item_is_geometry) {
             geoms->push_back(reinterpret_cast<geom::Geometry*>((*i).get_geometry()));
         }
         else {
             assert(!static_cast<bool>("should never be reached"));
         }
     }
     return geoms.release();
 }
std::unique_ptr< geom::Geometry > geos::operation::geounion::CascadedPolygonUnion::restrictToPolygons (std::unique_ptr< geom::Geometry > g) static private
Computes a Geometry containing only Polygonal components.
Extracts the Polygons from the input and returns them as an appropriate Polygonal geometry.
If the input is already Polygonal, it is returned unchanged.
A particular use case is to filter out non-polygonal components returned from an overlay operation.
Parameters
g the geometry to filter
Returns
a Polygonal geometry
Definition at line 374 of file CascadedPolygonUnion.cpp.
References geos::geom::util::PolygonExtracter::getPolygons().
 {
     using namespace geom;
     using namespace std;
     if ( dynamic_cast<Polygonal*>(g.get()) ) {
       return g;
     }
     Polygon::ConstVect polygons;
     geom::util::PolygonExtracter::getPolygons(*g, polygons);
     if (polygons.size() == 1)
       return std::unique_ptr<Geometry>(polygons[0]->clone());
     typedef vector<Geometry *> GeomVect;
     Polygon::ConstVect::size_type n = polygons.size();
     GeomVect* newpolys = new GeomVect(n);
     for (Polygon::ConstVect::size_type i=0; i<n; ++i) {
         (*newpolys)[i] = polygons[i]->clone();
     }
     return unique_ptr<Geometry>(
       g->getFactory()->createMultiPolygon(newpolys)
     );
 }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::Union (std::vector< geom::Polygon * > * polys) static
Computes the union of a collection of Polygonal Geometrys.
Parameters
polys a collection of Polygonal Geometrys. ownership of elements and vector are left to caller.
Definition at line 108 of file CascadedPolygonUnion.cpp.
References Union().
Referenced by Union().
 {
     CascadedPolygonUnion op (polys);
     return op.Union();
 }
template<class T > static geom::Geometry* geos::operation::geounion::CascadedPolygonUnion::Union (T start, T end) inline static
Computes the union of a set of Polygonal Geometrys.
Template Parameters
T an iterator yelding something castable to const Polygon *
Parameters
start start iterator
end end iterator
Definition at line 122 of file CascadedPolygonUnion.h.
     {
       std::vector<geom::Polygon*> polys;
       for (T i=start; i!=end; ++i) {
         const geom::Polygon* p = dynamic_cast<const geom::Polygon*>(*i);
         polys.push_back(const_cast<geom::Polygon*>(p));
       }
       return Union(&polys);
     }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::Union (const geom::MultiPolygon * polys) static
Computes the union of a collection of Polygonal Geometrys.
Parameters
polys a collection of Polygonal Geometrys ownership of elements and vector are left to caller.
Definition at line 114 of file CascadedPolygonUnion.cpp.
References geos::geom::GeometryCollection::begin(), geos::geom::GeometryCollection::end(), and Union().
 {
     std::vector<geom::Polygon*> polys;
     typedef geom::MultiPolygon::const_iterator iterator;
     iterator end = multipoly->end();
     for (iterator i = multipoly->begin(); i != end; ++i)
         polys.push_back(dynamic_cast<geom::Polygon*>(*i));
     CascadedPolygonUnion op (&polys);
     return op.Union();
 }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::Union ()
Computes the union of the input geometries.
Returns
the union of the input geometries
null if no input geometries were provided
A spatial index to organize the collection into groups of close geometries. This makes unioning more efficient, since vertices are more likely to be eliminated on each round.
Definition at line 127 of file CascadedPolygonUnion.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::getFactory(), geos::index::strtree::STRtree::insert(), and geos::index::strtree::AbstractSTRtree::itemsTree().
Referenced by geos::operation::geounion::UnaryUnionOp::Union().
 {
     if (inputPolys->empty())
         return nullptr;
     geomFactory = inputPolys->front()->getFactory();
     index::strtree::STRtree index(STRTREE_NODE_CAPACITY);
     typedef std::vector<geom::Polygon*>::iterator iterator_type;
     iterator_type end = inputPolys->end();
     for (iterator_type i = inputPolys->begin(); i != end; ++i) {
         geom::Geometry* g = dynamic_cast<geom::Geometry*>(*i);
         index.insert(g->getEnvelopeInternal(), g);
     }
     std::unique_ptr<index::strtree::ItemsList> itemTree (index.itemsTree());
     return unionTree(itemTree.get());
 }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::unionActual (geom::Geometry * g0, geom::Geometry * g1) static private
Encapsulates the actual unioning of two polygonal geometries.
Parameters
g0
g1
Returns
Definition at line 368 of file CascadedPolygonUnion.cpp.
References geos::geom::Geometry::Union().
 {
     return restrictToPolygons(std::unique_ptr<geom::Geometry>(g0->Union(g1))).release();
 }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::unionOptimized (geom::Geometry * g0, geom::Geometry * g1) private
Definition at line 227 of file CascadedPolygonUnion.cpp.
References geos::geom::util::GeometryCombiner::combine(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::getNumGeometries(), geos::geom::Envelope::intersection(), and geos::geom::Envelope::intersects().
 {
     geom::Envelope const* g0Env = g0->getEnvelopeInternal();
     geom::Envelope const* g1Env = g1->getEnvelopeInternal();
     if (!g0Env->intersects(g1Env))
         return geom::util::GeometryCombiner::combine(g0, g1);
     if (g0->getNumGeometries() <= 1 && g1->getNumGeometries() <= 1)
         return unionActual(g0, g1);
     geom::Envelope commonEnv;
     g0Env->intersection(*g1Env, commonEnv);
     return unionUsingEnvelopeIntersection(g0, g1, commonEnv);
 }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::unionSafe (geom::Geometry * g0, geom::Geometry * g1) private
Computes the union of two geometries, either of both of which may be null.
Parameters
g0 a Geometry
g1 a Geometry
Returns
the union of the input(s)
null if both inputs are null
Definition at line 213 of file CascadedPolygonUnion.cpp.
References geos::geom::Geometry::clone().
 {
     if (g0 == nullptr && g1 == nullptr)
         return nullptr;
     if (g0 == nullptr)
         return g1->clone();
     if (g1 == nullptr)
         return g0->clone();
     return unionOptimized(g0, g1);
 }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::unionTree (index::strtree::ItemsList * geomTree) private
Recursively unions all subtrees in the list into single geometries. The result is a list of Geometry's only
Definition at line 154 of file CascadedPolygonUnion.cpp.
 {
     std::unique_ptr<GeometryListHolder> geoms(reduceToGeometries(geomTree));
     return binaryUnion(geoms.get());
 }
geom::Geometry * geos::operation::geounion::CascadedPolygonUnion::unionUsingEnvelopeIntersection (geom::Geometry * g0, geom::Geometry * g1, geom::Envelope const & common) private
Unions two polygonal geometries, restricting computation to the envelope intersection where possible.
The case of MultiPolygons is optimized to union only the polygons which lie in the intersection of the two geometry's envelopes. Polygons outside this region can simply be combined with the union result, which is potentially much faster. This case is likely to occur often during cascaded union, and may also occur in real world data (such as unioning data for parcels on different street blocks).
Parameters
g0 a polygonal geometry
g1 a polygonal geometry
common the intersection of the envelopes of the inputs
Returns
the union of the inputs
Definition at line 245 of file CascadedPolygonUnion.cpp.
References geos::geom::check_valid(), and geos::geom::util::GeometryCombiner::combine().
 {
     std::vector<geom::Geometry*> disjointPolys;
 #if GEOS_DEBUG_CASCADED_UNION
     check_valid(*g0, "unionUsingEnvelopeIntersection g0");
     check_valid(*g1, "unionUsingEnvelopeIntersection g1");
 #endif
     std::unique_ptr<geom::Geometry> g0Int(extractByEnvelope(common, g0, disjointPolys));
     std::unique_ptr<geom::Geometry> g1Int(extractByEnvelope(common, g1, disjointPolys));
 #if GEOS_DEBUG_CASCADED_UNION
     check_valid(*g0Int, "unionUsingEnvelopeIntersection g0Int");
     check_valid(*g1Int, "unionUsingEnvelopeIntersection g1Int");
 #endif
     std::unique_ptr<geom::Geometry> u(unionActual(g0Int.get(), g1Int.get()));
 #if GEOS_DEBUG_CASCADED_UNION
     if ( ! check_valid(*u, "unionUsingEnvelopeIntersection unionActual return") )
     {
 #if GEOS_DEBUG_CASCADED_UNION_PRINT_INVALID
       std::cerr << " union between the following is invalid"
         << "<a>" << std::endl
         << *g0Int << std::endl
         << "</a>" << std::endl
         << "<b>" << std::endl
         << *g1Int << std::endl
         << "</b>" << std::endl
         ;
 #endif
     }
 #endif
     if ( disjointPolys.empty() ) return u.release();
 #if GEOS_DEBUG_CASCADED_UNION
     for ( size_t i=0; i<disjointPolys.size(); ++i )
     {
       std::ostringstream os; os << "dp"<< i;
       check_valid(*(disjointPolys[i]), os.str());
     }
 #endif
     // TODO: find, in disjointPolys, those which now have their
     // environment intersect the environment of the union "u"
     // and collect them in another vector to be unioned
     std::vector<geom::Geometry*> polysOn;
     std::vector<geom::Geometry*> polysOff;
     geom::Envelope const* uEnv = u->getEnvelopeInternal(); // TODO: check for EMPTY ?
     extractByEnvelope(*uEnv, disjointPolys, polysOn, polysOff);
 #if GEOS_DEBUG_CASCADED_UNION
     std::cerr << "unionUsingEnvelopeIntersection: " << polysOn.size() << "/" << disjointPolys.size() << " polys intersect union of final thing" << std::endl;
 #endif
     std::unique_ptr<geom::Geometry> ret;
     if ( polysOn.empty() ) {
       disjointPolys.push_back(u.get());
       ret.reset( geom::util::GeometryCombiner::combine(disjointPolys));
     } else {
       // TODO: could be further tweaked to only union with polysOn
       //       and combine with polysOff, but then it'll need again to
       //       recurse in the check for disjoint/intersecting
       ret.reset( geom::util::GeometryCombiner::combine(disjointPolys) );
       ret.reset( unionActual(ret.get(), u.get()) );
     }
 #if GEOS_DEBUG_CASCADED_UNION
     check_valid(*ret, "unionUsingEnvelopeIntersection returned geom");
 #endif
     return ret.release();
 }
Member Data Documentation
geom::GeometryFactory const* geos::operation::geounion::CascadedPolygonUnion::geomFactory private
Definition at line 75 of file CascadedPolygonUnion.h.
std::vector<geom::Polygon*>* geos::operation::geounion::CascadedPolygonUnion::inputPolys private
Definition at line 74 of file CascadedPolygonUnion.h.
int const geos::operation::geounion::CascadedPolygonUnion::STRTREE_NODE_CAPACITY = 4 static private
The effectiveness of the index is somewhat sensitive to the node capacity. Testing indicates that a smaller capacity is better. For an STRtree, 4 is probably a good number (since this produces 2x2 "squares").
Definition at line 84 of file CascadedPolygonUnion.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/union/CascadedPolygonUnion.h
/home/vicky/potree/geos/vicky/src/operation/union/CascadedPolygonUnion.cpp