GEOS: geos::io::WKBWriter Class Reference
geos::io::WKBWriter Class Reference
Writes a Geometry into Well-Known Binary format.
#include <geos.h>
Public Member Functions
WKBWriter (int dims=2, int bo=getMachineByteOrder(), bool includeSRID=false)
virtual ~WKBWriter ()
virtual int getOutputDimension () const
virtual void setOutputDimension (int newOutputDimension)
virtual int getByteOrder () const
virtual void setByteOrder (int newByteOrder)
virtual int getIncludeSRID () const
virtual void setIncludeSRID (int newIncludeSRID)
void write (const geom::Geometry &g, std::ostream &os)
Write a Geometry to an ostream.
void writeHEX (const geom::Geometry &g, std::ostream &os)
Write a Geometry to an ostream in binary hex format.
Private Member Functions
void writePoint (const geom::Point &p)
void writeLineString (const geom::LineString &ls)
void writePolygon (const geom::Polygon &p)
void writeGeometryCollection (const geom::GeometryCollection &c, int wkbtype)
void writeCoordinateSequence (const geom::CoordinateSequence &cs, bool sized)
void writeCoordinate (const geom::CoordinateSequence &cs, int idx, bool is3d)
void writeGeometryType (int geometryType, int SRID)
void writeSRID (int SRID)
void writeByteOrder ()
void writeInt (int intValue)
Private Attributes
int defaultOutputDimension
int outputDimension
int byteOrder
bool includeSRID
std::ostream * outStream
unsigned char buf [8]
Detailed Description
Writes a Geometry into Well-Known Binary format.
The WKB format is specified in the OGC Simple Features for SQL specification. This implementation supports the extended WKB standard for representing 3-dimensional coordinates. The presence of 3D coordinates is signified by setting the high bit of the wkbType word.
Empty Points cannot be represented in WKB; an IllegalArgumentException will be thrown if one is written. The WKB specification does not support representing LinearRing they will be written as LineString
This class is designed to support reuse of a single instance to read multiple geometries. This class is not thread-safe; each thread should create its own instance.
See also
WKBReader
Definition at line 72 of file WKBWriter.h.
Constructor & Destructor Documentation
geos::io::WKBWriter::WKBWriter (int dims = 2, int bo = getMachineByteOrder(), bool includeSRID = false)
Definition at line 47 of file WKBWriter.cpp.
References defaultOutputDimension, and outputDimension.
                                                :
     defaultOutputDimension(dims), byteOrder(bo), includeSRID(srid), outStream(nullptr)
 {
   if ( dims < 2 || dims > 3 )
     throw util::IllegalArgumentException("WKB output dimension must be 2 or 3");
     outputDimension = defaultOutputDimension;
 }
geos::io::WKBWriter::~WKBWriter () virtual
Definition at line 66 of file WKBWriter.cpp.
 {
 }
Member Function Documentation
virtual int geos::io::WKBWriter::getByteOrder () const inline virtual
Definition at line 116 of file WKBWriter.h.
 { return byteOrder; }
virtual int geos::io::WKBWriter::getIncludeSRID () const inline virtual
Definition at line 129 of file WKBWriter.h.
 { return includeSRID; }
virtual int geos::io::WKBWriter::getOutputDimension () const inline virtual
Definition at line 100 of file WKBWriter.h.
 { return defaultOutputDimension; }
void geos::io::WKBWriter::setByteOrder (int newByteOrder) virtual
Definition at line 235 of file WKBWriter.cpp.
References byteOrder, geos::io::ByteOrderValues::ENDIAN_BIG, and geos::io::ByteOrderValues::ENDIAN_LITTLE.
 {
   if (bo != ByteOrderValues::ENDIAN_LITTLE &&
       bo != ByteOrderValues::ENDIAN_BIG )
   {
       std::ostringstream os;
     os << "WKB output dimension must be LITTLE ("
        << ByteOrderValues::ENDIAN_LITTLE
        << ") or BIG (" << ByteOrderValues::ENDIAN_BIG << ")";
     throw util::IllegalArgumentException(os.str());
   }
   byteOrder = bo;
 }
virtual void geos::io::WKBWriter::setIncludeSRID (int newIncludeSRID) inline virtual
Definition at line 135 of file WKBWriter.h.
 { includeSRID = (0 == newIncludeSRID ? false : true); }
void geos::io::WKBWriter::setOutputDimension (int newOutputDimension) virtual
Definition at line 58 of file WKBWriter.cpp.
References defaultOutputDimension.
 {
   if ( dims < 2 || dims > 3 )
     throw util::IllegalArgumentException("WKB output dimension must be 2 or 3");
     defaultOutputDimension = dims;
 }
void geos::io::WKBWriter::write (const geom::Geometry & g, std::ostream & os)
Write a Geometry to an ostream.
Parameters
g the geometry to write
os the output stream
Exceptions
IOException
Definition at line 84 of file WKBWriter.cpp.
References defaultOutputDimension, geos::geom::Geometry::getCoordinateDimension(), outputDimension, outStream, geos::io::WKBConstants::wkbGeometryCollection, geos::io::WKBConstants::wkbMultiLineString, geos::io::WKBConstants::wkbMultiPoint, geos::io::WKBConstants::wkbMultiPolygon, writeGeometryCollection(), writeLineString(), writePoint(), and writePolygon().
Referenced by GEOSGeomToWKB_buf_r(), GEOSWKBWriter_write_r(), writeGeometryCollection(), and writeHEX().
 {
   outputDimension = defaultOutputDimension;
   if( outputDimension > g.getCoordinateDimension() )
     outputDimension = g.getCoordinateDimension();
   outStream = &os;
   if ( const Point* x = dynamic_cast<const Point*>(&g) )
   {
     return writePoint(*x);
   }
   if ( const LineString* x = dynamic_cast<const LineString*>(&g) )
   {
     return writeLineString(*x);
   }
   if ( const Polygon* x = dynamic_cast<const Polygon*>(&g) )
   {
     return writePolygon(*x);
   }
   if ( const MultiPoint* x = dynamic_cast<const MultiPoint*>(&g) )
   {
     return writeGeometryCollection(*x, WKBConstants::wkbMultiPoint);
   }
   if ( const MultiLineString* x = dynamic_cast<const MultiLineString*>(&g) )
   {
     return writeGeometryCollection(*x, WKBConstants::wkbMultiLineString);
   }
   if ( const MultiPolygon* x = dynamic_cast<const MultiPolygon*>(&g) )
   {
     return writeGeometryCollection(*x, WKBConstants::wkbMultiPolygon);
   }
   if ( const GeometryCollection* x =
        dynamic_cast<const GeometryCollection*>(&g) )
   {
     return writeGeometryCollection(*x, WKBConstants::wkbGeometryCollection);
   }
   assert(0); // Unknown Geometry type
 }
void geos::io::WKBWriter::writeByteOrder () private
Definition at line 218 of file WKBWriter.cpp.
References buf, byteOrder, geos::io::ByteOrderValues::ENDIAN_LITTLE, outStream, geos::io::WKBConstants::wkbNDR, and geos::io::WKBConstants::wkbXDR.
Referenced by writeGeometryCollection(), writeLineString(), writePoint(), and writePolygon().
 {
   if (byteOrder == ByteOrderValues::ENDIAN_LITTLE)
   {
     buf[0] = WKBConstants::wkbNDR;
   }
   else
   {
     buf[0] = WKBConstants::wkbXDR;
   }
   assert(outStream);
   outStream->write(reinterpret_cast<char*>(buf), 1);
 }
void geos::io::WKBWriter::writeCoordinate (const geom::CoordinateSequence & cs, int idx, bool is3d) private
Definition at line 290 of file WKBWriter.cpp.
References buf, byteOrder, geos::geom::CoordinateSequence::getOrdinate(), geos::geom::CoordinateSequence::getX(), geos::geom::CoordinateSequence::getY(), outStream, and geos::io::ByteOrderValues::putDouble().
 {
 #if DEBUG_WKB_WRITER
   cout<<"writeCoordinate: X:"<<cs.getX(idx)<<" Y:"<<cs.getY(idx)<<endl;
 #endif
   assert(outStream);
   ByteOrderValues::putDouble(cs.getX(idx), buf, byteOrder);
   outStream->write(reinterpret_cast<char *>(buf), 8);
   ByteOrderValues::putDouble(cs.getY(idx), buf, byteOrder);
   outStream->write(reinterpret_cast<char *>(buf), 8);
   if ( is3d )
   {
     ByteOrderValues::putDouble(
       cs.getOrdinate(idx, CoordinateSequence::Z),
       buf, byteOrder);
     outStream->write(reinterpret_cast<char *>(buf), 8);
   }
 }
void geos::io::WKBWriter::writeCoordinateSequence (const geom::CoordinateSequence & cs, bool sized) private
Definition at line 278 of file WKBWriter.cpp.
References geos::geom::CoordinateSequence::getSize(), outputDimension, and writeInt().
Referenced by writeLineString(), writePoint(), and writePolygon().
 {
   std::size_t size = cs.getSize();
   bool is3d=false;
   if ( outputDimension > 2) is3d = true;
   if (sized) writeInt(static_cast<int>(size));
   for (std::size_t i=0; i<size; i++) writeCoordinate(cs, static_cast<int>(i), is3d);
 }
void geos::io::WKBWriter::writeGeometryCollection (const geom::GeometryCollection & c, int wkbtype) private
Definition at line 196 of file WKBWriter.cpp.
References geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::geom::Geometry::getSRID(), outStream, write(), writeByteOrder(), writeGeometryType(), writeInt(), and writeSRID().
Referenced by write().
 {
   writeByteOrder();
   writeGeometryType(wkbtype, g.getSRID());
   writeSRID(g.getSRID());
   auto ngeoms = g.getNumGeometries();
   writeInt(static_cast<int>(ngeoms));
   assert(outStream);
   for (std::size_t i=0; i<ngeoms; i++)
   {
     const Geometry* elem = g.getGeometryN(i);
     assert(elem);
     write(*elem, *outStream);
   }
 }
void geos::io::WKBWriter::writeGeometryType (int geometryType, int SRID) private
Definition at line 251 of file WKBWriter.cpp.
References includeSRID, outputDimension, and writeInt().
Referenced by writeGeometryCollection(), writeLineString(), writePoint(), and writePolygon().
 {
   int flag3D = (outputDimension == 3) ? 0x80000000 : 0;
   int typeInt = typeId | flag3D;
   if (includeSRID && SRID != 0)
     typeInt = typeInt | 0x20000000;
   writeInt(typeInt);
 }
void geos::io::WKBWriter::writeHEX (const geom::Geometry & g, std::ostream & os)
Write a Geometry to an ostream in binary hex format.
Parameters
g the geometry to write
os the output stream
Exceptions
IOException
Definition at line 71 of file WKBWriter.cpp.
References geos::io::WKBReader::printHEX(), and write().
Referenced by GEOSGeomToHEX_buf_r(), GEOSWKBWriter_writeHEX_r(), and geos::geom::operator<<().
 {
   // setup input/output stream
   stringstream stream;
   // write the geometry in wkb format
   this->write(g, stream);
   // convert to HEX
   WKBReader::printHEX(stream, os);
 }
void geos::io::WKBWriter::writeInt (int intValue) private
Definition at line 270 of file WKBWriter.cpp.
References buf, byteOrder, outStream, and geos::io::ByteOrderValues::putInt().
Referenced by writeCoordinateSequence(), writeGeometryCollection(), writeGeometryType(), writePolygon(), and writeSRID().
 {
   ByteOrderValues::putInt(val, buf, byteOrder);
   outStream->write(reinterpret_cast<char *>(buf), 4);
   //outStream->write(reinterpret_cast<char *>(&val), 4);
 }
void geos::io::WKBWriter::writeLineString (const geom::LineString & ls) private
Definition at line 148 of file WKBWriter.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getSRID(), geos::io::WKBConstants::wkbLineString, writeByteOrder(), writeCoordinateSequence(), writeGeometryType(), and writeSRID().
Referenced by write().
 {
   writeByteOrder();
   writeGeometryType(WKBConstants::wkbLineString, g.getSRID());
   writeSRID(g.getSRID());
   const CoordinateSequence* cs=g.getCoordinatesRO();
   assert(cs);
   writeCoordinateSequence(*cs, true);
 }
void geos::io::WKBWriter::writePoint (const geom::Point & p) private
Definition at line 132 of file WKBWriter.cpp.
References geos::geom::Point::getCoordinatesRO(), geos::geom::Geometry::getSRID(), geos::geom::Point::isEmpty(), geos::io::WKBConstants::wkbPoint, writeByteOrder(), writeCoordinateSequence(), writeGeometryType(), and writeSRID().
Referenced by write().
 {
   if (g.isEmpty()) throw
     util::IllegalArgumentException("Empty Points cannot be represented in WKB");
   writeByteOrder();
   writeGeometryType(WKBConstants::wkbPoint, g.getSRID());
   writeSRID(g.getSRID());
   const CoordinateSequence* cs=g.getCoordinatesRO();
   assert(cs);
   writeCoordinateSequence(*cs, false);
 }
void geos::io::WKBWriter::writePolygon (const geom::Polygon & p) private
Definition at line 161 of file WKBWriter.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), geos::geom::Geometry::getSRID(), geos::geom::Polygon::isEmpty(), geos::io::WKBConstants::wkbPolygon, writeByteOrder(), writeCoordinateSequence(), writeGeometryType(), writeInt(), and writeSRID().
Referenced by write().
 {
   writeByteOrder();
   writeGeometryType(WKBConstants::wkbPolygon, g.getSRID());
   writeSRID(g.getSRID());
   if (g.isEmpty()) {
     writeInt(0);
     return;
   }
   std::size_t nholes = g.getNumInteriorRing();
   writeInt(static_cast<int>(nholes + 1));
   const LineString* ls = g.getExteriorRing();
   assert(ls);
   const CoordinateSequence* cs=ls->getCoordinatesRO();
   assert(cs);
   writeCoordinateSequence(*cs, true);
   for (std::size_t i=0; i<nholes; i++)
   {
     ls = g.getInteriorRingN(i);
     assert(ls);
     cs = ls->getCoordinatesRO();
     assert(cs);
     writeCoordinateSequence(*cs, true);
   }
 }
void geos::io::WKBWriter::writeSRID (int SRID) private
Definition at line 263 of file WKBWriter.cpp.
References includeSRID, and writeInt().
Referenced by writeGeometryCollection(), writeLineString(), writePoint(), and writePolygon().
 {
     if (includeSRID && SRID != 0)
         writeInt(SRID);
 }
Member Data Documentation
unsigned char geos::io::WKBWriter::buf[8] private
Definition at line 168 of file WKBWriter.h.
Referenced by writeByteOrder(), writeCoordinate(), and writeInt().
int geos::io::WKBWriter::byteOrder private
Definition at line 162 of file WKBWriter.h.
Referenced by setByteOrder(), writeByteOrder(), writeCoordinate(), and writeInt().
int geos::io::WKBWriter::defaultOutputDimension private
Definition at line 159 of file WKBWriter.h.
Referenced by setOutputDimension(), WKBWriter(), and write().
bool geos::io::WKBWriter::includeSRID private
Definition at line 164 of file WKBWriter.h.
Referenced by writeGeometryType(), and writeSRID().
int geos::io::WKBWriter::outputDimension private
Definition at line 160 of file WKBWriter.h.
Referenced by WKBWriter(), write(), writeCoordinateSequence(), and writeGeometryType().
std::ostream* geos::io::WKBWriter::outStream private
Definition at line 166 of file WKBWriter.h.
Referenced by write(), writeByteOrder(), writeCoordinate(), writeGeometryCollection(), and writeInt().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/io/WKBWriter.h
/home/vicky/potree/geos/vicky/src/io/WKBWriter.cpp