GEOS: geos::operation::overlay::validate::OffsetPointGenerator Class Reference
geos::operation::overlay::validate::OffsetPointGenerator Class Reference
Generates points offset from both sides of all segments in a geometry.
#include <OffsetPointGenerator.h>
Public Member Functions
OffsetPointGenerator (const geom::Geometry &geom, double offset)
std::unique_ptr< std::vector< geom::Coordinate > > getPoints ()
Gets the computed offset points.
Private Member Functions
void extractPoints (const geom::LineString *line)
void computeOffsets (const geom::Coordinate &p0, const geom::Coordinate &p1)
OffsetPointGenerator (const OffsetPointGenerator &other)=delete
OffsetPointGenerator & operator= (const OffsetPointGenerator &rhs)=delete
Private Attributes
const geom::Geometry & g
double offsetDistance
std::unique_ptr< std::vector< geom::Coordinate > > offsetPts
Detailed Description
Generates points offset from both sides of all segments in a geometry.
Definition at line 53 of file OffsetPointGenerator.h.
Constructor & Destructor Documentation
geos::operation::overlay::validate::OffsetPointGenerator::OffsetPointGenerator (const geom::Geometry & geom, double offset)
Definition at line 48 of file OffsetPointGenerator.cpp.
   :
   g(geom),
   offsetDistance(offset)
 {
 }
geos::operation::overlay::validate::OffsetPointGenerator::OffsetPointGenerator (const OffsetPointGenerator & other) private delete
Member Function Documentation
void geos::operation::overlay::validate::OffsetPointGenerator::computeOffsets (const geom::Coordinate & p0, const geom::Coordinate & p1) private
Definition at line 87 of file OffsetPointGenerator.cpp.
References offsetDistance, offsetPts, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by extractPoints().
 {
   double dx = p1.x - p0.x;
   double dy = p1.y - p0.y;
   double len = sqrt(dx * dx + dy * dy);
   // u is the vector that is the length of the offset,
   // in the direction of the segment
   double ux = offsetDistance * dx / len;
   double uy = offsetDistance * dy / len;
   double midX = (p1.x + p0.x) / 2;
   double midY = (p1.y + p0.y) / 2;
   Coordinate offsetLeft(midX - uy, midY + ux);
   Coordinate offsetRight(midX + uy, midY - ux);
   offsetPts->push_back(offsetLeft);
   offsetPts->push_back(offsetRight);
 }
void geos::operation::overlay::validate::OffsetPointGenerator::extractPoints (const geom::LineString * line) private
Definition at line 74 of file OffsetPointGenerator.cpp.
References computeOffsets(), geos::geom::LineString::getCoordinatesRO(), and geos::geom::CoordinateSequence::size().
Referenced by getPoints().
 {
   const CoordinateSequence& pts = *(line->getCoordinatesRO());
   assert(pts.size() > 1 );
   for (size_t i=0, n=pts.size()-1; i<n; ++i)
   {
     computeOffsets(pts[i], pts[i + 1]);
   }
 }
std::unique_ptr< std::vector< geom::Coordinate > > geos::operation::overlay::validate::OffsetPointGenerator::getPoints ()
Gets the computed offset points.
Definition at line 58 of file OffsetPointGenerator.cpp.
References extractPoints(), g, geos::geom::util::LinearComponentExtracter::getLines(), and offsetPts.
Referenced by geos::operation::overlay::validate::OverlayResultValidator::addTestPts().
 {
   assert (offsetPts.get() == nullptr);
   offsetPts.reset(new vector<Coordinate>());
   vector<const LineString*> lines;
   geos::geom::util::LinearComponentExtracter::getLines(g, lines);
   for_each(lines.begin(), lines.end(),
     bind1st(mem_fun(&OffsetPointGenerator::extractPoints), this));
   // NOTE: Apparently, this is 'source' method giving up the object resource.
   return std::move(offsetPts);
 }
OffsetPointGenerator& geos::operation::overlay::validate::OffsetPointGenerator::operator= (const OffsetPointGenerator & rhs) private delete
Member Data Documentation
const geom::Geometry& geos::operation::overlay::validate::OffsetPointGenerator::g private
Definition at line 64 of file OffsetPointGenerator.h.
Referenced by getPoints().
double geos::operation::overlay::validate::OffsetPointGenerator::offsetDistance private
Definition at line 66 of file OffsetPointGenerator.h.
Referenced by computeOffsets().
std::unique_ptr< std::vector<geom::Coordinate> > geos::operation::overlay::validate::OffsetPointGenerator::offsetPts private
Definition at line 68 of file OffsetPointGenerator.h.
Referenced by computeOffsets(), and getPoints().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/validate/OffsetPointGenerator.h
/home/vicky/potree/geos/vicky/src/operation/overlay/validate/OffsetPointGenerator.cpp