GEOS: geos::geomgraph::index::SimpleMCSweepLineIntersector Class Reference
geos::geomgraph::index::SimpleMCSweepLineIntersector Class Reference
Finds all intersections in one or two sets of edges, using an x-axis sweepline algorithm in conjunction with Monotone Chains.
#include <SimpleMCSweepLineIntersector.h>
Public Member Functions
SimpleMCSweepLineIntersector ()
~SimpleMCSweepLineIntersector () override
void computeIntersections (std::vector< Edge * > *edges, SegmentIntersector *si, bool testAllSegments) override
void computeIntersections (std::vector< Edge * > *edges0, std::vector< Edge * > *edges1, SegmentIntersector *si) override
Protected Attributes
std::vector< SweepLineEvent * > events
int nOverlaps
Private Member Functions
void add (std::vector< Edge * > *edges)
void add (std::vector< Edge * > *edges, void *edgeSet)
void add (Edge *edge, void *edgeSet)
void prepareEvents ()
void computeIntersections (SegmentIntersector *si)
void processOverlaps (int start, int end, SweepLineEvent *ev0, SegmentIntersector *si)
Detailed Description
Finds all intersections in one or two sets of edges, using an x-axis sweepline algorithm in conjunction with Monotone Chains.
While still O(n^2) in the worst case, this algorithm drastically improves the average-case time. The use of MonotoneChains as the items in the index seems to offer an improvement in performance over a sweep-line alone.
Definition at line 54 of file SimpleMCSweepLineIntersector.h.
Constructor & Destructor Documentation
geos::geomgraph::index::SimpleMCSweepLineIntersector::SimpleMCSweepLineIntersector ()
Definition at line 32 of file SimpleMCSweepLineIntersector.cpp.
 {
 }
geos::geomgraph::index::SimpleMCSweepLineIntersector::~SimpleMCSweepLineIntersector () override
Definition at line 37 of file SimpleMCSweepLineIntersector.cpp.
References geos::geomgraph::index::SweepLineEvent::isDelete().
 {
   for(size_t i=0; i<events.size(); ++i)
   {
     SweepLineEvent *sle=events[i];
     if (sle->isDelete()) delete sle;
   }
   //delete events;
 }
Member Function Documentation
void geos::geomgraph::index::SimpleMCSweepLineIntersector::add (std::vector< Edge * > * edges) private
Definition at line 68 of file SimpleMCSweepLineIntersector.cpp.
 {
   for (size_t i=0; i<edges->size(); ++i)
   {
     Edge *edge=(*edges)[i];
     // edge is its own group
     add(edge, edge);
   }
 }
void geos::geomgraph::index::SimpleMCSweepLineIntersector::add (std::vector< Edge * > * edges, void * edgeSet) private
Definition at line 79 of file SimpleMCSweepLineIntersector.cpp.
 {
   for (size_t i=0; i<edges->size(); ++i)
   {
     Edge *edge=(*edges)[i];
     add(edge,edgeSet);
   }
 }
void geos::geomgraph::index::SimpleMCSweepLineIntersector::add (Edge * edge, void * edgeSet) private
Definition at line 89 of file SimpleMCSweepLineIntersector.cpp.
References GEOS_CHECK_FOR_INTERRUPTS, geos::geomgraph::index::MonotoneChainEdge::getMaxX(), geos::geomgraph::index::MonotoneChainEdge::getMinX(), geos::geomgraph::Edge::getMonotoneChainEdge(), and geos::geomgraph::index::MonotoneChainEdge::getStartIndexes().
 {
   MonotoneChainEdge *mce=edge->getMonotoneChainEdge();
   vector<int> &startIndex=mce->getStartIndexes();
   size_t n = startIndex.size()-1;
   events.reserve(events.size()+(n*2));
   for(size_t i=0; i<n; ++i)
   {
     GEOS_CHECK_FOR_INTERRUPTS();
     MonotoneChain *mc=new MonotoneChain(mce, static_cast<int>(i));
     SweepLineEvent *insertEvent=new SweepLineEvent(edgeSet,mce->getMinX(static_cast<int>(i)),nullptr,mc);
     events.push_back(insertEvent);
     events.push_back(new SweepLineEvent(edgeSet,mce->getMaxX(static_cast<int>(i)),insertEvent,mc));
   }
 }
void geos::geomgraph::index::SimpleMCSweepLineIntersector::computeIntersections (std::vector< Edge * > * edges, SegmentIntersector * si, bool testAllSegments) override virtual
Computes all self-intersections between edges in a set of edges, allowing client to choose whether self-intersections are computed.
Parameters
edges a list of edges to test for intersections
si the SegmentIntersector to use
testAllSegments true if self-intersections are to be tested as well
Implements geos::geomgraph::index::EdgeSetIntersector.
Definition at line 48 of file SimpleMCSweepLineIntersector.cpp.
 {
   if (testAllSegments)
     add(edges,nullptr);
   else
     add(edges);
   computeIntersections(si);
 }
void geos::geomgraph::index::SimpleMCSweepLineIntersector::computeIntersections (std::vector< Edge * > * edges0, std::vector< Edge * > * edges1, SegmentIntersector * si) override virtual
Computes all mutual intersections between two sets of edges
Implements geos::geomgraph::index::EdgeSetIntersector.
Definition at line 59 of file SimpleMCSweepLineIntersector.cpp.
 {
   add(edges0,edges0);
   add(edges1,edges1);
   computeIntersections(si);
 }
void geos::geomgraph::index::SimpleMCSweepLineIntersector::computeIntersections (SegmentIntersector * si) private
Definition at line 126 of file SimpleMCSweepLineIntersector.cpp.
References GEOS_CHECK_FOR_INTERRUPTS, geos::geomgraph::index::SweepLineEvent::getDeleteEventIndex(), geos::geomgraph::index::SegmentIntersector::getIsDone(), and geos::geomgraph::index::SweepLineEvent::isInsert().
 {
   nOverlaps=0;
   prepareEvents();
   for(size_t i=0; i<events.size(); ++i)
   {
     GEOS_CHECK_FOR_INTERRUPTS();
     SweepLineEvent *ev=events[i];
     if (ev->isInsert())
     {
       processOverlaps(static_cast<int>(i),ev->getDeleteEventIndex(),ev,si);
     }
     if (si->getIsDone())
     {
       break;
     }
   }
 }
void geos::geomgraph::index::SimpleMCSweepLineIntersector::prepareEvents () private
Because Delete Events have a link to their corresponding Insert event, it is possible to compute exactly the range of events which must be compared to a given Insert event object.
Definition at line 111 of file SimpleMCSweepLineIntersector.cpp.
References GEOS_CHECK_FOR_INTERRUPTS, geos::geomgraph::index::SweepLineEvent::getInsertEvent(), geos::geomgraph::index::SweepLineEvent::isDelete(), and geos::geomgraph::index::SweepLineEvent::setDeleteEventIndex().
 {
   sort(events.begin(), events.end(), SweepLineEventLessThen());
   for(size_t i=0; i<events.size(); ++i)
   {
     GEOS_CHECK_FOR_INTERRUPTS();
     SweepLineEvent *ev=events[i];
     if (ev->isDelete())
     {
       ev->getInsertEvent()->setDeleteEventIndex(static_cast<int>(i));
     }
   }
 }
void geos::geomgraph::index::SimpleMCSweepLineIntersector::processOverlaps (int start, int end, SweepLineEvent * ev0, SegmentIntersector * si) private
Definition at line 146 of file SimpleMCSweepLineIntersector.cpp.
References geos::geomgraph::index::MonotoneChain::computeIntersections(), geos::geomgraph::index::SweepLineEvent::edgeSet, geos::geomgraph::index::SweepLineEvent::getObject(), and geos::geomgraph::index::SweepLineEvent::isInsert().
 {
   MonotoneChain *mc0=(MonotoneChain*) ev0->getObject();
   /*
    * Since we might need to test for self-intersections,
    * include current insert event object in list of event objects to test.
    * Last index can be skipped, because it must be a Delete event.
    */
   for(int i=start; i<end; ++i)
   {
     SweepLineEvent *ev1=events[i];
     if (ev1->isInsert())
     {
       MonotoneChain *mc1=(MonotoneChain*) ev1->getObject();
       // don't compare edges in same group
       // null group indicates that edges should be compared
       if (ev0->edgeSet==nullptr || (ev0->edgeSet!=ev1->edgeSet))
       {
         mc0->computeIntersections(mc1,si);
         nOverlaps++;
       }
     }
   }
 }
Member Data Documentation
std::vector<SweepLineEvent*> geos::geomgraph::index::SimpleMCSweepLineIntersector::events protected
Definition at line 71 of file SimpleMCSweepLineIntersector.h.
int geos::geomgraph::index::SimpleMCSweepLineIntersector::nOverlaps protected
Definition at line 74 of file SimpleMCSweepLineIntersector.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/index/SimpleMCSweepLineIntersector.h
/home/vicky/potree/geos/vicky/src/geomgraph/index/SimpleMCSweepLineIntersector.cpp