GEOS: geos::operation::buffer::DepthSegment Class Reference
geos::operation::buffer::DepthSegment Class Reference
Public Member Functions
DepthSegment (const geom::LineSegment &seg, int depth)
int compareTo (const DepthSegment &other) const
Public Attributes
int leftDepth
Static Private Member Functions
static int compareX (const geom::LineSegment *seg0, const geom::LineSegment *seg1)
Private Attributes
geom::LineSegment upwardSeg
Detailed Description
Definition at line 53 of file SubgraphDepthLocater.cpp.
Constructor & Destructor Documentation
geos::operation::buffer::DepthSegment::DepthSegment (const geom::LineSegment & seg, int depth) inline
Parameters
seg will be copied to private space
Definition at line 83 of file SubgraphDepthLocater.cpp.
     :
     upwardSeg(seg),
     leftDepth(depth)
   {
     // input seg is assumed to be normalized
     //upwardSeg.normalize();
   }
Member Function Documentation
int geos::operation::buffer::DepthSegment::compareTo (const DepthSegment & other) const inline
Defines a comparision operation on DepthSegments which orders them left to right
DS1 < DS2   if   DS1.seg is left of DS2.seg
DS1 > DS2   if   DS1.seg is right of DS2.seg
Parameters
obj
Returns
try and compute a determinate orientation for the segments. Test returns 1 if other is left of this (i.e. this > other)
If comparison between this and other is indeterminate, try the opposite call order. orientationIndex value is 1 if this is left of other, so have to flip sign to get proper comparison value of -1 if this is leftmost
Definition at line 104 of file SubgraphDepthLocater.cpp.
References geos::geom::LineSegment::orientationIndex(), and upwardSeg.
Referenced by geos::operation::buffer::DepthSegmentLessThen::operator()().
   {
     int orientIndex=upwardSeg.orientationIndex(&(other.upwardSeg));
     if (orientIndex==0)
       orientIndex=-1 * other.upwardSeg.orientationIndex(&upwardSeg);
     // if orientation is determinate, return it
     if (orientIndex != 0)
       return orientIndex;
     // otherwise, segs must be collinear - sort based on minimum X value
     return compareX(&upwardSeg, &(other.upwardSeg));
   }
static int geos::operation::buffer::DepthSegment::compareX (const geom::LineSegment * seg0, const geom::LineSegment * seg1) inline static private
Definition at line 71 of file SubgraphDepthLocater.cpp.
References geos::geom::Coordinate::compareTo(), geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
   {
     int compare0=seg0->p0.compareTo(seg1->p0);
     if (compare0!=0) return compare0;
     return seg0->p1.compareTo(seg1->p1);
   }
Member Data Documentation
int geos::operation::buffer::DepthSegment::leftDepth
Definition at line 80 of file SubgraphDepthLocater.cpp.
Referenced by geos::operation::buffer::SubgraphDepthLocater::getDepth().
geom::LineSegment geos::operation::buffer::DepthSegment::upwardSeg private
Definition at line 57 of file SubgraphDepthLocater.cpp.
Referenced by compareTo().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/operation/buffer/SubgraphDepthLocater.cpp