GEOS: geos::precision::CommonBits Class Reference
geos::precision::CommonBits Class Reference
Determines the maximum number of common most-significant bits in the mantissa of one or numbers.
#include <CommonBits.h>
Public Member Functions
CommonBits ()
void add (double num)
double getCommon ()
Static Public Member Functions
static int64 signExpBits (int64 num)
Computes the bit pattern for the sign and exponent of a double-precision number.
static int numCommonMostSigMantissaBits (int64 num1, int64 num2)
This computes the number of common most-significant bits in the mantissas of two double-precision numbers.
static int64 zeroLowerBits (int64 bits, int nBits)
Zeroes the lower n bits of a bitstring.
static int getBit (int64 bits, int i)
Extracts the i'th bit of a bitstring.
Private Attributes
bool isFirst
int commonMantissaBitsCount
int64 commonBits
int64 commonSignExp
Detailed Description
Determines the maximum number of common most-significant bits in the mantissa of one or numbers.
Can be used to compute the double-precision number which is represented by the common bits. If there are no common bits, the number computed is 0.0.
Definition at line 33 of file CommonBits.h.
Constructor & Destructor Documentation
geos::precision::CommonBits::CommonBits ()
Definition at line 61 of file CommonBits.cpp.
References commonBits, commonMantissaBitsCount, and isFirst.
{
   isFirst = true;
   commonMantissaBitsCount = 53;
   commonBits = 0;
 }
Member Function Documentation
void geos::precision::CommonBits::add (double num)
Definition at line 69 of file CommonBits.cpp.
References commonBits, commonMantissaBitsCount, commonSignExp, isFirst, numCommonMostSigMantissaBits(), signExpBits(), and zeroLowerBits().
Referenced by geos::precision::CommonCoordinateFilter::filter_ro().
 {
   int64 numBits=(int64)num;
   if (isFirst) {
     commonBits = numBits;
     commonSignExp = signExpBits(commonBits);
     isFirst = false;
     return;
   }
   int64 numSignExp = signExpBits(numBits);
   if (numSignExp != commonSignExp) {
     commonBits = 0;
     return;
   }
   //    System.out.println(toString(commonBits));
   //    System.out.println(toString(numBits));
   commonMantissaBitsCount = numCommonMostSigMantissaBits(commonBits, numBits);
   commonBits = zeroLowerBits(commonBits, 64 - (12 + commonMantissaBitsCount));
   //    System.out.println(toString(commonBits));
 }
int geos::precision::CommonBits::getBit (int64 bits, int i) static
Extracts the i'th bit of a bitstring.
Parameters
bits the bitstring to extract from
i the bit to extract
Returns
the value of the extracted bit
Definition at line 54 of file CommonBits.cpp.
Referenced by numCommonMostSigMantissaBits().
 {
   int64 mask = (1ull << i);
   return (bits & mask) != 0 ? 1 : 0;
 }
double geos::precision::CommonBits::getCommon ()
Definition at line 92 of file CommonBits.cpp.
References commonBits.
Referenced by geos::precision::CommonCoordinateFilter::getCommonCoordinate().
 {
   return (double)commonBits;
 }
int geos::precision::CommonBits::numCommonMostSigMantissaBits (int64 num1, int64 num2) static
This computes the number of common most-significant bits in the mantissas of two double-precision numbers.
It does not count the hidden bit, which is always 1. It does not determine whether the numbers have the same exponent - if they do not, the value computed by this function is meaningless.
Parameters
db
Returns
the number of common most-significant mantissa bits
Definition at line 31 of file CommonBits.cpp.
References getBit().
Referenced by add().
 {
   int count = 0;
   for (int i = 52; i >= 0; i--){
     if (getBit(num1, i) != getBit(num2, i))
       return count;
     count++;
   }
   return 52;
 }
int64 geos::precision::CommonBits::signExpBits (int64 num) static
Computes the bit pattern for the sign and exponent of a double-precision number.
Parameters
num
Returns
the bit pattern for the sign and exponent
Definition at line 24 of file CommonBits.cpp.
Referenced by add().
 {
   return num >> 52;
 }
int64 geos::precision::CommonBits::zeroLowerBits (int64 bits, int nBits) static
Zeroes the lower n bits of a bitstring.
Parameters
bits the bitstring to alter
i the number of bits to zero
Returns
the zeroed bitstring
Definition at line 44 of file CommonBits.cpp.
Referenced by add().
 {
   int64 invMask = (1<< nBits)-1;
   int64 mask = ~ invMask;
   int64 zeroed = bits & mask;
   return zeroed;
 }
Member Data Documentation
int64 geos::precision::CommonBits::commonBits private
Definition at line 41 of file CommonBits.h.
Referenced by add(), CommonBits(), and getCommon().
int geos::precision::CommonBits::commonMantissaBitsCount private
Definition at line 39 of file CommonBits.h.
Referenced by add(), and CommonBits().
int64 geos::precision::CommonBits::commonSignExp private
Definition at line 43 of file CommonBits.h.
Referenced by add().
bool geos::precision::CommonBits::isFirst private
Definition at line 37 of file CommonBits.h.
Referenced by add(), and CommonBits().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/precision/CommonBits.h
/home/vicky/potree/geos/vicky/src/precision/CommonBits.cpp