GEOS: geos::algorithm::RayCrossingCounter Class Reference
geos::algorithm::RayCrossingCounter Class Reference
Counts the number of segments crossed by a horizontal ray extending to the right from a given point, in an incremental fashion.
#include <RayCrossingCounter.h>
Public Member Functions
RayCrossingCounter (const geom::Coordinate &point)
void countSegment (const geom::Coordinate &p1, const geom::Coordinate &p2)
bool isOnSegment ()
int getLocation ()
bool isPointInPolygon ()
Static Public Member Functions
static int locatePointInRing (const geom::Coordinate &p, const geom::CoordinateSequence &ring)
static int locatePointInRing (const geom::Coordinate &p, const std::vector< const geom::Coordinate * > &ring)
Semantically equal to the above, just different args encoding.
static int orientationIndex (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &q)
Returns the index of the direction of the point q relative to a vector specified by p1-p2.
Private Member Functions
RayCrossingCounter (const RayCrossingCounter &other)=delete
RayCrossingCounter & operator= (const RayCrossingCounter &rhs)=delete
Private Attributes
const geom::Coordinate & point
int crossingCount
bool isPointOnSegment
Detailed Description
Counts the number of segments crossed by a horizontal ray extending to the right from a given point, in an incremental fashion.
This can be used to determine whether a point lies in a Polygonal geometry. The class determines the situation where the point lies exactly on a segment. When being used for Point-In-Polygon determination, this case allows short-circuiting the evaluation.
This class handles polygonal geometries with any number of shells and holes. The orientation of the shell and hole rings is unimportant. In order to compute a correct location for a given polygonal geometry, it is essential that all segments are counted which
touch the ray
lie in in any ring which may contain the point
The only exception is when the point-on-segment situation is detected, in which case no further processing is required. The implication of the above rule is that segments which can be a priori determined to not touch the ray (i.e. by a test of their bounding box or Y-extent) do not need to be counted. This allows for optimization by indexing.
Author
Martin Davis
Definition at line 66 of file RayCrossingCounter.h.
Constructor & Destructor Documentation
geos::algorithm::RayCrossingCounter::RayCrossingCounter (const RayCrossingCounter & other) private delete
geos::algorithm::RayCrossingCounter::RayCrossingCounter (const geom::Coordinate & point) inline
Definition at line 112 of file RayCrossingCounter.h.
   : point( point),
     crossingCount( 0),
     isPointOnSegment( false)
   { }
Member Function Documentation
void geos::algorithm::RayCrossingCounter::countSegment (const geom::Coordinate & p1, const geom::Coordinate & p2)
Counts a segment
Parameters
p1 an endpoint of the segment
p2 another endpoint of the segment
Definition at line 94 of file RayCrossingCounter.cpp.
References crossingCount, isPointOnSegment, orientationIndex(), point, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by locatePointInRing().
 {
   // For each segment, check if it crosses
   // a horizontal ray running from the test point in
   // the positive x direction.
   // check if the segment is strictly to the left of the test point
   if (p1.x < point.x && p2.x < point.x)
     return;
   // check if the point is equal to the current ring vertex
   if (point.x == p2.x && point.y == p2.y)
   {
     isPointOnSegment = true;
     return;
   }
   // For horizontal segments, check if the point is on the segment.
   // Otherwise, horizontal segments are not counted.
   if (p1.y == point.y && p2.y == point.y)
   {
     double minx = p1.x;
     double maxx = p2.x;
     if (minx > maxx)
     {
       minx = p2.x;
       maxx = p1.x;
     }
     if (point.x >= minx && point.x <= maxx)
       isPointOnSegment = true;
     return;
   }
   // Evaluate all non-horizontal segments which cross a horizontal ray
   // to the right of the test pt.
   // To avoid double-counting shared vertices, we use the convention that
   // - an upward edge includes its starting endpoint, and excludes its
   //   final endpoint
   // - a downward edge excludes its starting endpoint, and includes its
   //   final endpoint
   if (((p1.y > point.y) && (p2.y <= point.y)) ||
     ((p2.y > point.y) && (p1.y <= point.y)) )
   {
     // For an upward edge, orientationIndex will be positive when p1->p2
     // crosses ray. Conversely, downward edges should have negative sign.
     int sign = orientationIndex(p1, p2, point);
     if (sign == 0)
     {
       isPointOnSegment = true;
       return;
     }
     if (p2.y < p1.y)
       sign = -sign;
     // The segment crosses the ray if the sign is strictly positive.
     if (sign > 0)
       crossingCount++;
   }
 }
int geos::algorithm::RayCrossingCounter::getLocation ()
Gets the Location of the point relative to the ring, polygon or multipolygon from which the processed segments were provided.
This method only determines the correct location if all relevant segments must have been processed.
Returns
the Location of the point
Definition at line 161 of file RayCrossingCounter.cpp.
References geos::geom::Location::BOUNDARY, crossingCount, geos::geom::Location::EXTERIOR, geos::geom::Location::INTERIOR, and isPointOnSegment.
Referenced by isPointInPolygon(), geos::algorithm::locate::IndexedPointInAreaLocator::locate(), and locatePointInRing().
 {
   if (isPointOnSegment)
     return geom::Location::BOUNDARY;
   // The point is in the interior of the ring if the number
   // of X-crossings is odd.
   if ((crossingCount % 2) == 1)
     return geom::Location::INTERIOR;
   return geom::Location::EXTERIOR;
 }
bool geos::algorithm::RayCrossingCounter::isOnSegment () inline
Reports whether the point lies exactly on one of the supplied segments. This method may be called at any time as segments are processed. If the result of this method is true, no further segments need be supplied, since the result will never change again.
Returns
true if the point lies exactly on a segment
Definition at line 136 of file RayCrossingCounter.h.
Referenced by locatePointInRing().
   {
     return isPointOnSegment;
   }
bool geos::algorithm::RayCrossingCounter::isPointInPolygon ()
Tests whether the point lies in or on the ring, polygon or multipolygon from which the processed segments were provided.
This method only determines the correct location if all relevant segments must have been processed.
Returns
true if the point lies in or on the supplied polygon
Definition at line 176 of file RayCrossingCounter.cpp.
References geos::geom::Location::EXTERIOR, and getLocation().
 {
   return getLocation() != geom::Location::EXTERIOR;
 }
int geos::algorithm::RayCrossingCounter::locatePointInRing (const geom::Coordinate & p, const geom::CoordinateSequence & ring) static
Determines the Location of a point in a ring. This method is an exemplar of how to use this class.
Parameters
p the point to test
ring an array of Coordinates forming a ring
Returns
the location of the point in the ring
Definition at line 41 of file RayCrossingCounter.cpp.
References countSegment(), getLocation(), isOnSegment(), and geos::geom::CoordinateSequence::size().
 {
   RayCrossingCounter rcc(point);
   for (std::size_t i = 1, ni = ring.size(); i < ni; i++)
   {
     const geom::Coordinate & p1 = ring[ i - 1 ];
     const geom::Coordinate & p2 = ring[ i ];
     rcc.countSegment(p1, p2);
     if ( rcc.isOnSegment() )
       return rcc.getLocation();
   }
   return rcc.getLocation();
 }
int geos::algorithm::RayCrossingCounter::locatePointInRing (const geom::Coordinate & p, const std::vector< const geom::Coordinate * > & ring) static
Semantically equal to the above, just different args encoding.
Definition at line 60 of file RayCrossingCounter.cpp.
References countSegment(), getLocation(), and isOnSegment().
 {
   RayCrossingCounter rcc(point);
   for (std::size_t i = 1, ni = ring.size(); i < ni; i++)
   {
     const geom::Coordinate & p1 = *ring[ i - 1 ];
     const geom::Coordinate & p2 = *ring[ i ];
     rcc.countSegment(p1, p2);
     if ( rcc.isOnSegment() )
       return rcc.getLocation();
   }
   return rcc.getLocation();
 }
RayCrossingCounter& geos::algorithm::RayCrossingCounter::operator= (const RayCrossingCounter & rhs) private delete
int geos::algorithm::RayCrossingCounter::orientationIndex (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & q) static
Returns the index of the direction of the point q relative to a vector specified by p1-p2.
Parameters
p1 the origin point of the vector
p2 the final point of the vector
q the point to compute the direction to
Returns
1 if q is counter-clockwise (left) from p1-p2
-1 if q is clockwise (right) from p1-p2
0 if q is collinear with p1-p2
Definition at line 80 of file RayCrossingCounter.cpp.
References geos::algorithm::RobustDeterminant::signOfDet2x2(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by countSegment().
 {
   // travelling along p1->p2, turn counter clockwise to get to q return 1,
   // travelling along p1->p2, turn clockwise to get to q return -1,
   // p1, p2 and q are colinear return 0.
   double dx1=p2.x-p1.x;
   double dy1=p2.y-p1.y;
   double dx2=q.x-p2.x;
   double dy2=q.y-p2.y;
   return RobustDeterminant::signOfDet2x2(dx1,dy1,dx2,dy2);
 }
Member Data Documentation
int geos::algorithm::RayCrossingCounter::crossingCount private
Definition at line 71 of file RayCrossingCounter.h.
Referenced by countSegment(), and getLocation().
bool geos::algorithm::RayCrossingCounter::isPointOnSegment private
Definition at line 74 of file RayCrossingCounter.h.
Referenced by countSegment(), and getLocation().
const geom::Coordinate& geos::algorithm::RayCrossingCounter::point private
Definition at line 69 of file RayCrossingCounter.h.
Referenced by countSegment().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/RayCrossingCounter.h
/home/vicky/potree/geos/vicky/src/algorithm/RayCrossingCounter.cpp