GEOS: geos::operation::sharedpaths::SharedPathsOp Class Reference
geos::operation::sharedpaths::SharedPathsOp Class Reference
Find shared paths among two linear Geometry objects.
#include <SharedPathsOp.h>
Public Types
typedef std::vector< geom::LineString * > PathList
LineString vector (list of edges)
Public Member Functions
SharedPathsOp (const geom::Geometry &g1, const geom::Geometry &g2)
Constructor.
void getSharedPaths (PathList &sameDirection, PathList &oppositeDirection)
Get shared paths.
Static Public Member Functions
static void sharedPathsOp (const geom::Geometry &g1, const geom::Geometry &g2, PathList &sameDirection, PathList &oppositeDirection)
Find paths shared between two linear geometries.
static void clearEdges (PathList &from)
Delete all edges in the list.
Private Member Functions
void findLinearIntersections (PathList &to)
Get all the linear intersections.
bool isForward (const geom::LineString &edge, const geom::Geometry &geom)
Check if the given edge goes forward or backward on the given line.
bool isSameDirection (const geom::LineString &edge)
void checkLinealInput (const geom::Geometry &g)
Throw an IllegalArgumentException if the geom is not linear.
SharedPathsOp (const SharedPathsOp &other)=delete
SharedPathsOp & operator= (const SharedPathsOp &rhs)=delete
Private Attributes
const geom::Geometry & _g1
const geom::Geometry & _g2
const geom::GeometryFactory & _gf
Detailed Description
Find shared paths among two linear Geometry objects.
For each shared path report if it direction is the same or opposite.
Paths reported as shared are given in the direction they appear in the first geometry.
Developed by Sandro Santilli (strk@.nosp@m.kbt..nosp@m.io) for Faunalia (http://www.faunalia.it) with funding from Regione Toscana - Settore SISTEMA INFORMATIVO TERRITORIALE ED AMBIENTALE - for the project: "Sviluppo strumenti software per il trattamento di dati geografici basati su QuantumGIS e Postgis (CIG 0494241492)"
Definition at line 64 of file SharedPathsOp.h.
Member Typedef Documentation
typedef std::vector<geom::LineString*> geos::operation::sharedpaths::SharedPathsOp::PathList
LineString vector (list of edges)
Definition at line 69 of file SharedPathsOp.h.
Constructor & Destructor Documentation
geos::operation::sharedpaths::SharedPathsOp::SharedPathsOp (const geom::Geometry & g1, const geom::Geometry & g2)
Constructor.
Parameters
g1 First geometry. Must be linear.
g2 Second geometry. Must be linear.
Definition at line 53 of file SharedPathsOp.cpp.
References _g1, _g2, and checkLinealInput().
   :
   _g1(g1),
   _g2(g2),
   _gf(*g1.getFactory())
 {
   checkLinealInput(_g1);
   checkLinealInput(_g2);
 }
geos::operation::sharedpaths::SharedPathsOp::SharedPathsOp (const SharedPathsOp & other) private delete
Member Function Documentation
void geos::operation::sharedpaths::SharedPathsOp::checkLinealInput (const geom::Geometry & g) private
Throw an IllegalArgumentException if the geom is not linear.
Definition at line 66 of file SharedPathsOp.cpp.
Referenced by SharedPathsOp().
 {
   if ( ! dynamic_cast<const LineString*>(&g) &&
        ! dynamic_cast<const MultiLineString*>(&g) )
   {
     throw util::IllegalArgumentException("Geometry is not lineal");
   }
 }
void geos::operation::sharedpaths::SharedPathsOp::clearEdges (PathList & from) static
Delete all edges in the list.
Definition at line 91 of file SharedPathsOp.cpp.
 {
   for (PathList::const_iterator
         i=edges.begin(), e=edges.end();
         i!=e; ++i)
   {
     delete *i;
   }
   edges.clear();
 }
void geos::operation::sharedpaths::SharedPathsOp::findLinearIntersections (PathList & to) private
Get all the linear intersections.
Ownership of linestring pushed to the given container is transferred to caller. See clearEdges for a deep release if you need one.
Definition at line 104 of file SharedPathsOp.cpp.
References _g1, _g2, _gf, geos::geom::GeometryFactory::createLineString(), and geos::geom::Geometry::getGeometryN().
Referenced by getSharedPaths().
 {
   using geos::operation::overlay::OverlayOp;
   // TODO: optionally use the tolerance,
   //       snapping _g2 over _g1 ?
   std::unique_ptr<Geometry> full ( OverlayOp::overlayOp(
     &_g1, &_g2, OverlayOp::opINTERSECTION) );
   // NOTE: intersection of equal lines yelds splitted lines,
   //       should we sew them back ?
   for (size_t i=0, n=full->getNumGeometries(); i<n; ++i)
   {
     const Geometry* sub = full->getGeometryN(i);
     const LineString* path = dynamic_cast<const LineString*>(sub);
     if ( path ) {
       // NOTE: we're making a copy here, wouldn't be needed
       //       for a simple predicate
       to.push_back(_gf.createLineString(*path).release());
     }
   }
 }
void geos::operation::sharedpaths::SharedPathsOp::getSharedPaths (PathList & sameDirection, PathList & oppositeDirection)
Get shared paths.
Parameters
sameDir Shared edges having the same direction are pushed onto this vector. They'll be of type geom::LineString. Ownership of the edges is tranferred.
oppositeDir Shared edges having the opposite direction are pushed onto this vector. They'll be of type geom::LineString. Ownership of the edges is tranferred.
Definition at line 77 of file SharedPathsOp.cpp.
References findLinearIntersections(), and isSameDirection().
Referenced by sharedPathsOp().
 {
   PathList paths;
   findLinearIntersections(paths);
   for (size_t i=0, n=paths.size(); i<n; ++i)
   {
     LineString* path = paths[i];
     if ( isSameDirection(*path) ) forwDir.push_back(path);
     else backDir.push_back(path);
   }
 }
bool geos::operation::sharedpaths::SharedPathsOp::isForward (const geom::LineString & edge, const geom::Geometry & geom) private
Check if the given edge goes forward or backward on the given line.
PRECONDITION: It is assumed the edge fully lays on the geometry
Definition at line 131 of file SharedPathsOp.cpp.
References geos::linearref::LinearLocation::compareTo(), and geos::geom::LineString::getCoordinateN().
 {
   using namespace geos::linearref;
   /*
      ALGO:
       1. find first point of edge on geom (linearref)
       2. find second point of edge on geom (linearref)
       3. if first < second, we're forward
      PRECONDITIONS:
       1. edge has at least 2 points
       2. edge first two points are not equal
       3. geom is simple
    */
   const Coordinate& pt1 = edge.getCoordinateN(0);
   const Coordinate& pt2 = edge.getCoordinateN(1);
   /*
    * We move the coordinate somewhat closer, to avoid
    * vertices of the geometry being checked (geom).
    *
    * This is mostly only needed when one of the two points
    * of the edge is an endpoint of a _closed_ geom.
    * We have an unit test for this...
    */
   Coordinate pt1i = LinearLocation::pointAlongSegmentByFraction(pt1, pt2, 0.1);
   Coordinate pt2i = LinearLocation::pointAlongSegmentByFraction(pt1, pt2, 0.9);
   LinearLocation l1 = LocationIndexOfPoint::indexOf(&geom, pt1i);
   LinearLocation l2 = LocationIndexOfPoint::indexOf(&geom, pt2i);
   return l1.compareTo(l2) < 0;
 }
bool geos::operation::sharedpaths::SharedPathsOp::isSameDirection (const geom::LineString & edge) inline private
Check if the given edge goes in the same direction over the two geometries.
Definition at line 140 of file SharedPathsOp.h.
Referenced by getSharedPaths().
{
     return (isForward(edge, _g1) == isForward(edge, _g2));
   }
SharedPathsOp& geos::operation::sharedpaths::SharedPathsOp::operator= (const SharedPathsOp & rhs) private delete
void geos::operation::sharedpaths::SharedPathsOp::sharedPathsOp (const geom::Geometry & g1, const geom::Geometry & g2, PathList & sameDirection, PathList & oppositeDirection) static
Find paths shared between two linear geometries.
Parameters
g1 First geometry. Must be linear.
g2 Second geometry. Must be linear.
sameDir Shared edges having the same direction are pushed onto this vector. They'll be of type LineString. Ownership of the edges is tranferred.
oppositeDir Shared edges having the opposite direction are pushed onto this vector. They'll be of type geom::LineString. Ownership of the edges is tranferred.
Definition at line 44 of file SharedPathsOp.cpp.
References getSharedPaths().
 {
   SharedPathsOp sp(g1, g2);
   sp.getSharedPaths(sameDirection, oppositeDirection);
 }
Member Data Documentation
const geom::Geometry& geos::operation::sharedpaths::SharedPathsOp::_g1 private
Definition at line 147 of file SharedPathsOp.h.
Referenced by findLinearIntersections(), and SharedPathsOp().
const geom::Geometry& geos::operation::sharedpaths::SharedPathsOp::_g2 private
Definition at line 148 of file SharedPathsOp.h.
Referenced by findLinearIntersections(), and SharedPathsOp().
const geom::GeometryFactory& geos::operation::sharedpaths::SharedPathsOp::_gf private
Definition at line 149 of file SharedPathsOp.h.
Referenced by findLinearIntersections().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/sharedpaths/SharedPathsOp.h
/home/vicky/potree/geos/vicky/src/operation/sharedpaths/SharedPathsOp.cpp