GEOS: geos::index::strtree::Boundable Class Reference
geos::index::strtree::Boundable Class Reference abstract
A spatial object in an AbstractSTRtree.
#include <Boundable.h>
Public Member Functions
virtual const void * getBounds () const =0
virtual ~Boundable ()
Detailed Description
A spatial object in an AbstractSTRtree.
Definition at line 25 of file Boundable.h.
Constructor & Destructor Documentation
virtual geos::index::strtree::Boundable::~Boundable () inline virtual
Definition at line 41 of file Boundable.h.
 {}
Member Function Documentation
virtual const void* geos::index::strtree::Boundable::getBounds () const pure virtual
Returns a representation of space that encloses this Boundable, preferably not much bigger than this Boundable's boundary yet fast to test for intersection with the bounds of other Boundables.
The class of object returned depends on the subclass of AbstractSTRtree.
Returns
an Envelope (for STRtrees), an Interval (for SIRtrees), or other object (for other subclasses of AbstractSTRtree)
See also
AbstractSTRtree::IntersectsOp
Implemented in geos::index::strtree::AbstractNode, and geos::index::strtree::ItemBoundable.
Referenced by geos::index::strtree::BoundablePair::area(), geos::index::strtree::compareSIRBoundables(), geos::index::strtree::SIRAbstractNode::computeBounds(), geos::index::strtree::STRAbstractNode::computeBounds(), geos::index::strtree::BoundablePair::distance(), geos::index::strtree::AbstractSTRtree::query(), geos::index::strtree::AbstractSTRtree::remove(), and geos::index::strtree::yComparator().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/index/strtree/Boundable.h