GEOS: geos::algorithm::LineIntersector Class Reference
geos::algorithm::LineIntersector Class Reference
A LineIntersector is an algorithm that can both test whether two line segments intersect and compute the intersection point if they do.
#include <LineIntersector.h>
Public Types
enum { DONT_INTERSECT =0, DO_INTERSECT =1, COLLINEAR =2 }
enum { NO_INTERSECTION =0, POINT_INTERSECTION =1, COLLINEAR_INTERSECTION =2 }
Public Member Functions
LineIntersector (const geom::PrecisionModel *initialPrecisionModel=nullptr)
~LineIntersector ()
bool isInteriorIntersection ()
Tests whether either intersection point is an interior point of one of the input segments.
bool isInteriorIntersection (int inputLineIndex)
Tests whether either intersection point is an interior point of the specified input segment.
void setPrecisionModel (const geom::PrecisionModel *newPM)
Force computed intersection to be rounded to a given precision model.
void computeIntersection (const geom::Coordinate &p, const geom::Coordinate &p1, const geom::Coordinate &p2)
Compute the intersection of a point p and the line p1-p2.
void computeIntersection (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &p3, const geom::Coordinate &p4)
Computes the intersection of the lines p1-p2 and p3-p4.
std::string toString () const
bool hasIntersection () const
int getIntersectionNum () const
Returns the number of intersection points found.
const geom::Coordinate & getIntersection (int intIndex) const
Returns the intIndex'th intersection point.
bool isIntersection (const geom::Coordinate &pt) const
Test whether a point is a intersection point of two line segments.
bool isProper () const
Tests whether an intersection is proper.
const geom::Coordinate & getIntersectionAlongSegment (int segmentIndex, int intIndex)
Computes the intIndex'th intersection point in the direction of a specified input line segment.
int getIndexAlongSegment (int segmentIndex, int intIndex)
Computes the index of the intIndex'th intersection point in the direction of a specified input line segment.
double getEdgeDistance (int geomIndex, int intIndex) const
Computes the "edge distance" of an intersection point along the specified input line segment.
Static Public Member Functions
static double interpolateZ (const geom::Coordinate &p, const geom::Coordinate &p0, const geom::Coordinate &p1)
Return a Z value being the interpolation of Z from p0 and p1 at the given point p.
static double computeEdgeDistance (const geom::Coordinate &p, const geom::Coordinate &p0, const geom::Coordinate &p1)
Computes the "edge distance" of an intersection point p in an edge.
static double nonRobustComputeEdgeDistance (const geom::Coordinate &p, const geom::Coordinate &p1, const geom::Coordinate &p2)
static bool hasIntersection (const geom::Coordinate &p, const geom::Coordinate &p1, const geom::Coordinate &p2)
Same as above but doen's compute intersection point. Faster.
static bool isSameSignAndNonZero (double a, double b)
Returns false if both numbers are zero.
Private Member Functions
void intersectionWithNormalization (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &q1, const geom::Coordinate &q2, geom::Coordinate &ret) const
bool isCollinear () const
int computeIntersect (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &q1, const geom::Coordinate &q2)
bool isEndPoint () const
void computeIntLineIndex ()
void computeIntLineIndex (int segmentIndex)
int computeCollinearIntersection (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &q1, const geom::Coordinate &q2)
void intersection (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &q1, const geom::Coordinate &q2, geom::Coordinate &ret) const
This method computes the actual value of the intersection point.
double smallestInAbsValue (double x1, double x2, double x3, double x4) const
bool isInSegmentEnvelopes (const geom::Coordinate &intPt) const
void normalizeToEnvCentre (geom::Coordinate &n00, geom::Coordinate &n01, geom::Coordinate &n10, geom::Coordinate &n11, geom::Coordinate &normPt) const
Normalize the supplied coordinates to so that the midpoint of their intersection envelope lies at the origin.
void safeHCoordinateIntersection (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &q1, const geom::Coordinate &q2, geom::Coordinate &intPt) const
Private Attributes
const geom::PrecisionModel * precisionModel
int result
const geom::Coordinate * inputLines [2][2]
geom::Coordinate intPt [2]
int intLineIndex [2][2]
bool isProperVar
Detailed Description
A LineIntersector is an algorithm that can both test whether two line segments intersect and compute the intersection point if they do.
The intersection point may be computed in a precise or non-precise manner. Computing it precisely involves rounding it to an integer. (This assumes that the input coordinates have been made precise by scaling them to an integer grid.)
Definition at line 49 of file LineIntersector.h.
Member Enumeration Documentation
anonymous enum
Enumerator
DONT_INTERSECT
DO_INTERSECT
COLLINEAR
Definition at line 129 of file LineIntersector.h.
        {
     DONT_INTERSECT=0,
     DO_INTERSECT=1,
     COLLINEAR=2
   };
anonymous enum
Enumerator
NO_INTERSECTION
Indicates that line segments do not intersect.
POINT_INTERSECTION
Indicates that line segments intersect in a single point.
COLLINEAR_INTERSECTION
Indicates that line segments intersect in a line segment.
Definition at line 135 of file LineIntersector.h.
        {
     NO_INTERSECTION=0,
     POINT_INTERSECTION=1,
     COLLINEAR_INTERSECTION=2
   };
Constructor & Destructor Documentation
geos::algorithm::LineIntersector::LineIntersector (const geom::PrecisionModel * initialPrecisionModel = nullptr) inline
Definition at line 80 of file LineIntersector.h.
     :
     precisionModel(initialPrecisionModel),
     result(0),
     isProperVar(false)
   {}
geos::algorithm::LineIntersector::~LineIntersector () inline
Definition at line 87 of file LineIntersector.h.
 {}
Member Function Documentation
int geos::algorithm::LineIntersector::computeCollinearIntersection (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & q1, const geom::Coordinate & q2) private
Definition at line 554 of file LineIntersector.cpp.
References geos::geom::Coordinate::toString(), and geos::geom::Coordinate::z.
 {
 #if COMPUTE_Z
   double ztot;
   int hits;
   double p2z;
   double p1z;
   double q1z;
   double q2z;
 #endif // COMPUTE_Z
 #if GEOS_DEBUG
   cerr<<"LineIntersector::computeCollinearIntersection called"<<endl;
   cerr<<" p1:"<<p1.toString()<<" p2:"<<p2.toString()<<" q1:"<<q1.toString()<<" q2:"<<q2.toString()<<endl;
 #endif // GEOS_DEBUG
   bool p1q1p2=Envelope::intersects(p1,p2,q1);
   bool p1q2p2=Envelope::intersects(p1,p2,q2);
   bool q1p1q2=Envelope::intersects(q1,q2,p1);
   bool q1p2q2=Envelope::intersects(q1,q2,p2);
   if (p1q1p2 && p1q2p2) {
 #if GEOS_DEBUG
     cerr<<" p1q1p2 && p1q2p2"<<endl;
 #endif
     intPt[0]=q1;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     q1z = interpolateZ(q1, p1, p2);
     if (!ISNAN(q1z)) { ztot+=q1z; hits++; }
     if (!ISNAN(q1.z)) { ztot+=q1.z; hits++; }
     if ( hits ) intPt[0].z = ztot/hits;
 #endif
     intPt[1]=q2;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     q2z = interpolateZ(q2, p1, p2);
     if (!ISNAN(q2z)) { ztot+=q2z; hits++; }
     if (!ISNAN(q2.z)) { ztot+=q2.z; hits++; }
     if ( hits ) intPt[1].z = ztot/hits;
 #endif
 #if GEOS_DEBUG
     cerr<<" intPt[0]: "<<intPt[0].toString()<<endl;
     cerr<<" intPt[1]: "<<intPt[1].toString()<<endl;
 #endif
     return COLLINEAR_INTERSECTION;
   }
   if (q1p1q2 && q1p2q2) {
 #if GEOS_DEBUG
     cerr<<" q1p1q2 && q1p2q2"<<endl;
 #endif
     intPt[0]=p1;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     p1z = interpolateZ(p1, q1, q2);
     if (!ISNAN(p1z)) { ztot+=p1z; hits++; }
     if (!ISNAN(p1.z)) { ztot+=p1.z; hits++; }
     if ( hits ) intPt[0].z = ztot/hits;
 #endif
     intPt[1]=p2;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     p2z = interpolateZ(p2, q1, q2);
     if (!ISNAN(p2z)) { ztot+=p2z; hits++; }
     if (!ISNAN(p2.z)) { ztot+=p2.z; hits++; }
     if ( hits ) intPt[1].z = ztot/hits;
 #endif
     return COLLINEAR_INTERSECTION;
   }
   if (p1q1p2 && q1p1q2) {
 #if GEOS_DEBUG
     cerr<<" p1q1p2 && q1p1q2"<<endl;
 #endif
     intPt[0]=q1;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     q1z = interpolateZ(q1, p1, p2);
     if (!ISNAN(q1z)) { ztot+=q1z; hits++; }
     if (!ISNAN(q1.z)) { ztot+=q1.z; hits++; }
     if ( hits ) intPt[0].z = ztot/hits;
 #endif
     intPt[1]=p1;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     p1z = interpolateZ(p1, q1, q2);
     if (!ISNAN(p1z)) { ztot+=p1z; hits++; }
     if (!ISNAN(p1.z)) { ztot+=p1.z; hits++; }
     if ( hits ) intPt[1].z = ztot/hits;
 #endif
 #if GEOS_DEBUG
     cerr<<" intPt[0]: "<<intPt[0].toString()<<endl;
     cerr<<" intPt[1]: "<<intPt[1].toString()<<endl;
 #endif
     return (q1==p1) && !p1q2p2 && !q1p2q2 ? POINT_INTERSECTION : COLLINEAR_INTERSECTION;
   }
   if (p1q1p2 && q1p2q2) {
 #if GEOS_DEBUG
     cerr<<" p1q1p2 && q1p2q2"<<endl;
 #endif
     intPt[0]=q1;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     q1z = interpolateZ(q1, p1, p2);
     if (!ISNAN(q1z)) { ztot+=q1z; hits++; }
     if (!ISNAN(q1.z)) { ztot+=q1.z; hits++; }
     if ( hits ) intPt[0].z = ztot/hits;
 #endif
     intPt[1]=p2;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     p2z = interpolateZ(p2, q1, q2);
     if (!ISNAN(p2z)) { ztot+=p2z; hits++; }
     if (!ISNAN(p2.z)) { ztot+=p2.z; hits++; }
     if ( hits ) intPt[1].z = ztot/hits;
 #endif
 #if GEOS_DEBUG
     cerr<<" intPt[0]: "<<intPt[0].toString()<<endl;
     cerr<<" intPt[1]: "<<intPt[1].toString()<<endl;
 #endif
     return (q1==p2) && !p1q2p2 && !q1p1q2 ? POINT_INTERSECTION : COLLINEAR_INTERSECTION;
   }
   if (p1q2p2 && q1p1q2) {
 #if GEOS_DEBUG
     cerr<<" p1q2p2 && q1p1q2"<<endl;
 #endif
     intPt[0]=q2;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     q2z = interpolateZ(q2, p1, p2);
     if (!ISNAN(q2z)) { ztot+=q2z; hits++; }
     if (!ISNAN(q2.z)) { ztot+=q2.z; hits++; }
     if ( hits ) intPt[0].z = ztot/hits;
 #endif
     intPt[1]=p1;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     p1z = interpolateZ(p1, q1, q2);
     if (!ISNAN(p1z)) { ztot+=p1z; hits++; }
     if (!ISNAN(p1.z)) { ztot+=p1.z; hits++; }
     if ( hits ) intPt[1].z = ztot/hits;
 #endif
 #if GEOS_DEBUG
     cerr<<" intPt[0]: "<<intPt[0].toString()<<endl;
     cerr<<" intPt[1]: "<<intPt[1].toString()<<endl;
 #endif
     return (q2==p1) && !p1q1p2 && !q1p2q2 ? POINT_INTERSECTION : COLLINEAR_INTERSECTION;
   }
   if (p1q2p2 && q1p2q2) {
 #if GEOS_DEBUG
     cerr<<" p1q2p2 && q1p2q2"<<endl;
 #endif
     intPt[0]=q2;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     q2z = interpolateZ(q2, p1, p2);
     if (!ISNAN(q2z)) { ztot+=q2z; hits++; }
     if (!ISNAN(q2.z)) { ztot+=q2.z; hits++; }
     if ( hits ) intPt[0].z = ztot/hits;
 #endif
     intPt[1]=p2;
 #if COMPUTE_Z
     ztot=0;
     hits=0;
     p2z = interpolateZ(p2, q1, q2);
     if (!ISNAN(p2z)) { ztot+=p2z; hits++; }
     if (!ISNAN(p2.z)) { ztot+=p2.z; hits++; }
     if ( hits ) intPt[1].z = ztot/hits;
 #endif
 #if GEOS_DEBUG
     cerr<<" intPt[0]: "<<intPt[0].toString()<<endl;
     cerr<<" intPt[1]: "<<intPt[1].toString()<<endl;
 #endif
     return (q2==p2) && !p1q1p2 && !q1p1q2 ? POINT_INTERSECTION : COLLINEAR_INTERSECTION;
   }
   return NO_INTERSECTION;
 }
double geos::algorithm::LineIntersector::computeEdgeDistance (const geom::Coordinate & p, const geom::Coordinate & p0, const geom::Coordinate & p1) static
Computes the "edge distance" of an intersection point p in an edge.
The edge distance is a metric of the point along the edge. The metric used is a robust and easy to compute metric function. It is not equivalent to the usual Euclidean metric. It relies on the fact that either the x or the y ordinates of the points in the edge are unique, depending on whether the edge is longer in the horizontal or vertical direction.
NOTE: This function may produce incorrect distances for inputs where p is not precisely on p1-p2 (E.g. p = (139,9) p1 = (139,10), p2 = (280,1) produces distanct 0.0, which is incorrect.
My hypothesis is that the function is safe to use for points which are the result of rounding points which lie on the line, but not safe to use for truncated points.
Definition at line 108 of file LineIntersector.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   double dx=fabs(p1.x-p0.x);
   double dy=fabs(p1.y-p0.y);
   double dist=-1.0; // sentinel value
   if (p==p0) {
     dist=0.0;
   } else if (p==p1) {
     if (dx>dy)
       dist=dx;
     else
       dist=dy;
   } else {
     double pdx=fabs(p.x - p0.x);
     double pdy=fabs(p.y - p0.y);
     if (dx > dy)
       dist = pdx;
     else
       dist = pdy;
     // <FIX>
     // hack to ensure that non-endpoints always have a non-zero distance
     if (dist == 0.0 && !(p==p0)) {
       dist=std::max(pdx,pdy);
     }
   }
   assert(!(dist == 0.0 && !(p==p0))); // Bad distance calculation
   return dist;
 }
int geos::algorithm::LineIntersector::computeIntersect (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & q1, const geom::Coordinate & q2) private
At this point we know that there is a single intersection point (since the lines are not collinear).
Now check to see if any endpoint lies on the interior of the other segment.
Definition at line 383 of file LineIntersector.cpp.
References geos::geom::Coordinate::equals2D(), geos::geom::Coordinate::toString(), and geos::geom::Coordinate::z.
 {
 #if GEOS_DEBUG
   cerr<<"LineIntersector::computeIntersect called"<<endl;
   cerr<<" p1:"<<p1.toString()<<" p2:"<<p2.toString()<<" q1:"<<q1.toString()<<" q2:"<<q2.toString()<<endl;
 #endif // GEOS_DEBUG
   isProperVar=false;
   // first try a fast test to see if the envelopes of the lines intersect
   if (!Envelope::intersects(p1,p2,q1,q2))
   {
 #if GEOS_DEBUG
     cerr<<" NO_INTERSECTION"<<endl;
 #endif
     return NO_INTERSECTION;
   }
   // for each endpoint, compute which side of the other segment it lies
   // if both endpoints lie on the same side of the other segment,
   // the segments do not intersect
   int Pq1=CGAlgorithms::orientationIndex(p1,p2,q1);
   int Pq2=CGAlgorithms::orientationIndex(p1,p2,q2);
   if ((Pq1>0 && Pq2>0) || (Pq1<0 && Pq2<0))
   {
 #if GEOS_DEBUG
     cerr<<" NO_INTERSECTION"<<endl;
 #endif
     return NO_INTERSECTION;
   }
   int Qp1=CGAlgorithms::orientationIndex(q1,q2,p1);
   int Qp2=CGAlgorithms::orientationIndex(q1,q2,p2);
   if ((Qp1>0 && Qp2>0)||(Qp1<0 && Qp2<0)) {
 #if GEOS_DEBUG
     cerr<<" NO_INTERSECTION"<<endl;
 #endif
     return NO_INTERSECTION;
   }
   bool collinear=Pq1==0 && Pq2==0 && Qp1==0 && Qp2==0;
   if (collinear) {
 #if GEOS_DEBUG
     cerr<<" computingCollinearIntersection"<<endl;
 #endif
     return computeCollinearIntersection(p1,p2,q1,q2);
   }
   /*
    * Check if the intersection is an endpoint.
    * If it is, copy the endpoint as
    * the intersection point. Copying the point rather than
    * computing it ensures the point has the exact value,
    * which is important for robustness. It is sufficient to
    * simply check for an endpoint which is on the other line,
    * since at this point we know that the inputLines must
    *  intersect.
    */
   if (Pq1==0 || Pq2==0 || Qp1==0 || Qp2==0) {
 #if COMPUTE_Z
     int hits=0;
     double z=0.0;
 #endif
     isProperVar=false;
     /* Check for two equal endpoints.
      * This is done explicitly rather than by the orientation tests
      * below in order to improve robustness.
      *
      * (A example where the orientation tests fail
      *  to be consistent is:
      *
      * LINESTRING ( 19.850257749638203 46.29709338043669,
      *      20.31970698357233 46.76654261437082 )
      * and
      * LINESTRING ( -48.51001596420236 -22.063180333403878,
      *      19.850257749638203 46.29709338043669 )
      *
      * which used to produce the result:
      * (20.31970698357233, 46.76654261437082, NaN)
      */
     if ( p1.equals2D(q1) || p1.equals2D(q2) ) {
       intPt[0]=p1;
 #if COMPUTE_Z
       if ( !ISNAN(p1.z) )
       {
         z += p1.z;
         hits++;
       }
 #endif
     }
     else if ( p2.equals2D(q1) || p2.equals2D(q2) ) {
       intPt[0]=p2;
 #if COMPUTE_Z
       if ( !ISNAN(p2.z) )
       {
         z += p2.z;
         hits++;
       }
 #endif
     }
     else if (Pq1==0) {
       intPt[0]=q1;
 #if COMPUTE_Z
       if ( !ISNAN(q1.z) )
       {
         z += q1.z;
         hits++;
       }
 #endif
     }
     else if (Pq2==0) {
       intPt[0]=q2;
 #if COMPUTE_Z
       if ( !ISNAN(q2.z) )
       {
         z += q2.z;
         hits++;
       }
 #endif
     }
     else if (Qp1==0) {
       intPt[0]=p1;
 #if COMPUTE_Z
       if ( !ISNAN(p1.z) )
       {
         z += p1.z;
         hits++;
       }
 #endif
     }
     else if (Qp2==0) {
       intPt[0]=p2;
 #if COMPUTE_Z
       if ( !ISNAN(p2.z) )
       {
         z += p2.z;
         hits++;
       }
 #endif
     }
 #if COMPUTE_Z
 #if GEOS_DEBUG
     cerr<<"LineIntersector::computeIntersect: z:"<<z<<" hits:"<<hits<<endl;
 #endif // GEOS_DEBUG
     if ( hits ) intPt[0].z = z/hits;
 #endif // COMPUTE_Z
   } else {
     isProperVar=true;
     intersection(p1, p2, q1, q2, intPt[0]);
   }
 #if GEOS_DEBUG
   cerr<<" POINT_INTERSECTION; intPt[0]:"<<intPt[0].toString()<<endl;
 #endif // GEOS_DEBUG
   return POINT_INTERSECTION;
 }
void geos::algorithm::LineIntersector::computeIntersection (const geom::Coordinate & p, const geom::Coordinate & p1, const geom::Coordinate & p2)
Compute the intersection of a point p and the line p1-p2.
This function computes the boolean value of the hasIntersection test. The actual value of the intersection (if there is one) is equal to the value of p.
Definition at line 334 of file LineIntersector.cpp.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addCollinear(), geos::operation::buffer::OffsetSegmentGenerator::addInsideTurn(), geos::geom::LineSegment::intersection(), geos::noding::snapround::HotPixel::intersectsPixelClosure(), geos::noding::snapround::HotPixel::intersectsToleranceSquare(), geos::operation::overlay::OverlayOp::mergeZ(), and geos::noding::SegmentIntersectionDetector::processIntersections().
 {
   isProperVar=false;
   // do between check first, since it is faster than the orientation test
   if(Envelope::intersects(p1,p2,p)) {
     if ((CGAlgorithms::orientationIndex(p1,p2,p)==0)&&
       (CGAlgorithms::orientationIndex(p2,p1,p)==0)) {
       isProperVar=true;
       if ((p==p1)||(p==p2)) // 2d only test
       {
         isProperVar=false;
       }
 #if COMPUTE_Z
       intPt[0]=p;
 #if GEOS_DEBUG
       cerr<<"RobustIntersector::computeIntersection(Coordinate,Coordinate,Coordinate) calling interpolateZ"<<endl;
 #endif
       double z = interpolateZ(p, p1, p2);
       if ( !ISNAN(z) )
       {
         if ( ISNAN(intPt[0].z) )
           intPt[0].z = z;
         else
           intPt[0].z = (intPt[0].z+z)/2;
       }
 #endif // COMPUTE_Z
       result=POINT_INTERSECTION;
       return;
     }
   }
   result = NO_INTERSECTION;
 }
void geos::algorithm::LineIntersector::computeIntersection (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & p3, const geom::Coordinate & p4)
Computes the intersection of the lines p1-p2 and p3-p4.
Definition at line 139 of file LineIntersector.cpp.
 {
   inputLines[0][0]=&p1;
   inputLines[0][1]=&p2;
   inputLines[1][0]=&p3;
   inputLines[1][1]=&p4;
   result=computeIntersect(p1,p2,p3,p4);
   //numIntersects++;
 }
void geos::algorithm::LineIntersector::computeIntLineIndex () private
Definition at line 181 of file LineIntersector.cpp.
{
   computeIntLineIndex(0);
   computeIntLineIndex(1);
 }
void geos::algorithm::LineIntersector::computeIntLineIndex (int segmentIndex) private
Definition at line 217 of file LineIntersector.cpp.
 {
   double dist0=getEdgeDistance(segmentIndex,0);
   double dist1=getEdgeDistance(segmentIndex,1);
   if (dist0>dist1) {
     intLineIndex[segmentIndex][0]=0;
     intLineIndex[segmentIndex][1]=1;
   } else {
     intLineIndex[segmentIndex][0]=1;
     intLineIndex[segmentIndex][1]=0;
   }
 }
double geos::algorithm::LineIntersector::getEdgeDistance (int geomIndex, int intIndex) const
Computes the "edge distance" of an intersection point along the specified input line segment.
Parameters
segmentIndex is 0 or 1
intIndex is 0 or 1
Returns
the edge distance of the intersection point
Definition at line 232 of file LineIntersector.cpp.
Referenced by geos::geomgraph::Edge::addIntersection().
 {
   double dist=computeEdgeDistance(intPt[intIndex],
     *inputLines[segmentIndex][0],
     *inputLines[segmentIndex][1]);
   return dist;
 }
int geos::algorithm::LineIntersector::getIndexAlongSegment (int segmentIndex, int intIndex)
Computes the index of the intIndex'th intersection point in the direction of a specified input line segment.
Parameters
segmentIndex is 0 or 1
intIndex is 0 or 1
Returns
the index of the intersection point along the segment (0 or 1)
Definition at line 209 of file LineIntersector.cpp.
 {
   computeIntLineIndex();
   return intLineIndex[segmentIndex][intIndex];
 }
const geom::Coordinate& geos::algorithm::LineIntersector::getIntersection (int intIndex) const inline
Returns the intIndex'th intersection point.
Parameters
intIndex is 0 or 1
Returns
the intIndex'th intersection point
Definition at line 172 of file LineIntersector.h.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addInsideTurn(), geos::noding::NodedSegmentString::addIntersection(), geos::geomgraph::Edge::addIntersection(), geos::noding::NodingValidator::hasInteriorIntersection(), geos::geom::LineSegment::intersection(), and geos::noding::SegmentIntersectionDetector::processIntersections().
{
     return intPt[intIndex];
   }
const Coordinate & geos::algorithm::LineIntersector::getIntersectionAlongSegment (int segmentIndex, int intIndex)
Computes the intIndex'th intersection point in the direction of a specified input line segment.
Parameters
segmentIndex is 0 or 1
intIndex is 0 or 1
Returns
the intIndex'th intersection point in the direction of the specified input line segment
Definition at line 200 of file LineIntersector.cpp.
 {
   // lazily compute int line array
   computeIntLineIndex();
   return intPt[intLineIndex[segmentIndex][intIndex]];
 }
int geos::algorithm::LineIntersector::getIntersectionNum () const inline
Returns the number of intersection points found.
This will be either 0, 1 or 2.
Definition at line 163 of file LineIntersector.h.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addCollinear(), geos::noding::NodedSegmentString::addIntersections(), geos::geomgraph::Edge::addIntersections(), and geos::noding::NodingValidator::hasInteriorIntersection().
 { return result; }
bool geos::algorithm::LineIntersector::hasIntersection (const geom::Coordinate & p, const geom::Coordinate & p1, const geom::Coordinate & p2) static
Same as above but doen's compute intersection point. Faster.
Definition at line 370 of file LineIntersector.cpp.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addInsideTurn(), geos::geom::LineSegment::intersection(), geos::noding::snapround::HotPixel::intersectsPixelClosure(), geos::noding::snapround::HotPixel::intersectsToleranceSquare(), geos::operation::overlay::OverlayOp::mergeZ(), and geos::noding::SegmentIntersectionDetector::processIntersections().
 {
   if(Envelope::intersects(p1,p2,p)) {
     if ((CGAlgorithms::orientationIndex(p1,p2,p)==0)&&
       (CGAlgorithms::orientationIndex(p2,p1,p)==0)) {
       return true;
     }
   }
   return false;
 }
bool geos::algorithm::LineIntersector::hasIntersection () const inline
Tests whether the input geometries intersect.
Returns
true if the input geometries intersect
Definition at line 157 of file LineIntersector.h.
 { return result!=NO_INTERSECTION; }
double geos::algorithm::LineIntersector::interpolateZ (const geom::Coordinate & p, const geom::Coordinate & p0, const geom::Coordinate & p1) static
Return a Z value being the interpolation of Z from p0 and p1 at the given point p.
Definition at line 266 of file LineIntersector.cpp.
References geos::geom::Coordinate::toString(), geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
 {
 #if GEOS_DEBUG
   cerr<<"LineIntersector::interpolateZ("<<p.toString()<<", "<<p1.toString()<<", "<<p2.toString()<<")"<<endl;
 #endif
   if ( ISNAN(p1.z) )
   {
 #if GEOS_DEBUG
     cerr<<" p1 do not have a Z"<<endl;
 #endif
     return p2.z; // might be DoubleNotANumber again
   }
   if ( ISNAN(p2.z) )
   {
 #if GEOS_DEBUG
     cerr<<" p2 do not have a Z"<<endl;
 #endif
     return p1.z; // might be DoubleNotANumber again
   }
   if (p==p1)
   {
 #if GEOS_DEBUG
     cerr<<" p==p1, returning "<<p1.z<<endl;
 #endif
     return p1.z;
   }
   if (p==p2)
   {
 #if GEOS_DEBUG
     cerr<<" p==p2, returning "<<p2.z<<endl;
 #endif
     return p2.z;
   }
   //double zgap = fabs(p2.z - p1.z);
   double zgap = p2.z - p1.z;
   if ( ! zgap )
   {
 #if GEOS_DEBUG
     cerr<<" no zgap, returning "<<p2.z<<endl;
 #endif
     return p2.z;
   }
   double xoff = (p2.x-p1.x);
   double yoff = (p2.y-p1.y);
   double seglen = (xoff*xoff+yoff*yoff);
   xoff = (p.x-p1.x);
   yoff = (p.y-p1.y);
   double pdist = (xoff*xoff+yoff*yoff);
   double fract = sqrt(pdist/seglen);
   double zoff = zgap*fract;
   //double interpolated = p1.z < p2.z ? p1.z+zoff : p1.z-zoff;
   double interpolated = p1.z+zoff;
 #if GEOS_DEBUG
   cerr<<" zgap:"<<zgap<<" seglen:"<<seglen<<" pdist:"<<pdist
     <<" fract:"<<fract<<" z:"<<interpolated<<endl;
 #endif
   return interpolated;
 }
void geos::algorithm::LineIntersector::intersection (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & q1, const geom::Coordinate & q2, geom::Coordinate & ret) const private
This method computes the actual value of the intersection point.
To obtain the maximum precision from the intersection calculation, the coordinates are normalized by subtracting the minimum ordinate values (in absolute value). This has the effect of removing common significant digits from the calculation to maintain more bits of precision.
Definition at line 744 of file LineIntersector.cpp.
References geos::geom::Coordinate::z.
 {
   intersectionWithNormalization(p1, p2, q1, q2, intPtOut);
   /*
    * Due to rounding it can happen that the computed intersection is
    * outside the envelopes of the input segments.  Clearly this
    * is inconsistent.
    * This code checks this condition and forces a more reasonable answer
    *
    * MD - May 4 2005 - This is still a problem.  Here is a failure case:
    *
    * LINESTRING (2089426.5233462777 1180182.3877339689,
    *             2085646.6891757075 1195618.7333999649)
    * LINESTRING (1889281.8148903656 1997547.0560044837,
    *             2259977.3672235999 483675.17050843034)
    * int point = (2097408.2633752143,1144595.8008114607)
    */
   if (! isInSegmentEnvelopes(intPtOut))
   {
     //intPt = CentralEndpointIntersector::getIntersection(p1, p2, q1, q2);
     intPtOut = nearestEndpoint(p1, p2, q1, q2);
 #if GEOS_DEBUG
     cerr << "Intersection outside segment envelopes, snapped to "
          << intPt.toString() << endl;
 #endif
   }
   if (precisionModel!=nullptr) {
     precisionModel->makePrecise(intPtOut);
   }
 #if COMPUTE_Z
   double ztot = 0;
   double zvals = 0;
   double zp = interpolateZ(intPtOut, p1, p2);
   double zq = interpolateZ(intPtOut, q1, q2);
   if ( !ISNAN(zp)) { ztot += zp; zvals++; }
   if ( !ISNAN(zq)) { ztot += zq; zvals++; }
   if ( zvals ) intPtOut.z = ztot/zvals;
 #endif // COMPUTE_Z
 }
void geos::algorithm::LineIntersector::intersectionWithNormalization (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & q1, const geom::Coordinate & q2, geom::Coordinate & ret) const private
Definition at line 795 of file LineIntersector.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   Coordinate n1=p1;
   Coordinate n2=p2;
   Coordinate n3=q1;
   Coordinate n4=q2;
   Coordinate normPt;
   normalizeToEnvCentre(n1, n2, n3, n4, normPt);
   safeHCoordinateIntersection(n1, n2, n3, n4, intPtOut);
   intPtOut.x += normPt.x;
   intPtOut.y += normPt.y;
 }
bool geos::algorithm::LineIntersector::isCollinear () const inline private
Definition at line 280 of file LineIntersector.h.
 { return result==COLLINEAR_INTERSECTION; }
bool geos::algorithm::LineIntersector::isEndPoint () const inline private
Definition at line 284 of file LineIntersector.h.
{
     return hasIntersection()&&!isProperVar;
   }
bool geos::algorithm::LineIntersector::isInSegmentEnvelopes (const geom::Coordinate & intPt) const private
Test whether a point lies in the envelopes of both input segments. A correctly computed intersection point should return true for this test. Since this test is for debugging purposes only, no attempt is made to optimize the envelope test.
Returns
true if the input point lies within both input segment envelopes
Definition at line 835 of file LineIntersector.cpp.
References geos::geom::Envelope::contains().
 {
   Envelope env0(*inputLines[0][0], *inputLines[0][1]);
   Envelope env1(*inputLines[1][0], *inputLines[1][1]);
   return env0.contains(pt) && env1.contains(pt);
 }
bool geos::algorithm::LineIntersector::isInteriorIntersection ()
Tests whether either intersection point is an interior point of one of the input segments.
Returns
true if either intersection point is in the interior of one of the input segments
Definition at line 242 of file LineIntersector.cpp.
 {
   if (isInteriorIntersection(0)) return true;
   if (isInteriorIntersection(1)) return true;
   return false;
 }
bool geos::algorithm::LineIntersector::isInteriorIntersection (int inputLineIndex)
Tests whether either intersection point is an interior point of the specified input segment.
Returns
true if either intersection point is in the interior of the input segment
Definition at line 251 of file LineIntersector.cpp.
 {
   for (int i=0; i<result; i++)
   {
     if (!(intPt[i].equals2D(*inputLines[inputLineIndex][0])
                 || intPt[i].equals2D(*inputLines[inputLineIndex][1])))
         {
       return true;
     }
   }
   return false;
 }
bool geos::algorithm::LineIntersector::isIntersection (const geom::Coordinate & pt) const
Test whether a point is a intersection point of two line segments.
Note that if the intersection is a line segment, this method only tests for equality with the endpoints of the intersection segment. It does not return true if the input point is internal to the intersection segment.
Returns
true if the input point is one of the intersection points.
Definition at line 188 of file LineIntersector.cpp.
Referenced by geos::geomgraph::index::SegmentIntersector::isBoundaryPoint().
 {
   for (int i=0;i<result;i++) {
     if (intPt[i].equals2D(pt)) {
       return true;
     }
   }
   return false;
 }
bool geos::algorithm::LineIntersector::isProper () const inline
Tests whether an intersection is proper.
The intersection between two line segments is considered proper if they intersect in a single point in the interior of both segments (e.g. the intersection is a single point and is not equal to any of the endpoints).
The intersection between a point and a line segment is considered proper if the point lies in the interior of the segment (e.g. is not equal to either of the endpoints).
Returns
true if the intersection is proper
Definition at line 208 of file LineIntersector.h.
Referenced by geos::noding::snapround::HotPixel::intersectsToleranceSquare(), and geos::noding::SegmentIntersectionDetector::processIntersections().
{
     return hasIntersection()&&isProperVar;
   }
bool geos::algorithm::LineIntersector::isSameSignAndNonZero (double a, double b) static
Returns false if both numbers are zero.
Returns
true if both numbers are positive or if both numbers are negative.
Definition at line 171 of file LineIntersector.cpp.
 {
   if (a==0 || b==0) {
     return false;
   }
   return (a<0 && b<0) || (a>0 && b>0);
 }
static double geos::algorithm::LineIntersector::nonRobustComputeEdgeDistance (const geom::Coordinate & p, const geom::Coordinate & p1, const geom::Coordinate & p2) static
void geos::algorithm::LineIntersector::normalizeToEnvCentre (geom::Coordinate & n00, geom::Coordinate & n01, geom::Coordinate & n10, geom::Coordinate & n11, geom::Coordinate & normPt) const private
Normalize the supplied coordinates to so that the midpoint of their intersection envelope lies at the origin.
Parameters
n00
n01
n10
n11
normPt
Definition at line 844 of file LineIntersector.cpp.
References geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
 {
   double minX0 = n00.x < n01.x ? n00.x : n01.x;
   double minY0 = n00.y < n01.y ? n00.y : n01.y;
   double maxX0 = n00.x > n01.x ? n00.x : n01.x;
   double maxY0 = n00.y > n01.y ? n00.y : n01.y;
   double minX1 = n10.x < n11.x ? n10.x : n11.x;
   double minY1 = n10.y < n11.y ? n10.y : n11.y;
   double maxX1 = n10.x > n11.x ? n10.x : n11.x;
   double maxY1 = n10.y > n11.y ? n10.y : n11.y;
   double intMinX = minX0 > minX1 ? minX0 : minX1;
   double intMaxX = maxX0 < maxX1 ? maxX0 : maxX1;
   double intMinY = minY0 > minY1 ? minY0 : minY1;
   double intMaxY = maxY0 < maxY1 ? maxY0 : maxY1;
   double intMidX = (intMinX + intMaxX) / 2.0;
   double intMidY = (intMinY + intMaxY) / 2.0;
   normPt.x = intMidX;
   normPt.y = intMidY;
   n00.x -= normPt.x;    n00.y -= normPt.y;
   n01.x -= normPt.x;    n01.y -= normPt.y;
   n10.x -= normPt.x;    n10.y -= normPt.y;
   n11.x -= normPt.x;    n11.y -= normPt.y;
 #if COMPUTE_Z
   // Only do this if input does have Z
   // See https://trac.osgeo.org/geos/ticket/811
   if( ISNAN(n00.z) ) return;
   double minZ0 = n00.z < n01.z ? n00.z : n01.z;
   double minZ1 = n10.z < n11.z ? n10.z : n11.z;
   double maxZ0 = n00.z > n01.z ? n00.z : n01.z;
   double maxZ1 = n10.z > n11.z ? n10.z : n11.z;
   double intMinZ = minZ0 > minZ1 ? minZ0 : minZ1;
   double intMaxZ = maxZ0 < maxZ1 ? maxZ0 : maxZ1;
   double intMidZ = (intMinZ + intMaxZ) / 2.0;
   normPt.z = intMidZ;
   n00.z -= normPt.z;
   n01.z -= normPt.z;
   n10.z -= normPt.z;
   n11.z -= normPt.z;
 #endif
 }
void geos::algorithm::LineIntersector::safeHCoordinateIntersection (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & q1, const geom::Coordinate & q2, geom::Coordinate & intPt) const private
Computes a segment intersection using homogeneous coordinates. Round-off error can cause the raw computation to fail, (usually due to the segments being approximately parallel). If this happens, a reasonable approximation is computed instead.
Parameters
p1 a segment endpoint
p2 a segment endpoint
q1 a segment endpoint
q2 a segment endpoint
intPt the computed intersection point is stored there
Definition at line 896 of file LineIntersector.cpp.
 {
   try {
     HCoordinate::intersection(p1, p2, q1, q2, intPtOut);
 #if GEOS_DEBUG
     cerr<<" HCoordinate found intersection h:"<<intPt.toString()<<endl;
 #endif
   } catch (const NotRepresentableException& /* e */) {
     // compute an approximate result
     //intPt = CentralEndpointIntersector::getIntersection(p1, p2, q1, q2);
     intPtOut = nearestEndpoint(p1, p2, q1, q2);
       }
 }
void geos::algorithm::LineIntersector::setPrecisionModel (const geom::PrecisionModel * newPM) inline
Force computed intersection to be rounded to a given precision model.
No getter is provided, because the precision model is not required to be specified.
Parameters
precisionModel the PrecisionModel to use for rounding
Definition at line 113 of file LineIntersector.h.
Referenced by geos::operation::GeometryGraphOperation::setComputationPrecision().
{
     precisionModel=newPM;
   }
double geos::algorithm::LineIntersector::smallestInAbsValue (double x1, double x2, double x3, double x4) const private
Definition at line 815 of file LineIntersector.cpp.
 {
   double x=x1;
   double xabs=fabs(x);
   if(fabs(x2)<xabs) {
     x=x2;
     xabs=fabs(x2);
   }
   if(fabs(x3)<xabs) {
     x=x3;
     xabs=fabs(x3);
   }
   if(fabs(x4)<xabs) {
     x=x4;
   }
   return x;
 }
string geos::algorithm::LineIntersector::toString () const
Definition at line 151 of file LineIntersector.cpp.
Referenced by geos::geomgraph::Edge::addIntersection(), geos::geomgraph::Edge::addIntersections(), and geos::operation::overlay::OverlayOp::computeOverlay().
 {
   string str=inputLines[0][0]->toString()+"_"
         +inputLines[0][1]->toString()+" "
         +inputLines[1][0]->toString()+"_"
         +inputLines[1][1]->toString()+" : ";
   if (isEndPoint()) {
     str+=" endpoint";
   }
   if (isProperVar) {
     str+=" proper";
   }
   if (isCollinear()) {
     str+=" collinear";
   }
   return str;
 }
Member Data Documentation
const geom::Coordinate* geos::algorithm::LineIntersector::inputLines[2][2] private
Definition at line 262 of file LineIntersector.h.
int geos::algorithm::LineIntersector::intLineIndex[2][2] private
The indexes of the endpoints of the intersection lines, in order along the corresponding line
Definition at line 274 of file LineIntersector.h.
geom::Coordinate geos::algorithm::LineIntersector::intPt[2] private
We store real Coordinates here because we must compute the Z of intersection point.
Definition at line 268 of file LineIntersector.h.
bool geos::algorithm::LineIntersector::isProperVar private
Definition at line 276 of file LineIntersector.h.
const geom::PrecisionModel* geos::algorithm::LineIntersector::precisionModel private
If makePrecise is true, computed intersection coordinates will be made precise using Coordinate::makePrecise
Definition at line 258 of file LineIntersector.h.
int geos::algorithm::LineIntersector::result private
Definition at line 260 of file LineIntersector.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/LineIntersector.h
/home/vicky/potree/geos/vicky/src/algorithm/LineIntersector.cpp