GEOS: geos::algorithm::MinimumDiameter Class Reference
geos::algorithm::MinimumDiameter Class Reference
Computes the minimum diameter of a geom::Geometry.
#include <MinimumDiameter.h>
Public Member Functions
~MinimumDiameter ()
MinimumDiameter (const geom::Geometry *newInputGeom)
Compute a minimum diameter for a giver Geometry.
MinimumDiameter (const geom::Geometry *newInputGeom, const bool newIsConvex)
Compute a minimum diameter for a given Geometry, with a hint if the Geometry is convex (e.g. a convex Polygon or LinearRing, or a two-point LineString, or a Point).
double getLength ()
Gets the length of the minimum diameter of the input Geometry.
geom::Coordinate * getWidthCoordinate ()
Gets the geom::Coordinate forming one end of the minimum diameter.
geom::LineString * getSupportingSegment ()
Gets the segment forming the base of the minimum diameter.
geom::LineString * getDiameter ()
Gets a LineString which is a minimum diameter.
geom::Geometry * getMinimumRectangle ()
Static Public Member Functions
static geom::Geometry * getMinimumRectangle (geom::Geometry *geom)
static geom::Geometry * getMinimumDiameter (geom::Geometry *geom)
Private Member Functions
void computeMinimumDiameter ()
void computeWidthConvex (const geom::Geometry *geom)
void computeConvexRingMinDiameter (const geom::CoordinateSequence *pts)
unsigned int findMaxPerpDistance (const geom::CoordinateSequence *pts, geom::LineSegment *seg, unsigned int startIndex)
Static Private Member Functions
static unsigned int getNextIndex (const geom::CoordinateSequence *pts, unsigned int index)
static double computeC (double a, double b, const geom::Coordinate &p)
static geom::LineSegment computeSegmentForLine (double a, double b, double c)
Private Attributes
const geom::Geometry * inputGeom
bool isConvex
geom::CoordinateSequence * convexHullPts
geom::LineSegment * minBaseSeg
geom::Coordinate * minWidthPt
int minPtIndex
double minWidth
Detailed Description
Computes the minimum diameter of a geom::Geometry.
The minimum diameter is defined to be the width of the smallest band that contains the geometry, where a band is a strip of the plane defined by two parallel lines. This can be thought of as the smallest hole that the geometry can be moved through, with a single rotation.
The first step in the algorithm is computing the convex hull of the Geometry. If the input Geometry is known to be convex, a hint can be supplied to avoid this computation.
This class can also be used to compute a line segment representing the minimum diameter, the supporting line segment of the minimum diameter, and a minimum rectangle enclosing the input geometry. This rectangle will have width equal to the minimum diameter, and have one side parallel to the supporting segment.
See also
ConvexHull
Definition at line 65 of file MinimumDiameter.h.
Constructor & Destructor Documentation
geos::algorithm::MinimumDiameter::~MinimumDiameter ()
Definition at line 99 of file MinimumDiameter.cpp.
 {
   delete minBaseSeg;
   delete minWidthPt;
   delete convexHullPts;
 }
geos::algorithm::MinimumDiameter::MinimumDiameter (const geom::Geometry * newInputGeom)
Compute a minimum diameter for a giver Geometry.
Parameters
geom a Geometry
Computes the minimum diameter of a Geometry. The minimum diameter is defined to be the width of the smallest band that contains the geometry, where a band is a strip of the plane defined by two parallel lines. This can be thought of as the smallest hole that the geometry can be moved through, with a single rotation.
The first step in the algorithm is computing the convex hull of the Geometry. If the input Geometry is known to be convex, a hint can be supplied to avoid this computation.
See also
ConvexHull
Version
1.4 Compute a minimum diameter for a giver Geometry.
Parameters
geom a Geometry
Definition at line 68 of file MinimumDiameter.cpp.
 {
   minBaseSeg=new LineSegment();
   minWidthPt=nullptr;
   minPtIndex=0;
   minWidth=0.0;
   inputGeom=newInputGeom;
   isConvex=false;
   convexHullPts=nullptr;
 }
geos::algorithm::MinimumDiameter::MinimumDiameter (const geom::Geometry * newInputGeom, const bool newIsConvex)
Compute a minimum diameter for a given Geometry, with a hint if the Geometry is convex (e.g. a convex Polygon or LinearRing, or a two-point LineString, or a Point).
Parameters
geom a Geometry which is convex
isConvex true if the input geometry is convex
Compute a minimum diameter for a giver Geometry, with a hint if the Geometry is convex (e.g. a convex Polygon or LinearRing, or a two-point LineString, or a Point).
Parameters
geom a Geometry which is convex
isConvex true if the input geometry is convex
Definition at line 89 of file MinimumDiameter.cpp.
 {
   minBaseSeg=new LineSegment();
   minWidthPt=nullptr;
   minWidth=0.0;
   inputGeom=newInputGeom;
   isConvex=newIsConvex;
   convexHullPts=nullptr;
 }
Member Function Documentation
double geos::algorithm::MinimumDiameter::computeC (double a, double b, const geom::Coordinate & p) static private
Definition at line 357 of file MinimumDiameter.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   return a * p.y - b * p.x;
 }
void geos::algorithm::MinimumDiameter::computeConvexRingMinDiameter (const geom::CoordinateSequence * pts) private
Compute the width information for a ring of geom::Coordinates. Leaves the width information in the instance variables.
Parameters
pts
Returns
Compute the width information for a ring of Coordinates. Leaves the width information in the instance variables.
Parameters
pts
Returns
Definition at line 238 of file MinimumDiameter.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   minWidth=DoubleMax;
   unsigned int currMaxIndex=1;
   LineSegment seg;
   // compute the max distance for all segments in the ring, and pick the minimum
   const std::size_t npts=pts->getSize();
   for (std::size_t i=1; i<npts; ++i) {
     seg.p0=pts->getAt(i-1);
     seg.p1=pts->getAt(i);
     currMaxIndex=findMaxPerpDistance(pts, &seg, currMaxIndex);
   }
 }
void geos::algorithm::MinimumDiameter::computeMinimumDiameter () private
Definition at line 169 of file MinimumDiameter.cpp.
References geos::algorithm::ConvexHull::getConvexHull().
 {
   // check if computation is cached
   if (minWidthPt!=nullptr)
     return;
   if (isConvex)
     computeWidthConvex(inputGeom);
   else {
     ConvexHull ch(inputGeom);
     Geometry* convexGeom=ch.getConvexHull();
     computeWidthConvex(convexGeom);
     delete convexGeom;
   }
 }
LineSegment geos::algorithm::MinimumDiameter::computeSegmentForLine (double a, double b, double c) static private
Definition at line 362 of file MinimumDiameter.cpp.
 {
   Coordinate p0;
   Coordinate p1;
   /*
   * Line eqn is ax + by = c
   * Slope is a/b.
   * If slope is steep, use y values as the inputs
   */
   if (fabs(b) > fabs(a) ) {
     p0 = Coordinate(0.0, c/b);
     p1 = Coordinate(1.0, c/b - a/b);
   }
   else {
     p0 = Coordinate(c/a, 0.0);
     p1 = Coordinate(c/a - b/a, 1.0);
   }
   return LineSegment(p0, p1);
 }
void geos::algorithm::MinimumDiameter::computeWidthConvex (const geom::Geometry * geom) private
Definition at line 186 of file MinimumDiameter.cpp.
References geos::geom::LineString::getCoordinates(), geos::geom::Geometry::getCoordinates(), and geos::geom::Polygon::getExteriorRing().
 {
   //System.out.println("Input = " + geom);
   delete convexHullPts;
   if (typeid(*geom)==typeid(Polygon))
   {
     const Polygon* p = dynamic_cast<const Polygon*>(geom);
     convexHullPts=p->getExteriorRing()->getCoordinates();
   }
   else
   {
     convexHullPts=geom->getCoordinates();
   }
   // special cases for lines or points or degenerate rings
   switch(convexHullPts->getSize())
   {
     case 0:
       minWidth=0.0;
       delete minWidthPt;
       minWidthPt=nullptr;
       delete minBaseSeg;
       minBaseSeg=nullptr;
       break;
     case 1:
       minWidth = 0.0;
       delete minWidthPt;
       minWidthPt=new Coordinate(convexHullPts->getAt(0));
       minBaseSeg->p0=convexHullPts->getAt(0);
       minBaseSeg->p1=convexHullPts->getAt(0);
       break;
     case 2:
     case 3:
       minWidth = 0.0;
       delete minWidthPt;
       minWidthPt=new Coordinate(convexHullPts->getAt(0));
       minBaseSeg->p0=convexHullPts->getAt(0);
       minBaseSeg->p1=convexHullPts->getAt(1);
       break;
     default:
       computeConvexRingMinDiameter(convexHullPts);
   }
 }
unsigned int geos::algorithm::MinimumDiameter::findMaxPerpDistance (const geom::CoordinateSequence * pts, geom::LineSegment * seg, unsigned int startIndex) private
Definition at line 254 of file MinimumDiameter.cpp.
References geos::geom::LineSegment::distancePerpendicular(), and geos::geom::CoordinateSequence::getAt().
 {
   double maxPerpDistance=seg->distancePerpendicular(pts->getAt(startIndex));
   double nextPerpDistance = maxPerpDistance;
   unsigned int maxIndex = startIndex;
   unsigned int nextIndex = maxIndex;
   while (nextPerpDistance >= maxPerpDistance) {
     maxPerpDistance = nextPerpDistance;
     maxIndex=nextIndex;
     nextIndex=getNextIndex(pts, maxIndex);
     nextPerpDistance = seg->distancePerpendicular(pts->getAt(nextIndex));
   }
   // found maximum width for this segment - update global min dist if appropriate
   if (maxPerpDistance < minWidth) {
     minPtIndex = maxIndex;
     minWidth = maxPerpDistance;
     delete minWidthPt;
     minWidthPt = new Coordinate(pts->getAt(minPtIndex));
     delete minBaseSeg;
     minBaseSeg = new LineSegment(*seg);
 //      System.out.println(minBaseSeg);
 //      System.out.println(minWidth);
   }
   return maxIndex;
 }
LineString * geos::algorithm::MinimumDiameter::getDiameter ()
Gets a LineString which is a minimum diameter.
Returns
a LineString which is a minimum diameter
Gets a LineString which is a minimum diameter
Returns
a LineString which is a minimum diameter
Definition at line 151 of file MinimumDiameter.cpp.
References geos::geom::CoordinateSequence::add().
Referenced by GEOSMinimumWidth_r(), and getMinimumDiameter().
 {
   computeMinimumDiameter();
   // return empty linestring if no minimum width calculated
   if (minWidthPt==nullptr)
     return inputGeom->getFactory()->createLineString(nullptr);
   Coordinate basePt;
   minBaseSeg->project(*minWidthPt, basePt);
   CoordinateSequence* cl=inputGeom->getFactory()->getCoordinateSequenceFactory()->create();
   cl->add(basePt);
   cl->add(*minWidthPt);
   return inputGeom->getFactory()->createLineString(cl);
 }
double geos::algorithm::MinimumDiameter::getLength ()
Gets the length of the minimum diameter of the input Geometry.
Returns
the length of the minimum diameter
Gets the length of the minimum diameter of the input Geometry
Returns
the length of the minimum diameter
Definition at line 112 of file MinimumDiameter.cpp.
Referenced by geos::operation::buffer::OffsetCurveSetBuilder::isErodedCompletely().
 {
   computeMinimumDiameter();
   return minWidth;
 }
Geometry * geos::algorithm::MinimumDiameter::getMinimumDiameter (geom::Geometry * geom) static
Gets the length of the minimum diameter enclosing a geometry
Parameters
geom the geometry
Returns
the length of the minimum diameter of the geometry
Definition at line 389 of file MinimumDiameter.cpp.
References getDiameter().
 {
   MinimumDiameter md( geom );
   return md.getDiameter();
 }
Geometry * geos::algorithm::MinimumDiameter::getMinimumRectangle ()
Gets the minimum rectangular Polygon which encloses the input geometry. The rectangle has width equal to the minimum diameter, and a longer length. If the convex hill of the input is degenerate (a line or point) a LineString or Point is returned. The minimum rectangle can be used as an extremely generalized representation for the given geometry.
Returns
the minimum rectangle enclosing the input (or a line or point if degenerate)
Definition at line 290 of file MinimumDiameter.cpp.
References geos::geom::CoordinateSequenceFactory::create(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createPolygon(), geos::geom::Geometry::getFactory(), geos::geom::LineSegment::lineIntersection(), and geos::geom::CoordinateSequence::setAt().
Referenced by GEOSMinimumRotatedRectangle_r(), and getMinimumRectangle().
 {
   computeMinimumDiameter();
   if ( !minBaseSeg || !convexHullPts )
   {
     //return empty polygon
     return inputGeom->getFactory()->createPolygon();
   }
   // check if minimum rectangle is degenerate (a point or line segment)
   if (minWidth == 0.0) {
     if (minBaseSeg->p0.equals2D(minBaseSeg->p1)) {
       return inputGeom->getFactory()->createPoint(minBaseSeg->p0);
     }
     return minBaseSeg->toGeometry(*inputGeom->getFactory()).release();
   }
   // deltas for the base segment of the minimum diameter
   double dx = minBaseSeg->p1.x - minBaseSeg->p0.x;
   double dy = minBaseSeg->p1.y - minBaseSeg->p0.y;
   double minPara = DoubleMax;
   double maxPara = -DoubleMax;
   double minPerp = DoubleMax;
   double maxPerp = -DoubleMax;
   // compute maxima and minima of lines parallel and perpendicular to base segment
   std::size_t const n=convexHullPts->getSize();
   for (std::size_t i = 0; i < n; ++i) {
     double paraC = computeC(dx, dy, convexHullPts->getAt(i));
     if (paraC > maxPara) maxPara = paraC;
     if (paraC < minPara) minPara = paraC;
     double perpC = computeC(-dy, dx, convexHullPts->getAt(i));
     if (perpC > maxPerp) maxPerp = perpC;
     if (perpC < minPerp) minPerp = perpC;
   }
   // compute lines along edges of minimum rectangle
   LineSegment maxPerpLine = computeSegmentForLine(-dx, -dy, maxPerp);
   LineSegment minPerpLine = computeSegmentForLine(-dx, -dy, minPerp);
   LineSegment maxParaLine = computeSegmentForLine(-dy, dx, maxPara);
   LineSegment minParaLine = computeSegmentForLine(-dy, dx, minPara);
   // compute vertices of rectangle (where the para/perp max & min lines intersect)
   Coordinate p0, p1, p2, p3;
   maxParaLine.lineIntersection(maxPerpLine, p0);
   minParaLine.lineIntersection(maxPerpLine, p1);
   minParaLine.lineIntersection(minPerpLine, p2);
   maxParaLine.lineIntersection(minPerpLine, p3);
   const CoordinateSequenceFactory *csf =
   inputGeom->getFactory()->getCoordinateSequenceFactory();
   geom::CoordinateSequence *seq = csf->create(5, 2);
   seq->setAt(p0, 0);
   seq->setAt(p1, 1);
   seq->setAt(p2, 2);
   seq->setAt(p3, 3);
   seq->setAt(p0, 4); // close
   LinearRing* shell = inputGeom->getFactory()->createLinearRing( seq );
   return inputGeom->getFactory()->createPolygon( shell, nullptr );
 }
Geometry * geos::algorithm::MinimumDiameter::getMinimumRectangle (geom::Geometry * geom) static
Gets the minimum rectangle enclosing a geometry.
Parameters
geom the geometry
Returns
the minimum rectangle enclosing the geometry
Definition at line 383 of file MinimumDiameter.cpp.
References getMinimumRectangle().
 {
   MinimumDiameter md( geom );
   return md.getMinimumRectangle();
 }
unsigned int geos::algorithm::MinimumDiameter::getNextIndex (const geom::CoordinateSequence * pts, unsigned int index) static private
Definition at line 283 of file MinimumDiameter.cpp.
References geos::geom::CoordinateSequence::getSize().
 {
   if (++index >= pts->getSize()) index = 0;
   return index;
 }
LineString * geos::algorithm::MinimumDiameter::getSupportingSegment ()
Gets the segment forming the base of the minimum diameter.
Returns
the segment forming the base of the minimum diameter
Gets the segment forming the base of the minimum diameter
Returns
the segment forming the base of the minimum diameter
Definition at line 136 of file MinimumDiameter.cpp.
References geos::geom::CoordinateSequence::add(), geos::geom::CoordinateSequenceFactory::create(), geos::geom::GeometryFactory::createLineString(), and geos::geom::GeometryFactory::getCoordinateSequenceFactory().
{
   computeMinimumDiameter();
   const GeometryFactory *fact = inputGeom->getFactory();
   CoordinateSequence* cl=fact->getCoordinateSequenceFactory()->create();
   cl->add(minBaseSeg->p0);
   cl->add(minBaseSeg->p1);
   return fact->createLineString(cl);
 }
Coordinate * geos::algorithm::MinimumDiameter::getWidthCoordinate ()
Gets the geom::Coordinate forming one end of the minimum diameter.
Returns
a coordinate forming one end of the minimum diameter
Gets the Coordinate forming one end of the minimum diameter
Returns
a coordinate forming one end of the minimum diameter
Definition at line 124 of file MinimumDiameter.cpp.
 {
   computeMinimumDiameter();
   return minWidthPt;
 }
Member Data Documentation
geom::CoordinateSequence* geos::algorithm::MinimumDiameter::convexHullPts private
Definition at line 70 of file MinimumDiameter.h.
const geom::Geometry* geos::algorithm::MinimumDiameter::inputGeom private
Definition at line 67 of file MinimumDiameter.h.
bool geos::algorithm::MinimumDiameter::isConvex private
Definition at line 68 of file MinimumDiameter.h.
geom::LineSegment* geos::algorithm::MinimumDiameter::minBaseSeg private
Definition at line 72 of file MinimumDiameter.h.
int geos::algorithm::MinimumDiameter::minPtIndex private
Definition at line 74 of file MinimumDiameter.h.
double geos::algorithm::MinimumDiameter::minWidth private
Definition at line 75 of file MinimumDiameter.h.
geom::Coordinate* geos::algorithm::MinimumDiameter::minWidthPt private
Definition at line 73 of file MinimumDiameter.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/MinimumDiameter.h
/home/vicky/potree/geos/vicky/src/algorithm/MinimumDiameter.cpp