GEOS: geos::precision::CommonCoordinateFilter Class Reference
geos::precision::CommonCoordinateFilter Class Reference
Public Member Functions
void filter_rw (geom::Coordinate *coord) const override
void filter_ro (const geom::Coordinate *coord) override
void getCommonCoordinate (geom::Coordinate &c)
Private Attributes
CommonBits commonBitsX
CommonBits commonBitsY
Detailed Description
Definition at line 66 of file CommonBitsRemover.cpp.
Member Function Documentation
void geos::precision::CommonCoordinateFilter::filter_ro (const geom::Coordinate *) inline override virtual
Performs an operation with coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented from geos::geom::CoordinateFilter.
Definition at line 79 of file CommonBitsRemover.cpp.
References geos::precision::CommonBits::add(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
   {
     commonBitsX.add(coord->x);
     commonBitsY.add(coord->y);
   }
void geos::precision::CommonCoordinateFilter::filter_rw (geom::Coordinate *) const inline override virtual
Performs an operation on coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented from geos::geom::CoordinateFilter.
Definition at line 72 of file CommonBitsRemover.cpp.
References geos::ignore_unused_variable_warning().
   {
         // CommonCoordinateFilter is a read-only filter
         ::geos::ignore_unused_variable_warning(coord);
     assert(0);
   }
void geos::precision::CommonCoordinateFilter::getCommonCoordinate (geom::Coordinate & c) inline
Definition at line 85 of file CommonBitsRemover.cpp.
References geos::precision::CommonBits::getCommon().
   {
     c=Coordinate(commonBitsX.getCommon(),
       commonBitsY.getCommon());
   }
Member Data Documentation
CommonBits geos::precision::CommonCoordinateFilter::commonBitsX private
Definition at line 68 of file CommonBitsRemover.cpp.
CommonBits geos::precision::CommonCoordinateFilter::commonBitsY private
Definition at line 69 of file CommonBitsRemover.cpp.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/precision/CommonBitsRemover.cpp