GEOS: geos::geomgraph::EdgeNodingValidator Class Reference
geos::geomgraph::EdgeNodingValidator Class Reference
Validates that a collection of SegmentStrings is correctly noded.
#include <EdgeNodingValidator.h>
Public Member Functions
EdgeNodingValidator (std::vector< Edge * > &edges)
~EdgeNodingValidator ()
void checkValid ()
Static Public Member Functions
static void checkValid (std::vector< Edge * > &edges)
Checks whether the supplied Edges are correctly noded.
Private Member Functions
std::vector< noding::SegmentString * > & toSegmentStrings (std::vector< Edge * > &edges)
Private Attributes
std::vector< noding::SegmentString * > segStr
std::vector< geom::CoordinateSequence * > newCoordSeq
noding::FastNodingValidator nv
Detailed Description
Validates that a collection of SegmentStrings is correctly noded.
Throws an appropriate exception if an noding error is found.
Definition at line 57 of file EdgeNodingValidator.h.
Constructor & Destructor Documentation
geos::geomgraph::EdgeNodingValidator::EdgeNodingValidator (std::vector< Edge * > & edges) inline
Definition at line 95 of file EdgeNodingValidator.h.
     :
     segStr(),
     newCoordSeq(),
     nv(toSegmentStrings(edges))
   {}
geos::geomgraph::EdgeNodingValidator::~EdgeNodingValidator ()
Definition at line 47 of file EdgeNodingValidator.cpp.
 {
   for (SegmentString::NonConstVect::iterator
       i=segStr.begin(), e=segStr.end();
       i != e;
       ++i)
   {
     delete *i;
   }
   for(size_t i=0, n=newCoordSeq.size(); i<n; ++i)
     delete newCoordSeq[i];
 }
Member Function Documentation
static void geos::geomgraph::EdgeNodingValidator::checkValid (std::vector< Edge * > & edges) inline static
Checks whether the supplied Edges are correctly noded.
Throws a TopologyException if they are not.
Parameters
edges a collection of Edges.
Exceptions
TopologyException if the SegmentStrings are not correctly noded
Definition at line 89 of file EdgeNodingValidator.h.
References checkValid().
Referenced by checkValid().
         {
                 EdgeNodingValidator validator(edges);
                 validator.checkValid();
         }
void geos::geomgraph::EdgeNodingValidator::checkValid () inline
Definition at line 104 of file EdgeNodingValidator.h.
References geos::noding::FastNodingValidator::checkValid().
 { nv.checkValid(); }
vector< SegmentString * > & geos::geomgraph::EdgeNodingValidator::toSegmentStrings (std::vector< Edge * > & edges) private
Definition at line 35 of file EdgeNodingValidator.cpp.
References geos::geom::CoordinateSequence::clone(), and geos::geomgraph::Edge::getCoordinates().
 {
   // convert Edges to SegmentStrings
   for(size_t i=0, n=edges.size(); i<n; ++i) {
     Edge *e=edges[i];
     CoordinateSequence* cs=e->getCoordinates()->clone();
     newCoordSeq.push_back(cs);
     segStr.push_back(new BasicSegmentString(cs, e));
   }
   return segStr;
 }
Member Data Documentation
std::vector<geom::CoordinateSequence*> geos::geomgraph::EdgeNodingValidator::newCoordSeq private
Definition at line 72 of file EdgeNodingValidator.h.
noding::FastNodingValidator geos::geomgraph::EdgeNodingValidator::nv private
Definition at line 74 of file EdgeNodingValidator.h.
std::vector<noding::SegmentString*> geos::geomgraph::EdgeNodingValidator::segStr private
Definition at line 66 of file EdgeNodingValidator.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/EdgeNodingValidator.h
/home/vicky/potree/geos/vicky/src/geomgraph/EdgeNodingValidator.cpp