GEOS: geos::operation::overlay::snap::LineStringSnapper Class Reference
geos::operation::overlay::snap::LineStringSnapper Class Reference
Snaps the vertices and segments of a LineString to a set of target snap vertices.
#include <LineStringSnapper.h>
Public Member Functions
LineStringSnapper (const geom::Coordinate::Vect &nSrcPts, double nSnapTol)
std::unique_ptr< geom::Coordinate::Vect > snapTo (const geom::Coordinate::ConstVect &snapPts)
void setAllowSnappingToSourceVertices (bool allow)
Private Member Functions
void snapVertices (geom::CoordinateList &srcCoords, const geom::Coordinate::ConstVect &snapPts)
geom::Coordinate::ConstVect::const_iterator findSnapForVertex (const geom::Coordinate &pt, const geom::Coordinate::ConstVect &snapPts)
void snapSegments (geom::CoordinateList &srcCoords, const geom::Coordinate::ConstVect &snapPts)
Snap segments of the source to nearby snap vertices.
geom::CoordinateList::iterator findSegmentToSnap (const geom::Coordinate &snapPt, geom::CoordinateList::iterator from, geom::CoordinateList::iterator too_far)
Finds a src segment which snaps to (is close to) the given snap point.
geom::CoordinateList::iterator findVertexToSnap (const geom::Coordinate &snapPt, geom::CoordinateList::iterator from, geom::CoordinateList::iterator too_far)
LineStringSnapper (const LineStringSnapper &other)=delete
LineStringSnapper & operator= (const LineStringSnapper &rhs)=delete
Private Attributes
const geom::Coordinate::Vect & srcPts
double snapTolerance
bool allowSnappingToSourceVertices
bool isClosed
Detailed Description
Snaps the vertices and segments of a LineString to a set of target snap vertices.
A snapping distance tolerance is used to control where snapping is performed.
Definition at line 51 of file LineStringSnapper.h.
Constructor & Destructor Documentation
geos::operation::overlay::snap::LineStringSnapper::LineStringSnapper (const geom::Coordinate::Vect & nSrcPts, double nSnapTol) inline
Creates a new snapper using the given points as source points to be snapped.
Parameters
nSrcPts the points to snap
nSnapTolerance the snap tolerance to use
Definition at line 62 of file LineStringSnapper.h.
     :
     srcPts(nSrcPts),
     snapTolerance(nSnapTol),
     allowSnappingToSourceVertices(false)
   {
     size_t s = srcPts.size();
     isClosed = s < 2 ? false : srcPts[0].equals2D(srcPts[s-1]);
   }
geos::operation::overlay::snap::LineStringSnapper::LineStringSnapper (const LineStringSnapper & other) private delete
Member Function Documentation
CoordinateList::iterator geos::operation::overlay::snap::LineStringSnapper::findSegmentToSnap (const geom::Coordinate & snapPt, geom::CoordinateList::iterator from, geom::CoordinateList::iterator too_far) private
Finds a src segment which snaps to (is close to) the given snap point.
Only a single segment is selected for snapping. This prevents multiple segments snapping to the same snap vertex, which would almost certainly cause invalid geometry to be created. (The heuristic approach to snapping used here is really only appropriate when snap pts snap to a unique spot on the src geometry.)
Also, if the snap vertex occurs as a vertex in the src coordinate list, no snapping is performed (may be changed using setAllowSnappingToSourceVertices).
Parameters
from an iterator to first point of first segment to be checked
too_far an iterator to last point of last segment to be checked
Returns
an iterator to the snapped segment or too_far if no segment needs snapping (either none within snapTol distance, or one found on the snapPt)
Check if the snap pt is equal to one of the segment endpoints.
If the snap pt is already in the src list, don't snap at all (unless allowSnappingToSourceVertices is set to true)
Definition at line 381 of file LineStringSnapper.cpp.
References geos::geom::LineSegment::distance(), geos::geom::Coordinate::equals2D(), geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   LineSegment seg;
   double minDist = snapTolerance; // make sure the first closer then
                                   // snapTolerance is accepted
   CoordinateList::iterator match=too_far;
   // TODO: use std::find_if
   for ( ; from != too_far; ++from)
   {
     seg.p0 = *from;
     CoordinateList::iterator to = from;
     ++to;
     seg.p1 = *to;
 #if GEOS_DEBUG
 cerr << " Checking segment " << seg << endl;
 #endif
     if ( seg.p0.equals2D(snapPt) || seg.p1.equals2D(snapPt) )
     {
       if (allowSnappingToSourceVertices) {
 #if GEOS_DEBUG
 cerr << "   snap point matches a segment endpoint, checking next segment"
      << endl;
 #endif
         continue;
       } else {
 #if GEOS_DEBUG
 cerr << "   snap point matches a segment endpoint, giving up seek" << endl;
 #endif
         return too_far;
       }
     }
     double dist = seg.distance(snapPt);
     if ( dist >= minDist) {
 #if GEOS_DEBUG
 cerr << "   snap point distance " << dist
      << " not smaller than tolerance "
      << snapTolerance << " or previous closest "
      << minDist << endl;
 #endif
       continue;
     }
 #if GEOS_DEBUG
     cerr << "   snap point distance " << dist << " within tolerance "
          << snapTolerance << " and closer than previous candidate "
          << minDist << endl;
 #endif
     if ( dist == 0.0 ) return from; // can't find any closer
     match = from;
     minDist = dist;
   }
   return match;
 }
Coordinate::ConstVect::const_iterator geos::operation::overlay::snap::LineStringSnapper::findSnapForVertex (const geom::Coordinate & pt, const geom::Coordinate::ConstVect & snapPts) private
Definition at line 178 of file LineStringSnapper.cpp.
References geos::geom::Coordinate::distance(), geos::geom::CoordinateList::end(), and geos::geom::Coordinate::equals2D().
 {
   Coordinate::ConstVect::const_iterator end = snapPts.end();
   Coordinate::ConstVect::const_iterator candidate = end;
   double minDist = snapTolerance;
   // TODO: use std::find_if
   for ( Coordinate::ConstVect::const_iterator
       it=snapPts.begin();
       it != end;
       ++it)
   {
     assert(*it);
     const Coordinate& snapPt = *(*it);
     if ( snapPt.equals2D(pt) )
     {
 #if GEOS_DEBUG
 cerr << " points are equal, returning not-found " << endl;
 #endif
       return end;
     }
     double dist = snapPt.distance(pt);
 #if GEOS_DEBUG
 cerr << " distance from snap point " << snapPt << ": " << dist << endl;
 #endif
     if ( dist < minDist )
     {
       minDist = dist;
       candidate = it;
     }
   }
 #if GEOS_DEBUG
   if ( candidate == end ) {
 cerr << " no snap point within distance, returning not-found" << endl;
   }
 #endif
   return candidate;
 }
CoordinateList::iterator geos::operation::overlay::snap::LineStringSnapper::findVertexToSnap (const geom::Coordinate & snapPt, geom::CoordinateList::iterator from, geom::CoordinateList::iterator too_far) private
Definition at line 67 of file LineStringSnapper.cpp.
References geos::geom::Coordinate::distance().
 {
   double minDist = snapTolerance; // make sure the first closer then
                                   // snapTolerance is accepted
   CoordinateList::iterator match=too_far;
   for ( ; from != too_far; ++from)
   {
     Coordinate& c0 = *from;
 #if GEOS_DEBUG
 cerr << " Checking vertex " << c0 << endl;
 #endif
     double dist = c0.distance(snapPt);
     if ( dist >= minDist) {
 #if GEOS_DEBUG
 cerr << "   snap point distance " << dist
      << " not smaller than tolerance "
      << snapTolerance << " or previous closest "
      << minDist << endl;
 #endif
       continue;
     }
 #if GEOS_DEBUG
     cerr << "   snap point distance " << dist << " within tolerance "
          << snapTolerance << " and closer than previous candidate "
          << minDist << endl;
 #endif
     if ( dist == 0.0 ) return from; // can't find any closer
     match = from;
     minDist = dist;
   }
   return match;
 }
LineStringSnapper& geos::operation::overlay::snap::LineStringSnapper::operator= (const LineStringSnapper & rhs) private delete
void geos::operation::overlay::snap::LineStringSnapper::setAllowSnappingToSourceVertices (bool allow) inline
Definition at line 76 of file LineStringSnapper.h.
{
     allowSnappingToSourceVertices = allow;
   }
void geos::operation::overlay::snap::LineStringSnapper::snapSegments (geom::CoordinateList & srcCoords, const geom::Coordinate::ConstVect & snapPts) private
Snap segments of the source to nearby snap vertices.
Source segments are "cracked" at a snap vertex. A single input segment may be snapped several times to different snap vertices.
For each distinct snap vertex, at most one source segment is snapped to. This prevents "cracking" multiple segments at the same point, which would likely cause topology collapse when being used on polygonal linework.
Parameters
srcCoords the coordinates of the source linestring to be snapped the object will be modified (coords snapped)
snapPts the target snap vertices
Definition at line 226 of file LineStringSnapper.cpp.
References geos::geom::CoordinateList::begin(), geos::geom::LineSegment::distance(), geos::geom::CoordinateList::empty(), geos::geom::CoordinateList::end(), GEOS_CHECK_FOR_INTERRUPTS, geos::geom::CoordinateList::insert(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and geos::geom::LineSegment::projectionFactor().
 {
   // nothing to do if there are no source coords..
   if ( srcCoords.empty() ) return;
   GEOS_CHECK_FOR_INTERRUPTS();
 #if GEOS_DEBUG
 cerr << "Snapping segments of: " << srcCoords << endl;
 #endif
   for ( Coordinate::ConstVect::const_iterator
       it=snapPts.begin(), end=snapPts.end();
       it != end;
       ++it)
   {
     assert(*it);
     const Coordinate& snapPt = *(*it);
 #if GEOS_DEBUG
 cerr << "Checking for a segment to snap to snapPt " << snapPt << endl;
 #endif
     CoordinateList::iterator too_far = srcCoords.end(); --too_far;
     CoordinateList::iterator segpos =
       findSegmentToSnap(snapPt, srcCoords.begin(), too_far);
     if ( segpos == too_far)
     {
 #if GEOS_DEBUG
 cerr << " No segment to snap" << endl;
 #endif
       continue;
     }
     /* Check if the snap point falls outside of the segment */
     // If the snap point is outside, this means that an endpoint
     // was not snap where it should have been
     // so what we should do is re-snap the endpoint to this
     // snapPt and then snap the closest between this and
     // previous (for pf < 0.0) or next (for pf > 1.0) segment
     // to the old endpoint.
     //     --strk May 2013
     //
     // TODO: simplify this code, make more readable
     //
     CoordinateList::iterator to = segpos; ++to;
     LineSegment seg(*segpos, *to);
     double pf = seg.projectionFactor(snapPt);
     if ( pf >= 1.0 ) {
 #if GEOS_DEBUG
       cerr << " Segment to be snapped is closer on his end point" << endl;
 #endif
       Coordinate newSnapPt = seg.p1;
       *to = seg.p1 = snapPt;
       // now snap from-to (segpos) or to-next (segpos++) to newSnapPt
       if ( to == too_far ) {
         if ( isClosed ) {
 #if GEOS_DEBUG
           cerr << " His end point is the last one, but is closed " << endl;
 #endif
           *(srcCoords.begin()) = snapPt; // sync to start point
           to = srcCoords.begin();
         } else {
 #if GEOS_DEBUG
           cerr << " His end point is the last one, inserting " << newSnapPt << " before it" << endl;
 #endif
           srcCoords.insert(to, newSnapPt);
           continue;
         }
       }
       ++to;
       LineSegment nextSeg(seg.p1, *to);
       if ( nextSeg.distance(newSnapPt) < seg.distance(newSnapPt) ) {
 #if GEOS_DEBUG
         cerr << " Next segment closer, inserting " << newSnapPt << " into " << nextSeg << endl;
 #endif
         // insert into next segment
         srcCoords.insert(to, newSnapPt);
       } else {
 #if GEOS_DEBUG
         cerr << " This segment closer, inserting " << newSnapPt << " into " << seg << endl;
 #endif
         // insert must happen one-past first point (before next point)
         ++segpos;
         srcCoords.insert(segpos, newSnapPt);
       }
     }
     else if ( pf <= 0.0 ) {
 #if GEOS_DEBUG
       cerr << " Segment to be snapped is closer on his start point" << endl;
 #endif
       Coordinate newSnapPt = seg.p0;
       *segpos = seg.p0 = snapPt;
       // now snap prev-from (--segpos) or from-to (segpos) to newSnapPt
       if ( segpos == srcCoords.begin() ) {
         if ( isClosed ) {
 #if GEOS_DEBUG
           cerr << " His start point is the first one, but is closed " << endl;
 #endif
           segpos = srcCoords.end(); --segpos;
           *segpos = snapPt; // sync to end point
         } else {
 #if GEOS_DEBUG
           cerr << " His start point is the first one, inserting " << newSnapPt << " before it" << endl;
 #endif
           ++segpos;
           srcCoords.insert(segpos, newSnapPt);
           continue;
         }
       }
 #if GEOS_DEBUG
 cerr << " Before seg-snapping, srcCoors are: " << srcCoords << endl;
 #endif
       --segpos;
       LineSegment prevSeg(*segpos, seg.p0);
       if ( prevSeg.distance(newSnapPt) < seg.distance(newSnapPt) ) {
 #if GEOS_DEBUG
         cerr << " Prev segment closer, inserting " << newSnapPt << " into "
              << prevSeg << endl;
 #endif
         // insert into prev segment
         ++segpos;
         srcCoords.insert(segpos, newSnapPt);
       } else {
 #if GEOS_DEBUG
         cerr << " This segment closer, inserting " << newSnapPt << " into " << seg << endl;
 #endif
         // insert must happen one-past first point (before next point)
         srcCoords.insert(to, newSnapPt);
       }
     }
     else {
       //assert(pf != 0.0);
 #if GEOS_DEBUG
 cerr << " Segment to be snapped found, projection factor is " << pf << ", inserting point" << endl;
 #endif
       // insert must happen one-past first point (before next point)
       ++segpos;
       srcCoords.insert(segpos, snapPt);
     }
   }
 #if GEOS_DEBUG
 cerr << " After segment snapping, srcCoors are: " << srcCoords << endl;
 #endif
 }
std::unique_ptr< Coordinate::Vect > geos::operation::overlay::snap::LineStringSnapper::snapTo (const geom::Coordinate::ConstVect & snapPts)
Definition at line 55 of file LineStringSnapper.cpp.
References geos::geom::CoordinateList::toCoordinateArray().
 {
   geom::CoordinateList coordList(srcPts);
   snapVertices(coordList, snapPts);
   snapSegments(coordList, snapPts);
   return coordList.toCoordinateArray();
 }
void geos::operation::overlay::snap::LineStringSnapper::snapVertices (geom::CoordinateList & srcCoords, const geom::Coordinate::ConstVect & snapPts) private
Definition at line 114 of file LineStringSnapper.cpp.
References geos::geom::CoordinateList::begin(), geos::geom::CoordinateList::empty(), geos::geom::CoordinateList::end(), and GEOS_CHECK_FOR_INTERRUPTS.
 {
   // nothing to do if there are no source coords..
   if ( srcCoords.empty() ) return;
 #if GEOS_DEBUG
 cerr << "Snapping vertices of: " << srcCoords << endl;
 #endif
   for ( Coordinate::ConstVect::const_iterator
       it=snapPts.begin(), end=snapPts.end();
       it != end;
       ++it)
   {
       GEOS_CHECK_FOR_INTERRUPTS();
     assert(*it);
     const Coordinate& snapPt = *(*it);
 #if GEOS_DEBUG
 cerr << "Checking for a vertex to snap to snapPt " << snapPt << endl;
 #endif
     CoordinateList::iterator too_far = srcCoords.end();
     if ( isClosed ) --too_far;
     CoordinateList::iterator vertpos =
       findVertexToSnap(snapPt, srcCoords.begin(), too_far);
     if ( vertpos == too_far)
     {
 #if GEOS_DEBUG
 cerr << " No vertex to snap" << endl;
 #endif
       continue;
     }
 #if GEOS_DEBUG
 cerr << " Vertex to be snapped found, snapping" << endl;
 #endif
     *vertpos = snapPt;
     // keep final closing point in synch (rings only)
     if (vertpos == srcCoords.begin() && isClosed)
     {
       vertpos = srcCoords.end(); --vertpos;
 #if GEOS_DEBUG
 cerr << " Snapped vertex was first in a closed line, also snapping last" << endl;
 #endif
       *vertpos = snapPt;
     }
 #if GEOS_DEBUG
 cerr << " After snapping of vertex " << snapPt << ", srcCoors are: " << srcCoords << endl;
 #endif
   }
 #if GEOS_DEBUG
 cerr << " After vertices snapping, srcCoors are: " << srcCoords << endl;
 #endif
 }
Member Data Documentation
bool geos::operation::overlay::snap::LineStringSnapper::allowSnappingToSourceVertices private
Definition at line 86 of file LineStringSnapper.h.
bool geos::operation::overlay::snap::LineStringSnapper::isClosed private
Definition at line 87 of file LineStringSnapper.h.
double geos::operation::overlay::snap::LineStringSnapper::snapTolerance private
Definition at line 84 of file LineStringSnapper.h.
const geom::Coordinate::Vect& geos::operation::overlay::snap::LineStringSnapper::srcPts private
Definition at line 82 of file LineStringSnapper.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/snap/LineStringSnapper.h
/home/vicky/potree/geos/vicky/src/operation/overlay/snap/LineStringSnapper.cpp