GEOS: geos::operation::buffer::OffsetSegmentGenerator Class Reference
geos::operation::buffer::OffsetSegmentGenerator Class Reference
#include <OffsetSegmentGenerator.h>
Public Member Functions
OffsetSegmentGenerator (const geom::PrecisionModel *newPrecisionModel, const BufferParameters &bufParams, double distance)
bool hasNarrowConcaveAngle () const
void initSideSegments (const geom::Coordinate &nS1, const geom::Coordinate &nS2, int nSide)
void getCoordinates (std::vector< geom::CoordinateSequence * > &to)
Get coordinates by taking ownership of them.
void closeRing ()
void createCircle (const geom::Coordinate &p, double distance)
Adds a CW circle around a point.
void createSquare (const geom::Coordinate &p, double distance)
Adds a CW square around a point.
void addFirstSegment ()
Add first offset point.
void addLastSegment ()
Add last offset point.
void addNextSegment (const geom::Coordinate &p, bool addStartPoint)
void addLineEndCap (const geom::Coordinate &p0, const geom::Coordinate &p1)
Add an end cap around point p1, terminating a line segment coming from p0.
void addSegments (const geom::CoordinateSequence &pts, bool isForward)
Private Member Functions
void addCollinear (bool addStartPoint)
void addMitreJoin (const geom::Coordinate &p, const geom::LineSegment &offset0, const geom::LineSegment &offset1, double distance)
The mitre will be beveled if it exceeds the mitre ratio limit.
void addLimitedMitreJoin (const geom::LineSegment &offset0, const geom::LineSegment &offset1, double distance, double mitreLimit)
Adds a limited mitre join connecting the two reflex offset segments.
void addBevelJoin (const geom::LineSegment &offset0, const geom::LineSegment &offset1)
Adds a bevel join connecting the two offset segments around a reflex corner.
void init (double newDistance)
void addOutsideTurn (int orientation, bool addStartPoint)
Adds the offset points for an outside (convex) turn.
void addInsideTurn (int orientation, bool addStartPoint)
Adds the offset points for an inside (concave) turn.
void computeOffsetSegment (const geom::LineSegment &seg, int side, double distance, geom::LineSegment &offset)
Compute an offset segment for an input segment on a given side and at a given distance.
void addFillet (const geom::Coordinate &p, const geom::Coordinate &p0, const geom::Coordinate &p1, int direction, double radius)
void addFillet (const geom::Coordinate &p, double startAngle, double endAngle, int direction, double radius)
OffsetSegmentGenerator (const OffsetSegmentGenerator &)
void operator= (const OffsetSegmentGenerator &)
Private Attributes
double maxCurveSegmentError
the max error of approximation (distance) between a quad segment and the true fillet curve
double filletAngleQuantum
The angle quantum with which to approximate a fillet curve (based on the input # of quadrant segments)
int closingSegLengthFactor
OffsetSegmentString segList
Owned by this object, destroyed by dtor.
double distance
const geom::PrecisionModel * precisionModel
const BufferParameters & bufParams
algorithm::LineIntersector li
geom::Coordinate s0
geom::Coordinate s1
geom::Coordinate s2
geom::LineSegment seg0
geom::LineSegment seg1
geom::LineSegment offset0
geom::LineSegment offset1
int side
bool _hasNarrowConcaveAngle
int endCapIndex
Static Private Attributes
static const double OFFSET_SEGMENT_SEPARATION_FACTOR = 1.0E-3
static const double INSIDE_TURN_VERTEX_SNAP_DISTANCE_FACTOR = 1.0E-3
static const double CURVE_VERTEX_SNAP_DISTANCE_FACTOR = 1.0E-6
static const int MAX_CLOSING_SEG_LEN_FACTOR = 80
static const double PI = 3.14159265358979
static const double SIMPLIFY_FACTOR = 100.0
Detailed Description
Generates segments which form an offset curve. Supports all end cap and join options provided for buffering. Implements various heuristics to produce smoother, simpler curves which are still within a reasonable tolerance of the true curve.
Author
Martin Davis
Definition at line 61 of file OffsetSegmentGenerator.h.
Constructor & Destructor Documentation
geos::operation::buffer::OffsetSegmentGenerator::OffsetSegmentGenerator (const geom::PrecisionModel * newPrecisionModel, const BufferParameters & bufParams, double distance)
Non-round joins cause issues with short closing segments, so don't use them. In any case, non-round joins only really make sense for relatively small buffer distances.
Definition at line 60 of file OffsetSegmentGenerator.cpp.
References bufParams, closingSegLengthFactor, distance, filletAngleQuantum, geos::operation::buffer::BufferParameters::getJoinStyle(), geos::operation::buffer::BufferParameters::getQuadrantSegments(), init(), geos::operation::buffer::BufferParameters::JOIN_ROUND, MAX_CLOSING_SEG_LEN_FACTOR, and PI.
     :
     maxCurveSegmentError(0.0),
     closingSegLengthFactor(1),
     segList(),
     distance(dist),
     precisionModel(newPrecisionModel),
     bufParams(nBufParams),
     li(),
     s0(),
     s1(),
     s2(),
     seg0(),
     seg1(),
     offset0(),
     offset1(),
     side(0),
     _hasNarrowConcaveAngle(false),
     endCapIndex(0)
 {
   // compute intersections in full precision, to provide accuracy
   // the points are rounded as they are inserted into the curve line
   filletAngleQuantum = PI / 2.0 / bufParams.getQuadrantSegments();
   if (bufParams.getQuadrantSegments() >= 8
        && bufParams.getJoinStyle() == BufferParameters::JOIN_ROUND)
   {
     closingSegLengthFactor = MAX_CLOSING_SEG_LEN_FACTOR;
   }
   init(distance);
 }
geos::operation::buffer::OffsetSegmentGenerator::OffsetSegmentGenerator (const OffsetSegmentGenerator &) private
Member Function Documentation
void geos::operation::buffer::OffsetSegmentGenerator::addBevelJoin (const geom::LineSegment & offset0, const geom::LineSegment & offset1) private
Adds a bevel join connecting the two offset segments around a reflex corner.
Parameters
offset0 the first offset segment
offset1 the second offset segment
Definition at line 591 of file OffsetSegmentGenerator.cpp.
References geos::operation::buffer::OffsetSegmentString::addPt(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and segList.
Referenced by addOutsideTurn().
 {
   segList.addPt(offset0.p1);
   segList.addPt(offset1.p0);
 }
void geos::operation::buffer::OffsetSegmentGenerator::addCollinear (bool addStartPoint) private
This test could probably be done more efficiently, but the situation of exact collinearity should be fairly rare.
if numInt is<2, the lines are parallel and in the same direction. In this case the point can be ignored, since the offset lines will also be parallel.
Segments are collinear but reversing. Add an "end-cap" fillet all the way around to other direction
This case should ONLY happen for LineStrings, so the orientation is always CW (Polygons can never have two consecutive segments which are parallel but reversed, because that would be a self intersection).
Definition at line 319 of file OffsetSegmentGenerator.cpp.
References addFillet(), geos::operation::buffer::OffsetSegmentString::addPt(), bufParams, geos::algorithm::LineIntersector::computeIntersection(), distance, geos::algorithm::LineIntersector::getIntersectionNum(), geos::operation::buffer::BufferParameters::getJoinStyle(), geos::operation::buffer::BufferParameters::JOIN_BEVEL, geos::operation::buffer::BufferParameters::JOIN_MITRE, li, offset0, offset1, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, s0, s1, s2, and segList.
Referenced by addNextSegment().
 {
   li.computeIntersection(s0,s1,s1,s2);
   int numInt=li.getIntersectionNum();
   if (numInt>= 2)
   {
     if (  bufParams.getJoinStyle() == BufferParameters::JOIN_BEVEL
        || bufParams.getJoinStyle() == BufferParameters::JOIN_MITRE)
     {
       if (addStartPoint) segList.addPt(offset0.p1);
       segList.addPt(offset1.p0);
     }
     else
     {
       addFillet(s1, offset0.p1, offset1.p0,
           CGAlgorithms::CLOCKWISE, distance);
     }
   }
 }
void geos::operation::buffer::OffsetSegmentGenerator::addFillet (const geom::Coordinate & p, const geom::Coordinate & p0, const geom::Coordinate & p1, int direction, double radius) private
Adds points for a circular fillet around a reflex corner.
Adds the start and end points
Parameters
p base point of curve
p0 start point of fillet curve
p1 endpoint of fillet curve
direction the orientation of the fillet
radius the radius of the fillet
Definition at line 242 of file OffsetSegmentGenerator.cpp.
References geos::operation::buffer::OffsetSegmentString::addPt(), PI, segList, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by addCollinear(), addLineEndCap(), addOutsideTurn(), and createCircle().
 {
   double dx0 = p0.x - p.x;
   double dy0 = p0.y - p.y;
   double startAngle = atan2(dy0, dx0);
   double dx1 = p1.x - p.x;
   double dy1 = p1.y - p.y;
   double endAngle = atan2(dy1, dx1);
   if (direction == CGAlgorithms::CLOCKWISE) {
     if (startAngle <= endAngle) startAngle += 2.0 * PI;
   }
   else {    // direction==COUNTERCLOCKWISE
     if (startAngle >= endAngle) startAngle -= 2.0 * PI;
   }
   segList.addPt(p0);
   addFillet(p, startAngle, endAngle, direction, radius);
   segList.addPt(p1);
 }
void geos::operation::buffer::OffsetSegmentGenerator::addFillet (const geom::Coordinate & p, double startAngle, double endAngle, int direction, double radius) private
Adds points for a circular fillet arc between two specified angles.
The start and end point for the fillet are not added - the caller must add them if required.
Parameters
direction is -1 for a CW angle, 1 for a CCW angle
radius the radius of the fillet
Definition at line 266 of file OffsetSegmentGenerator.cpp.
References geos::operation::buffer::OffsetSegmentString::addPt(), filletAngleQuantum, segList, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   int directionFactor = direction == CGAlgorithms::CLOCKWISE ? -1 : 1;
   double totalAngle = fabs(startAngle - endAngle);
   int nSegs = (int) (totalAngle / filletAngleQuantum + 0.5);
   // no segments because angle is less than increment-nothing to do!
   if (nSegs<1) return;
   double initAngle, currAngleInc;
   // choose angle increment so that each segment has equal length
   initAngle = 0.0;
   currAngleInc = totalAngle / nSegs;
   double currAngle = initAngle;
   Coordinate pt;
   while (currAngle < totalAngle) {
     double angle = startAngle + directionFactor * currAngle;
     pt.x = p.x + radius * cos(angle);
     pt.y = p.y + radius * sin(angle);
     segList.addPt(pt);
     currAngle += currAngleInc;
   }
 }
void geos::operation::buffer::OffsetSegmentGenerator::addFirstSegment () inline
Add first offset point.
Definition at line 118 of file OffsetSegmentGenerator.h.
Referenced by geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve().
   {
     segList.addPt(offset1.p0);
   }
void geos::operation::buffer::OffsetSegmentGenerator::addInsideTurn (int orientation, bool addStartPoint) private
Adds the offset points for an inside (concave) turn.
Parameters
orientation
addStartPoint
  The intersection test above is vulnerable to robustness errors;
i.e. it may be that the offsets should intersect very close to their endpoints, but aren't reported as such due to rounding. To handle this situation appropriately, we use the following test: If the offset points are very close, don't add closing segments but simply use one of the offset points
Definition at line 401 of file OffsetSegmentGenerator.cpp.
References geos::operation::buffer::OffsetSegmentString::addPt(), closingSegLengthFactor, geos::algorithm::LineIntersector::computeIntersection(), geos::geom::Coordinate::distance(), distance, geos::algorithm::LineIntersector::getIntersection(), geos::algorithm::LineIntersector::hasIntersection(), geos::ignore_unused_variable_warning(), INSIDE_TURN_VERTEX_SNAP_DISTANCE_FACTOR, li, offset0, offset1, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, s1, segList, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by addNextSegment().
 {
     ::geos::ignore_unused_variable_warning(orientation);
     ::geos::ignore_unused_variable_warning(addStartPoint);
   // add intersection point of offset segments (if any)
   li.computeIntersection(offset0.p0, offset0.p1, offset1.p0, offset1.p1);
   if (li.hasIntersection())
   {
     segList.addPt(li.getIntersection(0));
     return;
   }
   // If no intersection is detected, it means the angle is so small
   // and/or the offset so large that the offsets segments don't
   // intersect. In this case we must add a "closing segment" to make
   // sure the buffer curve is continuous,
   // fairly smooth (e.g. no sharp reversals in direction)
   // and tracks the buffer correctly around the corner.
   // The curve connects the endpoints of the segment offsets to points
   // which lie toward the centre point of the corner.
   // The joining curve will not appear in the final buffer outline,
   // since it is completely internal to the buffer polygon.
   //
   // In complex buffer cases the closing segment may cut across many
   // other segments in the generated offset curve.
   // In order to improve the performance of the noding, the closing
   // segment should be kept as short as possible.
   // (But not too short, since that would defeat it's purpose).
   // This is the purpose of the closingSegLengthFactor heuristic value.
   if (offset0.p1.distance(offset1.p0) <
     distance * INSIDE_TURN_VERTEX_SNAP_DISTANCE_FACTOR)
   {
     segList.addPt(offset0.p1);
   }
   else
   {
     // add endpoint of this segment offset
     segList.addPt(offset0.p1);
     // Add "closing segment" of required length.
     if ( closingSegLengthFactor > 0 )
     {
       Coordinate mid0(
  (closingSegLengthFactor*offset0.p1.x + s1.x)/(closingSegLengthFactor + 1),
  (closingSegLengthFactor*offset0.p1.y + s1.y)/(closingSegLengthFactor + 1)
       );
       segList.addPt(mid0);
       Coordinate mid1(
  (closingSegLengthFactor*offset1.p0.x + s1.x)/(closingSegLengthFactor + 1),
  (closingSegLengthFactor*offset1.p0.y + s1.y)/(closingSegLengthFactor + 1)
       );
       segList.addPt(mid1);
     }
     else
     {
       // This branch is not expected to be used
       // except for testing purposes.
       // It is equivalent to the JTS 1.9 logic for
       // closing segments (which results in very poor
       // performance for large buffer distances)
       segList.addPt(s1);
     }
     // add start point of next segment offset
     segList.addPt(offset1.p0);
   }
 }
void geos::operation::buffer::OffsetSegmentGenerator::addLastSegment () inline
Add last offset point.
Definition at line 124 of file OffsetSegmentGenerator.h.
Referenced by geos::operation::buffer::OffsetCurveBuilder::computeLineBufferCurve(), and geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve().
   {
     segList.addPt(offset1.p1);
   }
void geos::operation::buffer::OffsetSegmentGenerator::addLimitedMitreJoin (const geom::LineSegment & offset0, const geom::LineSegment & offset1, double distance, double mitreLimit) private
Adds a limited mitre join connecting the two reflex offset segments.
A limited mitre is a mitre which is beveled at the distance determined by the mitre ratio limit.
Parameters
offset0 the first offset segment
offset1 the second offset segment
distance the offset distance
mitreLimit the mitre limit ratio
Definition at line 532 of file OffsetSegmentGenerator.cpp.
References geos::operation::buffer::OffsetSegmentString::addPt(), distance, geos::ignore_unused_variable_warning(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, PI, geos::geom::LineSegment::pointAlongOffset(), seg0, seg1, segList, side, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by addMitreJoin().
 {
     ::geos::ignore_unused_variable_warning(offset0);
     ::geos::ignore_unused_variable_warning(offset1);
   const Coordinate& basePt = seg0.p1;
   double ang0 = Angle::angle(basePt, seg0.p0);
   //double ang1 = Angle::angle(basePt, seg1.p1); // unused in JTS, bug ?
   // oriented angle between segments
   double angDiff = Angle::angleBetweenOriented(seg0.p0, basePt, seg1.p1);
   // half of the interior angle
   double angDiffHalf = angDiff / 2;
   // angle for bisector of the interior angle between the segments
   double midAng = Angle::normalize(ang0 + angDiffHalf);
   // rotating this by PI gives the bisector of the reflex angle
   double mitreMidAng = Angle::normalize(midAng + PI);
   // the miterLimit determines the distance to the mitre bevel
   double mitreDist = mitreLimit * distance;
   // the bevel delta is the difference between the buffer distance
   // and half of the length of the bevel segment
   double bevelDelta = mitreDist * fabs(sin(angDiffHalf));
   double bevelHalfLen = distance - bevelDelta;
   // compute the midpoint of the bevel segment
   double bevelMidX = basePt.x + mitreDist * cos(mitreMidAng);
   double bevelMidY = basePt.y + mitreDist * sin(mitreMidAng);
   Coordinate bevelMidPt(bevelMidX, bevelMidY);
   // compute the mitre midline segment from the corner point to
   // the bevel segment midpoint
   LineSegment mitreMidLine(basePt, bevelMidPt);
   // finally the bevel segment endpoints are computed as offsets from
   // the mitre midline
   Coordinate bevelEndLeft;
   mitreMidLine.pointAlongOffset(1.0, bevelHalfLen, bevelEndLeft);
   Coordinate bevelEndRight;
   mitreMidLine.pointAlongOffset(1.0, -bevelHalfLen, bevelEndRight);
   if (side == Position::LEFT) {
     segList.addPt(bevelEndLeft);
     segList.addPt(bevelEndRight);
   }
   else {
     segList.addPt(bevelEndRight);
     segList.addPt(bevelEndLeft);
   }
 }
void geos::operation::buffer::OffsetSegmentGenerator::addLineEndCap (const geom::Coordinate & p0, const geom::Coordinate & p1)
Add an end cap around point p1, terminating a line segment coming from p0.
Definition at line 195 of file OffsetSegmentGenerator.cpp.
References addFillet(), geos::operation::buffer::OffsetSegmentString::addPt(), bufParams, geos::operation::buffer::BufferParameters::CAP_FLAT, geos::operation::buffer::BufferParameters::CAP_ROUND, geos::operation::buffer::BufferParameters::CAP_SQUARE, computeOffsetSegment(), distance, geos::operation::buffer::BufferParameters::getEndCapStyle(), geos::geom::LineSegment::p1, PI, segList, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::operation::buffer::OffsetCurveBuilder::computeLineBufferCurve().
 {
   LineSegment seg(p0, p1);
   LineSegment offsetL;
   computeOffsetSegment(seg, Position::LEFT, distance, offsetL);
   LineSegment offsetR;
   computeOffsetSegment(seg, Position::RIGHT, distance, offsetR);
   double dx=p1.x-p0.x;
   double dy=p1.y-p0.y;
   double angle=atan2(dy, dx);
   switch (bufParams.getEndCapStyle()) {
     case BufferParameters::CAP_ROUND:
       // add offset seg points with a fillet between them
       segList.addPt(offsetL.p1);
       addFillet(p1, angle+PI/2.0, angle-PI/2.0,
                 CGAlgorithms::CLOCKWISE, distance);
       segList.addPt(offsetR.p1);
       break;
     case BufferParameters::CAP_FLAT:
       // only offset segment points are added
       segList.addPt(offsetL.p1);
       segList.addPt(offsetR.p1);
       break;
     case BufferParameters::CAP_SQUARE:
       // add a square defined by extensions of the offset
       // segment endpoints
       Coordinate squareCapSideOffset;
       squareCapSideOffset.x=fabs(distance)*cos(angle);
       squareCapSideOffset.y=fabs(distance)*sin(angle);
       Coordinate squareCapLOffset(
         offsetL.p1.x+squareCapSideOffset.x,
         offsetL.p1.y+squareCapSideOffset.y);
       Coordinate squareCapROffset(
         offsetR.p1.x+squareCapSideOffset.x,
         offsetR.p1.y+squareCapSideOffset.y);
       segList.addPt(squareCapLOffset);
       segList.addPt(squareCapROffset);
       break;
   }
 }
void geos::operation::buffer::OffsetSegmentGenerator::addMitreJoin (const geom::Coordinate & p, const geom::LineSegment & offset0, const geom::LineSegment & offset1, double distance) private
The mitre will be beveled if it exceeds the mitre ratio limit.
Parameters
offset0 the first offset segment
offset1 the second offset segment
distance the offset distance
  This computation is unstable if the offset segments
are nearly collinear. Howver, this situation should have been eliminated earlier by the check for whether the offset segment endpoints are almost coincident
Definition at line 483 of file OffsetSegmentGenerator.cpp.
References addLimitedMitreJoin(), geos::operation::buffer::OffsetSegmentString::addPt(), bufParams, geos::geom::Coordinate::distance(), geos::operation::buffer::BufferParameters::getMitreLimit(), geos::ignore_unused_variable_warning(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and segList.
Referenced by addOutsideTurn().
 {
   bool isMitreWithinLimit = true;
   Coordinate intPt;
     try
     {
         HCoordinate::intersection(offset0.p0, offset0.p1,
             offset1.p0, offset1.p1,
             intPt);
         double mitreRatio = distance <= 0.0 ? 1.0
             : intPt.distance(p) / fabs(distance);
         if (mitreRatio > bufParams.getMitreLimit())
             isMitreWithinLimit = false;
     }
     catch (const NotRepresentableException& e)
     {
         ::geos::ignore_unused_variable_warning(e);
         intPt = Coordinate(0,0);
         isMitreWithinLimit = false;
     }
     if (isMitreWithinLimit)
     {
         segList.addPt(intPt);
     }
     else
     {
         addLimitedMitreJoin(offset0, offset1, distance,
             bufParams.getMitreLimit());
         //addBevelJoin(offset0, offset1);
     }
 }
void geos::operation::buffer::OffsetSegmentGenerator::addNextSegment (const geom::Coordinate & p, bool addStartPoint)
Definition at line 134 of file OffsetSegmentGenerator.cpp.
References addCollinear(), addInsideTurn(), addOutsideTurn(), computeOffsetSegment(), distance, offset0, offset1, s0, s1, s2, seg0, seg1, geos::geom::LineSegment::setCoordinates(), and side.
Referenced by geos::operation::buffer::OffsetCurveBuilder::computeLineBufferCurve(), geos::operation::buffer::OffsetCurveBuilder::computeRingBufferCurve(), and geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve().
 {
   // do nothing if points are equal
   if (s2==p) return;
   // s0-s1-s2 are the coordinates of the previous segment
   // and the current one
   s0=s1;
   s1=s2;
   s2=p;
   seg0.setCoordinates(s0, s1);
   computeOffsetSegment(seg0, side, distance, offset0);
   seg1.setCoordinates(s1, s2);
   computeOffsetSegment(seg1, side, distance, offset1);
   int orientation=CGAlgorithms::computeOrientation(s0, s1, s2);
   bool outsideTurn =
     (orientation==CGAlgorithms::CLOCKWISE
      && side==Position::LEFT)
     ||
     (orientation==CGAlgorithms::COUNTERCLOCKWISE
      && side==Position::RIGHT);
   if (orientation==0)
   {
     // lines are collinear
     addCollinear(addStartPoint);
   }
   else if (outsideTurn)
   {
     addOutsideTurn(orientation, addStartPoint);
   }
   else
   {
     // inside turn
     addInsideTurn(orientation, addStartPoint);
   }
 }
void geos::operation::buffer::OffsetSegmentGenerator::addOutsideTurn (int orientation, bool addStartPoint) private
Adds the offset points for an outside (convex) turn.
Parameters
orientation
addStartPoint
Heuristic: If offset endpoints are very close together, just use one of them as the corner vertex. This avoids problems with computing mitre corners in the case where the two segments are almost parallel (which is hard to compute a robust intersection for).
Definition at line 362 of file OffsetSegmentGenerator.cpp.
References addBevelJoin(), addFillet(), addMitreJoin(), geos::operation::buffer::OffsetSegmentString::addPt(), bufParams, geos::geom::Coordinate::distance(), distance, geos::operation::buffer::BufferParameters::getJoinStyle(), geos::operation::buffer::BufferParameters::JOIN_BEVEL, geos::operation::buffer::BufferParameters::JOIN_MITRE, offset0, offset1, OFFSET_SEGMENT_SEPARATION_FACTOR, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, s1, and segList.
Referenced by addNextSegment().
 {
   if (offset0.p1.distance(offset1.p0) <
     distance*OFFSET_SEGMENT_SEPARATION_FACTOR)
   {
     segList.addPt(offset0.p1);
     return;
   }
   if (bufParams.getJoinStyle() == BufferParameters::JOIN_MITRE)
   {
     addMitreJoin(s1, offset0, offset1, distance);
   }
   else if (bufParams.getJoinStyle() == BufferParameters::JOIN_BEVEL)
   {
     addBevelJoin(offset0, offset1);
   }
   else
   {
     // add a circular fillet connecting the endpoints
     // of the offset segments
     if (addStartPoint) segList.addPt(offset0.p1);
     // TESTING - comment out to produce beveled joins
     addFillet(s1, offset0.p1, offset1.p0, orientation, distance);
     segList.addPt(offset1.p0);
   }
 }
void geos::operation::buffer::OffsetSegmentGenerator::addSegments (const geom::CoordinateSequence & pts, bool isForward) inline
Definition at line 137 of file OffsetSegmentGenerator.h.
Referenced by geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve().
   {
     segList.addPts(pts, isForward);
   }
void geos::operation::buffer::OffsetSegmentGenerator::closeRing () inline
Definition at line 107 of file OffsetSegmentGenerator.h.
Referenced by geos::operation::buffer::OffsetCurveBuilder::computeLineBufferCurve(), geos::operation::buffer::OffsetCurveBuilder::computeRingBufferCurve(), and geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve().
                    {
     segList.closeRing();
   }
void geos::operation::buffer::OffsetSegmentGenerator::computeOffsetSegment (const geom::LineSegment & seg, int side, double distance, geom::LineSegment & offset) private
Compute an offset segment for an input segment on a given side and at a given distance.
The offset points are computed in full double precision, for accuracy.
Parameters
seg the segment to offset
side the side of the segment the offset lies on
distance the offset distance
offset the points computed for the offset segment
Definition at line 176 of file OffsetSegmentGenerator.cpp.
References geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by addLineEndCap(), addNextSegment(), and initSideSegments().
 {
   int sideSign = side == Position::LEFT ? 1 : -1;
   double dx = seg.p1.x - seg.p0.x;
   double dy = seg.p1.y - seg.p0.y;
   double len = sqrt(dx * dx + dy * dy);
   // u is the vector that is the length of the offset,
   // in the direction of the segment
   double ux = sideSign * distance * dx / len;
   double uy = sideSign * distance * dy / len;
   offset.p0.x = seg.p0.x - uy;
   offset.p0.y = seg.p0.y + ux;
   offset.p1.x = seg.p1.x - uy;
   offset.p1.y = seg.p1.y + ux;
 }
void geos::operation::buffer::OffsetSegmentGenerator::createCircle (const geom::Coordinate & p, double distance)
Adds a CW circle around a point.
Definition at line 297 of file OffsetSegmentGenerator.cpp.
References addFillet(), geos::operation::buffer::OffsetSegmentString::addPt(), geos::operation::buffer::OffsetSegmentString::closeRing(), PI, segList, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::operation::buffer::OffsetCurveBuilder::computePointCurve().
 {
   // add start point
   Coordinate pt(p.x + distance, p.y);
   segList.addPt(pt);
   addFillet(p, 0.0, 2.0*PI, -1, distance);
   segList.closeRing();
 }
void geos::operation::buffer::OffsetSegmentGenerator::createSquare (const geom::Coordinate & p, double distance)
Adds a CW square around a point.
Definition at line 308 of file OffsetSegmentGenerator.cpp.
References geos::operation::buffer::OffsetSegmentString::addPt(), geos::operation::buffer::OffsetSegmentString::closeRing(), segList, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::operation::buffer::OffsetCurveBuilder::computePointCurve().
 {
   segList.addPt(Coordinate(p.x+distance, p.y+distance));
   segList.addPt(Coordinate(p.x+distance, p.y-distance));
   segList.addPt(Coordinate(p.x-distance, p.y-distance));
   segList.addPt(Coordinate(p.x-distance, p.y+distance));
   segList.closeRing();
 }
void geos::operation::buffer::OffsetSegmentGenerator::getCoordinates (std::vector< geom::CoordinateSequence * > & to) inline
Get coordinates by taking ownership of them.
After this call, the coordinates reference in this object are dropped. Calling twice will segfault...
FIXME: refactor memory management of this
Definition at line 103 of file OffsetSegmentGenerator.h.
{
     to.push_back(segList.getCoordinates());
   }
bool geos::operation::buffer::OffsetSegmentGenerator::hasNarrowConcaveAngle () const inline
Tests whether the input has a narrow concave angle (relative to the offset distance). In this case the generated offset curve will contain self-intersections and heuristic closing segments. This is expected behaviour in the case of buffer curves. For pure offset curves, the output needs to be further treated before it can be used.
Returns
true if the input has a narrow concave angle
Definition at line 87 of file OffsetSegmentGenerator.h.
   {
     return _hasNarrowConcaveAngle;
   }
void geos::operation::buffer::OffsetSegmentGenerator::init (double newDistance) private
Choose the min vertex separation as a small fraction of the offset distance.
Definition at line 103 of file OffsetSegmentGenerator.cpp.
References CURVE_VERTEX_SNAP_DISTANCE_FACTOR, distance, filletAngleQuantum, maxCurveSegmentError, precisionModel, geos::operation::buffer::OffsetSegmentString::reset(), segList, geos::operation::buffer::OffsetSegmentString::setMinimumVertexDistance(), and geos::operation::buffer::OffsetSegmentString::setPrecisionModel().
Referenced by OffsetSegmentGenerator().
 {
   distance = newDistance;
   maxCurveSegmentError = distance * (1 - cos(filletAngleQuantum/2.0));
   // Point list needs to be reset
   segList.reset();
   segList.setPrecisionModel(precisionModel);
   segList.setMinimumVertexDistance(
     distance * CURVE_VERTEX_SNAP_DISTANCE_FACTOR);
 }
void geos::operation::buffer::OffsetSegmentGenerator::initSideSegments (const geom::Coordinate & nS1, const geom::Coordinate & nS2, int nSide)
Definition at line 122 of file OffsetSegmentGenerator.cpp.
References computeOffsetSegment(), distance, offset1, s1, s2, seg1, geos::geom::LineSegment::setCoordinates(), and side.
Referenced by geos::operation::buffer::OffsetCurveBuilder::computeLineBufferCurve(), geos::operation::buffer::OffsetCurveBuilder::computeRingBufferCurve(), and geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve().
 {
   s1 = nS1;
   s2 = nS2;
   side = nSide;
   seg1.setCoordinates(s1, s2);
   computeOffsetSegment(seg1, side, distance, offset1);
 }
void geos::operation::buffer::OffsetSegmentGenerator::operator= (const OffsetSegmentGenerator &) private
Member Data Documentation
bool geos::operation::buffer::OffsetSegmentGenerator::_hasNarrowConcaveAngle private
Definition at line 227 of file OffsetSegmentGenerator.h.
const BufferParameters& geos::operation::buffer::OffsetSegmentGenerator::bufParams private
Definition at line 211 of file OffsetSegmentGenerator.h.
Referenced by addCollinear(), addLineEndCap(), addMitreJoin(), addOutsideTurn(), and OffsetSegmentGenerator().
int geos::operation::buffer::OffsetSegmentGenerator::closingSegLengthFactor private
The Closing Segment Factor controls how long "closing segments" are. Closing segments are added at the middle of inside corners to ensure a smoother boundary for the buffer offset curve. In some cases (particularly for round joins with default-or-better quantization) the closing segments can be made quite short. This substantially improves performance (due to fewer intersections being created).
A closingSegFactor of 0 results in lines to the corner vertex. A closingSegFactor of 1 results in lines halfway to the corner vertex. A closingSegFactor of 80 results in lines 1/81 of the way to the corner vertex (this option is reasonable for the very common default situation of round joins and quadrantSegs >= 8).
The default is 1.
Definition at line 195 of file OffsetSegmentGenerator.h.
Referenced by addInsideTurn(), and OffsetSegmentGenerator().
const double geos::operation::buffer::OffsetSegmentGenerator::CURVE_VERTEX_SNAP_DISTANCE_FACTOR = 1.0E-6 static private
Factor which controls how close curve vertices can be to be snapped
Definition at line 159 of file OffsetSegmentGenerator.h.
Referenced by init().
double geos::operation::buffer::OffsetSegmentGenerator::distance private
Definition at line 207 of file OffsetSegmentGenerator.h.
Referenced by addCollinear(), addInsideTurn(), addLimitedMitreJoin(), addLineEndCap(), addNextSegment(), addOutsideTurn(), init(), initSideSegments(), and OffsetSegmentGenerator().
int geos::operation::buffer::OffsetSegmentGenerator::endCapIndex private
Definition at line 270 of file OffsetSegmentGenerator.h.
double geos::operation::buffer::OffsetSegmentGenerator::filletAngleQuantum private
The angle quantum with which to approximate a fillet curve (based on the input # of quadrant segments)
Definition at line 176 of file OffsetSegmentGenerator.h.
Referenced by addFillet(), init(), and OffsetSegmentGenerator().
const double geos::operation::buffer::OffsetSegmentGenerator::INSIDE_TURN_VERTEX_SNAP_DISTANCE_FACTOR = 1.0E-3 static private
Factor which controls how close curve vertices on inside turns can be to be snapped
Definition at line 154 of file OffsetSegmentGenerator.h.
Referenced by addInsideTurn().
algorithm::LineIntersector geos::operation::buffer::OffsetSegmentGenerator::li private
Definition at line 213 of file OffsetSegmentGenerator.h.
Referenced by addCollinear(), and addInsideTurn().
const int geos::operation::buffer::OffsetSegmentGenerator::MAX_CLOSING_SEG_LEN_FACTOR = 80 static private
Factor which determines how short closing segs can be for round buffers
Definition at line 164 of file OffsetSegmentGenerator.h.
Referenced by OffsetSegmentGenerator().
double geos::operation::buffer::OffsetSegmentGenerator::maxCurveSegmentError private
the max error of approximation (distance) between a quad segment and the true fillet curve
Definition at line 170 of file OffsetSegmentGenerator.h.
Referenced by init().
geom::LineSegment geos::operation::buffer::OffsetSegmentGenerator::offset0 private
Definition at line 221 of file OffsetSegmentGenerator.h.
Referenced by addCollinear(), addInsideTurn(), addNextSegment(), and addOutsideTurn().
geom::LineSegment geos::operation::buffer::OffsetSegmentGenerator::offset1 private
Definition at line 223 of file OffsetSegmentGenerator.h.
Referenced by addCollinear(), addInsideTurn(), addNextSegment(), addOutsideTurn(), and initSideSegments().
const double geos::operation::buffer::OffsetSegmentGenerator::OFFSET_SEGMENT_SEPARATION_FACTOR = 1.0E-3 static private
Factor which controls how close offset segments can be to skip adding a filler or mitre.
Definition at line 148 of file OffsetSegmentGenerator.h.
Referenced by addOutsideTurn().
const double geos::operation::buffer::OffsetSegmentGenerator::PI = 3.14159265358979 static private
Definition at line 267 of file OffsetSegmentGenerator.h.
Referenced by addFillet(), addLimitedMitreJoin(), addLineEndCap(), createCircle(), and OffsetSegmentGenerator().
const geom::PrecisionModel* geos::operation::buffer::OffsetSegmentGenerator::precisionModel private
Definition at line 209 of file OffsetSegmentGenerator.h.
Referenced by init().
geom::Coordinate geos::operation::buffer::OffsetSegmentGenerator::s0 private
Definition at line 215 of file OffsetSegmentGenerator.h.
Referenced by addCollinear(), and addNextSegment().
geom::Coordinate geos::operation::buffer::OffsetSegmentGenerator::s1 private
Definition at line 215 of file OffsetSegmentGenerator.h.
Referenced by addCollinear(), addInsideTurn(), addNextSegment(), addOutsideTurn(), and initSideSegments().
geom::Coordinate geos::operation::buffer::OffsetSegmentGenerator::s2 private
Definition at line 215 of file OffsetSegmentGenerator.h.
Referenced by addCollinear(), addNextSegment(), and initSideSegments().
geom::LineSegment geos::operation::buffer::OffsetSegmentGenerator::seg0 private
Definition at line 217 of file OffsetSegmentGenerator.h.
Referenced by addLimitedMitreJoin(), and addNextSegment().
geom::LineSegment geos::operation::buffer::OffsetSegmentGenerator::seg1 private
Definition at line 219 of file OffsetSegmentGenerator.h.
Referenced by addLimitedMitreJoin(), addNextSegment(), and initSideSegments().
OffsetSegmentString geos::operation::buffer::OffsetSegmentGenerator::segList private
Owned by this object, destroyed by dtor.
This actually gets created multiple times and each of the old versions is pushed to the ptLists std::vector to ensure all created CoordinateSequences are properly destroyed.
Definition at line 205 of file OffsetSegmentGenerator.h.
Referenced by addBevelJoin(), addCollinear(), addFillet(), addInsideTurn(), addLimitedMitreJoin(), addLineEndCap(), addMitreJoin(), addOutsideTurn(), createCircle(), createSquare(), and init().
int geos::operation::buffer::OffsetSegmentGenerator::side private
Definition at line 225 of file OffsetSegmentGenerator.h.
Referenced by addLimitedMitreJoin(), addNextSegment(), and initSideSegments().
const double geos::operation::buffer::OffsetSegmentGenerator::SIMPLIFY_FACTOR = 100.0 static private
Use a value which results in a potential distance error which is significantly less than the error due to the quadrant segment discretization. For QS = 8 a value of 100 is reasonable. This should produce a maximum of 1% distance error.
Definition at line 281 of file OffsetSegmentGenerator.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/OffsetSegmentGenerator.h
/home/vicky/potree/geos/vicky/src/operation/buffer/OffsetSegmentGenerator.cpp