GEOS: geos::operation::overlay::OverlayOp Class Reference
geos::operation::overlay::OverlayOp Class Reference
Computes the geometric overlay of two Geometry.
#include <OverlayOp.h>
Public Types
enum OpCode { opINTERSECTION = 1, opUNION = 2, opDIFFERENCE = 3, opSYMDIFFERENCE = 4 }
The spatial functions supported by this class.
Public Member Functions
OverlayOp (const geom::Geometry *g0, const geom::Geometry *g1)
Construct an OverlayOp with the given Geometry args.
~OverlayOp () override
geom::Geometry * getResultGeometry (OpCode overlayOpCode)
geomgraph::PlanarGraph & getGraph ()
bool isCoveredByLA (const geom::Coordinate &coord)
This method is used to decide if a point node should be included in the result or not.
bool isCoveredByA (const geom::Coordinate &coord)
This method is used to decide if an L edge should be included in the result or not.
const geom::Geometry * getArgGeometry (unsigned int i) const
Static Public Member Functions
static geom::Geometry * overlayOp (const geom::Geometry *geom0, const geom::Geometry *geom1, OpCode opCode)
static bool isResultOfOp (const geomgraph::Label &label, OpCode opCode)
static bool isResultOfOp (int loc0, int loc1, OpCode opCode)
This method will handle arguments of Location.NULL correctly.
Protected Member Functions
void insertUniqueEdge (geomgraph::Edge *e)
Insert an edge from one of the noded input graphs.
void setComputationPrecision (const geom::PrecisionModel *pm)
Protected Attributes
algorithm::LineIntersector li
const geom::PrecisionModel * resultPrecisionModel
std::vector< geomgraph::GeometryGraph * > arg
The operation args into an array so they can be accessed by index.
Private Member Functions
void computeOverlay (OpCode opCode)
void insertUniqueEdges (std::vector< geomgraph::Edge * > *edges, const geom::Envelope *env=nullptr)
void computeLabelsFromDepths ()
Update the labels for edges according to their depths.
void replaceCollapsedEdges ()
If edges which have undergone dimensional collapse are found, replace them with a new edge which is a L edge.
void copyPoints (int argIndex, const geom::Envelope *env=nullptr)
Copy all nodes from an arg geometry into this graph.
void computeLabelling ()
Compute initial labelling for all DirectedEdges at each node.
void mergeSymLabels ()
void updateNodeLabelling ()
void labelIncompleteNodes ()
void labelIncompleteNode (geomgraph::Node *n, int targetIndex)
Label an isolated node with its relationship to the target geometry.
void findResultAreaEdges (OpCode opCode)
Find all edges whose label indicates that they are in the result area(s), according to the operation being performed.
void cancelDuplicateResultEdges ()
bool isCovered (const geom::Coordinate &coord, std::vector< geom::Geometry * > *geomList)
bool isCovered (const geom::Coordinate &coord, std::vector< geom::Polygon * > *geomList)
bool isCovered (const geom::Coordinate &coord, std::vector< geom::LineString * > *geomList)
geom::Geometry * computeGeometry (std::vector< geom::Point * > *nResultPointList, std::vector< geom::LineString * > *nResultLineList, std::vector< geom::Polygon * > *nResultPolyList)
int mergeZ (geomgraph::Node *n, const geom::Polygon *poly) const
Merge Z values of node with those of the segment or vertex in the given Polygon it is on.
int mergeZ (geomgraph::Node *n, const geom::LineString *line) const
double getAverageZ (int targetIndex)
void checkObviouslyWrongResult (OpCode opCode)
Static Private Member Functions
static double getAverageZ (const geom::Polygon *poly)
Private Attributes
algorithm::PointLocator ptLocator
const geom::GeometryFactory * geomFact
geom::Geometry * resultGeom
geomgraph::PlanarGraph graph
geomgraph::EdgeList edgeList
std::vector< geom::Polygon * > * resultPolyList
std::vector< geom::LineString * > * resultLineList
std::vector< geom::Point * > * resultPointList
std::vector< geomgraph::Edge * > dupEdges
Caches for memory management.
double avgz [2]
bool avgzcomputed [2]
ElevationMatrix * elevationMatrix
Detailed Description
Computes the geometric overlay of two Geometry.
The overlay can be used to determine any boolean combination of the geometries.
Definition at line 68 of file OverlayOp.h.
Member Enumeration Documentation
enum geos::operation::overlay::OverlayOp::OpCode
The spatial functions supported by this class.
These operations implement various boolean combinations of the resultants of the overlay.
Enumerator
opINTERSECTION
The code for the Intersection overlay operation.
opUNION
The code for the Union overlay operation.
opDIFFERENCE
The code for the Difference overlay operation.
opSYMDIFFERENCE
The code for the Symmetric Difference overlay operation.
Definition at line 77 of file OverlayOp.h.
               {
     opINTERSECTION = 1,
     opUNION = 2,
     opDIFFERENCE = 3,
     opSYMDIFFERENCE = 4
   };
Constructor & Destructor Documentation
geos::operation::overlay::OverlayOp::OverlayOp (const geom::Geometry * g0, const geom::Geometry * g1)
Construct an OverlayOp with the given Geometry args.
Ownership of passed args will remain to caller, and the OverlayOp won't change them in any way.
Definition at line 126 of file OverlayOp.cpp.
References geos::operation::overlay::ElevationMatrix::add(), avgz, avgzcomputed, elevationMatrix, geos::geom::Envelope::expandToInclude(), geos::geom::Geometry::getEnvelopeInternal(), and geos::operation::overlay::ElevationMatrix::print().
   :
   // this builds graphs in arg[0] and arg[1]
   GeometryGraphOperation(g0, g1),
   /*
    * Use factory of primary geometry.
    * Note that this does NOT handle mixed-precision arguments
    * where the second arg has greater precision than the first.
    */
   geomFact(g0->getFactory()),
   resultGeom(nullptr),
   graph(OverlayNodeFactory::instance()),
   resultPolyList(nullptr),
   resultLineList(nullptr),
   resultPointList(nullptr)
 {
 #if COMPUTE_Z
 #if USE_INPUT_AVGZ
   avgz[0] = DoubleNotANumber;
   avgz[1] = DoubleNotANumber;
   avgzcomputed[0] = false;
   avgzcomputed[1] = false;
 #endif // USE_INPUT_AVGZ
   Envelope env(*(g0->getEnvelopeInternal()));
   env.expandToInclude(g1->getEnvelopeInternal());
 #if USE_ELEVATION_MATRIX
   elevationMatrix = new ElevationMatrix(env, 3, 3);
   elevationMatrix->add(g0);
   elevationMatrix->add(g1);
 #if GEOS_DEBUG
   cerr<<elevationMatrix->print()<<endl;
 #endif
 #endif // USE_ELEVATION_MATRIX
 #endif // COMPUTE_Z
 }
geos::operation::overlay::OverlayOp::~OverlayOp () override
Definition at line 169 of file OverlayOp.cpp.
References dupEdges, elevationMatrix, resultLineList, resultPointList, and resultPolyList.
 {
   //delete edgeList;
   delete resultPolyList;
   delete resultLineList;
   delete resultPointList;
   for (size_t i=0; i<dupEdges.size(); i++)
     delete dupEdges[i];
 #if USE_ELEVATION_MATRIX
   delete elevationMatrix;
 #endif
 }
Member Function Documentation
void geos::operation::overlay::OverlayOp::cancelDuplicateResultEdges () private
If both a dirEdge and its sym are marked as being in the result, cancel them out.
Definition at line 569 of file OverlayOp.cpp.
References geos::geomgraph::PlanarGraph::getEdgeEnds(), geos::geomgraph::DirectedEdge::getSym(), graph, geos::geomgraph::DirectedEdge::isInResult(), and geos::geomgraph::DirectedEdge::setInResult().
Referenced by computeOverlay().
 {
   // remove any dirEdges whose sym is also included
   // (they "cancel each other out")
   vector<EdgeEnd*> *ee=graph.getEdgeEnds();
   for(size_t i=0, eesize=ee->size(); i<eesize; ++i)
   {
     DirectedEdge *de=static_cast<DirectedEdge*>( (*ee)[i] );
     DirectedEdge *sym=de->getSym();
     if (de->isInResult() && sym->isInResult()) {
       de->setInResult(false);
       sym->setInResult(false);
       //Debug.print("cancelled "); Debug.println(de); Debug.println(sym);
     }
   }
 }
void geos::operation::overlay::OverlayOp::checkObviouslyWrongResult (OverlayOp::OpCode opCode) private
Throw TopologyException if an obviously wrong result has been computed.
Definition at line 987 of file OverlayOp.cpp.
References geos::operation::GeometryGraphOperation::arg, geos::geom::Geometry::getArea(), geos::operation::overlay::validate::OverlayResultValidator::getInvalidLocation(), geos::ignore_unused_variable_warning(), geos::geom::PrecisionModel::isFloating(), geos::operation::overlay::validate::OverlayResultValidator::isValid(), opDIFFERENCE, opINTERSECTION, resultGeom, geos::operation::GeometryGraphOperation::resultPrecisionModel, geos::geom::Coordinate::toString(), and geos::geom::Geometry::toString().
Referenced by computeOverlay().
 {
   using std::cerr;
   using std::endl;
   assert(resultGeom);
 #ifdef ENABLE_OTHER_OVERLAY_RESULT_VALIDATORS
   if ( opCode == opINTERSECTION
     && arg[0]->getGeometry()->getDimension() == Dimension::A
     && arg[1]->getGeometry()->getDimension() == Dimension::A )
   {
     // Area of result must be less or equal area of smaller geom
     double area0 = arg[0]->getGeometry()->getArea();
     double area1 = arg[1]->getGeometry()->getArea();
     double minarea = min(area0, area1);
     double resultArea = resultGeom->getArea();
     if ( resultArea > minarea )
     {
       throw util::TopologyException("Obviously wrong result: "
         "area of intersection "
         "result is bigger then minimum area between "
         "input geometries");
     }
   }
   else if ( opCode == opDIFFERENCE
     && arg[0]->getGeometry()->getDimension() == Dimension::A
     && arg[1]->getGeometry()->getDimension() == Dimension::A )
   {
     // Area of result must be less or equal area of first geom
     double area0 = arg[0]->getGeometry()->getArea();
     double resultArea = resultGeom->getArea();
     if ( resultArea > area0 )
     {
       throw util::TopologyException("Obviously wrong result: "
         "area of difference "
         "result is bigger then area of first "
         "input geometry");
     }
     // less obvious check:
     // each vertex in first geom must be either covered by
     // result or second geom
     vector<const Geometry*> testGeoms; testGeoms.reserve(2);
     testGeoms.push_back(resultGeom);
     testGeoms.push_back(arg[1]->getGeometry());
     PointCoveredByAny tester(testGeoms);
     arg[0]->getGeometry()->apply_ro(&tester);
   }
   // Add your tests here
 #else
     ::geos::ignore_unused_variable_warning(opCode);
 #endif
 #ifdef ENABLE_OVERLAY_RESULT_VALIDATOR
   // This only work for FLOATING precision
   if ( resultPrecisionModel->isFloating() )
   {
     validate::OverlayResultValidator validator( *(arg[0]->getGeometry()),
       *(arg[1]->getGeometry()), *(resultGeom));
     bool isvalid = validator.isValid(opCode);
     if ( ! isvalid )
     {
 #ifdef GEOS_DEBUG_VALIDATION
       cout << "OverlayResultValidator considered result INVALID" << endl;
 #endif
       throw util::TopologyException(
         "Obviously wrong result: "
         "OverlayResultValidator didn't like "
         "the result: \n"
         "Invalid point: " +
         validator.getInvalidLocation().toString() +
         string("\nInvalid result: ") +
         resultGeom->toString());
     }
 #ifdef GEOS_DEBUG_VALIDATION
     else
     {
       cout << "OverlayResultValidator considered result valid" << endl;
     }
 #endif
   }
 #ifdef GEOS_DEBUG_VALIDATION
   else
   {
     cout << "Did not run OverlayResultValidator as the precision model is not floating" << endl;
   }
 #endif // ndef GEOS_DEBUG
 #endif
 }
Geometry * geos::operation::overlay::OverlayOp::computeGeometry (std::vector< geom::Point * > * nResultPointList, std::vector< geom::LineString * > * nResultLineList, std::vector< geom::Polygon * > * nResultPolyList) private
Build a Geometry containing all Geometries in the given vectors. Takes element's ownership, vector control is left to caller.
Definition at line 644 of file OverlayOp.cpp.
References geos::geom::GeometryFactory::buildGeometry(), and geomFact.
Referenced by computeOverlay().
 {
   size_t nPoints=nResultPointList->size();
   size_t nLines=nResultLineList->size();
   size_t nPolys=nResultPolyList->size();
   vector<Geometry*> *geomList=new vector<Geometry*>();
   geomList->reserve(nPoints+nLines+nPolys);
   // element geometries of the result are always in the order P,L,A
   geomList->insert(geomList->end(),
       nResultPointList->begin(),
       nResultPointList->end());
   geomList->insert(geomList->end(),
       nResultLineList->begin(),
       nResultLineList->end());
   geomList->insert(geomList->end(),
       nResultPolyList->begin(),
       nResultPolyList->end());
   // build the most specific geometry possible
   Geometry *g=geomFact->buildGeometry(geomList);
   return g;
 }
void geos::operation::overlay::OverlayOp::computeLabelling () private
Compute initial labelling for all DirectedEdges at each node.
In this step, DirectedEdges will acquire a complete labelling (i.e. one with labels for both Geometries) only if they are incident on a node which has edges for both Geometries
Definition at line 276 of file OverlayOp.cpp.
References geos::operation::GeometryGraphOperation::arg, geos::geomgraph::EdgeEndStar::computeLabelling(), edgeList, geos::geomgraph::Node::getEdges(), geos::geomgraph::EdgeEndStar::getEdges(), geos::geomgraph::PlanarGraph::getNodeMap(), graph, mergeSymLabels(), geos::geomgraph::NodeMap::nodeMap, geos::geomgraph::EdgeList::print(), geos::geomgraph::Node::print(), and updateNodeLabelling().
Referenced by computeOverlay().
 {
   NodeMap::container& nodeMap=graph.getNodeMap()->nodeMap;
 #if GEOS_DEBUG
   cerr<<"OverlayOp::computeLabelling(): at call time: "<<edgeList.print()<<endl;
 #endif
 #if GEOS_DEBUG
   cerr<<"OverlayOp::computeLabelling() scanning "<<nodeMap.size()<<" nodes from map:"<<endl;
 #endif
   for ( NodeMap::const_iterator it=nodeMap.begin(), itEnd=nodeMap.end();
       it != itEnd; ++it )
   {
     Node *node=it->second;
 #if GEOS_DEBUG
     cerr<<"     "<<node->print()<<" has "<<node->getEdges()->getEdges().size()<<" edgeEnds"<<endl;
 #endif
     node->getEdges()->computeLabelling(&arg);
   }
 #if GEOS_DEBUG
   cerr<<"OverlayOp::computeLabelling(): after edge labelling: "<<edgeList.print()<<endl;
 #endif
   mergeSymLabels();
 #if GEOS_DEBUG
   cerr<<"OverlayOp::computeLabelling(): after labels sym merging: "<<edgeList.print()<<endl;
 #endif
   updateNodeLabelling();
 #if GEOS_DEBUG
   cerr<<"OverlayOp::computeLabelling(): after node labeling update: "<<edgeList.print()<<endl;
 #endif
 }
void geos::operation::overlay::OverlayOp::computeLabelsFromDepths () private
Update the labels for edges according to their depths.
For each edge, the depths are first normalized. Then, if the depths for the edge are equal, this edge must have collapsed into a line edge. If the depths are not equal, update the label with the locations corresponding to the depths (i.e. a depth of 0 corresponds to a Location of EXTERIOR, a depth of 1 corresponds to INTERIOR)
Definition at line 912 of file OverlayOp.cpp.
References edgeList, geos::geomgraph::Depth::getDelta(), geos::geomgraph::Depth::getDepth(), geos::geomgraph::EdgeList::getEdges(), geos::geomgraph::Depth::getLocation(), geos::geomgraph::Label::isArea(), geos::geomgraph::Depth::isNull(), geos::geomgraph::Label::isNull(), geos::geomgraph::Depth::normalize(), geos::geomgraph::Label::setLocation(), and geos::geomgraph::Label::toLine().
Referenced by computeOverlay().
 {
   for(auto &e : edgeList.getEdges())
   {
     Label& lbl = e->getLabel();
     Depth &depth = e->getDepth();
     /*
      * Only check edges for which there were duplicates,
      * since these are the only ones which might
      * be the result of dimensional collapses.
      */
     if (depth.isNull()) continue;
     depth.normalize();
     for (int i=0;i<2;i++)
     {
       if (!lbl.isNull(i) && lbl.isArea() && !depth.isNull(i))
       {
         /*
          * if the depths are equal, this edge is the result of
          * the dimensional collapse of two or more edges.
          * It has the same location on both sides of the edge,
          * so it has collapsed to a line.
          */
         if (depth.getDelta(i)==0) {
           lbl.toLine(i);
         } else {
           /*
            * This edge may be the result of a dimensional collapse,
            * but it still has different locations on both sides.  The
            * label of the edge must be updated to reflect the resultant
            * side locations indicated by the depth values.
            */
           assert(!depth.isNull(i,Position::LEFT)); // depth of LEFT side has not been initialized
           lbl.setLocation(i,Position::LEFT,depth.getLocation(i,Position::LEFT));
           assert(!depth.isNull(i,Position::RIGHT)); // depth of RIGHT side has not been initialized
           lbl.setLocation(i,Position::RIGHT,depth.getLocation(i,Position::RIGHT));
         }
       }
     }
   }
 }
void geos::operation::overlay::OverlayOp::computeOverlay (OverlayOp::OpCode opCode) private
Check that the noding completed correctly.
This test is slow, but necessary in order to catch robustness failure situations. If an exception is thrown because of a noding failure, then snapping will be performed, which will hopefully avoid the problem. In the future hopefully a faster check can be developed.
Definition at line 675 of file OverlayOp.cpp.
References geos::operation::overlay::PolygonBuilder::add(), geos::geomgraph::PlanarGraph::addEdges(), geos::operation::GeometryGraphOperation::arg, geos::operation::overlay::LineBuilder::build(), geos::operation::overlay::PointBuilder::build(), cancelDuplicateResultEdges(), checkObviouslyWrongResult(), geos::geomgraph::EdgeList::clearList(), computeGeometry(), computeLabelling(), computeLabelsFromDepths(), copyPoints(), edgeList, geos::operation::overlay::ElevationMatrix::elevate(), elevationMatrix, findResultAreaEdges(), geomFact, GEOS_CHECK_FOR_INTERRUPTS, geos::operation::GeometryGraphOperation::getArgGeometry(), geos::geomgraph::EdgeList::getEdges(), geos::geom::Geometry::getEnvelopeInternal(), geos::operation::overlay::PolygonBuilder::getPolygons(), graph, insertUniqueEdges(), geos::geom::Envelope::intersection(), geos::geom::PrecisionModel::isFloating(), labelIncompleteNodes(), geos::operation::GeometryGraphOperation::li, opDIFFERENCE, opINTERSECTION, ptLocator, replaceCollapsedEdges(), resultGeom, resultLineList, resultPointList, resultPolyList, geos::operation::GeometryGraphOperation::resultPrecisionModel, geos::algorithm::LineIntersector::toString(), and geos::util::GEOSException::what().
Referenced by getResultGeometry().
 {
   // Compute the target envelope
   const Envelope *env = nullptr;
   const Envelope *env0 = getArgGeometry(0)->getEnvelopeInternal();
   const Envelope *env1 = getArgGeometry(1)->getEnvelopeInternal();
   Envelope opEnv;
   if ( resultPrecisionModel->isFloating() )
   {
     // Envelope-based optimization only works in floating precision
     switch (opCode) {
       case opINTERSECTION:
         env0->intersection(*env1, opEnv);
         env = &opEnv;
         break;
       case opDIFFERENCE:
         opEnv = *env0;
         env = &opEnv;
         break;
       default:
         break;
     }
   }
   //env = 0; // WARNING: uncomment to disable env-optimization
   // copy points from input Geometries.
   // This ensures that any Point geometries
   // in the input are considered for inclusion in the result set
   copyPoints(0, env);
   copyPoints(1, env);
   GEOS_CHECK_FOR_INTERRUPTS();
   // node the input Geometries
   delete arg[0]->computeSelfNodes(li, false, env);
   GEOS_CHECK_FOR_INTERRUPTS();
   delete arg[1]->computeSelfNodes(li, false, env);
 #if GEOS_DEBUG
   cerr<<"OverlayOp::computeOverlay: computed SelfNodes"<<endl;
 #endif
   GEOS_CHECK_FOR_INTERRUPTS();
   // compute intersections between edges of the two input geometries
   delete arg[0]->computeEdgeIntersections(arg[1], &li, true, env);
 #if GEOS_DEBUG
   cerr<<"OverlayOp::computeOverlay: computed EdgeIntersections"<<endl;
   cerr<<"OverlayOp::computeOverlay: li: "<<li.toString()<<endl;
 #endif
   GEOS_CHECK_FOR_INTERRUPTS();
   vector<Edge*> baseSplitEdges;
   arg[0]->computeSplitEdges(&baseSplitEdges);
   GEOS_CHECK_FOR_INTERRUPTS();
   arg[1]->computeSplitEdges(&baseSplitEdges);
   GEOS_CHECK_FOR_INTERRUPTS();
   // add the noded edges to this result graph
   insertUniqueEdges(&baseSplitEdges, env);
   computeLabelsFromDepths();
   replaceCollapsedEdges();
   //Debug.println(edgeList);
   GEOS_CHECK_FOR_INTERRUPTS();
 #ifdef ENABLE_EDGE_NODING_VALIDATOR // {
   try
   {
 #ifdef GEOS_DEBUG_VALIDATION
     cout << "EdgeNodingValidator about to evaluate " << edgeList.getEdges().size() << " edges" << endl;
 #endif
     // Will throw TopologyException if noding is
     // found to be invalid
     EdgeNodingValidator::checkValid(edgeList.getEdges());
 #ifdef GEOS_DEBUG_VALIDATION
     cout << "EdgeNodingValidator accepted the noding" << endl;
 #endif
   }
   catch (const util::TopologyException& ex)
   {
 #ifdef GEOS_DEBUG_VALIDATION
     cout << "EdgeNodingValidator found noding invalid: " << ex.what() << endl;
 #endif
     // In the error scenario, the edgeList is not properly
     // deleted. Cannot add to the destructor of EdgeList
     // (as it should) because
     // "graph.addEdges(edgeList.getEdges());" below
     // takes over edgeList ownership in the success case.
     edgeList.clearList();
     throw ex;
   }
 #endif // ENABLE_EDGE_NODING_VALIDATOR }
   GEOS_CHECK_FOR_INTERRUPTS();
   graph.addEdges(edgeList.getEdges());
   GEOS_CHECK_FOR_INTERRUPTS();
   // this can throw TopologyException *
   computeLabelling();
   //Debug.printWatch();
   labelIncompleteNodes();
   //Debug.printWatch();
   //nodeMap.print(System.out);
   GEOS_CHECK_FOR_INTERRUPTS();
   /*
    * The ordering of building the result Geometries is important.
    * Areas must be built before lines, which must be built
    * before points.
    * This is so that lines which are covered by areas are not
    * included explicitly, and similarly for points.
    */
   findResultAreaEdges(opCode);
   cancelDuplicateResultEdges();
   GEOS_CHECK_FOR_INTERRUPTS();
   PolygonBuilder polyBuilder(geomFact);
   // might throw a TopologyException *
   polyBuilder.add(&graph);
   vector<Geometry*> *gv=polyBuilder.getPolygons();
   size_t gvsize=gv->size();
   resultPolyList=new vector<Polygon*>(gvsize);
   for(size_t i=0; i<gvsize; ++i) {
     Polygon* p = dynamic_cast<Polygon*>((*gv)[i]);
     (*resultPolyList)[i]=p;
   }
   delete gv;
   LineBuilder lineBuilder(this,geomFact,&ptLocator);
   resultLineList=lineBuilder.build(opCode);
   PointBuilder pointBuilder(this,geomFact,&ptLocator);
   resultPointList=pointBuilder.build(opCode);
   // gather the results from all calculations into a single
   // Geometry for the result set
   resultGeom=computeGeometry(resultPointList,resultLineList,resultPolyList);
   checkObviouslyWrongResult(opCode);
 #if USE_ELEVATION_MATRIX
   elevationMatrix->elevate(resultGeom);
 #endif // USE_ELEVATION_MATRIX
 }
void geos::operation::overlay::OverlayOp::copyPoints (int argIndex, const geom::Envelope * env = nullptr) private
Copy all nodes from an arg geometry into this graph.
The node label in the arg geometry overrides any previously computed label for that argIndex. (E.g. a node may be an intersection node with a previously computed label of BOUNDARY, but in the original arg Geometry it is actually in the interior due to the Boundary Determination Rule)
Definition at line 238 of file OverlayOp.cpp.
References geos::geomgraph::PlanarGraph::addNode(), geos::operation::GeometryGraphOperation::arg, geos::geom::Envelope::covers(), geos::geomgraph::Node::getCoordinate(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), graph, and geos::geomgraph::Node::setLabel().
Referenced by computeOverlay().
 {
 //#define GEOS_DEBUG_COPY_POINTS 1
 #ifdef GEOS_DEBUG_COPY_POINTS
   int copied = 0;
 #endif
   //env = 0; // WARNING: uncomment to disable env-optimization
   // TODO: set env to null if it covers arg geometry envelope
   NodeMap::container& nodeMap=arg[argIndex]->getNodeMap()->nodeMap;
   for ( NodeMap::const_iterator it=nodeMap.begin(), itEnd=nodeMap.end();
       it != itEnd; ++it )
   {
     Node* graphNode=it->second;
     assert(graphNode);
     const Coordinate &coord = graphNode->getCoordinate();
     if ( env && ! env->covers(coord) ) continue;
 #ifdef GEOS_DEBUG_COPY_POINTS
     ++copied;
 #endif
     Node* newNode=graph.addNode(coord);
     assert(newNode);
     newNode->setLabel(argIndex, graphNode->getLabel().getLocation(argIndex));
   }
 #ifdef GEOS_DEBUG_COPY_POINTS
   cerr << "Copied " << copied << " nodes out of " << nodeMap.size() << " for geom " << argIndex << endl;
 #endif
 }
void geos::operation::overlay::OverlayOp::findResultAreaEdges (OverlayOp::OpCode opCode) private
Find all edges whose label indicates that they are in the result area(s), according to the operation being performed.
Since we want polygon shells to be oriented CW, choose dirEdges with the interior of the result on the RHS. Mark them as being in the result. Interior Area edges are the result of dimensional collapses. They do not form part of the result area boundary.
Definition at line 546 of file OverlayOp.cpp.
References geos::geomgraph::PlanarGraph::getEdgeEnds(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), graph, geos::geomgraph::Label::isArea(), geos::geomgraph::DirectedEdge::isInteriorAreaEdge(), isResultOfOp(), and geos::geomgraph::DirectedEdge::setInResult().
Referenced by computeOverlay().
 {
   vector<EdgeEnd*> *ee=graph.getEdgeEnds();
   for(size_t i=0, e=ee->size(); i<e; ++i)
   {
     DirectedEdge *de=(DirectedEdge*) (*ee)[i];
     // mark all dirEdges with the appropriate label
     const Label& label = de->getLabel();
     if ( label.isArea()
       && !de->isInteriorAreaEdge()
       && isResultOfOp(label.getLocation(0,Position::RIGHT),
           label.getLocation(1,Position::RIGHT),
           opCode)
       )
     {
         de->setInResult(true);
         //Debug.print("in result "); Debug.println(de);
     }
   }
 }
const Geometry * geos::operation::GeometryGraphOperation::getArgGeometry (unsigned int i) const inherited
Definition at line 96 of file GeometryGraphOperation.cpp.
References geos::operation::GeometryGraphOperation::arg.
Referenced by computeOverlay(), and geos::operation::overlay::LineBuilder::labelIsolatedLine().
 {
   assert(i<arg.size());
   return arg[i]->getGeometry();
 }
double geos::operation::overlay::OverlayOp::getAverageZ (int targetIndex) private
Definition at line 478 of file OverlayOp.cpp.
References geos::operation::GeometryGraphOperation::arg, avgz, avgzcomputed, geos::geom::GEOS_POLYGON, and geos::geom::Geometry::getGeometryTypeId().
Referenced by labelIncompleteNode().
 {
   if ( avgzcomputed[targetIndex] ) return avgz[targetIndex];
   const Geometry *targetGeom = arg[targetIndex]->getGeometry();
   // OverlayOp::getAverageZ(int) called with a ! polygon
   assert(targetGeom->getGeometryTypeId() == GEOS_POLYGON);
   const Polygon* p = dynamic_cast<const Polygon*>(targetGeom);
   avgz[targetIndex] = getAverageZ(p);
   avgzcomputed[targetIndex] = true;
   return avgz[targetIndex];
 }
double geos::operation::overlay::OverlayOp::getAverageZ (const geom::Polygon * poly) static private
Definition at line 454 of file OverlayOp.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::CoordinateSequence::getSize(), and geos::geom::Coordinate::z.
 {
   double totz = 0.0;
   int zcount = 0;
   const CoordinateSequence *pts =
     poly->getExteriorRing()->getCoordinatesRO();
   size_t npts=pts->getSize();
   for (size_t i=0; i<npts; ++i)
   {
     const Coordinate &c = pts->getAt(i);
     if ( !ISNAN(c.z) )
     {
       totz += c.z;
       zcount++;
     }
   }
   if ( zcount ) return totz/zcount;
   else return DoubleNotANumber;
 }
geomgraph::PlanarGraph& geos::operation::overlay::OverlayOp::getGraph () inline
Gets the graph constructed to compute the overlay.
Returns
the overlay graph
Definition at line 148 of file OverlayOp.h.
Referenced by geos::operation::overlay::LineBuilder::collectLines(), and geos::operation::overlay::LineBuilder::findCoveredLineEdges().
 { return graph; }
Geometry * geos::operation::overlay::OverlayOp::getResultGeometry (OverlayOp::OpCode funcCode)
Gets the result of the overlay for a given overlay operation.
Note: this method can be called once only.
Parameters
overlayOpCode the overlay operation to perform
Returns
the compute result geometry
Exceptions
TopologyException if a robustness problem is encountered
Definition at line 184 of file OverlayOp.cpp.
References computeOverlay(), and resultGeom.
Referenced by overlayOp().
 {
   computeOverlay(funcCode);
   return resultGeom;
 }
void geos::operation::overlay::OverlayOp::insertUniqueEdge (geomgraph::Edge * e) protected
Insert an edge from one of the noded input graphs.
Checks edges that are inserted to see if an identical edge already exists. If so, the edge is not inserted, but its label is merged with the existing edge.
Definition at line 852 of file OverlayOp.cpp.
References geos::geomgraph::Depth::add(), geos::geomgraph::EdgeList::add(), dupEdges, edgeList, geos::geomgraph::EdgeList::findEqualEdge(), geos::geomgraph::Label::flip(), geos::geomgraph::Edge::getDepth(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Depth::isNull(), geos::geomgraph::Edge::isPointwiseEqual(), geos::geomgraph::Label::merge(), and geos::geomgraph::Edge::print().
Referenced by insertUniqueEdges().
 {
   //Debug.println(e);
 #if GEOS_DEBUG
   cerr<<"OverlayOp::insertUniqueEdge("<<e->print()<<")"<<endl;
 #endif
   //<FIX> MD 8 Oct 03  speed up identical edge lookup
   // fast lookup
   Edge *existingEdge = edgeList.findEqualEdge(e);
   // If an identical edge already exists, simply update its label
   if (existingEdge)
   {
 #if GEOS_DEBUG
     cerr<<"  found identical edge, should merge Z"<<endl;
 #endif
     Label& existingLabel = existingEdge->getLabel();
     Label labelToMerge = e->getLabel();
     // check if new edge is in reverse direction to existing edge
     // if so, must flip the label before merging it
     if (!existingEdge->isPointwiseEqual(e))
     {
       labelToMerge.flip();
     }
     Depth &depth = existingEdge->getDepth();
     // if this is the first duplicate found for this edge,
     // initialize the depths
     if (depth.isNull())
     {
       depth.add(existingLabel);
     }
     depth.add(labelToMerge);
     existingLabel.merge(labelToMerge);
     //Debug.print("inserted edge: "); Debug.println(e);
     //Debug.print("existing edge: "); Debug.println(existingEdge);
     dupEdges.push_back(e);
   }
   else
   {  // no matching existing edge was found
 #if GEOS_DEBUG
     cerr<<"  no matching existing edge"<<endl;
 #endif
     // add this new edge to the list of edges in this graph
     //e.setName(name+edges.size());
     //e.getDepth().add(e.getLabel());
     edgeList.add(e);
   }
 }
void geos::operation::overlay::OverlayOp::insertUniqueEdges (std::vector< geomgraph::Edge * > * edges, const geom::Envelope * env = nullptr) private
Definition at line 193 of file OverlayOp.cpp.
References dupEdges, geos::geomgraph::Edge::getEnvelope(), insertUniqueEdge(), geos::geom::Envelope::intersects(), and geos::geomgraph::Edge::print().
Referenced by computeOverlay().
 {
   for(size_t i=0, n=edges->size(); i<n; ++i) {
     Edge *e = (*edges)[i];
     if ( env && ! env->intersects(e->getEnvelope()) ) {
       dupEdges.push_back(e); // or could it be deleted directly ?
       continue;
     }
 #if GEOS_DEBUG
     cerr <<" "<< e->print() << endl;
 #endif
     insertUniqueEdge(e);
   }
 /*
   for_each(edges->begin(), edges->end(),
       bind1st(mem_fun(&OverlayOp::insertUniqueEdge), this));
 */
 }
bool geos::operation::overlay::OverlayOp::isCovered (const geom::Coordinate & coord, std::vector< geom::Geometry * > * geomList) private
Returns
true if the coord is located in the interior or boundary of a geometry in the list.
Definition at line 605 of file OverlayOp.cpp.
References geos::algorithm::PointLocator::locate(), and ptLocator.
Referenced by isCoveredByA(), and isCoveredByLA().
 {
   for(size_t i=0, n=geomList->size(); i<n; ++i)
   {
     Geometry *geom=(*geomList)[i];
     int loc=ptLocator.locate(coord,geom);
     if (loc!=Location::EXTERIOR) return true;
   }
   return false;
 }
bool geos::operation::overlay::OverlayOp::isCovered (const geom::Coordinate & coord, std::vector< geom::Polygon * > * geomList) private
Returns
true if the coord is located in the interior or boundary of a geometry in the list.
Definition at line 631 of file OverlayOp.cpp.
References geos::algorithm::PointLocator::locate(), and ptLocator.
 {
   for(size_t i=0, n=geomList->size(); i<n; ++i)
   {
     Geometry *geom=(Geometry*)(*geomList)[i];
     int loc=ptLocator.locate(coord,geom);
     if (loc!=Location::EXTERIOR) return true;
   }
   return false;
 }
bool geos::operation::overlay::OverlayOp::isCovered (const geom::Coordinate & coord, std::vector< geom::LineString * > * geomList) private
Returns
true if the coord is located in the interior or boundary of a geometry in the list.
Definition at line 618 of file OverlayOp.cpp.
References geos::algorithm::PointLocator::locate(), and ptLocator.
 {
   for(size_t i=0, n=geomList->size(); i<n; ++i)
   {
     Geometry *geom=(Geometry*)(*geomList)[i];
     int loc=ptLocator.locate(coord,geom);
     if (loc!=Location::EXTERIOR) return true;
   }
   return false;
 }
bool geos::operation::overlay::OverlayOp::isCoveredByA (const geom::Coordinate & coord)
This method is used to decide if an L edge should be included in the result or not.
Returns
true if the coord point is covered by a result Area geometry
Definition at line 597 of file OverlayOp.cpp.
References isCovered(), and resultPolyList.
Referenced by geos::operation::overlay::LineBuilder::findCoveredLineEdges().
 {
   if (isCovered(coord,resultPolyList)) return true;
   return false;
 }
bool geos::operation::overlay::OverlayOp::isCoveredByLA (const geom::Coordinate & coord)
This method is used to decide if a point node should be included in the result or not.
Returns
true if the coord point is covered by a result Line or Area geometry
Definition at line 588 of file OverlayOp.cpp.
References isCovered(), resultLineList, and resultPolyList.
 {
   if (isCovered(coord,resultLineList)) return true;
   if (isCovered(coord,resultPolyList)) return true;
   return false;
 }
bool geos::operation::overlay::OverlayOp::isResultOfOp (const geomgraph::Label & label, OverlayOp::OpCode opCode) static
Tests whether a point with a given topological Label relative to two geometries is contained in the result of overlaying the geometries using a given overlay operation.
The method handles arguments of Location#NONE correctly
Parameters
label the topological label of the point
opCode the code for the overlay operation to test
Returns
true if the label locations correspond to the overlayOpCode
Definition at line 98 of file OverlayOp.cpp.
References geos::geomgraph::Label::getLocation().
Referenced by geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::LineBuilder::collectLineEdge(), findResultAreaEdges(), and geos::operation::overlay::validate::OverlayResultValidator::isValidResult().
 {
   int loc0 = label.getLocation(0);
   int loc1 = label.getLocation(1);
   return isResultOfOp(loc0, loc1, opCode);
 }
bool geos::operation::overlay::OverlayOp::isResultOfOp (int loc0, int loc1, OverlayOp::OpCode opCode) static
This method will handle arguments of Location.NULL correctly.
Returns
true if the locations correspond to the opCode
Definition at line 108 of file OverlayOp.cpp.
 {
   if (loc0==Location::BOUNDARY) loc0=Location::INTERIOR;
   if (loc1==Location::BOUNDARY) loc1=Location::INTERIOR;
   switch (opCode) {
     case opINTERSECTION:
       return loc0==Location::INTERIOR && loc1==Location::INTERIOR;
     case opUNION:
       return loc0==Location::INTERIOR || loc1==Location::INTERIOR;
     case opDIFFERENCE:
       return loc0==Location::INTERIOR && loc1!=Location::INTERIOR;
     case opSYMDIFFERENCE:
       return (loc0==Location::INTERIOR && loc1!=Location::INTERIOR)
         || (loc0!=Location::INTERIOR && loc1==Location::INTERIOR);
   }
   return false;
 }
void geos::operation::overlay::OverlayOp::labelIncompleteNode (geomgraph::Node * n, int targetIndex) private
Label an isolated node with its relationship to the target geometry.
Definition at line 406 of file OverlayOp.cpp.
References geos::geomgraph::Node::addZ(), geos::operation::GeometryGraphOperation::arg, getAverageZ(), geos::geomgraph::Node::getCoordinate(), geos::geom::Geometry::getCoordinateDimension(), geos::geomgraph::GraphComponent::getLabel(), geos::algorithm::PointLocator::locate(), mergeZ(), poly, geos::geomgraph::Node::print(), ptLocator, and geos::geomgraph::Label::setLocation().
Referenced by labelIncompleteNodes().
 {
 #if GEOS_DEBUG
   cerr<<"OverlayOp::labelIncompleteNode("<<n->print()<<", "<<targetIndex<<")"<<endl;
 #endif
   const Geometry *targetGeom = arg[targetIndex]->getGeometry();
   int loc=ptLocator.locate(n->getCoordinate(), targetGeom);
   n->getLabel().setLocation(targetIndex, loc);
 #if GEOS_DEBUG
   cerr<<"   after location set: "<<n->print()<<endl;
 #endif
 #if COMPUTE_Z
   /*
    * If this node has been labeled INTERIOR of a line
    * or BOUNDARY of a polygon we must merge
    * Z values of the intersected segment.
    * The intersection point has been already computed
    * by LineIntersector invoked by CGAlgorithms::isOnLine
    * invoked by PointLocator.
    */
   // Only do this if input does have Z
   // See https://trac.osgeo.org/geos/ticket/811
   if(targetGeom->getCoordinateDimension() < 3 ) return;
   const LineString *line = dynamic_cast<const LineString *>(targetGeom);
   if ( loc == Location::INTERIOR && line )
   {
     mergeZ(n, line);
   }
   const Polygon *poly = dynamic_cast<const Polygon *>(targetGeom);
   if ( loc == Location::BOUNDARY && poly )
   {
     mergeZ(n, poly);
   }
 #if USE_INPUT_AVGZ
   if ( loc == Location::INTERIOR && poly )
   {
     n->addZ(getAverageZ(targetIndex));
   }
 #endif // USE_INPUT_AVGZ
 #endif // COMPUTE_Z
 }
void geos::operation::overlay::OverlayOp::labelIncompleteNodes () private
Incomplete nodes are nodes whose labels are incomplete.
(e.g. the location for one Geometry is NULL). These are either isolated nodes, or nodes which have edges from only a single Geometry incident on them.
Isolated nodes are found because nodes in one graph which don't intersect nodes in the other are not completely labelled by the initial process of adding nodes to the nodeList. To complete the labelling we need to check for nodes that lie in the interior of edges, and in the interior of areas.
When each node labelling is completed, the labelling of the incident edges is updated, to complete their labelling as well.
Definition at line 369 of file OverlayOp.cpp.
References geos::geomgraph::Node::getEdges(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::PlanarGraph::getNodeMap(), graph, geos::geomgraph::Node::isIsolated(), geos::geomgraph::Label::isNull(), labelIncompleteNode(), geos::geomgraph::NodeMap::nodeMap, and geos::geomgraph::DirectedEdgeStar::updateLabelling().
Referenced by computeOverlay().
 {
   NodeMap::container& nodeMap=graph.getNodeMap()->nodeMap;
 #if GEOS_DEBUG
   cerr<<"OverlayOp::labelIncompleteNodes() scanning "<<nodeMap.size()<<" nodes from map:"<<endl;
 #endif
   for ( NodeMap::const_iterator it=nodeMap.begin(), itEnd=nodeMap.end();
       it != itEnd; ++it )
   {
     Node *n=it->second;
     const Label& label = n->getLabel();
     if (n->isIsolated())
     {
       if (label.isNull(0))
       {
         labelIncompleteNode(n,0);
       }
       else
       {
         labelIncompleteNode(n, 1);
       }
     }
     // now update the labelling for the DirectedEdges incident on this node
     EdgeEndStar* ees = n->getEdges();
     assert( dynamic_cast<DirectedEdgeStar*>(ees) );
     DirectedEdgeStar* des = static_cast<DirectedEdgeStar*>(ees);
     des->updateLabelling(label);
     //((DirectedEdgeStar*)n->getEdges())->updateLabelling(label);
     //n.print(System.out);
   }
 }
void geos::operation::overlay::OverlayOp::mergeSymLabels () private
For nodes which have edges from only one Geometry incident on them, the previous step will have left their dirEdges with no labelling for the other Geometry. However, the sym dirEdge may have a labelling for the other Geometry, so merge the two labels.
Definition at line 313 of file OverlayOp.cpp.
References geos::geomgraph::Node::getEdges(), geos::geomgraph::PlanarGraph::getNodeMap(), graph, geos::geomgraph::NodeMap::nodeMap, and geos::geomgraph::Node::print().
Referenced by computeLabelling().
 {
   NodeMap::container& nodeMap=graph.getNodeMap()->nodeMap;
 #if GEOS_DEBUG
   cerr<<"OverlayOp::mergeSymLabels() scanning "<<nodeMap.size()<<" nodes from map:"<<endl;
 #endif
   for ( NodeMap::const_iterator it=nodeMap.begin(), itEnd=nodeMap.end();
       it != itEnd; ++it )
   {
     Node *node=it->second;
     EdgeEndStar* ees=node->getEdges();
     assert(dynamic_cast<DirectedEdgeStar*>(ees));
     static_cast<DirectedEdgeStar*>(ees)->mergeSymLabels();
     //((DirectedEdgeStar*)node->getEdges())->mergeSymLabels();
 #if GEOS_DEBUG
     cerr<<"     "<<node->print()<<endl;
 #endif
     //node.print(System.out);
   }
 }
int geos::operation::overlay::OverlayOp::mergeZ (geomgraph::Node * n, const geom::Polygon * poly) const private
Merge Z values of node with those of the segment or vertex in the given Polygon it is on.
Definition at line 495 of file OverlayOp.cpp.
References geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), and geos::geom::Polygon::getNumInteriorRing().
Referenced by labelIncompleteNode().
 {
   const LineString *ls;
   int found = 0;
   ls = poly->getExteriorRing();
   found = mergeZ(n, ls);
   if ( found ) return 1;
   for (size_t i=0, nr=poly->getNumInteriorRing(); i<nr; ++i)
   {
     ls = poly->getInteriorRingN(i);
     found = mergeZ(n, ls);
     if ( found ) return 1;
   }
   return 0;
 }
int geos::operation::overlay::OverlayOp::mergeZ (geomgraph::Node * n, const geom::LineString * line) const private
Merge Z values of node with those of the segment or vertex in the given LineString it is on.
Returns
1 if an intersection is found, 0 otherwise.
Definition at line 513 of file OverlayOp.cpp.
References geos::geomgraph::Node::addZ(), geos::algorithm::LineIntersector::computeIntersection(), geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Node::getCoordinate(), geos::geom::LineString::getCoordinatesRO(), geos::algorithm::LineIntersector::hasIntersection(), geos::operation::GeometryGraphOperation::li, geos::geom::CoordinateSequence::size(), and geos::geom::Coordinate::z.
 {
   const CoordinateSequence *pts = line->getCoordinatesRO();
   const Coordinate &p = n->getCoordinate();
   LineIntersector li;
   for(size_t i=1, size=pts->size(); i<size; ++i)
   {
     const Coordinate &p0=pts->getAt(i-1);
     const Coordinate &p1=pts->getAt(i);
     li.computeIntersection(p, p0, p1);
     if (li.hasIntersection())
     {
       if ( p == p0 )
       {
         n->addZ(p0.z);
       }
       else if ( p == p1 )
       {
         n->addZ(p1.z);
       }
       else
       {
         n->addZ(LineIntersector::interpolateZ(p,
           p0, p1));
       }
       return 1;
     }
   }
   return 0;
 }
Geometry * geos::operation::overlay::OverlayOp::overlayOp (const geom::Geometry * geom0, const geom::Geometry * geom1, OverlayOp::OpCode opCode) static
Computes an overlay operation for the given geometry arguments.
Parameters
geom0 the first geometry argument
geom1 the second geometry argument
opCode the code for the desired overlay operation
Returns
the result of the overlay operation
Exceptions
TopologyException if a robustness problem is encountered
Definition at line 88 of file OverlayOp.cpp.
References getResultGeometry().
 {
   OverlayOp gov(geom0, geom1);
   return gov.getResultGeometry(opCode);
 }
void geos::operation::overlay::OverlayOp::replaceCollapsedEdges () private
If edges which have undergone dimensional collapse are found, replace them with a new edge which is a L edge.
Definition at line 214 of file OverlayOp.cpp.
References edgeList, geos::geomgraph::Edge::getCollapsedEdge(), geos::geomgraph::EdgeList::getEdges(), and geos::geomgraph::Edge::isCollapsed().
Referenced by computeOverlay().
 {
   vector<Edge*>& edges=edgeList.getEdges();
   for(size_t i=0, nedges=edges.size(); i<nedges; ++i)
   {
     Edge *e=edges[i];
     assert(e);
     if (e->isCollapsed())
     {
 #if GEOS_DEBUG
     cerr << " replacing collapsed edge " << i << endl;
 #endif // GEOS_DEBUG
       //Debug.print(e);
       edges[i]=e->getCollapsedEdge();
       // should we keep this alive some more ?
       delete e;
     }
   }
 }
void geos::operation::GeometryGraphOperation::setComputationPrecision (const geom::PrecisionModel * pm) protected inherited
Definition at line 104 of file GeometryGraphOperation.cpp.
References geos::operation::GeometryGraphOperation::li, geos::operation::GeometryGraphOperation::resultPrecisionModel, and geos::algorithm::LineIntersector::setPrecisionModel().
Referenced by geos::operation::GeometryGraphOperation::GeometryGraphOperation().
 {
   assert(pm);
   resultPrecisionModel=pm;
   li.setPrecisionModel(resultPrecisionModel);
 }
void geos::operation::overlay::OverlayOp::updateNodeLabelling () private
Definition at line 338 of file OverlayOp.cpp.
References geos::geomgraph::Node::getEdges(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::DirectedEdgeStar::getLabel(), geos::geomgraph::PlanarGraph::getNodeMap(), graph, geos::geomgraph::Label::merge(), geos::geomgraph::NodeMap::nodeMap, and geos::geomgraph::Node::print().
Referenced by computeLabelling().
 {
   // update the labels for nodes
   // The label for a node is updated from the edges incident on it
   // (Note that a node may have already been labelled
   // because it is a point in one of the input geometries)
   NodeMap::container& nodeMap=graph.getNodeMap()->nodeMap;
 #if GEOS_DEBUG
   cerr << "OverlayOp::updateNodeLabelling() scanning "
        << nodeMap.size() << " nodes from map:" << endl;
 #endif
   for ( NodeMap::const_iterator it=nodeMap.begin(), itEnd=nodeMap.end();
       it != itEnd; ++it )
   {
     Node *node=it->second;
     EdgeEndStar* ees = node->getEdges();
     assert( dynamic_cast<DirectedEdgeStar*>(ees) );
     DirectedEdgeStar* des = static_cast<DirectedEdgeStar*>(ees);
     Label &lbl = des->getLabel();
     node->getLabel().merge(lbl);
 #if GEOS_DEBUG
     cerr<<"     "<<node->print()<<endl;
 #endif
   }
 }
Member Data Documentation
std::vector<geomgraph::GeometryGraph*> geos::operation::GeometryGraphOperation::arg protected inherited
The operation args into an array so they can be accessed by index.
Definition at line 78 of file GeometryGraphOperation.h.
Referenced by checkObviouslyWrongResult(), computeLabelling(), computeOverlay(), copyPoints(), geos::operation::GeometryGraphOperation::GeometryGraphOperation(), geos::operation::GeometryGraphOperation::getArgGeometry(), getAverageZ(), labelIncompleteNode(), and geos::operation::GeometryGraphOperation::~GeometryGraphOperation().
double geos::operation::overlay::OverlayOp::avgz[2] private
Average Z of input geometries
Definition at line 359 of file OverlayOp.h.
Referenced by getAverageZ(), and OverlayOp().
bool geos::operation::overlay::OverlayOp::avgzcomputed[2] private
Definition at line 360 of file OverlayOp.h.
Referenced by getAverageZ(), and OverlayOp().
std::vector<geomgraph::Edge *> geos::operation::overlay::OverlayOp::dupEdges private
Caches for memory management.
Definition at line 341 of file OverlayOp.h.
Referenced by insertUniqueEdge(), insertUniqueEdges(), and ~OverlayOp().
geomgraph::EdgeList geos::operation::overlay::OverlayOp::edgeList private
Definition at line 194 of file OverlayOp.h.
Referenced by computeLabelling(), computeLabelsFromDepths(), computeOverlay(), insertUniqueEdge(), and replaceCollapsedEdges().
ElevationMatrix* geos::operation::overlay::OverlayOp::elevationMatrix private
Definition at line 365 of file OverlayOp.h.
Referenced by computeOverlay(), OverlayOp(), and ~OverlayOp().
const geom::GeometryFactory* geos::operation::overlay::OverlayOp::geomFact private
Definition at line 188 of file OverlayOp.h.
Referenced by computeGeometry(), and computeOverlay().
geomgraph::PlanarGraph geos::operation::overlay::OverlayOp::graph private
Definition at line 192 of file OverlayOp.h.
Referenced by cancelDuplicateResultEdges(), computeLabelling(), computeOverlay(), copyPoints(), findResultAreaEdges(), labelIncompleteNodes(), mergeSymLabels(), and updateNodeLabelling().
algorithm::LineIntersector geos::operation::GeometryGraphOperation::li protected inherited
Definition at line 71 of file GeometryGraphOperation.h.
Referenced by computeOverlay(), mergeZ(), and geos::operation::GeometryGraphOperation::setComputationPrecision().
algorithm::PointLocator geos::operation::overlay::OverlayOp::ptLocator private
Definition at line 186 of file OverlayOp.h.
Referenced by computeOverlay(), isCovered(), and labelIncompleteNode().
geom::Geometry* geos::operation::overlay::OverlayOp::resultGeom private
Definition at line 190 of file OverlayOp.h.
Referenced by checkObviouslyWrongResult(), computeOverlay(), and getResultGeometry().
std::vector<geom::LineString*>* geos::operation::overlay::OverlayOp::resultLineList private
Definition at line 198 of file OverlayOp.h.
Referenced by computeOverlay(), isCoveredByLA(), and ~OverlayOp().
std::vector<geom::Point*>* geos::operation::overlay::OverlayOp::resultPointList private
Definition at line 200 of file OverlayOp.h.
Referenced by computeOverlay(), and ~OverlayOp().
std::vector<geom::Polygon*>* geos::operation::overlay::OverlayOp::resultPolyList private
Definition at line 196 of file OverlayOp.h.
Referenced by computeOverlay(), isCoveredByA(), isCoveredByLA(), and ~OverlayOp().
const geom::PrecisionModel* geos::operation::GeometryGraphOperation::resultPrecisionModel protected inherited
Definition at line 73 of file GeometryGraphOperation.h.
Referenced by checkObviouslyWrongResult(), computeOverlay(), and geos::operation::GeometryGraphOperation::setComputationPrecision().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/OverlayOp.h
/home/vicky/potree/geos/vicky/src/operation/overlay/OverlayOp.cpp