GEOS: geos::operation::overlay::PointBuilder Class Reference
geos::operation::overlay::PointBuilder Class Reference
Constructs geom::Point s from the nodes of an overlay graph.
#include <PointBuilder.h>
Public Member Functions
PointBuilder (OverlayOp *newOp, const geom::GeometryFactory *newGeometryFactory, algorithm::PointLocator *newPtLocator=nullptr)
std::vector< geom::Point * > * build (OverlayOp::OpCode opCode)
Private Member Functions
void extractNonCoveredResultNodes (OverlayOp::OpCode opCode)
void filterCoveredNodeToPoint (const geomgraph::Node *)
Private Attributes
OverlayOp * op
const geom::GeometryFactory * geometryFactory
std::vector< geom::Point * > * resultPointList
Detailed Description
Constructs geom::Point s from the nodes of an overlay graph.
Definition at line 56 of file PointBuilder.h.
Constructor & Destructor Documentation
geos::operation::overlay::PointBuilder::PointBuilder (OverlayOp * newOp, const geom::GeometryFactory * newGeometryFactory, algorithm::PointLocator * newPtLocator = nullptr) inline
Definition at line 83 of file PointBuilder.h.
References geos::ignore_unused_variable_warning().
     :
     op(newOp),
     geometryFactory(newGeometryFactory),
     resultPointList(new std::vector<geom::Point *>())
   {
         ::geos::ignore_unused_variable_warning(newPtLocator);
     }
Member Function Documentation
vector< Point * > * geos::operation::overlay::PointBuilder::build (OverlayOp::OpCode opCode)
Returns
a list of the Points in the result of the specified overlay operation
Definition at line 47 of file PointBuilder.cpp.
Referenced by geos::operation::overlay::OverlayOp::computeOverlay().
 {
   extractNonCoveredResultNodes(opCode);
   return resultPointList;
 }
void geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes (OverlayOp::OpCode opCode) private
For nodes on edges, only INTERSECTION can result in edge nodes being included even if none of their incident edges are included
Definition at line 62 of file PointBuilder.cpp.
References geos::geomgraph::EdgeEndStar::getDegree(), geos::geomgraph::Node::getEdges(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Node::isIncidentEdgeInResult(), and geos::geomgraph::GraphComponent::isInResult().
 {
   map<Coordinate*,Node*,CoordinateLessThen> &nodeMap =
     op->getGraph().getNodeMap()->nodeMap;
   map<Coordinate*,Node*,CoordinateLessThen>::iterator it=nodeMap.begin();
   for (; it!=nodeMap.end(); ++it)
   {
     Node *n=it->second;
     // filter out nodes which are known to be in the result
     if (n->isInResult()) continue;
     // if an incident edge is in the result, then
     // the node coordinate is included already
     if (n->isIncidentEdgeInResult()) continue;
     if ( n->getEdges()->getDegree() == 0 ||
       opCode == OverlayOp::opINTERSECTION )
     {
       const Label& label=n->getLabel();
       if (OverlayOp::isResultOfOp(label, opCode))
         filterCoveredNodeToPoint(n);
     }
   }
 }
void geos::operation::overlay::PointBuilder::filterCoveredNodeToPoint (const geomgraph::Node * n) private
Definition at line 95 of file PointBuilder.cpp.
References geos::geomgraph::Node::getCoordinate().
 {
   const Coordinate& coord=n->getCoordinate();
   if(!op->isCoveredByLA(coord)) {
     Point *pt=geometryFactory->createPoint(coord);
     resultPointList->push_back(pt);
   }
 }
Member Data Documentation
const geom::GeometryFactory* geos::operation::overlay::PointBuilder::geometryFactory private
Definition at line 60 of file PointBuilder.h.
OverlayOp* geos::operation::overlay::PointBuilder::op private
Definition at line 59 of file PointBuilder.h.
std::vector<geom::Point*>* geos::operation::overlay::PointBuilder::resultPointList private
Allocated a construction time, but not owned. Make sure you take ownership of it, getting it from build()
Definition at line 79 of file PointBuilder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/PointBuilder.h
/home/vicky/potree/geos/vicky/src/operation/overlay/PointBuilder.cpp