GEOS: geos::algorithm::distance::PointPairDistance Class Reference
geos::algorithm::distance::PointPairDistance Class Reference
#include <PointPairDistance.h>
Public Member Functions
PointPairDistance ()
void initialize ()
void initialize (const geom::Coordinate &p0, const geom::Coordinate &p1)
double getDistance () const
const std::vector< geom::Coordinate > & getCoordinates () const
const geom::Coordinate & getCoordinate (unsigned int i) const
void setMaximum (const PointPairDistance &ptDist)
void setMaximum (const geom::Coordinate &p0, const geom::Coordinate &p1)
void setMinimum (const PointPairDistance &ptDist)
void setMinimum (const geom::Coordinate &p0, const geom::Coordinate &p1)
bool getIsNull ()
Private Member Functions
void initialize (const geom::Coordinate &p0, const geom::Coordinate &p1, double dist)
Private Attributes
std::vector< geom::Coordinate > pt
double distance
bool isNull
Detailed Description
Contains a pair of points and the distance between them. Provides methods to update with a new point pair with either maximum or minimum distance.
Definition at line 37 of file PointPairDistance.h.
Constructor & Destructor Documentation
geos::algorithm::distance::PointPairDistance::PointPairDistance () inline
Definition at line 41 of file PointPairDistance.h.
References pt.
     :
     pt(2),
     distance(DoubleNotANumber),
     isNull(true)
   {
     assert(pt.size() == 2);
   }
Member Function Documentation
const geom::Coordinate& geos::algorithm::distance::PointPairDistance::getCoordinate (unsigned int i) const inline
Definition at line 73 of file PointPairDistance.h.
References pt.
   {
     assert(i<pt.size());
     return pt[i];
   }
const std::vector<geom::Coordinate>& geos::algorithm::distance::PointPairDistance::getCoordinates () const inline
Definition at line 68 of file PointPairDistance.h.
References pt.
   {
     return pt;
   }
double geos::algorithm::distance::PointPairDistance::getDistance () const inline
Definition at line 63 of file PointPairDistance.h.
References distance.
Referenced by geos::algorithm::distance::DiscreteFrechetDistance::getFrecheDistance().
   {
     return distance;
   }
bool geos::algorithm::distance::PointPairDistance::getIsNull () inline
Definition at line 111 of file PointPairDistance.h.
References isNull.
   {
     return isNull;
   }
void geos::algorithm::distance::PointPairDistance::initialize () inline
Definition at line 50 of file PointPairDistance.h.
References isNull.
Referenced by geos::algorithm::distance::DiscreteFrechetDistance::getFrecheDistance(), setMaximum(), and setMinimum().
   {
     isNull = true;
   }
void geos::algorithm::distance::PointPairDistance::initialize (const geom::Coordinate & p0, const geom::Coordinate & p1) inline
Definition at line 55 of file PointPairDistance.h.
References geos::geom::Coordinate::distance(), distance, isNull, and pt.
   {
     pt[0] = p0;
     pt[1] = p1;
     distance = p0.distance(p1);
     isNull = false;
   }
void geos::algorithm::distance::PointPairDistance::initialize (const geom::Coordinate & p0, const geom::Coordinate & p1, double dist) inline private
Initializes the points, avoiding recomputing the distance.
Parameters
p0
p1
dist the distance between p0 and p1
Definition at line 124 of file PointPairDistance.h.
References distance, isNull, and pt.
   {
     pt[0] = p0;
     pt[1] = p1;
     distance = dist;
     isNull = false;
   }
void geos::algorithm::distance::PointPairDistance::setMaximum (const PointPairDistance & ptDist) inline
Definition at line 79 of file PointPairDistance.h.
References pt.
Referenced by geos::algorithm::distance::DiscreteHausdorffDistance::computeOrientedDistance().
   {
     setMaximum(ptDist.pt[0], ptDist.pt[1]);
   }
void geos::algorithm::distance::PointPairDistance::setMaximum (const geom::Coordinate & p0, const geom::Coordinate & p1) inline
Definition at line 84 of file PointPairDistance.h.
References geos::geom::Coordinate::distance(), distance, initialize(), and isNull.
   {
     if (isNull) {
       initialize(p0, p1);
       return;
     }
     double dist = p0.distance(p1);
     if (dist > distance)
       initialize(p0, p1, dist);
   }
void geos::algorithm::distance::PointPairDistance::setMinimum (const PointPairDistance & ptDist) inline
Definition at line 95 of file PointPairDistance.h.
References pt.
Referenced by geos::algorithm::distance::DistanceToPoint::computeDistance().
   {
     setMinimum(ptDist.pt[0], ptDist.pt[1]);
   }
void geos::algorithm::distance::PointPairDistance::setMinimum (const geom::Coordinate & p0, const geom::Coordinate & p1) inline
Definition at line 100 of file PointPairDistance.h.
References geos::geom::Coordinate::distance(), distance, initialize(), and isNull.
   {
     if (isNull) {
       initialize(p0, p1);
       return;
     }
     double dist = p0.distance(p1);
     if (dist < distance)
       initialize(p0, p1, dist);
   }
Member Data Documentation
double geos::algorithm::distance::PointPairDistance::distance private
Definition at line 135 of file PointPairDistance.h.
Referenced by getDistance(), initialize(), setMaximum(), and setMinimum().
bool geos::algorithm::distance::PointPairDistance::isNull private
Definition at line 137 of file PointPairDistance.h.
Referenced by getIsNull(), initialize(), setMaximum(), and setMinimum().
std::vector<geom::Coordinate> geos::algorithm::distance::PointPairDistance::pt private
Definition at line 133 of file PointPairDistance.h.
Referenced by getCoordinate(), getCoordinates(), initialize(), PointPairDistance(), setMaximum(), and setMinimum().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/algorithm/distance/PointPairDistance.h