GEOS: geos::operation::IsSimpleOp Class Reference
geos::operation::IsSimpleOp Class Reference
Tests whether a Geometry is simple.
#include <IsSimpleOp.h>
Public Member Functions
IsSimpleOp ()
Creates a simplicity checker using the default SFS Mod-2 Boundary Node Rule.
IsSimpleOp (const geom::Geometry &geom)
Creates a simplicity checker using the default SFS Mod-2 Boundary Node Rule.
IsSimpleOp (const geom::Geometry &geom, const algorithm::BoundaryNodeRule &boundaryNodeRule)
Creates a simplicity checker using a given algorithm::BoundaryNodeRule.
bool isSimple ()
const geom::Coordinate * getNonSimpleLocation () const
bool isSimple (const geom::LineString *geom)
bool isSimple (const geom::MultiLineString *geom)
bool isSimple (const geom::MultiPoint *mp)
bool isSimpleLinearGeometry (const geom::Geometry *geom)
Private Member Functions
bool hasNonEndpointIntersection (geomgraph::GeometryGraph &graph)
bool hasClosedEndpointIntersection (geomgraph::GeometryGraph &graph)
void addEndpoint (std::map< const geom::Coordinate *, EndpointInfo *, geom::CoordinateLessThen > &endPoints, const geom::Coordinate *p, bool isClosed)
bool isSimpleMultiPoint (const geom::MultiPoint &mp)
Private Attributes
bool isClosedEndpointsInInterior
const geom::Geometry * geom
std::unique_ptr< geom::Coordinate > nonSimpleLocation
Detailed Description
Tests whether a Geometry is simple.
In general, the SFS specification of simplicity follows the rule:
A Geometry is simple if and only if the only self-intersections are at boundary points.
This definition relies on the definition of boundary points. The SFS uses the Mod-2 rule to determine which points are on the boundary of lineal geometries, but this class supports using other BoundaryNodeRules as well.
Simplicity is defined for each Geometry subclass as follows:
Valid polygonal geometries are simple by definition, so isSimple trivially returns true. (Hint: in order to check if a polygonal geometry has self-intersections, use Geometry::isValid).
Linear geometries are simple iff they do not self-intersect at points other than boundary points. (Using the Mod-2 rule, this means that closed linestrings cannot be touched at their endpoints, since these are interior points, not boundary points).
Zero-dimensional geometries (points) are simple iff they have no repeated points.
Empty Geometrys are always simple
See also
algorithm::BoundaryNodeRule
Definition at line 93 of file IsSimpleOp.h.
Constructor & Destructor Documentation
geos::operation::IsSimpleOp::IsSimpleOp ()
Creates a simplicity checker using the default SFS Mod-2 Boundary Node Rule.
Deprecated:
use IsSimpleOp(Geometry)
Definition at line 81 of file IsSimpleOp.cpp.
   :
   isClosedEndpointsInInterior(true),
   geom(nullptr),
   nonSimpleLocation()
 {}
geos::operation::IsSimpleOp::IsSimpleOp (const geom::Geometry & geom)
Creates a simplicity checker using the default SFS Mod-2 Boundary Node Rule.
Parameters
geom The geometry to test. Will store a reference: keep it alive.
Definition at line 89 of file IsSimpleOp.cpp.
   :
   isClosedEndpointsInInterior(true),
   geom(&g),
   nonSimpleLocation()
 {}
geos::operation::IsSimpleOp::IsSimpleOp (const geom::Geometry & geom, const algorithm::BoundaryNodeRule & boundaryNodeRule)
Creates a simplicity checker using a given algorithm::BoundaryNodeRule.
Parameters
geom the geometry to test
boundaryNodeRule the rule to use.
Definition at line 97 of file IsSimpleOp.cpp.
   :
   isClosedEndpointsInInterior( ! boundaryNodeRule.isInBoundary(2) ),
   geom(&g),
   nonSimpleLocation()
 {}
Member Function Documentation
void geos::operation::IsSimpleOp::addEndpoint (std::map< const geom::Coordinate *, EndpointInfo *, geom::CoordinateLessThen > & endPoints, const geom::Coordinate * p, bool isClosed) private
Add an endpoint to the map, creating an entry for it if none exists
Definition at line 265 of file IsSimpleOp.cpp.
References geos::operation::EndpointInfo::addEndpoint().
Referenced by hasClosedEndpointIntersection().
 {
   map<const Coordinate*,EndpointInfo*,CoordinateLessThen>::iterator it=endPoints.find(p);
   EndpointInfo *eiInfo;
   if (it==endPoints.end()) {
     eiInfo=nullptr;
   } else {
     eiInfo=it->second;
   }
   if (eiInfo==nullptr) {
     eiInfo=new EndpointInfo(*p);
     endPoints[p]=eiInfo;
   }
   eiInfo->addEndpoint(isClosed);
 }
const geom::Coordinate* geos::operation::IsSimpleOp::getNonSimpleLocation () const inline
Gets a coordinate for the location where the geometry fails to be simple. (i.e. where it has a non-boundary self-intersection). isSimple must be called before this method is called.
Returns
a coordinate for the location of the non-boundary self-intersection. Ownership retained.
the null coordinate if the geometry is simple
Definition at line 142 of file IsSimpleOp.h.
   {
     return nonSimpleLocation.get();
   }
bool geos::operation::IsSimpleOp::hasClosedEndpointIntersection (geomgraph::GeometryGraph & graph) private
Tests that no edge intersection is the endpoint of a closed line. This ensures that closed lines are not touched at their endpoint, which is an interior point according to the Mod-2 rule To check this we compute the degree of each endpoint. The degree of endpoints of closed lines must be exactly 2.
Definition at line 223 of file IsSimpleOp.cpp.
References addEndpoint(), geos::operation::EndpointInfo::degree, geos::operation::EndpointInfo::getCoordinate(), geos::geomgraph::Edge::getCoordinate(), geos::geomgraph::GeometryGraph::getEdges(), geos::geomgraph::Edge::getNumPoints(), geos::operation::EndpointInfo::isClosed, geos::geomgraph::Edge::isClosed(), and nonSimpleLocation.
Referenced by isSimpleLinearGeometry().
 {
   map<const Coordinate*,EndpointInfo*,CoordinateLessThen> endPoints;
   vector<Edge*> *edges=graph.getEdges();
   for (vector<Edge*>::iterator i=edges->begin();i<edges->end();i++) {
     Edge *e=*i;
     //int maxSegmentIndex=e->getMaximumSegmentIndex();
     bool isClosed=e->isClosed();
     const Coordinate *p0=&e->getCoordinate(0);
     addEndpoint(endPoints,p0,isClosed);
     const Coordinate *p1=&e->getCoordinate(e->getNumPoints()-1);
     addEndpoint(endPoints,p1,isClosed);
   }
   map<const Coordinate*,EndpointInfo*,CoordinateLessThen>::iterator it=endPoints.begin();
   for (; it!=endPoints.end(); ++it) {
     EndpointInfo *eiInfo=it->second;
     if (eiInfo->isClosed && eiInfo->degree!=2) {
       nonSimpleLocation.reset(
         new Coordinate( eiInfo->getCoordinate() )
       );
       it=endPoints.begin();
       for (; it!=endPoints.end(); ++it) {
         EndpointInfo *ep=it->second;
         delete ep;
       }
                 return true;
     }
   }
   it=endPoints.begin();
   for (; it!=endPoints.end(); ++it) {
     EndpointInfo *ep=it->second;
     delete ep;
   }
   return false;
 }
bool geos::operation::IsSimpleOp::hasNonEndpointIntersection (geomgraph::GeometryGraph & graph) private
For all edges, check if there are any intersections which are NOT at an endpoint. The Geometry is not simple if there are intersections not at endpoints.
Definition at line 198 of file IsSimpleOp.cpp.
References geos::geomgraph::EdgeIntersectionList::begin(), geos::geomgraph::EdgeIntersectionList::end(), geos::geomgraph::EdgeIntersection::getCoordinate(), geos::geomgraph::Edge::getEdgeIntersectionList(), geos::geomgraph::GeometryGraph::getEdges(), geos::geomgraph::Edge::getMaximumSegmentIndex(), geos::geomgraph::EdgeIntersection::isEndPoint(), and nonSimpleLocation.
Referenced by isSimpleLinearGeometry().
 {
   vector<Edge*> *edges=graph.getEdges();
   for (vector<Edge*>::iterator i=edges->begin();i<edges->end();i++) {
     Edge *e=*i;
     int maxSegmentIndex=e->getMaximumSegmentIndex();
     EdgeIntersectionList &eiL=e->getEdgeIntersectionList();
     for ( EdgeIntersectionList::iterator eiIt=eiL.begin(),
       eiEnd=eiL.end(); eiIt!=eiEnd; ++eiIt )
     {
       EdgeIntersection *ei=*eiIt;
       if (!ei->isEndPoint(maxSegmentIndex))
       {
         nonSimpleLocation.reset(
           new Coordinate(ei->getCoordinate())
         );
         return true;
       }
     }
   }
   return false;
 }
bool geos::operation::IsSimpleOp::isSimple ()
Tests whether the geometry is simple.
Returns
true if the geometry is simple
Definition at line 107 of file IsSimpleOp.cpp.
References geom, isSimpleLinearGeometry(), isSimpleMultiPoint(), and nonSimpleLocation.
Referenced by geos::geom::check_valid(), and geos::geom::Geometry::isSimple().
 {
   nonSimpleLocation.reset();
   if ( dynamic_cast<const LineString*>(geom) )
     return isSimpleLinearGeometry(geom);
   if ( dynamic_cast<const MultiLineString*>(geom) )
     return isSimpleLinearGeometry(geom);
   const MultiPoint* mp = dynamic_cast<const MultiPoint*>(geom);
   if ( mp ) return isSimpleMultiPoint(*mp);
   // all other geometry types are simple by definition
   return true;
 }
bool geos::operation::IsSimpleOp::isSimple (const geom::LineString * geom)
Reports whether a geom::LineString is simple.
Parameters
geom the lineal geometry to test
Returns
true if the geometry is simple
Deprecated:
use isSimple()
Definition at line 127 of file IsSimpleOp.cpp.
References isSimpleLinearGeometry().
 {
   return isSimpleLinearGeometry(geom);
 }
bool geos::operation::IsSimpleOp::isSimple (const geom::MultiLineString * geom)
Reports whether a geom::MultiLineString is simple.
Parameters
geom the lineal geometry to test
Returns
true if the geometry is simple
Deprecated:
use isSimple()
Definition at line 134 of file IsSimpleOp.cpp.
References isSimpleLinearGeometry().
 {
   return isSimpleLinearGeometry(geom);
 }
bool geos::operation::IsSimpleOp::isSimple (const geom::MultiPoint * mp)
A MultiPoint is simple iff it has no repeated points
Deprecated:
use isSimple()
Definition at line 141 of file IsSimpleOp.cpp.
References isSimpleMultiPoint().
 {
   return isSimpleMultiPoint(*mp);
 }
bool geos::operation::IsSimpleOp::isSimpleLinearGeometry (const geom::Geometry * geom)
Definition at line 169 of file IsSimpleOp.cpp.
References geos::geomgraph::GeometryGraph::computeSelfNodes(), hasClosedEndpointIntersection(), hasNonEndpointIntersection(), isClosedEndpointsInInterior, geos::geom::Geometry::isEmpty(), and nonSimpleLocation.
Referenced by isSimple().
 {
   if (geom->isEmpty()) return true;
   GeometryGraph graph(0,geom);
   LineIntersector li;
   std::unique_ptr<SegmentIntersector> si (graph.computeSelfNodes(&li,true));
   // if no self-intersection, must be simple
   if (!si->hasIntersection()) return true;
   if (si->hasProperIntersection())
   {
     nonSimpleLocation.reset(
       new Coordinate(si->getProperIntersectionPoint())
     );
     return false;
   }
   if (hasNonEndpointIntersection(graph)) return false;
   if ( isClosedEndpointsInInterior ) {
     if (hasClosedEndpointIntersection(graph)) return false;
   }
   return true;
 }
bool geos::operation::IsSimpleOp::isSimpleMultiPoint (const geom::MultiPoint & mp) private
Definition at line 148 of file IsSimpleOp.cpp.
References geos::geom::Point::getCoordinate(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::geom::GeometryCollection::isEmpty(), and nonSimpleLocation.
Referenced by isSimple().
 {
   if (mp.isEmpty()) return true;
   set<const Coordinate*, CoordinateLessThen> points;
   for (std::size_t i=0, n=mp.getNumGeometries(); i<n; ++i)
   {
     const Point *pt = dynamic_cast<const Point*>(mp.getGeometryN(i));
     assert(pt);
     const Coordinate *p=pt->getCoordinate();
     if (points.find(p) != points.end())
     {
       nonSimpleLocation.reset(new Coordinate(*p));
       return false;
     }
     points.insert(p);
   }
   return true;
 }
Member Data Documentation
const geom::Geometry* geos::operation::IsSimpleOp::geom private
Definition at line 207 of file IsSimpleOp.h.
Referenced by isSimple().
bool geos::operation::IsSimpleOp::isClosedEndpointsInInterior private
Definition at line 203 of file IsSimpleOp.h.
Referenced by isSimpleLinearGeometry().
std::unique_ptr<geom::Coordinate> geos::operation::IsSimpleOp::nonSimpleLocation private
Definition at line 209 of file IsSimpleOp.h.
Referenced by hasClosedEndpointIntersection(), hasNonEndpointIntersection(), isSimple(), isSimpleLinearGeometry(), and isSimpleMultiPoint().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/IsSimpleOp.h
/home/vicky/potree/geos/vicky/src/operation/IsSimpleOp.cpp