GEOS: geos::noding::snapround::HotPixel Class Reference
geos::noding::snapround::HotPixel Class Reference
Implements a "hot pixel" as used in the Snap Rounding algorithm.
#include <HotPixel.h>
Public Member Functions
HotPixel (const geom::Coordinate &pt, double scaleFact, algorithm::LineIntersector &li)
const geom::Coordinate & getCoordinate () const
Return reference to original Coordinate (the one provided at construction time)
const geom::Envelope & getSafeEnvelope () const
Returns a "safe" envelope that is guaranteed to contain the hot pixel. Keeps ownership of it.
bool intersects (const geom::Coordinate &p0, const geom::Coordinate &p1) const
bool addSnappedNode (NodedSegmentString &segStr, std::size_t segIndex)
Private Member Functions
void initCorners (const geom::Coordinate &pt)
double scale (double val) const
void copyScaled (const geom::Coordinate &p, geom::Coordinate &pScaled) const
bool intersectsToleranceSquare (const geom::Coordinate &p0, const geom::Coordinate &p1) const
Tests whether the segment p0-p1 intersects the hot pixel tolerance square.
bool intersectsPixelClosure (const geom::Coordinate &p0, const geom::Coordinate &p1)
Test whether the given segment intersects the closure of this hot pixel.
bool intersectsScaled (const geom::Coordinate &p0, const geom::Coordinate &p1) const
HotPixel (const HotPixel &other)=delete
HotPixel & operator= (const HotPixel &rhs)=delete
Private Attributes
algorithm::LineIntersector & li
geom::Coordinate pt
const geom::Coordinate & originalPt
geom::Coordinate ptScaled
geom::Coordinate p0Scaled
geom::Coordinate p1Scaled
double scaleFactor
double minx
double maxx
double miny
double maxy
std::vector< geom::Coordinate > corner
The corners of the hot pixel.
std::unique_ptr< geom::Envelope > safeEnv
Owned by this class, constructed on demand.
Detailed Description
Implements a "hot pixel" as used in the Snap Rounding algorithm.
A hot pixel contains the interior of the tolerance square and the boundary minus the top and right segments.
The hot pixel operations are all computed in the integer domain to avoid rounding problems.
Definition at line 62 of file HotPixel.h.
Constructor & Destructor Documentation
geos::noding::snapround::HotPixel::HotPixel (const HotPixel & other) private delete
geos::noding::snapround::HotPixel::HotPixel (const geom::Coordinate & pt, double scaleFact, algorithm::LineIntersector & li)
Creates a new hot pixel.
Parameters
pt the coordinate at the centre of the pixel. Will be kept by reference, so make sure to keep it alive.
scaleFact the scaleFactor determining the pixel size
li the intersector to use for testing intersection with line segments
Definition at line 40 of file HotPixel.cpp.
References initCorners(), pt, scale(), scaleFactor, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
   :
   li(newLi),
   pt(newPt),
   originalPt(newPt),
   scaleFactor(newScaleFactor)
 {
   if (scaleFactor != 1.0) {
     assert( scaleFactor != 0 ); // or should it be an IllegalArgumentException ?
     pt.x=scale(pt.x);
     pt.y=scale(pt.y);
   }
   initCorners(pt);
 }
Member Function Documentation
bool geos::noding::snapround::HotPixel::addSnappedNode (NodedSegmentString & segStr, std::size_t segIndex)
Adds a new node (equal to the snap pt) to the specified segment if the segment passes through the hot pixel
Parameters
segStr
segIndex
Returns
true if a node was added to the segment
Definition at line 175 of file HotPixel.cpp.
References geos::noding::NodedSegmentString::addIntersection(), geos::noding::NodedSegmentString::getCoordinate(), getCoordinate(), and intersects().
Referenced by geos::noding::snapround::SimpleSnapRounder::computeSnaps(), and geos::noding::snapround::SimpleSnapRounder::computeVertexSnaps().
 {
   const Coordinate& p0 = segStr.getCoordinate(static_cast<unsigned int>(segIndex));
   const Coordinate& p1 = segStr.getCoordinate(static_cast<unsigned int>(segIndex + 1));
   if (intersects(p0, p1))
   {
     //cout << "snapped: " <<  snapPt << endl;
     segStr.addIntersection(getCoordinate(), static_cast<unsigned int>(segIndex));
     return true;
   }
   return false;
 }
INLINE void geos::noding::snapround::HotPixel::copyScaled (const geom::Coordinate & p, geom::Coordinate & pScaled) const private
Definition at line 39 of file HotPixel.inl.
References scale(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by intersects().
 {
   pScaled.x = scale(p.x);
   pScaled.y = scale(p.y);
 }
const geom::Coordinate& geos::noding::snapround::HotPixel::getCoordinate () const inline
Return reference to original Coordinate (the one provided at construction time)
Definition at line 168 of file HotPixel.h.
Referenced by addSnappedNode().
 { return originalPt; }
const Envelope & geos::noding::snapround::HotPixel::getSafeEnvelope () const
Returns a "safe" envelope that is guaranteed to contain the hot pixel. Keeps ownership of it.
The envelope returned will be larger than the exact envelope of the pixel.
Definition at line 57 of file HotPixel.cpp.
References originalPt, safeEnv, scaleFactor, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::noding::snapround::MCIndexPointSnapper::snap().
 {
   static const double SAFE_ENV_EXPANSION_FACTOR = 0.75;
   if (safeEnv.get() == nullptr) {
     double safeTolerance = SAFE_ENV_EXPANSION_FACTOR / scaleFactor;
     safeEnv = unique_ptr<Envelope>(new Envelope(originalPt.x - safeTolerance,
       originalPt.x + safeTolerance,
       originalPt.y - safeTolerance,
       originalPt.y + safeTolerance
       ));
   }
   return *safeEnv;
 }
void geos::noding::snapround::HotPixel::initCorners (const geom::Coordinate & pt) private
Definition at line 74 of file HotPixel.cpp.
References corner, maxx, maxy, minx, miny, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by HotPixel().
 {
   double tolerance = 0.5;
   minx = pt.x - tolerance;
   maxx = pt.x + tolerance;
   miny = pt.y - tolerance;
   maxy = pt.y + tolerance;
   corner.resize(4);
   corner[0] = Coordinate(maxx, maxy);
   corner[1] = Coordinate(minx, maxy);
   corner[2] = Coordinate(minx, miny);
   corner[3] = Coordinate(maxx, miny);
 }
bool geos::noding::snapround::HotPixel::intersects (const geom::Coordinate & p0, const geom::Coordinate & p1) const
Tests whether the line segment (p0-p1) intersects this hot pixel.
Parameters
p0 the first coordinate of the line segment to test
p1 the second coordinate of the line segment to test
Returns
true if the line segment intersects this hot pixel
Definition at line 90 of file HotPixel.cpp.
References copyScaled(), intersectsScaled(), p0Scaled, p1Scaled, and scaleFactor.
Referenced by addSnappedNode(), and intersectsScaled().
 {
   if (scaleFactor == 1.0) return intersectsScaled(p0, p1);
   copyScaled(p0, p0Scaled);
   copyScaled(p1, p1Scaled);
   return intersectsScaled(p0Scaled, p1Scaled);
 }
bool geos::noding::snapround::HotPixel::intersectsPixelClosure (const geom::Coordinate & p0, const geom::Coordinate & p1) private
Test whether the given segment intersects the closure of this hot pixel.
This is NOT the test used in the standard snap-rounding algorithm, which uses the partially closed tolerance square instead. This routine is provided for testing purposes only.
Parameters
p0 the start point of a line segment
p1 the end point of a line segment
Returns
true if the segment intersects the closure of the pixel's tolerance square
Definition at line 159 of file HotPixel.cpp.
References geos::algorithm::LineIntersector::computeIntersection(), corner, geos::algorithm::LineIntersector::hasIntersection(), and li.
 {
     li.computeIntersection(p0, p1, corner[0], corner[1]);
     if (li.hasIntersection()) return true;
     li.computeIntersection(p0, p1, corner[1], corner[2]);
     if (li.hasIntersection()) return true;
     li.computeIntersection(p0, p1, corner[2], corner[3]);
     if (li.hasIntersection()) return true;
     li.computeIntersection(p0, p1, corner[3], corner[0]);
     if (li.hasIntersection()) return true;
     return false;
 }
bool geos::noding::snapround::HotPixel::intersectsScaled (const geom::Coordinate & p0, const geom::Coordinate & p1) const private
Definition at line 103 of file HotPixel.cpp.
References intersects(), intersectsToleranceSquare(), maxx, maxy, minx, miny, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by intersects().
 {
   double const segMinx = std::min(p0.x, p1.x);
   double const segMaxx = std::max(p0.x, p1.x);
   double const segMiny = std::min(p0.y, p1.y);
   double const segMaxy = std::max(p0.y, p1.y);
   bool isOutsidePixelEnv =  maxx < segMinx
                          || minx > segMaxx
                          || maxy < segMiny
                          || miny > segMaxy;
   if (isOutsidePixelEnv) return false;
   bool intersects = intersectsToleranceSquare(p0, p1);
   // Found bad envelope test
   assert(!(isOutsidePixelEnv && intersects));
   return intersects;
 }
bool geos::noding::snapround::HotPixel::intersectsToleranceSquare (const geom::Coordinate & p0, const geom::Coordinate & p1) const private
Tests whether the segment p0-p1 intersects the hot pixel tolerance square.
Because the tolerance square point set is partially open (along the top and right) the test needs to be more sophisticated than simply checking for any intersection. However, it can take advantage of the fact that because the hot pixel edges do not lie on the coordinate grid. It is sufficient to check if there is at least one of:
a proper intersection with the segment and any hot pixel edge
an intersection between the segment and both the left and bottom edges
an intersection between a segment endpoint and the hot pixel coordinate
Parameters
p0
p1
Returns
Definition at line 129 of file HotPixel.cpp.
References geos::algorithm::LineIntersector::computeIntersection(), corner, geos::geom::Coordinate::equals2D(), geos::algorithm::LineIntersector::hasIntersection(), geos::algorithm::LineIntersector::isProper(), li, and pt.
Referenced by intersectsScaled().
 {
     bool intersectsLeft = false;
     bool intersectsBottom = false;
     li.computeIntersection(p0, p1, corner[0], corner[1]);
     if (li.isProper()) return true;
     li.computeIntersection(p0, p1, corner[1], corner[2]);
     if (li.isProper()) return true;
     if (li.hasIntersection()) intersectsLeft = true;
     li.computeIntersection(p0, p1, corner[2], corner[3]);
     if (li.isProper()) return true;
     if (li.hasIntersection()) intersectsBottom = true;
     li.computeIntersection(p0, p1, corner[3], corner[0]);
     if (li.isProper()) return true;
     if (intersectsLeft && intersectsBottom) return true;
     if (p0.equals2D(pt)) return true;
     if (p1.equals2D(pt)) return true;
     return false;
 }
HotPixel& geos::noding::snapround::HotPixel::operator= (const HotPixel & rhs) private delete
INLINE double geos::noding::snapround::HotPixel::scale (double val) const private
Definition at line 31 of file HotPixel.inl.
References INLINE, geos::util::round(), and scaleFactor.
Referenced by copyScaled(), and HotPixel().
 {
   // Math.round
   //return round(val*scaleFactor);
   return util::round(val*scaleFactor);
 }
Member Data Documentation
std::vector<geom::Coordinate> geos::noding::snapround::HotPixel::corner private
The corners of the hot pixel.
In the order: 1 0 2 3
Definition at line 89 of file HotPixel.h.
Referenced by initCorners(), intersectsPixelClosure(), and intersectsToleranceSquare().
algorithm::LineIntersector& geos::noding::snapround::HotPixel::li private
Definition at line 66 of file HotPixel.h.
Referenced by intersectsPixelClosure(), and intersectsToleranceSquare().
double geos::noding::snapround::HotPixel::maxx private
Definition at line 78 of file HotPixel.h.
Referenced by initCorners(), and intersectsScaled().
double geos::noding::snapround::HotPixel::maxy private
Definition at line 80 of file HotPixel.h.
Referenced by initCorners(), and intersectsScaled().
double geos::noding::snapround::HotPixel::minx private
Definition at line 77 of file HotPixel.h.
Referenced by initCorners(), and intersectsScaled().
double geos::noding::snapround::HotPixel::miny private
Definition at line 79 of file HotPixel.h.
Referenced by initCorners(), and intersectsScaled().
const geom::Coordinate& geos::noding::snapround::HotPixel::originalPt private
Definition at line 69 of file HotPixel.h.
Referenced by getSafeEnvelope().
geom::Coordinate geos::noding::snapround::HotPixel::p0Scaled mutable private
Definition at line 72 of file HotPixel.h.
Referenced by intersects().
geom::Coordinate geos::noding::snapround::HotPixel::p1Scaled mutable private
Definition at line 73 of file HotPixel.h.
Referenced by intersects().
geom::Coordinate geos::noding::snapround::HotPixel::pt private
Definition at line 68 of file HotPixel.h.
Referenced by HotPixel(), and intersectsToleranceSquare().
geom::Coordinate geos::noding::snapround::HotPixel::ptScaled private
Definition at line 70 of file HotPixel.h.
std::unique_ptr<geom::Envelope> geos::noding::snapround::HotPixel::safeEnv mutable private
Owned by this class, constructed on demand.
Definition at line 92 of file HotPixel.h.
Referenced by getSafeEnvelope().
double geos::noding::snapround::HotPixel::scaleFactor private
Definition at line 75 of file HotPixel.h.
Referenced by getSafeEnvelope(), HotPixel(), intersects(), and scale().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/snapround/HotPixel.h
/home/vicky/potree/geos/vicky/src/noding/snapround/HotPixel.cpp
/home/vicky/potree/geos/vicky/include/geos/noding/snapround/HotPixel.inl