GEOS: geos::io::ParseException Class Reference
geos::io::ParseException Class Reference
Notifies a parsing error.
#include <geos.h>
Public Member Functions
ParseException ()
ParseException (const std::string &msg)
ParseException (const std::string &msg, const std::string &var)
ParseException (const std::string &msg, double num)
~ParseException () override throw ()
const char * what () const override throw ()
Static Private Member Functions
static std::string stringify (double num)
Detailed Description
Notifies a parsing error.
Definition at line 34 of file ParseException.h.
Constructor & Destructor Documentation
geos::io::ParseException::ParseException ()
Definition at line 29 of file ParseException.cpp.
References geos::util::GEOSException::GEOSException(), and stringify().
   :
   GEOSException("ParseException", "")
 {
 }
geos::io::ParseException::ParseException (const std::string & msg)
geos::io::ParseException::ParseException (const std::string & msg, const std::string & var)
geos::io::ParseException::ParseException (const std::string & msg, double num)
geos::io::ParseException::~ParseException () throw () inline override
Definition at line 47 of file ParseException.h.
 {}
Member Function Documentation
string geos::io::ParseException::stringify (double num) static private
Definition at line 54 of file ParseException.cpp.
Referenced by ParseException().
 {
   stringstream ss;
   ss<<num;
   return ss.str();
 }
const char* geos::util::GEOSException::what () const throw () inline override inherited
Definition at line 63 of file GEOSException.h.
Referenced by geos::operation::overlay::ElevationMatrix::add(), geos::geom::BinaryOp(), geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::snap::SnapIfNeededOverlayOp::getResultGeometry(), geos::operation::polygonize::EdgeRing::getRingInternal(), and geos::precision::EnhancedPrecisionOp::intersection().
   {
     return _msg.c_str();
   }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/io/ParseException.h
/home/vicky/potree/geos/vicky/src/io/ParseException.cpp