GEOS: geos::noding::SegmentString Class Reference
geos::noding::SegmentString Class Reference abstract
An interface for classes which represent a sequence of contiguous line segments.
#include <SegmentString.h>
Public Types
typedef std::vector< const SegmentString * > ConstVect
typedef std::vector< SegmentString * > NonConstVect
Public Member Functions
SegmentString (const void *newContext)
Construct a SegmentString.
virtual ~SegmentString ()
const void * getData () const
void setData (const void *data)
virtual unsigned int size () const =0
virtual const geom::Coordinate & getCoordinate (unsigned int i) const =0
virtual geom::CoordinateSequence * getCoordinates () const =0
Return a pointer to the CoordinateSequence associated with this SegmentString.
virtual bool isClosed () const =0
virtual std::ostream & print (std::ostream &os) const
Private Member Functions
SegmentString (const SegmentString &other)=delete
SegmentString & operator= (const SegmentString &rhs)=delete
Private Attributes
const void * context
Friends
std::ostream & operator<< (std::ostream &os, const SegmentString &ss)
Detailed Description
An interface for classes which represent a sequence of contiguous line segments.
SegmentStrings can carry a context object, which is useful for preserving topological or parentage information.
Definition at line 46 of file SegmentString.h.
Member Typedef Documentation
typedef std::vector<const SegmentString*> geos::noding::SegmentString::ConstVect
Definition at line 48 of file SegmentString.h.
typedef std::vector<SegmentString *> geos::noding::SegmentString::NonConstVect
Definition at line 49 of file SegmentString.h.
Constructor & Destructor Documentation
geos::noding::SegmentString::SegmentString (const void * newContext) inline
Construct a SegmentString.
Parameters
newContext the context associated to this SegmentString
Definition at line 58 of file SegmentString.h.
     :
     context(newContext)
   {}
virtual geos::noding::SegmentString::~SegmentString () inline virtual
Definition at line 63 of file SegmentString.h.
 {}
geos::noding::SegmentString::SegmentString (const SegmentString & other) private delete
Member Function Documentation
virtual const geom::Coordinate& geos::noding::SegmentString::getCoordinate (unsigned int i) const pure virtual
Implemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Referenced by geos::noding::SegmentNodeList::checkSplitEdgesCorrectness(), geos::noding::IntersectionFinderAdder::processIntersections(), geos::noding::SingleInteriorIntersectionFinder::processIntersections(), and geos::noding::IntersectionAdder::processIntersections().
virtual geom::CoordinateSequence* geos::noding::SegmentString::getCoordinates () const pure virtual
Return a pointer to the CoordinateSequence associated with this SegmentString.
Note that the CoordinateSequence is owned by this SegmentString!
Implemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Referenced by geos::noding::MCIndexNoder::add(), geos::noding::MCIndexSegmentSetMutualIntersector::addToIndex(), geos::noding::MCIndexSegmentSetMutualIntersector::addToMonoChains(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::noding::NodingValidator::checkCollapses(), geos::noding::NodingValidator::checkEndPtVertexIntersections(), geos::noding::NodingValidator::checkInteriorIntersections(), geos::noding::SimpleNoder::computeIntersects(), geos::operation::buffer::BufferBuilder::computeNodedEdges(), geos::noding::SegmentIntersectionDetector::processIntersections(), geos::noding::ScaledNoder::rescale(), and geos::noding::ScaledNoder::scale().
const void* geos::noding::SegmentString::getData () const inline
Gets the user-defined data for this segment string.
Returns
the user-defined data
Definition at line 70 of file SegmentString.h.
Referenced by geos::operation::buffer::BufferBuilder::computeNodedEdges().
 { return context; }
virtual bool geos::noding::SegmentString::isClosed () const pure virtual
Implemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Referenced by geos::noding::IntersectionAdder::isTrivialIntersection().
SegmentString& geos::noding::SegmentString::operator= (const SegmentString & rhs) private delete
std::ostream & geos::noding::SegmentString::print (std::ostream & os) const virtual
Reimplemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Definition at line 49 of file SegmentString.cpp.
Referenced by geos::noding::operator<<().
 {
   os << "SegmentString" << std::endl;
   return os;
 }
void geos::noding::SegmentString::setData (const void * data) inline
Sets the user-defined data for this segment string.
Parameters
data an Object containing user-defined data
Definition at line 77 of file SegmentString.h.
 { context=data; }
virtual unsigned int geos::noding::SegmentString::size () const pure virtual
Implemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Referenced by geos::noding::IntersectionAdder::isTrivialIntersection().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const SegmentString & ss) friend
Definition at line 43 of file SegmentString.cpp.
 {
   return ss.print(os);
 }
Member Data Documentation
const void* geos::noding::SegmentString::context private
Definition at line 98 of file SegmentString.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/SegmentString.h
/home/vicky/potree/geos/vicky/src/noding/SegmentString.cpp