GEOS: geos::algorithm::distance::DiscreteHausdorffDistance Class Reference
geos::algorithm::distance::DiscreteHausdorffDistance Class Reference
An algorithm for computing a distance metric which is an approximation to the Hausdorff Distance based on a discretization of the input Geometry.
#include <DiscreteHausdorffDistance.h>
Classes
class MaxDensifiedByFractionDistanceFilter
class MaxPointDistanceFilter
Public Member Functions
DiscreteHausdorffDistance (const geom::Geometry &g0, const geom::Geometry &g1)
void setDensifyFraction (double dFrac)
double distance ()
double orientedDistance ()
const std::vector< geom::Coordinate > getCoordinates () const
Static Public Member Functions
static double distance (const geom::Geometry &g0, const geom::Geometry &g1)
static double distance (const geom::Geometry &g0, const geom::Geometry &g1, double densifyFrac)
Private Member Functions
void compute (const geom::Geometry &g0, const geom::Geometry &g1)
void computeOrientedDistance (const geom::Geometry &discreteGeom, const geom::Geometry &geom, PointPairDistance &ptDist)
DiscreteHausdorffDistance (const DiscreteHausdorffDistance &other)=delete
DiscreteHausdorffDistance & operator= (const DiscreteHausdorffDistance &rhs)=delete
Private Attributes
const geom::Geometry & g0
const geom::Geometry & g1
PointPairDistance ptDist
double densifyFrac
Value of 0.0 indicates that no densification should take place.
Detailed Description
An algorithm for computing a distance metric which is an approximation to the Hausdorff Distance based on a discretization of the input Geometry.
The algorithm computes the Hausdorff distance restricted to discrete points for one of the geometries. The points can be either the vertices of the geometries (the default), or the geometries with line segments densified by a given fraction. Also determines two points of the Geometries which are separated by the computed distance.
This algorithm is an approximation to the standard Hausdorff distance. Specifically,
   for all geometries a, b:    DHD(a, b) <= HD(a, b)
The approximation can be made as close as needed by densifying the input geometries. In the limit, this value will approach the true Hausdorff distance:
   DHD(A, B, densifyFactor) -> HD(A, B) as densifyFactor -> 0.0
The default approximation is exact or close enough for a large subset of useful cases. Examples of these are:
computing distance between Linestrings that are roughly parallel to each other, and roughly equal in length. This occurs in matching linear networks.
Testing similarity of geometries.
An example where the default approximation is not close is:
  A = LINESTRING (0 0, 100 0, 10 100, 10 100)
  B = LINESTRING (0 100, 0 10, 80 10)
  DHD(A, B) = 22.360679774997898
  HD(A, B) ~= 47.8
Definition at line 100 of file DiscreteHausdorffDistance.h.
Constructor & Destructor Documentation
geos::algorithm::distance::DiscreteHausdorffDistance::DiscreteHausdorffDistance (const geom::Geometry & g0, const geom::Geometry & g1) inline
Definition at line 110 of file DiscreteHausdorffDistance.h.
     :
     g0(g0),
     g1(g1),
     ptDist(),
     densifyFrac(0.0)
   {}
geos::algorithm::distance::DiscreteHausdorffDistance::DiscreteHausdorffDistance (const DiscreteHausdorffDistance & other) private delete
Member Function Documentation
void geos::algorithm::distance::DiscreteHausdorffDistance::compute (const geom::Geometry & g0, const geom::Geometry & g1) inline private
Definition at line 224 of file DiscreteHausdorffDistance.h.
   {
     computeOrientedDistance(g0, g1, ptDist);
     computeOrientedDistance(g1, g0, ptDist);
   }
void geos::algorithm::distance::DiscreteHausdorffDistance::computeOrientedDistance (const geom::Geometry & discreteGeom, const geom::Geometry & geom, PointPairDistance & ptDist) private
Definition at line 87 of file DiscreteHausdorffDistance.cpp.
References geos::geom::Geometry::apply_ro(), geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::getMaxPointDistance(), geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::getMaxPointDistance(), and geos::algorithm::distance::PointPairDistance::setMaximum().
 {
   MaxPointDistanceFilter distFilter(geom);
   discreteGeom.apply_ro(&distFilter);
   ptDist.setMaximum(distFilter.getMaxPointDistance());
   if (densifyFrac > 0)
   {
     MaxDensifiedByFractionDistanceFilter fracFilter(geom,
                 densifyFrac);
     discreteGeom.apply_ro(fracFilter);
     ptDist.setMaximum(fracFilter.getMaxPointDistance());
   }
 }
double geos::algorithm::distance::DiscreteHausdorffDistance::distance (const geom::Geometry & g0, const geom::Geometry & g1) static
Definition at line 67 of file DiscreteHausdorffDistance.cpp.
References distance().
Referenced by distance().
 {
   DiscreteHausdorffDistance dist(g0, g1);
   return dist.distance();
 }
double geos::algorithm::distance::DiscreteHausdorffDistance::distance (const geom::Geometry & g0, const geom::Geometry & g1, double densifyFrac) static
Definition at line 76 of file DiscreteHausdorffDistance.cpp.
References distance(), and setDensifyFraction().
 {
   DiscreteHausdorffDistance dist(g0, g1);
   dist.setDensifyFraction(densifyFrac);
   return dist.distance();
 }
double geos::algorithm::distance::DiscreteHausdorffDistance::distance () inline
Definition at line 138 of file DiscreteHausdorffDistance.h.
   {
     compute(g0, g1);
     return ptDist.getDistance();
   }
const std::vector<geom::Coordinate> geos::algorithm::distance::DiscreteHausdorffDistance::getCoordinates () const inline
Definition at line 150 of file DiscreteHausdorffDistance.h.
   {
     return ptDist.getCoordinates();
   }
DiscreteHausdorffDistance& geos::algorithm::distance::DiscreteHausdorffDistance::operator= (const DiscreteHausdorffDistance & rhs) private delete
double geos::algorithm::distance::DiscreteHausdorffDistance::orientedDistance () inline
Definition at line 144 of file DiscreteHausdorffDistance.h.
   {
     computeOrientedDistance(g0, g1, ptDist);
     return ptDist.getDistance();
   }
void geos::algorithm::distance::DiscreteHausdorffDistance::setDensifyFraction (double dFrac) inline
Sets the fraction by which to densify each segment. Each segment will be (virtually) split into a number of equal-length subsegments, whose fraction of the total length is closest to the given fraction.
Parameters
dFrac
Definition at line 127 of file DiscreteHausdorffDistance.h.
Referenced by distance().
   {
     if ( dFrac > 1.0 || dFrac <= 0.0 )
     {
       throw util::IllegalArgumentException(
         "Fraction is not in range (0.0 - 1.0]");
     }
     densifyFrac = dFrac;
   }
Member Data Documentation
double geos::algorithm::distance::DiscreteHausdorffDistance::densifyFrac private
Value of 0.0 indicates that no densification should take place.
Definition at line 242 of file DiscreteHausdorffDistance.h.
const geom::Geometry& geos::algorithm::distance::DiscreteHausdorffDistance::g0 private
Definition at line 235 of file DiscreteHausdorffDistance.h.
const geom::Geometry& geos::algorithm::distance::DiscreteHausdorffDistance::g1 private
Definition at line 237 of file DiscreteHausdorffDistance.h.
PointPairDistance geos::algorithm::distance::DiscreteHausdorffDistance::ptDist private
Definition at line 239 of file DiscreteHausdorffDistance.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/distance/DiscreteHausdorffDistance.h
/home/vicky/potree/geos/vicky/src/algorithm/distance/DiscreteHausdorffDistance.cpp