GEOS: geos::geom::util::SineStarFactory Class Reference
geos::geom::util::SineStarFactory Class Reference
#include <SineStarFactory.h>
Public Member Functions
SineStarFactory (const geom::GeometryFactory *fact)
void setNumArms (int nArms)
void setArmLengthRatio (double armLenRatio)
std::unique_ptr< Polygon > createSineStar () const
geom::LineString * createArc (double startAng, double angExtent)
Creates an elliptical arc, as a LineString.
geom::Polygon * createArcPolygon (double startAng, double angExt)
Creates an elliptical arc polygon.
geom::Polygon * createCircle ()
Creates a circular Polygon.
geom::Polygon * createRectangle ()
Creates a rectangular Polygon.
void setBase (const geom::Coordinate &base)
Sets the location of the shape by specifying the base coordinate (which in most cases is the * lower left point of the envelope containing the shape).
void setCentre (const geom::Coordinate &centre)
Sets the location of the shape by specifying the centre of the shape's bounding box.
void setHeight (double height)
Sets the height of the shape.
void setNumPoints (int nNPts)
Sets the total number of points in the created Geometry.
void setSize (double size)
Sets the size of the extent of the shape in both x and y directions.
void setWidth (double width)
Sets the width of the shape.
Protected Member Functions
geom::Coordinate coord (double x, double y) const
Protected Attributes
int numArms
double armLengthRatio
const geom::GeometryFactory * geomFact
const geom::PrecisionModel * precModel
Dimensions dim
int nPts
Detailed Description
Creates geometries which are shaped like multi-armed stars with each arm shaped like a sine wave. These kinds of geometries are useful as a more complex geometry for testing algorithms.
Author
Martin Davis
Definition at line 58 of file SineStarFactory.h.
Constructor & Destructor Documentation
geos::geom::util::SineStarFactory::SineStarFactory (const geom::GeometryFactory * fact) inline
Creates a factory which will create sine stars using the given GeometryFactory.
Parameters
fact the factory to use. You need to keep the factory alive for the whole SineStarFactory life time.
Definition at line 75 of file SineStarFactory.h.
     :
     geos::util::GeometricShapeFactory(fact),
     numArms(8),
     armLengthRatio(0.5)
   {}
Member Function Documentation
Coordinate geos::util::GeometricShapeFactory::coord (double x, double y) const protected inherited
Definition at line 265 of file GeometricShapeFactory.cpp.
References geos::geom::PrecisionModel::makePrecise(), and geos::util::GeometricShapeFactory::precModel.
Referenced by geos::util::GeometricShapeFactory::createArc(), geos::util::GeometricShapeFactory::createArcPolygon(), geos::util::GeometricShapeFactory::createCircle(), and geos::util::GeometricShapeFactory::createRectangle().
 {
   Coordinate ret(x, y);
   precModel->makePrecise(&ret);
   return ret;
 }
LineString * geos::util::GeometricShapeFactory::createArc (double startAng, double angExtent) inherited
Creates an elliptical arc, as a LineString.
The arc is always created in a counter-clockwise direction.
Parameters
startAng start angle in radians
angExtent size of angle in radians
Returns
an elliptical arc
Definition at line 153 of file GeometricShapeFactory.cpp.
References centreY, geos::util::GeometricShapeFactory::coord(), geos::geom::CoordinateSequenceFactory::create(), geos::geom::GeometryFactory::createLineString(), geos::util::GeometricShapeFactory::dim, geos::util::GeometricShapeFactory::geomFact, geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::util::GeometricShapeFactory::Dimensions::getEnvelope(), M_PI, and geos::util::GeometricShapeFactory::nPts.
 {
   std::unique_ptr<Envelope> env ( dim.getEnvelope() );
   double xRadius = env->getWidth() / 2.0;
   double yRadius = env->getHeight() / 2.0;
   double centreX = env->getMinX() + xRadius;
   double centreY = env->getMinY() + yRadius;
   env.reset();
   double angSize = angExtent;
   if (angSize <= 0.0 || angSize > 2 * M_PI)
     angSize = 2 * M_PI;
   double angInc = angSize / ( nPts - 1 );
   vector<Coordinate> *pts = new vector<Coordinate>(nPts);
   int iPt = 0;
   for (int i = 0; i < nPts; i++) {
     double ang = startAng + i * angInc;
     double x = xRadius * cos(ang) + centreX;
     double y = yRadius * sin(ang) + centreY;
     (*pts)[iPt++] = coord(x, y);
   }
   CoordinateSequence *cs = geomFact->getCoordinateSequenceFactory()->create(pts);
   LineString* line = geomFact->createLineString(cs);
   return line;
 }
Polygon * geos::util::GeometricShapeFactory::createArcPolygon (double startAng, double angExt) inherited
Creates an elliptical arc polygon.
The polygon is formed from the specified arc of an ellipse and the two radii connecting the endpoints to the centre of the ellipse.
Parameters
startAng start angle in radians
angExtent size of angle in radians
Returns
an elliptical arc polygon
Definition at line 182 of file GeometricShapeFactory.cpp.
References centreY, geos::util::GeometricShapeFactory::coord(), geos::geom::CoordinateSequenceFactory::create(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createPolygon(), geos::util::GeometricShapeFactory::dim, geos::util::GeometricShapeFactory::geomFact, geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::util::GeometricShapeFactory::Dimensions::getEnvelope(), M_PI, and geos::util::GeometricShapeFactory::nPts.
 {
   std::unique_ptr<Envelope> env ( dim.getEnvelope() );
   double xRadius = env->getWidth() / 2.0;
   double yRadius = env->getHeight() / 2.0;
   double centreX = env->getMinX() + xRadius;
   double centreY = env->getMinY() + yRadius;
   env.reset();
   double angSize = angExtent;
   if (angSize <= 0.0 || angSize > 2 * M_PI)
     angSize = 2 * M_PI;
   double angInc = angSize / ( nPts - 1 );
   vector<Coordinate> *pts = new vector<Coordinate>(nPts + 2);
   int iPt = 0;
   (*pts)[iPt++] = coord(centreX, centreY);
   for (int i = 0; i < nPts; i++) {
     double ang = startAng + i * angInc;
     double x = xRadius * cos(ang) + centreX;
     double y = yRadius * sin(ang) + centreY;
     (*pts)[iPt++] = coord(x, y);
   }
   (*pts)[iPt++] = coord(centreX, centreY);
   CoordinateSequence *cs = geomFact->getCoordinateSequenceFactory()->create(pts);
   LinearRing* ring = geomFact->createLinearRing(cs);
   Polygon* geom = geomFact->createPolygon(ring, nullptr);
   return geom;
 }
Polygon * geos::util::GeometricShapeFactory::createCircle () inherited
Creates a circular Polygon.
Returns
a circle
Definition at line 127 of file GeometricShapeFactory.cpp.
References centreY, geos::util::GeometricShapeFactory::coord(), geos::geom::CoordinateSequenceFactory::create(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createPolygon(), geos::util::GeometricShapeFactory::dim, geos::util::GeometricShapeFactory::geomFact, geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::util::GeometricShapeFactory::Dimensions::getEnvelope(), geos::util::GeometricShapeFactory::nPts, and poly.
 {
   std::unique_ptr<Envelope> env ( dim.getEnvelope() );
   double xRadius = env->getWidth() / 2.0;
   double yRadius = env->getHeight() / 2.0;
   double centreX = env->getMinX() + xRadius;
   double centreY = env->getMinY() + yRadius;
   env.reset();
   vector<Coordinate>*pts=new vector<Coordinate>(nPts+1);
   int iPt = 0;
   for (int i = 0; i < nPts; i++) {
     double ang = i * (2 * 3.14159265358979 / nPts);
     double x = xRadius * cos(ang) + centreX;
     double y = yRadius * sin(ang) + centreY;
     (*pts)[iPt++] = coord(x, y);
   }
   (*pts)[iPt++] = (*pts)[0];
   CoordinateSequence *cs=geomFact->getCoordinateSequenceFactory()->create(pts);
   LinearRing* ring = geomFact->createLinearRing(cs);
   Polygon* poly=geomFact->createPolygon(ring,nullptr);
   return poly;
 }
Polygon * geos::util::GeometricShapeFactory::createRectangle () inherited
Creates a rectangular Polygon.
Returns
a rectangular Polygon
Definition at line 86 of file GeometricShapeFactory.cpp.
References geos::util::GeometricShapeFactory::coord(), geos::geom::CoordinateSequenceFactory::create(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createPolygon(), geos::util::GeometricShapeFactory::dim, geos::util::GeometricShapeFactory::geomFact, geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::util::GeometricShapeFactory::Dimensions::getEnvelope(), geos::util::GeometricShapeFactory::nPts, and poly.
 {
   int i;
   int ipt = 0;
   int nSide = nPts / 4;
   if (nSide < 1) nSide = 1;
   std::unique_ptr<Envelope> env ( dim.getEnvelope() );
   double XsegLen = env->getWidth() / nSide;
   double YsegLen = env->getHeight() / nSide;
   vector<Coordinate> *vc = new vector<Coordinate>(4*nSide+1);
   //CoordinateSequence* pts=new CoordinateArraySequence(4*nSide+1);
   for (i = 0; i < nSide; i++) {
     double x = env->getMinX() + i * XsegLen;
     double y = env->getMinY();
     (*vc)[ipt++] = coord(x, y);
   }
   for (i = 0; i < nSide; i++) {
     double x = env->getMaxX();
     double y = env->getMinY() + i * YsegLen;
     (*vc)[ipt++] = coord(x, y);
   }
   for (i = 0; i < nSide; i++) {
     double x = env->getMaxX() - i * XsegLen;
     double y = env->getMaxY();
     (*vc)[ipt++] = coord(x, y);
   }
   for (i = 0; i < nSide; i++) {
     double x = env->getMinX();
     double y = env->getMaxY() - i * YsegLen;
     (*vc)[ipt++] = coord(x, y);
   }
   (*vc)[ipt++] = (*vc)[0];
   CoordinateSequence *cs = geomFact->getCoordinateSequenceFactory()->create(vc);
   LinearRing* ring=geomFact->createLinearRing(cs);
   Polygon* poly=geomFact->createPolygon(ring, nullptr);
   return poly;
 }
unique_ptr< Polygon > geos::geom::util::SineStarFactory::createSineStar () const
Generates the geometry for the sine star
Returns
the geometry representing the sine star
Definition at line 45 of file SineStarFactory.cpp.
References centreY, M_PI, and poly.
 {
   unique_ptr<Envelope> env ( dim.getEnvelope() );
   double radius = env->getWidth() / 2.0;
   double armRatio = armLengthRatio;
   if (armRatio < 0.0) armRatio = 0.0;
   if (armRatio > 1.0) armRatio = 1.0;
   double armMaxLen = armRatio * radius;
   double insideRadius = (1 - armRatio) * radius;
   double centreX = env->getMinX() + radius;
   double centreY = env->getMinY() + radius;
   unique_ptr< vector<Coordinate> > pts ( new vector<Coordinate>(nPts+1) );
   int iPt = 0;
   for (int i = 0; i < nPts; i++) {
     // the fraction of the way thru the current arm - in [0,1]
     double ptArcFrac = (i / (double) nPts) * numArms;
     double armAngFrac = ptArcFrac - floor(ptArcFrac);
     // the angle for the current arm - in [0,2Pi]
     // (each arm is a complete sine wave cycle)
     double armAng = 2 * M_PI * armAngFrac;
     // the current length of the arm
     double armLenFrac = (cos(armAng) + 1.0) / 2.0;
     // the current radius of the curve (core + arm)
     double curveRadius = insideRadius + armMaxLen * armLenFrac;
     // the current angle of the curve
     double ang = i * (2 * M_PI / nPts);
     double x = curveRadius * cos(ang) + centreX;
     double y = curveRadius * sin(ang) + centreY;
     (*pts)[iPt++] = coord(x, y);
   }
   (*pts)[iPt] = Coordinate((*pts)[0]);
   unique_ptr<CoordinateSequence> cs (
     geomFact->getCoordinateSequenceFactory()->create( pts.release() )
   );
   unique_ptr<LinearRing> ring ( geomFact->createLinearRing( cs.release() ) );
   unique_ptr<Polygon> poly ( geomFact->createPolygon(ring.release(), nullptr) );
   return poly;
 }
void geos::geom::util::SineStarFactory::setArmLengthRatio (double armLenRatio) inline
Sets the ration of the length of each arm to the distance from the tip of the arm to the centre of the star. Value should be between 0.0 and 1.0
Parameters
armLenRatio
Definition at line 99 of file SineStarFactory.h.
   {
         armLengthRatio = armLenRatio;
   }
void geos::util::GeometricShapeFactory::setBase (const geom::Coordinate & base) inherited
Sets the location of the shape by specifying the base coordinate (which in most cases is the * lower left point of the envelope containing the shape).
Parameters
base the base coordinate of the shape
Definition at line 50 of file GeometricShapeFactory.cpp.
References geos::util::GeometricShapeFactory::dim, and geos::util::GeometricShapeFactory::Dimensions::setBase().
 {
   dim.setBase(base);
 }
void geos::util::GeometricShapeFactory::setCentre (const geom::Coordinate & centre) inherited
Sets the location of the shape by specifying the centre of the shape's bounding box.
Parameters
centre the centre coordinate of the shape
Definition at line 56 of file GeometricShapeFactory.cpp.
References geos::util::GeometricShapeFactory::dim, and geos::util::GeometricShapeFactory::Dimensions::setCentre().
 {
   dim.setCentre(centre);
 }
void geos::util::GeometricShapeFactory::setHeight (double height) inherited
Sets the height of the shape.
Parameters
height the height of the shape
Definition at line 80 of file GeometricShapeFactory.cpp.
References geos::util::GeometricShapeFactory::dim, and geos::util::GeometricShapeFactory::Dimensions::setHeight().
 {
   dim.setHeight(height);
 }
void geos::geom::util::SineStarFactory::setNumArms (int nArms) inline
Sets the number of arms in the star
Parameters
nArms the number of arms to generate
Definition at line 87 of file SineStarFactory.h.
   {
     numArms = nArms;
   }
void geos::util::GeometricShapeFactory::setNumPoints (int nNPts) inherited
Sets the total number of points in the created Geometry.
Definition at line 62 of file GeometricShapeFactory.cpp.
References geos::util::GeometricShapeFactory::nPts.
 {
   nPts=nNPts;
 }
void geos::util::GeometricShapeFactory::setSize (double size) inherited
Sets the size of the extent of the shape in both x and y directions.
Parameters
size the size of the shape's extent
Definition at line 68 of file GeometricShapeFactory.cpp.
References geos::util::GeometricShapeFactory::dim, and geos::util::GeometricShapeFactory::Dimensions::setSize().
 {
   dim.setSize(size);
 }
void geos::util::GeometricShapeFactory::setWidth (double width) inherited
Sets the width of the shape.
Parameters
width the width of the shape
Definition at line 74 of file GeometricShapeFactory.cpp.
References geos::util::GeometricShapeFactory::dim, and geos::util::GeometricShapeFactory::Dimensions::setWidth().
 {
   dim.setWidth(width);
 }
Member Data Documentation
double geos::geom::util::SineStarFactory::armLengthRatio protected
Definition at line 63 of file SineStarFactory.h.
Dimensions geos::util::GeometricShapeFactory::dim protected inherited
Definition at line 86 of file GeometricShapeFactory.h.
Referenced by geos::util::GeometricShapeFactory::createArc(), geos::util::GeometricShapeFactory::createArcPolygon(), geos::util::GeometricShapeFactory::createCircle(), geos::util::GeometricShapeFactory::createRectangle(), geos::util::GeometricShapeFactory::setBase(), geos::util::GeometricShapeFactory::setCentre(), geos::util::GeometricShapeFactory::setHeight(), geos::util::GeometricShapeFactory::setSize(), and geos::util::GeometricShapeFactory::setWidth().
const geom::GeometryFactory* geos::util::GeometricShapeFactory::geomFact protected inherited
Definition at line 84 of file GeometricShapeFactory.h.
Referenced by geos::util::GeometricShapeFactory::createArc(), geos::util::GeometricShapeFactory::createArcPolygon(), geos::util::GeometricShapeFactory::createCircle(), and geos::util::GeometricShapeFactory::createRectangle().
int geos::util::GeometricShapeFactory::nPts protected inherited
Definition at line 87 of file GeometricShapeFactory.h.
Referenced by geos::util::GeometricShapeFactory::createArc(), geos::util::GeometricShapeFactory::createArcPolygon(), geos::util::GeometricShapeFactory::createCircle(), geos::util::GeometricShapeFactory::createRectangle(), and geos::util::GeometricShapeFactory::setNumPoints().
int geos::geom::util::SineStarFactory::numArms protected
Definition at line 62 of file SineStarFactory.h.
const geom::PrecisionModel* geos::util::GeometricShapeFactory::precModel protected inherited
Definition at line 85 of file GeometricShapeFactory.h.
Referenced by geos::util::GeometricShapeFactory::coord().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/util/SineStarFactory.h
/home/vicky/potree/geos/vicky/src/geom/util/SineStarFactory.cpp