GEOS: geos::operation::buffer::OffsetSegmentString Class Reference
geos::operation::buffer::OffsetSegmentString Class Reference
A dynamic list of the vertices in a constructed offset curve.
#include <OffsetSegmentString.h>
Public Member Functions
OffsetSegmentString ()
~OffsetSegmentString ()
void reset ()
void setPrecisionModel (const geom::PrecisionModel *nPrecisionModel)
void setMinimumVertexDistance (double nMinVertexDistance)
void addPt (const geom::Coordinate &pt)
void addPts (const geom::CoordinateSequence &pts, bool isForward)
void closeRing ()
Check that points are a ring.
geom::CoordinateSequence * getCoordinates ()
Get coordinates by taking ownership of them.
size_t size () const
Private Member Functions
bool isRedundant (const geom::Coordinate &pt) const
Tests whether the given point is redundant relative to the previous point in the list (up to tolerance)
Private Attributes
geom::CoordinateArraySequence * ptList
const geom::PrecisionModel * precisionModel
double minimumVertexDistance
The distance below which two adjacent points on the curve are considered to be coincident.
Friends
std::ostream & operator<< (std::ostream &os, const OffsetSegmentString &node)
Detailed Description
A dynamic list of the vertices in a constructed offset curve.
Automatically removes close vertices which are closer than a given tolerance.
Author
Martin Davis
Definition at line 43 of file OffsetSegmentString.h.
Constructor & Destructor Documentation
geos::operation::buffer::OffsetSegmentString::OffsetSegmentString () inline
Definition at line 83 of file OffsetSegmentString.h.
     :
     ptList(new geom::CoordinateArraySequence()),
     precisionModel(nullptr),
     minimumVertexDistance (0.0)
   {
   }
geos::operation::buffer::OffsetSegmentString::~OffsetSegmentString () inline
Definition at line 91 of file OffsetSegmentString.h.
References ptList.
   {
     delete ptList;
   }
Member Function Documentation
void geos::operation::buffer::OffsetSegmentString::addPt (const geom::Coordinate & pt) inline
Definition at line 115 of file OffsetSegmentString.h.
References geos::geom::CoordinateArraySequence::add(), isRedundant(), and geos::geom::PrecisionModel::makePrecise().
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addBevelJoin(), geos::operation::buffer::OffsetSegmentGenerator::addCollinear(), geos::operation::buffer::OffsetSegmentGenerator::addFillet(), geos::operation::buffer::OffsetSegmentGenerator::addInsideTurn(), geos::operation::buffer::OffsetSegmentGenerator::addLimitedMitreJoin(), geos::operation::buffer::OffsetSegmentGenerator::addLineEndCap(), geos::operation::buffer::OffsetSegmentGenerator::addMitreJoin(), geos::operation::buffer::OffsetSegmentGenerator::addOutsideTurn(), addPts(), geos::operation::buffer::OffsetSegmentGenerator::createCircle(), and geos::operation::buffer::OffsetSegmentGenerator::createSquare().
   {
     assert(precisionModel);
     geom::Coordinate bufPt = pt;
     precisionModel->makePrecise(bufPt);
     // don't add duplicate (or near-duplicate) points
     if (isRedundant(bufPt))
     {
       return;
     }
     // we ask to allow repeated as we checked this ourself
     // (JTS uses a vector for ptList, not a CoordinateSequence,
     // we should do the same)
     ptList->add(bufPt, true);
   }
void geos::operation::buffer::OffsetSegmentString::addPts (const geom::CoordinateSequence & pts, bool isForward) inline
Definition at line 132 of file OffsetSegmentString.h.
References addPt(), and geos::geom::CoordinateSequence::size().
   {
     if ( isForward ) {
       for (size_t i=0, n=pts.size(); i<n; ++i) {
         addPt(pts[i]);
       }
     } else {
       for (size_t i=pts.size(); i>0; --i) {
         addPt(pts[i-1]);
       }
     }
   }
void geos::operation::buffer::OffsetSegmentString::closeRing () inline
Check that points are a ring.
add the startpoint again if they are not
Definition at line 148 of file OffsetSegmentString.h.
References geos::geom::CoordinateArraySequence::add(), geos::geom::CoordinateSequence::back(), geos::geom::Coordinate::equals(), geos::geom::CoordinateSequence::front(), and geos::geom::CoordinateSequence::size().
Referenced by geos::operation::buffer::OffsetSegmentGenerator::createCircle(), geos::operation::buffer::OffsetSegmentGenerator::createSquare(), and getCoordinates().
   {
     if (ptList->size() < 1) return;
     const geom::Coordinate& startPt = ptList->front();
     const geom::Coordinate& lastPt = ptList->back();
     if (startPt.equals(lastPt)) return;
     // we ask to allow repeated as we checked this ourself
     ptList->add(startPt, true);
   }
geom::CoordinateSequence* geos::operation::buffer::OffsetSegmentString::getCoordinates (void) inline
Get coordinates by taking ownership of them.
After this call, the coordinates reference in this object are dropped. Calling twice will segfault...
FIXME: refactor memory management of this
Definition at line 166 of file OffsetSegmentString.h.
References closeRing(), and ptList.
   {
     closeRing();
     geom::CoordinateSequence* ret = ptList;
     ptList = nullptr;
     return ret;
   }
bool geos::operation::buffer::OffsetSegmentString::isRedundant (const geom::Coordinate & pt) const inline private
Tests whether the given point is redundant relative to the previous point in the list (up to tolerance)
Parameters
pt
Returns
true if the point is redundant
Definition at line 67 of file OffsetSegmentString.h.
References geos::geom::CoordinateSequence::back(), geos::geom::Coordinate::distance(), operator<<, and geos::geom::CoordinateSequence::size().
Referenced by addPt().
   {
     if (ptList->size() < 1)
       return false;
     const geom::Coordinate& lastPt = ptList->back();
     double ptDist = pt.distance(lastPt);
     if (ptDist < minimumVertexDistance)
       return true;
     return false;
   }
void geos::operation::buffer::OffsetSegmentString::reset () inline
Definition at line 96 of file OffsetSegmentString.h.
References geos::geom::CoordinateArraySequence::clear().
Referenced by geos::operation::buffer::OffsetSegmentGenerator::init().
   {
     if ( ptList ) ptList->clear();
     else ptList = new geom::CoordinateArraySequence();
     precisionModel = nullptr;
     minimumVertexDistance = 0.0;
   }
void geos::operation::buffer::OffsetSegmentString::setMinimumVertexDistance (double nMinVertexDistance) inline
Definition at line 110 of file OffsetSegmentString.h.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::init().
   {
     minimumVertexDistance = nMinVertexDistance;
   }
void geos::operation::buffer::OffsetSegmentString::setPrecisionModel (const geom::PrecisionModel * nPrecisionModel) inline
Definition at line 105 of file OffsetSegmentString.h.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::init().
   {
     precisionModel = nPrecisionModel;
   }
size_t geos::operation::buffer::OffsetSegmentString::size () const inline
Definition at line 174 of file OffsetSegmentString.h.
References geos::geom::CoordinateSequence::size().
 { return ptList ? ptList->size() : 0 ; }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const OffsetSegmentString & node) friend
Definition at line 178 of file OffsetSegmentString.h.
Referenced by isRedundant().
 {
   if ( lst.ptList )
   {
     os << *(lst.ptList);
   }
   else
   {
     os << "empty (consumed?)";
   }
   return os;
 }
Member Data Documentation
double geos::operation::buffer::OffsetSegmentString::minimumVertexDistance private
The distance below which two adjacent points on the curve are considered to be coincident.
This is chosen to be a small fraction of the offset distance.
Definition at line 58 of file OffsetSegmentString.h.
const geom::PrecisionModel* geos::operation::buffer::OffsetSegmentString::precisionModel private
Definition at line 50 of file OffsetSegmentString.h.
geom::CoordinateArraySequence* geos::operation::buffer::OffsetSegmentString::ptList private
Definition at line 48 of file OffsetSegmentString.h.
Referenced by getCoordinates(), geos::operation::buffer::operator<<(), and ~OffsetSegmentString().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/OffsetSegmentString.h