GEOS: geos::operation::buffer::BufferOp Class Reference
geos::operation::buffer::BufferOp Class Reference
Computes the buffer of a geometry, for both positive and negative buffer distances.
#include <geos/opBuffer.h>
Public Types
enum { CAP_ROUND = BufferParameters::CAP_ROUND, CAP_BUTT = BufferParameters::CAP_FLAT, CAP_SQUARE = BufferParameters::CAP_SQUARE }
Public Member Functions
BufferOp (const geom::Geometry *g)
BufferOp (const geom::Geometry *g, const BufferParameters &params)
void setEndCapStyle (int nEndCapStyle)
void setQuadrantSegments (int nQuadrantSegments)
void setSingleSided (bool isSingleSided)
geom::Geometry * getResultGeometry (double nDistance)
Static Public Member Functions
static geom::Geometry * bufferOp (const geom::Geometry *g, double distance, int quadrantSegments=BufferParameters::DEFAULT_QUADRANT_SEGMENTS, int endCapStyle=BufferParameters::CAP_ROUND)
Private Member Functions
void computeGeometry ()
void bufferOriginalPrecision ()
void bufferReducedPrecision (int precisionDigits)
void bufferReducedPrecision ()
void bufferFixedPrecision (const geom::PrecisionModel &fixedPM)
Static Private Member Functions
static double precisionScaleFactor (const geom::Geometry *g, double distance, int maxPrecisionDigits)
Private Attributes
const geom::Geometry * argGeom
util::TopologyException saveException
double distance
BufferParameters bufParams
geom::Geometry * resultGeometry
Static Private Attributes
static const int MAX_PRECISION_DIGITS = 12
Detailed Description
Computes the buffer of a geometry, for both positive and negative buffer distances.
In GIS, the positive (or negative) buffer of a geometry is defined as the Minkowski sum (or difference) of the geometry with a circle with radius equal to the absolute value of the buffer distance. In the CAD/CAM world buffers are known as offset curves. In morphological analysis the operation of positive and negative buffering is referred to as erosion and dilation.
The buffer operation always returns a polygonal result. The negative or zero-distance buffer of lines and points is always an empty Polygon.
Since true buffer curves may contain circular arcs, computed buffer polygons can only be approximations to the true geometry. The user can control the accuracy of the curve approximation by specifying the number of linear segments with which to approximate a curve.
The end cap style of a linear buffer may be specified. The following end cap styles are supported:
CAP_ROUND - the usual round end caps
CAP_BUTT - end caps are truncated flat at the line ends
CAP_SQUARE - end caps are squared off at the buffer distance beyond the line ends
Definition at line 78 of file BufferOp.h.
Member Enumeration Documentation
anonymous enum
Enumerator
CAP_ROUND
Specifies a round line buffer end cap style.
Deprecated:
use BufferParameters
CAP_BUTT
Specifies a butt (or flat) line buffer end cap style.
Deprecated:
use BufferParameters
CAP_SQUARE
Specifies a square line buffer end cap style.
Deprecated:
use BufferParameters
Definition at line 134 of file BufferOp.h.
        {
     CAP_ROUND = BufferParameters::CAP_ROUND,
     CAP_BUTT = BufferParameters::CAP_FLAT,
     CAP_SQUARE = BufferParameters::CAP_SQUARE
   };
Constructor & Destructor Documentation
geos::operation::buffer::BufferOp::BufferOp (const geom::Geometry * g) inline
Initializes a buffer computation for the given geometry
Parameters
g the geometry to buffer
Definition at line 170 of file BufferOp.h.
     :
     argGeom(g),
     bufParams(),
     resultGeometry(nullptr)
   {
   }
geos::operation::buffer::BufferOp::BufferOp (const geom::Geometry * g, const BufferParameters & params) inline
Initializes a buffer computation for the given geometry with the given set of parameters
Parameters
g the geometry to buffer
params the buffer parameters to use. This class will copy it to private memory.
Definition at line 186 of file BufferOp.h.
     :
     argGeom(g),
     bufParams(params),
     resultGeometry(nullptr)
   {
   }
Member Function Documentation
void geos::operation::buffer::BufferOp::bufferFixedPrecision (const geom::PrecisionModel & fixedPM) private
Definition at line 220 of file BufferOp.cpp.
References geos::geom::Geometry::buffer(), geos::geom::PrecisionModel::getScale(), and geos::geom::PrecisionModel::getType().
 {
   PrecisionModel pm(1.0); // fixed as well
 #if 0 /* FIXME: MCIndexSnapRounder seems to be still bogus */
   snapround::MCIndexSnapRounder inoder(pm);
 #else
   algorithm::LineIntersector li(&fixedPM);
   IntersectionAdder ia(li);
   MCIndexNoder inoder(&ia);
 #endif
   ScaledNoder noder(inoder, fixedPM.getScale());
   BufferBuilder bufBuilder(bufParams);
   bufBuilder.setWorkingPrecisionModel(&fixedPM);
   bufBuilder.setNoder(&noder);
   // Reduce precision of the input geometry
   //
   // NOTE: this reduction is not in JTS and should supposedly
   //       not be needed because the PrecisionModel we pass
   //       to the BufferBuilder above (with setWorkingPrecisionModel)
   //       should be used to round coordinates emitted by the
   //       OffsetCurveBuilder, thus effectively producing a fully
   //       rounded input to the noder.
   //       Nonetheless the amount of scrambling done by rounding here
   //       is known to fix at least one case in which MCIndexNoder
   //       would fail: http://trac.osgeo.org/geos/ticket/605
   //
   // TODO: follow JTS in MCIndexSnapRounder usage
   //
   const Geometry *workGeom = argGeom;
   const PrecisionModel& argPM = *(argGeom->getFactory()->getPrecisionModel());
   std::unique_ptr<Geometry> fixedGeom;
   if ( argPM.getType() != PrecisionModel::FIXED || argPM.getScale() != fixedPM.getScale() )
   {
     using precision::GeometryPrecisionReducer;
     fixedGeom = GeometryPrecisionReducer::reduce(*argGeom, fixedPM);
     workGeom = fixedGeom.get();
   }
   // this may throw an exception, if robustness errors are encountered
   resultGeometry = bufBuilder.buffer(workGeom, distance);
 }
Geometry * geos::operation::buffer::BufferOp::bufferOp (const geom::Geometry * g, double distance, int quadrantSegments = BufferParameters::DEFAULT_QUADRANT_SEGMENTS, int endCapStyle = BufferParameters::CAP_ROUND) static
Computes the buffer for a geometry for a given buffer distance and accuracy of approximation.
Parameters
g the geometry to buffer
distance the buffer distance
quadrantSegments the number of segments used to approximate a quarter circle
Returns
the buffer of the input geometry
Definition at line 106 of file BufferOp.cpp.
References getResultGeometry(), setEndCapStyle(), and setQuadrantSegments().
 {
   BufferOp bufOp(g);
   bufOp.setQuadrantSegments(quadrantSegments);
   bufOp.setEndCapStyle(nEndCapStyle);
   return bufOp.getResultGeometry(distance);
 }
void geos::operation::buffer::BufferOp::bufferOriginalPrecision () private
Definition at line 182 of file BufferOp.cpp.
References geos::operation::buffer::BufferBuilder::buffer().
 {
   BufferBuilder bufBuilder(bufParams);
   //std::cerr<<"computing with original precision"<<std::endl;
   try
   {
     resultGeometry=bufBuilder.buffer(argGeom, distance);
   }
   catch (const util::TopologyException& ex)
   {
     // don't propagate the exception - it will be detected by
     // fact that resultGeometry is null
     saveException=ex;
     //std::cerr<<ex->toString()<<std::endl;
   }
   //std::cerr<<"done"<<std::endl;
 }
void geos::operation::buffer::BufferOp::bufferReducedPrecision (int precisionDigits) private
Definition at line 203 of file BufferOp.cpp.
 {
   double sizeBasedScaleFactor=precisionScaleFactor(argGeom, distance, precisionDigits);
 #if GEOS_DEBUG
   std::cerr << "recomputing with precision scale factor = "
     << sizeBasedScaleFactor
     << std::endl;
 #endif
   assert(sizeBasedScaleFactor>0);
   PrecisionModel fixedPM(sizeBasedScaleFactor);
   bufferFixedPrecision(fixedPM);
 }
void geos::operation::buffer::BufferOp::bufferReducedPrecision () private
Definition at line 151 of file BufferOp.cpp.
References MIN_PRECISION_DIGITS.
 {
   // try and compute with decreasing precision,
   // up to a min, to avoid gross results
   // (not in JTS, see http://trac.osgeo.org/geos/ticket/605)
 #define MIN_PRECISION_DIGITS 6
   for (int precDigits=MAX_PRECISION_DIGITS; precDigits >= MIN_PRECISION_DIGITS; precDigits--)
   {
 #if GEOS_DEBUG
     std::cerr<<"BufferOp::computeGeometry: trying with precDigits "<<precDigits<<std::endl;
 #endif
     try {
       bufferReducedPrecision(precDigits);
     } catch (const util::TopologyException& ex) {
       saveException=ex;
       // don't propagate the exception - it will be detected by fact that resultGeometry is null
     }
     if (resultGeometry!=nullptr) {
       // debug
       //if ( saveException ) std::cerr<<saveException->toString()<<std::endl;
       return;
     }
   }
   // tried everything - have to bail
   throw saveException;
 }
void geos::operation::buffer::BufferOp::computeGeometry () private
Definition at line 127 of file BufferOp.cpp.
References geos::geom::PrecisionModel::getType().
 {
 #if GEOS_DEBUG
   std::cerr<<"BufferOp::computeGeometry: trying with original precision"<<std::endl;
 #endif
   bufferOriginalPrecision();
   if (resultGeometry!=nullptr) return;
 #if GEOS_DEBUG
   std::cerr << "bufferOriginalPrecision failed (" << saveException.what() << "), trying with reduced precision"
             << std::endl;
 #endif
   const PrecisionModel& argPM = *(argGeom->getFactory()->getPrecisionModel());
   if ( argPM.getType() == PrecisionModel::FIXED )
     bufferFixedPrecision(argPM);
   else
     bufferReducedPrecision();
 }
Geometry * geos::operation::buffer::BufferOp::getResultGeometry (double nDistance)
Returns the buffer computed for a geometry for a given buffer distance.
Parameters
g the geometry to buffer
distance the buffer distance
Returns
the buffer of the input geometry
Definition at line 118 of file BufferOp.cpp.
Referenced by bufferOp().
 {
   distance=nDistance;
   computeGeometry();
   return resultGeometry;
 }
double geos::operation::buffer::BufferOp::precisionScaleFactor (const geom::Geometry * g, double distance, int maxPrecisionDigits) static private
Compute a reasonable scale factor to limit the precision of a given combination of Geometry and buffer distance. The scale factor is based on a heuristic.
Parameters
g the Geometry being buffered
distance the buffer distance
maxPrecisionDigits the mzx # of digits that should be allowed by the precision determined by the computed scale factor
Returns
a scale factor that allows a reasonable amount of precision for the buffer computation
Definition at line 82 of file BufferOp.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), and geos::geom::Envelope::getMinY().
 {
   const Envelope *env=g->getEnvelopeInternal();
   double envMax = std::max(
     std::max(fabs(env->getMaxX()), fabs(env->getMinX())),
     std::max(fabs(env->getMaxY()), fabs(env->getMinY()))
   );
   double expandByDistance = distance > 0.0 ? distance : 0.0;
   double bufEnvMax = envMax + 2 * expandByDistance;
   // the smallest power of 10 greater than the buffer envelope
   int bufEnvPrecisionDigits = (int) (std::log(bufEnvMax) / std::log(10.0) + 1.0);
   int minUnitLog10 = maxPrecisionDigits - bufEnvPrecisionDigits;
   double scaleFactor = std::pow(10.0, minUnitLog10);
   return scaleFactor;
 }
void geos::operation::buffer::BufferOp::setEndCapStyle (int nEndCapStyle) inline
Specifies the end cap style of the generated buffer. The styles supported are CAP_ROUND, CAP_BUTT, and CAP_SQUARE. The default is CAP_ROUND.
Parameters
endCapStyle the end cap style to specify
Definition at line 254 of file BufferOp.h.
Referenced by bufferOp().
 {
   bufParams.setEndCapStyle((BufferParameters::EndCapStyle)s);
 }
void geos::operation::buffer::BufferOp::setQuadrantSegments (int nQuadrantSegments) inline
Specifies the end cap style of the generated buffer. The styles supported are CAP_ROUND, CAP_BUTT, and CAP_SQUARE. The default is CAP_ROUND.
Parameters
endCapStyle the end cap style to specify
Definition at line 248 of file BufferOp.h.
Referenced by bufferOp().
 {
   bufParams.setQuadrantSegments(q);
 }
void geos::operation::buffer::BufferOp::setSingleSided (bool isSingleSided) inline
Sets whether the computed buffer should be single-sided.
A single-sided buffer is constructed on only one side of each input line.
The side used is determined by the sign of the buffer distance:
a positive distance indicates the left-hand side
a negative distance indicates the right-hand side
The single-sided buffer of point geometries is the same as the regular buffer.
The End Cap Style for single-sided buffers is always ignored, and forced to the equivalent of CAP_FLAT.
Parameters
isSingleSided true if a single-sided buffer should be constructed
Definition at line 260 of file BufferOp.h.
 {
    bufParams.setSingleSided(isSingleSided);
 }
Member Data Documentation
const geom::Geometry* geos::operation::buffer::BufferOp::argGeom private
Definition at line 110 of file BufferOp.h.
BufferParameters geos::operation::buffer::BufferOp::bufParams private
Definition at line 118 of file BufferOp.h.
double geos::operation::buffer::BufferOp::distance private
Definition at line 114 of file BufferOp.h.
const int geos::operation::buffer::BufferOp::MAX_PRECISION_DIGITS = 12 static private
A number of digits of precision which leaves some computational "headroom" for floating point operations.
This value should be less than the decimal precision of double-precision values (16).
Definition at line 89 of file BufferOp.h.
geom::Geometry* geos::operation::buffer::BufferOp::resultGeometry private
Definition at line 120 of file BufferOp.h.
util::TopologyException geos::operation::buffer::BufferOp::saveException private
Definition at line 112 of file BufferOp.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/BufferOp.h
/home/vicky/potree/geos/vicky/src/operation/buffer/BufferOp.cpp