GEOS: geos::operation::geounion::CascadedUnion Class Reference
geos::operation::geounion::CascadedUnion Class Reference
Provides an efficient method of unioning a collection of Geometries.
#include <CascadedUnion.h>
Public Member Functions
CascadedUnion ()
CascadedUnion (const std::vector< geom::Geometry * > *geoms)
geom::Geometry * Union ()
Static Public Member Functions
static geom::Geometry * Union (std::vector< geom::Geometry * > *geoms)
template<class T >
static geom::Geometry * Union (T start, T end)
Private Member Functions
geom::Geometry * unionTree (index::strtree::ItemsList *geomTree)
geom::Geometry * binaryUnion (GeometryListHolder *geoms)
geom::Geometry * binaryUnion (GeometryListHolder *geoms, std::size_t start, std::size_t end)
GeometryListHolder * reduceToGeometries (index::strtree::ItemsList *geomTree)
geom::Geometry * unionSafe (geom::Geometry *g0, geom::Geometry *g1)
geom::Geometry * unionOptimized (geom::Geometry *g0, geom::Geometry *g1)
geom::Geometry * unionUsingEnvelopeIntersection (geom::Geometry *g0, geom::Geometry *g1, geom::Envelope const &common)
geom::Geometry * extractByEnvelope (geom::Envelope const &env, geom::Geometry *geom, std::vector< geom::Geometry * > &disjointGeoms)
Static Private Member Functions
static geom::Geometry * unionActual (geom::Geometry *g0, geom::Geometry *g1)
Private Attributes
const std::vector< geom::Geometry * > * inputGeoms
geom::GeometryFactory const * geomFactory
Static Private Attributes
static int const STRTREE_NODE_CAPACITY = 4
Detailed Description
Provides an efficient method of unioning a collection of Geometries.
This algorithm is more robust than the simple iterated approach of repeatedly unioning each geometry to a result geometry.
Definition at line 55 of file CascadedUnion.h.
Constructor & Destructor Documentation
geos::operation::geounion::CascadedUnion::CascadedUnion ()
geos::operation::geounion::CascadedUnion::CascadedUnion (const std::vector< geom::Geometry * > * geoms) inline
Creates a new instance to union the given collection of Geometrys.
Parameters
geoms a collection of Geometryal Geometrys ownership of elements and vector are left to caller.
Definition at line 106 of file CascadedUnion.h.
       : inputGeoms(geoms),
         geomFactory(nullptr)
     {}
Member Function Documentation
geom::Geometry * geos::operation::geounion::CascadedUnion::binaryUnion (GeometryListHolder * geoms) private
Unions a list of geometries by treating the list as a flattened binary tree, and performing a cascaded union on the tree.
Definition at line 79 of file CascadedUnion.cpp.
Referenced by binaryUnion(), and unionTree().
 {
     return binaryUnion(geoms, 0, geoms->size());
 }
geom::Geometry * geos::operation::geounion::CascadedUnion::binaryUnion (GeometryListHolder * geoms, std::size_t start, std::size_t end) private
Unions a section of a list using a recursive binary union on each half of the section.
Parameters
geoms
start
end
Returns
the union of the list section
Definition at line 84 of file CascadedUnion.cpp.
References binaryUnion(), geos::operation::geounion::GeometryListHolder::getGeometry(), and unionSafe().
 {
     if (end - start <= 1) {
         return unionSafe(geoms->getGeometry(start), nullptr);
     }
     else if (end - start == 2) {
         return unionSafe(geoms->getGeometry(start), geoms->getGeometry(start + 1));
     }
     else {
         // recurse on both halves of the list
         std::size_t mid = (end + start) / 2;
         std::unique_ptr<geom::Geometry> g0 (binaryUnion(geoms, start, mid));
         std::unique_ptr<geom::Geometry> g1 (binaryUnion(geoms, mid, end));
         return unionSafe(g0.get(), g1.get());
     }
 }
geom::Geometry * geos::operation::geounion::CascadedUnion::extractByEnvelope (geom::Envelope const & env, geom::Geometry * geom, std::vector< geom::Geometry * > & disjointGeoms) private
Definition at line 173 of file CascadedUnion.cpp.
References geos::geom::GeometryFactory::buildGeometry(), geomFactory, geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getNumGeometries(), and geos::geom::Envelope::intersects().
Referenced by unionUsingEnvelopeIntersection().
 {
     std::vector<geom::Geometry*> intersectingGeoms;
     for (std::size_t i = 0; i < geom->getNumGeometries(); i++) {
         geom::Geometry* elem = const_cast<geom::Geometry*>(geom->getGeometryN(i));
         if (elem->getEnvelopeInternal()->intersects(env))
             intersectingGeoms.push_back(elem);
         else
             disjointGeoms.push_back(elem);
     }
     return geomFactory->buildGeometry(intersectingGeoms);
 }
GeometryListHolder * geos::operation::geounion::CascadedUnion::reduceToGeometries (index::strtree::ItemsList * geomTree) private
Reduces a tree of geometries to a list of geometries by recursively unioning the subtrees in the list.
Parameters
geomTree a tree-structured list of geometries
Returns
a list of Geometrys
Definition at line 103 of file CascadedUnion.cpp.
References geos::index::strtree::ItemsListItem::item_is_geometry, geos::index::strtree::ItemsListItem::item_is_list, and unionTree().
Referenced by unionTree().
 {
     std::unique_ptr<GeometryListHolder> geoms (new GeometryListHolder());
     typedef index::strtree::ItemsList::iterator iterator_type;
     iterator_type end = geomTree->end();
     for (iterator_type i = geomTree->begin(); i != end; ++i) {
         if ((*i).get_type() == index::strtree::ItemsListItem::item_is_list) {
             std::unique_ptr<geom::Geometry> geom (unionTree((*i).get_itemslist()));
             geoms->push_back_owned(geom.get());
             geom.release();
         }
         else if ((*i).get_type() == index::strtree::ItemsListItem::item_is_geometry) {
             geoms->push_back(reinterpret_cast<geom::Geometry*>((*i).get_geometry()));
         }
         else {
             assert(!static_cast<bool>("should never be reached"));
         }
     }
     return geoms.release();
 }
geom::Geometry * geos::operation::geounion::CascadedUnion::Union (std::vector< geom::Geometry * > * geoms) static
Computes the union of a collection of Geometrys.
Parameters
geoms a collection of Geometrys. ownership of elements and vector are left to caller.
Definition at line 35 of file CascadedUnion.cpp.
References Union().
Referenced by Union().
 {
     CascadedUnion op (polys);
     return op.Union();
 }
template<class T > static geom::Geometry* geos::operation::geounion::CascadedUnion::Union (T start, T end) inline static
Computes the union of a set of Geometrys.
Template Parameters
T an iterator yelding something castable to const Geometry *
Parameters
start start iterator
end end iterator
Definition at line 89 of file CascadedUnion.h.
     {
       std::vector<geom::Geometry*> polys;
       for (T i=start; i!=end; ++i) {
         const geom::Geometry* p = dynamic_cast<const geom::Geometry*>(*i);
         polys.push_back(const_cast<geom::Geometry*>(p));
       }
       return Union(&polys);
     }
geom::Geometry * geos::operation::geounion::CascadedUnion::Union ()
Computes the union of the input geometries.
Returns
the union of the input geometries
null if no input geometries were provided
A spatial index to organize the collection into groups of close geometries. This makes unioning more efficient, since vertices are more likely to be eliminated on each round.
Definition at line 41 of file CascadedUnion.cpp.
References geomFactory, geos::geom::Geometry::getEnvelopeInternal(), inputGeoms, geos::index::strtree::STRtree::insert(), geos::index::strtree::AbstractSTRtree::itemsTree(), STRTREE_NODE_CAPACITY, and unionTree().
Referenced by geos::operation::geounion::UnaryUnionOp::Union().
 {
     if (inputGeoms->empty())
         return nullptr;
     geomFactory = inputGeoms->front()->getFactory();
     index::strtree::STRtree index(STRTREE_NODE_CAPACITY);
     typedef std::vector<geom::Geometry*>::const_iterator iterator_type;
     iterator_type end = inputGeoms->end();
     for (iterator_type i = inputGeoms->begin(); i != end; ++i) {
         geom::Geometry* g = *i;
         index.insert(g->getEnvelopeInternal(), g);
     }
     std::unique_ptr<index::strtree::ItemsList> itemTree (index.itemsTree());
     return unionTree(itemTree.get());
 }
geom::Geometry * geos::operation::geounion::CascadedUnion::unionActual (geom::Geometry * g0, geom::Geometry * g1) static private
Encapsulates the actual unioning of two polygonal geometries.
Parameters
g0
g1
Returns
Definition at line 190 of file CascadedUnion.cpp.
References geos::geom::Geometry::Union().
Referenced by unionOptimized(), and unionUsingEnvelopeIntersection().
 {
     return g0->Union(g1);
 }
geom::Geometry * geos::operation::geounion::CascadedUnion::unionOptimized (geom::Geometry * g0, geom::Geometry * g1) private
Definition at line 141 of file CascadedUnion.cpp.
References geos::geom::util::GeometryCombiner::combine(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::getNumGeometries(), geos::geom::Envelope::intersection(), geos::geom::Envelope::intersects(), unionActual(), and unionUsingEnvelopeIntersection().
Referenced by unionSafe().
 {
     geom::Envelope const* g0Env = g0->getEnvelopeInternal();
     geom::Envelope const* g1Env = g1->getEnvelopeInternal();
     if (!g0Env->intersects(g1Env))
         return geom::util::GeometryCombiner::combine(g0, g1);
     if (g0->getNumGeometries() <= 1 && g1->getNumGeometries() <= 1)
         return unionActual(g0, g1);
     geom::Envelope commonEnv;
     g0Env->intersection(*g1Env, commonEnv);
     return unionUsingEnvelopeIntersection(g0, g1, commonEnv);
 }
geom::Geometry * geos::operation::geounion::CascadedUnion::unionSafe (geom::Geometry * g0, geom::Geometry * g1) private
Computes the union of two geometries, either of both of which may be null.
Parameters
g0 a Geometry
g1 a Geometry
Returns
the union of the input(s)
null if both inputs are null
Definition at line 127 of file CascadedUnion.cpp.
References geos::geom::Geometry::clone(), and unionOptimized().
Referenced by binaryUnion().
 {
     if (g0 == nullptr && g1 == nullptr)
         return nullptr;
     if (g0 == nullptr)
         return g1->clone();
     if (g1 == nullptr)
         return g0->clone();
     return unionOptimized(g0, g1);
 }
geom::Geometry * geos::operation::geounion::CascadedUnion::unionTree (index::strtree::ItemsList * geomTree) private
Recursively unions all subtrees in the list into single geometries. The result is a list of Geometry's only
Definition at line 68 of file CascadedUnion.cpp.
References binaryUnion(), and reduceToGeometries().
Referenced by reduceToGeometries(), and Union().
 {
     std::unique_ptr<GeometryListHolder> geoms(reduceToGeometries(geomTree));
     return binaryUnion(geoms.get());
 }
geom::Geometry * geos::operation::geounion::CascadedUnion::unionUsingEnvelopeIntersection (geom::Geometry * g0, geom::Geometry * g1, geom::Envelope const & common) private
Unions two geometries. The case of multi geometries is optimized to union only the components which lie in the intersection of the two geometry's envelopes. Geometrys outside this region can simply be combined with the union result, which is potentially much faster. This case is likely to occur often during cascaded union, and may also occur in real world data (such as unioning data for parcels on different street blocks).
Parameters
g0 a geometry
g1 a geometry
common the intersection of the envelopes of the inputs
Returns
the union of the inputs
Definition at line 158 of file CascadedUnion.cpp.
References geos::geom::util::GeometryCombiner::combine(), extractByEnvelope(), and unionActual().
Referenced by unionOptimized().
 {
     std::vector<geom::Geometry*> disjointPolys;
     std::unique_ptr<geom::Geometry> g0Int(extractByEnvelope(common, g0, disjointPolys));
     std::unique_ptr<geom::Geometry> g1Int(extractByEnvelope(common, g1, disjointPolys));
     std::unique_ptr<geom::Geometry> u(unionActual(g0Int.get(), g1Int.get()));
     disjointPolys.push_back(u.get());
     return geom::util::GeometryCombiner::combine(disjointPolys);
 }
Member Data Documentation
geom::GeometryFactory const* geos::operation::geounion::CascadedUnion::geomFactory private
Definition at line 59 of file CascadedUnion.h.
Referenced by extractByEnvelope(), and Union().
const std::vector<geom::Geometry*>* geos::operation::geounion::CascadedUnion::inputGeoms private
Definition at line 58 of file CascadedUnion.h.
Referenced by Union().
int const geos::operation::geounion::CascadedUnion::STRTREE_NODE_CAPACITY = 4 static private
The effectiveness of the index is somewhat sensitive to the node capacity. Testing indicates that a smaller capacity is better. For an STRtree, 4 is probably a good number (since this produces 2x2 "squares").
Definition at line 68 of file CascadedUnion.h.
Referenced by Union().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/union/CascadedUnion.h
/home/vicky/potree/geos/vicky/src/operation/union/CascadedUnion.cpp