GEOS: geos::noding::SinglePassNoder Class Reference
geos::noding::SinglePassNoder Class Reference abstract
#include <SinglePassNoder.h>
Public Member Functions
SinglePassNoder (SegmentIntersector *nSegInt=nullptr)
~SinglePassNoder () override
virtual void setSegmentIntersector (SegmentIntersector *newSegInt)
void computeNodes (std::vector< SegmentString * > *segStrings) override=0
std::vector< SegmentString * > * getNodedSubstrings () const override=0
Protected Attributes
SegmentIntersector * segInt
Externally owned.
Detailed Description
Base class for Noders which make a single pass to find intersections. This allows using a custom SegmentIntersector (which for instance may simply identify intersections, rather than insert them).
Last port: noding/SinglePassNoder.java rev. 1.3 (JTS-1.7)
TODO: Noder inheritance (that's just an interface!)
Definition at line 50 of file SinglePassNoder.h.
Constructor & Destructor Documentation
geos::noding::SinglePassNoder::SinglePassNoder (SegmentIntersector * nSegInt = nullptr) inline
Definition at line 59 of file SinglePassNoder.h.
 : segInt(nSegInt) {}
geos::noding::SinglePassNoder::~SinglePassNoder () inline override
Definition at line 61 of file SinglePassNoder.h.
 {}
Member Function Documentation
void geos::noding::SinglePassNoder::computeNodes (std::vector< SegmentString * > * segStrings) override pure virtual
Computes the noding for a collection of SegmentStrings.
Parameters
segStrings a collection of SegmentStrings to node
Implements geos::noding::Noder.
Implemented in geos::noding::MCIndexNoder, and geos::noding::SimpleNoder.
std::vector<SegmentString*>* geos::noding::SinglePassNoder::getNodedSubstrings () const override pure virtual
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
Returns
a Collection of SegmentStrings
Implements geos::noding::Noder.
Implemented in geos::noding::MCIndexNoder, and geos::noding::SimpleNoder.
virtual void geos::noding::SinglePassNoder::setSegmentIntersector (SegmentIntersector * newSegInt) inline virtual
Sets the SegmentIntersector to use with this noder. A SegmentIntersector will normally add intersection nodes to the input segment strings, but it may not - it may simply record the presence of intersections. However, some Noders may require that intersections be added.
Parameters
newSegInt
Definition at line 72 of file SinglePassNoder.h.
Referenced by geos::noding::FastNodingValidator::checkInteriorIntersections(), geos::noding::snapround::SimpleSnapRounder::findInteriorIntersections(), geos::noding::snapround::MCIndexSnapRounder::findInteriorIntersections(), and geos::noding::IteratedNoder::node().
{
     segInt = newSegInt;
   }
Member Data Documentation
SegmentIntersector* geos::noding::SinglePassNoder::segInt protected
Externally owned.
Definition at line 55 of file SinglePassNoder.h.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/noding/SinglePassNoder.h