GEOS: geos::noding::SegmentNodeList Class Reference
geos::noding::SegmentNodeList Class Reference
A list of the SegmentNode present along a NodedSegmentString.
#include <SegmentNodeList.h>
Public Types
typedef std::set< SegmentNode *, SegmentNodeLT > container
typedef container::iterator iterator
typedef container::const_iterator const_iterator
Public Member Functions
SegmentNodeList (const NodedSegmentString *newEdge)
SegmentNodeList (const NodedSegmentString &newEdge)
const NodedSegmentString & getEdge () const
virtual ~SegmentNodeList ()
SegmentNode * add (const geom::Coordinate &intPt, std::size_t segmentIndex)
SegmentNode * add (const geom::Coordinate *intPt, std::size_t segmentIndex)
std::set< SegmentNode *, SegmentNodeLT > * getNodes ()
size_t size () const
Return the number of nodes in this list.
container::iterator begin ()
container::const_iterator begin () const
container::iterator end ()
container::const_iterator end () const
void addEndpoints ()
void addSplitEdges (std::vector< SegmentString * > &edgeList)
void addSplitEdges (std::vector< SegmentString * > *edgeList)
Private Member Functions
void checkSplitEdgesCorrectness (std::vector< SegmentString * > &splitEdges)
SegmentString * createSplitEdge (SegmentNode *ei0, SegmentNode *ei1)
void addCollapsedNodes ()
void findCollapsesFromExistingVertices (std::vector< std::size_t > &collapsedVertexIndexes)
void findCollapsesFromInsertedNodes (std::vector< std::size_t > &collapsedVertexIndexes)
bool findCollapseIndex (SegmentNode &ei0, SegmentNode &ei1, size_t &collapsedVertexIndex)
SegmentNodeList (const SegmentNodeList &other)=delete
SegmentNodeList & operator= (const SegmentNodeList &rhs)=delete
Private Attributes
std::set< SegmentNode *, SegmentNodeLT > nodeMap
const NodedSegmentString & edge
Friends
std::ostream & operator<< (std::ostream &os, const SegmentNodeList &l)
Detailed Description
A list of the SegmentNode present along a NodedSegmentString.
Definition at line 56 of file SegmentNodeList.h.
Member Typedef Documentation
typedef container::const_iterator geos::noding::SegmentNodeList::const_iterator
Definition at line 121 of file SegmentNodeList.h.
typedef std::set<SegmentNode*,SegmentNodeLT> geos::noding::SegmentNodeList::container
Definition at line 119 of file SegmentNodeList.h.
typedef container::iterator geos::noding::SegmentNodeList::iterator
Definition at line 120 of file SegmentNodeList.h.
Constructor & Destructor Documentation
geos::noding::SegmentNodeList::SegmentNodeList (const SegmentNodeList & other) private delete
geos::noding::SegmentNodeList::SegmentNodeList (const NodedSegmentString * newEdge) inline
Definition at line 123 of file SegmentNodeList.h.
 : edge(*newEdge) {}
geos::noding::SegmentNodeList::SegmentNodeList (const NodedSegmentString & newEdge) inline
Definition at line 125 of file SegmentNodeList.h.
 : edge(newEdge) {}
geos::noding::SegmentNodeList::~SegmentNodeList () virtual
Definition at line 51 of file SegmentNodeList.cpp.
References geos::noding::SegmentNode::coord, and geos::geom::Coordinate::equals2D().
 {
   std::set<SegmentNode *, SegmentNodeLT>::iterator it=nodeMap.begin();
   for(; it!=nodeMap.end(); it++)
   {
     delete *it;
   }
 }
Member Function Documentation
SegmentNode* geos::noding::SegmentNodeList::add (const geom::Coordinate & intPt, std::size_t segmentIndex)
Adds an intersection into the list, if it isn't already there. The input segmentIndex is expected to be normalized.
Returns
the SegmentIntersection found or added. It will be destroyed at SegmentNodeList destruction time.
Parameters
intPt the intersection Coordinate, will be copied
segmentIndex
SegmentNode* geos::noding::SegmentNodeList::add (const geom::Coordinate * intPt, std::size_t segmentIndex) inline
Definition at line 145 of file SegmentNodeList.h.
{
     return add(*intPt, segmentIndex);
   }
void geos::noding::SegmentNodeList::addCollapsedNodes () private
Adds nodes for any collapsed edge pairs. Collapsed edge pairs can be caused by inserted nodes, or they can be pre-existing in the edge vertex list. In order to provide the correct fully noded semantics, the vertex at the base of a collapsed pair must also be added as a node.
Definition at line 88 of file SegmentNodeList.cpp.
 {
   std::vector<size_t> collapsedVertexIndexes;
   findCollapsesFromInsertedNodes(collapsedVertexIndexes);
   findCollapsesFromExistingVertices(collapsedVertexIndexes);
   // node the collapses
   for (std::vector<size_t>::iterator
     i=collapsedVertexIndexes.begin(),
       e=collapsedVertexIndexes.end();
     i != e; ++i)
   {
     auto vertexIndex = static_cast<unsigned int>(*i);
     add(edge.getCoordinate(vertexIndex), vertexIndex);
   }
 }
void geos::noding::SegmentNodeList::addEndpoints ()
Adds entries for the first and last points of the edge to the list
Definition at line 79 of file SegmentNodeList.cpp.
 {
   int maxSegIndex = edge.size() - 1;
   add(&(edge.getCoordinate(0)), 0);
   add(&(edge.getCoordinate(maxSegIndex)), maxSegIndex);
 }
void geos::noding::SegmentNodeList::addSplitEdges (std::vector< SegmentString * > & edgeList)
Creates new edges for all the edges that the intersections in this list split the parent edge into. Adds the edges to the input list (this is so a single list can be used to accumulate all split edges for a Geometry).
Definition at line 174 of file SegmentNodeList.cpp.
References geos::noding::SegmentNode::compareTo().
Referenced by geos::noding::NodedSegmentString::getNodedSubstrings().
 {
   // testingOnly
 #if GEOS_DEBUG
   std::cerr<<__FUNCTION__<<" entered"<<std::endl;
   std::vector<SegmentString*> testingSplitEdges;
 #endif
   // ensure that the list has entries for the first and last
   // point of the edge
   addEndpoints();
   addCollapsedNodes();
   // there should always be at least two entries in the list
   // since the endpoints are nodes
   iterator it=begin();
   SegmentNode *eiPrev=*it;
   assert(eiPrev);
   it++;
   for(iterator itEnd=end(); it!=itEnd; ++it)
   {
     SegmentNode *ei=*it;
     assert(ei);
     if ( ! ei->compareTo(*eiPrev) ) continue;
     SegmentString *newEdge=createSplitEdge(eiPrev, ei);
     edgeList.push_back(newEdge);
 #if GEOS_DEBUG
     testingSplitEdges.push_back(newEdge);
 #endif
     eiPrev = ei;
   }
 #if GEOS_DEBUG
   std::cerr<<__FUNCTION__<<" finished, now checking correctness"<<std::endl;
   checkSplitEdgesCorrectness(testingSplitEdges);
 #endif
 }
void geos::noding::SegmentNodeList::addSplitEdges (std::vector< SegmentString * > * edgeList) inline
Definition at line 177 of file SegmentNodeList.h.
References geos::geom::operator<<().
{
     assert(edgeList);
     addSplitEdges(*edgeList);
   }
container::iterator geos::noding::SegmentNodeList::begin () inline
Definition at line 159 of file SegmentNodeList.h.
 { return nodeMap.begin(); }
container::const_iterator geos::noding::SegmentNodeList::begin () const inline
Definition at line 160 of file SegmentNodeList.h.
 { return nodeMap.begin(); }
void geos::noding::SegmentNodeList::checkSplitEdgesCorrectness (std::vector< SegmentString * > & splitEdges) private
Checks the correctness of the set of split edges corresponding to this edge
Parameters
splitEdges the split edges for this edge (in order)
Definition at line 216 of file SegmentNodeList.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::noding::SegmentString::getCoordinate(), geos::geom::CoordinateSequence::getSize(), and geos::geom::Coordinate::toString().
 {
   const CoordinateSequence *edgePts=edge.getCoordinates();
   assert(edgePts);
   // check that first and last points of split edges
   // are same as endpoints of edge
   SegmentString *split0=splitEdges[0];
   assert(split0);
   const Coordinate& pt0=split0->getCoordinate(0);
   if (!(pt0==edgePts->getAt(0)))
     throw util::GEOSException("bad split edge start point at " + pt0.toString());
   SegmentString *splitn=splitEdges[splitEdges.size()-1];
   assert(splitn);
   const CoordinateSequence *splitnPts=splitn->getCoordinates();
   assert(splitnPts);
   const Coordinate &ptn=splitnPts->getAt(splitnPts->getSize()-1);
   if (!(ptn==edgePts->getAt(edgePts->getSize()-1)))
     throw util::GEOSException("bad split edge end point at " + ptn.toString());
 }
SegmentString * geos::noding::SegmentNodeList::createSplitEdge (SegmentNode * ei0, SegmentNode * ei1) private
Create a new "split edge" with the section of points between (and including) the two intersections. The label for the new edge is the same as the label for the parent edge.
ownership of return value is transferred
Definition at line 243 of file SegmentNodeList.cpp.
References geos::noding::SegmentNode::coord, geos::geom::Coordinate::equals2D(), geos::noding::SegmentNode::isInterior(), geos::noding::SegmentNode::segmentIndex, and geos::geom::CoordinateSequence::setAt().
 {
   assert(ei0);
   assert(ei1);
   size_t npts = ei1->segmentIndex - ei0->segmentIndex + 2;
   const Coordinate &lastSegStartPt=edge.getCoordinate(ei1->segmentIndex);
   // if the last intersection point is not equal to the its
   // segment start pt, add it to the points list as well.
   // (This check is needed because the distance metric is not
   // totally reliable!)
   // The check for point equality is 2D only - Z values are ignored
   // Added check for npts being == 2 as in that case NOT using second point
   // would mean creating a SegmentString with a single point
   // FIXME: check with mbdavis about this, ie: is it a bug in the caller ?
   //
   bool useIntPt1 = npts == 2 || (ei1->isInterior() || ! ei1->coord.equals2D(lastSegStartPt));
   if (! useIntPt1) {
     npts--;
   }
   CoordinateSequence *pts = new CoordinateArraySequence(npts);
   size_t ipt = 0;
   pts->setAt(ei0->coord, ipt++);
   for (size_t i=ei0->segmentIndex+1; i<=ei1->segmentIndex; i++)
   {
     pts->setAt(edge.getCoordinate(static_cast<unsigned int>(i)),ipt++);
   }
   if (useIntPt1)  pts->setAt(ei1->coord, ipt++);
   // SegmentString takes ownership of CoordinateList 'pts'
   SegmentString *ret = new NodedSegmentString(pts, edge.getData());
 #if GEOS_DEBUG
   std::cerr<<" SegmentString created"<<std::endl;
 #endif
   return ret;
 }
container::iterator geos::noding::SegmentNodeList::end () inline
Definition at line 161 of file SegmentNodeList.h.
 { return nodeMap.end(); }
container::const_iterator geos::noding::SegmentNodeList::end () const inline
Definition at line 162 of file SegmentNodeList.h.
 { return nodeMap.end(); }
bool geos::noding::SegmentNodeList::findCollapseIndex (SegmentNode & ei0, SegmentNode & ei1, size_t & collapsedVertexIndex) private
Definition at line 151 of file SegmentNodeList.cpp.
References geos::noding::SegmentNode::coord, geos::geom::Coordinate::equals2D(), geos::noding::SegmentNode::isInterior(), and geos::noding::SegmentNode::segmentIndex.
 {
   // only looking for equal nodes
   if (! ei0.coord.equals2D(ei1.coord)) return false;
   int numVerticesBetween = ei1.segmentIndex - ei0.segmentIndex;
   if (! ei1.isInterior()) {
     numVerticesBetween--;
   }
   // if there is a single vertex between the two equal nodes,
   // this is a collapse
   if (numVerticesBetween == 1) {
     collapsedVertexIndex = ei0.segmentIndex + 1;
     return true;
   }
   return false;
 }
void geos::noding::SegmentNodeList::findCollapsesFromExistingVertices (std::vector< std::size_t > & collapsedVertexIndexes) private
Adds nodes for any collapsed edge pairs which are pre-existing in the vertex list.
Definition at line 109 of file SegmentNodeList.cpp.
References geos::geom::Coordinate::equals2D().
 {
   if ( edge.size() < 2 ) return; // or we'll never exit the loop below
   for (size_t i=0, n=edge.size()-2; i<n; ++i)
   {
     const Coordinate& p0 = edge.getCoordinate(static_cast<unsigned int>(i));
     const Coordinate& p2 = edge.getCoordinate(static_cast<unsigned int>(i + 2));
     if (p0.equals2D(p2)) {
       // add base of collapse as node
       collapsedVertexIndexes.push_back(i + 1);
     }
   }
 }
void geos::noding::SegmentNodeList::findCollapsesFromInsertedNodes (std::vector< std::size_t > & collapsedVertexIndexes) private
Adds nodes for any collapsed edge pairs caused by inserted nodes Collapsed edge pairs occur when the same coordinate is inserted as a node both before and after an existing edge vertex. To provide the correct fully noded semantics, the vertex must be added as a node as well.
Definition at line 127 of file SegmentNodeList.cpp.
 {
   size_t collapsedVertexIndex;
   // there should always be at least two entries in the list,
   // since the endpoints are nodes
   iterator it = begin();
   SegmentNode* eiPrev = *it;
   ++it;
   for(iterator itEnd=end(); it!=itEnd; ++it)
   {
     SegmentNode *ei=*it;
           bool isCollapsed = findCollapseIndex(*eiPrev, *ei,
         collapsedVertexIndex);
     if (isCollapsed)
       collapsedVertexIndexes.push_back(collapsedVertexIndex);
     eiPrev = ei;
   }
 }
const NodedSegmentString& geos::noding::SegmentNodeList::getEdge () const inline
Definition at line 127 of file SegmentNodeList.h.
 { return edge; }
std::set<SegmentNode*,SegmentNodeLT>* geos::noding::SegmentNodeList::getNodes () inline
Definition at line 154 of file SegmentNodeList.h.
 { return &nodeMap; }
SegmentNodeList& geos::noding::SegmentNodeList::operator= (const SegmentNodeList & rhs) private delete
size_t geos::noding::SegmentNodeList::size () const inline
Return the number of nodes in this list.
Definition at line 157 of file SegmentNodeList.h.
 { return nodeMap.size(); }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const SegmentNodeList & l) friend
Definition at line 289 of file SegmentNodeList.cpp.
 {
   os << "Intersections: (" << nlist.nodeMap.size() << "):" << std::endl;
   std::set<SegmentNode*,SegmentNodeLT>::const_iterator
       it = nlist.nodeMap.begin(),
       itEnd = nlist.nodeMap.end();
   for(; it!=itEnd; it++)
   {
     SegmentNode *ei=*it;
     os << " " << *ei;
   }
   return os;
 }
Member Data Documentation
const NodedSegmentString& geos::noding::SegmentNodeList::edge private
Definition at line 61 of file SegmentNodeList.h.
std::set<SegmentNode*,SegmentNodeLT> geos::noding::SegmentNodeList::nodeMap private
Definition at line 58 of file SegmentNodeList.h.
Referenced by geos::noding::operator<<().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/SegmentNodeList.h
/home/vicky/potree/geos/vicky/src/noding/SegmentNodeList.cpp