GEOS: geos::simplify::LineSegmentIndex Class Reference
geos::simplify::LineSegmentIndex Class Reference
#include <LineSegmentIndex.h>
Public Member Functions
LineSegmentIndex ()
~LineSegmentIndex ()
void add (const TaggedLineString &line)
void add (const geom::LineSegment *seg)
void remove (const geom::LineSegment *seg)
std::unique_ptr< std::vector< geom::LineSegment * > > query (const geom::LineSegment *seg) const
Private Member Functions
LineSegmentIndex (const LineSegmentIndex &)
LineSegmentIndex & operator= (const LineSegmentIndex &)
Private Attributes
std::unique_ptr< index::quadtree::Quadtree > index
std::vector< geom::Envelope * > newEnvelopes
Detailed Description
Definition at line 54 of file LineSegmentIndex.h.
Constructor & Destructor Documentation
geos::simplify::LineSegmentIndex::LineSegmentIndex ()
Definition at line 109 of file LineSegmentIndex.cpp.
   :
   index(new Quadtree())
 {
 }
geos::simplify::LineSegmentIndex::~LineSegmentIndex ()
Definition at line 116 of file LineSegmentIndex.cpp.
References newEnvelopes.
 {
   for (size_t i=0, n=newEnvelopes.size(); i<n; ++i)
   {
     delete newEnvelopes[i];
   }
 }
geos::simplify::LineSegmentIndex::LineSegmentIndex (const LineSegmentIndex &) private
Member Function Documentation
void geos::simplify::LineSegmentIndex::add (const TaggedLineString & line)
Definition at line 126 of file LineSegmentIndex.cpp.
References geos::simplify::TaggedLineString::getSegments().
Referenced by geos::simplify::TaggedLineStringSimplifier::flatten().
 {
   const vector<TaggedLineSegment*>& segs = line.getSegments();
   for (size_t i=0, n=segs.size(); i<n; ++i)
   {
     const LineSegment* seg = segs[i];
     add(seg);
   }
 }
void geos::simplify::LineSegmentIndex::add (const geom::LineSegment * seg)
Definition at line 138 of file LineSegmentIndex.cpp.
References index, newEnvelopes, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   Envelope* env = new Envelope(seg->p0, seg->p1);
   newEnvelopes.push_back(env);
   // We need a cast because index wants a non-const,
   // altought it won't change the argument
   index->insert(env, (LineSegment*)seg);
 }
LineSegmentIndex& geos::simplify::LineSegmentIndex::operator= (const LineSegmentIndex &) private
unique_ptr< vector< LineSegment * > > geos::simplify::LineSegmentIndex::query (const geom::LineSegment * seg) const
Definition at line 161 of file LineSegmentIndex.cpp.
References geos::simplify::LineSegmentVisitor::getItems(), index, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by geos::simplify::TaggedLineStringSimplifier::hasBadInputIntersection(), and geos::simplify::TaggedLineStringSimplifier::hasBadOutputIntersection().
 {
   Envelope env(querySeg->p0, querySeg->p1);
   LineSegmentVisitor visitor(querySeg);
   index->query(&env, visitor);
   unique_ptr< vector<LineSegment*> > itemsFound = visitor.getItems();
   return itemsFound;
 }
void geos::simplify::LineSegmentIndex::remove (const geom::LineSegment * seg)
Definition at line 150 of file LineSegmentIndex.cpp.
References index, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by geos::simplify::TaggedLineStringSimplifier::remove().
 {
   Envelope env(seg->p0, seg->p1);
   // We need a cast because index wants a non-const
   // altought it won't change the argument
   index->remove(&env, (LineSegment*)seg);
 }
Member Data Documentation
std::unique_ptr<index::quadtree::Quadtree> geos::simplify::LineSegmentIndex::index private
Definition at line 73 of file LineSegmentIndex.h.
Referenced by add(), query(), and remove().
std::vector<geom::Envelope*> geos::simplify::LineSegmentIndex::newEnvelopes private
Definition at line 75 of file LineSegmentIndex.h.
Referenced by add(), and ~LineSegmentIndex().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/simplify/LineSegmentIndex.h
/home/vicky/potree/geos/vicky/src/simplify/LineSegmentIndex.cpp