GEOS: geos::geom::CoordinateSequence Class Reference
geos::geom::CoordinateSequence Class Reference abstract
The internal representation of a list of coordinates inside a Geometry.
#include <geos.h>
Public Types
enum { X, Y, Z, M }
Standard ordinate index values.
typedef std::unique_ptr< CoordinateSequence > Ptr
Public Member Functions
virtual ~CoordinateSequence ()
virtual CoordinateSequence * clone () const =0
Returns a deep copy of this collection.
virtual const Coordinate & getAt (std::size_t i) const =0
Returns a read-only reference to Coordinate at position i.
const Coordinate & back () const
Return last Coordinate in the sequence.
const Coordinate & front () const
Return first Coordinate in the sequence.
const Coordinate & operator[] (std::size_t i) const
virtual void getAt (std::size_t i, Coordinate &c) const =0
Write Coordinate at position i to given Coordinate.
virtual std::size_t getSize () const =0
Returns the number of Coordinates (actual or otherwise, as this implementation may not store its data in Coordinate objects).
size_t size () const
virtual const std::vector< Coordinate > * toVector () const =0
Returns a read-only vector with the Coordinates in this collection.
virtual void toVector (std::vector< Coordinate > &coords) const =0
Pushes all Coordinates of this sequence onto the provided vector.
void add (const std::vector< Coordinate > *vc, bool allowRepeated)
Add an array of coordinates.
void add (const CoordinateSequence *cl, bool allowRepeated, bool direction)
Add an array of coordinates.
virtual void add (const Coordinate &c, bool allowRepeated)
Add a coordinate.
virtual void add (std::size_t i, const Coordinate &coord, bool allowRepeated)=0
Inserts the specified coordinate at the specified position in this list.
virtual bool isEmpty () const =0
Returns true it list contains no coordinates.
virtual void add (const Coordinate &c)=0
Add a Coordinate to the list.
virtual void setAt (const Coordinate &c, std::size_t pos)=0
Get a reference to Coordinate at position pos.
virtual void deleteAt (std::size_t pos)=0
Delete Coordinate at position pos (list will shrink).
virtual std::string toString () const =0
Get a string rapresentation of CoordinateSequence.
virtual void setPoints (const std::vector< Coordinate > &v)=0
Substitute Coordinate list with a copy of the given vector.
bool hasRepeatedPoints () const
Returns true if contains any two consecutive points.
const Coordinate * minCoordinate () const
Returns lower-left Coordinate in list.
virtual CoordinateSequence & removeRepeatedPoints ()=0
Remove consecutive equal Coordinates from the sequence.
virtual std::size_t getDimension () const =0
virtual double getOrdinate (std::size_t index, std::size_t ordinateIndex) const =0
virtual double getX (std::size_t index) const
virtual double getY (std::size_t index) const
virtual void setOrdinate (std::size_t index, std::size_t ordinateIndex, double value)=0
virtual void expandEnvelope (Envelope &env) const
virtual void apply_rw (const CoordinateFilter *filter)=0
virtual void apply_ro (CoordinateFilter *filter) const =0
template<class T >
void applyCoordinateFilter (T &f)
Apply a fiter to each Coordinate of this sequence. The filter is expected to provide a .filter(Coordinate&) method.
Static Public Member Functions
static CoordinateSequence * removeRepeatedPoints (const CoordinateSequence *cl)
Returns a new CoordinateSequence being a copy of the input with any consecutive equal Coordinate removed.
static bool hasRepeatedPoints (const CoordinateSequence *cl)
Returns true if given CoordinateSequence contains any two consecutive Coordinate.
static CoordinateSequence * atLeastNCoordinatesOrNothing (std::size_t n, CoordinateSequence *c)
Returns either the given CoordinateSequence if its length is greater than the given amount, or an empty CoordinateSequence.
static const Coordinate * minCoordinate (CoordinateSequence *cl)
Returns lower-left Coordinate in given CoordinateSequence. This is actually the Coordinate with lower X (and Y if needed) ordinate.
static int indexOf (const Coordinate *coordinate, const CoordinateSequence *cl)
Return position of a Coordinate, or -1 if not found.
static bool equals (const CoordinateSequence *cl1, const CoordinateSequence *cl2)
Returns true if the two arrays are identical, both null, or pointwise equal.
static void scroll (CoordinateSequence *cl, const Coordinate *firstCoordinate)
Scroll given CoordinateSequence so to start with given Coordinate.
static int increasingDirection (const CoordinateSequence &pts)
Determines which orientation of the Coordinate array is (overall) increasing.
static void reverse (CoordinateSequence *cl)
Reverse Coordinate order in given CoordinateSequence.
Protected Member Functions
CoordinateSequence ()
CoordinateSequence (const CoordinateSequence &)
Detailed Description
The internal representation of a list of coordinates inside a Geometry.
There are some cases in which you might want Geometries to store their points using something other than the GEOS Coordinate class. For example, you may want to experiment with another implementation, such as an array of Xs and an array of Ys. or you might want to use your own coordinate class, one that supports extra attributes like M-values.
You can do this by implementing the CoordinateSequence and CoordinateSequenceFactory interfaces. You would then create a GeometryFactory parameterized by your CoordinateSequenceFactory, and use this GeometryFactory to create new Geometries. All of these new Geometries will use your CoordinateSequence implementation.
Definition at line 59 of file CoordinateSequence.h.
Member Typedef Documentation
typedef std::unique_ptr<CoordinateSequence> geos::geom::CoordinateSequence::Ptr
Definition at line 69 of file CoordinateSequence.h.
Member Enumeration Documentation
anonymous enum
Standard ordinate index values.
Enumerator
X
Y
Z
M
Definition at line 302 of file CoordinateSequence.h.
 { X,Y,Z,M };
Constructor & Destructor Documentation
geos::geom::CoordinateSequence::CoordinateSequence () inline protected
Definition at line 63 of file CoordinateSequence.h.
 {}
geos::geom::CoordinateSequence::CoordinateSequence (const CoordinateSequence &) inline protected
Definition at line 65 of file CoordinateSequence.h.
 {}
virtual geos::geom::CoordinateSequence::~CoordinateSequence () inline virtual
Definition at line 71 of file CoordinateSequence.h.
 {}
Member Function Documentation
void geos::geom::CoordinateSequence::add (const std::vector< Coordinate > * vc, bool allowRepeated)
Add an array of coordinates.
Parameters
vc The coordinates
allowRepeated if set to false, repeated coordinates are collapsed
Returns
true (as by general collection contract)
Definition at line 191 of file CoordinateSequence.cpp.
Referenced by geos::linearref::LinearGeometryBuilder::add(), geos::operation::polygonize::EdgeRing::addEdge(), geos::geomgraph::EdgeRing::addPoints(), geos::operation::linemerge::EdgeString::getCoordinates(), geos::io::WKTReader::getCoordinates(), geos::algorithm::MinimumDiameter::getDiameter(), geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), geos::algorithm::MinimumDiameter::getSupportingSegment(), geos::operation::distance::DistanceOp::nearestPoints(), geos::geom::Polygon::normalize(), geos::noding::SegmentIntersectionDetector::processIntersections(), geos::io::WKTReader::readMultiPointText(), geos::operation::intersection::RectangleIntersectionBuilder::reconnect(), geos::geom::GeometryFactory::toGeometry(), and geos::geom::LineSegment::toGeometry().
 {
   assert(vc);
   for(size_t i=0; i<vc->size(); ++i)
   {
     add((*vc)[i], allowRepeated);
   }
 }
void geos::geom::CoordinateSequence::add (const CoordinateSequence * cl, bool allowRepeated, bool direction)
Add an array of coordinates.
Parameters
cl The coordinates
allowRepeated if set to false, repeated coordinates are collapsed
direction if false, the array is added in reverse order
Returns
true (as by general collection contract)
Definition at line 225 of file CoordinateSequence.cpp.
References getAt(), and getSize().
 {
   // FIXME:  don't rely on negative values for 'j' (the reverse case)
   const int npts = static_cast<int>(cl->getSize());
   if (direction) {
     for (int i=0; i<npts; i++) {
       add(cl->getAt(i), allowRepeated);
     }
   } else {
     for (int j=npts-1; j>=0; j--) {
       add(cl->getAt(j), allowRepeated);
     }
   }
 }
void geos::geom::CoordinateSequence::add (const Coordinate & c, bool allowRepeated) virtual
Add a coordinate.
Parameters
c The coordinate to add
allowRepeated if set to false, repeated coordinates are collapsed
Returns
true (as by general collection contract)
Reimplemented in geos::geom::CoordinateArraySequence.
Definition at line 202 of file CoordinateSequence.cpp.
References geos::geom::Coordinate::equals2D().
 {
   if (!allowRepeated) {
         std::size_t npts=getSize();
     if (npts>=1) {
       const Coordinate& last=getAt(npts-1);
       if (last.equals2D(c))
                 return;
     }
   }
   add(c);
 }
virtual void geos::geom::CoordinateSequence::add (std::size_t i, const Coordinate & coord, bool allowRepeated) pure virtual
Inserts the specified coordinate at the specified position in this list.
Parameters
i the position at which to insert
coord the coordinate to insert
allowRepeated if set to false, repeated coordinates are collapsed
NOTE: this is a CoordinateList interface in JTS
Implemented in geos::geom::CoordinateArraySequence.
virtual void geos::geom::CoordinateSequence::add (const Coordinate & c) pure virtual
Add a Coordinate to the list.
Implemented in geos::geom::CoordinateArraySequence.
virtual void geos::geom::CoordinateSequence::apply_ro (CoordinateFilter * filter) const pure virtual
Implemented in geos::geom::CoordinateArraySequence.
virtual void geos::geom::CoordinateSequence::apply_rw (const CoordinateFilter * filter) pure virtual
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::noding::ScaledNoder::rescale(), and geos::noding::ScaledNoder::scale().
template<class T > void geos::geom::CoordinateSequence::applyCoordinateFilter (T & f) inline
Apply a fiter to each Coordinate of this sequence. The filter is expected to provide a .filter(Coordinate&) method.
TODO: accept a Functor instead, will be more flexible. actually, define iterators on Geometry
Definition at line 372 of file CoordinateSequence.h.
References GEOS_DLL, geos::geom::operator!=(), geos::geom::operator<<(), and geos::geom::operator==().
   {
     Coordinate c;
     for(std::size_t i=0, n=size(); i<n; ++i)
     {
       getAt(i, c);
       f.filter(c);
       setAt(c, i);
     }
   }
CoordinateSequence * geos::geom::CoordinateSequence::atLeastNCoordinatesOrNothing (std::size_t n, CoordinateSequence * c) static
Returns either the given CoordinateSequence if its length is greater than the given amount, or an empty CoordinateSequence.
Definition at line 55 of file CoordinateSequence.cpp.
References getSize().
 {
   if ( c->getSize() >= n )
   {
     return c;
   }
   else
   {
     // FIXME: return NULL rather then empty coordinate array
     return CoordinateArraySequenceFactory::instance()->create();
   }
 }
const Coordinate& geos::geom::CoordinateSequence::back () const inline
Return last Coordinate in the sequence.
Definition at line 88 of file CoordinateSequence.h.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::operation::buffer::OffsetSegmentString::closeRing(), and geos::operation::buffer::OffsetSegmentString::isRedundant().
{
     return getAt(size()-1);
   }
virtual CoordinateSequence* geos::geom::CoordinateSequence::clone () const pure virtual
Returns a deep copy of this collection.
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::operation::overlay::LineBuilder::buildLines(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createLineString(), geos::geom::GeometryFactory::createPoint(), GEOSCoordSeq_clone_r(), geos::operation::buffer::OffsetCurveBuilder::getRingCurve(), geos::triangulate::VoronoiDiagramBuilder::setSites(), geos::triangulate::DelaunayTriangulationBuilder::setSites(), geos::noding::GeometryNoder::toGeometry(), geos::geomgraph::EdgeNodingValidator::toSegmentStrings(), and geos::geom::util::GeometryTransformer::transformCoordinates().
virtual void geos::geom::CoordinateSequence::deleteAt (std::size_t pos) pure virtual
Delete Coordinate at position pos (list will shrink).
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::geom::Polygon::normalize().
bool geos::geom::CoordinateSequence::equals (const CoordinateSequence * cl1, const CoordinateSequence * cl2) static
Returns true if the two arrays are identical, both null, or pointwise equal.
Definition at line 174 of file CoordinateSequence.cpp.
References getAt(), and getSize().
 {
   // FIXME: use std::equals()
   if (cl1==cl2) return true;
   if (cl1==nullptr||cl2==nullptr) return false;
   size_t npts1=cl1->getSize();
   if (npts1!=cl2->getSize()) return false;
   for (size_t i=0; i<npts1; i++) {
     if (!(cl1->getAt(i)==cl2->getAt(i))) return false;
   }
   return true;
 }
void geos::geom::CoordinateSequence::expandEnvelope (Envelope & env) const virtual
Expands the given Envelope to include the coordinates in the sequence. Allows implementing classes to optimize access to coordinate values.
Parameters
env the envelope to expand
Reimplemented in geos::geom::CoordinateArraySequence.
Definition at line 265 of file CoordinateSequence.cpp.
References geos::geom::Envelope::expandToInclude().
Referenced by geos::triangulate::DelaunayTriangulationBuilder::create().
 {
   const std::size_t size = getSize();
   for (std::size_t i=0; i<size; i++)
         env.expandToInclude(getAt(i));
 }
const Coordinate& geos::geom::CoordinateSequence::front () const inline
Return first Coordinate in the sequence.
Definition at line 93 of file CoordinateSequence.h.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), and geos::operation::buffer::OffsetSegmentString::closeRing().
{
     return getAt(0);
   }
virtual const Coordinate& geos::geom::CoordinateSequence::getAt (std::size_t i) const pure virtual
Returns a read-only reference to Coordinate at position i.
Whether or not the Coordinate returned is the actual underlying Coordinate or merely a copy depends on the implementation.
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::algorithm::CentroidLine::add(), geos::operation::overlay::ElevationMatrix::add(), geos::algorithm::CentroidArea::add(), add(), geos::operation::polygonize::EdgeRing::addEdge(), geos::geomgraph::GeometryGraph::addEdge(), geos::algorithm::InteriorPointLine::addEndpoints(), geos::geomgraph::EdgeIntersectionList::addEndpoints(), geos::algorithm::CentroidArea::addHole(), geos::algorithm::InteriorPointLine::addInterior(), geos::geomgraph::Edge::addIntersection(), geos::geomgraph::index::SegmentIntersector::addIntersections(), geos::geomgraph::GeometryGraph::addLineString(), geos::geomgraph::EdgeRing::addPoints(), geos::geomgraph::GeometryGraph::addPolygonRing(), geos::algorithm::CentroidArea::addShell(), geos::algorithm::SIRtreePointInRing::buildIndex(), geos::operation::buffer::RightmostEdgeFinder::checkForRightmostCoordinate(), geos::noding::NodingValidator::checkInteriorIntersections(), geos::operation::valid::IsValidOp::checkInvalidCoordinates(), geos::noding::SegmentNodeList::checkSplitEdgesCorrectness(), geos::algorithm::MinimumDiameter::computeConvexRingMinDiameter(), geos::algorithm::distance::DistanceToPoint::computeDistance(), geos::geomgraph::index::MonotoneChainEdge::computeIntersectsForChain(), geos::operation::distance::FacetSequence::computeLineLineDistance(), geos::operation::distance::DistanceOp::computeMinDistance(), geos::operation::distance::FacetSequence::computePointLineDistance(), geos::noding::snapround::SimpleSnapRounder::computeVertexSnaps(), geos::geom::CoordinateArraySequence::CoordinateArraySequence(), geos::geom::GeometryFactory::createMultiPoint(), geos::geomgraph::EdgeIntersectionList::createSplitEdge(), geos::operation::distance::FacetSequence::distance(), geos::operation::intersection::distance(), geos::precision::PrecisionReducerCoordinateOperation::edit(), geos::geomgraph::Edge::equals(), equals(), geos::algorithm::distance::DiscreteHausdorffDistance::MaxDensifiedByFractionDistanceFilter::filter_ro(), geos::geomgraph::index::MonotoneChainIndexer::findChainEnd(), geos::operation::valid::ConnectedInteriorTester::findDifferentPoint(), geos::geomgraph::PlanarGraph::findEdge(), geos::geomgraph::PlanarGraph::findEdgeInSameDirection(), geos::simplify::TaggedLineStringSimplifier::findFurthestPoint(), geos::algorithm::MinimumDiameter::findMaxPerpDistance(), geos::operation::valid::IsValidOp::findPtNotNode(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtVertex(), geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments(), geos::simplify::TaggedLineStringSimplifier::flatten(), geos::operation::overlay::OverlayOp::getAverageZ(), geos::geomgraph::Edge::getCollapsedEdge(), geos::operation::distance::FacetSequence::getCoordinate(), geos::geomgraph::Edge::getCoordinate(), geos::geom::GeometryCollection::getCoordinates(), geos::operation::buffer::BufferSubgraph::getEnvelope(), geos::geomgraph::Edge::getEnvelope(), geos::operation::buffer::OffsetCurveBuilder::getLineCurve(), geos::geomgraph::index::SweepLineSegment::getMaxX(), geos::geomgraph::index::MonotoneChainEdge::getMaxX(), geos::geomgraph::index::SweepLineSegment::getMinX(), geos::geomgraph::index::MonotoneChainEdge::getMinX(), geos::operation::buffer::RightmostEdgeFinder::getRightmostSideOfSegment(), geos::algorithm::distance::DiscreteFrechetDistance::getSegementAt(), geos::operation::predicate::SegmentIntersectionTester::hasIntersection(), geos::operation::predicate::SegmentIntersectionTester::hasIntersectionWithEnvelopeFilter(), geos::geom::Geometry::hasNullElements(), geos::operation::valid::RepeatedPointTester::hasRepeatedPoint(), hasRepeatedPoints(), indexOf(), geos::simplify::TaggedLineString::init(), geos::algorithm::CGAlgorithms::isCCW(), geos::noding::BasicSegmentString::isClosed(), geos::noding::NodedSegmentString::isClosed(), geos::geomgraph::Edge::isClosed(), geos::geomgraph::Edge::isCollapsed(), geos::operation::polygonize::EdgeRing::isInList(), geos::operation::predicate::RectangleContains::isLineStringContainedInBoundary(), geos::algorithm::CGAlgorithms::isOnLine(), geos::geomgraph::Edge::isPointwiseEqual(), geos::operation::buffer::OffsetCurveSetBuilder::isTriangleErodedCompletely(), geos::algorithm::CGAlgorithms::length(), geos::algorithm::PointLocator::locate(), geos::operation::overlay::OverlayOp::mergeZ(), minCoordinate(), geos::geom::Polygon::normalize(), geos::geomgraph::Edge::printReverse(), geos::operation::overlay::LineBuilder::propagateZ(), geos::operation::polygonize::EdgeRing::ptNotInList(), geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), reverse(), scroll(), geos::algorithm::CGAlgorithms::signedArea(), geos::simplify::TaggedLineStringSimplifier::simplifySection(), geos::operation::intersection::Rectangle::toLinearRing(), geos::triangulate::DelaunayTriangulationBuilder::toVertices(), geos::operation::predicate::ContainsPointVisitor::visit(), and geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
virtual void geos::geom::CoordinateSequence::getAt (std::size_t i, Coordinate & c) const pure virtual
Write Coordinate at position i to given Coordinate.
Implemented in geos::geom::CoordinateArraySequence.
virtual std::size_t geos::geom::CoordinateSequence::getDimension () const pure virtual
Returns the dimension (number of ordinates in each coordinate) for this sequence.
Returns
the dimension of the sequence.
Implemented in geos::geom::CoordinateArraySequence.
Referenced by GEOSCoordSeq_getDimensions_r(), and geos::io::WKBReader::readCoordinateSequence().
virtual double geos::geom::CoordinateSequence::getOrdinate (std::size_t index, std::size_t ordinateIndex) const pure virtual
Returns the ordinate of a coordinate in this sequence. Ordinate indices 0 and 1 are assumed to be X and Y. Ordinates indices greater than 1 have user-defined semantics (for instance, they may contain other dimensions or measure values).
Parameters
index the coordinate index in the sequence
ordinateIndex the ordinate index in the coordinate (in range [0, dimension-1])
Referenced by GEOSCoordSeq_getOrdinate_r(), and geos::io::WKBWriter::writeCoordinate().
virtual std::size_t geos::geom::CoordinateSequence::getSize () const pure virtual
Returns the number of Coordinates (actual or otherwise, as this implementation may not store its data in Coordinate objects).
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::algorithm::CentroidLine::add(), geos::geomgraph::index::SimpleSweepLineIntersector::add(), geos::operation::overlay::ElevationMatrix::add(), add(), geos::operation::buffer::OffsetCurveSetBuilder::addCurve(), geos::operation::polygonize::EdgeRing::addEdge(), geos::geomgraph::GeometryGraph::addEdge(), geos::algorithm::CentroidArea::addHole(), geos::algorithm::InteriorPointLine::addInterior(), geos::geomgraph::GeometryGraph::addLineString(), geos::geomgraph::EdgeRing::addPoints(), geos::geomgraph::GeometryGraph::addPolygonRing(), geos::algorithm::CentroidArea::addShell(), atLeastNCoordinatesOrNothing(), geos::algorithm::SIRtreePointInRing::buildIndex(), geos::noding::NodingValidator::checkCollapses(), geos::operation::buffer::RightmostEdgeFinder::checkForRightmostCoordinate(), geos::operation::valid::IsValidOp::checkInvalidCoordinates(), geos::noding::SegmentNodeList::checkSplitEdgesCorrectness(), geos::algorithm::MinimumDiameter::computeConvexRingMinDiameter(), geos::geomgraph::index::SimpleEdgeSetIntersector::computeIntersects(), geos::noding::SimpleNoder::computeIntersects(), geos::operation::distance::DistanceOp::computeMinDistance(), geos::noding::snapround::SimpleSnapRounder::computeVertexSnaps(), geos::geom::GeometryFactory::createMultiPoint(), geos::precision::PrecisionReducerCoordinateOperation::edit(), equals(), geos::geomgraph::index::MonotoneChainIndexer::findChainEnd(), geos::index::chain::MonotoneChainBuilder::findChainEnd(), geos::operation::valid::ConnectedInteriorTester::findDifferentPoint(), geos::operation::valid::IsValidOp::findPtNotNode(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode(), geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments(), GEOSCoordSeq_getSize_r(), geos::operation::overlay::OverlayOp::getAverageZ(), geos::geomgraph::index::MonotoneChainIndexer::getChainStartIndices(), geos::index::chain::MonotoneChainBuilder::getChainStartIndices(), geos::geom::GeometryCollection::getCoordinates(), geos::operation::buffer::BufferSubgraph::getEnvelope(), geos::operation::buffer::OffsetCurveBuilder::getLineCurve(), geos::algorithm::MinimumDiameter::getNextIndex(), geos::geomgraph::Edge::getNumPoints(), geos::operation::buffer::RightmostEdgeFinder::getRightmostSideOfSegment(), geos::operation::buffer::OffsetCurveBuilder::getRingCurve(), geos::operation::buffer::OffsetCurveBuilder::getSingleSidedLineCurve(), geos::operation::predicate::SegmentIntersectionTester::hasIntersection(), geos::operation::predicate::SegmentIntersectionTester::hasIntersectionWithEnvelopeFilter(), geos::geom::Geometry::hasNullElements(), geos::operation::valid::RepeatedPointTester::hasRepeatedPoint(), hasRepeatedPoints(), indexOf(), geos::algorithm::CGAlgorithms::isCCW(), geos::operation::buffer::OffsetCurveSetBuilder::isErodedCompletely(), geos::operation::polygonize::EdgeRing::isInList(), geos::operation::predicate::RectangleContains::isLineStringContainedInBoundary(), geos::algorithm::CGAlgorithms::isOnLine(), geos::algorithm::CGAlgorithms::length(), geos::algorithm::PointLocator::locate(), minCoordinate(), geos::geom::Polygon::normalize(), geos::operation::overlay::LineBuilder::propagateZ(), geos::operation::polygonize::EdgeRing::ptNotInList(), reverse(), scroll(), geos::algorithm::CGAlgorithms::signedArea(), geos::io::WKTWriter::toLineString(), and geos::io::WKBWriter::writeCoordinateSequence().
virtual double geos::geom::CoordinateSequence::getX (std::size_t index) const inline virtual
Returns ordinate X (0) of the specified coordinate.
Parameters
index
Returns
the value of the X ordinate in the index'th coordinate
Definition at line 330 of file CoordinateSequence.h.
Referenced by geos::operation::distance::FacetSequence::computeEnvelope(), geos::geom::Polygon::isRectangle(), geos::io::WKTWriter::toLineString(), and geos::io::WKBWriter::writeCoordinate().
 { return getOrdinate(index, X); }
virtual double geos::geom::CoordinateSequence::getY (std::size_t index) const inline virtual
Returns ordinate Y (1) of the specified coordinate.
Parameters
index
Returns
the value of the Y ordinate in the index'th coordinate
Definition at line 338 of file CoordinateSequence.h.
Referenced by geos::operation::distance::FacetSequence::computeEnvelope(), geos::geom::Polygon::isRectangle(), geos::io::WKTWriter::toLineString(), and geos::io::WKBWriter::writeCoordinate().
 { return getOrdinate(index, Y); }
bool geos::geom::CoordinateSequence::hasRepeatedPoints () const
Returns true if contains any two consecutive points.
Definition at line 39 of file CoordinateSequence.cpp.
 {
     const std::size_t size=getSize();
   for(std::size_t i=1; i<size; i++) {
     if (getAt(i-1)==getAt(i)) {
       return true;
     }
   }
   return false;
 }
bool geos::geom::CoordinateSequence::hasRepeatedPoints (const CoordinateSequence * cl) static
Returns true if given CoordinateSequence contains any two consecutive Coordinate.
Definition at line 71 of file CoordinateSequence.cpp.
References getAt(), and getSize().
 {
   const std::size_t size=cl->getSize();
   for(std::size_t i=1;i<size; i++) {
     if (cl->getAt(i-1)==cl->getAt(i)) {
       return true;
     }
   }
   return false;
 }
int geos::geom::CoordinateSequence::increasingDirection (const CoordinateSequence & pts) static
Determines which orientation of the Coordinate array is (overall) increasing.
In other words, determines which end of the array is "smaller" (using the standard ordering on Coordinate). Returns an integer indicating the increasing direction. If the sequence is a palindrome, it is defined to be oriented in a positive direction.
Parameters
pts the array of Coordinates to test
Returns
1 if the array is smaller at the start or is a palindrome, -1 if smaller at the end
NOTE: this method is found in CoordinateArrays class for JTS
Definition at line 145 of file CoordinateSequence.cpp.
References size().
Referenced by geos::noding::OrientedCoordinateArray::orientation().
 {
   size_t ptsize = pts.size();
   for (size_t i=0, n=ptsize/2; i<n; ++i)
   {
     size_t j = ptsize - 1 - i;
     // skip equal points on both ends
     int comp = pts[i].compareTo(pts[j]);
     if (comp != 0) return comp;
   }
   // array must be a palindrome - defined to be in positive direction
   return 1;
 }
int geos::geom::CoordinateSequence::indexOf (const Coordinate * coordinate, const CoordinateSequence * cl) static
Return position of a Coordinate, or -1 if not found.
FIXME: return std::size_t, using numeric_limits<std::size_t>::max as 'not found' value.
Definition at line 109 of file CoordinateSequence.cpp.
References getAt(), and getSize().
 {
   size_t size=cl->getSize();
   for (size_t i=0; i<size; ++i)
   {
     if ((*coordinate)==cl->getAt(i))
     {
       return static_cast<int>(i); // FIXME: what if we overflow the int ?
     }
   }
   return -1;
 }
virtual bool geos::geom::CoordinateSequence::isEmpty () const pure virtual
Returns true it list contains no coordinates.
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::linearref::LinearGeometryBuilder::endLine().
const Coordinate * geos::geom::CoordinateSequence::minCoordinate () const
Returns lower-left Coordinate in list.
Definition at line 83 of file CoordinateSequence.cpp.
References geos::geom::Coordinate::compareTo().
Referenced by geos::geom::Polygon::normalize().
 {
   const Coordinate* minCoord=nullptr;
   const std::size_t size=getSize();
   for(std::size_t i=0; i<size; i++) {
     if(minCoord==nullptr || minCoord->compareTo(getAt(i))>0) {
       minCoord=&getAt(i);
     }
   }
   return minCoord;
 }
const Coordinate * geos::geom::CoordinateSequence::minCoordinate (CoordinateSequence * cl) static
Returns lower-left Coordinate in given CoordinateSequence. This is actually the Coordinate with lower X (and Y if needed) ordinate.
Definition at line 96 of file CoordinateSequence.cpp.
References geos::geom::Coordinate::compareTo(), getAt(), and getSize().
 {
   const Coordinate* minCoord=nullptr;
   const std::size_t size=cl->getSize();
   for(std::size_t i=0;i<size; i++) {
     if(minCoord==nullptr || minCoord->compareTo(cl->getAt(i))>0) {
       minCoord=&(cl->getAt(i));
     }
   }
   return minCoord;
 }
const Coordinate& geos::geom::CoordinateSequence::operator[] (std::size_t i) const inline
Definition at line 97 of file CoordinateSequence.h.
{
     return getAt(i);
   }
CoordinateSequence * geos::geom::CoordinateSequence::removeRepeatedPoints (const CoordinateSequence * cl) static
Returns a new CoordinateSequence being a copy of the input with any consecutive equal Coordinate removed.
Equality test is 2D based
Ownership of returned object goes to the caller.
Definition at line 245 of file CoordinateSequence.cpp.
References toVector().
Referenced by geos::noding::ScaledNoder::scale(), and geos::triangulate::DelaunayTriangulationBuilder::unique().
 {
 #if PROFILE
   static Profile *prof= profiler->get("CoordinateSequence::removeRepeatedPoints()");
   prof->start();
 #endif
   const vector<Coordinate> *v=cl->toVector();
   vector<Coordinate> *nv=new vector<Coordinate>;
   nv->reserve(v->size());
   unique_copy(v->begin(), v->end(), back_inserter(*nv));
   CoordinateSequence* ret=CoordinateArraySequenceFactory::instance()->create(nv);
 #if PROFILE
   prof->stop();
 #endif
   return ret;
 }
virtual CoordinateSequence& geos::geom::CoordinateSequence::removeRepeatedPoints () pure virtual
Remove consecutive equal Coordinates from the sequence.
Equality test is 2D based. Returns a reference to self.
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::operation::buffer::BufferBuilder::computeNodedEdges(), geos::precision::PrecisionReducerCoordinateOperation::edit(), and geos::operation::intersection::RectangleIntersectionBuilder::reconnect().
void geos::geom::CoordinateSequence::reverse (CoordinateSequence * cl) static
Reverse Coordinate order in given CoordinateSequence.
Definition at line 160 of file CoordinateSequence.cpp.
References getAt(), getSize(), and setAt().
Referenced by geos::geom::LineString::normalize(), geos::geom::Polygon::normalize(), geos::geom::LinearRing::reverse(), and geos::geom::LineString::reverse().
 {
   // FIXME: use a standard algorithm
   int last = static_cast<int>(cl->getSize()) - 1;
   int mid=last/2;
   for(int i=0;i<=mid;i++) {
     const Coordinate tmp=cl->getAt(i);
     cl->setAt(cl->getAt(last-i),i);
     cl->setAt(tmp,last-i);
   }
 }
void geos::geom::CoordinateSequence::scroll (CoordinateSequence * cl, const Coordinate * firstCoordinate) static
Scroll given CoordinateSequence so to start with given Coordinate.
Definition at line 124 of file CoordinateSequence.cpp.
References getAt(), getSize(), and setPoints().
Referenced by geos::geom::Polygon::normalize().
 {
   // FIXME: use a standard algorithm instead
   std::size_t i, j=0;
   std::size_t ind=indexOf(firstCoordinate,cl);
   if (ind<1)
         return; // not found or already first
   const std::size_t length=cl->getSize();
   vector<Coordinate> v(length);
   for (i=ind; i<length; i++) {
     v[j++]=cl->getAt(i);
   }
   for (i=0; i<ind; i++) {
     v[j++]=cl->getAt(i);
   }
   cl->setPoints(v);
 }
virtual void geos::geom::CoordinateSequence::setAt (const Coordinate & c, std::size_t pos) pure virtual
Get a reference to Coordinate at position pos.
Copy Coordinate c to position pos
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::geom::LineSegment::closestPoints(), geos::noding::SegmentNodeList::createSplitEdge(), geos::geomgraph::Edge::getCollapsedEdge(), geos::algorithm::MinimumDiameter::getMinimumRectangle(), geos::operation::overlay::LineBuilder::propagateZ(), reverse(), geos::operation::intersection::Rectangle::toLinearRing(), and geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor::visit().
virtual void geos::geom::CoordinateSequence::setOrdinate (std::size_t index, std::size_t ordinateIndex, double value) pure virtual
Sets the value for a given ordinate of a coordinate in this sequence.
Parameters
index the coordinate index in the sequence
ordinateIndex the ordinate index in the coordinate (in range [0, dimension-1])
value the new ordinate value
Implemented in geos::geom::CoordinateArraySequence.
Referenced by GEOSCoordSeq_setOrdinate_r(), and geos::io::WKBReader::readCoordinateSequence().
virtual void geos::geom::CoordinateSequence::setPoints (const std::vector< Coordinate > & v) pure virtual
Substitute Coordinate list with a copy of the given vector.
Implemented in geos::geom::CoordinateArraySequence.
Referenced by scroll(), and geos::triangulate::DelaunayTriangulationBuilder::unique().
size_t geos::geom::CoordinateSequence::size () const inline
Definition at line 113 of file CoordinateSequence.h.
Referenced by geos::geom::CoordinateArraySequence::add(), geos::algorithm::InteriorPointLine::addEndpoints(), geos::operation::distance::FacetSequenceTreeBuilder::addFacetSequences(), geos::algorithm::Centroid::addHole(), geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::addLine(), geos::algorithm::CentroidArea::addLinearSegments(), geos::algorithm::Centroid::addLineSegments(), geos::geomgraph::GeometryGraph::addLineString(), geos::operation::buffer::OffsetCurveSetBuilder::addPolygonRing(), geos::operation::buffer::OffsetSegmentString::addPts(), geos::algorithm::Centroid::addShell(), geos::noding::NodingValidator::checkEndPtVertexIntersections(), geos::noding::NodingValidator::checkInteriorIntersections(), geos::operation::buffer::OffsetSegmentString::closeRing(), geos::operation::buffer::BufferInputLineSimplifier::collapseLine(), geos::noding::OrientedCoordinateArray::compareOriented(), geos::algorithm::distance::DiscreteFrechetDistance::compute(), geos::algorithm::distance::DistanceToPoint::computeDistance(), geos::linearref::ExtractLineByLocation::computeLine(), geos::operation::buffer::OffsetCurveBuilder::computeLineBufferCurve(), geos::operation::buffer::BufferBuilder::computeNodedEdges(), geos::operation::buffer::OffsetCurveBuilder::computeRingBufferCurve(), geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve(), geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps(), geos::operation::buffer::BufferInputLineSimplifier::deleteShallowConcavities(), geos::linearref::LinearGeometryBuilder::endLine(), geos::operation::overlay::validate::OffsetPointGenerator::extractPoints(), geos::geomgraph::PlanarGraph::findEdgeInSameDirection(), geos::operation::buffer::BufferInputLineSimplifier::findNextNonDeletedIndex(), geos::algorithm::distance::DiscreteFrechetDistance::getSegementAt(), geos::operation::buffer::OffsetCurveBuilder::getSingleSidedLineCurve(), increasingDirection(), geos::simplify::TaggedLineString::init(), geos::operation::buffer::OffsetSegmentString::isRedundant(), geos::algorithm::RayCrossingCounter::locatePointInRing(), geos::operation::overlay::OverlayOp::mergeZ(), geos::geom::operator<<(), geos::operation::intersection::RectangleIntersectionBuilder::reconnect(), geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), geos::noding::ScaledNoder::scale(), geos::simplify::TaggedLineStringSimplifier::simplify(), geos::operation::buffer::BufferInputLineSimplifier::simplify(), geos::operation::buffer::OffsetSegmentString::size(), and geos::triangulate::DelaunayTriangulationBuilder::toVertices().
 { return getSize(); }
virtual std::string geos::geom::CoordinateSequence::toString () const pure virtual
Get a string rapresentation of CoordinateSequence.
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::operation::buffer::OffsetCurveSetBuilder::addCurve().
virtual const std::vector<Coordinate>* geos::geom::CoordinateSequence::toVector () const pure virtual
Returns a read-only vector with the Coordinates in this collection.
Whether or not the Coordinates returned are the actual underlying Coordinates or merely copies depends on the implementation. Note that if this implementation does not store its data as an array of Coordinates, this method will incur a performance penalty because the array needs to be built from scratch.
This method is a port of the toCoordinateArray() method of JTS. It is not much used as memory management requires us to know wheter we should or not delete the returned object in a consistent way. Our options are: use shared_ptr<Coordinate> or always keep ownerhips of an eventual newly created vector. We opted for the second, so the returned object is a const, to also ensure that returning an internal pointer doesn't make the object mutable.
Deprecated:
use toVector(std::vector<Coordinate>&) instead
Implemented in geos::geom::CoordinateArraySequence.
Referenced by geos::operation::intersection::RectangleIntersection::clip_linestring_parts(), geos::triangulate::DelaunayTriangulationBuilder::envelope(), geos::geom::Polygon::getCoordinates(), geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), removeRepeatedPoints(), geos::geom::LinearRing::setPoints(), geos::operation::overlay::snap::SnapTransformer::snapLine(), geos::simplify::DPTransformer::transformCoordinates(), and geos::triangulate::DelaunayTriangulationBuilder::unique().
virtual void geos::geom::CoordinateSequence::toVector (std::vector< Coordinate > & coords) const pure virtual
Pushes all Coordinates of this sequence onto the provided vector.
This method is a port of the toCoordinateArray() method of JTS.
Implemented in geos::geom::CoordinateArraySequence.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/CoordinateSequence.h
/home/vicky/potree/geos/vicky/src/geom/CoordinateSequence.cpp