GEOS: geos::operation::buffer::OffsetCurveSetBuilder Class Reference
geos::operation::buffer::OffsetCurveSetBuilder Class Reference
Creates all the raw offset curves for a buffer of a Geometry.
#include <geos/opBuffer.h>
Public Member Functions
OffsetCurveSetBuilder (const geom::Geometry &newInputGeom, double newDistance, OffsetCurveBuilder &newCurveBuilder)
Constructor.
~OffsetCurveSetBuilder ()
Destructor.
std::vector< noding::SegmentString * > & getCurves ()
Computes the set of raw offset curves for the buffer.
void addCurves (const std::vector< geom::CoordinateSequence * > &lineList, int leftLoc, int rightLoc)
Add raw curves for a set of CoordinateSequences.
Private Member Functions
void addCurve (geom::CoordinateSequence *coord, int leftLoc, int rightLoc)
void add (const geom::Geometry &g)
void addCollection (const geom::GeometryCollection *gc)
void addPoint (const geom::Point *p)
void addLineString (const geom::LineString *line)
void addPolygon (const geom::Polygon *p)
void addPolygonRing (const geom::CoordinateSequence *coord, double offsetDistance, int side, int cwLeftLoc, int cwRightLoc)
bool isErodedCompletely (const geom::LinearRing *ringCoord, double bufferDistance)
bool isTriangleErodedCompletely (const geom::CoordinateSequence *triCoords, double bufferDistance)
OffsetCurveSetBuilder (const OffsetCurveSetBuilder &other)=delete
OffsetCurveSetBuilder & operator= (const OffsetCurveSetBuilder &rhs)=delete
Private Attributes
std::vector< geomgraph::Label * > newLabels
const geom::Geometry & inputGeom
double distance
OffsetCurveBuilder & curveBuilder
std::vector< noding::SegmentString * > curveList
Detailed Description
Creates all the raw offset curves for a buffer of a Geometry.
Raw curves need to be noded together and polygonized to form the final buffer area.
Definition at line 70 of file OffsetCurveSetBuilder.h.
Constructor & Destructor Documentation
geos::operation::buffer::OffsetCurveSetBuilder::OffsetCurveSetBuilder (const OffsetCurveSetBuilder & other) private delete
geos::operation::buffer::OffsetCurveSetBuilder::OffsetCurveSetBuilder (const geom::Geometry & newInputGeom, double newDistance, OffsetCurveBuilder & newCurveBuilder)
Constructor.
Definition at line 62 of file OffsetCurveSetBuilder.cpp.
                                                             :
   inputGeom(newInputGeom),
   distance(newDistance),
   curveBuilder(newCurveBuilder),
   curveList()
 {
 }
geos::operation::buffer::OffsetCurveSetBuilder::~OffsetCurveSetBuilder ()
Destructor.
Definition at line 71 of file OffsetCurveSetBuilder.cpp.
References curveList, and newLabels.
 {
   for (size_t i=0, n=curveList.size(); i<n; ++i)
   {
     SegmentString* ss = curveList[i];
     delete ss;
   }
   for (size_t i=0, n=newLabels.size(); i<n; ++i)
     delete newLabels[i];
 }
Member Function Documentation
void geos::operation::buffer::OffsetCurveSetBuilder::add (const geom::Geometry & g) private
Definition at line 134 of file OffsetCurveSetBuilder.cpp.
References addCollection(), addLineString(), addPoint(), addPolygon(), geos::geom::Geometry::isEmpty(), and poly.
Referenced by addCollection(), and getCurves().
 {
   if (g.isEmpty()) {
 #if GEOS_DEBUG
     std::cerr<<__FUNCTION__<<": skip empty geometry"<<std::endl;
 #endif
     return;
   }
   const Polygon *poly = dynamic_cast<const Polygon *>(&g);
   if ( poly ) {
     addPolygon(poly);
     return;
   }
   const LineString *line = dynamic_cast<const LineString *>(&g);
   if ( line ) {
     addLineString(line);
     return;
   }
   const Point *point = dynamic_cast<const Point *>(&g);
   if ( point ) {
     addPoint(point);
     return;
   }
   const GeometryCollection *collection = dynamic_cast<const GeometryCollection *>(&g);
   if ( collection ) {
     addCollection(collection);
     return;
   }
   std::string out=typeid(g).name();
   throw util::UnsupportedOperationException("GeometryGraph::add(Geometry &): unknown geometry type: "+out);
 }
void geos::operation::buffer::OffsetCurveSetBuilder::addCollection (const geom::GeometryCollection * gc) private
Definition at line 173 of file OffsetCurveSetBuilder.cpp.
References add(), geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
Referenced by add().
 {
   for (int i=0, n=static_cast<int>(gc->getNumGeometries()); i<n; i++) {
     const Geometry *g=gc->getGeometryN(i);
     add(*g);
   }
 }
void geos::operation::buffer::OffsetCurveSetBuilder::addCurve (geom::CoordinateSequence * coord, int leftLoc, int rightLoc) private
Creates a noding::SegmentString for a coordinate list which is a raw offset curve, and adds it to the list of buffer curves. The noding::SegmentString is tagged with a geomgraph::Label giving the topology of the curve. The curve may be oriented in either direction. If the curve is oriented CW, the locations will be:
Left: Location.EXTERIOR
Right: Location.INTERIOR
Parameters
coord is raw offset curve, ownership transferred here
Definition at line 104 of file OffsetCurveSetBuilder.cpp.
References curveList, geos::geom::CoordinateSequence::getSize(), newLabels, and geos::geom::CoordinateSequence::toString().
Referenced by addCurves().
 {
 #if GEOS_DEBUG
   std::cerr<<__FUNCTION__<<": coords="<<coord->toString()<<std::endl;
 #endif
   // don't add null curves!
   if (coord->getSize() < 2) {
 #if GEOS_DEBUG
     std::cerr<<" skipped (size<2)"<<std::endl;
 #endif
     delete coord;
     return;
   }
   // add the edge for a coordinate list which is a raw offset curve
   Label *newlabel = new Label(0, Location::BOUNDARY, leftLoc, rightLoc);
   // coord ownership transferred to SegmentString
   SegmentString *e=new NodedSegmentString(coord, newlabel);
   // SegmentString doesnt own the sequence, so we need to delete in
   // the destructor
   newLabels.push_back(newlabel);
   curveList.push_back(e);
 }
void geos::operation::buffer::OffsetCurveSetBuilder::addCurves (const std::vector< geom::CoordinateSequence * > & lineList, int leftLoc, int rightLoc)
Add raw curves for a set of CoordinateSequences.
Parameters
lineList is a list of CoordinateSequence, ownership of which is transferred here.
Definition at line 92 of file OffsetCurveSetBuilder.cpp.
References addCurve().
Referenced by addLineString(), addPoint(), and addPolygonRing().
 {
   for (size_t i=0, n=lineList.size(); i<n; ++i)
   {
     CoordinateSequence *coords = lineList[i];
     addCurve(coords, leftLoc, rightLoc);
   }
 }
void geos::operation::buffer::OffsetCurveSetBuilder::addLineString (const geom::LineString * line) private
Definition at line 196 of file OffsetCurveSetBuilder.cpp.
References addCurves(), curveBuilder, distance, geos::operation::buffer::OffsetCurveBuilder::getBufferParameters(), geos::geom::LineString::getCoordinatesRO(), geos::operation::buffer::OffsetCurveBuilder::getLineCurve(), geos::operation::buffer::BufferParameters::isSingleSided(), and geos::geom::Geometry::toString().
Referenced by add().
 {
   if (distance <= 0.0 && ! curveBuilder.getBufferParameters().isSingleSided())
   {
     return;
   }
 #if GEOS_DEBUG
   std::cerr<<__FUNCTION__<<": "<<line->toString()<<std::endl;
 #endif
   std::unique_ptr<CoordinateSequence> coord(CoordinateSequence::removeRepeatedPoints(line->getCoordinatesRO()));
 #if GEOS_DEBUG
   std::cerr<<" After coordinate removal: "<<coord->toString()<<std::endl;
 #endif
   std::vector<CoordinateSequence*> lineList;
   curveBuilder.getLineCurve(coord.get(), distance, lineList);
   addCurves(lineList, Location::EXTERIOR, Location::INTERIOR);
 }
void geos::operation::buffer::OffsetCurveSetBuilder::addPoint (const geom::Point * p) private
Add a Point to the graph.
Definition at line 183 of file OffsetCurveSetBuilder.cpp.
References addCurves(), curveBuilder, distance, geos::geom::Point::getCoordinatesRO(), and geos::operation::buffer::OffsetCurveBuilder::getLineCurve().
Referenced by add().
 {
   if (distance <= 0.0) return;
   const CoordinateSequence *coord=p->getCoordinatesRO();
   std::vector<CoordinateSequence*> lineList;
   curveBuilder.getLineCurve(coord, distance, lineList);
   addCurves(lineList, Location::EXTERIOR, Location::INTERIOR);
   //delete lineList;
 }
void geos::operation::buffer::OffsetCurveSetBuilder::addPolygon (const geom::Polygon * p) private
Definition at line 217 of file OffsetCurveSetBuilder.cpp.
References addPolygonRing(), distance, geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), and isErodedCompletely().
Referenced by add().
 {
   double offsetDistance=distance;
   int offsetSide=Position::LEFT;
   if (distance < 0.0)
   {
     offsetDistance = -distance;
     offsetSide = Position::RIGHT;
   }
   // FIXME: avoid the C-style cast
   const LinearRing *shell=(const LinearRing *)p->getExteriorRing();
   // optimization - don't bother computing buffer
   // if the polygon would be completely eroded
   if (distance < 0.0 && isErodedCompletely(shell, distance))
   {
 #if GEOS_DEBUG
     std::cerr<<__FUNCTION__<<": polygon is eroded completely "<<std::endl;
 #endif
     return;
   }
   // don't attempt to buffer a polygon
   // with too few distinct vertices
   CoordinateSequence *shellCoord =
     CoordinateSequence::removeRepeatedPoints(shell->getCoordinatesRO());
   if (distance <= 0.0 && shellCoord->size() < 3)
   {
     delete shellCoord;
     return;
   }
   addPolygonRing(
     shellCoord,
     offsetDistance,
     offsetSide,
     Location::EXTERIOR,
     Location::INTERIOR);
   delete shellCoord;
   for (size_t i=0, n=p->getNumInteriorRing(); i<n; ++i)
   {
     const LineString *hls=p->getInteriorRingN(i);
     assert(dynamic_cast<const LinearRing *>(hls));
     const LinearRing *hole=static_cast<const LinearRing *>(hls);
     // optimization - don't bother computing buffer for this hole
     // if the hole would be completely covered
     if (distance > 0.0 && isErodedCompletely(hole, -distance))
     {
       continue;
     }
     CoordinateSequence *holeCoord =
       CoordinateSequence::removeRepeatedPoints(hole->getCoordinatesRO());
     // Holes are topologically labelled opposite to the shell,
     // since the interior of the polygon lies on their opposite
     // side (on the left, if the hole is oriented CCW)
     addPolygonRing(
       holeCoord,
       offsetDistance,
       Position::opposite(offsetSide),
       Location::INTERIOR,
       Location::EXTERIOR);
     delete holeCoord;
   }
 }
void geos::operation::buffer::OffsetCurveSetBuilder::addPolygonRing (const geom::CoordinateSequence * coord, double offsetDistance, int side, int cwLeftLoc, int cwRightLoc) private
Add an offset curve for a polygon ring. The side and left and right topological location arguments assume that the ring is oriented CW. If the ring is in the opposite orientation, the left and right locations must be interchanged and the side flipped.
Parameters
coord the coordinates of the ring (must not contain repeated points)
offsetDistance the distance at which to create the buffer
side the side of the ring on which to construct the buffer line
cwLeftLoc the location on the L side of the ring (if it is CW)
cwRightLoc the location on the R side of the ring (if it is CW)
Definition at line 292 of file OffsetCurveSetBuilder.cpp.
References addCurves(), curveBuilder, geos::operation::buffer::OffsetCurveBuilder::getRingCurve(), and geos::geom::CoordinateSequence::size().
Referenced by addPolygon().
 {
   // don't bother adding ring if it is "flat" and
   // will disappear in the output
   if (offsetDistance == 0.0 && coord->size() < LinearRing::MINIMUM_VALID_SIZE)
     return;
   int leftLoc=cwLeftLoc;
   int rightLoc=cwRightLoc;
 #if GEOS_DEBUG
   std::cerr<<"OffsetCurveSetBuilder::addPolygonRing: CCW: "<<CGAlgorithms::isCCW(coord)<<std::endl;
 #endif
   if (coord->size() >= LinearRing::MINIMUM_VALID_SIZE
       && CGAlgorithms::isCCW(coord))
   {
     leftLoc=cwRightLoc;
     rightLoc=cwLeftLoc;
 #if GEOS_DEBUG
   std::cerr<<" side "<<side<<" becomes "<<Position::opposite(side)<<std::endl;
 #endif
     side=Position::opposite(side);
   }
   std::vector<CoordinateSequence*> lineList;
   curveBuilder.getRingCurve(coord, side, offsetDistance, lineList);
   addCurves(lineList, leftLoc, rightLoc);
 }
std::vector< SegmentString * > & geos::operation::buffer::OffsetCurveSetBuilder::getCurves ()
Computes the set of raw offset curves for the buffer.
Each offset curve has an attached geomgraph::Label indicating its left and right location.
Returns
a Collection of SegmentStrings representing the raw buffer curves
Definition at line 84 of file OffsetCurveSetBuilder.cpp.
References add(), curveList, and inputGeom.
Referenced by geos::operation::buffer::BufferBuilder::buffer().
 {
   add(inputGeom);
   return curveList;
 }
bool geos::operation::buffer::OffsetCurveSetBuilder::isErodedCompletely (const geom::LinearRing * ringCoord, double bufferDistance) private
The ringCoord is assumed to contain no repeated points. It may be degenerate (i.e. contain only 1, 2, or 3 points). In this case it has no area, and hence has a minimum diameter of 0.
Parameters
ring
offsetDistance
Returns
The following is a heuristic test to determine whether an inside buffer will be eroded completely-> It is based on the fact that the minimum diameter of the ring pointset provides an upper bound on the buffer distance which would erode the ring-> If the buffer distance is less than the minimum diameter, the ring may still be eroded, but this will be determined by a full topological computation->
Definition at line 323 of file OffsetCurveSetBuilder.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::getHeight(), geos::algorithm::MinimumDiameter::getLength(), geos::geom::CoordinateSequence::getSize(), geos::geom::Envelope::getWidth(), and isTriangleErodedCompletely().
Referenced by addPolygon().
 {
   const CoordinateSequence *ringCoord = ring->getCoordinatesRO();
   // degenerate ring has no area
   if (ringCoord->getSize() < 4)
     return bufferDistance < 0;
   // important test to eliminate inverted triangle bug
   // also optimizes erosion test for triangles
   if (ringCoord->getSize() == 4)
     return isTriangleErodedCompletely(ringCoord, bufferDistance);
   const Envelope* env = ring->getEnvelopeInternal();
   double envMinDimension = std::min(env->getHeight(), env->getWidth());
   if (bufferDistance < 0.0 && 2 * std::abs(bufferDistance) > envMinDimension)
       return true;
 /* MD  7 Feb 2005 - there's an unknown bug in the MD code,
  so disable this for now */
 #if 0
   MinimumDiameter md(ring); //=new MinimumDiameter(ring);
   double minDiam = md.getLength();
   return minDiam < (2 * std::fabs(bufferDistance));
 #endif
   return false;
 }
bool geos::operation::buffer::OffsetCurveSetBuilder::isTriangleErodedCompletely (const geom::CoordinateSequence * triCoords, double bufferDistance) private
Tests whether a triangular ring would be eroded completely by the given buffer distance. This is a precise test. It uses the fact that the inner buffer of a triangle converges on the inCentre of the triangle (the point equidistant from all sides). If the buffer distance is greater than the distance of the inCentre from a side, the triangle will be eroded completely.
This test is important, since it removes a problematic case where the buffer distance is slightly larger than the inCentre distance. In this case the triangle buffer curve "inverts" with incorrect topology, producing an incorrect hole in the buffer.
Parameters
triCoord
bufferDistance
Returns
Definition at line 368 of file OffsetCurveSetBuilder.cpp.
References geos::geom::CoordinateSequence::getAt().
Referenced by isErodedCompletely().
 {
   Triangle tri(triangleCoord->getAt(0), triangleCoord->getAt(1), triangleCoord->getAt(2));
   Coordinate inCentre;
   tri.inCentre(inCentre);
   double distToCentre=CGAlgorithms::distancePointLine(inCentre, tri.p0, tri.p1);
   bool ret = distToCentre < std::fabs(bufferDistance);
   return ret;
 }
OffsetCurveSetBuilder& geos::operation::buffer::OffsetCurveSetBuilder::operator= (const OffsetCurveSetBuilder & rhs) private delete
Member Data Documentation
OffsetCurveBuilder& geos::operation::buffer::OffsetCurveSetBuilder::curveBuilder private
Definition at line 82 of file OffsetCurveSetBuilder.h.
Referenced by addLineString(), addPoint(), and addPolygonRing().
std::vector<noding::SegmentString*> geos::operation::buffer::OffsetCurveSetBuilder::curveList private
The raw offset curves computed. This class holds ownership of std::vector elements.
Definition at line 87 of file OffsetCurveSetBuilder.h.
Referenced by addCurve(), getCurves(), and ~OffsetCurveSetBuilder().
double geos::operation::buffer::OffsetCurveSetBuilder::distance private
Definition at line 80 of file OffsetCurveSetBuilder.h.
Referenced by addLineString(), addPoint(), and addPolygon().
const geom::Geometry& geos::operation::buffer::OffsetCurveSetBuilder::inputGeom private
Definition at line 78 of file OffsetCurveSetBuilder.h.
Referenced by getCurves().
std::vector<geomgraph::Label*> geos::operation::buffer::OffsetCurveSetBuilder::newLabels private
Definition at line 76 of file OffsetCurveSetBuilder.h.
Referenced by addCurve(), and ~OffsetCurveSetBuilder().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/OffsetCurveSetBuilder.h
/home/vicky/potree/geos/vicky/src/operation/buffer/OffsetCurveSetBuilder.cpp