GEOS: geos::index::bintree::Interval Class Reference
geos::index::bintree::Interval Class Reference
Represents an (1-dimensional) closed interval on the Real number line.
#include <Interval.h>
Public Member Functions
Interval ()
~Interval ()
Interval (double nmin, double nmax)
Interval (const Interval *interval)
TODO: drop this, rely on copy ctor.
void init (double nmin, double nmax)
double getMin () const
double getMax () const
double getWidth () const
void expandToInclude (Interval *interval)
bool overlaps (const Interval *interval) const
bool overlaps (double nmin, double nmax) const
bool contains (const Interval *interval) const
bool contains (double nmin, double nmax) const
bool contains (double p) const
Public Attributes
double min
double max
Detailed Description
Represents an (1-dimensional) closed interval on the Real number line.
Definition at line 25 of file Interval.h.
Constructor & Destructor Documentation
geos::index::bintree::Interval::Interval ()
Definition at line 22 of file Interval.cpp.
References max, and min.
 {
   min=0.0;
   max=0.0;
 }
geos::index::bintree::Interval::~Interval ()
Definition at line 33 of file Interval.cpp.
 {
 }
geos::index::bintree::Interval::Interval (double nmin, double nmax)
Definition at line 28 of file Interval.cpp.
References init().
 {
   init(nmin, nmax);
 }
geos::index::bintree::Interval::Interval (const Interval * interval)
TODO: drop this, rely on copy ctor.
Definition at line 37 of file Interval.cpp.
References init(), max, and min.
 {
   init(interval->min, interval->max);
 }
Member Function Documentation
bool geos::index::bintree::Interval::contains (const Interval * interval) const
Definition at line 92 of file Interval.cpp.
References max, and min.
Referenced by geos::index::bintree::Key::computeKey(), geos::index::bintree::Node::insert(), geos::index::bintree::Root::insert(), and geos::index::bintree::Root::insertContained().
 {
   return contains(interval->min,interval->max);
 }
bool geos::index::bintree::Interval::contains (double nmin, double nmax) const
Definition at line 98 of file Interval.cpp.
References max, and min.
 {
   return (nmin>=min && nmax<=max);
 }
bool geos::index::bintree::Interval::contains (double p) const
Definition at line 104 of file Interval.cpp.
References max, and min.
 {
   return (p>=min && p<=max);
 }
void geos::index::bintree::Interval::expandToInclude (Interval * interval)
Definition at line 72 of file Interval.cpp.
References max, and min.
Referenced by geos::index::bintree::Node::createExpanded().
 {
   if (interval->max>max) max=interval->max;
   if (interval->min<min) min=interval->min;
 }
double geos::index::bintree::Interval::getMax () const
Definition at line 60 of file Interval.cpp.
References max.
Referenced by geos::index::bintree::Node::createSubnode(), geos::index::bintree::Bintree::ensureExtent(), geos::index::bintree::Root::insertContained(), and geos::index::bintree::Node::Node().
 {
   return max;
 }
double geos::index::bintree::Interval::getMin () const
Definition at line 54 of file Interval.cpp.
References min.
Referenced by geos::index::bintree::Key::computeInterval(), geos::index::bintree::Node::createSubnode(), geos::index::bintree::Bintree::ensureExtent(), geos::index::bintree::Root::insertContained(), and geos::index::bintree::Node::Node().
 {
   return min;
 }
double geos::index::bintree::Interval::getWidth (void) const
Definition at line 66 of file Interval.cpp.
References max, and min.
Referenced by geos::index::bintree::Bintree::collectStats(), and geos::index::bintree::Key::computeLevel().
 {
   return max-min;
 }
void geos::index::bintree::Interval::init (double nmin, double nmax)
Definition at line 43 of file Interval.cpp.
References max, and min.
Referenced by geos::index::bintree::Key::computeInterval(), and Interval().
 {
   min=nmin;
   max=nmax;
   if (min>max) {
     min=nmax;
     max=nmin;
   }
 }
bool geos::index::bintree::Interval::overlaps (const Interval * interval) const
Definition at line 79 of file Interval.cpp.
References max, and min.
Referenced by geos::index::bintree::Node::isSearchMatch().
 {
   return overlaps(interval->min,interval->max);
 }
bool geos::index::bintree::Interval::overlaps (double nmin, double nmax) const
Definition at line 85 of file Interval.cpp.
References max, and min.
 {
   if (min>nmax || max<nmin) return false;
   return true;
 }
Member Data Documentation
double geos::index::bintree::Interval::max
Definition at line 29 of file Interval.h.
Referenced by geos::algorithm::MCPointInRing::buildIndex(), contains(), expandToInclude(), getMax(), geos::index::bintree::NodeBase::getSubnodeIndex(), getWidth(), init(), Interval(), geos::algorithm::MCPointInRing::isInside(), and overlaps().
double geos::index::bintree::Interval::min
Definition at line 29 of file Interval.h.
Referenced by geos::algorithm::MCPointInRing::buildIndex(), contains(), expandToInclude(), getMin(), geos::index::bintree::NodeBase::getSubnodeIndex(), getWidth(), init(), Interval(), geos::algorithm::MCPointInRing::isInside(), and overlaps().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/bintree/Interval.h
/home/vicky/potree/geos/vicky/src/index/bintree/Interval.cpp