GEOS: geos::operation::overlay::ElevationMatrixCell Class Reference
geos::operation::overlay::ElevationMatrixCell Class Reference
#include <ElevationMatrixCell.h>
Public Member Functions
ElevationMatrixCell ()
~ElevationMatrixCell ()
void add (const geom::Coordinate &c)
void add (double z)
double getAvg (void) const
double getTotal (void) const
std::string print () const
Private Attributes
std::set< double > zvals
double ztot
Detailed Description
Definition at line 43 of file ElevationMatrixCell.h.
Constructor & Destructor Documentation
geos::operation::overlay::ElevationMatrixCell::ElevationMatrixCell ()
Definition at line 35 of file ElevationMatrixCell.cpp.
                                         : ztot(0)
 {
 }
geos::operation::overlay::ElevationMatrixCell::~ElevationMatrixCell ()
Definition at line 39 of file ElevationMatrixCell.cpp.
 {
 }
Member Function Documentation
void geos::operation::overlay::ElevationMatrixCell::add (const geom::Coordinate & c)
Definition at line 44 of file ElevationMatrixCell.cpp.
References geos::geom::Coordinate::z, ztot, and zvals.
Referenced by geos::operation::overlay::ElevationMatrix::add().
 {
   if ( !ISNAN(c.z) )
   {
     if ( zvals.insert(c.z).second )
     {
       ztot+=c.z;
     }
   }
 }
void geos::operation::overlay::ElevationMatrixCell::add (double z)
Definition at line 56 of file ElevationMatrixCell.cpp.
References ztot, and zvals.
 {
   if ( !ISNAN(z) )
   {
     if ( zvals.insert(z).second )
     {
       ztot+=z;
     }
   }
 }
double geos::operation::overlay::ElevationMatrixCell::getAvg (void) const
Definition at line 74 of file ElevationMatrixCell.cpp.
References ztot, and zvals.
Referenced by geos::operation::overlay::ElevationMatrixFilter::filter_rw(), geos::operation::overlay::ElevationMatrix::getAvgElevation(), and print().
 {
   return  zvals.size() ?
     ztot / static_cast<double>(zvals.size()) :
     DoubleNotANumber;
 }
double geos::operation::overlay::ElevationMatrixCell::getTotal (void) const
Definition at line 68 of file ElevationMatrixCell.cpp.
References ztot.
 {
   return ztot;
 }
string geos::operation::overlay::ElevationMatrixCell::print () const
Definition at line 82 of file ElevationMatrixCell.cpp.
References getAvg().
 {
   ostringstream ret;
   //ret<<"["<<ztot<<"/"<<zvals.size()<<"]";
   ret << "[" << getAvg() << "]";
   return ret.str();
 }
Member Data Documentation
double geos::operation::overlay::ElevationMatrixCell::ztot private
Definition at line 54 of file ElevationMatrixCell.h.
Referenced by add(), getAvg(), and getTotal().
std::set<double> geos::operation::overlay::ElevationMatrixCell::zvals private
Definition at line 53 of file ElevationMatrixCell.h.
Referenced by add(), and getAvg().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/ElevationMatrixCell.h
/home/vicky/potree/geos/vicky/src/operation/overlay/ElevationMatrixCell.cpp