GEOS: geos::noding::IteratedNoder Class Reference
geos::noding::IteratedNoder Class Reference
Nodes a set of SegmentStrings completely.
#include <IteratedNoder.h>
Public Member Functions
IteratedNoder (const geom::PrecisionModel *newPm)
~IteratedNoder () override
void setMaximumIterations (int n)
std::vector< SegmentString * > * getNodedSubstrings () const override
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
void computeNodes (std::vector< SegmentString * > *inputSegmentStrings) override
Private Member Functions
void node (std::vector< SegmentString * > *segStrings, int *numInteriorIntersections)
Private Attributes
const geom::PrecisionModel * pm
algorithm::LineIntersector li
std::vector< SegmentString * > * nodedSegStrings
int maxIter
Static Private Attributes
static const int MAX_ITER = 5
Detailed Description
Nodes a set of SegmentStrings completely.
The set of segmentStrings is fully noded; i.e. noding is repeated until no further intersections are detected.
Iterated noding using a FLOATING precision model is not guaranteed to converge, due to roundoff error. This problem is detected and an exception is thrown. Clients can choose to rerun the noding using a lower precision model.
Definition at line 55 of file IteratedNoder.h.
Constructor & Destructor Documentation
geos::noding::IteratedNoder::IteratedNoder (const geom::PrecisionModel * newPm) inline
Definition at line 75 of file IteratedNoder.h.
     :
     pm(newPm),
     li(pm),
     maxIter(MAX_ITER)
   {
   }
geos::noding::IteratedNoder::~IteratedNoder () inline override
Definition at line 83 of file IteratedNoder.h.
 {}
Member Function Documentation
void geos::noding::IteratedNoder::computeNodes (std::vector< SegmentString * > * inputSegmentStrings) override virtual
Fully nodes a list of SegmentStrings, i.e. peforms noding iteratively until no intersections are found between segments. Maintains labelling of edges correctly through the noding.
Parameters
segStrings a collection of SegmentStrings to be noded
Exceptions
TopologyException if the iterated noding fails to converge.
Fail if the number of nodes created is not declining. However, allow a few iterations at least before doing this
Implements geos::noding::Noder.
Definition at line 56 of file IteratedNoder.cpp.
 {
   int numInteriorIntersections;
   nodedSegStrings = segStrings;
   int nodingIterationCount = 0;
   int lastNodesCreated = -1;
   vector<SegmentString*> *lastStrings = nullptr;
   do {
     // NOTE: will change this.nodedSegStrings
     node(nodedSegStrings, &numInteriorIntersections);
     // Delete noded strings from previous iteration
     if ( lastStrings ) {
       for (auto &s : *lastStrings)
         delete s;
       delete lastStrings;
     }
     lastStrings = nodedSegStrings;
     nodingIterationCount++;
     int nodesCreated = numInteriorIntersections;
     //cerr<<"# nodes created: "<<nodesCreated<<endl;
     if (lastNodesCreated > 0
         && nodesCreated >= lastNodesCreated
         && nodingIterationCount > maxIter)
     {
       stringstream s;
       s<<"Iterated noding failed to converge after "<<
                                     nodingIterationCount << " iterations";
       throw util::TopologyException(s.str());
     }
     lastNodesCreated = nodesCreated;
   } while (lastNodesCreated > 0);
   //cerr<<"# nodings = "<<nodingIterationCount<<endl;
 }
std::vector<SegmentString*>* geos::noding::IteratedNoder::getNodedSubstrings () const inline override virtual
Returns a Collection of fully noded SegmentStrings. The SegmentStrings have the same context as their parent.
Returns
a newly allocated std::vector of const SegmentStrings. Caller is responsible to delete container and elements.
Implements geos::noding::Noder.
Definition at line 96 of file IteratedNoder.h.
{
     return nodedSegStrings;
   }
void geos::noding::IteratedNoder::node (std::vector< SegmentString * > * segStrings, int * numInteriorIntersections) private
Node the input segment strings once and create the split edges between the nodes
Definition at line 42 of file IteratedNoder.cpp.
References geos::noding::MCIndexNoder::computeNodes(), geos::noding::MCIndexNoder::getNodedSubstrings(), geos::noding::IntersectionAdder::numInteriorIntersections, and geos::noding::SinglePassNoder::setSegmentIntersector().
 {
   IntersectionAdder si(li);
   MCIndexNoder noder;
   noder.setSegmentIntersector(&si);
   noder.computeNodes(segStrings);
   nodedSegStrings = noder.getNodedSubstrings();
   *numInteriorIntersections = si.numInteriorIntersections;
 //System.out.println("# intersection tests: " + si.numTests);
 }
void geos::noding::IteratedNoder::setMaximumIterations (int n) inline
Sets the maximum number of noding iterations performed before the noding is aborted. Experience suggests that this should rarely need to be changed from the default. The default is MAX_ITER.
Parameters
n the maximum number of iterations to perform
Definition at line 94 of file IteratedNoder.h.
 { maxIter = n; }
Member Data Documentation
algorithm::LineIntersector geos::noding::IteratedNoder::li private
Definition at line 62 of file IteratedNoder.h.
const int geos::noding::IteratedNoder::MAX_ITER = 5 static private
Definition at line 58 of file IteratedNoder.h.
int geos::noding::IteratedNoder::maxIter private
Definition at line 64 of file IteratedNoder.h.
std::vector<SegmentString*>* geos::noding::IteratedNoder::nodedSegStrings private
Definition at line 63 of file IteratedNoder.h.
const geom::PrecisionModel* geos::noding::IteratedNoder::pm private
Definition at line 61 of file IteratedNoder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/IteratedNoder.h
/home/vicky/potree/geos/vicky/src/noding/IteratedNoder.cpp