GEOS: geos::operation::buffer::SubgraphDepthLocater Class Reference
geos::operation::buffer::SubgraphDepthLocater Class Reference
Locates a subgraph inside a set of subgraphs, in order to determine the outside depth of the subgraph.
#include <geos/opBuffer.h>
Public Member Functions
SubgraphDepthLocater (std::vector< BufferSubgraph * > *newSubgraphs)
~SubgraphDepthLocater ()
int getDepth (const geom::Coordinate &p)
Private Member Functions
void findStabbedSegments (const geom::Coordinate &stabbingRayLeftPt, std::vector< DepthSegment * > &stabbedSegments)
void findStabbedSegments (const geom::Coordinate &stabbingRayLeftPt, std::vector< geomgraph::DirectedEdge * > *dirEdges, std::vector< DepthSegment * > &stabbedSegments)
void findStabbedSegments (const geom::Coordinate &stabbingRayLeftPt, geomgraph::DirectedEdge *dirEdge, std::vector< DepthSegment * > &stabbedSegments)
Private Attributes
std::vector< BufferSubgraph * > * subgraphs
geom::LineSegment seg
Detailed Description
Locates a subgraph inside a set of subgraphs, in order to determine the outside depth of the subgraph.
The input subgraphs are assumed to have had depths already calculated for their edges.
Definition at line 59 of file SubgraphDepthLocater.h.
Constructor & Destructor Documentation
geos::operation::buffer::SubgraphDepthLocater::SubgraphDepthLocater (std::vector< BufferSubgraph * > * newSubgraphs) inline
Definition at line 63 of file SubgraphDepthLocater.h.
     :
     subgraphs(newSubgraphs)
   {}
geos::operation::buffer::SubgraphDepthLocater::~SubgraphDepthLocater () inline
Definition at line 68 of file SubgraphDepthLocater.h.
 {}
Member Function Documentation
void geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments (const geom::Coordinate & stabbingRayLeftPt, std::vector< DepthSegment * > & stabbedSegments) private
Finds all non-horizontal segments intersecting the stabbing line. The stabbing line is the ray to the right of stabbingRayLeftPt.
Parameters
stabbingRayLeftPt the left-hand origin of the stabbing line
stabbedSegments a vector to which DepthSegments intersecting the stabbing line will be added.
Definition at line 175 of file SubgraphDepthLocater.cpp.
References geos::operation::buffer::BufferSubgraph::getDirectedEdges(), geos::operation::buffer::BufferSubgraph::getEnvelope(), geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   size_t size = subgraphs->size();
   for (size_t i=0; i<size; ++i)
   {
     BufferSubgraph *bsg=(*subgraphs)[i];
     // optimization - don't bother checking subgraphs
     // which the ray does not intersect
     Envelope *env = bsg->getEnvelope();
     if ( stabbingRayLeftPt.y < env->getMinY()
       || stabbingRayLeftPt.y > env->getMaxY()
                         || stabbingRayLeftPt.x < env->getMinX()
                         || stabbingRayLeftPt.x > env->getMaxX())
     {
         continue;
     }
     findStabbedSegments(stabbingRayLeftPt, bsg->getDirectedEdges(),
       stabbedSegments);
   }
 }
void geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments (const geom::Coordinate & stabbingRayLeftPt, std::vector< geomgraph::DirectedEdge * > * dirEdges, std::vector< DepthSegment * > & stabbedSegments) private
Finds all non-horizontal segments intersecting the stabbing line in the list of dirEdges. The stabbing line is the ray to the right of stabbingRayLeftPt.
Parameters
stabbingRayLeftPt the left-hand origin of the stabbing line
stabbedSegments the current vector of DepthSegments intersecting the stabbing line will be added.
Check all forward DirectedEdges only. This is still general, because each Edge has a forward DirectedEdge.
Definition at line 201 of file SubgraphDepthLocater.cpp.
References geos::geomgraph::DirectedEdge::isForward().
 {
   for (size_t i=0, n=dirEdges->size(); i<n; ++i)
   {
     DirectedEdge *de=(*dirEdges)[i];
     if (!de->isForward()) continue;
     findStabbedSegments(stabbingRayLeftPt, de, stabbedSegments);
   }
 }
void geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments (const geom::Coordinate & stabbingRayLeftPt, geomgraph::DirectedEdge * dirEdge, std::vector< DepthSegment * > & stabbedSegments) private
Finds all non-horizontal segments intersecting the stabbing line in the input dirEdge. The stabbing line is the ray to the right of stabbingRayLeftPt.
Parameters
stabbingRayLeftPt the left-hand origin of the stabbing line
stabbedSegments the current list of DepthSegments intersecting the stabbing line
Definition at line 221 of file SubgraphDepthLocater.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), geos::geomgraph::DirectedEdge::getDepth(), geos::geomgraph::EdgeEnd::getEdge(), geos::geom::CoordinateSequence::getSize(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   const CoordinateSequence *pts=dirEdge->getEdge()->getCoordinates();
 // It seems that LineSegment is *very* slow... undef this
 // to see yourself
 // LineSegment has been refactored to be mostly inline, still
 // it makes copies of the given coordinates, while the 'non-LineSemgent'
 // based code below uses pointers instead. I'll kip the SKIP_LS
 // defined until LineSegment switches to Coordinate pointers instead.
 //
 #define SKIP_LS 1
   int n = static_cast<int>(pts->getSize())-1;
   for (int i=0; i<n; ++i) {
 #ifndef SKIP_LS
     seg.p0=pts->getAt(i);
     seg.p1=pts->getAt(i + 1);
 #if GEOS_DEBUG
     cerr << " SubgraphDepthLocater::findStabbedSegments: segment " << i
       << " (" << seg << ") ";
 #endif
 #else
     const Coordinate *low=&(pts->getAt(i));
     const Coordinate *high=&(pts->getAt(i+1));
     const Coordinate *swap=nullptr;
 #endif
 #ifndef SKIP_LS
     // ensure segment always points upwards
     //if (seg.p0.y > seg.p1.y)
     {
       seg.reverse();
 #if GEOS_DEBUG
       cerr << " reverse (" << seg << ") ";
 #endif
     }
 #else
     if (low->y > high->y)
     {
       swap=low;
       low=high;
       high=swap;
     }
 #endif
     // skip segment if it is left of the stabbing line
     // skip if segment is above or below stabbing line
 #ifndef SKIP_LS
     double maxx=max(seg.p0.x, seg.p1.x);
 #else
     double maxx=max(low->x, high->x);
 #endif
     if (maxx < stabbingRayLeftPt.x)
     {
 #if GEOS_DEBUG
       cerr<<" segment is left to stabbing line, skipping "<<endl;
 #endif
       continue;
     }
     // skip horizontal segments (there will be a non-horizontal
     // one carrying the same depth info
 #ifndef SKIP_LS
     if (seg.isHorizontal())
 #else
     if (low->y == high->y)
 #endif
     {
 #if GEOS_DEBUG
       cerr<<" segment is horizontal, skipping "<<endl;
 #endif
       continue;
     }
     // skip if segment is above or below stabbing line
 #ifndef SKIP_LS
     if (stabbingRayLeftPt.y < seg.p0.y ||
       stabbingRayLeftPt.y > seg.p1.y)
 #else
     if (stabbingRayLeftPt.y < low->y ||
       stabbingRayLeftPt.y > high->y)
 #endif
     {
 #if GEOS_DEBUG
       cerr<<" segment above or below stabbing line, skipping "<<endl;
 #endif
       continue;
     }
     // skip if stabbing ray is right of the segment
 #ifndef SKIP_LS
     if (CGAlgorithms::computeOrientation(seg.p0, seg.p1,
 #else
     if (CGAlgorithms::computeOrientation(*low, *high,
 #endif
         stabbingRayLeftPt)==CGAlgorithms::RIGHT)
     {
 #if GEOS_DEBUG
       cerr<<" stabbing ray right of segment, skipping"<<endl;
 #endif
       continue;
     }
 #ifndef SKIP_LS
     // stabbing line cuts this segment, so record it
     int depth=dirEdge->getDepth(Position::LEFT);
     // if segment direction was flipped, use RHS depth instead
     if (! (seg.p0==pts->getAt(i)))
       depth=dirEdge->getDepth(Position::RIGHT);
 #else
     int depth = swap ?
       dirEdge->getDepth(Position::RIGHT)
       :
       dirEdge->getDepth(Position::LEFT);
 #endif
 #if GEOS_DEBUG
   cerr<<" depth: "<<depth<<endl;
 #endif
 #ifdef SKIP_LS
     seg.p0 = *low;
     seg.p1 = *high;
 #endif
     DepthSegment *ds=new DepthSegment(seg, depth);
     stabbedSegments.push_back(ds);
   }
 }
int geos::operation::buffer::SubgraphDepthLocater::getDepth (const geom::Coordinate & p)
Definition at line 145 of file SubgraphDepthLocater.cpp.
References geos::operation::buffer::DepthSegment::leftDepth, and geos::geom::Coordinate::toString().
Referenced by geos::operation::buffer::BufferBuilder::buildSubgraphs().
 {
   vector<DepthSegment*> stabbedSegments;
   findStabbedSegments(p, stabbedSegments);
   // if no segments on stabbing line subgraph must be outside all others
   if (stabbedSegments.size()==0) return 0;
   sort(stabbedSegments.begin(), stabbedSegments.end(), DepthSegmentLessThen());
   DepthSegment *ds=stabbedSegments[0];
   int ret = ds->leftDepth;
 #if GEOS_DEBUG
   cerr<<"SubgraphDepthLocater::getDepth("<<p.toString()<<"): "<<ret<<endl;
 #endif
   for (vector<DepthSegment *>::iterator
     it=stabbedSegments.begin(), itEnd=stabbedSegments.end();
     it != itEnd;
     ++it)
   {
     delete *it;
   }
   return ret;
 }
Member Data Documentation
geom::LineSegment geos::operation::buffer::SubgraphDepthLocater::seg private
Definition at line 76 of file SubgraphDepthLocater.h.
std::vector<BufferSubgraph*>* geos::operation::buffer::SubgraphDepthLocater::subgraphs private
Definition at line 74 of file SubgraphDepthLocater.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/SubgraphDepthLocater.h
/home/vicky/potree/geos/vicky/src/operation/buffer/SubgraphDepthLocater.cpp