GEOS: geos::operation::buffer::BufferParameters Class Reference
geos::operation::buffer::BufferParameters Class Reference
Contains the parameters which describe how a buffer should be constructed.
#include <BufferParameters.h>
Public Types
enum EndCapStyle { CAP_ROUND =1, CAP_FLAT =2, CAP_SQUARE =3 }
End cap styles.
enum JoinStyle { JOIN_ROUND =1, JOIN_MITRE =2, JOIN_BEVEL =3 }
Join styles.
Public Member Functions
BufferParameters ()
Creates a default set of parameters.
BufferParameters (int quadrantSegments)
Creates a set of parameters with the given quadrantSegments value.
BufferParameters (int quadrantSegments, EndCapStyle endCapStyle)
Creates a set of parameters with the given quadrantSegments and endCapStyle values.
BufferParameters (int quadrantSegments, EndCapStyle endCapStyle, JoinStyle joinStyle, double mitreLimit)
Creates a set of parameters with the given parameter values.
int getQuadrantSegments () const
Gets the number of quadrant segments which will be used.
void setQuadrantSegments (int quadSegs)
Sets the number of line segments used to approximate an angle fillet.
EndCapStyle getEndCapStyle () const
Gets the end cap style.
void setEndCapStyle (EndCapStyle style)
Specifies the end cap style of the generated buffer.
JoinStyle getJoinStyle () const
Gets the join style.
void setJoinStyle (JoinStyle style)
Sets the join style for outside (reflex) corners between line segments.
double getMitreLimit () const
Gets the mitre ratio limit.
void setMitreLimit (double limit)
Sets the limit on the mitre ratio used for very sharp corners.
void setSingleSided (bool isSingleSided)
bool isSingleSided () const
Static Public Member Functions
static double bufferDistanceError (int quadSegs)
Computes the maximum distance error due to a given level of approximation to a true arc.
Static Public Attributes
static const int DEFAULT_QUADRANT_SEGMENTS = 8
The default number of facets into which to divide a fillet of 90 degrees.
static const double DEFAULT_MITRE_LIMIT = 5.0
The default mitre limit.
Private Attributes
int quadrantSegments
Defaults to DEFAULT_QUADRANT_SEGMENTS;.
EndCapStyle endCapStyle
Defaults to CAP_ROUND;.
JoinStyle joinStyle
Defaults to JOIN_ROUND;.
double mitreLimit
Defaults to DEFAULT_MITRE_LIMIT;.
bool _isSingleSided
Detailed Description
Contains the parameters which describe how a buffer should be constructed.
Definition at line 57 of file BufferParameters.h.
Member Enumeration Documentation
enum geos::operation::buffer::BufferParameters::EndCapStyle
End cap styles.
Enumerator
CAP_ROUND
Specifies a round line buffer end cap style.
CAP_FLAT
Specifies a flat line buffer end cap style.
CAP_SQUARE
Specifies a square line buffer end cap style.
Definition at line 63 of file BufferParameters.h.
{
                 CAP_ROUND=1,
                 CAP_FLAT=2,
                 CAP_SQUARE=3
         };
enum geos::operation::buffer::BufferParameters::JoinStyle
Join styles.
Enumerator
JOIN_ROUND
Specifies a round join style.
JOIN_MITRE
Specifies a mitre join style.
JOIN_BEVEL
Specifies a bevel join style.
Definition at line 76 of file BufferParameters.h.
{
                 JOIN_ROUND=1,
                 JOIN_MITRE=2,
                 JOIN_BEVEL=3
         };
Constructor & Destructor Documentation
geos::operation::buffer::BufferParameters::BufferParameters ()
Creates a default set of parameters.
Definition at line 38 of file BufferParameters.cpp.
     :
     quadrantSegments(DEFAULT_QUADRANT_SEGMENTS),
     endCapStyle(CAP_ROUND),
     joinStyle(JOIN_ROUND),
     mitreLimit(DEFAULT_MITRE_LIMIT),
     _isSingleSided(false)
 {}
geos::operation::buffer::BufferParameters::BufferParameters (int quadrantSegments)
Creates a set of parameters with the given quadrantSegments value.
Parameters
quadrantSegments the number of quadrant segments to use
Definition at line 48 of file BufferParameters.cpp.
References setQuadrantSegments().
   :
   quadrantSegments(DEFAULT_QUADRANT_SEGMENTS),
   endCapStyle(CAP_ROUND),
   joinStyle(JOIN_ROUND),
   mitreLimit(DEFAULT_MITRE_LIMIT),
   _isSingleSided(false)
 {
   setQuadrantSegments(quadrantSegments);
 }
geos::operation::buffer::BufferParameters::BufferParameters (int quadrantSegments, EndCapStyle endCapStyle)
Creates a set of parameters with the given quadrantSegments and endCapStyle values.
Parameters
quadrantSegments the number of quadrant segments to use
endCapStyle the end cap style to use
Definition at line 60 of file BufferParameters.cpp.
References setEndCapStyle(), and setQuadrantSegments().
   :
   quadrantSegments(DEFAULT_QUADRANT_SEGMENTS),
   endCapStyle(CAP_ROUND),
   joinStyle(JOIN_ROUND),
   mitreLimit(DEFAULT_MITRE_LIMIT),
   _isSingleSided(false)
 {
   setQuadrantSegments(quadrantSegments);
   setEndCapStyle(endCapStyle);
 }
geos::operation::buffer::BufferParameters::BufferParameters (int quadrantSegments, EndCapStyle endCapStyle, JoinStyle joinStyle, double mitreLimit)
Creates a set of parameters with the given parameter values.
Parameters
quadrantSegments the number of quadrant segments to use
endCapStyle the end cap style to use
joinStyle the join style to use
mitreLimit the mitre limit to use
Definition at line 74 of file BufferParameters.cpp.
References setEndCapStyle(), setJoinStyle(), setMitreLimit(), and setQuadrantSegments().
   :
   quadrantSegments(DEFAULT_QUADRANT_SEGMENTS),
   endCapStyle(CAP_ROUND),
   joinStyle(JOIN_ROUND),
   mitreLimit(DEFAULT_MITRE_LIMIT),
   _isSingleSided(false)
 {
   setQuadrantSegments(quadrantSegments);
   setEndCapStyle(endCapStyle);
   setJoinStyle(joinStyle);
   setMitreLimit(mitreLimit);
 }
Member Function Documentation
double geos::operation::buffer::BufferParameters::bufferDistanceError (int quadSegs) static
Computes the maximum distance error due to a given level of approximation to a true arc.
Parameters
quadSegs the number of segments used to approximate a quarter-circle
Returns
the error of approximation
Definition at line 129 of file BufferParameters.cpp.
References M_PI.
 {
   double alpha = M_PI / 2.0 / quadSegs;
   return 1 - cos(alpha / 2.0);
 }
EndCapStyle geos::operation::buffer::BufferParameters::getEndCapStyle () const inline
Gets the end cap style.
Returns
the end cap style
Definition at line 185 of file BufferParameters.h.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addLineEndCap().
 { return endCapStyle; }
JoinStyle geos::operation::buffer::BufferParameters::getJoinStyle () const inline
Gets the join style.
Returns
the join style
Definition at line 205 of file BufferParameters.h.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addCollinear(), geos::operation::buffer::OffsetSegmentGenerator::addOutsideTurn(), and geos::operation::buffer::OffsetSegmentGenerator::OffsetSegmentGenerator().
 { return joinStyle; }
double geos::operation::buffer::BufferParameters::getMitreLimit () const inline
Gets the mitre ratio limit.
Returns
the limit value
Definition at line 225 of file BufferParameters.h.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addMitreJoin().
 { return mitreLimit; }
int geos::operation::buffer::BufferParameters::getQuadrantSegments () const inline
Gets the number of quadrant segments which will be used.
Returns
the number of quadrant segments
Definition at line 138 of file BufferParameters.h.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::OffsetSegmentGenerator().
 { return quadrantSegments; }
bool geos::operation::buffer::BufferParameters::isSingleSided () const inline
Tests whether the buffer is to be generated on a single side only.
Returns
true if the generated buffer is to be single-sided
Definition at line 272 of file BufferParameters.h.
Referenced by geos::operation::buffer::OffsetCurveSetBuilder::addLineString().
{
     return _isSingleSided;
   }
void geos::operation::buffer::BufferParameters::setEndCapStyle (EndCapStyle style) inline
Specifies the end cap style of the generated buffer.
The styles supported are CAP_ROUND, CAP_BUTT, and CAP_SQUARE.
The default is CAP_ROUND.
Parameters
style the end cap style to specify
Definition at line 196 of file BufferParameters.h.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), BufferParameters(), GEOSBufferWithStyle_r(), GEOSOffsetCurve_r(), and GEOSSingleSidedBuffer_r().
   {
     endCapStyle = style;
   }
void geos::operation::buffer::BufferParameters::setJoinStyle (JoinStyle style) inline
Sets the join style for outside (reflex) corners between line segments.
Allowable values are JOIN_ROUND (which is the default), JOIN_MITRE and JOIN_BEVEL.
Parameters
style the code for the join style
Definition at line 216 of file BufferParameters.h.
Referenced by BufferParameters(), GEOSBufferWithStyle_r(), GEOSOffsetCurve_r(), and GEOSSingleSidedBuffer_r().
   {
     joinStyle = style;
   }
void geos::operation::buffer::BufferParameters::setMitreLimit (double limit) inline
Sets the limit on the mitre ratio used for very sharp corners.
The mitre ratio is the ratio of the distance from the corner to the end of the mitred offset corner. When two line segments meet at a sharp angle, a miter join will extend far beyond the original geometry. (and in the extreme case will be infinitely far.) To prevent unreasonable geometry, the mitre limit allows controlling the maximum length of the join corner. Corners with a ratio which exceed the limit will be beveled.
Parameters
limit the mitre ratio limit
Definition at line 240 of file BufferParameters.h.
Referenced by BufferParameters(), GEOSBufferWithStyle_r(), GEOSOffsetCurve_r(), and GEOSSingleSidedBuffer_r().
   {
     mitreLimit = limit;
   }
void geos::operation::buffer::BufferParameters::setQuadrantSegments (int quadSegs)
Sets the number of line segments used to approximate an angle fillet.
If quadSegs >= 1, joins are round, and quadSegs indicates the number of segments to use to approximate a quarter-circle.
If quadSegs = 0, joins are bevelled (flat)
If quadSegs < 0, joins are mitred, and the value of qs indicates the mitre ration limit as
   mitreLimit = |quadSegs|
For round joins, quadSegs determines the maximum error in the approximation to the true buffer curve.
The default value of 8 gives less than 2% max error in the buffer distance.
For a max error of < 1%, use QS = 12. For a max error of < 0.1%, use QS = 18. The error is always less than the buffer distance (in other words, the computed buffer curve is always inside the true curve).
Parameters
quadrantSegments the number of segments in a fillet for a quadrant
Indicates how to construct fillets. If qs >= 1, fillet is round, and qs indicates number of segments to use to approximate a quarter-circle. If qs = 0, fillet is bevelled flat (i.e. no filleting is performed) If qs < 0, fillet is mitred, and absolute value of qs indicates maximum length of mitre according to
mitreLimit = |qs|
If join style was set by the quadSegs value, use the default for the actual quadrantSegments value.
Definition at line 93 of file BufferParameters.cpp.
References DEFAULT_QUADRANT_SEGMENTS, JOIN_BEVEL, JOIN_MITRE, JOIN_ROUND, joinStyle, mitreLimit, and quadrantSegments.
Referenced by BufferParameters(), GEOSBufferWithStyle_r(), GEOSOffsetCurve_r(), and GEOSSingleSidedBuffer_r().
 {
   quadrantSegments = quadSegs;
   if (quadrantSegments == 0)
     joinStyle = JOIN_BEVEL;
   if (quadrantSegments < 0) {
     joinStyle = JOIN_MITRE;
     mitreLimit = std::abs(quadrantSegments);
   }
   if (quadSegs <= 0) {
     quadrantSegments = 1;
   }
   if (joinStyle != JOIN_ROUND) {
     quadrantSegments = DEFAULT_QUADRANT_SEGMENTS;
   }
 }
void geos::operation::buffer::BufferParameters::setSingleSided (bool isSingleSided) inline
Sets whether the computed buffer should be single-sided. A single-sided buffer is constructed on only one side of each input line.
The side used is determined by the sign of the buffer distance:
a positive distance indicates the left-hand side
a negative distance indicates the right-hand side
The single-sided buffer of point geometries is the same as the regular buffer.
The End Cap Style for single-sided buffers is always ignored, and forced to the equivalent of CAP_FLAT.
Parameters
isSingleSided true if a single-sided buffer should be constructed
Definition at line 262 of file BufferParameters.h.
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided().
   {
     _isSingleSided = isSingleSided;
   }
Member Data Documentation
bool geos::operation::buffer::BufferParameters::_isSingleSided private
Definition at line 291 of file BufferParameters.h.
const double geos::operation::buffer::BufferParameters::DEFAULT_MITRE_LIMIT = 5.0 static
The default mitre limit.
Allows fairly pointy mitres.
Definition at line 102 of file BufferParameters.h.
const int geos::operation::buffer::BufferParameters::DEFAULT_QUADRANT_SEGMENTS = 8 static
The default number of facets into which to divide a fillet of 90 degrees.
A value of 8 gives less than 2% max error in the buffer distance. For a max error of < 1%, use QS = 12. For a max error of < 0.1%, use QS = 18.
Definition at line 96 of file BufferParameters.h.
Referenced by setQuadrantSegments().
EndCapStyle geos::operation::buffer::BufferParameters::endCapStyle private
Defaults to CAP_ROUND;.
Definition at line 283 of file BufferParameters.h.
JoinStyle geos::operation::buffer::BufferParameters::joinStyle private
Defaults to JOIN_ROUND;.
Definition at line 286 of file BufferParameters.h.
Referenced by setQuadrantSegments().
double geos::operation::buffer::BufferParameters::mitreLimit private
Defaults to DEFAULT_MITRE_LIMIT;.
Definition at line 289 of file BufferParameters.h.
Referenced by setQuadrantSegments().
int geos::operation::buffer::BufferParameters::quadrantSegments private
Defaults to DEFAULT_QUADRANT_SEGMENTS;.
Definition at line 280 of file BufferParameters.h.
Referenced by setQuadrantSegments().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/BufferParameters.h
/home/vicky/potree/geos/vicky/src/operation/buffer/BufferParameters.cpp