GEOS: geos::algorithm::CGAlgorithms Class Reference
geos::algorithm::CGAlgorithms Class Reference
Specifies and implements various fundamental Computational Geometric algorithms. The algorithms supplied in this class are robust for double-precision floating point.
#include <CGAlgorithms.h>
Public Types
enum { CLOCKWISE =-1, COLLINEAR, COUNTERCLOCKWISE }
enum { RIGHT =-1, LEFT, STRAIGHT }
Public Member Functions
CGAlgorithms ()
Static Public Member Functions
static bool isPointInRing (const geom::Coordinate &p, const geom::CoordinateSequence *ring)
Tests whether a point lies inside a ring.
static bool isPointInRing (const geom::Coordinate &p, const std::vector< const geom::Coordinate * > &ring)
Same as above, but taking a vector of const Coordinates (faster)
static int locatePointInRing (const geom::Coordinate &p, const geom::CoordinateSequence &ring)
Determines whether a point lies in the interior, on the boundary, or in the exterior of a ring.
static int locatePointInRing (const geom::Coordinate &p, const std::vector< const geom::Coordinate * > &ring)
Same as above, but taking a vector of const Coordinates.
static bool isOnLine (const geom::Coordinate &p, const geom::CoordinateSequence *pt)
Test whether a point lies on the given line segment.
static bool isCCW (const geom::CoordinateSequence *ring)
Computes whether a ring defined by an array of Coordinate is oriented counter-clockwise.
static int computeOrientation (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &q)
Computes the orientation of a point q to the directed line segment p1-p2.
static double distancePointLine (const geom::Coordinate &p, const geom::Coordinate &A, const geom::Coordinate &B)
Computes the distance from a point p to a line segment AB.
static double distancePointLinePerpendicular (const geom::Coordinate &p, const geom::Coordinate &A, const geom::Coordinate &B)
Computes the perpendicular distance from a point p to the (infinite) line containing the points AB.
static double distanceLineLine (const geom::Coordinate &A, const geom::Coordinate &B, const geom::Coordinate &C, const geom::Coordinate &D)
Computes the distance from a line segment AB to a line segment CD.
static double signedArea (const geom::CoordinateSequence *ring)
Returns the signed area for a ring. The area is positive if the ring is oriented CW.
static double length (const geom::CoordinateSequence *pts)
Computes the length of a linestring specified by a sequence of points.
static int orientationIndex (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &q)
Returns the index of the direction of the point q relative to a vector specified by p1-p2.
Detailed Description
Specifies and implements various fundamental Computational Geometric algorithms. The algorithms supplied in this class are robust for double-precision floating point.
Definition at line 47 of file CGAlgorithms.h.
Member Enumeration Documentation
anonymous enum
Enumerator
CLOCKWISE
COLLINEAR
COUNTERCLOCKWISE
Definition at line 51 of file CGAlgorithms.h.
        {
     CLOCKWISE=-1,
     COLLINEAR,
     COUNTERCLOCKWISE
   };
anonymous enum
Enumerator
RIGHT
LEFT
STRAIGHT
Definition at line 57 of file CGAlgorithms.h.
        {
     RIGHT=-1,
     LEFT,
     STRAIGHT
   };
Constructor & Destructor Documentation
geos::algorithm::CGAlgorithms::CGAlgorithms () inline
Definition at line 63 of file CGAlgorithms.h.
 {}
Member Function Documentation
int geos::algorithm::CGAlgorithms::computeOrientation (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & q) static
Computes the orientation of a point q to the directed line segment p1-p2.
The orientation of a point relative to a directed line segment indicates which way you turn to get to q after travelling from p1 to p2.
Returns
1 if q is counter-clockwise from p1-p2
-1 if q is clockwise from p1-p2
0 if q is collinear with p1-p2
Definition at line 183 of file CGAlgorithms.cpp.
Referenced by geos::geomgraph::EdgeEnd::compareDirection(), and geos::geomgraph::PlanarGraph::matchInSameDirection().
 {
   return orientationIndex(p1,p2,q);
 }
double geos::algorithm::CGAlgorithms::distanceLineLine (const geom::Coordinate & A, const geom::Coordinate & B, const geom::Coordinate & C, const geom::Coordinate & D) static
Computes the distance from a line segment AB to a line segment CD.
Note: NON-ROBUST!
Parameters
A a point of one line
B the second point of (must be different to A)
C one point of the line
D another point of the line (must be different to A)
Definition at line 245 of file CGAlgorithms.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::geom::LineSegment::distance().
 {
   // check for zero-length segments
   if (A==B) return distancePointLine(A,C,D);
   if (C==D) return distancePointLine(D,A,B);
     // AB and CD are line segments
     /* from comp.graphics.algo
   Solving the above for r and s yields
         (Ay-Cy)(Dx-Cx)-(Ax-Cx)(Dy-Cy)
              r = ----------------------------- (eqn 1)
         (Bx-Ax)(Dy-Cy)-(By-Ay)(Dx-Cx)
       (Ay-Cy)(Bx-Ax)-(Ax-Cx)(By-Ay)
     s = ----------------------------- (eqn 2)
       (Bx-Ax)(Dy-Cy)-(By-Ay)(Dx-Cx)
   Let P be the position vector of the intersection point, then
     P=A+r(B-A) or
     Px=Ax+r(Bx-Ax)
     Py=Ay+r(By-Ay)
   By examining the values of r & s, you can also determine some other
 limiting conditions:
     If 0<=r<=1 & 0<=s<=1, intersection exists
     r<0 or r>1 or s<0 or s>1 line segments do not intersect
     If the denominator in eqn 1 is zero, AB & CD are parallel
     If the numerator in eqn 1 is also zero, AB & CD are collinear.
   */
   double r_top=(A.y-C.y)*(D.x-C.x)-(A.x-C.x)*(D.y-C.y);
   double r_bot=(B.x-A.x)*(D.y-C.y)-(B.y-A.y)*(D.x-C.x);
   double s_top=(A.y-C.y)*(B.x-A.x)-(A.x-C.x)*(B.y-A.y);
   double s_bot=(B.x-A.x)*(D.y-C.y)-(B.y-A.y)*(D.x-C.x);
   if ((r_bot==0)||(s_bot==0)) {
     return std::min(distancePointLine(A,C,D),
             std::min(distancePointLine(B,C,D),
             std::min(distancePointLine(C,A,B), distancePointLine(D,A,B))));
   }
   double s=s_top/s_bot;
   double r=r_top/r_bot;
   if ((r<0)||( r>1)||(s<0)||(s>1)) {
     //no intersection
     return std::min(distancePointLine(A,C,D),
             std::min(distancePointLine(B,C,D),
             std::min(distancePointLine(C,A,B), distancePointLine(D,A,B))));
   }
   return 0.0; //intersection exists
 }
double geos::algorithm::CGAlgorithms::distancePointLine (const geom::Coordinate & p, const geom::Coordinate & A, const geom::Coordinate & B) static
Computes the distance from a point p to a line segment AB.
Note: NON-ROBUST!
Parameters
p the point to compute the distance for
A one point of the line
B another point of the line (must be different to A)
Returns
the distance from p to line segment AB
Definition at line 191 of file CGAlgorithms.cpp.
References geos::geom::Coordinate::distance(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::precision::MinimumClearance::compute(), and geos::geom::LineSegment::distance().
 {
   //if start==end, then use pt distance
   if (A==B) return p.distance(A);
     // otherwise use comp.graphics.algorithms Frequently Asked Questions method
     /*(1)             AC dot AB
                    r = ---------
                          ||AB||^2
     r has the following meaning:
     r=0 P = A
     r=1 P = B
     r<0 P is on the backward extension of AB
     r>1 P is on the forward extension of AB
     0<r<1 P is interior to AB
   */
   double r=((p.x-A.x)*(B.x-A.x)+(p.y-A.y)*(B.y-A.y))/
        ((B.x-A.x)*(B.x-A.x)+(B.y-A.y)*(B.y-A.y));
   if (r<=0.0) return p.distance(A);
   if (r>=1.0) return p.distance(B);
     /*(2)
          (Ay-Cy)(Bx-Ax)-(Ax-Cx)(By-Ay)
     s = -----------------------------
                   L^2
     Then the distance from C to P = |s|*L.
   */
   double s=((A.y-p.y)*(B.x-A.x)-(A.x-p.x)*(B.y-A.y))/
        ((B.x-A.x)*(B.x-A.x)+(B.y-A.y)*(B.y-A.y));
   return fabs(s)*sqrt(((B.x-A.x)*(B.x-A.x)+(B.y-A.y)*(B.y-A.y)));
 }
double geos::algorithm::CGAlgorithms::distancePointLinePerpendicular (const geom::Coordinate & p, const geom::Coordinate & A, const geom::Coordinate & B) static
Computes the perpendicular distance from a point p to the (infinite) line containing the points AB.
Parameters
p the point to compute the distance for
A one point of the line
B another point of the line (must be different to A)
Returns
the distance from p to line AB
Definition at line 226 of file CGAlgorithms.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::geom::LineSegment::distancePerpendicular().
 {
     // use comp.graphics.algorithms Frequently Asked Questions method
     /*(2)
                      (Ay-Cy)(Bx-Ax)-(Ax-Cx)(By-Ay)
                 s = -----------------------------
                                      L^2
                 Then the distance from C to P = |s|*L.
         */
   double s = ((A.y - p.y) *(B.x - A.x) - (A.x - p.x)*(B.y - A.y) )
               /
             ((B.x - A.x) * (B.x - A.x) + (B.y - A.y) * (B.y - A.y) );
     return fabs(s)*sqrt(((B.x - A.x) * (B.x - A.x) + (B.y - A.y) * (B.y - A.y)));
 }
bool geos::algorithm::CGAlgorithms::isCCW (const geom::CoordinateSequence * ring) static
Computes whether a ring defined by an array of Coordinate is oriented counter-clockwise.
The list of points is assumed to have the first and last points equal.
This will handle coordinate lists which contain repeated points.
This algorithm is only guaranteed to work with valid rings. If the ring is invalid (e.g. self-crosses or touches), the computed result may not be correct.
Parameters
ring an array of coordinates forming a ring
Returns
true if the ring is oriented counter-clockwise.
If disc is exactly 0, lines are collinear. There are two possible cases: (1) the lines lie along the x axis in opposite directions (2) the lines lie on top of one another
(1) is handled by checking if next is left of prev ==> CCW (2) should never happen, so we're going to ignore it! (Might want to assert this)
Definition at line 100 of file CGAlgorithms.cpp.
References geos::geom::Coordinate::equals2D(), geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::geomgraph::EdgeRing::computeRing(), GEOSCoordSeq_isCCW_r(), and geos::geom::Polygon::normalize().
 {
   // # of points without closing endpoint
   const std::size_t nPts=ring->getSize()-1;
   // sanity check
   if (nPts < 3)
   {
     throw util::IllegalArgumentException("Ring has fewer than 3 points, so orientation cannot be determined");
   }
   // find highest point
   const Coordinate *hiPt=&ring->getAt(0);
   int hiIndex=0;
   for (std::size_t i=1; i<=nPts; ++i)
   {
     const Coordinate *p=&ring->getAt(i);
     if (p->y > hiPt->y) {
       hiPt = p;
       hiIndex = static_cast<int>(i);
     }
   }
   // find distinct point before highest point
   int iPrev = hiIndex;
   do {
     iPrev = iPrev - 1;
     if (iPrev < 0)
             iPrev = static_cast<int>(nPts);
   } while (ring->getAt(iPrev)==*hiPt && iPrev!=hiIndex);
   // find distinct point after highest point
   int iNext = hiIndex;
   do {
     iNext = (iNext + 1) % static_cast<int>(nPts);
   } while (ring->getAt(iNext)==*hiPt && iNext != hiIndex);
   const Coordinate *prev=&ring->getAt(iPrev);
   const Coordinate *next=&ring->getAt(iNext);
   /*
    * This check catches cases where the ring contains an A-B-A
    * configuration of points.
    * This can happen if the ring does not contain 3 distinct points
    * (including the case where the input array has fewer than 4 elements),
    * or it contains coincident line segments.
    */
   if ( prev->equals2D(*hiPt) || next->equals2D(*hiPt) ||
     prev->equals2D(*next) )
   {
     return false;
     // MD - don't bother throwing exception,
     // since this isn't a complete check for ring validity
     //throw  IllegalArgumentException("degenerate ring (does not contain 3 distinct points)");
   }
   int disc = computeOrientation(*prev, *hiPt, *next);
   bool isCCW=false;
   if (disc == 0) {
     // poly is CCW if prev x is right of next x
     isCCW = (prev->x > next->x);
   } else {
     // if area is positive, points are ordered CCW
     isCCW = (disc > 0);
   }
   return isCCW;
 }
bool geos::algorithm::CGAlgorithms::isOnLine (const geom::Coordinate & p, const geom::CoordinateSequence * pt) static
Test whether a point lies on the given line segment.
Returns
true true if the point is a vertex of the line or lies in the interior of a line segment in the linestring
Definition at line 81 of file CGAlgorithms.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   //LineIntersector lineIntersector;
   size_t ptsize = pt->getSize();
   if ( ptsize == 0 ) return false;
   const Coordinate *pp=&(pt->getAt(0));
   for(size_t i=1; i<ptsize; ++i)
   {
     const Coordinate &p1=pt->getAt(i);
     if ( LineIntersector::hasIntersection(p, *pp, p1) )
       return true;
     pp=&p1;
   }
   return false;
 }
bool geos::algorithm::CGAlgorithms::isPointInRing (const geom::Coordinate & p, const geom::CoordinateSequence * ring) static
Tests whether a point lies inside a ring.
The ring may be oriented in either direction. A point lying exactly on the ring boundary is considered to be inside the ring.
This algorithm does not first check the point against the envelope of the ring.
Parameters
p point to check for ring inclusion
ring is assumed to have first point identical to last point
Returns
true if p is inside ring
See also
locatePointInRing
Definition at line 50 of file CGAlgorithms.cpp.
Referenced by geos::geomgraph::EdgeRing::containsPoint(), geos::operation::valid::SweeplineNestedRingTester::isInside(), geos::operation::valid::IndexedNestedRingTester::isNonNested(), and geos::operation::valid::SimpleNestedRingTester::isNonNested().
 {
   return locatePointInRing(p, *ring) != Location::EXTERIOR;
 }
static bool geos::algorithm::CGAlgorithms::isPointInRing (const geom::Coordinate & p, const std::vector< const geom::Coordinate * > & ring) static
Same as above, but taking a vector of const Coordinates (faster)
double geos::algorithm::CGAlgorithms::length (const geom::CoordinateSequence * pts) static
Computes the length of a linestring specified by a sequence of points.
Parameters
pts the points specifying the linestring
Returns
the length of the linestring
Definition at line 323 of file CGAlgorithms.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   // optimized for processing CoordinateSequences
   size_t npts=pts->getSize();
   if (npts <= 1) return 0.0;
   double len = 0.0;
   const Coordinate& p0 = pts->getAt(0);
   double x0 = p0.x;
   double y0 = p0.y;
   for(size_t i = 1; i < npts; ++i)
   {
     const Coordinate& p = pts->getAt(i);
     double x1 = p.x;
     double y1 = p.y;
     double dx = x1 - x0;
     double dy = y1 - y0;
     len += sqrt(dx * dx + dy * dy);
     x0 = x1;
     y0 = y1;
   }
   return len;
 }
int geos::algorithm::CGAlgorithms::locatePointInRing (const geom::Coordinate & p, const geom::CoordinateSequence & ring) static
Determines whether a point lies in the interior, on the boundary, or in the exterior of a ring.
The ring may be oriented in either direction.
This method does not first check the point against the envelope of the ring.
Parameters
p point to check for ring inclusion
ring an array of coordinates representing the ring (which must have first point identical to last point)
Returns
the Location of p relative to the ring
Definition at line 65 of file CGAlgorithms.cpp.
 {
   return RayCrossingCounter::locatePointInRing(p, ring);
 }
int geos::algorithm::CGAlgorithms::locatePointInRing (const geom::Coordinate & p, const std::vector< const geom::Coordinate * > & ring) static
Same as above, but taking a vector of const Coordinates.
Definition at line 73 of file CGAlgorithms.cpp.
 {
   return RayCrossingCounter::locatePointInRing(p, ring);
 }
int geos::algorithm::CGAlgorithms::orientationIndex (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & q) static
Returns the index of the direction of the point q relative to a vector specified by p1-p2.
Parameters
p1 the origin point of the vector
p2 the final point of the vector
q the point to compute the direction to
Returns
1 if q is counter-clockwise (left) from p1-p2
-1 if q is clockwise (right) from p1-p2
0 if q is collinear with p1-p2
Definition at line 43 of file CGAlgorithms.cpp.
Referenced by geos::geom::LineSegment::orientationIndex().
 {
   return RayCrossingCounter::orientationIndex(p1, p2, q);
 }
double geos::algorithm::CGAlgorithms::signedArea (const geom::CoordinateSequence * ring) static
Returns the signed area for a ring. The area is positive if the ring is oriented CW.
Definition at line 297 of file CGAlgorithms.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::geom::Polygon::getArea().
 {
   size_t npts=ring->getSize();
   if (npts<3) return 0.0;
   Coordinate pp;
   Coordinate cp = ring->getAt(0);
   Coordinate np = ring->getAt(1);
   double x0 = cp.x;
         np.x -= x0;
   double sum=0.0;
   for (size_t i=1; i<npts; ++i)
   {
     pp.y = cp.y;
     cp.x = np.x;
     cp.y = np.y;
     ring->getAt(i, np);
                 np.x -= x0;
     sum += cp.x * (np.y - pp.y);
   }
   return -sum/2.0;
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/CGAlgorithms.h
/home/vicky/potree/geos/vicky/src/algorithm/CGAlgorithms.cpp