GEOS: geos::linearref::LinearIterator Class Reference
geos::linearref::LinearIterator Class Reference
An iterator over the components and coordinates of a linear geometry (LineString or MultiLineString).
#include <LinearIterator.h>
Public Member Functions
LinearIterator (const geom::Geometry *linear)
LinearIterator (const geom::Geometry *linear, const LinearLocation &start)
LinearIterator (const geom::Geometry *linear, unsigned int componentIndex, unsigned int vertexIndex)
bool hasNext () const
void next ()
bool isEndOfLine () const
unsigned int getComponentIndex () const
unsigned int getVertexIndex () const
const geom::LineString * getLine () const
geom::Coordinate getSegmentStart () const
geom::Coordinate getSegmentEnd () const
Private Member Functions
void loadCurrentLine ()
LinearIterator (const LinearIterator &other)=delete
LinearIterator & operator= (const LinearIterator &rhs)=delete
Static Private Member Functions
static unsigned int segmentEndVertexIndex (const LinearLocation &loc)
Private Attributes
const geom::LineString * currentLine
unsigned int vertexIndex
unsigned int componentIndex
const geom::Geometry * linear
const unsigned int numLines
Detailed Description
An iterator over the components and coordinates of a linear geometry (LineString or MultiLineString).
The standard usage pattern for a LinearIterator is:
for (LinearIterator it = new LinearIterator(...); it.hasNext(); it.next()) {
  ...
  int ci = it.getComponentIndex();   // for example
  int vi = it.getVertexIndex();      // for example
  ...
}
Version
1.7
Definition at line 50 of file LinearIterator.h.
Constructor & Destructor Documentation
geos::linearref::LinearIterator::LinearIterator (const geom::Geometry * linear)
Creates an iterator initialized to the start of a linear Geometry
Parameters
linear the linear geometry to iterate over
Definition at line 41 of file LinearIterator.cpp.
References loadCurrentLine().
                                                      :
     vertexIndex(0),
     componentIndex(0),
     linear(linear),
     numLines(static_cast<unsigned int>(linear->getNumGeometries()))
 {
   loadCurrentLine();
 }
geos::linearref::LinearIterator::LinearIterator (const geom::Geometry * linear, const LinearLocation & start)
Creates an iterator starting at a LinearLocation on a linear Geometry
Parameters
linear the linear geometry to iterate over
start the location to start at
Definition at line 51 of file LinearIterator.cpp.
References loadCurrentLine().
                                                                                  :
     vertexIndex(segmentEndVertexIndex(start)),
     componentIndex(start.getComponentIndex()),
     linear(linear),
     numLines(static_cast<unsigned int>(linear->getNumGeometries()))
 {
   loadCurrentLine();
 }
geos::linearref::LinearIterator::LinearIterator (const geom::Geometry * linear, unsigned int componentIndex, unsigned int vertexIndex)
Creates an iterator starting at a component and vertex in a linear Geometry
Parameters
linear the linear geometry to iterate over
componentIndex the component to start at
vertexIndex the vertex to start at
Definition at line 60 of file LinearIterator.cpp.
References loadCurrentLine().
                                                                                                             :
     vertexIndex(vertexIndex),
     componentIndex(componentIndex),
     linear(linear),
     numLines(static_cast<unsigned int>(linear->getNumGeometries()))
 {
   loadCurrentLine();
 }
geos::linearref::LinearIterator::LinearIterator (const LinearIterator & other) private delete
Member Function Documentation
unsigned int geos::linearref::LinearIterator::getComponentIndex () const
The component index of the vertex the iterator is currently at.
Returns
the current component index
Definition at line 115 of file LinearIterator.cpp.
References componentIndex.
Referenced by geos::linearref::LengthLocationMap::getLength(), and geos::linearref::LengthLocationMap::getLocationForward().
 {
   return componentIndex;
 }
const LineString * geos::linearref::LinearIterator::getLine () const
Gets the LineString component the iterator is current at.
Returns
a linestring
Definition at line 125 of file LinearIterator.cpp.
References currentLine.
Referenced by getSegmentEnd().
 {
   return currentLine;
 }
Coordinate geos::linearref::LinearIterator::getSegmentEnd () const
Gets the second Coordinate of the current segment. (the coordinate of the next vertex). If the iterator is at the end of a line, null is returned.
Returns
a Coordinate or null
Definition at line 135 of file LinearIterator.cpp.
References currentLine, geos::geom::LineString::getCoordinateN(), getLine(), geos::geom::Coordinate::setNull(), and vertexIndex.
Referenced by geos::linearref::LengthLocationMap::getLength(), geos::linearref::LengthLocationMap::getLocationForward(), and geos::linearref::LengthIndexOfPoint::indexOfFromStart().
 {
   if (vertexIndex < getLine()->getNumPoints() - 1)
     return currentLine->getCoordinateN(vertexIndex + 1);
   Coordinate c;
   c.setNull();
   return c;
 }
Coordinate geos::linearref::LinearIterator::getSegmentStart () const
Gets the first Coordinate of the current segment. (the coordinate of the current vertex).
Returns
a Coordinate
Definition at line 130 of file LinearIterator.cpp.
References currentLine, geos::geom::LineString::getCoordinateN(), and vertexIndex.
Referenced by geos::linearref::LengthLocationMap::getLength(), geos::linearref::LengthLocationMap::getLocationForward(), and geos::linearref::LengthIndexOfPoint::indexOfFromStart().
 {
   return currentLine->getCoordinateN(vertexIndex);
 }
unsigned int geos::linearref::LinearIterator::getVertexIndex () const
The vertex index of the vertex the iterator is currently at.
Returns
the current vertex index
Definition at line 120 of file LinearIterator.cpp.
References vertexIndex.
Referenced by geos::linearref::LengthLocationMap::getLength(), and geos::linearref::LengthLocationMap::getLocationForward().
 {
   return vertexIndex;
 }
bool geos::linearref::LinearIterator::hasNext () const
Tests whether there are any vertices left to iterator over.
Returns
true if there are more vertices to scan
Definition at line 82 of file LinearIterator.cpp.
References componentIndex, currentLine, geos::geom::LineString::getNumPoints(), numLines, and vertexIndex.
Referenced by geos::linearref::ExtractLineByLocation::computeLinear(), geos::linearref::LengthLocationMap::getLength(), geos::linearref::LengthLocationMap::getLocationForward(), geos::linearref::LocationIndexOfPoint::indexOfFromStart(), geos::linearref::LengthIndexOfPoint::indexOfFromStart(), and next().
 {
   if (componentIndex >= numLines) return false;
   if (componentIndex == numLines - 1
       && vertexIndex >= currentLine->getNumPoints())
     return false;
   return true;
 }
bool geos::linearref::LinearIterator::isEndOfLine () const
Checks whether the iterator cursor is pointing to the endpoint of a component LineString.
Returns
true</true> if the iterator is at an endpoint
Definition at line 104 of file LinearIterator.cpp.
References componentIndex, currentLine, and numLines.
Referenced by geos::linearref::LengthLocationMap::getLength(), geos::linearref::LengthLocationMap::getLocationForward(), and geos::linearref::LengthIndexOfPoint::indexOfFromStart().
 {
   if (componentIndex >= numLines) return false;
   //LineString currentLine = (LineString) linear.getGeometryN(componentIndex);
   if (!currentLine)
     return false;
   if (vertexIndex < currentLine->getNumPoints() - 1)
     return false;
   return true;
 }
void geos::linearref::LinearIterator::loadCurrentLine () private
Invariant: currentLine <> null if the iterator is pointing at a valid coordinate
Exceptions
IllegalArgumentException if linearGeom is not Lineal
Definition at line 69 of file LinearIterator.cpp.
References componentIndex, currentLine, geos::geom::Geometry::getGeometryN(), linear, and numLines.
Referenced by LinearIterator(), and next().
 {
   if (componentIndex >= numLines)
   {
     currentLine = nullptr;
     return;
   }
   currentLine = dynamic_cast<const LineString *> (linear->getGeometryN(componentIndex));
   if ( ! currentLine ) {
     throw util::IllegalArgumentException("LinearIterator only supports lineal geometry components");
   }
 }
void geos::linearref::LinearIterator::next ()
Moves the iterator ahead to the next vertex and (possibly) linear component.
Definition at line 91 of file LinearIterator.cpp.
References componentIndex, currentLine, geos::geom::LineString::getNumPoints(), hasNext(), loadCurrentLine(), and vertexIndex.
Referenced by geos::linearref::LengthLocationMap::getLength(), geos::linearref::LengthLocationMap::getLocationForward(), and geos::linearref::LengthIndexOfPoint::indexOfFromStart().
 {
   if (! hasNext()) return;
   vertexIndex++;
   if (vertexIndex >= currentLine->getNumPoints())
   {
     componentIndex++;
     loadCurrentLine();
     vertexIndex = 0;
   }
 }
LinearIterator& geos::linearref::LinearIterator::operator= (const LinearIterator & rhs) private delete
unsigned int geos::linearref::LinearIterator::segmentEndVertexIndex (const LinearLocation & loc) static private
Definition at line 34 of file LinearIterator.cpp.
References geos::linearref::LinearLocation::getSegmentFraction(), and geos::linearref::LinearLocation::getSegmentIndex().
 {
   if (loc.getSegmentFraction() > 0.0)
     return loc.getSegmentIndex() + 1;
   return loc.getSegmentIndex();
 }
Member Data Documentation
unsigned int geos::linearref::LinearIterator::componentIndex private
Definition at line 139 of file LinearIterator.h.
Referenced by getComponentIndex(), hasNext(), isEndOfLine(), loadCurrentLine(), and next().
const geom::LineString* geos::linearref::LinearIterator::currentLine private
Definition at line 137 of file LinearIterator.h.
Referenced by getLine(), getSegmentEnd(), getSegmentStart(), hasNext(), isEndOfLine(), loadCurrentLine(), and next().
const geom::Geometry* geos::linearref::LinearIterator::linear private
Definition at line 140 of file LinearIterator.h.
Referenced by loadCurrentLine().
const unsigned int geos::linearref::LinearIterator::numLines private
Definition at line 141 of file LinearIterator.h.
Referenced by hasNext(), isEndOfLine(), and loadCurrentLine().
unsigned int geos::linearref::LinearIterator::vertexIndex private
Definition at line 138 of file LinearIterator.h.
Referenced by getSegmentEnd(), getSegmentStart(), getVertexIndex(), hasNext(), and next().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/linearref/LinearIterator.h
/home/vicky/potree/geos/vicky/src/linearref/LinearIterator.cpp