GEOS: geos::linearref::LengthIndexedLine Class Reference
geos::linearref::LengthIndexedLine Class Reference
Supports linear referencing along a linear Geometry using the length along the line as the index. Negative length values are taken as measured in the reverse direction from the end of the geometry. Out-of-range index values are handled by clamping them to the valid range of values. Non-simple lines (i.e. which loop back to cross or touch themselves) are supported.
#include <LengthIndexedLine.h>
Public Member Functions
LengthIndexedLine (const geom::Geometry *linearGeom)
Constructs an object which allows a linear Geometry to be linearly referenced using length as an index.
geom::Coordinate extractPoint (double index) const
Computes the Coordinate for the point on the line at the given index. If the index is out of range the first or last point on the line will be returned. The Z-ordinate of the computed point will be interpolated from the Z-ordinates of the line segment containing it, if they exist.
geom::Coordinate extractPoint (double index, double offsetDistance) const
Computes the Coordinate for the point on the line at the given index, offset by the given distance.
geom::Geometry * extractLine (double startIndex, double endIndex) const
double indexOf (const geom::Coordinate &pt) const
double indexOfAfter (const geom::Coordinate &pt, double minIndex) const
double * indicesOf (const geom::Geometry *subLine) const
double project (const geom::Coordinate &pt) const
double getStartIndex () const
double getEndIndex () const
bool isValidIndex (double index) const
double clampIndex (double index) const
Private Member Functions
LinearLocation locationOf (double index) const
LinearLocation locationOf (double index, bool resolveLower) const
double positiveIndex (double index) const
Private Attributes
const geom::Geometry * linearGeom
Detailed Description
Supports linear referencing along a linear Geometry using the length along the line as the index. Negative length values are taken as measured in the reverse direction from the end of the geometry. Out-of-range index values are handled by clamping them to the valid range of values. Non-simple lines (i.e. which loop back to cross or touch themselves) are supported.
Definition at line 45 of file LengthIndexedLine.h.
Constructor & Destructor Documentation
geos::linearref::LengthIndexedLine::LengthIndexedLine (const geom::Geometry * linearGeom)
Constructs an object which allows a linear Geometry to be linearly referenced using length as an index.
Parameters
linearGeom the linear geometry to reference along
Definition at line 38 of file LengthIndexedLine.cpp.
                                                                :
     linearGeom(linearGeom) {}
Member Function Documentation
double geos::linearref::LengthIndexedLine::clampIndex (double index) const
Computes a valid index for this line by clamping the given index to the valid range of index values
Returns
a valid index value
Definition at line 131 of file LengthIndexedLine.cpp.
References getEndIndex(), getStartIndex(), and positiveIndex().
Referenced by extractLine().
 {
   double posIndex = positiveIndex(index);
   double startIndex = getStartIndex();
   if (posIndex < startIndex) return startIndex;
   double endIndex = getEndIndex();
   if (posIndex > endIndex) return endIndex;
   return posIndex;
 }
Geometry * geos::linearref::LengthIndexedLine::extractLine (double startIndex, double endIndex) const
Computes the LineString for the interval on the line between the given indices. If the endIndex lies before the startIndex, the computed geometry is reversed.
Parameters
startIndex the index of the start of the interval
endIndex the index of the end of the interval
Returns
the linear interval between the indices
Definition at line 58 of file LengthIndexedLine.cpp.
References clampIndex(), geos::linearref::ExtractLineByLocation::extract(), linearGeom, and locationOf().
 {
   const LocationIndexedLine lil(linearGeom);
   const double startIndex2 = clampIndex(startIndex);
   const double endIndex2 = clampIndex(endIndex);
   // if extracted line is zero-length, resolve start lower as well to
   // ensure they are equal
   const bool resolveStartLower = ( startIndex2 == endIndex2 );
   const LinearLocation startLoc = locationOf(startIndex2, resolveStartLower);
   const LinearLocation endLoc = locationOf(endIndex2);
 //    LinearLocation endLoc = locationOf(endIndex2, true);
 //    LinearLocation startLoc = locationOf(startIndex2);
   return ExtractLineByLocation::extract(linearGeom, startLoc, endLoc);
 }
Coordinate geos::linearref::LengthIndexedLine::extractPoint (double index) const
Computes the Coordinate for the point on the line at the given index. If the index is out of range the first or last point on the line will be returned. The Z-ordinate of the computed point will be interpolated from the Z-ordinates of the line segment containing it, if they exist.
Parameters
index the index of the desired point
Returns
the Coordinate at the given index
Definition at line 41 of file LengthIndexedLine.cpp.
References geos::linearref::LinearLocation::getCoordinate(), geos::linearref::LengthLocationMap::getLocation(), and linearGeom.
Referenced by GEOSInterpolate_r().
 {
   LinearLocation loc = LengthLocationMap::getLocation(linearGeom, index);
   Coordinate coord = loc.getCoordinate(linearGeom);
   return coord;
 }
Coordinate geos::linearref::LengthIndexedLine::extractPoint (double index, double offsetDistance) const
Computes the Coordinate for the point on the line at the given index, offset by the given distance.
If the index is out of range the first or last point on the line will be returned. The computed point is offset to the left of the line if the offset distance is positive, to the right if negative.
The Z-ordinate of the computed point will be interpolated from the Z-ordinates of the line segment containing it, if they exist.
Parameters
index the index of the desired point
offsetDistance the distance the point is offset from the segment (positive is to the left, negative is to the right)
Returns
the Coordinate at the given index
Definition at line 48 of file LengthIndexedLine.cpp.
References geos::linearref::LengthLocationMap::getLocation(), geos::linearref::LinearLocation::getSegment(), geos::linearref::LinearLocation::getSegmentFraction(), and linearGeom.
 {
   LinearLocation loc = LengthLocationMap::getLocation(linearGeom, index);
   Coordinate ret;
   loc.getSegment(linearGeom)->pointAlongOffset(loc.getSegmentFraction(), offsetDistance, ret);
   return ret;
 }
double geos::linearref::LengthIndexedLine::getEndIndex () const
Returns the index of the end of the line
Returns
the end index
Definition at line 118 of file LengthIndexedLine.cpp.
References geos::geom::Geometry::getLength(), and linearGeom.
Referenced by clampIndex(), and isValidIndex().
 {
   return linearGeom->getLength();
 }
double geos::linearref::LengthIndexedLine::getStartIndex () const
Returns the index of the start of the line
Returns
the start index
Definition at line 113 of file LengthIndexedLine.cpp.
Referenced by clampIndex(), and isValidIndex().
 {
   return 0.0;
 }
double geos::linearref::LengthIndexedLine::indexOf (const geom::Coordinate & pt) const
Computes the minimum index for a point on the line. If the line is not simple (i.e. loops back on itself) a single point may have more than one possible index. In this case, the smallest index is returned.
The supplied point does not necessarily have to lie precisely on the line, but if it is far from the line the accuracy and performance of this function is not guaranteed. Use project to compute a guaranteed result for points which may be far from the line.
Parameters
pt a point on the line
Returns
the minimum index of the point
See also
project
Definition at line 85 of file LengthIndexedLine.cpp.
References geos::linearref::LengthIndexOfPoint::indexOf(), and linearGeom.
 {
   return LengthIndexOfPoint::indexOf(linearGeom, pt);
 }
double geos::linearref::LengthIndexedLine::indexOfAfter (const geom::Coordinate & pt, double minIndex) const
Finds the index for a point on the line which is greater than the given index. If no such index exists, returns minIndex. This method can be used to determine all indexes for a point which occurs more than once on a non-simple line. It can also be used to disambiguate cases where the given point lies slightly off the line and is equidistant from two different points on the line.
The supplied point does not necessarily have to lie precisely on the line, but if it is far from the line the accuracy and performance of this function is not guaranteed. Use project to compute a guaranteed result for points which may be far from the line.
Parameters
pt a point on the line
minIndex the value the returned index must be greater than
Returns
the index of the point greater than the given minimum index
See also
project
Definition at line 91 of file LengthIndexedLine.cpp.
References geos::linearref::LengthIndexOfPoint::indexOfAfter(), and linearGeom.
 {
   return LengthIndexOfPoint::indexOfAfter(linearGeom, pt, minIndex);
 }
double * geos::linearref::LengthIndexedLine::indicesOf (const geom::Geometry * subLine) const
Computes the indices for a subline of the line. (The subline must conform to the line; that is, all vertices in the subline (except possibly the first and last) must be vertices of the line and occcur in the same order).
Parameters
subLine a subLine of the line
Returns
a pair of indices for the start and end of the subline.
Definition at line 97 of file LengthIndexedLine.cpp.
References geos::linearref::LengthLocationMap::getLength(), geos::linearref::LocationIndexOfLine::indicesOf(), and linearGeom.
 {
   LinearLocation* locIndex = LocationIndexOfLine::indicesOf(linearGeom, subLine);
   double* index = new double[2];
   index[0] = LengthLocationMap::getLength(linearGeom, locIndex[0]);
   index[1] = LengthLocationMap::getLength(linearGeom, locIndex[1]);
   delete [] locIndex;
   return index;
 }
bool geos::linearref::LengthIndexedLine::isValidIndex (double index) const
Tests whether an index is in the valid index range for the line.
Parameters
length the index to test
Returns
true if the index is in the valid range
Definition at line 123 of file LengthIndexedLine.cpp.
References getEndIndex(), and getStartIndex().
 {
   return (index >= getStartIndex()
     && index <= getEndIndex());
 }
LinearLocation geos::linearref::LengthIndexedLine::locationOf (double index) const private
Definition at line 73 of file LengthIndexedLine.cpp.
References geos::linearref::LengthLocationMap::getLocation(), and linearGeom.
Referenced by extractLine().
 {
   return LengthLocationMap::getLocation(linearGeom, index);
 }
LinearLocation geos::linearref::LengthIndexedLine::locationOf (double index, bool resolveLower) const private
Definition at line 79 of file LengthIndexedLine.cpp.
References geos::linearref::LengthLocationMap::getLocation(), and linearGeom.
 {
   return LengthLocationMap::getLocation(linearGeom, index, resolveLower);
 }
double geos::linearref::LengthIndexedLine::positiveIndex (double index) const private
Definition at line 145 of file LengthIndexedLine.cpp.
References geos::geom::Geometry::getLength(), and linearGeom.
Referenced by clampIndex().
 {
   if (index >= 0.0) return index;
   return linearGeom->getLength() + index;
 }
double geos::linearref::LengthIndexedLine::project (const geom::Coordinate & pt) const
Computes the index for the closest point on the line to the given point. If more than one point has the closest distance the first one along the line is returned. (The point does not necessarily have to lie precisely on the line.)
Parameters
pt a point on the line
Returns
the index of the point
Definition at line 108 of file LengthIndexedLine.cpp.
References geos::linearref::LengthIndexOfPoint::indexOf(), and linearGeom.
Referenced by GEOSProject_r().
 {
   return LengthIndexOfPoint::indexOf(linearGeom, pt);
 }
Member Data Documentation
const geom::Geometry* geos::linearref::LengthIndexedLine::linearGeom private
Definition at line 48 of file LengthIndexedLine.h.
Referenced by extractLine(), extractPoint(), getEndIndex(), indexOf(), indexOfAfter(), indicesOf(), locationOf(), positiveIndex(), and project().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/linearref/LengthIndexedLine.h
/home/vicky/potree/geos/vicky/src/linearref/LengthIndexedLine.cpp