GEOS: geos::geomgraph::DirectedEdge Class Reference
geos::geomgraph::DirectedEdge Class Reference
A directed EdgeEnd.
#include <DirectedEdge.h>
Public Member Functions
DirectedEdge (Edge *newEdge, bool newIsForward)
void setInResult (bool newIsInResult)
bool isInResult ()
bool isVisited ()
void setVisited (bool newIsVisited)
void setEdgeRing (EdgeRing *newEdgeRing)
EdgeRing * getEdgeRing ()
void setMinEdgeRing (EdgeRing *newMinEdgeRing)
EdgeRing * getMinEdgeRing ()
int getDepth (int position)
void setDepth (int position, int newDepth)
int getDepthDelta () const
void setVisitedEdge (bool newIsVisited)
Marks both DirectedEdges attached to a given Edge.
DirectedEdge * getSym ()
Each Edge gives rise to a pair of symmetric DirectedEdges, in opposite directions.
bool isForward ()
void setSym (DirectedEdge *de)
DirectedEdge * getNext ()
void setNext (DirectedEdge *newNext)
DirectedEdge * getNextMin ()
void setNextMin (DirectedEdge *newNextMin)
bool isLineEdge ()
Tells wheter this edge is a Line.
bool isInteriorAreaEdge ()
Tells wheter this edge is an Area.
void setEdgeDepths (int position, int newDepth)
Set both edge depths.
std::string print () const override
std::string printEdge ()
Edge * getEdge ()
Label & getLabel ()
const Label & getLabel () const
virtual geom::Coordinate & getCoordinate ()
const geom::Coordinate & getCoordinate () const
virtual geom::Coordinate & getDirectedCoordinate ()
virtual int getQuadrant ()
virtual double getDx ()
virtual double getDy ()
virtual void setNode (Node *newNode)
virtual Node * getNode ()
virtual int compareTo (const EdgeEnd *e) const
virtual int compareDirection (const EdgeEnd *e) const
virtual void computeLabel (const algorithm::BoundaryNodeRule &bnr)
Static Public Member Functions
static int depthFactor (int currLocation, int nextLocation)
Computes the factor for the change in depth when moving from one location to another. E.g. if crossing from the INTERIOR to the EXTERIOR the depth decreases, so the factor is -1.
Protected Member Functions
virtual void init (const geom::Coordinate &newP0, const geom::Coordinate &newP1)
Protected Attributes
bool isForwardVar
Edge * edge
Label label
Private Member Functions
void computeDirectedLabel ()
Compute the label in the appropriate orientation for this DirEdge.
Private Attributes
bool isInResultVar
bool isVisitedVar
DirectedEdge * sym
the symmetric edge
DirectedEdge * next
the next edge in the edge ring for the polygon containing this edge
DirectedEdge * nextMin
the next edge in the MinimalEdgeRing that contains this edge
EdgeRing * edgeRing
the EdgeRing that this edge is part of
EdgeRing * minEdgeRing
the MinimalEdgeRing that this edge is part of
int depth [3]
The depth of each side (position) of this edge. The 0 element of the array is never used.
Detailed Description
A directed EdgeEnd.
Definition at line 44 of file DirectedEdge.h.
Constructor & Destructor Documentation
geos::geomgraph::DirectedEdge::DirectedEdge (Edge * newEdge, bool newIsForward)
Definition at line 74 of file DirectedEdge.cpp.
References computeDirectedLabel(), depth, geos::geomgraph::EdgeEnd::edge, geos::geomgraph::Edge::getCoordinate(), geos::geomgraph::Edge::getNumPoints(), geos::geomgraph::EdgeEnd::init(), and isForwardVar.
                                                           :
   EdgeEnd(newEdge),
   isForwardVar(newIsForward),
   isInResultVar(false),
   isVisitedVar(false),
   sym(nullptr),
   next(nullptr),
   nextMin(nullptr),
   edgeRing(nullptr),
   minEdgeRing(nullptr)
 {
   depth[0]=0;
   depth[1]=-999;
   depth[2]=-999;
   assert(newEdge);
   assert(newEdge->getNumPoints() >= 2);
   if (isForwardVar) {
     init(edge->getCoordinate(0), edge->getCoordinate(1));
   } else {
     int n=edge->getNumPoints()-1;
     init(edge->getCoordinate(n), edge->getCoordinate(n-1));
   }
   computeDirectedLabel();
 }
Member Function Documentation
int geos::geomgraph::EdgeEnd::compareDirection (const EdgeEnd * e) const virtual inherited
Implements the total order relation:
a has a greater angle with the positive x-axis than b
Using the obvious algorithm of simply computing the angle is not robust, since the angle calculation is obviously susceptible to roundoff. A robust algorithm is:
first compare the quadrant. If the quadrants are different, it it trivial to determine which vector is "greater".
if the vectors lie in the same quadrant, the computeOrientation function can be used to decide the relative orientation of the vectors.
Definition at line 167 of file EdgeEnd.cpp.
References geos::algorithm::CGAlgorithms::computeOrientation(), geos::geomgraph::EdgeEnd::dx, geos::geomgraph::EdgeEnd::dy, geos::geomgraph::EdgeEnd::p0, geos::geomgraph::EdgeEnd::p1, and geos::geomgraph::EdgeEnd::quadrant.
Referenced by geos::geomgraph::EdgeEnd::compareTo().
 {
   assert(e);
   if (dx == e->dx && dy == e->dy)
     return 0;
   // if the rays are in different quadrants,
   // determining the ordering is trivial
   if (quadrant>e->quadrant) return 1;
   if (quadrant<e->quadrant) return -1;
   // vectors are in the same quadrant - check relative
   // orientation of direction vectors
   // this is > e if it is CCW of e
   return CGAlgorithms::computeOrientation(e->p0, e->p1, p1);
 }
int geos::geomgraph::EdgeEnd::compareTo (const EdgeEnd * e) const virtual inherited
Definition at line 160 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::compareDirection().
Referenced by geos::geomgraph::EdgeEndLT::operator()().
 {
   return compareDirection(e);
 }
void geos::geomgraph::DirectedEdge::computeDirectedLabel () private
Compute the label in the appropriate orientation for this DirEdge.
Definition at line 160 of file DirectedEdge.cpp.
References geos::geomgraph::EdgeEnd::edge, geos::geomgraph::Label::flip(), geos::geomgraph::GraphComponent::getLabel(), isForwardVar, and geos::geomgraph::EdgeEnd::label.
Referenced by DirectedEdge().
 {
   label = edge->getLabel();
   if (!isForwardVar)
     label.flip();
 }
void geos::geomgraph::EdgeEnd::computeLabel (const algorithm::BoundaryNodeRule & bnr) virtual inherited
Reimplemented in geos::operation::relate::EdgeEndBundle.
Definition at line 186 of file EdgeEnd.cpp.
Referenced by geos::geomgraph::EdgeEndStar::computeEdgeEndLabels().
 {
   // subclasses should override this if they are using labels
 }
int geos::geomgraph::DirectedEdge::depthFactor (int currLocation, int nextLocation) static
Computes the factor for the change in depth when moving from one location to another. E.g. if crossing from the INTERIOR to the EXTERIOR the depth decreases, so the factor is -1.
Definition at line 47 of file DirectedEdge.cpp.
References geos::geom::Location::EXTERIOR, and geos::geom::Location::INTERIOR.
 {
   if (currLocation==Location::EXTERIOR && nextLocation==Location::INTERIOR)
     return 1;
   else if (currLocation==Location::INTERIOR && nextLocation==Location::EXTERIOR)
     return -1;
   return 0;
 }
Coordinate & geos::geomgraph::EdgeEnd::getCoordinate () virtual inherited
Definition at line 110 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::p0.
Referenced by geos::geomgraph::NodeMap::add(), geos::geomgraph::Node::add(), geos::geomgraph::DirectedEdgeStar::computeDepths(), geos::geomgraph::EdgeEndStar::computeLabelling(), geos::geomgraph::EdgeRing::computePoints(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), geos::operation::buffer::RightmostEdgeFinder::findEdge(), geos::geomgraph::EdgeEndStar::getCoordinate(), geos::operation::valid::ConnectedInteriorTester::hasUnvisitedShellEdge(), geos::geomgraph::Node::Node(), geos::geomgraph::EdgeEndStar::propagateSideLabels(), setDepth(), and geos::geomgraph::Node::testInvariant().
 {
   return p0;
 }
const geom::Coordinate& geos::geomgraph::EdgeEnd::getCoordinate () const inline inherited
Definition at line 95 of file EdgeEnd.h.
 { return p0; }
INLINE int geos::geomgraph::DirectedEdge::getDepth (int position)
Definition at line 57 of file DirectedEdge.inl.
References depth, and INLINE.
Referenced by geos::geomgraph::DirectedEdgeStar::computeDepths(), geos::operation::buffer::BufferSubgraph::copySymDepths(), geos::operation::buffer::BufferSubgraph::findResultEdges(), and geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments().
 { return depth[position]; }
int geos::geomgraph::DirectedEdge::getDepthDelta () const
Definition at line 116 of file DirectedEdge.cpp.
References geos::geomgraph::EdgeEnd::edge, geos::geomgraph::Edge::getDepthDelta(), and isForwardVar.
Referenced by print().
 {
   int depthDelta=edge->getDepthDelta();
   if (!isForwardVar) depthDelta=-depthDelta;
   return depthDelta;
 }
Coordinate & geos::geomgraph::EdgeEnd::getDirectedCoordinate () virtual inherited
Definition at line 117 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::p1.
 {
   return p1;
 }
double geos::geomgraph::EdgeEnd::getDx () virtual inherited
Definition at line 131 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::dx.
 {
   return dx;
 }
double geos::geomgraph::EdgeEnd::getDy () virtual inherited
Definition at line 138 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::dy.
Referenced by geos::geomgraph::DirectedEdgeStar::getRightmostEdge().
 {
   return dy;
 }
Edge* geos::geomgraph::EdgeEnd::getEdge () inline inherited
Definition at line 86 of file EdgeEnd.h.
Referenced by geos::operation::buffer::RightmostEdgeFinder::checkForRightmostCoordinate(), geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::LineBuilder::collectLineEdge(), geos::geomgraph::DirectedEdgeStar::computeLabelling(), geos::geomgraph::EdgeRing::computePoints(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges(), geos::geomgraph::PlanarGraph::findEdgeEnd(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtVertex(), geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments(), geos::operation::buffer::BufferSubgraph::getEnvelope(), geos::operation::buffer::RightmostEdgeFinder::getRightmostSideOfSegment(), geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), geos::geomgraph::Node::isIncidentEdgeInResult(), setEdgeDepths(), and geos::geomgraph::EdgeRing::setInResult().
 { return edge; }
INLINE EdgeRing * geos::geomgraph::DirectedEdge::getEdgeRing ()
Definition at line 48 of file DirectedEdge.inl.
References edgeRing, and INLINE.
Referenced by geos::operation::valid::ConnectedInteriorTester::buildEdgeRings(), geos::operation::overlay::PolygonBuilder::buildMaximalEdgeRings(), geos::geomgraph::EdgeRing::computePoints(), geos::geomgraph::DirectedEdgeStar::getOutgoingDegree(), and geos::geomgraph::DirectedEdgeStar::linkMinimalDirectedEdges().
 { return edgeRing; }
Label& geos::geomgraph::EdgeEnd::getLabel () inline inherited
Definition at line 89 of file EdgeEnd.h.
Referenced by geos::operation::overlay::PolygonBuilder::buildMaximalEdgeRings(), geos::geomgraph::EdgeEndStar::checkAreaLabelsConsistent(), geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::LineBuilder::collectLineEdge(), geos::operation::relate::EdgeEndBundle::computeLabel(), geos::geomgraph::EdgeEndStar::computeLabelling(), geos::operation::relate::EdgeEndBundle::computeLabelOn(), geos::operation::relate::EdgeEndBundle::computeLabelSide(), geos::geomgraph::EdgeRing::computePoints(), geos::operation::overlay::OverlayOp::findResultAreaEdges(), geos::operation::valid::ConnectedInteriorTester::hasUnvisitedShellEdge(), geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges(), geos::geomgraph::DirectedEdgeStar::mergeSymLabels(), geos::geomgraph::EdgeEndStar::propagateSideLabels(), geos::operation::valid::ConnectedInteriorTester::setInteriorEdgesInResult(), geos::geomgraph::DirectedEdgeStar::updateLabelling(), and geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
 { return label; }
const Label& geos::geomgraph::EdgeEnd::getLabel () const inline inherited
Definition at line 91 of file EdgeEnd.h.
 { return label; }
INLINE EdgeRing * geos::geomgraph::DirectedEdge::getMinEdgeRing ()
Definition at line 54 of file DirectedEdge.inl.
References INLINE, and minEdgeRing.
Referenced by geos::operation::overlay::MaximalEdgeRing::buildMinimalRings().
 { return minEdgeRing; }
INLINE DirectedEdge * geos::geomgraph::DirectedEdge::getNext ()
Definition at line 69 of file DirectedEdge.inl.
References INLINE, and next.
Referenced by geos::operation::overlay::MaximalEdgeRing::buildMinimalRings(), geos::operation::overlay::MaximalEdgeRing::getNext(), geos::operation::overlay::MaximalEdgeRing::linkDirectedEdgesForMinimalEdgeRings(), geos::geomgraph::EdgeRing::setInResult(), and geos::operation::valid::ConnectedInteriorTester::visitLinkedDirectedEdges().
 { return next; }
INLINE DirectedEdge * geos::geomgraph::DirectedEdge::getNextMin ()
Definition at line 75 of file DirectedEdge.inl.
References INLINE, and nextMin.
Referenced by geos::operation::overlay::MinimalEdgeRing::getNext().
 { return nextMin; }
Node * geos::geomgraph::EdgeEnd::getNode () virtual inherited
Definition at line 153 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::node.
Referenced by geos::operation::buffer::BufferSubgraph::add(), geos::operation::buffer::BufferSubgraph::computeDepths(), geos::geomgraph::EdgeRing::computeMaxNodeDegree(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode(), and geos::operation::overlay::MaximalEdgeRing::linkDirectedEdgesForMinimalEdgeRings().
 {
   return node;
 }
int geos::geomgraph::EdgeEnd::getQuadrant () virtual inherited
Definition at line 124 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::quadrant.
Referenced by geos::geomgraph::DirectedEdgeStar::getRightmostEdge().
 {
   return quadrant;
 }
INLINE DirectedEdge * geos::geomgraph::DirectedEdge::getSym ()
Each Edge gives rise to a pair of symmetric DirectedEdges, in opposite directions.
Returns
the DirectedEdge for the same Edge but in the opposite direction
Definition at line 60 of file DirectedEdge.inl.
References INLINE, and sym.
Referenced by geos::operation::buffer::BufferSubgraph::add(), geos::operation::overlay::OverlayOp::cancelDuplicateResultEdges(), geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::buffer::BufferSubgraph::computeDepths(), geos::operation::buffer::BufferSubgraph::computeNodeDepth(), geos::operation::buffer::BufferSubgraph::copySymDepths(), geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges(), geos::operation::buffer::RightmostEdgeFinder::findEdge(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode(), geos::geomgraph::DirectedEdgeStar::getResultAreaEdges(), geos::geomgraph::DirectedEdgeStar::linkAllDirectedEdges(), geos::geomgraph::DirectedEdgeStar::linkMinimalDirectedEdges(), geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges(), geos::geomgraph::DirectedEdgeStar::mergeSymLabels(), geos::geomgraph::DirectedEdgeStar::print(), and geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
 { return sym; }
void geos::geomgraph::EdgeEnd::init (const geom::Coordinate & newP0, const geom::Coordinate & newP1) protected virtual inherited
Definition at line 96 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::dx, geos::geomgraph::EdgeEnd::dy, geos::geomgraph::EdgeEnd::p0, geos::geomgraph::EdgeEnd::p1, geos::geomgraph::EdgeEnd::quadrant, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by DirectedEdge(), and geos::geomgraph::EdgeEnd::EdgeEnd().
 {
   p0=newP0;
   p1=newP1;
   dx=p1.x-p0.x;
   dy=p1.y-p0.y;
   quadrant=Quadrant::quadrant(dx,dy);
   // "EdgeEnd with identical endpoints found");
   assert(!(dx == 0 && dy == 0));
 }
INLINE bool geos::geomgraph::DirectedEdge::isForward ()
Definition at line 63 of file DirectedEdge.inl.
References INLINE, and isForwardVar.
Referenced by geos::geomgraph::EdgeRing::computePoints(), geos::operation::buffer::RightmostEdgeFinder::findEdge(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode(), and geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments().
 { return isForwardVar; }
INLINE bool geos::geomgraph::DirectedEdge::isInResult ()
Definition at line 36 of file DirectedEdge.inl.
References INLINE, and isInResultVar.
Referenced by geos::operation::valid::ConnectedInteriorTester::buildEdgeRings(), geos::operation::overlay::PolygonBuilder::buildMaximalEdgeRings(), geos::operation::overlay::OverlayOp::cancelDuplicateResultEdges(), geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges(), geos::geomgraph::DirectedEdgeStar::getOutgoingDegree(), geos::geomgraph::DirectedEdgeStar::getResultAreaEdges(), and geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges().
 { return isInResultVar; }
bool geos::geomgraph::DirectedEdge::isInteriorAreaEdge ()
Tells wheter this edge is an Area.
This is an interior Area edge if
its label is an Area label for both Geometries
and for each Geometry both sides are in the interior.
Returns
true if this is an interior Area edge
Definition at line 145 of file DirectedEdge.cpp.
References geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isArea(), geos::geomgraph::EdgeEnd::label, geos::geomgraph::Position::LEFT, and geos::geomgraph::Position::RIGHT.
Referenced by geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::OverlayOp::findResultAreaEdges(), and geos::operation::buffer::BufferSubgraph::findResultEdges().
 {
   bool isInteriorAreaEdge=true;
   for (int i=0; i<2; i++) {
     if (!(label.isArea(i)
       && label.getLocation(i,Position::LEFT )==Location::INTERIOR
       && label.getLocation(i,Position::RIGHT)==Location::INTERIOR)) {
         isInteriorAreaEdge=false;
     }
   }
   return isInteriorAreaEdge;
 }
bool geos::geomgraph::DirectedEdge::isLineEdge ()
Tells wheter this edge is a Line.
This edge is a line edge if
at least one of the labels is a line label
any labels which are not line labels have all Locations = EXTERIOR
Definition at line 135 of file DirectedEdge.cpp.
References geos::geomgraph::Label::allPositionsEqual(), geos::geomgraph::Label::isArea(), geos::geomgraph::Label::isLine(), and geos::geomgraph::EdgeEnd::label.
Referenced by geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::LineBuilder::collectLineEdge(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), and geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges().
 {
   bool isLine = label.isLine(0) || label.isLine(1);
   bool isExteriorIfArea0=!label.isArea(0) || label.allPositionsEqual(0,Location::EXTERIOR);
   bool isExteriorIfArea1=!label.isArea(1) || label.allPositionsEqual(1,Location::EXTERIOR);
   return isLine && isExteriorIfArea0 && isExteriorIfArea1;
 }
INLINE bool geos::geomgraph::DirectedEdge::isVisited ()
Definition at line 39 of file DirectedEdge.inl.
References INLINE, and isVisitedVar.
Referenced by geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::LineBuilder::collectLineEdge(), geos::operation::buffer::BufferSubgraph::computeDepths(), geos::operation::buffer::BufferSubgraph::computeNodeDepth(), and geos::operation::valid::ConnectedInteriorTester::hasUnvisitedShellEdge().
 { return isVisitedVar; }
std::string geos::geomgraph::DirectedEdge::print () const override virtual
Reimplemented from geos::geomgraph::EdgeEnd.
Definition at line 188 of file DirectedEdge.cpp.
References depth, edgeRing, getDepthDelta(), isInResultVar, geos::geomgraph::Position::LEFT, geos::geomgraph::EdgeEnd::print(), and geos::geomgraph::Position::RIGHT.
Referenced by geos::operation::valid::ConnectedInteriorTester::buildEdgeRings(), and geos::geomgraph::DirectedEdgeStar::print().
 {
   std::stringstream ss;
   ss << EdgeEnd::print();
   ss << " "
      << depth[Position::LEFT]
      << "/"
      << depth[Position::RIGHT]
      << " ("
      << getDepthDelta()
      << ")";
   if (isInResultVar)
   {
     ss << " inResult";
   }
   ss << " EdgeRing: " << edgeRing;
   if ( edgeRing )
   {
     EdgeRing* er = edgeRing;
     ss << " (" << *er << ")";
   }
   return ss.str();
 }
std::string geos::geomgraph::DirectedEdge::printEdge ()
Definition at line 214 of file DirectedEdge.cpp.
References geos::geomgraph::EdgeEnd::edge, isForwardVar, geos::geomgraph::Edge::print(), and geos::geomgraph::Edge::printReverse().
Referenced by geos::operation::overlay::PolygonBuilder::buildMaximalEdgeRings(), and geos::operation::buffer::BufferSubgraph::findResultEdges().
 {
   //std::string out=print();
   std::string out("");
   if (isForwardVar)
     out += edge->print();
   else
     out += edge->printReverse();
   return out;
 }
void geos::geomgraph::DirectedEdge::setDepth (int position, int newDepth)
Definition at line 104 of file DirectedEdge.cpp.
References depth, and geos::geomgraph::EdgeEnd::getCoordinate().
Referenced by geos::operation::buffer::BufferSubgraph::copySymDepths(), and setEdgeDepths().
 {
   if (depth[position]!=-999) {
     if (depth[position]!=newDepth)
       throw util::TopologyException("assigned depths do not match", getCoordinate());
       //Assert.isTrue(depth[position] == depthVal, "assigned depths do not match at " + getCoordinate());
   }
   depth[position]=newDepth;
 }
void geos::geomgraph::DirectedEdge::setEdgeDepths (int position, int newDepth)
Set both edge depths.
One depth for a given side is provided. The other is computed depending on the Location transition and the depthDelta of the edge.
Definition at line 169 of file DirectedEdge.cpp.
References geos::geomgraph::Edge::getDepthDelta(), geos::geomgraph::EdgeEnd::getEdge(), isForwardVar, geos::geomgraph::Position::LEFT, geos::geomgraph::Position::opposite(), and setDepth().
Referenced by geos::operation::buffer::BufferSubgraph::computeDepth(), and geos::geomgraph::DirectedEdgeStar::computeDepths().
 {
   // get the depth transition delta from R to L for this directed Edge
   int depthDelta=getEdge()->getDepthDelta();
   if (!isForwardVar) depthDelta=-depthDelta;
   // if moving from L to R instead of R to L must change sign of delta
   int directionFactor=1;
   if (position==Position::LEFT)
     directionFactor=-1;
   int oppositePos=Position::opposite(position);
   int delta=depthDelta*directionFactor;
   //TESTINGint delta = depthDelta * DirectedEdge.depthFactor(loc, oppositeLoc);
   int oppositeDepth=newDepth+delta;
   setDepth(position,newDepth);
   setDepth(oppositePos,oppositeDepth);
 }
INLINE void geos::geomgraph::DirectedEdge::setEdgeRing (EdgeRing * newEdgeRing)
Definition at line 45 of file DirectedEdge.inl.
References edgeRing, and INLINE.
Referenced by geos::operation::overlay::MaximalEdgeRing::setEdgeRing().
 { edgeRing=er; }
INLINE void geos::geomgraph::DirectedEdge::setInResult (bool newIsInResult)
Definition at line 33 of file DirectedEdge.inl.
References INLINE, and isInResultVar.
Referenced by geos::operation::overlay::OverlayOp::cancelDuplicateResultEdges(), geos::operation::overlay::OverlayOp::findResultAreaEdges(), geos::operation::buffer::BufferSubgraph::findResultEdges(), and geos::operation::valid::ConnectedInteriorTester::setInteriorEdgesInResult().
 { isInResultVar=v; }
INLINE void geos::geomgraph::DirectedEdge::setMinEdgeRing (EdgeRing * newMinEdgeRing)
Definition at line 51 of file DirectedEdge.inl.
References INLINE, and minEdgeRing.
Referenced by geos::operation::overlay::MinimalEdgeRing::setEdgeRing().
 { minEdgeRing=mer; }
INLINE void geos::geomgraph::DirectedEdge::setNext (DirectedEdge * newNext)
Definition at line 72 of file DirectedEdge.inl.
References INLINE, and next.
Referenced by geos::geomgraph::DirectedEdgeStar::linkAllDirectedEdges(), and geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges().
 { next=newNext; }
INLINE void geos::geomgraph::DirectedEdge::setNextMin (DirectedEdge * newNextMin)
Definition at line 78 of file DirectedEdge.inl.
References nextMin.
Referenced by geos::geomgraph::DirectedEdgeStar::linkMinimalDirectedEdges().
 { nextMin=nm; }
void geos::geomgraph::EdgeEnd::setNode (Node * newNode) virtual inherited
Definition at line 145 of file EdgeEnd.cpp.
References geos::geom::Coordinate::equals2D(), geos::geomgraph::Node::getCoordinate(), geos::geomgraph::EdgeEnd::node, and geos::geomgraph::EdgeEnd::p0.
Referenced by geos::geomgraph::Node::add().
 {
   node=newNode;
   assert(node->getCoordinate().equals2D(p0));
 }
INLINE void geos::geomgraph::DirectedEdge::setSym (DirectedEdge * de)
Definition at line 66 of file DirectedEdge.inl.
References INLINE, and sym.
 { sym=de; }
INLINE void geos::geomgraph::DirectedEdge::setVisited (bool newIsVisited)
Definition at line 42 of file DirectedEdge.inl.
References INLINE, and isVisitedVar.
Referenced by geos::operation::buffer::BufferSubgraph::clearVisitedEdges(), geos::operation::buffer::BufferSubgraph::computeDepths(), geos::operation::buffer::BufferSubgraph::computeNodeDepth(), setVisitedEdge(), and geos::operation::valid::ConnectedInteriorTester::visitLinkedDirectedEdges().
 { isVisitedVar=v; }
void geos::geomgraph::DirectedEdge::setVisitedEdge (bool newIsVisited)
Marks both DirectedEdges attached to a given Edge.
This is used for edges corresponding to lines, which will only appear oriented in a single direction in the result.
Definition at line 125 of file DirectedEdge.cpp.
References setVisited(), and sym.
Referenced by geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), and geos::operation::overlay::LineBuilder::collectLineEdge().
 {
   setVisited(newIsVisited);
   assert(sym);
   sym->setVisited(newIsVisited);
 }
Member Data Documentation
int geos::geomgraph::DirectedEdge::depth[3] private
The depth of each side (position) of this edge. The 0 element of the array is never used.
Definition at line 178 of file DirectedEdge.h.
Referenced by DirectedEdge(), getDepth(), print(), and setDepth().
Edge* geos::geomgraph::EdgeEnd::edge protected inherited
Definition at line 135 of file EdgeEnd.h.
Referenced by computeDirectedLabel(), DirectedEdge(), getDepthDelta(), and printEdge().
EdgeRing* geos::geomgraph::DirectedEdge::edgeRing private
the EdgeRing that this edge is part of
Definition at line 169 of file DirectedEdge.h.
Referenced by getEdgeRing(), print(), and setEdgeRing().
bool geos::geomgraph::DirectedEdge::isForwardVar protected
Definition at line 151 of file DirectedEdge.h.
Referenced by computeDirectedLabel(), DirectedEdge(), getDepthDelta(), isForward(), printEdge(), and setEdgeDepths().
bool geos::geomgraph::DirectedEdge::isInResultVar private
Definition at line 155 of file DirectedEdge.h.
Referenced by isInResult(), print(), and setInResult().
bool geos::geomgraph::DirectedEdge::isVisitedVar private
Definition at line 157 of file DirectedEdge.h.
Referenced by isVisited(), and setVisited().
Label geos::geomgraph::EdgeEnd::label protected inherited
Definition at line 137 of file EdgeEnd.h.
Referenced by computeDirectedLabel(), geos::operation::relate::EdgeEndBundle::computeLabel(), geos::operation::relate::EdgeEndBundle::computeLabelOn(), geos::operation::relate::EdgeEndBundle::computeLabelSide(), isInteriorAreaEdge(), isLineEdge(), geos::geomgraph::operator<<(), geos::operation::relate::EdgeEndBundle::print(), and geos::operation::relate::EdgeEndBundle::updateIM().
EdgeRing* geos::geomgraph::DirectedEdge::minEdgeRing private
the MinimalEdgeRing that this edge is part of
Definition at line 172 of file DirectedEdge.h.
Referenced by getMinEdgeRing(), and setMinEdgeRing().
DirectedEdge* geos::geomgraph::DirectedEdge::next private
the next edge in the edge ring for the polygon containing this edge
Definition at line 163 of file DirectedEdge.h.
Referenced by getNext(), and setNext().
DirectedEdge* geos::geomgraph::DirectedEdge::nextMin private
the next edge in the MinimalEdgeRing that contains this edge
Definition at line 166 of file DirectedEdge.h.
Referenced by getNextMin(), and setNextMin().
DirectedEdge* geos::geomgraph::DirectedEdge::sym private
the symmetric edge
Definition at line 160 of file DirectedEdge.h.
Referenced by getSym(), setSym(), and setVisitedEdge().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/DirectedEdge.h
/home/vicky/potree/geos/vicky/src/geomgraph/DirectedEdge.cpp
/home/vicky/potree/geos/vicky/include/geos/geomgraph/DirectedEdge.inl