GEOS: geos::geom::CoordinateArraySequenceFactory Class Reference
geos::geom::CoordinateArraySequenceFactory Class Reference
Creates CoordinateSequences internally represented as an array of Coordinates.
#include <geos.h>
Public Member Functions
CoordinateSequence * create () const override
Returns an empty CoordinateSequence, the dimensions will be autodetected when it is populated.
CoordinateSequence * create (std::vector< Coordinate > *coords, std::size_t dims=0) const override
Returns a CoordinateSequence based on the given array.
CoordinateSequence * create (std::size_t size, std::size_t dimension=0) const override
CoordinateSequence * create (const CoordinateSequence &coordSeq) const override
Creates a CoordinateSequence which is a copy of the given one.
Static Public Member Functions
static const CoordinateSequenceFactory * instance ()
Returns the singleton instance of CoordinateArraySequenceFactory.
Detailed Description
Creates CoordinateSequences internally represented as an array of Coordinates.
Definition at line 43 of file CoordinateArraySequenceFactory.h.
Member Function Documentation
INLINE CoordinateSequence * geos::geom::CoordinateArraySequenceFactory::create () const override virtual
Returns an empty CoordinateSequence, the dimensions will be autodetected when it is populated.
Implements geos::geom::CoordinateSequenceFactory.
Definition at line 26 of file CoordinateArraySequenceFactory.inl.
References INLINE.
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor::visit().
 {
     return new CoordinateArraySequence(
                 reinterpret_cast<std::vector<Coordinate>*>(0), 0);
 }
CoordinateSequence* geos::geom::CoordinateArraySequenceFactory::create (std::vector< Coordinate > * coordinates, std::size_t dimension = 0) const override virtual
Returns a CoordinateSequence based on the given array.
Whether the array is copied or simply referenced is implementation-dependent. For this reason caller does give up ownership of it. Implementations that will not copy it will need take care of deleting it.
This method must handle null arguments by creating an empty sequence.
Parameters
coordinates the coordinates
dimension 0, 2 or 3 with 0 indicating unknown at this time.
Implements geos::geom::CoordinateSequenceFactory.
INLINE CoordinateSequence * geos::geom::CoordinateArraySequenceFactory::create (std::size_t size, std::size_t dimension = 0) const override virtual
See also
CoordinateSequenceFactory::create(std::size_t, int)
Implements geos::geom::CoordinateSequenceFactory.
Definition at line 40 of file CoordinateArraySequenceFactory.inl.
References INLINE.
 {
   return new CoordinateArraySequence(size,dimension);
 }
INLINE CoordinateSequence * geos::geom::CoordinateArraySequenceFactory::create (const CoordinateSequence & coordSeq) const override virtual
Creates a CoordinateSequence which is a copy of the given one.
This method must handle null arguments by creating an empty sequence.
Parameters
coordSeq the coordinate sequence to copy
Implements geos::geom::CoordinateSequenceFactory.
Definition at line 47 of file CoordinateArraySequenceFactory.inl.
 {
   return new CoordinateArraySequence(seq);
 }
const CoordinateSequenceFactory * geos::geom::CoordinateArraySequenceFactory::instance () static
Returns the singleton instance of CoordinateArraySequenceFactory.
Definition at line 29 of file CoordinateArraySequenceFactory.cpp.
References geos::geom::defaultCoordinateSequenceFactory.
Referenced by geos::geom::GeometryFactory::GeometryFactory(), geos::geom::GeometryCollection::getCoordinates(), and geos::geom::GeometryFactory::toGeometry().
 {
   return &defaultCoordinateSequenceFactory;
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/CoordinateArraySequenceFactory.h
/home/vicky/potree/geos/vicky/src/geom/CoordinateArraySequenceFactory.cpp
/home/vicky/potree/geos/vicky/include/geos/geom/CoordinateArraySequenceFactory.inl