GEOS: geos::geom::prep::PreparedPolygon Class Reference
geos::geom::prep::PreparedPolygon Class Reference
A prepared version of Polygon or MultiPolygon geometries.
#include <PreparedPolygon.h>
Public Member Functions
PreparedPolygon (const geom::Geometry *geom)
~PreparedPolygon () override
noding::FastSegmentSetIntersectionFinder * getIntersectionFinder () const
algorithm::locate::PointOnGeometryLocator * getPointLocator () const
bool contains (const geom::Geometry *g) const override
bool containsProperly (const geom::Geometry *g) const override
bool covers (const geom::Geometry *g) const override
bool intersects (const geom::Geometry *g) const override
const geom::Geometry & getGeometry () const override
const Coordinate::ConstVect * getRepresentativePoints () const
bool isAnyTargetComponentInTest (const geom::Geometry *testGeom) const
bool coveredBy (const geom::Geometry *g) const override
bool crosses (const geom::Geometry *g) const override
bool disjoint (const geom::Geometry *g) const override
bool overlaps (const geom::Geometry *g) const override
bool touches (const geom::Geometry *g) const override
bool within (const geom::Geometry *g) const override
std::string toString ()
Protected Member Functions
void setGeometry (const geom::Geometry *geom)
bool envelopesIntersect (const geom::Geometry *g) const
bool envelopeCovers (const geom::Geometry *g) const
Private Attributes
bool isRectangle
noding::FastSegmentSetIntersectionFinder * segIntFinder
algorithm::locate::PointOnGeometryLocator * ptOnGeomLoc
noding::SegmentString::ConstVect segStrings
Detailed Description
A prepared version of Polygon or MultiPolygon geometries.
Author
mbdavis
Definition at line 48 of file PreparedPolygon.h.
Constructor & Destructor Documentation
geos::geom::prep::PreparedPolygon::PreparedPolygon (const geom::Geometry * geom)
Definition at line 41 of file PreparedPolygon.cpp.
References geos::geom::prep::BasicPreparedGeometry::getGeometry(), isRectangle, and geos::geom::Geometry::isRectangle().
     : BasicPreparedGeometry(geom), segIntFinder(nullptr), ptOnGeomLoc(nullptr)
 {
   isRectangle = getGeometry().isRectangle();
 }
geos::geom::prep::PreparedPolygon::~PreparedPolygon () override
Definition at line 47 of file PreparedPolygon.cpp.
References getIntersectionFinder(), ptOnGeomLoc, segIntFinder, and segStrings.
 {
   delete segIntFinder;
   delete ptOnGeomLoc;
   for ( std::size_t i = 0, ni = segStrings.size(); i < ni; i++ )
   {
     delete segStrings[ i ];
   }
 }
Member Function Documentation
bool geos::geom::prep::PreparedPolygon::contains (const geom::Geometry * g) const override virtual
Default implementation.
Reimplemented from geos::geom::prep::BasicPreparedGeometry.
Definition at line 83 of file PreparedPolygon.cpp.
References geos::geom::prep::PreparedPolygonContains::contains(), geos::operation::predicate::RectangleContains::contains(), containsProperly(), geos::geom::prep::BasicPreparedGeometry::envelopeCovers(), geos::geom::prep::BasicPreparedGeometry::getGeometry(), isRectangle, and poly.
Referenced by getPointLocator().
 {
     // short-circuit test
     if ( !envelopeCovers( g) )
     return false;
     // optimization for rectangles
     if ( isRectangle )
     {
         geom::Geometry const& geom = getGeometry();
         geom::Polygon const& poly = dynamic_cast<geom::Polygon const&>(geom);
         return operation::predicate::RectangleContains::contains(poly, *g);
     }
   return PreparedPolygonContains::contains(this, g);
 }
bool geos::geom::prep::PreparedPolygon::containsProperly (const geom::Geometry * g) const override virtual
Default implementation.
Reimplemented from geos::geom::prep::BasicPreparedGeometry.
Definition at line 103 of file PreparedPolygon.cpp.
References geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), covers(), and geos::geom::prep::BasicPreparedGeometry::envelopeCovers().
Referenced by contains().
 {
     // short-circuit test
     if ( !envelopeCovers( g) )
     return false;
   return PreparedPolygonContainsProperly::containsProperly( this, g);
 }
bool geos::geom::prep::BasicPreparedGeometry::coveredBy (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 101 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::coveredBy().
 {
   return baseGeom->coveredBy(g);
 }
bool geos::geom::prep::PreparedPolygon::covers (const geom::Geometry * g) const override virtual
Default implementation.
Reimplemented from geos::geom::prep::BasicPreparedGeometry.
Definition at line 114 of file PreparedPolygon.cpp.
References geos::geom::prep::PreparedPolygonCovers::covers(), geos::geom::prep::BasicPreparedGeometry::envelopeCovers(), intersects(), and isRectangle.
Referenced by containsProperly().
 {
     // short-circuit test
     if ( !envelopeCovers( g) )
     return false;
     // optimization for rectangle arguments
     if ( isRectangle)
     return true;
   return PreparedPolygonCovers::covers( this, g);
 }
bool geos::geom::prep::BasicPreparedGeometry::crosses (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 113 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::crosses().
 {
   return baseGeom->crosses(g);
 }
bool geos::geom::prep::BasicPreparedGeometry::disjoint (const geom::Geometry * g) const override virtual inherited
Standard implementation for all geometries. Supports GeometryCollections as input.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 119 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::intersects().
 {
   return ! intersects(g);
 }
bool geos::geom::prep::BasicPreparedGeometry::envelopeCovers (const geom::Geometry * g) const protected inherited
Determines whether the envelope of this geometry covers the Geometry g.
Parameters
g a Geometry
Returns
true if g is contained in this envelope
Definition at line 47 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, geos::geom::Envelope::covers(), and geos::geom::Geometry::getEnvelopeInternal().
Referenced by contains(), containsProperly(), and covers().
 {
   return baseGeom->getEnvelopeInternal()->covers(g->getEnvelopeInternal());
 }
bool geos::geom::prep::BasicPreparedGeometry::envelopesIntersect (const geom::Geometry * g) const protected inherited
Determines whether a Geometry g interacts with this geometry by testing the geometry envelopes.
Parameters
g a Geometry
Returns
true if the envelopes intersect
Definition at line 41 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, geos::geom::Geometry::getEnvelopeInternal(), and geos::geom::Envelope::intersects().
Referenced by geos::geom::prep::PreparedPoint::intersects(), geos::geom::prep::PreparedLineString::intersects(), and intersects().
 {
   return baseGeom->getEnvelopeInternal()->intersects(g->getEnvelopeInternal());
 }
const geom::Geometry& geos::geom::prep::BasicPreparedGeometry::getGeometry () const inline override virtual inherited
Gets the original Geometry which has been prepared.
Returns
the base geometry
Implements geos::geom::prep::PreparedGeometry.
Definition at line 95 of file BasicPreparedGeometry.h.
Referenced by contains(), geos::geom::prep::PreparedPolygonCovers::fullTopologicalPredicate(), geos::geom::prep::PreparedPolygonContains::fullTopologicalPredicate(), geos::geom::prep::PreparedLineString::getIntersectionFinder(), getIntersectionFinder(), getPointLocator(), intersects(), geos::geom::prep::AbstractPreparedPolygonContains::isProperIntersectionImpliesNotContainedSituation(), and PreparedPolygon().
   {
     return *baseGeom;
   }
noding::FastSegmentSetIntersectionFinder * geos::geom::prep::PreparedPolygon::getIntersectionFinder () const
Definition at line 61 of file PreparedPolygon.cpp.
References geos::noding::SegmentStringUtil::extractSegmentStrings(), geos::geom::prep::BasicPreparedGeometry::getGeometry(), getPointLocator(), segIntFinder, and segStrings.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections(), geos::geom::prep::PreparedPolygonIntersects::intersects(), and ~PreparedPolygon().
 {
   if (! segIntFinder)
   {
     noding::SegmentStringUtil::extractSegmentStrings( &getGeometry(), segStrings );
     segIntFinder = new noding::FastSegmentSetIntersectionFinder( &segStrings );
   }
   return segIntFinder;
 }
algorithm::locate::PointOnGeometryLocator * geos::geom::prep::PreparedPolygon::getPointLocator () const
Definition at line 73 of file PreparedPolygon.cpp.
References contains(), geos::geom::prep::BasicPreparedGeometry::getGeometry(), and ptOnGeomLoc.
Referenced by getIntersectionFinder(), geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTarget(), geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTargetInterior(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTarget(), and geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTargetInterior().
 {
   if (! ptOnGeomLoc)
     ptOnGeomLoc = new algorithm::locate::IndexedPointInAreaLocator( getGeometry() );
   return ptOnGeomLoc;
 }
const Coordinate::ConstVect* geos::geom::prep::BasicPreparedGeometry::getRepresentativePoints () const inline inherited
Gets the list of representative points for this geometry. One vertex is included for every component of the geometry (i.e. including one for every ring of polygonal geometries)
Returns
a List of Coordinate
Definition at line 107 of file BasicPreparedGeometry.h.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), and geos::geom::prep::PreparedPolygonIntersects::intersects().
   {
     return &representativePts;
   }
bool geos::geom::prep::PreparedPolygon::intersects (const geom::Geometry * g) const override virtual
Default implementation.
Reimplemented from geos::geom::prep::BasicPreparedGeometry.
Definition at line 129 of file PreparedPolygon.cpp.
References geos::geom::prep::BasicPreparedGeometry::envelopesIntersect(), geos::geom::prep::BasicPreparedGeometry::getGeometry(), geos::geom::prep::PreparedPolygonIntersects::intersects(), geos::operation::predicate::RectangleIntersects::intersects(), isRectangle, and poly.
Referenced by covers().
 {
     // envelope test
     if ( !envelopesIntersect( g) )
     return false;
     // optimization for rectangles
     if ( isRectangle )
     {
         geom::Geometry const& geom = getGeometry();
         geom::Polygon const& poly = dynamic_cast<geom::Polygon const&>(geom);
         return operation::predicate::RectangleIntersects::intersects(poly, *g);
     }
   return PreparedPolygonIntersects::intersects( this, g);
 }
bool geos::geom::prep::BasicPreparedGeometry::isAnyTargetComponentInTest (const geom::Geometry * testGeom) const inherited
Tests whether any representative of the target geometry intersects the test geometry. This is useful in A/A, A/L, A/P, L/P, and P/P cases.
Parameters
geom the test geometry
repPts the representative points of the target geometry
Returns
true if any component intersects the areal test geometry
Definition at line 66 of file BasicPreparedGeometry.cpp.
References geos::algorithm::PointLocator::intersects(), and geos::geom::prep::BasicPreparedGeometry::representativePts.
Referenced by geos::geom::prep::PreparedPoint::intersects().
 {
   algorithm::PointLocator locator;
   for (size_t i=0, n=representativePts.size(); i<n; i++)
   {
     const geom::Coordinate& c = *(representativePts[i]);
     if ( locator.intersects( c, testGeom) )
     return true;
   }
   return false;
 }
bool geos::geom::prep::BasicPreparedGeometry::overlaps (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 131 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::overlaps().
 {
   return baseGeom->overlaps(g);
 }
void geos::geom::prep::BasicPreparedGeometry::setGeometry (const geom::Geometry * geom) protected inherited
Sets the original Geometry which will be prepared.
Definition at line 34 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), and geos::geom::prep::BasicPreparedGeometry::representativePts.
Referenced by geos::geom::prep::BasicPreparedGeometry::BasicPreparedGeometry().
 {
   baseGeom = geom;
   geom::util::ComponentCoordinateExtracter::getCoordinates(*baseGeom, representativePts);
 }
std::string geos::geom::prep::BasicPreparedGeometry::toString (void) inherited
Definition at line 149 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::toString().
 {
   return baseGeom->toString();
 }
bool geos::geom::prep::BasicPreparedGeometry::touches (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 137 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::touches().
 {
   return baseGeom->touches(g);
 }
bool geos::geom::prep::BasicPreparedGeometry::within (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 143 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::within().
 {
   return baseGeom->within(g);
 }
Member Data Documentation
bool geos::geom::prep::PreparedPolygon::isRectangle private
Definition at line 51 of file PreparedPolygon.h.
Referenced by contains(), covers(), intersects(), and PreparedPolygon().
algorithm::locate::PointOnGeometryLocator* geos::geom::prep::PreparedPolygon::ptOnGeomLoc mutable private
Definition at line 53 of file PreparedPolygon.h.
Referenced by getPointLocator(), and ~PreparedPolygon().
noding::FastSegmentSetIntersectionFinder* geos::geom::prep::PreparedPolygon::segIntFinder mutable private
Definition at line 52 of file PreparedPolygon.h.
Referenced by getIntersectionFinder(), and ~PreparedPolygon().
noding::SegmentString::ConstVect geos::geom::prep::PreparedPolygon::segStrings mutable private
Definition at line 54 of file PreparedPolygon.h.
Referenced by getIntersectionFinder(), and ~PreparedPolygon().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/prep/PreparedPolygon.h
/home/vicky/potree/geos/vicky/src/geom/prep/PreparedPolygon.cpp