GEOS: geos::geom::IntersectionMatrix Class Reference
geos::geom::IntersectionMatrix Class Reference
Implementation of Dimensionally Extended Nine-Intersection Model (DE-9IM) matrix.
#include <IntersectionMatrix.h>
Public Member Functions
IntersectionMatrix ()
Default constructor.
IntersectionMatrix (const std::string &elements)
Overriden constructor.
IntersectionMatrix (const IntersectionMatrix &other)
Copy constructor.
bool matches (const std::string &requiredDimensionSymbols) const
Returns whether the elements of this IntersectionMatrix satisfies the required dimension symbols.
void add (IntersectionMatrix *other)
Adds one matrix to another.
void set (int row, int column, int dimensionValue)
Changes the value of one of this IntersectionMatrixs elements.
void set (const std::string &dimensionSymbols)
Changes the elements of this IntersectionMatrix to the dimension symbols in dimensionSymbols.
void setAtLeast (int row, int column, int minimumDimensionValue)
Changes the specified element to minimumDimensionValue if the element is less.
void setAtLeastIfValid (int row, int column, int minimumDimensionValue)
If row >= 0 and column >= 0, changes the specified element to minimumDimensionValue if the element is less. Does nothing if row <0 or column < 0.
void setAtLeast (std::string minimumDimensionSymbols)
For each element in this IntersectionMatrix, changes the element to the corresponding minimum dimension symbol if the element is less.
void setAll (int dimensionValue)
Changes the elements of this IntersectionMatrix to dimensionValue.
int get (int row, int column) const
Returns the value of one of this IntersectionMatrixs elements.
bool isDisjoint () const
Returns true if this IntersectionMatrix is FF*FF****.
bool isIntersects () const
Returns true if isDisjoint returns false.
bool isTouches (int dimensionOfGeometryA, int dimensionOfGeometryB) const
Returns true if this IntersectionMatrix is FT*******, F**T***** or F***T****.
bool isCrosses (int dimensionOfGeometryA, int dimensionOfGeometryB) const
Returns true if this IntersectionMatrix is:
bool isWithin () const
Returns true if this IntersectionMatrix is T*F**F***.
bool isContains () const
Returns true if this IntersectionMatrix is T*****FF*.
bool isEquals (int dimensionOfGeometryA, int dimensionOfGeometryB) const
Returns true if this IntersectionMatrix is T*F**FFF*.
bool isOverlaps (int dimensionOfGeometryA, int dimensionOfGeometryB) const
Returns true if this IntersectionMatrix is:
bool isCovers () const
Returns true if this IntersectionMatrix is T*****FF* or *T****FF* or ***T**FF* or ****T*FF*
bool isCoveredBy () const
Returns true if this IntersectionMatrix is T*F**F*** *TF**F*** or **FT*F*** or **F*TF***
IntersectionMatrix * transpose ()
Transposes this IntersectionMatrix.
std::string toString () const
Returns a nine-character String representation of this IntersectionMatrix.
Static Public Member Functions
static bool matches (int actualDimensionValue, char requiredDimensionSymbol)
Tests if given dimension value satisfies the dimension symbol.
static bool matches (const std::string &actualDimensionSymbols, const std::string &requiredDimensionSymbols)
Returns true if each of the actual dimension symbols satisfies the corresponding required dimension symbol.
Private Attributes
int matrix [3][3]
Static Private Attributes
static const int firstDim = 3
static const int secondDim = 3
Detailed Description
Implementation of Dimensionally Extended Nine-Intersection Model (DE-9IM) matrix.
Dimensionally Extended Nine-Intersection Model (DE-9IM) matrix. This class can used to represent both computed DE-9IM's (like 212FF1FF2) as well as patterns for matching them (like T*T******).
Methods are provided to:
set and query the elements of the matrix in a convenient fashion
convert to and from the standard string representation (specified in SFS Section 2.1.13.2).
test to see if a matrix matches a given pattern string.
For a description of the DE-9IM, see the OpenGIS Simple Features Specification for SQL.
Todo:
Suggestion: add equal and not-equal operator to this class.
Definition at line 51 of file IntersectionMatrix.h.
Constructor & Destructor Documentation
geos::geom::IntersectionMatrix::IntersectionMatrix ()
Default constructor.
Creates an IntersectionMatrix with Dimension::False dimension values ('F').
Definition at line 37 of file IntersectionMatrix.cpp.
 {
   //matrix = new int[3][3];
   setAll(Dimension::False);
 }
geos::geom::IntersectionMatrix::IntersectionMatrix (const std::string & elements)
Overriden constructor.
Creates an IntersectionMatrix with the given dimension symbols.
Parameters
elements - reference to string containing pattern of dimension values for elements.
geos::geom::IntersectionMatrix::IntersectionMatrix (const IntersectionMatrix & other)
Copy constructor.
Creates an IntersectionMatrix with the same elements as other.
Todo:
Add assignment operator to make this class fully copyable.
Definition at line 51 of file IntersectionMatrix.cpp.
References matrix.
 {
   matrix[Location::INTERIOR][Location::INTERIOR] = other.matrix[Location::INTERIOR][Location::INTERIOR];
   matrix[Location::INTERIOR][Location::BOUNDARY] = other.matrix[Location::INTERIOR][Location::BOUNDARY];
   matrix[Location::INTERIOR][Location::EXTERIOR] = other.matrix[Location::INTERIOR][Location::EXTERIOR];
   matrix[Location::BOUNDARY][Location::INTERIOR] = other.matrix[Location::BOUNDARY][Location::INTERIOR];
   matrix[Location::BOUNDARY][Location::BOUNDARY] = other.matrix[Location::BOUNDARY][Location::BOUNDARY];
   matrix[Location::BOUNDARY][Location::EXTERIOR] = other.matrix[Location::BOUNDARY][Location::EXTERIOR];
   matrix[Location::EXTERIOR][Location::INTERIOR] = other.matrix[Location::EXTERIOR][Location::INTERIOR];
   matrix[Location::EXTERIOR][Location::BOUNDARY] = other.matrix[Location::EXTERIOR][Location::BOUNDARY];
   matrix[Location::EXTERIOR][Location::EXTERIOR] = other.matrix[Location::EXTERIOR][Location::EXTERIOR];
 }
Member Function Documentation
void geos::geom::IntersectionMatrix::add (IntersectionMatrix * other)
Adds one matrix to another.
Addition is defined by taking the maximum dimension value of each position in the summand matrices.
Parameters
other - the matrix to add.
Todo:
Why the 'other' matrix is not passed by const-reference?
Definition at line 66 of file IntersectionMatrix.cpp.
References get().
 {
   for(int i = 0; i < firstDim; i++) {
     for(int j = 0; j < secondDim; j++) {
       setAtLeast(i, j, other->get(i, j));
     }
   }
 }
int geos::geom::IntersectionMatrix::get (int row, int column) const
Returns the value of one of this IntersectionMatrixs elements.
Parameters
row - the row of this IntersectionMatrix, indicating the interior, boundary or exterior of the first Geometry.
column - the column of this IntersectionMatrix, indicating the interior, boundary or exterior of the second Geometry.
Returns
the dimension value at the given matrix position.
Definition at line 224 of file IntersectionMatrix.cpp.
Referenced by add().
 {
   assert( row >= 0 && row < firstDim );
   assert( col >= 0 && col < secondDim );
   return matrix[row][col];
 }
bool geos::geom::IntersectionMatrix::isContains () const
Returns true if this IntersectionMatrix is T*****FF*.
Returns
true if the first Geometry contains the second.
Definition at line 315 of file IntersectionMatrix.cpp.
 {
   return matches(matrix[Location::INTERIOR][Location::INTERIOR], 'T') &&
        matrix[Location::EXTERIOR][Location::INTERIOR]==Dimension::False &&
        matrix[Location::EXTERIOR][Location::BOUNDARY]==Dimension::False;
 }
bool geos::geom::IntersectionMatrix::isCoveredBy () const
Returns true if this IntersectionMatrix is T*F**F*** *TF**F*** or **FT*F*** or **F*TF***
Returns
true if the first Geometry is covered by the second
Definition at line 380 of file IntersectionMatrix.cpp.
 {
   bool hasPointInCommon =
     matches(matrix[Location::INTERIOR][Location::INTERIOR], 'T')
     ||
     matches(matrix[Location::INTERIOR][Location::BOUNDARY], 'T')
     ||
     matches(matrix[Location::BOUNDARY][Location::INTERIOR], 'T')
     ||
     matches(matrix[Location::BOUNDARY][Location::BOUNDARY], 'T');
   return
     hasPointInCommon
     &&
     matrix[Location::INTERIOR][Location::EXTERIOR] ==
       Dimension::False
     &&
     matrix[Location::BOUNDARY][Location::EXTERIOR] ==
       Dimension::False;
 }
bool geos::geom::IntersectionMatrix::isCovers () const
Returns true if this IntersectionMatrix is T*****FF* or *T****FF* or ***T**FF* or ****T*FF*
Returns
true if the first Geometry covers the second
Definition at line 358 of file IntersectionMatrix.cpp.
 {
   bool hasPointInCommon =
     matches(matrix[Location::INTERIOR][Location::INTERIOR], 'T')
     ||
     matches(matrix[Location::INTERIOR][Location::BOUNDARY], 'T')
     ||
     matches(matrix[Location::BOUNDARY][Location::INTERIOR], 'T')
     ||
     matches(matrix[Location::BOUNDARY][Location::BOUNDARY], 'T');
   return hasPointInCommon
     &&
     matrix[Location::EXTERIOR][Location::INTERIOR] ==
       Dimension::False
     &&
     matrix[Location::EXTERIOR][Location::BOUNDARY] ==
       Dimension::False;
 }
bool geos::geom::IntersectionMatrix::isCrosses (int dimensionOfGeometryA, int dimensionOfGeometryB) const
Returns true if this IntersectionMatrix is:
T*T****** (for a point and a curve, a point and an area or a line and an area)
0******** (for two curves)
Parameters
dimensionOfGeometryA - he dimension of the first Geometry.
dimensionOfGeometryB - the dimension of the second Geometry.
Returns
true if the two Geometry's related by this IntersectionMatrix cross.
For this function to return true, the Geometrys must be a point and a curve; a point and a surface; two curves; or a curve and a surface.
Definition at line 283 of file IntersectionMatrix.cpp.
 {
   if ((dimensionOfGeometryA==Dimension::P && dimensionOfGeometryB==Dimension::L) ||
     (dimensionOfGeometryA==Dimension::P && dimensionOfGeometryB==Dimension::A) ||
     (dimensionOfGeometryA==Dimension::L && dimensionOfGeometryB==Dimension::A)) {
     return matches(matrix[Location::INTERIOR][Location::INTERIOR], 'T') &&
          matches(matrix[Location::INTERIOR][Location::EXTERIOR], 'T');
   }
   if ((dimensionOfGeometryA==Dimension::L && dimensionOfGeometryB==Dimension::P) ||
     (dimensionOfGeometryA==Dimension::A && dimensionOfGeometryB==Dimension::P) ||
     (dimensionOfGeometryA==Dimension::A && dimensionOfGeometryB==Dimension::L)) {
     return matches(matrix[Location::INTERIOR][Location::INTERIOR], 'T') &&
          matches(matrix[Location::EXTERIOR][Location::INTERIOR], 'T');
   }
   if (dimensionOfGeometryA==Dimension::L && dimensionOfGeometryB==Dimension::L) {
     return matrix[Location::INTERIOR][Location::INTERIOR]==0;
   }
   return false;
 }
bool geos::geom::IntersectionMatrix::isDisjoint () const
Returns true if this IntersectionMatrix is FF*FF****.
Returns
true if the two Geometrys related by this IntersectionMatrix are disjoint.
Definition at line 234 of file IntersectionMatrix.cpp.
 {
   return
     matrix[Location::INTERIOR][Location::INTERIOR]==Dimension::False
     &&
     matrix[Location::INTERIOR][Location::BOUNDARY]==Dimension::False
     &&
     matrix[Location::BOUNDARY][Location::INTERIOR]==Dimension::False
     &&
     matrix[Location::BOUNDARY][Location::BOUNDARY]==Dimension::False;
 }
bool geos::geom::IntersectionMatrix::isEquals (int dimensionOfGeometryA, int dimensionOfGeometryB) const
Returns true if this IntersectionMatrix is T*F**FFF*.
Parameters
dimensionOfGeometryA - he dimension of the first Geometry.
dimensionOfGeometryB - the dimension of the second Geometry.
Returns
true if the two Geometry's related by this IntersectionMatrix are equal; the Geometrys must have the same dimension for this function to return true
Definition at line 324 of file IntersectionMatrix.cpp.
 {
   if (dimensionOfGeometryA != dimensionOfGeometryB) {
     return false;
   }
   return matches(matrix[Location::INTERIOR][Location::INTERIOR], 'T') &&
        matrix[Location::EXTERIOR][Location::INTERIOR]==Dimension::False &&
        matrix[Location::INTERIOR][Location::EXTERIOR]==Dimension::False &&
        matrix[Location::EXTERIOR][Location::BOUNDARY]==Dimension::False &&
        matrix[Location::BOUNDARY][Location::EXTERIOR]==Dimension::False;
 }
bool geos::geom::IntersectionMatrix::isIntersects () const
Returns true if isDisjoint returns false.
Returns
true if the two Geometrys related by this IntersectionMatrix intersect.
Definition at line 248 of file IntersectionMatrix.cpp.
 {
   return !isDisjoint();
 }
bool geos::geom::IntersectionMatrix::isOverlaps (int dimensionOfGeometryA, int dimensionOfGeometryB) const
Returns true if this IntersectionMatrix is:
T*T***T** (for two points or two surfaces)
1*T***T** (for two curves)
Parameters
dimensionOfGeometryA - he dimension of the first Geometry.
dimensionOfGeometryB - the dimension of the second Geometry.
Returns
true if the two Geometry's related by this IntersectionMatrix overlap.
For this function to return true, the Geometrys must be two points, two curves or two surfaces.
Definition at line 339 of file IntersectionMatrix.cpp.
 {
   if ((dimensionOfGeometryA==Dimension::P && dimensionOfGeometryB==Dimension::P) ||
     (dimensionOfGeometryA==Dimension::A && dimensionOfGeometryB==Dimension::A)) {
     return matches(matrix[Location::INTERIOR][Location::INTERIOR], 'T') &&
          matches(matrix[Location::INTERIOR][Location::EXTERIOR], 'T') &&
          matches(matrix[Location::EXTERIOR][Location::INTERIOR],'T');
   }
   if (dimensionOfGeometryA==Dimension::L && dimensionOfGeometryB==Dimension::L) {
     return matrix[Location::INTERIOR][Location::INTERIOR]==1 &&
          matches(matrix[Location::INTERIOR][Location::EXTERIOR], 'T') &&
          matches(matrix[Location::EXTERIOR][Location::INTERIOR], 'T');
   }
   return false;
 }
bool geos::geom::IntersectionMatrix::isTouches (int dimensionOfGeometryA, int dimensionOfGeometryB) const
Returns true if this IntersectionMatrix is FT*******, F**T***** or F***T****.
Parameters
dimensionOfGeometryA - the dimension of the first Geometry.
dimensionOfGeometryB - the dimension of the second Geometry.
Returns
true if the two Geometry's related by this IntersectionMatrix touch, false if both Geometrys are points.
Definition at line 255 of file IntersectionMatrix.cpp.
 {
   if (dimensionOfGeometryA > dimensionOfGeometryB)
   {
     //no need to get transpose because pattern matrix is symmetrical
     return isTouches(dimensionOfGeometryB, dimensionOfGeometryA);
   }
   if ((dimensionOfGeometryA==Dimension::A && dimensionOfGeometryB==Dimension::A)
     ||
     (dimensionOfGeometryA==Dimension::L && dimensionOfGeometryB==Dimension::L)
     ||
     (dimensionOfGeometryA==Dimension::L && dimensionOfGeometryB==Dimension::A)
     ||
     (dimensionOfGeometryA==Dimension::P && dimensionOfGeometryB==Dimension::A)
     ||
     (dimensionOfGeometryA==Dimension::P && dimensionOfGeometryB==Dimension::L))
   {
     return matrix[Location::INTERIOR][Location::INTERIOR]==Dimension::False &&
         (matches(matrix[Location::INTERIOR][Location::BOUNDARY], 'T') ||
          matches(matrix[Location::BOUNDARY][Location::INTERIOR], 'T') ||
          matches(matrix[Location::BOUNDARY][Location::BOUNDARY], 'T'));
   }
   return false;
 }
bool geos::geom::IntersectionMatrix::isWithin () const
Returns true if this IntersectionMatrix is T*F**F***.
Returns
true if the first Geometry is within the second.
Definition at line 306 of file IntersectionMatrix.cpp.
 {
   return matches(matrix[Location::INTERIOR][Location::INTERIOR], 'T') &&
        matrix[Location::INTERIOR][Location::EXTERIOR]==Dimension::False &&
        matrix[Location::BOUNDARY][Location::EXTERIOR]==Dimension::False;
 }
bool geos::geom::IntersectionMatrix::matches (const std::string & requiredDimensionSymbols) const
Returns whether the elements of this IntersectionMatrix satisfies the required dimension symbols.
Parameters
requiredDimensionSymbols - nine dimension symbols with which to compare the elements of this IntersectionMatrix. Possible values are {T, F, * , 0, 1, 2}.
Returns
true if this IntersectionMatrix matches the required dimension symbols.
Referenced by matches().
bool geos::geom::IntersectionMatrix::matches (int actualDimensionValue, char requiredDimensionSymbol) static
Tests if given dimension value satisfies the dimension symbol.
Parameters
actualDimensionValue - valid dimension value stored in the IntersectionMatrix. Possible values are {TRUE, FALSE, DONTCARE, 0, 1, 2}.
requiredDimensionSymbol - a character used in the string representation of an IntersectionMatrix. Possible values are {T, F, * , 0, 1, 2}.
Returns
true if the dimension symbol encompasses the dimension value.
Definition at line 97 of file IntersectionMatrix.cpp.
References matches().
 {
   if (requiredDimensionSymbol=='*') return true;
   if (requiredDimensionSymbol=='T' && (actualDimensionValue >= 0 ||
     actualDimensionValue==Dimension::True))
   {
     return true;
   }
   if (requiredDimensionSymbol=='F' &&
     actualDimensionValue==Dimension::False)
   {
     return true;
   }
   if (requiredDimensionSymbol=='0' &&
     actualDimensionValue==Dimension::P)
   {
     return true;
   }
   if (requiredDimensionSymbol=='1' &&
     actualDimensionValue==Dimension::L)
   {
     return true;
   }
   if (requiredDimensionSymbol=='2' &&
     actualDimensionValue==Dimension::A)
   {
     return true;
   }
   return false;
 }
static bool geos::geom::IntersectionMatrix::matches (const std::string & actualDimensionSymbols, const std::string & requiredDimensionSymbols) static
Returns true if each of the actual dimension symbols satisfies the corresponding required dimension symbol.
Parameters
actualDimensionSymbols - nine dimension symbols to validate. Possible values are {T, F, * , 0, 1, 2}.
requiredDimensionSymbols - nine dimension symbols to validate against. Possible values are {T, F, * , 0, 1, 2}.
Returns
true if each of the required dimension symbols encompass the corresponding actual dimension symbol.
void geos::geom::IntersectionMatrix::set (int row, int column, int dimensionValue)
Changes the value of one of this IntersectionMatrixs elements.
Parameters
row - the row of this IntersectionMatrix, indicating the interior, boundary or exterior of the first Geometry.
column - the column of this IntersectionMatrix, indicating the interior, boundary or exterior of the second Geometry.
dimensionValue - the new value of the element.
Definition at line 149 of file IntersectionMatrix.cpp.
Referenced by geos::operation::relate::RelateComputer::computeDisjointIM().
 {
   assert( row >= 0 && row < firstDim );
   assert( col >= 0 && col < secondDim );
   matrix[row][col] = dimensionValue;
 }
void geos::geom::IntersectionMatrix::set (const std::string & dimensionSymbols)
Changes the elements of this IntersectionMatrix to the dimension symbols in dimensionSymbols.
Parameters
dimensionSymbols - nine dimension symbols to which to set this IntersectionMatrix elements. Possible values are {T, F, * , 0, 1, 2}.
void geos::geom::IntersectionMatrix::setAll (int dimensionValue)
Changes the elements of this IntersectionMatrix to dimensionValue.
Parameters
dimensionValue - the dimension value to which to set this IntersectionMatrix elements. Possible values {TRUE, FALSE, DONTCARE, 0, 1, 2}.
Definition at line 213 of file IntersectionMatrix.cpp.
 {
   for (int ai = 0; ai < firstDim; ai++) {
     for (int bi = 0; bi < secondDim; bi++) {
       matrix[ai][bi] = dimensionValue;
     }
   }
 }
void geos::geom::IntersectionMatrix::setAtLeast (int row, int column, int minimumDimensionValue)
Changes the specified element to minimumDimensionValue if the element is less.
Parameters
row - the row of this IntersectionMatrix, indicating the interior, boundary or exterior of the first Geometry.
column - the column of this IntersectionMatrix, indicating the interior, boundary or exterior of the second Geometry.
minimumDimensionValue - the dimension value with which to compare the element. The order of dimension values from least to greatest is {DONTCARE, TRUE, FALSE, 0, 1, 2}.
Definition at line 173 of file IntersectionMatrix.cpp.
Referenced by geos::operation::relate::RelateComputer::computeProperIntersectionIM().
 {
   assert( row >= 0 && row < firstDim );
   assert( col >= 0 && col < secondDim );
   if (matrix[row][col] < minimumDimensionValue)
   {
     matrix[row][col] = minimumDimensionValue;
   }
 }
void geos::geom::IntersectionMatrix::setAtLeast (std::string minimumDimensionSymbols)
For each element in this IntersectionMatrix, changes the element to the corresponding minimum dimension symbol if the element is less.
Parameters
minimumDimensionSymbols - nine dimension symbols with which to compare the elements of this IntersectionMatrix. The order of dimension values from least to greatest is {DONTCARE, TRUE, FALSE, 0, 1, 2} .
void geos::geom::IntersectionMatrix::setAtLeastIfValid (int row, int column, int minimumDimensionValue)
If row >= 0 and column >= 0, changes the specified element to minimumDimensionValue if the element is less. Does nothing if row <0 or column < 0.
Parameters
row - the row of this IntersectionMatrix, indicating the interior, boundary or exterior of the first Geometry.
column - the column of this IntersectionMatrix, indicating the interior, boundary or exterior of the second Geometry.
minimumDimensionValue - the dimension value with which to compare the element. The order of dimension values from least to greatest is {DONTCARE, TRUE, FALSE, 0, 1, 2}.
Definition at line 186 of file IntersectionMatrix.cpp.
Referenced by geos::operation::relate::RelateNode::computeIM(), and geos::geomgraph::Edge::updateIM().
 {
   assert( row >= 0 && row < firstDim );
   assert( col >= 0 && col < secondDim );
   if (row >= 0 && col >= 0)
   {
     setAtLeast(row, col, minimumDimensionValue);
   }
 }
string geos::geom::IntersectionMatrix::toString (void) const
Returns a nine-character String representation of this IntersectionMatrix.
Returns
the nine dimension symbols of this IntersectionMatrix in row-major order.
Definition at line 419 of file IntersectionMatrix.cpp.
Referenced by geos::geom::operator<<().
 {
   string result("");
   for (int ai = 0; ai < firstDim; ai++) {
     for (int bi = 0; bi < secondDim; bi++) {
       result += Dimension::toDimensionSymbol(matrix[ai][bi]);
     }
   }
   return result;
 }
IntersectionMatrix * geos::geom::IntersectionMatrix::transpose ()
Transposes this IntersectionMatrix.
Returns
this IntersectionMatrix as a convenience.
Todo:
It returns 'this' pointer so why not to return const-pointer?
May be it would be better to return copy of transposed matrix?
Definition at line 403 of file IntersectionMatrix.cpp.
 {
   int temp = matrix[1][0];
   matrix[1][0] = matrix[0][1];
   matrix[0][1] = temp;
   temp = matrix[2][0];
   matrix[2][0] = matrix[0][2];
   matrix[0][2] = temp;
   temp = matrix[2][1];
   matrix[2][1] = matrix[1][2];
   matrix[1][2] = temp;
   return this;
 }
Member Data Documentation
const int geos::geom::IntersectionMatrix::firstDim = 3 static private
Definition at line 366 of file IntersectionMatrix.h.
int geos::geom::IntersectionMatrix::matrix[3][3] private
Definition at line 371 of file IntersectionMatrix.h.
Referenced by IntersectionMatrix().
const int geos::geom::IntersectionMatrix::secondDim = 3 static private
Definition at line 368 of file IntersectionMatrix.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/IntersectionMatrix.h
/home/vicky/potree/geos/vicky/src/geom/IntersectionMatrix.cpp