GEOS: geos::noding::IntersectionAdder Class Reference
geos::noding::IntersectionAdder Class Reference
#include <IntersectionAdder.h>
Public Member Functions
IntersectionAdder (algorithm::LineIntersector &newLi)
algorithm::LineIntersector & getLineIntersector ()
const geom::Coordinate * getProperIntersectionPoint ()
bool hasIntersection ()
bool hasProperIntersection ()
bool hasProperInteriorIntersection ()
bool hasInteriorIntersection ()
void processIntersections (SegmentString *e0, int segIndex0, SegmentString *e1, int segIndex1) override
bool isDone () const override
Static Public Member Functions
static bool isAdjacentSegments (int i1, int i2)
Public Attributes
int numIntersections
int numInteriorIntersections
int numProperIntersections
int numTests
Private Member Functions
bool isTrivialIntersection (const SegmentString *e0, int segIndex0, const SegmentString *e1, int segIndex1)
IntersectionAdder (const IntersectionAdder &other)=delete
IntersectionAdder & operator= (const IntersectionAdder &rhs)=delete
Private Attributes
bool hasIntersectionVar
bool hasProper
bool hasProperInterior
bool hasInterior
const geom::Coordinate * properIntersectionPoint
algorithm::LineIntersector & li
bool isSelfIntersection
Detailed Description
Computes the intersections between two line segments in SegmentString and adds them to each string. The SegmentIntersector is passed to a Noder. The addIntersections method is called whenever the Noder detects that two SegmentStrings might intersect. This class is an example of the Strategy pattern.
Definition at line 58 of file IntersectionAdder.h.
Constructor & Destructor Documentation
geos::noding::IntersectionAdder::IntersectionAdder (const IntersectionAdder & other) private delete
geos::noding::IntersectionAdder::IntersectionAdder (algorithm::LineIntersector & newLi) inline
Definition at line 100 of file IntersectionAdder.h.
     :
     hasIntersectionVar(false),
     hasProper(false),
     hasProperInterior(false),
     hasInterior(false),
     properIntersectionPoint(nullptr),
     li(newLi),
     numIntersections(0),
     numInteriorIntersections(0),
     numProperIntersections(0),
     numTests(0)
   {}
Member Function Documentation
algorithm::LineIntersector& geos::noding::IntersectionAdder::getLineIntersector () inline
Definition at line 114 of file IntersectionAdder.h.
 { return li; }
const geom::Coordinate* geos::noding::IntersectionAdder::getProperIntersectionPoint () inline
Returns
the proper intersection point, or NULL if none was found
Definition at line 120 of file IntersectionAdder.h.
{
     return properIntersectionPoint;
   }
bool geos::noding::IntersectionAdder::hasInteriorIntersection () inline
An interior intersection is an intersection which is in the interior of some segment.
Definition at line 147 of file IntersectionAdder.h.
 { return hasInterior; }
bool geos::noding::IntersectionAdder::hasIntersection () inline
Definition at line 124 of file IntersectionAdder.h.
 { return hasIntersectionVar; }
bool geos::noding::IntersectionAdder::hasProperInteriorIntersection () inline
A proper interior intersection is a proper intersection which is not contained in the set of boundary nodes set for this SegmentIntersector.
Definition at line 141 of file IntersectionAdder.h.
 { return hasProperInterior; }
bool geos::noding::IntersectionAdder::hasProperIntersection () inline
A proper intersection is an intersection which is interior to at least two line segments. Note that a proper intersection is not necessarily in the interior of the entire Geometry, since another edge may have an endpoint equal to the intersection, which according to SFS semantics can result in the point being on the Boundary of the Geometry.
Definition at line 134 of file IntersectionAdder.h.
 { return hasProper; }
static bool geos::noding::IntersectionAdder::isAdjacentSegments (int i1, int i2) inline static
Definition at line 164 of file IntersectionAdder.h.
{
     return std::abs(i1 - i2) == 1;
   }
bool geos::noding::IntersectionAdder::isDone () const inline override virtual
Always process all intersections
Returns
false always
Reimplemented from geos::noding::SegmentIntersector.
Definition at line 173 of file IntersectionAdder.h.
{
     return false;
   }
bool geos::noding::IntersectionAdder::isTrivialIntersection (const SegmentString * e0, int segIndex0, const SegmentString * e1, int segIndex1) private
A trivial intersection is an apparent self-intersection which in fact is simply the point shared by adjacent line segments. Note that closed edges require a special check for the point shared by the beginning and end segments.
Definition at line 32 of file IntersectionAdder.cpp.
References geos::noding::SegmentString::isClosed(), and geos::noding::SegmentString::size().
 {
   if (e0 != e1) return false;
   if (li.getIntersectionNum() != 1) return false;
   if (isAdjacentSegments(segIndex0, segIndex1)) return true;
   if (! e0->isClosed()) return false;
   int maxSegIndex = e0->size() - 1;
   if ( (segIndex0 == 0 && segIndex1 == maxSegIndex)
     ||  (segIndex1 == 0 && segIndex0 == maxSegIndex) )
   {
     return true;
   }
   return false;
 }
IntersectionAdder& geos::noding::IntersectionAdder::operator= (const IntersectionAdder & rhs) private delete
void geos::noding::IntersectionAdder::processIntersections (SegmentString * e0, int segIndex0, SegmentString * e1, int segIndex1) override virtual
This method is called by clients of the SegmentIntersector class to process intersections for two segments of the SegmentStrings being intersected. Note that some clients (such as MonotoneChains) may optimize away this call for segment pairs which they have determined do not intersect (e.g. by an disjoint envelope test).
Implements geos::noding::SegmentIntersector.
Definition at line 55 of file IntersectionAdder.cpp.
References geos::noding::NodedSegmentString::addIntersections(), and geos::noding::SegmentString::getCoordinate().
 {
   // don't bother intersecting a segment with itself
   if (e0 == e1 && segIndex0 == segIndex1) return;
   numTests++;
   const Coordinate& p00 = e0->getCoordinate(segIndex0);
   const Coordinate& p01 = e0->getCoordinate(segIndex0 + 1);
   const Coordinate& p10 = e1->getCoordinate(segIndex1);
   const Coordinate& p11 = e1->getCoordinate(segIndex1 + 1);
   li.computeIntersection(p00, p01, p10, p11);
 //if (li.hasIntersection() && li.isProper()) Debug.println(li);
   // No intersection, nothing to do
   if (! li.hasIntersection()) return;
   //intersectionFound = true;
   numIntersections++;
   if (li.isInteriorIntersection())
   {
     numInteriorIntersections++;
     hasInterior=true;
   }
   // if the segments are adjacent they have at least
   // one trivial intersection,
   // the shared endpoint.  Don't bother adding it if it
   // is the only intersection.
   if (! isTrivialIntersection(e0, segIndex0, e1, segIndex1))
   {
     hasIntersectionVar = true;
     NodedSegmentString* ee0 = dynamic_cast<NodedSegmentString*>(e0);
     NodedSegmentString* ee1 = dynamic_cast<NodedSegmentString*>(e1);
     assert(ee0 && ee1);
     ee0->addIntersections(&li, segIndex0, 0);
     ee1->addIntersections(&li, segIndex1, 1);
     if (li.isProper()) {
       numProperIntersections++;
       //Debug.println(li.toString());
       //Debug.println(li.getIntersection(0));
 //properIntersectionPoint = (Coordinate) li.getIntersection(0).clone();
       hasProper = true;
       hasProperInterior = true;
     }
   }
 }
Member Data Documentation
bool geos::noding::IntersectionAdder::hasInterior private
Definition at line 69 of file IntersectionAdder.h.
bool geos::noding::IntersectionAdder::hasIntersectionVar private
These variables keep track of what types of intersections were found during ALL edges that have been intersected.
Definition at line 66 of file IntersectionAdder.h.
bool geos::noding::IntersectionAdder::hasProper private
Definition at line 67 of file IntersectionAdder.h.
bool geos::noding::IntersectionAdder::hasProperInterior private
Definition at line 68 of file IntersectionAdder.h.
bool geos::noding::IntersectionAdder::isSelfIntersection private
Definition at line 75 of file IntersectionAdder.h.
algorithm::LineIntersector& geos::noding::IntersectionAdder::li private
Definition at line 74 of file IntersectionAdder.h.
int geos::noding::IntersectionAdder::numInteriorIntersections
Definition at line 94 of file IntersectionAdder.h.
Referenced by geos::noding::IteratedNoder::node().
int geos::noding::IntersectionAdder::numIntersections
Definition at line 93 of file IntersectionAdder.h.
int geos::noding::IntersectionAdder::numProperIntersections
Definition at line 95 of file IntersectionAdder.h.
int geos::noding::IntersectionAdder::numTests
Definition at line 98 of file IntersectionAdder.h.
const geom::Coordinate* geos::noding::IntersectionAdder::properIntersectionPoint private
Definition at line 72 of file IntersectionAdder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/IntersectionAdder.h
/home/vicky/potree/geos/vicky/src/noding/IntersectionAdder.cpp