GEOS: geos::precision::PrecisionReducerCoordinateOperation Class Reference
geos::precision::PrecisionReducerCoordinateOperation Class Reference
#include <PrecisionReducerCoordinateOperation.h>
Public Member Functions
PrecisionReducerCoordinateOperation (const geom::PrecisionModel &pm, bool doRemoveCollapsed)
geom::CoordinateSequence * edit (const geom::CoordinateSequence *coordinates, const geom::Geometry *geom) override
Ownership of returned CoordinateSequence to caller.
Geometry * edit (const Geometry *geometry, const GeometryFactory *factory) override
Private Member Functions
PrecisionReducerCoordinateOperation (PrecisionReducerCoordinateOperation const &)
PrecisionReducerCoordinateOperation & operator= (PrecisionReducerCoordinateOperation const &)
Private Attributes
const geom::PrecisionModel & targetPM
bool removeCollapsed
Detailed Description
Definition at line 36 of file PrecisionReducerCoordinateOperation.h.
Constructor & Destructor Documentation
geos::precision::PrecisionReducerCoordinateOperation::PrecisionReducerCoordinateOperation (PrecisionReducerCoordinateOperation const &) private
geos::precision::PrecisionReducerCoordinateOperation::PrecisionReducerCoordinateOperation (const geom::PrecisionModel & pm, bool doRemoveCollapsed) inline
Definition at line 51 of file PrecisionReducerCoordinateOperation.h.
       :
       targetPM(pm),
       removeCollapsed(doRemoveCollapsed)
   {}
Member Function Documentation
Geometry * geos::geom::util::CoordinateOperation::edit (const Geometry * geometry, const GeometryFactory * factory) override virtual inherited
Return a newly created geometry, ownership to caller
Implements geos::geom::util::GeometryEditorOperation.
Definition at line 30 of file CoordinateOperation.cpp.
References geos::geom::Geometry::clone(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createLineString(), geos::geom::GeometryFactory::createPoint(), geos::geom::util::CoordinateOperation::edit(), geos::geom::Geometry::getCoordinates(), and geos::geom::LineString::getCoordinatesRO().
Referenced by geos::geom::util::CoordinateOperation::edit().
 {
     const LinearRing *ring = dynamic_cast<const LinearRing *>(geometry);
     if (ring) {
       const CoordinateSequence *coords = ring->getCoordinatesRO();
       CoordinateSequence *newCoords = edit(coords,geometry);
             // LinearRing instance takes over ownership of newCoords instance
       return factory->createLinearRing(newCoords);
     }
     const LineString *line = dynamic_cast<const LineString *>(geometry);
     if (line) {
       const CoordinateSequence *coords = line->getCoordinatesRO();
       CoordinateSequence *newCoords = edit(coords,geometry);
       return factory->createLineString(newCoords);
     }
     if (typeid(*geometry)==typeid(Point)) {
       CoordinateSequence *coords = geometry->getCoordinates();
       CoordinateSequence *newCoords = edit(coords,geometry);
       delete coords;
       return factory->createPoint(newCoords);
     }
     return geometry->clone();
 }
CoordinateSequence * geos::precision::PrecisionReducerCoordinateOperation::edit (const geom::CoordinateSequence * coordinates, const geom::Geometry * geom) override virtual
Ownership of returned CoordinateSequence to caller.
virtual function
Check to see if the removal of repeated points collapsed the coordinate List to an invalid length for the type of the parent geometry. It is not necessary to check for Point collapses, since the coordinate list can never collapse to less than one point. If the length is invalid, return the full-length coordinate array first computed, or null if collapses are being removed. (This may create an invalid geometry - the client must handle this.)
Implements geos::geom::util::CoordinateOperation.
Definition at line 37 of file PrecisionReducerCoordinateOperation.cpp.
References geos::geom::CoordinateSequenceFactory::create(), geos::geom::CoordinateSequence::getAt(), geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::geom::Geometry::getFactory(), geos::geom::CoordinateSequence::getSize(), and geos::geom::CoordinateSequence::removeRepeatedPoints().
 {
   unsigned int csSize = static_cast<unsigned int>(cs->getSize());
   if ( csSize == 0 ) return nullptr;
   vector<Coordinate> *vc = new vector<Coordinate>(csSize);
   // copy coordinates and reduce
   for (unsigned int i=0; i<csSize; ++i) {
     Coordinate coord=cs->getAt(i);
     targetPM.makePrecise(&coord);
     (*vc)[i] = coord;
   }
   // reducedCoords take ownership of 'vc'
   CoordinateSequence *reducedCoords =
     geom->getFactory()->getCoordinateSequenceFactory()->create(vc);
   // remove repeated points, to simplify returned geometry as
   // much as possible.
   //
   CoordinateSequence *noRepeatedCoords=CoordinateSequence::removeRepeatedPoints(reducedCoords);
   unsigned int minLength = 0;
   if ( dynamic_cast<const LineString*>(geom) ) minLength = 2;
   if ( dynamic_cast<const LinearRing*>(geom) ) minLength = 4;
   CoordinateSequence *collapsedCoords = reducedCoords;
   if ( removeCollapsed )
   {
     delete reducedCoords; reducedCoords=nullptr;
     collapsedCoords=nullptr;
   }
   // return null or orginal length coordinate array
   if ( noRepeatedCoords->getSize() < minLength ) {
     delete noRepeatedCoords;
     return collapsedCoords;
   }
   // ok to return shorter coordinate array
   delete reducedCoords;
   return noRepeatedCoords;
 }
PrecisionReducerCoordinateOperation& geos::precision::PrecisionReducerCoordinateOperation::operator= (PrecisionReducerCoordinateOperation const &) private
Member Data Documentation
bool geos::precision::PrecisionReducerCoordinateOperation::removeCollapsed private
Definition at line 44 of file PrecisionReducerCoordinateOperation.h.
const geom::PrecisionModel& geos::precision::PrecisionReducerCoordinateOperation::targetPM private
Definition at line 42 of file PrecisionReducerCoordinateOperation.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/precision/PrecisionReducerCoordinateOperation.h
/home/vicky/potree/geos/vicky/src/precision/PrecisionReducerCoordinateOperation.cpp