GEOS: geos::geomgraph::index::SegmentIntersector Class Reference
geos::geomgraph::index::SegmentIntersector Class Reference
#include <SegmentIntersector.h>
Public Member Functions
virtual ~SegmentIntersector ()
SegmentIntersector (algorithm::LineIntersector *newLi, bool newIncludeProper, bool newRecordIsolated)
void setBoundaryNodes (std::vector< Node * > *bdyNodes0, std::vector< Node * > *bdyNodes1)
Parameters are externally owned. Make sure they live for the whole lifetime of this object.
geom::Coordinate & getProperIntersectionPoint ()
bool hasIntersection ()
bool hasProperIntersection ()
bool hasProperInteriorIntersection ()
void addIntersections (Edge *e0, int segIndex0, Edge *e1, int segIndex1)
void setIsDoneIfProperInt (bool isDoneWhenProperInt)
bool getIsDone ()
Static Public Member Functions
static bool isAdjacentSegments (int i1, int i2)
Public Attributes
int numTests
Private Member Functions
bool isTrivialIntersection (Edge *e0, int segIndex0, Edge *e1, int segIndex1)
bool isBoundaryPoint (algorithm::LineIntersector *li, std::vector< std::vector< Node * > * > &tstBdyNodes)
bool isBoundaryPoint (algorithm::LineIntersector *li, std::vector< Node * > *tstBdyNodes)
Private Attributes
bool hasIntersectionVar
bool hasProper
bool hasProperInterior
bool isDone
bool isDoneWhenProperInt
geom::Coordinate properIntersectionPoint
algorithm::LineIntersector * li
bool includeProper
bool recordIsolated
int numIntersections
std::vector< std::vector< Node * > * > bdyNodes
Elements are externally owned.
Detailed Description
Definition at line 45 of file SegmentIntersector.h.
Constructor & Destructor Documentation
virtual geos::geomgraph::index::SegmentIntersector::~SegmentIntersector () inline virtual
Definition at line 98 of file SegmentIntersector.h.
 {}
geos::geomgraph::index::SegmentIntersector::SegmentIntersector (algorithm::LineIntersector * newLi, bool newIncludeProper, bool newRecordIsolated) inline
Definition at line 100 of file SegmentIntersector.h.
     :
     hasIntersectionVar(false),
     hasProper(false),
     hasProperInterior(false),
     isDone(false),
     isDoneWhenProperInt(false),
     li(newLi),
     includeProper(newIncludeProper),
     recordIsolated(newRecordIsolated),
     numIntersections(0),
     bdyNodes(2),
     numTests(0)
   {}
Member Function Documentation
void geos::geomgraph::index::SegmentIntersector::addIntersections (Edge * e0, int segIndex0, Edge * e1, int segIndex1)
This method is called by clients of the EdgeIntersector class to test for and add intersections for two segments of the edges being intersected. Note that clients (such as MonotoneChainEdges) may choose not to intersect certain pairs of segments for efficiency reasons.
Definition at line 144 of file SegmentIntersector.cpp.
References geos::geomgraph::Edge::addIntersections(), geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), and geos::geomgraph::Edge::setIsolated().
Referenced by geos::geomgraph::index::SweepLineSegment::computeIntersections(), geos::geomgraph::index::SimpleEdgeSetIntersector::computeIntersects(), and geos::geomgraph::index::MonotoneChainEdge::computeIntersectsForChain().
 {
 #if GEOS_DEBUG
   cerr<<"SegmentIntersector::addIntersections() called"<<endl;
 #endif
 //  if (e0->equals(e1) && segIndex0==segIndex1) return;
   if (e0==e1 && segIndex0==segIndex1) return;
   numTests++;
   const CoordinateSequence* cl0=e0->getCoordinates();
   const Coordinate& p00=cl0->getAt(segIndex0);
   const Coordinate& p01=cl0->getAt(segIndex0+1);
   const CoordinateSequence* cl1=e1->getCoordinates();
   const Coordinate& p10=cl1->getAt(segIndex1);
   const Coordinate& p11=cl1->getAt(segIndex1+1);
   li->computeIntersection(p00,p01,p10,p11);
   /*
    * Always record any non-proper intersections.
    * If includeProper is true, record any proper intersections as well.
    */
   if (li->hasIntersection()) {
     if (recordIsolated) {
       e0->setIsolated(false);
       e1->setIsolated(false);
     }
     //intersectionFound = true;
     numIntersections++;
     // If the segments are adjacent they have at least one trivial
     // intersection, the shared endpoint.
     // Don't bother adding it if it is the
     // only intersection.
     if (!isTrivialIntersection(e0,segIndex0,e1,segIndex1))
     {
 #if GEOS_DEBUG
       cerr<<"SegmentIntersector::addIntersections(): has !TrivialIntersection"<<endl;
 #endif // DEBUG_INTERSECT
       hasIntersectionVar=true;
       if (includeProper || !li->isProper()) {
         //Debug.println(li);
         e0->addIntersections(li,segIndex0,0);
         e1->addIntersections(li,segIndex1,1);
 #if GEOS_DEBUG
         cerr<<"SegmentIntersector::addIntersections(): includeProper || !li->isProper()"<<endl;
 #endif // DEBUG_INTERSECT
       }
       if (li->isProper())
       {
         properIntersectionPoint=li->getIntersection(0);
 #if GEOS_DEBUG
         cerr<<"SegmentIntersector::addIntersections(): properIntersectionPoint: "<<properIntersectionPoint.toString()<<endl;
 #endif // DEBUG_INTERSECT
         hasProper=true;
         if (isDoneWhenProperInt)
         {
           isDone = true;
         }
         if (!isBoundaryPoint(li,bdyNodes))
           hasProperInterior=true;
       }
       //if (li.isCollinear())
       //hasCollinear = true;
     }
   }
 }
bool geos::geomgraph::index::SegmentIntersector::getIsDone ()
Definition at line 83 of file SegmentIntersector.cpp.
Referenced by geos::geomgraph::index::SimpleMCSweepLineIntersector::computeIntersections().
 {
   return isDone;
 }
Coordinate & geos::geomgraph::index::SegmentIntersector::getProperIntersectionPoint ()
Definition at line 65 of file SegmentIntersector.cpp.
 {
   return properIntersectionPoint;
 }
bool geos::geomgraph::index::SegmentIntersector::hasIntersection ()
Definition at line 71 of file SegmentIntersector.cpp.
 {
   return hasIntersectionVar;
 }
bool geos::geomgraph::index::SegmentIntersector::hasProperInteriorIntersection ()
Definition at line 106 of file SegmentIntersector.cpp.
Referenced by geos::operation::relate::RelateComputer::computeProperIntersectionIM().
 {
   return hasProperInterior;
 }
bool geos::geomgraph::index::SegmentIntersector::hasProperIntersection ()
Definition at line 96 of file SegmentIntersector.cpp.
Referenced by geos::operation::relate::RelateComputer::computeProperIntersectionIM().
 {
   return hasProper;
 }
bool geos::geomgraph::index::SegmentIntersector::isAdjacentSegments (int i1, int i2) static
Definition at line 47 of file SegmentIntersector.cpp.
 {
   return abs(i1-i2)==1;
 }
bool geos::geomgraph::index::SegmentIntersector::isBoundaryPoint (algorithm::LineIntersector * li, std::vector< std::vector< Node * > * > & tstBdyNodes) private
Definition at line 230 of file SegmentIntersector.cpp.
 {
   if (isBoundaryPoint(li, tstBdyNodes[0])) return true;
   if (isBoundaryPoint(li, tstBdyNodes[1])) return true;
   return false;
 }
bool geos::geomgraph::index::SegmentIntersector::isBoundaryPoint (algorithm::LineIntersector * li, std::vector< Node * > * tstBdyNodes) private
Definition at line 214 of file SegmentIntersector.cpp.
References geos::geomgraph::Node::getCoordinate(), and geos::algorithm::LineIntersector::isIntersection().
 {
   if ( ! tstBdyNodes ) return false;
   for(vector<Node*>::iterator i=tstBdyNodes->begin();i<tstBdyNodes->end();i++) {
     Node *node=*i;
     const Coordinate& pt=node->getCoordinate();
     if (li->isIntersection(pt)) return true;
   }
   return false;
 }
bool geos::geomgraph::index::SegmentIntersector::isTrivialIntersection (Edge * e0, int segIndex0, Edge * e1, int segIndex1) private
Definition at line 118 of file SegmentIntersector.cpp.
References geos::geomgraph::Edge::getNumPoints(), and geos::geomgraph::Edge::isClosed().
 {
 //  if (e0->equals(e1))
   if (e0==e1) {
     if (li->getIntersectionNum()==1) {
       if (isAdjacentSegments(segIndex0,segIndex1))
         return true;
       if (e0->isClosed()) {
         int maxSegIndex=e0->getNumPoints()-1;
         if ((segIndex0==0 && segIndex1==maxSegIndex)
           || (segIndex1==0 && segIndex0==maxSegIndex)) {
           return true;
         }
       }
     }
   }
   return false;
 }
void geos::geomgraph::index::SegmentIntersector::setBoundaryNodes (std::vector< Node * > * bdyNodes0, std::vector< Node * > * bdyNodes1)
Parameters are externally owned. Make sure they live for the whole lifetime of this object.
Definition at line 53 of file SegmentIntersector.cpp.
Referenced by geos::geomgraph::GeometryGraph::computeEdgeIntersections().
 {
   bdyNodes[0]=bdyNodes0;
   bdyNodes[1]=bdyNodes1;
 }
void geos::geomgraph::index::SegmentIntersector::setIsDoneIfProperInt (bool isDoneWhenProperInt)
Definition at line 77 of file SegmentIntersector.cpp.
Referenced by geos::geomgraph::GeometryGraph::computeSelfNodes().
 {
   isDoneWhenProperInt = idwpi;
 }
Member Data Documentation
std::vector<std::vector<Node*>*> geos::geomgraph::index::SegmentIntersector::bdyNodes private
Elements are externally owned.
Definition at line 79 of file SegmentIntersector.h.
bool geos::geomgraph::index::SegmentIntersector::hasIntersectionVar private
These variables keep track of what types of intersections were found during ALL edges that have been intersected.
Definition at line 53 of file SegmentIntersector.h.
bool geos::geomgraph::index::SegmentIntersector::hasProper private
Definition at line 55 of file SegmentIntersector.h.
bool geos::geomgraph::index::SegmentIntersector::hasProperInterior private
Definition at line 57 of file SegmentIntersector.h.
bool geos::geomgraph::index::SegmentIntersector::includeProper private
Definition at line 68 of file SegmentIntersector.h.
bool geos::geomgraph::index::SegmentIntersector::isDone private
Definition at line 59 of file SegmentIntersector.h.
bool geos::geomgraph::index::SegmentIntersector::isDoneWhenProperInt private
Definition at line 61 of file SegmentIntersector.h.
algorithm::LineIntersector* geos::geomgraph::index::SegmentIntersector::li private
Definition at line 66 of file SegmentIntersector.h.
int geos::geomgraph::index::SegmentIntersector::numIntersections private
Definition at line 76 of file SegmentIntersector.h.
int geos::geomgraph::index::SegmentIntersector::numTests
Definition at line 94 of file SegmentIntersector.h.
Referenced by geos::geomgraph::GeometryGraph::computeSelfNodes().
geom::Coordinate geos::geomgraph::index::SegmentIntersector::properIntersectionPoint private
Definition at line 64 of file SegmentIntersector.h.
bool geos::geomgraph::index::SegmentIntersector::recordIsolated private
Definition at line 70 of file SegmentIntersector.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/index/SegmentIntersector.h
/home/vicky/potree/geos/vicky/src/geomgraph/index/SegmentIntersector.cpp