GEOS: geos::algorithm::ConvexHull Class Reference
geos::algorithm::ConvexHull Class Reference
#include <ConvexHull.h>
Public Member Functions
ConvexHull (const geom::Geometry *newGeometry)
~ConvexHull ()
geom::Geometry * getConvexHull ()
Private Member Functions
void extractCoordinates (const geom::Geometry *geom)
geom::CoordinateSequence * toCoordinateSequence (geom::Coordinate::ConstVect &cv)
void computeOctPts (const geom::Coordinate::ConstVect &src, geom::Coordinate::ConstVect &tgt)
bool computeOctRing (const geom::Coordinate::ConstVect &src, geom::Coordinate::ConstVect &tgt)
void reduce (geom::Coordinate::ConstVect &pts)
void padArray3 (geom::Coordinate::ConstVect &pts)
parameter will be modified
void preSort (geom::Coordinate::ConstVect &pts)
parameter will be modified
int polarCompare (const geom::Coordinate &o, const geom::Coordinate &p, const geom::Coordinate &q)
void grahamScan (const geom::Coordinate::ConstVect &c, geom::Coordinate::ConstVect &ps)
geom::Geometry * lineOrPolygon (const geom::Coordinate::ConstVect &vertices)
void cleanRing (const geom::Coordinate::ConstVect &input, geom::Coordinate::ConstVect &cleaned)
bool isBetween (const geom::Coordinate &c1, const geom::Coordinate &c2, const geom::Coordinate &c3)
Private Attributes
const geom::GeometryFactory * geomFactory
geom::Coordinate::ConstVect inputPts
Detailed Description
Computes the convex hull of a Geometry.
The convex hull is the smallest convex Geometry that contains all the points in the input Geometry.
Uses the Graham Scan algorithm.
Last port: algorithm/ConvexHull.java rev. 1.26 (JTS-1.7)
Definition at line 58 of file ConvexHull.h.
Constructor & Destructor Documentation
INLINE geos::algorithm::ConvexHull::ConvexHull (const geom::Geometry * newGeometry)
Create a new convex hull construction for the input Geometry.
Definition at line 31 of file ConvexHull.inl.
References extractCoordinates(), and INLINE.
   :
   geomFactory(newGeometry->getFactory())
 {
   extractCoordinates(newGeometry);
 }
INLINE geos::algorithm::ConvexHull::~ConvexHull ()
Definition at line 39 of file ConvexHull.inl.
References INLINE.
 {
 }
Member Function Documentation
void geos::algorithm::ConvexHull::cleanRing (const geom::Coordinate::ConstVect & input, geom::Coordinate::ConstVect & cleaned) private
Write in 'cleaned' a version of 'input' with collinear vertexes removed.
Definition at line 489 of file ConvexHull.cpp.
References geos::geom::Coordinate::equals2D().
 {
   size_t npts=original.size();
   const Coordinate *last = original[npts-1];
   //util::Assert::equals(*(original[0]), *last);
   assert(last);
   assert(original[0]->equals2D(*last));
   const Coordinate *prev = nullptr;
   for (size_t i=0; i<npts-1; ++i)
   {
     const Coordinate *curr = original[i];
     const Coordinate *next = original[i+1];
     // skip consecutive equal coordinates
     if (curr->equals2D(*next)) continue;
     if ( prev != nullptr &&  isBetween(*prev, *curr, *next) )
     {
       continue;
     }
     cleaned.push_back(curr);
     prev=curr;
   }
   cleaned.push_back(last);
 }
void geos::algorithm::ConvexHull::computeOctPts (const geom::Coordinate::ConstVect & src, geom::Coordinate::ConstVect & tgt) private
Definition at line 121 of file ConvexHull.cpp.
 {
   // Initialize all slots with first input coordinate
   pts = Coordinate::ConstVect(8, inputPts[0]);
   for (size_t i=1, n=inputPts.size(); i<n; ++i)
   {
     if (inputPts[i]->x < pts[0]->x) {
       pts[0] = inputPts[i];
     }
     if (inputPts[i]->x - inputPts[i]->y < pts[1]->x - pts[1]->y) {
       pts[1] = inputPts[i];
     }
     if (inputPts[i]->y > pts[2]->y) {
       pts[2] = inputPts[i];
     }
     if (inputPts[i]->x + inputPts[i]->y > pts[3]->x + pts[3]->y) {
       pts[3] = inputPts[i];
     }
     if (inputPts[i]->x > pts[4]->x) {
       pts[4] = inputPts[i];
     }
     if (inputPts[i]->x - inputPts[i]->y > pts[5]->x - pts[5]->y) {
       pts[5] = inputPts[i];
     }
     if (inputPts[i]->y < pts[6]->y) {
       pts[6] = inputPts[i];
     }
     if (inputPts[i]->x + inputPts[i]->y < pts[7]->x + pts[7]->y) {
       pts[7] = inputPts[i];
     }
   }
 }
bool geos::algorithm::ConvexHull::computeOctRing (const geom::Coordinate::ConstVect & src, geom::Coordinate::ConstVect & tgt) private
Definition at line 160 of file ConvexHull.cpp.
 {
   computeOctPts(inputPts, dest);
   // Remove consecutive equal Coordinates
   // unique() returns an iterator to the end of the resulting
   // sequence, we erase from there to the end.
   dest.erase( std::unique(dest.begin(),dest.end()), dest.end() );
   // points must all lie in a line
   if ( dest.size() < 3 ) return false;
   // close ring
   dest.push_back(dest[0]);
   return true;
 }
INLINE void geos::algorithm::ConvexHull::extractCoordinates (const geom::Geometry * geom) private
Definition at line 44 of file ConvexHull.inl.
References geos::geom::Geometry::apply_ro(), and inputPts.
Referenced by ConvexHull().
 {
   util::UniqueCoordinateArrayFilter filter(inputPts);
   geom->apply_ro(&filter);
 }
Geometry * geos::algorithm::ConvexHull::getConvexHull ()
Returns a Geometry that represents the convex hull of the input geometry. The returned geometry contains the minimal number of points needed to represent the convex hull. In particular, no more than two consecutive points will be collinear.
Returns
if the convex hull contains 3 or more points, a Polygon; 2 points, a LineString; 1 point, a Point; 0 points, an empty GeometryCollection.
Definition at line 226 of file ConvexHull.cpp.
References GEOS_CHECK_FOR_INTERRUPTS.
Referenced by geos::algorithm::MinimumDiameter::computeMinimumDiameter(), and geos::geom::Geometry::convexHull().
 {
   size_t nInputPts=inputPts.size();
   if (nInputPts==0) // Return an empty geometry
     return geomFactory->createEmptyGeometry();
   if (nInputPts==1) // Return a Point
   {
     // Copy the Coordinate from the ConstVect
     return geomFactory->createPoint(*(inputPts[0]));
   }
   if (nInputPts==2) // Return a LineString
   {
     // Copy all Coordinates from the ConstVect
     CoordinateSequence *cs = toCoordinateSequence(inputPts);
     return geomFactory->createLineString(cs);
   }
   // use heuristic to reduce points, if large
   if (nInputPts > 50 )
   {
     reduce(inputPts);
   }
     GEOS_CHECK_FOR_INTERRUPTS();
   // sort points for Graham scan.
   preSort(inputPts);
     GEOS_CHECK_FOR_INTERRUPTS();
   // Use Graham scan to find convex hull.
   Coordinate::ConstVect cHS;
   grahamScan(inputPts, cHS);
     GEOS_CHECK_FOR_INTERRUPTS();
   return lineOrPolygon(cHS);
 }
void geos::algorithm::ConvexHull::grahamScan (const geom::Coordinate::ConstVect & c, geom::Coordinate::ConstVect & ps) private
Definition at line 294 of file ConvexHull.cpp.
 {
   ps.push_back(c[0]);
   ps.push_back(c[1]);
   ps.push_back(c[2]);
   for(size_t i=3, n=c.size(); i<n; ++i)
   {
     const Coordinate *p = ps.back(); ps.pop_back();
     while (!ps.empty() &&
       CGAlgorithms::computeOrientation(
         *(ps.back()), *p, *(c[i])) > 0)
     {
       p = ps.back(); ps.pop_back();
     }
     ps.push_back(p);
     ps.push_back(c[i]);
   }
   ps.push_back(c[0]);
 }
bool geos::algorithm::ConvexHull::isBetween (const geom::Coordinate & c1, const geom::Coordinate & c2, const geom::Coordinate & c3) private
Returns
whether the three coordinates are collinear and c2 lies between c1 and c3 inclusive
**
Definition at line 419 of file ConvexHull.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   if (CGAlgorithms::computeOrientation(c1, c2, c3)!=0) {
     return false;
   }
   if (c1.x!=c3.x) {
     if (c1.x<=c2.x && c2.x<=c3.x) {
       return true;
     }
     if (c3.x<=c2.x && c2.x<=c1.x) {
       return true;
     }
   }
   if (c1.y!=c3.y) {
     if (c1.y<=c2.y && c2.y<=c3.y) {
       return true;
     }
     if (c3.y<=c2.y && c2.y<=c1.y) {
       return true;
     }
   }
   return false;
 }
Geometry * geos::algorithm::ConvexHull::lineOrPolygon (const geom::Coordinate::ConstVect & vertices) private
Parameters
vertices the vertices of a linear ring, which may or may not be flattened (i.e. vertices collinear)
Returns
a 2-vertex LineString if the vertices are collinear; otherwise, a Polygon with unnecessary (collinear) vertices removed
Definition at line 470 of file ConvexHull.cpp.
 {
   Coordinate::ConstVect cleaned;
   cleanRing(input, cleaned);
   if (cleaned.size()==3) { // shouldn't this be 2 ??
     cleaned.resize(2);
     CoordinateSequence *cl1=toCoordinateSequence(cleaned);
     LineString *ret = geomFactory->createLineString(cl1);
     return ret;
   }
   CoordinateSequence *cl2=toCoordinateSequence(cleaned);
   LinearRing *linearRing=geomFactory->createLinearRing(cl2);
   return geomFactory->createPolygon(linearRing,nullptr);
 }
void geos::algorithm::ConvexHull::padArray3 (geom::Coordinate::ConstVect & pts) private
parameter will be modified
Definition at line 218 of file ConvexHull.cpp.
 {
   for (size_t i = pts.size(); i < 3; ++i) {
     pts.push_back(pts[0]);
   }
 }
int geos::algorithm::ConvexHull::polarCompare (const geom::Coordinate & o, const geom::Coordinate & p, const geom::Coordinate & q) private
Given two points p and q compare them with respect to their radial ordering about point o. First checks radial ordering. If points are collinear, the comparison is based on their distance to the origin.
p < q iff
ang(o-p) < ang(o-q) (e.g. o-p-q is CCW)
or ang(o-p) == ang(o-q) && dist(o,p) < dist(o,q)
Parameters
o the origin
p a point
q another point
Returns
-1, 0 or 1 depending on whether p is less than, equal to or greater than q
void geos::algorithm::ConvexHull::preSort (geom::Coordinate::ConstVect & pts) private
parameter will be modified
Definition at line 271 of file ConvexHull.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   // find the lowest point in the set. If two or more points have
   // the same minimum y coordinate choose the one with the minimum x.
   // This focal point is put in array location pts[0].
   for(size_t i=1, n=pts.size(); i<n; ++i)
   {
     const Coordinate *p0=pts[0]; // this will change
     const Coordinate *pi=pts[i];
     if ( (pi->y<p0->y) || ((pi->y==p0->y) && (pi->x<p0->x)) )
     {
       const Coordinate *t=p0;
       pts[0]=pi;
       pts[i]=t;
     }
   }
   // sort the points radially around the focal point.
     std::sort(pts.begin(), pts.end(), RadiallyLessThen(pts[0]));
 }
void geos::algorithm::ConvexHull::reduce (geom::Coordinate::ConstVect & pts) private
Uses a heuristic to reduce the number of points scanned to compute the hull. The heuristic is to find a polygon guaranteed to be in (or on) the hull, and eliminate all points inside it. A quadrilateral defined by the extremal points in the four orthogonal directions can be used, but even more inclusive is to use an octilateral defined by the points in the 8 cardinal directions.
Note that even if the method used to determine the polygon vertices is not 100% robust, this does not affect the robustness of the convex hull.
To satisfy the requirements of the Graham Scan algorithm, the resulting array has at least 3 entries.
Parameters
pts The vector of const Coordinate pointers to be reduced (to at least 3 elements)
WARNING: the parameter will be modified
Add all unique points not in the interior poly. CGAlgorithms.isPointInRing is not defined for points actually on the ring, but this doesn't matter since the points of the interior polygon are forced to be in the reduced set.
@TIP: there should be a std::algo for this
Definition at line 181 of file ConvexHull.cpp.
 {
   Coordinate::ConstVect polyPts;
   if ( ! computeOctRing(pts, polyPts) ) {
   // unable to compute interior polygon for some reason
     return;
   }
   // add points defining polygon
   Coordinate::ConstSet reducedSet;
   reducedSet.insert(polyPts.begin(), polyPts.end());
   for (size_t i=0, n=pts.size(); i<n; ++i)
   {
     if ( !CGAlgorithms::isPointInRing(*(pts[i]), polyPts) )
     {
       reducedSet.insert(pts[i]);
     }
   }
   inputPts.assign(reducedSet.begin(), reducedSet.end());
   if ( inputPts.size() < 3 ) padArray3(inputPts);
 }
CoordinateSequence * geos::algorithm::ConvexHull::toCoordinateSequence (geom::Coordinate::ConstVect & cv) private
Create a CoordinateSequence from the Coordinate::ConstVect This is needed to construct the geometries. Here coordinate copies happen The returned object is newly allocated !NO EXCEPTION SAFE!
Definition at line 98 of file ConvexHull.cpp.
References geos::geom::CoordinateSequenceFactory::create().
 {
   const CoordinateSequenceFactory *csf =
     geomFactory->getCoordinateSequenceFactory();
   // Create a new Coordinate::Vect for feeding it to
   // the CoordinateSequenceFactory
   Coordinate::Vect *vect=new Coordinate::Vect();
   size_t n=cv.size();
   vect->reserve(n); // avoid multiple reallocs
   for (size_t i=0; i<n; ++i)
   {
     vect->push_back(*(cv[i])); // Coordinate copy
   }
   return csf->create(vect); // takes ownership of the vector
 }
Member Data Documentation
const geom::GeometryFactory* geos::algorithm::ConvexHull::geomFactory private
Definition at line 60 of file ConvexHull.h.
geom::Coordinate::ConstVect geos::algorithm::ConvexHull::inputPts private
Definition at line 61 of file ConvexHull.h.
Referenced by extractCoordinates().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/ConvexHull.h
/home/vicky/potree/geos/vicky/src/algorithm/ConvexHull.cpp
/home/vicky/potree/geos/vicky/include/geos/algorithm/ConvexHull.inl