GEOS: geos::geom::util::ComponentCoordinateExtracter Class Reference
geos::geom::util::ComponentCoordinateExtracter Class Reference
Extracts a single representative Coordinate from each connected component of a Geometry.
#include <ComponentCoordinateExtracter.h>
Public Member Functions
ComponentCoordinateExtracter (std::vector< const Coordinate * > &newComps)
void filter_rw (Geometry *geom) override
void filter_ro (const Geometry *geom) override
Static Public Member Functions
static void getCoordinates (const Geometry &geom, std::vector< const Coordinate * > &ret)
Private Member Functions
ComponentCoordinateExtracter (const ComponentCoordinateExtracter &other)=delete
ComponentCoordinateExtracter & operator= (const ComponentCoordinateExtracter &rhs)=delete
Private Attributes
Coordinate::ConstVect & comps
Detailed Description
Extracts a single representative Coordinate from each connected component of a Geometry.
Version
1.9
Definition at line 38 of file ComponentCoordinateExtracter.h.
Constructor & Destructor Documentation
geos::geom::util::ComponentCoordinateExtracter::ComponentCoordinateExtracter (std::vector< const Coordinate * > & newComps)
Constructs a ComponentCoordinateFilter with a list in which to store Coordinates found.
Definition at line 23 of file ComponentCoordinateExtracter.cpp.
             :
          comps(newComps)
          {}
geos::geom::util::ComponentCoordinateExtracter::ComponentCoordinateExtracter (const ComponentCoordinateExtracter & other) private delete
Member Function Documentation
void geos::geom::util::ComponentCoordinateExtracter::filter_ro (const Geometry * geom) override virtual
Reimplemented from geos::geom::GeometryComponentFilter.
Definition at line 40 of file ComponentCoordinateExtracter.cpp.
References comps, geos::geom::GEOS_LINEARRING, geos::geom::GEOS_LINESTRING, geos::geom::GEOS_POINT, geos::geom::Geometry::getCoordinate(), and geos::geom::Geometry::getGeometryTypeId().
          {
             //if (  typeid( *geom ) == typeid( LineString )
             //  ||  typeid( *geom ) == typeid( Point ) )
             if (  geom->getGeometryTypeId() == geos::geom::GEOS_LINEARRING
                || geom->getGeometryTypeId() == geos::geom::GEOS_LINESTRING
                || geom->getGeometryTypeId() == geos::geom::GEOS_POINT )
                comps.push_back( geom->getCoordinate() );
             //if ( const Coordinate *ls=dynamic_cast<const Coordinate *>(geom) )
             //  comps.push_back(ls);
          }
void geos::geom::util::ComponentCoordinateExtracter::filter_rw (Geometry * geom) override virtual
Performs an operation with or on geom.
Parameters
geom a Geometry to which the filter is applied.
Reimplemented from geos::geom::GeometryComponentFilter.
Definition at line 28 of file ComponentCoordinateExtracter.cpp.
References comps, geos::geom::GEOS_LINEARRING, geos::geom::GEOS_LINESTRING, geos::geom::GEOS_POINT, geos::geom::Geometry::getCoordinate(), and geos::geom::Geometry::getGeometryTypeId().
          {
             if (  geom->getGeometryTypeId() == geos::geom::GEOS_LINEARRING
                || geom->getGeometryTypeId() == geos::geom::GEOS_LINESTRING
                || geom->getGeometryTypeId() == geos::geom::GEOS_POINT )
                comps.push_back( geom->getCoordinate() );
             //if (  typeid( *geom ) == typeid( LineString )
             //  ||  typeid( *geom ) == typeid( Point ) )
             //if ( const Coordinate *ls=dynamic_cast<const Coordinate *>(geom) )
             //  comps.push_back(ls);
          }
void geos::geom::util::ComponentCoordinateExtracter::getCoordinates (const Geometry & geom, std::vector< const Coordinate * > & ret) static
Push the linear components from a single geometry into the provided vector. If more than one geometry is to be processed, it is more efficient to create a single ComponentCoordinateFilter instance and pass it to multiple geometries.
Definition at line 53 of file ComponentCoordinateExtracter.cpp.
References geos::geom::Geometry::apply_ro().
Referenced by geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTarget(), geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTargetInterior(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTarget(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTargetInterior(), and geos::geom::prep::BasicPreparedGeometry::setGeometry().
          {
             ComponentCoordinateExtracter cce(ret);
             geom.apply_ro(&cce);
          }
ComponentCoordinateExtracter& geos::geom::util::ComponentCoordinateExtracter::operator= (const ComponentCoordinateExtracter & rhs) private delete
Member Data Documentation
Coordinate::ConstVect& geos::geom::util::ComponentCoordinateExtracter::comps private
Definition at line 62 of file ComponentCoordinateExtracter.h.
Referenced by filter_ro(), and filter_rw().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/util/ComponentCoordinateExtracter.h
/home/vicky/potree/geos/vicky/src/geom/util/ComponentCoordinateExtracter.cpp