GEOS: geos::precision::CommonBitsRemover Class Reference
geos::precision::CommonBitsRemover Class Reference
Allow computing and removing common mantissa bits from one or more Geometries.
#include <CommonBitsRemover.h>
Public Member Functions
CommonBitsRemover ()
~CommonBitsRemover ()
void add (const geom::Geometry *geom)
geom::Coordinate & getCommonCoordinate ()
geom::Geometry * removeCommonBits (geom::Geometry *geom)
Removes the common coordinate bits from a Geometry. The coordinates of the Geometry are changed.
geom::Geometry * addCommonBits (geom::Geometry *geom)
Adds the common coordinate bits back into a Geometry. The coordinates of the Geometry are changed.
Private Attributes
geom::Coordinate commonCoord
CommonCoordinateFilter * ccFilter
Detailed Description
Allow computing and removing common mantissa bits from one or more Geometries.
Definition at line 40 of file CommonBitsRemover.h.
Constructor & Destructor Documentation
geos::precision::CommonBitsRemover::CommonBitsRemover ()
Definition at line 94 of file CommonBitsRemover.cpp.
 {
   ccFilter=new CommonCoordinateFilter();
 }
geos::precision::CommonBitsRemover::~CommonBitsRemover ()
Definition at line 99 of file CommonBitsRemover.cpp.
 {
   delete ccFilter;
 }
Member Function Documentation
void geos::precision::CommonBitsRemover::add (const geom::Geometry * geom)
Add a geometry to the set of geometries whose common bits are being computed. After this method has executed the common coordinate reflects the common bits of all added geometries.
Parameters
geom a Geometry to test for common bits
Definition at line 113 of file CommonBitsRemover.cpp.
References geos::geom::Geometry::apply_ro().
Referenced by geos::geom::BinaryOp(), and geos::geom::SnapOp().
 {
   geom->apply_ro(ccFilter);
   ccFilter->getCommonCoordinate(commonCoord);
 }
Geometry * geos::precision::CommonBitsRemover::addCommonBits (geom::Geometry * geom)
Adds the common coordinate bits back into a Geometry. The coordinates of the Geometry are changed.
Parameters
geom the Geometry to which to add the common coordinate bits
Returns
the shifted Geometry
Adds the common coordinate bits back into a Geometry. The coordinates of the Geometry are changed.
Parameters
geom the Geometry to which to add the common coordinate bits
Returns
the shifted Geometry
Definition at line 164 of file CommonBitsRemover.cpp.
References geos::geom::Geometry::apply_rw(), and geos::geom::Geometry::geometryChanged().
Referenced by geos::geom::BinaryOp(), and geos::geom::SnapOp().
 {
 #if GEOS_DEBUG
   std::cerr << "CommonBits before add: " << *geom << std::endl;
 #endif
   Translater trans(commonCoord);
   geom->apply_rw(&trans);
   geom->geometryChanged();
 #if GEOS_DEBUG
   std::cerr << "CommonBits added: " << *geom << std::endl;
 #endif
   return geom;
 }
Coordinate & geos::precision::CommonBitsRemover::getCommonCoordinate ()
The common bits of the Coordinates in the supplied Geometries.
Definition at line 123 of file CommonBitsRemover.cpp.
Referenced by geos::geom::SnapOp().
 {
   return commonCoord;
 }
Geometry * geos::precision::CommonBitsRemover::removeCommonBits (geom::Geometry * geom)
Removes the common coordinate bits from a Geometry. The coordinates of the Geometry are changed.
Parameters
geom the Geometry from which to remove the common coordinate bits
Returns
the shifted Geometry
Removes the common coordinate bits from a Geometry. The coordinates of the Geometry are changed.
Parameters
geom the Geometry from which to remove the common coordinate bits
Returns
the shifted Geometry
Definition at line 136 of file CommonBitsRemover.cpp.
References geos::geom::Geometry::apply_rw(), geos::geom::Geometry::geometryChanged(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::geom::BinaryOp(), and geos::geom::SnapOp().
 {
   if (commonCoord.x == 0.0 && commonCoord.y == 0.0)
     return geom;
   Coordinate invCoord(commonCoord);
   invCoord.x = -invCoord.x;
   invCoord.y = -invCoord.y;
   Translater trans(invCoord);
   geom->apply_rw(&trans);
   geom->geometryChanged();
 #if GEOS_DEBUG
   std::cerr << "CommonBits removed: " << *geom << std::endl;
 #endif
   return geom;
 }
Member Data Documentation
CommonCoordinateFilter* geos::precision::CommonBitsRemover::ccFilter private
Definition at line 46 of file CommonBitsRemover.h.
geom::Coordinate geos::precision::CommonBitsRemover::commonCoord private
Definition at line 44 of file CommonBitsRemover.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/precision/CommonBitsRemover.h
/home/vicky/potree/geos/vicky/src/precision/CommonBitsRemover.cpp