GEOS: geos::noding::SegmentIntersectionDetector Class Reference
geos::noding::SegmentIntersectionDetector Class Reference
Detects and records an intersection between two SegmentStrings, if one exists.
#include <SegmentIntersectionDetector.h>
Public Member Functions
SegmentIntersectionDetector (LineIntersector *li)
~SegmentIntersectionDetector () override
void setFindProper (bool findProper)
void setFindAllIntersectionTypes (bool findAllTypes)
bool hasIntersection () const
bool hasProperIntersection () const
bool hasNonProperIntersection () const
const geom::Coordinate * getIntersection () const
const geom::CoordinateSequence * getIntersectionSegments () const
bool isDone () const override
Reports whether the client of this class needs to continue testing all intersections in an arrangement.
void processIntersections (noding::SegmentString *e0, int segIndex0, noding::SegmentString *e1, int segIndex1) override
Private Attributes
LineIntersector * li
bool findProper
bool findAllTypes
bool _hasIntersection
bool _hasProperIntersection
bool _hasNonProperIntersection
const geom::Coordinate * intPt
geom::CoordinateSequence * intSegments
Detailed Description
Detects and records an intersection between two SegmentStrings, if one exists.
This strategy can be configured to search for proper intersections. In this case, the presence of any intersection will still be recorded, but searching will continue until either a proper intersection has been found or no intersections are detected.
Only a single intersection is recorded.
Version
1.7
Definition at line 43 of file SegmentIntersectionDetector.h.
Constructor & Destructor Documentation
geos::noding::SegmentIntersectionDetector::SegmentIntersectionDetector (LineIntersector * li) inline
Definition at line 60 of file SegmentIntersectionDetector.h.
     :
     li( li),
     findProper(false),
     findAllTypes(false),
     _hasIntersection(false),
     _hasProperIntersection(false),
     _hasNonProperIntersection(false),
     intPt( nullptr),
     intSegments( nullptr)
   { }
geos::noding::SegmentIntersectionDetector::~SegmentIntersectionDetector () inline override
Definition at line 72 of file SegmentIntersectionDetector.h.
   {
     //delete intPt;
     delete intSegments;
   }
Member Function Documentation
const geom::Coordinate* geos::noding::SegmentIntersectionDetector::getIntersection () const inline
Gets the computed location of the intersection. Due to round-off, the location may not be exact.
Returns
the coordinate for the intersection location
Definition at line 125 of file SegmentIntersectionDetector.h.
   {
     return intPt;
   }
const geom::CoordinateSequence* geos::noding::SegmentIntersectionDetector::getIntersectionSegments () const inline
Gets the endpoints of the intersecting segments.
Returns
an array of the segment endpoints (p00, p01, p10, p11)
Definition at line 136 of file SegmentIntersectionDetector.h.
   {
     return intSegments;
   }
bool geos::noding::SegmentIntersectionDetector::hasIntersection () const inline
Tests whether an intersection was found.
Returns
true if an intersection was found
Definition at line 94 of file SegmentIntersectionDetector.h.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections(), and geos::noding::FastSegmentSetIntersectionFinder::intersects().
   {
     return _hasIntersection;
   }
bool geos::noding::SegmentIntersectionDetector::hasNonProperIntersection () const inline
Tests whether a non-proper intersection was found.
Returns
true if a non-proper intersection was found
Definition at line 114 of file SegmentIntersectionDetector.h.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections().
   {
     return _hasNonProperIntersection;
   }
bool geos::noding::SegmentIntersectionDetector::hasProperIntersection () const inline
Tests whether a proper intersection was found.
Returns
true if a proper intersection was found
Definition at line 104 of file SegmentIntersectionDetector.h.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections().
   {
     return _hasProperIntersection;
   }
bool geos::noding::SegmentIntersectionDetector::isDone () const inline override virtual
Reports whether the client of this class needs to continue testing all intersections in an arrangement.
Returns
true if there is not need to continue testing segments
The default implementation always return false (process all intersections).
Reimplemented from geos::noding::SegmentIntersector.
Definition at line 141 of file SegmentIntersectionDetector.h.
   {
     // If finding all types, we can stop
     // when both possible types have been found.
     if (findAllTypes)
       return _hasProperIntersection && _hasNonProperIntersection;
     // If searching for a proper intersection, only stop if one is found
     if (findProper)
       return _hasProperIntersection;
     return _hasIntersection;
   }
void geos::noding::SegmentIntersectionDetector::processIntersections (noding::SegmentString * e0, int segIndex0, noding::SegmentString * e1, int segIndex1) override virtual
This method is called by clients of the SegmentIntersector class to process intersections for two segments of the SegmentStrings being intersected. Note that some clients (such as MonotoneChains) may optimize away this call for segment pairs which they have determined do not intersect (e.g. by an disjoint envelope test).
Implements geos::noding::SegmentIntersector.
Definition at line 31 of file SegmentIntersectionDetector.cpp.
References _hasIntersection, _hasNonProperIntersection, _hasProperIntersection, geos::geom::CoordinateSequence::add(), geos::algorithm::LineIntersector::computeIntersection(), findProper, geos::noding::SegmentString::getCoordinates(), geos::algorithm::LineIntersector::getIntersection(), geos::algorithm::LineIntersector::hasIntersection(), intPt, intSegments, geos::algorithm::LineIntersector::isProper(), and li.
 {
   // don't bother intersecting a segment with itself
   if (e0 == e1 && segIndex0 == segIndex1) return;
   const geom::Coordinate & p00 = (*e0->getCoordinates())[ segIndex0 ];
   const geom::Coordinate & p01 = (*e0->getCoordinates())[ segIndex0 + 1 ];
   const geom::Coordinate & p10 = (*e1->getCoordinates())[ segIndex1 ];
   const geom::Coordinate & p11 = (*e1->getCoordinates())[ segIndex1 + 1 ];
   li->computeIntersection( p00, p01, p10, p11);
   if (li->hasIntersection())
   {
     // record intersection info
     _hasIntersection = true;
     bool isProper = li->isProper();
     if (isProper)
       _hasProperIntersection = true;
     else
       _hasNonProperIntersection = true;
     // If this is the kind of intersection we are searching for
     // OR no location has yet been recorded
     // save the location data
     bool saveLocation = true;
     if (findProper && !isProper)
       saveLocation = false;
     if (!intPt || saveLocation)
     {
       // record intersection location (approximate)
       intPt = &li->getIntersection(0);
       delete intSegments;
       // record intersecting segments
       intSegments = new geom::CoordinateArraySequence();
       intSegments->add( p00, true);
       intSegments->add( p01, true);
       intSegments->add( p10, true);
       intSegments->add( p11, true);
     }
   }
 }
void geos::noding::SegmentIntersectionDetector::setFindAllIntersectionTypes (bool findAllTypes) inline
Definition at line 84 of file SegmentIntersectionDetector.h.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections().
   {
     this->findAllTypes = findAllTypes;
   }
void geos::noding::SegmentIntersectionDetector::setFindProper (bool findProper) inline
Definition at line 79 of file SegmentIntersectionDetector.h.
   {
     this->findProper = findProper;
   }
Member Data Documentation
bool geos::noding::SegmentIntersectionDetector::_hasIntersection private
Definition at line 51 of file SegmentIntersectionDetector.h.
Referenced by processIntersections().
bool geos::noding::SegmentIntersectionDetector::_hasNonProperIntersection private
Definition at line 53 of file SegmentIntersectionDetector.h.
Referenced by processIntersections().
bool geos::noding::SegmentIntersectionDetector::_hasProperIntersection private
Definition at line 52 of file SegmentIntersectionDetector.h.
Referenced by processIntersections().
bool geos::noding::SegmentIntersectionDetector::findAllTypes private
Definition at line 49 of file SegmentIntersectionDetector.h.
bool geos::noding::SegmentIntersectionDetector::findProper private
Definition at line 48 of file SegmentIntersectionDetector.h.
Referenced by processIntersections().
const geom::Coordinate* geos::noding::SegmentIntersectionDetector::intPt private
Definition at line 55 of file SegmentIntersectionDetector.h.
Referenced by processIntersections().
geom::CoordinateSequence* geos::noding::SegmentIntersectionDetector::intSegments private
Definition at line 56 of file SegmentIntersectionDetector.h.
Referenced by processIntersections().
LineIntersector* geos::noding::SegmentIntersectionDetector::li private
Definition at line 46 of file SegmentIntersectionDetector.h.
Referenced by processIntersections().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/SegmentIntersectionDetector.h
/home/vicky/potree/geos/vicky/src/noding/SegmentIntersectionDetector.cpp