GEOS: geos::index::quadtree::Quadtree Class Reference
geos::index::quadtree::Quadtree Class Reference
A Quadtree is a spatial index structure for efficient querying of 2D rectangles. If other kinds of spatial objects need to be indexed they can be represented by their envelopes.
#include <Quadtree.h>
Public Member Functions
Quadtree ()
Constructs a Quadtree with zero items.
~Quadtree () override
int depth ()
Returns the number of levels in the tree.
int size ()
Returns the number of items in the tree.
void insert (const geom::Envelope *itemEnv, void *item) override
Adds a spatial item with an extent specified by the given Envelope to the index.
void query (const geom::Envelope *searchEnv, std::vector< void * > &ret) override
Queries the tree and returns items which may lie in the given search envelope.
void query (const geom::Envelope *searchEnv, ItemVisitor &visitor) override
Queries the tree and visits items which may lie in the given search envelope.
bool remove (const geom::Envelope *itemEnv, void *item) override
std::vector< void * > * queryAll ()
Return a list of all items in the Quadtree.
std::string toString () const
Static Public Member Functions
static geom::Envelope * ensureExtent (const geom::Envelope *itemEnv, double minExtent)
Ensure that the envelope for the inserted item has non-zero extents.
Private Member Functions
void collectStats (const geom::Envelope &itemEnv)
Private Attributes
std::vector< geom::Envelope * > newEnvelopes
Root root
double minExtent
Detailed Description
A Quadtree is a spatial index structure for efficient querying of 2D rectangles. If other kinds of spatial objects need to be indexed they can be represented by their envelopes.
The quadtree structure is used to provide a primary filter for range rectangle queries. The query() method returns a list of all objects which may intersect the query rectangle. Note that it may return objects which do not in fact intersect. A secondary filter is required to test for exact intersection. Of course, this secondary filter may consist of other tests besides intersection, such as testing other kinds of spatial relationships.
This implementation does not require specifying the extent of the inserted items beforehand. It will automatically expand to accomodate any extent of dataset.
This data structure is also known as an MX-CIF quadtree following the usage of Samet and others.
Definition at line 72 of file Quadtree.h.
Constructor & Destructor Documentation
geos::index::quadtree::Quadtree::Quadtree () inline
Constructs a Quadtree with zero items.
Definition at line 110 of file Quadtree.h.
     :
     root(),
     minExtent(1.0)
   {}
geos::index::quadtree::Quadtree::~Quadtree () override
Definition at line 69 of file Quadtree.cpp.
 {
   for (unsigned int i=0; i<newEnvelopes.size(); i++)
     delete newEnvelopes[i];
 }
Member Function Documentation
void geos::index::quadtree::Quadtree::collectStats (const geom::Envelope & itemEnv) private
Definition at line 145 of file Quadtree.cpp.
References geos::geom::Envelope::getHeight(), and geos::geom::Envelope::getWidth().
 {
   double delX = itemEnv.getWidth();
   if (delX < minExtent && delX > 0.0)
     minExtent = delX;
   double delY = itemEnv.getHeight();
   if (delY < minExtent && delY > 0.0)
     minExtent = delY;
 }
int geos::index::quadtree::Quadtree::depth ()
Returns the number of levels in the tree.
Definition at line 77 of file Quadtree.cpp.
 {
   return root.depth();
 }
Envelope * geos::index::quadtree::Quadtree::ensureExtent (const geom::Envelope * itemEnv, double minExtent) static
Ensure that the envelope for the inserted item has non-zero extents.
Use the current minExtent to pad the envelope, if necessary. Can return a new Envelope or the given one (casted to non-const).
Definition at line 43 of file Quadtree.cpp.
References geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), and geos::geom::Envelope::getMinY().
 {
   //The names "ensureExtent" and "minExtent" are misleading -- sounds like
   //this method ensures that the extents are greater than minExtent.
   //Perhaps we should rename them to "ensurePositiveExtent" and "defaultExtent".
   //[Jon Aquino]
   double minx=itemEnv->getMinX();
   double maxx=itemEnv->getMaxX();
   double miny=itemEnv->getMinY();
   double maxy=itemEnv->getMaxY();
   // has a non-zero extent
   if (minx!=maxx && miny!=maxy) return (Envelope *)itemEnv;
   // pad one or both extents
   if (minx==maxx) {
     minx=minx-minExtent/2.0;
     maxx=minx+minExtent/2.0;
   }
   if (miny==maxy) {
     miny=miny-minExtent/2.0;
     maxy=miny+minExtent/2.0;
   }
   Envelope *newEnv = new Envelope(minx, maxx, miny, maxy);
   return newEnv;
 }
void geos::index::quadtree::Quadtree::insert (const geom::Envelope * itemEnv, void * item) override virtual
Adds a spatial item with an extent specified by the given Envelope to the index.
Parameters
itemEnv Envelope of the item, ownership left to caller. TODO: Reference hold by this class ?
item Opaque item, ownership left to caller. Reference hold by this class.
Implements geos::index::SpatialIndex.
Definition at line 91 of file Quadtree.cpp.
References geos::geom::Envelope::toString().
Referenced by geos::operation::valid::QuadtreeNestedRingTester::buildQuadtree().
 {
   collectStats(*itemEnv);
   Envelope *insertEnv=ensureExtent(itemEnv,minExtent);
   if ( insertEnv != itemEnv ) newEnvelopes.push_back(insertEnv);
   root.insert(insertEnv,item);
 #if GEOS_DEBUG
   cerr<<"Quadtree::insert("<<itemEnv->toString()<<", "<<item<<")"<<endl;
   cerr<<"       insertEnv:"<<insertEnv->toString()<<endl;
   cerr<<"       tree:"<<endl<<root.toString()<<endl;
 #endif
 }
void geos::index::quadtree::Quadtree::query (const geom::Envelope * searchEnv, std::vector< void * > & ret) override virtual
Queries the tree and returns items which may lie in the given search envelope.
Precisely, the items that are returned are all items in the tree whose envelope may intersect the search Envelope. Note that some items with non-intersecting envelopes may be returned as well; the client is responsible for filtering these out. In most situations there will be many items in the tree which do not intersect the search envelope and which are not returned - thus providing improved performance over a simple linear scan.
Parameters
searchEnv the envelope of the desired query area.
ret a vector where items which may intersect the search envelope are pushed
Implements geos::index::SpatialIndex.
Definition at line 108 of file Quadtree.cpp.
Referenced by geos::operation::valid::QuadtreeNestedRingTester::isNonNested().
 {
   /*
    * the items that are matched are the items in quads which
    * overlap the search envelope
    */
   root.addAllItemsFromOverlapping(*searchEnv, foundItems);
 #if GEOS_DEBUG
   cerr<<"Quadtree::query returning "<<foundItems.size()
     <<" items over "<<size()
     <<" items in index (of depth: "<<depth()<<")"<<endl;
   cerr<<" Root:\n"<<root.toString()<<endl;
 #endif
 }
void geos::index::quadtree::Quadtree::query (const geom::Envelope * searchEnv, ItemVisitor & visitor) inline override virtual
Queries the tree and visits items which may lie in the given search envelope.
Precisely, the items that are visited are all items in the tree whose envelope may intersect the search Envelope. Note that some items with non-intersecting envelopes may be visited as well; the client is responsible for filtering these out. In most situations there will be many items in the tree which do not intersect the search envelope and which are not visited - thus providing improved performance over a simple linear scan.
Parameters
searchEnv the envelope of the desired query area.
visitor a visitor object which is passed the visited items
Implements geos::index::SpatialIndex.
Definition at line 162 of file Quadtree.h.
References geos::index::quadtree::NodeBase::visit().
   {
     /*
      * the items that are matched are the items in quads which
      * overlap the search envelope
      */
     root.visit(searchEnv, visitor);
   }
vector< void * > * geos::index::quadtree::Quadtree::queryAll ()
Return a list of all items in the Quadtree.
Definition at line 126 of file Quadtree.cpp.
 {
   vector<void*> *foundItems=new vector<void*>();
   root.addAllItems(*foundItems);
   return foundItems;
 }
bool geos::index::quadtree::Quadtree::remove (const geom::Envelope * itemEnv, void * item) override virtual
Removes a single item from the tree.
Parameters
itemEnv the Envelope of the item to be removed
item the item to remove
Returns
true if the item was found (and thus removed)
Implements geos::index::SpatialIndex.
Definition at line 135 of file Quadtree.cpp.
 {
   Envelope* posEnv = ensureExtent(itemEnv, minExtent);
   bool ret = root.remove(posEnv, item);
   if ( posEnv != itemEnv ) delete posEnv;
   return ret;
 }
int geos::index::quadtree::Quadtree::size ()
Returns the number of items in the tree.
Definition at line 84 of file Quadtree.cpp.
 {
   return root.size();
 }
string geos::index::quadtree::Quadtree::toString (void) const
Definition at line 158 of file Quadtree.cpp.
 {
   string ret = root.toString();
   return ret;
 }
Member Data Documentation
double geos::index::quadtree::Quadtree::minExtent private
Statistics
minExtent is the minimum envelope extent of all items inserted into the tree so far. It is used as a heuristic value to construct non-zero envelopes for features with zero X and/or Y extent. Start with a non-zero extent, in case the first feature inserted has a zero extent in both directions. This value may be non-optimal, but only one feature will be inserted with this value.
Definition at line 93 of file Quadtree.h.
std::vector<geom::Envelope *> geos::index::quadtree::Quadtree::newEnvelopes private
Definition at line 76 of file Quadtree.h.
Root geos::index::quadtree::Quadtree::root private
Definition at line 80 of file Quadtree.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/quadtree/Quadtree.h
/home/vicky/potree/geos/vicky/src/index/quadtree/Quadtree.cpp