GEOS: geos::operation::distance::FacetSequence Class Reference
geos::operation::distance::FacetSequence Class Reference
#include <FacetSequence.h>
Public Member Functions
const geom::Envelope * getEnvelope () const
const geom::Coordinate * getCoordinate (size_t index) const
size_t size () const
bool isPoint () const
double distance (const FacetSequence &facetSeq) const
FacetSequence (const geom::CoordinateSequence *pts, size_t start, size_t end)
Private Member Functions
double computeLineLineDistance (const FacetSequence &facetSeq) const
double computePointLineDistance (const geom::Coordinate &pt, const FacetSequence &facetSeq) const
void computeEnvelope ()
Private Attributes
const geom::CoordinateSequence * pts
const size_t start
const size_t end
geom::Envelope env
Detailed Description
Definition at line 29 of file FacetSequence.h.
Constructor & Destructor Documentation
FacetSequence::FacetSequence (const geom::CoordinateSequence * pts, size_t start, size_t end)
Definition at line 26 of file FacetSequence.cpp.
References computeEnvelope().
                                                                                     :
         pts(pts),
         start(start),
         end(end) {
     computeEnvelope();
 }
Member Function Documentation
void FacetSequence::computeEnvelope () private
Definition at line 104 of file FacetSequence.cpp.
References end, env, geos::geom::Envelope::expandToInclude(), geos::geom::CoordinateSequence::getX(), geos::geom::CoordinateSequence::getY(), pts, and start.
Referenced by FacetSequence().
{
     env = Envelope();
     for (size_t i = start; i < end; i++) {
         env.expandToInclude(pts->getX(i), pts->getY(i));
     }
 }
double FacetSequence::computeLineLineDistance (const FacetSequence & facetSeq) const private
Definition at line 80 of file FacetSequence.cpp.
References end, geos::geom::CoordinateSequence::getAt(), pts, and start.
Referenced by distance().
{
     double minDistance = std::numeric_limits<double>::infinity();
     double dist;
     Coordinate p0, p1, q0, q1;
     for (size_t i = start; i < end - 1; i++) {
         pts->getAt(i, p0);
         pts->getAt(i + 1, p1);
         for (size_t j = facetSeq.start; j < facetSeq.end - 1; j++) {
             facetSeq.pts->getAt(j, q0);
             facetSeq.pts->getAt(j + 1, q1);
             dist = CGAlgorithms::distanceLineLine(p0, p1, q0, q1);
             if (dist == 0.0)
                 return dist;
             if (dist < minDistance)
                 minDistance = dist;
         }
     }
     return minDistance;
 }
double FacetSequence::computePointLineDistance (const geom::Coordinate & pt, const FacetSequence & facetSeq) const private
Definition at line 61 of file FacetSequence.cpp.
References end, geos::geom::CoordinateSequence::getAt(), pts, and start.
Referenced by distance().
{
     double minDistance = std::numeric_limits<double>::infinity();
     double dist;
     Coordinate q0;
     Coordinate q1;
     for (size_t i = facetSeq.start; i < facetSeq.end - 1; i++) {
         facetSeq.pts->getAt(i, q0);
         facetSeq.pts->getAt(i + 1, q1);
         dist = CGAlgorithms::distancePointLine(pt, q0, q1);
         if (dist == 0.0)
             return dist;
         if (dist < minDistance)
             minDistance = dist;
     }
     return minDistance;
 }
double FacetSequence::distance (const FacetSequence & facetSeq) const
Definition at line 41 of file FacetSequence.cpp.
References computeLineLineDistance(), computePointLineDistance(), geos::geom::Coordinate::distance(), geos::geom::CoordinateSequence::getAt(), isPoint(), pts, and start.
{
     bool isPointThis = isPoint();
     bool isPointOther = facetSeq.isPoint();
     if (isPointThis && isPointOther) {
         Coordinate pt = pts->getAt(start);
         Coordinate seqPt = facetSeq.pts->getAt(facetSeq.start);
         return pt.distance(seqPt);
     } else if (isPointThis) {
         Coordinate pt = pts->getAt(start);
         return computePointLineDistance(pt, facetSeq);
     } else if (isPointOther) {
         Coordinate seqPt = facetSeq.pts->getAt(facetSeq.start);
         return computePointLineDistance(seqPt, *this);
     }
     return computeLineLineDistance(facetSeq);
 }
const Coordinate * FacetSequence::getCoordinate (size_t index) const
Definition at line 115 of file FacetSequence.cpp.
References geos::geom::CoordinateSequence::getAt(), pts, and start.
Referenced by geos::precision::MinimumClearance::compute().
{
     return &(pts->getAt(start + index));
 }
const Envelope * FacetSequence::getEnvelope () const
Definition at line 111 of file FacetSequence.cpp.
References env.
Referenced by geos::operation::distance::FacetSequenceTreeBuilder::build().
{
     return &env;
 }
bool FacetSequence::isPoint () const
Definition at line 37 of file FacetSequence.cpp.
References end, and start.
Referenced by distance().
{
     return end - start == 1;
 }
size_t FacetSequence::size () const
Definition at line 33 of file FacetSequence.cpp.
References end, and start.
Referenced by geos::precision::MinimumClearance::compute().
{
     return end - start;
 }
Member Data Documentation
const size_t geos::operation::distance::FacetSequence::end private
Definition at line 33 of file FacetSequence.h.
Referenced by computeEnvelope(), computeLineLineDistance(), computePointLineDistance(), isPoint(), and size().
geom::Envelope geos::operation::distance::FacetSequence::env private
Definition at line 38 of file FacetSequence.h.
Referenced by computeEnvelope(), and getEnvelope().
const geom::CoordinateSequence* geos::operation::distance::FacetSequence::pts private
Definition at line 31 of file FacetSequence.h.
Referenced by computeEnvelope(), computeLineLineDistance(), computePointLineDistance(), distance(), and getCoordinate().
const size_t geos::operation::distance::FacetSequence::start private
Definition at line 32 of file FacetSequence.h.
Referenced by computeEnvelope(), computeLineLineDistance(), computePointLineDistance(), distance(), getCoordinate(), isPoint(), and size().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/distance/FacetSequence.h
/home/vicky/potree/geos/vicky/src/operation/distance/FacetSequence.cpp