GEOS: geos::algorithm::Angle Class Reference
geos::algorithm::Angle Class Reference
Utility functions for working with angles.
#include <Angle.h>
Static Public Member Functions
static double toDegrees (double radians)
Converts from radians to degrees.
static double toRadians (double angleDegrees)
Converts from degrees to radians.
static double angle (const geom::Coordinate &p0, const geom::Coordinate &p1)
Returns the angle of the vector from p0 to p1, relative to the positive X-axis.
static double angle (const geom::Coordinate &p)
Returns the angle that the vector from (0,0) to p, relative to the positive X-axis.
static bool isAcute (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &p2)
Tests whether the angle between p0-p1-p2 is acute.
static bool isObtuse (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &p2)
Tests whether the angle between p0-p1-p2 is obtuse.
static double angleBetween (const geom::Coordinate &tip1, const geom::Coordinate &tail, const geom::Coordinate &tip2)
Returns the unoriented smallest angle between two vectors.
static double angleBetweenOriented (const geom::Coordinate &tip1, const geom::Coordinate &tail, const geom::Coordinate &tip2)
Returns the oriented smallest angle between two vectors.
static double interiorAngle (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &p2)
Computes the interior angle between two segments of a ring.
static int getTurn (double ang1, double ang2)
Returns whether an angle must turn clockwise or counterclockwise to overlap another angle.
static double normalize (double angle)
Computes the normalized value of an angle, which is the equivalent angle in the range (-Pi, Pi ].
static double normalizePositive (double angle)
Computes the normalized positive value of an angle, which is the equivalent angle in the range [ 0, 2*Pi).
static double diff (double ang1, double ang2)
Computes the unoriented smallest difference between two angles.
Static Public Attributes
static const double PI_TIMES_2 = 2.0 * PI
static const double PI_OVER_2 = PI / 2.0
static const double PI_OVER_4 = PI / 4.0
static const int COUNTERCLOCKWISE = CGAlgorithms::COUNTERCLOCKWISE
Constant representing counterclockwise orientation.
static const int CLOCKWISE = CGAlgorithms::CLOCKWISE
Constant representing clockwise orientation.
static const int NONE = CGAlgorithms::COLLINEAR
Constant representing no orientation.
Detailed Description
Utility functions for working with angles.
Unless otherwise noted, methods in this class express angles in radians.
Definition at line 39 of file Angle.h.
Member Function Documentation
double geos::algorithm::Angle::angle (const geom::Coordinate & p0, const geom::Coordinate & p1) static
Returns the angle of the vector from p0 to p1, relative to the positive X-axis.
The angle is normalized to be in the range [ -Pi, Pi ].
Returns
the normalized angle (in radians) that p0-p1 makes with the positive x-axis.
Definition at line 52 of file Angle.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by angleBetween(), angleBetweenOriented(), interiorAngle(), normalize(), and normalizePositive().
 {
       double dx = p1.x - p0.x;
       double dy = p1.y - p0.y;
       return atan2(dy, dx);
 }
double geos::algorithm::Angle::angle (const geom::Coordinate & p) static
Returns the angle that the vector from (0,0) to p, relative to the positive X-axis.
The angle is normalized to be in the range (-Pi, Pi ].
Returns
the normalized angle (in radians) that p makes with the positive x-axis.
Definition at line 62 of file Angle.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   return atan2(p.y, p.x);
 }
double geos::algorithm::Angle::angleBetween (const geom::Coordinate & tip1, const geom::Coordinate & tail, const geom::Coordinate & tip2) static
Returns the unoriented smallest angle between two vectors.
The computed angle will be in the range [0, Pi).
Parameters
tip1 the tip of one vector
tail the tail of each vector
tip2 the tip of the other vector
Returns
the angle between tail-tip1 and tail-tip2
Definition at line 99 of file Angle.cpp.
References angle(), and diff().
 {
   double a1 = angle(tail, tip1);
   double a2 = angle(tail, tip2);
   return diff(a1, a2);
 }
double geos::algorithm::Angle::angleBetweenOriented (const geom::Coordinate & tip1, const geom::Coordinate & tail, const geom::Coordinate & tip2) static
Returns the oriented smallest angle between two vectors.
The computed angle will be in the range (-Pi, Pi]. A positive result corresponds to a counterclockwise rotation from v1 to v2; a negative result corresponds to a clockwise rotation.
Parameters
tip1 the tip of v1
tail the tail of each vector
tip2 the tip of v2
Returns
the angle between v1 and v2, relative to v1
Definition at line 111 of file Angle.cpp.
References angle(), and PI_TIMES_2.
 {
   double a1 = angle(tail, tip1);
   double a2 = angle(tail, tip2);
   double angDel = a2 - a1;
   // normalize, maintaining orientation
   if (angDel <= -PI)
     return angDel + PI_TIMES_2;
   if (angDel > PI)
     return angDel - PI_TIMES_2;
   return angDel;
 }
double geos::algorithm::Angle::diff (double ang1, double ang2) static
Computes the unoriented smallest difference between two angles.
The angles are assumed to be normalized to the range [-Pi, Pi]. The result will be in the range [0, Pi].
Parameters
ang1 the angle of one vector (in [-Pi, Pi])
ang2 the angle of the other vector (in range [-Pi, Pi])
Returns
the angle (in radians) between the two vectors (in range [0, Pi])
Definition at line 186 of file Angle.cpp.
Referenced by angleBetween().
 {
   double delAngle;
   if (ang1 < ang2) {
     delAngle = ang2 - ang1;
   } else {
     delAngle = ang1 - ang2;
   }
   if (delAngle > PI) {
     delAngle = (2 * PI) - delAngle;
   }
   return delAngle;
 }
int geos::algorithm::Angle::getTurn (double ang1, double ang2) static
Returns whether an angle must turn clockwise or counterclockwise to overlap another angle.
Parameters
ang1 an angle (in radians)
ang2 an angle (in radians)
Returns
whether a1 must turn CLOCKWISE, COUNTERCLOCKWISE or NONE to overlap a2.
Definition at line 139 of file Angle.cpp.
References CLOCKWISE, COUNTERCLOCKWISE, and NONE.
 {
   double crossproduct = sin(ang2 - ang1);
   if (crossproduct > 0) {
     return COUNTERCLOCKWISE;
   }
   if (crossproduct < 0) {
     return CLOCKWISE;
   }
   return NONE;
 }
double geos::algorithm::Angle::interiorAngle (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & p2) static
Computes the interior angle between two segments of a ring.
The ring is assumed to be oriented in a clockwise direction. The computed angle will be in the range [0, 2Pi]
Parameters
p0 a point of the ring
p1 the next point of the ring
p2 the next point of the ring
Returns
the interior angle based at p1
Definition at line 129 of file Angle.cpp.
References angle().
 {
   double anglePrev = angle(p1, p0);
   double angleNext = angle(p1, p2);
   return fabs(angleNext - anglePrev);
 }
bool geos::algorithm::Angle::isAcute (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & p2) static
Tests whether the angle between p0-p1-p2 is acute.
An angle is acute if it is less than 90 degrees.
Note: this implementation is not precise (determistic) for angles very close to 90 degrees.
Parameters
p0 an endpoint of the angle
p1 the base of the angle
p2 the other endpoint of the angle
Definition at line 69 of file Angle.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   // relies on fact that A dot B is positive iff A ang B is acute
   double dx0 = p0.x - p1.x;
   double dy0 = p0.y - p1.y;
   double dx1 = p2.x - p1.x;
   double dy1 = p2.y - p1.y;
   double dotprod = dx0 * dx1 + dy0 * dy1;
   return dotprod > 0;
 }
bool geos::algorithm::Angle::isObtuse (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & p2) static
Tests whether the angle between p0-p1-p2 is obtuse.
An angle is obtuse if it is greater than 90 degrees.
Note: this implementation is not precise (determistic) for angles very close to 90 degrees.
Parameters
p0 an endpoint of the angle
p1 the base of the angle
p2 the other endpoint of the angle
Definition at line 84 of file Angle.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   // relies on fact that A dot B is negative iff A ang B is obtuse
   double dx0 = p0.x - p1.x;
   double dy0 = p0.y - p1.y;
   double dx1 = p2.x - p1.x;
   double dy1 = p2.y - p1.y;
   double dotprod = dx0 * dx1 + dy0 * dy1;
   return dotprod < 0;
 }
double geos::algorithm::Angle::normalize (double angle) static
Computes the normalized value of an angle, which is the equivalent angle in the range (-Pi, Pi ].
Parameters
angle the angle to normalize
Returns
an equivalent angle in the range (-Pi, Pi]
Definition at line 154 of file Angle.cpp.
References angle(), and PI_TIMES_2.
 {
   while (angle > PI)
     angle -= PI_TIMES_2;
   while (angle <= -PI)
     angle += PI_TIMES_2;
   return angle;
 }
double geos::algorithm::Angle::normalizePositive (double angle) static
Computes the normalized positive value of an angle, which is the equivalent angle in the range [ 0, 2*Pi).
E.g.:
normalizePositive(0.0) = 0.0
normalizePositive(-PI) = PI
normalizePositive(-2PI) = 0.0
normalizePositive(-3PI) = PI
normalizePositive(-4PI) = 0
normalizePositive(PI) = PI
normalizePositive(2PI) = 0.0
normalizePositive(3PI) = PI
normalizePositive(4PI) = 0.0
Parameters
angle the angle to normalize, in radians
Returns
an equivalent positive angle
Definition at line 165 of file Angle.cpp.
References angle(), and PI_TIMES_2.
 {
   if (angle < 0.0) {
     while (angle < 0.0)
       angle += PI_TIMES_2;
     // in case round-off error bumps the value over
     if (angle >= PI_TIMES_2)
       angle = 0.0;
   }
   else {
     while (angle >= PI_TIMES_2)
       angle -= PI_TIMES_2;
     // in case round-off error bumps the value under
     if (angle < 0.0)
       angle = 0.0;
   }
   return angle;
 }
double geos::algorithm::Angle::toDegrees (double radians) static
Converts from radians to degrees.
Parameters
radians an angle in radians
Returns
the angle in degrees
Definition at line 38 of file Angle.cpp.
 {
       return (radians * 180) / (PI);
 }
double geos::algorithm::Angle::toRadians (double angleDegrees) static
Converts from degrees to radians.
Parameters
angleDegrees an angle in degrees
Returns
the angle in radians
Definition at line 45 of file Angle.cpp.
 {
   return (angleDegrees * PI) / 180.0;
 }
Member Data Documentation
const int geos::algorithm::Angle::CLOCKWISE = CGAlgorithms::CLOCKWISE static
Constant representing clockwise orientation.
Definition at line 51 of file Angle.h.
Referenced by getTurn().
const int geos::algorithm::Angle::COUNTERCLOCKWISE = CGAlgorithms::COUNTERCLOCKWISE static
Constant representing counterclockwise orientation.
Definition at line 48 of file Angle.h.
Referenced by getTurn().
const int geos::algorithm::Angle::NONE = CGAlgorithms::COLLINEAR static
Constant representing no orientation.
Definition at line 54 of file Angle.h.
Referenced by getTurn().
const double geos::algorithm::Angle::PI_OVER_2 = PI / 2.0 static
Definition at line 44 of file Angle.h.
const double geos::algorithm::Angle::PI_OVER_4 = PI / 4.0 static
Definition at line 45 of file Angle.h.
const double geos::algorithm::Angle::PI_TIMES_2 = 2.0 * PI static
Definition at line 43 of file Angle.h.
Referenced by angleBetweenOriented(), normalize(), and normalizePositive().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/Angle.h
/home/vicky/potree/geos/vicky/src/algorithm/Angle.cpp