GEOS: geos::operation::polygonize::Polygonizer Class Reference
geos::operation::polygonize::Polygonizer Class Reference
Polygonizes a set of Geometrys which contain linework that represents the edges of a planar graph.
#include <Polygonizer.h>
Classes
class LineStringAdder
Public Member Functions
Polygonizer ()
Create a polygonizer with the same GeometryFactory as the input Geometry.
~Polygonizer ()
void add (const std::vector< geom::Geometry * > *geomList)
Add a collection of geometries to be polygonized. May be called multiple times. Any dimension of Geometry may be added; the constituent linework will be extracted and used.
void add (const std::vector< const geom::Geometry * > *geomList)
Add a collection of geometries to be polygonized. May be called multiple times. Any dimension of Geometry may be added; the constituent linework will be extracted and used.
void add (const geom::Geometry *g)
std::vector< geom::Polygon * > getPolygons ()
Gets the list of polygons formed by the polygonization.
const std::vector< const geom::LineString * > & getDangles ()
Get the list of dangling lines found during polygonization.
const std::vector< const geom::LineString * > & getCutEdges ()
Get the list of cut edges found during polygonization.
const std::vector< geom::LineString * > & getInvalidRingLines ()
Get the list of lines forming invalid rings found during polygonization.
Polygonizer (const std::vector< geom::Geometry * > geomList)
Add a collection of geometries to be polygonized. May be called multiple times. Any dimension of Geometry may be added; the constituent linework will be extracted and used.
Polygonizer (const std::vector< const geom::Geometry * > geomList)
Polygonizer (const geom::Geometry *g)
void add (const std::vector< geom::Geometry * > geomList)
void add (const std::vector< const geom::Geometry * > geomList)
Private Member Functions
void add (const geom::LineString *line)
void polygonize ()
void clear ()
std::vector< EdgeRing * > findValidRings (const std::vector< EdgeRing * > &edgeRingList) const
void findShellsAndHoles (const std::vector< EdgeRing * > &edgeRingList)
Static Private Member Functions
static void assignHolesToShells (const std::vector< EdgeRing * > &holeList, std::vector< EdgeRing * > &shellList)
static void assignHoleToShell (EdgeRing *holeER, std::vector< EdgeRing * > &shellList)
Private Attributes
LineStringAdder lineStringAdder
PolygonizeGraph graph
std::vector< const geom::LineString * > dangles
std::vector< const geom::LineString * > cutEdges
std::vector< geom::LineString * > invalidRingLines
std::vector< EdgeRing * > holeList
std::vector< EdgeRing * > shellList
std::vector< geom::Polygon * > polyList
Detailed Description
Polygonizes a set of Geometrys which contain linework that represents the edges of a planar graph.
Any dimension of Geometry is handled - the constituent linework is extracted to form the edges. The edges must be correctly noded; that is, they must only meet at their endpoints. The Polygonizer will still run on incorrectly noded input but will not form polygons from incorrected noded edges.
The Polygonizer reports the follow kinds of errors:
Dangles - edges which have one or both ends which are not incident on another edge endpoint
Cut Edges - edges which are connected at both ends but which do not form part of polygon
Invalid Ring Lines - edges which form rings which are invalid (e.g. the component lines contain a self-intersection)
Definition at line 73 of file Polygonizer.h.
Constructor & Destructor Documentation
geos::operation::polygonize::Polygonizer::Polygonizer ()
Create a polygonizer with the same GeometryFactory as the input Geometry.
Definition at line 65 of file Polygonizer.cpp.
                         :
   lineStringAdder(this),
   graph(),
   dangles(),
   cutEdges(),
   invalidRingLines(),
   holeList(),
   shellList(),
   polyList()
 {
 }
geos::operation::polygonize::Polygonizer::~Polygonizer ()
Definition at line 99 of file Polygonizer.cpp.
References clear().
 {
   clear();
 }
geos::operation::polygonize::Polygonizer::Polygonizer (const std::vector< geom::Geometry * > geomList) explicit
Add a collection of geometries to be polygonized. May be called multiple times. Any dimension of Geometry may be added; the constituent linework will be extracted and used.
C++ Interface
Parameters
geomList a list of Geometry with linework to be polygonized
Definition at line 78 of file Polygonizer.cpp.
References add().
                                                                 :
   Polygonizer()
 {
   for (const auto g : (geomList)) add(g);
 }
geos::operation::polygonize::Polygonizer::Polygonizer (const std::vector< const geom::Geometry * > geomList) explicit
Definition at line 84 of file Polygonizer.cpp.
References add().
                                                                       :
   Polygonizer()
 {
   for (const auto g : (geomList)) add(g);
 }
geos::operation::polygonize::Polygonizer::Polygonizer (const geom::Geometry * g) explicit
Definition at line 90 of file Polygonizer.cpp.
References add().
                                               :
   Polygonizer()
 {
   add(g);
 }
Member Function Documentation
void geos::operation::polygonize::Polygonizer::add (const std::vector< geom::Geometry * > geomList)
Definition at line 113 of file Polygonizer.cpp.
References clear().
Referenced by add(), geos::operation::polygonize::Polygonizer::LineStringAdder::filter_ro(), GEOSPolygonize_full_r(), GEOSPolygonize_r(), GEOSPolygonizer_getCutEdges_r(), and Polygonizer().
 {
   clear();
   for (const auto g : (geomList)) add(g);
 }
void geos::operation::polygonize::Polygonizer::add (const std::vector< const geom::Geometry * > geomList)
Definition at line 120 of file Polygonizer.cpp.
References add(), and clear().
 {
   clear();
   for (const auto g : (geomList)) add(g);
 }
void geos::operation::polygonize::Polygonizer::add (const std::vector< geom::Geometry * > * geomList)
Add a collection of geometries to be polygonized. May be called multiple times. Any dimension of Geometry may be added; the constituent linework will be extracted and used.
Parameters
geomList a list of Geometry with linework to be polygonized
Definition at line 135 of file Polygonizer.cpp.
References add(), and clear().
 {
   clear();
   for (const auto g : (*geomList)) add(g);
 }
void geos::operation::polygonize::Polygonizer::add (const std::vector< const geom::Geometry * > * geomList)
Add a collection of geometries to be polygonized. May be called multiple times. Any dimension of Geometry may be added; the constituent linework will be extracted and used.
Parameters
geomList a list of Geometry with linework to be polygonized
Definition at line 150 of file Polygonizer.cpp.
References add(), geos::geom::Geometry::apply_ro(), clear(), and lineStringAdder.
 {
   clear();
   for (auto &g : (*geomList)) add(g);
 }
void geos::operation::polygonize::Polygonizer::add (const geom::Geometry * g)
Add a geometry to the linework to be polygonized. May be called multiple times. Any dimension of Geometry may be added; the constituent linework will be extracted and used
Parameters
g a Geometry with linework to be polygonized
Definition at line 181 of file Polygonizer.cpp.
References geos::geom::Geometry::apply_ro(), clear(), and lineStringAdder.
 {
   clear();
   g->apply_ro(&lineStringAdder);
 }
void geos::operation::polygonize::Polygonizer::add (const geom::LineString * line) private
Add a linestring to the graph of polygon edges.
Parameters
line the LineString to add
Definition at line 194 of file Polygonizer.cpp.
References geos::operation::polygonize::PolygonizeGraph::addEdge(), geos::operation::polygonize::PolygonizeGraph::empty(), geos::geom::Geometry::getFactory(), and graph.
 {
   // create a new graph using the factory from the input Geometry
   if (graph.empty())
     graph = PolygonizeGraph(line->getFactory());
   graph.addEdge(line);
 }
void geos::operation::polygonize::Polygonizer::assignHolesToShells (const std::vector< EdgeRing * > & holeList, std::vector< EdgeRing * > & shellList) static private
Definition at line 318 of file Polygonizer.cpp.
References assignHoleToShell(), and GEOS_CHECK_FOR_INTERRUPTS.
Referenced by polygonize().
 {
   for (const auto &holeER : holeList) {
     assignHoleToShell(holeER, shellList);
     GEOS_CHECK_FOR_INTERRUPTS();
   }
 }
void geos::operation::polygonize::Polygonizer::assignHoleToShell (EdgeRing * holeER, std::vector< EdgeRing * > & shellList) static private
Definition at line 328 of file Polygonizer.cpp.
References geos::operation::polygonize::EdgeRing::findEdgeRingContaining(), and geos::operation::polygonize::EdgeRing::getRingOwnership().
Referenced by assignHolesToShells().
 {
   auto shell = EdgeRing::findEdgeRingContaining(holeER, &shellList);
   if (shell)
     shell->addHole(holeER->getRingOwnership());
 }
void geos::operation::polygonize::Polygonizer::clear () private
Definition at line 104 of file Polygonizer.cpp.
References invalidRingLines, and polyList.
Referenced by add(), and ~Polygonizer().
{
   for (auto &p : polyList) delete p;
   polyList.clear();
   for (auto &r : invalidRingLines) delete r;
   invalidRingLines.clear();
 }
void geos::operation::polygonize::Polygonizer::findShellsAndHoles (const std::vector< EdgeRing * > & edgeRingList) private
Definition at line 302 of file Polygonizer.cpp.
References GEOS_CHECK_FOR_INTERRUPTS, holeList, and shellList.
Referenced by polygonize().
 {
   holeList.clear();
   shellList.clear();
   for (const auto &er : edgeRingList) {
     if (er->isHole())
       holeList.push_back(er);
     else
       shellList.push_back(er);
     GEOS_CHECK_FOR_INTERRUPTS();
   }
 }
vector< EdgeRing * > geos::operation::polygonize::Polygonizer::findValidRings (const std::vector< EdgeRing * > & edgeRingList) const private
Definition at line 282 of file Polygonizer.cpp.
References GEOS_CHECK_FOR_INTERRUPTS, and invalidRingLines.
Referenced by polygonize().
 {
   vector<EdgeRing*> validEdgeRingList;
   for (const auto &er : edgeRingList)
   {
     if (er->isValid())
     {
       validEdgeRingList.push_back(er);
     }
     else
     {
       invalidRingLines.push_back(er->getLineString());
     }
     GEOS_CHECK_FOR_INTERRUPTS();
   }
   return validEdgeRingList;
 }
const vector< const LineString * > & geos::operation::polygonize::Polygonizer::getCutEdges ()
Get the list of cut edges found during polygonization.
Returns
a (possibly empty) collection of pointers to the input LineStrings which are cut edges.
Definition at line 223 of file Polygonizer.cpp.
References cutEdges, and polygonize().
 {
   polygonize();
   return cutEdges;
 }
const vector< const LineString * > & geos::operation::polygonize::Polygonizer::getDangles ()
Get the list of dangling lines found during polygonization.
Returns
a (possibly empty) collection of pointers to the input LineStrings which are dangles.
Definition at line 215 of file Polygonizer.cpp.
References dangles, and polygonize().
 {
   polygonize();
   return dangles;
 }
const vector< LineString * > & geos::operation::polygonize::Polygonizer::getInvalidRingLines ()
Get the list of lines forming invalid rings found during polygonization.
Returns
a (possibly empty) collection of pointers to the input LineStrings which form invalid rings
Definition at line 231 of file Polygonizer.cpp.
References invalidRingLines, and polygonize().
 {
   polygonize();
   return invalidRingLines;
 }
vector< Polygon * > geos::operation::polygonize::Polygonizer::getPolygons ()
Gets the list of polygons formed by the polygonization.
Ownership of vector is transferred to caller, subsequent calls will return NULL.
Returns
a collection of Polygons
Definition at line 207 of file Polygonizer.cpp.
References polygonize(), and polyList.
 {
   polygonize();
   return polyList;
 }
void geos::operation::polygonize::Polygonizer::polygonize () private
Perform the polygonization, if it has not already been carried out.
Definition at line 239 of file Polygonizer.cpp.
References assignHolesToShells(), cutEdges, dangles, geos::operation::polygonize::PolygonizeGraph::deleteCutEdges(), geos::operation::polygonize::PolygonizeGraph::deleteDangles(), geos::operation::polygonize::PolygonizeGraph::empty(), findShellsAndHoles(), findValidRings(), geos::operation::polygonize::PolygonizeGraph::getEdgeRings(), graph, holeList, invalidRingLines, polyList, and shellList.
Referenced by getCutEdges(), getDangles(), getInvalidRingLines(), and getPolygons().
 {
   // check if already computed
   if (!polyList.empty()) return;
   polyList.clear();
   // if no geometries were supplied it's possible graph could be null
   if (graph.empty()) return;
   dangles = graph.deleteDangles();
   cutEdges = graph.deleteCutEdges();
   auto edgeRingList = graph.getEdgeRings();
 #if GEOS_DEBUG
   cerr<<"Polygonizer::polygonize(): "<<edgeRingList.size()<<" edgeRings in graph"<<endl;
 #endif
   auto validEdgeRingList = findValidRings(edgeRingList);
 #if GEOS_DEBUG
   cerr<<"                           "<<validEdgeRingList.size()<<" valid"<<endl;
   cerr<<"                           "<<invalidRingLines.size()<<" invalid"<<endl;
 #endif
   findShellsAndHoles(validEdgeRingList);
 #if GEOS_DEBUG
   cerr<<"                           "<<holeList.size()<<" holes"<<endl;
   cerr<<"                           "<<shellList.size()<<" shells"<<endl;
 #endif
   assignHolesToShells(holeList, shellList);
   for (const auto &er : shellList)
   {
     polyList.push_back(er->getPolygon());
   }
 }
Member Data Documentation
std::vector<const geom::LineString*> geos::operation::polygonize::Polygonizer::cutEdges private
Definition at line 231 of file Polygonizer.h.
Referenced by getCutEdges(), and polygonize().
std::vector<const geom::LineString*> geos::operation::polygonize::Polygonizer::dangles private
Definition at line 230 of file Polygonizer.h.
Referenced by getDangles(), and polygonize().
PolygonizeGraph geos::operation::polygonize::Polygonizer::graph private
Definition at line 227 of file Polygonizer.h.
Referenced by add(), and polygonize().
std::vector<EdgeRing*> geos::operation::polygonize::Polygonizer::holeList private
Definition at line 234 of file Polygonizer.h.
Referenced by findShellsAndHoles(), and polygonize().
std::vector<geom::LineString*> geos::operation::polygonize::Polygonizer::invalidRingLines mutable private
Definition at line 232 of file Polygonizer.h.
Referenced by clear(), findValidRings(), getInvalidRingLines(), and polygonize().
LineStringAdder geos::operation::polygonize::Polygonizer::lineStringAdder private
Definition at line 226 of file Polygonizer.h.
Referenced by add().
std::vector<geom::Polygon*> geos::operation::polygonize::Polygonizer::polyList private
Definition at line 236 of file Polygonizer.h.
Referenced by clear(), getPolygons(), and polygonize().
std::vector<EdgeRing*> geos::operation::polygonize::Polygonizer::shellList private
Definition at line 235 of file Polygonizer.h.
Referenced by findShellsAndHoles(), and polygonize().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/polygonize/Polygonizer.h
/home/vicky/potree/geos/vicky/src/operation/polygonize/Polygonizer.cpp