GEOS: geos::planargraph::Node Class Reference
geos::planargraph::Node Class Reference
A node in a PlanarGraph is a location where 0 or more Edge meet.
#include <Node.h>
Public Member Functions
Node (const geom::Coordinate &newPt)
Constructs a Node with the given location.
~Node () override
Node (geom::Coordinate &newPt, DirectedEdgeStar newDeStar)
Constructs a Node with the given location and collection of outgoing DirectedEdges. Takes ownership of the given DirectedEdgeStar!!
geom::Coordinate & getCoordinate ()
Returns the location of this Node.
void addOutEdge (DirectedEdge *de)
Adds an outgoing DirectedEdge to this Node.
DirectedEdgeStar getOutEdges ()
Returns the collection of DirectedEdges that leave this Node.
const DirectedEdgeStar & getOutEdges () const
size_t getDegree () const
Returns the number of edges around this Node.
int getIndex (Edge *edge)
Returns the zero-based index of the given Edge, after sorting in ascending order by angle with the positive x-axis.
virtual bool isVisited () const
Tests if a component has been visited during the course of a graph algorithm.
virtual void setVisited (bool isVisited)
Sets the visited flag for this component.
virtual void setMarked (bool isMarked)
Sets the marked flag for this component.
virtual bool isMarked () const
Tests if a component has been marked at some point during the processing involving this graph.
Static Public Member Functions
static std::vector< Edge * > * getEdgesBetween (Node *node0, Node *node1)
Returns all Edges that connect the two nodes (which are assumed to be different).
template<typename T >
static void setVisited (T start, T end, bool visited)
Sets the Visited state for the elements of a container, from start to end iterator.
template<typename T >
static void setVisitedMap (T start, T end, bool visited)
Sets the Visited state for the values of each map container element, from start to end iterator.
template<typename T >
static void setMarked (T start, T end, bool marked)
Sets the Marked state for the elements of a container, from start to end iterator.
template<typename T >
static void setMarkedMap (T start, T end, bool marked)
Sets the Marked state for the values of each map container element, from start to end iterator.
Protected Attributes
geom::Coordinate pt
The location of this Node.
DirectedEdgeStar deStar
The collection of DirectedEdges that leave this Node.
bool isMarkedVar
Variable holding ''marked'' status.
bool isVisitedVar
Variable holding ''visited'' status.
Friends
std::ostream & operator<< (std::ostream &os, const Node &)
Print a Node.
Detailed Description
A node in a PlanarGraph is a location where 0 or more Edge meet.
A node is connected to each of its incident Edges via an outgoing DirectedEdge. Some clients using a PlanarGraph may want to subclass Node to add their own application-specific data and methods.
Definition at line 45 of file Node.h.
Constructor & Destructor Documentation
geos::planargraph::Node::Node (const geom::Coordinate & newPt) inline
Constructs a Node with the given location.
Definition at line 69 of file Node.h.
     :
     pt(newPt)
     { }
geos::planargraph::Node::~Node () inline override
Definition at line 74 of file Node.h.
                    {
   }
geos::planargraph::Node::Node (geom::Coordinate & newPt, DirectedEdgeStar newDeStar) inline
Constructs a Node with the given location and collection of outgoing DirectedEdges. Takes ownership of the given DirectedEdgeStar!!
Definition at line 83 of file Node.h.
     :
     pt(newPt),
     deStar(newDeStar)
     {}
Member Function Documentation
void geos::planargraph::Node::addOutEdge (DirectedEdge * de) inline
Adds an outgoing DirectedEdge to this Node.
Definition at line 99 of file Node.h.
References geos::planargraph::DirectedEdgeStar::add().
Referenced by geos::planargraph::Edge::setDirectedEdges().
{
     deStar.add(de);
   }
geom::Coordinate& geos::planargraph::Node::getCoordinate () inline
Returns the location of this Node.
Definition at line 92 of file Node.h.
Referenced by geos::planargraph::NodeMap::add(), geos::planargraph::DirectedEdge::DirectedEdge(), and geos::planargraph::PlanarGraph::remove().
{
     return pt;
   }
size_t geos::planargraph::Node::getDegree () const inline
Returns the number of edges around this Node.
Definition at line 113 of file Node.h.
References geos::planargraph::DirectedEdgeStar::getDegree().
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForNonDegree2Nodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), geos::operation::linemerge::LineSequencer::findLowestDegreeNode(), geos::operation::linemerge::LineSequencer::hasSequence(), and geos::planargraph::operator<<().
{
     return deStar.getDegree();
   }
vector< Edge * > * geos::planargraph::Node::getEdgesBetween (Node * node0, Node * node1) static
Returns all Edges that connect the two nodes (which are assumed to be different).
Note: returned vector is newly allocated, ownership to the caller.
Definition at line 30 of file Node.cpp.
References geos::planargraph::DirectedEdgeStar::getEdges(), and getOutEdges().
 {
   std::vector<Edge*> edges0;
   DirectedEdge::toEdges(node0->getOutEdges().getEdges(), edges0);
   std::vector<Edge*> edges1;
   DirectedEdge::toEdges(node1->getOutEdges().getEdges(), edges1);
   // Sort edge lists (needed for set_intersection below
   std::sort( edges0.begin(), edges0.end() );
   std::sort( edges1.begin(), edges1.end() );
   std::vector<Edge*>* commonEdges = new std::vector<Edge*>();
   // Intersect the two sets
   std::set_intersection(
     edges0.begin(), edges0.end(),
     edges1.begin(), edges1.end(),
     commonEdges->end()
     );
   return commonEdges;
 }
int geos::planargraph::Node::getIndex (Edge * edge) inline
Returns the zero-based index of the given Edge, after sorting in ascending order by angle with the positive x-axis.
Definition at line 122 of file Node.h.
References geos::planargraph::DirectedEdgeStar::getIndex(), and geos::planargraph::operator<<().
{
     return deStar.getIndex(edge);
   }
DirectedEdgeStar geos::planargraph::Node::getOutEdges () inline
Returns the collection of DirectedEdges that leave this Node.
Definition at line 107 of file Node.h.
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges(), geos::operation::linemerge::LineMerger::buildEdgeStringsStartingAt(), geos::operation::polygonize::PolygonizeGraph::computeNextCCWEdges(), geos::operation::polygonize::PolygonizeGraph::computeNextCWEdges(), geos::operation::polygonize::PolygonizeGraph::deleteAllEdges(), geos::operation::linemerge::LineSequencer::findUnvisitedBestOrientedDE(), geos::operation::polygonize::PolygonizeGraph::getDegree(), geos::operation::polygonize::PolygonizeGraph::getDegreeNonDeleted(), getEdgesBetween(), geos::operation::linemerge::LineMergeDirectedEdge::getNext(), and geos::planargraph::PlanarGraph::remove().
 { return deStar; }
const DirectedEdgeStar& geos::planargraph::Node::getOutEdges () const inline
Definition at line 108 of file Node.h.
 { return deStar; }
virtual bool geos::planargraph::GraphComponent::isMarked () const inline virtual inherited
Tests if a component has been marked at some point during the processing involving this graph.
Returns
true if the component has been marked
Definition at line 146 of file GraphComponent.h.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsStartingAt(), and geos::planargraph::operator<<().
 { return isMarkedVar; }
virtual bool geos::planargraph::GraphComponent::isVisited () const inline virtual inherited
Tests if a component has been visited during the course of a graph algorithm.
Returns
true if the component has been visited
Definition at line 72 of file GraphComponent.h.
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges(), geos::planargraph::algorithm::ConnectedSubgraphFinder::getConnectedSubgraphs(), and geos::planargraph::operator<<().
 { return isVisitedVar; }
template<typename T > static void geos::planargraph::GraphComponent::setMarked (T start, T end, bool marked) inline static inherited
Sets the Marked state for the elements of a container, from start to end iterator.
Parameters
start the start element
end one past the last element
marked the state to set the marked flag to
Definition at line 119 of file GraphComponent.h.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForNonDegree2Nodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), geos::operation::linemerge::LineMerger::buildEdgeStringStartingWith(), geos::operation::polygonize::PolygonizeGraph::deleteAllEdges(), and geos::operation::polygonize::PolygonizeGraph::deleteCutEdges().
{
     for(T i=start; i!=end; ++i) {
       (*i)->setMarked(marked);
     }
   }
virtual void geos::planargraph::GraphComponent::setMarked (bool isMarked) inline virtual inherited
Sets the marked flag for this component.
Parameters
isMarked the desired value of the marked flag
Definition at line 152 of file GraphComponent.h.
 { isMarkedVar=isMarked; }
template<typename T > static void geos::planargraph::GraphComponent::setMarkedMap (T start, T end, bool marked) inline static inherited
Sets the Marked state for the values of each map container element, from start to end iterator.
Parameters
start the start element
end one past the last element
marked the state to set the visited flag to
Definition at line 135 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       i->second->setMarked(marked);
     }
   }
virtual void geos::planargraph::GraphComponent::setVisited (bool isVisited) inline virtual inherited
Sets the visited flag for this component.
Parameters
isVisited the desired value of the visited flag
Definition at line 78 of file GraphComponent.h.
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges(), and geos::operation::linemerge::LineSequencer::addReverseSubpath().
 { isVisitedVar=isVisited; }
template<typename T > static void geos::planargraph::GraphComponent::setVisited (T start, T end, bool visited) inline static inherited
Sets the Visited state for the elements of a container, from start to end iterator.
Parameters
start the start element
end one past the last element
visited the state to set the visited flag to
Definition at line 89 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       (*i)->setVisited(visited);
     }
   }
template<typename T > static void geos::planargraph::GraphComponent::setVisitedMap (T start, T end, bool visited) inline static inherited
Sets the Visited state for the values of each map container element, from start to end iterator.
Parameters
start the start element
end one past the last element
visited the state to set the visited flag to
Definition at line 104 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       i->second->setVisited(visited);
     }
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Node &) friend
Print a Node.
Definition at line 55 of file Node.cpp.
{
   os << "Node " << n.pt << " with degree " << n.getDegree();
   if ( n.isMarked() ) os << " Marked ";
   if ( n.isVisited() ) os << " Visited ";
   return os;
 }
Member Data Documentation
DirectedEdgeStar geos::planargraph::Node::deStar protected
The collection of DirectedEdges that leave this Node.
Definition at line 52 of file Node.h.
bool geos::planargraph::GraphComponent::isMarkedVar protected inherited
Variable holding ''marked'' status.
Definition at line 51 of file GraphComponent.h.
bool geos::planargraph::GraphComponent::isVisitedVar protected inherited
Variable holding ''visited'' status.
Definition at line 54 of file GraphComponent.h.
geom::Coordinate geos::planargraph::Node::pt protected
The location of this Node.
Definition at line 49 of file Node.h.
Referenced by geos::planargraph::operator<<().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/planargraph/Node.h
/home/vicky/potree/geos/vicky/src/planargraph/Node.cpp