GEOS: geos::operation::distance::ConnectedElementLocationFilter Class Reference
geos::operation::distance::ConnectedElementLocationFilter Class Reference
A ConnectedElementPointFilter extracts a single point from each connected element in a Geometry (e.g. a polygon, linestring or point) and returns them in a list. The elements of the list are DistanceOp::GeometryLocation.
#include <ConnectedElementLocationFilter.h>
Public Member Functions
ConnectedElementLocationFilter (std::vector< GeometryLocation * > *newLocations)
void filter_ro (const geom::Geometry *geom) override
void filter_rw (geom::Geometry *geom) override
Static Public Member Functions
static std::vector< GeometryLocation * > * getLocations (const geom::Geometry *geom)
Private Attributes
std::vector< GeometryLocation * > * locations
Detailed Description
A ConnectedElementPointFilter extracts a single point from each connected element in a Geometry (e.g. a polygon, linestring or point) and returns them in a list. The elements of the list are DistanceOp::GeometryLocation.
Definition at line 52 of file ConnectedElementLocationFilter.h.
Constructor & Destructor Documentation
geos::operation::distance::ConnectedElementLocationFilter::ConnectedElementLocationFilter (std::vector< GeometryLocation * > * newLocations) inline
Definition at line 66 of file ConnectedElementLocationFilter.h.
     :
     locations(newLocations)
   {}
Member Function Documentation
void geos::operation::distance::ConnectedElementLocationFilter::filter_ro (const geom::Geometry * geom) override virtual
Reimplemented from geos::geom::GeometryFilter.
Definition at line 48 of file ConnectedElementLocationFilter.cpp.
References geos::geom::Geometry::getCoordinate().
 {
   if ((typeid(*geom)==typeid(Point)) ||
     (typeid(*geom)==typeid(LineString)) ||
     (typeid(*geom)==typeid(LinearRing)) ||
     (typeid(*geom)==typeid(Polygon)))
   {
     locations->push_back(new GeometryLocation(geom, 0, *(geom->getCoordinate())));
   }
 }
void geos::operation::distance::ConnectedElementLocationFilter::filter_rw (geom::Geometry * geom) override virtual
Reimplemented from geos::geom::GeometryFilter.
Definition at line 59 of file ConnectedElementLocationFilter.cpp.
References geos::geom::Geometry::getCoordinate().
{
   if ((typeid(*geom)==typeid(Point)) ||
     (typeid(*geom)==typeid(LineString)) ||
     (typeid(*geom)==typeid(LinearRing)) ||
     (typeid(*geom)==typeid(Polygon)))
       locations->push_back(new GeometryLocation(geom, 0, *(geom->getCoordinate())));
 }
vector< GeometryLocation * > * geos::operation::distance::ConnectedElementLocationFilter::getLocations (const geom::Geometry * geom) static
Returns a list containing a point from each Polygon, LineString, and Point found inside the specified geometry. Thus, if the specified geometry is not a GeometryCollection, an empty list will be returned. The elements of the list are com.vividsolutions.jts.operation.distance.GeometryLocations.
Definition at line 39 of file ConnectedElementLocationFilter.cpp.
References geos::geom::Geometry::apply_ro().
Referenced by geos::operation::distance::DistanceOp::computeContainmentDistance().
 {
   vector<GeometryLocation*> *loc=new vector<GeometryLocation*>();
   ConnectedElementLocationFilter c(loc);
   geom->apply_ro(&c);
   return loc;
 }
Member Data Documentation
std::vector<GeometryLocation*>* geos::operation::distance::ConnectedElementLocationFilter::locations private
Definition at line 55 of file ConnectedElementLocationFilter.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/distance/ConnectedElementLocationFilter.h
/home/vicky/potree/geos/vicky/src/operation/distance/ConnectedElementLocationFilter.cpp