GEOS: geos::algorithm::PointLocator Class Reference
geos::algorithm::PointLocator Class Reference
Computes the topological relationship (Location) of a single point to a Geometry.
#include <geos/geosAlgorithm.h>
Public Member Functions
PointLocator ()
~PointLocator ()
int locate (const geom::Coordinate &p, const geom::Geometry *geom)
bool intersects (const geom::Coordinate &p, const geom::Geometry *geom)
Private Member Functions
void computeLocation (const geom::Coordinate &p, const geom::Geometry *geom)
void updateLocationInfo (int loc)
int locate (const geom::Coordinate &p, const geom::Point *pt)
int locate (const geom::Coordinate &p, const geom::LineString *l)
int locateInPolygonRing (const geom::Coordinate &p, const geom::LinearRing *ring)
int locate (const geom::Coordinate &p, const geom::Polygon *poly)
Private Attributes
bool isIn
int numBoundaries
Detailed Description
Computes the topological relationship (Location) of a single point to a Geometry.
The algorithm obeys the SFS boundaryDetermination rule to correctly determine whether the point lies on the boundary or not.
Notes:
instances of this class are not reentrant.
LinearRing objects do not enclose any area points inside the ring are still in the EXTERIOR of the ring.
Last port: algorithm/PointLocator.java rev. 1.26 (JTS-1.7+)
Definition at line 58 of file PointLocator.h.
Constructor & Destructor Documentation
geos::algorithm::PointLocator::PointLocator () inline
Definition at line 60 of file PointLocator.h.
 {}
geos::algorithm::PointLocator::~PointLocator () inline
Definition at line 61 of file PointLocator.h.
 {}
Member Function Documentation
void geos::algorithm::PointLocator::computeLocation (const geom::Coordinate & p, const geom::Geometry * geom) private
Definition at line 63 of file PointLocator.cpp.
 {
   if (const Point *pt=dynamic_cast<const Point*>(geom))
   {
     updateLocationInfo(locate(p, pt));
   }
   else if (const LineString *ls=dynamic_cast<const LineString*>(geom))
   {
     updateLocationInfo(locate(p, ls));
   }
   else if (const Polygon *po=dynamic_cast<const Polygon*>(geom))
   {
     updateLocationInfo(locate(p, po));
   }
   else if (const MultiLineString *mls=dynamic_cast<const MultiLineString *>(geom))
   {
     for(std::size_t i=0, n=mls->getNumGeometries(); i<n; ++i)
     {
       const LineString *l=dynamic_cast<const LineString *>(mls->getGeometryN(i));
       updateLocationInfo(locate(p,l));
     }
   }
   else if (const MultiPolygon *mpo=dynamic_cast<const MultiPolygon *>(geom))
   {
     for(std::size_t i=0, n=mpo->getNumGeometries(); i<n; ++i)
     {
       const Polygon *po=dynamic_cast<const Polygon *>(mpo->getGeometryN(i));
       updateLocationInfo(locate(p, po));
     }
   }
   else if (const GeometryCollection *col=dynamic_cast<const GeometryCollection *>(geom))
   {
     for (GeometryCollection::const_iterator
         it=col->begin(), endIt=col->end();
         it != endIt;
         ++it)
     {
       const Geometry *g2=*it;
       assert (g2!=geom); // is this check really needed ?
       computeLocation(p, g2);
     }
   }
 }
bool geos::algorithm::PointLocator::intersects (const geom::Coordinate & p, const geom::Geometry * geom) inline
Convenience method to test a point for intersection with a Geometry
Parameters
p the coordinate to test
geom the Geometry to test
Returns
true if the point is in the interior or boundary of the Geometry
Definition at line 83 of file PointLocator.h.
References geos::geom::Location::EXTERIOR.
Referenced by geos::geom::prep::BasicPreparedGeometry::isAnyTargetComponentInTest(), and geos::geom::prep::PreparedLineStringIntersects::isAnyTestPointInTarget().
{
     return locate(p, geom) != geom::Location::EXTERIOR;
   }
int geos::algorithm::PointLocator::locate (const geom::Coordinate & p, const geom::Geometry * geom)
Computes the topological relationship (Location) of a single point to a Geometry. It handles both single-element and multi-element Geometries. The algorithm for multi-part Geometries takes into account the boundaryDetermination rule.
Returns
the Location of the point relative to the input Geometry
Definition at line 42 of file PointLocator.cpp.
References geos::geom::Location::BOUNDARY, geos::geom::Location::EXTERIOR, geos::geom::Location::INTERIOR, geos::geom::Geometry::isEmpty(), and geos::geomgraph::GeometryGraph::isInBoundary().
Referenced by geos::operation::distance::DistanceOp::computeInside(), geos::operation::overlay::PointCoveredByAny::filter_ro(), geos::operation::overlay::validate::FuzzyPointLocator::getLocation(), geos::operation::overlay::OverlayOp::isCovered(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), geos::operation::relate::RelateComputer::labelIsolatedEdge(), geos::operation::overlay::LineBuilder::labelIsolatedLine(), and geos::operation::relate::RelateComputer::labelIsolatedNode().
 {
   if (geom->isEmpty()) return Location::EXTERIOR;
   const LineString *ls_geom = dynamic_cast<const LineString *>(geom);
   if (ls_geom) return locate(p, ls_geom);
   const Polygon *poly_geom = dynamic_cast<const Polygon *>(geom);
   if (poly_geom) return locate(p, poly_geom);
   isIn=false;
   numBoundaries=0;
   computeLocation(p,geom);
   if (geomgraph::GeometryGraph::isInBoundary(numBoundaries)) return Location::BOUNDARY;
   if (numBoundaries>0 || isIn) return Location::INTERIOR;
   return Location::EXTERIOR;
 }
int geos::algorithm::PointLocator::locate (const geom::Coordinate & p, const geom::Point * pt) private
Definition at line 118 of file PointLocator.cpp.
References geos::geom::Coordinate::equals2D(), geos::geom::Location::EXTERIOR, geos::geom::Point::getCoordinate(), and geos::geom::Location::INTERIOR.
 {
   // no point in doing envelope test, since equality test is just as fast
   const Coordinate *ptCoord = pt->getCoordinate();
   if (ptCoord->equals2D(p))
     return Location::INTERIOR;
   return Location::EXTERIOR;
 }
int geos::algorithm::PointLocator::locate (const geom::Coordinate & p, const geom::LineString * l) private
Definition at line 129 of file PointLocator.cpp.
References geos::geom::Location::BOUNDARY, geos::geom::Location::EXTERIOR, geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::CoordinateSequence::getSize(), geos::geom::Location::INTERIOR, and geos::geom::LineString::isClosed().
 {
   const CoordinateSequence* pt=l->getCoordinatesRO();
   if (! l->isClosed()) {
     if ((p==pt->getAt(0)) || (p==pt->getAt(pt->getSize()-1))) {
       return Location::BOUNDARY;
     }
   }
   if (CGAlgorithms::isOnLine(p,pt))
     return Location::INTERIOR;
   return Location::EXTERIOR;
 }
int geos::algorithm::PointLocator::locate (const geom::Coordinate & p, const geom::Polygon * poly) private
Definition at line 159 of file PointLocator.cpp.
References geos::geom::Location::BOUNDARY, geos::geom::Location::EXTERIOR, geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), geos::geom::Location::INTERIOR, and geos::geom::Polygon::isEmpty().
 {
   if (poly->isEmpty()) return Location::EXTERIOR;
   const LinearRing *shell=dynamic_cast<const LinearRing *>(poly->getExteriorRing());
   assert(shell);
   int shellLoc=locateInPolygonRing(p, shell);
   if (shellLoc==Location::EXTERIOR) return Location::EXTERIOR;
   if (shellLoc==Location::BOUNDARY) return Location::BOUNDARY;
   // now test if the point lies in or on the holes
   for(size_t i=0, n=poly->getNumInteriorRing(); i<n; ++i)
   {
     const LinearRing *hole=dynamic_cast<const LinearRing *>(poly->getInteriorRingN(i));
     int holeLoc=locateInPolygonRing(p,hole);
     if (holeLoc==Location::INTERIOR) return Location::EXTERIOR;
     if (holeLoc==Location::BOUNDARY) return Location::BOUNDARY;
   }
   return Location::INTERIOR;
 }
int geos::algorithm::PointLocator::locateInPolygonRing (const geom::Coordinate & p, const geom::LinearRing * ring) private
Definition at line 144 of file PointLocator.cpp.
References geos::geom::Location::BOUNDARY, geos::geom::Location::EXTERIOR, geos::geom::LineString::getCoordinatesRO(), and geos::geom::Location::INTERIOR.
 {
   // can this test be folded into isPointInRing ?
   const CoordinateSequence *cl = ring->getCoordinatesRO();
   if (CGAlgorithms::isOnLine(p,cl))
     return Location::BOUNDARY;
   if (CGAlgorithms::isPointInRing(p,cl))
     return Location::INTERIOR;
   return Location::EXTERIOR;
 }
void geos::algorithm::PointLocator::updateLocationInfo (int loc) private
Definition at line 110 of file PointLocator.cpp.
References geos::geom::Location::BOUNDARY, and geos::geom::Location::INTERIOR.
 {
   if (loc==Location::INTERIOR) isIn=true;
   if (loc==Location::BOUNDARY) ++numBoundaries;
 }
Member Data Documentation
bool geos::algorithm::PointLocator::isIn private
Definition at line 89 of file PointLocator.h.
int geos::algorithm::PointLocator::numBoundaries private
Definition at line 91 of file PointLocator.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/PointLocator.h
/home/vicky/potree/geos/vicky/src/algorithm/PointLocator.cpp