GEOS: geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry Class Reference
geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry Class Reference
Public Member Functions
IntervalIndexedGeometry (const geom::Geometry &g)
~IntervalIndexedGeometry ()
void query (double min, double max, index::ItemVisitor *visitor)
Private Member Functions
void init (const geom::Geometry &g)
void addLine (geom::CoordinateSequence *pts)
Private Attributes
index::intervalrtree::SortedPackedIntervalRTree * index
std::vector< geom::LineSegment * > allocatedSegments
Detailed Description
Definition at line 58 of file IndexedPointInAreaLocator.h.
Constructor & Destructor Documentation
geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::IntervalIndexedGeometry (const geom::Geometry & g)
Definition at line 38 of file IndexedPointInAreaLocator.cpp.
References index, and init().
 {
   index = new index::intervalrtree::SortedPackedIntervalRTree();
   init( g);
 }
geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::~IntervalIndexedGeometry ()
Definition at line 44 of file IndexedPointInAreaLocator.cpp.
References allocatedSegments, and index.
 {
   delete index;
   for ( size_t i = 0, ni = allocatedSegments.size(); i < ni; ++i )
   {
     delete allocatedSegments[i];
   }
 }
Member Function Documentation
void geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::addLine (geom::CoordinateSequence * pts) private
Definition at line 72 of file IndexedPointInAreaLocator.cpp.
References allocatedSegments, index, geos::index::intervalrtree::SortedPackedIntervalRTree::insert(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, geos::geom::CoordinateSequence::size(), and geos::geom::Coordinate::y.
Referenced by init().
 {
   for ( size_t i = 1, ni = pts->size(); i < ni; i++ )
   {
     geom::LineSegment * seg = new geom::LineSegment( (*pts)[ i - 1 ], (*pts)[ i ]);
     double const min = std::min( seg->p0.y, seg->p1.y);
     double const max = std::max( seg->p0.y, seg->p1.y);
     // NOTE: seg ownership still ours
     allocatedSegments.push_back(seg);
     index->insert( min, max, seg);
   }
 }
void geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::init (const geom::Geometry & g) private
Definition at line 55 of file IndexedPointInAreaLocator.cpp.
References addLine(), geos::geom::LineString::getCoordinates(), and geos::geom::util::LinearComponentExtracter::getLines().
Referenced by IntervalIndexedGeometry().
 {
   geom::LineString::ConstVect lines;
   geom::util::LinearComponentExtracter::getLines( g, lines);
   for ( size_t i = 0, ni = lines.size(); i < ni; i++ )
   {
     const geom::LineString * line = lines[ i ];
     geom::CoordinateSequence * pts = line->getCoordinates();
     addLine( pts);
     delete pts;
   }
 }
void geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::query (double min, double max, index::ItemVisitor * visitor)
Definition at line 139 of file IndexedPointInAreaLocator.cpp.
References geos::algorithm::locate::IndexedPointInAreaLocator::index, and query().
Referenced by geos::algorithm::locate::IndexedPointInAreaLocator::locate(), and query().
 {
   index->query( min, max, visitor);
 }
Member Data Documentation
std::vector< geom::LineSegment* > geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::allocatedSegments private
Definition at line 67 of file IndexedPointInAreaLocator.h.
Referenced by addLine(), and ~IntervalIndexedGeometry().
index::intervalrtree::SortedPackedIntervalRTree* geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::index private
Definition at line 61 of file IndexedPointInAreaLocator.h.
Referenced by addLine(), geos::algorithm::locate::IndexedPointInAreaLocator::buildIndex(), IntervalIndexedGeometry(), and ~IntervalIndexedGeometry().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/locate/IndexedPointInAreaLocator.h
/home/vicky/potree/geos/vicky/src/algorithm/locate/IndexedPointInAreaLocator.cpp