GEOS: geos::io::ByteOrderDataInStream Class Reference
geos::io::ByteOrderDataInStream Class Reference
#include <ByteOrderDataInStream.h>
Public Member Functions
ByteOrderDataInStream (std::istream *s=nullptr)
~ByteOrderDataInStream ()
void setInStream (std::istream *s)
void setOrder (int order)
unsigned char readByte ()
int readInt ()
long readLong ()
double readDouble ()
Private Attributes
int byteOrder
std::istream * stream
unsigned char buf [8]
Detailed Description
Definition at line 42 of file ByteOrderDataInStream.h.
Constructor & Destructor Documentation
INLINE geos::io::ByteOrderDataInStream::ByteOrderDataInStream (std::istream * s = nullptr)
Definition at line 34 of file ByteOrderDataInStream.inl.
References INLINE.
   :
   byteOrder(getMachineByteOrder()),
   stream(s)
 {
 }
INLINE geos::io::ByteOrderDataInStream::~ByteOrderDataInStream ()
Definition at line 42 of file ByteOrderDataInStream.inl.
References INLINE.
 {
 }
Member Function Documentation
INLINE unsigned char geos::io::ByteOrderDataInStream::readByte ()
Definition at line 59 of file ByteOrderDataInStream.inl.
References buf, INLINE, and stream.
Referenced by geos::io::WKBReader::readGeometry().
 {
   stream->read(reinterpret_cast<char *>(buf), 1);
   if ( stream->eof() )
     throw  ParseException("Unexpected EOF parsing WKB");
   return buf[0];
 }
INLINE double geos::io::ByteOrderDataInStream::readDouble ()
Definition at line 86 of file ByteOrderDataInStream.inl.
References buf, byteOrder, geos::io::ByteOrderValues::getDouble(), and stream.
Referenced by geos::io::WKBReader::readCoordinate().
 {
   stream->read(reinterpret_cast<char *>(buf), 8);
   if ( stream->eof() )
     throw  ParseException("Unexpected EOF parsing WKB");
   return ByteOrderValues::getDouble(buf, byteOrder);
 }
INLINE int geos::io::ByteOrderDataInStream::readInt ()
Definition at line 68 of file ByteOrderDataInStream.inl.
References buf, byteOrder, geos::io::ByteOrderValues::getInt(), INLINE, and stream.
Referenced by geos::io::WKBReader::readGeometry(), geos::io::WKBReader::readGeometryCollection(), geos::io::WKBReader::readLinearRing(), geos::io::WKBReader::readLineString(), geos::io::WKBReader::readMultiLineString(), geos::io::WKBReader::readMultiPoint(), geos::io::WKBReader::readMultiPolygon(), and geos::io::WKBReader::readPolygon().
 {
   stream->read(reinterpret_cast<char *>(buf), 4);
   if ( stream->eof() )
     throw  ParseException("Unexpected EOF parsing WKB");
   return ByteOrderValues::getInt(buf, byteOrder);
 }
INLINE long geos::io::ByteOrderDataInStream::readLong ()
Definition at line 77 of file ByteOrderDataInStream.inl.
References buf, byteOrder, geos::io::ByteOrderValues::getLong(), INLINE, and stream.
 {
   stream->read(reinterpret_cast<char *>(buf), 8);
   if ( stream->eof() )
     throw  ParseException("Unexpected EOF parsing WKB");
   return static_cast<long>(ByteOrderValues::getLong(buf, byteOrder));
 }
INLINE void geos::io::ByteOrderDataInStream::setInStream (std::istream * s)
Allows a single ByteOrderDataInStream to be reused on multiple istream.
Definition at line 47 of file ByteOrderDataInStream.inl.
References INLINE, and stream.
Referenced by geos::io::WKBReader::read().
 {
   stream=s;
 }
INLINE void geos::io::ByteOrderDataInStream::setOrder (int order)
Definition at line 53 of file ByteOrderDataInStream.inl.
References byteOrder, and INLINE.
Referenced by geos::io::WKBReader::readGeometry().
 {
   byteOrder=order;
 }
Member Data Documentation
unsigned char geos::io::ByteOrderDataInStream::buf[8] private
Definition at line 71 of file ByteOrderDataInStream.h.
Referenced by readByte(), readDouble(), readInt(), and readLong().
int geos::io::ByteOrderDataInStream::byteOrder private
Definition at line 67 of file ByteOrderDataInStream.h.
Referenced by readDouble(), readInt(), readLong(), and setOrder().
std::istream* geos::io::ByteOrderDataInStream::stream private
Definition at line 68 of file ByteOrderDataInStream.h.
Referenced by readByte(), readDouble(), readInt(), readLong(), and setInStream().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/io/ByteOrderDataInStream.h
/home/vicky/potree/geos/vicky/include/geos/io/ByteOrderDataInStream.inl