GEOS: geos::noding::MCIndexSegmentSetMutualIntersector Class Reference
geos::noding::MCIndexSegmentSetMutualIntersector Class Reference
Intersects two sets of SegmentStrings using a index based on MonotoneChains and a SpatialIndex.
#include <MCIndexSegmentSetMutualIntersector.h>
Classes
class SegmentOverlapAction
Public Member Functions
MCIndexSegmentSetMutualIntersector ()
~MCIndexSegmentSetMutualIntersector () override
std::vector< index::chain::MonotoneChain * > & getMonotoneChains ()
index::SpatialIndex * getIndex ()
void setBaseSegments (SegmentString::ConstVect *segStrings) override
void process (SegmentString::ConstVect *segStrings) override
void setSegmentIntersector (SegmentIntersector *si)
Protected Attributes
SegmentIntersector * segInt
Private Types
typedef std::vector< index::chain::MonotoneChain * > MonoChains
Private Member Functions
void addToIndex (SegmentString *segStr)
void intersectChains ()
void addToMonoChains (SegmentString *segStr)
Private Attributes
MonoChains monoChains
index::SpatialIndex * index
int indexCounter
int processCounter
int nOverlaps
MonoChains chainStore
Detailed Description
Intersects two sets of SegmentStrings using a index based on MonotoneChains and a SpatialIndex.
Version
1.7
Definition at line 54 of file MCIndexSegmentSetMutualIntersector.h.
Member Typedef Documentation
typedef std::vector<index::chain::MonotoneChain *> geos::noding::MCIndexSegmentSetMutualIntersector::MonoChains private
Definition at line 101 of file MCIndexSegmentSetMutualIntersector.h.
Constructor & Destructor Documentation
geos::noding::MCIndexSegmentSetMutualIntersector::MCIndexSegmentSetMutualIntersector ()
Definition at line 100 of file MCIndexSegmentSetMutualIntersector.cpp.
 : monoChains(),
 index(new geos::index::strtree::STRtree()),
 indexCounter(0),
 processCounter(0),
 nOverlaps(0)
 {
 }
geos::noding::MCIndexSegmentSetMutualIntersector::~MCIndexSegmentSetMutualIntersector () override
Definition at line 110 of file MCIndexSegmentSetMutualIntersector.cpp.
References chainStore, index, and monoChains.
 {
     delete index;
     MonoChains::iterator i, e;
     for (i = chainStore.begin(), e = chainStore.end(); i != e; ++i) {
         delete *i;
     }
     for (i = monoChains.begin(), e = monoChains.end(); i != e; i++) {
       delete *i;
     }
 }
Member Function Documentation
void geos::noding::MCIndexSegmentSetMutualIntersector::addToIndex (SegmentString * segStr) private
Definition at line 38 of file MCIndexSegmentSetMutualIntersector.cpp.
References geos::index::chain::MonotoneChainBuilder::getChains(), geos::noding::SegmentString::getCoordinates(), geos::index::chain::MonotoneChain::getEnvelope(), and geos::index::chain::MonotoneChain::setId().
Referenced by setBaseSegments().
 {
     MonoChains segChains;
     MonotoneChainBuilder::getChains(segStr->getCoordinates(),
       segStr, segChains);
     MonoChains::size_type n = segChains.size();
     chainStore.reserve(chainStore.size() + n);
     for (MonoChains::size_type i = 0; i < n; i++)
     {
         MonotoneChain * mc = segChains[i];
         mc->setId(indexCounter++);
         index->insert(&(mc->getEnvelope()), mc);
         chainStore.push_back(mc);
     }
 }
void geos::noding::MCIndexSegmentSetMutualIntersector::addToMonoChains (SegmentString * segStr) private
Definition at line 83 of file MCIndexSegmentSetMutualIntersector.cpp.
References geos::index::chain::MonotoneChainBuilder::getChains(), geos::noding::SegmentString::getCoordinates(), and geos::index::chain::MonotoneChain::setId().
Referenced by process().
 {
     MonoChains segChains;
     MonotoneChainBuilder::getChains(segStr->getCoordinates(),
                                     segStr, segChains);
     MonoChains::size_type n = segChains.size();
     monoChains.reserve(monoChains.size() + n);
     for (MonoChains::size_type i = 0; i < n; i++)
     {
         MonotoneChain* mc = segChains[i];
         mc->setId( processCounter++ );
         monoChains.push_back(mc);
     }
 }
index::SpatialIndex* geos::noding::MCIndexSegmentSetMutualIntersector::getIndex () inline
Definition at line 71 of file MCIndexSegmentSetMutualIntersector.h.
   {
     return index;
   }
std::vector<index::chain::MonotoneChain *>& geos::noding::MCIndexSegmentSetMutualIntersector::getMonotoneChains () inline
Definition at line 66 of file MCIndexSegmentSetMutualIntersector.h.
   {
     return monoChains;
   }
void geos::noding::MCIndexSegmentSetMutualIntersector::intersectChains () private
Definition at line 58 of file MCIndexSegmentSetMutualIntersector.cpp.
References geos::index::chain::MonotoneChain::computeOverlaps(), and geos::index::chain::MonotoneChain::getEnvelope().
Referenced by process().
 {
     MCIndexSegmentSetMutualIntersector::SegmentOverlapAction overlapAction( *segInt);
     for (MonoChains::size_type i = 0, ni = monoChains.size(); i < ni; ++i)
     {
         MonotoneChain * queryChain = (MonotoneChain *)monoChains[i];
         std::vector<void*> overlapChains;
         index->query( &(queryChain->getEnvelope()), overlapChains);
         for (std::size_t j = 0, nj = overlapChains.size(); j < nj; j++)
         {
             MonotoneChain * testChain = (MonotoneChain *)(overlapChains[j]);
             queryChain->computeOverlaps( testChain, &overlapAction);
             nOverlaps++;
             if (segInt->isDone())
                 return;
         }
     }
 }
void geos::noding::MCIndexSegmentSetMutualIntersector::process (SegmentString::ConstVect * segStrings) override virtual
Computes the intersections for two collections of SegmentStrings.
Parameters
segStrings1 a collection of SegmentStrings to node
Implements geos::noding::SegmentSetMutualIntersector.
Definition at line 141 of file MCIndexSegmentSetMutualIntersector.cpp.
References addToMonoChains(), indexCounter, intersectChains(), monoChains, nOverlaps, and processCounter.
Referenced by geos::noding::FastSegmentSetIntersectionFinder::intersects().
 {
     processCounter = indexCounter + 1;
     nOverlaps = 0;
     for (MonoChains::iterator i = monoChains.begin(), e = monoChains.end();
          i != e; i++)
     {
       delete *i;
     }
     monoChains.clear();
     for (SegmentString::ConstVect::size_type i = 0, n = segStrings->size(); i < n; i++)
     {
         SegmentString * seg = (SegmentString *)((*segStrings)[i]);
         addToMonoChains( seg);
     }
     intersectChains();
 }
void geos::noding::MCIndexSegmentSetMutualIntersector::setBaseSegments (SegmentString::ConstVect * segStrings) override virtual
Parameters
segStrings0 a collection of SegmentStrings to node
Implements geos::noding::SegmentSetMutualIntersector.
Definition at line 127 of file MCIndexSegmentSetMutualIntersector.cpp.
References addToIndex().
Referenced by geos::noding::FastSegmentSetIntersectionFinder::FastSegmentSetIntersectionFinder().
 {
     // NOTE - mloskot: const qualifier is removed silently, dirty.
     for (std::size_t i = 0, n = segStrings->size(); i < n; i++)
     {
         const SegmentString* css = (*segStrings)[i];
         SegmentString* ss = const_cast<SegmentString*>(css);
         addToIndex(ss);
     }
 }
void geos::noding::SegmentSetMutualIntersector::setSegmentIntersector (SegmentIntersector * si) inline inherited
Sets the SegmentIntersector to use with this intersector. The SegmentIntersector will either rocord or add intersection nodes for the input segment strings.
Parameters
segInt the segment intersector to use
Definition at line 54 of file SegmentSetMutualIntersector.h.
References geos::noding::SegmentSetMutualIntersector::process(), geos::noding::SegmentSetMutualIntersector::segInt, and geos::noding::SegmentSetMutualIntersector::setBaseSegments().
Referenced by geos::noding::FastSegmentSetIntersectionFinder::intersects().
   {
     segInt = si;
   }
Member Data Documentation
MonoChains geos::noding::MCIndexSegmentSetMutualIntersector::chainStore private
Definition at line 118 of file MCIndexSegmentSetMutualIntersector.h.
Referenced by ~MCIndexSegmentSetMutualIntersector().
index::SpatialIndex* geos::noding::MCIndexSegmentSetMutualIntersector::index private
Definition at line 109 of file MCIndexSegmentSetMutualIntersector.h.
Referenced by ~MCIndexSegmentSetMutualIntersector().
int geos::noding::MCIndexSegmentSetMutualIntersector::indexCounter private
Definition at line 110 of file MCIndexSegmentSetMutualIntersector.h.
Referenced by process().
MonoChains geos::noding::MCIndexSegmentSetMutualIntersector::monoChains private
Definition at line 102 of file MCIndexSegmentSetMutualIntersector.h.
Referenced by process(), and ~MCIndexSegmentSetMutualIntersector().
int geos::noding::MCIndexSegmentSetMutualIntersector::nOverlaps private
Definition at line 113 of file MCIndexSegmentSetMutualIntersector.h.
Referenced by process().
int geos::noding::MCIndexSegmentSetMutualIntersector::processCounter private
Definition at line 111 of file MCIndexSegmentSetMutualIntersector.h.
Referenced by process().
SegmentIntersector* geos::noding::SegmentSetMutualIntersector::segInt protected inherited
Definition at line 74 of file SegmentSetMutualIntersector.h.
Referenced by geos::noding::SegmentSetMutualIntersector::setSegmentIntersector().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/MCIndexSegmentSetMutualIntersector.h
/home/vicky/potree/geos/vicky/src/noding/MCIndexSegmentSetMutualIntersector.cpp