GEOS: geos::planargraph::NodeMap Class Reference
geos::planargraph::NodeMap Class Reference
A map of Node, indexed by the coordinate of the node.
#include <NodeMap.h>
Public Types
typedef std::map< geom::Coordinate, Node *, geom::CoordinateLessThen > container
Public Member Functions
NodeMap ()=default
Constructs a NodeMap without any Nodes.
~NodeMap ()=default
container & getNodeMap ()
Node * add (Node *n)
Adds a node to the std::map, replacing any that is already at that location.
Node * remove (geom::Coordinate &pt)
Removes the Node at the given location, and returns it (or null if no Node was there).
Node * find (const geom::Coordinate &coord) const
Returns the Node at the given location, or null if no Node was there.
container::iterator iterator ()
Returns an Iterator over the Nodes in this NodeMap, sorted in ascending order by angle with the positive x-axis.
container::iterator begin ()
container::const_iterator begin () const
container::iterator end ()
container::const_iterator end () const
std::vector< Node * > getNodes () const
Returns the Nodes in this NodeMap, sorted in ascending order by angle with the positive x-axis.
void getNodes (std::vector< Node * > &nodes) const
Returns the Nodes in this NodeMap, sorted in ascending order by angle with the positive x-axis.
Private Attributes
container nodeMap
Detailed Description
A map of Node, indexed by the coordinate of the node.
Will not:
create a new node
destroy the nodes
Classes using this NodeMap are responsible to do
pointer cleanup when needed
pass the responability to another class
Definition at line 48 of file NodeMap.h.
Member Typedef Documentation
typedef std::map<geom::Coordinate, Node*, geom::CoordinateLessThen> geos::planargraph::NodeMap::container
Definition at line 50 of file NodeMap.h.
Constructor & Destructor Documentation
geos::planargraph::NodeMap::NodeMap () default
Constructs a NodeMap without any Nodes.
geos::planargraph::NodeMap::~NodeMap () default
Member Function Documentation
Node * geos::planargraph::NodeMap::add (Node * n)
Adds a node to the std::map, replacing any that is already at that location.
Returns
the added node
Adds a node to the map, replacing any that is already at that location.
Returns
the added node
Definition at line 37 of file NodeMap.cpp.
References geos::planargraph::Node::getCoordinate(), and nodeMap.
Referenced by geos::planargraph::PlanarGraph::add().
 {
   nodeMap.insert(std::pair<geom::Coordinate, Node*> (n->getCoordinate(), n));
   return n;
 }
container::iterator geos::planargraph::NodeMap::begin () inline
Definition at line 97 of file NodeMap.h.
Referenced by geos::planargraph::PlanarGraph::nodeBegin(), and geos::planargraph::PlanarGraph::nodeIterator().
{
     return nodeMap.begin();
   }
container::const_iterator geos::planargraph::NodeMap::begin () const inline
Definition at line 100 of file NodeMap.h.
{
     return nodeMap.begin();
   }
container::iterator geos::planargraph::NodeMap::end () inline
Definition at line 104 of file NodeMap.h.
Referenced by geos::planargraph::PlanarGraph::nodeEnd().
{
     return nodeMap.end();
   }
container::const_iterator geos::planargraph::NodeMap::end () const inline
Definition at line 107 of file NodeMap.h.
{
     return nodeMap.end();
   }
Node * geos::planargraph::NodeMap::find (const geom::Coordinate & coord) const
Returns the Node at the given location, or null if no Node was there.
Returns the Node ptr at the given location, or null if no Node was there.
Definition at line 79 of file NodeMap.cpp.
References nodeMap.
Referenced by geos::planargraph::PlanarGraph::findNode(), and remove().
 {
   auto found = nodeMap.find(coord);
   return (found == nodeMap.end()) ?
     nullptr :
     found->second;
 }
NodeMap::container & geos::planargraph::NodeMap::getNodeMap ()
Definition at line 27 of file NodeMap.cpp.
References nodeMap.
 {
   return nodeMap;
 }
std::vector< Node * > geos::planargraph::NodeMap::getNodes () const
Returns the Nodes in this NodeMap, sorted in ascending order by angle with the positive x-axis.
Returns
a vector of Node pointers
Definition at line 57 of file NodeMap.cpp.
References nodeMap.
Referenced by getNodes(), and geos::planargraph::PlanarGraph::getNodes().
 {
   std::vector<Node*> values;
   for (const auto e : nodeMap) {
     values.push_back(e.second);
   }
   return values;
 }
void geos::planargraph::NodeMap::getNodes (std::vector< Node * > & nodes) const
Returns the Nodes in this NodeMap, sorted in ascending order by angle with the positive x-axis.
Parameters
nodes : the nodes are push_back'ed here
Definition at line 70 of file NodeMap.cpp.
References getNodes().
 {
   values = getNodes();
 }
container::iterator geos::planargraph::NodeMap::iterator () inline
Returns an Iterator over the Nodes in this NodeMap, sorted in ascending order by angle with the positive x-axis.
Definition at line 93 of file NodeMap.h.
{
     return nodeMap.begin();
   }
Node * geos::planargraph::NodeMap::remove (geom::Coordinate & pt)
Removes the Node at the given location, and returns it (or null if no Node was there).
Removes the Node at the given location, and returns it (or null if no Node was there).
Definition at line 48 of file NodeMap.cpp.
References find(), and nodeMap.
 {
   Node *n = find(pt);
   nodeMap.erase(pt);
   return n;
 }
Member Data Documentation
container geos::planargraph::NodeMap::nodeMap private
Definition at line 53 of file NodeMap.h.
Referenced by add(), find(), getNodeMap(), getNodes(), and remove().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/planargraph/NodeMap.h
/home/vicky/potree/geos/vicky/src/planargraph/NodeMap.cpp