GEOS: geos::geomgraph::EdgeIntersectionList Class Reference
geos::geomgraph::EdgeIntersectionList Class Reference
#include <EdgeIntersectionList.h>
Public Types
typedef std::set< EdgeIntersection *, EdgeIntersectionLessThen > container
typedef container::iterator iterator
typedef container::const_iterator const_iterator
Public Member Functions
EdgeIntersectionList (Edge *edge)
~EdgeIntersectionList ()
EdgeIntersection * add (const geom::Coordinate &coord, int segmentIndex, double dist)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool isEmpty () const
bool isIntersection (const geom::Coordinate &pt) const
void addEndpoints ()
void addSplitEdges (std::vector< Edge * > *edgeList)
Edge * createSplitEdge (EdgeIntersection *ei0, EdgeIntersection *ei1)
std::string print () const
Public Attributes
Edge * edge
Private Attributes
container nodeMap
Detailed Description
A list of edge intersections along an Edge. Implements splitting an edge with intersections into multiple resultant edges.
Definition at line 59 of file EdgeIntersectionList.h.
Member Typedef Documentation
typedef container::const_iterator geos::geomgraph::EdgeIntersectionList::const_iterator
Definition at line 63 of file EdgeIntersectionList.h.
typedef std::set<EdgeIntersection *, EdgeIntersectionLessThen> geos::geomgraph::EdgeIntersectionList::container
Definition at line 61 of file EdgeIntersectionList.h.
typedef container::iterator geos::geomgraph::EdgeIntersectionList::iterator
Definition at line 62 of file EdgeIntersectionList.h.
Constructor & Destructor Documentation
geos::geomgraph::EdgeIntersectionList::EdgeIntersectionList (Edge * edge)
Definition at line 49 of file EdgeIntersectionList.cpp.
                                                        :
   edge(newEdge)
 {
 }
geos::geomgraph::EdgeIntersectionList::~EdgeIntersectionList ()
Definition at line 54 of file EdgeIntersectionList.cpp.
References nodeMap.
 {
   for (EdgeIntersectionList::iterator it=nodeMap.begin(),
     endIt=nodeMap.end();
     it!=endIt; ++it)
   {
     delete *it;
   }
 }
Member Function Documentation
EdgeIntersection * geos::geomgraph::EdgeIntersectionList::add (const geom::Coordinate & coord, int segmentIndex, double dist)
Definition at line 65 of file EdgeIntersectionList.cpp.
References nodeMap.
Referenced by addEndpoints(), and geos::geomgraph::Edge::addIntersection().
 {
   EdgeIntersection *eiNew=new EdgeIntersection(coord, segmentIndex, dist);
   pair<EdgeIntersectionList::iterator, bool> p = nodeMap.insert(eiNew);
   if ( p.second ) { // new EdgeIntersection inserted
     return eiNew;
   } else {
     delete eiNew;
     return *(p.first);
   }
 }
void geos::geomgraph::EdgeIntersectionList::addEndpoints ()
Definition at line 101 of file EdgeIntersectionList.cpp.
References add(), edge, geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getNumPoints(), and geos::geomgraph::Edge::pts.
Referenced by addSplitEdges(), and geos::operation::relate::EdgeEndBuilder::computeEdgeEnds().
 {
   int maxSegIndex=edge->getNumPoints()-1;
   add(edge->pts->getAt(0), 0, 0.0);
   add(edge->pts->getAt(maxSegIndex), maxSegIndex, 0.0);
 }
void geos::geomgraph::EdgeIntersectionList::addSplitEdges (std::vector< Edge * > * edgeList)
Creates new edges for all the edges that the intersections in this list split the parent edge into. Adds the edges to the input list (this is so a single list can be used to accumulate all split edges for a Geometry).
Parameters
edgeList a list of EdgeIntersections
Definition at line 109 of file EdgeIntersectionList.cpp.
References addEndpoints(), createSplitEdge(), and nodeMap.
Referenced by geos::geomgraph::GeometryGraph::computeSplitEdges(), and geos::operation::overlay::EdgeSetNoder::getNodedEdges().
 {
   // ensure that the list has entries for the first and last point
   // of the edge
   addEndpoints();
   EdgeIntersectionList::iterator it=nodeMap.begin();
   // there should always be at least two entries in the list
   EdgeIntersection *eiPrev=*it;
   ++it;
   while (it!=nodeMap.end()) {
     EdgeIntersection *ei=*it;
     Edge *newEdge=createSplitEdge(eiPrev,ei);
     edgeList->push_back(newEdge);
     eiPrev=ei;
     it++;
   }
 }
iterator geos::geomgraph::EdgeIntersectionList::begin () inline
Definition at line 82 of file EdgeIntersectionList.h.
Referenced by geos::geomgraph::GeometryGraph::addSelfIntersectionNodes(), geos::operation::valid::IsValidOp::checkNoSelfIntersectingRing(), geos::operation::relate::EdgeEndBuilder::computeEdgeEnds(), geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), geos::operation::IsSimpleOp::hasNonEndpointIntersection(), geos::operation::relate::RelateComputer::labelIntersectionNodes(), and geos::geomgraph::operator<<().
 { return nodeMap.begin(); }
const_iterator geos::geomgraph::EdgeIntersectionList::begin () const inline
Definition at line 84 of file EdgeIntersectionList.h.
 { return nodeMap.begin(); }
Edge * geos::geomgraph::EdgeIntersectionList::createSplitEdge (EdgeIntersection * ei0, EdgeIntersection * ei1)
Definition at line 131 of file EdgeIntersectionList.cpp.
References geos::geomgraph::EdgeIntersection::coord, geos::geomgraph::EdgeIntersection::dist, edge, geos::geom::Coordinate::equals2D(), geos::geom::CoordinateSequence::getAt(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Edge::pts, and geos::geomgraph::EdgeIntersection::segmentIndex.
Referenced by addSplitEdges().
 {
 #if GEOS_DEBUG
   cerr<<"["<<this<<"] EdgeIntersectionList::createSplitEdge()"<<endl;
 #endif // GEOS_DEBUG
   int npts=ei1->segmentIndex-ei0->segmentIndex+2;
   const Coordinate& lastSegStartPt=edge->pts->getAt(ei1->segmentIndex);
   // if the last intersection point is not equal to the its segment
   // start pt, add it to the points list as well.
   // (This check is needed because the distance metric is not totally
   // reliable!). The check for point equality is 2D only - Z values
   // are ignored
   bool useIntPt1=ei1->dist>0.0 || !ei1->coord.equals2D(lastSegStartPt);
   if (!useIntPt1) --npts;
 #if GEOS_DEBUG
   cerr<<"    npts:"<<npts<<endl;
 #endif // GEOS_DEBUG
   vector<Coordinate> *vc=new vector<Coordinate>();
   vc->reserve(npts);
   vc->push_back(ei0->coord);
   for(int i=ei0->segmentIndex+1; i<=ei1->segmentIndex;i++)
   {
     if ( ! useIntPt1 && ei1->segmentIndex == i )
     {
       vc->push_back(ei1->coord);
     }
     else
     {
       vc->push_back(edge->pts->getAt(i));
     }
   }
   if (useIntPt1)
   {
     vc->push_back(ei1->coord);
   }
   CoordinateSequence* pts=new CoordinateArraySequence(vc);
   return new Edge(pts, edge->getLabel());
 }
iterator geos::geomgraph::EdgeIntersectionList::end () inline
Definition at line 83 of file EdgeIntersectionList.h.
Referenced by geos::geomgraph::GeometryGraph::addSelfIntersectionNodes(), geos::operation::valid::IsValidOp::checkNoSelfIntersectingRing(), geos::operation::relate::EdgeEndBuilder::computeEdgeEnds(), geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), geos::operation::IsSimpleOp::hasNonEndpointIntersection(), geos::operation::relate::RelateComputer::labelIntersectionNodes(), and geos::geomgraph::operator<<().
 { return nodeMap.end(); }
const_iterator geos::geomgraph::EdgeIntersectionList::end () const inline
Definition at line 85 of file EdgeIntersectionList.h.
References geos::geom::operator<<().
 { return nodeMap.end(); }
bool geos::geomgraph::EdgeIntersectionList::isEmpty () const
Definition at line 80 of file EdgeIntersectionList.cpp.
References nodeMap.
 {
   return nodeMap.empty();
 }
bool geos::geomgraph::EdgeIntersectionList::isIntersection (const geom::Coordinate & pt) const
Definition at line 86 of file EdgeIntersectionList.cpp.
References geos::geomgraph::EdgeIntersection::coord, and nodeMap.
Referenced by geos::operation::valid::IsValidOp::findPtNotNode().
 {
   EdgeIntersectionList::const_iterator
     it=nodeMap.begin(),
     endIt=nodeMap.end();
   for (; it!=endIt; ++it)
   {
     EdgeIntersection *ei=*it;
     if (ei->coord==pt) return true;
   }
   return false;
 }
string geos::geomgraph::EdgeIntersectionList::print () const
Definition at line 181 of file EdgeIntersectionList.cpp.
Referenced by geos::geomgraph::PlanarGraph::printEdges().
 {
   std::stringstream ss;
   ss << *this;
   return ss.str();
 }
Member Data Documentation
Edge* geos::geomgraph::EdgeIntersectionList::edge
Definition at line 70 of file EdgeIntersectionList.h.
Referenced by addEndpoints(), and createSplitEdge().
container geos::geomgraph::EdgeIntersectionList::nodeMap private
Definition at line 66 of file EdgeIntersectionList.h.
Referenced by add(), addSplitEdges(), isEmpty(), isIntersection(), and ~EdgeIntersectionList().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/EdgeIntersectionList.h
/home/vicky/potree/geos/vicky/src/geomgraph/EdgeIntersectionList.cpp