GEOS: geos::index::strtree::AbstractSTRtree Class Reference
geos::index::strtree::AbstractSTRtree Class Reference abstract
Base class for STRtree and SIRtree.
#include <AbstractSTRtree.h>
Classes
class IntersectsOp
A test for intersection between two bounds, necessary because subclasses of AbstractSTRtree have different implementations of bounds.
Public Member Functions
AbstractSTRtree (std::size_t newNodeCapacity)
virtual ~AbstractSTRtree ()
virtual void build ()
virtual std::size_t getNodeCapacity ()
virtual void query (const void *searchBounds, const AbstractNode *node, std::vector< void * > *matches)
void iterate (ItemVisitor &visitor)
virtual void boundablesAtLevel (int level, AbstractNode *top, BoundableList *boundables)
ItemsList * itemsTree ()
Static Public Member Functions
static bool compareDoubles (double a, double b)
Protected Member Functions
virtual AbstractNode * createNode (int level)=0
virtual std::unique_ptr< BoundableList > createParentBoundables (BoundableList *childBoundables, int newLevel)
virtual AbstractNode * lastNode (BoundableList *nodeList)
virtual AbstractNode * getRoot ()
virtual void insert (const void *bounds, void *item)
Also builds the tree, if necessary.
void query (const void *searchBounds, std::vector< void * > &foundItems)
Also builds the tree, if necessary.
void query (const void *searchBounds, ItemVisitor &visitor)
Also builds the tree, if necessary.
void query (const void *searchBounds, const AbstractNode &node, ItemVisitor &visitor)
bool remove (const void *itemEnv, void *item)
Also builds the tree, if necessary.
std::unique_ptr< BoundableList > boundablesAtLevel (int level)
virtual IntersectsOp * getIntersectsOp ()=0
Protected Attributes
AbstractNode * root
std::vector< AbstractNode * > * nodes
std::size_t nodeCapacity
Private Member Functions
virtual AbstractNode * createHigherLevels (BoundableList *boundablesOfALevel, int level)
virtual std::unique_ptr< BoundableList > sortBoundables (const BoundableList *input)=0
bool remove (const void *searchBounds, AbstractNode &node, void *item)
bool removeItem (AbstractNode &node, void *item)
ItemsList * itemsTree (AbstractNode *node)
Private Attributes
bool built
BoundableList * itemBoundables
Detailed Description
Base class for STRtree and SIRtree.
STR-packed R-trees are described in: P. Rigaux, Michel Scholl and Agnes Voisard. Spatial Databases With Application To GIS. Morgan Kaufmann, San Francisco, 2002.
This implementation is based on Boundables rather than just AbstractNodes, because the STR algorithm operates on both nodes and data, both of which are treated here as Boundables.
Definition at line 132 of file AbstractSTRtree.h.
Constructor & Destructor Documentation
geos::index::strtree::AbstractSTRtree::AbstractSTRtree (std::size_t newNodeCapacity) inline
Constructs an AbstractSTRtree with the specified maximum number of child nodes that a node may have
Definition at line 250 of file AbstractSTRtree.h.
Referenced by geos::index::strtree::SIRtree::SIRtree().
     :
     built(false),
     itemBoundables(new BoundableList()),
     nodes(new std::vector<AbstractNode *>()),
     nodeCapacity(newNodeCapacity)
   {
     assert(newNodeCapacity>1);
   }
geos::index::strtree::AbstractSTRtree::~AbstractSTRtree () virtual
Definition at line 34 of file AbstractSTRtree.cpp.
 {
   assert(nullptr != itemBoundables);
     BoundableList::iterator it = itemBoundables->begin();
     BoundableList::iterator end = itemBoundables->end();
   while (it != end)
   {
     delete *it;
         ++it;
   }
   delete itemBoundables;
   assert(nullptr != nodes);
   for (std::size_t i = 0, nsize = nodes->size(); i < nsize; i++)
     {
     delete (*nodes)[i];
     }
   delete nodes;
 }
Member Function Documentation
std::unique_ptr< BoundableList > geos::index::strtree::AbstractSTRtree::boundablesAtLevel (int level) protected
Definition at line 308 of file AbstractSTRtree.cpp.
 {
   std::unique_ptr<BoundableList> boundables ( new BoundableList() );
   boundablesAtLevel(level, root, boundables.get());
   return boundables;
 }
void geos::index::strtree::AbstractSTRtree::boundablesAtLevel (int level, AbstractNode * top, BoundableList * boundables) virtual
Parameters
level -1 to get items
Definition at line 317 of file AbstractSTRtree.cpp.
References geos::index::strtree::AbstractNode::getChildBoundables(), and geos::index::strtree::AbstractNode::getLevel().
 {
   assert(level>-2);
   if (top->getLevel()==level)
   {
     boundables->push_back(top);
     return;
   }
   assert(top);
   const BoundableList& vb = *(top->getChildBoundables());
   for(BoundableList::const_iterator i=vb.begin(), e=vb.end();
       i!=e; ++i)
   {
     Boundable* boundable=*i;
     if (typeid(*boundable)==typeid(AbstractNode))
     {
       boundablesAtLevel(level, (AbstractNode*)boundable,
         boundables);
     }
     else
     {
       assert(typeid(*boundable)==typeid(ItemBoundable));
       if (level==-1)
       {
         boundables->push_back(boundable);
       }
     }
   }
   return;
 }
void geos::index::strtree::AbstractSTRtree::build () virtual
Creates parent nodes, grandparent nodes, and so forth up to the root node, for the data that has been inserted into the tree. Can only be called once, and thus can be called only after all of the data has been inserted into the tree.
Definition at line 56 of file AbstractSTRtree.cpp.
Referenced by geos::index::strtree::STRtree::nearestNeighbour().
 {
   if(built)
     return;
   root=(itemBoundables->empty()?createNode(0):createHigherLevels(itemBoundables,-1));
   built=true;
 }
static bool geos::index::strtree::AbstractSTRtree::compareDoubles (double a, double b) inline static
Definition at line 260 of file AbstractSTRtree.h.
{
     // NOTE - strk:
     // Ternary operation is a workaround for
     // a probable MingW bug, see
     // http://trac.osgeo.org/geos/ticket/293
     return ( a < b ) ? true : false;
   }
AbstractNode * geos::index::strtree::AbstractSTRtree::createHigherLevels (BoundableList * boundablesOfALevel, int level) private virtual
Creates the levels higher than the given level
Parameters
boundablesOfALevel the level to build on
level the level of the Boundables, or -1 if the boundables are item boundables (that is, below level 0)
Returns
the root, which may be a ParentNode or a LeafNode
Definition at line 96 of file AbstractSTRtree.cpp.
 {
   assert(!boundablesOfALevel->empty());
   std::unique_ptr< BoundableList > parentBoundables (
       createParentBoundables(boundablesOfALevel,level+1)
       );
   if (parentBoundables->size()==1)
   {
     // Cast from Boundable to AbstractNode
     AbstractNode *ret = static_cast<AbstractNode*>(parentBoundables->front());
     return ret;
   }
   AbstractNode *ret = createHigherLevels(parentBoundables.get(), level+1);
   return ret;
 }
virtual AbstractNode* geos::index::strtree::AbstractSTRtree::createNode (int level) protected pure virtual
Implemented in geos::index::strtree::STRtree, and geos::index::strtree::SIRtree.
std::unique_ptr< BoundableList > geos::index::strtree::AbstractSTRtree::createParentBoundables (BoundableList * childBoundables, int newLevel) protected virtual
Sorts the childBoundables then divides them into groups of size M, where M is the node capacity.
Reimplemented in geos::index::strtree::SIRtree, and geos::index::strtree::STRtree.
Definition at line 67 of file AbstractSTRtree.cpp.
References geos::index::strtree::AbstractNode::addChildBoundable(), and geos::index::strtree::AbstractNode::getChildBoundables().
Referenced by geos::index::strtree::STRtree::createParentBoundablesFromVerticalSlice().
 {
   assert(!childBoundables->empty());
   std::unique_ptr< BoundableList > parentBoundables ( new BoundableList() );
   parentBoundables->push_back(createNode(newLevel));
   std::unique_ptr< BoundableList > sortedChildBoundables ( sortBoundables(childBoundables) );
   for (BoundableList::iterator i=sortedChildBoundables->begin(),
       e=sortedChildBoundables->end();
       i!=e; i++)
   //for(std::size_t i=0, scbsize=sortedChildBoundables->size(); i<scbsize; ++i)
   {
     Boundable *childBoundable=*i; // (*sortedChildBoundables)[i];
     AbstractNode *last = lastNode(parentBoundables.get());
     if (last->getChildBoundables()->size() == nodeCapacity)
     {
       last=createNode(newLevel);
       parentBoundables->push_back(last);
     }
     last->addChildBoundable(childBoundable);
   }
   return parentBoundables;
 }
virtual IntersectsOp* geos::index::strtree::AbstractSTRtree::getIntersectsOp () protected pure virtual
Returns
a test for intersection between two bounds, necessary because subclasses of AbstractSTRtree have different implementations of bounds.
See also
IntersectsOp
Implemented in geos::index::strtree::STRtree, and geos::index::strtree::SIRtree.
virtual std::size_t geos::index::strtree::AbstractSTRtree::getNodeCapacity () inline virtual
Returns the maximum number of child nodes that a node may have
Definition at line 281 of file AbstractSTRtree.h.
Referenced by geos::index::strtree::STRtree::createParentBoundables().
 { return nodeCapacity; }
virtual AbstractNode* geos::index::strtree::AbstractSTRtree::getRoot () inline protected virtual
Definition at line 203 of file AbstractSTRtree.h.
Referenced by geos::index::strtree::STRtree::nearestNeighbour().
{
                 assert(built);
     return root;
   }
void geos::index::strtree::AbstractSTRtree::insert (const void * bounds, void * item) protected virtual
Also builds the tree, if necessary.
Definition at line 115 of file AbstractSTRtree.cpp.
Referenced by geos::index::strtree::SIRtree::insert(), and geos::index::strtree::STRtree::insert().
 {
   // Cannot insert items into an STR packed R-tree after it has been built
   assert(!built);
   itemBoundables->push_back(new ItemBoundable(bounds,item));
 }
ItemsList * geos::index::strtree::AbstractSTRtree::itemsTree (AbstractNode * node) private
Definition at line 352 of file AbstractSTRtree.cpp.
References geos::index::strtree::AbstractNode::getChildBoundables().
 {
     std::unique_ptr<ItemsList> valuesTreeForNode (new ItemsList());
     BoundableList::iterator end = node->getChildBoundables()->end();
     for (BoundableList::iterator i = node->getChildBoundables()->begin();
          i != end; ++i)
     {
         Boundable* childBoundable = *i;
         if (dynamic_cast<AbstractNode*>(childBoundable)) {
             ItemsList* valuesTreeForChild =
                 itemsTree(static_cast<AbstractNode*>(childBoundable));
             // only add if not null (which indicates an item somewhere in this tree
             if (valuesTreeForChild != nullptr)
                 valuesTreeForNode->push_back_owned(valuesTreeForChild);
         }
         else if (dynamic_cast<ItemBoundable*>(childBoundable)) {
             valuesTreeForNode->push_back(
                 static_cast<ItemBoundable*>(childBoundable)->getItem());
         }
         else {
             assert(!static_cast<bool>("should never be reached"));
         }
     }
     if (valuesTreeForNode->empty())
         return nullptr;
     return valuesTreeForNode.release();
 }
ItemsList * geos::index::strtree::AbstractSTRtree::itemsTree ()
Gets a tree structure (as a nested list) corresponding to the structure of the items and nodes in this tree.
The returned Lists contain either Object items, or Lists which correspond to subtrees of the tree Subtrees which do not contain any items are not included.
Builds the tree if necessary.
Note
The caller is responsible for releasing the list
Returns
a List of items and/or Lists
Definition at line 382 of file AbstractSTRtree.cpp.
Referenced by geos::operation::geounion::CascadedUnion::Union(), and geos::operation::geounion::CascadedPolygonUnion::Union().
 {
     if (!built) {
         build();
     }
     ItemsList* valuesTree (itemsTree(root));
     if (valuesTree == nullptr)
         return new ItemsList();
     return valuesTree;
 }
void geos::index::strtree::AbstractSTRtree::iterate (ItemVisitor & visitor)
Iterate over all items added thus far. Explicitly does not build the tree.
Definition at line 293 of file AbstractSTRtree.cpp.
References geos::index::ItemVisitor::visitItem().
Referenced by geos::precision::MinimumClearance::compute(), and GEOSSTRtree_iterate_r().
 {
     for (BoundableList::const_iterator i=itemBoundables->begin(), e=itemBoundables->end();
       i!=e; i++)
   {
     const Boundable* boundable = *i;
     if (const ItemBoundable *ib=dynamic_cast<const ItemBoundable *>(boundable))
     {
       visitor.visitItem(ib->getItem());
     }
         }
 }
virtual AbstractNode* geos::index::strtree::AbstractSTRtree::lastNode (BoundableList * nodeList) inline protected virtual
Definition at line 196 of file AbstractSTRtree.h.
   {
     assert(!nodeList->empty());
     // Cast from Boundable to AbstractNode
     return static_cast<AbstractNode*>(nodeList->back() );
   }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, std::vector< void * > & foundItems) protected
Also builds the tree, if necessary.
Definition at line 124 of file AbstractSTRtree.cpp.
Referenced by geos::index::strtree::SIRtree::query(), and geos::index::strtree::STRtree::query().
 {
   if (!built) build();
   if (itemBoundables->empty()) assert(root->getBounds()==nullptr);
   if (getIntersectsOp()->intersects(root->getBounds(), searchBounds))
   {
     query(searchBounds,root, &matches);
   }
 }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, ItemVisitor & visitor) protected
Also builds the tree, if necessary.
Definition at line 138 of file AbstractSTRtree.cpp.
 {
   if (!built) build();
   if (itemBoundables->empty()) assert(root->getBounds()==nullptr);
   if (getIntersectsOp()->intersects(root->getBounds(),searchBounds))
   {
     query(searchBounds, *root, visitor);
   }
 }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, const AbstractNode & node, ItemVisitor & visitor) protected
Definition at line 152 of file AbstractSTRtree.cpp.
References geos::index::strtree::Boundable::getBounds(), geos::index::strtree::AbstractNode::getChildBoundables(), and geos::index::ItemVisitor::visitItem().
 {
   const BoundableList& boundables = *(node.getChildBoundables());
   for (BoundableList::const_iterator i=boundables.begin(), e=boundables.end();
       i!=e; i++)
   {
     const Boundable* childBoundable = *i;
     if (!getIntersectsOp()->intersects(childBoundable->getBounds(), searchBounds)) {
       continue;
     }
     if(const AbstractNode *an=dynamic_cast<const AbstractNode*>(childBoundable))
     {
       query(searchBounds, *an, visitor);
     }
     else if (const ItemBoundable *ib=dynamic_cast<const ItemBoundable *>(childBoundable))
     {
       visitor.visitItem(ib->getItem());
     }
     else
     {
       assert(0); // unsupported childBoundable type
     }
   }
 }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, const AbstractNode * node, std::vector< void * > * matches) virtual
Definition at line 257 of file AbstractSTRtree.cpp.
References geos::index::strtree::Boundable::getBounds(), geos::index::strtree::AbstractNode::getChildBoundables(), and geos::index::strtree::AbstractSTRtree::IntersectsOp::intersects().
 {
   assert(node);
   const BoundableList& vb = *(node->getChildBoundables());
   IntersectsOp *io=getIntersectsOp();
   //std::size_t vbsize=vb.size();
   //cerr<<"AbstractSTRtree::query: childBoundables: "<<vbsize<<endl;
   for(BoundableList::const_iterator i=vb.begin(), e=vb.end();
       i!=e; ++i)
   {
     const Boundable* childBoundable=*i;
     if (!io->intersects(childBoundable->getBounds(), searchBounds))
     {
       continue;
     }
     if(const AbstractNode *an=dynamic_cast<const AbstractNode*>(childBoundable))
     {
       query(searchBounds, an, matches);
     }
     else if (const ItemBoundable *ib=dynamic_cast<const ItemBoundable *>(childBoundable))
     {
       matches->push_back(ib->getItem());
     }
     else
     {
       assert(0); // unsupported childBoundable type
     }
   }
 }
bool geos::index::strtree::AbstractSTRtree::remove (const void * searchBounds, AbstractNode & node, void * item) private
Definition at line 197 of file AbstractSTRtree.cpp.
References geos::index::strtree::Boundable::getBounds(), and geos::index::strtree::AbstractNode::getChildBoundables().
Referenced by geos::index::strtree::STRtree::remove().
 {
   // first try removing item from this node
   if ( removeItem(node, item) ) return true;
   BoundableList& boundables = *(node.getChildBoundables());
   // next try removing item from lower nodes
   for (BoundableList::iterator i=boundables.begin(), e=boundables.end();
       i!=e; i++)
   {
     Boundable* childBoundable = *i;
     if (!getIntersectsOp()->intersects(childBoundable->getBounds(), searchBounds))
       continue;
     if (AbstractNode *an=dynamic_cast<AbstractNode*>(childBoundable))
     {
       // if found, record child for pruning and exit
       if ( remove(searchBounds, *an, item) )
       {
         if (an->getChildBoundables()->empty()) {
           boundables.erase(i);
         }
         return true;
       }
     }
   }
   return false;
 }
bool geos::index::strtree::AbstractSTRtree::remove (const void * itemEnv, void * item) protected
Also builds the tree, if necessary.
Definition at line 183 of file AbstractSTRtree.cpp.
 {
   if (!built) build();
   if (itemBoundables->empty()) {
     assert(root->getBounds() == nullptr);
   }
   if (getIntersectsOp()->intersects(root->getBounds(), searchBounds)) {
     return remove(searchBounds, *root, item);
   }
   return false;
 }
bool geos::index::strtree::AbstractSTRtree::removeItem (AbstractNode & node, void * item) private
Definition at line 230 of file AbstractSTRtree.cpp.
References geos::index::strtree::AbstractNode::getChildBoundables().
 {
   BoundableList& boundables = *(node.getChildBoundables());
   BoundableList::iterator childToRemove = boundables.end();
   for (BoundableList::iterator i=boundables.begin(),
       e=boundables.end();
       i!=e; i++)
   {
     Boundable* childBoundable = *i;
     if (ItemBoundable *ib=dynamic_cast<ItemBoundable*>(childBoundable))
     {
       if ( ib->getItem() == item) childToRemove = i;
     }
   }
   if (childToRemove != boundables.end()) {
     boundables.erase(childToRemove);
     return true;
   }
   return false;
 }
virtual std::unique_ptr<BoundableList> geos::index::strtree::AbstractSTRtree::sortBoundables (const BoundableList * input) private pure virtual
Implemented in geos::index::strtree::SIRtree, and geos::index::strtree::STRtree.
Member Data Documentation
bool geos::index::strtree::AbstractSTRtree::built private
Definition at line 135 of file AbstractSTRtree.h.
BoundableList* geos::index::strtree::AbstractSTRtree::itemBoundables private
Definition at line 136 of file AbstractSTRtree.h.
std::size_t geos::index::strtree::AbstractSTRtree::nodeCapacity protected
Definition at line 233 of file AbstractSTRtree.h.
Referenced by geos::index::strtree::STRtree::createNode(), and geos::index::strtree::SIRtree::SIRtree().
std::vector<AbstractNode *>* geos::index::strtree::AbstractSTRtree::nodes protected
Definition at line 184 of file AbstractSTRtree.h.
Referenced by geos::index::strtree::SIRtree::createNode(), and geos::index::strtree::STRtree::createNode().
AbstractNode* geos::index::strtree::AbstractSTRtree::root protected
Definition at line 182 of file AbstractSTRtree.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/strtree/AbstractSTRtree.h
/home/vicky/potree/geos/vicky/src/index/strtree/AbstractSTRtree.cpp