GEOS: geos::precision::CommonBitsOp Class Reference
geos::precision::CommonBitsOp Class Reference
Provides versions of Geometry spatial functions which use common bit removal to reduce the likelihood of robustness problems.
#include <CommonBitsOp.h>
Public Member Functions
CommonBitsOp ()
CommonBitsOp (bool nReturnToOriginalPrecision)
geom::Geometry * intersection (const geom::Geometry *geom0, const geom::Geometry *geom1)
geom::Geometry * Union (const geom::Geometry *geom0, const geom::Geometry *geom1)
geom::Geometry * difference (const geom::Geometry *geom0, const geom::Geometry *geom1)
geom::Geometry * symDifference (const geom::Geometry *geom0, const geom::Geometry *geom1)
geom::Geometry * buffer (const geom::Geometry *geom0, double distance)
geom::Geometry * computeResultPrecision (geom::Geometry *result)
Private Member Functions
geom::Geometry * removeCommonBits (const geom::Geometry *geom0)
Computes a copy of the input Geometry with the calculated common bits removed from each coordinate.
void removeCommonBits (const geom::Geometry *geom0, const geom::Geometry *geom1, std::unique_ptr< geom::Geometry > &rgeom0, std::unique_ptr< geom::Geometry > &rgeom1)
Private Attributes
bool returnToOriginalPrecision
std::unique_ptr< CommonBitsRemover > cbr
Detailed Description
Provides versions of Geometry spatial functions which use common bit removal to reduce the likelihood of robustness problems.
In the current implementation no rounding is performed on the reshifted result geometry, which means that it is possible that the returned Geometry is invalid. Client classes should check the validity of the returned result themselves.
Definition at line 50 of file CommonBitsOp.h.
Constructor & Destructor Documentation
geos::precision::CommonBitsOp::CommonBitsOp ()
Creates a new instance of class, which reshifts result Geometry
Definition at line 40 of file CommonBitsOp.cpp.
   :
   returnToOriginalPrecision(true)
 {
 #if GEOS_DEBUG
   std::cerr << "CommonBitsOp[" << this
             << "]::CommonBitsOp()" << std::endl;
 #endif
 }
geos::precision::CommonBitsOp::CommonBitsOp (bool nReturnToOriginalPrecision)
Creates a new instance of class, specifying whether the result Geometrys should be reshifted.
Parameters
returnToOriginalPrecision
Definition at line 52 of file CommonBitsOp.cpp.
   :
   returnToOriginalPrecision(nReturnToOriginalPrecision)
 {
 #if GEOS_DEBUG
   std::cerr << "CommonBitsOp[" << this
             << "]::CommonBitsOp(bool "
       << nReturnToOriginalPrecision << ")"
       << std::endl;
 #endif
 }
Member Function Documentation
Geometry * geos::precision::CommonBitsOp::buffer (const geom::Geometry * geom0, double distance)
Computes the buffer a geometry, using enhanced precision.
Parameters
geom0 the Geometry to buffer
distance the buffer distance
Returns
the Geometry representing the buffer of the input Geometry.
Definition at line 114 of file CommonBitsOp.cpp.
References computeResultPrecision(), and removeCommonBits().
Referenced by geos::precision::EnhancedPrecisionOp::buffer().
 {
   unique_ptr<Geometry> rgeom0(removeCommonBits(geom0));
   return computeResultPrecision(rgeom0->buffer(distance));
 }
Geometry * geos::precision::CommonBitsOp::computeResultPrecision (geom::Geometry * result)
If required, returning the result to the orginal precision if required.
In this current implementation, no rounding is performed on the reshifted result geometry, which means that it is possible that the returned Geometry is invalid.
Parameters
result the result Geometry to modify
Returns
the result Geometry with the required precision
Definition at line 122 of file CommonBitsOp.cpp.
References cbr, and returnToOriginalPrecision.
Referenced by buffer(), difference(), intersection(), symDifference(), and Union().
 {
   assert(cbr.get());
   if (returnToOriginalPrecision)
     cbr->addCommonBits(result);
   return result;
 }
Geometry * geos::precision::CommonBitsOp::difference (const geom::Geometry * geom0, const geom::Geometry * geom1)
Computes the set-theoretic difference of two Geometry, using enhanced precision.
Parameters
geom0 the first Geometry
geom1 the second Geometry, to be subtracted from the first
Returns
the Geometry representing the set-theoretic difference of the input Geometries.
Definition at line 90 of file CommonBitsOp.cpp.
References computeResultPrecision(), and removeCommonBits().
Referenced by geos::precision::EnhancedPrecisionOp::difference().
 {
   unique_ptr<Geometry> rgeom0;
   unique_ptr<Geometry> rgeom1;
   removeCommonBits(geom0, geom1, rgeom0, rgeom1);
   return computeResultPrecision(rgeom0->difference(rgeom1.get()));
 }
Geometry * geos::precision::CommonBitsOp::intersection (const geom::Geometry * geom0, const geom::Geometry * geom1)
Computes the set-theoretic intersection of two Geometry, using enhanced precision.
Parameters
geom0 the first Geometry
geom1 the second Geometry
Returns
the Geometry representing the set-theoretic intersection of the input Geometries.
Definition at line 66 of file CommonBitsOp.cpp.
References computeResultPrecision(), and removeCommonBits().
Referenced by geos::precision::EnhancedPrecisionOp::intersection().
 {
   unique_ptr<Geometry> rgeom0;
   unique_ptr<Geometry> rgeom1;
   removeCommonBits(geom0, geom1, rgeom0, rgeom1);
   return computeResultPrecision(rgeom0->intersection(rgeom1.get()));
 }
Geometry * geos::precision::CommonBitsOp::removeCommonBits (const geom::Geometry * geom0) private
Computes a copy of the input Geometry with the calculated common bits removed from each coordinate.
Parameters
geom0 the Geometry to remove common bits from
Returns
a copy of the input Geometry with common bits removed (caller takes responsibility of its deletion)
Definition at line 132 of file CommonBitsOp.cpp.
References cbr, geos::geom::Geometry::clone(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by buffer(), difference(), intersection(), symDifference(), and Union().
 {
   cbr.reset(new CommonBitsRemover());
   cbr->add(geom0);
 #if GEOS_DEBUG
   const Coordinate& commonCoord = cbr->getCommonCoordinate();
   cerr << "CommonBitsRemover bits: " << commonCoord.x << ", " << commonCoord.y << endl;
 #endif
   Geometry* geom=cbr->removeCommonBits(geom0->clone());
   return geom;
 }
void geos::precision::CommonBitsOp::removeCommonBits (const geom::Geometry * geom0, const geom::Geometry * geom1, std::unique_ptr< geom::Geometry > & rgeom0, std::unique_ptr< geom::Geometry > & rgeom1) private
Geometry * geos::precision::CommonBitsOp::symDifference (const geom::Geometry * geom0, const geom::Geometry * geom1)
Computes the set-theoretic symmetric difference of two geometries, using enhanced precision.
Parameters
geom0 the first Geometry
geom1 the second Geometry
Returns
the Geometry representing the set-theoretic symmetric difference of the input Geometries.
Definition at line 102 of file CommonBitsOp.cpp.
References computeResultPrecision(), and removeCommonBits().
Referenced by geos::precision::EnhancedPrecisionOp::symDifference().
 {
   unique_ptr<Geometry> rgeom0;
   unique_ptr<Geometry> rgeom1;
   removeCommonBits(geom0, geom1, rgeom0, rgeom1);
   return computeResultPrecision(rgeom0->symDifference(rgeom1.get()));
 }
Geometry * geos::precision::CommonBitsOp::Union (const geom::Geometry * geom0, const geom::Geometry * geom1)
Computes the set-theoretic union of two Geometry, using enhanced precision.
Parameters
geom0 the first Geometry
geom1 the second Geometry
Returns
the Geometry representing the set-theoretic union of the input Geometries.
Definition at line 78 of file CommonBitsOp.cpp.
References computeResultPrecision(), and removeCommonBits().
Referenced by geos::precision::EnhancedPrecisionOp::Union().
 {
   unique_ptr<Geometry> rgeom0;
   unique_ptr<Geometry> rgeom1;
   removeCommonBits(geom0, geom1, rgeom0, rgeom1);
   return computeResultPrecision(rgeom0->Union(rgeom1.get()));
 }
Member Data Documentation
std::unique_ptr<CommonBitsRemover> geos::precision::CommonBitsOp::cbr private
Definition at line 56 of file CommonBitsOp.h.
Referenced by computeResultPrecision(), and removeCommonBits().
bool geos::precision::CommonBitsOp::returnToOriginalPrecision private
Definition at line 54 of file CommonBitsOp.h.
Referenced by computeResultPrecision().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/precision/CommonBitsOp.h
/home/vicky/potree/geos/vicky/src/precision/CommonBitsOp.cpp