GEOS: geos::index::sweepline::SweepLineInterval Class Reference
geos::index::sweepline::SweepLineInterval Class Reference
#include <SweepLineInterval.h>
Public Member Functions
SweepLineInterval (double newMin, double newMax, void *newItem=nullptr)
double getMin ()
double getMax ()
void * getItem ()
Private Attributes
double min
double max
void * item
Detailed Description
Definition at line 24 of file SweepLineInterval.h.
Constructor & Destructor Documentation
geos::index::sweepline::SweepLineInterval::SweepLineInterval (double newMin, double newMax, void * newItem = nullptr)
Definition at line 22 of file SweepLineInterval.cpp.
References item, max, and min.
 {
   min=newMin<newMax?newMin:newMax;
   max=newMax>newMin?newMax:newMin;
   item=newItem;
 }
Member Function Documentation
void * geos::index::sweepline::SweepLineInterval::getItem ()
Definition at line 42 of file SweepLineInterval.cpp.
References item.
Referenced by geos::operation::valid::SweeplineNestedRingTester::OverlapAction::overlap().
 {
   return item;
 }
double geos::index::sweepline::SweepLineInterval::getMax ()
Definition at line 36 of file SweepLineInterval.cpp.
References max.
Referenced by geos::index::sweepline::SweepLineIndex::add().
 {
   return max;
 }
double geos::index::sweepline::SweepLineInterval::getMin ()
Definition at line 30 of file SweepLineInterval.cpp.
References min.
Referenced by geos::index::sweepline::SweepLineIndex::add().
 {
   return min;
 }
Member Data Documentation
void* geos::index::sweepline::SweepLineInterval::item private
Definition at line 32 of file SweepLineInterval.h.
Referenced by getItem(), and SweepLineInterval().
double geos::index::sweepline::SweepLineInterval::max private
Definition at line 31 of file SweepLineInterval.h.
Referenced by getMax(), and SweepLineInterval().
double geos::index::sweepline::SweepLineInterval::min private
Definition at line 31 of file SweepLineInterval.h.
Referenced by getMin(), and SweepLineInterval().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/sweepline/SweepLineInterval.h
/home/vicky/potree/geos/vicky/src/index/sweepline/SweepLineInterval.cpp