GEOS: geos::planargraph::PlanarGraph Class Reference
geos::planargraph::PlanarGraph Class Reference
Represents a directed graph which is embeddable in a planar surface.
#include <geos/planargraph.h>
Public Types
typedef std::vector< Edge * > EdgeContainer
typedef EdgeContainer::iterator EdgeIterator
Public Member Functions
PlanarGraph ()
Constructs a PlanarGraph without any Edges, DirectedEdges, or Nodes.
virtual ~PlanarGraph ()
Node * findNode (const geom::Coordinate &pt)
Returns the Node at the given location, or null if no Node was there.
NodeMap::container::iterator nodeIterator ()
Returns an Iterator over the Nodes in this PlanarGraph.
NodeMap::container::iterator nodeBegin ()
NodeMap::container::const_iterator nodeBegin () const
NodeMap::container::iterator nodeEnd ()
NodeMap::container::const_iterator nodeEnd () const
void getNodes (std::vector< Node * > &nodes) const
Returns the Nodes in this PlanarGraph.
std::vector< DirectedEdge * >::iterator dirEdgeIterator ()
Returns an Iterator over the DirectedEdges in this PlanarGraph, in the order in which they were added.
std::vector< Edge * >::iterator edgeIterator ()
Alias for edgeBegin()
std::vector< Edge * >::iterator edgeBegin ()
Returns an iterator to first Edge in this graph.
std::vector< Edge * >::iterator edgeEnd ()
Returns an iterator to one-past last Edge in this graph.
std::vector< Edge * > * getEdges ()
Returns the Edges that have been added to this PlanarGraph.
void remove (Edge *edge)
Removes an Edge and its associated DirectedEdges from their from-Nodes and from this PlanarGraph.
void remove (DirectedEdge *de)
Removes DirectedEdge from its from-Node and from this PlanarGraph.
void remove (Node *node)
Removes a node from the graph, along with any associated DirectedEdges and Edges.
std::vector< Node * > findNodesOfDegree (std::size_t degree) const
Returns all Nodes with the given number of Edges around it. The return value is a newly allocated vector of existing nodes.
void findNodesOfDegree (std::size_t degree, std::vector< Node * > &to) const
Get all Nodes with the given number of Edges around it.
Protected Member Functions
void add (Node *node)
Adds a node to the std::map, replacing any that is already at that location.
void add (Edge *edge)
Adds the Edge and its DirectedEdges with this PlanarGraph.
void add (DirectedEdge *dirEdge)
Adds the Edge to this PlanarGraph.
Protected Attributes
std::vector< Edge * > edges
std::vector< DirectedEdge * > dirEdges
NodeMap nodeMap
Detailed Description
Represents a directed graph which is embeddable in a planar surface.
This class and the other classes in this package serve as a framework for building planar graphs for specific algorithms. This class must be subclassed to expose appropriate methods to construct the graph. This allows controlling the types of graph components (DirectedEdge, Edge and Node) which can be added to the graph. An application which uses the graph framework will almost always provide subclasses for one or more graph components, which hold application-specific data and graph algorithms.
Definition at line 60 of file PlanarGraph.h.
Member Typedef Documentation
typedef std::vector<Edge *> geos::planargraph::PlanarGraph::EdgeContainer
Definition at line 105 of file PlanarGraph.h.
typedef EdgeContainer::iterator geos::planargraph::PlanarGraph::EdgeIterator
Definition at line 106 of file PlanarGraph.h.
Constructor & Destructor Documentation
geos::planargraph::PlanarGraph::PlanarGraph () inline
Constructs a PlanarGraph without any Edges, DirectedEdges, or Nodes.
Definition at line 113 of file PlanarGraph.h.
 {}
virtual geos::planargraph::PlanarGraph::~PlanarGraph () inline virtual
Definition at line 115 of file PlanarGraph.h.
 {}
Member Function Documentation
void geos::planargraph::PlanarGraph::add (Node * node) inline protected
Adds a node to the std::map, replacing any that is already at that location.
Only subclasses can add Nodes, to ensure Nodes are of the right type.
Returns
the added node
Definition at line 77 of file PlanarGraph.h.
References geos::planargraph::NodeMap::add().
Referenced by geos::operation::polygonize::PolygonizeGraph::addEdge(), and geos::operation::polygonize::PolygonizeGraph::getNode().
{
     nodeMap.add(node);
   }
void geos::planargraph::PlanarGraph::add (Edge * edge) protected
Adds the Edge and its DirectedEdges with this PlanarGraph.
Assumes that the Edge has already been created with its associated DirectEdges. Only subclasses can add Edges, to ensure the edges added are of the right class.
Definition at line 51 of file PlanarGraph.cpp.
References geos::planargraph::Edge::getDirEdge().
 {
   edges.push_back(edge);
   add(edge->getDirEdge(0));
   add(edge->getDirEdge(1));
 }
void geos::planargraph::PlanarGraph::add (DirectedEdge * dirEdge) inline protected
Adds the Edge to this PlanarGraph.
Only subclasses can add DirectedEdges, to ensure the edges added are of the right class.
Definition at line 99 of file PlanarGraph.h.
{
     dirEdges.push_back(dirEdge);
   }
std::vector<DirectedEdge*>::iterator geos::planargraph::PlanarGraph::dirEdgeIterator () inline
Returns an Iterator over the DirectedEdges in this PlanarGraph, in the order in which they were added.
See also
add(Edge)
add(DirectedEdge)
Definition at line 166 of file PlanarGraph.h.
{
     return dirEdges.begin();
   }
std::vector<Edge*>::iterator geos::planargraph::PlanarGraph::edgeBegin () inline
Returns an iterator to first Edge in this graph.
Edges are stored in the order they were added.
See also
add(Edge)
Definition at line 180 of file PlanarGraph.h.
{
     return edges.begin();
   }
std::vector<Edge*>::iterator geos::planargraph::PlanarGraph::edgeEnd () inline
Returns an iterator to one-past last Edge in this graph.
Edges are stored in the order they were added.
See also
add(Edge)
Definition at line 189 of file PlanarGraph.h.
Referenced by geos::operation::linemerge::LineMerger::merge().
{
     return edges.end();
   }
std::vector<Edge*>::iterator geos::planargraph::PlanarGraph::edgeIterator () inline
Alias for edgeBegin()
Definition at line 171 of file PlanarGraph.h.
Referenced by geos::operation::linemerge::LineMerger::merge().
{
     return edges.begin();
   }
Node* geos::planargraph::PlanarGraph::findNode (const geom::Coordinate & pt) inline
Returns the Node at the given location, or null if no Node was there.
Definition at line 122 of file PlanarGraph.h.
References geos::planargraph::NodeMap::find().
Referenced by geos::operation::polygonize::PolygonizeGraph::getNode().
{
     return nodeMap.find(pt);
   }
std::vector<Node*> geos::planargraph::PlanarGraph::findNodesOfDegree (std::size_t degree) const
Returns all Nodes with the given number of Edges around it. The return value is a newly allocated vector of existing nodes.
Referenced by geos::operation::polygonize::PolygonizeGraph::deleteDangles().
void geos::planargraph::PlanarGraph::findNodesOfDegree (std::size_t degree, std::vector< Node * > & to) const
Get all Nodes with the given number of Edges around it.
Found nodes are pushed to the given vector
std::vector<Edge*>* geos::planargraph::PlanarGraph::getEdges () inline
Returns the Edges that have been added to this PlanarGraph.
See also
#add(Edge)
Definition at line 198 of file PlanarGraph.h.
{
     return &edges;
   }
void geos::planargraph::PlanarGraph::getNodes (std::vector< Node * > & nodes) const inline
Returns the Nodes in this PlanarGraph.
Parameters
nodes : the nodes are push_back'ed here
Definition at line 156 of file PlanarGraph.h.
References geos::planargraph::NodeMap::getNodes().
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForNonDegree2Nodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), and geos::operation::polygonize::PolygonizeGraph::computeNextCWEdges().
 { nodes = nodeMap.getNodes(); }
NodeMap::container::iterator geos::planargraph::PlanarGraph::nodeBegin () inline
Definition at line 134 of file PlanarGraph.h.
References geos::planargraph::NodeMap::begin().
{
     return nodeMap.begin();
   }
NodeMap::container::const_iterator geos::planargraph::PlanarGraph::nodeBegin () const inline
Definition at line 138 of file PlanarGraph.h.
References geos::planargraph::NodeMap::begin().
{
     return nodeMap.begin();
   }
NodeMap::container::iterator geos::planargraph::PlanarGraph::nodeEnd () inline
Definition at line 142 of file PlanarGraph.h.
References geos::planargraph::NodeMap::end().
Referenced by geos::operation::linemerge::LineMerger::merge().
{
     return nodeMap.end();
   }
NodeMap::container::const_iterator geos::planargraph::PlanarGraph::nodeEnd () const inline
Definition at line 146 of file PlanarGraph.h.
References geos::planargraph::NodeMap::end().
{
     return nodeMap.end();
   }
NodeMap::container::iterator geos::planargraph::PlanarGraph::nodeIterator () inline
Returns an Iterator over the Nodes in this PlanarGraph.
Definition at line 130 of file PlanarGraph.h.
References geos::planargraph::NodeMap::begin().
Referenced by geos::operation::linemerge::LineMerger::merge().
{
     return nodeMap.begin();
   }
void geos::planargraph::PlanarGraph::remove (Edge * edge)
Removes an Edge and its associated DirectedEdges from their from-Nodes and from this PlanarGraph.
Note: This method does not remove the Nodes associated with the Edge, even if the removal of the Edge reduces the degree of a Node to zero.
Definition at line 66 of file PlanarGraph.cpp.
References geos::planargraph::find_and_erase(), and geos::planargraph::Edge::getDirEdge().
 {
   remove(edge->getDirEdge(0));
   remove(edge->getDirEdge(1));
   find_and_erase(edge, edges);
 }
void geos::planargraph::PlanarGraph::remove (DirectedEdge * de)
Removes DirectedEdge from its from-Node and from this PlanarGraph.
Note: This method does not remove the Nodes associated with the DirectedEdge, even if the removal of the DirectedEdge reduces the degree of a Node to zero.
Definition at line 80 of file PlanarGraph.cpp.
References geos::planargraph::find_and_erase(), geos::planargraph::DirectedEdge::getFromNode(), geos::planargraph::Node::getOutEdges(), geos::planargraph::DirectedEdge::getSym(), geos::planargraph::DirectedEdgeStar::remove(), and geos::planargraph::DirectedEdge::setSym().
 {
   DirectedEdge *sym = de->getSym();
   if (sym!=nullptr) sym->setSym(nullptr);
   de->getFromNode()->getOutEdges().remove(de);
   find_and_erase(de, dirEdges);
 }
void geos::planargraph::PlanarGraph::remove (Node * node)
Removes a node from the graph, along with any associated DirectedEdges and Edges.
Definition at line 93 of file PlanarGraph.cpp.
References geos::planargraph::find_and_erase(), geos::planargraph::Node::getCoordinate(), geos::planargraph::DirectedEdgeStar::getEdges(), geos::planargraph::Node::getOutEdges(), and geos::planargraph::DirectedEdge::getSym().
 {
   // unhook all directed edges
   auto & outEdges=node->getOutEdges().getEdges();
   for(auto de : outEdges) {
     DirectedEdge *sym = de->getSym();
     // remove the diredge that points to this node
     if (sym) remove(sym);
     find_and_erase(de, dirEdges);
     find_and_erase(de->getEdge(), edges);
   }
   // remove the node from the graph
   nodeMap.remove(node->getCoordinate());
   //nodes.remove(node);
 }
Member Data Documentation
std::vector<DirectedEdge*> geos::planargraph::PlanarGraph::dirEdges protected
Definition at line 65 of file PlanarGraph.h.
Referenced by geos::operation::polygonize::PolygonizeGraph::deleteCutEdges(), and geos::operation::polygonize::PolygonizeGraph::getEdgeRings().
std::vector<Edge*> geos::planargraph::PlanarGraph::edges protected
Definition at line 64 of file PlanarGraph.h.
Referenced by geos::operation::polygonize::PolygonizeGraph::computeNextCCWEdges(), geos::operation::polygonize::PolygonizeGraph::deleteAllEdges(), geos::operation::polygonize::PolygonizeGraph::findDirEdgesInRing(), geos::operation::polygonize::PolygonizeGraph::findLabeledEdgeRings(), geos::operation::polygonize::PolygonizeGraph::getDegree(), and geos::operation::polygonize::PolygonizeGraph::getDegreeNonDeleted().
NodeMap geos::planargraph::PlanarGraph::nodeMap protected
Definition at line 66 of file PlanarGraph.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/planargraph/PlanarGraph.h
/home/vicky/potree/geos/vicky/src/planargraph/PlanarGraph.cpp