GEOS: geos::geomgraph::Edge Class Reference
geos::geomgraph::Edge Class Reference
#include <Edge.h>
Public Member Functions
void testInvariant () const
Edge (geom::CoordinateSequence *newPts, const Label &newLabel)
Takes ownership of CoordinateSequence.
Edge (geom::CoordinateSequence *newPts)
Takes ownership of CoordinateSequence.
~Edge () override
virtual int getNumPoints () const
virtual void setName (const std::string &newName)
virtual const geom::CoordinateSequence * getCoordinates () const
virtual const geom::Coordinate & getCoordinate (int i) const
virtual const geom::Coordinate & getCoordinate () const
virtual Depth & getDepth ()
virtual int getDepthDelta () const
The depthDelta is the change in depth as an edge is crossed from R to L.
virtual void setDepthDelta (int newDepthDelta)
virtual int getMaximumSegmentIndex () const
virtual EdgeIntersectionList & getEdgeIntersectionList ()
virtual index::MonotoneChainEdge * getMonotoneChainEdge ()
Return this Edge's index::MonotoneChainEdge, ownership is retained by this object.
virtual bool isClosed () const
virtual bool isCollapsed () const
An Edge is collapsed if it is an Area edge and it consists of two segments which are equal and opposite (eg a zero-width V).
virtual Edge * getCollapsedEdge ()
virtual void setIsolated (bool newIsIsolated)
bool isIsolated () const override
virtual void addIntersections (algorithm::LineIntersector *li, int segmentIndex, int geomIndex)
Adds EdgeIntersections for one or both intersections found for a segment of an edge to the edge intersection list.
virtual void addIntersection (algorithm::LineIntersector *li, int segmentIndex, int geomIndex, int intIndex)
Add an EdgeIntersection for intersection intIndex.
void computeIM (geom::IntersectionMatrix &im) override
Update the IM with the contribution for this component.
virtual bool isPointwiseEqual (const Edge *e) const
return true if the coordinate sequences of the Edges are identical
virtual std::string print () const
virtual std::string printReverse () const
virtual bool equals (const Edge &e) const
virtual bool equals (const Edge *e) const
virtual geom::Envelope * getEnvelope ()
Label & getLabel ()
const Label & getLabel () const
void setLabel (const Label &newLabel)
virtual void setInResult (bool isInResult)
virtual bool isInResult () const
virtual void setCovered (bool isCovered)
virtual bool isCovered () const
virtual bool isCoveredSet () const
virtual bool isVisited () const
virtual void setVisited (bool isVisited)
virtual void updateIM (geom::IntersectionMatrix &im)
Static Public Member Functions
static void updateIM (const Label &lbl, geom::IntersectionMatrix &im)
Public Attributes
geom::CoordinateSequence * pts
Externally-set, owned by Edge. FIXME: refuse ownership.
EdgeIntersectionList eiList
Protected Attributes
Label label
Private Attributes
std::string name
index::MonotoneChainEdge * mce
Lazily-created, owned by Edge.
geom::Envelope * env
Lazily-created, owned by Edge.
bool isIsolatedVar
Depth depth
int depthDelta
Friends
std::ostream & operator<< (std::ostream &os, const Edge &el)
Detailed Description
The edge component of a geometry graph
Definition at line 66 of file Edge.h.
Constructor & Destructor Documentation
geos::geomgraph::Edge::Edge (geom::CoordinateSequence * newPts, const Label & newLabel)
Takes ownership of CoordinateSequence.
Definition at line 89 of file Edge.cpp.
References testInvariant().
Referenced by getCollapsedEdge().
   :
   GraphComponent(newLabel),
   mce(nullptr),
   env(nullptr),
   isIsolatedVar(true),
   depth(),
   depthDelta(0),
   pts(newPts),
   eiList(this)
 {
   testInvariant();
 }
geos::geomgraph::Edge::Edge (geom::CoordinateSequence * newPts)
Takes ownership of CoordinateSequence.
Definition at line 104 of file Edge.cpp.
References testInvariant().
   :
   GraphComponent(),
   mce(nullptr),
   env(nullptr),
   isIsolatedVar(true),
   depth(),
   depthDelta(0),
   pts(newPts),
   eiList(this)
 {
   testInvariant();
 }
geos::geomgraph::Edge::~Edge () override
Definition at line 80 of file Edge.cpp.
 {
   //cerr<<"["<<this<<"] ~Edge()"<<endl;
   delete mce;
   delete pts;
   delete env;
 }
Member Function Documentation
void geos::geomgraph::Edge::addIntersection (algorithm::LineIntersector * li, int segmentIndex, int geomIndex, int intIndex) virtual
Add an EdgeIntersection for intersection intIndex.
An intersection that falls exactly on a vertex of the edge is normalized to use the higher of the two possible segmentIndexes
Definition at line 165 of file Edge.cpp.
References geos::geomgraph::EdgeIntersectionList::add(), eiList, geos::geom::Coordinate::equals2D(), geos::geom::CoordinateSequence::getAt(), geos::algorithm::LineIntersector::getEdgeDistance(), geos::algorithm::LineIntersector::getIntersection(), getNumPoints(), pts, testInvariant(), geos::geom::Coordinate::toString(), and geos::algorithm::LineIntersector::toString().
Referenced by addIntersections().
 {
 #if GEOS_DEBUG
   std::cerr << "["<<this<<"] Edge::addIntersection("<<li->toString()<<", "<<segmentIndex<<", "<<geomIndex<<", "<<intIndex<<") called"<< std::endl;
 #endif
   const Coordinate& intPt=li->getIntersection(intIndex);
   unsigned int normalizedSegmentIndex=segmentIndex;
   double dist=li->getEdgeDistance(geomIndex,intIndex);
   // normalize the intersection point location
   unsigned int nextSegIndex=normalizedSegmentIndex+1;
   unsigned int npts=getNumPoints();
   if (nextSegIndex<npts)
   {
     const Coordinate& nextPt=pts->getAt(nextSegIndex);
         // Normalize segment index if intPt falls on vertex
         // The check for point equality is 2D only - Z values are ignored
     if (intPt.equals2D(nextPt)) {
       normalizedSegmentIndex=nextSegIndex;
       dist=0.0;
     }
   }
   /*
    * Add the intersection point to edge intersection list.
    */
 #if GEOS_DEBUG
   cerr<<"Edge::addIntersection adding to edge intersection list point "<<intPt.toString()<<endl;
 #endif
   eiList.add(intPt,normalizedSegmentIndex,dist);
   testInvariant();
 }
void geos::geomgraph::Edge::addIntersections (algorithm::LineIntersector * li, int segmentIndex, int geomIndex) virtual
Adds EdgeIntersections for one or both intersections found for a segment of an edge to the edge intersection list.
Definition at line 151 of file Edge.cpp.
References addIntersection(), geos::algorithm::LineIntersector::getIntersectionNum(), testInvariant(), and geos::algorithm::LineIntersector::toString().
Referenced by geos::geomgraph::index::SegmentIntersector::addIntersections().
 {
 #if GEOS_DEBUG
   cerr<<"["<<this<<"] Edge::addIntersections("<<li->toString()<<", "<<segmentIndex<<", "<<geomIndex<<") called"<<endl;
 #endif
   for (int i=0; i<li->getIntersectionNum();i++) {
     addIntersection(li,segmentIndex,geomIndex,i);
   }
   testInvariant();
 }
void geos::geomgraph::Edge::computeIM (geom::IntersectionMatrix & im) inline override virtual
Update the IM with the contribution for this component.
A component only contributes if it has a labelling for both parent geometries
Implements geos::geomgraph::GraphComponent.
Definition at line 215 of file Edge.h.
{
     updateIM(label, im);
     testInvariant();
   }
bool geos::geomgraph::Edge::equals (const Edge & e) const virtual
equals is defined to be:
e1 equals e2 iff the coordinates of e1 are the same or the reverse of the coordinates in e2
Definition at line 202 of file Edge.cpp.
References geos::geom::Coordinate::equals2D(), geos::geom::CoordinateSequence::getAt(), getNumPoints(), pts, and testInvariant().
Referenced by geos::geomgraph::operator==().
 {
   testInvariant();
   unsigned int npts1=getNumPoints();
   unsigned int npts2=e.getNumPoints();
   if (npts1 != npts2 ) return false;
   bool isEqualForward=true;
   bool isEqualReverse=true;
   for (unsigned int i=0, iRev=npts1-1; i<npts1; ++i, --iRev)
   {
     const Coordinate &e1pi=pts->getAt(i);
     const Coordinate &e2pi=e.pts->getAt(i);
     const Coordinate &e2piRev=e.pts->getAt(iRev);
     if ( !e1pi.equals2D(e2pi) ) isEqualForward=false;
     if ( !e1pi.equals2D(e2piRev) ) isEqualReverse=false;
     if ( !isEqualForward && !isEqualReverse ) return false;
   }
   return true;
 }
virtual bool geos::geomgraph::Edge::equals (const Edge * e) const inline virtual
Definition at line 236 of file Edge.h.
{
     assert(e);
     return equals(*e);
   }
Edge * geos::geomgraph::Edge::getCollapsedEdge () virtual
Definition at line 140 of file Edge.cpp.
References Edge(), geos::geom::CoordinateSequence::getAt(), geos::geomgraph::GraphComponent::label, pts, geos::geom::CoordinateSequence::setAt(), testInvariant(), and geos::geomgraph::Label::toLineLabel().
Referenced by geos::operation::overlay::OverlayOp::replaceCollapsedEdges().
 {
   testInvariant();
   CoordinateSequence *newPts = new CoordinateArraySequence(2);
   newPts->setAt(pts->getAt(0),0);
   newPts->setAt(pts->getAt(1),1);
   return new Edge(newPts, Label::toLineLabel(label));
 }
virtual const geom::Coordinate& geos::geomgraph::Edge::getCoordinate (int i) const inline virtual
Definition at line 125 of file Edge.h.
References geos::geom::CoordinateSequence::getAt().
Referenced by geos::operation::relate::EdgeEndBuilder::createEdgeEndForNext(), geos::operation::relate::EdgeEndBuilder::createEdgeEndForPrev(), geos::geomgraph::DirectedEdge::DirectedEdge(), geos::operation::IsSimpleOp::hasClosedEndpointIntersection(), geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), geos::operation::relate::RelateComputer::labelIsolatedEdge(), and geos::operation::overlay::LineBuilder::labelIsolatedLine().
{
     testInvariant();
     return pts->getAt(i);
   }
virtual const geom::Coordinate& geos::geomgraph::Edge::getCoordinate () const inline virtual
Definition at line 130 of file Edge.h.
References geos::geom::CoordinateSequence::getAt().
{
     testInvariant();
     return pts->getAt(0);
   }
virtual const geom::CoordinateSequence* geos::geomgraph::Edge::getCoordinates (void) const inline virtual
Definition at line 120 of file Edge.h.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::add(), geos::geomgraph::EdgeList::add(), geos::geomgraph::GeometryGraph::addEdge(), geos::geomgraph::index::SegmentIntersector::addIntersections(), geos::geomgraph::EdgeRing::addPoints(), geos::operation::overlay::LineBuilder::buildLines(), geos::operation::buffer::RightmostEdgeFinder::checkForRightmostCoordinate(), geos::geomgraph::index::SimpleEdgeSetIntersector::computeIntersects(), geos::geomgraph::PlanarGraph::findEdge(), geos::geomgraph::PlanarGraph::findEdgeInSameDirection(), geos::geomgraph::EdgeList::findEqualEdge(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtVertex(), geos::operation::buffer::SubgraphDepthLocater::findStabbedSegments(), geos::operation::buffer::BufferSubgraph::getEnvelope(), geos::operation::buffer::RightmostEdgeFinder::getRightmostSideOfSegment(), and geos::geomgraph::EdgeNodingValidator::toSegmentStrings().
{
     testInvariant();
     return pts;
   }
virtual Depth& geos::geomgraph::Edge::getDepth () inline virtual
Definition at line 136 of file Edge.h.
Referenced by geos::operation::overlay::OverlayOp::insertUniqueEdge().
{
     testInvariant();
     return depth;
   }
virtual int geos::geomgraph::Edge::getDepthDelta () const inline virtual
The depthDelta is the change in depth as an edge is crossed from R to L.
Returns
the change in depth as the edge is crossed from R to L
Definition at line 146 of file Edge.h.
Referenced by geos::geomgraph::DirectedEdge::getDepthDelta(), geos::operation::buffer::BufferBuilder::insertUniqueEdge(), and geos::geomgraph::DirectedEdge::setEdgeDepths().
{
     testInvariant();
     return depthDelta;
   }
virtual EdgeIntersectionList& geos::geomgraph::Edge::getEdgeIntersectionList () inline virtual
Definition at line 161 of file Edge.h.
Referenced by geos::operation::valid::IsValidOp::checkNoSelfIntersectingRings(), geos::operation::relate::EdgeEndBuilder::computeEdgeEnds(), geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), geos::operation::valid::IsValidOp::findPtNotNode(), geos::operation::overlay::EdgeSetNoder::getNodedEdges(), geos::operation::IsSimpleOp::hasNonEndpointIntersection(), and geos::operation::relate::RelateComputer::labelIntersectionNodes().
{
     testInvariant();
     return eiList;
   }
Envelope * geos::geomgraph::Edge::getEnvelope () virtual
Definition at line 288 of file Edge.cpp.
References env, geos::geom::Envelope::expandToInclude(), geos::geom::CoordinateSequence::getAt(), getNumPoints(), pts, and testInvariant().
Referenced by geos::geomgraph::collect_intersecting_edges(), and geos::operation::overlay::OverlayOp::insertUniqueEdges().
 {
   // compute envelope lazily
   if (env==nullptr)
   {
     env=new Envelope();
     unsigned int npts=getNumPoints();
     for (unsigned int i = 0; i<npts; ++i)
     {
       env->expandToInclude(pts->getAt(i));
     }
   }
   testInvariant();
   return env;
 }
Label& geos::geomgraph::GraphComponent::getLabel () inline inherited
Definition at line 57 of file GraphComponent.h.
Referenced by geos::geomgraph::GeometryGraph::addSelfIntersectionNodes(), geos::geomgraph::DirectedEdge::computeDirectedLabel(), geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), geos::geomgraph::DirectedEdgeStar::computeLabelling(), geos::operation::relate::RelateNodeGraph::copyNodesAndLabels(), geos::operation::relate::RelateComputer::copyNodesAndLabels(), geos::operation::overlay::OverlayOp::copyPoints(), geos::operation::relate::EdgeEndBuilder::createEdgeEndForNext(), geos::operation::relate::EdgeEndBuilder::createEdgeEndForPrev(), geos::geomgraph::EdgeIntersectionList::createSplitEdge(), geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes(), geos::geomgraph::NodeMap::getBoundaryNodes(), geos::geomgraph::GeometryGraph::insertBoundaryPoint(), geos::geomgraph::GeometryGraph::insertPoint(), geos::operation::overlay::OverlayOp::insertUniqueEdge(), geos::operation::buffer::BufferBuilder::insertUniqueEdge(), geos::geomgraph::PlanarGraph::isBoundaryNode(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), geos::operation::overlay::OverlayOp::labelIncompleteNodes(), geos::operation::relate::RelateComputer::labelIntersectionNodes(), geos::operation::relate::RelateComputer::labelIsolatedEdge(), geos::operation::overlay::LineBuilder::labelIsolatedLine(), geos::operation::overlay::LineBuilder::labelIsolatedLines(), geos::operation::relate::RelateComputer::labelIsolatedNode(), geos::operation::relate::RelateComputer::labelIsolatedNodes(), and geos::operation::overlay::OverlayOp::updateNodeLabelling().
 { return label; }
const Label& geos::geomgraph::GraphComponent::getLabel () const inline inherited
Definition at line 58 of file GraphComponent.h.
 { return label; }
virtual int geos::geomgraph::Edge::getMaximumSegmentIndex () const inline virtual
Definition at line 156 of file Edge.h.
Referenced by geos::operation::IsSimpleOp::hasNonEndpointIntersection().
{
     testInvariant();
     return getNumPoints()-1;
   }
MonotoneChainEdge * geos::geomgraph::Edge::getMonotoneChainEdge () virtual
Return this Edge's index::MonotoneChainEdge, ownership is retained by this object.
Definition at line 120 of file Edge.cpp.
References mce, and testInvariant().
Referenced by geos::geomgraph::index::SimpleMCSweepLineIntersector::add().
 {
   testInvariant();
   if (mce==nullptr) mce=new MonotoneChainEdge(this);
   return mce;
 }
virtual int geos::geomgraph::Edge::getNumPoints () const inline virtual
Definition at line 112 of file Edge.h.
References geos::geom::CoordinateSequence::getSize().
Referenced by geos::geomgraph::EdgeIntersectionList::addEndpoints(), addIntersection(), geos::operation::relate::EdgeEndBuilder::createEdgeEndForNext(), geos::geomgraph::DirectedEdge::DirectedEdge(), equals(), getEnvelope(), geos::operation::IsSimpleOp::hasClosedEndpointIntersection(), isCollapsed(), isPointwiseEqual(), geos::geomgraph::index::SegmentIntersector::isTrivialIntersection(), and printReverse().
{
     return static_cast<int>(pts->getSize());
   }
virtual bool geos::geomgraph::Edge::isClosed () const inline virtual
Definition at line 172 of file Edge.h.
References geos::geom::CoordinateSequence::getAt().
Referenced by geos::operation::IsSimpleOp::hasClosedEndpointIntersection(), and geos::geomgraph::index::SegmentIntersector::isTrivialIntersection().
{
     testInvariant();
     return pts->getAt(0)==pts->getAt(getNumPoints()-1);
   }
bool geos::geomgraph::Edge::isCollapsed () const virtual
An Edge is collapsed if it is an Area edge and it consists of two segments which are equal and opposite (eg a zero-width V).
Definition at line 130 of file Edge.cpp.
References geos::geom::CoordinateSequence::getAt(), getNumPoints(), geos::geomgraph::Label::isArea(), geos::geomgraph::GraphComponent::label, pts, and testInvariant().
Referenced by geos::operation::overlay::OverlayOp::replaceCollapsedEdges().
 {
   testInvariant();
   if (!label.isArea()) return false;
   if (getNumPoints()!= 3) return false;
   if (pts->getAt(0)==pts->getAt(2) ) return true;
   return false;
 }
virtual bool geos::geomgraph::GraphComponent::isCovered () const inline virtual inherited
Definition at line 64 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::collectLineEdge(), and geos::geomgraph::GraphComponent::setCovered().
 { return isCoveredVar; }
virtual bool geos::geomgraph::GraphComponent::isCoveredSet () const inline virtual inherited
Definition at line 65 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::findCoveredLineEdges().
 { return isCoveredSetVar; }
virtual bool geos::geomgraph::GraphComponent::isInResult () const inline virtual inherited
Definition at line 62 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes(), and geos::geomgraph::Node::isIncidentEdgeInResult().
 { return isInResultVar; }
bool geos::geomgraph::Edge::isIsolated () const inline override virtual
Implements geos::geomgraph::GraphComponent.
Definition at line 190 of file Edge.h.
Referenced by geos::operation::relate::RelateComputer::labelIsolatedEdges(), and geos::operation::overlay::LineBuilder::labelIsolatedLines().
{
     testInvariant();
     return isIsolatedVar;
   }
bool geos::geomgraph::Edge::isPointwiseEqual (const Edge * e) const virtual
return true if the coordinate sequences of the Edges are identical
Definition at line 229 of file Edge.cpp.
References geos::geom::Coordinate::equals2D(), geos::geom::CoordinateSequence::getAt(), getNumPoints(), pts, and testInvariant().
Referenced by geos::operation::overlay::OverlayOp::insertUniqueEdge(), and geos::operation::buffer::BufferBuilder::insertUniqueEdge().
 {
   testInvariant();
 #if GEOS_DEBUG > 2
   cerr<<"Edge::isPointwiseEqual call"<<endl;
 #endif
   unsigned int npts=getNumPoints();
   unsigned int enpts=e->getNumPoints();
   if (npts!=enpts) return false;
 #if GEOS_DEBUG
   cerr<<"Edge::isPointwiseEqual scanning "<<enpts<<"x"<<npts<<" points"<<endl;
 #endif
   for (unsigned int i=0; i<npts; ++i)
   {
     if (!pts->getAt(i).equals2D(e->pts->getAt(i))) {
       return false;
     }
   }
   return true;
 }
virtual bool geos::geomgraph::GraphComponent::isVisited () const inline virtual inherited
Definition at line 66 of file GraphComponent.h.
Referenced by geos::operation::buffer::BufferSubgraph::add(), and geos::operation::buffer::BufferBuilder::createSubgraphs().
 { return isVisitedVar; }
string geos::geomgraph::Edge::print () const virtual
Definition at line 252 of file Edge.cpp.
References testInvariant().
Referenced by geos::geomgraph::GeometryGraph::computeSplitEdges(), geos::operation::overlay::OverlayOp::insertUniqueEdge(), geos::operation::overlay::OverlayOp::insertUniqueEdges(), geos::geomgraph::EdgeList::print(), geos::geomgraph::DirectedEdge::printEdge(), and geos::geomgraph::PlanarGraph::printEdges().
 {
   testInvariant();
   std::stringstream ss;
   ss << *this;
   return ss.str();
 }
string geos::geomgraph::Edge::printReverse () const virtual
Definition at line 263 of file Edge.cpp.
References depthDelta, geos::geom::CoordinateSequence::getAt(), getNumPoints(), geos::geomgraph::GraphComponent::label, name, pts, testInvariant(), and geos::geom::Coordinate::toString().
Referenced by geos::geomgraph::DirectedEdge::printEdge().
 {
   testInvariant();
   stringstream os;
   os << "EDGE (rev)";
   if ( name != "" ) os << " name:" << name;
   os << " label:" << label
      << " depthDelta:" << depthDelta
      << ":" << std::endl
      << "  LINESTRING(";
   unsigned int npts=getNumPoints();
   for (unsigned int i=npts; i>0; --i)
   {
     if (i<npts) os << ", ";
     os << pts->getAt(i-1).toString();
   }
   os << ")";
   return os.str();
 }
void geos::geomgraph::GraphComponent::setCovered (bool isCovered) virtual inherited
Definition at line 55 of file GraphComponent.cpp.
References geos::geomgraph::GraphComponent::isCovered(), geos::geomgraph::GraphComponent::isCoveredSetVar, and geos::geomgraph::GraphComponent::isCoveredVar.
Referenced by geos::operation::overlay::LineBuilder::findCoveredLineEdges(), and geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges().
 {
   isCoveredVar = isCovered;
   isCoveredSetVar = true;
 }
virtual void geos::geomgraph::Edge::setDepthDelta (int newDepthDelta) inline virtual
Definition at line 151 of file Edge.h.
Referenced by geos::operation::buffer::BufferBuilder::insertUniqueEdge().
{
     depthDelta=newDepthDelta;
     testInvariant();
   }
virtual void geos::geomgraph::GraphComponent::setInResult (bool isInResult) inline virtual inherited
Definition at line 61 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::buildLines(), and geos::geomgraph::EdgeRing::setInResult().
 { isInResultVar=isInResult; }
virtual void geos::geomgraph::Edge::setIsolated (bool newIsIsolated) inline virtual
Definition at line 185 of file Edge.h.
Referenced by geos::geomgraph::index::SegmentIntersector::addIntersections().
{
     isIsolatedVar=newIsIsolated;
     testInvariant();
   }
void geos::geomgraph::GraphComponent::setLabel (const Label & newLabel) inline inherited
Definition at line 59 of file GraphComponent.h.
 { label = newLabel; }
virtual void geos::geomgraph::Edge::setName (const std::string & newName) inline virtual
Definition at line 116 of file Edge.h.
{
     name=newName;
   }
virtual void geos::geomgraph::GraphComponent::setVisited (bool isVisited) inline virtual inherited
Definition at line 67 of file GraphComponent.h.
Referenced by geos::operation::buffer::BufferSubgraph::add().
 { isVisitedVar = isVisited; }
void geos::geomgraph::Edge::testInvariant () const inline
Definition at line 87 of file Edge.h.
References geos::geom::operator<<().
Referenced by addIntersection(), addIntersections(), Edge(), equals(), getCollapsedEdge(), getEnvelope(), getMonotoneChainEdge(), isCollapsed(), isPointwiseEqual(), print(), and printReverse().
{
     assert(pts);
     assert(pts->size() > 1);
   }
void geos::geomgraph::GraphComponent::updateIM (geom::IntersectionMatrix & im) virtual inherited
Definition at line 62 of file GraphComponent.cpp.
References geos::geomgraph::GraphComponent::computeIM(), geos::geomgraph::Label::getGeometryCount(), and geos::geomgraph::GraphComponent::label.
Referenced by geos::operation::relate::RelateComputer::updateIM().
 {
   assert(label.getGeometryCount() >= 2); // found partial label
   computeIM(im);
 }
void geos::geomgraph::Edge::updateIM (const Label & lbl, geom::IntersectionMatrix & im) static
Updates an IM from the label for an edge. Handles edges from both L and A geometrys.
Definition at line 62 of file Edge.cpp.
References geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isArea(), and geos::geom::IntersectionMatrix::setAtLeastIfValid().
 {
   im.setAtLeastIfValid(lbl.getLocation(0,Position::ON),
                         lbl.getLocation(1,Position::ON),
                         1);
   if (lbl.isArea()) {
     im.setAtLeastIfValid(lbl.getLocation(0,Position::LEFT),
                           lbl.getLocation(1,Position::LEFT),
                           2);
     im.setAtLeastIfValid(lbl.getLocation(0,Position::RIGHT),
                           lbl.getLocation(1,Position::RIGHT),
                           2);
   }
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Edge & el) friend
Definition at line 305 of file Edge.cpp.
 {
   os << "edge";
   if ( e.name != "" ) os << " " << e.name;
   os
      << "  LINESTRING"
      << *(e.pts)
      << "  " << e.label
      << "  " << e.depthDelta
      ;
   return os;
 }
Member Data Documentation
Depth geos::geomgraph::Edge::depth private
Definition at line 81 of file Edge.h.
int geos::geomgraph::Edge::depthDelta private
Definition at line 83 of file Edge.h.
Referenced by geos::geomgraph::operator<<(), and printReverse().
EdgeIntersectionList geos::geomgraph::Edge::eiList
Definition at line 100 of file Edge.h.
Referenced by addIntersection(), geos::geomgraph::GeometryGraph::addSelfIntersectionNodes(), geos::geomgraph::GeometryGraph::computeSplitEdges(), and geos::geomgraph::PlanarGraph::printEdges().
geom::Envelope* geos::geomgraph::Edge::env private
Lazily-created, owned by Edge.
Definition at line 77 of file Edge.h.
Referenced by getEnvelope().
bool geos::geomgraph::Edge::isIsolatedVar private
Definition at line 79 of file Edge.h.
Label geos::geomgraph::GraphComponent::label protected inherited
Definition at line 71 of file GraphComponent.h.
Referenced by geos::operation::relate::RelateNode::computeIM(), geos::geomgraph::Node::computeMergedLocation(), getCollapsedEdge(), isCollapsed(), geos::geomgraph::Node::isIsolated(), geos::geomgraph::Node::mergeLabel(), geos::geomgraph::operator<<(), printReverse(), geos::geomgraph::Node::setLabel(), geos::geomgraph::Node::setLabelBoundary(), and geos::geomgraph::GraphComponent::updateIM().
index::MonotoneChainEdge* geos::geomgraph::Edge::mce private
Lazily-created, owned by Edge.
Definition at line 74 of file Edge.h.
Referenced by getMonotoneChainEdge().
std::string geos::geomgraph::Edge::name private
Definition at line 71 of file Edge.h.
Referenced by geos::geomgraph::operator<<(), and printReverse().
geom::CoordinateSequence* geos::geomgraph::Edge::pts
Externally-set, owned by Edge. FIXME: refuse ownership.
Definition at line 98 of file Edge.h.
Referenced by geos::geomgraph::EdgeIntersectionList::addEndpoints(), addIntersection(), geos::geomgraph::EdgeIntersectionList::createSplitEdge(), equals(), getCollapsedEdge(), getEnvelope(), isCollapsed(), isPointwiseEqual(), geos::geomgraph::operator<<(), and printReverse().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/Edge.h
/home/vicky/potree/geos/vicky/src/geomgraph/Edge.cpp