GEOS: geos::operation::geounion::PointGeometryUnion Class Reference
geos::operation::geounion::PointGeometryUnion Class Reference
Computes the union of a Puntal geometry with another arbitrary Geometry.
#include <PointGeometryUnion.h>
Public Member Functions
PointGeometryUnion (const geom::Puntal &pointGeom, const geom::Geometry &otherGeom)
std::unique_ptr< geom::Geometry > Union () const
Static Public Member Functions
static std::unique_ptr< geom::Geometry > Union (const geom::Puntal &pointGeom, const geom::Geometry &otherGeom)
Private Member Functions
PointGeometryUnion (const PointGeometryUnion &other)
PointGeometryUnion & operator= (const PointGeometryUnion &rhs)
Private Attributes
const geom::Geometry & pointGeom
const geom::Geometry & otherGeom
const geom::GeometryFactory * geomFact
Detailed Description
Computes the union of a Puntal geometry with another arbitrary Geometry.
Does not copy any component geometries.
Definition at line 47 of file PointGeometryUnion.h.
Constructor & Destructor Documentation
geos::operation::geounion::PointGeometryUnion::PointGeometryUnion (const geom::Puntal & pointGeom, const geom::Geometry & otherGeom)
Definition at line 91 of file PointGeometryUnion.cpp.
References geomFact, geos::geom::Geometry::getFactory(), and otherGeom.
   :
   pointGeom ( pointGeom_ ),
   otherGeom ( otherGeom_ )
 {
   geomFact = otherGeom.getFactory();
 }
geos::operation::geounion::PointGeometryUnion::PointGeometryUnion (const PointGeometryUnion & other) private
Member Function Documentation
PointGeometryUnion& geos::operation::geounion::PointGeometryUnion::operator= (const PointGeometryUnion & rhs) private
std::unique_ptr< geom::Geometry > geos::operation::geounion::PointGeometryUnion::Union (const geom::Puntal & pointGeom, const geom::Geometry & otherGeom) static
Definition at line 83 of file PointGeometryUnion.cpp.
References Union().
Referenced by Union().
 {
   PointGeometryUnion unioner(pointGeom, otherGeom);
   return unioner.Union();
 }
std::unique_ptr< geom::Geometry > geos::operation::geounion::PointGeometryUnion::Union () const
Definition at line 39 of file PointGeometryUnion.cpp.
References geos::geom::Geometry::clone(), geos::geom::GeometryFactory::createMultiPoint(), geos::geom::GeometryFactory::createPoint(), geomFact, geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getNumGeometries(), otherGeom, and pointGeom.
Referenced by geos::operation::geounion::UnaryUnionOp::Union().
 {
   using namespace geom;
   using algorithm::PointLocator;
   using geom::util::GeometryCombiner;
   PointLocator locater;
   // use a set to eliminate duplicates, as required for union
   std::set<Coordinate> exteriorCoords;
   for (std::size_t i=0, n=pointGeom.getNumGeometries(); i<n; ++i) {
       const Point* point = dynamic_cast<const Point*>(pointGeom.getGeometryN(i));
       assert(point);
       const Coordinate* coord = point->getCoordinate();
       int loc = locater.locate(*coord, &otherGeom);
       if (loc == Location::EXTERIOR)
               exteriorCoords.insert(*coord);
   }
   // if no points are in exterior, return the other geom
   if (exteriorCoords.empty())
           return std::unique_ptr<Geometry>(otherGeom.clone());
   // make a puntal geometry of appropriate size
   std::unique_ptr<Geometry> ptComp;
   if (exteriorCoords.size() == 1) {
     ptComp.reset( geomFact->createPoint(*(exteriorCoords.begin())) );
   }
   else
   {
     std::vector<Coordinate> coords(exteriorCoords.size());
     std::copy(exteriorCoords.begin(), exteriorCoords.end(), coords.begin());
     ptComp.reset( geomFact->createMultiPoint(coords) );
   }
   // add point component to the other geometry
   return std::unique_ptr<Geometry> (
     GeometryCombiner::combine(ptComp.get(), &otherGeom)
   );
 }
Member Data Documentation
const geom::GeometryFactory* geos::operation::geounion::PointGeometryUnion::geomFact private
Definition at line 64 of file PointGeometryUnion.h.
Referenced by PointGeometryUnion(), and Union().
const geom::Geometry& geos::operation::geounion::PointGeometryUnion::otherGeom private
Definition at line 63 of file PointGeometryUnion.h.
Referenced by PointGeometryUnion(), and Union().
const geom::Geometry& geos::operation::geounion::PointGeometryUnion::pointGeom private
Definition at line 62 of file PointGeometryUnion.h.
Referenced by Union().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/union/PointGeometryUnion.h
/home/vicky/potree/geos/vicky/src/operation/union/PointGeometryUnion.cpp