GEOS: geos::triangulate::quadedge::QuadEdgeSubdivision Class Reference
geos::triangulate::quadedge::QuadEdgeSubdivision Class Reference
#include <QuadEdgeSubdivision.h>
Classes
class TriangleCircumcentreVisitor
class TriangleCoordinatesVisitor
Public Types
typedef std::vector< QuadEdge * > QuadEdgeList
Public Member Functions
QuadEdgeSubdivision (const geom::Envelope &env, double tolerance)
virtual ~QuadEdgeSubdivision ()
double getTolerance () const
const geom::Envelope & getEnvelope () const
const QuadEdgeList & getEdges () const
void setLocator (std::unique_ptr< QuadEdgeLocator > locator)
virtual QuadEdge & makeEdge (const Vertex &o, const Vertex &d)
virtual QuadEdge & connect (QuadEdge &a, QuadEdge &b)
void remove (QuadEdge &e)
QuadEdge * locateFromEdge (const Vertex &v, const QuadEdge &startEdge) const
QuadEdge * locate (const Vertex &v) const
QuadEdge * locate (const geom::Coordinate &p)
QuadEdge * locate (const geom::Coordinate &p0, const geom::Coordinate &p1)
QuadEdge & insertSite (const Vertex &v)
bool isFrameEdge (const QuadEdge &e) const
bool isFrameBorderEdge (const QuadEdge &e) const
bool isFrameVertex (const Vertex &v) const
bool isOnEdge (const QuadEdge &e, const geom::Coordinate &p) const
bool isVertexOfEdge (const QuadEdge &e, const Vertex &v) const
std::unique_ptr< QuadEdgeList > getPrimaryEdges (bool includeFrame)
void visitTriangles (TriangleVisitor *triVisitor, bool includeFrame)
std::unique_ptr< geom::MultiLineString > getEdges (const geom::GeometryFactory &geomFact)
std::unique_ptr< geom::GeometryCollection > getTriangles (const geom::GeometryFactory &geomFact)
std::unique_ptr< geom::GeometryCollection > getVoronoiDiagram (const geom::GeometryFactory &geomFact)
std::unique_ptr< geom::MultiLineString > getVoronoiDiagramEdges (const geom::GeometryFactory &geomFact)
std::unique_ptr< std::vector< geom::Geometry * > > getVoronoiCellPolygons (const geom::GeometryFactory &geomFact)
std::unique_ptr< std::vector< geom::Geometry * > > getVoronoiCellEdges (const geom::GeometryFactory &geomFact)
std::unique_ptr< QuadEdgeSubdivision::QuadEdgeList > getVertexUniqueEdges (bool includeFrame)
std::unique_ptr< geom::Geometry > getVoronoiCellPolygon (QuadEdge *qe, const geom::GeometryFactory &geomFact)
std::unique_ptr< geom::Geometry > getVoronoiCellEdge (QuadEdge *qe, const geom::GeometryFactory &geomFact)
Static Public Member Functions
static void getTriangleEdges (const QuadEdge &startQE, const QuadEdge *triEdge[3])
Private Types
typedef std::stack< QuadEdge * > QuadEdgeStack
typedef std::set< QuadEdge * > QuadEdgeSet
typedef std::list< geom::CoordinateSequence * > TriList
Private Member Functions
virtual void createFrame (const geom::Envelope &env)
virtual void initSubdiv (QuadEdge *initEdges[3])
QuadEdge ** fetchTriangleToVisit (QuadEdge *edge, QuadEdgeStack &edgeStack, bool includeFrame, QuadEdgeSet &visitedEdges)
void getTriangleCoordinates (TriList *triList, bool includeFrame)
Private Attributes
QuadEdgeList quadEdges
QuadEdgeList createdEdges
QuadEdge * startingEdges [3]
double tolerance
double edgeCoincidenceTolerance
Vertex frameVertex [3]
geom::Envelope frameEnv
std::unique_ptr< QuadEdgeLocator > locator
QuadEdge * triEdges [3]
Detailed Description
A class that contains the QuadEdges representing a planar subdivision that models a triangulation. The subdivision is constructed using the quadedge algebra defined in the classs QuadEdge. All metric calculations are done in the Vertex class. In addition to a triangulation, subdivisions support extraction of Voronoi diagrams. This is easily accomplished, since the Voronoi diagram is the dual of the Delaunay triangulation.
Subdivisions can be provided with a tolerance value. Inserted vertices which are closer than this value to vertices already in the subdivision will be ignored. Using a suitable tolerance value can prevent robustness failures from happening during Delaunay triangulation.
Subdivisions maintain a frame triangle around the client-created edges. The frame is used to provide a bounded "container" for all edges within a TIN. Normally the frame edges, frame connecting edges, and frame triangles are not included in client processing.
Author
JTS: David Skea
JTS: Martin Davis
Benjamin Campbell
Definition at line 79 of file QuadEdgeSubdivision.h.
Member Typedef Documentation
typedef std::vector<QuadEdge*> geos::triangulate::quadedge::QuadEdgeSubdivision::QuadEdgeList
Definition at line 81 of file QuadEdgeSubdivision.h.
typedef std::set<QuadEdge*> geos::triangulate::quadedge::QuadEdgeSubdivision::QuadEdgeSet private
Definition at line 344 of file QuadEdgeSubdivision.h.
typedef std::stack<QuadEdge*> geos::triangulate::quadedge::QuadEdgeSubdivision::QuadEdgeStack private
Definition at line 343 of file QuadEdgeSubdivision.h.
typedef std::list< geom::CoordinateSequence*> geos::triangulate::quadedge::QuadEdgeSubdivision::TriList private
Definition at line 345 of file QuadEdgeSubdivision.h.
Constructor & Destructor Documentation
geos::triangulate::quadedge::QuadEdgeSubdivision::QuadEdgeSubdivision (const geom::Envelope & env, double tolerance)
Creates a new instance of a quad-edge subdivision based on a frame triangle that encloses a supplied bounding box. A new super-bounding box that contains the triangle is computed and stored.
Parameters
env the bouding box to surround
tolerance the tolerance value for determining if two sites are equal
Definition at line 64 of file QuadEdgeSubdivision.cpp.
References createdEdges, createFrame(), geos::triangulate::quadedge::EDGE_COINCIDENCE_TOL_FACTOR, edgeCoincidenceTolerance, initSubdiv(), quadEdges, and startingEdges.
                                                                                   :
         tolerance(tolerance),
         locator(new LastFoundQuadEdgeLocator(this))
 {
     edgeCoincidenceTolerance = tolerance / EDGE_COINCIDENCE_TOL_FACTOR;
     createFrame(env);
     initSubdiv(startingEdges);
     quadEdges.push_back(startingEdges[0]);
     createdEdges.push_back(startingEdges[0]);
     quadEdges.push_back(startingEdges[1]);
     createdEdges.push_back(startingEdges[1]);
     quadEdges.push_back(startingEdges[2]);
     createdEdges.push_back(startingEdges[2]);
 }
geos::triangulate::quadedge::QuadEdgeSubdivision::~QuadEdgeSubdivision () virtual
Definition at line 79 of file QuadEdgeSubdivision.cpp.
References createdEdges.
 {
     for(QuadEdgeList::iterator iter=createdEdges.begin(); iter!=createdEdges.end(); ++iter)
     {
         (*iter)->free();
         delete *iter;
     }
 }
Member Function Documentation
QuadEdge & geos::triangulate::quadedge::QuadEdgeSubdivision::connect (QuadEdge & a, QuadEdge & b) virtual
Creates a new QuadEdge connecting the destination of a to the origin of b, in such a way that all three have the same left face after the connection is complete. The quadedge is recorded in the edges list.
Parameters
a
b
Returns
Definition at line 146 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::connect(), createdEdges, and quadEdges.
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), and insertSite().
 {
     std::unique_ptr<QuadEdge> q0 = QuadEdge::connect(a, b);
     QuadEdge *q0_ptr = q0.get();
     q0.release();
     createdEdges.push_back(q0_ptr);
     quadEdges.push_back(q0_ptr);
     return *q0_ptr;
 }
void geos::triangulate::quadedge::QuadEdgeSubdivision::createFrame (const geom::Envelope & env) private virtual
Definition at line 89 of file QuadEdgeSubdivision.cpp.
References frameEnv, frameVertex, geos::geom::Envelope::getHeight(), geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), and geos::geom::Envelope::getWidth().
Referenced by QuadEdgeSubdivision().
 {
     double deltaX = env.getWidth();
     double deltaY = env.getHeight();
     double offset = 0.0;
     if (deltaX > deltaY) {
         offset = deltaX * 10.0;
     } else {
         offset = deltaY * 10.0;
     }
     frameVertex[0] = Vertex((env.getMaxX() + env.getMinX()) / 2.0, env
             .getMaxY() + offset);
     frameVertex[1] = Vertex(env.getMinX() - offset, env.getMinY() - offset);
     frameVertex[2] = Vertex(env.getMaxX() + offset, env.getMinY() - offset);
     frameEnv = Envelope(frameVertex[0].getCoordinate(), frameVertex[1]
             .getCoordinate());
     frameEnv.expandToInclude(frameVertex[2].getCoordinate());
 }
QuadEdge ** geos::triangulate::quadedge::QuadEdgeSubdivision::fetchTriangleToVisit (QuadEdge * edge, QuadEdgeStack & edgeStack, bool includeFrame, QuadEdgeSet & visitedEdges) private
Stores the edges for a visited triangle. Also pushes sym (neighbour) edges on stack to visit later.
Parameters
edge
edgeStack
includeFrame
Returns
the visited triangle edges
null if the triangle should not be visited (for instance, if it is outer)
Definition at line 344 of file QuadEdgeSubdivision.cpp.
References isFrameEdge(), geos::triangulate::quadedge::QuadEdge::lNext(), geos::triangulate::quadedge::QuadEdge::sym(), and triEdges.
Referenced by visitTriangles().
 {
     QuadEdge *curr = edge;
     int edgeCount = 0;
     bool isFrame = false;
     do
     {
         triEdges[edgeCount] = curr;
         if (isFrameEdge(*curr))
             isFrame = true;
         // push sym edges to visit next
         QuadEdge *sym = &curr->sym();
         if (visitedEdges.find(sym) == visitedEdges.end())
             edgeStack.push(sym);
         // mark this edge as visited
         visitedEdges.insert(curr);
         edgeCount++;
         curr = &curr->lNext();
     } while (curr != edge);
     if (isFrame && !includeFrame)
         return nullptr;
     return triEdges;
 }
const QuadEdgeList& geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges () const inline
Gets the collection of base QuadEdges (one for every pair of vertices which is connected).
Returns
a QuadEdgeList
Definition at line 151 of file QuadEdgeSubdivision.h.
Referenced by geos::triangulate::quadedge::LastFoundQuadEdgeLocator::findEdge(), and geos::triangulate::DelaunayTriangulationBuilder::getEdges().
{
     return quadEdges;
   }
std::unique_ptr< geom::MultiLineString > geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges (const geom::GeometryFactory & geomFact)
Gets the geometry for the edges in the subdivision as a MultiLineString containing 2-point lines.
Parameters
geomFact the GeometryFactory to use
Returns
a MultiLineString. The caller takes ownership of the returned object.
Definition at line 448 of file QuadEdgeSubdivision.cpp.
References geos::geom::CoordinateSequence::add(), geos::geom::GeometryFactory::createLineString(), geos::geom::GeometryFactory::createMultiLineString(), geos::triangulate::quadedge::QuadEdge::dest(), geos::triangulate::quadedge::Vertex::getCoordinate(), geos::geom::GeometryFactory::getCoordinateSequenceFactory(), getPrimaryEdges(), geos::triangulate::quadedge::QuadEdge::orig(), and quadEdges.
 {
     std::unique_ptr<QuadEdgeList> quadEdges(getPrimaryEdges(false));
     std::vector<Geometry *> edges(quadEdges->size());
     const CoordinateSequenceFactory *coordSeqFact = geomFact.getCoordinateSequenceFactory();
     int i = 0;
     for (QuadEdgeSubdivision::QuadEdgeList::iterator it = quadEdges->begin(); it != quadEdges->end(); ++it)
     {
         QuadEdge *qe = *it;
         CoordinateSequence *coordSeq = coordSeqFact->create((std::vector<geom::Coordinate>*)nullptr);;
         coordSeq->add(qe->orig().getCoordinate());
         coordSeq->add(qe->dest().getCoordinate());
         edges[i++] = static_cast<Geometry*>(geomFact.createLineString(*coordSeq));
         delete coordSeq;
     }
     geom::MultiLineString* result = geomFact.createMultiLineString(edges);
     for(std::vector<Geometry*>::iterator it=edges.begin(); it!=edges.end(); ++it)
         delete *it;
     return std::unique_ptr<MultiLineString>(result);
 }
const geom::Envelope& geos::triangulate::quadedge::QuadEdgeSubdivision::getEnvelope () const inline
Gets the envelope of the Subdivision (including the frame).
Returns
the envelope
Definition at line 141 of file QuadEdgeSubdivision.h.
{
     return frameEnv;
   }
std::unique_ptr< QuadEdgeSubdivision::QuadEdgeList > geos::triangulate::quadedge::QuadEdgeSubdivision::getPrimaryEdges (bool includeFrame)
Gets all primary quadedges in the subdivision. A primary edge is a QuadEdge which occupies the 0'th position in its array of associated quadedges. These provide the unique geometric edges of the triangulation.
Parameters
includeFrame true if the frame edges are to be included
Returns
a List of QuadEdges. The caller takes ownership of the returned QuadEdgeList but not the items it contains.
Definition at line 314 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::getPrimary(), isFrameEdge(), geos::triangulate::quadedge::QuadEdge::oNext(), startingEdges, and geos::triangulate::quadedge::QuadEdge::sym().
Referenced by getEdges().
 {
     QuadEdgeList *edges = new QuadEdgeList();
     QuadEdgeStack edgeStack;
     QuadEdgeSet visitedEdges;
     edgeStack.push(startingEdges[0]);
     while (!edgeStack.empty())
     {
         QuadEdge *edge = edgeStack.top();
         edgeStack.pop();
         if (visitedEdges.find(edge) == visitedEdges.end())
         {
             QuadEdge* priQE = (QuadEdge*)&edge->getPrimary();
             if (includeFrame || ! isFrameEdge(*priQE))
                 edges->push_back(priQE);
             edgeStack.push(&edge->oNext());
             edgeStack.push(&edge->sym().oNext());
             visitedEdges.insert(edge);
             visitedEdges.insert(&edge->sym());
         }
     }
     return std::unique_ptr<QuadEdgeList>(edges);
 }
double geos::triangulate::quadedge::QuadEdgeSubdivision::getTolerance () const inline
Gets the vertex-equality tolerance value used in this subdivision
Returns
the tolerance value
Definition at line 132 of file QuadEdgeSubdivision.h.
{
     return tolerance;
   }
void geos::triangulate::quadedge::QuadEdgeSubdivision::getTriangleCoordinates (QuadEdgeSubdivision::TriList * triList, bool includeFrame) private
Gets the coordinates for each triangle in the subdivision as an array.
Parameters
includeFrame true if the frame triangles should be included
triList a list of Coordinate[4] representing each triangle
Definition at line 420 of file QuadEdgeSubdivision.cpp.
References visitTriangles().
Referenced by getTriangles().
 {
     TriangleCoordinatesVisitor visitor(triList);
     visitTriangles((TriangleVisitor*)&visitor, includeFrame);
 }
void geos::triangulate::quadedge::QuadEdgeSubdivision::getTriangleEdges (const QuadEdge & startQE, const QuadEdge * triEdge[3]) static
Gets the edges for the triangle to the left of the given QuadEdge.
Parameters
startQE
triEdge
Exceptions
IllegalArgumentException if the edges do not form a triangle
Definition at line 52 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::lNext().
 {
     triEdge[0] = &startQE;
     triEdge[1] = &triEdge[0]->lNext();
     triEdge[2] = &triEdge[1]->lNext();
     if (&triEdge[2]->lNext() != triEdge[0]) {
         throw new
             util::IllegalArgumentException("Edges do not form a triangle");
     }
 }
std::unique_ptr< GeometryCollection > geos::triangulate::quadedge::QuadEdgeSubdivision::getTriangles (const geom::GeometryFactory & geomFact)
Gets the geometry for the triangles in a triangulated subdivision as a GeometryCollection of triangular Polygons.
Parameters
geomFact the GeometryFactory to use
Returns
a GeometryCollection of triangular Polygons. The caller takes ownership of the returned object.
Definition at line 476 of file QuadEdgeSubdivision.cpp.
References geos::geom::GeometryFactory::createGeometryCollection(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createPolygon(), and getTriangleCoordinates().
Referenced by geos::triangulate::DelaunayTriangulationBuilder::getTriangles().
 {
     TriList triPtsList;
     getTriangleCoordinates(&triPtsList, false);
     std::vector<Geometry*> tris;
     for(TriList::const_iterator it = triPtsList.begin();
             it != triPtsList.end(); ++it)
     {
         CoordinateSequence *coordSeq = *it;
         Polygon *tri = geomFact.createPolygon(
                 geomFact.createLinearRing(coordSeq), nullptr);
         tris.push_back(static_cast<Geometry*>(tri));
     }
     GeometryCollection* ret =  geomFact.createGeometryCollection(tris);
     //release memory
     for(std::vector<Geometry*>::iterator it=tris.begin(); it!=tris.end(); ++it)
         delete *it;
     tris.clear();
     return std::unique_ptr<GeometryCollection>(ret);
 }
std::unique_ptr< QuadEdgeSubdivision::QuadEdgeList > geos::triangulate::quadedge::QuadEdgeSubdivision::getVertexUniqueEdges (bool includeFrame)
Gets a collection of QuadEdges whose origin vertices are a unique set which includes all vertices in the subdivision. The frame vertices can be included if required. This is useful for algorithms which require traversing the subdivision starting at all vertices. Returning a quadedge for each vertex is more efficient than the alternative of finding the actual vertices using getVertices and then locating quadedges attached to them.
Parameters
includeFrame true if the frame vertices should be included
Returns
a collection of QuadEdge with the vertices of the subdivision as their origins
Definition at line 622 of file QuadEdgeSubdivision.cpp.
References isFrameVertex(), geos::triangulate::quadedge::QuadEdge::orig(), quadEdges, and geos::triangulate::quadedge::QuadEdge::sym().
Referenced by getVoronoiCellEdges(), and getVoronoiCellPolygons().
 {
   std::unique_ptr<QuadEdgeSubdivision::QuadEdgeList> edges(new QuadEdgeList());
   std::set<Vertex> visitedVertices;
   for(QuadEdgeSubdivision::QuadEdgeList::iterator it=quadEdges.begin() ; it!=quadEdges.end() ; ++it)
   {
     QuadEdge *qe = (QuadEdge*)(*it);
     Vertex v = qe->orig();
     if(visitedVertices.find(v) == visitedVertices.end())  //if v not found
     {
       visitedVertices.insert(v);
       if(includeFrame || ! QuadEdgeSubdivision::isFrameVertex(v))
       {
         edges->push_back(qe);
       }
     }
     QuadEdge *qd = &(qe->sym());
     Vertex vd = qd->orig();
     if(visitedVertices.find(vd) == visitedVertices.end()){
       visitedVertices.insert(vd);
       if(includeFrame || ! QuadEdgeSubdivision::isFrameVertex(vd)){
         edges->push_back(qd);
       }
     }
   }
   return edges;
 }
std::unique_ptr< geom::Geometry > geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellEdge (QuadEdge * qe, const geom::GeometryFactory & geomFact)
Gets the Voronoi cell edge around a site specified by the origin of a QuadEdge. The userData of the LineString is set to be the Coordinate of the site. This allows attaching external data associated with the site to this cell polygon.
Parameters
qe a quadedge originating at the cell site
geomFact a factory for building the polygon
Returns
a polygon indicating the cell extent
Definition at line 592 of file QuadEdgeSubdivision.cpp.
References geos::geom::CoordinateList::closeRing(), geos::geom::GeometryFactory::createLineString(), geos::triangulate::quadedge::Vertex::getCoordinate(), geos::triangulate::quadedge::QuadEdge::oPrev(), geos::triangulate::quadedge::QuadEdge::orig(), geos::triangulate::quadedge::QuadEdge::rot(), and geos::geom::CoordinateList::toCoordinateArray().
Referenced by getVoronoiCellEdges().
 {
   std::vector<Coordinate> cellPts;
   QuadEdge *startQE = qe;
   do{
     Coordinate cc = qe->rot().orig().getCoordinate();
     if ( cellPts.empty() || cellPts.back() != cc ) // no duplicates
       cellPts.push_back(cc);
     qe = &qe->oPrev();
   }while ( qe != startQE);
   //CoordList from a vector of Coordinates.
   geom::CoordinateList coordList(cellPts);
   //for checking close ring in CoordList class:
   coordList.closeRing();
   std::unique_ptr<Coordinate::Vect> pts = coordList.toCoordinateArray();
   std::unique_ptr<geom::Geometry> cellEdge(
     geomFact.createLineString(new geom::CoordinateArraySequence(pts.release())));
   Vertex v = startQE->orig();
   Coordinate c(0,0);
   c = v.getCoordinate();
   cellEdge->setUserData(reinterpret_cast<void*>(&c));
   return cellEdge;
 }
std::unique_ptr< std::vector< geom::Geometry * > > geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellEdges (const geom::GeometryFactory & geomFact)
Gets a List of LineStrings for the Voronoi cells of this triangulation. The userData of each LineString is set to be the Coordinate of the cell site. This allows easily associating external data associated with the sites to the cells.
Parameters
geomFact a geometry factory
Returns
a List of LineString
Definition at line 537 of file QuadEdgeSubdivision.cpp.
References getVertexUniqueEdges(), getVoronoiCellEdge(), poly, and visitTriangles().
Referenced by getVoronoiDiagramEdges().
 {
   std::unique_ptr< std::vector<geom::Geometry*> > cells(new std::vector<geom::Geometry*>);
   TriangleCircumcentreVisitor* tricircumVisitor = new TriangleCircumcentreVisitor();
   visitTriangles((TriangleVisitor*)tricircumVisitor, true);
   std::unique_ptr<QuadEdgeSubdivision::QuadEdgeList> edges = getVertexUniqueEdges(false);
   for(QuadEdgeSubdivision::QuadEdgeList::iterator it=edges->begin() ; it!=edges->end() ; ++it)
   {
     QuadEdge *qe = *it;
     std::unique_ptr<geom::Geometry> poly = getVoronoiCellEdge(qe,geomFact);
     cells->push_back(poly.release());
   }
   delete tricircumVisitor;
   return cells;
 }
std::unique_ptr< geom::Geometry > geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon (QuadEdge * qe, const geom::GeometryFactory & geomFact)
Gets the Voronoi cell around a site specified by the origin of a QuadEdge. The userData of the polygon is set to be the Coordinate of the site. This allows attaching external data associated with the site to this cell polygon.
Parameters
qe a quadedge originating at the cell site
geomFact a factory for building the polygon
Returns
a polygon indicating the cell extent
Definition at line 557 of file QuadEdgeSubdivision.cpp.
References geos::geom::CoordinateList::closeRing(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createPolygon(), geos::geom::CoordinateList::end(), geos::triangulate::quadedge::Vertex::getCoordinate(), geos::geom::CoordinateList::insert(), geos::triangulate::quadedge::QuadEdge::oPrev(), geos::triangulate::quadedge::QuadEdge::orig(), geos::triangulate::quadedge::QuadEdge::rot(), geos::geom::CoordinateList::size(), and geos::geom::CoordinateList::toCoordinateArray().
Referenced by getVoronoiCellPolygons().
 {
   std::vector<Coordinate> cellPts;
   QuadEdge *startQE = qe;
   do{
     Coordinate cc = qe->rot().orig().getCoordinate();
     if ( cellPts.empty() || cellPts.back() != cc ) // no duplicates
       cellPts.push_back(cc);
     qe = &qe->oPrev();
   }while ( qe != startQE);
   //CoordList from a vector of Coordinates.
   geom::CoordinateList coordList(cellPts);
   //for checking close ring in CoordList class:
   coordList.closeRing();
   if(coordList.size() < 4)
   {
     coordList.insert(coordList.end(),*(coordList.end()),true);
   }
   std::unique_ptr<Coordinate::Vect> pts = coordList.toCoordinateArray();
   std::unique_ptr<geom::Geometry> cellPoly(
     geomFact.createPolygon(geomFact.createLinearRing(new geom::CoordinateArraySequence(pts.release())),nullptr));
   Vertex v = startQE->orig();
   Coordinate c(0,0);
   c = v.getCoordinate();
   cellPoly->setUserData(reinterpret_cast<void*>(&c));
   return cellPoly;
 }
std::unique_ptr< std::vector< geom::Geometry * > > geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygons (const geom::GeometryFactory & geomFact)
Gets a List of Polygons for the Voronoi cells of this triangulation. The userData of each polygon is set to be the Coordinate of the cell site. This allows easily associating external data associated with the sites to the cells.
Parameters
geomFact a geometry factory
Returns
a List of Polygons
Definition at line 517 of file QuadEdgeSubdivision.cpp.
References getVertexUniqueEdges(), getVoronoiCellPolygon(), poly, and visitTriangles().
Referenced by getVoronoiDiagram().
 {
   std::unique_ptr< std::vector<geom::Geometry*> > cells(new std::vector<geom::Geometry*>);
   TriangleCircumcentreVisitor* tricircumVisitor = new TriangleCircumcentreVisitor();
   visitTriangles((TriangleVisitor*)tricircumVisitor, true);
   std::unique_ptr<QuadEdgeSubdivision::QuadEdgeList> edges = getVertexUniqueEdges(false);
   for(QuadEdgeSubdivision::QuadEdgeList::iterator it=edges->begin() ; it!=edges->end() ; ++it)
   {
     QuadEdge *qe = *it;
     std::unique_ptr<geom::Geometry> poly = getVoronoiCellPolygon(qe,geomFact);
     cells->push_back(poly.release());
   }
   delete tricircumVisitor;
   return cells;
 }
std::unique_ptr< geom::GeometryCollection > geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiDiagram (const geom::GeometryFactory & geomFact)
Gets the cells in the Voronoi diagram for this triangulation. The cells are returned as a GeometryCollection of Polygons The userData of each polygon is set to be the Coordinate of the cell site. This allows easily associating external data associated with the sites to the cells.
Parameters
geomFact a geometry factory
Returns
a GeometryCollection of Polygons
Definition at line 503 of file QuadEdgeSubdivision.cpp.
References geos::geom::GeometryFactory::createGeometryCollection(), and getVoronoiCellPolygons().
 {
   std::unique_ptr< std::vector<geom::Geometry*> > vorCells = getVoronoiCellPolygons(geomFact);
   return std::unique_ptr<GeometryCollection>(geomFact.createGeometryCollection(vorCells.release()));
 }
std::unique_ptr< geom::MultiLineString > geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiDiagramEdges (const geom::GeometryFactory & geomFact)
Gets the cells in the Voronoi diagram for this triangulation. The cells are returned as a GeometryCollection of LineStrings The userData of each polygon is set to be the Coordinate of the cell site. This allows easily associating external data associated with the sites to the cells.
Parameters
geomFact a geometry factory
Returns
a MultiLineString
Definition at line 510 of file QuadEdgeSubdivision.cpp.
References geos::geom::GeometryFactory::createMultiLineString(), and getVoronoiCellEdges().
 {
   std::unique_ptr< std::vector<geom::Geometry*> > vorCells = getVoronoiCellEdges(geomFact);
   return std::unique_ptr<MultiLineString>(geomFact.createMultiLineString(vorCells.release()));
 }
void geos::triangulate::quadedge::QuadEdgeSubdivision::initSubdiv (QuadEdge * initEdges[3]) private virtual
Definition at line 110 of file QuadEdgeSubdivision.cpp.
References frameVertex, geos::triangulate::quadedge::QuadEdge::makeEdge(), and geos::triangulate::quadedge::QuadEdge::splice().
Referenced by QuadEdgeSubdivision().
 {
     std::unique_ptr<QuadEdge> tmp_ptr;
     // build initial subdivision from frame
     tmp_ptr = QuadEdge::makeEdge(frameVertex[0], frameVertex[1]);
     initEdges[0] = tmp_ptr.get();
     tmp_ptr.release();
     tmp_ptr = QuadEdge::makeEdge(frameVertex[1], frameVertex[2]);
     initEdges[1] = tmp_ptr.get();
     tmp_ptr.release();
     QuadEdge::splice(initEdges[0]->sym(), *initEdges[1]);
     tmp_ptr = QuadEdge::makeEdge(frameVertex[2], frameVertex[0]);
     initEdges[2] = tmp_ptr.get();
     tmp_ptr.release();
     QuadEdge::splice(initEdges[1]->sym(), *initEdges[2]);
     QuadEdge::splice(initEdges[2]->sym(), *initEdges[0]);
 }
QuadEdge & geos::triangulate::quadedge::QuadEdgeSubdivision::insertSite (const Vertex & v)
Inserts a new site into the Subdivision, connecting it to the vertices of the containing triangle (or quadrilateral, if the split point falls on an existing edge).
This method does NOT maintain the Delaunay condition. If desired, this must be checked and enforced by the caller.
This method does NOT check if the inserted vertex falls on an edge. This must be checked by the caller, since this situation may cause erroneous triangulation
Parameters
v the vertex to insert
Returns
a new quad edge terminating in v
Definition at line 237 of file QuadEdgeSubdivision.cpp.
References connect(), geos::triangulate::quadedge::QuadEdge::dest(), geos::triangulate::quadedge::Vertex::equals(), geos::triangulate::quadedge::QuadEdge::lNext(), locate(), makeEdge(), geos::triangulate::quadedge::QuadEdge::oPrev(), geos::triangulate::quadedge::QuadEdge::orig(), geos::triangulate::quadedge::QuadEdge::splice(), geos::triangulate::quadedge::QuadEdge::sym(), and tolerance.
 {
     QuadEdge *e = locate(v);
     if ((v.equals(e->orig(), tolerance)) || (v.equals(e->dest(), tolerance))) {
         return *e; // point already in subdivision.
     }
     // Connect the new point to the vertices of the containing
     // triangle (or quadrilateral, if the new point fell on an
     // existing edge.)
     QuadEdge *base = &makeEdge(e->orig(), v);
     QuadEdge::splice(*base, *e);
     QuadEdge *startEdge = base;
     do {
         base = &connect(*e, base->sym());
         e = &base->oPrev();
     } while (&e->lNext() != startEdge);
     return *startEdge;
 }
bool geos::triangulate::quadedge::QuadEdgeSubdivision::isFrameBorderEdge (const QuadEdge & e) const
Tests whether a QuadEdge is an edge on the border of the frame facets and the internal facets. E.g. an edge which does not itself touch a frame vertex, but which touches an edge which does.
Parameters
e the edge to test
Returns
true if the edge is on the border of the frame
Definition at line 268 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::dest(), isFrameVertex(), geos::triangulate::quadedge::QuadEdge::lNext(), and geos::triangulate::quadedge::QuadEdge::sym().
 {
     // check other vertex of triangle to left of edge
     Vertex vLeftTriOther = e.lNext().dest();
     if (isFrameVertex(vLeftTriOther))
         return true;
     // check other vertex of triangle to right of edge
     Vertex vRightTriOther = e.sym().lNext().dest();
     if (isFrameVertex(vRightTriOther))
         return true;
     return false;
 }
bool geos::triangulate::quadedge::QuadEdgeSubdivision::isFrameEdge (const QuadEdge & e) const
Tests whether a QuadEdge is an edge incident on a frame triangle vertex.
Parameters
e the edge to test
Returns
true if the edge is connected to the frame triangle
Definition at line 260 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::dest(), isFrameVertex(), and geos::triangulate::quadedge::QuadEdge::orig().
Referenced by fetchTriangleToVisit(), and getPrimaryEdges().
 {
     if (isFrameVertex(e.orig()) || isFrameVertex(e.dest()))
         return true;
     return false;
 }
bool geos::triangulate::quadedge::QuadEdgeSubdivision::isFrameVertex (const Vertex & v) const
Tests whether a vertex is a vertex of the outer triangle.
Parameters
v the vertex to test
Returns
true if the vertex is an outer triangle vertex
Definition at line 283 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::Vertex::equals(), and frameVertex.
Referenced by getVertexUniqueEdges(), isFrameBorderEdge(), and isFrameEdge().
 {
     if (v.equals(frameVertex[0]))
         return true;
     if (v.equals(frameVertex[1]))
         return true;
     if (v.equals(frameVertex[2]))
         return true;
     return false;
 }
bool geos::triangulate::quadedge::QuadEdgeSubdivision::isOnEdge (const QuadEdge & e, const geom::Coordinate & p) const
Tests whether a Coordinate lies on a QuadEdge, up to a tolerance determined by the subdivision tolerance.
Parameters
e a QuadEdge
p a point
Returns
true if the vertex lies on the edge
Definition at line 295 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::dest(), geos::geom::LineSegment::distance(), edgeCoincidenceTolerance, geos::triangulate::quadedge::Vertex::getCoordinate(), geos::triangulate::quadedge::QuadEdge::orig(), and geos::geom::LineSegment::setCoordinates().
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite().
 {
     geom::LineSegment seg;
     seg.setCoordinates(e.orig().getCoordinate(), e.dest().getCoordinate());
     double dist = seg.distance(p);
     // heuristic (hack?)
     return dist < edgeCoincidenceTolerance;
 }
bool geos::triangulate::quadedge::QuadEdgeSubdivision::isVertexOfEdge (const QuadEdge & e, const Vertex & v) const
Tests whether a Vertex is the start or end vertex of a QuadEdge, up to the subdivision tolerance distance.
Parameters
e
v
Returns
true if the vertex is a endpoint of the edge
Definition at line 305 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::dest(), geos::triangulate::quadedge::Vertex::equals(), geos::triangulate::quadedge::QuadEdge::orig(), and tolerance.
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite().
 {
     if ((v.equals(e.orig(), tolerance)) || (v.equals(e.dest(), tolerance))) {
         return true;
     }
     return false;
 }
QuadEdge* geos::triangulate::quadedge::QuadEdgeSubdivision::locate (const Vertex & v) const inline
Finds a quadedge of a triangle containing a location specified by a Vertex, if one exists.
Parameters
x the vertex to locate
Returns
a quadedge on the edge of a triangle which touches or contains the location
null if no such triangle exists. The returned pointer should not be freed be the caller.
Definition at line 225 of file QuadEdgeSubdivision.h.
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), and insertSite().
{
     return locator->locate(v);
   }
QuadEdge* geos::triangulate::quadedge::QuadEdgeSubdivision::locate (const geom::Coordinate & p) inline
Finds a quadedge of a triangle containing a location specified by a Coordinate, if one exists.
Parameters
p the Coordinate to locate
Returns
a quadedge on the edge of a triangle which touches or contains the location
null if no such triangle exists. The returned pointer should not be freed be the caller.
Definition at line 238 of file QuadEdgeSubdivision.h.
{
     return locator->locate(Vertex(p));
   }
QuadEdge * geos::triangulate::quadedge::QuadEdgeSubdivision::locate (const geom::Coordinate & p0, const geom::Coordinate & p1)
Locates the edge between the given vertices, if it exists in the subdivision.
Parameters
p0 a coordinate
p1 another coordinate
Returns
the edge joining the coordinates, if present
null if no such edge exists
the caller should not free the returned pointer
Definition at line 215 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::dest(), geos::geom::Coordinate::equals2D(), geos::triangulate::quadedge::Vertex::getCoordinate(), locator, geos::triangulate::quadedge::QuadEdge::oNext(), and geos::triangulate::quadedge::QuadEdge::sym().
 {
     // find an edge containing one of the points
     QuadEdge *e = locator->locate(Vertex(p0));
     if (e == nullptr)
         return nullptr;
     // normalize so that p0 is origin of base edge
     QuadEdge *base = e;
     if (e->dest().getCoordinate().equals2D(p0))
         base = &e->sym();
     // check all edges around origin of base edge
     QuadEdge *locEdge = base;
     do {
         if (locEdge->dest().getCoordinate().equals2D(p1))
             return locEdge;
         locEdge = &locEdge->oNext();
     } while (locEdge != base);
     return nullptr;
 }
QuadEdge * geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge (const Vertex & v, const QuadEdge & startEdge) const
Locates an edge of a triangle which contains a location specified by a Vertex v. The edge returned has the property that either v is on e, or e is an edge of a triangle containing v. The search starts from startEdge amd proceeds on the general direction of v.
This locate algorithm relies on the subdivision being Delaunay. For non-Delaunay subdivisions, this may loop for ever.
Parameters
v the location to search for
startEdge an edge of the subdivision to start searching at
Returns
a QuadEdge which contains v, or is on the edge of a triangle containing v
Exceptions
LocateFailureException if the location algorithm fails to converge in a reasonable number of iterations. The returned pointer should not be freed be the caller.
So far it has always been the case that failure to locate indicates an invalid subdivision. So just fail completely. (An alternative would be to perform an exhaustive search for the containing triangle, but this would mask errors in the subdivision topology)
This can also happen if two vertices are located very close together, since the orientation predicates may experience precision failures.
Definition at line 172 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::dest(), geos::triangulate::quadedge::QuadEdge::dPrev(), geos::triangulate::quadedge::Vertex::equals(), geos::ignore_unused_variable_warning(), geos::triangulate::quadedge::QuadEdge::oNext(), geos::triangulate::quadedge::QuadEdge::orig(), quadEdges, geos::triangulate::quadedge::Vertex::rightOf(), startingEdges, and geos::triangulate::quadedge::QuadEdge::sym().
Referenced by geos::triangulate::quadedge::LastFoundQuadEdgeLocator::locate().
 {
     ::geos::ignore_unused_variable_warning(startEdge);
     int iter = 0;
     int maxIter = static_cast<int>(quadEdges.size());
     QuadEdge *e = startingEdges[0];
     for (;;)
     {
         ++iter;
         if (iter > maxIter) {
             throw LocateFailureException("");
         }
         if ((v.equals(e->orig())) || (v.equals(e->dest()))) {
             break;
         } else if (v.rightOf(*e)) {
             e = &e->sym();
         } else if (!v.rightOf(e->oNext())) {
             e = &e->oNext();
         } else if (!v.rightOf(e->dPrev())) {
             e = &e->dPrev();
         } else {
             // on edge or in triangle containing edge
             break;
         }
     }
     return e;
 }
QuadEdge & geos::triangulate::quadedge::QuadEdgeSubdivision::makeEdge (const Vertex & o, const Vertex & d) virtual
Creates a new quadedge, recording it in the edges list.
Parameters
o
d
Returns
Definition at line 134 of file QuadEdgeSubdivision.cpp.
References createdEdges, geos::triangulate::quadedge::QuadEdge::makeEdge(), and quadEdges.
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), and insertSite().
 {
     std::unique_ptr<QuadEdge> q0 = QuadEdge::makeEdge(o, d);
     QuadEdge *q0_ptr = q0.get();
     q0.release();
     createdEdges.push_back(q0_ptr);
     quadEdges.push_back(q0_ptr);
     return *q0_ptr;
 }
void geos::triangulate::quadedge::QuadEdgeSubdivision::remove (QuadEdge & e)
Deletes a quadedge from the subdivision. Linked quadedges are updated to reflect the deletion.
Parameters
e the quadedge to delete
Definition at line 158 of file QuadEdgeSubdivision.cpp.
References geos::triangulate::quadedge::QuadEdge::oPrev(), quadEdges, geos::triangulate::quadedge::QuadEdge::remove(), geos::triangulate::quadedge::QuadEdge::splice(), and geos::triangulate::quadedge::QuadEdge::sym().
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite().
 {
     QuadEdge::splice(e, e.oPrev());
     QuadEdge::splice(e.sym(), e.sym().oPrev());
     // this is inefficient on a std::vector, but this method should be called infrequently
     quadEdges.erase(std::remove(quadEdges.begin(), quadEdges.end(), &e), quadEdges.end());
     //mark these edges as removed
     e.remove();
 }
void geos::triangulate::quadedge::QuadEdgeSubdivision::setLocator (std::unique_ptr< QuadEdgeLocator > locator) inline
Sets the QuadEdgeLocator to use for locating containing triangles in this subdivision.
Parameters
locator a QuadEdgeLocator
Definition at line 162 of file QuadEdgeSubdivision.h.
{
     this->locator = std::move(locator);
   }
void geos::triangulate::quadedge::QuadEdgeSubdivision::visitTriangles (TriangleVisitor * triVisitor, bool includeFrame)
Definition at line 427 of file QuadEdgeSubdivision.cpp.
References fetchTriangleToVisit(), startingEdges, triEdges, and geos::triangulate::quadedge::TriangleVisitor::visit().
Referenced by getTriangleCoordinates(), getVoronoiCellEdges(), and getVoronoiCellPolygons().
 {
     QuadEdgeStack edgeStack;
     edgeStack.push(startingEdges[0]);
     QuadEdgeSet visitedEdges;
     while (!edgeStack.empty()) {
         QuadEdge *edge = edgeStack.top();
         edgeStack.pop();
         if (visitedEdges.find(edge) == visitedEdges.end()) {
             QuadEdge **triEdges = fetchTriangleToVisit(edge, edgeStack,
                     includeFrame, visitedEdges);
             if (triEdges != nullptr)
                 triVisitor->visit(triEdges);
         }
     }
 }
Member Data Documentation
QuadEdgeList geos::triangulate::quadedge::QuadEdgeSubdivision::createdEdges private
Definition at line 97 of file QuadEdgeSubdivision.h.
Referenced by connect(), makeEdge(), QuadEdgeSubdivision(), and ~QuadEdgeSubdivision().
double geos::triangulate::quadedge::QuadEdgeSubdivision::edgeCoincidenceTolerance private
Definition at line 100 of file QuadEdgeSubdivision.h.
Referenced by isOnEdge(), and QuadEdgeSubdivision().
geom::Envelope geos::triangulate::quadedge::QuadEdgeSubdivision::frameEnv private
Definition at line 102 of file QuadEdgeSubdivision.h.
Referenced by createFrame().
Vertex geos::triangulate::quadedge::QuadEdgeSubdivision::frameVertex[3] private
Definition at line 101 of file QuadEdgeSubdivision.h.
Referenced by createFrame(), initSubdiv(), and isFrameVertex().
std::unique_ptr<QuadEdgeLocator> geos::triangulate::quadedge::QuadEdgeSubdivision::locator private
Definition at line 103 of file QuadEdgeSubdivision.h.
Referenced by locate().
QuadEdgeList geos::triangulate::quadedge::QuadEdgeSubdivision::quadEdges private
Definition at line 96 of file QuadEdgeSubdivision.h.
Referenced by connect(), getEdges(), getVertexUniqueEdges(), locateFromEdge(), makeEdge(), QuadEdgeSubdivision(), and remove().
QuadEdge* geos::triangulate::quadedge::QuadEdgeSubdivision::startingEdges[3] private
Definition at line 98 of file QuadEdgeSubdivision.h.
Referenced by getPrimaryEdges(), locateFromEdge(), QuadEdgeSubdivision(), and visitTriangles().
double geos::triangulate::quadedge::QuadEdgeSubdivision::tolerance private
Definition at line 99 of file QuadEdgeSubdivision.h.
Referenced by insertSite(), and isVertexOfEdge().
QuadEdge* geos::triangulate::quadedge::QuadEdgeSubdivision::triEdges[3] private
The quadedges forming a single triangle. Only one visitor is allowed to be active at a time, so this is safe.
Definition at line 352 of file QuadEdgeSubdivision.h.
Referenced by fetchTriangleToVisit(), and visitTriangles().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/triangulate/quadedge/QuadEdgeSubdivision.h
/home/vicky/potree/geos/vicky/src/triangulate/quadedge/QuadEdgeSubdivision.cpp