GEOS: geos::planargraph::algorithm::ConnectedSubgraphFinder Class Reference
geos::planargraph::algorithm::ConnectedSubgraphFinder Class Reference
Finds all connected Subgraphs of a PlanarGraph.
#include <ConnectedSubgraphFinder.h>
Public Member Functions
ConnectedSubgraphFinder (PlanarGraph &newGraph)
void getConnectedSubgraphs (std::vector< Subgraph * > &dest)
Store newly allocated connected Subgraphs into the given std::vector.
Private Member Functions
Subgraph * findSubgraph (Node *node)
Returns a newly allocated Subgraph.
void addReachable (Node *node, Subgraph *subgraph)
void addEdges (Node *node, std::stack< Node * > &nodeStack, Subgraph *subgraph)
ConnectedSubgraphFinder (const ConnectedSubgraphFinder &other)=delete
ConnectedSubgraphFinder & operator= (const ConnectedSubgraphFinder &rhs)=delete
Private Attributes
PlanarGraph & graph
Detailed Description
Finds all connected Subgraphs of a PlanarGraph.
Note: uses the isVisited flag on the nodes.
Definition at line 43 of file ConnectedSubgraphFinder.h.
Constructor & Destructor Documentation
geos::planargraph::algorithm::ConnectedSubgraphFinder::ConnectedSubgraphFinder (PlanarGraph & newGraph) inline
Definition at line 47 of file ConnectedSubgraphFinder.h.
     :
     graph(newGraph)
     {}
geos::planargraph::algorithm::ConnectedSubgraphFinder::ConnectedSubgraphFinder (const ConnectedSubgraphFinder & other) private delete
Member Function Documentation
void geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges (Node * node, std::stack< Node * > & nodeStack, Subgraph * subgraph) private
Adds the argument node and all its out edges to the subgraph.
Parameters
node the node to add
nodeStack the current set of nodes being traversed
Definition at line 79 of file ConnectedSubgraphFinder.cpp.
References geos::planargraph::Subgraph::add(), geos::planargraph::Node::getOutEdges(), geos::planargraph::GraphComponent::isVisited(), and geos::planargraph::GraphComponent::setVisited().
 {
   node->setVisited(true);
   auto des = node->getOutEdges();
   for (auto de : des)
   {
     subgraph->add(de->getEdge());
     Node *toNode = de->getToNode();
     if ( ! toNode->isVisited() ) nodeStack.push(toNode);
   }
 }
void geos::planargraph::algorithm::ConnectedSubgraphFinder::addReachable (Node * node, Subgraph * subgraph) private
Adds all nodes and edges reachable from this node to the subgraph. Uses an explicit stack to avoid a large depth of recursion.
Parameters
node a node known to be in the subgraph
Definition at line 64 of file ConnectedSubgraphFinder.cpp.
 {
   stack<Node *> nodeStack;
   nodeStack.push(startNode);
   while ( !nodeStack.empty() )
   {
     Node* node = nodeStack.top();
     nodeStack.pop();
     addEdges(node, nodeStack, subgraph);
   }
 }
Subgraph * geos::planargraph::algorithm::ConnectedSubgraphFinder::findSubgraph (Node * node) private
Returns a newly allocated Subgraph.
Definition at line 55 of file ConnectedSubgraphFinder.cpp.
 {
   Subgraph* subgraph = new Subgraph(graph);
   addReachable(node, subgraph);
   return subgraph;
 }
void geos::planargraph::algorithm::ConnectedSubgraphFinder::getConnectedSubgraphs (std::vector< Subgraph * > & dest)
Store newly allocated connected Subgraphs into the given std::vector.
Caller take responsibility in releasing memory associated with the subgraphs themself.
Definition at line 34 of file ConnectedSubgraphFinder.cpp.
References geos::planargraph::Edge::getDirEdge(), geos::planargraph::DirectedEdge::getFromNode(), and geos::planargraph::GraphComponent::isVisited().
Referenced by geos::operation::linemerge::LineSequencer::findSequences().
 {
   GraphComponent::setVisitedMap(graph.nodeBegin(),
       graph.nodeEnd(), false);
   for (PlanarGraph::EdgeIterator
       it=graph.edgeBegin(),
       itEnd=graph.edgeEnd();
       it!=itEnd; ++it)
   {
     Edge *e = *it;
     Node *node = e->getDirEdge(0)->getFromNode();
     if (! node->isVisited()) {
       subgraphs.push_back(findSubgraph(node));
     }
   }
 }
ConnectedSubgraphFinder& geos::planargraph::algorithm::ConnectedSubgraphFinder::operator= (const ConnectedSubgraphFinder & rhs) private delete
Member Data Documentation
PlanarGraph& geos::planargraph::algorithm::ConnectedSubgraphFinder::graph private
Definition at line 64 of file ConnectedSubgraphFinder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/planargraph/algorithm/ConnectedSubgraphFinder.h
/home/vicky/potree/geos/vicky/src/planargraph/algorithm/ConnectedSubgraphFinder.cpp