GEOS: geos::noding::SegmentSetMutualIntersector Class Reference
geos::noding::SegmentSetMutualIntersector Class Reference abstract
An intersector for the red-blue intersection problem.
#include <SegmentSetMutualIntersector.h>
Public Member Functions
SegmentSetMutualIntersector ()
virtual ~SegmentSetMutualIntersector ()
void setSegmentIntersector (SegmentIntersector *si)
virtual void setBaseSegments (SegmentString::ConstVect *segStrings)=0
virtual void process (SegmentString::ConstVect *segStrings)=0
Protected Attributes
SegmentIntersector * segInt
Detailed Description
An intersector for the red-blue intersection problem.
In this class of line arrangement problem, two disjoint sets of linestrings are provided. It is assumed that within each set, no two linestrings intersect except possibly at their endpoints. Implementations can take advantage of this fact to optimize processing.
Author
Martin Davis
Version
1.10
Definition at line 37 of file SegmentSetMutualIntersector.h.
Constructor & Destructor Documentation
geos::noding::SegmentSetMutualIntersector::SegmentSetMutualIntersector () inline
Definition at line 41 of file SegmentSetMutualIntersector.h.
         : segInt(nullptr)
     {}
virtual geos::noding::SegmentSetMutualIntersector::~SegmentSetMutualIntersector () inline virtual
Definition at line 45 of file SegmentSetMutualIntersector.h.
 {}
Member Function Documentation
virtual void geos::noding::SegmentSetMutualIntersector::process (SegmentString::ConstVect * segStrings) pure virtual
Computes the intersections for two collections of SegmentStrings.
Parameters
segStrings1 a collection of SegmentStrings to node
Implemented in geos::noding::MCIndexSegmentSetMutualIntersector.
Referenced by setSegmentIntersector().
virtual void geos::noding::SegmentSetMutualIntersector::setBaseSegments (SegmentString::ConstVect * segStrings) pure virtual
Parameters
segStrings0 a collection of SegmentStrings to node
Implemented in geos::noding::MCIndexSegmentSetMutualIntersector.
Referenced by setSegmentIntersector().
void geos::noding::SegmentSetMutualIntersector::setSegmentIntersector (SegmentIntersector * si) inline
Sets the SegmentIntersector to use with this intersector. The SegmentIntersector will either rocord or add intersection nodes for the input segment strings.
Parameters
segInt the segment intersector to use
Definition at line 54 of file SegmentSetMutualIntersector.h.
References process(), segInt, and setBaseSegments().
Referenced by geos::noding::FastSegmentSetIntersectionFinder::intersects().
   {
     segInt = si;
   }
Member Data Documentation
SegmentIntersector* geos::noding::SegmentSetMutualIntersector::segInt protected
Definition at line 74 of file SegmentSetMutualIntersector.h.
Referenced by setSegmentIntersector().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/noding/SegmentSetMutualIntersector.h