GEOS: geos::algorithm::MCPointInRing::MCSelecter Class Reference
geos::algorithm::MCPointInRing::MCSelecter Class Reference
#include <MCPointInRing.h>
Public Member Functions
MCSelecter (const geom::Coordinate &newP, MCPointInRing *prt)
void select (const geom::LineSegment &ls) override
virtual void select (MonotoneChain &mc, unsigned int start)
This function can be overridden if the original chain is needed.
Public Attributes
geom::Envelope tempEnv1
Protected Attributes
geom::LineSegment selectedSegment
Private Attributes
geom::Coordinate p
MCPointInRing * parent
Detailed Description
Definition at line 59 of file MCPointInRing.h.
Constructor & Destructor Documentation
geos::algorithm::MCPointInRing::MCSelecter::MCSelecter (const geom::Coordinate & newP, MCPointInRing * prt)
Definition at line 36 of file MCPointInRing.cpp.
References p, and parent.
   :
   MonotoneChainSelectAction()
 {
   p=newP;
   parent=prt;
 }
Member Function Documentation
void geos::index::chain::MonotoneChainSelectAction::select (MonotoneChain & mc, unsigned int start) virtual inherited
This function can be overridden if the original chain is needed.
Reimplemented in geos::noding::snapround::HotPixelSnapAction.
Definition at line 31 of file MonotoneChainSelectAction.cpp.
References geos::index::chain::MonotoneChain::getLineSegment(), and geos::index::chain::MonotoneChainSelectAction::selectedSegment.
Referenced by geos::index::chain::MonotoneChain::computeSelect().
 {
   mc.getLineSegment(start, selectedSegment);
   select(selectedSegment);
 }
void geos::algorithm::MCPointInRing::MCSelecter::select (const geom::LineSegment & seg) override virtual
This is a convenience function which can be overridden to obtain the actual line segment which is selected
Parameters
seg
Implements geos::index::chain::MonotoneChainSelectAction.
Definition at line 47 of file MCPointInRing.cpp.
References p, parent, and geos::algorithm::MCPointInRing::testLineSegment().
 {
   parent->testLineSegment(p, ls);
 }
Member Data Documentation
geom::Coordinate geos::algorithm::MCPointInRing::MCSelecter::p private
Definition at line 62 of file MCPointInRing.h.
Referenced by MCSelecter(), and select().
MCPointInRing* geos::algorithm::MCPointInRing::MCSelecter::parent private
Definition at line 63 of file MCPointInRing.h.
Referenced by MCSelecter(), and select().
geom::LineSegment geos::index::chain::MonotoneChainSelectAction::selectedSegment protected inherited
Definition at line 49 of file MonotoneChainSelectAction.h.
Referenced by geos::index::chain::MonotoneChainSelectAction::select().
geom::Envelope geos::index::chain::MonotoneChainSelectAction::tempEnv1 inherited
Definition at line 70 of file MonotoneChainSelectAction.h.
Referenced by geos::index::chain::MonotoneChain::computeSelect().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/MCPointInRing.h
/home/vicky/potree/geos/vicky/src/algorithm/MCPointInRing.cpp