GEOS: geos::geom::prep::PreparedLineStringIntersects Class Reference
geos::geom::prep::PreparedLineStringIntersects Class Reference
Computes the intersects spatial relationship predicate for a target PreparedLineString relative to all other Geometry classes.
#include <PreparedLineStringIntersects.h>
Public Member Functions
PreparedLineStringIntersects (PreparedLineString &prep)
bool intersects (const geom::Geometry *g) const
Static Public Member Functions
static bool intersects (PreparedLineString &prep, const geom::Geometry *geom)
Protected Member Functions
bool isAnyTestPointInTarget (const geom::Geometry *testGeom) const
PreparedLineStringIntersects (const PreparedLineStringIntersects &other)=delete
PreparedLineStringIntersects & operator= (const PreparedLineStringIntersects &rhs)=delete
Protected Attributes
PreparedLineString & prepLine
Detailed Description
Computes the intersects spatial relationship predicate for a target PreparedLineString relative to all other Geometry classes.
Uses short-circuit tests and indexing to improve performance.
Author
Martin Davis
Definition at line 44 of file PreparedLineStringIntersects.h.
Constructor & Destructor Documentation
geos::geom::prep::PreparedLineStringIntersects::PreparedLineStringIntersects (PreparedLineString & prep) inline
Todo:
FIXME - mloskot: Why not taking linestring through const reference?
Definition at line 65 of file PreparedLineStringIntersects.h.
References intersects().
     : prepLine( prep)
   { }
geos::geom::prep::PreparedLineStringIntersects::PreparedLineStringIntersects (const PreparedLineStringIntersects & other) protected delete
Member Function Documentation
static bool geos::geom::prep::PreparedLineStringIntersects::intersects (PreparedLineString & prep, const geom::Geometry * geom) inline static
Computes the intersects predicate between a PreparedLineString and a Geometry.
Parameters
prep the prepared linestring
geom a test geometry
Returns
true if the linestring intersects the geometry
Definition at line 56 of file PreparedLineStringIntersects.h.
References intersects().
Referenced by intersects(), geos::geom::prep::PreparedLineString::intersects(), and PreparedLineStringIntersects().
   {
     PreparedLineStringIntersects op( prep);
     return op.intersects( geom);
   }
bool geos::geom::prep::PreparedLineStringIntersects::intersects (const geom::Geometry * g) const
Tests whether this geometry intersects a given geometry.
Parameters
geom the test geometry
Returns
true if the test geometry intersects
Definition at line 55 of file PreparedLineStringIntersects.cpp.
References geos::noding::SegmentStringUtil::extractSegmentStrings(), geos::geom::Geometry::getDimension(), and geos::noding::FastSegmentSetIntersectionFinder::intersects().
   {
     // If any segments intersect, obviously intersects = true
     noding::SegmentString::ConstVect lineSegStr;
     noding::SegmentStringUtil::extractSegmentStrings( g, lineSegStr);
     noding::FastSegmentSetIntersectionFinder * fssif = prepLine.getIntersectionFinder();
     bool segsIntersect = fssif->intersects( &lineSegStr);// prepLine.getIntersectionFinder()->intersects(lineSegStr);
     for ( size_t i = 0, ni = lineSegStr.size(); i < ni; i++ ) {
       delete lineSegStr[ i ];
     }
     if ( segsIntersect ) return true;
     // For L/L case we are done
     if ( g->getDimension() == 1 )
       return false;
     // For L/A case, need to check for proper inclusion of the target in the test
     if (  g->getDimension() == 2
       &&  prepLine.isAnyTargetComponentInTest(g) )
       return true;
     // For L/P case, need to check if any points lie on line(s)
     if ( g->getDimension() == 0 )
       return isAnyTestPointInTarget(g);
     return false;
   }
bool geos::geom::prep::PreparedLineStringIntersects::isAnyTestPointInTarget (const geom::Geometry * testGeom) const protected
Tests whether any representative point of the test Geometry intersects the target geometry. Only handles test geometries which are Puntal (dimension 0)
Parameters
geom a Puntal geometry to test
Returns
true if any point of the argument intersects the prepared geometry
This could be optimized by using the segment index on the lineal target. However, it seems like the L/P case would be pretty rare in practice.
Definition at line 35 of file PreparedLineStringIntersects.cpp.
References geos::algorithm::PointLocator::intersects().
   {
     PointLocator  locator;
     geom::Coordinate::ConstVect coords;
     ComponentCoordinateExtracter::getCoordinates( *testGeom, coords);
     for (size_t i=0, n=coords.size(); i<n; i++)
     {
       geom::Coordinate c = *(coords[i]);
       if ( locator.intersects( c, &(prepLine.getGeometry()) ))
         return true;
     }
     return false;
   }
PreparedLineStringIntersects& geos::geom::prep::PreparedLineStringIntersects::operator= (const PreparedLineStringIntersects & rhs) protected delete
Member Data Documentation
PreparedLineString& geos::geom::prep::PreparedLineStringIntersects::prepLine protected
Definition at line 78 of file PreparedLineStringIntersects.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/prep/PreparedLineStringIntersects.h
/home/vicky/potree/geos/vicky/src/geom/prep/PreparedLineStringIntersects.cpp