GEOS: geos::index::quadtree::Node Class Reference
geos::index::quadtree::Node Class Reference
Represents a node of a Quadtree.
#include <Node.h>
Public Member Functions
Node (std::unique_ptr< geom::Envelope > nenv, int nlevel)
~Node () override
geom::Envelope * getEnvelope ()
Node * getNode (const geom::Envelope *searchEnv)
Returns the subquad containing the envelope. Creates the subquad if it does not already exist.
NodeBase * find (const geom::Envelope *searchEnv)
Returns the smallest existing node containing the envelope.
void insertNode (std::unique_ptr< Node > node)
std::string toString () const override
std::vector< void * > & getItems ()
void add (void *item)
std::vector< void * > & addAllItems (std::vector< void * > &resultItems) const
Push all node items to the given vector, return the argument.
virtual void addAllItemsFromOverlapping (const geom::Envelope &searchEnv, std::vector< void * > &resultItems) const
unsigned int depth () const
unsigned int size () const
unsigned int getNodeCount () const
virtual void visit (const geom::Envelope *searchEnv, ItemVisitor &visitor)
bool remove (const geom::Envelope *itemEnv, void *item)
bool hasItems () const
bool hasChildren () const
bool isPrunable () const
Static Public Member Functions
static std::unique_ptr< Node > createNode (const geom::Envelope &env)
static std::unique_ptr< Node > createExpanded (std::unique_ptr< Node > node, const geom::Envelope &addEnv)
Create a node containing the given node and envelope.
static int getSubnodeIndex (const geom::Envelope *env, const geom::Coordinate &centre)
Protected Member Functions
bool isSearchMatch (const geom::Envelope &searchEnv) const override
Protected Attributes
std::vector< void * > items
Actual items are NOT owned by this class.
Node * subnode [4]
Private Member Functions
Node * getSubnode (int index)
std::unique_ptr< Node > createSubnode (int index)
Private Attributes
std::unique_ptr< geom::Envelope > env
Owned by this class.
geom::Coordinate centre
int level
Detailed Description
Represents a node of a Quadtree.
Nodes contain items which have a spatial extent corresponding to the node's position in the quadtree.
Definition at line 55 of file Node.h.
Constructor & Destructor Documentation
geos::index::quadtree::Node::Node (std::unique_ptr< geom::Envelope > nenv, int nlevel) inline
Definition at line 95 of file Node.h.
     :
     env(std::move(nenv)),
     centre((env->getMinX()+env->getMaxX())/2,
       (env->getMinY()+env->getMaxY())/2),
     level(nlevel)
   {
   }
geos::index::quadtree::Node::~Node () inline override
Definition at line 104 of file Node.h.
 {}
Member Function Documentation
void geos::index::quadtree::NodeBase::add (void * item) inherited
Add an item to this node. Ownership of the item is left to caller.
Definition at line 91 of file NodeBase.cpp.
Referenced by geos::index::quadtree::Root::insertContained().
 {
   items.push_back(item);
   //GEOS_DEBUG itemCount++;
   //GEOS_DEBUG System.out.print(itemCount);
 }
vector< void * > & geos::index::quadtree::NodeBase::addAllItems (std::vector< void * > & resultItems) const inherited
Push all node items to the given vector, return the argument.
Definition at line 99 of file NodeBase.cpp.
 {
   // this node may have items as well as subnodes (since items may not
   // be wholely contained in any single subnode
   resultItems.insert(resultItems.end(), items.begin(), items.end());
   for(int i=0; i<4; ++i)
   {
     if ( subnode[i] )
     {
       subnode[i]->addAllItems(resultItems);
     }
   }
   return resultItems;
 }
void geos::index::quadtree::NodeBase::addAllItemsFromOverlapping (const geom::Envelope & searchEnv, std::vector< void * > & resultItems) const virtual inherited
Definition at line 116 of file NodeBase.cpp.
 {
   if (!isSearchMatch(searchEnv))
     return;
   // this node may have items as well as subnodes (since items may not
   // be wholely contained in any single subnode
   resultItems.insert(resultItems.end(), items.begin(), items.end());
   for(int i=0; i<4; ++i)
   {
     if ( subnode[i] )
     {
       subnode[i]->addAllItemsFromOverlapping(searchEnv,
                                              resultItems);
     }
   }
 }
std::unique_ptr< Node > geos::index::quadtree::Node::createExpanded (std::unique_ptr< Node > node, const geom::Envelope & addEnv) static
Create a node containing the given node and envelope.
Parameters
node if not null, will be inserted to the returned node
addEnv minimum envelope to use for the node
Definition at line 57 of file Node.cpp.
References geos::geom::Envelope::expandToInclude(), and geos::geom::Envelope::toString().
 {
   Envelope expandEnv(addEnv);
   if ( node.get() ) // should this be asserted ?
   {
     expandEnv.expandToInclude(node->getEnvelope());
   }
 #if GEOS_DEBUG
   cerr<<"Node::createExpanded computed "<<expandEnv.toString()<<endl;
 #endif
   std::unique_ptr<Node> largerNode = createNode(expandEnv);
   if ( node.get() ) // should this be asserted ?
   {
     largerNode->insertNode(std::move(node));
   }
   return largerNode;
 }
std::unique_ptr< Node > geos::index::quadtree::Node::createNode (const geom::Envelope & env) static
Definition at line 45 of file Node.cpp.
References geos::index::quadtree::Key::getEnvelope(), and geos::index::quadtree::Key::getLevel().
 {
   Key key(env);
   std::unique_ptr<Envelope> envelope(new Envelope(key.getEnvelope()));
   std::unique_ptr<Node> node (
     new Node(std::move(envelope), key.getLevel())
   );
   return std::move(node);
 }
std::unique_ptr< Node > geos::index::quadtree::Node::createSubnode (int index) private
Definition at line 156 of file Node.cpp.
 {
   // create a new subquad in the appropriate quadrant
   double minx=0.0;
   double maxx=0.0;
   double miny=0.0;
   double maxy=0.0;
   switch (index) {
     case 0:
       minx=env->getMinX();
       maxx=centre.x;
       miny=env->getMinY();
       maxy=centre.y;
       break;
     case 1:
       minx=centre.x;
       maxx=env->getMaxX();
       miny=env->getMinY();
       maxy=centre.y;
       break;
     case 2:
       minx=env->getMinX();
       maxx=centre.x;
       miny=centre.y;
       maxy=env->getMaxY();
       break;
     case 3:
       minx=centre.x;
       maxx=env->getMaxX();
       miny=centre.y;
       maxy=env->getMaxY();
       break;
   }
   std::unique_ptr<Envelope> sqEnv ( new Envelope(minx,maxx,miny,maxy) );
   std::unique_ptr<Node> node ( new Node(std::move(sqEnv), level-1) );
   return node;
 }
unsigned int geos::index::quadtree::NodeBase::depth () const inherited
Definition at line 139 of file NodeBase.cpp.
 {
   unsigned int maxSubDepth=0;
   for (int i=0; i<4; ++i)
   {
     if (subnode[i] != nullptr)
     {
       unsigned int sqd=subnode[i]->depth();
       if ( sqd > maxSubDepth )
         maxSubDepth=sqd;
     }
   }
   return maxSubDepth + 1;
 }
NodeBase * geos::index::quadtree::Node::find (const geom::Envelope * searchEnv)
Returns the smallest existing node containing the envelope.
Definition at line 99 of file Node.cpp.
References find().
Referenced by find(), and geos::index::quadtree::Root::insertContained().
 {
   int subnodeIndex=getSubnodeIndex(searchEnv, centre);
   if (subnodeIndex==-1)
     return this;
   if (subnode[subnodeIndex]!=nullptr) {
     // query lies in subquad, so search it
     Node *node=subnode[subnodeIndex];
     return node->find(searchEnv);
   }
   // no existing subquad, so return this one anyway
   return this;
 }
geom::Envelope* geos::index::quadtree::Node::getEnvelope () inline
Return Envelope associated with this node ownership retained by this object
Definition at line 108 of file Node.h.
Referenced by geos::index::quadtree::Root::insert(), and geos::index::quadtree::Root::insertContained().
 { return env.get(); }
vector< void * > & geos::index::quadtree::NodeBase::getItems () inherited
Definition at line 85 of file NodeBase.cpp.
 {
   return items;
 }
Node * geos::index::quadtree::Node::getNode (const geom::Envelope * searchEnv)
Returns the subquad containing the envelope. Creates the subquad if it does not already exist.
Definition at line 80 of file Node.cpp.
References getNode().
Referenced by getNode(), and geos::index::quadtree::Root::insertContained().
 {
   int subnodeIndex = getSubnodeIndex(searchEnv, centre);
   // if subquadIndex is -1 searchEnv is not contained in a subquad
   if (subnodeIndex != -1)
   {
     // create the quad if it does not exist
     Node *node = getSubnode(subnodeIndex);
     // recursively search the found/created quad
     return node->getNode(searchEnv);
   }
   else
   {
     return this;
   }
 }
unsigned int geos::index::quadtree::NodeBase::getNodeCount () const inherited
Definition at line 169 of file NodeBase.cpp.
 {
   unsigned int subSize=0;
   for(int i=0; i<4; ++i)
   {
     if (subnode[i] != nullptr)
     {
       subSize += subnode[i]->size();
     }
   }
   return subSize + 1;
 }
Node * geos::index::quadtree::Node::getSubnode (int index) private
Get the subquad for the index. If it doesn't exist, create it.
Ownership of the returned object belongs to this class.
Definition at line 145 of file Node.cpp.
 {
   assert(index >=0 && index < 4);
   if (subnode[index] == nullptr)
   {
     subnode[index] = createSubnode(index).release();
   }
   return subnode[index];
 }
int geos::index::quadtree::NodeBase::getSubnodeIndex (const geom::Envelope * env, const geom::Coordinate & centre) static inherited
Definition at line 47 of file NodeBase.cpp.
References geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), geos::geom::Coordinate::toString(), geos::geom::Envelope::toString(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   int subnodeIndex=-1;
   if (env->getMinX()>=centre.x) {
     if (env->getMinY()>=centre.y) subnodeIndex=3;
     if (env->getMaxY()<=centre.y) subnodeIndex=1;
   }
   if (env->getMaxX()<=centre.x) {
     if (env->getMinY()>=centre.y) subnodeIndex=2;
     if (env->getMaxY()<=centre.y) subnodeIndex=0;
   }
 #if GEOS_DEBUG
   cerr<<"getSubNodeIndex("<<env->toString()<<", "<<centre.toString()<<") returning "<<subnodeIndex<<endl;
 #endif
   return subnodeIndex;
 }
bool geos::index::quadtree::NodeBase::hasChildren () const inline inherited
Definition at line 131 of file NodeBase.h.
 {
   for (int i = 0; i < 4; i++)
     if (subnode[i]) return true;
   return false;
 }
bool geos::index::quadtree::NodeBase::hasItems () const inline inherited
Definition at line 145 of file NodeBase.h.
 {
   return ! items.empty();
 }
void geos::index::quadtree::Node::insertNode (std::unique_ptr< Node > node)
Definition at line 114 of file Node.cpp.
 {
   assert( env->contains(node->getEnvelope()) );
   int index = getSubnodeIndex(node->getEnvelope(), centre);
   assert(index >= 0);
   if (node->level == level-1)
   {
     // We take ownership of node
     delete subnode[index];
     subnode[index] = node.release();
     //System.out.println("inserted");
   }
   else
   {
     // the quad is not a direct child, so make a new child
     // quad to contain it and recursively insert the quad
     std::unique_ptr<Node> childNode ( createSubnode(index) );
     // childNode takes ownership of node
     childNode->insertNode(std::move(node));
     // We take ownership of childNode
     delete subnode[index];
     subnode[index] = childNode.release();
   }
 }
bool geos::index::quadtree::NodeBase::isPrunable () const inline inherited
Definition at line 139 of file NodeBase.h.
 {
   return ! (hasChildren() || hasItems());
 }
bool geos::index::quadtree::Node::isSearchMatch (const geom::Envelope & searchEnv) const inline override protected virtual
Implements geos::index::quadtree::NodeBase.
Definition at line 78 of file Node.h.
{
     return env->intersects(searchEnv);
   }
bool geos::index::quadtree::NodeBase::remove (const geom::Envelope * itemEnv, void * item) inherited
Removes a single item from this subtree.
Parameters
searchEnv the envelope containing the item
item the item to remove
Returns
true if the item was found and removed
Definition at line 232 of file NodeBase.cpp.
 {
   // use envelope to restrict nodes scanned
   if (! isSearchMatch(*itemEnv)) return false;
   bool found = false;
   for (int i = 0; i < 4; ++i)
   {
     if ( subnode[i] )
     {
       found = subnode[i]->remove(itemEnv, item);
       if (found)
       {
         // trim subtree if empty
         if (subnode[i]->isPrunable())
         {
           delete subnode[i];
           subnode[i] = nullptr;
         }
         break;
       }
     }
   }
   // if item was found lower down, don't need to search for it here
   if (found) return found;
   // otherwise, try and remove the item from the list of items
   // in this node
   vector<void*>::iterator foundIter =
     find(items.begin(), items.end(), item);
   if ( foundIter != items.end() ) {
     items.erase(foundIter);
     return true;
   } else {
     return false;
   }
 }
unsigned int geos::index::quadtree::NodeBase::size () const inherited
Definition at line 155 of file NodeBase.cpp.
 {
   unsigned int subSize=0;
   for(int i=0; i<4; i++)
   {
     if (subnode[i] != nullptr)
     {
       subSize += subnode[i]->size();
     }
   }
   return subSize + static_cast<unsigned int>(items.size());
 }
string geos::index::quadtree::Node::toString (void) const override virtual
Reimplemented from geos::index::quadtree::NodeBase.
Definition at line 196 of file Node.cpp.
 {
   ostringstream os;
   os <<"L"<<level<<" "<<env->toString()<<" Ctr["<<centre.toString()<<"]";
   os <<" "+NodeBase::toString();
   return os.str();
 }
void geos::index::quadtree::NodeBase::visit (const geom::Envelope * searchEnv, ItemVisitor & visitor) virtual inherited
Definition at line 200 of file NodeBase.cpp.
Referenced by geos::index::quadtree::Quadtree::query().
 {
   if (! isSearchMatch(*searchEnv)) return;
   // this node may have items as well as subnodes (since items may not
   // be wholely contained in any single subnode
   visitItems(searchEnv, visitor);
   for (int i = 0; i < 4; i++) {
     if (subnode[i] != nullptr) {
       subnode[i]->visit(searchEnv, visitor);
     }
   }
 }
Member Data Documentation
geom::Coordinate geos::index::quadtree::Node::centre private
Definition at line 62 of file Node.h.
std::unique_ptr<geom::Envelope> geos::index::quadtree::Node::env private
Owned by this class.
Definition at line 60 of file Node.h.
std::vector<void*> geos::index::quadtree::NodeBase::items protected inherited
Actual items are NOT owned by this class.
Definition at line 110 of file NodeBase.h.
int geos::index::quadtree::Node::level private
Definition at line 64 of file Node.h.
Node* geos::index::quadtree::NodeBase::subnode[4] protected inherited
subquads are numbered as follows:
 2 | 3
 --+--
 0 | 1
Nodes are owned by this class
Definition at line 122 of file NodeBase.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/quadtree/Node.h
/home/vicky/potree/geos/vicky/src/index/quadtree/Node.cpp