GEOS: geos::index::chain::MonotoneChainBuilder Class Reference
geos::index::chain::MonotoneChainBuilder Class Reference
Constructs MonotoneChains for sequences of Coordinates.
#include <MonotoneChainBuilder.h>
Public Member Functions
MonotoneChainBuilder ()
Static Public Member Functions
static std::vector< MonotoneChain * > * getChains (const geom::CoordinateSequence *pts, void *context)
Return a newly-allocated vector of newly-allocated MonotoneChain objects for the given CoordinateSequence. Remember to deep-delete the result.
static void getChains (const geom::CoordinateSequence *pts, void *context, std::vector< MonotoneChain * > &mcList)
Fill the provided vector with newly-allocated MonotoneChain objects for the given CoordinateSequence. Remember to delete vector elements!
static std::vector< MonotoneChain * > * getChains (const geom::CoordinateSequence *pts)
static void getChainStartIndices (const geom::CoordinateSequence &pts, std::vector< std::size_t > &startIndexList)
Fill the given vector with start/end indexes of the monotone chains for the given CoordinateSequence. The last entry in the array points to the end point of the point array, for use as a sentinel.
Static Private Member Functions
static std::size_t findChainEnd (const geom::CoordinateSequence &pts, std::size_t start)
Detailed Description
Constructs MonotoneChains for sequences of Coordinates.
TODO: use vector<const Coordinate*> instead ?
Definition at line 48 of file MonotoneChainBuilder.h.
Constructor & Destructor Documentation
geos::index::chain::MonotoneChainBuilder::MonotoneChainBuilder () inline
Definition at line 52 of file MonotoneChainBuilder.h.
 {}
Member Function Documentation
std::size_t geos::index::chain::MonotoneChainBuilder::findChainEnd (const geom::CoordinateSequence & pts, std::size_t start) static private
Finds the index of the last point in a monotone chain starting at a given point. Any repeated points (0-length segments) will be included in the monotone chain returned.
Returns
the index of the last point in the monotone chain starting at start.
NOTE: aborts if 'start' is >= pts.getSize()
Definition at line 93 of file MonotoneChainBuilder.cpp.
References geos::geom::CoordinateSequence::getSize().
 {
   const std::size_t npts = pts.getSize(); // cache
   assert(start < npts);
   assert(npts); // should be implied by the assertion above,
                 // 'start' being unsigned
   std::size_t safeStart = start;
         // skip any zero-length segments at the start of the sequence
         // (since they cannot be used to establish a quadrant)
   while ( safeStart < npts - 1
     && pts[safeStart].equals2D(pts[safeStart+1]) )
   {
     ++safeStart;
   }
   // check if there are NO non-zero-length segments
   if (safeStart >= npts - 1) {
     return npts - 1;
   }
   // determine overall quadrant for chain
   // (which is the starting quadrant)
   int chainQuad = Quadrant::quadrant(pts[safeStart],
                                      pts[safeStart + 1]);
   std::size_t last = start + 1;
   while (last < npts)
   {
     // skip zero-length segments, but include them in the chain
     if (! pts[last - 1].equals2D( pts[last] ) )
     {
       // compute quadrant for next possible segment in chain
       int quad = Quadrant::quadrant( pts[last - 1],
                                      pts[last]      );
       if (quad != chainQuad) break;
     }
     ++last;
   }
 #if GEOS_DEBUG
   std::cerr<<"MonotoneChainBuilder::findChainEnd() returning"<<std::endl;
 #endif
   return last - 1;
 }
vector< MonotoneChain * > * geos::index::chain::MonotoneChainBuilder::getChains (const geom::CoordinateSequence * pts, void * context) static
Return a newly-allocated vector of newly-allocated MonotoneChain objects for the given CoordinateSequence. Remember to deep-delete the result.
Definition at line 46 of file MonotoneChainBuilder.cpp.
Referenced by geos::noding::MCIndexSegmentSetMutualIntersector::addToIndex(), and geos::noding::MCIndexSegmentSetMutualIntersector::addToMonoChains().
 {
   vector<MonotoneChain*>* mcList = new vector<MonotoneChain*>();
   getChains(pts, context, *mcList);
   return mcList;
 }
void geos::index::chain::MonotoneChainBuilder::getChains (const geom::CoordinateSequence * pts, void * context, std::vector< MonotoneChain * > & mcList) static
Fill the provided vector with newly-allocated MonotoneChain objects for the given CoordinateSequence. Remember to delete vector elements!
Definition at line 55 of file MonotoneChainBuilder.cpp.
 {
   vector<std::size_t> startIndex;
   getChainStartIndices(*pts, startIndex);
   std::size_t nindexes = startIndex.size();
   if (nindexes > 0)
   {
     std::size_t n = nindexes - 1;
     for(std::size_t i = 0; i < n; i++)
     {
       MonotoneChain* mc = new MonotoneChain(*pts, startIndex[i], startIndex[i+1], context);
       mcList.push_back(mc);
     }
   }
 }
static std::vector<MonotoneChain*>* geos::index::chain::MonotoneChainBuilder::getChains (const geom::CoordinateSequence * pts) inline static
Definition at line 72 of file MonotoneChainBuilder.h.
   {
     return getChains(pts, nullptr);
   }
void geos::index::chain::MonotoneChainBuilder::getChainStartIndices (const geom::CoordinateSequence & pts, std::vector< std::size_t > & startIndexList) static
Fill the given vector with start/end indexes of the monotone chains for the given CoordinateSequence. The last entry in the array points to the end point of the point array, for use as a sentinel.
Definition at line 74 of file MonotoneChainBuilder.cpp.
References geos::geom::CoordinateSequence::getSize().
 {
   // find the startpoint (and endpoints) of all monotone chains
   // in this edge
   std::size_t start = 0;
   startIndexList.push_back(start);
   const std::size_t n = pts.getSize() - 1;
   do
   {
     std::size_t last = findChainEnd(pts, start);
     startIndexList.push_back(last);
     start = last;
   } while (start < n);
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/chain/MonotoneChainBuilder.h
/home/vicky/potree/geos/vicky/src/index/chain/MonotoneChainBuilder.cpp