GEOS: geos::operation::polygonize::EdgeRing Class Reference
geos::operation::polygonize::EdgeRing Class Reference
Represents a ring of PolygonizeDirectedEdge which form a ring of a polygon. The ring may be either an outer shell or a hole.
#include <EdgeRing.h>
Public Member Functions
EdgeRing (const geom::GeometryFactory *newFactory)
~EdgeRing ()
void add (const planargraph::DirectedEdge *de)
Adds a DirectedEdge which is known to form part of this ring.
bool isHole ()
Tests whether this ring is a hole.
void addHole (geom::LinearRing *hole)
Adds a hole to the polygon formed by this ring.
geom::Polygon * getPolygon ()
Computes the Polygon formed by this ring and any contained holes.
bool isValid ()
Tests if the LinearRing ring formed by this edge ring is topologically valid.
geom::LineString * getLineString ()
Gets the coordinates for this ring as a LineString.
geom::LinearRing * getRingInternal ()
Returns this ring as a LinearRing, or null if an Exception occurs while creating it (such as a topology problem).
geom::LinearRing * getRingOwnership ()
Returns this ring as a LinearRing, or null if an Exception occurs while creating it (such as a topology problem).
Static Public Member Functions
static EdgeRing * findEdgeRingContaining (EdgeRing *testEr, std::vector< EdgeRing * > *shellList)
Find the innermost enclosing shell EdgeRing containing the argument EdgeRing, if any.
static const geom::Coordinate & ptNotInList (const geom::CoordinateSequence *testPts, const geom::CoordinateSequence *pts)
Finds a point in a list of points which is not contained in another list of points.
static bool isInList (const geom::Coordinate &pt, const geom::CoordinateSequence *pts)
Tests whether a given point is in an array of points. Uses a value-based test.
Private Types
typedef std::vector< const planargraph::DirectedEdge * > DeList
typedef std::vector< geom::Geometry * > GeomVect
Private Member Functions
geom::CoordinateSequence * getCoordinates ()
Computes the list of coordinates which are contained in this ring. The coordinatea are computed once only and cached.
Static Private Member Functions
static void addEdge (const geom::CoordinateSequence *coords, bool isForward, geom::CoordinateSequence *coordList)
Private Attributes
const geom::GeometryFactory * factory
DeList deList
geom::LinearRing * ring
geom::CoordinateSequence * ringPts
GeomVect * holes
Detailed Description
Represents a ring of PolygonizeDirectedEdge which form a ring of a polygon. The ring may be either an outer shell or a hole.
Definition at line 57 of file EdgeRing.h.
Member Typedef Documentation
typedef std::vector<const planargraph::DirectedEdge*> geos::operation::polygonize::EdgeRing::DeList private
Definition at line 61 of file EdgeRing.h.
typedef std::vector<geom::Geometry*> geos::operation::polygonize::EdgeRing::GeomVect private
Definition at line 68 of file EdgeRing.h.
Constructor & Destructor Documentation
geos::operation::polygonize::EdgeRing::EdgeRing (const geom::GeometryFactory * newFactory)
Definition at line 128 of file EdgeRing.cpp.
     :
     factory(newFactory),
     ring(nullptr),
     ringPts(nullptr),
     holes(nullptr)
 {
 #ifdef DEBUG_ALLOC
     cerr<<"["<<this<<"] EdgeRing(factory)"<<endl;
 #endif // DEBUG_ALLOC
 }
geos::operation::polygonize::EdgeRing::~EdgeRing ()
Definition at line 140 of file EdgeRing.cpp.
References holes, ring, and ringPts.
 {
 #ifdef DEBUG_ALLOC
     cerr<<"["<<this<<"] ~EdgeRing()"<<endl;
 #endif // DEBUG_ALLOC
     if ( holes )
     {
         for (GeomVect::size_type i=0, e=holes->size(); i<e; ++i)
             delete (*holes)[i];
         delete holes;
     }
     delete ring;
     delete ringPts;
 }
Member Function Documentation
void geos::operation::polygonize::EdgeRing::add (const planargraph::DirectedEdge * de)
Adds a DirectedEdge which is known to form part of this ring.
Parameters
de the DirectedEdge to add. Ownership to the caller.
Definition at line 157 of file EdgeRing.cpp.
References deList.
Referenced by geos::operation::polygonize::PolygonizeGraph::findEdgeRing().
{
     deList.push_back(de);
 }
void geos::operation::polygonize::EdgeRing::addEdge (const geom::CoordinateSequence * coords, bool isForward, geom::CoordinateSequence * coordList) static private
Definition at line 253 of file EdgeRing.cpp.
References geos::geom::CoordinateSequence::add(), geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
Referenced by getCoordinates().
 {
     const std::size_t npts=coords->getSize();
     if (isForward)
     {
         for (std::size_t i = 0; i < npts; ++i)
         {
             coordList->add(coords->getAt(i), false);
         }
     }
     else
     {
         for (std::size_t i = npts; i > 0; --i)
         {
             coordList->add(coords->getAt(i-1), false);
         }
     }
 }
void geos::operation::polygonize::EdgeRing::addHole (geom::LinearRing * hole)
Adds a hole to the polygon formed by this ring.
Parameters
hole the LinearRing forming the hole.
Definition at line 170 of file EdgeRing.cpp.
References holes.
 {
     if (holes==nullptr)
         holes=new vector<Geometry*>();
     holes->push_back(hole);
 }
EdgeRing * geos::operation::polygonize::EdgeRing::findEdgeRingContaining (EdgeRing * testEr, std::vector< EdgeRing * > * shellList) static
Find the innermost enclosing shell EdgeRing containing the argument EdgeRing, if any.
The innermost enclosing ring is the smallest enclosing ring. The algorithm used depends on the fact that:
ring A contains ring B iff envelope(ring A) contains envelope(ring B)
This routine is only safe to use if the chosen point of the hole is known to be properly contained in a shell (which is guaranteed to be the case if the hole does not touch its shell)
Returns
containing EdgeRing, if there is one
null if no containing EdgeRing is found
Definition at line 50 of file EdgeRing.cpp.
References geos::geom::Envelope::contains(), geos::geom::Envelope::equals(), geos::geom::LineString::getCoordinateN(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getEnvelopeInternal(), and getRingInternal().
Referenced by geos::operation::polygonize::Polygonizer::assignHoleToShell().
 {
     const LinearRing *testRing=testEr->getRingInternal();
     if ( ! testRing ) return nullptr;
     const Envelope *testEnv=testRing->getEnvelopeInternal();
     Coordinate testPt=testRing->getCoordinateN(0);
     EdgeRing *minShell=nullptr;
     const Envelope *minEnv=nullptr;
     typedef std::vector<EdgeRing*> ERList;
     for(ERList::size_type i=0, e=shellList->size(); i<e; ++i) {
         EdgeRing *tryShell=(*shellList)[i];
         LinearRing *tryRing=tryShell->getRingInternal();
         const Envelope *tryEnv=tryRing->getEnvelopeInternal();
         if (minShell!=nullptr) minEnv=minShell->getRingInternal()->getEnvelopeInternal();
         bool isContained=false;
         // the hole envelope cannot equal the shell envelope
         if (tryEnv->equals(testEnv)) continue;
         const CoordinateSequence *tryCoords =
             tryRing->getCoordinatesRO();
         if ( tryEnv->contains(testEnv) ) {
             // TODO: don't copy testPt !
             testPt = ptNotInList(testRing->getCoordinatesRO(), tryCoords);
             if ( CGAlgorithms::isPointInRing(testPt, tryCoords) ) {
                 isContained=true;
             }
     }
         // check if this new containing ring is smaller
         // than the current minimum ring
         if (isContained) {
             if (minShell==nullptr || minEnv->contains(tryEnv)) {
                 minShell=tryShell;
             }
         }
     }
     return minShell;
 }
CoordinateSequence * geos::operation::polygonize::EdgeRing::getCoordinates (void) private
Computes the list of coordinates which are contained in this ring. The coordinatea are computed once only and cached.
Returns
an array of the Coordinate in this ring
Definition at line 197 of file EdgeRing.cpp.
References addEdge(), geos::geom::CoordinateSequenceFactory::create(), deList, factory, geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::geom::LineString::getCoordinatesRO(), geos::planargraph::DirectedEdge::getEdge(), geos::planargraph::DirectedEdge::getEdgeDirection(), geos::operation::polygonize::PolygonizeEdge::getLine(), and ringPts.
Referenced by getLineString(), and getRingInternal().
 {
     if (ringPts==nullptr)
     {
         ringPts=factory->getCoordinateSequenceFactory()->create();
         for (DeList::size_type i=0, e=deList.size(); i<e; ++i) {
             const DirectedEdge *de=deList[i];
             assert(dynamic_cast<PolygonizeEdge*>(de->getEdge()));
             PolygonizeEdge *edge=static_cast<PolygonizeEdge*>(de->getEdge());
             addEdge(edge->getLine()->getCoordinatesRO(),
                 de->getEdgeDirection(), ringPts);
         }
     }
     return ringPts;
 }
LineString * geos::operation::polygonize::EdgeRing::getLineString ()
Gets the coordinates for this ring as a LineString.
Used to return the coordinates in this ring as a valid geometry, when it has been detected that the ring is topologically invalid.
Returns
a LineString containing the coordinates in this ring
Definition at line 215 of file EdgeRing.cpp.
References geos::geom::GeometryFactory::createLineString(), factory, getCoordinates(), and ringPts.
 {
     getCoordinates();
     return factory->createLineString(*ringPts);
 }
Polygon * geos::operation::polygonize::EdgeRing::getPolygon ()
Computes the Polygon formed by this ring and any contained holes.
LinearRings ownership is transferred to returned polygon. Subsequent calls to the function will return NULL.
Returns
the Polygon formed by this ring and its holes.
Definition at line 179 of file EdgeRing.cpp.
References geos::geom::GeometryFactory::createPolygon(), factory, holes, poly, and ring.
 {
     Polygon *poly=factory->createPolygon(ring, holes);
     ring=nullptr;
     holes=nullptr;
     return poly;
 }
LinearRing * geos::operation::polygonize::EdgeRing::getRingInternal ()
Returns this ring as a LinearRing, or null if an Exception occurs while creating it (such as a topology problem).
Ownership of ring is retained by the object. Details of problems are written to standard output.
Definition at line 223 of file EdgeRing.cpp.
References geos::geom::GeometryFactory::createLinearRing(), factory, getCoordinates(), geos::ignore_unused_variable_warning(), ring, ringPts, and geos::util::GEOSException::what().
Referenced by findEdgeRingContaining(), getRingOwnership(), isHole(), and isValid().
 {
     if (ring!=nullptr) return ring;
     getCoordinates();
     try {
         ring=factory->createLinearRing(*ringPts);
     } catch (const geos::util::IllegalArgumentException& e) {
 #if GEOS_DEBUG
         // FIXME: print also ringPts
         std::cerr << "EdgeRing::getRingInternal: "
                   << e.what()
                   << endl;
 #endif
         ::geos::ignore_unused_variable_warning(e);
     }
     return ring;
 }
LinearRing * geos::operation::polygonize::EdgeRing::getRingOwnership ()
Returns this ring as a LinearRing, or null if an Exception occurs while creating it (such as a topology problem).
Details of problems are written to standard output. Caller gets ownership of ring.
Definition at line 244 of file EdgeRing.cpp.
References getRingInternal(), and ring.
Referenced by geos::operation::polygonize::Polygonizer::assignHoleToShell().
 {
     LinearRing *ret = getRingInternal();
     ring = nullptr;
     return ret;
 }
bool geos::operation::polygonize::EdgeRing::isHole ()
Tests whether this ring is a hole.
Due to the way the edges in the polyongization graph are linked, a ring is a hole if it is oriented counter-clockwise.
Returns
true if this ring is a hole
Definition at line 163 of file EdgeRing.cpp.
References geos::geom::LineString::getCoordinatesRO(), getRingInternal(), and ring.
                 {
     getRingInternal();
     return CGAlgorithms::isCCW(ring->getCoordinatesRO());
 }
bool geos::operation::polygonize::EdgeRing::isInList (const geom::Coordinate & pt, const geom::CoordinateSequence * pts) static
Tests whether a given point is in an array of points. Uses a value-based test.
Parameters
pt a Coordinate for the test point
pts an array of Coordinate to test
Returns
true if the point is in the array
Definition at line 115 of file EdgeRing.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
     const std::size_t npts = pts->getSize();
     for (std::size_t i = 0; i < npts; ++i)
     {
         if (pt == pts->getAt(i))
             return false;
     }
     return true;
 }
bool geos::operation::polygonize::EdgeRing::isValid ()
Tests if the LinearRing ring formed by this edge ring is topologically valid.
Definition at line 189 of file EdgeRing.cpp.
References getRingInternal(), geos::geom::Geometry::isValid(), and ring.
 {
     if ( ! getRingInternal() ) return false; // computes cached ring
     return ring->isValid();
 }
const Coordinate & geos::operation::polygonize::EdgeRing::ptNotInList (const geom::CoordinateSequence * testPts, const geom::CoordinateSequence * pts) static
Finds a point in a list of points which is not contained in another list of points.
Parameters
testPts the CoordinateSequence to test
pts the CoordinateSequence to test the input points against
Returns
a Coordinate reference from testPts which is not in pts, or Coordinate::nullCoord
Definition at line 99 of file EdgeRing.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
     const std::size_t npts = testPts->getSize();
     for (std::size_t i = 0; i < npts; ++i)
     {
         const Coordinate& testPt = testPts->getAt(i);
         // TODO: shouldn't this be ! isInList ?
         if (isInList(testPt, pts))
             return testPt;
     }
     return Coordinate::getNull();
 }
Member Data Documentation
DeList geos::operation::polygonize::EdgeRing::deList private
Definition at line 62 of file EdgeRing.h.
Referenced by add(), and getCoordinates().
const geom::GeometryFactory* geos::operation::polygonize::EdgeRing::factory private
Definition at line 59 of file EdgeRing.h.
Referenced by getCoordinates(), getLineString(), getPolygon(), and getRingInternal().
GeomVect* geos::operation::polygonize::EdgeRing::holes private
Definition at line 69 of file EdgeRing.h.
Referenced by addHole(), getPolygon(), and ~EdgeRing().
geom::LinearRing* geos::operation::polygonize::EdgeRing::ring private
Definition at line 65 of file EdgeRing.h.
Referenced by getPolygon(), getRingInternal(), getRingOwnership(), isHole(), isValid(), and ~EdgeRing().
geom::CoordinateSequence* geos::operation::polygonize::EdgeRing::ringPts private
Definition at line 66 of file EdgeRing.h.
Referenced by getCoordinates(), getLineString(), getRingInternal(), and ~EdgeRing().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/polygonize/EdgeRing.h
/home/vicky/potree/geos/vicky/src/operation/polygonize/EdgeRing.cpp