GEOS: geos::operation::relate::RelateOp Class Reference
geos::operation::relate::RelateOp Class Reference
Implements the SFS relate() operation on two geom::Geometry objects.
#include <RelateOp.h>
Public Member Functions
RelateOp (const geom::Geometry *g0, const geom::Geometry *g1)
Creates a new Relate operation, using the default (OGC SFS) Boundary Node Rule.
RelateOp (const geom::Geometry *g0, const geom::Geometry *g1, const algorithm::BoundaryNodeRule &boundaryNodeRule)
Creates a new Relate operation with a specified Boundary Node Rule.
~RelateOp () override
geom::IntersectionMatrix * getIntersectionMatrix ()
Gets the IntersectionMatrix for the spatial relationship between the input geometries.
const geom::Geometry * getArgGeometry (unsigned int i) const
Static Public Member Functions
static geom::IntersectionMatrix * relate (const geom::Geometry *a, const geom::Geometry *b)
Computes the geom::IntersectionMatrix for the spatial relationship between two geom::Geometry objects, using the default (OGC SFS) Boundary Node Rule.
static geom::IntersectionMatrix * relate (const geom::Geometry *a, const geom::Geometry *b, const algorithm::BoundaryNodeRule &boundaryNodeRule)
Computes the geom::IntersectionMatrix for the spatial relationship between two geom::Geometry objects, using a specified Boundary Node Rule.
Protected Member Functions
void setComputationPrecision (const geom::PrecisionModel *pm)
Protected Attributes
algorithm::LineIntersector li
const geom::PrecisionModel * resultPrecisionModel
std::vector< geomgraph::GeometryGraph * > arg
The operation args into an array so they can be accessed by index.
Private Attributes
RelateComputer relateComp
Detailed Description
Implements the SFS relate() operation on two geom::Geometry objects.
This class supports specifying a custom algorithm::BoundaryNodeRule to be used during the relate computation.
Note: custom Boundary Node Rules do not (currently) affect the results of other Geometry methods (such as Geometry::getBoundary. The results of these methods may not be consistent with the relationship computed by a custom Boundary Node Rule.
Definition at line 57 of file RelateOp.h.
Constructor & Destructor Documentation
geos::operation::relate::RelateOp::RelateOp (const geom::Geometry * g0, const geom::Geometry * g1)
Creates a new Relate operation, using the default (OGC SFS) Boundary Node Rule.
Parameters
g0 a Geometry to relate. Ownership left to caller.
g1 another Geometry to relate. Ownership to caller.
Definition at line 53 of file RelateOp.cpp.
                                                         :
   GeometryGraphOperation(g0, g1),
   relateComp(&arg)
 {
 }
geos::operation::relate::RelateOp::RelateOp (const geom::Geometry * g0, const geom::Geometry * g1, const algorithm::BoundaryNodeRule & boundaryNodeRule)
Creates a new Relate operation with a specified Boundary Node Rule.
Parameters
g0 a Geometry to relate. Ownership left to caller.
g1 another Geometry to relate. Ownership to caller.
boundaryNodeRule the Boundary Node Rule to use
Definition at line 59 of file RelateOp.cpp.
   :
   GeometryGraphOperation(g0, g1, boundaryNodeRule),
   relateComp(&arg)
 {
 }
geos::operation::relate::RelateOp::~RelateOp () override
Definition at line 67 of file RelateOp.cpp.
 {
 }
Member Function Documentation
const Geometry * geos::operation::GeometryGraphOperation::getArgGeometry (unsigned int i) const inherited
Definition at line 96 of file GeometryGraphOperation.cpp.
References geos::operation::GeometryGraphOperation::arg.
Referenced by geos::operation::overlay::OverlayOp::computeOverlay(), and geos::operation::overlay::LineBuilder::labelIsolatedLine().
 {
   assert(i<arg.size());
   return arg[i]->getGeometry();
 }
IntersectionMatrix * geos::operation::relate::RelateOp::getIntersectionMatrix ()
Gets the IntersectionMatrix for the spatial relationship between the input geometries.
Returns
the geom::IntersectionMatrix for the spatial relationship between the input geometries. Ownership transferred.
Definition at line 72 of file RelateOp.cpp.
References geos::operation::relate::RelateComputer::computeIM(), and relateComp.
Referenced by relate().
 {
   return relateComp.computeIM();
 }
IntersectionMatrix * geos::operation::relate::RelateOp::relate (const geom::Geometry * a, const geom::Geometry * b) static
Computes the geom::IntersectionMatrix for the spatial relationship between two geom::Geometry objects, using the default (OGC SFS) Boundary Node Rule.
Parameters
a a Geometry to test. Ownership left to caller.
b a Geometry to test. Ownership left to caller.
Returns
the IntersectonMatrix for the spatial relationship between the geometries. Ownership transferred.
Definition at line 39 of file RelateOp.cpp.
References getIntersectionMatrix().
 {
   RelateOp relOp(a,b);
   return relOp.getIntersectionMatrix();
 }
IntersectionMatrix * geos::operation::relate::RelateOp::relate (const geom::Geometry * a, const geom::Geometry * b, const algorithm::BoundaryNodeRule & boundaryNodeRule) static
Computes the geom::IntersectionMatrix for the spatial relationship between two geom::Geometry objects, using a specified Boundary Node Rule.
Parameters
a a Geometry to test. Ownership left to caller.
b a Geometry to test. Ownership left to caller.
boundaryNodeRule the Boundary Node Rule to use.
Returns
the IntersectonMatrix for the spatial relationship between the geometries. Ownership transferred.
Definition at line 46 of file RelateOp.cpp.
References getIntersectionMatrix().
 {
   RelateOp relOp(a, b, boundaryNodeRule);
   return relOp.getIntersectionMatrix();
 }
void geos::operation::GeometryGraphOperation::setComputationPrecision (const geom::PrecisionModel * pm) protected inherited
Definition at line 104 of file GeometryGraphOperation.cpp.
References geos::operation::GeometryGraphOperation::li, geos::operation::GeometryGraphOperation::resultPrecisionModel, and geos::algorithm::LineIntersector::setPrecisionModel().
Referenced by geos::operation::GeometryGraphOperation::GeometryGraphOperation().
 {
   assert(pm);
   resultPrecisionModel=pm;
   li.setPrecisionModel(resultPrecisionModel);
 }
Member Data Documentation
std::vector<geomgraph::GeometryGraph*> geos::operation::GeometryGraphOperation::arg protected inherited
The operation args into an array so they can be accessed by index.
Definition at line 78 of file GeometryGraphOperation.h.
Referenced by geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), geos::operation::overlay::OverlayOp::computeLabelling(), geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::OverlayOp::copyPoints(), geos::operation::GeometryGraphOperation::GeometryGraphOperation(), geos::operation::GeometryGraphOperation::getArgGeometry(), geos::operation::overlay::OverlayOp::getAverageZ(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), and geos::operation::GeometryGraphOperation::~GeometryGraphOperation().
algorithm::LineIntersector geos::operation::GeometryGraphOperation::li protected inherited
Definition at line 71 of file GeometryGraphOperation.h.
Referenced by geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::OverlayOp::mergeZ(), and geos::operation::GeometryGraphOperation::setComputationPrecision().
RelateComputer geos::operation::relate::RelateOp::relateComp private
Definition at line 129 of file RelateOp.h.
Referenced by getIntersectionMatrix().
const geom::PrecisionModel* geos::operation::GeometryGraphOperation::resultPrecisionModel protected inherited
Definition at line 73 of file GeometryGraphOperation.h.
Referenced by geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), geos::operation::overlay::OverlayOp::computeOverlay(), and geos::operation::GeometryGraphOperation::setComputationPrecision().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/relate/RelateOp.h
/home/vicky/potree/geos/vicky/src/operation/relate/RelateOp.cpp