GEOS: geos::geom::prep::PreparedGeometryFactory Class Reference
geos::geom::prep::PreparedGeometryFactory Class Reference
A factory for creating PreparedGeometrys.
#include <PreparedGeometryFactory.h>
Public Member Functions
const PreparedGeometry * create (const geom::Geometry *geom) const
Static Public Member Functions
static const PreparedGeometry * prepare (const geom::Geometry *geom)
static void destroy (const PreparedGeometry *geom)
Detailed Description
A factory for creating PreparedGeometrys.
It chooses an appropriate implementation of PreparedGeometry based on the geoemtric type of the input geometry. In the future, the factory may accept hints that indicate special optimizations which can be performed.
Author
Martin Davis
Definition at line 52 of file PreparedGeometryFactory.h.
Member Function Documentation
const PreparedGeometry * geos::geom::prep::PreparedGeometryFactory::create (const geom::Geometry * geom) const
Creates a new PreparedGeometry appropriate for the argument Geometry.
Parameters
geom the geometry to prepare
Returns
the prepared geometry
Definition at line 40 of file PreparedGeometryFactory.cpp.
References geos::geom::GEOS_LINEARRING, geos::geom::GEOS_LINESTRING, geos::geom::GEOS_MULTILINESTRING, geos::geom::GEOS_MULTIPOINT, geos::geom::GEOS_MULTIPOLYGON, geos::geom::GEOS_POINT, geos::geom::GEOS_POLYGON, and geos::geom::Geometry::getGeometryTypeId().
Referenced by prepare().
 {
     using geos::geom::GeometryTypeId;
     if (nullptr == g)
     {
         throw util::IllegalArgumentException("PreparedGeometry constructd with null Geometry object");
     }
   PreparedGeometry* pg = nullptr;
   switch ( g->getGeometryTypeId() )
   {
     case GEOS_MULTIPOINT:
     case GEOS_POINT:
       pg = new PreparedPoint( g);
       break;
     case GEOS_LINEARRING:
     case GEOS_LINESTRING:
     case GEOS_MULTILINESTRING:
       pg = new PreparedLineString( g);
       break;
     case GEOS_POLYGON:
     case GEOS_MULTIPOLYGON:
       pg = new PreparedPolygon( g);
       break;
     default:
       pg = new BasicPreparedGeometry( g);
   }
   return pg;
 }
static void geos::geom::prep::PreparedGeometryFactory::destroy (const PreparedGeometry * geom) inline static
Destroys PreparedGeometry allocated with the factory.
Parameters
geom to be deallocated
Definition at line 73 of file PreparedGeometryFactory.h.
     {
         delete geom;
     }
static const PreparedGeometry* geos::geom::prep::PreparedGeometryFactory::prepare (const geom::Geometry * geom) inline static
Creates a new PreparedGeometry appropriate for the argument Geometry.
Parameters
geom the geometry to prepare
Returns
the prepared geometry
Definition at line 62 of file PreparedGeometryFactory.h.
References create().
Referenced by GEOSPrepare_r().
   {
     PreparedGeometryFactory pf;
     return pf.create(geom);
   }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/prep/PreparedGeometryFactory.h
/home/vicky/potree/geos/vicky/src/geom/prep/PreparedGeometryFactory.cpp