GEOS: geos::triangulate::quadedge::Vertex Class Reference
geos::triangulate::quadedge::Vertex Class Reference
#include <Vertex.h>
Public Member Functions
Vertex (double _x, double _y)
Vertex (double _x, double _y, double _z)
Vertex (const geom::Coordinate &_p)
Vertex ()
double getX () const
double getY () const
double getZ () const
void setZ (double _z)
const geom::Coordinate & getCoordinate () const
bool equals (const Vertex &_x) const
bool equals (const Vertex &_x, double tolerance) const
virtual int classify (const Vertex &p0, const Vertex &p1)
double crossProduct (const Vertex &v) const
double dot (Vertex v) const
std::unique_ptr< Vertex > times (double c) const
std::unique_ptr< Vertex > sum (Vertex v) const
std::unique_ptr< Vertex > sub (const Vertex &v) const
double magn () const
std::unique_ptr< Vertex > cross () const
virtual bool isInCircle (const Vertex &a, const Vertex &b, const Vertex &c) const
bool isCCW (const Vertex &b, const Vertex &c) const
bool rightOf (const QuadEdge &e) const
bool leftOf (const QuadEdge &e) const
Static Public Attributes
static const int LEFT = 0
static const int RIGHT = 1
static const int BEYOND = 2
static const int BEHIND = 3
static const int BETWEEN = 4
static const int ORIGIN = 5
static const int DESTINATION = 6
Private Member Functions
double distance (const Vertex &v1, const Vertex &v2)
virtual double circumRadiusRatio (const Vertex &b, const Vertex &c)
virtual std::unique_ptr< Vertex > midPoint (const Vertex &a)
virtual std::unique_ptr< Vertex > circleCenter (const Vertex &b, const Vertex &c) const
virtual double interpolateZValue (const Vertex &v0, const Vertex &v1, const Vertex &v2) const
Static Private Member Functions
static std::unique_ptr< algorithm::HCoordinate > bisector (const Vertex &a, const Vertex &b)
static double interpolateZ (const geom::Coordinate &p, const geom::Coordinate &v0, const geom::Coordinate &v1, const geom::Coordinate &v2)
static double interpolateZ (const geom::Coordinate &p, const geom::Coordinate &p0, const geom::Coordinate &p1)
Private Attributes
geom::Coordinate p
Detailed Description
Models a site (node) in a QuadEdgeSubdivision. The sites can be points on a line string representing a linear site.
The vertex can be considered as a vector with a norm, length, inner product, cross product, etc. Additionally, point relations (e.g., is a point to the left of a line, the circle defined by this point and two others, etc.) are also defined in this class.
It is common to want to attach user-defined data to the vertices of a subdivision. One way to do this is to subclass Vertex to carry any desired information (see ConstraintVertex).
Author
JTS: David Skea
JTS: Martin Davis
Benjamin Campbell
Definition at line 61 of file Vertex.h.
Constructor & Destructor Documentation
geos::triangulate::quadedge::Vertex::Vertex (double _x, double _y)
Definition at line 33 of file Vertex.cpp.
                                    : p(_x, _y)
 {
 }
geos::triangulate::quadedge::Vertex::Vertex (double _x, double _y, double _z)
Definition at line 37 of file Vertex.cpp.
                                              : p( _x, _y, _z)
 {
 }
geos::triangulate::quadedge::Vertex::Vertex (const geom::Coordinate & _p)
Definition at line 41 of file Vertex.cpp.
                                    : p(_p)
 {
 }
geos::triangulate::quadedge::Vertex::Vertex ()
Definition at line 45 of file Vertex.cpp.
Referenced by circleCenter(), and midPoint().
                : p() {
 }
Member Function Documentation
std::unique_ptr< HCoordinate > geos::triangulate::quadedge::Vertex::bisector (const Vertex & a, const Vertex & b) static private
Definition at line 86 of file Vertex.cpp.
References getX(), and getY().
Referenced by circleCenter().
 {
   // returns the perpendicular bisector of the line segment ab
   double dx = b.getX() - a.getX();
   double dy = b.getY() - a.getY();
   HCoordinate l1 = HCoordinate(a.getX() + dx / 2.0, a.getY() + dy / 2.0, 1.0);
   HCoordinate l2 = HCoordinate(a.getX() - dy + dx / 2.0, a.getY() + dx + dy / 2.0, 1.0);
   return std::unique_ptr<HCoordinate>(new HCoordinate(l1, l2));
 }
std::unique_ptr< Vertex > geos::triangulate::quadedge::Vertex::circleCenter (const Vertex & b, const Vertex & c) const private virtual
Computes the centre of the circumcircle of this vertex and two others.
Parameters
b
c
Returns
the Coordinate which is the circumcircle of the 3 points.
Definition at line 124 of file Vertex.cpp.
References bisector(), getX(), getY(), and Vertex().
Referenced by circumRadiusRatio().
 {
   std::unique_ptr<Vertex> a(new Vertex(getX(), getY()));
   // compute the perpendicular bisector of cord ab
   std::unique_ptr<HCoordinate> cab = bisector(*a, b);
   // compute the perpendicular bisector of cord bc
   std::unique_ptr<HCoordinate> cbc = bisector(b, c);
   // compute the intersection of the bisectors (circle radii)
   std::unique_ptr<HCoordinate> hcc(new HCoordinate(*cab, *cbc));
   std::unique_ptr<Vertex> cc;
   try
   {
     cc.reset(new Vertex(hcc->getX(), hcc->getY()));
   } catch (NotRepresentableException nre) {
   }
   return cc;
 }
double geos::triangulate::quadedge::Vertex::circumRadiusRatio (const Vertex & b, const Vertex & c) private virtual
Computes the value of the ratio of the circumradius to shortest edge. If smaller than some given tolerance B, the associated triangle is considered skinny. For an equal lateral triangle this value is 0.57735. The ratio is related to the minimum triangle angle theta by: circumRadius/shortestEdge = 1/(2sin(theta)).
Parameters
b second vertex of the triangle
c third vertex of the triangle
Returns
ratio of circumradius to shortest edge.
Definition at line 97 of file Vertex.cpp.
References circleCenter(), and distance().
 {
   std::unique_ptr<Vertex> x(circleCenter(b, c));
   double radius = distance(*x, b);
   double edgeLength = distance(*this, b);
   double el = distance(b, c);
   if (el < edgeLength)
   {
     edgeLength = el;
   }
   el = distance(c, *this);
   if (el < edgeLength)
   {
     edgeLength = el;
   }
   return radius / edgeLength;
 }
int geos::triangulate::quadedge::Vertex::classify (const Vertex & p0, const Vertex & p1) virtual
Definition at line 48 of file Vertex.cpp.
References BEHIND, BETWEEN, BEYOND, DESTINATION, equals(), LEFT, ORIGIN, RIGHT, and sub().
 {
   Vertex &p2 = *this;
   std::unique_ptr<Vertex> a = p1.sub(p0);
   std::unique_ptr<Vertex> b = p2.sub(p0);
   double sa = a->crossProduct(*b);
   if (sa > 0.0)
     return LEFT;
   if (sa < 0.0)
     return RIGHT;
   if ((a->getX() * b->getX() < 0.0) || (a->getY() * b->getY() < 0.0))
     return BEHIND;
   if (a->magn() < b->magn())
     return BEYOND;
   if (p0.equals(p2))
     return ORIGIN;
   if (p1.equals(p2))
     return DESTINATION;
   else
     return BETWEEN;
 }
std::unique_ptr<Vertex> geos::triangulate::quadedge::Vertex::cross () const inline
Definition at line 166 of file Vertex.h.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
{
     return std::unique_ptr<Vertex>(new Vertex(p.y, -p.x));
   }
double geos::triangulate::quadedge::Vertex::crossProduct (const Vertex & v) const inline
Computes the cross product k = u X v.
Parameters
v a vertex
Returns
returns the magnitude of u X v
Definition at line 124 of file Vertex.h.
References getX(), getY(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
   {
     return (p.x * v.getY() - p.y * v.getX());
   }
double geos::triangulate::quadedge::Vertex::distance (const Vertex & v1, const Vertex & v2) inline private
Definition at line 208 of file Vertex.h.
References getX(), and getY().
Referenced by circumRadiusRatio().
   {
     return sqrt(pow(v2.getX() - v1.getX(), 2.0)
         + pow(v2.getY() - v1.getY(), 2.0));
   }
double geos::triangulate::quadedge::Vertex::dot (Vertex v) const inline
Computes the inner or dot product
Parameters
v,a vertex
Returns
returns the dot product u.v
Definition at line 135 of file Vertex.h.
References getX(), getY(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
   {
     return (p.x * v.getX() + p.y * v.getY());
   }
bool geos::triangulate::quadedge::Vertex::equals (const Vertex & _x) const inline
Definition at line 102 of file Vertex.h.
References getX(), getY(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by classify(), geos::triangulate::quadedge::QuadEdgeSubdivision::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::isFrameVertex(), geos::triangulate::quadedge::QuadEdgeSubdivision::isVertexOfEdge(), and geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge().
   {
     if (p.x == _x.getX() && p.y == _x.getY())
       return true;
     return false;
   }
bool geos::triangulate::quadedge::Vertex::equals (const Vertex & _x, double tolerance) const inline
Definition at line 109 of file Vertex.h.
References geos::geom::Coordinate::distance(), and getCoordinate().
   {
     if (p.distance(_x.getCoordinate()) < tolerance)
       return true;
     return false;
   }
const geom::Coordinate& geos::triangulate::quadedge::Vertex::getCoordinate () const inline
Definition at line 98 of file Vertex.h.
Referenced by equals(), geos::triangulate::quadedge::QuadEdge::equalsOriented(), geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon(), geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), geos::triangulate::quadedge::QuadEdgeSubdivision::isOnEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::locate(), geos::triangulate::quadedge::operator<(), geos::triangulate::quadedge::QuadEdge::toLineSegment(), and geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor::visit().
{
     return p;
   }
double geos::triangulate::quadedge::Vertex::getX () const inline
Definition at line 82 of file Vertex.h.
References geos::geom::Coordinate::x.
Referenced by bisector(), circleCenter(), crossProduct(), distance(), dot(), equals(), interpolateZValue(), midPoint(), sub(), and sum().
{
     return p.x;
   }
double geos::triangulate::quadedge::Vertex::getY () const inline
Definition at line 86 of file Vertex.h.
References geos::geom::Coordinate::y.
Referenced by bisector(), circleCenter(), crossProduct(), distance(), dot(), equals(), interpolateZValue(), midPoint(), sub(), and sum().
{
     return p.y;
   }
double geos::triangulate::quadedge::Vertex::getZ () const inline
Definition at line 90 of file Vertex.h.
References geos::geom::Coordinate::z.
Referenced by interpolateZValue(), and midPoint().
{
     return p.z;
   }
double geos::triangulate::quadedge::Vertex::interpolateZ (const geom::Coordinate & p, const geom::Coordinate & v0, const geom::Coordinate & v1, const geom::Coordinate & v2) static private
Interpolates the Z-value (height) of a point enclosed in a triangle whose vertices all have Z values. The containing triangle must not be degenerate (in other words, the three vertices must enclose a non-zero area).
Parameters
p the point to interpolate the Z value of
v0 a vertex of a triangle containing the p
v1 a vertex of a triangle containing the p
v2 a vertex of a triangle containing the p
Returns
the interpolated Z-value (height) of the point
Definition at line 162 of file Vertex.cpp.
References geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
 {
   double x0 = v0.x;
   double y0 = v0.y;
   double a = v1.x - x0;
   double b = v2.x - x0;
   double c = v1.y - y0;
   double d = v2.y - y0;
   double det = a * d - b * c;
   double dx = p.x - x0;
   double dy = p.y - y0;
   double t = (d * dx - b * dy) / det;
   double u = (-c * dx + a * dy) / det;
   double z = v0.z + t * (v1.z - v0.z) + u * (v2.z - v0.z);
   return z;
 }
double geos::triangulate::quadedge::Vertex::interpolateZ (const geom::Coordinate & p, const geom::Coordinate & p0, const geom::Coordinate & p1) static private
Computes the interpolated Z-value for a point p lying on the segment p0-p1
Parameters
p
p0
p1
Returns
the interpolated Z value
Definition at line 180 of file Vertex.cpp.
References geos::geom::Coordinate::distance(), and geos::geom::Coordinate::z.
 {
   double segLen = p0.distance(p1);
   double ptLen = p.distance(p0);
   double dz = p1.z - p0.z;
   double pz = p0.z + dz * (ptLen / segLen);
   return pz;
 }
double geos::triangulate::quadedge::Vertex::interpolateZValue (const Vertex & v0, const Vertex & v1, const Vertex & v2) const private virtual
For this vertex enclosed in a triangle defined by three verticies v0, v1 and v2, interpolate a z value from the surrounding vertices.
Definition at line 144 of file Vertex.cpp.
References getX(), getY(), and getZ().
 {
   double x0 = v0.getX();
   double y0 = v0.getY();
   double a = v1.getX() - x0;
   double b = v2.getX() - x0;
   double c = v1.getY() - y0;
   double d = v2.getY() - y0;
   double det = a * d - b * c;
   double dx = this->getX() - x0;
   double dy = this->getY() - y0;
   double t = (d * dx - b * dy) / det;
   double u = (-c * dx + a * dy) / det;
   double z = v0.getZ() + t * (v1.getZ() - v0.getZ()) + u * (v2.getZ() - v0.getZ());
   return z;
 }
bool geos::triangulate::quadedge::Vertex::isCCW (const Vertex & b, const Vertex & c) const inline
Tests whether the triangle formed by this vertex and two other vertices is in CCW orientation.
Parameters
b a vertex
c a vertex
Returns
true if the triangle is oriented CCW
Definition at line 194 of file Vertex.h.
References p, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by leftOf(), and rightOf().
   {
     // is equal to the signed area of the triangle
     return (b.p.x - p.x) * (c.p.y - p.y)
       - (b.p.y - p.y) * (c.p.x - p.x) > 0;
   }
bool geos::triangulate::quadedge::Vertex::isInCircle (const Vertex & a, const Vertex & b, const Vertex & c) const virtual
Tests if the vertex is inside the circle defined by the triangle with vertices a, b, c (oriented counter-clockwise).
Parameters
a a vertex of the triangle
b a vertex of the triangle
c a vertex of the triangle
Returns
true if this vertex is in the circumcircle of (a,b,c)
Definition at line 71 of file Vertex.cpp.
References geos::geom::TrianglePredicate::isInCircleRobust(), and p.
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite().
 {
   return TrianglePredicate::isInCircleRobust(a.p, b.p, c.p, this->p);
   // non-robust - best to not use
   //return TrianglePredicate.isInCircle(a.p, b.p, c.p, this->p);
 }
bool geos::triangulate::quadedge::Vertex::leftOf (const QuadEdge & e) const
Definition at line 82 of file Vertex.cpp.
References geos::triangulate::quadedge::QuadEdge::dest(), isCCW(), and geos::triangulate::quadedge::QuadEdge::orig().
{
   return isCCW(e.orig(), e.dest());
 }
double geos::triangulate::quadedge::Vertex::magn () const inline
Definition at line 161 of file Vertex.h.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
{
     return (sqrt(p.x * p.x + p.y * p.y));
   }
std::unique_ptr< Vertex > geos::triangulate::quadedge::Vertex::midPoint (const Vertex & a) private virtual
returns a new vertex that is mid-way between this vertex and another end point.
Parameters
a the other end point.
Returns
the point mid-way between this and that.
Definition at line 116 of file Vertex.cpp.
References getX(), getY(), getZ(), p, Vertex(), geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
 {
   double xm = (p.x + a.getX()) / 2.0;
   double ym = (p.y + a.getY()) / 2.0;
   double zm = (p.z + a.getZ()) / 2.0;
   return std::unique_ptr<Vertex>(new Vertex(xm, ym, zm));
 }
bool geos::triangulate::quadedge::Vertex::rightOf (const QuadEdge & e) const
Definition at line 78 of file Vertex.cpp.
References geos::triangulate::quadedge::QuadEdge::dest(), isCCW(), and geos::triangulate::quadedge::QuadEdge::orig().
Referenced by geos::triangulate::IncrementalDelaunayTriangulator::insertSite(), and geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge().
{
   return isCCW(e.dest(), e.orig());
 }
void geos::triangulate::quadedge::Vertex::setZ (double _z) inline
Definition at line 94 of file Vertex.h.
References geos::geom::Coordinate::z.
{
     p.z = _z;
   }
std::unique_ptr<Vertex> geos::triangulate::quadedge::Vertex::sub (const Vertex & v) const inline
Definition at line 156 of file Vertex.h.
References getX(), getY(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by classify().
{
     return std::unique_ptr<Vertex>(new Vertex(p.x - v.getX(), p.y - v.getY()));
   }
std::unique_ptr<Vertex> geos::triangulate::quadedge::Vertex::sum (Vertex v) const inline
Definition at line 151 of file Vertex.h.
References getX(), getY(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
{
     return std::unique_ptr<Vertex>(new Vertex(p.x + v.getX(), p.y + v.getY()));
   }
std::unique_ptr<Vertex> geos::triangulate::quadedge::Vertex::times (double c) const inline
Computes the scalar product c(v)
Parameters
v,a vertex
Returns
returns the scaled vector
Definition at line 146 of file Vertex.h.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
{
     return std::unique_ptr<Vertex>(new Vertex(c * p.x, c * p.y));
   }
Member Data Documentation
const int geos::triangulate::quadedge::Vertex::BEHIND = 3 static
Definition at line 66 of file Vertex.h.
Referenced by classify().
const int geos::triangulate::quadedge::Vertex::BETWEEN = 4 static
Definition at line 67 of file Vertex.h.
Referenced by classify().
const int geos::triangulate::quadedge::Vertex::BEYOND = 2 static
Definition at line 65 of file Vertex.h.
Referenced by classify().
const int geos::triangulate::quadedge::Vertex::DESTINATION = 6 static
Definition at line 69 of file Vertex.h.
Referenced by classify().
const int geos::triangulate::quadedge::Vertex::LEFT = 0 static
Definition at line 63 of file Vertex.h.
Referenced by classify().
const int geos::triangulate::quadedge::Vertex::ORIGIN = 5 static
Definition at line 68 of file Vertex.h.
Referenced by classify().
geom::Coordinate geos::triangulate::quadedge::Vertex::p private
Definition at line 71 of file Vertex.h.
Referenced by isCCW(), isInCircle(), and midPoint().
const int geos::triangulate::quadedge::Vertex::RIGHT = 1 static
Definition at line 64 of file Vertex.h.
Referenced by classify().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/triangulate/quadedge/Vertex.h
/home/vicky/potree/geos/vicky/src/triangulate/quadedge/Vertex.cpp