GEOS: geos::index::strtree::BoundablePair Class Reference
geos::index::strtree::BoundablePair Class Reference
#include <BoundablePair.h>
Classes
struct BoundablePairQueueCompare
Public Types
typedef std::priority_queue< BoundablePair *, std::vector< BoundablePair * >, BoundablePairQueueCompare > BoundablePairQueue
Public Member Functions
BoundablePair (const Boundable *boundable1, const Boundable *boundable2, ItemDistance *itemDistance)
const Boundable * getBoundable (int i) const
double distance () const
double getDistance () const
bool isLeaves () const
void expandToQueue (BoundablePairQueue &, double minDistance)
void expand (const Boundable *bndComposite, const Boundable *bndOther, BoundablePairQueue &priQ, double minDistance)
Static Public Member Functions
static bool isComposite (const Boundable *item)
static double area (const Boundable *b)
Private Attributes
const Boundable * boundable1
const Boundable * boundable2
ItemDistance * itemDistance
double mDistance
Detailed Description
Definition at line 43 of file BoundablePair.h.
Member Typedef Documentation
typedef std::priority_queue<BoundablePair*, std::vector<BoundablePair*>, BoundablePairQueueCompare> geos::index::strtree::BoundablePair::BoundablePairQueue
Definition at line 57 of file BoundablePair.h.
Constructor & Destructor Documentation
geos::index::strtree::BoundablePair::BoundablePair (const Boundable * boundable1, const Boundable * boundable2, ItemDistance * itemDistance)
Definition at line 28 of file BoundablePair.cpp.
References distance(), and mDistance.
Referenced by expand().
                                                                                                                  :
   boundable1(boundable1),
   boundable2(boundable2),
   itemDistance(itemDistance)
 {
   mDistance = distance();
 }
Member Function Documentation
double geos::index::strtree::BoundablePair::area (const Boundable * b) static
Definition at line 69 of file BoundablePair.cpp.
References geos::index::strtree::Boundable::getBounds().
Referenced by expandToQueue().
{
   return ((const geos::geom::Envelope*) b->getBounds())->getArea();
 }
double geos::index::strtree::BoundablePair::distance () const
Computes the distance between the Boundables in this pair. The boundables are either composites or leaves. If either is composite, the distance is computed as the minimum distance between the bounds. If both are leaves, the distance is computed by itemDistance(ItemBoundable, ItemBoundable).
Returns
Definition at line 42 of file BoundablePair.cpp.
References boundable1, boundable2, geos::index::strtree::ItemDistance::distance(), geos::geom::Envelope::distance(), geos::index::strtree::Boundable::getBounds(), isLeaves(), and itemDistance.
Referenced by BoundablePair().
{
   // if items, compute exact distance
   if (isLeaves()) {
     return itemDistance->distance((ItemBoundable*) boundable1, (ItemBoundable*) boundable2);
   }
   // otherwise compute distance between bounds of boundables
   const geom::Envelope* e1 = (const geom::Envelope*) boundable1->getBounds();
   const geom::Envelope* e2 = (const geom::Envelope*) boundable2->getBounds();
   if (!e1 || !e2)
     throw util::GEOSException("Can't compute envelope of item in BoundablePair");
   return e1->distance(e2);
 }
void geos::index::strtree::BoundablePair::expand (const Boundable * bndComposite, const Boundable * bndOther, BoundablePairQueue & priQ, double minDistance)
Definition at line 103 of file BoundablePair.cpp.
References BoundablePair(), and itemDistance.
Referenced by expandToQueue().
{
   std::vector<Boundable*> *children = ((AbstractNode*) bndComposite)->getChildBoundables();
   for(std::vector<Boundable*>::iterator it = children->begin(); it != children->end(); ++it) {
     Boundable* child = *it;
     std::unique_ptr<BoundablePair> bp(new BoundablePair(child, bndOther, itemDistance));
     if (minDistance == std::numeric_limits<double>::infinity() || bp->getDistance() < minDistance) {
       priQ.push(bp.release());
     }
   }
 }
void geos::index::strtree::BoundablePair::expandToQueue (BoundablePairQueue & priQ, double minDistance)
HEURISTIC: If both boundables are composite, choose the one with largest area to expand. Otherwise, simply expand whichever is composite.
Definition at line 73 of file BoundablePair.cpp.
References area(), boundable1, boundable2, expand(), and isComposite().
Referenced by geos::index::strtree::STRtree::nearestNeighbour().
{
   bool isComp1 = isComposite(boundable1);
   bool isComp2 = isComposite(boundable2);
   if (isComp1 && isComp2) {
     if (area(boundable1) > area(boundable2)) {
       expand(boundable1, boundable2, priQ, minDistance);
       return;
     } else {
       expand(boundable2, boundable1, priQ, minDistance);
       return;
     }
   }
   else if (isComp1) {
     expand(boundable1, boundable2, priQ, minDistance);
     return;
   }
   else if (isComp2) {
     expand(boundable2, boundable1, priQ, minDistance);
     return;
   }
   throw new geos::util::IllegalArgumentException("neither boundable is composite");
 }
const Boundable * geos::index::strtree::BoundablePair::getBoundable (int i) const
Gets one of the member Boundables in the pair (indexed by [0, 1]).
Parameters
i the index of the member to return (0 or 1)
Returns
the chosen member
Definition at line 36 of file BoundablePair.cpp.
References boundable1, and boundable2.
Referenced by geos::index::strtree::STRtree::nearestNeighbour().
{
   if (i == 0)
     return boundable1;
   return boundable2;
 }
double geos::index::strtree::BoundablePair::getDistance () const
Gets the minimum possible distance between the Boundables in this pair. If the members are both items, this will be the exact distance between them. Otherwise, this distance will be a lower bound on the distances between the items in the members.
Returns
the exact or lower bound distance for this pair
Definition at line 57 of file BoundablePair.cpp.
References mDistance.
Referenced by geos::index::strtree::STRtree::nearestNeighbour(), and geos::index::strtree::BoundablePair::BoundablePairQueueCompare::operator()().
{
   return mDistance;
 }
bool geos::index::strtree::BoundablePair::isComposite (const Boundable * item) static
Definition at line 65 of file BoundablePair.cpp.
Referenced by expandToQueue(), and isLeaves().
{
   return dynamic_cast<const AbstractNode*>(item) != nullptr;
 }
bool geos::index::strtree::BoundablePair::isLeaves () const
Tests if both elements of the pair are leaf nodes
Returns
true if both pair elements are leaf nodes
Definition at line 61 of file BoundablePair.cpp.
References boundable1, boundable2, and isComposite().
Referenced by distance(), and geos::index::strtree::STRtree::nearestNeighbour().
{
   return !(isComposite(boundable1) || isComposite(boundable2));
 }
Member Data Documentation
const Boundable* geos::index::strtree::BoundablePair::boundable1 private
Definition at line 45 of file BoundablePair.h.
Referenced by distance(), expandToQueue(), getBoundable(), and isLeaves().
const Boundable* geos::index::strtree::BoundablePair::boundable2 private
Definition at line 46 of file BoundablePair.h.
Referenced by distance(), expandToQueue(), getBoundable(), and isLeaves().
ItemDistance* geos::index::strtree::BoundablePair::itemDistance private
Definition at line 47 of file BoundablePair.h.
Referenced by distance(), and expand().
double geos::index::strtree::BoundablePair::mDistance private
Definition at line 48 of file BoundablePair.h.
Referenced by BoundablePair(), and getDistance().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/strtree/BoundablePair.h
/home/vicky/potree/geos/vicky/src/index/strtree/BoundablePair.cpp