GEOS: geos::operation::polygonize::PolygonizeDirectedEdge Class Reference
geos::operation::polygonize::PolygonizeDirectedEdge Class Reference
A DirectedEdge of a PolygonizeGraph, which represents an edge of a polygon formed by the graph.
#include <PolygonizeDirectedEdge.h>
Public Types
typedef std::list< DirectedEdge * > NonConstList
typedef std::list< const DirectedEdge * > ConstList
typedef std::vector< DirectedEdge * > NonConstVect
typedef std::vector< const DirectedEdge * > ConstVect
typedef std::vector< DirectedEdge * > Vect
Public Member Functions
PolygonizeDirectedEdge (planargraph::Node *newFrom, planargraph::Node *newTo, const geom::Coordinate &newDirectionPt, bool nEdgeDirection)
long getLabel () const
void setLabel (long newLabel)
PolygonizeDirectedEdge * getNext () const
void setNext (PolygonizeDirectedEdge *newNext)
bool isInRing () const
void setRing (EdgeRing *newEdgeRing)
Edge * getEdge () const
Returns this DirectedEdge's parent Edge, or null if it has none.
void setEdge (Edge *newParentEdge)
Associates this DirectedEdge with an Edge (possibly null, indicating no associated Edge).
int getQuadrant () const
Returns 0, 1, 2, or 3, indicating the quadrant in which this DirectedEdge's orientation lies.
const geom::Coordinate & getDirectionPt () const
Returns a point to which an imaginary line is drawn from the from-node to specify this DirectedEdge's orientation.
bool getEdgeDirection () const
Returns whether the direction of the parent Edge (if any) is the same as that of this Directed Edge.
Node * getFromNode () const
Returns the node from which this DirectedEdge leaves.
Node * getToNode () const
Returns the node to which this DirectedEdge goes.
geom::Coordinate & getCoordinate () const
Returns the coordinate of the from-node.
double getAngle () const
Returns the angle that the start of this DirectedEdge makes with the positive x-axis, in radians.
DirectedEdge * getSym () const
Returns the symmetric DirectedEdge – the other DirectedEdge associated with this DirectedEdge's parent Edge.
void setSym (DirectedEdge *newSym)
Sets this DirectedEdge's symmetric DirectedEdge, which runs in the opposite direction.
int compareTo (const DirectedEdge *obj) const
Returns 1 if this DirectedEdge has a greater angle with the positive x-axis than b", 0 if the DirectedEdges are collinear, and -1 otherwise.
int compareDirection (const DirectedEdge *e) const
Returns 1 if this DirectedEdge has a greater angle with the positive x-axis than b", 0 if the DirectedEdges are collinear, and -1 otherwise.
std::string print () const
Prints a detailed string representation of this DirectedEdge to the given PrintStream.
virtual bool isVisited () const
Tests if a component has been visited during the course of a graph algorithm.
virtual void setVisited (bool isVisited)
Sets the visited flag for this component.
virtual void setMarked (bool isMarked)
Sets the marked flag for this component.
virtual bool isMarked () const
Tests if a component has been marked at some point during the processing involving this graph.
Static Public Member Functions
static std::vector< Edge * > * toEdges (std::vector< DirectedEdge * > &dirEdges)
Returns a List containing the parent Edge (possibly null) for each of the given DirectedEdges.
static void toEdges (std::vector< DirectedEdge * > &dirEdges, std::vector< Edge * > &parentEdges)
Add parent Edge (possibly null) of each of the given DirectedEdges to the given parentEdges vector.
template<typename T >
static void setVisited (T start, T end, bool visited)
Sets the Visited state for the elements of a container, from start to end iterator.
template<typename T >
static void setVisitedMap (T start, T end, bool visited)
Sets the Visited state for the values of each map container element, from start to end iterator.
template<typename T >
static void setMarked (T start, T end, bool marked)
Sets the Marked state for the elements of a container, from start to end iterator.
template<typename T >
static void setMarkedMap (T start, T end, bool marked)
Sets the Marked state for the values of each map container element, from start to end iterator.
Protected Attributes
Edge * parentEdge
Node * from
Node * to
geom::Coordinate p0
geom::Coordinate p1
DirectedEdge * sym
bool edgeDirection
int quadrant
double angle
bool isMarkedVar
Variable holding ''marked'' status.
bool isVisitedVar
Variable holding ''visited'' status.
Private Attributes
EdgeRing * edgeRing
PolygonizeDirectedEdge * next
long label
Detailed Description
A DirectedEdge of a PolygonizeGraph, which represents an edge of a polygon formed by the graph.
May be logically deleted from the graph by setting the marked flag.
Definition at line 54 of file PolygonizeDirectedEdge.h.
Member Typedef Documentation
typedef std::list<const DirectedEdge *> geos::planargraph::DirectedEdge::ConstList inherited
Definition at line 53 of file DirectedEdge.h.
typedef std::vector<const DirectedEdge *> geos::planargraph::DirectedEdge::ConstVect inherited
Definition at line 67 of file DirectedEdge.h.
typedef std::list<DirectedEdge *> geos::planargraph::DirectedEdge::NonConstList inherited
Definition at line 52 of file DirectedEdge.h.
typedef std::vector<DirectedEdge *> geos::planargraph::DirectedEdge::NonConstVect inherited
Definition at line 54 of file DirectedEdge.h.
typedef std::vector<DirectedEdge *> geos::planargraph::DirectedEdge::Vect inherited
Definition at line 68 of file DirectedEdge.h.
Constructor & Destructor Documentation
geos::operation::polygonize::PolygonizeDirectedEdge::PolygonizeDirectedEdge (planargraph::Node * newFrom, planargraph::Node * newTo, const geom::Coordinate & newDirectionPt, bool nEdgeDirection)
Constructs a directed edge connecting the from node to the to node.
Parameters
directionPt specifies this DirectedEdge's direction (given by an imaginary line from the from node to directionPt)
edgeDirection whether this DirectedEdge's direction is the same as or opposite to that of the parent Edge (if any)
Definition at line 41 of file PolygonizeDirectedEdge.cpp.
References edgeRing, label, and next.
   :
   DirectedEdge(newFrom, newTo,
     newDirectionPt, nEdgeDirection)
 {
   edgeRing=nullptr;
   next=nullptr;
   label=-1;
 }
Member Function Documentation
int geos::planargraph::DirectedEdge::compareDirection (const DirectedEdge * e) const inherited
Returns 1 if this DirectedEdge has a greater angle with the positive x-axis than b", 0 if the DirectedEdges are collinear, and -1 otherwise.
Using the obvious algorithm of simply computing the angle is not robust, since the angle calculation is susceptible to roundoff. A robust algorithm is:
first compare the quadrants. If the quadrants are different, it it trivial to determine which std::vector is "greater".
if the vectors lie in the same quadrant, the robust RobustCGAlgorithms::computeOrientation(Coordinate, Coordinate, Coordinate) function can be used to decide the relative orientation of the vectors.
Definition at line 155 of file DirectedEdge.cpp.
References geos::planargraph::DirectedEdge::p0, geos::planargraph::DirectedEdge::p1, and geos::planargraph::DirectedEdge::quadrant.
 {
 // if the rays are in different quadrants, determining the ordering is trivial
   if (quadrant > e->quadrant) return 1;
   if (quadrant < e->quadrant) return -1;
   // vectors are in the same quadrant - check relative orientation of direction vectors
   // this is > e if it is CCW of e
   return algorithm::CGAlgorithms::computeOrientation(e->p0,e->p1,p1);
 }
int geos::planargraph::DirectedEdge::compareTo (const DirectedEdge * obj) const inherited
Returns 1 if this DirectedEdge has a greater angle with the positive x-axis than b", 0 if the DirectedEdges are collinear, and -1 otherwise.
Using the obvious algorithm of simply computing the angle is not robust, since the angle calculation is susceptible to roundoff. A robust algorithm is:
first compare the quadrants. If the quadrants are different, it it trivial to determine which std::vector is "greater".
if the vectors lie in the same quadrant, the robust RobustCGAlgorithms::computeOrientation(Coordinate, Coordinate, Coordinate) function can be used to decide the relative orientation of the vectors.
Definition at line 148 of file DirectedEdge.cpp.
Referenced by geos::planargraph::pdeLessThan().
 {
   return compareDirection(de);
 }
double geos::planargraph::DirectedEdge::getAngle () const inherited
Returns the angle that the start of this DirectedEdge makes with the positive x-axis, in radians.
Definition at line 124 of file DirectedEdge.cpp.
 {
   return angle;
 }
Coordinate & geos::planargraph::DirectedEdge::getCoordinate () const inherited
Returns the coordinate of the from-node.
Definition at line 117 of file DirectedEdge.cpp.
Referenced by geos::planargraph::DirectedEdgeStar::getCoordinate().
 {
   return from->getCoordinate();
 }
const Coordinate & geos::planargraph::DirectedEdge::getDirectionPt () const inherited
Returns a point to which an imaginary line is drawn from the from-node to specify this DirectedEdge's orientation.
Definition at line 89 of file DirectedEdge.cpp.
 {
   return p1;
 }
Edge * geos::planargraph::DirectedEdge::getEdge () const inherited
Returns this DirectedEdge's parent Edge, or null if it has none.
Definition at line 68 of file DirectedEdge.cpp.
Referenced by geos::operation::linemerge::LineSequencer::addReverseSubpath(), geos::operation::linemerge::LineMerger::buildEdgeStringsStartingAt(), geos::operation::linemerge::LineMerger::buildEdgeStringStartingWith(), geos::operation::linemerge::LineSequencer::buildSequencedGeometry(), geos::operation::linemerge::EdgeString::getCoordinates(), geos::operation::polygonize::EdgeRing::getCoordinates(), and geos::planargraph::DirectedEdgeStar::getIndex().
 {
   return parentEdge;
 }
bool geos::planargraph::DirectedEdge::getEdgeDirection () const inherited
Returns whether the direction of the parent Edge (if any) is the same as that of this Directed Edge.
Definition at line 96 of file DirectedEdge.cpp.
Referenced by geos::operation::linemerge::LineSequencer::buildSequencedGeometry(), geos::operation::linemerge::EdgeString::getCoordinates(), and geos::operation::polygonize::EdgeRing::getCoordinates().
 {
   return edgeDirection;
 }
Node * geos::planargraph::DirectedEdge::getFromNode () const inherited
Returns the node from which this DirectedEdge leaves.
Definition at line 103 of file DirectedEdge.cpp.
Referenced by geos::planargraph::Subgraph::add(), geos::operation::linemerge::LineSequencer::addReverseSubpath(), geos::operation::polygonize::PolygonizeGraph::findIntersectionNodes(), geos::planargraph::algorithm::ConnectedSubgraphFinder::getConnectedSubgraphs(), geos::planargraph::PlanarGraph::remove(), and geos::planargraph::Edge::setDirectedEdges().
 {
   return from;
 }
long geos::operation::polygonize::PolygonizeDirectedEdge::getLabel () const
Definition at line 57 of file PolygonizeDirectedEdge.cpp.
References label.
 {
   return label;
 }
PolygonizeDirectedEdge * geos::operation::polygonize::PolygonizeDirectedEdge::getNext () const
Definition at line 74 of file PolygonizeDirectedEdge.cpp.
References next.
 {
   return next;
 }
int geos::planargraph::DirectedEdge::getQuadrant () const inherited
Returns 0, 1, 2, or 3, indicating the quadrant in which this DirectedEdge's orientation lies.
Definition at line 82 of file DirectedEdge.cpp.
 {
   return quadrant;
 }
DirectedEdge * geos::planargraph::DirectedEdge::getSym () const inherited
Returns the symmetric DirectedEdge – the other DirectedEdge associated with this DirectedEdge's parent Edge.
Definition at line 131 of file DirectedEdge.cpp.
Referenced by geos::operation::linemerge::LineSequencer::addReverseSubpath(), geos::operation::polygonize::PolygonizeGraph::computeNextCWEdges(), geos::operation::linemerge::LineMergeDirectedEdge::getNext(), and geos::planargraph::PlanarGraph::remove().
 {
   return sym;
 }
Node * geos::planargraph::DirectedEdge::getToNode () const inherited
Returns the node to which this DirectedEdge goes.
Definition at line 110 of file DirectedEdge.cpp.
Referenced by geos::operation::linemerge::LineSequencer::addReverseSubpath(), and geos::operation::linemerge::LineMergeDirectedEdge::getNext().
 {
   return to;
 }
bool geos::operation::polygonize::PolygonizeDirectedEdge::isInRing () const
Definition at line 95 of file PolygonizeDirectedEdge.cpp.
References edgeRing.
Referenced by geos::operation::polygonize::PolygonizeGraph::findDirEdgesInRing(), geos::operation::polygonize::PolygonizeGraph::findEdgeRing(), and geos::operation::polygonize::PolygonizeGraph::findIntersectionNodes().
 {
   return edgeRing!=nullptr;
 }
virtual bool geos::planargraph::GraphComponent::isMarked () const inline virtual inherited
Tests if a component has been marked at some point during the processing involving this graph.
Returns
true if the component has been marked
Definition at line 146 of file GraphComponent.h.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsStartingAt(), and geos::planargraph::operator<<().
 { return isMarkedVar; }
virtual bool geos::planargraph::GraphComponent::isVisited () const inline virtual inherited
Tests if a component has been visited during the course of a graph algorithm.
Returns
true if the component has been visited
Definition at line 72 of file GraphComponent.h.
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges(), geos::planargraph::algorithm::ConnectedSubgraphFinder::getConnectedSubgraphs(), and geos::planargraph::operator<<().
 { return isVisitedVar; }
string geos::planargraph::DirectedEdge::print () const inherited
Prints a detailed string representation of this DirectedEdge to the given PrintStream.
Definition at line 167 of file DirectedEdge.cpp.
 {
   ostringstream s;
   s << *this;
   return s.str();
 }
void geos::planargraph::DirectedEdge::setEdge (Edge * newParentEdge) inherited
Associates this DirectedEdge with an Edge (possibly null, indicating no associated Edge).
Definition at line 75 of file DirectedEdge.cpp.
Referenced by geos::planargraph::Edge::setDirectedEdges().
 {
   parentEdge=newParentEdge;
 }
void geos::operation::polygonize::PolygonizeDirectedEdge::setLabel (long newLabel)
Definition at line 65 of file PolygonizeDirectedEdge.cpp.
References label.
{
   label=newLabel;
 }
template<typename T > static void geos::planargraph::GraphComponent::setMarked (T start, T end, bool marked) inline static inherited
Sets the Marked state for the elements of a container, from start to end iterator.
Parameters
start the start element
end one past the last element
marked the state to set the marked flag to
Definition at line 119 of file GraphComponent.h.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForNonDegree2Nodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), geos::operation::linemerge::LineMerger::buildEdgeStringStartingWith(), geos::operation::polygonize::PolygonizeGraph::deleteAllEdges(), and geos::operation::polygonize::PolygonizeGraph::deleteCutEdges().
{
     for(T i=start; i!=end; ++i) {
       (*i)->setMarked(marked);
     }
   }
virtual void geos::planargraph::GraphComponent::setMarked (bool isMarked) inline virtual inherited
Sets the marked flag for this component.
Parameters
isMarked the desired value of the marked flag
Definition at line 152 of file GraphComponent.h.
 { isMarkedVar=isMarked; }
template<typename T > static void geos::planargraph::GraphComponent::setMarkedMap (T start, T end, bool marked) inline static inherited
Sets the Marked state for the values of each map container element, from start to end iterator.
Parameters
start the start element
end one past the last element
marked the state to set the visited flag to
Definition at line 135 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       i->second->setMarked(marked);
     }
   }
void geos::operation::polygonize::PolygonizeDirectedEdge::setNext (PolygonizeDirectedEdge * newNext)
Definition at line 84 of file PolygonizeDirectedEdge.cpp.
References next.
Referenced by geos::operation::polygonize::PolygonizeGraph::computeNextCCWEdges().
 {
   next=newNext;
 }
void geos::operation::polygonize::PolygonizeDirectedEdge::setRing (EdgeRing * newEdgeRing)
Definition at line 105 of file PolygonizeDirectedEdge.cpp.
References edgeRing.
 {
   edgeRing=newEdgeRing;
 }
void geos::planargraph::DirectedEdge::setSym (DirectedEdge * newSym) inherited
Sets this DirectedEdge's symmetric DirectedEdge, which runs in the opposite direction.
Definition at line 141 of file DirectedEdge.cpp.
Referenced by geos::planargraph::PlanarGraph::remove(), and geos::planargraph::Edge::setDirectedEdges().
 {
   sym = newSym;
 }
virtual void geos::planargraph::GraphComponent::setVisited (bool isVisited) inline virtual inherited
Sets the visited flag for this component.
Parameters
isVisited the desired value of the visited flag
Definition at line 78 of file GraphComponent.h.
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges(), and geos::operation::linemerge::LineSequencer::addReverseSubpath().
 { isVisitedVar=isVisited; }
template<typename T > static void geos::planargraph::GraphComponent::setVisited (T start, T end, bool visited) inline static inherited
Sets the Visited state for the elements of a container, from start to end iterator.
Parameters
start the start element
end one past the last element
visited the state to set the visited flag to
Definition at line 89 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       (*i)->setVisited(visited);
     }
   }
template<typename T > static void geos::planargraph::GraphComponent::setVisitedMap (T start, T end, bool visited) inline static inherited
Sets the Visited state for the values of each map container element, from start to end iterator.
Parameters
start the start element
end one past the last element
visited the state to set the visited flag to
Definition at line 104 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       i->second->setVisited(visited);
     }
   }
vector< Edge * > * geos::planargraph::DirectedEdge::toEdges (std::vector< DirectedEdge * > & dirEdges) static inherited
Returns a List containing the parent Edge (possibly null) for each of the given DirectedEdges.
NOTE: ownership of the returned vector is left to the caller, see the equivalent function taking a vector reference to avoid this.
Definition at line 43 of file DirectedEdge.cpp.
 {
   vector<Edge*> *edges=new vector<Edge*>();
   toEdges(dirEdges, *edges);
   return edges;
 }
void geos::planargraph::DirectedEdge::toEdges (std::vector< DirectedEdge * > & dirEdges, std::vector< Edge * > & parentEdges) static inherited
Add parent Edge (possibly null) of each of the given DirectedEdges to the given parentEdges vector.
NOTE: parents are pushed to the parentEdges vector, make sure it is empty if index-based corrispondence is important.
Definition at line 33 of file DirectedEdge.cpp.
 {
   for (size_t i=0, n=dirEdges.size(); i<n; ++i)
   {
     edges.push_back(dirEdges[i]->parentEdge);
   }
 }
Member Data Documentation
double geos::planargraph::DirectedEdge::angle protected inherited
Definition at line 64 of file DirectedEdge.h.
Referenced by geos::planargraph::operator<<().
bool geos::planargraph::DirectedEdge::edgeDirection protected inherited
Definition at line 62 of file DirectedEdge.h.
EdgeRing* geos::operation::polygonize::PolygonizeDirectedEdge::edgeRing private
Definition at line 58 of file PolygonizeDirectedEdge.h.
Referenced by isInRing(), PolygonizeDirectedEdge(), and setRing().
Node* geos::planargraph::DirectedEdge::from protected inherited
Definition at line 58 of file DirectedEdge.h.
bool geos::planargraph::GraphComponent::isMarkedVar protected inherited
Variable holding ''marked'' status.
Definition at line 51 of file GraphComponent.h.
bool geos::planargraph::GraphComponent::isVisitedVar protected inherited
Variable holding ''visited'' status.
Definition at line 54 of file GraphComponent.h.
long geos::operation::polygonize::PolygonizeDirectedEdge::label private
Definition at line 62 of file PolygonizeDirectedEdge.h.
Referenced by getLabel(), PolygonizeDirectedEdge(), and setLabel().
PolygonizeDirectedEdge* geos::operation::polygonize::PolygonizeDirectedEdge::next private
Definition at line 60 of file PolygonizeDirectedEdge.h.
Referenced by getNext(), PolygonizeDirectedEdge(), and setNext().
geom::Coordinate geos::planargraph::DirectedEdge::p0 protected inherited
Definition at line 60 of file DirectedEdge.h.
Referenced by geos::planargraph::DirectedEdge::compareDirection(), and geos::planargraph::operator<<().
geom::Coordinate geos::planargraph::DirectedEdge::p1 protected inherited
Definition at line 60 of file DirectedEdge.h.
Referenced by geos::planargraph::DirectedEdge::compareDirection(), and geos::planargraph::operator<<().
Edge* geos::planargraph::DirectedEdge::parentEdge protected inherited
Definition at line 57 of file DirectedEdge.h.
int geos::planargraph::DirectedEdge::quadrant protected inherited
Definition at line 63 of file DirectedEdge.h.
Referenced by geos::planargraph::DirectedEdge::compareDirection(), and geos::planargraph::operator<<().
DirectedEdge* geos::planargraph::DirectedEdge::sym protected inherited
Definition at line 61 of file DirectedEdge.h.
Node* geos::planargraph::DirectedEdge::to protected inherited
Definition at line 59 of file DirectedEdge.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/polygonize/PolygonizeDirectedEdge.h
/home/vicky/potree/geos/vicky/src/operation/polygonize/PolygonizeDirectedEdge.cpp