GEOS: geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter Class Reference
geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter Class Reference
#include <DiscreteHausdorffDistance.h>
Public Member Functions
MaxPointDistanceFilter (const geom::Geometry &geom)
void filter_ro (const geom::Coordinate *pt) override
const PointPairDistance & getMaxPointDistance () const
virtual void filter_rw (Coordinate *) const
Private Member Functions
MaxPointDistanceFilter (const MaxPointDistanceFilter &other)
MaxPointDistanceFilter & operator= (const MaxPointDistanceFilter &rhs)
Private Attributes
PointPairDistance maxPtDist
PointPairDistance minPtDist
DistanceToPoint euclideanDist
const geom::Geometry & geom
Detailed Description
Definition at line 155 of file DiscreteHausdorffDistance.h.
Constructor & Destructor Documentation
geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::MaxPointDistanceFilter (const geom::Geometry & geom) inline
Definition at line 158 of file DiscreteHausdorffDistance.h.
       :
       geom(geom)
     {}
geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::MaxPointDistanceFilter (const MaxPointDistanceFilter & other) private
Member Function Documentation
void geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::filter_ro (const geom::Coordinate *) inline override virtual
Performs an operation with coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented from geos::geom::CoordinateFilter.
Definition at line 163 of file DiscreteHausdorffDistance.h.
     {
       minPtDist.initialize();
       DistanceToPoint::computeDistance(geom, *pt,
                                                minPtDist);
       maxPtDist.setMaximum(minPtDist);
     }
virtual void geos::geom::CoordinateFilter::filter_rw (Coordinate *) const inline virtual inherited
Performs an operation on coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented in geos::noding::ScaledNoder::ReScaler, geos::noding::ScaledNoder::Scaler, geos::precision::CommonCoordinateFilter, geos::operation::overlay::ElevationMatrixFilter, and geos::precision::Translater.
Definition at line 52 of file CoordinateFilter.h.
Referenced by geos::geom::CoordinateArraySequence::apply_rw(), and geos::geom::Point::apply_rw().
 { assert(0); }
const PointPairDistance& geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::getMaxPointDistance () const inline
Definition at line 171 of file DiscreteHausdorffDistance.h.
Referenced by geos::algorithm::distance::DiscreteHausdorffDistance::computeOrientedDistance().
     {
       return maxPtDist;
     }
MaxPointDistanceFilter& geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::operator= (const MaxPointDistanceFilter & rhs) private
Member Data Documentation
DistanceToPoint geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::euclideanDist private
Definition at line 179 of file DiscreteHausdorffDistance.h.
const geom::Geometry& geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::geom private
Definition at line 180 of file DiscreteHausdorffDistance.h.
PointPairDistance geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::maxPtDist private
Definition at line 177 of file DiscreteHausdorffDistance.h.
PointPairDistance geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::minPtDist private
Definition at line 178 of file DiscreteHausdorffDistance.h.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/algorithm/distance/DiscreteHausdorffDistance.h