GEOS: geos::geom::util::GeometryEditor Class Reference
geos::geom::util::GeometryEditor Class Reference
#include <GeometryEditor.h>
Public Member Functions
GeometryEditor ()
GeometryEditor (const GeometryFactory *newFactory)
Geometry * edit (const Geometry *geometry, GeometryEditorOperation *operation)
Private Member Functions
Polygon * editPolygon (const Polygon *polygon, GeometryEditorOperation *operation)
GeometryCollection * editGeometryCollection (const GeometryCollection *collection, GeometryEditorOperation *operation)
Private Attributes
const GeometryFactory * factory
Detailed Description
Supports creating a new Geometry which is a modification of an existing one. Geometry objects are intended to be treated as immutable. This class allows you to "modify" a Geometry by traversing it and creating a new Geometry with the same overall structure but possibly modified components.
The following kinds of modifications can be made:
the values of the coordinates may be changed. Changing coordinate values may make the result Geometry invalid; this is not checked by the GeometryEditor
the coordinate lists may be changed (e.g. by adding or deleting coordinates). The modifed coordinate lists must be consistent with their original parent component (e.g. a LinearRing must always have at least 4 coordinates, and the first and last coordinate must be equal)
components of the original geometry may be deleted (e.g. holes may be removed from a Polygon, or LineStrings removed from a MultiLineString). Deletions will be propagated up the component tree appropriately.
Note that all changes must be consistent with the original Geometry's structure (e.g. a Polygon cannot be collapsed into a LineString).
The resulting Geometry is not checked for validity. If validity needs to be enforced, the new Geometry's isValid should be checked.
See also
Geometry::isValid
Definition at line 78 of file GeometryEditor.h.
Constructor & Destructor Documentation
geos::geom::util::GeometryEditor::GeometryEditor ()
Creates a new GeometryEditor object which will create an edited Geometry with the same GeometryFactory as the input Geometry.
Definition at line 50 of file GeometryEditor.cpp.
{
   factory=nullptr;
 }
geos::geom::util::GeometryEditor::GeometryEditor (const GeometryFactory * newFactory)
Creates a new GeometryEditor object which will create the edited Geometry with the given GeometryFactory
Parameters
newFactory the GeometryFactory to create the edited Geometry with
Creates a new GeometryEditor object which will create the edited Geometry with the given GeometryFactory
Parameters
factory the GeometryFactory to create the edited Geometry with
Definition at line 60 of file GeometryEditor.cpp.
{
   factory=newFactory;
 }
Member Function Documentation
Geometry * geos::geom::util::GeometryEditor::edit (const Geometry * geometry, GeometryEditorOperation * operation)
Edit the input Geometry with the given edit operation. Clients will create subclasses of GeometryEditorOperation or CoordinateOperation to perform required modifications.
Parameters
geometry the Geometry to edit
operation the edit operation to carry out
Returns
a new Geometry which is the result of the editing
Edit the input Geometry with the given edit operation. Clients will create subclasses of GeometryEditorOperation or CoordinateOperation to perform required modifications.
Parameters
geometry the Geometry to edit
operation the edit operation to carry out
Returns
a new Geometry which is the result of the editing
Definition at line 74 of file GeometryEditor.cpp.
References geos::geom::util::GeometryEditorOperation::edit(), and geos::geom::Geometry::getFactory().
Referenced by geos::geom::GeometryFactory::createGeometry(), and geos::precision::SimpleGeometryPrecisionReducer::reduce().
 {
   // if client did not supply a GeometryFactory, use the one from the input Geometry
   if (factory == nullptr)
     factory=geometry->getFactory();
   if ( const GeometryCollection *gc =
             dynamic_cast<const GeometryCollection*>(geometry) )
   {
     return editGeometryCollection(gc, operation);
   }
   if ( const Polygon *p = dynamic_cast<const Polygon*>(geometry) )
   {
     return editPolygon(p, operation);
   }
   if ( dynamic_cast<const Point*>(geometry) )
   {
     return operation->edit(geometry, factory);
   }
   if ( dynamic_cast<const LineString*>(geometry) )
   {
     return operation->edit(geometry, factory);
   }
     // Unsupported Geometry classes should be caught in the GeometryEditorOperation.
     assert(!static_cast<bool>("SHOULD NEVER GET HERE"));
     return nullptr;
 }
GeometryCollection * geos::geom::util::GeometryEditor::editGeometryCollection (const GeometryCollection * collection, GeometryEditorOperation * operation) private
Definition at line 154 of file GeometryEditor.cpp.
References geos::geom::util::GeometryEditorOperation::edit(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), and geos::geom::Geometry::isEmpty().
 {
   GeometryCollection *newCollection = dynamic_cast<GeometryCollection*>( operation->edit(collection,factory) );
   vector<Geometry*> *geometries = new vector<Geometry*>();
   for (std::size_t i=0, n=newCollection->getNumGeometries(); i<n; i++)
   {
     Geometry *geometry = edit(newCollection->getGeometryN(i),
       operation);
     if (geometry->isEmpty()) {
       delete geometry;
       continue;
     }
     geometries->push_back(geometry);
   }
   if (typeid(*newCollection)==typeid(MultiPoint)) {
     delete newCollection;
     return factory->createMultiPoint(geometries);
   }
   else if (typeid(*newCollection)==typeid(MultiLineString)) {
     delete newCollection;
     return factory->createMultiLineString(geometries);
   }
   else if (typeid(*newCollection)==typeid(MultiPolygon)) {
     delete newCollection;
     return factory->createMultiPolygon(geometries);
   }
   else {
     delete newCollection;
     return factory->createGeometryCollection(geometries);
   }
 }
Polygon * geos::geom::util::GeometryEditor::editPolygon (const Polygon * polygon, GeometryEditorOperation * operation) private
Definition at line 107 of file GeometryEditor.cpp.
References geos::geom::util::GeometryEditorOperation::edit(), geos::geom::Polygon::getExteriorRing(), geos::geom::Geometry::getFactory(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), and geos::geom::Polygon::isEmpty().
 {
   Polygon* newPolygon= dynamic_cast<Polygon*>(
     operation->edit(polygon, factory)
   );
   if (newPolygon->isEmpty()) {
     //RemoveSelectedPlugIn relies on this behaviour. [Jon Aquino]
     if ( newPolygon->getFactory() != factory ) {
       Polygon *ret = factory->createPolygon(nullptr, nullptr);
       delete newPolygon;
       return ret;
     } else {
       return newPolygon;
     }
   }
   Geometry* editResult = edit(newPolygon->getExteriorRing(),operation);
   LinearRing* shell = dynamic_cast<LinearRing*>(editResult);
   if (shell->isEmpty()) {
     //RemoveSelectedPlugIn relies on this behaviour. [Jon Aquino]
     delete shell;
     delete newPolygon;
     return factory->createPolygon(nullptr,nullptr);
   }
   vector<Geometry*> *holes=new vector<Geometry*>;
   for (size_t i=0, n=newPolygon->getNumInteriorRing(); i<n; ++i)
   {
     Geometry *hole_geom = edit(newPolygon->getInteriorRingN(i),
       operation);
     LinearRing *hole = dynamic_cast<LinearRing*>(hole_geom);
     assert(hole);
     if (hole->isEmpty())
     {
       continue;
     }
     holes->push_back(hole);
   }
   delete newPolygon;
   return factory->createPolygon(shell,holes);
 }
Member Data Documentation
const GeometryFactory* geos::geom::util::GeometryEditor::factory private
The factory used to create the modified Geometry
Definition at line 83 of file GeometryEditor.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/util/GeometryEditor.h
/home/vicky/potree/geos/vicky/src/geom/util/GeometryEditor.cpp