GEOS: geos::index::chain::MonotoneChain Class Reference
geos::index::chain::MonotoneChain Class Reference
Monotone Chains are a way of partitioning the segments of a linestring to allow for fast searching of intersections.
#include <MonotoneChain.h>
Public Member Functions
MonotoneChain (const geom::CoordinateSequence &pts, std::size_t start, std::size_t end, void *context)
~MonotoneChain ()
const geom::Envelope & getEnvelope () const
Returned envelope is owned by this class.
size_t getStartIndex () const
size_t getEndIndex () const
void getLineSegment (std::size_t index, geom::LineSegment &ls) const
Set given LineSegment with points of the segment starting at the given index.
std::unique_ptr< geom::CoordinateSequence > getCoordinates () const
void select (const geom::Envelope &searchEnv, MonotoneChainSelectAction &mcs)
void computeOverlaps (MonotoneChain *mc, MonotoneChainOverlapAction *mco)
void setId (int nId)
int getId () const
void * getContext ()
Private Member Functions
void computeSelect (const geom::Envelope &searchEnv, size_t start0, size_t end0, MonotoneChainSelectAction &mcs)
void computeOverlaps (std::size_t start0, std::size_t end0, MonotoneChain &mc, std::size_t start1, std::size_t end1, MonotoneChainOverlapAction &mco)
MonotoneChain (const MonotoneChain &other)=delete
MonotoneChain & operator= (const MonotoneChain &rhs)=delete
Private Attributes
const geom::CoordinateSequence & pts
Externally owned.
geom::Envelope * env
Owned by this class, lazely created.
void * context
user-defined information
size_t start
Index of chain start vertex into the CoordinateSequence, 0 based.
size_t end
Index of chain end vertex into the CoordinateSequence, 0 based.
int id
useful for optimizing chain comparisons
Detailed Description
Monotone Chains are a way of partitioning the segments of a linestring to allow for fast searching of intersections.
They have the following properties:
the segments within a monotone chain never intersect each other
the envelope of any contiguous subset of the segments in a monotone chain is equal to the envelope of the endpoints of the subset.
Property 1 means that there is no need to test pairs of segments from within the same monotone chain for intersection. Property 2 allows an efficient binary search to be used to find the intersection points of two monotone chains.
For many types of real-world data, these properties eliminate a large number of segment comparisons, producing substantial speed gains.
One of the goals of this implementation of MonotoneChains is to be as space and time efficient as possible. One design choice that aids this is that a MonotoneChain is based on a subarray of a list of points. This means that new arrays of points (potentially very large) do not have to be allocated.
MonotoneChains support the following kinds of queries:
Envelope select: determine all the segments in the chain which intersect a given envelope
Overlap: determine all the pairs of segments in two chains whose envelopes overlap
This implementation of MonotoneChains uses the concept of internal iterators to return the resultsets for the above queries. This has time and space advantages, since it is not necessary to build lists of instantiated objects to represent the segments returned by the query. However, it does mean that the queries are not thread-safe.
Definition at line 85 of file MonotoneChain.h.
Constructor & Destructor Documentation
geos::index::chain::MonotoneChain::MonotoneChain (const geom::CoordinateSequence & pts, std::size_t start, std::size_t end, void * context)
Parameters
pts Ownership left to caller, this class holds a reference.
start
end
context Ownership left to caller, this class holds a reference.
geos::index::chain::MonotoneChain::~MonotoneChain ()
Definition at line 45 of file MonotoneChain.cpp.
 {
     delete env;
 }
geos::index::chain::MonotoneChain::MonotoneChain (const MonotoneChain & other) private delete
Member Function Documentation
void geos::index::chain::MonotoneChain::computeOverlaps (MonotoneChain * mc, MonotoneChainOverlapAction * mco)
Definition at line 119 of file MonotoneChain.cpp.
References end, geos::geom::Envelope::init(), geos::geom::Envelope::intersects(), geos::index::chain::MonotoneChainOverlapAction::overlap(), pts, start, geos::index::chain::MonotoneChainOverlapAction::tempEnv1, and geos::index::chain::MonotoneChainOverlapAction::tempEnv2.
Referenced by geos::noding::MCIndexNoder::intersectChains(), and geos::noding::MCIndexSegmentSetMutualIntersector::intersectChains().
 {
     computeOverlaps(start, end, *mc, mc->start, mc->end, *mco);
 }
void geos::index::chain::MonotoneChain::computeOverlaps (std::size_t start0, std::size_t end0, MonotoneChain & mc, std::size_t start1, std::size_t end1, MonotoneChainOverlapAction & mco) private
void geos::index::chain::MonotoneChain::computeSelect (const geom::Envelope & searchEnv, size_t start0, size_t end0, MonotoneChainSelectAction & mcs) private
Definition at line 82 of file MonotoneChain.cpp.
References geos::geom::Envelope::init(), geos::geom::Envelope::intersects(), geos::index::chain::MonotoneChainSelectAction::select(), and geos::index::chain::MonotoneChainSelectAction::tempEnv1.
 {
     const Coordinate& p0=pts[start0];
     const Coordinate& p1=pts[end0];
     mcs.tempEnv1.init(p0,p1);
     //Debug.println("trying:"+p0+p1+" [ "+start0+","+end0+" ]");
     // terminating condition for the recursion
     if(end0-start0==1)
     {
         //Debug.println("computeSelect:"+p0+p1);
         mcs.select(*this, static_cast<unsigned int>(start0));
         return;
     }
     // nothing to do if the envelopes don't overlap
     if (!searchEnv.intersects(mcs.tempEnv1))
         return;
     // the chains overlap,so split each in half and iterate (binary search)
     unsigned int mid= static_cast<unsigned int>((start0 + end0) / 2);
     // Assert: mid != start or end (since we checked above for end-start <= 1)
     // check terminating conditions before recursing
     if (start0 < mid)
     {
         computeSelect(searchEnv,start0,mid,mcs);
     }
     if (mid < end0)
     {
         computeSelect(searchEnv,mid,end0,mcs);
     }
 }
void* geos::index::chain::MonotoneChain::getContext () inline
Definition at line 138 of file MonotoneChain.h.
Referenced by geos::noding::MCIndexSegmentSetMutualIntersector::SegmentOverlapAction::overlap(), geos::noding::MCIndexNoder::SegmentOverlapAction::overlap(), and geos::noding::snapround::HotPixelSnapAction::select().
 { return context; }
std::unique_ptr< CoordinateSequence > geos::index::chain::MonotoneChain::getCoordinates (void) const
Return the subsequence of coordinates forming this chain. Allocates a new CoordinateSequence to hold the Coordinates
Definition at line 70 of file MonotoneChain.cpp.
 {
     return std::unique_ptr<CoordinateSequence>(pts.clone());
 }
size_t geos::index::chain::MonotoneChain::getEndIndex () const inline
Definition at line 109 of file MonotoneChain.h.
 { return end; }
const Envelope & geos::index::chain::MonotoneChain::getEnvelope () const
Returned envelope is owned by this class.
Definition at line 51 of file MonotoneChain.cpp.
Referenced by geos::noding::MCIndexNoder::add(), geos::noding::MCIndexSegmentSetMutualIntersector::addToIndex(), geos::algorithm::MCPointInRing::buildIndex(), geos::noding::MCIndexNoder::intersectChains(), and geos::noding::MCIndexSegmentSetMutualIntersector::intersectChains().
 {
     if (nullptr == env)
     {
         const Coordinate& p0 = pts[start];
         const Coordinate& p1 = pts[end];
         env = new Envelope(p0, p1);
     }
     return *env;
 }
int geos::index::chain::MonotoneChain::getId () const inline
Definition at line 136 of file MonotoneChain.h.
Referenced by geos::noding::MCIndexNoder::intersectChains().
 { return id; }
void geos::index::chain::MonotoneChain::getLineSegment (std::size_t index, geom::LineSegment & ls) const
Set given LineSegment with points of the segment starting at the given index.
Definition at line 63 of file MonotoneChain.cpp.
References geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by geos::index::chain::MonotoneChainSelectAction::select().
 {
     ls.p0 = pts[index];
     ls.p1 = pts[index+1];
 }
size_t geos::index::chain::MonotoneChain::getStartIndex () const inline
Definition at line 107 of file MonotoneChain.h.
 { return start; }
MonotoneChain& geos::index::chain::MonotoneChain::operator= (const MonotoneChain & rhs) private delete
void geos::index::chain::MonotoneChain::select (const geom::Envelope & searchEnv, MonotoneChainSelectAction & mcs)
Determine all the line segments in the chain whose envelopes overlap the searchEnvelope, and process them
Definition at line 76 of file MonotoneChain.cpp.
Referenced by geos::algorithm::MCPointInRing::testMonotoneChain(), and geos::noding::snapround::MCIndexPointSnapperVisitor::visitItem().
 {
     computeSelect(searchEnv, start, end, mcs);
 }
void geos::index::chain::MonotoneChain::setId (int nId) inline
Definition at line 134 of file MonotoneChain.h.
Referenced by geos::noding::MCIndexNoder::add(), geos::noding::MCIndexSegmentSetMutualIntersector::addToIndex(), and geos::noding::MCIndexSegmentSetMutualIntersector::addToMonoChains().
 { id=nId; }
Member Data Documentation
void* geos::index::chain::MonotoneChain::context private
user-defined information
Definition at line 158 of file MonotoneChain.h.
size_t geos::index::chain::MonotoneChain::end private
Index of chain end vertex into the CoordinateSequence, 0 based.
Definition at line 164 of file MonotoneChain.h.
Referenced by computeOverlaps().
geom::Envelope* geos::index::chain::MonotoneChain::env mutable private
Owned by this class, lazely created.
Definition at line 155 of file MonotoneChain.h.
int geos::index::chain::MonotoneChain::id private
useful for optimizing chain comparisons
Definition at line 167 of file MonotoneChain.h.
const geom::CoordinateSequence& geos::index::chain::MonotoneChain::pts private
Externally owned.
Definition at line 152 of file MonotoneChain.h.
Referenced by computeOverlaps().
size_t geos::index::chain::MonotoneChain::start private
Index of chain start vertex into the CoordinateSequence, 0 based.
Definition at line 161 of file MonotoneChain.h.
Referenced by computeOverlaps().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/chain/MonotoneChain.h
/home/vicky/potree/geos/vicky/src/index/chain/MonotoneChain.cpp