GEOS: geos::geom::util::GeometryTransformer Class Reference
geos::geom::util::GeometryTransformer Class Reference
A framework for processes which transform an input Geometry into an output Geometry, possibly changing its structure and type(s).
#include <GeometryTransformer.h>
Public Member Functions
GeometryTransformer ()
virtual ~GeometryTransformer ()
std::unique_ptr< Geometry > transform (const Geometry *nInputGeom)
void setSkipTransformedInvalidInteriorRings (bool b)
Protected Member Functions
CoordinateSequence::Ptr createCoordinateSequence (std::unique_ptr< std::vector< Coordinate > > coords)
virtual CoordinateSequence::Ptr transformCoordinates (const CoordinateSequence *coords, const Geometry *parent)
virtual Geometry::Ptr transformPoint (const Point *geom, const Geometry *parent)
virtual Geometry::Ptr transformMultiPoint (const MultiPoint *geom, const Geometry *parent)
virtual Geometry::Ptr transformLinearRing (const LinearRing *geom, const Geometry *parent)
virtual Geometry::Ptr transformLineString (const LineString *geom, const Geometry *parent)
virtual Geometry::Ptr transformMultiLineString (const MultiLineString *geom, const Geometry *parent)
virtual Geometry::Ptr transformPolygon (const Polygon *geom, const Geometry *parent)
virtual Geometry::Ptr transformMultiPolygon (const MultiPolygon *geom, const Geometry *parent)
virtual Geometry::Ptr transformGeometryCollection (const GeometryCollection *geom, const Geometry *parent)
Protected Attributes
const GeometryFactory * factory
Private Member Functions
GeometryTransformer (const GeometryTransformer &other)=delete
GeometryTransformer & operator= (const GeometryTransformer &rhs)=delete
Private Attributes
const Geometry * inputGeom
bool pruneEmptyGeometry
bool preserveGeometryCollectionType
bool preserveCollections
bool preserveType
bool skipTransformedInvalidInteriorRings
Detailed Description
A framework for processes which transform an input Geometry into an output Geometry, possibly changing its structure and type(s).
This class is a framework for implementing subclasses which perform transformations on various different Geometry subclasses. It provides an easy way of applying specific transformations to given geometry types, while allowing unhandled types to be simply copied. Also, the framework ensures that if subcomponents change type the parent geometries types change appropriately to maintain valid structure. Subclasses will override whichever transformX methods they need to to handle particular Geometry types.
A typically usage would be a transformation that may transform Polygons into Polygons, LineStrings or Points. This class would likely need to override the transformMultiPolygon method to ensure that if input Polygons change type the result is a GeometryCollection, not a MultiPolygon
The default behaviour of this class is to simply recursively transform each Geometry component into an identical object by copying.
Note that all transformX methods may return null, to avoid creating empty geometry objects. This will be handled correctly by the transformer. The transform method itself will always return a geometry object.
See also
GeometryEditor
Possible extensions: getParent() method to return immediate parent e.g. of LinearRings in Polygons
Definition at line 92 of file GeometryTransformer.h.
Constructor & Destructor Documentation
geos::geom::util::GeometryTransformer::GeometryTransformer ()
Definition at line 55 of file GeometryTransformer.cpp.
   :
   factory(nullptr),
   inputGeom(nullptr),
   pruneEmptyGeometry(true),
   preserveGeometryCollectionType(true),
   preserveCollections(false),
   preserveType(false),
   skipTransformedInvalidInteriorRings(false)
 {}
geos::geom::util::GeometryTransformer::~GeometryTransformer () virtual
Definition at line 66 of file GeometryTransformer.cpp.
 {
 }
geos::geom::util::GeometryTransformer::GeometryTransformer (const GeometryTransformer & other) private delete
Member Function Documentation
std::unique_ptr< CoordinateSequence > geos::geom::util::GeometryTransformer::createCoordinateSequence (std::unique_ptr< std::vector< Coordinate > > coords) protected
Convenience method which provides standard way of creating a CoordinateSequence
Parameters
coords the coordinate array to copy
Returns
a coordinate sequence for the array
[final]
Definition at line 109 of file GeometryTransformer.cpp.
References geos::geom::CoordinateSequenceFactory::create(), factory, and geos::geom::GeometryFactory::getCoordinateSequenceFactory().
 {
   return std::unique_ptr<CoordinateSequence>(
     factory->getCoordinateSequenceFactory()->create(
         coords.release())
   );
 }
GeometryTransformer& geos::geom::util::GeometryTransformer::operator= (const GeometryTransformer & rhs) private delete
void geos::geom::util::GeometryTransformer::setSkipTransformedInvalidInteriorRings (bool b)
Definition at line 70 of file GeometryTransformer.cpp.
References skipTransformedInvalidInteriorRings.
Referenced by geos::simplify::DPTransformer::DPTransformer().
 {
   skipTransformedInvalidInteriorRings = b;
 }
unique_ptr< Geometry > geos::geom::util::GeometryTransformer::transform (const Geometry * nInputGeom)
Definition at line 77 of file GeometryTransformer.cpp.
References factory, geos::geom::Geometry::getFactory(), inputGeom, transformGeometryCollection(), transformLinearRing(), transformLineString(), transformMultiLineString(), transformMultiPoint(), transformMultiPolygon(), transformPoint(), and transformPolygon().
Referenced by geos::simplify::DouglasPeuckerSimplifier::getResultGeometry(), and transformGeometryCollection().
 {
   using geos::util::IllegalArgumentException;
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transform(Geometry " << nInputGeom << ");" << std::endl;
 #endif
   inputGeom = nInputGeom;
   factory = inputGeom->getFactory();
   if ( const Point* p=dynamic_cast<const Point*>(inputGeom) )
     return transformPoint(p, nullptr);
   if ( const MultiPoint* mp=dynamic_cast<const MultiPoint*>(inputGeom) )
     return transformMultiPoint(mp, nullptr);
   if ( const LinearRing* lr=dynamic_cast<const LinearRing*>(inputGeom) )
     return transformLinearRing(lr, nullptr);
   if ( const LineString* ls=dynamic_cast<const LineString*>(inputGeom) )
     return transformLineString(ls, nullptr);
   if ( const MultiLineString* mls=dynamic_cast<const MultiLineString*>(inputGeom) )
     return transformMultiLineString(mls, nullptr);
   if ( const Polygon* p=dynamic_cast<const Polygon*>(inputGeom) )
     return transformPolygon(p, nullptr);
   if ( const MultiPolygon* mp=dynamic_cast<const MultiPolygon*>(inputGeom) )
     return transformMultiPolygon(mp, nullptr);
   if ( const GeometryCollection* gc=dynamic_cast<const GeometryCollection*>(inputGeom) )
     return transformGeometryCollection(gc, nullptr);
   throw IllegalArgumentException("Unknown Geometry subtype.");
 }
std::unique_ptr< CoordinateSequence > geos::geom::util::GeometryTransformer::transformCoordinates (const CoordinateSequence * coords, const Geometry * parent) protected virtual
Reimplemented in geos::operation::overlay::snap::SnapTransformer, and geos::simplify::DPTransformer.
Definition at line 119 of file GeometryTransformer.cpp.
References geos::geom::CoordinateSequence::clone(), and geos::ignore_unused_variable_warning().
Referenced by transformLinearRing(), transformLineString(), and transformPoint().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformCoordinates(CoordinateSequence " << coords <<", Geometry " << parent << ");" << std::endl;
 #endif
   return std::unique_ptr<CoordinateSequence>(coords->clone());
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformGeometryCollection (const GeometryCollection * geom, const Geometry * parent) protected virtual
Definition at line 358 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::buildGeometry(), geos::geom::GeometryFactory::createGeometryCollection(), factory, geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::ignore_unused_variable_warning(), preserveGeometryCollectionType, pruneEmptyGeometry, and transform().
Referenced by transform().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformGeometryCollection(GeometryCollection " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   vector<Geometry*>* transGeomList = new vector<Geometry*>();
   for (std::size_t i=0, n=geom->getNumGeometries(); i<n; i++)
   {
     Geometry::Ptr transformGeom = transform(
       geom->getGeometryN(i)); // no parent ?
     if ( transformGeom.get() == nullptr ) continue;
     if ( pruneEmptyGeometry && transformGeom->isEmpty() ) continue;
     // If an exception is thrown we'll leak
     transGeomList->push_back(transformGeom.release());
   }
   if ( preserveGeometryCollectionType )
   {
     return Geometry::Ptr(factory->createGeometryCollection(
       transGeomList));
   }
   else
   {
     return Geometry::Ptr(factory->buildGeometry(transGeomList));
   }
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformLinearRing (const LinearRing * geom, const Geometry * parent) protected virtual
Definition at line 180 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createLineString(), factory, geos::geom::LineString::getCoordinatesRO(), geos::ignore_unused_variable_warning(), preserveType, and transformCoordinates().
Referenced by transform(), and transformPolygon().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformLinearRing(LinearRing " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   CoordinateSequence::Ptr seq(transformCoordinates(
     geom->getCoordinatesRO(), geom));
   auto seqSize = seq->size();
   // ensure a valid LinearRing
   if ( seqSize > 0 && seqSize < 4 && ! preserveType )
   {
     return factory->createLineString(std::move(seq));
   }
   else
   {
     return factory->createLinearRing(std::move(seq));
   }
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformLineString (const LineString * geom, const Geometry * parent) protected virtual
Definition at line 207 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::createLineString(), factory, geos::geom::LineString::getCoordinatesRO(), geos::ignore_unused_variable_warning(), and transformCoordinates().
Referenced by transform(), and transformMultiLineString().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformLineString(LineString " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   // should check for 1-point sequences and downgrade them to points
   return factory->createLineString(
     transformCoordinates(geom->getCoordinatesRO(), geom));
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformMultiLineString (const MultiLineString * geom, const Geometry * parent) protected virtual
Definition at line 223 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::buildGeometry(), factory, geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::ignore_unused_variable_warning(), and transformLineString().
Referenced by transform().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformMultiLineString(MultiLineString " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   vector<Geometry*>* transGeomList = new vector<Geometry*>();
   for (unsigned int i=0, n=static_cast<unsigned int>(geom->getNumGeometries()); i<n; i++)
   {
     const LineString* l = dynamic_cast<const LineString*>(
         geom->getGeometryN(i));
     assert(l);
     Geometry::Ptr transformGeom = transformLineString(l, geom);
     if ( transformGeom.get() == nullptr ) continue;
     if ( transformGeom->isEmpty() ) continue;
     // If an exception is thrown we'll leak
     transGeomList->push_back(transformGeom.release());
   }
   return Geometry::Ptr(factory->buildGeometry(transGeomList));
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformMultiPoint (const MultiPoint * geom, const Geometry * parent) protected virtual
Definition at line 150 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::buildGeometry(), factory, geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::ignore_unused_variable_warning(), and transformPoint().
Referenced by transform().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformMultiPoint(MultiPoint " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   vector<Geometry*>* transGeomList = new vector<Geometry*>();
   for (unsigned int i=0, n=static_cast<unsigned int>(geom->getNumGeometries()); i<n; i++)
   {
     const Point* p = dynamic_cast<const Point*>(geom->getGeometryN(i));
     assert(p);
     Geometry::Ptr transformGeom = transformPoint(p, geom);
     if ( transformGeom.get() == nullptr ) continue;
     if ( transformGeom->isEmpty() ) continue;
     // If an exception is thrown we'll leak
     transGeomList->push_back(transformGeom.release());
   }
   return Geometry::Ptr(factory->buildGeometry(transGeomList));
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformMultiPolygon (const MultiPolygon * geom, const Geometry * parent) protected virtual
Reimplemented in geos::simplify::DPTransformer.
Definition at line 327 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::buildGeometry(), factory, geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::ignore_unused_variable_warning(), and transformPolygon().
Referenced by transform().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformMultiPolygon(MultiPolygon " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   unique_ptr< vector<Geometry*> > transGeomList( new vector<Geometry*>() );
   for (std::size_t i=0, n=geom->getNumGeometries(); i<n; i++)
   {
     const Polygon* p = dynamic_cast<const Polygon*>(
         geom->getGeometryN(i));
     assert(p);
     Geometry::Ptr transformGeom = transformPolygon(p, geom);
     if ( transformGeom.get() == nullptr ) continue;
     if ( transformGeom->isEmpty() ) continue;
     // If an exception is thrown we'll leak
     transGeomList->push_back(transformGeom.release());
   }
   return Geometry::Ptr(factory->buildGeometry(transGeomList.release()));
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformPoint (const Point * geom, const Geometry * parent) protected virtual
Definition at line 133 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::createPoint(), factory, geos::geom::Point::getCoordinatesRO(), geos::ignore_unused_variable_warning(), and transformCoordinates().
Referenced by transform(), and transformMultiPoint().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformPoint(Point " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   CoordinateSequence::Ptr cs(transformCoordinates(
     geom->getCoordinatesRO(), geom));
   return Geometry::Ptr(factory->createPoint(cs.release()));
 }
Geometry::Ptr geos::geom::util::GeometryTransformer::transformPolygon (const Polygon * geom, const Geometry * parent) protected virtual
Reimplemented in geos::simplify::DPTransformer.
Definition at line 254 of file GeometryTransformer.cpp.
References geos::geom::GeometryFactory::buildGeometry(), geos::geom::GeometryFactory::createPolygon(), factory, geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), geos::ignore_unused_variable_warning(), geos::geom::LineString::isEmpty(), skipTransformedInvalidInteriorRings, and transformLinearRing().
Referenced by transform(), and transformMultiPolygon().
 {
     ::geos::ignore_unused_variable_warning(parent);
 #if GEOS_DEBUG
   std::cerr << "GeometryTransformer::transformPolygon(Polygon " << geom <<", Geometry " << parent << ");" << std::endl;
 #endif
   bool isAllValidLinearRings = true;
   const LinearRing* lr = dynamic_cast<const LinearRing*>(
       geom->getExteriorRing());
   assert(lr);
   Geometry::Ptr shell = transformLinearRing(lr, geom);
   if ( shell.get() == nullptr
     || ! dynamic_cast<LinearRing*>(shell.get())
     || shell->isEmpty() )
   {
     isAllValidLinearRings = false;
   }
   vector<Geometry*>* holes = new vector<Geometry*>();
   for (unsigned int i=0, n=static_cast<unsigned int>(geom->getNumInteriorRing()); i<n; i++)
   {
     const LinearRing* lr = dynamic_cast<const LinearRing*>(
       geom->getInteriorRingN(i));
     assert(lr);
     Geometry::Ptr hole(transformLinearRing(lr, geom));
     if ( hole.get() == nullptr || hole->isEmpty() ) {
       continue;
     }
     if ( ! dynamic_cast<LinearRing*>(hole.get()) )
     {
       if ( skipTransformedInvalidInteriorRings )
           continue;
       isAllValidLinearRings = false;
     }
     holes->push_back(hole.release());
   }
   if ( isAllValidLinearRings)
   {
     Geometry* sh = shell.release();
     LinearRing* lr = dynamic_cast<LinearRing*>(sh);
     assert(lr);
     return Geometry::Ptr(factory->createPolygon(lr, holes));
   }
   else
   {
     // would like to use a manager constructor here
     vector<Geometry*>* components = new vector<Geometry*>();
     if ( shell.get() != nullptr ) {
       components->push_back(shell.release());
     }
     components->insert(components->end(),
       holes->begin(), holes->end());
     delete holes; // :(
     return Geometry::Ptr(factory->buildGeometry(components));
   }
 }
Member Data Documentation
const GeometryFactory* geos::geom::util::GeometryTransformer::factory protected
Definition at line 106 of file GeometryTransformer.h.
Referenced by createCoordinateSequence(), transform(), geos::simplify::DPTransformer::transformCoordinates(), transformGeometryCollection(), transformLinearRing(), transformLineString(), transformMultiLineString(), transformMultiPoint(), transformMultiPolygon(), transformPoint(), and transformPolygon().
const Geometry* geos::geom::util::GeometryTransformer::inputGeom private
Definition at line 158 of file GeometryTransformer.h.
Referenced by transform().
bool geos::geom::util::GeometryTransformer::preserveCollections private
true if the output from a collection argument should still be a collection
Definition at line 176 of file GeometryTransformer.h.
bool geos::geom::util::GeometryTransformer::preserveGeometryCollectionType private
true if a homogenous collection result from a GeometryCollection should still be a general GeometryCollection
Definition at line 171 of file GeometryTransformer.h.
Referenced by transformGeometryCollection().
bool geos::geom::util::GeometryTransformer::preserveType private
true if the type of the input should be preserved
Definition at line 181 of file GeometryTransformer.h.
Referenced by transformLinearRing().
bool geos::geom::util::GeometryTransformer::pruneEmptyGeometry private
true if empty geometries should not be included in the result
Definition at line 164 of file GeometryTransformer.h.
Referenced by transformGeometryCollection().
bool geos::geom::util::GeometryTransformer::skipTransformedInvalidInteriorRings private
true if transformed invalid interior rings should be skipped
Definition at line 186 of file GeometryTransformer.h.
Referenced by setSkipTransformedInvalidInteriorRings(), and transformPolygon().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/util/GeometryTransformer.h
/home/vicky/potree/geos/vicky/src/geom/util/GeometryTransformer.cpp