GEOS: geos::geom::GeometryFactory Class Reference
geos::geom::GeometryFactory Class Reference
Supplies a set of utility methods for building Geometry objects from CoordinateSequence or other Geometry objects.
#include <GeometryFactory.h>
Classes
struct GeometryFactoryDeleter
Public Types
using Ptr = std::unique_ptr< GeometryFactory, GeometryFactoryDeleter >
Public Member Functions
Point * createPointFromInternalCoord (const Coordinate *coord, const Geometry *exemplar) const
Geometry * toGeometry (const Envelope *envelope) const
Converts an Envelope to a Geometry.
const PrecisionModel * getPrecisionModel () const
Returns the PrecisionModel that Geometries created by this factory will be associated with.
Point * createPoint () const
Creates an EMPTY Point.
Point * createPoint (const Coordinate &coordinate) const
Creates a Point using the given Coordinate.
Point * createPoint (CoordinateSequence *coordinates) const
Creates a Point taking ownership of the given CoordinateSequence.
Point * createPoint (const CoordinateSequence &coordinates) const
Creates a Point with a deep-copy of the given CoordinateSequence.
GeometryCollection * createGeometryCollection () const
Construct an EMPTY GeometryCollection.
Geometry * createEmptyGeometry () const
Construct the EMPTY Geometry.
GeometryCollection * createGeometryCollection (std::vector< Geometry * > *newGeoms) const
Construct a GeometryCollection taking ownership of given arguments.
GeometryCollection * createGeometryCollection (const std::vector< Geometry * > &newGeoms) const
Constructs a GeometryCollection with a deep-copy of args.
MultiLineString * createMultiLineString () const
Construct an EMPTY MultiLineString.
MultiLineString * createMultiLineString (std::vector< Geometry * > *newLines) const
Construct a MultiLineString taking ownership of given arguments.
MultiLineString * createMultiLineString (const std::vector< Geometry * > &fromLines) const
Construct a MultiLineString with a deep-copy of given arguments.
MultiPolygon * createMultiPolygon () const
Construct an EMPTY MultiPolygon.
MultiPolygon * createMultiPolygon (std::vector< Geometry * > *newPolys) const
Construct a MultiPolygon taking ownership of given arguments.
MultiPolygon * createMultiPolygon (const std::vector< Geometry * > &fromPolys) const
Construct a MultiPolygon with a deep-copy of given arguments.
LinearRing * createLinearRing () const
Construct an EMPTY LinearRing.
LinearRing * createLinearRing (CoordinateSequence *newCoords) const
Construct a LinearRing taking ownership of given arguments.
std::unique_ptr< Geometry > createLinearRing (std::unique_ptr< CoordinateSequence > newCoords) const
LinearRing * createLinearRing (const CoordinateSequence &coordinates) const
Construct a LinearRing with a deep-copy of given arguments.
MultiPoint * createMultiPoint () const
Constructs an EMPTY MultiPoint.
MultiPoint * createMultiPoint (std::vector< Geometry * > *newPoints) const
Construct a MultiPoint taking ownership of given arguments.
MultiPoint * createMultiPoint (const std::vector< Geometry * > &fromPoints) const
Construct a MultiPoint with a deep-copy of given arguments.
MultiPoint * createMultiPoint (const CoordinateSequence &fromCoords) const
Construct a MultiPoint containing a Point geometry for each Coordinate in the given list.
MultiPoint * createMultiPoint (const std::vector< Coordinate > &fromCoords) const
Construct a MultiPoint containing a Point geometry for each Coordinate in the given vector.
Polygon * createPolygon () const
Construct an EMPTY Polygon.
Polygon * createPolygon (LinearRing *shell, std::vector< Geometry * > *holes) const
Construct a Polygon taking ownership of given arguments.
Polygon * createPolygon (const LinearRing &shell, const std::vector< Geometry * > &holes) const
Construct a Polygon with a deep-copy of given arguments.
LineString * createLineString () const
Construct an EMPTY LineString.
std::unique_ptr< LineString > createLineString (const LineString &ls) const
Copy a LineString.
LineString * createLineString (CoordinateSequence *coordinates) const
Construct a LineString taking ownership of given argument.
std::unique_ptr< Geometry > createLineString (std::unique_ptr< CoordinateSequence > coordinates) const
LineString * createLineString (const CoordinateSequence &coordinates) const
Construct a LineString with a deep-copy of given argument.
Geometry * buildGeometry (std::vector< Geometry * > *geoms) const
template<class T >
std::unique_ptr< Geometry > buildGeometry (T from, T toofar) const
See buildGeometry(std::vector<Geometry *>&) for semantics.
Geometry * buildGeometry (const std::vector< Geometry * > &geoms) const
This function does the same thing of the omonimouse function taking vector pointer instead of reference.
int getSRID () const
const CoordinateSequenceFactory * getCoordinateSequenceFactory () const
Returns the CoordinateSequenceFactory associated with this GeometryFactory.
Geometry * createGeometry (const Geometry *g) const
Returns a clone of given Geometry.
void destroyGeometry (Geometry *g) const
Destroy a Geometry, or release it.
void destroy ()
Request that the instance is deleted.
Static Public Member Functions
static GeometryFactory::Ptr create ()
Constructs a GeometryFactory that generates Geometries having a floating PrecisionModel and a spatial-reference ID of 0.
static GeometryFactory::Ptr create (const PrecisionModel *pm, int newSRID, CoordinateSequenceFactory *nCoordinateSequenceFactory)
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel, spatial-reference ID, and CoordinateSequence implementation.
static GeometryFactory::Ptr create (CoordinateSequenceFactory *nCoordinateSequenceFactory)
Constructs a GeometryFactory that generates Geometries having the given CoordinateSequence implementation, a double-precision floating PrecisionModel and a spatial-reference ID of 0.
static GeometryFactory::Ptr create (const PrecisionModel *pm)
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel and the default CoordinateSequence implementation.
static GeometryFactory::Ptr create (const PrecisionModel *pm, int newSRID)
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel and spatial-reference ID, and the default CoordinateSequence implementation.
static GeometryFactory::Ptr create (const GeometryFactory &gf)
Copy constructor.
static const GeometryFactory * getDefaultInstance ()
Return a pointer to the default GeometryFactory. This is a global shared object instantiated using default constructor.
Protected Member Functions
GeometryFactory ()
Constructs a GeometryFactory that generates Geometries having a floating PrecisionModel and a spatial-reference ID of 0.
GeometryFactory (const PrecisionModel *pm, int newSRID, CoordinateSequenceFactory *nCoordinateSequenceFactory)
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel, spatial-reference ID, and CoordinateSequence implementation.
GeometryFactory (CoordinateSequenceFactory *nCoordinateSequenceFactory)
Constructs a GeometryFactory that generates Geometries having the given CoordinateSequence implementation, a double-precision floating PrecisionModel and a spatial-reference ID of 0.
GeometryFactory (const PrecisionModel *pm)
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel and the default CoordinateSequence implementation.
GeometryFactory (const PrecisionModel *pm, int newSRID)
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel and spatial-reference ID, and the default CoordinateSequence implementation.
GeometryFactory (const GeometryFactory &gf)
Copy constructor.
virtual ~GeometryFactory ()
Destructor.
Private Member Functions
void addRef () const
void dropRef () const
Private Attributes
const PrecisionModel * precisionModel
int SRID
const CoordinateSequenceFactory * coordinateListFactory
int _refCount
bool _autoDestroy
Friends
class Geometry
class geos::operation::polygonize::PolygonizeGraph
Detailed Description
Supplies a set of utility methods for building Geometry objects from CoordinateSequence or other Geometry objects.
Note that the factory constructor methods do not change the input coordinates in any way. In particular, they are not rounded to the supplied PrecisionModel. It is assumed that input Coordinates meet the given precision.
Definition at line 73 of file GeometryFactory.h.
Member Typedef Documentation
using geos::geom::GeometryFactory::Ptr = std::unique_ptr<GeometryFactory, GeometryFactoryDeleter>
Definition at line 86 of file GeometryFactory.h.
Constructor & Destructor Documentation
geos::geom::GeometryFactory::GeometryFactory () protected
Constructs a GeometryFactory that generates Geometries having a floating PrecisionModel and a spatial-reference ID of 0.
Definition at line 82 of file GeometryFactory.cpp.
References precisionModel.
Referenced by create(), and getDefaultInstance().
   :
   precisionModel(new PrecisionModel()),
   SRID(0),
   coordinateListFactory(CoordinateArraySequenceFactory::instance())
   ,_refCount(0),_autoDestroy(false)
 {
 #if GEOS_DEBUG
   std::cerr << "GEOS_DEBUG: GeometryFactory["<<this<<"]::GeometryFactory()" << std::endl;
   std::cerr << "\tcreate PrecisionModel["<<precisionModel<<"]" << std::endl;
 #endif
 }
geos::geom::GeometryFactory::GeometryFactory (const PrecisionModel * pm, int newSRID, CoordinateSequenceFactory * nCoordinateSequenceFactory) protected
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel, spatial-reference ID, and CoordinateSequence implementation.
NOTES: (1) the given PrecisionModel is COPIED (2) the CoordinateSequenceFactory is NOT COPIED and must be available for the whole lifetime of the GeometryFactory
Definition at line 100 of file GeometryFactory.cpp.
References coordinateListFactory, geos::geom::CoordinateArraySequenceFactory::instance(), and precisionModel.
   :
   SRID(newSRID)
   ,_refCount(0),_autoDestroy(false)
 {
 #if GEOS_DEBUG
   std::cerr << "GEOS_DEBUG: GeometryFactory["<<this<<"]::GeometryFactory(PrecisionModel["<<pm<<"], SRID)" << std::endl;
 #endif
   if ( ! pm ) {
     precisionModel=new PrecisionModel();
   } else {
     precisionModel=new PrecisionModel(*pm);
   }
   if ( ! nCoordinateSequenceFactory ) {
     coordinateListFactory=CoordinateArraySequenceFactory::instance();
   } else {
     coordinateListFactory=nCoordinateSequenceFactory;
   }
 }
geos::geom::GeometryFactory::GeometryFactory (CoordinateSequenceFactory * nCoordinateSequenceFactory) protected
Constructs a GeometryFactory that generates Geometries having the given CoordinateSequence implementation, a double-precision floating PrecisionModel and a spatial-reference ID of 0.
Definition at line 133 of file GeometryFactory.cpp.
References coordinateListFactory, and geos::geom::CoordinateArraySequenceFactory::instance().
   :
   precisionModel(new PrecisionModel()),
   SRID(0)
   ,_refCount(0),_autoDestroy(false)
 {
 #if GEOS_DEBUG
   std::cerr << "GEOS_DEBUG: GeometryFactory["<<this<<"]::GeometryFactory(CoordinateSequenceFactory["<<nCoordinateSequenceFactory<<"])" << std::endl;
 #endif
   if ( ! nCoordinateSequenceFactory ) {
     coordinateListFactory=CoordinateArraySequenceFactory::instance();
   } else {
     coordinateListFactory=nCoordinateSequenceFactory;
   }
 }
geos::geom::GeometryFactory::GeometryFactory (const PrecisionModel * pm) protected
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel and the default CoordinateSequence implementation.
Parameters
pm the PrecisionModel to use
Definition at line 161 of file GeometryFactory.cpp.
References precisionModel.
   :
   SRID(0),
   coordinateListFactory(CoordinateArraySequenceFactory::instance())
   ,_refCount(0),_autoDestroy(false)
 {
 #if GEOS_DEBUG
   std::cerr << "GEOS_DEBUG: GeometryFactory["<<this<<"]::GeometryFactory(PrecisionModel["<<pm<<"])" << std::endl;
 #endif
   if ( ! pm ) {
     precisionModel=new PrecisionModel();
   } else {
     precisionModel=new PrecisionModel(*pm);
   }
 }
geos::geom::GeometryFactory::GeometryFactory (const PrecisionModel * pm, int newSRID) protected
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel and spatial-reference ID, and the default CoordinateSequence implementation.
Parameters
pm the PrecisionModel to use, will be copied internally
newSRID the SRID to use
Definition at line 187 of file GeometryFactory.cpp.
References precisionModel.
   :
   SRID(newSRID),
   coordinateListFactory(CoordinateArraySequenceFactory::instance())
   ,_refCount(0),_autoDestroy(false)
 {
 #if GEOS_DEBUG
   std::cerr << "GEOS_DEBUG: GeometryFactory["<<this<<"]::GeometryFactory(PrecisionModel["<<pm<<"], SRID)" << std::endl;
 #endif
   if ( ! pm ) {
     precisionModel=new PrecisionModel();
   } else {
     precisionModel=new PrecisionModel(*pm);
   }
 }
geos::geom::GeometryFactory::GeometryFactory (const GeometryFactory & gf) protected
Copy constructor.
Parameters
gf the GeometryFactory to clone from
Definition at line 213 of file GeometryFactory.cpp.
References _autoDestroy, _refCount, coordinateListFactory, precisionModel, and SRID.
 {
   assert(gf.precisionModel);
   precisionModel=new PrecisionModel(*(gf.precisionModel));
   SRID=gf.SRID;
   coordinateListFactory=gf.coordinateListFactory;
   _autoDestroy=false;
   _refCount=0;
 }
geos::geom::GeometryFactory::~GeometryFactory () protected virtual
Destructor.
Virtual on purpose: don't allow users to contsruct a GeometryFactory
Definition at line 233 of file GeometryFactory.cpp.
References precisionModel.
{
 #if GEOS_DEBUG
   std::cerr << "GEOS_DEBUG: GeometryFactory["<<this<<"]::~GeometryFactory()" << std::endl;
 #endif
   delete precisionModel;
 }
Member Function Documentation
void geos::geom::GeometryFactory::addRef () const private
Definition at line 793 of file GeometryFactory.cpp.
References _refCount.
Referenced by geos::geom::Geometry::Geometry().
 {
   ++_refCount;
 }
Geometry * geos::geom::GeometryFactory::buildGeometry (std::vector< Geometry * > * geoms) const
Build an appropriate Geometry, MultiGeometry, or GeometryCollection to contain the Geometrys in it.
For example:
If geomList contains a single Polygon, the Polygon is returned.
If geomList contains several Polygons, a MultiPolygon is returned.
If geomList contains some Polygons and some LineStrings, a GeometryCollection is returned.
If geomList is empty, an empty GeometryCollection is returned
Note that this method does not "flatten" Geometries in the input, and hence if any MultiGeometries are contained in the input a GeometryCollection containing them will be returned.
Parameters
newGeoms the Geometrys to combine
Returns
A Geometry of the "smallest", "most type-specific" class that can contain the elements of geomList.
NOTE: the returned Geometry will take ownership of the given vector AND its elements
Definition at line 654 of file GeometryFactory.cpp.
References createGeometryCollection(), createMultiLineString(), createMultiPoint(), and createMultiPolygon().
Referenced by geos::geom::util::GeometryCombiner::combine(), geos::operation::overlay::OverlayOp::computeGeometry(), geos::operation::geounion::CascadedUnion::extractByEnvelope(), geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), GEOSLineMerge_r(), geos::linearref::LinearGeometryBuilder::getGeometry(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::geom::Geometry::symDifference(), geos::geom::util::GeometryTransformer::transformGeometryCollection(), geos::geom::util::GeometryTransformer::transformMultiLineString(), geos::geom::util::GeometryTransformer::transformMultiPoint(), geos::geom::util::GeometryTransformer::transformMultiPolygon(), geos::geom::util::GeometryTransformer::transformPolygon(), geos::operation::geounion::UnaryUnionOp::Union(), and geos::geom::Geometry::Union().
 {
   string geomClass("NULL");
   bool isHeterogeneous=false;
   bool hasGeometryCollection=false;
   for (size_t i=0, n=newGeoms->size(); i<n; ++i)
   {
     Geometry* geom = (*newGeoms)[i];
     string partClass(typeid(*geom).name());
     if (geomClass=="NULL")
     {
       geomClass=partClass;
     }
     else if (geomClass!=partClass)
     {
       isHeterogeneous = true;
     }
     if ( dynamic_cast<GeometryCollection*>(geom) )
     {
       hasGeometryCollection=true;
     }
   }
   // for the empty geometry, return an empty GeometryCollection
   if (geomClass=="NULL")
   {
     // we do not need the vector anymore
     delete newGeoms;
     return createGeometryCollection();
   }
   if (isHeterogeneous || hasGeometryCollection)
   {
     return createGeometryCollection(newGeoms);
   }
   // At this point we know the collection is not hetereogenous.
   // Determine the type of the result from the first Geometry in the
   // list. This should always return a geometry, since otherwise
   // an empty collection would have already been returned
   Geometry *geom0=(*newGeoms)[0];
   bool isCollection=newGeoms->size()>1;
   if (isCollection)
   {
     if (typeid(*geom0)==typeid(Polygon)) {
       return createMultiPolygon(newGeoms);
     } else if (typeid(*geom0)==typeid(LineString)) {
       return createMultiLineString(newGeoms);
     } else if (typeid(*geom0)==typeid(LinearRing)) {
       return createMultiLineString(newGeoms);
     } else if (typeid(*geom0)==typeid(Point)) {
       return createMultiPoint(newGeoms);
     } else {
       return createGeometryCollection(newGeoms);
     }
   }
   // since this is not a collection we can delete vector
   delete newGeoms;
   return geom0;
 }
template<class T > std::unique_ptr<Geometry> geos::geom::GeometryFactory::buildGeometry (T from, T toofar) const inline
See buildGeometry(std::vector<Geometry *>&) for semantics.
Will clone the geometries accessible trough the iterator.
Template Parameters
T an iterator yelding something which casts to const Geometry*
Parameters
from start iterator
toofar end iterator
Definition at line 322 of file GeometryFactory.h.
References geos::geom::Geometry::getClassSortIndex().
   {
     bool isHeterogeneous = false;
     size_t count = 0;
     int geomClass = -1;
     for (T i=from; i != toofar; ++i)
     {
       ++count;
       const Geometry* g = *i;
       if ( geomClass < 0 ) {
         geomClass = g->getClassSortIndex();
       }
       else if ( geomClass != g->getClassSortIndex() ) {
         isHeterogeneous = true;
       }
     }
     // for the empty geometry, return an empty GeometryCollection
     if ( count == 0 ) {
       return std::unique_ptr<Geometry>( createGeometryCollection() );
     }
     // for the single geometry, return a clone
     if ( count == 1 ) {
       return std::unique_ptr<Geometry>( (*from)->clone() );
     }
     // Now we know it is a collection
     // FIXME:
     // Until we tweak all the createMulti* interfaces
     // to support taking iterators we'll have to build
     // a custom vector here.
     std::vector<Geometry*> fromGeoms;
     for (T i=from; i != toofar; ++i) {
       const Geometry* g = *i;
       fromGeoms.push_back(const_cast<Geometry*>(g));
     }
     // for an heterogeneous ...
     if ( isHeterogeneous ) {
       return std::unique_ptr<Geometry>( createGeometryCollection(fromGeoms) );
     }
     // At this point we know the collection is not hetereogenous.
     if ( dynamic_cast<const Polygon*>(*from) ) {
       return std::unique_ptr<Geometry>( createMultiPolygon(fromGeoms) );
     } else if ( dynamic_cast<const LineString*>(*from) ) {
       return std::unique_ptr<Geometry>( createMultiLineString(fromGeoms) );
     } else if ( dynamic_cast<const Point*>(*from) ) {
       return std::unique_ptr<Geometry>( createMultiPoint(fromGeoms) );
     }
     // FIXME: Why not to throw an exception? --mloskot
     assert(0); // buildGeomtry encountered an unkwnon geometry type
     return std::unique_ptr<Geometry>(); // nullptr
   }
Geometry * geos::geom::GeometryFactory::buildGeometry (const std::vector< Geometry * > & geoms) const
This function does the same thing of the omonimouse function taking vector pointer instead of reference.
The difference is that this version will copy needed data leaving ownership to the caller.
Definition at line 718 of file GeometryFactory.cpp.
References geos::geom::Geometry::clone(), createGeometryCollection(), createMultiLineString(), createMultiPoint(), and createMultiPolygon().
 {
   string geomClass("NULL");
   bool isHeterogeneous=false;
   bool isCollection=fromGeoms.size()>1;
   size_t i;
   for (i=0; i<fromGeoms.size(); i++) {
     Geometry *geom = fromGeoms[i];
     string partClass(typeid(*geom).name());
     if (geomClass=="NULL") {
       geomClass=partClass;
     } else if (geomClass!=partClass) {
       isHeterogeneous = true;
     }
   }
   // for the empty geometry, return an empty GeometryCollection
   if (geomClass=="NULL") {
     return createGeometryCollection();
   }
   if (isHeterogeneous) {
     return createGeometryCollection(fromGeoms);
   }
   // At this point we know the collection is not hetereogenous.
   // Determine the type of the result from the first Geometry in the
   // list. This should always return a geometry, since otherwise
   // an empty collection would have already been returned
   Geometry *geom0=fromGeoms[0];
   if (isCollection) {
     if (typeid(*geom0)==typeid(Polygon)) {
       return createMultiPolygon(fromGeoms);
     } else if (typeid(*geom0)==typeid(LineString)) {
       return createMultiLineString(fromGeoms);
     } else if (typeid(*geom0)==typeid(LinearRing)) {
       return createMultiLineString(fromGeoms);
     } else if (typeid(*geom0)==typeid(Point)) {
       return createMultiPoint(fromGeoms);
     }
     assert(0); // buildGeomtry encountered an unkwnon geometry type
   }
   return geom0->clone();
 }
GeometryFactory::Ptr geos::geom::GeometryFactory::create () static
Constructs a GeometryFactory that generates Geometries having a floating PrecisionModel and a spatial-reference ID of 0.
Definition at line 97 of file GeometryFactory.cpp.
References GeometryFactory().
Referenced by geos::geom::BinaryOp(), and toGeometry().
 { return GeometryFactory::Ptr(new GeometryFactory()); }
GeometryFactory::Ptr geos::geom::GeometryFactory::create (const PrecisionModel * pm, int newSRID, CoordinateSequenceFactory * nCoordinateSequenceFactory) static
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel, spatial-reference ID, and CoordinateSequence implementation.
NOTES: (1) the given PrecisionModel is COPIED (2) the CoordinateSequenceFactory is NOT COPIED and must be available for the whole lifetime of the GeometryFactory
Definition at line 124 of file GeometryFactory.cpp.
References GeometryFactory().
 {
   return GeometryFactory::Ptr(
     new GeometryFactory(pm, newSRID, nCoordinateSequenceFactory)
   );
 }
GeometryFactory::Ptr geos::geom::GeometryFactory::create (CoordinateSequenceFactory * nCoordinateSequenceFactory) static
Constructs a GeometryFactory that generates Geometries having the given CoordinateSequence implementation, a double-precision floating PrecisionModel and a spatial-reference ID of 0.
Definition at line 152 of file GeometryFactory.cpp.
References GeometryFactory().
 {
   return GeometryFactory::Ptr(
     new GeometryFactory(nCoordinateSequenceFactory)
   );
 }
GeometryFactory::Ptr geos::geom::GeometryFactory::create (const PrecisionModel * pm) static
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel and the default CoordinateSequence implementation.
Parameters
pm the PrecisionModel to use
Definition at line 179 of file GeometryFactory.cpp.
References GeometryFactory().
 {
   return GeometryFactory::Ptr(
     new GeometryFactory(pm)
   );
 }
GeometryFactory::Ptr geos::geom::GeometryFactory::create (const PrecisionModel * pm, int newSRID) static
Constructs a GeometryFactory that generates Geometries having the given PrecisionModel and spatial-reference ID, and the default CoordinateSequence implementation.
Parameters
pm the PrecisionModel to use, will be copied internally
newSRID the SRID to use
Definition at line 205 of file GeometryFactory.cpp.
References GeometryFactory().
 {
   return GeometryFactory::Ptr(
     new GeometryFactory(pm, newSRID)
   );
 }
GeometryFactory::Ptr geos::geom::GeometryFactory::create (const GeometryFactory & gf) static
Copy constructor.
Parameters
gf the GeometryFactory to clone from
Definition at line 225 of file GeometryFactory.cpp.
References GeometryFactory().
 {
   return GeometryFactory::Ptr(
     new GeometryFactory(gf)
   );
 }
Geometry * geos::geom::GeometryFactory::createEmptyGeometry () const
Construct the EMPTY Geometry.
Definition at line 389 of file GeometryFactory.cpp.
 {
   return new GeometryCollection(nullptr,this);
 }
Geometry * geos::geom::GeometryFactory::createGeometry (const Geometry * g) const
Returns a clone of given Geometry.
Definition at line 766 of file GeometryFactory.cpp.
References coordinateListFactory, and geos::geom::util::GeometryEditor::edit().
Referenced by geos::geom::BinaryOp(), and geos::precision::GeometryPrecisionReducer::fixPolygonalTopology().
 {
   // could this be cached to make this more efficient? Or maybe it isn't enough overhead to bother
   //return g->clone();
   util::GeometryEditor editor(this);
   gfCoordinateOperation coordOp(coordinateListFactory);
   Geometry *ret = editor.edit(g, &coordOp);
   return ret;
 }
GeometryCollection * geos::geom::GeometryFactory::createGeometryCollection () const
Construct an EMPTY GeometryCollection.
Definition at line 382 of file GeometryFactory.cpp.
Referenced by buildGeometry(), geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), geos::geom::util::GeometryCombiner::combine(), geos::geom::Geometry::difference(), GEOSGeom_createCollection_r(), GEOSGeom_createEmptyCollection_r(), GEOSPolygonize_full_r(), GEOSPolygonizer_getCutEdges_r(), GEOSSharedPaths_r(), geos::geom::MultiLineString::getBoundary(), geos::geom::MultiPoint::getBoundary(), geos::geom::Point::getBoundary(), geos::triangulate::quadedge::QuadEdgeSubdivision::getTriangles(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiDiagram(), geos::geom::Geometry::intersection(), geos::io::WKBReader::readGeometryCollection(), geos::geom::GeometryCollection::reverse(), geos::geom::util::GeometryTransformer::transformGeometryCollection(), and geos::operation::geounion::UnaryUnionOp::Union().
 {
   return new GeometryCollection(nullptr,this);
 }
GeometryCollection * geos::geom::GeometryFactory::createGeometryCollection (std::vector< Geometry * > * newGeoms) const
Construct a GeometryCollection taking ownership of given arguments.
Definition at line 396 of file GeometryFactory.cpp.
 {
   return new GeometryCollection(newGeoms,this);
 }
GeometryCollection * geos::geom::GeometryFactory::createGeometryCollection (const std::vector< Geometry * > & newGeoms) const
Constructs a GeometryCollection with a deep-copy of args.
Definition at line 403 of file GeometryFactory.cpp.
References geos::geom::GeometryCollection::clone().
 {
   vector<Geometry *> *newGeoms = new vector<Geometry *>(fromGeoms.size());
   for (size_t i=0; i<fromGeoms.size(); i++) {
     (*newGeoms)[i] = fromGeoms[i]->clone();
   }
   GeometryCollection *g = nullptr;
   try {
     g = new GeometryCollection(newGeoms,this);
   } catch (...) {
     for (size_t i=0; i<newGeoms->size(); i++) {
       delete (*newGeoms)[i];
     }
     delete newGeoms;
     throw;
   }
   return g;
 }
LinearRing * geos::geom::GeometryFactory::createLinearRing () const
Construct an EMPTY LinearRing.
Definition at line 460 of file GeometryFactory.cpp.
Referenced by geos::simplify::TaggedLineString::asLinearRing(), geos::geomgraph::EdgeRing::computeRing(), geos::util::GeometricShapeFactory::createArcPolygon(), geos::util::GeometricShapeFactory::createCircle(), createLinearRing(), geos::util::GeometricShapeFactory::createRectangle(), geos::geom::util::CoordinateOperation::edit(), GEOSGeom_createLinearRing_r(), geos::algorithm::MinimumDiameter::getMinimumRectangle(), geos::operation::polygonize::EdgeRing::getRingInternal(), geos::triangulate::quadedge::QuadEdgeSubdivision::getTriangles(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon(), geos::geom::Polygon::Polygon(), geos::io::WKBReader::readLinearRing(), geos::geom::LinearRing::reverse(), toGeometry(), geos::operation::intersection::Rectangle::toLinearRing(), and geos::geom::util::GeometryTransformer::transformLinearRing().
 {
   return new LinearRing(nullptr,this);
 }
LinearRing * geos::geom::GeometryFactory::createLinearRing (CoordinateSequence * newCoords) const
Construct a LinearRing taking ownership of given arguments.
Definition at line 467 of file GeometryFactory.cpp.
References createLinearRing().
 {
   return new LinearRing(newCoords,this);
 }
std::unique_ptr<Geometry> geos::geom::GeometryFactory::createLinearRing (std::unique_ptr< CoordinateSequence > newCoords) const
LinearRing * geos::geom::GeometryFactory::createLinearRing (const CoordinateSequence & coordinates) const
Construct a LinearRing with a deep-copy of given arguments.
Definition at line 481 of file GeometryFactory.cpp.
References geos::geom::CoordinateSequence::clone().
 {
   CoordinateSequence *newCoords = fromCoords.clone();
   LinearRing *g = nullptr;
   // construction failure will delete newCoords
   g = new LinearRing(newCoords, this);
   return g;
 }
LineString * geos::geom::GeometryFactory::createLineString () const
Construct an EMPTY LineString.
Definition at line 612 of file GeometryFactory.cpp.
Referenced by geos::simplify::TaggedLineString::asLineString(), geos::operation::overlay::LineBuilder::buildLines(), geos::linearref::ExtractLineByLocation::computeLine(), geos::util::GeometricShapeFactory::createArc(), createLineString(), geos::geom::util::CoordinateOperation::edit(), geos::linearref::LinearGeometryBuilder::endLine(), geos::operation::sharedpaths::SharedPathsOp::findLinearIntersections(), GEOSGeom_createEmptyLineString_r(), GEOSGeom_createLineString_r(), geos::geom::Polygon::getBoundary(), geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), geos::precision::MinimumClearance::getLine(), geos::operation::polygonize::EdgeRing::getLineString(), geos::algorithm::MinimumDiameter::getSupportingSegment(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellEdge(), geos::io::WKBReader::readLineString(), geos::operation::linemerge::LineSequencer::reverse(), geos::geom::LineString::reverse(), geos::noding::GeometryNoder::toGeometry(), geos::geom::LineSegment::toGeometry(), geos::operation::linemerge::EdgeString::toLineString(), geos::geom::util::GeometryTransformer::transformLinearRing(), and geos::geom::util::GeometryTransformer::transformLineString().
 {
   return new LineString(nullptr, this);
 }
std::unique_ptr< LineString > geos::geom::GeometryFactory::createLineString (const LineString & ls) const
Copy a LineString.
Definition at line 619 of file GeometryFactory.cpp.
 {
   return std::unique_ptr<LineString>(new LineString(ls));
 }
LineString * geos::geom::GeometryFactory::createLineString (CoordinateSequence * coordinates) const
Construct a LineString taking ownership of given argument.
Definition at line 626 of file GeometryFactory.cpp.
References createLineString().
 {
   return new LineString(newCoords, this);
 }
std::unique_ptr<Geometry> geos::geom::GeometryFactory::createLineString (std::unique_ptr< CoordinateSequence > coordinates) const
LineString * geos::geom::GeometryFactory::createLineString (const CoordinateSequence & coordinates) const
Construct a LineString with a deep-copy of given argument.
Definition at line 642 of file GeometryFactory.cpp.
References geos::geom::CoordinateSequence::clone().
 {
   CoordinateSequence *newCoords = fromCoords.clone();
   LineString *g = nullptr;
   // construction failure will delete newCoords
   g = new LineString(newCoords, this);
   return g;
 }
MultiLineString * geos::geom::GeometryFactory::createMultiLineString () const
Construct an EMPTY MultiLineString.
Definition at line 342 of file GeometryFactory.cpp.
Referenced by buildGeometry(), GEOSGeom_createCollection_r(), GEOSGeom_createEmptyCollection_r(), GEOSSharedPaths_r(), geos::geom::MultiPolygon::getBoundary(), geos::geom::Polygon::getBoundary(), geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiDiagramEdges(), geos::io::WKBReader::readMultiLineString(), geos::geom::MultiLineString::reverse(), and geos::noding::GeometryNoder::toGeometry().
 {
   return new MultiLineString(nullptr,this);
 }
MultiLineString * geos::geom::GeometryFactory::createMultiLineString (std::vector< Geometry * > * newLines) const
Construct a MultiLineString taking ownership of given arguments.
Definition at line 349 of file GeometryFactory.cpp.
 {
   return new MultiLineString(newLines,this);
 }
MultiLineString * geos::geom::GeometryFactory::createMultiLineString (const std::vector< Geometry * > & fromLines) const
Construct a MultiLineString with a deep-copy of given arguments.
Definition at line 357 of file GeometryFactory.cpp.
 {
   vector<Geometry *>*newGeoms = new vector<Geometry *>(fromLines.size());
   for (size_t i=0; i<fromLines.size(); i++)
   {
     const LineString *line = dynamic_cast<const LineString *>(fromLines[i]);
     if ( ! line ) throw geos::util::IllegalArgumentException("createMultiLineString called with a vector containing non-LineStrings");
     (*newGeoms)[i] = new LineString(*line);
   }
   MultiLineString *g = nullptr;
   try {
     g = new MultiLineString(newGeoms,this);
   } catch (...) {
     for (size_t i=0; i<newGeoms->size(); i++) {
       delete (*newGeoms)[i];
     }
     delete newGeoms;
     throw;
   }
   return g;
 }
MultiPoint * geos::geom::GeometryFactory::createMultiPoint () const
Constructs an EMPTY MultiPoint.
Definition at line 522 of file GeometryFactory.cpp.
Referenced by buildGeometry(), createMultiPoint(), GEOSGeom_createCollection_r(), GEOSGeom_createEmptyCollection_r(), GEOSGeom_extractUniquePoints_r(), geos::geom::MultiLineString::getBoundary(), geos::geom::LineString::getBoundary(), geos::io::WKBReader::readMultiPoint(), and geos::operation::geounion::PointGeometryUnion::Union().
 {
   return new MultiPoint(nullptr, this);
 }
MultiPoint * geos::geom::GeometryFactory::createMultiPoint (std::vector< Geometry * > * newPoints) const
Construct a MultiPoint taking ownership of given arguments.
Definition at line 492 of file GeometryFactory.cpp.
 {
   return new MultiPoint(newPoints,this);
 }
MultiPoint * geos::geom::GeometryFactory::createMultiPoint (const std::vector< Geometry * > & fromPoints) const
Construct a MultiPoint with a deep-copy of given arguments.
Definition at line 499 of file GeometryFactory.cpp.
References geos::geom::MultiPoint::clone().
 {
   vector<Geometry *>*newGeoms = new vector<Geometry *>(fromPoints.size());
   for (size_t i=0; i<fromPoints.size(); i++)
   {
     (*newGeoms)[i] = fromPoints[i]->clone();
   }
   MultiPoint *g = nullptr;
   try {
     g = new MultiPoint(newGeoms,this);
   } catch (...) {
     for (size_t i=0; i<newGeoms->size(); i++) {
       delete (*newGeoms)[i];
     }
     delete newGeoms;
     throw;
   }
   return g;
 }
MultiPoint * geos::geom::GeometryFactory::createMultiPoint (const CoordinateSequence & fromCoords) const
Construct a MultiPoint containing a Point geometry for each Coordinate in the given list.
Definition at line 529 of file GeometryFactory.cpp.
References createMultiPoint(), createPoint(), geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   size_t npts=fromCoords.getSize();
   vector<Geometry *> *pts=new vector<Geometry *>;
   pts->reserve(npts);
   for (size_t i=0; i<npts; ++i) {
     Point *pt=createPoint(fromCoords.getAt(i));
     pts->push_back(pt);
   }
   MultiPoint *mp = nullptr;
   try {
     mp = createMultiPoint(pts);
   } catch (...) {
     for (size_t i=0; i<npts; ++i) delete (*pts)[i];
     delete pts;
     throw;
   }
   return mp;
 }
MultiPoint * geos::geom::GeometryFactory::createMultiPoint (const std::vector< Coordinate > & fromCoords) const
Construct a MultiPoint containing a Point geometry for each Coordinate in the given vector.
Definition at line 551 of file GeometryFactory.cpp.
References createMultiPoint(), and createPoint().
 {
   size_t npts=fromCoords.size();
   vector<Geometry *> *pts=new vector<Geometry *>;
   pts->reserve(npts);
   for (size_t i=0; i<npts; ++i) {
     Point *pt=createPoint(fromCoords[i]);
     pts->push_back(pt);
   }
   MultiPoint *mp = nullptr;
   try {
     mp = createMultiPoint(pts);
   } catch (...) {
     for (size_t i=0; i<npts; ++i) delete (*pts)[i];
     delete pts;
     throw;
   }
   return mp;
 }
MultiPolygon * geos::geom::GeometryFactory::createMultiPolygon () const
Construct an EMPTY MultiPolygon.
Definition at line 424 of file GeometryFactory.cpp.
Referenced by buildGeometry(), GEOSGeom_createCollection_r(), GEOSGeom_createEmptyCollection_r(), geos::io::WKBReader::readMultiPolygon(), and geos::geom::MultiPolygon::reverse().
 {
   return new MultiPolygon(nullptr,this);
 }
MultiPolygon * geos::geom::GeometryFactory::createMultiPolygon (std::vector< Geometry * > * newPolys) const
Construct a MultiPolygon taking ownership of given arguments.
Definition at line 431 of file GeometryFactory.cpp.
 {
   return new MultiPolygon(newPolys,this);
 }
MultiPolygon * geos::geom::GeometryFactory::createMultiPolygon (const std::vector< Geometry * > & fromPolys) const
Construct a MultiPolygon with a deep-copy of given arguments.
Definition at line 438 of file GeometryFactory.cpp.
References geos::geom::MultiPolygon::clone().
 {
   vector<Geometry *>*newGeoms = new vector<Geometry *>(fromPolys.size());
   for (size_t i=0; i<fromPolys.size(); i++)
   {
     (*newGeoms)[i] = fromPolys[i]->clone();
   }
   MultiPolygon *g = nullptr;
   try {
     g = new MultiPolygon(newGeoms,this);
   } catch (...) {
     for (size_t i=0; i<newGeoms->size(); i++) {
       delete (*newGeoms)[i];
     }
     delete newGeoms;
     throw;
   }
   return g;
 }
Point * geos::geom::GeometryFactory::createPoint () const
Creates an EMPTY Point.
Definition at line 297 of file GeometryFactory.cpp.
Referenced by createMultiPoint(), createPoint(), createPointFromInternalCoord(), geos::geom::util::CoordinateOperation::edit(), GEOSGeom_createEmptyPoint_r(), GEOSGeom_createPoint_r(), GEOSGeom_extractUniquePoints_r(), GEOSGetCentroid_r(), GEOSInterpolate_r(), GEOSisValidDetail_r(), GEOSPointOnSurface_r(), geos::geom::Geometry::getCentroid(), geos::operation::overlay::validate::FuzzyPointLocator::getLocation(), geos::geom::LineString::getPointN(), geos::io::WKBReader::readPoint(), toGeometry(), geos::geom::util::GeometryTransformer::transformPoint(), and geos::operation::geounion::PointGeometryUnion::Union().
 {
   return new Point(nullptr, this);
 }
Point * geos::geom::GeometryFactory::createPoint (const Coordinate & coordinate) const
Creates a Point using the given Coordinate.
Definition at line 304 of file GeometryFactory.cpp.
References coordinateListFactory, geos::geom::CoordinateSequenceFactory::create(), createPoint(), geos::geom::Coordinate::isNull(), and geos::geom::Coordinate::z.
 {
   if (coordinate.isNull()) {
     return createPoint();
   } else {
     std::size_t dim = ISNAN(coordinate.z) ? 2 : 3;
     CoordinateSequence *cl = coordinateListFactory->create(new vector<Coordinate>(1, coordinate), dim);
     //cl->setAt(coordinate, 0);
     Point *ret = createPoint(cl);
     return ret;
   }
 }
Point * geos::geom::GeometryFactory::createPoint (CoordinateSequence * coordinates) const
Creates a Point taking ownership of the given CoordinateSequence.
Definition at line 319 of file GeometryFactory.cpp.
 {
   return new Point(newCoords,this);
 }
Point * geos::geom::GeometryFactory::createPoint (const CoordinateSequence & coordinates) const
Creates a Point with a deep-copy of the given CoordinateSequence.
Definition at line 326 of file GeometryFactory.cpp.
References geos::geom::CoordinateSequence::clone().
 {
   CoordinateSequence *newCoords = fromCoords.clone();
   Point *g = nullptr;
   try {
     g = new Point(newCoords,this);
   } catch (...) {
     delete newCoords;
     throw;
   }
   return g;
 }
Point * geos::geom::GeometryFactory::createPointFromInternalCoord (const Coordinate * coord, const Geometry * exemplar) const
Definition at line 242 of file GeometryFactory.cpp.
References createPoint(), geos::geom::Geometry::getFactory(), geos::geom::Geometry::getPrecisionModel(), and geos::geom::PrecisionModel::makePrecise().
Referenced by geos::geom::Geometry::getInteriorPoint().
 {
   assert(coord);
   Coordinate newcoord = *coord;
   exemplar->getPrecisionModel()->makePrecise(&newcoord);
   return exemplar->getFactory()->createPoint(newcoord);
 }
Polygon * geos::geom::GeometryFactory::createPolygon () const
Construct an EMPTY Polygon.
Definition at line 573 of file GeometryFactory.cpp.
Referenced by geos::util::GeometricShapeFactory::createArcPolygon(), geos::util::GeometricShapeFactory::createCircle(), geos::util::GeometricShapeFactory::createRectangle(), GEOSGeom_createEmptyPolygon_r(), GEOSGeom_createPolygon_r(), geos::algorithm::MinimumDiameter::getMinimumRectangle(), geos::operation::polygonize::EdgeRing::getPolygon(), geos::triangulate::quadedge::QuadEdgeSubdivision::getTriangles(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon(), geos::io::WKBReader::readPolygon(), geos::geom::Polygon::reverse(), toGeometry(), geos::geomgraph::EdgeRing::toPolygon(), geos::operation::intersection::Rectangle::toPolygon(), and geos::geom::util::GeometryTransformer::transformPolygon().
 {
   return new Polygon(nullptr, nullptr, this);
 }
Polygon * geos::geom::GeometryFactory::createPolygon (LinearRing * shell, std::vector< Geometry * > * holes) const
Construct a Polygon taking ownership of given arguments.
Definition at line 580 of file GeometryFactory.cpp.
 {
   return new Polygon(shell, holes, this);
 }
Polygon * geos::geom::GeometryFactory::createPolygon (const LinearRing & shell, const std::vector< Geometry * > & holes) const
Construct a Polygon with a deep-copy of given arguments.
Definition at line 588 of file GeometryFactory.cpp.
References geos::geom::LinearRing::clone().
 {
   LinearRing *newRing = dynamic_cast<LinearRing *>(shell.clone());
   vector<Geometry *>*newHoles = new vector<Geometry *>(holes.size());
   for (size_t i=0; i<holes.size(); i++)
   {
     (*newHoles)[i] = holes[i]->clone();
   }
   Polygon *g = nullptr;
   try {
     g = new Polygon(newRing, newHoles, this);
   } catch (...) {
     delete newRing;
     for (size_t i=0; i<holes.size(); i++)
       delete (*newHoles)[i];
     delete newHoles;
     throw;
   }
   return g;
 }
void geos::geom::GeometryFactory::destroy ()
Request that the instance is deleted.
It will really be deleted only after last child Geometry is deleted. Do not use the instance anymore after calling this function (unless you're a live child!).
Definition at line 809 of file GeometryFactory.cpp.
References _autoDestroy, and _refCount.
Referenced by geos::geom::GeometryFactory::GeometryFactoryDeleter::operator()().
 {
   assert(!_autoDestroy); // don't call me twice !
   _autoDestroy = true;
   if ( ! _refCount ) delete this;
 }
void geos::geom::GeometryFactory::destroyGeometry (Geometry * g) const
Destroy a Geometry, or release it.
Definition at line 778 of file GeometryFactory.cpp.
 {
   delete g;
 }
void geos::geom::GeometryFactory::dropRef () const private
Definition at line 800 of file GeometryFactory.cpp.
References _autoDestroy, and _refCount.
Referenced by geos::geom::Geometry::~Geometry().
 {
   if ( ! --_refCount )
   {
     if ( _autoDestroy ) delete this;
   }
 }
INLINE const CoordinateSequenceFactory * geos::geom::GeometryFactory::getCoordinateSequenceFactory () const
Returns the CoordinateSequenceFactory associated with this GeometryFactory.
Definition at line 39 of file GeometryFactory.inl.
References coordinateListFactory.
Referenced by geos::precision::MinimumClearance::compute(), geos::util::GeometricShapeFactory::createArc(), geos::util::GeometricShapeFactory::createArcPolygon(), geos::util::GeometricShapeFactory::createCircle(), geos::geom::util::GeometryTransformer::createCoordinateSequence(), geos::precision::GeometryPrecisionReducer::createFactory(), geos::util::GeometricShapeFactory::createRectangle(), geos::precision::PrecisionReducerCoordinateOperation::edit(), GEOSCoordSeq_create_r(), geos::operation::linemerge::EdgeString::getCoordinates(), geos::operation::polygonize::EdgeRing::getCoordinates(), geos::geom::Polygon::getCoordinates(), geos::triangulate::quadedge::QuadEdgeSubdivision::getEdges(), geos::simplify::TaggedLineString::getResultCoordinates(), geos::algorithm::MinimumDiameter::getSupportingSegment(), geos::geom::Point::Point(), geos::io::WKBReader::readCoordinateSequence(), geos::operation::intersection::RectangleIntersection::RectangleIntersection(), geos::operation::intersection::Rectangle::toLinearRing(), and geos::simplify::DPTransformer::transformCoordinates().
 {
   return coordinateListFactory;
 }
const GeometryFactory * geos::geom::GeometryFactory::getDefaultInstance () static
Return a pointer to the default GeometryFactory. This is a global shared object instantiated using default constructor.
Definition at line 785 of file GeometryFactory.cpp.
References GeometryFactory().
Referenced by geos::geom::Geometry::Geometry().
 {
   static GeometryFactory* defInstance = new GeometryFactory();
   return defInstance;
 }
const PrecisionModel * geos::geom::GeometryFactory::getPrecisionModel () const
Returns the PrecisionModel that Geometries created by this factory will be associated with.
Definition at line 290 of file GeometryFactory.cpp.
References precisionModel.
Referenced by geos::geom::BinaryOp(), geos::noding::GeometryNoder::getNoder(), geos::geom::Geometry::getPrecisionModel(), and geos::io::WKBReader::readCoordinate().
 {
   return precisionModel;
 }
INLINE int geos::geom::GeometryFactory::getSRID () const
Definition at line 33 of file GeometryFactory.inl.
References INLINE, and SRID.
Referenced by geos::precision::GeometryPrecisionReducer::createFactory(), and geos::geom::Geometry::Geometry().
 {
   return SRID;
 }
Geometry * geos::geom::GeometryFactory::toGeometry (const Envelope * envelope) const
Converts an Envelope to a Geometry.
Returned Geometry can be a Point, a Polygon or an EMPTY geom.
Definition at line 254 of file GeometryFactory.cpp.
References geos::geom::CoordinateSequence::add(), create(), createLinearRing(), createPoint(), createPolygon(), geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), geos::geom::CoordinateArraySequenceFactory::instance(), geos::geom::Envelope::isNull(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), geos::triangulate::VoronoiDiagramBuilder::getDiagramEdges(), and geos::geom::Geometry::getEnvelope().
 {
   Coordinate coord;
   if (envelope->isNull()) {
     return createPoint();
   }
   if (envelope->getMinX()==envelope->getMaxX() && envelope->getMinY()==envelope->getMaxY()) {
     coord.x = envelope->getMinX();
     coord.y = envelope->getMinY();
     return createPoint(coord);
   }
   CoordinateSequence *cl=CoordinateArraySequenceFactory::instance()->
         create((size_t) 0, 2);
   coord.x = envelope->getMinX();
   coord.y = envelope->getMinY();
   cl->add(coord);
   coord.x = envelope->getMaxX();
   coord.y = envelope->getMinY();
   cl->add(coord);
   coord.x = envelope->getMaxX();
   coord.y = envelope->getMaxY();
   cl->add(coord);
   coord.x = envelope->getMinX();
   coord.y = envelope->getMaxY();
   cl->add(coord);
   coord.x = envelope->getMinX();
   coord.y = envelope->getMinY();
   cl->add(coord);
   Polygon *p = createPolygon(createLinearRing(cl), nullptr);
   return p;
 }
Friends And Related Function Documentation
friend class Geometry friend
Definition at line 485 of file GeometryFactory.h.
friend class geos::operation::polygonize::PolygonizeGraph friend
Definition at line 486 of file GeometryFactory.h.
Member Data Documentation
bool geos::geom::GeometryFactory::_autoDestroy private
Definition at line 483 of file GeometryFactory.h.
Referenced by destroy(), dropRef(), and GeometryFactory().
int geos::geom::GeometryFactory::_refCount mutable private
Definition at line 482 of file GeometryFactory.h.
Referenced by addRef(), destroy(), dropRef(), and GeometryFactory().
const CoordinateSequenceFactory* geos::geom::GeometryFactory::coordinateListFactory private
Definition at line 480 of file GeometryFactory.h.
Referenced by createGeometry(), createPoint(), GeometryFactory(), and getCoordinateSequenceFactory().
const PrecisionModel* geos::geom::GeometryFactory::precisionModel private
Definition at line 478 of file GeometryFactory.h.
Referenced by GeometryFactory(), getPrecisionModel(), and ~GeometryFactory().
int geos::geom::GeometryFactory::SRID private
Definition at line 479 of file GeometryFactory.h.
Referenced by GeometryFactory(), and getSRID().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/GeometryFactory.h
/home/vicky/potree/geos/vicky/src/geom/GeometryFactory.cpp
/home/vicky/potree/geos/vicky/include/geos/geom/GeometryFactory.inl