GEOS: geos::operation::distance::DistanceOp Class Reference
geos::operation::distance::DistanceOp Class Reference
Find two points on two Geometrys which lie within a given distance, or else are the nearest points on the geometries (in which case this also provides the distance between the geometries).
#include <DistanceOp.h>
Public Member Functions
DistanceOp (const geom::Geometry *g0, const geom::Geometry *g1)
DistanceOp (const geom::Geometry &g0, const geom::Geometry &g1)
Constructs a DistanceOp that computes the distance and nearest points between the two specified geometries.
DistanceOp (const geom::Geometry &g0, const geom::Geometry &g1, double terminateDistance)
Constructs a DistanceOp that computes the distance and nearest points between the two specified geometries.
~DistanceOp ()
double distance ()
geom::CoordinateSequence * closestPoints ()
geom::CoordinateSequence * nearestPoints ()
Static Public Member Functions
static double distance (const geom::Geometry &g0, const geom::Geometry &g1)
Compute the distance between the nearest points of two geometries.
static double distance (const geom::Geometry *g0, const geom::Geometry *g1)
static bool isWithinDistance (const geom::Geometry &g0, const geom::Geometry &g1, double distance)
Test whether two geometries lie within a given distance of each other.
static geom::CoordinateSequence * nearestPoints (const geom::Geometry *g0, const geom::Geometry *g1)
static geom::CoordinateSequence * closestPoints (const geom::Geometry *g0, const geom::Geometry *g1)
Private Member Functions
std::vector< GeometryLocation * > * nearestLocations ()
void updateMinDistance (std::vector< GeometryLocation * > &locGeom, bool flip)
void computeMinDistance ()
void computeContainmentDistance ()
void computeInside (std::vector< GeometryLocation * > *locs, const std::vector< const geom::Polygon * > &polys, std::vector< GeometryLocation * > *locPtPoly)
void computeInside (GeometryLocation *ptLoc, const geom::Polygon *poly, std::vector< GeometryLocation * > *locPtPoly)
void computeFacetDistance ()
void computeMinDistanceLines (const std::vector< const geom::LineString * > &lines0, const std::vector< const geom::LineString * > &lines1, std::vector< GeometryLocation * > &locGeom)
void computeMinDistancePoints (const std::vector< const geom::Point * > &points0, const std::vector< const geom::Point * > &points1, std::vector< GeometryLocation * > &locGeom)
void computeMinDistanceLinesPoints (const std::vector< const geom::LineString * > &lines0, const std::vector< const geom::Point * > &points1, std::vector< GeometryLocation * > &locGeom)
void computeMinDistance (const geom::LineString *line0, const geom::LineString *line1, std::vector< GeometryLocation * > &locGeom)
void computeMinDistance (const geom::LineString *line, const geom::Point *pt, std::vector< GeometryLocation * > &locGeom)
Private Attributes
std::vector< geom::Geometry const * > geom
double terminateDistance
algorithm::PointLocator ptLocator
std::vector< GeometryLocation * > * minDistanceLocation
double minDistance
std::vector< geom::Coordinate * > newCoords
Detailed Description
Find two points on two Geometrys which lie within a given distance, or else are the nearest points on the geometries (in which case this also provides the distance between the geometries).
The distance computation also finds a pair of points in the input geometries which have the minimum distance between them. If a point lies in the interior of a line segment, the coordinate computed is a close approximation to the exact point.
The algorithms used are straightforward O(n^2) comparisons. This worst-case performance could be improved on by using Voronoi techniques or spatial indexes.
Definition at line 74 of file DistanceOp.h.
Constructor & Destructor Documentation
geos::operation::distance::DistanceOp::DistanceOp (const geom::Geometry * g0, const geom::Geometry * g1)
Deprecated:
use the one taking references
Definition at line 89 of file DistanceOp.cpp.
References geom.
                                                             :
   geom(2),
   terminateDistance(0.0),
   minDistanceLocation(nullptr),
   minDistance(DoubleMax)
 {
   geom[0] = g0;
   geom[1] = g1;
 }
geos::operation::distance::DistanceOp::DistanceOp (const geom::Geometry & g0, const geom::Geometry & g1)
Constructs a DistanceOp that computes the distance and nearest points between the two specified geometries.
Parameters
g0 a Geometry
g1 a Geometry
Definition at line 99 of file DistanceOp.cpp.
References geom.
                                                             :
   geom(2),
   terminateDistance(0.0),
   minDistanceLocation(nullptr),
   minDistance(DoubleMax)
 {
   geom[0] = &g0;
   geom[1] = &g1;
 }
geos::operation::distance::DistanceOp::DistanceOp (const geom::Geometry & g0, const geom::Geometry & g1, double terminateDistance)
Constructs a DistanceOp that computes the distance and nearest points between the two specified geometries.
Parameters
g0 a Geometry
g1 a Geometry
terminateDistance the distance on which to terminate the search
Definition at line 109 of file DistanceOp.cpp.
References geom.
   :
   geom(2),
   terminateDistance(tdist),
   minDistanceLocation(nullptr),
   minDistance(DoubleMax)
 {
   geom[0] = &g0;
   geom[1] = &g1;
 }
geos::operation::distance::DistanceOp::~DistanceOp ()
Definition at line 120 of file DistanceOp.cpp.
References minDistanceLocation, and newCoords.
 {
   size_t i;
   for (i=0; i<newCoords.size(); i++) delete newCoords[i];
   if ( minDistanceLocation )
   {
     for (i=0; i<minDistanceLocation->size(); i++)
     {
       delete (*minDistanceLocation)[i];
     }
     delete minDistanceLocation;
   }
 }
Member Function Documentation
CoordinateSequence * geos::operation::distance::DistanceOp::closestPoints (const geom::Geometry * g0, const geom::Geometry * g1) static
Compute the the closest points of two geometries.
The points are presented in the same order as the input Geometries.
Parameters
g0 a Geometry
g1 another Geometry
Returns
the closest points in the geometries, ownership to caller. A NULL return means one of the geometries is empty.
Deprecated:
renamed to nearestPoints
Definition at line 75 of file DistanceOp.cpp.
References nearestPoints().
 {
   DistanceOp distOp(g0,g1);
   return distOp.nearestPoints();
 }
CoordinateSequence * geos::operation::distance::DistanceOp::closestPoints ()
Report the coordinates of the closest points in the input geometries. The points are presented in the same order as the input Geometries.
Returns
a pair of Coordinates of the closest points as a newly allocated object (ownership to caller)
Deprecated:
renamed to nearestPoints
Definition at line 153 of file DistanceOp.cpp.
References nearestPoints().
 {
   return nearestPoints();
 }
void geos::operation::distance::DistanceOp::computeContainmentDistance () private
Definition at line 251 of file DistanceOp.cpp.
References computeInside(), geom, geos::operation::distance::ConnectedElementLocationFilter::getLocations(), minDistance, minDistanceLocation, and terminateDistance.
Referenced by computeMinDistance().
 {
   using geom::util::PolygonExtracter;
   Polygon::ConstVect polys1;
   PolygonExtracter::getPolygons(*(geom[1]), polys1);
 #if GEOS_DEBUG
   std::cerr << "PolygonExtracter found " << polys1.size() << " polygons in geometry 2" << std::endl;
 #endif
   // NOTE:
   // Expected to fill minDistanceLocation items
   // if minDistance <= terminateDistance
   vector<GeometryLocation*> *locPtPoly = new vector<GeometryLocation*>(2);
   // test if either geometry has a vertex inside the other
   if ( ! polys1.empty() )
   {
     vector<GeometryLocation*> *insideLocs0 =
       ConnectedElementLocationFilter::getLocations(geom[0]);
     computeInside(insideLocs0, polys1, locPtPoly);
     if (minDistance <= terminateDistance) {
       assert( (*locPtPoly)[0] );
       assert( (*locPtPoly)[1] );
       (*minDistanceLocation)[0] = (*locPtPoly)[0];
       (*minDistanceLocation)[1] = (*locPtPoly)[1];
       delete locPtPoly;
       for (size_t i=0; i<insideLocs0->size(); i++)
       {
         GeometryLocation *l = (*insideLocs0)[i];
         if ( l != (*minDistanceLocation)[0] &&
           l != (*minDistanceLocation)[1] )
         {
           delete l;
         }
       }
       delete insideLocs0;
       return;
     }
     for (size_t i=0; i<insideLocs0->size(); i++)
       delete (*insideLocs0)[i];
     delete insideLocs0;
   }
   Polygon::ConstVect polys0;
   PolygonExtracter::getPolygons(*(geom[0]), polys0);
 #if GEOS_DEBUG
   std::cerr << "PolygonExtracter found " << polys0.size() << " polygons in geometry 1" << std::endl;
 #endif
   if ( ! polys0.empty() )
   {
     vector<GeometryLocation*> *insideLocs1 = ConnectedElementLocationFilter::getLocations(geom[1]);
     computeInside(insideLocs1, polys0, locPtPoly);
     if (minDistance <= terminateDistance) {
 // flip locations, since we are testing geom 1 VS geom 0
       assert( (*locPtPoly)[0] );
       assert( (*locPtPoly)[1] );
       (*minDistanceLocation)[0] = (*locPtPoly)[1];
       (*minDistanceLocation)[1] = (*locPtPoly)[0];
       delete locPtPoly;
       for (size_t i=0; i<insideLocs1->size(); i++)
       {
         GeometryLocation *l = (*insideLocs1)[i];
         if ( l != (*minDistanceLocation)[0] &&
           l != (*minDistanceLocation)[1] )
         {
           delete l;
         }
       }
       delete insideLocs1;
       return;
     }
     for (size_t i=0; i<insideLocs1->size(); i++)
       delete (*insideLocs1)[i];
     delete insideLocs1;
   }
   delete locPtPoly;
   // If minDistance <= terminateDistance we must have
   // set minDistanceLocations to some non-null item
   assert( minDistance > terminateDistance ||
           ( (*minDistanceLocation)[0] && (*minDistanceLocation)[1] ) );
 }
void geos::operation::distance::DistanceOp::computeFacetDistance () private
Computes distance between facets (lines and points) of input geometries.
Geometries are not wholely inside, so compute distance from lines and points of one to lines and points of the other
Definition at line 380 of file DistanceOp.cpp.
References computeMinDistanceLines(), computeMinDistanceLinesPoints(), computeMinDistancePoints(), geom, minDistance, terminateDistance, and updateMinDistance().
Referenced by computeMinDistance().
 {
   using geom::util::LinearComponentExtracter;
   using geom::util::PointExtracter;
   vector<GeometryLocation*> locGeom(2);
   LineString::ConstVect lines0;
   LineString::ConstVect lines1;
   LinearComponentExtracter::getLines(*(geom[0]), lines0);
   LinearComponentExtracter::getLines(*(geom[1]), lines1);
 #if GEOS_DEBUG
   std::cerr << "LinearComponentExtracter found "
             << lines0.size() << " lines in geometry 1 and "
             << lines1.size() << " lines in geometry 2 "
             << std::endl;
 #endif
   Point::ConstVect pts0;
   Point::ConstVect pts1;
   PointExtracter::getPoints(*(geom[0]), pts0);
   PointExtracter::getPoints(*(geom[1]), pts1);
 #if GEOS_DEBUG
   std::cerr << "PointExtracter found "
             << pts0.size() << " points in geometry 1 and "
             << pts1.size() << " points in geometry 2 "
             << std::endl;
 #endif
   // exit whenever minDistance goes LE than terminateDistance
   computeMinDistanceLines(lines0, lines1, locGeom);
   updateMinDistance(locGeom, false);
   if (minDistance <= terminateDistance) {
 #if GEOS_DEBUG
     std::cerr << "Early termination after line-line distance" << std::endl;
 #endif
     return;
   };
   locGeom[0]=nullptr;
   locGeom[1]=nullptr;
   computeMinDistanceLinesPoints(lines0, pts1, locGeom);
   updateMinDistance(locGeom, false);
   if (minDistance <= terminateDistance) {
 #if GEOS_DEBUG
     std::cerr << "Early termination after lines0-points1 distance" << std::endl;
 #endif
     return;
   };
   locGeom[0]=nullptr;
   locGeom[1]=nullptr;
   computeMinDistanceLinesPoints(lines1, pts0, locGeom);
   updateMinDistance(locGeom, true);
   if (minDistance <= terminateDistance){
 #if GEOS_DEBUG
     std::cerr << "Early termination after lines1-points0 distance" << std::endl;
 #endif
     return;
   };
   locGeom[0]=nullptr;
   locGeom[1]=nullptr;
   computeMinDistancePoints(pts0, pts1, locGeom);
   updateMinDistance(locGeom, false);
 #if GEOS_DEBUG
   std::cerr << "termination after pts-pts distance" << std::endl;
 #endif
 }
void geos::operation::distance::DistanceOp::computeInside (std::vector< GeometryLocation * > * locs, const std::vector< const geom::Polygon * > & polys, std::vector< GeometryLocation * > * locPtPoly) private
Referenced by computeContainmentDistance().
void geos::operation::distance::DistanceOp::computeInside (GeometryLocation * ptLoc, const geom::Polygon * poly, std::vector< GeometryLocation * > * locPtPoly) private
Definition at line 361 of file DistanceOp.cpp.
References geos::geom::Location::EXTERIOR, geos::operation::distance::GeometryLocation::getCoordinate(), geos::algorithm::PointLocator::locate(), minDistance, and ptLocator.
 {
   const Coordinate &pt=ptLoc->getCoordinate();
   // if pt is not in exterior, distance to geom is 0
   if (Location::EXTERIOR!=ptLocator.locate(pt, static_cast<const Geometry *>(poly)))
   {
     minDistance = 0.0;
     (*locPtPoly)[0] = ptLoc;
     GeometryLocation *locPoly = new GeometryLocation(poly, pt);
     (*locPtPoly)[1] = locPoly;
     return;
   }
 }
void geos::operation::distance::DistanceOp::computeMinDistance () private
Definition at line 224 of file DistanceOp.cpp.
References computeContainmentDistance(), computeFacetDistance(), geom, minDistance, minDistanceLocation, and terminateDistance.
Referenced by computeMinDistanceLines(), computeMinDistanceLinesPoints(), distance(), nearestLocations(), and nearestPoints().
 {
   // only compute once!
   if (minDistanceLocation) return;
 #if GEOS_DEBUG
   std::cerr << "---Start: " << geom[0]->toString() << " - " << geom[1]->toString() << std::endl;
 #endif
   minDistanceLocation = new vector<GeometryLocation*>(2);
   computeContainmentDistance();
   if (minDistance <= terminateDistance)
   {
     return;
   }
   computeFacetDistance();
 #if GEOS_DEBUG
   std::cerr << "---End " << std::endl;
 #endif
 }
void geos::operation::distance::DistanceOp::computeMinDistance (const geom::LineString * line0, const geom::LineString * line1, std::vector< GeometryLocation * > & locGeom) private
Definition at line 535 of file DistanceOp.cpp.
References geos::geom::Envelope::distance(), geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::CoordinateSequence::getSize(), minDistance, newCoords, and terminateDistance.
 {
   using geos::algorithm::CGAlgorithms;
   const Envelope *env0=line0->getEnvelopeInternal();
   const Envelope *env1=line1->getEnvelopeInternal();
   if (env0->distance(env1)>minDistance) {
     return;
   }
   const CoordinateSequence *coord0=line0->getCoordinatesRO();
   const CoordinateSequence *coord1=line1->getCoordinatesRO();
   size_t npts0=coord0->getSize();
   size_t npts1=coord1->getSize();
   // brute force approach!
   for(size_t i=0; i<npts0-1; ++i)
   {
     for(size_t j=0; j<npts1-1; ++j)
     {
       double dist=CGAlgorithms::distanceLineLine(coord0->getAt(i),coord0->getAt(i+1),
         coord1->getAt(j),coord1->getAt(j+1));
       if (dist < minDistance) {
         minDistance = dist;
         LineSegment seg0(coord0->getAt(i), coord0->getAt(i + 1));
         LineSegment seg1(coord1->getAt(j), coord1->getAt(j + 1));
         CoordinateSequence* closestPt = seg0.closestPoints(seg1);
         Coordinate *c1 = new Coordinate(closestPt->getAt(0));
         Coordinate *c2 = new Coordinate(closestPt->getAt(1));
         newCoords.push_back(c1);
         newCoords.push_back(c2);
         delete closestPt;
         delete locGeom[0];
         locGeom[0] = new GeometryLocation(line0, static_cast<int>(i), *c1);
         delete locGeom[1];
         locGeom[1] = new GeometryLocation(line1, static_cast<int>(j), *c2);
       }
       if (minDistance<=terminateDistance) return;
     }
   }
 }
void geos::operation::distance::DistanceOp::computeMinDistance (const geom::LineString * line, const geom::Point * pt, std::vector< GeometryLocation * > & locGeom) private
Definition at line 583 of file DistanceOp.cpp.
References geos::geom::Envelope::distance(), geos::geom::CoordinateSequence::getAt(), geos::geom::Point::getCoordinate(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::CoordinateSequence::getSize(), minDistance, newCoords, and terminateDistance.
 {
   using geos::algorithm::CGAlgorithms;
   const Envelope *env0=line->getEnvelopeInternal();
   const Envelope *env1=pt->getEnvelopeInternal();
   if (env0->distance(env1)>minDistance) {
     return;
   }
   const CoordinateSequence *coord0=line->getCoordinatesRO();
   Coordinate *coord=new Coordinate(*(pt->getCoordinate()));
   newCoords.push_back(coord);
   // brute force approach!
   size_t npts0=coord0->getSize();
   for(size_t i=0; i<npts0-1; ++i)
   {
     double dist=CGAlgorithms::distancePointLine(*coord,coord0->getAt(i),coord0->getAt(i+1));
           if (dist < minDistance) {
               minDistance = dist;
       LineSegment seg(coord0->getAt(i), coord0->getAt(i + 1));
       Coordinate segClosestPoint;
       seg.closestPoint(*coord, segClosestPoint);
       delete locGeom[0];
       locGeom[0] = new GeometryLocation(line, static_cast<int>(i), segClosestPoint);
       delete locGeom[1];
       locGeom[1] = new GeometryLocation(pt, 0, *coord);
           }
     if (minDistance<=terminateDistance) return;
   }
 }
void geos::operation::distance::DistanceOp::computeMinDistanceLines (const std::vector< const geom::LineString * > & lines0, const std::vector< const geom::LineString * > & lines1, std::vector< GeometryLocation * > & locGeom) private
Definition at line 460 of file DistanceOp.cpp.
References computeMinDistance(), minDistance, and terminateDistance.
Referenced by computeFacetDistance().
 {
   for (size_t i=0, ni=lines0.size(); i<ni; ++i)
   {
     const LineString *line0=lines0[i];
     for (size_t j=0, nj=lines1.size(); j<nj; ++j) {
       const LineString *line1=lines1[j];
       computeMinDistance(line0, line1, locGeom);
       if (minDistance<=terminateDistance) return;
     }
   }
 }
void geos::operation::distance::DistanceOp::computeMinDistanceLinesPoints (const std::vector< const geom::LineString * > & lines0, const std::vector< const geom::Point * > & points1, std::vector< GeometryLocation * > & locGeom) private
Definition at line 516 of file DistanceOp.cpp.
References computeMinDistance(), minDistance, and terminateDistance.
Referenced by computeFacetDistance().
 {
   for (size_t i=0;i<lines.size();i++)
   {
     const LineString *line=lines[i];
     for (size_t j=0;j<points.size();j++)
     {
       const Point *pt=points[j];
       computeMinDistance(line,pt,locGeom);
       if (minDistance<=terminateDistance) return;
     }
   }
 }
void geos::operation::distance::DistanceOp::computeMinDistancePoints (const std::vector< const geom::Point * > & points0, const std::vector< const geom::Point * > & points1, std::vector< GeometryLocation * > & locGeom) private
Definition at line 478 of file DistanceOp.cpp.
References geos::geom::Coordinate::distance(), geos::geom::Point::getCoordinate(), minDistance, terminateDistance, and geos::geom::Geometry::toString().
Referenced by computeFacetDistance().
 {
   for (size_t i=0, ni=points0.size(); i<ni; ++i)
   {
     const Point *pt0 = points0[i];
     for (size_t j=0, nj=points1.size(); j<nj; ++j)
     {
       const Point *pt1 = points1[j];
       double dist = pt0->getCoordinate()->distance(*(pt1->getCoordinate()));
 #if GEOS_DEBUG
   std::cerr << "Distance "
             << pt0->toString() << " - "
             << pt1->toString() << ": "
             << dist << ", minDistance: " << minDistance
             << std::endl;
 #endif
       if (dist < minDistance)
       {
         minDistance = dist;
         // this is wrong - need to determine closest points on both segments!!!
         delete locGeom[0];
         locGeom[0] = new GeometryLocation(pt0, 0, *(pt0->getCoordinate()));
         delete locGeom[1];
         locGeom[1] = new GeometryLocation(pt1, 0, *(pt1->getCoordinate()));
       }
       if (minDistance<=terminateDistance) return;
     }
   }
 }
double geos::operation::distance::DistanceOp::distance (const geom::Geometry & g0, const geom::Geometry & g1) static
Compute the distance between the nearest points of two geometries.
Parameters
g0 a Geometry
g1 another Geometry
Returns
the distance between the geometries
0 if either input geometry is empty
Exceptions
IllegalArgumentException if either input geometry is null
Definition at line 67 of file DistanceOp.cpp.
References distance().
Referenced by distance(), and isWithinDistance().
 {
   DistanceOp distOp(g0,g1);
   return distOp.distance();
 }
double geos::operation::distance::DistanceOp::distance (const geom::Geometry * g0, const geom::Geometry * g1) static
Deprecated:
, use the version taking references
Definition at line 59 of file DistanceOp.cpp.
References distance().
 {
   DistanceOp distOp(g0,g1);
   return distOp.distance();
 }
double geos::operation::distance::DistanceOp::distance ()
Report the distance between the closest points on the input geometries.
Returns
the distance between the geometries
Definition at line 140 of file DistanceOp.cpp.
References computeMinDistance(), geom, and minDistance.
Referenced by isWithinDistance().
 {
   using geos::util::IllegalArgumentException;
   if ( geom[0] == nullptr || geom[1] == nullptr )
     throw IllegalArgumentException("null geometries are not supported");
   if ( geom[0]->isEmpty() || geom[1]->isEmpty() ) return 0.0;
   computeMinDistance();
   return minDistance;
 }
bool geos::operation::distance::DistanceOp::isWithinDistance (const geom::Geometry & g0, const geom::Geometry & g1, double distance) static
Test whether two geometries lie within a given distance of each other.
Parameters
g0 a Geometry
g1 another Geometry
distance the distance to test
Returns
true if g0.distance(g1) <= distance
Definition at line 620 of file DistanceOp.cpp.
References distance().
 {
   DistanceOp distOp(g0, g1, distance);
   return distOp.distance() <= distance;
 }
vector< GeometryLocation * > * geos::operation::distance::DistanceOp::nearestLocations () private
Report the locations of the closest points in the input geometries. The locations are presented in the same order as the input Geometries.
Returns
a pair of GeometryLocations for the closest points. Ownership of returned object is left to this instance and it's reference will be alive for the whole lifetime of it.
NOTE: this is public in JTS, but we aim at API reduction here...
Definition at line 191 of file DistanceOp.cpp.
References computeMinDistance(), and minDistanceLocation.
{
   computeMinDistance();
   return minDistanceLocation;
 }
CoordinateSequence * geos::operation::distance::DistanceOp::nearestPoints (const geom::Geometry * g0, const geom::Geometry * g1) static
Compute the the nearest points of two geometries.
The points are presented in the same order as the input Geometries.
Parameters
g0 a Geometry
g1 another Geometry
Returns
the nearest points in the geometries, ownership to caller. A NULL return means one of the geometries is empty.
Definition at line 83 of file DistanceOp.cpp.
References nearestPoints().
Referenced by closestPoints(), and nearestPoints().
 {
   DistanceOp distOp(g0,g1);
   return distOp.nearestPoints();
 }
CoordinateSequence * geos::operation::distance::DistanceOp::nearestPoints ()
Report the coordinates of the nearest points in the input geometries. The points are presented in the same order as the input Geometries.
Returns
a pair of Coordinates of the nearest points as a newly allocated object (ownership to caller)
Definition at line 161 of file DistanceOp.cpp.
References geos::geom::CoordinateSequence::add(), computeMinDistance(), geos::operation::distance::GeometryLocation::getCoordinate(), and minDistanceLocation.
Referenced by closestPoints(), and GEOSNearestPoints_r().
 {
   // lazily creates minDistanceLocation
   computeMinDistance();
   assert(nullptr != minDistanceLocation);
   std::vector<GeometryLocation*>& locs = *minDistanceLocation;
   // Empty input geometries result in this behaviour
   if ( locs[0] == nullptr || locs[1] == nullptr )
   {
     // either both or none are set..
     assert(locs[0] == nullptr && locs[1] == nullptr);
     return nullptr;
   }
   GeometryLocation* loc0 = locs[0];
   GeometryLocation* loc1 = locs[1];
   const Coordinate& c0 = loc0->getCoordinate();
   const Coordinate& c1 = loc1->getCoordinate();
   CoordinateSequence* nearestPts = new CoordinateArraySequence();
   nearestPts->add(c0);
   nearestPts->add(c1);
   return nearestPts;
 }
void geos::operation::distance::DistanceOp::updateMinDistance (std::vector< GeometryLocation * > & locGeom, bool flip) private
Definition at line 197 of file DistanceOp.cpp.
References minDistanceLocation.
Referenced by computeFacetDistance().
 {
   assert(minDistanceLocation);
   // if not set then don't update
   if (locGeom[0]==nullptr)
   {
 #if GEOS_DEBUG
 std::cerr << "updateMinDistance called with loc[0] == null and loc[1] == " << locGeom[1] << std::endl;
 #endif
     assert(locGeom[1] == nullptr);
     return;
   }
   delete (*minDistanceLocation)[0];
   delete (*minDistanceLocation)[1];
   if (flip) {
     (*minDistanceLocation)[0]=locGeom[1];
     (*minDistanceLocation)[1]=locGeom[0];
   } else {
     (*minDistanceLocation)[0]=locGeom[0];
     (*minDistanceLocation)[1]=locGeom[1];
   }
 }
Member Data Documentation
std::vector<geom::Geometry const*> geos::operation::distance::DistanceOp::geom private
Definition at line 213 of file DistanceOp.h.
Referenced by computeContainmentDistance(), computeFacetDistance(), computeMinDistance(), distance(), and DistanceOp().
double geos::operation::distance::DistanceOp::minDistance private
Definition at line 220 of file DistanceOp.h.
Referenced by computeContainmentDistance(), computeFacetDistance(), computeInside(), computeMinDistance(), computeMinDistanceLines(), computeMinDistanceLinesPoints(), computeMinDistancePoints(), and distance().
std::vector<GeometryLocation*>* geos::operation::distance::DistanceOp::minDistanceLocation private
Definition at line 219 of file DistanceOp.h.
Referenced by computeContainmentDistance(), computeMinDistance(), nearestLocations(), nearestPoints(), updateMinDistance(), and ~DistanceOp().
std::vector<geom::Coordinate *> geos::operation::distance::DistanceOp::newCoords private
Definition at line 223 of file DistanceOp.h.
Referenced by computeMinDistance(), and ~DistanceOp().
algorithm::PointLocator geos::operation::distance::DistanceOp::ptLocator private
Definition at line 217 of file DistanceOp.h.
Referenced by computeInside().
double geos::operation::distance::DistanceOp::terminateDistance private
Definition at line 214 of file DistanceOp.h.
Referenced by computeContainmentDistance(), computeFacetDistance(), computeMinDistance(), computeMinDistanceLines(), computeMinDistanceLinesPoints(), and computeMinDistancePoints().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/distance/DistanceOp.h
/home/vicky/potree/geos/vicky/src/operation/distance/DistanceOp.cpp