GEOS: geos::triangulate::VoronoiDiagramBuilder Class Reference
geos::triangulate::VoronoiDiagramBuilder Class Reference
#include <VoronoiDiagramBuilder.h>
Public Member Functions
VoronoiDiagramBuilder ()
~VoronoiDiagramBuilder ()
void setSites (const geom::Geometry &geom)
void setSites (const geom::CoordinateSequence &coords)
void setClipEnvelope (const geom::Envelope *clipEnv)
void setTolerance (double tolerance)
std::unique_ptr< quadedge::QuadEdgeSubdivision > getSubdivision ()
std::unique_ptr< geom::GeometryCollection > getDiagram (const geom::GeometryFactory &geomFact)
std::unique_ptr< geom::Geometry > getDiagramEdges (const geom::GeometryFactory &geomFact)
Private Member Functions
void create ()
Static Private Member Functions
static std::unique_ptr< geom::GeometryCollection > clipGeometryCollection (const geom::GeometryCollection &geom, const geom::Envelope &clipEnv)
Private Attributes
std::unique_ptr< geom::CoordinateSequence > siteCoords
double tolerance
std::unique_ptr< quadedge::QuadEdgeSubdivision > subdiv
const geom::Envelope * clipEnv
geom::Envelope diagramEnv
Detailed Description
A utility class which creates Voronoi Diagrams from collections of points. The diagram is returned as a GeometryCollection of Polygons, clipped to the larger of a supplied envelope or to an envelope determined by the input sites.
Author
Martin Davis
Definition at line 46 of file VoronoiDiagramBuilder.h.
Constructor & Destructor Documentation
geos::triangulate::VoronoiDiagramBuilder::VoronoiDiagramBuilder ()
Creates a new Voronoi diagram builder.
Definition at line 40 of file VoronoiDiagramBuilder.cpp.
                                              :
   tolerance(0.0), clipEnv(nullptr)
 {
 }
geos::triangulate::VoronoiDiagramBuilder::~VoronoiDiagramBuilder ()
Definition at line 45 of file VoronoiDiagramBuilder.cpp.
 {
 }
Member Function Documentation
std::unique_ptr< geom::GeometryCollection > geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection (const geom::GeometryCollection & geom, const geom::Envelope & clipEnv) static private
Definition at line 123 of file VoronoiDiagramBuilder.cpp.
References geos::geom::Geometry::clone(), geos::geom::Envelope::contains(), geos::geom::GeometryFactory::createGeometryCollection(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Geometry::getFactory(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::geom::Envelope::intersects(), geos::geom::Geometry::setUserData(), and geos::geom::GeometryFactory::toGeometry().
Referenced by getDiagram().
 {
   std::unique_ptr<geom::Geometry> clipPoly ( geom.getFactory()->toGeometry(&clipEnv) );
   std::unique_ptr< std::vector<Geometry*> >clipped(new std::vector<Geometry*>);
   for(std::size_t i=0 ; i < geom.getNumGeometries() ; i++)
   {
     const Geometry* g = geom.getGeometryN(i);
     std::unique_ptr<Geometry> result;
     // don't clip unless necessary
     if(clipEnv.contains(g->getEnvelopeInternal()))
     {
       result.reset( g->clone() );
       // TODO: check if userData is correctly cloned here?
     }
     else if(clipEnv.intersects(g->getEnvelopeInternal()))
     {
       result.reset( clipPoly->intersection(g) );
       result->setUserData(((Geometry*)g)->getUserData()); // TODO: needed ?
     }
     if(result.get() && !result->isEmpty() )
     {
       clipped->push_back(result.release());
     }
   }
   return std::unique_ptr<GeometryCollection>(geom.getFactory()->createGeometryCollection(clipped.release()));
 }
void geos::triangulate::VoronoiDiagramBuilder::create () private
Definition at line 75 of file VoronoiDiagramBuilder.cpp.
References clipEnv, diagramEnv, geos::triangulate::DelaunayTriangulationBuilder::envelope(), geos::geom::Envelope::expandBy(), geos::geom::Envelope::expandToInclude(), geos::geom::Envelope::getHeight(), geos::geom::Envelope::getWidth(), geos::triangulate::IncrementalDelaunayTriangulator::insertSites(), siteCoords, subdiv, tolerance, and geos::triangulate::DelaunayTriangulationBuilder::toVertices().
Referenced by getDiagram(), getDiagramEdges(), and getSubdivision().
 {
   if( subdiv.get() ) return;
   diagramEnv = DelaunayTriangulationBuilder::envelope(*siteCoords);
   //adding buffer around the final envelope
   double expandBy = std::max(diagramEnv.getWidth() , diagramEnv.getHeight());
   diagramEnv.expandBy(expandBy);
   if(clipEnv)
     diagramEnv.expandToInclude(clipEnv);
   std::unique_ptr<IncrementalDelaunayTriangulator::VertexList> vertices (
     DelaunayTriangulationBuilder::toVertices(*siteCoords)
   );
   subdiv.reset( new quadedge::QuadEdgeSubdivision(diagramEnv,tolerance) );
   IncrementalDelaunayTriangulator triangulator(subdiv.get());
   triangulator.insertSites(*vertices);
 }
std::unique_ptr< geom::GeometryCollection > geos::triangulate::VoronoiDiagramBuilder::getDiagram (const geom::GeometryFactory & geomFact)
Gets the faces of the computed diagram as a GeometryCollection of Polygons, clipped as specified.
Parameters
geomFact the geometry factory to use to create the output
Returns
the faces of the diagram
Definition at line 104 of file VoronoiDiagramBuilder.cpp.
References clipGeometryCollection(), create(), diagramEnv, and subdiv.
 {
   create();
   std::unique_ptr<geom::GeometryCollection> polys = subdiv->getVoronoiDiagram(geomFact);
   return clipGeometryCollection(*polys,diagramEnv);
 }
std::unique_ptr< geom::Geometry > geos::triangulate::VoronoiDiagramBuilder::getDiagramEdges (const geom::GeometryFactory & geomFact)
Gets the faces of the computed diagram as a GeometryCollection of LineStrings, clipped as specified.
Parameters
geomFact the geometry factory to use to create the output
Returns
the faces of the diagram
Definition at line 112 of file VoronoiDiagramBuilder.cpp.
References create(), diagramEnv, subdiv, and geos::geom::GeometryFactory::toGeometry().
 {
   create();
   std::unique_ptr<geom::MultiLineString> edges = subdiv->getVoronoiDiagramEdges(geomFact);
   if ( edges->isEmpty() ) return std::unique_ptr<Geometry>(edges.release());
   std::unique_ptr<geom::Geometry> clipPoly ( geomFact.toGeometry(&diagramEnv) );
   std::unique_ptr<Geometry> clipped( clipPoly->intersection(edges.get()) );
   return clipped;
 }
std::unique_ptr< quadedge::QuadEdgeSubdivision > geos::triangulate::VoronoiDiagramBuilder::getSubdivision ()
Gets the QuadEdgeSubdivision which models the computed diagram.
Returns
the subdivision containing the triangulation
Definition at line 96 of file VoronoiDiagramBuilder.cpp.
References create(), and subdiv.
 {
   create();
   // NOTE: Apparently, this is 'source' method giving up the object resource.
   return std::move(subdiv);
 }
void geos::triangulate::VoronoiDiagramBuilder::setClipEnvelope (const geom::Envelope * clipEnv)
Sets the envelope to clip the diagram to. The diagram will be clipped to the larger of this envelope or an envelope surrounding the sites.
Parameters
clipEnv the clip envelope; must be kept alive by caller until done with this instance; set to 0 for no clipping.
Definition at line 63 of file VoronoiDiagramBuilder.cpp.
References clipEnv.
 {
   clipEnv = nClipEnv;
 }
void geos::triangulate::VoronoiDiagramBuilder::setSites (const geom::Geometry & geom)
Sets the sites (point or vertices) which will be diagrammed. All vertices of the given geometry will be used as sites.
Parameters
geom the geometry from which the sites will be extracted.
Definition at line 50 of file VoronoiDiagramBuilder.cpp.
References geos::triangulate::DelaunayTriangulationBuilder::extractUniqueCoordinates(), and siteCoords.
Referenced by GEOSVoronoiDiagram_r().
 {
   siteCoords.reset( DelaunayTriangulationBuilder::extractUniqueCoordinates(geom) );
 }
void geos::triangulate::VoronoiDiagramBuilder::setSites (const geom::CoordinateSequence & coords)
Sets the sites (point or vertices) which will be diagrammed from a collection of Coordinates.
Parameters
coords a collection of Coordinates.
Definition at line 56 of file VoronoiDiagramBuilder.cpp.
References geos::geom::CoordinateSequence::clone(), siteCoords, and geos::triangulate::DelaunayTriangulationBuilder::unique().
 {
   siteCoords.reset( coords.clone() );
   DelaunayTriangulationBuilder::unique(*siteCoords);
 }
void geos::triangulate::VoronoiDiagramBuilder::setTolerance (double tolerance)
Sets the snapping tolerance which will be used to improved the robustness of the triangulation computation. A tolerance of 0.0 specifies that no snapping will take place.
Parameters
tolerance the tolerance distance to use
Definition at line 69 of file VoronoiDiagramBuilder.cpp.
References tolerance.
 {
   tolerance = nTolerance;
 }
Member Data Documentation
const geom::Envelope* geos::triangulate::VoronoiDiagramBuilder::clipEnv private
Definition at line 122 of file VoronoiDiagramBuilder.h.
Referenced by create(), and setClipEnvelope().
geom::Envelope geos::triangulate::VoronoiDiagramBuilder::diagramEnv private
Definition at line 123 of file VoronoiDiagramBuilder.h.
Referenced by create(), getDiagram(), and getDiagramEdges().
std::unique_ptr<geom::CoordinateSequence> geos::triangulate::VoronoiDiagramBuilder::siteCoords private
Definition at line 119 of file VoronoiDiagramBuilder.h.
Referenced by create(), and setSites().
std::unique_ptr<quadedge::QuadEdgeSubdivision> geos::triangulate::VoronoiDiagramBuilder::subdiv private
Definition at line 121 of file VoronoiDiagramBuilder.h.
Referenced by create(), getDiagram(), getDiagramEdges(), and getSubdivision().
double geos::triangulate::VoronoiDiagramBuilder::tolerance private
Definition at line 120 of file VoronoiDiagramBuilder.h.
Referenced by create(), and setTolerance().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/triangulate/VoronoiDiagramBuilder.h
/home/vicky/potree/geos/vicky/src/triangulate/VoronoiDiagramBuilder.cpp