GEOS: geos::algorithm::MCPointInRing Class Reference
geos::algorithm::MCPointInRing Class Reference
#include <MCPointInRing.h>
Classes
class MCSelecter
Public Member Functions
MCPointInRing (const geom::LinearRing *newRing)
~MCPointInRing () override
bool isInside (const geom::Coordinate &pt) override
void testLineSegment (const geom::Coordinate &p, const geom::LineSegment &seg)
Private Member Functions
void buildIndex ()
void testMonotoneChain (geom::Envelope *rayEnv, MCSelecter *mcSelecter, index::chain::MonotoneChain *mc)
Private Attributes
const geom::LinearRing * ring
index::bintree::Interval interval
geom::CoordinateSequence * pts
index::bintree::Bintree * tree
int crossings
Detailed Description
Definition at line 50 of file MCPointInRing.h.
Constructor & Destructor Documentation
geos::algorithm::MCPointInRing::MCPointInRing (const geom::LinearRing * newRing)
Definition at line 52 of file MCPointInRing.cpp.
References buildIndex().
   :
   ring(newRing),
   interval(),
   pts(nullptr),
   tree(nullptr),
   crossings(0)
 {
   buildIndex();
 }
geos::algorithm::MCPointInRing::~MCPointInRing () override
Definition at line 63 of file MCPointInRing.cpp.
References pts, and tree.
 {
   delete tree;
   delete pts;
 }
Member Function Documentation
void geos::algorithm::MCPointInRing::buildIndex () private
Definition at line 70 of file MCPointInRing.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::index::chain::MonotoneChain::getEnvelope(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinY(), geos::index::bintree::Bintree::insert(), interval, geos::index::bintree::Interval::max, geos::index::bintree::Interval::min, pts, ring, and tree.
Referenced by MCPointInRing().
 {
   //using namespace geos::index;
 //  Envelope *env=ring->getEnvelopeInternal();
   tree=new bintree::Bintree();
   pts=CoordinateSequence::removeRepeatedPoints(ring->getCoordinatesRO());
   // NOTE: we take ownership of mcList and it's elements
   vector<chain::MonotoneChain*> *mcList =
     chain::MonotoneChainBuilder::getChains(pts);
   for(size_t i=0, n=mcList->size(); i<n; ++i)
   {
     chain::MonotoneChain *mc=(*mcList)[i];
     const Envelope& mcEnv = mc->getEnvelope();
     interval.min = mcEnv.getMinY();
     interval.max = mcEnv.getMaxY();
     // TODO: is 'mc' ownership transferred here ? (see below)
     //       by documentation SpatialIndex does NOT take
     //       ownership of the items, so unless we query it
     //       all later we've a leak problem here..
     //       Need a focused testcase.
     //
     tree->insert(&interval, mc);
   }
   // TODO: mcList elements ownership went to tree or what ?
   delete mcList;
 }
bool geos::algorithm::MCPointInRing::isInside (const geom::Coordinate & pt) override virtual
Implements geos::algorithm::PointInRing.
Definition at line 104 of file MCPointInRing.cpp.
References crossings, interval, geos::index::bintree::Interval::max, geos::index::bintree::Interval::min, geos::index::bintree::Bintree::query(), testMonotoneChain(), tree, and geos::geom::Coordinate::y.
Referenced by geos::operation::valid::IsValidOp::checkHolesInShell().
 {
   crossings=0;
   // test all segments intersected by ray from pt in positive x direction
   Envelope *rayEnv=new Envelope(DoubleNegInfinity,DoubleInfinity,pt.y,pt.y);
   interval.min=pt.y;
   interval.max=pt.y;
   vector<void*> *segs=tree->query(&interval);
   //System.out.println("query size=" + segs.size());
   MCSelecter *mcSelecter=new MCSelecter(pt,this);
   for(int i=0;i<(int)segs->size();i++) {
     chain::MonotoneChain *mc=(chain::MonotoneChain*) (*segs)[i];
     testMonotoneChain(rayEnv,mcSelecter,mc);
   }
   /*
   *  p is inside if number of crossings is odd.
   */
 //  for(int i=0;i<(int)segs->size();i++) {
 //    delete (chain::MonotoneChain*) (*segs)[i];
 //  }
   delete segs;
   delete rayEnv;
   delete mcSelecter;
   if((crossings%2)==1) {
     return true;
   }
   return false;
 }
void geos::algorithm::MCPointInRing::testLineSegment (const geom::Coordinate & p, const geom::LineSegment & seg)
Definition at line 143 of file MCPointInRing.cpp.
References crossings, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, geos::algorithm::RobustDeterminant::signOfDet2x2(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::algorithm::MCPointInRing::MCSelecter::select().
 {
   double xInt;  // x intersection of segment with ray
   double x1;    // translated coordinates
   double y1;
   double x2;
   double y2;
   /*
    * Test if segment crosses ray from test point in positive x direction.
    */
   const Coordinate& p1 = seg.p0;
   const Coordinate& p2 = seg.p1;
   x1 = p1.x - p.x;
   y1 = p1.y - p.y;
   x2 = p2.x - p.x;
   y2 = p2.y - p.y;
   if (((y1>0)&&(y2<=0)) || ((y2>0)&&(y1<=0)))
   {
     /*
      *  segment straddles x axis, so compute intersection.
      */
     xInt=RobustDeterminant::signOfDet2x2(x1,y1,x2,y2)/(y2-y1);
     /*
      *  crosses ray if strictly positive intersection.
      */
     if (0.0<xInt) {
       crossings++;
     }
   }
 }
void geos::algorithm::MCPointInRing::testMonotoneChain (geom::Envelope * rayEnv, MCSelecter * mcSelecter, index::chain::MonotoneChain * mc) private
Definition at line 135 of file MCPointInRing.cpp.
References geos::index::chain::MonotoneChain::select().
Referenced by isInside().
 {
   mc->select(*rayEnv, *mcSelecter);
 }
Member Data Documentation
int geos::algorithm::MCPointInRing::crossings private
Definition at line 74 of file MCPointInRing.h.
Referenced by isInside(), and testLineSegment().
index::bintree::Interval geos::algorithm::MCPointInRing::interval private
Definition at line 71 of file MCPointInRing.h.
Referenced by buildIndex(), and isInside().
geom::CoordinateSequence* geos::algorithm::MCPointInRing::pts private
Definition at line 72 of file MCPointInRing.h.
Referenced by buildIndex(), and ~MCPointInRing().
const geom::LinearRing* geos::algorithm::MCPointInRing::ring private
Definition at line 70 of file MCPointInRing.h.
Referenced by buildIndex().
index::bintree::Bintree* geos::algorithm::MCPointInRing::tree private
Definition at line 73 of file MCPointInRing.h.
Referenced by buildIndex(), isInside(), and ~MCPointInRing().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/MCPointInRing.h
/home/vicky/potree/geos/vicky/src/algorithm/MCPointInRing.cpp