GEOS: geos::geom::CoordinateSequenceFactory Class Reference
geos::geom::CoordinateSequenceFactory Class Reference abstract
A factory to create concrete instances of CoordinateSequences.
#include <CoordinateSequenceFactory.h>
Public Member Functions
virtual CoordinateSequence * create () const =0
Returns an empty CoordinateSequence, the dimensions will be autodetected when it is populated.
virtual CoordinateSequence * create (std::vector< Coordinate > *coordinates, std::size_t dimension=0) const =0
Returns a CoordinateSequence based on the given array.
virtual CoordinateSequence * create (std::size_t size, std::size_t dimension=0) const =0
Creates a CoordinateSequence of the specified size and dimension.
virtual CoordinateSequence * create (const CoordinateSequence &coordSeq) const =0
Creates a CoordinateSequence which is a copy of the given one.
virtual ~CoordinateSequenceFactory ()
Detailed Description
A factory to create concrete instances of CoordinateSequences.
Used to configure GeometryFactorys to provide specific kinds of CoordinateSequences.
Definition at line 47 of file CoordinateSequenceFactory.h.
Constructor & Destructor Documentation
geos::geom::CoordinateSequenceFactory::~CoordinateSequenceFactory () virtual
Definition at line 24 of file CoordinateSequenceFactory.cpp.
 {}
Member Function Documentation
virtual CoordinateSequence* geos::geom::CoordinateSequenceFactory::create () const pure virtual
Returns an empty CoordinateSequence, the dimensions will be autodetected when it is populated.
Implemented in geos::geom::CoordinateArraySequenceFactory.
Referenced by geos::precision::MinimumClearance::compute(), geos::util::GeometricShapeFactory::createArc(), geos::util::GeometricShapeFactory::createArcPolygon(), geos::util::GeometricShapeFactory::createCircle(), geos::geom::util::GeometryTransformer::createCoordinateSequence(), geos::geom::GeometryFactory::createPoint(), geos::util::GeometricShapeFactory::createRectangle(), geos::precision::PrecisionReducerCoordinateOperation::edit(), GEOSCoordSeq_create_r(), geos::operation::linemerge::EdgeString::getCoordinates(), geos::operation::polygonize::EdgeRing::getCoordinates(), geos::geom::Polygon::getCoordinates(), geos::geom::GeometryCollection::getCoordinates(), geos::algorithm::MinimumDiameter::getMinimumRectangle(), geos::simplify::TaggedLineString::getResultCoordinates(), geos::algorithm::MinimumDiameter::getSupportingSegment(), geos::geom::Point::Point(), geos::io::WKBReader::readCoordinateSequence(), geos::io::WKTReader::readMultiPointText(), geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), geos::operation::overlay::snap::SnapTransformer::snapLine(), geos::algorithm::ConvexHull::toCoordinateSequence(), geos::operation::intersection::Rectangle::toLinearRing(), and geos::simplify::DPTransformer::transformCoordinates().
virtual CoordinateSequence* geos::geom::CoordinateSequenceFactory::create (std::vector< Coordinate > * coordinates, std::size_t dimension = 0) const pure virtual
Returns a CoordinateSequence based on the given array.
Whether the array is copied or simply referenced is implementation-dependent. For this reason caller does give up ownership of it. Implementations that will not copy it will need take care of deleting it.
This method must handle null arguments by creating an empty sequence.
Parameters
coordinates the coordinates
dimension 0, 2 or 3 with 0 indicating unknown at this time.
Implemented in geos::geom::CoordinateArraySequenceFactory.
virtual CoordinateSequence* geos::geom::CoordinateSequenceFactory::create (std::size_t size, std::size_t dimension = 0) const pure virtual
Creates a CoordinateSequence of the specified size and dimension.
For this to be useful, the CoordinateSequence implementation must be mutable.
Parameters
size the number of coordinates in the sequence
dimension the dimension of the coordinates in the sequence (0=unknown, 2, or 3 - ignored if not user specifiable)
Implemented in geos::geom::CoordinateArraySequenceFactory.
virtual CoordinateSequence* geos::geom::CoordinateSequenceFactory::create (const CoordinateSequence & coordSeq) const pure virtual
Creates a CoordinateSequence which is a copy of the given one.
This method must handle null arguments by creating an empty sequence.
Parameters
coordSeq the coordinate sequence to copy
Implemented in geos::geom::CoordinateArraySequenceFactory.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/CoordinateSequenceFactory.h
/home/vicky/potree/geos/vicky/src/geom/CoordinateSequenceFactory.cpp