GEOS: geos::algorithm::InteriorPointPoint Class Reference
geos::algorithm::InteriorPointPoint Class Reference
Computes a point in the interior of an point geometry.
#include <geos/geosAlgorithm.h>
Public Member Functions
InteriorPointPoint (const geom::Geometry *g)
~InteriorPointPoint ()
bool getInteriorPoint (geom::Coordinate &ret) const
Private Member Functions
void add (const geom::Geometry *geom)
void add (const geom::Coordinate *point)
Private Attributes
bool hasInterior
geom::Coordinate centroid
double minDistance
geom::Coordinate interiorPoint
Detailed Description
Computes a point in the interior of an point geometry.
Algorithm:
Find a point which is closest to the centroid of the geometry.
Definition at line 41 of file InteriorPointPoint.h.
Constructor & Destructor Documentation
geos::algorithm::InteriorPointPoint::InteriorPointPoint (const geom::Geometry * g)
Definition at line 34 of file InteriorPointPoint.cpp.
References geos::geom::Geometry::getCentroid().
 {
   minDistance=DoubleMax;
   if ( ! g->getCentroid(centroid) ) {
     hasInterior=false;
   } else {
     hasInterior=true;
     add(g);
   }
 }
geos::algorithm::InteriorPointPoint::~InteriorPointPoint () inline
Definition at line 65 of file InteriorPointPoint.h.
 {}
Member Function Documentation
void geos::algorithm::InteriorPointPoint::add (const geom::Geometry * geom) private
Tests the point(s) defined by a Geometry for the best inside point. If a Geometry is not of dimension 0 it is not tested.
Parameters
geom the geometry to add
Definition at line 47 of file InteriorPointPoint.cpp.
References geos::geom::Point::getCoordinate(), geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   const Point *po = dynamic_cast<const Point*>(geom);
   if ( po ) {
     add(po->getCoordinate());
     return;
   }
   const GeometryCollection *gc = dynamic_cast<const GeometryCollection*>(geom);
   if ( gc )
   {
     for(std::size_t i=0, n=gc->getNumGeometries(); i<n; i++) {
       add(gc->getGeometryN(i));
     }
   }
 }
void geos::algorithm::InteriorPointPoint::add (const geom::Coordinate * point) private
Definition at line 66 of file InteriorPointPoint.cpp.
References geos::geom::Coordinate::distance().
 {
   assert ( point ); // we wouldn't been called if this was an empty geom
   double dist=point->distance(centroid);
   if (dist<minDistance) {
     interiorPoint=*point;
     minDistance=dist;
   }
 }
bool geos::algorithm::InteriorPointPoint::getInteriorPoint (geom::Coordinate & ret) const
Definition at line 78 of file InteriorPointPoint.cpp.
Referenced by geos::geom::Geometry::getInteriorPoint().
 {
   if ( ! hasInterior ) return false;
   ret=interiorPoint;
   return true;
 }
Member Data Documentation
geom::Coordinate geos::algorithm::InteriorPointPoint::centroid private
Definition at line 46 of file InteriorPointPoint.h.
bool geos::algorithm::InteriorPointPoint::hasInterior private
Definition at line 44 of file InteriorPointPoint.h.
geom::Coordinate geos::algorithm::InteriorPointPoint::interiorPoint private
Definition at line 50 of file InteriorPointPoint.h.
double geos::algorithm::InteriorPointPoint::minDistance private
Definition at line 48 of file InteriorPointPoint.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/InteriorPointPoint.h
/home/vicky/potree/geos/vicky/src/algorithm/InteriorPointPoint.cpp