GEOS: geos::geom::CoordinateFilter Class Reference
geos::geom::CoordinateFilter Class Reference
#include <CoordinateFilter.h>
Public Member Functions
virtual ~CoordinateFilter ()
virtual void filter_rw (Coordinate *) const
virtual void filter_ro (const Coordinate *)
Detailed Description
Geometry classes support the concept of applying a coordinate filter to every coordinate in the Geometry.
A coordinate filter can either record information about each coordinate or change the coordinate in some way. Coordinate filters implement the interface CoordinateFilter. (CoordinateFilter is an example of the Gang-of-Four Visitor pattern). Coordinate filters can be used to implement such things as coordinate transformations, centroid and envelope computation, and many other functions.
TODO: provide geom::CoordinateInspector and geom::CoordinateMutator instead of having the two versions of filter_rw and filter_ro
Definition at line 43 of file CoordinateFilter.h.
Constructor & Destructor Documentation
virtual geos::geom::CoordinateFilter::~CoordinateFilter () inline virtual
Definition at line 45 of file CoordinateFilter.h.
 {}
Member Function Documentation
virtual void geos::geom::CoordinateFilter::filter_ro (const Coordinate *) inline virtual
Performs an operation with coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented in geos::operation::overlay::PointCoveredByAny, geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter, geos::noding::ScaledNoder::ReScaler, geos::precision::CommonCoordinateFilter, geos::operation::overlay::ElevationMatrixFilter, geos::util::UniqueCoordinateArrayFilter, geos::precision::Translater, and geos::util::CoordinateArrayFilter.
Definition at line 59 of file CoordinateFilter.h.
Referenced by geos::geom::CoordinateArraySequence::apply_ro(), and geos::geom::Point::apply_ro().
 { assert(0); }
virtual void geos::geom::CoordinateFilter::filter_rw (Coordinate *) const inline virtual
Performs an operation on coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented in geos::noding::ScaledNoder::ReScaler, geos::noding::ScaledNoder::Scaler, geos::precision::CommonCoordinateFilter, geos::operation::overlay::ElevationMatrixFilter, and geos::precision::Translater.
Definition at line 52 of file CoordinateFilter.h.
Referenced by geos::geom::CoordinateArraySequence::apply_rw(), and geos::geom::Point::apply_rw().
 { assert(0); }
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/geom/CoordinateFilter.h