GEOS: geos::index::ItemVisitor Class Reference
geos::index::ItemVisitor Class Reference abstract
A visitor for items in an index.
#include <ItemVisitor.h>
Public Member Functions
virtual void visitItem (void *)=0
virtual ~ItemVisitor ()
Detailed Description
A visitor for items in an index.
Last port: index/ItemVisitor.java rev. 1.2 (JTS-1.7)
Definition at line 29 of file ItemVisitor.h.
Constructor & Destructor Documentation
virtual geos::index::ItemVisitor::~ItemVisitor () inline virtual
Definition at line 33 of file ItemVisitor.h.
 {}
Member Function Documentation
virtual void geos::index::ItemVisitor::visitItem (void *) pure virtual
Implemented in CAPI_ItemVisitor, geos::noding::snapround::MCIndexPointSnapperVisitor, geos::algorithm::locate::IndexedPointInAreaLocator::SegmentVisitor, geos::simplify::LineSegmentVisitor, and geos::operation::distance::Deleter.
Referenced by geos::index::strtree::AbstractSTRtree::iterate(), geos::index::intervalrtree::IntervalRTreeLeafNode::query(), geos::index::strtree::AbstractSTRtree::query(), and geos::index::quadtree::NodeBase::visitItems().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/index/ItemVisitor.h