GEOS: geos::geomgraph::GeometryGraph Class Reference
geos::geomgraph::GeometryGraph Class Reference
#include <GeometryGraph.h>
Public Member Functions
GeometryGraph ()
GeometryGraph (int newArgIndex, const geom::Geometry *newParentGeom)
GeometryGraph (int newArgIndex, const geom::Geometry *newParentGeom, const algorithm::BoundaryNodeRule &boundaryNodeRule)
~GeometryGraph () override
const geom::Geometry * getGeometry ()
std::vector< Node * > * getBoundaryNodes ()
Returned object is owned by this GeometryGraph.
void getBoundaryNodes (std::vector< Node * > &bdyNodes)
geom::CoordinateSequence * getBoundaryPoints ()
Returned object is owned by this GeometryGraph.
Edge * findEdge (const geom::LineString *line)
void computeSplitEdges (std::vector< Edge * > *edgelist)
void addEdge (Edge *e)
void addPoint (geom::Coordinate &pt)
index::SegmentIntersector * computeSelfNodes (algorithm::LineIntersector *li, bool computeRingSelfNodes, const geom::Envelope *env=nullptr)
Compute self-nodes, taking advantage of the Geometry type to minimize the number of intersection tests. (E.g. rings are not tested for self-intersection, since they are assumed to be valid).
index::SegmentIntersector * computeSelfNodes (algorithm::LineIntersector *li, bool computeRingSelfNodes, bool isDoneIfProperInt, const geom::Envelope *env=nullptr)
index::SegmentIntersector * computeSelfNodes (algorithm::LineIntersector &li, bool computeRingSelfNodes, const geom::Envelope *env=nullptr)
index::SegmentIntersector * computeSelfNodes (algorithm::LineIntersector &li, bool computeRingSelfNodes, bool isDoneIfProperInt, const geom::Envelope *env=nullptr)
index::SegmentIntersector * computeEdgeIntersections (GeometryGraph *g, algorithm::LineIntersector *li, bool includeProper, const geom::Envelope *env=nullptr)
std::vector< Edge * > * getEdges ()
bool hasTooFewPoints ()
const geom::Coordinate & getInvalidPoint ()
const algorithm::BoundaryNodeRule & getBoundaryNodeRule () const
virtual void linkResultDirectedEdges ()
virtual std::vector< Edge * >::iterator getEdgeIterator ()
virtual std::vector< EdgeEnd * > * getEdgeEnds ()
virtual bool isBoundaryNode (int geomIndex, const geom::Coordinate &coord)
virtual void add (EdgeEnd *e)
virtual NodeMap::iterator getNodeIterator ()
virtual void getNodes (std::vector< Node * > &)
virtual Node * addNode (Node *node)
virtual Node * addNode (const geom::Coordinate &coord)
virtual Node * find (geom::Coordinate &coord)
virtual void addEdges (const std::vector< Edge * > &edgesToAdd)
Add a set of edges to the graph. For each edge two DirectedEdges will be created. DirectedEdges are NOT linked by this method.
virtual void linkAllDirectedEdges ()
virtual EdgeEnd * findEdgeEnd (Edge *e)
Returns the EdgeEnd which has edge e as its base edge (MD 18 Feb 2002 - this should return a pair of edges)
virtual Edge * findEdge (const geom::Coordinate &p0, const geom::Coordinate &p1)
Returns the edge whose first two coordinates are p0 and p1.
virtual Edge * findEdgeInSameDirection (const geom::Coordinate &p0, const geom::Coordinate &p1)
Returns the edge which starts at p0 and whose first segment is parallel to p1.
virtual std::string printEdges ()
virtual NodeMap * getNodeMap ()
Static Public Member Functions
static bool isInBoundary (int boundaryCount)
static int determineBoundary (int boundaryCount)
static int determineBoundary (const algorithm::BoundaryNodeRule &boundaryNodeRule, int boundaryCount)
template<typename It >
static void linkResultDirectedEdges (It first, It last)
For nodes in the collection (first..last), link the DirectedEdges at the node that are in the result.
Protected Member Functions
virtual void insertEdge (Edge *e)
Protected Attributes
std::vector< Edge * > * edges
NodeMap * nodes
std::vector< EdgeEnd * > * edgeEndList
Private Member Functions
index::EdgeSetIntersector * createEdgeSetIntersector ()
Allocates a new EdgeSetIntersector. Remember to delete it!
void add (const geom::Geometry *g)
void addCollection (const geom::GeometryCollection *gc)
void addPoint (const geom::Point *p)
void addPolygonRing (const geom::LinearRing *lr, int cwLeft, int cwRight)
void addPolygon (const geom::Polygon *p)
void addLineString (const geom::LineString *line)
void insertPoint (int argIndex, const geom::Coordinate &coord, int onLocation)
void insertBoundaryPoint (int argIndex, const geom::Coordinate &coord)
Adds candidate boundary points using the current algorithm::BoundaryNodeRule.
void addSelfIntersectionNodes (int argIndex)
void addSelfIntersectionNode (int argIndex, const geom::Coordinate &coord, int loc)
Add a node for a self-intersection.
GeometryGraph (const GeometryGraph &other)=delete
GeometryGraph & operator= (const GeometryGraph &rhs)=delete
Private Attributes
const geom::Geometry * parentGeom
std::map< const geom::LineString *, Edge * > lineEdgeMap
bool useBoundaryDeterminationRule
const algorithm::BoundaryNodeRule & boundaryNodeRule
int argIndex
std::unique_ptr< geom::CoordinateSequence > boundaryPoints
Cache for fast responses to getBoundaryPoints.
std::unique_ptr< std::vector< Node * > > boundaryNodes
bool hasTooFewPointsVar
geom::Coordinate invalidPoint
Detailed Description
A GeometryGraph is a graph that models a given Geometry
Definition at line 73 of file GeometryGraph.h.
Constructor & Destructor Documentation
geos::geomgraph::GeometryGraph::GeometryGraph (const GeometryGraph & other) private delete
geos::geomgraph::GeometryGraph::GeometryGraph ()
Definition at line 567 of file GeometryGraph.cpp.
   :
   PlanarGraph(),
   parentGeom(nullptr),
   useBoundaryDeterminationRule(true),
     boundaryNodeRule(algorithm::BoundaryNodeRule::getBoundaryOGCSFS()),
   argIndex(-1),
   hasTooFewPointsVar(false)
 {
 }
geos::geomgraph::GeometryGraph::GeometryGraph (int newArgIndex, const geom::Geometry * newParentGeom)
Definition at line 540 of file GeometryGraph.cpp.
References add(), and parentGeom.
   :
   PlanarGraph(),
   parentGeom(newParentGeom),
   useBoundaryDeterminationRule(true),
     boundaryNodeRule(algorithm::BoundaryNodeRule::getBoundaryOGCSFS()),
   argIndex(newArgIndex),
   hasTooFewPointsVar(false)
 {
   if (parentGeom!=nullptr) add(parentGeom);
 }
geos::geomgraph::GeometryGraph::GeometryGraph (int newArgIndex, const geom::Geometry * newParentGeom, const algorithm::BoundaryNodeRule & boundaryNodeRule)
Definition at line 553 of file GeometryGraph.cpp.
References add(), and parentGeom.
   :
   PlanarGraph(),
   parentGeom(newParentGeom),
   useBoundaryDeterminationRule(true),
   boundaryNodeRule(bnr),
   argIndex(newArgIndex),
   hasTooFewPointsVar(false)
 {
   if (parentGeom!=nullptr) add(parentGeom);
 }
INLINE geos::geomgraph::GeometryGraph::~GeometryGraph () override
Definition at line 42 of file GeometryGraph.inl.
 {
 }
Member Function Documentation
void geos::geomgraph::PlanarGraph::add (EdgeEnd * e) virtual inherited
Definition at line 134 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::add(), geos::geomgraph::PlanarGraph::edgeEndList, and geos::geomgraph::PlanarGraph::nodes.
Referenced by geos::geomgraph::PlanarGraph::addEdges().
 {
   // It is critical to add the edge to the edgeEndList first,
   // then it is safe to follow with any potentially throwing operations.
   assert(edgeEndList);
   edgeEndList->push_back(e);
   assert(e);
   assert(nodes);
   nodes->add(e);
 }
void geos::geomgraph::GeometryGraph::add (const geom::Geometry * g) private
Definition at line 176 of file GeometryGraph.cpp.
References geos::geom::Geometry::isEmpty().
Referenced by GeometryGraph().
 {
   if (g->isEmpty()) return;
   // check if this Geometry should obey the Boundary Determination Rule
   // all collections except MultiPolygons obey the rule
   if ( dynamic_cast<const MultiPolygon*>(g) )
     useBoundaryDeterminationRule = false;
   if ( const Polygon* x = dynamic_cast<const Polygon*>(g) )
     addPolygon(x);
   // LineString also handles LinearRings
   else if ( const LineString* x = dynamic_cast<const LineString*>(g) )
     addLineString(x);
   else if ( const Point* x = dynamic_cast<const Point*>(g) )
     addPoint(x);
   else if ( const GeometryCollection* x =
             dynamic_cast<const GeometryCollection*>(g) )
   {
     addCollection(x);
   }
   else {
     string out=typeid(*g).name();
     throw util::UnsupportedOperationException("GeometryGraph::add(Geometry *): unknown geometry type: "+out);
   }
 }
void geos::geomgraph::GeometryGraph::addCollection (const geom::GeometryCollection * gc) private
Definition at line 210 of file GeometryGraph.cpp.
References geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   for (size_t i=0, n=gc->getNumGeometries(); i<n; ++i)
   {
     const Geometry *g=gc->getGeometryN(i);
     add(g);
   }
 }
void geos::geomgraph::GeometryGraph::addEdge (Edge * e)
Definition at line 332 of file GeometryGraph.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), and geos::geom::CoordinateSequence::getSize().
 {
   insertEdge(e);
   const CoordinateSequence* coord=e->getCoordinates();
   // insert the endpoint as a node, to mark that it is on the boundary
   insertPoint(argIndex,coord->getAt(0),Location::BOUNDARY);
   insertPoint(argIndex,coord->getAt(coord->getSize()-1),Location::BOUNDARY);
 }
void geos::geomgraph::PlanarGraph::addEdges (const std::vector< Edge * > & edgesToAdd) virtual inherited
Add a set of edges to the graph. For each edge two DirectedEdges will be created. DirectedEdges are NOT linked by this method.
Definition at line 202 of file PlanarGraph.cpp.
References geos::geomgraph::PlanarGraph::add(), and geos::geomgraph::PlanarGraph::edges.
Referenced by geos::operation::buffer::BufferBuilder::buffer(), geos::operation::overlay::OverlayOp::computeOverlay(), and geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected().
 {
   // create all the nodes for the edges
   for (vector<Edge*>::const_iterator it=edgesToAdd.begin(),
     endIt=edgesToAdd.end(); it!=endIt; ++it)
   {
     Edge *e=*it;
     assert(e);
     edges->push_back(e);
     // PlanarGraph destructor will delete all DirectedEdges
     // in edgeEndList, which is where these are added
     // by the ::add(EdgeEnd) call
     std::unique_ptr<DirectedEdge> de1(new DirectedEdge(e, true));
     std::unique_ptr<DirectedEdge> de2(new DirectedEdge(e, false));
     de1->setSym(de2.get());
     de2->setSym(de1.get());
     // First, ::add takes the ownership, then follows with operations that may throw.
     add(de1.release());
     add(de2.release());
   }
 }
void geos::geomgraph::GeometryGraph::addLineString (const geom::LineString * line) private
Definition at line 301 of file GeometryGraph.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::CoordinateSequence::getSize(), and geos::geom::CoordinateSequence::size().
 {
   CoordinateSequence* coord=CoordinateSequence::removeRepeatedPoints(line->getCoordinatesRO());
   if(coord->getSize()<2) {
     hasTooFewPointsVar=true;
     invalidPoint=coord->getAt(0);
     delete coord;
     return;
   }
   Edge *e=new Edge(coord, Label(argIndex, Location::INTERIOR));
   lineEdgeMap[line]=e;
   insertEdge(e);
   /*
    * Add the boundary points of the LineString, if any.
    * Even if the LineString is closed, add both points as if they
    * were endpoints.
    * This allows for the case that the node already exists and is
    * a boundary point.
    */
   assert(coord->size() >= 2); // found LineString with single point
   insertBoundaryPoint(argIndex, coord->getAt(0));
   insertBoundaryPoint(argIndex, coord->getAt(coord->getSize()-1));
 }
Node * geos::geomgraph::PlanarGraph::addNode (Node * node) virtual inherited
Definition at line 171 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::addNode(), and geos::geomgraph::PlanarGraph::nodes.
Referenced by geos::operation::overlay::OverlayOp::copyPoints().
 {
   assert(nodes);
 #if GEOS_DEBUG > 1
   cerr << "PlanarGraph::addNode(Node * " << *node
     << ")" << endl;
 #endif
   return nodes->addNode(node);
 }
Node * geos::geomgraph::PlanarGraph::addNode (const geom::Coordinate & coord) virtual inherited
Definition at line 183 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::addNode(), and geos::geomgraph::PlanarGraph::nodes.
 {
 #if GEOS_DEBUG > 1
   cerr << "PlanarGraph::addNode(Coordinate& "
     << coord << ")" << endl;
 #endif
   return nodes->addNode(coord);
 }
void geos::geomgraph::GeometryGraph::addPoint (const geom::Point * p) private
Definition at line 223 of file GeometryGraph.cpp.
References geos::geom::Point::getCoordinate().
 {
   const Coordinate& coord=*(p->getCoordinate());
   insertPoint(argIndex, coord, Location::INTERIOR);
 }
void geos::geomgraph::GeometryGraph::addPoint (geom::Coordinate & pt)
Definition at line 346 of file GeometryGraph.cpp.
 {
   insertPoint(argIndex,pt,Location::INTERIOR);
 }
void geos::geomgraph::GeometryGraph::addPolygon (const geom::Polygon * p) private
Definition at line 279 of file GeometryGraph.cpp.
References geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), and geos::geom::Polygon::getNumInteriorRing().
 {
   const LineString* ls;
   const LinearRing* lr;
   ls = p->getExteriorRing();
   assert(dynamic_cast<const LinearRing*>(ls));
   lr = static_cast<const LinearRing*>(ls);
   addPolygonRing(lr, Location::EXTERIOR, Location::INTERIOR);
   for (size_t i=0, n=p->getNumInteriorRing(); i<n; ++i)
   {
     // Holes are topologically labelled opposite to the shell, since
     // the interior of the polygon lies on their opposite side
     // (on the left, if the hole is oriented CW)
     ls = p->getInteriorRingN(i);
     assert(dynamic_cast<const LinearRing*>(ls));
     lr = static_cast<const LinearRing*>(ls);
     addPolygonRing(lr, Location::INTERIOR, Location::EXTERIOR);
   }
 }
void geos::geomgraph::GeometryGraph::addPolygonRing (const geom::LinearRing * lr, int cwLeft, int cwRight) private
Definition at line 236 of file GeometryGraph.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::CoordinateSequence::getSize(), and geos::geom::LineString::isEmpty().
 {
   // skip empty component (see bug #234)
   if ( lr->isEmpty() ) return;
   const CoordinateSequence *lrcl = lr->getCoordinatesRO();
   CoordinateSequence* coord=CoordinateSequence::removeRepeatedPoints(lrcl);
   if (coord->getSize()<4) {
     hasTooFewPointsVar=true;
     invalidPoint=coord->getAt(0); // its now a Coordinate
     delete coord;
     return;
   }
   int left=cwLeft;
   int right=cwRight;
   /*
    * the isCCW call might throw an
    * IllegalArgumentException if degenerate ring does
    * not contain 3 distinct points.
    */
   try
   {
     if (CGAlgorithms::isCCW(coord)) {
       left=cwRight;
       right=cwLeft;
     }
   }
   catch(...)
   {
     delete coord;
     throw;
   }
   Edge *e=new Edge(coord, Label(argIndex, Location::BOUNDARY, left, right));
   lineEdgeMap[lr]=e;
   insertEdge(e);
   insertPoint(argIndex,coord->getAt(0), Location::BOUNDARY);
 }
void geos::geomgraph::GeometryGraph::addSelfIntersectionNode (int argIndex, const geom::Coordinate & coord, int loc) private
Add a node for a self-intersection.
If the node is a potential boundary node (e.g. came from an edge which is a boundary) then insert it as a potential boundary node. Otherwise, just add it as a regular node.
Definition at line 507 of file GeometryGraph.cpp.
 {
   // if this node is already a boundary node, don't change it
   if (isBoundaryNode(argIndex,coord)) return;
   if (loc==Location::BOUNDARY && useBoundaryDeterminationRule)
   {
     insertBoundaryPoint(argIndex,coord);
   }
   else
   {
     insertPoint(argIndex,coord,loc);
   }
 }
void geos::geomgraph::GeometryGraph::addSelfIntersectionNodes (int argIndex) private
Definition at line 486 of file GeometryGraph.cpp.
References geos::geomgraph::EdgeIntersectionList::begin(), geos::geomgraph::EdgeIntersection::coord, geos::geomgraph::Edge::eiList, geos::geomgraph::EdgeIntersectionList::end(), GEOS_CHECK_FOR_INTERRUPTS, geos::geomgraph::GraphComponent::getLabel(), and geos::geomgraph::Label::getLocation().
 {
   for (vector<Edge*>::iterator i=edges->begin(), endIt=edges->end();
     i!=endIt; ++i)
   {
     Edge *e=*i;
     int eLoc = e->getLabel().getLocation(argIndex);
     EdgeIntersectionList &eiL = e->eiList;
     for (EdgeIntersectionList::iterator
       eiIt=eiL.begin(), eiEnd=eiL.end();
       eiIt!=eiEnd; ++eiIt)
     {
       EdgeIntersection *ei=*eiIt;
       addSelfIntersectionNode(argIndex, ei->coord, eLoc);
       GEOS_CHECK_FOR_INTERRUPTS();
     }
   }
 }
SegmentIntersector * geos::geomgraph::GeometryGraph::computeEdgeIntersections (GeometryGraph * g, algorithm::LineIntersector * li, bool includeProper, const geom::Envelope * env = nullptr)
Definition at line 404 of file GeometryGraph.cpp.
References geos::geomgraph::collect_intersecting_edges(), geos::geom::Envelope::covers(), geos::geomgraph::PlanarGraph::edges, getBoundaryNodes(), geos::geom::Geometry::getEnvelopeInternal(), parentGeom, and geos::geomgraph::index::SegmentIntersector::setBoundaryNodes().
 {
 #if GEOS_DEBUG
   cerr<<"GeometryGraph::computeEdgeIntersections call"<<endl;
 #endif
   SegmentIntersector *si=new SegmentIntersector(li, includeProper, true);
   si->setBoundaryNodes(getBoundaryNodes(), g->getBoundaryNodes());
   unique_ptr<EdgeSetIntersector> esi(createEdgeSetIntersector());
   typedef vector<Edge*> EC;
   EC self_edges_copy;
   EC other_edges_copy;
   EC *se = edges;
   EC *oe = g->edges;
   if ( env && ! env->covers(parentGeom->getEnvelopeInternal()) ) {
     collect_intersecting_edges(env, se->begin(), se->end(), self_edges_copy);
     //cerr << "Self edges reduced from " << se->size() << " to " << self_edges_copy.size() << endl;
     se = &self_edges_copy;
   }
   if ( env && ! env->covers(g->parentGeom->getEnvelopeInternal()) ) {
     collect_intersecting_edges(env, oe->begin(), oe->end(), other_edges_copy);
     //cerr << "Other edges reduced from " << oe->size() << " to " << other_edges_copy.size() << endl;
     oe = &other_edges_copy;
   }
   esi->computeIntersections(se, oe, si);
 #if GEOS_DEBUG
   cerr<<"GeometryGraph::computeEdgeIntersections returns"<<endl;
 #endif
   return si;
 }
index::SegmentIntersector* geos::geomgraph::GeometryGraph::computeSelfNodes (algorithm::LineIntersector * li, bool computeRingSelfNodes, const geom::Envelope * env = nullptr) inline
Compute self-nodes, taking advantage of the Geometry type to minimize the number of intersection tests. (E.g. rings are not tested for self-intersection, since they are assumed to be valid).
Parameters
li the LineIntersector to use
computeRingSelfNodes if <false>, intersection checks are optimized to not test rings for self-intersection
Returns
the SegmentIntersector used, containing information about the intersections found
Definition at line 214 of file GeometryGraph.h.
Referenced by geos::operation::valid::IsValidOp::checkValid(), geos::operation::valid::ConsistentAreaTester::isNodeConsistentArea(), and geos::operation::IsSimpleOp::isSimpleLinearGeometry().
   {
     return computeSelfNodes(*li, computeRingSelfNodes, env);
   }
index::SegmentIntersector* geos::geomgraph::GeometryGraph::computeSelfNodes (algorithm::LineIntersector * li, bool computeRingSelfNodes, bool isDoneIfProperInt, const geom::Envelope * env = nullptr) inline
Definition at line 222 of file GeometryGraph.h.
   {
     return computeSelfNodes(*li, computeRingSelfNodes, isDoneIfProperInt, env);
   }
SegmentIntersector * geos::geomgraph::GeometryGraph::computeSelfNodes (algorithm::LineIntersector & li, bool computeRingSelfNodes, const geom::Envelope * env = nullptr)
Definition at line 363 of file GeometryGraph.cpp.
 {
   return computeSelfNodes(li, computeRingSelfNodes, false, env);
 }
SegmentIntersector * geos::geomgraph::GeometryGraph::computeSelfNodes (algorithm::LineIntersector & li, bool computeRingSelfNodes, bool isDoneIfProperInt, const geom::Envelope * env = nullptr)
Definition at line 370 of file GeometryGraph.cpp.
References geos::geomgraph::collect_intersecting_edges(), geos::geom::Envelope::covers(), geos::geomgraph::index::SegmentIntersector::numTests, and geos::geomgraph::index::SegmentIntersector::setIsDoneIfProperInt().
 {
   SegmentIntersector *si = new SegmentIntersector(&li, true, false);
   si->setIsDoneIfProperInt(isDoneIfProperInt);
   unique_ptr<EdgeSetIntersector> esi(createEdgeSetIntersector());
   typedef vector<Edge*> EC;
   EC *se = edges;
   EC self_edges_copy;
   if ( env && ! env->covers(parentGeom->getEnvelopeInternal()) ) {
     collect_intersecting_edges(env, se->begin(), se->end(), self_edges_copy);
     //cerr << "(computeSelfNodes) Self edges reduced from " << se->size() << " to " << self_edges_copy.size() << endl;
     se = &self_edges_copy;
   }
   bool isRings = dynamic_cast<const LinearRing*>(parentGeom)
       || dynamic_cast<const Polygon*>(parentGeom)
       || dynamic_cast<const MultiPolygon*>(parentGeom);
   bool computeAllSegments = computeRingSelfNodes || ! isRings;
   esi->computeIntersections(se, si, computeAllSegments);
 #if GEOS_DEBUG
   cerr << "SegmentIntersector # tests = " << si->numTests << endl;
 #endif // GEOS_DEBUG
   addSelfIntersectionNodes(argIndex);
   return si;
 }
void geos::geomgraph::GeometryGraph::computeSplitEdges (std::vector< Edge * > * edgelist)
Definition at line 156 of file GeometryGraph.cpp.
References geos::geomgraph::EdgeIntersectionList::addSplitEdges(), geos::geomgraph::Edge::eiList, and geos::geomgraph::Edge::print().
Referenced by geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected().
 {
 #if GEOS_DEBUG
   cerr<<"["<<this<<"] GeometryGraph::computeSplitEdges() scanning "<<edges->size()<<" local and "<<edgelist->size()<<" provided edges"<<endl;
 #endif
   for (vector<Edge*>::iterator i=edges->begin(), endIt=edges->end();
     i!=endIt; ++i)
   {
     Edge *e=*i;
 #if GEOS_DEBUG
     cerr<<"   "<<e->print()<<" adding split edges from arg"<<endl;
 #endif
     e->eiList.addSplitEdges(edgelist);
   }
 #if GEOS_DEBUG
   cerr<<"["<<this<<"] GeometryGraph::computeSplitEdges() completed "<<endl;
 #endif
 }
EdgeSetIntersector * geos::geomgraph::GeometryGraph::createEdgeSetIntersector () private
Allocates a new EdgeSetIntersector. Remember to delete it!
Definition at line 100 of file GeometryGraph.cpp.
 {
   // various options for computing intersections, from slowest to fastest
   //private EdgeSetIntersector esi = new SimpleEdgeSetIntersector();
   //private EdgeSetIntersector esi = new MonotoneChainIntersector();
   //private EdgeSetIntersector esi = new NonReversingChainIntersector();
   //private EdgeSetIntersector esi = new SimpleSweepLineIntersector();
   //private EdgeSetIntersector esi = new MCSweepLineIntersector();
   //return new SimpleEdgeSetIntersector();
   return new SimpleMCSweepLineIntersector();
 }
int geos::geomgraph::GeometryGraph::determineBoundary (int boundaryCount) static
Definition at line 93 of file GeometryGraph.cpp.
 {
   return isInBoundary(boundaryCount)?Location::BOUNDARY : Location::INTERIOR;
 }
int geos::geomgraph::GeometryGraph::determineBoundary (const algorithm::BoundaryNodeRule & boundaryNodeRule, int boundaryCount) static
Definition at line 581 of file GeometryGraph.cpp.
References geos::algorithm::BoundaryNodeRule::isInBoundary().
 {
   return boundaryNodeRule.isInBoundary(boundaryCount)
     ? Location::BOUNDARY : Location::INTERIOR;
 }
Node * geos::geomgraph::PlanarGraph::find (geom::Coordinate & coord) virtual inherited
Returns
the node if found; null otherwise
Definition at line 194 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::find(), and geos::geomgraph::PlanarGraph::nodes.
 {
   assert(nodes);
   return nodes->find(coord);
 }
Edge * geos::geomgraph::PlanarGraph::findEdge (const geom::Coordinate & p0, const geom::Coordinate & p1) virtual inherited
Returns the edge whose first two coordinates are p0 and p1.
Returns
the edge, if found null if the edge was not found
Definition at line 298 of file PlanarGraph.cpp.
References geos::geomgraph::PlanarGraph::edges, geos::geom::CoordinateSequence::getAt(), and geos::geomgraph::Edge::getCoordinates().
 {
   for (size_t i=0, n=edges->size(); i<n; ++i)
   {
     Edge *e=(*edges)[i];
     assert(e);
     const CoordinateSequence* eCoord=e->getCoordinates();
     assert(eCoord);
     if (p0==eCoord->getAt(0) && p1==eCoord->getAt(1))
       return e;
   }
   return nullptr;
 }
Edge * geos::geomgraph::GeometryGraph::findEdge (const geom::LineString * line)
Definition at line 150 of file GeometryGraph.cpp.
Referenced by geos::operation::valid::IsValidOp::findPtNotNode().
 {
   return lineEdgeMap.find(line)->second;
 }
EdgeEnd * geos::geomgraph::PlanarGraph::findEdgeEnd (Edge * e) virtual inherited
Returns the EdgeEnd which has edge e as its base edge (MD 18 Feb 2002 - this should return a pair of edges)
Returns
the edge, if found null if the edge was not found
Definition at line 278 of file PlanarGraph.cpp.
References geos::geomgraph::EdgeEnd::getEdge(), and geos::geomgraph::PlanarGraph::getEdgeEnds().
Referenced by geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
 {
   vector<EdgeEnd*>* eev=getEdgeEnds();
   assert(eev);
   for (vector<EdgeEnd*>::iterator i=eev->begin(), iEnd=eev->end();
       i != iEnd;
       ++i)
   {
     EdgeEnd *ee=*i;
     assert(ee);
     // should test using values rather then pointers ?
     if (ee->getEdge()==e) return ee;
   }
   return nullptr;
 }
Edge * geos::geomgraph::PlanarGraph::findEdgeInSameDirection (const geom::Coordinate & p0, const geom::Coordinate & p1) virtual inherited
Returns the edge which starts at p0 and whose first segment is parallel to p1.
Returns
the edge, if found null if the edge was not found
Definition at line 316 of file PlanarGraph.cpp.
References geos::geomgraph::PlanarGraph::edges, geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), geos::geomgraph::PlanarGraph::matchInSameDirection(), and geos::geom::CoordinateSequence::size().
Referenced by geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
 {
   for(size_t i=0, n=edges->size(); i<n; i++)
   {
     Edge *e=(*edges)[i];
     assert(e);
     const CoordinateSequence* eCoord=e->getCoordinates();
     assert(eCoord);
     size_t nCoords=eCoord->size();
     assert(nCoords>1);
     if (matchInSameDirection(p0, p1,
         eCoord->getAt(0),
         eCoord->getAt(1)))
     {
       return e;
     }
     if (matchInSameDirection(p0, p1,
         eCoord->getAt(nCoords-1),
         eCoord->getAt(nCoords-2)))
     {
       return e;
     }
   }
   return nullptr;
 }
const algorithm::BoundaryNodeRule& geos::geomgraph::GeometryGraph::getBoundaryNodeRule () const inline
Definition at line 251 of file GeometryGraph.h.
Referenced by geos::geomgraph::EdgeEndStar::isAreaLabelsConsistent().
   { return boundaryNodeRule; }
vector< Node * > * geos::geomgraph::GeometryGraph::getBoundaryNodes ()
Returned object is owned by this GeometryGraph.
Definition at line 116 of file GeometryGraph.cpp.
Referenced by computeEdgeIntersections().
 {
   if ( ! boundaryNodes.get() )
   {
     boundaryNodes.reset(new vector<Node*>());
     getBoundaryNodes(*(boundaryNodes.get()));
   }
   return boundaryNodes.get();
 }
INLINE void geos::geomgraph::GeometryGraph::getBoundaryNodes (std::vector< Node * > & bdyNodes)
Definition at line 30 of file GeometryGraph.inl.
References argIndex, geos::geomgraph::NodeMap::getBoundaryNodes(), INLINE, and geos::geomgraph::PlanarGraph::nodes.
 {
   nodes->getBoundaryNodes(argIndex, bdyNodes);
 }
CoordinateSequence * geos::geomgraph::GeometryGraph::getBoundaryPoints ()
Returned object is owned by this GeometryGraph.
Definition at line 128 of file GeometryGraph.cpp.
References geos::geomgraph::Node::getCoordinate().
Referenced by geos::geom::MultiLineString::getBoundary().
 {
   if ( ! boundaryPoints.get() )
   {
     // Collection will be destroied by GeometryGraph dtor
     vector<Node*>* coll = getBoundaryNodes();
     boundaryPoints.reset(new CoordinateArraySequence(coll->size()));
     size_t i=0;
     for (vector<Node*>::iterator it=coll->begin(), endIt=coll->end();
       it!=endIt; ++it)
     {
       Node *node=*it;
       boundaryPoints->setAt(node->getCoordinate(), i++);
     }
   }
   // We keep ownership of this, will be destroyed by destructor
   return boundaryPoints.get();
 }
vector< EdgeEnd * > * geos::geomgraph::PlanarGraph::getEdgeEnds () virtual inherited
Definition at line 102 of file PlanarGraph.cpp.
References geos::geomgraph::PlanarGraph::edgeEndList.
Referenced by geos::operation::overlay::PolygonBuilder::add(), geos::operation::overlay::OverlayOp::cancelDuplicateResultEdges(), geos::operation::overlay::LineBuilder::collectLines(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), geos::geomgraph::PlanarGraph::findEdgeEnd(), geos::operation::overlay::OverlayOp::findResultAreaEdges(), geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected(), and geos::operation::valid::ConnectedInteriorTester::setInteriorEdgesInResult().
 {
   return edgeEndList;
 }
vector< Edge * >::iterator geos::geomgraph::PlanarGraph::getEdgeIterator () virtual inherited
Definition at line 94 of file PlanarGraph.cpp.
References geos::geomgraph::PlanarGraph::edges.
 {
   assert(edges);
   return edges->begin();
 }
vector< Edge * > * geos::geomgraph::GeometryGraph::getEdges ()
Definition at line 523 of file GeometryGraph.cpp.
Referenced by geos::operation::relate::RelateNodeGraph::build(), geos::operation::valid::IsValidOp::checkNoSelfIntersectingRings(), geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::IsSimpleOp::hasClosedEndpointIntersection(), and geos::operation::IsSimpleOp::hasNonEndpointIntersection().
 {
   return edges;
 }
INLINE const geom::Geometry * geos::geomgraph::GeometryGraph::getGeometry ()
Definition at line 36 of file GeometryGraph.inl.
References INLINE, and parentGeom.
Referenced by geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected().
 {
   return parentGeom;
 }
const Coordinate & geos::geomgraph::GeometryGraph::getInvalidPoint ()
Definition at line 535 of file GeometryGraph.cpp.
Referenced by geos::operation::valid::IsValidOp::checkTooFewPoints().
 {
   return invalidPoint;
 }
NodeMap::iterator geos::geomgraph::PlanarGraph::getNodeIterator () virtual inherited
Definition at line 148 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::begin(), and geos::geomgraph::PlanarGraph::nodes.
 {
   assert(nodes);
   return nodes->begin();
 }
NodeMap * geos::geomgraph::PlanarGraph::getNodeMap () virtual inherited
Definition at line 377 of file PlanarGraph.cpp.
References geos::geomgraph::PlanarGraph::nodes.
Referenced by geos::operation::overlay::PolygonBuilder::add(), geos::operation::overlay::OverlayOp::computeLabelling(), geos::operation::relate::RelateNodeGraph::copyNodesAndLabels(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), geos::operation::overlay::OverlayOp::labelIncompleteNodes(), geos::operation::overlay::OverlayOp::mergeSymLabels(), and geos::operation::overlay::OverlayOp::updateNodeLabelling().
 {
   return nodes;
 }
void geos::geomgraph::PlanarGraph::getNodes (std::vector< Node * > & values) virtual inherited
Definition at line 156 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::nodeMap, and geos::geomgraph::PlanarGraph::nodes.
Referenced by geos::operation::buffer::BufferBuilder::createSubgraphs().
 {
   assert(nodes);
   NodeMap::iterator it=nodes->nodeMap.begin();
   while(it!=nodes->nodeMap.end()) {
     assert(it->second);
     values.push_back(it->second);
     it++;
   }
 }
bool geos::geomgraph::GeometryGraph::hasTooFewPoints ()
Definition at line 529 of file GeometryGraph.cpp.
Referenced by geos::operation::valid::IsValidOp::checkTooFewPoints().
 {
   return hasTooFewPointsVar;
 }
void geos::geomgraph::GeometryGraph::insertBoundaryPoint (int argIndex, const geom::Coordinate & coord) private
Adds candidate boundary points using the current algorithm::BoundaryNodeRule.
This is used to add the boundary points of dim-1 geometries (Curves/MultiCurves).
Definition at line 465 of file GeometryGraph.cpp.
References geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), and geos::geomgraph::Label::setLocation().
 {
   Node *n=nodes->addNode(coord);
   // nodes always have labels
   Label& lbl = n->getLabel();
   // the new point to insert is on a boundary
   int boundaryCount=1;
   // determine the current location for the point (if any)
   int loc = lbl.getLocation(argIndex,Position::ON);
   if (loc==Location::BOUNDARY) boundaryCount++;
   // determine the boundary status of the point according to the
   // Boundary Determination Rule
   int newLoc = determineBoundary(boundaryNodeRule, boundaryCount);
   lbl.setLocation(argIndex,newLoc);
 }
void geos::geomgraph::PlanarGraph::insertEdge (Edge * e) protected virtual inherited
Definition at line 125 of file PlanarGraph.cpp.
References geos::geomgraph::PlanarGraph::edges.
 {
   assert(e);
   assert(edges);
   edges->push_back(e);
 }
void geos::geomgraph::GeometryGraph::insertPoint (int argIndex, const geom::Coordinate & coord, int onLocation) private
Definition at line 440 of file GeometryGraph.cpp.
References geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::isNull(), geos::geomgraph::Node::setLabel(), geos::geomgraph::Label::setLocation(), and geos::geom::Coordinate::toString().
 {
 #if GEOS_DEBUG > 1
   cerr<<"GeometryGraph::insertPoint("<<coord.toString()<<" called"<<endl;
 #endif
   Node *n=nodes->addNode(coord);
   Label& lbl = n->getLabel();
   if ( lbl.isNull() )
   {
     n->setLabel(argIndex, onLocation);
   }
   else
   {
     lbl.setLocation(argIndex, onLocation);
   }
 }
bool geos::geomgraph::PlanarGraph::isBoundaryNode (int geomIndex, const geom::Coordinate & coord) virtual inherited
Definition at line 109 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::find(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isNull(), and geos::geomgraph::PlanarGraph::nodes.
 {
   assert(nodes);
   Node *node=nodes->find(coord);
   if (node==nullptr) return false;
   const Label& label = node->getLabel();
   if (! label.isNull() && label.getLocation(geomIndex)==Location::BOUNDARY)
       return true;
   return false;
 }
bool geos::geomgraph::GeometryGraph::isInBoundary (int boundaryCount) static
Definition at line 86 of file GeometryGraph.cpp.
Referenced by geos::algorithm::PointLocator::locate().
 {
   // the "Mod-2 Rule"
   return boundaryCount%2==1;
 }
void geos::geomgraph::PlanarGraph::linkAllDirectedEdges () virtual inherited
Definition at line 254 of file PlanarGraph.cpp.
References geos::geomgraph::Node::getEdges(), geos::geomgraph::DirectedEdgeStar::linkAllDirectedEdges(), geos::geomgraph::NodeMap::nodeMap, and geos::geomgraph::PlanarGraph::nodes.
 {
 #if GEOS_DEBUG
   cerr<<"PlanarGraph::linkAllDirectedEdges called"<<endl;
 #endif
   NodeMap::iterator nodeit=nodes->nodeMap.begin();
   for (;nodeit!=nodes->nodeMap.end();nodeit++)
   {
     Node *node=nodeit->second;
     assert(node);
     EdgeEndStar *ees=node->getEdges();
     assert(ees);
     // Unespected non-DirectedEdgeStar in node
     assert(dynamic_cast<DirectedEdgeStar *>(ees));
     DirectedEdgeStar *des=static_cast<DirectedEdgeStar *>(ees);
     des->linkAllDirectedEdges();
   }
 }
template<typename It > static void geos::geomgraph::PlanarGraph::linkResultDirectedEdges (It first, It last) inline static inherited
For nodes in the collection (first..last), link the DirectedEdges at the node that are in the result.
This allows clients to link only a subset of nodes in the graph, for efficiency (because they know that only a subset is of interest).
Definition at line 87 of file PlanarGraph.h.
References geos::geomgraph::Node::getEdges(), and geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges().
Referenced by geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected().
   {
     for ( ; first!=last; ++first )
     {
       Node *node=*first;
       assert(node);
       EdgeEndStar* ees = node->getEdges();
       assert(ees);
       DirectedEdgeStar* des = dynamic_cast<DirectedEdgeStar*>(ees);
       assert(des);
       // this might throw an exception
       des->linkResultDirectedEdges();
     }
   }
void geos::geomgraph::PlanarGraph::linkResultDirectedEdges () virtual inherited
Definition at line 228 of file PlanarGraph.cpp.
References geos::geomgraph::Node::getEdges(), geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges(), geos::geomgraph::NodeMap::nodeMap, and geos::geomgraph::PlanarGraph::nodes.
 {
 #if GEOS_DEBUG
   cerr<<"PlanarGraph::linkResultDirectedEdges called"<<endl;
 #endif
   NodeMap::iterator nodeit=nodes->nodeMap.begin();
   for (;nodeit!=nodes->nodeMap.end();nodeit++) {
     Node *node=nodeit->second;
     assert(node);
     EdgeEndStar* ees=node->getEdges();
     assert(ees);
     assert(dynamic_cast<DirectedEdgeStar*>(ees));
     DirectedEdgeStar* des = static_cast<DirectedEdgeStar*>(ees);
     // this might throw an exception
     des->linkResultDirectedEdges();
   }
 }
GeometryGraph& geos::geomgraph::GeometryGraph::operator= (const GeometryGraph & rhs) private delete
string geos::geomgraph::PlanarGraph::printEdges () virtual inherited
Definition at line 363 of file PlanarGraph.cpp.
References geos::geomgraph::PlanarGraph::edges, geos::geomgraph::Edge::eiList, geos::geomgraph::EdgeIntersectionList::print(), and geos::geomgraph::Edge::print().
 {
     std::ostringstream oss;
     oss << "Edges: ";
   for(size_t i=0, n=edges->size(); i<n; ++i)
   {
         Edge *e=(*edges)[i];
     oss << "edge " << i << ":\n" << e->print() << e->eiList.print();
   }
     return oss.str();
 }
Member Data Documentation
int geos::geomgraph::GeometryGraph::argIndex private
the index of this geometry as an argument to a spatial function (used for labelling)
Definition at line 105 of file GeometryGraph.h.
Referenced by getBoundaryNodes().
const algorithm::BoundaryNodeRule& geos::geomgraph::GeometryGraph::boundaryNodeRule private
Definition at line 99 of file GeometryGraph.h.
std::unique_ptr< std::vector<Node*> > geos::geomgraph::GeometryGraph::boundaryNodes private
Definition at line 110 of file GeometryGraph.h.
std::unique_ptr< geom::CoordinateSequence > geos::geomgraph::GeometryGraph::boundaryPoints private
Cache for fast responses to getBoundaryPoints.
Definition at line 108 of file GeometryGraph.h.
std::vector<EdgeEnd*>* geos::geomgraph::PlanarGraph::edgeEndList protected inherited
Definition at line 180 of file PlanarGraph.h.
Referenced by geos::geomgraph::PlanarGraph::add(), geos::geomgraph::PlanarGraph::getEdgeEnds(), and geos::geomgraph::PlanarGraph::~PlanarGraph().
std::vector<Edge*>* geos::geomgraph::PlanarGraph::edges protected inherited
Definition at line 176 of file PlanarGraph.h.
Referenced by geos::geomgraph::PlanarGraph::addEdges(), computeEdgeIntersections(), geos::geomgraph::PlanarGraph::findEdge(), geos::geomgraph::PlanarGraph::findEdgeInSameDirection(), geos::geomgraph::PlanarGraph::getEdgeIterator(), geos::geomgraph::PlanarGraph::insertEdge(), geos::geomgraph::PlanarGraph::printEdges(), and geos::geomgraph::PlanarGraph::~PlanarGraph().
bool geos::geomgraph::GeometryGraph::hasTooFewPointsVar private
Definition at line 112 of file GeometryGraph.h.
geom::Coordinate geos::geomgraph::GeometryGraph::invalidPoint private
Definition at line 114 of file GeometryGraph.h.
std::map<const geom::LineString*, Edge*> geos::geomgraph::GeometryGraph::lineEdgeMap private
The lineEdgeMap is a map of the linestring components of the parentGeometry to the edges which are derived from them. This is used to efficiently perform findEdge queries
Following the above description there's no need to compare LineStrings other then by pointer value.
Definition at line 91 of file GeometryGraph.h.
NodeMap* geos::geomgraph::PlanarGraph::nodes protected inherited
Definition at line 178 of file PlanarGraph.h.
Referenced by geos::geomgraph::PlanarGraph::add(), geos::geomgraph::PlanarGraph::addNode(), geos::geomgraph::PlanarGraph::find(), getBoundaryNodes(), geos::geomgraph::PlanarGraph::getNodeIterator(), geos::geomgraph::PlanarGraph::getNodeMap(), geos::geomgraph::PlanarGraph::getNodes(), geos::geomgraph::PlanarGraph::isBoundaryNode(), geos::geomgraph::PlanarGraph::linkAllDirectedEdges(), geos::geomgraph::PlanarGraph::linkResultDirectedEdges(), and geos::geomgraph::PlanarGraph::~PlanarGraph().
const geom::Geometry* geos::geomgraph::GeometryGraph::parentGeom private
Definition at line 80 of file GeometryGraph.h.
Referenced by computeEdgeIntersections(), GeometryGraph(), and getGeometry().
bool geos::geomgraph::GeometryGraph::useBoundaryDeterminationRule private
If this flag is true, the Boundary Determination Rule will used when deciding whether nodes are in the boundary or not
Definition at line 97 of file GeometryGraph.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/GeometryGraph.h
/home/vicky/potree/geos/vicky/src/geomgraph/GeometryGraph.cpp
/home/vicky/potree/geos/vicky/include/geos/geomgraph/GeometryGraph.inl