GEOS: geos::geomgraph::Depth Class Reference
geos::geomgraph::Depth Class Reference
#include <Depth.h>
Public Member Functions
Depth ()
virtual ~Depth ()
int getDepth (int geomIndex, int posIndex) const
void setDepth (int geomIndex, int posIndex, int depthValue)
int getLocation (int geomIndex, int posIndex) const
void add (int geomIndex, int posIndex, int location)
bool isNull () const
bool isNull (int geomIndex) const
bool isNull (int geomIndex, int posIndex) const
int getDelta (int geomIndex) const
void normalize ()
void add (const Label &lbl)
std::string toString () const
Static Public Member Functions
static int depthAtLocation (int location)
Private Types
enum { NULL_VALUE =-1 }
Private Attributes
int depth [2][3]
Detailed Description
Definition at line 39 of file Depth.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
NULL_VALUE
Definition at line 56 of file Depth.h.
        {
     NULL_VALUE=-1 //Replaces NULL
   };
Constructor & Destructor Documentation
geos::geomgraph::Depth::Depth ()
Definition at line 44 of file Depth.cpp.
References NULL_VALUE.
 {
   // initialize depth array to a sentinel value
   for (int i=0; i<2; i++) {
     for (int j=0; j<3;j++) {
       depth[i][j]=NULL_VALUE;
     }
   }
 }
geos::geomgraph::Depth::~Depth () virtual
Definition at line 54 of file Depth.cpp.
 {
 //  delete[] &depth;
 }
Member Function Documentation
void geos::geomgraph::Depth::add (int geomIndex, int posIndex, int location)
Definition at line 79 of file Depth.cpp.
Referenced by geos::operation::overlay::OverlayOp::insertUniqueEdge().
 {
   if (location == Location::INTERIOR)
     depth[geomIndex][posIndex]++;
 }
void geos::geomgraph::Depth::add (const Label & lbl)
Definition at line 146 of file Depth.cpp.
References geos::geomgraph::Label::getLocation().
 {
   for (int i=0; i<2; i++) {
     for (int j=1; j<3; j++) {
       int loc=lbl.getLocation(i,j);
       if (loc==Location::EXTERIOR || loc==Location::INTERIOR)
       {
         // initialize depth if it is null, otherwise
         // add this location value
         if (isNull(i,j)) {
           depth[i][j]=depthAtLocation(loc);
         } else
           depth[i][j]+=depthAtLocation(loc);
       }
     }
   }
 }
int geos::geomgraph::Depth::depthAtLocation (int location) static
Definition at line 37 of file Depth.cpp.
References NULL_VALUE.
 {
   if (location == Location::EXTERIOR) return 0;
   if (location == Location::INTERIOR) return 1;
   return NULL_VALUE;
 }
int geos::geomgraph::Depth::getDelta (int geomIndex) const
Definition at line 113 of file Depth.cpp.
Referenced by geos::operation::overlay::OverlayOp::computeLabelsFromDepths().
 {
   return depth[geomIndex][Position::RIGHT]-depth[geomIndex][Position::LEFT];
 }
int geos::geomgraph::Depth::getDepth (int geomIndex, int posIndex) const
Definition at line 60 of file Depth.cpp.
Referenced by geos::operation::overlay::OverlayOp::computeLabelsFromDepths().
 {
   return depth[geomIndex][posIndex];
 }
int geos::geomgraph::Depth::getLocation (int geomIndex, int posIndex) const
Definition at line 72 of file Depth.cpp.
Referenced by geos::operation::overlay::OverlayOp::computeLabelsFromDepths().
 {
   if (depth[geomIndex][posIndex] <= 0) return Location::EXTERIOR;
   return Location::INTERIOR;
 }
bool geos::geomgraph::Depth::isNull (void) const
A Depth object is null (has never been initialized) if all depths are null.
Definition at line 89 of file Depth.cpp.
References NULL_VALUE.
Referenced by geos::operation::overlay::OverlayOp::computeLabelsFromDepths(), and geos::operation::overlay::OverlayOp::insertUniqueEdge().
 {
   for (int i=0; i<2; i++) {
     for (int j=0; j<3; j++) {
       if (depth[i][j] != NULL_VALUE)
         return false;
     }
   }
   return true;
 }
bool geos::geomgraph::Depth::isNull (int geomIndex) const
Definition at line 101 of file Depth.cpp.
References NULL_VALUE.
 {
   return depth[geomIndex][1] == NULL_VALUE;
 }
bool geos::geomgraph::Depth::isNull (int geomIndex, int posIndex) const
Definition at line 107 of file Depth.cpp.
References NULL_VALUE.
 {
   return depth[geomIndex][posIndex] == NULL_VALUE;
 }
void geos::geomgraph::Depth::normalize (void)
Normalize the depths for each geometry, if they are non-null. A normalized depth has depth values in the set { 0, 1 }. Normalizing the depths involves reducing the depths by the same amount so that at least one of them is 0. If the remaining value is > 0, it is set to 1.
Definition at line 127 of file Depth.cpp.
Referenced by geos::operation::overlay::OverlayOp::computeLabelsFromDepths().
 {
   for (int i=0; i<2; i++) {
     if (!isNull(i)) {
       int minDepth=depth[i][1];
       if (depth[i][2]<minDepth)
         minDepth=depth[i][2];
       if (minDepth<0) minDepth = 0;
       for (int j=1; j<3; j++) {
         int newValue=0;
         if (depth[i][j]>minDepth)
           newValue = 1;
         depth[i][j] = newValue;
       }
     }
   }
 }
void geos::geomgraph::Depth::setDepth (int geomIndex, int posIndex, int depthValue)
Definition at line 66 of file Depth.cpp.
 {
   depth[geomIndex][posIndex] = depthValue;
 }
string geos::geomgraph::Depth::toString (void) const
Definition at line 165 of file Depth.cpp.
 {
   ostringstream s;
   s<<"A:"<<depth[0][1]<<","<<depth[0][2]<<" ";
   s<<"B:"<<depth[1][1]<<","<<depth[1][2]<<"]";
   return s.str();
 }
Member Data Documentation
int geos::geomgraph::Depth::depth[2][3] private
Definition at line 59 of file Depth.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/Depth.h
/home/vicky/potree/geos/vicky/src/geomgraph/Depth.cpp