GEOS: geos::util::Interrupt Class Reference
geos::util::Interrupt Class Reference
#include <Interrupt.h>
Public Types
typedef void(Callback) (void)
Static Public Member Functions
static void request ()
static void cancel ()
static bool check ()
static Callback * registerCallback (Callback *cb)
Register a callback that will be invoked before checking for interruption requests.
static void process ()
static void interrupt ()
Detailed Description
Used to manage interruption requests and callbacks
Definition at line 26 of file Interrupt.h.
Member Typedef Documentation
typedef void(geos::util::Interrupt::Callback) (void)
Definition at line 30 of file Interrupt.h.
Member Function Documentation
void geos::util::Interrupt::cancel () static
Cancel a pending interruption request
Definition at line 36 of file Interrupt.cpp.
Referenced by GEOS_init_r(), GEOS_interruptCancel(), and initGEOS().
 { requested = false; }
bool geos::util::Interrupt::check () static
Check if an interruption request is pending
Definition at line 38 of file Interrupt.cpp.
 { return requested; }
void geos::util::Interrupt::interrupt () static
Definition at line 56 of file Interrupt.cpp.
                      {
   requested = false;
   throw InterruptedException();
 }
void geos::util::Interrupt::process () static
Invoke the callback, if any. Process pending interruption, if any.
Definition at line 46 of file Interrupt.cpp.
{
     if ( callback ) (*callback)();
     if ( requested ) {
         requested = false;
         interrupt();
     }
 }
Interrupt::Callback * geos::util::Interrupt::registerCallback (Interrupt::Callback * cb) static
Register a callback that will be invoked before checking for interruption requests.
NOTE that interruption request checking may happen frequently so any callback would better be quick.
The callback can be used to call Interrupt::request()
Definition at line 40 of file Interrupt.cpp.
Referenced by GEOS_interruptRegisterCallback().
{
     Callback* prev = callback;
     callback = cb;
     return prev;
   }
void geos::util::Interrupt::request () static
Request interruption of operations
Operations will be terminated by a GEOSInterrupt exception at first occasion.
Definition at line 34 of file Interrupt.cpp.
Referenced by GEOS_interruptRequest().
 { requested = true; }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/util/Interrupt.h
/home/vicky/potree/geos/vicky/src/util/Interrupt.cpp