GEOS: geos::geomgraph::EdgeList Class Reference
geos::geomgraph::EdgeList Class Reference
#include <EdgeList.h>
Classes
struct OcaCmp
Public Member Functions
EdgeList ()
virtual ~EdgeList ()
void add (Edge *e)
void addAll (const std::vector< Edge * > &edgeColl)
std::vector< Edge * > & getEdges ()
Edge * findEqualEdge (Edge *e)
Edge * get (int i)
int findEdgeIndex (Edge *e)
std::string print ()
void clearList ()
Private Types
typedef std::map< noding::OrientedCoordinateArray *, Edge *, OcaCmp > EdgeMap
Private Attributes
std::vector< Edge * > edges
EdgeMap ocaMap
Friends
std::ostream & operator<< (std::ostream &os, const EdgeList &el)
Detailed Description
A EdgeList is a list of Edges.
It supports locating edges that are pointwise equals to a target edge.
Definition at line 58 of file EdgeList.h.
Member Typedef Documentation
typedef std::map<noding::OrientedCoordinateArray*, Edge*, OcaCmp> geos::geomgraph::EdgeList::EdgeMap private
An index of the edges, for fast lookup.
OrientedCoordinateArray objects are owned by us. TODO: optimize by dropping the OrientedCoordinateArray construction as a whole, and use CoordinateSequence directly instead..
Definition at line 81 of file EdgeList.h.
Constructor & Destructor Documentation
geos::geomgraph::EdgeList::EdgeList () inline
Definition at line 87 of file EdgeList.h.
     :
     edges(),
     ocaMap()
   {}
geos::geomgraph::EdgeList::~EdgeList () virtual
Definition at line 147 of file EdgeList.cpp.
 {
   for (EdgeMap::iterator i=ocaMap.begin(), e=ocaMap.end(); i!=e; ++i)
   {
     delete i->first; // OrientedCoordinateArray
   }
 }
Member Function Documentation
void geos::geomgraph::EdgeList::add (Edge * e)
Insert an edge unless it is already in the list
Definition at line 44 of file EdgeList.cpp.
References geos::geomgraph::Edge::getCoordinates().
Referenced by geos::operation::overlay::OverlayOp::insertUniqueEdge().
 {
   edges.push_back(e);
   OrientedCoordinateArray* oca = new OrientedCoordinateArray(*(e->getCoordinates()));
   ocaMap[oca] = e;
 }
void geos::geomgraph::EdgeList::addAll (const std::vector< Edge * > & edgeColl)
Definition at line 52 of file EdgeList.cpp.
 {
     for (std::size_t i=0, s=edgeColl.size(); i<s ; ++i)
   {
     add(edgeColl[i]);
   }
 }
void geos::geomgraph::EdgeList::clearList ()
Definition at line 127 of file EdgeList.cpp.
Referenced by geos::operation::overlay::OverlayOp::computeOverlay().
 {
         for (unsigned int pos=0; pos < edges.size(); pos++)
                 delete *(&edges[pos]);
         edges.clear();
 }
int geos::geomgraph::EdgeList::findEdgeIndex (Edge * e)
If the edge e is already in the list, return its index.
Returns
index, if e is already in the list -1 otherwise
Definition at line 98 of file EdgeList.cpp.
 {
   for (int i=0, s=(int)edges.size(); i<s; ++i)
   {
     if ( edges[i]->equals(e) ) return i;
   }
   return -1;
 }
Edge * geos::geomgraph::EdgeList::findEqualEdge (Edge * e)
If there is an edge equal to e already in the list, return it. Otherwise return null.
Returns
equal edge, if there is one already in the list null otherwise
Definition at line 67 of file EdgeList.cpp.
References geos::geomgraph::Edge::getCoordinates().
Referenced by geos::operation::overlay::OverlayOp::insertUniqueEdge().
 {
 #if PROFILE
   static Profile *prof = profiler->get("EdgeList::findEqualEdge(Edge *e)");
   prof->start();
 #endif
   OrientedCoordinateArray oca(*(e->getCoordinates()));
   EdgeMap::iterator it = ocaMap.find(&oca);
 #if PROFILE
   prof->stop();
 #endif
   if ( it != ocaMap.end() ) return it->second;
   return nullptr;
 }
Edge * geos::geomgraph::EdgeList::get (int i)
Definition at line 87 of file EdgeList.cpp.
 {
   return edges[i];
 }
std::vector<Edge*>& geos::geomgraph::EdgeList::getEdges () inline
Definition at line 102 of file EdgeList.h.
References geos::algorithm::operator<<().
Referenced by geos::operation::overlay::OverlayOp::computeLabelsFromDepths(), geos::operation::overlay::OverlayOp::computeOverlay(), and geos::operation::overlay::OverlayOp::replaceCollapsedEdges().
 { return edges; }
string geos::geomgraph::EdgeList::print ()
Definition at line 108 of file EdgeList.cpp.
References geos::geomgraph::Edge::print().
Referenced by geos::operation::overlay::OverlayOp::computeLabelling().
 {
   ostringstream ss;
   ss << *this;
   return ss.str();
 #if 0
   string out="EdgeList( ";
   for(unsigned int j=0, s=edges.size(); j<s; ++j)
   {
           Edge *e=edges[j];
     if (j) out+=",";
     out += e->print();
   }
   out+=")  ";
   return out;
 #endif
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const EdgeList & el) friend
Definition at line 136 of file EdgeList.cpp.
 {
   os << "EdgeList: " << std::endl;
   for(std::size_t j=0, s=el.edges.size(); j<s; ++j)
   {
           Edge *e=el.edges[j];
     os << "  " << *e << std::endl;
   }
   return os;
 }
Member Data Documentation
std::vector<Edge*> geos::geomgraph::EdgeList::edges private
Definition at line 62 of file EdgeList.h.
Referenced by geos::geomgraph::operator<<().
EdgeMap geos::geomgraph::EdgeList::ocaMap private
Definition at line 82 of file EdgeList.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/EdgeList.h
/home/vicky/potree/geos/vicky/src/geomgraph/EdgeList.cpp