GEOS: geos::index::strtree::STRAbstractNode Class Reference
geos::index::strtree::STRAbstractNode Class Reference
Public Member Functions
STRAbstractNode (int level, int capacity)
~STRAbstractNode () override
std::vector< Boundable * > * getChildBoundables ()
const std::vector< Boundable * > * getChildBoundables () const
const void * getBounds () const override
int getLevel ()
void addChildBoundable (Boundable *childBoundable)
Protected Member Functions
void * computeBounds () const override
Protected Attributes
void * bounds
Detailed Description
Definition at line 277 of file STRtree.cpp.
Constructor & Destructor Documentation
geos::index::strtree::STRAbstractNode::STRAbstractNode (int level, int capacity) inline
Definition at line 280 of file STRtree.cpp.
     :
     AbstractNode(level, capacity)
   {}
geos::index::strtree::STRAbstractNode::~STRAbstractNode () inline override
Definition at line 285 of file STRtree.cpp.
   {
     delete (Envelope *)bounds;
   }
Member Function Documentation
void geos::index::strtree::AbstractNode::addChildBoundable (Boundable * childBoundable) inherited
Adds either an AbstractNode, or if this is a leaf node, a data object (wrapped in an ItemBoundable)
Definition at line 63 of file AbstractNode.cpp.
Referenced by geos::index::strtree::SIRtree::createParentBoundables(), and geos::index::strtree::AbstractSTRtree::createParentBoundables().
{
   assert(bounds==nullptr);
   childBoundables.push_back(childBoundable);
 }
void* geos::index::strtree::STRAbstractNode::computeBounds () const inline override protected virtual
Implements geos::index::strtree::AbstractNode.
Definition at line 292 of file STRtree.cpp.
References geos::geom::Envelope::expandToInclude(), and geos::index::strtree::Boundable::getBounds().
   {
     Envelope* bounds=nullptr;
     const BoundableList& b = *getChildBoundables();
     if ( b.empty() ) return nullptr;
     BoundableList::const_iterator i=b.begin();
     BoundableList::const_iterator e=b.end();
     bounds=new Envelope(* static_cast<const Envelope*>((*i)->getBounds()) );
     for(; i!=e; ++i)
     {
       const Boundable* childBoundable=*i;
       bounds->expandToInclude((Envelope*)childBoundable->getBounds());
     }
     return bounds;
   }
const void * geos::index::strtree::AbstractNode::getBounds () const override virtual inherited
Returns a representation of space that encloses this Boundable, preferably not much bigger than this Boundable's boundary yet fast to test for intersection with the bounds of other Boundables. The class of object returned depends on the subclass of AbstractSTRtree.
Returns
an Envelope (for STRtrees), an Interval (for SIRtrees), or other object (for other subclasses of AbstractSTRtree)
See also
AbstractSTRtree::IntersectsOp
Implements geos::index::strtree::Boundable.
Definition at line 43 of file AbstractNode.cpp.
 {
   if (bounds==nullptr) {
     bounds = computeBounds();
   }
   return bounds;
 }
std::vector<Boundable*>* geos::index::strtree::AbstractNode::getChildBoundables () inline inherited
Definition at line 52 of file AbstractNode.h.
Referenced by geos::index::strtree::AbstractSTRtree::boundablesAtLevel(), geos::index::strtree::SIRtree::createParentBoundables(), geos::index::strtree::AbstractSTRtree::createParentBoundables(), geos::index::strtree::AbstractSTRtree::itemsTree(), geos::index::strtree::AbstractSTRtree::query(), geos::index::strtree::AbstractSTRtree::remove(), and geos::index::strtree::AbstractSTRtree::removeItem().
{
     return &childBoundables;
   }
const std::vector<Boundable*>* geos::index::strtree::AbstractNode::getChildBoundables () const inline inherited
Definition at line 58 of file AbstractNode.h.
{
     return &childBoundables;
   }
int geos::index::strtree::AbstractNode::getLevel () inherited
Returns 0 if this node is a leaf, 1 if a parent of a leaf, and so on; the root node will have the highest level
Definition at line 55 of file AbstractNode.cpp.
Referenced by geos::index::strtree::AbstractSTRtree::boundablesAtLevel().
{
   return level;
 }
Member Data Documentation
void* geos::index::strtree::AbstractNode::bounds mutable protected inherited
Definition at line 84 of file AbstractNode.h.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/index/strtree/STRtree.cpp