GEOS: geos::geomgraph::index::SweepLineEvent Class Reference
geos::geomgraph::index::SweepLineEvent Class Reference
#include <SweepLineEvent.h>
Public Types
enum { INSERT_EVENT = 1, DELETE_EVENT }
Public Member Functions
SweepLineEvent (void *newEdgeSet, double x, SweepLineEvent *newInsertEvent, SweepLineEventOBJ *newObj)
virtual ~SweepLineEvent ()
bool isInsert ()
bool isDelete ()
SweepLineEvent * getInsertEvent ()
int getDeleteEventIndex ()
void setDeleteEventIndex (int newDeleteEventIndex)
SweepLineEventOBJ * getObject () const
int compareTo (SweepLineEvent *sle)
std::string print ()
Public Attributes
void * edgeSet
Protected Attributes
SweepLineEventOBJ * obj
Private Attributes
double xValue
int eventType
SweepLineEvent * insertEvent
int deleteEventIndex
Friends
class SweepLineEventLessThen
Detailed Description
Definition at line 38 of file SweepLineEvent.h.
Member Enumeration Documentation
anonymous enum
Enumerator
INSERT_EVENT
DELETE_EVENT
Definition at line 43 of file SweepLineEvent.h.
        {
     INSERT_EVENT = 1,
     DELETE_EVENT
   };
Constructor & Destructor Documentation
geos::geomgraph::index::SweepLineEvent::SweepLineEvent (void * newEdgeSet, double x, SweepLineEvent * newInsertEvent, SweepLineEventOBJ * newObj)
Definition at line 27 of file SweepLineEvent.cpp.
References DELETE_EVENT, eventType, INSERT_EVENT, and insertEvent.
                                                             :
     edgeSet(newEdgeSet),
     obj(newObj),
     xValue(x),
     insertEvent(newInsertEvent),
     deleteEventIndex(0)
 {
   if(insertEvent!=nullptr) eventType=DELETE_EVENT;
   else eventType=INSERT_EVENT;
 }
geos::geomgraph::index::SweepLineEvent::~SweepLineEvent () virtual
Definition at line 39 of file SweepLineEvent.cpp.
References DELETE_EVENT, eventType, insertEvent, and obj.
{
   if (eventType==DELETE_EVENT) {
     delete insertEvent;
     delete obj;
   }
 }
Member Function Documentation
int geos::geomgraph::index::SweepLineEvent::compareTo (SweepLineEvent * sle)
ProjectionEvents are ordered first by their x-value, and then by their eventType. It is important that Insert events are sorted before Delete events, so that items whose Insert and Delete events occur at the same x-value will be correctly handled.
Definition at line 54 of file SweepLineEvent.cpp.
References eventType, and xValue.
 {
   if (xValue<sle->xValue) return -1;
   if (xValue>sle->xValue) return 1;
   if (eventType<sle->eventType) return -1;
   if (eventType>sle->eventType) return 1;
   return 0;
 }
int geos::geomgraph::index::SweepLineEvent::getDeleteEventIndex () inline
Definition at line 60 of file SweepLineEvent.h.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::computeIntersections(), and geos::geomgraph::index::SimpleMCSweepLineIntersector::computeIntersections().
 { return deleteEventIndex; }
SweepLineEvent* geos::geomgraph::index::SweepLineEvent::getInsertEvent () inline
Definition at line 58 of file SweepLineEvent.h.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::prepareEvents(), and geos::geomgraph::index::SimpleMCSweepLineIntersector::prepareEvents().
 { return insertEvent; }
SweepLineEventOBJ* geos::geomgraph::index::SweepLineEvent::getObject () const inline
Definition at line 66 of file SweepLineEvent.h.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::processOverlaps(), and geos::geomgraph::index::SimpleMCSweepLineIntersector::processOverlaps().
 { return obj; }
bool geos::geomgraph::index::SweepLineEvent::isDelete () inline
Definition at line 56 of file SweepLineEvent.h.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::prepareEvents(), geos::geomgraph::index::SimpleMCSweepLineIntersector::prepareEvents(), and geos::geomgraph::index::SimpleMCSweepLineIntersector::~SimpleMCSweepLineIntersector().
 { return insertEvent!=nullptr; }
bool geos::geomgraph::index::SweepLineEvent::isInsert () inline
Definition at line 54 of file SweepLineEvent.h.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::computeIntersections(), geos::geomgraph::index::SimpleMCSweepLineIntersector::computeIntersections(), geos::geomgraph::index::SimpleSweepLineIntersector::processOverlaps(), and geos::geomgraph::index::SimpleMCSweepLineIntersector::processOverlaps().
 { return insertEvent==nullptr; }
string geos::geomgraph::index::SweepLineEvent::print ()
Definition at line 64 of file SweepLineEvent.cpp.
References deleteEventIndex, eventType, INSERT_EVENT, insertEvent, print(), and xValue.
Referenced by print().
 {
   ostringstream s;
   s<<"SweepLineEvent:";
   s<<" xValue="<<xValue<<" deleteEventIndex="<<deleteEventIndex;
   s<<( (eventType==INSERT_EVENT) ? " INSERT_EVENT" : " DELETE_EVENT" );
   s<<endl<<"\tinsertEvent=";
   if (insertEvent) s<<insertEvent->print();
   else s<<"NULL";
   return s.str();
 }
void geos::geomgraph::index::SweepLineEvent::setDeleteEventIndex (int newDeleteEventIndex) inline
Definition at line 62 of file SweepLineEvent.h.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::prepareEvents(), and geos::geomgraph::index::SimpleMCSweepLineIntersector::prepareEvents().
{
     deleteEventIndex=newDeleteEventIndex;
   }
Friends And Related Function Documentation
friend class SweepLineEventLessThen friend
Definition at line 39 of file SweepLineEvent.h.
Member Data Documentation
int geos::geomgraph::index::SweepLineEvent::deleteEventIndex private
Definition at line 86 of file SweepLineEvent.h.
Referenced by print().
void* geos::geomgraph::index::SweepLineEvent::edgeSet
Definition at line 72 of file SweepLineEvent.h.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::processOverlaps(), and geos::geomgraph::index::SimpleMCSweepLineIntersector::processOverlaps().
int geos::geomgraph::index::SweepLineEvent::eventType private
Definition at line 82 of file SweepLineEvent.h.
Referenced by compareTo(), geos::geomgraph::index::SweepLineEventLessThen::operator()(), print(), SweepLineEvent(), and ~SweepLineEvent().
SweepLineEvent* geos::geomgraph::index::SweepLineEvent::insertEvent private
Definition at line 84 of file SweepLineEvent.h.
Referenced by print(), SweepLineEvent(), and ~SweepLineEvent().
SweepLineEventOBJ* geos::geomgraph::index::SweepLineEvent::obj protected
Definition at line 76 of file SweepLineEvent.h.
Referenced by ~SweepLineEvent().
double geos::geomgraph::index::SweepLineEvent::xValue private
Definition at line 80 of file SweepLineEvent.h.
Referenced by compareTo(), geos::geomgraph::index::SweepLineEventLessThen::operator()(), and print().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/index/SweepLineEvent.h
/home/vicky/potree/geos/vicky/src/geomgraph/index/SweepLineEvent.cpp