GEOS: geos::geom::GeometryFilter Class Reference
geos::geom::GeometryFilter Class Reference
Geometry classes support the concept of applying a Geometry filter to the Geometry.
#include <GeometryFilter.h>
Public Member Functions
virtual void filter_ro (const Geometry *)
virtual void filter_rw (Geometry *)
virtual ~GeometryFilter ()
Detailed Description
Geometry classes support the concept of applying a Geometry filter to the Geometry.
In the case of GeometryCollection subclasses, the filter is applied to every element Geometry. A Geometry filter can either record information about the Geometry or change the Geometry in some way. Geometry filters implement the interface GeometryFilter. (GeometryFilter is an example of the Gang-of-Four Visitor pattern).
Definition at line 48 of file GeometryFilter.h.
Constructor & Destructor Documentation
virtual geos::geom::GeometryFilter::~GeometryFilter () inline virtual
Definition at line 63 of file GeometryFilter.h.
 {}
Member Function Documentation
virtual void geos::geom::GeometryFilter::filter_ro (const Geometry *) inline virtual
Reimplemented in geos::geom::util::GeometryExtracter::Extracter< ComponentType, TargetContainer >, geos::operation::distance::ConnectedElementLocationFilter, geos::operation::distance::ConnectedElementPointFilter, geos::geom::util::PolygonExtracter, and geos::geom::util::PointExtracter.
Definition at line 60 of file GeometryFilter.h.
Referenced by geos::geom::Point::apply_ro(), geos::geom::Polygon::apply_ro(), geos::geom::GeometryCollection::apply_ro(), geos::geom::LineString::apply_ro(), and geos::geom::Geometry::apply_ro().
 { assert(0); }
virtual void geos::geom::GeometryFilter::filter_rw (Geometry *) inline virtual
Reimplemented in geos::operation::distance::ConnectedElementLocationFilter, geos::geom::util::PolygonExtracter, and geos::geom::util::PointExtracter.
Definition at line 61 of file GeometryFilter.h.
Referenced by geos::geom::Point::apply_rw(), geos::geom::Polygon::apply_rw(), geos::geom::GeometryCollection::apply_rw(), geos::geom::LineString::apply_rw(), and geos::geom::Geometry::apply_rw().
 { assert(0); }
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/geom/GeometryFilter.h