GEOS: geos::index::bintree::Bintree Class Reference
geos::index::bintree::Bintree Class Reference
An BinTree (or "Binary Interval Tree") is a 1-dimensional version of a quadtree.
#include <Bintree.h>
Public Member Functions
Bintree ()
~Bintree ()
int depth ()
int size ()
int nodeSize ()
void insert (Interval *itemInterval, void *item)
std::vector< void * > * iterator ()
std::vector< void * > * query (double x)
std::vector< void * > * query (Interval *interval)
void query (Interval *interval, std::vector< void * > *foundItems)
Static Public Member Functions
static Interval * ensureExtent (const Interval *itemInterval, double minExtent)
Private Member Functions
void collectStats (Interval *interval)
Private Attributes
std::vector< Interval * > newIntervals
Root * root
double minExtent
Detailed Description
An BinTree (or "Binary Interval Tree") is a 1-dimensional version of a quadtree.
It indexes 1-dimensional intervals (which of course may be the projection of 2-D objects on an axis). It supports range searching (where the range may be a single point).
This implementation does not require specifying the extent of the inserted items beforehand. It will automatically expand to accomodate any extent of dataset.
This index is different to the Interval Tree of Edelsbrunner or the Segment Tree of Bentley.
Definition at line 56 of file Bintree.h.
Constructor & Destructor Documentation
geos::index::bintree::Bintree::Bintree ()
Definition at line 53 of file Bintree.cpp.
 {
   minExtent=1.0;
   root=new Root();
 }
geos::index::bintree::Bintree::~Bintree ()
Definition at line 59 of file Bintree.cpp.
 {
   for (unsigned int i=0; i<newIntervals.size(); i++)
     delete newIntervals[i];
   delete root;
 }
Member Function Documentation
void geos::index::bintree::Bintree::collectStats (Interval * interval) private
Definition at line 143 of file Bintree.cpp.
References geos::index::bintree::Interval::getWidth().
 {
   double del=interval->getWidth();
   if (del<minExtent && del>0.0)
     minExtent=del;
 }
int geos::index::bintree::Bintree::depth ()
Definition at line 67 of file Bintree.cpp.
 {
   if (root!=nullptr) return root->depth();
   return 0;
 }
Interval * geos::index::bintree::Bintree::ensureExtent (const Interval * itemInterval, double minExtent) static
Ensure that the Interval for the inserted item has non-zero extents. Use the current minExtent to pad it, if necessary
NOTE: in GEOS this function always return a newly allocated object with ownership transferred to caller. TODO: change this ?
Parameters
itemInterval Source interval, ownership left to caller, no references hold.
Definition at line 29 of file Bintree.cpp.
References geos::index::bintree::Interval::getMax(), and geos::index::bintree::Interval::getMin().
 {
   double min = itemInterval->getMin();
   double max = itemInterval->getMax();
   // has a non-zero extent
   if (min != max)
   {
     // GEOS forces a copy here to be predictable wrt
     // memory management. May change in the future.
     return new Interval(*itemInterval);
   }
   // pad extent
   if (min==max)
   {
     min = min-minExtent/2.0;
     max = min+minExtent/2.0;
   }
   return new Interval(min, max);
 }
void geos::index::bintree::Bintree::insert (Interval * itemInterval, void * item)
Parameters
itemInterval Ownership left to caller, NO reference hold by this class.
item Ownership left to caller, reference kept by this class.
Definition at line 93 of file Bintree.cpp.
Referenced by geos::algorithm::MCPointInRing::buildIndex().
 {
   collectStats(itemInterval);
   Interval *insertInterval=ensureExtent(itemInterval,minExtent);
   if ( insertInterval != itemInterval )
     newIntervals.push_back(insertInterval);
   //int oldSize=size();
   root->insert(insertInterval,item);
   /* GEOS_DEBUG
   int newSize=size();
   System.out.println("BinTree: size="+newSize+"   node size="+nodeSize());
   if (newSize <= oldSize) {
   System.out.println("Lost item!");
   root.insert(insertInterval, item);
   System.out.println("reinsertion size="+size());
   }
   */
 }
vector< void * > * geos::index::bintree::Bintree::iterator ()
Definition at line 113 of file Bintree.cpp.
{
   vector<void*>* foundItems=new vector<void*>();
   root->addAllItems(foundItems);
   return foundItems;
 }
int geos::index::bintree::Bintree::nodeSize ()
Compute the total number of nodes in the tree
Returns
the number of nodes in the tree
Definition at line 86 of file Bintree.cpp.
 {
   if (root!=nullptr) return root->nodeSize();
   return 0;
 }
vector< void * > * geos::index::bintree::Bintree::query (double x)
Definition at line 119 of file Bintree.cpp.
Referenced by geos::algorithm::MCPointInRing::isInside().
{
   return query(new Interval(x, x));
 }
vector< void * > * geos::index::bintree::Bintree::query (Interval * interval)
min and max may be the same value
the items that are matched are all items in intervals which overlap the query interval
Definition at line 126 of file Bintree.cpp.
{
   vector<void*>* foundItems=new vector<void*>();
   query(interval,foundItems);
   return foundItems;
 }
void geos::index::bintree::Bintree::query (Interval * interval, std::vector< void * > * foundItems)
Definition at line 137 of file Bintree.cpp.
 {
   root->addAllItemsFromOverlapping(interval,foundItems);
 }
int geos::index::bintree::Bintree::size ()
Definition at line 74 of file Bintree.cpp.
 {
   if (root!=nullptr) return root->size();
   return 0;
 }
Member Data Documentation
double geos::index::bintree::Bintree::minExtent private
Statistics
minExtent is the minimum extent of all items inserted into the tree so far. It is used as a heuristic value to construct non-zero extents for features with zero extent. Start with a non-zero extent, in case the first feature inserted has a zero extent in both directions. This value may be non-optimal, but only one feature will be inserted with this value.
Definition at line 116 of file Bintree.h.
std::vector<Interval *> geos::index::bintree::Bintree::newIntervals private
Definition at line 102 of file Bintree.h.
Root* geos::index::bintree::Bintree::root private
Definition at line 104 of file Bintree.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/bintree/Bintree.h
/home/vicky/potree/geos/vicky/src/index/bintree/Bintree.cpp