GEOS: geos::geomgraph::index::SweepLineSegment Class Reference
geos::geomgraph::index::SweepLineSegment Class Reference
#include <SweepLineSegment.h>
Public Member Functions
SweepLineSegment (Edge *newEdge, int newPtIndex)
~SweepLineSegment () override
double getMinX ()
double getMaxX ()
void computeIntersections (SweepLineSegment *ss, SegmentIntersector *si)
Protected Attributes
Edge * edge
const geom::CoordinateSequence * pts
int ptIndex
Detailed Description
Definition at line 40 of file SweepLineSegment.h.
Constructor & Destructor Documentation
geos::geomgraph::index::SweepLineSegment::SweepLineSegment (Edge * newEdge, int newPtIndex)
Definition at line 28 of file SweepLineSegment.cpp.
                                                                :
   edge(newEdge),
   pts(newEdge->getCoordinates()),
   ptIndex(newPtIndex)
 {
   //pts=newEdge->getCoordinates();
   //edge=newEdge;
   //ptIndex=newPtIndex;
 }
geos::geomgraph::index::SweepLineSegment::~SweepLineSegment () override
Definition at line 38 of file SweepLineSegment.cpp.
 {
 }
Member Function Documentation
void geos::geomgraph::index::SweepLineSegment::computeIntersections (SweepLineSegment * ss, SegmentIntersector * si)
Definition at line 59 of file SweepLineSegment.cpp.
References geos::geomgraph::index::SegmentIntersector::addIntersections(), edge, and ptIndex.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::processOverlaps().
 {
   si->addIntersections(edge, ptIndex, ss->edge, ss->ptIndex);
 }
double geos::geomgraph::index::SweepLineSegment::getMaxX ()
Definition at line 51 of file SweepLineSegment.cpp.
References geos::geom::CoordinateSequence::getAt(), ptIndex, pts, and geos::geom::Coordinate::x.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::add().
 {
   double x1=pts->getAt(ptIndex).x;
   double x2=pts->getAt(ptIndex+1).x;
   return x1>x2?x1:x2;
 }
double geos::geomgraph::index::SweepLineSegment::getMinX ()
Definition at line 43 of file SweepLineSegment.cpp.
References geos::geom::CoordinateSequence::getAt(), ptIndex, pts, and geos::geom::Coordinate::x.
Referenced by geos::geomgraph::index::SimpleSweepLineIntersector::add().
 {
   double x1=pts->getAt(ptIndex).x;
   double x2=pts->getAt(ptIndex+1).x;
   return x1<x2?x1:x2;
 }
Member Data Documentation
Edge* geos::geomgraph::index::SweepLineSegment::edge protected
Definition at line 48 of file SweepLineSegment.h.
Referenced by computeIntersections().
int geos::geomgraph::index::SweepLineSegment::ptIndex protected
Definition at line 50 of file SweepLineSegment.h.
Referenced by computeIntersections(), getMaxX(), and getMinX().
const geom::CoordinateSequence* geos::geomgraph::index::SweepLineSegment::pts protected
Definition at line 49 of file SweepLineSegment.h.
Referenced by getMaxX(), and getMinX().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/index/SweepLineSegment.h
/home/vicky/potree/geos/vicky/src/geomgraph/index/SweepLineSegment.cpp