GEOS: geos::operation::overlay::snap::GeometrySnapper Class Reference
geos::operation::overlay::snap::GeometrySnapper Class Reference
Snaps the vertices and segments of a Geometry to another Geometry's vertices.
#include <GeometrySnapper.h>
Public Types
typedef std::unique_ptr< geom::Geometry > GeomPtr
Public Member Functions
GeometrySnapper (const geom::Geometry &g)
std::unique_ptr< geom::Geometry > snapTo (const geom::Geometry &g, double snapTolerance)
Snaps the vertices in the component LineStrings of the source geometry to the vertices of the given snap geometry with a given snap tolerance.
std::unique_ptr< geom::Geometry > snapToSelf (double snapTolerance, bool cleanResult)
Snaps the vertices in the component LineStrings of the source geometry to the vertices of itself with a given snap tolerance and optionally cleaning the result.
Static Public Member Functions
static void snap (const geom::Geometry &g0, const geom::Geometry &g1, double snapTolerance, geom::GeomPtrPair &ret)
static GeomPtr snapToSelf (const geom::Geometry &g0, double snapTolerance, bool cleanResult)
static double computeOverlaySnapTolerance (const geom::Geometry &g)
Estimates the snap tolerance for a Geometry, taking into account its precision model.
static double computeSizeBasedSnapTolerance (const geom::Geometry &g)
static double computeOverlaySnapTolerance (const geom::Geometry &g1, const geom::Geometry &g2)
Computes the snap tolerance based on input geometries;.
Private Member Functions
std::unique_ptr< geom::Coordinate::ConstVect > extractTargetCoordinates (const geom::Geometry &g)
Extract target (unique) coordinates.
GeometrySnapper (const GeometrySnapper &other)=delete
GeometrySnapper & operator= (const GeometrySnapper &rhs)=delete
Private Attributes
const geom::Geometry & srcGeom
Static Private Attributes
static const double snapPrecisionFactor = 1e-9
Detailed Description
Snaps the vertices and segments of a Geometry to another Geometry's vertices.
A snap distance tolerance is used to control where snapping is performed. Snapping one geometry to another can improve robustness for overlay operations by eliminating nearly-coincident edges (which cause problems during noding and intersection calculation). Too much snapping can result in invalid topology being created, so the number and location of snapped vertices is decided using heuristics to determine when it is safe to snap. This can result in some potential snaps being omitted, however.
Definition at line 58 of file GeometrySnapper.h.
Member Typedef Documentation
typedef std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::GeometrySnapper::GeomPtr
Definition at line 62 of file GeometrySnapper.h.
Constructor & Destructor Documentation
geos::operation::overlay::snap::GeometrySnapper::GeometrySnapper (const geom::Geometry & g) inline
Creates a new snapper acting on the given geometry
Parameters
g the geometry to snap
Definition at line 85 of file GeometrySnapper.h.
     :
     srcGeom(g)
   {
   }
geos::operation::overlay::snap::GeometrySnapper::GeometrySnapper (const GeometrySnapper & other) private delete
Member Function Documentation
double geos::operation::overlay::snap::GeometrySnapper::computeOverlaySnapTolerance (const geom::Geometry & g) static
Estimates the snap tolerance for a Geometry, taking into account its precision model.
Parameters
g a Geometry
Returns
the estimated snap tolerance
Overlay is carried out in the precision model of the two inputs. If this precision model is of type FIXED, then the snap tolerance must reflect the precision grid size. Specifically, the snap tolerance should be at least the distance from a corner of a precision grid cell to the centre point of the cell.
Definition at line 158 of file GeometrySnapper.cpp.
References geos::geom::PrecisionModel::FIXED, and geos::geom::Geometry::getPrecisionModel().
 {
   double snapTolerance = computeSizeBasedSnapTolerance(g);
   assert(g.getPrecisionModel());
   const PrecisionModel& pm = *(g.getPrecisionModel());
   if (pm.getType() == PrecisionModel::FIXED)
   {
     double fixedSnapTol = (1 / pm.getScale()) * 2 / 1.415;
     if ( fixedSnapTol > snapTolerance )
       snapTolerance = fixedSnapTol;
   }
   return snapTolerance;
 }
double geos::operation::overlay::snap::GeometrySnapper::computeOverlaySnapTolerance (const geom::Geometry & g1, const geom::Geometry & g2) static
Computes the snap tolerance based on input geometries;.
Definition at line 184 of file GeometrySnapper.cpp.
 {
         return std::min(computeOverlaySnapTolerance(g1), computeOverlaySnapTolerance(g2));
 }
double geos::operation::overlay::snap::GeometrySnapper::computeSizeBasedSnapTolerance (const geom::Geometry & g) static
Definition at line 148 of file GeometrySnapper.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::getHeight(), and geos::geom::Envelope::getWidth().
 {
   const Envelope* env = g.getEnvelopeInternal();
   double minDimension = std::min(env->getHeight(), env->getWidth());
   double snapTol = minDimension * snapPrecisionFactor;
   return snapTol;
 }
std::unique_ptr< Coordinate::ConstVect > geos::operation::overlay::snap::GeometrySnapper::extractTargetCoordinates (const geom::Geometry & g) private
Extract target (unique) coordinates.
Definition at line 92 of file GeometrySnapper.cpp.
References geos::geom::Geometry::apply_ro(), and geos::geom::Geometry::getNumPoints().
 {
   std::unique_ptr<Coordinate::ConstVect> snapPts(new Coordinate::ConstVect());
   util::UniqueCoordinateArrayFilter filter(*snapPts);
   g.apply_ro(&filter);
   // integrity check
   assert( snapPts->size() <= g.getNumPoints() );
   return snapPts;
 }
GeometrySnapper& geos::operation::overlay::snap::GeometrySnapper::operator= (const GeometrySnapper & rhs) private delete
void geos::operation::overlay::snap::GeometrySnapper::snap (const geom::Geometry & g0, const geom::Geometry & g1, double snapTolerance, geom::GeomPtrPair & ret) static
Snaps two geometries together with a given tolerance.
Parameters
g0 a geometry to snap
g1 a geometry to snap
snapTolerance the tolerance to use
ret the snapped geometries as a pair of smart pointers (output parameter)
Snap the second geometry to the snapped first geometry (this strategy minimizes the number of possible different points in the result)
Definition at line 192 of file GeometrySnapper.cpp.
References geos::geom::GeomPtrPair::first, geos::geom::GeomPtrPair::second, and snapTo().
 {
   GeometrySnapper snapper0(g0);
   snapGeom.first = snapper0.snapTo(g1, snapTolerance);
   GeometrySnapper snapper1(g1);
   snapGeom.second = snapper1.snapTo(*snapGeom.first, snapTolerance);
 //  cout << *snapGeom.first << endl;
 //  cout << *snapGeom.second << endl;
 }
std::unique_ptr< geom::Geometry > geos::operation::overlay::snap::GeometrySnapper::snapTo (const geom::Geometry & g, double snapTolerance)
Snaps the vertices in the component LineStrings of the source geometry to the vertices of the given snap geometry with a given snap tolerance.
Parameters
g a geometry to snap the source to
snapTolerance
Returns
a new snapped Geometry
Definition at line 104 of file GeometrySnapper.cpp.
Referenced by GEOSSnap_r(), and snap().
 {
   using std::unique_ptr;
   using geom::util::GeometryTransformer;
   // Get snap points
   unique_ptr<Coordinate::ConstVect> snapPts=extractTargetCoordinates(g);
   // Apply a SnapTransformer to source geometry
   // (we need a pointer for dynamic polymorphism)
   unique_ptr<GeometryTransformer> snapTrans(new SnapTransformer(snapTolerance, *snapPts));
   return snapTrans->transform(&srcGeom);
 }
GeometrySnapper::GeomPtr geos::operation::overlay::snap::GeometrySnapper::snapToSelf (const geom::Geometry & g0, double snapTolerance, bool cleanResult) static
Definition at line 215 of file GeometrySnapper.cpp.
References snapToSelf().
Referenced by snapToSelf().
 {
   GeometrySnapper snapper0(g);
   return snapper0.snapToSelf(snapTolerance, cleanResult);
 }
std::unique_ptr< geom::Geometry > geos::operation::overlay::snap::GeometrySnapper::snapToSelf (double snapTolerance, bool cleanResult)
Snaps the vertices in the component LineStrings of the source geometry to the vertices of itself with a given snap tolerance and optionally cleaning the result.
Parameters
snapTolerance
cleanResult clean the result
Returns
a new snapped Geometry
Definition at line 121 of file GeometrySnapper.cpp.
 {
   using std::unique_ptr;
   using geom::util::GeometryTransformer;
   // Get snap points
   unique_ptr<Coordinate::ConstVect> snapPts=extractTargetCoordinates(srcGeom);
   // Apply a SnapTransformer to source geometry
   // (we need a pointer for dynamic polymorphism)
   unique_ptr<GeometryTransformer> snapTrans(new SnapTransformer(snapTolerance, *snapPts));
   GeomPtr result = snapTrans->transform(&srcGeom);
   if (cleanResult && ( dynamic_cast<const Polygon*>(result.get()) ||
                        dynamic_cast<const MultiPolygon*>(result.get()) ) )
   {
     // TODO: use better cleaning approach
     result.reset(result->buffer(0));
   }
   return result;
 }
Member Data Documentation
const double geos::operation::overlay::snap::GeometrySnapper::snapPrecisionFactor = 1e-9 static private
Definition at line 138 of file GeometrySnapper.h.
const geom::Geometry& geos::operation::overlay::snap::GeometrySnapper::srcGeom private
Definition at line 140 of file GeometrySnapper.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/snap/GeometrySnapper.h
/home/vicky/potree/geos/vicky/src/operation/overlay/snap/GeometrySnapper.cpp