GEOS: geos::index::bintree::Key Class Reference
geos::index::bintree::Key Class Reference
A Key is a unique identifier for a node in a tree.
#include <Key.h>
Public Member Functions
Key (Interval *newInterval)
~Key ()
double getPoint ()
int getLevel ()
Interval * getInterval ()
void computeKey (Interval *itemInterval)
Static Public Member Functions
static int computeLevel (Interval *newInterval)
Private Member Functions
void computeInterval (int level, Interval *itemInterval)
Private Attributes
double pt
int level
Interval * interval
Detailed Description
A Key is a unique identifier for a node in a tree.
It contains a lower-left point and a level number. The level number is the power of two for the size of the node envelope
Definition at line 39 of file Key.h.
Constructor & Destructor Documentation
geos::index::bintree::Key::Key (Interval * newInterval)
Definition at line 36 of file Key.cpp.
References computeKey(), interval, level, and pt.
 {
   interval=nullptr;
   pt=0.0;
   level=0;
   computeKey(newInterval);
 }
geos::index::bintree::Key::~Key ()
Definition at line 44 of file Key.cpp.
References interval.
 {
   delete interval;
 }
Member Function Documentation
void geos::index::bintree::Key::computeInterval (int level, Interval * itemInterval) private
Definition at line 86 of file Key.cpp.
References geos::index::bintree::Interval::getMin(), geos::index::bintree::Interval::init(), interval, and pt.
Referenced by computeKey().
 {
   using geos::index::quadtree::DoubleBits;
   double size=DoubleBits::powerOf2(level);
   //double size = pow2.power(level);
   pt=std::floor(itemInterval->getMin()/size)*size;
   interval->init(pt,pt+size);
 }
void geos::index::bintree::Key::computeKey (Interval * itemInterval)
return a square envelope containing the argument envelope, whose extent is a power of two and which is based at a power of 2
Definition at line 72 of file Key.cpp.
References computeInterval(), computeLevel(), geos::index::bintree::Interval::contains(), interval, and level.
Referenced by Key().
 {
   level=computeLevel(itemInterval);
   delete interval;
   interval=new Interval();
   computeInterval(level,itemInterval);
   // MD - would be nice to have a non-iterative form of this algorithm
   while (!interval->contains(itemInterval)) {
     level+=1;
     computeInterval(level,itemInterval);
   }
 }
int geos::index::bintree::Key::computeLevel (Interval * newInterval) static
Definition at line 27 of file Key.cpp.
References geos::index::bintree::Interval::getWidth(), and level.
Referenced by computeKey().
 {
   using geos::index::quadtree::DoubleBits;
   double dx=newInterval->getWidth();
   //int level = BinaryPower.exponent(dx) + 1;
   int level=DoubleBits::exponent(dx)+1;
   return level;
 }
Interval * geos::index::bintree::Key::getInterval ()
Definition at line 62 of file Key.cpp.
References interval.
Referenced by geos::index::bintree::Node::createNode().
 {
   return interval;
 }
int geos::index::bintree::Key::getLevel ()
Definition at line 56 of file Key.cpp.
References level.
Referenced by geos::index::bintree::Node::createNode().
 {
   return level;
 }
double geos::index::bintree::Key::getPoint ()
Definition at line 50 of file Key.cpp.
References pt.
 {
   return pt;
 }
Member Data Documentation
Interval* geos::index::bintree::Key::interval private
Definition at line 64 of file Key.h.
Referenced by computeInterval(), computeKey(), getInterval(), Key(), and ~Key().
int geos::index::bintree::Key::level private
Definition at line 61 of file Key.h.
Referenced by computeKey(), computeLevel(), getLevel(), and Key().
double geos::index::bintree::Key::pt private
Definition at line 60 of file Key.h.
Referenced by computeInterval(), getPoint(), and Key().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/bintree/Key.h
/home/vicky/potree/geos/vicky/src/index/bintree/Key.cpp