GEOS: geos::geom::prep::PreparedPolygonPredicate Class Reference
geos::geom::prep::PreparedPolygonPredicate Class Reference
A base class for predicate operations on PreparedPolygons.
#include <PreparedPolygonPredicate.h>
Public Member Functions
PreparedPolygonPredicate (const PreparedPolygon *const prepPoly)
virtual ~PreparedPolygonPredicate ()
Protected Member Functions
bool isAllTestComponentsInTarget (const geom::Geometry *testGeom) const
Tests whether all components of the test Geometry are contained in the target geometry.
bool isAllTestComponentsInTargetInterior (const geom::Geometry *testGeom) const
Tests whether all components of the test Geometry are contained in the interior of the target geometry.
bool isAnyTestComponentInTarget (const geom::Geometry *testGeom) const
Tests whether any component of the test Geometry intersects the area of the target geometry.
bool isAnyTestComponentInTargetInterior (const geom::Geometry *testGeom) const
Tests whether any component of the test Geometry intersects the interior of the target geometry.
bool isAnyTargetComponentInAreaTest (const geom::Geometry *testGeom, const geom::Coordinate::ConstVect *targetRepPts) const
Protected Attributes
const PreparedPolygon *const prepPoly
Private Member Functions
PreparedPolygonPredicate (const PreparedPolygonPredicate &other)=delete
PreparedPolygonPredicate & operator= (const PreparedPolygonPredicate &rhs)=delete
Detailed Description
A base class for predicate operations on PreparedPolygons.
Author
mbdavis
Definition at line 57 of file PreparedPolygonPredicate.h.
Constructor & Destructor Documentation
geos::geom::prep::PreparedPolygonPredicate::PreparedPolygonPredicate (const PreparedPolygonPredicate & other) private delete
geos::geom::prep::PreparedPolygonPredicate::PreparedPolygonPredicate (const PreparedPolygon *const prepPoly) inline
Creates an instance of this operation.
Parameters
prepPoly the PreparedPolygon to evaluate
Definition at line 131 of file PreparedPolygonPredicate.h.
   : prepPoly( prepPoly)
   { }
virtual geos::geom::prep::PreparedPolygonPredicate::~PreparedPolygonPredicate () inline virtual
Definition at line 135 of file PreparedPolygonPredicate.h.
   { }
Member Function Documentation
bool geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTarget (const geom::Geometry * testGeom) const protected
Tests whether all components of the test Geometry are contained in the target geometry.
Handles both linear and point components.
Parameters
geom a geometry to test
Returns
true if all components of the argument are contained in the target geometry
Definition at line 41 of file PreparedPolygonPredicate.cpp.
References geos::geom::Location::EXTERIOR, geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::algorithm::locate::PointOnGeometryLocator::locate(), and prepPoly.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::eval().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const geom::Coordinate* pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::EXTERIOR == loc)
         {
             return false;
         }
     }
     return true;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTargetInterior (const geom::Geometry * testGeom) const protected
Tests whether all components of the test Geometry are contained in the interior of the target geometry.
Handles both linear and point components.
Parameters
geom a geometry to test
Returns
true if all componenta of the argument are contained in the target geometry interior
Definition at line 59 of file PreparedPolygonPredicate.cpp.
References geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::geom::Location::INTERIOR, geos::algorithm::locate::PointOnGeometryLocator::locate(), and prepPoly.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const geom::Coordinate * pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::INTERIOR != loc)
         {
             return false;
         }
     }
     return true;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAnyTargetComponentInAreaTest (const geom::Geometry * testGeom, const geom::Coordinate::ConstVect * targetRepPts) const protected
Tests whether any component of the target geometry intersects the test geometry (which must be an areal geometry)
Parameters
geom the test geometry
repPts the representative points of the target geometry
Returns
true if any component intersects the areal test geometry
Definition at line 116 of file PreparedPolygonPredicate.cpp.
References geos::geom::Location::EXTERIOR, and geos::algorithm::locate::SimplePointInAreaLocator::locate().
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), and geos::geom::prep::PreparedPolygonIntersects::intersects().
 {
     algorithm::locate::SimplePointInAreaLocator piaLoc(testGeom);
     for (std::size_t i = 0, ni = targetRepPts->size(); i < ni; i++)
     {
         const geom::Coordinate * pt = (*targetRepPts)[i];
         const int loc = piaLoc.locate(pt);
         if (geom::Location::EXTERIOR != loc)
         {
             return true;
         }
     }
     return false;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTarget (const geom::Geometry * testGeom) const protected
Tests whether any component of the test Geometry intersects the area of the target geometry.
Handles test geometries with both linear and point components.
Parameters
geom a geometry to test
Returns
true if any component of the argument intersects the prepared geometry
Definition at line 78 of file PreparedPolygonPredicate.cpp.
References geos::geom::Location::EXTERIOR, geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::algorithm::locate::PointOnGeometryLocator::locate(), and prepPoly.
Referenced by geos::geom::prep::PreparedPolygonIntersects::intersects().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const Coordinate* pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::EXTERIOR != loc)
         {
             return true;
         }
     }
     return false;
 }
bool geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTargetInterior (const geom::Geometry * testGeom) const protected
Tests whether any component of the test Geometry intersects the interior of the target geometry.
Handles test geometries with both linear and point components.
Parameters
geom a geometry to test
Returns
true if any component of the argument intersects the prepared area geometry interior
Definition at line 97 of file PreparedPolygonPredicate.cpp.
References geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::geom::Location::INTERIOR, geos::algorithm::locate::PointOnGeometryLocator::locate(), and prepPoly.
Referenced by geos::geom::prep::AbstractPreparedPolygonContains::eval().
 {
     geom::Coordinate::ConstVect pts;
     geom::util::ComponentCoordinateExtracter::getCoordinates(*testGeom, pts);
     for (std::size_t i = 0, ni = pts.size(); i < ni; i++)
     {
         const Coordinate * pt = pts[i];
         const int loc = prepPoly->getPointLocator()->locate(pt);
         if (geom::Location::INTERIOR == loc)
         {
             return true;
         }
     }
     return false;
 }
PreparedPolygonPredicate& geos::geom::prep::PreparedPolygonPredicate::operator= (const PreparedPolygonPredicate & rhs) private delete
Member Data Documentation
const PreparedPolygon* const geos::geom::prep::PreparedPolygonPredicate::prepPoly protected
Definition at line 65 of file PreparedPolygonPredicate.h.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections(), geos::geom::prep::PreparedPolygonCovers::fullTopologicalPredicate(), geos::geom::prep::PreparedPolygonContains::fullTopologicalPredicate(), geos::geom::prep::PreparedPolygonIntersects::intersects(), isAllTestComponentsInTarget(), isAllTestComponentsInTargetInterior(), isAnyTestComponentInTarget(), isAnyTestComponentInTargetInterior(), and geos::geom::prep::AbstractPreparedPolygonContains::isProperIntersectionImpliesNotContainedSituation().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/prep/PreparedPolygonPredicate.h
/home/vicky/potree/geos/vicky/src/geom/prep/PreparedPolygonPredicate.cpp