GEOS: geos::planargraph::GraphComponent Class Reference
geos::planargraph::GraphComponent Class Reference
The base class for all graph component classes.
#include <GraphComponent.h>
Public Member Functions
GraphComponent ()
virtual ~GraphComponent ()
virtual bool isVisited () const
Tests if a component has been visited during the course of a graph algorithm.
virtual void setVisited (bool isVisited)
Sets the visited flag for this component.
virtual bool isMarked () const
Tests if a component has been marked at some point during the processing involving this graph.
virtual void setMarked (bool isMarked)
Sets the marked flag for this component.
Static Public Member Functions
template<typename T >
static void setVisited (T start, T end, bool visited)
Sets the Visited state for the elements of a container, from start to end iterator.
template<typename T >
static void setVisitedMap (T start, T end, bool visited)
Sets the Visited state for the values of each map container element, from start to end iterator.
template<typename T >
static void setMarked (T start, T end, bool marked)
Sets the Marked state for the elements of a container, from start to end iterator.
template<typename T >
static void setMarkedMap (T start, T end, bool marked)
Sets the Marked state for the values of each map container element, from start to end iterator.
Protected Attributes
bool isMarkedVar
Variable holding ''marked'' status.
bool isVisitedVar
Variable holding ''visited'' status.
Detailed Description
The base class for all graph component classes.
Maintains flags of use in generic graph algorithms. Provides two flags:
marked - typically this is used to indicate a state that persists for the course of the graph's lifetime. For instance, it can be used to indicate that a component has been logically deleted from the graph.
visited - this is used to indicate that a component has been processed or visited by an single graph algorithm. For instance, a breadth-first traversal of the graph might use this to indicate that a node has already been traversed. The visited flag may be set and cleared many times during the lifetime of a graph.
Definition at line 46 of file GraphComponent.h.
Constructor & Destructor Documentation
geos::planargraph::GraphComponent::GraphComponent () inline
Definition at line 58 of file GraphComponent.h.
     :
     isMarkedVar(false),
     isVisitedVar(false)
     {}
virtual geos::planargraph::GraphComponent::~GraphComponent () inline virtual
Definition at line 64 of file GraphComponent.h.
 {}
Member Function Documentation
virtual bool geos::planargraph::GraphComponent::isMarked () const inline virtual
Tests if a component has been marked at some point during the processing involving this graph.
Returns
true if the component has been marked
Definition at line 146 of file GraphComponent.h.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsStartingAt(), and geos::planargraph::operator<<().
 { return isMarkedVar; }
virtual bool geos::planargraph::GraphComponent::isVisited () const inline virtual
Tests if a component has been visited during the course of a graph algorithm.
Returns
true if the component has been visited
Definition at line 72 of file GraphComponent.h.
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges(), geos::planargraph::algorithm::ConnectedSubgraphFinder::getConnectedSubgraphs(), and geos::planargraph::operator<<().
 { return isVisitedVar; }
template<typename T > static void geos::planargraph::GraphComponent::setMarked (T start, T end, bool marked) inline static
Sets the Marked state for the elements of a container, from start to end iterator.
Parameters
start the start element
end one past the last element
marked the state to set the marked flag to
Definition at line 119 of file GraphComponent.h.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForNonDegree2Nodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), geos::operation::linemerge::LineMerger::buildEdgeStringStartingWith(), geos::operation::polygonize::PolygonizeGraph::deleteAllEdges(), and geos::operation::polygonize::PolygonizeGraph::deleteCutEdges().
{
     for(T i=start; i!=end; ++i) {
       (*i)->setMarked(marked);
     }
   }
virtual void geos::planargraph::GraphComponent::setMarked (bool isMarked) inline virtual
Sets the marked flag for this component.
Parameters
isMarked the desired value of the marked flag
Definition at line 152 of file GraphComponent.h.
 { isMarkedVar=isMarked; }
template<typename T > static void geos::planargraph::GraphComponent::setMarkedMap (T start, T end, bool marked) inline static
Sets the Marked state for the values of each map container element, from start to end iterator.
Parameters
start the start element
end one past the last element
marked the state to set the visited flag to
Definition at line 135 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       i->second->setMarked(marked);
     }
   }
virtual void geos::planargraph::GraphComponent::setVisited (bool isVisited) inline virtual
Sets the visited flag for this component.
Parameters
isVisited the desired value of the visited flag
Definition at line 78 of file GraphComponent.h.
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges(), and geos::operation::linemerge::LineSequencer::addReverseSubpath().
 { isVisitedVar=isVisited; }
template<typename T > static void geos::planargraph::GraphComponent::setVisited (T start, T end, bool visited) inline static
Sets the Visited state for the elements of a container, from start to end iterator.
Parameters
start the start element
end one past the last element
visited the state to set the visited flag to
Definition at line 89 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       (*i)->setVisited(visited);
     }
   }
template<typename T > static void geos::planargraph::GraphComponent::setVisitedMap (T start, T end, bool visited) inline static
Sets the Visited state for the values of each map container element, from start to end iterator.
Parameters
start the start element
end one past the last element
visited the state to set the visited flag to
Definition at line 104 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       i->second->setVisited(visited);
     }
   }
Member Data Documentation
bool geos::planargraph::GraphComponent::isMarkedVar protected
Variable holding ''marked'' status.
Definition at line 51 of file GraphComponent.h.
bool geos::planargraph::GraphComponent::isVisitedVar protected
Variable holding ''visited'' status.
Definition at line 54 of file GraphComponent.h.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/planargraph/GraphComponent.h