GEOS: geos::geom::PrecisionModel Class Reference
geos::geom::PrecisionModel Class Reference
Specifies the precision model of the Coordinate in a Geometry.
#include <geos.h>
Public Types
enum Type { FIXED, FLOATING, FLOATING_SINGLE }
The types of Precision Model which GEOS supports.
Public Member Functions
PrecisionModel (void)
Creates a PrecisionModel with a default precision of FLOATING.
PrecisionModel (Type nModelType)
Creates a PrecisionModel specifying an explicit precision model type.
PrecisionModel (double newScale, double newOffsetX, double newOffsetY)
Creates a PrecisionModel with Fixed precision.
PrecisionModel (double newScale)
Creates a PrecisionModel with Fixed precision.
PrecisionModel (const PrecisionModel &pm)
~PrecisionModel (void)
destructor
double makePrecise (double val) const
Rounds a numeric value to the PrecisionModel grid.
void makePrecise (Coordinate &coord) const
Rounds the given Coordinate to the PrecisionModel grid.
void makePrecise (Coordinate *coord) const
bool isFloating () const
Tests whether the precision model supports floating point.
int getMaximumSignificantDigits () const
Returns the maximum number of significant digits provided by this precision model.
Type getType () const
Gets the type of this PrecisionModel.
double getScale () const
Returns the multiplying factor used to obtain a precise coordinate.
double getOffsetX () const
Returns the x-offset used to obtain a precise coordinate.
double getOffsetY () const
Returns the y-offset used to obtain a precise coordinate.
std::string toString () const
Sets internal to the precise representation of external.
int compareTo (const PrecisionModel *other) const
Compares this PrecisionModel object with the specified object for order.
Static Public Attributes
static const double maximumPreciseValue =9007199254740992.0
The maximum precise value representable in a double.
Private Member Functions
void setScale (double newScale)
Sets the multiplying factor used to obtain a precise coordinate.
Private Attributes
Type modelType
double scale
Friends
class io::Unload
Detailed Description
Specifies the precision model of the Coordinate in a Geometry.
In other words, specifies the grid of allowable points for all Geometrys.
The makePrecise method allows rounding a coordinate to a "precise" value; that is, one whose precision is known exactly.
Coordinates are assumed to be precise in geometries. That is, the coordinates are assumed to be rounded to the precision model given for the geometry. JTS input routines automatically round coordinates to the precision model before creating Geometries. All internal operations assume that coordinates are rounded to the precision model. Constructive methods (such as boolean operations) always round computed coordinates to the appropriate precision model.
Currently three types of precision model are supported:
FLOATING - represents full double precision floating point. This is the default precision model used in JTS
FLOATING_SINGLE - represents single precision floating point.
FIXED - represents a model with a fixed number of decimal places. A Fixed Precision Model is specified by a scale factor. The scale factor specifies the grid which numbers are rounded to. Input coordinates are mapped to fixed coordinates according to the following equations:
jtsPt.x = round(inputPt.x * scale) / scale
jtsPt.y = round(inputPt.y * scale) / scale
For example, to specify 3 decimal places of precision, use a scale factor of 1000. To specify -3 decimal places of precision (i.e. rounding to the nearest 1000), use a scale factor of 0.001.
Coordinates are represented internally as Java double-precision values. Since Java uses the IEEE-394 floating point standard, this provides 53 bits of precision. (Thus the maximum precisely representable integer is 9,007,199,254,740,992).
JTS methods currently do not handle inputs with different precision models.
Definition at line 87 of file PrecisionModel.h.
Member Enumeration Documentation
enum geos::geom::PrecisionModel::Type
The types of Precision Model which GEOS supports.
Enumerator
FIXED
Fixed Precision indicates that coordinates have a fixed number of decimal places. The number of decimal places is determined by the log10 of the scale factor.
FLOATING
Floating precision corresponds to the standard Java double-precision floating-point representation, which is based on the IEEE-754 standard
FLOATING_SINGLE
Floating single precision corresponds to the standard Java single-precision floating-point representation, which is based on the IEEE-754 standard
Definition at line 93 of file PrecisionModel.h.
                {
     FIXED,
     FLOATING,
     FLOATING_SINGLE
   } Type;
Constructor & Destructor Documentation
geos::geom::PrecisionModel::PrecisionModel (void)
Creates a PrecisionModel with a default precision of FLOATING.
Definition at line 80 of file PrecisionModel.cpp.
   :
   modelType(FLOATING),
   scale(0.0)
 {
 #if GEOS_DEBUG
   cerr<<"PrecisionModel["<<this<<"] ctor()"<<endl;
 #endif
   //modelType=FLOATING;
   //scale=1.0;
 }
geos::geom::PrecisionModel::PrecisionModel (Type nModelType)
Creates a PrecisionModel specifying an explicit precision model type.
If the model type is FIXED the scale factor will default to 1.
Parameters
nModelType the type of the precision model
Definition at line 93 of file PrecisionModel.cpp.
   :
   modelType(nModelType),
   scale(1.0)
 {
 #if GEOS_DEBUG
   cerr<<"PrecisionModel["<<this<<"] ctor(Type)"<<endl;
 #endif
   //modelType=nModelType;
   //if (modelType==FIXED) setScale(1.0);
   //else setScale(666); // arbitrary number for invariant testing
 }
geos::geom::PrecisionModel::PrecisionModel (double newScale, double newOffsetX, double newOffsetY)
Creates a PrecisionModel with Fixed precision.
Fixed-precision coordinates are represented as precise internal coordinates, which are rounded to the grid defined by the scale factor.
Parameters
scale amount by which to multiply a coordinate after subtracting the offset, to obtain a precise coordinate
offsetX not used.
offsetY not used.
Deprecated:
offsets are no longer supported, since internal representation is rounded floating point
Definition at line 108 of file PrecisionModel.cpp.
References geos::ignore_unused_variable_warning(), and setScale().
   :
   modelType(FIXED)
 {
     ::geos::ignore_unused_variable_warning(newOffsetX);
     ::geos::ignore_unused_variable_warning(newOffsetY);
 #if GEOS_DEBUG
   cerr<<"PrecisionModel["<<this<<"] ctor(scale,offsets)"<<endl;
 #endif
   //modelType = FIXED;
   setScale(newScale);
 }
geos::geom::PrecisionModel::PrecisionModel (double newScale)
Creates a PrecisionModel with Fixed precision.
Fixed-precision coordinates are represented as precise internal coordinates which are rounded to the grid defined by the scale factor.
Parameters
newScale amount by which to multiply a coordinate after subtracting the offset, to obtain a precise coordinate
Definition at line 125 of file PrecisionModel.cpp.
References setScale().
   :
   modelType(FIXED)
 {
 #if GEOS_DEBUG
   cerr<<"PrecisionModel["<<this<<"] ctor(scale)"<<endl;
 #endif
   setScale(newScale);
 }
geos::geom::PrecisionModel::PrecisionModel (const PrecisionModel & pm)
Definition at line 137 of file PrecisionModel.cpp.
   :
   modelType(pm.modelType),
   scale(pm.scale)
 {
 #if GEOS_DEBUG
   cerr<<"PrecisionModel["<<this<<"] ctor(pm["<< &pm <<"])"<<endl;
 #endif
 }
INLINE geos::geom::PrecisionModel::~PrecisionModel (void)
destructor
Definition at line 32 of file PrecisionModel.inl.
References INLINE.
 {
 }
Member Function Documentation
int geos::geom::PrecisionModel::compareTo (const PrecisionModel * other) const
Compares this PrecisionModel object with the specified object for order.
A PrecisionModel is greater than another if it provides greater precision. The comparison is based on the value returned by the getMaximumSignificantDigits method. This comparison is not strictly accurate when comparing floating precision models to fixed models; however, it is correct when both models are either floating or fixed.
Parameters
other the PrecisionModel with which this PrecisionModel is being compared
Returns
a negative integer, zero, or a positive integer as this PrecisionModel is less than, equal to, or greater than the specified PrecisionModel.
Definition at line 227 of file PrecisionModel.cpp.
References getMaximumSignificantDigits().
Referenced by geos::geom::BinaryOp(), and geos::operation::GeometryGraphOperation::GeometryGraphOperation().
 {
   int sigDigits=getMaximumSignificantDigits();
   int otherSigDigits=other->getMaximumSignificantDigits();
   return sigDigits<otherSigDigits? -1: (sigDigits==otherSigDigits? 0:1);
 }
int geos::geom::PrecisionModel::getMaximumSignificantDigits () const
Returns the maximum number of significant digits provided by this precision model.
Intended for use by routines which need to print out precise values.
Returns
the maximum number of decimal places provided by this precision model
Definition at line 156 of file PrecisionModel.cpp.
References FIXED, FLOATING, FLOATING_SINGLE, getScale(), and modelType.
Referenced by compareTo(), and geos::io::WKTWriter::writeFormatted().
 {
   int maxSigDigits = 16;
   if (modelType == FLOATING) {
     maxSigDigits = 16;
   } else if (modelType == FLOATING_SINGLE) {
     maxSigDigits = 6;
   } else if (modelType == FIXED) {
     double dgtsd = std::log(getScale()) / std::log(double(10.0));
     const int dgts = static_cast<int>(
       dgtsd > 0 ? std::ceil(dgtsd)
                 : std::floor(dgtsd)
     );
     maxSigDigits = dgts;
   }
   return maxSigDigits;
 }
double geos::geom::PrecisionModel::getOffsetX () const
Returns the x-offset used to obtain a precise coordinate.
Returns
the amount by which to subtract the x-coordinate before multiplying by the scale
Deprecated:
Offsets are no longer used
Definition at line 188 of file PrecisionModel.cpp.
Referenced by toString().
 {
   return 0;
 }
double geos::geom::PrecisionModel::getOffsetY () const
Returns the y-offset used to obtain a precise coordinate.
Returns
the amount by which to subtract the y-coordinate before multiplying by the scale
Deprecated:
Offsets are no longer used
Definition at line 195 of file PrecisionModel.cpp.
Referenced by toString().
 {
   return 0;
 }
INLINE double geos::geom::PrecisionModel::getScale () const
Returns the multiplying factor used to obtain a precise coordinate.
Definition at line 53 of file PrecisionModel.inl.
References scale.
Referenced by geos::geom::BinaryOp(), geos::operation::buffer::BufferOp::bufferFixedPrecision(), GEOSGeom_getPrecision_r(), GEOSGeom_setPrecision_r(), getMaximumSignificantDigits(), geos::operation::buffer::BufferBuilder::getNoder(), geos::geom::operator==(), and toString().
 {
     assert(!(scale < 0));
     return scale;
 }
INLINE PrecisionModel::Type geos::geom::PrecisionModel::getType () const
Gets the type of this PrecisionModel.
Returns
the type of this PrecisionModel
Definition at line 46 of file PrecisionModel.inl.
References INLINE, and modelType.
Referenced by geos::operation::buffer::BufferOp::bufferFixedPrecision(), and geos::operation::buffer::BufferOp::computeGeometry().
 {
   return modelType;
 }
bool geos::geom::PrecisionModel::isFloating () const
Tests whether the precision model supports floating point.
Returns
true if the precision model supports floating point
Definition at line 149 of file PrecisionModel.cpp.
References FLOATING, FLOATING_SINGLE, and modelType.
Referenced by geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), geos::operation::overlay::OverlayOp::computeOverlay(), GEOSGeom_getPrecision_r(), GEOSGeom_setPrecision_r(), and geos::geom::operator==().
 {
   return (modelType == FLOATING || modelType == FLOATING_SINGLE);
 }
double geos::geom::PrecisionModel::makePrecise (double val) const
Rounds a numeric value to the PrecisionModel grid.
Asymmetric Arithmetic Rounding is used, to provide uniform rounding behaviour no matter where the number is on the number line.
Note: Java's Math::rint uses the "Banker's Rounding" algorithm, which is not suitable for precision operations elsewhere in JTS.
Definition at line 48 of file PrecisionModel.cpp.
References geos::util::round().
Referenced by geos::operation::buffer::OffsetSegmentString::addPt(), geos::util::GeometricShapeFactory::coord(), geos::geom::GeometryFactory::createPointFromInternalCoord(), geos::geom::Geometry::getCentroid(), makePrecise(), and geos::io::WKBReader::readCoordinate().
 {
 #if GEOS_DEBUG
     cerr<<"PrecisionModel["<<this<<"]::makePrecise called"<<endl;
 #endif
     if (modelType==FLOATING_SINGLE) {
         float floatSingleVal = static_cast<float>(val);
         return static_cast<double>(floatSingleVal);
     }
     if (modelType == FIXED) {
         // Use whatever happens to be the default rounding method
         const double ret = util::round(val*scale)/scale;
         return ret;
     }
     // modelType == FLOATING - no rounding necessary
     return val;
 }
void geos::geom::PrecisionModel::makePrecise (Coordinate & coord) const
Rounds the given Coordinate to the PrecisionModel grid.
Definition at line 69 of file PrecisionModel.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   // optimization for full precision
   if (modelType==FLOATING) return;
   coord.x=makePrecise(coord.x);
   coord.y=makePrecise(coord.y);
 }
INLINE void geos::geom::PrecisionModel::makePrecise (Coordinate * coord) const
Definition at line 38 of file PrecisionModel.inl.
References INLINE, and makePrecise().
 {
   assert(coord);
   return makePrecise(*coord);
 }
void geos::geom::PrecisionModel::setScale (double newScale) private
Sets the multiplying factor used to obtain a precise coordinate.
This method is private because PrecisionModel is intended to be an immutable (value) type.
Definition at line 178 of file PrecisionModel.cpp.
References scale.
Referenced by PrecisionModel().
 {
   if ( newScale <= 0 )
     throw util::IllegalArgumentException("PrecisionModel scale cannot be 0");
     scale = std::fabs(newScale);
 }
string geos::geom::PrecisionModel::toString (void) const
Sets internal to the precise representation of external.
Parameters
external the original coordinate
internal the coordinate whose values will be changed to the precise representation of external
Deprecated:
use makePrecise instead
Definition at line 202 of file PrecisionModel.cpp.
References FIXED, FLOATING, FLOATING_SINGLE, getOffsetX(), getOffsetY(), getScale(), and modelType.
 {
   ostringstream s;
     if (modelType == FLOATING) {
       s<<"Floating";
     } else if (modelType == FLOATING_SINGLE) {
       s<<"Floating-Single";
     } else if (modelType == FIXED) {
     s <<"Fixed (Scale=" << getScale()
       << " OffsetX=" << getOffsetX()
       << " OffsetY=" << getOffsetY()
       << ")";
   } else {
     s<<"UNKNOWN";
   }
   return s.str();
 }
Friends And Related Function Documentation
friend class io::Unload friend
Definition at line 88 of file PrecisionModel.h.
Member Data Documentation
const double geos::geom::PrecisionModel::maximumPreciseValue =9007199254740992.0 static
The maximum precise value representable in a double.
Since IEE754 double-precision numbers allow 53 bits of mantissa, the value is equal to 2^53 - 1. This provides almost 16 decimal digits of precision.
Definition at line 174 of file PrecisionModel.h.
Type geos::geom::PrecisionModel::modelType private
Definition at line 316 of file PrecisionModel.h.
Referenced by getMaximumSignificantDigits(), getType(), isFloating(), and toString().
double geos::geom::PrecisionModel::scale private
Definition at line 318 of file PrecisionModel.h.
Referenced by getScale(), and setScale().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/PrecisionModel.h
/home/vicky/potree/geos/vicky/src/geom/PrecisionModel.cpp
/home/vicky/potree/geos/vicky/include/geos/geom/PrecisionModel.inl