GEOS: geos::algorithm::CentralEndpointIntersector Class Reference
geos::algorithm::CentralEndpointIntersector Class Reference
Computes an approximate intersection of two line segments by taking the most central of the endpoints of the segments.
#include <CentralEndpointIntersector.h>
Public Member Functions
CentralEndpointIntersector (const geom::Coordinate &p00, const geom::Coordinate &p01, const geom::Coordinate &p10, const geom::Coordinate &p11)
const geom::Coordinate & getIntersection () const
Static Public Member Functions
static const geom::Coordinate & getIntersection (const geom::Coordinate &p00, const geom::Coordinate &p01, const geom::Coordinate &p10, const geom::Coordinate &p11)
Private Member Functions
void compute ()
geom::Coordinate findNearestPoint (const geom::Coordinate &p, const std::vector< geom::Coordinate > &pts) const
Static Private Member Functions
static geom::Coordinate average (const std::vector< geom::Coordinate > &pts)
Private Attributes
std::vector< geom::Coordinate > _pts
geom::Coordinate _intPt
Detailed Description
Computes an approximate intersection of two line segments by taking the most central of the endpoints of the segments.
This is effective in cases where the segments are nearly parallel and should intersect at an endpoint. It is also a reasonable strategy for cases where the endpoint of one segment lies on or almost on the interior of another one. Taking the most central endpoint ensures that the computed intersection point lies in the envelope of the segments. Also, by always returning one of the input points, this should result in reducing segment fragmentation. Intended to be used as a last resort for computing ill-conditioned intersection situations which cause other methods to fail.
Author
Martin Davis
Version
1.8
Definition at line 62 of file CentralEndpointIntersector.h.
Constructor & Destructor Documentation
geos::algorithm::CentralEndpointIntersector::CentralEndpointIntersector (const geom::Coordinate & p00, const geom::Coordinate & p01, const geom::Coordinate & p10, const geom::Coordinate & p11) inline
Definition at line 74 of file CentralEndpointIntersector.h.
     :
     _pts(4)
   {
     _pts[0]=p00;
     _pts[1]=p01;
     _pts[2]=p10;
     _pts[3]=p11;
     compute();
   }
Member Function Documentation
static geom::Coordinate geos::algorithm::CentralEndpointIntersector::average (const std::vector< geom::Coordinate > & pts) inline static private
Definition at line 108 of file CentralEndpointIntersector.h.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
   {
     geom::Coordinate avg(0, 0);
     size_t n = pts.size();
     if ( ! n ) return avg;
     for (std::size_t i=0; i<n; ++i)
     {
       avg.x += pts[i].x;
       avg.y += pts[i].y;
     }
     avg.x /= n;
     avg.y /= n;
     return avg;
   }
void geos::algorithm::CentralEndpointIntersector::compute () inline private
Definition at line 102 of file CentralEndpointIntersector.h.
   {
     geom::Coordinate centroid = average(_pts);
     _intPt = findNearestPoint(centroid, _pts);
   }
geom::Coordinate geos::algorithm::CentralEndpointIntersector::findNearestPoint (const geom::Coordinate & p, const std::vector< geom::Coordinate > & pts) const inline private
Determines a point closest to the given point.
Parameters
p the point to compare against
p1 a potential result point
p2 a potential result point
q1 a potential result point
q2 a potential result point
Returns
the point closest to the input point p
Definition at line 134 of file CentralEndpointIntersector.h.
References geos::geom::Coordinate::distance(), and geos::geom::Coordinate::getNull().
   {
     double minDist = std::numeric_limits<double>::max();
     geom::Coordinate result = geom::Coordinate::getNull();
     for (std::size_t i = 0, n=pts.size(); i < n; ++i) {
       double dist = p.distance(pts[i]);
       if (dist < minDist) {
         minDist = dist;
         result = pts[i];
       }
     }
     return result;
   }
static const geom::Coordinate& geos::algorithm::CentralEndpointIntersector::getIntersection (const geom::Coordinate & p00, const geom::Coordinate & p01, const geom::Coordinate & p10, const geom::Coordinate & p11) inline static
Definition at line 66 of file CentralEndpointIntersector.h.
References getIntersection().
Referenced by getIntersection().
   {
     CentralEndpointIntersector intor(p00, p01, p10, p11);
     return intor.getIntersection();
   }
const geom::Coordinate& geos::algorithm::CentralEndpointIntersector::getIntersection () const inline
Definition at line 88 of file CentralEndpointIntersector.h.
   {
     return _intPt;
   }
Member Data Documentation
geom::Coordinate geos::algorithm::CentralEndpointIntersector::_intPt private
Definition at line 100 of file CentralEndpointIntersector.h.
std::vector<geom::Coordinate> geos::algorithm::CentralEndpointIntersector::_pts private
Definition at line 98 of file CentralEndpointIntersector.h.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/algorithm/CentralEndpointIntersector.h