GEOS: geos::operation::intersection::RectangleIntersection Class Reference
geos::operation::intersection::RectangleIntersection Class Reference
Speed-optimized clipping of a Geometry with a rectangle.
#include <RectangleIntersection.h>
Static Public Member Functions
static std::unique_ptr< geom::Geometry > clip (const geom::Geometry &geom, const Rectangle &rect)
Clip geometry with a rectangle.
static std::unique_ptr< geom::Geometry > clipBoundary (const geom::Geometry &geom, const Rectangle &rect)
Clip boundary of a geometry with a rectangle.
Private Member Functions
RectangleIntersection (const geom::Geometry &geom, const Rectangle &rect)
std::unique_ptr< geom::Geometry > clipBoundary ()
std::unique_ptr< geom::Geometry > clip ()
void clip_geom (const geom::Geometry *g, RectangleIntersectionBuilder &parts, const Rectangle &rect, bool keep_polygons)
void clip_point (const geom::Point *g, RectangleIntersectionBuilder &parts, const Rectangle &rect)
Clip geometry.
void clip_multipoint (const geom::MultiPoint *g, RectangleIntersectionBuilder &parts, const Rectangle &rect)
void clip_linestring (const geom::LineString *g, RectangleIntersectionBuilder &parts, const Rectangle &rect)
Clip geometry.
void clip_multilinestring (const geom::MultiLineString *g, RectangleIntersectionBuilder &parts, const Rectangle &rect)
void clip_polygon (const geom::Polygon *g, RectangleIntersectionBuilder &parts, const Rectangle &rect, bool keep_polygons)
Clip geometry.
void clip_multipolygon (const geom::MultiPolygon *g, RectangleIntersectionBuilder &parts, const Rectangle &rect, bool keep_polygons)
void clip_geometrycollection (const geom::GeometryCollection *g, RectangleIntersectionBuilder &parts, const Rectangle &rect, bool keep_polygons)
void clip_polygon_to_linestrings (const geom::Polygon *g, RectangleIntersectionBuilder &parts, const Rectangle &rect)
Clip polygon, do not close clipped ones.
void clip_polygon_to_polygons (const geom::Polygon *g, RectangleIntersectionBuilder &parts, const Rectangle &rect)
Clip polygon, close clipped ones.
bool clip_linestring_parts (const geom::LineString *gi, RectangleIntersectionBuilder &parts, const Rectangle &rect)
Clip geometry.
Private Attributes
const geom::Geometry & _geom
const Rectangle & _rect
const geom::GeometryFactory * _gf
const geom::CoordinateSequenceFactory * _csf
Detailed Description
Speed-optimized clipping of a Geometry with a rectangle.
Two different methods are provided. The first performs normal clipping, the second clips the boundaries of polygons, not the polygons themselves. In the first case a polygon will remain a polygon or is completely cut out. In the latter case polygons will be converted to polylines if any vertex is outside the clipping rectangle, or will be cut out completely.
The algorithm works best when the number of intersections is very low. For example, if the geometry is completely to the left of the clipping rectangle, only the x-coordinate of the geometry is ever tested and is only compared with the x-coordinate of the left edge of the rectangle. Hence clipping may be faster than calculating the envelope of the geometry for trivial overlap tests.
The input geometry must be valid. In particular all LinearRings must be properly closed, or the algorithm may not terminate.
Definition at line 74 of file RectangleIntersection.h.
Constructor & Destructor Documentation
geos::operation::intersection::RectangleIntersection::RectangleIntersection (const geom::Geometry & geom, const Rectangle & rect) private
Definition at line 700 of file RectangleIntersection.cpp.
References _csf, _gf, and geos::geom::GeometryFactory::getCoordinateSequenceFactory().
   : _geom(geom), _rect(rect),
     _gf(geom.getFactory())
 {
   _csf = _gf->getCoordinateSequenceFactory();
 }
Member Function Documentation
std::unique_ptr< geom::Geometry > geos::operation::intersection::RectangleIntersection::clip (const geom::Geometry & geom, const Rectangle & rect) static
Clip geometry with a rectangle.
Parameters
geom a Geometry
rect a Rectangle
Returns
the clipped geometry
NULL if the geometry is outside the Rectangle
Definition at line 683 of file RectangleIntersection.cpp.
References clip().
Referenced by clip().
 {
   RectangleIntersection ri(g,rect);
   return ri.clip();
 }
std::unique_ptr< geom::Geometry > geos::operation::intersection::RectangleIntersection::clip () private
Definition at line 690 of file RectangleIntersection.cpp.
References geos::operation::intersection::RectangleIntersectionBuilder::build().
 {
   RectangleIntersectionBuilder parts(*_gf);
   bool keep_polygons = true;
   clip_geom(&_geom, parts, _rect, keep_polygons);
   return parts.build();
 }
void geos::operation::intersection::RectangleIntersection::clip_geom (const geom::Geometry * g, RectangleIntersectionBuilder & parts, const Rectangle & rect, bool keep_polygons) private
Definition at line 638 of file RectangleIntersection.cpp.
 {
   if ( const Point* p = dynamic_cast<const geom::Point *>(g) )
     return clip_point(p, parts, rect);
   else if ( const MultiPoint* p = dynamic_cast<const geom::MultiPoint *>(g) )
     return clip_multipoint(p, parts, rect);
   else if ( const LineString* p = dynamic_cast<const geom::LineString *>(g) )
     return clip_linestring(p, parts, rect);
   else if ( const MultiLineString* p = dynamic_cast<const geom::MultiLineString *>(g) )
     return clip_multilinestring(p, parts, rect);
   else if ( const Polygon* p = dynamic_cast<const geom::Polygon *>(g) )
     return clip_polygon(p, parts, rect, keep_polygons);
   else if ( const MultiPolygon* p = dynamic_cast<const geom::MultiPolygon *>(g) )
     return clip_multipolygon(p, parts, rect, keep_polygons);
   else if ( const GeometryCollection* p = dynamic_cast<const geom::GeometryCollection *>(g) )
     return clip_geometrycollection(p, parts, rect, keep_polygons);
   else {
     throw util::UnsupportedOperationException("Encountered an unknown geometry component when clipping polygons");
   }
 }
void geos::operation::intersection::RectangleIntersection::clip_geometrycollection (const geom::GeometryCollection * g, RectangleIntersectionBuilder & parts, const Rectangle & rect, bool keep_polygons) private
Definition at line 621 of file RectangleIntersection.cpp.
References geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), and geos::geom::GeometryCollection::isEmpty().
 {
   if(g == nullptr || g->isEmpty())
   return;
   for(int i=0, n=static_cast<int>(g->getNumGeometries()); i<n; ++i)
   {
     clip_geom(g->getGeometryN(i),
         parts, rect, keep_polygons);
   }
 }
void geos::operation::intersection::RectangleIntersection::clip_linestring (const geom::LineString * g, RectangleIntersectionBuilder & parts, const Rectangle & rect) private
Clip geometry.
Definition at line 561 of file RectangleIntersection.cpp.
References geos::operation::intersection::RectangleIntersectionBuilder::add(), geos::geom::LineString::clone(), and geos::geom::LineString::isEmpty().
 {
   if(g == nullptr || g->isEmpty())
   return;
   // If everything was in, just clone the original
   if(clip_linestring_parts(g, parts, rect))
   parts.add(dynamic_cast<geom::LineString *>(g->clone()));
 }
bool geos::operation::intersection::RectangleIntersection::clip_linestring_parts (const geom::LineString * gi, RectangleIntersectionBuilder & parts, const Rectangle & rect) private
Clip geometry.
Returns true if the geometry was fully inside, and does not output anything to RectangleIntersectionBuilder.
Definition at line 118 of file RectangleIntersection.cpp.
References geos::operation::intersection::RectangleIntersectionBuilder::add(), geos::operation::intersection::clip_to_edges(), geos::operation::intersection::different(), geos::geom::LineString::getCoordinatesRO(), geos::geom::LineString::getNumPoints(), geos::operation::intersection::Rectangle::position(), geos::geom::CoordinateSequence::toVector(), geos::operation::intersection::Rectangle::xmax(), geos::operation::intersection::Rectangle::xmin(), geos::operation::intersection::Rectangle::ymax(), and geos::operation::intersection::Rectangle::ymin().
 {
   using namespace geos::geom;
   int n = static_cast<int>(gi->getNumPoints());
   if(gi == nullptr || n<1)
   return false;
   // For shorthand code
   std::vector<Coordinate> cs;
   gi->getCoordinatesRO()->toVector(cs);
   //const geom::CoordinateSequence &cs = *(gi->getCoordinatesRO());
   // Keep a record of the point where a line segment entered
   // the rectangle. If the boolean is set, we must insert
   // the point to the beginning of the linestring which then
   // continues inside the rectangle.
   double x0 = 0;
   double y0 = 0;
   bool add_start = false;
   // Start iterating
   int i = 0;
   while(i<n)
   {
     // Establish initial position
     double x = cs[i].x;
     double y = cs[i].y;
     Rectangle::Position pos = rect.position(x,y);
     if(pos == Rectangle::Outside)
     {
       // Skip points as fast as possible until something has to be checked
       // in more detail.
       ++i;  // we already know it is outside
       if(x < rect.xmin())
       while(i < n && cs[i].x < rect.xmin())
         ++i;
       else if(x > rect.xmax())
       while(i < n && cs[i].x > rect.xmax())
         ++i;
       else if(y < rect.ymin())
       while(i < n && cs[i].y < rect.ymin())
         ++i;
       else if(y > rect.ymax())
       while(i < n && cs[i].y > rect.ymax())
         ++i;
       if(i >= n)
       return false;
       // Establish new position
       x = cs[i].x;
       y = cs[i].y;
       pos = rect.position(x,y);
       // Handle all possible cases
       x0 = cs[i-1].x;
       y0 = cs[i-1].y;
       clip_to_edges(x0,y0,x,y,rect);
       if(pos == Rectangle::Inside)
       {
         add_start = true; // x0,y0 must have clipped the rectangle
         // Main loop will enter the Inside/Edge section
       }
       else if(pos == Rectangle::Outside)
       {
         // From Outside to Outside. We need to check whether
         // we created a line segment inside the box. In any
         // case, we will continue the main loop after this
         // which will then enter the Outside section.
         // Clip the other end too
         clip_to_edges(x,y,x0,y0,rect);
         Rectangle::Position prev_pos = rect.position(x0,y0);
         pos = rect.position(x,y);
         if( different(x0,y0,x,y) &&   // discard corners etc
           Rectangle::onEdge(prev_pos) &&    // discard if does not intersect rect
           Rectangle::onEdge(pos) &&
           !Rectangle::onSameEdge(prev_pos,pos)  // discard if travels along edge
           )
         {
           std::vector<Coordinate> *coords = new std::vector<Coordinate>(2);
           (*coords)[0] = Coordinate(x0,y0);
           (*coords)[1] = Coordinate(x,y);
           CoordinateSequence *seq = _csf->create(coords);
           geom::LineString * line = _gf->createLineString(seq);
           parts.add(line);
         }
         // Continue main loop outside the rect
       }
       else
       {
         // From outside to edge. If the edge we hit first when
         // following the line is not the edge we end at, then
         // clearly we must go through the rectangle and hence
         // a start point must be set.
         Rectangle::Position newpos = rect.position(x0,y0);
         if(!Rectangle::onSameEdge(pos,newpos))
         {
           add_start = true;
         }
         else
         {
           // we ignore the travel along the edge and continue
           // the main loop at the last edge point
         }
       }
     }
     else
     {
       // The point is now stricly inside or on the edge.
       // Keep iterating until the end or the point goes
       // outside. We may have to output partial linestrings
       // while iterating until we go strictly outside
       int start_index = i;      // 1st valid original point
       bool go_outside = false;
       while(!go_outside && ++i<n)
       {
         x = cs[i].x;
         y = cs[i].y;
         Rectangle::Position prev_pos = pos;
         pos = rect.position(x,y);
         if(pos == Rectangle::Inside)
         {
           // Just keep going
         }
         else if(pos == Rectangle::Outside)
         {
           go_outside = true;
           // Clip the outside point to edges
           clip_to_edges(x, y, cs[i-1].x, cs[i-1].y, rect);
           pos = rect.position(x,y);
           // Does the line exit through the inside of the box?
           bool through_box = (different(x,y,cs[i].x,cs[i].y) &&
                     !Rectangle::onSameEdge(prev_pos,pos));
           // Output a LineString if it at least one segment long
           if(start_index < i-1 || add_start || through_box)
           {
             std::vector<Coordinate> *coords = new std::vector<Coordinate>();
             if(add_start)
             {
               coords->push_back(Coordinate(x0, y0));
               add_start = false;
             }
             //line->addSubLineString(&g, start_index, i-1);
             coords->insert(coords->end(), cs.begin()+start_index, cs.begin()+i);
             if(through_box) coords->push_back(Coordinate(x,y));
             CoordinateSequence *seq = _csf->create(coords);
             geom::LineString * line = _gf->createLineString(seq);
             parts.add(line);
           }
           // And continue main loop on the outside
         }
         else
         {
           // on same edge?
           if(Rectangle::onSameEdge(prev_pos,pos))
           {
             // Nothing to output if we haven't been elsewhere
             if(start_index < i-1 || add_start)
             {
               std::vector<Coordinate> *coords = new std::vector<Coordinate>();
               //geom::LineString * line = new geom::LineString();
               if(add_start)
               {
                 //line->addPoint(x0,y0);
                 coords->push_back(Coordinate(x0, y0));
                 add_start = false;
               }
               //line->addSubLineString(&g, start_index, i-1);
               coords->insert(coords->end(), cs.begin()+start_index, cs.begin()+i);
               CoordinateSequence *seq = _csf->create(coords);
               geom::LineString * line = _gf->createLineString(seq);
               parts.add(line);
             }
             start_index = i;
           }
           else
           {
             // On different edge. Must have gone through the box
             // then - keep collecting points that generate inside
             // line segments
           }
         }
       }
       // Was everything in? If so, generate no output but return true in this case only
       if(start_index == 0 && i >= n)
       return true;
       // Flush the last line segment if data ended and there is something to flush
       if(!go_outside &&           // meaning data ended
        (start_index < i-1 || add_start))  // meaning something has to be generated
       {
         std::vector<Coordinate> *coords = new std::vector<Coordinate>();
         //geom::LineString * line = new geom::LineString();
         if(add_start)
         {
           //line->addPoint(x0,y0);
           coords->push_back(Coordinate(x0, y0));
           add_start = false;
         }
         //line->addSubLineString(&g, start_index, i-1);
         coords->insert(coords->end(), cs.begin()+start_index, cs.begin()+i);
         CoordinateSequence *seq = _csf->create(coords);
         geom::LineString * line = _gf->createLineString(seq);
         parts.add(line);
       }
     }
   }
   return false;
 }
void geos::operation::intersection::RectangleIntersection::clip_multilinestring (const geom::MultiLineString * g, RectangleIntersectionBuilder & parts, const Rectangle & rect) private
Definition at line 590 of file RectangleIntersection.cpp.
References geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), and geos::geom::GeometryCollection::isEmpty().
 {
   if(g == nullptr || g->isEmpty())
   return;
   for(int i=0, n = static_cast<int>(g->getNumGeometries()); i<n; ++i)
   {
     clip_linestring(dynamic_cast<const geom::LineString *>(g->getGeometryN(i)),
             parts, rect);
   }
 }
void geos::operation::intersection::RectangleIntersection::clip_multipoint (const geom::MultiPoint * g, RectangleIntersectionBuilder & parts, const Rectangle & rect) private
Definition at line 576 of file RectangleIntersection.cpp.
References geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), and geos::geom::GeometryCollection::isEmpty().
 {
   if(g == nullptr || g->isEmpty())
   return;
   for(int i=0, n=static_cast<int>(g->getNumGeometries()); i<n; ++i)
   {
     clip_point(dynamic_cast<const geom::Point *>(g->getGeometryN(i)),
          parts, rect);
   }
 }
void geos::operation::intersection::RectangleIntersection::clip_multipolygon (const geom::MultiPolygon * g, RectangleIntersectionBuilder & parts, const Rectangle & rect, bool keep_polygons) private
Definition at line 605 of file RectangleIntersection.cpp.
References geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), and geos::geom::GeometryCollection::isEmpty().
 {
   if(g == nullptr || g->isEmpty())
   return;
   for(int i=0, n = static_cast<int>(g->getNumGeometries()); i<n; ++i)
   {
     clip_polygon(dynamic_cast<const geom::Polygon *>(g->getGeometryN(i)),
            parts, rect, keep_polygons);
   }
 }
void geos::operation::intersection::RectangleIntersection::clip_point (const geom::Point * g, RectangleIntersectionBuilder & parts, const Rectangle & rect) private
Clip geometry.
Here outGeom may also be a MultiPoint
Definition at line 103 of file RectangleIntersection.cpp.
References geos::operation::intersection::RectangleIntersectionBuilder::add(), geos::geom::Point::clone(), geos::geom::Point::getX(), geos::geom::Point::getY(), and geos::operation::intersection::Rectangle::position().
 {
   if(g == nullptr)
   return;
   double x = g->getX();
   double y = g->getY();
   if(rect.position(x,y) == Rectangle::Inside)
   parts.add(dynamic_cast<geom::Point*>(g->clone()));
 }
void geos::operation::intersection::RectangleIntersection::clip_polygon (const geom::Polygon * g, RectangleIntersectionBuilder & parts, const Rectangle & rect, bool keep_polygons) private
Clip geometry.
Definition at line 545 of file RectangleIntersection.cpp.
 {
   if(keep_polygons)
   clip_polygon_to_polygons(g, parts, rect);
   else
   clip_polygon_to_linestrings(g, parts, rect);
 }
void geos::operation::intersection::RectangleIntersection::clip_polygon_to_linestrings (const geom::Polygon * g, RectangleIntersectionBuilder & parts, const Rectangle & rect) private
Clip polygon, do not close clipped ones.
Definition at line 375 of file RectangleIntersection.cpp.
References geos::operation::intersection::RectangleIntersectionBuilder::add(), geos::geom::Polygon::clone(), geos::geom::LineString::clone(), geos::operation::intersection::RectangleIntersectionBuilder::empty(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), geos::geom::Polygon::isEmpty(), poly, geos::operation::intersection::RectangleIntersectionBuilder::reconnect(), and geos::operation::intersection::RectangleIntersectionBuilder::release().
 {
   if(g == nullptr || g->isEmpty())
   return;
   // Clip the exterior first to see what's going on
   RectangleIntersectionBuilder parts(*_gf);
   // If everything was in, just clone the original
   if(clip_linestring_parts(g->getExteriorRing(), parts, rect))
   {
     toParts.add(dynamic_cast<geom::Polygon *>(g->clone()));
     return;
   }
   // Now, if parts is empty, our rectangle may be inside the polygon
   // If not, holes are outside too
   if(parts.empty())
   {
     // We could now check whether the rectangle is inside the outer
     // ring to avoid checking the holes. However, if holes are much
     // smaller than the exterior ring just checking the holes
     // separately could be faster.
     if(g->getNumInteriorRing() == 0)
     return;
   }
   else
   {
     // The exterior must have been clipped into linestrings.
     // Move them to the actual parts collector, clearing parts.
     parts.reconnect();
     parts.release(toParts);
   }
   // Handle the holes now:
   // - Clipped ones become linestrings
   // - Intact ones become new polygons without holes
   for(int i=0, n= static_cast<int>(g->getNumInteriorRing()); i<n; ++i)
   {
     if(clip_linestring_parts(g->getInteriorRingN(i), parts, rect))
     {
       // clones
       LinearRing *hole = dynamic_cast<LinearRing*>(g->getInteriorRingN(i)->clone());
       // becomes exterior
       Polygon *poly = _gf->createPolygon(hole, nullptr);
       toParts.add(poly);
     }
     else if(!parts.empty())
     {
       parts.reconnect();
       parts.release(toParts);
     }
   }
 }
void geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons (const geom::Polygon * g, RectangleIntersectionBuilder & parts, const Rectangle & rect) private
Clip polygon, close clipped ones.
Definition at line 444 of file RectangleIntersection.cpp.
References geos::operation::intersection::RectangleIntersectionBuilder::add(), geos::geom::Polygon::clone(), geos::geom::LineString::clone(), geos::operation::intersection::RectangleIntersectionBuilder::empty(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), geos::geom::Location::INTERIOR, geos::geom::Polygon::isEmpty(), poly, geos::operation::intersection::RectangleIntersectionBuilder::reconnect(), geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), geos::operation::intersection::RectangleIntersectionBuilder::release(), geos::operation::intersection::RectangleIntersectionBuilder::reverseLines(), geos::geom::Coordinate::x, geos::operation::intersection::Rectangle::xmax(), geos::operation::intersection::Rectangle::xmin(), geos::operation::intersection::Rectangle::ymax(), and geos::operation::intersection::Rectangle::ymin().
 {
   if(g == nullptr || g->isEmpty())
   return;
   // Clip the exterior first to see what's going on
   RectangleIntersectionBuilder parts(*_gf);
   // If everything was in, just clone the original
   const LineString *shell = g->getExteriorRing();
   if(clip_linestring_parts(shell, parts, rect))
   {
     toParts.add(dynamic_cast<geom::Polygon *>(g->clone()));
     return;
   }
   // If there were no intersections, the outer ring might be
   // completely outside.
   using geos::algorithm::CGAlgorithms;
   if( parts.empty() )
   {
     Coordinate rectCenter(rect.xmin(), rect.ymin());
     rectCenter.x += (rect.xmax()-rect.xmin())/2;
     rectCenter.y += (rect.ymax()-rect.ymin())/2;
     if ( CGAlgorithms::locatePointInRing(rectCenter,
                           *g->getExteriorRing()->getCoordinatesRO())
          != Location::INTERIOR )
     {
       return;
     }
   }
   else
   {
     // TODO: make CCW checking part of clip_linestring_parts ?
     if ( CGAlgorithms::isCCW(shell->getCoordinatesRO()) ) {
       parts.reverseLines();
     }
   }
   // Must do this to make sure all end points are on the edges
   parts.reconnect();
   // Handle the holes now:
   // - Clipped ones become part of the exterior
   // - Intact ones become holes in new polygons formed by exterior parts
   for(int i=0, n = static_cast<int>(g->getNumInteriorRing()); i<n; ++i)
   {
     RectangleIntersectionBuilder holeparts(*_gf);
     const LineString *hole = g->getInteriorRingN(i);
     if(clip_linestring_parts(hole, holeparts, rect))
     {
       // becomes exterior
       LinearRing *cloned = dynamic_cast<LinearRing*>(hole->clone());
       Polygon *poly = _gf->createPolygon(cloned, nullptr);
       parts.add(poly);
     }
     else
     {
       if(!holeparts.empty())
       {
         // TODO: make CCW checking part of clip_linestring_parts ?
         if ( ! CGAlgorithms::isCCW(hole->getCoordinatesRO()) ) {
           holeparts.reverseLines();
         }
         holeparts.reconnect();
         holeparts.release(parts);
       }
       else
       {
         using geos::algorithm::CGAlgorithms;
         Coordinate rectCenter(rect.xmin(), rect.ymin());
         rectCenter.x += (rect.xmax()-rect.xmin())/2;
         rectCenter.y += (rect.ymax()-rect.ymin())/2;
         if( CGAlgorithms::isPointInRing(rectCenter,
             g->getInteriorRingN(i)->getCoordinatesRO()) )
         {
           // Completely inside the hole
           return;
         }
       }
     }
   }
   parts.reconnectPolygons(rect);
   parts.release(toParts);
 }
std::unique_ptr< geom::Geometry > geos::operation::intersection::RectangleIntersection::clipBoundary (const geom::Geometry & geom, const Rectangle & rect) static
Clip boundary of a geometry with a rectangle.
Any polygon which intersects the rectangle will be converted to a polyline or a multipolyline - including the holes.
Parameters
geom a Geometry
rect a Rectangle
Returns
the clipped geometry
NULL if the geometry is outside the Rectangle
Definition at line 664 of file RectangleIntersection.cpp.
References clipBoundary().
Referenced by clipBoundary().
 {
   RectangleIntersection ri(g,rect);
   return ri.clipBoundary();
 }
std::unique_ptr< geom::Geometry > geos::operation::intersection::RectangleIntersection::clipBoundary () private
Definition at line 671 of file RectangleIntersection.cpp.
References geos::operation::intersection::RectangleIntersectionBuilder::build().
 {
   RectangleIntersectionBuilder parts(*_gf);
   bool keep_polygons = false;
   clip_geom(&_geom, parts, _rect, keep_polygons);
   return parts.build();
 }
Member Data Documentation
const geom::CoordinateSequenceFactory* geos::operation::intersection::RectangleIntersection::_csf private
Definition at line 115 of file RectangleIntersection.h.
Referenced by RectangleIntersection().
const geom::Geometry& geos::operation::intersection::RectangleIntersection::_geom private
Definition at line 112 of file RectangleIntersection.h.
const geom::GeometryFactory* geos::operation::intersection::RectangleIntersection::_gf private
Definition at line 114 of file RectangleIntersection.h.
Referenced by RectangleIntersection().
const Rectangle& geos::operation::intersection::RectangleIntersection::_rect private
Definition at line 113 of file RectangleIntersection.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/intersection/RectangleIntersection.h
/home/vicky/potree/geos/vicky/src/operation/intersection/RectangleIntersection.cpp