GEOS: geos::linearref::LocationIndexOfPoint Class Reference
geos::linearref::LocationIndexOfPoint Class Reference
#include <LocationIndexOfPoint.h>
Public Member Functions
LocationIndexOfPoint (const geom::Geometry *linearGeom)
LinearLocation indexOf (const geom::Coordinate &inputPt) const
LinearLocation indexOfAfter (const geom::Coordinate &inputPt, const LinearLocation *minIndex) const
Static Public Member Functions
static LinearLocation indexOf (const geom::Geometry *linearGeom, const geom::Coordinate &inputPt)
static LinearLocation indexOfAfter (const geom::Geometry *linearGeom, const geom::Coordinate &inputPt, const LinearLocation *minIndex)
Private Member Functions
LinearLocation indexOfFromStart (const geom::Coordinate &inputPt, const LinearLocation *minIndex) const
Private Attributes
const geom::Geometry * linearGeom
Detailed Description
Computes the LinearLocation of the point on a linear Geometry nearest a given Coordinate. The nearest point is not necessarily unique; this class always computes the nearest point closest to the start of the geometry.
Definition at line 40 of file LocationIndexOfPoint.h.
Constructor & Destructor Documentation
geos::linearref::LocationIndexOfPoint::LocationIndexOfPoint (const geom::Geometry * linearGeom)
Definition at line 94 of file LocationIndexOfPoint.cpp.
                                                                      :
     linearGeom(linearGeom)
 {}
Member Function Documentation
LinearLocation geos::linearref::LocationIndexOfPoint::indexOf (const geom::Geometry * linearGeom, const geom::Coordinate & inputPt) static
Definition at line 82 of file LocationIndexOfPoint.cpp.
References indexOf().
Referenced by indexOf(), geos::linearref::LocationIndexedLine::indexOf(), indexOfAfter(), geos::linearref::LocationIndexOfLine::indicesOf(), and geos::linearref::LocationIndexedLine::project().
 {
   LocationIndexOfPoint locater(linearGeom);
   return locater.indexOf(inputPt);
 }
LinearLocation geos::linearref::LocationIndexOfPoint::indexOf (const geom::Coordinate & inputPt) const
Find the nearest location along a linear Geometry to a given point.
Parameters
inputPt the coordinate to locate
Returns
the location of the nearest point
Definition at line 98 of file LocationIndexOfPoint.cpp.
References indexOfFromStart().
 {
   return indexOfFromStart(inputPt, nullptr);
 }
LinearLocation geos::linearref::LocationIndexOfPoint::indexOfAfter (const geom::Geometry * linearGeom, const geom::Coordinate & inputPt, const LinearLocation * minIndex) static
Definition at line 88 of file LocationIndexOfPoint.cpp.
References indexOfAfter().
Referenced by indexOfAfter(), geos::linearref::LocationIndexedLine::indexOfAfter(), and geos::linearref::LocationIndexOfLine::indicesOf().
 {
   LocationIndexOfPoint locater(linearGeom);
   return locater.indexOfAfter(inputPt, minIndex);
 }
LinearLocation geos::linearref::LocationIndexOfPoint::indexOfAfter (const geom::Coordinate & inputPt, const LinearLocation * minIndex) const
Find the nearest LinearLocation along the linear Geometry to a given Coordinate after the specified minimum LinearLocation. If possible the location returned will be strictly greater than the minLocation. If this is not possible, the value returned will equal minLocation. (An example where this is not possible is when minLocation = [end of line]).
Parameters
inputPt the coordinate to locate
minLocation the minimum location for the point location
Returns
the location of the nearest point
Return the minDistanceLocation found. This will not be null, since it was initialized to minLocation
Definition at line 104 of file LocationIndexOfPoint.cpp.
References geos::linearref::LinearLocation::compareTo(), geos::linearref::LinearLocation::getEndLocation(), indexOf(), indexOfFromStart(), and linearGeom.
 {
   if (!minIndex) return indexOf(inputPt);
   // sanity check for minLocation at or past end of line
   LinearLocation endLoc = LinearLocation::getEndLocation(linearGeom);
   if (endLoc.compareTo(*minIndex) <= 0)
     return endLoc;
   LinearLocation closestAfter = indexOfFromStart(inputPt, minIndex);
   if (closestAfter.compareTo(*minIndex) < 0)
   {
     throw util::IllegalArgumentException("computed location is before specified minimum location");
   }
   return closestAfter;
 }
LinearLocation geos::linearref::LocationIndexOfPoint::indexOfFromStart (const geom::Coordinate & inputPt, const LinearLocation * minIndex) const private
Definition at line 41 of file LocationIndexOfPoint.cpp.
References geos::linearref::LinearLocation::compareLocationValues(), geos::geom::LineSegment::distance(), geos::linearref::LinearIterator::hasNext(), geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, and geos::geom::LineSegment::segmentFraction().
Referenced by indexOf(), and indexOfAfter().
 {
   double minDistance = numeric_limits<double>::max();
   int minComponentIndex = 0;
   int minSegmentIndex = 0;
   double minFrac = -1.0;
   LineSegment seg;
   for (LinearIterator it(linearGeom);
       it.hasNext(); it.next())
   {
     if (! it.isEndOfLine())
     {
       seg.p0 = it.getSegmentStart();
       seg.p1 = it.getSegmentEnd();
       double segDistance = seg.distance(inputPt);
       double segFrac = seg.segmentFraction(inputPt);
       int candidateComponentIndex = it.getComponentIndex();
       int candidateSegmentIndex = it.getVertexIndex();
       if (segDistance < minDistance)
       {
         // ensure after minLocation, if any
         if (!minIndex ||
             minIndex->compareLocationValues(candidateComponentIndex, candidateSegmentIndex, segFrac) < 0)
         {
           // otherwise, save this as new minimum
           minComponentIndex = candidateComponentIndex;
           minSegmentIndex = candidateSegmentIndex;
           minFrac = segFrac;
           minDistance = segDistance;
         }
       }
     }
   }
   LinearLocation loc(minComponentIndex, minSegmentIndex, minFrac);
   return loc;
 }
Member Data Documentation
const geom::Geometry* geos::linearref::LocationIndexOfPoint::linearGeom private
Definition at line 44 of file LocationIndexOfPoint.h.
Referenced by indexOfAfter().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/linearref/LocationIndexOfPoint.h
/home/vicky/potree/geos/vicky/src/linearref/LocationIndexOfPoint.cpp