GEOS: geos::geomgraph::index::MonotoneChainIndexer Class Reference
geos::geomgraph::index::MonotoneChainIndexer Class Reference
#include <MonotoneChainIndexer.h>
Public Member Functions
MonotoneChainIndexer ()
void getChainStartIndices (const geom::CoordinateSequence *, std::vector< int > &)
Private Member Functions
int findChainEnd (const geom::CoordinateSequence *pts, int start)
Detailed Description
Definition at line 34 of file MonotoneChainIndexer.h.
Constructor & Destructor Documentation
geos::geomgraph::index::MonotoneChainIndexer::MonotoneChainIndexer () inline
Definition at line 38 of file MonotoneChainIndexer.h.
 {}
Member Function Documentation
int geos::geomgraph::index::MonotoneChainIndexer::findChainEnd (const geom::CoordinateSequence * pts, int start) private
Returns
the index of the last point in the monotone chain
Definition at line 51 of file MonotoneChainIndexer.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
{
   // determine quadrant for chain
   int chainQuad=Quadrant::quadrant(pts->getAt(start),pts->getAt(start + 1));
   int last=start+1;
   while(last<(int)pts->getSize()) {
     // compute quadrant for next possible segment in chain
     int quad=Quadrant::quadrant(pts->getAt(last - 1),pts->getAt(last));
     if (quad!=chainQuad) break;
     last++;
   }
   return last-1;
 }
void geos::geomgraph::index::MonotoneChainIndexer::getChainStartIndices (const geom::CoordinateSequence * pts, std::vector< int > & startIndexList)
Definition at line 31 of file MonotoneChainIndexer.cpp.
References geos::geom::CoordinateSequence::getSize().
Referenced by geos::geomgraph::index::MonotoneChainEdge::MonotoneChainEdge().
 {
   // find the startpoint (and endpoints) of all monotone chains
   // in this edge
   int start=0;
   //vector<int>* startIndexList=new vector<int>();
   startIndexList.push_back(start);
   do {
     int last=findChainEnd(pts,start);
     startIndexList.push_back(last);
     start=last;
   } while(start<(int)pts->getSize()-1);
   // copy list to an array of ints, for efficiency
   //return startIndexList;
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/index/MonotoneChainIndexer.h
/home/vicky/potree/geos/vicky/src/geomgraph/index/MonotoneChainIndexer.cpp