GEOS: geos::util::UnsupportedOperationException Class Reference
geos::util::UnsupportedOperationException Class Reference
Indicates that the requested operation is unsupported.
#include <geos.h>
Public Member Functions
UnsupportedOperationException ()
UnsupportedOperationException (const std::string &msg)
~UnsupportedOperationException () override throw ()
const char * what () const override throw ()
Detailed Description
Indicates that the requested operation is unsupported.
This exception is thrown - for example - when requesting the X or Y member of an empty Point
Definition at line 36 of file UnsupportedOperationException.h.
Constructor & Destructor Documentation
geos::util::UnsupportedOperationException::UnsupportedOperationException () inline
Definition at line 38 of file UnsupportedOperationException.h.
     :
     GEOSException("UnsupportedOperationException", "")
   {}
geos::util::UnsupportedOperationException::UnsupportedOperationException (const std::string & msg) inline
Definition at line 43 of file UnsupportedOperationException.h.
     :
     GEOSException("UnsupportedOperationException", msg)
   {}
geos::util::UnsupportedOperationException::~UnsupportedOperationException () throw () inline override
Definition at line 48 of file UnsupportedOperationException.h.
 {}
Member Function Documentation
const char* geos::util::GEOSException::what () const throw () inline override inherited
Definition at line 63 of file GEOSException.h.
Referenced by geos::operation::overlay::ElevationMatrix::add(), geos::geom::BinaryOp(), geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::snap::SnapIfNeededOverlayOp::getResultGeometry(), geos::operation::polygonize::EdgeRing::getRingInternal(), and geos::precision::EnhancedPrecisionOp::intersection().
   {
     return _msg.c_str();
   }
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/util/UnsupportedOperationException.h