GEOS: geos::geomgraph::NodeMap Class Reference
geos::geomgraph::NodeMap Class Reference
#include <NodeMap.h>
Public Types
typedef std::map< geom::Coordinate *, Node *, geom::CoordinateLessThen > container
typedef container::iterator iterator
typedef container::const_iterator const_iterator
typedef std::pair< geom::Coordinate *, Node * > pair
Public Member Functions
NodeMap (const NodeFactory &newNodeFact)
NodeMap will keep a reference to the NodeFactory, keep it alive for the whole NodeMap lifetime.
virtual ~NodeMap ()
Node * addNode (const geom::Coordinate &coord)
Node * addNode (Node *n)
void add (EdgeEnd *e)
Node * find (const geom::Coordinate &coord) const
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
void getBoundaryNodes (int geomIndex, std::vector< Node * > &bdyNodes) const
std::string print () const
void testInvariant ()
Public Attributes
container nodeMap
const NodeFactory & nodeFact
Private Member Functions
NodeMap (const NodeMap &other)=delete
NodeMap & operator= (const NodeMap &rhs)=delete
Detailed Description
Definition at line 51 of file NodeMap.h.
Member Typedef Documentation
typedef container::const_iterator geos::geomgraph::NodeMap::const_iterator
Definition at line 58 of file NodeMap.h.
typedef std::map<geom::Coordinate*,Node*,geom::CoordinateLessThen> geos::geomgraph::NodeMap::container
Definition at line 54 of file NodeMap.h.
typedef container::iterator geos::geomgraph::NodeMap::iterator
Definition at line 56 of file NodeMap.h.
typedef std::pair<geom::Coordinate*,Node*> geos::geomgraph::NodeMap::pair
Definition at line 60 of file NodeMap.h.
Constructor & Destructor Documentation
geos::geomgraph::NodeMap::NodeMap (const NodeFactory & newNodeFact)
NodeMap will keep a reference to the NodeFactory, keep it alive for the whole NodeMap lifetime.
Definition at line 41 of file NodeMap.cpp.
   :
   nodeFact(newNodeFact)
 {
 #if GEOS_DEBUG
   cerr<<"["<<this<<"] NodeMap::NodeMap"<<endl;
 #endif
 }
geos::geomgraph::NodeMap::~NodeMap () virtual
Definition at line 50 of file NodeMap.cpp.
References nodeMap.
 {
   NodeMap::const_iterator it=nodeMap.begin();
   for (;it!=nodeMap.end();it++) {
     delete it->second;
   }
 }
geos::geomgraph::NodeMap::NodeMap (const NodeMap & other) private delete
Member Function Documentation
void geos::geomgraph::NodeMap::add (EdgeEnd * e)
Definition at line 121 of file NodeMap.cpp.
References geos::geomgraph::Node::add(), addNode(), and geos::geomgraph::EdgeEnd::getCoordinate().
Referenced by geos::geomgraph::PlanarGraph::add(), and geos::operation::relate::RelateComputer::insertEdgeEnds().
 {
   Coordinate& p=e->getCoordinate();
   Node *n=addNode(p);
   n->add(e);
 }
Node * geos::geomgraph::NodeMap::addNode (const geom::Coordinate & coord)
Definition at line 59 of file NodeMap.cpp.
References geos::geomgraph::Node::addZ(), geos::geomgraph::NodeFactory::createNode(), find(), geos::geomgraph::Node::getCoordinate(), nodeFact, nodeMap, geos::geom::Coordinate::toString(), and geos::geom::Coordinate::z.
Referenced by add(), geos::geomgraph::PlanarGraph::addNode(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), and geos::operation::relate::RelateComputer::copyNodesAndLabels().
 {
 #if GEOS_DEBUG
         cerr<<"["<<this<<"] NodeMap::addNode("<<coord.toString()<<")";
 #endif
         Node *node=find(coord);
         if (node==nullptr) {
 #if GEOS_DEBUG
                 cerr<<" is new"<<endl;
 #endif
                 node=nodeFact.createNode(coord);
     Coordinate* c = const_cast<Coordinate *>(
       &(node->getCoordinate()));
                 nodeMap[c]=node;
                 //nodeMap[const_cast<Coordinate *>(&coord)]=node;
         }
         else
         {
 #if GEOS_DEBUG
                 cerr<<" already found ("<<node->getCoordinate().toString()<<") - adding Z"<<endl;
 #endif
                 node->addZ(coord.z);
         }
         return node;
 }
Node * geos::geomgraph::NodeMap::addNode (Node * n)
Definition at line 88 of file NodeMap.cpp.
References geos::geomgraph::Node::addZ(), find(), geos::geomgraph::Node::getCoordinate(), geos::geomgraph::Node::getZ(), geos::geomgraph::Node::mergeLabel(), nodeMap, and geos::geomgraph::Node::print().
 {
   assert(n);
 #if GEOS_DEBUG
   cerr<<"["<<this<<"] NodeMap::addNode("<<n->print()<<")";
 #endif
   Coordinate *c=const_cast<Coordinate *>(&n->getCoordinate());
   Node *node=find(*c);
   if (node==nullptr) {
 #if GEOS_DEBUG
     cerr<<" is new"<<endl;
 #endif
     nodeMap[c]=n;
     return n;
   }
 #if GEOS_DEBUG
   else
   {
     cerr<<" found already, merging label"<<endl;
     const vector<double>&zvals = n->getZ();
     for (unsigned int i=0; i<zvals.size(); i++)
     {
       node->addZ(zvals[i]);
     }
   }
 #endif // GEOS_DEBUG
   node->mergeLabel(*n);
   return node;
 }
const_iterator geos::geomgraph::NodeMap::begin () const inline
Definition at line 81 of file NodeMap.h.
Referenced by geos::operation::relate::RelateComputer::copyNodesAndLabels(), geos::geomgraph::PlanarGraph::getNodeIterator(), and geos::operation::relate::RelateComputer::labelIsolatedNodes().
 { return nodeMap.begin(); }
iterator geos::geomgraph::NodeMap::begin () inline
Definition at line 85 of file NodeMap.h.
 { return nodeMap.begin(); }
const_iterator geos::geomgraph::NodeMap::end () const inline
Definition at line 83 of file NodeMap.h.
Referenced by geos::operation::relate::RelateComputer::copyNodesAndLabels(), and geos::operation::relate::RelateComputer::labelIsolatedNodes().
 { return nodeMap.end(); }
iterator geos::geomgraph::NodeMap::end () inline
Definition at line 87 of file NodeMap.h.
 { return nodeMap.end(); }
Node * geos::geomgraph::NodeMap::find (const geom::Coordinate & coord) const
Definition at line 132 of file NodeMap.cpp.
References nodeMap.
Referenced by addNode(), geos::geomgraph::PlanarGraph::find(), geos::geomgraph::PlanarGraph::isBoundaryNode(), and geos::operation::relate::RelateComputer::labelIntersectionNodes().
 {
   Coordinate *c=const_cast<Coordinate *>(&coord);
   NodeMap::const_iterator found=nodeMap.find(c);
   if (found==nodeMap.end())
     return nullptr;
   else
     return found->second;
 }
void geos::geomgraph::NodeMap::getBoundaryNodes (int geomIndex, std::vector< Node * > & bdyNodes) const
Definition at line 145 of file NodeMap.cpp.
References geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), and nodeMap.
Referenced by geos::geomgraph::GeometryGraph::getBoundaryNodes().
 {
   NodeMap::const_iterator it=nodeMap.begin();
   for (;it!=nodeMap.end();it++) {
     Node *node=it->second;
     if (node->getLabel().getLocation(geomIndex)==Location::BOUNDARY)
       bdyNodes.push_back(node);
   }
 }
NodeMap& geos::geomgraph::NodeMap::operator= (const NodeMap & rhs) private delete
string geos::geomgraph::NodeMap::print () const
Definition at line 156 of file NodeMap.cpp.
References nodeMap, and geos::geomgraph::Node::print().
 {
   string out="";
   NodeMap::const_iterator it=nodeMap.begin();
   for (;it!=nodeMap.end();it++) {
     Node *node=it->second;
     out+=node->print();
   }
   return out;
 }
void geos::geomgraph::NodeMap::testInvariant () inline
Definition at line 94 of file NodeMap.h.
References geos::geomgraph::Node::getCoordinate().
   {
 #ifndef NDEBUG
     // Each Coordinate key is a pointer inside the Node value
     for (iterator it=begin(), itEnd=end(); it != itEnd; ++it)
     {
       pair p = *it;
       geomgraph::Node* n = p.second;
       geom::Coordinate* c = const_cast<geom::Coordinate*>(
         &(n->getCoordinate())
       );
       assert(p.first == c);
     }
 #endif
   }
Member Data Documentation
const NodeFactory& geos::geomgraph::NodeMap::nodeFact
Definition at line 64 of file NodeMap.h.
Referenced by addNode().
container geos::geomgraph::NodeMap::nodeMap
Definition at line 62 of file NodeMap.h.
Referenced by geos::operation::overlay::PolygonBuilder::add(), addNode(), geos::operation::overlay::OverlayOp::computeLabelling(), geos::operation::relate::RelateNodeGraph::copyNodesAndLabels(), find(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), getBoundaryNodes(), geos::geomgraph::PlanarGraph::getNodes(), geos::operation::overlay::OverlayOp::labelIncompleteNodes(), geos::operation::relate::RelateComputer::labelNodeEdges(), geos::geomgraph::PlanarGraph::linkAllDirectedEdges(), geos::geomgraph::PlanarGraph::linkResultDirectedEdges(), geos::operation::overlay::OverlayOp::mergeSymLabels(), print(), geos::operation::relate::RelateComputer::updateIM(), geos::operation::overlay::OverlayOp::updateNodeLabelling(), and ~NodeMap().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/NodeMap.h
/home/vicky/potree/geos/vicky/src/geomgraph/NodeMap.cpp