GEOS: geos::operation::distance::IndexedFacetDistance Class Reference
geos::operation::distance::IndexedFacetDistance Class Reference
#include <IndexedFacetDistance.h>
Public Member Functions
IndexedFacetDistance (const geom::Geometry *g)
double getDistance (const geom::Geometry *g) const
~IndexedFacetDistance ()
Static Public Member Functions
static double distance (const geom::Geometry *g1, const geom::Geometry *g2)
Private Attributes
std::unique_ptr< geos::index::strtree::STRtree > cachedTree
Detailed Description
Definition at line 27 of file IndexedFacetDistance.h.
Constructor & Destructor Documentation
geos::operation::distance::IndexedFacetDistance::IndexedFacetDistance (const geom::Geometry * g) inline
Definition at line 29 of file IndexedFacetDistance.h.
References geos::operation::intersection::distance().
                                                              :
                         cachedTree(FacetSequenceTreeBuilder::build(g))
                         {}
geos::operation::distance::IndexedFacetDistance::~IndexedFacetDistance ()
Definition at line 58 of file IndexedFacetDistance.cpp.
References geos::operation::distance::deleter.
{
                 cachedTree->iterate(deleter);
             }
Member Function Documentation
double geos::operation::distance::IndexedFacetDistance::distance (const geom::Geometry * g1, const geom::Geometry * g2) static
Definition at line 35 of file IndexedFacetDistance.cpp.
References getDistance().
{
                 IndexedFacetDistance ifd(g1);
                 return ifd.getDistance(g2);
             }
double geos::operation::distance::IndexedFacetDistance::getDistance (const geom::Geometry * g) const
Definition at line 40 of file IndexedFacetDistance.cpp.
References geos::operation::distance::deleter, geos::operation::intersection::distance(), and geos::index::strtree::ItemBoundable::getItem().
Referenced by distance().
{
                 struct : public ItemDistance {
                     double distance(const ItemBoundable* item1, const ItemBoundable* item2) override {
                         return static_cast<const FacetSequence*>(item1->getItem())->distance(*static_cast<const FacetSequence*>(item2->getItem()));
                     }
                 } itemDistance;
                 std::unique_ptr<STRtree> tree2(FacetSequenceTreeBuilder::build(g));
                 std::pair<const void*, const void*> obj = cachedTree->nearestNeighbour(tree2.get(), dynamic_cast<ItemDistance*>(&itemDistance));
                 double distance = static_cast<const FacetSequence*>(obj.first)->distance(*static_cast<const FacetSequence*>(obj.second));
                 tree2->iterate(deleter);
                 return distance;
             }
Member Data Documentation
std::unique_ptr<geos::index::strtree::STRtree> geos::operation::distance::IndexedFacetDistance::cachedTree private
Definition at line 40 of file IndexedFacetDistance.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/distance/IndexedFacetDistance.h
/home/vicky/potree/geos/vicky/src/operation/distance/IndexedFacetDistance.cpp