GEOS: geos::operation::valid::IndexedNestedRingTester Class Reference
geos::operation::valid::IndexedNestedRingTester Class Reference
Tests whether any of a set of LinearRings are nested inside another ring in the set, using a spatial index to speed up the comparisons.
#include <IndexedNestedRingTester.h>
Public Member Functions
IndexedNestedRingTester (geomgraph::GeometryGraph *newGraph)
~IndexedNestedRingTester ()
const geom::Coordinate * getNestedPoint () const
void add (const geom::LinearRing *ring)
bool isNonNested ()
Private Member Functions
void buildIndex ()
Private Attributes
geomgraph::GeometryGraph * graph
Externally owned.
std::vector< const geom::LinearRing * > rings
Ownership of this vector elements are externally owned.
geos::index::SpatialIndex * index
const geom::Coordinate * nestedPt
Detailed Description
Tests whether any of a set of LinearRings are nested inside another ring in the set, using a spatial index to speed up the comparisons.
Definition at line 49 of file IndexedNestedRingTester.h.
Constructor & Destructor Documentation
geos::operation::valid::IndexedNestedRingTester::IndexedNestedRingTester (geomgraph::GeometryGraph * newGraph) inline
Definition at line 53 of file IndexedNestedRingTester.h.
     :
     graph(newGraph),
     //totalEnv(0),
     index(nullptr),
     nestedPt(nullptr)
   {
   }
geos::operation::valid::IndexedNestedRingTester::~IndexedNestedRingTester ()
Definition at line 98 of file IndexedNestedRingTester.cpp.
 {
   delete index;
   //delete totalEnv;
 }
Member Function Documentation
void geos::operation::valid::IndexedNestedRingTester::add (const geom::LinearRing * ring) inline
Parameters
ring : ownership retained by caller
Definition at line 76 of file IndexedNestedRingTester.h.
Referenced by geos::operation::valid::IsValidOp::checkHolesNotNested().
   {
     rings.push_back(ring);
   }
void geos::operation::valid::IndexedNestedRingTester::buildIndex () private
Definition at line 105 of file IndexedNestedRingTester.cpp.
References geos::geom::Geometry::getEnvelopeInternal().
 {
   delete index;
   index = new index::strtree::STRtree();
   for (size_t i=0, n=rings.size(); i<n; ++i)
   {
     const geom::LinearRing* ring = rings[i];
     const geom::Envelope* env = ring->getEnvelopeInternal();
     index->insert(env, (void*)ring);
   }
 }
const geom::Coordinate* geos::operation::valid::IndexedNestedRingTester::getNestedPoint () const inline
Definition at line 70 of file IndexedNestedRingTester.h.
Referenced by geos::operation::valid::IsValidOp::checkHolesNotNested().
   {
     return nestedPt;
   }
bool geos::operation::valid::IndexedNestedRingTester::isNonNested ()
If no non-node pts can be found, this means that the searchRing touches ALL of the innerRing vertices. This indicates an invalid polygon, since either the two holes create a disconnected interior, or they touch in an infinite number of points (i.e. along a line segment). Both of these cases are caught by other tests, so it is safe to simply skip this situation here.
Definition at line 39 of file IndexedNestedRingTester.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::intersects(), and geos::algorithm::CGAlgorithms::isPointInRing().
Referenced by geos::operation::valid::IsValidOp::checkHolesNotNested().
 {
   buildIndex();
   for (size_t i=0, n=rings.size(); i<n; ++i)
   {
     const geom::LinearRing* innerRing = rings[i];
     const geom::CoordinateSequence *innerRingPts=innerRing->getCoordinatesRO();
     std::vector<void*> results;
     index->query(innerRing->getEnvelopeInternal(), results);
     for (size_t j=0, jn=results.size(); j<jn; ++j)
     {
       const geom::LinearRing* searchRing = static_cast<const geom::LinearRing*>(results[j]);
       const geom::CoordinateSequence *searchRingPts=searchRing->getCoordinatesRO();
       if (innerRing==searchRing)
         continue;
       if (!innerRing->getEnvelopeInternal()->intersects(
         searchRing->getEnvelopeInternal()))
       {
         continue;
       }
                         const geom::Coordinate *innerRingPt =
         IsValidOp::findPtNotNode(innerRingPts,
                searchRing,
                graph);
         if ( ! innerRingPt ) continue;
                         // Unable to find a ring point not a node of
       // the search ring
       assert(innerRingPt!=nullptr);
       bool isInside = algorithm::CGAlgorithms::isPointInRing(
           *innerRingPt, searchRingPts);
       if (isInside) {
         nestedPt = innerRingPt;
         return false;
       }
     }
   }
   return true;
 }
Member Data Documentation
geomgraph::GeometryGraph* geos::operation::valid::IndexedNestedRingTester::graph private
Externally owned.
Definition at line 86 of file IndexedNestedRingTester.h.
geos::index::SpatialIndex* geos::operation::valid::IndexedNestedRingTester::index private
Definition at line 95 of file IndexedNestedRingTester.h.
const geom::Coordinate* geos::operation::valid::IndexedNestedRingTester::nestedPt private
Definition at line 98 of file IndexedNestedRingTester.h.
std::vector<const geom::LinearRing*> geos::operation::valid::IndexedNestedRingTester::rings private
Ownership of this vector elements are externally owned.
Definition at line 89 of file IndexedNestedRingTester.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/src/operation/valid/IndexedNestedRingTester.h
/home/vicky/potree/geos/vicky/src/operation/valid/IndexedNestedRingTester.cpp