GEOS: geos::geomgraph::index::SimpleSweepLineIntersector Class Reference
geos::geomgraph::index::SimpleSweepLineIntersector Class Reference
Finds all intersections in one or two sets of edges, using a simple x-axis sweepline algorithm.
#include <SimpleSweepLineIntersector.h>
Public Member Functions
SimpleSweepLineIntersector ()
~SimpleSweepLineIntersector () override
void computeIntersections (std::vector< Edge * > *edges, SegmentIntersector *si, bool testAllSegments) override
void computeIntersections (std::vector< Edge * > *edges0, std::vector< Edge * > *edges1, SegmentIntersector *si) override
Private Member Functions
void add (std::vector< Edge * > *edges)
void add (std::vector< Edge * > *edges, void *edgeSet)
void add (Edge *edge, void *edgeSet)
void prepareEvents ()
void computeIntersections (SegmentIntersector *si)
void processOverlaps (int start, int end, SweepLineEvent *ev0, SegmentIntersector *si)
Private Attributes
std::vector< SweepLineEvent * > events
int nOverlaps
Detailed Description
Finds all intersections in one or two sets of edges, using a simple x-axis sweepline algorithm.
While still O(n^2) in the worst case, this algorithm drastically improves the average-case time.
Definition at line 51 of file SimpleSweepLineIntersector.h.
Constructor & Destructor Documentation
geos::geomgraph::index::SimpleSweepLineIntersector::SimpleSweepLineIntersector ()
Definition at line 32 of file SimpleSweepLineIntersector.cpp.
                                                       :
   //events(new vector<SweepLineEvent*>()),
   nOverlaps(0)
 {
 }
geos::geomgraph::index::SimpleSweepLineIntersector::~SimpleSweepLineIntersector () override
Definition at line 38 of file SimpleSweepLineIntersector.cpp.
References events.
 {
   for(unsigned int i=0; i<events.size(); ++i)
     delete events[i];
   //delete events;
 }
Member Function Documentation
void geos::geomgraph::index::SimpleSweepLineIntersector::add (std::vector< Edge * > * edges) private
Definition at line 65 of file SimpleSweepLineIntersector.cpp.
Referenced by add(), and computeIntersections().
 {
   for (unsigned int i=0; i<edges->size(); ++i)
   {
     Edge *edge=(*edges)[i];
     // edge is its own group
     add(edge,edge);
   }
 }
void geos::geomgraph::index::SimpleSweepLineIntersector::add (std::vector< Edge * > * edges, void * edgeSet) private
Definition at line 76 of file SimpleSweepLineIntersector.cpp.
References add().
 {
   for (unsigned int i=0; i<edges->size(); ++i)
   {
     Edge *edge=(*edges)[i];
     add(edge,edgeSet);
   }
 }
void geos::geomgraph::index::SimpleSweepLineIntersector::add (Edge * edge, void * edgeSet) private
Definition at line 86 of file SimpleSweepLineIntersector.cpp.
References events, geos::geomgraph::Edge::getCoordinates(), geos::geomgraph::index::SweepLineSegment::getMaxX(), geos::geomgraph::index::SweepLineSegment::getMinX(), and geos::geom::CoordinateSequence::getSize().
 {
   const CoordinateSequence *pts=edge->getCoordinates();
   std::size_t n=pts->getSize()-1;
   for(std::size_t i=0; i<n; ++i)
   {
     SweepLineSegment *ss=new SweepLineSegment(edge, static_cast<int>(i));
     SweepLineEvent *insertEvent=new SweepLineEvent(edgeSet, ss->getMinX(), nullptr, ss);
     events.push_back(insertEvent);
     events.push_back(new SweepLineEvent(edgeSet, ss->getMaxX(), insertEvent, ss));
   }
 }
void geos::geomgraph::index::SimpleSweepLineIntersector::computeIntersections (std::vector< Edge * > * edges, SegmentIntersector * si, bool testAllSegments) override virtual
Computes all self-intersections between edges in a set of edges, allowing client to choose whether self-intersections are computed.
Parameters
edges a list of edges to test for intersections
si the SegmentIntersector to use
testAllSegments true if self-intersections are to be tested as well
Implements geos::geomgraph::index::EdgeSetIntersector.
Definition at line 46 of file SimpleSweepLineIntersector.cpp.
References add().
Referenced by computeIntersections().
 {
   if (testAllSegments)
     add(edges,nullptr);
   else
     add(edges);
   computeIntersections(si);
 }
void geos::geomgraph::index::SimpleSweepLineIntersector::computeIntersections (std::vector< Edge * > * edges0, std::vector< Edge * > * edges1, SegmentIntersector * si) override virtual
Computes all mutual intersections between two sets of edges
Implements geos::geomgraph::index::EdgeSetIntersector.
Definition at line 57 of file SimpleSweepLineIntersector.cpp.
References add(), and computeIntersections().
 {
   add(edges0,edges0);
   add(edges1,edges1);
   computeIntersections(si);
 }
void geos::geomgraph::index::SimpleSweepLineIntersector::computeIntersections (SegmentIntersector * si) private
Definition at line 119 of file SimpleSweepLineIntersector.cpp.
References events, geos::geomgraph::index::SweepLineEvent::getDeleteEventIndex(), geos::geomgraph::index::SweepLineEvent::isInsert(), nOverlaps, prepareEvents(), and processOverlaps().
 {
   nOverlaps=0;
   prepareEvents();
   for(unsigned int i=0; i<events.size(); ++i)
   {
     SweepLineEvent *ev=events[i];
     if (ev->isInsert())
     {
       processOverlaps(i,ev->getDeleteEventIndex(),ev,si);
     }
   }
 }
void geos::geomgraph::index::SimpleSweepLineIntersector::prepareEvents () private
Because Delete Events have a link to their corresponding Insert event, it is possible to compute exactly the range of events which must be compared to a given Insert event object.
Definition at line 105 of file SimpleSweepLineIntersector.cpp.
References events, geos::geomgraph::index::SweepLineEvent::getInsertEvent(), geos::geomgraph::index::SweepLineEvent::isDelete(), and geos::geomgraph::index::SweepLineEvent::setDeleteEventIndex().
Referenced by computeIntersections().
 {
   sort(events.begin(), events.end(), SweepLineEventLessThen());
   for(unsigned int i=0; i<events.size(); ++i )
   {
     SweepLineEvent *ev=events[i];
     if (ev->isDelete())
     {
       ev->getInsertEvent()->setDeleteEventIndex(i);
     }
   }
 }
void geos::geomgraph::index::SimpleSweepLineIntersector::processOverlaps (int start, int end, SweepLineEvent * ev0, SegmentIntersector * si) private
Since we might need to test for self-intersections, include current insert event object in list of event objects to test. Last index can be skipped, because it must be a Delete event.
Definition at line 134 of file SimpleSweepLineIntersector.cpp.
References geos::geomgraph::index::SweepLineSegment::computeIntersections(), geos::geomgraph::index::SweepLineEvent::edgeSet, events, geos::geomgraph::index::SweepLineEvent::getObject(), geos::geomgraph::index::SweepLineEvent::isInsert(), and nOverlaps.
Referenced by computeIntersections().
 {
   SweepLineSegment *ss0=(SweepLineSegment*) ev0->getObject();
   for(int i=start; i<end; ++i)
   {
     SweepLineEvent *ev1=events[i];
     if (ev1->isInsert())
     {
       SweepLineSegment *ss1=(SweepLineSegment*) ev1->getObject();
       if (ev0->edgeSet==nullptr || (ev0->edgeSet!=ev1->edgeSet))
       {
         ss0->computeIntersections(ss1,si);
         nOverlaps++;
       }
     }
   }
 }
Member Data Documentation
std::vector<SweepLineEvent*> geos::geomgraph::index::SimpleSweepLineIntersector::events private
Definition at line 71 of file SimpleSweepLineIntersector.h.
Referenced by add(), computeIntersections(), prepareEvents(), processOverlaps(), and ~SimpleSweepLineIntersector().
int geos::geomgraph::index::SimpleSweepLineIntersector::nOverlaps private
Definition at line 74 of file SimpleSweepLineIntersector.h.
Referenced by computeIntersections(), and processOverlaps().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/index/SimpleSweepLineIntersector.h
/home/vicky/potree/geos/vicky/src/geomgraph/index/SimpleSweepLineIntersector.cpp