GEOS: geos::simplify::TaggedLineStringSimplifier Class Reference
geos::simplify::TaggedLineStringSimplifier Class Reference
Simplifies a TaggedLineString, preserving topology (in the sense that no new intersections are introduced). Uses the recursive Douglas-Peucker algorithm.
#include <TaggedLineStringSimplifier.h>
Public Member Functions
TaggedLineStringSimplifier (LineSegmentIndex *inputIndex, LineSegmentIndex *outputIndex)
void setDistanceTolerance (double d)
Sets the distance tolerance for the simplification.
void simplify (TaggedLineString *line)
Private Member Functions
void simplifySection (std::size_t i, std::size_t j, std::size_t depth)
bool hasBadIntersection (const TaggedLineString *parentLine, const std::vector< std::size_t > &sectionIndex, const geom::LineSegment &candidateSeg)
bool hasBadInputIntersection (const TaggedLineString *parentLine, const std::vector< std::size_t > &sectionIndex, const geom::LineSegment &candidateSeg)
bool hasBadOutputIntersection (const geom::LineSegment &candidateSeg)
bool hasInteriorIntersection (const geom::LineSegment &seg0, const geom::LineSegment &seg1) const
std::unique_ptr< TaggedLineSegment > flatten (std::size_t start, std::size_t end)
void remove (const TaggedLineString *line, std::size_t start, std::size_t end)
Remove the segs in the section of the line.
Static Private Member Functions
static std::size_t findFurthestPoint (const geom::CoordinateSequence *pts, std::size_t i, std::size_t j, double &maxDistance)
static bool isInLineSection (const TaggedLineString *parentLine, const std::vector< std::size_t > &sectionIndex, const TaggedLineSegment *seg)
Tests whether a segment is in a section of a TaggedLineString.
Private Attributes
LineSegmentIndex * inputIndex
LineSegmentIndex * outputIndex
std::unique_ptr< algorithm::LineIntersector > li
TaggedLineString * line
non-const as segments are possibly added to it
const geom::CoordinateSequence * linePts
double distanceTolerance
Detailed Description
Simplifies a TaggedLineString, preserving topology (in the sense that no new intersections are introduced). Uses the recursive Douglas-Peucker algorithm.
Definition at line 63 of file TaggedLineStringSimplifier.h.
Constructor & Destructor Documentation
geos::simplify::TaggedLineStringSimplifier::TaggedLineStringSimplifier (LineSegmentIndex * inputIndex, LineSegmentIndex * outputIndex)
Definition at line 48 of file TaggedLineStringSimplifier.cpp.
   :
   inputIndex(nInputIndex),
   outputIndex(nOutputIndex),
   li(new algorithm::LineIntersector()),
   line(nullptr),
   linePts(nullptr),
   distanceTolerance(0.0)
 {
 }
Member Function Documentation
std::size_t geos::simplify::TaggedLineStringSimplifier::findFurthestPoint (const geom::CoordinateSequence * pts, std::size_t i, std::size_t j, double & maxDistance) static private
Definition at line 312 of file TaggedLineStringSimplifier.cpp.
References geos::operation::intersection::distance(), and geos::geom::CoordinateSequence::getAt().
Referenced by simplifySection().
 {
   LineSegment seg(pts->getAt(i), pts->getAt(j));
 #if GEOS_DEBUG
   std::cerr << __FUNCTION__ << "segment " << seg
             << std::endl;
 #endif
   double maxDist = -1.0;
   std::size_t maxIndex = i;
   for (std::size_t k = i + 1; k < j; k++)
   {
     const Coordinate& midPt = pts->getAt(k);
     double distance = seg.distance(midPt);
 #if GEOS_DEBUG
     std::cerr << "dist to " << midPt
         << ": " << distance
         << std::endl;
 #endif
     if (distance > maxDist) {
 #if GEOS_DEBUG
       std::cerr << "this is max"
           << std::endl;
 #endif
       maxDist = distance;
       maxIndex = k;
     }
   }
   maxDistance = maxDist;
   return maxIndex;
 }
unique_ptr< TaggedLineSegment > geos::simplify::TaggedLineStringSimplifier::flatten (std::size_t start, std::size_t end) private
Definition at line 178 of file TaggedLineStringSimplifier.cpp.
References geos::simplify::LineSegmentIndex::add(), geos::geom::CoordinateSequence::getAt(), line, linePts, and outputIndex.
Referenced by simplifySection().
 {
   // make a new segment for the simplified geometry
   const Coordinate& p0 = linePts->getAt(start);
   const Coordinate& p1 = linePts->getAt(end);
   unique_ptr<TaggedLineSegment> newSeg(new TaggedLineSegment(p0, p1));
   // update the indexes
   remove(line, start, end);
   outputIndex->add(newSeg.get());
   return newSeg;
 }
bool geos::simplify::TaggedLineStringSimplifier::hasBadInputIntersection (const TaggedLineString * parentLine, const std::vector< std::size_t > & sectionIndex, const geom::LineSegment & candidateSeg) private
Definition at line 242 of file TaggedLineStringSimplifier.cpp.
References hasInteriorIntersection(), inputIndex, isInLineSection(), and geos::simplify::LineSegmentIndex::query().
Referenced by hasBadIntersection().
 {
   unique_ptr< vector<LineSegment*> > querySegs =
     inputIndex->query(&candidateSeg);
   for (vector<LineSegment*>::iterator
       it = querySegs->begin(), iEnd = querySegs->end();
       it != iEnd;
       ++it)
   {
     assert(*it);
     assert(dynamic_cast<TaggedLineSegment*>(*it));
     TaggedLineSegment* querySeg =
       static_cast<TaggedLineSegment*>(*it);
     if (hasInteriorIntersection(*querySeg, candidateSeg))
     {
       if ( isInLineSection(parentLine,
           sectionIndex, querySeg) )
       {
         continue;
       }
       return true;
     }
   }
   return false;
 }
bool geos::simplify::TaggedLineStringSimplifier::hasBadIntersection (const TaggedLineString * parentLine, const std::vector< std::size_t > & sectionIndex, const geom::LineSegment & candidateSeg) private
Definition at line 192 of file TaggedLineStringSimplifier.cpp.
References hasBadInputIntersection(), and hasBadOutputIntersection().
Referenced by simplifySection().
 {
   if (hasBadOutputIntersection(candidateSeg))
     return true;
   if (hasBadInputIntersection(parentLine, sectionIndex, candidateSeg))
     return true;
   return false;
 }
bool geos::simplify::TaggedLineStringSimplifier::hasBadOutputIntersection (const geom::LineSegment & candidateSeg) private
Definition at line 208 of file TaggedLineStringSimplifier.cpp.
References hasInteriorIntersection(), outputIndex, and geos::simplify::LineSegmentIndex::query().
Referenced by hasBadIntersection().
 {
   unique_ptr< vector<LineSegment*> > querySegs =
     outputIndex->query(&candidateSeg);
   for (vector<LineSegment*>::iterator
       it = querySegs->begin(), iEnd = querySegs->end();
       it != iEnd;
       ++it)
   {
     LineSegment* querySeg = *it;
     assert(querySeg);
     if (hasInteriorIntersection(*querySeg, candidateSeg))
     {
       return true;
     }
   }
   return false;
 }
bool geos::simplify::TaggedLineStringSimplifier::hasInteriorIntersection (const geom::LineSegment & seg0, const geom::LineSegment & seg1) const private
Definition at line 232 of file TaggedLineStringSimplifier.cpp.
References li, geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
Referenced by hasBadInputIntersection(), and hasBadOutputIntersection().
 {
   li->computeIntersection(seg0.p0, seg0.p1, seg1.p0, seg1.p1);
   return li->isInteriorIntersection();
 }
bool geos::simplify::TaggedLineStringSimplifier::isInLineSection (const TaggedLineString * parentLine, const std::vector< std::size_t > & sectionIndex, const TaggedLineSegment * seg) static private
Tests whether a segment is in a section of a TaggedLineString.
Parameters
line
sectionIndex
seg
Returns
Definition at line 278 of file TaggedLineStringSimplifier.cpp.
References geos::simplify::TaggedLineSegment::getIndex(), geos::simplify::TaggedLineSegment::getParent(), and geos::simplify::TaggedLineString::getParent().
Referenced by hasBadInputIntersection().
 {
   // not in this line
   if (seg->getParent() != line->getParent())
     return false;
   std::size_t segIndex = seg->getIndex();
   if (segIndex >= sectionIndex[0] && segIndex < sectionIndex[1])
     return true;
   return false;
 }
void geos::simplify::TaggedLineStringSimplifier::remove (const TaggedLineString * line, std::size_t start, std::size_t end) private
Remove the segs in the section of the line.
Parameters
line
pts
sectionStartIndex
sectionEndIndex
Definition at line 296 of file TaggedLineStringSimplifier.cpp.
References geos::simplify::TaggedLineString::getSegment(), inputIndex, and geos::simplify::LineSegmentIndex::remove().
 {
   assert(end <= line->getSegments().size() );
   assert(start < end); // I'm not sure this should always be true
   for (std::size_t i = start; i < end; i++)
   {
     const TaggedLineSegment* seg = line->getSegment(i);
     inputIndex->remove(seg);
   }
 }
void geos::simplify::TaggedLineStringSimplifier::setDistanceTolerance (double d) inline
Sets the distance tolerance for the simplification.
All vertices in the simplified geometry will be within this distance of the original geometry.
Parameters
d the approximation tolerance to use
Definition at line 158 of file TaggedLineStringSimplifier.h.
 {
   distanceTolerance = d;
 }
void geos::simplify::TaggedLineStringSimplifier::simplify (TaggedLineString * line)
Simplifies the given TaggedLineString using the distance tolerance specified.
Parameters
line the linestring to simplify
Definition at line 63 of file TaggedLineStringSimplifier.cpp.
References geos::simplify::TaggedLineString::getParentCoordinates(), line, linePts, simplifySection(), and geos::geom::CoordinateSequence::size().
 {
   assert(nLine);
   line = nLine;
   linePts = line->getParentCoordinates();
   assert(linePts);
 #if GEOS_DEBUG
   std::cerr << "TaggedLineStringSimplifier[" << this << "] "
        << " TaggedLineString[" << line << "] "
        << " has " << linePts->size() << " coords in input"
        << std::endl;
 #endif
   if ( ! linePts->size() ) return;
   simplifySection(0, linePts->size() - 1, 0);
 }
void geos::simplify::TaggedLineStringSimplifier::simplifySection (std::size_t i, std::size_t j, std::size_t depth) private
Following logic ensures that there is enough points in the output line. If there is already more points than the minimum, there's nothing to check. Otherwise, if in the worst case there wouldn't be enough points, don't flatten this segment (which avoids the worst case scenario)
Definition at line 86 of file TaggedLineStringSimplifier.cpp.
References geos::simplify::TaggedLineString::addToResult(), geos::operation::intersection::distance(), distanceTolerance, findFurthestPoint(), flatten(), geos::geom::CoordinateSequence::getAt(), geos::simplify::TaggedLineString::getMinimumSize(), geos::simplify::TaggedLineString::getResultSize(), geos::simplify::TaggedLineString::getSegment(), hasBadIntersection(), line, and linePts.
Referenced by simplify().
 {
   depth += 1;
 #if GEOS_DEBUG
   std::cerr << "TaggedLineStringSimplifier[" << this << "] "
             << " simplifying section " << i << "-" << j
             << std::endl;
 #endif
   vector<std::size_t> sectionIndex(2);
   if((i+1) == j)
   {
 #if GEOS_DEBUG
     std::cerr << "single segment, no flattening"
               << std::endl;
 #endif
     unique_ptr<TaggedLineSegment> newSeg(new
       TaggedLineSegment(*(line->getSegment(i))));
     line->addToResult(std::move(newSeg));
     // leave this segment in the input index, for efficiency
     return;
   }
   bool isValidToSimplify = true;
   if (line->getResultSize() < line->getMinimumSize())
   {
     std::size_t worstCaseSize = depth + 1;
     if (worstCaseSize < line->getMinimumSize())
       isValidToSimplify = false;
   }
   double distance;
   // pass distance by ref
   std::size_t furthestPtIndex = findFurthestPoint(linePts, i, j, distance);
 #if GEOS_DEBUG
   std::cerr << "furthest point " << furthestPtIndex
             << " at distance " << distance
             << std::endl;
 #endif
   // flattening must be less than distanceTolerance
   if ( distance > distanceTolerance ) isValidToSimplify = false;
   // test if flattened section would cause intersection
   LineSegment candidateSeg(linePts->getAt(i), linePts->getAt(j));
   sectionIndex[0] = i;
   sectionIndex[1] = j;
   if (hasBadIntersection(line, sectionIndex, candidateSeg))
       isValidToSimplify = false;
   if (isValidToSimplify)
   {
     unique_ptr<TaggedLineSegment> newSeg = flatten(i, j);
 #if GEOS_DEBUG
     std::cerr << "isValidToSimplify, adding seg "
         << newSeg->p0 << ", " << newSeg->p1
         << " to TaggedLineSegment["<<line<<"] result "
         << std::endl;
 #endif
     line->addToResult(std::move(newSeg));
     return;
   }
   simplifySection(i, furthestPtIndex, depth);
   simplifySection(furthestPtIndex, j, depth);
 }
Member Data Documentation
double geos::simplify::TaggedLineStringSimplifier::distanceTolerance private
Definition at line 104 of file TaggedLineStringSimplifier.h.
Referenced by simplifySection().
LineSegmentIndex* geos::simplify::TaggedLineStringSimplifier::inputIndex private
Definition at line 92 of file TaggedLineStringSimplifier.h.
Referenced by hasBadInputIntersection(), and remove().
std::unique_ptr<algorithm::LineIntersector> geos::simplify::TaggedLineStringSimplifier::li private
Definition at line 97 of file TaggedLineStringSimplifier.h.
Referenced by hasInteriorIntersection().
TaggedLineString* geos::simplify::TaggedLineStringSimplifier::line private
non-const as segments are possibly added to it
Definition at line 100 of file TaggedLineStringSimplifier.h.
Referenced by flatten(), simplify(), and simplifySection().
const geom::CoordinateSequence* geos::simplify::TaggedLineStringSimplifier::linePts private
Definition at line 102 of file TaggedLineStringSimplifier.h.
Referenced by flatten(), simplify(), and simplifySection().
LineSegmentIndex* geos::simplify::TaggedLineStringSimplifier::outputIndex private
Definition at line 95 of file TaggedLineStringSimplifier.h.
Referenced by flatten(), and hasBadOutputIntersection().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/simplify/TaggedLineStringSimplifier.h
/home/vicky/potree/geos/vicky/src/simplify/TaggedLineStringSimplifier.cpp