GEOS: geos::operation::predicate::LineIntersectsVisitor Class Reference
geos::operation::predicate::LineIntersectsVisitor Class Reference
Public Member Functions
LineIntersectsVisitor (const geom::Polygon &rect)
bool intersects () const
void applyTo (const Geometry &geom)
Protected Member Functions
void visit (const geom::Geometry &geom) override
bool isDone () override
Private Member Functions
void computeSegmentIntersection (const geom::Geometry &geom)
LineIntersectsVisitor (const LineIntersectsVisitor &other)
LineIntersectsVisitor & operator= (const LineIntersectsVisitor &rhs)
Private Attributes
const geom::Envelope & rectEnv
const geom::LineString & rectLine
bool intersectsVar
Detailed Description
Definition at line 196 of file RectangleIntersects.cpp.
Constructor & Destructor Documentation
geos::operation::predicate::LineIntersectsVisitor::LineIntersectsVisitor (const LineIntersectsVisitor & other) private
geos::operation::predicate::LineIntersectsVisitor::LineIntersectsVisitor (const geom::Polygon & rect) inline
Definition at line 242 of file RectangleIntersects.cpp.
     :
     //rectangle(rect),
     rectEnv(*(rect.getEnvelopeInternal())),
     rectLine(*(rect.getExteriorRing())),
     intersectsVar(false)
     //rectSeq(*(rect.getExteriorRing()->getCoordinatesRO()))
     {}
Member Function Documentation
void geos::geom::util::ShortCircuitedGeometryVisitor::applyTo (const Geometry & geom) inherited
Definition at line 31 of file ShortCircuitedGeometryVisitor.cpp.
References geos::geom::Geometry::getGeometryN(), and geos::geom::Geometry::getNumGeometries().
Referenced by geos::operation::predicate::RectangleIntersects::intersects().
 {
   for (std::size_t i=0, n=geom.getNumGeometries(); i<n; ++i)
   {
     const Geometry *element = geom.getGeometryN(i);
     if (dynamic_cast<const GeometryCollection*>(element))
     {
       applyTo(*element);
     }
     else
     {
       // calls the abstract virtual
       visit(*element);
       if (isDone()) done = true;
     }
     if ( done ) return;
   }
 }
void geos::operation::predicate::LineIntersectsVisitor::computeSegmentIntersection (const geom::Geometry & geom) inline private
Definition at line 206 of file RectangleIntersects.cpp.
References geos::operation::predicate::SegmentIntersectionTester::hasIntersectionWithLineStrings(), and geos::operation::predicate::EnvelopeIntersectsVisitor::operator=().
   {
     using geos::geom::util::LinearComponentExtracter;
     // check segment intersection
     // get all lines from geom (e.g. if it's a multi-ring polygon)
     geom::LineString::ConstVect lines;
     LinearComponentExtracter::getLines(geom, lines);
     SegmentIntersectionTester si;
     if ( si.hasIntersectionWithLineStrings(rectLine, lines) )
     {
       intersectsVar = true;
       return;
     }
   }
bool geos::operation::predicate::LineIntersectsVisitor::intersects () const inline
Reports whether any segment intersection exists.
Returns
true if a segment intersection exists false if no segment intersection exists
Definition at line 257 of file RectangleIntersects.cpp.
References geos::operation::predicate::EnvelopeIntersectsVisitor::intersectsVar.
Referenced by geos::operation::predicate::RectangleIntersects::intersects().
 { return intersectsVar; }
bool geos::operation::predicate::LineIntersectsVisitor::isDone () inline override protected virtual
Implements geos::geom::util::ShortCircuitedGeometryVisitor.
Definition at line 238 of file RectangleIntersects.cpp.
References geos::operation::predicate::EnvelopeIntersectsVisitor::intersectsVar.
 { return intersectsVar; }
LineIntersectsVisitor& geos::operation::predicate::LineIntersectsVisitor::operator= (const LineIntersectsVisitor & rhs) private
void geos::operation::predicate::LineIntersectsVisitor::visit (const geom::Geometry & geom) inline override protected virtual
Implements geos::geom::util::ShortCircuitedGeometryVisitor.
Definition at line 228 of file RectangleIntersects.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), and geos::geom::Envelope::intersects().
   {
     const geom::Envelope &elementEnv = *(geom.getEnvelopeInternal());
     // check for envelope intersection
     if (! rectEnv.intersects(elementEnv) ) return;
     computeSegmentIntersection(geom);
   }
Member Data Documentation
bool geos::operation::predicate::LineIntersectsVisitor::intersectsVar private
Definition at line 203 of file RectangleIntersects.cpp.
const geom::Envelope& geos::operation::predicate::LineIntersectsVisitor::rectEnv private
Definition at line 201 of file RectangleIntersects.cpp.
const geom::LineString& geos::operation::predicate::LineIntersectsVisitor::rectLine private
Definition at line 202 of file RectangleIntersects.cpp.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/operation/predicate/RectangleIntersects.cpp