GEOS: geos::simplify::TaggedLineString Class Reference
geos::simplify::TaggedLineString Class Reference
Contains and owns a list of TaggedLineSegments.
#include <TaggedLineString.h>
Public Types
typedef std::vector< geom::Coordinate > CoordVect
typedef std::unique_ptr< CoordVect > CoordVectPtr
typedef geom::CoordinateSequence CoordSeq
typedef std::unique_ptr< geom::CoordinateSequence > CoordSeqPtr
Public Member Functions
TaggedLineString (const geom::LineString *nParentLine, std::size_t minimumSize=2)
~TaggedLineString ()
std::size_t getMinimumSize () const
const geom::LineString * getParent () const
const CoordSeq * getParentCoordinates () const
CoordSeqPtr getResultCoordinates () const
std::size_t getResultSize () const
TaggedLineSegment * getSegment (std::size_t i)
const TaggedLineSegment * getSegment (std::size_t i) const
std::vector< TaggedLineSegment * > & getSegments ()
const std::vector< TaggedLineSegment * > & getSegments () const
void addToResult (std::unique_ptr< TaggedLineSegment > seg)
std::unique_ptr< geom::Geometry > asLineString () const
std::unique_ptr< geom::Geometry > asLinearRing () const
Private Member Functions
void init ()
TaggedLineString (const TaggedLineString &)
TaggedLineString & operator= (const TaggedLineString &)
Static Private Member Functions
static CoordVectPtr extractCoordinates (const std::vector< TaggedLineSegment * > &segs)
Private Attributes
const geom::LineString * parentLine
std::vector< TaggedLineSegment * > segs
std::vector< TaggedLineSegment * > resultSegs
std::size_t minimumSize
Detailed Description
Contains and owns a list of TaggedLineSegments.
Definition at line 60 of file TaggedLineString.h.
Member Typedef Documentation
typedef geom::CoordinateSequence geos::simplify::TaggedLineString::CoordSeq
Definition at line 68 of file TaggedLineString.h.
typedef std::unique_ptr<geom::CoordinateSequence> geos::simplify::TaggedLineString::CoordSeqPtr
Definition at line 70 of file TaggedLineString.h.
typedef std::vector<geom::Coordinate> geos::simplify::TaggedLineString::CoordVect
Definition at line 64 of file TaggedLineString.h.
typedef std::unique_ptr<CoordVect> geos::simplify::TaggedLineString::CoordVectPtr
Definition at line 66 of file TaggedLineString.h.
Constructor & Destructor Documentation
geos::simplify::TaggedLineString::TaggedLineString (const geom::LineString * nParentLine, std::size_t minimumSize = 2)
Definition at line 45 of file TaggedLineString.cpp.
References init().
   :
   parentLine(nParentLine),
   minimumSize(nMinimumSize)
 {
   init();
 }
geos::simplify::TaggedLineString::~TaggedLineString ()
Definition at line 55 of file TaggedLineString.cpp.
References resultSegs, and segs.
 {
 #if GEOS_DEBUG
   cerr << "TaggedLineString[" << this << "] destructor"
        << endl;
 #endif
   for (std::size_t i=0, n=segs.size(); i<n; i++)
     delete segs[i];
   for (std::size_t i=0, n=resultSegs.size(); i<n; i++)
     delete resultSegs[i];
 }
geos::simplify::TaggedLineString::TaggedLineString (const TaggedLineString &) private
Member Function Documentation
void geos::simplify::TaggedLineString::addToResult (std::unique_ptr< TaggedLineSegment > seg)
Definition at line 234 of file TaggedLineString.cpp.
References resultSegs.
Referenced by geos::simplify::TaggedLineStringSimplifier::simplifySection().
 {
 #if GEOS_DEBUG
   cerr << "TaggedLineString[" << this << "] adding "
        << " seg " << seg.get() << " to result"
        << endl;
 #endif
   resultSegs.push_back(seg.release());
 #if GEOS_DEBUG
   cerr << "TaggedLineString[" << this << "] adding "
        << " seg " << seg.get() << " to result"
        << endl;
 #endif
 }
unique_ptr< Geometry > geos::simplify::TaggedLineString::asLinearRing () const
Definition at line 226 of file TaggedLineString.cpp.
References geos::geom::GeometryFactory::createLinearRing(), geos::geom::Geometry::getFactory(), getResultCoordinates(), and parentLine.
 {
   return parentLine->getFactory()->createLinearRing(
       getResultCoordinates());
 }
unique_ptr< Geometry > geos::simplify::TaggedLineString::asLineString () const
Definition at line 218 of file TaggedLineString.cpp.
References geos::geom::GeometryFactory::createLineString(), geos::geom::Geometry::getFactory(), getResultCoordinates(), and parentLine.
 {
   return parentLine->getFactory()->createLineString(
       getResultCoordinates());
 }
TaggedLineString::CoordVectPtr geos::simplify::TaggedLineString::extractCoordinates (const std::vector< TaggedLineSegment * > & segs) static private
Definition at line 153 of file TaggedLineString.cpp.
References geos::geom::LineSegment::p0.
Referenced by getResultCoordinates().
 {
   CoordVectPtr pts(new CoordVect());
 #if GEOS_DEBUG
   cerr << __FUNCTION__ << " segs.size: " << segs.size() << endl;
 #endif
   std::size_t i=0, size=segs.size();
   if ( size ) {
     for (; i<size; i++)
     {
       TaggedLineSegment* seg = segs[i];
       assert(seg);
       pts->push_back(seg->p0);
     }
     // add last point
     pts->push_back(segs[size-1]->p1);
   }
   return pts;
 }
std::size_t geos::simplify::TaggedLineString::getMinimumSize () const
Definition at line 108 of file TaggedLineString.cpp.
References minimumSize.
Referenced by geos::simplify::TaggedLineStringSimplifier::simplifySection().
 {
   return minimumSize;
 }
const geom::LineString * geos::simplify::TaggedLineString::getParent () const
Definition at line 115 of file TaggedLineString.cpp.
References parentLine.
Referenced by geos::simplify::TaggedLineStringSimplifier::isInLineSection().
 {
   return parentLine;
 }
const CoordinateSequence * geos::simplify::TaggedLineString::getParentCoordinates () const
Definition at line 122 of file TaggedLineString.cpp.
References geos::geom::LineString::getCoordinatesRO(), and parentLine.
Referenced by geos::simplify::TaggedLineStringSimplifier::simplify().
 {
   assert(parentLine);
   return parentLine->getCoordinatesRO();
 }
CoordinateSequence::Ptr geos::simplify::TaggedLineString::getResultCoordinates () const
Definition at line 130 of file TaggedLineString.cpp.
References geos::geom::CoordinateSequenceFactory::create(), extractCoordinates(), geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::geom::Geometry::getFactory(), parentLine, and resultSegs.
Referenced by asLinearRing(), and asLineString().
 {
 #if GEOS_DEBUG
   cerr << __FUNCTION__ << " resultSegs.size: "
        << resultSegs.size() << endl;
 #endif
   CoordVectPtr pts = extractCoordinates(resultSegs);
 #if GEOS_DEBUG
   cerr << __FUNCTION__ << " extracted Coords.size: "
        << pts->size() << endl;
 #endif
   CoordVect* v = pts.release();
   return CoordinateSequence::Ptr(parentLine->getFactory()->getCoordinateSequenceFactory()->create(v));
 }
std::size_t geos::simplify::TaggedLineString::getResultSize () const
Definition at line 181 of file TaggedLineString.cpp.
References resultSegs.
Referenced by geos::simplify::TaggedLineStringSimplifier::simplifySection().
 {
   auto resultSegsSize = resultSegs.size();
   return resultSegsSize == 0 ? 0 : resultSegsSize + 1;
 }
TaggedLineSegment * geos::simplify::TaggedLineString::getSegment (std::size_t i)
Definition at line 189 of file TaggedLineString.cpp.
References segs.
Referenced by geos::simplify::TaggedLineStringSimplifier::remove(), and geos::simplify::TaggedLineStringSimplifier::simplifySection().
 {
   return segs[i];
 }
const TaggedLineSegment * geos::simplify::TaggedLineString::getSegment (std::size_t i) const
Definition at line 196 of file TaggedLineString.cpp.
References segs.
 {
   return segs[i];
 }
vector< TaggedLineSegment * > & geos::simplify::TaggedLineString::getSegments ()
Definition at line 203 of file TaggedLineString.cpp.
References segs.
Referenced by geos::simplify::LineSegmentIndex::add().
 {
   assert(0);
   return segs;
 }
const vector< TaggedLineSegment * > & geos::simplify::TaggedLineString::getSegments () const
Definition at line 211 of file TaggedLineString.cpp.
References segs.
 {
   return segs;
 }
void geos::simplify::TaggedLineString::init (void) private
Definition at line 71 of file TaggedLineString.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), parentLine, resultSegs, segs, and geos::geom::CoordinateSequence::size().
Referenced by TaggedLineString().
 {
   assert(parentLine);
   const CoordinateSequence* pts = parentLine->getCoordinatesRO();
 #if GEOS_DEBUG
   cerr << "TaggedLineString[" << this << "] pts.size() " << pts->size()
        << endl;
 #endif
   if ( pts->size() )
   {
     segs.reserve(pts->size()-1);
     for (std::size_t i=0, n=pts->size()-1; i<n; i++)
     {
       TaggedLineSegment* seg = new TaggedLineSegment(
           pts->getAt(i),
           pts->getAt(i+1),
           parentLine, static_cast<unsigned int>(i));
       segs.push_back(seg);
     }
   }
 #if GEOS_DEBUG
   cerr << "TaggedLineString[" << this << "] segs.size " << segs.size()
       << endl;
   cerr << "TaggedLineString[" << this << "] resultSegs.size " << resultSegs.size()
       << endl;
 #endif
 }
TaggedLineString& geos::simplify::TaggedLineString::operator= (const TaggedLineString &) private
Member Data Documentation
std::size_t geos::simplify::TaggedLineString::minimumSize private
Definition at line 111 of file TaggedLineString.h.
Referenced by getMinimumSize().
const geom::LineString* geos::simplify::TaggedLineString::parentLine private
Definition at line 103 of file TaggedLineString.h.
Referenced by asLinearRing(), asLineString(), getParent(), getParentCoordinates(), getResultCoordinates(), and init().
std::vector<TaggedLineSegment*> geos::simplify::TaggedLineString::resultSegs private
Definition at line 109 of file TaggedLineString.h.
Referenced by addToResult(), getResultCoordinates(), getResultSize(), init(), and ~TaggedLineString().
std::vector<TaggedLineSegment*> geos::simplify::TaggedLineString::segs private
Definition at line 106 of file TaggedLineString.h.
Referenced by getSegment(), getSegments(), init(), and ~TaggedLineString().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/simplify/TaggedLineString.h
/home/vicky/potree/geos/vicky/src/simplify/TaggedLineString.cpp