GEOS: geos::io::ByteOrderValues Class Reference
geos::io::ByteOrderValues Class Reference
#include <ByteOrderValues.h>
Public Types
enum EndianType { ENDIAN_BIG = 0, ENDIAN_LITTLE = 1 }
Static Public Member Functions
static int getInt (const unsigned char *buf, int byteOrder)
static void putInt (int intValue, unsigned char *buf, int byteOrder)
static int64 getLong (const unsigned char *buf, int byteOrder)
static void putLong (int64 longValue, unsigned char *buf, int byteOrder)
static double getDouble (const unsigned char *buf, int byteOrder)
static void putDouble (double doubleValue, unsigned char *buf, int byteOrder)
Detailed Description
Definition at line 37 of file ByteOrderValues.h.
Member Enumeration Documentation
enum geos::io::ByteOrderValues::EndianType
Enumerator
ENDIAN_BIG
ENDIAN_LITTLE
Definition at line 41 of file ByteOrderValues.h.
     {
         ENDIAN_BIG = 0,
         ENDIAN_LITTLE = 1
     };
Member Function Documentation
double geos::io::ByteOrderValues::getDouble (const unsigned char * buf, int byteOrder) static
Definition at line 137 of file ByteOrderValues.cpp.
References getLong().
Referenced by geos::io::ByteOrderDataInStream::readDouble().
 {
   int64 longValue = getLong(buf, byteOrder);
   double ret;
     std::memcpy(&ret, &longValue, sizeof(double));
   return ret;
 }
int geos::io::ByteOrderValues::getInt (const unsigned char * buf, int byteOrder) static
Definition at line 35 of file ByteOrderValues.cpp.
References ENDIAN_BIG, and ENDIAN_LITTLE.
Referenced by geos::io::ByteOrderDataInStream::readInt().
 {
   if ( byteOrder == ENDIAN_BIG )
   {
     return  ((int) (buf[0]&0xff) <<24) |
       ((int) (buf[1]&0xff) <<16) |
       ((int) (buf[2]&0xff) <<8) |
       ((int) (buf[3]&0xff) );
   }
   else // ENDIAN_LITTLE
   {
     assert(byteOrder == ENDIAN_LITTLE);
     return  ((int) (buf[3]&0xff) <<24) |
       ((int) (buf[2]&0xff) <<16) |
       ((int) (buf[1]&0xff) <<8) |
       ((int) (buf[0]&0xff) );
   }
 }
int64 geos::io::ByteOrderValues::getLong (const unsigned char * buf, int byteOrder) static
Definition at line 77 of file ByteOrderValues.cpp.
References ENDIAN_BIG, and ENDIAN_LITTLE.
Referenced by getDouble(), and geos::io::ByteOrderDataInStream::readLong().
 {
   if ( byteOrder == ENDIAN_BIG )
   {
     return
       (int64) (buf[0]) << 56
       | (int64) (buf[1] & 0xff) << 48
       | (int64) (buf[2] & 0xff) << 40
       | (int64) (buf[3] & 0xff) << 32
       | (int64) (buf[4] & 0xff) << 24
       | (int64) (buf[5] & 0xff) << 16
       | (int64) (buf[6] & 0xff) <<  8
       | (int64) (buf[7] & 0xff);
   }
   else // ENDIAN_LITTLE
   {
     assert(byteOrder == ENDIAN_LITTLE);
     return
       (int64) (buf[7]) << 56
       | (int64) (buf[6] & 0xff) << 48
       | (int64) (buf[5] & 0xff) << 40
       | (int64) (buf[4] & 0xff) << 32
       | (int64) (buf[3] & 0xff) << 24
       | (int64) (buf[2] & 0xff) << 16
       | (int64) (buf[1] & 0xff) <<  8
       | (int64) (buf[0] & 0xff);
   }
 }
void geos::io::ByteOrderValues::putDouble (double doubleValue, unsigned char * buf, int byteOrder) static
Definition at line 146 of file ByteOrderValues.cpp.
References putLong().
Referenced by geos::io::WKBWriter::writeCoordinate().
 {
   int64 longValue;
     std::memcpy(&longValue, &doubleValue, sizeof(double));
 #if DEBUG_BYTEORDER_VALUES
   std::cout<<"ByteOrderValues::putDouble("<<doubleValue<<
     ", order:"<<byteOrder
     <<") = "<<std::hex;
   for (int i=0; i<8; i++)
     std::cout<<"["<<(int)buf[i]<<"]";
   std::cout<<std::dec<<std::endl;
 #endif
   putLong(longValue, buf, byteOrder);
 }
void geos::io::ByteOrderValues::putInt (int intValue, unsigned char * buf, int byteOrder) static
Definition at line 56 of file ByteOrderValues.cpp.
References ENDIAN_BIG, and ENDIAN_LITTLE.
Referenced by geos::io::WKBWriter::writeInt().
 {
   if ( byteOrder == ENDIAN_BIG )
   {
     buf[0] = (unsigned char)(intValue >> 24);
     buf[1] = (unsigned char)(intValue >> 16);
     buf[2] = (unsigned char)(intValue >> 8);
     buf[3] = (unsigned char) intValue;
   }
   else // ENDIAN_LITTLE
   {
     assert(byteOrder == ENDIAN_LITTLE);
     buf[3] = (unsigned char)(intValue >> 24);
     buf[2] = (unsigned char)(intValue >> 16);
     buf[1] = (unsigned char)(intValue >> 8);
     buf[0] = (unsigned char) intValue;
   }
 }
void geos::io::ByteOrderValues::putLong (int64 longValue, unsigned char * buf, int byteOrder) static
Definition at line 108 of file ByteOrderValues.cpp.
References ENDIAN_BIG, and ENDIAN_LITTLE.
Referenced by putDouble().
 {
   if ( byteOrder == ENDIAN_BIG )
   {
     buf[0] = (unsigned char)(longValue >> 56);
     buf[1] = (unsigned char)(longValue >> 48);
     buf[2] = (unsigned char)(longValue >> 40);
     buf[3] = (unsigned char)(longValue >> 32);
     buf[4] = (unsigned char)(longValue >> 24);
     buf[5] = (unsigned char)(longValue >> 16);
     buf[6] = (unsigned char)(longValue >> 8);
     buf[7] = (unsigned char) longValue;
   }
   else // ENDIAN_LITTLE
   {
     assert(byteOrder == ENDIAN_LITTLE);
     buf[0] = (unsigned char) longValue;
     buf[1] = (unsigned char)(longValue >> 8);
     buf[2] = (unsigned char)(longValue >> 16);
     buf[3] = (unsigned char)(longValue >> 24);
     buf[4] = (unsigned char)(longValue >> 32);
     buf[5] = (unsigned char)(longValue >> 40);
     buf[6] = (unsigned char)(longValue >> 48);
     buf[7] = (unsigned char)(longValue >> 56);
   }
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/io/ByteOrderValues.h
/home/vicky/potree/geos/vicky/src/io/ByteOrderValues.cpp