GEOS: geos::util::GEOSException Class Reference
geos::util::GEOSException Class Reference
Base class for all GEOS exceptions.
#include <GEOSException.h>
Public Member Functions
GEOSException ()
GEOSException (std::string const &msg)
GEOSException (std::string const &name, std::string const &msg)
~GEOSException () override throw ()
const char * what () const override throw ()
Private Attributes
std::string _msg
Detailed Description
Base class for all GEOS exceptions.
Exceptions are thrown as pointers to this type. Use toString() to get a readable message.
Definition at line 39 of file GEOSException.h.
Constructor & Destructor Documentation
geos::util::GEOSException::GEOSException () inline
Definition at line 45 of file GEOSException.h.
Referenced by geos::io::ParseException::ParseException().
     :
     _msg("Unknown error")
   {}
geos::util::GEOSException::GEOSException (std::string const & msg) inline
Definition at line 50 of file GEOSException.h.
     :
     _msg(msg)
   {}
geos::util::GEOSException::GEOSException (std::string const & name, std::string const & msg) inline
Definition at line 55 of file GEOSException.h.
     :
     _msg(name+": "+msg)
   {}
geos::util::GEOSException::~GEOSException () throw () inline override
Definition at line 60 of file GEOSException.h.
   {}
Member Function Documentation
const char* geos::util::GEOSException::what () const throw () inline override
Definition at line 63 of file GEOSException.h.
Referenced by geos::operation::overlay::ElevationMatrix::add(), geos::geom::BinaryOp(), geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::snap::SnapIfNeededOverlayOp::getResultGeometry(), geos::operation::polygonize::EdgeRing::getRingInternal(), and geos::precision::EnhancedPrecisionOp::intersection().
   {
     return _msg.c_str();
   }
Member Data Documentation
std::string geos::util::GEOSException::_msg private
Definition at line 41 of file GEOSException.h.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/util/GEOSException.h