GEOS: geos::operation::overlay::LineBuilder Class Reference
geos::operation::overlay::LineBuilder Class Reference
Forms JTS LineStrings out of a the graph of geomgraph::DirectedEdge created by an OverlayOp.
#include <LineBuilder.h>
Public Member Functions
LineBuilder (OverlayOp *newOp, const geom::GeometryFactory *newGeometryFactory, algorithm::PointLocator *newPtLocator)
~LineBuilder ()
std::vector< geom::LineString * > * build (OverlayOp::OpCode opCode)
void collectLineEdge (geomgraph::DirectedEdge *de, OverlayOp::OpCode opCode, std::vector< geomgraph::Edge * > *edges)
Private Member Functions
void findCoveredLineEdges ()
void collectLines (OverlayOp::OpCode opCode)
void buildLines (OverlayOp::OpCode opCode)
void labelIsolatedLines (std::vector< geomgraph::Edge * > *edgesList)
void collectBoundaryTouchEdge (geomgraph::DirectedEdge *de, OverlayOp::OpCode opCode, std::vector< geomgraph::Edge * > *edges)
void labelIsolatedLine (geomgraph::Edge *e, int targetIndex)
void propagateZ (geom::CoordinateSequence *cs)
Private Attributes
OverlayOp * op
const geom::GeometryFactory * geometryFactory
algorithm::PointLocator * ptLocator
std::vector< geomgraph::Edge * > lineEdgesList
std::vector< geom::LineString * > * resultLineList
Detailed Description
Forms JTS LineStrings out of a the graph of geomgraph::DirectedEdge created by an OverlayOp.
Definition at line 63 of file LineBuilder.h.
Constructor & Destructor Documentation
geos::operation::overlay::LineBuilder::LineBuilder (OverlayOp * newOp, const geom::GeometryFactory * newGeometryFactory, algorithm::PointLocator * newPtLocator)
Definition at line 49 of file LineBuilder.cpp.
                                :
   op(newOp),
   geometryFactory(newGeometryFactory),
   ptLocator(newPtLocator),
   //lineEdgesList(new vector<Edge *>()),
   resultLineList(new vector<LineString *>())
 {
 }
geos::operation::overlay::LineBuilder::~LineBuilder ()
Definition at line 60 of file LineBuilder.cpp.
 {
 }
Member Function Documentation
vector< LineString * > * geos::operation::overlay::LineBuilder::build (OverlayOp::OpCode opCode)
Returns
a list of the LineStrings in the result of the specified overlay operation
Definition at line 69 of file LineBuilder.cpp.
References buildLines(), collectLines(), findCoveredLineEdges(), and resultLineList.
Referenced by geos::operation::overlay::OverlayOp::computeOverlay().
 {
   findCoveredLineEdges();
   collectLines(opCode);
   //labelIsolatedLines(&lineEdgesList);
   buildLines(opCode);
   return resultLineList;
 }
void geos::operation::overlay::LineBuilder::buildLines (OverlayOp::OpCode opCode) private
Definition at line 189 of file LineBuilder.cpp.
References geos::geom::CoordinateSequence::clone(), geos::geom::GeometryFactory::createLineString(), geometryFactory, geos::geomgraph::Edge::getCoordinates(), lineEdgesList, propagateZ(), resultLineList, and geos::geomgraph::GraphComponent::setInResult().
Referenced by build().
 {
   for(size_t i=0, s=lineEdgesList.size(); i<s; ++i)
   {
     Edge *e=lineEdgesList[i];
     CoordinateSequence *cs = e->getCoordinates()->clone();
 #if COMPUTE_Z
     propagateZ(cs);
 #endif
     LineString *line=geometryFactory->createLineString(cs);
     resultLineList->push_back(line);
     e->setInResult(true);
   }
 }
void geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge (geomgraph::DirectedEdge * de, OverlayOp::OpCode opCode, std::vector< geomgraph::Edge * > * edges) private
Collect edges from Area inputs which should be in the result but which have not been included in a result area. This happens ONLY:
during an intersection when the boundaries of two areas touch in a line segment
OR as a result of a dimensional collapse.
Definition at line 160 of file LineBuilder.cpp.
References geos::geomgraph::EdgeEnd::getEdge(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::DirectedEdge::getSym(), geos::geomgraph::GraphComponent::isInResult(), geos::geomgraph::DirectedEdge::isInResult(), geos::geomgraph::DirectedEdge::isInteriorAreaEdge(), geos::geomgraph::DirectedEdge::isLineEdge(), geos::operation::overlay::OverlayOp::isResultOfOp(), geos::geomgraph::DirectedEdge::isVisited(), geos::operation::overlay::OverlayOp::opINTERSECTION, and geos::geomgraph::DirectedEdge::setVisitedEdge().
Referenced by collectLines().
 {
   if (de->isLineEdge()) return;  // only interested in area edges
   if (de->isVisited()) return;  // already processed
   // added to handle dimensional collapses
   if (de->isInteriorAreaEdge()) return;
   // if the edge linework is already included, don't include it again
   if (de->getEdge()->isInResult()) return;
   // sanity check for labelling of result edgerings
   assert( ! ( de->isInResult() || de->getSym()->isInResult() )
     ||
           ! de->getEdge()->isInResult() );
   // include the linework if it's in the result of the operation
   const Label& label = de->getLabel();
   if ( OverlayOp::isResultOfOp(label, opCode)
     && opCode == OverlayOp::opINTERSECTION )
   {
     edges->push_back(de->getEdge());
     de->setVisitedEdge(true);
   }
 }
void geos::operation::overlay::LineBuilder::collectLineEdge (geomgraph::DirectedEdge * de, OverlayOp::OpCode opCode, std::vector< geomgraph::Edge * > * edges)
Collect line edges which are in the result.
Line edges are in the result if they are not part of an area boundary, if they are in the result of the overlay operation, and if they are not covered by a result area.
Parameters
de the directed edge to test.
opCode the overlap operation
edges the list of included line edges.
Definition at line 133 of file LineBuilder.cpp.
References geos::geomgraph::EdgeEnd::getEdge(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::GraphComponent::isCovered(), geos::geomgraph::DirectedEdge::isLineEdge(), geos::operation::overlay::OverlayOp::isResultOfOp(), geos::geomgraph::DirectedEdge::isVisited(), and geos::geomgraph::DirectedEdge::setVisitedEdge().
Referenced by collectLines().
 {
   // include L edges which are in the result
   if (de->isLineEdge()) {
     const Label& label = de->getLabel();
     Edge *e = de->getEdge();
     if (!de->isVisited()
           && OverlayOp::isResultOfOp(label, opCode)
           && !e->isCovered() )
     {
       //Debug.println("de: "+de.getLabel());
       //Debug.println("edge: "+e.getLabel());
       edges->push_back(e);
       de->setVisitedEdge(true);
     }
   }
 }
void geos::operation::overlay::LineBuilder::collectLines (OverlayOp::OpCode opCode) private
Definition at line 120 of file LineBuilder.cpp.
References collectBoundaryTouchEdge(), collectLineEdge(), geos::geomgraph::PlanarGraph::getEdgeEnds(), geos::operation::overlay::OverlayOp::getGraph(), lineEdgesList, and op.
Referenced by build().
 {
   vector<EdgeEnd*> *ee=op->getGraph().getEdgeEnds();
   for(size_t i=0, s=ee->size(); i<s; ++i)
   {
     assert(dynamic_cast<DirectedEdge*>((*ee)[i]));
     DirectedEdge *de=static_cast<DirectedEdge*>((*ee)[i]);
     collectLineEdge(de, opCode, &lineEdgesList);
     collectBoundaryTouchEdge(de, opCode, &lineEdgesList);
   }
 }
void geos::operation::overlay::LineBuilder::findCoveredLineEdges () private
Definition at line 86 of file LineBuilder.cpp.
References geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges(), geos::geomgraph::EdgeEnd::getCoordinate(), geos::geomgraph::EdgeEnd::getEdge(), geos::geomgraph::PlanarGraph::getEdgeEnds(), geos::geomgraph::Node::getEdges(), geos::operation::overlay::OverlayOp::getGraph(), geos::geomgraph::PlanarGraph::getNodeMap(), geos::operation::overlay::OverlayOp::isCoveredByA(), geos::geomgraph::GraphComponent::isCoveredSet(), geos::geomgraph::DirectedEdge::isLineEdge(), geos::geomgraph::NodeMap::nodeMap, op, and geos::geomgraph::GraphComponent::setCovered().
Referenced by build().
 {
 // first set covered for all L edges at nodes which have A edges too
   map<Coordinate*,Node*,CoordinateLessThen> &nodeMap=op->getGraph().getNodeMap()->nodeMap;
   map<Coordinate*,Node*,CoordinateLessThen>::iterator it=nodeMap.begin();
   map<Coordinate*,Node*,CoordinateLessThen>::iterator endIt=nodeMap.end();
   for ( ; it!=endIt; ++it)
   {
     Node *node=it->second;
     //node.print(System.out);
     assert(dynamic_cast<DirectedEdgeStar*>(node->getEdges()));
     DirectedEdgeStar* des=static_cast<DirectedEdgeStar*>(node->getEdges());
     des->findCoveredLineEdges();
     //((DirectedEdgeStar*)node->getEdges())->findCoveredLineEdges();
   }
   /*
    * For all L edges which weren't handled by the above,
    * use a point-in-poly test to determine whether they are covered
    */
   vector<EdgeEnd*> *ee=op->getGraph().getEdgeEnds();
   for(size_t i=0, s=ee->size(); i<s; ++i)
   {
     assert(dynamic_cast<DirectedEdge*>((*ee)[i]));
     DirectedEdge *de=static_cast<DirectedEdge*>((*ee)[i]);
     Edge *e=de->getEdge();
     if (de->isLineEdge() && !e->isCoveredSet()) {
       bool isCovered=op->isCoveredByA(de->getCoordinate());
       e->setCovered(isCovered);
     }
   }
 }
void geos::operation::overlay::LineBuilder::labelIsolatedLine (geomgraph::Edge * e, int targetIndex) private
Label an isolated node with its relationship to the target geometry.
Definition at line 311 of file LineBuilder.cpp.
References geos::operation::GeometryGraphOperation::getArgGeometry(), geos::geomgraph::Edge::getCoordinate(), geos::geomgraph::GraphComponent::getLabel(), geos::algorithm::PointLocator::locate(), op, ptLocator, and geos::geomgraph::Label::setLocation().
Referenced by labelIsolatedLines().
 {
   int loc = ptLocator->locate( e->getCoordinate(),
                                op->getArgGeometry(targetIndex) );
   e->getLabel().setLocation(targetIndex,loc);
 }
void geos::operation::overlay::LineBuilder::labelIsolatedLines (std::vector< geomgraph::Edge * > * edgesList) private
Definition at line 291 of file LineBuilder.cpp.
References geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Edge::isIsolated(), geos::geomgraph::Label::isNull(), and labelIsolatedLine().
 {
   for(size_t i=0, s=edgesList->size(); i<s; ++i)
   {
     Edge *e=(*edgesList)[i];
     const Label& label = e->getLabel();
     //n.print(System.out);
     if (e->isIsolated()) {
       if (label.isNull(0))
         labelIsolatedLine(e, 0);
       else
         labelIsolatedLine(e, 1);
     }
   }
 }
void geos::operation::overlay::LineBuilder::propagateZ (geom::CoordinateSequence * cs) private
Definition at line 211 of file LineBuilder.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), geos::geom::CoordinateSequence::setAt(), and geos::geom::Coordinate::z.
Referenced by buildLines().
 {
 #if GEOS_DEBUG
   cerr<<"LineBuilder::propagateZ() called"<<endl;
 #endif
   vector<size_t> v3d; // vertex 3d
   size_t cssize = cs->getSize();
   for (size_t i = 0; i < cssize; ++i)
   {
     if ( !ISNAN(cs->getAt(i).z) ) v3d.push_back(i);
   }
 #if GEOS_DEBUG
   cerr<<"  found "<<v3d.size()<<" 3d vertexes"<<endl;
 #endif
   if ( v3d.size() == 0 )
   {
 #if GEOS_DEBUG
     cerr<<"  nothing to do"<<endl;
 #endif
     return;
   }
   Coordinate buf;
   // fill initial part
   if ( v3d[0] != 0 )
   {
     double z = cs->getAt(v3d[0]).z;
     for (size_t j = 0; j < v3d[0]; ++j)
     {
       buf = cs->getAt(j);
       buf.z = z;
       cs->setAt(buf, j);
     }
   }
   // interpolate inbetweens
   size_t prev=v3d[0];
   for (size_t i = 1; i < v3d.size(); ++i)
   {
     auto curr = v3d[i];
     auto dist = curr - prev;
     if (dist > 1)
     {
       const Coordinate &cto = cs->getAt(curr);
       const Coordinate &cfrom = cs->getAt(prev);
       double gap = cto.z - cfrom.z;
       double zstep = gap / static_cast<double>(dist);
       double z = cfrom.z;
       for (size_t j = prev+1; j < curr; ++j)
       {
         buf = cs->getAt(j);
         z+=zstep;
         buf.z = z;
         cs->setAt(buf, j);
       }
     }
     prev = curr;
   }
   // fill final part
   if ( prev < cssize-1 )
   {
     double z = cs->getAt(prev).z;
     for (size_t j=prev+1; j<cssize; j++)
     {
       buf = cs->getAt(j);
       buf.z = z;
       cs->setAt(buf, j);
     }
   }
 }
Member Data Documentation
const geom::GeometryFactory* geos::operation::overlay::LineBuilder::geometryFactory private
Definition at line 95 of file LineBuilder.h.
Referenced by buildLines().
std::vector<geomgraph::Edge*> geos::operation::overlay::LineBuilder::lineEdgesList private
Definition at line 97 of file LineBuilder.h.
Referenced by buildLines(), and collectLines().
OverlayOp* geos::operation::overlay::LineBuilder::op private
Definition at line 94 of file LineBuilder.h.
Referenced by collectLines(), findCoveredLineEdges(), and labelIsolatedLine().
algorithm::PointLocator* geos::operation::overlay::LineBuilder::ptLocator private
Definition at line 96 of file LineBuilder.h.
Referenced by labelIsolatedLine().
std::vector<geom::LineString*>* geos::operation::overlay::LineBuilder::resultLineList private
Definition at line 98 of file LineBuilder.h.
Referenced by build(), and buildLines().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/LineBuilder.h
/home/vicky/potree/geos/vicky/src/operation/overlay/LineBuilder.cpp