GEOS: geos::geom::TrianglePredicate Class Reference
geos::geom::TrianglePredicate Class Reference
#include <TrianglePredicate.h>
Static Public Member Functions
static bool isInCircleNonRobust (const Coordinate &a, const Coordinate &b, const Coordinate &c, const Coordinate &p)
static bool isInCircleNormalized (const Coordinate &a, const Coordinate &b, const Coordinate &c, const Coordinate &p)
static bool isInCircleRobust (const Coordinate &a, const Coordinate &b, const Coordinate &c, const Coordinate &p)
Static Private Member Functions
static double triArea (const Coordinate &a, const Coordinate &b, const Coordinate &c)
Detailed Description
Algorithms for computing values and predicates associated with triangles. For some algorithms extended-precision implementations are provided, which are more robust (i.e. they produce correct answers in more cases). Also, some more robust formulations of some algorithms are provided, which utilize normalization to the origin.
Author
JTS: Martin Davis
Benjamin Campbell
Definition at line 41 of file TrianglePredicate.h.
Member Function Documentation
bool geos::geom::TrianglePredicate::isInCircleNonRobust (const Coordinate & a, const Coordinate & b, const Coordinate & c, const Coordinate & p) static
Tests if a point is inside the circle defined by the triangle with vertices a, b, c (oriented counter-clockwise). This test uses simple double-precision arithmetic, and thus may not be robust.
Parameters
a a vertex of the triangle
b a vertex of the triangle
c a vertex of the triangle
P the point to test
Returns
true if this point is inside the circle defined by the points a, b, c
Definition at line 27 of file TrianglePredicate.cpp.
References triArea(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   bool isInCircle =
     (a.x * a.x + a.y * a.y) * triArea(b, c, p)
     - (b.x * b.x + b.y * b.y) * triArea(a, c, p)
     + (c.x * c.x + c.y * c.y) * triArea(a, b, p)
     - (p.x * p.x + p.y * p.y) * triArea(a, b, c)
     > 0;
   return isInCircle;
 }
bool geos::geom::TrianglePredicate::isInCircleNormalized (const Coordinate & a, const Coordinate & b, const Coordinate & c, const Coordinate & p) static
Tests if a point is inside the circle defined by the triangle with vertices a, b, c (oriented counter-clockwise). This test uses simple double-precision arithmetic, and thus is not 10% robust. However, by using normalization to the origin it provides improved robustness and increased performance.
Based on code by J.R.Shewchuk.
Parameters
a a vertex of the triangle
b a vertex of the triangle
c a vertex of the triangle
P the point to test
Returns
true if this point is inside the circle defined by the points a, b, c
Definition at line 41 of file TrianglePredicate.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by isInCircleRobust().
 {
   double adx = a.x - p.x;
   double ady = a.y - p.y;
   double bdx = b.x - p.x;
   double bdy = b.y - p.y;
   double cdx = c.x - p.x;
   double cdy = c.y - p.y;
   double abdet = adx * bdy - bdx * ady;
   double bcdet = bdx * cdy - cdx * bdy;
   double cadet = cdx * ady - adx * cdy;
   double alift = adx * adx + ady * ady;
   double blift = bdx * bdx + bdy * bdy;
   double clift = cdx * cdx + cdy * cdy;
   double disc = alift * bcdet + blift * cadet + clift * abdet;
   return disc > 0;
 }
bool geos::geom::TrianglePredicate::isInCircleRobust (const Coordinate & a, const Coordinate & b, const Coordinate & c, const Coordinate & p) static
Tests if a point is inside the circle defined by the triangle with vertices a, b, c (oriented counter-clockwise). This method uses more robust computation.
Parameters
a a vertex of the triangle
b a vertex of the triangle
c a vertex of the triangle
P the point to test
Returns
true if this point is inside the circle defined by the points a, b, c
Definition at line 72 of file TrianglePredicate.cpp.
References isInCircleNormalized().
Referenced by geos::triangulate::quadedge::Vertex::isInCircle().
 {
   //checkRobustInCircle(a, b, c, p);
   //  return isInCircleNonRobust(a, b, c, p);
   return isInCircleNormalized(a, b, c, p);
 }
double geos::geom::TrianglePredicate::triArea (const Coordinate & a, const Coordinate & b, const Coordinate & c) static private
Computes twice the area of the oriented triangle (a, b, c), i.e., the area is positive if the triangle is oriented counterclockwise.
Parameters
a a vertex of the triangle
b a vertex of the triangle
c a vertex of the triangle
Definition at line 64 of file TrianglePredicate.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by isInCircleNonRobust().
 {
   return (b.x - a.x) * (c.y - a.y)
     - (b.y - a.y) * (c.x - a.x);
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/triangulate/quadedge/TrianglePredicate.h
/home/vicky/potree/geos/vicky/src/triangulate/quadedge/TrianglePredicate.cpp