GEOS: geos::operation::valid::ConsistentAreaTester Class Reference
geos::operation::valid::ConsistentAreaTester Class Reference
Checks that a geomgraph::GeometryGraph representing an area (a Polygon or MultiPolygon) is consistent with the OGC-SFS semantics for area geometries.
#include <ConsistentAreaTester.h>
Public Member Functions
ConsistentAreaTester (geomgraph::GeometryGraph *newGeomGraph)
~ConsistentAreaTester ()
geom::Coordinate & getInvalidPoint ()
bool isNodeConsistentArea ()
Check all nodes to see if their labels are consistent with area topology.
bool hasDuplicateRings ()
Private Member Functions
bool isNodeEdgeAreaLabelsConsistent ()
Private Attributes
algorithm::LineIntersector li
geomgraph::GeometryGraph * geomGraph
Not owned.
relate::RelateNodeGraph nodeGraph
geom::Coordinate invalidPoint
the intersection point found (if any)
Detailed Description
Checks that a geomgraph::GeometryGraph representing an area (a Polygon or MultiPolygon) is consistent with the OGC-SFS semantics for area geometries.
Checks include:
testing for rings which self-intersect (both properly and at nodes)
testing for duplicate rings
If an inconsistency if found the location of the problem is recorded. Checks that a geomgraph::GeometryGraph representing an area (a geom::Polygon or geom::MultiPolygon) has consistent semantics for area geometries. This check is required for any reasonable polygonal model (including the OGC-SFS model, as well as models which allow ring self-intersection at single points)
Checks include:
test for rings which properly intersect (but not for ring self-intersection, or intersections at vertices)
test for consistent labelling at all node points (this detects vertex intersections with invalid topology, i.e. where the exterior side of an edge lies in the interior of the area)
test for duplicate rings
If an inconsistency is found the location of the problem is recorded and is available to the caller.
Definition at line 83 of file ConsistentAreaTester.h.
Constructor & Destructor Documentation
geos::operation::valid::ConsistentAreaTester::ConsistentAreaTester (geomgraph::GeometryGraph * newGeomGraph)
Creates a new tester for consistent areas.
Parameters
geomGraph the topology graph of the area geometry. Caller keeps responsibility for its deletion
Definition at line 44 of file ConsistentAreaTester.cpp.
   :
   li(),
   geomGraph(newGeomGraph),
   nodeGraph(),
   invalidPoint()
 {
 }
geos::operation::valid::ConsistentAreaTester::~ConsistentAreaTester ()
Definition at line 53 of file ConsistentAreaTester.cpp.
 {
 }
Member Function Documentation
Coordinate & geos::operation::valid::ConsistentAreaTester::getInvalidPoint ()
Returns
the intersection point, or null if none was found
Definition at line 58 of file ConsistentAreaTester.cpp.
References invalidPoint.
Referenced by geos::operation::valid::IsValidOp::checkConsistentArea().
 {
   return invalidPoint;
 }
bool geos::operation::valid::ConsistentAreaTester::hasDuplicateRings ()
Checks for two duplicate rings in an area. Duplicate rings are rings that are topologically equal (that is, which have the same sequence of points up to point order). If the area is topologically consistent (determined by calling the isNodeConsistentArea, duplicate rings can be found by checking for EdgeBundles which contain more than one geomgraph::EdgeEnd. (This is because topologically consistent areas cannot have two rings sharing the same line segment, unless the rings are equal). The start point of one of the equal rings will be placed in invalidPoint.
Returns
true if this area Geometry is topologically consistent but has two duplicate rings
Definition at line 104 of file ConsistentAreaTester.cpp.
References geos::geomgraph::EdgeEndStar::begin(), geos::geomgraph::EdgeEndStar::end(), geos::geomgraph::Edge::getCoordinate(), geos::geomgraph::EdgeEnd::getEdge(), geos::operation::relate::EdgeEndBundle::getEdgeEnds(), geos::geomgraph::Node::getEdges(), geos::operation::relate::RelateNodeGraph::getNodeMap(), invalidPoint, and nodeGraph.
Referenced by geos::operation::valid::IsValidOp::checkConsistentArea().
 {
   map<Coordinate*,Node*,CoordinateLessThen>& nMap=nodeGraph.getNodeMap();
   map<Coordinate*,Node*,CoordinateLessThen>::iterator nodeIt;
   for(nodeIt=nMap.begin(); nodeIt!=nMap.end(); ++nodeIt)
   {
     assert(dynamic_cast<relate::RelateNode*>(nodeIt->second));
     relate::RelateNode *node=static_cast<relate::RelateNode*>(nodeIt->second);
     EdgeEndStar *ees=node->getEdges();
     EdgeEndStar::iterator endIt=ees->end();
     for(EdgeEndStar::iterator it=ees->begin(); it!=endIt; ++it)
     {
       assert(dynamic_cast<relate::EdgeEndBundle*>(*it));
       relate::EdgeEndBundle *eeb=static_cast<relate::EdgeEndBundle*>(*it);
       if (eeb->getEdgeEnds()->size()>1) {
         invalidPoint=eeb->getEdge()->getCoordinate(0);
         return true;
       }
     }
   }
   return false;
 }
bool geos::operation::valid::ConsistentAreaTester::isNodeConsistentArea ()
Check all nodes to see if their labels are consistent with area topology.
Returns
true if this area has a consistent node labelling
To fully check validity, it is necessary to compute ALL intersections, including self-intersections within a single edge.
A proper intersection means that the area is not consistent.
Definition at line 64 of file ConsistentAreaTester.cpp.
References geos::operation::relate::RelateNodeGraph::build(), geos::geomgraph::GeometryGraph::computeSelfNodes(), geomGraph, invalidPoint, isNodeEdgeAreaLabelsConsistent(), li, and nodeGraph.
Referenced by geos::operation::valid::IsValidOp::checkConsistentArea().
 {
   using geomgraph::index::SegmentIntersector;
   unique_ptr<SegmentIntersector> intersector(geomGraph->computeSelfNodes(&li, true, true));
   if (intersector->hasProperIntersection()) {
     invalidPoint=intersector->getProperIntersectionPoint();
     return false;
   }
   nodeGraph.build(geomGraph);
   return isNodeEdgeAreaLabelsConsistent();
 }
bool geos::operation::valid::ConsistentAreaTester::isNodeEdgeAreaLabelsConsistent () private
Check all nodes to see if their labels are consistent. If any are not, return false
Definition at line 86 of file ConsistentAreaTester.cpp.
References geomGraph, geos::geomgraph::Node::getCoordinate(), geos::geomgraph::Node::getEdges(), geos::operation::relate::RelateNodeGraph::getNodeMap(), invalidPoint, geos::geomgraph::EdgeEndStar::isAreaLabelsConsistent(), and nodeGraph.
Referenced by isNodeConsistentArea().
 {
   assert(geomGraph);
   map<Coordinate*,Node*,CoordinateLessThen>& nMap=nodeGraph.getNodeMap();
   map<Coordinate*,Node*,CoordinateLessThen>::iterator nodeIt;
   for(nodeIt=nMap.begin();nodeIt!=nMap.end();nodeIt++) {
     relate::RelateNode *node=static_cast<relate::RelateNode*>(nodeIt->second);
     if (!node->getEdges()->isAreaLabelsConsistent(*geomGraph)) {
       invalidPoint=node->getCoordinate();
       return false;
     }
   }
   return true;
 }
Member Data Documentation
geomgraph::GeometryGraph* geos::operation::valid::ConsistentAreaTester::geomGraph private
Not owned.
Definition at line 89 of file ConsistentAreaTester.h.
Referenced by isNodeConsistentArea(), and isNodeEdgeAreaLabelsConsistent().
geom::Coordinate geos::operation::valid::ConsistentAreaTester::invalidPoint private
the intersection point found (if any)
Definition at line 94 of file ConsistentAreaTester.h.
Referenced by getInvalidPoint(), hasDuplicateRings(), isNodeConsistentArea(), and isNodeEdgeAreaLabelsConsistent().
algorithm::LineIntersector geos::operation::valid::ConsistentAreaTester::li private
Definition at line 86 of file ConsistentAreaTester.h.
Referenced by isNodeConsistentArea().
relate::RelateNodeGraph geos::operation::valid::ConsistentAreaTester::nodeGraph private
Definition at line 91 of file ConsistentAreaTester.h.
Referenced by hasDuplicateRings(), isNodeConsistentArea(), and isNodeEdgeAreaLabelsConsistent().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/valid/ConsistentAreaTester.h
/home/vicky/potree/geos/vicky/src/operation/valid/ConsistentAreaTester.cpp