GEOS: geos::index::intervalrtree::IntervalRTreeLeafNode Class Reference
geos::index::intervalrtree::IntervalRTreeLeafNode Class Reference
#include <IntervalRTreeLeafNode.h>
Public Types
typedef std::vector< const IntervalRTreeNode * > ConstVect
Public Member Functions
IntervalRTreeLeafNode (double min, double max, void *item)
~IntervalRTreeLeafNode () override
void query (double queryMin, double queryMax, index::ItemVisitor *visitor) const override
double getMin () const
double getMax () const
Static Public Member Functions
static bool compare (const IntervalRTreeNode *n1, const IntervalRTreeNode *n2)
Protected Member Functions
bool intersects (double queryMin, double queryMax) const
Protected Attributes
double min
double max
Private Attributes
void * item
externally owned
Detailed Description
Definition at line 35 of file IntervalRTreeLeafNode.h.
Member Typedef Documentation
typedef std::vector<const IntervalRTreeNode *> geos::index::intervalrtree::IntervalRTreeNode::ConstVect inherited
Definition at line 51 of file IntervalRTreeNode.h.
Constructor & Destructor Documentation
geos::index::intervalrtree::IntervalRTreeLeafNode::IntervalRTreeLeafNode (double min, double max, void * item) inline
Parameters
item externally owned
Definition at line 45 of file IntervalRTreeLeafNode.h.
   : IntervalRTreeNode( min, max),
     item( item)
   { }
geos::index::intervalrtree::IntervalRTreeLeafNode::~IntervalRTreeLeafNode () inline override
Definition at line 50 of file IntervalRTreeLeafNode.h.
   {
   }
Member Function Documentation
static bool geos::index::intervalrtree::IntervalRTreeNode::compare (const IntervalRTreeNode * n1, const IntervalRTreeNode * n2) inline static inherited
Definition at line 87 of file IntervalRTreeNode.h.
References geos::index::intervalrtree::IntervalRTreeNode::getMax(), and geos::index::intervalrtree::IntervalRTreeNode::getMin().
Referenced by geos::index::intervalrtree::SortedPackedIntervalRTree::buildTree().
     {
       //IntervalRTreeNode * n1 = dynamic_cast<IntervalRTreeNode *>( o1);
       //IntervalRTreeNode * n2 = dynamic_cast<IntervalRTreeNode *>( o2);
       double mid1 = (n1->getMin() + n1->getMax()) / 2;
       double mid2 = (n2->getMin() + n2->getMax()) / 2;
       //if (mid1 < mid2) return -1;
       //if (mid1 > mid2) return 1;
       //return 0;
       return mid1 > mid2;
     }
double geos::index::intervalrtree::IntervalRTreeNode::getMax () const inline inherited
Definition at line 71 of file IntervalRTreeNode.h.
Referenced by geos::index::intervalrtree::IntervalRTreeNode::compare().
   {
     return max;
   }
double geos::index::intervalrtree::IntervalRTreeNode::getMin () const inline inherited
Definition at line 66 of file IntervalRTreeNode.h.
Referenced by geos::index::intervalrtree::IntervalRTreeNode::compare().
   {
     return min;
   }
bool geos::index::intervalrtree::IntervalRTreeNode::intersects (double queryMin, double queryMax) const inline protected inherited
Definition at line 42 of file IntervalRTreeNode.h.
Referenced by query(), and geos::index::intervalrtree::IntervalRTreeBranchNode::query().
   {
     if (min > queryMax || max < queryMin)
       return false;
     return true;
   }
void geos::index::intervalrtree::IntervalRTreeLeafNode::query (double queryMin, double queryMax, index::ItemVisitor * visitor) const override virtual
Implements geos::index::intervalrtree::IntervalRTreeNode.
Definition at line 34 of file IntervalRTreeLeafNode.cpp.
References geos::index::intervalrtree::IntervalRTreeNode::intersects(), item, and geos::index::ItemVisitor::visitItem().
 {
   if (! intersects( queryMin, queryMax))
     return;
   visitor->visitItem( item);
 }
Member Data Documentation
void* geos::index::intervalrtree::IntervalRTreeLeafNode::item private
externally owned
Definition at line 39 of file IntervalRTreeLeafNode.h.
Referenced by query().
double geos::index::intervalrtree::IntervalRTreeNode::max protected inherited
Definition at line 40 of file IntervalRTreeNode.h.
double geos::index::intervalrtree::IntervalRTreeNode::min protected inherited
Definition at line 39 of file IntervalRTreeNode.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/intervalrtree/IntervalRTreeLeafNode.h
/home/vicky/potree/geos/vicky/src/index/intervalrtree/IntervalRTreeLeafNode.cpp