GEOS: geos::geom::CoordinateList Class Reference
geos::geom::CoordinateList Class Reference
A list of Coordinates, which may be set to prevent repeated coordinates from occuring in the list.
#include <CoordinateList.h>
Public Types
typedef std::list< Coordinate >::iterator iterator
typedef std::list< Coordinate >::const_iterator const_iterator
typedef std::list< Coordinate >::size_type size_type
Public Member Functions
CoordinateList (const std::vector< Coordinate > &v)
Constructs a new list from an array of Coordinates, allowing repeated points.
CoordinateList ()
size_type size () const
bool empty () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
iterator insert (iterator pos, const Coordinate &c, bool allowRepeated)
Inserts the specified coordinate at the specified position in this list.
iterator insert (iterator pos, const Coordinate &c)
iterator erase (iterator pos)
iterator erase (iterator first, iterator last)
std::unique_ptr< Coordinate::Vect > toCoordinateArray () const
void closeRing ()
Private Attributes
std::list< Coordinate > coords
Friends
std::ostream & operator<< (std::ostream &os, const CoordinateList &cl)
Detailed Description
A list of Coordinates, which may be set to prevent repeated coordinates from occuring in the list.
Use this class when fast insertions and removal at arbitrary position is needed. The class keeps ownership of the Coordinates.
Definition at line 55 of file CoordinateList.h.
Member Typedef Documentation
typedef std::list<Coordinate>::const_iterator geos::geom::CoordinateList::const_iterator
Definition at line 60 of file CoordinateList.h.
typedef std::list<Coordinate>::iterator geos::geom::CoordinateList::iterator
Definition at line 59 of file CoordinateList.h.
typedef std::list<Coordinate>::size_type geos::geom::CoordinateList::size_type
Definition at line 61 of file CoordinateList.h.
Constructor & Destructor Documentation
geos::geom::CoordinateList::CoordinateList (const std::vector< Coordinate > & v) inline
Constructs a new list from an array of Coordinates, allowing repeated points.
(I.e. this constructor produces a CoordinateList with exactly the same set of points as the input array.)
Parameters
v the initial coordinates
Definition at line 75 of file CoordinateList.h.
     :
     coords(v.begin(), v.end())
   {
   }
geos::geom::CoordinateList::CoordinateList () inline
Definition at line 81 of file CoordinateList.h.
     :
     coords()
   {
   }
Member Function Documentation
iterator geos::geom::CoordinateList::begin () inline
Definition at line 97 of file CoordinateList.h.
Referenced by geos::geom::operator<<(), geos::operation::overlay::snap::LineStringSnapper::snapSegments(), and geos::operation::overlay::snap::LineStringSnapper::snapVertices().
   {
     return coords.begin();
   }
const_iterator geos::geom::CoordinateList::begin () const inline
Definition at line 107 of file CoordinateList.h.
   {
     return coords.begin();
   }
void geos::geom::CoordinateList::closeRing () inline
Definition at line 160 of file CoordinateList.h.
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellEdge(), and geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon().
   {
     if(!coords.empty() && ! (*(coords.begin())).equals(*(coords.rbegin())))
     {
       const Coordinate &c = *(coords.begin());
       coords.insert(coords.end(),c);
     }
   }
bool geos::geom::CoordinateList::empty () const inline
Definition at line 92 of file CoordinateList.h.
Referenced by geos::operation::overlay::snap::LineStringSnapper::snapSegments(), and geos::operation::overlay::snap::LineStringSnapper::snapVertices().
   {
     return coords.empty();
   }
iterator geos::geom::CoordinateList::end () inline
Definition at line 102 of file CoordinateList.h.
Referenced by geos::operation::overlay::snap::LineStringSnapper::findSnapForVertex(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon(), geos::geom::operator<<(), geos::operation::overlay::snap::LineStringSnapper::snapSegments(), and geos::operation::overlay::snap::LineStringSnapper::snapVertices().
   {
     return coords.end();
   }
const_iterator geos::geom::CoordinateList::end () const inline
Definition at line 112 of file CoordinateList.h.
   {
     return coords.end();
   }
iterator geos::geom::CoordinateList::erase (iterator pos) inline
Definition at line 144 of file CoordinateList.h.
   {
     return coords.erase(pos);
   }
iterator geos::geom::CoordinateList::erase (iterator first, iterator last) inline
Definition at line 149 of file CoordinateList.h.
   {
     return coords.erase(first, last);
   }
iterator geos::geom::CoordinateList::insert (iterator pos, const Coordinate & c, bool allowRepeated) inline
Inserts the specified coordinate at the specified position in this list.
Parameters
pos the position at which to insert
coord the coordinate to insert
allowRepeated if set to false, repeated coordinates are collapsed
Returns
an iterator to the newly installed coordinate (or previous, if equal and repeated are not allowed)
NOTE: when allowRepeated is false next point is not checked this matches JTS behavior
Definition at line 130 of file CoordinateList.h.
References geos::geom::Coordinate::equals2D().
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon(), and geos::operation::overlay::snap::LineStringSnapper::snapSegments().
   {
     if ( !allowRepeated && pos != coords.begin() ) {
       iterator prev = pos; --prev;
       if ( c.equals2D(*prev) ) return prev;
     }
     return coords.insert(pos, c);
   }
iterator geos::geom::CoordinateList::insert (iterator pos, const Coordinate & c) inline
Definition at line 139 of file CoordinateList.h.
   {
     return coords.insert(pos, c);
   }
size_type geos::geom::CoordinateList::size () const inline
Definition at line 87 of file CoordinateList.h.
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon().
   {
     return coords.size();
   }
std::unique_ptr<Coordinate::Vect> geos::geom::CoordinateList::toCoordinateArray () const inline
Definition at line 154 of file CoordinateList.h.
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::getVoronoiCellPolygon(), and geos::operation::overlay::snap::LineStringSnapper::snapTo().
   {
     std::unique_ptr<Coordinate::Vect> ret(new Coordinate::Vect);
     ret->assign(coords.begin(), coords.end());
     return ret;
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CoordinateList & cl) friend
Definition at line 176 of file CoordinateList.h.
 {
   os << "(";
   for (CoordinateList::const_iterator
     it=cl.begin(), end=cl.end();
     it != end;
     ++it)
   {
     const Coordinate& c = *it;
     if ( it != cl.begin() ) os << ", ";
     os << c;
   }
   os << ")";
   return os;
 }
Member Data Documentation
std::list<Coordinate> geos::geom::CoordinateList::coords private
Definition at line 172 of file CoordinateList.h.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/geom/CoordinateList.h