GEOS: geos::algorithm::locate::PointOnGeometryLocator Class Reference
geos::algorithm::locate::PointOnGeometryLocator Class Reference abstract
An interface for classes which determine the Location of points in Polygon or MultiPolygon geometries.
#include <PointOnGeometryLocator.h>
Public Member Functions
virtual ~PointOnGeometryLocator ()
virtual int locate (const geom::Coordinate *p)=0
Detailed Description
An interface for classes which determine the Location of points in Polygon or MultiPolygon geometries.
Author
Martin Davis
Definition at line 35 of file PointOnGeometryLocator.h.
Constructor & Destructor Documentation
virtual geos::algorithm::locate::PointOnGeometryLocator::~PointOnGeometryLocator () inline virtual
Definition at line 40 of file PointOnGeometryLocator.h.
   { }
Member Function Documentation
virtual int geos::algorithm::locate::PointOnGeometryLocator::locate (const geom::Coordinate * p) pure virtual
Determines the Location of a point in an areal Geometry.
Parameters
p the point to test
Returns
the location of the point in the geometry
Implemented in geos::algorithm::locate::IndexedPointInAreaLocator, and geos::algorithm::locate::SimplePointInAreaLocator.
Referenced by geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTarget(), geos::geom::prep::PreparedPolygonPredicate::isAllTestComponentsInTargetInterior(), geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTarget(), and geos::geom::prep::PreparedPolygonPredicate::isAnyTestComponentInTargetInterior().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/algorithm/locate/PointOnGeometryLocator.h