GEOS: geos::geom::util::ShortCircuitedGeometryVisitor Class Reference
geos::geom::util::ShortCircuitedGeometryVisitor Class Reference abstract
A visitor to Geometry elements which can be short-circuited by a given condition.
#include <ShortCircuitedGeometryVisitor.h>
Public Member Functions
ShortCircuitedGeometryVisitor ()
void applyTo (const Geometry &geom)
virtual ~ShortCircuitedGeometryVisitor ()
Protected Member Functions
virtual void visit (const Geometry &element)=0
virtual bool isDone ()=0
Private Attributes
bool done
Detailed Description
A visitor to Geometry elements which can be short-circuited by a given condition.
Last port: geom/util/ShortCircuitedGeometryVisitor.java rev. 1.1 (JTS-1.7)
Definition at line 39 of file ShortCircuitedGeometryVisitor.h.
Constructor & Destructor Documentation
geos::geom::util::ShortCircuitedGeometryVisitor::ShortCircuitedGeometryVisitor () inline
Definition at line 53 of file ShortCircuitedGeometryVisitor.h.
     :
     done(false)
     {}
virtual geos::geom::util::ShortCircuitedGeometryVisitor::~ShortCircuitedGeometryVisitor () inline virtual
Definition at line 60 of file ShortCircuitedGeometryVisitor.h.
 {}
Member Function Documentation
void geos::geom::util::ShortCircuitedGeometryVisitor::applyTo (const Geometry & geom)
Definition at line 31 of file ShortCircuitedGeometryVisitor.cpp.
References geos::geom::Geometry::getGeometryN(), and geos::geom::Geometry::getNumGeometries().
Referenced by geos::operation::predicate::RectangleIntersects::intersects().
 {
   for (std::size_t i=0, n=geom.getNumGeometries(); i<n; ++i)
   {
     const Geometry *element = geom.getGeometryN(i);
     if (dynamic_cast<const GeometryCollection*>(element))
     {
       applyTo(*element);
     }
     else
     {
       // calls the abstract virtual
       visit(*element);
       if (isDone()) done = true;
     }
     if ( done ) return;
   }
 }
virtual bool geos::geom::util::ShortCircuitedGeometryVisitor::isDone () protected pure virtual
Implemented in geos::operation::predicate::LineIntersectsVisitor, geos::operation::predicate::ContainsPointVisitor, and geos::operation::predicate::EnvelopeIntersectsVisitor.
virtual void geos::geom::util::ShortCircuitedGeometryVisitor::visit (const Geometry & element) protected pure virtual
Implemented in geos::operation::predicate::LineIntersectsVisitor, geos::operation::predicate::ContainsPointVisitor, and geos::operation::predicate::EnvelopeIntersectsVisitor.
Member Data Documentation
bool geos::geom::util::ShortCircuitedGeometryVisitor::done private
Definition at line 44 of file ShortCircuitedGeometryVisitor.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/util/ShortCircuitedGeometryVisitor.h
/home/vicky/potree/geos/vicky/src/geom/util/ShortCircuitedGeometryVisitor.cpp