GEOS: geos::operation::GeometryGraphOperation Class Reference
geos::operation::GeometryGraphOperation Class Reference
The base class for operations that require GeometryGraph.
#include <GeometryGraphOperation.h>
Public Member Functions
GeometryGraphOperation (const geom::Geometry *g0, const geom::Geometry *g1)
GeometryGraphOperation (const geom::Geometry *g0, const geom::Geometry *g1, const algorithm::BoundaryNodeRule &boundaryNodeRule)
GeometryGraphOperation (const geom::Geometry *g0)
virtual ~GeometryGraphOperation ()
const geom::Geometry * getArgGeometry (unsigned int i) const
Protected Member Functions
void setComputationPrecision (const geom::PrecisionModel *pm)
Protected Attributes
algorithm::LineIntersector li
const geom::PrecisionModel * resultPrecisionModel
std::vector< geomgraph::GeometryGraph * > arg
The operation args into an array so they can be accessed by index.
Detailed Description
The base class for operations that require GeometryGraph.
Definition at line 52 of file GeometryGraphOperation.h.
Constructor & Destructor Documentation
geos::operation::GeometryGraphOperation::GeometryGraphOperation (const geom::Geometry * g0, const geom::Geometry * g1)
Definition at line 38 of file GeometryGraphOperation.cpp.
References arg, geos::geom::PrecisionModel::compareTo(), geos::algorithm::BoundaryNodeRule::getBoundaryOGCSFS(), geos::geom::Geometry::getPrecisionModel(), and setComputationPrecision().
   :
   arg(2)
 {
   const PrecisionModel* pm0 = g0->getPrecisionModel();
   assert(pm0);
   const PrecisionModel* pm1 = g1->getPrecisionModel();
   assert(pm1);
   // use the most precise model for the result
   if (pm0->compareTo(pm1) >= 0)
     setComputationPrecision(pm0);
   else
     setComputationPrecision(pm1);
   arg[0]=new GeometryGraph(0, g0,
         algorithm::BoundaryNodeRule::getBoundaryOGCSFS());
   arg[1]=new GeometryGraph(1, g1,
     algorithm::BoundaryNodeRule::getBoundaryOGCSFS());
 }
geos::operation::GeometryGraphOperation::GeometryGraphOperation (const geom::Geometry * g0, const geom::Geometry * g1, const algorithm::BoundaryNodeRule & boundaryNodeRule)
Definition at line 61 of file GeometryGraphOperation.cpp.
References arg, geos::geom::PrecisionModel::compareTo(), geos::geom::Geometry::getPrecisionModel(), and setComputationPrecision().
   :
   arg(2)
 {
   const PrecisionModel* pm0 = g0->getPrecisionModel();
   assert(pm0);
   const PrecisionModel* pm1 = g1->getPrecisionModel();
   assert(pm1);
   // use the most precise model for the result
   if (pm0->compareTo(pm1) >= 0)
     setComputationPrecision(pm0);
   else
     setComputationPrecision(pm1);
   arg[0]=new GeometryGraph(0, g0, boundaryNodeRule);
   arg[1]=new GeometryGraph(1, g1, boundaryNodeRule);
 }
geos::operation::GeometryGraphOperation::GeometryGraphOperation (const geom::Geometry * g0)
Definition at line 84 of file GeometryGraphOperation.cpp.
References arg, geos::geom::Geometry::getPrecisionModel(), and setComputationPrecision().
                                                                 :
   arg(1)
 {
   const PrecisionModel* pm0 = g0->getPrecisionModel();
   assert(pm0);
   setComputationPrecision(pm0);
   arg[0]=new GeometryGraph(0, g0);
 }
geos::operation::GeometryGraphOperation::~GeometryGraphOperation () virtual
Definition at line 111 of file GeometryGraphOperation.cpp.
References arg.
 {
   for(unsigned int i=0; i<arg.size(); ++i)
   {
     delete arg[i];
   }
 }
Member Function Documentation
const Geometry * geos::operation::GeometryGraphOperation::getArgGeometry (unsigned int i) const
Definition at line 96 of file GeometryGraphOperation.cpp.
References arg.
Referenced by geos::operation::overlay::OverlayOp::computeOverlay(), and geos::operation::overlay::LineBuilder::labelIsolatedLine().
 {
   assert(i<arg.size());
   return arg[i]->getGeometry();
 }
void geos::operation::GeometryGraphOperation::setComputationPrecision (const geom::PrecisionModel * pm) protected
Definition at line 104 of file GeometryGraphOperation.cpp.
References li, resultPrecisionModel, and geos::algorithm::LineIntersector::setPrecisionModel().
Referenced by GeometryGraphOperation().
 {
   assert(pm);
   resultPrecisionModel=pm;
   li.setPrecisionModel(resultPrecisionModel);
 }
Member Data Documentation
std::vector<geomgraph::GeometryGraph*> geos::operation::GeometryGraphOperation::arg protected
The operation args into an array so they can be accessed by index.
Definition at line 78 of file GeometryGraphOperation.h.
Referenced by geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), geos::operation::overlay::OverlayOp::computeLabelling(), geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::OverlayOp::copyPoints(), GeometryGraphOperation(), getArgGeometry(), geos::operation::overlay::OverlayOp::getAverageZ(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), and ~GeometryGraphOperation().
algorithm::LineIntersector geos::operation::GeometryGraphOperation::li protected
Definition at line 71 of file GeometryGraphOperation.h.
Referenced by geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::OverlayOp::mergeZ(), and setComputationPrecision().
const geom::PrecisionModel* geos::operation::GeometryGraphOperation::resultPrecisionModel protected
Definition at line 73 of file GeometryGraphOperation.h.
Referenced by geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), geos::operation::overlay::OverlayOp::computeOverlay(), and setComputationPrecision().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/GeometryGraphOperation.h
/home/vicky/potree/geos/vicky/src/operation/GeometryGraphOperation.cpp