GEOS: geos::operation::buffer::OffsetCurveBuilder Class Reference
geos::operation::buffer::OffsetCurveBuilder Class Reference
Computes the raw offset curve for a single Geometry component (ring, line or point).
#include <geos/opBuffer.h>
Public Member Functions
OffsetCurveBuilder (const geom::PrecisionModel *newPrecisionModel, const BufferParameters &nBufParams)
const BufferParameters & getBufferParameters () const
void getLineCurve (const geom::CoordinateSequence *inputPts, double distance, std::vector< geom::CoordinateSequence * > &lineList)
void getSingleSidedLineCurve (const geom::CoordinateSequence *inputPts, double distance, std::vector< geom::CoordinateSequence * > &lineList, bool leftSide, bool rightSide)
void getRingCurve (const geom::CoordinateSequence *inputPts, int side, double distance, std::vector< geom::CoordinateSequence * > &lineList)
Private Member Functions
double simplifyTolerance (double bufDistance)
Computes the distance tolerance to use during input line simplification.
void computeLineBufferCurve (const geom::CoordinateSequence &inputPts, OffsetSegmentGenerator &segGen)
void computeSingleSidedBufferCurve (const geom::CoordinateSequence &inputPts, bool isRightSide, OffsetSegmentGenerator &segGen)
void computeRingBufferCurve (const geom::CoordinateSequence &inputPts, int side, OffsetSegmentGenerator &segGen)
std::unique_ptr< OffsetSegmentGenerator > getSegGen (double dist)
void computePointCurve (const geom::Coordinate &pt, OffsetSegmentGenerator &segGen)
OffsetCurveBuilder (const OffsetCurveBuilder &other)=delete
OffsetCurveBuilder & operator= (const OffsetCurveBuilder &rhs)=delete
Private Attributes
double distance
const geom::PrecisionModel * precisionModel
const BufferParameters & bufParams
Static Private Attributes
static const double SIMPLIFY_FACTOR = 100.0
Detailed Description
Computes the raw offset curve for a single Geometry component (ring, line or point).
A raw offset curve line is not noded - it may contain self-intersections (and usually will). The final buffer polygon is computed by forming a topological graph of all the noded raw curves and tracing outside contours. The points in the raw curve are rounded to a given geom::PrecisionModel.
Definition at line 62 of file OffsetCurveBuilder.h.
Constructor & Destructor Documentation
geos::operation::buffer::OffsetCurveBuilder::OffsetCurveBuilder (const geom::PrecisionModel * newPrecisionModel, const BufferParameters & nBufParams) inline
Definition at line 72 of file OffsetCurveBuilder.h.
     :
     distance(0.0),
     precisionModel(newPrecisionModel),
     bufParams(nBufParams)
   {}
geos::operation::buffer::OffsetCurveBuilder::OffsetCurveBuilder (const OffsetCurveBuilder & other) private delete
Member Function Documentation
void geos::operation::buffer::OffsetCurveBuilder::computeLineBufferCurve (const geom::CoordinateSequence & inputPts, OffsetSegmentGenerator & segGen) private
Definition at line 198 of file OffsetCurveBuilder.cpp.
References geos::operation::buffer::OffsetSegmentGenerator::addLastSegment(), geos::operation::buffer::OffsetSegmentGenerator::addLineEndCap(), geos::operation::buffer::OffsetSegmentGenerator::addNextSegment(), geos::operation::buffer::OffsetSegmentGenerator::closeRing(), geos::operation::intersection::distance(), geos::operation::buffer::OffsetSegmentGenerator::initSideSegments(), and geos::geom::CoordinateSequence::size().
 {
   double distTol = simplifyTolerance(distance);
   //--------- compute points for left side of line
   // Simplify the appropriate side of the line before generating
   std::unique_ptr<CoordinateSequence> simp1_ =
     BufferInputLineSimplifier::simplify(inputPts, distTol);
   const CoordinateSequence& simp1 = *simp1_;
   int n1 = static_cast<int>(simp1.size()) - 1;
   segGen.initSideSegments(simp1[0], simp1[1], Position::LEFT);
   for (int i = 2; i <= n1; ++i) {
     segGen.addNextSegment(simp1[i], true);
   }
   segGen.addLastSegment();
   // add line cap for end of line
   segGen.addLineEndCap(simp1[n1-1], simp1[n1]);
   //---------- compute points for right side of line
   // Simplify the appropriate side of the line before generating
   std::unique_ptr<CoordinateSequence> simp2_ =
     BufferInputLineSimplifier::simplify(inputPts, -distTol);
   const CoordinateSequence& simp2 = *simp2_;
   int n2 = static_cast<int>(simp2.size()) - 1;
   segGen.initSideSegments(simp2[n2], simp2[n2-1], Position::LEFT);
   for (int i = n2-2; i >= 0; --i) {
     segGen.addNextSegment(simp2[i], true);
   }
   segGen.addLastSegment();
   // add line cap for start of line
   segGen.addLineEndCap(simp2[1], simp2[0]);
   segGen.closeRing();
 }
void geos::operation::buffer::OffsetCurveBuilder::computePointCurve (const geom::Coordinate & pt, OffsetSegmentGenerator & segGen) private
Definition at line 88 of file OffsetCurveBuilder.cpp.
References geos::operation::buffer::OffsetSegmentGenerator::createCircle(), geos::operation::buffer::OffsetSegmentGenerator::createSquare(), and geos::operation::intersection::distance().
 {
   switch (bufParams.getEndCapStyle()) {
     case BufferParameters::CAP_ROUND:
       segGen.createCircle(pt, distance);
       break;
     case BufferParameters::CAP_SQUARE:
       segGen.createSquare(pt, distance);
       break;
     default:
       // otherwise curve is empty (e.g. for a butt cap);
       break;
   }
 }
void geos::operation::buffer::OffsetCurveBuilder::computeRingBufferCurve (const geom::CoordinateSequence & inputPts, int side, OffsetSegmentGenerator & segGen) private
Definition at line 239 of file OffsetCurveBuilder.cpp.
References geos::operation::buffer::OffsetSegmentGenerator::addNextSegment(), geos::operation::buffer::OffsetSegmentGenerator::closeRing(), geos::operation::intersection::distance(), geos::operation::buffer::OffsetSegmentGenerator::initSideSegments(), and geos::geom::CoordinateSequence::size().
 {
   // simplify input line to improve performance
   double distTol = simplifyTolerance(distance);
   // ensure that correct side is simplified
   if (side == Position::RIGHT)
     distTol = -distTol;
   std::unique_ptr<CoordinateSequence> simp_ =
     BufferInputLineSimplifier::simplify(inputPts, distTol);
   const CoordinateSequence& simp = *simp_;
   int n = static_cast<int>(simp.size())-1;
   segGen.initSideSegments(simp[n-1], simp[0], side);
   for (int i = 1; i <= n; i++) {
     bool addStartPoint = i != 1;
     segGen.addNextSegment(simp[i], addStartPoint);
   }
   segGen.closeRing();
 }
void geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve (const geom::CoordinateSequence & inputPts, bool isRightSide, OffsetSegmentGenerator & segGen) private
Definition at line 262 of file OffsetCurveBuilder.cpp.
References geos::operation::buffer::OffsetSegmentGenerator::addFirstSegment(), geos::operation::buffer::OffsetSegmentGenerator::addLastSegment(), geos::operation::buffer::OffsetSegmentGenerator::addNextSegment(), geos::operation::buffer::OffsetSegmentGenerator::addSegments(), geos::operation::buffer::OffsetSegmentGenerator::closeRing(), geos::operation::intersection::distance(), geos::operation::buffer::OffsetSegmentGenerator::initSideSegments(), and geos::geom::CoordinateSequence::size().
 {
   double distTol = simplifyTolerance(distance);
   if ( isRightSide ) {
     // add original line
     segGen.addSegments(inputPts, true);
     //---------- compute points for right side of line
     // Simplify the appropriate side of the line before generating
     std::unique_ptr<CoordinateSequence> simp2_ =
       BufferInputLineSimplifier::simplify(inputPts, -distTol);
     const CoordinateSequence& simp2 = *simp2_;
     int n2 = static_cast<int>(simp2.size()) - 1;
     segGen.initSideSegments(simp2[n2], simp2[n2-1], Position::LEFT);
     segGen.addFirstSegment();
     for (int i = n2-2; i >= 0; --i) {
       segGen.addNextSegment(simp2[i], true);
     }
   } else {
     // add original line
     segGen.addSegments(inputPts, false);
     //--------- compute points for left side of line
     // Simplify the appropriate side of the line before generating
     std::unique_ptr<CoordinateSequence> simp1_ =
       BufferInputLineSimplifier::simplify(inputPts, distTol);
     const CoordinateSequence& simp1 = *simp1_;
     int n1 = static_cast<int>(simp1.size()) - 1;
     segGen.initSideSegments(simp1[0], simp1[1], Position::LEFT);
     segGen.addFirstSegment();
     for (int i = 2; i <= n1; ++i) {
       segGen.addNextSegment(simp1[i], true);
     }
   }
   segGen.addLastSegment();
   segGen.closeRing();
 }
const BufferParameters& geos::operation::buffer::OffsetCurveBuilder::getBufferParameters () const inline
Gets the buffer parameters being used to generate the curve.
Returns
the buffer parameters being used
Definition at line 85 of file OffsetCurveBuilder.h.
References geos::operation::intersection::distance().
Referenced by geos::operation::buffer::OffsetCurveSetBuilder::addLineString().
   {
     return bufParams;
   }
void geos::operation::buffer::OffsetCurveBuilder::getLineCurve (const geom::CoordinateSequence * inputPts, double distance, std::vector< geom::CoordinateSequence * > & lineList)
This method handles single points as well as lines. Lines are assumed to not be closed (the function will not fail for closed lines, but will generate superfluous line caps).
Parameters
lineList the std::vector to which the newly created CoordinateSequences will be pushed_back. Caller is responsible to delete these new elements.
Definition at line 59 of file OffsetCurveBuilder.cpp.
References geos::operation::intersection::distance(), geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
Referenced by geos::operation::buffer::OffsetCurveSetBuilder::addLineString(), and geos::operation::buffer::OffsetCurveSetBuilder::addPoint().
 {
   distance = nDistance;
   // a zero or (non-singlesided) negative width buffer of a line/point is empty
   if (distance == 0.0) return;
   if (distance < 0.0 && ! bufParams.isSingleSided()) return;
   double posDistance = std::abs(distance);
   std::unique_ptr<OffsetSegmentGenerator> segGen = getSegGen(posDistance);
   if (inputPts->getSize() <= 1) {
     computePointCurve(inputPts->getAt(0), *segGen);
   } else {
     if (bufParams.isSingleSided()) {
       bool isRightSide = distance < 0.0;
       computeSingleSidedBufferCurve(*inputPts, isRightSide, *segGen);
     }
     else {
       computeLineBufferCurve(*inputPts, *segGen);
     }
   }
   segGen->getCoordinates(lineList);
 }
void geos::operation::buffer::OffsetCurveBuilder::getRingCurve (const geom::CoordinateSequence * inputPts, int side, double distance, std::vector< geom::CoordinateSequence * > & lineList)
This method handles the degenerate cases of single points and lines, as well as rings.
Parameters
lineList the std::vector to which CoordinateSequences will be pushed_back
Definition at line 166 of file OffsetCurveBuilder.cpp.
References geos::geom::CoordinateSequence::clone(), geos::operation::intersection::distance(), and geos::geom::CoordinateSequence::getSize().
Referenced by geos::operation::buffer::OffsetCurveSetBuilder::addPolygonRing().
 {
   distance = nDistance;
   // optimize creating ring for zero distance
   if (distance == 0.0) {
     lineList.push_back(inputPts->clone());
     return;
   }
   if (inputPts->getSize() <= 2)
   {
     getLineCurve(inputPts, distance, lineList);
     return;
   }
   std::unique_ptr<OffsetSegmentGenerator> segGen = getSegGen(std::abs(distance));
   computeRingBufferCurve(*inputPts, side, *segGen);
   segGen->getCoordinates(lineList);
 }
std::unique_ptr< OffsetSegmentGenerator > geos::operation::buffer::OffsetCurveBuilder::getSegGen (double dist) private
Definition at line 311 of file OffsetCurveBuilder.cpp.
 {
   std::unique_ptr<OffsetSegmentGenerator> osg(
     new OffsetSegmentGenerator(precisionModel, bufParams, dist)
   );
   return osg;
 }
void geos::operation::buffer::OffsetCurveBuilder::getSingleSidedLineCurve (const geom::CoordinateSequence * inputPts, double distance, std::vector< geom::CoordinateSequence * > & lineList, bool leftSide, bool rightSide)
This method handles single points as well as lines.
Lines are assumed to not be closed (the function will not fail for closed lines, but will generate superfluous line caps).
Parameters
lineList the std::vector to which newly created CoordinateSequences will be pushed_back. Caller will be responsible to delete them.
leftSide indicates that the left side buffer will be obtained/skipped
rightSide indicates that the right side buffer will be obtained/skipped
NOTE: this is a GEOS extension
Definition at line 106 of file OffsetCurveBuilder.cpp.
References geos::geom::CoordinateSequence::getSize(), and geos::geom::CoordinateSequence::size().
Referenced by geos::operation::buffer::BufferBuilder::bufferLineSingleSided().
 {
    // A zero or negative width buffer of a line/point is empty.
    if ( distance <= 0.0 ) return ;
    if ( inputPts->getSize() < 2 )
    {
       // No cap, so just return.
       return ;
    }
   double distTol = simplifyTolerance(distance);
   std::unique_ptr<OffsetSegmentGenerator> segGen = getSegGen(distance);
   if ( leftSide ) {
     //--------- compute points for left side of line
     // Simplify the appropriate side of the line before generating
     std::unique_ptr<CoordinateSequence> simp1_ =
       BufferInputLineSimplifier::simplify( *inputPts, distTol );
     const CoordinateSequence& simp1 = *simp1_;
     int n1 = static_cast<int>(simp1.size()) - 1;
     if ( ! n1 )
       throw util::IllegalArgumentException("Cannot get offset of single-vertex line");
     segGen->initSideSegments(simp1[0], simp1[1], Position::LEFT);
     segGen->addFirstSegment();
     for (int i = 2; i <= n1; ++i) {
       segGen->addNextSegment(simp1[i], true);
     }
     segGen->addLastSegment();
   }
   if ( rightSide ) {
     //---------- compute points for right side of line
     // Simplify the appropriate side of the line before generating
     std::unique_ptr<CoordinateSequence> simp2_ =
       BufferInputLineSimplifier::simplify( *inputPts, -distTol );
     const CoordinateSequence& simp2 = *simp2_;
     int n2 = static_cast<int>(simp2.size()) - 1;
     if ( ! n2 )
       throw util::IllegalArgumentException("Cannot get offset of single-vertex line");
     segGen->initSideSegments(simp2[n2], simp2[n2-1], Position::LEFT);
     segGen->addFirstSegment();
     for (int i = n2-2; i >= 0; --i) {
       segGen->addNextSegment(simp2[i], true);
     }
     segGen->addLastSegment();
   }
   segGen->getCoordinates(lineList);
 }
OffsetCurveBuilder& geos::operation::buffer::OffsetCurveBuilder::operator= (const OffsetCurveBuilder & rhs) private delete
double geos::operation::buffer::OffsetCurveBuilder::simplifyTolerance (double bufDistance) private
Computes the distance tolerance to use during input line simplification.
Parameters
distance the buffer distance
Returns
the simplification tolerance
Definition at line 191 of file OffsetCurveBuilder.cpp.
 {
   return bufDistance / SIMPLIFY_FACTOR;
 }
Member Data Documentation
const BufferParameters& geos::operation::buffer::OffsetCurveBuilder::bufParams private
Definition at line 141 of file OffsetCurveBuilder.h.
double geos::operation::buffer::OffsetCurveBuilder::distance private
Definition at line 137 of file OffsetCurveBuilder.h.
const geom::PrecisionModel* geos::operation::buffer::OffsetCurveBuilder::precisionModel private
Definition at line 139 of file OffsetCurveBuilder.h.
const double geos::operation::buffer::OffsetCurveBuilder::SIMPLIFY_FACTOR = 100.0 static private
Use a value which results in a potential distance error which is significantly less than the error due to the quadrant segment discretization. For QS = 8 a value of 100 is reasonable. This should produce a maximum of 1% distance error.
Definition at line 150 of file OffsetCurveBuilder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/OffsetCurveBuilder.h
/home/vicky/potree/geos/vicky/src/operation/buffer/OffsetCurveBuilder.cpp