GEOS: geos::precision::GeometryPrecisionReducer Class Reference
geos::precision::GeometryPrecisionReducer Class Reference
Reduces the precision of a Geometry according to the supplied PrecisionModel, ensuring that the result is topologically valid.
#include <GeometryPrecisionReducer.h>
Public Member Functions
GeometryPrecisionReducer (const geom::PrecisionModel &pm)
GeometryPrecisionReducer (const geom::GeometryFactory &gf)
Create a reducer that will change the precision model of the new reduced Geometry.
void setRemoveCollapsedComponents (bool remove)
void setPointwise (bool pointwise)
Sets whether the precision reduction will be done in pointwise fashion only.
std::unique_ptr< geom::Geometry > reduce (const geom::Geometry &geom)
Static Public Member Functions
static std::unique_ptr< geom::Geometry > reduce (const geom::Geometry &g, const geom::PrecisionModel &precModel)
static std::unique_ptr< geom::Geometry > reducePointwise (const geom::Geometry &g, const geom::PrecisionModel &precModel)
Private Member Functions
std::unique_ptr< geom::Geometry > reducePointwise (const geom::Geometry &geom)
std::unique_ptr< geom::Geometry > fixPolygonalTopology (const geom::Geometry &geom)
geom::GeometryFactory::Ptr createFactory (const geom::GeometryFactory &oldGF, const geom::PrecisionModel &newPM)
GeometryPrecisionReducer (GeometryPrecisionReducer const &)
GeometryPrecisionReducer & operator= (GeometryPrecisionReducer const &)
Private Attributes
const geom::GeometryFactory * newFactory
const geom::PrecisionModel & targetPM
bool removeCollapsed
bool isPointwise
Detailed Description
Reduces the precision of a Geometry according to the supplied PrecisionModel, ensuring that the result is topologically valid.
Definition at line 43 of file GeometryPrecisionReducer.h.
Constructor & Destructor Documentation
geos::precision::GeometryPrecisionReducer::GeometryPrecisionReducer (GeometryPrecisionReducer const &) private
geos::precision::GeometryPrecisionReducer::GeometryPrecisionReducer (const geom::PrecisionModel & pm) inline
Definition at line 109 of file GeometryPrecisionReducer.h.
       :
       newFactory(nullptr),
       targetPM(pm),
       removeCollapsed(true),
       isPointwise(false)
   {}
geos::precision::GeometryPrecisionReducer::GeometryPrecisionReducer (const geom::GeometryFactory & gf)
Create a reducer that will change the precision model of the new reduced Geometry.
Parameters
gf the factory for the created Geometry. Its PrecisionModel will be used for the reduction. NOTE: ownership left to caller must be kept alive for the whole lifetime of the returned Geometry.
Definition at line 93 of file GeometryPrecisionReducer.cpp.
       :
       newFactory(&changeFactory),
       targetPM(*(changeFactory.getPrecisionModel())),
       removeCollapsed(true),
       isPointwise(false)
 {}
Member Function Documentation
GeometryFactory::Ptr geos::precision::GeometryPrecisionReducer::createFactory (const geom::GeometryFactory & oldGF, const geom::PrecisionModel & newPM) private
Definition at line 132 of file GeometryPrecisionReducer.cpp.
References geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::geom::GeometryFactory::getSRID(), and newFactory.
Referenced by fixPolygonalTopology().
 {
   GeometryFactory::Ptr newFactory(
     GeometryFactory::create(&newPM,
                         oldGF.getSRID(),
                         const_cast<CoordinateSequenceFactory*>(oldGF.getCoordinateSequenceFactory()))
   );
   return newFactory;
 }
unique_ptr< Geometry > geos::precision::GeometryPrecisionReducer::fixPolygonalTopology (const geom::Geometry & geom) private
If precision model was not changed, need to flip geometry to targetPM, buffer in that model, then flip back
Definition at line 103 of file GeometryPrecisionReducer.cpp.
References geos::geom::Geometry::buffer(), createFactory(), geos::geom::GeometryFactory::createGeometry(), geos::geom::Geometry::getFactory(), newFactory, and targetPM.
 {
   unique_ptr<Geometry> tmp;
   GeometryFactory::Ptr tmpFactory;
   const Geometry* geomToBuffer = &geom;
   if ( ! newFactory ) {
     tmpFactory = createFactory(*geom.getFactory(), targetPM);
     tmp.reset( tmpFactory->createGeometry(&geom) );
     geomToBuffer = tmp.get();
   }
   unique_ptr<Geometry> bufGeom ( geomToBuffer->buffer(0) );
   if ( ! newFactory ) {
     // a slick way to copy the geometry with the original precision factory
     bufGeom.reset( geom.getFactory()->createGeometry(bufGeom.get()) );
   }
   return bufGeom;
 }
GeometryPrecisionReducer& geos::precision::GeometryPrecisionReducer::operator= (GeometryPrecisionReducer const &) private
static std::unique_ptr<geom::Geometry> geos::precision::GeometryPrecisionReducer::reduce (const geom::Geometry & g, const geom::PrecisionModel & precModel) inline static
Convenience method for doing precision reduction on a single geometry, with collapses removed and keeping the geometry precision model the same, and preserving polygonal topology.
Parameters
g the geometry to reduce
precModel the precision model to use
Returns
the reduced geometry
Definition at line 81 of file GeometryPrecisionReducer.h.
References reduce().
Referenced by geos::geom::BinaryOp(), GEOSGeom_setPrecision_r(), reduce(), and reducePointwise().
   {
     GeometryPrecisionReducer reducer(precModel);
     return reducer.reduce(g);
   }
unique_ptr< Geometry > geos::precision::GeometryPrecisionReducer::reduce (const geom::Geometry & geom)
Definition at line 72 of file GeometryPrecisionReducer.cpp.
 {
   unique_ptr<Geometry> reducePW = reducePointwise(geom);
   if ( isPointwise ) return reducePW;
   //TODO: handle GeometryCollections containing polys
   if (! (dynamic_cast<const Polygonal*>(reducePW.get())) )
     return reducePW;
   // Geometry is polygonal - test if topology needs to be fixed
   if (reducePW->isValid()) return reducePW;
   // hack to fix topology.
   // TODO: implement snap-rounding and use that.
   return fixPolygonalTopology(*reducePW);
 }
unique_ptr< Geometry > geos::precision::GeometryPrecisionReducer::reducePointwise (const geom::Geometry & geom) private
For polygonal geometries, collapses are always removed, in order to produce correct topology
Definition at line 45 of file GeometryPrecisionReducer.cpp.
References geos::geom::Geometry::getDimension().
 {
   unique_ptr<GeometryEditor> geomEdit;
   if ( newFactory ) {
       geomEdit.reset( new GeometryEditor(newFactory) );
   } else {
       geomEdit.reset( new GeometryEditor() );
   }
   bool finalRemoveCollapsed = removeCollapsed;
   if (geom.getDimension() >= 2)
     finalRemoveCollapsed = true;
   PrecisionReducerCoordinateOperation prco(targetPM, finalRemoveCollapsed);
   std::unique_ptr<Geometry> g ( geomEdit->edit(&geom, &prco) );
   return g;
 }
static std::unique_ptr<geom::Geometry> geos::precision::GeometryPrecisionReducer::reducePointwise (const geom::Geometry & g, const geom::PrecisionModel & precModel) inline static
Convenience method for doing precision reduction on a single geometry, with collapses removed and keeping the geometry precision model the same, but NOT preserving valid polygonal topology.
Parameters
g the geometry to reduce
precModel the precision model to use
Returns
the reduced geometry
Definition at line 100 of file GeometryPrecisionReducer.h.
References reduce(), and setPointwise().
   {
     GeometryPrecisionReducer reducer(precModel);
     reducer.setPointwise(true);
     return reducer.reduce(g);
   }
void geos::precision::GeometryPrecisionReducer::setPointwise (bool pointwise) inline
Sets whether the precision reduction will be done in pointwise fashion only.
Pointwise precision reduction reduces the precision of the individual coordinates only, but does not attempt to recreate valid topology. This is only relevant for geometries containing polygonal components.
Parameters
pointwise if reduction should be done pointwise only
Definition at line 151 of file GeometryPrecisionReducer.h.
Referenced by GEOSGeom_setPrecision_r(), and reducePointwise().
   {
     isPointwise = pointwise;
   }
void geos::precision::GeometryPrecisionReducer::setRemoveCollapsedComponents (bool remove) inline
Sets whether the reduction will result in collapsed components being removed completely, or simply being collapsed to an (invalid) Geometry of the same type.
Parameters
remove if true collapsed components will be removed
Definition at line 136 of file GeometryPrecisionReducer.h.
Referenced by GEOSGeom_setPrecision_r().
{
     removeCollapsed = remove;
   }
Member Data Documentation
bool geos::precision::GeometryPrecisionReducer::isPointwise private
Definition at line 54 of file GeometryPrecisionReducer.h.
const geom::GeometryFactory* geos::precision::GeometryPrecisionReducer::newFactory private
Definition at line 48 of file GeometryPrecisionReducer.h.
Referenced by createFactory(), and fixPolygonalTopology().
bool geos::precision::GeometryPrecisionReducer::removeCollapsed private
Definition at line 52 of file GeometryPrecisionReducer.h.
const geom::PrecisionModel& geos::precision::GeometryPrecisionReducer::targetPM private
Definition at line 50 of file GeometryPrecisionReducer.h.
Referenced by fixPolygonalTopology().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/precision/GeometryPrecisionReducer.h
/home/vicky/potree/geos/vicky/src/precision/GeometryPrecisionReducer.cpp