GEOS: geos::geom::util::CoordinateOperation Class Reference
geos::geom::util::CoordinateOperation Class Reference abstract
#include <CoordinateOperation.h>
Public Member Functions
Geometry * edit (const Geometry *geometry, const GeometryFactory *factory) override
virtual CoordinateSequence * edit (const CoordinateSequence *coordinates, const Geometry *geometry)=0
~CoordinateOperation () override
Detailed Description
A GeometryEditorOperation which modifies the coordinate list of a Geometry. Operates on Geometry subclasses which contains a single coordinate list.
Definition at line 41 of file CoordinateOperation.h.
Constructor & Destructor Documentation
geos::geom::util::CoordinateOperation::~CoordinateOperation () inline override
Definition at line 63 of file CoordinateOperation.h.
 {}
Member Function Documentation
Geometry * geos::geom::util::CoordinateOperation::edit (const Geometry * geometry, const GeometryFactory * factory) override virtual
Return a newly created geometry, ownership to caller
Implements geos::geom::util::GeometryEditorOperation.
Definition at line 30 of file CoordinateOperation.cpp.
References geos::geom::Geometry::clone(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::GeometryFactory::createLineString(), geos::geom::GeometryFactory::createPoint(), edit(), geos::geom::Geometry::getCoordinates(), and geos::geom::LineString::getCoordinatesRO().
Referenced by edit().
 {
     const LinearRing *ring = dynamic_cast<const LinearRing *>(geometry);
     if (ring) {
       const CoordinateSequence *coords = ring->getCoordinatesRO();
       CoordinateSequence *newCoords = edit(coords,geometry);
             // LinearRing instance takes over ownership of newCoords instance
       return factory->createLinearRing(newCoords);
     }
     const LineString *line = dynamic_cast<const LineString *>(geometry);
     if (line) {
       const CoordinateSequence *coords = line->getCoordinatesRO();
       CoordinateSequence *newCoords = edit(coords,geometry);
       return factory->createLineString(newCoords);
     }
     if (typeid(*geometry)==typeid(Point)) {
       CoordinateSequence *coords = geometry->getCoordinates();
       CoordinateSequence *newCoords = edit(coords,geometry);
       delete coords;
       return factory->createPoint(newCoords);
     }
     return geometry->clone();
 }
virtual CoordinateSequence* geos::geom::util::CoordinateOperation::edit (const CoordinateSequence * coordinates, const Geometry * geometry) pure virtual
Edits the array of Coordinate from a Geometry.
Parameters
coordinates the coordinate array to operate on
geometry the geometry containing the coordinate list
Returns
an edited coordinate array (which may be the same as the input)
Implemented in geos::precision::PrecisionReducerCoordinateOperation.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/util/CoordinateOperation.h
/home/vicky/potree/geos/vicky/src/geom/util/CoordinateOperation.cpp