GEOS: geos::algorithm::InteriorPointLine Class Reference
geos::algorithm::InteriorPointLine Class Reference
Computes a point in the interior of an linear geometry.
#include <InteriorPointLine.h>
Public Member Functions
InteriorPointLine (const geom::Geometry *g)
~InteriorPointLine ()
bool getInteriorPoint (geom::Coordinate &ret) const
Private Member Functions
void addInterior (const geom::Geometry *geom)
void addInterior (const geom::CoordinateSequence *pts)
void addEndpoints (const geom::Geometry *geom)
void addEndpoints (const geom::CoordinateSequence *pts)
void add (const geom::Coordinate &point)
Private Attributes
bool hasInterior
geom::Coordinate centroid
double minDistance
geom::Coordinate interiorPoint
Detailed Description
Computes a point in the interior of an linear geometry.
Algorithm
Find an interior vertex which is closest to the centroid of the linestring.
If there is no interior vertex, find the endpoint which is closest to the centroid.
Definition at line 48 of file InteriorPointLine.h.
Constructor & Destructor Documentation
geos::algorithm::InteriorPointLine::InteriorPointLine (const geom::Geometry * g)
Definition at line 40 of file InteriorPointLine.cpp.
References geos::geom::Geometry::getCentroid().
 {
   minDistance=DoubleMax;
   hasInterior=false;
   if ( g->getCentroid(centroid) )
   {
 #if GEOS_DEBUG
     std::cerr << "Centroid: " << centroid << std::endl;
 #endif
     addInterior(g);
   }
   if (!hasInterior) addEndpoints(g);
 }
geos::algorithm::InteriorPointLine::~InteriorPointLine ()
Definition at line 54 of file InteriorPointLine.cpp.
 {
 }
Member Function Documentation
void geos::algorithm::InteriorPointLine::add (const geom::Coordinate & point) private
Definition at line 130 of file InteriorPointLine.cpp.
References geos::geom::Coordinate::distance().
 {
   double dist=point.distance(centroid);
 #if GEOS_DEBUG
   std::cerr << "point " << point << " dist " << dist << ", minDistance " << minDistance << std::endl;
 #endif
   if (!hasInterior || dist<minDistance) {
     interiorPoint=point;
 #if GEOS_DEBUG
     std::cerr << " is new InteriorPoint" << std::endl;
 #endif
     minDistance=dist;
     hasInterior=true;
   }
 }
void geos::algorithm::InteriorPointLine::addEndpoints (const geom::Geometry * geom) private
Definition at line 101 of file InteriorPointLine.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   const LineString *ls = dynamic_cast<const LineString*>(geom);
   if ( ls ) {
     addEndpoints(ls->getCoordinatesRO());
     return;
   }
   const GeometryCollection *gc = dynamic_cast<const GeometryCollection*>(geom);
   if ( gc )
   {
     for(std::size_t i=0, n=gc->getNumGeometries(); i<n; i++) {
       addEndpoints(gc->getGeometryN(i));
     }
   }
 }
void geos::algorithm::InteriorPointLine::addEndpoints (const geom::CoordinateSequence * pts) private
Definition at line 119 of file InteriorPointLine.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::size().
 {
   size_t npts = pts->size();
   if ( npts ) {
     add(pts->getAt(0));
     if ( npts > 1 ) add(pts->getAt(npts-1));
   }
 }
void geos::algorithm::InteriorPointLine::addInterior (const geom::Geometry * geom) private
Definition at line 66 of file InteriorPointLine.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   const LineString *ls = dynamic_cast<const LineString*>(geom);
   if ( ls ) {
     addInterior(ls->getCoordinatesRO());
     return;
   }
   const GeometryCollection *gc = dynamic_cast<const GeometryCollection*>(geom);
   if ( gc )
   {
     for(std::size_t i=0, n=gc->getNumGeometries(); i<n; i++) {
       addInterior(gc->getGeometryN(i));
     }
   }
 }
void geos::algorithm::InteriorPointLine::addInterior (const geom::CoordinateSequence * pts) private
Definition at line 84 of file InteriorPointLine.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   const std::size_t n=pts->getSize()-1;
   for(std::size_t i=1; i<n; ++i)
   {
     add(pts->getAt(i));
   }
 }
bool geos::algorithm::InteriorPointLine::getInteriorPoint (geom::Coordinate & ret) const
Definition at line 148 of file InteriorPointLine.cpp.
Referenced by geos::geom::Geometry::getInteriorPoint().
 {
   if ( ! hasInterior ) return false;
   ret=interiorPoint;
   return true;
 }
Member Data Documentation
geom::Coordinate geos::algorithm::InteriorPointLine::centroid private
Definition at line 63 of file InteriorPointLine.h.
bool geos::algorithm::InteriorPointLine::hasInterior private
Definition at line 61 of file InteriorPointLine.h.
geom::Coordinate geos::algorithm::InteriorPointLine::interiorPoint private
Definition at line 67 of file InteriorPointLine.h.
double geos::algorithm::InteriorPointLine::minDistance private
Definition at line 65 of file InteriorPointLine.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/InteriorPointLine.h
/home/vicky/potree/geos/vicky/src/algorithm/InteriorPointLine.cpp