GEOS: geos::operation::valid::QuadtreeNestedRingTester Class Reference
geos::operation::valid::QuadtreeNestedRingTester Class Reference
Tests whether any of a set of LinearRings are nested inside another ring in the set, using a Quadtree index to speed up the comparisons.
#include <QuadtreeNestedRingTester.h>
Public Member Functions
QuadtreeNestedRingTester (geomgraph::GeometryGraph *newGraph)
Caller retains ownership of GeometryGraph.
~QuadtreeNestedRingTester ()
geom::Coordinate * getNestedPoint ()
void add (const geom::LinearRing *ring)
bool isNonNested ()
Private Member Functions
void buildQuadtree ()
Private Attributes
geomgraph::GeometryGraph * graph
std::vector< const geom::LinearRing * > rings
geom::Envelope totalEnv
index::quadtree::Quadtree * qt
geom::Coordinate * nestedPt
Detailed Description
Tests whether any of a set of LinearRings are nested inside another ring in the set, using a Quadtree index to speed up the comparisons.
Definition at line 60 of file QuadtreeNestedRingTester.h.
Constructor & Destructor Documentation
geos::operation::valid::QuadtreeNestedRingTester::QuadtreeNestedRingTester (geomgraph::GeometryGraph * newGraph)
Caller retains ownership of GeometryGraph.
Definition at line 41 of file QuadtreeNestedRingTester.cpp.
                                                                          :
   graph(newGraph),
   rings(),
   totalEnv(),
   qt(nullptr),
   nestedPt(nullptr)
 {
 }
geos::operation::valid::QuadtreeNestedRingTester::~QuadtreeNestedRingTester ()
Definition at line 50 of file QuadtreeNestedRingTester.cpp.
References qt.
 {
   //delete rings;
   //delete totalEnv;
   delete qt;
 }
Member Function Documentation
void geos::operation::valid::QuadtreeNestedRingTester::add (const geom::LinearRing * ring)
Definition at line 64 of file QuadtreeNestedRingTester.cpp.
References geos::geom::Envelope::expandToInclude(), geos::geom::Geometry::getEnvelopeInternal(), rings, and totalEnv.
 {
   rings.push_back(ring);
   const Envelope *envi=ring->getEnvelopeInternal();
   totalEnv.expandToInclude(envi);
 }
void geos::operation::valid::QuadtreeNestedRingTester::buildQuadtree () private
Definition at line 117 of file QuadtreeNestedRingTester.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::index::quadtree::Quadtree::insert(), qt, and rings.
Referenced by isNonNested().
 {
   qt=new Quadtree();
   for(size_t i=0, n=rings.size(); i<n; ++i)
   {
     const LinearRing *ring=rings[i];
     const Envelope *env=ring->getEnvelopeInternal();
     qt->insert(env, (void*)ring);
   }
 }
Coordinate * geos::operation::valid::QuadtreeNestedRingTester::getNestedPoint ()
Definition at line 58 of file QuadtreeNestedRingTester.cpp.
References nestedPt.
 {
   return nestedPt;
 }
bool geos::operation::valid::QuadtreeNestedRingTester::isNonNested ()
Definition at line 72 of file QuadtreeNestedRingTester.cpp.
References buildQuadtree(), geos::operation::valid::IsValidOp::findPtNotNode(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Geometry::getEnvelopeInternal(), graph, geos::geom::Envelope::intersects(), nestedPt, qt, geos::index::quadtree::Quadtree::query(), and rings.
 {
   buildQuadtree();
   for(size_t i=0, ni=rings.size(); i<ni; ++i)
   {
     const LinearRing *innerRing=rings[i];
     const CoordinateSequence *innerRingPts=innerRing->getCoordinatesRO();
     const Envelope *envi=innerRing->getEnvelopeInternal();
     vector<void*> results;
     qt->query(envi, results);
     for(size_t j=0, nj=results.size(); j<nj; ++j)
     {
       LinearRing *searchRing=(LinearRing*)results[j];
       const CoordinateSequence *searchRingPts=searchRing->getCoordinatesRO();
       if (innerRing==searchRing) continue;
       const Envelope *e1=innerRing->getEnvelopeInternal();
       const Envelope *e2=searchRing->getEnvelopeInternal();
       if (!e1->intersects(e2)) continue;
       const Coordinate *innerRingPt=IsValidOp::findPtNotNode(innerRingPts,
           searchRing, graph);
       // Unable to find a ring point not a node of the search ring
       assert(innerRingPt!=nullptr);
       bool isInside=CGAlgorithms::isPointInRing(*innerRingPt,searchRingPts);
       if (isInside) {
         /*
          * innerRingPt is const just because the input
          * CoordinateSequence is const. If the input
          * Polygon survives lifetime of this object
          * we are safe.
          */
         nestedPt=const_cast<Coordinate *>(innerRingPt);
         return false;
       }
     }
   }
   return true;
 }
Member Data Documentation
geomgraph::GeometryGraph* geos::operation::valid::QuadtreeNestedRingTester::graph private
Definition at line 82 of file QuadtreeNestedRingTester.h.
Referenced by isNonNested().
geom::Coordinate* geos::operation::valid::QuadtreeNestedRingTester::nestedPt private
Definition at line 90 of file QuadtreeNestedRingTester.h.
Referenced by getNestedPoint(), and isNonNested().
index::quadtree::Quadtree* geos::operation::valid::QuadtreeNestedRingTester::qt private
Definition at line 88 of file QuadtreeNestedRingTester.h.
Referenced by buildQuadtree(), isNonNested(), and ~QuadtreeNestedRingTester().
std::vector<const geom::LinearRing*> geos::operation::valid::QuadtreeNestedRingTester::rings private
Definition at line 84 of file QuadtreeNestedRingTester.h.
Referenced by add(), buildQuadtree(), and isNonNested().
geom::Envelope geos::operation::valid::QuadtreeNestedRingTester::totalEnv private
Definition at line 86 of file QuadtreeNestedRingTester.h.
Referenced by add().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/valid/QuadtreeNestedRingTester.h
/home/vicky/potree/geos/vicky/src/operation/valid/QuadtreeNestedRingTester.cpp