GEOS: geos::operation::valid::TopologyValidationError Class Reference
geos::operation::valid::TopologyValidationError Class Reference
Contains information about the nature and location of a Geometry validation error.
#include <TopologyValidationError.h>
Public Types
enum errorEnum {
eError, eRepeatedPoint, eHoleOutsideShell, eNestedHoles,
eDisconnectedInterior, eSelfIntersection, eRingSelfIntersection, eNestedShells,
eDuplicatedRings, eTooFewPoints, eInvalidCoordinate, eRingNotClosed
}
Public Member Functions
TopologyValidationError (int newErrorType, const geom::Coordinate &newPt)
TopologyValidationError (int newErrorType)
geom::Coordinate & getCoordinate ()
std::string getMessage ()
int getErrorType ()
std::string toString ()
Private Attributes
int errorType
geom::Coordinate pt
Static Private Attributes
static const char * errMsg []
Detailed Description
Contains information about the nature and location of a Geometry validation error.
Definition at line 40 of file TopologyValidationError.h.
Member Enumeration Documentation
enum geos::operation::valid::TopologyValidationError::errorEnum
Enumerator
eError
eRepeatedPoint
eHoleOutsideShell
eNestedHoles
eDisconnectedInterior
eSelfIntersection
eRingSelfIntersection
eNestedShells
eDuplicatedRings
eTooFewPoints
eInvalidCoordinate
eRingNotClosed
Definition at line 43 of file TopologyValidationError.h.
                  {
     eError,
     eRepeatedPoint,
     eHoleOutsideShell,
     eNestedHoles,
     eDisconnectedInterior,
     eSelfIntersection,
     eRingSelfIntersection,
     eNestedShells,
     eDuplicatedRings,
     eTooFewPoints,
     eInvalidCoordinate,
     eRingNotClosed
   };
Constructor & Destructor Documentation
geos::operation::valid::TopologyValidationError::TopologyValidationError (int newErrorType, const geom::Coordinate & newPt)
Definition at line 47 of file TopologyValidationError.cpp.
   :
   errorType(newErrorType),
   pt(newPt)
 {
 }
geos::operation::valid::TopologyValidationError::TopologyValidationError (int newErrorType)
Definition at line 55 of file TopologyValidationError.cpp.
   :
   errorType(newErrorType),
   pt(Coordinate::getNull())
 {
 }
Member Function Documentation
Coordinate & geos::operation::valid::TopologyValidationError::getCoordinate ()
Definition at line 69 of file TopologyValidationError.cpp.
References pt.
 {
   return pt;
 }
int geos::operation::valid::TopologyValidationError::getErrorType ()
Definition at line 63 of file TopologyValidationError.cpp.
References errorType.
Referenced by geos::geom::fix_self_intersections().
 {
   return errorType;
 }
string geos::operation::valid::TopologyValidationError::getMessage ()
Definition at line 75 of file TopologyValidationError.cpp.
References errMsg, and errorType.
Referenced by toString().
 {
   return string(errMsg[errorType]);
 }
string geos::operation::valid::TopologyValidationError::toString (void)
Definition at line 81 of file TopologyValidationError.cpp.
References getMessage(), pt, and geos::geom::Coordinate::toString().
Referenced by geos::geom::check_valid().
 {
   return getMessage().append(" at or near point ").append(pt.toString());
 }
Member Data Documentation
const char * geos::operation::valid::TopologyValidationError::errMsg static private
Initial value:
={
  "Topology Validation Error",
  "Repeated Point",
  "Hole lies outside shell",
  "Holes are nested",
  "Interior is disconnected",
  "Self-intersection",
  "Ring Self-intersection",
  "Nested shells",
  "Duplicate Rings",
  "Too few points in geometry component",
  "Invalid Coordinate",
  "Ring is not closed"
}
Definition at line 67 of file TopologyValidationError.h.
Referenced by getMessage().
int geos::operation::valid::TopologyValidationError::errorType private
Definition at line 68 of file TopologyValidationError.h.
Referenced by getErrorType(), and getMessage().
geom::Coordinate geos::operation::valid::TopologyValidationError::pt private
Definition at line 69 of file TopologyValidationError.h.
Referenced by getCoordinate(), and toString().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/valid/TopologyValidationError.h
/home/vicky/potree/geos/vicky/src/operation/valid/TopologyValidationError.cpp