GEOS: geos::algorithm::InteriorPointArea Class Reference
geos::algorithm::InteriorPointArea Class Reference
Computes a point in the interior of an areal geometry.
#include <InteriorPointArea.h>
Public Member Functions
InteriorPointArea (const geom::Geometry *g)
~InteriorPointArea ()
bool getInteriorPoint (geom::Coordinate &ret) const
Private Member Functions
void add (const geom::Geometry *geom)
const geom::Geometry * widestGeometry (const geom::Geometry *geometry)
const geom::Geometry * widestGeometry (const geom::GeometryCollection *gc)
geom::LineString * horizontalBisector (const geom::Geometry *geometry)
void addPolygon (const geom::Geometry *geometry)
Finds an interior point of a Polygon.
Private Attributes
bool foundInterior
const geom::GeometryFactory * factory
geom::Coordinate interiorPoint
double maxWidth
Detailed Description
Computes a point in the interior of an areal geometry.
Algorithm
Find a Y value which is close to the centre of the geometry's vertical extent but is different to any of it's Y ordinates.
Create a horizontal bisector line using the Y value and the geometry's horizontal extent
Find the intersection between the geometry and the horizontal bisector line. The intersection is a collection of lines and points.
Pick the midpoint of the largest intersection geometry
Note: If a fixed precision model is used, in some cases this method may return a point which does not lie in the interior.
Definition at line 63 of file InteriorPointArea.h.
Constructor & Destructor Documentation
geos::algorithm::InteriorPointArea::InteriorPointArea (const geom::Geometry * g)
Creates a new interior point finder for an areal geometry.
Parameters
g an areal geometry
Definition at line 119 of file InteriorPointArea.cpp.
References geos::geom::Geometry::getFactory().
 {
   foundInterior=false;
   maxWidth=0.0;
   factory=g->getFactory();
   add(g);
 }
geos::algorithm::InteriorPointArea::~InteriorPointArea ()
Definition at line 128 of file InteriorPointArea.cpp.
 {
 }
Member Function Documentation
void geos::algorithm::InteriorPointArea::add (const geom::Geometry * geom) private
Definition at line 144 of file InteriorPointArea.cpp.
References geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   const Polygon *poly = dynamic_cast<const Polygon*>(geom);
   if ( poly ) {
     addPolygon(geom);
     return;
   }
   const GeometryCollection *gc = dynamic_cast<const GeometryCollection*>(geom);
   if ( gc )
   {
         for(std::size_t i=0, n=gc->getNumGeometries(); i<n; i++) {
       add(gc->getGeometryN(i));
     }
   }
 }
void geos::algorithm::InteriorPointArea::addPolygon (const geom::Geometry * geometry) private
Finds an interior point of a Polygon.
Parameters
geometry the geometry to analyze
Returns
the midpoint of the largest intersection between the geometry and a line halfway down its envelope
Definition at line 163 of file InteriorPointArea.cpp.
References geos::geom::Envelope::getWidth(), and geos::geom::Geometry::isEmpty().
 {
   if (geometry->isEmpty()) return;
   Coordinate intPt;
   double width;
   unique_ptr<LineString> bisector ( horizontalBisector(geometry) );
   if ( bisector->getLength() == 0.0 ) {
     width = 0;
     intPt = bisector->getCoordinateN(0);
   }
   else {
     unique_ptr<Geometry> intersections ( bisector->intersection(geometry) );
     const Geometry *widestIntersection = widestGeometry(intersections.get());
     const Envelope *env = widestIntersection->getEnvelopeInternal();
     width=env->getWidth();
     env->centre(intPt);
   }
   if (!foundInterior || width>maxWidth) {
     interiorPoint = intPt;
     maxWidth = width;
     foundInterior=true;
   }
 }
bool geos::algorithm::InteriorPointArea::getInteriorPoint (geom::Coordinate & ret) const
Gets the computed interior point.
Returns
the coordinate of an interior point
Definition at line 134 of file InteriorPointArea.cpp.
Referenced by geos::geom::Geometry::getInteriorPoint().
 {
   if ( ! foundInterior ) return false;
   ret=interiorPoint;
   return true;
 }
LineString * geos::algorithm::InteriorPointArea::horizontalBisector (const geom::Geometry * geometry) private
Original algorithm. Fails when geometry contains a horizontal segment at the Y midpoint.
Definition at line 223 of file InteriorPointArea.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::getMaxX(), and geos::geom::Envelope::getMinX().
 {
   const Envelope *envelope=geometry->getEnvelopeInternal();
   // Assert: for areas, minx <> maxx
   //double avgY=avg(envelope->getMinY(),envelope->getMaxY());
   double bisectY = SafeBisectorFinder::getBisectorY(*dynamic_cast<const Polygon *>(geometry));
   vector<Coordinate>*cv=new vector<Coordinate>(2);
   (*cv)[0].x = envelope->getMinX();
   (*cv)[0].y = bisectY;
   (*cv)[1].x = envelope->getMaxX();
   (*cv)[1].y = bisectY;
   CoordinateSequence *cl = factory->getCoordinateSequenceFactory()->create(cv);
   LineString *ret = factory->createLineString(cl);
   return ret;
 }
const Geometry * geos::algorithm::InteriorPointArea::widestGeometry (const geom::Geometry * geometry) private
Definition at line 192 of file InteriorPointArea.cpp.
 {
   const GeometryCollection *gc = dynamic_cast<const GeometryCollection*>(geometry);
   if ( gc ) {
     return widestGeometry(gc);
   } else {
     return geometry;
   }
 }
const Geometry * geos::algorithm::InteriorPointArea::widestGeometry (const geom::GeometryCollection * gc) private
Definition at line 203 of file InteriorPointArea.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), and geos::geom::GeometryCollection::isEmpty().
{
   if (gc->isEmpty()) {
     return gc;
   }
   const Geometry* widestGeometry=gc->getGeometryN(0);
   // scan remaining geom components to see if any are wider
   for(std::size_t i=1, n=gc->getNumGeometries(); i<n; i++) // start at 1
   {
     const Envelope *env1(gc->getGeometryN(i)->getEnvelopeInternal());
     const Envelope *env2(widestGeometry->getEnvelopeInternal());
     if (env1->getWidth()>env2->getWidth()) {
         widestGeometry=gc->getGeometryN(i);
     }
   }
   return widestGeometry;
 }
Member Data Documentation
const geom::GeometryFactory* geos::algorithm::InteriorPointArea::factory private
Definition at line 69 of file InteriorPointArea.h.
bool geos::algorithm::InteriorPointArea::foundInterior private
Definition at line 67 of file InteriorPointArea.h.
geom::Coordinate geos::algorithm::InteriorPointArea::interiorPoint private
Definition at line 71 of file InteriorPointArea.h.
double geos::algorithm::InteriorPointArea::maxWidth private
Definition at line 73 of file InteriorPointArea.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/InteriorPointArea.h
/home/vicky/potree/geos/vicky/src/algorithm/InteriorPointArea.cpp