GEOS: geos::index::sweepline::SweepLineEvent Class Reference
geos::index::sweepline::SweepLineEvent Class Reference
#include <SweepLineEvent.h>
Public Types
enum { INSERT_EVENT = 1, DELETE_EVENT }
Public Member Functions
SweepLineEvent (double x, SweepLineEvent *newInsertEvent, SweepLineInterval *newSweepInt)
bool isInsert ()
bool isDelete ()
SweepLineEvent * getInsertEvent ()
int getDeleteEventIndex ()
void setDeleteEventIndex (int newDeleteEventIndex)
SweepLineInterval * getInterval ()
int compareTo (const SweepLineEvent *pe) const
Private Attributes
double xValue
int eventType
SweepLineEvent * insertEvent
null if this is an INSERT_EVENT event
int deleteEventIndex
SweepLineInterval * sweepInt
Detailed Description
Definition at line 33 of file SweepLineEvent.h.
Member Enumeration Documentation
anonymous enum
Enumerator
INSERT_EVENT
DELETE_EVENT
Definition at line 37 of file SweepLineEvent.h.
        {
     INSERT_EVENT = 1,
     DELETE_EVENT
   };
Constructor & Destructor Documentation
geos::index::sweepline::SweepLineEvent::SweepLineEvent (double x, SweepLineEvent * newInsertEvent, SweepLineInterval * newSweepInt)
Definition at line 22 of file SweepLineEvent.cpp.
References DELETE_EVENT, eventType, and insertEvent.
   :
   xValue(x),
   eventType(SweepLineEvent::INSERT_EVENT),
   insertEvent(newInsertEvent),
   sweepInt(newSweepInt)
 {
   if (insertEvent!=nullptr)
     eventType=SweepLineEvent::DELETE_EVENT;
 }
Member Function Documentation
int geos::index::sweepline::SweepLineEvent::compareTo (const SweepLineEvent * pe) const
ProjectionEvents are ordered first by their x-value, and then by their eventType. It is important that Insert events are sorted before Delete events, so that items whose Insert and Delete events occur at the same x-value will be correctly handled.
Definition at line 71 of file SweepLineEvent.cpp.
References eventType, and xValue.
Referenced by geos::index::sweepline::SweepLineEventLessThen::operator()().
 {
   if (xValue<pe->xValue) return -1;
   if (xValue>pe->xValue) return 1;
   if (eventType<pe->eventType) return -1;
   if (eventType>pe->eventType) return 1;
   return 0;
 }
int geos::index::sweepline::SweepLineEvent::getDeleteEventIndex ()
Definition at line 53 of file SweepLineEvent.cpp.
References deleteEventIndex.
Referenced by geos::index::sweepline::SweepLineIndex::computeOverlaps().
 {
   return deleteEventIndex;
 }
SweepLineEvent * geos::index::sweepline::SweepLineEvent::getInsertEvent ()
Definition at line 47 of file SweepLineEvent.cpp.
References insertEvent.
Referenced by geos::index::sweepline::SweepLineIndex::buildIndex().
 {
   return insertEvent;
 }
SweepLineInterval * geos::index::sweepline::SweepLineEvent::getInterval ()
Definition at line 65 of file SweepLineEvent.cpp.
References sweepInt.
Referenced by geos::index::sweepline::SweepLineIndex::computeOverlaps(), and geos::index::sweepline::SweepLineIndex::processOverlaps().
 {
   return sweepInt;
 }
bool geos::index::sweepline::SweepLineEvent::isDelete ()
Definition at line 41 of file SweepLineEvent.cpp.
References insertEvent.
Referenced by geos::index::sweepline::SweepLineIndex::buildIndex().
 {
   return insertEvent!=nullptr;
 }
bool geos::index::sweepline::SweepLineEvent::isInsert ()
Definition at line 35 of file SweepLineEvent.cpp.
References insertEvent.
Referenced by geos::index::sweepline::SweepLineIndex::computeOverlaps(), and geos::index::sweepline::SweepLineIndex::processOverlaps().
 {
   return insertEvent==nullptr;
 }
void geos::index::sweepline::SweepLineEvent::setDeleteEventIndex (int newDeleteEventIndex)
Definition at line 59 of file SweepLineEvent.cpp.
References deleteEventIndex.
Referenced by geos::index::sweepline::SweepLineIndex::buildIndex().
 {
   deleteEventIndex=newDeleteEventIndex;
 }
Member Data Documentation
int geos::index::sweepline::SweepLineEvent::deleteEventIndex private
Definition at line 76 of file SweepLineEvent.h.
Referenced by getDeleteEventIndex(), and setDeleteEventIndex().
int geos::index::sweepline::SweepLineEvent::eventType private
Definition at line 71 of file SweepLineEvent.h.
Referenced by compareTo(), and SweepLineEvent().
SweepLineEvent* geos::index::sweepline::SweepLineEvent::insertEvent private
null if this is an INSERT_EVENT event
Definition at line 74 of file SweepLineEvent.h.
Referenced by getInsertEvent(), isDelete(), isInsert(), and SweepLineEvent().
SweepLineInterval* geos::index::sweepline::SweepLineEvent::sweepInt private
Definition at line 78 of file SweepLineEvent.h.
Referenced by getInterval().
double geos::index::sweepline::SweepLineEvent::xValue private
Definition at line 69 of file SweepLineEvent.h.
Referenced by compareTo().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/sweepline/SweepLineEvent.h
/home/vicky/potree/geos/vicky/src/index/sweepline/SweepLineEvent.cpp