GEOS: geos::linearref::LinearLocation Class Reference
geos::linearref::LinearLocation Class Reference
Represents a location along a LineString or MultiLineString.
#include <LinearLocation.h>
Public Member Functions
LinearLocation (unsigned int segmentIndex=0, double segmentFraction=0.0)
LinearLocation (unsigned int componentIndex, unsigned int segmentIndex, double segmentFraction)
void clamp (const geom::Geometry *linear)
void snapToVertex (const geom::Geometry *linearGeom, double minDistance)
double getSegmentLength (const geom::Geometry *linearGeom) const
void setToEnd (const geom::Geometry *linear)
unsigned int getComponentIndex () const
unsigned int getSegmentIndex () const
double getSegmentFraction () const
bool isVertex () const
geom::Coordinate getCoordinate (const geom::Geometry *linearGeom) const
std::unique_ptr< geom::LineSegment > getSegment (const geom::Geometry *linearGeom) const
bool isValid (const geom::Geometry *linearGeom) const
int compareTo (const LinearLocation &other) const
int compareLocationValues (unsigned int componentIndex1, unsigned int segmentIndex1, double segmentFraction1) const
bool isOnSameSegment (const LinearLocation &loc) const
bool isEndpoint (const geom::Geometry &linearGeom) const
Tests whether this location is an endpoint of the linear component it refers to.
Static Public Member Functions
static LinearLocation getEndLocation (const geom::Geometry *linear)
static geom::Coordinate pointAlongSegmentByFraction (const geom::Coordinate &p0, const geom::Coordinate &p1, double frac)
static int compareLocationValues (unsigned int componentIndex0, unsigned int segmentIndex0, double segmentFraction0, unsigned int componentIndex1, unsigned int segmentIndex1, double segmentFraction1)
Private Member Functions
void normalize ()
Private Attributes
unsigned int componentIndex
unsigned int segmentIndex
double segmentFraction
Friends
std::ostream & operator<< (std::ostream &out, const LinearLocation &obj)
Detailed Description
Represents a location along a LineString or MultiLineString.
The referenced geometry is not maintained within this location, but must be provided for operations which require it. Various methods are provided to manipulate the location value and query the geometry it references.
Definition at line 43 of file LinearLocation.h.
Constructor & Destructor Documentation
geos::linearref::LinearLocation::LinearLocation (unsigned int segmentIndex = 0, double segmentFraction = 0.0)
Creates a location referring to the start of a linear geometry
Definition at line 59 of file LinearLocation.cpp.
   :
   componentIndex(0),
   segmentIndex(segmentIndex),
   segmentFraction(segmentFraction)
 {}
geos::linearref::LinearLocation::LinearLocation (unsigned int componentIndex, unsigned int segmentIndex, double segmentFraction)
Definition at line 69 of file LinearLocation.cpp.
References normalize().
   :
   componentIndex(componentIndex),
   segmentIndex(segmentIndex),
   segmentFraction(segmentFraction)
 {
   normalize();
 }
Member Function Documentation
void geos::linearref::LinearLocation::clamp (const geom::Geometry * linear)
Ensures the indexes are valid for a given linear Geometry.
Parameters
linear a linear geometry
Definition at line 101 of file LinearLocation.cpp.
References componentIndex, geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getNumGeometries(), geos::geom::LineString::getNumPoints(), geos::geom::Geometry::getNumPoints(), segmentFraction, segmentIndex, and setToEnd().
Referenced by geos::linearref::LocationIndexedLine::clampIndex().
 {
   if (componentIndex >= linear->getNumGeometries())
   {
     setToEnd(linear);
     return;
   }
   if (segmentIndex >= linear->getNumPoints())
   {
     const LineString* line = dynamic_cast<const LineString*> (linear->getGeometryN(componentIndex));
     segmentIndex = static_cast<unsigned int>(line->getNumPoints() - 1);
     segmentFraction = 1.0;
   }
 }
int geos::linearref::LinearLocation::compareLocationValues (unsigned int componentIndex1, unsigned int segmentIndex1, double segmentFraction1) const
Compares this object with the specified index values for order.
Parameters
componentIndex1 a component index
segmentIndex1 a segment index
segmentFraction1 a segment fraction
Returns
a negative integer, zero, or a positive integer as this LineStringLocation is less than, equal to, or greater than the specified locationValues
Definition at line 257 of file LinearLocation.cpp.
References componentIndex, segmentFraction, and segmentIndex.
Referenced by geos::linearref::ExtractLineByLocation::computeLinear(), and geos::linearref::LocationIndexOfPoint::indexOfFromStart().
 {
   // compare component indices
   if (componentIndex < componentIndex1) return -1;
   if (componentIndex > componentIndex1) return 1;
   // compare segments
   if (segmentIndex < segmentIndex1) return -1;
   if (segmentIndex > segmentIndex1) return 1;
   // same segment, so compare segment fraction
   if (segmentFraction < segmentFraction1) return -1;
   if (segmentFraction > segmentFraction1) return 1;
   // same location
   return 0;
 }
int geos::linearref::LinearLocation::compareLocationValues (unsigned int componentIndex0, unsigned int segmentIndex0, double segmentFraction0, unsigned int componentIndex1, unsigned int segmentIndex1, double segmentFraction1) static
Compares two sets of location values for order.
Parameters
componentIndex0 a component index
segmentIndex0 a segment index
segmentFraction0 a segment fraction
componentIndex1 another component index
segmentIndex1 another segment index
segmentFraction1 another segment fraction
Returns
a negative integer, zero, or a positive integer as the first set of location values is less than, equal to, or greater than the second set of locationValues
Definition at line 276 of file LinearLocation.cpp.
 {
   // compare component indices
   if (componentIndex0 < componentIndex1) return -1;
   if (componentIndex0 > componentIndex1) return 1;
   // compare segments
   if (segmentIndex0 < segmentIndex1) return -1;
   if (segmentIndex0 > segmentIndex1) return 1;
   // same segment, so compare segment fraction
   if (segmentFraction0 < segmentFraction1) return -1;
   if (segmentFraction0 > segmentFraction1) return 1;
   // same location
   return 0;
 }
int geos::linearref::LinearLocation::compareTo (const LinearLocation & other) const
Compares this object with the specified object for order.
Parameters
o the LineStringLocation with which this Coordinate is being compared
Returns
a negative integer, zero, or a positive integer as this LineStringLocation is less than, equal to, or greater than the specified LineStringLocation
Definition at line 240 of file LinearLocation.cpp.
References componentIndex, segmentFraction, and segmentIndex.
Referenced by geos::linearref::ExtractLineByLocation::extract(), geos::linearref::LocationIndexOfPoint::indexOfAfter(), and geos::operation::sharedpaths::SharedPathsOp::isForward().
 {
   // compare component indices
   if (componentIndex < other.componentIndex) return -1;
   if (componentIndex > other.componentIndex) return 1;
   // compare segments
   if (segmentIndex < other.segmentIndex) return -1;
   if (segmentIndex > other.segmentIndex) return 1;
   // same segment, so compare segment fraction
   if (segmentFraction < other.segmentFraction) return -1;
   if (segmentFraction > other.segmentFraction) return 1;
   // same location
   return 0;
 }
unsigned int geos::linearref::LinearLocation::getComponentIndex () const
Gets the component index for this location.
Returns
the component index
Definition at line 163 of file LinearLocation.cpp.
References componentIndex.
Referenced by geos::linearref::LengthLocationMap::getLength(), and geos::linearref::LengthLocationMap::resolveHigher().
 {
   return componentIndex;
 }
Coordinate geos::linearref::LinearLocation::getCoordinate (const geom::Geometry * linearGeom) const
Gets the Coordinate along the given linear Geometry which is referenced by this location.
Parameters
linearGeom the linear geometry referenced by this location
Returns
the Coordinate at the location
Definition at line 191 of file LinearLocation.cpp.
References componentIndex, geos::geom::LineString::getCoordinateN(), geos::geom::Geometry::getGeometryN(), geos::geom::LineString::getNumPoints(), pointAlongSegmentByFraction(), segmentFraction, and segmentIndex.
Referenced by geos::linearref::ExtractLineByLocation::computeLine(), geos::linearref::ExtractLineByLocation::computeLinear(), geos::linearref::LengthIndexedLine::extractPoint(), and geos::linearref::LocationIndexedLine::extractPoint().
 {
   const LineString* lineComp = dynamic_cast<const LineString *> (linearGeom->getGeometryN(componentIndex));
   if ( ! lineComp ) {
     throw util::IllegalArgumentException("LinearLocation::getCoordinate only works with LineString geometries");
   }
   Coordinate p0 = lineComp->getCoordinateN(segmentIndex);
   if (segmentIndex >= lineComp->getNumPoints() - 1)
     return p0;
   Coordinate p1 = lineComp->getCoordinateN(segmentIndex + 1);
   return pointAlongSegmentByFraction(p0, p1, segmentFraction);
 }
LinearLocation geos::linearref::LinearLocation::getEndLocation (const geom::Geometry * linear) static
Gets a location which refers to the end of a linear Geometry.
Parameters
linear the linear geometry
Returns
a new LinearLocation
Definition at line 36 of file LinearLocation.cpp.
References setToEnd().
Referenced by geos::linearref::LocationIndexedLine::getEndIndex(), geos::linearref::LengthLocationMap::getLocationForward(), and geos::linearref::LocationIndexOfPoint::indexOfAfter().
 {
   // assert: linear is LineString or MultiLineString
   LinearLocation loc;
   loc.setToEnd(linear);
   return loc;
 }
std::unique_ptr< LineSegment > geos::linearref::LinearLocation::getSegment (const geom::Geometry * linearGeom) const
Gets a LineSegment representing the segment of the given linear Geometry which contains this location.
Parameters
linearGeom a linear geometry
Returns
the LineSegment containing the location
Definition at line 206 of file LinearLocation.cpp.
References componentIndex, geos::geom::LineString::getCoordinateN(), geos::geom::Geometry::getGeometryN(), geos::geom::LineString::getNumPoints(), and segmentIndex.
Referenced by geos::linearref::LengthIndexedLine::extractPoint(), and geos::linearref::LocationIndexedLine::extractPoint().
 {
   const LineString* lineComp = dynamic_cast<const LineString *> (linearGeom->getGeometryN(componentIndex));
   Coordinate p0 = lineComp->getCoordinateN(segmentIndex);
   // check for endpoint - return last segment of the line if so
   if (segmentIndex >= lineComp->getNumPoints() - 1)
   {
     Coordinate prev = lineComp->getCoordinateN(static_cast<int>(lineComp->getNumPoints() - 2));
     return std::unique_ptr<LineSegment>(new LineSegment(prev, p0));
   }
   Coordinate p1 = lineComp->getCoordinateN(segmentIndex + 1);
   return std::unique_ptr<LineSegment>(new LineSegment(p0, p1));
 }
double geos::linearref::LinearLocation::getSegmentFraction () const
Gets the segment fraction for this location
Returns
the segment fraction
Definition at line 177 of file LinearLocation.cpp.
References segmentFraction.
Referenced by geos::linearref::ExtractLineByLocation::computeLine(), geos::linearref::LengthIndexedLine::extractPoint(), geos::linearref::LocationIndexedLine::extractPoint(), geos::linearref::LengthLocationMap::getLength(), and geos::linearref::LinearIterator::segmentEndVertexIndex().
 {
   return segmentFraction;
 }
unsigned int geos::linearref::LinearLocation::getSegmentIndex () const
Gets the segment index for this location
Returns
the segment index
Definition at line 170 of file LinearLocation.cpp.
References segmentIndex.
Referenced by geos::linearref::ExtractLineByLocation::computeLine(), geos::linearref::LengthLocationMap::getLength(), and geos::linearref::LinearIterator::segmentEndVertexIndex().
 {
   return segmentIndex;
 }
double geos::linearref::LinearLocation::getSegmentLength (const geom::Geometry * linearGeom) const
Gets the length of the segment in the given Geometry containing this location.
Parameters
linearGeom a linear geometry
Returns
the length of the segment
Definition at line 137 of file LinearLocation.cpp.
References componentIndex, geos::geom::Coordinate::distance(), geos::geom::LineString::getCoordinateN(), geos::geom::Geometry::getGeometryN(), geos::geom::LineString::getNumPoints(), and segmentIndex.
Referenced by snapToVertex().
 {
   const LineString* lineComp = dynamic_cast<const LineString*> (linearGeom->getGeometryN(componentIndex));
   // ensure segment index is valid
   unsigned int segIndex = segmentIndex;
   if (segmentIndex >= lineComp->getNumPoints() - 1)
     segIndex = static_cast<unsigned int>(lineComp->getNumPoints() - 2);
   Coordinate p0 = lineComp->getCoordinateN(segIndex);
   Coordinate p1 = lineComp->getCoordinateN(segIndex + 1);
   return p0.distance(p1);
 }
bool geos::linearref::LinearLocation::isEndpoint (const geom::Geometry & linearGeom) const
Tests whether this location is an endpoint of the linear component it refers to.
Parameters
linearGeom the linear geometry referenced by this location
Returns
true if the location is a component endpoint
Definition at line 313 of file LinearLocation.cpp.
References componentIndex, geos::geom::Geometry::getGeometryN(), geos::geom::LineString::getNumPoints(), segmentFraction, and segmentIndex.
Referenced by geos::linearref::LengthLocationMap::resolveHigher().
 {
   const LineString& lineComp = dynamic_cast<const LineString&>(
       *(linearGeom.getGeometryN(componentIndex)) );
   // check for endpoint
   auto nseg = lineComp.getNumPoints() - 1;
   return segmentIndex >= nseg
         || (segmentIndex == nseg && segmentFraction >= 1.0);
 }
bool geos::linearref::LinearLocation::isOnSameSegment (const LinearLocation & loc) const
Tests whether two locations are on the same segment in the parent Geometry.
Parameters
loc a location on the same geometry
Returns
true if the locations are on the same segment of the parent geometry
Definition at line 298 of file LinearLocation.cpp.
References componentIndex, segmentFraction, and segmentIndex.
 {
   if (componentIndex != loc.componentIndex) return false;
   if (segmentIndex == loc.segmentIndex) return true;
   if (loc.segmentIndex - segmentIndex == 1
       && loc.segmentFraction == 0.0)
     return true;
   if (segmentIndex - loc.segmentIndex == 1
       && segmentFraction == 0.0)
     return true;
   return false;
 }
bool geos::linearref::LinearLocation::isValid (const geom::Geometry * linearGeom) const
Tests whether this location refers to a valid location on the given linear Geometry.
Parameters
linearGeom a linear geometry
Returns
true if this location is valid
Definition at line 222 of file LinearLocation.cpp.
References componentIndex, geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getNumGeometries(), geos::geom::LineString::getNumPoints(), segmentFraction, and segmentIndex.
Referenced by geos::linearref::LocationIndexedLine::isValidIndex().
 {
   if (componentIndex >= linearGeom->getNumGeometries())
     return false;
   const LineString* lineComp = dynamic_cast<const LineString*> (linearGeom->getGeometryN(componentIndex));
   if (segmentIndex > lineComp->getNumPoints())
     return false;
   if (segmentIndex == lineComp->getNumPoints() && segmentFraction != 0.0)
     return false;
   if (segmentFraction < 0.0 || segmentFraction > 1.0)
     return false;
   return true;
 }
bool geos::linearref::LinearLocation::isVertex () const
Tests whether this location refers to a vertex
Returns
true if the location is a vertex
Definition at line 184 of file LinearLocation.cpp.
References segmentFraction.
Referenced by geos::linearref::ExtractLineByLocation::computeLine(), and geos::linearref::ExtractLineByLocation::computeLinear().
 {
   return segmentFraction <= 0.0 || segmentFraction >= 1.0;
 }
void geos::linearref::LinearLocation::normalize (void) private
Ensures the individual values are locally valid. Does not ensure that the indexes are valid for a particular linear geometry.
See also
clamp
Definition at line 81 of file LinearLocation.cpp.
References segmentFraction, and segmentIndex.
Referenced by LinearLocation().
 {
   if (segmentFraction < 0.0)
   {
     segmentFraction = 0.0;
   }
   if (segmentFraction > 1.0)
   {
     segmentFraction = 1.0;
   }
   if (segmentFraction == 1.0)
   {
     segmentFraction = 0.0;
     segmentIndex += 1;
   }
 }
Coordinate geos::linearref::LinearLocation::pointAlongSegmentByFraction (const geom::Coordinate & p0, const geom::Coordinate & p1, double frac) static
Computes the Coordinate of a point a given fraction along the line segment (p0, p1). If the fraction is greater than 1.0 the last point of the segment is returned. If the fraction is less than or equal to 0.0 the first point of the segment is returned. The Z ordinate is interpolated from the Z-ordinates of the given points, if they are specified.
Parameters
p0 the first point of the line segment
p1 the last point of the line segment
frac the length to the desired point
Returns
the Coordinate of the desired point
Definition at line 46 of file LinearLocation.cpp.
References geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
Referenced by getCoordinate().
 {
   if (frac <= 0.0) return p0;
   if (frac >= 1.0) return p1;
   double x = (p1.x - p0.x) * frac + p0.x;
   double y = (p1.y - p0.y) * frac + p0.y;
   // interpolate Z value. If either input Z is NaN, result z will be NaN as well.
   double z = (p1.z - p0.z) * frac + p0.z;
   return Coordinate(x, y, z);
 }
void geos::linearref::LinearLocation::setToEnd (const geom::Geometry * linear)
Sets the value of this location to refer the end of a linear geometry
Parameters
linear the linear geometry to set
Definition at line 153 of file LinearLocation.cpp.
References componentIndex, geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getNumGeometries(), geos::geom::LineString::getNumPoints(), segmentFraction, and segmentIndex.
Referenced by clamp(), and getEndLocation().
 {
   componentIndex = static_cast<unsigned int>(linear->getNumGeometries() - 1);
   const LineString* lastLine = dynamic_cast<const LineString*>(linear->getGeometryN(componentIndex));
   segmentIndex = static_cast<unsigned int>(lastLine->getNumPoints() - 1);
   segmentFraction = 1.0;
 }
void geos::linearref::LinearLocation::snapToVertex (const geom::Geometry * linearGeom, double minDistance)
Snaps the value of this location to the nearest vertex on the given linear Geometry, if the vertex is closer than minDistance.
Parameters
linearGeom a linear geometry
minDistance the minimum allowable distance to a vertex
Definition at line 118 of file LinearLocation.cpp.
References getSegmentLength(), and segmentFraction.
 {
   if (segmentFraction <= 0.0 || segmentFraction >= 1.0)
     return;
   double segLen = getSegmentLength(linearGeom);
   double lenToStart = segmentFraction * segLen;
   double lenToEnd = segLen - lenToStart;
   if (lenToStart <= lenToEnd && lenToStart < minDistance)
   {
     segmentFraction = 0.0;
   }
   else if (lenToEnd <= lenToStart && lenToEnd < minDistance)
   {
     segmentFraction = 1.0;
   }
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const LinearLocation & obj) friend
Member Data Documentation
unsigned int geos::linearref::LinearLocation::componentIndex private
Definition at line 46 of file LinearLocation.h.
Referenced by clamp(), compareLocationValues(), compareTo(), getComponentIndex(), getCoordinate(), getSegment(), getSegmentLength(), isEndpoint(), isOnSameSegment(), isValid(), geos::linearref::operator<<(), and setToEnd().
double geos::linearref::LinearLocation::segmentFraction private
Definition at line 48 of file LinearLocation.h.
Referenced by clamp(), compareLocationValues(), compareTo(), getCoordinate(), getSegmentFraction(), isEndpoint(), isOnSameSegment(), isValid(), isVertex(), normalize(), geos::linearref::operator<<(), setToEnd(), and snapToVertex().
unsigned int geos::linearref::LinearLocation::segmentIndex private
Definition at line 47 of file LinearLocation.h.
Referenced by clamp(), compareLocationValues(), compareTo(), getCoordinate(), getSegment(), getSegmentIndex(), getSegmentLength(), isEndpoint(), isOnSameSegment(), isValid(), normalize(), geos::linearref::operator<<(), and setToEnd().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/linearref/LinearLocation.h
/home/vicky/potree/geos/vicky/src/linearref/LinearLocation.cpp