GEOS: geos::noding::SegmentStringUtil Class Reference
geos::noding::SegmentStringUtil Class Reference
Utility methods for processing SegmentStrings.
#include <SegmentStringUtil.h>
Static Public Member Functions
static void extractSegmentStrings (const geom::Geometry *g, SegmentString::ConstVect &segStr)
Extracts all linear components from a given Geometry to SegmentStrings.
Detailed Description
Utility methods for processing SegmentStrings.
Author
Martin Davis
Definition at line 37 of file SegmentStringUtil.h.
Member Function Documentation
static void geos::noding::SegmentStringUtil::extractSegmentStrings (const geom::Geometry * g, SegmentString::ConstVect & segStr) inline static
Extracts all linear components from a given Geometry to SegmentStrings.
The SegmentString data item is set to be the source Geometry.
Parameters
geom the geometry to extract from
segStr a List of SegmentStrings (output parameter). Ownership of elements pushed to the vector is transferred to caller.
Definition at line 51 of file SegmentStringUtil.h.
References geos::geom::LineString::getCoordinates(), and geos::geom::util::LinearComponentExtracter::getLines().
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::findAndClassifyIntersections(), geos::geom::prep::PreparedLineString::getIntersectionFinder(), geos::geom::prep::PreparedPolygon::getIntersectionFinder(), geos::geom::prep::PreparedLineStringIntersects::intersects(), and geos::geom::prep::PreparedPolygonIntersects::intersects().
   {
     geom::LineString::ConstVect lines;
     geom::util::LinearComponentExtracter::getLines(*g, lines);
     for (std::size_t i=0, n=lines.size(); i<n; i++)
     {
       geom::LineString* line = (geom::LineString*)(lines[i]);
       // we take ownership of the coordinates here
       // TODO: check if this can be optimized by getting
       //       the internal CS.
       geom::CoordinateSequence* pts = line->getCoordinates();
       segStr.push_back(new NodedSegmentString(pts, g));
     }
   }
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/noding/SegmentStringUtil.h