GEOS: geos::algorithm::CentroidArea Class Reference
geos::algorithm::CentroidArea Class Reference
Computes the centroid of an area geometry.
#include <geos/geosAlgorithm.h>
Public Member Functions
CentroidArea ()
~CentroidArea ()
void add (const geom::Geometry *geom)
void add (const geom::CoordinateSequence *ring)
geom::Coordinate * getCentroid () const
bool getCentroid (geom::Coordinate &ret) const
Return false if a centroid couldn't be computed (empty polygon)
Private Member Functions
void setBasePoint (const geom::Coordinate &newbasePt)
void add (const geom::Polygon *poly)
void addShell (const geom::CoordinateSequence *pts)
void addHole (const geom::CoordinateSequence *pts)
void addTriangle (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &p2, bool isPositiveArea)
void addLinearSegments (const geom::CoordinateSequence &pts)
Static Private Member Functions
static void centroid3 (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &p3, geom::Coordinate &c)
static double area2 (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &p3)
Private Attributes
geom::Coordinate basePt
the point all triangles are based at
geom::Coordinate triangleCent3
double areasum2
Partial area sum.
geom::Coordinate cg3
partial centroid sum
geom::Coordinate centSum
double totalLength
Detailed Description
Computes the centroid of an area geometry.
Algorithm:
Based on the usual algorithm for calculating the centroid as a weighted sum of the centroids of a decomposition of the area into (possibly overlapping) triangles. The algorithm has been extended to handle holes and multi-polygons. See http://www.faqs.org/faqs/graphics/algorithms-faq/ for further details of the basic approach.
The code has also be extended to handle degenerate (zero-area) polygons. In this case, the centroid of the line segments in the polygon will be returned.
Deprecated:
use Centroid instead
Definition at line 60 of file CentroidArea.h.
Constructor & Destructor Documentation
geos::algorithm::CentroidArea::CentroidArea () inline
Definition at line 64 of file CentroidArea.h.
     :
     basePt(0.0, 0.0),
     areasum2(0.0),
     totalLength(0.0)
   {}
geos::algorithm::CentroidArea::~CentroidArea () inline
Definition at line 71 of file CentroidArea.h.
 {}
Member Function Documentation
void geos::algorithm::CentroidArea::add (const geom::Geometry * geom)
Adds the area defined by a Geometry to the centroid total. If the geometry has no area it does not contribute to the centroid.
Parameters
geom the geometry to add
Definition at line 38 of file CentroidArea.cpp.
References geos::geom::LineString::getCoordinateN(), geos::geom::Polygon::getExteriorRing(), geos::geom::Geometry::isEmpty(), and poly.
 {
   if(geom->isEmpty()) return;
   else if(const Polygon *poly=dynamic_cast<const Polygon*>(geom)) {
     setBasePoint(poly->getExteriorRing()->getCoordinateN(0));
     add(poly);
   }
   else if(const GeometryCollection *gc=dynamic_cast<const GeometryCollection*>(geom))
   {
         for(std::size_t i=0, n=gc->getNumGeometries(); i<n; ++i)
     {
       add(gc->getGeometryN(i));
     }
   }
 }
void geos::algorithm::CentroidArea::add (const geom::CoordinateSequence * ring)
Adds the area defined by an array of coordinates. The array must be a ring; i.e. end with the same coordinate as it starts with.
Parameters
ring an array of Coordinates
Definition at line 56 of file CentroidArea.cpp.
References geos::geom::CoordinateSequence::getAt().
 {
   setBasePoint(ring->getAt(0));
   addShell(ring);
 }
void geos::algorithm::CentroidArea::add (const geom::Polygon * poly) private
Definition at line 91 of file CentroidArea.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), and geos::geom::Polygon::getNumInteriorRing().
 {
   addShell(poly->getExteriorRing()->getCoordinatesRO());
   for(size_t i=0, n=poly->getNumInteriorRing(); i<n; ++i)
   {
     addHole(poly->getInteriorRingN(i)->getCoordinatesRO());
   }
 }
void geos::algorithm::CentroidArea::addHole (const geom::CoordinateSequence * pts) private
Definition at line 113 of file CentroidArea.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   bool isPositiveArea=CGAlgorithms::isCCW(pts);
   std::size_t const n=pts->getSize()-1;
   for(std::size_t i=0; i<n; ++i)
   {
     addTriangle(basePt, pts->getAt(i), pts->getAt(i+1), isPositiveArea);
   }
   addLinearSegments(*pts);
 }
void geos::algorithm::CentroidArea::addLinearSegments (const geom::CoordinateSequence & pts) private
Adds the linear segments defined by an array of coordinates to the linear centroid accumulators.
This is done in case the polygon(s) have zero-area, in which case the linear centroid is computed instead.
Parameters
pts an array of Coordinates
Definition at line 160 of file CentroidArea.cpp.
References geos::geom::CoordinateSequence::size().
 {
   std::size_t const n = pts.size()-1;
   for (std::size_t i = 0; i < n; ++i) {
     double segmentLen = pts[i].distance(pts[i + 1]);
     totalLength += segmentLen;
     double midx = (pts[i].x + pts[i + 1].x) / 2;
     centSum.x += segmentLen * midx;
     double midy = (pts[i].y + pts[i + 1].y) / 2;
     centSum.y += segmentLen * midy;
   }
 }
void geos::algorithm::CentroidArea::addShell (const geom::CoordinateSequence * pts) private
Definition at line 101 of file CentroidArea.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   bool isPositiveArea=!CGAlgorithms::isCCW(pts);
   std::size_t const n=pts->getSize()-1;
   for(std::size_t i=0; i<n; ++i)
   {
     addTriangle(basePt, pts->getAt(i), pts->getAt(i+1), isPositiveArea);
   }
   addLinearSegments(*pts);
 }
void geos::algorithm::CentroidArea::addTriangle (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & p2, bool isPositiveArea) private
Definition at line 125 of file CentroidArea.cpp.
 {
   double sign=(isPositiveArea)?1.0:-1.0;
   centroid3(p0,p1,p2,triangleCent3);
   double area2res=area2(p0,p1,p2);
   cg3.x+=sign*area2res*triangleCent3.x;
   cg3.y+=sign*area2res*triangleCent3.y;
   areasum2+=sign*area2res;
 }
double geos::algorithm::CentroidArea::area2 (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & p3) static private
Returns twice the signed area of the triangle p1-p2-p3, positive if a,b,c are oriented ccw, and negative if cw.
Definition at line 154 of file CentroidArea.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   return (p2.x-p1.x)*(p3.y-p1.y)-(p3.x-p1.x)*(p2.y-p1.y);
 }
void geos::algorithm::CentroidArea::centroid3 (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & p3, geom::Coordinate & c) static private
Returns three times the centroid of the triangle p1-p2-p3. The factor of 3 is left in to permit division to be avoided until later.
Definition at line 142 of file CentroidArea.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   c.x=p1.x+p2.x+p3.x;
   c.y=p1.y+p2.y+p3.y;
 }
Coordinate * geos::algorithm::CentroidArea::getCentroid () const
Definition at line 64 of file CentroidArea.cpp.
 {
   Coordinate *cent = new Coordinate();
   getCentroid(*cent); // or return NULL on failure !
   return cent;
 }
bool geos::algorithm::CentroidArea::getCentroid (geom::Coordinate & ret) const
Return false if a centroid couldn't be computed (empty polygon)
Definition at line 72 of file CentroidArea.cpp.
 {
   if ( areasum2 ) {
     ret = Coordinate(cg3.x/3.0/areasum2, cg3.y/3.0/areasum2);
   } else if ( totalLength ) {
     ret = Coordinate(centSum.x/totalLength, centSum.y/totalLength);
   } else {
     return false;
   }
   return true;
 }
void geos::algorithm::CentroidArea::setBasePoint (const geom::Coordinate & newbasePt) private
Definition at line 85 of file CentroidArea.cpp.
 {
   basePt=newbasePt;
 }
Member Data Documentation
double geos::algorithm::CentroidArea::areasum2 private
Partial area sum.
Definition at line 104 of file CentroidArea.h.
geom::Coordinate geos::algorithm::CentroidArea::basePt private
the point all triangles are based at
Definition at line 98 of file CentroidArea.h.
geom::Coordinate geos::algorithm::CentroidArea::centSum private
Definition at line 110 of file CentroidArea.h.
geom::Coordinate geos::algorithm::CentroidArea::cg3 private
partial centroid sum
Definition at line 107 of file CentroidArea.h.
double geos::algorithm::CentroidArea::totalLength private
Definition at line 111 of file CentroidArea.h.
geom::Coordinate geos::algorithm::CentroidArea::triangleCent3 private
Definition at line 101 of file CentroidArea.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/CentroidArea.h
/home/vicky/potree/geos/vicky/src/algorithm/CentroidArea.cpp