GEOS: geos::operation::valid::SweeplineNestedRingTester Class Reference
geos::operation::valid::SweeplineNestedRingTester Class Reference
Tests whether any of a set of LinearRings are nested inside another ring in the set, using an index::sweepline::SweepLineIndex to speed up the comparisons.
#include <SweeplineNestedRingTester.h>
Classes
class OverlapAction
Public Member Functions
SweeplineNestedRingTester (geomgraph::GeometryGraph *newGraph)
~SweeplineNestedRingTester ()
geom::Coordinate * getNestedPoint ()
void add (geom::LinearRing *ring)
bool isNonNested ()
bool isInside (geom::LinearRing *innerRing, geom::LinearRing *searchRing)
Private Member Functions
void buildIndex ()
Private Attributes
geomgraph::GeometryGraph * graph
std::vector< geom::LinearRing * > rings
index::sweepline::SweepLineIndex * sweepLine
geom::Coordinate * nestedPt
Detailed Description
Tests whether any of a set of LinearRings are nested inside another ring in the set, using an index::sweepline::SweepLineIndex to speed up the comparisons.
Definition at line 62 of file SweeplineNestedRingTester.h.
Constructor & Destructor Documentation
geos::operation::valid::SweeplineNestedRingTester::SweeplineNestedRingTester (geomgraph::GeometryGraph * newGraph) inline
Definition at line 73 of file SweeplineNestedRingTester.h.
     :
     graph(newGraph),
     rings(),
     sweepLine(new index::sweepline::SweepLineIndex()),
     nestedPt(nullptr)
   {}
geos::operation::valid::SweeplineNestedRingTester::~SweeplineNestedRingTester () inline
Definition at line 81 of file SweeplineNestedRingTester.h.
   {
     delete sweepLine;
   }
Member Function Documentation
void geos::operation::valid::SweeplineNestedRingTester::add (geom::LinearRing * ring) inline
Definition at line 94 of file SweeplineNestedRingTester.h.
{
     rings.push_back(ring);
   }
void geos::operation::valid::SweeplineNestedRingTester::buildIndex () private
Definition at line 64 of file SweeplineNestedRingTester.cpp.
References geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::getMaxX(), and geos::geom::Envelope::getMinX().
 {
   sweepLine=new SweepLineIndex();
   for(size_t i=0, n=rings.size(); i<n; i++) {
     LinearRing *ring=rings[i];
     const Envelope *env=ring->getEnvelopeInternal();
     SweepLineInterval *sweepInt=new SweepLineInterval(env->getMinX(),env->getMaxX(),ring);
     sweepLine->add(sweepInt);
   }
 }
geom::Coordinate* geos::operation::valid::SweeplineNestedRingTester::getNestedPoint () inline
Definition at line 92 of file SweeplineNestedRingTester.h.
 { return nestedPt; }
bool geos::operation::valid::SweeplineNestedRingTester::isInside (geom::LinearRing * innerRing, geom::LinearRing * searchRing)
Definition at line 76 of file SweeplineNestedRingTester.cpp.
References geos::geom::LineString::getCoordinates(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::intersects(), and geos::algorithm::CGAlgorithms::isPointInRing().
 {
   CoordinateSequence *innerRingPts=innerRing->getCoordinates();
   CoordinateSequence *searchRingPts=searchRing->getCoordinates();
   if (!innerRing->getEnvelopeInternal()->intersects(searchRing->getEnvelopeInternal()))
     return false;
   const Coordinate *innerRingPt=IsValidOp::findPtNotNode(innerRingPts, searchRing, graph);
   // Unable to find a ring point not a node of the search ring
   assert(innerRingPt!=nullptr);
   bool isInside=CGAlgorithms::isPointInRing(*innerRingPt,searchRingPts);
   if (isInside) {
     /*
      * innerRingPt is const just because the input
      * CoordinateSequence is const. If the input
      * Polygon survives lifetime of this object
      * we are safe.
      */
     nestedPt=const_cast<Coordinate *>(innerRingPt);
     return true;
   }
   return false;
 }
bool geos::operation::valid::SweeplineNestedRingTester::isNonNested ()
Definition at line 55 of file SweeplineNestedRingTester.cpp.
References geos::operation::valid::SweeplineNestedRingTester::OverlapAction::isNonNested.
 {
   buildIndex();
   OverlapAction *action=new OverlapAction(this);
   sweepLine->computeOverlaps(action);
   return action->isNonNested;
 }
Member Data Documentation
geomgraph::GeometryGraph* geos::operation::valid::SweeplineNestedRingTester::graph private
Definition at line 65 of file SweeplineNestedRingTester.h.
geom::Coordinate* geos::operation::valid::SweeplineNestedRingTester::nestedPt private
Definition at line 68 of file SweeplineNestedRingTester.h.
std::vector<geom::LinearRing*> geos::operation::valid::SweeplineNestedRingTester::rings private
Definition at line 66 of file SweeplineNestedRingTester.h.
index::sweepline::SweepLineIndex* geos::operation::valid::SweeplineNestedRingTester::sweepLine private
Definition at line 67 of file SweeplineNestedRingTester.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/valid/SweeplineNestedRingTester.h
/home/vicky/potree/geos/vicky/src/operation/valid/SweeplineNestedRingTester.cpp