GEOS: geos::geom::util::GeometryCombiner Class Reference
geos::geom::util::GeometryCombiner Class Reference
#include <GeometryCombiner.h>
Public Member Functions
GeometryCombiner (std::vector< Geometry * > const &geoms)
Geometry * combine ()
Static Public Member Functions
static Geometry * combine (std::vector< Geometry * > const &geoms)
static Geometry * combine (const Geometry *g0, const Geometry *g1)
static Geometry * combine (const Geometry *g0, const Geometry *g1, const Geometry *g2)
static GeometryFactory const * extractFactory (std::vector< Geometry * > const &geoms)
Private Member Functions
void extractElements (Geometry *geom, std::vector< Geometry * > &elems)
GeometryCombiner (const GeometryCombiner &other)=delete
GeometryCombiner & operator= (const GeometryCombiner &rhs)=delete
Private Attributes
GeometryFactory const * geomFactory
bool skipEmpty
std::vector< Geometry * > const & inputGeoms
Detailed Description
Combines Geometrys to produce a GeometryCollection of the most appropriate type. Input geometries which are already collections will have their elements extracted first. No validation of the result geometry is performed. (The only case where invalidity is possible is where Polygonal geometries are combined and result in a self-intersection).
See also
GeometryFactory::buildGeometry
Definition at line 47 of file GeometryCombiner.h.
Constructor & Destructor Documentation
geos::geom::util::GeometryCombiner::GeometryCombiner (std::vector< Geometry * > const & geoms)
Creates a new combiner for a collection of geometries
Parameters
geoms the geometries to combine
Definition at line 56 of file GeometryCombiner.cpp.
   : geomFactory(extractFactory(geoms)), skipEmpty(false), inputGeoms(geoms)
 {
 }
geos::geom::util::GeometryCombiner::GeometryCombiner (const GeometryCombiner & other) private delete
Member Function Documentation
Geometry * geos::geom::util::GeometryCombiner::combine (std::vector< Geometry * > const & geoms) static
Combines a collection of geometries.
Parameters
geoms the geometries to combine (ownership left to caller)
Returns
the combined geometry
Definition at line 28 of file GeometryCombiner.cpp.
References combine().
Referenced by combine().
 {
     GeometryCombiner combiner(geoms);
     return combiner.combine();
 }
Geometry * geos::geom::util::GeometryCombiner::combine (const Geometry * g0, const Geometry * g1) static
Combines two geometries.
Parameters
g0 a geometry to combine (ownership left to caller)
g1 a geometry to combine (ownership left to caller)
Returns
the combined geometry
Definition at line 34 of file GeometryCombiner.cpp.
References combine().
 {
     std::vector<Geometry*> geoms;
     geoms.push_back(const_cast<Geometry*>(g0));
     geoms.push_back(const_cast<Geometry*>(g1));
     GeometryCombiner combiner(geoms);
     return combiner.combine();
 }
Geometry * geos::geom::util::GeometryCombiner::combine (const Geometry * g0, const Geometry * g1, const Geometry * g2) static
Combines three geometries.
Parameters
g0 a geometry to combine (ownership left to caller)
g1 a geometry to combine (ownership left to caller)
g2 a geometry to combine (ownership left to caller)
Returns
the combined geometry
Definition at line 44 of file GeometryCombiner.cpp.
References combine().
 {
     std::vector<Geometry*> geoms;
     geoms.push_back(const_cast<Geometry*>(g0));
     geoms.push_back(const_cast<Geometry*>(g1));
     geoms.push_back(const_cast<Geometry*>(g2));
     GeometryCombiner combiner(geoms);
     return combiner.combine();
 }
Geometry * geos::geom::util::GeometryCombiner::combine ()
Computes the combination of the input geometries to produce the most appropriate Geometry or GeometryCollection
Returns
a Geometry which is the combination of the inputs
Definition at line 67 of file GeometryCombiner.cpp.
References geos::geom::GeometryFactory::buildGeometry(), geos::geom::GeometryFactory::createGeometryCollection(), extractElements(), geomFactory, and inputGeoms.
Referenced by geos::operation::geounion::CascadedUnion::unionOptimized(), geos::operation::geounion::CascadedPolygonUnion::unionOptimized(), geos::operation::geounion::CascadedUnion::unionUsingEnvelopeIntersection(), and geos::operation::geounion::CascadedPolygonUnion::unionUsingEnvelopeIntersection().
 {
     std::vector<Geometry*> elems;
     std::vector<Geometry*>::const_iterator end = inputGeoms.end();
     for (std::vector<Geometry*>::const_iterator i = inputGeoms.begin();
          i != end; ++i)
     {
         extractElements(*i, elems);
     }
     if (elems.empty()) {
         if (geomFactory != nullptr) {
             return geomFactory->createGeometryCollection(nullptr);
         }
         return nullptr;
     }
     // return the "simplest possible" geometry
     return geomFactory->buildGeometry(elems);
 }
void geos::geom::util::GeometryCombiner::extractElements (Geometry * geom, std::vector< Geometry * > & elems) private
Definition at line 90 of file GeometryCombiner.cpp.
References geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getNumGeometries(), geos::geom::Geometry::isEmpty(), and skipEmpty.
Referenced by combine().
 {
     if (geom == nullptr)
         return;
     for (std::size_t i = 0; i < geom->getNumGeometries(); ++i) {
         Geometry* elemGeom = const_cast<Geometry*>(geom->getGeometryN(i));
         if (skipEmpty && elemGeom->isEmpty())
             continue;
         elems.push_back(elemGeom);
     }
 }
GeometryFactory const * geos::geom::util::GeometryCombiner::extractFactory (std::vector< Geometry * > const & geoms) static
Extracts the GeometryFactory used by the geometries in a collection
Parameters
geoms
Returns
a GeometryFactory
Definition at line 62 of file GeometryCombiner.cpp.
 {
     return geoms.empty() ? nullptr : geoms.front()->getFactory();
 }
GeometryCombiner& geos::geom::util::GeometryCombiner::operator= (const GeometryCombiner & rhs) private delete
Member Data Documentation
GeometryFactory const* geos::geom::util::GeometryCombiner::geomFactory private
Definition at line 78 of file GeometryCombiner.h.
Referenced by combine().
std::vector<Geometry*> const& geos::geom::util::GeometryCombiner::inputGeoms private
Definition at line 80 of file GeometryCombiner.h.
Referenced by combine().
bool geos::geom::util::GeometryCombiner::skipEmpty private
Definition at line 79 of file GeometryCombiner.h.
Referenced by extractElements().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/util/GeometryCombiner.h
/home/vicky/potree/geos/vicky/src/geom/util/GeometryCombiner.cpp