GEOS: geos::geom::prep::PreparedLineString Class Reference
geos::geom::prep::PreparedLineString Class Reference
A prepared version of LinearRing, LineString or MultiLineString geometries.
#include <PreparedLineString.h>
Public Member Functions
PreparedLineString (const Geometry *geom)
~PreparedLineString () override
noding::FastSegmentSetIntersectionFinder * getIntersectionFinder ()
bool intersects (const geom::Geometry *g) const override
const geom::Geometry & getGeometry () const override
const Coordinate::ConstVect * getRepresentativePoints () const
bool isAnyTargetComponentInTest (const geom::Geometry *testGeom) const
bool contains (const geom::Geometry *g) const override
bool containsProperly (const geom::Geometry *g) const override
bool coveredBy (const geom::Geometry *g) const override
bool covers (const geom::Geometry *g) const override
bool crosses (const geom::Geometry *g) const override
bool disjoint (const geom::Geometry *g) const override
bool overlaps (const geom::Geometry *g) const override
bool touches (const geom::Geometry *g) const override
bool within (const geom::Geometry *g) const override
std::string toString ()
Protected Member Functions
void setGeometry (const geom::Geometry *geom)
bool envelopesIntersect (const geom::Geometry *g) const
bool envelopeCovers (const geom::Geometry *g) const
Private Attributes
noding::FastSegmentSetIntersectionFinder * segIntFinder
noding::SegmentString::ConstVect segStrings
Detailed Description
A prepared version of LinearRing, LineString or MultiLineString geometries.
Author
mbdavis
Definition at line 43 of file PreparedLineString.h.
Constructor & Destructor Documentation
geos::geom::prep::PreparedLineString::PreparedLineString (const Geometry * geom) inline
Definition at line 51 of file PreparedLineString.h.
     :
     BasicPreparedGeometry( geom),
     segIntFinder( nullptr)
   { }
geos::geom::prep::PreparedLineString::~PreparedLineString () override
Definition at line 33 of file PreparedLineString.cpp.
References segIntFinder, and segStrings.
 {
   delete segIntFinder;
   for ( noding::SegmentString::ConstVect::size_type i = 0,
        ni = segStrings.size(); i < ni; ++i )
   {
     delete segStrings[ i ];
   }
 }
Member Function Documentation
bool geos::geom::prep::BasicPreparedGeometry::contains (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Reimplemented in geos::geom::prep::PreparedPolygon.
Definition at line 80 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::contains().
 {
   return baseGeom->contains(g);
 }
bool geos::geom::prep::BasicPreparedGeometry::containsProperly (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Reimplemented in geos::geom::prep::PreparedPolygon.
Definition at line 86 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, geos::geom::Envelope::contains(), geos::geom::Geometry::getEnvelopeInternal(), and geos::geom::Geometry::relate().
 {
   // since raw relate is used, provide some optimizations
   // short-circuit test
   if (! baseGeom->getEnvelopeInternal()->contains(g->getEnvelopeInternal()))
   {
     return false;
   }
   // otherwise, compute using relate mask
   return baseGeom->relate(g, "T**FF*FF*");
 }
bool geos::geom::prep::BasicPreparedGeometry::coveredBy (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 101 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::coveredBy().
 {
   return baseGeom->coveredBy(g);
 }
bool geos::geom::prep::BasicPreparedGeometry::covers (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Reimplemented in geos::geom::prep::PreparedPolygon.
Definition at line 107 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::covers().
 {
   return baseGeom->covers(g);
 }
bool geos::geom::prep::BasicPreparedGeometry::crosses (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 113 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::crosses().
 {
   return baseGeom->crosses(g);
 }
bool geos::geom::prep::BasicPreparedGeometry::disjoint (const geom::Geometry * g) const override virtual inherited
Standard implementation for all geometries. Supports GeometryCollections as input.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 119 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::intersects().
 {
   return ! intersects(g);
 }
bool geos::geom::prep::BasicPreparedGeometry::envelopeCovers (const geom::Geometry * g) const protected inherited
Determines whether the envelope of this geometry covers the Geometry g.
Parameters
g a Geometry
Returns
true if g is contained in this envelope
Definition at line 47 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, geos::geom::Envelope::covers(), and geos::geom::Geometry::getEnvelopeInternal().
Referenced by geos::geom::prep::PreparedPolygon::contains(), geos::geom::prep::PreparedPolygon::containsProperly(), and geos::geom::prep::PreparedPolygon::covers().
 {
   return baseGeom->getEnvelopeInternal()->covers(g->getEnvelopeInternal());
 }
bool geos::geom::prep::BasicPreparedGeometry::envelopesIntersect (const geom::Geometry * g) const protected inherited
Determines whether a Geometry g interacts with this geometry by testing the geometry envelopes.
Parameters
g a Geometry
Returns
true if the envelopes intersect
Definition at line 41 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, geos::geom::Geometry::getEnvelopeInternal(), and geos::geom::Envelope::intersects().
Referenced by geos::geom::prep::PreparedPoint::intersects(), intersects(), and geos::geom::prep::PreparedPolygon::intersects().
 {
   return baseGeom->getEnvelopeInternal()->intersects(g->getEnvelopeInternal());
 }
const geom::Geometry& geos::geom::prep::BasicPreparedGeometry::getGeometry () const inline override virtual inherited
Gets the original Geometry which has been prepared.
Returns
the base geometry
Implements geos::geom::prep::PreparedGeometry.
Definition at line 95 of file BasicPreparedGeometry.h.
Referenced by geos::geom::prep::PreparedPolygon::contains(), geos::geom::prep::PreparedPolygonCovers::fullTopologicalPredicate(), geos::geom::prep::PreparedPolygonContains::fullTopologicalPredicate(), getIntersectionFinder(), geos::geom::prep::PreparedPolygon::getIntersectionFinder(), geos::geom::prep::PreparedPolygon::getPointLocator(), geos::geom::prep::PreparedPolygon::intersects(), geos::geom::prep::AbstractPreparedPolygonContains::isProperIntersectionImpliesNotContainedSituation(), and geos::geom::prep::PreparedPolygon::PreparedPolygon().
   {
     return *baseGeom;
   }
noding::FastSegmentSetIntersectionFinder * geos::geom::prep::PreparedLineString::getIntersectionFinder ()
Definition at line 44 of file PreparedLineString.cpp.
References geos::noding::SegmentStringUtil::extractSegmentStrings(), geos::geom::prep::BasicPreparedGeometry::getGeometry(), segIntFinder, and segStrings.
 {
   if (! segIntFinder)
   {
     noding::SegmentStringUtil::extractSegmentStrings( &getGeometry(), segStrings );
     segIntFinder = new noding::FastSegmentSetIntersectionFinder( &segStrings );
   }
   return segIntFinder;
 }
const Coordinate::ConstVect* geos::geom::prep::BasicPreparedGeometry::getRepresentativePoints () const inline inherited
Gets the list of representative points for this geometry. One vertex is included for every component of the geometry (i.e. including one for every ring of polygonal geometries)
Returns
a List of Coordinate
Definition at line 107 of file BasicPreparedGeometry.h.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), and geos::geom::prep::PreparedPolygonIntersects::intersects().
   {
     return &representativePts;
   }
bool geos::geom::prep::PreparedLineString::intersects (const geom::Geometry * g) const override virtual
Default implementation.
Reimplemented from geos::geom::prep::BasicPreparedGeometry.
Definition at line 56 of file PreparedLineString.cpp.
References geos::geom::prep::BasicPreparedGeometry::envelopesIntersect(), and geos::geom::prep::PreparedLineStringIntersects::intersects().
 {
   if (! envelopesIntersect(g))
     {
         return false;
     }
     PreparedLineString& prep = *(const_cast<PreparedLineString*>(this));
     return PreparedLineStringIntersects::intersects(prep, g);
 }
bool geos::geom::prep::BasicPreparedGeometry::isAnyTargetComponentInTest (const geom::Geometry * testGeom) const inherited
Tests whether any representative of the target geometry intersects the test geometry. This is useful in A/A, A/L, A/P, L/P, and P/P cases.
Parameters
geom the test geometry
repPts the representative points of the target geometry
Returns
true if any component intersects the areal test geometry
Definition at line 66 of file BasicPreparedGeometry.cpp.
References geos::algorithm::PointLocator::intersects(), and geos::geom::prep::BasicPreparedGeometry::representativePts.
Referenced by geos::geom::prep::PreparedPoint::intersects().
 {
   algorithm::PointLocator locator;
   for (size_t i=0, n=representativePts.size(); i<n; i++)
   {
     const geom::Coordinate& c = *(representativePts[i]);
     if ( locator.intersects( c, testGeom) )
     return true;
   }
   return false;
 }
bool geos::geom::prep::BasicPreparedGeometry::overlaps (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 131 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::overlaps().
 {
   return baseGeom->overlaps(g);
 }
void geos::geom::prep::BasicPreparedGeometry::setGeometry (const geom::Geometry * geom) protected inherited
Sets the original Geometry which will be prepared.
Definition at line 34 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), and geos::geom::prep::BasicPreparedGeometry::representativePts.
Referenced by geos::geom::prep::BasicPreparedGeometry::BasicPreparedGeometry().
 {
   baseGeom = geom;
   geom::util::ComponentCoordinateExtracter::getCoordinates(*baseGeom, representativePts);
 }
std::string geos::geom::prep::BasicPreparedGeometry::toString (void) inherited
Definition at line 149 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::toString().
 {
   return baseGeom->toString();
 }
bool geos::geom::prep::BasicPreparedGeometry::touches (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 137 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::touches().
 {
   return baseGeom->touches(g);
 }
bool geos::geom::prep::BasicPreparedGeometry::within (const geom::Geometry * g) const override virtual inherited
Default implementation.
Implements geos::geom::prep::PreparedGeometry.
Definition at line 143 of file BasicPreparedGeometry.cpp.
References geos::geom::prep::BasicPreparedGeometry::baseGeom, and geos::geom::Geometry::within().
 {
   return baseGeom->within(g);
 }
Member Data Documentation
noding::FastSegmentSetIntersectionFinder* geos::geom::prep::PreparedLineString::segIntFinder private
Definition at line 46 of file PreparedLineString.h.
Referenced by getIntersectionFinder(), and ~PreparedLineString().
noding::SegmentString::ConstVect geos::geom::prep::PreparedLineString::segStrings mutable private
Definition at line 47 of file PreparedLineString.h.
Referenced by getIntersectionFinder(), and ~PreparedLineString().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/prep/PreparedLineString.h
/home/vicky/potree/geos/vicky/src/geom/prep/PreparedLineString.cpp