GEOS: geos::geom::util::LinearComponentExtracter Class Reference
geos::geom::util::LinearComponentExtracter Class Reference
#include <LinearComponentExtracter.h>
Public Member Functions
LinearComponentExtracter (std::vector< const LineString * > &newComps)
void filter_rw (Geometry *geom) override
void filter_ro (const Geometry *geom) override
Static Public Member Functions
static void getLines (const Geometry &geom, std::vector< const LineString * > &ret)
Private Member Functions
LinearComponentExtracter (const LinearComponentExtracter &other)=delete
LinearComponentExtracter & operator= (const LinearComponentExtracter &rhs)=delete
Private Attributes
LineString::ConstVect & comps
Detailed Description
Extracts all the 1-dimensional (LineString) components from a Geometry.
Definition at line 35 of file LinearComponentExtracter.h.
Constructor & Destructor Documentation
geos::geom::util::LinearComponentExtracter::LinearComponentExtracter (const LinearComponentExtracter & other) private delete
geos::geom::util::LinearComponentExtracter::LinearComponentExtracter (std::vector< const LineString * > & newComps)
Constructs a LinearComponentExtracterFilter with a list in which to store LineStrings found.
Definition at line 26 of file LinearComponentExtracter.cpp.
             :
          comps(newComps)
          {}
Member Function Documentation
void geos::geom::util::LinearComponentExtracter::filter_ro (const Geometry * geom) override virtual
Reimplemented from geos::geom::GeometryComponentFilter.
Definition at line 43 of file LinearComponentExtracter.cpp.
References comps.
          {
             if ( const LineString *ls=dynamic_cast<const LineString *>(geom) )
                comps.push_back(ls);
          }
void geos::geom::util::LinearComponentExtracter::filter_rw (Geometry * geom) override virtual
Performs an operation with or on geom.
Parameters
geom a Geometry to which the filter is applied.
Reimplemented from geos::geom::GeometryComponentFilter.
Definition at line 37 of file LinearComponentExtracter.cpp.
References comps.
          {
             if ( const LineString *ls=dynamic_cast<const LineString *>(geom) )
                comps.push_back(ls);
          }
void geos::geom::util::LinearComponentExtracter::getLines (const Geometry & geom, std::vector< const LineString * > & ret) static
Push the linear components from a single geometry into the provided vector. If more than one geometry is to be processed, it is more efficient to create a single LinearComponentExtracterFilter instance and pass it to multiple geometries.
Definition at line 31 of file LinearComponentExtracter.cpp.
References geos::geom::Geometry::apply_ro().
Referenced by geos::noding::SegmentStringUtil::extractSegmentStrings(), geos::operation::overlay::validate::OffsetPointGenerator::getPoints(), and geos::algorithm::locate::IndexedPointInAreaLocator::IntervalIndexedGeometry::init().
          {
             LinearComponentExtracter lce(ret);
             geom.apply_ro(&lce);
          }
LinearComponentExtracter& geos::geom::util::LinearComponentExtracter::operator= (const LinearComponentExtracter & rhs) private delete
Member Data Documentation
LineString::ConstVect& geos::geom::util::LinearComponentExtracter::comps private
Definition at line 39 of file LinearComponentExtracter.h.
Referenced by filter_ro(), and filter_rw().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/util/LinearComponentExtracter.h
/home/vicky/potree/geos/vicky/src/geom/util/LinearComponentExtracter.cpp