GEOS: geos::index::bintree::Node Class Reference
geos::index::bintree::Node Class Reference
A node of a Bintree.
#include <Node.h>
Public Member Functions
Node (Interval *newInterval, int newLevel)
~Node () override
Interval * getInterval ()
Node * getNode (Interval *searchInterval)
NodeBase * find (Interval *searchInterval)
void insert (Node *node)
virtual std::vector< void * > * getItems ()
virtual void add (void *item)
virtual std::vector< void * > * addAllItems (std::vector< void * > *newItems)
virtual std::vector< void * > * addAllItemsFromOverlapping (Interval *interval, std::vector< void * > *resultItems)
virtual int depth ()
virtual int size ()
virtual int nodeSize ()
Static Public Member Functions
static Node * createNode (Interval *itemInterval)
static Node * createExpanded (Node *node, Interval *addInterval)
static int getSubnodeIndex (Interval *interval, double centre)
Protected Member Functions
bool isSearchMatch (Interval *itemInterval) override
Protected Attributes
std::vector< void * > * items
Node * subnode [2]
Private Member Functions
Node * getSubnode (int index)
Node * createSubnode (int index)
Private Attributes
Interval * interval
double centre
int level
Detailed Description
A node of a Bintree.
Definition at line 35 of file Node.h.
Constructor & Destructor Documentation
geos::index::bintree::Node::Node (Interval * newInterval, int newLevel)
Definition at line 48 of file Node.cpp.
References centre, geos::index::bintree::Interval::getMax(), geos::index::bintree::Interval::getMin(), interval, and level.
Referenced by createNode(), and createSubnode().
 {
   interval=newInterval;
   level=newLevel;
   centre=(interval->getMin()+interval->getMax())/2;
 }
geos::index::bintree::Node::~Node () override
Definition at line 55 of file Node.cpp.
References interval.
 {
   delete interval;
 }
Member Function Documentation
void geos::index::bintree::NodeBase::add (void * item) virtual inherited
Definition at line 68 of file NodeBase.cpp.
Referenced by geos::index::bintree::Root::insert(), and geos::index::bintree::Root::insertContained().
{
   items->push_back(item);
 }
vector< void * > * geos::index::bintree::NodeBase::addAllItems (std::vector< void * > * newItems) virtual inherited
Definition at line 72 of file NodeBase.cpp.
{
   items->insert(items->end(),newItems->begin(),newItems->end());
   for(int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subnode[i]->addAllItems(newItems);
     }
   }
   return items;
 }
vector< void * > * geos::index::bintree::NodeBase::addAllItemsFromOverlapping (Interval * interval, std::vector< void * > * resultItems) virtual inherited
Definition at line 83 of file NodeBase.cpp.
 {
   if (!isSearchMatch(interval))
     return items;
   resultItems->insert(resultItems->end(),items->begin(),items->end());
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subnode[i]->addAllItemsFromOverlapping(interval,resultItems);
     }
   }
   return items;
 }
Node * geos::index::bintree::Node::createExpanded (Node * node, Interval * addInterval) static
Definition at line 38 of file Node.cpp.
References createNode(), geos::index::bintree::Interval::expandToInclude(), insert(), and interval.
Referenced by geos::index::bintree::Root::insert().
 {
   Interval *expandInt=new Interval(addInterval);
   if (node!=nullptr) expandInt->expandToInclude(node->interval);
   Node *largerNode=createNode(expandInt);
   if (node!=nullptr) largerNode->insert(node);
   delete expandInt;
   return largerNode;
 }
Node * geos::index::bintree::Node::createNode (Interval * itemInterval) static
Definition at line 28 of file Node.cpp.
References geos::index::bintree::Key::getInterval(), geos::index::bintree::Key::getLevel(), and Node().
Referenced by createExpanded().
 {
   Key *key=new Key(itemInterval);
   //System.out.println("input: " + env + "  binaryEnv: " + key.getEnvelope());
   Node* node=new Node(new Interval(key->getInterval()),key->getLevel());
   delete key;
   return node;
 }
Node * geos::index::bintree::Node::createSubnode (int index) private
Definition at line 142 of file Node.cpp.
References centre, geos::index::bintree::Interval::getMax(), geos::index::bintree::Interval::getMin(), interval, level, and Node().
Referenced by getSubnode(), and insert().
 {
   // create a new subnode in the appropriate interval
   double min=0.0;
   double max=0.0;
   switch (index) {
     case 0:
       min=interval->getMin();
       max=centre;
       break;
     case 1:
       min=centre;
       max=interval->getMax();
       break;
   }
   Interval* subInt=new Interval(min,max);
   Node *node=new Node(subInt,level-1);
   return node;
 }
int geos::index::bintree::NodeBase::depth () virtual inherited
Definition at line 97 of file NodeBase.cpp.
 {
   int maxSubDepth=0;
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       int sqd=subnode[i]->depth();
       if (sqd>maxSubDepth)
         maxSubDepth=sqd;
     }
   }
   return maxSubDepth+1;
 }
NodeBase * geos::index::bintree::Node::find (Interval * searchInterval)
Returns the smallest existing node containing the envelope.
Definition at line 97 of file Node.cpp.
References centre, find(), geos::index::bintree::NodeBase::getSubnodeIndex(), and geos::index::bintree::NodeBase::subnode.
Referenced by find(), and geos::index::bintree::Root::insertContained().
 {
   int subnodeIndex=getSubnodeIndex(searchInterval,centre);
   if (subnodeIndex==-1)
     return this;
   if (subnode[subnodeIndex]!=nullptr) {
     // query lies in subnode, so search it
     Node *node=subnode[subnodeIndex];
     return node->find(searchInterval);
   }
   // no existing subnode, so return this one anyway
   return this;
 }
Interval * geos::index::bintree::Node::getInterval ()
Definition at line 61 of file Node.cpp.
References interval.
Referenced by geos::index::bintree::Root::insert(), and geos::index::bintree::Root::insertContained().
 {
   return interval;
 }
vector< void * > * geos::index::bintree::NodeBase::getItems () virtual inherited
Definition at line 63 of file NodeBase.cpp.
 {
   return items;
 }
Node * geos::index::bintree::Node::getNode (Interval * searchInterval)
Returns the subnode containing the envelope. Creates the node if it does not already exist.
Definition at line 78 of file Node.cpp.
References centre, getNode(), getSubnode(), and geos::index::bintree::NodeBase::getSubnodeIndex().
Referenced by getNode(), and geos::index::bintree::Root::insertContained().
 {
   int subnodeIndex=getSubnodeIndex(searchInterval,centre);
   // if index is -1 searchEnv is not contained in a subnode
   if (subnodeIndex!=-1) {
     // create the node if it does not exist
     Node* node=getSubnode(subnodeIndex);
     // recursively search the found/created node
     return node->getNode(searchInterval);
   } else {
     return this;
   }
 }
Node * geos::index::bintree::Node::getSubnode (int index) private
get the subnode for the index. If it doesn't exist, create it
Definition at line 133 of file Node.cpp.
References createSubnode(), and geos::index::bintree::NodeBase::subnode.
Referenced by getNode().
 {
   if (subnode[index]==nullptr) {
     subnode[index]=createSubnode(index);
   }
   return subnode[index];
 }
int geos::index::bintree::NodeBase::getSubnodeIndex (Interval * interval, double centre) static inherited
Returns the index of the subnode that wholely contains the given interval. If none does, returns -1.
Definition at line 36 of file NodeBase.cpp.
References geos::index::bintree::Interval::max, and geos::index::bintree::Interval::min.
Referenced by find(), getNode(), insert(), and geos::index::bintree::Root::insert().
 {
   int subnodeIndex=-1;
   if (interval->min>=centre) subnodeIndex=1;
   if (interval->max<=centre) subnodeIndex=0;
   return subnodeIndex;
 }
void geos::index::bintree::Node::insert (Node * node)
Definition at line 112 of file Node.cpp.
References centre, geos::index::bintree::Interval::contains(), createSubnode(), geos::index::bintree::NodeBase::getSubnodeIndex(), insert(), interval, level, and geos::index::bintree::NodeBase::subnode.
Referenced by createExpanded(), and insert().
 {
   assert(interval==nullptr || interval->contains(node->interval));
   int index=getSubnodeIndex(node->interval,centre);
   assert(index >= 0);
   if (node->level==level-1) {
     subnode[index]=node;
   } else {
     // the node is not a direct child, so make a new child node to contain it
     // and recursively insert the node
     Node* childNode=createSubnode(index);
     childNode->insert(node);
     subnode[index]=childNode;
   }
 }
bool geos::index::bintree::Node::isSearchMatch (Interval * itemInterval) override protected virtual
Implements geos::index::bintree::NodeBase.
Definition at line 67 of file Node.cpp.
References interval, and geos::index::bintree::Interval::overlaps().
 {
   return itemInterval->overlaps(interval);
 }
int geos::index::bintree::NodeBase::nodeSize () virtual inherited
Definition at line 123 of file NodeBase.cpp.
 {
   int subSize=0;
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subSize+=subnode[i]->nodeSize();
     }
   }
   return subSize+1;
 }
int geos::index::bintree::NodeBase::size () virtual inherited
Definition at line 111 of file NodeBase.cpp.
 {
   int subSize=0;
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subSize+=subnode[i]->size();
     }
   }
   return subSize+(int)items->size();
 }
Member Data Documentation
double geos::index::bintree::Node::centre private
Definition at line 59 of file Node.h.
Referenced by createSubnode(), find(), getNode(), insert(), and Node().
Interval* geos::index::bintree::Node::interval private
Definition at line 57 of file Node.h.
Referenced by createExpanded(), createSubnode(), getInterval(), insert(), isSearchMatch(), Node(), and ~Node().
std::vector<void*>* geos::index::bintree::NodeBase::items protected inherited
Definition at line 63 of file NodeBase.h.
int geos::index::bintree::Node::level private
Definition at line 61 of file Node.h.
Referenced by createSubnode(), insert(), and Node().
Node* geos::index::bintree::NodeBase::subnode[2] protected inherited
subnodes are numbered as follows:
0 | 1
Definition at line 70 of file NodeBase.h.
Referenced by find(), getSubnode(), insert(), and geos::index::bintree::Root::insert().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/bintree/Node.h
/home/vicky/potree/geos/vicky/src/index/bintree/Node.cpp