GEOS: geos::index::strtree::SIRtree Class Reference
geos::index::strtree::SIRtree Class Reference
One-dimensional version of an STR-packed R-tree.
#include <SIRtree.h>
Classes
class SIRIntersectsOp
Public Member Functions
SIRtree ()
Constructs an SIRtree with the default node capacity.
SIRtree (std::size_t nodeCapacity)
Constructs an SIRtree with the given maximum number of child nodes that a node may have.
~SIRtree () override
void insert (double x1, double x2, void *item)
std::vector< void * > * query (double x1, double x2)
std::vector< void * > * query (double x)
ItemsList * itemsTree ()
virtual void query (const void *searchBounds, const AbstractNode *node, std::vector< void * > *matches)
virtual void boundablesAtLevel (int level, AbstractNode *top, BoundableList *boundables)
virtual void build ()
virtual std::size_t getNodeCapacity ()
void iterate (ItemVisitor &visitor)
Static Public Member Functions
static bool compareDoubles (double a, double b)
Protected Member Functions
std::unique_ptr< BoundableList > createParentBoundables (BoundableList *childBoundables, int newLevel) override
Sorts the childBoundables then divides them into groups of size M, where M is the node capacity.
AbstractNode * createNode (int level) override
IntersectsOp * getIntersectsOp () override
std::unique_ptr< BoundableList > sortBoundables (const BoundableList *input) override
bool remove (const void *itemEnv, void *item)
Also builds the tree, if necessary.
virtual AbstractNode * lastNode (BoundableList *nodeList)
virtual AbstractNode * getRoot ()
virtual void insert (const void *bounds, void *item)
Also builds the tree, if necessary.
void query (const void *searchBounds, std::vector< void * > &foundItems)
Also builds the tree, if necessary.
void query (const void *searchBounds, ItemVisitor &visitor)
Also builds the tree, if necessary.
void query (const void *searchBounds, const AbstractNode &node, ItemVisitor &visitor)
std::unique_ptr< BoundableList > boundablesAtLevel (int level)
Protected Attributes
AbstractNode * root
std::vector< AbstractNode * > * nodes
std::size_t nodeCapacity
Private Attributes
IntersectsOp * intersectsOp
Detailed Description
One-dimensional version of an STR-packed R-tree.
SIR stands for "Sort-Interval-Recursive".
STR-packed R-trees are described in: P. Rigaux, Michel Scholl and Agnes Voisard. Spatial Databases With Application To GIS. Morgan Kaufmann, San Francisco, 2002.
See also
STRtree
Definition at line 41 of file SIRtree.h.
Constructor & Destructor Documentation
geos::index::strtree::SIRtree::SIRtree ()
Constructs an SIRtree with the default node capacity.
Definition at line 69 of file SIRtree.cpp.
References geos::index::strtree::AbstractSTRtree::AbstractSTRtree(), intersectsOp, and geos::index::strtree::AbstractSTRtree::nodeCapacity.
                 :
   AbstractSTRtree(10),
   intersectsOp(new SIRIntersectsOp())
 {
 }
geos::index::strtree::SIRtree::SIRtree (std::size_t nodeCapacity)
Constructs an SIRtree with the given maximum number of child nodes that a node may have.
geos::index::strtree::SIRtree::~SIRtree () override
Definition at line 82 of file SIRtree.cpp.
References intersectsOp.
                   {
   delete intersectsOp;
 }
Member Function Documentation
std::unique_ptr< BoundableList > geos::index::strtree::AbstractSTRtree::boundablesAtLevel (int level) protected inherited
Definition at line 308 of file AbstractSTRtree.cpp.
 {
   std::unique_ptr<BoundableList> boundables ( new BoundableList() );
   boundablesAtLevel(level, root, boundables.get());
   return boundables;
 }
void geos::index::strtree::AbstractSTRtree::boundablesAtLevel (int level, AbstractNode * top, BoundableList * boundables) virtual inherited
Parameters
level -1 to get items
Definition at line 317 of file AbstractSTRtree.cpp.
References geos::index::strtree::AbstractNode::getChildBoundables(), and geos::index::strtree::AbstractNode::getLevel().
 {
   assert(level>-2);
   if (top->getLevel()==level)
   {
     boundables->push_back(top);
     return;
   }
   assert(top);
   const BoundableList& vb = *(top->getChildBoundables());
   for(BoundableList::const_iterator i=vb.begin(), e=vb.end();
       i!=e; ++i)
   {
     Boundable* boundable=*i;
     if (typeid(*boundable)==typeid(AbstractNode))
     {
       boundablesAtLevel(level, (AbstractNode*)boundable,
         boundables);
     }
     else
     {
       assert(typeid(*boundable)==typeid(ItemBoundable));
       if (level==-1)
       {
         boundables->push_back(boundable);
       }
     }
   }
   return;
 }
void geos::index::strtree::AbstractSTRtree::build () virtual inherited
Creates parent nodes, grandparent nodes, and so forth up to the root node, for the data that has been inserted into the tree. Can only be called once, and thus can be called only after all of the data has been inserted into the tree.
Definition at line 56 of file AbstractSTRtree.cpp.
Referenced by geos::index::strtree::STRtree::nearestNeighbour().
 {
   if(built)
     return;
   root=(itemBoundables->empty()?createNode(0):createHigherLevels(itemBoundables,-1));
   built=true;
 }
static bool geos::index::strtree::AbstractSTRtree::compareDoubles (double a, double b) inline static inherited
Definition at line 260 of file AbstractSTRtree.h.
{
     // NOTE - strk:
     // Ternary operation is a workaround for
     // a probable MingW bug, see
     // http://trac.osgeo.org/geos/ticket/293
     return ( a < b ) ? true : false;
   }
AbstractNode * geos::index::strtree::SIRtree::createNode (int level) override protected virtual
Implements geos::index::strtree::AbstractSTRtree.
Definition at line 120 of file SIRtree.cpp.
References geos::index::strtree::AbstractSTRtree::nodes.
 {
   AbstractNode *an = new SIRAbstractNode(level, static_cast<int>(nodeCapacity));
   nodes->push_back(an);
   return an;
 }
std::unique_ptr< BoundableList > geos::index::strtree::SIRtree::createParentBoundables (BoundableList * childBoundables, int newLevel) override protected virtual
Sorts the childBoundables then divides them into groups of size M, where M is the node capacity.
Reimplemented from geos::index::strtree::AbstractSTRtree.
Definition at line 37 of file SIRtree.cpp.
References geos::index::strtree::AbstractNode::addChildBoundable(), and geos::index::strtree::AbstractNode::getChildBoundables().
 {
   assert(!childBoundables->empty());
   std::unique_ptr<BoundableList> parentBoundables ( new BoundableList() );
   parentBoundables->push_back(createNode(newLevel));
   std::unique_ptr<BoundableList> sortedChildBoundables ( sortBoundables(childBoundables) );
   //for(unsigned int i=0;i<sortedChildBoundables->size();i++)
   for (BoundableList::iterator i=sortedChildBoundables->begin(),
       e=sortedChildBoundables->end();
       i!=e; ++i)
   {
     //Boundable *childBoundable=(AbstractNode*)(*sortedChildBoundables)[i];
     Boundable *childBoundable=*i;
     AbstractNode* lNode = lastNode(parentBoundables.get());
     if (lNode->getChildBoundables()->size() == nodeCapacity)
     {
       parentBoundables->push_back(createNode(newLevel));
     }
     lNode->addChildBoundable(childBoundable);
   }
   return parentBoundables;
 }
IntersectsOp* geos::index::strtree::SIRtree::getIntersectsOp () inline override protected virtual
Returns
a test for intersection between two bounds, necessary because subclasses of AbstractSTRtree have different implementations of bounds.
See also
IntersectsOp
Implements geos::index::strtree::AbstractSTRtree.
Definition at line 96 of file SIRtree.h.
 {return intersectsOp;}
virtual std::size_t geos::index::strtree::AbstractSTRtree::getNodeCapacity () inline virtual inherited
Returns the maximum number of child nodes that a node may have
Definition at line 281 of file AbstractSTRtree.h.
Referenced by geos::index::strtree::STRtree::createParentBoundables().
 { return nodeCapacity; }
virtual AbstractNode* geos::index::strtree::AbstractSTRtree::getRoot () inline protected virtual inherited
Definition at line 203 of file AbstractSTRtree.h.
Referenced by geos::index::strtree::STRtree::nearestNeighbour().
{
                 assert(built);
     return root;
   }
void geos::index::strtree::SIRtree::insert (double x1, double x2, void * item)
Inserts an item having the given bounds into the tree.
Definition at line 130 of file SIRtree.cpp.
References geos::index::strtree::AbstractSTRtree::insert().
Referenced by geos::algorithm::SIRtreePointInRing::buildIndex().
{
   AbstractSTRtree::insert(new Interval(min(x1,x2),max(x1, x2)),item);
 }
void geos::index::strtree::AbstractSTRtree::insert (const void * bounds, void * item) protected virtual inherited
Also builds the tree, if necessary.
Definition at line 115 of file AbstractSTRtree.cpp.
Referenced by insert(), and geos::index::strtree::STRtree::insert().
 {
   // Cannot insert items into an STR packed R-tree after it has been built
   assert(!built);
   itemBoundables->push_back(new ItemBoundable(bounds,item));
 }
ItemsList * geos::index::strtree::AbstractSTRtree::itemsTree () inherited
Gets a tree structure (as a nested list) corresponding to the structure of the items and nodes in this tree.
The returned Lists contain either Object items, or Lists which correspond to subtrees of the tree Subtrees which do not contain any items are not included.
Builds the tree if necessary.
Note
The caller is responsible for releasing the list
Returns
a List of items and/or Lists
Definition at line 382 of file AbstractSTRtree.cpp.
Referenced by geos::operation::geounion::CascadedUnion::Union(), and geos::operation::geounion::CascadedPolygonUnion::Union().
 {
     if (!built) {
         build();
     }
     ItemsList* valuesTree (itemsTree(root));
     if (valuesTree == nullptr)
         return new ItemsList();
     return valuesTree;
 }
void geos::index::strtree::AbstractSTRtree::iterate (ItemVisitor & visitor) inherited
Iterate over all items added thus far. Explicitly does not build the tree.
Definition at line 293 of file AbstractSTRtree.cpp.
References geos::index::ItemVisitor::visitItem().
Referenced by geos::precision::MinimumClearance::compute(), and GEOSSTRtree_iterate_r().
 {
     for (BoundableList::const_iterator i=itemBoundables->begin(), e=itemBoundables->end();
       i!=e; i++)
   {
     const Boundable* boundable = *i;
     if (const ItemBoundable *ib=dynamic_cast<const ItemBoundable *>(boundable))
     {
       visitor.visitItem(ib->getItem());
     }
         }
 }
virtual AbstractNode* geos::index::strtree::AbstractSTRtree::lastNode (BoundableList * nodeList) inline protected virtual inherited
Definition at line 196 of file AbstractSTRtree.h.
   {
     assert(!nodeList->empty());
     // Cast from Boundable to AbstractNode
     return static_cast<AbstractNode*>(nodeList->back() );
   }
std::vector<void*>* geos::index::strtree::SIRtree::query (double x1, double x2) inline
Returns items whose bounds intersect the given bounds.
Parameters
x1 possibly equal to x2
Definition at line 66 of file SIRtree.h.
References geos::index::strtree::AbstractSTRtree::query().
Referenced by geos::algorithm::SIRtreePointInRing::isInside().
   {
     std::vector<void*>* results = new std::vector<void*>();
     Interval interval(std::min(x1, x2), std::max(x1, x2));
     AbstractSTRtree::query(&interval, *results);
     return results;
   }
std::vector<void*>* geos::index::strtree::SIRtree::query (double x) inline
Returns items whose bounds intersect the given value.
Definition at line 77 of file SIRtree.h.
References query().
Referenced by query().
 { return query(x,x); }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, std::vector< void * > & foundItems) protected inherited
Also builds the tree, if necessary.
Definition at line 124 of file AbstractSTRtree.cpp.
Referenced by query(), and geos::index::strtree::STRtree::query().
 {
   if (!built) build();
   if (itemBoundables->empty()) assert(root->getBounds()==nullptr);
   if (getIntersectsOp()->intersects(root->getBounds(), searchBounds))
   {
     query(searchBounds,root, &matches);
   }
 }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, ItemVisitor & visitor) protected inherited
Also builds the tree, if necessary.
Definition at line 138 of file AbstractSTRtree.cpp.
 {
   if (!built) build();
   if (itemBoundables->empty()) assert(root->getBounds()==nullptr);
   if (getIntersectsOp()->intersects(root->getBounds(),searchBounds))
   {
     query(searchBounds, *root, visitor);
   }
 }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, const AbstractNode & node, ItemVisitor & visitor) protected inherited
Definition at line 152 of file AbstractSTRtree.cpp.
References geos::index::strtree::Boundable::getBounds(), geos::index::strtree::AbstractNode::getChildBoundables(), and geos::index::ItemVisitor::visitItem().
 {
   const BoundableList& boundables = *(node.getChildBoundables());
   for (BoundableList::const_iterator i=boundables.begin(), e=boundables.end();
       i!=e; i++)
   {
     const Boundable* childBoundable = *i;
     if (!getIntersectsOp()->intersects(childBoundable->getBounds(), searchBounds)) {
       continue;
     }
     if(const AbstractNode *an=dynamic_cast<const AbstractNode*>(childBoundable))
     {
       query(searchBounds, *an, visitor);
     }
     else if (const ItemBoundable *ib=dynamic_cast<const ItemBoundable *>(childBoundable))
     {
       visitor.visitItem(ib->getItem());
     }
     else
     {
       assert(0); // unsupported childBoundable type
     }
   }
 }
void geos::index::strtree::AbstractSTRtree::query (const void * searchBounds, const AbstractNode * node, std::vector< void * > * matches) virtual inherited
Definition at line 257 of file AbstractSTRtree.cpp.
References geos::index::strtree::Boundable::getBounds(), geos::index::strtree::AbstractNode::getChildBoundables(), and geos::index::strtree::AbstractSTRtree::IntersectsOp::intersects().
 {
   assert(node);
   const BoundableList& vb = *(node->getChildBoundables());
   IntersectsOp *io=getIntersectsOp();
   //std::size_t vbsize=vb.size();
   //cerr<<"AbstractSTRtree::query: childBoundables: "<<vbsize<<endl;
   for(BoundableList::const_iterator i=vb.begin(), e=vb.end();
       i!=e; ++i)
   {
     const Boundable* childBoundable=*i;
     if (!io->intersects(childBoundable->getBounds(), searchBounds))
     {
       continue;
     }
     if(const AbstractNode *an=dynamic_cast<const AbstractNode*>(childBoundable))
     {
       query(searchBounds, an, matches);
     }
     else if (const ItemBoundable *ib=dynamic_cast<const ItemBoundable *>(childBoundable))
     {
       matches->push_back(ib->getItem());
     }
     else
     {
       assert(0); // unsupported childBoundable type
     }
   }
 }
bool geos::index::strtree::AbstractSTRtree::remove (const void * itemEnv, void * item) protected inherited
Also builds the tree, if necessary.
Definition at line 183 of file AbstractSTRtree.cpp.
 {
   if (!built) build();
   if (itemBoundables->empty()) {
     assert(root->getBounds() == nullptr);
   }
   if (getIntersectsOp()->intersects(root->getBounds(), searchBounds)) {
     return remove(searchBounds, *root, item);
   }
   return false;
 }
std::unique_ptr< BoundableList > geos::index::strtree::SIRtree::sortBoundables (const BoundableList * input) override protected virtual
Implements geos::index::strtree::AbstractSTRtree.
Definition at line 135 of file SIRtree.cpp.
References geos::index::strtree::compareSIRBoundables().
 {
   std::unique_ptr<BoundableList> output ( new BoundableList(*input) );
   sort(output->begin(), output->end(), compareSIRBoundables);
   //output->sort(compareSIRBoundables);
   return output;
 }
Member Data Documentation
IntersectsOp* geos::index::strtree::SIRtree::intersectsOp private
Definition at line 102 of file SIRtree.h.
Referenced by SIRtree(), and ~SIRtree().
std::size_t geos::index::strtree::AbstractSTRtree::nodeCapacity protected inherited
Definition at line 233 of file AbstractSTRtree.h.
Referenced by geos::index::strtree::STRtree::createNode(), and SIRtree().
std::vector<AbstractNode *>* geos::index::strtree::AbstractSTRtree::nodes protected inherited
Definition at line 184 of file AbstractSTRtree.h.
Referenced by createNode(), and geos::index::strtree::STRtree::createNode().
AbstractNode* geos::index::strtree::AbstractSTRtree::root protected inherited
Definition at line 182 of file AbstractSTRtree.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/strtree/SIRtree.h
/home/vicky/potree/geos/vicky/src/index/strtree/SIRtree.cpp