GEOS: geos::index::strtree::AbstractNode Class Reference
geos::index::strtree::AbstractNode Class Reference abstract
A node of the STR tree.
#include <AbstractNode.h>
Public Member Functions
AbstractNode (int newLevel, int capacity=10)
~AbstractNode () override
std::vector< Boundable * > * getChildBoundables ()
const std::vector< Boundable * > * getChildBoundables () const
const void * getBounds () const override
int getLevel ()
void addChildBoundable (Boundable *childBoundable)
Protected Member Functions
virtual void * computeBounds () const =0
Protected Attributes
void * bounds
Private Attributes
std::vector< Boundable * > childBoundables
int level
Detailed Description
A node of the STR tree.
The children of this node are either more nodes (AbstractNodes) or real data (ItemBoundables).
If this node contains real data (rather than nodes), then we say that this node is a "leaf node".
Definition at line 42 of file AbstractNode.h.
Constructor & Destructor Documentation
geos::index::strtree::AbstractNode::AbstractNode (int newLevel, int capacity = 10)
Definition at line 33 of file AbstractNode.cpp.
{
   childBoundables.reserve(capacity);
   bounds=nullptr;
   level=newLevel;
 }
geos::index::strtree::AbstractNode::~AbstractNode () override
Definition at line 39 of file AbstractNode.cpp.
{
 }
Member Function Documentation
void geos::index::strtree::AbstractNode::addChildBoundable (Boundable * childBoundable)
Adds either an AbstractNode, or if this is a leaf node, a data object (wrapped in an ItemBoundable)
Definition at line 63 of file AbstractNode.cpp.
Referenced by geos::index::strtree::SIRtree::createParentBoundables(), and geos::index::strtree::AbstractSTRtree::createParentBoundables().
{
   assert(bounds==nullptr);
   childBoundables.push_back(childBoundable);
 }
virtual void* geos::index::strtree::AbstractNode::computeBounds () const protected pure virtual
Implemented in geos::index::strtree::STRAbstractNode, and geos::index::strtree::SIRAbstractNode.
const void * geos::index::strtree::AbstractNode::getBounds () const override virtual
Returns a representation of space that encloses this Boundable, preferably not much bigger than this Boundable's boundary yet fast to test for intersection with the bounds of other Boundables. The class of object returned depends on the subclass of AbstractSTRtree.
Returns
an Envelope (for STRtrees), an Interval (for SIRtrees), or other object (for other subclasses of AbstractSTRtree)
See also
AbstractSTRtree::IntersectsOp
Implements geos::index::strtree::Boundable.
Definition at line 43 of file AbstractNode.cpp.
 {
   if (bounds==nullptr) {
     bounds = computeBounds();
   }
   return bounds;
 }
std::vector<Boundable*>* geos::index::strtree::AbstractNode::getChildBoundables () inline
Definition at line 52 of file AbstractNode.h.
Referenced by geos::index::strtree::AbstractSTRtree::boundablesAtLevel(), geos::index::strtree::SIRtree::createParentBoundables(), geos::index::strtree::AbstractSTRtree::createParentBoundables(), geos::index::strtree::AbstractSTRtree::itemsTree(), geos::index::strtree::AbstractSTRtree::query(), geos::index::strtree::AbstractSTRtree::remove(), and geos::index::strtree::AbstractSTRtree::removeItem().
{
     return &childBoundables;
   }
const std::vector<Boundable*>* geos::index::strtree::AbstractNode::getChildBoundables () const inline
Definition at line 58 of file AbstractNode.h.
{
     return &childBoundables;
   }
int geos::index::strtree::AbstractNode::getLevel ()
Returns 0 if this node is a leaf, 1 if a parent of a leaf, and so on; the root node will have the highest level
Definition at line 55 of file AbstractNode.cpp.
Referenced by geos::index::strtree::AbstractSTRtree::boundablesAtLevel().
{
   return level;
 }
Member Data Documentation
void* geos::index::strtree::AbstractNode::bounds mutable protected
Definition at line 84 of file AbstractNode.h.
std::vector<Boundable*> geos::index::strtree::AbstractNode::childBoundables private
Definition at line 44 of file AbstractNode.h.
int geos::index::strtree::AbstractNode::level private
Definition at line 45 of file AbstractNode.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/strtree/AbstractNode.h
/home/vicky/potree/geos/vicky/src/index/strtree/AbstractNode.cpp