GEOS: geos::operation::distance::ConnectedElementPointFilter Class Reference
geos::operation::distance::ConnectedElementPointFilter Class Reference
Extracts a single point from each connected element in a Geometry (e.g. a polygon, linestring or point) and returns them in a list.
#include <ConnectedElementPointFilter.h>
Public Member Functions
ConnectedElementPointFilter (std::vector< const geom::Coordinate * > *newPts)
void filter_ro (const geom::Geometry *geom) override
virtual void filter_rw (Geometry *)
Static Public Member Functions
static std::vector< const geom::Coordinate * > * getCoordinates (const geom::Geometry *geom)
Private Attributes
std::vector< const geom::Coordinate * > * pts
Detailed Description
Extracts a single point from each connected element in a Geometry (e.g. a polygon, linestring or point) and returns them in a list.
Definition at line 47 of file ConnectedElementPointFilter.h.
Constructor & Destructor Documentation
geos::operation::distance::ConnectedElementPointFilter::ConnectedElementPointFilter (std::vector< const geom::Coordinate * > * newPts) inline
Definition at line 60 of file ConnectedElementPointFilter.h.
     :
     pts(newPts)
   {}
Member Function Documentation
void geos::operation::distance::ConnectedElementPointFilter::filter_ro (const geom::Geometry * geom) override virtual
Reimplemented from geos::geom::GeometryFilter.
Definition at line 49 of file ConnectedElementPointFilter.cpp.
References geos::geom::Geometry::getCoordinate().
{
   if ((typeid(*geom)==typeid(Point)) ||
     (typeid(*geom)==typeid(LineString)) ||
     (typeid(*geom)==typeid(Polygon)))
       pts->push_back(geom->getCoordinate());
 }
virtual void geos::geom::GeometryFilter::filter_rw (Geometry *) inline virtual inherited
Reimplemented in geos::operation::distance::ConnectedElementLocationFilter, geos::geom::util::PolygonExtracter, and geos::geom::util::PointExtracter.
Definition at line 61 of file GeometryFilter.h.
Referenced by geos::geom::Point::apply_rw(), geos::geom::Polygon::apply_rw(), geos::geom::GeometryCollection::apply_rw(), geos::geom::LineString::apply_rw(), and geos::geom::Geometry::apply_rw().
 { assert(0); }
vector< const Coordinate * > * geos::operation::distance::ConnectedElementPointFilter::getCoordinates (const geom::Geometry * geom) static
Returns a list containing a Coordinate from each Polygon, LineString, and Point found inside the specified geometry. Thus, if the specified geometry is not a GeometryCollection, an empty list will be returned.
Definition at line 41 of file ConnectedElementPointFilter.cpp.
References geos::geom::Geometry::apply_ro().
 {
   vector<const Coordinate*> *points=new vector<const Coordinate*>();
   ConnectedElementPointFilter c(points);
   geom->apply_ro(&c);
   return points;
 }
Member Data Documentation
std::vector<const geom::Coordinate*>* geos::operation::distance::ConnectedElementPointFilter::pts private
Definition at line 50 of file ConnectedElementPointFilter.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/distance/ConnectedElementPointFilter.h
/home/vicky/potree/geos/vicky/src/operation/distance/ConnectedElementPointFilter.cpp