GEOS: geos::index::intervalrtree::IntervalRTreeBranchNode Class Reference
geos::index::intervalrtree::IntervalRTreeBranchNode Class Reference
#include <IntervalRTreeBranchNode.h>
Public Types
typedef std::vector< const IntervalRTreeNode * > ConstVect
Public Member Functions
IntervalRTreeBranchNode (const IntervalRTreeNode *n1, const IntervalRTreeNode *n2)
~IntervalRTreeBranchNode () override
void query (double queryMin, double queryMax, index::ItemVisitor *visitor) const override
double getMin () const
double getMax () const
Static Public Member Functions
static bool compare (const IntervalRTreeNode *n1, const IntervalRTreeNode *n2)
Protected Member Functions
bool intersects (double queryMin, double queryMax) const
Protected Attributes
double min
double max
Private Attributes
const IntervalRTreeNode * node1
const IntervalRTreeNode * node2
Detailed Description
Definition at line 35 of file IntervalRTreeBranchNode.h.
Member Typedef Documentation
typedef std::vector<const IntervalRTreeNode *> geos::index::intervalrtree::IntervalRTreeNode::ConstVect inherited
Definition at line 51 of file IntervalRTreeNode.h.
Constructor & Destructor Documentation
geos::index::intervalrtree::IntervalRTreeBranchNode::IntervalRTreeBranchNode (const IntervalRTreeNode * n1, const IntervalRTreeNode * n2) inline
Definition at line 49 of file IntervalRTreeBranchNode.h.
   : IntervalRTreeNode( std::min( n1->getMin(), n2->getMin()), std::max( n1->getMax(), n2->getMax())),
     node1( n1),
     node2( n2)
   { }
geos::index::intervalrtree::IntervalRTreeBranchNode::~IntervalRTreeBranchNode () inline override
Definition at line 55 of file IntervalRTreeBranchNode.h.
   {
     delete node1;
     delete node2;
   }
Member Function Documentation
static bool geos::index::intervalrtree::IntervalRTreeNode::compare (const IntervalRTreeNode * n1, const IntervalRTreeNode * n2) inline static inherited
Definition at line 87 of file IntervalRTreeNode.h.
References geos::index::intervalrtree::IntervalRTreeNode::getMax(), and geos::index::intervalrtree::IntervalRTreeNode::getMin().
Referenced by geos::index::intervalrtree::SortedPackedIntervalRTree::buildTree().
     {
       //IntervalRTreeNode * n1 = dynamic_cast<IntervalRTreeNode *>( o1);
       //IntervalRTreeNode * n2 = dynamic_cast<IntervalRTreeNode *>( o2);
       double mid1 = (n1->getMin() + n1->getMax()) / 2;
       double mid2 = (n2->getMin() + n2->getMax()) / 2;
       //if (mid1 < mid2) return -1;
       //if (mid1 > mid2) return 1;
       //return 0;
       return mid1 > mid2;
     }
double geos::index::intervalrtree::IntervalRTreeNode::getMax () const inline inherited
Definition at line 71 of file IntervalRTreeNode.h.
Referenced by geos::index::intervalrtree::IntervalRTreeNode::compare().
   {
     return max;
   }
double geos::index::intervalrtree::IntervalRTreeNode::getMin () const inline inherited
Definition at line 66 of file IntervalRTreeNode.h.
Referenced by geos::index::intervalrtree::IntervalRTreeNode::compare().
   {
     return min;
   }
bool geos::index::intervalrtree::IntervalRTreeNode::intersects (double queryMin, double queryMax) const inline protected inherited
Definition at line 42 of file IntervalRTreeNode.h.
Referenced by geos::index::intervalrtree::IntervalRTreeLeafNode::query(), and query().
   {
     if (min > queryMax || max < queryMin)
       return false;
     return true;
   }
void geos::index::intervalrtree::IntervalRTreeBranchNode::query (double queryMin, double queryMax, index::ItemVisitor * visitor) const override virtual
Implements geos::index::intervalrtree::IntervalRTreeNode.
Definition at line 36 of file IntervalRTreeBranchNode.cpp.
References geos::index::intervalrtree::IntervalRTreeNode::intersects(), node1, node2, and geos::index::intervalrtree::IntervalRTreeNode::query().
 {
   if (! intersects(queryMin, queryMax))
     return;
   if (node1)
     node1->query( queryMin, queryMax, visitor);
   if (node2)
     node2->query( queryMin, queryMax, visitor);
 }
Member Data Documentation
double geos::index::intervalrtree::IntervalRTreeNode::max protected inherited
Definition at line 40 of file IntervalRTreeNode.h.
double geos::index::intervalrtree::IntervalRTreeNode::min protected inherited
Definition at line 39 of file IntervalRTreeNode.h.
const IntervalRTreeNode* geos::index::intervalrtree::IntervalRTreeBranchNode::node1 private
Definition at line 38 of file IntervalRTreeBranchNode.h.
Referenced by query().
const IntervalRTreeNode* geos::index::intervalrtree::IntervalRTreeBranchNode::node2 private
Definition at line 39 of file IntervalRTreeBranchNode.h.
Referenced by query().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/intervalrtree/IntervalRTreeBranchNode.h
/home/vicky/potree/geos/vicky/src/index/intervalrtree/IntervalRTreeBranchNode.cpp