GEOS: geos::index::bintree::NodeBase Class Reference
geos::index::bintree::NodeBase Class Reference abstract
The base class for nodes in a Bintree.
#include <NodeBase.h>
Public Member Functions
NodeBase ()
virtual ~NodeBase ()
virtual std::vector< void * > * getItems ()
virtual void add (void *item)
virtual std::vector< void * > * addAllItems (std::vector< void * > *newItems)
virtual std::vector< void * > * addAllItemsFromOverlapping (Interval *interval, std::vector< void * > *resultItems)
virtual int depth ()
virtual int size ()
virtual int nodeSize ()
Static Public Member Functions
static int getSubnodeIndex (Interval *interval, double centre)
Protected Member Functions
virtual bool isSearchMatch (Interval *interval)=0
Protected Attributes
std::vector< void * > * items
Node * subnode [2]
Detailed Description
The base class for nodes in a Bintree.
Definition at line 36 of file NodeBase.h.
Constructor & Destructor Documentation
geos::index::bintree::NodeBase::NodeBase ()
Definition at line 44 of file NodeBase.cpp.
 {
   items=new vector<void*>();
   subnode[0]=nullptr;
   subnode[1]=nullptr;
 }
geos::index::bintree::NodeBase::~NodeBase () virtual
Definition at line 51 of file NodeBase.cpp.
                     {
   for(int i=0;i<(int)items->size();i++) {
     delete (MonotoneChain*)(*items)[i];
   }
   delete items;
   delete subnode[0];
   delete subnode[1];
   subnode[0]=nullptr;
   subnode[1]=nullptr;
 }
Member Function Documentation
void geos::index::bintree::NodeBase::add (void * item) virtual
Definition at line 68 of file NodeBase.cpp.
Referenced by geos::index::bintree::Root::insert(), and geos::index::bintree::Root::insertContained().
{
   items->push_back(item);
 }
vector< void * > * geos::index::bintree::NodeBase::addAllItems (std::vector< void * > * newItems) virtual
Definition at line 72 of file NodeBase.cpp.
{
   items->insert(items->end(),newItems->begin(),newItems->end());
   for(int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subnode[i]->addAllItems(newItems);
     }
   }
   return items;
 }
vector< void * > * geos::index::bintree::NodeBase::addAllItemsFromOverlapping (Interval * interval, std::vector< void * > * resultItems) virtual
Definition at line 83 of file NodeBase.cpp.
 {
   if (!isSearchMatch(interval))
     return items;
   resultItems->insert(resultItems->end(),items->begin(),items->end());
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subnode[i]->addAllItemsFromOverlapping(interval,resultItems);
     }
   }
   return items;
 }
int geos::index::bintree::NodeBase::depth () virtual
Definition at line 97 of file NodeBase.cpp.
 {
   int maxSubDepth=0;
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       int sqd=subnode[i]->depth();
       if (sqd>maxSubDepth)
         maxSubDepth=sqd;
     }
   }
   return maxSubDepth+1;
 }
vector< void * > * geos::index::bintree::NodeBase::getItems () virtual
Definition at line 63 of file NodeBase.cpp.
 {
   return items;
 }
int geos::index::bintree::NodeBase::getSubnodeIndex (Interval * interval, double centre) static
Returns the index of the subnode that wholely contains the given interval. If none does, returns -1.
Definition at line 36 of file NodeBase.cpp.
References geos::index::bintree::Interval::max, and geos::index::bintree::Interval::min.
Referenced by geos::index::bintree::Node::find(), geos::index::bintree::Node::getNode(), geos::index::bintree::Node::insert(), and geos::index::bintree::Root::insert().
 {
   int subnodeIndex=-1;
   if (interval->min>=centre) subnodeIndex=1;
   if (interval->max<=centre) subnodeIndex=0;
   return subnodeIndex;
 }
virtual bool geos::index::bintree::NodeBase::isSearchMatch (Interval * interval) protected pure virtual
Implemented in geos::index::bintree::Node, and geos::index::bintree::Root.
int geos::index::bintree::NodeBase::nodeSize () virtual
Definition at line 123 of file NodeBase.cpp.
 {
   int subSize=0;
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subSize+=subnode[i]->nodeSize();
     }
   }
   return subSize+1;
 }
int geos::index::bintree::NodeBase::size () virtual
Definition at line 111 of file NodeBase.cpp.
 {
   int subSize=0;
   for (int i=0;i<2;i++) {
     if (subnode[i]!=nullptr) {
       subSize+=subnode[i]->size();
     }
   }
   return subSize+(int)items->size();
 }
Member Data Documentation
std::vector<void*>* geos::index::bintree::NodeBase::items protected
Definition at line 63 of file NodeBase.h.
Node* geos::index::bintree::NodeBase::subnode[2] protected
subnodes are numbered as follows:
0 | 1
Definition at line 70 of file NodeBase.h.
Referenced by geos::index::bintree::Node::find(), geos::index::bintree::Node::getSubnode(), geos::index::bintree::Node::insert(), and geos::index::bintree::Root::insert().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/bintree/NodeBase.h
/home/vicky/potree/geos/vicky/src/index/bintree/NodeBase.cpp