GEOS: geos::planargraph::Subgraph Class Reference
geos::planargraph::Subgraph Class Reference
A subgraph of a PlanarGraph.
#include <Subgraph.h>
Public Member Functions
Subgraph (PlanarGraph &parent)
PlanarGraph & getParent () const
std::pair< std::set< Edge * >::iterator, bool > add (Edge *e)
std::vector< const DirectedEdge * >::iterator getDirEdgeBegin ()
std::set< Edge * >::iterator edgeBegin ()
std::set< Edge * >::iterator edgeEnd ()
NodeMap::container::iterator nodeBegin ()
NodeMap::container::const_iterator nodeEnd () const
NodeMap::container::iterator nodeEnd ()
NodeMap::container::const_iterator nodeBegin () const
bool contains (Edge *e)
Protected Member Functions
Subgraph (const Subgraph &other)=delete
Subgraph & operator= (const Subgraph &rhs)=delete
Protected Attributes
PlanarGraph & parentGraph
std::set< Edge * > edges
std::vector< const DirectedEdge * > dirEdges
NodeMap nodeMap
Detailed Description
A subgraph of a PlanarGraph.
A subgraph may contain any subset of geomgraph::Edges from the parent graph. It will also automatically contain all geomgraph::DirectedEdge and geomgraph::Node associated with those edges. No new objects are created when edges are added - all associated components must already exist in the parent graph.
@ Actually we'll be copying Coordinates in NodeMap. I guess that'll need to be changed soon.
Definition at line 53 of file Subgraph.h.
Constructor & Destructor Documentation
geos::planargraph::Subgraph::Subgraph (PlanarGraph & parent) inline
Creates a new subgraph of the given PlanarGraph
Parameters
parent the parent graph
Definition at line 61 of file Subgraph.h.
     :
     parentGraph(parent)
     {}
geos::planargraph::Subgraph::Subgraph (const Subgraph & other) protected delete
Member Function Documentation
pair< Edge::NonConstSet::iterator, bool > geos::planargraph::Subgraph::add (Edge * e)
Adds an Edge to the subgraph. The associated DirectedEdges and planarNodes are also added.
Parameters
e the edge to add
Returns
a pair with first element being an iterator to the Edge in set and second element being a boolean value indicating wheter the Edge has been inserted now or was already in the set.
Definition at line 30 of file Subgraph.cpp.
References geos::planargraph::Edge::getDirEdge(), and geos::planargraph::DirectedEdge::getFromNode().
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges().
 {
   pair<Edge::NonConstSet::iterator,bool> p = edges.insert(e);
   if (!p.second) return p;
   dirEdges.push_back(e->getDirEdge(0));
   dirEdges.push_back(e->getDirEdge(1));
   nodeMap.add(e->getDirEdge(0)->getFromNode());
   nodeMap.add(e->getDirEdge(1)->getFromNode());
   return p;
 }
bool geos::planargraph::Subgraph::contains (Edge * e) inline
Tests whether an Edge is contained in this subgraph
Parameters
e the edge to test
Returns
true if the edge is contained in this subgraph
Definition at line 135 of file Subgraph.h.
 { return (edges.find(e) != edges.end()); }
std::set<Edge*>::iterator geos::planargraph::Subgraph::edgeBegin () inline
Returns an Iterator over the Edges in this graph, in the order in which they were added.
Returns
an iterator over the edges
See also
add(Edge)
Definition at line 110 of file Subgraph.h.
Referenced by geos::operation::linemerge::LineSequencer::findSequence().
 { return edges.begin(); }
std::set<Edge*>::iterator geos::planargraph::Subgraph::edgeEnd () inline
Definition at line 111 of file Subgraph.h.
Referenced by geos::operation::linemerge::LineSequencer::findSequence().
 { return edges.end(); }
std::vector<const DirectedEdge*>::iterator geos::planargraph::Subgraph::getDirEdgeBegin () inline
Returns an iterator over the DirectedEdge in this graph, in the order in which they were added.
Returns
an iterator over the directed edges
See also
add(Edge)
Definition at line 97 of file Subgraph.h.
{
     return dirEdges.begin();
   }
PlanarGraph& geos::planargraph::Subgraph::getParent () const inline
Gets the PlanarGraph which this subgraph is part of.
Returns
the parent PlanarGraph
Definition at line 72 of file Subgraph.h.
 { return parentGraph; }
NodeMap::container::iterator geos::planargraph::Subgraph::nodeBegin () inline
Returns a iterators over the planarNodesMap::container in this graph.
Definition at line 117 of file Subgraph.h.
Referenced by geos::operation::linemerge::LineSequencer::findLowestDegreeNode(), and geos::operation::linemerge::LineSequencer::hasSequence().
{
     return nodeMap.begin();
   }
NodeMap::container::const_iterator geos::planargraph::Subgraph::nodeBegin () const inline
Definition at line 126 of file Subgraph.h.
{
     return nodeMap.begin();
   }
NodeMap::container::const_iterator geos::planargraph::Subgraph::nodeEnd () const inline
Definition at line 120 of file Subgraph.h.
Referenced by geos::operation::linemerge::LineSequencer::findLowestDegreeNode(), and geos::operation::linemerge::LineSequencer::hasSequence().
{
     return nodeMap.end();
   }
NodeMap::container::iterator geos::planargraph::Subgraph::nodeEnd () inline
Definition at line 123 of file Subgraph.h.
{
     return nodeMap.end();
   }
Subgraph& geos::planargraph::Subgraph::operator= (const Subgraph & rhs) protected delete
Member Data Documentation
std::vector<const DirectedEdge*> geos::planargraph::Subgraph::dirEdges protected
Definition at line 141 of file Subgraph.h.
std::set<Edge*> geos::planargraph::Subgraph::edges protected
Definition at line 140 of file Subgraph.h.
NodeMap geos::planargraph::Subgraph::nodeMap protected
Definition at line 142 of file Subgraph.h.
PlanarGraph& geos::planargraph::Subgraph::parentGraph protected
Definition at line 139 of file Subgraph.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/planargraph/Subgraph.h
/home/vicky/potree/geos/vicky/src/planargraph/Subgraph.cpp