GEOS: geos::io::WKBReader Class Reference
geos::io::WKBReader Class Reference
Reads a Geometry from Well-Known Binary format.
#include <geos.h>
Public Member Functions
WKBReader (geom::GeometryFactory const &f)
WKBReader ()
Inizialize parser with default GeometryFactory.
geom::Geometry * read (std::istream &is)
Reads a Geometry from an istream.
geom::Geometry * readHEX (std::istream &is)
Reads a Geometry from an istream in hex format.
Static Public Member Functions
static std::ostream & printHEX (std::istream &is, std::ostream &os)
Print WKB in HEX form to out stream.
Private Member Functions
geom::Geometry * readGeometry ()
geom::Point * readPoint ()
geom::LineString * readLineString ()
geom::LinearRing * readLinearRing ()
geom::Polygon * readPolygon ()
geom::MultiPoint * readMultiPoint ()
geom::MultiLineString * readMultiLineString ()
geom::MultiPolygon * readMultiPolygon ()
geom::GeometryCollection * readGeometryCollection ()
geom::CoordinateSequence * readCoordinateSequence (int)
void readCoordinate ()
WKBReader (const WKBReader &other)=delete
WKBReader & operator= (const WKBReader &rhs)=delete
Private Attributes
const geom::GeometryFactory & factory
unsigned int inputDimension
ByteOrderDataInStream dis
std::vector< double > ordValues
Detailed Description
Reads a Geometry from Well-Known Binary format.
This class is designed to support reuse of a single instance to read multiple geometries. This class is not thread-safe; each thread should create its own instance.
The Well-known Binary format is defined in the OpenGIS Simple Features Specification for SQL. This implementation supports the extended WKB standard which allows representing 3-dimensional coordinates.
Definition at line 79 of file WKBReader.h.
Constructor & Destructor Documentation
geos::io::WKBReader::WKBReader (geom::GeometryFactory const & f) inline
Definition at line 83 of file WKBReader.h.
 : factory(f) {}
geos::io::WKBReader::WKBReader ()
Inizialize parser with default GeometryFactory.
Definition at line 49 of file WKBReader.cpp.
   :
   factory(*(GeometryFactory::getDefaultInstance()))
 {}
geos::io::WKBReader::WKBReader (const WKBReader & other) private delete
Member Function Documentation
WKBReader& geos::io::WKBReader::operator= (const WKBReader & rhs) private delete
ostream & geos::io::WKBReader::printHEX (std::istream & is, std::ostream & os) static
Print WKB in HEX form to out stream.
Parameters
is is the stream to read from
os is the stream to write to
Definition at line 55 of file WKBReader.cpp.
Referenced by geos::io::WKBWriter::writeHEX().
 {
   static const char hex[] = "0123456789ABCDEF";
     std::streampos pos = is.tellg(); // take note of input stream get pointer
   is.seekg(0, ios::beg); // rewind input stream
   char each=0;
   while(is.read(&each, 1))
   {
     const unsigned char c=each;
     int low = (c & 0x0F);
     int high = (c >> 4);
     os << hex[high] << hex[low];
   }
   is.clear(); // clear input stream eof flag
   is.seekg(pos); // reset input stream position
   return os;
 }
Geometry * geos::io::WKBReader::read (std::istream & is)
Reads a Geometry from an istream.
Parameters
is the stream to read from
Returns
the Geometry read
Exceptions
IOException
ParseException
Definition at line 168 of file WKBReader.cpp.
References dis, readGeometry(), and geos::io::ByteOrderDataInStream::setInStream().
Referenced by GEOSGeomFromWKB_buf_r(), GEOSWKBReader_read_r(), and readHEX().
 {
   dis.setInStream(&is); // will default to machine endian
   return readGeometry();
 }
void geos::io::WKBReader::readCoordinate () private
Definition at line 437 of file WKBReader.cpp.
References dis, factory, geos::geom::GeometryFactory::getPrecisionModel(), inputDimension, geos::geom::PrecisionModel::makePrecise(), ordValues, and geos::io::ByteOrderDataInStream::readDouble().
Referenced by readCoordinateSequence(), and readPoint().
 {
   const PrecisionModel &pm = *factory.getPrecisionModel();
   for (unsigned int i=0; i<inputDimension; ++i)
   {
     if ( i <= 1 ) ordValues[i] = pm.makePrecise(dis.readDouble());
     else ordValues[i] = dis.readDouble();
   }
 #if DEBUG_WKB_READER
   cout<<"WKB coordinate: "<<ordValues[0]<<","<<ordValues[1]<<endl;
 #endif
 }
CoordinateSequence * geos::io::WKBReader::readCoordinateSequence (int size) private
Definition at line 421 of file WKBReader.cpp.
References geos::geom::CoordinateSequenceFactory::create(), factory, geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::geom::CoordinateSequence::getDimension(), inputDimension, ordValues, readCoordinate(), and geos::geom::CoordinateSequence::setOrdinate().
Referenced by readLinearRing(), and readLineString().
 {
   CoordinateSequence *seq = factory.getCoordinateSequenceFactory()->create(size, inputDimension);
   auto targetDim = seq->getDimension();
   if ( targetDim > inputDimension )
     targetDim = inputDimension;
   for (int i=0; i<size; i++) {
     readCoordinate();
     for (unsigned int j=0; j<targetDim; j++) {
       seq->setOrdinate(i, j, ordValues[j]);
     }
   }
   return seq;
 }
Geometry * geos::io::WKBReader::readGeometry () private
Definition at line 175 of file WKBReader.cpp.
References dis, geos::io::ByteOrderValues::ENDIAN_BIG, geos::io::ByteOrderValues::ENDIAN_LITTLE, inputDimension, ordValues, geos::io::ByteOrderDataInStream::readByte(), readGeometryCollection(), geos::io::ByteOrderDataInStream::readInt(), readLineString(), readMultiLineString(), readMultiPoint(), readMultiPolygon(), readPoint(), readPolygon(), geos::io::ByteOrderDataInStream::setOrder(), geos::geom::Geometry::setSRID(), geos::io::WKBConstants::wkbGeometryCollection, geos::io::WKBConstants::wkbLineString, geos::io::WKBConstants::wkbMultiLineString, geos::io::WKBConstants::wkbMultiPoint, geos::io::WKBConstants::wkbMultiPolygon, geos::io::WKBConstants::wkbNDR, geos::io::WKBConstants::wkbPoint, geos::io::WKBConstants::wkbPolygon, and geos::io::WKBConstants::wkbXDR.
Referenced by read(), readGeometryCollection(), readMultiLineString(), readMultiPoint(), and readMultiPolygon().
 {
   // determine byte order
   unsigned char byteOrder = dis.readByte();
 #if DEBUG_WKB_READER
   cout<<"WKB byteOrder: "<<(int)byteOrder<<endl;
 #endif
   // default is machine endian
   if (byteOrder == WKBConstants::wkbNDR)
     dis.setOrder(ByteOrderValues::ENDIAN_LITTLE);
         else if (byteOrder == WKBConstants::wkbXDR)
                 dis.setOrder(ByteOrderValues::ENDIAN_BIG);
   int typeInt = dis.readInt();
   int geometryType = typeInt & 0xff;
 #if DEBUG_WKB_READER
   cout<<"WKB geometryType: "<<geometryType<<endl;
 #endif
   bool hasZ = ((typeInt & 0x80000000) != 0);
   if (hasZ) inputDimension = 3;
   else inputDimension = 2; // doesn't handle M currently
 #if DEBUG_WKB_READER
   cout<<"WKB hasZ: "<<hasZ<<endl;
 #endif
 #if DEBUG_WKB_READER
   cout<<"WKB dimensions: "<<inputDimension<<endl;
 #endif
   bool hasSRID = ((typeInt & 0x20000000) != 0);
 #if DEBUG_WKB_READER
   cout<<"WKB hasSRID: "<<hasSRID<<endl;
 #endif
   int SRID = 0;
   if (hasSRID) SRID = dis.readInt(); // read SRID
   // allocate space for ordValues
   if ( ordValues.size() < inputDimension )
     ordValues.resize(inputDimension);
   Geometry *result;
   switch (geometryType) {
     case WKBConstants::wkbPoint :
       result = readPoint();
       break;
     case WKBConstants::wkbLineString :
       result = readLineString();
       break;
     case WKBConstants::wkbPolygon :
       result = readPolygon();
       break;
     case WKBConstants::wkbMultiPoint :
       result = readMultiPoint();
       break;
     case WKBConstants::wkbMultiLineString :
       result = readMultiLineString();
       break;
     case WKBConstants::wkbMultiPolygon :
       result = readMultiPolygon();
       break;
     case WKBConstants::wkbGeometryCollection :
       result = readGeometryCollection();
       break;
     default:
       stringstream err;
       err << "Unknown WKB type " << geometryType;
       throw  ParseException(err.str());
   }
   result->setSRID(SRID);
   return result;
 }
GeometryCollection * geos::io::WKBReader::readGeometryCollection () private
Definition at line 403 of file WKBReader.cpp.
References geos::geom::GeometryFactory::createGeometryCollection(), dis, factory, readGeometry(), and geos::io::ByteOrderDataInStream::readInt().
Referenced by readGeometry().
 {
   int numGeoms = dis.readInt();
   vector<Geometry *> *geoms = new vector<Geometry *>(numGeoms);
   try {
     for (int i=0; i<numGeoms; i++)
       (*geoms)[i] = (readGeometry());
   } catch (...) {
     for (unsigned int i=0; i<geoms->size(); i++)
       delete (*geoms)[i];
     delete geoms;
     throw;
   }
   return factory.createGeometryCollection(geoms);
 }
Geometry * geos::io::WKBReader::readHEX (std::istream & is)
Reads a Geometry from an istream in hex format.
Parameters
is the stream to read from
Returns
the Geometry read
Exceptions
IOException
ParseException
Definition at line 132 of file WKBReader.cpp.
References read().
Referenced by GEOSGeomFromHEX_buf_r(), and GEOSWKBReader_readHEX_r().
 {
   // setup input/output stream
   stringstream os(ios_base::binary|ios_base::in|ios_base::out);
   while( true )
   {
     const int input_high = is.get();
     if (input_high == char_traits<char>::eof())
       break;
     const int input_low = is.get();
     if (input_low == char_traits<char>::eof())
       throw ParseException("Premature end of HEX string");
     const char high = static_cast<char>(input_high);
     const char low = static_cast<char>(input_low);
     const unsigned char result_high = ASCIIHexToUChar(high);
     const unsigned char result_low = ASCIIHexToUChar(low);
     const unsigned char value =
       static_cast<char>((result_high<<4) + result_low);
 #if DEBUG_HEX_READER
   cout<<"HEX "<<high<<low<<" -> DEC "<<(int)value<<endl;
 #endif
     // write the value to the output stream
     os << value;
   }
   // now call read to convert the geometry
   return this->read(os);
 }
LinearRing * geos::io::WKBReader::readLinearRing () private
Definition at line 280 of file WKBReader.cpp.
References geos::geom::GeometryFactory::createLinearRing(), dis, factory, readCoordinateSequence(), and geos::io::ByteOrderDataInStream::readInt().
Referenced by readPolygon().
 {
   int size = dis.readInt();
 #if DEBUG_WKB_READER
   cout<<"WKB npoints: "<<size<<endl;
 #endif
   CoordinateSequence *pts = readCoordinateSequence(size);
   return factory.createLinearRing(pts);
 }
LineString * geos::io::WKBReader::readLineString () private
Definition at line 269 of file WKBReader.cpp.
References geos::geom::GeometryFactory::createLineString(), dis, factory, readCoordinateSequence(), and geos::io::ByteOrderDataInStream::readInt().
Referenced by readGeometry().
 {
   int size = dis.readInt();
 #if DEBUG_WKB_READER
   cout<<"WKB npoints: "<<size<<endl;
 #endif
   CoordinateSequence *pts = readCoordinateSequence(size);
   return factory.createLineString(pts);
 }
MultiLineString * geos::io::WKBReader::readMultiLineString () private
Definition at line 349 of file WKBReader.cpp.
References BAD_GEOM_TYPE_MSG, geos::geom::GeometryFactory::createMultiLineString(), dis, factory, readGeometry(), and geos::io::ByteOrderDataInStream::readInt().
Referenced by readGeometry().
 {
   int numGeoms = dis.readInt();
   vector<Geometry *> *geoms = new vector<Geometry *>(numGeoms);
   try {
     for (int i=0; i<numGeoms; i++)
     {
       Geometry *g = readGeometry();
       if (!dynamic_cast<LineString *>(g))
       {
         stringstream err;
         err << BAD_GEOM_TYPE_MSG << " LineString";
         throw  ParseException(err.str());
       }
       (*geoms)[i] = g;
     }
   } catch (...) {
     for (unsigned int i=0; i<geoms->size(); i++)
       delete (*geoms)[i];
     delete geoms;
     throw;
   }
   return factory.createMultiLineString(geoms);
 }
MultiPoint * geos::io::WKBReader::readMultiPoint () private
Definition at line 322 of file WKBReader.cpp.
References BAD_GEOM_TYPE_MSG, geos::geom::GeometryFactory::createMultiPoint(), dis, factory, readGeometry(), and geos::io::ByteOrderDataInStream::readInt().
Referenced by readGeometry().
 {
   int numGeoms = dis.readInt();
   vector<Geometry *> *geoms = new vector<Geometry *>(numGeoms);
   try {
     for (int i=0; i<numGeoms; i++)
     {
       Geometry *g = readGeometry();
       if (!dynamic_cast<Point *>(g))
       {
         stringstream err;
         err << BAD_GEOM_TYPE_MSG << " MultiPoint";
         throw ParseException(err.str());
       }
       (*geoms)[i] = g;
     }
   } catch (...) {
     for (unsigned int i=0; i<geoms->size(); i++)
       delete (*geoms)[i];
     delete geoms;
     throw;
   }
   return factory.createMultiPoint(geoms);
 }
MultiPolygon * geos::io::WKBReader::readMultiPolygon () private
Definition at line 376 of file WKBReader.cpp.
References BAD_GEOM_TYPE_MSG, geos::geom::GeometryFactory::createMultiPolygon(), dis, factory, readGeometry(), and geos::io::ByteOrderDataInStream::readInt().
Referenced by readGeometry().
 {
   int numGeoms = dis.readInt();
   vector<Geometry *> *geoms = new vector<Geometry *>(numGeoms);
   try {
     for (int i=0; i<numGeoms; i++)
     {
       Geometry *g = readGeometry();
       if (!dynamic_cast<Polygon *>(g))
       {
         stringstream err;
         err << BAD_GEOM_TYPE_MSG << " Polygon";
         throw  ParseException(err.str());
       }
       (*geoms)[i] = g;
     }
   } catch (...) {
     for (unsigned int i=0; i<geoms->size(); i++)
       delete (*geoms)[i];
     delete geoms;
     throw;
   }
   return factory.createMultiPolygon(geoms);
 }
Point * geos::io::WKBReader::readPoint () private
Definition at line 258 of file WKBReader.cpp.
References geos::geom::GeometryFactory::createPoint(), factory, inputDimension, ordValues, and readCoordinate().
Referenced by readGeometry().
 {
   readCoordinate();
   if(inputDimension == 3){
     return factory.createPoint(Coordinate(ordValues[0], ordValues[1], ordValues[2]));
   }else{
     return factory.createPoint(Coordinate(ordValues[0], ordValues[1]));
   }
 }
Polygon * geos::io::WKBReader::readPolygon () private
Definition at line 291 of file WKBReader.cpp.
References geos::geom::GeometryFactory::createPolygon(), dis, factory, geos::io::ByteOrderDataInStream::readInt(), and readLinearRing().
Referenced by readGeometry().
 {
   int numRings = dis.readInt();
 #if DEBUG_WKB_READER
   cout<<"WKB numRings: "<<numRings<<endl;
 #endif
         LinearRing *shell = nullptr;
         if( numRings > 0 )
             shell = readLinearRing();
   vector<Geometry *>*holes=nullptr;
   if ( numRings > 1 )
   {
     try {
       holes = new vector<Geometry *>(numRings-1);
       for (int i=0; i<numRings-1; i++)
         (*holes)[i] = (Geometry *)readLinearRing();
     } catch (...) {
       for (unsigned int i=0; i<holes->size(); i++)
         delete (*holes)[i];
       delete holes;
       delete shell;
       throw;
     }
   }
   return factory.createPolygon(shell, holes);
 }
Member Data Documentation
ByteOrderDataInStream geos::io::WKBReader::dis private
Definition at line 125 of file WKBReader.h.
Referenced by read(), readCoordinate(), readGeometry(), readGeometryCollection(), readLinearRing(), readLineString(), readMultiLineString(), readMultiPoint(), readMultiPolygon(), and readPolygon().
const geom::GeometryFactory& geos::io::WKBReader::factory private
Definition at line 120 of file WKBReader.h.
Referenced by readCoordinate(), readCoordinateSequence(), readGeometryCollection(), readLinearRing(), readLineString(), readMultiLineString(), readMultiPoint(), readMultiPolygon(), readPoint(), and readPolygon().
unsigned int geos::io::WKBReader::inputDimension private
Definition at line 123 of file WKBReader.h.
Referenced by readCoordinate(), readCoordinateSequence(), readGeometry(), and readPoint().
std::vector<double> geos::io::WKBReader::ordValues private
Definition at line 127 of file WKBReader.h.
Referenced by readCoordinate(), readCoordinateSequence(), readGeometry(), and readPoint().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/io/WKBReader.h
/home/vicky/potree/geos/vicky/src/io/WKBReader.cpp