GEOS: geos::noding::GeometryNoder Class Reference
geos::noding::GeometryNoder Class Reference
#include <GeometryNoder.h>
Public Member Functions
GeometryNoder (const geom::Geometry &g)
std::unique_ptr< geom::Geometry > getNoded ()
Static Public Member Functions
static std::unique_ptr< geom::Geometry > node (const geom::Geometry &geom)
Private Member Functions
Noder & getNoder ()
std::unique_ptr< geom::Geometry > toGeometry (SegmentString::NonConstVect &noded)
GeometryNoder (GeometryNoder const &)
GeometryNoder & operator= (GeometryNoder const &)
Static Private Member Functions
static void extractSegmentStrings (const geom::Geometry &g, SegmentString::NonConstVect &to)
Private Attributes
const geom::Geometry & argGeom
SegmentString::NonConstVect lineList
std::unique_ptr< Noder > noder
Detailed Description
Definition at line 40 of file GeometryNoder.h.
Constructor & Destructor Documentation
geos::noding::GeometryNoder::GeometryNoder (const geom::Geometry & g)
Definition at line 84 of file GeometryNoder.cpp.
   :
   argGeom(g)
 {
 }
geos::noding::GeometryNoder::GeometryNoder (GeometryNoder const &) private
Member Function Documentation
void geos::noding::GeometryNoder::extractSegmentStrings (const geom::Geometry & g, SegmentString::NonConstVect & to) static private
Definition at line 153 of file GeometryNoder.cpp.
References geos::geom::Geometry::apply_ro().
Referenced by getNoded().
 {
   SegmentStringExtractor ex(to);
   g.apply_ro(&ex);
 }
std::unique_ptr< geom::Geometry > geos::noding::GeometryNoder::getNoded ()
Definition at line 120 of file GeometryNoder.cpp.
References argGeom, geos::noding::Noder::computeNodes(), extractSegmentStrings(), geos::noding::Noder::getNodedSubstrings(), getNoder(), lineList, noder, and toGeometry().
Referenced by node().
 {
   SegmentString::NonConstVect lineList;
   extractSegmentStrings(argGeom, lineList);
   Noder& noder = getNoder();
   SegmentString::NonConstVect* nodedEdges = nullptr;
   try {
     noder.computeNodes( &lineList );
     nodedEdges = noder.getNodedSubstrings();
   }
   catch (const std::exception& ex)
   {
     for (size_t i=0, n=lineList.size(); i<n; ++i)
       delete lineList[i];
     throw ex;
   }
   std::unique_ptr<geom::Geometry> noded = toGeometry(*nodedEdges);
   for (auto &elem : (*nodedEdges))
     delete elem;
   delete nodedEdges;
   for (auto &elem : lineList)
     delete elem;
   return noded;
 }
Noder & geos::noding::GeometryNoder::getNoder () private
Definition at line 162 of file GeometryNoder.cpp.
References argGeom, geos::geom::Geometry::getFactory(), geos::geom::GeometryFactory::getPrecisionModel(), and noder.
Referenced by getNoded().
 {
   if ( ! noder.get() )
   {
     const geom::PrecisionModel *pm = argGeom.getFactory()->getPrecisionModel();
 #if 0
     using algorithm::LineIntersector;
     LineIntersector li;
     IntersectionAdder intersectionAdder(li);
     noder.reset( new MCIndexNoder(&intersectionAdder) );
 #else
     IteratedNoder* in = new IteratedNoder(pm);
     //in->setMaximumIterations(0);
     noder.reset( in );
     //using snapround::SimpleSnapRounder;
     //noder.reset( new SimpleSnapRounder(*pm) );
     //using snapround::MCIndexSnapRounder;
     //noder.reset( new MCIndexSnapRounder(*pm) );
 #endif
   }
   return *noder;
 }
std::unique_ptr< geom::Geometry > geos::noding::GeometryNoder::node (const geom::Geometry & geom) static
Definition at line 77 of file GeometryNoder.cpp.
References getNoded().
Referenced by GEOSNode_r().
 {
   GeometryNoder noder(geom);
   return noder.getNoded();
 }
GeometryNoder& geos::noding::GeometryNoder::operator= (GeometryNoder const &) private
std::unique_ptr< geom::Geometry > geos::noding::GeometryNoder::toGeometry (SegmentString::NonConstVect & noded) private
Definition at line 92 of file GeometryNoder.cpp.
References argGeom, geos::geom::CoordinateSequence::clone(), geos::geom::GeometryFactory::createLineString(), geos::geom::GeometryFactory::createMultiLineString(), and geos::geom::Geometry::getFactory().
Referenced by getNoded().
 {
   const geom::GeometryFactory *geomFact = argGeom.getFactory();
   std::set< OrientedCoordinateArray > ocas;
   // Create a geometry out of the noded substrings.
   std::vector< geom::Geometry* >* lines = new std::vector< geom::Geometry * >();
   lines->reserve(nodedEdges.size());
   for (auto &ss :  nodedEdges)
   {
     const geom::CoordinateSequence* coords = ss->getCoordinates();
     // Check if an equivalent edge is known
     OrientedCoordinateArray oca1( *coords );
     if ( ocas.insert(oca1).second ) {
       geom::Geometry* tmp = geomFact->createLineString( coords->clone() );
       lines->push_back( tmp );
     }
   }
   std::unique_ptr<geom::Geometry> noded ( geomFact->createMultiLineString( lines ) );
   return noded;
 }
Member Data Documentation
const geom::Geometry& geos::noding::GeometryNoder::argGeom private
Definition at line 52 of file GeometryNoder.h.
Referenced by getNoded(), getNoder(), and toGeometry().
SegmentString::NonConstVect geos::noding::GeometryNoder::lineList private
Definition at line 54 of file GeometryNoder.h.
Referenced by getNoded().
std::unique_ptr<Noder> geos::noding::GeometryNoder::noder private
Definition at line 61 of file GeometryNoder.h.
Referenced by getNoded(), and getNoder().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/GeometryNoder.h
/home/vicky/potree/geos/vicky/src/noding/GeometryNoder.cpp