GEOS: geos::operation::geounion::GeometryListHolder Class Reference
geos::operation::geounion::GeometryListHolder Class Reference
Helper class holding Geometries, part of which are held by reference others are held exclusively.
#include <GeometryListHolder.h>
Public Member Functions
GeometryListHolder ()
~GeometryListHolder ()
void push_back_owned (geom::Geometry *item)
geom::Geometry * getGeometry (std::size_t index)
Private Types
typedef std::vector< geom::Geometry * > base_type
Static Private Member Functions
static void deleteItem (geom::Geometry *item)
Private Attributes
std::vector< geom::Geometry * > ownedItems
Detailed Description
Helper class holding Geometries, part of which are held by reference others are held exclusively.
Definition at line 34 of file GeometryListHolder.h.
Member Typedef Documentation
typedef std::vector<geom::Geometry*> geos::operation::geounion::GeometryListHolder::base_type private
Definition at line 37 of file GeometryListHolder.h.
Constructor & Destructor Documentation
geos::operation::geounion::GeometryListHolder::GeometryListHolder () inline
Definition at line 40 of file GeometryListHolder.h.
Referenced by geos::operation::geounion::CascadedPolygonUnion::reduceToGeometries().
 {}
geos::operation::geounion::GeometryListHolder::~GeometryListHolder () inline
Definition at line 41 of file GeometryListHolder.h.
     {
         std::for_each(ownedItems.begin(), ownedItems.end(),
             &GeometryListHolder::deleteItem);
     }
Member Function Documentation
void geos::operation::geounion::GeometryListHolder::deleteItem (geom::Geometry * item) static private
Definition at line 102 of file CascadedPolygonUnion.cpp.
 {
     delete item;
 }
geom::Geometry* geos::operation::geounion::GeometryListHolder::getGeometry (std::size_t index) inline
Definition at line 54 of file GeometryListHolder.h.
Referenced by geos::operation::geounion::CascadedUnion::binaryUnion(), and geos::operation::geounion::CascadedPolygonUnion::binaryUnion().
     {
       if (index >= this->base_type::size())
           return nullptr;
       return (*this)[index];
     }
void geos::operation::geounion::GeometryListHolder::push_back_owned (geom::Geometry * item) inline
Definition at line 48 of file GeometryListHolder.h.
     {
         this->base_type::push_back(item);
         ownedItems.push_back(item);
     }
Member Data Documentation
std::vector<geom::Geometry*> geos::operation::geounion::GeometryListHolder::ownedItems private
Definition at line 65 of file GeometryListHolder.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/union/GeometryListHolder.h
/home/vicky/potree/geos/vicky/src/operation/union/CascadedPolygonUnion.cpp