GEOS: geos::operation::valid::ConnectedInteriorTester Class Reference
geos::operation::valid::ConnectedInteriorTester Class Reference
This class tests that the interior of an area Geometry (Polygon or MultiPolygon) is connected.
#include <ConnectedInteriorTester.h>
Public Member Functions
ConnectedInteriorTester (geomgraph::GeometryGraph &newGeomGraph)
~ConnectedInteriorTester ()
geom::Coordinate & getCoordinate ()
bool isInteriorsConnected ()
Static Public Member Functions
static const geom::Coordinate & findDifferentPoint (const geom::CoordinateSequence *coord, const geom::Coordinate &pt)
Protected Member Functions
void visitLinkedDirectedEdges (geomgraph::DirectedEdge *start)
Private Member Functions
void setInteriorEdgesInResult (geomgraph::PlanarGraph &graph)
void buildEdgeRings (std::vector< geomgraph::EdgeEnd * > *dirEdges, std::vector< geomgraph::EdgeRing * > &minEdgeRings)
Form DirectedEdges in graph into Minimal EdgeRings.
void visitShellInteriors (const geom::Geometry *g, geomgraph::PlanarGraph &graph)
void visitInteriorRing (const geom::LineString *ring, geomgraph::PlanarGraph &graph)
bool hasUnvisitedShellEdge (std::vector< geomgraph::EdgeRing * > *edgeRings)
ConnectedInteriorTester (const ConnectedInteriorTester &other)=delete
ConnectedInteriorTester & operator= (const ConnectedInteriorTester &rhs)=delete
Private Attributes
geom::GeometryFactory::Ptr geometryFactory
geomgraph::GeometryGraph & geomGraph
geom::Coordinate disconnectedRingcoord
std::vector< geomgraph::EdgeRing * > maximalEdgeRings
Used to track MaximalEdgeRings allocations.
Detailed Description
This class tests that the interior of an area Geometry (Polygon or MultiPolygon) is connected.
An area Geometry is invalid if the interior is disconnected. This can happen if:
one or more holes either form a chain touching the shell at two places
one or more holes form a ring around a portion of the interior
If an inconsistency if found the location of the problem is recorded.
Definition at line 71 of file ConnectedInteriorTester.h.
Constructor & Destructor Documentation
geos::operation::valid::ConnectedInteriorTester::ConnectedInteriorTester (geomgraph::GeometryGraph & newGeomGraph)
Definition at line 71 of file ConnectedInteriorTester.cpp.
                                                                            :
   geometryFactory(GeometryFactory::create()),
   geomGraph(newGeomGraph),
   disconnectedRingcoord()
 {
 }
geos::operation::valid::ConnectedInteriorTester::~ConnectedInteriorTester ()
Definition at line 78 of file ConnectedInteriorTester.cpp.
 {
 }
geos::operation::valid::ConnectedInteriorTester::ConnectedInteriorTester (const ConnectedInteriorTester & other) private delete
Member Function Documentation
void geos::operation::valid::ConnectedInteriorTester::buildEdgeRings (std::vector< geomgraph::EdgeEnd * > * dirEdges, std::vector< geomgraph::EdgeRing * > & minEdgeRings) private
Form DirectedEdges in graph into Minimal EdgeRings.
Minimal Edgerings must be used, because only they are guaranteed to provide a correct isHole computation.
Parameters
minEdgeRings : newly allocated minimal edge rings will be push_back'ed here. deletion responsibility is left to caller.
Definition at line 196 of file ConnectedInteriorTester.cpp.
References geos::operation::overlay::MaximalEdgeRing::buildMinimalRings(), geometryFactory, geos::geomgraph::DirectedEdge::getEdgeRing(), geos::geomgraph::DirectedEdge::isInResult(), geos::operation::overlay::MaximalEdgeRing::linkDirectedEdgesForMinimalEdgeRings(), maximalEdgeRings, and geos::geomgraph::DirectedEdge::print().
Referenced by isInteriorsConnected().
 {
 #if GEOS_DEBUG
   cerr << __FUNCTION__ << " got " << dirEdges->size() << " EdgeEnd vector" << endl;
 #endif
   typedef std::vector<EdgeEnd*> EdgeEnds;
   //std::vector<MinimalEdgeRing*> minEdgeRings;
   for(EdgeEnds::size_type i=0, n=dirEdges->size(); i<n; ++i)
   {
 #ifdef GEOS_CAST_PARANOIA
     assert(dynamic_cast<DirectedEdge*>((*dirEdges)[i]));
 #endif
     DirectedEdge *de=static_cast<DirectedEdge*>((*dirEdges)[i]);
 #if GEOS_DEBUG
     cerr << "DirectedEdge " << i << ": " << de->print() << endl;
 #endif
     // if this edge has not yet been processed
     if(de->isInResult() && de->getEdgeRing()==nullptr)
     {
       MaximalEdgeRing* er = new MaximalEdgeRing(de,
                                          geometryFactory.get());
       // We track MaximalEdgeRings allocations
       // using the private maximalEdgeRings vector
       maximalEdgeRings.push_back(er);
       er->linkDirectedEdgesForMinimalEdgeRings();
       er->buildMinimalRings(minEdgeRings);
     }
   }
 /*
   std::vector<EdgeRing*> *edgeRings=new std::vector<EdgeRing*>();
   edgeRings->assign(minEdgeRings.begin(), minEdgeRings.end());
   return edgeRings;
 */
 }
const Coordinate & geos::operation::valid::ConnectedInteriorTester::findDifferentPoint (const geom::CoordinateSequence * coord, const geom::Coordinate & pt) static
Definition at line 89 of file ConnectedInteriorTester.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
Referenced by visitInteriorRing().
 {
   assert(coord);
   size_t npts=coord->getSize();
   for(size_t i=0; i<npts; ++i)
   {
     if(!(coord->getAt(i)==pt))
       return coord->getAt(i);
   }
   return Coordinate::getNull();
 }
Coordinate & geos::operation::valid::ConnectedInteriorTester::getCoordinate ()
Definition at line 83 of file ConnectedInteriorTester.cpp.
References disconnectedRingcoord.
Referenced by geos::operation::valid::IsValidOp::checkConnectedInteriors().
 {
   return disconnectedRingcoord;
 }
bool geos::operation::valid::ConnectedInteriorTester::hasUnvisitedShellEdge (std::vector< geomgraph::EdgeRing * > * edgeRings) private
Check if any shell ring has an unvisited edge. A shell ring is a ring which is not a hole and which has the interior of the parent area on the RHS. (Note that there may be non-hole rings with the interior on the LHS, since the interior of holes will also be polygonized into CW rings by the linkAllDirectedEdges() step)
Returns
true if there is an unvisited edge in a non-hole ring
Definition at line 303 of file ConnectedInteriorTester.cpp.
References disconnectedRingcoord, geos::geomgraph::EdgeEnd::getCoordinate(), geos::geomgraph::EdgeRing::getEdges(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::EdgeRing::isHole(), and geos::geomgraph::DirectedEdge::isVisited().
Referenced by isInteriorsConnected().
 {
 #if GEOS_DEBUG
   cerr << "hasUnvisitedShellEdge called with " << edgeRings->size() << " edgeRings." << endl;
 #endif
   for(std::vector<EdgeRing*>::iterator
     it=edgeRings->begin(), itEnd=edgeRings->end();
     it != itEnd;
     ++it)
   {
     EdgeRing *er=*it;
     assert(er);
     // don't check hole rings
     if (er->isHole()) continue;
     std::vector<DirectedEdge*>& edges=er->getEdges();
     DirectedEdge *de=edges[0];
     assert(de);
     // don't check CW rings which are holes
     // (MD - this check may now be irrelevant - 2006-03-09)
     if (de->getLabel().getLocation(0, Position::RIGHT) != Location::INTERIOR) continue;
     /*
      * the edgeRing is CW ring which surrounds the INT
      * of the area, so check all edges have been visited.
      * If any are unvisited, this is a disconnected part
      * of the interior
      */
     for(std::vector<DirectedEdge*>::iterator
       jt=edges.begin(), jtEnd=edges.end();
       jt != jtEnd;
       ++jt)
     {
       de=*jt;
       assert(de);
       //Debug.print("visted? "); Debug.println(de);
       if (!de->isVisited()) {
         //Debug.print("not visited "); Debug.println(de);
         disconnectedRingcoord=de->getCoordinate();
         return true;
       }
     }
   }
   return false;
 }
bool geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected ()
Definition at line 104 of file ConnectedInteriorTester.cpp.
References geos::geomgraph::PlanarGraph::addEdges(), buildEdgeRings(), geos::geomgraph::GeometryGraph::computeSplitEdges(), geomGraph, geos::geomgraph::PlanarGraph::getEdgeEnds(), geos::geomgraph::GeometryGraph::getGeometry(), hasUnvisitedShellEdge(), geos::operation::overlay::OverlayNodeFactory::instance(), geos::geomgraph::PlanarGraph::linkResultDirectedEdges(), maximalEdgeRings, setInteriorEdgesInResult(), and visitShellInteriors().
Referenced by geos::operation::valid::IsValidOp::checkConnectedInteriors().
 {
   // node the edges, in case holes touch the shell
   std::vector<Edge*> splitEdges;
   geomGraph.computeSplitEdges(&splitEdges);
   // form the edges into rings
   PlanarGraph graph(operation::overlay::OverlayNodeFactory::instance());
   graph.addEdges(splitEdges);
   setInteriorEdgesInResult(graph);
   graph.linkResultDirectedEdges();
   std::vector<EdgeRing*> edgeRings;
   buildEdgeRings(graph.getEdgeEnds(), edgeRings);
 #if GEOS_DEBUG
   cerr << "buildEdgeRings constructed " << edgeRings.size() << " edgeRings." << endl;
 #endif
   /*
    * Mark all the edges for the edgeRings corresponding to the shells
    * of the input polygons.
    *
    * Only ONE ring gets marked for each shell - if there are others
    * which remain unmarked this indicates a disconnected interior.
    */
   visitShellInteriors(geomGraph.getGeometry(), graph);
 #if GEOS_DEBUG
   cerr << "after visitShellInteriors edgeRings are " << edgeRings.size() << " edgeRings." << endl;
 #endif
   /*
    * If there are any unvisited shell edges
    * (i.e. a ring which is not a hole and which has the interior
    * of the parent area on the RHS)
    * this means that one or more holes must have split the interior of the
    * polygon into at least two pieces.  The polygon is thus invalid.
    */
   bool res=!hasUnvisitedShellEdge(&edgeRings);
 #if GEOS_DEBUG
   cerr << "releasing " << edgeRings.size() << " edgeRings." << endl;
 #endif
   // Release memory allocated by buildEdgeRings
   for(size_t i=0, n=edgeRings.size(); i<n; ++i)
   {
     EdgeRing* er = edgeRings[i];
 #if GEOS_DEBUG
     cerr<<*er<<endl;
 #endif
     assert(er);
     delete er;
 #if GEOS_DEBUG
   cerr << "releasing edgeRing at " << er << endl;
 #endif
   }
   edgeRings.clear();
   // Release memory allocated by MaximalEdgeRings
   // There should be no more references to this object
   // how to check this ? boost::shared_ptr<> comes to mind.
   //
   for (size_t i=0, n=maximalEdgeRings.size(); i<n; i++)
   {
     delete maximalEdgeRings[i];
   }
   maximalEdgeRings.clear();
   return res;
 }
ConnectedInteriorTester& geos::operation::valid::ConnectedInteriorTester::operator= (const ConnectedInteriorTester & rhs) private delete
void geos::operation::valid::ConnectedInteriorTester::setInteriorEdgesInResult (geomgraph::PlanarGraph & graph) private
Definition at line 179 of file ConnectedInteriorTester.cpp.
References geos::geomgraph::PlanarGraph::getEdgeEnds(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), and geos::geomgraph::DirectedEdge::setInResult().
Referenced by isInteriorsConnected().
 {
   std::vector<EdgeEnd*> *ee=graph.getEdgeEnds();
   for(size_t i=0, n=ee->size(); i<n; ++i)
   {
     // Unexpected non DirectedEdge in graphEdgeEnds
     assert(dynamic_cast<DirectedEdge*>((*ee)[i]));
     DirectedEdge *de=static_cast<DirectedEdge*>((*ee)[i]);
     if ( de->getLabel().getLocation(0, Position::RIGHT) == Location::INTERIOR)
     {
       de->setInResult(true);
     }
   }
 }
void geos::operation::valid::ConnectedInteriorTester::visitInteriorRing (const geom::LineString * ring, geomgraph::PlanarGraph & graph) private
Find first point in coord list different to initial point. Need special check since the first point may be repeated.
Definition at line 259 of file ConnectedInteriorTester.cpp.
References findDifferentPoint(), geos::geomgraph::PlanarGraph::findEdgeEnd(), geos::geomgraph::PlanarGraph::findEdgeInSameDirection(), geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geomgraph::EdgeEnd::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::DirectedEdge::getSym(), geos::geom::LineString::isEmpty(), and visitLinkedDirectedEdges().
Referenced by visitShellInteriors().
 {
   // can't visit an empty ring
   if(ring->isEmpty()) return;
   const CoordinateSequence *pts=ring->getCoordinatesRO();
   const Coordinate& pt0=pts->getAt(0);
       const Coordinate& pt1=findDifferentPoint(pts, pt0);
   Edge *e=graph.findEdgeInSameDirection(pt0, pt1);
   DirectedEdge *de=static_cast<DirectedEdge*>(graph.findEdgeEnd(e));
   DirectedEdge *intDe=nullptr;
   if (de->getLabel().getLocation(0,Position::RIGHT)==Location::INTERIOR) {
     intDe=de;
   } else if (de->getSym()->getLabel().getLocation(0,Position::RIGHT)==Location::INTERIOR) {
     intDe=de->getSym();
   }
   assert(intDe!=nullptr); // unable to find dirEdge with Interior on RHS
   visitLinkedDirectedEdges(intDe);
 }
void geos::operation::valid::ConnectedInteriorTester::visitLinkedDirectedEdges (geomgraph::DirectedEdge * start) protected
Definition at line 286 of file ConnectedInteriorTester.cpp.
References geos::geomgraph::DirectedEdge::getNext(), and geos::geomgraph::DirectedEdge::setVisited().
Referenced by visitInteriorRing().
 {
   DirectedEdge *startDe=start;
   DirectedEdge *de=start;
   //Debug.println(de);
   do {
     // found null Directed Edge
     assert(de!=nullptr);
     de->setVisited(true);
     de=de->getNext();
     //Debug.println(de);
   } while (de!=startDe);
 }
void geos::operation::valid::ConnectedInteriorTester::visitShellInteriors (const geom::Geometry * g, geomgraph::PlanarGraph & graph) private
Mark all the edges for the edgeRings corresponding to the shells of the input polygons. Note only ONE ring gets marked for each shell.
Definition at line 242 of file ConnectedInteriorTester.cpp.
References geos::geom::Polygon::getExteriorRing(), and visitInteriorRing().
Referenced by isInteriorsConnected().
 {
   if (const Polygon* p=dynamic_cast<const Polygon*>(g))
   {
     visitInteriorRing(p->getExteriorRing(), graph);
   }
   if (const MultiPolygon* mp=dynamic_cast<const MultiPolygon*>(g))
   {
     for (size_t i=0, n=mp->getNumGeometries(); i<n; i++) {
       const Polygon *p=dynamic_cast<const Polygon*>(mp->getGeometryN(i));
       visitInteriorRing(p->getExteriorRing(), graph);
     }
   }
 }
Member Data Documentation
geom::Coordinate geos::operation::valid::ConnectedInteriorTester::disconnectedRingcoord private
Save a coordinate for any disconnected interior found the coordinate will be somewhere on the ring surrounding the disconnected interior
Definition at line 94 of file ConnectedInteriorTester.h.
Referenced by getCoordinate(), and hasUnvisitedShellEdge().
geom::GeometryFactory::Ptr geos::operation::valid::ConnectedInteriorTester::geometryFactory private
Definition at line 87 of file ConnectedInteriorTester.h.
Referenced by buildEdgeRings().
geomgraph::GeometryGraph& geos::operation::valid::ConnectedInteriorTester::geomGraph private
Definition at line 89 of file ConnectedInteriorTester.h.
Referenced by isInteriorsConnected().
std::vector<geomgraph::EdgeRing*> geos::operation::valid::ConnectedInteriorTester::maximalEdgeRings private
Used to track MaximalEdgeRings allocations.
Definition at line 97 of file ConnectedInteriorTester.h.
Referenced by buildEdgeRings(), and isInteriorsConnected().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/valid/ConnectedInteriorTester.h
/home/vicky/potree/geos/vicky/src/operation/valid/ConnectedInteriorTester.cpp