GEOS: geos::operation::polygonize::PolygonizeEdge Class Reference
geos::operation::polygonize::PolygonizeEdge Class Reference
#include <PolygonizeEdge.h>
Public Types
typedef std::set< const Edge * > ConstSet
Set of const Edges pointers.
typedef std::set< Edge * > NonConstSet
Set of non-const Edges pointers.
typedef std::vector< Edge * > NonConstVect
Vector of non-const Edges pointers.
typedef std::vector< const Edge * > ConstVect
Vector of const Edges pointers.
Public Member Functions
PolygonizeEdge (const geom::LineString *newLine)
const geom::LineString * getLine () const
void setDirectedEdges (DirectedEdge *de0, DirectedEdge *de1)
Initializes this Edge's two DirectedEdges.
DirectedEdge * getDirEdge (int i)
Returns one of the DirectedEdges associated with this Edge.
DirectedEdge * getDirEdge (Node *fromNode)
Returns the DirectedEdge that starts from the given node, or null if the node is not one of the two nodes associated with this Edge.
Node * getOppositeNode (Node *node)
If node is one of the two nodes associated with this Edge, returns the other node; otherwise returns null.
virtual bool isVisited () const
Tests if a component has been visited during the course of a graph algorithm.
virtual void setVisited (bool isVisited)
Sets the visited flag for this component.
virtual void setMarked (bool isMarked)
Sets the marked flag for this component.
virtual bool isMarked () const
Tests if a component has been marked at some point during the processing involving this graph.
Static Public Member Functions
template<typename T >
static void setVisited (T start, T end, bool visited)
Sets the Visited state for the elements of a container, from start to end iterator.
template<typename T >
static void setVisitedMap (T start, T end, bool visited)
Sets the Visited state for the values of each map container element, from start to end iterator.
template<typename T >
static void setMarked (T start, T end, bool marked)
Sets the Marked state for the elements of a container, from start to end iterator.
template<typename T >
static void setMarkedMap (T start, T end, bool marked)
Sets the Marked state for the values of each map container element, from start to end iterator.
Protected Attributes
std::vector< DirectedEdge * > dirEdge
The two DirectedEdges associated with this Edge.
bool isMarkedVar
Variable holding ''marked'' status.
bool isVisitedVar
Variable holding ''visited'' status.
Private Attributes
const geom::LineString * line
Detailed Description
Definition at line 44 of file PolygonizeEdge.h.
Member Typedef Documentation
typedef std::set<const Edge *> geos::planargraph::Edge::ConstSet inherited
Set of const Edges pointers.
Definition at line 61 of file Edge.h.
typedef std::vector<const Edge *> geos::planargraph::Edge::ConstVect inherited
Vector of const Edges pointers.
Definition at line 70 of file Edge.h.
typedef std::set<Edge *> geos::planargraph::Edge::NonConstSet inherited
Set of non-const Edges pointers.
Definition at line 64 of file Edge.h.
typedef std::vector<Edge *> geos::planargraph::Edge::NonConstVect inherited
Vector of non-const Edges pointers.
Definition at line 67 of file Edge.h.
Constructor & Destructor Documentation
geos::operation::polygonize::PolygonizeEdge::PolygonizeEdge (const geom::LineString * newLine)
Definition at line 29 of file PolygonizeEdge.cpp.
                                                         :
   line(newLine) {
 }
Member Function Documentation
DirectedEdge * geos::planargraph::Edge::getDirEdge (int i) inherited
Returns one of the DirectedEdges associated with this Edge.
Parameters
i 0 or 1
Returns one of the DirectedEdges associated with this Edge.
Parameters
i 0 or 1
Definition at line 49 of file Edge.cpp.
References geos::planargraph::Edge::dirEdge.
Referenced by geos::planargraph::Subgraph::add(), geos::planargraph::PlanarGraph::add(), geos::planargraph::algorithm::ConnectedSubgraphFinder::getConnectedSubgraphs(), and geos::planargraph::PlanarGraph::remove().
 {
   return dirEdge[i];
 }
DirectedEdge * geos::planargraph::Edge::getDirEdge (Node * fromNode) inherited
Returns the DirectedEdge that starts from the given node, or null if the node is not one of the two nodes associated with this Edge.
Definition at line 59 of file Edge.cpp.
References geos::planargraph::Edge::dirEdge.
 {
   if (dirEdge[0]->getFromNode()==fromNode) return dirEdge[0];
   if (dirEdge[1]->getFromNode()==fromNode) return dirEdge[1];
   // node not found
   // possibly should throw an exception here?
   return nullptr;
 }
const LineString * geos::operation::polygonize::PolygonizeEdge::getLine () const
Definition at line 34 of file PolygonizeEdge.cpp.
References line.
Referenced by geos::operation::polygonize::EdgeRing::getCoordinates().
{
   return line;
 }
Node * geos::planargraph::Edge::getOppositeNode (Node * node) inherited
If node is one of the two nodes associated with this Edge, returns the other node; otherwise returns null.
If node is one of the two nodes associated with this Edge, returns the other node; otherwise returns null.
Definition at line 73 of file Edge.cpp.
References geos::planargraph::Edge::dirEdge.
 {
   if (dirEdge[0]->getFromNode()==node) return dirEdge[0]->getToNode();
   if (dirEdge[1]->getFromNode()==node) return dirEdge[1]->getToNode();
   // node not found
   // possibly should throw an exception here?
   return nullptr;
 }
virtual bool geos::planargraph::GraphComponent::isMarked () const inline virtual inherited
Tests if a component has been marked at some point during the processing involving this graph.
Returns
true if the component has been marked
Definition at line 146 of file GraphComponent.h.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsStartingAt(), and geos::planargraph::operator<<().
 { return isMarkedVar; }
virtual bool geos::planargraph::GraphComponent::isVisited () const inline virtual inherited
Tests if a component has been visited during the course of a graph algorithm.
Returns
true if the component has been visited
Definition at line 72 of file GraphComponent.h.
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges(), geos::planargraph::algorithm::ConnectedSubgraphFinder::getConnectedSubgraphs(), and geos::planargraph::operator<<().
 { return isVisitedVar; }
void geos::planargraph::Edge::setDirectedEdges (DirectedEdge * de0, DirectedEdge * de1) inherited
Initializes this Edge's two DirectedEdges.
For each DirectedEdge: sets the Edge, sets the symmetric DirectedEdge, and adds this Edge to its from-Node.
Definition at line 32 of file Edge.cpp.
References geos::planargraph::Node::addOutEdge(), geos::planargraph::Edge::dirEdge, geos::planargraph::DirectedEdge::getFromNode(), geos::planargraph::DirectedEdge::setEdge(), and geos::planargraph::DirectedEdge::setSym().
Referenced by geos::operation::linemerge::LineMergeGraph::addEdge(), and geos::operation::polygonize::PolygonizeGraph::addEdge().
 {
   dirEdge.push_back(de0);
   dirEdge.push_back(de1);
   de0->setEdge(this);
   de1->setEdge(this);
   de0->setSym(de1);
   de1->setSym(de0);
   de0->getFromNode()->addOutEdge(de0);
   de1->getFromNode()->addOutEdge(de1);
 }
template<typename T > static void geos::planargraph::GraphComponent::setMarked (T start, T end, bool marked) inline static inherited
Sets the Marked state for the elements of a container, from start to end iterator.
Parameters
start the start element
end one past the last element
marked the state to set the marked flag to
Definition at line 119 of file GraphComponent.h.
Referenced by geos::operation::linemerge::LineMerger::buildEdgeStringsForNonDegree2Nodes(), geos::operation::linemerge::LineMerger::buildEdgeStringsForUnprocessedNodes(), geos::operation::linemerge::LineMerger::buildEdgeStringStartingWith(), geos::operation::polygonize::PolygonizeGraph::deleteAllEdges(), and geos::operation::polygonize::PolygonizeGraph::deleteCutEdges().
{
     for(T i=start; i!=end; ++i) {
       (*i)->setMarked(marked);
     }
   }
virtual void geos::planargraph::GraphComponent::setMarked (bool isMarked) inline virtual inherited
Sets the marked flag for this component.
Parameters
isMarked the desired value of the marked flag
Definition at line 152 of file GraphComponent.h.
 { isMarkedVar=isMarked; }
template<typename T > static void geos::planargraph::GraphComponent::setMarkedMap (T start, T end, bool marked) inline static inherited
Sets the Marked state for the values of each map container element, from start to end iterator.
Parameters
start the start element
end one past the last element
marked the state to set the visited flag to
Definition at line 135 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       i->second->setMarked(marked);
     }
   }
virtual void geos::planargraph::GraphComponent::setVisited (bool isVisited) inline virtual inherited
Sets the visited flag for this component.
Parameters
isVisited the desired value of the visited flag
Definition at line 78 of file GraphComponent.h.
Referenced by geos::planargraph::algorithm::ConnectedSubgraphFinder::addEdges(), and geos::operation::linemerge::LineSequencer::addReverseSubpath().
 { isVisitedVar=isVisited; }
template<typename T > static void geos::planargraph::GraphComponent::setVisited (T start, T end, bool visited) inline static inherited
Sets the Visited state for the elements of a container, from start to end iterator.
Parameters
start the start element
end one past the last element
visited the state to set the visited flag to
Definition at line 89 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       (*i)->setVisited(visited);
     }
   }
template<typename T > static void geos::planargraph::GraphComponent::setVisitedMap (T start, T end, bool visited) inline static inherited
Sets the Visited state for the values of each map container element, from start to end iterator.
Parameters
start the start element
end one past the last element
visited the state to set the visited flag to
Definition at line 104 of file GraphComponent.h.
{
     for(T i=start; i!=end; ++i) {
       i->second->setVisited(visited);
     }
   }
Member Data Documentation
std::vector<DirectedEdge*> geos::planargraph::Edge::dirEdge protected inherited
The two DirectedEdges associated with this Edge.
Definition at line 75 of file Edge.h.
Referenced by geos::planargraph::Edge::getDirEdge(), geos::planargraph::Edge::getOppositeNode(), and geos::planargraph::Edge::setDirectedEdges().
bool geos::planargraph::GraphComponent::isMarkedVar protected inherited
Variable holding ''marked'' status.
Definition at line 51 of file GraphComponent.h.
bool geos::planargraph::GraphComponent::isVisitedVar protected inherited
Variable holding ''visited'' status.
Definition at line 54 of file GraphComponent.h.
const geom::LineString* geos::operation::polygonize::PolygonizeEdge::line private
Definition at line 47 of file PolygonizeEdge.h.
Referenced by getLine().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/polygonize/PolygonizeEdge.h
/home/vicky/potree/geos/vicky/src/operation/polygonize/PolygonizeEdge.cpp