GEOS: geos::noding::NodedSegmentString Class Reference
geos::noding::NodedSegmentString Class Reference
Represents a list of contiguous line segments, and supports noding the segments.
#include <NodedSegmentString.h>
Public Types
typedef std::vector< const SegmentString * > ConstVect
typedef std::vector< SegmentString * > NonConstVect
Public Member Functions
NodedSegmentString (geom::CoordinateSequence *newPts, const void *newContext)
~NodedSegmentString () override
SegmentNode * addIntersectionNode (geom::Coordinate *intPt, std::size_t segmentIndex)
SegmentNodeList & getNodeList ()
const SegmentNodeList & getNodeList () const
unsigned int size () const override
const geom::Coordinate & getCoordinate (unsigned int i) const override
geom::CoordinateSequence * getCoordinates () const override
Return a pointer to the CoordinateSequence associated with this SegmentString.
bool isClosed () const override
std::ostream & print (std::ostream &os) const override
int getSegmentOctant (unsigned int index) const
Gets the octant of the segment starting at vertex index.
void addIntersections (algorithm::LineIntersector *li, unsigned int segmentIndex, int geomIndex)
Add {SegmentNode}s for one or both intersections found for a segment of an edge to the edge intersection list.
void addIntersection (algorithm::LineIntersector *li, unsigned int segmentIndex, int geomIndex, int intIndex)
Add an SegmentNode for intersection intIndex.
void addIntersection (const geom::Coordinate &intPt, unsigned int segmentIndex)
Add an SegmentNode for intersection intIndex.
const void * getData () const
void setData (const void *data)
Static Public Member Functions
template<class II >
static void getNodedSubstrings (II from, II too_far, SegmentString::NonConstVect *resultEdgelist)
template<class C >
static void getNodedSubstrings (C *segStrings, SegmentString::NonConstVect *resultEdgelist)
static void getNodedSubstrings (const SegmentString::NonConstVect &segStrings, SegmentString::NonConstVect *resultEdgeList)
static SegmentString::NonConstVect * getNodedSubstrings (const SegmentString::NonConstVect &segStrings)
Returns allocated object.
Static Private Member Functions
static int safeOctant (const geom::Coordinate &p0, const geom::Coordinate &p1)
Private Attributes
SegmentNodeList nodeList
geom::CoordinateSequence * pts
Detailed Description
Represents a list of contiguous line segments, and supports noding the segments.
The line segments are represented by an array of Coordinates. Intended to optimize the noding of contiguous segments by reducing the number of allocated objects. SegmentStrings can carry a context object, which is useful for preserving topological or parentage information. All noded substrings are initialized with the same context object.
Definition at line 57 of file NodedSegmentString.h.
Member Typedef Documentation
typedef std::vector<const SegmentString*> geos::noding::SegmentString::ConstVect inherited
Definition at line 48 of file SegmentString.h.
typedef std::vector<SegmentString *> geos::noding::SegmentString::NonConstVect inherited
Definition at line 49 of file SegmentString.h.
Constructor & Destructor Documentation
geos::noding::NodedSegmentString::NodedSegmentString (geom::CoordinateSequence * newPts, const void * newContext) inline
Creates a new segment string from a list of vertices.
Parameters
newPts CoordinateSequence representing the string, ownership transferred.
data the user-defined data of this segment string (may be null)
Definition at line 98 of file NodedSegmentString.h.
         : NodableSegmentString(newContext)
         , nodeList(this)
         , pts(newPts)
     {}
geos::noding::NodedSegmentString::~NodedSegmentString () inline override
Definition at line 104 of file NodedSegmentString.h.
   {
     delete pts;
   }
Member Function Documentation
void geos::noding::NodedSegmentString::addIntersection (algorithm::LineIntersector * li, unsigned int segmentIndex, int geomIndex, int intIndex)
Add an SegmentNode for intersection intIndex.
An intersection that falls exactly on a vertex of the SegmentString is normalized to use the higher of the two possible segmentIndexes
Definition at line 74 of file NodedSegmentString.cpp.
References geos::algorithm::LineIntersector::getIntersection(), and geos::ignore_unused_variable_warning().
Referenced by geos::noding::snapround::HotPixel::addSnappedNode(), geos::noding::snapround::SimpleSnapRounder::computeVertexSnaps(), and geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps().
 {
     ::geos::ignore_unused_variable_warning(geomIndex);
   const Coordinate &intPt=li->getIntersection(intIndex);
   addIntersection(intPt, segmentIndex);
 }
void geos::noding::NodedSegmentString::addIntersection (const geom::Coordinate & intPt, unsigned int segmentIndex)
Add an SegmentNode for intersection intIndex.
An intersection that falls exactly on a vertex of the edge is normalized to use the higher of the two possible segmentIndexes
Definition at line 86 of file NodedSegmentString.cpp.
References geos::geom::Coordinate::equals2D().
 {
   unsigned int normalizedSegmentIndex = segmentIndex;
   if ( segmentIndex > size()-2 )
   {
     throw util::IllegalArgumentException("SegmentString::addIntersection: SegmentIndex out of range");
   }
   // normalize the intersection point location
   unsigned int nextSegIndex = normalizedSegmentIndex + 1;
   if (nextSegIndex < size())
   {
     const Coordinate& nextPt = pts->getAt(nextSegIndex);
     // Normalize segment index if intPt falls on vertex
     // The check for point equality is 2D only -
     // Z values are ignored
     if (intPt.equals2D(nextPt)) {
       normalizedSegmentIndex = nextSegIndex;
     }
   }
   /*
    * Add the intersection point to edge intersection list
    * (unless the node is already known)
    */
   //SegmentNode *ei=
   nodeList.add(intPt, normalizedSegmentIndex);
 }
SegmentNode* geos::noding::NodedSegmentString::addIntersectionNode (geom::Coordinate * intPt, std::size_t segmentIndex) inline
Adds an intersection node for a given point and segment to this segment string. If an intersection already exists for this exact location, the existing node will be returned.
Parameters
intPt the location of the intersection
segmentIndex the index of the segment containing the intersection
Returns
the intersection node for the point
Definition at line 118 of file NodedSegmentString.h.
References geos::geom::Coordinate::equals2D().
   {
     std::size_t normalizedSegmentIndex = segmentIndex;
     // normalize the intersection point location
     std::size_t nextSegIndex = normalizedSegmentIndex + 1;
     if (nextSegIndex < size())
     {
       geom::Coordinate const& nextPt =
                 getCoordinate(static_cast<unsigned int>(nextSegIndex));
       // Normalize segment index if intPt falls on vertex
       // The check for point equality is 2D only - Z values are ignored
       if ( intPt->equals2D( nextPt ))
       {
         normalizedSegmentIndex = nextSegIndex;
       }
     }
     // Add the intersection point to edge intersection list.
     SegmentNode * ei = getNodeList().add( *intPt, normalizedSegmentIndex);
     return ei;
   }
void geos::noding::NodedSegmentString::addIntersections (algorithm::LineIntersector * li, unsigned int segmentIndex, int geomIndex)
Add {SegmentNode}s for one or both intersections found for a segment of an edge to the edge intersection list.
Definition at line 64 of file NodedSegmentString.cpp.
References geos::algorithm::LineIntersector::getIntersectionNum().
Referenced by geos::noding::IntersectionFinderAdder::processIntersections(), and geos::noding::IntersectionAdder::processIntersections().
 {
   for (int i=0, n=li->getIntersectionNum(); i<n; ++i) {
     addIntersection(li, segmentIndex, geomIndex, i);
   }
 }
const geom::Coordinate & geos::noding::NodedSegmentString::getCoordinate (unsigned int i) const override virtual
Implements geos::noding::SegmentString.
Definition at line 150 of file NodedSegmentString.cpp.
Referenced by geos::noding::snapround::HotPixel::addSnappedNode(), and geos::noding::SegmentNode::SegmentNode().
 {
   return pts->getAt(i);
 }
geom::CoordinateSequence * geos::noding::NodedSegmentString::getCoordinates () const override virtual
Return a pointer to the CoordinateSequence associated with this SegmentString.
Note that the CoordinateSequence is owned by this SegmentString!
Implements geos::noding::SegmentString.
Definition at line 157 of file NodedSegmentString.cpp.
Referenced by geos::noding::snapround::SimpleSnapRounder::computeVertexSnaps(), and geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps().
 {
   return pts;
 }
const void* geos::noding::SegmentString::getData () const inline inherited
Gets the user-defined data for this segment string.
Returns
the user-defined data
Definition at line 70 of file SegmentString.h.
Referenced by geos::operation::buffer::BufferBuilder::computeNodedEdges().
 { return context; }
template<class II > static void geos::noding::NodedSegmentString::getNodedSubstrings (II from, II too_far, SegmentString::NonConstVect * resultEdgelist) inline static
Definition at line 63 of file NodedSegmentString.h.
References geos::noding::SegmentNodeList::addSplitEdges(), and getNodeList().
Referenced by geos::noding::snapround::SimpleSnapRounder::checkCorrectness(), geos::noding::SimpleNoder::getNodedSubstrings(), geos::noding::snapround::SimpleSnapRounder::getNodedSubstrings(), and geos::noding::MCIndexNoder::getNodedSubstrings().
     {
         for (II i=from; i != too_far; ++i)
         {
             NodedSegmentString * nss = dynamic_cast<NodedSegmentString*>(*i);
             assert(nss);
             nss->getNodeList().addSplitEdges(resultEdgelist);
         }
     }
template<class C > static void geos::noding::NodedSegmentString::getNodedSubstrings (C * segStrings, SegmentString::NonConstVect * resultEdgelist) inline static
Definition at line 75 of file NodedSegmentString.h.
     {
         getNodedSubstrings(segStrings->begin(), segStrings->end(), resultEdgelist);
     }
void geos::noding::NodedSegmentString::getNodedSubstrings (const SegmentString::NonConstVect & segStrings, SegmentString::NonConstVect * resultEdgeList) static
Definition at line 122 of file NodedSegmentString.cpp.
References geos::noding::SegmentNodeList::addSplitEdges(), and getNodeList().
 {
   assert(resultEdgeList);
   for ( SegmentString::NonConstVect::const_iterator
     i=segStrings.begin(), iEnd=segStrings.end();
     i != iEnd; ++i )
   {
     NodedSegmentString* ss = dynamic_cast<NodedSegmentString*>(*i);
     assert(ss);
     ss->getNodeList().addSplitEdges(resultEdgeList);
   }
 }
SegmentString::NonConstVect * geos::noding::NodedSegmentString::getNodedSubstrings (const SegmentString::NonConstVect & segStrings) static
Returns allocated object.
Definition at line 139 of file NodedSegmentString.cpp.
 {
   SegmentString::NonConstVect* resultEdgelist = \
     new SegmentString::NonConstVect();
   getNodedSubstrings(segStrings, resultEdgelist);
   return resultEdgelist;
 }
SegmentNodeList & geos::noding::NodedSegmentString::getNodeList ()
Definition at line 39 of file NodedSegmentString.cpp.
Referenced by getNodedSubstrings().
 {
   return nodeList;
 }
const SegmentNodeList & geos::noding::NodedSegmentString::getNodeList () const
Definition at line 33 of file NodedSegmentString.cpp.
 {
   return nodeList;
 }
int geos::noding::NodedSegmentString::getSegmentOctant (unsigned int index) const
Gets the octant of the segment starting at vertex index.
Parameters
index the index of the vertex starting the segment. Must not be the last index in the vertex list
Returns
the octant of the segment at the vertex
Definition at line 55 of file NodedSegmentString.cpp.
 {
   if (index >= size() - 1) return -1;
   return safeOctant(getCoordinate(index), getCoordinate(index+1));
   //return Octant::octant(getCoordinate(index), getCoordinate(index+1));
 }
bool geos::noding::NodedSegmentString::isClosed () const override virtual
Implements geos::noding::SegmentString.
Definition at line 164 of file NodedSegmentString.cpp.
References geos::geom::CoordinateSequence::getAt().
 {
   return pts->getAt(0)==pts->getAt(size()-1);
 }
std::ostream & geos::noding::NodedSegmentString::print (std::ostream & os) const override virtual
Reimplemented from geos::noding::SegmentString.
Definition at line 171 of file NodedSegmentString.cpp.
 {
   os << "NodedSegmentString: " << std::endl;
   os << " LINESTRING" << *(pts) << ";" << std::endl;
   os << " Nodes: " << nodeList.size() << std::endl;
   return os;
 }
int geos::noding::NodedSegmentString::safeOctant (const geom::Coordinate & p0, const geom::Coordinate & p1) static private
Definition at line 46 of file NodedSegmentString.cpp.
References geos::geom::Coordinate::equals2D().
 {
   if ( p0.equals2D(p1) ) return 0;
   return Octant::octant(p0, p1);
 }
void geos::noding::SegmentString::setData (const void * data) inline inherited
Sets the user-defined data for this segment string.
Parameters
data an Object containing user-defined data
Definition at line 77 of file SegmentString.h.
 { context=data; }
unsigned int geos::noding::NodedSegmentString::size () const inline override virtual
Implements geos::noding::SegmentString.
Definition at line 146 of file NodedSegmentString.h.
Referenced by geos::noding::snapround::SimpleSnapRounder::computeSnaps(), and geos::noding::SegmentNode::SegmentNode().
   {
     return static_cast<unsigned int>(pts->size());
   }
Member Data Documentation
SegmentNodeList geos::noding::NodedSegmentString::nodeList private
Definition at line 201 of file NodedSegmentString.h.
geom::CoordinateSequence* geos::noding::NodedSegmentString::pts private
Definition at line 203 of file NodedSegmentString.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/noding/NodedSegmentString.h
/home/vicky/potree/geos/vicky/src/noding/NodedSegmentString.cpp