GEOS: geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCircumcentreVisitor Class Reference
geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCircumcentreVisitor Class Reference
Public Member Functions
void visit (QuadEdge *triEdges[3]) override
Detailed Description
Definition at line 399 of file QuadEdgeSubdivision.cpp.
Member Function Documentation
void geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCircumcentreVisitor::visit (QuadEdge * triEdges[3]) inline override virtual
Visits the QuadEdges of a triangle.
Parameters
triEdges an array of the 3 quad edges in a triangle (in CCW order)
Implements geos::triangulate::quadedge::TriangleVisitor.
Definition at line 403 of file QuadEdgeSubdivision.cpp.
References geos::geom::Triangle::circumcentre(), geos::triangulate::quadedge::QuadEdge::rot(), and geos::triangulate::quadedge::QuadEdge::setOrig().
   {
     Triangle triangle(triEdges[0]->orig().getCoordinate(),
         triEdges[1]->orig().getCoordinate(), triEdges[2]->orig().getCoordinate());
     Coordinate cc;
     triangle.circumcentre(cc);
     Vertex ccVertex(cc);
     for(int i=0 ; i<3 ; i++){
       triEdges[i]->rot().setOrig(ccVertex);
     }
   }
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/triangulate/quadedge/QuadEdgeSubdivision.cpp