GEOS: geos::operation::valid::IsValidOp Class Reference
geos::operation::valid::IsValidOp Class Reference
Implements the algorithsm required to compute the isValid() method for Geometrys.
#include <IsValidOp.h>
Public Member Functions
IsValidOp (const geom::Geometry *geom)
virtual ~IsValidOp ()
TODO: validErr can't be a pointer!
bool isValid ()
TopologyValidationError * getValidationError ()
void setSelfTouchingRingFormingHoleValid (bool isValid)
Sets whether polygons using Self-Touching Rings to form holes are reported as valid.
Static Public Member Functions
static const geom::Coordinate * findPtNotNode (const geom::CoordinateSequence *testCoords, const geom::LinearRing *searchRing, geomgraph::GeometryGraph *graph)
static bool isValid (const geom::Coordinate &coord)
static bool isValid (const geom::Geometry &geom)
Private Member Functions
void checkValid ()
void checkValid (const geom::Geometry *g)
void checkValid (const geom::Point *g)
void checkValid (const geom::LinearRing *g)
void checkValid (const geom::LineString *g)
void checkValid (const geom::Polygon *g)
void checkValid (const geom::MultiPolygon *g)
void checkValid (const geom::GeometryCollection *gc)
void checkConsistentArea (geomgraph::GeometryGraph *graph)
void checkNoSelfIntersectingRings (geomgraph::GeometryGraph *graph)
void checkNoSelfIntersectingRing (geomgraph::EdgeIntersectionList &eiList)
void checkTooFewPoints (geomgraph::GeometryGraph *graph)
void checkHolesInShell (const geom::Polygon *p, geomgraph::GeometryGraph *graph)
void checkHolesNotNested (const geom::Polygon *p, geomgraph::GeometryGraph *graph)
void checkShellsNotNested (const geom::MultiPolygon *mp, geomgraph::GeometryGraph *graph)
void checkShellNotNested (const geom::LinearRing *shell, const geom::Polygon *p, geomgraph::GeometryGraph *graph)
const geom::Coordinate * checkShellInsideHole (const geom::LinearRing *shell, const geom::LinearRing *hole, geomgraph::GeometryGraph *graph)
void checkConnectedInteriors (geomgraph::GeometryGraph &graph)
void checkInvalidCoordinates (const geom::CoordinateSequence *cs)
void checkInvalidCoordinates (const geom::Polygon *poly)
void checkClosedRings (const geom::Polygon *poly)
void checkClosedRing (const geom::LinearRing *ring)
Private Attributes
const geom::Geometry * parentGeometry
the base Geometry to be validated
bool isChecked
TopologyValidationError * validErr
bool isSelfTouchingRingFormingHoleValid
Friends
class Unload
Detailed Description
Implements the algorithsm required to compute the isValid() method for Geometrys.
Definition at line 61 of file IsValidOp.h.
Constructor & Destructor Documentation
geos::operation::valid::IsValidOp::IsValidOp (const geom::Geometry * geom) inline
Definition at line 224 of file IsValidOp.h.
     :
     parentGeometry(geom),
     isChecked(false),
     validErr(nullptr),
     isSelfTouchingRingFormingHoleValid(false)
   {}
virtual geos::operation::valid::IsValidOp::~IsValidOp () inline virtual
TODO: validErr can't be a pointer!
Definition at line 233 of file IsValidOp.h.
{
     delete validErr;
   }
Member Function Documentation
void geos::operation::valid::IsValidOp::checkClosedRing (const geom::LinearRing * ring) private
Definition at line 657 of file IsValidOp.cpp.
References geos::geom::LineString::getCoordinateN(), geos::geom::LinearRing::isClosed(), and geos::geom::LineString::isEmpty().
 {
   if ( ! ring->isClosed() && ! ring->isEmpty() )
   {
     validErr = new TopologyValidationError(
       TopologyValidationError::eRingNotClosed,
         ring->getCoordinateN(0));
   }
 }
void geos::operation::valid::IsValidOp::checkClosedRings (const geom::Polygon * poly) private
Definition at line 640 of file IsValidOp.cpp.
References geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), and geos::geom::Polygon::getNumInteriorRing().
 {
   const LinearRing *lr=(const LinearRing *)poly->getExteriorRing();
   checkClosedRing(lr);
   if (validErr) return;
   int nholes = static_cast<int>(poly->getNumInteriorRing());
   for (int i=0; i<nholes; ++i)
   {
     lr=(const LinearRing *)poly->getInteriorRingN(i);
     checkClosedRing(lr);
     if (validErr) return;
   }
 }
void geos::operation::valid::IsValidOp::checkConnectedInteriors (geomgraph::GeometryGraph & graph) private
Definition at line 591 of file IsValidOp.cpp.
References geos::operation::valid::ConnectedInteriorTester::getCoordinate(), and geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected().
 {
   ConnectedInteriorTester cit(graph);
   if (!cit.isInteriorsConnected())
   {
     validErr=new TopologyValidationError(
       TopologyValidationError::eDisconnectedInterior,
       cit.getCoordinate());
   }
 }
void geos::operation::valid::IsValidOp::checkConsistentArea (geomgraph::GeometryGraph * graph) private
Checks that the arrangement of edges in a polygonal geometry graph forms a consistent area.
Parameters
graph
See also
ConsistentAreaTester
Definition at line 315 of file IsValidOp.cpp.
References geos::operation::valid::ConsistentAreaTester::getInvalidPoint(), geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), and geos::operation::valid::ConsistentAreaTester::isNodeConsistentArea().
 {
   ConsistentAreaTester cat(graph);
   bool isValidArea=cat.isNodeConsistentArea();
   if (!isValidArea)
   {
     validErr=new TopologyValidationError(
       TopologyValidationError::eSelfIntersection,
       cat.getInvalidPoint());
     return;
   }
   if (cat.hasDuplicateRings())
   {
     validErr=new TopologyValidationError(
       TopologyValidationError::eDuplicatedRings,
       cat.getInvalidPoint());
   }
 }
void geos::operation::valid::IsValidOp::checkHolesInShell (const geom::Polygon * p, geomgraph::GeometryGraph * graph) private
Test that each hole is inside the polygon shell. This routine assumes that the holes have previously been tested to ensure that all vertices lie on the shell or inside it. A simple test of a single point in the hole can be used, provide the point is chosen such that it does not lie on the boundary of the shell.
Parameters
p the polygon to be tested for hole inclusion
graph a geomgraph::GeometryGraph incorporating the polygon
If no non-node hole vertex can be found, the hole must split the polygon into disconnected interiors. This will be caught by a subsequent check.
Definition at line 378 of file IsValidOp.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), geos::geom::LineString::isEmpty(), and geos::algorithm::MCPointInRing::isInside().
 {
   assert(dynamic_cast<const LinearRing*>(p->getExteriorRing()));
   const LinearRing *shell=static_cast<const LinearRing*>(
       p->getExteriorRing());
   int nholes = static_cast<int>(p->getNumInteriorRing());
   if(shell->isEmpty())
   {
     for(int i=0; i<nholes; ++i)
     {
       assert(dynamic_cast<const LinearRing*>(
         p->getInteriorRingN(i)));
       const LinearRing *hole=static_cast<const LinearRing*>(
         p->getInteriorRingN(i));
       if(!hole->isEmpty())
       {
         validErr=new TopologyValidationError(
           TopologyValidationError::eHoleOutsideShell);
         return;
       }
     }
     // all interiors also empty or none exist
     return;
   }
   //SimplePointInRing pir(shell);
   //SIRtreePointInRing pir(shell);
   MCPointInRing pir(shell);
   for(int i=0; i<nholes; ++i)
   {
     assert(dynamic_cast<const LinearRing*>(
         p->getInteriorRingN(i)));
     const LinearRing *hole=static_cast<const LinearRing*>(
         p->getInteriorRingN(i));
     const Coordinate *holePt=findPtNotNode(
         hole->getCoordinatesRO(), shell, graph);
     if (holePt==nullptr) return;
     bool outside = !pir.isInside(*holePt);
     if (outside) {
       validErr=new TopologyValidationError(
         TopologyValidationError::eHoleOutsideShell,
         *holePt);
       return;
     }
   }
 }
void geos::operation::valid::IsValidOp::checkHolesNotNested (const geom::Polygon * p, geomgraph::GeometryGraph * graph) private
Tests that no hole is nested inside another hole. This routine assumes that the holes are disjoint. To ensure this, holes have previously been tested to ensure that:
they do not partially overlap (checked by checkRelateConsistency)
they are not identical (checked by checkRelateConsistency)
Definition at line 442 of file IsValidOp.cpp.
References geos::operation::valid::IndexedNestedRingTester::add(), geos::geom::Polygon::getInteriorRingN(), geos::operation::valid::IndexedNestedRingTester::getNestedPoint(), geos::geom::Polygon::getNumInteriorRing(), geos::geom::LineString::isEmpty(), and geos::operation::valid::IndexedNestedRingTester::isNonNested().
 {
   //SimpleNestedRingTester nestedTester(graph);
   //SweeplineNestedRingTester nestedTester(graph);
   //QuadtreeNestedRingTester nestedTester(graph);
   IndexedNestedRingTester nestedTester(graph);
   int nholes = static_cast<int>(p->getNumInteriorRing());
   for(int i=0; i<nholes; ++i)
   {
     assert(dynamic_cast<const LinearRing*>(
         p->getInteriorRingN(i)));
     const LinearRing *innerHole=static_cast<const LinearRing*>(
         p->getInteriorRingN(i));
     //empty holes always pass
     if(innerHole->isEmpty()) continue;
     nestedTester.add(innerHole);
   }
   bool isNonNested=nestedTester.isNonNested();
   if (!isNonNested)
   {
     validErr=new TopologyValidationError(
       TopologyValidationError::eNestedHoles,
       *(nestedTester.getNestedPoint()));
   }
 }
void geos::operation::valid::IsValidOp::checkInvalidCoordinates (const geom::CoordinateSequence * cs) private
Definition at line 605 of file IsValidOp.cpp.
References geos::geom::CoordinateSequence::getAt(), and geos::geom::CoordinateSequence::getSize().
 {
   unsigned int size = static_cast<unsigned int>(cs->getSize());
   for (unsigned int i=0; i<size; ++i)
   {
     if (! isValid(cs->getAt(i)) )
     {
       validErr = new TopologyValidationError(
         TopologyValidationError::eInvalidCoordinate,
         cs->getAt(i));
       return;
     }
   }
 }
void geos::operation::valid::IsValidOp::checkInvalidCoordinates (const geom::Polygon * poly) private
Definition at line 623 of file IsValidOp.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), and geos::geom::Polygon::getNumInteriorRing().
 {
   checkInvalidCoordinates(poly->getExteriorRing()->getCoordinatesRO());
   if (validErr != nullptr) return;
   int nholes = static_cast<int>(poly->getNumInteriorRing());
   for (int i=0; i<nholes; ++i)
   {
     checkInvalidCoordinates(
       poly->getInteriorRingN(i)->getCoordinatesRO()
     );
     if (validErr != nullptr) return;
   }
 }
void geos::operation::valid::IsValidOp::checkNoSelfIntersectingRing (geomgraph::EdgeIntersectionList & eiList) private
check that a ring does not self-intersect, except at its endpoints. Algorithm is to count the number of times each node along edge occurs. If any occur more than once, that must be a self-intersection.
Definition at line 352 of file IsValidOp.cpp.
References geos::geomgraph::EdgeIntersectionList::begin(), geos::geomgraph::EdgeIntersection::coord, and geos::geomgraph::EdgeIntersectionList::end().
 {
   set<const Coordinate*,CoordinateLessThen>nodeSet;
   bool isFirst=true;
   EdgeIntersectionList::iterator it=eiList.begin();
   EdgeIntersectionList::iterator end=eiList.end();
   for(; it!=end; ++it)
   {
     EdgeIntersection *ei=*it;
     if (isFirst) {
       isFirst=false;
       continue;
     }
     if (nodeSet.find(&ei->coord)!=nodeSet.end()) {
       validErr=new TopologyValidationError(
         TopologyValidationError::eRingSelfIntersection,
         ei->coord);
       return;
     } else {
       nodeSet.insert(&ei->coord);
     }
   }
 }
void geos::operation::valid::IsValidOp::checkNoSelfIntersectingRings (geomgraph::GeometryGraph * graph) private
Check that there is no ring which self-intersects (except of course at its endpoints). This is required by OGC topology rules (but not by other models such as ESRI SDE, which allow inverted shells and exverted holes).
Parameters
graph the topology graph of the geometry
Definition at line 339 of file IsValidOp.cpp.
References geos::geomgraph::Edge::getEdgeIntersectionList(), and geos::geomgraph::GeometryGraph::getEdges().
 {
   vector<Edge*> *edges=graph->getEdges();
   for(unsigned int i=0; i<edges->size(); ++i)
   {
     Edge *e=(*edges)[i];
     checkNoSelfIntersectingRing(e->getEdgeIntersectionList());
     if(validErr!=nullptr) return;
   }
 }
const Coordinate * geos::operation::valid::IsValidOp::checkShellInsideHole (const geom::LinearRing * shell, const geom::LinearRing * hole, geomgraph::GeometryGraph * graph) private
This routine checks to see if a shell is properly contained in a hole. It assumes that the edges of the shell and hole do not properly intersect.
Returns
null if the shell is properly contained, or a Coordinate which is not inside the hole if it is not
Definition at line 558 of file IsValidOp.cpp.
References geos::geom::LineString::getCoordinatesRO().
 {
   const CoordinateSequence *shellPts=shell->getCoordinatesRO();
   const CoordinateSequence *holePts=hole->getCoordinatesRO();
   // TODO: improve performance of this - by sorting pointlists
   // for instance?
   const Coordinate *shellPt=findPtNotNode(shellPts, hole, graph);
   // if point is on shell but not hole, check that the shell is
   // inside the hole
   if (shellPt) {
     bool insideHole=CGAlgorithms::isPointInRing(*shellPt, holePts);
     if (!insideHole) return shellPt;
   }
   const Coordinate *holePt=findPtNotNode(holePts, shell, graph);
   // if point is on hole but not shell, check that the hole is
   // outside the shell
   if (holePt) {
     bool insideShell=CGAlgorithms::isPointInRing(*holePt, shellPts);
     if (insideShell) return holePt;
     return nullptr;
   }
   assert(0); // points in shell and hole appear to be equal
   return nullptr;
 }
void geos::operation::valid::IsValidOp::checkShellNotNested (const geom::LinearRing * shell, const geom::Polygon * p, geomgraph::GeometryGraph * graph) private
Check if a shell is incorrectly nested within a polygon. This is the case if the shell is inside the polygon shell, but not inside a polygon hole. (If the shell is inside a polygon hole, the nesting is valid.)
The algorithm used relies on the fact that the rings must be properly contained. E.g. they cannot partially overlap (this has been previously checked by checkRelateConsistency
Check if the shell is inside one of the holes. This is the case if one of the calls to checkShellInsideHole returns a null coordinate. Otherwise, the shell is not properly contained in a hole, which is an error.
Definition at line 506 of file IsValidOp.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), and geos::geom::Polygon::getNumInteriorRing().
 {
   const CoordinateSequence *shellPts=shell->getCoordinatesRO();
   // test if shell is inside polygon shell
   assert(dynamic_cast<const LinearRing*>(
       p->getExteriorRing()));
   const LinearRing *polyShell=static_cast<const LinearRing*>(
       p->getExteriorRing());
   const CoordinateSequence *polyPts=polyShell->getCoordinatesRO();
   const Coordinate *shellPt=findPtNotNode(shellPts,polyShell,graph);
   // if no point could be found, we can assume that the shell
   // is outside the polygon
   if (shellPt==nullptr) return;
   bool insidePolyShell=CGAlgorithms::isPointInRing(*shellPt, polyPts);
   if (!insidePolyShell) return;
   // if no holes, this is an error!
   int nholes = static_cast<int>(p->getNumInteriorRing());
   if (nholes<=0) {
     validErr=new TopologyValidationError(
       TopologyValidationError::eNestedShells,
       *shellPt);
     return;
   }
   const Coordinate *badNestedPt=nullptr;
   for(int i=0; i<nholes; ++i) {
     assert(dynamic_cast<const LinearRing*>(
         p->getInteriorRingN(i)));
     const LinearRing *hole=static_cast<const LinearRing*>(
         p->getInteriorRingN(i));
     badNestedPt = checkShellInsideHole(shell, hole, graph);
     if (badNestedPt==nullptr) return;
   }
   validErr=new TopologyValidationError(
     TopologyValidationError::eNestedShells, *badNestedPt
   );
 }
void geos::operation::valid::IsValidOp::checkShellsNotNested (const geom::MultiPolygon * mp, geomgraph::GeometryGraph * graph) private
Tests that no element polygon is wholly in the interior of another element polygon.
Preconditions:
shells do not partially overlap
shells do not touch along an edge
no duplicate rings exist
This routine relies on the fact that while polygon shells may touch at one or more vertices, they cannot touch at ALL vertices.
Definition at line 475 of file IsValidOp.cpp.
References geos::geom::Polygon::getExteriorRing(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::geom::Polygon::isEmpty(), and geos::geom::LineString::isEmpty().
 {
   for(unsigned int i=0, ngeoms = static_cast<int>(mp->getNumGeometries()); i<ngeoms; ++i)
   {
     const Polygon *p=dynamic_cast<const Polygon *>(
         mp->getGeometryN(i));
     assert(p);
     const LinearRing *shell=dynamic_cast<const LinearRing*>(
         p->getExteriorRing());
     assert(shell);
     for(unsigned int j=0; j<ngeoms; ++j)
     {
       if (i==j) continue;
       const Polygon *p2 = dynamic_cast<const Polygon *>(
           mp->getGeometryN(j));
       assert(p2);
       if (shell->isEmpty() || p2->isEmpty()) continue;
       checkShellNotNested(shell, p2, graph);
       if (validErr!=nullptr) return;
     }
   }
 }
void geos::operation::valid::IsValidOp::checkTooFewPoints (geomgraph::GeometryGraph * graph) private
Definition at line 296 of file IsValidOp.cpp.
References geos::geomgraph::GeometryGraph::getInvalidPoint(), and geos::geomgraph::GeometryGraph::hasTooFewPoints().
 {
   if (graph->hasTooFewPoints()) {
     validErr=new TopologyValidationError(
       TopologyValidationError::eTooFewPoints,
       graph->getInvalidPoint());
     return;
   }
 }
void geos::operation::valid::IsValidOp::checkValid () private
Definition at line 117 of file IsValidOp.cpp.
 {
   if (isChecked) return;
   checkValid(parentGeometry);
         isChecked=true;
 }
void geos::operation::valid::IsValidOp::checkValid (const geom::Geometry * g) private
Definition at line 125 of file IsValidOp.cpp.
References geos::geom::Geometry::isEmpty().
 {
   assert( validErr == nullptr );
   if (nullptr == g)
     return;
   // empty geometries are always valid!
   if (g->isEmpty()) return;
   if ( const Point* x = dynamic_cast<const Point*>(g) )
     checkValid(x);
   // LineString also handles LinearRings, so we check LinearRing first
   else if ( const LinearRing* x = dynamic_cast<const LinearRing*>(g) )
     checkValid(x);
   else if ( const LineString* x = dynamic_cast<const LineString*>(g) )
     checkValid(x);
   else if ( const Polygon* x = dynamic_cast<const Polygon*>(g) )
     checkValid(x);
   else if ( const MultiPolygon* x = dynamic_cast<const MultiPolygon*>(g) )
     checkValid(x);
   else if ( const GeometryCollection* x =
         dynamic_cast<const GeometryCollection*>(g) )
   {
     checkValid(x);
   }
   else throw util::UnsupportedOperationException();
 }
void geos::operation::valid::IsValidOp::checkValid (const geom::Point * g) private
Definition at line 158 of file IsValidOp.cpp.
References geos::geom::Point::getCoordinatesRO().
 {
   checkInvalidCoordinates(g->getCoordinatesRO());
 }
void geos::operation::valid::IsValidOp::checkValid (const geom::LinearRing * g) private
Checks validity of a LinearRing.
Definition at line 180 of file IsValidOp.cpp.
References geos::geomgraph::GeometryGraph::computeSelfNodes(), and geos::geom::LineString::getCoordinatesRO().
{
   checkInvalidCoordinates(g->getCoordinatesRO());
   if (validErr != nullptr) return;
   checkClosedRing(g);
   if (validErr != nullptr) return;
   GeometryGraph graph(0, g);
   checkTooFewPoints(&graph);
   if (validErr!=nullptr) return;
   LineIntersector li;
   delete graph.computeSelfNodes(&li, true, true);
   checkNoSelfIntersectingRings(&graph);
 }
void geos::operation::valid::IsValidOp::checkValid (const geom::LineString * g) private
Definition at line 167 of file IsValidOp.cpp.
References geos::geom::LineString::getCoordinatesRO().
 {
   checkInvalidCoordinates(g->getCoordinatesRO());
   if (validErr != nullptr) return;
   GeometryGraph graph(0,g);
   checkTooFewPoints(&graph);
 }
void geos::operation::valid::IsValidOp::checkValid (const geom::Polygon * g) private
Checks the validity of a polygon. Sets the validErr flag.
Definition at line 201 of file IsValidOp.cpp.
 {
   checkInvalidCoordinates(g);
   if (validErr != nullptr) return;
   checkClosedRings(g);
   if (validErr != nullptr) return;
   GeometryGraph graph(0,g);
   checkTooFewPoints(&graph);
   if (validErr!=nullptr) return;
   checkConsistentArea(&graph);
   if (validErr!=nullptr) return;
   if (!isSelfTouchingRingFormingHoleValid) {
     checkNoSelfIntersectingRings(&graph);
     if (validErr!=nullptr) return;
   }
   checkHolesInShell(g,&graph);
   if (validErr!=nullptr) return;
   checkHolesNotNested(g,&graph);
   if (validErr!=nullptr) return;
   checkConnectedInteriors(graph);
 }
void geos::operation::valid::IsValidOp::checkValid (const geom::MultiPolygon * g) private
Definition at line 232 of file IsValidOp.cpp.
References geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   unsigned int ngeoms = static_cast<unsigned int>(g->getNumGeometries());
   vector<const Polygon *>polys(ngeoms);
   for (unsigned int i=0; i<ngeoms; ++i)
   {
     const Polygon *p = dynamic_cast<const Polygon *>(g->getGeometryN(i));
     checkInvalidCoordinates(p);
     if (validErr != nullptr) return;
     checkClosedRings(p);
     if (validErr != nullptr) return;
     polys[i]=p;
   }
   GeometryGraph graph(0,g);
   checkTooFewPoints(&graph);
   if (validErr!=nullptr) return;
   checkConsistentArea(&graph);
   if (validErr!=nullptr) return;
   if (!isSelfTouchingRingFormingHoleValid)
   {
     checkNoSelfIntersectingRings(&graph);
     if (validErr!=nullptr) return;
   }
   for(unsigned int i=0; i<ngeoms; ++i)
   {
     const Polygon *p=polys[i];
     checkHolesInShell(p, &graph);
     if (validErr!=nullptr) return;
   }
   for(unsigned int i=0; i<ngeoms; ++i)
   {
     const Polygon *p=polys[i];
     checkHolesNotNested(p, &graph);
     if (validErr!=nullptr) return;
   }
   checkShellsNotNested(g,&graph);
   if (validErr!=nullptr) return;
   checkConnectedInteriors(graph);
 }
void geos::operation::valid::IsValidOp::checkValid (const geom::GeometryCollection * gc) private
Definition at line 285 of file IsValidOp.cpp.
References geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   for(unsigned int i=0, ngeoms=static_cast<unsigned int>(gc->getNumGeometries()); i<ngeoms; ++i)
   {
     const Geometry *g=gc->getGeometryN(i);
     checkValid(g);
     if (validErr!=nullptr) return;
   }
 }
const Coordinate * geos::operation::valid::IsValidOp::findPtNotNode (const geom::CoordinateSequence * testCoords, const geom::LinearRing * searchRing, geomgraph::GeometryGraph * graph) static
Find a point from the list of testCoords that is NOT a node in the edge for the list of searchCoords
Returns
the point found, or NULL if none found
Find a point from the list of testCoords that is NOT a node in the edge for the list of searchCoords
Returns
the point found, or null if none found
Definition at line 65 of file IsValidOp.cpp.
References geos::geomgraph::GeometryGraph::findEdge(), geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getEdgeIntersectionList(), geos::geom::CoordinateSequence::getSize(), and geos::geomgraph::EdgeIntersectionList::isIntersection().
Referenced by geos::operation::valid::QuadtreeNestedRingTester::isNonNested().
 {
   // find edge corresponding to searchRing.
   Edge *searchEdge=graph->findEdge(searchRing);
   // find a point in the testCoords which is not a node of the searchRing
   EdgeIntersectionList &eiList=searchEdge->getEdgeIntersectionList();
   // somewhat inefficient - is there a better way? (Use a node map, for instance?)
   unsigned int npts = static_cast<int>(testCoords->getSize());
   for(unsigned int i=0; i<npts; ++i)
   {
     const Coordinate& pt=testCoords->getAt(i);
     if (!eiList.isIntersection(pt)) {
       return &pt;
     }
   }
   return nullptr;
 }
TopologyValidationError * geos::operation::valid::IsValidOp::getValidationError ()
Definition at line 110 of file IsValidOp.cpp.
Referenced by geos::geom::check_valid().
 {
   checkValid();
   return validErr;
 }
bool geos::operation::valid::IsValidOp::isValid (const geom::Coordinate & coord) static
Checks whether a coordinate is valid for processing. Coordinates are valid iff their x and y coordinates are in the range of the floating point representation.
Parameters
coord the coordinate to validate
Returns
true if the coordinate is valid
Definition at line 94 of file IsValidOp.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::geom::check_valid(), isValid(), and geos::geom::Geometry::isValid().
 {
   if (! FINITE(coord.x) ) return false;
   if (! FINITE(coord.y) ) return false;
   return true;
 }
bool geos::operation::valid::IsValidOp::isValid (const geom::Geometry & geom) static
Tests whether a Geometry is valid.
Parameters
geom the Geometry to test
Returns
true if the geometry is valid
Definition at line 103 of file IsValidOp.cpp.
References isValid().
 {
   IsValidOp op(&g);
   return op.isValid();
 }
bool geos::operation::valid::IsValidOp::isValid ()
Definition at line 86 of file IsValidOp.cpp.
 {
   checkValid();
   return validErr==nullptr;
 }
void geos::operation::valid::IsValidOp::setSelfTouchingRingFormingHoleValid (bool isValid) inline
Sets whether polygons using Self-Touching Rings to form holes are reported as valid.
If this flag is set, the following Self-Touching conditions are treated as being valid:
the shell ring self-touches to create a hole touching the shell
a hole ring self-touches to create two holes touching at a point
The default (following the OGC SFS standard) is that this condition is not valid (false).
This does not affect whether Self-Touching Rings disconnecting the polygon interior are considered valid (these are considered to be invalid under the SFS, and many other spatial models as well). This includes "bow-tie" shells, which self-touch at a single point causing the interior to be disconnected, and "C-shaped" holes which self-touch at a single point causing an island to be formed.
Parameters
isValid states whether geometry with this condition is valid
Definition at line 267 of file IsValidOp.h.
   {
     isSelfTouchingRingFormingHoleValid = isValid;
   }
Friends And Related Function Documentation
friend class Unload friend
Definition at line 62 of file IsValidOp.h.
Member Data Documentation
bool geos::operation::valid::IsValidOp::isChecked private
Definition at line 67 of file IsValidOp.h.
bool geos::operation::valid::IsValidOp::isSelfTouchingRingFormingHoleValid private
Definition at line 192 of file IsValidOp.h.
const geom::Geometry* geos::operation::valid::IsValidOp::parentGeometry private
the base Geometry to be validated
Definition at line 65 of file IsValidOp.h.
TopologyValidationError* geos::operation::valid::IsValidOp::validErr private
Definition at line 70 of file IsValidOp.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/valid/IsValidOp.h
/home/vicky/potree/geos/vicky/src/operation/valid/IsValidOp.cpp