GEOS: geos::geomgraph::index::MonotoneChainEdge Class Reference
geos::geomgraph::index::MonotoneChainEdge Class Reference
#include <MonotoneChainEdge.h>
Public Member Functions
~MonotoneChainEdge ()
MonotoneChainEdge (Edge *newE)
const geom::CoordinateSequence * getCoordinates ()
std::vector< int > & getStartIndexes ()
double getMinX (int chainIndex)
double getMaxX (int chainIndex)
void computeIntersects (const MonotoneChainEdge &mce, SegmentIntersector &si)
void computeIntersectsForChain (int chainIndex0, const MonotoneChainEdge &mce, int chainIndex1, SegmentIntersector &si)
Protected Attributes
Edge * e
const geom::CoordinateSequence * pts
std::vector< int > startIndex
geom::Envelope env1
geom::Envelope env2
Private Member Functions
void computeIntersectsForChain (int start0, int end0, const MonotoneChainEdge &mce, int start1, int end1, SegmentIntersector &ei)
Detailed Description
Definition at line 44 of file MonotoneChainEdge.h.
Constructor & Destructor Documentation
geos::geomgraph::index::MonotoneChainEdge::~MonotoneChainEdge ()
MonotoneChains are a way of partitioning the segments of an edge to allow for fast searching of intersections. They have the following properties:
the segments within a monotone chain will never intersect each other
the envelope of any contiguous subset of the segments in a monotone chain is simply the envelope of the endpoints of the subset.
Property 1 means that there is no need to test pairs of segments from within the same monotone chain for intersection. Property 2 allows binary search to be used to find the intersection points of two monotone chains. For many types of real-world data, these properties eliminate a large number of segment comparisons, producing substantial speed gains.
Version
1.1
Definition at line 51 of file MonotoneChainEdge.cpp.
 {
 }
geos::geomgraph::index::MonotoneChainEdge::MonotoneChainEdge (Edge * newE)
Definition at line 55 of file MonotoneChainEdge.cpp.
References e, geos::geomgraph::index::MonotoneChainIndexer::getChainStartIndices(), pts, and startIndex.
                                               :
   e(newE),
   pts(newE->getCoordinates())
 {
   assert(e);
   MonotoneChainIndexer mcb;
   mcb.getChainStartIndices(pts, startIndex);
   assert(e);
 }
Member Function Documentation
void geos::geomgraph::index::MonotoneChainEdge::computeIntersects (const MonotoneChainEdge & mce, SegmentIntersector & si)
Definition at line 95 of file MonotoneChainEdge.cpp.
References computeIntersectsForChain(), and startIndex.
 {
   size_t I=startIndex.size()-1;
   size_t J=mce.startIndex.size()-1;
   for(size_t i=0; i<I; ++i)
   {
     for(size_t j=0; j<J; ++j)
     {
       computeIntersectsForChain(static_cast<int>(i),mce,static_cast<int>(j),si);
     }
   }
 }
void geos::geomgraph::index::MonotoneChainEdge::computeIntersectsForChain (int chainIndex0, const MonotoneChainEdge & mce, int chainIndex1, SegmentIntersector & si)
Definition at line 110 of file MonotoneChainEdge.cpp.
References startIndex.
Referenced by geos::geomgraph::index::MonotoneChain::computeIntersections(), computeIntersects(), and computeIntersectsForChain().
 {
   computeIntersectsForChain(startIndex[chainIndex0],
     startIndex[chainIndex0+1], mce,
     mce.startIndex[chainIndex1],
     mce.startIndex[chainIndex1+1],
     si);
 }
void geos::geomgraph::index::MonotoneChainEdge::computeIntersectsForChain (int start0, int end0, const MonotoneChainEdge & mce, int start1, int end1, SegmentIntersector & ei) private
Definition at line 122 of file MonotoneChainEdge.cpp.
References geos::geomgraph::index::SegmentIntersector::addIntersections(), computeIntersectsForChain(), e, env1, env2, geos::geom::CoordinateSequence::getAt(), geos::geom::Envelope::init(), geos::geom::Envelope::intersects(), and pts.
 {
   // terminating condition for the recursion
   if (end0-start0==1 && end1-start1==1) {
     ei.addIntersections(e, start0, mce.e, start1);
     return;
   }
   const Coordinate& p00=pts->getAt(start0);
   const Coordinate& p01=pts->getAt(end0);
   const Coordinate& p10=mce.pts->getAt(start1);
   const Coordinate& p11=mce.pts->getAt(end1);
   // nothing to do if the envelopes of these chains don't overlap
   env1.init(p00,p01);
   env2.init(p10,p11);
   if (!env1.intersects(&env2)) return;
   // the chains overlap, so split each in half and iterate
   // (binary search)
   int mid0=(start0+end0)/2;
   int mid1=(start1+end1)/2;
   // Assert: mid != start or end
   // (since we checked above for end - start <= 1)
   // check terminating conditions before recursing
   if (start0<mid0) {
     if (start1<mid1)
       computeIntersectsForChain(start0, mid0, mce,
         start1, mid1, ei);
     if (mid1<end1)
       computeIntersectsForChain(start0, mid0, mce,
         mid1, end1, ei);
   }
   if (mid0<end0) {
     if (start1<mid1)
       computeIntersectsForChain(mid0, end0, mce,
         start1, mid1, ei);
     if (mid1<end1)
       computeIntersectsForChain(mid0, end0, mce,
         mid1, end1, ei);
   }
 }
const CoordinateSequence * geos::geomgraph::index::MonotoneChainEdge::getCoordinates (void)
Definition at line 66 of file MonotoneChainEdge.cpp.
References pts.
 {
   assert(pts);
   return pts;
 }
double geos::geomgraph::index::MonotoneChainEdge::getMaxX (int chainIndex)
Definition at line 87 of file MonotoneChainEdge.cpp.
References geos::geom::CoordinateSequence::getAt(), pts, startIndex, and geos::geom::Coordinate::x.
Referenced by geos::geomgraph::index::SimpleMCSweepLineIntersector::add().
 {
   double x1=pts->getAt(startIndex[chainIndex]).x;
   double x2=pts->getAt(startIndex[chainIndex+1]).x;
   return x1>x2?x1:x2;
 }
double geos::geomgraph::index::MonotoneChainEdge::getMinX (int chainIndex)
Definition at line 79 of file MonotoneChainEdge.cpp.
References geos::geom::CoordinateSequence::getAt(), pts, startIndex, and geos::geom::Coordinate::x.
Referenced by geos::geomgraph::index::SimpleMCSweepLineIntersector::add().
 {
   double x1=pts->getAt(startIndex[chainIndex]).x;
   double x2=pts->getAt(startIndex[chainIndex+1]).x;
   return x1<x2?x1:x2;
 }
vector< int > & geos::geomgraph::index::MonotoneChainEdge::getStartIndexes ()
Definition at line 73 of file MonotoneChainEdge.cpp.
References startIndex.
Referenced by geos::geomgraph::index::SimpleMCSweepLineIntersector::add().
 {
   return startIndex;
 }
Member Data Documentation
Edge* geos::geomgraph::index::MonotoneChainEdge::e protected
Definition at line 62 of file MonotoneChainEdge.h.
Referenced by computeIntersectsForChain(), and MonotoneChainEdge().
geom::Envelope geos::geomgraph::index::MonotoneChainEdge::env1 protected
Definition at line 68 of file MonotoneChainEdge.h.
Referenced by computeIntersectsForChain().
geom::Envelope geos::geomgraph::index::MonotoneChainEdge::env2 protected
Definition at line 69 of file MonotoneChainEdge.h.
Referenced by computeIntersectsForChain().
const geom::CoordinateSequence* geos::geomgraph::index::MonotoneChainEdge::pts protected
Definition at line 63 of file MonotoneChainEdge.h.
Referenced by computeIntersectsForChain(), getCoordinates(), getMaxX(), getMinX(), and MonotoneChainEdge().
std::vector<int> geos::geomgraph::index::MonotoneChainEdge::startIndex protected
Definition at line 66 of file MonotoneChainEdge.h.
Referenced by computeIntersects(), computeIntersectsForChain(), getMaxX(), getMinX(), getStartIndexes(), and MonotoneChainEdge().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/index/MonotoneChainEdge.h
/home/vicky/potree/geos/vicky/src/geomgraph/index/MonotoneChainEdge.cpp