GEOS: geos::linearref::LocationIndexOfLine Class Reference
geos::linearref::LocationIndexOfLine Class Reference
#include <LocationIndexOfLine.h>
Public Member Functions
LocationIndexOfLine (const geom::Geometry *linearGeom)
LinearLocation * indicesOf (const geom::Geometry *subLine) const
Caller must take of releasing with delete[].
Static Public Member Functions
static LinearLocation * indicesOf (const geom::Geometry *linearGeom, const geom::Geometry *subLine)
Determines the location of a subline along a linear Geometry.
Private Attributes
const geom::Geometry * linearGeom
Detailed Description
Determines the location of a subline along a linear Geometry. The location is reported as a pair of LinearLocations.
Note: Currently this algorithm is not guaranteed to return the correct substring in some situations where an endpoint of the test line occurs more than once in the input line. (However, the common case of a ring is always handled correctly).
Definition at line 41 of file LocationIndexOfLine.h.
Constructor & Destructor Documentation
geos::linearref::LocationIndexOfLine::LocationIndexOfLine (const geom::Geometry * linearGeom)
Definition at line 44 of file LocationIndexOfLine.cpp.
                                                                    :
     linearGeom(linearGeom) {}
Member Function Documentation
LinearLocation * geos::linearref::LocationIndexOfLine::indicesOf (const geom::Geometry * linearGeom, const geom::Geometry * subLine) static
Determines the location of a subline along a linear Geometry.
The location is reported as a pair of LinearLocations.
Note: Currently this algorithm is not guaranteed to return the correct substring in some situations where an endpoint of the test line occurs more than once in the input line. (However, the common case of a ring is always handled correctly).
Caller must take of releasing with delete[]
Definition at line 37 of file LocationIndexOfLine.cpp.
References indicesOf().
Referenced by indicesOf(), geos::linearref::LengthIndexedLine::indicesOf(), and geos::linearref::LocationIndexedLine::indicesOf().
 {
   LocationIndexOfLine locater(linearGeom);
   return locater.indicesOf(subLine);
 }
LinearLocation * geos::linearref::LocationIndexOfLine::indicesOf (const geom::Geometry * subLine) const
Caller must take of releasing with delete[].
Definition at line 49 of file LocationIndexOfLine.cpp.
References geos::geom::LineString::getCoordinateN(), geos::geom::Geometry::getGeometryN(), geos::geom::Geometry::getLength(), geos::geom::Geometry::getNumGeometries(), geos::geom::LineString::getNumPoints(), geos::linearref::LocationIndexOfPoint::indexOf(), geos::linearref::LocationIndexOfPoint::indexOfAfter(), and linearGeom.
 {
   Coordinate startPt = dynamic_cast<const LineString*> (subLine->getGeometryN(0))->getCoordinateN(0);
   const LineString* lastLine = dynamic_cast<const LineString*> (subLine->getGeometryN(subLine->getNumGeometries() - 1));
   Coordinate endPt = lastLine->getCoordinateN(static_cast<int>(lastLine->getNumPoints() - 1));
   LocationIndexOfPoint locPt(linearGeom);
   LinearLocation *subLineLoc = new LinearLocation[2];
   subLineLoc[0] = locPt.indexOf(startPt);
   // check for case where subline is zero length
   if (subLine->getLength() == 0.0)
   {
     subLineLoc[1] = subLineLoc[0];
   }
   else
   {
     subLineLoc[1] = locPt.indexOfAfter(endPt, &subLineLoc[0]);
   }
   return subLineLoc;
 }
Member Data Documentation
const geom::Geometry* geos::linearref::LocationIndexOfLine::linearGeom private
MD - this algorithm has been extracted into a class because it is intended to validate that the subline truly is a subline, and also to use the internal vertex information to unambiguously locate the subline.
Definition at line 49 of file LocationIndexOfLine.h.
Referenced by indicesOf().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/linearref/LocationIndexOfLine.h
/home/vicky/potree/geos/vicky/src/linearref/LocationIndexOfLine.cpp