GEOS: geos::geom::Triangle Class Reference
geos::geom::Triangle Class Reference
Represents a planar triangle, and provides methods for calculating various properties of triangles.
#include <Triangle.h>
Public Member Functions
Triangle (const Coordinate &nP0, const Coordinate &nP1, const Coordinate &nP2)
void inCentre (Coordinate &resultPoint)
void circumcentre (Coordinate &resultPoint)
Public Attributes
Coordinate p0
Coordinate p1
Coordinate p2
Private Member Functions
double det (double m00, double m01, double m10, double m11) const
Detailed Description
Represents a planar triangle, and provides methods for calculating various properties of triangles.
Definition at line 31 of file Triangle.h.
Constructor & Destructor Documentation
geos::geom::Triangle::Triangle (const Coordinate & nP0, const Coordinate & nP1, const Coordinate & nP2) inline
Definition at line 35 of file Triangle.h.
     :
     p0(nP0),
     p1(nP1),
     p2(nP2)
   {}
Member Function Documentation
void geos::geom::Triangle::circumcentre (Coordinate & resultPoint)
Computes the circumcentre of a triangle. The circumcentre is the centre of the circumcircle, the smallest circle which encloses the triangle. It is also the common intersection point of the perpendicular bisectors of the sides of the triangle, and is the only point which has equal distance to all three vertices of the triangle.
The circumcentre does not necessarily lie within the triangle. For example, the circumcentre of an obtuse isoceles triangle lies outside the triangle.
This method uses an algorithm due to J.R.Shewchuk which uses normalization to the origin to improve the accuracy of computation. (See Lecture Notes on Geometric Robustness, Jonathan Richard Shewchuk, 1999).
Parameters
resultPoint the point into which to write the inCentre of the triangle
Definition at line 36 of file Triangle.cpp.
References det(), p0, p1, p2, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
Referenced by geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCircumcentreVisitor::visit().
 {
   double cx = p2.x;
   double cy = p2.y;
   double ax = p0.x - cx;
   double ay = p0.y - cy;
   double bx = p1.x - cx;
   double by = p1.y - cy;
   double denom = 2 * det(ax,ay,bx,by);
   double numx = det(ay , ax * ax + ay * ay , by , bx * bx + by * by);
   double numy = det(ax, ax * ax + ay * ay, bx, bx * bx + by * by);
   double ccx = cx - numx / denom;
   double ccy = cy + numy / denom;
   result = Coordinate(ccx,ccy);
 }
double geos::geom::Triangle::det (double m00, double m01, double m10, double m11) const private
Computes the determinant of a 2x2 matrix. Uses standard double-precision arithmetic, so is susceptible to round-off error.
Parameters
m00 the [0,0] entry of the matrix
m01 the [0,1] entry of the matrix
m10 the [1,0] entry of the matrix
m11 the [1,1] entry of the matrix
Returns
the determinant
Definition at line 55 of file Triangle.cpp.
Referenced by circumcentre().
 {
   return m00 * m11 - m01 * m10;
 }
void geos::geom::Triangle::inCentre (Coordinate & resultPoint)
The inCentre of a triangle is the point which is equidistant from the sides of the triangle. This is also the point at which the bisectors of the angles meet.
Parameters
resultPoint the point into which to write the inCentre of the triangle
Definition at line 23 of file Triangle.cpp.
References geos::geom::Coordinate::distance(), p0, p1, p2, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   // the lengths of the sides, labelled by their opposite vertex
   double len0 = p1.distance(p2);
   double len1 = p0.distance(p2);
   double len2 = p0.distance(p1);
   double circum = len0 + len1 + len2;
   double inCentreX = (len0 * p0.x + len1 * p1.x +len2 * p2.x)  / circum;
   double inCentreY = (len0 * p0.y + len1 * p1.y +len2 * p2.y)  / circum;
   result = Coordinate(inCentreX, inCentreY);
 }
Member Data Documentation
Coordinate geos::geom::Triangle::p0
Definition at line 33 of file Triangle.h.
Referenced by circumcentre(), and inCentre().
Coordinate geos::geom::Triangle::p1
Definition at line 33 of file Triangle.h.
Referenced by circumcentre(), and inCentre().
Coordinate geos::geom::Triangle::p2
Definition at line 33 of file Triangle.h.
Referenced by circumcentre(), and inCentre().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/Triangle.h
/home/vicky/potree/geos/vicky/src/geom/Triangle.cpp