GEOS: geos::operation::valid::SimpleNestedRingTester Class Reference
geos::operation::valid::SimpleNestedRingTester Class Reference
Tests whether any of a set of LinearRings are nested inside another ring in the set, using a simple O(n^2) comparison.
#include <SimpleNestedRingTester.h>
Public Member Functions
SimpleNestedRingTester (geomgraph::GeometryGraph *newGraph)
~SimpleNestedRingTester ()
void add (geom::LinearRing *ring)
geom::Coordinate * getNestedPoint ()
bool isNonNested ()
Private Attributes
geomgraph::GeometryGraph * graph
std::vector< geom::LinearRing * > rings
geom::Coordinate * nestedPt
Detailed Description
Tests whether any of a set of LinearRings are nested inside another ring in the set, using a simple O(n^2) comparison.
Definition at line 54 of file SimpleNestedRingTester.h.
Constructor & Destructor Documentation
geos::operation::valid::SimpleNestedRingTester::SimpleNestedRingTester (geomgraph::GeometryGraph * newGraph) inline
Definition at line 60 of file SimpleNestedRingTester.h.
     :
     graph(newGraph),
     rings(),
     nestedPt(nullptr)
   {}
geos::operation::valid::SimpleNestedRingTester::~SimpleNestedRingTester () inline
Definition at line 67 of file SimpleNestedRingTester.h.
{
   }
Member Function Documentation
void geos::operation::valid::SimpleNestedRingTester::add (geom::LinearRing * ring) inline
Definition at line 70 of file SimpleNestedRingTester.h.
{
     rings.push_back(ring);
   }
geom::Coordinate* geos::operation::valid::SimpleNestedRingTester::getNestedPoint () inline
Definition at line 80 of file SimpleNestedRingTester.h.
{
     return nestedPt;
   }
bool geos::operation::valid::SimpleNestedRingTester::isNonNested ()
Definition at line 36 of file SimpleNestedRingTester.cpp.
References geos::geom::LineString::getCoordinates(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::intersects(), and geos::algorithm::CGAlgorithms::isPointInRing().
 {
   for(size_t i=0, ni=rings.size(); i<ni; i++) {
     LinearRing* innerRing=rings[i];
     CoordinateSequence *innerRingPts=innerRing->getCoordinates();
     for(size_t j=0, nj=rings.size(); j<nj; j++) {
       LinearRing* searchRing=rings[j];
       CoordinateSequence *searchRingPts=searchRing->getCoordinates();
       if (innerRing==searchRing)
         continue;
       if (!innerRing->getEnvelopeInternal()->intersects(searchRing->getEnvelopeInternal()))
         continue;
       const Coordinate *innerRingPt=IsValidOp::findPtNotNode(innerRingPts,searchRing,graph);
       // Unable to find a ring point not a node of the search ring
       assert(innerRingPt!=nullptr);
       bool isInside=CGAlgorithms::isPointInRing(*innerRingPt,searchRingPts);
       if (isInside) {
         /*
          * innerRingPt is const just because the input
          * CoordinateSequence is const. If the input
          * Polygon survives lifetime of this object
          * we are safe.
          */
         nestedPt=const_cast<Coordinate *>(innerRingPt);
         return false;
       }
     }
   }
   return true;
 }
Member Data Documentation
geomgraph::GeometryGraph* geos::operation::valid::SimpleNestedRingTester::graph private
Definition at line 56 of file SimpleNestedRingTester.h.
geom::Coordinate* geos::operation::valid::SimpleNestedRingTester::nestedPt private
Definition at line 58 of file SimpleNestedRingTester.h.
std::vector<geom::LinearRing*> geos::operation::valid::SimpleNestedRingTester::rings private
Definition at line 57 of file SimpleNestedRingTester.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/valid/SimpleNestedRingTester.h
/home/vicky/potree/geos/vicky/src/operation/valid/SimpleNestedRingTester.cpp