GEOS: geos::operation::overlay::snap::SnapOverlayOp Class Reference
geos::operation::overlay::snap::SnapOverlayOp Class Reference
Performs an overlay operation using snapping and enhanced precision to improve the robustness of the result.
#include <SnapOverlayOp.h>
Public Types
typedef std::unique_ptr< geom::Geometry > GeomPtr
Public Member Functions
SnapOverlayOp (const geom::Geometry &g1, const geom::Geometry &g2)
GeomPtr getResultGeometry (OverlayOp::OpCode opCode)
Static Public Member Functions
static std::unique_ptr< geom::Geometry > overlayOp (const geom::Geometry &g0, const geom::Geometry &g1, OverlayOp::OpCode opCode)
static std::unique_ptr< geom::Geometry > intersection (const geom::Geometry &g0, const geom::Geometry &g1)
static std::unique_ptr< geom::Geometry > Union (const geom::Geometry &g0, const geom::Geometry &g1)
static std::unique_ptr< geom::Geometry > difference (const geom::Geometry &g0, const geom::Geometry &g1)
static std::unique_ptr< geom::Geometry > symDifference (const geom::Geometry &g0, const geom::Geometry &g1)
Private Member Functions
void computeSnapTolerance ()
void snap (geom::GeomPtrPair &ret)
void removeCommonBits (const geom::Geometry &geom0, const geom::Geometry &geom1, geom::GeomPtrPair &ret)
void prepareResult (geom::Geometry &geom)
SnapOverlayOp (const SnapOverlayOp &other)=delete
SnapOverlayOp & operator= (const SnapOverlayOp &rhs)=delete
Private Attributes
const geom::Geometry & geom0
const geom::Geometry & geom1
double snapTolerance
std::unique_ptr< precision::CommonBitsRemover > cbr
Detailed Description
Performs an overlay operation using snapping and enhanced precision to improve the robustness of the result.
This class always uses snapping. This is less performant than the standard JTS overlay code, and may even introduce errors which were not present in the original data. For this reason, this class should only be used if the standard overlay code fails to produce a correct result.
Definition at line 56 of file SnapOverlayOp.h.
Member Typedef Documentation
typedef std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapOverlayOp::GeomPtr
Definition at line 102 of file SnapOverlayOp.h.
Constructor & Destructor Documentation
geos::operation::overlay::snap::SnapOverlayOp::SnapOverlayOp (const geom::Geometry & g1, const geom::Geometry & g2) inline
Definition at line 93 of file SnapOverlayOp.h.
     :
     geom0(g1),
     geom1(g2)
   {
     computeSnapTolerance();
   }
geos::operation::overlay::snap::SnapOverlayOp::SnapOverlayOp (const SnapOverlayOp & other) private delete
Member Function Documentation
void geos::operation::overlay::snap::SnapOverlayOp::computeSnapTolerance () private
Definition at line 42 of file SnapOverlayOp.cpp.
 {
   snapTolerance = GeometrySnapper::computeOverlaySnapTolerance(geom0,
                                                                geom1);
   // cout << "Snap tol = " <<  snapTolerance << endl;
 }
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapOverlayOp::difference (const geom::Geometry & g0, const geom::Geometry & g1) inline static
Definition at line 82 of file SnapOverlayOp.h.
   {
     return overlayOp(g0, g1, OverlayOp::opDIFFERENCE);
   }
unique_ptr< Geometry > geos::operation::overlay::snap::SnapOverlayOp::getResultGeometry (OverlayOp::OpCode opCode)
Definition at line 52 of file SnapOverlayOp.cpp.
References geos::geom::GeomPtrPair::first, and geos::geom::GeomPtrPair::second.
Referenced by overlayOp().
 {
   geom::GeomPtrPair prepGeom;
   snap(prepGeom);
   GeomPtr result ( OverlayOp::overlayOp(prepGeom.first.get(),
                                         prepGeom.second.get(), opCode) );
   prepareResult(*result);
   return result;
 }
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapOverlayOp::intersection (const geom::Geometry & g0, const geom::Geometry & g1) inline static
Definition at line 70 of file SnapOverlayOp.h.
   {
     return overlayOp(g0, g1, OverlayOp::opINTERSECTION);
   }
SnapOverlayOp& geos::operation::overlay::snap::SnapOverlayOp::operator= (const SnapOverlayOp & rhs) private delete
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapOverlayOp::overlayOp (const geom::Geometry & g0, const geom::Geometry & g1, OverlayOp::OpCode opCode) inline static
Definition at line 62 of file SnapOverlayOp.h.
References getResultGeometry().
   {
     SnapOverlayOp op(g0, g1);
     return op.getResultGeometry(opCode);
   }
void geos::operation::overlay::snap::SnapOverlayOp::prepareResult (geom::Geometry & geom) private
Definition at line 100 of file SnapOverlayOp.cpp.
 {
     cbr->addCommonBits(&geom);
 }
void geos::operation::overlay::snap::SnapOverlayOp::removeCommonBits (const geom::Geometry & geom0, const geom::Geometry & geom1, geom::GeomPtrPair & ret) private
Definition at line 86 of file SnapOverlayOp.cpp.
References geos::geom::Geometry::clone(), geos::geom::GeomPtrPair::first, and geos::geom::GeomPtrPair::second.
 {
   cbr.reset(new precision::CommonBitsRemover());
   cbr->add(&geom0);
   cbr->add(&geom1);
   remGeom.first.reset( cbr->removeCommonBits(geom0.clone()) );
   remGeom.second.reset( cbr->removeCommonBits(geom1.clone()) );
 }
void geos::operation::overlay::snap::SnapOverlayOp::snap (geom::GeomPtrPair & ret) private
Definition at line 64 of file SnapOverlayOp.cpp.
References geos::geom::GeomPtrPair::first, and geos::geom::GeomPtrPair::second.
 {
   geom::GeomPtrPair remGeom;
   removeCommonBits(geom0, geom1, remGeom);
   GeometrySnapper::snap(*remGeom.first, *remGeom.second,
                         snapTolerance, snapGeom);
     // MD - may want to do this at some point, but it adds cycles
 //    checkValid(snapGeom[0]);
 //    checkValid(snapGeom[1]);
     /*
     System.out.println("Snapped geoms: ");
     System.out.println(snapGeom[0]);
     System.out.println(snapGeom[1]);
     */
 }
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapOverlayOp::symDifference (const geom::Geometry & g0, const geom::Geometry & g1) inline static
Definition at line 88 of file SnapOverlayOp.h.
   {
     return overlayOp(g0, g1, OverlayOp::opSYMDIFFERENCE);
   }
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapOverlayOp::Union (const geom::Geometry & g0, const geom::Geometry & g1) inline static
Definition at line 76 of file SnapOverlayOp.h.
   {
     return overlayOp(g0, g1, OverlayOp::opUNION);
   }
Member Data Documentation
std::unique_ptr<precision::CommonBitsRemover> geos::operation::overlay::snap::SnapOverlayOp::cbr private
Definition at line 125 of file SnapOverlayOp.h.
const geom::Geometry& geos::operation::overlay::snap::SnapOverlayOp::geom0 private
Definition at line 120 of file SnapOverlayOp.h.
const geom::Geometry& geos::operation::overlay::snap::SnapOverlayOp::geom1 private
Definition at line 121 of file SnapOverlayOp.h.
double geos::operation::overlay::snap::SnapOverlayOp::snapTolerance private
Definition at line 123 of file SnapOverlayOp.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/snap/SnapOverlayOp.h
/home/vicky/potree/geos/vicky/src/operation/overlay/snap/SnapOverlayOp.cpp