GEOS: geos::operation::relate::RelateNode Class Reference
geos::operation::relate::RelateNode Class Reference
Represents a node in the topological graph used to compute spatial relationships.
#include <RelateNode.h>
Public Member Functions
RelateNode (const geom::Coordinate &coord, geomgraph::EdgeEndStar *edges)
~RelateNode () override
void updateIMFromEdges (geom::IntersectionMatrix &im)
virtual const geom::Coordinate & getCoordinate () const
virtual EdgeEndStar * getEdges ()
bool isIsolated () const override
virtual void add (EdgeEnd *e)
Add the edge to the list of edges at this node.
virtual void mergeLabel (const Node &n)
virtual void mergeLabel (const Label &label2)
To merge labels for two nodes, the merged location for each LabelElement is computed.
virtual void setLabel (int argIndex, int onLocation)
void setLabel (const Label &newLabel)
virtual void setLabelBoundary (int argIndex)
Updates the label of a node to BOUNDARY, obeying the mod-2 boundaryDetermination rule.
virtual int computeMergedLocation (const Label &label2, int eltIndex)
virtual std::string print ()
virtual const std::vector< double > & getZ () const
virtual void addZ (double)
virtual bool isIncidentEdgeInResult () const
Tests whether any incident edge is flagged as being in the result.
Label & getLabel ()
const Label & getLabel () const
virtual void setInResult (bool isInResult)
virtual bool isInResult () const
virtual void setCovered (bool isCovered)
virtual bool isCovered () const
virtual bool isCoveredSet () const
virtual bool isVisited () const
virtual void setVisited (bool isVisited)
virtual void updateIM (geom::IntersectionMatrix &im)
Protected Member Functions
void computeIM (geom::IntersectionMatrix &im) override
void testInvariant () const
Protected Attributes
geom::Coordinate coord
EdgeEndStar * edges
Label label
Detailed Description
Represents a node in the topological graph used to compute spatial relationships.
Definition at line 46 of file RelateNode.h.
Constructor & Destructor Documentation
geos::operation::relate::RelateNode::RelateNode (const geom::Coordinate & coord, geomgraph::EdgeEndStar * edges)
Definition at line 35 of file RelateNode.cpp.
                                                                  :
   Node(coord,edges)
 {}
geos::operation::relate::RelateNode::~RelateNode () override
Definition at line 39 of file RelateNode.cpp.
 {
 }
Member Function Documentation
void geos::geomgraph::Node::add (EdgeEnd * e) virtual inherited
Add the edge to the list of edges at this node.
Definition at line 136 of file Node.cpp.
References geos::geomgraph::Node::addZ(), geos::geomgraph::Node::coord, geos::geomgraph::Node::edges, geos::geom::Coordinate::equals2D(), geos::geomgraph::EdgeEnd::getCoordinate(), geos::geomgraph::EdgeEndStar::insert(), geos::geomgraph::EdgeEnd::print(), geos::geomgraph::EdgeEnd::setNode(), geos::geomgraph::Node::testInvariant(), and geos::geom::Coordinate::z.
Referenced by geos::geomgraph::NodeMap::add().
 {
   assert(e);
 #if GEOS_DEBUG
   cerr<<"["<<this<<"] Node::add("<<e->print()<<")"<<endl;
 #endif
   // Assert: start pt of e is equal to node point
   if ( ! e->getCoordinate().equals2D(coord) ) {
     std::stringstream ss;
     ss << "EdgeEnd with coordinate " << e->getCoordinate()
        << " invalid for node " << coord;
     throw util::IllegalArgumentException(ss.str());
   }
   // It seems it's legal for edges to be NULL
   // we'd not be honouring the promise of adding
   // an EdgeEnd in this case, though ...
   assert(edges);
   //if (edges==NULL) return;
   edges->insert(e);
   e->setNode(this);
 #if COMPUTE_Z
   addZ(e->getCoordinate().z);
 #endif
   testInvariant();
 }
void geos::geomgraph::Node::addZ (double z) virtual inherited
Definition at line 243 of file Node.cpp.
References geos::geomgraph::Node::coord, geos::geom::Coordinate::z, geos::geomgraph::Node::ztot, and geos::geomgraph::Node::zvals.
Referenced by geos::geomgraph::Node::add(), geos::geomgraph::NodeMap::addNode(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), geos::operation::overlay::OverlayOp::mergeZ(), and geos::geomgraph::Node::Node().
 {
 #if GEOS_DEBUG
   cerr<<"["<<this<<"] Node::addZ("<<z<<")";
 #endif
   if ( ISNAN(z) )
   {
 #if GEOS_DEBUG
     cerr<<" skipped"<<endl;
 #endif
     return;
   }
   if ( find(zvals.begin(), zvals.end(), z) != zvals.end() )
   {
 #if GEOS_DEBUG
     cerr<<" already stored"<<endl;
 #endif
     return;
   }
   zvals.push_back(z);
   ztot+=z;
   coord.z = ztot / static_cast<double>(zvals.size());
 #if GEOS_DEBUG
   cerr<<" added "<<z<<": ["<<ztot<<"/"<<zvals.size()<<"="<<coord.z<<"]"<<endl;
 #endif
 }
void geos::operation::relate::RelateNode::computeIM (geom::IntersectionMatrix & im) override protected virtual
Update the IM with the contribution for this component. A component only contributes if it has a labelling for both parent geometries
Reimplemented from geos::geomgraph::Node.
Definition at line 48 of file RelateNode.cpp.
References geos::geomgraph::Label::getLocation(), geos::geomgraph::GraphComponent::label, and geos::geom::IntersectionMatrix::setAtLeastIfValid().
 {
   im.setAtLeastIfValid(label.getLocation(0), label.getLocation(1),0);
 }
int geos::geomgraph::Node::computeMergedLocation (const Label & label2, int eltIndex) virtual inherited
The location for a given eltIndex for a node will be one of { null, INTERIOR, BOUNDARY }. A node may be on both the boundary and the interior of a geometry; in this case, the rule is that the node is considered to be in the boundary. The merged location is the maximum of the two input values.
Definition at line 216 of file Node.cpp.
References geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isNull(), geos::geomgraph::GraphComponent::label, and geos::geomgraph::Node::testInvariant().
Referenced by geos::geomgraph::Node::mergeLabel().
 {
   int loc=Location::UNDEF;
   loc=label.getLocation(eltIndex);
   if (!label2.isNull(eltIndex)) {
     int nLoc=label2.getLocation(eltIndex);
     if (loc!=Location::BOUNDARY) loc=nLoc;
   }
   testInvariant();
   return loc;
 }
const Coordinate & geos::geomgraph::Node::getCoordinate () const virtual inherited
Definition at line 91 of file Node.cpp.
References geos::geomgraph::Node::coord, and geos::geomgraph::Node::testInvariant().
Referenced by geos::geomgraph::NodeMap::addNode(), geos::operation::buffer::BufferSubgraph::computeNodeDepth(), geos::operation::relate::RelateNodeGraph::copyNodesAndLabels(), geos::operation::relate::RelateComputer::copyNodesAndLabels(), geos::operation::overlay::OverlayOp::copyPoints(), geos::operation::overlay::PointBuilder::filterCoveredNodeToPoint(), geos::geomgraph::GeometryGraph::getBoundaryPoints(), geos::geomgraph::index::SegmentIntersector::isBoundaryPoint(), geos::operation::valid::ConsistentAreaTester::isNodeEdgeAreaLabelsConsistent(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), geos::operation::relate::RelateComputer::labelIsolatedNode(), geos::operation::overlay::OverlayOp::mergeZ(), geos::geomgraph::EdgeEnd::setNode(), and geos::geomgraph::NodeMap::testInvariant().
 {
   testInvariant();
   return coord;
 }
EdgeEndStar * geos::geomgraph::Node::getEdges () virtual inherited
Definition at line 99 of file Node.cpp.
References geos::geomgraph::Node::edges, and geos::geomgraph::Node::testInvariant().
Referenced by geos::operation::buffer::BufferSubgraph::add(), geos::operation::buffer::BufferSubgraph::computeDepths(), geos::operation::overlay::OverlayOp::computeLabelling(), geos::geomgraph::EdgeRing::computeMaxNodeDegree(), geos::operation::buffer::BufferSubgraph::computeNodeDepth(), geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode(), geos::operation::valid::ConsistentAreaTester::hasDuplicateRings(), geos::operation::valid::ConsistentAreaTester::isNodeEdgeAreaLabelsConsistent(), geos::operation::overlay::OverlayOp::labelIncompleteNodes(), geos::operation::relate::RelateComputer::labelNodeEdges(), geos::geomgraph::PlanarGraph::linkAllDirectedEdges(), geos::operation::overlay::MaximalEdgeRing::linkDirectedEdgesForMinimalEdgeRings(), geos::geomgraph::PlanarGraph::linkResultDirectedEdges(), geos::operation::overlay::OverlayOp::mergeSymLabels(), and geos::operation::overlay::OverlayOp::updateNodeLabelling().
 {
   testInvariant();
   return edges;
 }
Label& geos::geomgraph::GraphComponent::getLabel () inline inherited
Definition at line 57 of file GraphComponent.h.
Referenced by geos::geomgraph::GeometryGraph::addSelfIntersectionNodes(), geos::geomgraph::DirectedEdge::computeDirectedLabel(), geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), geos::geomgraph::DirectedEdgeStar::computeLabelling(), geos::operation::relate::RelateNodeGraph::copyNodesAndLabels(), geos::operation::relate::RelateComputer::copyNodesAndLabels(), geos::operation::overlay::OverlayOp::copyPoints(), geos::operation::relate::EdgeEndBuilder::createEdgeEndForNext(), geos::operation::relate::EdgeEndBuilder::createEdgeEndForPrev(), geos::geomgraph::EdgeIntersectionList::createSplitEdge(), geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes(), geos::geomgraph::NodeMap::getBoundaryNodes(), geos::geomgraph::GeometryGraph::insertBoundaryPoint(), geos::geomgraph::GeometryGraph::insertPoint(), geos::operation::overlay::OverlayOp::insertUniqueEdge(), geos::operation::buffer::BufferBuilder::insertUniqueEdge(), geos::geomgraph::PlanarGraph::isBoundaryNode(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), geos::operation::overlay::OverlayOp::labelIncompleteNodes(), geos::operation::relate::RelateComputer::labelIntersectionNodes(), geos::operation::relate::RelateComputer::labelIsolatedEdge(), geos::operation::overlay::LineBuilder::labelIsolatedLine(), geos::operation::overlay::LineBuilder::labelIsolatedLines(), geos::operation::relate::RelateComputer::labelIsolatedNode(), geos::operation::relate::RelateComputer::labelIsolatedNodes(), and geos::operation::overlay::OverlayOp::updateNodeLabelling().
 { return label; }
const Label& geos::geomgraph::GraphComponent::getLabel () const inline inherited
Definition at line 58 of file GraphComponent.h.
 { return label; }
const vector< double > & geos::geomgraph::Node::getZ () const virtual inherited
Definition at line 272 of file Node.cpp.
References geos::geomgraph::Node::zvals.
Referenced by geos::geomgraph::NodeMap::addNode().
 {
   return zvals;
 }
virtual bool geos::geomgraph::GraphComponent::isCovered () const inline virtual inherited
Definition at line 64 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::collectLineEdge(), and geos::geomgraph::GraphComponent::setCovered().
 { return isCoveredVar; }
virtual bool geos::geomgraph::GraphComponent::isCoveredSet () const inline virtual inherited
Definition at line 65 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::findCoveredLineEdges().
 { return isCoveredSetVar; }
bool geos::geomgraph::Node::isIncidentEdgeInResult () const virtual inherited
Tests whether any incident edge is flagged as being in the result.
This test can be used to determine if the node is in the result, since if any incident edge is in the result, the node must be in the result as well.
Returns
true if any indicident edge in the in the result
Definition at line 117 of file Node.cpp.
References geos::geomgraph::EdgeEndStar::begin(), geos::geomgraph::Node::edges, geos::geomgraph::EdgeEndStar::end(), geos::geomgraph::EdgeEnd::getEdge(), geos::geomgraph::GraphComponent::isInResult(), and geos::geomgraph::Node::testInvariant().
Referenced by geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes().
 {
   testInvariant();
   if (!edges) return false;
   EdgeEndStar::iterator it=edges->begin();
   EdgeEndStar::iterator endIt=edges->end();
   for ( ; it!=endIt; ++it)
   {
     assert(*it);
     assert(dynamic_cast<DirectedEdge *>(*it));
     DirectedEdge *de = static_cast<DirectedEdge *>(*it);
     if ( de->getEdge()->isInResult() ) return true;
   }
   return false;
 }
virtual bool geos::geomgraph::GraphComponent::isInResult () const inline virtual inherited
Definition at line 62 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::collectBoundaryTouchEdge(), geos::operation::overlay::PointBuilder::extractNonCoveredResultNodes(), and geos::geomgraph::Node::isIncidentEdgeInResult().
 { return isInResultVar; }
bool geos::geomgraph::Node::isIsolated () const override virtual inherited
Implements geos::geomgraph::GraphComponent.
Definition at line 108 of file Node.cpp.
References geos::geomgraph::Label::getGeometryCount(), geos::geomgraph::GraphComponent::label, and geos::geomgraph::Node::testInvariant().
Referenced by geos::operation::overlay::OverlayOp::labelIncompleteNodes(), and geos::operation::relate::RelateComputer::labelIsolatedNodes().
 {
   testInvariant();
   return (label.getGeometryCount()==1);
 }
virtual bool geos::geomgraph::GraphComponent::isVisited () const inline virtual inherited
Definition at line 66 of file GraphComponent.h.
Referenced by geos::operation::buffer::BufferSubgraph::add(), and geos::operation::buffer::BufferBuilder::createSubgraphs().
 { return isVisitedVar; }
void geos::geomgraph::Node::mergeLabel (const Node & n) virtual inherited
Definition at line 166 of file Node.cpp.
References geos::geomgraph::Label::isNull(), geos::geomgraph::GraphComponent::label, and geos::geomgraph::Node::testInvariant().
Referenced by geos::geomgraph::NodeMap::addNode().
 {
   assert(!n.label.isNull());
   mergeLabel(n.label);
   testInvariant();
 }
void geos::geomgraph::Node::mergeLabel (const Label & label2) virtual inherited
To merge labels for two nodes, the merged location for each LabelElement is computed.
The location for the corresponding node LabelElement is set to the result, as long as the location is non-null.
Definition at line 175 of file Node.cpp.
References geos::geomgraph::Node::computeMergedLocation(), geos::geomgraph::Label::getLocation(), geos::geomgraph::GraphComponent::label, geos::geomgraph::Label::setLocation(), and geos::geomgraph::Node::testInvariant().
 {
   for (int i=0; i<2; i++) {
     int loc=computeMergedLocation(label2, i);
     int thisLoc=label.getLocation(i);
     if (thisLoc==Location::UNDEF) label.setLocation(i,loc);
   }
   testInvariant();
 }
string geos::geomgraph::Node::print () virtual inherited
Definition at line 232 of file Node.cpp.
References geos::geomgraph::Node::testInvariant().
Referenced by geos::geomgraph::NodeMap::addNode(), geos::operation::overlay::OverlayOp::computeLabelling(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), geos::operation::overlay::OverlayOp::mergeSymLabels(), geos::geomgraph::NodeMap::print(), and geos::operation::overlay::OverlayOp::updateNodeLabelling().
 {
   testInvariant();
   ostringstream ss;
   ss<<*this;
   return ss.str();
 }
void geos::geomgraph::GraphComponent::setCovered (bool isCovered) virtual inherited
Definition at line 55 of file GraphComponent.cpp.
References geos::geomgraph::GraphComponent::isCovered(), geos::geomgraph::GraphComponent::isCoveredSetVar, and geos::geomgraph::GraphComponent::isCoveredVar.
Referenced by geos::operation::overlay::LineBuilder::findCoveredLineEdges(), and geos::geomgraph::DirectedEdgeStar::findCoveredLineEdges().
 {
   isCoveredVar = isCovered;
   isCoveredSetVar = true;
 }
virtual void geos::geomgraph::GraphComponent::setInResult (bool isInResult) inline virtual inherited
Definition at line 61 of file GraphComponent.h.
Referenced by geos::operation::overlay::LineBuilder::buildLines(), and geos::geomgraph::EdgeRing::setInResult().
 { isInResultVar=isInResult; }
void geos::geomgraph::GraphComponent::setLabel (const Label & newLabel) inline inherited
Definition at line 59 of file GraphComponent.h.
 { label = newLabel; }
void geos::geomgraph::Node::setLabel (int argIndex, int onLocation) virtual inherited
Definition at line 187 of file Node.cpp.
References geos::geomgraph::Label::isNull(), geos::geomgraph::GraphComponent::label, geos::geomgraph::Label::setLocation(), and geos::geomgraph::Node::testInvariant().
Referenced by geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), geos::operation::relate::RelateNodeGraph::copyNodesAndLabels(), geos::operation::relate::RelateComputer::copyNodesAndLabels(), geos::operation::overlay::OverlayOp::copyPoints(), geos::geomgraph::GeometryGraph::insertPoint(), and geos::operation::relate::RelateComputer::labelIntersectionNodes().
 {
   if ( label.isNull() ) {
     label = Label(argIndex, onLocation);
   } else
     label.setLocation(argIndex, onLocation);
   testInvariant();
 }
void geos::geomgraph::Node::setLabelBoundary (int argIndex) virtual inherited
Updates the label of a node to BOUNDARY, obeying the mod-2 boundaryDetermination rule.
Definition at line 199 of file Node.cpp.
References geos::geomgraph::Label::getLocation(), geos::geomgraph::GraphComponent::label, geos::geomgraph::Label::setLocation(), and geos::geomgraph::Node::testInvariant().
Referenced by geos::operation::relate::RelateNodeGraph::computeIntersectionNodes(), geos::operation::relate::RelateComputer::computeIntersectionNodes(), and geos::operation::relate::RelateComputer::labelIntersectionNodes().
 {
   int loc = label.getLocation(argIndex);
   // flip the loc
   int newLoc;
   switch (loc){
     case Location::BOUNDARY: newLoc=Location::INTERIOR; break;
     case Location::INTERIOR: newLoc=Location::BOUNDARY; break;
     default: newLoc=Location::BOUNDARY;  break;
   }
   label.setLocation(argIndex, newLoc);
   testInvariant();
 }
virtual void geos::geomgraph::GraphComponent::setVisited (bool isVisited) inline virtual inherited
Definition at line 67 of file GraphComponent.h.
Referenced by geos::operation::buffer::BufferSubgraph::add().
 { isVisitedVar = isVisited; }
void geos::geomgraph::Node::testInvariant () const inline protected inherited
Definition at line 156 of file Node.h.
References geos::geom::Coordinate::equals2D(), and geos::geomgraph::EdgeEnd::getCoordinate().
Referenced by geos::geomgraph::Node::add(), geos::geomgraph::Node::computeMergedLocation(), geos::geomgraph::Node::getCoordinate(), geos::geomgraph::Node::getEdges(), geos::geomgraph::Node::isIncidentEdgeInResult(), geos::geomgraph::Node::isIsolated(), geos::geomgraph::Node::mergeLabel(), geos::geomgraph::Node::Node(), geos::geomgraph::Node::print(), geos::geomgraph::Node::setLabel(), geos::geomgraph::Node::setLabelBoundary(), and geos::geomgraph::Node::~Node().
 {
 #ifndef NDEBUG
   if (edges)
   {
     // Each EdgeEnd in the star has this Node's
     // coordinate as first coordinate
     for (EdgeEndStar::iterator
         it=edges->begin(), itEnd=edges->end();
         it != itEnd; it++)
     {
       EdgeEnd* e=*it;
       assert(e);
       assert(e->getCoordinate().equals2D(coord));
     }
   }
 #if 0 // We can't rely on numerical stability with FP computations
   // ztot is the sum of doubnle sin zvals vector
   double ztot_check=0.0;
   for (std::vector<double>::const_iterator
       i = zvals.begin(), e = zvals.end();
       i != e;
       i++)
   {
     ztot_check += *i;
   }
   assert(ztot_check == ztot);
 #endif // 0
 #endif
 }
void geos::geomgraph::GraphComponent::updateIM (geom::IntersectionMatrix & im) virtual inherited
Definition at line 62 of file GraphComponent.cpp.
References geos::geomgraph::GraphComponent::computeIM(), geos::geomgraph::Label::getGeometryCount(), and geos::geomgraph::GraphComponent::label.
Referenced by geos::operation::relate::RelateComputer::updateIM().
 {
   assert(label.getGeometryCount() >= 2); // found partial label
   computeIM(im);
 }
void geos::operation::relate::RelateNode::updateIMFromEdges (geom::IntersectionMatrix & im)
Update the IM with the contribution for the EdgeEnds incident on this node.
Definition at line 54 of file RelateNode.cpp.
References geos::geomgraph::Node::edges, and geos::operation::relate::EdgeEndBundleStar::updateIM().
Referenced by geos::operation::relate::RelateComputer::updateIM().
 {
   assert(dynamic_cast<EdgeEndBundleStar*>(edges));
   EdgeEndBundleStar* eebs=static_cast<EdgeEndBundleStar*>(edges);
   eebs->updateIM(im);
 }
Member Data Documentation
geom::Coordinate geos::geomgraph::Node::coord protected inherited
Definition at line 136 of file Node.h.
Referenced by geos::geomgraph::Node::add(), geos::geomgraph::Node::addZ(), geos::geomgraph::Node::getCoordinate(), and geos::geomgraph::operator<<().
EdgeEndStar* geos::geomgraph::Node::edges protected inherited
Definition at line 138 of file Node.h.
Referenced by geos::geomgraph::Node::add(), geos::geomgraph::Node::getEdges(), geos::geomgraph::Node::isIncidentEdgeInResult(), geos::geomgraph::Node::Node(), updateIMFromEdges(), and geos::geomgraph::Node::~Node().
Label geos::geomgraph::GraphComponent::label protected inherited
Definition at line 71 of file GraphComponent.h.
Referenced by computeIM(), geos::geomgraph::Node::computeMergedLocation(), geos::geomgraph::Edge::getCollapsedEdge(), geos::geomgraph::Edge::isCollapsed(), geos::geomgraph::Node::isIsolated(), geos::geomgraph::Node::mergeLabel(), geos::geomgraph::operator<<(), geos::geomgraph::Edge::printReverse(), geos::geomgraph::Node::setLabel(), geos::geomgraph::Node::setLabelBoundary(), and geos::geomgraph::GraphComponent::updateIM().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/relate/RelateNode.h
/home/vicky/potree/geos/vicky/src/operation/relate/RelateNode.cpp