GEOS: geos::operation::geounion::UnaryUnionOp Class Reference
geos::operation::geounion::UnaryUnionOp Class Reference
#include <UnaryUnionOp.h>
Public Member Functions
template<class T >
UnaryUnionOp (const T &geoms, geom::GeometryFactory &geomFactIn)
template<class T >
UnaryUnionOp (const T &geoms)
UnaryUnionOp (const geom::Geometry &geom)
std::unique_ptr< geom::Geometry > Union ()
Gets the union of the input geometries.
Static Public Member Functions
template<typename T >
static std::unique_ptr< geom::Geometry > Union (const T &geoms)
template<class T >
static std::unique_ptr< geom::Geometry > Union (const T &geoms, geom::GeometryFactory &geomFact)
static std::unique_ptr< geom::Geometry > Union (const geom::Geometry &geom)
Private Member Functions
template<typename T >
void extractGeoms (const T &geoms)
void extract (const geom::Geometry &geom)
std::unique_ptr< geom::Geometry > unionNoOpt (const geom::Geometry &g0)
std::unique_ptr< geom::Geometry > unionWithNull (std::unique_ptr< geom::Geometry > g0, std::unique_ptr< geom::Geometry > g1)
Private Attributes
std::vector< const geom::Polygon * > polygons
std::vector< const geom::LineString * > lines
std::vector< const geom::Point * > points
const geom::GeometryFactory * geomFact
std::unique_ptr< geom::Geometry > empty
Detailed Description
Unions a collection of Geometry or a single Geometry (which may be a collection) together. By using this special-purpose operation over a collection of geometries it is possible to take advantage of various optimizations to improve performance. Heterogeneous GeometryCollections are fully supported.
The result obeys the following contract:
Unioning a set of overlapping Polygonss has the effect of merging the areas (i.e. the same effect as iteratively unioning all individual polygons together).
Unioning a set of LineStrings has the effect of fully noding and dissolving the input linework. In this context "fully noded" means that there will be a node or endpoint in the output for every endpoint or line segment crossing in the input. "Dissolved" means that any duplicate (e.g. coincident) line segments or portions of line segments will be reduced to a single line segment in the output. * This is consistent with the semantics of the Geometry#union(Geometry) operation. If merged linework is required, the LineMerger class can be used.
Unioning a set of Pointss has the effect of merging al identical points (producing a set with no duplicates).
UnaryUnion always operates on the individual components of MultiGeometries. So it is possible to use it to "clean" invalid self-intersecting MultiPolygons (although the polygon components must all still be individually valid.)
Definition at line 85 of file UnaryUnionOp.h.
Constructor & Destructor Documentation
template<class T > geos::operation::geounion::UnaryUnionOp::UnaryUnionOp (const T & geoms, geom::GeometryFactory & geomFactIn) inline
Definition at line 111 of file UnaryUnionOp.h.
       :
       geomFact(&geomFactIn)
   {
     extractGeoms(geoms);
   }
template<class T > geos::operation::geounion::UnaryUnionOp::UnaryUnionOp (const T & geoms) inline
Definition at line 119 of file UnaryUnionOp.h.
       :
       geomFact(nullptr)
   {
     extractGeoms(geoms);
   }
geos::operation::geounion::UnaryUnionOp::UnaryUnionOp (const geom::Geometry & geom) inline
Definition at line 126 of file UnaryUnionOp.h.
       :
       geomFact(geom.getFactory())
   {
     extract(geom);
   }
Member Function Documentation
void geos::operation::geounion::UnaryUnionOp::extract (const geom::Geometry & geom) inline private
Definition at line 161 of file UnaryUnionOp.h.
References geos::geom::Geometry::getFactory().
   {
       using namespace geom::util;
       if ( ! geomFact ) geomFact = geom.getFactory();
       GeometryExtracter::extract<geom::Polygon>(geom, polygons);
       GeometryExtracter::extract<geom::LineString>(geom, lines);
       GeometryExtracter::extract<geom::Point>(geom, points);
   }
template<typename T > void geos::operation::geounion::UnaryUnionOp::extractGeoms (const T & geoms) inline private
Definition at line 148 of file UnaryUnionOp.h.
   {
       for (typename T::const_iterator
               i=geoms.begin(),
               e=geoms.end();
               i!=e;
               ++i)
       {
           const geom::Geometry* geom = *i;
           extract(*geom);
       }
   }
template<typename T > static std::unique_ptr<geom::Geometry> geos::operation::geounion::UnaryUnionOp::Union (const T & geoms) inline static
Definition at line 90 of file UnaryUnionOp.h.
References Union().
Referenced by Union().
   {
     UnaryUnionOp op(geoms);
     return op.Union();
   }
template<class T > static std::unique_ptr<geom::Geometry> geos::operation::geounion::UnaryUnionOp::Union (const T & geoms, geom::GeometryFactory & geomFact) inline static
Definition at line 97 of file UnaryUnionOp.h.
References Union().
   {
     UnaryUnionOp op(geoms, geomFact);
     return op.Union();
   }
static std::unique_ptr<geom::Geometry> geos::operation::geounion::UnaryUnionOp::Union (const geom::Geometry & geom) inline static
Definition at line 104 of file UnaryUnionOp.h.
References Union().
   {
     UnaryUnionOp op(geom);
     return op.Union();
   }
std::unique_ptr< geom::Geometry > geos::operation::geounion::UnaryUnionOp::Union ()
Gets the union of the input geometries.
If no input geometries were provided, a POINT EMPTY is returned.
Returns
a Geometry containing the union
an empty GEOMETRYCOLLECTION if no geometries were provided in the input
For points and lines, only a single union operation is required, since the OGC model allowings self-intersecting MultiPoint and MultiLineStrings. This is not the case for polygons, so Cascaded Union is required.
Performing two unions is somewhat inefficient, but is mitigated by unioning lines and points first
Definition at line 61 of file UnaryUnionOp.cpp.
References geos::geom::GeometryFactory::buildGeometry(), geos::geom::GeometryFactory::createGeometryCollection(), geomFact, lines, points, polygons, geos::operation::geounion::PointGeometryUnion::Union(), geos::operation::geounion::CascadedUnion::Union(), geos::operation::geounion::CascadedPolygonUnion::Union(), unionNoOpt(), and unionWithNull().
 {
   using geom::Puntal;
   typedef std::unique_ptr<geom::Geometry> GeomPtr;
   GeomPtr ret;
   if ( ! geomFact ) return ret;
   GeomPtr unionPoints;
   if (!points.empty()) {
       GeomPtr ptGeom = geomFact->buildGeometry( points.begin(),
                                                     points.end()    );
       unionPoints = unionNoOpt(*ptGeom);
   }
   GeomPtr unionLines;
   if (!lines.empty()) {
       /* JTS compatibility NOTE:
        * we use cascaded here for robustness [1]
        * but also add a final unionNoOpt step to deal with
        * self-intersecting lines [2]
        *
        * [1](http://trac.osgeo.org/geos/ticket/392
        * [2](http://trac.osgeo.org/geos/ticket/482
        *
        */
       unionLines.reset( CascadedUnion::Union( lines.begin(),
                                               lines.end()   ) );
       unionLines = unionNoOpt(*unionLines);
   }
   GeomPtr unionPolygons;
   if (!polygons.empty()) {
       unionPolygons.reset( CascadedPolygonUnion::Union( polygons.begin(),
                                                         polygons.end()   ) );
   }
   GeomPtr unionLA = unionWithNull(std::move(unionLines), std::move(unionPolygons));
   assert(!unionLines.get()); assert(!unionPolygons.get());
   if ( ! unionPoints.get() ) {
     ret = std::move(unionLA);
     assert(!unionLA.get());
   }
   else if ( ! unionLA.get() ) {
     ret = std::move(unionPoints);
     assert(!unionPoints.get());
   }
   else {
     Puntal& up = dynamic_cast<Puntal&>(*unionPoints);
     ret = PointGeometryUnion::Union(up, *unionLA);
   }
   if ( ! ret.get() ) {
           ret.reset( geomFact->createGeometryCollection() );
   }
   return ret;
 }
std::unique_ptr<geom::Geometry> geos::operation::geounion::UnaryUnionOp::unionNoOpt (const geom::Geometry & g0) inline private
Computes a unary union with no extra optimization, and no short-circuiting. Due to the way the overlay operations are implemented, this is still efficient in the case of linear and puntal geometries. Uses robust version of overlay operation to ensure identical behaviour to the union(Geometry) operation.
Parameters
g0 a geometry
Returns
the union of the input geometry
Definition at line 184 of file UnaryUnionOp.h.
References geos::geom::BinaryOp().
Referenced by Union().
   {
     using geos::operation::overlay::OverlayOp;
     //using geos::operation::overlay::snap::SnapIfNeededOverlayOp;
     if ( ! empty.get() ) {
       empty.reset( geomFact->createEmptyGeometry() );
     }
     //return SnapIfNeededOverlayOp::overlayOp(g0, *empty, OverlayOp::opUNION);
     return BinaryOp(&g0, empty.get(), overlay::overlayOp(OverlayOp::opUNION));
   }
std::unique_ptr< geom::Geometry > geos::operation::geounion::UnaryUnionOp::unionWithNull (std::unique_ptr< geom::Geometry > g0, std::unique_ptr< geom::Geometry > g1) private
Computes the union of two geometries, either of both of which may be null.
Parameters
g0 a Geometry (ownership transferred)
g1 a Geometry (ownership transferred)
Returns
the union of the input(s)
null if both inputs are null
Definition at line 46 of file UnaryUnionOp.cpp.
Referenced by Union().
 {
   std::unique_ptr<geom::Geometry> ret;
   if ( ( ! g0.get() ) && ( ! g1.get() ) ) return ret;
   if ( ! g0.get() ) return g1;
   if ( ! g1.get() ) return g0;
   ret.reset( g0->Union(g1.get()) );
   return ret;
 }
Member Data Documentation
std::unique_ptr<geom::Geometry> geos::operation::geounion::UnaryUnionOp::empty private
Definition at line 214 of file UnaryUnionOp.h.
const geom::GeometryFactory* geos::operation::geounion::UnaryUnionOp::geomFact private
Definition at line 212 of file UnaryUnionOp.h.
Referenced by Union().
std::vector<const geom::LineString*> geos::operation::geounion::UnaryUnionOp::lines private
Definition at line 209 of file UnaryUnionOp.h.
Referenced by Union().
std::vector<const geom::Point*> geos::operation::geounion::UnaryUnionOp::points private
Definition at line 210 of file UnaryUnionOp.h.
Referenced by Union().
std::vector<const geom::Polygon*> geos::operation::geounion::UnaryUnionOp::polygons private
Definition at line 208 of file UnaryUnionOp.h.
Referenced by Union().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/union/UnaryUnionOp.h
/home/vicky/potree/geos/vicky/src/operation/union/UnaryUnionOp.cpp