GEOS: geos::precision::EnhancedPrecisionOp Class Reference
geos::precision::EnhancedPrecisionOp Class Reference
Provides versions of Geometry spatial functions which use enhanced precision techniques to reduce the likelihood of robustness problems.
#include <EnhancedPrecisionOp.h>
Static Public Member Functions
static geom::Geometry * intersection (const geom::Geometry *geom0, const geom::Geometry *geom1)
Computes the set-theoretic intersection of two Geometrys, using enhanced precision.
static geom::Geometry * Union (const geom::Geometry *geom0, const geom::Geometry *geom1)
static geom::Geometry * difference (const geom::Geometry *geom0, const geom::Geometry *geom1)
static geom::Geometry * symDifference (const geom::Geometry *geom0, const geom::Geometry *geom1)
static geom::Geometry * buffer (const geom::Geometry *geom, double distance)
Detailed Description
Provides versions of Geometry spatial functions which use enhanced precision techniques to reduce the likelihood of robustness problems.
Definition at line 40 of file EnhancedPrecisionOp.h.
Member Function Documentation
Geometry * geos::precision::EnhancedPrecisionOp::buffer (const geom::Geometry * geom, double distance) static
Computes the buffer of a Geometry, using enhanced precision. This method should no longer be necessary, since the buffer algorithm now is highly robust.
Parameters
geom0 the first Geometry
distance the buffer distance
Returns
the Geometry representing the buffer of the input Geometry.
Definition at line 211 of file EnhancedPrecisionOp.cpp.
References geos::precision::CommonBitsOp::buffer(), geos::geom::Geometry::buffer(), and geos::geom::Geometry::isValid().
 {
   util::GEOSException originalEx;
   try
   {
     Geometry *result = geom->buffer(distance);
     return result;
   }
   catch (const util::GEOSException& ex)
   {
     originalEx = ex;
   }
   /*
    * If we are here, the original op encountered a precision problem
    * (or some other problem)->  Retry the operation with
    * enhanced precision to see if it succeeds
    */
   try
   {
     CommonBitsOp cbo(true);
     Geometry *resultEP = cbo.buffer(geom, distance);
     // check that result is a valid geometry
     // after the reshift to orginal precision
     if (! resultEP->isValid())
       throw originalEx;
     return resultEP;
   }
   catch (const util::GEOSException& /* ex2 */)
   {
     throw originalEx;
   }
 }
Geometry * geos::precision::EnhancedPrecisionOp::difference (const geom::Geometry * geom0, const geom::Geometry * geom1) static
Computes the set-theoretic difference of two Geometrys, using enhanced precision.
Parameters
geom0 the first Geometry
geom1 the second Geometry
Returns
the Geometry representing the set-theoretic difference of the input Geometries.
Definition at line 132 of file EnhancedPrecisionOp.cpp.
References geos::precision::CommonBitsOp::difference(), geos::geom::Geometry::difference(), and geos::geom::Geometry::isValid().
 {
   util::GEOSException originalEx;
   try
   {
     Geometry *result = geom0->difference(geom1);
     return result;
   }
   catch (const util::GEOSException& ex)
   {
     originalEx = ex;
   }
   /*
    * If we are here, the original op encountered a precision problem
    * (or some other problem).  Retry the operation with
    * enhanced precision to see if it succeeds
    */
   try
   {
     CommonBitsOp cbo(true);
     Geometry *resultEP = cbo.difference(geom0, geom1);
     // check that result is a valid geometry after
     // the reshift to orginal precision
     if (! resultEP->isValid())
       throw originalEx;
     return resultEP;
   }
   catch (const util::GEOSException& /* ex2 */)
   {
     throw originalEx;
   }
 }
Geometry * geos::precision::EnhancedPrecisionOp::intersection (const geom::Geometry * geom0, const geom::Geometry * geom1) static
Computes the set-theoretic intersection of two Geometrys, using enhanced precision.
Parameters
geom0 the first Geometry
geom1 the second Geometry
Returns
the Geometry representing the set-theoretic intersection of the input Geometries.
Definition at line 41 of file EnhancedPrecisionOp.cpp.
References geos::precision::CommonBitsOp::intersection(), geos::geom::Geometry::intersection(), geos::geom::Geometry::isValid(), and geos::util::GEOSException::what().
 {
   util::GEOSException originalEx;
   try
   {
     Geometry *result = geom0->intersection(geom1);
     return result;
   }
   catch (const util::GEOSException& ex)
   {
     originalEx = ex;
   }
   /*
    * If we are here, the original op encountered a precision problem
    * (or some other problem). Retry the operation with
    * enhanced precision to see if it succeeds
    */
   try
   {
     CommonBitsOp cbo(true);
     Geometry *resultEP = cbo.intersection(geom0, geom1);
     // check that result is a valid geometry after
     // the reshift to orginal precision
     if (! resultEP->isValid())
     {
 #if GEOS_DEBUG
       std::cerr << "Reduced operation result is invalid"
                 << std::endl;
 #endif
       throw originalEx;
     }
     return resultEP;
   }
   catch (const util::GEOSException& ex2 )
   {
 #if GEOS_DEBUG
     std::cerr << "Reduced operation exception: "
               << ex2.what() << std::endl;
 #else
         (void)ex2;
 #endif
     throw originalEx;
   }
 }
Geometry * geos::precision::EnhancedPrecisionOp::symDifference (const geom::Geometry * geom0, const geom::Geometry * geom1) static
Computes the set-theoretic symmetric difference of two Geometrys, using enhanced precision.
Parameters
geom0 the first Geometry
geom1 the second Geometry
Returns
the Geometry representing the set-theoretic symmetric difference of the input Geometries.
Definition at line 172 of file EnhancedPrecisionOp.cpp.
References geos::geom::Geometry::isValid(), geos::precision::CommonBitsOp::symDifference(), and geos::geom::Geometry::symDifference().
 {
   util::GEOSException originalEx;
   try
   {
     Geometry *result = geom0->symDifference(geom1);
     return result;
   }
   catch (const util::GEOSException& ex)
   {
     originalEx = ex;
   }
   /*
    * If we are here, the original op encountered a precision problem
    * (or some other problem).  Retry the operation with
    * enhanced precision to see if it succeeds
    */
   try
   {
     CommonBitsOp cbo(true);
     Geometry* resultEP = cbo.symDifference(geom0, geom1);
     // check that result is a valid geometry after
     // the reshift to orginal precision
     if (! resultEP->isValid())
       throw originalEx;
     return resultEP;
   }
   catch (const util::GEOSException& /* ex2 */)
   {
     throw originalEx;
   }
 }
Geometry * geos::precision::EnhancedPrecisionOp::Union (const geom::Geometry * geom0, const geom::Geometry * geom1) static
Computes the set-theoretic union of two Geometrys, using enhanced precision.
Parameters
geom0 the first Geometry
geom1 the second Geometry
Returns
the Geometry representing the set-theoretic union of the input Geometries.
Definition at line 93 of file EnhancedPrecisionOp.cpp.
References geos::geom::Geometry::isValid(), geos::precision::CommonBitsOp::Union(), and geos::geom::Geometry::Union().
 {
   util::GEOSException originalEx;
   try
   {
     Geometry* result = geom0->Union(geom1);
     return result;
   }
   catch (const util::GEOSException& ex)
   {
     originalEx = ex;
   }
   /*
    * If we are here, the original op encountered a precision problem
    * (or some other problem)->  Retry the operation with
    * enhanced precision to see if it succeeds
    */
   try
   {
     CommonBitsOp cbo(true);
     Geometry *resultEP = cbo.Union(geom0, geom1);
     // check that result is a valid geometry after
     // the reshift to orginal precision
     if (! resultEP->isValid())
       throw originalEx;
     return resultEP;
   }
   catch (const util::GEOSException& /* ex2 */)
   {
     throw originalEx;
   }
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/precision/EnhancedPrecisionOp.h
/home/vicky/potree/geos/vicky/src/precision/EnhancedPrecisionOp.cpp