GEOS: geos::operation::buffer::RightmostEdgeFinder Class Reference
geos::operation::buffer::RightmostEdgeFinder Class Reference
A RightmostEdgeFinder find the geomgraph::DirectedEdge in a list which has the highest coordinate, and which is oriented L to R at that point. (I.e. the right side is on the RHS of the edge.)
#include <RightmostEdgeFinder.h>
Public Member Functions
RightmostEdgeFinder ()
A RightmostEdgeFinder finds the geomgraph::DirectedEdge with the rightmost coordinate.
geomgraph::DirectedEdge * getEdge ()
geom::Coordinate & getCoordinate ()
void findEdge (std::vector< geomgraph::DirectedEdge * > *dirEdgeList)
Note that only Forward DirectedEdges will be checked.
Private Member Functions
void findRightmostEdgeAtNode ()
void findRightmostEdgeAtVertex ()
void checkForRightmostCoordinate (geomgraph::DirectedEdge *de)
int getRightmostSide (geomgraph::DirectedEdge *de, int index)
int getRightmostSideOfSegment (geomgraph::DirectedEdge *de, int i)
Private Attributes
int minIndex
geom::Coordinate minCoord
geomgraph::DirectedEdge * minDe
geomgraph::DirectedEdge * orientedDe
Detailed Description
A RightmostEdgeFinder find the geomgraph::DirectedEdge in a list which has the highest coordinate, and which is oriented L to R at that point. (I.e. the right side is on the RHS of the edge.)
Definition at line 47 of file RightmostEdgeFinder.h.
Constructor & Destructor Documentation
geos::operation::buffer::RightmostEdgeFinder::RightmostEdgeFinder ()
A RightmostEdgeFinder finds the geomgraph::DirectedEdge with the rightmost coordinate.
The geomgraph::DirectedEdge returned is guaranteed to have the R of the world on its RHS.
Definition at line 41 of file RightmostEdgeFinder.cpp.
   :
   minIndex(-1), // FIXME: don't use -1 as a sentinel, or we won't be
                 // able to use an unsigned int here
   minCoord(Coordinate::getNull()),
   minDe(nullptr),
   orientedDe(nullptr)
 {
 }
Member Function Documentation
void geos::operation::buffer::RightmostEdgeFinder::checkForRightmostCoordinate (geomgraph::DirectedEdge * de) private
Definition at line 196 of file RightmostEdgeFinder.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), geos::geomgraph::EdgeEnd::getEdge(), geos::geom::CoordinateSequence::getSize(), geos::geom::Coordinate::isNull(), minCoord, minDe, minIndex, and geos::geom::Coordinate::x.
Referenced by findEdge(), and getRightmostSide().
 {
   const Edge* deEdge=de->getEdge();
   assert(deEdge);
   const CoordinateSequence *coord=deEdge->getCoordinates();
   assert(coord);
   // only check vertices which are the starting point of
   // a non-horizontal segment
   size_t n=coord->getSize()-1;
   for(size_t i=0; i<n; i++)
   {
      // only check vertices which are the start or end point
      // of a non-horizontal segment
      // <FIX> MD 19 Sep 03 - NO!  we can test all vertices,
      // since the rightmost must have a non-horiz segment adjacent to it
     if (minCoord.isNull() ||
       coord->getAt(i).x > minCoord.x )
     {
       minDe = de;
       minIndex = (int)i;
       minCoord = coord->getAt(i);
     }
   }
 }
void geos::operation::buffer::RightmostEdgeFinder::findEdge (std::vector< geomgraph::DirectedEdge * > * dirEdgeList)
Note that only Forward DirectedEdges will be checked.
Definition at line 53 of file RightmostEdgeFinder.cpp.
References checkForRightmostCoordinate(), findRightmostEdgeAtNode(), findRightmostEdgeAtVertex(), geos::geomgraph::EdgeEnd::getCoordinate(), getRightmostSide(), geos::geomgraph::DirectedEdge::getSym(), geos::geomgraph::DirectedEdge::isForward(), minCoord, minDe, minIndex, and orientedDe.
Referenced by geos::operation::buffer::BufferSubgraph::create().
 {
 #ifndef NDEBUG
   size_t checked=0;
 #endif
   /*
    * Check all forward DirectedEdges only.  This is still general,
    * because each edge has a forward DirectedEdge.
    */
   size_t dirEdgeListSize=dirEdgeList->size();
   for(size_t i=0; i<dirEdgeListSize; ++i)
   {
     DirectedEdge *de=(*dirEdgeList)[i];
     assert(de);
     if (!de->isForward()) continue;
     checkForRightmostCoordinate(de);
 #ifndef NDEBUG
     ++checked;
 #endif
   }
   if ( ! minDe ) {
     // I don't know why, but it looks like this can happen
     // (invalid PlanarGraph, I think)
     // See http://trac.osgeo.org/geos/ticket/605#comment:17
     //
     throw util::TopologyException("No forward edges found in buffer subgraph");
   }
 #ifndef NDEBUG
   assert(checked>0);
   assert(minIndex>=0);
   assert(minDe);
 #endif
   /*
    * If the rightmost point is a node, we need to identify which of
    * the incident edges is rightmost.
    */
   assert(minIndex!=0 || minCoord==minDe->getCoordinate());
   // inconsistency in rightmost processing
   if (minIndex==0 ) {
     findRightmostEdgeAtNode();
   } else {
     findRightmostEdgeAtVertex();
   }
   /*
    * now check that the extreme side is the R side.
    * If not, use the sym instead.
    */
   orientedDe=minDe;
   int rightmostSide=getRightmostSide(minDe, minIndex);
   if (rightmostSide==Position::LEFT) {
     orientedDe=minDe->getSym();
   }
 }
void geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtNode () private
Definition at line 116 of file RightmostEdgeFinder.cpp.
References geos::geomgraph::Edge::getCoordinates(), geos::geomgraph::EdgeEnd::getEdge(), geos::geomgraph::Node::getEdges(), geos::geomgraph::EdgeEnd::getNode(), geos::geomgraph::DirectedEdgeStar::getRightmostEdge(), geos::geom::CoordinateSequence::getSize(), geos::geomgraph::DirectedEdge::getSym(), geos::geomgraph::DirectedEdge::isForward(), minDe, and minIndex.
Referenced by findEdge().
 {
   Node *node=minDe->getNode();
   assert(node);
   assert(dynamic_cast<DirectedEdgeStar*>(node->getEdges()));
   DirectedEdgeStar *star=static_cast<DirectedEdgeStar*>(node->getEdges());
   // Warning! NULL could be returned if the star is empty!
   minDe=star->getRightmostEdge();
   assert(minDe);
   // the DirectedEdge returned by the previous call is not
   // necessarily in the forward direction. Use the sym edge if it isn't.
   if (!minDe->isForward())
   {
     minDe=minDe->getSym();
     const Edge* minEdge=minDe->getEdge();
     assert(minEdge);
     const CoordinateSequence* minEdgeCoords =
         minEdge->getCoordinates();
     assert(minEdgeCoords);
     minIndex=(int)(minEdgeCoords->getSize())-1;
     assert(minIndex>=0);
   }
 }
void geos::operation::buffer::RightmostEdgeFinder::findRightmostEdgeAtVertex () private
Definition at line 148 of file RightmostEdgeFinder.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), geos::geomgraph::EdgeEnd::getEdge(), minCoord, minDe, minIndex, and geos::geom::Coordinate::y.
Referenced by findEdge().
 {
   /*
    * The rightmost point is an interior vertex, so it has
    * a segment on either side of it.
    * If these segments are both above or below the rightmost
    * point, we need to determine their relative orientation
    * to decide which is rightmost.
    */
   Edge* minEdge=minDe->getEdge();
   assert(minEdge);
   const CoordinateSequence *pts=minEdge->getCoordinates();
   assert(pts);
   // rightmost point expected to be interior vertex of edge
   assert(minIndex>0);
   assert((size_t)minIndex<pts->getSize());
   const Coordinate& pPrev=pts->getAt(minIndex-1);
   const Coordinate& pNext=pts->getAt(minIndex+1);
   int orientation=CGAlgorithms::computeOrientation(
       minCoord,
       pNext,
       pPrev);
   bool usePrev=false;
   // both segments are below min point
   if ( pPrev.y < minCoord.y && pNext.y < minCoord.y
     && orientation == CGAlgorithms::COUNTERCLOCKWISE)
   {
       usePrev=true;
   }
   else if ( pPrev.y > minCoord.y && pNext.y > minCoord.y
     && orientation == CGAlgorithms::CLOCKWISE)
   {
       usePrev=true;
   }
   // if both segments are on the same side, do nothing - either is safe
   // to select as a rightmost segment
   if (usePrev) {
     minIndex=minIndex-1;
   }
 }
geom::Coordinate & geos::operation::buffer::RightmostEdgeFinder::getCoordinate () inline
Definition at line 97 of file RightmostEdgeFinder.h.
Referenced by geos::operation::buffer::BufferSubgraph::create().
 {
   return minCoord;
 }
geomgraph::DirectedEdge * geos::operation::buffer::RightmostEdgeFinder::getEdge () inline
Definition at line 90 of file RightmostEdgeFinder.h.
Referenced by geos::operation::buffer::BufferSubgraph::computeDepth().
 {
   return orientedDe;
 }
int geos::operation::buffer::RightmostEdgeFinder::getRightmostSide (geomgraph::DirectedEdge * de, int index) private
Definition at line 225 of file RightmostEdgeFinder.cpp.
References checkForRightmostCoordinate(), getRightmostSideOfSegment(), and minCoord.
Referenced by findEdge().
 {
   int side = getRightmostSideOfSegment(de, index);
   if (side<0) side=getRightmostSideOfSegment(de, index-1);
   if (side<0)
   {
     // reaching here can indicate that segment is horizontal
     // Assert::shouldNeverReachHere(
     //  "problem with finding rightmost side of segment");
     minCoord=Coordinate::getNull();
     checkForRightmostCoordinate(de);
   }
   return side;
 }
int geos::operation::buffer::RightmostEdgeFinder::getRightmostSideOfSegment (geomgraph::DirectedEdge * de, int i) private
Definition at line 246 of file RightmostEdgeFinder.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), geos::geomgraph::EdgeEnd::getEdge(), geos::geom::CoordinateSequence::getSize(), and geos::geom::Coordinate::y.
Referenced by getRightmostSide().
 {
   assert(de);
   const Edge *e=de->getEdge();
   assert(e);
   const CoordinateSequence *coord=e->getCoordinates();
   assert(coord);
   if ( i < 0 || i+1 >= (int)coord->getSize() ) return -1;
   // indicates edge is parallel to x-axis
   if (coord->getAt(i).y == coord->getAt(i+1).y) return -1;
   int pos=Position::LEFT;
   if (coord->getAt(i).y < coord->getAt(i+1).y) pos=Position::RIGHT;
   return pos;
 }
Member Data Documentation
geom::Coordinate geos::operation::buffer::RightmostEdgeFinder::minCoord private
Definition at line 53 of file RightmostEdgeFinder.h.
Referenced by checkForRightmostCoordinate(), findEdge(), findRightmostEdgeAtVertex(), and getRightmostSide().
geomgraph::DirectedEdge* geos::operation::buffer::RightmostEdgeFinder::minDe private
Definition at line 55 of file RightmostEdgeFinder.h.
Referenced by checkForRightmostCoordinate(), findEdge(), findRightmostEdgeAtNode(), and findRightmostEdgeAtVertex().
int geos::operation::buffer::RightmostEdgeFinder::minIndex private
Definition at line 51 of file RightmostEdgeFinder.h.
Referenced by checkForRightmostCoordinate(), findEdge(), findRightmostEdgeAtNode(), and findRightmostEdgeAtVertex().
geomgraph::DirectedEdge* geos::operation::buffer::RightmostEdgeFinder::orientedDe private
Definition at line 57 of file RightmostEdgeFinder.h.
Referenced by findEdge().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/buffer/RightmostEdgeFinder.h
/home/vicky/potree/geos/vicky/src/operation/buffer/RightmostEdgeFinder.cpp