GEOS: geos::simplify::DouglasPeuckerSimplifier Class Reference
geos::simplify::DouglasPeuckerSimplifier Class Reference
Simplifies a Geometry using the standard Douglas-Peucker algorithm.
#include <DouglasPeuckerSimplifier.h>
Public Member Functions
DouglasPeuckerSimplifier (const geom::Geometry *geom)
void setDistanceTolerance (double tolerance)
Sets the distance tolerance for the simplification.
std::unique_ptr< geom::Geometry > getResultGeometry ()
Static Public Member Functions
static std::unique_ptr< geom::Geometry > simplify (const geom::Geometry *geom, double tolerance)
Private Attributes
const geom::Geometry * inputGeom
double distanceTolerance
Detailed Description
Simplifies a Geometry using the standard Douglas-Peucker algorithm.
Ensures that any polygonal geometries returned are valid. Simple lines are not guaranteed to remain simple after simplification.
Note that in general D-P does not preserve topology - e.g. polygons can be split, collapse to lines or disappear holes can be created or disappear, and lines can cross. To simplify geometry while preserving topology use TopologyPreservingSimplifier. (However, using D-P is significantly faster).
Definition at line 50 of file DouglasPeuckerSimplifier.h.
Constructor & Destructor Documentation
geos::simplify::DouglasPeuckerSimplifier::DouglasPeuckerSimplifier (const geom::Geometry * geom)
Definition at line 171 of file DouglasPeuckerSimplifier.cpp.
   :
   inputGeom(geom)
 {
 }
Member Function Documentation
Geometry::Ptr geos::simplify::DouglasPeuckerSimplifier::getResultGeometry ()
Definition at line 187 of file DouglasPeuckerSimplifier.cpp.
References distanceTolerance, inputGeom, and geos::geom::util::GeometryTransformer::transform().
Referenced by simplify().
 {
   DPTransformer t(distanceTolerance);
   return t.transform(inputGeom);
 }
void geos::simplify::DouglasPeuckerSimplifier::setDistanceTolerance (double tolerance)
Sets the distance tolerance for the simplification.
All vertices in the simplified geometry will be within this distance of the original geometry. The tolerance value must be non-negative. A tolerance value of zero is effectively a no-op.
Parameters
distanceTolerance the approximation tolerance to use
Definition at line 179 of file DouglasPeuckerSimplifier.cpp.
References distanceTolerance.
Referenced by simplify().
 {
   if (tol < 0.0)
     throw util::IllegalArgumentException("Tolerance must be non-negative");
   distanceTolerance = tol;
 }
Geometry::Ptr geos::simplify::DouglasPeuckerSimplifier::simplify (const geom::Geometry * geom, double tolerance) static
Definition at line 162 of file DouglasPeuckerSimplifier.cpp.
References getResultGeometry(), and setDistanceTolerance().
 {
   DouglasPeuckerSimplifier tss(geom);
   tss.setDistanceTolerance(tolerance);
   return tss.getResultGeometry();
 }
Member Data Documentation
double geos::simplify::DouglasPeuckerSimplifier::distanceTolerance private
Definition at line 79 of file DouglasPeuckerSimplifier.h.
Referenced by getResultGeometry(), and setDistanceTolerance().
const geom::Geometry* geos::simplify::DouglasPeuckerSimplifier::inputGeom private
Definition at line 77 of file DouglasPeuckerSimplifier.h.
Referenced by getResultGeometry().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/simplify/DouglasPeuckerSimplifier.h
/home/vicky/potree/geos/vicky/src/simplify/DouglasPeuckerSimplifier.cpp