GEOS: geos::algorithm::BoundaryNodeRule Class Reference
geos::algorithm::BoundaryNodeRule Class Reference abstract
#include <BoundaryNodeRule.h>
Public Member Functions
virtual ~BoundaryNodeRule ()
virtual bool isInBoundary (int boundaryCount) const =0
Static Public Member Functions
static const BoundaryNodeRule & getBoundaryRuleMod2 ()
The Mod-2 Boundary Node Rule (which is the rule specified in the OGC SFS).
static const BoundaryNodeRule & getBoundaryEndPoint ()
The Endpoint Boundary Node Rule.
static const BoundaryNodeRule & getBoundaryMultivalentEndPoint ()
The MultiValent Endpoint Boundary Node Rule.
static const BoundaryNodeRule & getBoundaryMonovalentEndPoint ()
The Monovalent Endpoint Boundary Node Rule.
static const BoundaryNodeRule & getBoundaryOGCSFS ()
The Boundary Node Rule specified by the OGC Simple Features Specification, which is the same as the Mod-2 rule.
Detailed Description
An interface for rules which determine whether node points which are in boundaries of Lineal geometry components are in the boundary of the parent geometry collection. The SFS specifies a single kind of boundary node rule, the Mod2BoundaryNodeRule rule. However, other kinds of Boundary Node Rules are appropriate in specific situations (for instance, linear network topology usually follows the EndPointBoundaryNodeRule.) Some JTS operations allow the BoundaryNodeRule to be specified, and respect this rule when computing the results of the operation.
Author
Martin Davis
Version
1.7
See also
operation::relate::RelateOp
operation::IsSimpleOp
algorithm::PointLocator
Definition at line 50 of file BoundaryNodeRule.h.
Constructor & Destructor Documentation
virtual geos::algorithm::BoundaryNodeRule::~BoundaryNodeRule () inline virtual
Definition at line 55 of file BoundaryNodeRule.h.
 {}
Member Function Documentation
const BoundaryNodeRule & geos::algorithm::BoundaryNodeRule::getBoundaryEndPoint () static
The Endpoint Boundary Node Rule.
See also
EndPointBoundaryNodeRule
Definition at line 139 of file BoundaryNodeRule.cpp.
Referenced by geos::geom::check_valid().
 {
     return endPointRule;
 }
const BoundaryNodeRule & geos::algorithm::BoundaryNodeRule::getBoundaryMonovalentEndPoint () static
The Monovalent Endpoint Boundary Node Rule.
See also
MonoValentEndPointBoundaryNodeRule
Definition at line 151 of file BoundaryNodeRule.cpp.
 {
     return monoValentRule;
 }
const BoundaryNodeRule & geos::algorithm::BoundaryNodeRule::getBoundaryMultivalentEndPoint () static
The MultiValent Endpoint Boundary Node Rule.
See also
MultiValentEndPointBoundaryNodeRule
Definition at line 145 of file BoundaryNodeRule.cpp.
 {
     return multiValentRule;
 }
const BoundaryNodeRule & geos::algorithm::BoundaryNodeRule::getBoundaryOGCSFS () static
The Boundary Node Rule specified by the OGC Simple Features Specification, which is the same as the Mod-2 rule.
See also
Mod2BoundaryNodeRule
Definition at line 157 of file BoundaryNodeRule.cpp.
Referenced by geos::operation::GeometryGraphOperation::GeometryGraphOperation().
 {
     return getBoundaryRuleMod2();
 }
const BoundaryNodeRule & geos::algorithm::BoundaryNodeRule::getBoundaryRuleMod2 () static
The Mod-2 Boundary Node Rule (which is the rule specified in the OGC SFS).
See also
Mod2BoundaryNodeRule
Definition at line 133 of file BoundaryNodeRule.cpp.
 {
     return mod2Rule;
 }
virtual bool geos::algorithm::BoundaryNodeRule::isInBoundary (int boundaryCount) const pure virtual
Tests whether a point that lies in boundaryCount geometry component boundaries is considered to form part of the boundary of the parent geometry.
Parameters
boundaryCount the number of component boundaries that this point occurs in
Returns
true if points in this number of boundaries lie in the parent boundary
Referenced by geos::geomgraph::GeometryGraph::determineBoundary().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/BoundaryNodeRule.h
/home/vicky/potree/geos/vicky/src/algorithm/BoundaryNodeRule.cpp