GEOS: geos::operation::relate::EdgeEndBuilder Class Reference
geos::operation::relate::EdgeEndBuilder Class Reference
Computes the geomgraph::EdgeEnd objects which arise from a noded geomgraph::Edge.
#include <EdgeEndBuilder.h>
Public Member Functions
EdgeEndBuilder ()
std::vector< geomgraph::EdgeEnd * > * computeEdgeEnds (std::vector< geomgraph::Edge * > *edges)
void computeEdgeEnds (geomgraph::Edge *edge, std::vector< geomgraph::EdgeEnd * > *l)
Protected Member Functions
void createEdgeEndForPrev (geomgraph::Edge *edge, std::vector< geomgraph::EdgeEnd * > *l, geomgraph::EdgeIntersection *eiCurr, geomgraph::EdgeIntersection *eiPrev)
void createEdgeEndForNext (geomgraph::Edge *edge, std::vector< geomgraph::EdgeEnd * > *l, geomgraph::EdgeIntersection *eiCurr, geomgraph::EdgeIntersection *eiNext)
Detailed Description
Computes the geomgraph::EdgeEnd objects which arise from a noded geomgraph::Edge.
Definition at line 48 of file EdgeEndBuilder.h.
Constructor & Destructor Documentation
geos::operation::relate::EdgeEndBuilder::EdgeEndBuilder () inline
Definition at line 50 of file EdgeEndBuilder.h.
 {}
Member Function Documentation
vector< EdgeEnd * > * geos::operation::relate::EdgeEndBuilder::computeEdgeEnds (std::vector< geomgraph::Edge * > * edges)
Definition at line 38 of file EdgeEndBuilder.cpp.
Referenced by geos::operation::relate::RelateNodeGraph::build(), and geos::operation::relate::RelateComputer::computeIM().
 {
   vector<EdgeEnd*> *l=new vector<EdgeEnd*>();
   for(vector<Edge*>::iterator i=edges->begin();i<edges->end();i++) {
     Edge *e=*i;
     computeEdgeEnds(e,l);
   }
   return l;
 }
void geos::operation::relate::EdgeEndBuilder::computeEdgeEnds (geomgraph::Edge * edge, std::vector< geomgraph::EdgeEnd * > * l)
Creates stub edges for all the intersections in this Edge (if any) and inserts them into the graph.
Definition at line 53 of file EdgeEndBuilder.cpp.
References geos::geomgraph::EdgeIntersectionList::addEndpoints(), geos::geomgraph::EdgeIntersectionList::begin(), geos::geomgraph::EdgeIntersectionList::end(), and geos::geomgraph::Edge::getEdgeIntersectionList().
 {
   EdgeIntersectionList &eiList=edge->getEdgeIntersectionList();
   //Debug.print(eiList);
   // ensure that the list has entries for the first and last point of the edge
   eiList.addEndpoints();
   EdgeIntersectionList::iterator it=eiList.begin();
   // no intersections, so there is nothing to do
   if (it==eiList.end()) return;
   EdgeIntersection *eiPrev=nullptr;
   EdgeIntersection *eiCurr=nullptr;
   EdgeIntersection *eiNext=*it;
   it++;
   do {
     eiPrev=eiCurr;
     eiCurr=eiNext;
     eiNext=nullptr;
     if (it!=eiList.end()) {
       eiNext=*it;
       it++;
     }
     if (eiCurr!=nullptr) {
       createEdgeEndForPrev(edge,l,eiCurr,eiPrev);
       createEdgeEndForNext(edge,l,eiCurr,eiNext);
     }
   } while (eiCurr!=nullptr);
 }
void geos::operation::relate::EdgeEndBuilder::createEdgeEndForNext (geomgraph::Edge * edge, std::vector< geomgraph::EdgeEnd * > * l, geomgraph::EdgeIntersection * eiCurr, geomgraph::EdgeIntersection * eiNext) protected
Create a StubEdge for the edge after the intersection eiCurr. The next intersection is provided in case it is the endpoint for the stub edge. Otherwise, the next point from the parent edge will be the endpoint.
eiCurr will always be an EdgeIntersection, but eiNext may be null.
Definition at line 123 of file EdgeEndBuilder.cpp.
References geos::geomgraph::EdgeIntersection::coord, geos::geomgraph::Edge::getCoordinate(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Edge::getNumPoints(), and geos::geomgraph::EdgeIntersection::segmentIndex.
 {
   int iNext=eiCurr->segmentIndex + 1;
   // if there is no next edge there is nothing to do
   if (iNext>=edge->getNumPoints() && eiNext==nullptr) return;
   Coordinate pNext(edge->getCoordinate(iNext));
   // if the next intersection is in the same segment as the current, use it as the endpoint
   if (eiNext!=nullptr && eiNext->segmentIndex==eiCurr->segmentIndex)
     pNext=eiNext->coord;
   EdgeEnd *e = new EdgeEnd(edge, eiCurr->coord, pNext, edge->getLabel());
   //Debug.println(e);
   l->push_back(e);
 }
void geos::operation::relate::EdgeEndBuilder::createEdgeEndForPrev (geomgraph::Edge * edge, std::vector< geomgraph::EdgeEnd * > * l, geomgraph::EdgeIntersection * eiCurr, geomgraph::EdgeIntersection * eiPrev) protected
Create a EdgeStub for the edge before the intersection eiCurr. The previous intersection is provided in case it is the endpoint for the stub edge. Otherwise, the previous point from the parent edge will be the endpoint.
eiCurr will always be an EdgeIntersection, but eiPrev may be null.
Definition at line 93 of file EdgeEndBuilder.cpp.
References geos::geomgraph::EdgeIntersection::coord, geos::geomgraph::EdgeIntersection::dist, geos::geomgraph::Label::flip(), geos::geomgraph::Edge::getCoordinate(), geos::geomgraph::GraphComponent::getLabel(), and geos::geomgraph::EdgeIntersection::segmentIndex.
 {
   int iPrev=eiCurr->segmentIndex;
   if (eiCurr->dist==0.0) {
     // if at the start of the edge there is no previous edge
     if (iPrev==0) return;
     iPrev--;
   }
   Coordinate pPrev(edge->getCoordinate(iPrev));
   // if prev intersection is past the previous vertex, use it instead
   if (eiPrev!=nullptr && eiPrev->segmentIndex>=iPrev)
     pPrev=eiPrev->coord;
   Label label( edge->getLabel() );
   // since edgeStub is oriented opposite to it's parent edge, have to flip sides for edge label
   label.flip();
   EdgeEnd *e=new EdgeEnd(edge,eiCurr->coord,pPrev,label);
   //e.print(System.out);  System.out.println();
   l->push_back(e);
 }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/relate/EdgeEndBuilder.h
/home/vicky/potree/geos/vicky/src/operation/relate/EdgeEndBuilder.cpp