GEOS: geos::algorithm::NotRepresentableException Class Reference
geos::algorithm::NotRepresentableException Class Reference
Indicates that a HCoordinate has been computed which is not representable on the Cartesian plane.
#include <geos/geosAlgorithm.h>
Public Member Functions
NotRepresentableException ()
NotRepresentableException (std::string msg)
~NotRepresentableException () override throw ()
const char * what () const override throw ()
Detailed Description
Indicates that a HCoordinate has been computed which is not representable on the Cartesian plane.
Version
1.4
See also
HCoordinate
Definition at line 35 of file NotRepresentableException.h.
Constructor & Destructor Documentation
geos::algorithm::NotRepresentableException::NotRepresentableException ()
Definition at line 22 of file NotRepresentableException.cpp.
   :
   GEOSException(
     "NotRepresentableException",
     "Projective point not representable on the Cartesian plane.")
 {
 }
geos::algorithm::NotRepresentableException::NotRepresentableException (std::string msg)
Definition at line 31 of file NotRepresentableException.cpp.
   :
   GEOSException(
     "NotRepresentableException", msg)
 {
 }
geos::algorithm::NotRepresentableException::~NotRepresentableException () throw () inline override
Definition at line 39 of file NotRepresentableException.h.
 {}
Member Function Documentation
const char* geos::util::GEOSException::what () const throw () inline override inherited
Definition at line 63 of file GEOSException.h.
Referenced by geos::operation::overlay::ElevationMatrix::add(), geos::geom::BinaryOp(), geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::snap::SnapIfNeededOverlayOp::getResultGeometry(), geos::operation::polygonize::EdgeRing::getRingInternal(), and geos::precision::EnhancedPrecisionOp::intersection().
   {
     return _msg.c_str();
   }
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/NotRepresentableException.h
/home/vicky/potree/geos/vicky/src/algorithm/NotRepresentableException.cpp