GEOS: geos::index::strtree::ItemBoundable Class Reference
geos::index::strtree::ItemBoundable Class Reference
Boundable wrapper for a non-Boundable spatial object. Used internally by AbstractSTRtree.
#include <ItemBoundable.h>
Public Member Functions
ItemBoundable (const void *newBounds, void *newItem)
~ItemBoundable () override=default
const void * getBounds () const override
void * getItem () const
Private Attributes
const void * bounds
void * item
Detailed Description
Boundable wrapper for a non-Boundable spatial object. Used internally by AbstractSTRtree.
Todo:
TODO: It's unclear who takes ownership of passed newBounds and newItem objects.
Definition at line 32 of file ItemBoundable.h.
Constructor & Destructor Documentation
geos::index::strtree::ItemBoundable::ItemBoundable (const void * newBounds, void * newItem)
Definition at line 22 of file ItemBoundable.cpp.
                                                                  :
     bounds(newBounds), item(newItem)
 {
 }
geos::index::strtree::ItemBoundable::~ItemBoundable () override default
Member Function Documentation
const void * geos::index::strtree::ItemBoundable::getBounds () const override virtual
Returns a representation of space that encloses this Boundable, preferably not much bigger than this Boundable's boundary yet fast to test for intersection with the bounds of other Boundables.
The class of object returned depends on the subclass of AbstractSTRtree.
Returns
an Envelope (for STRtrees), an Interval (for SIRtrees), or other object (for other subclasses of AbstractSTRtree)
See also
AbstractSTRtree::IntersectsOp
Implements geos::index::strtree::Boundable.
Definition at line 28 of file ItemBoundable.cpp.
References bounds.
{
   return bounds;
 }
void * geos::index::strtree::ItemBoundable::getItem () const
Definition at line 32 of file ItemBoundable.cpp.
References item.
Referenced by geos::precision::MinimumClearance::compute(), geos::index::strtree::GeometryItemDistance::distance(), GEOSSTRtree_nearest_generic_r(), and geos::operation::distance::IndexedFacetDistance::getDistance().
{
   return item;
 }
Member Data Documentation
const void* geos::index::strtree::ItemBoundable::bounds private
Definition at line 44 of file ItemBoundable.h.
Referenced by getBounds().
void* geos::index::strtree::ItemBoundable::item private
Definition at line 45 of file ItemBoundable.h.
Referenced by getItem().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/strtree/ItemBoundable.h
/home/vicky/potree/geos/vicky/src/index/strtree/ItemBoundable.cpp