GEOS: geos::geomgraph::PlanarGraph Class Reference
geos::geomgraph::PlanarGraph Class Reference
Represents a directed graph which is embeddable in a planar surface.
#include <PlanarGraph.h>
Public Member Functions
PlanarGraph (const NodeFactory &nodeFact)
PlanarGraph ()
virtual ~PlanarGraph ()
virtual std::vector< Edge * >::iterator getEdgeIterator ()
virtual std::vector< EdgeEnd * > * getEdgeEnds ()
virtual bool isBoundaryNode (int geomIndex, const geom::Coordinate &coord)
virtual void add (EdgeEnd *e)
virtual NodeMap::iterator getNodeIterator ()
virtual void getNodes (std::vector< Node * > &)
virtual Node * addNode (Node *node)
virtual Node * addNode (const geom::Coordinate &coord)
virtual Node * find (geom::Coordinate &coord)
virtual void addEdges (const std::vector< Edge * > &edgesToAdd)
Add a set of edges to the graph. For each edge two DirectedEdges will be created. DirectedEdges are NOT linked by this method.
virtual void linkResultDirectedEdges ()
virtual void linkAllDirectedEdges ()
virtual EdgeEnd * findEdgeEnd (Edge *e)
Returns the EdgeEnd which has edge e as its base edge (MD 18 Feb 2002 - this should return a pair of edges)
virtual Edge * findEdge (const geom::Coordinate &p0, const geom::Coordinate &p1)
Returns the edge whose first two coordinates are p0 and p1.
virtual Edge * findEdgeInSameDirection (const geom::Coordinate &p0, const geom::Coordinate &p1)
Returns the edge which starts at p0 and whose first segment is parallel to p1.
virtual std::string printEdges ()
virtual NodeMap * getNodeMap ()
Static Public Member Functions
template<typename It >
static void linkResultDirectedEdges (It first, It last)
For nodes in the collection (first..last), link the DirectedEdges at the node that are in the result.
Protected Member Functions
virtual void insertEdge (Edge *e)
Protected Attributes
std::vector< Edge * > * edges
NodeMap * nodes
std::vector< EdgeEnd * > * edgeEndList
Private Member Functions
bool matchInSameDirection (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &ep0, const geom::Coordinate &ep1)
The coordinate pairs match if they define line segments lying in the same direction.
Detailed Description
Represents a directed graph which is embeddable in a planar surface.
The computation of the IntersectionMatrix relies on the use of a structure called a "topology graph". The topology graph contains nodes and edges corresponding to the nodes and line segments of a Geometry. Each node and edge in the graph is labeled with its topological location relative to the source geometry.
Note that there is no requirement that points of self-intersection be a vertex. Thus to obtain a correct topology graph, Geometry objects must be self-noded before constructing their graphs.
Two fundamental operations are supported by topology graphs:
Computing the intersections between all the edges and nodes of a single graph
Computing the intersections between the edges and nodes of two different graphs
Definition at line 75 of file PlanarGraph.h.
Constructor & Destructor Documentation
geos::geomgraph::PlanarGraph::PlanarGraph (const NodeFactory & nodeFact)
Definition at line 54 of file PlanarGraph.cpp.
   :
   edges(new vector<Edge*>()),
   nodes(new NodeMap(nodeFact)),
   edgeEndList(new vector<EdgeEnd*>())
 {
 }
geos::geomgraph::PlanarGraph::PlanarGraph ()
Definition at line 63 of file PlanarGraph.cpp.
   :
   edges(new vector<Edge*>()),
   nodes(new NodeMap(NodeFactory::instance())),
   edgeEndList(new vector<EdgeEnd*>())
 {
 }
geos::geomgraph::PlanarGraph::~PlanarGraph () virtual
Definition at line 72 of file PlanarGraph.cpp.
References edgeEndList, edges, and nodes.
 {
 #if GEOS_DEBUG
   std::cerr << "~PlanarGraph" << std::endl;
 #endif
   delete nodes;
 #if 1 // FIXME: PlanarGraph should *not* own edges!
   for(size_t i=0, n=edges->size(); i<n; i++) {
     delete (*edges)[i];
   }
 #endif
   delete edges;
   for(size_t i=0, n=edgeEndList->size(); i<n; i++) {
     delete (*edgeEndList)[i];
   }
   delete edgeEndList;
 }
Member Function Documentation
void geos::geomgraph::PlanarGraph::add (EdgeEnd * e) virtual
Definition at line 134 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::add(), edgeEndList, and nodes.
Referenced by addEdges().
 {
   // It is critical to add the edge to the edgeEndList first,
   // then it is safe to follow with any potentially throwing operations.
   assert(edgeEndList);
   edgeEndList->push_back(e);
   assert(e);
   assert(nodes);
   nodes->add(e);
 }
void geos::geomgraph::PlanarGraph::addEdges (const std::vector< Edge * > & edgesToAdd) virtual
Add a set of edges to the graph. For each edge two DirectedEdges will be created. DirectedEdges are NOT linked by this method.
Definition at line 202 of file PlanarGraph.cpp.
References add(), and edges.
Referenced by geos::operation::buffer::BufferBuilder::buffer(), geos::operation::overlay::OverlayOp::computeOverlay(), and geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected().
 {
   // create all the nodes for the edges
   for (vector<Edge*>::const_iterator it=edgesToAdd.begin(),
     endIt=edgesToAdd.end(); it!=endIt; ++it)
   {
     Edge *e=*it;
     assert(e);
     edges->push_back(e);
     // PlanarGraph destructor will delete all DirectedEdges
     // in edgeEndList, which is where these are added
     // by the ::add(EdgeEnd) call
     std::unique_ptr<DirectedEdge> de1(new DirectedEdge(e, true));
     std::unique_ptr<DirectedEdge> de2(new DirectedEdge(e, false));
     de1->setSym(de2.get());
     de2->setSym(de1.get());
     // First, ::add takes the ownership, then follows with operations that may throw.
     add(de1.release());
     add(de2.release());
   }
 }
Node * geos::geomgraph::PlanarGraph::addNode (Node * node) virtual
Definition at line 171 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::addNode(), and nodes.
Referenced by geos::operation::overlay::OverlayOp::copyPoints().
 {
   assert(nodes);
 #if GEOS_DEBUG > 1
   cerr << "PlanarGraph::addNode(Node * " << *node
     << ")" << endl;
 #endif
   return nodes->addNode(node);
 }
Node * geos::geomgraph::PlanarGraph::addNode (const geom::Coordinate & coord) virtual
Definition at line 183 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::addNode(), and nodes.
 {
 #if GEOS_DEBUG > 1
   cerr << "PlanarGraph::addNode(Coordinate& "
     << coord << ")" << endl;
 #endif
   return nodes->addNode(coord);
 }
Node * geos::geomgraph::PlanarGraph::find (geom::Coordinate & coord) virtual
Returns
the node if found; null otherwise
Definition at line 194 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::find(), and nodes.
 {
   assert(nodes);
   return nodes->find(coord);
 }
Edge * geos::geomgraph::PlanarGraph::findEdge (const geom::Coordinate & p0, const geom::Coordinate & p1) virtual
Returns the edge whose first two coordinates are p0 and p1.
Returns
the edge, if found null if the edge was not found
Definition at line 298 of file PlanarGraph.cpp.
References edges, geos::geom::CoordinateSequence::getAt(), and geos::geomgraph::Edge::getCoordinates().
 {
   for (size_t i=0, n=edges->size(); i<n; ++i)
   {
     Edge *e=(*edges)[i];
     assert(e);
     const CoordinateSequence* eCoord=e->getCoordinates();
     assert(eCoord);
     if (p0==eCoord->getAt(0) && p1==eCoord->getAt(1))
       return e;
   }
   return nullptr;
 }
EdgeEnd * geos::geomgraph::PlanarGraph::findEdgeEnd (Edge * e) virtual
Returns the EdgeEnd which has edge e as its base edge (MD 18 Feb 2002 - this should return a pair of edges)
Returns
the edge, if found null if the edge was not found
Definition at line 278 of file PlanarGraph.cpp.
References geos::geomgraph::EdgeEnd::getEdge(), and getEdgeEnds().
Referenced by geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
 {
   vector<EdgeEnd*>* eev=getEdgeEnds();
   assert(eev);
   for (vector<EdgeEnd*>::iterator i=eev->begin(), iEnd=eev->end();
       i != iEnd;
       ++i)
   {
     EdgeEnd *ee=*i;
     assert(ee);
     // should test using values rather then pointers ?
     if (ee->getEdge()==e) return ee;
   }
   return nullptr;
 }
Edge * geos::geomgraph::PlanarGraph::findEdgeInSameDirection (const geom::Coordinate & p0, const geom::Coordinate & p1) virtual
Returns the edge which starts at p0 and whose first segment is parallel to p1.
Returns
the edge, if found null if the edge was not found
Definition at line 316 of file PlanarGraph.cpp.
References edges, geos::geom::CoordinateSequence::getAt(), geos::geomgraph::Edge::getCoordinates(), matchInSameDirection(), and geos::geom::CoordinateSequence::size().
Referenced by geos::operation::valid::ConnectedInteriorTester::visitInteriorRing().
 {
   for(size_t i=0, n=edges->size(); i<n; i++)
   {
     Edge *e=(*edges)[i];
     assert(e);
     const CoordinateSequence* eCoord=e->getCoordinates();
     assert(eCoord);
     size_t nCoords=eCoord->size();
     assert(nCoords>1);
     if (matchInSameDirection(p0, p1,
         eCoord->getAt(0),
         eCoord->getAt(1)))
     {
       return e;
     }
     if (matchInSameDirection(p0, p1,
         eCoord->getAt(nCoords-1),
         eCoord->getAt(nCoords-2)))
     {
       return e;
     }
   }
   return nullptr;
 }
vector< EdgeEnd * > * geos::geomgraph::PlanarGraph::getEdgeEnds () virtual
Definition at line 102 of file PlanarGraph.cpp.
References edgeEndList.
Referenced by geos::operation::overlay::PolygonBuilder::add(), geos::operation::overlay::OverlayOp::cancelDuplicateResultEdges(), geos::operation::overlay::LineBuilder::collectLines(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), findEdgeEnd(), geos::operation::overlay::OverlayOp::findResultAreaEdges(), geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected(), and geos::operation::valid::ConnectedInteriorTester::setInteriorEdgesInResult().
 {
   return edgeEndList;
 }
vector< Edge * >::iterator geos::geomgraph::PlanarGraph::getEdgeIterator () virtual
Definition at line 94 of file PlanarGraph.cpp.
References edges.
 {
   assert(edges);
   return edges->begin();
 }
NodeMap::iterator geos::geomgraph::PlanarGraph::getNodeIterator () virtual
Definition at line 148 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::begin(), and nodes.
 {
   assert(nodes);
   return nodes->begin();
 }
NodeMap * geos::geomgraph::PlanarGraph::getNodeMap () virtual
Definition at line 377 of file PlanarGraph.cpp.
References nodes.
Referenced by geos::operation::overlay::PolygonBuilder::add(), geos::operation::overlay::OverlayOp::computeLabelling(), geos::operation::relate::RelateNodeGraph::copyNodesAndLabels(), geos::operation::overlay::LineBuilder::findCoveredLineEdges(), geos::operation::overlay::OverlayOp::labelIncompleteNodes(), geos::operation::overlay::OverlayOp::mergeSymLabels(), and geos::operation::overlay::OverlayOp::updateNodeLabelling().
 {
   return nodes;
 }
void geos::geomgraph::PlanarGraph::getNodes (std::vector< Node * > & values) virtual
Definition at line 156 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::nodeMap, and nodes.
Referenced by geos::operation::buffer::BufferBuilder::createSubgraphs().
 {
   assert(nodes);
   NodeMap::iterator it=nodes->nodeMap.begin();
   while(it!=nodes->nodeMap.end()) {
     assert(it->second);
     values.push_back(it->second);
     it++;
   }
 }
void geos::geomgraph::PlanarGraph::insertEdge (Edge * e) protected virtual
Definition at line 125 of file PlanarGraph.cpp.
References edges.
 {
   assert(e);
   assert(edges);
   edges->push_back(e);
 }
bool geos::geomgraph::PlanarGraph::isBoundaryNode (int geomIndex, const geom::Coordinate & coord) virtual
Definition at line 109 of file PlanarGraph.cpp.
References geos::geomgraph::NodeMap::find(), geos::geomgraph::GraphComponent::getLabel(), geos::geomgraph::Label::getLocation(), geos::geomgraph::Label::isNull(), and nodes.
 {
   assert(nodes);
   Node *node=nodes->find(coord);
   if (node==nullptr) return false;
   const Label& label = node->getLabel();
   if (! label.isNull() && label.getLocation(geomIndex)==Location::BOUNDARY)
       return true;
   return false;
 }
void geos::geomgraph::PlanarGraph::linkAllDirectedEdges () virtual
Definition at line 254 of file PlanarGraph.cpp.
References geos::geomgraph::Node::getEdges(), geos::geomgraph::DirectedEdgeStar::linkAllDirectedEdges(), geos::geomgraph::NodeMap::nodeMap, and nodes.
 {
 #if GEOS_DEBUG
   cerr<<"PlanarGraph::linkAllDirectedEdges called"<<endl;
 #endif
   NodeMap::iterator nodeit=nodes->nodeMap.begin();
   for (;nodeit!=nodes->nodeMap.end();nodeit++)
   {
     Node *node=nodeit->second;
     assert(node);
     EdgeEndStar *ees=node->getEdges();
     assert(ees);
     // Unespected non-DirectedEdgeStar in node
     assert(dynamic_cast<DirectedEdgeStar *>(ees));
     DirectedEdgeStar *des=static_cast<DirectedEdgeStar *>(ees);
     des->linkAllDirectedEdges();
   }
 }
template<typename It > static void geos::geomgraph::PlanarGraph::linkResultDirectedEdges (It first, It last) inline static
For nodes in the collection (first..last), link the DirectedEdges at the node that are in the result.
This allows clients to link only a subset of nodes in the graph, for efficiency (because they know that only a subset is of interest).
Definition at line 87 of file PlanarGraph.h.
References geos::geomgraph::Node::getEdges(), and geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges().
Referenced by geos::operation::valid::ConnectedInteriorTester::isInteriorsConnected().
   {
     for ( ; first!=last; ++first )
     {
       Node *node=*first;
       assert(node);
       EdgeEndStar* ees = node->getEdges();
       assert(ees);
       DirectedEdgeStar* des = dynamic_cast<DirectedEdgeStar*>(ees);
       assert(des);
       // this might throw an exception
       des->linkResultDirectedEdges();
     }
   }
void geos::geomgraph::PlanarGraph::linkResultDirectedEdges () virtual
Definition at line 228 of file PlanarGraph.cpp.
References geos::geomgraph::Node::getEdges(), geos::geomgraph::DirectedEdgeStar::linkResultDirectedEdges(), geos::geomgraph::NodeMap::nodeMap, and nodes.
 {
 #if GEOS_DEBUG
   cerr<<"PlanarGraph::linkResultDirectedEdges called"<<endl;
 #endif
   NodeMap::iterator nodeit=nodes->nodeMap.begin();
   for (;nodeit!=nodes->nodeMap.end();nodeit++) {
     Node *node=nodeit->second;
     assert(node);
     EdgeEndStar* ees=node->getEdges();
     assert(ees);
     assert(dynamic_cast<DirectedEdgeStar*>(ees));
     DirectedEdgeStar* des = static_cast<DirectedEdgeStar*>(ees);
     // this might throw an exception
     des->linkResultDirectedEdges();
   }
 }
bool geos::geomgraph::PlanarGraph::matchInSameDirection (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & ep0, const geom::Coordinate & ep1) private
The coordinate pairs match if they define line segments lying in the same direction.
E.g. the segments are parallel and in the same quadrant (as opposed to parallel and opposite!).
Definition at line 350 of file PlanarGraph.cpp.
References geos::algorithm::CGAlgorithms::COLLINEAR, and geos::algorithm::CGAlgorithms::computeOrientation().
Referenced by findEdgeInSameDirection().
 {
   if (!(p0==ep0))
     return false;
   if (CGAlgorithms::computeOrientation(p0,p1,ep1)==CGAlgorithms::COLLINEAR
     && Quadrant::quadrant(p0,p1)==Quadrant::quadrant(ep0,ep1))
       return true;
   return false;
 }
string geos::geomgraph::PlanarGraph::printEdges () virtual
Definition at line 363 of file PlanarGraph.cpp.
References edges, geos::geomgraph::Edge::eiList, geos::geomgraph::EdgeIntersectionList::print(), and geos::geomgraph::Edge::print().
 {
     std::ostringstream oss;
     oss << "Edges: ";
   for(size_t i=0, n=edges->size(); i<n; ++i)
   {
         Edge *e=(*edges)[i];
     oss << "edge " << i << ":\n" << e->print() << e->eiList.print();
   }
     return oss.str();
 }
Member Data Documentation
std::vector<EdgeEnd*>* geos::geomgraph::PlanarGraph::edgeEndList protected
Definition at line 180 of file PlanarGraph.h.
Referenced by add(), getEdgeEnds(), and ~PlanarGraph().
std::vector<Edge*>* geos::geomgraph::PlanarGraph::edges protected
Definition at line 176 of file PlanarGraph.h.
Referenced by addEdges(), geos::geomgraph::GeometryGraph::computeEdgeIntersections(), findEdge(), findEdgeInSameDirection(), getEdgeIterator(), insertEdge(), printEdges(), and ~PlanarGraph().
NodeMap* geos::geomgraph::PlanarGraph::nodes protected
Definition at line 178 of file PlanarGraph.h.
Referenced by add(), addNode(), find(), geos::geomgraph::GeometryGraph::getBoundaryNodes(), getNodeIterator(), getNodeMap(), getNodes(), isBoundaryNode(), linkAllDirectedEdges(), linkResultDirectedEdges(), and ~PlanarGraph().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geomgraph/PlanarGraph.h
/home/vicky/potree/geos/vicky/src/geomgraph/PlanarGraph.cpp