GEOS: geos::operation::overlay::snap::SnapIfNeededOverlayOp Class Reference
geos::operation::overlay::snap::SnapIfNeededOverlayOp Class Reference
Performs an overlay operation using snapping and enhanced precision to improve the robustness of the result.
#include <SnapIfNeededOverlayOp.h>
Public Types
typedef std::unique_ptr< geom::Geometry > GeomPtr
Public Member Functions
SnapIfNeededOverlayOp (const geom::Geometry &g1, const geom::Geometry &g2)
GeomPtr getResultGeometry (OverlayOp::OpCode opCode)
Static Public Member Functions
static std::unique_ptr< geom::Geometry > overlayOp (const geom::Geometry &g0, const geom::Geometry &g1, OverlayOp::OpCode opCode)
static std::unique_ptr< geom::Geometry > intersection (const geom::Geometry &g0, const geom::Geometry &g1)
static std::unique_ptr< geom::Geometry > Union (const geom::Geometry &g0, const geom::Geometry &g1)
static std::unique_ptr< geom::Geometry > difference (const geom::Geometry &g0, const geom::Geometry &g1)
static std::unique_ptr< geom::Geometry > symDifference (const geom::Geometry &g0, const geom::Geometry &g1)
Private Member Functions
SnapIfNeededOverlayOp (const SnapIfNeededOverlayOp &other)=delete
SnapIfNeededOverlayOp & operator= (const SnapIfNeededOverlayOp &rhs)=delete
Private Attributes
const geom::Geometry & geom0
const geom::Geometry & geom1
Detailed Description
Performs an overlay operation using snapping and enhanced precision to improve the robustness of the result.
This class only uses snapping if an error is detected when running the standard JTS overlay code. Errors detected include thrown exceptions (in particular, TopologyException) and invalid overlay computations.
Definition at line 49 of file SnapIfNeededOverlayOp.h.
Member Typedef Documentation
typedef std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapIfNeededOverlayOp::GeomPtr
Definition at line 94 of file SnapIfNeededOverlayOp.h.
Constructor & Destructor Documentation
geos::operation::overlay::snap::SnapIfNeededOverlayOp::SnapIfNeededOverlayOp (const geom::Geometry & g1, const geom::Geometry & g2) inline
Definition at line 86 of file SnapIfNeededOverlayOp.h.
     :
     geom0(g1),
     geom1(g2)
   {
   }
geos::operation::overlay::snap::SnapIfNeededOverlayOp::SnapIfNeededOverlayOp (const SnapIfNeededOverlayOp & other) private delete
Member Function Documentation
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapIfNeededOverlayOp::difference (const geom::Geometry & g0, const geom::Geometry & g1) inline static
Definition at line 75 of file SnapIfNeededOverlayOp.h.
   {
     return overlayOp(g0, g1, OverlayOp::opDIFFERENCE);
   }
unique_ptr< Geometry > geos::operation::overlay::snap::SnapIfNeededOverlayOp::getResultGeometry (OverlayOp::OpCode opCode)
Definition at line 43 of file SnapIfNeededOverlayOp.cpp.
References geos::ignore_unused_variable_warning(), and geos::util::GEOSException::what().
Referenced by overlayOp().
 {
   using geos::util::TopologyException;
   unique_ptr<Geometry> result;
   TopologyException origEx;
   // Try with original input
   try {
     result.reset( OverlayOp::overlayOp(&geom0, &geom1, opCode) );
     return result;
   }
   catch (const TopologyException& ex) {
     origEx = ex; // save original exception
 #if GEOS_DEBUG
     std::cerr << "Overlay op threw " << ex.what() << ". Will try snapping now" << std::endl;
 #endif
   }
   // Try snapping
   try {
     result = SnapOverlayOp::overlayOp(geom0, geom1, opCode);
     return result;
   }
   catch (const TopologyException& ex) {
     ::geos::ignore_unused_variable_warning(ex);
 #if GEOS_DEBUG
     std::cerr << "Overlay op on snapped geoms threw " << ex.what() << ". Will try snapping now" << std::endl;
 #endif
     throw origEx;
   }
 }
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapIfNeededOverlayOp::intersection (const geom::Geometry & g0, const geom::Geometry & g1) inline static
Definition at line 63 of file SnapIfNeededOverlayOp.h.
   {
     return overlayOp(g0, g1, OverlayOp::opINTERSECTION);
   }
SnapIfNeededOverlayOp& geos::operation::overlay::snap::SnapIfNeededOverlayOp::operator= (const SnapIfNeededOverlayOp & rhs) private delete
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapIfNeededOverlayOp::overlayOp (const geom::Geometry & g0, const geom::Geometry & g1, OverlayOp::OpCode opCode) inline static
Definition at line 55 of file SnapIfNeededOverlayOp.h.
References getResultGeometry().
   {
     SnapIfNeededOverlayOp op(g0, g1);
     return op.getResultGeometry(opCode);
   }
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapIfNeededOverlayOp::symDifference (const geom::Geometry & g0, const geom::Geometry & g1) inline static
Definition at line 81 of file SnapIfNeededOverlayOp.h.
   {
     return overlayOp(g0, g1, OverlayOp::opSYMDIFFERENCE);
   }
static std::unique_ptr<geom::Geometry> geos::operation::overlay::snap::SnapIfNeededOverlayOp::Union (const geom::Geometry & g0, const geom::Geometry & g1) inline static
Definition at line 69 of file SnapIfNeededOverlayOp.h.
   {
     return overlayOp(g0, g1, OverlayOp::opUNION);
   }
Member Data Documentation
const geom::Geometry& geos::operation::overlay::snap::SnapIfNeededOverlayOp::geom0 private
Definition at line 100 of file SnapIfNeededOverlayOp.h.
const geom::Geometry& geos::operation::overlay::snap::SnapIfNeededOverlayOp::geom1 private
Definition at line 101 of file SnapIfNeededOverlayOp.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/overlay/snap/SnapIfNeededOverlayOp.h
/home/vicky/potree/geos/vicky/src/operation/overlay/snap/SnapIfNeededOverlayOp.cpp