GEOS: geos::triangulate::IncrementalDelaunayTriangulator Class Reference
geos::triangulate::IncrementalDelaunayTriangulator Class Reference
#include <IncrementalDelaunayTriangulator.h>
Public Types
typedef std::list< quadedge::Vertex > VertexList
Public Member Functions
IncrementalDelaunayTriangulator (quadedge::QuadEdgeSubdivision *subdiv)
void insertSites (const VertexList &vertices)
quadedge::QuadEdge & insertSite (const quadedge::Vertex &v)
Private Attributes
quadedge::QuadEdgeSubdivision * subdiv
bool isUsingTolerance
Detailed Description
Computes a Delauanay Triangulation of a set of Vertexes, using an incrementatal insertion algorithm.
Author
JTS: Martin Davis
Benjamin Campbell
Definition at line 42 of file IncrementalDelaunayTriangulator.h.
Member Typedef Documentation
typedef std::list<quadedge::Vertex> geos::triangulate::IncrementalDelaunayTriangulator::VertexList
Definition at line 58 of file IncrementalDelaunayTriangulator.h.
Constructor & Destructor Documentation
geos::triangulate::IncrementalDelaunayTriangulator::IncrementalDelaunayTriangulator (quadedge::QuadEdgeSubdivision * subdiv)
Creates a new triangulator using the given QuadEdgeSubdivision. The triangulator uses the tolerance of the supplied subdivision.
Parameters
subdiv a subdivision in which to build the TIN
Definition at line 30 of file IncrementalDelaunayTriangulator.cpp.
                                      :
     subdiv(subdiv), isUsingTolerance(subdiv->getTolerance() > 0.0)
 {
 }
Member Function Documentation
QuadEdge & geos::triangulate::IncrementalDelaunayTriangulator::insertSite (const quadedge::Vertex & v)
Inserts a new point into a subdivision representing a Delaunay triangulation, and fixes the affected edges so that the result is still a Delaunay triangulation.
Returns
a quadedge containing the inserted vertex
This code is based on Guibas and Stolfi (1985), with minor modifications and a bug fix from Dani Lischinski (Graphic Gems 1993). (The modification I believe is the test for the inserted site falling exactly on an existing edge. Without this test zero-width triangles have been observed to be created)
Connect the new point to the vertices of the containing triangle (or quadrilateral, if the new point fell on an existing edge.)
Definition at line 44 of file IncrementalDelaunayTriangulator.cpp.
References geos::triangulate::quadedge::QuadEdgeSubdivision::connect(), geos::triangulate::quadedge::QuadEdge::dest(), geos::triangulate::quadedge::Vertex::getCoordinate(), geos::triangulate::quadedge::Vertex::isInCircle(), geos::triangulate::quadedge::QuadEdgeSubdivision::isOnEdge(), geos::triangulate::quadedge::QuadEdgeSubdivision::isVertexOfEdge(), geos::triangulate::quadedge::QuadEdge::lNext(), geos::triangulate::quadedge::QuadEdgeSubdivision::locate(), geos::triangulate::quadedge::QuadEdge::lPrev(), geos::triangulate::quadedge::QuadEdgeSubdivision::makeEdge(), geos::triangulate::quadedge::QuadEdge::oNext(), geos::triangulate::quadedge::QuadEdge::oPrev(), geos::triangulate::quadedge::QuadEdge::orig(), geos::triangulate::quadedge::QuadEdgeSubdivision::remove(), geos::triangulate::quadedge::Vertex::rightOf(), geos::triangulate::quadedge::QuadEdge::splice(), subdiv, geos::triangulate::quadedge::QuadEdge::swap(), and geos::triangulate::quadedge::QuadEdge::sym().
Referenced by insertSites().
 {
     QuadEdge *e = subdiv->locate(v);
     if(!e) {
         throw LocateFailureException("");
     }
     if (subdiv->isVertexOfEdge(*e, v)) {
         // point is already in subdivision.
         return *e;
     }
     else if (subdiv->isOnEdge(*e, v.getCoordinate())) {
         // the point lies exactly on an edge, so delete the edge
         // (it will be replaced by a pair of edges which have the point as a vertex)
         e = &e->oPrev();
         subdiv->remove(e->oNext());
     }
     QuadEdge* base = &subdiv->makeEdge(e->orig(), v);
     QuadEdge::splice(*base, *e);
     QuadEdge *startEdge = base;
     do {
         base = &subdiv->connect(*e, base->sym());
         e = &base->oPrev();
     } while (&e->lNext() != startEdge);
     // Examine suspect edges to ensure that the Delaunay condition
     // is satisfied.
     for (;;)
     {
         QuadEdge* t = &e->oPrev();
         if (t->dest().rightOf(*e) &&
                 v.isInCircle(e->orig(), t->dest(), e->dest())) {
             QuadEdge::swap(*e);
             e = &e->oPrev();
         } else if (&e->oNext() == startEdge) {
             return *base; // no more suspect edges.
         } else {
             e = &e->oNext().lPrev();
         }
     }
 }
void geos::triangulate::IncrementalDelaunayTriangulator::insertSites (const VertexList & vertices)
Inserts all sites in a collection. The inserted vertices MUST be unique up to the provided tolerance value. (i.e. no two vertices should be closer than the provided tolerance value). They do not have to be rounded to the tolerance grid, however.
Parameters
vertices a Collection of Vertex
Exceptions
LocateFailureException if the location algorithm fails to converge in a reasonable number of iterations
Definition at line 36 of file IncrementalDelaunayTriangulator.cpp.
References insertSite().
Referenced by geos::triangulate::DelaunayTriangulationBuilder::create(), and geos::triangulate::VoronoiDiagramBuilder::create().
 {
     for (VertexList::const_iterator x=vertices.begin();
             x != vertices.end(); ++x) {
         insertSite(*x);
     }
 }
Member Data Documentation
bool geos::triangulate::IncrementalDelaunayTriangulator::isUsingTolerance private
Definition at line 46 of file IncrementalDelaunayTriangulator.h.
quadedge::QuadEdgeSubdivision* geos::triangulate::IncrementalDelaunayTriangulator::subdiv private
Definition at line 45 of file IncrementalDelaunayTriangulator.h.
Referenced by insertSite().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/triangulate/IncrementalDelaunayTriangulator.h
/home/vicky/potree/geos/vicky/src/triangulate/IncrementalDelaunayTriangulator.cpp