GEOS: geos::noding::NodableSegmentString Class Reference
geos::noding::NodableSegmentString Class Reference abstract
An interface for classes which support adding nodes to a segment string.
#include <NodableSegmentString.h>
Public Types
typedef std::vector< const SegmentString * > ConstVect
typedef std::vector< SegmentString * > NonConstVect
Public Member Functions
NodableSegmentString (const void *newContext)
const void * getData () const
void setData (const void *data)
virtual unsigned int size () const =0
virtual const geom::Coordinate & getCoordinate (unsigned int i) const =0
virtual geom::CoordinateSequence * getCoordinates () const =0
Return a pointer to the CoordinateSequence associated with this SegmentString.
virtual bool isClosed () const =0
virtual std::ostream & print (std::ostream &os) const
Detailed Description
An interface for classes which support adding nodes to a segment string.
Author
Martin Davis
Definition at line 37 of file NodableSegmentString.h.
Member Typedef Documentation
typedef std::vector<const SegmentString*> geos::noding::SegmentString::ConstVect inherited
Definition at line 48 of file SegmentString.h.
typedef std::vector<SegmentString *> geos::noding::SegmentString::NonConstVect inherited
Definition at line 49 of file SegmentString.h.
Constructor & Destructor Documentation
geos::noding::NodableSegmentString::NodableSegmentString (const void * newContext) inline
Definition at line 42 of file NodableSegmentString.h.
     :
     SegmentString( newContext )
   { }
Member Function Documentation
virtual const geom::Coordinate& geos::noding::SegmentString::getCoordinate (unsigned int i) const pure virtual inherited
Implemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Referenced by geos::noding::SegmentNodeList::checkSplitEdgesCorrectness(), geos::noding::IntersectionFinderAdder::processIntersections(), geos::noding::SingleInteriorIntersectionFinder::processIntersections(), and geos::noding::IntersectionAdder::processIntersections().
virtual geom::CoordinateSequence* geos::noding::SegmentString::getCoordinates () const pure virtual inherited
Return a pointer to the CoordinateSequence associated with this SegmentString.
Note that the CoordinateSequence is owned by this SegmentString!
Implemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Referenced by geos::noding::MCIndexNoder::add(), geos::noding::MCIndexSegmentSetMutualIntersector::addToIndex(), geos::noding::MCIndexSegmentSetMutualIntersector::addToMonoChains(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::noding::NodingValidator::checkCollapses(), geos::noding::NodingValidator::checkEndPtVertexIntersections(), geos::noding::NodingValidator::checkInteriorIntersections(), geos::noding::SimpleNoder::computeIntersects(), geos::operation::buffer::BufferBuilder::computeNodedEdges(), geos::noding::SegmentIntersectionDetector::processIntersections(), geos::noding::ScaledNoder::rescale(), and geos::noding::ScaledNoder::scale().
const void* geos::noding::SegmentString::getData () const inline inherited
Gets the user-defined data for this segment string.
Returns
the user-defined data
Definition at line 70 of file SegmentString.h.
Referenced by geos::operation::buffer::BufferBuilder::computeNodedEdges().
 { return context; }
virtual bool geos::noding::SegmentString::isClosed () const pure virtual inherited
Implemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Referenced by geos::noding::IntersectionAdder::isTrivialIntersection().
std::ostream & geos::noding::SegmentString::print (std::ostream & os) const virtual inherited
Reimplemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Definition at line 49 of file SegmentString.cpp.
Referenced by geos::noding::operator<<().
 {
   os << "SegmentString" << std::endl;
   return os;
 }
void geos::noding::SegmentString::setData (const void * data) inline inherited
Sets the user-defined data for this segment string.
Parameters
data an Object containing user-defined data
Definition at line 77 of file SegmentString.h.
 { context=data; }
virtual unsigned int geos::noding::SegmentString::size () const pure virtual inherited
Implemented in geos::noding::NodedSegmentString, and geos::noding::BasicSegmentString.
Referenced by geos::noding::IntersectionAdder::isTrivialIntersection().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/noding/NodableSegmentString.h