GEOS: geos::io::Writer Class Reference
geos::io::Writer Class Reference
#include <Writer.h>
Public Member Functions
Writer ()
void reserve (std::size_t capacity)
~Writer ()
void write (const std::string &txt)
const std::string & toString ()
Private Attributes
std::string str
Detailed Description
Definition at line 35 of file Writer.h.
Constructor & Destructor Documentation
geos::io::Writer::Writer ()
Definition at line 28 of file Writer.cpp.
 {
 }
geos::io::Writer::~Writer ()
Definition at line 38 of file Writer.cpp.
 {
 }
Member Function Documentation
void geos::io::Writer::reserve (std::size_t capacity)
Definition at line 33 of file Writer.cpp.
 {
   str.reserve(capacity);
 }
const std::string & geos::io::Writer::toString (void)
Definition at line 49 of file Writer.cpp.
Referenced by geos::io::WKTWriter::write(), and geos::io::WKTWriter::writeFormatted().
 {
   return str;
 }
void geos::io::Writer::write (const std::string & txt)
Definition at line 43 of file Writer.cpp.
Referenced by geos::io::WKTWriter::appendCoordinate(), geos::io::WKTWriter::appendGeometryCollectionTaggedText(), geos::io::WKTWriter::appendGeometryCollectionText(), geos::io::WKTWriter::appendLinearRingTaggedText(), geos::io::WKTWriter::appendLineStringTaggedText(), geos::io::WKTWriter::appendLineStringText(), geos::io::WKTWriter::appendMultiLineStringTaggedText(), geos::io::WKTWriter::appendMultiLineStringText(), geos::io::WKTWriter::appendMultiPointTaggedText(), geos::io::WKTWriter::appendMultiPointText(), geos::io::WKTWriter::appendMultiPolygonTaggedText(), geos::io::WKTWriter::appendMultiPolygonText(), geos::io::WKTWriter::appendPointTaggedText(), geos::io::WKTWriter::appendPointText(), geos::io::WKTWriter::appendPolygonTaggedText(), geos::io::WKTWriter::appendPolygonText(), and geos::io::WKTWriter::indent().
 {
   str.append(txt);
 }
Member Data Documentation
std::string geos::io::Writer::str private
Definition at line 43 of file Writer.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/io/Writer.h
/home/vicky/potree/geos/vicky/src/io/Writer.cpp