GEOS: geos::geom::Geometry Class Reference
geos::geom::Geometry Class Reference abstract
Basic implementation of Geometry, constructed and destructed by GeometryFactory.
#include <geos.h>
Classes
class GeometryChangedFilter
Public Types
using ConstVect = std::vector< const Geometry * >
A vector of const Geometry pointers.
using NonConstVect = std::vector< Geometry * >
A vector of non-const Geometry pointers.
using Ptr = std::unique_ptr< Geometry >
An unique_ptr of Geometry.
Public Member Functions
virtual Geometry * clone () const =0
Make a deep-copy of this Geometry.
virtual ~Geometry ()
Destroy Geometry and all components.
const GeometryFactory * getFactory () const
Gets the factory which contains the context in which this geometry was created.
void setUserData (void *newUserData)
A simple scheme for applications to add their own custom data to a Geometry. An example use might be to add an object representing a Coordinate Reference System.
void * getUserData () const
Gets the user data object for this geometry, if any.
virtual int getSRID () const
virtual void setSRID (int newSRID)
const PrecisionModel * getPrecisionModel () const
Get the PrecisionModel used to create this Geometry.
virtual const Coordinate * getCoordinate () const =0
Returns a vertex of this Geometry, or NULL if this is the empty geometry.
virtual CoordinateSequence * getCoordinates () const =0
Returns this Geometry vertices. Caller takes ownership of the returned object.
virtual std::size_t getNumPoints () const =0
Returns the count of this Geometrys vertices.
virtual bool isSimple () const
Returns false if the Geometry not simple.
virtual std::string getGeometryType () const =0
Return a string representation of this Geometry type.
virtual GeometryTypeId getGeometryTypeId () const =0
Return an integer representation of this Geometry type.
virtual std::size_t getNumGeometries () const
virtual const Geometry * getGeometryN (std::size_t) const
virtual bool isValid () const
Tests the validity of this Geometry.
virtual bool isEmpty () const =0
Returns whether or not the set of points in this Geometry is empty.
virtual bool isRectangle () const
Polygon overrides to check for actual rectangle.
virtual Dimension::DimensionType getDimension () const =0
Returns the dimension of this Geometry (0=point, 1=line, 2=surface)
virtual int getCoordinateDimension () const =0
Returns the coordinate dimension of this Geometry (2=XY, 3=XYZ, 4=XYZM in future).
virtual Geometry * getBoundary () const =0
Returns the boundary, or an empty geometry of appropriate dimension if this Geometry is empty.
virtual int getBoundaryDimension () const =0
Returns the dimension of this Geometrys inherent boundary.
virtual Geometry * getEnvelope () const
Returns this Geometrys bounding box.
virtual const Envelope * getEnvelopeInternal () const
Returns the minimum and maximum x and y values in this Geometry, or a null Envelope if this Geometry is empty.
virtual bool disjoint (const Geometry *other) const
virtual bool touches (const Geometry *other) const
Returns true if the DE-9IM intersection matrix for the two Geometrys is FT*******, F**T***** or F***T****.
virtual bool intersects (const Geometry *g) const
Returns true if disjoint returns false.
virtual bool crosses (const Geometry *g) const
virtual bool within (const Geometry *g) const
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*F**F***.
virtual bool contains (const Geometry *g) const
Returns true if other.within(this) returns true.
virtual bool overlaps (const Geometry *g) const
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*T***T** (for two points or two surfaces) 1*T***T** (for two curves).
virtual bool relate (const Geometry *g, const std::string &intersectionPattern) const
Returns true if the elements in the DE-9IM intersection matrix for the two Geometrys match the elements in intersectionPattern.
bool relate (const Geometry &g, const std::string &intersectionPattern) const
virtual IntersectionMatrix * relate (const Geometry *g) const
Returns the DE-9IM intersection matrix for the two Geometrys.
IntersectionMatrix * relate (const Geometry &g) const
virtual bool equals (const Geometry *g) const
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*F**FFF*.
bool covers (const Geometry *g) const
Returns true if this geometry covers the specified geometry.
bool coveredBy (const Geometry *g) const
Tests whether this geometry is covered by the specified geometry.
virtual std::string toString () const
Returns the Well-known Text representation of this Geometry.
virtual std::string toText () const
virtual Geometry * buffer (double distance) const
Returns a buffer region around this Geometry having the given width.
virtual Geometry * buffer (double distance, int quadrantSegments) const
Returns a buffer region around this Geometry having the given width and with a specified number of segments used to approximate curves.
virtual Geometry * buffer (double distance, int quadrantSegments, int endCapStyle) const
Computes a buffer area around this geometry having the given width and with a specified accuracy of approximation for circular arcs, and using a specified end cap style.
virtual Geometry * convexHull () const
Returns the smallest convex Polygon that contains all the points in the Geometry.
virtual Geometry * reverse () const =0
virtual Geometry * intersection (const Geometry *other) const
Returns a Geometry representing the points shared by this Geometry and other.
Geometry * Union (const Geometry *other) const
Returns a Geometry representing all the points in this Geometry and other.
Ptr Union () const
virtual Geometry * difference (const Geometry *other) const
Returns a Geometry representing the points making up this Geometry that do not make up other.
virtual Geometry * symDifference (const Geometry *other) const
Returns a set combining the points in this Geometry not in other, and the points in other not in this Geometry.
virtual bool equalsExact (const Geometry *other, double tolerance=0) const =0
Returns true iff the two Geometrys are of the same type and their vertices corresponding by index are equal up to a specified tolerance.
virtual void apply_rw (const CoordinateFilter *filter)=0
virtual void apply_ro (CoordinateFilter *filter) const =0
virtual void apply_rw (GeometryFilter *filter)
virtual void apply_ro (GeometryFilter *filter) const
virtual void apply_rw (GeometryComponentFilter *filter)
virtual void apply_ro (GeometryComponentFilter *filter) const
virtual void apply_rw (CoordinateSequenceFilter &filter)=0
virtual void apply_ro (CoordinateSequenceFilter &filter) const =0
template<class T >
void applyComponentFilter (T &f) const
Apply a fiter to each component of this geometry. The filter is expected to provide a .filter(const Geometry*) method.
virtual void normalize ()=0
Converts this Geometry to normal form (or canonical form).
virtual int compareTo (const Geometry *geom) const
virtual double distance (const Geometry *g) const
Returns the minimum distance between this Geometry and the Geometry g.
virtual double getArea () const
Returns the area of this Geometry.
virtual double getLength () const
Returns the length of this Geometry.
virtual bool isWithinDistance (const Geometry *geom, double cDistance) const
Tests whether the distance from this Geometry to another is less than or equal to a specified value.
virtual Point * getCentroid () const
Computes the centroid of this Geometry.
virtual bool getCentroid (Coordinate &ret) const
Computes the centroid of this Geometry as a Coordinate.
virtual Point * getInteriorPoint () const
Computes an interior point of this Geometry.
virtual void geometryChanged ()
void geometryChangedAction ()
Notifies this Geometry that its Coordinates have been changed by an external party.
Protected Member Functions
virtual bool isEquivalentClass (const Geometry *other) const
Returns whether the two Geometrys are equal, from the point of view of the equalsExact method.
virtual Envelope::Ptr computeEnvelopeInternal () const =0
virtual int compareToSameClass (const Geometry *geom) const =0
int compare (std::vector< Coordinate > a, std::vector< Coordinate > b) const
int compare (std::vector< Geometry * > a, std::vector< Geometry * > b) const
bool equal (const Coordinate &a, const Coordinate &b, double tolerance) const
Geometry (const Geometry &geom)
Polygon overrides to check for actual rectangle.
Geometry (const GeometryFactory *factory)
Construct a geometry with the given GeometryFactory.
Static Protected Member Functions
static bool hasNonEmptyElements (const std::vector< Geometry * > *geometries)
Returns true if the array contains any non-empty Geometrys.
static bool hasNullElements (const CoordinateSequence *list)
Returns true if the CoordinateSequence contains any null elements.
static bool hasNullElements (const std::vector< Geometry * > *lrs)
Returns true if the vector contains any null elements.
static void checkNotGeometryCollection (const Geometry *g)
Protected Attributes
std::unique_ptr< Envelope > envelope
The bounding box of this Geometry.
int SRID
Private Member Functions
int getClassSortIndex () const
Private Attributes
const GeometryFactory * _factory
The GeometryFactory used to create this Geometry.
void * _userData
Static Private Attributes
static GeometryChangedFilter geometryChangedFilter
Friends
class GeometryFactory
Detailed Description
Basic implementation of Geometry, constructed and destructed by GeometryFactory.
clone returns a deep copy of the object. Use GeometryFactory to construct.
Binary Predicates
Because it is not clear at this time what semantics for spatial analysis methods involving GeometryCollections would be useful, GeometryCollections are not supported as arguments to binary predicates (other than convexHull) or the relate method.
Set-Theoretic Methods
The spatial analysis methods will return the most specific class possible to represent the result. If the result is homogeneous, a Point, LineString, or Polygon will be returned if the result contains a single element; otherwise, a MultiPoint, MultiLineString, or MultiPolygon will be returned. If the result is heterogeneous a GeometryCollection will be returned.
Because it is not clear at this time what semantics for set-theoretic methods involving GeometryCollections would be useful, GeometryCollections are not supported as arguments to the set-theoretic methods.
Representation of Computed Geometries
The SFS states that the result of a set-theoretic method is the "point-set" result of the usual set-theoretic definition of the operation (SFS 3.2.21.1). However, there are sometimes many ways of representing a point set as a Geometry.
The SFS does not specify an unambiguous representation of a given point set returned from a spatial analysis method. One goal of JTS is to make this specification precise and unambiguous. JTS will use a canonical form for Geometrys returned from spatial analysis methods. The canonical form is a Geometry which is simple and noded:
Simple means that the Geometry returned will be simple according to the JTS definition of isSimple.
Noded applies only to overlays involving LineStrings. It means that all intersection points on LineStrings will be present as endpoints of LineStrings in the result.
This definition implies that non-simple geometries which are arguments to spatial analysis methods must be subjected to a line-dissolve process to ensure that the results are simple.
Constructed Points And The Precision Model
The results computed by the set-theoretic methods may contain constructed points which are not present in the input Geometry. These new points arise from intersections between line segments in the edges of the input Geometry. In the general case it is not possible to represent constructed points exactly. This is due to the fact that the coordinates of an intersection point may contain twice as many bits of precision as the coordinates of the input line segments. In order to represent these constructed points explicitly, JTS must truncate them to fit the PrecisionModel.
Unfortunately, truncating coordinates moves them slightly. Line segments which would not be coincident in the exact result may become coincident in the truncated representation. This in turn leads to "topology collapses" – situations where a computed element has a lower dimension than it would in the exact result.
When JTS detects topology collapses during the computation of spatial analysis methods, it will throw an exception. If possible the exception will report the location of the collapse.
equals(Object) and hashCode are not overridden, so that when two topologically equal Geometries are added to HashMaps and HashSets, they remain distinct. This behaviour is desired in many cases.
Definition at line 177 of file Geometry.h.
Member Typedef Documentation
using geos::geom::Geometry::ConstVect = std::vector<const Geometry *>
A vector of const Geometry pointers.
Definition at line 184 of file Geometry.h.
using geos::geom::Geometry::NonConstVect = std::vector<Geometry *>
A vector of non-const Geometry pointers.
Definition at line 187 of file Geometry.h.
using geos::geom::Geometry::Ptr = std::unique_ptr<Geometry>
An unique_ptr of Geometry.
Definition at line 190 of file Geometry.h.
Constructor & Destructor Documentation
geos::geom::Geometry::~Geometry () virtual
Destroy Geometry and all components.
Definition at line 811 of file Geometry.cpp.
References _factory, and geos::geom::GeometryFactory::dropRef().
 {
   _factory->dropRef();
 }
geos::geom::Geometry::Geometry (const Geometry & geom) protected
Polygon overrides to check for actual rectangle.
Deprecated:
Deprecated:
Definition at line 122 of file Geometry.cpp.
References _factory, geos::geom::GeometryFactory::addRef(), and envelope.
   :
   SRID(geom.getSRID()),
   _factory(geom._factory),
   _userData(nullptr)
 {
   if ( geom.envelope.get() )
   {
     envelope.reset(new Envelope(*(geom.envelope)));
   }
   //factory=geom.factory;
   //envelope(new Envelope(*(geom.envelope.get())));
   //SRID=geom.getSRID();
   //_userData=NULL;
   _factory->addRef();
 }
geos::geom::Geometry::Geometry (const GeometryFactory * factory) protected
Construct a geometry with the given GeometryFactory.
Will keep a reference to the factory, so don't delete it until al Geometry objects referring to it are deleted.
Parameters
factory
Definition at line 109 of file Geometry.cpp.
References _factory, geos::geom::GeometryFactory::addRef(), geos::geom::GeometryFactory::getDefaultInstance(), geos::geom::GeometryFactory::getSRID(), and SRID.
   :
   envelope(nullptr),
   _factory(newFactory),
   _userData(nullptr)
 {
   if ( _factory == nullptr ) {
     _factory = GeometryFactory::getDefaultInstance();
   }
   SRID=_factory->getSRID();
   _factory->addRef();
 }
Member Function Documentation
virtual void geos::geom::Geometry::apply_ro (CoordinateFilter * filter) const pure virtual
Implemented in geos::geom::LineString, geos::geom::Polygon, geos::geom::GeometryCollection, and geos::geom::Point.
Referenced by geos::precision::CommonBitsRemover::add(), geos::operation::overlay::ElevationMatrix::add(), geos::operation::polygonize::Polygonizer::add(), geos::operation::distance::FacetSequenceTreeBuilder::computeFacetSequences(), geos::algorithm::distance::DiscreteHausdorffDistance::computeOrientedDistance(), geos::algorithm::ConvexHull::extractCoordinates(), geos::noding::GeometryNoder::extractSegmentStrings(), geos::operation::overlay::snap::GeometrySnapper::extractTargetCoordinates(), geos::geom::util::ComponentCoordinateExtracter::getCoordinates(), geos::operation::distance::ConnectedElementPointFilter::getCoordinates(), geos::geom::util::LinearComponentExtracter::getLines(), geos::operation::distance::ConnectedElementLocationFilter::getLocations(), geos::geom::util::PointExtracter::getPoints(), geos::geom::util::PolygonExtracter::getPolygons(), and geos::simplify::TopologyPreservingSimplifier::getResultGeometry().
void geos::geom::Geometry::apply_ro (GeometryFilter * filter) const virtual
Reimplemented in geos::geom::LineString, geos::geom::GeometryCollection, geos::geom::Polygon, and geos::geom::Point.
Definition at line 838 of file Geometry.cpp.
References geos::geom::GeometryFilter::filter_ro().
 {
   filter->filter_ro(this);
 }
void geos::geom::Geometry::apply_ro (GeometryComponentFilter * filter) const virtual
Reimplemented in geos::geom::LineString, geos::geom::Polygon, geos::geom::GeometryCollection, and geos::geom::Point.
Definition at line 850 of file Geometry.cpp.
References geos::geom::GeometryComponentFilter::filter_ro().
 {
   filter->filter_ro(this);
 }
virtual void geos::geom::Geometry::apply_ro (CoordinateSequenceFilter & filter) const pure virtual
Performs a read-only operation on the coordinates in this Geometry's CoordinateSequences.
Parameters
filter the filter to apply
Implemented in geos::geom::LineString, geos::geom::GeometryCollection, geos::geom::Polygon, and geos::geom::Point.
virtual void geos::geom::Geometry::apply_rw (const CoordinateFilter * filter) pure virtual
Implemented in geos::geom::LineString, geos::geom::GeometryCollection, geos::geom::Polygon, and geos::geom::Point.
Referenced by geos::precision::CommonBitsRemover::addCommonBits(), geos::operation::overlay::ElevationMatrix::elevate(), geometryChanged(), and geos::precision::CommonBitsRemover::removeCommonBits().
void geos::geom::Geometry::apply_rw (GeometryFilter * filter) virtual
Reimplemented in geos::geom::LineString, geos::geom::GeometryCollection, geos::geom::Polygon, and geos::geom::Point.
Definition at line 844 of file Geometry.cpp.
References geos::geom::GeometryFilter::filter_rw().
 {
   filter->filter_rw(this);
 }
void geos::geom::Geometry::apply_rw (GeometryComponentFilter * filter) virtual
Reimplemented in geos::geom::LineString, geos::geom::Polygon, geos::geom::GeometryCollection, and geos::geom::Point.
Definition at line 856 of file Geometry.cpp.
References geos::geom::GeometryComponentFilter::filter_rw().
 {
   filter->filter_rw(this);
 }
virtual void geos::geom::Geometry::apply_rw (CoordinateSequenceFilter & filter) pure virtual
Performs an operation on the coordinates in this Geometry's CoordinateSequences. If the filter reports that a coordinate value has been changed, geometryChanged will be called automatically.
Parameters
filter the filter to apply
Implemented in geos::geom::LineString, geos::geom::GeometryCollection, geos::geom::Polygon, and geos::geom::Point.
template<class T > void geos::geom::Geometry::applyComponentFilter (T & f) const inline
Apply a fiter to each component of this geometry. The filter is expected to provide a .filter(const Geometry*) method.
I intend similar templated methods to replace all the virtual apply_rw and apply_ro functions... –strk(2005-02-06);
Definition at line 703 of file Geometry.h.
References geos::operation::intersection::distance().
Referenced by geos::operation::linemerge::LineMerger::add(), and geos::operation::linemerge::LineSequencer::add().
   {
     for(std::size_t i=0, n=getNumGeometries(); i<n; ++i)
       f.filter(getGeometryN(i));
   }
Geometry * geos::geom::Geometry::buffer (double distance) const virtual
Returns a buffer region around this Geometry having the given width.
Exceptions
util::TopologyException if a robustness error occurs
Definition at line 481 of file Geometry.cpp.
Referenced by geos::precision::EnhancedPrecisionOp::buffer(), geos::operation::buffer::BufferOp::bufferFixedPrecision(), geos::simplify::DPTransformer::createValidArea(), geos::precision::GeometryPrecisionReducer::fixPolygonalTopology(), and GEOSBuffer_r().
 {
   return BufferOp::bufferOp(this, distance);
 }
Geometry * geos::geom::Geometry::buffer (double distance, int quadrantSegments) const virtual
Returns a buffer region around this Geometry having the given width and with a specified number of segments used to approximate curves.
Exceptions
util::TopologyException if a robustness error occurs
Definition at line 487 of file Geometry.cpp.
 {
   return BufferOp::bufferOp(this, distance, quadrantSegments);
 }
Geometry * geos::geom::Geometry::buffer (double distance, int quadrantSegments, int endCapStyle) const virtual
Computes a buffer area around this geometry having the given width and with a specified accuracy of approximation for circular arcs, and using a specified end cap style.
Buffer area boundaries can contain circular arcs. To represent these arcs using linear geometry they must be approximated with line segments.
The quadrantSegments argument allows controlling the accuracy of the approximation by specifying the number of line segments used to represent a quadrant of a circle
The end cap style specifies the buffer geometry that will be created at the ends of linestrings. The styles provided are:
BufferOp::CAP_ROUND - (default) a semi-circle
BufferOp::CAP_BUTT - a straight line perpendicular to the end segment
BufferOp::CAP_SQUARE - a half-square
Parameters
distance the width of the buffer (may be positive, negative or 0)
quadrantSegments the number of line segments used to represent a quadrant of a circle
endCapStyle the end cap style to use
Returns
an area geometry representing the buffer region
Exceptions
util::TopologyException if a robustness error occurs
See also
BufferOp
Definition at line 493 of file Geometry.cpp.
 {
   return BufferOp::bufferOp(this, distance, quadrantSegments, endCapStyle);
 }
void geos::geom::Geometry::checkNotGeometryCollection (const Geometry * g) static protected
Definition at line 682 of file Geometry.cpp.
Referenced by isSimple().
 {
   if ((typeid(*g)==typeid(GeometryCollection))) {
     throw  geos::util::IllegalArgumentException("This method does not support GeometryCollection arguments\n");
   }
 }
virtual Geometry* geos::geom::Geometry::clone () const pure virtual
Make a deep-copy of this Geometry.
Implemented in geos::geom::MultiPolygon, geos::geom::LinearRing, geos::geom::LineString, geos::geom::MultiPoint, geos::geom::Point, geos::geom::Polygon, geos::geom::MultiLineString, and geos::geom::GeometryCollection.
Referenced by geos::geom::BinaryOp(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::geom::GeometryFactory::buildGeometry(), geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), difference(), geos::geom::util::CoordinateOperation::edit(), GEOSGeom_clone_r(), geos::geom::MultiPolygon::getBoundary(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::simplify::TopologyPreservingSimplifier::getResultGeometry(), geos::precision::CommonBitsOp::removeCommonBits(), geos::operation::overlay::snap::SnapOverlayOp::removeCommonBits(), geos::geom::SnapOp(), symDifference(), geos::operation::geounion::PointGeometryUnion::Union(), Union(), geos::operation::geounion::CascadedUnion::unionSafe(), and geos::operation::geounion::CascadedPolygonUnion::unionSafe().
int geos::geom::Geometry::compare (std::vector< Coordinate > a, std::vector< Coordinate > b) const protected
Definition at line 723 of file Geometry.cpp.
References geos::geom::Coordinate::compareTo().
Referenced by geos::geom::GeometryCollection::compareToSameClass().
 {
   size_t i=0;
   size_t j=0;
   while (i<a.size() && j<b.size()) {
     Coordinate& aCoord=a[i];
     Coordinate& bCoord=b[j];
     int comparison=aCoord.compareTo(bCoord);
     if (comparison!=0) {
       return comparison;
     }
     i++;
     j++;
   }
   if (i<a.size()) {
     return 1;
   }
   if (j<b.size()) {
     return -1;
   }
   return 0;
 }
int geos::geom::Geometry::compare (std::vector< Geometry * > a, std::vector< Geometry * > b) const protected
Definition at line 747 of file Geometry.cpp.
References compareTo().
 {
   size_t i=0;
   size_t j=0;
   while (i<a.size() && j<b.size()) {
     Geometry *aGeom=a[i];
     Geometry *bGeom=b[j];
     int comparison=aGeom->compareTo(bGeom);
     if (comparison!=0) {
       return comparison;
     }
     i++;
     j++;
   }
   if (i<a.size()) {
     return 1;
   }
   if (j<b.size()) {
     return -1;
   }
   return 0;
 }
int geos::geom::Geometry::compareTo (const Geometry * geom) const virtual
Definition at line 652 of file Geometry.cpp.
References compareToSameClass(), getClassSortIndex(), and isEmpty().
Referenced by compare(), geos::geom::LineStringLT::operator()(), and geos::geom::GeometryGreaterThen::operator()().
 {
   // compare to self
   if ( this == geom ) return 0;
   if (getClassSortIndex()!=geom->getClassSortIndex()) {
     return getClassSortIndex()-geom->getClassSortIndex();
   }
   if (isEmpty() && geom->isEmpty()) {
     return 0;
   }
   if (isEmpty()) {
     return -1;
   }
   if (geom->isEmpty()) {
     return 1;
   }
   return compareToSameClass(geom);
 }
virtual int geos::geom::Geometry::compareToSameClass (const Geometry * geom) const protected pure virtual
Implemented in geos::geom::GeometryCollection, geos::geom::LineString, geos::geom::Point, and geos::geom::Polygon.
Referenced by compareTo().
virtual Envelope::Ptr geos::geom::Geometry::computeEnvelopeInternal () const protected pure virtual
Implemented in geos::geom::GeometryCollection, geos::geom::LineString, geos::geom::Polygon, and geos::geom::Point.
Referenced by getEnvelopeInternal().
bool geos::geom::Geometry::contains (const Geometry * g) const virtual
Returns true if other.within(this) returns true.
Definition at line 391 of file Geometry.cpp.
References getEnvelopeInternal(), isRectangle(), and relate().
Referenced by geos::geom::prep::BasicPreparedGeometry::contains(), geos::geom::prep::PreparedPolygonContains::fullTopologicalPredicate(), GEOSContains_r(), and within().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->contains(g->getEnvelopeInternal()))
     return false;
 #endif
   // optimization for rectangle arguments
   if (isRectangle()) {
     const Polygon* p = dynamic_cast<const Polygon*>(this);
     return predicate::RectangleContains::contains(*p, *g);
   }
   // Incorrect: contains is not commutative
   //if (g->isRectangle()) {
   //  return predicate::RectangleContains::contains((const Polygon&)*g, *this);
   //}
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isContains();
   return res;
 }
Geometry * geos::geom::Geometry::convexHull () const virtual
Returns the smallest convex Polygon that contains all the points in the Geometry.
Reimplemented in geos::geom::Polygon.
Definition at line 499 of file Geometry.cpp.
References geos::algorithm::ConvexHull::getConvexHull().
Referenced by geos::geom::Polygon::convexHull(), and GEOSConvexHull_r().
 {
   return ConvexHull(this).getConvexHull();
 }
bool geos::geom::Geometry::coveredBy (const Geometry * g) const inline
Tests whether this geometry is covered by the specified geometry.
The coveredBy predicate has the following equivalent definitions:
Every point of this geometry is a point of the other geometry.
The DE-9IM Intersection Matrix for the two geometries matches [T*F**F***] or [*TF**F***] or [**FT*F***] or [**F*TF***]
g.covers(this) (coveredBy is the converse of covers)
If either geometry is empty, the value of this predicate is false.
This predicate is similar to within, but is more inclusive (i.e. returns true for more cases).
Parameters
g the Geometry with which to compare this Geometry
Returns
true if this Geometry is covered by g
See also
Geometry::within
Geometry::covers
Definition at line 518 of file Geometry.h.
References covers(), and geos::operation::intersection::distance().
Referenced by geos::geom::prep::BasicPreparedGeometry::coveredBy(), and GEOSCoveredBy_r().
{
     return g->covers(this);
   }
bool geos::geom::Geometry::covers (const Geometry * g) const
Returns true if this geometry covers the specified geometry.
The covers predicate has the following equivalent definitions:
Every point of the other geometry is a point of this geometry.
The DE-9IM Intersection Matrix for the two geometries is T*****FF* or *T****FF* or ***T**FF* or ****T*FF*
g.coveredBy(this) (covers is the inverse of coveredBy)
If either geometry is empty, the value of this predicate is false.
This predicate is similar to contains, but is more inclusive (i.e. returns true for more cases). In particular, unlike contains it does not distinguish between points in the boundary and in the interior of geometries. For most situations, covers should be used in preference to contains. As an added benefit, covers is more amenable to optimization, and hence should be more performant.
Parameters
g the Geometry with which to compare this Geometry
Returns
true if this Geometry covers g
See also
Geometry::contains
Geometry::coveredBy
Definition at line 351 of file Geometry.cpp.
References getEnvelopeInternal(), isRectangle(), and relate().
Referenced by coveredBy(), geos::geom::prep::BasicPreparedGeometry::covers(), geos::geom::prep::PreparedPolygonCovers::fullTopologicalPredicate(), and GEOSCovers_r().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->covers(g->getEnvelopeInternal()))
     return false;
 #endif
   // optimization for rectangle arguments
   if (isRectangle()) {
     // since we have already tested that the test envelope
     // is covered
     return true;
   }
   unique_ptr<IntersectionMatrix> im(relate(g));
   return im->isCovers();
 }
bool geos::geom::Geometry::crosses (const Geometry * g) const virtual
Tests whether this geometry crosses the specified geometry.
The crosses predicate has the following equivalent definitions:
The geometries have some but not all interior points in common.
The DE-9IM Intersection Matrix for the two geometries matches
[T*T******] (for P/L, P/A, and L/A situations)
[T*****T**] (for L/P, A/P, and A/L situations)
[0********] (for L/L situations) For any other combination of dimensions this predicate returns false.
The SFS defined this predicate only for P/L, P/A, L/L, and L/A situations. JTS extends the definition to apply to L/P, A/P and A/L situations as well, in order to make the relation symmetric.
Parameters
g the Geometry with which to compare this Geometry
Returns
true if the two Geometrys cross.
Definition at line 372 of file Geometry.cpp.
References getDimension(), getEnvelopeInternal(), intersects(), and relate().
Referenced by geos::geom::prep::BasicPreparedGeometry::crosses(), and GEOSCrosses_r().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return false;
 #endif
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isCrosses(getDimension(), g->getDimension());
   return res;
 }
Geometry * geos::geom::Geometry::difference (const Geometry * other) const virtual
Returns a Geometry representing the points making up this Geometry that do not make up other.
Exceptions
util::TopologyException if a robustness error occurs
util::IllegalArgumentException if either input is a non-empty GeometryCollection
Definition at line 598 of file Geometry.cpp.
References geos::geom::BinaryOp(), clone(), geos::geom::GeometryFactory::createGeometryCollection(), getFactory(), and isEmpty().
Referenced by geos::precision::EnhancedPrecisionOp::difference(), and GEOSDifference_r().
 {
   // special case: if A.isEmpty ==> empty; if B.isEmpty ==> A
   if (isEmpty()) return getFactory()->createGeometryCollection();
   if (other->isEmpty()) return clone();
   return BinaryOp(this, other, overlayOp(OverlayOp::opDIFFERENCE)).release();
 }
bool geos::geom::Geometry::disjoint (const Geometry * other) const virtual
Tests whether this geometry is disjoint from the specified geometry.
The disjoint predicate has the following equivalent definitions:
The two geometries have no point in common
The DE-9IM Intersection Matrix for the two geometries matches [FF*FF****]
! g.intersects(this) (disjoint is the inverse of intersects)
Parameters
g the Geometry with which to compare this Geometry
Returns
true if the two Geometrys are disjoint
See also
Geometry::intersects
Definition at line 284 of file Geometry.cpp.
References getEnvelopeInternal(), intersects(), and relate().
Referenced by GEOSDisjoint_r().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return true;
 #endif
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isDisjoint();
   return res;
 }
double geos::geom::Geometry::distance (const Geometry * other) const virtual
Returns the minimum distance between this Geometry and the Geometry g.
Returns the minimum distance between this Geometry and the other Geometry
Parameters
other the Geometry from which to compute the distance
Definition at line 777 of file Geometry.cpp.
References geos::operation::intersection::distance().
Referenced by geos::index::strtree::GeometryItemDistance::distance(), GEOSDistance_r(), and isWithinDistance().
 {
   return DistanceOp::distance(this, other);
 }
bool geos::geom::Geometry::equal (const Coordinate & a, const Coordinate & b, double tolerance) const protected
Definition at line 826 of file Geometry.cpp.
References geos::geom::Coordinate::distance().
Referenced by geos::geom::Point::equalsExact(), and geos::geom::LineString::equalsExact().
 {
   if (tolerance==0)
   {
     return a == b; // 2D only !!!
   }
   //double dist=a.distance(b);
   return a.distance(b)<=tolerance;
 }
bool geos::geom::Geometry::equals (const Geometry * g) const virtual
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*F**FFF*.
Definition at line 436 of file Geometry.cpp.
References getDimension(), getEnvelopeInternal(), isEmpty(), and relate().
Referenced by GEOSEquals_r().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->equals(g->getEnvelopeInternal()))
     return false;
 #endif
   if (isEmpty()) return g->isEmpty();
   else if (g->isEmpty()) return isEmpty();
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isEquals(getDimension(), g->getDimension());
   return res;
 }
virtual bool geos::geom::Geometry::equalsExact (const Geometry * other, double tolerance = 0) const pure virtual
Returns true iff the two Geometrys are of the same type and their vertices corresponding by index are equal up to a specified tolerance.
Implemented in geos::geom::LineString, geos::geom::Point, geos::geom::Polygon, geos::geom::GeometryCollection, geos::geom::MultiPolygon, geos::geom::MultiPoint, and geos::geom::MultiLineString.
Referenced by geos::geom::Polygon::equalsExact(), and GEOSEqualsExact_r().
void geos::geom::Geometry::geometryChanged () virtual
Notifies this Geometry that its Coordinates have been changed by an external party (using a CoordinateFilter, for example). The Geometry will flush and/or update any information it has cached (such as its Envelope).
Definition at line 244 of file Geometry.cpp.
References apply_rw(), and geometryChangedFilter.
Referenced by geos::precision::CommonBitsRemover::addCommonBits(), geos::geom::Point::apply_rw(), geos::geom::Polygon::apply_rw(), geos::geom::GeometryCollection::apply_rw(), geos::geom::LineString::apply_rw(), and geos::precision::CommonBitsRemover::removeCommonBits().
 {
   apply_rw(&geometryChangedFilter);
 }
void geos::geom::Geometry::geometryChangedAction ()
Notifies this Geometry that its Coordinates have been changed by an external party.
Notifies this Geometry that its Coordinates have been changed by an external party. When geometryChanged is called, this method will be called for this Geometry and its component Geometries.
See also
apply(GeometryComponentFilter *)
Definition at line 256 of file Geometry.cpp.
References envelope.
Referenced by geos::geom::Geometry::GeometryChangedFilter::filter_rw().
 {
   //delete envelope;
   envelope.reset(nullptr);
 }
double geos::geom::Geometry::getArea () const virtual
Returns the area of this Geometry.
Returns the area of this Geometry. Areal Geometries have a non-zero area. They override this function to compute the area. Others return 0.0
Returns
the area of the Geometry
Reimplemented in geos::geom::GeometryCollection, and geos::geom::Polygon.
Definition at line 791 of file Geometry.cpp.
Referenced by geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), and GEOSArea_r().
 {
   return 0.0;
 }
virtual Geometry* geos::geom::Geometry::getBoundary () const pure virtual
Returns the boundary, or an empty geometry of appropriate dimension if this Geometry is empty.
(In the case of zero-dimensional geometries, an empty GeometryCollection is returned.) For a discussion of this function, see the OpenGIS Simple Features Specification. As stated in SFS Section 2.1.13.1, "the boundary of a Geometry is a set of Geometries of the next lower dimension."
Returns
the closure of the combinatorial boundary of this Geometry. Ownershipof the returned object transferred to caller.
Implemented in geos::geom::LineString, geos::geom::Point, geos::geom::GeometryCollection, geos::geom::Polygon, geos::geom::MultiPolygon, geos::geom::MultiPoint, and geos::geom::MultiLineString.
Referenced by geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), GEOSBoundary_r(), and geos::operation::overlay::validate::FuzzyPointLocator::getLineWork().
virtual int geos::geom::Geometry::getBoundaryDimension () const pure virtual
Returns the dimension of this Geometrys inherent boundary.
Implemented in geos::geom::GeometryCollection, geos::geom::LineString, geos::geom::Point, geos::geom::LinearRing, geos::geom::Polygon, geos::geom::MultiPolygon, geos::geom::MultiPoint, and geos::geom::MultiLineString.
Referenced by geos::operation::relate::RelateComputer::computeDisjointIM().
Point * geos::geom::Geometry::getCentroid () const virtual
Computes the centroid of this Geometry.
The centroid is equal to the centroid of the set of component Geometries of highest dimension (since the lower-dimension geometries contribute zero "weight" to the centroid)
Returns
a Point which is the centroid of this Geometry
Definition at line 198 of file Geometry.cpp.
References geos::geom::GeometryFactory::createPoint(), and getFactory().
Referenced by GEOSGetCentroid_r(), geos::algorithm::InteriorPointLine::InteriorPointLine(), and geos::algorithm::InteriorPointPoint::InteriorPointPoint().
 {
   Coordinate centPt;
   if ( ! getCentroid(centPt) ) return nullptr;
   // We don't use createPointFromInternalCoord here
   // because ::getCentroid() takes care about rounding
   Point *pt=getFactory()->createPoint(centPt);
   return pt;
 }
bool geos::geom::Geometry::getCentroid (Coordinate & ret) const virtual
Computes the centroid of this Geometry as a Coordinate.
Returns false if centroid cannot be computed (EMPTY geometry)
Definition at line 211 of file Geometry.cpp.
References getPrecisionModel(), isEmpty(), and geos::geom::PrecisionModel::makePrecise().
 {
   if ( isEmpty() ) { return false; }
   if ( ! Centroid::getCentroid(*this, ret) ) return false;
   getPrecisionModel()->makePrecise(ret); // not in JTS
   return true;
 }
int geos::geom::Geometry::getClassSortIndex () const private
Definition at line 691 of file Geometry.cpp.
Referenced by geos::geom::GeometryFactory::buildGeometry(), and compareTo().
 {
   //const type_info &t=typeid(*this);
        if ( typeid(*this) == typeid(Point)              ) return 0;
   else if ( typeid(*this) == typeid(MultiPoint)         ) return 1;
   else if ( typeid(*this) == typeid(LineString)         ) return 2;
   else if ( typeid(*this) == typeid(LinearRing)         ) return 3;
   else if ( typeid(*this) == typeid(MultiLineString)    ) return 4;
   else if ( typeid(*this) == typeid(Polygon)            ) return 5;
   else if ( typeid(*this) == typeid(MultiPolygon)       ) return 6;
   else
   {
     assert(typeid(*this) == typeid(GeometryCollection)); // unsupported class
     return 7;
   }
 #if 0
   string str="Class not supported: ";
   str.append(typeid(*this).name());
   str.append("");
   Assert::shouldNeverReachHere(str);
   return -1;
 #endif
 }
virtual const Coordinate* geos::geom::Geometry::getCoordinate () const pure virtual
Returns a vertex of this Geometry, or NULL if this is the empty geometry.
Implemented in geos::geom::LineString, geos::geom::GeometryCollection, geos::geom::Polygon, and geos::geom::Point.
Referenced by geos::algorithm::distance::DistanceToPoint::computeDistance(), geos::geom::Point::equalsExact(), geos::geom::util::ComponentCoordinateExtracter::filter_ro(), geos::operation::distance::ConnectedElementPointFilter::filter_ro(), geos::operation::distance::ConnectedElementLocationFilter::filter_ro(), geos::geom::util::ComponentCoordinateExtracter::filter_rw(), geos::operation::distance::ConnectedElementLocationFilter::filter_rw(), GEOSHasZ_r(), and GEOSProject_r().
virtual int geos::geom::Geometry::getCoordinateDimension () const pure virtual
Returns the coordinate dimension of this Geometry (2=XY, 3=XYZ, 4=XYZM in future).
Implemented in geos::geom::GeometryCollection, geos::geom::LineString, geos::geom::Point, and geos::geom::Polygon.
Referenced by geos::io::WKTWriter::appendGeometryTaggedText(), GEOSGeom_getCoordinateDimension_r(), geos::operation::overlay::OverlayOp::labelIncompleteNode(), and geos::io::WKBWriter::write().
virtual CoordinateSequence* geos::geom::Geometry::getCoordinates () const pure virtual
Returns this Geometry vertices. Caller takes ownership of the returned object.
Implemented in geos::geom::GeometryCollection, geos::geom::LineString, geos::geom::Point, and geos::geom::Polygon.
Referenced by geos::operation::overlay::validate::OverlayResultValidator::addVertices(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::algorithm::distance::DiscreteFrechetDistance::compute(), geos::linearref::ExtractLineByLocation::computeLine(), geos::algorithm::MinimumDiameter::computeWidthConvex(), geos::geom::util::CoordinateOperation::edit(), and geos::triangulate::DelaunayTriangulationBuilder::extractUniqueCoordinates().
virtual Dimension::DimensionType geos::geom::Geometry::getDimension () const pure virtual
Returns the dimension of this Geometry (0=point, 1=line, 2=surface)
Implemented in geos::geom::GeometryCollection, geos::geom::LineString, geos::geom::Point, geos::geom::Polygon, geos::geom::MultiPolygon, geos::geom::MultiPoint, and geos::geom::MultiLineString.
Referenced by geos::operation::relate::RelateComputer::computeDisjointIM(), crosses(), equals(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), GEOSGeom_getDimensions_r(), getInteriorPoint(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::geom::prep::PreparedLineStringIntersects::intersects(), geos::geom::prep::PreparedPolygonIntersects::intersects(), geos::operation::relate::RelateComputer::labelIsolatedEdge(), overlaps(), geos::precision::GeometryPrecisionReducer::reducePointwise(), and touches().
Geometry * geos::geom::Geometry::getEnvelope () const virtual
Returns this Geometrys bounding box.
Definition at line 269 of file Geometry.cpp.
References getEnvelopeInternal(), getFactory(), and geos::geom::GeometryFactory::toGeometry().
Referenced by GEOSEnvelope_r().
 {
   return getFactory()->toGeometry(getEnvelopeInternal());
 }
const Envelope * geos::geom::Geometry::getEnvelopeInternal () const virtual
Returns the minimum and maximum x and y values in this Geometry, or a null Envelope if this Geometry is empty.
Definition at line 275 of file Geometry.cpp.
References computeEnvelopeInternal(), and envelope.
Referenced by geos::operation::valid::QuadtreeNestedRingTester::add(), geos::operation::valid::SweeplineNestedRingTester::buildIndex(), geos::operation::valid::IndexedNestedRingTester::buildIndex(), geos::operation::valid::QuadtreeNestedRingTester::buildQuadtree(), geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), geos::geomgraph::GeometryGraph::computeEdgeIntersections(), geos::geom::Polygon::computeEnvelopeInternal(), geos::operation::distance::DistanceOp::computeMinDistance(), geos::operation::overlay::OverlayOp::computeOverlay(), geos::operation::overlay::snap::GeometrySnapper::computeSizeBasedSnapTolerance(), geos::operation::predicate::RectangleContains::contains(), contains(), geos::geomgraph::EdgeRing::containsPoint(), geos::geom::prep::BasicPreparedGeometry::containsProperly(), covers(), crosses(), disjoint(), geos::geom::prep::BasicPreparedGeometry::envelopeCovers(), geos::geom::prep::BasicPreparedGeometry::envelopesIntersect(), equals(), geos::operation::geounion::CascadedUnion::extractByEnvelope(), geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope(), geos::operation::polygonize::EdgeRing::findEdgeRingContaining(), geos::operation::overlay::PolygonBuilder::findEdgeRingContaining(), GEOSGeom_getXMax_r(), GEOSGeom_getXMin_r(), GEOSGeom_getYMax_r(), GEOSGeom_getYMin_r(), GEOSSTRtree_insert_r(), GEOSSTRtree_nearest_generic_r(), GEOSSTRtree_query_r(), GEOSSTRtree_remove_r(), GEOSVoronoiDiagram_r(), getEnvelope(), geos::operation::predicate::SegmentIntersectionTester::hasIntersectionWithEnvelopeFilter(), geos::algorithm::InteriorPointArea::horizontalBisector(), intersection(), geos::operation::predicate::RectangleIntersects::intersects(), intersects(), geos::operation::buffer::OffsetCurveSetBuilder::isErodedCompletely(), geos::operation::valid::SweeplineNestedRingTester::isInside(), geos::operation::valid::QuadtreeNestedRingTester::isNonNested(), geos::operation::valid::IndexedNestedRingTester::isNonNested(), geos::operation::valid::SimpleNestedRingTester::isNonNested(), geos::geom::Polygon::isRectangle(), isWithinDistance(), overlaps(), geos::operation::overlay::OverlayOp::OverlayOp(), geos::operation::buffer::BufferOp::precisionScaleFactor(), symDifference(), touches(), geos::operation::geounion::CascadedUnion::Union(), geos::operation::geounion::CascadedPolygonUnion::Union(), Union(), geos::operation::geounion::CascadedUnion::unionOptimized(), geos::operation::geounion::CascadedPolygonUnion::unionOptimized(), geos::operation::predicate::EnvelopeIntersectsVisitor::visit(), geos::operation::predicate::ContainsPointVisitor::visit(), geos::operation::predicate::LineIntersectsVisitor::visit(), and geos::algorithm::InteriorPointArea::widestGeometry().
 {
   if (!envelope.get()) {
     envelope = computeEnvelopeInternal();
   }
   return envelope.get();
 }
const GeometryFactory* geos::geom::Geometry::getFactory () const inline
Gets the factory which contains the context in which this geometry was created.
Returns
the factory for this geometry
Definition at line 206 of file Geometry.h.
Referenced by geos::operation::linemerge::LineMerger::add(), geos::operation::polygonize::Polygonizer::add(), geos::operation::linemerge::LineSequencer::addLine(), geos::simplify::TaggedLineString::asLinearRing(), geos::simplify::TaggedLineString::asLineString(), geos::geom::BinaryOp(), geos::operation::buffer::BufferBuilder::buffer(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), geos::precision::MinimumClearance::compute(), geos::linearref::ExtractLineByLocation::computeLine(), geos::linearref::ExtractLineByLocation::computeLinear(), geos::geom::GeometryFactory::createPointFromInternalCoord(), difference(), geos::precision::PrecisionReducerCoordinateOperation::edit(), geos::geom::util::GeometryEditor::edit(), geos::geom::util::GeometryEditor::editPolygon(), geos::operation::geounion::UnaryUnionOp::extract(), geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), geos::precision::GeometryPrecisionReducer::fixPolygonalTopology(), GEOSDelaunayTriangulation_r(), GEOSVoronoiDiagram_r(), geos::geom::MultiLineString::getBoundary(), geos::geom::MultiPoint::getBoundary(), geos::geom::MultiPolygon::getBoundary(), geos::geom::Polygon::getBoundary(), geos::geom::Point::getBoundary(), geos::geom::LineString::getBoundary(), getCentroid(), geos::geom::Polygon::getCoordinates(), getEnvelope(), getInteriorPoint(), geos::precision::MinimumClearance::getLine(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::operation::overlay::validate::FuzzyPointLocator::getLocation(), geos::algorithm::MinimumDiameter::getMinimumRectangle(), geos::noding::GeometryNoder::getNoder(), geos::geom::LineString::getPointN(), geos::simplify::TaggedLineString::getResultCoordinates(), geos::algorithm::InteriorPointArea::InteriorPointArea(), intersection(), geos::operation::geounion::PointGeometryUnion::PointGeometryUnion(), geos::geom::Polygon::Polygon(), geos::geom::MultiLineString::reverse(), geos::geom::MultiPolygon::reverse(), geos::geom::LinearRing::reverse(), geos::operation::linemerge::LineSequencer::reverse(), geos::geom::Polygon::reverse(), geos::geom::GeometryCollection::reverse(), geos::geom::LineString::reverse(), geos::noding::GeometryNoder::toGeometry(), geos::geom::util::GeometryTransformer::transform(), geos::operation::geounion::CascadedPolygonUnion::Union(), and geos::geom::LineString::validateConstruction().
 { return _factory; }
virtual const Geometry* geos::geom::Geometry::getGeometryN (std::size_t) const inline virtual
Returns a pointer to the nth Geometry int this collection (or self if this is not a collection)
Reimplemented in geos::geom::GeometryCollection.
Definition at line 291 of file Geometry.h.
Referenced by geos::geom::util::ShortCircuitedGeometryVisitor::applyTo(), geos::linearref::LinearLocation::clamp(), geos::algorithm::distance::DistanceToPoint::computeDistance(), geos::operation::geounion::CascadedUnion::extractByEnvelope(), geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope(), geos::geom::util::GeometryCombiner::extractElements(), geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), geos::operation::sharedpaths::SharedPathsOp::findLinearIntersections(), GEOSGetGeometryN_r(), GEOSPolygonize_full_r(), geos::linearref::LinearLocation::getCoordinate(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::linearref::LinearLocation::getSegment(), geos::linearref::LinearLocation::getSegmentLength(), geos::linearref::LocationIndexOfLine::indicesOf(), geos::operation::predicate::RectangleContains::isContainedInBoundary(), geos::linearref::LinearLocation::isEndpoint(), geos::geom::prep::AbstractPreparedPolygonContains::isSingleShell(), geos::linearref::LinearLocation::isValid(), geos::linearref::LinearIterator::loadCurrentLine(), geos::linearref::LengthLocationMap::resolveHigher(), geos::linearref::LinearLocation::setToEnd(), and geos::operation::geounion::PointGeometryUnion::Union().
 { return this; }
virtual std::string geos::geom::Geometry::getGeometryType () const pure virtual
Return a string representation of this Geometry type.
Implemented in geos::geom::LineString, geos::geom::Polygon, geos::geom::GeometryCollection, geos::geom::Point, geos::geom::LinearRing, geos::geom::MultiPolygon, geos::geom::MultiPoint, and geos::geom::MultiLineString.
Referenced by GEOSGeomType_r().
virtual GeometryTypeId geos::geom::Geometry::getGeometryTypeId () const pure virtual
Return an integer representation of this Geometry type.
Implemented in geos::geom::LineString, geos::geom::Polygon, geos::geom::GeometryCollection, geos::geom::Point, geos::geom::LinearRing, geos::geom::MultiPolygon, geos::geom::MultiPoint, and geos::geom::MultiLineString.
Referenced by geos::geom::prep::PreparedPolygonContainsProperly::containsProperly(), geos::geom::prep::PreparedGeometryFactory::create(), geos::geom::prep::AbstractPreparedPolygonContains::eval(), geos::geom::util::ComponentCoordinateExtracter::filter_ro(), geos::geom::util::ComponentCoordinateExtracter::filter_rw(), GEOSGeomTypeId_r(), geos::operation::overlay::OverlayOp::getAverageZ(), and geos::geom::prep::AbstractPreparedPolygonContains::isProperIntersectionImpliesNotContainedSituation().
Point * geos::geom::Geometry::getInteriorPoint () const virtual
Computes an interior point of this Geometry.
An interior point is guaranteed to lie in the interior of the Geometry, if it possible to calculate such a point exactly. Otherwise, the point may lie on the boundary of the geometry.
Returns
a Point which is in the interior of this Geometry, or null if the geometry doesn't have an interior (empty)
Definition at line 220 of file Geometry.cpp.
References geos::geom::GeometryFactory::createPointFromInternalCoord(), getDimension(), getFactory(), geos::algorithm::InteriorPointLine::getInteriorPoint(), geos::algorithm::InteriorPointPoint::getInteriorPoint(), and geos::algorithm::InteriorPointArea::getInteriorPoint().
Referenced by GEOSPointOnSurface_r().
 {
   Coordinate interiorPt;
   int dim=getDimension();
   if (dim==0) {
     InteriorPointPoint intPt(this);
     if ( ! intPt.getInteriorPoint(interiorPt) ) return nullptr;
   } else if (dim==1) {
     InteriorPointLine intPt(this);
     if ( ! intPt.getInteriorPoint(interiorPt) ) return nullptr;
   } else {
     InteriorPointArea intPt(this);
     if ( ! intPt.getInteriorPoint(interiorPt) ) return nullptr;
   }
   Point *p=getFactory()->createPointFromInternalCoord(&interiorPt, this);
   return p;
 }
double geos::geom::Geometry::getLength () const virtual
Returns the length of this Geometry.
Returns the length of this Geometry. Linear geometries return their length. Areal geometries return their perimeter. They override this function to compute the area. Others return 0.0
Returns
the length of the Geometry
Reimplemented in geos::geom::LineString, geos::geom::GeometryCollection, and geos::geom::Polygon.
Definition at line 806 of file Geometry.cpp.
Referenced by GEOSLength_r(), geos::linearref::LengthIndexedLine::getEndIndex(), geos::linearref::LengthLocationMap::getLocation(), geos::linearref::LengthIndexOfPoint::indexOfAfter(), geos::linearref::LocationIndexOfLine::indicesOf(), geos::linearref::LengthIndexedLine::positiveIndex(), and geos::linearref::LengthLocationMap::resolveHigher().
 {
   return 0.0;
 }
virtual std::size_t geos::geom::Geometry::getNumGeometries () const inline virtual
Returns the number of geometries in this collection (or 1 if this is not a collection)
Reimplemented in geos::geom::GeometryCollection.
Definition at line 287 of file Geometry.h.
Referenced by geos::geom::util::ShortCircuitedGeometryVisitor::applyTo(), geos::linearref::LinearLocation::clamp(), geos::operation::geounion::CascadedUnion::extractByEnvelope(), geos::operation::geounion::CascadedPolygonUnion::extractByEnvelope(), geos::geom::util::GeometryCombiner::extractElements(), geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), GEOSGetNumGeometries_r(), GEOSPolygonize_full_r(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::linearref::LocationIndexOfLine::indicesOf(), geos::operation::predicate::RectangleContains::isContainedInBoundary(), geos::geom::prep::AbstractPreparedPolygonContains::isSingleShell(), geos::linearref::LinearLocation::isValid(), geos::linearref::LengthLocationMap::resolveHigher(), geos::linearref::LinearLocation::setToEnd(), symDifference(), geos::operation::geounion::PointGeometryUnion::Union(), Union(), geos::operation::geounion::CascadedUnion::unionOptimized(), and geos::operation::geounion::CascadedPolygonUnion::unionOptimized().
 { return 1; }
virtual std::size_t geos::geom::Geometry::getNumPoints () const pure virtual
Returns the count of this Geometrys vertices.
Implemented in geos::geom::GeometryCollection, geos::geom::LineString, geos::geom::Point, and geos::geom::Polygon.
Referenced by geos::linearref::LinearLocation::clamp(), geos::operation::overlay::snap::GeometrySnapper::extractTargetCoordinates(), and GEOSGetNumCoordinates_r().
const PrecisionModel * geos::geom::Geometry::getPrecisionModel () const
Get the PrecisionModel used to create this Geometry.
Definition at line 871 of file Geometry.cpp.
References _factory, and geos::geom::GeometryFactory::getPrecisionModel().
Referenced by geos::operation::buffer::BufferBuilder::buffer(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::operation::overlay::snap::GeometrySnapper::computeOverlaySnapTolerance(), geos::geom::GeometryFactory::createPointFromInternalCoord(), geos::operation::GeometryGraphOperation::GeometryGraphOperation(), getCentroid(), and geos::io::WKTWriter::writeFormatted().
 {
   return _factory->getPrecisionModel();
 }
virtual int geos::geom::Geometry::getSRID () const inline virtual
Definition at line 246 of file Geometry.h.
Referenced by GEOSGetSRID_r(), geos::io::WKBWriter::writeGeometryCollection(), geos::io::WKBWriter::writeLineString(), geos::io::WKBWriter::writePoint(), and geos::io::WKBWriter::writePolygon().
 { return SRID; }
void* geos::geom::Geometry::getUserData () const inline
Gets the user data object for this geometry, if any.
Returns
the user data object, or null if none set
Definition at line 229 of file Geometry.h.
Referenced by GEOSGeom_getUserData_r().
 { return _userData; }
bool geos::geom::Geometry::hasNonEmptyElements (const std::vector< Geometry * > * geometries) static protected
Returns true if the array contains any non-empty Geometrys.
Definition at line 140 of file Geometry.cpp.
Referenced by geos::geom::Polygon::Polygon().
 {
   for (size_t i=0; i<geometries->size(); i++) {
     if (!(*geometries)[i]->isEmpty()) {
       return true;
     }
   }
   return false;
 }
bool geos::geom::Geometry::hasNullElements (const CoordinateSequence * list) static protected
Returns true if the CoordinateSequence contains any null elements.
Definition at line 151 of file Geometry.cpp.
References geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), and geos::geom::Coordinate::isNull().
Referenced by geos::geom::GeometryCollection::GeometryCollection(), and geos::geom::Polygon::Polygon().
 {
   size_t npts=list->getSize();
   for (size_t i=0; i<npts; ++i) {
     if (list->getAt(i).isNull()) {
       return true;
     }
   }
   return false;
 }
bool geos::geom::Geometry::hasNullElements (const std::vector< Geometry * > * lrs) static protected
Returns true if the vector contains any null elements.
Definition at line 163 of file Geometry.cpp.
 {
   size_t n=lrs->size();
   for (size_t i=0; i<n; ++i) {
     if ((*lrs)[i]==nullptr) {
       return true;
     }
   }
   return false;
 }
Geometry * geos::geom::Geometry::intersection (const Geometry * other) const virtual
Returns a Geometry representing the points shared by this Geometry and other.
Exceptions
util::TopologyException if a robustness error occurs
util::IllegalArgumentException if either input is a non-empty GeometryCollection
TODO: MD - add optimization for P-A case using Point-In-Polygon
Definition at line 505 of file Geometry.cpp.
References geos::geom::BinaryOp(), geos::geom::GeometryFactory::createGeometryCollection(), getEnvelopeInternal(), getFactory(), geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), isEmpty(), and isRectangle().
Referenced by GEOSIntersection_r(), and geos::precision::EnhancedPrecisionOp::intersection().
 {
   // special case: if one input is empty ==> empty
   if (isEmpty() || other->isEmpty() )
   {
     return getFactory()->createGeometryCollection();
   }
 #ifdef USE_RECTANGLE_INTERSECTION
   // optimization for rectangle arguments
   using operation::intersection::Rectangle;
   using operation::intersection::RectangleIntersection;
   if ( isRectangle() ) {
     const Envelope* env = getEnvelopeInternal();
     Rectangle rect(env->getMinX(), env->getMinY(),
                    env->getMaxX(), env->getMaxY());
     return RectangleIntersection::clip(*other, rect).release();
   }
   if (other->isRectangle()) {
     const Envelope* env = other->getEnvelopeInternal();
     Rectangle rect(env->getMinX(), env->getMinY(),
                    env->getMaxX(), env->getMaxY());
     return RectangleIntersection::clip(*this, rect).release();
   }
 #endif
   return BinaryOp(this, other, overlayOp(OverlayOp::opINTERSECTION)).release();
 }
bool geos::geom::Geometry::intersects (const Geometry * g) const virtual
Returns true if disjoint returns false.
TODO: (MD) Add optimizations:
for P-A case: If P is in env(A), test for point-in-poly
for A-A case: If env(A1).overlaps(env(A2)) test for overlaps via point-in-poly first (both ways) Possibly optimize selection of point to test by finding point of A1 closest to centre of env(A2). (Is there a test where we shouldn't bother - e.g. if env A is much smaller than env B, maybe there's no point in testing pt(B) in env(A)?
Definition at line 310 of file Geometry.cpp.
References getEnvelopeInternal(), isRectangle(), and relate().
Referenced by crosses(), disjoint(), GEOSIntersects_r(), geos::geom::prep::BasicPreparedGeometry::intersects(), overlaps(), and touches().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return false;
 #endif
   // optimization for rectangle arguments
   if (isRectangle()) {
     const Polygon* p = dynamic_cast<const Polygon*>(this);
     return predicate::RectangleIntersects::intersects(*p, *g);
   }
   if (g->isRectangle()) {
     const Polygon* p = dynamic_cast<const Polygon*>(g);
     return predicate::RectangleIntersects::intersects(*p, *this);
   }
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isIntersects();
   return res;
 }
virtual bool geos::geom::Geometry::isEmpty () const pure virtual
Returns whether or not the set of points in this Geometry is empty.
Implemented in geos::geom::LineString, geos::geom::Polygon, geos::geom::GeometryCollection, and geos::geom::Point.
Referenced by geos::algorithm::CentroidArea::add(), geos::operation::buffer::OffsetCurveSetBuilder::add(), geos::algorithm::Centroid::add(), geos::geomgraph::GeometryGraph::add(), geos::algorithm::InteriorPointArea::addPolygon(), geos::operation::valid::IsValidOp::checkValid(), compareTo(), geos::precision::MinimumClearance::compute(), geos::operation::relate::RelateComputer::computeDisjointIM(), difference(), geos::geom::util::GeometryEditor::editGeometryCollection(), equals(), geos::geom::Point::equalsExact(), geos::geom::util::GeometryCombiner::extractElements(), GEOSGeom_getXMax_r(), GEOSGeom_getXMin_r(), GEOSGeom_getYMax_r(), GEOSGeom_getYMin_r(), GEOSHasZ_r(), GEOSisEmpty_r(), GEOSNearestPoints_r(), getCentroid(), geos::simplify::TopologyPreservingSimplifier::getResultGeometry(), geos::operation::valid::RepeatedPointTester::hasRepeatedPoint(), intersection(), geos::operation::IsSimpleOp::isSimpleLinearGeometry(), geos::algorithm::locate::SimplePointInAreaLocator::locate(), geos::algorithm::PointLocator::locate(), symDifference(), and Union().
bool geos::geom::Geometry::isEquivalentClass (const Geometry * other) const protected virtual
Returns whether the two Geometrys are equal, from the point of view of the equalsExact method.
Definition at line 673 of file Geometry.cpp.
Referenced by geos::geom::MultiLineString::equalsExact(), geos::geom::MultiPoint::equalsExact(), geos::geom::MultiPolygon::equalsExact(), geos::geom::GeometryCollection::equalsExact(), geos::geom::Point::equalsExact(), and geos::geom::LineString::equalsExact().
 {
   if (typeid(*this)==typeid(*other))
     return true;
   else
     return false;
 }
virtual bool geos::geom::Geometry::isRectangle () const inline virtual
Polygon overrides to check for actual rectangle.
Reimplemented in geos::geom::Polygon.
Definition at line 308 of file Geometry.h.
Referenced by contains(), covers(), intersection(), intersects(), and geos::geom::prep::PreparedPolygon::PreparedPolygon().
 { return false; }
bool geos::geom::Geometry::isSimple () const virtual
Returns false if the Geometry not simple.
Reimplemented in geos::geom::Polygon, geos::geom::LinearRing, geos::geom::Point, and geos::geom::MultiPolygon.
Definition at line 862 of file Geometry.cpp.
References checkNotGeometryCollection(), and geos::operation::IsSimpleOp::isSimple().
Referenced by GEOSisSimple_r(), and geos::geom::LineString::isRing().
 {
   checkNotGeometryCollection(this);
   operation::IsSimpleOp op(*this);
   return op.isSimple();
 }
bool geos::geom::Geometry::isValid () const virtual
Tests the validity of this Geometry.
Subclasses provide their own definition of "valid".
Returns
true if this Geometry is valid
See also
IsValidOp
Definition at line 263 of file Geometry.cpp.
References geos::operation::valid::IsValidOp::isValid().
Referenced by geos::precision::EnhancedPrecisionOp::buffer(), geos::precision::EnhancedPrecisionOp::difference(), geos::precision::EnhancedPrecisionOp::intersection(), geos::operation::polygonize::EdgeRing::isValid(), geos::precision::EnhancedPrecisionOp::symDifference(), and geos::precision::EnhancedPrecisionOp::Union().
 {
   return IsValidOp(this).isValid();
 }
bool geos::geom::Geometry::isWithinDistance (const Geometry * geom, double cDistance) const virtual
Tests whether the distance from this Geometry to another is less than or equal to a specified value.
Parameters
geom the Geometry to check the distance to
cDistance the distance value to compare
Returns
true if the geometries are less than distance apart.
Todo:
doesn't seem to need being virtual, make it concrete
Definition at line 176 of file Geometry.cpp.
References geos::geom::Envelope::distance(), distance(), and getEnvelopeInternal().
 {
   const Envelope *env0=getEnvelopeInternal();
   const Envelope *env1=geom->getEnvelopeInternal();
   double envDist=env0->distance(env1);
   //delete env0;
   //delete env1;
   if (envDist>cDistance)
   {
     return false;
   }
   // NOTE: this could be implemented more efficiently
   double geomDist=distance(geom);
   if (geomDist>cDistance)
   {
     return false;
   }
   return true;
 }
virtual void geos::geom::Geometry::normalize () pure virtual
Converts this Geometry to normal form (or canonical form).
Implemented in geos::geom::LineString, geos::geom::GeometryCollection, geos::geom::Polygon, and geos::geom::Point.
Referenced by GEOSNormalize_r().
bool geos::geom::Geometry::overlaps (const Geometry * g) const virtual
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*T***T** (for two points or two surfaces) 1*T***T** (for two curves).
Definition at line 415 of file Geometry.cpp.
References getDimension(), getEnvelopeInternal(), intersects(), and relate().
Referenced by GEOSOverlaps_r(), and geos::geom::prep::BasicPreparedGeometry::overlaps().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return false;
 #endif
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isOverlaps(getDimension(), g->getDimension());
   return res;
 }
virtual bool geos::geom::Geometry::relate (const Geometry * g, const std::string & intersectionPattern) const virtual
Returns true if the elements in the DE-9IM intersection matrix for the two Geometrys match the elements in intersectionPattern.
IntersectionPattern elements may be: 0 1 2 T (= 0, 1 or 2) F (= -1) * (= -1, 0, 1 or 2).
For more information on the DE-9IM, see the OpenGIS Simple Features Specification.
Exceptions
util::IllegalArgumentException if either arg is a collection
Referenced by contains(), geos::geom::prep::BasicPreparedGeometry::containsProperly(), covers(), crosses(), disjoint(), equals(), GEOSRelate_r(), GEOSRelatePattern_r(), intersects(), overlaps(), and touches().
bool geos::geom::Geometry::relate (const Geometry & g, const std::string & intersectionPattern) const inline
Definition at line 430 of file Geometry.h.
   {
     return relate(&g, intersectionPattern);
   }
IntersectionMatrix * geos::geom::Geometry::relate (const Geometry * g) const virtual
Returns the DE-9IM intersection matrix for the two Geometrys.
Definition at line 453 of file Geometry.cpp.
 {
   return RelateOp::relate(this, other);
 }
IntersectionMatrix* geos::geom::Geometry::relate (const Geometry & g) const inline
Definition at line 437 of file Geometry.h.
{
     return relate(&g);
   }
virtual Geometry* geos::geom::Geometry::reverse () const pure virtual
Computes a new geometry which has all component coordinate sequences in reverse order (opposite orientation) to this one.
Returns
a reversed geometry
Implemented in geos::geom::LineString, geos::geom::GeometryCollection, geos::geom::Polygon, geos::geom::Point, geos::geom::LinearRing, geos::geom::MultiPolygon, geos::geom::MultiLineString, and geos::geom::MultiPoint.
Referenced by GEOSReverse_r().
virtual void geos::geom::Geometry::setSRID (int newSRID) inline virtual
Definition at line 252 of file Geometry.h.
Referenced by geos::geom::GeometryCollection::GeometryCollection(), GEOSSetSRID_r(), and geos::io::WKBReader::readGeometry().
 { SRID=newSRID; }
void geos::geom::Geometry::setUserData (void * newUserData) inline
A simple scheme for applications to add their own custom data to a Geometry. An example use might be to add an object representing a Coordinate Reference System.
Note that user data objects are not present in geometries created by construction methods.
Parameters
newUserData an object, the semantics for which are defined by the application using this Geometry
Definition at line 221 of file Geometry.h.
Referenced by geos::triangulate::VoronoiDiagramBuilder::clipGeometryCollection(), and GEOSGeom_setUserData_r().
 { _userData=newUserData; }
Geometry * geos::geom::Geometry::symDifference (const Geometry * other) const virtual
Returns a set combining the points in this Geometry not in other, and the points in other not in this Geometry.
Exceptions
util::TopologyException if a robustness error occurs
util::IllegalArgumentException if either input is a non-empty GeometryCollection
Definition at line 609 of file Geometry.cpp.
References _factory, geos::geom::BinaryOp(), geos::geom::GeometryFactory::buildGeometry(), clone(), getEnvelopeInternal(), geos::geom::GeometryCollection::getGeometryN(), getNumGeometries(), geos::geom::Envelope::intersects(), and isEmpty().
Referenced by GEOSSymDifference_r(), and geos::precision::EnhancedPrecisionOp::symDifference().
 {
   // special case: if either input is empty ==> other input
   if ( isEmpty() ) return other->clone();
   if ( other->isEmpty() ) return clone();
   // if envelopes are disjoint return a MULTI geom or
   // a geometrycollection
   if ( ! getEnvelopeInternal()->intersects(other->getEnvelopeInternal()) )
   {
     const GeometryCollection *coll;
     size_t ngeomsThis = getNumGeometries();
     size_t ngeomsOther = other->getNumGeometries();
     // Allocated for ownership transfer
     vector<Geometry *> *v = new vector<Geometry *>();
     v->reserve(ngeomsThis+ngeomsOther);
     if ( nullptr != (coll = dynamic_cast<const GeometryCollection *>(this)) )
     {
       for (size_t i=0; i<ngeomsThis; ++i)
         v->push_back(coll->getGeometryN(i)->clone());
     } else {
       v->push_back(this->clone());
     }
     if ( nullptr != (coll = dynamic_cast<const GeometryCollection *>(other)) )
     {
       for (size_t i=0; i<ngeomsOther; ++i)
         v->push_back(coll->getGeometryN(i)->clone());
     } else {
       v->push_back(other->clone());
     }
     return _factory->buildGeometry(v);
   }
   return BinaryOp(this, other, overlayOp(OverlayOp::opSYMDIFFERENCE)).release();
 }
string geos::geom::Geometry::toString (void) const virtual
Returns the Well-known Text representation of this Geometry.
Definition at line 460 of file Geometry.cpp.
References toText().
Referenced by geos::operation::linemerge::LineMergeGraph::addEdge(), geos::operation::buffer::OffsetCurveSetBuilder::addLineString(), geos::geom::BinaryOp(), geos::geom::check_valid(), geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), geos::operation::distance::DistanceOp::computeMinDistancePoints(), GEOSClipByRect_r(), GEOSGeomToWKT_r(), GEOSNode_r(), GEOSUnaryUnion_r(), GEOSUnion_r(), and geos::geom::prep::BasicPreparedGeometry::toString().
 {
   return toText();
 }
string geos::geom::Geometry::toText () const virtual
Definition at line 474 of file Geometry.cpp.
References geos::io::WKTWriter::write().
Referenced by toString().
 {
   io::WKTWriter writer;
   return writer.write(this);
 }
bool geos::geom::Geometry::touches (const Geometry * other) const virtual
Returns true if the DE-9IM intersection matrix for the two Geometrys is FT*******, F**T***** or F***T****.
Definition at line 297 of file Geometry.cpp.
References getDimension(), getEnvelopeInternal(), intersects(), and relate().
Referenced by GEOSTouches_r(), and geos::geom::prep::BasicPreparedGeometry::touches().
 {
 #ifdef SHORTCIRCUIT_PREDICATES
   // short-circuit test
   if (! getEnvelopeInternal()->intersects(g->getEnvelopeInternal()))
     return false;
 #endif
   unique_ptr<IntersectionMatrix> im ( relate(g) );
   bool res=im->isTouches(getDimension(), g->getDimension());
   return res;
 }
Geometry * geos::geom::Geometry::Union (const Geometry * other) const
Returns a Geometry representing all the points in this Geometry and other.
Exceptions
util::TopologyException if a robustness error occurs
util::IllegalArgumentException if either input is a non-empty GeometryCollection
Definition at line 539 of file Geometry.cpp.
References _factory, geos::geom::BinaryOp(), geos::geom::GeometryFactory::buildGeometry(), clone(), getEnvelopeInternal(), geos::geom::GeometryCollection::getGeometryN(), getNumGeometries(), geos::geom::Envelope::intersects(), and isEmpty().
Referenced by GEOSUnaryUnion_r(), GEOSUnion_r(), geos::precision::EnhancedPrecisionOp::Union(), geos::operation::geounion::CascadedUnion::unionActual(), and geos::operation::geounion::CascadedPolygonUnion::unionActual().
 {
   // special case: if one input is empty ==> other input
   if ( isEmpty() ) return other->clone();
   if ( other->isEmpty() ) return clone();
   Geometry *out = nullptr;
 #ifdef SHORTCIRCUIT_PREDICATES
   // if envelopes are disjoint return a MULTI geom or
   // a geometrycollection
   if ( ! getEnvelopeInternal()->intersects(other->getEnvelopeInternal()) )
   {
 //cerr<<"SHORTCIRCUITED-UNION engaged"<<endl;
     const GeometryCollection *coll;
     size_t ngeomsThis = getNumGeometries();
     size_t ngeomsOther = other->getNumGeometries();
     // Allocated for ownership transfer
     vector<Geometry *> *v = new vector<Geometry *>();
     v->reserve(ngeomsThis+ngeomsOther);
     if ( nullptr != (coll = dynamic_cast<const GeometryCollection *>(this)) )
     {
       for (size_t i=0; i<ngeomsThis; ++i)
         v->push_back(coll->getGeometryN(i)->clone());
     } else {
       v->push_back(this->clone());
     }
     if ( nullptr != (coll = dynamic_cast<const GeometryCollection *>(other)) )
     {
       for (size_t i=0; i<ngeomsOther; ++i)
         v->push_back(coll->getGeometryN(i)->clone());
     } else {
       v->push_back(other->clone());
     }
     out = _factory->buildGeometry(v);
     return out;
   }
 #endif
   return BinaryOp(this, other, overlayOp(OverlayOp::opUNION)).release();
 }
Geometry::Ptr geos::geom::Geometry::Union () const
Computes the union of all the elements of this geometry. Heterogeneous GeometryCollections are fully supported.
The result obeys the following contract:
Unioning a set of LineStrings has the effect of fully noding and dissolving the linework.
Unioning a set of Polygons will always return a Polygonal geometry (unlike {link #union(Geometry)}, which may return geometrys of lower dimension if a topology collapse occurred.
Returns
the union geometry
See also
UnaryUnionOp
Definition at line 591 of file Geometry.cpp.
 {
   using geos::operation::geounion::UnaryUnionOp;
   return UnaryUnionOp::Union(*this);
 }
bool geos::geom::Geometry::within (const Geometry * g) const virtual
Returns true if the DE-9IM intersection matrix for the two Geometrys is T*F**F***.
Definition at line 385 of file Geometry.cpp.
References contains().
Referenced by GEOSWithin_r(), and geos::geom::prep::BasicPreparedGeometry::within().
 {
   return g->contains(this);
 }
Friends And Related Function Documentation
friend class GeometryFactory friend
Definition at line 181 of file Geometry.h.
Member Data Documentation
const GeometryFactory* geos::geom::Geometry::_factory private
The GeometryFactory used to create this Geometry.
Externally owned
Definition at line 865 of file Geometry.h.
Referenced by Geometry(), getPrecisionModel(), symDifference(), Union(), and ~Geometry().
void* geos::geom::Geometry::_userData private
Definition at line 867 of file Geometry.h.
std::unique_ptr<Envelope> geos::geom::Geometry::envelope mutable protected
The bounding box of this Geometry.
Definition at line 786 of file Geometry.h.
Referenced by geos::geom::GeometryCollection::computeEnvelopeInternal(), Geometry(), geometryChangedAction(), and getEnvelopeInternal().
Geometry::GeometryChangedFilter geos::geom::Geometry::geometryChangedFilter static private
Definition at line 859 of file Geometry.h.
Referenced by geometryChanged().
int geos::geom::Geometry::SRID protected
Definition at line 825 of file Geometry.h.
Referenced by Geometry().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/geom/Geometry.h
/home/vicky/potree/geos/vicky/src/geom/Geometry.cpp