GEOS: geos::geom::util::GeometryEditorOperation Class Reference
geos::geom::util::GeometryEditorOperation Class Reference abstract
#include <GeometryEditorOperation.h>
Public Member Functions
virtual Geometry * edit (const Geometry *geometry, const GeometryFactory *factory)=0
virtual ~GeometryEditorOperation ()
Detailed Description
A interface which specifies an edit operation for Geometries.
Definition at line 38 of file GeometryEditorOperation.h.
Constructor & Destructor Documentation
virtual geos::geom::util::GeometryEditorOperation::~GeometryEditorOperation () inline virtual
Definition at line 56 of file GeometryEditorOperation.h.
 {}
Member Function Documentation
virtual Geometry* geos::geom::util::GeometryEditorOperation::edit (const Geometry * geometry, const GeometryFactory * factory) pure virtual
Edits a Geometry by returning a new Geometry with a modification. The returned Geometry might be the same as the Geometry passed in.
Parameters
geometry the Geometry to modify
factory the factory with which to construct the modified Geometry (may be different to the factory of the input geometry)
Returns
a new Geometry which is a modification of the input Geometry
Implemented in geos::geom::util::CoordinateOperation.
Referenced by geos::geom::util::GeometryEditor::edit(), geos::geom::util::GeometryEditor::editGeometryCollection(), and geos::geom::util::GeometryEditor::editPolygon().
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/geom/util/GeometryEditorOperation.h