GEOS: geos::algorithm::Centroid Class Reference
geos::algorithm::Centroid Class Reference
#include <Centroid.h>
Public Member Functions
Centroid (const geom::Geometry &geom)
bool getCentroid (geom::Coordinate &cent) const
Static Public Member Functions
static bool getCentroid (const geom::Geometry &geom, geom::Coordinate &cent)
Private Member Functions
void add (const geom::Geometry &geom)
void setBasePoint (const geom::Coordinate &basePt)
void add (const geom::Polygon &poly)
void addShell (const geom::CoordinateSequence &pts)
void addHole (const geom::CoordinateSequence &pts)
void addTriangle (const geom::Coordinate &p0, const geom::Coordinate &p1, const geom::Coordinate &p2, bool isPositiveArea)
void addLineSegments (const geom::CoordinateSequence &pts)
void addPoint (const geom::Coordinate &pt)
Static Private Member Functions
static void centroid3 (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &p3, geom::Coordinate &c)
static double area2 (const geom::Coordinate &p1, const geom::Coordinate &p2, const geom::Coordinate &p3)
Private Attributes
std::unique_ptr< geom::Coordinate > areaBasePt
geom::Coordinate triangleCent3
geom::Coordinate cg3
geom::Coordinate lineCentSum
geom::Coordinate ptCentSum
double areasum2
double totalLength
int ptCount
Detailed Description
Computes the centroid of a Geometry of any dimension. If the geometry is nomimally of higher dimension, but contains only components having a lower effective dimension (i.e. zero length or area), the centroid will be computed appropriately.
Algorithm
Dimension = 2 - Based on the usual algorithm for calculating the centroid as a weighted sum of the centroids of a decomposition of the area into (possibly overlapping) triangles. The algorithm has been extended to handle holes and multi-polygons. See http://www.faqs.org/faqs/graphics/algorithms-faq/ for further details of the basic approach.
Dimension = 1 - Computes the average of the midpoints of all line segments weighted by the segment length.
Dimension = 0 - Compute the average coordinate over all points.
If the input geometries are empty, a null Coordinate is returned.
Definition at line 61 of file Centroid.h.
Constructor & Destructor Documentation
geos::algorithm::Centroid::Centroid (const geom::Geometry & geom) inline
Creates a new instance for computing the centroid of a geometry
Definition at line 79 of file Centroid.h.
     :
     areasum2(0.0),
     totalLength(0.0),
     ptCount(0)
   {
     add(geom);
   }
Member Function Documentation
void geos::algorithm::Centroid::add (const geom::Geometry & geom) private
Adds a Geometry to the centroid total.
Parameters
geom the geometry to add
Definition at line 69 of file Centroid.cpp.
References geos::geom::Geometry::isEmpty().
 {
   if (geom.isEmpty()) return;
   if (const Point* pt = dynamic_cast<const Point*>(&geom)) {
     addPoint(*pt->getCoordinate());
   }
   else if (const LineString* ls = dynamic_cast<const LineString*>(&geom)) {
     addLineSegments(*ls->getCoordinatesRO());
   }
   else if (const Polygon* p = dynamic_cast<const Polygon*>(&geom)) {
     add(*p);
   }
   else if (const GeometryCollection* g = dynamic_cast<const GeometryCollection*>(&geom)) {
     for (size_t i = 0; i < g->getNumGeometries(); i++) {
       add(*g->getGeometryN(i));
     }
   }
 }
void geos::algorithm::Centroid::add (const geom::Polygon & poly) private
Definition at line 99 of file Centroid.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), and geos::geom::Polygon::getNumInteriorRing().
 {
   addShell(*poly.getExteriorRing()->getCoordinatesRO());
   for (size_t i = 0; i < poly.getNumInteriorRing(); i++) {
     addHole(*poly.getInteriorRingN(i)->getCoordinatesRO());
   }
 }
void geos::algorithm::Centroid::addHole (const geom::CoordinateSequence & pts) private
Definition at line 123 of file Centroid.cpp.
References geos::geom::CoordinateSequence::size().
 {
   bool isPositiveArea = CGAlgorithms::isCCW(&pts);
   for (size_t i = 0, e = pts.size() - 1; i < e; ++i) {
     addTriangle(*areaBasePt, pts[i], pts[i+1], isPositiveArea);
   }
   addLineSegments(pts);
 }
void geos::algorithm::Centroid::addLineSegments (const geom::CoordinateSequence & pts) private
Adds the line segments defined by an array of coordinates to the linear centroid accumulators.
Parameters
pts an array of Coordinates
Definition at line 164 of file Centroid.cpp.
References geos::geom::CoordinateSequence::size().
 {
   size_t npts = pts.size();
   double lineLen = 0.0;
   for (size_t i = 0; i < npts - 1; i++) {
     double segmentLen = pts[i].distance(pts[i + 1]);
     if (segmentLen == 0.0)
       continue;
     lineLen += segmentLen;
     double midx = (pts[i].x + pts[i + 1].x) / 2;
     lineCentSum.x += segmentLen * midx;
     double midy = (pts[i].y + pts[i + 1].y) / 2;
     lineCentSum.y += segmentLen * midy;
   }
   totalLength += lineLen;
   if (lineLen == 0.0 && npts > 0)
     addPoint(pts[0]);
 }
void geos::algorithm::Centroid::addPoint (const geom::Coordinate & pt) private
Adds a point to the point centroid accumulator.
Parameters
pt a Coordinate
Definition at line 187 of file Centroid.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   ptCount += 1;
   ptCentSum.x += pt.x;
   ptCentSum.y += pt.y;
 }
void geos::algorithm::Centroid::addShell (const geom::CoordinateSequence & pts) private
Definition at line 109 of file Centroid.cpp.
References geos::geom::CoordinateSequence::size().
 {
   size_t len = pts.size();
   if (len > 0)
     setBasePoint(pts[0]);
   bool isPositiveArea = ! CGAlgorithms::isCCW(&pts);
   for (size_t i = 0; i < len - 1; ++i) {
     addTriangle(*areaBasePt, pts[i], pts[i+1], isPositiveArea);
   }
   addLineSegments(pts);
 }
void geos::algorithm::Centroid::addTriangle (const geom::Coordinate & p0, const geom::Coordinate & p1, const geom::Coordinate & p2, bool isPositiveArea) private
Definition at line 134 of file Centroid.cpp.
 {
   double sign = (isPositiveArea) ? 1.0 : -1.0;
   centroid3( p0, p1, p2, triangleCent3 );
   double a2 = area2( p0, p1, p2 );
   cg3.x += sign * a2 * triangleCent3.x;
   cg3.y += sign * a2 * triangleCent3.y;
   areasum2 += sign * a2;
 }
double geos::algorithm::Centroid::area2 (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & p3) static private
Returns twice the signed area of the triangle p1-p2-p3. The area is positive if the triangle is oriented CCW, and negative if CW.
Definition at line 155 of file Centroid.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   return
     (p2.x - p1.x) * (p3.y - p1.y) -
     (p3.x - p1.x) * (p2.y - p1.y);
 }
void geos::algorithm::Centroid::centroid3 (const geom::Coordinate & p1, const geom::Coordinate & p2, const geom::Coordinate & p3, geom::Coordinate & c) static private
Computes three times the centroid of the triangle p1-p2-p3. The factor of 3 is left in to permit division to be avoided until later.
Definition at line 146 of file Centroid.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   c.x = p1.x + p2.x + p3.x;
   c.y = p1.y + p2.y + p3.y;
   return;
 }
bool geos::algorithm::Centroid::getCentroid (const geom::Geometry & geom, geom::Coordinate & cent) static
Computes the centroid point of a geometry.
Parameters
geom the geometry to use
cent will be set to the centroid point, if any
Returns
true if a centroid could be computed, false otherwise (empty geom)
Definition at line 38 of file Centroid.cpp.
References getCentroid().
Referenced by getCentroid().
 {
   Centroid cent(geom);
   return cent.getCentroid(pt);
 }
bool geos::algorithm::Centroid::getCentroid (geom::Coordinate & cent) const
Gets the computed centroid.
Parameters
cent will be set to the centroid point, if any
Returns
true if a centroid could be computed, false otherwise (empty geom)
Definition at line 46 of file Centroid.cpp.
References geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   if (std::abs(areasum2) > 0.0) {
     cent.x = cg3.x / 3 / areasum2;
     cent.y = cg3.y / 3 / areasum2;
   }
   else if (totalLength > 0.0) {
     // if polygon was degenerate, compute linear centroid instead
     cent.x = lineCentSum.x / totalLength;
     cent.y = lineCentSum.y / totalLength;
   }
   else if (ptCount > 0){
     cent.x = ptCentSum.x / ptCount;
     cent.y = ptCentSum.y / ptCount;
   }
   else {
     return false;
   }
   return true;
 }
void geos::algorithm::Centroid::setBasePoint (const geom::Coordinate & basePt) private
Definition at line 91 of file Centroid.cpp.
 {
   if ( ! areaBasePt.get() )
       areaBasePt.reset( new Coordinate(basePt) );
 }
Member Data Documentation
std::unique_ptr<geom::Coordinate> geos::algorithm::Centroid::areaBasePt private
Definition at line 100 of file Centroid.h.
double geos::algorithm::Centroid::areasum2 private
Definition at line 105 of file Centroid.h.
geom::Coordinate geos::algorithm::Centroid::cg3 private
Definition at line 102 of file Centroid.h.
geom::Coordinate geos::algorithm::Centroid::lineCentSum private
Definition at line 103 of file Centroid.h.
geom::Coordinate geos::algorithm::Centroid::ptCentSum private
Definition at line 104 of file Centroid.h.
int geos::algorithm::Centroid::ptCount private
Definition at line 107 of file Centroid.h.
double geos::algorithm::Centroid::totalLength private
Definition at line 106 of file Centroid.h.
geom::Coordinate geos::algorithm::Centroid::triangleCent3 private
Definition at line 101 of file Centroid.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/Centroid.h
/home/vicky/potree/geos/vicky/src/algorithm/Centroid.cpp