GEOS: geos::operation::intersection::Rectangle Class Reference
geos::operation::intersection::Rectangle Class Reference
Clipping rectangle.
#include <Rectangle.h>
Public Types
enum Position {
Inside = 1, Outside = 2, Left = 4, Top = 8,
Right = 16, Bottom = 32, TopLeft = Top|Left, TopRight = Top|Right,
BottomLeft = Bottom|Left, BottomRight = Bottom|Right
}
Position with respect to a clipping rectangle.
Public Member Functions
Rectangle (double x1, double y1, double x2, double y2)
Construct a clipping rectangle.
double xmin () const
double ymin () const
double xmax () const
double ymax () const
geom::Polygon * toPolygon (const geom::GeometryFactory &f) const
geom::LinearRing * toLinearRing (const geom::GeometryFactory &f) const
Position position (double x, double y) const
Establish position of coordinate with respect to a Rectangle.
Static Public Member Functions
static bool onEdge (Position pos)
Test if the given position is on a edge.
static bool onSameEdge (Position pos1, Position pos2)
Test if the given positions are on the same Rectangle edge.
static Position nextEdge (Position pos)
Next edge in clock-wise direction.
Private Member Functions
Rectangle ()
Private Attributes
double xMin
double yMin
double xMax
double yMax
Detailed Description
Clipping rectangle.
A clipping rectangle defines the boundaries of the rectangle by defining the limiting x- and y-coordinates. The clipping rectangle must be non-empty. In addition, methods are provided for specifying the location of a given coordinate with respect to the clipping rectangle similarly to the Cohen-Sutherland clipping algorithm.
Definition at line 51 of file Rectangle.h.
Member Enumeration Documentation
enum geos::operation::intersection::Rectangle::Position
Position with respect to a clipping rectangle.
Enumerator
Inside
Outside
Left
Top
Right
Bottom
TopLeft
TopRight
BottomLeft
BottomRight
Definition at line 105 of file Rectangle.h.
   {
   Inside    = 1,
   Outside   = 2,
   Left        = 4,
   Top         = 8,
   Right       = 16,
   Bottom      = 32,
   TopLeft     = Top|Left,                 // 12
   TopRight    = Top|Right,                // 24
   BottomLeft  = Bottom|Left,              // 36
   BottomRight = Bottom|Right              // 48
   };
Constructor & Destructor Documentation
geos::operation::intersection::Rectangle::Rectangle (double x1, double y1, double x2, double y2)
Construct a clipping rectangle.
Parameters
x1 x-coordinate of the left edge
y1 y-coordinate of the bottom edge
x2 x-coordinate of the right edge
y2 y-coordinate of the right edge
Exceptions
IllegalArgumentException if the rectangle is empty
Definition at line 31 of file Rectangle.cpp.
References xMax, xMin, yMax, and yMin.
   : xMin(x1)
   , yMin(y1)
   , xMax(x2)
   , yMax(y2)
   {
   if(xMin >= xMax || yMin >= yMax)
     {
     throw util::IllegalArgumentException("Clipping rectangle must be non-empty");
     }
   }
geos::operation::intersection::Rectangle::Rectangle () private
Member Function Documentation
static Position geos::operation::intersection::Rectangle::nextEdge (Position pos) inline static
Next edge in clock-wise direction.
Parameters
pos Rectangle Position
Returns
next {} Position in clock-wise direction
Definition at line 178 of file Rectangle.h.
Referenced by geos::operation::intersection::RectangleIntersectionBuilder::close_boundary(), and geos::operation::intersection::distance().
   {
   switch(pos)
     {
     case BottomLeft:
     case Left:       return Top;
     case TopLeft:
     case Top:        return Right;
     case TopRight:
     case Right:      return Bottom;
     case BottomRight:
     case Bottom:     return Left;
     /* silences compiler warnings, Inside & Outside are not handled explicitly */
     default:         return pos;
     }
   }
static bool geos::operation::intersection::Rectangle::onEdge (Position pos) inline static
Test if the given position is on a edge.
Parameters
pos Rectangle Position
Returns
true, if the position is on an edge
Definition at line 127 of file Rectangle.h.
   {
   return (pos > Outside);
   }
static bool geos::operation::intersection::Rectangle::onSameEdge (Position pos1, Position pos2) inline static
Test if the given positions are on the same Rectangle edge.
Parameters
pos1 Rectangle Position of first coordinate
pos2 Rectangle Position of second coordinate
Returns
true, if the positions are on the same edge
Definition at line 139 of file Rectangle.h.
   {
   return onEdge(Position(pos1 & pos2));
   }
Position geos::operation::intersection::Rectangle::position (double x, double y) const inline
Establish position of coordinate with respect to a Rectangle.
Parameters
x x-coordinate
y y-coordinate
Returns
Position of the coordinate
Definition at line 151 of file Rectangle.h.
Referenced by geos::operation::intersection::RectangleIntersection::clip_linestring_parts(), geos::operation::intersection::RectangleIntersection::clip_point(), geos::operation::intersection::RectangleIntersectionBuilder::close_boundary(), and geos::operation::intersection::distance().
   {
   // We assume the point to be inside and test it first
   if(x>xMin && x<xMax && y>yMin && y<yMax)
     return Inside;
   // Next we assume the point to be outside and test it next
   if(x<xMin || x>xMax || y<yMin || y>yMax)
     return Outside;
   // Slower cases
   unsigned int pos = 0;
   if(x==xMin)
     pos |= Left;
   else if(x==xMax)
     pos |= Right;
   if(y==yMin)
     pos |= Bottom;
   else if(y==yMax)
     pos |= Top;
   return Position(pos);
   }
geom::LinearRing * geos::operation::intersection::Rectangle::toLinearRing (const geom::GeometryFactory & f) const
Definition at line 51 of file Rectangle.cpp.
References geos::geom::CoordinateSequenceFactory::create(), geos::geom::GeometryFactory::createLinearRing(), geos::geom::CoordinateSequence::getAt(), geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::geom::CoordinateSequence::setAt(), xMax, xMin, yMax, and yMin.
Referenced by geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), and toPolygon().
   {
     const geom::CoordinateSequenceFactory *csf = f.getCoordinateSequenceFactory();
     geom::CoordinateSequence *seq = csf->create(5, 2);
     seq->setAt(geom::Coordinate(xMin, yMin), 0);
     seq->setAt(geom::Coordinate(xMin, yMax), 1);
     seq->setAt(geom::Coordinate(xMax, yMax), 2);
     seq->setAt(geom::Coordinate(xMax, yMin), 3);
     seq->setAt(seq->getAt(0), 4); // close
     return f.createLinearRing(seq);
   }
geom::Polygon * geos::operation::intersection::Rectangle::toPolygon (const geom::GeometryFactory & f) const
@return the rectangle as a polygon geometry
Ownership transferred to caller
Definition at line 44 of file Rectangle.cpp.
References geos::geom::GeometryFactory::createPolygon(), and toLinearRing().
   {
     geom::LinearRing* ls = toLinearRing(f);
     return f.createPolygon(ls, nullptr);
   }
double geos::operation::intersection::Rectangle::xmax () const inline
@return the maximum x-coordinate of the rectangle
Definition at line 83 of file Rectangle.h.
Referenced by geos::operation::intersection::RectangleIntersection::clip_linestring_parts(), geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons(), geos::operation::intersection::clip_to_edges(), geos::operation::intersection::RectangleIntersectionBuilder::close_boundary(), and geos::operation::intersection::distance().
 { return xMax; }
double geos::operation::intersection::Rectangle::xmin () const inline
@return the minimum x-coordinate of the rectangle
Definition at line 70 of file Rectangle.h.
Referenced by geos::operation::intersection::RectangleIntersection::clip_linestring_parts(), geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons(), geos::operation::intersection::clip_to_edges(), geos::operation::intersection::RectangleIntersectionBuilder::close_boundary(), and geos::operation::intersection::distance().
 { return xMin; }
double geos::operation::intersection::Rectangle::ymax () const inline
@return the maximum y-coordinate of the rectangle
Definition at line 90 of file Rectangle.h.
Referenced by geos::operation::intersection::RectangleIntersection::clip_linestring_parts(), geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons(), geos::operation::intersection::clip_to_edges(), geos::operation::intersection::RectangleIntersectionBuilder::close_boundary(), and geos::operation::intersection::distance().
 { return yMax; }
double geos::operation::intersection::Rectangle::ymin () const inline
@return the minimum y-coordinate of the rectangle
Definition at line 76 of file Rectangle.h.
Referenced by geos::operation::intersection::RectangleIntersection::clip_linestring_parts(), geos::operation::intersection::RectangleIntersection::clip_polygon_to_polygons(), geos::operation::intersection::clip_to_edges(), geos::operation::intersection::RectangleIntersectionBuilder::close_boundary(), and geos::operation::intersection::distance().
 { return yMin; }
Member Data Documentation
double geos::operation::intersection::Rectangle::xMax private
Definition at line 200 of file Rectangle.h.
Referenced by Rectangle(), and toLinearRing().
double geos::operation::intersection::Rectangle::xMin private
Definition at line 198 of file Rectangle.h.
Referenced by Rectangle(), and toLinearRing().
double geos::operation::intersection::Rectangle::yMax private
Definition at line 201 of file Rectangle.h.
Referenced by Rectangle(), and toLinearRing().
double geos::operation::intersection::Rectangle::yMin private
Definition at line 199 of file Rectangle.h.
Referenced by Rectangle(), and toLinearRing().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/intersection/Rectangle.h
/home/vicky/potree/geos/vicky/src/operation/intersection/Rectangle.cpp