GEOS: geos::operation::linemerge::LineSequencer Class Reference
geos::operation::linemerge::LineSequencer Class Reference
Builds a sequence from a set of LineStrings so that they are ordered end to end.
#include <LineSequencer.h>
Public Member Functions
LineSequencer ()
bool isSequenceable ()
void add (const geom::Geometry &geometry)
template<class TargetContainer >
void add (TargetContainer &geoms)
void filter (const geom::Geometry *g)
geom::Geometry * getSequencedLineStrings (bool release=1)
Static Public Member Functions
static geom::Geometry * sequence (const geom::Geometry &geom)
static bool isSequenced (const geom::Geometry *geom)
Private Types
typedef std::list< planargraph::DirectedEdge * > DirEdgeList
typedef std::vector< DirEdgeList * > Sequences
Private Member Functions
void addLine (const geom::LineString *lineString)
void computeSequence ()
Sequences * findSequences ()
DirEdgeList * findSequence (planargraph::Subgraph &graph)
void delAll (Sequences &)
geom::Geometry * buildSequencedGeometry (const Sequences &sequences)
void addReverseSubpath (const planargraph::DirectedEdge *de, DirEdgeList &deList, DirEdgeList::iterator lit, bool expectedClosed)
DirEdgeList * orient (DirEdgeList *seq)
DirEdgeList * reverse (DirEdgeList &seq)
bool hasSequence (planargraph::Subgraph &graph)
Static Private Member Functions
static geom::LineString * reverse (const geom::LineString *line)
return a newly allocated LineString
static const planargraph::Node * findLowestDegreeNode (const planargraph::Subgraph &graph)
static const planargraph::DirectedEdge * findUnvisitedBestOrientedDE (const planargraph::Node *node)
Private Attributes
LineMergeGraph graph
const geom::GeometryFactory * factory
unsigned int lineCount
bool isRun
std::unique_ptr< geom::Geometry > sequencedGeometry
bool isSequenceableVar
Detailed Description
Builds a sequence from a set of LineStrings so that they are ordered end to end.
A sequence is a complete non-repeating list of the linear components of the input. Each linestring is oriented so that identical endpoints are adjacent in the list.
A typical use case is to convert a set of unoriented geometric links from a linear network (e.g. such as block faces on a bus route) into a continuous oriented path through the network.
The input linestrings may form one or more connected sets. The input linestrings should be correctly noded, or the results may not be what is expected. The computed output is a single MultiLineString containing the ordered linestrings in the sequence.
The sequencing employs the classic Eulerian path graph algorithm. Since Eulerian paths are not uniquely determined, further rules are used to make the computed sequence preserve as much as possible of the input ordering. Within a connected subset of lines, the ordering rules are:
If there is degree-1 node which is the start node of an linestring, use that node as the start of the sequence
If there is a degree-1 node which is the end node of an linestring, use that node as the end of the sequence
If the sequence has no degree-1 nodes, use any node as the start
Note that not all arrangements of lines can be sequenced. For a connected set of edges in a graph, Euler's Theorem states that there is a sequence containing each edge once if and only if there are no more than 2 nodes of odd degree. If it is not possible to find a sequence, the isSequenceable method will return false.
Definition at line 99 of file LineSequencer.h.
Member Typedef Documentation
typedef std::list<planargraph::DirectedEdge*> geos::operation::linemerge::LineSequencer::DirEdgeList private
Definition at line 102 of file LineSequencer.h.
typedef std::vector< DirEdgeList* > geos::operation::linemerge::LineSequencer::Sequences private
Definition at line 103 of file LineSequencer.h.
Constructor & Destructor Documentation
geos::operation::linemerge::LineSequencer::LineSequencer () inline
Definition at line 203 of file LineSequencer.h.
     :
     factory(nullptr),
     lineCount(0),
     isRun(false),
     sequencedGeometry(nullptr),
     isSequenceableVar(false)
     {}
Member Function Documentation
void geos::operation::linemerge::LineSequencer::add (const geom::Geometry & geometry) inline
Adds a Geometry to be sequenced. May be called multiple times. Any dimension of Geometry may be added; the constituent linework will be extracted.
Parameters
geometry the geometry to add
Definition at line 243 of file LineSequencer.h.
References geos::geom::Geometry::applyComponentFilter().
Referenced by sequence().
{
     geometry.applyComponentFilter(*this);
   }
template<class TargetContainer > void geos::operation::linemerge::LineSequencer::add (TargetContainer & geoms) inline
Definition at line 248 of file LineSequencer.h.
   {
     for (typename TargetContainer::const_iterator i = geoms.begin(),
          e = geoms.end(); i != e; ++i)
     {
       const geom::Geometry* g = *i;
       add(*g);
     }
   }
void geos::operation::linemerge::LineSequencer::addLine (const geom::LineString * lineString) private
Definition at line 167 of file LineSequencer.cpp.
References geos::geom::Geometry::getFactory().
 {
   if (factory == nullptr) {
     factory = lineString->getFactory();
   }
   graph.addEdge(lineString);
   ++lineCount;
 }
void geos::operation::linemerge::LineSequencer::addReverseSubpath (const planargraph::DirectedEdge * de, DirEdgeList & deList, DirEdgeList::iterator lit, bool expectedClosed) private
Definition at line 299 of file LineSequencer.cpp.
References geos::planargraph::DirectedEdge::getEdge(), geos::planargraph::DirectedEdge::getFromNode(), geos::planargraph::DirectedEdge::getSym(), geos::planargraph::DirectedEdge::getToNode(), and geos::planargraph::GraphComponent::setVisited().
 {
   using planargraph::Node;
   using planargraph::DirectedEdge;
   // trace an unvisited path *backwards* from this de
   Node* endNode = de->getToNode();
   Node* fromNode = nullptr;
   while (true) {
     deList.insert(lit, de->getSym());
     de->getEdge()->setVisited(true);
     fromNode = de->getFromNode();
     const DirectedEdge* unvisitedOutDE = findUnvisitedBestOrientedDE(fromNode);
     // this must terminate, since we are continually marking edges as visited
     if (unvisitedOutDE == nullptr) break;
     de = unvisitedOutDE->getSym();
   }
   if ( expectedClosed ) {
     // the path should end at the toNode of this de,
     // otherwise we have an error
     util::Assert::isTrue(fromNode == endNode, "path not contiguos");
     //assert(fromNode == endNode);
   }
 }
Geometry * geos::operation::linemerge::LineSequencer::buildSequencedGeometry (const Sequences & sequences) private
Builds a geometry (LineString or MultiLineString) representing the sequence.
Parameters
sequences a vector of vectors of const planarDirectedEdges with LineMergeEdges as their parent edges. Ownership of container and contents retained by caller.
Returns
the sequenced geometry, possibly NULL if no sequence exists
Definition at line 202 of file LineSequencer.cpp.
References geos::geom::LineString::clone(), geos::planargraph::DirectedEdge::getEdge(), geos::planargraph::DirectedEdge::getEdgeDirection(), geos::operation::linemerge::LineMergeEdge::getLine(), and geos::geom::LineString::isClosed().
 {
   unique_ptr<Geometry::NonConstVect> lines(new Geometry::NonConstVect);
   for (Sequences::const_iterator
     i1=sequences.begin(), i1End=sequences.end();
     i1 != i1End;
     ++i1)
   {
     planargraph::DirectedEdge::NonConstList& seq = *(*i1);
     for(planargraph::DirectedEdge::NonConstList::iterator i2=seq.begin(),
       i2End=seq.end(); i2 != i2End; ++i2)
     {
       const planargraph::DirectedEdge* de = *i2;
       assert(dynamic_cast<LineMergeEdge* >(de->getEdge()));
       LineMergeEdge* e = static_cast<LineMergeEdge* >(de->getEdge());
       const LineString* line = e->getLine();
       // lineToAdd will be a *copy* of input things
       LineString* lineToAdd;
       if ( ! de->getEdgeDirection() && ! line->isClosed() ) {
         lineToAdd = reverse(line);
       } else {
         Geometry* lineClone = line->clone();
         lineToAdd = dynamic_cast<LineString *>(lineClone);
         assert(lineToAdd);
       }
       lines->push_back(lineToAdd);
     }
   }
   if ( lines->size() == 0 ) {
     return nullptr;
   } else {
     Geometry::NonConstVect *l=lines.get();
     lines.release();
     return factory->buildGeometry(l);
   }
 }
void geos::operation::linemerge::LineSequencer::computeSequence () private
Definition at line 178 of file LineSequencer.cpp.
 {
   if (isRun) return;
   isRun = true;
   Sequences* sequences = findSequences();
   if (sequences == nullptr) return;
   sequencedGeometry = unique_ptr<Geometry>(buildSequencedGeometry(*sequences));
   isSequenceableVar = true;
   delAll(*sequences);
   delete sequences;
   // Lines were missing from result
   assert(lineCount == sequencedGeometry->getNumGeometries());
   // Result is not linear
   assert(dynamic_cast<LineString *>(sequencedGeometry.get())
     || dynamic_cast<MultiLineString *>(sequencedGeometry.get()));
 }
void geos::operation::linemerge::LineSequencer::delAll (LineSequencer::Sequences & s) private
Definition at line 127 of file LineSequencer.cpp.
 {
   for ( Sequences::iterator i=s.begin(), e=s.end(); i!=e; ++i )
   {
     delete *i;
   }
 }
void geos::operation::linemerge::LineSequencer::filter (const geom::Geometry * g) inline
Act as a GeometryComponentFilter so to extract the linearworks
Definition at line 262 of file LineSequencer.h.
   {
     if (const geom::LineString *ls=dynamic_cast<const geom::LineString *>(g))
     {
       addLine(ls);
     }
   }
const planargraph::Node * geos::operation::linemerge::LineSequencer::findLowestDegreeNode (const planargraph::Subgraph & graph) static private
Definition at line 255 of file LineSequencer.cpp.
References geos::planargraph::Node::getDegree(), geos::planargraph::Subgraph::nodeBegin(), and geos::planargraph::Subgraph::nodeEnd().
 {
   size_t minDegree = numeric_limits<size_t>::max();
   const planargraph::Node* minDegreeNode = nullptr;
   for (planargraph::NodeMap::container::const_iterator
     it = graph.nodeBegin(), itEnd = graph.nodeEnd();
     it != itEnd;
     ++it )
   {
     const planargraph::Node* node = (*it).second;
     if (minDegreeNode == nullptr || node->getDegree() < minDegree)
     {
       minDegree = node->getDegree();
       minDegreeNode = node;
     }
   }
   return minDegreeNode;
 }
planargraph::DirectedEdge::NonConstList * geos::operation::linemerge::LineSequencer::findSequence (planargraph::Subgraph & graph) private
Definition at line 332 of file LineSequencer.cpp.
References geos::planargraph::Subgraph::edgeBegin(), and geos::planargraph::Subgraph::edgeEnd().
 {
   using planargraph::DirectedEdge;
   using planargraph::Node;
   using planargraph::GraphComponent;
   GraphComponent::setVisited(graph.edgeBegin(),
       graph.edgeEnd(), false);
   const Node* startNode = findLowestDegreeNode(graph);
   const auto startDE = *(startNode->getOutEdges().begin());
   const DirectedEdge *startDESym = startDE->getSym();
   DirectedEdge::NonConstList *seq = new DirectedEdge::NonConstList();
   DirectedEdge::NonConstList::iterator lit=seq->begin();
   addReverseSubpath(startDESym, *seq, lit, false);
   lit=seq->end();
   while (lit != seq->begin()) {
     const DirectedEdge* prev = *(--lit);
     const DirectedEdge* unvisitedOutDE = findUnvisitedBestOrientedDE(prev->getFromNode());
     if (unvisitedOutDE != nullptr)
       addReverseSubpath(unvisitedOutDE->getSym(), *seq, lit, true);
   }
   // At this point, we have a valid sequence of graph DirectedEdges,
   // but it is not necessarily appropriately oriented relative to
   // the underlying geometry.
   DirectedEdge::NonConstList* orientedSeq = orient(seq);
   if (orientedSeq != seq) delete seq;
   return orientedSeq;
 }
LineSequencer::Sequences * geos::operation::linemerge::LineSequencer::findSequences () private
Definition at line 137 of file LineSequencer.cpp.
References geos::planargraph::algorithm::ConnectedSubgraphFinder::getConnectedSubgraphs().
 {
   Sequences *sequences = new Sequences();
   planargraph::algorithm::ConnectedSubgraphFinder csFinder(graph);
   vector<planargraph::Subgraph*> subgraphs;
   csFinder.getConnectedSubgraphs(subgraphs);
   for (vector<planargraph::Subgraph*>::const_iterator
     it=subgraphs.begin(), endIt=subgraphs.end();
     it!=endIt;
     ++it )
   {
     planargraph::Subgraph* subgraph = *it;
     if (hasSequence(*subgraph)) {
       planargraph::DirectedEdge::NonConstList* seq=findSequence(*subgraph);
       sequences->push_back(seq);
     }
     else {
       // if any subgraph cannot be sequenced, abort
       delete subgraph;
       delAll(*sequences);
       delete sequences;
       return nullptr;
     }
     delete subgraph;
   }
   return sequences;
 }
const planargraph::DirectedEdge * geos::operation::linemerge::LineSequencer::findUnvisitedBestOrientedDE (const planargraph::Node * node) static private
Finds an DirectedEdge for an unvisited edge (if any), choosing the dirEdge which preserves orientation, if possible.
Parameters
node the node to examine
Returns
the dirEdge found, or null if none were unvisited
Definition at line 276 of file LineSequencer.cpp.
References geos::planargraph::Node::getOutEdges().
 {
   using planargraph::DirectedEdge;
   using planargraph::DirectedEdgeStar;
   const DirectedEdge* wellOrientedDE = nullptr;
   const DirectedEdge* unvisitedDE = nullptr;
   const auto des = node->getOutEdges();
   for (const auto de : des)
   {
     if (! de->getEdge()->isVisited()) {
       unvisitedDE = de;
       if (de->getEdgeDirection()) wellOrientedDE = de;
     }
   }
   if (wellOrientedDE != nullptr)
     return wellOrientedDE;
   return unvisitedDE;
 }
geom::Geometry* geos::operation::linemerge::LineSequencer::getSequencedLineStrings (bool release = 1) inline
Returns the LineString or MultiLineString built by the sequencing process, if one exists.
Parameters
release release ownership of computed Geometry
Returns
the sequenced linestrings, or null if a valid sequence does not exist.
Definition at line 280 of file LineSequencer.h.
Referenced by sequence().
{
     computeSequence();
     if (release) return sequencedGeometry.release();
     else return sequencedGeometry.get();
   }
bool geos::operation::linemerge::LineSequencer::hasSequence (planargraph::Subgraph & graph) private
Tests whether a complete unique path exists in a graph using Euler's Theorem.
Parameters
graph the subgraph containing the edges
Returns
true if a sequence exists
Definition at line 111 of file LineSequencer.cpp.
References geos::planargraph::Node::getDegree(), geos::planargraph::Subgraph::nodeBegin(), and geos::planargraph::Subgraph::nodeEnd().
 {
   int oddDegreeCount = 0;
   for (planargraph::NodeMap::container::const_iterator
     it=graph.nodeBegin(), endIt=graph.nodeEnd();
     it!=endIt;
     ++it)
   {
     planargraph::Node* node = it->second;
     if (node->getDegree() % 2 == 1)
     oddDegreeCount++;
   }
   return oddDegreeCount <= 2;
 }
bool geos::operation::linemerge::LineSequencer::isSequenceable () inline
Tests whether the arrangement of linestrings has a valid sequence.
Returns
true if a valid sequence exists.
Definition at line 230 of file LineSequencer.h.
{
     computeSequence();
     return isSequenceableVar;
   }
bool geos::operation::linemerge::LineSequencer::isSequenced (const geom::Geometry * geom) static
Tests whether a Geometry is sequenced correctly. { LineString}s are trivially sequenced. MultiLineStrings are checked for correct sequencing. Otherwise, isSequenced is defined to be true for geometries that are not lineal.
Parameters
geom the geometry to test
Returns
true if the geometry is sequenced or is not lineal
If this linestring is connected to a previous subgraph, geom is not sequenced
Definition at line 53 of file LineSequencer.cpp.
References geos::geom::Coordinate::equals2D(), geos::geom::LineString::getCoordinateN(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), and geos::geom::LineString::getNumPoints().
 {
   const MultiLineString *mls;
   if ( nullptr == (mls=dynamic_cast<const MultiLineString *>(geom)) )
   {
     return true;
   }
   // the nodes in all subgraphs which have been completely scanned
   Coordinate::ConstSet prevSubgraphNodes;
   Coordinate::ConstVect currNodes;
   const Coordinate* lastNode = nullptr;
   for (std::size_t i=0, n=mls->getNumGeometries(); i<n; ++i)
   {
     const LineString* lineptr = \
       dynamic_cast<const LineString*>(mls->getGeometryN(i));
     assert(lineptr);
     const LineString& line = *lineptr;
     const Coordinate* startNode = &(line.getCoordinateN(0));
     const Coordinate* endNode = &(line.getCoordinateN(static_cast<int>(line.getNumPoints() - 1)));
     if (prevSubgraphNodes.find(startNode) != prevSubgraphNodes.end())
     {
       return false;
     }
     if (prevSubgraphNodes.find(endNode) != prevSubgraphNodes.end())
     {
       return false;
     }
     if (lastNode != nullptr)
     {
       if (! startNode->equals2D(*lastNode))
       {
         // start new connected sequence
         prevSubgraphNodes.insert(currNodes.begin(),
             currNodes.end());
         currNodes.clear();
       }
     }
     currNodes.push_back(startNode);
     currNodes.push_back(endNode);
     lastNode = endNode;
   }
   return true;
 }
planargraph::DirectedEdge::NonConstList * geos::operation::linemerge::LineSequencer::orient (DirEdgeList * seq) private
Computes a version of the sequence which is optimally oriented relative to the underlying geometry.
Heuristics used are:
If the path has a degree-1 node which is the start node of an linestring, use that node as the start of the sequence
If the path has a degree-1 node which is the end node of an linestring, use that node as the end of the sequence
If the sequence has no degree-1 nodes, use any node as the start (NOTE: in this case could orient the sequence according to the majority of the linestring orientations)
Parameters
seq a List of planarDirectedEdges
Returns
the oriented sequence, possibly same as input if already oriented
Definition at line 371 of file LineSequencer.cpp.
 {
   using namespace geos::planargraph;
   const DirectedEdge* startEdge = seq->front();
   const DirectedEdge* endEdge = seq->back();
   Node* startNode = startEdge->getFromNode();
   Node* endNode = endEdge->getToNode();
   bool flipSeq = false;
   bool hasDegree1Node = \
     startNode->getDegree() == 1 || endNode->getDegree() == 1;
   if (hasDegree1Node)
   {
     bool hasObviousStartNode = false;
     // test end edge before start edge, to make result stable
     // (ie. if both are good starts, pick the actual start
     if (endEdge->getToNode()->getDegree() == 1 &&
         endEdge->getEdgeDirection() == false)
     {
       hasObviousStartNode = true;
       flipSeq = true;
     }
     if (startEdge->getFromNode()->getDegree() == 1 &&
         startEdge->getEdgeDirection() == true)
     {
       hasObviousStartNode = true;
       flipSeq = false;
     }
     // since there is no obvious start node,
     // use any node of degree 1
     if (! hasObviousStartNode)
     {
       // check if the start node should actually
       // be the end node
       if (startEdge->getFromNode()->getDegree() == 1)
         flipSeq = true;
       // if the end node is of degree 1, it is
       // properly the end node
     }
   }
   // if there is no degree 1 node, just use the sequence as is
   // (Could insert heuristic of taking direction of majority of
   // lines as overall direction)
   if (flipSeq)
   {
     return reverse(*seq);
   }
   return seq;
 }
LineString * geos::operation::linemerge::LineSequencer::reverse (const geom::LineString * line) static private
return a newly allocated LineString
Definition at line 246 of file LineSequencer.cpp.
References geos::geom::GeometryFactory::createLineString(), geos::geom::LineString::getCoordinates(), and geos::geom::Geometry::getFactory().
 {
   CoordinateSequence* cs=line->getCoordinates();
   CoordinateSequence::reverse(cs);
   return line->getFactory()->createLineString(cs);
 }
DirEdgeList* geos::operation::linemerge::LineSequencer::reverse (DirEdgeList & seq) private
Reverse the sequence. This requires reversing the order of the dirEdges, and flipping each dirEdge as well
Parameters
seq a List of DirectedEdges, in sequential order
Returns
the reversed sequence
static geom::Geometry* geos::operation::linemerge::LineSequencer::sequence (const geom::Geometry & geom) inline static
Definition at line 196 of file LineSequencer.h.
References add(), and getSequencedLineStrings().
   {
     LineSequencer sequencer;
     sequencer.add(geom);
     return sequencer.getSequencedLineStrings();
   }
Member Data Documentation
const geom::GeometryFactory* geos::operation::linemerge::LineSequencer::factory private
Definition at line 106 of file LineSequencer.h.
LineMergeGraph geos::operation::linemerge::LineSequencer::graph private
Definition at line 105 of file LineSequencer.h.
bool geos::operation::linemerge::LineSequencer::isRun private
Definition at line 108 of file LineSequencer.h.
bool geos::operation::linemerge::LineSequencer::isSequenceableVar private
Definition at line 110 of file LineSequencer.h.
unsigned int geos::operation::linemerge::LineSequencer::lineCount private
Definition at line 107 of file LineSequencer.h.
std::unique_ptr<geom::Geometry> geos::operation::linemerge::LineSequencer::sequencedGeometry private
Definition at line 109 of file LineSequencer.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/operation/linemerge/LineSequencer.h
/home/vicky/potree/geos/vicky/src/operation/linemerge/LineSequencer.cpp