GEOS: geos::io::WKTWriter Class Reference
geos::io::WKTWriter Class Reference
Outputs the textual representation of a Geometry. See also WKTReader.
#include <geos.h>
Public Member Functions
WKTWriter ()
~WKTWriter ()
std::string write (const geom::Geometry *geometry)
Returns WKT string for the given Geometry.
void write (const geom::Geometry *geometry, Writer *writer)
std::string writeFormatted (const geom::Geometry *geometry)
void writeFormatted (const geom::Geometry *geometry, Writer *writer)
void setRoundingPrecision (int p0)
void setTrim (bool p0)
void setOld3D (bool useOld3D)
int getOutputDimension () const
void setOutputDimension (int newOutputDimension)
Static Public Member Functions
static std::string toLineString (const geom::CoordinateSequence &seq)
static std::string toLineString (const geom::Coordinate &p0, const geom::Coordinate &p1)
static std::string toPoint (const geom::Coordinate &p0)
Protected Member Functions
void appendGeometryTaggedText (const geom::Geometry *geometry, int level, Writer *writer)
void appendPointTaggedText (const geom::Coordinate *coordinate, int level, Writer *writer)
void appendLineStringTaggedText (const geom::LineString *lineString, int level, Writer *writer)
void appendLinearRingTaggedText (const geom::LinearRing *lineString, int level, Writer *writer)
void appendPolygonTaggedText (const geom::Polygon *polygon, int level, Writer *writer)
void appendMultiPointTaggedText (const geom::MultiPoint *multipoint, int level, Writer *writer)
void appendMultiLineStringTaggedText (const geom::MultiLineString *multiLineString, int level, Writer *writer)
void appendMultiPolygonTaggedText (const geom::MultiPolygon *multiPolygon, int level, Writer *writer)
void appendGeometryCollectionTaggedText (const geom::GeometryCollection *geometryCollection, int level, Writer *writer)
void appendPointText (const geom::Coordinate *coordinate, int level, Writer *writer)
void appendCoordinate (const geom::Coordinate *coordinate, Writer *writer)
std::string writeNumber (double d)
void appendLineStringText (const geom::LineString *lineString, int level, bool doIndent, Writer *writer)
void appendPolygonText (const geom::Polygon *polygon, int level, bool indentFirst, Writer *writer)
void appendMultiPointText (const geom::MultiPoint *multiPoint, int level, Writer *writer)
void appendMultiLineStringText (const geom::MultiLineString *multiLineString, int level, bool indentFirst, Writer *writer)
void appendMultiPolygonText (const geom::MultiPolygon *multiPolygon, int level, Writer *writer)
void appendGeometryCollectionText (const geom::GeometryCollection *geometryCollection, int level, Writer *writer)
Protected Attributes
int decimalPlaces
Private Types
enum { INDENT = 2 }
Private Member Functions
void writeFormatted (const geom::Geometry *geometry, bool isFormatted, Writer *writer)
void indent (int level, Writer *writer)
Private Attributes
bool isFormatted
int roundingPrecision
bool trim
int level
int defaultOutputDimension
int outputDimension
bool old3D
Detailed Description
Outputs the textual representation of a Geometry. See also WKTReader.
The WKTWriter outputs coordinates rounded to the precision model. No more than the maximum number of necessary decimal places will be output.
The Well-known Text format is defined in the OpenGIS Simple Features Specification for SQL.
A non-standard "LINEARRING" tag is used for LinearRings. The WKT spec does not define a special tag for LinearRings. The standard tag to use is "LINESTRING".
See WKTReader for parsing.
Definition at line 79 of file WKTWriter.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
INDENT
Definition at line 242 of file WKTWriter.h.
        {
     INDENT = 2
   };
Constructor & Destructor Documentation
geos::io::WKTWriter::WKTWriter ()
Definition at line 52 of file WKTWriter.cpp.
                     :
   decimalPlaces(6),
   isFormatted(false),
   roundingPrecision(-1),
   trim(false),
   level(0),
   defaultOutputDimension(2),
   old3D(false)
 {
 }
geos::io::WKTWriter::~WKTWriter ()
Definition at line 72 of file WKTWriter.cpp.
 {}
Member Function Documentation
void geos::io::WKTWriter::appendCoordinate (const geom::Coordinate * coordinate, Writer * writer) protected
Definition at line 320 of file WKTWriter.cpp.
References outputDimension, geos::io::Writer::write(), writeNumber(), geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
Referenced by appendLineStringText(), appendMultiPointText(), and appendPointText().
 {
   writer->write(writeNumber(coordinate->x));
   writer->write(" ");
   writer->write(writeNumber(coordinate->y));
   if( outputDimension == 3 )
   {
     writer->write(" ");
     if( ISNAN(coordinate->z) )
       writer->write(writeNumber(0.0));
     else
       writer->write(writeNumber(coordinate->z));
   }
 }
void geos::io::WKTWriter::appendGeometryCollectionTaggedText (const geom::GeometryCollection * geometryCollection, int level, Writer * writer) protected
Definition at line 298 of file WKTWriter.cpp.
References appendGeometryCollectionText(), geos::geom::GeometryCollection::isEmpty(), old3D, outputDimension, and geos::io::Writer::write().
Referenced by appendGeometryTaggedText().
{
   writer->write("GEOMETRYCOLLECTION ");
   if( outputDimension == 3 && !old3D && !geometryCollection->isEmpty() )
     writer->write( "Z " );
   appendGeometryCollectionText(geometryCollection, level, writer);
 }
void geos::io::WKTWriter::appendGeometryCollectionText (const geom::GeometryCollection * geometryCollection, int level, Writer * writer) protected
Definition at line 462 of file WKTWriter.cpp.
References appendGeometryTaggedText(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::geom::GeometryCollection::isEmpty(), level, and geos::io::Writer::write().
Referenced by appendGeometryCollectionTaggedText().
 {
   if (geometryCollection->isEmpty()) {
     writer->write("EMPTY");
   } else {
     int level2=level;
     writer->write("(");
     for (unsigned int i=0, n=static_cast<unsigned int>(geometryCollection->getNumGeometries());
         i < n ; ++i)
     {
       if (i>0) {
         writer->write(", ");
         level2=level+1;
       }
       appendGeometryTaggedText(geometryCollection->getGeometryN(i),level2,writer);
     }
     writer->write(")");
   }
 }
void geos::io::WKTWriter::appendGeometryTaggedText (const geom::Geometry * geometry, int level, Writer * writer) protected
Definition at line 181 of file WKTWriter.cpp.
References appendGeometryCollectionTaggedText(), appendLinearRingTaggedText(), appendLineStringTaggedText(), appendMultiLineStringTaggedText(), appendMultiPointTaggedText(), appendMultiPolygonTaggedText(), appendPointTaggedText(), appendPolygonTaggedText(), defaultOutputDimension, geos::geom::Geometry::getCoordinateDimension(), indent(), level, and outputDimension.
Referenced by appendGeometryCollectionText(), and writeFormatted().
 {
   outputDimension = std::min( defaultOutputDimension,
                          geometry->getCoordinateDimension() );
   indent(level, writer);
   if ( const Point* point = dynamic_cast<const Point*>(geometry) )
   {
     appendPointTaggedText(point->getCoordinate(),level,writer);
   }
   else if ( const LinearRing* lr =
     dynamic_cast<const LinearRing*>(geometry) )
   {
     appendLinearRingTaggedText(lr, level, writer);
   }
   else if ( const LineString* ls =
     dynamic_cast<const LineString*>(geometry) )
   {
     appendLineStringTaggedText(ls, level, writer);
   }
   else if ( const Polygon* x =
     dynamic_cast<const Polygon*>(geometry) )
   {
     appendPolygonTaggedText(x, level, writer);
   }
   else if ( const MultiPoint* x =
     dynamic_cast<const MultiPoint*>(geometry) )
   {
     appendMultiPointTaggedText(x, level, writer);
   }
   else if ( const MultiLineString* x =
     dynamic_cast<const MultiLineString*>(geometry) )
   {
     appendMultiLineStringTaggedText(x, level, writer);
   }
   else if ( const MultiPolygon* x =
     dynamic_cast<const MultiPolygon*>(geometry) )
   {
     appendMultiPolygonTaggedText(x, level, writer);
   }
   else if ( const GeometryCollection* x =
     dynamic_cast<const GeometryCollection*>(geometry) )
   {
     appendGeometryCollectionTaggedText(x, level, writer);
   }
   else
   {
     assert(0); // Unsupported Geometry implementation
   }
 }
void geos::io::WKTWriter::appendLinearRingTaggedText (const geom::LinearRing * lineString, int level, Writer * writer) protected
Definition at line 263 of file WKTWriter.cpp.
References appendLineStringText(), geos::geom::LineString::isEmpty(), old3D, outputDimension, and geos::io::Writer::write().
Referenced by appendGeometryTaggedText().
{
   writer->write("LINEARRING ");
   if( outputDimension == 3 && !old3D && !linearRing->isEmpty() )
     writer->write( "Z " );
   appendLineStringText((LineString*)linearRing, level, false, writer);
 }
void geos::io::WKTWriter::appendLineStringTaggedText (const geom::LineString * lineString, int level, Writer * writer) protected
Definition at line 246 of file WKTWriter.cpp.
References appendLineStringText(), geos::geom::LineString::isEmpty(), old3D, outputDimension, and geos::io::Writer::write().
Referenced by appendGeometryTaggedText().
 {
   writer->write("LINESTRING ");
   if( outputDimension == 3 && !old3D && !lineString->isEmpty() )
     writer->write( "Z " );
   appendLineStringText(lineString, level, false, writer);
 }
void geos::io::WKTWriter::appendLineStringText (const geom::LineString * lineString, int level, bool doIndent, Writer * writer) protected
Definition at line 349 of file WKTWriter.cpp.
References appendCoordinate(), geos::geom::LineString::getCoordinateN(), geos::geom::LineString::getNumPoints(), indent(), geos::geom::LineString::isEmpty(), and geos::io::Writer::write().
Referenced by appendLinearRingTaggedText(), appendLineStringTaggedText(), appendMultiLineStringText(), and appendPolygonText().
 {
   if (lineString->isEmpty()) {
     writer->write("EMPTY");
   } else {
     if (doIndent) indent(level, writer);
     writer->write("(");
     for(size_t i=0, n=lineString->getNumPoints(); i<n; ++i)
     {
       if (i>0) {
         writer->write(", ");
         if (i%10==0) indent(level + 2, writer);
       }
       appendCoordinate(&(lineString->getCoordinateN(static_cast<int>(i))), writer);
     }
     writer->write(")");
   }
 }
void geos::io::WKTWriter::appendMultiLineStringTaggedText (const geom::MultiLineString * multiLineString, int level, Writer * writer) protected
Definition at line 284 of file WKTWriter.cpp.
References appendMultiLineStringText(), geos::geom::GeometryCollection::isEmpty(), old3D, outputDimension, and geos::io::Writer::write().
Referenced by appendGeometryTaggedText().
{
   writer->write("MULTILINESTRING ");
   if( outputDimension == 3 && !old3D && !multiLineString->isEmpty() )
     writer->write( "Z " );
   appendMultiLineStringText(multiLineString, level, false, writer);
 }
void geos::io::WKTWriter::appendMultiLineStringText (const geom::MultiLineString * multiLineString, int level, bool indentFirst, Writer * writer) protected
Definition at line 412 of file WKTWriter.cpp.
References appendLineStringText(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::geom::GeometryCollection::isEmpty(), level, and geos::io::Writer::write().
Referenced by appendMultiLineStringTaggedText().
{
   if (multiLineString->isEmpty()) {
     writer->write("EMPTY");
   } else {
     int level2=level;
     bool doIndent=indentFirst;
     writer->write("(");
     for (unsigned int i=0, n=static_cast<unsigned int>(multiLineString->getNumGeometries());
         i<n; i++)
     {
       if (i>0) {
         writer->write(", ");
         level2=level+1;
         doIndent=true;
       }
       const LineString* ls = dynamic_cast<const LineString *>(
         multiLineString->getGeometryN(i)
       );
       appendLineStringText(ls, level2, doIndent, writer);
     }
     writer->write(")");
   }
 }
void geos::io::WKTWriter::appendMultiPointTaggedText (const geom::MultiPoint * multipoint, int level, Writer * writer) protected
Definition at line 277 of file WKTWriter.cpp.
References appendMultiPointText(), geos::geom::GeometryCollection::isEmpty(), old3D, outputDimension, and geos::io::Writer::write().
Referenced by appendGeometryTaggedText().
{
   writer->write("MULTIPOINT ");
   if( outputDimension == 3 && !old3D && !multipoint->isEmpty() )
     writer->write( "Z " );
   appendMultiPointText(multipoint, level, writer);
 }
void geos::io::WKTWriter::appendMultiPointText (const geom::MultiPoint * multiPoint, int level, Writer * writer) protected
Definition at line 390 of file WKTWriter.cpp.
References appendCoordinate(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::geom::GeometryCollection::isEmpty(), and geos::io::Writer::write().
Referenced by appendMultiPointTaggedText().
 {
   if (multiPoint->isEmpty()) {
     writer->write("EMPTY");
   } else {
     writer->write("(");
     for (unsigned int i=0, n=static_cast<unsigned int>(multiPoint->getNumGeometries());
         i<n; i++)
     {
       if (i > 0)
       {
         writer->write(", ");
       }
       appendCoordinate(
         dynamic_cast<const Point*>(multiPoint->getGeometryN(i))->getCoordinate(),
         writer);
     }
     writer->write(")");
   }
 }
void geos::io::WKTWriter::appendMultiPolygonTaggedText (const geom::MultiPolygon * multiPolygon, int level, Writer * writer) protected
Definition at line 291 of file WKTWriter.cpp.
References appendMultiPolygonText(), geos::geom::GeometryCollection::isEmpty(), old3D, outputDimension, and geos::io::Writer::write().
Referenced by appendGeometryTaggedText().
{
   writer->write("MULTIPOLYGON ");
   if( outputDimension == 3 && !old3D && !multiPolygon->isEmpty() )
     writer->write( "Z " );
   appendMultiPolygonText(multiPolygon, level, writer);
 }
void geos::io::WKTWriter::appendMultiPolygonText (const geom::MultiPolygon * multiPolygon, int level, Writer * writer) protected
Definition at line 437 of file WKTWriter.cpp.
References appendPolygonText(), geos::geom::GeometryCollection::getGeometryN(), geos::geom::GeometryCollection::getNumGeometries(), geos::geom::GeometryCollection::isEmpty(), level, and geos::io::Writer::write().
Referenced by appendMultiPolygonTaggedText().
{
   if (multiPolygon->isEmpty()) {
     writer->write("EMPTY");
   } else {
     int level2=level;
     bool doIndent=false;
     writer->write("(");
     for (unsigned int i=0, n=static_cast<unsigned int>(multiPolygon->getNumGeometries());
         i < n; i++)
     {
       if (i>0) {
         writer->write(", ");
         level2=level+1;
         doIndent=true;
       }
       const Polygon *p = dynamic_cast<const Polygon *>(
         multiPolygon->getGeometryN(i)
       );
       appendPolygonText(p, level2, doIndent, writer);
     }
     writer->write(")");
   }
 }
void geos::io::WKTWriter::appendPointTaggedText (const geom::Coordinate * coordinate, int level, Writer * writer) protected
Definition at line 235 of file WKTWriter.cpp.
References appendPointText(), old3D, outputDimension, and geos::io::Writer::write().
Referenced by appendGeometryTaggedText().
 {
   writer->write("POINT ");
   if( outputDimension == 3 && !old3D && coordinate != nullptr )
     writer->write( "Z " );
   appendPointText(coordinate, level, writer);
 }
void geos::io::WKTWriter::appendPointText (const geom::Coordinate * coordinate, int level, Writer * writer) protected
Definition at line 306 of file WKTWriter.cpp.
References appendCoordinate(), and geos::io::Writer::write().
Referenced by appendPointTaggedText().
 {
   if (coordinate==nullptr) {
     writer->write("EMPTY");
   } else {
     writer->write("(");
     appendCoordinate(coordinate, writer);
     writer->write(")");
   }
 }
void geos::io::WKTWriter::appendPolygonTaggedText (const geom::Polygon * polygon, int level, Writer * writer) protected
Definition at line 270 of file WKTWriter.cpp.
References appendPolygonText(), geos::geom::Polygon::isEmpty(), old3D, outputDimension, and geos::io::Writer::write().
Referenced by appendGeometryTaggedText().
{
   writer->write("POLYGON ");
   if( outputDimension == 3 && !old3D && !polygon->isEmpty())
     writer->write( "Z " );
   appendPolygonText(polygon, level, false, writer);
 }
void geos::io::WKTWriter::appendPolygonText (const geom::Polygon * polygon, int level, bool indentFirst, Writer * writer) protected
Definition at line 370 of file WKTWriter.cpp.
References appendLineStringText(), geos::geom::Polygon::getExteriorRing(), geos::geom::Polygon::getInteriorRingN(), geos::geom::Polygon::getNumInteriorRing(), indent(), geos::geom::Polygon::isEmpty(), level, and geos::io::Writer::write().
Referenced by appendMultiPolygonText(), and appendPolygonTaggedText().
 {
   if (polygon->isEmpty()) {
     writer->write("EMPTY");
   } else {
     if (indentFirst) indent(level, writer);
     writer->write("(");
     appendLineStringText(polygon->getExteriorRing(), level, false, writer);
     for (size_t i=0, n=polygon->getNumInteriorRing(); i<n; ++i)
     {
       writer->write(", ");
       const LineString *ls=polygon->getInteriorRingN(i);
       appendLineStringText(ls, level + 1, true, writer);
     }
     writer->write(")");
   }
 }
int geos::io::WKTWriter::getOutputDimension () const inline
Definition at line 159 of file WKTWriter.h.
Referenced by GEOSWKTWriter_getOutputDimension_r().
 { return defaultOutputDimension; }
void geos::io::WKTWriter::indent (int level, Writer * writer) private
Definition at line 485 of file WKTWriter.cpp.
References INDENT, isFormatted, and geos::io::Writer::write().
Referenced by appendGeometryTaggedText(), appendLineStringText(), and appendPolygonText().
{
   if (!isFormatted || level<=0) return;
   writer->write("\n");
   writer->write(string(INDENT * level, ' '));
 }
void geos::io::WKTWriter::setOld3D (bool useOld3D) inline
Enable old style 3D/4D WKT generation.
By default the WKBWriter produces new style 3D/4D WKT (ie. "POINT Z (10 20 30)") but if this method is used to turn on old style WKT production then the WKT will be formatted in the style "POINT (10 20 30)".
Parameters
useOld3D true or false
Definition at line 152 of file WKTWriter.h.
Referenced by GEOSWKTWriter_setOld3D_r().
 { old3D = useOld3D; }
void geos::io::WKTWriter::setOutputDimension (int newOutputDimension)
Definition at line 65 of file WKTWriter.cpp.
References defaultOutputDimension.
Referenced by GEOSWKTWriter_setOutputDimension_r().
 {
   if ( dims < 2 || dims > 3 )
     throw util::IllegalArgumentException("WKT output dimension must be 2 or 3");
   defaultOutputDimension = dims;
 }
void geos::io::WKTWriter::setRoundingPrecision (int p0)
Sets the rounding precision when writing the WKT a precision of -1 disables it
Parameters
p0 the new precision to use
Definition at line 135 of file WKTWriter.cpp.
References roundingPrecision.
Referenced by GEOSWKTWriter_setRoundingPrecision_r().
 {
   if(p0 < -1) {
     p0 = -1;
   }
   roundingPrecision = p0;
 }
void geos::io::WKTWriter::setTrim (bool p0)
Enables/disables trimming of unnecessary decimals
Parameters
p0 the trim boolean
Definition at line 144 of file WKTWriter.cpp.
References trim.
Referenced by geos::operation::buffer::BufferBuilder::computeNodedEdges(), and GEOSWKTWriter_setTrim_r().
 {
   trim = p0;
 }
string geos::io::WKTWriter::toLineString (const geom::CoordinateSequence & seq) static
Generates the WKT for a N-point LineString.
Parameters
seq the sequence to outpout
Returns
the WKT
Definition at line 76 of file WKTWriter.cpp.
References geos::geom::CoordinateSequence::getSize(), geos::geom::CoordinateSequence::getX(), and geos::geom::CoordinateSequence::getY().
 {
   stringstream buf(ios_base::in|ios_base::out);
     buf << "LINESTRING ";
   unsigned int npts = static_cast<unsigned int>(seq.getSize());
   if ( npts == 0 )
   {
     buf << "EMPTY";
   }
   else
   {
     buf << "(";
     for (unsigned int i=0; i<npts; ++i)
     {
       if (i) buf << ", ";
       buf << seq.getX(i) << " " << seq.getY(i);
 #if PRINT_Z
       buf << seq.getZ(i);
 #endif
     }
     buf << ")";
   }
   return buf.str();
 }
string geos::io::WKTWriter::toLineString (const geom::Coordinate & p0, const geom::Coordinate & p1) static
Generates the WKT for a 2-point LineString.
Parameters
p0 the first coordinate
p1 the second coordinate
Returns
the WKT
Definition at line 104 of file WKTWriter.cpp.
References geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
 {
   stringstream ret(ios_base::in|ios_base::out);
   ret << "LINESTRING (" << p0.x << " " << p0.y;
 #if PRINT_Z
   ret << " " << p0.z;
 #endif
   ret << ", " << p1.x << " " << p1.y;
 #if PRINT_Z
   ret << " " << p1.z;
 #endif
     ret << ")";
   return ret.str();
 }
string geos::io::WKTWriter::toPoint (const geom::Coordinate & p0) static
Generates the WKT for a Point.
Parameters
p0 the point coordinate
Returns
the WKT
Definition at line 122 of file WKTWriter.cpp.
References geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
 {
   stringstream ret(ios_base::in|ios_base::out);
     ret << "POINT (";
 #if PRINT_Z
   ret << p0.x << " " << p0.y  << " " << p0.z << " )";
 #else
   ret << p0.x << " " << p0.y  << " )";
 #endif
   return ret.str();
 }
string geos::io::WKTWriter::write (const geom::Geometry * geometry)
Returns WKT string for the given Geometry.
Definition at line 149 of file WKTWriter.cpp.
References geos::io::Writer::toString(), and writeFormatted().
Referenced by geos::operation::buffer::BufferBuilder::computeNodedEdges(), GEOSWKTWriter_write_r(), and geos::geom::Geometry::toText().
{
   Writer sw;
   writeFormatted(geometry,false,&sw);
   string res=sw.toString();
   return res;
 }
void geos::io::WKTWriter::write (const geom::Geometry * geometry, Writer * writer)
Definition at line 156 of file WKTWriter.cpp.
References writeFormatted().
{
   writeFormatted(geometry, false, writer);
 }
string geos::io::WKTWriter::writeFormatted (const geom::Geometry * geometry)
Definition at line 160 of file WKTWriter.cpp.
References geos::io::Writer::toString().
Referenced by write(), and writeFormatted().
{
   Writer sw;
   writeFormatted(geometry, true, &sw);
   return sw.toString();
 }
void geos::io::WKTWriter::writeFormatted (const geom::Geometry * geometry, Writer * writer)
Definition at line 166 of file WKTWriter.cpp.
References writeFormatted().
{
   writeFormatted(geometry, true, writer);
 }
void geos::io::WKTWriter::writeFormatted (const geom::Geometry * geometry, bool isFormatted, Writer * writer) private
Definition at line 171 of file WKTWriter.cpp.
References appendGeometryTaggedText(), decimalPlaces, geos::geom::PrecisionModel::getMaximumSignificantDigits(), geos::geom::Geometry::getPrecisionModel(), isFormatted, and roundingPrecision.
 {
         CLocalizer clocale;
   this->isFormatted=isFormatted;
   decimalPlaces = roundingPrecision == -1 ? geometry->getPrecisionModel()->getMaximumSignificantDigits() : roundingPrecision;
   appendGeometryTaggedText(geometry, 0, writer);
 }
string geos::io::WKTWriter::writeNumber (double d) protected
Definition at line 338 of file WKTWriter.cpp.
References decimalPlaces, and trim.
Referenced by appendCoordinate().
{
   std::stringstream ss;
   if ( ! trim ) ss << std::fixed;
   ss << std::setprecision(decimalPlaces >= 0 ? decimalPlaces : 0) << d;
   return ss.str();
 }
Member Data Documentation
int geos::io::WKTWriter::decimalPlaces protected
Definition at line 172 of file WKTWriter.h.
Referenced by writeFormatted(), and writeNumber().
int geos::io::WKTWriter::defaultOutputDimension private
Definition at line 256 of file WKTWriter.h.
Referenced by appendGeometryTaggedText(), and setOutputDimension().
bool geos::io::WKTWriter::isFormatted private
Definition at line 248 of file WKTWriter.h.
Referenced by indent(), and writeFormatted().
int geos::io::WKTWriter::level private
Definition at line 254 of file WKTWriter.h.
Referenced by appendGeometryCollectionText(), appendGeometryTaggedText(), appendMultiLineStringText(), appendMultiPolygonText(), and appendPolygonText().
bool geos::io::WKTWriter::old3D private
Definition at line 258 of file WKTWriter.h.
Referenced by appendGeometryCollectionTaggedText(), appendLinearRingTaggedText(), appendLineStringTaggedText(), appendMultiLineStringTaggedText(), appendMultiPointTaggedText(), appendMultiPolygonTaggedText(), appendPointTaggedText(), and appendPolygonTaggedText().
int geos::io::WKTWriter::outputDimension private
Definition at line 257 of file WKTWriter.h.
Referenced by appendCoordinate(), appendGeometryCollectionTaggedText(), appendGeometryTaggedText(), appendLinearRingTaggedText(), appendLineStringTaggedText(), appendMultiLineStringTaggedText(), appendMultiPointTaggedText(), appendMultiPolygonTaggedText(), appendPointTaggedText(), and appendPolygonTaggedText().
int geos::io::WKTWriter::roundingPrecision private
Definition at line 250 of file WKTWriter.h.
Referenced by setRoundingPrecision(), and writeFormatted().
bool geos::io::WKTWriter::trim private
Definition at line 252 of file WKTWriter.h.
Referenced by setTrim(), and writeNumber().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/io/WKTWriter.h
/home/vicky/potree/geos/vicky/src/io/WKTWriter.cpp