GEOS: geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor Class Reference
geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor Class Reference
Public Member Functions
TriangleCoordinatesVisitor (QuadEdgeSubdivision::TriList *triCoords)
void visit (QuadEdge *triEdges[3]) override
Private Attributes
QuadEdgeSubdivision::TriList * triCoords
CoordinateArraySequenceFactory coordSeqFact
Detailed Description
Definition at line 375 of file QuadEdgeSubdivision.cpp.
Constructor & Destructor Documentation
geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor::TriangleCoordinatesVisitor (QuadEdgeSubdivision::TriList * triCoords) inline
Definition at line 382 of file QuadEdgeSubdivision.cpp.
                                                                      : triCoords(triCoords)
     {
     }
Member Function Documentation
void geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor::visit (QuadEdge * triEdges[3]) inline override virtual
Visits the QuadEdges of a triangle.
Parameters
triEdges an array of the 3 quad edges in a triangle (in CCW order)
Implements geos::triangulate::quadedge::TriangleVisitor.
Definition at line 386 of file QuadEdgeSubdivision.cpp.
References geos::geom::CoordinateArraySequenceFactory::create(), geos::triangulate::quadedge::Vertex::getCoordinate(), geos::triangulate::quadedge::QuadEdge::orig(), and geos::geom::CoordinateSequence::setAt().
     {
         geom::CoordinateSequence *coordSeq = coordSeqFact.create(4,0);
         for (int i = 0; i < 3; i++) {
             Vertex v = triEdges[i]->orig();
             coordSeq->setAt(v.getCoordinate(), i);
         }
         coordSeq->setAt(triEdges[0]->orig().getCoordinate(), 3);
         triCoords->push_back(coordSeq);
     }
Member Data Documentation
CoordinateArraySequenceFactory geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor::coordSeqFact private
Definition at line 379 of file QuadEdgeSubdivision.cpp.
QuadEdgeSubdivision::TriList* geos::triangulate::quadedge::QuadEdgeSubdivision::TriangleCoordinatesVisitor::triCoords private
Definition at line 378 of file QuadEdgeSubdivision.cpp.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/triangulate/quadedge/QuadEdgeSubdivision.cpp