GEOS: geos::precision::MinimumClearance Class Reference
geos::precision::MinimumClearance Class Reference
#include <MinimumClearance.h>
Public Member Functions
MinimumClearance (const geom::Geometry *g)
double getDistance ()
std::unique_ptr< geom::LineString > getLine ()
Private Member Functions
void compute ()
Private Attributes
const geom::Geometry * inputGeom
double minClearance
std::unique_ptr< geom::CoordinateSequence > minClearancePts
Detailed Description
Definition at line 28 of file MinimumClearance.h.
Constructor & Destructor Documentation
geos::precision::MinimumClearance::MinimumClearance (const geom::Geometry * g)
Definition at line 35 of file MinimumClearance.cpp.
 : inputGeom(g) {}
Member Function Documentation
void geos::precision::MinimumClearance::compute () private
Definition at line 52 of file MinimumClearance.cpp.
References geos::geom::LineSegment::closestPoint(), geos::geom::CoordinateSequenceFactory::create(), geos::geom::Coordinate::distance(), geos::operation::intersection::distance(), geos::algorithm::CGAlgorithms::distancePointLine(), geos::geom::Coordinate::equals2D(), geos::operation::distance::FacetSequence::getCoordinate(), geos::geom::GeometryFactory::getCoordinateSequenceFactory(), geos::geom::Geometry::getFactory(), geos::index::strtree::ItemBoundable::getItem(), inputGeom, geos::geom::Geometry::isEmpty(), geos::index::strtree::AbstractSTRtree::iterate(), minClearance, minClearancePts, and geos::operation::distance::FacetSequence::size().
Referenced by getDistance(), and getLine().
{
     class MinClearanceDistance : public ItemDistance {
     private:
         double minDist;
         std::vector<Coordinate> minPts;
         void updatePts(const Coordinate & p, const Coordinate & seg0, const Coordinate & seg1) {
             LineSegment seg(seg0, seg1);
             minPts[0] = p;
             seg.closestPoint(p, minPts[1]);
         }
     public:
         MinClearanceDistance() :
                 minDist(std::numeric_limits<double>::infinity()),
                 minPts(std::vector<Coordinate>(2))
         {}
         const std::vector<Coordinate> * getCoordinates() {
             return &minPts;
         }
         double distance(const ItemBoundable* b1, const ItemBoundable* b2) override {
             FacetSequence* fs1 = static_cast<FacetSequence*>(b1->getItem());
             FacetSequence* fs2 = static_cast<FacetSequence*>(b2->getItem());
             minDist = std::numeric_limits<double>::infinity();
             return distance(fs1, fs2);
         }
         double distance(const FacetSequence* fs1, const FacetSequence* fs2) {
             // Compute MinClearance distance metric
             vertexDistance(fs1, fs2);
             if (fs1->size() == 1 && fs2->size() == 1)
                 return minDist;
             if (minDist <= 0.0)
                 return minDist;
             segmentDistance(fs1, fs2);
             if (minDist <= 0.0)
                 return minDist;
             segmentDistance(fs2, fs1);
             return minDist;
         }
         double vertexDistance(const FacetSequence* fs1, const FacetSequence* fs2) {
             for (size_t i1 = 0; i1 < fs1->size(); i1++) {
                 for (size_t i2 = 0; i2 < fs2->size(); i2++) {
                     const Coordinate* p1 = fs1->getCoordinate(i1);
                     const Coordinate* p2 = fs2->getCoordinate(i2);
                     if (!p1->equals2D(*p2)) {
                         double d = p1->distance(*p2);
                         if (d < minDist) {
                             minDist = d;
                             minPts[0] = *p1;
                             minPts[1] = *p2;
                             if (d == 0.0)
                                 return d;
                         }
                     }
                 }
             }
             return minDist;
         }
         double segmentDistance(const FacetSequence* fs1, const FacetSequence* fs2) {
             for (size_t i1 = 0; i1 < fs1->size(); i1++) {
                 for (size_t i2 = 1; i2 < fs2->size(); i2++) {
                     const Coordinate* p = fs1->getCoordinate(i1);
                     const Coordinate* seg0 = fs2->getCoordinate(i2 - 1);
                     const Coordinate* seg1 = fs2->getCoordinate(i2);
                     if (! (p->equals2D(*seg0) || p->equals2D(*seg1))) {
                         double d = geos::algorithm::CGAlgorithms::distancePointLine(*p, *seg0, *seg1);
                         if (d < minDist) {
                             minDist = d;
                             updatePts(*p, *seg0, *seg1);
                             if (d == 0.0)
                                 return d;
                         }
                     }
                 }
             }
             return minDist;
         }
     };
     struct ItemDeleter : public index::ItemVisitor {
         void visitItem(void * item) override {
             delete static_cast<FacetSequence*>(item);
         }
     };
     struct ManagedResourceSTRtree {
         STRtree* m_tree;
         ManagedResourceSTRtree(STRtree * p_tree) : m_tree(p_tree) {}
         ~ManagedResourceSTRtree() {
             ItemDeleter id;
             m_tree->iterate(id);
             delete m_tree;
         }
     };
     // already computed
     if (minClearancePts.get() != nullptr)
         return;
     // initialize to "No Distance Exists" state
     minClearancePts = std::unique_ptr<CoordinateSequence>(inputGeom->getFactory()->getCoordinateSequenceFactory()->create(2, 2));
     minClearance = std::numeric_limits<double>::infinity();
     // handle empty geometries
     if (inputGeom->isEmpty())
         return;
     ManagedResourceSTRtree tree(FacetSequenceTreeBuilder::build(inputGeom));
     MinClearanceDistance mcd;
     std::pair<const void *, const void *> nearest = tree.m_tree->nearestNeighbour(&mcd);
     minClearance = mcd.distance(
             static_cast<const FacetSequence *>(nearest.first),
             static_cast<const FacetSequence *>(nearest.second));
     const std::vector<Coordinate>* minClearancePtsVec = mcd.getCoordinates();
     minClearancePts->setAt((*minClearancePtsVec)[0], 0);
     minClearancePts->setAt((*minClearancePtsVec)[1], 1);
 }
double geos::precision::MinimumClearance::getDistance ()
Gets the Minimum Clearance distance.
Returns
the value of the minimum clearance distance or DBL_MAX if no Minimum Clearance distance exists
Definition at line 37 of file MinimumClearance.cpp.
References compute(), and minClearance.
Referenced by GEOSMinimumClearance_r().
{
     compute();
     return minClearance;
 }
std::unique_ptr< LineString > geos::precision::MinimumClearance::getLine ()
Gets a LineString containing two points which are at the Minimum Clearance distance.
Returns
the value of the minimum clearance distance or LINESTRING EMPTY if no Minimum Clearance distance exists
Definition at line 42 of file MinimumClearance.cpp.
References compute(), geos::geom::GeometryFactory::createLineString(), geos::geom::Geometry::getFactory(), inputGeom, minClearance, and minClearancePts.
Referenced by GEOSMinimumClearanceLine_r().
{
     compute();
     // return empty line string if no min pts were found
     if (minClearance == std::numeric_limits<double>::infinity())
         return std::unique_ptr<LineString>(inputGeom->getFactory()->createLineString());
     return std::unique_ptr<LineString>(inputGeom->getFactory()->createLineString(minClearancePts->clone()));
 }
Member Data Documentation
const geom::Geometry* geos::precision::MinimumClearance::inputGeom private
Definition at line 30 of file MinimumClearance.h.
Referenced by compute(), and getLine().
double geos::precision::MinimumClearance::minClearance private
Definition at line 31 of file MinimumClearance.h.
Referenced by compute(), getDistance(), and getLine().
std::unique_ptr<geom::CoordinateSequence> geos::precision::MinimumClearance::minClearancePts private
Definition at line 32 of file MinimumClearance.h.
Referenced by compute(), and getLine().
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/precision/MinimumClearance.h
/home/vicky/potree/geos/vicky/src/precision/MinimumClearance.cpp