GEOS: geos::index::quadtree::Root Class Reference
geos::index::quadtree::Root Class Reference
QuadRoot is the root of a single Quadtree. It is centred at the origin, and does not have a defined extent.
#include <geos/indexQuadtree.h>
Public Member Functions
Root ()
~Root () override
void insert (const geom::Envelope *itemEnv, void *item)
std::vector< void * > & getItems ()
void add (void *item)
std::vector< void * > & addAllItems (std::vector< void * > &resultItems) const
Push all node items to the given vector, return the argument.
virtual void addAllItemsFromOverlapping (const geom::Envelope &searchEnv, std::vector< void * > &resultItems) const
unsigned int depth () const
unsigned int size () const
unsigned int getNodeCount () const
virtual std::string toString () const
virtual void visit (const geom::Envelope *searchEnv, ItemVisitor &visitor)
bool remove (const geom::Envelope *itemEnv, void *item)
bool hasItems () const
bool hasChildren () const
bool isPrunable () const
Static Public Member Functions
static int getSubnodeIndex (const geom::Envelope *env, const geom::Coordinate &centre)
Protected Member Functions
bool isSearchMatch (const geom::Envelope &) const override
Protected Attributes
std::vector< void * > items
Actual items are NOT owned by this class.
Node * subnode [4]
Private Member Functions
void insertContained (Node *tree, const geom::Envelope *itemEnv, void *item)
Static Private Attributes
static const geom::Coordinate origin
Detailed Description
QuadRoot is the root of a single Quadtree. It is centred at the origin, and does not have a defined extent.
Definition at line 49 of file Root.h.
Constructor & Destructor Documentation
geos::index::quadtree::Root::Root () inline
Definition at line 66 of file Root.h.
 {}
geos::index::quadtree::Root::~Root () inline override
Definition at line 68 of file Root.h.
 {}
Member Function Documentation
void geos::index::quadtree::NodeBase::add (void * item) inherited
Add an item to this node. Ownership of the item is left to caller.
Definition at line 91 of file NodeBase.cpp.
Referenced by insertContained().
 {
   items.push_back(item);
   //GEOS_DEBUG itemCount++;
   //GEOS_DEBUG System.out.print(itemCount);
 }
vector< void * > & geos::index::quadtree::NodeBase::addAllItems (std::vector< void * > & resultItems) const inherited
Push all node items to the given vector, return the argument.
Definition at line 99 of file NodeBase.cpp.
 {
   // this node may have items as well as subnodes (since items may not
   // be wholely contained in any single subnode
   resultItems.insert(resultItems.end(), items.begin(), items.end());
   for(int i=0; i<4; ++i)
   {
     if ( subnode[i] )
     {
       subnode[i]->addAllItems(resultItems);
     }
   }
   return resultItems;
 }
void geos::index::quadtree::NodeBase::addAllItemsFromOverlapping (const geom::Envelope & searchEnv, std::vector< void * > & resultItems) const virtual inherited
Definition at line 116 of file NodeBase.cpp.
 {
   if (!isSearchMatch(searchEnv))
     return;
   // this node may have items as well as subnodes (since items may not
   // be wholely contained in any single subnode
   resultItems.insert(resultItems.end(), items.begin(), items.end());
   for(int i=0; i<4; ++i)
   {
     if ( subnode[i] )
     {
       subnode[i]->addAllItemsFromOverlapping(searchEnv,
                                              resultItems);
     }
   }
 }
unsigned int geos::index::quadtree::NodeBase::depth () const inherited
Definition at line 139 of file NodeBase.cpp.
 {
   unsigned int maxSubDepth=0;
   for (int i=0; i<4; ++i)
   {
     if (subnode[i] != nullptr)
     {
       unsigned int sqd=subnode[i]->depth();
       if ( sqd > maxSubDepth )
         maxSubDepth=sqd;
     }
   }
   return maxSubDepth + 1;
 }
vector< void * > & geos::index::quadtree::NodeBase::getItems () inherited
Definition at line 85 of file NodeBase.cpp.
 {
   return items;
 }
unsigned int geos::index::quadtree::NodeBase::getNodeCount () const inherited
Definition at line 169 of file NodeBase.cpp.
 {
   unsigned int subSize=0;
   for(int i=0; i<4; ++i)
   {
     if (subnode[i] != nullptr)
     {
       subSize += subnode[i]->size();
     }
   }
   return subSize + 1;
 }
int geos::index::quadtree::NodeBase::getSubnodeIndex (const geom::Envelope * env, const geom::Coordinate & centre) static inherited
Definition at line 47 of file NodeBase.cpp.
References geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), geos::geom::Coordinate::toString(), geos::geom::Envelope::toString(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   int subnodeIndex=-1;
   if (env->getMinX()>=centre.x) {
     if (env->getMinY()>=centre.y) subnodeIndex=3;
     if (env->getMaxY()<=centre.y) subnodeIndex=1;
   }
   if (env->getMaxX()<=centre.x) {
     if (env->getMinY()>=centre.y) subnodeIndex=2;
     if (env->getMaxY()<=centre.y) subnodeIndex=0;
   }
 #if GEOS_DEBUG
   cerr<<"getSubNodeIndex("<<env->toString()<<", "<<centre.toString()<<") returning "<<subnodeIndex<<endl;
 #endif
   return subnodeIndex;
 }
bool geos::index::quadtree::NodeBase::hasChildren () const inline inherited
Definition at line 131 of file NodeBase.h.
 {
   for (int i = 0; i < 4; i++)
     if (subnode[i]) return true;
   return false;
 }
bool geos::index::quadtree::NodeBase::hasItems () const inline inherited
Definition at line 145 of file NodeBase.h.
 {
   return ! items.empty();
 }
void geos::index::quadtree::Root::insert (const geom::Envelope * itemEnv, void * item)
Insert an item into the quadtree this is the root of.
Definition at line 48 of file Root.cpp.
References geos::geom::Envelope::contains(), geos::index::quadtree::Node::getEnvelope(), origin, and geos::geom::Envelope::toString().
 {
 #if GEOS_DEBUG
   std::cerr<< "Root("<<this<<")::insert("<<itemEnv->toString()<<", "<<item<<") called"<<std::endl;
 #endif
   int index = getSubnodeIndex(itemEnv, origin);
   // if index is -1, itemEnv must cross the X or Y axis.
   if (index==-1)
   {
 #if GEOS_DEBUG
   std::cerr<<"  -1 subnode index"<<std::endl;
 #endif
     add(item);
     return;
   }
   /*
    * the item must be contained in one quadrant, so insert it into the
    * tree for that quadrant (which may not yet exist)
    */
   Node *node = subnode[index];
 #if GEOS_DEBUG
   std::cerr<<"("<<this<<") subnode["<<index<<"] @ "<<node<<std::endl;
 #endif
   /*
    *  If the subquad doesn't exist or this item is not contained in it,
    *  have to expand the tree upward to contain the item.
    */
   if (node==nullptr || !node->getEnvelope()->contains(itemEnv))
   {
     std::unique_ptr<Node> snode (node); // may be NULL
     node = nullptr; subnode[index] = nullptr;
     std::unique_ptr<Node> largerNode =
       Node::createExpanded(std::move(snode), *itemEnv);
 #if GEOS_DEBUG
     std::cerr<<"("<<this<<") created expanded node " << largerNode.get() << " containing previously reported subnode" << std::endl;
 #endif
     // Previous subnode was passed as a child of the larger one
     assert(!subnode[index]);
     subnode[index] = largerNode.release();
   }
 #if GEOS_DEBUG
   std::cerr<<"("<<this<<") calling insertContained with subnode " << subnode[index] << std::endl;
 #endif
   /*
    * At this point we have a subquad which exists and must contain
    * contains the env for the item.  Insert the item into the tree.
    */
   insertContained(subnode[index], itemEnv, item);
 #if GEOS_DEBUG
   std::cerr<<"("<<this<<") done calling insertContained with subnode " << subnode[index] << std::endl;
 #endif
   //System.out.println("depth = " + root.depth() + " size = " + root.size());
   //System.out.println(" size = " + size());
 }
void geos::index::quadtree::Root::insertContained (Node * tree, const geom::Envelope * itemEnv, void * item) private
insert an item which is known to be contained in the tree rooted at the given QuadNode root. Lower levels of the tree will be created if necessary to hold the item.
Do NOT create a new quad for zero-area envelopes - this would lead to infinite recursion. Instead, use a heuristic of simply returning the smallest existing quad containing the query
Definition at line 115 of file Root.cpp.
References geos::index::quadtree::NodeBase::add(), geos::geom::Envelope::contains(), geos::index::quadtree::Node::find(), geos::index::quadtree::Node::getEnvelope(), geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), and geos::index::quadtree::Node::getNode().
 {
   assert(tree->getEnvelope()->contains(itemEnv));
   bool isZeroX = IntervalSize::isZeroWidth(itemEnv->getMinX(),
                                            itemEnv->getMaxX());
   bool isZeroY = IntervalSize::isZeroWidth(itemEnv->getMinY(),
                                            itemEnv->getMaxY());
   NodeBase *node;
   if (isZeroX || isZeroY)
   {
     node = tree->find(itemEnv);
   }
   else
   {
     node = tree->getNode(itemEnv);
   }
   node->add(item);
 }
bool geos::index::quadtree::NodeBase::isPrunable () const inline inherited
Definition at line 139 of file NodeBase.h.
 {
   return ! (hasChildren() || hasItems());
 }
bool geos::index::quadtree::Root::isSearchMatch (const geom::Envelope &) const inline override protected virtual
Implements geos::index::quadtree::NodeBase.
Definition at line 77 of file Root.h.
{
     return true;
   }
bool geos::index::quadtree::NodeBase::remove (const geom::Envelope * itemEnv, void * item) inherited
Removes a single item from this subtree.
Parameters
searchEnv the envelope containing the item
item the item to remove
Returns
true if the item was found and removed
Definition at line 232 of file NodeBase.cpp.
 {
   // use envelope to restrict nodes scanned
   if (! isSearchMatch(*itemEnv)) return false;
   bool found = false;
   for (int i = 0; i < 4; ++i)
   {
     if ( subnode[i] )
     {
       found = subnode[i]->remove(itemEnv, item);
       if (found)
       {
         // trim subtree if empty
         if (subnode[i]->isPrunable())
         {
           delete subnode[i];
           subnode[i] = nullptr;
         }
         break;
       }
     }
   }
   // if item was found lower down, don't need to search for it here
   if (found) return found;
   // otherwise, try and remove the item from the list of items
   // in this node
   vector<void*>::iterator foundIter =
     find(items.begin(), items.end(), item);
   if ( foundIter != items.end() ) {
     items.erase(foundIter);
     return true;
   } else {
     return false;
   }
 }
unsigned int geos::index::quadtree::NodeBase::size () const inherited
Definition at line 155 of file NodeBase.cpp.
 {
   unsigned int subSize=0;
   for(int i=0; i<4; i++)
   {
     if (subnode[i] != nullptr)
     {
       subSize += subnode[i]->size();
     }
   }
   return subSize + static_cast<unsigned int>(items.size());
 }
string geos::index::quadtree::NodeBase::toString (void) const virtual inherited
Reimplemented in geos::index::quadtree::Node.
Definition at line 184 of file NodeBase.cpp.
 {
   ostringstream s;
   s<<"ITEMS:"<<items.size()<<endl;
   for (int i=0; i<4; i++)
   {
     s<<"subnode["<<i<<"] ";
     if ( subnode[i] == nullptr ) s<<"NULL";
     else s<<subnode[i]->toString();
     s<<endl;
   }
   return s.str();
 }
void geos::index::quadtree::NodeBase::visit (const geom::Envelope * searchEnv, ItemVisitor & visitor) virtual inherited
Definition at line 200 of file NodeBase.cpp.
Referenced by geos::index::quadtree::Quadtree::query().
 {
   if (! isSearchMatch(*searchEnv)) return;
   // this node may have items as well as subnodes (since items may not
   // be wholely contained in any single subnode
   visitItems(searchEnv, visitor);
   for (int i = 0; i < 4; i++) {
     if (subnode[i] != nullptr) {
       subnode[i]->visit(searchEnv, visitor);
     }
   }
 }
Member Data Documentation
std::vector<void*> geos::index::quadtree::NodeBase::items protected inherited
Actual items are NOT owned by this class.
Definition at line 110 of file NodeBase.h.
const Coordinate geos::index::quadtree::Root::origin static private
Definition at line 54 of file Root.h.
Node* geos::index::quadtree::NodeBase::subnode[4] protected inherited
subquads are numbered as follows:
 2 | 3
 --+--
 0 | 1
Nodes are owned by this class
Definition at line 122 of file NodeBase.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/index/quadtree/Root.h
/home/vicky/potree/geos/vicky/src/index/quadtree/Root.cpp