GEOS: geos::operation::predicate::ContainsPointVisitor Class Reference
geos::operation::predicate::ContainsPointVisitor Class Reference
Public Member Functions
ContainsPointVisitor (const geom::Polygon &rect)
bool containsPoint ()
void applyTo (const Geometry &geom)
Protected Member Functions
void visit (const geom::Geometry &geom) override
bool isDone () override
Private Member Functions
ContainsPointVisitor (const ContainsPointVisitor &other)
ContainsPointVisitor & operator= (const ContainsPointVisitor &rhs)
Private Attributes
const geom::Envelope & rectEnv
bool containsPointVar
const geom::CoordinateSequence & rectSeq
Detailed Description
Tests whether it can be concluded that a geometry contains a corner point of a rectangle.
Definition at line 126 of file RectangleIntersects.cpp.
Constructor & Destructor Documentation
geos::operation::predicate::ContainsPointVisitor::ContainsPointVisitor (const ContainsPointVisitor & other) private
geos::operation::predicate::ContainsPointVisitor::ContainsPointVisitor (const geom::Polygon & rect) inline
Definition at line 181 of file RectangleIntersects.cpp.
     :
     rectEnv(*(rect.getEnvelopeInternal())),
     containsPointVar(false),
     rectSeq(*(rect.getExteriorRing()->getCoordinatesRO()))
     {}
Member Function Documentation
void geos::geom::util::ShortCircuitedGeometryVisitor::applyTo (const Geometry & geom) inherited
Definition at line 31 of file ShortCircuitedGeometryVisitor.cpp.
References geos::geom::Geometry::getGeometryN(), and geos::geom::Geometry::getNumGeometries().
Referenced by geos::operation::predicate::RectangleIntersects::intersects().
 {
   for (std::size_t i=0, n=geom.getNumGeometries(); i<n; ++i)
   {
     const Geometry *element = geom.getGeometryN(i);
     if (dynamic_cast<const GeometryCollection*>(element))
     {
       applyTo(*element);
     }
     else
     {
       // calls the abstract virtual
       visit(*element);
       if (isDone()) done = true;
     }
     if ( done ) return;
   }
 }
bool geos::operation::predicate::ContainsPointVisitor::containsPoint () inline
Definition at line 188 of file RectangleIntersects.cpp.
Referenced by geos::operation::predicate::RectangleIntersects::intersects().
 { return containsPointVar; }
bool geos::operation::predicate::ContainsPointVisitor::isDone () inline override protected virtual
Implements geos::geom::util::ShortCircuitedGeometryVisitor.
Definition at line 177 of file RectangleIntersects.cpp.
 { return containsPointVar; }
ContainsPointVisitor& geos::operation::predicate::ContainsPointVisitor::operator= (const ContainsPointVisitor & rhs) private
void geos::operation::predicate::ContainsPointVisitor::visit (const geom::Geometry & geom) inline override protected virtual
Implements geos::geom::util::ShortCircuitedGeometryVisitor.
Definition at line 140 of file RectangleIntersects.cpp.
References geos::geom::Envelope::contains(), geos::geom::CoordinateSequence::getAt(), geos::geom::Geometry::getEnvelopeInternal(), geos::geom::Envelope::intersects(), and poly.
   {
     using geos::algorithm::locate::SimplePointInAreaLocator;
     const geom::Polygon *poly;
     // if test geometry is not polygonal this check is not needed
     if ( nullptr == (poly=dynamic_cast<const geom::Polygon *>(&geom)) ) {
       return;
     }
     const geom::Envelope &elementEnv = *(geom.getEnvelopeInternal());
     if ( !rectEnv.intersects(elementEnv) ) {
       return;
     }
     // test each corner of rectangle for inclusion
     for (int i=0; i<4; i++)
     {
       const geom::Coordinate &rectPt=rectSeq.getAt(i);
       if ( !elementEnv.contains(rectPt) ) {
         continue;
       }
       // check rect point in poly (rect is known not to
       // touch polygon at this point)
       if ( SimplePointInAreaLocator::containsPointInPolygon(rectPt, poly) )
       {
         containsPointVar=true;
         return;
       }
     }
   }
Member Data Documentation
bool geos::operation::predicate::ContainsPointVisitor::containsPointVar private
Definition at line 131 of file RectangleIntersects.cpp.
const geom::Envelope& geos::operation::predicate::ContainsPointVisitor::rectEnv private
Definition at line 130 of file RectangleIntersects.cpp.
const geom::CoordinateSequence& geos::operation::predicate::ContainsPointVisitor::rectSeq private
Definition at line 132 of file RectangleIntersects.cpp.
The documentation for this class was generated from the following file:
/home/vicky/potree/geos/vicky/src/operation/predicate/RectangleIntersects.cpp