GEOS: geos::algorithm::CentroidLine Class Reference
geos::algorithm::CentroidLine Class Reference
#include <CentroidLine.h>
Public Member Functions
CentroidLine ()
~CentroidLine ()
void add (const geom::Geometry *geom)
Adds the linestring(s) defined by a Geometry to the centroid total.
void add (const geom::CoordinateSequence *pts)
Adds the length defined by an array of coordinates.
geom::Coordinate * getCentroid () const
bool getCentroid (geom::Coordinate &ret) const
return false if centroid could not be computed
Private Attributes
geom::Coordinate centSum
double totalLength
Detailed Description
Deprecated:
use Centroid instead
Definition at line 35 of file CentroidLine.h.
Constructor & Destructor Documentation
geos::algorithm::CentroidLine::CentroidLine () inline
Definition at line 44 of file CentroidLine.h.
     :
     centSum(0.0, 0.0),
     totalLength(0.0)
   {}
geos::algorithm::CentroidLine::~CentroidLine () inline
Definition at line 50 of file CentroidLine.h.
 {}
Member Function Documentation
void geos::algorithm::CentroidLine::add (const geom::Geometry * geom)
Adds the linestring(s) defined by a Geometry to the centroid total.
If the geometry is not linear it does not contribute to the centroid
Parameters
geom the geometry to add
Definition at line 34 of file CentroidLine.cpp.
References geos::geom::LineString::getCoordinatesRO(), geos::geom::GeometryCollection::getGeometryN(), and geos::geom::GeometryCollection::getNumGeometries().
 {
   const LineString* ls = dynamic_cast<const LineString*>(geom);
   if ( ls )
   {
     add(ls->getCoordinatesRO());
     return;
   }
   const GeometryCollection* gc = dynamic_cast<const GeometryCollection*>(geom);
   if (gc)
   {
         for(std::size_t i=0, n=gc->getNumGeometries(); i<n; i++) {
       add(gc->getGeometryN(i));
     }
   }
 }
void geos::algorithm::CentroidLine::add (const geom::CoordinateSequence * pts)
Adds the length defined by an array of coordinates.
Parameters
pts an array of geom::Coordinates
Definition at line 54 of file CentroidLine.cpp.
References geos::geom::Coordinate::distance(), geos::geom::CoordinateSequence::getAt(), geos::geom::CoordinateSequence::getSize(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   std::size_t const npts=pts->getSize();
   for(std::size_t i=1; i<npts; ++i)
   {
     const Coordinate &p1=pts->getAt(i-1);
     const Coordinate &p2=pts->getAt(i);
     double segmentLen=p1.distance(p2);
     totalLength+=segmentLen;
     double midx=(p1.x+p2.x)/2;
     centSum.x+=segmentLen*midx;
     double midy=(p1.y+p2.y)/2;
     centSum.y+=segmentLen*midy;
   }
 }
Coordinate * geos::algorithm::CentroidLine::getCentroid () const
Definition at line 73 of file CentroidLine.cpp.
 {
   return new Coordinate(centSum.x/totalLength, centSum.y/totalLength);
 }
bool geos::algorithm::CentroidLine::getCentroid (geom::Coordinate & ret) const
return false if centroid could not be computed
Definition at line 79 of file CentroidLine.cpp.
 {
   if ( totalLength == 0.0 ) return false;
   c=Coordinate(centSum.x/totalLength, centSum.y/totalLength);
   return true;
 }
Member Data Documentation
geom::Coordinate geos::algorithm::CentroidLine::centSum private
Definition at line 38 of file CentroidLine.h.
double geos::algorithm::CentroidLine::totalLength private
Definition at line 40 of file CentroidLine.h.
The documentation for this class was generated from the following files:
/home/vicky/potree/geos/vicky/include/geos/algorithm/CentroidLine.h
/home/vicky/potree/geos/vicky/src/algorithm/CentroidLine.cpp