GEOS: /home/vicky/potree/geos/vicky/capi/geos_c.cpp File Reference
geos_c.cpp File Reference
#include <geos/geom/prep/PreparedGeometryFactory.h>
#include <geos/index/strtree/STRtree.h>
#include <geos/io/WKTReader.h>
#include <geos/io/WKBReader.h>
#include <geos/io/WKTWriter.h>
#include <geos/io/WKBWriter.h>
#include <geos/operation/overlay/OverlayOp.h>
#include <geos/operation/union/CascadedPolygonUnion.h>
#include <geos/algorithm/distance/DiscreteHausdorffDistance.h>
#include <geos/algorithm/distance/DiscreteFrechetDistance.h>
#include <geos/util/Interrupt.h>
#include <stdexcept>
#include <new>
#include "geos_c.h"
#include <geos/export.h>
Macros
#define GEOSGeometry geos::geom::Geometry
#define GEOSPreparedGeometry geos::geom::prep::PreparedGeometry
#define GEOSCoordSequence geos::geom::CoordinateSequence
#define GEOSSTRtree geos::index::strtree::STRtree
#define GEOSWKTReader_t geos::io::WKTReader
#define GEOSWKTWriter_t geos::io::WKTWriter
#define GEOSWKBReader_t geos::io::WKBReader
#define GEOSWKBWriter_t geos::io::WKBWriter
Typedefs
typedef struct GEOSBufParams_t GEOSBufferParams
typedef std::unique_ptr< Geometry > GeomPtr
Functions
void initGEOS (GEOSMessageHandler nf, GEOSMessageHandler ef)
void finishGEOS ()
GEOSInterruptCallback * GEOS_interruptRegisterCallback (GEOSInterruptCallback *cb)
void GEOS_interruptRequest ()
void GEOS_interruptCancel ()
void GEOSFree (void *buffer)
char GEOSDisjoint (const Geometry *g1, const Geometry *g2)
char GEOSTouches (const Geometry *g1, const Geometry *g2)
char GEOSIntersects (const Geometry *g1, const Geometry *g2)
char GEOSCrosses (const Geometry *g1, const Geometry *g2)
char GEOSWithin (const Geometry *g1, const Geometry *g2)
char GEOSContains (const Geometry *g1, const Geometry *g2)
char GEOSOverlaps (const Geometry *g1, const Geometry *g2)
char GEOSCovers (const Geometry *g1, const Geometry *g2)
char GEOSCoveredBy (const Geometry *g1, const Geometry *g2)
char GEOSRelatePattern (const Geometry *g1, const Geometry *g2, const char *pat)
char GEOSRelatePatternMatch (const char *mat, const char *pat)
char * GEOSRelate (const Geometry *g1, const Geometry *g2)
char * GEOSRelateBoundaryNodeRule (const Geometry *g1, const Geometry *g2, int bnr)
char GEOSisValid (const Geometry *g)
char * GEOSisValidReason (const Geometry *g)
char GEOSisValidDetail (const Geometry *g, int flags, char **reason, Geometry **location)
char GEOSEquals (const Geometry *g1, const Geometry *g2)
char GEOSEqualsExact (const Geometry *g1, const Geometry *g2, double tolerance)
int GEOSDistance (const Geometry *g1, const Geometry *g2, double *dist)
int GEOSDistanceIndexed (const Geometry *g1, const Geometry *g2, double *dist)
int GEOSHausdorffDistance (const Geometry *g1, const Geometry *g2, double *dist)
int GEOSHausdorffDistanceDensify (const Geometry *g1, const Geometry *g2, double densifyFrac, double *dist)
int GEOSFrechetDistance (const Geometry *g1, const Geometry *g2, double *dist)
int GEOSFrechetDistanceDensify (const Geometry *g1, const Geometry *g2, double densifyFrac, double *dist)
int GEOSArea (const Geometry *g, double *area)
int GEOSLength (const Geometry *g, double *length)
CoordinateSequence * GEOSNearestPoints (const Geometry *g1, const Geometry *g2)
Geometry * GEOSGeomFromWKT (const char *wkt)
char * GEOSGeomToWKT (const Geometry *g)
unsigned char * GEOSGeomToWKB_buf (const Geometry *g, size_t *size)
Geometry * GEOSGeomFromWKB_buf (const unsigned char *wkb, size_t size)
unsigned char * GEOSGeomToHEX_buf (const Geometry *g, size_t *size)
Geometry * GEOSGeomFromHEX_buf (const unsigned char *hex, size_t size)
char GEOSisEmpty (const Geometry *g)
char GEOSisSimple (const Geometry *g)
char GEOSisRing (const Geometry *g)
char * GEOSGeomType (const Geometry *g)
int GEOSGeomTypeId (const Geometry *g)
Geometry * GEOSEnvelope (const Geometry *g)
Geometry * GEOSIntersection (const Geometry *g1, const Geometry *g2)
Geometry * GEOSBuffer (const Geometry *g, double width, int quadrantsegments)
Geometry * GEOSBufferWithStyle (const Geometry *g, double width, int quadsegs, int endCapStyle, int joinStyle, double mitreLimit)
Geometry * GEOSSingleSidedBuffer (const Geometry *g, double width, int quadsegs, int joinStyle, double mitreLimit, int leftSide)
Geometry * GEOSOffsetCurve (const Geometry *g, double width, int quadsegs, int joinStyle, double mitreLimit)
Geometry * GEOSConvexHull (const Geometry *g)
Geometry * GEOSMinimumRotatedRectangle (const Geometry *g)
Geometry * GEOSMinimumWidth (const Geometry *g)
Geometry * GEOSMinimumClearanceLine (const Geometry *g)
int GEOSMinimumClearance (const Geometry *g, double *d)
Geometry * GEOSDifference (const Geometry *g1, const Geometry *g2)
Geometry * GEOSBoundary (const Geometry *g)
Geometry * GEOSSymDifference (const Geometry *g1, const Geometry *g2)
Geometry * GEOSUnion (const Geometry *g1, const Geometry *g2)
Geometry * GEOSUnaryUnion (const Geometry *g)
Geometry * GEOSNode (const Geometry *g)
Geometry * GEOSUnionCascaded (const Geometry *g)
Geometry * GEOSPointOnSurface (const Geometry *g)
Geometry * GEOSClipByRect (const Geometry *g, double xmin, double ymin, double xmax, double ymax)
void GEOSGeom_destroy (Geometry *a)
int GEOSGetNumCoordinates (const Geometry *g)
int GEOSNormalize (Geometry *g)
int GEOSGetNumInteriorRings (const Geometry *g)
int GEOSGetNumGeometries (const Geometry *g)
const Geometry * GEOSGetGeometryN (const Geometry *g, int n)
Geometry * GEOSGeomGetPointN (const Geometry *g, int n)
Geometry * GEOSGeomGetStartPoint (const Geometry *g)
Geometry * GEOSGeomGetEndPoint (const Geometry *g)
char GEOSisClosed (const Geometry *g)
int GEOSGeomGetLength (const Geometry *g, double *length)
int GEOSGeomGetNumPoints (const Geometry *g)
int GEOSGeomGetX (const Geometry *g, double *x)
int GEOSGeomGetY (const Geometry *g, double *y)
int GEOSGeomGetZ (const Geometry *g1, double *z)
const Geometry * GEOSGetExteriorRing (const Geometry *g)
const Geometry * GEOSGetInteriorRingN (const Geometry *g, int n)
Geometry * GEOSGetCentroid (const Geometry *g)
Geometry * GEOSGeom_createCollection (int type, Geometry **geoms, unsigned int ngeoms)
Geometry * GEOSPolygonize (const Geometry *const *g, unsigned int ngeoms)
Geometry * GEOSPolygonizer_getCutEdges (const Geometry *const *g, unsigned int ngeoms)
GEOSGeometry * GEOSPolygonize_full (const GEOSGeometry *input, GEOSGeometry **cuts, GEOSGeometry **dangles, GEOSGeometry **invalid)
Geometry * GEOSLineMerge (const Geometry *g)
Geometry * GEOSReverse (const Geometry *g)
int GEOSGetSRID (const Geometry *g)
void GEOSSetSRID (Geometry *g, int srid)
void * GEOSGeom_getUserData (const Geometry *g)
void GEOSGeom_setUserData (Geometry *g, void *userData)
char GEOSHasZ (const Geometry *g)
int GEOS_getWKBOutputDims ()
int GEOS_setWKBOutputDims (int newdims)
int GEOS_getWKBByteOrder ()
int GEOS_setWKBByteOrder (int byteOrder)
CoordinateSequence * GEOSCoordSeq_create (unsigned int size, unsigned int dims)
int GEOSCoordSeq_setOrdinate (CoordinateSequence *s, unsigned int idx, unsigned int dim, double val)
int GEOSCoordSeq_setX (CoordinateSequence *s, unsigned int idx, double val)
int GEOSCoordSeq_setY (CoordinateSequence *s, unsigned int idx, double val)
int GEOSCoordSeq_setZ (CoordinateSequence *s, unsigned int idx, double val)
CoordinateSequence * GEOSCoordSeq_clone (const CoordinateSequence *s)
int GEOSCoordSeq_getOrdinate (const CoordinateSequence *s, unsigned int idx, unsigned int dim, double *val)
int GEOSCoordSeq_getX (const CoordinateSequence *s, unsigned int idx, double *val)
int GEOSCoordSeq_getY (const CoordinateSequence *s, unsigned int idx, double *val)
int GEOSCoordSeq_getZ (const CoordinateSequence *s, unsigned int idx, double *val)
int GEOSCoordSeq_getSize (const CoordinateSequence *s, unsigned int *size)
int GEOSCoordSeq_getDimensions (const CoordinateSequence *s, unsigned int *dims)
int GEOSCoordSeq_isCCW (const CoordinateSequence *s, char *is_ccw)
void GEOSCoordSeq_destroy (CoordinateSequence *s)
const CoordinateSequence * GEOSGeom_getCoordSeq (const Geometry *g)
Geometry * GEOSGeom_createPoint (CoordinateSequence *cs)
Geometry * GEOSGeom_createLinearRing (CoordinateSequence *cs)
Geometry * GEOSGeom_createLineString (CoordinateSequence *cs)
Geometry * GEOSGeom_createPolygon (Geometry *shell, Geometry **holes, unsigned int nholes)
Geometry * GEOSGeom_clone (const Geometry *g)
GEOSGeometry * GEOSGeom_setPrecision (const GEOSGeometry *g, double gridSize, int flags)
double GEOSGeom_getPrecision (const GEOSGeometry *g)
int GEOSGeom_getDimensions (const Geometry *g)
int GEOSGeom_getCoordinateDimension (const Geometry *g)
int GEOS_DLL GEOSGeom_getXMin (const GEOSGeometry *g, double *value)
int GEOS_DLL GEOSGeom_getYMin (const GEOSGeometry *g, double *value)
int GEOS_DLL GEOSGeom_getXMax (const GEOSGeometry *g, double *value)
int GEOS_DLL GEOSGeom_getYMax (const GEOSGeometry *g, double *value)
Geometry * GEOSSimplify (const Geometry *g, double tolerance)
Geometry * GEOSTopologyPreserveSimplify (const Geometry *g, double tolerance)
WKTReader * GEOSWKTReader_create ()
void GEOSWKTReader_destroy (WKTReader *reader)
Geometry * GEOSWKTReader_read (WKTReader *reader, const char *wkt)
WKTWriter * GEOSWKTWriter_create ()
void GEOSWKTWriter_destroy (WKTWriter *Writer)
char * GEOSWKTWriter_write (WKTWriter *writer, const Geometry *geom)
void GEOSWKTWriter_setTrim (WKTWriter *writer, char trim)
void GEOSWKTWriter_setRoundingPrecision (WKTWriter *writer, int precision)
void GEOSWKTWriter_setOutputDimension (WKTWriter *writer, int dim)
int GEOSWKTWriter_getOutputDimension (WKTWriter *writer)
void GEOSWKTWriter_setOld3D (WKTWriter *writer, int useOld3D)
WKBReader * GEOSWKBReader_create ()
void GEOSWKBReader_destroy (WKBReader *reader)
Geometry * GEOSWKBReader_read (WKBReader *reader, const unsigned char *wkb, size_t size)
Geometry * GEOSWKBReader_readHEX (WKBReader *reader, const unsigned char *hex, size_t size)
WKBWriter * GEOSWKBWriter_create ()
void GEOSWKBWriter_destroy (WKBWriter *Writer)
unsigned char * GEOSWKBWriter_write (WKBWriter *writer, const Geometry *geom, size_t *size)
unsigned char * GEOSWKBWriter_writeHEX (WKBWriter *writer, const Geometry *geom, size_t *size)
int GEOSWKBWriter_getOutputDimension (const GEOSWKBWriter *writer)
void GEOSWKBWriter_setOutputDimension (GEOSWKBWriter *writer, int newDimension)
int GEOSWKBWriter_getByteOrder (const GEOSWKBWriter *writer)
void GEOSWKBWriter_setByteOrder (GEOSWKBWriter *writer, int newByteOrder)
char GEOSWKBWriter_getIncludeSRID (const GEOSWKBWriter *writer)
void GEOSWKBWriter_setIncludeSRID (GEOSWKBWriter *writer, const char newIncludeSRID)
const geos::geom::prep::PreparedGeometry * GEOSPrepare (const Geometry *g)
void GEOSPreparedGeom_destroy (const geos::geom::prep::PreparedGeometry *a)
char GEOSPreparedContains (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
char GEOSPreparedContainsProperly (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
char GEOSPreparedCoveredBy (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
char GEOSPreparedCovers (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
char GEOSPreparedCrosses (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
char GEOSPreparedDisjoint (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
char GEOSPreparedIntersects (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
char GEOSPreparedOverlaps (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
char GEOSPreparedTouches (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
char GEOSPreparedWithin (const geos::geom::prep::PreparedGeometry *pg1, const Geometry *g2)
STRtree * GEOSSTRtree_create (size_t nodeCapacity)
void GEOSSTRtree_insert (geos::index::strtree::STRtree *tree, const geos::geom::Geometry *g, void *item)
void GEOSSTRtree_query (geos::index::strtree::STRtree *tree, const geos::geom::Geometry *g, GEOSQueryCallback cb, void *userdata)
const GEOSGeometry * GEOSSTRtree_nearest (geos::index::strtree::STRtree *tree, const geos::geom::Geometry *g)
const void * GEOSSTRtree_nearest_generic (GEOSSTRtree *tree, const void *item, const GEOSGeometry *itemEnvelope, GEOSDistanceCallback distancefn, void *userdata)
void GEOSSTRtree_iterate (geos::index::strtree::STRtree *tree, GEOSQueryCallback callback, void *userdata)
char GEOSSTRtree_remove (geos::index::strtree::STRtree *tree, const geos::geom::Geometry *g, void *item)
void GEOSSTRtree_destroy (geos::index::strtree::STRtree *tree)
double GEOSProject (const geos::geom::Geometry *g, const geos::geom::Geometry *p)
geos::geom::Geometry * GEOSInterpolate (const geos::geom::Geometry *g, double d)
double GEOSProjectNormalized (const geos::geom::Geometry *g, const geos::geom::Geometry *p)
geos::geom::Geometry * GEOSInterpolateNormalized (const geos::geom::Geometry *g, double d)
geos::geom::Geometry * GEOSGeom_extractUniquePoints (const geos::geom::Geometry *g)
geos::geom::Geometry * GEOSGeom_createEmptyCollection (int type)
geos::geom::Geometry * GEOSGeom_createEmptyPoint ()
geos::geom::Geometry * GEOSGeom_createEmptyLineString ()
geos::geom::Geometry * GEOSGeom_createEmptyPolygon ()
int GEOSOrientationIndex (double Ax, double Ay, double Bx, double By, double Px, double Py)
GEOSGeometry * GEOSSharedPaths (const GEOSGeometry *g1, const GEOSGeometry *g2)
GEOSGeometry * GEOSSnap (const GEOSGeometry *g1, const GEOSGeometry *g2, double tolerance)
GEOSBufferParams * GEOSBufferParams_create ()
void GEOSBufferParams_destroy (GEOSBufferParams *p)
int GEOSBufferParams_setEndCapStyle (GEOSBufferParams *p, int style)
int GEOSBufferParams_setJoinStyle (GEOSBufferParams *p, int joinStyle)
int GEOSBufferParams_setMitreLimit (GEOSBufferParams *p, double l)
int GEOSBufferParams_setQuadrantSegments (GEOSBufferParams *p, int joinStyle)
int GEOSBufferParams_setSingleSided (GEOSBufferParams *p, int singleSided)
Geometry * GEOSBufferWithParams (const Geometry *g, const GEOSBufferParams *p, double w)
Geometry * GEOSDelaunayTriangulation (const Geometry *g, double tolerance, int onlyEdges)
Geometry * GEOSVoronoiDiagram (const Geometry *g, const Geometry *env, double tolerance, int onlyEdges)
int GEOSSegmentIntersection (double ax0, double ay0, double ax1, double ay1, double bx0, double by0, double bx1, double by1, double *cx, double *cy)
Variables
GEOSContextHandle_t handle = NULL
Macro Definition Documentation
#define GEOSCoordSequence geos::geom::CoordinateSequence
Definition at line 40 of file geos_c.cpp.
#define GEOSGeometry geos::geom::Geometry
Definition at line 38 of file geos_c.cpp.
Referenced by GEOSGeom_clone(), GEOSOrientationIndex(), GEOSPolygonizer_getCutEdges(), GEOSSharedPaths(), and GEOSSTRtree_query().
#define GEOSPreparedGeometry geos::geom::prep::PreparedGeometry
Definition at line 39 of file geos_c.cpp.
#define GEOSSTRtree geos::index::strtree::STRtree
Definition at line 41 of file geos_c.cpp.
#define GEOSWKBReader_t geos::io::WKBReader
Definition at line 44 of file geos_c.cpp.
#define GEOSWKBWriter_t geos::io::WKBWriter
Definition at line 45 of file geos_c.cpp.
#define GEOSWKTReader_t geos::io::WKTReader
Definition at line 42 of file geos_c.cpp.
#define GEOSWKTWriter_t geos::io::WKTWriter
Definition at line 43 of file geos_c.cpp.
Typedef Documentation
typedef std::unique_ptr<Geometry> GeomPtr
Definition at line 83 of file geos_c.cpp.
typedef struct GEOSBufParams_t GEOSBufferParams
Definition at line 46 of file geos_c.cpp.
Function Documentation
void finishGEOS ()
Definition at line 109 of file geos_c.cpp.
References finishGEOS_r(), and handle.
 {
     if (handle != NULL) {
         finishGEOS_r( handle );
         handle = NULL;
     }
 }
int GEOS_getWKBByteOrder ()
Definition at line 784 of file geos_c.cpp.
References GEOS_getWKBByteOrder_r(), and handle.
 {
   return GEOS_getWKBByteOrder_r( handle );
 }
int GEOS_getWKBOutputDims ()
Definition at line 772 of file geos_c.cpp.
References GEOS_getWKBOutputDims_r(), and handle.
 {
     return GEOS_getWKBOutputDims_r( handle );
 }
void GEOS_interruptCancel ()
Definition at line 130 of file geos_c.cpp.
References geos::util::Interrupt::cancel().
 {
   geos::util::Interrupt::cancel();
 }
GEOSInterruptCallback* GEOS_interruptRegisterCallback (GEOSInterruptCallback * cb)
Definition at line 118 of file geos_c.cpp.
References geos::util::Interrupt::registerCallback().
 {
   return geos::util::Interrupt::registerCallback(cb);
 }
void GEOS_interruptRequest ()
Definition at line 124 of file geos_c.cpp.
References geos::util::Interrupt::request().
 {
   geos::util::Interrupt::request();
 }
int GEOS_setWKBByteOrder (int byteOrder)
Definition at line 790 of file geos_c.cpp.
References GEOS_setWKBByteOrder_r(), and handle.
 {
   return GEOS_setWKBByteOrder_r( handle, byteOrder );
 }
int GEOS_setWKBOutputDims (int newdims)
Definition at line 778 of file geos_c.cpp.
References GEOS_setWKBOutputDims_r(), and handle.
 {
     return GEOS_setWKBOutputDims_r( handle, newdims );
 }
int GEOSArea (const Geometry * g, double * area)
Definition at line 311 of file geos_c.cpp.
References GEOSArea_r(), and handle.
 {
     return GEOSArea_r( handle, g, area );
 }
Geometry* GEOSBoundary (const Geometry * g)
Definition at line 487 of file geos_c.cpp.
References GEOSBoundary_r(), and handle.
 {
     return GEOSBoundary_r( handle, g );
 }
Geometry* GEOSBuffer (const Geometry * g, double width, int quadrantsegments)
Definition at line 421 of file geos_c.cpp.
References GEOSBuffer_r(), and handle.
 {
     return GEOSBuffer_r( handle, g, width, quadrantsegments );
 }
GEOSBufferParams* GEOSBufferParams_create ()
Definition at line 1348 of file geos_c.cpp.
References GEOSBufferParams_create_r(), and handle.
 {
   return GEOSBufferParams_create_r(handle);
 }
void GEOSBufferParams_destroy (GEOSBufferParams * p)
Definition at line 1354 of file geos_c.cpp.
References GEOSBufferParams_destroy_r(), and handle.
 {
   return GEOSBufferParams_destroy_r(handle, p);
 }
int GEOSBufferParams_setEndCapStyle (GEOSBufferParams * p, int style)
Definition at line 1360 of file geos_c.cpp.
References GEOSBufferParams_setEndCapStyle_r(), and handle.
 {
   return GEOSBufferParams_setEndCapStyle_r(handle, p, style);
 }
int GEOSBufferParams_setJoinStyle (GEOSBufferParams * p, int joinStyle)
Definition at line 1366 of file geos_c.cpp.
References GEOSBufferParams_setJoinStyle_r(), and handle.
 {
   return GEOSBufferParams_setJoinStyle_r(handle, p, joinStyle);
 }
int GEOSBufferParams_setMitreLimit (GEOSBufferParams * p, double l)
Definition at line 1372 of file geos_c.cpp.
References GEOSBufferParams_setMitreLimit_r(), and handle.
 {
   return GEOSBufferParams_setMitreLimit_r(handle, p, l);
 }
int GEOSBufferParams_setQuadrantSegments (GEOSBufferParams * p, int joinStyle)
Definition at line 1378 of file geos_c.cpp.
References GEOSBufferParams_setQuadrantSegments_r(), and handle.
 {
   return GEOSBufferParams_setQuadrantSegments_r(handle, p, joinStyle);
 }
int GEOSBufferParams_setSingleSided (GEOSBufferParams * p, int singleSided)
Definition at line 1384 of file geos_c.cpp.
References GEOSBufferParams_setSingleSided_r(), and handle.
 {
   return GEOSBufferParams_setSingleSided_r(handle, p, singleSided);
 }
Geometry* GEOSBufferWithParams (const Geometry * g, const GEOSBufferParams * p, double w)
Definition at line 1390 of file geos_c.cpp.
References GEOSBufferWithParams_r(), and handle.
 {
   return GEOSBufferWithParams_r(handle, g, p, w);
 }
Geometry* GEOSBufferWithStyle (const Geometry * g, double width, int quadsegs, int endCapStyle, int joinStyle, double mitreLimit)
Definition at line 427 of file geos_c.cpp.
References GEOSBufferWithStyle_r(), and handle.
 {
     return GEOSBufferWithStyle_r( handle, g, width, quadsegs, endCapStyle,
                                joinStyle, mitreLimit );
 }
Geometry* GEOSClipByRect (const Geometry * g, double xmin, double ymin, double xmax, double ymax)
Definition at line 530 of file geos_c.cpp.
References GEOSClipByRect_r(), and handle.
 {
     return GEOSClipByRect_r( handle, g, xmin, ymin, xmax, ymax );
 }
char GEOSContains (const Geometry * g1, const Geometry * g2)
Definition at line 181 of file geos_c.cpp.
References GEOSContains_r(), and handle.
 {
     return GEOSContains_r( handle, g1, g2 );
 }
Geometry* GEOSConvexHull (const Geometry * g)
Definition at line 451 of file geos_c.cpp.
References GEOSConvexHull_r(), and handle.
 {
     return GEOSConvexHull_r( handle, g );
 }
CoordinateSequence* GEOSCoordSeq_clone (const CoordinateSequence * s)
Definition at line 827 of file geos_c.cpp.
References GEOSCoordSeq_clone_r(), and handle.
 {
     return GEOSCoordSeq_clone_r( handle, s );
 }
CoordinateSequence* GEOSCoordSeq_create (unsigned int size, unsigned int dims)
Definition at line 797 of file geos_c.cpp.
References GEOSCoordSeq_create_r(), and handle.
 {
     return GEOSCoordSeq_create_r( handle, size, dims );
 }
void GEOSCoordSeq_destroy (CoordinateSequence * s)
Definition at line 875 of file geos_c.cpp.
References GEOSCoordSeq_destroy_r(), and handle.
 {
     return GEOSCoordSeq_destroy_r( handle, s );
 }
int GEOSCoordSeq_getDimensions (const CoordinateSequence * s, unsigned int * dims)
Definition at line 863 of file geos_c.cpp.
References GEOSCoordSeq_getDimensions_r(), and handle.
 {
     return GEOSCoordSeq_getDimensions_r( handle, s, dims );
 }
int GEOSCoordSeq_getOrdinate (const CoordinateSequence * s, unsigned int idx, unsigned int dim, double * val)
Definition at line 833 of file geos_c.cpp.
References GEOSCoordSeq_getOrdinate_r(), and handle.
Referenced by GEOSCoordSeq_getX(), GEOSCoordSeq_getY(), and GEOSCoordSeq_getZ().
 {
     return GEOSCoordSeq_getOrdinate_r( handle, s, idx, dim, val );
 }
int GEOSCoordSeq_getSize (const CoordinateSequence * s, unsigned int * size)
Definition at line 857 of file geos_c.cpp.
References GEOSCoordSeq_getSize_r(), and handle.
 {
     return GEOSCoordSeq_getSize_r( handle, s, size );
 }
int GEOSCoordSeq_getX (const CoordinateSequence * s, unsigned int idx, double * val)
Definition at line 839 of file geos_c.cpp.
References GEOSCoordSeq_getOrdinate().
 {
   return GEOSCoordSeq_getOrdinate(s, idx, 0, val);
 }
int GEOSCoordSeq_getY (const CoordinateSequence * s, unsigned int idx, double * val)
Definition at line 845 of file geos_c.cpp.
References GEOSCoordSeq_getOrdinate().
 {
   return GEOSCoordSeq_getOrdinate(s, idx, 1, val);
 }
int GEOSCoordSeq_getZ (const CoordinateSequence * s, unsigned int idx, double * val)
Definition at line 851 of file geos_c.cpp.
References GEOSCoordSeq_getOrdinate().
 {
   return GEOSCoordSeq_getOrdinate(s, idx, 2, val);
 }
int GEOSCoordSeq_isCCW (const CoordinateSequence * s, char * is_ccw)
Definition at line 869 of file geos_c.cpp.
References GEOSCoordSeq_isCCW_r(), and handle.
 {
     return GEOSCoordSeq_isCCW_r(handle, s, is_ccw);
 }
int GEOSCoordSeq_setOrdinate (CoordinateSequence * s, unsigned int idx, unsigned int dim, double val)
Definition at line 803 of file geos_c.cpp.
References GEOSCoordSeq_setOrdinate_r(), and handle.
Referenced by GEOSCoordSeq_setX(), GEOSCoordSeq_setY(), and GEOSCoordSeq_setZ().
 {
     return GEOSCoordSeq_setOrdinate_r( handle, s, idx, dim, val );
 }
int GEOSCoordSeq_setX (CoordinateSequence * s, unsigned int idx, double val)
Definition at line 809 of file geos_c.cpp.
References GEOSCoordSeq_setOrdinate().
 {
   return GEOSCoordSeq_setOrdinate(s, idx, 0, val);
 }
int GEOSCoordSeq_setY (CoordinateSequence * s, unsigned int idx, double val)
Definition at line 815 of file geos_c.cpp.
References GEOSCoordSeq_setOrdinate().
 {
   return GEOSCoordSeq_setOrdinate(s, idx, 1, val);
 }
int GEOSCoordSeq_setZ (CoordinateSequence * s, unsigned int idx, double val)
Definition at line 821 of file geos_c.cpp.
References GEOSCoordSeq_setOrdinate().
 {
   return GEOSCoordSeq_setOrdinate(s, idx, 2, val);
 }
char GEOSCoveredBy (const Geometry * g1, const Geometry * g2)
Definition at line 199 of file geos_c.cpp.
References GEOSCoveredBy_r(), and handle.
 {
     return GEOSCoveredBy_r( handle, g1, g2 );
 }
char GEOSCovers (const Geometry * g1, const Geometry * g2)
Definition at line 193 of file geos_c.cpp.
References GEOSCovers_r(), and handle.
 {
     return GEOSCovers_r( handle, g1, g2 );
 }
char GEOSCrosses (const Geometry * g1, const Geometry * g2)
Definition at line 165 of file geos_c.cpp.
References GEOSCrosses_r(), and handle.
 {
     return GEOSCrosses_r( handle, g1, g2 );
 }
Geometry* GEOSDelaunayTriangulation (const Geometry * g, double tolerance, int onlyEdges)
Definition at line 1396 of file geos_c.cpp.
References GEOSDelaunayTriangulation_r(), and handle.
 {
   return GEOSDelaunayTriangulation_r(handle, g, tolerance, onlyEdges);
 }
Geometry* GEOSDifference (const Geometry * g1, const Geometry * g2)
Definition at line 481 of file geos_c.cpp.
References GEOSDifference_r(), and handle.
 {
     return GEOSDifference_r( handle, g1, g2 );
 }
char GEOSDisjoint (const Geometry * g1, const Geometry * g2)
Definition at line 147 of file geos_c.cpp.
References GEOSDisjoint_r(), and handle.
 {
     return GEOSDisjoint_r( handle, g1, g2 );
 }
int GEOSDistance (const Geometry * g1, const Geometry * g2, double * dist)
Definition at line 275 of file geos_c.cpp.
References GEOSDistance_r(), and handle.
 {
     return GEOSDistance_r( handle, g1, g2, dist );
 }
int GEOSDistanceIndexed (const Geometry * g1, const Geometry * g2, double * dist)
Definition at line 281 of file geos_c.cpp.
References GEOSDistanceIndexed_r(), and handle.
 {
     return GEOSDistanceIndexed_r( handle, g1, g2, dist );
 }
Geometry* GEOSEnvelope (const Geometry * g)
Definition at line 409 of file geos_c.cpp.
References GEOSEnvelope_r(), and handle.
 {
     return GEOSEnvelope_r( handle, g );
 }
char GEOSEquals (const Geometry * g1, const Geometry * g2)
Definition at line 263 of file geos_c.cpp.
References GEOSEquals_r(), and handle.
 {
     return GEOSEquals_r( handle, g1, g2 );
 }
char GEOSEqualsExact (const Geometry * g1, const Geometry * g2, double tolerance)
Definition at line 269 of file geos_c.cpp.
References GEOSEqualsExact_r(), and handle.
 {
     return GEOSEqualsExact_r( handle, g1, g2, tolerance );
 }
int GEOSFrechetDistance (const Geometry * g1, const Geometry * g2, double * dist)
Definition at line 299 of file geos_c.cpp.
References GEOSFrechetDistance_r(), and handle.
 {
     return GEOSFrechetDistance_r( handle, g1, g2, dist );
 }
int GEOSFrechetDistanceDensify (const Geometry * g1, const Geometry * g2, double densifyFrac, double * dist)
Definition at line 305 of file geos_c.cpp.
References GEOSFrechetDistanceDensify_r(), and handle.
 {
     return GEOSFrechetDistanceDensify_r( handle, g1, g2, densifyFrac, dist );
 }
void GEOSFree (void * buffer)
Definition at line 136 of file geos_c.cpp.
References GEOSFree_r(), and handle.
 {
     GEOSFree_r( handle, buffer );
 }
Geometry* GEOSGeom_clone (const Geometry * g)
Definition at line 911 of file geos_c.cpp.
References GEOSGeom_clone_r(), GEOSGeometry, and handle.
 {
     return GEOSGeom_clone_r( handle, g );
 }
Geometry* GEOSGeom_createCollection (int type, Geometry ** geoms, unsigned int ngeoms)
Definition at line 705 of file geos_c.cpp.
References GEOSGeom_createCollection_r(), and handle.
 {
     return GEOSGeom_createCollection_r( handle, type, geoms, ngeoms );
 }
geos::geom::Geometry* GEOSGeom_createEmptyCollection (int type)
Definition at line 1305 of file geos_c.cpp.
References GEOSGeom_createEmptyCollection_r(), and handle.
 {
     return GEOSGeom_createEmptyCollection_r(handle, type);
 }
geos::geom::Geometry* GEOSGeom_createEmptyLineString ()
Definition at line 1317 of file geos_c.cpp.
References GEOSGeom_createEmptyLineString_r(), and handle.
 {
     return GEOSGeom_createEmptyLineString_r(handle);
 }
geos::geom::Geometry* GEOSGeom_createEmptyPoint ()
Definition at line 1311 of file geos_c.cpp.
References GEOSGeom_createEmptyPoint_r(), and handle.
 {
     return GEOSGeom_createEmptyPoint_r(handle);
 }
geos::geom::Geometry* GEOSGeom_createEmptyPolygon ()
Definition at line 1323 of file geos_c.cpp.
References GEOSGeom_createEmptyPolygon_r(), and handle.
 {
     return GEOSGeom_createEmptyPolygon_r(handle);
 }
Geometry* GEOSGeom_createLinearRing (CoordinateSequence * cs)
Definition at line 893 of file geos_c.cpp.
References GEOSGeom_createLinearRing_r(), and handle.
 {
     return GEOSGeom_createLinearRing_r( handle, cs );
 }
Geometry* GEOSGeom_createLineString (CoordinateSequence * cs)
Definition at line 899 of file geos_c.cpp.
References GEOSGeom_createLineString_r(), and handle.
 {
     return GEOSGeom_createLineString_r( handle, cs );
 }
Geometry* GEOSGeom_createPoint (CoordinateSequence * cs)
Definition at line 887 of file geos_c.cpp.
References GEOSGeom_createPoint_r(), and handle.
 {
     return GEOSGeom_createPoint_r( handle, cs );
 }
Geometry* GEOSGeom_createPolygon (Geometry * shell, Geometry ** holes, unsigned int nholes)
Definition at line 905 of file geos_c.cpp.
References GEOSGeom_createPolygon_r(), and handle.
 {
     return GEOSGeom_createPolygon_r( handle, shell, holes, nholes );
 }
void GEOSGeom_destroy (Geometry * a)
Definition at line 543 of file geos_c.cpp.
References GEOSGeom_destroy_r(), and handle.
 {
     return GEOSGeom_destroy_r( handle, a );
 }
geos::geom::Geometry* GEOSGeom_extractUniquePoints (const geos::geom::Geometry * g)
Definition at line 1299 of file geos_c.cpp.
References GEOSGeom_extractUniquePoints_r(), and handle.
 {
     return GEOSGeom_extractUniquePoints_r(handle, g);
 }
int GEOSGeom_getCoordinateDimension (const Geometry * g)
Definition at line 935 of file geos_c.cpp.
References GEOSGeom_getCoordinateDimension_r(), and handle.
 {
     return GEOSGeom_getCoordinateDimension_r( handle, g );
 }
const CoordinateSequence* GEOSGeom_getCoordSeq (const Geometry * g)
Definition at line 881 of file geos_c.cpp.
References GEOSGeom_getCoordSeq_r(), and handle.
 {
     return GEOSGeom_getCoordSeq_r( handle, g );
 }
int GEOSGeom_getDimensions (const Geometry * g)
Definition at line 929 of file geos_c.cpp.
References GEOSGeom_getDimensions_r(), and handle.
 {
     return GEOSGeom_getDimensions_r( handle, g );
 }
double GEOSGeom_getPrecision (const GEOSGeometry * g)
Definition at line 923 of file geos_c.cpp.
References GEOSGeom_getPrecision_r(), and handle.
 {
   return GEOSGeom_getPrecision_r(handle, g);
 }
void* GEOSGeom_getUserData (const Geometry * g)
Definition at line 754 of file geos_c.cpp.
References GEOSGeom_getUserData_r(), and handle.
 {
     return GEOSGeom_getUserData_r( handle, g );
 }
int GEOS_DLL GEOSGeom_getXMax (const GEOSGeometry * g, double * value)
Definition at line 950 of file geos_c.cpp.
References GEOSGeom_getXMax_r(), and handle.
 {
     return GEOSGeom_getXMax_r(handle, g, value);
 }
int GEOS_DLL GEOSGeom_getXMin (const GEOSGeometry * g, double * value)
Definition at line 940 of file geos_c.cpp.
References GEOSGeom_getXMin_r(), and handle.
 {
     return GEOSGeom_getXMin_r(handle, g, value);
 }
int GEOS_DLL GEOSGeom_getYMax (const GEOSGeometry * g, double * value)
Definition at line 955 of file geos_c.cpp.
References GEOSGeom_getYMax_r(), and handle.
 {
     return GEOSGeom_getYMax_r(handle, g, value);
 }
int GEOS_DLL GEOSGeom_getYMin (const GEOSGeometry * g, double * value)
Definition at line 945 of file geos_c.cpp.
References GEOSGeom_getYMin_r(), and handle.
 {
     return GEOSGeom_getYMin_r(handle, g, value);
 }
GEOSGeometry* GEOSGeom_setPrecision (const GEOSGeometry * g, double gridSize, int flags)
Definition at line 917 of file geos_c.cpp.
References GEOSGeom_setPrecision_r(), and handle.
 {
   return GEOSGeom_setPrecision_r(handle, g, gridSize, flags);
 }
void GEOSGeom_setUserData (Geometry * g, void * userData)
Definition at line 760 of file geos_c.cpp.
References GEOSGeom_setUserData_r(), and handle.
 {
     return GEOSGeom_setUserData_r( handle, g, userData );
 }
Geometry* GEOSGeomFromHEX_buf (const unsigned char * hex, size_t size)
Definition at line 362 of file geos_c.cpp.
References GEOSGeomFromHEX_buf_r(), and handle.
 {
     return GEOSGeomFromHEX_buf_r( handle, hex, size );
 }
Geometry* GEOSGeomFromWKB_buf (const unsigned char * wkb, size_t size)
Definition at line 348 of file geos_c.cpp.
References GEOSGeomFromWKB_buf_r(), and handle.
 {
     return GEOSGeomFromWKB_buf_r( handle, wkb, size );
 }
Geometry* GEOSGeomFromWKT (const char * wkt)
Definition at line 329 of file geos_c.cpp.
References GEOSGeomFromWKT_r(), and handle.
 {
     return GEOSGeomFromWKT_r( handle, wkt );
 }
Geometry* GEOSGeomGetEndPoint (const Geometry * g)
Definition at line 613 of file geos_c.cpp.
References GEOSGeomGetEndPoint_r(), and handle.
 {
   return GEOSGeomGetEndPoint_r(handle, g);
 }
int GEOSGeomGetLength (const Geometry * g, double * length)
Definition at line 633 of file geos_c.cpp.
References GEOSGeomGetLength_r(), and handle.
 {
   return GEOSGeomGetLength_r(handle, g, length);
 }
int GEOSGeomGetNumPoints (const Geometry * g)
Definition at line 643 of file geos_c.cpp.
References GEOSGeomGetNumPoints_r(), and handle.
 {
   return GEOSGeomGetNumPoints_r(handle, g);
 }
Geometry* GEOSGeomGetPointN (const Geometry * g, int n)
Definition at line 595 of file geos_c.cpp.
References GEOSGeomGetPointN_r(), and handle.
 {
   return GEOSGeomGetPointN_r(handle, g, n);
 }
Geometry* GEOSGeomGetStartPoint (const Geometry * g)
Definition at line 604 of file geos_c.cpp.
References GEOSGeomGetStartPoint_r(), and handle.
 {
   return GEOSGeomGetStartPoint_r(handle, g);
 }
int GEOSGeomGetX (const Geometry * g, double * x)
Definition at line 653 of file geos_c.cpp.
References GEOSGeomGetX_r(), and handle.
 {
   return GEOSGeomGetX_r(handle, g, x);
 }
int GEOSGeomGetY (const Geometry * g, double * y)
Definition at line 663 of file geos_c.cpp.
References GEOSGeomGetY_r(), and handle.
 {
   return GEOSGeomGetY_r(handle, g, y);
 }
int GEOSGeomGetZ (const Geometry * g1, double * z)
Definition at line 673 of file geos_c.cpp.
References GEOSGeomGetZ_r(), and handle.
 {
   return GEOSGeomGetZ_r(handle, g1, z);
 }
unsigned char* GEOSGeomToHEX_buf (const Geometry * g, size_t * size)
Definition at line 356 of file geos_c.cpp.
References GEOSGeomToHEX_buf_r(), and handle.
 {
     return GEOSGeomToHEX_buf_r( handle, g, size );
 }
unsigned char* GEOSGeomToWKB_buf (const Geometry * g, size_t * size)
Definition at line 342 of file geos_c.cpp.
References GEOSGeomToWKB_buf_r(), and handle.
 {
     return GEOSGeomToWKB_buf_r( handle, g, size );
 }
char* GEOSGeomToWKT (const Geometry * g)
Definition at line 335 of file geos_c.cpp.
References GEOSGeomToWKT_r(), and handle.
 {
     return GEOSGeomToWKT_r( handle, g );
 }
char* GEOSGeomType (const Geometry * g)
Definition at line 389 of file geos_c.cpp.
References GEOSGeomType_r(), and handle.
 {
     return GEOSGeomType_r( handle, g );
 }
int GEOSGeomTypeId (const Geometry * g)
Definition at line 396 of file geos_c.cpp.
References GEOSGeomTypeId_r(), and handle.
 {
     return GEOSGeomTypeId_r( handle, g );
 }
Geometry* GEOSGetCentroid (const Geometry * g)
Definition at line 699 of file geos_c.cpp.
References GEOSGetCentroid_r(), and handle.
 {
     return GEOSGetCentroid_r( handle, g );
 }
const Geometry* GEOSGetExteriorRing (const Geometry * g)
Definition at line 683 of file geos_c.cpp.
References GEOSGetExteriorRing_r(), and handle.
 {
     return GEOSGetExteriorRing_r( handle, g );
 }
const Geometry* GEOSGetGeometryN (const Geometry * g, int n)
Definition at line 585 of file geos_c.cpp.
References GEOSGetGeometryN_r(), and handle.
 {
     return GEOSGetGeometryN_r( handle, g, n );
 }
const Geometry* GEOSGetInteriorRingN (const Geometry * g, int n)
Definition at line 693 of file geos_c.cpp.
References GEOSGetInteriorRingN_r(), and handle.
 {
     return GEOSGetInteriorRingN_r( handle, g, n );
 }
int GEOSGetNumCoordinates (const Geometry * g)
Definition at line 550 of file geos_c.cpp.
References GEOSGetNumCoordinates_r(), and handle.
 {
     return GEOSGetNumCoordinates_r( handle, g );
 }
int GEOSGetNumGeometries (const Geometry * g)
Definition at line 574 of file geos_c.cpp.
References GEOSGetNumGeometries_r(), and handle.
 {
     return GEOSGetNumGeometries_r( handle, g );
 }
int GEOSGetNumInteriorRings (const Geometry * g)
Definition at line 566 of file geos_c.cpp.
References GEOSGetNumInteriorRings_r(), and handle.
 {
     return GEOSGetNumInteriorRings_r( handle, g );
 }
int GEOSGetSRID (const Geometry * g)
Definition at line 742 of file geos_c.cpp.
References GEOSGetSRID_r(), and handle.
 {
     return GEOSGetSRID_r( handle, g );
 }
char GEOSHasZ (const Geometry * g)
Definition at line 766 of file geos_c.cpp.
References GEOSHasZ_r(), and handle.
 {
     return GEOSHasZ_r( handle, g );
 }
int GEOSHausdorffDistance (const Geometry * g1, const Geometry * g2, double * dist)
Definition at line 287 of file geos_c.cpp.
References GEOSHausdorffDistance_r(), and handle.
 {
     return GEOSHausdorffDistance_r( handle, g1, g2, dist );
 }
int GEOSHausdorffDistanceDensify (const Geometry * g1, const Geometry * g2, double densifyFrac, double * dist)
Definition at line 293 of file geos_c.cpp.
References GEOSHausdorffDistanceDensify_r(), and handle.
 {
     return GEOSHausdorffDistanceDensify_r( handle, g1, g2, densifyFrac, dist );
 }
geos::geom::Geometry* GEOSInterpolate (const geos::geom::Geometry * g, double d)
Definition at line 1278 of file geos_c.cpp.
References GEOSInterpolate_r(), and handle.
 {
     return GEOSInterpolate_r(handle, g, d);
 }
geos::geom::Geometry* GEOSInterpolateNormalized (const geos::geom::Geometry * g, double d)
Definition at line 1292 of file geos_c.cpp.
References GEOSInterpolateNormalized_r(), and handle.
 {
     return GEOSInterpolateNormalized_r(handle, g, d);
 }
Geometry* GEOSIntersection (const Geometry * g1, const Geometry * g2)
Definition at line 415 of file geos_c.cpp.
References GEOSIntersection_r(), and handle.
 {
     return GEOSIntersection_r( handle, g1, g2 );
 }
char GEOSIntersects (const Geometry * g1, const Geometry * g2)
Definition at line 159 of file geos_c.cpp.
References GEOSIntersects_r(), and handle.
 {
     return GEOSIntersects_r( handle, g1, g2 );
 }
char GEOSisClosed (const Geometry * g)
Definition at line 623 of file geos_c.cpp.
References GEOSisClosed_r(), and handle.
 {
   return GEOSisClosed_r(handle, g);
 }
char GEOSisEmpty (const Geometry * g)
Definition at line 368 of file geos_c.cpp.
References GEOSisEmpty_r(), and handle.
 {
     return GEOSisEmpty_r( handle, g );
 }
char GEOSisRing (const Geometry * g)
Definition at line 380 of file geos_c.cpp.
References GEOSisRing_r(), and handle.
 {
     return GEOSisRing_r( handle, g );
 }
char GEOSisSimple (const Geometry * g)
Definition at line 374 of file geos_c.cpp.
References GEOSisSimple_r(), and handle.
 {
     return GEOSisSimple_r( handle, g );
 }
char GEOSisValid (const Geometry * g)
Definition at line 240 of file geos_c.cpp.
References GEOSisValid_r(), and handle.
 {
     return GEOSisValid_r( handle, g );
 }
char GEOSisValidDetail (const Geometry * g, int flags, char ** reason, Geometry ** location)
Definition at line 252 of file geos_c.cpp.
References GEOSisValidDetail_r(), and handle.
 {
     return GEOSisValidDetail_r( handle, g, flags, reason, location );
 }
char* GEOSisValidReason (const Geometry * g)
Definition at line 246 of file geos_c.cpp.
References GEOSisValidReason_r(), and handle.
 {
     return GEOSisValidReason_r( handle, g );
 }
int GEOSLength (const Geometry * g, double * length)
Definition at line 317 of file geos_c.cpp.
References GEOSLength_r(), and handle.
 {
     return GEOSLength_r( handle, g, length );
 }
Geometry* GEOSLineMerge (const Geometry * g)
Definition at line 730 of file geos_c.cpp.
References GEOSLineMerge_r(), and handle.
 {
     return GEOSLineMerge_r( handle, g );
 }
int GEOSMinimumClearance (const Geometry * g, double * d)
Definition at line 475 of file geos_c.cpp.
References GEOSMinimumClearance_r(), and handle.
 {
     return GEOSMinimumClearance_r( handle, g, d);
 }
Geometry* GEOSMinimumClearanceLine (const Geometry * g)
Definition at line 469 of file geos_c.cpp.
References GEOSMinimumClearanceLine_r(), and handle.
 {
     return GEOSMinimumClearanceLine_r( handle, g );
 }
Geometry* GEOSMinimumRotatedRectangle (const Geometry * g)
Definition at line 457 of file geos_c.cpp.
References GEOSMinimumRotatedRectangle_r(), and handle.
 {
     return GEOSMinimumRotatedRectangle_r( handle, g );
 }
Geometry* GEOSMinimumWidth (const Geometry * g)
Definition at line 463 of file geos_c.cpp.
References GEOSMinimumWidth_r(), and handle.
 {
     return GEOSMinimumWidth_r( handle, g );
 }
CoordinateSequence* GEOSNearestPoints (const Geometry * g1, const Geometry * g2)
Definition at line 323 of file geos_c.cpp.
References GEOSNearestPoints_r(), and handle.
 {
     return GEOSNearestPoints_r( handle, g1, g2 );
 }
Geometry* GEOSNode (const Geometry * g)
Definition at line 511 of file geos_c.cpp.
References GEOSNode_r(), and handle.
 {
     return GEOSNode_r( handle, g );
 }
int GEOSNormalize (Geometry * g)
Definition at line 560 of file geos_c.cpp.
References GEOSNormalize_r(), and handle.
 {
     return GEOSNormalize_r( handle, g );
 }
Geometry* GEOSOffsetCurve (const Geometry * g, double width, int quadsegs, int joinStyle, double mitreLimit)
Definition at line 443 of file geos_c.cpp.
References GEOSOffsetCurve_r(), and handle.
 {
     return GEOSOffsetCurve_r( handle, g, width, quadsegs,
                                joinStyle, mitreLimit );
 }
int GEOSOrientationIndex (double Ax, double Ay, double Bx, double By, double Px, double Py)
Definition at line 1329 of file geos_c.cpp.
References GEOSGeometry, GEOSOrientationIndex_r(), and handle.
 {
     return GEOSOrientationIndex_r(handle, Ax, Ay, Bx, By, Px, Py);
 }
char GEOSOverlaps (const Geometry * g1, const Geometry * g2)
Definition at line 187 of file geos_c.cpp.
References GEOSOverlaps_r(), and handle.
 {
     return GEOSOverlaps_r( handle, g1, g2 );
 }
Geometry* GEOSPointOnSurface (const Geometry * g)
Definition at line 523 of file geos_c.cpp.
References GEOSPointOnSurface_r(), and handle.
 {
     return GEOSPointOnSurface_r( handle, g );
 }
Geometry* GEOSPolygonize (const Geometry *const * g, unsigned int ngeoms)
Definition at line 711 of file geos_c.cpp.
References GEOSPolygonize_r(), and handle.
 {
     return GEOSPolygonize_r( handle, g, ngeoms );
 }
GEOSGeometry* GEOSPolygonize_full (const GEOSGeometry * input, GEOSGeometry ** cuts, GEOSGeometry ** dangles, GEOSGeometry ** invalid)
Definition at line 723 of file geos_c.cpp.
References GEOSPolygonize_full_r(), and handle.
 {
     return GEOSPolygonize_full_r(handle, input, cuts, dangles, invalid );
 }
Geometry* GEOSPolygonizer_getCutEdges (const Geometry *const * g, unsigned int ngeoms)
Definition at line 717 of file geos_c.cpp.
References GEOSGeometry, GEOSPolygonizer_getCutEdges_r(), and handle.
 {
     return GEOSPolygonizer_getCutEdges_r( handle, g, ngeoms );
 }
const geos::geom::prep::PreparedGeometry* GEOSPrepare (const Geometry * g)
Definition at line 1138 of file geos_c.cpp.
References GEOSPrepare_r(), and handle.
 {
     return GEOSPrepare_r( handle, g );
 }
char GEOSPreparedContains (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1150 of file geos_c.cpp.
References GEOSPreparedContains_r(), and handle.
 {
     return GEOSPreparedContains_r( handle, pg1, g2 );
 }
char GEOSPreparedContainsProperly (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1156 of file geos_c.cpp.
References GEOSPreparedContainsProperly_r(), and handle.
 {
     return GEOSPreparedContainsProperly_r( handle, pg1, g2 );
 }
char GEOSPreparedCoveredBy (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1162 of file geos_c.cpp.
References GEOSPreparedCoveredBy_r(), and handle.
 {
     return GEOSPreparedCoveredBy_r( handle, pg1, g2 );
 }
char GEOSPreparedCovers (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1168 of file geos_c.cpp.
References GEOSPreparedCovers_r(), and handle.
 {
     return GEOSPreparedCovers_r( handle, pg1, g2 );
 }
char GEOSPreparedCrosses (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1174 of file geos_c.cpp.
References GEOSPreparedCrosses_r(), and handle.
 {
     return GEOSPreparedCrosses_r( handle, pg1, g2 );
 }
char GEOSPreparedDisjoint (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1180 of file geos_c.cpp.
References GEOSPreparedDisjoint_r(), and handle.
 {
     return GEOSPreparedDisjoint_r( handle, pg1, g2 );
 }
void GEOSPreparedGeom_destroy (const geos::geom::prep::PreparedGeometry * a)
Definition at line 1144 of file geos_c.cpp.
References GEOSPreparedGeom_destroy_r(), and handle.
 {
     GEOSPreparedGeom_destroy_r( handle, a );
 }
char GEOSPreparedIntersects (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1186 of file geos_c.cpp.
References GEOSPreparedIntersects_r(), and handle.
 {
     return GEOSPreparedIntersects_r( handle, pg1, g2 );
 }
char GEOSPreparedOverlaps (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1192 of file geos_c.cpp.
References GEOSPreparedOverlaps_r(), and handle.
 {
     return GEOSPreparedOverlaps_r( handle, pg1, g2 );
 }
char GEOSPreparedTouches (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1198 of file geos_c.cpp.
References GEOSPreparedTouches_r(), and handle.
 {
     return GEOSPreparedTouches_r( handle, pg1, g2 );
 }
char GEOSPreparedWithin (const geos::geom::prep::PreparedGeometry * pg1, const Geometry * g2)
Definition at line 1204 of file geos_c.cpp.
References GEOSPreparedWithin_r(), and handle.
 {
     return GEOSPreparedWithin_r( handle, pg1, g2 );
 }
double GEOSProject (const geos::geom::Geometry * g, const geos::geom::Geometry * p)
Definition at line 1271 of file geos_c.cpp.
References GEOSProject_r(), and handle.
 {
     return GEOSProject_r (handle, g, p);
 }
double GEOSProjectNormalized (const geos::geom::Geometry * g, const geos::geom::Geometry * p)
Definition at line 1285 of file geos_c.cpp.
References GEOSProjectNormalized_r(), and handle.
 {
     return GEOSProjectNormalized_r (handle, g, p);
 }
char* GEOSRelate (const Geometry * g1, const Geometry * g2)
Definition at line 222 of file geos_c.cpp.
References GEOSRelate_r(), and handle.
 {
     return GEOSRelate_r( handle, g1, g2 );
 }
char* GEOSRelateBoundaryNodeRule (const Geometry * g1, const Geometry * g2, int bnr)
Definition at line 228 of file geos_c.cpp.
References GEOSRelateBoundaryNodeRule_r(), and handle.
 {
     return GEOSRelateBoundaryNodeRule_r( handle, g1, g2, bnr );
 }
char GEOSRelatePattern (const Geometry * g1, const Geometry * g2, const char * pat)
Definition at line 210 of file geos_c.cpp.
References GEOSRelatePattern_r(), and handle.
 {
     return GEOSRelatePattern_r( handle, g1, g2, pat );
 }
char GEOSRelatePatternMatch (const char * mat, const char * pat)
Definition at line 216 of file geos_c.cpp.
References GEOSRelatePatternMatch_r(), and handle.
 {
     return GEOSRelatePatternMatch_r( handle, mat, pat );
 }
Geometry* GEOSReverse (const Geometry * g)
Definition at line 736 of file geos_c.cpp.
References GEOSReverse_r(), and handle.
 {
     return GEOSReverse_r( handle, g );
 }
int GEOSSegmentIntersection (double ax0, double ay0, double ax1, double ay1, double bx0, double by0, double bx1, double by1, double * cx, double * cy)
Definition at line 1408 of file geos_c.cpp.
References GEOSSegmentIntersection_r(), and handle.
 {
     return GEOSSegmentIntersection_r(handle,
         ax0, ay0, ax1, ay1,
         bx0, by0, bx1, by1,
         cx, cy);
 }
void GEOSSetSRID (Geometry * g, int srid)
Definition at line 748 of file geos_c.cpp.
References GEOSSetSRID_r(), and handle.
 {
     return GEOSSetSRID_r( handle, g, srid );
 }
GEOSGeometry* GEOSSharedPaths (const GEOSGeometry * g1, const GEOSGeometry * g2)
Definition at line 1336 of file geos_c.cpp.
References GEOSGeometry, GEOSSharedPaths_r(), and handle.
 {
     return GEOSSharedPaths_r(handle, g1, g2);
 }
Geometry* GEOSSimplify (const Geometry * g, double tolerance)
Definition at line 961 of file geos_c.cpp.
References GEOSSimplify_r(), and handle.
 {
     return GEOSSimplify_r( handle, g, tolerance );
 }
Geometry* GEOSSingleSidedBuffer (const Geometry * g, double width, int quadsegs, int joinStyle, double mitreLimit, int leftSide)
Definition at line 435 of file geos_c.cpp.
References GEOSSingleSidedBuffer_r(), and handle.
 {
     return GEOSSingleSidedBuffer_r( handle, g, width, quadsegs,
                                joinStyle, mitreLimit, leftSide );
 }
GEOSGeometry* GEOSSnap (const GEOSGeometry * g1, const GEOSGeometry * g2, double tolerance)
Definition at line 1342 of file geos_c.cpp.
References GEOSSnap_r(), and handle.
 {
   return GEOSSnap_r(handle, g1, g2, tolerance);
 }
STRtree* GEOSSTRtree_create (size_t nodeCapacity)
Definition at line 1210 of file geos_c.cpp.
References GEOSSTRtree_create_r(), and handle.
 {
     return GEOSSTRtree_create_r( handle, nodeCapacity );
 }
void GEOSSTRtree_destroy (geos::index::strtree::STRtree * tree)
Definition at line 1265 of file geos_c.cpp.
References GEOSSTRtree_destroy_r(), and handle.
 {
     GEOSSTRtree_destroy_r( handle, tree );
 }
void GEOSSTRtree_insert (geos::index::strtree::STRtree * tree, const geos::geom::Geometry * g, void * item)
Definition at line 1216 of file geos_c.cpp.
References GEOSSTRtree_insert_r(), and handle.
 {
     GEOSSTRtree_insert_r( handle, tree, g, item );
 }
void GEOSSTRtree_iterate (geos::index::strtree::STRtree * tree, GEOSQueryCallback callback, void * userdata)
Definition at line 1249 of file geos_c.cpp.
References GEOSSTRtree_iterate_r(), and handle.
 {
     GEOSSTRtree_iterate_r( handle, tree, callback, userdata );
 }
const GEOSGeometry* GEOSSTRtree_nearest (geos::index::strtree::STRtree * tree, const geos::geom::Geometry * g)
Definition at line 1233 of file geos_c.cpp.
References GEOSSTRtree_nearest_r(), and handle.
 {
     return GEOSSTRtree_nearest_r( handle, tree, g);
 }
const void* GEOSSTRtree_nearest_generic (GEOSSTRtree * tree, const void * item, const GEOSGeometry * itemEnvelope, GEOSDistanceCallback distancefn, void * userdata)
Definition at line 1239 of file geos_c.cpp.
References GEOSSTRtree_nearest_generic_r(), and handle.
 {
     return GEOSSTRtree_nearest_generic_r( handle, tree, item, itemEnvelope, distancefn, userdata);
 }
void GEOSSTRtree_query (geos::index::strtree::STRtree * tree, const geos::geom::Geometry * g, GEOSQueryCallback cb, void * userdata)
Definition at line 1224 of file geos_c.cpp.
References GEOSGeometry, GEOSSTRtree_query_r(), and handle.
 {
     GEOSSTRtree_query_r( handle, tree, g, cb, userdata );
 }
char GEOSSTRtree_remove (geos::index::strtree::STRtree * tree, const geos::geom::Geometry * g, void * item)
Definition at line 1257 of file geos_c.cpp.
References GEOSSTRtree_remove_r(), and handle.
 {
     return GEOSSTRtree_remove_r( handle, tree, g, item );
 }
Geometry* GEOSSymDifference (const Geometry * g1, const Geometry * g2)
Definition at line 493 of file geos_c.cpp.
References GEOSSymDifference_r(), and handle.
 {
     return GEOSSymDifference_r( handle, g1, g2 );
 }
Geometry* GEOSTopologyPreserveSimplify (const Geometry * g, double tolerance)
Definition at line 967 of file geos_c.cpp.
References GEOSTopologyPreserveSimplify_r(), and handle.
 {
     return GEOSTopologyPreserveSimplify_r( handle, g, tolerance );
 }
char GEOSTouches (const Geometry * g1, const Geometry * g2)
Definition at line 153 of file geos_c.cpp.
References GEOSTouches_r(), and handle.
 {
     return GEOSTouches_r( handle, g1, g2 );
 }
Geometry* GEOSUnaryUnion (const Geometry * g)
Definition at line 505 of file geos_c.cpp.
References GEOSUnaryUnion_r(), and handle.
 {
     return GEOSUnaryUnion_r( handle, g);
 }
Geometry* GEOSUnion (const Geometry * g1, const Geometry * g2)
Definition at line 499 of file geos_c.cpp.
References GEOSUnion_r(), and handle.
 {
     return GEOSUnion_r( handle, g1, g2 );
 }
Geometry* GEOSUnionCascaded (const Geometry * g)
Definition at line 517 of file geos_c.cpp.
References GEOSUnionCascaded_r(), and handle.
 {
   return GEOSUnionCascaded_r( handle, g );
 }
Geometry* GEOSVoronoiDiagram (const Geometry * g, const Geometry * env, double tolerance, int onlyEdges)
Definition at line 1402 of file geos_c.cpp.
References GEOSVoronoiDiagram_r(), and handle.
 {
   return GEOSVoronoiDiagram_r(handle, g, env, tolerance, onlyEdges);
 }
char GEOSWithin (const Geometry * g1, const Geometry * g2)
Definition at line 171 of file geos_c.cpp.
References GEOSWithin_r(), and handle.
 {
     return GEOSWithin_r( handle, g1, g2 );
 }
WKBReader* GEOSWKBReader_create ()
Definition at line 1044 of file geos_c.cpp.
References GEOSWKBReader_create_r(), and handle.
 {
     return GEOSWKBReader_create_r( handle );
 }
void GEOSWKBReader_destroy (WKBReader * reader)
Definition at line 1050 of file geos_c.cpp.
References GEOSWKBReader_destroy_r(), and handle.
 {
     GEOSWKBReader_destroy_r( handle, reader );
 }
Geometry* GEOSWKBReader_read (WKBReader * reader, const unsigned char * wkb, size_t size)
Definition at line 1057 of file geos_c.cpp.
References GEOSWKBReader_read_r(), and handle.
 {
     return GEOSWKBReader_read_r( handle, reader, wkb, size );
 }
Geometry* GEOSWKBReader_readHEX (WKBReader * reader, const unsigned char * hex, size_t size)
Definition at line 1063 of file geos_c.cpp.
References GEOSWKBReader_readHEX_r(), and handle.
 {
     return GEOSWKBReader_readHEX_r( handle, reader, hex, size );
 }
WKBWriter* GEOSWKBWriter_create ()
Definition at line 1070 of file geos_c.cpp.
References GEOSWKBWriter_create_r(), and handle.
 {
     return GEOSWKBWriter_create_r( handle );
 }
void GEOSWKBWriter_destroy (WKBWriter * Writer)
Definition at line 1076 of file geos_c.cpp.
References GEOSWKBWriter_destroy_r(), and handle.
 {
     GEOSWKBWriter_destroy_r( handle, Writer );
 }
int GEOSWKBWriter_getByteOrder (const GEOSWKBWriter * writer)
Definition at line 1109 of file geos_c.cpp.
References GEOSWKBWriter_getByteOrder_r(), and handle.
 {
     return GEOSWKBWriter_getByteOrder_r( handle, writer );
 }
char GEOSWKBWriter_getIncludeSRID (const GEOSWKBWriter * writer)
Definition at line 1121 of file geos_c.cpp.
References GEOSWKBWriter_getIncludeSRID_r(), and handle.
 {
     return GEOSWKBWriter_getIncludeSRID_r( handle, writer );
 }
int GEOSWKBWriter_getOutputDimension (const GEOSWKBWriter * writer)
Definition at line 1097 of file geos_c.cpp.
References GEOSWKBWriter_getOutputDimension_r(), and handle.
 {
     return GEOSWKBWriter_getOutputDimension_r( handle, writer );
 }
void GEOSWKBWriter_setByteOrder (GEOSWKBWriter * writer, int newByteOrder)
Definition at line 1115 of file geos_c.cpp.
References GEOSWKBWriter_setByteOrder_r(), and handle.
 {
     GEOSWKBWriter_setByteOrder_r( handle, writer, newByteOrder );
 }
void GEOSWKBWriter_setIncludeSRID (GEOSWKBWriter * writer, const char newIncludeSRID)
Definition at line 1127 of file geos_c.cpp.
References GEOSWKBWriter_setIncludeSRID_r(), and handle.
 {
     GEOSWKBWriter_setIncludeSRID_r( handle, writer, newIncludeSRID );
 }
void GEOSWKBWriter_setOutputDimension (GEOSWKBWriter * writer, int newDimension)
Definition at line 1103 of file geos_c.cpp.
References GEOSWKBWriter_setOutputDimension_r(), and handle.
 {
     GEOSWKBWriter_setOutputDimension_r( handle, writer, newDimension );
 }
unsigned char* GEOSWKBWriter_write (WKBWriter * writer, const Geometry * geom, size_t * size)
Definition at line 1084 of file geos_c.cpp.
References GEOSWKBWriter_write_r(), and handle.
 {
     return GEOSWKBWriter_write_r( handle, writer, geom, size );
 }
unsigned char* GEOSWKBWriter_writeHEX (WKBWriter * writer, const Geometry * geom, size_t * size)
Definition at line 1091 of file geos_c.cpp.
References GEOSWKBWriter_writeHEX_r(), and handle.
 {
     return GEOSWKBWriter_writeHEX_r( handle, writer, geom, size );
 }
WKTReader* GEOSWKTReader_create ()
Definition at line 975 of file geos_c.cpp.
References GEOSWKTReader_create_r(), and handle.
 {
     return GEOSWKTReader_create_r( handle );
 }
void GEOSWKTReader_destroy (WKTReader * reader)
Definition at line 981 of file geos_c.cpp.
References GEOSWKTReader_destroy_r(), and handle.
 {
     GEOSWKTReader_destroy_r( handle, reader );
 }
Geometry* GEOSWKTReader_read (WKTReader * reader, const char * wkt)
Definition at line 988 of file geos_c.cpp.
References GEOSWKTReader_read_r(), and handle.
 {
     return GEOSWKTReader_read_r( handle, reader, wkt );
 }
WKTWriter* GEOSWKTWriter_create ()
Definition at line 995 of file geos_c.cpp.
References GEOSWKTWriter_create_r(), and handle.
 {
     return GEOSWKTWriter_create_r( handle );
 }
void GEOSWKTWriter_destroy (WKTWriter * Writer)
Definition at line 1001 of file geos_c.cpp.
References GEOSWKTWriter_destroy_r(), and handle.
 {
     GEOSWKTWriter_destroy_r( handle, Writer );
 }
int GEOSWKTWriter_getOutputDimension (WKTWriter * writer)
Definition at line 1031 of file geos_c.cpp.
References GEOSWKTWriter_getOutputDimension_r(), and handle.
 {
   return GEOSWKTWriter_getOutputDimension_r(handle, writer);
 }
void GEOSWKTWriter_setOld3D (WKTWriter * writer, int useOld3D)
Definition at line 1037 of file geos_c.cpp.
References GEOSWKTWriter_setOld3D_r(), and handle.
 {
   GEOSWKTWriter_setOld3D_r(handle, writer, useOld3D);
 }
void GEOSWKTWriter_setOutputDimension (WKTWriter * writer, int dim)
Definition at line 1025 of file geos_c.cpp.
References GEOSWKTWriter_setOutputDimension_r(), and handle.
 {
   GEOSWKTWriter_setOutputDimension_r(handle, writer, dim);
 }
void GEOSWKTWriter_setRoundingPrecision (WKTWriter * writer, int precision)
Definition at line 1019 of file geos_c.cpp.
References GEOSWKTWriter_setRoundingPrecision_r(), and handle.
 {
   return GEOSWKTWriter_setRoundingPrecision_r(handle, writer, precision);
 }
void GEOSWKTWriter_setTrim (WKTWriter * writer, char trim)
Definition at line 1013 of file geos_c.cpp.
References GEOSWKTWriter_setTrim_r(), and handle.
 {
   GEOSWKTWriter_setTrim_r(handle, writer, trim);
 }
char* GEOSWKTWriter_write (WKTWriter * writer, const Geometry * geom)
Definition at line 1007 of file geos_c.cpp.
References GEOSWKTWriter_write_r(), and handle.
 {
     return GEOSWKTWriter_write_r( handle, writer, geom );
 }
void initGEOS (GEOSMessageHandler nf, GEOSMessageHandler ef)
Definition at line 93 of file geos_c.cpp.
References geos::util::Interrupt::cancel(), GEOSContext_setErrorHandler_r(), GEOSContext_setNoticeHandler_r(), handle, and initGEOS_r().
 {
     if ( ! handle )
     {
         handle = initGEOS_r( nf, ef );
     }
     else
     {
         GEOSContext_setNoticeHandler_r(handle, nf);
         GEOSContext_setErrorHandler_r(handle, ef);
     }
     geos::util::Interrupt::cancel();
 }
Variable Documentation
GEOSContextHandle_t handle = NULL
Definition at line 88 of file geos_c.cpp.
Referenced by finishGEOS(), GEOS_getWKBByteOrder(), GEOS_getWKBByteOrder_r(), GEOS_getWKBOutputDims(), GEOS_getWKBOutputDims_r(), GEOS_init_r(), GEOS_setWKBByteOrder(), GEOS_setWKBByteOrder_r(), GEOS_setWKBOutputDims(), GEOS_setWKBOutputDims_r(), GEOSArea(), GEOSArea_r(), GEOSBoundary(), GEOSBoundary_r(), GEOSBuffer(), GEOSBuffer_r(), GEOSBufferParams_create(), GEOSBufferParams_create_r(), GEOSBufferParams_destroy(), GEOSBufferParams_setEndCapStyle(), GEOSBufferParams_setEndCapStyle_r(), GEOSBufferParams_setJoinStyle(), GEOSBufferParams_setJoinStyle_r(), GEOSBufferParams_setMitreLimit(), GEOSBufferParams_setMitreLimit_r(), GEOSBufferParams_setQuadrantSegments(), GEOSBufferParams_setQuadrantSegments_r(), GEOSBufferParams_setSingleSided(), GEOSBufferParams_setSingleSided_r(), GEOSBufferWithParams(), GEOSBufferWithParams_r(), GEOSBufferWithStyle(), GEOSBufferWithStyle_r(), GEOSClipByRect(), GEOSClipByRect_r(), GEOSContains(), GEOSContains_r(), GEOSContext_setErrorHandler_r(), GEOSContext_setErrorMessageHandler_r(), GEOSContext_setNoticeHandler_r(), GEOSContext_setNoticeMessageHandler_r(), GEOSConvexHull(), GEOSConvexHull_r(), GEOSCoordSeq_clone(), GEOSCoordSeq_clone_r(), GEOSCoordSeq_create(), GEOSCoordSeq_create_r(), GEOSCoordSeq_destroy(), GEOSCoordSeq_destroy_r(), GEOSCoordSeq_getDimensions(), GEOSCoordSeq_getDimensions_r(), GEOSCoordSeq_getOrdinate(), GEOSCoordSeq_getOrdinate_r(), GEOSCoordSeq_getSize(), GEOSCoordSeq_getSize_r(), GEOSCoordSeq_isCCW(), GEOSCoordSeq_isCCW_r(), GEOSCoordSeq_setOrdinate(), GEOSCoordSeq_setOrdinate_r(), GEOSCoveredBy(), GEOSCoveredBy_r(), GEOSCovers(), GEOSCovers_r(), GEOSCrosses(), GEOSCrosses_r(), GEOSDelaunayTriangulation(), GEOSDelaunayTriangulation_r(), GEOSDifference(), GEOSDifference_r(), GEOSDisjoint(), GEOSDisjoint_r(), GEOSDistance(), GEOSDistance_r(), GEOSDistanceIndexed(), GEOSDistanceIndexed_r(), GEOSEnvelope(), GEOSEnvelope_r(), GEOSEquals(), GEOSEquals_r(), GEOSEqualsExact(), GEOSEqualsExact_r(), GEOSFrechetDistance(), GEOSFrechetDistance_r(), GEOSFrechetDistanceDensify(), GEOSFrechetDistanceDensify_r(), GEOSFree(), GEOSGeom_clone(), GEOSGeom_clone_r(), GEOSGeom_createCollection(), GEOSGeom_createCollection_r(), GEOSGeom_createEmptyCollection(), GEOSGeom_createEmptyCollection_r(), GEOSGeom_createEmptyLineString(), GEOSGeom_createEmptyLineString_r(), GEOSGeom_createEmptyPoint(), GEOSGeom_createEmptyPoint_r(), GEOSGeom_createEmptyPolygon(), GEOSGeom_createEmptyPolygon_r(), GEOSGeom_createLinearRing(), GEOSGeom_createLinearRing_r(), GEOSGeom_createLineString(), GEOSGeom_createLineString_r(), GEOSGeom_createPoint(), GEOSGeom_createPoint_r(), GEOSGeom_createPolygon(), GEOSGeom_createPolygon_r(), GEOSGeom_destroy(), GEOSGeom_destroy_r(), GEOSGeom_extractUniquePoints(), GEOSGeom_extractUniquePoints_r(), GEOSGeom_getCoordinateDimension(), GEOSGeom_getCoordinateDimension_r(), GEOSGeom_getCoordSeq(), GEOSGeom_getCoordSeq_r(), GEOSGeom_getDimensions(), GEOSGeom_getDimensions_r(), GEOSGeom_getPrecision(), GEOSGeom_getPrecision_r(), GEOSGeom_getUserData(), GEOSGeom_getUserData_r(), GEOSGeom_getXMax(), GEOSGeom_getXMax_r(), GEOSGeom_getXMin(), GEOSGeom_getXMin_r(), GEOSGeom_getYMax(), GEOSGeom_getYMax_r(), GEOSGeom_getYMin(), GEOSGeom_getYMin_r(), GEOSGeom_setPrecision(), GEOSGeom_setPrecision_r(), GEOSGeom_setUserData(), GEOSGeom_setUserData_r(), GEOSGeomFromHEX_buf(), GEOSGeomFromHEX_buf_r(), GEOSGeomFromWKB_buf(), GEOSGeomFromWKB_buf_r(), GEOSGeomFromWKT(), GEOSGeomFromWKT_r(), GEOSGeomGetEndPoint(), GEOSGeomGetEndPoint_r(), GEOSGeomGetLength(), GEOSGeomGetLength_r(), GEOSGeomGetNumPoints(), GEOSGeomGetNumPoints_r(), GEOSGeomGetPointN(), GEOSGeomGetPointN_r(), GEOSGeomGetStartPoint(), GEOSGeomGetStartPoint_r(), GEOSGeomGetX(), GEOSGeomGetX_r(), GEOSGeomGetY(), GEOSGeomGetY_r(), GEOSGeomGetZ(), GEOSGeomGetZ_r(), GEOSGeomToHEX_buf(), GEOSGeomToHEX_buf_r(), GEOSGeomToWKB_buf(), GEOSGeomToWKB_buf_r(), GEOSGeomToWKT(), GEOSGeomToWKT_r(), GEOSGeomType(), GEOSGeomType_r(), GEOSGeomTypeId(), GEOSGeomTypeId_r(), GEOSGetCentroid(), GEOSGetCentroid_r(), GEOSGetExteriorRing(), GEOSGetExteriorRing_r(), GEOSGetGeometryN(), GEOSGetGeometryN_r(), GEOSGetInteriorRingN(), GEOSGetInteriorRingN_r(), GEOSGetNumCoordinates(), GEOSGetNumCoordinates_r(), GEOSGetNumGeometries(), GEOSGetNumGeometries_r(), GEOSGetNumInteriorRings(), GEOSGetNumInteriorRings_r(), GEOSGetSRID(), GEOSGetSRID_r(), GEOSHasZ(), GEOSHasZ_r(), GEOSHausdorffDistance(), GEOSHausdorffDistance_r(), GEOSHausdorffDistanceDensify(), GEOSHausdorffDistanceDensify_r(), GEOSInterpolate(), GEOSInterpolate_r(), GEOSInterpolateNormalized(), GEOSIntersection(), GEOSIntersection_r(), GEOSIntersects(), GEOSIntersects_r(), GEOSisClosed(), GEOSisClosed_r(), GEOSisEmpty(), GEOSisEmpty_r(), GEOSisRing(), GEOSisRing_r(), GEOSisSimple(), GEOSisSimple_r(), GEOSisValid(), GEOSisValid_r(), GEOSisValidDetail(), GEOSisValidDetail_r(), GEOSisValidReason(), GEOSisValidReason_r(), GEOSLength(), GEOSLength_r(), GEOSLineMerge(), GEOSLineMerge_r(), GEOSMinimumClearance(), GEOSMinimumClearance_r(), GEOSMinimumClearanceLine(), GEOSMinimumClearanceLine_r(), GEOSMinimumRotatedRectangle(), GEOSMinimumRotatedRectangle_r(), GEOSMinimumWidth(), GEOSMinimumWidth_r(), GEOSNearestPoints(), GEOSNearestPoints_r(), GEOSNode(), GEOSNode_r(), GEOSNormalize(), GEOSNormalize_r(), GEOSOffsetCurve(), GEOSOffsetCurve_r(), GEOSOrientationIndex(), GEOSOrientationIndex_r(), GEOSOverlaps(), GEOSOverlaps_r(), GEOSPointOnSurface(), GEOSPointOnSurface_r(), GEOSPolygonize(), GEOSPolygonize_full(), GEOSPolygonize_full_r(), GEOSPolygonize_r(), GEOSPolygonizer_getCutEdges(), GEOSPolygonizer_getCutEdges_r(), GEOSPrepare(), GEOSPrepare_r(), GEOSPreparedContains(), GEOSPreparedContains_r(), GEOSPreparedContainsProperly(), GEOSPreparedContainsProperly_r(), GEOSPreparedCoveredBy(), GEOSPreparedCoveredBy_r(), GEOSPreparedCovers(), GEOSPreparedCovers_r(), GEOSPreparedCrosses(), GEOSPreparedCrosses_r(), GEOSPreparedDisjoint(), GEOSPreparedDisjoint_r(), GEOSPreparedGeom_destroy(), GEOSPreparedGeom_destroy_r(), GEOSPreparedIntersects(), GEOSPreparedIntersects_r(), GEOSPreparedOverlaps(), GEOSPreparedOverlaps_r(), GEOSPreparedTouches(), GEOSPreparedTouches_r(), GEOSPreparedWithin(), GEOSPreparedWithin_r(), GEOSProject(), GEOSProject_r(), GEOSProjectNormalized(), GEOSRelate(), GEOSRelate_r(), GEOSRelateBoundaryNodeRule(), GEOSRelateBoundaryNodeRule_r(), GEOSRelatePattern(), GEOSRelatePattern_r(), GEOSRelatePatternMatch(), GEOSRelatePatternMatch_r(), GEOSReverse(), GEOSReverse_r(), GEOSSegmentIntersection(), GEOSSegmentIntersection_r(), GEOSSetSRID(), GEOSSetSRID_r(), GEOSSharedPaths(), GEOSSharedPaths_r(), GEOSSimplify(), GEOSSimplify_r(), GEOSSingleSidedBuffer(), GEOSSingleSidedBuffer_r(), GEOSSnap(), GEOSSnap_r(), GEOSSTRtree_create(), GEOSSTRtree_create_r(), GEOSSTRtree_destroy(), GEOSSTRtree_destroy_r(), GEOSSTRtree_insert(), GEOSSTRtree_insert_r(), GEOSSTRtree_iterate(), GEOSSTRtree_iterate_r(), GEOSSTRtree_nearest(), GEOSSTRtree_nearest_generic(), GEOSSTRtree_nearest_generic_r(), GEOSSTRtree_query(), GEOSSTRtree_query_r(), GEOSSTRtree_remove(), GEOSSTRtree_remove_r(), GEOSSymDifference(), GEOSSymDifference_r(), GEOSTopologyPreserveSimplify(), GEOSTopologyPreserveSimplify_r(), GEOSTouches(), GEOSTouches_r(), GEOSUnaryUnion(), GEOSUnaryUnion_r(), GEOSUnion(), GEOSUnion_r(), GEOSUnionCascaded(), GEOSUnionCascaded_r(), GEOSVoronoiDiagram(), GEOSVoronoiDiagram_r(), GEOSWithin(), GEOSWithin_r(), GEOSWKBReader_create(), GEOSWKBReader_create_r(), GEOSWKBReader_destroy(), GEOSWKBReader_destroy_r(), GEOSWKBReader_read(), GEOSWKBReader_read_r(), GEOSWKBReader_readHEX(), GEOSWKBReader_readHEX_r(), GEOSWKBWriter_create(), GEOSWKBWriter_create_r(), GEOSWKBWriter_destroy(), GEOSWKBWriter_destroy_r(), GEOSWKBWriter_getByteOrder(), GEOSWKBWriter_getByteOrder_r(), GEOSWKBWriter_getIncludeSRID(), GEOSWKBWriter_getIncludeSRID_r(), GEOSWKBWriter_getOutputDimension(), GEOSWKBWriter_getOutputDimension_r(), GEOSWKBWriter_setByteOrder(), GEOSWKBWriter_setByteOrder_r(), GEOSWKBWriter_setIncludeSRID(), GEOSWKBWriter_setIncludeSRID_r(), GEOSWKBWriter_setOutputDimension(), GEOSWKBWriter_setOutputDimension_r(), GEOSWKBWriter_write(), GEOSWKBWriter_write_r(), GEOSWKBWriter_writeHEX(), GEOSWKBWriter_writeHEX_r(), GEOSWKTReader_create(), GEOSWKTReader_create_r(), GEOSWKTReader_destroy(), GEOSWKTReader_destroy_r(), GEOSWKTReader_read(), GEOSWKTReader_read_r(), GEOSWKTWriter_create(), GEOSWKTWriter_create_r(), GEOSWKTWriter_destroy(), GEOSWKTWriter_destroy_r(), GEOSWKTWriter_getOutputDimension(), GEOSWKTWriter_getOutputDimension_r(), GEOSWKTWriter_setOld3D(), GEOSWKTWriter_setOld3D_r(), GEOSWKTWriter_setOutputDimension(), GEOSWKTWriter_setOutputDimension_r(), GEOSWKTWriter_setRoundingPrecision(), GEOSWKTWriter_setRoundingPrecision_r(), GEOSWKTWriter_setTrim(), GEOSWKTWriter_setTrim_r(), GEOSWKTWriter_write(), GEOSWKTWriter_write_r(), initGEOS(), and initGEOS_r().