GEOS: geos::noding Namespace Reference
geos::noding Namespace Reference
Classes to compute nodings for arrangements of line segments and line segment sequences.
Namespaces
snapround
Contains classes to implement the Snap Rounding algorithm for noding linestrings.
Classes
class BasicSegmentString
class FastNodingValidator
Validates that a collection of SegmentStrings is correctly noded.
class FastSegmentSetIntersectionFinder
Finds if two sets of SegmentStringss intersect.
class GeometryNoder
class IntersectionAdder
class IntersectionFinderAdder
Finds proper and interior intersections in a set of SegmentStrings, and adds them as nodes.
class IteratedNoder
Nodes a set of SegmentStrings completely.
class MCIndexNoder
Nodes a set of SegmentString using a index based on index::chain::MonotoneChain and a index::SpatialIndex.
class MCIndexSegmentSetMutualIntersector
Intersects two sets of SegmentStrings using a index based on MonotoneChains and a SpatialIndex.
class NodableSegmentString
An interface for classes which support adding nodes to a segment string.
class NodedSegmentString
Represents a list of contiguous line segments, and supports noding the segments.
class Noder
Computes all intersections between segments in a set of SegmentString.
class NodingValidator
class Octant
Methods for computing and working with octants of the Cartesian plane.
class OrientedCoordinateArray
Allows comparing geom::CoordinateSequences in an orientation-independent way.
class ScaledNoder
Wraps a Noder and transforms its input into the integer domain.
class SegmentIntersectionDetector
Detects and records an intersection between two SegmentStrings, if one exists.
class SegmentIntersector
Processes possible intersections detected by a Noder.
class SegmentNode
Represents an intersection point between two NodedSegmentString.
class SegmentNodeList
A list of the SegmentNode present along a NodedSegmentString.
struct SegmentNodeLT
class SegmentPointComparator
class SegmentSetMutualIntersector
An intersector for the red-blue intersection problem.
class SegmentString
An interface for classes which represent a sequence of contiguous line segments.
class SegmentStringUtil
Utility methods for processing SegmentStrings.
class SimpleNoder
Nodes a set of SegmentStrings by performing a brute-force comparison of every segment to every other one.
class SingleInteriorIntersectionFinder
Finds an interior intersection in a set of SegmentString, if one exists. Only the first intersection found is reported.
class SinglePassNoder
Typedefs
typedef SegmentIntersector nodingSegmentIntersector
Temporary typedef for namespace transition.
Functions
ostream & operator<< (ostream &os, const SegmentNode &n)
std::ostream & operator<< (std::ostream &os, const SegmentNodeList &nlist)
std::ostream & operator<< (std::ostream &os, const SegmentString &ss)
bool operator< (const OrientedCoordinateArray &oca1, const OrientedCoordinateArray &oca2)
Strict weak ordering operator for OrientedCoordinateArray.
std::ostream & operator<< (std::ostream &os, const SegmentNode &n)
Detailed Description
Classes to compute nodings for arrangements of line segments and line segment sequences.
Typedef Documentation
typedef SegmentIntersector geos::noding::nodingSegmentIntersector
Temporary typedef for namespace transition.
Definition at line 84 of file SegmentIntersector.h.
Function Documentation
bool geos::noding::operator< (const OrientedCoordinateArray & oca1, const OrientedCoordinateArray & oca2) inline
Strict weak ordering operator for OrientedCoordinateArray.
This is the C++ equivalent of JTS's compareTo
Definition at line 104 of file OrientedCoordinateArray.h.
References geos::noding::OrientedCoordinateArray::compareTo().
 {
   return oca1.compareTo(oca2)<0;
 }
std::ostream & geos::noding::operator<< (std::ostream & os, const SegmentString & ss)
Definition at line 43 of file SegmentString.cpp.
References geos::noding::SegmentString::print().
 {
   return ss.print(os);
 }
ostream& geos::noding::operator<< (ostream & os, const SegmentNode & n)
Definition at line 98 of file SegmentNode.cpp.
References geos::noding::SegmentNode::coord, geos::noding::SegmentNode::segmentIndex, and geos::noding::SegmentNode::segmentOctant.
Referenced by geos::noding::SegmentNode::isInterior().
 {
   return os<<n.coord<<" seg#="<<n.segmentIndex<<" octant#="<<n.segmentOctant<<endl;
 }
std::ostream& geos::noding::operator<< (std::ostream & os, const SegmentNode & n)
std::ostream & geos::noding::operator<< (std::ostream & os, const SegmentNodeList & nlist)
Definition at line 289 of file SegmentNodeList.cpp.
References geos::noding::SegmentNodeList::nodeMap.
 {
   os << "Intersections: (" << nlist.nodeMap.size() << "):" << std::endl;
   std::set<SegmentNode*,SegmentNodeLT>::const_iterator
       it = nlist.nodeMap.begin(),
       itEnd = nlist.nodeMap.end();
   for(; it!=itEnd; it++)
   {
     SegmentNode *ei=*it;
     os << " " << *ei;
   }
   return os;
 }