GEOS: geos::geom Namespace Reference
geos::geom Namespace Reference
Contains the Geometry interface hierarchy and supporting classes.
Namespaces
prep
Contains classes and interfaces implementing algorithms that optimize the performance of repeated calls to specific geometric operations.
util
Provides classes that parse and modify Geometry objects.
Classes
class Coordinate
Coordinate is the lightweight class used to store coordinates.
class CoordinateArraySequence
The default implementation of CoordinateSequence.
class CoordinateArraySequenceFactory
Creates CoordinateSequences internally represented as an array of Coordinates.
class CoordinateFilter
struct CoordinateLessThen
Strict weak ordering Functor for Coordinate.
class CoordinateList
A list of Coordinates, which may be set to prevent repeated coordinates from occuring in the list.
class CoordinateSequence
The internal representation of a list of coordinates inside a Geometry.
class CoordinateSequenceFactory
A factory to create concrete instances of CoordinateSequences.
class CoordinateSequenceFilter
class Dimension
Constants representing the dimensions of a point, a curve and a surface.
class Envelope
An Envelope defines a rectangulare region of the 2D coordinate plane.
class Geometry
Basic implementation of Geometry, constructed and destructed by GeometryFactory.
class GeometryCollection
Represents a collection of heterogeneous Geometry objects.
class GeometryComponentFilter
class GeometryFactory
Supplies a set of utility methods for building Geometry objects from CoordinateSequence or other Geometry objects.
class GeometryFilter
Geometry classes support the concept of applying a Geometry filter to the Geometry.
struct GeometryGreaterThen
struct GeomPtrPair
class IntersectionMatrix
Implementation of Dimensionally Extended Nine-Intersection Model (DE-9IM) matrix.
class Lineal
class LinearRing
Models an OGC SFS LinearRing.
class LineSegment
class LineString
struct LineStringLT
class Location
Constants representing the location of a point relative to a geometry.
class MultiLineString
Models a collection of (}s.
class MultiPoint
class MultiPolygon
Models a collection of Polygons.
class Point
class Polygon
Represents a linear polygon, which may include holes.
class Polygonal
class PrecisionModel
Specifies the precision model of the Coordinate in a Geometry.
class Puntal
class Triangle
Represents a planar triangle, and provides methods for calculating various properties of triangles.
class TrianglePredicate
Typedefs
typedef CoordinateArraySequence DefaultCoordinateSequence
This is for backward API compatibility.
typedef CoordinateArraySequenceFactory DefaultCoordinateSequenceFactory
This is for backward API compatibility.
Enumerations
enum GeometryTypeId {
GEOS_POINT, GEOS_LINESTRING, GEOS_LINEARRING, GEOS_POLYGON,
GEOS_MULTIPOINT, GEOS_MULTILINESTRING, GEOS_MULTIPOLYGON, GEOS_GEOMETRYCOLLECTION
}
Geometry types.
Functions
std::ostream & operator<< (std::ostream &os, const Coordinate &c)
Output function.
std::ostream & operator<< (std::ostream &os, const CoordinateSequence &cs)
bool operator== (const CoordinateSequence &s1, const CoordinateSequence &s2)
bool operator!= (const CoordinateSequence &s1, const CoordinateSequence &s2)
std::ostream & operator<< (std::ostream &os, const Envelope &o)
Output operator.
bool operator== (const Envelope &a, const Envelope &b)
Checks if two Envelopes are equal (2D only check)
string geosversion ()
Return current GEOS version.
string jtsport ()
Return the version of JTS this GEOS release has been ported from.
std::ostream & operator<< (std::ostream &os, const Geometry &geom)
Write the Well-known Binary representation of this Geometry as an HEX string to the given output stream.
std::ostream & operator<< (std::ostream &os, const IntersectionMatrix &im)
bool operator== (const PrecisionModel &a, const PrecisionModel &b)
bool check_valid (const Geometry &g, const std::string &label, bool doThrow=false, bool validOnly=false)
std::unique_ptr< Geometry > fix_self_intersections (std::unique_ptr< Geometry > g, const std::string &label)
template<class BinOp >
std::unique_ptr< Geometry > SnapOp (const Geometry *g0, const Geometry *g1, BinOp _Op)
Apply a binary operation to the given geometries after snapping them to each other after common-bits removal.
template<class BinOp >
std::unique_ptr< Geometry > BinaryOp (const Geometry *g0, const Geometry *g1, BinOp _Op)
bool operator< (const Coordinate &a, const Coordinate &b)
Strict weak ordering operator for Coordinate.
GEOS_DLL bool operator== (const Coordinate &a, const Coordinate &b)
Equality operator for Coordinate. 2D only.
GEOS_DLL bool operator!= (const Coordinate &a, const Coordinate &b)
Inequality operator for Coordinate. 2D only.
std::ostream & operator<< (std::ostream &os, const CoordinateList &cl)
std::ostream & operator<< (std::ostream &o, const LineSegment &l)
bool operator== (const LineSegment &a, const LineSegment &b)
Checks if two LineSegment are equal (2D only check)
Variables
static CoordinateArraySequenceFactory defaultCoordinateSequenceFactory
Detailed Description
Contains the Geometry interface hierarchy and supporting classes.
The Java Topology Suite (JTS) is a Java API that implements a core set of spatial data operations using an explicit precision model and robust geometric algorithms. JTS is int ended to be used in the development of applications that support the validation, cleaning, integration and querying of spatial datasets.
JTS attempts to implement the OpenGIS Simple Features Specification (SFS) as accurately as possible. In some cases the SFS is unclear or omits a specification; in this case J TS attempts to choose a reasonable and consistent alternative. Differences from and elaborations of the SFS are documented in this specification.
Package Specification
Java Topology Suite Technical Specifications
OpenGIS Simple Features Specification for SQL
Typedef Documentation
typedef CoordinateArraySequence geos::geom::DefaultCoordinateSequence
This is for backward API compatibility.
Definition at line 127 of file CoordinateArraySequence.h.
typedef CoordinateArraySequenceFactory geos::geom::DefaultCoordinateSequenceFactory
This is for backward API compatibility.
Definition at line 62 of file CoordinateArraySequenceFactory.h.
Enumeration Type Documentation
enum geos::geom::GeometryTypeId
Geometry types.
Enumerator
GEOS_POINT
a point
GEOS_LINESTRING
a linestring
GEOS_LINEARRING
a linear ring (linestring with 1st point == last point)
GEOS_POLYGON
a polygon
GEOS_MULTIPOINT
a collection of points
GEOS_MULTILINESTRING
a collection of linestrings
GEOS_MULTIPOLYGON
a collection of polygons
GEOS_GEOMETRYCOLLECTION
a collection of heterogeneus geometries
Definition at line 75 of file Geometry.h.
                     {
   GEOS_POINT,
   GEOS_LINESTRING,
   GEOS_LINEARRING,
   GEOS_POLYGON,
   GEOS_MULTIPOINT,
   GEOS_MULTILINESTRING,
   GEOS_MULTIPOLYGON,
   GEOS_GEOMETRYCOLLECTION
 };
Function Documentation
template<class BinOp > std::unique_ptr<Geometry> geos::geom::BinaryOp (const Geometry * g0, const Geometry * g1, BinOp _Op)
Definition at line 343 of file BinaryOp.h.
References geos::precision::CommonBitsRemover::add(), geos::precision::CommonBitsRemover::addCommonBits(), check_valid(), geos::geom::Geometry::clone(), geos::geom::PrecisionModel::compareTo(), geos::geom::GeometryFactory::create(), geos::geom::GeometryFactory::createGeometry(), geos::geom::Geometry::getFactory(), geos::geom::GeometryFactory::getPrecisionModel(), geos::geom::PrecisionModel::getScale(), geos::ignore_unused_variable_warning(), geos::precision::GeometryPrecisionReducer::reduce(), geos::precision::CommonBitsRemover::removeCommonBits(), geos::simplify::TopologyPreservingSimplifier::simplify(), SnapOp(), geos::geom::Geometry::toString(), and geos::util::GEOSException::what().
Referenced by geos::geom::Geometry::difference(), geos::geom::Geometry::intersection(), geos::geom::Geometry::symDifference(), geos::geom::Geometry::Union(), and geos::operation::geounion::UnaryUnionOp::unionNoOpt().
 {
   typedef std::unique_ptr<Geometry> GeomPtr;
   GeomPtr ret;
   geos::util::TopologyException origException;
 #ifdef USE_ORIGINAL_INPUT
   // Try with original input
   try
   {
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "Trying with original input." << std::endl;
 #endif
     ret.reset(_Op(g0, g1));
 #if GEOS_CHECK_ORIGINAL_RESULT_VALIDITY
     check_valid(*ret, "Overlay result between original inputs", true, true);
 #endif
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "Attempt with original input succeeded" << std::endl;
 #endif
     return ret;
   }
   catch (const geos::util::TopologyException& ex)
   {
     origException=ex;
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "Original exception: " << ex.what() << std::endl;
 #endif
   }
 #endif // USE_ORIGINAL_INPUT
   check_valid(*g0, "Input geom 0", true, true);
   check_valid(*g1, "Input geom 1", true, true);
 #if USE_COMMONBITS_POLICY
   // Try removing common bits (possibly obsoleted by snapping below)
   //
   // NOTE: this policy was _later_ implemented
   //       in JTS as EnhancedPrecisionOp
   // TODO: consider using the now-ported EnhancedPrecisionOp
   //       here too
   //
   try
   {
     GeomPtr rG0;
     GeomPtr rG1;
     precision::CommonBitsRemover cbr;
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "Trying with Common Bits Remover (CBR)" << std::endl;
 #endif
     cbr.add(g0);
     cbr.add(g1);
     rG0.reset( cbr.removeCommonBits(g0->clone()) );
     rG1.reset( cbr.removeCommonBits(g1->clone()) );
 #if GEOS_DEBUG_BINARYOP
     check_valid(*rG0, "CBR: geom 0 (after common-bits removal)");
     check_valid(*rG1, "CBR: geom 1 (after common-bits removal)");
 #endif
     ret.reset( _Op(rG0.get(), rG1.get()) );
 #if GEOS_DEBUG_BINARYOP
     check_valid(*ret, "CBR: result (before common-bits addition)");
 #endif
     cbr.addCommonBits( ret.get() );
 #if GEOS_CHECK_COMMONBITS_VALIDITY
     check_valid(*ret, "CBR: result (after common-bits addition)", true);
 #endif
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "Attempt with CBR succeeded" << std::endl;
 #endif
     return ret;
   }
   catch (const geos::util::TopologyException& ex)
   {
         ::geos::ignore_unused_variable_warning(ex);
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "CBR: " << ex.what() << std::endl;
 #endif
   }
 #endif
   // Try with snapping
   //
   // TODO: possible optimization would be reusing the
   //       already common-bit-removed inputs and just
   //       apply geometry snapping, whereas the current
   //       SnapOp function does both.
 // {
 #if USE_SNAPPING_POLICY
 #if GEOS_DEBUG_BINARYOP
   std::cerr << "Trying with snapping " << std::endl;
 #endif
   try {
     ret = SnapOp(g0, g1, _Op);
 #if GEOS_CHECK_SNAPPINGOP_VALIDITY
     check_valid(*ret, "SNAP: result", true, true);
 #endif
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "SnapOp succeeded" << std::endl;
 #endif
     return ret;
   }
   catch (const geos::util::TopologyException& ex)
   {
         ::geos::ignore_unused_variable_warning(ex);
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "SNAP: " << ex.what() << std::endl;
 #endif
   }
 #endif // USE_SNAPPING_POLICY }
 // {
 #if USE_PRECISION_REDUCTION_POLICY
   // Try reducing precision
   try
   {
     long unsigned int g0scale =
             static_cast<long unsigned int>(g0->getFactory()->getPrecisionModel()->getScale());
     long unsigned int g1scale =
             static_cast<long unsigned int>(g1->getFactory()->getPrecisionModel()->getScale());
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "Original input scales are: "
               << g0scale
               << " and "
               << g1scale
               << std::endl;
 #endif
     double maxScale = 1e16;
     // Don't use a scale bigger than the input one
     if ( g0scale && static_cast<double>(g0scale) < maxScale ) maxScale = static_cast<double>(g0scale);
     if ( g1scale && static_cast<double>(g1scale) < maxScale ) maxScale = static_cast<double>(g1scale);
     for (double scale=maxScale; scale >= 1; scale /= 10)
     {
       PrecisionModel pm(scale);
       GeometryFactory::Ptr gf = GeometryFactory::create(&pm);
 #if GEOS_DEBUG_BINARYOP
       std::cerr << "Trying with scale " << scale << std::endl;
 #endif
       precision::GeometryPrecisionReducer reducer( *gf );
       GeomPtr rG0( reducer.reduce(*g0) );
       GeomPtr rG1( reducer.reduce(*g1) );
 #if GEOS_DEBUG_BINARYOP
       check_valid(*rG0, "PR: geom 0 (after precision reduction)");
       check_valid(*rG1, "PR: geom 1 (after precision reduction)");
 #endif
       try
       {
         ret.reset( _Op(rG0.get(), rG1.get()) );
         // restore original precision (least precision between inputs)
         if ( g0->getFactory()->getPrecisionModel()->compareTo( g1->getFactory()->getPrecisionModel() ) < 0 ) {
           ret.reset( g0->getFactory()->createGeometry(ret.get()) );
         }
         else {
           ret.reset( g1->getFactory()->createGeometry(ret.get()) );
         }
 #if GEOS_CHECK_PRECISION_REDUCTION_VALIDITY
         check_valid(*ret, "PR: result (after restore of original precision)", true);
 #endif
 #if GEOS_DEBUG_BINARYOP
         std::cerr << "Attempt with scale " << scale << " succeeded" << std::endl;
 #endif
         return ret;
       }
       catch (const geos::util::TopologyException& ex)
       {
 #if GEOS_DEBUG_BINARYOP
         std::cerr << "Reduced with scale (" << scale << "): "
                   << ex.what() << std::endl;
 #endif
         if ( scale == 1 ) throw ex;
       }
     }
   }
   catch (const geos::util::TopologyException& ex)
   {
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "Reduced: " << ex.what() << std::endl;
 #endif
     ::geos::ignore_unused_variable_warning(ex);
   }
 #endif
 // USE_PRECISION_REDUCTION_POLICY }
 // {
 #if USE_TP_SIMPLIFY_POLICY
   // Try simplifying
   try
   {
     double maxTolerance = 0.04;
     double minTolerance = 0.01;
     double tolStep = 0.01;
     for (double tol = minTolerance; tol <= maxTolerance; tol += tolStep)
     {
 #if GEOS_DEBUG_BINARYOP
       std::cerr << "Trying simplifying with tolerance " << tol << std::endl;
 #endif
       GeomPtr rG0( simplify::TopologyPreservingSimplifier::simplify(g0, tol) );
       GeomPtr rG1( simplify::TopologyPreservingSimplifier::simplify(g1, tol) );
       try
       {
         ret.reset( _Op(rG0.get(), rG1.get()) );
         return ret;
       }
       catch (const geos::util::TopologyException& ex)
       {
         if ( tol >= maxTolerance ) throw ex;
 #if GEOS_DEBUG_BINARYOP
         std::cerr << "Simplified with tolerance (" << tol << "): "
                   << ex.what() << std::endl;
 #endif
       }
     }
     return ret;
   }
   catch (const geos::util::TopologyException& ex)
   {
 #if GEOS_DEBUG_BINARYOP
     std::cerr << "Simplified: " << ex.what() << std::endl;
 #endif
   }
 #endif
 // USE_TP_SIMPLIFY_POLICY }
 #if GEOS_DEBUG_BINARYOP
   std::cerr << "No attempts worked to union " << std::endl;
   std::cerr << "Input geometries:" << std::endl
             << "<A>" << std::endl
             << g0->toString() << std::endl
             << "</A>" << std::endl
             << "<B>" << std::endl
             << g1->toString() << std::endl
             << "</B>" << std::endl;
 #endif
   throw origException;
 }
bool geos::geom::check_valid (const Geometry & g, const std::string & label, bool doThrow = false, bool validOnly = false) inline
Definition at line 171 of file BinaryOp.h.
References geos::algorithm::BoundaryNodeRule::getBoundaryEndPoint(), geos::operation::valid::IsValidOp::getValidationError(), geos::operation::IsSimpleOp::isSimple(), geos::operation::valid::IsValidOp::isValid(), geos::operation::valid::TopologyValidationError::toString(), and geos::geom::Geometry::toString().
Referenced by BinaryOp(), SnapOp(), and geos::operation::geounion::CascadedPolygonUnion::unionUsingEnvelopeIntersection().
 {
   if ( dynamic_cast<const Lineal*>(&g) ) {
     if ( ! validOnly ) {
       operation::IsSimpleOp sop(g, algorithm::BoundaryNodeRule::getBoundaryEndPoint());
       if ( ! sop.isSimple() )
       {
         if ( doThrow ) {
           throw geos::util::TopologyException(
             label + " is not simple");
         }
         return false;
       }
     }
   } else {
     operation::valid::IsValidOp ivo(&g);
     if ( ! ivo.isValid() )
     {
       using operation::valid::TopologyValidationError;
       TopologyValidationError* err = ivo.getValidationError();
 #ifdef GEOS_DEBUG_BINARYOP
       std::cerr << label << " is INVALID: "
         << err->toString()
         << " (" << std::setprecision(20)
         << err->getCoordinate() << ")"
         << std::endl
 #ifdef GEOS_DEBUG_BINARYOP_PRINT_INVALID
         << "<A>" << std::endl
         << g.toString()
         << std::endl
         << "</A>" << std::endl
 #endif
         ;
 #endif
       if ( doThrow ) {
         throw geos::util::TopologyException(
           label + " is invalid: " + err->toString(),
                 err->getCoordinate());
       }
       return false;
     }
   }
   return true;
 }
std::unique_ptr<Geometry> geos::geom::fix_self_intersections (std::unique_ptr< Geometry > g, const std::string & label) inline
Definition at line 223 of file BinaryOp.h.
References geos::operation::valid::TopologyValidationError::getErrorType(), and geos::ignore_unused_variable_warning().
 {
   ::geos::ignore_unused_variable_warning(label);
 #ifdef GEOS_DEBUG_BINARYOP
   std::cerr << label << " fix_self_intersection (UnaryUnion)" << std::endl;
 #endif
   // Only multi-components can be fixed by UnaryUnion
   if ( ! dynamic_cast<const GeometryCollection*>(g.get()) ) return g;
   using operation::valid::IsValidOp;
   IsValidOp ivo(g.get());
   // Polygon is valid, nothing to do
   if ( ivo.isValid() ) return g;
   // Not all invalidities can be fixed by this code
   using operation::valid::TopologyValidationError;
   TopologyValidationError* err = ivo.getValidationError();
   switch ( err->getErrorType() ) {
     case TopologyValidationError::eRingSelfIntersection:
     case TopologyValidationError::eTooFewPoints: // collapsed lines
 #ifdef GEOS_DEBUG_BINARYOP
       std::cerr << label << " ATTEMPT_TO_FIX: " << err->getErrorType() << ": " << *g << std::endl;
 #endif
       g = g->Union();
 #ifdef GEOS_DEBUG_BINARYOP
       std::cerr << label << " ATTEMPT_TO_FIX succeeded.. " << std::endl;
 #endif
       return g;
     case TopologyValidationError::eSelfIntersection:
       // this one is within a single component, won't be fixed
     default:
 #ifdef GEOS_DEBUG_BINARYOP
       std::cerr << label << " invalidity is: " << err->getErrorType() << std::endl;
 #endif
       return g;
   }
 }
std::string geos::geom::geosversion ()
Return current GEOS version.
Definition at line 92 of file Geometry.cpp.
 {
   return GEOS_VERSION;
 }
std::string geos::geom::jtsport ()
Return the version of JTS this GEOS release has been ported from.
Definition at line 102 of file Geometry.cpp.
 {
   return GEOS_JTS_PORT;
 }
INLINE bool geos::geom::operator!= (const Coordinate & a, const Coordinate & b)
Inequality operator for Coordinate. 2D only.
Definition at line 127 of file Coordinate.inl.
References geos::geom::Coordinate::equals2D().
 {
   return ! a.equals2D(b);
 }
GEOS_DLL bool geos::geom::operator!= (const CoordinateSequence & s1, const CoordinateSequence & s2)
Definition at line 291 of file CoordinateSequence.cpp.
Referenced by geos::geom::CoordinateSequence::applyCoordinateFilter(), and operator<().
 {
   return ! CoordinateSequence::equals(&s1, &s2);
 }
bool geos::geom::operator< (const Coordinate & a, const Coordinate & b) inline
Strict weak ordering operator for Coordinate.
Definition at line 135 of file Coordinate.h.
References GEOS_DLL, operator!=(), operator<<(), and operator==().
{
   return CoordinateLessThen()(a,b);
 }
GEOS_DLL std::ostream & geos::geom::operator<< (std::ostream & os, const Coordinate & c)
Output function.
Definition at line 47 of file Coordinate.cpp.
References geos::geom::Coordinate::x, geos::geom::Coordinate::y, and geos::geom::Coordinate::z.
Referenced by geos::noding::SegmentNodeList::addSplitEdges(), geos::geom::CoordinateSequence::applyCoordinateFilter(), geos::geomgraph::EdgeIntersectionList::end(), operator<(), geos::geomgraph::operator==(), and geos::geomgraph::Edge::testInvariant().
 {
   if ( ISNAN(c.z) )
   {
     os << c.x << " " << c.y;
   } else {
     os << c.x << " " << c.y << " " << c.z;
   }
   return os;
 }
std::ostream& geos::geom::operator<< (std::ostream & os, const CoordinateList & cl) inline
Definition at line 176 of file CoordinateList.h.
References geos::geom::CoordinateList::begin(), and geos::geom::CoordinateList::end().
 {
   os << "(";
   for (CoordinateList::const_iterator
     it=cl.begin(), end=cl.end();
     it != end;
     ++it)
   {
     const Coordinate& c = *it;
     if ( it != cl.begin() ) os << ", ";
     os << c;
   }
   os << ")";
   return os;
 }
GEOS_DLL std::ostream & geos::geom::operator<< (std::ostream & os, const CoordinateSequence & cs)
Definition at line 272 of file CoordinateSequence.cpp.
References geos::geom::CoordinateSequence::size().
 {
   os << "(";
   for (size_t i=0, n=cs.size(); i<n; ++i)
   {
     const Coordinate& c = cs[i];
     if ( i ) os << ", ";
     os << c;
   }
   os << ")";
   return os;
 }
GEOS_DLL std::ostream & geos::geom::operator<< (std::ostream & os, const Envelope & o)
Output operator.
Definition at line 336 of file Envelope.cpp.
References geos::geom::Envelope::maxx, geos::geom::Envelope::maxy, geos::geom::Envelope::minx, and geos::geom::Envelope::miny.
 {
   os << "Env[" << o.minx << ":" << o.maxx << ","
      << o.miny << ":" << o.maxy << "]";
   return os;
 }
INLINE std::ostream & geos::geom::operator<< (std::ostream & o, const LineSegment & l)
Definition at line 181 of file LineSegment.inl.
References INLINE, geos::geom::LineSegment::p0, geos::geom::LineSegment::p1, geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   return o<<"LINESEGMENT("<<l.p0.x<<" "<<l.p0.y<<","<<l.p1.x<<" "<<l.p1.y<<")";
 }
GEOS_DLL std::ostream & geos::geom::operator<< (std::ostream & os, const IntersectionMatrix & im)
Definition at line 431 of file IntersectionMatrix.cpp.
References geos::geom::IntersectionMatrix::toString().
 {
   return os << im.toString();
 }
GEOS_DLL std::ostream & geos::geom::operator<< (std::ostream & os, const Geometry & geom)
Write the Well-known Binary representation of this Geometry as an HEX string to the given output stream.
Definition at line 466 of file Geometry.cpp.
References geos::io::WKBWriter::writeHEX().
 {
   io::WKBWriter writer;
   writer.writeHEX(geom, os);
   return os;
 }
INLINE bool geos::geom::operator== (const Coordinate & a, const Coordinate & b)
Equality operator for Coordinate. 2D only.
Definition at line 121 of file Coordinate.inl.
References geos::geom::Coordinate::equals2D(), and INLINE.
 {
   return a.equals2D(b);
 }
bool geos::geom::operator== (const PrecisionModel & a, const PrecisionModel & b)
Definition at line 220 of file PrecisionModel.cpp.
References geos::geom::PrecisionModel::getScale(), and geos::geom::PrecisionModel::isFloating().
{
   return a.isFloating() == b.isFloating() &&
       a.getScale() == b.getScale();
 }
GEOS_DLL bool geos::geom::operator== (const CoordinateSequence & s1, const CoordinateSequence & s2)
Definition at line 286 of file CoordinateSequence.cpp.
Referenced by geos::geom::CoordinateSequence::applyCoordinateFilter(), and operator<().
 {
   return CoordinateSequence::equals(&s1, &s2);
 }
GEOS_DLL bool geos::geom::operator== (const Envelope & a, const Envelope & b)
Checks if two Envelopes are equal (2D only check)
Definition at line 372 of file Envelope.cpp.
References geos::geom::Envelope::getMaxX(), geos::geom::Envelope::getMaxY(), geos::geom::Envelope::getMinX(), geos::geom::Envelope::getMinY(), and geos::geom::Envelope::isNull().
 {
   if (a.isNull()) {
     return b.isNull();
   }
   if (b.isNull()) {
     return a.isNull();
   }
   return a.getMaxX() == b.getMaxX() &&
        a.getMaxY() == b.getMaxY() &&
        a.getMinX() == b.getMinX() &&
        a.getMinY() == b.getMinY();
 }
INLINE bool geos::geom::operator== (const LineSegment & a, const LineSegment & b)
Checks if two LineSegment are equal (2D only check)
Definition at line 187 of file LineSegment.inl.
References geos::geom::LineSegment::p0, and geos::geom::LineSegment::p1.
 {
   return a.p0==b.p0 && a.p1==b.p1;
 }
template<class BinOp > std::unique_ptr<Geometry> geos::geom::SnapOp (const Geometry * g0, const Geometry * g1, BinOp _Op)
Apply a binary operation to the given geometries after snapping them to each other after common-bits removal.
Definition at line 273 of file BinaryOp.h.
References geos::precision::CommonBitsRemover::add(), geos::precision::CommonBitsRemover::addCommonBits(), check_valid(), geos::geom::Geometry::clone(), geos::precision::CommonBitsRemover::getCommonCoordinate(), and geos::precision::CommonBitsRemover::removeCommonBits().
Referenced by BinaryOp().
 {
   typedef std::unique_ptr<Geometry> GeomPtr;
   //using geos::precision::GeometrySnapper;
   using geos::operation::overlay::snap::GeometrySnapper;
   // Snap tolerance must be computed on the original
   // (not commonbits-removed) geoms
   double snapTolerance = GeometrySnapper::computeOverlaySnapTolerance(*g0, *g1);
 #if GEOS_DEBUG_BINARYOP
   std::cerr<< std::setprecision(20) << "Computed snap tolerance: "<<snapTolerance<<std::endl;
 #endif
 #if CBR_BEFORE_SNAPPING
   // Compute common bits
   geos::precision::CommonBitsRemover cbr;
   cbr.add(g0); cbr.add(g1);
 #if GEOS_DEBUG_BINARYOP
   std::cerr<<"Computed common bits: "<<cbr.getCommonCoordinate()<<std::endl;
 #endif
   // Now remove common bits
   GeomPtr rG0( cbr.removeCommonBits(g0->clone()) );
   GeomPtr rG1( cbr.removeCommonBits(g1->clone()) );
 #if GEOS_DEBUG_BINARYOP
   check_valid(*rG0, "CBR: removed-bits geom 0");
   check_valid(*rG1, "CBR: removed-bits geom 1");
 #endif
   const Geometry& operand0 = *rG0;
   const Geometry& operand1 = *rG1;
 #else // don't CBR before snapping
   const Geometry& operand0 = *g0;
   const Geometry& operand1 = *g1;
 #endif
   GeometrySnapper snapper0( operand0 );
   GeomPtr snapG0( snapper0.snapTo(operand1, snapTolerance) );
   //snapG0 = fix_self_intersections(snapG0, "SNAP: snapped geom 0");
   // NOTE: second geom is snapped on the snapped first one
   GeometrySnapper snapper1( operand1 );
   GeomPtr snapG1( snapper1.snapTo(*snapG0, snapTolerance) );
   //snapG1 = fix_self_intersections(snapG1, "SNAP: snapped geom 1");
   // Run the binary op
   GeomPtr result( _Op(snapG0.get(), snapG1.get()) );
 #if GEOS_DEBUG_BINARYOP
   check_valid(*result, "SNAP: result (before common-bits addition");
 #endif
 #if CBR_BEFORE_SNAPPING
   // Add common bits back in
   cbr.addCommonBits( result.get() );
   //result = fix_self_intersections(result, "SNAP: result (after common-bits addition)");
   check_valid(*result, "CBR: result (after common-bits addition)", true);
 #endif
   return result;
 }
Variable Documentation
CoordinateArraySequenceFactory geos::geom::defaultCoordinateSequenceFactory static
Definition at line 26 of file CoordinateArraySequenceFactory.cpp.
Referenced by geos::geom::CoordinateArraySequenceFactory::instance().