GEOS: geos Namespace Reference
geos Namespace Reference
for EnvelopeIntersectsVisitor inheritance
Namespaces
algorithm
Contains classes and interfaces implementing fundamental computational geometry algorithms.
geom
Contains the Geometry interface hierarchy and supporting classes.
geomgraph
Contains classes that implement topology graphs.
index
Provides classes for various kinds of spatial indexes.
io
Contains the interfaces for converting JTS objects to and from other formats.
linearref
noding
Classes to compute nodings for arrangements of line segments and line segment sequences.
operation
Provides classes for implementing operations on geometries.
planargraph
Contains classes to implement a planar graph data structure.
precision
Provides classes for manipulating the precision model of Geometries.
simplify
Line simplification algorithms.
triangulate
util
Functions
template<class T >
void ignore_unused_variable_warning (T const &)
Detailed Description
for EnvelopeIntersectsVisitor inheritance
Basic namespace for all GEOS functionalities.
A pair of Boundables, whose leaf items support a distance metric between them. Used to compute the distance between the members, and to expand a member relative to the other in order to produce new branches of the Branch-and-Bound evaluation tree. Provides an ordering based on the distance between the members, which allows building a priority queue by minimum distance.
Author
Martin Davis
Function Documentation
template<class T > void geos::ignore_unused_variable_warning (T const &)
Definition at line 41 of file util.h.
Referenced by geos::operation::buffer::OffsetSegmentGenerator::addInsideTurn(), geos::noding::NodedSegmentString::addIntersection(), geos::operation::buffer::OffsetSegmentGenerator::addLimitedMitreJoin(), geos::operation::buffer::OffsetSegmentGenerator::addMitreJoin(), geos::geom::BinaryOp(), geos::operation::overlay::OverlayOp::checkObviouslyWrongResult(), geos::operation::overlay::validate::FuzzyPointLocator::extractLineWork(), geos::precision::Translater::filter_ro(), geos::geom::GeometryComponentFilter::filter_ro(), geos::noding::ScaledNoder::filter_ro(), geos::noding::ScaledNoder::ReScaler::filter_ro(), geos::geom::GeometryComponentFilter::filter_rw(), geos::precision::CommonCoordinateFilter::filter_rw(), geos::geom::fix_self_intersections(), geos::operation::overlay::validate::FuzzyPointLocator::getLineWork(), geos::operation::overlay::snap::SnapIfNeededOverlayOp::getResultGeometry(), geos::operation::polygonize::EdgeRing::getRingInternal(), geos::triangulate::quadedge::QuadEdgeSubdivision::locateFromEdge(), geos::noding::Octant::octant(), geos::operation::overlay::PointBuilder::PointBuilder(), geos::geom::PrecisionModel::PrecisionModel(), geos::noding::snapround::HotPixelSnapAction::select(), geos::simplify::DPTransformer::transformCoordinates(), geos::operation::overlay::snap::SnapTransformer::transformCoordinates(), geos::geom::util::GeometryTransformer::transformCoordinates(), geos::geom::util::GeometryTransformer::transformGeometryCollection(), geos::geom::util::GeometryTransformer::transformLinearRing(), geos::geom::util::GeometryTransformer::transformLineString(), geos::geom::util::GeometryTransformer::transformMultiLineString(), geos::geom::util::GeometryTransformer::transformMultiPoint(), geos::geom::util::GeometryTransformer::transformMultiPolygon(), geos::geom::util::GeometryTransformer::transformPoint(), geos::geom::util::GeometryTransformer::transformPolygon(), and geos::index::quadtree::NodeBase::visitItems().
 {}