GEOS: geos::util Namespace Reference
geos::util Namespace Reference
Classes
class Assert
class AssertionFailedException
Indicates a bug in GEOS code.
class CoordinateArrayFilter
class GeometricShapeFactory
class GEOSException
Base class for all GEOS exceptions.
class IllegalArgumentException
Indicates one or more illegal arguments.
class IllegalStateException
Indicates an illegal state.
class Interrupt
class InterruptedException
class Profile
class Profiler
class TopologyException
Indicates an invalid or inconsistent topological situation encountered during processing.
class UniqueCoordinateArrayFilter
class UnsupportedOperationException
Indicates that the requested operation is unsupported.
Functions
double sym_round (double val)
Symmetric Rounding Algorithm.
double java_math_round (double val)
Asymmetric Rounding Algorithm.
double rint_vc (double val)
Equivalent to Java Math.rint()
ostream & operator<< (ostream &os, const Profile &prof)
ostream & operator<< (ostream &os, const Profiler &prof)
GEOS_DLL std::ostream & operator<< (std::ostream &os, const Profile &)
Return a string representing the Profile.
GEOS_DLL std::ostream & operator<< (std::ostream &os, const Profiler &)
Return a string representing the Profiler.
double round (double val)
Function Documentation
double geos::util::java_math_round (double val)
Asymmetric Rounding Algorithm.
Definition at line 51 of file math.cpp.
Referenced by round().
 {
   double n;
   double f = std::fabs(std::modf(val, &n));
   if (val >= 0)
   {
     if (f < 0.5) {
       return std::floor(val);
     } else if (f > 0.5) {
       return std::ceil(val);
     } else {
       return (n + 1.0);
     }
   } else {
     if (f < 0.5) {
       return std::ceil(val);
     } else if (f > 0.5) {
       return std::floor(val);
     } else {
       return n;
     }
   }
 } // java_math_round
ostream& geos::util::operator<< (ostream & os, const Profile & prof)
Definition at line 121 of file Profiler.cpp.
References geos::util::Profile::getAvg(), geos::util::Profile::getMax(), geos::util::Profile::getMin(), geos::util::Profile::getNumTimings(), geos::util::Profile::getTot(), and geos::util::Profile::name.
 {
   os << " num:"<<prof.getNumTimings()<<" min:"<<
     prof.getMin()<<" max:"<<prof.getMax()<<
     " avg:"<<prof.getAvg()<<" tot:"<<prof.getTot()<<
     " ["<<prof.name<<"]";
   return os;
 }
ostream& geos::util::operator<< (ostream & os, const Profiler & prof)
Definition at line 131 of file Profiler.cpp.
References geos::util::Profiler::profs.
 {
   map<string, Profile *>::const_iterator it;
   for ( it=prof.profs.begin(); it != prof.profs.end(); ++it )
   {
     os<<*(it->second)<<endl;
   }
   return os;
 }
GEOS_DLL std::ostream& geos::util::operator<< (std::ostream & os, const Profile &)
Return a string representing the Profile.
GEOS_DLL std::ostream& geos::util::operator<< (std::ostream & os, const Profiler &)
Return a string representing the Profiler.
double geos::util::rint_vc (double val)
Equivalent to Java Math.rint()
Definition at line 80 of file math.cpp.
 {
   double n;
   double f=std::fabs(std::modf(val,&n));
   if (val>=0) {
     if (f<0.5) {
       return std::floor(val);
     } else if (f>0.5) {
       return std::ceil(val);
     } else {
       return(std::floor(n/2)==n/2)?n:n+1.0;
     }
   } else {
     if (f<0.5) {
       return std::ceil(val);
     } else if (f>0.5) {
       return std::floor(val);
     } else {
       return(std::floor(n/2)==n/2)?n:n-1.0;
     }
   }
 }
double geos::util::round (double val) inline
Default rounding method for GEOS
Note
Always use this rounding method, to easy easy switching between different rounding method for the whole codebase.
Definition at line 34 of file math.h.
References java_math_round().
Referenced by geos::algorithm::distance::DiscreteFrechetDistance::compute(), geos::noding::ScaledNoder::Scaler::filter_rw(), geos::algorithm::distance::DiscreteFrechetDistance::getSegementAt(), geos::geom::PrecisionModel::makePrecise(), and geos::noding::snapround::HotPixel::scale().
 {
   return java_math_round(val);
 }
double geos::util::sym_round (double val)
Symmetric Rounding Algorithm.
Definition at line 25 of file math.cpp.
 {
         double n;
         double f = std::fabs(std::modf(val, &n));
         if (val >= 0) {
                 if (f < 0.5) {
                         return std::floor(val);
                 } else if (f > 0.5) {
                         return std::ceil(val);
                 } else {
                         return (n + 1.0);
                 }
         } else {
                 if (f < 0.5) {
                         return std::ceil(val);
                 } else if (f > 0.5) {
                         return std::floor(val);
                 } else {
                         return (n - 1.0);
                 }
         }
 }