GEOS: geos::operation::intersection Namespace Reference
geos::operation::intersection Namespace Reference
Classes
class Rectangle
Clipping rectangle.
class RectangleIntersection
Speed-optimized clipping of a Geometry with a rectangle.
class RectangleIntersectionBuilder
Rebuild geometries from subpaths left by clipping with a rectangle.
Functions
bool different (double x1, double y1, double x2, double y2)
Test if two coordinates are different.
void clip_one_edge (double &x1, double &y1, double x2, double y2, double limit)
Calculate a line intersection point.
void clip_to_edges (double &x1, double &y1, double x2, double y2, const Rectangle &rect)
Start point is outside, endpoint is definitely inside.
double distance (const Rectangle &rect, double x1, double y1, double x2, double y2)
double distance (const Rectangle &rect, const std::vector< Coordinate > &ring, const geom::LineString *line)
double distance (const Rectangle &rect, const std::vector< Coordinate > &ring)
void reverse_points (std::vector< Coordinate > &v, int start, int end)
Reverse given segment in a coordinate vector.
void normalize_ring (std::vector< Coordinate > &ring)
Normalize a ring into lexicographic order.
Function Documentation
void geos::operation::intersection::clip_one_edge (double & x1, double & y1, double x2, double y2, double limit) inline
Calculate a line intersection point.
Note:
Calling this with x1,y1 and x2,y2 swapped cuts the other end of the line
Calling this with x and y swapped cuts in y-direction instead
Calling with 1<->2 and x<->y swapped works too
Definition at line 61 of file RectangleIntersection.cpp.
Referenced by clip_to_edges().
 {
   if(x1 != x2)
   {
     y1 += (y2-y1)*(limit-x1)/(x2-x1);
     x1 = limit;
   }
 }
void geos::operation::intersection::clip_to_edges (double & x1, double & y1, double x2, double y2, const Rectangle & rect)
Start point is outside, endpoint is definitely inside.
Note: Even though one might think using >= etc operators would produce the same result, that is not the case. We rely on the fact that nothing is clipped unless the point is truly outside the rectangle! Without this handling lines ending on the edges of the rectangle would be very difficult.
Definition at line 80 of file RectangleIntersection.cpp.
References clip_one_edge(), geos::operation::intersection::Rectangle::xmax(), geos::operation::intersection::Rectangle::xmin(), geos::operation::intersection::Rectangle::ymax(), and geos::operation::intersection::Rectangle::ymin().
Referenced by geos::operation::intersection::RectangleIntersection::clip_linestring_parts().
 {
   if(x1 < rect.xmin())
   clip_one_edge(x1,y1,x2,y2,rect.xmin());
   else if(x1 > rect.xmax())
   clip_one_edge(x1,y1,x2,y2,rect.xmax());
   if(y1<rect.ymin())
   clip_one_edge(y1,x1,y2,x2,rect.ymin());
   else if(y1>rect.ymax())
   clip_one_edge(y1,x1,y2,x2,rect.ymax());
 }
bool geos::operation::intersection::different (double x1, double y1, double x2, double y2) inline
Test if two coordinates are different.
Definition at line 46 of file RectangleIntersection.cpp.
Referenced by geos::operation::intersection::RectangleIntersection::clip_linestring_parts().
 {
   return !(x1==x2 && y1==y2);
 }
double geos::operation::intersection::distance (const Rectangle & rect, double x1, double y1, double x2, double y2)
Distance of 1st point of linestring to last point of linearring along rectangle edges
Definition at line 178 of file RectangleIntersectionBuilder.cpp.
References geos::operation::intersection::Rectangle::Left, geos::operation::intersection::Rectangle::nextEdge(), geos::operation::intersection::Rectangle::position(), geos::operation::intersection::Rectangle::Right, geos::operation::intersection::Rectangle::Top, geos::operation::intersection::Rectangle::xmax(), geos::operation::intersection::Rectangle::xmin(), geos::operation::intersection::Rectangle::ymax(), and geos::operation::intersection::Rectangle::ymin().
Referenced by geos::geom::Geometry::applyComponentFilter(), geos::operation::buffer::BufferBuilder::bufferLineSingleSided(), geos::precision::MinimumClearance::compute(), geos::operation::buffer::OffsetCurveBuilder::computeLineBufferCurve(), geos::operation::buffer::OffsetCurveBuilder::computePointCurve(), geos::operation::buffer::OffsetCurveBuilder::computeRingBufferCurve(), geos::operation::buffer::OffsetCurveBuilder::computeSingleSidedBufferCurve(), geos::geom::Geometry::coveredBy(), geos::geom::Envelope::covers(), distance(), geos::geom::Geometry::distance(), geos::simplify::TaggedLineStringSimplifier::findFurthestPoint(), GEOSDistanceIndexed_r(), GEOSFrechetDistance_r(), GEOSFrechetDistanceDensify_r(), GEOSHausdorffDistance_r(), GEOSHausdorffDistanceDensify_r(), GEOSSTRtree_nearest_generic_r(), geos::operation::buffer::OffsetCurveBuilder::getBufferParameters(), geos::operation::distance::IndexedFacetDistance::getDistance(), geos::operation::buffer::OffsetCurveBuilder::getLineCurve(), geos::operation::buffer::OffsetCurveBuilder::getRingCurve(), geos::operation::distance::IndexedFacetDistance::IndexedFacetDistance(), geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons(), geos::operation::buffer::BufferBuilder::setNoder(), geos::simplify::DouglasPeuckerLineSimplifier::simplifySection(), and geos::simplify::TaggedLineStringSimplifier::simplifySection().
 {
   double dist = 0;
   Rectangle::Position pos = rect.position(x1,y1);
   Rectangle::Position endpos = rect.position(x2,y2);
   while(true)
   {
     // Close up when we have the same edge and the
     // points are in the correct clockwise order
     if((pos & endpos) != 0 &&
      (
       (x1==rect.xmin() && y2>=y1) ||
       (y1==rect.ymax() && x2>=x1) ||
       (x1==rect.xmax() && y2<=y1) ||
       (y1==rect.ymin() && x2<=x1))
       )
     {
       dist += fabs(x2-x1) + fabs(y2-y1);
       break;
     }
     pos = Rectangle::nextEdge(pos);
     if(pos & Rectangle::Left)
     {
       dist += x1-rect.xmin();
       x1 = rect.xmin();
     }
     else if(pos & Rectangle::Top)
     {
       dist += rect.ymax()-y1;
       y1 = rect.ymax();
     }
     else if(pos & Rectangle::Right)
     {
       dist += rect.xmax()-x1;
       x1 = rect.xmax();
     }
     else
     {
       dist += y1-rect.ymin();
       y1 = rect.ymin();
     }
   }
   return dist;
 }
double geos::operation::intersection::distance (const Rectangle & rect, const std::vector< Coordinate > & ring, const geom::LineString * line)
Definition at line 228 of file RectangleIntersectionBuilder.cpp.
References distance(), geos::geom::CoordinateSequence::getAt(), geos::geom::LineString::getCoordinatesRO(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   auto nr = ring.size();
   const Coordinate &c1 = ring[nr-1];
   const CoordinateSequence * linecs = line->getCoordinatesRO();
   const Coordinate &c2 = linecs->getAt(0);
   return distance(rect,c1.x,c1.y,c2.x,c2.y);
 }
double geos::operation::intersection::distance (const Rectangle & rect, const std::vector< Coordinate > & ring)
Definition at line 241 of file RectangleIntersectionBuilder.cpp.
References distance(), geos::geom::Coordinate::x, and geos::geom::Coordinate::y.
 {
   auto nr = ring.size();
   const Coordinate& c1 = ring[nr-1]; // TODO: ring.back() ?
   const Coordinate& c2 = ring[0]; // TODO: ring.front() ?
   return distance(rect, c1.x, c1.y, c2.x, c2.y);
 }
void geos::operation::intersection::normalize_ring (std::vector< Coordinate > & ring)
Normalize a ring into lexicographic order.
Definition at line 272 of file RectangleIntersectionBuilder.cpp.
References reverse_points().
Referenced by geos::operation::intersection::RectangleIntersectionBuilder::reconnectPolygons().
 {
   if(ring.empty())
   return;
   // Find the "smallest" coordinate
   int best_pos = 0;
   int n = static_cast<int>(ring.size());
   for(int pos = 0; pos<n; ++pos)
   {
     // TODO: use CoordinateLessThan ?
     if(ring[pos].x < ring[best_pos].x)
     best_pos = pos;
     else if(ring[pos].x == ring[best_pos].x &&
         ring[pos].y < ring[best_pos].y )
     best_pos = pos;
   }
   // Quick exit if the ring is already normalized
   if(best_pos == 0)
   return;
   // Flip hands -algorithm to the part without the
   // duplicate last coordinate at n-1:
   reverse_points(ring,0,best_pos-1);
   reverse_points(ring,best_pos,n-2);
   reverse_points(ring,0,n-2);
   // And make sure the ring is valid by duplicating the first coordinate
   // at the end:
   geom::Coordinate c;
   c = ring[0];
   ring[n-1] = c;
 }
void geos::operation::intersection::reverse_points (std::vector< Coordinate > & v, int start, int end)
Reverse given segment in a coordinate vector.
Definition at line 253 of file RectangleIntersectionBuilder.cpp.
Referenced by normalize_ring().
 {
   geom::Coordinate p1;
   geom::Coordinate p2;
   while(start < end)
   {
     p1 = v[start];
     p2 = v[end];
     v[start] = p2;
     v[end] = p1;
     ++start;
     --end;
   }
 }