GEOS: geos::index::strtree Namespace Reference
geos::index::strtree Namespace Reference
Contains 2-D and 1-D versions of the Sort-Tile-Recursive (STR) tree, a query-only R-tree.
Classes
class AbstractNode
A node of the STR tree.
class AbstractSTRtree
Base class for STRtree and SIRtree.
class Boundable
A spatial object in an AbstractSTRtree.
class BoundablePair
class GeometryItemDistance
class Interval
A contiguous portion of 1D-space. Used internally by SIRtree.
class ItemBoundable
Boundable wrapper for a non-Boundable spatial object. Used internally by AbstractSTRtree.
class ItemDistance
class ItemsList
class ItemsListItem
class SIRAbstractNode
class SIRtree
One-dimensional version of an STR-packed R-tree.
class STRAbstractNode
class STRtree
A query-only R-tree created using the Sort-Tile-Recursive (STR) algorithm. For two-dimensional spatial data.
Typedefs
typedef std::vector< Boundable * > BoundableList
A list of boundables. TODO: use a list.
Functions
static bool compareSIRBoundables (Boundable *a, Boundable *b)
static bool yComparator (Boundable *a, Boundable *b)
Detailed Description
Contains 2-D and 1-D versions of the Sort-Tile-Recursive (STR) tree, a query-only R-tree.
Typedef Documentation
typedef std::vector<Boundable*> geos::index::strtree::BoundableList
A list of boundables. TODO: use a list.
Definition at line 44 of file AbstractSTRtree.h.
Function Documentation
static bool geos::index::strtree::compareSIRBoundables (Boundable * a, Boundable * b) static
Definition at line 31 of file SIRtree.cpp.
References geos::index::strtree::Boundable::getBounds().
Referenced by geos::index::strtree::SIRtree::sortBoundables().
{
   return AbstractSTRtree::compareDoubles(((Interval*)a->getBounds())->getCentre(),((Interval*)b->getBounds())->getCentre());
 }
static bool geos::index::strtree::yComparator (Boundable * a, Boundable * b) static
Definition at line 40 of file STRtree.cpp.
References centreY, and geos::index::strtree::Boundable::getBounds().
Referenced by geos::index::strtree::STRtree::sortBoundables().
 {
   assert(a);
   assert(b);
   const void* aBounds = a->getBounds();
   const void* bBounds = b->getBounds();
   assert(aBounds);
   assert(bBounds);
   const Envelope* aEnv = static_cast<const Envelope*>(aBounds);
   const Envelope* bEnv = static_cast<const Envelope*>(bBounds);
     // NOTE - mloskot:
     // The problem of instability is directly related to mathematical definition of
     // "strict weak ordering" as a fundamental requirement for binary predicate:
     //
     // if a is less than b then b is not less than a,
     // if a is less than b and b is less than c
     // then a is less than c,
     // and so on.
     //
     // For some very low values, this predicate does not fulfill this requiremnet,
     // NOTE - strk:
   // It seems that the '<' comparison here gives unstable results.
   // In particular, when inlines are on (for Envelope::getMinY and getMaxY)
   // things are fine, but when they are off we can even get a memory corruption !!
   //return STRtree::centreY(aEnv) < STRtree::centreY(bEnv);
     // NOTE - mloskot:
     // This comparison does not answer if a is "lower" than b
     // what is required for sorting. This comparison only answeres
     // if a and b are "almost the same" or different
     /*NOTE - cfis
       In debug mode VC++ checks the predicate in both directions.
       If !_Pred(_Left, _Right)
       Then an exception is thrown if _Pred(_Right, _Left).
       See xutility around line 320:
         bool __CLRCALL_OR_CDECL _Debug_lt_pred(_Pr _Pred, _Ty1& _Left, _Ty2& _Right,
     const wchar_t *_Where, unsigned int _Line)*/
     //return std::fabs( STRtree::centreY(aEnv) - STRtree::centreY(bEnv) ) < 1e-30
     // NOTE - strk:
     // See http://trac.osgeo.org/geos/ticket/293
     // as for why simple comparison (<) isn't used here
     return AbstractSTRtree::compareDoubles(STRtree::centreY(aEnv),
                                            STRtree::centreY(bEnv));
 }