GEOS: geos::operation::buffer Namespace Reference
geos::operation::buffer Namespace Reference
Provides classes for computing buffers of geometries.
Classes
class BufferBuilder
Builds the buffer geometry for a given input geometry and precision model.
class BufferInputLineSimplifier
Simplifies a buffer input line to remove concavities with shallow depth.
class BufferOp
Computes the buffer of a geometry, for both positive and negative buffer distances.
class BufferParameters
Contains the parameters which describe how a buffer should be constructed.
class BufferSubgraph
A connected subset of the graph of DirectedEdge and geomgraph::Node.
class DepthSegment
struct DepthSegmentLessThen
class OffsetCurveBuilder
Computes the raw offset curve for a single Geometry component (ring, line or point).
class OffsetCurveSetBuilder
Creates all the raw offset curves for a buffer of a Geometry.
class OffsetSegmentGenerator
class OffsetSegmentString
A dynamic list of the vertices in a constructed offset curve.
class RightmostEdgeFinder
A RightmostEdgeFinder find the geomgraph::DirectedEdge in a list which has the highest coordinate, and which is oriented L to R at that point. (I.e. the right side is on the RHS of the edge.)
class SubgraphDepthLocater
Locates a subgraph inside a set of subgraphs, in order to determine the outside depth of the subgraph.
Functions
bool BufferSubgraphGT (BufferSubgraph *first, BufferSubgraph *second)
std::ostream & operator<< (std::ostream &os, const BufferSubgraph &bs)
std::ostream & operator<< (std::ostream &os, const OffsetSegmentString &lst)
Detailed Description
Provides classes for computing buffers of geometries.
Function Documentation
bool geos::operation::buffer::BufferSubgraphGT (BufferSubgraph * first, BufferSubgraph * second)
Definition at line 616 of file BufferBuilder.cpp.
References geos::operation::buffer::BufferSubgraph::compareTo().
Referenced by geos::operation::buffer::BufferBuilder::createSubgraphs(), and geos::operation::buffer::BufferSubgraph::getDirectedEdges().
{
   if (first->compareTo(second)>0)
     return true;
   else
     return false;
 }
std::ostream& geos::operation::buffer::operator<< (std::ostream & os, const OffsetSegmentString & lst) inline
Definition at line 178 of file OffsetSegmentString.h.
References geos::operation::buffer::OffsetSegmentString::ptList.
 {
   if ( lst.ptList )
   {
     os << *(lst.ptList);
   }
   else
   {
     os << "empty (consumed?)";
   }
   return os;
 }
std::ostream & geos::operation::buffer::operator<< (std::ostream & os, const BufferSubgraph & bs)
Definition at line 338 of file BufferSubgraph.cpp.
References geos::operation::buffer::BufferSubgraph::dirEdgeList, and geos::operation::buffer::BufferSubgraph::nodes.
 {
   os << "BufferSubgraph[" << &bs << "] "
      << bs.nodes.size() << " nodes, "
      << bs.dirEdgeList.size() << " directed edges" << std::endl;
   for (size_t i=0, n=bs.nodes.size(); i<n; i++)
     os << "  Node " << i << ": " << *(bs.nodes[i]) << std::endl;
   for (size_t i=0, n=bs.dirEdgeList.size(); i<n; i++)
   {
     os << "  DirEdge " << i << ": " << std::endl
        << bs.dirEdgeList[i]->printEdge() << std::endl;
   }
   return os;
 }