GEOS: geos::planargraph Namespace Reference
geos::planargraph Namespace Reference
Contains classes to implement a planar graph data structure.
Namespaces
algorithm
Planargraph algorithms.
Classes
class DirectedEdge
Represents a directed edge in a PlanarGraph.
class DirectedEdgeStar
A sorted collection of DirectedEdge which leave a Node in a PlanarGraph.
class Edge
Represents an undirected edge of a PlanarGraph.
class GraphComponent
The base class for all graph component classes.
class Node
A node in a PlanarGraph is a location where 0 or more Edge meet.
class NodeMap
A map of Node, indexed by the coordinate of the node.
class PlanarGraph
Represents a directed graph which is embeddable in a planar surface.
class Subgraph
A subgraph of a PlanarGraph.
Functions
std::ostream & operator<< (std::ostream &, const DirectedEdge &)
Output operator.
bool pdeLessThan (DirectedEdge *first, DirectedEdge *second)
Strict Weak comparator function for containers.
std::ostream & operator<< (std::ostream &os, const Edge &n)
Print a Edge.
std::ostream & operator<< (std::ostream &os, const Node &n)
Print a Node.
template<typename T >
void find_and_erase (T what, vector< T > &where)
Detailed Description
Contains classes to implement a planar graph data structure.
Function Documentation
template<typename T > void geos::planargraph::find_and_erase (T what, vector< T > & where)
Definition at line 37 of file PlanarGraph.cpp.
Referenced by geos::planargraph::PlanarGraph::remove().
{
   if (!what) return;
   where.erase(std::remove(where.begin(), where.end(), what), where.end());
 }
std::ostream & geos::planargraph::operator<< (std::ostream & os, const Node & n)
Print a Node.
Definition at line 55 of file Node.cpp.
References geos::planargraph::Node::getDegree(), geos::planargraph::GraphComponent::isMarked(), geos::planargraph::GraphComponent::isVisited(), and geos::planargraph::Node::pt.
{
   os << "Node " << n.pt << " with degree " << n.getDegree();
   if ( n.isMarked() ) os << " Marked ";
   if ( n.isVisited() ) os << " Visited ";
   return os;
 }
std::ostream & geos::planargraph::operator<< (std::ostream & os, const Edge & n)
Print a Edge.
Definition at line 82 of file Edge.cpp.
References geos::planargraph::GraphComponent::isMarked(), and geos::planargraph::GraphComponent::isVisited().
{
   os << "Edge ";
   if ( n.isMarked() ) os << " Marked ";
   if ( n.isVisited() ) os << " Visited ";
   return os;
 }
std::ostream & geos::planargraph::operator<< (std::ostream & s, const DirectedEdge & de)
Output operator.
Definition at line 175 of file DirectedEdge.cpp.
References geos::planargraph::DirectedEdge::angle, geos::planargraph::DirectedEdge::p0, geos::planargraph::DirectedEdge::p1, and geos::planargraph::DirectedEdge::quadrant.
Referenced by geos::planargraph::Edge::Edge(), and geos::planargraph::Node::getIndex().
 {
   s << typeid(de).name() << ": " << de.p0 << " - " << de.p1;
   s << " " << de.quadrant << ":" << de.angle;
   return s;
 }
bool geos::planargraph::pdeLessThan (DirectedEdge * first, DirectedEdge * second)
Strict Weak comparator function for containers.
Definition at line 103 of file DirectedEdgeStar.cpp.
References geos::planargraph::DirectedEdge::compareTo().
Referenced by geos::planargraph::DirectedEdgeStar::sortEdges().
 {
   if (first->compareTo(second)<0)
     return true;
   else
     return false;
 }