GEOS: geos::geomgraph Namespace Reference
geos::geomgraph Namespace Reference
Contains classes that implement topology graphs.
Namespaces
index
Classes
class Depth
class DirectedEdge
A directed EdgeEnd.
class DirectedEdgeStar
A DirectedEdgeStar is an ordered list of outgoing DirectedEdges around a node.
class Edge
class EdgeEnd
Models the end of an edge incident on a node.
struct EdgeEndLT
class EdgeEndStar
A EdgeEndStar is an ordered list of EdgeEnds around a node.
class EdgeIntersection
struct EdgeIntersectionLessThen
class EdgeIntersectionList
class EdgeList
class EdgeNodingValidator
Validates that a collection of SegmentStrings is correctly noded.
class EdgeRing
class GeometryGraph
class GraphComponent
A GraphComponent is the parent class for the objects' that form a graph.
class Label
A Label indicates the topological relationship of a component of a topology graph to a given Geometry. This class supports labels for relationships to two Geometrys, which is sufficient for algorithms for binary operations.
class Node
class NodeFactory
class NodeMap
class PlanarGraph
Represents a directed graph which is embeddable in a planar surface.
class Position
class TopologyLocation
A TopologyLocation is the labelling of a GraphComponent's topological relationship to a single Geometry.
Functions
std::ostream & operator<< (std::ostream &os, const Edge &e)
std::ostream & operator<< (std::ostream &os, const EdgeEnd &ee)
std::ostream & operator<< (std::ostream &os, const EdgeEndStar &es)
std::ostream & operator<< (std::ostream &os, const EdgeIntersectionList &e)
std::ostream & operator<< (std::ostream &os, const EdgeList &el)
std::ostream & operator<< (std::ostream &os, const EdgeRing &er)
template<class T , class C >
void collect_intersecting_edges (const Envelope *env, T start, T end, C &to)
std::ostream & operator<< (std::ostream &os, const Label &l)
std::ostream & operator<< (std::ostream &os, const Node &node)
std::ostream & operator<< (std::ostream &os, const TopologyLocation &tl)
bool operator== (const Edge &a, const Edge &b)
bool operator< (const EdgeIntersection &ei1, const EdgeIntersection &ei2)
Strict weak ordering operator for EdgeIntersection.
std::ostream & operator<< (std::ostream &os, const EdgeIntersection &e)
Output operator.
Detailed Description
Contains classes that implement topology graphs.
The Java Topology Suite (JTS) is a Java API that implements a core set of spatial data operations using an explicit precision model and robust geometric algorithms. JTS is int ended to be used in the development of applications that support the validation, cleaning, integration and querying of spatial datasets.
JTS attempts to implement the OpenGIS Simple Features Specification (SFS) as accurately as possible. In some cases the SFS is unclear or omits a specification; in this case JTS attempts to choose a reasonable and consistent alternative. Differences from and elaborations of the SFS are documented in this specification.
Package Specification
Java Topology Suite Technical Specifications
OpenGIS Simple Features Specification for SQL
Function Documentation
template<class T , class C > void geos::geomgraph::collect_intersecting_edges (const Envelope * env, T start, T end, C & to)
Definition at line 352 of file GeometryGraph.cpp.
References geos::geomgraph::Edge::getEnvelope(), and geos::geom::Envelope::intersects().
Referenced by geos::geomgraph::GeometryGraph::computeEdgeIntersections(), and geos::geomgraph::GeometryGraph::computeSelfNodes().
 {
   for (T i=start; i != end; ++i)
   {
     Edge *e = *i;
     if ( e->getEnvelope()->intersects(env) ) to.push_back(e);
   }
 }
bool geos::geomgraph::operator< (const EdgeIntersection & ei1, const EdgeIntersection & ei2) inline
Strict weak ordering operator for EdgeIntersection.
This is the C++ equivalent of JTS's compareTo
Definition at line 84 of file EdgeIntersection.h.
References geos::geomgraph::EdgeIntersection::dist, and geos::geomgraph::EdgeIntersection::segmentIndex.
 {
     if ( ei1.segmentIndex < ei2.segmentIndex ) return true;
     if ( ei1.segmentIndex == ei2.segmentIndex )
     {
       if ( ei1.dist < ei2.dist ) return true;
       // TODO: check if the Coordinate matches, or this will
       //       be a robustness issue in computin distance
       //       See http://trac.osgeo.org/geos/ticket/350
     }
     return false;
 }
std::ostream& geos::geomgraph::operator<< (std::ostream & os, const EdgeIntersection & e) inline
Output operator.
Definition at line 108 of file EdgeIntersection.h.
References geos::geomgraph::EdgeIntersection::coord, geos::geomgraph::EdgeIntersection::dist, and geos::geomgraph::EdgeIntersection::segmentIndex.
 {
   os << e.coord << " seg # = " << e.segmentIndex << " dist = " << e.dist;
   return os;
 }
std::ostream & geos::geomgraph::operator<< (std::ostream & os, const EdgeList & el)
Definition at line 136 of file EdgeList.cpp.
References geos::geomgraph::EdgeList::edges.
 {
   os << "EdgeList: " << std::endl;
   for(std::size_t j=0, s=el.edges.size(); j<s; ++j)
   {
           Edge *e=el.edges[j];
     os << "  " << *e << std::endl;
   }
   return os;
 }
std::ostream & geos::geomgraph::operator<< (std::ostream & os, const EdgeIntersectionList & e)
Definition at line 189 of file EdgeIntersectionList.cpp.
References geos::geomgraph::EdgeIntersectionList::begin(), and geos::geomgraph::EdgeIntersectionList::end().
 {
   os << "Intersections:" << std::endl;
   EdgeIntersectionList::const_iterator it=e.begin(), endIt=e.end();
   for (; it!=endIt; ++it) {
     EdgeIntersection *ei=*it;
     os << *ei << endl;
   }
   return os;
 }
std::ostream & geos::geomgraph::operator<< (std::ostream & os, const EdgeEnd & ee)
Definition at line 203 of file EdgeEnd.cpp.
References geos::geomgraph::EdgeEnd::dx, geos::geomgraph::EdgeEnd::dy, geos::geomgraph::EdgeEnd::label, geos::geomgraph::EdgeEnd::p0, geos::geomgraph::EdgeEnd::p1, and geos::geomgraph::EdgeEnd::quadrant.
 {
   os << "EdgeEnd: ";
   os << ee.p0;
   os << " - ";
   os << ee.p1;
   os << " ";
   os << ee.quadrant << ":" << std::atan2(ee.dy, ee.dx);
   os << "  ";
   os << ee.label;
   return os;
 }
std::ostream & geos::geomgraph::operator<< (std::ostream & os, const TopologyLocation & tl)
Definition at line 227 of file TopologyLocation.cpp.
References geos::geomgraph::Position::LEFT, geos::geomgraph::TopologyLocation::location, geos::geomgraph::Position::ON, and geos::geomgraph::Position::RIGHT.
 {
   if (tl.location.size()>1) os << Location::toLocationSymbol(tl.location[Position::LEFT]);
   os << Location::toLocationSymbol(tl.location[Position::ON]);
   if (tl.location.size()>1) os << Location::toLocationSymbol(tl.location[Position::RIGHT]);
   return os;
 }
std::ostream & geos::geomgraph::operator<< (std::ostream & os, const Label & l)
Definition at line 267 of file Label.cpp.
References geos::geomgraph::Label::elt.
 {
   os << "A:"
      << l.elt[0]
      << " B:"
      << l.elt[1];
   return os;
 }
std::ostream & geos::geomgraph::operator<< (std::ostream & os, const Node & node)
Definition at line 277 of file Node.cpp.
References geos::geomgraph::Node::coord, and geos::geomgraph::GraphComponent::label.
 {
   os << "Node["<<&node<<"]" << std::endl
      << "  POINT(" << node.coord << ")" << std::endl
      << "  lbl: " << node.label;
   return os;
 }
std::ostream & geos::geomgraph::operator<< (std::ostream & os, const Edge & e)
Definition at line 305 of file Edge.cpp.
References geos::geomgraph::Edge::depthDelta, geos::geomgraph::GraphComponent::label, geos::geomgraph::Edge::name, and geos::geomgraph::Edge::pts.
 {
   os << "edge";
   if ( e.name != "" ) os << " " << e.name;
   os
      << "  LINESTRING"
      << *(e.pts)
      << "  " << e.label
      << "  " << e.depthDelta
      ;
   return os;
 }
std::ostream & geos::geomgraph::operator<< (std::ostream & os, const EdgeEndStar & es)
Definition at line 355 of file EdgeEndStar.cpp.
References geos::geomgraph::EdgeEndStar::begin(), geos::geomgraph::EdgeEndStar::end(), and geos::geomgraph::EdgeEndStar::getCoordinate().
 {
   os << "EdgeEndStar:   " << es.getCoordinate() << "\n";
   for (EdgeEndStar::const_iterator it=es.begin(), itEnd=es.end(); it!=itEnd; ++it)
   {
     const EdgeEnd *e=*it;
     assert(e);
     os << *e;
   }
   return os;
 }
std::ostream & geos::geomgraph::operator<< (std::ostream & os, const EdgeRing & er)
Definition at line 397 of file EdgeRing.cpp.
References geos::geomgraph::EdgeRing::pts.
 {
   os << "EdgeRing[" << &er << "]: "
      << std::endl
      << "Points: " << er.pts
      << std::endl;
   return os;
 }
bool geos::geomgraph::operator== (const Edge & a, const Edge & b) inline
Definition at line 246 of file Edge.h.
References geos::geomgraph::Edge::equals(), and geos::geom::operator<<().
{
   return a.equals(b);
 }