GEOS: GEOSContextHandle_HS Struct Reference
GEOSContextHandle_HS Struct Reference
Public Member Functions
GEOSContextHandle_HS ()
GEOSMessageHandler setNoticeHandler (GEOSMessageHandler nf)
GEOSMessageHandler setErrorHandler (GEOSMessageHandler nf)
GEOSMessageHandler_r setNoticeHandler (GEOSMessageHandler_r nf, void *userData)
GEOSMessageHandler_r setErrorHandler (GEOSMessageHandler_r ef, void *userData)
void NOTICE_MESSAGE (string fmt,...)
void ERROR_MESSAGE (string fmt,...)
Public Attributes
const GeometryFactory * geomFactory
char msgBuffer [1024]
GEOSMessageHandler noticeMessageOld
GEOSMessageHandler_r noticeMessageNew
void * noticeData
GEOSMessageHandler errorMessageOld
GEOSMessageHandler_r errorMessageNew
void * errorData
int WKBOutputDims
int WKBByteOrder
int initialized
Detailed Description
Definition at line 155 of file geos_ts_c.cpp.
Constructor & Destructor Documentation
GEOSContextHandle_HS::GEOSContextHandle_HS () inline
Definition at line 169 of file geos_ts_c.cpp.
References getMachineByteOrder().
       :
       geomFactory(0),
       noticeMessageOld(0),
       noticeMessageNew(0),
       noticeData(0),
       errorMessageOld(0),
       errorMessageNew(0),
       errorData(0)
     {
       memset(msgBuffer, 0, sizeof(msgBuffer));
       geomFactory = GeometryFactory::getDefaultInstance();
       WKBOutputDims = 2;
       WKBByteOrder = getMachineByteOrder();
       setNoticeHandler(NULL);
       setErrorHandler(NULL);
       initialized = 1;
     }
Member Function Documentation
void GEOSContextHandle_HS::ERROR_MESSAGE (string fmt, ...) inline
Definition at line 253 of file geos_ts_c.cpp.
Referenced by GEOS_setWKBOutputDims_r(), GEOSArea_r(), GEOSBoundary_r(), GEOSBuffer_r(), GEOSBufferParams_create_r(), GEOSBufferParams_setEndCapStyle_r(), GEOSBufferParams_setJoinStyle_r(), GEOSBufferParams_setMitreLimit_r(), GEOSBufferParams_setQuadrantSegments_r(), GEOSBufferParams_setSingleSided_r(), GEOSBufferWithParams_r(), GEOSBufferWithStyle_r(), GEOSClipByRect_r(), GEOSContains_r(), GEOSConvexHull_r(), GEOSCoordSeq_clone_r(), GEOSCoordSeq_create_r(), GEOSCoordSeq_destroy_r(), GEOSCoordSeq_getDimensions_r(), GEOSCoordSeq_getOrdinate_r(), GEOSCoordSeq_getSize_r(), GEOSCoordSeq_isCCW_r(), GEOSCoordSeq_setOrdinate_r(), GEOSCoveredBy_r(), GEOSCovers_r(), GEOSCrosses_r(), GEOSDelaunayTriangulation_r(), GEOSDifference_r(), GEOSDisjoint_r(), GEOSDistance_r(), GEOSDistanceIndexed_r(), GEOSEnvelope_r(), GEOSEquals_r(), GEOSEqualsExact_r(), GEOSFrechetDistance_r(), GEOSFrechetDistanceDensify_r(), GEOSGeom_clone_r(), GEOSGeom_createCollection_r(), GEOSGeom_createEmptyCollection_r(), GEOSGeom_createEmptyLineString_r(), GEOSGeom_createEmptyPoint_r(), GEOSGeom_createEmptyPolygon_r(), GEOSGeom_createLinearRing_r(), GEOSGeom_createLineString_r(), GEOSGeom_createPoint_r(), GEOSGeom_createPolygon_r(), GEOSGeom_destroy_r(), GEOSGeom_extractUniquePoints_r(), GEOSGeom_getCoordinateDimension_r(), GEOSGeom_getCoordSeq_r(), GEOSGeom_getDimensions_r(), GEOSGeom_getPrecision_r(), GEOSGeom_getUserData_r(), GEOSGeom_getXMax_r(), GEOSGeom_getXMin_r(), GEOSGeom_getYMax_r(), GEOSGeom_getYMin_r(), GEOSGeom_setPrecision_r(), GEOSGeomFromHEX_buf_r(), GEOSGeomFromWKB_buf_r(), GEOSGeomFromWKT_r(), GEOSGeomGetEndPoint_r(), GEOSGeomGetLength_r(), GEOSGeomGetNumPoints_r(), GEOSGeomGetPointN_r(), GEOSGeomGetStartPoint_r(), GEOSGeomGetX_r(), GEOSGeomGetY_r(), GEOSGeomGetZ_r(), GEOSGeomToHEX_buf_r(), GEOSGeomToWKB_buf_r(), GEOSGeomToWKT_r(), GEOSGeomType_r(), GEOSGeomTypeId_r(), GEOSGetCentroid_r(), GEOSGetExteriorRing_r(), GEOSGetGeometryN_r(), GEOSGetInteriorRingN_r(), GEOSGetNumCoordinates_r(), GEOSGetNumGeometries_r(), GEOSGetNumInteriorRings_r(), GEOSGetSRID_r(), GEOSHausdorffDistance_r(), GEOSHausdorffDistanceDensify_r(), GEOSInterpolate_r(), GEOSIntersection_r(), GEOSIntersects_r(), GEOSisClosed_r(), GEOSisEmpty_r(), GEOSisRing_r(), GEOSisSimple_r(), GEOSisValid_r(), GEOSisValidDetail_r(), GEOSisValidReason_r(), GEOSLength_r(), GEOSLineMerge_r(), GEOSMinimumClearance_r(), GEOSMinimumClearanceLine_r(), GEOSMinimumRotatedRectangle_r(), GEOSMinimumWidth_r(), GEOSNearestPoints_r(), GEOSNode_r(), GEOSNormalize_r(), GEOSOffsetCurve_r(), GEOSOrientationIndex_r(), GEOSOverlaps_r(), GEOSPointOnSurface_r(), GEOSPolygonize_full_r(), GEOSPolygonize_r(), GEOSPolygonizer_getCutEdges_r(), GEOSPrepare_r(), GEOSPreparedContains_r(), GEOSPreparedContainsProperly_r(), GEOSPreparedCoveredBy_r(), GEOSPreparedCovers_r(), GEOSPreparedCrosses_r(), GEOSPreparedDisjoint_r(), GEOSPreparedGeom_destroy_r(), GEOSPreparedIntersects_r(), GEOSPreparedOverlaps_r(), GEOSPreparedTouches_r(), GEOSPreparedWithin_r(), GEOSProject_r(), GEOSRelate_r(), GEOSRelateBoundaryNodeRule_r(), GEOSRelatePattern_r(), GEOSRelatePatternMatch_r(), GEOSReverse_r(), GEOSSegmentIntersection_r(), GEOSSharedPaths_r(), GEOSSimplify_r(), GEOSSingleSidedBuffer_r(), GEOSSnap_r(), GEOSSTRtree_create_r(), GEOSSTRtree_destroy_r(), GEOSSTRtree_insert_r(), GEOSSTRtree_iterate_r(), GEOSSTRtree_nearest_generic_r(), GEOSSTRtree_query_r(), GEOSSTRtree_remove_r(), GEOSSymDifference_r(), GEOSTopologyPreserveSimplify_r(), GEOSTouches_r(), GEOSUnaryUnion_r(), GEOSUnion_r(), GEOSUnionCascaded_r(), GEOSVoronoiDiagram_r(), GEOSWithin_r(), GEOSWKBReader_create_r(), GEOSWKBReader_destroy_r(), GEOSWKBReader_read_r(), GEOSWKBReader_readHEX_r(), GEOSWKBWriter_create_r(), GEOSWKBWriter_destroy_r(), GEOSWKBWriter_getByteOrder_r(), GEOSWKBWriter_getIncludeSRID_r(), GEOSWKBWriter_getOutputDimension_r(), GEOSWKBWriter_setByteOrder_r(), GEOSWKBWriter_setIncludeSRID_r(), GEOSWKBWriter_setOutputDimension_r(), GEOSWKBWriter_write_r(), GEOSWKBWriter_writeHEX_r(), GEOSWKTReader_create_r(), GEOSWKTReader_destroy_r(), GEOSWKTReader_read_r(), GEOSWKTWriter_create_r(), GEOSWKTWriter_destroy_r(), GEOSWKTWriter_getOutputDimension_r(), GEOSWKTWriter_setOutputDimension_r(), and GEOSWKTWriter_write_r().
     {
       if (NULL == errorMessageOld && NULL == errorMessageNew) {
         return;
       }
       va_list args;
       va_start(args, fmt);
       int result = vsnprintf(msgBuffer, sizeof(msgBuffer) - 1, fmt.c_str(), args);
       va_end(args);
       if (result > 0) {
         if (errorMessageOld) {
           errorMessageOld("%s", msgBuffer);
         } else {
           errorMessageNew(msgBuffer, errorData);
         }
       }
     }
void GEOSContextHandle_HS::NOTICE_MESSAGE (string fmt, ...) inline
Definition at line 232 of file geos_ts_c.cpp.
Referenced by GEOSClipByRect_r(), GEOSGeom_createCollection_r(), GEOSGeom_createEmptyCollection_r(), GEOSisValid_r(), GEOSLineMerge_r(), GEOSNode_r(), GEOSPolygonize_full_r(), GEOSPolygonize_r(), GEOSPolygonizer_getCutEdges_r(), GEOSUnaryUnion_r(), and GEOSUnion_r().
     {
       if (NULL == noticeMessageOld && NULL == noticeMessageNew) {
         return;
       }
       va_list args;
       va_start(args, fmt);
       int result = vsnprintf(msgBuffer, sizeof(msgBuffer) - 1, fmt.c_str(), args);
       va_end(args);
       if (result > 0) {
         if (noticeMessageOld) {
           noticeMessageOld("%s", msgBuffer);
         } else {
           noticeMessageNew(msgBuffer, noticeData);
         }
       }
     }
GEOSMessageHandler GEOSContextHandle_HS::setErrorHandler (GEOSMessageHandler nf) inline
Definition at line 200 of file geos_ts_c.cpp.
Referenced by GEOSContext_setErrorHandler_r(), and GEOSContext_setErrorMessageHandler_r().
     {
         GEOSMessageHandler f = errorMessageOld;
         errorMessageOld = nf;
         errorMessageNew = NULL;
         errorData = NULL;
         return f;
     }
GEOSMessageHandler_r GEOSContextHandle_HS::setErrorHandler (GEOSMessageHandler_r ef, void * userData) inline
Definition at line 221 of file geos_ts_c.cpp.
     {
         GEOSMessageHandler_r f = errorMessageNew;
         errorMessageOld = NULL;
         errorMessageNew = ef;
         errorData = userData;
         return f;
     }
GEOSMessageHandler GEOSContextHandle_HS::setNoticeHandler (GEOSMessageHandler nf) inline
Definition at line 189 of file geos_ts_c.cpp.
Referenced by GEOSContext_setNoticeHandler_r(), and GEOSContext_setNoticeMessageHandler_r().
     {
         GEOSMessageHandler f = noticeMessageOld;
         noticeMessageOld = nf;
         noticeMessageNew = NULL;
         noticeData = NULL;
         return f;
     }
GEOSMessageHandler_r GEOSContextHandle_HS::setNoticeHandler (GEOSMessageHandler_r nf, void * userData) inline
Definition at line 211 of file geos_ts_c.cpp.
{
         GEOSMessageHandler_r f = noticeMessageNew;
         noticeMessageOld = NULL;
         noticeMessageNew = nf;
         noticeData = userData;
         return f;
     }
Member Data Documentation
void* GEOSContextHandle_HS::errorData
Definition at line 164 of file geos_ts_c.cpp.
GEOSMessageHandler_r GEOSContextHandle_HS::errorMessageNew
Definition at line 163 of file geos_ts_c.cpp.
GEOSMessageHandler GEOSContextHandle_HS::errorMessageOld
Definition at line 162 of file geos_ts_c.cpp.
const GeometryFactory* GEOSContextHandle_HS::geomFactory
Definition at line 157 of file geos_ts_c.cpp.
Referenced by GEOSCoordSeq_create_r(), GEOSGeom_createCollection_r(), GEOSGeom_createEmptyCollection_r(), GEOSGeom_createEmptyLineString_r(), GEOSGeom_createEmptyPoint_r(), GEOSGeom_createEmptyPolygon_r(), GEOSGeom_createLinearRing_r(), GEOSGeom_createLineString_r(), GEOSGeom_createPoint_r(), GEOSGeom_createPolygon_r(), GEOSGeomFromHEX_buf_r(), GEOSGeomFromWKB_buf_r(), GEOSGeomFromWKT_r(), GEOSGetCentroid_r(), GEOSInterpolate_r(), GEOSisValidDetail_r(), GEOSLineMerge_r(), GEOSPointOnSurface_r(), GEOSPolygonize_full_r(), GEOSPolygonize_r(), GEOSPolygonizer_getCutEdges_r(), GEOSWKBReader_create_r(), and GEOSWKTReader_create_r().
int GEOSContextHandle_HS::initialized
Definition at line 167 of file geos_ts_c.cpp.
Referenced by GEOS_getWKBByteOrder_r(), GEOS_getWKBOutputDims_r(), GEOS_setWKBByteOrder_r(), GEOS_setWKBOutputDims_r(), GEOSArea_r(), GEOSBoundary_r(), GEOSBuffer_r(), GEOSBufferParams_create_r(), GEOSBufferParams_setEndCapStyle_r(), GEOSBufferParams_setJoinStyle_r(), GEOSBufferParams_setMitreLimit_r(), GEOSBufferParams_setQuadrantSegments_r(), GEOSBufferParams_setSingleSided_r(), GEOSBufferWithParams_r(), GEOSBufferWithStyle_r(), GEOSClipByRect_r(), GEOSContains_r(), GEOSContext_setErrorHandler_r(), GEOSContext_setErrorMessageHandler_r(), GEOSContext_setNoticeHandler_r(), GEOSContext_setNoticeMessageHandler_r(), GEOSConvexHull_r(), GEOSCoordSeq_clone_r(), GEOSCoordSeq_create_r(), GEOSCoordSeq_destroy_r(), GEOSCoordSeq_getDimensions_r(), GEOSCoordSeq_getOrdinate_r(), GEOSCoordSeq_getSize_r(), GEOSCoordSeq_isCCW_r(), GEOSCoordSeq_setOrdinate_r(), GEOSCoveredBy_r(), GEOSCovers_r(), GEOSCrosses_r(), GEOSDelaunayTriangulation_r(), GEOSDifference_r(), GEOSDisjoint_r(), GEOSDistance_r(), GEOSDistanceIndexed_r(), GEOSEnvelope_r(), GEOSEquals_r(), GEOSEqualsExact_r(), GEOSFrechetDistance_r(), GEOSFrechetDistanceDensify_r(), GEOSGeom_clone_r(), GEOSGeom_createCollection_r(), GEOSGeom_createEmptyCollection_r(), GEOSGeom_createEmptyLineString_r(), GEOSGeom_createEmptyPoint_r(), GEOSGeom_createEmptyPolygon_r(), GEOSGeom_createLinearRing_r(), GEOSGeom_createLineString_r(), GEOSGeom_createPoint_r(), GEOSGeom_createPolygon_r(), GEOSGeom_destroy_r(), GEOSGeom_extractUniquePoints_r(), GEOSGeom_getCoordinateDimension_r(), GEOSGeom_getCoordSeq_r(), GEOSGeom_getDimensions_r(), GEOSGeom_getPrecision_r(), GEOSGeom_getUserData_r(), GEOSGeom_getXMax_r(), GEOSGeom_getXMin_r(), GEOSGeom_getYMax_r(), GEOSGeom_getYMin_r(), GEOSGeom_setPrecision_r(), GEOSGeom_setUserData_r(), GEOSGeomFromHEX_buf_r(), GEOSGeomFromWKB_buf_r(), GEOSGeomFromWKT_r(), GEOSGeomGetEndPoint_r(), GEOSGeomGetLength_r(), GEOSGeomGetNumPoints_r(), GEOSGeomGetPointN_r(), GEOSGeomGetStartPoint_r(), GEOSGeomGetX_r(), GEOSGeomGetY_r(), GEOSGeomGetZ_r(), GEOSGeomToHEX_buf_r(), GEOSGeomToWKB_buf_r(), GEOSGeomToWKT_r(), GEOSGeomType_r(), GEOSGeomTypeId_r(), GEOSGetCentroid_r(), GEOSGetExteriorRing_r(), GEOSGetGeometryN_r(), GEOSGetInteriorRingN_r(), GEOSGetNumCoordinates_r(), GEOSGetNumGeometries_r(), GEOSGetNumInteriorRings_r(), GEOSGetSRID_r(), GEOSHasZ_r(), GEOSHausdorffDistance_r(), GEOSHausdorffDistanceDensify_r(), GEOSInterpolate_r(), GEOSIntersection_r(), GEOSIntersects_r(), GEOSisClosed_r(), GEOSisEmpty_r(), GEOSisRing_r(), GEOSisSimple_r(), GEOSisValid_r(), GEOSisValidDetail_r(), GEOSisValidReason_r(), GEOSLength_r(), GEOSLineMerge_r(), GEOSMinimumClearance_r(), GEOSMinimumClearanceLine_r(), GEOSMinimumRotatedRectangle_r(), GEOSMinimumWidth_r(), GEOSNearestPoints_r(), GEOSNode_r(), GEOSNormalize_r(), GEOSOffsetCurve_r(), GEOSOrientationIndex_r(), GEOSOverlaps_r(), GEOSPointOnSurface_r(), GEOSPolygonize_full_r(), GEOSPolygonize_r(), GEOSPolygonizer_getCutEdges_r(), GEOSPrepare_r(), GEOSPreparedContains_r(), GEOSPreparedContainsProperly_r(), GEOSPreparedCoveredBy_r(), GEOSPreparedCovers_r(), GEOSPreparedCrosses_r(), GEOSPreparedDisjoint_r(), GEOSPreparedGeom_destroy_r(), GEOSPreparedIntersects_r(), GEOSPreparedOverlaps_r(), GEOSPreparedTouches_r(), GEOSPreparedWithin_r(), GEOSProject_r(), GEOSRelate_r(), GEOSRelateBoundaryNodeRule_r(), GEOSRelatePattern_r(), GEOSRelatePatternMatch_r(), GEOSReverse_r(), GEOSSegmentIntersection_r(), GEOSSetSRID_r(), GEOSSharedPaths_r(), GEOSSimplify_r(), GEOSSingleSidedBuffer_r(), GEOSSnap_r(), GEOSSTRtree_create_r(), GEOSSTRtree_destroy_r(), GEOSSTRtree_insert_r(), GEOSSTRtree_iterate_r(), GEOSSTRtree_nearest_generic_r(), GEOSSTRtree_query_r(), GEOSSTRtree_remove_r(), GEOSSymDifference_r(), GEOSTopologyPreserveSimplify_r(), GEOSTouches_r(), GEOSUnaryUnion_r(), GEOSUnion_r(), GEOSUnionCascaded_r(), GEOSVoronoiDiagram_r(), GEOSWithin_r(), GEOSWKBReader_create_r(), GEOSWKBReader_destroy_r(), GEOSWKBReader_read_r(), GEOSWKBReader_readHEX_r(), GEOSWKBWriter_create_r(), GEOSWKBWriter_destroy_r(), GEOSWKBWriter_getByteOrder_r(), GEOSWKBWriter_getIncludeSRID_r(), GEOSWKBWriter_getOutputDimension_r(), GEOSWKBWriter_setByteOrder_r(), GEOSWKBWriter_setIncludeSRID_r(), GEOSWKBWriter_setOutputDimension_r(), GEOSWKBWriter_write_r(), GEOSWKBWriter_writeHEX_r(), GEOSWKTReader_create_r(), GEOSWKTReader_destroy_r(), GEOSWKTReader_read_r(), GEOSWKTWriter_create_r(), GEOSWKTWriter_destroy_r(), GEOSWKTWriter_getOutputDimension_r(), GEOSWKTWriter_setOld3D_r(), GEOSWKTWriter_setOutputDimension_r(), GEOSWKTWriter_setRoundingPrecision_r(), GEOSWKTWriter_setTrim_r(), and GEOSWKTWriter_write_r().
char GEOSContextHandle_HS::msgBuffer[1024]
Definition at line 158 of file geos_ts_c.cpp.
void* GEOSContextHandle_HS::noticeData
Definition at line 161 of file geos_ts_c.cpp.
GEOSMessageHandler_r GEOSContextHandle_HS::noticeMessageNew
Definition at line 160 of file geos_ts_c.cpp.
GEOSMessageHandler GEOSContextHandle_HS::noticeMessageOld
Definition at line 159 of file geos_ts_c.cpp.
int GEOSContextHandle_HS::WKBByteOrder
Definition at line 166 of file geos_ts_c.cpp.
Referenced by GEOS_getWKBByteOrder_r(), GEOS_setWKBByteOrder_r(), GEOSGeomToHEX_buf_r(), and GEOSGeomToWKB_buf_r().
int GEOSContextHandle_HS::WKBOutputDims
Definition at line 165 of file geos_ts_c.cpp.
Referenced by GEOS_getWKBOutputDims_r(), GEOS_setWKBOutputDims_r(), GEOSGeomToHEX_buf_r(), and GEOSGeomToWKB_buf_r().
The documentation for this struct was generated from the following file:
/home/vicky/potree/geos/vicky/capi/geos_ts_c.cpp