GEOS: geos::geom::util::GeometryExtracter::Extracter< ComponentType, TargetContainer > Struct Template Reference
geos::geom::util::GeometryExtracter::Extracter< ComponentType, TargetContainer > Struct Template Reference
Public Member Functions
Extracter (TargetContainer &comps)
void filter_ro (const Geometry *geom) override
Extracter (const Extracter &other)
Extracter & operator= (const Extracter &rhs)
virtual void filter_rw (Geometry *)
Public Attributes
TargetContainer & comps_
Detailed Description
template<class ComponentType, class TargetContainer>
struct geos::geom::util::GeometryExtracter::Extracter< ComponentType, TargetContainer >
Definition at line 66 of file GeometryExtracter.h.
Constructor & Destructor Documentation
template<class ComponentType, class TargetContainer> geos::geom::util::GeometryExtracter::Extracter< ComponentType, TargetContainer >::Extracter (TargetContainer & comps) inline
Constructs a filter with a list in which to store the elements found.
Parameters
comps the container to extract into (will push_back to it)
Definition at line 73 of file GeometryExtracter.h.
 : comps_(comps) {}
template<class ComponentType, class TargetContainer> geos::geom::util::GeometryExtracter::Extracter< ComponentType, TargetContainer >::Extracter (const Extracter< ComponentType, TargetContainer > & other)
Member Function Documentation
template<class ComponentType, class TargetContainer> void geos::geom::util::GeometryExtracter::Extracter< ComponentType, TargetContainer >::filter_ro (const Geometry * geom) inline override virtual
Reimplemented from geos::geom::GeometryFilter.
Definition at line 77 of file GeometryExtracter.h.
     {
       if ( const ComponentType* c = dynamic_cast<const ComponentType*>(geom) ) {
         comps_.push_back(c);
       }
     }
virtual void geos::geom::GeometryFilter::filter_rw (Geometry *) inline virtual inherited
Reimplemented in geos::operation::distance::ConnectedElementLocationFilter, geos::geom::util::PolygonExtracter, and geos::geom::util::PointExtracter.
Definition at line 61 of file GeometryFilter.h.
Referenced by geos::geom::Point::apply_rw(), geos::geom::Polygon::apply_rw(), geos::geom::GeometryCollection::apply_rw(), geos::geom::LineString::apply_rw(), and geos::geom::Geometry::apply_rw().
 { assert(0); }
template<class ComponentType, class TargetContainer> Extracter& geos::geom::util::GeometryExtracter::Extracter< ComponentType, TargetContainer >::operator= (const Extracter< ComponentType, TargetContainer > & rhs)
Member Data Documentation
template<class ComponentType, class TargetContainer> TargetContainer& geos::geom::util::GeometryExtracter::Extracter< ComponentType, TargetContainer >::comps_
Definition at line 75 of file GeometryExtracter.h.
The documentation for this struct was generated from the following file:
/home/vicky/potree/geos/vicky/include/geos/geom/util/GeometryExtracter.h