GEOS: geos::operation::linemerge::LMGeometryComponentFilter Struct Reference
geos::operation::linemerge::LMGeometryComponentFilter Struct Reference
Public Member Functions
LMGeometryComponentFilter (LineMerger *newLm)
void filter (const Geometry *geom)
virtual void filter_rw (Geometry *geom)
virtual void filter_ro (const Geometry *geom)
Public Attributes
LineMerger * lm
Detailed Description
Definition at line 69 of file LineMerger.cpp.
Constructor & Destructor Documentation
geos::operation::linemerge::LMGeometryComponentFilter::LMGeometryComponentFilter (LineMerger * newLm) inline
Definition at line 72 of file LineMerger.cpp.
 : lm(newLm) {}
Member Function Documentation
void geos::operation::linemerge::LMGeometryComponentFilter::filter (const Geometry * geom) inline
Definition at line 74 of file LineMerger.cpp.
References geos::operation::linemerge::LineMerger::add().
{
     const LineString *ls = dynamic_cast<const LineString *>(geom);
     if ( ls ) lm->add(ls);
   }
void geos::geom::GeometryComponentFilter::filter_ro (const Geometry * geom) virtual inherited
Reimplemented in geos::operation::polygonize::Polygonizer::LineStringAdder, geos::geom::util::LinearComponentExtracter, and geos::geom::util::ComponentCoordinateExtracter.
Definition at line 31 of file GeometryComponentFilter.cpp.
References geos::ignore_unused_variable_warning().
Referenced by geos::geom::Point::apply_ro(), geos::geom::GeometryCollection::apply_ro(), geos::geom::Polygon::apply_ro(), geos::geom::LineString::apply_ro(), and geos::geom::Geometry::apply_ro().
 {
   ::geos::ignore_unused_variable_warning(geom);
   assert(0);
 }
void geos::geom::GeometryComponentFilter::filter_rw (Geometry * geom) virtual inherited
Performs an operation with or on geom.
Parameters
geom a Geometry to which the filter is applied.
Reimplemented in geos::geom::Geometry::GeometryChangedFilter, geos::geom::util::LinearComponentExtracter, and geos::geom::util::ComponentCoordinateExtracter.
Definition at line 25 of file GeometryComponentFilter.cpp.
References geos::ignore_unused_variable_warning().
Referenced by geos::geom::Point::apply_rw(), geos::geom::GeometryCollection::apply_rw(), geos::geom::Polygon::apply_rw(), geos::geom::LineString::apply_rw(), and geos::geom::Geometry::apply_rw().
 {
   ::geos::ignore_unused_variable_warning(geom);
   assert(0);
 }
Member Data Documentation
LineMerger* geos::operation::linemerge::LMGeometryComponentFilter::lm
Definition at line 70 of file LineMerger.cpp.
The documentation for this struct was generated from the following file:
/home/vicky/potree/geos/vicky/src/operation/linemerge/LineMerger.cpp