GEOS: geos::operation::overlay::PointCoveredByAny Struct Reference
geos::operation::overlay::PointCoveredByAny Struct Reference
Public Member Functions
PointCoveredByAny (const vector< const Geometry * > &nGeoms)
void filter_ro (const Coordinate *coord) override
virtual void filter_rw (Coordinate *) const
Public Attributes
const vector< const Geometry * > & geoms
PointLocator locator
Private Member Functions
PointCoveredByAny (const PointCoveredByAny &other)=delete
PointCoveredByAny & operator= (const PointCoveredByAny &rhs)=delete
Detailed Description
Definition at line 956 of file OverlayOp.cpp.
Constructor & Destructor Documentation
geos::operation::overlay::PointCoveredByAny::PointCoveredByAny (const vector< const Geometry * > & nGeoms) inline
Definition at line 960 of file OverlayOp.cpp.
     : geoms(nGeoms)
   {}
geos::operation::overlay::PointCoveredByAny::PointCoveredByAny (const PointCoveredByAny & other) private delete
Member Function Documentation
void geos::operation::overlay::PointCoveredByAny::filter_ro (const Coordinate *) inline override virtual
Performs an operation with coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented from geos::geom::CoordinateFilter.
Definition at line 964 of file OverlayOp.cpp.
References geos::algorithm::PointLocator::locate().
   {
     for (size_t i=0, n=geoms.size(); i<n; ++i)
     {
       int loc = locator.locate(*coord, geoms[i]);
       if ( loc == Location::INTERIOR ||
         loc == Location::BOUNDARY )
       {
         return;
       }
     }
     throw util::TopologyException("Obviously wrong result: "
       "A point on first geom boundary isn't covered "
       "by either result or second geom");
   }
virtual void geos::geom::CoordinateFilter::filter_rw (Coordinate *) const inline virtual inherited
Performs an operation on coord.
Parameters
coord a Coordinate to which the filter is applied.
Reimplemented in geos::noding::ScaledNoder::ReScaler, geos::noding::ScaledNoder::Scaler, geos::precision::CommonCoordinateFilter, geos::operation::overlay::ElevationMatrixFilter, and geos::precision::Translater.
Definition at line 52 of file CoordinateFilter.h.
Referenced by geos::geom::CoordinateArraySequence::apply_rw(), and geos::geom::Point::apply_rw().
 { assert(0); }
PointCoveredByAny& geos::operation::overlay::PointCoveredByAny::operator= (const PointCoveredByAny & rhs) private delete
Member Data Documentation
const vector<const Geometry*>& geos::operation::overlay::PointCoveredByAny::geoms
Definition at line 958 of file OverlayOp.cpp.
PointLocator geos::operation::overlay::PointCoveredByAny::locator
Definition at line 959 of file OverlayOp.cpp.
The documentation for this struct was generated from the following file:
/home/vicky/potree/geos/vicky/src/operation/overlay/OverlayOp.cpp